### ISSUE TITLE
Rename project and elements

### ISSUE THREAD

**Issue by joshuaboniface** [jellyfin/jellyfin#1]
With this fork being named `jellyfin`, we'll need to differentiate this repo by renaming anything we reasonably can. This might just be the README for now, but long-term anything referencing Emby should be updated.

**Comment by anthonylavado** [comment]
I can work on at least the README. Ideally we’ll want to move a lot of it (the statements on why the project exists, etc) out to the Wiki. We’ll probably need to take out the screenshots too.

**Comment by anthonylavado** [comment]
@JustAMan - I’ll talk with @joshuaboniface on this too, but would a statement, followed by “Read more” with a link to the wiki be good?

I’m just thinking ahead to people that might come across this, so I would want to have a nice quick page that briefly tells them about the project, and how to get started.

Admittedly I’m not a master at this. You can see a README for a project I help maintain: https://github.com/mike-grant/haaska/blob/master/README.md

Here’s a good example from a semi-popular template:
https://gist.github.com/PurpleBooth/109311bb0361f32d87a2

**Comment by anthonylavado** [comment]
Linking here: there is some work in #6

**Comment by JustAMan** [comment]
I had a look at your readme and now I get your point. I think we can safelt move "motivation" to wiki leaving a link in readme. Ideally it might just be a paragraph about what is this project plus a few links for further reading.

**Comment by joshuaboniface** [comment]
I agree, my essay doesn't need to be in the README :laughing:

**Comment by joshuaboniface** [comment]
@nvllsvm 's PR #6 has been merged, which gets rid of the old Emby images and such from the README. I'm going to start splitting things out now to get the README condensed.

**Comment by joshuaboniface** [comment]
Suplemented by practical action in #25
