### ISSUE TITLE
[Issue]: Metadata retrieval broken

### ISSUE THREAD

**Issue by Tobls** [jellyfin/jellyfin#10009]
### Please describe your bug

When trying to identify a movie using the build-in feature I get to the selection of different hits from metadata providers, but as soon as i select one, the spinning progress bar shows up but never ends. I already had this issue some time ago and solved it by disabling ipv6, but now the issue came back with it still being disabled.
Is there any other known fix for this?

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Ubuntu
- Virtualization: Docker
- Plugins: none
- Reverse Proxy: NGinx
- Base URL: none
- Networking: tried all
- Storage: local
```

### Jellyfin logs

```shell
Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from https://mysite.com/Items/RemoteSearch/Movie to xxx.xxx.xxx.xxx in 0:00:03.1172709 with Status Code 200
Jellyfin.Api.Controllers.ItemLookupController: Setting provider id's to item 6bee2edf-5f51-ef59-b3ba-fda15c26d0b6-title: {"Imdb":"tt0000000"}
Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing. URL POST /Items/RemoteSearch/Apply/6bee2edf5f51ef59b3bafda15c26d0b6.
16.07.2023 17:43:06
Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from https://mysite.comg/Items/RemoteSearch/Apply/6bee2edf5f51ef59b3bafda15c26d0b6?ReplaceAllImages=true to xxx.xxx.xxx.xxx in 0:01:40.2289393 with Status Code 500
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gummykage** [comment]
Status Code 500 aka Forbidden = API banned?

**Comment by Tobls** [comment]
> Status Code 500 aka Forbidden = API banned?

Hmm, you're right. Do you have any idea what could cause this?
