### ISSUE TITLE
[Issue]: RottenTomato Rating is being pulled from the wrong tag

### ISSUE THREAD

**Issue by gummykage** [jellyfin/jellyfin#10013]
### Please describe your bug

First the actual Rotten tomato rating:
****
![image](https://github.com/jellyfin/jellyfin/assets/9695713/88e7d507-ad3c-47f0-a748-6b96d48538c1)

Sample Movie: 10 Cloverfield Lane
Nfo: Created by Tiny Media Manager with correct tags
Issue: Parsing wrong tag
****
![image](https://github.com/jellyfin/jellyfin/assets/9695713/2da5d9b2-b015-4293-947f-300c39fe5f8d)

End result:
![image](https://github.com/jellyfin/jellyfin/assets/9695713/98476870-ca34-48de-8fda-e4475bbc6f11)

Is there someway to modify which tag it reads from manually? A refresh all metadata fixes it. It's possible the metadata that Tiny Media Manager is wrong.

Any advice for possible patch to fix this.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS:Docker Latest
- Linux Kernel: QNAP QTS 5.0.1 Latest
- Virtualization:
- Clients: Jellyfin Movie Player
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by boc-the-git** [comment]
@gummykage can this be closed?
