### ISSUE TITLE
remove setting on playback video

### ISSUE THREAD

**Issue by KasidisMunkongdee** [jellyfin/jellyfin#1001]
How to edit player , I just want to remove setting menu for all user
I just wanna playing media by default

**Comment by JustAMan** [comment]
I don't think there's an option for that now. You'd have to hack around the `jellyfin-web` manually to achieve this.

What is the use case you're trying to solve anyway?

**Comment by KasidisMunkongdee** [comment]
I want to hide changing video quality. Because every time the video quality
changes, it will be transcode via the server, not directly from google
drive.

ในวันที่ จ. 25 ก.พ. 2019 21:00 น. Vasily <notifications@github.com>
เขียนว่า:

**Comment by JustAMan** [comment]
You can already turn off video transcoding on per-user basis, won't it solve your problem?

**Comment by KasidisMunkongdee** [comment]
> You can already turn off video transcoding on per-user basis, won't it solve your problem?

Sorry for late reply
How i can turn off it, And i didnt see path of jellyfin-web

**Comment by JustAMan** [comment]
`jellyfin-web` is https://github.com/jellyfin/jellyfin-web/

To disable transcoding, go to `Server Settings` -> `Users` -> click on the user you want to edit -> uncheck "Allow audio playback that requires transcoding" and "Allow video playback that requires transcoding" -> click `Save`

**Comment by KasidisMunkongdee** [comment]
> `jellyfin-web` is https://github.com/jellyfin/jellyfin-web/
> 
> To disable transcoding, go to `Server Settings` -> `Users` -> click on the user you want to edit -> uncheck "Allow audio playback that requires transcoding" and "Allow video playback that requires transcoding" -> click `Save`

If i have download jellyfin-web, How can I install in server

**Comment by joshuaboniface** [comment]
`jellyfin-web` is already packaged with your Jellyfin installation; where exactly depends on how you installed it (OS packages, archive, etc.). What @JustAMan meant was if you wanted to remove it entirely, you'd have to modify the code.

The transcoding setting should do what you want however, which is prevent any transcoding being done on the server side.

**Comment by KasidisMunkongdee** [comment]
There is no solution with the new web import?

**Comment by KasidisMunkongdee** [comment]
solved !!!
I got the path web editting /usr/lib64/jellyfin/jellyfin-web
