### ISSUE TITLE
[Issue]: M3U cant add a new list just get and error

### ISSUE THREAD

**Issue by killertrust** [jellyfin/jellyfin#10019]
### Please describe your bug

trying to update my channel list but always get and error cant add cant modify nothing is accessible before it work fine 
![image](https://github.com/jellyfin/jellyfin/assets/71734496/3299ca7d-4e8a-4799-87a1-f5208ec99f71)

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS:linux
- Linux Kernel: ubuntu
- Virtualization:
- Clients:
- Browser:  mozilla
- FFmpeg Version: 5
- Playback Method:
- Hardware Acceleration: intel
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Please attach any screenshots here

![image](https://github.com/jellyfin/jellyfin/assets/71734496/83abc94e-3579-467b-a461-c6644af1a107)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ramboozer** [comment]
This has been happening after I Upgraded. I downgraded to Version: 10.8.8 and m3u lists works fine.
The newest version - IT wouldn't allow me to add, update or even remove any m3u lists I had added
temp fix is to just downgrade IMO
It kept says Auth Denied? (In dev console) or something along those lines

**Comment by killertrust** [comment]
> This has been happening after I Upgraded. I downgraded to Version: 10.8.8 and m3u lists works fine. The newest version - IT wouldn't allow me to add, update or even remove any m3u lists I had added temp fix is to just downgrade IMO It kept says Auth Denied? (In dev console) or something along those lines

can you guide me how to downgrade please

**Comment by ramboozer** [comment]
> > This has been happening after I Upgraded. I downgraded to Version: 10.8.8 and m3u lists works fine. The newest version - IT wouldn't allow me to add, update or even remove any m3u lists I had added temp fix is to just downgrade IMO It kept says Auth Denied? (In dev console) or something along those lines
> 
> can you guide me how to downgrade please

I believe all I did was go onto the site. downloaded a different version and reinstalled ontop of what I had.
Or I removed the old install which doesn't remove config files (one of the two)
