### ISSUE TITLE
[Issue]: absolute paths in .nfo files

### ISSUE THREAD

**Issue by thielj** [jellyfin/jellyfin#10010]
### Please describe your bug

Writing absolute path names into .NFO files should be avoided if the file is local. For example:

```
<album>
 <art>
    <poster>/data/music/VA/VA - Album/cover.jpg</poster>
  </art>
```

Instead, the path should be relative to the base folder whenever possible:

`    <poster>./cover.jpg</poster>
`

Referencing files outside the base folder should be considered a security issue.

### Jellyfin Version

10.8.z

### if other:

10.8.10

### Environment

```markdown
- OS: Ubuntu
- Linux Kernel: 5.10
- Virtualization: Docker
- Storage: bind mount to external HDD
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gummykage** [comment]
Untick this:
![image](https://github.com/jellyfin/jellyfin/assets/9695713/4ff43a6c-45a6-4ea9-9b1d-81e6b6c7e0d9)

**Comment by miguelarios** [comment]
I researched this and I think this is still a bug. According to the source code i see this.

```
if (!Uri.TryCreate(val, UriKind.Absolute, out var uri))
{
    Logger.LogError("Image location {Path} specified in nfo file for {ItemName} is not a valid URL or file path.", val, itemResult.Item.Name);
    return;
}
```

In the file https://github.com/jellyfin/jellyfin/blob/06c603428bceccdb793eb34cc0340e25552d6c1d/MediaBrowser.XbmcMetadata/Parsers/BaseNfoParser.cs. I think this is the issue as it is not trying to validate a relative path.

**Comment by peterysch** [comment]
@miguelarios yeah, this is the root cause. All the posters and thumbnails of my local videos are not showing properly.

**Comment by peterysch** [comment]
@thielj maybe reopen this issue?

Related: https://github.com/jellyfin/jellyfin/issues/7517
