### ISSUE TITLE
[Issue]: Jellyfin binds to all interfaces when using any loopback address other than 127.0.0.1 or [::1]

### ISSUE THREAD

**Issue by LucasMZReal** [jellyfin/jellyfin#10020]
### Please describe your bug

The title is very self-explanatory, it's pretty much it. If you use any other loopback address in 127.0.0.0/8, like 127.0.0.2 even, Jellyfin seems to believe it's not a valid IP or something, instead, it defaults to binding to every interface.

This caused a security problem for me, I use port 80 and 443, and because it was binding to every interface and IP it saw, it also binded to a bunch of public IPv6 addresses, this usually wouldn't be that big of an issue, however my router is kind of crap and does not have a stateful firewall, and since I trusted Jellyfin with firewall rules, it opened those ports directly to the open web; anyone pasting my IP on their browser would directly get into Jellyfin's page.

I use a reverse proxy because it has a lot of benefits, and I need to host other stuff in the same IP on the web, so I set Jellyfin to use 127.0.1.1, but didn't realize until weeks, maybe a month later what was going on.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Windows 11
- Linux Kernel: none
- Virtualization: none ?
- Clients: Not applicable
- Browser: Not applicable
- FFmpeg Version: Not applicable
- Playback Method: Not applicable
- Hardware Acceleration: Not applicable
- GPU Model: Not applicable
- Plugins: Open Subtitles, Session Cleaner, Skip Intro
- Reverse Proxy: Caddy
- Base URL: 
- Networking: Host (I think?)
- Storage: Not applicable
```

### Jellyfin logs

```shell
[2023-07-19 00:42:29.455 -03:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : "[XXXX:XXXX:XXXX:XXXX::/64]"
[2023-07-19 00:42:29.456 -03:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : "[]"
[2023-07-19 00:42:29.458 -03:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: "[XXXX:XXXX:XXXX:XXXX::/64]"
[2023-07-19 00:42:29.465 -03:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: "[]"
[2023-07-19 00:42:29.466 -03:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind exclusions: "[]"
```
```


### FFmpeg logs

_No response_

### Please attach any browser or client logs here

_No response_

### Please attach any screenshots here

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cvium** [comment]
Duplicate of #6272
