### ISSUE TITLE
[Issue]: Having issue with my audio being out of sync.

### ISSUE THREAD

**Issue by navcz** [jellyfin/jellyfin#10031]
### Please describe your bug

Recently started using jellyfin, It was working fine for the first few weeks, Started facing audio out of sync issues especially when not played form 00:00 or pickup back up form the continue to watch section.

Have not faced any issue with IOS mobile application, Seams to be only with the web client in the browser.  

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Ubuntu Ubuntu 20.04.6 LTS
- Linux Kernel: 5.15.0-76-generic
- Virtualization:
- Clients: Jellyfin Web on Chrome (Version 114.0.5735.199)
- Browser: Chrome
- FFmpeg Version: 
- Playback Method: Direct Stream
- Hardware Acceleration: none
- GPU Model: none
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
Hi, can you provide the media info of the problematic files?

**Comment by skulleddino** [comment]
I Just started noticing this issue too
If you play a movie for example, after some time the audio will slowly go out of sync, or if you skip ahead the audio will be completely out of sync. I have noticed this on my Sony TV. Will have to do some more testing to see if other devices are affected.
Here is information from two movies this happens to.

___________________________________________________________________

Video
Title: 1080p H264 SDR
Codec: H264
Codec tag: avc1
AVC: Yes
Profile: Main
Level: 40
Resolution: 1920x1078
Aspect ratio: 16:9
Interlaced: No
Framerate: 23.976025
Bitrate: 3586 kbps
Bit depth: 8 bit
Video range: SDR
Video range type: SDR
Color space: bt709
Color transfer: bt709
Color primaries: bt709
Pixel format: yuv420p
Ref frames: 1
NAL: 4


Audio
Title: Stereo - AAC - Default
Language: und
Codec: AAC
Codec tag: mp4a
Profile: LC
Layout: stereo
Channels: 2 ch
Bitrate: 160 kbps
Sample rate: 48000 Hz
Default: Yes
Forced: No
External: No

___________________________________________________________________

Video
Title: 1080p H264 SDR
Codec: H264
Codec tag: avc1
AVC: Yes
Profile: Main
Level: 40
Resolution: 1904x1040
Aspect ratio: 1.85:1
Interlaced: No
Framerate: 23.972214
Bitrate: 3448 kbps
Bit depth: 8 bit
Video range: SDR
Video range type: SDR
Color space: bt709
Color transfer: bt709
Color primaries: bt709
Pixel format: yuv420p
Ref frames: 1
NAL: 4


Audio
Title: Stereo - AAC - Default
Language: und
Codec: AAC
Codec tag: mp4a
Profile: LC
Layout: stereo
Channels: 2 ch
Bitrate: 158 kbps
Sample rate: 48000 Hz
Default: Yes
Forced: No
External: No

**Comment by felix920506** [comment]
So you are having issues of audio desync in the Web client and on your TV but the same files play without issues on your iPhone via the Jellyfin app? Or are they different files?

**Comment by felix920506** [comment]
@skulleddino can you try with the same files that you are having issues with on other devices and see if the issue persists? As a sanity check also copy out those files and play them in something like VLC.

**Comment by skulleddino** [comment]
After my indepth testing, it was issues on my end from ripping my copies, looks like an option was incorrectly selected and the audio was off, my apologies

**Comment by srcrist** [comment]
Issue closed as it is not a Jellyfin bug per submitter.
