### ISSUE TITLE
how to convert Emby media library to  Jellyfin media library 

### ISSUE THREAD

**Issue by dzhl** [jellyfin/jellyfin#10040]
I have been using Emby all along, but now I don't want to renew it. I want to switch to Jellyfin instead. The reason is that the media library of Emby is very large, with a capacity of 300TB, and the image resources are not in the same folder as the video files. Is there any way to directly convert the Emby media library into a Jellyfin media library without having to rescan everything?

**Comment by crobibero** [comment]
No, sorry. It was only possible to migrate to Jellyfin from Emby when we originally created the fork.
