### ISSUE TITLE
[Issue]: [bug] Movie extras in the "other" folder aren't being read

### ISSUE THREAD

**Issue by dwt12777** [jellyfin/jellyfin#10048]
Movie extras in the "other" folder aren't made available in the Special Features section of the Jellyfin clients.

Steps to reproduce the problem:

1. Rip blueray or DVD with extras
2. Name and organize files using the folder method [outlined here](https://jellyfin.org/docs/general/server/media/movies/#extras-folders) (see tree example below)
3. Wait for jellyfin to pickup changes or rescan the library manually
4. Go to movie in Jellyfin client (I've tried Roku, iOS, and web)
5. Scroll to "Special Features" and observe that all special features are shown except those in "Other" folder

Some examples of current file structures where this is happening:

```
E:\Media\Movies\The Bourne Identity (2002) [imdbid-tt0258463]>tree /f
Folder PATH listing for volume Data
Volume serial number is E4C5-C95D
E:.
│   The Bourne Identity (2002).mkv
│
├───Deleted Scenes
│       Alternate Ending 1.mkv
│       Bourne and Marie by the Side of the Road.mkv
│       Bourne and Marie Practice on Subway.mkv
│       Farmhouse - Extended Scene.mkv
│       Post 911 Alternate Ending.mkv
│       Post 911 Alternate Opening.mkv
│       Post 911 Introduction.mkv
│       Psychologist Discusses Bourne.mkv
│       Wombosi on the Private Jet.mkv
│
├───Featurettes
│       Access Granted - 2004 interview with Tony Gilroy.mkv
│       Cloak and Dagger - Covert Ops.mkv
│       From Identity to Supremacy - Jason and Marie.mkv
│       Inside a Fight Sequence.mkv
│       The Birth of The Bourne Identity.mkv
│       The Bourne Diagnosis (Part 1).mkv
│       The Bourne Mastermind - Robert Ludlum (Part 1).mkv
│       The Speed of Sound.mkv
│
├───Other
│       Extreme Ways - Music Video.mkv
│
└───Trailers
        Theatrical Trailer.mkv
```

```
E:\Media\Movies\Puss in Boots The Last Wish (2022) [tmdbid-315162]>tree /f
Folder PATH listing for volume Data
Volume serial number is E4C5-C95D
E:.
│   Puss in Boots The Last Wish (2022).mkv
│
├───Deleted Scenes
│       Deleted Scenes.mkv
│
├───Featurettes
│       A Cast of Characters.mkv
│       How to Draw the Purrfect Pawtrait.mkv
│       How to Make a Paper Perrito.mkv
│       In the Beginning.mkv
│       Jack Horner's Line-O-Rama.mkv
│       Kitty Cam.mkv
│
└───Other
        Fearless Hero - Lyric Video.mkv
        The Trident.mkv
```

```
E:\Media\Movies\The Super Mario Bros. Movie (2023)>tree /f
Folder PATH listing for volume Data
Volume serial number is E4C5-C95D
E:.
│   The Super Mario Bros. Movie (2023) - 1080p.mkv
│   The Super Mario Bros. Movie (2023) - 4K HDR.mkv
│
├───Featurettes
│       Getting to Know the Cast.mkv
│       Leadership Lessons with Anya Taylor-Joy.mkv
│       Leveling Up - Making The Super Mario Bros. Movie.mkv
│       The Super Mario Bros. Movie Field Guide.mkv
│
└───Other
        Peaches - Lyric Music Video.mkv
```

In each case, anything in the "Other" folder isn't being picked up by Jellyfin.  However, if I move the "Other" items to the "Featurettes" subfolder and rescan the library, they're read successfully and playable in the client.

Also, I'm aware that the Jellyfin [naming specification for movie extras](https://jellyfin.org/docs/general/server/media/movies/#extras-folders) lists the supported folder names in lowercase.  I have tried changing the folder names to all lowercase (i.e. "other") and rescanned the library with no success.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Windows 10
- Virtualization: none
- Clients: Browser (firefox), Roku, iOS
- Reverse Proxy: nginx
- Base URL: none
- Storage: local
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sabberworm** [comment]
I have the same problem when I use the `-other` suffix to name my files. They show up as separate movies instead of as special features of the main movie:

<img width="864" alt="image" src="https://github.com/jellyfin/jellyfin/assets/47652/1ed2ab92-d490-44e8-8622-f3fe12438968">

**Comment by Bond-009** [comment]
"other" isn't supported yet in 10.8.x, it will be supported in version 10.9+, the docs got updated to fast.
@sabberworm That's an unsupported naming scheme

**Comment by sabberworm** [comment]
> @sabberworm That's an unsupported naming scheme

Are the docs wrong then?

<img width="846" alt="image" src="https://github.com/jellyfin/jellyfin/assets/47652/f160f91c-d5b8-4dd5-a380-4c02c7bc24a6">

**Comment by Bond-009** [comment]
I'm talking about the fact that your media is 2 levels deep, I'm assuming your movie library is `/mnt/upper/movies` and not `/mnt/upper/movies/Comedy`
