### ISSUE TITLE
[Issue]: Matroska Direct Play is broken

### ISSUE THREAD

**Issue by kvaster** [jellyfin/jellyfin#10046]
### Please describe your bug

Matroska Direct Play is broken with following commit:  [47aa07c3424ce0041e0a79eea1ab7f6621485b94](https://github.com/jellyfin/jellyfin/commit/47aa07c3424ce0041e0a79eea1ab7f6621485b94)

Matroska container name normalization was changed from:

```
format = format.Replace("matroska", "mkv", StringComparison.OrdinalIgnoreCase);
```

to:

```
if (string.Equals(format, "matroska", StringComparison.OrdinalIgnoreCase))
{
    return "mkv";
}
```

ffmpeg reports `matroska,webm` for all mkv files. With old code it will be transformed to `mkv,webm` and it's good and with new code it will remain as `matroska,webm`.

### Jellyfin Version

10.8.z

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shadowghost** [comment]
Afaik this commit is not part of our stable 10.8 releases. Nonetheless I'll take a look if I find the time to fix it in master.

**Comment by kvaster** [comment]
Thanks. I will make a PR next time for such case.
