### ISSUE TITLE
Language labels

### ISSUE THREAD

**Issue by mkrsticch** [jellyfin/jellyfin#10044]
### Please describe your bug

Actually, it's not a issue, but I'm still curious. I have a Jellyfin server 10.8.10 installed on OpenMediaVault / Docker and another one installed on Asustor AS6706T / Docker. 

On the first server, full language labels (English, French, etc.) are displayed, while on the second platform, only abbreviations (eng, fra) are displayed. 

Why is this the case?

OpenMediaVault 
![image](https://github.com/jellyfin/jellyfin/assets/81646422/adab5815-7b2a-42ec-aabe-bc1359f9a025)

Asustor
![image](https://github.com/jellyfin/jellyfin/assets/81646422/d2039321-8053-4b01-a72f-842b36f481c5)

### Jellyfin Version

10.8.10

**Comment by srcrist** [comment]
Closing this issue as it does not contain an actual Jellyfin bug. Please visit our forums or our Matrix/Discord server for general questions.
