### ISSUE TITLE
[feature] IPFS library bridge

### ISSUE THREAD

**Issue by icf20** [jellyfin/jellyfin#1005]
**Describe the feature you'd like**
in order to avoid having duplicate files one copy in IPFS storage and another normal folder for jellyfin, what if there is a bridge that links the IPFS file to the normal library and avoid having duplicates file

**Additional context**
https://github.com/ipfs/go-ipfs

**Comment by JustAMan** [comment]
Cannot you somehow just mount your IPFS and tell Jellyfin to make a library on top of that? Why'd you need a bridge? This seems like it should be OS-level thing, not application-level.

**Comment by fruhnow** [comment]
> Cannot you somehow just mount your IPFS and tell Jellyfin to make a library on top of that? Why'd you need a bridge? This seems like it should be OS-level thing, not application-level.

Fully agree with this. There should be some sort of FUSE-driver for IPFS but that doesn't concern Jellyfin in any way imho

**Comment by icf20** [comment]
yes you can mount ipfs on a folder but there are some issues

1 meta files dont get inserted into ipfs

2 there is no way to categorize the files lets say tv shows / movies etc because everything is mounted

**Comment by fruhnow** [comment]
> yes you can mount ipfs on a folder but there are some issues
> 
> 1 meta files dont get inserted into ipfs
> 

Even if the driver would allow that, im not sure if thats something IPFS you should do with an IPFS-Filesystem. (Regarding that sharing aspect. If someone who you are sharing with needs metadata for a File, he probably just crafts it on his own and doesnt rely on your sharing).

>
> 2 there is no way to categorize the files lets say tv shows / movies etc because everything is mounted
>

I think i dont really get that point
