### ISSUE TITLE
[Issue]: 

### ISSUE THREAD

**Issue by spaceaape** [jellyfin/jellyfin#10057]
### Please describe your bug

Library Mixed Movies and TV media option just flat out doesn't work. Tv shows will get recognized as movies completely overwriting the metadata with wrong information, and there isn't anyway to label it one way or the other so its recognized properly. There is also no way to strip the inaccurate metadata Jellyfin wrote without manually deleting it one by one. 

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS:
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by HybridSarcasm** [comment]
There is not adequate information in this issue to review the reported problem. If the problem persists with the current build, please add the minimum details for a proper bug report.

**Comment by felix920506** [comment]
Closing as invalid
