### ISSUE TITLE
Strange behavior with some Windows directories

### ISSUE THREAD

**Issue by Luclu7** [jellyfin/jellyfin#1006]
Unzipping the zip on the desktop on a clean user

**To Reproduce**
1. Download the 10.2.1's windows zip
2. Unzip it on desktop
3. Launch jellyfin.exe
4. It insta-crashes

**Expected behavior**
Just the normal setup wizard.

**Logs**
Only error I could get:
![](https://user-images.githubusercontent.com/11773528/53411146-06172a00-39c6-11e9-86b4-0dc7355ca098.png)

**Screenshots**
See https://gfycat.com/SeparateVictoriousCob

 - OS: Windows Server 2012R2
 - Browser: IE (default)/Firefox
 - Jellyfin Version: 10.2.1

How to fix: (for me)
Just unzip it to C:\JF and launch it with `jellyfin.exe -d C:\JF-data` and it works.

**Comment by JustAMan** [comment]
cc @LogicalPhallacy

**Comment by LogicalPhallacy** [comment]
This is super interesting. Is your clean user named jellyfin? I want to try and repro this.

**Comment by Luclu7** [comment]
Yes, I also had this issue on the Administrator user before, so I tried
with a jellyfin user and this happened.

Le lun. 4 mars 2019 à 02:34, LogicalPhallacy <notifications@github.com> a
écrit :
