### ISSUE TITLE
Windows upgrade 10.8.8 -> 10.8.10 / Libraries, Metadata, Users all lost [Issue]: 

### ISSUE THREAD

**Issue by isuee94** [jellyfin/jellyfin#10079]
### Please describe your bug

I upgraded yesterday from 10.8.8 to 10.8.10.  All seemed to go fine, but when Jellyfin restarted it was like a fresh install.  Asking me to create a user, etc.  Any chance of getting this back or do I need to start from scratch?  How do I prevent this in the future?  Super frustrating!

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS:Windows 10
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cvium** [comment]
Make sure your data and config folders aren't in Program Files if you're using Windows. If you're using docker, either mount your folders or use volumes.

**Comment by isuee94** [comment]
> Make sure your data and config folders aren't in Program Files if you're using Windows. If you're using docker, either mount your folders or use volumes.
> 
> What happened is that either your data/config folders were wiped when you upgraded (bad folder placement) or they weren't persisted.

Is the default location in Program Files?  I didn't change anything from default.  If that's the default and it is wiped during an upgrade, that's really poor.

**Comment by isuee94** [comment]
So it appears my data may be intact.  I found it in the hidden Program Files folder.  How do I get my Jellyfin installation pointed to this folder since it's acting like a new installation?

**Comment by isuee94** [comment]
@cvium - Please see my note above.  Can you re-open this and provide input on how to get my installation pointed to my c:\ProgramData folder?
