### ISSUE TITLE
Separate Language Settings for Titles and Posters

### ISSUE THREAD

**Issue by j506130598** [jellyfin/jellyfin#10076]
Hello Jellyfin team,

I am a user of Jellyfin and I find it to be an outstanding media server, as it allows me to manage and stream my multimedia content conveniently. However, there's one feature that, if implemented, could significantly enhance the customization and flexibility of Jellyfin.

Currently, when fetching metadata from sources (like TheMovieDB, OMDb, etc.), Jellyfin applies the preferred language settings to both titles and posters uniformly. So, if I set Chinese as my preferred language, both movie/series titles and their respective posters are fetched in Chinese.

However, for my specific use-case, I would like to have the ability to set different languages for titles and posters. For instance, I would prefer having Chinese titles but English posters. This is because while I would like the convenience of navigating through titles in my native language, I still want to retain the originality that comes with English posters.

A feature allowing separate language settings for titles and posters would be greatly appreciated. It would offer users greater control over the appearance of their media library and might cater to more diverse use-cases.

Thank you very much for considering my request. I look forward to seeing the continual development and improvement of Jellyfin.

**Comment by j506130598** [comment]
I am a user of the Docker version of Jellyfin (latest release)

**Comment by crobibero** [comment]
Thank you for your fleshed out feature request- but we collect requests at
