### ISSUE TITLE
[Issue]: Nuget.com doesn't have the latest stable version of "Jellyfin.*" for plugin development

### ISSUE THREAD

**Issue by luzmane** [jellyfin/jellyfin#10089]
### Please describe your bug

Nuget.com doesn't have the latest stable version (10.8.10) of:

- Jellyfin.Controller
- Jellyfin.Model
- Jellyfin.Naming
- Jellyfin.Data
- Jellyfin.Extensions
- Jellyfin.Common

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS:
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 1337joe** [comment]
Looks like 10.8.11 is up now if I'm reading this right:

https://www.nuget.org/packages?q=jellyfin&prerel=true&sortby=relevance
