### ISSUE TITLE
[Issue]: Metadata refresh problems with NFO files

### ISSUE THREAD

**Issue by scampower3** [jellyfin/jellyfin#10088]
### Please describe your bug

Currently, if you use the Search for missing metadata when refreshing metadata, the existing metadata will be replaced by the metadata found in the NFO files.  I think for this option, only missing metadata should be added, not replace all metadata, even if the exisiting metadata differs from the ones found in NFO files.

Also, if you use the Replace all metadata when refreshing metadata, metadata from remote sources will be used instead of the metadata from the NFO file.

I think the issue stems from this line of code.
https://github.com/jellyfin/jellyfin/blob/e5dcaa6ed52a22360958e5d2054f55924f2a1512/MediaBrowser.Providers/Manager/MetadataService.cs#L723C24-L723C117

### Jellyfin Version

Other

### if other:

10.9.0

### Environment

```markdown
- OS: 6.11.5
- Linux Kernel: 5.19.17-Unraid
- Virtualization: jellyfin/jellyfin:unstable docker
- Clients: Web app
- Browser: Firefox
- FFmpeg Version: 5.1.3-Jellyfin
- Playback Method: 
- Hardware Acceleration: VAAPI
- GPU Model: AMD Ryzen™ 5 5600G with Vega graphics
- Plugins: 
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JPVenson** [comment]
Could you attach a logfile from around the time when this did happen?

**Comment by scampower3** [comment]
[logs.txt](https://github.com/jellyfin/jellyfin/files/12270070/logs.txt)

**Comment by cxfksword** [comment]
This PR now encounter a problem. If I configure Jellyfin to auto generate NFO files, when the automatic scan idenitfy not correct, and generated an incorrect nfo file, I cannot identify and modify correctly by searching again. The related issue #11479.
