### ISSUE TITLE
[Issue]: Slow download speeds

### ISSUE THREAD

**Issue by MarkusTieger** [jellyfin/jellyfin#10081]
### Please describe your bug

Downloads are incredibly slow. A Videofile with about 10 GB requires over a hour to download over LAN (1 GBit/s) while it only requires about 2 minutes when using smb instead. I also tested it with this unofficial package for my nas and it also wasn't faster: https://synocommunity.com/package/jellyfin, so it isn't a docker issue.
I expected that it is almost so fast as over smb.

And yes: I am sure, that it isn't routed over the internet.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: DSM 7.2 (based on Debian)
- Linux Kernel: 4.4.302+ (output from "uname -r")
- Virtualization: Docker
- Clients: Browser, "Jellyfin Media Player" on Linux, Findroid
- Browser: Brave Version 1.56.14 Chromium: 115.0.5790.114 (Official Build) (64-bit)
- FFmpeg Version: (the latest from the docker image)
- Hardware Acceleration: none
- GPU Model: none
- Plugins: AudioDB, Intro Skipper, Jellyscrub, MusicBrainz, OMDb, Studio Images, TMDb
- Reverse Proxy: none
- Base URL: none
- Networking: Host
- Storage: local
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MarkusTieger** [comment]
I now kinda believe it's a synology issue, because with ssh logged into my nas and i fetch the file using 127.0.0.1 etc. i have normal download speeds.
I leave the issue open if anyone has an idea.

**Comment by MarkusTieger** [comment]
Found the problem

**Comment by geirskogul** [comment]
what was the problem?

**Comment by MarkusTieger** [comment]
I forgot to disable a network throttle option, which i enabled for testing and forgot to disable like 3 months ago.

**Comment by geirskogul** [comment]
Aw beans that's not my issue then. Some users are hard limited to 50kb/s download speed and I'm about to throw in the towel and say it's ISP stuff. Was hoping for some secret jellyfin config I screwed up lol

Thank you for responding!
