### ISSUE TITLE
Logo Discussion

### ISSUE THREAD

**Issue by SpootDev** [jellyfin/jellyfin#101]
Should be a jelly donut with a sharkfin on top.

**Comment by thejacer87** [comment]
already a thread on reddit here: https://www.reddit.com/r/jellyfin/comments/a5c39s/some_rough_logo_sketches/

seems like a good start

**Comment by thejacer87** [comment]
a new update: https://www.reddit.com/r/jellyfin/comments/a5mai1/i_put_together_a_logo_concept_based_on_one_the/

**Comment by BnMcG** [comment]
I like this design, but I agree with others that we should consider moving away from Emby's colour scheme.

**Comment by RazeLighter777** [comment]
Change it to pink or purple? Both are jelly like colors.

**Comment by thejacer87** [comment]
purple!!!!!

**Comment by thejacer87** [comment]
that dark purple :ok_hand:  so nice. really nice @Ronald-McDaddy 

@joshuaboniface @nvllsvm +1 for dark purple

**Comment by JustAMan** [comment]
I like both purples, though dark one seems to have some edge artifacts (some white-ish pixels around the jelly). Might be me viewing from a phone, though...

If we go with that logo I think we'd also need a small square version for favicon, is it possible?

**Comment by Terror-Gene** [comment]
My issue with the design is it looks like it says "Jelly Fin", is it the last jelly? :p 
I like the design with 1 part of the word in & 1 part out though.
As for the color, I find the 1st one is too dark on a dark background. Out of the 3 I like the 3rd the most.
These are just my opinions, I am not involved in the development of Jellyfin.

**Comment by PrplHaz4** [comment]
1. are we upper or lowercase J?  Most references seem to be jellyfin - does the logo still work w/a lower case J?
2. Agree the darker purple looks better but we need it to work on both black  and white backgrounds - so my vote would be middle purple
3. favicon should probably just be the sideways jelly shape with no words - this square icon would probably get used more than the full icon w/words, and the shape done by @Ronald-McDaddy is very strong in that regard

**Comment by davebrny** [comment]
something to keep in mind is the different sizes that the logo will have to be shown at and if the text and the logo are fused together then it means you cant resize them separately. for example if you want to have a small icon, then text inside the logo will be even smaller or if you want the text large enough to be legible then the icon will be too large or at least take up a lot of space

**Comment by JustAMan** [comment]
What if we put all the text onto the icon? Here's my attempt at showing the idea (yes, Paint *madskillz*!! xD): https://imgur.com/a/KK4AJZp

**Comment by CubGeek** [comment]
Or, alternatively, keeping the correct letter spacing for “jellyfin” and where the icon crosses the border of the text near the apex, have the color of the letter bisected too... white inside the icon, purple for the part of the letter outside the icon.

Obscene skillz with an app I have never really used before....
https://imgur.com/a/jSaHM4V

**Comment by CubGeek** [comment]
> something to keep in mind is the different sizes that the logo will have to be shown at and if the text and the logo are fused together then it means you cant resize them separately. for example if you want to have a small icon, then text inside the logo will be even smaller or if you want the text large enough to be legible then the icon will be too large or at least take up a lot of space

It’s not uncommon for branding to incorporate an icon-only version of the logo, as well as sometimes a text-only version,in addition to the combined version. this way, the most appropriate version can be chosen for the usage at hand.

**Comment by nvllsvm** [comment]
I'm contracting with a few designers right now. Will have samples in a few days.

**Comment by TheManchineel** [comment]
I was thinking of the potential implications of using a darker colour. For me at least the dark theme is fundamental, and colour consistency is better for the UI.

**Comment by davebrny** [comment]
i had a look through dafont yesterday evening for possible fonts that could be used. i wasnt looking for your typical media-browser type font so they might not be everyone's cup of tea but here they are anyway: 
https://imgur.com/a/2WLlPUb

**Comment by BnMcG** [comment]
@davebrny I really like several of these, particularly the ones including an eye in the logo shape.

**Comment by anthonylavado** [comment]
Closing here, as work is now being done in https://github.com/jellyfin/jellyfin-ux
