### ISSUE TITLE
[Issue]: Video format is detected incorrectly because of sub file

### ISSUE THREAD

**Issue by pythaeusone** [jellyfin/jellyfin#10108]
### Please describe your bug

If you convert a video e.g. to 480p and put it on the server with a sub file, JellyFin does not look at the format of the video file, but gets the information from the sub file.
But if the sub file contains the information that the video is or was 560p, then the server starts transcoding instead of direct streaming.
For me this approach is wrong and should be corrected, because many subs are with resolution information that does not always match the video format.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS:
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shadowghost** [comment]
Can you please post the mediainfo of the wrongly identified file and the subtitle?

**Comment by srcrist** [comment]
Issue closed as stale. No response from submitter for several months.
