### ISSUE TITLE
Jellyfin in Docker fails to start on Raspberry Pi - no logs, no error messages, just says "Aborted" in interactive session

### ISSUE THREAD

**Issue by shankargopal** [jellyfin/jellyfin#10106]
### Please describe your bug

I installed the docker container on a Raspberry Pi by running `docker pull jellyfin/jellyfin`

Then I ran
<pre>
docker run -it -u {uid>}:{gid} --name jellyfin --net=host --volume {HOMEDIR}/jellyfin-config:/config --volume {HOMEDIR}/jellyfin-cache:/cache --mount type=bind,source={HOMEDIR}/Music,target=/media jellyfin/jellyfin
</pre>

(I have redacted my actual uid and gid and the home directory).  

and several variations.  When I do this, I get this output from `docker container list -all`:

<pre>
CONTAINER ID   IMAGE               COMMAND                CREATED         STATUS                       PORTS     NAMES
020748c27b2d   jellyfin/jellyfin   "/jellyfin/jellyfin"   3 seconds ago   Exited (132) 2 seconds ago             jellyfin
</pre>

I tried to enter the container using `--entrypoint=/bin/bash`.  When I get into the container and type `jellyfin/jellyfin`, I get a single word message `Aborted`. 

Running `docker logs` gets me no output at all from the container.

The user that I am on the system has write access to `jellyfin-config`, `jellyfin-cache`, and `Music`.  When I run `id` inside the container, it reports the same user id and group id as my system user.  When I run `whoami`, however, it says `cannot find name for user xxx`.  When I run `touch test` inside `/cache` when running bash inside the container, I get an error that setting times is not permitted, but the file is written.

I'm not sure what is going on, this seems like a bug?

### Jellyfin Version

10.8.z

### Environment

```markdown
Output of `uname -a`:

`Linux raspberrypi 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU/Linux`

- Networking: WiFi
- Storage: 64GB SD card
```

### Jellyfin logs

```shell
I cannot get any logs, as noted above.
```

### FFmpeg logs

```shell
N/A
```

### Please attach any browser or client logs here

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dev-gavinfang** [comment]
have you tried to use images with '*-armhf' tag such as  'jellyfin/jellyfin:20231002.19-unstable-armhf'
