### ISSUE TITLE
[Issue]:android client can reach server while browser is good.

### ISSUE THREAD

**Issue by Rich-xuguo** [jellyfin/jellyfin#10105]
### Please describe your bug

neither android Tv and mobile client can reach server while browser is good.
![Screenshot_20230809_222751_org jellyfin mobile debug](https://github.com/jellyfin/jellyfin/assets/119148467/5bb50ae2-2af6-456f-95fc-005881637df1)

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS:server in docker
- Linux Kernel:
- Virtualization:
- Clients:Android app
- Browser:all types of browser
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cubale** [comment]
I encountered the same issue too! I think that is a bug.

**Comment by nielsvanvelzen** [comment]
When you open `http://192.168.2.100:8096/System/Info/Public` in your browser what does it say after `"Version":`?

**Comment by Rich-xuguo** [comment]
> When you open `http://192.168.2.100:8096/System/Info/Public` in your browser what does it say after `"Version":`?

browser is OK to connect Server，Server version is 10.8 8

**Comment by nielsvanvelzen** [comment]
We recommend using 10.8.10 (it fixes security vulnerabilities) but all versions starting from 10.8.1 should work. Can you share everything on that page?

**Comment by Rich-xuguo** [comment]
> We recommend using 10.8.10 (it fixes security vulnerabilities) but all versions starting from 10.8.1 should work. Can you share everything on that page?

Sorry, got wrong, it's version 10.7.7, I will try pulling some newer one from dockerhub. Thank you.

**Comment by nielsvanvelzen** [comment]
Well that's the issue then. Next time please check the version first.
