### ISSUE TITLE
[Issue]: difference between metadata providers causing issue

### ISSUE THREAD

**Issue by gustavodeon** [jellyfin/jellyfin#10102]
### Please describe your bug

I've found a very frustrating (and admittedly niche) issue with the way jellyfin seeks metadata.

I'm trying to organize Naruto Shippuden in my library, and while the anime originally doesn't have seasons, most metadata providers do separate the episodes in seasons, which i prefer since it's easier to skip big filler sequences.

The problem is, since these separations are made up, each provider separated the anime by its own standard, and here lies the issue. I prefer the way TMDB has sliced the anime, but it seems jellyfin favors TVDB for the library organization, which lead to, for example:

episodes being in the directory "season 18/" but being displayed in season 17 inside jellyfin.
episode's metadata (title, description, etc) and image not being collected.

i've tried disabling TVDB, or at least setting it lower in the list of metadata providers, but to my surprise, it isn't even listed inside that menu for me, since i don't have the TVDB plugin installed, which means jellyfin uses it natively, and even installing it and not selecting it as source doesn't do anything.

I don't know about jellyfin's development history, but i imagine that this integration with TVDB was built before plugins, and now it's not playing nice with multiple sources.

All i want is for jellyfin to stop listening to TVDB, and only check TMDB for metadata for this specific library, but disabling it doesn't work, setting it as the last option does nothing either, much less having its plugin deleted.

If necessary i'm more than willing to create a user and allowing management over the library for who wants so see and interact with the issue.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Ubuntu 22.04
- Linux Kernel:6.2.0-26-generic
- Virtualization:Docker
- Clients:Browser
- Browser:Chrome 115.0.5790.170
- FFmpeg Version: 
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins: aniDB, TMDB, TVDB (installed for testing, but originally when the issue arrived it wasn't installed)
- Reverse Proxy: traefik
- Base URL:
- Networking:
- Storage: local
```

### Please attach any screenshots here

![image](https://github.com/jellyfin/jellyfin/assets/21964050/f9215b21-1945-42a9-9e17-0b7efa2b078a)
![image](https://github.com/jellyfin/jellyfin/assets/21964050/6bf9a3f2-4eca-4b70-be3b-c19af4fea699)
![image](https://github.com/jellyfin/jellyfin/assets/21964050/36c197e3-56b8-45a8-b990-3bb0bb4f913b)
![image](https://github.com/jellyfin/jellyfin/assets/21964050/48acec29-fd11-4f5f-887b-5c16aaf42bbb)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jacobslusser** [comment]
I'm new to the codebase but I've debugged metadata retrieval for shows when configured exactly as in your screenshots and there is not a hidden TVDB metadata provider being used that I can see. To confirm that, I also traced all the outbound HTTP calls from Jellyfin and TMDB is the only external provider used when configured as you have it.

I'm sorry that doesn't resolve your issue, but I don't think it is because there is a built-in TVDB metadata provider in play.

**Comment by gustavodeon** [comment]
Got it, I've fixed the issue now by reorganizing the library, but honestly I've made so many attempts that I don't even remember how I got it working. I will close this since I lack the info for deeper debugging, thanks for the response @jacobslusser!
