### ISSUE TITLE
[Issue]: Media access settings ignored for folder thumbnails

### ISSUE THREAD

**Issue by widhalmt** [jellyfin/jellyfin#10116]
### Please describe your bug

I know that the background picture / thumbnail for libraries on the home screen are randomly created from media in the library. Recently I introduced media access settings / permissions / movie ratings to block some Jellyfin users from accessing content not appropriate for them. (We have a very diverse library and some users don't want to get into contact with some movies like from the Splatter genre)

On a rescan of the library I recognized that the picture of the "Movies" library was replaced with a screenshot from a movie that's actually blocked for some users. But even when these users log in, they see the screenshot.

A possible solution for me would to exclude movies that are restricted for any user when choosing a movie to extract the library thumbnail. That could work for excluding by age rating as well as tag. I think users with access to all movies won't mind if they never get one of "their" movies chosen.

Another option would be to just allow to deactivate the random picture and replace it with something fixed. Preferably not with a theme but via menua.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Debian GNU/Linux 11 (bullseye)
- Linux Kernel: 5.10.0-23-amd64
- Virtualization: Proxmox/quemu
- Clients: Web, Amazon Fire Stick 4k
- Browser: Chromium, Chrome
- FFmpeg Version: 5.1.3-3-bullseye
- Playback Method:
- Hardware Acceleration: no
- GPU Model:
- Plugins:
- Reverse Proxy: no
- Base URL:
- Networking:
- Storage: CephFS
```

### Please attach any screenshots here

Can't post any screenshots because they might violate GitHub policies and might be disturbing for some viewers. That's the exact point. :-)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shadowghost** [comment]
Library images are global and therefore do not respect any user specific limitations (not sure how we could tackle that outside of implementing library images on a per user basis). Best way to prevent this currently is using a custom library image.

**Comment by widhalmt** [comment]
My approach would be excluding movies that are affected from any sort of exclusion and exclude them from ramdomly choosen which movie to use for thumbnail extraction.

Like: If a movie is rated `R` and *any* user isn't allowed to watch `R` rated movies, then don't use this movie for thumbnail generation at all. Does that sound sensible or is it just a lot of overhead?

**Comment by Shadowghost** [comment]
Main problem with this approach is that thumbnails are only created on scan, so we'd need to hook that up into the user controller so new thumbnails are generated whenever a user's parental controls are changed. Should be doable but seems kinda hacky to me tbh
