### ISSUE TITLE
[Issue]: High Memory usage on Debian 12 - native install VM

### ISSUE THREAD

**Issue by karserasl** [jellyfin/jellyfin#10112]
### Please describe your bug

I have the Jellyfin install in a dedicated VM (Debian 12) with 10GB of RAM.
Is it normal the picture you see below? It seems that really something is wrong.

![image](https://github.com/jellyfin/jellyfin/assets/14327196/df22e900-5e4b-4b2b-a582-d950acdab090)

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS:
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wgilthorpe** [comment]
I have this same issue.  I have never posted a bug report, but if I can provide any info.  Please let me know.  

I have Jellyfin running on my bare metal Ubuntu media server.  The memory usage was above 16gb.
