### ISSUE TITLE
[Issue]: Jellyfin dont update (scan) library in starlink internet

### ISSUE THREAD

**Issue by Dsamaz** [jellyfin/jellyfin#10124]
### Please describe your bug

Jellyfin dont update (scan) library in starlink internet

On other internet connections, it's OK, fine;

however, with Starlink's internet connection (satellites) it doesn't work at all.

Can any friend tell how to update the libraries without internet? Is there a way to move from an updated PC to another just by copying the files from the folder: /var/lib/jellyfin/metadata?

How to check library update logs? accessing /var/log/jellyfin does not show anything about the unsuccessful updates.

Note: I installed all metadata plugins, and tried to update later, repeating the failure.

### Jellyfin Version

Other

### if other:

10.8.10

### Environment

```markdown
- OS: ubuntu server 23.04
- Linux Kernel:
- Virtualization: no
- Clients:
- Browser: chrome
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration: no
- GPU Model: no
- Plugins:
- Reverse Proxy: no
- Base URL: http://192.168.1.254:8096
- Networking:
- Storage:
```

### Please attach any screenshots here

![WhatsApp Image 2023-08-18 at 10 20 13 AM](https://github.com/jellyfin/jellyfin/assets/142624767/cd947d5f-cade-41ec-94a4-c39eedeb3210)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Dsamaz** [comment]
Hello, updating.

I did the following test: 1. I have a jellyfin with a complete library and internet present, I scanned normally, with the images working.
2. We copy the Metadata folder (/var/lib/jellyfin/metadata) to a pendrive

On another computer WITHOUT internet, fresh installation, we install ubuntu server + jellyfin, then copy the metadata folder to its location (var-lib-jellyfin)
  and we copied three movie folders.

We added the Movies library, disabling all metadata downloaders (because the PC doesn't have internet), such as TheMovieDb The Open Movie Database. I also disabled Screen Grabber and Embedded Image Extractor in the Image Fetchers option, and the result was OK, Jellyfin was able to get the previously copied metadata without internet.

Partial success.
The main problem, the fact that it does not work on Elon Musk's internet - Starlink - continues.
![Screenshot from 2023-08-18 15-54-52](https://github.com/jellyfin/jellyfin/assets/142624767/69591360-4d10-4241-b089-e3da4173f3a1)

**Comment by srcrist** [comment]
Closing this issue as it does not contain an actual Jellyfin bug. Jellyfin does not require internet access to function or scan for media in your library, but it would require correctly configured internet access in order to contact metadata providers for artwork and metadata. If you're having issues with that process, please visit our support communities on the forums or our Matrix/Discord server and people will be glad to help you troubleshoot the issue. Someone may be aware of workarounds for Starlink, specifically.
