### ISSUE TITLE
[Issue]: Jellyfin not labeling external subtitles as SDH per documentation

### ISSUE THREAD

**Issue by jathek** [jellyfin/jellyfin#10123]
### Please describe your bug

According to the [documentation](https://jellyfin.org/docs/general/server/media/external-files/#naming-flags), suffixing an external subtitle file with `.sdh.en` should result in the subtitle stream being marked as hearing impaired and English in Jellyfin. Instead, the `.sdh` is being parsed into the stream title.

Current media names:
- A.Movie.Title.mp4
- A.Movie.Title.Main [SRT].en.srt
- A.Movie.Title.Main (SDH) [SRT].sdh.en.srt

Expected:
- 1 English subtitle stream titled "Main [SRT]"
- 1 English subtitle stream titled "Main (SDH) [SRT]" and flagged as SDH

Result:
- 1 English subtitle stream titled "Main [SRT]"
- 1 English subtitle stream titled "Main (SDH) [SRT].sdh"

### Jellyfin Version

10.8.10

### Environment

```markdown
- OS: Unraid 6.12.3 [Slackware 15.0 x86_64 (post 15.0 -current)]
- Linux Kernel: 6.1.38-Unraid
- Virtualization: docker
- Clients: Browser, Jellyfin Media Player 1.9.0
- Browser: Firefox 117.0b9
- FFmpeg Version: ffmpeg version 5.1.2-Jellyfin
- Playback Method: not relevant
- Hardware Acceleration: not relevant
- GPU Model: not relevant
- Plugins: not relevant
- Reverse Proxy: traefik
- Base URL: none
- Networking: not relevant
- Storage: local
```

### Please attach any screenshots here

![image](https://github.com/jellyfin/jellyfin/assets/692914/eacb4e38-6e41-4be9-9a13-a4092f21074d)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shadowghost** [comment]
This will be part of 10.9.

**Comment by jathek** [comment]
My bad! Read it as 10.8.9 instead of 10.9 for some reason. I think I will close this and reopen if it doesn't work in 10.9.
