### ISSUE TITLE
[Issue]: When transcoding jellyfin should transcode to the most effecient supported codec

### ISSUE THREAD

**Issue by Ember-ruby** [jellyfin/jellyfin#10136]
### Please describe your bug

when playing a hevc video on a device with hevc playback turned off (or not supported) jellyfin should transcode to av1 (if supported) rather than the far less efficient h264

### Jellyfin Version

10.8.z

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shadowghost** [comment]
AV1 is still a WIP in our transcoder and support will be better in 10.9. Keep in mind though that AV1 is often only viable as a transcoding target if hardware encoding is properly supported (though our FFmpeg does provide software encodnig via SVT).

**Comment by Ember-ruby** [comment]
> AV1 is still a WIP in our transcoder and support will be better in 10.9. Keep in mind though that AV1 is often only viable as a transcoding target if hardware encoding is properly supported (though our FFmpeg does provide software encodnig via SVT).

i do have hardware av1 encoding, so it'd be really nice to be able to utilize it

**Comment by srcrist** [comment]
Closing this issue as it does not reference a Jellyfin bug. Feel free to submit feature requests to features.jellyfin.org, but this particular request is already in development. AV1 transcoding is simply not released yet.
