### ISSUE TITLE
[Issue]: Confusing network settings regarding external access and proxies

### ISSUE THREAD

**Issue by jameskimmel** [jellyfin/jellyfin#10145]
### Please describe your bug

**Describe the bug**

The get Jellyfin working behind a reverse proxy, one has to enable "external access" under networking, despite having set the trusted proxy IP. 

**To Reproduce**

1. Fresh install of Jellyfin
2. Setup a reverse proxy
3. set known proxies in network settings

**Expected behavior**

External access should be possible without enabling external access. 

Another solution could be to move the known proxies field down to the external access settings. That way it is very clear that you have to enable it for the proxy to work. 

I don't quite understand what the external access setting does, so it is hard to describe a solution. In my understanding, a proxy that even sits in the same subnet, is not an external access. 

### Jellyfin Version

10.8.z

**Comment by cvium** [comment]
https://github.com/jellyfin/jellyfin/issues/6099#issuecomment-847258037

**Comment by srcrist** [comment]
Closing this issue as it does not reference an actual Jellyfin bug.
