### ISSUE TITLE
Judder/Stutter in Jellyfin but not MPV

### ISSUE THREAD

**Issue by nomonkeynodeal** [jellyfin/jellyfin#10157]
I am experiencing judder/stutter with certain files in Jellyfin, **but not in MPV**, using the exact same config file. Same problem after lots of troubleshooting and reinstalling Windows. I have been fighting this issue for months and difference is extremely palpable. I am not using any transcoding.

I posted extensive information about my config and the media, which I really don't want to reformat for this editor, at the Jellyfin forums here: https://forum.jellyfin.org/t-judder-in-jf-but-not-mpv

If anyone could take a look at that I'd really appreciate it.

**Comment by felix920506** [comment]
Closing this as it is not a valid issue report.
