### ISSUE TITLE
[Issue]: Audio stream selection issue

### ISSUE THREAD

**Issue by Onepamopa** [jellyfin/jellyfin#10152]
### Please describe your bug

Playing TV series with multiple audio streams.
The 2nd one is English which I select. On the next episode - English is selected but the 1st stream is used, which results in me having to select the first, then select the 2nd again...

Extremely inconvenient.

### Jellyfin Version

10.8.z

### if other:

10.8.10 @ Windows 10

### Environment

```markdown
- OS: Windows 10
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
Which client?

**Comment by Onepamopa** [comment]
Jellyfin app @ Samsung TV

**Comment by gummykage** [comment]
Two things you can try to see if it fixes it:
Remux all the files using copy with ffmepg / Use MKVToolsNix drop the mkv in there and remux it.
Refresh all metadata for that series.

**Comment by Onepamopa** [comment]
Already done that - switched them all to English "first" + "default = yes". That sort of works, but say the 2nd stream is needed.. the same thing will happen again.

**Comment by herby2212** [comment]
The same behaviour can be seen when using the default Web UI. The server either doesn't check if a preferred audio track is selected or doesn't know about it.

I will take a look into it.
