### ISSUE TITLE
[Issue]: IOS subtitles not diplayed (tried swiftfin)

### ISSUE THREAD

**Issue by xanderohara1** [jellyfin/jellyfin#10155]
### Please describe your bug

I'm having an issue where on my IOS devices my .srt subtitles (even though they are showing up as an option) will not be displayed on the video. I am running the latest 10.8.10 Jellyfin update. Subtitles do work on my PC firefox browser and also on my roku. I have tried turning off  "Allow subtitle extraction on the fly" and also forcing subtitles to "burn in all complex formats", yet they still do not want to be displayed I also tried getting them to show on swiftfin, yet this also didn't fix the issue. I appreciate any advice! 

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: IOS
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration: 
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gummykage** [comment]
If  you are using jellyfin ios app, set the player on the settings screen to "Native video player". After you select the subtitle and start, make sure you also turn on the subtitles in the native ios video player. Think of it as after jellyfin passes the subtitles to native video player, you still need to turn it on there also. Sometimes its listed as CC, Unknown, English, Garbled text. If you don't want to "extract subtitles on the fly" you can extract the files as a .srt file, name it the same as the movie:

For example

Jurassic Park - Web-DL 1080p H264.mkv
Jurassic Park - Web-DL 1080p H264.en.default.srt

You can just turn on the subtitles. Keep in mind if you are using extract on the fly it can take up to 10 mins for a large file 30gb + and how fast your storage + what processor you are using will all affect this. If has finished extracting it once it will just use the cached subtitles.

**Comment by srcrist** [comment]
There is insufficient information to determine how to handle this issue. Your template is incomplete. What iOS client are you using, specifically? Jellyfin Mobile for iOS or Swiftfin? Or another client entirely?
