### ISSUE TITLE
Add back openssl support to ffmpeg

### ISSUE THREAD

**Issue by vanagandr42** [jellyfin/jellyfin#1015]
**Describe the bug**
The docker image jellyfin/ffmpeg is compiled without support for openssl. Support for openssl is needed to play https urls in strm files. It worked with release 10.2.0.

**Expected behavior**
Jellyfin can play videos via https in an strm file.

**System (please complete the following information):**
 - OS: Docker
 - Browser: Chrome
 - Jellyfin Version: 10.2.1

**Additional context**
 This was actually removed with commit [1398e7bd401782451695a40019037357b23e26cf](https://github.com/jellyfin/ffmpeg-build/commit/1398e7bd401782451695a40019037357b23e26cf).

**Comment by joshuaboniface** [comment]
We can't keep `openssl` in particular because it requires `enable-nonfree` (why, I don't understand, but whatever). That said enabling `gnutls` is pretty trivial - testing that out now. CC @nvllsvm

**Comment by namgk** [comment]
gnutls doesn't work on mac, try using it with rtmps and you'll see.

**Comment by cvium** [comment]
What's the problem with gnutls on macos exactly?

Either way, we cannot enable openssl.

**Comment by JustAMan** [comment]
According to "recent" changes in OpenSSL licensing, OpenSSL 3.0+ (yet to be released) will become Apache 2.0-licensed, so it would be possible to build ffmpeg under GPLv3 with openssl.

That said, what is the problem with Docker version of ffmpeg using gnutls under Mac? I mean, you cannot run Docker under Mac directly, you run it in a (somewhat hidden AFAIK) virtual machine running Linux, so why would we care?..
