### ISSUE TITLE
[Issue]: The server reaction and scanning speed is soooo lowwwww

### ISSUE THREAD

**Issue by Zhanzhanle** [jellyfin/jellyfin#10174]
### Please describe your bug

Every time I made any change in one of my media folder, the server was lagging to update scan and took a thousand years to react. I couldn't do anything during this period. 

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS:win11
- Linux Kernel:
- Virtualization:
- Clients: browser
- Browser:edge
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model: Nvedia3060Ti
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
This is not an actionable issue.
