### ISSUE TITLE
Missing channels

### ISSUE THREAD

**Issue by RStoroy** [jellyfin/jellyfin#10182]
Why is channels missing in Live TV?
![Screenshot 2023-09-01 at 15-57-56 Jellyfin](https://github.com/jellyfin/jellyfin/assets/26773223/f131c810-1dc3-4db4-ae3e-64d06e8a61f4)
![Screenshot 2023-09-01 at 15-58-36 SOFT OTT - Number editor - IPTVEditor 4](https://github.com/jellyfin/jellyfin/assets/26773223/cdcb882a-97c8-4961-9c0e-de8eec69e4d0)

**Comment by srcrist** [comment]
Closing this issue as it does not contain a Jellyfin bug. Please visit our support communities on the forum or our Matrix/Discord server for help with configuration and troubleshooting.
