### ISSUE TITLE
[Issue]: New Media not added after moving metadata and path changes via dashboard- SOLVED via manual SQL updates 

### ISSUE THREAD

**Issue by FrankBKK** [jellyfin/jellyfin#10184]
### Please describe your bug

Some week ago I moved the Jellyfin Metadata to a new drive and changed the path data via dashboard accordingly. 
On first look all worked well. however after some time I realized that for a few libraries new data was not added. 

When browsing through the logs I noticed some ERR messages regarding missing user profile pics that pointed to the old path. 

I then used an SQLite editor and searched for rows with the old path and found several entries. 
After manually changing the path in the database JellyFin now works as intended and all new metadata was added. 

Database  library.db   Table TypedBaseItems   Field  path 
Database  jellyfin.db   Table ImageInfos  Field path 

Just to let users with similar problems know how to fix this.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS:
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sevenrats** [comment]
Hey mate, thanks for your report. Please fill out the form and removed your solved tag, manual database changes are not a solution or advisable at all. It would help a lot to attach your logs as well. Thanks!

**Comment by Bond-009** [comment]
Moving the metadata folder like this isn't supported
