### ISSUE TITLE
[Issue]: Some images are ignored by Scanning

### ISSUE THREAD

**Issue by MartinMSPedersen** [jellyfin/jellyfin#10185]
### Please describe your bug

About 500 out of 8000 images was not found by jellyfin when scanning the folder.

A work-around is renaming the files to shorter names. However it will take a long time locating the 500 images that are missing.

Eg. the file amamo_dark_white_and_blue_landscapes.png was not picked up by jellyfin. However after

```
cp amamo_dark_white_and_blue_landscapes.png amamo_dark_white_and_blue_landscap.png
```

Jellyfin found the shorter version of the file name with 38 characters in total but still not the original version with a total of 40 characters. 

[amamo_dark_white_and_blue_landscapes.png](https://20dage.dk/amamo_dark_white_and_blue_landscapes.png)

No errors found the docker logs
```
docker logs -f jellyfin

[13:58:17] [INF] [199] Emby.Server.Implementations.IO.LibraryMonitor: midjourney3 (/media/midjourney3) will be refreshed.
```

### Jellyfin Version

10.8.z

### if other:

jellyfin docker image with id: 8931b78f5536 (unstable)

### Environment

```markdown
- OS: Linux - Rocky Linux 9.2
- Linux Kernel: 5.14.0-284.25.1.el9_2.x86_64
- Virtualization: Docker
- Storage: docker bind mount on local xfs fs (efi boot)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MichaelRUSF** [comment]
Looks like [this ](https://github.com/jellyfin/jellyfin/issues/7830)is the same issue, which was fixed by this [PR](https://github.com/jellyfin/jellyfin/pull/10222). 

File was ignored b/c it had "landscape" in the filename, not due to a character limit.

**Comment by MartinMSPedersen** [comment]
yes! solved using unstable. thanks
