### ISSUE TITLE
[Issue]: Jellyfin brings up setup menu every few weeks

### ISSUE THREAD

**Issue by DragonFire125** [jellyfin/jellyfin#10193]
### Please describe your bug

Every so often jellyfin brings up the "Welcome to Jellyfin" screen I've had to go trough and setup the library again but some settings remain i have jellyfin's config and cache on my system's ssd with a hdd mounted over usb for the media

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS:Alpine Linux v3.17 x86_64 
- Linux Kernel: 5.15.112-0-lts
- Virtualization:Docker
- Clients:Browser
- Browser:Brave Version 1.56.14
- Hardware Acceleration:none
- GPU Model:UHD630
- Storage:local
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Bond-009** [comment]
Needs way more info on how you've set it up
