### ISSUE TITLE
Question regarding vpp tone mapping and hdr 10 videos in hvec main instead of hvec main 10

### ISSUE THREAD

**Issue by Mainfrezzer** [jellyfin/jellyfin#10206]
Ive noticed a peculiar behavior with one of my movie files that was a hdr 10 video.

That video has the Videocodec: HEVC Main instead of Videocodec: HEVC Main 10 and no matter what setting i used, vpp or the other tone mapping, the sdr was just broken.

Ive changed to video file manually to be the right codec and now the settings do apply.

My question in that regard is, is there a way to force vpp to tonemap files that are clearly 10 bit videos but for some reason only have the HVEC Main set?

**Comment by sevenrats** [comment]
please take your support question to our forums http://forum.jellyfin.org or to our chat space on Matrix/Discord. This space is for reporting bugs.
