### ISSUE TITLE
System.IO.InternalBufferOverflowException - Too many changes at once in directory

### ISSUE THREAD

**Issue by need4swede** [jellyfin/jellyfin#10209]
### Please describe your bug

Running v10.8 on Windows 11

I noticed that my real time monitoring wasn't working - checked logs and found this error occurring in every library:

``System.IO.InternalBufferOverflowException: Too many changes at once in directory``

I even created a test library with one movie in it and noticed that error still occurs. 
So my logs look something like this:

```
[2023-09-11 15:51:05.981 -07:00] [ERR] [113] Emby.Server.Implementations.IO.LibraryMonitor: Error in Directory watcher for: "\\<SERVER ADDRESS>\Movies"
System.IO.InternalBufferOverflowException: Too many changes at once in directory:\\<SERVER ADDRESS>\Movies.
[2023-09-11 15:51:05.989 -07:00] [INF] [113] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "\\<SERVER ADDRESS>\Movies"
```

What can I do about this? I would prefer not to have to run a manual scan every time I add content.

Thank you!

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Windows 11
```

### Jellyfin logs

```shell
[2023-09-11 15:51:05.981 -07:00] [ERR] [113] Emby.Server.Implementations.IO.LibraryMonitor: Error in Directory watcher for: "\\<SERVER ADDRESS>\Movies"
System.IO.InternalBufferOverflowException: Too many changes at once in directory:\\<SERVER ADDRESS>\Movies.
[2023-09-11 15:51:05.989 -07:00] [INF] [113] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "\\<SERVER ADDRESS>\Movies"
```
```


### FFmpeg logs

_No response_

### Please attach any browser or client logs here

_No response_

### Please attach any screenshots here

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SamJongenelen** [comment]
I've look around and noticed that the `FilesystemWatcher` will throw that exception, when it cannot keep up with the number of changes.  This will cause the buffer to overflow.
This is JF code for initializing (`LibraryMonitor.cs`) the FSW 
![image](https://github.com/jellyfin/jellyfin/assets/3382443/58f1cc02-8c8e-4403-9ccc-4745f0d62745)

I suspect your share is subject to many changes. To workaround,  lower the write actions and or change the share to only point to the low-write file location.

**Comment by SamJongenelen** [comment]
From a dev perspective, I've read the best workaround for the API would be to offload the FSW directly into a ConcurrentQueue and process the events in the background. I was wondering perhaps `IHostedService` with a [Channel](https://flerka.github.io/personal-blog/2020-01-23-communication-with-hosted-service-using-channels/ ) would be a good fit?
