### ISSUE TITLE
Media discovered as Movie won't Discover as Show

### ISSUE THREAD

**Issue by ricks03** [jellyfin/jellyfin#10204]
### Please describe your bug

I have a Library that is Content Type Mixed Movies and Shows. 

However, it has problems when I have a Show that has the same name as a Movie.
Examples: 
Supergirl recordings I have are from the TV show, identified as the Movie
The Rookie recordings I have are from the TV show, identified as a Movie
Star Trek recordings I have are from ToS, identified as a Movie

When I look at the Properties of SuperGirl and How I Met Your Mother. I'm given the option to "Identify" and "Media Info"
When I look at the Properties for "The Rookie" I am not.

I have the TVDB plug-in installed. I would expect when this happens I could just add the ID from TVDB and fix this. But the Identify option from SuperGirl and How I Met Your Mother don't include the ability to set the TVID. 

For the Rookie, I don't even get the option to Identify. The Rookie menu is Shuffle, Add to Collection, Add to Playlist, Delete Media, Edit Metadata, Edit Images, Refresh Metadata.  (<< List A)

For Supergirl that list is longer: Play, Play from Here, Add to Collection, add to playlist, Delete media, Download, Copy Stream URL, Edit Metadata, Edit Images, Edit Subtitles, Identify, Media Info, and Refresh Metadata.  (< List B).

If I delete and recreate the entire library, I get the same results. 

Looking at the shows I have: 
List A: The Big Bang Theory, the Rookie, Stargate SG-1
List B: GunSmoke, How I Met Your Mother, Star Trek, Stargate Atlantis, Supergirl

If I select Properties > Edit Metadata  I can change the Content Type from Inherit to Shows, but they still stay on the same List (List A or List B) respectively. 

Refresh metadata ("Replace all metadata") after that point doesn't appear to change anything.

Thanks.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Raspberry Pi Debian : Bullseye
- Linux Kernel:
- Virtualization:
- Clients: 
- Browser: Chrome
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration: No
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Please attach any screenshots here

![image](https://github.com/jellyfin/jellyfin/assets/41844549/f9808f92-e6a6-4f16-a71c-8a3c338b8ae6)
![image](https://github.com/jellyfin/jellyfin/assets/41844549/1e9551e7-f4d8-4e27-9293-376adf7b9565)
![image](https://github.com/jellyfin/jellyfin/assets/41844549/b4541425-ab1f-404b-af87-55e57864a55f)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by srcrist** [comment]
Closing this issue as it does not reference an actual Jellyfin bug. Mixed libraries can only provide reliable metadata if they are paired with an external metadata manager like TinyMediaManager that can generate bespoke NFO metadata for each item. It is strongly advised against using the mixed library type if you want to rely on Jellyfin's integrated metadata retrieval. Separate movie and television libraries are highly recommended.
