### ISSUE TITLE
[Issue]: Flatpak install not respecting NoAutoRunWebApp

### ISSUE THREAD

**Issue by Danzig67** [jellyfin/jellyfin#10208]
### Please describe your bug

I understand that NoAutoRunWebApp is essentially the default behaviour since version 10.7.

I am running flatpak version 10.8.10 and autorun flatpak run org.jellyfin.JellyfinServer at startup and it launches the server perfectly fine but it also opens my default broswer (Firefox) and loads the web gui in a new tab.

It is not the end of the world but it would be good to disable this feature, particularly if the default behaviour is supposed to be not to launch the web gui by default (after setup wizard complete).

### Jellyfin Version

Other

### if other:

10.8.10

### Environment

```markdown
- OS:PopOS
- Linux Kernel:6.4.6-76060406-generic
- Browser: Firefox
- GPU Model:NVIDIA GeForce GTX 1070
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nielsvanvelzen** [comment]
The flatpak package is community maintained, you can report issues here: https://github.com/flathub/org.jellyfin.JellyfinServer

**Comment by Bond-009** [comment]
Indeed an issue with the flatpak
https://github.com/flathub/org.jellyfin.JellyfinServer/blob/master/org.jellyfin.JellyfinServer.sh

**Comment by Chillsmeit** [comment]
Just to answer this issue in case someone stumbles upon this.
The jellyfin server flatpak opening the browser on startup can be disabled by using this flag:
`flatpak run --command=jellyfin org.jellyfin.JellyfinServer`

In my case I modified my `org.jellyfin.JellyfinServer.desktop` in `~/.config/autostart` to be like this:
```
[Desktop Entry]
Name=Jellyfin Server
Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=jellyfin org.jellyfin.JellyfinServer
Type=Application
Icon=org.jellyfin.JellyfinServer
Categories=AudioVideo;
X-Flatpak=org.jellyfin.JellyfinServer
```

Hope this helps
