### ISSUE TITLE
[Issue]: media directories served by ZFS have a ".zfs" directory, and with snapshots, duplicate the library contents, unable to exclude!

### ISSUE THREAD

**Issue by fermulator** [jellyfin/jellyfin#10215]
### Please describe your bug

Consider first, https://jellyfin.org/docs/general/server/media/excluding-directory/ ; OK we are able to exclude a directory by adding a `.ignore` file into it. I suppose that is "neat" (though slightly annoying to pollute the filesystem solely for a "hint" to Jellyfin).

Now consider this scenario;
* Admin has a ZFS storage filesystem on Linux zfsonlinux.org
* Admin uses ZFS snapshots https://docs.oracle.com/cd/E19253-01/819-5461/gbcya/index.html
* Admin remote mounts (or has local datasets)
* Admin is running jellyfin in docker (volume binding)
* Jellyfin imports media to these storage locations

The PROBLEM, is that the zfs dataset will contain a directory called `.zfs` (for zfs specific content) - and specifically in there, `.zfs/snapshot/*` contains DUPLICATIONS of any and all data within the dataset :( -- this means that jellyfin is trolling and finding duplicate media content for as many snapshots that may exist.

Cannot even workaround this problem by adding `.ignore` into there because the `.zfs` directory is READ-ONLY (by user or root).

Jellyfin should ideally provide a means to target `glob*` or `regex` exclusions - instead of relying on a `.ignore` file in the directory subsystem?

Open to alternative ways to fix/address.

---
ABOUT REFS

`[23:10:39] [INF] [1] Main: Jellyfin version: 10.8.10`

docker volume in docker-compose file:
```
      - /mnt/myserver/tv:/tv:ro
      - /mnt/myserver/movies:/movies:ro 
```

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: (N/A docker,, `jellyfin/jellyfin`)
- Linux Kernel:
- Virtualization:
- Clients: N/A
- Browser: N/A
- FFmpeg Version: `5.1.3`
- Playback Method:
- Hardware Acceleration: N/A
- GPU Model: N/A
- Plugins: N/A
- Reverse Proxy: N/A
- Base URL: N/A
- Networking: N/A
- Storage: `/movies` and `/tv`, via docker volume bind, to host `NFS` mount, backed by `zfs`
```

### Jellyfin logs

```shell
Interestingly, also jellyfin is throwing exceptions in logs :) 

System.IO.IOException: Stale file handle : '/movies/.zfs/snapshot/AutoM-2023-09'
System.IO.IOException: Stale file handle : '/tv/.zfs/snapshot/AutoW-2023-37'

[23:44:42] [ERR] [15] Emby.Server.Implementations.IO.LibraryMonitor: Error in Directory watcher for: /movies
System.IO.IOException: Stale file handle : '/movies/.zfs/snapshot/AutoM-2023-09'
[23:44:42] [INF] [15] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path /movies
[23:44:43] [ERR] [8] Emby.Server.Implementations.IO.LibraryMonitor: Error in Directory watcher for: /tv
System.IO.IOException: Stale file handle : '/tv/.zfs/snapshot/LAST_BACKUP'


```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fermulator** [comment]
(on second glance ... I'm actually not getting duplicates due to the `.zfs` directory :) ... in fact those IO exceptions are probably halting the scan and preventing it?)

**Comment by srcrist** [comment]
Issue closed by https://github.com/jellyfin/jellyfin/pull/10219

**Comment by fermulator** [comment]
nice! thanks for the fix team
