### ISSUE TITLE
[Issue]: Deleting Media doesn't remove it from playlists

### ISSUE THREAD

**Issue by sic6SaNdMaN** [jellyfin/jellyfin#10216]
Hello.

If I have custom playlists (for movies) and anytime any media gets deleted that is in (one of) those playlists, it isn't removed from the playlist(.xml).
So, to be clear: The movie is not visible in the playlist after deletion anymore, but it is still present in the playlist.xml - file.

This also causes the "reordering playlists doesn't work" - bug, which is open for over two years now:
https://github.com/jellyfin/jellyfin-web/issues/2684

So, when deleting media, check all playlists and collections and remove the entries there.

Besides that it also would be great to trigger the generation of new images for the affected playlists, because the movie (in this case) perhaps isn't in the playlist anymore but it's cover is still shown in the picture (collage).

### Jellyfin Version

10.8.9

### Environment

```markdown
- OS: Raspbian GNU/Linux 11
- Linux Kernel: Linux RPi4-1 6.1.19-v8+
- Virtualization: none
- Clients: Chrome Linux/Windows, (doesn't matter, but anyways: Kodi on Andoid TV)
- Browser: Chrome Linux/Windows
- FFmpeg Version: ffmpeg version 4.3.5-0+deb11u1+rpt3
- Playback Method: native paths
- Hardware Acceleration: Android TV integrated
- GPU Model: Android TV integrated
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking: 1000 MBit/s LAN
- Storage: Samba/NFS on Raspberry Pi
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shadowghost** [comment]
I looked at deferring this to when media is deleted but all playlists would need to be checked on each media deletion. Depending on how many entities are removed this introduces a lot of overhead.

Could be temporarily fixed by introducing a scheduled job cleaning up playlists as proposed for collections - or do both in one job.

**Comment by sic6SaNdMaN** [comment]
I doubt, that a scheduled job, that does the exact same thing on a regular basis, is less overhead, than doing it once...
But OK, I'll take that as a workaround.

**Comment by Shadowghost** [comment]
There is a difference of iterate over all playlists and collections once and remove all removed items and iterate over all playlists and collections whenever a single item is removed.

**Comment by sic6SaNdMaN** [comment]
OK, that's true. Normally one watches a movie and than deletes it.
But OK, I get your point.
The advantage of triggering the cleaning immediately is that the playlists aren't broken until the scheduled job ran.

The question is, how big the impact really is.
When it comes to the decision if it is going to be a scheduled job or triggered immediately, the developer should benchmark this.
Make one playlist, copy it a 1000 times (i. e. with a counter in the name), delete a movie which is in this playlists and then measure the time for the cleanup process.
I hope, that the impact isn't too much of an issue, but that has to be seen.
