### ISSUE TITLE
Series doesn't show up in Next up after previous episode was deleted

### ISSUE THREAD

**Issue by SenorSmartyPants** [jellyfin/jellyfin#1022]
Watch an episode of a series. Only one episode on disk, delete after watching. When the next episode is added to JF it will not show up in the Next Up section.

**Expected behavior**
New episode should show up in Next Up section if JF knows you have been watching this series.

**System (please complete the following information):**
 - Docker ARMHF
 - Browser: [e.g. Firefox, Chrome, Safari]
 - Jellyfin Version: 10.2.1

**Comment by SenorSmartyPants** [comment]
I'd still like this looked into. I use trakt, so JF will know if I've been watching a series even when I get the first new episode on disk.

**Comment by SenorSmartyPants** [comment]
beep

**Comment by JustAMan** [comment]
@SenorSmartyPants I take it that you've checked on 10.4.1 and it's still an issue, right? (I think it is, but just wanting to be extra-sure)

**Comment by SenorSmartyPants** [comment]
I just update to 10.4.1 today, and yes it is still an issue.

**Comment by cvium** [comment]
I don't get why you expect Jellyfin to keep track of the data when you delete the episode tbh. We would have to keep the episode in the db forever...

**Comment by patel8786** [comment]
@cvium well the alternative is to keep the physical file around forever if deleting the file means the DB entry is also deleted. Also there's often a limit 30/60 days when items in a "next up" list go stale and get removed anyway.

This is also a problem for me since I use the API to find played items and delete the file.

**Comment by Freddster** [comment]
Trying to get some life back into this issue as this is one of my main gripes with JF.

@cvium You are correct that it would need to be in the db forever, but keeping the file on the disk to avoid the issue results in even more space being used. As someone who watches many different series and tends to delete an episode after it has been watched, the usability of having the next episode in the "next up" section, despite previous episodes being deleted, is a huge convenience factor. 
I don't know how much space it would take to store some of the metadata of an episode, and if it has been watched and when, but it should take up less space than saving an entire 1-hour episode in decent quality.

The feature could be disabled by default, and then by enabling it in the settings, JF will start to keep track of previously watched episodes. Additional options could be present such as setting a limit on how long JF should track an item, which might be two years, given that some people binge an entire season in a weekend and then wait a whole year or more for the next season to come out. 

As an alternative to storing a ton of possibly useless data, I suggest using something like Trakt and then, through that API, figuring out if a person has watched the previous episode (given that it is possible). This could also enable a warning that an episode has not been seen, e.g., episode 3 has been watched and deleted, episode 5 is added to JF, and a "warning" appears informing the user that episode 4 has not been watched.
I am not sure if the last thing about "warnings" is useful to everyone, but it could be an additional usability feature.

**Comment by zilexa** [comment]
Please give this issue some attention

**Comment by sevenrats** [comment]
please open a discussion or feature request to replace this stale issue. thanks.

**Comment by MXC1** [comment]
This has been marked as done, but I don't believe the issue is fixed?
