### ISSUE TITLE
solve the problem that jellyfin in docker randomly unable to transcode with NVIDIA

### ISSUE THREAD

**Issue by GJCav** [jellyfin/jellyfin#10238]
**Media Info of the file**
not responsible

**Logs**
not responsible

**FFmpeg Logs**

*highly responsible* and I stripped off irrelevant parts.

```
ffmpeg version 5.1.3-Jellyfin Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-libs=-lfftw3f --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libsvtav1 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[AVHWDeviceContext @ 0x56010853aa80] cu->cuInit(0) failed -> CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
Device creation failed: -542398533.
Failed to set value 'cuda=cu:0' for option 'init_hw_device': Generic error in an external library
Error parsing global options: Generic error in an external library
```

The key clue is `cu->cuInit(0) failed -> CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected`. It implies that something went wrong with the NVIDIA GPU. And ran`nvidia-smi` with:

```
docker exec -it jellyfin nvidia-smi
```

It failed with error `Failed to initialize NVML: Unknown Error`, which indicated that jellyfin in docker lost the connection to my nvidia card!

After searching, the problem is related to a bug in nvidia driver and the problem is described in https://github.com/NVIDIA/nvidia-docker/issues/1730 

You can find a reproducing method and a yet-not-work workaround in it. To fully resolve it, in addition to the workaround, we need to modify the docker-compose file by adding the following lines:

```
devices:
  - /dev/nvidia-uvm
  - /dev/nvidia-uvm-tools
  - /dev/nvidia-modeset
  - /dev/nvidiactl
  - /dev/nvidia0
```

and in my situation, it solved my problem. So please consider updating the official [docker-compose file](https://jellyfin.org/docs/general/administration/hardware-acceleration/nvidia#configure-with-linux-virtualization).

NOTE: I am not confident about the `/dev/nvidia0` and I don't know what will happen if there are several Nvidia cards in your system. Further investigation is required but I only have 1 card so may the jellyfin developers test it.

**Server System (please complete the following information):**
 - OS: Docker 24.0.6 on Ubuntu 22 LTS
 - Jellyfin Version: 10.8.10
 - Hardware settings & device: NVENC on GTX1050
 - Reverse proxy: no
 - Other hardware notes: no
 
**Client System (please complete the following information):**

it is client independent problem.

**Comment by nyanmisaka** [comment]
![image](https://github.com/jellyfin/jellyfin/assets/14953024/9accd76d-6e9e-466f-b61e-48c105be0dfd)

Didn't you see the NOTE in that chapter?

Since this is an upstream driver issue, tell NVIDIA to fix it. https://stackoverflow.com/a/76646962

**Comment by GJCav** [comment]
> ![image](https://user-images.githubusercontent.com/14953024/268517659-9accd76d-6e9e-466f-b61e-48c105be0dfd.png)
> 
> Didn't you see the NOTE in that chapter?
> 
> Since this is an upstream driver issue, tell NVIDIA to fix it. https://stackoverflow.com/a/76646962

my bad, i skip it as i don't understand what will happen at the fisrt time reading it.
