### ISSUE TITLE
[Issue]: 点击演员后一直加载

### ISSUE THREAD

**Issue by xcstg** [jellyfin/jellyfin#10235]
### Please describe your bug

查询了帖子https://github.com/jellyfin/jellyfin/issues/4352以后，在system.xml中添加了
    <MetadataOptions>
      <ItemType>Person</ItemType>
      <DisabledMetadataSavers />
      <LocalMetadataReaderOrder />
      <DisabledMetadataFetchers>
        <string>TheMovieDb</string>
      </DisabledMetadataFetchers>
      <MetadataFetcherOrder />
      <DisabledImageFetchers />
      <ImageFetcherOrder />
然后保存并重启了，奇怪的是重启后配置文件似乎还原了，配置无法生效

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS:[synology]
- Linux Kernel:
- Virtualization:[Docker]
- Clients:[Browser]
- Browser:[EDGE]
- FFmpeg Version:[10.7.7]
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xcstg** [comment]
<MetadataOptions>
      <ItemType>Person</ItemType>
      <DisabledMetadataSavers />
      <LocalMetadataReaderOrder />
      <DisabledMetadataFetchers>
        <string>TheMovieDb</string>
      </DisabledMetadataFetchers>
      <MetadataFetcherOrder />
      <DisabledImageFetchers />
      <ImageFetcherOrder />

**Comment by felix920506** [comment]
请更新至最新版本（10.8.11）
Please update to the latest version (10.8.11)

**Comment by sevenrats** [comment]
10.7 is EOL
