### ISSUE TITLE
Tags Allow Feature

### ISSUE THREAD

**Issue by fscorrupt** [jellyfin/jellyfin#10233]
Currently there only is `Block items with Tags` i would need to tag every movie/show with a block tag for my daughter.

If we could have a Show only media with a certain tag, i could tag the shows/movies i want that my daughter can see/play.

Could this be implemented?

Thanks! Rg FSCorrupt

**Comment by sjorge** [comment]
There is a feature request for it here : https://features.jellyfin.org/posts/235/parental-controls-allow-items-with-tags
