### ISSUE TITLE
Violation of the Filesystem Hierarchy Standard

### ISSUE THREAD

**Issue by grawlinson** [jellyfin/jellyfin#10236]
https://github.com/jellyfin/jellyfin/blob/61155adecd8a69bb476487f9fc81175b0c4185b7/Jellyfin.Server/Helpers/StartupHelpers.cs#L117

Architecture independent files (ie anything that isn’t a binary) are supposed to be found in `/usr/share`, not `/usr/lib` as per the Filesystem Hierarchy Standard [spec](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/index.html).

**Comment by joshuaboniface** [comment]
Please provide more detail. Our Debian install is definitely in `/usr/share/jellyfin/web`. Which OS is this, and which install method?

**Comment by cvium** [comment]
Seems fine to me

https://github.com/jellyfin/jellyfin/blob/master/debian/conf/jellyfin#L22

**Comment by grawlinson** [comment]
I've just packaged this for Arch Linux, basing the setup upon the [Fedora files](https://github.com/jellyfin/jellyfin/tree/master/fedora) because they are simpler (all in one file, as opposed to Debian's split across multiple files).

Except that I am packaging `jellyfin-web` into `/usr/share/jellyfin-web`, as opposed to the Fedora [spec](https://github.com/jellyfin/jellyfin-web/blob/52588d46d63f3d7e1621db48a5fcd0a247139ce9/fedora/jellyfin-web.spec#L41-L43) file.
