### ISSUE TITLE
[Issue]: External subtitle not download when user get media

### ISSUE THREAD

**Issue by Monirzadeh** [jellyfin/jellyfin#10248]
### Please describe your bug

if your media has external subtitle (like srt beside video file) it is not download when user Download music
1. go to a a file that jellyfin detect an external subtitle
2. click three dot
3. click Download

just video downloaded without external subtitle

### Jellyfin Version

10.8.9

### Environment

```markdown
- OS:
- Linux Kernel:
- Virtualization: Docker
- Clients: Browser, Android, etc
- Browser: Firefox or Chrome base 
- Storage: Local
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
There are multiple existing feature requests for this to be added over at features.jellyfin.org
