### ISSUE TITLE
Random album order

### ISSUE THREAD

**Issue by AlexKraak** [jellyfin/jellyfin#1026]
**Describe the feature you'd like**

An option to have the list of albums be random, or a list of random albums on the music library suggestion page similar to the recent music section or recently played section

**Comment by onny** [comment]
Could such an feature be accomplished by writing a plugin?

**Comment by AlexKraak** [comment]
I'm unsure, Is there a source of documentation for plugin writing? if so i could give it an attempt.

**Comment by JustAMan** [comment]
> Is there a source of documentation for plugin writing? if so i could give it an attempt.

@LogicalPhallacy was working on making an example, have a look here: https://github.com/LogicalPhallacy/jellyfin-plugin-example

**Comment by AlexKraak** [comment]
Oh deadly, I'll take a look into this and see what i can figure out :)
