### ISSUE TITLE
mp2 identified as mp3 and errored during playback.

### ISSUE THREAD

**Issue by SplitMilky** [jellyfin/jellyfin#10279]
**Media Info of the file**

> General
> Complete name                            : I:\Movies\Movie.mp4
> Format                                   : MPEG-4
> Format profile                           : Base Media
> Codec ID                                 : isom (mp41/avc1)
> File size                                : 2.97 GiB
> Duration                                 : 1 h 30 min
> Overall bit rate                         : 4 718 kb/s
> Frame rate                               : 23.976 FPS
> Encoded date                             : 2023-09-21 19:23:00 UTC
> Tagged date                              : 2023-09-21 19:23:00 UTC
> Writing application                      : vlc 3.0.18 stream output
> 
> Video
> ID                                       : 2
> Format                                   : AVC
> Format/Info                              : Advanced Video Codec
> Format profile                           : High@L4
> Format settings                          : CABAC / 4 Ref Frames
> Format settings, CABAC                   : Yes
> Format settings, Reference frames        : 4 frames
> Codec ID                                 : avc1
> Codec ID/Info                            : Advanced Video Coding
> Duration                                 : 1 h 30 min
> Bit rate                                 : 4 585 kb/s
> Width                                    : 1 920 pixels
> Height                                   : 1 080 pixels
> Display aspect ratio                     : 16:9
> Frame rate                               : 23.976 (23976/1000) FPS
> Color space                              : YUV
> Chroma subsampling                       : 4:2:0
> Bit depth                                : 8 bits
> Scan type                                : Progressive
> Bits/(Pixel*Frame)                       : 0.092
> Stream size                              : 2.88 GiB (97%)
> Writing library                          : x264 core 155
> Encoding settings                        : cabac=1 / ref=3 / deblock=1:0:0 / analyse=0x3:0x13 / me=hex / subme=7 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=6 / lookahead_threads=1 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=23 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=crf / mbtree=1 / crf=23.0 / qcomp=0.60 / qpmin=10 / qpmax=51 / qpstep=4 / ip_ratio=1.40 / aq=1:1.00
> Language                                 : English
> Encoded date                             : 2023-09-21 19:23:00 UTC
> Tagged date                              : 2023-09-21 19:23:00 UTC
> mdhd_Duration                            : 5405132
> Codec configuration box                  : avcC
> 
> Audio
> ID                                       : 1
> Format                                   : MPEG Audio
> Format version                           : Version 1
> Format profile                           : Layer 2
> Codec ID                                 : mp4a-6B
> Duration                                 : 1 h 30 min
> Bit rate mode                            : Constant
> Bit rate                                 : 128 kb/s
> Channel(s)                               : 2 channels
> Sampling rate                            : 44.1 kHz
> Compression mode                         : Lossy
> Stream size                              : 82.3 MiB (3%)
> Language                                 : English
> Encoded date                             : 2023-09-21 19:23:00 UTC
> Tagged date                              : 2023-09-21 19:23:00 UTC
> mdhd_Duration                            : 5405074

**Logs**

> DeviceIdentification { FriendlyName: "Media Room TV", ModelNumber: "100", SerialNumber: null, ModelName: "MediaRenderer", ModelDescription: "Sony 2017 4K RVU TV", ModelUrl: "", Manufacturer: "Sony Corporation", ManufacturerUrl: "http://www.sony.net/", Headers: [] }
> [2023-09-25 15:51:59.632 -03:00] [INF] [17] Emby.Dlna.Main.DlnaEntryPoint: DLNA Session created for "Media Room TV" - "MediaRenderer"
> [2023-09-25 15:52:10.157 -03:00] [INF] [24] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.1.41" request
> [2023-09-25 15:54:45.307 -03:00] [INF] [13] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
> [2023-09-25 15:55:04.309 -03:00] [INF] [13] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "User n' User". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
> [2023-09-25 15:55:04.344 -03:00] [INF] [13] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile="AndroidTV-libVLC", Path="I:\Movies\Movie.mp4", AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=DirectPlay, TranscodeReason=0 ) "media:/videos/f056114c-4234-87ed-56a3-8ade24a0477f/stream.mov?MediaSourceId=f056114c423487ed56a38ade24a0477f&Static=true&VideoCodec=h264&AudioCodec=mp3&AudioStreamIndex=0&api_key=<token>&Tag=df4567adaa11d451ad3e1a0ae216fc81"
> [2023-09-25 15:55:04.504 -03:00] [INF] [13] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "User n' User". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
> [2023-09-25 15:55:04.505 -03:00] [INF] [13] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile="AndroidTV-ExoPlayer", Path="I:\Movies\Movie.mp4", AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=DirectPlay, TranscodeReason=0 ) "media:/videos/f056114c-4234-87ed-56a3-8ade24a0477f/stream.mov?MediaSourceId=f056114c423487ed56a38ade24a0477f&Static=true&VideoCodec=h264&AudioCodec=mp3&AudioStreamIndex=0&api_key=<token>&Tag=df4567adaa11d451ad3e1a0ae216fc81"
> [2023-09-25 15:55:06.320 -03:00] [INF] [37] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "User n' User". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
> [2023-09-25 15:55:06.321 -03:00] [INF] [37] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile="AndroidTV-libVLC", Path="I:\Movies\Movie.mp4", AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=DirectPlay, TranscodeReason=0 ) "media:/videos/f056114c-4234-87ed-56a3-8ade24a0477f/stream.mov?MediaSourceId=f056114c423487ed56a38ade24a0477f&Static=true&VideoCodec=h264&AudioCodec=mp3&AudioStreamIndex=0&api_key=<token>&Tag=df4567adaa11d451ad3e1a0ae216fc81"
> [2023-09-25 15:55:06.357 -03:00] [INF] [37] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Android TV" "0.15.12" playing "Movie". Stopped at "0" ms
> [2023-09-25 15:55:06.402 -03:00] [INF] [13] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "User n' User". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
> [2023-09-25 15:55:06.404 -03:00] [INF] [13] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile="AndroidTV-ExoPlayer", Path="I:\Movies\Movie.mp4", AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=DirectPlay, TranscodeReason=0 ) "media:/videos/f056114c-4234-87ed-56a3-8ade24a0477f/stream.mov?MediaSourceId=f056114c423487ed56a38ade24a0477f&Static=true&VideoCodec=h264&AudioCodec=mp3&AudioStreamIndex=0&api_key=<token>&Tag=df4567adaa11d451ad3e1a0ae216fc81"
> [2023-09-25 15:55:08.112 -03:00] [INF] [35] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "User n' User". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
> [2023-09-25 15:55:08.114 -03:00] [INF] [35] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile="AndroidTV-libVLC", Path="I:\Movies\Movie.mp4", AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=DirectPlay, TranscodeReason=0 ) "media:/videos/f056114c-4234-87ed-56a3-8ade24a0477f/stream.mov?MediaSourceId=f056114c423487ed56a38ade24a0477f&Static=true&VideoCodec=h264&AudioCodec=mp3&AudioStreamIndex=0&api_key=<token>&Tag=df4567adaa11d451ad3e1a0ae216fc81"
> [2023-09-25 15:55:08.143 -03:00] [INF] [35] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Android TV" "0.15.12" playing "Movie". Stopped at "0" ms
> [2023-09-25 15:55:08.199 -03:00] [INF] [37] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "User n' User". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
> [2023-09-25 15:55:08.201 -03:00] [INF] [37] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile="AndroidTV-ExoPlayer", Path="I:\Movies\Movie.mp4", AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=DirectPlay, TranscodeReason=0 ) "media:/videos/f056114c-4234-87ed-56a3-8ade24a0477f/stream.mov?MediaSourceId=f056114c423487ed56a38ade24a0477f&Static=true&VideoCodec=h264&AudioCodec=mp3&AudioStreamIndex=0&api_key=<token>&Tag=df4567adaa11d451ad3e1a0ae216fc81"
> [2023-09-25 15:55:10.653 -03:00] [INF] [35] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Android TV" "0.15.12" playing "Movie". Stopped at "0" ms

**FFmpeg Logs**

**Stats for Nerds Screenshots**
?

**Server System (please complete the following information):**
 - OS: Windows 11 22H2 Build 22621.2271
 - Jellyfin Version:10.8.10
 - Hardware settings & device: RTX 3080  i9 11900K
 - Reverse proxy: ? Used default install didnt install database

 
**Client System (please complete the following information):**
 - Device: Sony 2017 4K RVU TV (XBR75X900F)
 - OS: Android 9
 - Client: Android

Client indicates there are playback errors and will try again. Play back never starts.  I changed the container from MP4 to MKV and it worked fine.   Maybe this is a bug in the client jellyfin software.  I'm not sure so I put in playback issue.

**Comment by Shadowghost** [comment]
Seems like the client announces direct play and fails to do so

**Comment by SplitMilky** [comment]
Could that be related to the contents of the mp4 container being misidentified? When I select the movie it shows mp3 inside the mp4 container but it is mp2 or mp4a-6B (I seen some people had issues elsewhere with this ID)
