### ISSUE TITLE
[Issue]: After Update to 10.8.11 cant login anymore

### ISSUE THREAD

**Issue by solisinvictum** [jellyfin/jellyfin#10280]
### Please describe your bug

After Updating to 10.8.11, its impossible to login anymore. 

If visiting the web ui, following is shown:

![grafik](https://github.com/jellyfin/jellyfin/assets/94938946/d93ef52f-95e2-486a-8744-d78b4c0570ee)

![grafik](https://github.com/jellyfin/jellyfin/assets/94938946/9dc4c7cf-d6a2-4800-b3c0-57d748fbafec)

All clients cant login anymore (Smartphones, FireTV Sticks, etc). 

After restarting the server, only for 1-2 minutes it is possible to log in. After that time, the Wizards shows up again. 

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Debian 12
- Linux Kernel: latest debian available
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
Cant login to obtain logs
```

### FFmpeg logs

```shell
Cant login to obtain logs
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cvium** [comment]
Have you tried clearing the browser cache?

**Comment by solisinvictum** [comment]
> Have you tried clearing the browser cache?

Yes. tried other browsers and OS'es too. But this seems to be a bigger problem, because like said Apps like Jellyfin for FireTV, Kodi, Smartphones etc cant log in anymore. I just rolled back a VM Image prior the update (10.8.10).

**Comment by solisinvictum** [comment]
Ok, sry. My Issue. I totaly forgot the VM is running arch not debian.

After little investigation, this seems to be the problem: 

https://github.com/jellyfin/jellyfin/issues/10236
https://bugs.archlinux.org/task/79712
https://aur.archlinux.org/packages/jellyfin-server

Im unsure if i should do this:  https://aur.archlinux.org/packages/jellyfin-server#comment-934026

Or wait for fixes from upstream?

**Comment by kauron** [comment]
I'm having the same issue in ArchLinux, after updating from `jellyfin-{server,web}-bin` 10.8.10 (from the aur) to `jellyfin-{server,web}` 10.8.11 from the official repositories.

@solisinvictum can you remember what the action recommended by the aur comment you linked was? The package was deleted from the AUR and I can't find the comment (there's no recent archive on the wayback machine...)

**Comment by solisinvictum** [comment]
@kauron: Yeah there was written, to move to old config locations etc to the new one. Sry, didnt reminder anymore which paths exactly. 

Because this is only a small instance for me and family, i stopped after a hour working on it with trial & error, and simply removed jellyfin, purged any config, and reinstalled jellyfin complete new from repo and configured anything new.

**Comment by stegl** [comment]
i have the same problem updating from jellyfin_10.8.11_windows-x64 to jellyfin_10.8.13_windows-x64
it looks like all data from older version was deleted
