### ISSUE TITLE
jellyfin wigs out 

### ISSUE THREAD

**Issue by lawrence1986101** [jellyfin/jellyfin#10282]
### Please describe your bug

The issue is that I use your Docker in Unraid. When I install Docker in the edit, I have it set to /tmp for transcoding. Jellyfin will boot, but once I get into the dashboard playback and try to edit the transcode path to /transcode Jellyfin will just wig out after a restart. It will stay in my media just with an endless spinning thing until you put back the transcode path to the factory, which was /config/data/transcodes. This needs to be fixed because I don't even know where /config/data/transcodes are. I have never used it. Where is the /config/data/transcodes going? Is that still going to my /tmp?

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS:
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dgalli1** [comment]
I'm sorry but this sounds like a config mistake. What are the permissions of /transcode in the container?

And you can see the host path for /config/data/transcodes clearly if you look at the docker config.

**Comment by lawrence1986101** [comment]
There is no misconfig error. I have been using these same paths on Plex without issue. normally I would change the Transcode path: I'm jellyfin to /transcode just like plex 

    On Tuesday, September 26, 2023 at 02:23:23 AM EDT, Damian Galli ***@***.***> wrote:  
 
 


I'm sorry but this sounds like a config mistake. What are the permissions of /transcode in the container?

And you can see the host path for /config/data/transcodes clearly if you look at the docker config.

**Comment by 1337joe** [comment]
Jellyfin isn't Plex: blindly copying configurations from plex isn't a recipe for success.

`/config/data/transcodes` goes to `<wherever your config volume is>/data/transcodes`. Unless you're adding it as a volume `/transcode` doesn't exist in the jellyfin container, so if you're determined to use that path you'll have to add it.

I don't use unraid, but [this](https://docs.unraid.net/unraid-os/manual/docker-management/#volume-mappings) looks like the documentation on how to set it up.

Whatever you do, just don't set your transcode directory to somewhere with files you want to keep since Jellyfin has a cleanup task that will routinely delete everything in transcodes.

**Comment by lawrence1986101** [comment]
That's kind of the point. I tried to point it to the file. I would be using it because Plex is using it, so the file should already be there.this is how why i use /tmp in the docker and inside Plex I use /transcode Plex transcode in Ram


| 
| 
|  | 
Plex transcode in Ram

Hi, I'm trying to set up Plex to transcode to RAM. I have set the Docker container to.. container path: /transco...
 |

 |

 |





    On Tuesday, September 26, 2023 at 11:06:29 AM EDT, Joe Rogers ***@***.***> wrote:  
 
 


Jellyfin isn't Plex: blindly copying configurations from plex isn't a recipe for success.

/config/data/transcodes goes to <wherever your config volume is>/data/transcodes. Unless you're adding it as a volume /transcode doesn't exist in the jellyfin container, so if you're determined to use that path you'll have to add it.

I don't use unraid, but this looks like the documentation on how to set it up.

Whatever you do, just don't set your transcode directory to somewhere with files you want to keep since Jellyfin has a cleanup task that will routinely delete everything in transcodes.

**Comment by 1337joe** [comment]
> I would be using it because Plex is using it, so the file should already be there.

This is not how containers work. In the plex container the path exists. In the jellyfin container it does not. If you want the jellyfin container to behave like the plex container you will have to understand enough to add a volume to create that path.

**Comment by srcrist** [comment]
Closing this issue as it does not reference a genuine Jellyfin bug. This is a container configuration issue.
