### ISSUE TITLE
Filtering library with SD Video Type shows 720p content

### ISSUE THREAD

**Issue by Jim-Jellyfin** [jellyfin/jellyfin#10288]
### Please describe your bug

Create a library with 720 movies, and filter them via Video Type SD.
some of the video files will be flagged as SD when their size is 1194x720

Here is one such file's data as reported by JF - this file is flagged as SD and HD, when filtered by video type SD or HD.

About Joan (2022) 720p AAC h264 2ch
Container: mp4
Path: Z:\Movies\h264\About Joan (2022) 720p h264\About Joan (2022) 720p AAC h264 2ch.mp4
Size: 931 MB

Video
Title: 720p H264 SDR
Codec: H264
Codec tag: avc1
AVC: Yes
Profile: High
Level: 41
Resolution: 1194x720
Aspect ratio: 5:3
Interlaced: No
Framerate: 24
Bitrate: 1149 kbps
Bit depth: 8 bit
Video range: SDR
Video range type: SDR
Color space: bt709
Color transfer: bt709
Color primaries: bt709
Pixel format: yuv420p
Ref frames: 1
NAL: 4

Audio
Title: AAC - Stereo - Default
Language: und
Codec: AAC
Codec tag: mp4a
Profile: LC
Layout: stereo
Channels: 2 ch
Bitrate: 128 kbps
Sample rate: 48000 Hz
Default: Yes
Forced: No
External: No

Subtitle
Title: English - SUBRIP - External
Language: eng
Codec: SUBRIP
Default: No
Forced: No
External: Yes

Subtitle
Title: Hindi - SUBRIP - External
Language: hin
Codec: SUBRIP
Default: No
Forced: No
External: Yes

Subtitle
Title: Undefined - SUBRIP - External
Codec: SUBRIP
Default: No
Forced: No
External: Yes

### Jellyfin Version

Other

### if other:

10.8.10

### Environment

```markdown
- OS:Windows
- Linux Kernel:no
- Virtualization:no
- Clients:
- Browser:ALL
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:Nvidia
- GPU Model:1060
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:1GB
- Storage:NAS
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mewajda** [comment]
I was able to look into this a little bit.  It seems as though this particular movie is near the resolution threshold.  Even though its 720, the width is 1194, which is under the 1199 threshold used when filtering by SD.  In order to be in the HD category the minimum width needs to be 1200 or greater.  

Hopefully this helps, thanks

**Comment by Jim-Jellyfin** [comment]
So why is it also shown in HD filter as well then ?Sent from my Galaxy
-------- Original message --------From: Mike Wajda ***@***.***> Date: 30/09/2023  05:13  (GMT+00:00) To: jellyfin/jellyfin ***@***.***> Cc: Jim-Jellyfin ***@***.***>, Author ***@***.***> Subject: Re: [jellyfin/jellyfin] Filtering library with SD Video Type shows 720p content (Issue #10288) 
I was able to look into this a little bit.  It seems as though this particular movie is near the resolution threshold.  Even though its 720, the width is 1194, which is under the 1199 threshold used when filtering by SD.  In order to be in the HD category the minimum width needs to be 1200 or greater.
Hopefully this helps, thanks

**Comment by mewajda** [comment]
That is a good question.  I wasn't able to reproduce that scenario.  I created a movie with the exact resolution as the one you specified and it only shows with the SD filter.  Do you have any other filters selected when you are selecting HD?

**Comment by Jim-Jellyfin** [comment]
All I can say is that others in the Jellyfin discord have the same issue. - I will try with Plex and Emby and see if I can reproduce the same there.  FWIW it might well be something with the files I have, that still does not make it a bug though.

**Comment by Jim-Jellyfin** [comment]
Plex does not produce the issue, however Jellyfin and Emby do.
