### ISSUE TITLE
[Issue]: Regression: Auth with API Key

### ISSUE THREAD

**Issue by endrl** [jellyfin/jellyfin#10284]
### Please describe your bug

The following endpoints return a `403 Forbidden` while using an API key in latest master
* GET `/System/Info`
* GET `​/Library​/VirtualFolders`

Other endpoints like `/Items` or `Videos/${itemId}/master.m3u8` still work

Repro:
* Try to use something like that `http://localhost:8096/System/Info?ApiKey=379cbd42c3af4ff0a9f3f4535a25170fx`
* Returns 403

Thank you

### Jellyfin Version

Other

### if other:

master

### Environment

```markdown
- OS: Ubuntu 22.04
- Linux Kernel: 
- Virtualization: VMware
- Clients: -
- Browser: -
- FFmpeg Version: -
- Playback Method: -
- Hardware Acceleration: -
- GPU Model: -
- Plugins: -
- Reverse Proxy: -
- Base URL: -
- Networking:-
- Storage: -
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nielsvanvelzen** [comment]
This might be a regression from #9747 (CC @Shadowghost).

**Comment by Shadowghost** [comment]
Possible, but it should have worked with the selected policy. I'll take a look when I have time.

**Comment by endrl** [comment]
Thank you for your fast response. I reverted the commit and it works again.
