### ISSUE TITLE
The playback mode is “Remux“ or “DirectStream”, and the subtitles are not packaged.

### ISSUE THREAD

**Issue by shaino** [jellyfin/jellyfin#10298]
Did ffmpeg not consider encapsulating it into subtitles or did I set it incorrectly?

**Comment by cvium** [comment]
There's not enough information. Please describe your issue in detail and provide logs.

**Comment by shaino** [comment]
Sorry, it seems like it's an issue with ffmpeg.

**Comment by cvium** [comment]
It's a possibility, but I doubt it. Ffmpeg does not decide on its own which streams to mux

**Comment by felix920506** [comment]
Please fill out the issue template, thanks.

**Comment by shaino** [comment]
Restrict user transcoding of video or audio in server user settings, and only allow muxing to verify the issue.

**Comment by felix920506** [comment]
This is not enough information. Please open a new issue and complete the issue template in detail, thanks.
