### ISSUE TITLE
[Issue]: Background images for MP3 albums often show "Isaac Albeniz" picture

### ISSUE THREAD

**Issue by IngoBoe** [jellyfin/jellyfin#10326]
### Please describe your bug

Jellyfin is configured to use TheAudioDB and MusicBrainz to load album art for MP3 albums. This works for the album itself, but the background image often shows some black/white image of some ancient artist "Isaac Albeniz". For some albums the right background image is shown, but a lot of albums show this strange picture.

I have rescanned the metadata, but the issue persists.
A screenshot has been attached. Any ideas or which data do you need to have a look into this?

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Windows Server 2022
- Linux Kernel:
- Virtualization: Hyper-V
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Please attach any screenshots here

![Screenshot_20231002_213110](https://github.com/jellyfin/jellyfin/assets/65680486/e4a7271c-eddf-461c-b9b7-7a4376ab9e58)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gerwim** [comment]
I tried to reproduce your issue, both with `10.8.11` and the latest development build but I could not reproduce your issue.

Does this issue also happen when you create a new Music library and put your `Impulse` album in it?

**Comment by IngoBoe** [comment]
No, I created a new library with the same settings with just this album and the background looks okay.
So it seems, the library is somehow broken. Is it possible to fix this or do I have to recreate it?
