### ISSUE TITLE
[Issue]: GitHub stale issue action doesn't seem to be closing old issues

### ISSUE THREAD

**Issue by jacobslusser** [jellyfin/jellyfin#10333]
### Please describe your bug

As of this writing, there are 703 open issues in the Jellyfin project. If you sort by least recently updated (and ignore those with the following tags: regression, security, roadmap, future, feature, enhancement, confirmed) there are a number of open issues that should have been closed by the GitHub stale action, [.github/workflows/repo-stale.yaml](https://github.com/jellyfin/jellyfin/blob/467aa40d215131e15f1ded162e8768a8df90e7d0/.github/workflows/repo-stale.yaml#L12C1-L34C1)

The action logs suggest a fix might be to [increase the number of operations](https://github.com/jellyfin/jellyfin/actions/runs/6387647162/job/17336290340#step:2:8461), however, that would need to be confirmed.

### Jellyfin Version

Other

### if other:

N/A

### Environment

```markdown
N/A
```

### Jellyfin logs

```shell
N/A
```

### FFmpeg logs

```shell
N/A
```

### Please attach any browser or client logs here

N/A

### Please attach any screenshots here

![image](https://github.com/jellyfin/jellyfin/assets/345183/842648e5-566b-4cea-8281-d0d2a3be2d07)

![image](https://github.com/jellyfin/jellyfin/assets/345183/854265d1-c44e-4279-af99-c3423dbf947c)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jacobslusser** [comment]
I can submit a PR to fix this issue if the maintainers agree with the issue and probable cause.

**Comment by sevenrats** [comment]
we just added a handful of members to the triage team, and we are in the process of cleaning this up now.  how do you want this issue to proceed? i suspect all these old issues are going to get handled by human intelligence is the next few days, but if you think your PR is  still a good idea it would be appreciated.

**Comment by jacobslusser** [comment]
I have submitted the PR. It has been approved but not merged yet. Happy to help.

**Comment by jacobslusser** [comment]
I don't believe the PR that was intended to fix this has worked. I still see the "stale issue" action starting from the most recent issue on every run, instead of from where it finished in the last run....

**Comment by srcrist** [comment]
Jacob, did you have any thoughts on how to proceed here?

**Comment by jacobslusser** [comment]
I can only conclude that the stale action doesn't work as advertised and is not persisting state between executions, despite their documentation and my every attempt to get it to do so.

Here is what I think I will do to work around the issue:

1. Increase the `operations-per-run` to maybe 500 -- at least for the time being to work through the backlog and then maybe we can decrease it again. Ideally we don't want that many operations per run because it could cause the GitHub API to block or throttle us.
2. Add the `ascending: true` property. This will have the effect of starting from the oldest and then going to the newest -- which is more appropriate for the goal of the bot to find stale issues.
3. Change the cron schedule back to once a day instead of twice, since that change was based on the assumption it would be stateful and resume where it previously left off.
