### ISSUE TITLE
Add more complicate naming (in PT site) support

### ISSUE THREAD

**Issue by marcosteam** [jellyfin/jellyfin#1033]
**I'm a Chinese user,sorry for my poor English.**
## Problem
In many PT site,any torrents should be named followed by this rules:

> It MUST be English. Do not have space in it (use "." between two word)
> 
> 1. Movie: Name.[CUT].[Year].[Release Info].Source.Resolution.Video Codec.[Audio Codec]-Tag
>    e.g.: Avatar.EXTENDED.2009.BluRay.1080p.x264.DTS-CMCT
> 2. TV Series:  Name.S**E**.[Year].[Release Info].Source.Resolution.Video Codec.[Audio Codec]-Tag
>    e.g.: Prison.Break.S04E01.PROPER.720p.HDTV.x264-CTU
> 3. Audio: Artist.Volume Name.[CUT].[Year].[Release Info].Audio Codec-Tag
>    e.g.:Enya.And.Winter.Came.2008.FLAC
> 4. Music: Artist.Year.Volume Name.Type (Volume, Single one, Pack).Form (MUST have
>    e.g.:Jay.Chou.2008.Capricorn.Album.ape

so download files may has name like this:

> Once.Upon.a.Bite.2018.E01.4K.WEB-DL.AAC.H.265
> Unnatural.2018.E02.4K.WEB-DL.AAC.H265
>Reply1988.2015.E03.WEB-DL.1080p.H264.AAC

But the scrapper don't recognize these names,so it may lose some metadata,Just like this:
![2019-3-2 20-46-47.png](https://i.loli.net/2019/03/02/5c7a7b384532f.png)
these series has many wrong metadata,like "season 20" ,and many files episode are wrong.What worse,it lose the introduction of the episode.But in the TVDB site could be founded.

## Solution
Add these filename scarp support,or open the scrapper's regex setting.

**Comment by JustAMan** [comment]
@cvium do you have any experience with how name parsing is done? I think you touched some of it in your previous PRs...

**Comment by cvium** [comment]
There isn't really any

**Comment by JustAMan** [comment]
Can we fix the parser so it at least recognizes dot as same word separator as is whitespace now?..
