### ISSUE TITLE
[Issue]: After removing second version of movies, the browse screen still shows a version count of (2)

### ISSUE THREAD

**Issue by theshoeshiner** [jellyfin/jellyfin#10335]
### Please describe your bug

When a movie has two versions, the browse view will show a small text bubble indicating the number of versions on each poster. After removing versions, some movies still show a value. Clicking on the movie confirms that there is actually only one version present. Metadata refresh does not fix this.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS:
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cvium** [comment]
Duplicate #9281
