### ISSUE TITLE
[Notice] dotnet7 on arm64 currently requires specific workarounds to prevent segmentation fault

### ISSUE THREAD

**Issue by gnattu** [jellyfin/jellyfin#10342]
As described in dotnet/runtime#93047, there is a codegen bug in dotnet 7 affecting all arm64 platforms, which the project currently depends on. If you want to test the master branch on an arm64-based platform, you should specify `DOTNET_JITMinOpts=1` as an environment variable to disable JIT optimizations and prevent potential segmentation faults, especially if you have a relatively large library. This option would reduce performance, but at least Jellyfin would not crash.

I'm leaving this notice here as the upstream is looking into this issue.

**Comment by gnattu** [comment]
The problem that caused this bug has been identified and fixed in dotnet/runtime#93992. I tested it by downloading the artifacts from the Azure pipelines of that PR and confirmed that Jellyfin no longer crashes after replacing `libcoreclr` and `libclrjit` with the versions in the artifacts. If that PR gets merged, this issue will be fixed in the next release of .NET 7. Furthermore, .NET 8 won't have this issue in case we decide to upgrade in the future.

**Comment by felix920506** [comment]
Hi, it looks like the upstream fix has been merged. Please confirm if the issue has been solved so we can close this issue, thanks.

**Comment by gnattu** [comment]
Yes it has been merged but it is tagged to be released in dotnet 7.0.15, which is not available at the moment.

**Comment by felix920506** [comment]
Thanks for the update. Please let us know if the issue still exists after 7.0.15 is released and close it if it got fixed, thanks.

**Comment by barronpm** [comment]
We're on .NET 8 now, so I'm assuming this is solved
