### ISSUE TITLE
Get season pictures from tmdb

### ISSUE THREAD

**Issue by ryoii** [jellyfin/jellyfin#1034]
**Describe the feature you'd like**
Why can't I download season pics from tmdb.

**Additional context**
I know jellyfin can get metadata from tmdb and tvdb, but the season pics can only download from tvdb and fanart. Usually we expect the metadata and post are consistent. Please, could jellyfin offer a feature to get season pics from tmdb?

**Comment by JustAMan** [comment]
cc @cvium

**Comment by cvium** [comment]
I took a quick peek a few days ago and it shouldn't be difficult. All the data is already there afaict

**Comment by Darkcolth** [comment]
Great, I am looking forward.

**Comment by colem213** [comment]
This feature looks like it has already been implemented.

**Comment by anthonylavado** [comment]
> This feature looks like it has already been implemented.

@colem213 Nope.
![19FA6439-A3E6-4B14-A7D7-6A0D0CA0262E](https://user-images.githubusercontent.com/596194/66804760-53aebb80-eef1-11e9-8e36-1c04b2f3b8c6.jpeg)

**Comment by ryoii** [comment]
lol, I cant find it

**Comment by anthonylavado** [comment]
@ryoii It still hasn’t been implemented yet. There was someone in our chat who said they would try, but I don’t remember where they left off with it.

**Comment by ryoii** [comment]
I am sorry that I am not proficient with C#, otherwise I am very happy to have a try.
