### ISSUE TITLE
[Issue]: external subtitles not loaded while client decoding 

### ISSUE THREAD

**Issue by johndhzd** [jellyfin/jellyfin#10349]
### Please describe your bug

My TV can decode most of the videos on my server, so I turned off the server transcoding, but while direct playing on Jellyfin TV app, the external subtitles are not loaded.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Ubuntu 20.04 lts
- Linux Kernel: 6.2
- Virtualization: proxmox virtual environment 
- Clients: Jellyfin TV android 
- Browser:
- FFmpeg Version:
- Playback Method: direct play, client decoding 
- Hardware Acceleration: GPU passthrough, Intel HD 630
- GPU Model: HD 630
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking: local 
- Storage: HDD
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by johndhzd** [comment]
I saw there is an option on Android phone app, client setting>allow ssa/ass subtitles for direct play, but no such option on Android TV app

**Comment by thornbill** [comment]
At a minimum, we would need more detailed information about the format of the media that is failing to play. However if you are disabling transcoding, it is expected that incompatible media would fail to play.

**Comment by johndhzd** [comment]
it's the subtitle not load, the media can play fine, do you need both media format and the subtitle format?
I think the media is a normal MP4 file with H264 encode, and the subtitle is `ass` format

**Comment by happyTonakai** [comment]
Did you see the 'cc' icon when playing? I can manually load the ass subtitle on Android TV, but the app tells me that the server cannot bake the subtitle. Now I have to convert ass to srt...

**Comment by johndhzd** [comment]
Yes,the button is there,but subtitles not really loaded

**Comment by happyTonakai** [comment]
It seems that in Android TV app, it requires transcoding for ass/ssa subtitles. AFAIK, both ExoPlayer and VLC player support ass/ssa subtitles and I don't know why Jellyfin server has to bake them and transcode...

**Comment by thornbill** [comment]
ExoPlayer lacks full support for ass/ssa. Most subtitles would not render correctly without transcoding... and that is why the app requires transcoding them.

**Comment by happyTonakai** [comment]
> ExoPlayer lacks full support for ass/ssa. Most subtitles would not render correctly without transcoding... and that is why the app requires transcoding them.

Thank you for responding. They're working on it, but it's still not completely resolved. https://github.com/google/ExoPlayer/issues/8435. What about libVLC?
