### ISSUE TITLE
[Issue]: Jellyfin doesn't recognize Artists or Album Artists anymore

### ISSUE THREAD

**Issue by regimeG** [jellyfin/jellyfin#10353]
### Please describe your bug

After updating Jellyfin **10.8.10_1** to **10.8.10_3** on my TrueNAS Core, no Artist or Album Artist is listed. Only Albums are displayed properly. Folder stucture , tags or nfo-files are untouched. How can I force Jellyfin to display the Artists again.
This Link is theming the same issue but was closed without solution: [](https://github.com/jellyfin/jellyfin/issues/9585)

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS:FreeBSD 13.0-U5.3
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Please attach any screenshots here

![grafik](https://github.com/jellyfin/jellyfin/assets/113975337/e2111c56-57d9-452d-89c0-89483b057d8c)
![grafik](https://github.com/jellyfin/jellyfin/assets/113975337/dbb6b21c-7572-4591-bd74-8d528e6f9484)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by srcrist** [comment]
Closing this issue as FreeBSD is unfortunately not a supported platform. It might be the case that this is simply a result of .NET support on this OS. If you can confirm that same issue on a supported platform we can reopen the issue for further investigation.

**Comment by oddstr13** [comment]
FreeNAS is not a platform the Jellyfin team is providing packages for, if something breaks within the same version like you suggest, it is an issue with the packaging, and should be raised as an issue with your package provider.

**Comment by NiceneNerd** [comment]
I'm experiencing precisely the same in Debian running in Termux, not sure if that really counts as a supported platform.

**Comment by HeisenbergK** [comment]
I;m having the same issue on docker jellyfin. I have added an album from a new artist that it didn't match automatically, I self-identified the album, the artist is not there in the album or artist list.

**Comment by regimeG** [comment]
This thread was closed few weeks ago. Guess you have to open an new issue.

**Comment by felix920506** [comment]
@HeisenbergK @NiceneNerd @devsnek Please open a new issue.
