### ISSUE TITLE
Starting Jellyfin as a Windows service may load the wrong data directory

### ISSUE THREAD

**Issue by Andeke** [jellyfin/jellyfin#1036]
In the following key there is a missing `"` for the library directory parameter:

`...\Services\Jellyfin\Parameters\AppParameters = --datadir path/to/library"`

The problem only appears when using spaces in a custom library path, and adding the missing `"` fixes it.

**Comment by JustAMan** [comment]
cc @LogicalPhallacy

**Comment by LogicalPhallacy** [comment]
This is (I think) a relic of the nssm install @Andeke  did you use the windows installer to configure Jellyfin as a service?

**Comment by Andeke** [comment]
Yes, I did. Is this an error with nssm, or is it Jellyfin's usage of nssm that's the problem?

**Comment by LogicalPhallacy** [comment]
This is the line that installs the service: 
`&"$Script:DefaultJellyfinInstallDirectory\nssm.exe" install Jellyfin `"$Script:DefaultJellyfinInstallDirectory\jellyfin.exe`" --datadir `"$Script:JellyfinDataDir`" `

The syntax can be a little weird if you aren't used to powershell, but we are passing in a data directory to NSSM with quotes around it. There are plans to deprecate NSSM soon so we may have to address this with that.
