### ISSUE TITLE
[Issue]: Automatic matching of audio tracks is not appropriate.

### ISSUE THREAD

**Issue by shaino** [jellyfin/jellyfin#10369]
### Please describe your bug

After triggering the audio de mix, it was found that Jellyfin always forcibly changes the pre-selected audio track to the preferred de mix track format.
For example, if the device supports AC3 tracks, choose EAC3/DTS tracks to reduce mixing. If there are AC3 tracks in the movie, playing the track again will be forced to switch to AC3 (perhaps 2 channels).
The track record displayed in the log is correct. The 'jellyfin' server side has undergone automatic switching. Isn't it good to keep users' choices?
Set the conditions so that both the Android client and TV client can reproduce this problem.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS:
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
Please fill out the issue template *properly*.

**Comment by felix920506** [comment]
Closing this as it is not a valid issue report. 

Please head to our [forum or Matrix/Discord channels](https://jellyfin.org/contact) for general questions and troubleshooting.

Alternatively, open a new issue and fill out the issue template properly.
