### ISSUE TITLE
Allow setting MusicBrainz server URL

### ISSUE THREAD

**Issue by LeoVerto** [jellyfin/jellyfin#1037]
Right now the MusicBrainz server used by Jellyfin is hard coded to https://musicbrainz.org/ [here](https://github.com/jellyfin/jellyfin/blob/master/MediaBrowser.Providers/Music/MusicBrainzAlbumProvider.cs#L33).

As with other metadata services where we should allow users to set their own API keys, I believe we should allow them to set the MB URL so those running a replicated server (either via [docker](https://github.com/metabrainz/musicbrainz-docker) or the [VM image](https://musicbrainz.org/doc/MusicBrainz_Server/Setup)) can make use of higher rate limits, lower latency and independence from an internet connection.

Relevant Reddit discussion: https://www.reddit.com/r/jellyfin/comments/aw1bqi/feature_request_use_local_musicbrainz/

**Comment by fruhnow** [comment]
Maybe it would be a good idea to turn this (or in future every) Metadata-Provider into a Plugin (with its own configurationPage.html) while implementing this feature, so that the User can decide which Metadataproviders he wants to install?

Not sure if this is applicable for all Providers (e.g the ones where we got organization-wide API keys for).

**Comment by anthonylavado** [comment]
I forget where I commented this, but an eventual goal idea is to:
- have all metadata providers be plug-ins
- have an extra screen in the setup wizard that recommends plug-ins

The setup would read like:
“Metadata plug-ins provide information about your media. Here are some we recommend:”

It would then have a list of the available providers, links to their privacy policies, and if supported, a spot to put in either a URL/API key as required. This would all be configurable later as well.

**Comment by RazeLighter777** [comment]
Would some be enabled or installed by default?

**Comment by anthonylavado** [comment]
@RazeLighter777 It’s open for debate (and will be in another issue when we start to discuss it further). My original thought was to have some “pre-selected”/opt out, but they could just be highlighted in the list instead. Hence the “Here’s some we recommend:”

**Comment by GoelBiju** [comment]
@anthonylavado I would like to help out but I saw that the URL is set by configuration now in MusicBrainzAlbumProvider.cs file. What can I do to help?

**Comment by dkanada** [comment]
A while ago I migrated the FanArt provider to a plugin, which was the last provider with unique settings in the core server. All providers should eventually be turned into plugins, which will not only let users remove unused providers, but also provide a dedicated location for provider options.

We hadn't actually decided on a method for these core providers yet, but converting them to plugins is actually quite straightforward. Once MusicBrainz gets converted to a plugin you can add as many unique options as you want. I'm not sure what would be useful in this case but things like parsing rules, user access tokens, and image download options would be excellent to include eventually.
