### ISSUE TITLE
[Issue]: redirected to homepage after 5s

### ISSUE THREAD

**Issue by Reaster0** [jellyfin/jellyfin#10372]
### Please describe your bug

a lot of people (4) using my server (but not me i haven't been able to reproduce the issue) using the web version on chrome,firefox and also using the android app have encounter this issue since last week, when they load the service, they can navigate for like 6-7 seconds and then they are redirected to the homepage, even if they manage to launch a video during this time

### Jellyfin Version

Other

### if other:

10.9.0

### Environment

```markdown
- OS: docker image unstable
- Linux Kernel: docker image
- Virtualization: yes
- Clients: web and android
- Browser: chrome,firefox
- FFmpeg Version: packaged in the docker image
- Playback Method:
- Hardware Acceleration: yes nvidia
- GPU Model: gtx 960
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Please attach any browser or client logs here

only log relevant in the console would be this one, it make a request on the ip of the server (in the container) instead of the real hostname of the service? weird?

Mixed Content: The page at 'https://MY_HOSTNAME/web/index.html#/home.html' was loaded over HTTPS, but requested an insecure resource 'http://172.19.0.2:8096/system/info/public'. This request has been blocked; the content must be served over HTTPS.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cvium** [comment]
Looks like a misconfiguration of your network settings

**Comment by Reaster0** [comment]
what type of misconfiguration could it be? i have a dns name that point to a gateway that has a port forward to a reverse proxy nginx, that handle the ssl/https support and forward to my jellyfin into a docker container (unstable image), what could cause the website to return to the homepage?

**Comment by Reaster0** [comment]
after running some tests and having more people telling me they have the issue, yeah it seems that often (but not the majority of requests) the website ask the client to make some requests to the local address of the service inside the docker (172.19.0.x),

*it's worth noting that my service run since 3month and i haven't changed any settings or conf since and we never had any issues like that before, i'm also running the latest unstable docker image*

**Comment by nipsy** [comment]
Out of curiosity, does this happen to those users if they have the admin option checked (the "Allow this user to manage the server" option)?  I ask because I'm seeing a somewhat similar breakage occurring just within the last couple of days where the logs indicate a successful authentication for my non-admin remote users, but then it simply loads the sign-in page again (after very briefly flashing the logged in home screen with my proper categories listed!).

And I do see a difference in the logs between those two scenarios.  For the admin user, I see:

```
Oct 08 16:06:34 ds.blaspheme.net jellyfin[3652109]: [16:06:34] [INF] Authentication request for admin has succeeded.
Oct 08 16:06:34 ds.blaspheme.net jellyfin[3652109]: [16:06:34] [INF] Current/Max sessions for user admin: 1/0
Oct 08 16:06:34 ds.blaspheme.net jellyfin[3652109]: [16:06:34] [INF] Logging out access token 32c21d9f2f2c48549361dabdcd0ba744
Oct 08 16:06:34 ds.blaspheme.net jellyfin[3652109]: [16:06:34] [INF] Creating new access token for user e3a81de3-f185-4eed-b279-dfadfe5a724c
```

whereas for the non-admin user, I see:

```
Oct 08 16:06:18 ds.blaspheme.net jellyfin[3652109]: [16:06:18] [INF] Authentication request for non-admin has succeeded.
Oct 08 16:06:18 ds.blaspheme.net jellyfin[3652109]: [16:06:18] [INF] Current/Max sessions for user non-admin: 1/0
Oct 08 16:06:18 ds.blaspheme.net jellyfin[3652109]: [16:06:18] [INF] Logging out access token b7ba352e689f4506bcfd0cca15395563
Oct 08 16:06:18 ds.blaspheme.net jellyfin[3652109]: [16:06:18] [INF] Creating new access token for user 96c79c5d-3006-4741-9a52-614fd93a17fd
Oct 08 16:06:19 ds.blaspheme.net jellyfin[3652109]: [16:06:19] [WRN] 98.97.115.16: External request received, no matching external bind address found, trying internal addresses.
Oct 08 16:06:19 ds.blaspheme.net jellyfin[3652109]: [16:06:19] [WRN] 98.97.115.16: External request received, but no external interface found. Need to route through internal network.
Oct 08 16:06:19 ds.blaspheme.net jellyfin[3652109]: [16:06:19] [WRN] 98.97.115.16: External request received, no matching external bind address found, trying internal addresses.
Oct 08 16:06:19 ds.blaspheme.net jellyfin[3652109]: [16:06:19] [WRN] 98.97.115.16: External request received, but no external interface found. Need to route through internal network.
```

I should also mention that I'm using nginx as the front-end here and a subpath configuration.

Anyway, this could be an entirely different problem that has only recently popped up, but it sounded similar enough I figured I'd start here.

**Comment by cvium** [comment]
Likely fixed by https://github.com/jellyfin/jellyfin-web/pull/4861

**Comment by nipsy** [comment]
Can confirm this fixed my problem at least.  Thanks!

**Comment by Reaster0** [comment]
it as also fixed my problem, thanks!
