### ISSUE TITLE
protentional vulnerability form curl

### ISSUE THREAD

**Issue by 332plim** [jellyfin/jellyfin#10383]
Describe the bug
Concern about recent curl vulnerability as mentioned https://github.com/curl/curl/discussions/12026
Will the vulnerability impact jellyfin

**Comment by satmandu** [comment]
The node images used in the default docker setups do use the vulnerable version of curl: https://hub.docker.com/_/node/tags but AFAIK that is only used during the building of the images...

The next update to the node images should hopefully take care of that. The node:20-alpine image hasn't been updated in several months, so hopefully that will get updated too soon.
