### ISSUE TITLE
[Enhancement] added desktop-file

### ISSUE THREAD

**Issue by varlesh** [jellyfin/jellyfin#1038]
Will be good added desktop-file for run Jellyfin. This quick access for open server and comfortable ;)
For example:
```
[Desktop Entry]
Categories=Audio;Music;Video;Player;Media;
Comment=Manage your Jellyfin Media
Exec=x-www-browser http://localhost:8096
GenericName=Jellyfin
Icon=jellyfin
Name=Jellyfin
StartupNotify=true
Terminal=false
Type=Application
```

**Comment by varlesh** [comment]
how this work:
https://youtu.be/IKKflXYgac0

**Comment by onny** [comment]
Hm this is quite unusual. Normally you don't have desktop shortcuts to web service pages. This would make more sense in the future for a jellyfin-desktop player/app.

**Comment by varlesh** [comment]
@onny Why not? Plex already have desktop file too...

**Comment by JustAMan** [comment]
Idea itself is good, but cannot be implemented as simple as this, as URL to access the Jellyfin server is configurable. So there's need to have a middle program that would read Jellyfin config, compose the URL and then launch a web browser.

**Comment by RazeLighter777** [comment]
I thought we weren't going to launch the web page upon start-up anymore?

**Comment by JustAMan** [comment]
This is not about launching a page on startup, it's more like browser bookmark for jellyfin instance being put to the desktop.

**Comment by varlesh** [comment]
@JustAMan Yes, you right... Also `localhost:8096` it's default URL. if user change port, need fix that on desktop file. I think it's not problem with sed ))

**Comment by JustAMan** [comment]
If a user is experienced enough to work with `sed` they should have no problem creating a bookmark in their browser or a shortcut to said bookmark themselves :)

**Comment by EraYaN** [comment]
This should probably be in the form of `jellyfin --launch-browser` so we don't have to do any external parsing of stuff.
