### ISSUE TITLE
[Issue]: Media Filtering multiple Versions does only filter the primary Version

### ISSUE THREAD

**Issue by alwe2710** [jellyfin/jellyfin#10399]
### Please describe your bug

Hello,

I do have movies with multiple versions (3D & 4K, 480p & 1080p, etc.). I already named them like the documentation explains it. They also get displayed right when I look in the web interface. 
But whenever I try to filter, the filter only applies to the version i added first. The second version does not get displayed. 
So for example I add the 3D version of a movie, after that I add the 4K version. I filter for 4K, I don't see the movie. I filter for 3D, I see the movie.

I can provide more information if you need it

### Jellyfin Version

Other

### if other:

10.8.11

### Environment

```markdown
- OS: Ubuntu 22.04.3 LTS
- Linux Kernel: Linux 6.2.16-10-pve
- Virtualization: Prxomox LXC
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model: 
- Plugins:
- Reverse Proxy: Caddy
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheMelmacian** [comment]
This is a known bug: https://github.com/jellyfin/jellyfin/issues/6609

**Comment by felix920506** [comment]
Closing as duplicate
