### ISSUE TITLE
Unable to play BDMV with Infuse

### ISSUE THREAD

**Issue by Eisaichen** [jellyfin/jellyfin#10398]
![IMG_0873](https://github.com/jellyfin/jellyfin/assets/12467320/4cb7c319-b176-41d7-a2e0-dbe167f0c176)
Play BDMV folder with Infuse will report "File not found"
I found a closed issue here https://github.com/jellyfin/jellyfin/issues/10047
It seems like this issue has already been fixed, but it is somehow still present here with the latest version.
Ps. Play the same file with webui have no problem

**Media Info of the file**
<img width="835" alt="image" src="https://github.com/jellyfin/jellyfin/assets/12467320/63852bb5-def7-43f0-b835-fc5fc777524d">

**Logs**
```
[05:50:14] [ERR] [98] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request: Could not find file 
'/media/Videos/Movies/Top.Gun.Maverick.2022.IMAX.2160p.BluRay.HEVC.TrueHD.7.1.Atmos-ESiR'. URL GET 
/Videos/236750af9e695acac9f57e45e171f084/stream.   
```
the path shown above is valid
```
# ls -l /media/Videos/Movies/Top.Gun.Maverick.2022.IMAX.2160p.BluRay.HEVC.TrueHD.7.1.Atmos-ESiR
total 4
drwxr-xr-x 2 1000 1000  0 Oct 13 05:50 BDMV
drwxr-xr-x 2 1000 1000  0 Feb 13  2023 CERTIFICATE
drwxr-xr-x 2 1000 1000  0 Feb 13  2023 MAKEMKV
-rwxr-xr-x 1 1000 1000 31 Feb 13  2023 RARBG.txt
# ls -l /media/Videos/Movies/Top.Gun.Maverick.2022.IMAX.2160p.BluRay.HEVC.TrueHD.7.1.Atmos-ESiR/BDMV
total 116
drwxr-xr-x 2 1000 1000      0 Feb 12  2023 BACKUP
drwxr-xr-x 2 1000 1000      0 Feb 12  2023 BDJO
drwxr-xr-x 2 1000 1000      0 Feb 12  2023 CLIPINF
-rwxr-xr-x 1 1000 1000   1224 Feb 13  2023 index.bdmv
drwxr-xr-x 2 1000 1000      0 Feb 12  2023 JAR
drwxr-xr-x 2 1000 1000      0 Feb 12  2023 META
-rwxr-xr-x 1 1000 1000 114170 Feb 12  2023 MovieObject.bdmv
drwxr-xr-x 2 1000 1000      0 Feb 12  2023 PLAYLIST
drwxr-xr-x 2 1000 1000      0 Feb 13  2023 STREAM
```

**Server System (please complete the following information):**
 - OS: Ubuntu Docker 24.0.6 jellyfin/jellyfin:latest
 - Jellyfin Version: 10.8.11
 - Hardware settings & device: AMD Ryzen 9 5900X
 - Reverse proxy: Caddy
 - Other hardware notes: Media mounted in CIFS/SMB share on the host, as a local drive in container
 
**Client System (please complete the following information):**
 - Device: iPad Pro
 - OS: iOS
 **- Client: Infuse**
 - Client and Browser Version: Infuse 7.6.1

**Comment by Shadowghost** [comment]
Already fixed by #9254 in master. Will be part of 10.9
