### ISSUE TITLE
Replace NSSM with native Windows Service control

### ISSUE THREAD

**Issue by LogicalPhallacy** [jellyfin/jellyfin#1039]
**Is your feature request related to a problem? Please describe.**
Despite the name NSSM sucks. It is a finicky hack to wrap a console app into a service and shouldn't really be used as the main mechanism to power a media server.

**Describe the solution you'd like**
Jellyfin should support installing itself as a windows service natively, which would then enable it to both be controlled by the standard windows service control mechanisms and hopefully control itself better on windows (self restarts spring to mind)

**Describe alternatives you've considered**
We can keep using NSSM or make a Windows DotNet 4.7 app that loads a process for jellyfin to live in. Both of these are maintainability headaches.

**Comment by LogicalPhallacy** [comment]
While I had hoped to do this hand in hand with  #431 there's a compelling argument to go earlier. After seeing some [problems with NSSM on reddit](https://www.reddit.com/r/jellyfin/comments/awxwxn/jellyfin_service_refuses_to_start/) and [this option](https://github.com/PeterKottas/DotNetCore.WindowsService) it might be worth doing now.

**Comment by anthonylavado** [comment]
@logicalphallacy - I can look at this too. Let me know if you’ve started anything or not.

**Comment by sevenrats** [comment]
moved to 
https://features.jellyfin.org/posts/2352/replace-nssm-with-native-windows-service-control
