### ISSUE TITLE
Chromecast stream freezing with a failing IPTV

### ISSUE THREAD

**Issue by DarkJoney** [jellyfin/jellyfin#1040]
**Describe the bug**
Hello. I was still trying to get a IPTV working, and I found out a strange behaviour of failing IPTV playing attempt.
I reproduced the issue two times, via a webUI and Android app.
So, what's happens:
- I select my chromcast for a streaming
- I launch any channel from mine different ITPV lists
- At TV's screen I get a label of TV channel with a black screen and no sound (I am not able to watch IPTV at all)
- At this while, Jellyfin thinks that it plays an IPTV stream
- When I am stopping the stream or trying to play something another, webUI disconnects from Chromecast, Android app crashes to launcher
- When I try to stream to chromecast once more, from webUI it's impossible to stream to it (just a loading indicator or chromecast selection don't connect), and at Android APP just don't show up chromcast at the list.
- At this moment, in the settings, Jelly says that he is playing directly to Chromecast my IPTV stream even if it disconected and moreover when Chromcast TV is switched off.
- ffmpeg keeps loading the CPU at background
- I can interrupt the IPTV stream, for example, by YouTube app, but Jelly will still show that he is playing IPTV and will keep the ffmpeg alive.

Only relaunch of the server brings back a working streaming.

**To Reproduce**

1. Grab any working IPTV playlist
2. Try to cast IPTV stream to TV, get a black screen
3. Try to change the playing content on TV or pause the stream
4. Catch the disconnection
5. See error

**Expected behavior**
Working IPTV, correct stream shutdown and correct change of  the playing content.

**System (please complete the following information):**
 - OS:  Windows Server 2012
 - Browser: Chrome 72
 - Jellyfin Version: 10.2.2

**Additional context**

**Comment by otakon84** [comment]
sorry for bother, any news from this?  I would love to install jellyfin but i cant use it with chromecast.
Thanks a lot for your efforts!

**Comment by DarkJoney** [comment]
> sorry for bother, any news from this? I would love to install jellyfin but i cant use it with chromecast.
> Thanks a lot for your efforts!

Nope, no way, IPTV still doesn't work. Looks like that nobody works on it. Have to watch F1 at small computer screen.

**Comment by anthonylavado** [comment]
Okay, we'll need some more information.

How is the IPTV stream added to Jellyfin? Is it using a plugin, or the built in Live TV function? Is it an M3U tuner?

What media format does the stream come in? MP4 with AAC audio? Is it possible to get any logs from when you reproduce the error?

**Comment by otakon84** [comment]
Thanks a lot @anthonylavado for the reply!

I am using the latest version of jellyfin for Windows 64 bit and Windows 10. I used an M3U list by my IPTV provider, as well as one created by me with free channels - all without success

They reproduce perfectly well on my pc, but when issuing to chromcast the error described at the beginning of the post occurs.

I don't know the format of the iptv signals, but I attach the pastebin of the free m3u list and the logs.

Thank you

[](https://pastebin.com/bszZYeEs)

[https://pastebin.com/utYUfzFY](url)

**Comment by DarkJoney** [comment]
> Okay, we'll need some more information.
> 
> How is the IPTV stream added to Jellyfin? Is it using a plugin, or the built in Live TV function? Is it an M3U tuner?
> 
> What media format does the stream come in? MP4 with AAC audio? Is it possible to get any logs from when you reproduce the error?

Hi, Anthony. I use M3U tuners for m3u playlists. Video should be mpeg4/mpeg2 inside, but I have a Quadro P600 running inside for the transcoding. I don't think that they stream anything special. Casting doesnt work with any playlist, so,I don't really think that problem in it. Hardware acceleration settings also doesn't change anything. Directly via web at Chrome it actually works, but I don't need IPTV at my PC, because dedicated VLC based IP-TV Player works more stabily.

But, when I am going to stream it to Chromecast, Jellyfin web stucks for a minute, starts streaming (TV with a chromecast keeps black), and in the web it shows no time and that it's playing. At settings it says that it directly playing those stream to the chromecast. After I want to disable the stream, entire cast to chromecast breaks, it is just freesing, and only reboot of the Jellyfin helps. 

I don't know what is wrong with it. Where can I grab the logs for you? 
Currently, I am running those playlists:
http://iptvm3u.ru/spb.m3u
https://webarmen.com/my/iptv/auto.nogrp.m3u

**Comment by otakon84** [comment]
![Captura](https://user-images.githubusercontent.com/52890667/63233792-8d708800-c208-11e9-8cb9-1d62614c541d.JPG)
Another screenshot if helps

**Comment by otakon84** [comment]
Good News!
I just try last nightly and seems works with one channel XD 
![works](https://user-images.githubusercontent.com/52890667/64078697-2ea11900-ccb4-11e9-8391-d6579d19a8d3.JPG) [](https://pastebin.com/6bveAB0b)

**Comment by otakon84** [comment]
https://pastebin.com/6bveAB0b

**Comment by anthonylavado** [comment]
I will test as well, we recently merged some things that should help.

**Comment by DarkJoney** [comment]
Well, IPTV is not working via Android TV at Fire TV 4K. Will check it out at the next update.
Finally, I have bought the Samsung Tizen TV which can maintain IPTV by himself.

**Comment by anthonylavado** [comment]
@DarkJoney There are some Android TV/Fire TV fixes still on the way.

**Comment by DarkJoney** [comment]
> @DarkJoney There are some Android TV/Fire TV fixes still on the way.
Well, but in general app works fine, H265 4K actually works for me.

**Comment by anthonylavado** [comment]
Yeah, the Android TV/Fire TV app creates a playback request with format support, and uses player libs. Each client is different at the moment.

**Comment by otakon84** [comment]
Well for me still unsolved. waiting for next version

**Comment by JustAMan** [comment]
Probably could benefit from https://github.com/jellyfin/jellyfin/pull/2160 being merged
