### ISSUE TITLE
Add forced remuxing

### ISSUE THREAD

**Issue by Guru1-228** [jellyfin/jellyfin#10401]
Direct playback doesn't work for me, but remixing works perfectly, I don't need re-encoding, but it plays some files directly
Please add the ability to choose to force playback through either remixing or transcoding, this would solve a huge number of problems not only for me, but also for many other users whose TV capabilities were incorrectly determined
*I don’t want automation to always decide for me how to play files

**Comment by felix920506** [comment]
Please fill out the issue template.

**Comment by felix920506** [comment]
Closing this as it is not a valid issue report. If you are still experiencing issues, please open a new issue and fill out the issue template properly.
