### ISSUE TITLE
[Issue]: Regression(?): Recent Update Breaks Home Screen Json on Swiftfin/Infuse

### ISSUE THREAD

**Issue by jet082** [jellyfin/jellyfin#10405]
### Please describe your bug

I am running the latest unstable and, for the last week or two, I have been unable to view the home screen on swiftfin and infuse. I can do so fine on web.

Moreover, I can still search for videos and play them on swiftfin/infuse, but I cannot see the home screen or the categories I created.

The most relevant logs are probably here (https://github.com/jellyfin/Swiftfin/issues/876#issuecomment-1763160481), wherein it seems to report issues with a json change.

I tried to do some digging into the source and commit history here to figure out where things changed, but I cannot seem to find it.

I know unstable is, well, unstable, but at the same time since I do not know if this is a 'regression' or an evolution that happens to break swiftfin/infuse, I felt it prudent to report. Worst-case, if it is possible to identify exactly what happened, swiftfin/infuse can more easily fix the issue and support any upcoming changes.

### Jellyfin Version

Other

### if other:

10.9.0

### Environment

```markdown
- OS: Ubuntu
- Linux Kernel: 5.4.203
- Virtualization: docker
- Clients: Swiftfin, Infuse
- Browser: Safari
- FFmpeg Version: 4.2.7
- Playback Method: Direct Play
- Hardware Acceleration: none
- GPU Model: none
- Plugins: InfuseSync
- Reverse Proxy: nginx
- Base URL: /jellyfin
- Networking: host
- Storage: local
```

### Jellyfin logs

```shell
The logs, strangely, do not report any issues.
```

### Please attach any screenshots here

![](https://user-images.githubusercontent.com/46708077/274588763-fffe7d2d-9ac9-4e88-9426-1f736e0c660a.jpeg)

![](https://user-images.githubusercontent.com/46708077/274588793-8b855ddd-f3df-4514-a045-b30cb568fec6.jpeg)

![](https://user-images.githubusercontent.com/46708077/274588812-112c0a06-80f1-4d8a-8ac3-fb926aba5805.jpeg)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
Does the same happen with the same clients on the current Jellyfin release?

**Comment by CoffeeKnyte** [comment]
Just to add that I have seen the same issue in testing. 10.9 nightly works with other clients and also the ios jellyfin app. However, it doesn't work with the swiftfin app which gives a "200 - unknown error" message on the swiftfin homescreen.

@jet082 do you have a date for the last known working nightly (that worked for you)? That can help narrow down which commits should be looked at.

**Comment by perler** [comment]
I think this started even with 10.8.11 stable. I get these errors when indexing on a stable 10.8.11 with infuse plugin 1.4.2.0:

```
[2023-10-29 10:44:56.243 +01:00] [INF] [136] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication"
was forbidden.
```
[this](https://community.firecore.com/t/indexing-error-with-jellyfin-10-8-8/39834/20) is what infuse wrote about this issue at the time.

**Comment by CoffeeKnyte** [comment]
At the moment it does not break for me on 10.8.11 stable. 

I run the same library with 10.8.11 stable and with the 10.9 nightly (i use docker containers). Swiftfin and infuse work ok for me on 10.8.11 but breaks on 10.9 (with the exact behavior that jet082 describes).

**Comment by perler** [comment]
Not sure what changed, but Infuse 7.6.4 in combination with jellyfin 10.8.13 fixed this problem for me. I can definitely say, that it didn't work with 10.8.12 and 7.6.4 as by chance I tried it yesterday. Todays 10.8.13 release, although supposedly only a security fix, fixed everything. :)
