### ISSUE TITLE
[Issue]: After refreshing TV Guide, wrong cover/background/description are shown

### ISSUE THREAD

**Issue by Moonbase59** [jellyfin/jellyfin#10402]
### Please describe your bug

After making a change in my TV program and manually refreshing the Jellyfin TV Guide, the correct title, year, genres are shown but the **cover image, description and background image are not updated** from what was there before, leading to a mix containing wrong information:

![Screenshot 2023-10-14 at 07-31-43 Jellyfin](https://github.com/jellyfin/jellyfin/assets/3706922/57fd76ac-2360-4e25-b111-0ed11eddc7f0)

**This is not a single case, but happens everytime I change my _ErsatzTV_ program, and programs at the same time are replaced with something different.** It is independent of the client used: I tried the Web UI, _Jellyfin Media Player_ on Linux and Windows, and the _AndroidTV_ version on my Amazon FireTV 4K.

In this case I changed the randomized playout in my _ErsatzTV_, and on 2023-10-14 at 20:15 is now the movie "Time Bandits" instead of "Star Trek", which was in this place before.

![Screenshot 2023-10-14 at 07-28-49 ErsatzTV](https://github.com/jellyfin/jellyfin/assets/3706922/5da56884-2adf-4229-be00-313bf053ad8d)

**(All items before and after "Time Bandits" are also shown with the wrong description and covers in Jellyfin.)**

My _xTeVe_ generates a perfectly valid XMLTV file:

```xml
      <programme channel="1000" start="20231014201500 +0200" stop="20231014221047 +0200">
          <title lang="en">Time Bandits</title>
          <desc lang="en">Als ihm eines Nachts sechs Zwerge aus seinem Kleiderschrank entgegenpurzeln, kann der kleine Kevin seinen Augen nicht trauen. Die Zwerge erzählen ihm, dass sie dem Obersten Wesen eine Karte mit Zeitlöchern gestohlen haben, um erfolgreiche Banditen zu werden. Der Junge lässt sich nicht lange bitten und schließt sich den Zwergen an. Gemeinsam treffen sie in Frankreich auf Napoleon, stellen aber schnell fest, dass er ein großer Lausbub ist. In König Agamemnon findet Kevin seine langersehnte Vaterfigur, während sich sein Held Robin Hood als Unterdrücker der Bauern entpuppt. Doch durch unglückliche Umstände kann das personifizierte Böse die Karte an sich nehmen.</desc>
          <category lang="en">Movie</category>
          <category lang="en">Abenteuer</category>
          <category lang="en">Familie</category>
          <category lang="en">Fantasy</category>
          <category lang="en">Komödie</category>
          <category lang="en">Science Fiction</category>
          <icon height="" src="http://media:8409/iptv/artwork/posters/jellyfin/Items/8979f240d0650a2c51d423942a0cc264/Images/Primary?tag=d97d3da9da33bee1e3a01da1f0812209&amp;fillHeight=440" width=""></icon>
          <credits></credits>
          <rating system="">
              <value>FSK-6</value>
          </rating>
          <video></video>
          <date>1981</date>
          <previously-shown start=""></previously-shown>
      </programme>
```

In case you wonder, the `<icon src="…">` leads to the correct cover image for "Time Bandits"—I verified by opening in a browser.

If it helps for debugging, here is the actual current `xteve.xml.gz` I use as an input for Jellyfin:
[xteve.xml.gz](https://github.com/jellyfin/jellyfin/files/12903109/xteve.xml.gz)

The relevant part of **jellyfin20231014.log** (where I updated the EPG):
[jellyfin20231014.log](https://github.com/jellyfin/jellyfin/files/12902760/jellyfin20231014.log)

### Jellyfin Version

10.8.z

### if other:

10.8.11

### Environment

```markdown
- OS: Ubuntu 22.04.3 LTS
- Linux Kernel: 5.15.116-1-pve
- Virtualization: Proxmox LXC
- Clients: Web UI, Jellyfin Media Player (Linux & Windows), AndroidTV
- Browser: Firefox 118.0.2
- FFmpeg Version: 5.1.3-Jellyfin
- Playback Method:
- Hardware Acceleration: VAAPI
- GPU Model: Intel i965 driver for Intel(R) Haswell Desktop - 2.4.1
- Plugins: AudioDB, Bookshelf, MusicBrainz, OMDb, Reports, Studio Images, TMDb, TMDb Box Sets, TheTVDB
- Reverse Proxy: External Nginx Proxy Manager
- Base URL:
- Networking:
- Storage: TrueNAS Core (NFS mounts)
```

### Jellyfin logs

```shell
(see above, was too long for a comment)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moonbase59** [comment]
I thought #6103 might be related, but doing a

```bash
sudo rm /var/cache/jellyfin/*_channels
sudo rm /var/cache/jellyfin/xmltv/*
```

on the server, followed by a manual TV Guide refresh didn’t help. It rebuilt the `…_channels` and `xmltv/….xml` files but images and description are still wrong.

**Comment by Moonbase59** [comment]
@felix920506 I thought I was rather exhaustive in getting all the data together to report this issue.

You triaged it into "Insufficient Data", so what else would you need?

**Comment by avionics75** [comment]
Same here #9884

:(

**Comment by lovelydumpling** [comment]
I can also report facing this same problem and I do also wonder what other data they need.
