### ISSUE TITLE
When playing, quality selection issues.

### ISSUE THREAD

**Issue by 1983shake** [jellyfin/jellyfin#1041]
CN:
1.由于硬件性能不行，导致转码很慢，等待播放时间很长，并且断断续续。
2.希望在播放质量里有不转码播放（或原始播放）。
3.就像播放器直接读取文件，在本地解码播放。
EN:
1.Because hardware performance is not good, the transcoding is slow, waiting for playback time is long, and intermittent.
2.You want to have no transcoding playback (or original playback) in playback quality. 
3.Just like the player reads the file directly and decodes the playback locally.

**Comment by marcosteam** [comment]
+1
群晖因为没有spk，所以不能发挥硬解性能

**Comment by 1983shake** [comment]
> +1
> 群晖因为没有spk，所以不能发挥硬解性能

确实，我的是黑群晖，用的是Intel Atom N455的工控板，虽然省电，但是性能不行，所以转码播放简直就是灾难。

**Comment by 5dprince** [comment]
所以需要kodi + 插件....

**Comment by EraYaN** [comment]
Playing without transcoding is supported depending on the client. What client are you trying to play the media on and what is the source media's codec and type?

**Comment by 1983shake** [comment]
> Playing without transcoding is supported depending on the client. What client are you trying to play the media on and what is the source media's codec and type?

An (CPU:Intel Atom N455) industrial control board, can transcode, is the hardware performance is not good, resulting in very slow transcoding, so the play will be intermittent.

[视频信息]
  视频编码： HVC1 - 内置 FFmpeg 解码器(hevc, Thread Frame)
  输入格式： HVC1(24 bits)
  输入尺寸： 1920 × 1080(1.78:1)
  输出格式： YV12(12 bits)
  输出尺寸： 1920 × 1080(1.78:1)
  帧率： 23.976
  BitRate: 未知

[音频信息]
  音频编码： AAC(0xaac0) - 内置 FFmpeg 解码器(aac)
  采样率： 44100 -> 44100 Hz
  位率： 0 -> 16 位
  声道数： 2 -> 2 声道
  Bitrate: 0 kbps

**Comment by 1983shake** [comment]
> 所以需要kodi + 插件....

想只用浏览器或安卓手机播放，但浏览器和安卓端播放质量只能选转码的。。。所以希望能有个不需要转码质量。

**Comment by EraYaN** [comment]
I rather from your second comment, that the client you watch on is Android and Browsers. Depending on the browser or the Android phone HEVC streaming should just work. But the app might not detect that properly.

For browsers really only these are supported: https://caniuse.com/#search=HEVC Although the web interface might not detect that either.

The Intel Atom N455 you mention would be your server, and it doesn't seem to have any hardware acceleration for video. So I would recommend disabling transcoding in the server settings altogether.

**Comment by 1983shake** [comment]
> I rather from your second comment, that the client you watch on is Android and Browsers. Depending on the browser or the Android phone HEVC streaming should just work. But the app might not detect that properly.
> 
> For browsers really only these are supported: https://caniuse.com/#search=HEVC Although the web interface might not detect that either.
> 
> The Intel Atom N455 you mention would be your server, and it doesn't seem to have any hardware acceleration for video. So I would recommend disabling transcoding in the server settings altogether.

It's OK not to transcode, but how can it be closed? I can't find a switch that can turn off the transcoding.

**Comment by marcosteam** [comment]
> I rather from your second comment, that the client you watch on is Android and Browsers. Depending on the browser or the Android phone HEVC streaming should just work. But the app might not detect that properly.
> 
> For browsers really only these are supported: https://caniuse.com/#search=HEVC Although the web interface might not detect that either.
> 
> The Intel Atom N455 you mention would be your server, and it doesn't seem to have any hardware acceleration for video. So I would recommend disabling transcoding in the server settings altogether.

I know Plex could directplay without transcode,I think it has a player in it.So why not include a encoder?

**Comment by JustAMan** [comment]
Jellyfin only transcodes if it thinks that your client cannot handle "direct play".
So forcing it to "not transcode" would end up with you seeing no video :)

So instead of this forcing option please go case-by-case where you think you should be having direct play but aren't having it, and submit issues for that.

Note that most common denominator now is `MP4` container with `x264/avc` for video and `aac/mp3` for audio.

**Comment by GSSYVGEG** [comment]
> CN:
> 1.由于硬件性能不行，导致转码很慢，等待播放时间很长，并且断断续续。
> 2.希望在播放质量里有不转码播放（或原始播放）。
> 3.就像播放器直接读取文件，在本地解码播放。
> EN:
> 1.Because hardware performance is not good, the transcoding is slow, waiting for playback time is long, and intermittent.
> 2.You want to have no transcoding playback (or original playback) in playback quality.
> 3.Just like the player reads the file directly and decodes the playback locally.

网页登陆jellyfin的管理页面，点击左侧的dashboard仪表盘，然后点击“用户”，右侧出来用户后，点击用户方块 ，出现设置选项，将以下的三个选项的对勾去掉，就彻底关闭转码了。

Alow audio playback that requires transcoding

Allow video playback that requires transcoding

Allow media downloading and syncing that requires transcoding

应该关闭第二项就行了，具体没测试。
ps：关闭转码后，外网播放，家庭那点上传带宽有点不够看，还是开着吧。
pps：jellyfin会改变个别视频的原始画面比例，16：9变成4：3，不知道如何解决

**Comment by 1983shake** [comment]
> > CN:
> > 1.由于硬件性能不行，导致转码很慢，等待播放时间很长，并且断断续续。
> > 2.希望在播放质量里有不转码播放（或原始播放）。
> > 3.就像播放器直接读取文件，在本地解码播放。
> > EN:
> > 1.Because hardware performance is not good, the transcoding is slow, waiting for playback time is long, and intermittent.
> > 2.You want to have no transcoding playback (or original playback) in playback quality.
> > 3.Just like the player reads the file directly and decodes the playback locally.
> 
> 网页登陆jellyfin的管理页面，点击左侧的dashboard仪表盘，然后点击“用户”，右侧出来用户后，点击用户方块 ，出现设置选项，将以下的三个选项的对勾去掉，就彻底关闭转码了。
> 
> Alow audio playback that requires transcoding
> 
> Allow video playback that requires transcoding
> 
> Allow media downloading and syncing that requires transcoding
> 
> 应该关闭第二项就行了，具体没测试。
> ps：关闭转码后，外网播放，家庭那点上传带宽有点不够看，还是开着吧。
> pps：jellyfin会改变个别视频的原始画面比例，16：9变成4：3，不知道如何解决

非常感谢，我试试。
现在家庭带宽都很高了，我家的上传已经达到300Mbps了。
改变比例案例，好像还没有遇到过。

**Comment by ntgeralt** [comment]
同问：ios上播放时，音频解码似乎一定要开。关了直接看视频都没声音。然而一定开解码的话，vps的cpu基本满载了。已经是iphone 11+千兆宽带，服务端解码这个真的应该作为可选项。

**Comment by GSSYVGEG** [comment]
> 同问：ios上播放时，音频解码似乎一定要开。关了直接看视频都没声音。然而一定开解码的话，vps的cpu基本满载了。已经是iphone 11+千兆宽带，服务端解码这个真的应该作为可选项。

其实上面的JustAMan老哥解释比较清楚。用来观看的客户端设备不一定能够支持所有的视频编码的播放，jellyfin之所以没有提供这个开关，是因为当客户端不支持某种编码时，视频会直接无法播放。jellyfin的思路是合理的

**Comment by ntgeralt** [comment]
逻辑可以改进为，客户端能硬解就硬解，不能硬解自动转软解
