### ISSUE TITLE
[Issue]: Jellyfin does not allow special characters such as '+' in user names

### ISSUE THREAD

**Issue by mmedic** [jellyfin/jellyfin#10414]
### Please describe your bug

When creating a new user via API or Web interface, if a user's name has a special character such as commonly used '+' in email addresses, 400 error is returned.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS:
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oddstr13** [comment]
I wasn't aware that we had username filtering, but this is it

https://github.com/jellyfin/jellyfin/blob/ed42fcf522084d4e98d1e0c56ac448c312805c25/Jellyfin.Server.Implementations/Users/UserManager.cs#L103-L107

**Comment by oddstr13** [comment]
Related tests can be found here, and need updating to test for `user+tag@example.org`.
Tests for unicode names would also be nice (accented characters, different scripts).

https://github.com/jellyfin/jellyfin/blob/ed42fcf522084d4e98d1e0c56ac448c312805c25/tests/Jellyfin.Server.Implementations.Tests/Users/UserManagerTests.cs#L9-L26

**Comment by Erizon0** [comment]
is this still being worked on? because there is no change in the pull request
