### ISSUE TITLE
[Issue]: Jellyfin.Server.Fuzz does not compile

### ISSUE THREAD

**Issue by markotfk** [jellyfin/jellyfin#10413]
### Please describe your bug

Due to incorrect references in project file the Jellyfin.Server.Fuzz does not compile.
There are references to dlls directly, change to project references to make it compile.
#hacktoberfest PR 

### Jellyfin Version

Other

### if other:

master

### Environment

```markdown
- OS:
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by markotfk** [comment]
From cc8f7fb83e686708973e0ab7d06e85cff8c1bff5 Mon Sep 17 00:00:00 2001
From: Marko Karjalainen <markotfk@gmail.com>
Date: Mon, 16 Oct 2023 18:34:17 +0300
Subject: [PATCH] Fix fuzz project compile problem

---
 .../Emby.Server.Implementations.Fuzz.csproj               | 4 +---
 fuzz/Jellyfin.Server.Fuzz/Jellyfin.Server.Fuzz.csproj     | 8 +++++---
 fuzz/Jellyfin.Server.Fuzz/Program.cs                      | 2 +-
 3 files changed, 7 insertions(+), 7 deletions(-)

diff --git a/fuzz/Emby.Server.Implementations.Fuzz/Emby.Server.Implementations.Fuzz.csproj b/fuzz/Emby.Server.Implementations.Fuzz/Emby.Server.Implementations.Fuzz.csproj
index 1e3f8a048..90c7e96ed 100644
--- a/fuzz/Emby.Server.Implementations.Fuzz/Emby.Server.Implementations.Fuzz.csproj
+++ b/fuzz/Emby.Server.Implementations.Fuzz/Emby.Server.Implementations.Fuzz.csproj
@@ -6,9 +6,7 @@
   </PropertyGroup>
 
   <ItemGroup>
-    <Reference Include="Emby.Server.Implementations">
-      <HintPath>Emby.Server.Implementations.dll</HintPath>
-    </Reference>
+    <ProjectReference Include="../../Emby.Server.Implementations/Emby.Server.Implementations.csproj" />
   </ItemGroup>
 
   <ItemGroup>
diff --git a/fuzz/Jellyfin.Server.Fuzz/Jellyfin.Server.Fuzz.csproj b/fuzz/Jellyfin.Server.Fuzz/Jellyfin.Server.Fuzz.csproj
index 20bc4c724..f9a90d2cb 100644
--- a/fuzz/Jellyfin.Server.Fuzz/Jellyfin.Server.Fuzz.csproj
+++ b/fuzz/Jellyfin.Server.Fuzz/Jellyfin.Server.Fuzz.csproj
@@ -6,14 +6,16 @@
   </PropertyGroup>
 
   <ItemGroup>
-    <Reference Include="Jellyfin.Server">
-      <HintPath>jellyfin.dll</HintPath>
-    </Reference>
+    <ProjectReference Include="../../Jellyfin.Server/Jellyfin.Server.csproj" />
   </ItemGroup>
 
   <ItemGroup>
     <ProjectReference Include="../../MediaBrowser.Common/MediaBrowser.Common.csproj" />
   </ItemGroup>
+  
+  <ItemGroup>
+    <ProjectReference Include="../../Jellyfin.Api/Jellyfin.Api.csproj" />
+  </ItemGroup>
 
   <ItemGroup>
     <PackageReference Include="SharpFuzz" />
diff --git a/fuzz/Jellyfin.Server.Fuzz/Program.cs b/fuzz/Jellyfin.Server.Fuzz/Program.cs
index e47286c13..886fc9303 100644
--- a/fuzz/Jellyfin.Server.Fuzz/Program.cs
+++ b/fuzz/Jellyfin.Server.Fuzz/Program.cs
@@ -1,6 +1,6 @@
 ﻿using System;
 using System.Collections.Generic;
-using Jellyfin.Server.Middleware;
+using Jellyfin.Api.Middleware;
 using Microsoft.AspNetCore.Http;
 using Microsoft.AspNetCore.Http.Features;
 using Microsoft.Extensions.Primitives;
-- 
2.41.0.windows.1

**Comment by Bond-009** [comment]
Firstly, this isn't a hacktoberfest PR, secondly these fuzz projects are designed to be used with the fuzz.sh scripts. We don't just reference the project as the dll needs to be instrumented.
