### ISSUE TITLE
[Issue]: Albums not appearing on JF

### ISSUE THREAD

**Issue by Ucda1212** [jellyfin/jellyfin#10412]
### Please describe your bug

I put some of my .MP3 files on Jellyfin to listen to, but albums don't appear. I tried refreshing metadata, and have confirmed that the album is listed in the metadata. I have also tried turning off the Jellyfin Themes plugin, thinking maybe it could be an error on there, but to no avail.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Windows
- Linux Kernel: None
- Virtualization: None
- Clients: Browser, Android
- Browser: Firefox
- FFmpeg Version: 6
- Playback Method: Direct
- Hardware Acceleration: Nvidia NVENC
- GPU Model: 3050 Ti
- Plugins: Jellyscrub, Skin manager
- Reverse Proxy: none
- Base URL: none
- Networking: host
- Storage: local
```

### Please attach any screenshots here

![Screenshot 2023-10-16 100846](https://github.com/jellyfin/jellyfin/assets/89806474/519b0383-70ff-4799-b08c-21b876a9051f)
![Screenshot 2023-10-16 100900](https://github.com/jellyfin/jellyfin/assets/89806474/d713791c-5d44-43a5-bd00-f59ed5e639b2)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
Closing this as a duplicate to #1757
