### ISSUE TITLE
[Issue]: deleted collections keep coming back

### ISSUE THREAD

**Issue by dd900** [jellyfin/jellyfin#10411]
### Please describe your bug

Ubuntu 22.04
Jellyfin Docker
v10.8.11

Deleted collections reappear. All collection related options are turned off. Including `Group movies into collections` and `<EnableAutomaticSeriesGrouping>false</EnableAutomaticSeriesGrouping>` in `/config/data/root/default/Collections/options.xml` that I can not find a UI entry for.

I expect that if I delete a collection, regardless of settings, it stays deleted. I also expect that collections will not be autogenerated in the first place as I have all the options turned off.

Collections that won't go away show up in `/config/data/data/collections` with names like `B420CI~M` and `BTSF7C~K`.

### Jellyfin Version

10.8.z

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
Closing this as a duplicate to #1055
