### ISSUE TITLE
[Issue]: Space bar doesn't trigger pause/play during music playback

### ISSUE THREAD

**Issue by asdil12** [jellyfin/jellyfin#10429]
### Please describe your bug

During video playback the space bar triggers play/pause.
But during music playback (while the player is shown at the bottom or when viewing the playlist) this doesn't work.

### Jellyfin Version

10.8.z

### Environment

```markdown
- Browser: Vivaldi (chromium)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
Duplicate of [jellyfin-web/#4857](https://github.com/jellyfin/jellyfin-web/issues/4857)
