### ISSUE TITLE
[Issue]: Keeps caching station logos forever, even if they change in M3U and XML

### ISSUE THREAD

**Issue by Moonbase59** [jellyfin/jellyfin#10421]
### Please describe your bug

Seems https://github.com/jellyfin/jellyfin/issues/8903 is still an issue: Station logos are somehow kept forever, even after a Jellyfin restart.

I have some stations that changed their logo (as can be seen in the `m3u` and `xml` files, but Jellyfin never updates these. Clearing the browser cache doesn’t help, and it also shows the old logos in the Desktop Media Player (Win & Linux), the AndroidTV clients.

Even deleting all M3U tuners and TV Guide Data Providers (XMLTV) and then recreating them doesn’t help!

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Ubuntu 22.04.3 LTS
- Linux Kernel:
- Virtualization: Proxmox LXC
- Clients: Misc
- Browser: Firefox 118.0.2, MS Edge, Chromium
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration: VAAPI
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by GodBleak** [comment]
As a workaround, you can delete the contents of `livetv` in your metadata folder.

**Comment by Arch-Storm** [comment]
> As a workaround, you can delete the contents of `livetv` in your `metadata` folder.

this doesn't seem to work for me at all. i deleted the m3u tuner and xmltv inside the app and turned off the container. then i deleted the livetv metadata; deleted xmltv and image cache fully; cleared browser cache; start jellyfin again; readd m3u and xmltv; images are still completely different than in the m3u file.

**Comment by Arch-Storm** [comment]
ok, i dug a bit deeper using debug logs and found that specifically all images hosted on imgur had problems. i then found that imgur for some reason has rate limited my server ip and i was getting 429 errors on those images. changing the images to a different host fixed the problem again after deleting livetv in metadata.
