### ISSUE TITLE
Allow arbitrary subdirectories in albums

### ISSUE THREAD

**Issue by Chais** [jellyfin/jellyfin#10425]
As discussed at length in #5605 there is a variety of options when it comes to naming media in albums. With MusicBrainz using "CD", "Digital Media", "LP", "Cassette" and many more and some artists simply naming the volumes instead of enumerating them I see no reason to impose any restrictions on the sub-directories of an album.

This issue mostly serves to announce my willingness to work on this matter, so if you would rather track the progress in the bug report, feel free to close this issue. I'd need some guidance on where to find the responsible piece(s) of code, as a quick search for CD, Disc and Volume in the server code came up empty.  
As for my approach, I would allow any sub-directory in an album to be used. Effectively `Artist/Album/*`. I suspect this change to mostly a deletion.

**Comment by felix920506** [comment]
Hi, we appreciate your will. However, this is not an appropriate place for having a discussion for the solution to a problem.

Discussions should be had in the [Discussions tab](https://github.com/jellyfin/jellyfin/discussions) or in our [Matrix/Discord development channels](https://jellyfin.org/contact)

Closing this one to keep the issue tracker clean
