### ISSUE TITLE
[Issue]: Randomly unhandled exception crashes

### ISSUE THREAD

**Issue by mobamoba** [jellyfin/jellyfin#10431]
### Please describe your bug

I have no idea why this crash is now randomly happening as my server (Windows 2019) hasn't changed in ages other than the monthly Windows security updates. Basically Jellyfin crashes and unfortunately doesn't autorestart itself meaning a user has to tell me Jellyfin is down and I have to go in there and manually click start. There's seems to be no logic to it as in Jellyfin is fine for a week then randomly does this for no reason I can see. All that's happening is people are direct playing videos so no transcoding or anything like that.

Here are the errors I've seen in the Windows Event View Logs:

Application: jellyfin.exe CoreCLR Version: 6.0.1623.17311 .NET Version: 6.0.16 Description: The process was terminated due to an unhandled exception. Exception Info: System.InvalidOperationException: Collection was modified; enumeration operation may not execute. at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext() at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext() at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer) at PreviousActions.Cleanup() at Jellyfin.Plugin.MediaTracker.ServerEntryPoint.OnPlaybackChanged(PlaybackProgressEventArgs e, String action) at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state) at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi) at System.Threading.QueueUserWorkItemCallback.Execute() at System.Threading.ThreadPoolWorkQueue.Dispatch() at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart() 

Also:

Faulting application name: jellyfin.exe, version: 0.0.0.0, time stamp: 0x641cef7e Faulting module name: KERNELBASE.dll, version: 10.0.17763.4720, time stamp: 0xbbeed0d7 Exception code: 0xe0434352 Fault offset: 0x00000000000349b9 Faulting process id: 0x31fc Faulting application start time: 0x01d9fe846db5bbbd Faulting application path: C:\Program Files\Jellyfin\Server\jellyfin.exe Faulting module path: C:\windows\System32\KERNELBASE.dll Report Id: b7bd6d25-f2c9-4450-9813-da12cb2d6cf2 Faulting package full name: Faulting package-relative application ID: 

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Windows 2019
- Linux Kernel:
- Virtualization:
- Clients: Browser, Android, Kodi, Ipad
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
[2023-10-17 21:10:40.705 -04:00] [INF] [3] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : "03bc8ee3-de4d-4938-b74a-2ad2c2129db3-ea994aa99b344eaaa2c8f78a5b2dc208-04cc55cfc5c1c3c6c1cfdbec2a120618"
[2023-10-17 21:10:40.710 -04:00] [FTL] [107] Main: Unhandled Exception
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at PreviousActions.Cleanup()
   at Jellyfin.Plugin.MediaTracker.ServerEntryPoint.OnPlaybackChanged(PlaybackProgressEventArgs e, String action)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mobamoba** [comment]
The issue has not been fixed. I get the same error listed up top at random intervals, and I have no idea what's triggering it since JF can go for weeks without issue then suddenly it crashes with that error.

**Comment by Bond-009** [comment]
From the logs it's clear that this is an issue with a plugin that you're using
`at Jellyfin.Plugin.MediaTracker.ServerEntryPoint.OnPlaybackChanged`
https://github.com/bonukai/jellyfin-plugin-mediatracker
