### ISSUE TITLE
Account based stream limit

### ISSUE THREAD

**Issue by hellfire1980** [jellyfin/jellyfin#1044]
Does jellyfin has the function to control same login to different devices to stream is prohibited at the same time?

**Comment by LogicalPhallacy** [comment]
I am not 100% sure I follow, but if you are asking if Jellyfin can stream to multiple devices on the same user at the same time, the answer is yes, as long as your hosting machine can handle it

**Comment by hellfire1980** [comment]
Sorry for my bad English, what i mean was there maybe some shitting friends share their login to multiple people. Which may cause high load on server side. Is there any function that can control on this part?

**Comment by EraYaN** [comment]
As far as I know there is no account based stream limiting currently, best way would be to solve this problem in "meat-space" as it were.

**Comment by anthonylavado** [comment]
Changed the title to better reflect the question/issue.

**Comment by pixelfudge** [comment]
Requesting too
