### ISSUE TITLE
[Issue]: Migrating from container image jellyfin/jellyfin to lscr.io/linuxserver/jellyfin

### ISSUE THREAD

**Issue by nodje** [jellyfin/jellyfin#10445]
### Please describe your bug

I'm using 10.8.11 \.

the data structure seem as expected on both sides (external data mounted on /config inside the container), but I get an ` error processing request: Invalid username or password entered. URL POST /Users/authenticatebyname.` after starting with the new image 

Would someone help me understand the datastructure and where could the issue be?

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS:
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shadowghost** [comment]
You cannot switch between the images because the structure is not the same, you'd need to manually change specific config options in the lsio image to make this work. We do not support this kind of migration and highly encourage using the official image.
