### ISSUE TITLE
[Issue]: Once Transcoding is completedthe playback freezes, but Jellyfin thinks it's still playing

### ISSUE THREAD

**Issue by ConnorBS** [jellyfin/jellyfin#10449]
### Please describe your bug

Playing large videos that require transcoding for Jellyfin Android App or Web browser will play until the transcoding is fully completed. Once Transcoding is completed (The red bar on the Server Dashboard, under Active Devices), the playback on the client looks like it freezes though the UI shows that you can pause the content (as it's playing but not progressing)

On the server Dashboard under Active Devices, it looks like it is still playing, updating the play time by 2 seconds every two seconds until the 5 second, it loops back to the start of the loop:
1:38:41-> 2 seconds -> 1:38:43 -> 2 seconds -> 1:38:45 -> 1 second -> 1:38:41

Pause/Play will only play a little bit of video, and will stop playing anymore. You have to exit and start up the stream again, and watch until the transcoding completes again.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Unraid 6.12.4
- Virtualization: Docker
- Clients: Browser, Android
- Browser: Chrome
- FFmpeg Version: 5.1.3-Jellyfin
- Playback Method:
- Hardware Acceleration: VAAPI
- GPU Model: AMD 570
- Reverse Proxy: nginx + direct
- Base URL: None
- Networking: Bridge
- Storage: Local HDD media, Local SSD Transcode file
```

### Jellyfin logs

```shell
Logs attached below (Logs too big)
```

### FFmpeg logs

```shell
Logs attached below (Logs too big)
```

### Please attach any browser or client logs here

[FFmpeg.Transcode-2023-10-21_23-53-57_b77f9174150344078ec958b03dc377b1_c7d6fc8e.log](https://github.com/jellyfin/jellyfin/files/13062433/FFmpeg.Transcode-2023-10-21_23-53-57_b77f9174150344078ec958b03dc377b1_c7d6fc8e.log)
[log_20231022.txt](https://github.com/jellyfin/jellyfin/files/13062434/log_20231022.txt)

### Please attach any screenshots here

![20231022_002715](https://github.com/jellyfin/jellyfin/assets/45362496/77851491-43d9-49c3-91f8-b86e560c1556)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by srcrist** [comment]
Can you also provide your Jellyfin server log, and exact steps to reproduce the issue? Those would also be helpful, I think.

**Comment by ConnorBS** [comment]
Was the log file I attached lacking? Reattached here incase it was passed over as it was too long to post in the body:
[log_20231022.txt](https://github.com/jellyfin/jellyfin/files/13064507/log_20231022.txt)

It consistently presents the issue when using large files that require transcoding, an example would be this media:
```
General
ID                                       : 0 (0x0)
Complete name                            : \\HOMEBASE\rootshare\Media\Movies\Holes (2003)\Holes (2003) BR-DISK.m2ts
Format                                   : BDAV
Format/Info                              : Blu-ray Video
File size                                : 33.0 GiB
Duration                                 : 1 h 57 min
Overall bit rate mode                    : Variable
Overall bit rate                         : 40.2 Mb/s
Maximum Overall bit rate                 : 48.0 Mb/s
Frame rate                               : 23.976 FPS

Video
ID                                       : 4113 (0x1011)
Menu ID                                  : 1 (0x1)
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4.1
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 4 frames
Codec ID                                 : 27
Duration                                 : 1 h 57 min
Bit rate mode                            : Variable
Maximum bit rate                         : 35.0 Mb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Time code of first frame                 : 00:59:59:0000000000

Audio
ID                                       : 4352 (0x1100)
Menu ID                                  : 1 (0x1)
Format                                   : DTS XLL
Format/Info                              : Digital Theater Systems
Commercial name                          : DTS-HD Master Audio
Muxing mode                              : Stream extension
Codec ID                                 : 134
Duration                                 : 1 h 57 min
Bit rate mode                            : Variable
Channel(s)                               : 6 channels
Channel layout                           : C L R Ls Rs LFE
Sampling rate                            : 48.0 kHz
Frame rate                               : 93.750 FPS (512 SPF)
Bit depth                                : 24 bits
Compression mode                         : Lossless

Text
ID                                       : 4608 (0x1200)
Menu ID                                  : 1 (0x1)
Format                                   : PGS
Codec ID                                 : 144

```

**Comment by srcrist** [comment]
Oh, my apologies. I saw the ffmpeg log and missed the server log. That's fine. Thank you for attaching them. I do not, however, see anything in either log indicating a server bug. The fact that we're not seeing a lot of issues reported on this behavior with this very common configuration that you're using suggests that it's probably limited to your specific setup. It may be a docker networking issue, or the proxy. 

I'll set this aside for some further testing to see if anyone else is able to reproduce it. Please add any additional information if you think of anything.
