### ISSUE TITLE
[feature] Option to configure disabling of users after failed login attempts

### ISSUE THREAD

**Issue by MalteT** [jellyfin/jellyfin#1045]
Jellyfin currently disables a user after a couple of failed login attempts (I think 3). This is especially hurtful for admin accounts, because you have to search for the right `/config/config/users/[gibberish]/policy.xml` to enable the account again.

If the Jellyfin setup is accessible from WAN, third parties might just spam login attempts to constantly block you from using Jellyfin, because a blocked user gets logged out on all devices.

I would like to be able to **disable the auto-disable funtion for specific users** and if possible **configure the amount of failed logins before the user gets disabled**. (Some timeout between login attempts would be nice)

#870 might already address some of the these.

**Comment by LogicalPhallacy** [comment]
This is fixed in master, it will be in the upcoming 10.3.
