### ISSUE TITLE
Songs with special symbols only in title doesnt show up correctly under artist

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [jellyfin/jellyfin#10459]
### Please describe your bug

I tried to save the song [(no name)](https://youtu.be/UxM5UgpXYM4) to my library. I downloaded the song from YouTube (the artist provided a google drive link) and transcoded it to mp3 for compatibility. Since the artist (also has no name) created more than one song with no name, I have to use the identifier given by youtube music. 

I tried to set the artist name to `x0o0x_` and the song name to `/ / // / /` in a mp3 tag editor, as thats what YouTube music claims it to be.

The song did show up in the list of songs but didnt under artist tab. Strangely, the song length (2m14s) did get added to the artist total runtime(?).

_see screenshots_
Escaping the title (`\/ \/ \/\/ \/ \/`) has no different.

In both cases, the song can be played in the songs tab

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Debian 11
- Linux Kernel: 6.1.21-v8+
- Virtualization: None
- Clients: Browser, Android
- Browser: Chrome 118
- FFmpeg Version: 5.1.3-5-bullseye
- Playback Method: Direct play
- Hardware Acceleration: None
- GPU Model: None
- Plugins: Musicbrainz
- Reverse Proxy: None
- Base URL: pi.jellyfin:8096
- Networking: Direct connect
- Storage: local sata SSD via USB3
```

### Jellyfin logs

```shell
N/A
```

### FFmpeg logs

```shell
N/A
```

### Please attach any browser or client logs here

![Screenshot_2023-10-23-21-56-47-582_com kiwibrowser browser-edit](https://github.com/jellyfin/jellyfin/assets/64138578/7fd7bac0-7103-49a7-b4fe-906c7ffd006c)

### Please attach any screenshots here

![Screenshot_2023-10-23-21-44-54-439_com android chrome-edit](https://github.com/jellyfin/jellyfin/assets/64138578/1c177dde-11c8-41f0-a016-55411a5e2eae)
![Screenshot_2023-10-23-21-44-42-343_com android chrome-edit](https://github.com/jellyfin/jellyfin/assets/64138578/987164be-e891-45f3-a11e-077485b8ff4b)
![Screenshot_2023-10-23-22-07-01-907_com.android.chrome-edit.jpg](https://github.com/jellyfin/jellyfin/assets/64138578/795a642c-e260-470f-bd6b-9f392f6eb1a0)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
Hi, please provide a sample file with the empty title.

**Comment by SodaWithoutSparkles** [comment]
@felix920506 wouldnt that violate copyright or sth?

**Comment by TheMelmacian** [comment]
You don't need to provide the complete song. It can be a small part of the song or a complete new audio file. Important is that it uses the same name and metadata so the error can be reproduced in a local test environment.

**Comment by SodaWithoutSparkles** [comment]
now I cant produce it reliably. It could be due to the fact that the artist was already initialized, or some other reason

anyway, I will still provide the file. I used a ffmpeg filter to make the volume to 0.

![nameless.mp3.zip](https://github.com/jellyfin/jellyfin/files/13116869/nameless.mp3.zip)

the initial file structure I used is as follows

- Music
  - song1.mp3
  - x0o0x_
    -  nameless.mp3 
  - some other artist
    - album1
      - song2.mp3
    - album2
      - song3.mp3

**Comment by felix920506** [comment]
Can you provide one with an empty title instead of a bunch of backslashes?

**Comment by SodaWithoutSparkles** [comment]
The zip contains 2 files. 
One with a title of `""`, the other has `" "`.

```
ffmpeg -i in.mp3 -filter:a "volume=0" -metadata title="" out.mp3
```

[nameless.zip](https://github.com/jellyfin/jellyfin/files/13125437/nameless.zip)

That said, according to YouTube, the song is really called `/ / // / /`
