### ISSUE TITLE
[Issue]: error/warning sounds after upgrading from 10.7.7 to 10.8.11 via winget

### ISSUE THREAD

**Issue by ricardonevesmusic** [jellyfin/jellyfin#10464]
[Issue]: error/warning sounds after upgrading from 10.7.7 to 10.8.11 via winget

After updating from version 10.7.7 to 10.8.11 via winget (using Windows Powershell), every time I scan the library or so in any device, the Windows plays an error/warning sound (the same things also happen when I access some of the menus inside th local IP address in Chrome).

I feel like something is wrong, because I didn't get these sounds before.

Hopefully we'll find a way to fix this.

Thank you.

---

**Jellyfin install version:**
10.8.11

---

- OS: Windows 10 x64
- Linux Kernel:
- Virtualization:
- Clients: Browser
- Browser: Chrome 118.0.5993.89
- FFmpeg Version: (have no idea)
- Playback Method: (have no idea atm)
- Hardware Acceleration: none
- GPU Model: NVIDIA EN210 1GB
- Plugins:
- Reverse Proxy: none
- Base URL: none
- Networking:
- Storage: local

---

[log_20231023.log](https://github.com/jellyfin/jellyfin/files/13079754/log_20231023.log)

---

[chrome console logs.txt](https://github.com/jellyfin/jellyfin/files/13079758/chrome.console.logs.txt)

**Comment by ricardonevesmusic** [comment]
UPDATE:
The sounds seem to come off of Jellyfin CMD console (at least it's what appears on the section of listed applications in sound panel/manager).

**Comment by felix920506** [comment]
Hi, exact timestamps of when the sounds happened would be appreciated.

**Comment by ricardonevesmusic** [comment]
I'll close this issue.

Not that it's been solved, but rather that I don't have time to follow through and deal with it.

Solution for now, was to disable the Jellyfin console sounds in the sound panel.

There's some issues with "ffprobe" and a few other things, but right now I don't have too much time.

And things seem to be working okay in the web interface and in the other devices I'm using.

I don't know what the problem is, but it doesn't seem to be a critical one, as all the movies/subs I added in there, seem to work just fine.

The only issues (according to the log), would be something related with .NET Framework, Schemas, not found content, etc.

Well, it seems to be working okay for the use I give it (which is not much at the time: maybe once or twice a week/near the weekends).

If I have more time to investigate this properly, I'll reopen this thread or create a new one.

Thank you so much for the help.

(apologies for having wasted your time)

**Comment by ricardonevesmusic** [comment]
I'll close this issue.

Not that it's been solved, but rather that I don't have time to follow through and deal with it.

Solution for now, was to disable the Jellyfin console sounds in the sound panel.

There's some issues with "ffprobe" and a few other things, but right now I don't have too much time.

And things seem to be working okay in the web interface and in the other devices I'm using.

I don't know what the problem is, but it doesn't seem to be a critical one, as all the movies/subs I added in there, seem to work just fine.

The only issues (according to the log), would be something related with .NET Framework, Schemas, not found content, etc.

Well, it seems to be working okay for the use I give it (which is not much at the time: maybe once or twice a week/near the weekends).

If I have more time to investigate this properly, I'll reopen this thread or create a new one.

Thank you so much for the help.

(apologies for having wasted your time)

**Comment by ricardonevesmusic** [comment]
I'll close this issue.

Not that it's been solved, but rather that I don't have time to follow through and deal with it.

Solution for now, was to disable the Jellyfin console sounds in the sound panel.

There's some issues with "ffprobe" and a few other things, but right now I don't have too much time.

And things seem to be working okay in the web interface and in the other devices I'm using.

I don't know what the problem is, but it doesn't seem to be a critical one, as all the movies/subs I added in there, seem to work just fine.

The only issues (according to the log), would be something related with .NET Framework, Schemas, not found content, etc.

Well, it seems to be working okay for the use I give it (which is not much at the time: maybe once or twice a week/near the weekends).

If I have more time to investigate this properly, I'll reopen this thread or create a new one.

Thank you so much for the help.

(apologies for having wasted your time)

**Comment by ricardonevesmusic** [comment]
I'll close this issue.

Not that it's been solved, but rather that I don't have time to follow through and deal with it.

Solution for now, was to disable the Jellyfin console sounds in the sound panel.

There's some issues with "ffprobe" and a few other things, but right now I don't have too much time.

And things seem to be working okay in the web interface and in the other devices I'm using.

I don't know what the problem is, but it doesn't seem to be a critical one, as all the movies/subs I added in there, seem to work just fine.

The only issues (according to the log), would be something related with .NET Framework, Schemas, not found content, etc.

Well, it seems to be working okay for the use I give it (which is not much at the time: maybe once or twice a week/near the weekends).

If I have more time to investigate this properly, I'll reopen this thread or create a new one.

Thank you so much for the help.

(apologies for having wasted your time)
