### ISSUE TITLE
[Issue]: With 'Enable Rewatching in Next Up' enabled, special episodes are never removed from Next Up

### ISSUE THREAD

**Issue by fuzxi** [jellyfin/jellyfin#10470]
### Please describe your bug

Reproduction:
1. In Settings > Display,  Check 'Enable Rewatching in Next Up'.
2. Using any series in a Shows library, which includes at least one episode in a 'Specials' season and at least one episode in any other season, mark the series as watched.

Expected behavior:
Since all episodes have been watched, the series should not be shown in Next Up.

Actual behavior:
Special episodes are not removed from Next Up after being watched. They are only removed from Next Up if a different episode of the series is watched (whereupon the next episode replaces the special), or the entire series is marked as unwatched. Marking the special episode as watched/unwatched does not remove it from Next Up.

### Jellyfin Version

10.8.z

### if other:

10.8.11

### Environment

```markdown
- OS: Debian 12
- Linux Kernel: 6.1
- Virtualization: Docker
- Clients: Browser, Android
```

### Please attach any screenshots here

![2023-10-24-16-57-10](https://github.com/jellyfin/jellyfin/assets/33790641/ca8b77d9-a7b8-4b59-9501-fceadd9ea2b8)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SenorSmartyPants** [comment]
Sounds like this would be fixed by #8248

**Comment by fuzxi** [comment]
Hey, thanks for the reply. I did see your issue #7534 but didn't realize it was the same bug for some reason. I'll close this in favor of your issue + PR.

**Comment by SenorSmartyPants** [comment]
Thanks for up voting my issue and PR.
