### ISSUE TITLE
[Issue]: User/Pass sent in cleartext

### ISSUE THREAD

**Issue by habeebtc** [jellyfin/jellyfin#10476]
### User/Pass sent in cleartext during login

Security best practices dictate that a cleartext password should never be sent over the wire, but instead a password hash which is validated against a hash of the password stored in the database.  

Steps to reproduce:

1. Open JellyFin in a browser
2. Go into Developer mode
3. Log on with username and password
4. Check the entry for /Users/authenticatebyname, under "Network" and the "Payload" of the request being sent.

You will see a JSON blob like so:

{Username: "username", Pw: "password"}

What is strange is, the password appears to be stored hashed in the database.  The remediation for this is to generate the hash client-side and send that across the wire.  Some remediation can be accomplished by using HTTPS, but this is still vulnerable to a MITM attack.

I do not know if the same issue is present in any of the client applications (yet).  Will investigate and update.

### Jellyfin Version

10.8.9

### Environment

```markdown
- OS: Windows
- Linux Kernel:
- Virtualization:
- Clients: Browser
- Browser: Brave
- FFmpeg Version: 
- Playback Method: 
- Hardware Acceleration: 
- GPU Model: none
- Plugins: default
- Reverse Proxy: none
- Base URL: http://192.168.2.155:8096
- Networking: 1x gigabit adapter
- Storage: 2x 14tb mirrored SATA drives
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cvium** [comment]
So you're saying the OAuth2 spec is insecure?

**Comment by habeebtc** [comment]
To your point @cvium, the OAuth2 spec has this to say:

https://www.rfc-editor.org/rfc/rfc6749#section-1.3.3

The authorization server MUST require the use of TLS as described in when sending requests using password authentication.

https://www.rfc-editor.org/rfc/rfc6749#section-2.3.1

Clients in possession of a client password MAY use the HTTP Basic
   authentication scheme as defined in [[RFC2617](https://www.rfc-editor.org/rfc/rfc2617)] to authenticate with
   the authorization server.

If we're going by the letter of the RFC, then the answer instead of sending the hash would be to refuse to function in non-TLS mode.  I think that's no good for most users, who are likely using it locally.

**Comment by habeebtc** [comment]
_Nonsensical. Now the hashed password is the password, which you're sending in plain text over the wire._

At least that hash can't easily be used elsewhere.  Password security is not just about securing the one system, it's about not leaking credentials which might be re-used elsewhere.

**Comment by cvium** [comment]
If someone wants to be stupid, we can't stop them. Our recommendation is to use a reverse proxy, which handles the TLS termination, so Jellyfin cannot determine whether the connection is secure. It is up to the server admin to make it so.

We will not add password hashing on the client side. If someone reuses their password, they are likely to have it leaked elsewhere.

**Comment by oddstr13** [comment]
Pre-hashed passwords where a part of Emby back when we forked (no idea if it still is), as a security by obscurity measure.
It was removed in Jellyfin 10.3 back in 2019, you can see some of the discussion following the removal in #1222.

It doesn't actually provide any additional security, as if you can read passwords, you can also most likely manipulate the sent/received data.

Re-use of passwords is a big no-no in any case, as there are still very many services out there not properly hashing and salting their password databases. Many are actually encrypting the database, as opposed to hashing, and others are still using md5/sha1, which are trivially reversed with rainbow tables or easily brute-forced using the GPU of any somewhat modern gaming PC.

If you are exposing Jellyfin, or any other service, to the internet, you *must* use https to avoid the many different forms of MITM attacks that exists.
