### ISSUE TITLE
[Issue]: DS220j  是跑不动吗？

### ISSUE THREAD

**Issue by huyuanjun976** [jellyfin/jellyfin#10484]
### Please describe your bug

![image](https://github.com/jellyfin/jellyfin/assets/85826005/b4f77295-dc53-4fd5-b2d6-fc58cc4e10cb)
VIRT  4500m左右  系统客户端一直转圈，加载不出来了，nas也变的好卡，jellyfin是套件中心下载的

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS:
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
您好，在低配置硬件上使用Jellyfin时遇到效能问题为正常现象，请参考 https://jellyfin.org/docs/general/administration/hardware-selection 选购合适的硬件。
