### ISSUE TITLE
[Issue]: music->playlist empty but available in search and in popup add to playlist

### ISSUE THREAD

**Issue by Darkmagister** [jellyfin/jellyfin#10489]
### Please describe your bug

i would like to access my music playlists but i get and empty page (not even the filters o sort option) if i go to music then playlist, but if i try to search a playlist name it find it and i can access it and play it, also if i try to add new element to a playlist in the popup i can see my playlists there

### Jellyfin Version

10.8.z

### if other:

1.8.11

### Environment

```markdown
- OS: Linux
- Linux Kernel: 5.13
- Virtualization: Docker
- Clients: Browser,Android
- Browser: Firefox 119
- Plugins: audiodb,fanart,intro skipper, kodi sync queue, musicbrainz, omdb,opensubs,playback reporting, reports, skinmanager, studio images, tmdb, tmdb box set, tmdb trailers, trakt
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shadowghost** [comment]
Fixed in master.
