### ISSUE TITLE
[Issue]: External Subtitles Not Auto-Displaying - Need Help!

### ISSUE THREAD

**Issue by Firestorm2359** [jellyfin/jellyfin#10491]
### Please describe your bug

Hey there,

I've got a Jellyfin server on my QNAP NAS, and my clients are the Shield Pro and Shield Light (both 2019 models).

On the server side, in the subtitle settings, I've set "preferred subtitle language" to "English," and for "subtitle mode," it's set to "Always Play." All the subtitle files I want to display automatically are in the external "sidecar" .srt format. They are English, and they follow the naming convention of "thevideofilename.eng" or "thevideofilename.eng.sdh" for hearing-impaired. The external subtitles are being detected by the server without any issues.

However, sometimes they don't display by default on the client, which is a bit confusing. It's like a 50/50 situation – half the time, they work just fine, but the other half, they don't appear during playback. When that happens, I click on "subtitles," and find it's set to "none." I can manually switch them to "external SUBRIP," and they work, but they don't display automatically.

Any ideas on what might be causing this? Your help would be greatly appreciated! 

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS:
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins: Skip Intro
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
Hi, please visit our forum or chatrooms for troubleshooting: https://jellyfin.org/contact
