### ISSUE TITLE
[Issue]: Multi Part Videos / File Stacking / Split Video Files

### ISSUE THREAD

**Issue by DummerJunge** [jellyfin/jellyfin#10493]
### Please describe your bug

I know #9848 - files named according to https://jellyfin.org/docs/general/server/media/movies/

Movie Directory "./Movie Title (2023)", containing
- Movie Title.nfo
- Movie Title-cd1.mp4
- Movie Title-cd2.mp4
- Movie Title-fanart.jpg
- Movie Title-poster.jpg

Movie is recognized as "Movie Title (2023)" with an additional part, as expected.
But nfo ist not parsed (no desc, genre) and all images are not displayed

Expected: Movie is recognized as "Movie Title" (without year), nfo is read, images are displayed - like all not stacked movies.

Adding " (2023)" to the Files, like "Movie Title (2023).nfo" changes nothing.

Adding "-cd1" to the files, like "Movie Title-cd1.nfo" leads to the expected behavior, but breaks with e.g. Kodi.

Additional info:
Kodi - https://kodi.wiki/view/Naming_video_files/Movies#Split_Video_Files

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Debian 12.1, Windows 11, Synology DSM 7.2
- Linux Kernel: 
- Virtualization: Docker
- Clients: Web, Jellyfin Media Player, JellyCon, Jellyfin for Android, Infuse (paid)
- Browser: Firefox, Chromium (Ungoogled), Edge
- FFmpeg Version: Div.
- Playback Method: Div.
- Hardware Acceleration: Div.
- GPU Model: Div.
- Plugins: Only Builtin
- Reverse Proxy: No
- Base URL: locahost, local network
- Networking: local, VPN
- Storage: NAS
```

### Jellyfin logs

```shell
No erros or warning.
```

### FFmpeg logs

```shell
No recoding.
```

### Please attach any browser or client logs here

No errors or warnings.

#### Overview of all cases
<img width="881" alt="00 Overview" src="https://github.com/jellyfin/jellyfin/assets/7841822/58560e01-c929-4e19-8687-8750faf76d8f">

#### Test Movie: Not stacked, shows expected behaviour
<img width="196" alt="05 Test Movie" src="https://github.com/jellyfin/jellyfin/assets/7841822/43ea1e8f-a3ad-4b18-9bda-faa01c5bd19d">

**nfo parsed (title, genre), poster shown**
<img width="562" alt="04 Test Movie" src="https://github.com/jellyfin/jellyfin/assets/7841822/07148a5a-429e-4416-9930-2d2af10dd060">

#### Test Movie: Stacked, broken
<img width="259" alt="11 Test Movie stacked" src="https://github.com/jellyfin/jellyfin/assets/7841822/589c0d03-d0f0-4c6b-a997-dcf4894d7436">

**nfo not parsed (wrong title, no genre), no poster shown, 2nd part found - _works in e.g. Kodi_**
<img width="564" alt="10 Test Movie stacked" src="https://github.com/jellyfin/jellyfin/assets/7841822/f43c86dc-ed67-4f94-8422-cd5ab9698945">

#### Test Movie: Stacked, added part1 to file names, _non standard files name, broken e.g. in Kodi etc._
<img width="403" alt="21 Test Movie stacked part1 in Name" src="https://github.com/jellyfin/jellyfin/assets/7841822/fc10057c-2741-473a-998b-a0dd939bce51">

**nfo parsed (title, genre), poster shown, 2nd part found**
<img width="666" alt="20 Test Movie stacked part1 in Name" src="https://github.com/jellyfin/jellyfin/assets/7841822/5498f7e0-0818-47c8-9e83-1cff957756a3">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
Hi, please include screenshots of the actual behavior

**Comment by DummerJunge** [comment]
Screenshots added
