### ISSUE TITLE
Link to user specified embedded streams

### ISSUE THREAD

**Issue by RaeBoz** [jellyfin/jellyfin#105]
I don't know if it is already possible or not, but is there or could there be a way to link to embedded streaming video on random web pages? Right now I have my computer hooked up to my TV to go to web pages that host videos that I like to watch on a regular basis. Currently I use VaughnTv, 123tv or LMShows.se to watch some streams and they are sometimes (especially Vaughn) dynamic and I have to update my bookmarks. Could there be a way to enter in an address into a plugin and it pull the stream? There is something similar on Plex UAS for ArconaiTV that I love, but I would like to be able to generate my own links on the fly. Hope this makes sense.

**Comment by JustAMan** [comment]
Here's a link to "project-that-must-not-be-named", seems it describes your case: https://github.com/MediaBrowser/Wiki/wiki/Strm-files
And I think it should be working in Jellyfin.

**Comment by RaeBoz** [comment]
Thanks but this is where my mind glazes over. I am unsure what they are talking about. I think I get making the file, (http://http://streamingservice.tv/watch/ChannelA/ into the txt file and rename it to a strm file, rename it to something like ChannelA.strm), but where do I put the strm file when I finish it?

**Comment by JustAMan** [comment]
Think of it like it's a regular movie file. So put it somewhere in your libraries :-)

Pure speculation, though, never used that feature myself.
