### ISSUE TITLE
TheTVDB wont install anything

### ISSUE THREAD

**Issue by jxshuaa** [jellyfin/jellyfin#10518]
### Please describe your bug

Hey there! 

Recently I installed Jellyfin as a use for my family and my friends. It is hosted on my home lab where it has a publicly accessible URL so we can watch movies from anywhere. But I watched a tutorial and I saw that the plugin TheTVDB is a cool plugin and I installed it rebooted the servers alongside with some more plugins. And when I went to create a new library, it didn't automatically download the movies. I waited a day maybe it was my slow bandwidth, but it still doesn't work. It has all the ports open on my router, so I don't think the issue is at the network or the ports at least.
![image](https://github.com/jellyfin/jellyfin/assets/120188256/a6e31365-cbf4-483c-beaf-3b983ebad267)
![image](https://github.com/jellyfin/jellyfin/assets/120188256/60bd3fa5-336b-4347-8fc1-1f8d661aae70)
![image](https://github.com/jellyfin/jellyfin/assets/120188256/1be7a6bc-de32-43f7-9a81-c7f9d7a31c93)

The pictures I have attached shows that the actual plugin is downloaded into the server. I don't really understand why it doesn't work so I am going to give my trust to the community to give me a helping hand.

### Jellyfin Version

10.8.11

### Environment

```markdown
- OS: Ubuntu 20.04
- Virtualization: Ran as Docker Container on a KVM machine.
- Clients: Browser
- Browser: Edge, Brave & Chrome 
- Hardware Acceleration: Quick Sync Intel QSV
- GPU Model: none
- Plugins: Fanart, AniDB, AniList, AniSearch, MergeVersions (custom), Reports, TheTVDB, Open Subtitles.
- Reverse Proxy: none
- Base URL: xxx.xxx.xxx.125:8096 (public IP)
- Networking: host
- Storage: local
```

### Jellyfin logs

```shell
https://[pastebin.com/raw/i8xfUVBd](https://pastebin.com/raw/i8xfUVBd)
```

### FFmpeg logs

```shell
https://pastebin.com/anpX6tYE
```

### Please attach any browser or client logs here

no issues on browser

### Please attach any screenshots here

![image](https://github.com/jellyfin/jellyfin/assets/120188256/2e809547-4954-422c-ab4d-aca0aebe3228)
![image](https://github.com/jellyfin/jellyfin/assets/120188256/3941f75e-8a93-4614-b9a0-b988dacea986)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
Sounds like you’re looking for Jellyfin to download media. That is not something Jellyfin does. The plugins are there to provide metadata on media that you have.

**Comment by jxshuaa** [comment]
> Sounds like you’re looking for Jellyfin to download media. That is not something Jellyfin does. The plugins are there to provide metadata on media that you have.

In an online tutorial I followed the person I watched showed me how to download Jellyfin and automatically install shows using this plugin ``TheTVDB``, he created a new library with nothing on it and after a few moments it started to download movies and shows for him. Thats what essentially I want to do to.

**Comment by crobibero** [comment]
There is no support for media acquisition.
