### ISSUE TITLE
will docker version support https

### ISSUE THREAD

**Issue by lilarcor** [jellyfin/jellyfin#1052]
when I was using emby, https is enabled without issue. somehow, jellyfin docker version seems doesn't like https, it keeps running http

**Comment by JustAMan** [comment]
Did you add your own https certificate? We're not shipping a self-signed certificate there so far.

**Comment by lilarcor** [comment]
Yes, I added. And from the dashboard, it still shows http

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lilarcor** [comment]
mybad, after I use my crt  file instead of crt path, the problem solved
