### ISSUE TITLE
[Issue]: Refreshing metadata marks media as watched

### ISSUE THREAD

**Issue by HammyHavoc** [jellyfin/jellyfin#10520]
### Please describe your bug

1. `Refresh metadata`
2. Behold the "Watched" status

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS:
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
I use this feature often and have never experiencved this bug. Please fill out the template and provide more information.

**Comment by d03j** [comment]
I am not sure if it is linked to refreshing metadata but i just had thousands of episodes an movies marked watched in the course of one hour. I can't see anything obvious on the logs but when I look at trakt.tv I can see them all marked watched on Nov 2nd.

Is there any way to programmatically undo the marking for all media marked as watched between two date/times? I have the trakt and playback plugins installed

**Comment by d03j** [comment]
FWIW, looking at trakt it looks it started marking the next up and latest shows/movies as watched.

**Comment by TheMelmacian** [comment]
Did you set the metadata language for the affected media? I experienced a similar bug when I pinned the metadata of shows to another language: https://github.com/jellyfin/jellyfin/issues/9223
But never when simply using refresh metadata.

**Comment by HammyHavoc** [comment]
> Did you set the metadata language for the affected media? I experienced a similar bug when I pinned the metadata of shows to another language: https://github.com/jellyfin/jellyfin/issues/9223
> But never when simply using refresh metadata.

Yes!
