### ISSUE TITLE
[Issue]: Collections missing artwork

### ISSUE THREAD

**Issue by mario-g98** [jellyfin/jellyfin#10529]
### Please describe your bug

I started uploading my media in the previous days so I don't know if this is a recent problem, but a bug number of automatically created collections by TMDb Box Sets Plugin don't get any artwork downloaded. Even if I click on Edit Images and then Search, no singe image is feched. 

I created a [post](https://forum.jellyfin.org/t-collections-don-t-have-thumbnails) in the forum, so apparently I'm not the only one with this problem.

### Jellyfin Version

10.8.z

### if other:

10.8.11

### Environment

```markdown
- OS: Unraid
```

### Jellyfin logs

```shell
This is the log when clicking on Refresh metadata:

[2023-11-04 21:10:26.110 +01:00] [INF] [76] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification: Started library sync
[2023-11-04 21:10:26.168 +01:00] [INF] [76] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification: Library Sync: Updated 1 items
[2023-11-04 21:10:26.168 +01:00] [INF] [76] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification: Finished library sync, taking "00:00:00.0581887"
```

### Please attach any screenshots here

![Screenshot from 2023-11-04 21-12-29](https://github.com/jellyfin/jellyfin/assets/49582442/dffd24ad-bea0-4fdd-9829-eda972f8cf32)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fogolin** [comment]
I'm also facing the same issue here. Even checked the TMDB to see if they were missing there as well, but they seem fine. One example is the John Wick collection, https://www.themoviedb.org/collection/404609-john-wick-collection, which is missing the artwork on my Jellyfin server.

**Comment by unoriginaltom** [comment]
Seeing the same issue on my side with those created by the TMDB Box Sets plugin. Weirdly, though, it seemed to work for a single collection, but none of the others.

**Comment by VigibotDev** [comment]
Same problem here.
Note few picture are downloaded of few collection, but vast majority won't.
What is surprising is that the problem is repeatable, collection of movie "xXx" for example always recovers the image correctly, but vast majority won't

**Comment by mikewesten** [comment]
Is it possible that https://github.com/jellyfin/jellyfin-plugin-tmdbboxsets has an expired API token or something.

**Comment by VigibotDev** [comment]
Collection box is a near mandatory basic feature I don't understand why plugin look not maintained....
I can create another script to download picture inside the data/collection directory of jellyfin...

**Comment by VigibotDev** [comment]
> I'm also facing the same issue here. Even checked the TMDB to see if they were missing there as well, but they seem fine. One example is the John Wick collection, https://www.themoviedb.org/collection/404609-john-wick-collection, which is missing the artwork on my Jellyfin server.

On mine I have the John wick collection artwork. Very strange it's random. You have also ghostbuster and not me. lol

**Comment by VigibotDev** [comment]
Also I suspect a very bad thing with Jellyfin. Where is to put OUR OWN TMDb API Key ? Why developers hard-code them to spy our request ?

**Comment by nielsvanvelzen** [comment]
Jellyfin does **not** spy on requests and we we avoid any code that could make us do so. The box set plugin doesn't use any API so it doesn't require an API key. It matches items based on locally available data that is provided by other plugins.

**Comment by VigibotDev** [comment]
> Jellyfin does **not** spy on requests and we we avoid any code that could make us do so. The box set plugin doesn't use any API so it doesn't require an API key. It matches items based on locally available data that is provided by other plugins.

Where is the Jellyfin main TMDb API Key ? themoviedb.org require an API Key to request.
The BOX Plugin must request BOX artwork because they are not included in metadata/library/xx/xxxxxxx..xxxxxx but only inside a /var/lib/jellyfin/data/collection/...name.../filder.jpg written by the box plugin.

**Comment by VigibotDev** [comment]
It look like a rate limit on TMDb image downloads...
I count the number of jpg file inside /var/lib/jellyfin/data/collections (watch "find | grep jpg | wc -l")
I "Search missing metadata" on the collections folder... I can add few missing JPG every hours or less... but only small amount increase each time....

If I "Search for missing metadata" twice in a row, no JPG added the second time, I must wait hours :(

**Comment by n00b12345** [comment]
It seems to be an API issue. *Some* artwork is downloaded after a few hours or so.

**Comment by VigibotDev** [comment]
> It seems to be an rate limit issue. _Some_ artwork is downloaded after a few hours or so.

Yes. This is what I see now. I launch every hours and my collection is 3/4 completed :)

Standard TMDb API don't have ratelimite (since a long time) but there is an expired key in Jellyfin and/or a new security on TMDb API server (located on Amazon-02 US) for picture only to avoid bandwidth abuses.

I expect a custom TMDb API Key config file in Jellyfin, or I must mock the TMDb API with a local HTTP proxy/cache, a complex local project but for better control/backup of my data. I already a complete mirror of TMDb API sync every days, all but not pictures....

**Comment by VigibotDev** [comment]
You can launch a bash command inside your Jellyfin data folder :

cd /var/lib/jellyfin/data/collections
watch "find | grep folder.jpg | wc -l"

to check the progress of the collection folder picture....
Don't try to "refresh missing data" more than once for each hours... it download nothing.... TMDb picture rate limite is very aggressive... Never use "Replace all picture" checkbox else you loss time....

**Comment by n00b12345** [comment]
> You can launch a bash command inside your Jellyfin data folder :
> 
> cd /var/lib/jellyfin/data/collections watch "find | grep folder.jpg | wc -l"
> 
> to check the progress of the collection folder picture.... Don't try to "refresh missing data" more than once for each hours... it download nothing.... TMDb picture rate limite is very aggressive... Never use "Replace all picture" checkbox else you loss time....

Thank you. Do you have an idea about what the rate limits are? I am guessing this isn't the standard API rate limit for TMDB API but a different one.

**Comment by VigibotDev** [comment]
This is undocumented by TMDb.... It's picture only, JSON are not ratelimited (because I make about 5/10K JSON request every days for statistics experiments and sync my TMDb complete local mirror)

![Sans titre](https://github.com/jellyfin/jellyfin/assets/4873680/f6a8cdec-173e-4f37-9789-ee8eee3dc9b7)

**Comment by VigibotDev** [comment]
There is another problem than a TMDb rate limit... because in two days I can get more pictures, I'm about 3/4 of OK and 1/4 of missing... Look like a TMDb migration in progress or a strange f%cking bug in jellyfin.
I tried a man in the middle proxy to spy TMDb API request but I need to trust a custom certificate.

**Comment by VigibotDev** [comment]
I installed mitmproxy (man in the middle proxy) and added the Certificate Authority in my Debian.

![Sans titre](https://github.com/jellyfin/jellyfin/assets/4873680/42ef6e8c-cccf-4189-b974-0e7543e10bd3)

Jellyfin just don't download missing picture !!!! It's a Jellyfin bug, no doubt !

**Comment by VigibotDev** [comment]
Another trick to test : is my last missing pictures considered as a missing metadata ?
Or does jellyfin just think it's correct in its database and doesn't try to download them again ?
But If I delete the /var/lib/jellyfin/data/collections directory to force redownload all, I can loss all my artworks.... It's bad... I need help from a developper....

**Comment by VigibotDev** [comment]
Here is an URL of a missing collection artwork :
https://api.themoviedb.org/3/collection/748?append_to_response=images&api_key=4219e299c89411838049ab0dab19ebd5
You can try it, It work, even with the api_key of Jellyfin itself :D the picture is appended to response
Poster path given in JSON is https://image.tmdb.org/t/p/w600_and_h900_bestv2/pqB8Xlu0QdwsONakoiKtortANdn.jpg
And it work !

**Comment by VigibotDev** [comment]
Use this MITMProxy command line to remplace the Jellyfin API Key with your own :

mitmdump -v -M "|4219e299c89411838049ab0dab19ebd5|xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" > /tmp/mitmdump.log
(must be launched as a systemd service or with & at the end of this CMDLine to deamonize)

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx is your TMDb API Token available on your TMDb account.

Privacy is better. TMDb don't know you use Jellyfin to request new movies added and you get your onw statistics on your own TMDb account.

**Comment by VigibotDev** [comment]
I installed adminer to see an offline copy of Jellyfin sqlite database... inside library.db :

![Sans titre](https://github.com/jellyfin/jellyfin/assets/4873680/b7c564f7-632c-44de-a6f1-a39238cb58c8)

I found my boxset... and image always NULL...
I deleted all collection directory and restarted / scanned.... there is no more pictures downloaded, and all API work. mitmproxy don't show any try to download JPG.

**Comment by VigibotDev** [comment]
I compared two library.db, the old with a working boxset, and the new with the current boxset problem
The only difference is the "Overview" not populated, Like "Images".

"Overview" is a TMDb JSON field I don't understand why Jellyfin don't get...

old without bug :
![oldboxset](https://github.com/jellyfin/jellyfin/assets/4873680/5b4553a1-c6f2-4644-92dc-de5597f9a8eb)
new with bug :
![newboxset](https://github.com/jellyfin/jellyfin/assets/4873680/5f580e09-ad6a-4054-99b2-ed11799deb9f)

**Comment by VigibotDev** [comment]
Finaly I made a tiny php script to do it, TMDb API work perfectly... Waiting help from developers...

![Sans titre](https://github.com/jellyfin/jellyfin/assets/4873680/a7ca58af-a36f-4b75-a503-235e32136457)

**Comment by tryolly** [comment]
Seems like I picked the wrong time to move from emby to jellyfin. Hopefully this issue can be fixed soon because my collection looks like crap and is very annoying.

**Comment by VigibotDev** [comment]
As a workaround, launch this script for a Linux Jellyfin server with php CLI, no dependency required :
(#php collection.php)
[collection.txt](https://github.com/jellyfin/jellyfin/files/13324620/collection.txt)
It browse all "/var/lib/jellyfin/data/collections" directory
Look inside all XML file for TMDb ID, download all missing folder.jpg (poster) and background.jpg (backdrop) from TMDb API in best quality. It use the Jellyfin API Key but you can change it.

You can also delete all subdir inside "/var/lib/jellyfin/data/collections" and launch BOXSet refresh in jellyfin admin board + launch this script to get the best last and sync collection folder.

**Comment by mario-g98** [comment]
@VigibotDev You are a legend! It worked! (Initially everything was in french, but I managed to change the language ;) ) 

But I guess images are not the only thing that is missing. After I deleted everything to refetch the metadata, now the descriptions are also missing, movies are also labeled as "Videos". 


![Screenshot](https://i.ibb.co/JHwd0Px/Screenshot-from-2023-11-11-13-08-15.png)

**Comment by VigibotDev** [comment]
TMDb BOX plugin don't load descriptions, but Jellyfin can add it with "search missing metadata"
Yes you can change language inside the TMDb API URL inside the script.

&include_image_language=en,null,fr&language=en-US

it fallback to "null" language or "fr" if no "en" poster is found.

**Comment by mario-g98** [comment]
> TMDb BOX plugin don't load descriptions, but Jellyfin can add it with "search missing metadata"

That did it! Thank you again! At least now we have a script that fixes the missing images!

**Comment by fogolin** [comment]
Following our amazing friend here, I've rewritten it in bash so those of us that are running docker can also use this workaround without having to install any new dependencies on our Docker containers.

> As a workaround, launch this script for a Linux Jellyfin server with php CLI, no dependency required : (#php collection.php) [collection.txt](https://github.com/jellyfin/jellyfin/files/13325363/collection.txt)
> 
> ```
> <?php
>  if(php_sapi_name() != "cli")
>   exit("This script is intended to be run from the CLI");
> 
>  $TMDBAPIKEY = "4219e299c89411838049ab0dab19ebd5";
>  $DIR = "/var/lib/jellyfin/data/collections";
> 
>  $TMDBURL = "https://api.themoviedb.org/3/collection";
>  $IMAGEURL = "https://image.tmdb.org/t/p/original";
> 
>  foreach(scandir($DIR) as $entry) {
>   if($entry == "." || $entry == "..")
>    continue;
> 
>   $xmlpath = "$DIR/$entry/collection.xml";
> 
>   if(!file_exists($xmlpath)) {
>    echo "File not found: \"$xmlpath\"\n";
>    continue;
>   }
> 
>   $posterpath = "$DIR/$entry/folder.jpg";
>   $backdroppath = "$DIR/$entry/background.jpg";
>   $posterexist = file_exists($posterpath);
>   $backdropexist = file_exists($backdroppath);
> 
>   if($posterexist && $backdropexist)
>    continue;
> 
>   $xml = file_get_contents($xmlpath);
>   $collection = new SimpleXMLElement($xml);
>   $tmdb = $collection->TmdbId;
> 
>   if(!$tmdb) {
>    echo "No TMDb ID in: \"$xmlpath\"\n";
>    continue;
>   }
> 
>   $url = "$TMDBURL/$tmdb?api_key=$TMDBAPIKEY&append_to_response=images&include_image_language=fr,null,en&language=fr-FR";
>   $json = @file_get_contents($url);
> 
>   if(!$json) {
>    echo "Failed to retrieve TMDb data: \"$url\"\n";
>    continue;
>   }
> 
>   $obj = json_decode($json, true);
> 
>   if(!$posterexist) {
>    $poster = $obj["poster_path"];
> 
>    if($poster) {
>     $posterurl = "$IMAGEURL$poster";
> 
>     echo "Downloading poster: \"$posterurl\"\n";
>     $image = file_get_contents($posterurl);
>     echo "Writing poster: \"$posterpath\"\n";
>     file_put_contents($posterpath, $image);
>    } else
>     echo "No poster: \"$DIR/$entry\"\n";
>   }
> 
>   if(!$backdropexist) {
>    $backdrop = $obj["backdrop_path"];
> 
>    if($backdrop) {
>     $backdropurl = "$IMAGEURL$backdrop";
> 
>     echo "Downloading backdrop: \"$backdropurl\"\n";
>     $image = file_get_contents($backdropurl);
>     echo "Writing backdrop: \"$backdroppath\"\n";
>     file_put_contents($backdroppath, $image);
>    } else
>     echo "No backdrop: \"$DIR/$entry\"\n";
>   }
>  }
> ?>
> ```
> 
> It browse all "/var/lib/jellyfin/data/collections" directory, and look inside all XML file for TMDb ID, it download all missing folder.jpg (poster) and background.jpg (backdrop) from TMDb API in best quality. It use the Jellyfin API Key but you can change it.
> 
> You can also delete all subdir inside "/var/lib/jellyfin/data/collections" and launch BOXSet refresh in jellyfin admin board + launch this script to get the best last and sync collection folder.
> 
> If you launch another time you get usefull information about missing picture for some movie collection or some dead collection TMDb ID in your database.
> 
> ![Sans titre](https://user-images.githubusercontent.com/4873680/282223489-22f110c7-8aa7-4aa0-997d-69eb8c10529d.png)

Ok, let's begin:

## The Script:
The first thing is you should get your own [TMDB API Key here](https://developer.themoviedb.org/reference/intro/authentication#api-key-quick-start). Also, check the directory for your collections. In my case, it was inside `/config/data/data/collections`, instead of @VigibotDev `/var/lib/jellyfin/data/collections`. If you don't get this path right, it wont work.

An additional update is the setting of the media language: I've added two new variables "LANG" and "LOCALE", for both, in my case, the language (pt) and location (pt-BR / Brazil).

File: collections.sh
```
#!/bin/bash

TMDBAPIKEY="{YOUR API KEY HERE}"
DIR="/config/data/data/collections"
TMDBURL="https://api.themoviedb.org/3/collection"
IMAGEURL="https://image.tmdb.org/t/p/original"
LANG="pt"
LOCALE="pt-BR"

for entry in "$DIR"/*; do
    if [ "$entry" == "$DIR/*" ]; then
        continue
    fi

    xmlpath="$entry/collection.xml"
    if [ ! -f "$xmlpath" ]; then
        echo "File not found: \"$xmlpath\""
        continue
    fi
    
    posterpath="$entry/folder.jpg"
    backdroppath="$entry/background.jpg"
    if [ -f "$posterpath" ] && [ -f "$backdroppath" ]; then
        continue
    fi

    tmdb=$(xmlstarlet sel -t -v "Item/TmdbId" "$xmlpath")

    if [ -z "$tmdb" ]; then
        echo "No TMDb ID in: \"$xmlpath\""
        continue
    fi

    url="$TMDBURL/$tmdb?api_key=$TMDBAPIKEY&append_to_response=images&include_image_language=$LANG,null,en&language=$LOCALE"
    json=$(curl -s "$url")

    if [ -z "$json" ]; then
        echo "Failed to retrieve TMDb data: \"$url\""
        continue
    fi

    if [ ! -f "$posterpath" ]; then
        poster=$(echo "$json" | jq -r .poster_path)

        if [ ! -z "$poster" ] && [ "$poster" != "null" ]; then
            posterurl="$IMAGEURL$poster"
            echo "Downloading poster: \"$posterurl\""
            curl -s "$posterurl" -o "$posterpath"
            echo "Writing poster: \"$posterpath\""
        else
            echo "No poster: \"$entry\""
        fi
    fi

    if [ ! -f "$backdroppath" ]; then
        backdrop=$(echo "$json" | jq -r .backdrop_path)

        if [ ! -z "$backdrop" ] && [ "$backdrop" != "null" ]; then
            backdropurl="$IMAGEURL$backdrop"
            echo "Downloading backdrop: \"$backdropurl\""
            curl -s "$backdropurl" -o "$backdroppath"
            echo "Writing backdrop: \"$backdroppath\""
        else
            echo "No backdrop: \"$entry\""
        fi
    fi
done
```

This is the script we're going to be running. It uses `xmlstarlet` for XML parsing, `curl` for making HTTP requests, and `jq` for JSON parsing, but on my latest install of Jellyfin on Docker, these were all present.

## Accessing the Docker container terminal
In my case, the docker container is called "jellyfin", and that's what I'm using here:
```
sudo docker exec -it jellyfin bash
```

## Creating the script
Once inside, you'll need to navigate to a new folder to store the script, I've created mine in `/data/scripts`:
```bash
mkdir /config/data/scripts
cd /config/data/scripts
```

Once in this folder, we need to create the script file. This docker container is minimal, and don't provide any pre installed editor such as `nano`, `vim` or `vi`, so we'll be creating the file using `echo`. The contents bellow should be placed all together, not one at a time, and is just the same script provided earlier, just in `echo` syntax. Remember to replace `{YOUR API KEY HERE}` with a proper value:
```
echo '#!/bin/bash' > collections.sh
echo '' >> collections.sh
echo 'DIR="/config/data/data/collections"' >> collections.sh
echo 'TMDBAPIKEY="{YOUR API KEY HERE}"' >> collections.sh
echo 'TMDBURL="https://api.themoviedb.org/3/collection"' >> collections.sh
echo 'IMAGEURL="https://image.tmdb.org/t/p/original"' >> collections.sh
echo 'LANG="pt"' >> collections.sh
echo 'LOCALE="pt-BR"' >> collections.sh
echo '' >> collections.sh
echo 'for entry in "$DIR"/*; do' >> collections.sh
echo '    if [ "$entry" == "$DIR/*" ]; then' >> collections.sh
echo '        continue' >> collections.sh
echo '    fi' >> collections.sh
echo '' >> collections.sh
echo '    xmlpath="$entry/collection.xml"' >> collections.sh
echo '    if [ ! -f "$xmlpath" ]; then' >> collections.sh
echo '        echo "File not found: \"$xmlpath\"" ' >> collections.sh
echo '        continue' >> collections.sh
echo '    fi' >> collections.sh
echo '' >> collections.sh
echo '    posterpath="$entry/folder.jpg"' >> collections.sh
echo '    backdroppath="$entry/background.jpg"' >> collections.sh
echo '    if [ -f "$posterpath" ] && [ -f "$backdroppath" ]; then' >> collections.sh
echo '        continue' >> collections.sh
echo '    fi' >> collections.sh
echo '' >> collections.sh
echo '    tmdb=$(xmlstarlet sel -t -v "Item/TmdbId" "$xmlpath")' >> collections.sh
echo '' >> collections.sh
echo '    if [ -z "$tmdb" ]; then' >> collections.sh
echo '        echo "No TMDb ID in: \"$xmlpath\"" ' >> collections.sh
echo '        continue' >> collections.sh
echo '    fi' >> collections.sh
echo '' >> collections.sh
echo '    url="$TMDBURL/$tmdb?api_key=$TMDBAPIKEY&append_to_response=images&include_image_language=$LANG,null,en&language=$LOCALE"' >> collections.sh
echo '    json=$(curl -s "$url")' >> collections.sh
echo '' >> collections.sh
echo '    if [ -z "$json" ]; then' >> collections.sh
echo '        echo "Failed to retrieve TMDb data: \"$url\""' >> collections.sh
echo '        continue' >> collections.sh
echo '    fi' >> collections.sh
echo '' >> collections.sh
echo '    if [ ! -f "$posterpath" ]; then' >> collections.sh
echo '        poster=$(echo "$json" | jq -r .poster_path)' >> collections.sh
echo '' >> collections.sh
echo '        if [ ! -z "$poster" ] && [ "$poster" != "null" ]; then' >> collections.sh
echo '            posterurl="$IMAGEURL$poster"' >> collections.sh
echo '            echo "Downloading poster: \"$posterurl\"" ' >> collections.sh
echo '            curl -s "$posterurl" -o "$posterpath"' >> collections.sh
echo '            echo "Writing poster: \"$posterpath\"" ' >> collections.sh
echo '        else' >> collections.sh
echo '            echo "No poster: \"$entry\"" ' >> collections.sh
echo '        fi' >> collections.sh
echo '    fi' >> collections.sh
echo '' >> collections.sh
echo '    if [ ! -f "$backdroppath" ]; then' >> collections.sh
echo '        backdrop=$(echo "$json" | jq -r .backdrop_path)' >> collections.sh
echo '' >> collections.sh
echo '        if [ ! -z "$backdrop" ] && [ "$backdrop" != "null" ]; then' >> collections.sh
echo '            backdropurl="$IMAGEURL$backdrop"' >> collections.sh
echo '            echo "Downloading backdrop: \"$backdropurl\"" ' >> collections.sh
echo '            curl -s "$backdropurl" -o "$backdroppath"' >> collections.sh
echo '            echo "Writing backdrop: \"$backdroppath\"" ' >> collections.sh
echo '        else' >> collections.sh
echo '            echo "No backdrop: \"$entry\"" ' >> collections.sh
echo '        fi' >> collections.sh
echo '    fi' >> collections.sh
echo 'done' >> collections.sh
```

## Running the script
For you to be able to run the script, you need to make it executable:
```
chmod -x collections.sh
```

Once that's done, just run it using:
```
./collections.sh
```

You should get a execution log on the console, looking something like this:
```
root@server:/config/data/scripts# ./collections.sh
Downloading poster: "https://image.tmdb.org/t/p/original/8QeWgrqxTVMANlAMNGqXucNLQyf.jpg"
Writing poster: "/config/data/data/collections/A História Sem Fim: Coleção [boxset]/folder.jpg"
Downloading backdrop: "https://image.tmdb.org/t/p/original/2IqXJIR1i0f6Ngq3A6rjXhQNqFc.jpg"
Writing backdrop: "/config/data/data/collections/A História Sem Fim: Coleção [boxset]/background.jpg"
... 
```

When the script is finished, you'll be able to use the console again, and that's it, no need to restart the container, nothing, it's already updated, when you load the collection's page on your client, it'll be there.

**Comment by mario-g98** [comment]
It seems that xmlstarlet is missing on Unraid and I couldn't find a way to install it, so I will stick to the python script.

**Comment by VigibotDev** [comment]
You can't mount a container directory on host ? with option -v /foo:/bar ?

**Comment by tryolly** [comment]
Finally got around to trying the above. Thank you everyone for your contributions. The docker instructions were of particular help.

I do however have 1 strange problem a couple of my collections are not downloading pictures. I get the following output
`Invalid expression: '/config/data/data/collections/National Lampoon's Vacation Collection [boxset]/collection.xml'
runtime error
Evaluating user parameter inputFile failed
no result for /config/data/data/collections/National Lampoon's Vacation Collection [boxset]/collection.xml
No TMDb ID in: "/config/data/data/collections/National Lampoon's Vacation Collection [boxset]/collection.xml"
`
I checked the collection.xml and it most definitely has a TMDb ID, it is also the correct one.

Any ideas?

**Comment by VigibotDev** [comment]
A quote escape problem in the bash version ?

**Comment by tryolly** [comment]
Thanks for the feedback @VigibotDev. I imagine that is the problem, though not going to worry about it further I just manually added the required images to those last few collections in the end.

Thanks for the help.

**Comment by PuhL** [comment]
Not sure about rate limiting. Looks like Jellyfin constructs wrong URL for artwork download.
All posters variants are missing and generating lots of 404s in web UI (any collection - menu "Image Edit" - 🔎 button).
Example request:
`https://image.tmdb.org/t/p//r14U0p13M99ccWhMg0wHprp8TQi.jpg`
But it should include picture size (`original`, `w500`, etc.):
`https://image.tmdb.org/t/p/original/r14U0p13M99ccWhMg0wHprp8TQi.jpg`

**Comment by VigibotDev** [comment]
> Not sure about rate limiting. Looks like Jellyfin constructs wrong URL for artwork download. All posters variants are missing and generating lots of 404s in web UI (any collection - menu "Image Edit" - 🔎 button). Example request: `https://image.tmdb.org/t/p//r14U0p13M99ccWhMg0wHprp8TQi.jpg` But it should include picture size (`original`, `w500`, etc.): `https://image.tmdb.org/t/p/original/r14U0p13M99ccWhMg0wHprp8TQi.jpg`

It's not a rate limiting problem because I already tested this case, I spoof with my own TMDb API Key with man in the middle reverse proxy. And my script download at high speed without problem.
A malformed URL is a better supposition yes.

**Comment by 1337joe** [comment]
Based on discussion here I just put in pull request #10737. I can't mark it as being a fix for this issue because I couldn't reproduce the missing collection images in the first place, so help testing would be appreciated if anyone can reproduce it in a dev environment.

I was able to add the TMDB API key to the `Jellyfin.Plugin.Tmdb.xml` configuration file (save your TMDb plugin configuration to regenerate the file with the API key, then change it to your own and restart Jellyfin).

I also fixed the collection identify page lacking TMDb images.

**Comment by MarcGodard** [comment]
I know this is old, but I am now having the same issue.

**Comment by POD319** [comment]
I just read this thread yesterday, and was sad to see it closed. But since someone else made the first move, I am also 100% having this issue.

**Comment by roughnecks** [comment]
Hello,
didn't want to open a new issue, but my collections are without images as well. The only collection to have them is one I created manually, all of the automatic ones don't. Also, if I look at the metadata section, all of the automatic collections are locked; tried unlocking one to no avail, always no images.

I'm running latest JF on Windows 10 and am using Chrome browser.

**Comment by zacaronii** [comment]
So, I had the same problem with my collections not having images when I had initially just allowed Jellyfin to automatically create collections by checking the setting in my movies library.

However, once I added the "TMDB Box Sets" plugin and selected "scan all libraries" in the plugin settings, all of my collections now have images.

**Comment by roughnecks** [comment]
> So, I had the same problem with my collections not having images when I had initially just allowed Jellyfin to automatically create collections by checking the setting in my movies library.
> 
> However, once I added the "TMDB Box Sets" plugin and selected "scan all libraries" in the plugin settings, all of my collections now have images.

Great Thanks! Worked like a charm :)

**Comment by zotabee** [comment]
Same issue.

However @zacaronii solution fixed it for me, apparently it removed all the imaged then redownloaded all (different ones / different source ? not sure) but now 100% of my collections have pictures again.

The question is why is this plugin even needed (except to fix this temp problem) ?

For me jellyfin worked great to download pictures initially for the first scan or when a new collection is created. It seems that the collections impacted were the ones where I removed a movie to replace it by another file (different release to be exact) of a same movie in an already existing collection. And it seems this is where jellyfin loose track of metadata and release files links.

Hopefully this will be fixed in the future.

**Comment by MarcGodard** [comment]
> So, I had the same problem with my collections not having images when I had initially just allowed Jellyfin to automatically create collections by checking the setting in my movies library.
> 
> However, once I added the "TMDB Box Sets" plugin and selected "scan all libraries" in the plugin settings, all of my collections now have images.

Awesome, this worked for me... however, now I have doubles:

![image](https://github.com/jellyfin/jellyfin/assets/5016637/58b4d26c-4572-43ad-96fa-f4faae66618f)

I noticed in the meta data that those were locked (the ones with images missing)...

![image](https://github.com/jellyfin/jellyfin/assets/5016637/b9274bff-1874-459b-89d0-112db4eba938)

I could remove the lock part... but I cannot seem to remove the ones with missing images. There is a delete option, but that looks like it will also delete the media.

**Comment by MarcGodard** [comment]
Does anyone know?

**Comment by theguymadmax** [comment]
@MarcGodard 

This happened b/c  you selected "Strip Keywords from Title" in the TMDb Box Sets plugin, which made a duplicate entry without the word collection. There are several ways to fix this, I'll outline one method below. 

1. Unselect "Strip Keywords from Title"  option from the TMDb Box Sets in Dashboard->Plugins. 
2. Shutdown the server
3. Delete all folders in your Jellyfin data directory \jellyfin\data\collections (you'll see all the collection folders in here)
4. Restart the server
5. In Dashboard->Library go to your Collections and trigger a scan of your library. This will remove all the folders you just deleted.
6. In Dashboard->Scheduled tasks manually run the Scan library for new box sets. This will recreate your collections.

**Comment by felix920506** [comment]
Please open a new issue if you are having the same problem

**Comment by aaronntw** [comment]
thanks @theguymadmax, this worked for me
