### ISSUE TITLE
[Issue]: server crashes and restarts every minute

### ISSUE THREAD

**Issue by nipsy** [jellyfin/jellyfin#10532]
### Please describe your bug

Somewhere since around Debian x86-64 package version 20231102.9-unstable from the unstable repo, The server process has been crashing during playback every minute or so with the following segfault message:

```
2023-11-03T14:32:49.271503-07:00 darkstar kernel: [13478.503812] .NET ThreadPool[123120]: segfault at 14 ip 00007f084dfb33e0 sp 00007f08390a4f30 error 4 in libSkiaSharp.so[7f084dc00000+8d7000] likely on CPU 8 (core 0, socket 0)
```

I'm not seeing much mention of this anywhere else, so I'm guessing no one has mentioned it or run into it yet.

I'm not sure if it's strictly transcoding related, but I do have a Radeon 6800 XT and I'm ussing VA-API currently.  I tried disabling throttling, but that didn't help at all.  I can certain try disabling hardware transcoding next if you think it might help.

### Jellyfin Version

Other

### if other:

10.9.0

### Environment

```markdown
- OS: Debian testing/unstable
- Linux Kernel: 6.5.10
- Virtualization: no
- Clients: mostly Android
- Browser:
- FFmpeg Version: jellyfin-ffmpeg6 6.0
- Playback Method: via Android client using transcoding
- Hardware Acceleration: yes, AMD VA-API
- GPU Model: Radeon 6800 XT
- Plugins: AudioDB, MusicBrainz, OMDb, Studio Images, TMDb
- Reverse Proxy: nginx
- Base URL:
- Networking: host
- Storage: local
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nipsy** [comment]
Disabling hardware transcoding does not help.  It still crashes with the same segfault.

**Comment by nipsy** [comment]
Also, I see https://github.com/jellyfin/jellyfin/commit/4876db82e61eb53d9793e6b68e41d1018067ff62 which is presumably related.  @Bond-009, any expected fall out from this?

**Comment by nullip** [comment]
I was getting SegFault without any playback.  Docker container was just looping through the boot sequence and seemed to just hang before segfault.

**Comment by nipsy** [comment]
@nullip, yes, to your point, even without playback, I am actually seeing the crash with that segfault.  I finally had a lull in activity and can confirm that even without any other activity, the server process is dying.  Good catch.

**Comment by JacKeTUs** [comment]
Seems that it's happening when library is rescanned
With 20231103.1 server working just fine with no restarts occuring

**Comment by Maeur1** [comment]
I cut and sliced through the recent commits as I was getting this too. I found this update to SkiaSharp was the culprit on mine and it was while scanning my library, when it tries to generate images it causes a segfault somewhere: 

https://github.com/jellyfin/jellyfin/commit/0be06f843b6d07f836e3bac390238b8eb5c8bbb8

Building the image right before this commit, the server works perfectly without any crashes when scanning the library/grabbing new images for series.
