### ISSUE TITLE
[Issue]: EncodingUtils | Input file path special character escaping incomplete

### ISSUE THREAD

**Issue by bin101** [jellyfin/jellyfin#10539]
### Please describe your bug

During usage of the plugin JellyScrub I noticed that the input file path doesn't escape all special characters allowed under linux.

i.e.:
'file:/mypath/One Piece (1999) [imdbid-tt0388629]/Season 12/One Piece (1999) - S12E54 - 379 - Brook`s Past Sad Farewell to the Cheerful Crew.mkv'

the "\`" in "Brook\`s" must be escaped.

I didn't follow the complete path handling route from jellyfin itself maybe the inputArgs handling inside Jellyscrub is the source of the issue:

https://github.com/nicknsy/jellyscrub/blob/236ed83c655b1f77fee1f59613fda8572646044b/Nick.Plugin.Jellyscrub/Drawing/OldMediaEncoder.cs#L110C9-L110C9

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Debian 12
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
Hi, this looks like a Jellyscrub issue. Please report the issue to them, thanks.
