### ISSUE TITLE
[Issue]: ScaledBorderAndShadow in ASS subtitle is not respected when burn subtitles is set to auto

### ISSUE THREAD

**Issue by joshuaavalon** [jellyfin/jellyfin#10533]
### Please describe your bug

In ASS subtitle, there is a setting `ScaledBorderAndShadow` which defines should border and shadow scale with the video resolution.

If my preference set burn subtitle to auto, no `ScaledBorderAndShadow`, `ScaledBorderAndShadow yes` and `ScaledBorderAndShadow no`, all of them has the the same effect as `ScaledBorderAndShadow yes`.

- However, if I set to burn ASS subtitle, no `ScaledBorderAndShadow` and `ScaledBorderAndShadow no` are respected and it show a non scale border and shadow.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Debian
- Linux Kernel: 
- Virtualization: Docker (linuxserver/jellyfin)
- Clients: Browser, Android
- Browser: Chrome
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration: none
- GPU Model: none
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage: local
```

### Please attach any screenshots here

`ScaledBorderAndShadow  yes`
![image](https://github.com/jellyfin/jellyfin/assets/7152420/58644405-4db7-4d9f-b678-a0ba09974b1e)

`ScaledBorderAndShadow no`
![image](https://github.com/jellyfin/jellyfin/assets/7152420/ffdb3d74-56b9-476d-b1d9-67e08928c576)

### Code of Conduct

- [X] #10534

**Comment by nyanmisaka** [comment]
@joshuaavalon Please provide subtitle files. Jellyfin just uses the subtitles/ass filter in FFmpeg without any additional style settings, so the settings in your subtitle file will be retained as is. You can check the FFmpeg command via logs.

**Comment by joshuaavalon** [comment]
@nyanmisaka I have include 3 subtitle files. `none.ass`, `yes.ass` and `no.ass` with respect to `ScaledBorderAndShadow`. 3 of them should show `Hello World!` at the beginning.

[subtitle.zip](https://github.com/jellyfin/jellyfin/files/13259769/subtitle.zip)

If you set burn subtitle, 
![image](https://github.com/jellyfin/jellyfin/assets/7152420/c523a420-a6b7-4844-9071-3784462b16e2)

It work with `no` and `none`,
![image](https://github.com/jellyfin/jellyfin/assets/7152420/6c04174b-6c49-465f-b120-152c78587004)

if you set auto,
![image](https://github.com/jellyfin/jellyfin/assets/7152420/97360eb9-df7d-4549-a190-9731426df667)

![image](https://github.com/jellyfin/jellyfin/assets/7152420/24f1f29b-b090-40bf-ae91-f69872cbf7c6)

**Comment by nyanmisaka** [comment]
@joshuaavalon 'Auto' usually means disable text based subtitle burn-in. So it should be a [jellyfin-web](https://github.com/jellyfin/jellyfin-web) issue.
AFAIK they migrate to a [new subtitle renderer](https://github.com/jellyfin/jellyfin-web/pull/4357) in JF 10.9, which may help with this issue.
Can you set up a JF 10.9 container and try with it?

**Comment by joshuaavalon** [comment]
@nyanmisaka Can you tell me which container to try? I have just tried the latest unstable `jellyfin/jellyfin:20231106.3-unstable` and it is so broken that scanning does not even works.
