### ISSUE TITLE
[Issue]: Bitrate limit is working weirdly?

### ISSUE THREAD

**Issue by Joly0** [jellyfin/jellyfin#10543]
### Please describe your bug

So i have setup my bitrate limit to 10 mbps which is 1/4 of the upload speed of my internet connection. If someone outside my networks streams something now, i can see, that the content is getting converted to fit to the 10 mbps limit, which is totally fine. Though the issue is, that i still can see uploads of 30-35 mbps coming from jellyfin, but its not consistent, its spiking every 2-3 seconds. But this makes my whole network latency increase alot. I cant play any online games that rely on stable pings like this. My in game pings keep going up and down all constantly.

Is this right? Why is this? Is there something i could do to make this work so others can still stream content but my network doesnt suffer so much from it?

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Unraid
- Linux Kernel: 6.1.49
- Virtualization: Docker
- Clients: Any
- Browser: Any
- FFmpeg Version: Jellyfin-ffmpeg5
- Playback Method:Transcode
- Hardware Acceleration:VAAPI
- GPU Model: AMD Ryzen 9 7950x iGPU
- Plugins: none
- Reverse Proxy: Nginx Proxy Manager
- Base URL:
- Networking: Bridge
- Storage: local
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joshuaboniface** [comment]
So this is a consequence of how Jellyfin chunks content to endpoints and what the "bitrate limit" actually means.

When streaming from Jellyfin, content is split into chunks; I forget exactly how long they are (IIRC about 5 seconds but could be wrong there, @jellyfin/server feel free to correct me!).

When the client is ready for the next chunk, it requests it from the server. Then the server sends that chunk as fast as it can (i.e. based on your network bandwidth) to the client.

What the birtate limit in Jellyfin means is just that, this is the maximum video bandwidth a video stream can be.

So, as an example let's say the "bitrate limit" is set to 10Mbps.

That means that, assuming a chunk size of 5 seconds and 10Mbps, then every ~5 seconds the server is going to send a 50Mb (or 6.25MB) chunk out to the client. It will send that as fast as your network allows. Then there will be a relative idle period until the next chunk, and this repeats for as long as the video is playing.

This is why you're seeing spikes like that.

Jellyfin can't do anything about a congested network. If this is causing major problems for other services, you should look into QoS in your router to de-prioritize the Jellyfin traffic (i.e. prioritize the things you care about relative to Jellyfin). There's really no other way to handle this on the Jellyfin side, as it will just transmit as fast as the network lets it, so this is not a bug.
