### ISSUE TITLE
[Issue]: Library scan doesn't work when IPv6 doesn't work

### ISSUE THREAD

**Issue by rderensy** [jellyfin/jellyfin#10548]
### Please describe your bug

Hi,

I am setting up IPv6 at home (so it doesn't work yet, I think, wip) and the option "Enable IPv6" is unchecked in Jellyfin but the network interface does have IPv6 addresses.

While looking for a solution on "library scan stuck", I came across a lot of threads, so I tried to delete the Collections, disable real-time monitoring, etc. Ultimately I came upon https://github.com/jellyfin/jellyfin/issues/2350#issuecomment-581084292 which talks about a problem with IPv6 and library scan. However, the linked issue https://github.com/jellyfin/jellyfin/issues/1002#issuecomment-1761315531 says that it's been fixed in May, and I am running Jellyfin 10.8.12 so it should be fixed for me too, but it doesn't seem to be.

So even if Jellyfin isn't configured to use IPv6, I had to add `net.ipv6.conf.eth0.disable_ipv6 = 1` to `/etc/sysctl.conf`, reboot and it started working again instantly.

I also noticed that the plugins update which happens automatically when restarting Jellyfin was stuck at 0%, so it's not just library scan but outbound connection too, as if if IPv6 fails, it doesn't fallback to IPv4.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Debian 12
- Linux Kernel: 6.5.0 (from backports)
- Virtualization: KVM
- Clients:
- Browser:
- FFmpeg Version: 5.1.3-Jellyfin
- Playback Method:
- Hardware Acceleration: QSV
- GPU Model: Arc A380
- Plugins: AudioDB, InfuseSync, MusicBrainz, OMDb, Open Susbtitles, Studio Images, TMDb, TheTVDB
- Reverse Proxy: nginx
- Base URL: none
- Networking: bridged from KVM host
- Storage: local
```

### Jellyfin logs

```shell
Nothing at all in the log.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Bond-009** [comment]
#8598 is not included in 10.8.12, it's currently only available in master/unstable and will be included in the next major release 10.9
