### ISSUE TITLE
[Issue]: Can't add shared folder.

### ISSUE THREAD

**Issue by ljdssdgOjosdgOsd** [jellyfin/jellyfin#10540]
### Please describe your bug

I have a Synology NAS DS920+ and wanted to try Jellyfin but i tried adding a library and i pressed Media and my movies folder is inside it but it will not go down  that folder into sub folders. What is stopping me from adding my folder? 

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS:
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
Hi, please head to our forum or chatrooms for general troubleshooting at https://jellyfin.org/contact/
