### ISSUE TITLE
[Issue]: Editing the Community rating for a show often leads to all metadata being reset

### ISSUE THREAD

**Issue by Henkow** [jellyfin/jellyfin#10547]
### Please describe your bug

I'm on 10.8.11. I have a lot of custom .NFO:s for TV Shows, in particular for cartoons that have A and B parts. I like to use the Community rating as a means to sort my shows in my preferred order. However, often when I change the Community rating for a given show in Jellyfin web gui everything for that show resets. So the Community rating gets reverted along with everything else including the episode .NFO:s. 

As I will now have to painstakingly redo all the .NFO:s I hope a fix can be made so this doesn't happen again. Will avoid Jellyfin for anything metadata related until then.

I use external .NFO:s for everything. It seems to happen quite consistently if I edit the Community rating back-to-back for 2-3 shows. 

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Docker through Openmediavault
- Browser: Chrome or Firefox
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
Hi, please open a new issue and fill out the bug report template, thanks.
