### ISSUE TITLE
[Issue]: Old Emby bug: Blindly picks up last of all M3U channels using same tvg-id

### ISSUE THREAD

**Issue by Moonbase59** [jellyfin/jellyfin#10561]
### Please describe your bug

Jellyfin seems to have inherited the [old Emby bug](https://emby.media/community/index.php?/topic/56084-m3u-duplicate-channel-id-not-showing/) of not handling the `tvg-id` right in M3Us: It blindly uses the last one of several identical entries, and only shows THAT entry as a channel in the UI.

Now this is definitely a BUG. Stations often have _many streams_ with the _same content_, which is referred to via the TV Guide ID (tvg-id). It’s an n:1 relation. No one would want to replicate a whole EPG for each and every stream that a station might have, just because Jellyfin blindly picks only _one_. The user might want to see them all, and decide.

In my case, it’s especially bad, since the radio has both _radio streams_ and _video streams_. These are alphabetically in the M3U, and the video stream comes last, so no chance to just listen to Radio, because Jellyfin will only show the Video stream!

Other programs (take KODI, for an example) handle this perfectly: Show _all_ streams and just use the same EPG program for the different ones. Just as indicated in the M3U.

**Please fix this, it’s extremely annoying "losing channels" that are perfectly valid.**

Before anyone asks: It is _not_ practical editing the M3U by hand:
- they’re auto-updated directly from the radio station, together with the XMLTV EPG
- manually changing the tvg-ids wouldn’t help, since the programs could then not be found anymore in the XML EPG. And I will do hell and increase the EPG size sevenfold, just to duplicate each and every program for all the 7 streams Nite radio offers.

---

The M3U, as an example (domains chaned):

```
#EXTM3U url-tvg="https://example.com/xmltv/example.com.xml" x-tvg-url="https://example.com/xmltv/example.com.xml"
#EXTINF:-1 tvg-name="Nite Radio (128kbps AAC)" group-title="Nite Radio" radio="true" tvg-id="niteradio.example.com" tvg-logo="https://example.com/api/station/1/art/0",Nite Radio (128kbps AAC)
https://example.com/listen/niteradio/radio.aac
#EXTINF:-1 tvg-name="Firefox Test (MP3)" group-title="Nite Radio" radio="true" tvg-id="niteradio.example.com" tvg-logo="https://example.com/api/station/1/art/0",Firefox Test (MP3)
https://example.com/listen/niteradio/firefox_test.mp3
#EXTINF:-1 tvg-name="Firefox Test (no Xing Header) (MP3)" group-title="Nite Radio" radio="true" tvg-id="niteradio.example.com" tvg-logo="https://example.com/api/station/1/art/0",Firefox Test (no Xing Header) (MP3)
https://example.com/listen/niteradio/firefox_test_no_xing.mp3
#EXTINF:-1 tvg-name="Nite Radio (128kbps MP3)" group-title="Nite Radio" radio="true" tvg-id="niteradio.example.com" tvg-logo="https://example.com/api/station/1/art/0",Nite Radio (128kbps MP3)
https://example.com/listen/niteradio/radio.mp3
#EXTINF:-1 tvg-name="Nite Radio (HLS)" group-title="Nite Radio" radio="true" tvg-id="niteradio.example.com" tvg-logo="https://example.com/api/station/1/art/0",Nite Radio (HLS)
https://example.com/hls/niteradio/live.m3u8
#EXTINF:-1 tvg-name="Nite Radio Testbild" group-title="Nite Radio" tvg-id="niteradio.example.com" tvg-logo="https://example.com/api/station/1/art/0",Nite Radio Testbild
https://example.com/listen/niteradio/testbild.m2t
#EXTINF:-1 tvg-name="Nite Radio Video-Stream" group-title="Nite Radio" tvg-id="niteradio.example.com" tvg-logo="https://example.com/api/station/1/art/0",Nite Radio Video-Stream
https://example.com/listen/niteradio/video.m2t
#EXTINF:-1 tvg-name="Nite Radio Berlin (128kbps MP3)" group-title="Nite Radio" radio="true" tvg-id="niteradio-berlin.example.com" tvg-logo="https://example.com/api/station/6/art/0",Nite Radio Berlin (128kbps MP3)
https://example.com/listen/niteradio-berlin/radio.mp3
#EXTINF:-1 tvg-name="Nite Radio Berlin (128kbps AAC)" group-title="Nite Radio" radio="true" tvg-id="niteradio-berlin.example.com" tvg-logo="https://example.com/api/station/6/art/0",Nite Radio Berlin (128kbps AAC)
https://example.com/listen/niteradio-berlin/radio.aac
```

"Nite Radio" has currently 7 streams (of which 2 are video), "Nite Radio Rock" zero (for testing), and "Nite Radio Berlin" has 2.

This is what’s left over in Jellyfin:

![Screenshot 2023-11-10 at 11-50-41 Jellyfin](https://github.com/jellyfin/jellyfin/assets/3706922/6c5a2c95-ac5f-404c-bb68-effb7ea0c66b)

This is how it _should_ be (used exactly same files)  .
Note KODI separates TV and Radio, thus two screenshots:

![screenshot00010](https://github.com/jellyfin/jellyfin/assets/3706922/fc295f76-d6b7-4cb9-91ae-9ad99ce16b2a)

![screenshot00009](https://github.com/jellyfin/jellyfin/assets/3706922/b32bcf0d-de29-4695-9083-1c6dab1127ca)

---

In case anyone wants to test, here are both the M3U + XML files in a ZIP:
[Test-M3U+XML.zip](https://github.com/jellyfin/jellyfin/files/13318672/Test-M3U%2BXML.zip)

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Ubuntu 22.04
- Linux Kernel: 5.15.116-1-pve
- Virtualization: Proxmox LXC
- Clients: Browsers, AndroidTV
- Browser: Firefox, Edge, Chromium, etc.
- FFmpeg Version: 5.1.3-Jellyfin
- Playback Method:
- Hardware Acceleration: VAAPI
- GPU Model: i7-4790
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anthonylavado-kxs** [comment]
Possibly related to #6527, which reportedly has a fix in #10323, which would be part of a 10.9 release.

**Comment by Moonbase59** [comment]
Hm. Have read that rather often, let’s hope 10.9 really fixes that many issues and will eventually be released…

**Comment by anthonylavado** [comment]
Possibly related to #6527, which reportedly has a fix in #10323, which would be part of a 10.9 release.

**Comment by anthonylavado** [comment]
I should add that only the part where channels are "missing" is what's fixed if the condition is that they have the same tvg-id. It does not separate Radio/TV, since the function really is just "Live TV" at the moment. Adding a radio function would be a [feature request](https://features.jellyfin.org/).

**Comment by alanmilinovic** [comment]
Any news?

**Comment by felix920506** [comment]
Thanks for your confirmation. Closing this as completed. If the issue reappears please open a new issue and reference this one.
