### ISSUE TITLE
[Issue]: Calling DELETE /Users/{user_id}/PlayingItems/{item_id}/?positionTicks=8470000000 does nothing.

### ISSUE THREAD

**Issue by arabcoders** [jellyfin/jellyfin#10567]
### Please describe your bug

Using https://api.jellyfin.org/#tag/Playstate/operation/OnPlaybackStopped as reference, the API supposed to record user item play progress if `positionTicks` was supplied, However in reality it doesn't do anything and only issue the event. 

For example, choose any item in your database and try calling

```bash
$ curl -v -X DELETE 'http://localhost:8096/Users/{user_id}/PlayingItems/{item_id}?positionTicks=8470000000&ApiKey={api_id}'
```
you will get something like 

```bash
< HTTP/2 204
< alt-svc: h3=":443"; ma=2592000
< date: Sat, 11 Nov 2023 13:48:30 GMT
< server: Kestrel
< x-response-time-ms: 1
```

Which indicates that the API understood and accepted the request. However, nothing is actually done, and no progress has changed. As you can see from the attached photo. 

What i expect to happen is that jellyfin's API change the user positionTicks to that reported one at least according to the API docs. I work on WatchState tool which manage user watch state and progress and i managed to make it work for both emby and plex. Sadly, jellyfin proven to be a bit difficult to update user play progress, And i tried all the endpoints which deals with positionTick and non of them works as expected. 

Anyway i traced the codepath to this method 

https://github.com/jellyfin/jellyfin/blob/88873b6e9eedd1b600bd17c56ee66109d2ef566d/Emby.Server.Implementations/Session/SessionManager.cs#L911-L1019

I am not C# experienced dev it seems there is the code issue an event which leads to this code

https://github.com/jellyfin/jellyfin/blob/88873b6e9eedd1b600bd17c56ee66109d2ef566d/Jellyfin.Server.Implementations/Events/Consumers/Session/PlaybackStopLogger.cs#L39-L81

Reading this code, there is no mention of using the positionTicks, and it seems to only update the ActivityLog.

### Jellyfin Version

10.8.z

### Environment

```markdown
- Virtualization: linuxserver/jellyfin docker container.
```

### Jellyfin logs

```shell
[16:50:15] [INF] [42] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app Syncer 10.8.12 playing Night Family. Stopped at 847000 ms
```

### Please attach any screenshots here

![image](https://github.com/jellyfin/jellyfin/assets/1621552/77810552-bd5d-488f-99bb-e920a4c0400a)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ArabCoders** [comment]
Stepping thru the debugger, it seems the problem relates to sessions and being the request is remote and no session exists, the code tries to generate a session for it, however, while stepping thru the debugger the call for getUsers is returning empty list.

https://github.com/jellyfin/jellyfin/blob/a173d01139357c5913d3293cfb4c6c53019fbed0/Emby.Server.Implementations/Session/SessionManager.cs#L966C1-L967C1


I was not able to test master branch as it has another bug or problem when calling the API `Guid cannot be empty (something "id")` or something sadly i closed my terminal which is weird as i have the same code working for 1.8.z
