### ISSUE TITLE
[Issue]: Folder matching compatibility with other media servers, support "{tmdb-123456}"

### ISSUE THREAD

**Issue by Motophan** [jellyfin/jellyfin#10565]
### Please describe your bug

Right now if you want plex and jellyfin to have force matching you need to name your titles in akward ways

`../movies/Movie Name (2009) {tmdb-123456}`
wont work
`../movies/Movie Name (2009) [tmdb-123456]`
wont work
`../movies/Movie Name (2009) {tmdbid-123456}`
wont work

You need to do some sillyness

`../movies/Movie Name (2009) {tmdb-123456} [tmdbid-123456]`

Can this get patched?
https://github.com/jellyfin/jellyfin/blob/44b771bfb4b6412360b18c80621c90902c0a43a7/tests/Jellyfin.Server.Implementations.Tests/Library/PathExtensionsTests.cs#L28

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS:
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sevenrats** [comment]
its better to just not do this.  place an nfo file inside the directory and both programs will "force match" on the nfo.  generally speaking, these tmdb flags don't really improve anything in jellyfin-land.  I'm going to close this feature request, as it does not belong on the bug tracker. feel free to reopen it at features.jellyfin.org
