### ISSUE TITLE
Reseting an admin users password clears ALL user passwords

### ISSUE THREAD

**Issue by Mountaineer1024** [jellyfin/jellyfin#1057]
**Describe the bug**
If you use the "Forgot Password" functionality on an admin user, ALL users on the server have their passwords blanked (so login can be achieved by simply clicking on a user tile.

**To Reproduce**
1. Go to 'http://ServerIP:8096/web/index.html#!/forgotpassword.html'
2. Enter admin username and hit Submit
3. Read the pin from /config/passwordreset.txt and enter it into 'http://ServerIP:8096/web/index.html#!/forgotpasswordpin.html'
4. All user passwords are blanked

**Expected behavior**
Only the specified user should have their password reset.
Non admin users should send a message to the admins, requesting assistance.

**Logs**
Nothing relevant.

**Screenshots**
![screenshot from 2019-03-08 00-48-37](https://user-images.githubusercontent.com/3783142/53964225-d2af6a80-413e-11e9-8c44-62fdb926a785.jpg)

**System (please complete the following information):**
 - Xubuntu 18.10 desktop, Docker-CE hosting
 - Browser: Chrome
 - Jellyfin Version: 10.2.1

**Comment by LogicalPhallacy** [comment]
Fixed in #1149
