### ISSUE TITLE
[Issue]: Other User have ability to delete Media

### ISSUE THREAD

**Issue by amtra** [jellyfin/jellyfin#10577]
### Please describe your bug

I have created 2 Profiles
1. Admin (Have permission to manage Server)
2. Guest (No Permission to manage Server)

From Guest Profile i can delete media files directly which is not supposed to do with non admin profiles.

![Screenshot_20231114-053545_Jellyfin](https://github.com/jellyfin/jellyfin/assets/9961395/bbf0b34d-a402-4aab-a230-5952b95947a2)
![Screenshot_20231114-053548_Jellyfin](https://github.com/jellyfin/jellyfin/assets/9961395/cde4673b-87fd-4596-9bec-e4cba13656a4)

### Jellyfin Version

10.8.z

### if other:

10.8.12

### Environment

```markdown
- OS: Windows 11
- Clients: Jellyfin for Android
- Browser: Chrome 119
- FFmpeg Version:
- Playback Method:Direct Play
- Hardware Acceleration: None
- GPU Model: RTX 3060Ti
- Networking: Local
- Storage: Local
```

### Please attach any screenshots here

![Screenshot_20231114-053545_Jellyfin](https://github.com/jellyfin/jellyfin/assets/9961395/8eba6485-e90a-42d7-b384-de133ea84100)
![Screenshot_20231114-053548_Jellyfin](https://github.com/jellyfin/jellyfin/assets/9961395/9379e618-10a9-45b5-9eb4-6a44d7a813a7)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
Does the "Guest" user have anything enabled under "Allow media deletion from"

**Comment by amtra** [comment]
I check twice and there is no option shown as you mentioned

**Comment by Shadowghost** [comment]
As admin you need to click on the user in the admin dashboard and check the permissions

**Comment by amtra** [comment]
Can u please specify exactly where to lookup. I have checked all user settings as admin and can't find any relevant settings for the above issue

**Comment by DaftFuzz** [comment]
Dashboard > Users > select your "Guest" user. In the Profile section, scroll down to "Allow media deletion from:" and make sure **all** libraries are unticked

![image](https://github.com/jellyfin/jellyfin/assets/35006874/20c6e832-c8e3-4ad8-b8df-dc2748dce581)

**Comment by amtra** [comment]
Yes. After Restarting Server it is showing more options, and finally i can disable this thankyou for your response. Im closing this issue here.

Thank You
