### ISSUE TITLE
[Issue]: Libary Permission Bypass

### ISSUE THREAD

**Issue by DefinitivLegit** [jellyfin/jellyfin#10571]
### Please describe your bug

When a user got no permission for any library, he can access any movie by just simply searching for it.
Found bug thanks to @fischboy1337

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Linux Ubuntu 22.04.3 LTS
- Linux Kernel: GNU/Linux 5.15.0-88-generic x86_64
- Virtualization: kvm
- Clients: Any
- Browser: Any
- FFmpeg Version: 5.1.3-Jellyfin
- Playback Method: Transcode
- Hardware Acceleration: NVENC
- GPU Model: NVIDIA Quadro P2200
- Plugins: AudioDB, MusicBrainz, OMDb, Playback Reporting, Reports, Studio Images, TMDb
- Reverse Proxy: https://github.com/fatedier/frp
- Base URL: none
- Networking: Host
- Storage: NAS CIFS mount
```

### Please attach any screenshots here

https://streamable.com/01exmp

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by cvium** [comment]
Likely fixed by https://github.com/jellyfin/jellyfin/pull/8526
