### ISSUE TITLE
[unstable -> stable] when the version 10.9 version will come into stable?

### ISSUE THREAD

**Issue by Reaster0** [jellyfin/jellyfin#10572]
hey all,  thanks for your amazing work before everything else!

for a while i was running the unstable version (docker) (because there was a bug unpatched in the stable version for a while that made my server launch an infinite number of threads and lock the system)
but well, the unstable version is... unstable,
so i'm wondering, when could i switch back to the stable version? i suppose when the 10.9 will come out in stable? because i suppose theres more db migration between major releases than in between?
i'm sure there's a time window in which i could do the switch, 
or maybe you have a magic way of doing it?

**Comment by Reaster0** [comment]
or at least, what are my migrations option if i ever wanna go back to the stable version and keep as much data as possible?

**Comment by crobibero** [comment]
There is no support for going from Unstable back to Stable. The only recommendation is to restore from backup.

**Comment by Reaster0** [comment]
what do you mean restore from backup? using the same data folder? it won't work because of the db schema difference
i'm currently trying https://github.com/Marc-Vieg/Emby2Jelly to see if it could do the trick

**Comment by Shadowghost** [comment]
Unstable includes Database migrations which are one-way. If you upgrade once, there is no way to roll them back, so your only way of going back from unstable to stable is to restore a backup of your data folders from before you moved to unstable.

**Comment by Bond-009** [comment]
While you can't go back to the current stable it should be possible to upgrade to version 10.9 when it releases.
This isn't guaranteed as there may be breaking changes in unstable while 10.9 is branched of in preparation for the release, but it's worth a shot.
If current unstable is working for you I'd stick with it until 10.9 releases (or keep up to date with unstable until 10.9 gets it's own branch)

**Comment by Reaster0** [comment]
the emby2Jellyfin script did not work as i would expect :/ well i've moved my users manually and i will run the two version until all would remake their watchlist to the stable version
