### ISSUE TITLE
Stream stutters/buffers when transcoding with Intel QuickSync

### ISSUE THREAD

**Issue by redhyper9** [jellyfin/jellyfin#10578]
**Media Info of the file**

Video
Title: 1080p H264 SDR
Codec: H264
AVC: Yes
Profile: High
Level: 41
Resolution: 1916x1080
Aspect ratio: 16:9
Interlaced: No
Framerate: 23.976025
Bitrate: 21837 kbps
Bit depth: 8 bit
Video range: SDR
Video range type: SDR
Pixel format: yuv420p
Ref frames: 1
NAL: 4

Audio
Title: Main Feature - English - DTS - 5.1 - Default
Language: eng
Codec: DTS
Profile: DTS
Layout: 5.1
Channels: 6 ch
Bitrate: 1536 kbps
Sample rate: 48000 Hz
Default: Yes
Forced: No
External: No

**FFmpeg Logs**
https://pastebin.com/raw/qSngarCi

**Stats for Nerds Screenshots**
https://i.imgur.com/Ytsxj68.png

**Server System (please complete the following information):**
 - OS: Linux, Debian 12
 - Jellyfin Version: 10.8.12
 - Hardware settings & device: Intel Quick Sync on i9 9900k
 - Reverse proxy: None
 - Other hardware notes: None, media is being stored on local hard drive
 
**Client System (please complete the following information):**
 - Device: Laptop
 - OS: Windows
 - Client: Browser
 - Browser: Chrome
 - Client and Browser Version: 119.0.6045.124

When I'm not using any hardware acceleration the stream doesn't stutter/buffer so I think the issue is related to hardware acceleration.

**Comment by felix920506** [comment]
Hi, what is the storage device you are using for the transcodes folder? Is it in any sort of array?

**Comment by redhyper9** [comment]
> Hi, what is the storage device you are using for the transcodes folder? Is it in any sort of array?

Hi, it's the same device that's also used for media, 2 HDDs in RAID0.

**Comment by felix920506** [comment]
@redhyper9 Can you provide the exact model of the drives?

**Comment by redhyper9** [comment]
@felix920506 Sure, `HGST HUH721010AL`

**Comment by felix920506** [comment]
Are you using any sort of virtualization?

**Comment by redhyper9** [comment]
No, it's bare metal.
