### ISSUE TITLE
[Issue]: Jellyfin does not recognize my login details and won't let me reset Password 

### ISSUE THREAD

**Issue by WilliamBjerglund** [jellyfin/jellyfin#10583]
### Please describe your bug

Hello, i ran into a problem where Jellyfin after resetting my Windows machine because of updates just won't recognize my login details. 
I know it's an issue with Jellyfin because i wrote my login down in my Password Manager.
Afterwards i tried using the reset password however it won't let me do that either as shown in the images:
in the first image it shows what happens when i try to login translated it says "Unknown username or password. Try again."
In the second image it shows what happens when trying to reset the password and it says "Please try again inside your home network to initiate your password reset."

Now my network has not been changed since making my Jellyfin server and i am using a wired connection so i find it hard to believe that is the problem i am just hosting the server on a localhost as shown in image 3.

Has anyone got any ideas i can try or possibly a way to fix this issue / bug?

### Jellyfin Version

10.8.9

### Environment

```markdown
- OS: Windows 10
- Virtualization: None
- Clients: Browser
- Browser: Firefox / rarely Chrome
- FFmpeg Version: 5.1.3-Jellyfin
- Hardware Acceleration: none
- GPU Model: GTX 1060 6GB
- Plugins: None
- Reverse Proxy: None
- Networking: Host
- Storage: Local
```

### Please attach any browser or client logs here

![image](https://github.com/jellyfin/jellyfin/assets/33435986/ba4405aa-9b47-4767-b4d1-88eb45de76b1)

[log_20231114.log](https://github.com/jellyfin/jellyfin/files/13358506/log_20231114.log)
[log_20231115.log](https://github.com/jellyfin/jellyfin/files/13358507/log_20231115.log)
[log_20231115_001.log](https://github.com/jellyfin/jellyfin/files/13358508/log_20231115_001.log)

### Please attach any screenshots here

![Image 2](https://github.com/jellyfin/jellyfin/assets/33435986/d7c9ec57-d639-41e2-926f-fe1143d8c4e9)
![image 1](https://github.com/jellyfin/jellyfin/assets/33435986/4c29dc16-4c55-4b5f-b88a-91e92b0670e9)
![image](https://github.com/jellyfin/jellyfin/assets/33435986/713178a8-6ca4-42cc-a89f-0d2460a0eb14)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by WilliamBjerglund** [comment]
Issue revolving key recognition script over multiple HDD's

**Comment by MurtadhaInit** [comment]
I'm confused, how was this resolved? I've got the same exact issue 2 years later
