### ISSUE TITLE
Certain Disks in Multidisk albums cant have individual tracks selected

### ISSUE THREAD

**Issue by lunarised** [jellyfin/jellyfin#10596]
Very unusual bug. Disk 1 - 3 of a soundtrack im listening to will not play if you click on the individual tracks, but will play if you click on the album cover to play all tracks. You can skip through these tracks happily however. Disks 4 - 6 do not have this issue however

Copying the individual disks out into the root library directory allows regular playback, so i wonder if the issue is related to the client fetching the disk directory?

Directory Structure
/media/Music/FRANCHISE/GAME/CD[1-6]/foo.flac

**Media Info of the file**
Media information is consistent between not working and working runs

**Logs**
Google Chrome thrown error
GET https://example.com/jellyfin/Users/f457b7ed5ea347889cbd29f27108ea47/Items?Ids=|hexShorterned|&Limit=300&Fields=Chapters&ExcludeLocationTypes=Virtual&EnableTotalRecordCount=false&CollapseBoxSetItems=false net::ERR_CONNECTION_CLOSED
b @ main.jellyfin.bundle.js?ba0eba4f8e459eb7c494:2
value @ main.jellyfin.bundle.js?ba0eba4f8e459eb7c494:2
value @ main.jellyfin.bundle.js?ba0eba4f8e459eb7c494:2
value @ main.jellyfin.bundle.js?ba0eba4f8e459eb7c494:2
D @ main.jellyfin.bundle.js?ba0eba4f8e459eb7c494:2
l.play @ main.jellyfin.bundle.js?ba0eba4f8e459eb7c494:2
d @ main.jellyfin.bundle.js?ba0eba4f8e459eb7c494:2
h @ main.jellyfin.bundle.js?ba0eba4f8e459eb7c494:2
g @ main.jellyfin.bundle.js?ba0eba4f8e459eb7c494:2
bt @ main.jellyfin.bundle.js?ba0eba4f8e459eb7c494:2

Firefox Errors:
Requesting https://example.com/jellyfin/Users/f457b7ed5ea347889cbd29f27108ea47/Items?Ids=[Hex]Limit=300&Fields=Chapters&ExcludeLocationTypes=Virtual&EnableTotalRecordCount=false&CollapseBoxSetItems=false main.jellyfin.bundle.js:2:790958

Request failed to https://example.com/jellyfin/Users/f457b7ed5ea347889cbd29f27108ea47/Items?Ids=[HEX]&Limit=300&Fields=Chapters&ExcludeLocationTypes=Virtual&EnableTotalRecordCount=false&CollapseBoxSetItems=false TypeError: NetworkError when attempting to fetch resource. main.jellyfin.bundle.js:2:791338

Attempting reconnection main.jellyfin.bundle.js:2:791541

tryReconnect: http://192.168.0.180:8096/jellyfin|https://example.com/jellyfin main.jellyfin.bundle.js:2:837844
(this is the local IP of my server, which I am not on the network of)
getTryConnectPromise http://192.168.0.180:8096/jellyfin main.jellyfin.bundle.js:2:838032
Blocked loading mixed active content “http://192.168.0.180:8096/jellyfin/system/info/public”

**Server System (please complete the following information):**
 - OS: Ubuntu 22.04
 - Jellyfin Version:  10.8.9.0
 - Hardware settings & device: No transcode
 - Reverse proxy: nginx
 - Other hardware notes: Media on mdadm raid array
 
**Client System (please complete the following information):**
 - OS: Windows 10
 - Client:  Web/Browser
 - Browser (if Web client): Both
 - Client and Browser Version: Chrome:119.0, Firefox 119.0

 
Long time user, first time bug finder. I hope ive found something. Thanks all for your hard work! <3

**Comment by felix920506** [comment]
Hi, please test on web client master branch. https://github.com/jellyfin/jellyfin-web

**Comment by lunarised** [comment]
> Hi, please test on web client master branch. https://github.com/jellyfin/jellyfin-web

Hey Thanks! This issue since been resolved!
