### ISSUE TITLE
[Issue]: the images can't display at v10.9

### ISSUE THREAD

**Issue by eillel** [jellyfin/jellyfin#10597]
### Please describe your bug

the images can't display when I test the newest version 10.9 by using VS2022 and .net 8.0
And then, I debug it, change the Class PhotoResolver:
at: protected override Photo? Resolve(ItemResolveArgs args)
if (collectionType == CollectionType.Photos
    || (collectionType == CollectionType.HomeVideos && args.LibraryOptions.EnablePhotos))

modify to:

if (collectionType == CollectionType.Photos
    || (collectionType == CollectionType.HomeVideos || args.LibraryOptions.EnablePhotos))

Then the picture will be displayed normally.

### Jellyfin Version

Other

### Environment

```markdown
- OS:Win 10
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:Chrome 119
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 1337joe** [comment]
Since you already seem to be running it in the debugger, what is the actual runtime value of `collectionType` when it gets to the lines you highlighted?

**Comment by eillel** [comment]
collectionType is null
