### ISSUE TITLE
[Issue]: Too small ffmpeg parameters prevent normal parsing of high-definition live streams

### ISSUE THREAD

**Issue by 0xc0000142** [jellyfin/jellyfin#10601]
### Please describe your bug

My English is not very good so I used Google Translate

I have some live TV sources, and when I watch these live TV feeds, I find that the original resolution is only 640x360

(pic1)(pic2)

After analysis, I successfully located the problem in the analysis given to FFmpeg by Jellyfin during transcoding.

When watching live TV, the -analyzeduration parameter given to FFmpeg is too small, resulting in the inability to properly analyze the high-definition stream.

If this parameter is too small, FFmpeg cannot correctly obtain high-definition stream information.

(pic3)

After discovering the problem, I tried to use the environment variable JELLYFIN_FFmpeg__analyzeduration="50M" in /etc/default/jellyfin to fix the problem, but the environment variable did not take effect on the live TV broadcast. It took effect everywhere except the live TV broadcast!

(pic4)

I tried to describe my problem in as much detail as possible, if some necessary information is still missing, please let me know and I will add what is needed

### Jellyfin Version

10.8.z

### if other:

10.8.12

### Environment

```markdown
- OS:Debian 12
- Linux Kernel:Linux 6.2.16-6-pve #1 SMP PREEMPT_DYNAMIC PMX 6.2.16-7 (2023-08-01T11:23Z)
- Virtualization:LXC 
- Clients:Chromium 102.0.5005.167
- Browser:Cent Browser	5.0.1002.354 (正式版本) （64 位） (Chromium 102.0.5005.167)
- FFmpeg Version:5.1.3
- Playback Method:Transcode
- Hardware Acceleration:NVENC
- GPU Model:Nvidia Tesla P4
- Plugins:Session Cleaner 2.0.0.0 TMDb 10.8.12.0  Studio Images 10.8.12.0 OMDb 10.8.12.0 MusicBrainz 10.8.12.0 AudioDB 10.8.12.0
- Reverse Proxy:nginx
- Base URL:none
- Networking:Bridge
- Storage:NFS
```

### Jellyfin logs

[jellyfin20231119.log](https://github.com/jellyfin/jellyfin/files/13401987/jellyfin20231119.log)

### FFmpeg logs

[FFmpeg.Transcode-2023-11-19_02-46-21_9939694234c829c769fce2c326d50769_5f0d5b9d.log](https://github.com/jellyfin/jellyfin/files/13401988/FFmpeg.Transcode-2023-11-19_02-46-21_9939694234c829c769fce2c326d50769_5f0d5b9d.log)

### Please attach any browser or client logs here

![image](https://github.com/jellyfin/jellyfin/assets/52188337/278c7904-f012-4756-863d-3c53c41fbee1)

### Please attach any screenshots here

![image](https://github.com/jellyfin/jellyfin/assets/52188337/b123e9a0-3b84-4483-b981-d60a28c29d1a)

![Source information](https://github.com/jellyfin/jellyfin/assets/52188337/79500160-938d-4c12-9e37-0be1fe9e0e88)

![image](https://github.com/jellyfin/jellyfin/assets/52188337/51221a67-1a4e-4c7b-bb9c-48ee8ee5d214)

![/etc/default/jellyfin](https://github.com/jellyfin/jellyfin/assets/52188337/1afa3580-1c40-4c65-b461-7912b770465d)

(Watch FFmpeg logs of live TV after setting variables)

![image](https://github.com/jellyfin/jellyfin/assets/52188337/f8dca7e4-66be-46db-af06-140663791716)

(Watch FFmpeg logs of Movie after setting variables)

![image](https://github.com/jellyfin/jellyfin/assets/52188337/e250b9ea-c4c6-4d85-9771-6481dd2e1a6d)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
Hi, please upload the logs as .log or .txt files to GitHub directly instead of using pastebin.
