### ISSUE TITLE
.avi-files won't play

### ISSUE THREAD

**Issue by Sjoerd** [jellyfin/jellyfin#10602]
**Media Info of the file**

General
Complete name                            : \\192.168.1.30\Entertainment\Series\Flodder\Seizoen 1\Aflevering 1 - Korte Metten.avi
Format                                   : AVI
Format/Info                              : Audio Video Interleave
Format settings                          : BitmapInfoHeader / WaveFormatEx
File size                                : 205 MiB
Duration                                 : 27 min 6 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 1 057 kb/s
Frame rate                               : 25.000 FPS
Writing application                      : VirtualDubMod 1.5.4.1 (build 2178/release)
Writing library                          : VirtualDubMod build 2178/release

Video
ID                                       : 0
Format                                   : MPEG-4 Visual
Format profile                           : Advanced Simple@L5
Format settings                          : BVOP1 / Custom Matrix
Format settings, BVOP                    : 1
Format settings, QPel                    : No
Format settings, GMC                     : No warppoints
Format settings, Matrix                  : Custom
Codec ID                                 : XVID
Codec ID/Hint                            : XviD
Duration                                 : 27 min 6 s
Bit rate                                 : 943 kb/s
Width                                    : 560 pixels
Height                                   : 320 pixels
Display aspect ratio                     : 16:9
Frame rate                               : 25.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Compression mode                         : Lossy
Bits/(Pixel*Frame)                       : 0.210
Stream size                              : 183 MiB (89%)
Writing library                          : XviD 1.1.0 (2005-11-22)

Audio
ID                                       : 1
Format                                   : MPEG Audio
Format version                           : Version 1
Format profile                           : Layer 3
Format settings                          : Joint stereo
Codec ID                                 : 55
Codec ID/Hint                            : MP3
Duration                                 : 27 min 6 s
Bit rate mode                            : Variable
Bit rate                                 : 101 kb/s
Nominal bit rate                         : 112 kb/s
Channel(s)                               : 2 channels
Sampling rate                            : 44.1 kHz
Frame rate                               : 38.281 FPS (1152 SPF)
Compression mode                         : Lossy
Delay relative to video                  : 78 ms
Stream size                              : 19.6 MiB (10%)
Alignment                                : Split across interleaves
Interleave, duration                     : 26  ms (0.65 video frame)
Interleave, preload duration             : 764  ms
Writing library                          : LAME3.97b
Encoding settings                        : -m j -V 4 -q 2 -lowpass 15.6 --abr 112

**Logs**

> [2023-11-18 11:50:48.216 +00:00] [INF] User policy for "Sjoerd". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
> [2023-11-18 11:50:48.217 +00:00] [INF] StreamBuilder.BuildVideoItem( Profile="Anonymous Profile", Path="/mnt/content/Series/Flodder/Seizoen 5/Aflevering 1 - 1 April.avi", AudioStreamIndex=1, SubtitleStreamIndex=-1 ) => ( PlayMethod=Transcode, TranscodeReason=ContainerNotSupported, VideoCodecNotSupported, AudioCodecNotSupported ) "media:/videos/2cce2c5e-e224-df10-5c78-c9fe380e188e/master.m3u8?MediaSourceId=2cce2c5ee224df105c78c9fe380e188e&VideoCodec=h264&AudioCodec=mp3&AudioStreamIndex=1&VideoBitrate=139900776&AudioBitrate=99224&AudioSampleRate=44100&MaxFramerate=25&api_key=<token>&SubtitleMethod=Encode&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=5fe261a0285983b476df0e1b072470e8&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&mpeg4-level=5&mpeg4-videobitdepth=8&mpeg4-profile=advancedsimpleprofile&mpeg4-audiochannels=2&TranscodeReasons=ContainerNotSupported,%20VideoCodecNotSupported,%20AudioCodecNotSupported"
> [2023-11-18 11:50:48.227 +00:00] [INF] Deleting partial stream file(s) "/var/lib/jellyfin/transcodes/29e14caa19f98e0931e9eaec10583e8b.m3u8"
> [2023-11-18 11:50:48.262 +00:00] [INF] Current HLS implementation doesn't support non-keyframe breaks but one is requested, ignoring that request
> [2023-11-18 11:50:48.262 +00:00] [INF] "/usr/lib/jellyfin-ffmpeg/ffmpeg" "-analyzeduration 200M -init_hw_device vaapi=va:/dev/dri/renderD128,driver=iHD -filter_hw_device va -autorotate 0 -i file:\"/mnt/content/Series/Flodder/Seizoen 5/Aflevering 1 - 1 April.avi\" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_vaapi -rc_mode VBR -b:v 5953096 -maxrate 5953096 -bufsize 11906192 -force_key_frames:0 \"expr:gte(t,0+n_forced*3)\" -vf \"setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale=trunc(min(max(iw\,ih*a)\,min(608\,352*a))/2)*2:trunc(min(max(iw/a\,ih)\,min(608/a\,352))/2)*2,format=nv12,hwupload=derive_device=vaapi\" -codec:a:0 libmp3lame -ac 2 -ab 99224 -ar 44100 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_segment_filename \"/var/lib/jellyfin/transcodes/906a17043a57b453d98baa4ddc1cf919%d.ts\" -hls_playlist_type vod -hls_list_size 0 -y \"/var/lib/jellyfin/transcodes/906a17043a57b453d98baa4ddc1cf919.m3u8\""
> [2023-11-18 11:50:48.295 +00:00] [ERR] FFmpeg exited with code 1
> [2023-11-18 11:50:48.376 +00:00] [ERR] Error processing request. URL "GET" "/videos/2cce2c5e-e224-df10-5c78-c9fe380e188e/hls1/main/0.ts".
> MediaBrowser.Common.FfmpegException: FFmpeg exited with code 1
>    at Jellyfin.Api.Helpers.TranscodingJobHelper.StartFfMpeg(StreamState state, String outputPath, String commandLineArguments, HttpRequest request, TranscodingJobType transcodingJobType, CancellationTokenSource cancellationTokenSource, String workingDirectory)
>    at Jellyfin.Api.Controllers.DynamicHlsController.GetDynamicSegment(StreamingRequestDto streamingRequest, Int32 segmentId)
>    at Jellyfin.Api.Controllers.DynamicHlsController.GetHlsVideoSegment(Guid itemId, String playlistId, Int32 segmentId, String container, Int64 runtimeTicks, Int64 actualSegmentLengthTicks, Nullable`1 static, String params, String tag, String deviceProfileId, String playSessionId, String segmentContainer, Nullable`1 segmentLength, Nullable`1 minSegments, String mediaSourceId, String deviceId, String audioCodec, Nullable`1 enableAutoStreamCopy, Nullable`1 allowVideoStreamCopy, Nullable`1 allowAudioStreamCopy, Nullable`1 breakOnNonKeyFrames, Nullable`1 audioSampleRate, Nullable`1 maxAudioBitDepth, Nullable`1 audioBitRate, Nullable`1 audioChannels, Nullable`1 maxAudioChannels, String profile, String level, Nullable`1 framerate, Nullable`1 maxFramerate, Nullable`1 copyTimestamps, Nullable`1 startTimeTicks, Nullable`1 width, Nullable`1 height, Nullable`1 maxWidth, Nullable`1 maxHeight, Nullable`1 videoBitRate, Nullable`1 subtitleStreamIndex, Nullable`1 subtitleMethod, Nullable`1 maxRefFrames, Nullable`1 maxVideoBitDepth, Nullable`1 requireAvc, Nullable`1 deInterlace, Nullable`1 requireNonAnamorphic, Nullable`1 transcodingMaxAudioChannels, Nullable`1 cpuCoreLimit, String liveStreamId, Nullable`1 enableMpegtsM2TsMode, String videoCodec, String subtitleCodec, String transcodeReasons, Nullable`1 audioStreamIndex, Nullable`1 videoStreamIndex, Nullable`1 context, Dictionary`2 streamOptions)
>    at lambda_method999(Closure , Object )
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
>    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
>    at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
>    at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
>    at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
>    at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
>    at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
>    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
>    at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
>    at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
>    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
>    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
>    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
>    at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
>    at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
>    at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
>    at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
>    at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
> [2023-11-18 11:50:48.389 +00:00] [INF] Deleting partial stream file(s) "/var/lib/jellyfin/transcodes/906a17043a57b453d98baa4ddc1cf919.m3u8"
> [2023-11-18 11:50:49.890 +00:00] [INF] Playback stopped reported by app "Jellyfin Web" "10.8.12" playing "Aflevering 1 - 1 April". Stopped at "0" ms
> [2023-11-18 11:50:49.914 +00:00] [WRN] Slow HTTP Response from "http://192.168.1.33:8096/Sessions/Playing/Stopped" to "192.168.1.214" in 0:00:01.5277013 with Status Code 204

**FFmpeg Logs**

> ffmpeg version 5.1.3-Jellyfin Copyright (c) 2000-2022 the FFmpeg developers
>   built with gcc 11 (Ubuntu 11.4.0-1ubuntu1~22.04)
>   configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-libs=-lfftw3f --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libsvtav1 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
>   libavutil      57. 28.100 / 57. 28.100
>   libavcodec     59. 37.100 / 59. 37.100
>   libavformat    59. 27.100 / 59. 27.100
>   libavdevice    59.  7.100 / 59.  7.100
>   libavfilter     8. 44.100 /  8. 44.100
>   libswscale      6.  7.100 /  6.  7.100
>   libswresample   4.  7.100 /  4.  7.100
>   libpostproc    56.  6.100 / 56.  6.100
> Input #0, avi, from 'file:/mnt/content/Series/Flodder/Seizoen 5/Aflevering 1 - 1 April.avi':
>   Metadata:
>     software        : VirtualDubMod 1.5.4.1 (build 2178/release)
>   Duration: 00:21:59.08, start: 0.000000, bitrate: 1302 kb/s
>   Stream #0:0: Video: mpeg4 (Advanced Simple Profile) (XVID / 0x44495658), yuv420p, 608x352 [SAR 1:1 DAR 19:11], 1190 kb/s, 25 fps, 25 tbr, 25 tbn
>   Stream #0:1: Audio: mp3 (U[0][0][0] / 0x0055), 44100 Hz, stereo, fltp, 99 kb/s
> Stream mapping:
>   Stream #0:0 -> #0:0 (mpeg4 (native) -> h264 (h264_vaapi))
>   Stream #0:1 -> #0:1 (mp3 (mp3float) -> mp3 (libmp3lame))
> Press [q] to stop, [?] for help
> [h264_vaapi @ 0x5566049677c0] Failed to create encode pipeline context: 2 (resource allocation failed).
> Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
> [libmp3lame @ 0x556604956200] 4 frames left in the queue on closing
> Conversion failed!

**Stats for Nerds Screenshots**

N/A

**Server System (please complete the following information):**
 - OS: Ubuntu
 - Jellyfin Version: [e.g. 10.0.1]
 - Hardware settings & device: VAAPI on Arc A380
 - Reverse proxy: None (localhost) and Cloudflared Tunnel
 - Other hardware notes: Media mounted from SMB share.
 
**Client System (please complete the following information):**
 - Device: Desktop & Smartphone (Galaxy S23+) 
 - OS: Windows 11 / Android 14
 - Client: Webbrowser / Android App
 - Browser (if Web client): Google Chrome 
 - Client and Browser Version: 119.0.6045.160 (Officiële build) (64-bits) (cohort: Stable) 
 
 **Playback settings:**
![image](https://github.com/jellyfin/jellyfin/assets/19862992/fbed4e76-1c10-46c8-a9e7-409243b1bb6d)
![image](https://github.com/jellyfin/jellyfin/assets/19862992/72d7526f-8180-42fd-bb93-2e8a43182d63)

**Comment by felix920506** [comment]
Hi, can you test with hardware acceleration disabled and see if it plays?

**Comment by solidsnake1298** [comment]
I was not able to duplicate.  Replicated your settings on my system.  I had some older media in an AVI container, Xvid codec, and MP3 audio.

Ubuntu 22.04.3 LTS w/HWE kernel
Intel i3 12100
Intel Arc A380

@Sjoerd If you are using Ubuntu 22.04, you need to install the HWE kernel with Arc GPUs.  You also should be using Quick Sync instead of VAAPI.

![image](https://github.com/jellyfin/jellyfin/assets/137357145/a0c5124e-ee9a-4263-a208-d9500cfb70d0)

**Comment by Sjoerd** [comment]
> Hi, can you provide the following:
> 
> 1. Does it work with Hardware Acceleration disabled
> 2. What is your OS? Also provide the distribution and kernel version if on Linux

I run Ubuntu 22.04 (I thought I added this to the issue, apologies) (`uname -r`: 6.2.0-36-generic)
It does work with Hardware Acceleration disabled.

**Comment by felix920506** [comment]
Can you also test QSV?

**Comment by sevenrats** [comment]
seems like a HWA configuration issue. shouldn't we close as support request?

**Comment by sevenrats** [comment]
Thanks for your report please stop by the chat space if you need support with your firmware.
