### ISSUE TITLE
[Issue]: Showstopper problem: Jellyfin server lets the computer it is running on go to sleep during playback

### ISSUE THREAD

**Issue by msimic** [jellyfin/jellyfin#10618]
### Please describe your bug

Jellyfin server is running and playing video to webos client.
The OS on the server is configured to go to sleep after 15 minutes.
During playback the computer that is running the server goes to sleep interrupting the playback on the webos client.

This should obviously not happen.
Jellyfin should keep the computer from going to sleep whenever there is a playback active (how Youtube does).
Afterwards, where there is no playback active it can go to sleep (and be woken back up by WoL for the next playback).

Carbon neutrality should be the goal :)

I'm not sure if it does the same on Linux but if yes, i believe it can be prevented with dbus and sending the apropriate message, but on Windows this would be to way to achieve it using PInvoke through .Net:

You can use SetThreadExecutionState function with ES_SYSTEM_REQUIRED to prevent a computer from entering Sleep/Standby/Hibernate while retaining the ability to turn of the screen. This should be done periodically while a streaming/transcoding process is active or with the additional ES_CONTINUOUS at the beginning and end of playback if periodical is not wanted (but I would advise against it, because of possible stale streams or similar problems - sending one periodical every 5 minutes would be enough. Additionaly i'm not sure if ES_CONTINUOUS  will allow the screen to turn off).

### Jellyfin Version

10.8.9

### Environment

```markdown
- OS: Windows 11
- Clients: webos
- Playback Method: DirectPlay
- Hardware Acceleration: NVDEC/NVENC
- GPU Model: GTX 1050
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by acidstout** [comment]
I think there's a misunderstanding here. And obviously a misconfiguration on the server side.

Clients are and should be configured by default to go to sleep whenever there's nothing running which requires attention. When playing a Youtube video in the Youtube app or in the browser on the client, the app tells the client to not go to sleep.

The Youtube servers are running always. They will never go to sleep and that's because servers have one single purpose: Availability of service. Nothing else.

If you run a server and configure it to go to sleep after some time, it will of course do so. And that's obviously a misconfiguration, because availability of service cannot be ensured.

From an end-user perspective this maybe desirable. But from a technical perspective this is not what a server is meant and made for.

Also this is not a bug, but rather a feature request.

**Comment by msimic** [comment]
Considering Jellyfin servers are often home/desktop PCs having them go to sleep after some time is desirable behavior.
A mixed usage scenario is encountered quite often for Jellyfin.
However even in a case of a pure server what you wrote is not entierely accurate.
There exists servers with high availability and there exist servers with other purposes that can be put to sleep and woken when needed which is why the suggested method works on microsoft server OSes as well.
You are right that this is a feature request tho.

**Comment by Bond-009** [comment]
This is a feature request, not a bug
https://features.jellyfin.org/posts/581/prevent-os-from-sleeping-hibernating-while-streaming
Also, I doubt this will get implemented in the server, maybe as a plugin (like this one https://github.com/jonschz/jellyfin-plugin-preventsleep)

**Comment by msimic** [comment]
> Also, I doubt this will get implemented in the server

It is sad to hear that users need to jump hoops to care about carbon emissions.
A feature that does this is:

a) easy to implement
b) does not harm any functionality when doing so by default

**Comment by Bond-009** [comment]
It may get included in the windows tray app https://github.com/jellyfin/jellyfin-server-windows/issues/78
But it doesn't make sense to include it in Jellyfin Server as it's intended to run on well ... *servers* not your desktop

**Comment by msimic** [comment]
Bond, there are two misconceptions in your thinking.
Neither is Jellyfin running only on servers, and neither are servers
required to be high availability servers. they can be put to sleep and
woken up. It just needs to be supported by what is running on them.
Jellyfin doesn't, at least for all the OSes. For Windows there is a plugin
that uses the microsoft way of doing that. But for linux and Mac there is
nothing (dbus support).
