### ISSUE TITLE
[Issue]: Filtering Sessions by activeWithinSeconds is not working

### ISSUE THREAD

**Issue by Morikko** [jellyfin/jellyfin#10610]
### Please describe your bug

Steps to reproduce: 
1. `curl 'http://localhost:8096/Sessions?activeWithinSeconds=3600'`
2. Even sessions with `LastActivityDate` older than 3600 seconds are returned

According to [the code](https://github.com/jellyfin/jellyfin/blob/v10.8.10/Jellyfin.Api/Controllers/SessionController.cs#L65C13-L65C13), the application of `activeWithinSeconds` is within the `controllableByUserId` branch.

Is it on purpose to not filter by `activeWithinSeconds` without `controllableByUserId` ?

### Jellyfin Version

10.8.z

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
Was able to reproduce on master, thanks for the report.
