### ISSUE TITLE
[Issue]: Sorting does not apply in audiobook subfolders

### ISSUE THREAD

**Issue by marius-luca-87** [jellyfin/jellyfin#10629]
### Please describe your bug

Sorting does not get applied for audio books that follow the path conventions described at https://jellyfin.org/docs/general/server/media/books .

Ex of Audiobooks library:
Audiobooks\Author Name\Book Name - 01\cover.jpg
Audiobooks\Author Name\Book Name - 01\Book Name - 01.m4b
Audiobooks\Author Name\Book Name - 02\cover.jpg
Audiobooks\Author Name\Book Name - 02\Book Name - 02.m4b
Audiobooks\Author Name\Book Name - 03\cover.jpg
Audiobooks\Author Name\Book Name - 03\Book Name - 03.m4b
Audiobooks\Author Name\Book Name - 04\cover.jpg
Audiobooks\Author Name\Book Name - 04\Book Name - 04.m4b

When browsing the library the author names get sorted but once entering the folder of any author the book names are displayed in a random order.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Fedora 39
- Linux Kernel: -
- Virtualization: Docker
- Clients: Browser
- Browser: Firefox 120.0
- FFmpeg Version: -
- Playback Method: -
- Hardware Acceleration: -
- GPU Model: -
- Plugins:-
- Reverse Proxy:-
- Base URL:-
- Networking:-
- Storage:-
```

### Please attach any screenshots here

![image](https://github.com/jellyfin/jellyfin/assets/7069165/975d8066-4d04-4365-820e-71c77c3a58a5)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marius-luca-87** [comment]
In case somebody is interested in picking up the investigation I tried looking a bit a while back when I had some free time and traced the problem to MediaBrowser.Controller\Entities\Folder.cs GetChildren that gets invoked with a null query losing any sort parameters provided by the web interface.

**Comment by sevenrats** [comment]
what happens if you select "Sort by name" instead of "sort by folder"

**Comment by marius-luca-87** [comment]
The sort parameter is completely ignored in that case.

**Comment by rosenbjerg** [comment]
This bug is quite frustrating. Any chance it will get fixed anytime soon?
