### ISSUE TITLE
[Issue]: ".pl.hi.srt" file detected as "pl - Hindi - SUBRIP - External"

### ISSUE THREAD

**Issue by m00nwtchr** [jellyfin/jellyfin#10638]
### Please describe your bug

External subtitles with a ".pl.hi.srt" extension are detected as "pl - Hindi - SUBRIP - External" instead of Polish + hearing impaired

### Jellyfin Version

10.8.z

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 1337joe** [comment]
This feature was merged after 10.8 was released (#7379). It works on unstable (master branch) but is not included in 10.8.
