### ISSUE TITLE
[Issue]: Unable to prevent Jellyfin scraping for 'People'

### ISSUE THREAD

**Issue by rosystain** [jellyfin/jellyfin#10632]
### Please describe your bug

I'm accustomed to using my own tools to generate NFO files for managing metadata, so I don't need Jellyfin to scrape additional data for me.
So I thought as long as TMDB and OMDB are not enabled in the media library, it should be fine.
But I found Jellyfin always scrapes metadata for 'People', even if I haven't enabled these information sources.
Moreover, the results it scrapes are often incorrect, especially when the actors or directors have CJK characters.
This has been quite frustrating for me, as I believe scraping for 'People' should also respect the metadata settings of the media library.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: 
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Please attach any screenshots here

Here is an example of matching to the wrong people.

```
<actor>
    <name>うんぱい</name>
</actor>
```
<img width="689" alt="Snipaste_2023-11-28_13-01-24" src="https://github.com/jellyfin/jellyfin/assets/27495128/0eed2aca-399b-4194-911a-565fd81d0bb1">
<img width="326" alt="Snipaste_2023-11-28_12-57-22" src="https://github.com/jellyfin/jellyfin/assets/27495128/e47dc464-cbdc-40df-b414-7dc190891e1b">
<img width="702" alt="Snipaste_2023-11-28_12-57-48" src="https://github.com/jellyfin/jellyfin/assets/27495128/eb013755-67c0-439f-973e-84ca519f93dc">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sevenrats** [comment]
Hi, thanks for your report.  This feature request is not a bug. Feel free to open a feature request at features.jellyfin.org.
