### ISSUE TITLE
[Issue]: Incorrect amount of episodes indicated for specific shows

### ISSUE THREAD

**Issue by OpetyrOrigin** [jellyfin/jellyfin#10645]
### Please describe your bug

So I have episodes of Bleach.  On the main page it states that there is only 2 episodes of Season 1 and Season 2 only has like 5.  Now when I open the specific season it sees all the episodes and even has the correct names for them.  This also then shows up as an issue with the total amount of episodes i.e. stating I have 338 instead of 366 episodes.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: TrueNasScale
- Linux Kernel:
- Virtualization:
- Clients:1
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
Hi, this does not look like an actual Jellyfin bug. Rather, it seems like you are trying to view your libraries while scanning hasn't completed yet. Please wait until scanning is complete for all files to be registered. If issues are still missing after scanning completes, please head to our chatrooms or forum for further support. https://jellyfin.org/contact
