### ISSUE TITLE
[Issue]: Jellyfin randomly stops working on a server

### ISSUE THREAD

**Issue by JarekDerp** [jellyfin/jellyfin#10640]
### Please describe your bug

I have a quite old terminal running Windows 11 and Jellyfin, among other apps.
From time to time (now everyday or sometimes even a couple times a day) the Jellyfin stops working. I need to log in into the server (this old terminal) and either restart Jellyfin or right-click and select "Start Jellyfin" in the tray.

I checked the log files and there's nothing in there. Like, it tells me I watched a movie yesterday and finished it and then nothing else, but the Jellyfin server is not running and none of the devices can connect to it.

Is there an obvious fix to it? Like something I have messed up in the settings? I don't even have any log files to paste because there's nothing there.
I always update to the latest version of Jellyfin, and I think it started to happen around version 10 or something

The terminal is quite old and the hardware doesn't have much support with Win11 but it still works. But for example Kodi failed to run due to drivers not being up-to-date or the video card not being able to display milions of colors - like it matters on the server.

### Jellyfin Version

10.8.z

### if other:

Up to date

### Environment

```markdown
- OS: Windows 11
- Clients: Server
- Hardware Acceleration: none
- GPU Model: none, AMD Radeon HD 8280E
- Plugins:AniDB7.0.0.0
AudioDB10.8.12.0
Fanart10.0.0.0
MusicBrainz10.8.12.0
OMDb10.8.12.0
Studio Images10.8.12.0
TMDb10.8.12.0
TheTVDB10.0.0.0
- Networking: Windows homegroup
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
Hi, please head t our chatrooms or forum for troubleshooting help. https://jellyfin.org/contact
If you believe there is an actual Jellyfin bug after troubleshooting with other community members, please reopen a new issue with more thorough documentation.
