### ISSUE TITLE
[Issue]: Navigation bars do not contain centered buttons such as "Suggestions", "Genres", "Artists", "Episodes", etc. depending on library type.

### ISSUE THREAD

**Issue by pokkst** [jellyfin/jellyfin#10658]
### Please describe your bug

After updating my jellyfin-git install, the navigation bar does not have the usual centered buttons like "Suggestions", "Genres", "Episodes", etc. depending on library type. I think this might also be causing issues on clients like Finamp, as I can no longer see my Music library in Finamp, despite it existing on Web, same with Findroid and being unable to view any libraries at all. I'm just not sure if these issues are related to the missing center buttons. I was told to post this issue here though.

### Jellyfin Version

Other

### if other:

10.9.0

### Environment

```markdown
- OS: Linux (Manjaro)
- Linux Kernel: 6.1.63-1-MANJARO
- Virtualization:
- Clients: Android, Web, Roku, (maybe) Finamp and Findroid
- Browser: Firefox, Mullvad Browser, Tor Browser, Brave, Chrome
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy: Nginx
- Base URL:
- Networking:
- Storage:
```

### Please attach any screenshots here

![4](https://github.com/jellyfin/jellyfin/assets/47200567/7ea2b723-5756-4266-8bcc-dc201c91fd78)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by thornbill** [comment]
Should be fixed by https://github.com/jellyfin/jellyfin/pull/10702

**Comment by pokkst** [comment]
@thornbill This bug was reintroduced in a recent commit.

**Comment by felix920506** [comment]
@pokkst please open new issue reports.

**Comment by pokkst** [comment]
You could also just... reopen this issue.

**Comment by felix920506** [comment]
I have confirmed with devs and they say this is unlikely to be the same issue. If you believe this is the same issue, please provide the relevant documentation such as logs.

**Comment by pokkst** [comment]
![image](https://github.com/jellyfin/jellyfin/assets/47200567/ec142ef9-088d-461d-aeb5-ace6d5b388ac)

Here's your proof.

**Comment by pokkst** [comment]
Same exact issue I encountered before.
