### ISSUE TITLE
[Issue]: File "Created Time" reported wrongly on Linux even though "Birth Time" is supported

### ISSUE THREAD

**Issue by verybadsoldier** [jellyfin/jellyfin#10655]
### Please describe your bug

I configured Jellyfin to use created timestamp as timestamp for added timestamp to library. I noticed that Jellyfin is using the modified time instead. The same works correctly on Windows
I tracked it down to be a dotnet issue on Linux (reproduced on dotnet 6 & 7). Well, maybe it is not a real issue in dotnet, but maybe I just don't understand the reasons.

I wrote a simple demo to showcase this with dotnet:
```
FileInfo fi = new FileInfo("/tmp/mytestfile");
var created = fi.CreationTime;
var lastmodified = fi.LastWriteTime;

Console.WriteLine("Created: " + created.ToString());
Console.WriteLine("Modified: " + lastmodified.ToString());
```
Output is:
```
~/DotNetTest$ dotnet run
Created: 12/18/2015 01:30:09
Modified: 12/18/2015 01:30:09
```
I am aware that not all Linux filesystems do support a created time. But Ext4 which I am using is supporting it and using `stat` on the console does reveal the birth time:
```
/tmp$ stat mytestfile
  File: mytestfile
  Size: 0               Blocks: 0          IO Block: 4096   regular empty file
Device: 801h/2049d      Inode: 931410      Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2023-11-29 21:59:49.344278582 +0100
Modify: 2015-12-18 01:30:09.000000000 +0100
Change: 2023-11-29 22:00:43.786880711 +0100
 Birth: 2023-11-29 21:59:49.344278582 +0100
```
So even thought Birth is available, the dotnet program (and also Jellyfin) outputs the modified timestamp also for `CreationTime`.

Has anyone an idea if this is intended behavior? Looks to me like a bug, but in such a widespread framework in such a basic function, I am surely not the first one to notice it?

### Jellyfin Version

10.8.z

### if other:

10.8.13

### Environment

```markdown
- OS: Ubuntu 22.04
- Linux Kernel: 5.15.0-84-generic 
- Virtualization: Official Docker Image
- Storage: Ext4
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joshuaboniface** [comment]
I mean, if the bug (and indeed if it is a bug) is in the .NET framework, there's absolutely nothing we can do about it. From your examples it looks like the intended behaviour. If I had to guess, it's precisely to support filesystems that don't support ctime attributes (ext3 comes to mind), and Microsoft is just being abundantly cautious about supporting it.

Best you can do is report it upstream, or adjust your workflow.

**Comment by verybadsoldier** [comment]
I made a widget, mainly for personal fun, that improves Jellyfin's DateAdded handling. I also added a workaround so JF will be able to acquire a correct created timestamp (instead of modified timestamp). Similar to the workaround described here.

So, if anyone is also bothered by this, feel free to give it a try:
https://github.com/verybadsoldier/Jellyfin.Plugin.DateAddedAdvanced
