### ISSUE TITLE
[Issue]: Video Files with the word "Sample" in them do not show up in the Library

### ISSUE THREAD

**Issue by CDubs00** [jellyfin/jellyfin#10656]
### Please describe your bug

I had a few episodes oh TV shows not showing up in the library but the files were in the directory. All of them had the word "Sample" in the episode title. Once I changed "Sample" to "S@mple" those episodes showed up in the library on the next scan. 

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS:Linux
- Linux Kernel: 6.1.49 
- Virtualization: Docker
- Clients:All
- Browser:All
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
Hi, please show your EXACT folder structure and file names.

**Comment by mikesulsenti** [comment]
> Hi, please show your EXACT folder structure and file names.

I'm here to also confirm this happens with media files with `sample` in the filename. My exmaple here is after I added periods between the letters of `sample`

```
~ > l /library/tv/Lilo\ \&\ Stitch\ -\ The\ Series\ \(2003\)/Season\ 01        32s root@media 20:37:49
total 12G
drwxrwxr-x 3 mike     users     121 Nov 29 17:00  .
drwxrwxr-x 4 mike     users      16 Nov 24 15:35  ..
-rw-rw-rw- 1 mike     users     74K Nov  9 06:43 'Lilo and Stitch The Series S01E01 Richter - x265-10Bit-AAC-WEBDL-1080p-thumb.jpg'
-rw-rw-rw- 1 mike     users    390M Nov  9 02:03 'Lilo and Stitch The Series S01E01 Richter - x265-10Bit-AAC-WEBDL-1080p.mkv'
-rw-rw-rw- 1 mike     users    1.4K Nov 15 03:12 'Lilo and Stitch The Series S01E01 Richter - x265-10Bit-AAC-WEBDL-1080p.nfo'
```
. . .
```
-rw-rw-rw- 1 mike     users     18K Nov  9 06:43 'Lilo and Stitch The Series S01E33 HunkaHunka - x265-10Bit-AAC-WEBDL-1080p-thumb.jpg'
-rw-rw-rw- 1 mike     users    304M Nov  9 02:06 'Lilo and Stitch The Series S01E33 HunkaHunka - x265-10Bit-AAC-WEBDL-1080p.mkv'
-rw-rw-rw- 1 mike     users    1.3K Nov 15 03:12 'Lilo and Stitch The Series S01E33 HunkaHunka - x265-10Bit-AAC-WEBDL-1080p.nfo'
-rw-rw-rw- 1 mike     users     20K Nov  9 06:43 'Lilo and Stitch The Series S01E34 S.a.m.p.l.e - x265-10Bit-AAC-WEBDL-1080p-thumb.jpg'
-rw-rw-rw- 1 mike     users    280M Nov  9 02:06 'Lilo and Stitch The Series S01E34 S.a.m.p.l.e - x265-10Bit-AAC-WEBDL-1080p.mkv'
-rw-rw-rw- 1 mike     users    1.2K Nov 15 03:12 'Lilo and Stitch The Series S01E34 S.a.m.p.l.e- x265-10Bit-AAC-WEBDL-1080p.nfo'
-rw-rw-rw- 1 mike     users     16K Nov  9 06:43 'Lilo and Stitch The Series S01E35 Baby-Fier - x265-10Bit-AAC-WEBDL-1080p-thumb.jpg'
-rw-rw-rw- 1 mike     users    314M Nov  9 02:08 'Lilo and Stitch The Series S01E35 Baby-Fier - x265-10Bit-AAC-WEBDL-1080p.mkv'
-rw-rw-rw- 1 mike     users    1.3K Nov 15 03:12 'Lilo and Stitch The Series S01E35 Baby-Fier - x265-10Bit-AAC-WEBDL-1080p.nfo'
```

![lilo-stitch-sample](https://github.com/jellyfin/jellyfin/assets/8174608/aa2b7697-9204-46c2-9dbb-0216907d2130)

**Comment by CDubs00** [comment]
Folder Structure is:

Episode 2 does not show up 
  /TV Shows
        /Mrs. Fletcher (2019)
             /Season 1
                  /Mrs. Fletcher (2019) - S01E01 - Empty Best [WEBDL-1080p][EAC3 5.1][x265]-Silence.mkv
                   Mrs. Fletcher (2019) - S01E02 - Free Sample [WEBDL-1080p][EAC3 5.1][x265]-Silence.mkv
                   Mrs. Fletcher (2019) - S01E03 - Care Package [WEBDL-1080p][EAC3 5.1][x265]-Silence.mkv


Episode 2 does show up 
  /TV Shows
        /Mrs. Fletcher (2019)
             /Season 1
                  /Mrs. Fletcher (2019) - S01E01 - Empty Best [WEBDL-1080p][EAC3 5.1][x265]-Silence.mkv
                   Mrs. Fletcher (2019) - S01E02 - Free S@mple [WEBDL-1080p][EAC3 5.1][x265]-Silence.mkv
                   Mrs. Fletcher (2019) - S01E03 - Care Package [WEBDL-1080p][EAC3 5.1][x265]-Silence.mkv

**Comment by 1hitsong** [comment]
Isn't `sample` a special keyword for filenames? Does it also happen if instead of the word `sample` you use `trailer`?

![image](https://github.com/jellyfin/jellyfin/assets/3330318/66c0d750-9037-4cb2-a2d9-501051f93437)
https://jellyfin.org/docs/general/server/media/movies#file-name

**Comment by CDubs00** [comment]
> Isn't `sample` a special keyword for filenames? Does it also happen if instead of the word `sample` you use `trailer`?
> 
> ![image](https://private-user-images.githubusercontent.com/3330318/286934658-66c0d750-9037-4cb2-a2d9-501051f93437.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzNDk2NTAsIm5iZiI6MTcwMTM0OTM1MCwicGF0aCI6Ii8zMzMwMzE4LzI4NjkzNDY1OC02NmMwZDc1MC05MDM3LTRjYjItYTJkOS01MDEwNTFmOTM0MzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMzBUMTMwMjMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDFlN2IzN2JmZTViODUyMGZlOGExYzYwZGViZDRjZjliYWViZTQ2Y2FlZTA1MDUyYjUwZTE5NGRmZDM1YTA2MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.u2iz43tl9bZLsmeUctlUDGYHQr852ud15wdIWhAf8a8) https://jellyfin.org/docs/general/server/media/movies#file-name

Yep, it also happens with the word trailer. This makes sense but episode titles in the file name are a common practice. and the arrr stack automate this process. Maybe have it look for SxxExx and if that exists ignore "Sample" but if thats not feasible then maybe a --sample.mkv or --trailer.mp4 with no space would be wise to key off of? I know this isn't Plex, but that's were I came from and they didn't have this issue.

**Comment by sevenrats** [comment]
@TheMelmacian without checking the source code, its straightforward enough to not match on the series title, as this is implied by other parts of the structure (parent folder name).  the episode name is too random though, and, in many cases, its not appropriate to add the episode title for this reason.  just "Series Title S01E01.mkv" is more than enough for jellyfin.

**Comment by CDubs00** [comment]
> the episode name is too random though, and, in many cases, its not appropriate to add the episode title for this reason. just "Series Title S01E01.mkv" is more than enough for jellyfin.

I would disagree, title and other metadata is important and very common practice. Jellyfin might not need it to function but it’s important for other applications and ones that automate populating a lot of Jellyfin servers. Other media server software don’t seem to have this issue know what is a sample or trailer vs an episode with sample or trailer in the filename.

**Comment by TheMelmacian** [comment]
Possible ways to solve the problem:

- make an extra subfolder mandatory for season extras, so that everything in the main folder of the season is treated as episode
- names that contain any special keyword like _sample_, _extra_, _trailer_ etc. must be put into square brackets (does this already work?)
  - `[The Trailer Show] - S01E01 - [Extra Samples of Trailers].mkv` => IMHO looks ugly
- the keywords for extras must be put into square brackets:
  - `The Trailer Show - S01E01 - Extra Samples of Trailers.mkv` => episode
  - `The Trailer Show - S01E01 - Extra Samples of Trailers - [trailer].mkv` => extra of type trailer

**Comment by DaveM8686** [comment]
This should be reopened as no solution was ever found and I'm having the same issue. Very frustrating.
