### ISSUE TITLE
[Issue]: Timezone format change in 10.9.0 breaks some jellyfin clients

### ISSUE THREAD

**Issue by 24fpsDaVinci** [jellyfin/jellyfin#10661]
### Please describe your bug

jellyfin clients for apple tvOS cannot login due to a timezone format change:

Affected (known): Infuse, SwiftFin, MrMc

_Originally posted by @DaRealHansForSure in https://github.com/jellyfin/Swiftfin/issues/876#issuecomment-1833992269_

 I fixed it in my code with modifing Jellyfin, it seems that in 10.9.0 (or C# Version) the behaviour of DateTime in json changes.

In previous version there were always the "Zulu" Timezone, in 10.9.0. You have no Timezone information:

10.9:
![image](https://github.com/jellyfin/Swiftfin/assets/3436574/7e3e7baa-898b-4d24-b081-0a1b389bf613)

10.8;
![image](https://github.com/jellyfin/Swiftfin/assets/3436574/3d46dc38-4279-42f4-81e4-0c628cf1c7ac)

Just for your information, maybe you could add some "standard" parsing, when no Timezone is present.

### Jellyfin Version

Other

### if other:

10.9.0

### Environment

```markdown
- OS: tvOS
- Linux Kernel: all
- Virtualization:
- Clients: SwiftFin, MrMc, Infuse (known so far)
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nielsvanvelzen** [comment]
Both Jellyfin 10.8 and 10.9 use the ISO 8601-1:2019 standard with the formatting specified in [rfc3339 section 5.6](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6). The time zone may be omitted if unknown. While the formatting did change with 10.9 and we should investigate why that exactly happened the issue here is with Swiftfin or more specifically the [swift SDK](https://github.com/jellyfin/jellyfin-sdk-swift) being unable to parse this format.

**Comment by nielsvanvelzen** [comment]
It could be possible both our Swift SDK and Infuse use a platform function that doesn't properly support our DateTime format but I am not familiar with Apple platforms/languages so I can't say what exactly is causing the issue. I can say that all other platforms (web/android/kodi/roku etc.) did not receive any reports of this problem.

**Comment by cmtonkinson** [comment]
I'm not 100% certain where else to post this, but it also seems to break Jellyseerr setup as well. On step 2 of the wizard, it's unable to sync libraries (`[Jellyfin API]: Something went wrong while getting libraries from the Jellyfin server: Requests failed with status code 403`) and on the Jellyfin server I see `AuthenticationScheme: "CustomAuthentication" was forbidden."`.

**Comment by felix920506** [comment]
@jet082 Why? According to above comments, the server is following the spec. It's the clients that are causing the problem and should be fixed client side.
