### ISSUE TITLE
How to handle unsupported FFmpeg versions

### ISSUE THREAD

**Issue by ploughpuff** [jellyfin/jellyfin#1066]
At present, the user is free to select any version of FFmpeg to use with Jellyfin, and only warnings shall be written to the log file if outside the supported (recommended) range.  An example log file entry as follows:
![image](https://user-images.githubusercontent.com/33969763/53990610-910fc700-4120-11e9-83e9-c15562dad41b.png)

Maybe this approach of free selection is ok.  Perhaps a better approach is to enforce a version range to use?  This issue has been raised to start the discussion and eventually resolve the ToDo in function ValidatePath():
https://github.com/jellyfin/jellyfin/blob/75996476a7ce63134e37935e8ddeddfdb0d63a5d/MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs#L198-L199

The FFmpeg version range supported (recommended) is defined in EncoderValidator():
https://github.com/jellyfin/jellyfin/blob/028a98d2c1440ba25e50e54ae97e81c55bc4c497/MediaBrowser.MediaEncoding/Encoder/EncoderValidator.cs#L70-L71

**Comment by JustAMan** [comment]
I think we should keep it as it is until we provide our own build for all platforms, right now only Docker and Debian (and probably Ubuntu) are covered.

**Comment by mooninite** [comment]
Please don't enforce a maximum. As I can tell from your screenshot that's the Windows way of handling external dependencies and that's why the old code had this functionality skeleton'd to begin with. Maximum versions are an unknown. You would have to bump the max version with every release to "validate" it and this will lead to more headache. Distros should be able to manage these dependencies on their own as long as you have a minimum set. Besides the ffmpeg changes to CLI options are pretty stable in my usage.

**Comment by joshuaboniface** [comment]
We wouldn't need maximum versions if OS maintainers were sensible about this - 4.0 -> 4.1 broke several things apparently that worked perfectly for us all the way from 3.2 to 4.0, but yet package maintainers don't seem to care and treat it as just another upgrade (see: Debian). We need to work around that somehow.

I prefer packaging our own of course (given that I've taken the lead on Debian/Ubuntu packaging - yes @JustAMan it does support Ubuntu too haha) but doing that for all possible operating systems seems to be a big effort.

**Comment by mooninite** [comment]
If it breaks it's on the maintainer of that package to remedy it. Version update breakage is nothing new and a max ceiling is not a solution. You know the ceiling at the moment, but when Jellyfin supports 4.1 what is the new ceiling?

**Comment by EraYaN** [comment]
We should probably keep it as strictly a suggestion. Especially if we start supporting things like tonemapping, that will just fail on older ffmpeg versions.
