### ISSUE TITLE
[Issue]: Unable to get NVIDIA transcoding working

### ISSUE THREAD

**Issue by EricThunder** [jellyfin/jellyfin#10675]
### Please describe your bug

Trying to get hardware transcoding working in a Proxmox LXC container (despite it working with no problems for months, got no clue what broke it). Running `nvidia-smi` gives me the expected output which makes this all the more confusing. All the useful info is attached below. I can provide any info if needed.

### Jellyfin Version

10.8.13

### Environment

```markdown
- OS: ubuntu-server 22.04.3 LTS
- Linux Kernel: 6.5.11-6-pve
- Virtualization: Proxmox LXC
- Clients: Browser
- Browser: Firefox
- FFmpeg Version: jellyfin-ffmpeg6
- Playback Method: Transcode to lower resolution
- Hardware Acceleration: NVIDIA Hardware transcoding
- GPU Model: 1660
- Plugins: N/A
- Reverse Proxy: NGINX Proxy Manager
- Base URL: N/A
- Networking: N/A
- Storage: ZFS (TrueNAS)
```

### FFmpeg logs

```shell
[AVHWDeviceContext @ 0x55a0b22a8fc0] cu->cuInit(0) failed -> CUDA_ERROR_UNKNOWN: unknown error
Device creation failed: -542398533.
Failed to set value 'cuda=cu:0' for option 'init_hw_device': Generic error in an external library
Error parsing global options: Generic error in an external library
```

### Please attach any screenshots here

![image](https://github.com/jellyfin/jellyfin/assets/67475344/21c4e158-9594-4b09-8abb-6f395ad779e4)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
Please head to our chat rooms or forum for support https://Jellyfin.org/contact
