### ISSUE TITLE
[Issue]: Audiobooks - Artist folder containing multiple books considered wrongly as one audiobook when the audiobooks start with artist name

### ISSUE THREAD

**Issue by verybadsoldier** [jellyfin/jellyfin#10677]
### Please describe your bug

I noticed another strange behavior related to audiobook handling:

When having such a structure (an artist folder containing two audiobooks), then the artist folder is considered as only one book:
```
D:.
└───MyAuthor
        MyAuthor - Book A.m4b
        MyAuthor - Book B.m4b
```

![image](https://github.com/jellyfin/jellyfin/assets/364469/2b6dbad0-6478-43f4-b9a4-178b799aacf9)

Expectation would have been to have "MyAuthor" displayed as a folder, being able to click into it to see two audiobooks.

The issue seems to be related to the audiobook files starting with the artist in the filename. When I rename the folder "MyAuthor" to e.g. "YourAuthor":
```
D:.
└───YourAuthor
        MyAuthor - Book A.m4b
        MyAuthor - Book B.m4b
```

Then the folder gets correctly displayed as folder:
![image](https://github.com/jellyfin/jellyfin/assets/364469/52e1cbb5-6358-4b7c-848b-129d21b4be06)

When clicking on it, then both books can be played:
![image](https://github.com/jellyfin/jellyfin/assets/364469/18e19b63-d962-4f3d-b08e-f9c69de8d238)

### Jellyfin Version

Other

### if other:

10.8.13

### Environment

```markdown
- OS: Ubuntu 22.04 Host
- Linux Kernel: Linux minion 5.15.0-84-generic #93-Ubuntu SMP Tue Sep 5 17:16:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- Virtualization: Official Docker Image
- Browser: Chrome
- Plugins: Bookshelf
- Reverse Proxy:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sevenrats** [comment]
This is not a bug, but the result of not following supported naming conventions:
https://jellyfin.org/docs/general/server/media/music/

**Comment by verybadsoldier** [comment]
> This is not a bug, but the result of not following supported naming conventions: https://jellyfin.org/docs/general/server/media/music/

You are probably referring to the "Books" version, right?
https://jellyfin.org/docs/general/server/media/books

Ok, fair enough, I wasn't aware that the structure mentioned there is a strict rule. To be honest, I didn't read that page as showing the supported naming conventions by Jellyfin. It says "The most common organization scheme for books is separation by Audiobook then by Author.", so it sounds like just one (of possibly multiple) example how people are doing it.

But no problem, I don't complain. Thanks for looking into it and clearing it up.

**Comment by sevenrats** [comment]
when I reread this in my email I realized how curt I had been. Sorry for that.  We appreciate your report very much, and you are correct that we could probably change the language in the docs to reflect that these structures are mandatory.
Thanks for participating!
