### ISSUE TITLE
[Issue]:  .avi files not working on Android tv

### ISSUE THREAD

**Issue by plasilva1997** [jellyfin/jellyfin#10688]
### Please describe your bug

I have video files in .avi format, and when I start the video I get a black screen and it doesn't work if I put play. for the moment I noticed that with this format.

Version Jellyfin android Tv 0.15.12

### Jellyfin Version

10.8.z

### if other:

10.8.13

### Environment

```markdown
- OS: Debian 11
- Linux Kernel: 5.10.0-26-amr64
- Clients: Android tv
- GPU Model: Quad- and dual-core ARM Cortex-A72 at 2.0GHz
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by plasilva1997** [comment]
[log.txt](https://github.com/jellyfin/jellyfin/files/13597442/log.txt)

this file "Dr Who S02E01 Une nouvelle Terre.avi"

**Comment by plasilva1997** [comment]
this is an extract from the logs 
[Logs.txt](https://github.com/jellyfin/jellyfin/files/13604114/Logs.txt)

**Comment by sevenrats** [comment]
will you please try the latest version as well and confirm if this issue persists or not
