### ISSUE TITLE
[Issue]: scan stalls without error when encountering a recursive symbolic link

### ISSUE THREAD

**Issue by kentdobias** [jellyfin/jellyfin#10687]
### Please describe your bug

When there is a recursive symbolic link inside a Jellyfin library, the scan will stall forever after encountering it. No error or warning messages are printed, so it is extremely challenging to identify the problem.

I discovered that I had mistakenly made a recursive symbolic link from inside the directory of a music album to the absolute path of the parent directory. I discovered this after _days_ of trying to debug the stalled scan for my music library.

Jellyfin should avoid traversing recursive links, or at least issue warnings when it suspects a scan loop has been encountered.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Arch Linux
- Linux Kernel: 6.6.4
- Virtualization: none
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage: local on ZFS
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sevenrats** [comment]
this is not something we can support.

**Comment by sevenrats** [comment]
You are welcome to open a feature request for this at features.jellyfin.org
We no longer accept feature requests in the bug tracker.
