### ISSUE TITLE
Finalise removal of --ffprobe switch

### ISSUE THREAD

**Issue by ploughpuff** [jellyfin/jellyfin#1068]
Decision during PR #844 to remove the logic behind the --ffprobe switch and write warning in log of its imminent demise:
https://github.com/jellyfin/jellyfin/blob/669c48cc8bd6b9023d54a38c8e8b7f4120cb7368/MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs#L89-L93

This issue raised to finalise removal of the --ffprobe switch.  Know actions as follows:
1. Remove ToDo and log warning in SetFFmpegPath()
1. Remove ffprobe from StartupOptions class.

**Comment by JustAMan** [comment]
Fixed by #1100
