### ISSUE TITLE
[Issue]: Grouped folder library navigation submenu

### ISSUE THREAD

**Issue by MichaelRUSF** [jellyfin/jellyfin#10686]
### Please describe your bug

Grouped folder libraries go to a submenu instead of going directly to the default view when viewing from the webUI using the latest unstable build. 

Seems related to other regressions introduced by #9764 

As a bonus bug, all subfolders will point to the respective items, but the genre folder view is broken. 

### Jellyfin Version

Other

### if other:

10.9.0

### Environment

```markdown
- OS: Windows 11
- Linux Kernel:
- Virtualization:
- Clients:
- Browser: Firefox 120
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Please attach any screenshots here

![1](https://github.com/jellyfin/jellyfin/assets/78215956/89058ae2-55ae-4897-8756-956891bf9a3c)

![2](https://github.com/jellyfin/jellyfin/assets/78215956/c9e21ff9-cc53-4c92-beed-1dd4afa5dd75)

![3](https://github.com/jellyfin/jellyfin/assets/78215956/81f77ef3-c011-4d0a-b87c-2121eb61f128)

![4](https://github.com/jellyfin/jellyfin/assets/78215956/2f7758e0-6b40-4c10-9fb5-099a4b838c4c)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by thornbill** [comment]
Should be fixed by https://github.com/jellyfin/jellyfin/pull/10702
