### ISSUE TITLE
How should I set up jellyfin so that I can access the jellyfin server only through a reverse proxy without enabling remote connections.

### ISSUE THREAD

**Issue by lin1123** [jellyfin/jellyfin#10699]
### Please describe your bug

I want to open my jellyfin server to the internet and have caddy provide the ssl certificates via caddy reverse proxy to 127.0.0.1:8096. i can access jellyfin's media server via the domain name when i turn on the remote connection feature, but this will also put the 8096 of the jellyfin server http port of jellyfin's server http open to the internet.
The scenario I want to achieve is that the jellyfin server does not expose any HTTP or HTTPS ports to the internet, and can only access jellyfin's server and play content via the caddy server's domain name.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS:debian 12
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:caddy
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PrplHaz4** [comment]
If you can access port 8096 from the internet, that means something is opening 8096 on your router.  Make sure you disable automatic port mapping in Network settings and do not forward any ports other than 443.

When using a reverse proxy, you will want all clients to access the IP of the proxy (on port 443 w/tls), not the actual jf server IP.  Often this means that internet clients will need dns to resolve to your public IP address (which will forward 80/443 to the proxy then to jf), and local network clients will need it to resolve to the internal proxy IP address.

**Comment by felix920506** [comment]
Hi, I'm afraid what you want isn't possible. If you really wanted to work out a solution that works for you, please head to our chat rooms or forum: https://jellyfin.org/contact

**Comment by Its-Ankush** [comment]
This is easy to achieve @lin1123  . Jut go to windows firewall and block incoming traffic to ports 8096/tcp, 8920/tcp, 1900/udp, 7359/udp . Once you do this, only 80 and 443 will be open to the internet and other ports will be unavailable from outside.

Let me know if this works :)
