### ISSUE TITLE
[Issue]: Use `eof_action=pass` when overlaying subtitles

### ISSUE THREAD

**Issue by jkhsjdhjs** [jellyfin/jellyfin#10698]
### Please describe your bug

When overlaying subtitles on video, jellyfin currently uses the following options with the `overlay` filter (there are multiple occurances, I only linked one):
https://github.com/jellyfin/jellyfin/blob/0d5bbfda321f64ad78b5b74e7bdfbbbb8b64c7af/MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs#L3978

Aside the redundancy (`repeatlast` overrides `eof_action` and `shortest` overrides `repeatlast`), this causes the output to be terminated as the end of one of the input streams is reached. In some cases, the subtitles don't have the same duration as the main video and may end before the video, which causes the resulting video stream to be terminated prematurely.

Instead, I propose using `eof_action=pass:repeatlast=0`, which continues transcoding the video if the subtitle stream ends earlier.
If the subtitle stream has a higher duration than the video, overlaying the subtitles is stopped once the end of the video stream is reached even without `shortest=1`, since that's the default behavior. The `overlay` filter will never create an output stream with a higher duration than the main input.

See also: https://ffmpeg.org/ffmpeg-filters.html#Options-for-filters-with-several-inputs-_0028framesync_0029

### Jellyfin Version

10.8.z

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
Hi, you should make a change and open a pull request instead.

Instructions on how to do so can be found here: https://docs.github.com/en/get-started/quickstart/contributing-to-projects

**Comment by jkhsjdhjs** [comment]
I created this issue, because I wanted to discuss this proposal first, as I didn't know the reasons for choosing `eof_action=endall:shortest=1:repeatlast=0`. However, since this proposal seems to have been accepted, I'll create a PR soon.

**Comment by nyanmisaka** [comment]
I'm okay with this. Setting `eof_action=endall:shortest=1` was due to an issue but it seems no longer exists now.
