### ISSUE TITLE
Fork existing documentation 

### ISSUE THREAD

**Issue by JustAMan** [jellyfin/jellyfin#107]
I think we miss the Emby docs found in their wiki, might make sense to fork it while we can.

**Comment by drakus72** [comment]
I do have it forked just in case.

**Comment by softworkz** [comment]
I would like to kindly inform you that the wiki content has not been published under any OSS license and the copyright is owned by Emby Llc.

**Comment by nvllsvm** [comment]
I have a script regularly updating local copies of all of Emby's and team member's repos as well.

We can't use it because Emby's license bullshit strikes again.

Closing

**Comment by JustAMan** [comment]
Just in case - https://github.com/jellyfin/jellyfin/wiki/Web-archive-of-Emby-documentation

**Comment by nvllsvm** [comment]
Beautiful.
