### ISSUE TITLE
[Issue]: Jellyfin doesn't recognize Artists or Album Artists anymore

### ISSUE THREAD

**Issue by devsnek** [jellyfin/jellyfin#10709]
I am experiencing this problem with jellyfin installed from the arch package. I am new to jellyfin so perhaps I am doing something wrong. All my tracks show up using the expected metadata, for example:
![](https://gc.gy/3f50e82c-90e6-460b-940f-eca1944b6be2.png)
However, artist pages are empty:
![](https://gc.gy/ad8c4a6d-e9ea-495b-9cd3-95bb36dc0388.png)
I haven't found a way to view any songs by grouped by albums, for example "We Like It Here" is not clickable here:
![](https://gc.gy/2a5096a9-5e2e-4eb6-a722-c69945ce6b3e.png)
And the albums page is empty
![](https://gc.gy/575e6ca4-98ca-42ef-bf64-42ff0b8a8859.png)

_Originally posted by @devsnek in https://github.com/jellyfin/jellyfin/issues/10353#issuecomment-1792769490_

**Comment by tubatodd** [comment]
I am experiencing this exact same issue with Ubuntu 24.04 x86_64 and Jellyfin 10.8.13. It is a new VM with a fresh music import
