### ISSUE TITLE
Continue/Up Next UI Suggests Different Versions of Same File in Different Libraries

### ISSUE THREAD

**Issue by eroc1990** [jellyfin/jellyfin#10716]
### Please describe your bug

To keep my subs and dubs separate and allow me to have burned in subs on my foreign language files, I have many shows in two different libraries. Those shows are inside their own subfolders, associated with separate libraries. When I play one file from one library, both versions show up in my Continue or Up Next feeds, where the expected behavior would be that only the one I played (and it's associated series files from the same library, if a series) would be suggested. Currently, that is not the case.

I can provide more details later if needed. I'm on my phone at the moment so grabbing additional info is a bit difficult.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Docker over Unraid 6.12.6
- Linux Kernel: 6.1.64
- Virtualization: Docker
- Clients: Android TV, Android, Windows, Linux, Web
- Browser: Firefox, Chrome (and Chrome-based), all latest at time of writing.
- FFmpeg Version:
- Playback Method: Mostly direct, some transcode in FF
- Hardware Acceleration: VAAPI
- GPU Model: AMD Radeon Vega APU
- Plugins: AniDB, AudioDB, Cover Art Archive, Intro Skipper, JellyScrub, MusicBrainz, 
- Reverse Proxy: Nginx Proxy Manager, Direct IP access
- Base URL:
- Networking:
- Storage: Local SATA SSD and HDD, NFS mount to Raid1 HDD array.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sevenrats** [comment]
related: #1481
