### ISSUE TITLE
Not meeting the requirements when using transcoding

### ISSUE THREAD

**Issue by ljc2266** [jellyfin/jellyfin#10711]
I found that the TS file after transcoding from 4K to 1080P and 10MBPS is still in 4K format. Upon checking the ffmpeg log, it was found that - scale was not used.

**Comment by Shadowghost** [comment]
Currently the bitrate is the major deciding factor, not the used resolution.

**Comment by felix920506** [comment]
Hi, this feature is working as intended.
Please understand that bitrate is a more significant factor than the actual resolution itself for the quality of a video stream.
Closing this as it is not a bug.

**Comment by ljc2266** [comment]
Sorry, but I found that using bit rate as the main criterion may result in low transcoding efficiency.
