### ISSUE TITLE
[Issue]: adding same path to two libraries causes it to be ignored in one of them

### ISSUE THREAD

**Issue by johnl** [jellyfin/jellyfin#10723]
### Please describe your bug

I have a directory that contains both music and movies. I added it first to my Music library and then also added it to my Movies library and found that it was being silently ignored by the Movies library. The music in it showed up in the Music library but none of the movies in it showed up in the Movies library.

If I then remove the directory it from the Music library, leaving it in the Movie library and then re-add it to the Music library, the movies show up but the music doesn't.

The same happens if I duplicate any subdirectory of the parent directory too.

It's ok if this cannot be supported, but *silently* ignoring the duplicate directory makes things very confusing.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Debian
- Virtualization: Docker
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cvium** [comment]
Known limitation. Not easily fixed nor alertable.
