### ISSUE TITLE
[Issue]: Roku: "Use Splashscreen as Home Background" includes libraries user can't access

### ISSUE THREAD

**Issue by cinderblockgames** [jellyfin/jellyfin#10728]
### Please describe your bug

The generated image when you select "Use Splashscreen as Home Background" uses images from all libraries, including ones the user can't access.

### Jellyfin Version

10.8.z

### if other:

10.8.13

### Environment

```markdown
- OS: Ubuntu 22.04.3 LTS
- Linux Kernel: GNU/Linux 5.15.0-89-generic x86_64
- Virtualization: Docker
- Clients: Roku
- Plugins: AudioDB, Bookshelf, Jellyscrub, LDAP-Auth, MusicBrainz, OMDb, Playback Reporting, Studio Images, TMDb, TMDb Box Sets, TMDb Trailers, TheTVDB, Trakt
- Reverse Proxy: traefik
- Networking: bridge
- Storage: SMB
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
The splash screen isn't user-specific so that makes sense.

**Comment by cinderblockgames** [comment]
At minimum, there should be a way to turn off the splash screen option on the server side, then. It shouldn't be only a client side option. You wouldn't want a kid turning it on and having horror scenes show up or something.

**Comment by crobibero** [comment]
There is.
Go to Settings -> General -> Enable the splash screen

**Comment by cinderblockgames** [comment]
> There is. Go to Settings -> General -> Enable the splash screen

Welp.  I'm a numpty.  Thanks for that!
