### ISSUE TITLE
[Issue]: "Display missing episodes within seasons" is not in the Admin UI for me

### ISSUE THREAD

**Issue by dandud100** [jellyfin/jellyfin#10725]
### Please describe your bug

I am missing the "Display missing episodes within seasons" in the library management within my admin panel.

Expected Behavior:
![image](https://github.com/jellyfin/jellyfin/assets/43549788/65642ca7-763e-4426-bdad-895f4449224e)
![image](https://github.com/jellyfin/jellyfin/assets/43549788/cf4472e8-9764-4a97-86c4-677c9eed3588)

Current Behavior:
![Screenshot_20231214-121512](https://github.com/jellyfin/jellyfin/assets/43549788/6c377de0-52ca-477c-abec-1829818ef41e)
![Screenshot_20231214-121529](https://github.com/jellyfin/jellyfin/assets/43549788/5ac36d3c-b147-47b4-b2d1-36e2ecba717b)

### Jellyfin Version

Other

### if other:

10.8.13

### Environment

```markdown
- OS: UnRaid 6.12.6
- Linux Kernel:
- Virtualization: Docker Container from Linuxserver
- Clients:
- Browser: Chrome
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nielsvanvelzen** [comment]
The "display missing episodes within seasons" option is not available for the "movies" library type because it doesn't have seasons.

**Comment by dandud100** [comment]
> The "display missing episodes within seasons" option is not available for the "movies" library type because it doesn't have seasons.

This it not a movies library.

**Comment by thornbill** [comment]
The option is only available globally not in the individual library settings. It seems like this should be a feature request.

**Comment by dandud100** [comment]
> The option is only available globally not in the individual library settings. It seems like this should be a feature request.

Where is it even globally? I only find it to enable for individual users, not server side.

**Comment by anthonylavado** [comment]
After installing the TVDB plugin, did you restart Jellyfin?

Also here's the library setting I was referring to in chat:

![image](https://github.com/jellyfin/jellyfin/assets/596194/0433fcec-fe55-4233-9fd1-6c82f984f92a)

**Comment by dandud100** [comment]
> After installing the TVDB plugin, did you restart Jellyfin?

Yes i did, multiple times.



> Also here's the library setting I was referring to in chat:

Yeah i enabled "Missing Episode Fetcher" and "TheTVDB"

**Comment by thornbill** [comment]
> The option is only available globally not in the individual library settings. It seems like this should be a feature request. 

I was looking at the wrong thing please ignore this comment 😅

**Comment by anthonylavado** [comment]
> Yeah i enabled "Missing Episode Fetcher" and "TheTVDB"

Alright, as long as everything's done you should be set. I think it'll get pulled on the next full library scan. I'm not sure, as I don't use the feature and have never tested it.

**Comment by dandud100** [comment]
> > Yeah i enabled "Missing Episode Fetcher" and "TheTVDB"
> 
> Alright, as long as everything's done you should be set. I think it'll get pulled on the next full library scan. I'm not sure, as I don't use the feature and have never tested it.

I let it scan my library but nothing new is added inside the tv show.

![image](https://github.com/jellyfin/jellyfin/assets/43549788/a2dee11b-a18a-47f2-8511-15b12d9ac2d9)

**Comment by cvium** [comment]
"Display missing episodes within seasons" is a User Display setting

**Comment by dandud100** [comment]
> "Display missing episodes within seasons" is a User Display setting

That user setting tells me to enable something on the **server side**... Where is this?

**Comment by cvium** [comment]
The Missing episode provider

**Comment by dandud100** [comment]
> The Missing episode provider

But why isn't it working for me?

**Comment by cvium** [comment]
I don't know. Could be many things. It's not a feature I use.
