### ISSUE TITLE
Unable to connect to Jellyfin Server using Jellyfin Kodi addon 

### ISSUE THREAD

**Issue by airsay** [jellyfin/jellyfin#1073]
**Describe the bug**
Kodi is unable to connect to Jellyfin Server after installing the Jellyfin addon on Kodi.

**To Reproduce**
Download Jellyfin Kodi Addon Zip and Install on Kodi (>= version 17)
After successful installation of addon, load addon (in Kodi) and provide Jellyfin Server IP address and port no
Tap on Connect

**Expected behavior**
Kodi (through Jellyfin addon) should load (and capable of playing) Jellyfin Libraries. 

**Actual Behaviour** 
Kodi with Jellyfin addon fails with an error message "Unable to connect to the server: server-ip" 

**System**:
OS: Ubuntu 18.04 (for ARM) 
Kodi Version: v18
Jellyfin Version: 10.2.1-1 for ARM
Kodi Log:http://paste.kodi.tv/jocacicire

**Comment by Gronkdalonka** [comment]
According to the log it's trying to connect to port 9096 where it should be 8096, maybe that's the problem here.

**Comment by airsay** [comment]
So I initially had Jellyfin running on 8096. When I couldn't get the addon to access Jellyfin, I changed the port on JF to 9096 and tried connecting without luck. The funny thing is that the upstream project (from which JF was forked) is also running on my server using Docker on a different port. I'm able to connect to the upstream project using both their Kodi addon and using JF's Kodi addon

**Comment by Verequies** [comment]
I can confirm this is an issue, had to switch down to the 10.2.z branch in order for the Kodi Addon to start working again.

**Comment by EraYaN** [comment]
It might be worth it to post the server log as well. I see a ton of different errors in the Kodi log, from refused connections to aborts.

**Comment by JamesVexica** [comment]
Just seen this, mines been working perfectly fine apart from the odd error from not been able to find a file but I had that with Plex/Emby so didn't consider it a problem. I'll double check my version when I'm home and post a log if I have the same issue, If I don't reply consider that I didn't have the issue.

**Comment by hukoeth** [comment]
I get an error whenever I try to switch on the Jellyfin Companion app setting ing KODi add-on (please install the Kodi companion app....). The error pops up after turning the mentioned setting on and then restarting Kodi.

However sync between Jellyfin and Kodi happens almost instantly despite this, so not sure what to make of it.

If someone can point me to the correct logs I'm happy to post them here (couldn't find anything related in Kodi/Jellyfin logs myself)

**Comment by oddstr13** [comment]
"the Kodi companion app" probably refers to the `Kodi Sync Queue` Jellyfin server plugin.

Other than that, is the connection issue still present?
If you are connecting via http, jellyfin/jellyfin-kodi#22 may be related.
Fix is merged jellyfin/jellyfin-kodi#28, but not in our Kodi repo yet.
You can [download the master branch](https://github.com/jellyfin/jellyfin-kodi/archive/master.zip), and install that as a zip addon to test if this solves the issue.
