### ISSUE TITLE
[Issue]: Any user can delete/edit collections created by all users

### ISSUE THREAD

**Issue by deadcxap** [jellyfin/jellyfin#10744]
### Please describe your bug

As an administrator, I created collections - lists of films by series/topics/events. It turned out that any user without administration rights can delete films from collections, delete the collections themselves, and edit their data.
I tried to enable the "lock data from changing" option both on the "collection" library and on its individual elements - it did not help.
I looked through all the settings, but did not find anything similar to the ban on deleting media files.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: UNRAID
- Linux Kernel:
- Virtualization: Docker
- Clients: Browser
- Browser: Chrome latest
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shadowghost** [comment]
Already fixed in master by having a new permission.
