### ISSUE TITLE
[Issue]: Playlists are visible to all users

### ISSUE THREAD

**Issue by TheDadNerd** [jellyfin/jellyfin#10747]
### Please describe your bug

I have multiple users on my server. Any playlist created by one user is visible to all users. This may be the expected behavior but it would be great if playlist were private to users unless shared. Or even the ability to mark certain playlists as private. 

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Linux
- Linux Kernel:
- Virtualization: Docker
- Clients: All
- Browser: Chrome
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration: NVENC
- GPU Model: GTX 1060
- Plugins: playbackreporting, infuse sync
- Reverse Proxy: nginx
- Base URL: none
- Networking: Bridge
- Storage: local
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
This is already fixed in unstable.
