### ISSUE TITLE
Change log message based on reason for delete

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin#1074]
**Is your feature request related to a problem? Please describe.**
The current log message for "DeleteItem" in LibraryManager just reads "Deleting item...", which can give you quite a fright given recent issues in other related projects.

**Describe the solution you'd like**
If possible, capture and log the reason for this item maintenance.  For example, if the item cannot be located on the drive, log text should read "Cannot find file, removing from library" or similar.

**Describe alternatives you've considered**
Nothing else at this time.

**Comment by anthonylavado** [comment]
https://github.com/jellyfin/jellyfin/blob/e04a152ed053a5a993b2d3d1f27b0f9ff6364fed/Emby.Server.Implementations/Library/LibraryManager.cs#L351

**Comment by LogicalPhallacy** [comment]
I think it might also be smart to add a logged warning whenever a File is deleted from the Filesystem itself
