### ISSUE TITLE
New user and many questions

### ISSUE THREAD

**Issue by wazerstar** [jellyfin/jellyfin#10743]
I have a few HDhomerun units (expand units) running via coax

I would like to know if one tuner is full will it move to the next if they are all added via web/index.html#!/livetvstatus.html ?

ie. 4 tuners used one the first, then if a fifth player is joining will it jump to the next available hdhomerun unit?

Also if 2 players are watching the same channel will it share the output so it only uses 1 tuner and puts out 2 both players?

How do I sort and build up a list to be shown in correct order, and is it possible via drag and drop to prioritize from one channel to another?

I tried from web/index.html#!/livetv.html.

But it does not really make any sense to me.

I could wish for when having a XMLTV epg, it would be cool when you map it also respect the actually info added to the epg/xmltv file

so If i have a channel  named DR 1 I would like to map from the epg, it will look its sort order id which would be 1 and its display name would be DR 1 as shown below, including the icon src also found in the epg file

```
 <channel id="1">
    <display-name>DR 1</display-name>
   <icon src="https://x.com/x/x/Logo.png"/>
  </channel>
```

**Comment by felix920506** [comment]
Please head to our chat rooms or forum for support: https://jellyfin.org/contact
