### ISSUE TITLE
[Issue]: Not playing series the language setup in my prefered languages

### ISSUE THREAD

**Issue by NielsJanssen90** [jellyfin/jellyfin#10741]
### Please describe your bug

Hello, 

When playing a serie that has multiple audio streams built into the serie. it always plays the one thats in the list at the top as default, even though i've set a preferred language in jellyfin. For every new episode of the serie i have to manually pick the my preferred language. 

PS. For subtitles this does work, just for the audio stream it doesn't. 

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Debian 
- Linux Kernel: 5.10.0-18-amd64
- Virtualization: TrueNAS Scale
- Clients: 
- Browser: Jellyfin App on tv, also fails to work in different browsers 
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Please attach any screenshots here

![ex1](https://github.com/jellyfin/jellyfin/assets/119003253/a436b679-870f-424f-a7d3-cbcba9dab9e6)
![Ex2](https://github.com/jellyfin/jellyfin/assets/119003253/121336a8-c64b-4dfd-9e5d-6174ed51a441)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JPVenson** [comment]
Hey,
This is a bug related to the [JellyfinWebUI ](https://github.com/jellyfin/jellyfin-web) project not to the server (this one).
Please reopen this bug in the respective repository.

**Comment by NielsJanssen90** [comment]
Done, thanks a lot for the feedback.
