### ISSUE TITLE
PGSSUB Subtitle Screen Position Restoration

### ISSUE THREAD

**Issue by wanglizao666** [jellyfin/jellyfin#10754]
When using PGSSUB subtitles for transcoding without black borders, the subtitle position changes when the screen ratio is incorrect

How to make ffmpeg automatically add black edges to the screen during transcoding to achieve a 16:9 ratio?

Can this feature be added in the next version to make it a selectable option

**Comment by wanglizao666** [comment]
![1](https://github.com/jellyfin/jellyfin/assets/107649720/9fc01a56-8f29-448b-9372-bedb0a040a74)
![2](https://github.com/jellyfin/jellyfin/assets/107649720/41f9e87e-0190-4d38-b608-99029e7547c5)

Image 1 is a normal subtitle position

Image 2 shows subtitles burned into the screen after transcoding, causing a change in position due to the screen ratio not being 16:9

**Comment by nyanmisaka** [comment]
Fixed by #10924
