### ISSUE TITLE
[Issue]: Integer overflow for MaxStreamingBitrate parameter

### ISSUE THREAD

**Issue by angaz** [jellyfin/jellyfin#10766]
Requests to `PlaybackInfo` results in:

```json
{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
  "title": "One or more validation errors occurred.",
  "status": 400,
  "traceId": "00-5fc4fdee225875b8c2749e5a311e2728-52d5f7e560aad94a-00",
  "errors": {
    "maxStreamingBitrate": [
      "The value '2400000000' is not valid."
    ]
  }
}
```

Looking at the successful and unsuccessful requests, the successful request has `MaxStreamingBitrate=1680000000`, while the unsuccessful request has `MaxStreamingBitrate=2400000000`.

I assume the problem is an integer overflow on the server side: https://github.com/jellyfin/jellyfin/blob/1cff5aef6386b8f4b303d86c8ab533010a7a7109/Jellyfin.Api/Models/MediaInfoDtos/PlaybackInfoDto.cs#L19

The value is `int`, which would max out at `2,147,483,647`, but the client is sending `2,400,000,000`.

_Originally posted by @angaz in https://github.com/jellyfin/jellyfin-media-player/issues/433#issuecomment-1868319840_

**Comment by felix920506** [comment]
2 Gbps is an absurd bitrate for media content.
If something is requesting such an absurd bitrate then it should be fixed, not the server. 
Closing this one as a non issue.

**Comment by thornbill** [comment]
fwiw this should be fixed by https://github.com/jellyfin-archive/jellyfin-apiclient-javascript/pull/433 in a future release

**Comment by angaz** [comment]
> fwiw this should be fixed by [jellyfin-archive/jellyfin-apiclient-javascript#433](https://github.com/jellyfin-archive/jellyfin-apiclient-javascript/pull/433) in a future release

Ah, cool, thanks
