### ISSUE TITLE
[Issue]: "Automatically add to collection" does not work

### ISSUE THREAD

**Issue by Neinei0k** [jellyfin/jellyfin#10768]
### Please describe your bug

When two or more movies have the same value in `<set>` tag in nfo file, they either should be added to the collection with the same name or to a new collection, if it does not exist. But jellyfin seems to completely ignore it. I remember this feature working when I first added my library to jellyfin but since then I never could make it work anymore.

I've tried to find the problem myself, but I could not figure out how to configure logging to show anything but default logs. This probably deserves a separate issue report.

### Jellyfin Version

Other

### if other:

10.8.13

### Environment

```markdown
- OS: Linux Mint 21.2
- Linux Kernel: 6.2.0-39-generic x86_64
- Virtualization:
- Clients: Jellyfin Media Player
- Browser: Firefox 121.0
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by UniverseDevel** [comment]
I can confirm this as well.
