### ISSUE TITLE
[Issue]: Jellyfin creating collection for movies even with Group Movies into Collections un-checked. 

### ISSUE THREAD

**Issue by onesandzeroesdotnet** [jellyfin/jellyfin#10762]
### Please describe your bug

I prefer to create my own collections, so I have unchecked Group Movies into Collections under Libraries->Display.

I have removed the Collection but any time I scan for new media it re-creates the collection. These movies are already in other collections as well.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Debian 11.7
- Linux Kernel: 5.10
- Virtualization: 
- Clients: Browser, GoogleTV, Android
- Browser: Firefox
- FFmpeg Version: 
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by scicomrunner** [comment]
Group Movies into Collections under Libraries->Display does not enable/disable the creation of collections. This enables the collections being displayed while browsing Movies. The creation of collections is done from the meta data collected on the movie and setup in the Library it self.

**Comment by onesandzeroesdotnet** [comment]
> Group Movies into Collections under Libraries->Display does not enable/disable the creation of collections. This enables the collections being displayed while browsing Movies. The creation of collections is done from the meta data collected on the movie and setup in the Library it self.

Ok, do you have a recommendation to how I can solve my issue then?

**Comment by MichaelRUSF** [comment]
You need to go into the movie library itself and unselect "Automatically add to collection"

![Screenshot 2023-12-26 175533](https://github.com/jellyfin/jellyfin/assets/78215956/2cbbb684-e78d-4548-ba2d-074729f2ff5f)

**Comment by onesandzeroesdotnet** [comment]
Thank you @MichaelRUSF .
