### ISSUE TITLE
[Issue]: Auto subtitle not working.

### ISSUE THREAD

**Issue by mateusfn98** [jellyfin/jellyfin#10771]
### Please describe your bug

My auto subtitle was working well, but was a simple subtitle with a black box and always showing at the bottom (not close to the translated word).
I fixed it, but now my subtitle isn't automatically. Every EP I need to activate, but in my subtitle settings I tried with force subtitle, and still not working. Does someone know something about it ?  

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Windows 11
- Clients: Browser, Roku
- Browser: Brave
```

### Please attach any screenshots here

![image](https://github.com/jellyfin/jellyfin/assets/74764525/dd5c79af-9904-4c78-9615-37b56e3f053d)
Tried with every option.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fireXtract** [comment]
If you go back to the media where it used to work reliably, does it work consistently again?

**Comment by felix920506** [comment]
Hi, please provide the following info
- Screenshots of the problem actually happening
- Concise reproduction steps
- Expected Behavior

**Comment by mateusfn98** [comment]
> Hi, please provide the following info
> 
> * Screenshots of the problem actually happening
> * Concise reproduction steps
> * Expected Behavior

Just opened the ep:
![image](https://github.com/jellyfin/jellyfin/assets/74764525/b2effa4b-6b37-4521-875b-febf959f894e)
Don't show the subtitles.

Expected: Show subtitles automatically in my preferred language (shown in the first comment).
