### ISSUE TITLE
[Issue]: Jellyfin not detecting album cover metadata (jpg)

### ISSUE THREAD

**Issue by elendil7** [jellyfin/jellyfin#10775]
### Please describe your bug

Jellyfin isn't detecting the jpeg file of the cover image for my media (e.g., a CD), even though its in the same folder as the music. This happens across my entire library, meaning I must manually upload the covers.

It it possible for jellyfin to scan & retrieve the cover images from each album folder automatically?

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS:
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by elendil7** [comment]
> Can you give some more info, like folder structure and the file name of your cover?

## Directory path to folder example:
\Media\Music\Classical\Symphony\Ludwig_van_Beethoven\Symphony_No.3_-_Eroica\Berlin_Philharmonic\Herbert_von_Karajan\1986

## Image of files in the directory (note jpg file is also there)
![image](https://github.com/jellyfin/jellyfin/assets/80429382/706f97e7-c965-4907-ba59-caf54ef49426)

**Comment by MichaelRUSF** [comment]
Rename your artwork to folder.jpg, cover.jpg, or other filenames as listed in the  [documentation.](https://jellyfin.org/docs/general/server/media/music/)

**Comment by felix920506** [comment]
Please rename the image files according to the documentation: https://jellyfin.org/docs/general/server/media/music/

**Comment by elendil7** [comment]
Thanks
