### ISSUE TITLE
DLNA streaming doesn't work after client has been restarted

### ISSUE THREAD

**Issue by agilob** [jellyfin/jellyfin#1078]
This regression appeared in 10.2.0.

Server seems to remember a DLNS session/client after reboot and is unable to start streaming again.

1. Start DLNA client like a TV
2. Stream one or more things
3. Turn off the client/TV
4. Attempt to stream again
4.1. client looks to be detected and connected
5. Streaming never starts, but client never receives the stream
6. Turn off the client/TV
7. Jellyfin still can see the client
![screenshot_20190308_175533](https://user-images.githubusercontent.com/2544251/54046162-76def300-41cb-11e9-9b06-ab4ee86096a1.png) 

which has been switched off 10minutes ago

Only walk around to fix re-streaming is to restart jellyfin docker. I saw people describing this on reddit too, so I'm not alone with this issue.

**Comment by AThomsen** [comment]
I can reproduce something similar with Kodi. Opening and closing it and checking in JF if it shows up and disappears. Sometimes after closing Kodi it still appears in JF.

git bisect tells me that 84d56976ba4494408c5e312a4f98a24efabca441 is to blame. Removing `Properties = null;`in the dispose method of device.cs seems to fix at least this problem. This means that the object (device) is still used after it is disposed (!!!).

@Bond-009 - any idea what's going on in this code?

**Comment by AThomsen** [comment]
This seems to be a combination of bugs from Emby as well as Jellyfin (84d5697).
@agilob , please try this docker image `athomsen/jellyfin:10.2.2-dlna-fix` and let me know if it works better.

**Comment by agilob** [comment]
@AThomsen it almost worked. 

1. Start movie A
2. Stop movie A and restart TV client (turn off for several seconds)
3. Turn on TV client and start movie A
4. Movie A resumed playing from previously stopped point
5. Stop movie A and restart TV client (turn off for several seconds)
6. Turn on TV client and start movie B
7. Movie B doesn't play
8. Movie A doesn't play

**Comment by AThomsen** [comment]
How do you "turn off" the TV? Pull the plug or switch to standby mode? Is the dlna client still running when in standby?

**Comment by agilob** [comment]
Turning off with red button on a remote. I wait several seconds for it to turn off, a few seconds later the DLNA client is invisible in JF.

**Comment by AThomsen** [comment]
Sorry, I can't reproduce this. But then again I don't have any dlna video receiving hardware, only audio/music. It would be great if you can reproduce this using a software player like Kodi.

Please do some more research to narrow down what causes the problem. Is it that the TV client is turned of twice? Is it when playing a different movie? Does the device get a new IP address when coming up again? Does the problem happen after JF hasn't been able to reach the client in 3x1 minute or only when it disconnects gracefully (you should see this is the logs).

**Comment by agilob** [comment]
Ok, I tried again and I was unable to stream it even second time, the TV was still available in JF even after being turned off over a minute ago and IP address was down (lost pings). After restart I wasn't able to stream the same movie. 
 
IP address is always the same, cached by MAC.

>you can reproduce this using a software player like Kodi.

This is a regression in JF, Emby works fine.

**Comment by AThomsen** [comment]
I meant reproduce using Kodi as the dlna client (instead of your TV) and JF as the server 😉

**Comment by agilob** [comment]
ok, I tested it with kodi from your docker and wasn't able to reproduce it, so I tested again on the TV and have good news. There seems to be a walk-around which is just force-reload Jellyfin webpage. There is still wired issue that client is listed as online for a few minutes(?, at least one minute) after being turned off doesn't respond to pings. Clicking on stream doesn't do anything, turning on TV and streaming does nothing, but as the client reconnected, JF page can be refreshed and streaming works fine. 

Your fix seems to work for me.

**Comment by agilob** [comment]
It's not fixed on master and fix isn't released, why close it?

**Comment by cvium** [comment]
Github automatically closes referenced issues when a PR is merged into the main branch (`master` in this case). Did you test the changes?

**Comment by agilob** [comment]
I tested changes from @AThomsen not from @Bond-009

**Comment by cvium** [comment]
Well, it's Bond's changes that are in master, which prompted the closing of this issue. Give it a whirl and let us know if it works.

**Comment by agilob** [comment]
If you don't mind I will test it on the next docker release.

**Comment by agilob** [comment]
Fixed, thank you guys.
