### ISSUE TITLE
Display Language - Localization doesn't work for some languages

### ISSUE THREAD

**Issue by nikolajevtovic** [jellyfin/jellyfin#10782]
### Please describe your bug

On user settings > display > display language change it does not update the UI language for some options. It works properly for many languages (eg. German, Italian, or Ukrainian work as expected) but it **does not work for Serbian or Macedonian** (I haven't tested them all, there might be more).

On change, it defaults to system default which is English in my case and completely ignores user settings.

### Jellyfin Version
10.8.12

### Environment
```markdown
- OS: Linux
- Clients: WebUI
- Browser: Chrome
- Networking: Bridge
- Storage: Local
```

**Comment by felix920506** [comment]
Please attach screenshots.

**Comment by nikolajevtovic** [comment]
![german](https://github.com/jellyfin/jellyfin/assets/25559626/515ddb9c-420f-4070-a726-5ce918f377b9)
![macedonian](https://github.com/jellyfin/jellyfin/assets/25559626/5a5620e1-4eaf-4a41-b911-7c222fed6f8c)
![serbian](https://github.com/jellyfin/jellyfin/assets/25559626/88be5101-a1b5-4b05-b888-b204279c9b03)

**Comment by nikolajevtovic** [comment]
Initially I thought it had something to do with Cyrillic fonts but it actually works for Bulgarian for example:
![bulgarian](https://github.com/jellyfin/jellyfin/assets/25559626/60a84394-a69a-4ef0-8312-30c3a5d3022e)

**Comment by nikolajevtovic** [comment]
The issue is still persistent.

**Comment by nielsvanvelzen** [comment]
I believe there is no issue here. The Macedonian translations are almost non-existent in 10.8
https://github.com/jellyfin/jellyfin-web/blob/release-10.8.z/src/strings/mk.json
They should improve dramatically in 10.9 https://github.com/jellyfin/jellyfin-web/blob/master/src/strings/mk.json

Keep in mind, translations are provided by the community via https://translate.jellyfin.org/.

**Comment by nikolajevtovic** [comment]
In the meantime I updated version to latest and I still don't see translations for Serbian although you can see it here it should be about 85% translated https://translate.jellyfin.org/translate/jellyfin/jellyfin-web/sr/?q=state:%3E=translated

**Comment by nielsvanvelzen** [comment]
Latest as in 10.9 (unstable upcoming release) or 10.8.13?

**Comment by nikolajevtovic** [comment]
10.8.13-1-ls10

**Comment by nielsvanvelzen** [comment]
We don't backport translation updates, so the last time translations where updated in 10.8 is over 2 years ago. The indicator in translations.jellyfin.org is for the current unreleased progress.

**Comment by nikolajevtovic** [comment]
Ok, in that case, let's wait for 10.9 and see

**Comment by Bond-009** [comment]
@nikolajevtovic Did 10.9 fix your issue?
