### ISSUE TITLE
jellyfin will supported mtt s70/80?

### ISSUE THREAD

**Issue by feichangaihu** [jellyfin/jellyfin#10796]
### Discussed in https://github.com/jellyfin/jellyfin/discussions/10770

<div type='discussions-op-text'>

<sup>Originally posted by **feichangaihu** December 26, 2023</sup>
i'm buy a gpu , name is mtt s80。
i like jellyfin,can i use jelly by mtt s80 to gpu encode or decode
</div>

**Comment by felix920506** [comment]
Please ask for help with setting up hardware acceleration in our chat rooms or forum: https://jellyfin.org/contact
