### ISSUE TITLE
[Issue]: Can't uninstalle or delete plugin AniList

### ISSUE THREAD

**Issue by florient22** [jellyfin/jellyfin#10827]
### Please describe your bug

![Schermafbeelding 2024-01-07 115527](https://github.com/jellyfin/jellyfin/assets/131882663/60bef4ab-744c-430d-9e1b-7b1d779a6798)
I am unable to uninstall or disable the AniList plugin, and despite there being multiple versions available, I can only successfully install version 6.0.0.0. This problem extends beyond AniList, as I have faced similar difficulties with other plugins, where older versions are installed and prove challenging to update or remove later.

Edith: I've discovered a method to uninstall the plugin, but I'm unsure how to proceed with installing the latest version. The process involves installing the newest version, deleting it afterward, and then restarting the server to ensure its removal.

### Jellyfin Version

10.8.z

### if other:

10.8.13

### Environment

```markdown
- OS:
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
Please provide what actually happens after you uninstall the plugin normally. This sounds like 2 issues in 1.

**Comment by florient22** [comment]
When attempting to delete it in the usual manner, I encounter a perpetual spinning circle animation, and the plugin fails to complete the deletion process.

**Comment by florient22** [comment]
i dont know if this helps but  at the message tab it says version 7 installed but in my repositorie it says version 6 is installed.
![Schermafbeelding 2024-01-08 1732361](https://github.com/jellyfin/jellyfin/assets/131882663/296c5a10-2de2-4dc6-a185-8cf5f037fbda)
![Schermafbeelding 2024-01-08 173211](https://github.com/jellyfin/jellyfin/assets/131882663/a227cda4-76c3-4b75-9426-b5d39886fbd7)

**Comment by florient22** [comment]
I believe I've identified the reason for the uninstallation issue. It seems that the repository incorrectly recognizes version 6 as installed, whereas version 7 is the actual installation. Consequently, attempts to uninstall it fail because the system is attempting to delete version 6, which isn't present.

**Comment by manjaroblack** [comment]
I am having this issue as well. Version 6.0.0.0 and Version 7.0.0.0 issue.

**Comment by crobibero** [comment]
This is an issue with the plugin, the version wasn't set correctly. I don't think there is anything the server can do to fix it.

**Comment by NilsLeo** [comment]
I wasnt able to get rid of the plugin. It looked identical to the screenshot above. I was able to get rid of it in my case by stopping the container, deleteing the folder `config/data/plugins/AniList_(version number) `, and then restarting the container

**Comment by Apellamen** [comment]
same problem here. where is the config/data/plugins/AniList_(version number) folder?

**Comment by samumatic** [comment]
Same Problem here with SkinManager

**Comment by uberhalit** [comment]
Same issue, plugin is utterly broken. 
> same problem here. where is the config/data/plugins/AniList_(version number) folder?

Under linux the plugin resides in `/var/lib/jellyfin/plugins/` and it can be successfully deleted from there.
