### ISSUE TITLE
[Issue]:  hardware transcoding fails vainfo reporte gfx1103 is not supported

### ISSUE THREAD

**Issue by zombiehoffa** [jellyfin/jellyfin#10830]
### Please describe your bug

hardware transcoding does not work on my beelink ser7 with a radeon 780m (RDNA3) gpu. on the host I get:

`vainfo --display drm --device /dev/dri/renderD128
libva info: VA-API version 1.19.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_1_19
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.19 (libva 2.12.0)
vainfo: Driver version: Mesa Gallium driver 24.0~git2401070600.a84729~oibaf~m for AMD Radeon Graphics (radeonsi, gfx1103_r1, LLVM 16.0.6, DRM 3.54, 6.5.11-7-pve)
vainfo: Supported profile and entrypoints
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointEncSlice
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileHEVCMain10             : VAEntrypointEncSlice
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileVP9Profile0            : VAEntrypointVLD
      VAProfileVP9Profile2            : VAEntrypointVLD
      VAProfileAV1Profile0            : VAEntrypointVLD
      VAProfileAV1Profile0            : VAEntrypointEncSlice
      VAProfileNone                   : VAEntrypointVideoProc
`

but in the container (it doesn't matter if it's official or linux server containers, it happens on both) I get:

`root@ubujelly:/# /usr/lib/jellyfin-ffmpeg/vainfo --display drm --device /dev/dri/renderD128
Trying display: drm
libva info: VA-API version 1.20.0
libva info: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_1_20
amdgpu: os_same_file_description couldn't determine if two DRM fds reference the same file description.
If they do, bad things may happen!
'gfx1103' is not a recognized processor for this target (ignoring processor)
'gfx1103' is not a recognized processor for this target (ignoring processor)
amd: LLVM doesn't support gfx1103, bailing out...
libva error: /usr/lib/jellyfin-ffmpeg/lib/dri/radeonsi_drv_video.so init failed
libva info: va_openDriver() returns 2
vaInitialize failed with error code 2 (resource allocation failed),exit
`

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: ubuntu 23.10 running docker
- Linux Kernel: 6.5.11-7
- Virtualization: docker
- Clients: web client
- Browser: chrome, firefox, edge, brave
- FFmpeg Version: ffmpeg version 5.1.4-Jellyfin Copyright (
- Playback Method: web
- Hardware Acceleration: that's what's broken
- GPU Model: radeon 780M
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
root@ubujelly:/# /usr/lib/jellyfin-ffmpeg/vainfo --display drm --device /dev/dri/renderD128
Trying display: drm
libva info: VA-API version 1.20.0
libva info: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_1_20
amdgpu: os_same_file_description couldn't determine if two DRM fds reference the same file description.
If they do, bad things may happen!
'gfx1103' is not a recognized processor for this target (ignoring processor)
'gfx1103' is not a recognized processor for this target (ignoring processor)
amd: LLVM doesn't support gfx1103, bailing out...
libva error: /usr/lib/jellyfin-ffmpeg/lib/dri/radeonsi_drv_video.so init failed
libva info: va_openDriver() returns 2
vaInitialize failed with error code 2 (resource allocation failed),exit
```

### FFmpeg logs

```shell
root@ubujelly:/# /usr/lib/jellyfin-ffmpeg/ffmpeg -v debug -init_hw_device drm=dr:/dev/dri/renderD128 -init_hw_device vulkan@dr
ffmpeg version 5.1.4-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-libs=-lfftw3f --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libsvtav1 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Splitting the commandline.
Reading option '-v' ... matched as option 'v' (set logging level) with argument 'debug'.
Reading option '-init_hw_device' ... matched as option 'init_hw_device' (initialise hardware device) with argument 'drm=dr:/dev/dri/renderD128'.
Reading option '-init_hw_device' ... matched as option 'init_hw_device' (initialise hardware device) with argument 'vulkan@dr'.
Finished splitting the commandline.
Parsing a group of options: global .
Applying option v (set logging level) with argument debug.
Applying option init_hw_device (initialise hardware device) with argument drm=dr:/dev/dri/renderD128.
[AVHWDeviceContext @ 0x55fbdb37a100] Opened DRM device /dev/dri/renderD128: driver amdgpu version 3.54.0.
Applying option init_hw_device (initialise hardware device) with argument vulkan@dr.
[AVHWDeviceContext @ 0x55fbdb37a5c0] Supported validation layers:
[AVHWDeviceContext @ 0x55fbdb37a5c0]    VK_LAYER_MESA_device_select
[AVHWDeviceContext @ 0x55fbdb37a5c0]    VK_LAYER_MESA_overlay
[AVHWDeviceContext @ 0x55fbdb37a5c0] GPU listing:
[AVHWDeviceContext @ 0x55fbdb37a5c0]     0: AMD Radeon Graphics (RADV GFX1103_R1) (integrated) (0x15bf)
[AVHWDeviceContext @ 0x55fbdb37a5c0] Requested device: 0x15bf
[AVHWDeviceContext @ 0x55fbdb37a5c0] Device 0 selected: AMD Radeon Graphics (RADV GFX1103_R1) (integrated) (0x15bf)
[AVHWDeviceContext @ 0x55fbdb37a5c0] Queue families:
[AVHWDeviceContext @ 0x55fbdb37a5c0]     0: graphics compute transfer sparse (queues: 1)
[AVHWDeviceContext @ 0x55fbdb37a5c0]     1: compute transfer sparse (queues: 4)
[AVHWDeviceContext @ 0x55fbdb37a5c0] Using device extension VK_KHR_push_descriptor
[AVHWDeviceContext @ 0x55fbdb37a5c0] Using device extension VK_KHR_sampler_ycbcr_conversion
[AVHWDeviceContext @ 0x55fbdb37a5c0] Using device extension VK_KHR_synchronization2
[AVHWDeviceContext @ 0x55fbdb37a5c0] Using device extension VK_KHR_external_memory_fd
[AVHWDeviceContext @ 0x55fbdb37a5c0] Using device extension VK_EXT_external_memory_dma_buf
[AVHWDeviceContext @ 0x55fbdb37a5c0] Using device extension VK_EXT_image_drm_format_modifier
[AVHWDeviceContext @ 0x55fbdb37a5c0] Using device extension VK_KHR_external_semaphore_fd
[AVHWDeviceContext @ 0x55fbdb37a5c0] Using device extension VK_EXT_external_memory_host
[AVHWDeviceContext @ 0x55fbdb37a5c0] Using device: AMD Radeon Graphics (RADV GFX1103_R1)
[AVHWDeviceContext @ 0x55fbdb37a5c0] Alignments:
[AVHWDeviceContext @ 0x55fbdb37a5c0]     optimalBufferCopyRowPitchAlignment: 1
[AVHWDeviceContext @ 0x55fbdb37a5c0]     minMemoryMapAlignment:              4096
[AVHWDeviceContext @ 0x55fbdb37a5c0]     minImportedHostPointerAlignment:    4096
[AVHWDeviceContext @ 0x55fbdb37a5c0] Using queue family 0 (queues: 1) for graphics
[AVHWDeviceContext @ 0x55fbdb37a5c0] Using queue family 1 (queues: 4) for compute transfers
Successfully parsed a group of options.
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
Which container are you using? The Linuxserver one or the Official one?

**Comment by felix920506** [comment]
This looks like a packaging issue of the containers

**Comment by zombiehoffa** [comment]
It does it in both but i suspect only the official is relevant to you guys. There was another closed bug from a while ago for a similar issue saying ffmpeg and something else just needed to be updated to get the new support. I will try and link it if i can find it again.

**Comment by zombiehoffa** [comment]
https://github.com/jellyfin/jellyfin/issues/10564

I believe this is the same or similar problem, just different card. something is in need of updating in the containter.

**Comment by zombiehoffa** [comment]
@felix920506  what repo should I be reporting this to? It's a problem with the jellyfin docker container not being properly updated.

**Comment by nyanmisaka** [comment]
Blocked by https://github.com/jellyfin/jellyfin-metapackages/pull/39

**Comment by zombiehoffa** [comment]
> Blocked by [jellyfin/jellyfin-metapackages#39](https://github.com/jellyfin/jellyfin-metapackages/pull/39)

that issue appears to be closed, dos that mean this can be fixed?

**Comment by crobibero** [comment]
We recently refactored how packaging works, I'm not entirely sure what part of that PR fixed the issue but if possible please give the `jellyfin/jellyfin:unstable` image a try.

https://jellyfin.org/posts/testing-10.9.0#how-you-can-test

**Comment by nyanmisaka** [comment]
> > Blocked by [jellyfin/jellyfin-metapackages#39](https://github.com/jellyfin/jellyfin-metapackages/pull/39)
> 
> that issue appears to be closed, dos that mean this can be fixed?

The latest unstable images have been upgraded to bookworm, which contains llvm16+ enough to support amdgpu gfx11.
