### ISSUE TITLE
[Issue]: turn off IP logging in reports

### ISSUE THREAD

**Issue by ristein** [jellyfin/jellyfin#10837]
### Please describe your bug

looking on the reports plugin I see IP addresses users connected from. I don't want to have a record of this. This is illegal in the EU. Logs are even shown for the time before the plugin was installed, so removing plugin does not help.

### Jellyfin Version

Other

### if other:

10.8.13

### Environment

```markdown
- OS: Ubuntu 22
- Linux Kernel: 6.2.0
- Virtualization: no
- Clients: yes
- Browser: yes
- FFmpeg Version: 4.4.2-0ubuntu0.22.04.1+esm3
- Playback Method: yes
- Hardware Acceleration: no
- GPU Model: AMD Radeon RX Vega 6 (Renoir)
- Plugins: AudioDB, KodiSyncQueue, MusicBrainz, OMDb, Open Subtitles, Playback Reporting, Reports, Studio Images, TMDb, TMDb boxsets
- Reverse Proxy: apache
- Base URL: yes: /jellyfin
- Networking: idk
- Storage: local
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
IPs in server logs are legal per European law and IP addresses aren't considered personal info. Closing as non issue.
