### ISSUE TITLE
"See it in Action" leads to login screen with unknown credentials

### ISSUE THREAD

**Issue by Corbie-42** [jellyfin/jellyfin#10835]
The interactive element, that a new user sees on the website https://jellyfin.org/ is a button labeled "See it in Action".
This leads to the demo under: https://demo.jellyfin.org/stable - which requires a username and password.

The credentials are nowhere to be found, so most potential new users are lost and will close the browser tab in this moment.

Please remove the login screen or provide the credentials somewhere.

**Comment by nielsvanvelzen** [comment]
Your adblocker is removing random elements.

> TO LOG IN: User "demo", empty password. NOTICE: This server is provided by the Jellyfin team for demonstration purposes with a limited media set. The demo user does NOT have administrative privileges. All content available on this server is in the Public Domain or released with a Free Culture license. This image is destroyed and recreated from a known good configuration EACH HOUR on the hour, and is updated to the latest upstream DAILY at 06:00 EST.
