### ISSUE TITLE
[Issue]: Subtitle system is problematic

### ISSUE THREAD

**Issue by csousougen** [jellyfin/jellyfin#10844]
### Please describe your bug

I find the subtitles system very buggy on jellyfin, so buggy that makes the app unusable some of the time. 
Below I have gathered some issues I am facing on a daily basis, using jellyfin via browser (safari)::

1. When I continue watching something, it resets subs to English language

2. When I change subs, it displays both English subs and my newly selected subs, or it ignores me and displays no subs at all.

3. It never sets subs to my default language. I have chosen my subs to be in Greek (Gre), so I expect the app to choose Gre among other available languages. Instead, I always see English subs as the pre-chosen (see my 1. comment).

Please spend some time fixing the subtitles system because it is very important for watching anything. 
 

### Jellyfin Version

Other

### if other:

10.8.13

### Environment

```markdown
- OS: Linux
- Linux Kernel:
- Virtualization: Docker
- Clients: 
- Browser: Safari
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration: Yes
- GPU Model: Intel
- Plugins:
- Reverse Proxy: No
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TimGels** [comment]
Can you provide a media info output of a relevant file in question? Preferably with [this](https://mediaarea.net/nl/MediaInfo) tool and output set to text.

> When I continue watching something, it resets subs to English language

Have you tried enabling the option: "Set subtitle track based on previous item". This option you can find under the Playback settings when you click on your user profile at the top right.

> When I change subs, it displays both English subs and my newly selected subs, or it ignores me and displays no subs at all.

Do you mean that it is displaying 2 subtitle tracks at the same time?

> It never sets subs to my default language. I have chosen my subs to be in Greek (Gre), so I expect the app to choose Gre among other available languages. Instead, I always see English subs as the pre-chosen (see my 1. comment).

There is much more to subtitle selection than it might seem on the surface. Have you tried setting the subtitle mode to either "Smart" or "Always Play"?
![afbeelding](https://github.com/jellyfin/jellyfin/assets/43609220/4c919aaa-f26d-4545-9c7b-9b6e539ad92a)

Please provide the requested information and answers to the questions.
