### ISSUE TITLE
Add Support for Riscv64

### ISSUE THREAD

**Issue by liberodark** [jellyfin/jellyfin#10846]
Hi,

Can you add riscv64 ? for improve hardware compatibility.
But I would like you to consider releasing support for riscv64.
Also I propose to provide riscv64 servers if necessary.

Best Regards

**Comment by crobibero** [comment]
dotnet doesn't currently support RISC-V, so not currently possible.

https://github.com/dotnet/runtime/issues/96117

**Comment by liberodark** [comment]
Thank for this information

**Comment by perise** [comment]
Shall we reopen this topic? I have made the latest Jellyfin run on my K1(https://canonical.com/blog/spacemit-announces-availability-of-ubuntu-on-k3-k1-series)?
