### ISSUE TITLE
[Issue]: Community rating must be a single decimal value

### ISSUE THREAD

**Issue by phaelax** [jellyfin/jellyfin#10851]
### Please describe your bug

I believe this has been reported before and from my understanding was supposedly fixed over a year ago. I'm on 10.8.4 and meta data is still inserted with community rating values with multiple decimal places but manually editing that meta data still requires the value be no more than a single decimal.  If the community rating was inserted as 7.174 from the scraping, you have to change it to 7.1 before you can save your own changes to any other field.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS:TrueNAS Scale (debian)
- Linux Kernel:
- Virtualization: docker
- Clients: 
- Browser: chrome
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
Hi, is there any reason for using an old version of Jellyfin?

**Comment by phaelax** [comment]
I'm running it through TrueNAS Scale and it says it's the current version and up to date, at least according to truecharts.
I'm checking again and it looks like my catalog isn't syncing.  I'll see if I can get this updated and check back.

**Comment by phaelax** [comment]
Now on 10.8.13 (a huge headache and lost my config, but that was a truecharts issue).  It does indeed look like this issue has been resolved.
