### ISSUE TITLE
[Issue]: transcode garbage collection removing `lost+found/` subdirectory

### ISSUE THREAD

**Issue by brianjmurrell** [jellyfin/jellyfin#10865]
### Please describe your bug

It would seem that the transcode directory garbage collection process is removing files/directories that it should not be removing, in particular the `ext[234]` `lost+found/` directory.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Linux
- Linux Kernel: N/A
- Virtualization: N/A
- Clients: N/A
- Browser: N/A
- FFmpeg Version: N/A
- Playback Method: N/A
- Hardware Acceleration: N/A
- GPU Model: N/A
- Plugins: N/A
- Reverse Proxy: N/A
- Base URL: N/A
- Networking: N/A
- Storage: N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
If this is happening, you have misconfigured permission settings. Please set appropriate permission settings such as preventing non root users from deleting lost+found and/or not granting Jellyfin root access.

Closing this as it is a non issue.

**Comment by brianjmurrell** [comment]
No.  Permissions are NOT wrong and you analysis is incorrect:

Before running the cleanup:

```
# ls -la /var/lib/jellyfin/transcodes/
total 188
drwxr-xr-x.  3 jellyfin jellyfin 139264 Jan 16 07:49 .
drwxr-x---. 14 jellyfin jellyfin   4096 Nov 30 01:00 ..
drwx------.  2 root     root      49152 Jan 16 07:49 lost+found
```

After running the cleanup:
```
# ls -la /var/lib/jellyfin/transcodes/
total 140
drwxr-xr-x.  2 jellyfin jellyfin 139264 Jan 16 07:50 .
drwxr-x---. 14 jellyfin jellyfin   4096 Nov 30 01:00 ..
```

Jellyfin process is running under it's own user:

```
# ps -ujellyfin fw
    PID TTY      STAT   TIME COMMAND
  20112 ?        Ssl   20:44 /usr/lib64/jellyfin/jellyfin --webdir=/usr/share/jellyfin-web --restartpath=/usr/libexec/jellyfin/restart.sh
```

Simply put, the `jellyfin` user is allowed to remove that directory:

```
# ls -la /var/lib/jellyfin/transcodes/
total 188
drwxr-xr-x.  3 jellyfin jellyfin 139264 Jan 16 07:56 .
drwxr-x---. 14 jellyfin jellyfin   4096 Nov 30 01:00 ..
drwx------.  2 root     root      49152 Jan 16 07:56 lost+found
# sudo -u jellyfin bash -c "rmdir /var/lib/jellyfin/transcodes/lost+found"
# ls -la /var/lib/jellyfin/transcodes/
total 140
drwxr-xr-x.  2 jellyfin jellyfin 139264 Jan 16 07:56 .
drwxr-x---. 14 jellyfin jellyfin   4096 Nov 30 01:00 ..
```
This is because the `jellyfin` user has permissions to write (which implies delete) entries in the directory, which it needs of course otherwise it could not create the transcode files it needs to create.

That's how the permission model works in POSIX file systems.  It doesn't matter that the directory being removed is owned by root.  The ownership/permissions of a sub-directory means diddly-squat about who can remove it.  It's entirely about the permissions of the containing directory.

Please reopen this issue.

**Comment by sevenrats** [comment]
it seems inappropriate to use a directory for your transcode which contains a lost+found/
isn't this a side effect of using the root of an ext4 drive as the transcode directory?  Wouldn't simply making a directory and using that instead obviate this entire problem?

**Comment by brianjmurrell** [comment]
> it seems inappropriate to use a directory for your transcode which contains a lost+found/

Why?  That sounds like blaming the victim.

Ultimately I want the space used by transcoding to be isolated so that if JF fills up it does not fill up a file system that anything else is using.  This seems pretty sane to me.  This is standard and responsible [file] system administration.  This is why for example one should create `/var` on a separate file system -- so that some run away process filling up a file in `/var` (i.e. `/var/log` perhaps) doesn't fill up your root file system and kill your system.

> isn't this a side effect of using the root of an ext4 drive as the transcode directory? 

Yes it is.  But I would rather put it that this is a side effect of the transcode directory cleanup just indiscriminately removing everything in a directory instead of isolating itself to the kinds of files that it wants to actually clean up.  If the cleanup simply even just removed files at the root of the directory and didn't descend directories or remove directories, this would be resolved.  But I would go further an say that it should only be removing files that it knows were created by the transcoding process.  I.e. by file name pattern.

> Wouldn't simply making a directory and using that instead obviate this entire problem?

I suppose.  But now I have an unnecessary sub-directory just to work around a bug in JF.  Is everyone going to have to know or learn this lesson the hard way as I have?

**Comment by oddstr13** [comment]
There is some sort of additional permissions applied to those directories, represented by the `.` at the end, Jellyfin would not be able to touch the `lost+found` dir at all with the `drwx------` permissions, regardless of the permissions of the directory it is saved in.

A quick search tells me the `.` represent that SELinux ACLs are present. `+` represent generic ACLs (getfacl/setfacl).

**Comment by brianjmurrell** [comment]
> There is some sort of additional permissions applied to those directories, represented by the `.` at the end,

That is just an SELinux indicator.  But SELinux should not be relied upon to mitigate this.  Many people (erroneously IMO) disable SELinux as they see it as a hassle (rather than trying to understand it and work with it).  Moreover JF is not always going to be run on Linux distros that have SELinux.

> Jellyfin would not be able to touch the `lost+found` dir at all with the `drwx------` permissions, regardless of the permissions of the directory it is saved in.

This is simply not true.  The permissions/ownership of a directory in a containing directory does nothing to prevent removal of it.  The permissions of the containing directory are all that is considered.  Try it for yourself:

```
$ id
uid=1001(brian) gid=1001(brian)
$ ls -ld .
drwxr-xr-x. 1 brian brian 50022 Jan 16 10:33 .
$ sudo bash -c "mkdir foo && chown root:root foo && chmod 700 foo"                                                                                                 
$ ls -ld foo
drwx------. 1 root root 0 Jan 16 10:33 foo
$ rmdir foo
$ ls -ld foo
ls: cannot access 'foo': No such file or directory
```

**Comment by sevenrats** [comment]
Its not blaming the victim, it's just not appropriate to use a path for your transcoding which contains things you want to keep.

**Comment by brianjmurrell** [comment]
I would argue that the garbage cleanup should not be removing just any/everything and it should be only removing things it knows to be garbage created by JF.
