### ISSUE TITLE
[Issue]: 具有ASS字幕的文件无法解码并自动退出解码

### ISSUE THREAD

**Issue by Meilinhost** [jellyfin/jellyfin#10868]
### Please describe your bug

具有内置ASS字幕的视频文件，在TV客户端播放无法正常解码，报错并在重试3次之后自动杀掉了解码进程。
如果将字幕选择为“无”就能正常解码播放，选择ASS字幕就如上被k掉解码进程自动退出
是哪里设置有问题或者说是哪里没设置对？
需要给它加一个ASS字体？

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS:群晖
- Linux Kernel:
- Virtualization:PVE
- Clients:Android TV
- Browser: chrome
- FFmpeg Version:10.8.13
- Playback Method:直接播放 转码
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
截图呈现
```

### FFmpeg logs

```shell
截图呈现
```

### Please attach any screenshots here

![IMG_20240115_213101_379](https://github.com/jellyfin/jellyfin/assets/3524108/dd75493a-1e3b-4956-bcdf-f42b063e077c)
![IMG_20240115_213104_273](https://github.com/jellyfin/jellyfin/assets/3524108/76257839-5a2f-405c-a9b8-f5aff243bcdc)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
Jellyfin is an English only project, please open another issue report, fill the template and submit it in English.
Also, please DO NOT put logs through translation engines.
