### ISSUE TITLE
[Issue]: Seeking inconsistent when using transcoding

### ISSUE THREAD

**Issue by AdamantUnstable** [jellyfin/jellyfin#10866]
### Please describe your bug

Seeking during playback often acts inconsistently for me, it's a bit hard to pin down exactly what's going on but basically after playing a bit of a video trying to rewind will often skip forwards instead of backwards, but not always. I think this is some sort of interaction between the cache and transcoding, because it only happens after there's a decent chunk of the video in the cache and disabling transcoding seems to stop it from happening. I am using software encoding but the system does have plenty of CPU power and transcoding runs very smoothly if I don't seek, and even if I do seek to an uncached part of the video it works properly. Of note is that the client doesn't seem to realise this is happening - I can skip backwards 10 seconds and have the video jump forwards instead, but the seek bar at the bottom still shows the time stamp having been stepped backwards by 10 seconds, which leads to different parts of the video being played with the same time displayed.

I'm not really sure what logs would be best for this, there's no obvious errors but the logs are very verbose. It does seem reliably reproducible though, at least on my setup.

### Jellyfin Version

10.8.z

### if other:

10.8.13

### Environment

```markdown
- OS: Prebuilt LinuxServer Docker image (hosted on Ubuntu 22.04)
- Clients: Android, Web (on Windows)
- Browser: Firefox
- Hardware Acceleration: None
- Reverse Proxy: NPM
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ericswpark** [comment]
Same issue here. Whenever I seek when transcoding is enabled I get bits of the file interspersed in the seek positions. I think it's Jellyfin restarting the transcode when a new position is set, but since it's done in the middle of a transcode it messes up the order of the segments being sent to the client.
