### ISSUE TITLE
Genres API does not return ItemCount (Albums) when using fields query param

### ISSUE THREAD

**Issue by ncrmro** [jellyfin/jellyfin#10864]
### Please describe your bug

Background: I was hoping to query genres and get album count and feed this to maybe chatGPT to consolidate my 300+ genres.

Issue: 

Given  a request to the following path `Genres?limit=1&ParentId=LONG_ID&fields=ItemCount`

I expect to get the count of items in the, though as I write this I realize what is the count of? 

```
{
  "Items": [
    {
      "Name": "17",
      "ServerId": "e2846106fb984d5c8af2bb0dba3c9fcc",
      "Id": "483843092bd841d1010b657d2095675e",
      "ChannelId": null,
      "Type": "MusicGenre",
      "ImageTags": {
        "Primary": "239ddbca6bc9fe27e3f9098c58c8fe7b"
      },
      "BackdropImageTags": [],
      "ImageBlurHashes": {
        "Primary": {
          "239ddbca6bc9fe27e3f9098c58c8fe7b": "eGL,,UxFfQxE#S*OWWfQS3oM9^WWfQS4XS?YbFfQWoV@E3bHfQW;N^"
        }
      },
      "LocationType": "FileSystem"
    }
  ],
  "TotalRecordCount": 310,
  "StartIndex": 0
}

```

I will say the Web UI calls this url on the Genres page

```
/Genres?SortBy=SortName&SortOrder=Ascending&Recursive=true&Fields=PrimaryImageAspectRatio%2CItemCounts&StartIndex=0&ParentId=ID&userId=ID
```

Which returns an item like this but again no count.

```
        {
            "Name": "17",
            "ServerId": "e2846106fb984d5c8af2bb0dba3c9fcc",
            "Id": "483843092bd841d1010b657d2095675e",
            "ChannelId": null,
            "Type": "MusicGenre",
            "PrimaryImageAspectRatio": 1,
            "ImageTags": {
                "Primary": "239ddbca6bc9fe27e3f9098c58c8fe7b"
            },
            "BackdropImageTags": [],
            "ImageBlurHashes": {
                "Primary": {
                    "239ddbca6bc9fe27e3f9098c58c8fe7b": "eGL,,UxFfQxE#S*OWWfQS3oM9^WWfQS4XS?YbFfQWoV@E3bHfQW;N^"
                }
            },
            "LocationType": "FileSystem"
        },
```

I also trying connecting directly to the library database but found it's not in WAL mode.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Debian
- Linux Kernel:
- Virtualization: ContainerD/Kubernetes
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chrisbenincasa** [comment]
Hey there - just wondering if you ever figured a workaround for this. Facing the same issue.

**Comment by errorforce** [comment]
solve it with multiple requests:

get all genres with your url and extract the genre name:
${serverUrl}/Genres?SortBy=SortName&SortOrder=Ascending&Recursive=true&UserId=${userId}

use each genre name and get the count:
${serverUrl}/Users/${userId}/Items?Recursive=true&Genres=${encodeURIComponent(genre.name)}&Limit=0
