### ISSUE TITLE
[Issue]: .m4a files not showing under "Artists" heading, fine under other headings.

### ISSUE THREAD

**Issue by xsaMNJfkltrwq5r3** [jellyfin/jellyfin#10860]
### Please describe your bug

I have some .m4a files that make up an Album under an Artist.  These file are scanned correctly and display under the "Albums" and "Songs" headings as well as play correctly.  These files though do not show up under the "Artists".  However other Albums (that contain .mp3 files) that are under the artist do display and play correctly.  I suspect it is an issue with the file type (being .m4a) vs .mp3.

After further investigation it seems if I place an .mp3 file (any random .mp3 file) in the above folder containing the .m4a files, once the metadata has been refreshed everything behaves as normal and the Album is listed under the "Artist" heading.  Possibly if Jellyfin doesn't see an .mp3 (or possibly other audio file type other than .m4a) in a folder it overlooks it?

Further investigation I have found that removing the bogus .mp3 file and refreshing now keeps the Album contents correctly and also shows it under the "Artists" heading correctly.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: UnRaid 6.12.6
- Linux Kernel:
- Virtualization: Docker
- Clients: Android, Browser
- Browser: Firefox
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:MusicBrainz, Audio DB
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
No Logs that appear to help available.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shadowghost** [comment]
Can you please post your file/folder layout?

**Comment by xsaMNJfkltrwq5r3** [comment]
Hello,  It is a standard Artist then album subfolder.   I have since settled that it is a metadata issue, somehow as I have since used Picard to set metadata and it works all the time.  Will post when I get back online.

**Comment by xsaMNJfkltrwq5r3** [comment]
So as mentioned I have the Standard Artist Folder structure with each album or song/s contained within.  I have since worked around the issue using Picard to apply the metadata and purposefully gathered the songs into albums if I could.  
I assume though that like me other users might just have a random collection of m4a's from an artist and place them in a subfolder and have the same issue.
