### ISSUE TITLE
[Issue]: Activities section in admin area is using old TV show name after meta data of that show got changed (corrected TV show indexing error)

### ISSUE THREAD

**Issue by Chingato** [jellyfin/jellyfin#10861]
### Please describe your bug

A TV show got indexed incorrectly (wrong show). I then manually corrected the meta data via the identify functionality and after searching the correct one got found. Now Jellyfin correctly updates all titles, descriptions, thumbnails and episodes which I can see as an end-user.

But if I now start watching / end an episode the old name is still used within the "activities" section which I can see within the admin settings. Looks like some fields which are not visible to end-users are not correctly updated and used for the activities section as identifier.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Windows 10 (installed as a Service)
- Linux Kernel: N/A
- Virtualization: N/A
- Clients: N/A
- Browser: Firefox 121.0.1
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration: Intel
- GPU Model: Intel
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deadcxap** [comment]
I'll add:
I had an anime on my media server. The metadata is obtained automatically via tvdb, but with a name that is unfamiliar to me. I corrected the name of the series to a more familiar to me manualy, and in the card it is displayed correctly, but at the start of each series - I see the old name, and neither in the metadata of the season, nor in the metadata of the series the name of the series is not specified at all. Even in the player in the title bar, it's the old title. The change only occurred after manually running "update metadata" from the context menu.
