### ISSUE TITLE
[Issue]: "Add to play queue" adds songs in album in alphabetical order, not in album order

### ISSUE THREAD

**Issue by infinitytec** [jellyfin/jellyfin#10877]
### Please describe your bug

When queuing up several albums to play, I expected them to play in the order of their track listing, however when pressing the "Add to play queue" button the album was added to the queue with its tracks in alphabetical order instead.

### Jellyfin Version

Other

### if other:

10.8.13

### Environment

```markdown
- OS: TrueNAS Scale Cobia
- Linux Kernel:
- Virtualization: TrueCharts app
- Clients: Web client
- Browser: Edge 120.0.2210.133
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by infinitytec** [comment]
I don't have access to some of the details of my instance at the moment, but I doubt they are relevant. If more details are needed I will get them.

**Comment by infinitytec** [comment]
I also reported #10879 which may or may not be related. It seems to be similar behavior.

**Comment by felix920506** [comment]
Hi, I was unable to reproduce this issue on 10.8.13 using both Edge and Firefox. Please provide more details.

**Comment by infinitytec** [comment]
Strange--I will try again on the computer I noticed the issue on in the same scenario as before. Perhaps I can then get more data, but I am not seeing the same behavior anymore on Firefox on the machine at home. same with #10879.

**Comment by infinitytec** [comment]
I accidentally closed this, but I will leave it closed unless I can verify I'm not going crazy.
