### ISSUE TITLE
[Issue]: Play button on album plays through tracks in alphabetical order instead of album order.

### ISSUE THREAD

**Issue by infinitytec** [jellyfin/jellyfin#10879]
### Please describe your bug

When pressing the play button on an album either from the library page or from the album's page the playback starts with the track which is alphabetically first. I would expect the album to play through in the order the tracks are listed rather than alphabetically. 

### Jellyfin Version

Other

### if other:

10.8.13

### Environment

```markdown
- OS: TrueNAS SCALE
- Linux Kernel:
- Virtualization:
- Clients: Web client
- Browser: Edge 120.0.2210.133
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by infinitytec** [comment]
I should also clarify that when clicking the first song in the album to play the playback order is as expected.

**Comment by felix920506** [comment]
Hi, I was unable to reproduce this issue on 10.8.13 using both Edge and Firefox. Please provide more details.

**Comment by infinitytec** [comment]
I am able to replicate this again on Firefox and Edge on Windows and the official Android app while away from home. Additionally this is over two different Internet connections. Perhaps this could be due to the added latency of the connection?

**Comment by felix920506** [comment]
My latency between client and server is ~300ms but this still doesn't happen to me

**Comment by solidsnake1298** [comment]
Does the metadata for your music have the track number in it?

![image](https://github.com/jellyfin/jellyfin/assets/137357145/7df836e8-85d4-4cd9-a8ba-2af2c5434cb8)

**Comment by infinitytec** [comment]
> Does the metadata for your music have the track number in it? I'm not able to reproduce on any client, but all my music has the track number populated.
> 
> ![image](https://private-user-images.githubusercontent.com/137357145/298194960-7df836e8-85d4-4cd9-a8ba-2af2c5434cb8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2OTg2MTgsIm5iZiI6MTcwNTY5ODMxOCwicGF0aCI6Ii8xMzczNTcxNDUvMjk4MTk0OTYwLTdkZjgzNmU4LTg1ZDQtNGNkOS1hOGJhLTJhZjJjNTQzNGNiOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOVQyMTA1MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYjcyOTI4NDJkNTYyZjY2YTE1MTNlMTI5MWZjMDcwNGM2NTUzNGRjNzQwMTE0YTI2NjhhNWM3ZTgxODcxY2E4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.44uhw6DEpZTPAwNNEpoRuXjEZ3v6Q4gyRhBz4YR-V3g)

Yes, I have that data correctly populated. I thought that may have been the problem as well, but the track numbers are correct.

I have a screen recording of it happening that I will try to share later, but to make matters more confusing I seem to have this issue on some albums but not on others, at least while away from home. I will verify more this evening.

**Comment by felix920506** [comment]
Please also provide client logs when this happens.

**Comment by infinitytec** [comment]
Well, this is interesting. I have verified it with at least eight albums. I bought them all at around the same time last year on iTunes. I then ran them through Picard to ensure the metadata was all good. Other albums, purchased through other methods, seem to be fine. In fact, CDs ripped with iTunes are even good!

For logs would a copy-and-paste of my browser's console work, or is there something else you need?

**Comment by infinitytec** [comment]
https://github.com/jellyfin/jellyfin/assets/13670462/adbf62f6-047d-41c8-ab75-0916052dfbdc

**Comment by felix920506** [comment]
*Client Logs Please*

**Comment by infinitytec** [comment]
> _Client Logs Please_
Apologies for my lack of knowledge, should I get the logs from my browser console or somewhere else?

**Comment by solidsnake1298** [comment]
Open your browser console (usually F12), click on the sources tab.  On your Jellyfin start an album playback.  In the dev console you should see a request called something like

`https://jellyfin.domain.tld:50443/Users/cd25ec33cb864773b14a0a46f90d9508/Items?ParentId=c5510361aa9242a4cee2c2517b5e03bb&Fields=ItemCounts%2CPrimaryImageAspectRatio%2CBasicSyncInfo%2CCanDelete%2CMediaSourceCount&SortBy=ParentIndexNumber%2CIndexNumber%2CSortName`

![devConsole](https://github.com/jellyfin/jellyfin/assets/137357145/ec5bf592-3288-4daa-a87c-e40cee55089b)

**Comment by infinitytec** [comment]
Thanks for the instructions, and I apologize for the delay.
[log.txt](https://github.com/jellyfin/jellyfin/files/14040888/log.txt)

For this album, "Gaeta's Lament" _should_ be the first track that plays, but "Adama in the Memorial Hallway" is the one that starts first. On Finamp, "Gaeta's Lament" plays first as expected.

**Comment by solidsnake1298** [comment]
Yep.  Jellyfin server is generating the playlist in the correct order.  So definitely confirmed not a server side issue.

**Comment by infinitytec** [comment]
Odd that it's only happening with these albums I bought from iTunes...

**Comment by solidsnake1298** [comment]
Are they ALAC files?  It shouldn't matter, but I'm curious.  Are these files transcoding?

**Comment by infinitytec** [comment]
They are playing direct. AAC, M4A

**Comment by solidsnake1298** [comment]
Can you make a backup of one of these albums and then use ffmpeg or some other app to repackage and reencode to another container?  We are finding some documentation that M4A doesn't properly support ID3 tabs.

You would do this with ffmpeg with something like this.

`ffmpeg -i filein.m4a -f flac fileout.flac`

**Comment by MichaelRUSF** [comment]
I was able to reproduce the same issue on an M4A AAC encoded album on 10.8.13. However, the issue seems to be fixed in the master.

**Comment by infinitytec** [comment]
> I was able to reproduce the same issue on an M4A AAC encoded album on 10.8.13. However, the issue seems to be fixed in the master.

Well, it's good to know I'm not crazy!

**Comment by MichaelRUSF** [comment]
I converted the album to .flac to check if that solved the issue on 10.8.13, but it didn't. However, I was able to narrow it down. The album had metadata populated in the "Sort title" field. Once I removed it for each track, the album played as expected, by track number. 

@infinitytec can you check if metadata is populated in the "Sort title" field in Jellyfin for an album? If so, remove it for each track in the album and let us know if that works.

**Comment by infinitytec** [comment]
> I converted the album to .flac to check if that solved the issue on 10.8.13, but it didn't. However, I was able to narrow it down. The album had metadata populated in the "Sort title" field. Once I removed it for each track, the album played as expected, by track number.
> 
> @infinitytec can you check if metadata is populated in the "Sort title" field in Jellyfin for an album? If so, remove it for each track in the album and let us know if that works.

Sorry for the incredibly late reply--these tracks indeed have a "Title Sort Order" tag. Removing that was a good idea, but didn't work.

I did, however, discover the culprit!

"Battlestar Galactica_ Season 2 (Original" - This made me think that the "(" made the files be read odd.
but...
"Battlestar Galactica_ The Plan and Razor" also had the same issue.

Which implies to me that the folder names may have been too long. Trimming the album folder names a bit seems to have done the trick. 

So, unless this is behavior that should be changed (or this is unintentionally fixed in an upcoming release as suggested earlier) I am happy to call this resolved and let this issue be a record of one of those obscure issues that someone in the far future will find.

**Comment by infinitytec** [comment]
> Do your media items have the sort title populated in Jellyfin?

They did, and clearing it didn't work. Renaming the folders and deleting the album.nfo file did the trick.

**Comment by alexcannan** [comment]
Hi there, this is also happening to me. Shouldn't track number take precedence over `Sort title` for music?

**Comment by ldexterldesign** [comment]
👋 https://github.com/jellyfin/jellyfin-web/issues/7019
