### ISSUE TITLE
[Issue]: Android/Android TV app failed to connect to a jellyfin server while web browser is working fine

### ISSUE THREAD

**Issue by gesong2077** [jellyfin/jellyfin#10897]
### Please describe your bug

1. One server hosts jellyfin behind the reverse proxy - haproxy. No public ipv4 address, only ipv6 public address
2. The other server has both public ipv4&ipv6 addresses and it only runs haproxy to reverse proxy the jellyfin service from the first server.

A device that has an public ipv6 address will connect to the first server without any issues. If I use the same device and try to connect to the second server, it will fail in the android app but succeed in the browser. This setup worked before 10.8.9, after upgrading the server version to 10.8.10, it doesn't work anymore

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Ubuntu 22.04 
- Linux Kernel: 6.2.x
- Virtualization: Docker
- Clients: 
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy: haproxy
- Base URL:
- Networking: Host
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
Please provide server and client logs.

**Comment by Bond-009** [comment]
Not enough info
