### ISSUE TITLE
[Issue]: Broken path to songs

### ISSUE THREAD

**Issue by auyylaso** [jellyfin/jellyfin#10890]
### Please describe your bug

This is what happens with all symbols except all of the following symbols ".()" accent letters as well result in showing as � in the jellyfin client. To be clear I only provided the log of one song but I get this error on all songs involving symbols. This doesn't occur when JellyFin server is running on windows.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Linux #92-Ubuntu SMP Mon Aug 14 09:30:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- Linux Kernel:5.15.0-83-generic
- Clients: JellyFin website and Feishin
- Browser: Opera gx
- FFmpeg Version: ffmpeg version 4.4.2-0ubuntu0.22.04.1 
- Playback Method: Play button?
- Hardware Acceleration: No I don't think so
- GPU Model: RTX 3070 and Adreno 650
- Plugins: None
- Reverse Proxy: Yes and No depends on who's connecting
- Networking: Yes
- Storage: Lots
```

### Jellyfin logs

```shell
Error processing request: "Could not find file '/REDACTED/Sleep Token/Take Me Back To Eden/07 - Are You Really Okay�.flac'". URL "GET" "/Items/19ddade139304b0613bb692bc34befec/File".
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JPVenson** [comment]
This issue is outside the scope of jellyfin. Your filesystem/mount does not support the uncode characters used by that filename. I suspect you tried to mount a filesystem via SMB that has those unicode chars.

But that is not an issue with jellyfin. Closing as won't fix

**Comment by auyylaso** [comment]
> This issue is outside the scope of jellyfin. Your filesystem/mount does not support the uncode characters used by that filename. I suspect you tried to mount a filesystem via SMB that has those unicode chars.
> 
> But that is not an issue with jellyfin. Closing as won't fix

Nope not mounted using SMB and the unicode chars look just fine in the Dolphin and terminal on the system so I honestly don't know why it happens especially given since it happens sometimes with - but other times doesn't the files can also be loaded locally using a music player on the ubuntu server which is why I was thinking it was jellyfin but if you don't think it has anything to do with jellyfin I will do some more looking on my own I guess.
