### ISSUE TITLE
Keep having problems with 4K HDR videos on WebOS and FireTV.

### ISSUE THREAD

**Issue by maxime334** [jellyfin/jellyfin#10898]
**Media Info of the file**
[media_info.txt](https://github.com/jellyfin/jellyfin/files/14000030/media_info.txt)
They're all non-working except the last media in the above media log file. it is one of the only HDR video working properly.

**Logs**
[log.txt](https://github.com/jellyfin/jellyfin/files/14000022/log.txt)

**FFmpeg Logs**
None?

**Stats for Nerds Screenshots**
Could not find.

**Server System (please complete the following information):**
 - OS: Ubuntu. Default installation.
 - Jellyfin Version: 10.8.13
 - Hardware settings & device: Intel i7 8700k w/o hardware accelaration.
 - Reverse proxy: None. Running on LAN.
 - Other hardware notes: Couple of HDD's mounted.
 
**Client System (please complete the following information):**
 - Device: LG C2 and older TV.
 - OS: WebOS and FireTV. Latest.

Playback stutter repeatedly after 5 seconds. Media is unwatchable. The problem seems to be mostly focused on 4k HDR videos. The media size can vary from 15gb to 70gb. I am certain that my network is not the problem. Putting a bitrate low, only when it removes the HDR, fixes the problem. I have migrated from Fedora to Ubuntu, did not fix the problem. Any help would be greatly appreciated. Please tell me if more information is necessary.

**Comment by Darkatek7** [comment]
This issue is still open, i got the same issue
