### ISSUE TITLE
[QSV]: Cant use on archlinux 

### ISSUE THREAD

**Issue by bibitocarlos** [jellyfin/jellyfin#10909]
### Please describe your bug

Hi,

I followed the installation of QS V on the jellyfin and archlinux wiki, but cant use QSV to transcode.

DEMSG log :
`
dmesg | grep i915
[    1.264192] i915 0000:00:02.0: vgaarb: deactivate vga console
[    1.264337] i915 0000:00:02.0: [drm] Using Transparent Hugepages
[    1.265184] i915 0000:00:02.0: vgaarb: VGA decodes changed: olddecodes=io+mem,decodes=io+mem:owns=io+mem
[    1.270223] i915 0000:00:02.0: [drm] Finished loading DMC firmware i915/adlp_dmc.bin (v2.20)
[    1.284388] i915 0000:00:02.0: [drm] GT0: GuC firmware i915/tgl_guc_70.bin version 70.13.1
[    1.284394] i915 0000:00:02.0: [drm] GT0: HuC firmware i915/tgl_huc.bin version 7.9.3
[    1.289083] i915 0000:00:02.0: [drm] GT0: HuC: authenticated for all workloads
[    1.289594] i915 0000:00:02.0: [drm] GT0: GUC: submission enabled
[    1.289596] i915 0000:00:02.0: [drm] GT0: GUC: SLPC enabled
[    1.289910] i915 0000:00:02.0: [drm] GT0: GUC: RC enabled
[    1.290642] i915 0000:00:02.0: [drm] Protected Xe Path (PXP) protected content support initialized
[    1.338880] [drm] Initialized i915 1.6.0 20230929 for 0000:00:02.0 on minor 1
[    1.344319] i915 display info: display version: 13
[    1.344327] i915 display info: cursor_needs_physical: no
[    1.344330] i915 display info: has_cdclk_crawl: yes
[    1.344332] i915 display info: has_cdclk_squash: no
[    1.344334] i915 display info: has_ddi: yes
[    1.344336] i915 display info: has_dp_mst: yes
[    1.344338] i915 display info: has_dsb: yes
[    1.344339] i915 display info: has_fpga_dbg: yes
[    1.344341] i915 display info: has_gmch: no
[    1.344343] i915 display info: has_hotplug: yes
[    1.344345] i915 display info: has_hti: no
[    1.344346] i915 display info: has_ipc: yes
[    1.344348] i915 display info: has_overlay: no
[    1.344350] i915 display info: has_psr: yes
[    1.344352] i915 display info: has_psr_hw_tracking: no
[    1.344353] i915 display info: overlay_needs_physical: no
[    1.344355] i915 display info: supports_tv: no
[    1.344357] i915 display info: has_hdcp: yes
[    1.344359] i915 display info: has_dmc: yes
[    1.344361] i915 display info: has_dsc: yes
[    1.387062] fbcon: i915drmfb (fb0) is primary device
[    1.387076] i915 0000:00:02.0: [drm] fb0: i915drmfb frame buffer device
[    3.519783] snd_hda_intel 0000:00:1f.3: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
`

Vainfo log :
`
vainfo 
Trying display: wayland
vainfo: VA-API version: 1.20 (libva 2.20.1)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 24.1.1 
`
ffmpeg log :
`
/usr/lib/jellyfin-ffmpeg/ffmpeg -encoders -hide_banner | grep -i qsv
 V..... av1_qsv              AV1 (Intel Quick Sync Video acceleration) (codec av1)
 V..... h264_qsv             H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (Intel Quick Sync Video acceleration) (codec h264)
 V..... hevc_qsv             HEVC (Intel Quick Sync Video acceleration) (codec hevc)
 V..... mjpeg_qsv            MJPEG (Intel Quick Sync Video acceleration) (codec mjpeg)
 V..... mpeg2_qsv            MPEG-2 video (Intel Quick Sync Video acceleration) (codec mpeg2video)
 V..... vp9_qsv              VP9 video (Intel Quick Sync Video acceleration) (codec vp9)
`

### Jellyfin Version

10.8.9

### Environment

```markdown
- OS: archlinux
- Linux Kernel: 6.7.0-arch3-1
- Clients: all
- Browser: all
- GPU Model:
```

### FFmpeg logs

```shell
/usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -ss 00:35:45.000 -init_hw_device vaapi=va:,kernel_driver=i915,driver=iHD -init_hw_device qsv=qs@va -filter_hw_device qs -hwaccel qsv -hwaccel_output_format qsv -c:v h264_qsv -autorotate 0 -i file:"/donnees/films/Transformers.Rise.of.the.Beasts.2023.AMZN.D.WEB-DL.1080p.seleZen.mkv" -autoscale 0 -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_qsv -preset 7 -look_ahead 0 -b:v 1116000 -maxrate 1116000 -bufsize 2232000 -profile:v:0 high -level 40 -g:v:0 72 -keyint_min:v:0 72 -vf "setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale_qsv=w=720:h=300:format=nv12" -codec:a:0 copy -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 715 -hls_segment_filename "/var/lib/jellyfin/transcodes/50edf99d5098dfbfd3899990c98e8e99%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/var/lib/jellyfin/transcodes/50edf99d5098dfbfd3899990c98e8e99.m3u8"


ffmpeg version 6.0.1-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 13.2.1 (GCC) 20230801
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-gpl --enable-version3 --enable-static --enable-gmp --enable-gnutls --enable-chromaprint --enable-libfontconfig --enable-libass --enable-libbluray --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopus --enable-libopenmpt --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
[AVHWDeviceContext @ 0x56282d613e80] Error setting child device handle: -17
Device creation failed: -1313558101.
Failed to set value 'qsv=qs@va' for option 'init_hw_device': Unknown error occurred
Error parsing global options: Unknown error occurred
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
Please ask for troubleshooting help in our chat rooms or on our forum: https://jellyfin.org/contact
