### ISSUE TITLE
Require lyrics function

### ISSUE THREAD

**Issue by HeHeHeeeeee** [jellyfin/jellyfin#10919]
I hope to be able to obtain lyrics online or recognize the lyrics I have imported.

**Comment by HeHeHeeeeee** [comment]
To obtain online lyrics, I believe it is possible to have code contributors from different regions and countries write a web crawler program to crawl the lyrics of well done music streaming platforms in their countries and display them. Or you can call some interfaces for free music platform lyrics, I don't know what you think.

**Comment by felix920506** [comment]
Hi, there are a few problems with your issue report.
1. Crawling websites almost certainly violate TOSes and possibly even copyright law.
2. This is a feature request and should be directed to https://features.jellyfin.org/

Closing this as it is a feature request.
