### ISSUE TITLE
Repo unanavailable Error 403

### ISSUE THREAD

**Issue by bdydrp** [jellyfin/jellyfin#10925]
Was trying to sort out some image art that has not been loading and and saw some posts about plugins to help the process
However, when i put the Jellyfin repo in the respository, the catalogue remians empty
This is a screen grab from the logs:
![image](https://github.com/jellyfin/jellyfin/assets/63593828/47f9891c-9e0a-4838-997e-0ce5417891b0)
Any one else have issue grabbing from the official repo??
Cheers

**Comment by JPVenson** [comment]
Does the issue still persists?

**Comment by bdydrp** [comment]
For me, yes.
Have been trying to work out why the last few weeks..

Can't get it to update or load the catalogue

**Comment by JPVenson** [comment]
Can you invoke the url via your browser?

**Comment by bdydrp** [comment]
I can...
Not home right now. But can show screen shots later

**Comment by bdydrp** [comment]
Just to follow up
This i sfrom my repo page
![image](https://github.com/jellyfin/jellyfin/assets/63593828/029a8d8e-011d-4967-8633-b7892c1e6f49)
Clicking on cataloge, i get "no plugin available"

And small screenshot of wnen i access the repo link in browser
![image](https://github.com/jellyfin/jellyfin/assets/63593828/053b64e9-4586-4208-99b6-51dfcce028ea)


I do have jellyfin on a vlan, but that vlan has no issues in accessing the net.

**Comment by felix920506** [comment]
Welp this looks like not a Jellyfin problem either way.
I'm closing this as it is likely not a problem with Jellyfin.
Please head to our chatrooms or forum for troubleshooting help: https://jellyfin.org/contact

**Comment by bdydrp** [comment]
ok - Any ideas where to sart looking/investigating why i cant load the catalogue?
