### ISSUE TITLE
[Issue]: does not add new tv show episode to existing series

### ISSUE THREAD

**Issue by sney** [jellyfin/jellyfin#10921]
### Please describe your bug

Hi,

This issue is the same as #9896 but unlike that person I still have the affected file and can help with follow-up. 

In summary: 
- mkv of a new episode of a current TV show added to library
- jellyfin identified it as a separate show in "latest shows" with no artwork and a bare title from the filename 
- episode not visible under "shows"
- manually editing title or imdb id changed nothing, before or after metadata refresh

Slightly different is that the "media info" dialog does show full codec/stream details unlike the previous report.

On this jellyfin instance: 
- Shows are in their own library
- No other episodes of any other shows have the same problem

The theory from the last bug that metadata was missing on the provider doesn't seem to be right in this case, as the episode aired about a week ago, and themoviedb has it listed: https://www.themoviedb.org/tv/46648-true-detective/season/4/episode/2 (and so do tvdb and imdb) . Metadata providers are unchanged from jellyfin defaults.

Thanks for your work, and please let me know what other information you need to debug this! Screenshots below. 

sney

![Screenshot_20240127_132705](https://github.com/jellyfin/jellyfin/assets/5084670/8fe0ea59-c86f-4964-ab3c-c0de0c785e77)
![Screenshot_20240127_132721](https://github.com/jellyfin/jellyfin/assets/5084670/ef932e8e-b0b9-4a9b-9b25-a1f05685c557)
![Screenshot_20240127_132545](https://github.com/jellyfin/jellyfin/assets/5084670/1cf874c8-0f8d-4eb8-8e7e-4cf85f85bede)
![image](https://github.com/jellyfin/jellyfin/assets/5084670/53f8e318-3e47-4099-a933-bafd29e820a9)

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Debian 12
- Linux Kernel: 6.5.11-7-pve
- Virtualization: LXC
- Clients: Web, Windows Jellyfin Player
- Browser: Firefox 122
- FFmpeg Version: 5.1.4-2-bookworm (jellyfin)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MichaelRUSF** [comment]
Looks like you don't have show folders set up correctly based on your screenshot, see [documentation](https://jellyfin.org/docs/general/server/media/shows/). 

At a minimum, you should have something like this: 
TV
-- True Detective (2018)
-----True Detective S04E02.mkv

**Comment by sney** [comment]
Yes, that's correct, even putting it in an individual folder for the episode let jellyfin sort it correctly. Seems weird that it needs to be in a folder to parse text that it's clearly able to read, but I assume there's some reason for doing it this way. Sorry for the noise, carry on.
