### ISSUE TITLE
[Issue]: Episode order is not correct when TMDb is used as the metadata source

### ISSUE THREAD

**Issue by therloux** [jellyfin/jellyfin#10937]
### Please describe your bug

Shows on TMDb can have multiple episode lists/groups where each can have its own episode order. Jellyfin can use this information for the display order of episodes (e.g. Story Arc).

However, when Jellyfin uses TMDB, the episode order is not quite correct. Instead of ordering the episodes according to the display order the user selected, the episodes are listed according to the default order on TMDB. This problem only seems to affect the TMDb plugin.

### Jellyfin Version

10.8.z

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by soundsbyjs** [comment]
I'm having this issue as well. I would like to look into this. I also get this issue using a different setup -- I'm pretty sure this isn't just a bug with TMDb. Will update soon with what I find. 

Can you provide a set of instructions to reproduce the bug as you're experiencing it?

**Comment by soundsbyjs** [comment]
I see. Are you naming your files based on jellyfin's prescribed show naming scheme?

```Shows
├── Series Name A (2010)
│ ├── Season 00
│ │ ├── Some Special.mkv
│ │ ├── Series Name A S00E01.mkv
│ │ └── Series Name A S00E02.mkv
│ ├── Season 01
│ │ ├── Series Name A S01E01-E02.mkv
│ │ ├── Series Name A S01E03.mkv
│ │ └── Series Name A S01E04.mkv
│ └── Season 02
│ ├── Series Name A S02E01.mkv
│ ├── Series Name A S02E02.mkv
│ ├── Series Name A S02E03 Part 1.mkv
│ └── Series Name A S02E03 Part 2.mkv
└── Series Name B (2018)
├── Series Name B S01E01.mkv
├── Series Name B S01E02.mkv
├── Series Name B S02E01-E02.mkv
└── Series Name B S02E03.mkv```

**Comment by ChildishhAlbino** [comment]
@therloux I tried by TOMDB and TMDB before settling on TVDB via the Plugin. But I can see that TMDB has multiple DVD orderings (listed in the reference I provided) and it seems like it is just picking the first episode group of that type.

I can see episode groups that contain the ordering I expect but I cannot get the TMDB source to select it.

**Comment by ChildishhAlbino** [comment]
Hey @therloux, noted. It seemed like a similar issue based on the titling and description but not after additional explanation.

Created https://github.com/jellyfin/jellyfin/issues/11274
