### ISSUE TITLE
[Issue]:  Can't play trailer by using YouTube

### ISSUE THREAD

**Issue by DavidHenryThoreau** [jellyfin/jellyfin#10936]
### Please describe your bug

I'm using Firefox but can't access YouTube trailer : 

```
Page blocked

An error came during connexion to www.youtube.com

```

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Linux
- Linux Kernel: 
- Virtualization: No
- Clients: Linux
- Browser: Firefox
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL: http://media.my.jf.com
- Networking: NAT
- Storage: local
```

### Please attach any browser or client logs here
If F12 is enable i'm getting that error code : 

NS_ERROR_DOM_COEP_FAILED

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
Hi, this is an unsupported usecase.
Please head to our forums or chat rooms for help. https://jellyfin.log/contact
