### ISSUE TITLE
[Issue]: Removing folder from library doesn't remove media from list

### ISSUE THREAD

**Issue by dfyx** [jellyfin/jellyfin#10932]
### Please describe your bug

I had a library that takes media from two folders (lets call them A and B) and later decided to split it into two libraries. So I removed folder B from the original library and added a new library with only B.

**Expected behavior:**
Media files from folder B disappear from the original library either immediately or on the next rescan.

**Actual behavior:**
Media files from folder B still show up in the original library and there seems to be no way to remove them without removing them from disk.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Ubuntu 22.04.03 LTS
- Linux Kernel: 5.15.0-89-generic
- Virtualization: not used
- Clients: any
- Browser: any
- FFmpeg Version: 5.1.4-Jellyfin
- Playback Method: any
- Hardware Acceleration: VAAPI
- GPU Model: Intel N100 integrated
- Plugins: defaults plus Open Subtitles
- Reverse Proxy: traefik
- Base URL: none
- Networking: runs on bare metal
- Storage: local and NFS
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dfyx** [comment]
I found a solution with some help from *thedreadpirate* in chat.

Jellyfin keeps the library paths in `/var/lib/jellyfin/root/default/[libraryname]/*.mblink` files. For some reason, the file corresponding to the folder I removed from my library didn't get deleted correctly. Once I deleted it, a rescan correctly removed the movies from the library.

**Comment by be-nj** [comment]
I had the same issue, there was an ".mblink" file left over after removing one of two paths from one of my libraries which resulted in content of the removed path still showing up in that library. After deleting the (hidden) file .mblink and rescanning the library, the problem was solved.
