### ISSUE TITLE
[Issue]: laggy UI on tv.

### ISSUE THREAD

**Issue by fusk-l** [jellyfin/jellyfin#10942]
### Please describe your bug

On the TV, either Chromecast 4K or build into to TV.
I notice when I switch directories, or if I am returning to a directory, the UI freezes for a second while the movie background and folder content is overlayed on top of each other.
While the picture might not say much, i was able to take the picture because it stays like that for 1/2 seconds before continuing.

I can't figure out why this happening, but it does not feel smooth to operate, and the transitions lags.

Thanks for any assist.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: win10
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration: amf
- GPU Model: 5600G
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage: SSD
```

### Please attach any screenshots here

![VID20240201180608_exported_1583](https://github.com/jellyfin/jellyfin/assets/6765298/084bce54-0f9e-4390-bf77-39ad913b53eb)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by solidsnake1298** [comment]
Can you provide the full specs of your server?  Including the storage arrangement?

**Comment by fusk-l** [comment]
> Can you provide the full specs of your server? Including the storage arrangement?

2400G, 32gb ram, 5*2TB SSD for storage, OS on separate ssd.

**Comment by fusk-l** [comment]
I switched the 2400G out for a 5600G. The lag is still there, albeit  it does appear to be better. But smoothness still isn't good.
