### ISSUE TITLE
[Issue]: No playback activity shown in admin dashboard, preroll plugin suspected.

### ISSUE THREAD

**Issue by schumi4** [jellyfin/jellyfin#10943]
### Please describe your bug

After installing an setting up the [Local Intros plugin](https://github.com/BrianCArnold/jellyfin-plugin-intros) by @BrianCArnold, some users/clients acrivity is not shown in admin dashboard anymore. Playback on client side is unaffected by this. Sometimes it briefly shows the preroll as playing, but then the client goes into "seen x minutes ago" mode.

I consulted with another Jellyfin admin who is reporting the same issue after installing a preroll.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Debian 12
- Linux Kernel: latest in distro
- Virtualization: Docker
- Clients: Jellyfin Media Player
- Browser: Firefox
- FFmpeg Version: included
- Playback Method: direct
- Hardware Acceleration: -
- GPU Model: -
- Plugins: Local Intros
- Reverse Proxy: Caddy
- Base URL: -
- Networking: -
- Storage: -
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
I am fairly certain this is a client-specific issue, so each client that is experiencing this would need an issue created.

**Comment by schumi4** [comment]
Both cases happened on Jellyfin Media Player, [issue](https://github.com/jellyfin/jellyfin-media-player/issues/554) opened.

**Comment by BrianCArnold** [comment]
Developer of the plugin here, the way it (and any pre-roll plugin, like trailers etc) works is that the client requests the playlist for the requested item from the server with a flag as to whether it wants pre-rolls included.

The server queries any plugins that implement pre-roll provisioning for the list of pre-roll videos that it wants to include, and adds them to the beginning of the item playlist, with the actual requested item at the end, and sends that to the client.

The client is then responsible for reporting position information for each item in the playlist. 

I _**suspect**_ that there's an unexamined assumption in the client code that it only needs to report position data for the "only" item in the playlist data sent by the server, which is the pre-roll, and then continues to play the rest of the playlist.

**Comment by sevenrats** [comment]
moved to the issue linked above.
