### ISSUE TITLE
[Issue]: Music track embedded cover cannot be removed

### ISSUE THREAD

**Issue by Jamy-L** [jellyfin/jellyfin#10945]
### Please describe your bug

Hi, it seems that Jellyfin struggles with covers extracted from tracks, leading to situations where the only solution is to delete the library. In particular, if one activates the "Image extractor" as an audio image finder, the tracks will keep the cover forever. Deactivating the option and forcing library rescan won't change it.

Steps to reproduce:
1. Have an album that has tracks with embedded cover.
2. Activate the Image extractor and force library rescan. Individual songs should now have the embedded cover as expected.
3. Deactivate the image extractor and force library rescan. Optionally, load a new album cover from an online metadata provider.
4. The tracks are still represented with their old embedded cover, although the option has been disabled

I have experienced this issue on docker.
A similar issue was documented [on reddit](https://www.reddit.com/r/jellyfin/comments/oyvtu2/music_artwork_does_not_update_from_embedded_tag/?rdt=35990).

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: docker
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
Hi, you can work around this by using the metadata editor in the dashboard.

**Comment by Jamy-L** [comment]
Oh you are right, it is possible to remove individual tracks' cover from there, thank you.
However, I find it quite unintuitive that they do remain after a rescan; it leads to situations where one can manually update an album cover, yet the songs remain unchanged. The process of manually removing all of them is also considerably tedious.

I am not sure if this still qualifies as a bug or a feature request though

**Comment by sevenrats** [comment]
jellyfin is not really designed to change your media in place.  if things are embedded into the file itself, jellyfin is designed to just accept them.  if some of these tracks are corrupted or you don't want some of them, remove them out of band.

**Comment by felix920506** [comment]
Additional things I've experienced:
If I change the embedded album image of the files themselves, JF will keep the old cover image even if I manually delete said image.

**Comment by Jamy-L** [comment]
> jellyfin is not really designed to change your media in place. if things are embedded into the file itself, jellyfin is designed to just accept them. if some of these tracks are corrupted or you don't want some of them, you should remove them out of band. it may be possible to delete them and then "lock" the metadata, but I haven't tested this.

I do not mean that Jellyfin should replace the embedded cover, but rather be able to ignore it more consistently when required to do so. This is already partially supported, since it is possible to completely disable the "Image Extractor" for a library in the control pannel. I was pointing out that once the "Image Extractor" is enabled, the displayed cover of the track will become locked and wont change, even when disabling the Image Extractor.
I find it more intuitive and consistent if "Image Extractor disabled" meant "Ignore embedded covers completely".

There is also the question of metadata priority, since Jellyfin allows to prioritise metadata source. I stumbled on this issue because I wanted to prioritise the cover source as 1 - tadb ; 2- embedded. Albums that had no cover would fall back to the embedded cover. But then once a new cover is added online on tadb, the tracks would keep the embedded cover and not fetch from tadb as should be the prioritized choice.
