### ISSUE TITLE
[Issue]: Disable Folder view / folder images are not saved

### ISSUE THREAD

**Issue by Joly0** [jellyfin/jellyfin#10957]
### Please describe your bug

I would like to have a feature, to disable the folder/library view (also server wide). I have a certain folder structure with a main "Movies" folder and sub folders for different franchises, but i dont like, how they are showed as folders in the normal "Movie" library. Thats why i have "Collections". In "Movie" i only want to see movies, no folder structure. I have read somewhere, that there is an option, but i cant find it, and as far as i have read, it only applies per user. I want to disable that for all users

But if this isnt possible, then i also have a bug. Because when i set a certain picture for that franchise folder (for example a folder inside "Movies" called "Marvel Collection"), and i configure a specific image for that folder, it isnt preserved. After some time, the image is gone, and some random image of any random movie inside that folder is used for that folder. Why is this?

### Jellyfin Version

Other

### if other:

10.9.0

### Environment

```markdown
- OS: Unraid
- Linux Kernel: 6.1
- Virtualization: Docker
- Clients:
- Browser:
- FFmpeg Version: 6.0-jellyfin
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy: nginx
- Base URL:
- Networking: Brdige
- Storage: local
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
Hi, feature requests should be directed to https://features.jellyfin.org/

If you want to achieve a certain goal, another good place would be to ask in our forum or chat rooms. Links to those can be found here: https://jellyfin.org/contact/

**Comment by Joly0** [comment]
> Hi, feature requests should be directed to https://features.jellyfin.org/
> 
> If you want to achieve a certain goal, another good place would be to ask in our forum or chat rooms. Links to those can be found here: https://jellyfin.org/contact/

What do you mean with feature request? Where is this a feature request?
I have read, that there should already be a feature like i described, but it isnt there. And my second issue is 100% a bug, not a feature at all

**Comment by felix920506** [comment]
> Where is this a feature request?

> I would like to have a feature

> And my second issue is 100% a bug

You should not report multiple items in one report. If you do think it is a bug, then please open a new report containing ONLY that specific issue.
