### ISSUE TITLE
[Issue]: DLNA not working on jellyfin 10.8.13

### ISSUE THREAD

**Issue by 9thChasingWindGirl** [jellyfin/jellyfin#10953]
### Please describe your bug

DLNA cannot be detected by other devices.

### Jellyfin Version

Other

### if other:

10.8.13

### Environment

```markdown
- OS:Windows 11
- Linux Kernel:
- Virtualization:
- Clients:browser
- Browser:Chrome 
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:AMD 6900Xt
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:NAT
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
No information provided
