### ISSUE TITLE
[Issue]: Show disappeared after watching the end

### ISSUE THREAD

**Issue by CharlesCanlom** [jellyfin/jellyfin#10952]
### Please describe your bug

Steps to reproduce:
1. Play a video and reach to the end
2. The show is removed from the library automatically 

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Ubuntu Server 22.05
- Linux Kernel: 5.15.0-92-generic
- Virtualization: Docker
- Clients: Andoid
- Browser: 
- FFmpeg Version: 5.1.4-jellyfin
- Playback Method: Transcode
- Hardware Acceleration: NVENC
- GPU Model: GTX1060 6GB
- Plugins: AniDB, AudioDB, Cover Art Archive
- Reverse Proxy: none
- Base URL: none
- Networking: Docker
- Storage: Local
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cvium** [comment]
Not enough information. There's nothing in the server that does what you're describing. You probably have a third-party plugin installed or something.
