### ISSUE TITLE
[Issue]: SyncPlay doesn't remember Audio Track between episodes

### ISSUE THREAD

**Issue by kyleyee52** [jellyfin/jellyfin#10960]
### Please describe your bug

When going to the next episode in SyncPlay and a non-default audio track setting is selected for the current episode, the next episode will revert back to the default audio track.

However, this doesn't seem to happen with subtitles? They get remembered correctly.

Additionally, outside of SyncPlay, the preferred audio track correctly applies between episodes.

### Jellyfin Version

10.8.9

### Environment

```markdown
- OS: Windows 11
- Linux Kernel: none
- Virtualization: none
- Clients: Jellyfin Media Player
- Browser: Firefox
- FFmpeg Version: 
- Playback Method: Direct Play
- Hardware Acceleration: AMD AMF
- GPU Model: Radeon RX Vega 56
- Plugins: none
- Reverse Proxy: caddy
- Base URL: none
- Networking: Host
- Storage: local
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jmerdich** [comment]
Could this be the same issue as https://github.com/jellyfin/jellyfin-web/issues/3994? I have a PR out to fix that.

**Comment by kyleyee52** [comment]
@jmerdich I just tried out your PR but that didn't seem to fix the issue here. I haven't looked at the code myself but I imagine syncplay is handled differently.
