### ISSUE TITLE
[Issue]: `Mixed Movies and Shows` - Custom Images for folders are not being kept after a library scan

### ISSUE THREAD

**Issue by CarlMichaelFabe** [jellyfin/jellyfin#10966]
### Please describe your bug

I have a library setup with content type `Mixed Movies and Shows`, where series/movies within a franchise are organized into a single folder. I usually put custom `Primary` images to these folders.

But when a library scan happens, the custom images disappear and it reverts back to its old images.
Series or Movies with custom images are kept, only images of folders are reset.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Windows 11 23H2
- Linux Kernel: none
- Virtualization: none
- Clients: Browser, Jellyfin Media Player
- Browser: Firefox 122
- FFmpeg Version: 5.1.3
- Playback Method: Direct Play
- Hardware Acceleration: NVENC
- GPU Model: GTX1650
- Plugins: AniDB, AudioDB, Fanart, Jellyscrub, MusicBrainz, OMDb, Playback Reporting, Reports, Studio Images, TMDb, TheTVDB
- Reverse Proxy: none
- Base URL: none
- Networking: Host
- Storage: local
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TimGels** [comment]
Just to clarity, you have not enabled the option that it should replace images when doing the re-scan?

**Comment by CarlMichaelFabe** [comment]
Nope. It also does this whenever a periodic scan happens. I see the loading icon, and when I open the folder, the custom images are gone.
