### ISSUE TITLE
[Issue]: websocket requests always return "404 Not Found" if going through apache reverse proxy.

### ISSUE THREAD

**Issue by Pedro-MC** [jellyfin/jellyfin#10977]
### Please describe your bug

As the title says, all websocket requests return "404 Not Found" if going through the apache reverse proxy.

My setup is as follows:
- Jellyfin listens at localhost:8096 with a URL base set to /Jellyfin (http://localhost:8096/Jellyfin).
- apache serves as a reverse proxy for Jellyfin at https://example.com/Jellyfin
- valid Lets Encrypt certificate that passes validation tests

When loading http://localhost:8096/Jellyfin on a browser everything works, including the websocket connection with a bunch of "MessageType: keepAlive" json messages.

When loading https://example.com/Jellyfin on a browser almost everything works, the exception being the websocket connection that return a "404 Not Found".

The following is the websocket request and reply captured with wireshark:

> GET /Jellyfin/socket?api_key=SNIP&deviceId=SNIP HTTP/1.1
> Host: example.com
> User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:122.0) Gecko/20100101 Firefox/122.0
> Accept: */*
> Accept-Language: pt-PT,pt;q=0.8,en;q=0.5,en-US;q=0.3
> Accept-Encoding: gzip, deflate, br
> Sec-WebSocket-Version: 13
> Origin: https://example.com
> Sec-WebSocket-Extensions: permessage-deflate
> Sec-WebSocket-Key: h86dF45dFLHso0Ac/oRbvw==
> DNT: 1
> Sec-GPC: 1
> Sec-Fetch-Dest: empty
> Sec-Fetch-Mode: websocket
> Sec-Fetch-Site: same-origin
> Pragma: no-cache
> Cache-Control: no-cache
> X-Forwarded-For: 10.0.12.66
> X-Forwarded-Host: example.com
> X-Forwarded-Server: example.com
> Connection: Keep-Alive
> 
> HTTP/1.1 404 Not Found
> Content-Length: 0
> Date: Wed, 07 Feb 2024 23:34:22 GMT
> Server: Kestrel
> Access-Control-Allow-Origin: *
> X-Response-Time-ms: 3

The following is the apache configuration for the Jellyfin reverse proxy:

> <Location "/Jellyfin/socket">
>         <RequireAny>
>                 Require ip 127
>                 Require ip ::1
>                 Require ip 10.0
>                 Require ip fd00::/64
>         </RequireAny>
> 
>         SSLRequireSSL
> 
>         ProxyPreserveHost On
>         ProxyPass "ws://localhost:8096/Jellyfin/socket" 
>         ProxyPassReverse "ws://localhost:8096/Jellyfin/socket"
> </Location>
> 
> <Location "/Jellyfin">
>         <RequireAny>
>                 Require ip 127
>                 Require ip ::1
>                 Require ip 10.0
>                 Require ip fd00::/64
>         </RequireAny>
> 
>         SSLRequireSSL
> 
>         ProxyPass "http://localhost:8096/Jellyfin" 
>         ProxyPassReverse "http://localhost:8096/Jellyfin"
> </Location>

### Jellyfin Version

10.8.z

### if other:

10.8.13

### Environment

```markdown
- OS: Mageia 9 (GNU/Linux x86_64)
- Linux Kernel: 6.6.14-desktop-1.mga9
- Virtualization: No
- Clients: Web Client
- Browser: Firefox
- FFmpeg Version: ffmpeg version 5.1.4-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
- Playback Method: Transcode
- Hardware Acceleration: VAAPI
- GPU Model: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller
- Plugins:
- Reverse Proxy: yes using Apache
- Base URL: /Jellyfin
- Networking: LAN
- Storage: local
```

### Please attach any browser or client logs here

GET wss://example.com/Jellyfin/socket?api_key=SNIP&deviceId=SNIP [HTTP/1.1 404 Not Found 30ms]

Estado 404 Not Found
Versão HTTP/1.1
Transferido 307 B (tamanho 0 B)
	
Access-Control-Allow-Origin
	*
Connection
	Keep-Alive
Content-Length
	0
Content-Security-Policy
	upgrade-insecure-requests
Date
	Wed, 07 Feb 2024 23:35:29 GMT
Keep-Alive
	timeout=5, max=100
Server
	Kestrel
Strict-Transport-Security
	max-age=63072000
X-Response-Time-ms
	0
	
Accept
	*/*
Accept-Encoding
	gzip, deflate, br
Accept-Language
	pt-PT,pt;q=0.8,en;q=0.5,en-US;q=0.3
Cache-Control
	no-cache
Connection
	keep-alive, Upgrade
DNT
	1
Host
	example.com
Origin
	https://example.com/
Pragma
	no-cache
Sec-Fetch-Dest
	empty
Sec-Fetch-Mode
	websocket
Sec-Fetch-Site
	same-origin
Sec-GPC
	1
Sec-WebSocket-Extensions
	permessage-deflate
Sec-WebSocket-Key
	VXlcDxcdtHYhJRuF/jsTOA==
Sec-WebSocket-Version
	13
Upgrade
	websocket
User-Agent
	Mozilla/5.0 (X11; Linux x86_64; rv:122.0) Gecko/20100101 Firefox/122.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
Hi, please go to our forum or chat rooms for troubleshooting help. https://jellyfin.org/contact
