### ISSUE TITLE
Fritzbox guest network access?! Why?!

### ISSUE THREAD

**Issue by Snipy2k4** [jellyfin/jellyfin#10986]
Hello,

I have a current Jellyfin server running on a Win11 PC. This is on my regular home network. I added the port to the shares on the home network.

I have connected various devices to a WiFi guest network.

The home network has the local IP's of 192.168.0.x
The guest network has the specified local IP'S of 192.168.179.x

Now here comes something that I don't understand.

Normally, the regular home network should be separate from the guest network, but if I enter the IP:Port on devices in the guest network, I can connect from the guest network to the Jellyfin server in the home network. Should that be so?!

How can that be?! Can someone please explain to me why this is the case or whether it is a security hole?

Thanks

Greetings

Snipy2k4

**Comment by solidsnake1298** [comment]
This is not a Jellyfin issue.  Jellyfin cannot make your router do anything it can't do with other apps.

But, FWIW, your router is probably configured (or misconfigured) to bridge the two subnets.

**Comment by Snipy2k4** [comment]
I reset my FritzBox 6690 and without changing any settings, only the WiFi guest network and port sharing for Jellyfin were activated and I can access the Jellyfin server in the home network from the guest network.

But what I can observe is that if I delete the port sharing, Jellyfin can no longer be reached from the guest network.

I'm very surprised that this has nothing to do with jellyfin...

There must be some connection here...

**Comment by solidsnake1298** [comment]
The only thing I can think of is that Jellyfin can use uPnP to automatically create port forwarding rules on your router.  And that your router is allowing the guest network to access Jellyfin when the port forwarding rule is present.  I don't recall if automatic port mapping is on by default in jellyfin.  If you don't access Jellyfin outside of your network, you can turn off automatic port mapping.

FWIW, this function is not unique to Jellyfin.  Most multiplayer video games implement uPnP.

**Comment by felix920506** [comment]
Hi, please head to our forum or chat rooms for troubleshooting help: https://jellyfin.org/contact

**Comment by Snipy2k4** [comment]
Hello,

thanks for the reply. UPnP is off by default on Jellyfin and I deactivated it again in the Fritzbox to reproduce it, restarted it, but unfortunately it had no effect.

The only thing I was able to reproduce is setting up manual port forwarding. If this is active, the Jellyfin server can be reached from the normal network via IP:PORT. If I deactivate port forwarding (which is actually intended for access from the Internet), I cannot reach the Jellyfin server.

According to AVM (manufacturer of the Fritzbox), the entire network should function separately from the guest network and there should be no connection.

I'm really wondering why this is possible

The IP range of the regular network from the default setting of the Fritzbox is 192.168.178.x from the guest network 192.168.178.x. Both with 255.255.255.0 subnet mask.

I'm really at a loss because this is a major security gap and therefore calls the entire guest network and its security into question.

**Comment by solidsnake1298** [comment]
If your router sends a request to Jellyfin, even if it shouldn't, Jellyfin will respond.  Again, Jellyfin can't make your router do anything it wouldn't otherwise do.

Take this up with Fritzbox/AVM.  Update the firmware?

**Comment by Snipy2k4** [comment]
The firmware is up to date, I flashed it again and reset the Fritzbox to rule out setting errors.

I simply assumed that the guest network was separate from the regular network and couldn't be easily overridden by simple port sharing because the devices weren't actually supposed to communicate.

I will definitely talk to AVM and test other server applications to see whether they can also be reached from the guest network with a normal forwarding for the internet.

thank you for your time

**Comment by Snipy2k4** [comment]
Hello,

I received an answer from AVM that I would like to share with you:

**"Thank you for your inquiry to AVM Support.
 
If I understand your query correctly based on my colleague's notes, it means that you see a security problem with the FRITZ!Box because you can access a device in the home network from the guest network for which port sharing is enabled.
 
The behavior is to be expected and does not represent a security problem. Because port sharing is set up, the device can be reached as expected from both the WAN/Internet and the guest network.
 
This is exactly what port sharing is intended for: to reach a device externally.
 
I hope that the information helps you and I wish you a pleasant week.
 
Kind regards from Berlin"**

It seems that by opening the port, the local guest network also negotiates the service or traffic locally in order to conserve bandwidth.
