### ISSUE TITLE
[Issue]: Jellyfin on Android TV player does not remember chosen sub on resume.

### ISSUE THREAD

**Issue by fusk-l** [jellyfin/jellyfin#10989]
### Please describe your bug

Every time i resume a media, the player does not remember which subtitles were chosen and i have to manually select subtitles again. I believe i remember this was not an issue in earlier versions.

### Jellyfin Version

10.8.z

### Environment

Android tv.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JPVenson** [comment]
Hey,
Although this is a bug, its known for AndroidTV and a few other clients to have this undesired behavior.
Please check in the appropriate repro if there is already a bug and if there is not create one there.
