### ISSUE TITLE
hasOfficialRating=true filter in API returning items without rating

### ISSUE THREAD

**Issue by nielsvanvelzen** [jellyfin/jellyfin#10983]
### Please describe your bug

When using the `hasOfficialRating` filter in the API the server will return items that have no rating. From my understanding it will apply the filter here:

https://github.com/jellyfin/jellyfin/blob/20f05f8103c2f5447c3d2ebd319c9ad31857d42e/Emby.Server.Implementations/Data/SqliteItemRepository.cs#L3852-L3859

But we also support a few values that imply no rating:

https://github.com/jellyfin/jellyfin/blob/20f05f8103c2f5447c3d2ebd319c9ad31857d42e/Emby.Server.Implementations/Localization/LocalizationManager.cs#L29

I discovered this bug when I filtered items with `maxOfficialRating=PG-G` and `hasOfficialRating=true`, which should've returned nothing (because my media not for babies). But it did return 1 item with the rating set to "Not Rated".

Tested with 10.8 but I believe the issue also exists in 10.9

### Jellyfin Version

10.8.z

### if other:

10.8.13

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shadowghost** [comment]
`hasOfficialRating` checks for the existence of the unprocessed rating string - e.g. `PG-13` or `unapproved` or whatever the providers returned.

What you want to use is `hasParentalRating` which checks for the existence of a processed RatingLevel for the `OfficialRating` string, meaning anything not mapped by any of our rating systems will be excluded.
