### ISSUE TITLE
[Issue]: Watched status gets removed from episode if was starts playing.

### ISSUE THREAD

**Issue by Neinei0k** [jellyfin/jellyfin#10984]
### Please describe your bug

If you start playing already watched episode but stop, its watched status gets removed. Additionally, if you then manually set its watched status, it messes up Next Up, which now have the next episode in it. I have not found any way to fix it.

I would expect, that if an episode was played for shorter amount of time that is required for it to appear in Continue Watching list, it also should not modify the watched status. I don't even think, it makes sense to remove watched status from an episode or movie by playing it. The only reasons to remove watched status should be either, if user did that manually, or synchronization.

Also, ideally, the user should be able to manually add or remove episodes from Next Up.

### Jellyfin Version

Other

### if other:

10.8.13

### Environment

```markdown
- OS:Linux Mint 21.2
- Linux Kernel: 6.5.0-17-generic x86_64
- Clients: Jellyfin Media Player
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
Please don't report two issues in one report.

**Comment by Neinei0k** [comment]
> Please don't report two issues in one report.

I reported a single issue. The rest is additional information and suggestions.
