### ISSUE TITLE
[Issue]: Movies in different libraries considered as same

### ISSUE THREAD

**Issue by yaneony** [jellyfin/jellyfin#10985]
### Please describe your bug

In my Jellyfin configuration, I've categorized content into different libraries by language, creating separate collections for German, English, and Russian movies. Each library is uniquely labeled and includes movies with titles translated into the corresponding language. However, I encounter a problem when I start watching a movie in any language: Jellyfin incorrectly identifies it as the same entity as its language variants. This results in all language versions being displayed in the "Continue Watching" section, with the viewing progress erroneously synced across two or three different language versions, despite having watched only one.

Is this behavior intentional, or is there a configuration option in Jellyfin to recognize these as distinct films? This issue also occurs with TV series.
![GV4XGZ52](https://github.com/jellyfin/jellyfin/assets/12472001/33091450-924c-44bb-b537-15dc7b90dcb6)

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS:
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
Are these libraries sharing the same storage path?

**Comment by crobibero** [comment]
This is an existing feature request: https://features.jellyfin.org/posts/2362/fix-watch-status-in-the-db-for-the-same-media-in-different-libraries
