### ISSUE TITLE
Docker Jellyfin does not delete media from disk

### ISSUE THREAD

**Issue by SenorSmartyPants** [jellyfin/jellyfin#1099]
**Describe the bug**
When told to delete a series, series removed from JF but is not deleted from disk.

**To Reproduce**

1. Go to TV Shows
2. Click on ellipses and then delete media 

**Expected behavior**

Series should be removed from JF (it is) and deleted from disk.

**Logs**

No errors are reported in the log.
```
jellyfin        | 2019-03-12T21:36:00.199173180Z [16:36:00] [INF] HTTP DELETE http://nanners:8196/emby/Items/9134f71d7e5883e3066b8aa242bc3c47. UserAgent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
jellyfin        | 2019-03-12T21:36:00.241404008Z [16:36:00] [INF] Deleting item, Type: Series, Name: The Simpsons, Path: /media/Videos/New/Tv/The Simpsons, Id: 9134f71d-7e58-83e3-066b-8aa242bc3c47
jellyfin        | 2019-03-12T21:36:00.368459506Z [16:36:00] [INF] HTTP Response 204 to 192.168.1.250. Time: 170ms. http://nanners:8196/emby/Items/9134f71d7e5883e3066b8aa242bc3c47
jellyfin        | 2019-03-12T21:41:32.052683627Z [16:41:32] [INF] HTTP DELETE http://nanners:8196/emby/Items/d16380fdd98bfc42e45bf9b089c67245. UserAgent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Geko) Chrome/72.0.3626.121 Safari/537.36
jellyfin        | 2019-03-12T21:41:32.060998611Z [16:41:32] [INF] Deleting item, Type: Series, Name: SMILF, Path: /media/Videos/New/Tv/SMILF, Id: d16380fd-d98b-fc42-e45b-f9b089c67245
jellyfin        | 2019-03-12T21:41:32.138103547Z [16:41:32] [INF] HTTP Response 204 to 192.168.1.250. Time: 85ms. http://nanners:8196/emby/Items/d16380fdd98bfc42e45bf9b089c67245
```

**System (please complete the following information):**
 - OS: Docker ARMHF
 - Browser: [Chrome]
 - Jellyfin Version: [e.g. 10.2.2]

**Comment by Mountaineer1024** [comment]
Whilst having an option to do this and renaming etc would great, NOT destroying files would be a sane default.

IMO.

An honestly better fix here would be to rename the jellyfin message from delete to "de-list".

**Comment by SenorSmartyPants** [comment]
Is there a queued delay on deleting media? I'm not sure why yet, but one file was deleted when I wasn't manually doing delete tests with JF. Going to try testing this again.

If there is a queued delete process, I'd like the option for filesystem deletes to happen immediately, just like when the media is removed from the JF library

**Comment by SenorSmartyPants** [comment]
Selecting an individual episode and deleting it works. It deletes the file immediately from the file system.

Selecting the series and delete media does not delete any files. The series I have been using to test this have been the following layout

Series/Series 1x01.mp4

and not with a seasons directory like this

Series/Season 1/Series 1x01.mp4

if that makes a difference.

Once all the episodes are individual deleted, there's still an empty series folder which can cause other issues. See #608
