### ISSUE TITLE
[Issue]: Wrong MIME type returned for different comic book formats

### ISSUE THREAD

**Issue by rluetzner** [jellyfin/jellyfin#11009]
### Please describe your bug

As described in https://github.com/jellyfin/jellyfin-plugin-opds/issues/38 , I noticed that the current MIME type implementation does not account for different comic book formats. It will always return `application/x-cbr`.

Sadly `cbr` (a.k.a. Rar) is a proprietary compression algorithm, so most FOSS eReaders won't be able to download or display such files.

I couldn't pinpoint the exact place where this goes wrong, but I noticed that this case is not covered by the tests in `MimeTypeTests.cs`. However, I also couldn't find a place where `x-cbr` is explicitly set, so I'm still not sure where this bug is coming from.

### Reproduction Steps

Is reproducible by adding `cbr` and `cbz` to the `MimeTypesTests` class like this:

```csharp
        [InlineData(".cbr", "application/x-cbr")]
        [InlineData(".cbz", "application/x-cbz")]
```

```text
[xUnit.net 00:00:00.73]     Jellyfin.Model.Tests.Net.MimeTypesTests.GetMimeType_Valid_ReturnsCorrectResult(input: ".cbz", expectedResult: "application/x-cbz") [FAIL]
  Fehler Jellyfin.Model.Tests.Net.MimeTypesTests.GetMimeType_Valid_ReturnsCorrectResult(input: ".cbz", expectedResult: "application/x-cbz") [1 ms]
  Fehlermeldung:
   Assert.Equal() Failure: Strings differ
                           ↓ (pos 16)
Expected: "application/x-cbz"
Actual:   "application/x-cbr"
                           ↑ (pos 16)
```

### Jellyfin Version

10.8.13

### Environment

```markdown
- OS:
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
-
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nielsvanvelzen** [comment]
You can look at #10980 to see how to update the mime type mappings.

**Comment by rluetzner** [comment]
Thanks @nielsvanvelzen . I'll get to work, depending on the answer I get to https://github.com/khellang/MimeTypes/issues/23 . :slightly_smiling_face: 

It's actually a bug in the MimeTypes package Jellyfin uses, so I'd rather have it fixed there and have other projects benefit from this as well.

Thanks for the quick response.

**Comment by felix920506** [comment]
I think you would get a quicker fix by fixing it on the JF side, given that the last commit on upstream is from 9 months ago

**Comment by rluetzner** [comment]
Thanks for the advice @felix920506 . I did both. :slightly_smiling_face:
