### ISSUE TITLE
20240212.4-unstable Music - Underscore in artist name breaks access to albums

### ISSUE THREAD

**Issue by rwrozelle** [jellyfin/jellyfin#11006]
### Please describe your bug

Music Artist name containing "_" does not work in Jellyfin

This folder structure works (I can see album and play songs):
America
  America-The_Complete_Greatest_Hits
    01.A_Horse_With_No_Name.flac

This folder structure does not work
Al_Green
  Al_Green-Greatest_Hits
    01.Tired_of_Being_Alone.flac

### Reproduction Steps

1.  Environment - Linux odroidhc4 6.1.11-meson64 #23.02.2 SMP PREEMPT Sat Feb 18 00:07:55 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
2. Music library is on HDDs mounted on server.
Duplicate folder structure in description and you'll see the problem with any artist with underscores "_" in name.

### Jellyfin Version

Unstable (master branch)

### Environment

```markdown
- OS: Armbian 23.02.2 Focal
- Linux Kernel: Linux 6.1.11-meson64
- Virtualization:
- Clients: Chrome, Roku
- Browser: 121.0.6167.161
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration: No
- GPU Model: odroidhc4
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage: local
```

### Jellyfin logs

```shell
Overall issue
```

### Please attach any screenshots here

<img width="958" alt="Al_Green" src="https://github.com/jellyfin/jellyfin/assets/8890259/2ba79f96-9f95-4a65-8cd9-3265099eb27a">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rwrozelle** [comment]
Manual Workaround is to go into each artist and update the "Title" to remove underscores.  This can take a lot of time for a large music library.

**Comment by solidsnake1298** [comment]
Can't reproduce with this folder structure.

`testmusic/Marina_and_The_Diamonds/Electra_Heart/02.Primadonna.flac`

However, my music is fully tagged.  Can you confirm that your music is ID3 tagged?

**Comment by rwrozelle** [comment]
There aren't any tags.  My music library is created using abcdef on my Linux server.  I've traced the issue to this.  When the Artist metadata was auto-created, the Title attribute has underscores.  But when the Album metadata is auto-created the People attribute (a list) was created without underscores.  So my fix was to manually remove the underscores from the Title attribute.  Also found that "-" also has to be updated in Title to get the album match.  I've had this library for a while, so not sure if this is an original issue, or showed up as part of unstable.
