### ISSUE TITLE
Multichannel audio are not downmixed/transcoded when the file can be directly played

### ISSUE THREAD

**Issue by MichaelRUSF** [jellyfin/jellyfin#11002]
### Please describe your bug

Multichannel audio in MP4 containers are not downmixed when the "Maximum Allowed Audio Channels" setting is set to Stereo in the playback menu. 

In the attached server [log ](https://github.com/jellyfin/jellyfin/files/14250465/Server.log.mp4.txt) I played two identical files, the only difference is the container. The 5.1 MKV container downmixed as expected, but the 5.1 MP4 container played directly without transcoding. This was on the webUI using Edge. I also tested with AC3 MP4 media and I had the same results. 

This seems to be the likely cause of several reports on the Android forum such as [1286](https://github.com/jellyfin/jellyfin-android/issues/1286), [953](https://github.com/jellyfin/jellyfin-android/issues/953), [1182.](https://github.com/jellyfin/jellyfin-android/issues/1182) 

### Reproduction Steps

1. Go to playback settings and set max audio channels to stereo.
2. Attempt to play 5.1[ AAC media ](https://www2.iis.fraunhofer.de/AAC/ChID-BLITS-EBU.mp4) in an mp4 container using the webUI
3.  Notice that the media plays directly without downmixing/transcoding to 2.0 audio

### Jellyfin Version

10.8.13

### Environment

```markdown
- OS:Windows 11 22H2
- Virtualization:No
- Browser:Edge 121
- FFmpeg Version:5.1.4-3
```

### Jellyfin logs

```shell
Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile="Anonymous Profile", Path="H:\Media\Samples\AAC\AAC 5.1 mp4.mp4", AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=DirectPlay, TranscodeReason=0 ) "media:/videos/668589b4-dd2d-18b2-2679-6c2221cbd614/stream.mp4?MediaSourceId=668589b4dd2d18b226796c2221cbd614&Static=true&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=1&api_key=<token>&SubtitleMethod=Encode&Tag=c1172c4fd91c496d3c4d552ae7077afc"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gnattu** [comment]
This should be moved to the web repo since the user-applied MaxAudioChannels setting is only applied to transcoding profiles by the web client. For direct play profiles, it always reports the maximum audio channels it detects. I'm not sure if this is the intended behavior, though.

**Comment by MichaelRUSF** [comment]
Closing in favor of issue  [#5715](https://github.com/jellyfin/jellyfin-web/issues/5715)
