### ISSUE TITLE
[Issue]: When using Video type ISO extras do not show up

### ISSUE THREAD

**Issue by raldone01** [jellyfin/jellyfin#11017]
### Please describe your bug

I have the following folder structure:
```
'Movie Name (Year) [imdbid-tt***]'
├── BDMV
├── 'behind the scenes'
├── 'deleted scenes'
└── shorts
```

Sadly the extras do not show up.
When I copy them to other movies they show up.
The movie plays fine.

### Reproduction Steps

Add extras to a Video type ISO movie.
They won't show up.

### Jellyfin Version

Unstable (master branch)

### Environment

```markdown
Docker container built from Dockerfile with commit 2bd85df383ec70251a8cdf9802963e29b52b60a4
```

### Jellyfin logs

```shell
No relevant logs.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shadowghost** [comment]
ISOs, BDMV and DVD folders do currently not support extras to my knowledge. This is a technical limitation and therefore not a really a bug.
