### ISSUE TITLE
Provide an ACL for Users/Libraries

### ISSUE THREAD

**Issue by Nickbert7** [jellyfin/jellyfin#1102]
**Describe the feature you'd like**
As we curently have no groups to manage users, I'd like to have an access control list to manage library access.

If you have a lot of libraries or/and a lot of users, it is difficult to manage the rights or the have an overview on who has access to which library.

![image](https://user-images.githubusercontent.com/14938497/54282664-c55e0a00-459c-11e9-80e6-483c0cfc0894.png)

**Comment by EraYaN** [comment]
This is probably something that would happen after user group support, which probably has to wait until the database migration. And LDAP might come before it, cause then you can use all the tools to manage that, which are plentiful and pretty nice. But yes it's really required.

**Comment by Nickbert7** [comment]
I thought it woud be a nice feature until we have the groups.
When the groups are here, it will not be such a big problem to keep an overview on who is allowed to access what.

I don't know how difficult it would be to display the lists of the user-edit-screen next to each other for all users in one page:

![IMG_20190313_212920](https://user-images.githubusercontent.com/14938497/54312444-4afeab80-45d7-11e9-9fc9-a394fbddb1bf.jpg)
