### ISSUE TITLE
[Issue]: ActivityLog/Entries does not yield ItemId's

### ISSUE THREAD

**Issue by rubdos** [jellyfin/jellyfin#11023]
### Please describe your bug

Looking at the output of the `ActivityLog/Entries` API, I am never seeing any `ItemId` in the output. Nonetheless, the code seems to indicate this is set in the database, for example in the [`PlaybackStartLogger`](https://github.com/jellyfin/jellyfin/blob/4d93f067320a83acd76f445fb0aabf828922e140/Jellyfin.Server.Implementations/Events/Consumers/Session/PlaybackStartLogger.cs#L71):

```cs
await _activityManager.CreateAsync(new ActivityLog(
    string.Format(
        CultureInfo.InvariantCulture,
        _localizationManager.GetLocalizedString("UserStartedPlayingItemWithValues"),
        user.Username,
        GetItemName(eventArgs.MediaInfo),
        eventArgs.DeviceName),
    GetPlaybackNotificationType(eventArgs.MediaInfo.MediaType),
    user.Id)
{
    ItemId = eventArgs.Item?.Id.ToString("N", CultureInfo.InvariantCulture),
})
```

Example output from the API:
```json
{
  "Id": 17340,
  "Name": "xxx speelt xxx af op Chrome",
  "Type": "VideoPlayback",
  "Date": "2024-02-13T19:00:05.9026692Z",
  "UserId": "xxx",
  "Severity": "Information"
}
```

Additionally, it would be useful to also add the `ItemId` when logging a download. My C# is not on point, but something like this might work towards that:

```diff
diff --git a/Jellyfin.Api/Controllers/LibraryController.cs b/Jellyfin.Api/Controllers/LibraryController.cs
index e357588d1..1618cd5b9 100644
--- a/Jellyfin.Api/Controllers/LibraryController.cs
+++ b/Jellyfin.Api/Controllers/LibraryController.cs
@@ -913,6 +913,7 @@ public class LibraryController : BaseJellyfinApiController
                 User.GetUserId())
             {
                 ShortOverview = string.Format(CultureInfo.InvariantCulture, _localization.GetLocalizedString("AppDeviceValues"), User.GetClient(), User.GetDevice()),
+                ItemId = item.Id.ToString("N", CultureInfo.InvariantCulture),
             }).ConfigureAwait(false);
         }
         catch
```

### Reproduction Steps

Call the `/System/ActivityLog/Entries` API and search for any `VideoPlayback` options.

### Jellyfin Version

10.8.13

### Environment

```markdown
- OS: Fedora 38
- Linux Kernel: 6.6.12-100.fc38.x86_64
- Virtualization: no
- Clients: various
- Browser: various
- FFmpeg Version: 6.0.1
- Playback Method: browser (but n/a)
- Hardware Acceleration: n/a
- GPU Model: n/a
- Plugins: Kodi sync queue, Trakt, TVHeadend
- Reverse Proxy: yes, nginx
- Base URL: none
- Networking: host/native v4+v6 dual stack
- Storage: btrfs
```

### Jellyfin logs

```shell
n/a, I think
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
I just tested the `/ActivityLog/Entries` endpoint on master and the ids are being returned.
PR created for the missing ItemId attachment

**Comment by crobibero** [comment]
That commit isn't in the 10.8 branch
https://github.com/jellyfin/jellyfin/blob/release-10.8.z/Jellyfin.Server.Implementations/Events/Consumers/Session/PlaybackStartLogger.cs

**Comment by rubdos** [comment]
> That commit isn't in the 10.8 branch

I literally just now realized that by checking the `git log`; sorry for the noise, and thanks for the help!
