### ISSUE TITLE
[Issue]: Can't (re)add specific movie to the library

### ISSUE THREAD

**Issue by Maypul** [jellyfin/jellyfin#11030]
### Please describe your bug

Hello.

I have hit the watcher limit when adding a movie and fixed it by extending watcher number on host system, now, I can add any new movie to the library again.

The error limit: System.IO.IOException: The configured user limit (8192) on the number of inotify watches has been reached, or the operating system failed to allocate a required resource.

But the movie that triggered the error, can't be readded. It was also never added in the first place, it does not appear in library.

The best I can do with this move, is generate following enttry in the logs when I move its folder outside of the library:
2024/02/18 11:11:17 stdout [11:11:17] [INF] [36] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: Movie, Name: Smokin' Aces, Path: /Media/Movies/Smokin' Aces (2006)/Smokin' Aces.mkv, Id: f35c8bec-46b0-ffb3-c948-c1f39d66f4bb

But when I readd it back, scan, nothing happens, no logs, movie is not added.

Checking library.db in DBBrowser for SQLite it seems the entry is here:
![image](https://github.com/jellyfin/jellyfin/assets/98578889/5951a01b-58c5-4895-8e70-86edeb793c8c)

It is some kind of corruption? How would I go about making the Jellyfin to add the movie successfully so it's showing in the library?

### Reproduction Steps

1. Hit error "The error limit: System.IO.IOException: The configured user limit (8192) on the number of inotify watches has been reached, or the operating system failed to allocate a required resource." when adding a movie
2. Fix the error, confirm by adding another movie
3.  Try to add/readd the movie that trigerred the error

### Jellyfin Version

10.8.13

### Environment

```markdown
- OS:Synology OS
- Model: DS1821+
- Version: DSM 7.2.1-69057 Update 4
```

### Jellyfin logs

```shell
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Maypul** [comment]
After adding around 10 new movies, this one still can't be "removed" or readded. If in logs there is info about it being removed, it is still kept in database which I guess is the reason it can't be added in the first place (and does not show in Jellyfin)

**Comment by sevenrats** [comment]
as a temporary workaround, try adding a .ignore file to the movie directory and rescanning the library. this should remove it.

**Comment by Maypul** [comment]
I think it might have helped, though there was no logs of its removal, the movie reappeared in the order it was firstly added, so about 20 movies earlier and now it's showing in Jellyfin. Thanks
