### ISSUE TITLE
[Issue]: Webhook structure is very suboptimal

### ISSUE THREAD

**Issue by iloveicedgreentea** [jellyfin/jellyfin#11059]
### Please describe your bug

JF primarily sends

* Play
* Stop
* Scrobble
* Progress

This is really suboptimal from an events processing standpoint. 

Plex meanwhile primarily sends
* Play
* Pause
* Resume
* Scrobble

Jellyfin should directly send pause and resume instead of progress with an is paused flag. 

### Reproduction Steps

Enable webhooks, enable playbackProgress

### Jellyfin Version

10.8.13

### Environment

```markdown
- OS: Unraid
- Clients: Web, mobile
```

### Jellyfin logs

```shell
n/a
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
Feature requests should be made at https://features.jellyfin.org

Closing as feature request
