### ISSUE TITLE
[Issue]: Music freezing and artifacts in Android app

### ISSUE THREAD

**Issue by geriko2000** [jellyfin/jellyfin#11070]
### Please describe your bug

When playing music through an Android application, playback artifacts are often heard. Also, after listening to 1-10 tracks, playback stops at a random point in the track (while loading proceeds correctly). Playback can be continued by restarting the application, but soon the same problems appear again. There are no such problems when playing through a browser. All logs in backend without errors

Device: Samsung S23U
Android version: 14

### Reproduction Steps

1. Run Android app
2. Choose track from album
3. Listen tracks

### Jellyfin Version

Unstable (master branch)

### Environment

```markdown
Server
- OS: Ubuntu 22.04
- Linux Kernel: 
- Virtualization:
- Clients: Android
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
Cant see in android app
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
This report is being closed as invalid for the following reasons:
1. 2 issues are being reported in one report. Audio Artifacts and Playback randomly stopping are 2 separate issues. Please open 2 separate reports for 2 separate issues.
2. Almost no information is provided apart from the OS version. We do not know what exact environment you are running Jellyfin and how you are running Jellyfin. Without this information, we cannot troubleshoot.
3. Jellyfin logs are not provided. The logs can be found in the dashboard through the WebUI.

Please keep the above points in mind and open new issues.
