### ISSUE TITLE
[Issue]: Live-TV - There was an error saving the TV provider

### ISSUE THREAD

**Issue by TheHellSite** [jellyfin/jellyfin#11085]
### Please describe your bug

Saving any type of Live-TV configuration results in the following error:
`Alert: There was an error saving the TV provider. Please ensure it is accessible and try again.`

Apart from the error above everytime I hit "Save" the log entry below gets created:
`[INF] [35] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was forbidden.`

It is not a permission issue between the jellyfin user and the m3u file, since it is stored in the same directory as the other media files.
Not even with the user jellyfin as the owner of the file the M3U Tuner configuration can be saved.
It is also not a firewall permission issue since the LXC running jellyfin is allowed to access the DVB-C tuner, can ping it, download the m3u file using curl, ...

The same error also appears if I try to save ...
- a random IP:Port combination as a HD Homerun tuner.
- the "[LegalStream Live News Playlist](https://raw.githubusercontent.com/notanewbie/LegalStream/master/packages/news/live.m3u8)", referenced in the Jellyfin Live-TV setup guide.

Therefore I think there is some sort of internal error in Jellyfin.
I even found a closed GitHub issue wich could be related to my issue but has not been answered by any dev: https://github.com/jellyfin/jellyfin/issues/9203

### Reproduction Steps

1. Go to: Jellyfin --> Administration --> Live-TV
2. Add Tuner --> f.e. M3U Tuner
3. Provide the path to the m3u file --> f.e. https://raw.githubusercontent.com/notanewbie/LegalStream/master/packages/news/live.m3u8 --> press Ok
4. Hit Save.
5. "Alert: There was an error saving the TV provider. Please ensure it is accessible and try again."

### Jellyfin Version

10.8.13

### Environment

```markdown
- OS: Arch Linux x86_64 (latest updates)
- Linux Kernel: 6.5.11-7-pve
- Virtualization: LXC
- Clients: Browser
- Browser: Firefox 123.0
- FFmpeg Version: jellyfin-ffmpeg-1:6.0.1p1-2
- Playback Method: none
- Hardware Acceleration: VA-API
- GPU Model: AMD APU Ryzen 3 PRO 4350G
- Plugins: none/default
- Reverse Proxy: HAProxy
- Base URL: none
- Networking: direct
- Storage: local
```

### Jellyfin logs

```shell
[2024-02-12 15:55:46.503 +01:00] [INF] [35] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was forbidden.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
Closing as invalid ![image](https://github.com/jellyfin/jellyfin/assets/25688628/223c9161-d8a3-4620-ab27-97508988d4e0)

**Comment by TheHellSite** [comment]
I am sorry but this issue clearly has nothing to do with the any of the before/after log entries.

But fine, I will create the exact same issue with a longer log even though the extended length will be of no use. :laughing:
