### ISSUE TITLE
[Issue]: TVDB Plugin slows down library scan and webui significatly 

### ISSUE THREAD

**Issue by sebman3** [jellyfin/jellyfin#11088]
### Please describe your bug

I have had  incredibly slow library scans lasting over 2 hours, while it is happening the WebUI and entire server is slowed down and is unusable. Every page takes 10-20 seconds to load. I realized that when the TVDB plugin is disabled this is no longer an issue

### Reproduction Steps

1. have tbdb plugin enabled
2. run library scan

### Jellyfin Version

10.8.13

### Environment

```markdown
- OS:Debian 12
- Linux Kernel:
- Virtualization:
- Clients:jellyfin for linux flatpak, swiftin for apple tv, kodi for nvidia shield
- Browser:librewolf
- FFmpeg Version:
- Playback Method:directplay
- Hardware Acceleration:none
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
*
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
Please provide details about your setup:
1. Do you have the database and other Jellyfin files on a mechanical hard drive?
2. Are the Jellyfin files and the media files physically on the same storage device?

**Comment by sebman3** [comment]
My database is installed on an nvme m.2 and my tv shows are windows network share mounted.

They aren't on the same device

**Comment by solidsnake1298** [comment]
I couldn't replicate the problem when the media is stored locally.  Tomorrow I plan on trying to replicate your setup with remote storage for the media.

**Comment by felix920506** [comment]
Another thing. Do you have the save metadata alongside media option enabled?

**Comment by sebman3** [comment]
No I don't, the network mounts are read only
