### ISSUE TITLE
[Issue]: comic books get zoomed in too far when viewed on mobile 

### ISSUE THREAD

**Issue by Betonhaus** [jellyfin/jellyfin#11084]
### Please describe your bug

When attempting to view a comic book in the android jellyfin player, it will zoom the individual images to fit the screen, cropping off a third of the page so that it's unreadable. Trying to pan to see the rest of the image changes it to the next page, preventing the user from reading the entire page

### Reproduction Steps

1. Add a book library with comics in .cbz format
2. Open the comic on the android phone 

### Jellyfin Version

10.8.13

### Environment

```markdown
- OS: Debian 11
- Clients: jellyfin player 2.6.0 for android 
- Device: Motorola RAZR Plus
```

### Jellyfin logs

```shell
N/a
```

### Please attach any screenshots here

![Screenshot_20240229-202425](https://github.com/jellyfin/jellyfin/assets/149969033/c2df162e-98a5-4591-8a08-68b0a66524c7)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Betonhaus** [comment]
Wrong repository

**Comment by sidney-eliot** [comment]
This is not the wrong repository, as this problem is also present when viewing Jellyfin via a web browser on mobile devices.
