### ISSUE TITLE
[Issue]: 404 on previous .deb file

### ISSUE THREAD

**Issue by Billos** [jellyfin/jellyfin#11094]
### Please describe your bug

Using Yunohost, we have automated restoring scripts that use the Jellyfin Repository to retrieve the .deb file

Unfortunately there is only the last version on the repository and no previous versions, so https://repo.jellyfin.org/releases/server/debian/versions/stable/web/10.8.11/ returns a 404.

Is it on purpose that there is only the latest version available ?

### Reproduction Steps

Going on the page https://repo.jellyfin.org/releases/server/debian/versions/stable/web/10.8.11/ returns 404

### Jellyfin Version

10.8.13

### Environment

```markdown
- OS: Debian
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
https://repo.jellyfin.org/releases/server/debian/versions/jellyfin-ffmpeg/6.0-6/jellyfin-ffmpeg6_6.0-6-bullseye_amd64.deb:
2024-03-02 20:57:12 erreur 404 : Not Found.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JPVenson** [comment]
You are linking the path to the /stable version of jellyfin which is 10.8.13 and not 10.8.11 anymore. Not a bug.

**Comment by joshuaboniface** [comment]
Yes, this is on purpose.

To save space on our mirrors, we move previous versions to our archive which is not distributed. In the past, we'd leave old point releases there, but as we prepare for a new repository we've moved all the 10.8.z releases except the latest there. You can find said old versions under https://repo.jellyfin.org/archive/server/debian/stable/ e.g. https://repo.jellyfin.org/archive/server/debian/stable/10.8.11

**Comment by joshuaboniface** [comment]
Also, worth noting for you @Billos that we'll be activating a new repository layout soon (next couple of days).

Debian releases for the latest version can now be found at paths like `https://repo.jellyfin.org/files/server/debian/latest-stable/<arch>/`, or at paths like `https://repo.jellyfin.org/files/server/debian/stable/<version>/<arch>/` (for at least a couple recent versions going forward, depends on how our release cadences change with our new CI).
