### ISSUE TITLE
Can't add a LiveTV guide data provider when on mobile.

### ISSUE THREAD

**Issue by bfayers** [jellyfin/jellyfin#111]
Results in this error:

```
Could not find file /dashboard- ui/components/tvproviders/.template.html. 
```
Seems like it doesn't get the type of guide data from the URL Properly while on mobile.

**Comment by Mengine** [comment]
same as issue [#57](https://github.com/jellyfin/jellyfin/issues/57#issuecomment-446443211)?

**Comment by bfayers** [comment]
@Mengine kind of? Except doing the refreshing several times that works in desktop doesn't seem to on mobile

**Comment by Mengine** [comment]
but are you using docker and if so have you tried to run it in bridge mode?

**Comment by joshuaboniface** [comment]
@bfayers Is this still happening on the latest releases?

**Comment by bfayers** [comment]
@joshuaboniface #453 is a dupe of this and by extension this is somewhat a dupe of #57 , but I wrote there about how to *fix* it. Pretty sure this is still happening on latest.


>The solution is to go look at the url it will end with ?type=xmltv change this to ?type=xmltva press >enter, refresh. change it back to ?type=xmltv press enter press refresh, repeat until it works.

**Comment by anthonylavado** [comment]
Just tried adding a LiveTV guide data provider from my phone, and the page loads. This is running 10.2.2 release, native Debian package.

Will close in 48h unless I hear otherwise.

@bfayers Is this still not working for you?

**Comment by bfayers** [comment]
@anthonylavado works fine now.
