### ISSUE TITLE
[Issue]: shows with more than 9 seasons are jumbled

### ISSUE THREAD

**Issue by JamesSwift** [jellyfin/jellyfin#11117]
### Please describe your bug

This is a strange bug that seems to be happening during metadata collection, rather than when the data is displayed. Say I have a show with 15 seasons. On the web app it displays as Season 1,11,12,13,14,15,2,3,4,5,6,7,8,9. At first I thought it was just a alphabetical vs natural sorting bug in the web app. But it's not. 

"season 11" does actually contain the episodes for season 2 - all correctly named, season 12 contains season 3 and so on all the way. It's purely that the name of the season has been set wrong... season 2 has been named "Season 11", season 3 is named "Season 12" and so on. I presume this is a bug somewhere in the processing of the metadata before it is written to the DB. All my shows with less than 9 seasons have no issue. 

### Reproduction Steps

1. Find a show with more than 9 seasons.
2. Force refresh it's metadata from tvdb.
3. Reload the web app to show the mixed up season names.

### Jellyfin Version

10.8.13

### Environment

```markdown
- OS:linux
- Linux Kernel:
- Virtualization: docker
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
N/a
```

### Please attach any screenshots here

![Screenshot_20240307_011450_Firefox](https://github.com/jellyfin/jellyfin/assets/2080205/b36d86e8-b995-42d1-91bb-fcad053e244e)
![Screenshot_20240307_012611_Firefox](https://github.com/jellyfin/jellyfin/assets/2080205/fd5c2009-89c5-4ece-b7e6-d94fb05216ad)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
I can't reproduce this on 10.8.13, what is shown if you edit the season metadata for Season 10?

**Comment by JamesSwift** [comment]
![metadata](https://github.com/jellyfin/jellyfin/assets/2080205/698d9c4b-e2b7-4839-889a-a20af375c2fc)

**Comment by JamesSwift** [comment]
And here's the filenames.

![image](https://github.com/jellyfin/jellyfin/assets/2080205/20b58c1d-9a33-4e6a-b0cc-c897fcf67199)

**Comment by oddstr13** [comment]
Does this still happen in the latest release, if you replace all metadata on the series?

Does it consistently happen for all shows with more than 9 seasons? Just one or a few?

A full list of metadata providers enabled on the library would likely be required to figure this one out, along with data from .nfo files if they are present

**Comment by JamesSwift** [comment]
Hi, sorry for the long delay. I can confirm this is still happening on 10.9.11. I've done a full replace of all metadata for the series and it's still going 1, 10, 2, 3 etc. 

I've no nfo files, and the only metadata provider enabled is TVDB.

**Comment by JamesSwift** [comment]
An update. By removing the folder containing the show in question from the filesystem, then scanning the library, then adding the folder back, then scanning again this issue was resolved. It still doesn't answer as to why it happened, but at least it is fixable.
