### ISSUE TITLE
[Issue]: Cannot play videos

### ISSUE THREAD

**Issue by PeachesMLG** [jellyfin/jellyfin#11125]
### Please describe your bug

Playing videos doesnt work on latest commit, going back a few commits (59f50ae8b2555b8caa19e743c3ba612e999f75bf) seems to fix it

### Reproduction Steps

1) Run code from Latest master commit
2) Watch a video
3) Observe Playback error message

### Jellyfin Version

Latest Commit on Master (10.9)

### Environment

```markdown
- OS: Manjaro Linux
- Linux Kernel: 6.6.19-1
- Clients: Browser
- Browser: Firefox
- FFmpeg Version: 6.0.1
- Playback Method: Direct
- Hardware Acceleration: None
```

### Jellyfin logs

```shell
My logs are too long to paste here, however there isnt anything particuarly relivent in there logs
```

### FFmpeg logs

```shell
N/A (there arnt any)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
Hi, please upload the logs as an attached text file.

**Comment by TimGels** [comment]
I can reproduce this and narrow it down to the following commit: https://github.com/jellyfin/jellyfin/commit/407cf5d0bf9d3563ae77fd34ce29ffae5af4339f . Starting from this commit my playback breaks.

**Comment by PeachesMLG** [comment]
[logs.log](https://github.com/jellyfin/jellyfin/files/14542457/logs.log)
