### ISSUE TITLE
[Issue]: Parental controls are ineffective for TV shows.

### ISSUE THREAD

**Issue by kekxv** [jellyfin/jellyfin#11122]
### Please describe your bug

Parental controls are ineffective for TV shows.

### Reproduction Steps

set TV shows was `R`

### Jellyfin Version

10.8.13

### Environment

```markdown
- OS: linux docker
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
Parental controls are ineffective for TV shows.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
Issue template not filled, closing as invalid.
