### ISSUE TITLE
Migrate to use MusicBrainz JSON Web Service (from XML)

### ISSUE THREAD

**Issue by ploughpuff** [jellyfin/jellyfin#1112]
Migrate to use MusicBrainz JSON Web Service (from XML).

MusicBrainz have plans to retire the XML interface at some point (1 or 2 years?) and Jellyfin should adopt the JSON interface prior to that.

MusicBrainz JSON: https://musicbrainz.org/doc/Development/JSON_Web_Service

**Comment by LeoVerto** [comment]
For reference: https://chatlogs.metabrainz.org/brainzbot/metabrainz/2019-03-14/?msg=4357869&page=4
