### ISSUE TITLE
[Issue]: Absolute Ordering not working

### ISSUE THREAD

**Issue by seyfu-t** [jellyfin/jellyfin#11123]
### Please describe your bug

My Spongebob files are ordered according to TVDB's absolute ordering, which has multi episodes. So really S01E01 is three episodes.
When I change the ordering to absolute, what I get is not what should be expected, rather it looks like DVD ordering or some other ordering but definitely not absolute ordering

### Reproduction Steps

1. Have Spongebob episodes sorted according to absolute ordering (usually max 20 multiepisodes per season)
![Screenshot_20240308_161245](https://github.com/jellyfin/jellyfin/assets/63481525/c07a2169-e24f-4153-b375-590ae35fff7e)
![Screenshot_20240308_155205](https://github.com/jellyfin/jellyfin/assets/63481525/df5970bf-cbc5-4f72-94dd-a4667e1043ec)
2. Set ordering to absolute
![Screenshot_20240308_155606](https://github.com/jellyfin/jellyfin/assets/63481525/330afc68-e36e-4104-b0dd-d9f6f7a18acf)
3. Re-scan libraries
4. Look at the episodes in Jellyfin, they are now ordered as single episodes, not multi episodes
![Screenshot_20240308_155234](https://github.com/jellyfin/jellyfin/assets/63481525/8961a7b7-f56d-4067-a624-ff03165f4483)

### Jellyfin Version

10.8.13

### Environment

```markdown
- OS: Jellyfin Official Docker Image
- Host: Ubuntu 22.04.4 LTS x86_64 with Kernel 5.15.0-97-generic
- Clients: Webbrowser, Swiftfin IOS App, Amazon FireTV Jellyfin App
- Browser: Librewolf, Firefox
- Hardware Acceleration: Nvidia NVENC
- GPU Model: GeForce GTX 970
- Plugins: TheTVDB
```

### Jellyfin logs

```shell
nothing relevant in logs
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TimGels** [comment]
# Sumamry
I have confirmed this behavior on 10.8.13. As a workaround you can try to first add the show, then set it to absolute ordering in the metadata settings, and finally add the episodes. When that is all done, refresh the metadata.

I am unable to reproduce this issue on 10.9 unstable (master branch) with TVDB plugin (master branch ported to work with 10.9). The files I tested with were named:
```
S01E01 help wanted.mkv
S01E02 Bubblestand.mkv
S01E03 Jellyfishing.mkv
S01E04 Naughty Nautical Neighbors.mkv
```

# Testing
I tested both 10.9 unstable and 10.8.13. The way I tested is how (how I would imagine) a user would expect to do this.

## 10.8.13
1. Add folder named `SpongeBob SquarePants` to my TVDB test library.
2. Rescan TVDB library.
3. **[Observation]** Spongebob show is added
4. Add episodes to Season 01 folder
5. Rescan the show
6. **[Observation]** Spongebob is now listed in aired order (as expected)
7. Edit the show metadata and set order to absolute
8. Rescan the show/library all metadata
9. **[Observation]** Episodes are listed in an order that makes no sense (looks like it is all over the place with my small test sample of 4 episodes) and I cannot link it to "Aired", "Absolute", "Joined" or "DVD". This should have been the "Absolute" order.

### Screenshot of episodes on Jellyfin (Absolute order)
![afbeelding](https://github.com/jellyfin/jellyfin/assets/43609220/20d5701d-0491-42fd-a04b-ae1c3cb14b5e)

### Screenshot of the same episodes on TVDB (Absolute order)
![afbeelding](https://github.com/jellyfin/jellyfin/assets/43609220/b7e3ee61-7a1a-4018-bab1-a513ba799f15)

> [!NOTE]
> Note how the fourth episode on Jellyfin has gotten the same title as the second episode.

This also gave many errors in the log. One entry of many similar entries:
```
[2024-03-09 14:16:53.641 +00:00] [ERR] [192] Jellyfin.Plugin.Tvdb.Providers.TvdbEpisodeProvider: Failed to retrieve episode with id "9289317", series id "179436":"BubbleStand/Ripped Pants"
TvDbSharper.TvDbServerException: The given episode ID does not exist; ID: 9289317 not found
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.EpisodesClient.GetAsync(Int32 episodeId, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.TvdbClientManager.<>c__DisplayClass24_0`1.<<TryGetValue>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreateAsync[TItem](IMemoryCache cache, Object key, Func`2 factory)
   at Jellyfin.Plugin.Tvdb.Providers.TvdbEpisodeProvider.GetEpisode(EpisodeInfo searchInfo, CancellationToken cancellationToken)
[2024-03-09 14:16:53.652 +00:00] [ERR] [19] Jellyfin.Plugin.Tvdb.Providers.TvdbEpisodeImageProvider: Failed to retrieve episode images for series "75886":"SpongeBob SquarePants"
TvDbSharper.TvDbServerException: The given episode ID does not exist; ID: 9289317 not found
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.EpisodesClient.GetAsync(Int32 episodeId, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Tvdb.TvdbClientManager.<>c__DisplayClass24_0`1.<<TryGetValue>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreateAsync[TItem](IMemoryCache cache, Object key, Func`2 factory)
   at Jellyfin.Plugin.Tvdb.Providers.TvdbEpisodeImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
```

Now on to testing on 10.9 unstable master branch.

## 10.9 Unstable Master branch (on commit 83d2bc3f9f13c62f6d3ef16c4fe75f0f5a18110d)

1. Add folder named `SpongeBob SquarePants` to my TVDB test library.
2. Rescan TVDB library.
3. **[Observation]** Spongebob show is added
4. Add episodes to Season 01 folder
5. Rescan the show
6. **[Observation]** Spongebob is now listed in aired order (as expected)
7. Edit the show metadata and set order to absolute
8. Rescan the show/library all metadata
9. **[Observation]** Episodes are correctly listed in absolute order.

### Screenshot of episodes on Jellyfin (Absolute order)
![afbeelding](https://github.com/jellyfin/jellyfin/assets/43609220/5e0e8095-5e01-4ff7-936f-9599c6bcc411)

### Screenshot of the same episodes on TVDB (Absolute order)
![afbeelding](https://github.com/jellyfin/jellyfin/assets/43609220/881676c4-2696-481c-8c55-4ff508a0a16f)

# Result
It appears that this issue is resolved on master (as I cannot reproduce it on master), I will therefore close this issue as resolved.

**Comment by s-talay** [comment]
I tried your steps with no success. I would love to try on unstable as well but how did you port the TVDB Plugin to work with unstable? @TimGels

**Comment by TimGels** [comment]
It is not easy to do the porting as it requires manually building all dependencies for the plugin to work with 10.9. But it also requires some small code changes to the plug-in code for it to be compatible with 10.9.

Can you write down the steps you took when trying the work around?

**Comment by s-talay** [comment]
Ok I start at my currently not working setup.
1. I shutdown the server
2. Remove Spongebob from my series library 
3. Delete all cache 
4. Start the server and do a re-scan.
5. Now I add the Spongebob folder with just season 1 but no episodes to my series library again
6. [Observe] Without doing a re-scan, after a couple of seconds i can search for Spongebob in Jellyfin and get a result and see season 1
7. Now I change the ordering to absolute in the metadata settings of the whole show
8. I add the episodes of season 1
9. I re-scan
10. Issue persists, episode order is a mess

**Comment by TimGels** [comment]
Thanks for the detailed steps @s-talay !
Can you try to do a re-scan between step 7 and 8. I noticed that 10.8.13 has trouble changing order without performing a re-scan.

**Comment by s-talay** [comment]
I retried it once more, with an additional re-scan between step 7 and 8.
No success. 
@TimGels

**Comment by scampower3** [comment]
Hey @s-talay, have you tried building the plugin from the Tvdb plugin master? There has been a significant rewrite of the plugin to migrate from the v3 api to v4 since the last release of the plugin.

**Comment by s-talay** [comment]
Hey @scampower3 thanks for the suggestion.
I tried it last week, though I'm not too well versed in C# and the technical details of jellyfin and its plugins.
What I dont know how to do in one go is compiling the plugin with all its dependencies also recompiled which @TimGels suggested was needed.
I might give it another shot soon and take a deeper look into it this time. But since this issue isn't persistent in the new version according to Tim, I don't think one should bother too much.

**Comment by seyfu-t** [comment]
Hi @TimGels
could you reopen this issue since now with version 10.9.0 and 10.9.1 the issue persists...

**Comment by TimGels** [comment]
@seyfu-t I will try to find time somewhere this week or next week to test this again.

**Comment by seyfu-t** [comment]
Thanks buddy, much appreciated

**Comment by scampower3** [comment]
@seyfu-t Try after selecting the display order, identify the show. Lmk if it works

**Comment by seyfu-t** [comment]
@scampower3  already tried that earlier but unfortunately no results

**Comment by TimGels** [comment]
@seyfu-t Could you test this with the provider/ library set to English and display language set to English, and share a screenshot of the result of the episodes listed in Jellyfin? It is easier for me to test when things are set to English. But I also want to eliminate a potential issue when metadata retrieval is done in with other languages.

**Comment by scampower3** [comment]
@seyfu-t Also, can you test with the latest release of the Tvdb plugin? It should refresh immediately when the display order change is submitted. No need to manually refresh after the display order change. The images will not be updated tho. So after confirming the metadata is updated correctly, manually refresh with replace existing images checked.

**Comment by seyfu-t** [comment]
Sorry guys, was a bit busy the last few days...

I updated jellyfin to the newest current version (10.9.3).
I also updated every single plugin including tvdb to the newest current version.

I re-scanned my library and re-ran the scheduled tasks for tvdb
![image](https://github.com/jellyfin/jellyfin/assets/63481525/2e3d2647-3264-4b98-95a5-0b891bc20ad5)

i have set the language to English
![image](https://github.com/jellyfin/jellyfin/assets/63481525/bce9cf43-75b9-4cbf-bc3c-fc40ce1e7abb)

i have re-done all the re-scans but for some reason the language of spongebob was still german even after refreshing all metadata multiple times. Removing, re-scanning and re-adding the show finally changed the language to english

after setting the setting to absolute and re doing all scans multiple times, I am once again stuck with no result...

![image](https://github.com/jellyfin/jellyfin/assets/63481525/d4686aea-8445-482e-862b-650f65988b95)

**Comment by TimGels** [comment]
If it is not much work, could you share the whole file tree here of the season? On [linux ](https://linux.die.net/man/1/tree)and [window ](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/tree)there are "tree" utilities to do this in command line.

**Comment by seyfu-t** [comment]
Not much work at all:

❯ exa -T jellyfin/media/Serien/Spongebob\ Squarepants/
jellyfin/media/Serien/Spongebob Squarepants
├── Season 1
│  ├── SpongeBob Schwammkopf S01E01.mp4
│  ├── SpongeBob Schwammkopf S01E02.mp4
│  ├── SpongeBob Schwammkopf S01E03.mp4
│  ├── SpongeBob Schwammkopf S01E04.mp4
│  ├── SpongeBob Schwammkopf S01E05.mp4
│  ├── SpongeBob Schwammkopf S01E06.mp4
│  ├── SpongeBob Schwammkopf S01E07.mp4
│  ├── SpongeBob Schwammkopf S01E08.mp4
│  ├── SpongeBob Schwammkopf S01E09.mp4
│  ├── SpongeBob Schwammkopf S01E10.mp4
│  ├── SpongeBob Schwammkopf S01E11.mp4
│  ├── SpongeBob Schwammkopf S01E12.mp4
│  ├── SpongeBob Schwammkopf S01E13.mp4
│  ├── SpongeBob Schwammkopf S01E14.mp4
│  ├── SpongeBob Schwammkopf S01E15.mp4
│  ├── SpongeBob Schwammkopf S01E16.mp4
│  ├── SpongeBob Schwammkopf S01E17.mp4
│  ├── SpongeBob Schwammkopf S01E18.mp4
│  ├── SpongeBob Schwammkopf S01E19.mp4
│  └── SpongeBob Schwammkopf S01E20.mp4
├── Season 2
│  ├── SpongeBob Schwammkopf S02E01.mp4
│  ├── SpongeBob Schwammkopf S02E02.mp4
│  ├── SpongeBob Schwammkopf S02E03.mp4
│  ├── SpongeBob Schwammkopf S02E04.mp4
│  ├── SpongeBob Schwammkopf S02E05.mp4
│  ├── SpongeBob Schwammkopf S02E06.mp4
│  ├── SpongeBob Schwammkopf S02E07.mp4
│  ├── SpongeBob Schwammkopf S02E08.mp4
│  ├── SpongeBob Schwammkopf S02E09.mp4
│  ├── SpongeBob Schwammkopf S02E10.mp4
│  ├── SpongeBob Schwammkopf S02E11.mp4
│  ├── SpongeBob Schwammkopf S02E12.mp4
│  ├── SpongeBob Schwammkopf S02E13.mp4
│  ├── SpongeBob Schwammkopf S02E14.mp4
│  ├── SpongeBob Schwammkopf S02E15.mp4
│  ├── SpongeBob Schwammkopf S02E16.mp4
│  ├── SpongeBob Schwammkopf S02E17.mp4
│  ├── SpongeBob Schwammkopf S02E18.mp4
│  ├── SpongeBob Schwammkopf S02E19.mp4
│  └── SpongeBob Schwammkopf S02E20.mp4
├── Season 3
│  ├── SpongeBob Schwammkopf S03E01.mp4
│  ├── SpongeBob Schwammkopf S03E02.mp4
│  ├── SpongeBob Schwammkopf S03E03.mp4
│  ├── SpongeBob Schwammkopf S03E04.mp4
│  ├── SpongeBob Schwammkopf S03E05.mp4
│  ├── SpongeBob Schwammkopf S03E06.mp4
│  ├── SpongeBob Schwammkopf S03E07.mp4
│  ├── SpongeBob Schwammkopf S03E08.mp4
│  ├── SpongeBob Schwammkopf S03E09.mp4
│  ├── SpongeBob Schwammkopf S03E10.mp4
│  ├── SpongeBob Schwammkopf S03E11.mp4
│  ├── SpongeBob Schwammkopf S03E12.mp4
│  ├── SpongeBob Schwammkopf S03E13.mp4
│  ├── SpongeBob Schwammkopf S03E14.mp4
│  ├── SpongeBob Schwammkopf S03E15.mp4
│  ├── SpongeBob Schwammkopf S03E16.mp4
│  ├── SpongeBob Schwammkopf S03E17.mp4
│  ├── SpongeBob Schwammkopf S03E18.mp4
│  ├── SpongeBob Schwammkopf S03E19.mp4
│  └── SpongeBob Schwammkopf S03E20.mp4
├── Season 4
│  ├── SpongeBob Schwammkopf S04E01.mp4
│  ├── SpongeBob Schwammkopf S04E02.mp4
│  ├── SpongeBob Schwammkopf S04E03.mp4
│  ├── SpongeBob Schwammkopf S04E04.mp4
│  ├── SpongeBob Schwammkopf S04E05.mp4
│  ├── SpongeBob Schwammkopf S04E06.mp4
│  ├── SpongeBob Schwammkopf S04E07.mp4
│  ├── SpongeBob Schwammkopf S04E08.mp4
│  ├── SpongeBob Schwammkopf S04E09.mp4
│  ├── SpongeBob Schwammkopf S04E10.mp4
│  ├── SpongeBob Schwammkopf S04E11.mp4
│  ├── SpongeBob Schwammkopf S04E12.mp4
│  ├── SpongeBob Schwammkopf S04E13.mp4
│  ├── SpongeBob Schwammkopf S04E14.mp4
│  ├── SpongeBob Schwammkopf S04E15.mp4
│  ├── SpongeBob Schwammkopf S04E16.mp4
│  ├── SpongeBob Schwammkopf S04E17.mp4
│  ├── SpongeBob Schwammkopf S04E18.mp4
│  ├── SpongeBob Schwammkopf S04E19.mp4
│  └── SpongeBob Schwammkopf S04E20.mp4
└── Season 5
   ├── SpongeBob Schwammkopf S05E01.mp4
   ├── SpongeBob Schwammkopf S05E02.mp4
   ├── SpongeBob Schwammkopf S05E03.mp4
   ├── SpongeBob Schwammkopf S05E04.mp4
   ├── SpongeBob Schwammkopf S05E05.mp4
   ├── SpongeBob Schwammkopf S05E06.mp4
   ├── SpongeBob Schwammkopf S05E07.mp4
   ├── SpongeBob Schwammkopf S05E08.mp4
   ├── SpongeBob Schwammkopf S05E09.mp4
   ├── SpongeBob Schwammkopf S05E10.mp4
   ├── SpongeBob Schwammkopf S05E11.mp4
   ├── SpongeBob Schwammkopf S05E12.mp4
   ├── SpongeBob Schwammkopf S05E13.mp4
   ├── SpongeBob Schwammkopf S05E14.mp4
   ├── SpongeBob Schwammkopf S05E15.mp4
   ├── SpongeBob Schwammkopf S05E16.mp4
   ├── SpongeBob Schwammkopf S05E17.mp4
   ├── SpongeBob Schwammkopf S05E18.mp4
   ├── SpongeBob Schwammkopf S05E19.mp4
   └── SpongeBob Schwammkopf S05E20.mp4

**Comment by seyfu-t** [comment]
And as a side note, @scampower3 the tip you gave with waiting for the merge in the tvdb plugin repo

> or wait for a release with https://github.com/jellyfin/jellyfin-plugin-tvdb/pull/143 merged in

the merge happened 3 weeks ago and was implemented in version 12, the plugin is now at version 13 and i installed version 13. Unfortunately, this didn't fix it...

**Comment by seyfu-t** [comment]
Are you guys still able to replicate the bug, after all these updates?

**Comment by BrunoGomesCoelho** [comment]
I can confirm this is still happening with version 13 of the plugin and the latest (stable) Jellyfin version.

See also #11274 and this [related](https://github.com/jellyfin/jellyfin-plugin-tvdb/pull/92) on TVDB repo for context.
