### ISSUE TITLE
[Issue]: jellyfin-ffmpeg5 missing from ubuntu repository

### ISSUE THREAD

**Issue by Rid** [jellyfin/jellyfin#11133]
### Please describe your bug

root@test:/# apt update && apt install jellyfin
Hit:1 http://security.ubuntu.com/ubuntu focal-security InRelease
Hit:2 http://archive.ubuntu.com/ubuntu focal InRelease
Hit:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Hit:5 https://repo.jellyfin.org/ubuntu focal InRelease
Reading package lists... Done
Building dependency tree
Reading state information... Done
134 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 jellyfin : Depends: jellyfin-ffmpeg5 (>= 5.0.0) but it is not installable
E: Unable to correct problems, you have held broken packages.

### Reproduction Steps

1. Try to install jellyfin via the repo on Ubuntu
2. You can see it's missing from https://ams1.mirror.jellyfin.org/files/ubuntu/dists/focal/main/binary-amd64/Packages

### Jellyfin Version

10.8.13

### Environment

```markdown
- OS: Debian 12
```

### Jellyfin logs

```shell
See above
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joshuaboniface** [comment]
Should be fixed now - some lingering issues from our new repo cutover last night.
