### ISSUE TITLE
Live TV error

### ISSUE THREAD

**Issue by chminsc** [jellyfin/jellyfin#11144]
when i play this m3u url, jellyfin returns error, while this can be played in other apps including vlc, tivimate, aptv on Mac,ios,android, under same network, same time

m3u url: http://livex.pop-app.live/s4n/poplive/ch217/playlist.m3u8"

Logs are as follows:

/videos/2680c1e5-7187-30d0-d13a-28e31d52a50d/live.m3u8

{"Protocol":1,"Id":"ce76962390436dfde54f90994a017af5","Path":"http://livex.pop-app.live/s4n/poplive/ch217/playlist.m3u8","EncoderPath":null,"EncoderProtocol":null,"Type":0,"Container":null,"Size":null,"Name":null,"IsRemote":true,"ETag":null,"RunTimeTicks":null,"ReadAtNativeFramerate":false,"IgnoreDts":true,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":false,"SupportsDirectPlay":true,"IsInfiniteStream":true,"RequiresOpening":true,"OpenToken":null,"RequiresClosing":true,"LiveStreamId":"a17c75760a04e99b68cf766e11316e1c_09efa0d56b934a82adec00a87b837fb0_ce76962390436dfde54f90994a017af5","BufferMs":null,"RequiresLooping":false,"SupportsProbing":true,"VideoType":null,"IsoType":null,"Video3DFormat":null,"MediaStreams":[{"Codec":null,"CodecTag":null,"Language":null,"ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Comment":null,"TimeBase":null,"CodecTimeBase":null,"Title":null,"VideoRange":"SDR","VideoRangeType":"SDR","VideoDoViTitle":null,"LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"DisplayTitle":"SDR","NalLengthSize":null,"IsInterlaced":true,"IsAVC":null,"ChannelLayout":null,"BitRate":20000000,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":false,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":1,"AspectRatio":null,"Index":-1,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":null,"Level":null,"IsAnamorphic":null},{"Codec":null,"CodecTag":null,"Language":null,"ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Comment":null,"TimeBase":null,"CodecTimeBase":null,"Title":null,"VideoRange":null,"VideoRangeType":null,"VideoDoViTitle":null,"LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"DisplayTitle":"","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":null,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":false,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":0,"AspectRatio":null,"Index":-1,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":null,"Level":null,"IsAnamorphic":null}],"MediaAttachments":[],"Formats":[],"Bitrate":20000000,"Timestamp":null,"RequiredHttpHeaders":{"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.85 Safari/537.36"},"TranscodingUrl":null,"TranscodingSubProtocol":null,"TranscodingContainer":null,"AnalyzeDurationMs":3000,"DefaultAudioStreamIndex":null,"DefaultSubtitleStreamIndex":null}

/usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 3000000 -user_agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.85 Safari/537.36" -fflags +igndts -init_hw_device vaapi=va:/dev/dri/renderD128,driver=iHD -filter_hw_device va -autorotate 0 -i "http://livex.pop-app.live/s4n/poplive/ch217/playlist.m3u8" -map_metadata -1 -map_chapters -1 -threads 0 -sn -codec:v:0 h264_vaapi -low_power 1 -rc_mode VBR -b:v 20000000 -maxrate 20000000 -bufsize 40000000 -force_key_frames:0 "expr:gte(t,n_forced*3)" -vf "setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,yadif=0:-1:0,format=nv12,hwupload_vaapi" -flags -global_header -codec:a:0 libfdk_aac -ac 6 -ab 384000 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_base_url "hls/ea7f8420e9e6ddb856459fd35f4bed07/" -hls_segment_filename "/config/transcodes/ea7f8420e9e6ddb856459fd35f4bed07%d.ts" -hls_playlist_type event -hls_list_size 0 -y "/config/transcodes/ea7f8420e9e6ddb856459fd35f4bed07.m3u8"

ffmpeg version 5.1.4-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 10 (Debian 10.2.1-6)
configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-libs=-lfftw3f --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libsvtav1 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
libavutil 57. 28.100 / 57. 28.100
libavcodec 59. 37.100 / 59. 37.100
libavformat 59. 27.100 / 59. 27.100
libavdevice 59. 7.100 / 59. 7.100
libavfilter 8. 44.100 / 8. 44.100
libswscale 6. 7.100 / 6. 7.100
libswresample 4. 7.100 / 4. 7.100
libpostproc 56. 6.100 / 56. 6.100
[hls @ 0x55e41caa4c00] Skip ('#EXT-X-VERSION:3')
[hls @ 0x55e41caa4c00] Opening 'http://livex.pop-app.live/s4n/poplive/ch217/chunks.m3u8?nimblesessionid=194330092' for reading
[http @ 0x55e41cacd0c0] HTTP error 403 Forbidden
[hls @ 0x55e41caa4c00] parse_playlist error Server returned 403 Forbidden (access denied) [http://livex.pop-app.live/s4n/poplive/ch217/chunks.m3u8?nimblesessionid=194330092]
http://livex.pop-app.live/s4n/poplive/ch217/playlist.m3u8: Server returned 403 Forbidden (access denied)

**Comment by gnattu** [comment]
Duplicate with #11015

Either setting user-agent is not enough or user-agent is broken.

**Comment by chminsc** [comment]
no user-agent for vlc, aptv, and tivimate, it works

there are seems few redirects when playing. and return 403 is also different from the issue you mentioned

**Comment by chminsc** [comment]
> Duplicate with #11015
> 
> 
> 
> Either setting user-agent is not enough or user-agent is broken. 

no user-agent for vlc, aptv, and tivimate, it works

there are seems few redirects when playing. and return 403 is also different from the issue you mentioned

**Comment by gnattu** [comment]
It is the same kind of the problem: the server rejects the client for some reason

Which is as I said: either setting user-agent is not enough, or the user-agent is broken.

> no user-agent for vlc, aptv, and tivimate, it works

They may already automatically set a valid user-agent, or they have additional headers to make the server think it is a browser.

**Comment by chminsc** [comment]
> It is the same kind of the problem: the server rejects the client for some reason
> 
> 
> 
> Which is as I said: either setting user-agent is not enough, or the user-agent is broken.
> 
> 
> 
> > no user-agent for vlc, aptv, and tivimate, it works
> 
> 
> 
> They may already automatically set a valid user-agent, or they have additional headers to make the server think it is a browser.

I found the reason. It's IP block. Thank you for help
