### ISSUE TITLE
[Issue]: Parental controls by blocking tag visible on home page and direct link

### ISSUE THREAD

**Issue by isaac-mcfadyen** [jellyfin/jellyfin#11153]
### Please describe your bug

Specifying Parental Controls via the Dashboard -> Users -> <username> -> Parental Control and setting a tag to block seems to be ineffective.

Specifically:
- the user can visit a direct link to the media and still view all information and play the media
- the media still appears on the user's Home Page under Up Next (ex. for TV if they've watched a previous episode)

### Reproduction Steps

1. Create a new user.
2. (Optionally) watch an episode of a TV show or part of a movie so it gets added to the Up Next on the home page.
3. Under the Parental Controls setting, add a Blocked tag of anything and assign that tag to a movie or show.
4. Observe that:
    i. The user can still see the media by using a direct link.
    ii. The user can still see the media on their home page under Up Next, and while the Up Next section could be removed the user can just add it back themselves it's still an issue.

### Jellyfin Version

10.8.13

### Environment

```markdown
- OS: Ubuntu 22.04
- Linux Kernel: 5.15.0-97-generic
- Virtualization: Docker
- Clients: Browser
- Browser: Chrome
- FFmpeg Version: 5.1.4-Jellyfin
- Playback Method: N/A
- Hardware Acceleration: None
- GPU Model: N/A
- Plugins: None
- Reverse Proxy: Caddy
- Base URL: None
- Networking: Bridge
- Storage: Local, ZFS
```

### Jellyfin logs

```shell
N/A
```

### FFmpeg logs

```shell
N/A
```

### Please attach any browser or client logs here

N/A

### Please attach any screenshots here

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Bond-009** [comment]
Is this still an issue in the latest release (currently 10.9.x)?
