### ISSUE TITLE
[Issue]: Trickplay API does not check for item permissions

### ISSUE THREAD

**Issue by JPVenson** [jellyfin/jellyfin#11166]
### Please describe your bug

The trickplay api does not check for individual library items Permission to actually view that item. Any authenticated user is able to request a trickplay playlist and authenticate with the used token for any item.

### Reproduction Steps

1. Authenticate with any valid user towards a Jellyfin server.
2. Obtain a HLS playlist for any item
3. Load all trickplay images for that item

### Jellyfin Version

Unstable (master branch)

### Environment

```markdown
- OS:
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
CodeIssue
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
Fixed by #11171
