### ISSUE TITLE
[Issue]: Empty artist created for folder containing music by an artist of a different name

### ISSUE THREAD

**Issue by guiweber** [jellyfin/jellyfin#11189]
### Please describe your bug

If you store music by a certain artist in a folder with a different name, an empty artist with the name of the folder will sometimes appear in the "More like this" recommendation section. Upon clicking on that recommendation, the user is taken to an empty artist info page.

To give one example, storing an album with tracks tagged as "Various Artists" in a folder called "VA" will create a recommendation for an empty artist named "VA".

Note that the empty artist does not appear in search results or in the artists list.

### Reproduction Steps

1. Create a music library where some of the folder names differ from the artist name tagged in the music files they contain.
2. Notice that Jellyfin may sometimes display a recommendation for an artist with the name of the folder.

Note: Although I'm seeing this for a few folders in my library, I haven't been able to reproduce purposefully just now by adding data to my existing library. Could it be that the recommendations are only updated periodically? Or just randomness in recommendations? In any case, let me know if I can provide further assistance if you're having trouble finding the cause of the issue.

### Jellyfin Version

10.8.13

### Environment

```markdown
- OS: Windows 10
- Virtualization: No
- Clients: Tested on Web and Android
- Browser: Firefox
```

### Jellyfin logs

```shell
No relevant log entries found.
```

### Please attach any screenshots here

Example: Music tagged with artist name "Ninc Inch Nails" placed in folder "NIN"

![image](https://github.com/jellyfin/jellyfin/assets/7825368/b68b4517-b931-4b7a-9804-27108b4548fb)

Empty artist page:

![image](https://github.com/jellyfin/jellyfin/assets/7825368/f8fb6232-72cd-4d67-ab20-f41d9215ae9d)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by guiweber** [comment]
Still present on 10.9.8

**Comment by guiweber** [comment]
Still present on a fresh install of 10.10.1 on a new system (clean slate).

The issue was reproduced by the following folder structure:

/music_root/music_flac/artist/album
/music_root/music_mp3/artist/album

And adding only the `/music_root` folder to the music library. Afterward, the More Like This section would sometimes show "music_mp3" and "music_mp3" as recommendations.

**Comment by felix920506** [comment]
Please organize your media according to the naming and folder scheme in the docs. 

https://jellyfin.org/docs/general/server/media/music

**Comment by guiweber** [comment]
@felix920506 like for issue #12976, this also happens when following the music naming guidelines. I can reproduce with the following structure:

music/soundtracks/album_1
music/soundtracks/album_2
...
music/soundtracks/album_n

Add the music folder to your library. When looking at the artist page of an artist present on those albums, the More Like This section will sometimes recommend "soundtracks". When clicking on the link you are taken to an empty artist page for "soundtracks".

This can also happen if a folder contains a single artist but is named differently (e.g. albums by Nine Inch Nails contained in a folder named NIN - a common abbreviation)

If this stays as "not planned", it would be good to update the music guidelines and explain that album-containing folders should have the exact same name as the artist name in the audio files metadata.
