### ISSUE TITLE
[Issue]: Search terms shouldn't strictly have to match certain special characters for search results to be returned

### ISSUE THREAD

**Issue by alvitali** [jellyfin/jellyfin#11193]
### Please describe your bug

In the search function for movie / tv shows on Jellyfin web, a search term needs to strictly match all the special characters in a title for it to be returned. 

This is hindersome when searching for e.g. movies with diacrytics in the title, like "Léon the Professional", where searching for "Leon" doesn't yield a result when not using the character "é". This is especially obstructive for a lot of foreign language films where characters with diacrytics can be much more prevalent

### Reproduction Steps

Search for media content with diacrytics in the title

### Jellyfin Version

10.8.13

### Environment

```markdown
- OS: Debian
- Clients: Browser
```

### Jellyfin logs

```shell
none
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gnattu** [comment]
This level of fuzzing search should be resolved once #11172 is merged.
