### ISSUE TITLE
Infuse client cannot log in unless user has admin privileges

### ISSUE THREAD

**Issue by puellaexmachina** [jellyfin/jellyfin#11197]
This same error is still occurring on my end with Infuse 7.7.2. If an account isn't an admin user, it can't sign in. When I grant that user admin rights, they can sign in -- and after the first time, they no longer require admin rights.

It's so weird. The only thing that I've changed on my server is putting it behind a HTTPS-based reverse proxy, but I doubt that would actually do anything. I'm still connecting on port 443 with HTTPS anyways.

_Originally posted by @puellaexmachina in https://github.com/jellyfin/jellyfin/issues/3599#issuecomment-2016321411_

I wanted to reopen this in case anything needed to be fixed.

Jellyfin version: 10.8.13
Networked using Tailscale's reverse proxy.

**Comment by felix920506** [comment]
You should file an issue with Infuse not us.
