### ISSUE TITLE
播放mp3的时候能不能支持字幕啊？

### ISSUE THREAD

**Issue by xyxy** [jellyfin/jellyfin#11202]
可不可以在播放mp3音频的时候支持加载本地字幕呢？这样我可以在学英语的时候可以看到字幕提示了。也可以管理本地音乐的时候显示我本地字幕文件里面的内容！

**Comment by felix920506** [comment]
Feature requests should be filed at https://features.Jellyfin.org

功能请求请至 https://features.jellyfin.org
