### ISSUE TITLE
[Issue]: Hang on server shutdown

### ISSUE THREAD

**Issue by Bond-009** [jellyfin/jellyfin#11218]
### Please describe your bug

Server hangs on shutdown, have to kill it manually

### Reproduction Steps

Can't reliably repro at the moment, just starting the server and shutting it down doesn't do the trick

### Jellyfin Version

Unstable (master branch)

### Environment

```markdown
- OS: Debian
- Linux Kernel: 6.1
- Virtualization: /
- Clients: Web, iOS expo
- Browser: Firefox
- FFmpeg Version: Latest jellyfin-ffmpeg
- Playback Method: /
- Hardware Acceleration: vaapi
- GPU Model: /
- Plugins: reports, boxsets
- Reverse Proxy: /
- Base URL: /
- Networking: /
- Storage: /
```

### Jellyfin logs

```shell
[10:37:58] [INF] [48] Jellyfin.Networking.PortForwardingHost: Stopping NAT discovery
[10:37:58] [INF] [48] Main: Running query planner optimizations in the database... This might take a while
[10:37:58] [DBG] [26] Jellyfin.Networking.AutoDiscoveryHost: Broadcast socket operation cancelled
[10:37:58] [DBG] [62] Jellyfin.Networking.AutoDiscoveryHost: Broadcast socket operation cancelled
[10:37:58] [DBG] [57] Jellyfin.Networking.AutoDiscoveryHost: Broadcast socket operation cancelled
[10:37:58] [DBG] [59] Jellyfin.Networking.AutoDiscoveryHost: Broadcast socket operation cancelled
```
```


### FFmpeg logs

_No response_

### Please attach any browser or client logs here

_No response_

### Please attach any screenshots here

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gnattu** [comment]
I've seen similar issue and the Network Manager keep refreshing the interface during the shutdown.

**Comment by joshuaboniface** [comment]
Can also confirm and reproduce reliably using the Restart button.

**Comment by nyanmisaka** [comment]
Same issue. Can't even stop the console with Ctrl-C.

It hangs on `Main: Running query planner optimizations in the database... This might take a while`

![image](https://github.com/jellyfin/jellyfin/assets/14953024/5aa745b7-c1a7-4810-aa1c-ec7ec4663770)

**Comment by felix920506** [comment]
Can reproduce with weekly unstable on macOS 13.1 arm64

**Comment by JPVenson** [comment]
Can reproduce with unstable on docker `sha256:971953acccf3cc06a130cf552efcbb82d633aea9c2dcfdc1b8b73057167388a6` after using the restart button in dashboard UI
