### ISSUE TITLE
[Issue]: maxStreamingBitrate can plausibly exceed `int` which leads to various clients failing

### ISSUE THREAD

**Issue by nagisa** [jellyfin/jellyfin#11223]
### Please describe your bug

When trying to play some tracks I'm seeing them fail regularly but without a clear pattern. This affects both the web client (https://github.com/jellyfin/jellyfin-web/issues/4744) and other clients that use similar APIs (Tauon Media Player, in my case.)

It turns that any time playback fails, it returns an error such as this:

```json
{"type":"https://tools.ietf.org/html/rfc7231#section-6.5.1","title":"One or more validation errors occurred.","status":400,"traceId":"00-7c910d7562b7035184937dc267b7df12-f0c4e1a1911af2a3-00","errors":{"maxStreamingBitrate":["The value \u00272800000000\u0027 is not valid."]}}
```

In jellyfin itself this param is represented by an `int` type and `log₂(2800000000) > 31` which is why this the request fails most likely.

While one could argue that this is plausibly a fault in the client for making the wrong request, I suspect that it isn't the clients that are coming up with this number in the first place. It seems to me that it shouldn't be too onerous to either clamp the value to the maximum if value too large to fit is supplied and/or to change the type of this parameter to a 64 bit or a bigint type.

### Reproduction Steps

I have no idea. I have a large FLAC library and individual tracks from the library keep failing with no clear pattern whatsoever. Furthermore fiddling with random settings and/or restarting the client may fix the issue for that particular track too...

Try grabbing whatever file you have in your library and manually replacing the value in `maxStreamingBitrate` the request with a value that doesn't fit into signed 32-bit integer?

### Jellyfin Version

10.8.13

### Environment

```markdown
- OS: Linux
- Linux Kernel: 6.6.21
- Virtualization: QEMU
- Clients: jellyfin-web, Tauon Music Box
- Browser: Firefox
- FFmpeg Version: 6.0.1
- Playback Method: Direct Play
- Hardware Acceleration: N/A
- GPU Model: N/A
- Plugins: none
- Reverse Proxy: nginx
- Base URL: none
- Networking: routed virtual interface
- Storage: local
```

### Jellyfin logs

Just a lot of

```shell
[2024-03-25 04:07:45.464 +02:00] [INF] [38] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: "[10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2024-03-25 04:11:09.451 +02:00] [INF] [44] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : "[10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2024-03-25 04:11:09.452 +02:00] [INF] [44] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : "[]"
```

### FFmpeg logs

```shell
N/A
```

### Please attach any browser or client logs here

```
$ curl 'https://jellyfin.home.kazlauskas.me/Audio/07fe5be09b8c830c576c4931126e2fd9/universal?UserId=<snip>&DeviceId=<snippit>&MaxStreamingBitrate=2800000000&Container=opus%2Cwebm%7Copus%2Cmp3%2Caac%2Cm4a%7Caac%2Cm4b%7Caac%2Cflac%2Cwebma%2Cwebm%7Cwebma%2Cwav%2Cogg&TranscodingContainer=ts&TranscodingProtocol=hls&AudioCodec=aac&api_key=<nah>&PlaySessionId=<eyes>&StartTimeTicks=0&EnableRedirection=true&EnableRemoteMedia=false' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:122.0) Gecko/20100101 Firefox/122.0' -H 'Accept: audio/webm,audio/ogg,audio/wav,audio/*;q=0.9,application/ogg;q=0.7,video/*;q=0.6,*/*;q=0.5' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br, identity' -H 'DNT: 1' -H 'Sec-Fetch-Dest: audio' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-origin' -H 'Range: bytes=0-' -H 'Connection: keep-alive' -H 'TE: trailers'
{"type":"https://tools.ietf.org/html/rfc7231#section-6.5.1","title":"One or more validation errors occurred.","status":400,"traceId":"00-7c910d7562b7035184937dc267b7df12-f0c4e1a1911af2a3-00","errors":{"maxStreamingBitrate":["The value \u00272800000000\u0027 is not valid."]}}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nagisa** [comment]
Hm, I guess my overarching question is: what is the value that the strict enforcement of this type achieves? If we don't anticipate anybody to have 2Gbps media files for the foreseeable future, then clamping the oversized parameter to the maximum would result in a ever-so-slightly more-reliable seeming system, even if it is a special case.

Do you know how is this parameter arrived at usually? Is there a speed test of sorts that the clients are expected to run in the background? With 2.5GbaseT Ethernet, WiFi 7 etc. becoming more prevalent, I suspect that issues related to this parameter may become more pronounced across more clients if this is indeed the usual implementation.

**Comment by gnattu** [comment]
> Do you know how is this parameter arrived at usually? Is there a speed test of sorts that the clients are expected to run in the background? 

It used to be a long int, but then we discovered that ffmpeg stores the bitrate in a 32-bit signed integer. Therefore, if we don't perform such clamping server-side, we will make ffmpeg unhappy.

> so the way this parameter gets arrived at does not appear to be related to the media files themselves

It should not, otherwise you won't see this error. The `1120000000 ` is a hard-coded value if I remembered it correctly.
