### ISSUE TITLE
[Issue]: Installing WebHook plugin over link provided in Notification tab shows 0.0.0.0 version

### ISSUE THREAD

**Issue by JPVenson** [jellyfin/jellyfin#11238]
### Please describe your bug

When installing the new Webhook plugin via the means of the Notification tabs button, shows the plugin installed as version 0.0.0.0 instead of the latest version expected.

### Reproduction Steps

1. Open Tab "Notifications" in Dashboard UI
2. Click on "Get The Plugin"
3. Install the displayed Plugin via click on "Install"
4. Wait for install 
5. restart server
6. open Plugins
7. Select "WebHook" plugin or Click on "Get the plugin" in Notification tab
8. Shows as installed version 0.0.0.0

### Jellyfin Version

Unstable (master branch)

### Environment

```markdown
- OS:
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
Nope
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DAMIOSKIDEV** [comment]
![image](https://github.com/jellyfin/jellyfin/assets/45036197/b1e8408a-2d6c-44ed-899f-0a3bbfceb847)
Same issue on other plugins like Artwork

**Comment by felix920506** [comment]
Mark confirmed by multiple reports

**Comment by crobibero** [comment]
![image](https://github.com/jellyfin/jellyfin/assets/24963659/fdfc1663-844e-4e9b-8b09-a5e2750793de)

I can confirm that after a plugin publish the image and version are displaying correctly. You may need to manually update the affected plugins
