### ISSUE TITLE
Use AAC for src with audiochannels >2

### ISSUE THREAD

**Issue by platinum55** [jellyfin/jellyfin#1123]
#### Problem:
currently every file/stream is transcoded with `-codec:a:0 libmp3lame -ac 2` - so any 5.1 source is converted to only two audio channels(stereo).

### Enhancement idea:
It would be amazing if the user could choose which format to use for streaming, I would prefer AAC. Maybe it also makes sense for the user to set the max-audiochannels :)

**Comment by daves00** [comment]
In a perfect world the server would detect what audio formats the client supports, however I've no idea if this is feasible. In my particular use case my video files are typically 5.1 as that matches my surround amp. The idea of setting max audio channel is good, but then you run into problems that this setting is per client device (note - Not per user!). For my surround amp pass-thru is the perfect solution, however when streaming to an alternate room I need stereo and transcode to 2 channel is a better fit, however the TV has this ability. The concept of profiles (similar in concept to the DLNA) may be a better fit but more effort to implement. As an interim step adding a pass-thru option would be an easy win and a great first step.

**Comment by JustAMan** [comment]
Server is already detecting what client supports.

It's only that for _transcoding_ the server uses hardcoded codec settings without looking what client supports IIRC.

**Comment by daves00** [comment]
cool - good to know, thank you

**Comment by JustAMan** [comment]
Also note that for both direct stream and transcode the server is limited in the choice of codecs as it currently uses HLS as a transport (which means using mp4 as underlying container, so it's most likely only `h264`/`h265` for video and `aac`/`ac3`/`mp3` for audio).

**Comment by platinum55** [comment]
We should use Fraunhofer AAC for best audio quality as well. Just checked the last jellyfin/ffmpeg build, there is no ```--enable-libfdk-aac``` builtin
