### ISSUE TITLE
[Issue]: Wizard retains detected language

### ISSUE THREAD

**Issue by jumoog** [jellyfin/jellyfin#11240]
### Please describe your bug

The wizard will remember the language of my browser. When I select a different language, the wizard stays in the detected language.

### Reproduction Steps

- Start new Docker Image.
- Visit Jellyfin in the browser
- pick a different language 

### Jellyfin Version

Unstable (master branch)

### if other:

2024032802

### Environment

```markdown
- Virtualization: Docker
```

### Jellyfin logs

```shell
no logs
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
Where did you get the image from? This isn't a valid build number for our official unstable image.

**Comment by felix920506** [comment]
That option is for setting the language for server translated text and not for client languages. This is working as intended.

**Comment by jumoog** [comment]
> Where did you get the image from? This isn't a valid build number for our official unstable image.

`jellyfin/jellyfin:2024032802-amd64` https://hub.docker.com/layers/jellyfin/jellyfin/2024032802-amd64/images/sha256-14428c3c6c04ed6d2060267852aeae079849d848651db99fd8b6a40c85cb0ebd?context=explore
