### ISSUE TITLE
[Issue]: Only on WebOS TV around 50% of mkv videos dont allow skipping/fast forwarding

### ISSUE THREAD

**Issue by freaked1234** [jellyfin/jellyfin#11265]
### Please describe your bug

1. Use WebOS TV (LG OLED) App
2. Play mkv video from library (over wired LAN, without transcoding)
3. Try to skip ahead or back within the video (manually or with +/- 5sec buttons)
4. Dot on "Progress bar(?)" moves to selected position 
5. Playback continues uninterrupted and dot jumps back to previous position

Same procedure on Laptop via Firefox (same Network but wireless), same video --> skipping within video works 

### Reproduction Steps

- Jellyfin server 10.8.13 running in Jail on TrueNAS Core

Not working:
- Jellyfin for WebOS 1.2.2 (wired network)
- Playback Info: Html Video Player; **Direct Play**; http; **Video**; mkv; 8.3 Mbps; H264 high

Working:
- Firefox on Windows Laptop (wireless network)
- Playback Info: Html video player; **Remuxing**; http; **HLS**

The only difference in playback info I see are play method DirectPlay/Remuxing and Video/HLS but I dont really know what that means and if I can change this on my TV.

### Jellyfin Version

10.8.13

### Environment

```markdown
see above
```

### Jellyfin logs

```shell
dont really know what exactly would help here
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
TrueNas Core is an unsupported platform.
