### ISSUE TITLE
[Issue]: Cannot update refresh progress of item 'Folder' (...) because a refresh for this item is not running

### ISSUE THREAD

**Issue by sjorge** [jellyfin/jellyfin#11264]
### Please describe your bug

After upgrading from 10.8.13 -> 10.9.0 while running a `Scan all libraries` (After updating all plugins) it seems this never really finishes and I get a lot of:

```
Mar 29 15:03:08 artemis.acheron.be jellyfin[236568]: [15:03:08] [ERR] Error refreshing folder
Mar 29 15:03:08 artemis.acheron.be jellyfin[236568]: System.InvalidOperationException: Cannot update refresh progress of item 'Folder' (ed4b05e7fae6991b5d3a95b1bf5bb510) because a refresh for this item is not running
Mar 29 15:03:08 artemis.acheron.be jellyfin[236568]:    at MediaBrowser.Providers.Manager.ProviderManager.<>c__DisplayClass69_0.<OnRefreshProgress>b__0(Guid _)
Mar 29 15:03:08 artemis.acheron.be jellyfin[236568]:    at MediaBrowser.Providers.Manager.ProviderManager.OnRefreshProgress(BaseItem item, Double progress)
Mar 29 15:03:08 artemis.acheron.be jellyfin[236568]:    at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass64_2.<ValidateChildrenInternal2>b__1(Double innerPercent)
```

I left it running for a nigh and it still never finished. Deleting the library to start fresh also doesn't help as the library never seems to delete.

However nuking `/var/lib/jellyfin`, /var/cache/jellyfin` and `/etc/jellyfin` and going through the setup wizard again on 10.9.0 and adding a new library does seem to work and I do not get these errors. (I only did a partial movie library)

### Reproduction Steps

1. install unstable (20240325) over an existing stable
2. Swap the plugin repo to the unstable one
3. trigger the plugin update schedule task
4. restart to load the updated plugins
5. trigger a scan all libraries

### Jellyfin Version

Unstable (master branch)

### if other:

10.9.0

### Environment

```markdown
- OS: Ubuntu 22.04.4 LTS
- Linux Kernel: GNU/Linux 6.5.0-26-generic x86_64 (for ARC support)
- Virtualization: BHYVE
- Clients: Browser
- Browser: Firefox 124.0b9 (64-bit)
- FFmpeg Version: jellyfin-ffmpeg6 - 6.0.1-5-jammy
- Playback Method: n/a
- Hardware Acceleration: QSV (also tried without, no difference)
- GPU Model: Intel Arc A310 Low Profile 4GB (ASRock)
- Plugins: AniDB, AniList, AudioDB, Cover Art Archive, Fanart, MusicBrainz, OMDb, Session Cleaner, Studio Images, TMDb, TMDb Box Sets, Trakt, Webhook
- Reverse Proxy: apache
- Base URL: /jellyfin
- Networking: vnic
- Storage: local (config) + NFS (media)
```

### Jellyfin logs

```shell
Lots of these:

Mar 29 15:03:08 artemis.acheron.be jellyfin[236568]: [15:03:08] [ERR] Error refreshing folder
Mar 29 15:03:08 artemis.acheron.be jellyfin[236568]: System.InvalidOperationException: Cannot update refresh progress of item 'Folder' (ed4b05e7fae6991b5d3a95b1bf5bb510) because a refresh for this item is not running
Mar 29 15:03:08 artemis.acheron.be jellyfin[236568]:    at MediaBrowser.Providers.Manager.ProviderManager.<>c__DisplayClass69_0.<OnRefreshProgress>b__0(Guid _)
Mar 29 15:03:08 artemis.acheron.be jellyfin[236568]:    at MediaBrowser.Providers.Manager.ProviderManager.OnRefreshProgress(BaseItem item, Double progress)
Mar 29 15:03:08 artemis.acheron.be jellyfin[236568]:    at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass64_2.<ValidateChildrenInternal2>b__1(Double innerPercent)
```

Also lots of
```
Mar 29 14:50:33 artemis.acheron.be jellyfin[236568]: [14:50:33] [ERR] Cannot get image dimensions for /var/lib/jellyfin/metadata/People/J/Jessica Raine/folder.jpg
Mar 29 14:50:33 artemis.acheron.be jellyfin[236568]: System.IO.FileNotFoundException: File not found
Mar 29 14:50:33 artemis.acheron.be jellyfin[236568]: File name: '/var/lib/jellyfin/metadata/People/J/Jessica Raine/folder.jpg'
Mar 29 14:50:33 artemis.acheron.be jellyfin[236568]:    at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
Mar 29 14:50:33 artemis.acheron.be jellyfin[236568]:    at Jellyfin.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info)
Mar 29 14:50:33 artemis.acheron.be jellyfin[236568]:    at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
```

I'm assuming they are not related as folder.jpg does indeed not exist for those people. I'm pretty sure I've seen a similar error for the missing people images on stable too at some point. But included it just in case as this is the only other ERR that I could spot while skimming the logs.
```


### FFmpeg logs

```shell
n/a
```

### Please attach any browser or client logs here

n/a

### Please attach any screenshots here

n/a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sjorge** [comment]
I did a tiny bit of digging, the message comes from 

https://github.com/jellyfin/jellyfin/blob/bfc5deb234ea89fe95482f30c02efad544229daf/MediaBrowser.Providers/Manager/ProviderManager.cs#L977

And a bit above it we have:

https://github.com/jellyfin/jellyfin/blob/bfc5deb234ea89fe95482f30c02efad544229daf/MediaBrowser.Providers/Manager/ProviderManager.cs#L971C13-L971C73

So it might be some weird thing that is hard to trigger or maybe only triggerable when upgrading a library from stable -> unstable.

**Comment by solidsnake1298** [comment]
I was able to replicate when I migrated my 10.8.13 testing instance to 10.9.  But it happens on both an upgraded 10.8 -> 10.9 /config and a "clean" unstable instance.

As far as I can tell, there is no harm in this message, though.

**Comment by fabwa** [comment]
Experience the same. I want to add that it freezes the controls on the dashboard 

"Scan All Libraries", "Restart", "Shutdown"

for me. So seems there is some harm beyond just showing a message in the logs.
