### ISSUE TITLE
[Issue]: Book library where author contains single book displays incorrectly

### ISSUE THREAD

**Issue by SethFalco** [jellyfin/jellyfin#11278]
### Please describe your bug

I'm creating a book library in my Jellyfin instance, as recommended in the Jellyfin documentation.

> ```
> Books
> …
> └── Books
>     └── Author
>         ├── Book1.epub
> …
> ```
>
> — https://jellyfin.org/docs/general/server/media/books/

However, for authors where I only have one of their books, Jellyfin seems to treat the book as if it has the name of the author.

So instead of either seeing a directory with the name of the author, or just seeing the book, it shows a book titled with the name of the author instead.

This shows how my library looks like:

![image](https://github.com/jellyfin/jellyfin/assets/22801583/6d8e8078-0e09-45f6-a4de-bae3e10fc34a)

This shows the metadata of the first book in the screenshot, where it uses the directory name (the author) instead of the file name (the book name):

![image](https://github.com/jellyfin/jellyfin/assets/22801583/496dfd8e-ff99-4493-85b7-39742cffafc2)

### Reproduction Steps

1. Launch Jellyfin
2. Create a directory for the Book library
3. In the directory, create a directory called Books
4. In the Books directory, create a directory for an author
5. In the author directory, add a book
6. Either wait or manually refresh the Book library
7. Observe that the library contains a book with the name of the author

### Jellyfin Version

10.8.13

### Environment

```markdown
- OS: Ubuntu 22.04.4 LTS x86_64
- Linux Kernel: 5.15.0-100-generic
- Virtualization: Docker
- Clients: Jellyfin Media Player
- Browser: Firefox
- FFmpeg Version: 
- Playback Method: 
- Hardware Acceleration:
- GPU Model: NVIDIA GeForce RTX 3070
- Plugins: AudioDB, Bookshelf, MusicBrainz, OMDb, Studio Images, TMDb
- Reverse Proxy: nginx
- Base URL: none
- Networking: 
- Storage: local
```

### Jellyfin logs

```shell
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SethFalco** [comment]
Update for anyone that finds this in future. The documentation has been updated since the issue was opened, and now suggests a different directory structure. Using the new proposed structure resolves this issue.

Each book or audiobook should be nested in a folder with the books name. So the correct structure would be:

> ```txt
> Books
> …
> ├── Books
> │   └── Author
> │       ├── Book4
> │       │   └── Book4.epub
> ```
> 
> — https://jellyfin.org/docs/general/server/media/books/

Using this structure, everything works perfectly. 👍

**Comment by Creaper1** [comment]
> Update for anyone that finds this in future. The documentation has been updated since the issue was opened, and now suggests a different directory structure. Using the new proposed structure resolves this issue.
> 
> Each book or audiobook should be nested in a folder with the books name. So the correct structure would be:
> 
> > Books
> > …
> > ├── Books
> > │   └── Author
> > │       ├── Book4
> > │       │   └── Book4.epub
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > — https://jellyfin.org/docs/general/server/media/books/
> 
> Using this structure, everything works perfectly. 👍

Configuring the structure as Books/Author/Book/book.epub prevents filters from working when used in the top level of the  Books library. Filters will work when used from Books/Author, but only return the books with the tag from whichever author you are currently viewing. 
If you use the Books/Author/book.epub method, filters will return all books for that filter, but any author with a single book is not displayed correctly in the library. They are displayed as a single book under the book library instead of residing in a folder of the author's name.
The Music Videos library has these same results as well.
This is with Jellyfin 10.11.6 and bookshelf 13.0.0.0
