### ISSUE TITLE
[Issue]: `/VirtualFolders` endpoint returns a transformed lowercase CollectionTypeOption

### ISSUE THREAD

**Issue by LePips** [jellyfin/jellyfin#11273]
### Please describe your bug

Originally reported in: https://github.com/jellyfin/jellyfin-sdk-swift/issues/34. The API schema is tagged with `CollectionTypeOptions` for this property and this lowercases it, causing decoding errors.

The attached transform can be seen below:
https://github.com/jellyfin/jellyfin/blob/ed82d796473455c3b89e640802eee24242801a3b/MediaBrowser.Model/Entities/VirtualFolderInfo.cs#L40

### Reproduction Steps

Easiest repro is to check the network response in the web API when viewing libraries in the dashboard.

### Jellyfin Version

10.8.13

### Environment

```markdown
N/A
```

### Jellyfin logs

```shell
Check local network response.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gnattu** [comment]
#11272

**Comment by felix920506** [comment]
Closing as duplicate of https://github.com/jellyfin/jellyfin-sdk-swift/issues/34
Please do not report the same issue if it has already been reported in another Jellyfin repo.
