### ISSUE TITLE
[Issue]: MacOS unstable arm build is corrupt

### ISSUE THREAD

**Issue by rasmuslos** [jellyfin/jellyfin#11271]
### Please describe your bug

The latest unstable arm build for macOS is not working, while the same build for amd64 works fine (through rosetta on the same device).

<img width="1611" alt="Bildschirmfoto 2024-03-31 um 20 40 56" src="https://github.com/jellyfin/jellyfin/assets/49640416/956d4e24-6a19-41db-9536-ea11d1ff2fbe">
The terminal on the left shows the amd64 build, the one on the right the arm one.

I ensured that the executable was not quarantined but I am pretty sure that the executable is not run correctly in the first place. Both installs are completely fresh.

### Reproduction Steps

1. Download the latest unstable Jellyfin macOS arm build
2. Try to run it

### Jellyfin Version

Unstable (master branch)

### Environment

```markdown
- OS: MacOS 14.4.1
- Processor: M1 Pro
```

### Jellyfin logs

```shell
`zsh: killed     ./jellyfin`
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gnattu** [comment]
dotnet projects does not work with Apple's auto ad-hoc signing mechanism, you have to manually sign all binaries in the folder, only removing the quarantine flag is not enough:

```
xattr -rd com.apple.quarantine .
codesign -fs - --deep jellyfin
```

This is documented on our website: https://jellyfin.org/docs/general/testing/server/macos
