### ISSUE TITLE
[Issue]: "Other" libary type has no Trickplay option

### ISSUE THREAD

**Issue by enter-a-random-username** [jellyfin/jellyfin#11284]
### Please describe your bug

Other as mixed libary type has no Trickplay option.

### Reproduction Steps

1. Open Libary settings
2. Set trickplay to Other (mixed Libary) - no section & checkbox

### Jellyfin Version

Unstable (master branch)

### Environment

```markdown
-
```

### Jellyfin logs

```shell
Not a playback issue or missing asset
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
This is likely a web change

**Comment by thornbill** [comment]
Duplicate of https://github.com/jellyfin/jellyfin-web/issues/5490
