### ISSUE TITLE
Debug logging doesn't work

### ISSUE THREAD

**Issue by platinum55** [jellyfin/jellyfin#1130]
### Issue:
1. Go on Expert - Logs 
2. Click "Enable debug logging"
3. Click again on the menu link, the checkbox isnt checked and there is no debugging enabled

### What I found out:
Browser did a POST request with "EnableDebugLevelLogging: true" inside

**Comment by ploughpuff** [comment]
Thanks for posting as I'm experiencing the same with latest master..

**Comment by ploughpuff** [comment]
Seems EnableDebugLevelLogging was pruned under PR #830 (https://github.com/jellyfin/jellyfin/pull/830/commits/7554f6355195443b721a9b65f04ef4f9f4c097e9)

@Bond-009 As this removal appears designed, what is the correct method for enabling the LogDebug() writes please?

**Comment by Bond-009** [comment]
You need to change the logger config manually.

**Comment by ploughpuff** [comment]
Ok, how do you do that?

Also, do we need an issue raising on jellyfin-web to remove the checkbox?

**Comment by platinum55** [comment]
I tried setting "EnableDebugLevelLogging = true" in the main config file, but it had no effect - how to enable debug-logging manually?

**Comment by joshuaboniface** [comment]
In the `logging.json` file under the `configdir` (default `datadir/config`), you change:

```
"MinimumLevel": "Information",
```

to

```
"MinimumLevel": "Debug",
```

And then restart Jellyfin. The debug messages show up in the log with the tag `DBG`.

**Comment by joshuaboniface** [comment]
I do agree we should simply prune this out of the WebUI, *or* add an interface to edit the `logging.json` file. I'm less a fan of the latter since it just adds more complexity, but perhaps it could be made into a runtime flag for that current session that turns off again on restart - do you know if that's possible @Bond-009?

**Comment by platinum55** [comment]
First, thank you very much for this information! About the complexity: I think it's better to give the user more power instead of moving options out of view. The "advanced" tab is maybe the best target for this, as it was already :)

**Comment by joshuaboniface** [comment]
I mean complexity in terms of having to get the server to edit another configuration file. It's doable, but I'd rather it be via some sort of physical editor; the logging configuration is quite complex and isn't well suited to buttons in a GUI.

**Comment by JustAMan** [comment]
As a stopgap measure we should be saying this much in documentation:


> In the `logging.json` file under the `configdir` (default `datadir/config`), you change:
> 
> ```
> "MinimumLevel": "Information",
> ```
> to
> 
> ```
> "MinimumLevel": "Debug",
> ```
> And then restart Jellyfin. The debug messages show up in the log with the tag `DBG`.

And hide the option from Web UI (or make it a link pointing to the documentation).

**Comment by JustAMan** [comment]
Uhh, this should be fixed sometime.

**Comment by JustAMan** [comment]
Fixed by https://github.com/jellyfin/jellyfin-web/pull/272
