### ISSUE TITLE
[Issue]: Metadata lookup is horrible (Shows/Movies)

### ISSUE THREAD

**Issue by i5x64BIT** [jellyfin/jellyfin#11329]
### Please describe your bug

I have a huge foler of tv shows, plex identified most of the shows correctly while jellyfin had less then 50% success.
I would like to discuss possible ways to imrove the title lookup.

And yes, if I follow the conventions everyting works great, but who wants to rename folders every time?

### Reproduction Steps

1. Install Jellyfin
2. Install all metadata plugins
3. Give a show you have an extra word like `Peaky.Blinders` -> `Peaky.Blinders.1080p`
4. Enjoy!

### Jellyfin Version

10.8.13

### Environment

```markdown
- Plugins:TVmaze TVDB TMDb OMDb
```

### Jellyfin logs

```shell
--
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by i5x64BIT** [comment]
I think a possible solution might be to take a title, split it, and try to lookup short titles.
maybe extract the year or season count  from the title and search by those too

**Comment by felix920506** [comment]
Please follow the naming convention specified in the documentation. https://jellyfin.org/docs/general/server/media/movies

**Comment by oddstr13** [comment]
The solution to this issue is to utilize an external tool to assist in organizing your media on disk.

One example of such tooling is Josh's [mediasorter](https://github.com/joshuaboniface/mediasorter), but there are plenty of other software serving a similar purpose.
