### ISSUE TITLE
[Issue]: rkmpp hardware encoding with 10bit source transcodes into black screen

### ISSUE THREAD

**Issue by fffonion** [jellyfin/jellyfin#11332]
### Please describe your bug

When the input is 10bit color depth video, either HEVC main10 or H264 high10 profile, when using rkmpp
hardware encoding, the output file is an incorrect black screen.

### Reproduction Steps

1. Use a 10bit source
2. Trigger transcode by setting very low bandwidth or always burn subtitle
3. On the client player plays black screen.
4. Copy the `.ts` file under `transcode` directory and play on computer shows it's all black too.
5. The same source file transcodes correctly without hardware accel, or when only using rkmpp for decoding but not encoding

### Jellyfin Version

10.8.13
using docker image:
`nyanmisaka/jellyfin    latest-rockchip   2b7ce3ef946d`

### Environment

```markdown
- OS: Ubuntu 22.04
- Linux Kernel: 5.10.110-rockchip-rk3588
- Virtualization: Docker
- Clients: Any
- Browser: Any
- FFmpeg Version: 6.0.1-Jellyfin
- Playback Method: Transcode
- Hardware Acceleration: rkmpp
- GPU Model: rk3588
- Plugins: none
- Reverse Proxy: none
- Base URL: none
- Networking: Host
- Storage: cifs mount
```

### Jellyfin logs

```shell
-
```

### FFmpeg logs

<details>
<summary>transcode log</summary>

/videos/557dbe1e-9484-6b71-dd03-74394b32ffa4/hls1/main/0.ts

{"Protocol":0,"Id":"557dbe1e94846b71dd0374394b32ffa4","Path":"source.mkv","EncoderPath":null,"EncoderProtocol":null,"Type":0,"Container":"mkv,webm","Size":1017666368,"Name":"source","IsRemote":false,"ETag":"39a2d1b3a5bbfafa727ac35281d496e5","RunTimeTicks":14220900352,"ReadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"OpenToken":null,"RequiresClosing":false,"LiveStreamId":null,"BufferMs":null,"RequiresLooping":false,"SupportsProbing":true,"VideoType":0,"IsoType":null,"Video3DFormat":null,"MediaStreams":[{"Codec":"ass","CodecTag":null,"Language":null,"ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Comment":null,"TimeBase":"1/100","CodecTimeBase":null,"Title":null,"VideoRange":null,"VideoRangeType":null,"VideoDoViTitle":null,"LocalizedUndefined":"\u672A\u5B9A\u4E49","LocalizedDefault":"\u9ED8\u8BA4","LocalizedForced":"\u5F3A\u5236\u7684","LocalizedExternal":"\u5916\u90E8","DisplayTitle":"\u672A\u5B9A\u4E49 - ASS - \u5916\u90E8","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":null,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":false,"IsForced":false,"Height":0,"Width":0,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":2,"AspectRatio":null,"Index":0,"Score":null,"IsExternal":true,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":true,"SupportsExternalStream":true,"Path":"source.ass","PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":"hevc","CodecTag":null,"Language":"jpn","ColorRange":null,"ColorSpace":"bt709","ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":null,"VideoRange":"SDR","VideoRangeType":"SDR","VideoDoViTitle":null,"LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"DisplayTitle":"1080p HEVC SDR","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":5724905,"BitDepth":10,"RefFrames":1,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":true,"IsForced":false,"Height":1080,"Width":1920,"AverageFrameRate":23.976025,"RealFrameRate":23.976025,"Profile":"Main 10","Type":1,"AspectRatio":"16:9","Index":1,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":"yuv420p10le","Level":120,"IsAnamorphic":null},{"Codec":"flac","CodecTag":null,"Language":"jpn","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":null,"VideoRange":null,"VideoRangeType":null,"VideoDoViTitle":null,"LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"DisplayTitle":"Japanese - FLAC - Stereo - Default","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":"stereo","BitRate":803104,"BitDepth":16,"RefFrames":null,"PacketLength":null,"Channels":2,"SampleRate":48000,"IsDefault":true,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":0,"AspectRatio":null,"Index":2,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null}],"MediaAttachments":[],"Formats":[],"Bitrate":6528009,"Timestamp":null,"RequiredHttpHeaders":{},"TranscodingUrl":null,"TranscodingSubProtocol":null,"TranscodingContainer":null,"AnalyzeDurationMs":null,"DefaultAudioStreamIndex":null,"DefaultSubtitleStreamIndex":null}

/usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -probesize 1G -init_hw_device rkmpp=rk -hwaccel rkmpp -hwaccel_output_format drm_prime -afbc rga -autorotate 0 -i file:"source.mkv" -autoscale 0 -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:0 -codec:v:0 h264_rkmpp -b:v 9541508 -maxrate 9541508 -bufsize 19083016 -g:v:0 96 -keyint_min:v:0 96 -filter_complex "alphasrc=s=1920x1080:r=23.976025:start='0',format=bgra,subtitles=f='source.ass.ass':alpha=1:sub2video=1:fontsdir='/cache/attachments/557dbe1e94846b71dd0374394b32ffa4',hwupload=derive_device=rkmpp[sub];[0:0]setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709[main];[main][sub]overlay_rkrga=eof_action=pass:repeatlast=0:format=nv12:afbc=1" -start_at_zero -codec:a:0 libmp3lame -ac 2 -ab 256000 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 4 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/config/transcodes/ef1525b20dd424c1b621685162beea43%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/config/transcodes/ef1525b20dd424c1b621685162beea43.m3u8"

ffmpeg version 6.0.1-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=arm64 --cross-prefix=/usr/bin/aarch64-linux-gnu- --toolchain=hardened --enable-cross-compile --enable-rkmpp --enable-rkrga
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
Input #0, matroska,webm, from 'file:source.mkv':
  Metadata:
    encoder         : libebml v1.3.4 + libmatroska v1.4.5
    creation_time   : 2020-07-22T16:52:12.000000Z
  Duration: 00:23:42.09, start: 0.000000, bitrate: 5724 kb/s
  Chapters:
    Chapter #0:0: start 0.000000, end 139.014000
      Metadata:
        title           : 
    Chapter #0:1: start 139.014000, end 647.063000
      Metadata:
        title           : 
    Chapter #0:2: start 647.063000, end 1308.891000
      Metadata:
        title           : 
    Chapter #0:3: start 1308.891000, end 1402.025000
      Metadata:
        title           : 
    Chapter #0:4: start 1402.025000, end 1422.090000
      Metadata:
        title           : 
  Stream #0:0(jpn): Video: hevc (Main 10), yuv420p10le(tv, bt709/unknown/unknown), 1920x1080, SAR 1:1 DAR 16:9, 23.98 fps, 23.98 tbr, 1k tbn (default)
    Metadata:
      BPS             : 4919985
      BPS-eng         : 4919985
      DURATION        : 00:23:42.088000000
      DURATION-eng    : 00:23:42.088000000
      NUMBER_OF_FRAMES: 34096
      NUMBER_OF_FRAMES-eng: 34096
      NUMBER_OF_BYTES : 874581525
      NUMBER_OF_BYTES-eng: 874581525
      _STATISTICS_WRITING_APP: mkvmerge v9.4.2 ('So High') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v9.4.2 ('So High') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2020-07-22 16:52:12
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-07-22 16:52:12
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:1(jpn): Audio: flac, 48000 Hz, stereo, s16 (default)
    Metadata:
      BPS             : 803104
      BPS-eng         : 803104
      DURATION        : 00:23:42.090000000
      DURATION-eng    : 00:23:42.090000000
      NUMBER_OF_FRAMES: 16666
      NUMBER_OF_FRAMES-eng: 16666
      NUMBER_OF_BYTES : 142760862
      NUMBER_OF_BYTES-eng: 142760862
      _STATISTICS_WRITING_APP: mkvmerge v9.4.2 ('So High') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v9.4.2 ('So High') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2020-07-22 16:52:12
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-07-22 16:52:12
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
[Parsed_subtitles_2 @ 0x555aa31f70] libass API version: 0x1701000
[Parsed_subtitles_2 @ 0x555aa31f70] libass source: tarball: 0.17.1
[Parsed_subtitles_2 @ 0x555aa31f70] Shaper: FriBidi 1.0.8 (SIMPLE) HarfBuzz-ng 6.0.0 (COMPLEX)
[Parsed_subtitles_2 @ 0x555aa31f70] Using font provider fontconfig
Stream mapping:
  Stream #0:0 (hevc_rkmpp) -> setparams:default (graph 0)
  overlay_rkrga:default (graph 0) -> Stream #0:0 (h264_rkmpp)
  Stream #0:1 -> #0:1 (flac (native) -> mp3 (libmp3lame))
Press [q] to stop, [?] for help
[Parsed_subtitles_2 @ 0x555aa88b80] libass API version: 0x1701000
[Parsed_subtitles_2 @ 0x555aa88b80] libass source: tarball: 0.17.1
[Parsed_subtitles_2 @ 0x555aa88b80] Shaper: FriBidi 1.0.8 (SIMPLE) HarfBuzz-ng 6.0.0 (COMPLEX)
[Parsed_subtitles_2 @ 0x555aa88b80] Using font provider fontconfig
[Parsed_subtitles_2 @ 0x555aa88b80] fontselect: (方正准圆_GBK, 700, 0) -> /usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf, 0, DejaVuSans-Bold
[Parsed_subtitles_2 @ 0x555aa88b80] Glyph 0x7B49 not found, selecting one more font for (方正准圆_GBK, 700, 0)
[Parsed_subtitles_2 @ 0x555aa88b80] fontselect: (方正准圆_GBK, 700, 0) -> /usr/share/fonts/opentype/noto/NotoSansCJK-Bold.ttc, 0, NotoSansCJKjp-Bold
Output #0, hls, to '/config/transcodes/ef1525b20dd424c1b621685162beea43.m3u8':
  Metadata:
    encoder         : Lavf60.3.100
  Stream #0:0: Video: h264 (High), drm_prime(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 9541 kb/s, 23.98 fps, 90k tbn
    Metadata:
      encoder         : Lavc60.3.100 h264_rkmpp
  Stream #0:1: Audio: mp3, 48000 Hz, stereo, s16p, 256 kb/s (default)
    Metadata:
      encoder         : Lavc60.3.100 libmp3lame
frame=    0 fps=0.0 q=0.0 size=       0kB time=-00:00:00.02 bitrate=  -0.0kbits/s speed=N/A    
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea430.ts' for writing
frame=  131 fps=0.0 q=-0.0 size=N/A time=-00:00:00.23 bitrate=N/A speed=N/A    
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea431.ts' for writing
frame=  242 fps=213 q=-0.0 size=N/A time=00:00:04.87 bitrate=N/A speed=4.29x    
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea432.ts' for writing
frame=  367 fps=223 q=-0.0 size=N/A time=00:00:10.01 bitrate=N/A speed=6.08x    
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea433.ts' for writing
frame=  478 fps=223 q=-0.0 size=N/A time=00:00:14.78 bitrate=N/A speed=6.89x    
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea434.ts' for writing
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea435.ts' for writing
frame=  610 fps=230 q=-0.0 size=N/A time=00:00:20.23 bitrate=N/A speed=7.64x    
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea436.ts' for writing
frame=  717 fps=227 q=-0.0 size=N/A time=00:00:24.24 bitrate=N/A speed=7.69x    
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea437.ts' for writing
frame=  824 fps=225 q=-0.0 size=N/A time=00:00:28.51 bitrate=N/A speed=7.77x    
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea438.ts' for writing
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea439.ts' for writing
frame=  969 fps=231 q=-0.0 size=N/A time=00:00:34.82 bitrate=N/A speed=8.32x    
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea4310.ts' for writing
frame= 1081 fps=230 q=-0.0 size=N/A time=00:00:39.53 bitrate=N/A speed=8.39x    
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea4311.ts' for writing
frame= 1188 fps=228 q=-0.0 size=N/A time=00:00:44.47 bitrate=N/A speed=8.54x    
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea4312.ts' for writing
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea4313.ts' for writing
frame= 1357 fps=237 q=-0.0 size=N/A time=00:00:51.48 bitrate=N/A speed=9.01x    
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea4314.ts' for writing
frame= 1493 fps=240 q=-0.0 size=N/A time=00:00:56.69 bitrate=N/A speed=9.12x    
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea4315.ts' for writing
frame= 1596 fps=238 q=-0.0 size=N/A time=00:01:01.20 bitrate=N/A speed=9.11x    
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea4316.ts' for writing
frame= 1733 fps=240 q=-0.0 size=N/A time=00:01:06.57 bitrate=N/A speed=9.21x    
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea4317.ts' for writing
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea4318.ts' for writing
frame= 1873 fps=242 q=-0.0 size=N/A time=00:01:12.38 bitrate=N/A speed=9.36x    
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea4319.ts' for writing
frame= 1977 fps=240 q=-0.0 size=N/A time=00:01:16.89 bitrate=N/A speed=9.34x    
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea4320.ts' for writing
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea4321.ts' for writing
frame= 2154 fps=247 q=-0.0 size=N/A time=00:01:24.07 bitrate=N/A speed=9.62x    
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea4322.ts' for writing
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea4323.ts' for writing
frame= 2311 fps=250 q=-0.0 size=N/A time=00:01:31.32 bitrate=N/A speed=9.88x    
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea4324.ts' for writing
frame= 2409 fps=245 q=-0.0 size=N/A time=00:01:35.25 bitrate=N/A speed=9.68x    
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea4325.ts' for writing
frame= 2587 fps=250 q=-0.0 size=N/A time=00:01:42.67 bitrate=N/A speed=9.92x    
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea4326.ts' for writing
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea4327.ts' for writing
frame= 2767 fps=255 q=-0.0 size=N/A time=00:01:49.85 bitrate=N/A speed=10.1x    
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea4328.ts' for writing
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea4329.ts' for writing
frame= 2892 fps=255 q=-0.0 size=N/A time=00:01:54.96 bitrate=N/A speed=10.1x    
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea4330.ts' for writing
frame= 3017 fps=254 q=-0.0 size=N/A time=00:02:00.67 bitrate=N/A speed=10.2x    
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea4331.ts' for writing
frame= 3156 fps=255 q=-0.0 size=N/A time=00:02:06.14 bitrate=N/A speed=10.2x    
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea4332.ts' for writing
frame= 3264 fps=254 q=-0.0 size=N/A time=00:02:10.48 bitrate=N/A speed=10.1x    
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea4333.ts' for writing
frame= 3342 fps=250 q=-0.0 size=N/A time=00:02:14.06 bitrate=N/A speed=  10x    
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea4334.ts' for writing
frame= 3403 fps=245 q=-0.0 size=N/A time=00:02:16.13 bitrate=N/A speed=9.79x    
frame= 3464 fps=240 q=-0.0 size=N/A time=00:02:18.67 bitrate=N/A speed=9.61x    
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea4335.ts' for writing
frame= 3518 fps=235 q=-0.0 size=N/A time=00:02:21.07 bitrate=N/A speed=9.43x    
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea4336.ts' for writing
frame= 3604 fps=233 q=-0.0 size=N/A time=00:02:24.91 bitrate=N/A speed=9.37x    
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea4337.ts' for writing
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea4338.ts' for writing
frame= 3784 fps=237 q=-0.0 size=N/A time=00:02:32.59 bitrate=N/A speed=9.55x    
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea4339.ts' for writing
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea4340.ts' for writing
frame= 3957 fps=240 q=-0.0 size=N/A time=00:02:39.84 bitrate=N/A speed= 9.7x    
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea4341.ts' for writing
frame= 4048 fps=238 q=-0.0 size=N/A time=00:02:43.34 bitrate=N/A speed=9.62x    
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea4342.ts' for writing
frame= 4182 fps=239 q=-0.0 size=N/A time=00:02:48.81 bitrate=N/A speed=9.65x    
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea4343.ts' for writing
frame= 4314 fps=240 q=-0.0 size=N/A time=00:02:54.09 bitrate=N/A speed=9.67x    
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea4344.ts' for writing
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea4345.ts' for writing
frame= 4473 fps=242 q=-0.0 size=N/A time=00:03:00.74 bitrate=N/A speed=9.77x    
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea4346.ts' for writing
frame= 4577 fps=241 q=-0.0 size=N/A time=00:03:05.18 bitrate=N/A speed=9.74x    
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea4347.ts' for writing
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea4348.ts' for writing
frame= 4726 fps=242 q=-0.0 size=N/A time=00:03:11.42 bitrate=N/A speed=9.81x    
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea4349.ts' for writing
frame= 4872 fps=243 q=-0.0 size=N/A time=00:03:17.47 bitrate=N/A speed=9.86x    
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea4350.ts' for writing
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea4351.ts' for writing
frame= 5010 fps=244 q=-0.0 size=N/A time=00:03:23.37 bitrate=N/A speed= 9.9x    
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea4352.ts' for writing
frame= 5132 fps=244 q=-0.0 size=N/A time=00:03:28.92 bitrate=N/A speed=9.93x    
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea4353.ts' for writing
frame= 5256 fps=244 q=-0.0 size=N/A time=00:03:33.53 bitrate=N/A speed=9.91x    
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea4354.ts' for writing
frame= 5368 fps=243 q=-0.0 size=N/A time=00:03:38.13 bitrate=N/A speed=9.89x    
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea4355.ts' for writing
frame= 5466 fps=242 q=-0.0 size=N/A time=00:03:42.57 bitrate=N/A speed=9.85x    
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea4356.ts' for writing
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea4357.ts' for writing
frame= 5601 fps=242 q=-0.0 size=N/A time=00:03:48.02 bitrate=N/A speed=9.87x    
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea4358.ts' for writing
frame= 5696 fps=241 q=-0.0 size=N/A time=00:03:51.86 bitrate=N/A speed=9.82x    
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea4359.ts' for writing
frame= 5825 fps=242 q=-0.0 size=N/A time=00:03:57.50 bitrate=N/A speed=9.85x    
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea4360.ts' for writing
frame= 5920 fps=240 q=-0.0 size=N/A time=00:04:01.41 bitrate=N/A speed=9.79x    
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea4361.ts' for writing
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea4362.ts' for writing
frame= 6057 fps=241 q=-0.0 size=N/A time=00:04:07.32 bitrate=N/A speed=9.83x    
[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea4363.ts' for writing

Transcoding is paused. Press [u] to resume.

[q] command received. Exiting.

[hls @ 0x555aa6b690] Opening '/config/transcodes/ef1525b20dd424c1b621685162beea4364.ts' for writing
frame= 6163 fps=239 q=-0.0 Lsize=N/A time=00:04:11.06 bitrate=N/A speed=9.74x    
video:1239kB audio:8017kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
Please test on unstable. 

https://jellyfin.org/docs/general/testing/server/
