### ISSUE TITLE
[Issue]:  No handling of DOVI files not conforming with DOVI spec

### ISSUE THREAD

**Issue by GeorgeH005** [jellyfin/jellyfin#11330]
### Please describe your bug

There was a pull request merged recently conecrning proper DoVi support, in which I was active, but since then I have stumbled upon media files that seem to not be following Dolby Spec. More specifically the files are DV Profile 8 CCid 6.
We are tagging these outliers as (SDR,SDR).

Playback does **NOT** seem to be affected.

### Reproduction Steps

1. Go to any file as described above.
2. Click media info.

### Jellyfin Version

Unstable (master branch)

### if other:

2024040805

### Environment

```markdown
- OS: Debian 12
- Linux Kernel: 6.5.15
- Virtualization: LXC
- Clients: Any
- Browser: Any
- FFmpeg Version: 6.0.1-Jellyfin
- Playback Method: N/A
- Hardware Acceleration: N/A
- GPU Model: N/A
- Plugins: N/A
- Reverse Proxy: N/A
- Base URL: N/A
- Networking: N/A
- Storage: N/A
```

### Jellyfin logs

```shell
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shadowghost** [comment]
Feel free to propose a PR if this is universally fixable.
