### ISSUE TITLE
Transmission via .strm files

### ISSUE THREAD

**Issue by KingRotiv** [jellyfin/jellyfin#11348]
Hello! I'm getting to know the project and in local tests and on servers, the transmission of videos via .strm files is ridiculously slow. Practically impossible to watch.

Is there any way to improve transmission performance? Any configuration?

**Comment by sevenrats** [comment]
Hi, thank you very much for your report.  Jellyfin itself should not really be slowing down strms.  The video should play more or less at the speed that the source can deliver it.  What is the source of the video in your strm file?

**Comment by KingRotiv** [comment]
> Hi, thank you very much for your report.  Jellyfin itself should not really be slowing down strms.  The video should play more or less at the speed that the source can deliver it.  What is the source of the video in your strm file?

The source of the files is an API running alongside Jellyfin. Running the video outside of Jellyfin, the video starts in about 3 seconds, with Jellyfin it takes a long time, and sometimes doesn't even start. The experience is even worse for mobile customers.

**Comment by sevenrats** [comment]
What clients in particular?  I have a similar application, an the nature of the API can impact jellyfin's ecosystem greatly. For example, some clients, partiuclarly those backed by libmpv, request all streams with static=True.  If your storage api is storingthe file as, say, a DAG, then the inclusion of this arg will either cause your API to fail or traverse the entire DAG.  Simply imagine this problem multiplied by however other many factors you can imagine.

**Comment by sevenrats** [comment]
this little bob has always stood out to me but I can't claim to understand what it is doing:
https://github.com/jellyfin/jellyfin/blob/79087eadd3a55a0671077349d3e8567d0d5a1ad9/MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs#L546

**Comment by KingRotiv** [comment]
> What clients in particular?  I have a similar application, an the nature of the API can impact jellyfin's ecosystem greatly. For example, some clients, partiuclarly those backed by libmpv, request all streams with static=True.  If your storage api is storingthe file as, say, a DAG, then the inclusion of this arg will either cause your API to fail or traverse the entire DAG.  Simply imagine this problem multiplied by however other many factors you can imagine.
> 

My api acts as an intermediary between the Telegram messaging platform to obtain videos. I could even think that the delay could be something in the api, but running outside of Jellyfin, the api is relatively fast. So I conclude that it is something in Jellyfin, be it some configuration or something internal. C# is far outside my scope, so it's a little unrealistic to understand more deeply how the project works, which is why I'm asking for help here. 

The clients I tested were Jellyfin Web itself, Jellyfin-vue, Jellyfin Android and Findroid. The one that stood out the most was Jellyfin Web, Jellyfin-vue didn't even play one video, the Android clients even ran it a few times, but with a delay of long minutes and interspersed with errors.

**Comment by sevenrats** [comment]
it could be as simple as the number of roundtrips jellyfin makes with the data on the first playback.  because jellyfin does not necesssarily have permission to blast every backend that could be in every conceivable strm file, library scans don't actually probe strm endpoints for their internal channels. only external scanning is performed until playback, where ffprobe is called, the internal channels are updated, and THEN the mediasources object is returned.  so there is at least 1 additional roundtrip plus the db access.

**Comment by sevenrats** [comment]
a possible workaround, then, would be to play every single file to get their internal tracks into the db, and then just be careful not to frivolously change your mtimes. then the extra work should only happen when the strm's mtime is newer than the recorded mtime from the last scan. a simple experiment might be to see if the slowness happens on replay, or only on the first play of a file.

**Comment by felix920506** [comment]
Closing this as this is an issue with the setup and not Jellyfin itself. Please head to our forum or chat rooms for troubleshooting help. https://jellyfin.org/contact
