### ISSUE TITLE
Replace `system.xml` with a more sensible config file

### ISSUE THREAD

**Issue by joshuaboniface** [jellyfin/jellyfin#1134]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
A main configuration file, preferably in JSON and preferably integrating `logging.json` into it (assuming this is possible for Serilog). Something human readable and both human and machine editable to replace the disorganized and unreadable `server.xml` configuration file.

Additionally and related, though optional, I'd like a flag to set a static config that cannot be edited by the GUI, for use with e.g. Ansible or other configuration management, that could overwrite the "default" configuration if the administrator so desires (web config changes would then be ignored).

This will probably require a reconfiguration of how the existing configuration is stored, based on my knowledge of that subsystem, but hopefully not a particular extensive one to start with.

**Describe alternatives you've considered**
Editing `server.xml` is possible, but is fraught with problems...

**Additional context**
Inspired by my long-running frustration with trying to set values in `server.xml` programatically via config management, as well as the discussion in #1130. With the optional facility #1130 could be implemented in-GUI while preserving my usecase of setting `logging.json` (and then the whole `server.json`) via Ansible template. Emby (and hence Jellyfin) is one of those apps that never expects administrators to edit their configuration file, and the smallest touch in the admin interface overwrites the on-disk file. I strongly disagree with this mentality on principle. I like to set all my options repeatably using a configuration file and configuration management. I accept that this isn't suitable for less advanced users so it shouldn't be the default, but it should be an option.

**Comment by EraYaN** [comment]
Something like this would be nice to do at the same time: https://forum.jellyfin.org/t/configuration-management/128 essentially mirror most unix daemons in how they handle config options.

JSON is not very nice to edit by hand, if TOML can work that might be an idea as well. It if supports all the structures we need.

**Comment by joshuaboniface** [comment]
Agreed completely with your forum post. Tiered options are aa very good idea. I also agree that JSON isn't very nice. TOML or YAML, or hell even a simple key-value file with headers, would be nicer. And a diff file would be super nice, have the defaults be assumed like, as you said, how most *NIX daemon configs are handled.
