### ISSUE TITLE
[Issue]: Webui stopped working, reinstalled and still not working

### ISSUE THREAD

**Issue by AzriallSNR** [jellyfin/jellyfin#11362]
### Please describe your bug

Good morning

So I had Jellyfin up and running, no issues. Then the next day I tried logging into Jellyfin via the webui and got access forbidden, or timed out. I had installed no additional software between the two except to update ubuntu and mess around with making shared folders for the media to be stored in

Running Ubuntu 22.04 LTS server
Jellyfin installed Natively (Don't understand Dockers yet)
Connected directly into my router
Could connect via all media inside and outside my house
Made a previous post about making media folders
Connect to Server via SSH

Now
Running Ubuntu 22.04 LTS server
Jellyfish installed natively
connected directly to router
No changes to router
Can't access on any platform with IP address internally or externally
Removed installation
reinstalled
Same result
Can't see it listening on port 8096.
service listed as active and running

Did a check and found the following

The server is expected to host the web client, but the provided content directory is either invalid or empty: /usr/lib/jellyfin/bin/jellyfin-web. If you do not want to host the web client with the server, you may set the '--nowebclient' command line flag, or set'hostwebclient=false' in your config settings.

I have uninstalled it and reinstalled it a few times. I've followed the commands on the jellyfish debian/ubuntu installation guide. If it helps the only hicup I find is a message about the kernal being different and then needing to restart services. WSDD often needs to be restarted.

Are dockers really the way to go. I don't understand them or how to use one. I have been searching the net for a fix and not had any joys but people have said use it in a docker. My only worry with using it in a docker is how I make a folder I can access from my Win pc at home to put media on it.

### Reproduction Steps

Ubuntu server 22.04 LTS on a standalone PC

### Jellyfin Version

10.8.13

### Environment

```markdown
- OS: Ubuntu 22.04
- Linux Kernel:
- Virtualization: None
- Clients:
- Browser: Chrome/Safari
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking: Direct to Router
- Storage:
```

### Jellyfin logs

```shell
I don't know how to get this
```

### FFmpeg logs

```shell
I don't know how to get this
```

### Please attach any browser or client logs here

I don't know how to get this

### Please attach any screenshots here

I don't know how to get this

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nielsvanvelzen** [comment]
Please don't crosspost. Closing in favor of the forum thread

https://forum.jellyfin.org/t-missing-webui

**Comment by AzriallSNR** [comment]
ah sorry that was my bad
