### ISSUE TITLE
Allowed Tags in Parental Controls - Not Working?

### ISSUE THREAD

**Issue by adoreparler** [jellyfin/jellyfin#11375]
Is this working?

I am on version 10.9.0

![Screen Recording 2024-04-17 at 9 14 59 AM](https://github.com/jellyfin/jellyfin/assets/135237656/23a4b449-4eb3-475a-b31b-cd3ae57efe2d)

_Originally posted by @adoreparler in https://github.com/jellyfin/jellyfin/issues/9139#issuecomment-2061242953_

**Comment by felix920506** [comment]
Please head to our forum or chat rooms for general support
https://jellyfin.org/contact
