### ISSUE TITLE
List of database fail-strings in log for Windows Backup functionality, 

### ISSUE THREAD

**Issue by Paelsmoessan** [jellyfin/jellyfin#11391]
**PLEASE DO NOT OPEN FEATURE REQUEST ISSUES ON GITHUB**

**Feature requests should be opened on our dedicated [feature request](https://features.jellyfin.org/) hub so they can be appropriately discussed and prioritized.**

I recently had a Jellyfin crash and realized that there is no builtin backup, I am currently writing a powershell-script that will separate the metadata from the important data. What I need is the fail-strings in log when databases are corrupt so I can flag those and not delete old backups when this occurs. Could I perhaps get them from here?

However, if you are willing to contribute to the project by adding a new feature yourself, then please ensure that you first review our [documentation](https://docs.jellyfin.org/general/contributing/development.html) on contributing code. Once you have reviewed the documentation, feel free to come back here and open an issue here outlining your proposed approach so that it can be documented, tracked, and discussed by other team members.

**Comment by JPVenson** [comment]
There are a bunch of log lines that could indicate a corrupted database. We use the `Microsoft.Data.Sqlite` nuget package and only redirect the exception logs from there. 

As this is an upstream issue, i will close this.
