### ISSUE TITLE
[Issue]: Trickplay 10.9 endless image generation

### ISSUE THREAD

**Issue by enter-a-random-username** [jellyfin/jellyfin#11409]
### Please describe your bug

In some cases the video size won't match in `src/Jellyfin.Drawing.Skia/SkiaEncoder.cs#L597`

Video
Width                                    : 1 432 pixels
Height                                   : 1 072 pixels

Trickplay is set to 480px
ffmpeg command has width set to 478px

So the image never matches and maybe also an issue in case the image is to small like 360x240 and image size is increased.

### Reproduction Steps

Use a width in option and video file as mentioned in bug report

### Jellyfin Version

Unstable (master branch)

### Environment

```markdown
Jellyfin: 374b6ca0e22719df25b8d0aa51c510515b928104
ffmpeg: Jellyfin ffmpeg 6.0.1p5
```

### Jellyfin logs

```shell
[INF] [71] Jellyfin.Server.Implementations.Trickplay.TrickplayManager: Creating trickplay files at 480 width, for file.mkv [ID: c0ffee]
 [INF] [71] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Trickplay generation: /usr/lib/jellyfin-ffmpeg/ffmpeg -loglevel error -init_hw_device vaapi=va:/dev/dri/renderD128,driver=iHD -hwaccel vaapi -hwaccel_output_format vaapi -noautorotate -i file:"file.mkv" -noautoscale -an -sn -vf "fps=0.20000000298023224,setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale_vaapi=w=478:h=358:format=nv12:extra_hw_frames=24,hwmap=mode=read,format=nv12" -c:v mjpeg -f image2 "path...%08d.jpg"
 [ERR] [73] Jellyfin.Server.Implementations.Trickplay.TrickplayManager: Error creating trickplay images.
                System.InvalidOperationException: Image width does not match provided width.
                    at Jellyfin.Drawing.Skia.SkiaEncoder.CreateTrickplayTile(ImageCollageOptions options, Int32 quality, Int32 imgWidth, Nullable`1 imgHeight)
                    at Jellyfin.Server.Implementations.Trickplay.TrickplayManager.CreateTiles(List`1 images, Int32 width, TrickplayOptions options, String outputDir)
    at Jellyfin.Server.Implementations.Trickplay.TrickplayManager.RefreshTrickplayDataInternal(Video video, Boolean replace, Int32 width, TrickplayOptions options, CancellationToken cancellationToken)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
@enter-a-random-username you should comment on the pull request about questions with the pull request

**Comment by gnattu** [comment]
> Will this work with small as `width` videos?  So 320px video with a 360px setting

The whichever the smaller one will be used. So for 320px video with 360px setting 320px will be the image width

> Will it cause some issues if somebody chooses as odd number like 279 as thumbnail width (i use something even - 480 - nice for high density -displays  can be divided by 1.5, 2, 2.5, 3)

All odd width setting will be forced to round to an even number before processing.
