### ISSUE TITLE
Jellyfin process creates filesystem locks

### ISSUE THREAD

**Issue by mazzystr** [jellyfin/jellyfin#1141]
**Describe the bug**
Jellyfin seems to put a lock on the media filesystem so that if the filesystem is disconnected from the kernel the process cannot be killed.

**To Reproduce**
1. Start Jellyfin
2. Create library on mountpoint that is a nfs mount
3. Turn off nfs server
4. Try to kill -9 pid

**Expected behavior**
No filesystem locks are created so that the process can correctly be terminated if mountpoint behind media library disappears.

**Logs**
There may be a way to capture something in strace but I haven't gotten around to it yet.

**Screenshots**

**System (please complete the following information):**
 - OS: CentOS 7
 - Browser: N/A
 - Jellyfin Version: 10.0.2
 - Reverse proxy: None

**Comment by JustAMan** [comment]
What process are you trying to kill?
Also what does `sudo lsof /path/to/nfs/share` show?

**Comment by mazzystr** [comment]
Here is what I have going on right now...
```
[root@cube ~]# podman ps | grep jellyfin
718b504afe58  registry.hub.docker.com/jellyfin/jellyfin:latest      /bin/sh -c dotnet...  14 hours ago  Up 14 hours ago                          jellyfin
[root@cube ~]# ps -ef | grep 718b504afe58
root       33468       1  0 Mar20 ?        00:00:00 /usr/libexec/podman/conmon -s -c 718b504afe582213da8066ce09667df5d4ef3a4c4996308402d0f7b2fc6b8c44 -u 718b504afe582213da8066ce09667df5d4ef3a4c4996308402d0f7b2fc6b8c44 -r /usr/bin/runc -b /var/lib/containers/storage/overlay-containers/718b504afe582213da8066ce09667df5d4ef3a4c4996308402d0f7b2fc6b8c44/userdata -p /var/run/containers/storage/overlay-containers/718b504afe582213da8066ce09667df5d4ef3a4c4996308402d0f7b2fc6b8c44/userdata/pidfile -l /var/lib/containers/storage/overlay-containers/718b504afe582213da8066ce09667df5d4ef3a4c4996308402d0f7b2fc6b8c44/userdata/ctr.log --exit-dir /var/run/libpod/exits --socket-dir-path /var/run/libpod/socket --log-level error
root      772273   24661  0 09:53 pts/2    00:00:00 grep --color=auto 718b504afe58

[root@cube ~]# ps -ef | grep 33468
root       33468       1  0 Mar20 ?        00:00:00 /usr/libexec/podman/conmon -s -c 718b504afe582213da8066ce09667df5d4ef3a4c4996308402d0f7b2fc6b8c44 -u 718b504afe582213da8066ce09667df5d4ef3a4c4996308402d0f7b2fc6b8c44 -r /usr/bin/runc -b /var/lib/containers/storage/overlay-containers/718b504afe582213da8066ce09667df5d4ef3a4c4996308402d0f7b2fc6b8c44/userdata -p /var/run/containers/storage/overlay-containers/718b504afe582213da8066ce09667df5d4ef3a4c4996308402d0f7b2fc6b8c44/userdata/pidfile -l /var/lib/containers/storage/overlay-containers/718b504afe582213da8066ce09667df5d4ef3a4c4996308402d0f7b2fc6b8c44/userdata/ctr.log --exit-dir /var/run/libpod/exits --socket-dir-path /var/run/libpod/socket --log-level error
root       33480   33468  0 Mar20 ?        00:00:00 /bin/sh -c dotnet /jellyfin/jellyfin.dll --datadir /config --cachedir /cache
root      772395   24661  0 09:53 pts/2    00:00:00 grep --color=auto 33468
```

lsof hangs.  My storage server is hanging because two drives with bad sectors are causing problems.  They're in process of being replaced.  That cascades to my media server causing the mount point to hang.  Then the process hangs on to the mount point some how.  The only option is to reboot the media server to wipe out the process.  I thought containerizing would help the situation but so far no dice.

**Comment by Liggy** [comment]
Could this be related to the realtime monitoring of a library (under advanced library settings)? On Linux I think this uses the inotify mechanism.

**Comment by mazzystr** [comment]
Oh very interesting.  I can turn that option off.  My library is fairly static and doesn't need to be scanned more than once a day.  I'd even prefer a manual trigger via an api call.

**Comment by joshuaboniface** [comment]
@mazzystr I'm curious if turning that option off does fix this, please let us know!

**Comment by mazzystr** [comment]
Is that a bit that I can flip within the config.xml?  I can't risk starting jellyfin, having the process hang, and having to reboot right now.  I'm in a precurious situation with having 3 disks failing at the same time... Hurry up with that disk delivery newegg!

**Comment by Liggy** [comment]
Not sure about config.xml, but you can go to the dashboard -> Library in the left menu -> Select library (one by one if you have multiple) -> Activate "Show advanced settings" -> Uncheck "Enable real time monitoring"

**Comment by anthonylavado** [comment]
Hey @mazzystr, did you have a chance to test this?
Thanks!

**Comment by mazzystr** [comment]
Sorry I've been silent so long.  I've been struggling to prevent data loss and getting those drives replaced.  I should be stable tomorrow or Sunday and will be able to retest.
