### ISSUE TITLE
external ssd on mac

### ISSUE THREAD

**Issue by yalagin** [jellyfin/jellyfin#11414]
### Please describe your bug

jellyfin is crashing or not working at all

### Reproduction Steps

mac m2 
native install 
I set new media folder to /Volumes/ssd/media-folder

### Jellyfin Version

10.8.13

### Environment

```markdown
- OS: mac os sonoma
- Linux Kernel: no
- Virtualization:no
- Clients: no
- Browser: chrome
- FFmpeg Version: latest
- Playback Method: browser
- Hardware Acceleration: no
- GPU Model: m2
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
nope
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gnattu** [comment]
Use unstable builds or wait for 10.9 for proper Apple Silicon Support: https://jellyfin.org/docs/general/testing/server/macos

**Comment by yalagin** [comment]
@gnattu thanks
