### ISSUE TITLE
[Issue]: Jellyfin no longer auto populates Album Artists in 10.9

### ISSUE THREAD

**Issue by felix920506** [jellyfin/jellyfin#11412]
### Please describe your bug

Jellyfin no longer auto populates Album Artists with a list of all artists from the individual tracks if not specified specifically.

In 10.8, Jellyfin auto populates the album artists field using a list of artists of the individual tracks

### Reproduction Steps

1. Add music album without album artist tag to Jellyfin server and rescan
2. See Error

### Jellyfin Version

Unstable (master branch)

### Environment

```markdown
- OS: Windows, MacOS
- Linux Kernel: N/A
- Virtualization: None
- Clients: Web
- Browser: Firefox
- FFmpeg Version: 6.0.1-jellyfin, 6.1.1
- Playback Method: N/A
- Hardware Acceleration: N/A
- GPU Model: N/A
- Plugins: Default
- Reverse Proxy: None
- Base URL: N/A
- Networking: N/A
- Storage: SMB, Local APFS
```

### Jellyfin logs

```shell
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
This should have already been fixed by https://github.com/jellyfin/jellyfin/pull/11357

Please make sure you are up to date and test again

**Comment by felix920506** [comment]
Can confirm fixed on current unstable build
