### ISSUE TITLE
Simple windows Portable option!?

### ISSUE THREAD

**Issue by rezpower** [jellyfin/jellyfin#1142]
I want to be able to use jellyfin the same way I am using emby if possible. I have my server on windows 10 system. I have a folder called "Emby" on my drive D:\ and inside the folder I have two folders: "system" and "programdata". The emby executable is in "system" folder and when I run it it uses the programdata folder which has the "data", "config", "cache" etc folders.

I tried to achieve the same thing with jellyfin, but it creates its folders in "C:\Users\MyUserName\AppData\Roaming\jellyfin" and I don't know how to bypass this automation. 

Sorry for posting this here! I couldn't find the answer to my question by searching https://forum.jellyfin.org/

**Comment by LogicalPhallacy** [comment]
You can run Jellyfin with the -? flag to get the commandline switches. 

The ones of interest to you are -d (data directory) -C (Cache dir) and -c (config directory) 
so you could run Jellyfin like so

    jellyfin.exe -d D:\jellyfin\programdata -C D:\jellyfin\programdata -c D:\jellyfin\programdata 

Which would accomplish what you were hoping for.

**Comment by rezpower** [comment]
Thank you very much :)  it's worked perfect! But is it possible to somehow copy emby library and users to Jellyfin? I copied emby's programdada to jellyfin folder and it didn't work. Maybe have to import them differently?

**Comment by JustAMan** [comment]
There were possibilities to migrate, but you'd rather not try to :)
Incompatibilities in database are subtle, but may cause weird bugs later on.

So your best bet is to create users anew and use something like Trakt plugin to synchronize watched status between Emby and Jellyfin.

P.S. If your original concern is addressed could you please close the issue?

**Comment by rezpower** [comment]
Thanks a lot for all the precious help and info.

**Comment by seascape** [comment]
New user. Thought I'd share my experience here.
Checking [the Windows documentation](https://jellyfin.org/docs/general/administration/configuration) showed there are different command line flags now. Not sure if the old one still work, but these definitely do. My .bat file:

`jellyfin.exe --datadir "F:\Media\~Jellyfin_Server_Data\data" --configdir "F:\Media\~Jellyfin_Server_Data\config" --cachedir "F:\Media\~Jellyfin_Server_Data\cache" --logdir "F:\Media\~Jellyfin_Server_Data\logs"`

This seems to work as expected and puts everything in the specified, neatly contained folders.

To get rid of the resulting terminal window I use [the utility RBTray](http://rbtray.sourceforge.net/), as described [here](https://old.reddit.com/r/jellyfin/comments/krlq47/jellyfin_portable_opens_a_terminal_window_every/). A bit hackish but fine for now.
