### ISSUE TITLE
[Issue]: Make Jellyfin logs managable by logrotate

### ISSUE THREAD

**Issue by sleepy-nols** [jellyfin/jellyfin#11438]
### Please describe your bug

So I want to be able to manage Jellyfin logs with logrotate or have generally more controll over how log files are written. I am aware that there is a `logging.json` config file but I have found now way of removing the automatic daly rotate and appending of the date to the logfile name in there. Another problem is that fail2ban fails to automatically read the correct new log file after jellyfin rotates the log to a new file.

**current logfile format:**
`log_20240425.log`
`log_20240426.log`
or
`somecustomname20240425.log`

**wanted logfile format:**
`jellyfin.log`
`jellyfin1.log`

I have not yet found a way to disable the appending of the date to the logfile name and disable rotation in the Serilog .Net logging framework. 

**Possible Solutions:**
Somehow make configurable via Serilog

**Current quickfix**
Use jellyfin systemd service override to write stdout to a logfile and remove file logging in the `logging.json`

I will happily provide a merge request but want to evaluate the possible best solution before with yall.
This is not exaclty a bug nor a feature requst so I dont know if this is the right place.

### Reproduction Steps

Run latest Jellyfin version on debian bookworm.

### Jellyfin Version

10.8.13

### Environment

```markdown
- OS: Debian 12
- Linux Kernel: 6.1
- Virtualization: incus
- Clients: /
- Browser: /
- FFmpeg Version: /
- Playback Method:
- Hardware Acceleration: /
- GPU Model: /
- Plugins: /
- Reverse Proxy: /
- Base URL: /
- Networking: /
- Storage: /
```

### Jellyfin logs

```shell
/
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
Closing as this isn't a bug. You should be able to achieve most of what you want by doing something like this:

```diff
{
    "Serilog": {
        "WriteTo": [
            {
                "Name": "Console",
                "Args": {
                    "outputTemplate": "[{Timestamp:HH:mm:ss}] [{Level:u3}] [{ThreadId}] {SourceContext}: {Message:lj}{NewLine}{Exception}"
                }
            },
            {
                "Name": "Async",
                "Args": {
                    "configure": [
                        {
                            "Name": "File",
                            "Args": {
+                                "path": "%JELLYFIN_LOG_DIR%//log.log",
-                                "path": "%JELLYFIN_LOG_DIR%//log_.log",
-                                "rollingInterval": "Day",
-                                "retainedFileCountLimit": 3,
-                                "rollOnFileSizeLimit": true,
-                                "fileSizeLimitBytes": 100000000,
                                "outputTemplate": "[{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz}] [{Level:u3}] [{ThreadId}] {SourceContext}: {Message}{NewLine}{Exception}"
                            }
                        }
                    ]
                }
            }
        ],
        "Enrich": [ "FromLogContext", "WithThreadId" ]
    }
}

```

**Comment by felix920506** [comment]
Closing this issue as a feature request. 

If you would like to implement it yourself, please open a discussion on the repo containing the following:
- how you would like your implement the feature (you don't need a working implementation but you should have a rough idea)
- what is the problem with the current system and why we should have this feature

**Comment by sleepy-nols** [comment]
so after a lot of digging in various repos and learning dotnet I finally found a solution.

to leave the logfile completely untouched my serilog except of course logging, we have to set `rollingInterval` to `Infinite` as in [1], `rollOnFileSizeLimit` to `false` and `retainedFileCountLimit` to `null` [2]. This way we can fully manage the file with logrotate and have no issues with fail2ban.  
```json
"Name": "File",
  "Args": {
    "path": "%JELLYFIN_LOG_DIR%//jellyfin.log",
    "rollingInterval": "Infinite",
    "retainedFileCountLimit": null,
    "rollOnFileSizeLimit": false,
    "outputTemplate": "[{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz}] [{Level:u3}] [{ThreadId}] {SourceContext}: {Message}{NewLine}{Exception}"
  }
```

some references to my research:
[1] https://github.com/serilog/serilog-sinks-file/blob/main/src/Serilog.Sinks.File/Sinks/File/RollingIntervalExtensions.cs#L25
[2] https://github.com/serilog/serilog-sinks-file/blob/dev/src/Serilog.Sinks.File/FileLoggerConfigurationExtensions.cs

**Comment by Henkow** [comment]
> so after a lot of digging in various repos and learning dotnet I finally found a solution.
> 
> to leave the logfile completely untouched my serilog except of course logging, we have to set `rollingInterval` to `Infinite` as in [1], `rollOnFileSizeLimit` to `false` and `retainedFileCountLimit` to `null` [2]. This way we can fully manage the file with logrotate and have no issues with fail2ban.
> 
> ```json
> "Name": "File",
>   "Args": {
>     "path": "%JELLYFIN_LOG_DIR%//jellyfin.log",
>     "rollingInterval": "Infinite",
>     "retainedFileCountLimit": null,
>     "rollOnFileSizeLimit": false,
>     "outputTemplate": "[{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz}] [{Level:u3}] [{ThreadId}] {SourceContext}: {Message}{NewLine}{Exception}"
>   }
> ```
> 
> some references to my research: [1] https://github.com/serilog/serilog-sinks-file/blob/main/src/Serilog.Sinks.File/Sinks/File/RollingIntervalExtensions.cs#L25 [2] https://github.com/serilog/serilog-sinks-file/blob/dev/src/Serilog.Sinks.File/FileLoggerConfigurationExtensions.cs

Do you reckon this could become an issue when the log file grows very large? Figured both in terms of fail2ban having to swift through a lot of data, but also accessing the log file through the web GUI.
