### ISSUE TITLE
Help Needed！Some troubles about  .strm

### ISSUE THREAD

**Issue by Akimio521** [jellyfin/jellyfin#11446]
Hi, I've been having some trouble with Jellyfin recently that I haven't been able to figure out, so I'm reaching out here for help.

I read in the Jellyfin documentation that it supports files with the ".strm" extension. I put an HTTPS URL link into a .strm file (opening this URL in a browser downloads an MKV video file directly). When I play this .strm file in Jellyfin, I found that the client tries to access the URL address in the .strm file. If the access is successful, the video file is obtained directly from the URL, and all traffic does not go through the Jellyfin server, unless the client cannot access the URL in the .strm file normally or the client requests transcoding.

However, after I added multiple .strm files, I found that the client no longer tries to access the URL, but instead the server directly streams the media. This takes up Jellyfin server bandwidth and wastes resources, which I don't want. What should I do?

**Comment by felix920506** [comment]
Please head to our chat rooms for support. https://jellyfin.org/contact
