### ISSUE TITLE
[Issue]: Chapters are extracted twice

### ISSUE THREAD

**Issue by enter-a-random-username** [jellyfin/jellyfin#11455]
### Please describe your bug

In case a library uses instant gen chapter settings the chapters will be added (works as excepted, starts a lot of parallel processes).
On next "Extract chapter images" run the same files will get extracted again with a single process.

### Reproduction Steps

1. As described in the bug report, check both chapter related boxes and add a file.
2. Add a file and monitor processes. Chapters will be generated.
3. Start the scheduled task, same file get extracted again.

### Jellyfin Version

Unstable (master branch)

### Environment

```markdown
- OS:
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
No useful log, there no error/exception.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by systemcrash** [comment]
See https://github.com/jellyfin/jellyfin-web/issues/5436
