### ISSUE TITLE
Add automatic updates functionality

### ISSUE THREAD

**Issue by realies** [jellyfin/jellyfin#1146]
It would be great if Jellyfin can auto-update and restart itself when not in use.

**Comment by JustAMan** [comment]
I believe this feature was explicitly removed.

Normal software doesn't update itself, it notifies the administrator who then uses OS-specific mechanisms to update the software.

Also in certain cases (like Debian or Docker installation) it is impossible to update without either adding too much permissions to Jellyfin or adding some ugly hacks.

**Comment by realies** [comment]
Would be happy if there is one less thing to manually update. Not aware of a straight-forward OS-specific update mechanisms for Windows. Perhaps a section in the web interface saying there is a new version might be a good start. Is something that reloads the application on update what you refer to as ugly hacks?

**Comment by JustAMan** [comment]
cc @LogicalPhallacy for Windows-specific install things

**Comment by joshuaboniface** [comment]
Yes, this was explicitly removed. This is something that should be left up to the administrator entirely IMO. For most platforms, automatic update is at best a nightmare to implement, and at worse contrary to what admins want. I'm personally wholly against the idea, I never want software to update itself without my explicit command to do so.

That said there could always be a "check for updates", but I don't think actually applying those updates should be done automatically. The reload isn't the problem, the hack is including spaghetti code inside the app to say "if Windows, download .exe and run .exe; if Debian, run apt update" etc. and then handling the numerous inevitable failure modes and then supporting that functionality. Just look at the problems an automatic DB migration caused to Emby - I don't want to go that direction.

**Comment by realies** [comment]
The reason for creating this issue is that the process of manually checking for an update every now and again, downloading the portable zip, stopping the server, replacing the files and starting it again is not the most joyful process. From my perspective, automating this and having the functionality integrated in the software would be ideal. If the development team compares this to a nightmare, I am absolutely happy to cobble something together that does exactly the same and runs separately to Jellyfin.

Appreciate the exaggeration of automation risks, not aware of the case mentioned, although what would have been better than an automatic DB migration? Asking the users to migrate the DB themselves?

**Comment by anthonylavado** [comment]
@realies  The danger isn’t doing the DB migration, it’s having it happen automatically, outside of your control. We can test as much as we want, but everyone’s set up is different. Bugs in other software as well as our own releases have taught us that, and we need to be careful. We need to give users sufficient warning, something I feel we don’t do enough as is 😄

That said, if you or anyone else would like to make an assistant to do this for Windows, I think we’d be happy to link to it as an unofficial resource ✨

**Comment by cvium** [comment]
Just to add some perspective. Plex is a very mature software, but even they don't do automatic updates. You actually have to download a .deb and install it manually with dpkg.

**Comment by realies** [comment]
Was initially thinking of scripting it up with something like AutoIt, although your suggestion of Powershell sounded like a better approach. No experience with the language so far, although this seems to work - https://github.com/realies/jellyfin-autoupdate/blob/23d296a58853661a694714c6073a7654aa087498/jellyfin-autoupdate.ps1

It still needs to install itself as a cron job that runs with administrative privileges (access to services) and Jellyfin has to be installed as a service at the default install location. Perhaps the script should copy itself in the same folder and be executed from there. Open for any suggestions on improvements and sweet dreams.

**Comment by LogicalPhallacy** [comment]
@realies that is a good script and basically the way that updating a windows service in the vein of jellyfin should be done. When we get around to an MSI and native windows service install (its coming promise) it could use some tweaking and we might be able to strip some steps out, but the downloading and installing of updated bits as well as the service restart are going to be on the server owner, either by a scheduled task script or by hand at their leisure.

**Comment by realies** [comment]
Thanks for having a look. Is transitioning/addition of MSI scheduled for anytime soon? Automated updates should be a decision of the server owner and I have not stated otherwise since the beginning of this issue. The idea is that _adding the option for doing so_ should be part of the updater tool, making everything easier.

**Comment by anthonylavado** [comment]
>Automated updates should be a decision of the server owner and I have not stated otherwise since the beginning of this issue. The idea is that _adding the option for doing so_ should be part of the updater tool, making everything easier.

@realies Sorry for the misunderstanding. I think we assumed you wanted the same behaviour as Emby, which is indeed automatic updates. This was built in until we removed it early on.

Regarding the MSI and other bits, I think we were waiting for .NET 3.0. Is that right @LogicalPhallacy?

**Comment by realies** [comment]
I should have been more verbose. Eventually, my intended usage for this was for it to be fully autonomous. Defaulting to a UI notification of the availability of a new version without performing any updates is indeed a more rational approach considering potential unhandled situations. Integrated software updating and reloading feature is a useful thing to have if a user deems the risks involved.

In any case better than third-party scripts that attempt to do the same without having any knowledge of the activity of the server at that given moment.

**Comment by JustAMan** [comment]
I guess this could be implemented as a plugin (that is, measuring server activity and presence of updates, and executing some user-defined external script to do actual update).

**Comment by LogicalPhallacy** [comment]
A plugin or even an update notification being part of core would be a nonissue. Triggering a script on said notification does shift into the plugin realm more though.

The plan was to wait until netcore3 drops to do some of this windows work because it makes adding back in the features that emby used to have (that they also removed or mangled) of minimize to tray and native windows service support significantly easier. Right now to implement minimize to tray I'd need to have a DotNetFramework 4.x application that effectively wraps Jellyfin as a consolehost, which adds needless complexity for windows users. Native windows service support is not so dire, but its still an irritation. 

As for packaging as an MSI, that's do-able now, and I imagine that just about anything would be better than our current terrible powershell installer. A simple MSI option could be prioritized, with a more complex one to come when native service support is back in.
