### ISSUE TITLE
[Issue]: Youtube-Trailers no longer working

### ISSUE THREAD

**Issue by schlumpfilein** [jellyfin/jellyfin#11460]
### Please describe your bug

Jellyfin always had some trailers not working, thats not a problem and expected. But for quite some time now absolutly no trailer is working any longer. If you use the web frontend you get the attached errormessage attached with this issue.

If you use the android/ios client, you just get the same login-screen as if the server would be down/not available. You can just log in again, so there's no problem with the server itself - but if you try to play a trailer the same happens again

Two things to mention:

1.) the log shows no error-message or anything
2.) If i use the web frontent and click the trailer-button, it shows the youtube player-interface before it failes and the message appears. If I click the "youtube" icon in the corner of the screen (its the icon you use to watch a video not on the site you are currently on but directly on youtube) the trailer runs fine.

Maybe this is a problem caused by youtube changing their software? They are trying to prevent people from evading ads, so maybe this caused a problem with jellyfin?

### Reproduction Steps

1.) Docker is running on a synology NAS (trailers ran fine for a year or so)
2.) Choose any movie you want, that has a trailer available (youtube), and try to play it.

### Jellyfin Version

10.8.13

### Environment

```markdown
- OS: Synology
- Virtualization: docker
- Browser: Every browser has the same behavior
- Networking: network works fine for any other purpose, internet-connection is stable
```

### Jellyfin logs

```shell
Log shows no errors or anything
```

### Please attach any screenshots here

![image](https://github.com/jellyfin/jellyfin/assets/70749414/42e223f7-59e9-4243-b5a8-8be945f2d97e)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
Please attach browser logs.

**Comment by schlumpfilein** [comment]
Hey Felix, thank you very much for trying to help me.

I just assumend that the problem was caused by youtube changing, and never really looked in to it....it was my ghostery-plugin that prevented the playback in the browser. I feel quite dumb right now.. :-(

So the only devices not playing the trailers right now are android based systems. Since that is not very important to me, I would close this issue, thank you (and everyone looking) for their time - and I'm sorry that i bothered you you with my mistake.
