### ISSUE TITLE
[Issue]: Plugin Logging is not possible in version 10.8.13

### ISSUE THREAD

**Issue by hexxone** [jellyfin/jellyfin#11488]
### Please describe your bug

My issue is very similar to https://github.com/jellyfin/jellyfin/issues/3881 and https://github.com/jellyfin/jellyfin/issues/11359 .

The problem is, currently I am unable to get any Logging in my Plugin to work. 
No matter if I try to use `ILogger` or `ILogger<SpecificType>` or `ILoggerFactory` in my Controller-constructor, they always fail to resolve via Dependency-Injection when the Controller is instantiated.

For example:
![image](https://github.com/jellyfin/jellyfin/assets/5312542/5dbe8cec-4f69-41d4-a06f-c8e7b1ac3c61)

So, what is the correct way of Logging for/in Plugins?

There is no example provided within the [jellyfin-plugin-template](https://github.com/jellyfin/jellyfin-plugin-template) or anywhere else I could find.

### Reproduction Steps

I have curerntly compeltely removed Logging from [my plugin](https://github.com/hexxone/TeleJelly)..

But if needed, I can re-add it on a separate branch for you to check-out and reproduce.

### Jellyfin Version

10.8.13

### Environment

```markdown
- OS: latest Docker image and Windows (10.8.13)
- Virtualization: Docker
- Clients: Browser
- Browser: Brave
```

### Jellyfin logs

```shell
Sorry, I only took a screenshot at the time and have restarted several times since then..
But basically it fails on Dependency Injection resolving constructor arguments.

![image](https://github.com/jellyfin/jellyfin/assets/5312542/5dbe8cec-4f69-41d4-a06f-c8e7b1ac3c61)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
According to the issue report you linked it is already fixed on master. Closing.

**Comment by hexxone** [comment]
> According to the issue report you linked it is already fixed on master. Closing.

It's great this is already fixed for the future, but the "latest" docker version is still 10.8.13. When will we see these fixes then?

And the question "what is the correct way of Logging for/in Plugins?" also still remains. 
Or should all of my mentioned methods actually work?

Thanks.

**Comment by felix920506** [comment]
> When will we see these fixes then?

When 10.9 comes out 

> And the question "what is the correct way of Logging for/in Plugins?" also still remains.
Or should all of my mentioned methods actually work?

This question can be asked in our development channel on Matrix or Discord. https://jellyfin.org/contact

**Comment by crobibero** [comment]
> And the question "what is the correct way of Logging for/in Plugins?" also still remains.
Or should all of my mentioned methods actually work?

`ILogger<T>` or `ILoggerFactory` both work for logging.

**Comment by hexxone** [comment]
> `ILogger<T>` or `ILoggerFactory` both work for logging.

Thank you for clarifying 👍
