### ISSUE TITLE
"Next Up" section is offering the next unwatched episode after the last watched episode instead of the first unwatched episode

### ISSUE THREAD

**Issue by BradenWentworth** [jellyfin/jellyfin#11483]
### Please describe your bug

The "Next Up" section is offering me Twilight Zone S4.E1 which is the first unwatched episode after the last watched episode of the series.
![image](https://github.com/jellyfin/jellyfin/assets/7004039/a985dd3f-7baa-4f82-8319-819a9bd5592b)

Instead of S2.E17 which is the first unwatched episode in the series.
![image](https://github.com/jellyfin/jellyfin/assets/7004039/bf43d154-f1c3-4c48-817e-7849d65f8c7c)

My expectation (and for reference the behavior seen in Plex) is to always offer the first unwatched episode in the series regardless of weather or not you have unwatched episodes earlier in the series.
![image](https://github.com/jellyfin/jellyfin/assets/7004039/beff118c-2125-491e-98f4-02116cc9de0b)

### Reproduction Steps

just pick any unwatched series and watch an episode in the middle, then see the "Next Up" section offer you the episode following the one you just watched instead of the first unwatched episode in the series

### Jellyfin Version

10.8.13

### Environment

```markdown
- OS: windows 10 pro 64bit
```

### Jellyfin logs

```shell
n/a
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
Working as intended

**Comment by BradenWentworth** [comment]
> Working as intended

why is this the intended method? to me it seems so strange this way.
cant there be an option/setting to do it how plex does it?

**Comment by joshuaboniface** [comment]
Short answer: because that's how Emby did it and we've never changed it.

But my understanding of the logic is, Jellyfin knows the last episode you played, and presumes that the next thing you will want to watch is the next episode after that one, not an earlier episode. Personally I agree with the logic, even though Plex does it differently.

Making this configurable is possible I believe, but would be a feature request and setting, not a bugfix.

**Comment by BradenWentworth** [comment]
Can this ticket be relabeled as a feature request or do I need to resubmit it?

**Comment by felix920506** [comment]
If you would like to submit a feature request, please do so at https://features.jellyfin.org
The GitHub issue tracker isn't open to feature requests.
