### ISSUE TITLE
[Issue]: Installation on Ubuntu Server fails (jellyfin-ffmpeg5 not installable)

### ISSUE THREAD

**Issue by BorisBrock** [jellyfin/jellyfin#11490]
### Please describe your bug

I just set up a fresh machine with Ubuntu Server. After `apt update` I used the install script from the Jellyfin docs:
```
curl https://repo.jellyfin.org/install-debuntu.sh | sudo bash
```
This runs into the following error:

> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
>  jellyfin : Depends: jellyfin-ffmpeg5 (>= 5.0.0) but it is not installable
> E: Unable to correct problems, you have held broken packages.

Is there any way to fix the installation?

### Reproduction Steps

1. Install Ubuntu Server
2. Do `apt update`
3. Install Jellyfin: `curl https://repo.jellyfin.org/install-debuntu.sh | sudo bash`

### Jellyfin Version

10.8.13

### Environment

```markdown
- OS: Ubuntu Server 29.04 AMD64
- Linux Kernel: 6.x
```

### Jellyfin logs

```shell
Installation fails, so there are no logs yet.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gratiachristi95** [comment]
Can you please provide your sudo apt edit-sources so we can see your repos you are pulling from?

**Comment by gnattu** [comment]
Jellyfin 10.8 won’t support Ubuntu Noble. You have to use 10.9

**Comment by BorisBrock** [comment]
> Jellyfin 10.8 won’t support Ubuntu Noble. You have to use 10.9 or deploy with docker

Doesn't the install script automatically install the latest version?

**Comment by gnattu** [comment]
> > Jellyfin 10.8 won’t support Ubuntu Noble. You have to use 10.9 or deploy with docker
> 
> Doesn't the install script automatically install the latest version?

The problem is, the 10.9 is not the latest stable version, it is unstable which will not be installed by this script.
