### ISSUE TITLE
.NET Version

### ISSUE THREAD

**Issue by RazeLighter777** [jellyfin/jellyfin#115]
Are we only supporting .NET 2.2 here and not other versions or Mono? Knowing this, we could simplify the build process by removing the arguments for .NET versions in the Dockerfile and possibly the debian package.

**Comment by nvllsvm** [comment]
We have deprecated support for Mono. https://github.com/jellyfin/jellyfin/issues/95

**Comment by RazeLighter777** [comment]
@nvllsvm Anything about the .NET version?

**Comment by nvllsvm** [comment]
We're targeting [.NET Standard 2.0](https://github.com/dotnet/standard/blob/master/docs/versions/netstandard2.0.md)

**Comment by nvllsvm** [comment]
We're targeting the latest stable .NET Core. I don't know enough about it to know what will break in older versions.

**Comment by Uatschitchun** [comment]
Sorry if I'm asking here, but it seems on topic...
There's no 32bit dotnet for Linux? My server's still on 32bit, so that's why I'm asking.

**Comment by nvllsvm** [comment]
@Uatschitchun - 32bit x86 support can be another topic of itself. I don't see a good reason one should be using it so I'm inclined to not care about it. Open to feedback.

**Comment by joshuaboniface** [comment]
.NET Core is indeed not supported by Linux at all, that's all on Microsoft. We're using 2.2 now as well. The recommendation should be to use `amd64` if at all possible (barring the occasional old Atom board that was 32-bit only). Closing this issue out.

**Comment by joshuaboniface** [comment]
Correction: we're still using 2.1, not 2.2, as it is the current stable. If requested, we should add a new issue to track 2.2 adoption specifically. I think the original question was answered however.
