### ISSUE TITLE
[Issue]: Lyrics with timestamps in 3 decimal places can't be recognized as synced

### ISSUE THREAD

**Issue by yoooogaQAQ** [jellyfin/jellyfin#11518]
### Please describe your bug

The synced lyrics files in my library have mixed timestamp formats, timestamp in 2 decimal places can be recognized by Jellyfin as synced, whereas timestamp in 3 decimal places cannot.

### Reproduction Steps

1. Place a LRC file next to a song file with the timestamp format like this:
[00:25.831]Lorem ipsum
[00:32.307]Lorem ipsum
[00:38.618]Lorem ipsum
2. Scan the library
3. Play the song
4. The lyrics are recognized as un-synced lyrics

Temporary solution:
1. Truncate the timestamp to 2 decimal places
2. The lyrics are successfully recognized as synced lyrics

### Jellyfin Version

Unstable (master branch)

### Environment

```markdown
- OS: Debian 12
- Linux Kernel: 6.1.21-v8+
- Virtualization: Docker
- Clients: Browser, Finamp
- Browser: Firefox 125.0.3
- FFmpeg Version: 6.0.1-Jellyfin
- Playback Method: Direct Play
- Hardware Acceleration: None
- GPU Model:
- Plugins:
- Reverse Proxy: Caddy
- Base URL: None
- Networking: Host
- Storage: local
```

### Jellyfin logs

```shell
N/A
```

### Please attach any screenshots here

![1](https://github.com/jellyfin/jellyfin/assets/17782472/8c19554b-0aa9-434d-87a0-09499ba4c84a)
![2](https://github.com/jellyfin/jellyfin/assets/17782472/8f752a0d-f91e-4dbf-b1e6-7c86a907417e)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Shadowghost** [comment]
This is an issue with the library we use.

**Comment by mihawk90** [comment]
In the same vein, timestamps without decimals (i.e. `[mm:ss]`) are not recognised either.
I haven't been able to test single-digit decimals but I wouldn't be surprised if it's affected as well.

> This is an issue with the library we use.

What library are you using, and is there an issue upstream we can track?

**Comment by congerh** [comment]
> What library are you using

[karaoke-dev/LrcParser](https://github.com/karaoke-dev/LrcParser)

> is there an issue upstream we can track

[karaoke-dev/LrcParser#40](https://github.com/karaoke-dev/LrcParser/issues/40)

**Comment by andy840119** [comment]
https://github.com/karaoke-dev/LrcParser/issues/40

New package update released
This issue should be fixed also.

**Comment by Reapor-Yurnero** [comment]
Second the above. We should be able to fix this issue now!
