### ISSUE TITLE
[Issue]: After upgrade to 10.9 scans randomly set creation date

### ISSUE THREAD

**Issue by JPVenson** [jellyfin/jellyfin#11522]
### Please describe your bug

After updating an existing Jellyfin server to the latest unstable version and rescanning a library afterwards, random media elements get sorted into the "newly added" home sections and are sorted wrongly on the library view.

### Reproduction Steps

1. Update an existing jellyfin server to 10.9 unstable, where there are more then 20 movies and 10 series
2. Make a full scan
3. random items get sorted incorrectly as new

### Jellyfin Version

10.8.13

### Environment

```markdown
- OS: Docker
- Linux Kernel:
- Virtualization:
- Clients: DefaultWebUI
- Browser: Edge
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy: Traefik
- Base URL:
- Networking:
- Storage: Read-Only SMB share for media and volume mount for data
```

### Jellyfin logs

```shell
Left Unstable, Right 10.8.13
```

### Please attach any screenshots here

![image](https://github.com/jellyfin/jellyfin/assets/6794763/aa9e0b9b-9aaa-4df8-870f-be4e5bdb3c92)
![image](https://github.com/jellyfin/jellyfin/assets/6794763/cb16c121-ffe0-4cd9-933d-8603d9ce606a)
![image](https://github.com/jellyfin/jellyfin/assets/6794763/1999edc0-c03b-4056-9aee-d916ae3ca7f3)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JPVenson** [comment]
Confirmed to still happen in 10.9.1 release.

**Comment by Shadowghost** [comment]
@JPVenson can you check if reverting the above PR fixes it for you? I kinda doubt it, but I want to be sure.

**Comment by JPVenson** [comment]
@Shadowghost can try tonight
