### ISSUE TITLE
[Issue]: Subtitles no longer in sync (build: 2024050906)

### ISSUE THREAD

**Issue by systemcrash** [jellyfin/jellyfin#11527]
### Please describe your bug

Subtitles perfectly in sync on 2024050117

Subtitles are not in sync on build: 2024050906

Sync is perfect in a desktop player like iina or VLC.

### Reproduction Steps

Play media with subs. 
Turn subs on.
Subs out of sync (whether included form play start or turned on during play). By default, the subs are at least a few seconds early.

### Jellyfin Version

Unstable (master branch)

### Environment

```markdown
- OS:
- Linux Kernel: Linux version 4.4.302+ (root@build5) (gcc version 12.2.0 (GCC) ) #69057 SMP Fri Jan 12 17:02:28 CST 2024
- Virtualization: Docker
- Clients: yes
- Browser: FF 125
- FFmpeg Version: latest jellyfin
- Playback Method: press play
- Hardware Acceleration: 
- GPU Model: -
- Plugins: -
- Reverse Proxy: -
- Base URL: -
- Networking: yes
- Storage: ofc
```

### Jellyfin logs

```shell
none (that reveal anything helpful)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gnattu** [comment]
> none (that reveal anything helpful)

Please don't make assumptions. If there is a log please attach it, if there is no log please say no log.

**Comment by systemcrash** [comment]
Actually, the pattern here is different. Even 0501 does not sync subs in some instances, and I have not found commonality yet. I'll spend a bit more time on this....
