### ISSUE TITLE
[Issue]: Cannot upgrade to 10.9

### ISSUE THREAD

**Issue by badmark** [jellyfin/jellyfin#11531]
### Please describe your bug

Try to update via apt update there is no newer version

### Reproduction Steps

Try to update via apt update there is no newer version

### Jellyfin Version

10.8.13

### Environment

```markdown
- OS: Linux
- Linux Kernel: Debian
- Virtualization: LXC
- Clients: Linux Web
- Browser: Chrome
- FFmpeg Version: 
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
Latest version shown in repo is the current one but I just received notification of 10.9
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by badmark** [comment]
I added all that is needed. If I get a notification of a new release I expect to be able to upgrade to it...

**Comment by nielsvanvelzen** [comment]
10.9 is still releasing.

**Comment by joshuaboniface** [comment]
It should be up now. Jumping on releases the second they're published to GitHub leaves no time for the CI to build. Please wait for the release announcement in our Matrix and/or Forums which only happens after CI builds complete.

**Comment by badmark** [comment]
Shouldn't the release notification go out after CI is complete and the update is published?

**Comment by oddstr13** [comment]
The GitHub release notification goes out when the release is *tagged*.

Only *after* that has been done, the compilation of the different parts can start.
