### ISSUE TITLE
[Issue]: Unable to play hardlinked files that are still seeding (unless seeding is paused)

### ISSUE THREAD

**Issue by kingp0dd** [jellyfin/jellyfin#11552]
### Please describe your bug

- torrent download gets completed
- radarr/sonarr hardlinks the file from torrent folder into my media folder
- torrent file in torrent folder continues to seed
- jellyfin unable to play the hardlinked file

When I pause the seeding torrent, the file plays in Jellyfin with no issues

### Reproduction Steps

- torrent download gets completed
- radarr/sonarr hardlinks the file from torrent folder into my media folder
- torrent file in torrent folder continues to seed
- jellyfin unable to play the hardlinked file

This has been happening even before the 10.9 update
Radarr/sonnar and qBittorrent all in the latest versions

### Jellyfin Version

10.9.0

### Environment

```markdown
- OS: Debian 12 Docker
```

### Jellyfin logs

```shell
ffmpeg version 6.0.1-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.4.0-1ubuntu1~22.04)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
libva info: VA-API version 1.21.0
libva info: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_21
libva info: va_openDriver() returns 0
libva info: VA-API version 1.21.0
libva info: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_21
libva info: va_openDriver() returns 0
file:/media/TV/Clarkson's Farm/Season 3/Clarksons.Farm.S03E06.Mushrooming.2160p.AMZN.WEB-DL.DDP5.1.HDR.H.265-FLUX.mkv: Invalid argument
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
There is no support for torrenting.

**Comment by FabioEight** [comment]
@crobibero can you please explain why I can open/stream the same file (with no transcoding) directly (while seeding it) via any player, and why this doesn't work via Jellyfin?

**Comment by Fred-0107** [comment]
@kingp0dd have you found a solution? im having the exat same problem, and can't seem to find a solution

**Comment by kingp0dd** [comment]
Still nothing

**Comment by GodlyJaaaj** [comment]
same problem here

**Comment by Tobo7** [comment]
Same problem

**Comment by GodlyJaaaj** [comment]
@Tobo7 i found something, if you use jellyfin with "ro" mode in the docker compose then it seems to work even when seeding.

<img width="418" height="359" alt="Image" src="https://github.com/user-attachments/assets/37c2994e-ba6e-489c-97ac-10626f1ba535" />

<img width="282" height="32" alt="Image" src="https://github.com/user-attachments/assets/a2137e4d-732c-4dd7-b5cd-1ae9c3af80a9" />

i tried with this avatar movie and as you can see it's still seeding at the same time


and this is my jenkins config 

<img width="917" height="589" alt="Image" src="https://github.com/user-attachments/assets/91dbb2d9-ba15-4275-b9d1-6ce67b88876e" />

**Comment by Alexis1war** [comment]
Same issue

**Comment by Coliinnn** [comment]
I had the same issue as well. Using NFS instead of Samba solved it for me.

**Comment by Ggjorven** [comment]
Did anyone find a solution for this?

**Comment by Tobo7** [comment]
Switch from Samba to NFS fixed it 🥳
