### ISSUE TITLE
[Issue]: Missing playlists after 10.9.0 update

### ISSUE THREAD

**Issue by FrenchGithubUser** [jellyfin/jellyfin#11558]
### Please describe your bug

The folder `/var/lib/jellyfin/data/playlists` contains more folders than the amount of playlists displayed in jellyfin.

Before updating, I had 44 playlists in jellyfin (which is the amount of folders in the `playlists` dir), and now only 33. The amount of songs in the playlists seem to be right though.

### Reproduction Steps

update to 10.9.0

### Jellyfin Version

10.9.0

### Environment

```markdown
- OS:debian 12
- Linux Kernel:6.1.0-18-amd64
- Virtualization:none
- Clients:jellyfin-media-player 10.9.0
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
none
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shadowghost** [comment]
10.9 transformed playlists to be user specific. If you have playlists created by another user, you don't have access as other users anymore.

**Comment by FrenchGithubUser** [comment]
> 10.9 transformed playlists to be user specific. If you have playlists created by another user, you don't have access as other users anymore.

is there a way to assign all playlists to a single user ? I tried editing the field `OwnerUserId` but that didn't change anything in jellyfin

**Comment by Shadowghost** [comment]
Playlists have the field Open access, setting it to true grants all users read access.
We have a full ACL logic with sharing in place but the interface for it wasn't ready for 10.9

**Comment by FrenchGithubUser** [comment]
> Playlists have the field Open access, setting it to true grants all users read access. We have a full ACL logic with sharing in place but the interface for it wasn't ready for 10.9

I added `<OpenAccess>true</OpenAccess>` after the `RunningTime` tag, but even after rescanning playlists, it is not accessible by other users. Did I make a typo ?

**Comment by FrenchGithubUser** [comment]
I ended up finding the api docs : https://api.jellyfin.org/#tag/Playlists/operation/UpdatePlaylist

And sending a request to my server for each playlist : 

```
{
  "Users": [
    {
      "UserId": "user-id",
      "CanEdit": true
    }
  ],
  "IsPublic": true
}
```

On : https://your-server-url.ext/Playlists/playlist-id

**Comment by dmill-bz** [comment]
For those landing here, I had an issue with this as well (all my playlists vanished). The fix was to update the date in the xml files since it was referencing 01/01/0001 00:00:00. 
You can do it directly in the XML or if you create a new "testing" playlist in the UI, it will likely show the other playlists at that point. You can then edit metadata and set any date (ex: 02/02/2020) and you should be good to go and can delete the "testing" playlist.
