### ISSUE TITLE
[Issue]: How long should Tickplay generation should take?

### ISSUE THREAD

**Issue by iChristGit** [jellyfin/jellyfin#11560]
### Please describe your bug

I just updated to latest Jellyfin version, trying to add scrub feature using tickplay, 
I have thousands of tv episodes and hundreds of movies, currently after two hours im at 3.7%
Is that normal?
Also, what size it should take for a large library? lets say how many Mb's per 20 minute episode? 

My HW is i7-12700KF-64GB ram+3090Ti, Win11

Its not an issue, just wondering how long it can take, and if there is options to make it quicker.

### Reproduction Steps

1.No issue or erros, just a question

### Jellyfin Version

10.9.0

### if other:

Win11

### Environment

```markdown
- OS: Win11
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model: 3090
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
No error logs
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jumoog** [comment]
Yes thats normal at your size.

**Comment by iChristGit** [comment]
> Yes thats normal at your size.

Thank you!
Il let it run overnight.
Do you know how much storage a 20 minute show take for the tickplay files? or for example a 2 hour movie? 
I wonder how much space needed for all the tickplay files.

**Comment by gnattu** [comment]
> > Yes thats normal at your size.
> 
> Thank you! Il let it run overnight. Do you know how much storage a 20 minute show take for the tickplay files? or for example a 2 hour movie? I wonder how much space needed for all the tickplay files.

It is usually < 10MB per hour video for the default setting. Actual value may vary but should not differ from this too much.

**Comment by iChristGit** [comment]
> > > Yes thats normal at your size.
> > 
> > 
> > Thank you! Il let it run overnight. Do you know how much storage a 20 minute show take for the tickplay files? or for example a 2 hour movie? I wonder how much space needed for all the tickplay files.
> 
> It is usually < 10MB per hour video for the default setting. Actual value may vary but should not differ from this too much.

Roger that!
Closing this "issue", thanks
