### ISSUE TITLE
AutoDiscoveryHost still returns wrong address

### ISSUE THREAD

**Issue by selfhoster1312** [jellyfin/jellyfin#11564]
This follows #10005 being closed.

The automatic server discovery code is still broken after upgrade to Jellyfin v10.9.

```
$ echo -n 'Who is JellyfinServer?' | socat - udp-datagram:255.255.255.255:7359,broadcast
{"Address":"http://127.0.0.1:8095/media","Id":"REDACTED","Name":"REDACTED","EndpointAddress":null}
```

The jellyfin server is behind a reverse proxy, and listens only to localhost for security reasons. I'm not sure which setting between `KnownProxies` and `PublishedServerUriySubnet` should be used here, but returning 127.0.0.1 is wrong.

The jellyfin network config is aware of the reverse proxy, as i set in /etc/jellyfin/network.xml:

```
  <KnownProxies>
    <string>https://REDACTED/media</string>
  </KnownProxies>
  <PublishedServerUriBySubnet>
    <string>https://REDACTED/media</string>
  </PublishedServerUriBySubnet>
```

I can understand the need for people to return different URL depending on the subnet querying the server, but for me a single URL is ok.

This is blocking https://github.com/jellyfin/jellyfin-media-player/issues/168 for example. It's very annoying to onboard users to have to type the complete URL.

**Comment by gnattu** [comment]
If you really want to override the announced url, you need to write the full url and set it as `JELLYFIN_PublishedServerUrl` environment variable, only this env variable will be picked up by auto discovery.

**Comment by selfhoster1312** [comment]
Thanks for the quick answer. So from what i can read there is also a [CLI flag](https://github.com/jellyfin/jellyfin/blob/25c23af8659700909995ca9c91c5dafccc6d348b/Jellyfin.Server/StartupOptions.cs#L68). But there is no network.xml setting for this yet?

**Comment by gnattu** [comment]
We usually don't put such super advanced config into xml, and those hidden options have no documentation because we don't expect most users to ever alter them.

**Comment by Shadowghost** [comment]
Just as an FYI: what you have in your config XML is wrong.
The proxy stanza should include the upstream proxy IPs and the override should be `subnet=override`, e.g. `127.0.01/8=https://domain.tld`

If you have local subnets and proxy properly configured you can also use external, internal and all instead of a subnet.

**Comment by selfhoster1312** [comment]
Thanks for your time! I'm gonna close the issue because the workaround is "documented" here.

However, i can't voice enough that documenting settings (or lack thereof) is very important. I just spent a lot of time looking through code because some settings have been deprecated/renamed and this was not in the release notes on the blog. I also could not find a migration guide, CHANGELOG or anything of the sort (maybe i missed it?)

> we don't expect most users to ever alter them

It's not just admins who can be confused. It's also maintainers trying to integrate Jellyfin into a selfhosted ecosystem like [Yunohost](https://yunohost.org/) who need to come up with config templates.

> Just as an FYI: what you have in your config XML is wrong

Thanks for the example. Just for clarification what is KnownProxies used for if not for discovery?

**Comment by Shadowghost** [comment]
If you don't set Know proxies, Jellyfin uses the IP of the proxy and not the one from the proxy header to decide if it's an internal/external request. This has an impact on e.g. remote access checks, bandwidth enforcement and similar

**Comment by Salamandar** [comment]
> We usually don't put such super advanced config into xml, and those hidden options have no documentation because we don't expect most users to ever alter them.

Hi there. What's the recommended way to set options present in network.xml ?
We're packaging Jellyfin for YunoHost and are using network.xml mostly for `BaseUrl`, `InternalHttpPort`, `LocalNetworkAddresses` and to enable UPnP, remote access and autodiscovery.
