### ISSUE TITLE
[Issue]:  Unable to access settings

### ISSUE THREAD

**Issue by gogo199432** [jellyfin/jellyfin#11568]
### Please describe your bug

weird bug I'm having with 10.9 . Almost all my settings pages are invisible / it looks like they are slid up over the top of the screen. I can just barely make out some UI elements.

The following pages load for some reason: Notifications, Extensions/Catalogue, Extensions/Repos, Library/(bottom 3 options), Playback/(bottom 3 options)

![kép](https://github.com/jellyfin/jellyfin/assets/9107561/e452d53f-a43f-4ef9-8da2-2bda28d11eff)

### Reproduction Steps

Just simply "apt upgrade"-d my bookworm Debian box

### Jellyfin Version

10.9.0

### Environment

```markdown
- OS: Debian 12 (bookworm)
- Linux Kernel: 6.x
- Virtualization: Proxmox VM
- Clients: Browser (Firefox and Chrome)
- Browser: Firefox 125.0.3 and Chrome
```

### Jellyfin logs

```shell
Could not access logs page. Systemctl didn't print anything at all.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
Try clearing browser cache.
Logs can be also be found directly on disk.

**Comment by gogo199432** [comment]
I have tried cleaning cache. Also as described I tried 2 separate browsers, same behaviour

**Comment by thornbill** [comment]
Any errors present in the browser console?

**Comment by gogo199432** [comment]
There are no actual errors in either journalctl or in the browser console. Last log is for logging in on the server side.

**Comment by mrboobek** [comment]
Same here, after upgrading to latest docker cointainer from linuxserver.io I can't enter settings (blank screen).

**Comment by gogo199432** [comment]
Apologies, apparenly I'm an idiot and I did have custom css too. I don't even remember importing it, must have been a couple of years ago. After deleting it from branding.xml, the settings load fine. I'll be closing this ticket :)

**Comment by keesfluitman** [comment]
> Apologies, apparenly I'm an idiot and I did have custom css too. I don't even remember importing it, must have been a couple of years ago. After deleting it from branding.xml, the settings load fine. I'll be closing this ticket :)

Didnt work for me. i had a theme activated as well. Tried to delete the theme plugin manually, but no look to see the content yet to do anything. I guess i should go back to a backup, remove the theme and do it then. Or find if i can use CLI to deactivate the plugin or theme.
