### ISSUE TITLE
Collections no longer have media in them 10.9.0

### ISSUE THREAD

**Issue by acidmanifesto** [jellyfin/jellyfin#11581]
### Please describe your bug

I updated to 10.9 and My media is still present and searchable and viewable, even newly added videos.
Howevee when browsing thru my collection, all collections still show, but they all have nothing in them.
![171555593221598057931260147181](https://github.com/jellyfin/jellyfin/assets/16887899/a65fb656-35d0-4e46-8795-7badadbecaa9)
I apologize for the phone picture. Network is currently out in my area.

### Reproduction Steps

Click on the collection category
Click on any collection item
Observe the collection item is empty.

### Jellyfin Version

10.9.0

### Environment

```markdown
- OS:servee 2022
- Linux Kernel:
- Virtualization:
- Clients: web, android, android tv
- Browser: chrome, firefox
- FFmpeg Version: current with 10.9 release
- Playback Method: n/a
- Hardware Acceleration: n/a
- GPU Model: p400
- Plugins: default
- Reverse Proxy: n/a
- Base URL: n/a
- Networking:local
- Storage: 2 nas
```

### Jellyfin logs

```shell
Unable to no network at the moment.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by acidmanifesto** [comment]
This is apparrently a dupe issue of something already reported. I will close this.
https://github.com/jellyfin/jellyfin/issues/11572

**Comment by gnattu** [comment]
10.9.1 Windows installer is up. You can test with that version with your 10.8 backup. It should work as intended now.

If you don't have your 10.8 database backup, then I'm not sure if those collections items will ever come back though.

**Comment by acidmanifesto** [comment]
> 10.9.1 Windows installer is up. You can test with that version with your 10.8 backup. It should work as intended now.
> 
> If you don't have your 10.8 database backup, then I'm not sure if those collections items will ever come back though.

I didnt have a back up. I upgraded and all collections are visible again now. So issue is resolved fully from my end.
