### ISSUE TITLE
[Issue]: Fedora release of 10.9.x missing from Fusion repositories

### ISSUE THREAD

**Issue by mikeybob** [jellyfin/jellyfin#11586]
### Please describe your bug

Fedora (RPM) release of 10.9.x missing from Fusion repositories.
No info stating when or if this release will be available.

### Reproduction Steps

dnf install jellyfin

the 10.8.13 version is the current version.

### Jellyfin Version

10.8.13

### Environment

```markdown
- OS: Fedora 40
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
n/a
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mikeybob** [comment]
Make it available and I’ll run it…

**Comment by nielsvanvelzen** [comment]
The Fedora packages are community maintained.

**Comment by mikeybob** [comment]
A big deal about having the fusion repos in the blog posts. I guess I misunderstood their meaning.

**Comment by mikeybob** [comment]
wow. not planned. I really misunderstood.

**Comment by joshuaboniface** [comment]
The meaning is that, we have offloaded support for RPMs to RPMFusion. We do not control the RPMFusion repositories, which is sort of the point. As such, the timing of the release of new stable versions in RPMFusion is entirely out of our hands. They will come when the RPMFusion maintainer(s) build them.

**Comment by joshuaboniface** [comment]
It looks like an update was submitted about 8 hours ago: https://pkgs.rpmfusion.org/cgit/free/jellyfin.git/commit/?id=506e0fb415704ad7db0725519bff7999b598c2a2 However, I do not yet see a build attempted, so I assume that must be triggered by the RPMFusion package owner which should hopefully occur relatively soon.

**Comment by lxwulf** [comment]
I still do not get why the packages are not yet released in the repository of `rpmfusion`. 
I do see the [builds](https://koji.rpmfusion.org/koji/packageinfo?packageID=648), which seem to be fine, but when I search on my distro for `Jellyfin`, it's still on the old `10.8.13` version.

If I can help somehow or if you can push me in the right direction, I would really appreciate this.

**For reference, here is my terminal output:**

```bash
[officerk@pro-00000001-jfms ~]$ dnf info jellyfin-*
Fedora 40 - x86_64                                                                                                                          6.3 MB/s |  20 MB     00:03    
Fedora 40 openh264 (From Cisco) - x86_64                                                                                                    1.3 kB/s | 1.4 kB     00:01    
Fedora 40 - x86_64 - Updates                                                                                                                3.6 MB/s | 6.8 MB     00:01    
RPM Fusion for Fedora 40 - Free                                                                                                             147 kB/s | 164 kB     00:01    
RPM Fusion for Fedora 40 - Free - Updates                                                                                                    45 kB/s |  33 kB     00:00    
RPM Fusion for Fedora 40 - Nonfree                                                                                                           44 kB/s |  69 kB     00:01    
RPM Fusion for Fedora 40 - Nonfree - Updates                                                                                                 19 kB/s |  17 kB     00:00    
Installed Packages
Name         : jellyfin-firewalld
Version      : 10.8.13
Release      : 1.fc40
Architecture : noarch
Size         : 18 k
Source       : jellyfin-10.8.13-1.fc40.src.rpm
Repository   : @System
From repo    : rpmfusion-free
Summary      : FirewallD metadata files for Jellyfin
URL          : https://jellyfin.org
License      : GPL-2.0-only
Description  : This package contains FirewallD files for Jellyfin.

Name         : jellyfin-server
Version      : 10.8.13
Release      : 1.fc40
Architecture : x86_64
Size         : 35 M
Source       : jellyfin-10.8.13-1.fc40.src.rpm
Repository   : @System
From repo    : rpmfusion-free
Summary      : The Free Software Media System Server backend
URL          : https://jellyfin.org
License      : GPL-2.0-only
Description  : The Jellyfin media server backend.

Name         : jellyfin-web
Version      : 10.8.13
Release      : 1.fc40
Architecture : noarch
Size         : 56 M
Source       : jellyfin-10.8.13-1.fc40.src.rpm
Repository   : @System
From repo    : rpmfusion-free
Summary      : The Free Software Media System Server frontend
URL          : https://jellyfin.org
License      : GPL-2.0-only
Description  : The Jellyfin media server web frontend.
```

**Comment by knowsshit** [comment]
I also seem to be stuck on 10.8.13 on Fedora 40. dnf search, info, update and upgrade just shows version 10.8.13 and not 10.9.4 as expected. Not sure if I need to do anything more on my part for it to work?

**Comment by maromcik** [comment]
I have the same problem. Is there anything that could be done about this? It seems like a minor issue. I'd love to install the newest update since my Flatpak Jellyfin Client refuses to work with my 10.8.13 server. Thank you

**Comment by joshuaboniface** [comment]
There is no input on this from our side. Again, this is now entirely managed by the folks over at RPMFusion. If their maintainers are not keeping it up-to-date, that's unfortunate and means that someone from this community needs to take on maintenance. https://pkgs.rpmfusion.org/cgit/free/jellyfin.git/

**Comment by maromcik** [comment]
Could you please inform them of the issue, considering that it is appropriate? Maybe they are not aware of it?

**Comment by lxwulf** [comment]
> There is no input on this from our side. Again, this is now entirely managed by the folks over at RPMFusion. IT does look like new commits were made very recently, but they'll have to trigger builds. https://pkgs.rpmfusion.org/cgit/free/jellyfin.git/

That's may be okay on one side for you, but I think it's a different story that the offloading of the `RPM package` to `RPMfusion` has the consequences that we need to wait more than a month to receive the update. In this time, you released several updates for both the server and the client.

Understand me correctly, my problem is not that you guys offloaded the work of compiling the `RPM` to `RPMfusion` but the long, not in time and inconsistent delivering of the updated packages.

> **Mostly one month later:**
> Still no update.
>
> Initial post: 13 May
> Today of this post: 8. June
>
> I mean dont wanna be picky but there are people out there which can not watch anymore on their media server because the client is updated and the server _can't_  be updated....

**Comment by opeeba** [comment]
I found it in the testing repo which can be enabled with this command:
#dnf config-manager --set-enabled rpmfusion-free-updates-testing

And installed with: 
dnf --enablerepo=rpmfusion-free-updates-testing install jellyfin

```
# dnf --enablerepo=rpmfusion-free-updates
-testing install jellyfin
Last metadata expiration check: 0:02:13 ago on Sat 08 Jun 20
24 12:22:27 PM PDT.
Dependencies resolved.
============================================================
 Package                Arch   Version       Repo      Size
============================================================
Installing:
 jellyfin               x86_64 10.9.4-1.fc40 rpmfusion-free-
updates-testing
                                                      9.7 k
Upgrading:
 jellyfin-server        x86_64 10.9.4-1.fc40 rpmfusion-free-
updates-testing
                                                       16 M
 jellyfin-web           noarch 10.9.4-1.fc40 rpmfusion-free-
updates-testing
                                                       31 M
Installing dependencies:
 aspnetcore-runtime-8.0 x86_64 8.0.4-1.fc40  updates  8.0 M
 dotnet-hostfxr-8.0     x86_64 8.0.4-1.fc40  updates  142 k
 dotnet-runtime-8.0     x86_64 8.0.4-1.fc40  updates   23 M

Transaction Summary
============================================================
Install  4 Packages
Upgrade  2 Packages

Total download size: 79 M
Is this ok [y/N]:
```

**Comment by maromcik** [comment]
Great, I installed it from the testing repo, however I had to uninstall dotnet-sdk-8.0, because it conflicts. 

```
RPM Fusion for Fedora 40 - Free - Test Updates                                                                                                    107 kB/s | 7.6 kB     00:00    
Dependencies resolved.
==================================================================================================================================================================================
 Package                                  Architecture                    Version                                   Repository                                               Size
==================================================================================================================================================================================
Upgrading:
 jellyfin                                 x86_64                          10.9.4-1.fc40                             rpmfusion-free-updates-testing                          9.7 k
 jellyfin-server                          x86_64                          10.9.4-1.fc40                             rpmfusion-free-updates-testing                           16 M
 jellyfin-web                             noarch                          10.9.4-1.fc40                             rpmfusion-free-updates-testing                           31 M

Transaction Summary
==================================================================================================================================================================================
Upgrade  3 Packages

Total download size: 47 M
Is this ok [y/N]: y
Downloading Packages:
(1/3): jellyfin-10.9.4-1.fc40.x86_64.rpm                                                                                                          125 kB/s | 9.7 kB     00:00    
(2/3): jellyfin-server-10.9.4-1.fc40.x86_64.rpm                                                                                                    25 MB/s |  16 MB     00:00    
(3/3): jellyfin-web-10.9.4-1.fc40.noarch.rpm                                                                                                       21 MB/s |  31 MB     00:01    
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                              26 MB/s |  47 MB     00:01     
Running transaction check
Transaction check succeeded.
Running transaction test
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Transaction test error:
  file /usr/lib/.build-id/07/bc41b8b8711e3b9965688d9f43c736739f0da1 from install of jellyfin-server-10.9.4-1.fc40.x86_64 conflicts with file from package dotnet-sdk-8.0-8.0.104-1.fc40.x86_64
```

**Comment by lxwulf** [comment]
It's now in the `rpmfusion` repos (updates).

**Comment by mikeybob** [comment]
I had given up and installed it by downloading the rpm files and applying 10.9.4 manually on June 3, and 10.9.6 on the 9th. I do hope I haven't made a mess of future upgrades by doing that.
