### ISSUE TITLE
[Issue]: Plugins showing twice in plugins dashboard after upgrading to 10.9.1

### ISSUE THREAD

**Issue by navilg** [jellyfin/jellyfin#11604]
### Please describe your bug

After upgrading jellyfin from 10.8 to 10.9, I see many plugins are showing twice in plugins section with different status.

Restart, Superceded, Active, NotSupported

Is there a guide how to handle this, if it was expected.

### Reproduction Steps

1. Install jellyfin 10.8
2. Install Jellyscrub and Trakt plugins
3. Upgrade Jellyfin to 10.9
4. Check plugins list

### Jellyfin Version

10.9.0

### if other:

10.9.1

### Environment

```markdown
- OS: Ubuntu 22.04
- Linux Kernel: 6.5.0
- Virtualization:
- Clients:
- Browser: Firefox
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins: Jellyscrub, Opensubtitles, Playback Reporting, Reports, TMDb Trailers, TVMaze, Trakt, Webhook
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
NA
```

### Please attach any screenshots here

![Screenshot from 2024-05-13 20-46-55](https://github.com/jellyfin/jellyfin/assets/37469234/656e3cc9-dc87-4f6d-823a-c0e250d3c47b)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
Have you tried restarting Jellyfin? 
Half of the tiles say `Status Restart`, meaning that it is waiting for Jellyfin to restart.

**Comment by navilg** [comment]
Yeah it worked after restart
