### ISSUE TITLE
Remember subtitle and audio track choice between episodes

### ISSUE THREAD

**Issue by oddstr13** [jellyfin/jellyfin#1160]
**Is your feature request related to a problem? Please describe.**
Currently (Jellyfin 10.2.2) I have to chose audio and subtitle track for every episode when my preference (japanese audio with english subs) is not the file (or server?) defaults (english dub with english signs).

**Describe the solution you'd like**
It would be nice if Jellyfin could be smart enough to remember the choice between episodes of the same series, at least as long as the available choices of the current episode matches the previous.

**Describe alternatives you've considered**
Preferably I would like a prioritized list of audio+subtitle language, taking original audio language into account.
I am however not sure of how hard/easy it would be to get the required metadata.

As an example, I would prefer something like this myself;

Audio | Subtitle
-|-
original=eng | none
original=nor | none
original | eng
original | nor
eng | signs=eng
eng | none
nor | signs=nor
nor | signs=eng
nor | none
any | eng
any | nor
any | none

**Comment by joshuaboniface** [comment]
I've noticed this bug too, but in the form of them always turning back *on* when I turn them off.

**Comment by oddstr13** [comment]
I wouldn't say it is a bug - more a lack of features. Current behaviour is how most stand-alone media players would handle it too.

**Comment by thornbill** [comment]
Also had a request for this on [Reddit](https://old.reddit.com/r/jellyfin/comments/b4px6s/androidtv_autoload_subtitle_and_cant_read_at_end/).

**Comment by iwalton3** [comment]
I figured I'd post this here too. The [Jellyfin MPV Shim](https://github.com/iwalton3/jellyfin-mpv-shim) application has a feature where you can configure the subtitles for an entire season of TV at once.
