### ISSUE TITLE
win 10 jellyfin server add library error by smba 

### ISSUE THREAD

**Issue by wheeliar** [jellyfin/jellyfin#1161]
I just wanted to add a library from a network disk which was attached in my router，and I share the files with smba，but I can't add it.
when I try，it reminds me 
>The path could not be found. Please ensure the path is valid and try again.
![image_10](https://user-images.githubusercontent.com/30236449/55049314-9f4d6500-5086-11e9-804f-cc2e2d5f30e2.png)
And I tried emby win server，it was ok.
![image_11](https://user-images.githubusercontent.com/30236449/55049360-c7d55f00-5086-11e9-9f1c-423c2972053d.png)
So what should I do？

**Comment by LogicalPhallacy** [comment]
Can you try again then post what was written to the Jellyfin log? Failing that, can you try mounting your smb share as a network drive with a drive letter and see if you can navigate it then? The second step should be unnecessary but it would help rule out any perms issues between the two.

**Comment by wheeliar** [comment]
YES，I did it. I mount smb share as a network drive, it works well. Thank
you.
LogicalPhallacy <notifications@github.com> 于2019年3月27日周三 下午1:32写道：

**Comment by onepage1230** [comment]
Hi, I had the same problem. I mount smb share as a network drive, but Jellyfin can't find it in the drive list.
Windown 10, Jellyfin Ver 10.5.5
![2020-07-08 000616](https://user-images.githubusercontent.com/8319032/86810028-16a5dd00-c0af-11ea-8fb1-cec6c7d16c08.png)
![2020-07-08 000617](https://user-images.githubusercontent.com/8319032/86810047-1b6a9100-c0af-11ea-99e3-33a9d61ffe92.png)
