### ISSUE TITLE
[Issue]: can't change metadata by search identify if exist NFO files

### ISSUE THREAD

**Issue by cxfksword** [jellyfin/jellyfin#11619]
### Please describe your bug

My movie library is configured to save metadata to NFO. After upgrading to version 10.9, I am unable to fix incorrect movie metadata. The `Identify` by search feature is not work, when I click `save`, there are no changes made and the movie retains its old incorrect metadata.

Maybe impacted by PR: https://github.com/jellyfin/jellyfin/issues/10088

### Reproduction Steps

1. Library configured to save metadata to NFO
2. Add new movie and wait Jellyfin scan metadata finish
3. Open movie detail page and select `Identity`
4. Input another movie name and click `Search`
5. Select one search result and click `Save`
6. Movie metadata keep old...

### Jellyfin Version

10.9.0

### Environment

```markdown
- OS: Ubuntu 22.04.4 LTS
- Linux Kernel:
- Virtualization: Docker
- Clients: Browser
- Browser: Edge 115
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model: none
- Plugins: TheMovieDb
- Reverse Proxy: none
- Base URL: none
- Networking: Bridge
- Storage: local
```

### Jellyfin logs

```shell
Jellyfin.Api.Controllers.ItemLookupController: Setting provider id's to item fe37f08f-e296-c000-b2e3-f118d56e8f61-Godzilla Minus One: {"Tmdb": "1213925"}stdout: [12:05:20] [INF] [33] Jellyfin.Api.Controllers.ItemLookupController: Setting provider id's to item fe37f08f-e296-c000-b2e3-f118d56e8f61-Godzilla Minus One: {"Tmdb": "1213925"}
stdout: [12:05:20] [INF] [33] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/data/downloads/jellyfin/movie/Godzilla Minus One (2023)/1.mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
stdout: [12:05:20] [WRN] [34] MediaBrowser.XbmcMetadata.Providers.MovieNfoProvider: Trailer URL uses a deprecated format : plugin://plugin.video.youtube/?action=play_video&videoid=VvSrHIX5a-0. Using plugin://plugin.video.youtube/play/?video_id=VvSrHIX5a-0 instead is advised.
stdout: [12:05:20] [WRN] [34] MediaBrowser.XbmcMetadata.Providers.MovieNfoProvider: Trailer URL uses a deprecated format : plugin://plugin.video.youtube/?action=play_video&videoid=r7DqccP1Q_4. Using plugin://plugin.video.youtube/play/?video_id=r7DqccP1Q_4 instead is advised.
stdout: [12:05:20] [WRN] [34] MediaBrowser.XbmcMetadata.Providers.MovieNfoProvider: Trailer URL uses a deprecated format : plugin://plugin.video.youtube/?action=play_video&videoid=YlceGpbGgvE. Using plugin://plugin.video.youtube/play/?video_id=YlceGpbGgvE instead is advised.
stdout: [12:05:31] [INF] [34] Emby.Server.Implementations.IO.LibraryMonitor: Godzilla Minus One (/data/downloads/jellyfin/movie/Godzilla Minus One (2023)/1.mp4) will be refreshed.
stdout: [12:05:31] [INF] [34] Emby.Server.Implementations.IO.LibraryMonitor: movie (/data/downloads/jellyfin/movie) will be refreshed.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gnattu** [comment]
This is more or less working as intended because we believe Jellyfin should never overwrite anything in the media folder because that can be provided by users as well.

**Comment by cxfksword** [comment]
> This is more or less working as intended because we believe Jellyfin should never overwrite anything in the media folder because that can be provided by users as well.

When the library's NFO saving feature is enabled, could an option be added to allow users to override NFO? Currently, when NFO files are present, the Identity becomes completely unavailable, movie always keep incorrect metadata.

**Comment by cxfksword** [comment]
I think the user has enabled the library's NFO saving feature, typically with an intention to override it. If they prefer not to overwrite their own NFO, they can choose not to enabling NFO saving.

**Comment by gnattu** [comment]
> I think the user has enabled the library's NFO saving feature, typically with an intention to override it. If they prefer not to overwrite their own NFO, they can choose not to enabling NFO saving.

Well you cannot assume that. A lot of our users use both the generated and manually edited ones. The user can edit the nfo files manually at any time and it is not a safe assumption to let Jellyfin to overwrite it.

**Comment by macmini888** [comment]
I'm also experiencing this problem. I have the NFO Saver function enabled to allow for quick repopulation of my media if I ever need to do a fresh install. Many of these titles are rare or unusual and required re-identification in Jellyfin when originally imported. As the administrator, I should have the choice to allow Jellyfin to correct a mis-identified title and associated NFO, especially if JF generated it.

Currently, my workaround is to import the file, let it populate on the server, then delete the NFO if improperly identified and use the Identify function to correct the title. That's fine, but the way that this function worked in past versions felt more intuitive to me.

**Comment by Thalhammer** [comment]
I just hit the same issue and only found this issue by accident.
I am pretty sure it used to work "correctly" before.
The way I see it there are multiple options to solve this:
- Put a tag in the generated nfo and only overwrite if the nfo was generated by jellyfin (preferred)
- Provide a simple toggle to allow overwriting all
- Disable the identify feature if an nfo is present (does not fix the bug, but at least makes the reason obvious)

But the way its currently implemented is definitly a bug, because it is not obvious to the use why the request is just ignored. As for me I'll just disable the nfo save for now and rename all nfo files, because I only keep them as a fallback in case jellyfin breaks its db anyway.

**Comment by Shadowghost** [comment]
AFAIK the Kodi NFO spec already includes a way to denote the "writer", maybe we can utilize that.

**Comment by cxfksword** [comment]
> > I think the user has enabled the library's NFO saving feature, typically with an intention to override it. If they prefer not to overwrite their own NFO, they can choose not to enabling NFO saving.
> 
> Well you cannot assume that. A lot of our users use both the generated and manually edited ones. The user can edit the nfo files manually at any time and it is not a safe assumption to let Jellyfin to overwrite it.

@gnattu NFO `<lockdata>` field also can achieve this, but the PR requests that Jellyfin modify and add the missing fields to NFO file.  Provide a toggle to `Identity` webui maybe a good option to solve this.
![SCR-20240517-jizs](https://github.com/jellyfin/jellyfin/assets/718792/fe479bef-304f-4c06-8f62-47bc375f6d00)

**Comment by rightsaidfred99** [comment]
Glad I came across this, a very obscure bug. I don't believe it's a feature here because if the metadata providor provies the wrong result, you have to go in to the server manually, delete the NFO or manually edit it. Compared to past versions where you'd just use the Jellyfin UI to choose the write source

**Comment by michaelkrieger** [comment]
> I can no longer user `Refresh metadata` to `Search for missing metadata` nor `Replace all metadata` I am forced to go into the directory and delete each of the relevant nfo files before new data can be populated.

similar here. a show may download before metadata like outline is populated.  In past versions, using replace all metadata (or identify), and checking to replace all, it did just that. Now it adds none of the empty data now and I’m still left without a description, dates, people.

removing *.NFO from the tv series folder and then replacing metadata works, but this is totally not the right behaviour.

I’m explicitly saying to replace the metadata it has. Right now there appears to be no way to do that other than to hand edit the NFO file.

noting, this is also a change in behaviour and doesn’t make sense. if you want this behavior, maybe something in the drop-down that says “refresh meta-data from NFO file”.

**Comment by Shadowghost** [comment]
Might be fixed by #11743 
If anyone is able to test it, please do so.

**Comment by cxfksword** [comment]
> Might be fixed by #11743 If anyone is able to test it, please do so.

@Shadowghost I have tested the new release v10.9.4, and the issue still persists.

**Comment by macmini888** [comment]
The issue still persists for me as well in 10.9.4. Thanks.

**Comment by Shadowghost** [comment]
Linked PR will fix it in .5

**Comment by macmini888** [comment]
It seems like this is working as expected now in 10.9.5, but I had to delete my plugin folder first after the upgrade.

**Comment by rightsaidfred99** [comment]
I'm not seeing it fixed. I deleted the plugins folder but it's still the broken behaviour. Ony the image gets updated if a NFO file exists on 10.9.5.

**Comment by macmini888** [comment]
I played with it some more this afternoon. Anything that was added after the 10.9.5 upgrade was working as expected. Anything with an NFO written under 10.9.4 took some massaging (replacing metadata and scanning for new or updated metadata) but I was eventually able to get it to do what I asked via Identify. It wasn’t smooth. I’m out right now but will test more in the morning and see if I can determine the steps I took.

**Comment by cxfksword** [comment]
I have tested the new release v10.9.6, and it is working as expected now. 👍

**Comment by rightsaidfred99** [comment]
I tested again, it works. But if background image exists Jellyfin will overwrite and it becomes a blank image. Something it never did before, it'd replace the background image

**Comment by macmini888** [comment]
My Jellyfin 10.9.6 is still behaving as it was before. To replace metadata via Identify, I have to Identify the title and then Replace All Metadata after. I am ok with this, but just thought I'd mention this since it is different from behavior prior to 10.9.0.

**Comment by Shadowghost** [comment]
Did you force-reload the page after identifying?

**Comment by macmini888** [comment]
Force reload doesn't do anything. The Identify + Replace All Metadata sequence changes it to the title I have selected.

**Comment by Shadowghost** [comment]
Does #12025 fix it?

**Comment by macmini888** [comment]
I am not sure what #12025 does... how would I test?

**Comment by tunemanbbs** [comment]
I can confirm this as a bug after upgrading to 10.9.6 this seems to now roll back when ever the metadata refresh is ran.

**Comment by Shadowghost** [comment]
Original reporter reported this fixed, so if you still have bad behaviour, please create a new ticket with new log files and description.

**Comment by d03j** [comment]
> Jellyfin.Api.Controllers.ItemLookupController: Setting provider id's to item fe37f08f-e296-c000-b2e3-f118d56e8f61-Godzilla Minus One: {"Tmdb": "1213925"}stdout: [12:05:20] [INF] [33] Jellyfin.Api.Controllers.ItemLookupController: Setting provider id's to item fe37f08f-e296-c000-b2e3-f118d56e8f61-Godzilla Minus One: {"Tmdb": "1213925"}
> stdout: [12:05:20] [INF] [33] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/data/downloads/jellyfin/movie/Godzilla Minus One (2023)/1.mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
> stdout: [12:05:20] [WRN] [34] MediaBrowser.XbmcMetadata.Providers.MovieNfoProvider: Trailer URL uses a deprecated format : plugin://plugin.video.youtube/?action=play_video&videoid=VvSrHIX5a-0. Using plugin://plugin.video.youtube/play/?video_id=VvSrHIX5a-0 instead is advised.
> stdout: [12:05:20] [WRN] [34] MediaBrowser.XbmcMetadata.Providers.MovieNfoProvider: Trailer URL uses a deprecated format : plugin://plugin.video.youtube/?action=play_video&videoid=r7DqccP1Q_4. Using plugin://plugin.video.youtube/play/?video_id=r7DqccP1Q_4 instead is advised.
> stdout: [12:05:20] [WRN] [34] MediaBrowser.XbmcMetadata.Providers.MovieNfoProvider: Trailer URL uses a deprecated format : plugin://plugin.video.youtube/?action=play_video&videoid=YlceGpbGgvE. Using plugin://plugin.video.youtube/play/?video_id=YlceGpbGgvE instead is advised.
> stdout: [12:05:31] [INF] [34] Emby.Server.Implementations.IO.LibraryMonitor: Godzilla Minus One (/data/downloads/jellyfin/movie/Godzilla Minus One (2023)/1.mp4) will be refreshed.
> stdout: [12:05:31] [INF] [34] Emby.Server.Implementations.IO.LibraryMonitor: movie (/data/downloads/jellyfin/movie

FWIW, I bulk fixed my nfo with `$ for f in path_to_media_library/*nfo; do sed -n 's/?action=play_video&amp;/play\/?/' $f;done`
