### ISSUE TITLE
[Issue]: attempted lyrics extraction every library scan

### ISSUE THREAD

**Issue by sjorge** [jellyfin/jellyfin#11622]
### Please describe your bug

Every library scan I noticed a whole bunch of ffprobe's for the same set of mp3's, I enabled debug logging to see if it told me more. (See log block below)

These seem to be generated here:
https://github.com/jellyfin/jellyfin/blob/69d4886697f3f5990069b6d7a8ca56d5a2ec111b/MediaBrowser.Providers/MediaInfo/ProbeProvider.cs#L162-L171

But as someone who does not know .net this seems fine. I did some more digging and found the extracted `.lrc` files in `/var/lib/metadata/library/...` Most of these have multiple lines of text (makes sense) but all the ones that keep showing up repeatedly have a single line.

For the file from the log entry I added below.
```
sjorge@node:~# sudo cat /var/lib/jellyfin/metadata/library/b2/b23c5c0d9e3b2ec2b8b632b81353f8c7/09\ Cap\ Diamant.lrc
FreeScooByDoo
```
(Seems the lyrics in those files is useless junk, but  that still should not trigger the ffprobe every scan)

The `.lrc` files that have multiple lines don't have the songs they belong to trigger a ffprobe every scan. 

### Reproduction Steps

1. scan all libraries | scan the music library
2. watch a bunch of ffprobe's be fired for the same set of songs

### Jellyfin Version

10.9.0

### if other:

10.9.1

### Environment

```markdown
- OS: Ubuntu 22.04.4 LTS
- Linux Kernel: GNU/Linux 6.5.0-26-generic x86_64 (for ARC support)
- Virtualization: BHYVE
- Clients: Browser
- Browser: Firefox 126.0b8 (64-bit)
- FFmpeg Version: jellyfin-ffmpeg6 - 6.0.1-6-jammy
- Playback Method: Transcode (Ends up playing without subs transcoded to AV1)
- Hardware Acceleration: QSV (also tried without, no difference)
- GPU Model: Intel Arc A310 Low Profile 4GB (ASRock)
- Plugins: AniDB, AniList, AudioDB, Cover Art Archive, Fanart, MusicBrainz, OMDb, Session Cleaner, Studio Images, TMDb, TMDb Box Sets, Trakt, Webhook
- Reverse Proxy: apache
- Base URL: /jellyfin
- Networking: vnic
- Storage: local (config) + NFS (media)
```

### Jellyfin logs

```shell
May 14 07:02:33 fqdn jellyfin[79939]: [07:02:33] [DBG] Refreshing /mm/music/Cœur de pirate/Blonde/09 Cap Diamant.mp3 due to external lyrics change.
May 14 07:02:33 fqdn jellyfin[79939]: [07:02:33] [DBG] ProbeProvider reports change to /mm/music/Cœur de pirate/Blonde/09 Cap Diamant.mp3
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gnattu** [comment]
TabLib issue. It has known compatibility problem with certain file containers that prevents it to extract the lyrics.

**Comment by sjorge** [comment]
```
root@node:~# /usr/lib/jellyfin-ffmpeg/ffprobe -analyzeduration 200M -probesize 1G -i file:"/mm/music/Cœur de pirate/Blonde/09 Cap Diamant.mp3" -threads 0 -v warning -print_format json -show_streams -show_format
{
    "streams": [
        {
            "index": 0,
            "codec_name": "mp3",
            "codec_long_name": "MP3 (MPEG audio layer 3)",
            "codec_type": "audio",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "sample_fmt": "fltp",
            "sample_rate": "44100",
            "channels": 2,
            "channel_layout": "stereo",
            "bits_per_sample": 0,
            "initial_padding": 0,
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "time_base": "1/14112000",
            "start_pts": 353600,
            "start_time": "0.025057",
            "duration_ts": 2305105920,
            "duration": "163.343673",
            "bit_rate": "320000",
            "disposition": {
                "default": 0,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0,
                "captions": 0,
                "descriptions": 0,
                "metadata": 0,
                "dependent": 0,
                "still_image": 0
            },
            "tags": {
                "encoder": "LAME3.99 "
            },
            "side_data_list": [
                {
                    "side_data_type": "Replay Gain"
                }
            ]
        },
        {
            "index": 1,
            "codec_name": "png",
            "codec_long_name": "PNG (Portable Network Graphics) image",
            "codec_type": "video",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "width": 500,
            "height": 453,
            "coded_width": 500,
            "coded_height": 453,
            "closed_captions": 0,
            "film_grain": 0,
            "has_b_frames": 0,
            "sample_aspect_ratio": "1:1",
            "display_aspect_ratio": "500:453",
            "pix_fmt": "rgb24",
            "level": -99,
            "color_range": "pc",
            "refs": 1,
            "r_frame_rate": "90000/1",
            "avg_frame_rate": "0/0",
            "time_base": "1/90000",
            "start_pts": 2255,
            "start_time": "0.025056",
            "duration_ts": 14700931,
            "duration": "163.343678",
            "disposition": {
                "default": 0,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 1,
                "timed_thumbnails": 0,
                "captions": 0,
                "descriptions": 0,
                "metadata": 0,
                "dependent": 0,
                "still_image": 0
            },
            "tags": {
                "comment": "Cover (front)"
            }
        }
    ],
    "format": {
        "filename": "file:/mm/music/Cœur de pirate/Blonde/09 Cap Diamant.mp3",
        "nb_streams": 2,
        "nb_programs": 0,
        "format_name": "mp3",
        "format_long_name": "MP2/3 (MPEG audio layer 2/3)",
        "start_time": "0.025056",
        "duration": "163.343673",
        "size": "6944915",
        "bit_rate": "340137",
        "probe_score": 51,
        "tags": {
            "title": "Cap Diamant",
            "artist": "Cœur de pirate",
            "track": "9/13",
            "album": "Blonde",
            "disc": "1/1",
            "date": "2011-11-07",
            "genre": "Alternative Pop Singer-Songwriter",
            "TDOR": "2011-01-01",
            "SCRIPT": "Latn",
            "TSRC": "CAD431192209",
            "copyright": "FreeScooByDoo",
            "encoded_by": "FreeScooByDoo",
            "TMED": "Digital Media",
            "publisher": "Grosse Boîte",
            "TSOC": "Cœur de pirat",
            "composer": "Cœur de pirate",
            "TEXT": "Cœur de pirate",
            "album_artist": "Cœur de pirate",
            "TSO2": "Cœur de pirate",
            "artist-sort": "Cœur de pirate",
            "ASIN": "B00C27JWR6",
            "comment": "FreeScooByDoo",
            "originalyear": "2011",
            "lyrics-XXX": "FreeScooByDoo\r\n",
            "BARCODE": "673793403329",
            "CATALOGNUMBER": "LPM 33-2",
            "ARTISTS": "Cœur de pirate",
            "MusicBrainz Album Type": "album",
            "replaygain_track_gain": "-4.00 dB",
            "replaygain_track_peak": "0.982330",
            "MusicBrainz Album Status": "official",
            "MusicBrainz Album Release Country": "FR",
            "MusicBrainz Album Id": "cc105cc6-6315-447f-b68e-571dba38b7a7",
            "MusicBrainz Artist Id": "130e7bd0-6d34-48a9-822f-03eff7ea95d4",
            "MusicBrainz Album Artist Id": "130e7bd0-6d34-48a9-822f-03eff7ea95d4",
            "MusicBrainz Release Group Id": "62e3d019-c30f-44d9-9a06-19b60d2cc6b0",
            "MusicBrainz Release Track Id": "356cc569-d42b-3519-8aef-e35c9a6a6223",
            "encoder": "Lavf61.1.100"
        }
    }
}
```

**Comment by sjorge** [comment]
> TabLib issue. It has known compatibility problem with certain file containers that prevents it to extract the lyrics.

I see, is there a way to just prevent lyrics extraction? I don't really care for it personally. Nuking the .lrc files in /var/lib/jellyfin/metadata/libraries seems to 'fix' it. But the webui still shows the lyrics option for those songs.

ffprobe does seem to find the same data than what is in the extracted .lrc files though. (Unless those are unix style newlines vs the windows style \r\n ffprobe finds 🤔

**Comment by gnattu** [comment]
> > TabLib issue. It has known compatibility problem with certain file containers that prevents it to extract the lyrics.
> 
> I see, is there a way to just prevent lyrics extraction? I don't really care for it personally. Nuking the .lrc files in /var/lib/jellyfin/metadata/libraries seems to 'fix' it. But the webui still shows the lyrics option for those songs.
> 
> ffprobe does seem to find the same data than what is in the extracted .lrc files though. (Unless those are unix style newlines vs the windows style \r\n ffprobe finds 🤔

Yes, you disable this:

<img width="649" alt="image" src="https://github.com/jellyfin/jellyfin/assets/12995396/5a42d09d-5072-458d-9079-f2d25dab60b6">

**Comment by sjorge** [comment]
Weird, I have that disabled already, but ffprobe is still triggered.

**Comment by sjorge** [comment]
Other observation, ffprobe output shows them as `lyrics-XXX` instead of `lyrics-eng` like the fines it does not complain about.

**Comment by gnattu** [comment]
> Weird, I have that disabled already, but ffprobe is still triggered.
> 
> Edit: for science, I'm gonna enable this and let it rescan to see if that 'fixes' it. Edit: doesn't seem to matter if that is checked or not

If you have it previously enabled, the already extracted ones will not be removed. You have to keep it disabled and remove all of them stored on the filesystem to mitigate this.

**Comment by gnattu** [comment]
> Other observation, ffprobe output shows them as `lyrics-XXX` instead of `lyrics-eng` like the fines it does not complain about.

This is the exact taglib problem.

**Comment by sjorge** [comment]
> > Weird, I have that disabled already, but ffprobe is still triggered.
> > Edit: for science, I'm gonna enable this and let it rescan to see if that 'fixes' it. Edit: doesn't seem to matter if that is checked or not
> 
> If you have it previously enabled, the already extracted ones will not be removed. You have to keep it disabled and remove all of them stored on the filesystem to mitigate this.

That stills shows the 'show lyrics' option for those songs when I disable/delete them from disk though.

**Comment by sjorge** [comment]
@gnattu I guess we should close this issue as won't fix, upstream ?

**Comment by gnattu** [comment]
> > > Weird, I have that disabled already, but ffprobe is still triggered.
> > > Edit: for science, I'm gonna enable this and let it rescan to see if that 'fixes' it. Edit: doesn't seem to matter if that is checked or not
> > 
> > 
> > If you have it previously enabled, the already extracted ones will not be removed. You have to keep it disabled and remove all of them stored on the filesystem to mitigate this.
> 
> That stills shows the 'show lyrics' option for those songs when I disable/delete them from disk though.

Will a replace all metadata scan help?

**Comment by sjorge** [comment]
> Will a replace all metadata scan help?

Cool that seems to work! Time to delete them all again and trigger refresh all on those songs.

**Comment by gnattu** [comment]
> @gnattu I guess we should close this issue as won't fix, upstream ?

For this very specific one, yes. But the taglib compatibility issue is real and will affect a lot of our users, and that is indeed a problem. So probably we can have a new issue called "better lyrics extraction" as enhancement and track the improvements there.

**Comment by sjorge** [comment]
Upstream, and workaround exists (disable lyrics extraction, remove them from disk, replace all metadata)

**Comment by sjorge** [comment]
I'm just going to script it and strip all lyric tags from all my media. I don't care about lyrics, this is a drastic measure but it seems to be the only way to get the ffprobes on ever rescan to stop.

**Comment by crobibero** [comment]
There is no way to actually disable lyric extraction. That checkbox only changes where it is extracted to

**Comment by sjorge** [comment]
That would explain the behavior I'm seeing.

I managed to strip just the lyrics-* tags from all my music and now the ffprobe every scan are gone. Not ideal.
