### ISSUE TITLE
TV-Series name detection improvement

### ISSUE THREAD

**Issue by platinum55** [jellyfin/jellyfin#1164]
### Problem:
TV documentations(mkv) in folders named like this:

Garden.Impressions.S01E01.Koburu.in.Brazil.CZECH.DOKU.HDTV.x264-RiO
Garden.Impressions.S01E02.Zhongshan.in.China.CZECH.DOKU.HDTV.x264-RiO

are not detected as expected. The name is just the foldername without any modifications.

### Expected

Detect series "Garden Impressions"
with one Season (Season 1 in this case)
and two Episodes:
"Koburu in Brazil" and "Zhongshan in China"

**Comment by Ribesg** [comment]
Everybody has its own way of naming things and Jellyfin, like Emby, does its best to understand what is what by searching on different sources.

I think that your problem is that the series you have cannot be found in those sources, for example I can't find it on TheTVDB https://www.thetvdb.com/search?q=Garden+Impressions&l=en

Once it finds the series on a source, it then can detect things like `S01E01` and get the proper title from the source. In does not try to predict how you named your files.

You should:
1. Make sure the series is known by one of the sources you have configured
2. Organize your files so that Jellyfin can easily recognize them, something like `series/Garden Impressions/Season 1/S01E01.mkv`

**Comment by JustAMan** [comment]
Is it by any chance related to #1033? That is, does it fail to detect the series even if you replace dots with spaces?

**Comment by edegrave** [comment]
I've noticed that the series Magnum is not detected correctly. There is an old and a new version which I both have. On https://www.thetvdb.com/search?q=magnum&l=en there is only a , difference in the name which works fine on Sonarr but when jellyfin indexes the collection both are show as the new version. I do (Sonarr) rename all series to: {Series Title} - S{season:00}E{episode:00} - {Episode Title} - {Quality Full} but I would expect that the meta data should be enough to keep both separated and recognized (Sonarr does). Any way to fix this manually perhaps?

**Comment by EraYaN** [comment]
Normally thetvdb would append the year to the name, but they seem to not have opted for that this time.

**Comment by anthonylavado** [comment]
>Any way to fix this manually perhaps?

@edegrave Yes. Locate the TVdb ID or other for the series you want to “fix”. Find the series in Jellyfin, and click the three dot menu “…”. Choose “Identify”. Enter the correct ID in the right field, and search. It will now tie it to that ID for you.

**Comment by edegrave** [comment]
That fixed it, thanks a million!

**Comment by JustAMan** [comment]
If you wish to keep original name intact use a sym- or hardlink with a confirming naming scheme.
It's a losing game trying to make a parser flexible enough to handle all funny naming schemes sceners can invent.

**Comment by wrong1man** [comment]
> Everybody has its own way of naming things and Jellyfin, like Emby, does its best to understand what is what by searching on different sources.
> 
> I think that your problem is that the series you have cannot be found in those sources, for example I can't find it on TheTVDB https://www.thetvdb.com/search?q=Garden+Impressions&l=en
> 
> Once it finds the series on a source, it then can detect things like `S01E01` and get the proper title from the source. It does not try to predict how you named your files.
> 
> You should:
> 
> 1. Make sure the series is known by one of the sources you have configured
> 2. Organize your files so that Jellyfin can easily recognize them, something like `series/Garden Impressions/Season 1/S01E01.mkv` or just `series/Garden Impressions/S01E01.mkv`. Note that `series/Garden Impression/Garden.Impressions.S01E01.Koburu.in.Brazil.CZECH.DOKU.HDTV.x264-RiO/anything.mkv` should also work, as it will find the `S01E01` in the file name

Allow me to butt in, while people can use whatever naming/organizing they want with their files, the method for naming TV shows that the OP mentioned is indeed a standardized and widely used method.

**Comment by coccobellof5** [comment]
It's an old topic.
But me too, I want to continue to stay in seed with torrents and I can't rename.
It is advisable to make the association of contents with tmdb, tvdb etc. "dynamic" in some way.

A custom system would make the association of contents easier in different countries around the world.
