### ISSUE TITLE
[Issue]: Season titles keep reverting to "Season 1", "Season Unknown" etc after being edited manually.

### ISSUE THREAD

**Issue by BrianCrowe3** [jellyfin/jellyfin#11655]
### Please describe your bug

After updating from 10.8.13 to 10.9.0 and then again to 10.9.1, I noticed all of the manual edits I've made to season titles reverted either to "Season 1", "Season 2" etc in the case that the season was numbered, or "Season Unknown" is the case that it wasn't numbered.

After making the edits again, I noticed that they reverted back to "Season 1" "Season Unknown" etc again, regardless of whether the "Lock this item to prevent future changes" box is ticked or not. 

I have "Metadata savers\Nfo" enabled in library settings, whatever is happening is also editing the "title" part of the nfo files themselves to be "Season 1" "Season Unknown" etc.

### Reproduction Steps

1. Install Jellyfin server on fully updated Windows 10
2. Edit the title of a season
3. At some point within ~4 hours or so it will revert the edit back to "Season 1" etc or "Season Unknown"

### Jellyfin Version

10.9.0

### if other:

10.9.1

### Environment

```markdown
- OS: Windows 10 Pro Build 19045
- Linux Kernel: none
- Virtualization: none
- Clients: Browser
- Browser: Firefox 115.11.0esr
- FFmpeg Version: 6.0.1-Jellyfin
- Playback Method: Direct Play
- Hardware Acceleration: NVENC
- GPU Model: GTX 960
- Plugins: AniDB, AniList, AniSearch, Fanart, TMDB, Studio Images, OMDb, MusicBrainz, AudioDB
- Reverse Proxy: Caddy
- Base URL: none
- Networking: Host
- Storage: local
```

### Jellyfin logs

```shell
Changes to season titles don't appear to be logged.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shadowghost** [comment]
Likely fixed by #11647
