### ISSUE TITLE
[Issue]: Edit User's Profile from admin dashboard not changing anything for the user

### ISSUE THREAD

**Issue by DwayneGoddem** [jellyfin/jellyfin#11683]
### Please describe your bug

I was trying to enable Theme songs and Subtitle settings for a user via the Admin Dashboard "Edit User's Profile"
While the screens all work and I can select and save setting. go back in and check they are saved.

When the user logs in nothing is changed for them

This was happening in 10.8.x as well I don't know about below versions.

### Reproduction Steps

Login in as admin
Goto the dashboard -> users
select a user
Click "Edit User's Profile"
Change a setting and click save
Login in as they users in another browser or computer
Check via the "icon in the top right" if the setting was changed on the user

### Jellyfin Version

10.9.0

### if other:

10.9.1

### Environment

```markdown
- OS: Windows
- Linux Kernel:
- Virtualization:
- Clients: Chrome
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
no logs for this function
```

### Please attach any screenshots here

The user has this
![image](https://github.com/jellyfin/jellyfin/assets/117789611/fe05893f-bbc6-4826-90bf-3e1f6a2e4dce)

The Admin screen shows this
![image](https://github.com/jellyfin/jellyfin/assets/117789611/c6686509-14da-481e-be4d-874400bde45d)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
Some of these settings are only stored in the client (eg current browser session)
This would be a web client feature request.
