### ISSUE TITLE
Add GIDLIST env var to docker image

### ISSUE THREAD

**Issue by LeoVerto** [jellyfin/jellyfin#117]
Using hardware decoding from inside the docker container requires access to `/dev/dri/renderD128` which is usually owned by `root:video`, neither of which jellyfin is running as.

The [official emby image](https://hub.docker.com/r/emby/embyserver/) uses an environment variable called `GIDLIST` to specify additional groups for the process to run as which solves this problem, we should implement something similar.

**Comment by joshuaboniface** [comment]
@LeoVerto Have we worked out an alternative to this, or is it still an issue?

**Comment by LeoVerto** [comment]
As far as I'm aware this is still an issue but not an immediate one as hardware-accelerated decoding is broken anyway.

But once we get our own ffmpeg builds up we'll either need to have something like GIDLIST or tell users to run jellyfin with `--user=user:video` which could work but is pretty limiting (i.e. when the library is owned by another user).

Meanwhile I've seen people recommend changing `/dev/dri/renderD*` permissions to 777 which is obviously not a good solution.

**Comment by JustAMan** [comment]
I'm not well versed in docker, but in lxc I added a `mknod` in startup script which creates render device inside the container prior to running it with correct permissions. Docker is run as `root` anyway, so it should be doable, too.

**Comment by LeoVerto** [comment]
While docker itself is running as root, it's considered good practice to run applications inside the container as a non-root user. That user will then have to run with a PID/GID that is allowed to access files on mounts/passed through devices in order for it to also have access.

For example while `docker run --device=/dev/sda:/dev/xvdc --rm -it ubuntu fdisk /dev/xvdc` will successfully start fdisk in a container running as root, `docker run --device=/dev/sda:/dev/xvdc --rm --user 123:123 -it ubuntu fdisk /dev/xvdc` won't work.

**Comment by nvllsvm** [comment]
Docker has a built-in feature for this too: [`--group-add`](https://docs.docker.com/engine/reference/run/#additional-groups).

```
$ docker run --rm --user 1234:5678 --group-add 9999 --group-add 1111 alpine id
uid=1234 gid=5678 groups=1111,9999
```

It is only available in Docker Compose format v2 however.

**Comment by LeoVerto** [comment]
@nvllsvm Thank you, I didn't know about that! But I also use compose v3 so yeah…

Do you think we could implement [this workaround](https://github.com/docker/compose/issues/4700#issuecomment-419735761)?

**Comment by nvllsvm** [comment]
Let's just modify the Docker image to accept a GIDLIST for now. Even if Docker Compose is updated, it'll take a while for it to release.

**Comment by nvllsvm** [comment]
Eh - I've just switched from Compose format 3.7 to 2.4 without any modifications. 

After reviewing the differences between the latest 2.x spec and the 3.x specs, I'm not sure I'd like to add a `GIDLIST`. I'd rather just encourage folks to downgrade and wait to see if anyone is actually using one of the features of the 3.x spec.
