### ISSUE TITLE
JF OOTB Collections get duplicated if TMDB Box Sets option is clicked

### ISSUE THREAD

**Issue by spcano01** [jellyfin/jellyfin#11722]
### Please describe your bug

OOTB works perfectly if you choose to add movies into collection under manage library.  This requires TMDB plugin (I believe).

Recently, I went to that plugin settings and saw it offered a box to "Strip Keyword from title".  Effectively making "300 Collection" into "300".  Love it!  But...it added (mostly) all new collections and duplicated the assigned movies, on some it just duplicated all movies under a single collection.  I thought I had messed up, so I deleted that library and rescanned all libraries.

Still same issue.  For now, I unchecked that box and will wait to see if we can incorporate that option more cleanly. 

Thanks all!

### Reproduction Steps

1. Check option under libraries to add movies to collections.
2. Go to TMDB Box Sets plugin and check "Strip Keyword from title".
3. Rescan libraries
4. Also happens if you start from scratch ad have it build collections automatically with checkbox chosen. 

### Jellyfin Version

10.9.0

### Environment

```markdown
- OS: Linux docker
- Linux Kernel: 
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
Will edit with logs when I return.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Mihara** [comment]
Notably, this did not happen to me before 10.9.4, but suddenly started happening upon upgrade. Same basic setup: a movies library, "strip keyword from title" checkbox checked.

I'm not entirely clear *when* this happens yet, (lots of things going on) but a ghost collection gets created, which contains the same movies as the collection with the keyword stripped, is named with the keyword intact, and has no images. If I empty it and destroy the collection, it gets recreated at some later point.

**Comment by Mihara** [comment]
Yes, ticking the "Automatically add to collection" option off in "Manage Library" seems to have resolved the problem, the duplicate "X Collection" sets stopped popping up.

We definitely have a feature conflict here.

**Comment by spcano01** [comment]
Also, when duplicate sets are not created - the single set still has duplicate videos.  So if you have 2 movies with both HD & 4K in a single collection - you will show 4 movies in that collection.  2 being the exact same, but usually different box art.
