### ISSUE TITLE
[Issue]: Jellyfin upgrade hangs on Ubuntu 22.04

### ISSUE THREAD

**Issue by jramseygreen** [jellyfin/jellyfin#11737]
### Please describe your bug

This occurred on both when I was upgrading from jellyfin 10.8.x to jellyfin 10.9.1 and just today when I tried to upgrade from jellyfin 10.9.1 to jellyfin 10.9.2. I run `sudo apt upgrade` which successfully pulls everything in and unpacks it, then it will get stuck on the post install script step of the `jellyfin-server` package.

After investingating, I found that it was hanging on the line `chown -R ${JELLYFIN_USER} $PROGRAMDATA $CONFIGDATA $LOGDATA $CACHEDATA` and after commenting it out the upgrade completed successfully.

I checked the owner of all the locations listed and the owner is set correctly, so there's no issues with my jellyfin having done this thankfully, although I do find it strange why this would be happening

### Reproduction Steps

1. install jellyfin 10.9.1 on ubuntu 22.04
2. run `sudo apt upgrade` to upgrade from 10.9.1 to 10.9.2
3. the upgrade process freezes indefinitely on the post install script step of upgrading `jellyfin-server`

### Jellyfin Version

10.9.1

### if other:

10.9.1

### Environment

```markdown
- OS: Ubuntu 22.04
- Linux Kernel: 5.15.0-107-generic
- Virtualization: None
- Clients: N/A
- Browser: N/A
- FFmpeg Version: jellyfin-ffmpeg 6.0.1
- Playback Method: N/A
- Hardware Acceleration: N/A
- GPU Model: None
- Plugins: N/A
- Reverse Proxy: N/A
- Base URL: N/A
- Networking: N/A
- Storage: local
```

### Jellyfin logs

```shell
No logs to provide
```

### FFmpeg logs

```shell
No logs to provide
```

### Please attach any browser or client logs here

No logs to provide

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TimGels** [comment]
The title mentions 20.04 but the steps indicate 22.04. Which one is it?

**Comment by jramseygreen** [comment]
> The title mentions 20.04 but the steps indicate 22.04. Which one is it?

Sorry about that, typo.

I've updated the post - it's 22.04

**Comment by TimGels** [comment]
Thanks for updating it! I will spin up a Ubuntu 22.04 VM to see if I can reproduce the hanging. Upgrading from 10.9.1 to latest 10.9 (10.9.2 as of writing this).

**Comment by TimGels** [comment]
@jramseygreen Upgrading from 10.9.1 to 10.9.2 with apt went without issues for me. I did not encounter any hanging.

![afbeelding](https://github.com/jellyfin/jellyfin/assets/43609220/d61d5bfa-841f-4c36-99aa-fd9b2e2c492d)

![afbeelding](https://github.com/jellyfin/jellyfin/assets/43609220/8b8b56ef-9306-4cd1-8fbb-a4c56128228c)

![afbeelding](https://github.com/jellyfin/jellyfin/assets/43609220/881f29cf-9886-4470-8065-2d5c8f98e807)

![afbeelding](https://github.com/jellyfin/jellyfin/assets/43609220/acc5aac1-40a2-414b-a9ae-5e2be6ecfb9f)

**Comment by jramseygreen** [comment]
I run ubuntu on a native system, which I might add is the only system I have access to for such purposes.

When this first occurred on my upgrade from 10.8.x to 10.9.1 I fully reinstalled the OS because I assumed something weird had gone wrong so I took it from fresh. Upon the update from 1.9.1 to 1.9.2 mere days after the reinstall exactly the same thing happened.

I wonder if it's hardware specific?

Regardless, with the next upgrade for 1.9.2 to 1.9.3, I'd be happy to document everything and post it here as I feel it's likely the issue will reoccur.

If there's anything in the meantime I may be able to do in order to provide you with more details please let me know.

**Comment by oddstr13** [comment]
It is likely not hanging, but using a long time to execute, assuming you have a large library.
Could be made worse depending on fs type and or drive type (NVME vs SD card).

That command is iterating over all jellyfin files, and making sure that the jellyfin user has write access to them.
This includes things like all images and some other metadata.

Simply listing Jellyfin's home folder took a little over one minute on my production system, producing almost 25k files and directories, and I don't consider my library to be very large. (`time find ~jellyfin/ | wc -l`)

I'd suggest grabbing a cup of $favorite_hot_beverage while chown does it's thing, as this could take several minutes.

We might want to echo a warning about that to the terminal before executing the command.
