### ISSUE TITLE
Low resolution images through DLNA

### ISSUE THREAD

**Issue by miegl** [jellyfin/jellyfin#1174]
**Describe the bug**
When viewing photos (images) through DLNA, jellyfin serves a very low resolution picture (looks like a thumbnail) instead of a full-res one. This happens on multiple DLNA clients (tried VLC and PS3).

**To Reproduce**
View any picture through DLNA.

**Expected behavior**
I expected to get a full picture instead of what looks like a thumbnail.

**Screenshots**
![screenshot](https://i.imgur.com/NtBW9Eh.png)

**System:**
 - OS: Arch Linux
 - DLNA Client: VLC, PS3 
 - Jellyfin Version:  10.2.2

**Comment by JustAMan** [comment]
Are you viewing videos or images specifically?

**Comment by miegl** [comment]
> Are you viewing videos or images specifically?
images. By picture I mean image, sorry if that wasn't clear.
