### ISSUE TITLE
[Issue]: Direct Play (ffmpeg) uses too much CPU usage

### ISSUE THREAD

**Issue by vegedb** [jellyfin/jellyfin#11753]
### Screenshot

![image](https://github.com/jellyfin/jellyfin/assets/72070424/ad4eaf8f-6975-44f6-a163-d4f6a4b31030)
![image](https://github.com/jellyfin/jellyfin/assets/72070424/0d137554-0af1-46e6-85b5-95ebe615a9a4)
![image](https://github.com/jellyfin/jellyfin/assets/72070424/ff27ad83-bfc0-4dce-9068-2c17693768f8)
![image](https://github.com/jellyfin/jellyfin/assets/72070424/e50845d0-8444-4e19-9da8-2f78bfedb5c3)

### Please describe your bug  

As you can see in the screenshot, direct playing uses ffmpeg, is that normal?
Also it uses way too much CPU usage when scrubbing, and takes too long to normalize after scrubbing.

### Jellyfin Version

10.9.2

### Environment

```markdown
- OS: Raspberry Pi 4GB Raspbian 64bit
```

**Comment by felix920506** [comment]
You are using a low end system that is significantly below the recommended system specs. High CPU load is expected. Please select appropriate hardware according to the documentation 
https://jellyfin.org/docs/general/administration/hardware-selection/

**Comment by Bond-009** [comment]
Your screenshot doesn't show ffmpeg usage, it shows Jellyfin with the args passed to it, one of which is the path where it should look for ffmpeg. It also shows jellyfin only using 38% CPU.

**Comment by vegedb** [comment]
> Your screenshot doesn't show ffmpeg usage, it shows Jellyfin with the args passed to it, one of which is the path where it should look for ffmpeg. It also shows jellyfin only using 38% CPU.

You clearly do not know how to read htop, its fine.
The point is direct playback uses significant cpu usage from the server, playing back through smb has 0 cpu usage.

**Comment by ferferga** [comment]
@vegedb As @Bond-009 said, your screenshot does not show any ffmpeg usage. If ffmpeg it's running, there's no way to know from the info you provided at least.

And yes, Jellyfin it's using 38% of CPU, them being repeated means that the process is using 4 threads, but htop displays the CPU usage shared across them (with percents > 100 when consuming more than one thread). 

Are you scrubbing with trickplay enabled?

**Comment by gnattu** [comment]
From your bar, more than half is in red, which means more than half of the CPU time is spent on kernel, and the rest it from userspace.

Your screenshot does not indicate if ffmpeg is used or not. Not at all. For all ffmpeg usage jellyfin will record a log and if yo don't see one in the dashboard with the time you are direct playing, no, jellyfin is not using ffmpeg.

Your system was indeed having a heavy load, but you provided too little information and jumped to the conclusion to blame jellyfin too early.

**Comment by vegedb** [comment]
> @vegedb As @Bond-009 said, your screenshot does not show any ffmpeg usage. If ffmpeg it's running, there's no way to know from the info you provided at least.

Just curious, does direct play uses ffmpeg? Always thought its only being used if transcoding is involved.


> Are you scrubbing with trickplay enabled?

Its disabled. But ever since i've updated to 10.9.2, post scrubbing will take a relatively LONG time to normalize.

**Comment by vegedb** [comment]
> Your screenshot does not indicate if ffmpeg is used or not. Not at all. For all ffmpeg usage jellyfin will record a log and if yo don't see one in the dashboard with the time you are direct playing, no, jellyfin is not using ffmpeg.

That's the problem, its direct play, so there's no log at all. Funny how ffmpeg is used for Direct Play but there's no log.

> Your system was indeed having a heavy load, but you provided too little information and jumped to the conclusion to blame jellyfin too early.

Nope, after I stop playback it becomes low instantly. Also post-scrubbing will normalize to low levels as well.

**Comment by gnattu** [comment]
> That's the problem, its direct play, so there's no log at all. Funny how ffmpeg is used for Direct Play but there's no log.

Because **it is not using ffmpeg**

**Comment by vegedb** [comment]
> Because **it is not using ffmpeg**

Then what does it use? 
Tested using mpv player as external to make it a fair comparison.
Jellyfin = 80-90% CPU usage
Compared to playback using "SMB" = close to 0% CPU usage.

**Comment by vegedb** [comment]
@gnattu @ferferga @Bond-009 @felix920506 

Look at jellyfin's cpu usage when I scrub compared to SMB. Both are using MPV player direct playback.
Tried my best showing you guys the issue, hope this helps. 

### Jellyfin
![jellyfin](https://github.com/jellyfin/jellyfin/assets/72070424/7efce63a-f1e0-42fa-9090-ce3bbe6362f1)

### SMB
![smb](https://github.com/jellyfin/jellyfin/assets/72070424/8d29bdd0-abc1-42e4-a786-59057fd52894)

**Comment by dzaqwan** [comment]
I have the same problem. Direct play with high CPU load. Sometimes it's so high that warning of thread pool starvation appeared in the log. 

My CPU is i7-7700. Had no problem before the 10.9.z updates
