### ISSUE TITLE
[Issue]: API endpoint "Libraries/AvailableOptions" publicly readable

### ISSUE THREAD

**Issue by hlinden** [jellyfin/jellyfin#11764]
### Please describe your bug

curl https://myserver/Libraries/AvailableOptions returns a subset of the available metadata handlers. This is not necessary for an unauthenticated user and should be avoided.

### Reproduction Steps

Install.

Call API.

Result.

### Jellyfin Version

10.9.0

### if other:

10.9.1

### Environment

```markdown
- OS: not really relevant
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
not really relevant
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
This was also fixed by https://github.com/jellyfin/jellyfin/pull/11651 and is available in 10.9.2
