### ISSUE TITLE
[Issue]: Current Jellyfin debuntu repos too out of date for use with latest Jellyfin desktop client.

### ISSUE THREAD

**Issue by AntsyBoi** [jellyfin/jellyfin#11765]
### Please describe your bug

The latest version of the [Jellyfin desktop client (v1.10.1)](https://github.com/jellyfin/jellyfin-media-player/releases/tag/v1.10.1) requires the minimum server version of [v10.9.1](https://github.com/jellyfin/jellyfin/releases/tag/v10.9.1) when the latest version of Jellyfin available in the deb releases (10.8.13) is below that minimum requirement. Making it impossible to use the current version of Jellyfin desktop with the an Ubuntu hosted server.

### Reproduction Steps

1. Install Jellyfin on an Ubuntu/Debian host using `curl -s https://repo.jellyfin.org/install-debuntu.sh | sudo bash`
2. Try to connect using the latest desktop client

### Jellyfin Version

10.8.13

### Environment

```markdown
- OS: Ubuntu Server 23.10 Linux
- Linux Kernel: 6.5.0-35-generic
- Clients: Jellyfin desktop client
```

### Jellyfin logs

```shell
No logs, just throws the "out of date server" error.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
Jellyfin only supports LTS versions of Ubuntu with 10.9 (and future)

**Comment by AntsyBoi** [comment]
This affects LTS versions of Ubuntu as well as it is the latest version available for the distro. As seen in https://repo.jellyfin.org/releases/server/ubuntu/stable/server/

**Comment by crobibero** [comment]
You are in the legacy repo path. 

https://repo.jellyfin.org/?path=/server/ubuntu/latest-stable/amd64

**Comment by ctrlaltdylan** [comment]
I had this issue as well, but I was running an older version (18.x) version of Ubuntu. Upgrading to a higher LTS version to see if that makes a difference.

**Comment by ctrlaltdylan** [comment]
@joshuaboniface Hm no luck yet.

Upgraded to v20.04:

```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal
```
Since`jellyfin` was still on v18, I thought an update would do the trick:

```
$ sudo apt update
$ sudo apt-get install --only-upgrade jellyfin
Reading package lists... Done
Building dependency tree
Reading state information... Done
jellyfin is already the newest version (10.8.13-1).
```
But jellyfin is definitely still on 10.8. Maybe running the installer from scratch will do the trick and get the correct repo.

**Comment by joshuaboniface** [comment]
Ensure you also update your `/etc/apt/sources.list.d` entry to use `focal`, that might still be wrong.
