### ISSUE TITLE
[Issue]: Jellyfin changes back metadata on refresh despite manual identification

### ISSUE THREAD

**Issue by ericswpark** [jellyfin/jellyfin#11773]
### Please describe your bug

Jellyfin keeps changing back metadata for media even if I use the "Identify..." functionality to tell Jellyfin what the content actually is. Mainly happens with foreign content such as Korean movies. Examples include:

- Burning (2018)
- The Phone (2015)
- Mother (2009)
- Deranged (2012)
- The Call (2020)

The movie files follow the naming syntax outlined by the documentation, but I'm guessing Jellyfin is still misidentifying them because there are multiple movies with the same name and release year.

Ideally, Jellyfin should remember that the user/admin has properly identified a piece of content and remember the unique ID from the manual identification, so that the next metadata refresh gets updated metadata from the correct content. Locking metadata is a workaround that will prevent future updates to the metadata should they become available.

### Reproduction Steps

1. See Jellyfin has misidentified media
2. Correctly tag media with "Identify"
3. Wait until next metadata refresh
4. Jellyfin sometimes overwrites correct metadata with that from a different movie/show

### Jellyfin Version

10.9.0

### if other:

10.9.2

### Environment

```markdown
- OS: Unraid
- Linux Kernel: 6.1.79-Unraid
- Virtualization: Docker
- Clients: Browser
- Browser: 124.0.6367.208 (Official Build) (64-bit) (cohort: Control) 
- FFmpeg Version: ffmpeg version 6.0.1-Jellyfin 
- Playback Method: N/A
- Hardware Acceleration: VAAPI
- GPU Model: AMD Ryzen 5 PRO 4650G with Radeon Graphics
- Plugins: AniDB, AudioDB, MusicBrainz, OMDb, Open Subtitles, Playback Reporting, Reports, Studio Images, Subtitle Extract, TMDb, TMDb Trailers, Trakt, Webhook
- Reverse Proxy: nginx
- Base URL: none
- Networking: Bridge/NAT
- Storage: local
```

### Jellyfin logs

```shell
N/A
```

### FFmpeg logs

```shell
N/A
```

### Please attach any browser or client logs here

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TimGels** [comment]
@ericswpark This should be solved in https://github.com/jellyfin/jellyfin/pull/11743. See test scenario 3 https://github.com/jellyfin/jellyfin/pull/11743#issuecomment-2130136145

**Comment by ericswpark** [comment]
Great, thank you so much @TimGels! I've subscribed to the PR but for some reason the potential issues fixed haven't been linked back to their issue threads, despite the "Fixes" keyword in front of each issue number. I'll keep this issue open until the PR is merged.

**Comment by ericswpark** [comment]
This seems to be fixed, closing!
