### ISSUE TITLE
Intel Quick Sync and VAPPI broken on H.265 content

### ISSUE THREAD

**Issue by Essasetic** [jellyfin/jellyfin#1179]
**Describe the bug**
When experimenting with Intel Quick Sync I've noticed a very significant difference in terms of CPU Usage and Video Playback on H.264 and H.265 content. 

H.264 content doesn't take up much of the CPU (around 15-20% for a 1080p video) and the video playback is great and loads almost immediately. Which suggests Quick Sync is working

H.265 content immediately takes up 100% of the CPU and buffers after 1-2 seconds of video playback. The video also takes around 30 seconds to even load.

**To Reproduce**
Load up any video that is in the H.265 codec 

**Expected behavior**
What I said about H.264 behaviour.

**Logs**
Will provide them soon (if it's necessary to solve the issue).

**Screenshots**
Will provide screenshot comparisons soon.

**System (please complete the following information):**
 - OS: Synology DSM
 - Browser: Firefox and Android App
 - Jellyfin Version: 10.2.2
 - Reverse proxy: no

EDIT: Just realised I've been using Intel Quick Sync. Will do further testing tomorrow.

EDIT 2: VAPPI is also broken.

**Comment by JustAMan** [comment]
Please provide media info on the problematic files, plus ideally your CPU name (on Linux look under `/proc/cpuinfo` or issue `lscpu` command).

**Comment by Essasetic** [comment]
![Pure x265 file](https://user-images.githubusercontent.com/34970796/55342471-ca79ef00-54a0-11e9-81cb-692f925b4f40.PNG)

This was the sample I was testing and CPU Usage is around 95-100%

**Comment by EraYaN** [comment]
ffmpeg logs and command lines would be very useful.

**Comment by Essasetic** [comment]
I've come back to close this issue. The reason being because 10bit simply isn't fully supported on Apollo Lake. I'm making the decision to sell my 218+ and build a custom NAS with a i5 8400. Tuere are still 10bit issues on Jellyfin but this one is no longer relevant. Thanks!
