### ISSUE TITLE
Improved/Enhanced ISO Playback

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin#118]
In #104, it was noted that ISO Playback works, but you'll get this message:
https://github.com/jellyfin/jellyfin/issues/104#issuecomment-446747699

>Playback of ISO files in this app is experimental. Some titles may not work at all. For a better experience, consider converting to mkv video files, or use an Jellyfin app with native ISO support.

This issue is to review the reasons for this message, and to eventually enhance ISO playback to remove the need for that message (wherever possible).

**Comment by cvium** [comment]
Should Jellyfin even support this feature? The current implementation mounts the ISO, which is gross since it requires *nix and _sudo_.

**Comment by EraYaN** [comment]
We don't have to extract to the file system, we can just write the correct ts files, to stdin for ffmpeg.
