### ISSUE TITLE
[Issue]: folder.jpg not stored with media but the other art is

### ISSUE THREAD

**Issue by ismay** [jellyfin/jellyfin#11815]
### Please describe your bug

Reopening this stale issue: https://github.com/jellyfin/jellyfin/issues/5642, because it hasn't been resolved and it's still a problem.

> In a Music library with Save artwork into media folders and nfos enabled, all art, artist.nfo and album.nfo are stored with the media folders except folder.jpg when using the automatic art fetchers. The folder.jpg is stored in /config/metadata/library/. Only when I manually upload a cover, folder.jpg is stored with the media. In both cases, the entry in the album.nfo is consistent with the described behaviour:

See the original issues for further details. I've reproduced this exact issue. In fact, I'd encountered this in the past, forgotten about it, and now encountered it again.

Expected behavior:

For folder.jpg to be stored in the media folder.

### Reproduction Steps

1. Enable Save artwork into media folders in a Music library
2. Get album art by refreshing

### Jellyfin Version

10.9.0

### Environment

```markdown
OS: Synology Diskstation OS (Linux)
Virtualization: official Docker image
Clients: Browser (but not relevant here)
Browser: Firefox 78.8 (but not relevant here)
Jellyfin Version: 10.7.1
Playback: Direct Play (but not relevant here)
Installed Plugins: issue with or without Cover Art Archive
Reverse Proxy: none
Base URL: none
Networking: Bridge
Storage: local, via docker mounts
```

### Jellyfin logs

```shell
No relevant log output found. I.e. no errors or anything.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by voronind-com** [comment]
The issue is still relevant
