### ISSUE TITLE
MPEG2 videos not listed in DLNA response

### ISSUE THREAD

**Issue by SenorSmartyPants** [jellyfin/jellyfin#1181]
**Describe the bug**
MPEG2 videos listed in latest videos on the web JF are not displayed in the latest folder in DLNA using VLC

**To Reproduce**

Start VLC and connect to JF server. Browse to TV Shows->Latest, cannot find new MPEG2 videos listed.
Also, browse to TV Shows->Shows. MPEG2 video will have a Series folder and Season folder generated correctly. The Season folder however will be empty.

**Expected behavior**

MPEG2 videos should be displayed.

**System (please complete the following information):**
 - OS: ARMHF Docker 
 - Browser: VLC  3.0.4
 - Jellyfin Version: [e.g. 10.2.2]

**Comment by SenorSmartyPants** [comment]
This is still happening in 10.3.7

```
jellyfin        | 2019-07-29T23:28:16.360406470Z [18:28:16] [INF] Profile: Generic Device, Path: /media/Videos/tvheadend/Grantchester/Grantchester - 4x01x02.ts, isEligibleForDirectPlay: True, isEligibleForDirectStream: True
jellyfin        | 2019-07-29T23:28:16.369246595Z [18:28:16] [INF] Profile: Generic Device, Path: /media/Videos/tvheadend/Grantchester/Grantchester - S04E03 -.ts, isEligibleForDirectPlay: True, isEligibleForDirectStream: True
jellyfin        | 2019-07-29T23:28:16.377160624Z [18:28:16] [INF] Profile: Generic Device, Path: /media/Videos/tvheadend/Grantchester/Grantchester - S04E04 -.ts, isEligibleForDirectPlay: True, isEligibleForDirectStream: True
```

None of the episodes listed above at displayed in VLC.

**Comment by JustAMan** [comment]
@SenorSmartyPants is this still an issue in 10.4.1?

**Comment by PrplHaz4** [comment]
@JustAMan i think I see this issue in the serverwmc plugin on 10.4.1. None of my livetv channels are listed in vlc but movies are.

**Comment by SenorSmartyPants** [comment]
> @SenorSmartyPants is this still an issue in 10.4.1?

@JustAMan I just confirmed that MPEG2-TS videos are not listed in the DLNA output. Same as before. Show and season folders are there, but no videos.

**Comment by PrplHaz4** [comment]
This was mostly fixed for me with 10.4.3.  Remaining DLNA issues for me are specifically related to m3u8 channels....captured my issue here: #2132

**Comment by SenorSmartyPants** [comment]
VLC still does not display MPEG2 .ts files from the Jellyfin DLNA. in 10.4.3

**Comment by Artiume** [comment]
is this fixed?

**Comment by SenorSmartyPants** [comment]
Just updated to 10.5.5 release. MPEG2 files are listed in DLNA and play.
