### ISSUE TITLE
[Issue]: Trickplay job hangs forever.

### ISSUE THREAD

**Issue by voronind-com** [jellyfin/jellyfin#11828]
### Please describe your bug

Trickplay images are not generated. It was stuck for 24 hours at 0% done - multiple attempts. Tried restarting and everything. Other parts of JF work fine. The log bellow is the only thing that is printed after the job manually started.

### Reproduction Steps

1. Docker container (latest).
2. Start Trickplay generation job.
3. Wait a long time.
4. ...
5. Nothing!

### Jellyfin Version

10.9.0

### if other:

10.9.2

### Environment

```markdown
- OS: NixOS Unstable
- Linux Kernel: 6.8.7
- Virtualization: Docker version 24.0.9, build v24.0.9
- Clients: Browser, Android, TV.
- Browser: Firefox ESR.
- FFmpeg Version: Built-in.
- Playback Method: -
- Hardware Acceleration: VAAPI
- GPU Model: Radeon 550.
- Plugins: Metadata fetchers only.
- Reverse Proxy: Nginx.
- Base URL: none
- Networking: Docker Bridge
- Storage: Local
```

### Jellyfin logs

```shell
watch  | [22:36:38] [INF] [19] Jellyfin.Server.Implementations.Trickplay.TrickplayManager: Creating trickplay files at 320 width, for /storage/show_1/Planet Earth II (2016)/Season 01/Episode S01E01.mkv [ID: a1e4b599-f2e1-8523-7891-19a0128b9c2f]
watch  | [22:36:38] [INF] [19] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Trickplay generation: /usr/lib/jellyfin-ffmpeg/ffmpeg -loglevel error -threads 1 -noautorotate -i file:"/storage/show_1/Planet Earth II (2016)/Season 01/Episode S01E01.mkv" -an -sn -vf "fps=0.10000000149011612,setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale=trunc(min(max(iw\,ih*a)\,320)/2)*2:trunc(ow/a/2)*2,format=yuv420p" -threads 1 -c:v mjpeg -qscale:v 4 -f image2 "/cache/temp/6459dabcc3fa43cbbf73527d94bfa0a4/%08d.jpg"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gnattu** [comment]
It is *that* slow. We will introduce faster generation in 10.10 but currently it is this slow. 

If you go to the data folder and look for caches, like the `/cache/temp/6459dabcc3fa43cbbf73527d94bfa0a4/` printed in your log, and if you can see jpgs being generated and keeps going then it is working as intended, just painfully slow. This will be more severe when your CPU is underpowered.

**Comment by csidirop** [comment]
> It is _that_ slow. We will introduce faster generation in 10.10 but currently it is this slow.

Hi @gnattu , can you recall the RP or commit that updated the trickplay job?

**Comment by voronind-com** [comment]
> Holy crap, same thing here. Disabling it. Thanks

It actually works okay-ish now if you enable everything in Playback > Trickplay. I wouldn't actually enable it if you have no HW transcoding.
