### ISSUE TITLE
[Issue]: 404 when clicking video playback

### ISSUE THREAD

**Issue by wangweiweiwei** [jellyfin/jellyfin#11836]
### Please describe your bug

I have newly installed version 10.9.2.
My Jellyfin is installed on a server on the intranet. The IP is 192.168.1.28. When I access directly using 192.168.1.28, everything works fine.
But when I use the router to do port forwarding for access, this problem occurs.
xxx.com:5896(Public Ip)->my router(192.168.1.1)->port forwarding->192.168.1.28:5896
Occurs when a video is clicked to play
Chrome console info：
requestURL：http://xxx.com:5896/Users/c2a7b70039004695ad6f49d844506e6d/Items/f1d467fb393671814513d6162625415e
respnse:{
    "type": "https://tools.ietf.org/html/rfc9110#section-15.5.5",
    "title": "Not Found",
    "status": 404,
    "traceId": "00-03d9842b0dc872f2cef33403c87d309d-8771edb437131277-00"
}

My router has a public IP and I want to access Jellyfin on the public network through this method, so I encountered this situation. I guess the compatibility of Jellyfin is not good enough. Jellyfin also did not print the relevant error log. I'm confused!

### Reproduction Steps

xxx.com:5896(Public Ip)->my router(192.168.1.1)->port forwarding->192.168.1.28:5896

### Jellyfin Version

10.9.0

### if other:

10.9.2

### Environment

```markdown
- OS:My Systems is Windows11，Jellyfin is Docker
- Linux Kernel:not involving
- Virtualization:
- Clients:
- Browser: 125.0.6422.78
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:

<NetworkConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <BaseUrl />
  <EnableHttps>false</EnableHttps>
  <RequireHttps>false</RequireHttps>
  <InternalHttpPort>5896</InternalHttpPort>
  <InternalHttpsPort>8920</InternalHttpsPort>
  <PublicHttpPort>8096</PublicHttpPort>
  <PublicHttpsPort>8920</PublicHttpsPort>
  <AutoDiscovery>true</AutoDiscovery>
  <EnableUPnP>false</EnableUPnP>
  <EnableIPv4>true</EnableIPv4>
  <EnableIPv6>false</EnableIPv6>
  <EnableRemoteAccess>true</EnableRemoteAccess>
  <LocalNetworkSubnets />
  <LocalNetworkAddresses />
  <KnownProxies>
    <string>xxx.com</string>
  </KnownProxies>
  <IgnoreVirtualInterfaces>true</IgnoreVirtualInterfaces>
  <VirtualInterfaceNames>
    <string>veth</string>
  </VirtualInterfaceNames>
  <EnablePublishedServerUriByRequest>false</EnablePublishedServerUriByRequest>
  <PublishedServerUriBySubnet />
  <RemoteIPFilter />
  <IsRemoteIPFilterBlacklist>false</IsRemoteIPFilterBlacklist>
```
- Storage:
```


### Jellyfin logs

```shell
[05:17:39] [INF] [65] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 192.168.1.1 request
```

### Please attach any browser or client logs here

Requesting http://xxx.com:5896/Users/c2a7b70039004695ad6f49d844506e6d/Items/f1d467fb393671814513d6162625415e
node_modules.jellyfin-apiclient.bundle.js?c63110386127b8fcd20f:2 
        
        
       GET http://xxx.com:5896/Users/c2a7b70039004695ad6f49d844506e6d/Items/f1d467fb393671814513d6162625415e 404 (Not Found)
（匿名） @ node_modules.jellyfin-apiclient.bundle.js?c63110386127b8fcd20f:2
w @ node_modules.jellyfin-apiclient.bundle.js?c63110386127b8fcd20f:2
k @ node_modules.jellyfin-apiclient.bundle.js?c63110386127b8fcd20f:2
value @ node_modules.jellyfin-apiclient.bundle.js?c63110386127b8fcd20f:2
value @ node_modules.jellyfin-apiclient.bundle.js?c63110386127b8fcd20f:2
value @ node_modules.jellyfin-apiclient.bundle.js?c63110386127b8fcd20f:2
value @ node_modules.jellyfin-apiclient.bundle.js?c63110386127b8fcd20f:2
$ @ main.jellyfin.bundle.js?c63110386127b8fcd20f:2
r.play @ main.jellyfin.bundle.js?c63110386127b8fcd20f:2
S @ 39435.69c90e515266013a522e.chunk.js:1
T @ 39435.69c90e515266013a522e.chunk.js:1
v @ list.e4f5ea56426052f807e6.chunk.js:2
node_modules.jellyfin-apiclient.bundle.js?c63110386127b8fcd20f:2 Request failed to http://xxx.com:5896/Users/c2a7b70039004695ad6f49d844506e6d/Items/f1d467fb393671814513d6162625415e [object Response]
node_modules.jellyfin-apiclient.bundle.js?c63110386127b8fcd20f:2 Reporting request failure
web/#/list.html?pare…2b6afff865d678a43:1 Uncaught (in promise) 

### Please attach any screenshots here

![image](https://github.com/jellyfin/jellyfin/assets/38938115/d0208d68-8b2f-4b3d-95e8-8e3d5a3e5376)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dkadavarath** [comment]
This is a must have feature for trickplay to be effective. Having all this amount of data in metadata is a bit too much especially since the trickplay files are only accessed when the media is already playing. Would have loved the subtitle extraction feature to also do this, but I digress.

**Comment by kinkykusco** [comment]
hey @wangweiweiwei - I have a user who has this exact issue.  Were you able to figure out a solution?

**Comment by wangweiweiwei** [comment]
> hey @wangweiweiwei - I have a user who has this exact issue. Were you able to figure out a solution?
No solution, looks like the app is rather rubbish, bad compatibility and support, I've given up using it.
