### ISSUE TITLE
Sort artist' albums alphabetically or by release year

### ISSUE THREAD

**Issue by SegiH** [jellyfin/jellyfin#1183]
When you got to the artist tab in a music library and select an artist, you're presented with all of that artists' album. 

Currently, the list of albums seem to be displayed in random order if there are more than 2 albums for that particular artist with no obvious method by which the albums are sorted.

Please default to alphabetically sorting order and an option to specify sorting by album name or by release year.

**Comment by chuckn246** [comment]
+1

Just came here to ask for this. There doesn't seem to be any order to which the albums are displayed.

I would at the very least like to be able to list them by year.

**Comment by ezersky** [comment]
+1
I need sort by year option for artist

**Comment by anthonylavado** [comment]
@ezersky If you get a chance, make sure to vote on Fider! We have GitHub sign in, so it’s fast and easy to do so.
