### ISSUE TITLE
[Issue]: New watch history (for Movies only) is lost daily 10.9.2

### ISSUE THREAD

**Issue by fromage9747** [jellyfin/jellyfin#11843]
### Please describe your bug

Watch history for newly started movies is lost daily. Series and anything else keeps the watch history. 

Other issues, search is extremely slow since upgrading to 10.9. Switching users keeps the previous user's home page visible and does not refresh the page. The audio playlist issue is back as well where they don't show up when using the Audio Playlist API

Dashboard refresh on switch user isn't a biggie, but watch history being lost and the incredibly slow search are making me pull my hair out. 

### Reproduction Steps

Upgrade to 10.9 and watch the problems gush in. 

I had assumed that this issue was caused by nfo files being modified.  I went and disabled what I could in the scheduled tasks for Jellyfin(shouldn't need to seen as it all worked prior to upgrading) but the issue persists.

I thought it then might be merged versions plugin, but even that is not showing anything in the logs relevant to the example movie that is losing its watch history.  I would also expect that watch history is not stored in the nfo file for the movie but rather in the Jellyfin database. 

### Jellyfin Version

10.9.0

### Environment

```markdown
- OS: Ubuntu Server 22
- Linux Kernel: 6
- Virtualization: Jellyfin running on Docker
- Clients: Windows, Android
- Browser: Chrome
- FFmpeg Version: latest
- Playback Method: Direct / Transcode
- Hardware Acceleration: yes
- GPU Model: Quadro P400
- Plugins: Merge Version and subbuzz
- Reverse Proxy: yes but this is not an issue
- Base URL: http://localhost:8096
- Networking: Docker, direct to network and then nginx reverse proxy for external
- Storage: NVME
```

### Jellyfin logs

```shell
perhaps this is relevant?


MediaBrowser.XbmcMetadata.Savers.MovieNfoSaver: Error reading existing nfo
System.Xml.XmlException: Data at the root level is invalid. Line 255, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at MediaBrowser.XbmcMetadata.Savers.BaseNfoSaver.AddCustomTags(String path, IReadOnlyCollection`1 xmlTagsUsed, XmlWriter writer, ILogger`1 logger)
   at MediaBrowser.XbmcMetadata.Savers.BaseNfoSaver.Save(BaseItem item, Stream stream, String xmlPath)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shadowghost** [comment]
Please do not report multiple issues in one issue.
Regardless, the playlists changes are intentional. By default any user created playlist is now user-only - it is not shared between users. Any playlist sourced from the local file system is read-only for every used.

**Comment by fromage9747** [comment]
@Shadowghost Playlists that I have created under MY user account are not visible to ME under MY account when logged in with MY user account that I logged into when using the Audio API playlist.  This was the same issue that occurred a few months ago. If I navigate to Playlist under the playlist tab, all the playlists are visible, but this is because it uses a different API endpoint. As it's just getting ALL playlists instead of ones specific to Audio/music.  Anyway, this is not the biggest issue for me.  Losing my watch status daily and extremely slow search (as I have to search for the movie I was watching in order to play it again) is grinding my gears.

**Comment by wyattoday** [comment]
> Dashboard refresh on switch user isn't a biggie, but watch history being lost

I think this in particular is related to this:

https://github.com/jellyfin/jellyfin/issues/12004

There seems to be a bug in the database (or database handling) for new items.

**Comment by fromage9747** [comment]
@wyattoday Unfortunately this issue is still occurring.  Movies are being removed from Continue watching.  They at least keep the resume status, but it's really annoying to have to go and search for them again with the search being INCREDIBLY slow.

**Comment by fromage9747** [comment]
> Does the server restart daily?
> 
> https://github.com/jellyfin/jellyfin/issues/12361

Correct, I restart daily but this particular problem is solved for me. There is a setting that is supposed to save user watch history to an nfo file. This had been enabled years ago on my system but it never did anything. Once 10.9.x arrived, it started "working" and created this problem. Insanely slow search still exists though! The new APIs that have been added are much slower that the previous APIs
