### ISSUE TITLE
Debug scan library process

### ISSUE THREAD

**Issue by platinum55** [jellyfin/jellyfin#1184]
**Is your feature request related to a problem? Please describe.**
Some movies in my library aren't detected and I dont know why. Even turning on debug logging didn't give me a clue, because there is no relevant logging output like "Starting scan process... Entering directory xy"

**Describe the solution you'd like**
Debug any step the scan process makes if requested by debug logging. Like "Starting library scan for <libname>" and "Entering directory x" or "Spawning ffprobe for file y".

**Comment by JustAMan** [comment]
Related: #1130 
There's a way to enable logs in that issue, you can try it to enable debug logging to investigate your issue.

**Comment by Aokromes** [comment]
maybe sort of related to this, i got scan media library failed, but when i click info the width is to small to read everything:
https://i.imgur.com/N1HwwMW.png
