### ISSUE TITLE
FFMPEG is sometimes not found on Windows

### ISSUE THREAD

**Issue by LogicalPhallacy** [jellyfin/jellyfin#1185]
**Describe the bug**
On the Jellyfin 10.3-RC jellyfin seems unable to find ffmpeg (shipped with it) without manual intervention

**To Reproduce**
1. Install Jellyfin on windows
2. Try and transcode something

**Expected behavior**
Jellyfin should search in the path, in its own directory, and in any common install locations for ffmpeg (that last one isn't really a thing on windows)

**System (please complete the following information):**
 - OS: Windows
 - Jellyfin Version: 10.3.0-rc1

**Comment by ploughpuff** [comment]
What do you mean by "shipped with it" please?

The search order is xml config file, command line switch and finally $PATH.

Out of interest, where is the required binary located?

**Comment by LogicalPhallacy** [comment]
We ship the windows builds of Jellyfin with a zeranoe ffmpeg build in the
jellyfin directory. The new search order prevents that included binary from
being detected which causes problems for windows installs. I am working on
a PR to append the jellyfin install directory where we keep that binary by
default on windows to the PATH variable from within the context of the
Jellyfin process which should resolve the issue in a nonimpactful way that
is compliant with how Windows and *Nix operate.

**Comment by Bond-009** [comment]
IMO the proper solution is just passing the exe name and let windows figure out if it’s in PATH or the current dir.

**Comment by ploughpuff** [comment]
> IMO the proper solution is just passing the exe name and let windows figure out if it’s in PATH or the current dir.

Well, the current approach was taken to allow the full path to the ffmpeg binary to be traced in the log file and appear on the transcode UI page.

**Comment by daves00** [comment]
On a Windows platform search order should always start with it's own directory. This was specified by M$ quite some while ago.

**Comment by joshuaboniface** [comment]
Should be fixed in 10.3.0 release.
