### ISSUE TITLE
Playback Error Unable to find a valid media source to play

### ISSUE THREAD

**Issue by sharicov** [jellyfin/jellyfin#11861]
### Please describe your bug

Seing library, not able to play.
Getting Playback Error Unable to find a valid media source to play error.
Running jellyfin in docker (version 10,9.3)
Removed and re added library folder
Still not working (worked fine before)
Music folder binded from host machine.
HW: Arm tv box X96 plus with armbian bookworm.

Fixed by completely removing the container, including respective images and creating it from scratch.

### Reproduction Steps

Update docker container and run

### Jellyfin Version

10.9.0

### if other:

10.9.3

### Environment

```markdown
- OS:armbian bookworm
- Linux Kernel:Linux 6.1.92-ophub
- Virtualization:Docker
- Clients:
- Browser:Chrome
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
No error in logs
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gnattu** [comment]
Your old container may have an invalid env var `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT` set. You have to remove this during upgrade

**Comment by gnattu** [comment]
It is: https://jellyfin.org/posts/jellyfin-release-10.9.0

**Comment by sharicov** [comment]
This is not the issue I experienced, I had see the library but couldn't play, after removing and re-adding library it appeard as an icon, but again, couldn't play.

**Comment by gnattu** [comment]
> This is not the issue I experienced, I had see the library but couldn't play, after removing and re-adding library it appeard as an icon, but again, couldn't play.

It is another thing that will cause. Most of users won't even get home page loading, but some of them like you can get into the library but still cannot play.

**Comment by JoseACT** [comment]
I had this issue, can you disable all the metadata fetching stuff ?  (it worked for me), now i'm gonna test it out 1 by 1 to see witch one is the one preventing the files from loading.

**Comment by StorminMormin1** [comment]
@DerLeole I just found this issue with one show I've added and can confirm it is the same thing. I can't play the media due to the error above, but can play it via a Playlist... huh

**Comment by nice3e3** [comment]
I can confirm the same error without ever setting that environment variable, and re-identifying fixed the issue (used show ID for the search), and before doing that the playlist trick also worked, pretty weird and confusing

**Comment by ddalben** [comment]
Same issue here.  I have found that refreshing all metedata for the affected show to fix the problem.  But I'm not sure how many shows are impacted in my library nor if there is a way to bulk refresh all metadata for all impacted shows in one go.

**Comment by WzorOn** [comment]
Some videos/serials get this error "Playback Error Unable to find a valid media source to play.".
However, if you add a video/serial to the playlist, it plays correctly. Updating metadata does not help.
