### ISSUE TITLE
[Issue]: Library disabled cannot be reenabled just spins quick and vanishes. (10.9.2 and 10.9.3)

### ISSUE THREAD

**Issue by gummykage** [jellyfin/jellyfin#11875]
### Please describe your bug

If you disable a library, you can't re-enable it. Work around is to re-create it, but when there is 1000+ movies it takes a very long time.

### Reproduction Steps

1.) Tested this on Win10 latest updates, and Docker -latest.
2.) Disable a library.
3.) Enable a library - nothing happens.
4.) Cannot re-enable library.
5.) Works around recreate library.

### Jellyfin Version

10.9.0

### if other:

10.9.3

### Environment

```markdown
- OS:Qnap QTS Latest
- Linux Kernel:
- Virtualization:Docker
- Clients:Jellyfin Media Player,
- Browser:Chrome
- FFmpeg Version:Bundled
- Playback Method:
- Hardware Acceleration:VAAPI
- GPU Model:Qnap
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
No error in logs.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nielsvanvelzen** [comment]
Can confirm, the server returns a 404 when you try to enable it again. My best guess is that the update endpoint doesn't ignore the disabled field.

**Comment by nielsvanvelzen** [comment]
Considering I tried to confirm the issue, I had to find a way to fix it for myself too. This is what I did:

1. Stop the Jellyfin server
2. Open the Jellyfin data folder
3. Open the `root` folder
4. Open the `default` folder
5. Open the folder for the library you disabled
6. Open the `options.xml` xml
7. Change `<Enabled>false</Enabled>` to `<Enabled>true</Enabled>`
8. Start the Jellyfin server

**Comment by gummykage** [comment]
Appreciate it. I actually disabled like 30 libraries to try and pinpoint what's causing safari and jellyfin ios mobile apps to freeze constantly when scrolling through the libraries. It's like it freezes, loads an images moves about half a library block then freezes again. A brand new install doesn't have this issue, but then again I haven't added 30 libraries. I wonder if there's a problem with how many you can add now. Will report this bug once I think I've found the exact cause. Thanx again for the help! @nielsvanvelzen.
