### ISSUE TITLE
[Issue]: Music Artist Didn't Split by Semicolon

### ISSUE THREAD

**Issue by hjkcai** [jellyfin/jellyfin#11871]
### Please describe your bug

I have a semicolon-separated artist "Adam Lambert;Nile Rodgers;Sam Sparro" in my ID3 metadata. However Jellyfin thinks there is only one artist called "Adam Lambert;Nile Rodgers;Sam Sparro". There should be 3 artists.

<img width="577" alt="image" src="https://github.com/jellyfin/jellyfin/assets/731326/6beb0573-6144-414c-96cb-ae02bccd567c">

The more interesting thing is that if I click "Edit Metadata" on the web client, don't modify anything and click "Save Changes", the artist are correct now.

Here is the screen record:

https://github.com/jellyfin/jellyfin/assets/731326/e44e326e-c8ed-4cdb-be2c-b2b4edac3f8b

### Reproduction Steps

As above

### Jellyfin Version

10.9.0

### if other:

10.9.3

### Environment

```markdown
- OS: macOS 14.3.1
- Clients: Browser
- Browser: Chrome 122
- FFmpeg Version: 6.0.1
```

### Jellyfin logs

```shell
[2024-05-29 10:20:21.411 +08:00] [INF] [31] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/Applications/Jellyfin.app/Contents/MacOS/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/mnt/media/MusicDLs/Adam Lambert;Nile Rodgers;Sam Sparro - Shady.mp3\" -threads 0 -v warning -print_format json -show_streams -show_format"
```

### FFmpeg logs

```shell
{
    "streams": [
        {
            "index": 0,
            "codec_name": "mp3",
            "codec_long_name": "MP3 (MPEG audio layer 3)",
            "codec_type": "audio",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "sample_fmt": "fltp",
            "sample_rate": "44100",
            "channels": 2,
            "channel_layout": "stereo",
            "bits_per_sample": 0,
            "initial_padding": 0,
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "time_base": "1/14112000",
            "start_pts": 353600,
            "start_time": "0.025057",
            "duration_ts": 2525552640,
            "duration": "178.964898",
            "bit_rate": "261193",
            "disposition": {
                "default": 0,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0,
                "captions": 0,
                "descriptions": 0,
                "metadata": 0,
                "dependent": 0,
                "still_image": 0
            },
            "tags": {
                "encoder": "Lavc60.31"
            },
            "side_data_list": [
                {
                    "side_data_type": "Replay Gain"
                }
            ]
        },
        {
            "index": 1,
            "codec_name": "mjpeg",
            "codec_long_name": "Motion JPEG",
            "profile": "Baseline",
            "codec_type": "video",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "width": 300,
            "height": 300,
            "coded_width": 300,
            "coded_height": 300,
            "closed_captions": 0,
            "film_grain": 0,
            "has_b_frames": 0,
            "sample_aspect_ratio": "1:1",
            "display_aspect_ratio": "1:1",
            "pix_fmt": "yuvj444p",
            "level": -99,
            "color_range": "pc",
            "color_space": "bt470bg",
            "chroma_location": "center",
            "refs": 1,
            "r_frame_rate": "90000/1",
            "avg_frame_rate": "0/0",
            "time_base": "1/90000",
            "start_pts": 2255,
            "start_time": "0.025056",
            "duration_ts": 16106841,
            "duration": "178.964900",
            "bits_per_raw_sample": "8",
            "disposition": {
                "default": 0,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 1,
                "timed_thumbnails": 0,
                "captions": 0,
                "descriptions": 0,
                "metadata": 0,
                "dependent": 0,
                "still_image": 0
            },
            "tags": {
                "title": "0",
                "comment": "Cover (front)"
            }
        }
    ],
    "format": {
        "filename": "/mnt/media/MusicDLs/Adam Lambert;Nile Rodgers;Sam Sparro - Shady.mp3",
        "nb_streams": 2,
        "nb_programs": 0,
        "format_name": "mp3",
        "format_long_name": "MP2/3 (MPEG audio layer 2/3)",
        "start_time": "0.025056",
        "duration": "178.964898",
        "size": "5899088",
        "bit_rate": "263698",
        "probe_score": 51,
        "tags": {
            "title": "Shady",
            "artist": "Adam Lambert;Nile Rodgers;Sam Sparro",
            "album": "Trespassing (Explicit)",
            "TDOR": "2012",
            "encoder": "Lavf60.16.100",
            "REPLAYGAIN_TRACK_GAIN": "-6.51 dB",
            "REPLAYGAIN_TRACK_PEAK": "0.904022",
            "lyrics-eng": "[ti:Shady]\r\n[ar:Adam Lambert]\r\n[al:Trespassing]\r\n[by:]\r\n[offset:0]\r\n[00:05.53]Baby  I'm on the hunt\r\n[00:07.03]\r\n[00:07.78]Baby  I got my target on you\r\n[00:09.72]Trouble  that's what I want\r\n[00:10.97]\r\n[00:12.53]And I'm gonna do just what I have to\r\n[00:15.03]Get your a** down to the front\r\n[00:17.28]Go on and roll it out  I dare you\r\n[00:19.28]\r\n[00:19.97]Sorry I'm kinda drunk\r\n[00:21.28]\r\n[00:22.10]But did you just say your game was brand new \r\n[00:24.34]\r\n[00:25.22]No I ain't broken but I \r\n[00:26.04]\r\n[00:27.22]I need a fix\r\n[00:28.16]\r\n[00:29.60]That satisfaction when I \r\n[00:30.91]\r\n[00:31.91]I get my kicks\r\n[00:32.85]\r\n[00:33.85]I'm up all night\r\n[00:35.04]\r\n[00:36.54]I'm out of sight\r\n[00:37.79]\r\n[00:38.66]Don't turn on the light\r\n[00:39.85]\r\n[00:41.60]Cause I'm feeling so shady lately\r\n[00:43.04]\r\n[00:44.54]Come on and take me underground\r\n[00:46.02]\r\n[00:47.33]Deep under the street\r\n[00:49.33]Come on and take me  take me down\r\n[00:51.02]\r\n[00:52.21]The freaks like us can meet\r\n[00:53.26]\r\n[00:54.08]Turn it up turn it up turn it up turn it way up\r\n[00:57.08]Don't stop the beat\r\n[00:57.95]\r\n[00:58.83]Come on and turn me  turn me on\r\n[01:01.33]\r\n[01:02.13]Cause I'm feeling so shady lately\r\n[01:03.64]\r\n[01:09.02]Gonna go and get me a shot\r\n[01:11.39]Gonna knock it back forget all my blues\r\n[01:12.95]\r\n[01:13.88]Yeah that really hits the spot\r\n[01:15.14]\r\n[01:16.21]I'm feeling pretty fierce in my damn sin shoes\r\n[01:18.14]\r\n[01:19.02]No I ain't broken but I \r\n[01:20.39]\r\n[01:21.14]I need a fix\r\n[01:22.26]\r\n[01:23.57]That satisfaction when I \r\n[01:25.14]\r\n[01:25.95]I get my kicks\r\n[01:27.08]\r\n[01:27.77]I'm up all night\r\n[01:28.82]\r\n[01:30.58]I'm out of sight\r\n[01:31.52]\r\n[01:32.64]Don't turn on the light\r\n[01:33.83]\r\n[01:35.58]Cause I'm feeling so shady lately\r\n[01:37.01]\r\n[01:38.51]Come on and take me underground\r\n[01:40.52]\r\n[01:41.51]Deep under the street\r\n[01:42.52]\r\n[01:43.26]Come on and take me  take me down\r\n[01:45.51]\r\n[01:46.20]The freaks like us can meet\r\n[01:47.45]\r\n[01:48.07]Turn it up turn it up turn it up turn it way up\r\n[01:51.01]\r\n[01:51.70]Don't stop the beat\r\n[01:52.88]Come on and turn me  turn me on\r\n[01:55.20]\r\n[01:56.08]Cause I'm feeling so shady lately\r\n[01:57.58]\r\n[02:01.19]I throw more shade than a cloudy day\r\n[02:02.04]\r\n[02:05.23]The brakes don't work I'm just a runaway train\r\n[02:07.01]\r\n[02:09.83]Somebody come and help me out\r\n[02:11.38]\r\n[02:12.13]All I wanna be is free\r\n[02:13.45]\r\n[02:14.58]I was trying to get down now I can't out\r\n[02:18.07]I'm shady lately\r\n[02:19.31]Come on and take me underground\r\n[02:21.00]\r\n[02:22.44]Deep under the street\r\n[02:23.44]\r\n[02:24.07]Come on and take me  take me down\r\n[02:26.88]Freaks like us can meet\r\n[02:28.00]\r\n[02:28.88]Turn it up turn it up turn it up turn it way up\r\n[02:31.31]\r\n[02:32.13]Don't stop the beat\r\n[02:33.63]Come on and turn me  turn me out\r\n[02:35.88]\r\n[02:36.81]Cause I'm feeling so shady lately\r\n[02:38.92]\r\n[02:39.42]Shady lately  that's how I play\r\n[02:41.30]\r\n[02:43.62]They say maybe it's just a phase\r\n[02:46.99]\r\n[02:48.74]Shady lately  runaway train\r\n[02:51.68]\r\n[02:53.55]Blame the game  quit blaming the gays\r\n[02:56.36]Shady lately"
        }
    }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JeckDev** [comment]
The same thing appears to be happening with genre tags on FLAC files in 10.9.3. Opening up an album nfo file shows the following:
```
  <genre>Alternative Rock; Ambient; Celtic Rock; Dream Pop; Electronic; Folk Rock; Grunge; Indie Pop; Indie Rock; Jangle Pop; Jazz; New Wave; Pop Music; Pop Rock; Post-Punk; Rock; Rock Music</genre>
```
Which means that rather than splitting each track's tags out into new genres around the semicolon, this just treats them as a single genre.
(I could open another issue if required, but this seems to be the same issue just applied to the genre tag instead of the artist tag)

**Comment by Nerokor** [comment]
> The same thing appears to be happening with genre tags on FLAC files in 10.9.3. Opening up an album nfo file shows the following:
> 
> ```
>   <genre>Alternative Rock; Ambient; Celtic Rock; Dream Pop; Electronic; Folk Rock; Grunge; Indie Pop; Indie Rock; Jangle Pop; Jazz; New Wave; Pop Music; Pop Rock; Post-Punk; Rock; Rock Music</genre>
> ```
> 
> Which means that rather than splitting each track's tags out into new genres around the semicolon, this just treats them as a single genre. (I could open another issue if required, but this seems to be the same issue just applied to the genre tag instead of the artist tag)

I'm experiencing a similar issue with genre tags as well, but mine are separated by commas ( , ). This setup breaks Instant Mix for me, as some albums have unique groupings of genres. 

When I try to use Instant Mix, it can end up only playing one album or maybe one or two albums from the same artist depending on if they have overlapping genere groupings. I assume this is because Instant Mix relies on pulling from genres tags, but since they are uniquely grouped, there's no common thread to provide a diverse mix.

**Comment by HerrHellmus** [comment]
I am experiencing the same issues, both with artists and genres

**Comment by felix920506** [comment]
Duplicate #10730

**Comment by RustyLoaf** [comment]
@felix920506 How is a bug specific to FLAC file metadata tags not being delimited correctly in 10.9.x the same issue as someone wanting configurable delimiters?

**Comment by chierinyan** [comment]
@felix920506 Sorry for the confusion caused, but we are not trying to use another split delimeter here. **Semicolon** is not working in 10.9.x and I believe it is the delimeter suggested.

**Comment by felix920506** [comment]
The preferred way to do multiple artists in formats that use VorbisComment (.ogg, .flac, .opus etc.) is to have multiple "artist" tags.

This is a #10730 duplicate because these are all issues with how you split an artist string into multiple artists. 

If we treat semicolons (or any other symbol) as delimiters, then other people with artists' names that contain those symbols will start complaining.

**Comment by hjkcai** [comment]
@felix920506 However MP3 files seems cannot have multiple "artist" tags. It is common to store all artists in one tag and separate by semicolon.

**Comment by RustyLoaf** [comment]
> The preferred way to do multiple artists in formats that use VorbisComment (.ogg, .flac, .opus etc.) is to have multiple "artist" tags.
> 
> This is a #10730 duplicate because these are all issues with how you split an artist string into multiple artists.
> 
> If we treat semicolons (or any other symbol) as delimiters, then other people with artists' names that contain those symbols will start complaining.

Jellyfin has treated semicolons as delimiters for years at this point. Are you telling me with 10.9.x this was an intended change? Can you point to a PR where this change was implemented? Additionally, if this is the intended behavior, then why does editing the metadata for a track with semicolons in it and then saving it result in the artists being split using the semicolon as a delimiter? Considering that functionality is still present in the Jellyfin metadata editor, I don't think this change was intended as you say, but if there's a PR I'd be glad to see the discussion on it.

Additionally, ID3 tags do not have a mechanism for allowing multiple artist tags in a file, as that breaks the spec. Are you expecting users to tag their MP3 files one way and their FLAC files another way? That feels like it'd be incredibly inconsistent for a user organizing their library, and still leave users with the same issue you mention about an artist name featuring a delimiter character in MP3 files. ID3 tags, mind you, still scrape correctly with semicolons, as noted in this thread.

**Comment by felix920506** [comment]
> However MP3 files seems cannot have multiple "artist" tags. It is common to store all artists in one tag and separate by semicolon.

The correct way to do it in formats that use ID3 (.mp3, .m4a etc.) is to separate artists with a null byte, rather than semicolons. 

It is only separating by semicolons because taglib cannot read your file and some weird behavior with ffmpeg. We fallback to ffmpeg if taglib cannot read the file.

**Comment by felix920506** [comment]
This behavior will change again in 10.10 because we are moving to another library, so don't expect too much time be spent on this for now.

**Comment by RustyLoaf** [comment]
> This behavior will change again in 10.10 because we are moving to another library, so don't expect too much time be spent on this for now.

What behavior should we expect in 10.10? 👀

**Comment by gnattu** [comment]
> Jellyfin has treated semicolons as delimiters for years at this point.

Because Jellyfin was reading from ffmpeg for years and we are now only using that as a fallback because ffmpeg does not read all tag fields and does not support id3v2.4 correctly. The current taglib is still very limited and not really maintained and is buggy, so we will be moving to another maintained lib in 10.10.

> Are you telling me with 10.9.x this was an intended change? Can you point to a PR where this change was implemented?

This one: https://github.com/jellyfin/jellyfin/pull/7514

The moment we stopped using ffmpeg as primary tag parser all old separator will stopped to work.

The reason for not using them was also explained: https://github.com/jellyfin/jellyfin/issues/6536#issuecomment-1300691991

> Additionally, if this is the intended behavior, then why does editing the metadata for a track with semicolons in it and then saving it result in the artists being split using the semicolon as a delimiter?

Web editor does not share logic with server scanner. The separation in done in the web which has not changed for years: https://github.com/jellyfin/jellyfin-web/blame/52c8cffc827a2532b161029f3df614e3db1a0fad/src/components/metadataEditor/metadataEditor.js#L80-L98

> Additionally, ID3 tags do not have a mechanism for allowing multiple artist tags in a file, as that breaks the spec.

If you want a spec:

https://id3.org/id3v2.4.0-frames

id3v2.4.0 Native frames, section 4.2 Text information frames defined that:

> All text information frames supports multiple strings, stored as a null separated list, where null is reperesented by the termination code for the charater encoding.

So the use of semicolon also breaks the spec

> What behavior should we expect in 10.10?

The first step is to move to more flexible and maintained atl: https://github.com/jellyfin/jellyfin/pull/11879

How to make it compatible with the numerous non-standard way of supporting multiple artists can only happen after that migration. For your use case, a user-defined separator and artist whitelist is needed.

For 10.9, the best thing we can do is probably provide an option like env var to force the usage of the old ffprobe parser instead to taglib so that it will work like 10.8-. But if we add that please note that any further bugs related to the old parser will probably not be fixed.

**Comment by RustyLoaf** [comment]
> For 10.9, the best thing we can do is probably provide an option like env var to force the usage of the old ffprobe parser instead to taglib so that it will work like 10.8-. But if we add that please note that any further bugs related to the old parser will probably not be fixed.

That actually seems like a great stopgap solution until a something like a user-defined delimiter and artist whitelist can be added. I agree that it'd be ideal for tags to be within spec, but offering an environment variable fallback for people who have been using semicolon delimiters for years precisely because Jellyfin used ffmpeg for tagging would be fantastic. Unless I'm just dense, there doesn't seem to be many metadata editors that handle null bytes for ID3 and multiple artists for Vorbis tags (I'd dig some recommendations though!), let alone ones that can handle a batch operation for converting existing Jellyfin libraries to be within the ID3 and Vorbis spec.

**Comment by chierinyan** [comment]
> All text information frames supports multiple strings, stored as a null separated list, where null is reperesented by the termination code for the charater encoding.

I would like to confirm if I got the specs correctly and if this has been adopted by jellyfin. I just manualy changed the semicolons to null charator in an FLAC file, and they are still not splited correctly and displayed as is. Also `ffprobe` cuts the string from the first null char (and I guess most tools will).

```
>> from mutagen.flac import FLAC
>> audio = FLAC('1-01\ 羽ばたきのバースデイ.flac')
>> print(audio['artist'])

['五島潤(CV:大野柚布子)\x00紅葉谷希美(CV:遠藤ゆりか)\x00金城そら(CV:古賀葵)']
```
```
~ ffprobe 1-01\ 羽ばたきのバースデイ.flac
[omitted]
  Metadata:
    artist          : 五島潤(CV:大野柚布子)
[omitted]
```

For edit metadata on jellyfin web:
```
document.querySelector('#txtAlbumArtist').value
'五島潤(CV:大野柚布子)\x00紅葉谷希美(CV:遠藤ゆりか)\x00金城そら(CV:古賀葵)'
```

**Comment by gnattu** [comment]
> I just manualy changed the semicolons to null charator in an FLAC file, and they are still not splited correctly and displayed as is. 

FLAC does not use ID3 tags but Vorbis tags. The spec defined way for multiple artists is to specify the artist tag multiple times.

> Field names are not required to be unique (occur once) within a comment header. As an example, assume a track was recorded by three well know artists; the following is permissible, and encouraged:
              ARTIST=Dizzy Gillespie 
              ARTIST=Sonny Rollins 
              ARTIST=Sonny Stitt 

See https://xiph.org/vorbis/doc/v-comment.html

> Also ffprobe cuts the string from the first null char (and I guess most tools will).

This is why we say that ffprobe does not support id3v2.4 properly. It should NOT do this.

If you want a tool that correctly handles the spec, use [mp3tag](https://www.mp3tag.de/en/) which handles multiple items in the tag for the spec. Just set id3v2.4 for mp3 and use the default vorbis tag for flac, and use `\\` to separate artists in the GUI, then it will save the tag to the spec-defined way for multiple items.
