### ISSUE TITLE
[Issue]: Wrong content sorting in RU language.

### ISSUE THREAD

**Issue by borozenetsvv** [jellyfin/jellyfin#11880]
### Please describe your bug

Wrong content sorting in RU language. 
![image](https://github.com/jellyfin/jellyfin/assets/12553723/7bee1594-385e-48b2-8aff-2fb3cb2742b8)

### Reproduction Steps

Simply add files.

### Jellyfin Version

10.9.0

### Environment

```markdown
- OS: Ubuntu 22.04
- Linux Kernel: 6.5.0-27
- Virtualization:
- Clients: Any
- Browser: Any
- FFmpeg Version: 
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
Not need
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by geriko2000** [comment]
Same issue. I'm also find this problem after commit with Transliterator in unstable 9 version

**Comment by geriko2000** [comment]
Name sort broken after this commit https://github.com/jellyfin/jellyfin/commit/c16135800c53873746321d0c9ea2fc36550511c1

**Comment by melod1n** [comment]
Same issue

**Comment by felix920506** [comment]
Marking confirmed from multiple reports

**Comment by mirlex1986** [comment]
Jellyfin Version
10.9.11

`result = result.Transliterated()`

Same issue. Movies sorts like Transliterated name.

**Comment by gnattu** [comment]
You will be able to disable the Transliterator in 10.10: https://github.com/jellyfin/jellyfin/pull/12378

**Comment by trustin** [comment]
`JELLYFIN_TRANSLITERATOR_ID=Any-Hex` environment variable will make Jellyfin transliterate everything into hexadecimal representation of unicode value, which largely fixes my issue.

**Comment by CHerSun** [comment]
Using `JELLYFIN_TRANSLITERATOR_ID=Any-Hex` content is sorted differently depending on if there's Sort title present or not. Like, setting sorting title to `Квартет И 2018` I expect the movie to be somewhere near other titles, which have no Sort title and start with `К` too, but instead it gets sorted way higher, right after numbers (`К` is in the middle of alphabet):

<img width="1340" height="591" alt="Image" src="https://github.com/user-attachments/assets/60fc5a70-e5ff-42fd-b8e6-eb3b6ec4521b" />

It looks that transliterator is applied differently to title and sort title
