### ISSUE TITLE
[Issue]: Group verisons doesn't function, bad request

### ISSUE THREAD

**Issue by Jake-Moss** [jellyfin/jellyfin#11891]
### Please describe your bug

When attempting to group two versions of a show the UI displays a spinning wheel forever. The shows are not grouped and a refresh removed the spinning wheel. Looking at the response to the POST request, it's always
> "Please supply at least two videos to merge."

### Reproduction Steps

1. Select two shows
2. Click "Group versions" from the top right 3 dots
3. See spinning wheel
4. On refresh the shows are not grouped

### Jellyfin Version

10.9.0

### if other:

10.9.3

### Environment

```markdown
- OS: Ubuntu 22.04
- Linux Kernel: 6.8.4-3-pve
- Virtualization: LXC
- Clients: Browser
- Browser: Firefox 125.0.3
- FFmpeg Version: 6.0.1-Jellyfin
- Playback Method: N/A
- Hardware Acceleration: QSV
- GPU Model: Intel UHD
- Plugins: none
- Reverse Proxy: none
- Base URL: none
- Networking: Host
- Storage: local
```

### Jellyfin logs

```shell
No log information appears for the bad request
```

### FFmpeg logs

```shell
N/A
```

### Please attach any browser or client logs here

![image](https://github.com/jellyfin/jellyfin/assets/49361082/706d82c5-e196-4e38-a6fb-1a1172d87622)
![image](https://github.com/jellyfin/jellyfin/assets/49361082/6b3a9de2-931e-4399-b2b3-917ea146f81a)

```
XHRPOST
http://192.168.1.100:8096/Videos/MergeVersions?Ids=8d8c09c4d747bd7448e09910bcf50325,2c484842f259eee372039eb154a41477
[HTTP/1.1 400 Bad Request 2ms]

	
POST
	http://192.168.1.100:8096/Videos/MergeVersions?Ids=8d8c09c4d747bd7448e09910bcf50325,2c484842f259eee372039eb154a41477
Status
400
Bad Request
VersionHTTP/1.1
Transferred333 B (45 B size)
Referrer Policyno-referrer
DNS ResolutionSystem

    	
    Access-Control-Allow-Origin
    	*
    Content-Encoding
    	gzip
    Content-Type
    	application/json; charset=utf-8
    Date
    	Fri, 31 May 2024 02:59:50 GMT
    Server
    	Kestrel
    Transfer-Encoding
    	chunked
    Vary
    	Accept-Encoding
    X-Response-Time-ms
    	1.5545
    	
    Accept
    	*/*
    Accept-Encoding
    	gzip, deflate
    Accept-Language
    	en-AU,en-US;q=0.7,en;q=0.3
    Authorization
    	MediaBrowser Client="Jellyfin Web", Device="Firefox", DeviceId="TW96aWxsYS81LjAgKFgxMTsgTGludXggeDg2XzY0OyBydjoxMjUuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC8xMjUuMHwxNzE3MDQ1Nzc2Mzcw", Version="10.9.3", Token="0d4045fb98fe496bb8e8a09dd377fa64"
    Connection
    	keep-alive
    Content-Length
    	0
    DNT
    	1
    Host
    	192.168.1.100:8096
    Origin
    	http://192.168.1.100:8096
    User-Agent
    	Mozilla/5.0 (X11; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cvium** [comment]
Only movies can be grouped currently

**Comment by Jake-Moss** [comment]
> Only movies can be grouped currently

I see, thanks

**Comment by mjmeans** [comment]
Grouping shows is mostly working for me. I go to Shows > (show) > (season), then I select the episode that I want to create a group for, then I scroll down to the "More from season" section and select the ... for the first video I want in the group and click 'select' in the context menu, the UI then changes to allow selecting other videos, I check the blue box for the other videos I want in the group, then I look all the way to the top of the page and the blue bar has a ... to click, then select 'group versions'.

While this does group multiple versions of an episode, it doesn't reliably sort the items within the group. For example, I have a series that has an originally aired version that name like '* - Original.mkv' and an enhanced version of the same episode with new CG special effects that I add to the end of the file name '* - Enhanced.mkv'. When browsing through the episodes, though, the order of the versions that appears in the drop down for the episode is seemingly random. The data in the list isn't being sorted by name. Perhaps it is being sorted by file size, or the row-id in the database, or some other metric.

**Comment by leon0399** [comment]
Cc #13755 #6317 #11891
