### ISSUE TITLE
[Issue]: Music libraries containing artists of the same name will appear in all libraries

### ISSUE THREAD

**Issue by texneus** [jellyfin/jellyfin#11890]
### Please describe your bug

When there are multiple music libraries, AND where each library contains the same artist, all albums and songs in are shown in the Album Artist, Artist, and Genre views in each library.  It does not matter which library you are looking at, and the extraneous albums do not appear in any other views (i.e. Albums and Songs).

Example: I have two libraries, one specifically for Jazz artists and another for "Mainstream" artists.  Eva Cassidy is an artist that is difficult to pin to a single library.  Most of her work is loosely defined as Jazz, but she has a few covers of popular songs.  I have accordingly placed some of her albums and songs into both libraries.

The result, shown below, as seen from the "Mainstream" library, then drilling down to "Album Artists" > "Eva Cassidy".  Note not only do four albums appear twice, but one album (Eva by Heart) which isn't even part of the Mainstream library appears too.

### Reproduction Steps

1. Create two folders for libraries.
2. In each folder, add identical folders for the same artists
3. Add albums and tracks to each artist's folder (it does not appear to matter if they are the same album or different)
5. Create two libraries in Jellyfin, with each library pointing to one of the above parent folders
6. Wait for library updates to finish
7. Investigate each library's Album Artist, Artist, and Genre views

### Jellyfin Version

10.9.0

### if other:

10.9.3

### Environment

```markdown
- OS: OpenMediaVault 7
- Linux Kernel: 6.1
- Virtualization: Docker
- Clients: Web client, Finamp
- Browser: Firefox
- FFmpeg Version: (unsure - whatever is included in the official docker image)
- Playback Method: NA
- Hardware Acceleration: NA
- GPU Model: NA
```

### Jellyfin logs

```shell
NA
```

### Please attach any screenshots here

![Eva Cassidy - Album Artist view (Main library)](https://github.com/jellyfin/jellyfin/assets/23441049/b975c3e4-fded-4f8e-9241-a2df5fb6847e)

Eva Cassidy folder structure in Mainstream:
![EC-Main](https://github.com/jellyfin/jellyfin/assets/23441049/fb01ee28-24f3-4999-9634-d35944b7534f)

Eva Cassidy folder structure in Jazz (I've only expanded two albums due to space, but I'm sure you get the idea...):
![EC-Jazz](https://github.com/jellyfin/jellyfin/assets/23441049/438473d2-261d-47f1-b8db-80cb2dffd5c5)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
This is intended behavior. If you would like a library filter for the artist view, please file a feature request at https://features.jellyfin.org
