### ISSUE TITLE
[Issue]: I upgraded to 10.9.3 and now can't open the app at all

### ISSUE THREAD

**Issue by KingCobra2208** [jellyfin/jellyfin#11904]
### Please describe your bug

It was working fine before but after I upgraded to 10.9.3 every time I try to open the app through an app on my phone or through a web ui it acts as if the server is completely offline. I've tried rebooting my entire server, CasaOS (which is what it's running on), and even just the Jellyfin app on CasaOS.
I'm not entirely sure that the update is what casued the problem but I'm out of ideas

### Reproduction Steps

1. I updated Jellyfin using the Check then Update in CasaOS 2. When I try to open the server on my phone or a web browser it says the server is offline

### Jellyfin Version

10.9.0

### if other:

10.9.3

### Environment

```markdown
- OS: Debian 12.2.0
- Linux Kernel:
- Virtualization: CasaOS
- Clients: Web Browser and iPhone app
- Browser: Brave
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
jellyfin  |    at Jellyfin.Server.Migrations.MigrationRunner.RunPreStartup(ServerApplicationPaths appPaths, ILoggerFactory loggerFactory)
jellyfin  |    at Jellyfin.Server.Program.StartApp(StartupOptions options)
jellyfin  |    at Jellyfin.Server.Program.
(String[] args)
jellyfin  | Unhandled exception. System.InvalidOperationException: There is an error in XML document (0, 0).
jellyfin  |  ---> System.Xml.XmlException: Root element is missing.
jellyfin  |    at System.Xml.XmlTextReaderImpl.Throw(Exception e)
jellyfin  |    at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo(String res)
jellyfin  |    at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
jellyfin  |    at System.Xml.XmlReader.MoveToContent()
jellyfin  |    at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderMigrationOptions.Read4_MigrationOptions()
jellyfin  |    at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
jellyfin  |    at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
jellyfin  |    --- End of inner exception stack trace ---
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gummykage** [comment]
I had an issue with the network.xml file located at config/ for your server data file got corrupted and had to be deleted or manually set after the migration from 10.8.13 -> 10.9.3. This solved it for me. Remember to delete the ios app to flush the old token and contents. And delete the cache/cookies from your browser before trying again.
