### ISSUE TITLE
[Issue]: The sound volume of all Jellyfin clients is lower than any other player

### ISSUE THREAD

**Issue by dadastory** [jellyfin/jellyfin#11907]
### Please describe your bug

The sound volume of all Jellyfin clients is lower than any other player, such as Potplayer, by approximately 50%, and the voice volume is at least 80% lower.
My jellyfin version is 10.9.3 working on Synology DSM923+
I don't know what caused it, but now the sound played by the player is very low, making it difficult to hear voices clearly. The background sound even overpowers the voices, and there is no way to modify or adjust this sound in any other place.
I work on a Synology NAS server, and when playing movies or TV shows through the web interface or Jellyfin, the sound is very low, much lower than what Potplayer plays. This happens whether I play the media directly or transcode it. Why hasn't anyone else reported this issue?

### Reproduction Steps

I work on a Synology NAS server, and when playing movies or TV shows through the web interface or Jellyfin, the sound is very low, much lower than what Potplayer plays. This happens whether I play the media directly or transcode it. 

### Jellyfin Version

10.9.0

### if other:

10.9.3

### Environment

```markdown
- OS:Linux 4.4.302+
- Linux Kernel:Linux 4.4.302+
- Virtualization:none
- Clients:jellyfin media player
- Browser:chrome
- FFmpeg Version:default
- Playback Method:Direct Play, Remux, Direct Stream, Transcode
- Hardware Acceleration:NVENC
- GPU Model:T40
- Plugins:default
- Reverse Proxy:none
- Base URL:none
- Networking:host
- Storage:local
```

### Jellyfin logs

```shell
none
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gummykage** [comment]
I had this exact problem before. If you are playing off a client on windows, try downgrading or checking the sound driver. Go to your profile client settings and look for Audio adjustments. Turn off Normalization see if that helps. This was mostly happening on any movie with DTS audio. You need it to downmix it to stereo if your device doesn't support the other channels. The bug you'll get if the channels are not properly mixed is the talking is gone, with just some distant echo because it's playing a background channel only.

**Comment by dadastory** [comment]
> I had this exact problem before. If you are playing off a client on windows, try downgrading or checking the sound driver. Go to your profile client settings and look for Audio adjustments. Turn off Normalization see if that helps. This was mostly happening on any movie with DTS audio. You need it to downmix it to stereo if your device doesn't support the other channels. The bug you'll get if the channels are not properly mixed is the talking is gone, with just some distant echo because it's playing a background channel only.

I don't think it has anything to do with the driver, because I tried to use the sound output of the monitor and the sound card that comes with the motherboard, but the result is the same, very quiet

**Comment by dadastory** [comment]
> I had this exact problem before. If you are playing off a client on windows, try downgrading or checking the sound driver. Go to your profile client settings and look for Audio adjustments. Turn off Normalization see if that helps. This was mostly happening on any movie with DTS audio. You need it to downmix it to stereo if your device doesn't support the other channels. The bug you'll get if the channels are not properly mixed is the talking is gone, with just some distant echo because it's playing a background channel only.

I finally reset it through the sonic studio program and it seems to be normal, thank you very much
![image](https://github.com/jellyfin/jellyfin/assets/84147842/9514a2c6-8c3c-4690-9184-4b8591d66552)
Seems to be the reason why the monitor's output doesn't support mixing

**Comment by dadastory** [comment]
Seems to be the reason why the monitor's output doesn't support mixing

**Comment by gummykage** [comment]
Yea, downmixing into stereo gave me inconsistent issues on different devices. On my main rig it was the sound cards panel realtek, another was a creative audigy, and then i had issues with a android tv tablet, the work around was to force transcoding. Good luck!

**Comment by dadastory** [comment]
> Yea, downmixing into stereo gave me inconsistent issues on different devices. On my main rig it was the sound cards panel realtek, another was a creative audigy, and then i had issues with a android tv tablet, the work around was to force transcoding. Good luck!

Although the background sound is still very loud, the vocals are a little more normal, and I hope it can be played like potplay

**Comment by afromoo** [comment]
This is still an issue, one "work around" at least on Jellyfin Media Player on windows was to give `exclusive` control in the client settings, but this does stop all other application from interacting with the sound card.

**Comment by 403cg** [comment]
> This is still an issue, one "work around" at least on Jellyfin Media Player on windows was to give `exclusive` control in the client settings, but this does stop all other application from interacting with the sound card.

could you elaborate? on mac the media player seems to be way worse? is there any chance or plugin to make streams play on vlc on mac instead of copy pasting the stream url?

**Comment by Dezmondboi** [comment]
idk if you're still having issues with this but what i did was go to dashboard > playback > transcoding then look for the setting "Boost audio when downmixing" and turn that up a bit and save it works great and the good thing is it will apply to all clients

**Comment by TristanTheBeep** [comment]
> idk if you're still having issues with this but what i did was go to dashboard > playback > transcoding then look for the setting "Boost audio when downmixing" and turn that up a bit and save it works great and the good thing is it will apply to all clients

Yo, thank you. It was already at 2 but bumping it to 3 gave the web player enough umph to be good enough for now. For me it's really important for UX that the browser player be usable and accessible.

**Comment by Dezmondboi** [comment]
> > idk if you're still having issues with this but what i did was go to dashboard > playback > transcoding then look for the setting "Boost audio when downmixing" and turn that up a bit and save it works great and the good thing is it will apply to all clients
> 
> Yo, thank you. It was already at 2 but bumping it to 3 gave the web player enough umph to be good enough for now. For me it's really important for UX that the browser player be usable and accessible.

of course!! it took me like 4-5 months to work out it was the downmix boost i have mine on 3 and its so SOOO much better full volume is almost too loud with some media!! no more complaining from friends YIPPEEE
