### ISSUE TITLE
[Issue]: Infuse Plugin 1.5.0 to be updated in https://repo.jellyfin.org/files/plugin/manifest.json

### ISSUE THREAD

**Issue by Oatavandi** [jellyfin/jellyfin#11902]
### Please describe your bug

Jellyfin Infuse Plugin 1.5.0 has been released for Jellyfish 10.9.x.
But the new plugin is not showing in Plugins Catalog.

Kindly update the below file for the updated plugin to show up.
https://repo.jellyfin.org/files/plugin/manifest.json

### Reproduction Steps

Visit the plugin catalog and click on Infuse Plugin for installation, it still shows 1.4.2.0.
(or)
Navigate to the below link to see the plugin versions available for installation.
https://repo.jellyfin.org/files/plugin/manifest.json

### Jellyfin Version

10.9.0

### Environment

```markdown
- OS:
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
NA
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anthonylavado** [comment]
This was added. I don't remember when, but it wasn't too long after this message.

This is the last version we will have on our repository, as Infuse is transitioning to direct server/library access (and does so on all new installs).

If the plugin is needed in future, they have been advised and provided with information on setting up their own repository feed.
