### ISSUE TITLE
[Issue]: Empty library folders don't update properly

### ISSUE THREAD

**Issue by theolaa** [jellyfin/jellyfin#11913]
### Please describe your bug

The following code skips scanning empty library folders, which means that if a library used to have content but has since been emptied, the media items are never removed from the library since the empty folder is not re-scanned.

https://github.com/jellyfin/jellyfin/blob/c7f87c0d69701480de0f53c0fa5858cbb38de119/MediaBrowser.Controller/Entities/Folder.cs#L343-L348

### Reproduction Steps

1. Add a library folder with content, and scan so that it appears in Jellyfin.
2. Delete/move all the content from in that library folder through external means (i.e. not using the "Delete Media" button)
3. Rescan the library, the deleted media items will not be removed from Jellyfin since the empty folder is skipped

### Jellyfin Version

10.9.3

### Environment

```markdown
- OS: Ubuntu 24.04 LTS
- Linux Kernel: 6.8
- Virtualization: N/A
- Clients: N/A
- Browser: N/A
- FFmpeg Version: N/A
- Playback Method: N/A
- Hardware Acceleration: N/A
- GPU Model: N/A
- Plugins: N/A
- Reverse Proxy: N/A
- Base URL: N/A
- Networking: N/A
- Storage: N/A
```

### Jellyfin logs

```shell
I don't have the log anymore, but the code I quoted above includes the line that it logs.
```

### FFmpeg logs

```shell
N/A
```

### Please attach any browser or client logs here

N/A

### Please attach any screenshots here

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oddstr13** [comment]
This is intentional behavior, to avoid clearing all library metadata when a media mount point is unavailable for whatever reason. (external drive accidentally unplugged, network share down, systemd failed to mount etc.).

If you need it to get cleared up, placing any non-media file there should do the trick.

**Comment by theolaa** [comment]
Ah, that makes sense. I've just been using the "Delete Media" option in the context menu on the items that get left behind and that's been working too.

**Comment by oddstr13** [comment]
@thornbill pointed out to me that deleting the path entry from the library settings should work too
