### ISSUE TITLE
Date added in local nfo gets ignored in 10.9.4

### ISSUE THREAD

**Issue by theguymadmax** [jellyfin/jellyfin#11927]
### Please describe your bug

I did a clean install of 10.9.4 and scanned in my movie library with local nfo files. The date added tag `<dateadded>year-MM-dd</dateadded>` gets ignored and the scraper uses the file created date instead. 
 

### Reproduction Steps

1. In 10.9.4 add a movie library with local nfo, which should include the field date added
2. See that the movie's metadata date added is based on the file creation date

### Jellyfin Version

10.9.0

### if other:

10.9.4

### Environment

```markdown
- OS:Windows 11
- Linux Kernel:N/A
- Virtualization:No
- Clients:N/A
- Browser:N/A
- FFmpeg Version:6.0.1-7 
- Playback Method:N/A
- Hardware Acceleration:N/a
- GPU Model:N/A
- Plugins:None added
- Reverse Proxy:No
- Base URL:N/A
- Networking:N/A
- Storage:N/A
```

### Jellyfin logs

```shell
nothing relevant in logs
```

### Please attach any screenshots here

Same movie and same nfo files both on clean installs.

10.9.3
![10 9 3](https://github.com/jellyfin/jellyfin/assets/171496228/139f0965-0746-4109-8848-5a838f3dcc14)

10.9.4
![10 9 4](https://github.com/jellyfin/jellyfin/assets/171496228/a0f391a7-2f75-47ab-8300-5d233bb71913)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shadowghost** [comment]
Don't we have a setting for this you need to enable?

**Comment by theguymadmax** [comment]
There is this option in Dashboard->Libraries->NFO.  "If a metadata value is present, it will always be used before either of these options.", which was the case prior to 10.9.4. This setting was kept at default for both 10.9.3 & 10.9.4 installs. 


![nfo settings](https://github.com/jellyfin/jellyfin/assets/171496228/1b0f9700-69e2-4245-8067-3abec0559dee)

**Comment by traptegies** [comment]
Not sure if it's related, but I noticed, that all my tv shows popped up at last added after upgrading to 10.9.4 (from 10.9.3, using linuxserver/jellyfin docker image). The dateadded in the NFOs were overridden with the upgrade-date (2024-06-02) - my guess is, they were recreated completely when the library got scanned via the planned task.

**Comment by mikewesten** [comment]
Probably related, I have a surge of new "latest episodes" after the 10.9.4 update. Evidently it used some logic to dump a ton of season's episodes into the specials season. A bit annoying. Not sure if it's a bug or if the files just need to be renamed more strictly and then rescanned.
