### ISSUE TITLE
[Issue]: new versions RPMs are missing from all downloads

### ISSUE THREAD

**Issue by AlexCzar** [jellyfin/jellyfin#11928]
### Please describe your bug

10.8.13 is the last version available in the repository for either RHEL/CentOS or Fedora.

### Reproduction Steps

1. Go to https://repo.jellyfin.org/?path=/server/fedora
1. Click on [Current Stable (v10.9.4) *](https://repo.jellyfin.org/?path=/server/fedora/latest-stable), Click on [AMD64](https://repo.jellyfin.org/?path=/server/fedora/latest-stable/amd64)

**expected**: v10.9.* rpm packages are shown

**actual**: 10.8.13 rpm pacakges are shown

### Jellyfin Version

10.9.0

### Environment

```markdown
*irrelevant*
```

### Jellyfin logs

```shell
*irrelevant*
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
https://jellyfin.org/posts/new-ci-new-repo

> We are dropping non-LTS Ubuntu packages, dropping our own Fedora/CentOS packages in favour of [RPMFusion builds](https://admin.rpmfusion.org/pkgdb/package/free/jellyfin/), and adding [GHCR as a container repository](https://ghcr.io/jellyfin/jellyfin) for our Docker images.

**Comment by kid1412621** [comment]
I'm confused, will there be an official RPM repo or not?

**Comment by nielsvanvelzen** [comment]
No, we will not host our own RPM repository in an official capacity.

**Comment by kid1412621** [comment]
> No, we will not host our own RPM repository in an official capacity.

![image](https://github.com/user-attachments/assets/8009a032-d6e1-41c2-b190-9c8678a9c11c)
so the docker version is recommended for fedora user?

**Comment by nielsvanvelzen** [comment]
Docker, portable linux builds, community maintained RPM. whatever is your preference.
