### ISSUE TITLE
Plugins are broken on 10.3.0-rc1

### ISSUE THREAD

**Issue by joshuaboniface** [jellyfin/jellyfin#1194]
**Describe the bug**
Plugins won't load from subdirectories of the PluginDir. Trying to upgrade plugins doesn't work properly, as the folder contains the version and overwriting fails. Removed plugins leave behind folders.

**Additional context**
Enough problems that describing them individually is futile. The way we were doing plugins in 10.2. was affected by most of these anyways, this fixes them going forward.

**Comment by anthonylavado** [comment]
Also to help close out other issues, plug-ins currently need to be rebuilt for this new version, because they depend on some internal components that have been changed during our work. At the time of the new release, a compatible plug-in will be available to install through the catalog.

**Comment by cesalo** [comment]
Not sure if related to this issue but I just installed 10.3 and tried to update the plugin reports (v1.01->v2) and didn't really do anything. It kept spinning and spinning with no messages in the logs.

**Comment by joshuaboniface** [comment]
@cesalo It's probably bad JS cached, that bug was fixed after RC2. Hard refreah/cache clear should fix it up.
