### ISSUE TITLE
[bug][Issue]: TV-Show seasons are messed up in 10.9.4

### ISSUE THREAD

**Issue by traptegies** [jellyfin/jellyfin#11953]
### Please describe your bug

I noticed that TV Shows are a little messed up.
My file structure can be seen in Screenshot 1. If I now visit the Shows main page in either Web-UI or the Android-App, you can see, Season 7 has too many episodes in it - all of them to be precise (Screenshot 3, "Kaltgestellt" is S01E01), although all episodes can also be found in their correct season.
Screenshot 2 shows the view of S06E11 (correct in Metadata and .nfo). As you can see the series title (Staffel 7, which translates to Season 7) is not the one of season 6 (as stated in the season.nfo). This behaviour can be observed at all episodes.
I also noticed, that there was a (random) season.nfo in the directory of each tv show (not only in the season sub-directories), I deleted them in an attempt to fix the issue, this produced a log entry like the one given below. In the example of Burn Notice it's Season 6, although Season 7 is the overpresent one. In another show it was Season 1, which is also the overpresent Season.
I was able to reproduce the issue with a test-directory containing only one show with all seasons and the correct .nfo-files and a fresh (high privileged) container (docker compose is below).
Let me know if you need more information

### Reproduction Steps

1. Have tv show with multiple seasons in /data/tvshows/Show (2023) [tmdbid-12345] (see Screenshot 1)
2. Upgrade linuxserver Docker from 10.9.3 to 10.9.4
3. Full library rescan planned task or triggered manually
4. Check out Show in Jellyfin Web or Android App

### Jellyfin Version

10.9.0

### if other:

10.9.4

### Environment

```markdown
- OS:Debian 12
- Linux Kernel: 6.1.0-18-amd64
- Virtualization: Docker 26.1.3 (linuxserver image, :latest)
- Clients: Web-UI, Android-App, Chromecast (w/o Google TV)
- Browser: Chrome, Firefox

- Plugins: AudioDB, MusicBrainz, OMDb, Open Subtitles, Playback Reporting, Studio Images, TMDb, TheTVDB, Theme Songs, Webhook

- Networking: Bridge
- Storage: local / Docker volume
```

### Jellyfin logs

```shell
[2024-06-04 11:43:10] [INF] [8] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: Season, Name: Staffel 6, Path: /data/tvshows/Burn Notice (2007) [tmdbid-2919]/Season 6 (2012), Id: 55a6e37f-7184-a694-bd00-a8532c33138e
```

### Please attach any browser or client logs here

Docker compose
`---
version: "3.8"
services:
  jellyfin:
    image: linuxserver/jellyfin:10.9.3
    container_name: jellyfintest
    user: 0:0
    group_add:
      - "105"  # render group
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Berlin
      - DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel
    volumes:
      - /home/traptegies/jellyfin-test/config:/config
      - /home/traptegies/jellyfin-test/cache:/cache
      - /mnt/raiddrives/jellyfin-test/TVShows:/data/tvshows
    network_mode: 'bridge'
    ports:
      - 8097:8096
      - 8921:8920
      - 7360:7359/udp
    restart: unless-stopped`

### Please attach any screenshots here

![image](https://github.com/jellyfin/jellyfin/assets/115918211/c33d7fef-3650-40cc-a7fc-5bd8e3dcf396)
![image](https://github.com/jellyfin/jellyfin/assets/115918211/f17b4ca2-a15b-4628-9b20-0b59e03b29a3)
![image](https://github.com/jellyfin/jellyfin/assets/115918211/079ddc85-7740-407b-869e-7b89f19ce98c)
![image](https://github.com/jellyfin/jellyfin/assets/115918211/13569f85-f5b3-4759-9779-41a2dd1f0e0b)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shadowghost** [comment]
Likely fixed by #11920

**Comment by Tirpitz** [comment]
I'm having the same issue since updating to 1.9.4. IMO could be #11920 which was pushed with the version that's causing the issue. 

I have a few shows afflicted, for example Twin Peaks is showing no episodes for any of the 3 seasons, while South Park has put EVERYTHING into "Season 1" and the path ignores the folder "Season 01" (while for Season 2 and forth it is correct).

**Comment by Tirpitz** [comment]
Updated to 1.9.6, after running a "scan media library" the Shows are now fixed. Twin Peaks is showing all three seasons, South Park has everything in the right place and season 1 doesn't contain all seasons episodes, and so on.

**Comment by traptegies** [comment]
> Updated to 1.9.6, after running a "scan media library" the Shows are now fixed. Twin Peaks is showing all three seasons, South Park has everything in the right place and season 1 doesn't contain all seasons episodes, and so on.

Can confirm, looks all good again. Thank you aweseome devs!
