### ISSUE TITLE
[Issue]: Jellyfin delete season folder after library scan

### ISSUE THREAD

**Issue by pafade89** [jellyfin/jellyfin#11988]
### Please describe your bug

After adding my existing series and performing a library scan, Jellyfin deleted all seasons of the series. Since these are anime, I thought I was affected by a current bug #11954. However, that wasn't the problem, as the behavior still occurs even after updating to version 10.9.5. My current solution is to mnt my NAS with read only.

### Reproduction Steps

1. Add One Piece season 14 episode 1
2. rescan library
3. folder gone

### Jellyfin Version

10.9.0

### Environment

```markdown
- OS: Debian
- Linux Kernel: 6.8.4.3
- Virtualization: LXC
- Clients: Android, Web
- Browser: Chrome
- FFmpeg Version: 6.0.1
- Playback Method: Direct Play
- Hardware Acceleration: irrelevant
- GPU Model: Intel 630
- Plugins: None
- Reverse Proxy: nxinx
- Base URL: None
- Networking: Host
- Storage: NFS
```

### Jellyfin logs

```shell
[INF] Deleting item path, Type: "Season", Name: "Staffel 14", Path: "/mnt/pve/Media/Serien/One Piece/Season 14", Id: 2eeadc93-d4dd-d238-2749-30a97324bacf
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gnattu** [comment]
Check your version again, are you running on 10.9.5?

**Comment by pafade89** [comment]
![WhatsApp Bild 2024-06-06 um 12 59 15_6416d448](https://github.com/jellyfin/jellyfin/assets/113902279/f1bd411b-21aa-4418-b5ab-6c50af155c53)

**Comment by Shadowghost** [comment]
I checked all the possible code paths leading to this log message and I can't see how this could have been triggered on 10.9.5 without someone manually calling the DeleteItem API endpoint. E.g. going to the series -> three dot menu -> delete item on the WebUI

**Comment by pafade89** [comment]
Thanks for quick reply.
I have checked everything again and shut down all LXCs that work with the Jellyfin API.

Same behaviour 

```
[2024-06-06 13:17:10.546 +02:00] [INF] Deleting item path, Type: "Season", Name: "Staffel 14", Path: "/mnt/pve/Media/Serien/One Piece/Season 14", Id: 2eeadc93-d4dd-d238-2749-30a97324bacf
[2024-06-06 13:17:11.115 +02:00] [INF] Removing virtual season 14 in series "One Piece"
[2024-06-06 13:17:11.115 +02:00] [INF] Removing item, Type: "Season", Name: "Staffel 14", Path: "", Id: e906a4fe-7f14-068a-60f8-9b4862ddb34a
```

**Comment by Shadowghost** [comment]
Are you by any chance using the tvdb plugin?
https://github.com/jellyfin/jellyfin-plugin-tvdb/pull/153 was merged but not released, fixing a similar bug in there

**Comment by pafade89** [comment]
I have now removed the stable plugin repository and deleted TVDB plugin. Now my series with episodes remain intact/not deleted, and the messages in the log are gone. Thank you very much.

When will this fix be implemented and released in the stable version of Jellyfin?

**Comment by pafade89** [comment]
When I deinstall the tvdbb plugin and restart jellyfin it looks like the following:

![image](https://github.com/jellyfin/jellyfin/assets/113902279/7d8d8618-b3de-4ac6-90e9-f132472dcb45)

If I now restart jellyfin again it looks like this:

![image](https://github.com/jellyfin/jellyfin/assets/113902279/2a1a9876-a9f2-40da-aa37-139212accdde)

Without removing the stable default repository it is not possible to deinstall the tvdb plugin.

Is this normal?

**Comment by Shadowghost** [comment]
Inside `system.xml` in your config folder should be the stanza `<RemoveOldPlugins>` set this to true, restart, uninstall the plugin again and restart again. Any future plugin update will now remove old versions.
You can always remove old versions manually by deleting the respective directories in the `plugins` folder

**Comment by pafade89** [comment]
> Inside `system.xml` in your config folder should be the stanza `<RemoveOldPlugins>` set this to true, restart, uninstall the plugin again and restart again. Any future plugin update will now remove old versions. You can always remove old versions manually by deleting the respective directories in the `plugins` folder

That worked, thank you very much. However, one question remains:

> Im wondering that a metadata plugin can delete files and reinstall completely automatically. Is this wanted?

**Comment by Shadowghost** [comment]
Plugins can do more or less anything the server can, so it is intended behaviour that they can do it but it's up to the plugin to use it properly/at all.

**Comment by pafade89** [comment]
Okay, thank you very much for your time and quick reply. I hope the [update](https://github.com/jellyfin/jellyfin-plugin-tvdb/pull/148) comes as soon as possible to prevent further data loss.
