### ISSUE TITLE
[Issue]: Failure to refresh libraries after update. Readonly database.

### ISSUE THREAD

**Issue by thoja21** [jellyfin/jellyfin#11980]
### Please describe your bug

Since upgrading to 10.9.5 I see the following exception being thrown in the Jellyfin logs when I refresh a library that has had new videos added.

I'm not familiar with the Jellyfin codebase at all and may be jumping ahead but assume this could be related to the readonly database changes made in the PR: https://github.com/jellyfin/jellyfin/pull/11969

### Reproduction Steps

With 10.9.5 server installed:

1. Add additional files (e.g. videos)
2. Request a library refresh
3. Video/music etc is not added to library and a 'readonly database' exception is thrown.

### Jellyfin Version

10.9.0

### Environment

```markdown
- OS: Ubuntu 23.10
- Linux Kernel: GNU/Linux 6.5.0-35-generic x86_64
- Virtualization: Docker
- Clients: N/A
- Browser: N/A
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage: Local SSD
```

### Jellyfin logs

```shell
jellyfin  | [00:07:27] [INF] [1] Main: Startup complete 0:00:43.3183502
jellyfin  | [00:07:28] [INF] [10] Emby.Server.Implementations.ScheduledTasks.TaskManager: Update Plugins Completed after 0 minute(s) and 5 seconds
jellyfin  | [00:07:32] [INF] [16] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 192.168.0.229 request
jellyfin  | [00:07:58] [INF] [23] MediaBrowser.Providers.TV.SeriesMetadataService: Creating Season Season Unknown entry for MyVideo
jellyfin  | [00:08:10] [ERR] [10] MediaBrowser.Providers.Manager.ProviderManager: Error refreshing item
jellyfin  | Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 8: 'attempt to write a readonly database'.
jellyfin  |    at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
jellyfin  |    at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
jellyfin  |    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
jellyfin  |    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
jellyfin  |    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
jellyfin  |    at Emby.Server.Implementations.Data.SqliteItemRepository.UpdatePeople(Guid itemId, List`1 people)
jellyfin  |    at Emby.Server.Implementations.Library.LibraryManager.UpdatePeopleAsync(BaseItem item, List`1 people, CancellationToken cancellationToken)
jellyfin  |    at MediaBrowser.Providers.Manager.MetadataService`2.SaveItemAsync(MetadataResult`1 result, ItemUpdateType reason, CancellationToken cancellationToken)
jellyfin  |    at MediaBrowser.Providers.Manager.MetadataService`2.RefreshMetadata(BaseItem item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken)
jellyfin  |    at MediaBrowser.Controller.Entities.BaseItem.RefreshMetadata(MetadataRefreshOptions options, CancellationToken cancellationToken)
jellyfin  |    at MediaBrowser.Controller.Entities.TV.Series.RefreshAllMetadata(MetadataRefreshOptions refreshOptions, IProgress`1 progress, CancellationToken cancellationToken)
jellyfin  |    at MediaBrowser.Controller.Entities.Folder.RefreshAllMetadataForContainer(IMetadataContainer container, MetadataRefreshOptions refreshOptions, IProgress`1 progress, CancellationToken cancellationToken)
jellyfin  |    at MediaBrowser.Controller.Entities.Folder.RefreshChildMetadata(BaseItem child, MetadataRefreshOptions refreshOptions, Boolean recursive, IProgress`1 progress, CancellationToken cancellationToken)
jellyfin  |    at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass69_0`1.<<RunTasks>b__1>d.MoveNext()
jellyfin  | --- End of stack trace from previous location ---
jellyfin  |    at MediaBrowser.Controller.Entities.Folder.RunTasks[T](Func`3 task, IList`1 children, IProgress`1 progress, CancellationToken cancellationToken)
jellyfin  |    at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, Boolean allowRemoveRoot, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
jellyfin  |    at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, Boolean allowRemoveRoot, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
jellyfin  |    at MediaBrowser.Providers.Manager.ProviderManager.RefreshCollectionFolderChildren(MetadataRefreshOptions options, CollectionFolder collectionFolder, CancellationToken cancellationToken)
jellyfin  |    at MediaBrowser.Providers.Manager.ProviderManager.RefreshItem(BaseItem item, MetadataRefreshOptions options, CancellationToken cancellationToken)
jellyfin  |    at MediaBrowser.Providers.Manager.ProviderManager.StartProcessingRefreshQueue()
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by thoja21** [comment]
Also, to add to this I'm also seeing readonly database exceptions when doing pretty much anything that requires Jellyfin to make updates. E.g. removing favourites:

[log.log](https://github.com/user-attachments/files/15597991/log.log)

**Comment by Eldarock** [comment]
Same here, can't add new shows or movies : readonly database exceptions

**Comment by oddstr13** [comment]
I've been unable to reproduce, but we have been getting multiple reports of this issue from different sources.

**Comment by MylesAU** [comment]
I've generated debug logs from an occurrence of this issue. Logs start from clicking "Scan All Libraries" in the WebUI Dashboard to the error occurring: https://gist.github.com/MylesAU/bed6360a9f2eff451ac176444acf8ec0

**Comment by cptn-x** [comment]
Have also been seeing exactly the same issue. Only with version 10.9.5 (the issue lists v10.9.0 which o assume is a typo).

**Comment by xd003** [comment]
I can confirm facing the very same issue,. hope a hotfix gets released for this once since its kinda critical affecting quite many tasks

**Comment by oddstr13** [comment]
> the issue lists v10.9.0 which i assume is a typo.

issue template default apparently, and the only 10.9 option currently available

**Comment by Vucko130** [comment]
Same here. Windows 11 64-bit. Reverted back to 10.9.4

**Comment by sjorge** [comment]
I can consistently trigger it with a 'scan all media', as long as there is some new content to be detected.

**Comment by gnattu** [comment]
Can any of you try this build to see if it improves anything?

https://github.com/gnattu/jellyfin/releases/tag/v10.9.5-db-next

Disclaimer: backup before you try

**Comment by nirvgorilla** [comment]
I'm currently at 10.9.3. If I wanted to go to 10.9.4 only, what would be the best way? I'm not familiar with installing "backports." Obviously, apt update is showing 10.9.5 only. 
Would the best way be to download the source .zip for 10.9.4, extract it to a folder, and upgrade that way? (I wouldn't even know what to type. Never did it this way before)
This obviously doesn't work because old versions are not in the repositories I have: **apt-get install jellyfin-server=10.9.4+deb12**

**Comment by p37307** [comment]
I had this issue after 10.9.5 restart. 

Can confirm, for me, setting parallel scan to 1 resolved the issue for me, so far, in 10.9.5.  I had bumped it back to 2 in 10.9.4 but had to take it back to 1. Set `Dashboard -> General -> Performance -> Set "Parallel library scan tasks limit" and "Parallel image encoding limit" both to 1`.https://github.com/jellyfin/jellyfin/issues/11957#issuecomment-2149346186

New items have scanned and been added. 
My system: Windows 10, Jellyfin 10.9.5

**Comment by Jordy3D** [comment]
Tried the above limit fix without success, so YMMV on that front.

**Comment by JumpyJim404** [comment]
Change setting to 1 in both "Parallel library scan tasks limit" and "Parallel image encoding limit" and stop and then restart server fixed the media scanning issue for me.  It would instantly fail previously after updating to 10.9.5.

**Comment by DcyMatrix** [comment]
> I had this issue after 10.9.5 restart.
> 
> Can confirm, for me, setting parallel scan to 1 resolved the issue for me, so far, in 10.9.5. I had bumped it back to 2 in 10.9.4 but had to take it back to 1. Set `Dashboard -> General -> Performance -> Set "Parallel library scan tasks limit" and "Parallel image encoding limit" both to 1`.[#11957 (comment)](https://github.com/jellyfin/jellyfin/issues/11957#issuecomment-2149346186)
> 
> New items have scanned and been added. My system: Windows 10, Jellyfin 10.9.5

I can confirm the issue with adding new media can be done by doing this. BUT my server does not seem to update things like what was viewed. Or even acknowledge if I stop watching something (it keeps show my client playing on the dashboard, and time going on watching the movie)

**Comment by gnattu** [comment]
So anyone having this issue and willing to help us to verify if this actually fixed the problem:

https://github.com/gnattu/jellyfin/releases/tag/v10.9.5-db-next

This is a release with PR #11986 meged

Can you try this docker image and test if the issue is gone for you. It should work with default concurrency (0).

Disclaimer: backup before you try

**Comment by p37307** [comment]
> > I had this issue after 10.9.5 restart.
> > Can confirm, for me, setting parallel scan to 1 resolved the issue for me, so far, in 10.9.5. I had bumped it back to 2 in 10.9.4 but had to take it back to 1. Set `Dashboard -> General -> Performance -> Set "Parallel library scan tasks limit" and "Parallel image encoding limit" both to 1`.[#11957 (comment)](https://github.com/jellyfin/jellyfin/issues/11957#issuecomment-2149346186)
> > New items have scanned and been added. My system: Windows 10, Jellyfin 10.9.5
> 
> I can confirm the issue with adding new media can be overcome by doing this. BUT my server does not seem to update things like what was viewed. Or even acknowledge if I stop watching something (it keeps show my client playing on the dashboard, and time going on watching the movie, trying to manually stop the playback on the client in the dashboard is ignored also)

The Nextup and playback session updating issue was resolved, _for me_, when I did a complete stop of Jellyfin and opened it up directly from the shortcut it had created. I had to manually mark what it had missed but then on, is recorded session playback correctly, moved next up items, etc. I then tested it with a computer reboot, even after reboot of the computer with auto startup, reporting od playback worked correctly.

**Comment by boydaihungst** [comment]
Response from dev. 
![image](https://github.com/jellyfin/jellyfin/assets/38396158/a2a58068-84bc-420b-917b-29a4d599485f)

**Comment by xd003** [comment]
The potential fix is already in a PR, they just need more users to test it out - https://github.com/jellyfin/jellyfin/issues/11980#issuecomment-2151892203

For me personally, it seems to be working well

**Comment by jothi-prasath** [comment]
> So anyone having this issue and willing to help us to verify if this actually fixed the problem:
> 
> https://github.com/gnattu/jellyfin/releases/tag/v10.9.5-db-next
> 
> This is a release with PR #11986 meged
> 
> Can you try this docker image and test if the issue is gone for you. It should work with default concurrency (0).
> 
> Disclaimer: backup before you try

i can run this i am using am64 raspberry pi can anyone give arm64 image

**Comment by cptn-x** [comment]
Tested pr #11986 and confirming that it resolved the read-only db error. Also seems to resolve database locking errors (but perhaps too early to confirm this).

**Comment by solidsnake1298** [comment]
Setting max library scan threads to 1 appears to be a workaround.  Still waiting for my scan to finish, but I don't see the database read only messages yet.

**Comment by solidsnake1298** [comment]
> Setting max library scan threads to 1 appears to be a workaround. Still waiting for my scan to finish, but I don't see the database read only messages yet.

The first scan completed without this issue re-appearing.  And another scan also completed without this issue re-appearing.

**Comment by gnattu** [comment]
> I spoke too soon. Click "Scan All Libraries" appears to still trigger the issue.

can you try the docker image?

**Comment by Killerherts** [comment]
Issue is not resolved for me by reducing parallel scans to 1. A roll back to 10.9.3 did get my server running again. PR #11986  looks like it should fix the issue i am on docker so I am unable to test until into an image.

**Comment by gnattu** [comment]
> Issue is not resolved for me by reducing parallel scans to 1. A roll back to 10.9.3 did get my server running again. PR #11986 looks like it should fix the issue i am on docker so I am unable to test until into an image.

https://github.com/jellyfin/jellyfin/issues/11980#issuecomment-2151892203

there is one

**Comment by Killerherts** [comment]
> > Issue is not resolved for me by reducing parallel scans to 1. A roll back to 10.9.3 did get my server running again. PR #11986 looks like it should fix the issue i am on docker so I am unable to test until into an image.
> 
> [#11980 (comment)](https://github.com/jellyfin/jellyfin/issues/11980#issuecomment-2151892203)
> 
> there is one

I'll clarify one hosted on offical repo.

**Comment by solidsnake1298** [comment]
> > I spoke too soon. Click "Scan All Libraries" appears to still trigger the issue.
> 
> can you try the docker image with that pr merged?

I have not been able to trigger this bug with db-bond applied.

**Comment by vortex91** [comment]
10.9.5 readonly database exceptions all over 
reverted back to 10.9.4 no issues

running docker in ubuntu.

**Comment by p37307** [comment]
> Can you try this docker image and test if the issue is gone for you. It should work with default concurrency (0).
Sorry, I would test it but I don't have docker in any of my machines.

**Comment by solidsnake1298** [comment]
Do I need to remove db-bond from docker now that 10.9.6 is out?

**Comment by gnattu** [comment]
Just use 10.9.6 now

**Comment by solbu** [comment]
> Just use 10.9.6 now

Can confirm that 10.9.6 fixed it for me. :-)

Found this thread a few hours ago and saw that the issue was being worked on, so I didn't want to add more noise.
So I waited.

Thank you for an exelent Free Software alternative to Plex and Emby.

**Comment by thoja21** [comment]
Confirmed 10.9.6 has resolved the issue. Thanks for sorting this so quickly.
Closing issue.

**Comment by chantalgo** [comment]
ON [latest](https://registry.hub.docker.com/layers/jellyfin/jellyfin/latest/images/sha256-15579ab64a14f9e3dce043c076df148e9de9631f11c9b3f614f1fbad868db701?context=explore) tag on container manager on NAS synology, showing 10.9.6 on the webui, Library still won't scan

**Comment by solidsnake1298** [comment]
> On [latest](https://registry.hub.docker.com/layers/jellyfin/jellyfin/latest/images/sha256-15579ab64a14f9e3dce043c076df148e9de9631f11c9b3f614f1fbad868db701?context=explore) tag on container manager on NAS synology, showing 10.9.6 on the webui, Library still won't scan
> ![CleanShot_2024-06-06_at_18 30 372x](https://github.com/jellyfin/jellyfin/assets/1203870/5a62dd48-3b3b-496a-a3e1-efc00fb521a0)
> ![CleanShot_2024-06-06_at_18 32 132x](https://github.com/jellyfin/jellyfin/assets/1203870/aa9f9cdf-835f-42be-83db-799bfc9eeb85)

If you have DOTNET_SYSTEM_GLOBALIZATION_INVARIANT enabled, disable it.
