### ISSUE TITLE
Test suite causes problems during dotnet clean

### ISSUE THREAD

**Issue by joshuaboniface** [jellyfin/jellyfin#120]
The testing suite added in #112 seems to cause a lot of problems for me running `dotnet clean`.

The very first run after fetching the updates caused a series of errors, ending:

```
       "/var/home/joshua/Projects/Emby/jellyfin/MediaBrowser.sln" (Clean target) (1) ->
       "/var/home/joshua/Projects/Emby/jellyfin/tests/Jellyfin.Test/Jellyfin.Test.csproj" (Clean target) (11) ->
       "/var/home/joshua/Projects/Emby/jellyfin/MediaBrowser.Server.Mono/EmbyServer.csproj" (Clean target) (14:2) ->
       "/var/home/joshua/Projects/Emby/jellyfin/RSSDP/RSSDP.csproj" (Clean target) (27:2) ->
         /usr/share/dotnet/sdk/2.2.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(208,5): error NETSDK1005: Assets file '/var/home/joshua/Projects/Emby/jellyfin/RSSDP/obj/project.assets.json' doesn't have a target for '.NETStandard,Version=v2.0'. Ensure that restore has run and that you have included 'netstandard2.0' in the TargetFrameworks for your project. [/var/home/joshua/Projects/Emby/jellyfin/RSSDP/RSSDP.csproj]

    0 Warning(s)
    24 Error(s)
```

However running `dotnet publish` succeeded (and quickly) afterwards.

The next run of `dotnet clean` took much longer, several minutes per stage, and ended hanging:

```
    20>Done Building Project "/var/home/joshua/Projects/Emby/jellyfin/Emby.IsoMounting/IsoMounter/IsoMounter.csproj" (C
lean target(s)).                                                                                                       
    19>Done Building Project "/var/home/joshua/Projects/Emby/jellyfin/tests/IsoMounter.Test/IsoMounter.Test.csproj" (Cl
ean target(s)).                                                                                                        
     1>Project "/var/home/joshua/Projects/Emby/jellyfin/MediaBrowser.sln" (1) is building "/var/home/joshua/Projects/Em
by/jellyfin/tests/Jellyfin.Test/Jellyfin.Test.csproj" (21) on node 1 (Clean target(s)).                                
    21>CoreClean:                                                                                                      
         Deleting file "/var/home/joshua/Projects/Emby/jellyfin/tests/Jellyfin.Test/bin/Release/netcoreapp2.1/dashboard
-ui/addplugin.html".                                                                                                   
[snip]
         Deleting file "/var/home/joshua/Projects/Emby/jellyfin/tests/Jellyfin.Test/obj/Release/netcoreapp2.1/Jellyfin.
Test.csproj.CopyComplete".                                                                                             
         Deleting file "/var/home/joshua/Projects/Emby/jellyfin/tests/Jellyfin.Test/obj/Release/netcoreapp2.1/Jellyfin.
Test.dll".                                                                                                             
         Deleting file "/var/home/joshua/Projects/Emby/jellyfin/tests/Jellyfin.Test/obj/Release/netcoreapp2.1/Jellyfin.
Test.pdb".                                                                                                             
```

While hanging, many `dotnet` processes spawned, and ended up consuming 10+GB RAM before:

```
-bash: fork: retry: Resource temporarily unavailable
-bash: fork: retry: Resource temporarily unavailable
-bash: fork: retry: Resource temporarily unavailable
```
```
 ^C                                                                                                                    
Unhandled Exception: OutOfMemoryException.       
```

I've tried this 3 times now and this is always the result.

The exact command is in `debian/rules`:

```
CONFIG := Release
dotnet clean --configuration $(CONFIG) $(CURDIR)/MediaBrowser.sln
```

**Comment by BnMcG** [comment]
Please assign to me and I'll take a look.

**Comment by BnMcG** [comment]
I can't reproduce this  behaviour, from the repository root, I ran the following commands in order:

1. `dotnet clean --configuration RELEASE ./MediaBrowser.sln`
2. `dotnet publish --configuration RELEASE ./MediaBrowser.sln --output='./usr/lib/jellyfin/bin'`
3. `dotnet clean`

Each step took about 12 seconds.

**Comment by joshuaboniface** [comment]
That is very odd! Is there a way to work around it? I always did find `dotnet clean` to be very very slow.

**Comment by BnMcG** [comment]
If you add a `-v d` argument to the dotnet clean command in the Debian rules file and then run, do you find it seems to be repeating the same projects in the output as well?

I'm not sure. One thing we could try is putting the dotnet commands in a sh file and running that from the `dpkg-buildpackage` command and seeing if that makes a difference. I'm tempted to say this is some sort of weird bug in dotnet, but I'm not sure.

Do you know how `dpkg-buildpackage` invokes these commands?

**Comment by BnMcG** [comment]
`-v d` will just make the output more verbose, I wouldn't expect it to fix anything. I'd try moving the dotnet calls into a shell script and calling that and seeing if it changes anything.

**Comment by joshuaboniface** [comment]
OK, I've narrowed it down to a `fakeroot` problem. If I run it as my real user, it works fine. If I run it under `fakeroot`, it loops endlessly. If I run it under real root, it also works fine. Looks like an incompatibility between the two tools - I'll see if I can dig into why.

**Comment by BnMcG** [comment]
Nice find!

**Comment by joshuaboniface** [comment]
Yup, that works, and in fact completes faster than running it as my normal user!

That fixes it, I'll do a PR to add that option to the Debian rules.
