### ISSUE TITLE
[Issue]: 'Custom rating' no longer overrides 'Parental rating' for Parental Control

### ISSUE THREAD

**Issue by jkrentz** [jellyfin/jellyfin#12007]
### Please describe your bug

Expected custom rating to supersede parental rating when set, as was the behavior in 10.8

### Reproduction Steps

1. Set a user's maximum allowed parental rating to 'PG'. Block items with no or unrecognized rating information on Shows.
2. Have a TV Show in the library with a parental rating of 'TV-PG'. This exceeds the maximum allowed rating of the user. The parental rating may also be blank.
3. Set a custom rating on the TV show to 'PG'.
4. Observe that the user cannot see the TV Show in the Shows view of the library. Library count will indicate that it is visible, but nothing is displayed.

![Capture](https://github.com/jellyfin/jellyfin/assets/4307988/f609d496-f70c-4d79-935c-9517e88a3706)

5. Lower the parental rating to 'PG'. Observe that the user can now see the TV Show.

### Jellyfin Version

10.9.0

### Environment

```markdown
- OS: ubuntu 20.04
- Linux Kernel: n/a
- Virtualization: n/a
- Clients: browser, android
- Browser: n/a
- FFmpeg Version: n/a
- Playback Method: n/a
- Hardware Acceleration: n/a
- GPU Model: n/a
- Plugins: none
- Reverse Proxy: nginx
- Base URL: none
- Networking: host
- Storage: local
```

### Jellyfin logs

```shell
nothing interesting
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by benab** [comment]
I still have this issue on 10.10 even though this issue was closed and marked completed.

**Comment by Bond-009** [comment]
@benab Please open a new issue as this one was closed by the person who created it.
