### ISSUE TITLE
[Issue]: 10.9.6 - Could not find a part of the path '/config/data'

### ISSUE THREAD

**Issue by nothing2obvi** [jellyfin/jellyfin#12006]
### Please describe your bug

Jellyfin crashed on 10.9.6. Just updated from 10.9.5. I get a repeating error (see below).

### Reproduction Steps

1. Watch something
2. Jellyfin crashes; get error in logs

### Jellyfin Version

10.9.0

### if other:

10.9.6

### Environment

```markdown
- OS: MacOS Sonoma 14.5
- Linux Kernel: n/a
- Virtualization: Docker Desktop 4.31.0
- Clients: Jellyfin Android TV
- Browser: Opera
- FFmpeg Version: whatever is with Jellyfin
- Playback Method: Jellyfin Android TV
- Hardware Acceleration: n/a
- GPU Model: n/a
- Plugins: many
- Reverse Proxy: none
- Base URL: none
- Networking: local
- Storage: external HDD
```

### Jellyfin logs

```shell
Error whilst attempting to create folder
System.IO.DirectoryNotFoundException: Could not find a part of the path '/config/data'.
   at System.IO.FileSystem.CreateParentsAndDirectory(String fullPath, UnixFileMode unixCreateMode)
   at System.IO.FileSystem.CreateDirectory(String fullPath, UnixFileMode unixCreateMode)
   at System.IO.Directory.CreateDirectory(String path)
   at Jellyfin.Server.Helpers.StartupHelpers.CreateApplicationPaths(StartupOptions options)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gnattu** [comment]
The log says everything. Your data path is not correctly passed into your docker container.

**Comment by nothing2obvi** [comment]
@gnattu 

How could that happen if I didn't change anything when upgrading from 10.9.5 to 10.9.6? I reverted to 10.9.5 and I'm all good now.

**Comment by felix920506** [comment]
this is an issue with your docker setup. Please head to our forum or chat rooms for troubleshooting help. https://jellyfin.org/contact
