### ISSUE TITLE
Feat. Artists 

### ISSUE THREAD

**Issue by screwfaze** [jellyfin/jellyfin#1201]
**Describe the bug**
 Featured artists not appearing on media that has been tagged and verified by Picard.

**To Reproduce**

1. Tested with various albums just not picking up featured artists from tags

**Expected behavior**

**Logs**

**Screenshots**

**System (please complete the following information):**
Docker

**Additional context**

**Comment by EraYaN** [comment]
Do you know what tag that info gets stored in?

**Comment by screwfaze** [comment]
Sorry I do not understand what you mean by what tag please explain.

**Comment by EraYaN** [comment]
What is the [ID3](https://en.m.wikipedia.org/wiki/ID3) tag Picard saves the featuring artist info to? If it’s just the artist tag the problem might be on our end in processing those, but if it’s some not esoteric tag then we might need to include extra stuff to read those.

So the tag is like the field the info shows up in in day foobar or iTunes.

**Comment by screwfaze** [comment]
![jellyfin](https://user-images.githubusercontent.com/17312955/55684230-c5a1b900-5940-11e9-8a03-e333f96ceecf.PNG)

I have attached an example, most of my files are flacs if that is useful.

Thanks

**Comment by EraYaN** [comment]
And what does Jellyfin show? Since I feel the artist field might just be displayed as is. Although the "Artists" field might be ignored, or maybe we pick just the first one.

**Comment by screwfaze** [comment]
Hi @EraYaN ,

You can close this one now mate I have been doing some checking and its actually not Jellyfin to blame here. When I tagged the music again and refreshed all the feat artists showed up on Jellyfin. So Jellyfin is working perfectly!!

Thanks
