### ISSUE TITLE
[Issue]: Hearing impaired subtitle stream indicator is too sensitive leading to false detections

### ISSUE THREAD

**Issue by mikewesten** [jellyfin/jellyfin#12019]
### Please describe your bug

There's an issue with the new subtitle stream indicator code #7379
It's falsely displaying the subtitle label for hearing impaired when the letters "HI", "CC", or "SDH" are found within any word descriptions (as in, they're present within a word by mere coincidence).

### Reproduction Steps

Name a subtitle giving it a description using any word that has the letters "hi" in it.
Example: `movie.name.year.date.Subs for Chinese Audio.eng.srt`
Instead of displaying the intended descriptive label "Subs for Chinese Audio", the subtitle indicator displays the "Hearing Impaired" label instead.
Quickly confirm this is what it is doing by changing the .srt filename to `movie.name.year.date.Subs for C h i n e s e Audio.eng.srt` and rescanning.
Now the indicator displays the label as "Subs for C h i n e s e Audio" instead of "Hearing Impaired".

### Jellyfin Version

10.9.0

### Environment

```markdown
Universal
```

### Jellyfin logs

```shell
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
should be fixed by #12026
