### ISSUE TITLE
[Issue]: Only Three episodes displayed on jellyfin web interface

### ISSUE THREAD

**Issue by phiphila** [jellyfin/jellyfin#12044]
### Please describe your bug

When I have a lot of episodes in my "series" sections, the number of series displayed is only 3. I think this is due to the number of episodes (too many episodes).
Is it possible to have a parameter to change the number of episodes to display (I could then increase this parameter), or better, a parameter to choose the number of different series to display without taking into account the number of episodes?
-----
Lorsque j'ai beaucoup d'épisodes dans mes sections "séries", le nombres de séries affichées n'est que de 3. Je penses que cela est du au nombres d'épisodes (épisodes trop nombreux). 
Est t'il possible d'avoir un paramètre pour changer le nombres d'épisodes à afficher (je pourrais alors augmenter ce paramètre), ou mieux, un paramètre pour choisir le nombres de séries différentes à afficher sans prendre en compte les nombres d'épisodes ?

### Reproduction Steps

put a lot episodes in series section

### Jellyfin Version

10.9.0

### Environment

```markdown
- OS: windows 11
- Linux Kernel:
- Virtualization:
- Clients:
- Browser: all
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
No necessary
```

### Please attach any screenshots here

![webInterface](https://github.com/jellyfin/jellyfin/assets/36555477/d6fc2909-3118-491c-8fcb-6103f385cdaf)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
duplicate of #1880
