### ISSUE TITLE
[Issue]: Progress of Movie/Show no longer shows on the Main splash page of the media about to played.

### ISSUE THREAD

**Issue by gummykage** [jellyfin/jellyfin#12068]
### Please describe your bug

On main home page the blue progress bar shows.
![image](https://github.com/jellyfin/jellyfin/assets/9695713/2ae62746-95c7-4cd5-8158-e541f336a0b9)

No longer shows in any main page:
![image](https://github.com/jellyfin/jellyfin/assets/9695713/5f0d8cae-2518-4cbb-836c-1bf49b94dcbf)

### Reproduction Steps

1.) This happens in chrome, jellyfin media player for win, and ios app jellyfin mobile.

### Jellyfin Version

10.9.0

### if other:

10.9.6

### Environment

```markdown
- OS:Linux
- Linux Kernel:QNAP QTS 5.2.0.2782
- Virtualization: Docker
- Clients: Jellyfin Media Player, Jellyfin Mobile OS
- Browser: Chrome
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
More of a inconvenient cosmetic bug, sorry about bugging you all.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
This is an intentional change.
