### ISSUE TITLE
Jellyfin Server Windows - Upgrade from 10.9.3 -> 10.9.4/.5 or .6 corrupts database

### ISSUE THREAD

**Issue by laris1403** [jellyfin/jellyfin#12069]
### Please describe your bug

When upgrading from 10.9.3 -> .4/.5/.6 the server starts doing the audiofix task which results in the malformed database error showing in log file and the server shuts itself down.

### Reproduction Steps

Windows version of Jellyfin Server 10.9.3
Download new version and install it - tried .4, .5 & latest .6
Install is successful
Start server
Server starts and runs for about 30s and then stops itself
Checking logs shows fixaudio task running, then erroring and malformed database error received 
Restarting the server results in the same error
Only way to get out of this is to restore 10.9.3 version from a backup

### Jellyfin Version

10.9.0

### if other:

10.9.3

### Environment

```markdown
Jellyfin Server running under Windows Server 2016
Version 10.9.3
Accessing via Windows client
```

### Jellyfin logs

```shell
Corrupt: SQLitePCL.pretty.SQLiteException: database disk image is malformed
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DrJapan** [comment]
I think I'm experiencing the same thing.

**Comment by felix920506** [comment]
#12035 Duplicate
