### ISSUE TITLE
[Issue]: Unable to correctly identify the flags and stream title of external subtitles

### ISSUE THREAD

**Issue by HMSRenown** [jellyfin/jellyfin#12062]
### Please describe your bug

Unable to correctly identify the flags and stream title of external subtitles
When I mount four external subtitles, their file names are as follows：
`Episode S01E01.Chinese Simplified with English.chi.default`
`Episode S01E01.Chinese Simplified.chi`
`Episode S01E01.Chinese Traditional with English.chi`
`Episode S01E01.Chinese Traditional.chi`
It appears on the front-end interface as:
![图片](https://github.com/jellyfin/jellyfin/assets/58620808/98923f83-9792-434c-90b3-bada83130c2a)
In this case ,we've seen that the flags ‘chi’ is identified as the stream title, but the stream title disappeared.
I've tried reversing the order of flags and stream title in my tests, but it didn't work.
This issue does not exist in version 10.8.13

### Reproduction Steps

1.In Jellyfin Version 10.9.6
2.Having an Movie or TV Episodes with external subtitles
3.Rename external subtitles with flags and stream title

### Jellyfin Version

10.9.0

### Environment

```markdown
- OS:Windows 10
 - Linux Kernel: none
 - Virtualization: KVM
 - Clients: Browser
 - Browser: Firefox 126
 - ffmpeg version 6.0.1-Jellyfin
 - Playback: Direct Play, Transcode
 - Hardware Acceleration: NVENC
 - GPU Model: NVIDIA RTX 4060Ti
 - Installed Plugins: TMDB, TVDB, OMDB, WEBh
 - Reverse Proxy: Nginx
 - Base URL: 
 - Networking: 
 - Storage:
```

### Jellyfin logs

```shell
Seems no related log to this issue.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shadowghost** [comment]
See #12026

**Comment by Kha611** [comment]
Help

**Comment by Shadowghost** [comment]
Original issue fixed by linked PR above.
