### ISSUE TITLE
Home Assistant integration

### ISSUE THREAD

**Issue by cznewt** [jellyfin/jellyfin#1207]
**Describe the feature you'd like**

The possibility to connect home assistant with jellyfin as https://www.home-assistant.io/components/emby/?

**Additional context**

I can clone the Emby component and make the necessary refactor, it there any Jellyfin's API key?

**Comment by EraYaN** [comment]
API Keys used to be created in the Jellyfin UI (on a per instance basis)

**Comment by anthonylavado** [comment]
You can still create an API key in the same place.

Looks like we’ve approached pyEmby before: https://github.com/mezz64/pyEmby/issues/6

If there is something that isn’t working, or we just want to make a fully separate component, I’d say that’s the place to start :-)

**Comment by phantomse** [comment]
Is there similar functionality or can this be approached? https://github.com/hassio-addons/addon-phlex/blob/master/README.md

**Comment by agilob** [comment]
hass works fine with jellyfin for me, I use it daily without any problems.
