### ISSUE TITLE
Trickplay: hardware accelerated MJPEG encoding on Rockchip devices

### ISSUE THREAD

**Issue by woiza** [jellyfin/jellyfin#12071]
Currently hardware accelerated MJPEG encoding is only available on QSV and VAAPI.
According to [ffmpeg-rockchip](https://github.com/nyanmisaka/ffmpeg-rockchip?tab=readme-ov-file#encoders) MJPEG hardware acceleration is available.
Is this already planned for a future release or should I create a feature request on your dedicated [feature request](https://features.jellyfin.org/) hub?

**Comment by nyanmisaka** [comment]
It's planned. Feature requests should be opened in https://features.jellyfin.org/
