### ISSUE TITLE
I hope Jellyfin can support multiple subtitle tracks playback

### ISSUE THREAD

**Issue by dadastory** [jellyfin/jellyfin#12083]
I hope that the Jellyfin team can support the ability to multi-language subtitles, in other words, to support the simultaneous selection of multiple subtitle tracks, whether it is a plug-in or system integration，just like potplayer, it will make it powerful
![image](https://github.com/jellyfin/jellyfin/assets/84147842/1fc432a2-dc3d-490d-b9e9-bf6bce79f9d0)

**Comment by dadastory** [comment]
> 它已经做到了 ![图像](https://private-user-images.githubusercontent.com/67679349/338849289-0a0aaa6a-a94c-4b56-ba81-610d9d6c5d94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNzQ1ODMsIm5iZiI6MTcxODE3NDI4MywicGF0aCI6Ii82NzY3OTM0OS8zMzg4NDkyODktMGEwYWFhNmEtYTk0Yy00YjU2LWJhODEtNjEwZDlkNmM1ZDk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDA2MzgwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1ZWQ4M2YyOTBmNWI3ODUyMGRmNzk5NTg1NmM0ZTgzZjM4OTg4ZWNmYTA1N2YzNTViNTMyZTNkMmNkOGJjZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SANkeNKoDvlk8J__JROdXnxhw52yHnqa9EnPhh55JjU)

你是怎么配置的？

**Comment by dadastory** [comment]
> ![image](https://private-user-images.githubusercontent.com/67679349/338856745-08d12f9f-4316-4303-bb8b-fa3a18c83d8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNzYxNjAsIm5iZiI6MTcxODE3NTg2MCwicGF0aCI6Ii82NzY3OTM0OS8zMzg4NTY3NDUtMDhkMTJmOWYtNDMxNi00MzAzLWJiOGItZmEzYTE4YzgzZDhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDA3MDQyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkN2ZmYmJlYTI1MzVmODUzODgyZjFhMmQ3ZTNlMmNlMjM0ZWRmZGRmMTM1YzUwMDA4ZDNlOTJlYjNhYzliMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5EwsphqtYx0aUBjPU5Ua8XBn9rLd4d4hGO51-DVnDJk)
> 
> I didn't configure anything

![image](https://github.com/jellyfin/jellyfin/assets/84147842/cc05ba9e-01e7-4d8b-a4c1-2e44655b1f07)

why? i do not have any configure

**Comment by Bond-009** [comment]
This feature is in 10.9
https://features.jellyfin.org/posts/936/multi-language-subtitles
https://github.com/jellyfin/jellyfin-web/pull/3906
