### ISSUE TITLE
[Issue]: Jellyfin gets slow over time, eating up all CPU and showing stuck ffmpeg processes

### ISSUE THREAD

**Issue by Schaka** [jellyfin/jellyfin#12084]
### Please describe your bug

Over time, I've noticed since 10.9.x that Jellyfin tends to get really slow. I've been monitoring system resources with htop and container resources with Docker to try and figure this out but haven't been able to.

It seems some ffmpeg tasks never finish and they start adding up. I've tried to have a look at my log file to see if anything is amiss but couldn't spot anything. I was also not able to reproduce this reliably. I thought it may have been the new Keyframe Extractor or similar.

Also small note: IntroSkipper says ConfusedPolarBear, but that's only the package - it's the new one that works with 10.9

One more thing I can think of: I have some libraries that are purely symlinks of items available in other libraries. It's how I manage letting family and friends know what media is going to be removed soon and to watch it now or never. Maybe playing via symlink could cause some of these issues. These links are written and re-written automatically. It's not unimagineable that this would happen while something is being processed for these "files". That being said, those libraries have everything but metadata fetching disabled.

![htop](https://github.com/jellyfin/jellyfin/assets/2223171/2e2f5fd7-0fd8-4edd-bbc0-1656e10cf932)

I'm tossing my log files here because they're too large for GitHub and I unfortunately don't see any section I could determine as relevant:

[jellyfin.log](https://github.com/user-attachments/files/15799654/jellyfin.log)
[ffmpeg.txt](https://github.com/user-attachments/files/15799656/ffmpeg.txt)

### Reproduction Steps

1. Wait and see, I have not had success reproducing this reliably

### Jellyfin Version

10.9.0

### Environment

```markdown
- OS: Debian 12
- Linux Kernel: 6.1.55-1
- Virtualization: Docker
- Clients: Browser (Firefox, Chrome, Edge), Jellyfin Media Player, Android TV OS
- Browser: See above
- FFmpeg Version: default that's shipped, so 6.x
- Playback Method: Direct and transcodes
- Hardware Acceleration: QSV
- GPU Model: HD630
- Plugins: Intro Skipper, Trakt
- Reverse Proxy: Nginx
- Base URL: -
- Networking: -
- Storage: HDD
```

### Jellyfin logs

```shell
See above
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cvium** [comment]
> It seems some ffmpeg tasks never finish and they start adding up. I've tried to have a look at my log file to see if anything is amiss but couldn't spot anything. I was also not able to reproduce this reliably. I thought it may have been the new Keyframe Extractor or similar.

What you are seeing are Jellyfin threads, not ffmpeg. `--ffmpeg` is just a commandline argument in Jellyfin specifying the location of the ffmpeg binary.

I don't really see anything wrong in that htop nor do your logs seem to indicate any glaring issues.

**Comment by PhilAllmighty** [comment]
Got the same issue and I think it comes from the introskipper plugin. When uninstalled... no more problem... and the issue comes back as soon as I reinstall it and I have to restart the container to fix it temporarily.

**Comment by Schaka** [comment]
I'll report it there as well. It's odd, because just triggering the task via the dashboard, I was never able to reproduce it.
Not for my home server where it's constantly in use either. So I figured it wouldn't be that.

**Comment by PhilAllmighty** [comment]
so far so good since intro-skipper release 0.2.0.10. How about you?

**Comment by Schaka** [comment]
I've been mostly good since limiting multi threading like suggested here: https://github.com/jumoog/intro-skipper/issues/199#issuecomment-2165195209

My suspicion is that either it'll take longer to happen now or if there's only ever one thread it gets cleaned up properly.

**Comment by PhilAllmighty** [comment]
Yeah I saw that but it didn't change a bit... for me it was the updated plugin that made the difference.

**Comment by Schaka** [comment]
I just happened again last night with limited multi threading on 10.9.7 and the "fixed" intro-skipper plugin.
The container was using 20GB+ of RAM at the time and everything slows down when my system starts swapping onto the slow spinning drives.

**Comment by PhilAllmighty** [comment]
Oh well... I guess it's something else then. I haven't had an issue since the updated plugin. If that makes a difference... ds920 w 20GB memory

**Comment by jawtis** [comment]
I have same problem when android app cant play a video. With every retry ram usage build up.

**Comment by JPVenson** [comment]
Hey there, as you reported this seems to be an issue with the external plugin. I looked it up and he actually had an memory leak in there so its plausable. However this report is on the wrong repo then.

**Comment by Schaka** [comment]
The problem was related to whatever is causing the ongoing memory problems with 10.9.x

Additionally, I had swapping enabled in my OS, which slowed Jellyfin down to a crawl. This happened both with and without the plugin. I believe the CPU usage it showed was because it got stuck running longer running tasks like the library scan forever and writing data to swap when it shouldn't have. 

I misinterpreted this as Jellyfin using up all CPU resources (it didn't, 100% in Docker is not actual 100% in your OS) and that's why it became too slow to even serve the web UI resources.

I don't believe there is a problem with high CPU usage.

**Comment by felix920506** [comment]
The ffmpeg processes not getting disposed of is not a Jellyfin bug, but a bug with the intro skipper plugin. 

The memory usage bug is being looked into but we still don't know the problem yet, that is being tracked in another issue. Please report anything further over there.
