### ISSUE TITLE
cannot enter jellyfin server installed in truenas from chrome. access denied

### ISSUE THREAD

**Issue by gigihhh122** [jellyfin/jellyfin#12085]
### Please describe your bug

When the ipv4 code is copied an error occurs saying access denied

### Reproduction Steps

1) truenas 13.0 U6.1 ; ipv4 from jellyfin jail
2) copied ipv4 on chrome tab 
3) error of denied access

### Jellyfin Version

10.9.0

### Environment

```markdown
- OS: truenas 13.0-U6.1
- Linux Kernel:
- Virtualization:
- Clients:
- Browser: chrome
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
boo
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
Truenas core / enterprise are freebsd therefore unsupported. Please report issues on those platforms here. https://github.com/Thefrank/jellyfin-server-freebsd
