### ISSUE TITLE
[Issue]: NFO and thumbnail files of Extras

### ISSUE THREAD

**Issue by Mihara** [jellyfin/jellyfin#12099]
### Please describe your bug

This is not, strictly speaking, a bug, but neither it is a feature request. Mostly, this is request to determine what *should* the server be doing, if anything.

Assume that you have a TV show with a file in the `Extras` directory and a regular episode, that NFO writing is enabled, and that artwork for the show is configured to be kept with the actual media files.

Metadata changed on an episode will get reflected in the NFO written, so if you set a different title on it, you will see a different title in the NFO. A thumnail of the episode will appear next to the video file as `-thumb.jpg` (as of 10.9.6 - previously, they would end up in `metadata`)

But then you do the same to the file in the Extras directory, presented in the UI among "Special Features". No NFO file will be written, yet the title will change. No `-thumb.jpg` will be created upon scanning either, even though I'm sure it's created somewhere, because there's no indication ffmpeg is called every time it is to be displayed.

I understand that there is no well-defined NFO format for extras (what they even are? `<movie>`? Certainly not `<episodedetails>` or `<musicvideo>`... There's no reason Jellyfin can't define its own, though, it might become a standard in the future.) so it's not a surprise nothing is written.

But the thumbnails, at least, should be kept together with the files, when the library is configured to do that, shouldn't they?

### Reproduction Steps

1. Enable "Metadata Savers [x] NFO" and "Save artwork into media folders [x]" for a TV show library.
2. Create a show with the following directory structure:

```
Shows
  -> Show (20XX)
     -> Season 01
        Episode S01E01.mkv
     -> Extras
        Special Feature.mkv
```

2. Scan it. Observe absence of `Special Feature.nfo` and `Special Feature-thumb.jpg` in Extras.

### Jellyfin Version

10.9.0

### if other:

10.9.6

### Environment

```markdown
- OS: Irrelevant
- Linux Kernel: Irrelevant
- Virtualization: Irrelevant
- Clients: Irrelevant
- Browser: Irrelevant
- FFmpeg Version: Irrelevant
- Playback Method: Irrelevant
- Hardware Acceleration: Irrelevant
- GPU Model: Irrelevant
- Plugins: Irrelevant
- Reverse Proxy: Irrelevant
- Base URL: Irrelevant
- Networking: Irrelevant
- Storage: Irrelevant
```

### Jellyfin logs

```shell
Nothing regarding thumbnail generation and NFO reading is posted to the logs by default.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tamburra** [comment]
Jellyfin also allows an Extras folder within the season folders. This populates extras within the season view. This directory doesn't get any nfo data either. Also these extras don't get sorted in alpha/numerical order but I believe that would be a separate issue.

**Comment by TheMelmacian** [comment]
For Series/Shows instead of an `Extras` folder in the series root you can use a `Season 00` folder which works like a separate season for all extras. Everything will have it's own media and nfo files. If a metadata provider knows the extra, jellyfin can also fetch the metadata automatically, if the extra has the right marker: `S00Exx` (the correct episode number can be found on the site of the metadata provider).
In the metadata you can also define after/before which season/episode the extra should be displayed (done automatically for known extras) and it will then be shown inside the season in the defined order.

Sadly we don't have the same features for Extras folders.
Especially for movie extras it would be awesome to have something similar.

**Comment by felix920506** [comment]
This is more of a design choice problem. If you would like to change it then feel free to come have a chat in our matrix space. https://jellyfin.org/contact
