### ISSUE TITLE
Multiple versions sorts by resolution regardless of naming structure

### ISSUE THREAD

**Issue by theguymadmax** [jellyfin/jellyfin#12129]
### Please describe your bug

According to the docs, multiple versions should be sorted by _filenames_ in alphabetic order except for the case of resolution filenames.

"Order of Versions
Movie versions are presented in an alphabetically sorted list. An exception applies to resolution names, which are sorted in descending order from highest to lowest resolution. A version name qualifies as a resolution name when ending with either a p or an i. "

However, the WebUI always sorts by resolution first regardless of filenames. 

### Reproduction Steps

Beta
Path: V: \Movies\Big Buck Bunny (2008)\Big Buck Bunny (2008) - Beta.mp4
Resolution: 3840x2160

Alpha
Path: V: \Movies\Big Buck Bunny (2008)\Big Buck Bunny (2008) - Alpha.mp4
Resolution: 1920x1080

Gamma
Path: V: \Movies\Big Buck Bunny (2008)\Big Buck Bunny (2008) - Gamma.mp4
Resolution: 1920x1080

The higher resolution gets sorted first, even though the filename doesn't include any resolutions. 

![versions](https://github.com/jellyfin/jellyfin/assets/171496228/34a17889-877d-45b6-885c-92d4a2b986ee)

### Jellyfin Version

10.9.0

### if other:

10.9.6

### Environment

```markdown
- OS: Windows
- Linux Kernel: N/A
- Virtualization: No
- Clients: Web
- Browser: Firefox
- FFmpeg Version: N/A
- Playback Method: N/A
- Hardware Acceleration: N/A
- GPU Model: N/A
- Plugins: N/A
- Reverse Proxy: N/A
- Base URL: N/A
- Networking: N/A
- Storage: N/A
- Server: 10.9.6
```

### Jellyfin logs

```shell
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mikewesten** [comment]
Specifically it sorts by resolution width. So for example a version that's 1920x1040 gets sorted ahead of 1916x1080.

**Comment by MichaelRUSF** [comment]
This sorting behavior is also present in the Jellyfin Android TV client (.17.4), which doesn’t use the Jellyfin web UI. 

Server: 10.9.10

![Screenshot from 2024-09-04 13-58-03](https://github.com/user-attachments/assets/d1e3b403-dc48-4418-bfbe-4ae5b920aad2)
