### ISSUE TITLE
[Issue]: HLS manifest uses "mp4a" for EAC3 instead of "ec-3"

### ISSUE THREAD

**Issue by jnorris441** [jellyfin/jellyfin#12133]
### Please describe your bug

Jellyfin stopped being able to stream EAC3 in fMP4 HLS on VisionOS 2.0. mediastreamvalidator is one of the tools Apple provides to debug HLS. it reports

```
Error: Playlist codec type doesn't match content codec type
--> Detail:  Playlist: mp4a, Content: ec-3
```

For example the HLS manifest for a Dolby 5.1 has `mp4a.a6` in the `CODECS` list instead of the Apple-recommended `ec-3`

`RANGE=PQ,CODECS="hvc1.2.4.L150.B0,mp4a.a6",RESOLUTION=3840x2160,FRAME-RATE=23.976,SUBTITLES="subs"`

Apple is pretty particular about supported codec values I guess [https://developer.apple.com/documentation/http-live-streaming/hls-authoring-specification-for-apple-devices-appendixes#Values-for-the-CODECS-attribute](https://developer.apple.com/documentation/http-live-streaming/hls-authoring-specification-for-apple-devices-appendixes#Values-for-the-CODECS-attribute)

Please tell me I am wrong about this so this can be closed.

I have the full FFMPEG log but Github will not let me paste it in the issue. `There was an error creating your issue: body is too long (maximum is 65536 characters).`

### Reproduction Steps

Try to stream an HLS manifest in any app that supports HLS on VisionOS 2, or a raw AVPlayer.

### Jellyfin Version

10.9.0

### Environment

```markdown
- OS: Windows 10
- Linux Kernel: none
- Virtualization: none
- Clients: AVPlayer in VisionOS 2 beta
- Browser: none
- FFmpeg Version: 6.0.1-Jellyfin
- Playback Method:  VisionOS 2 raw AVPlayer
- Hardware Acceleration: VideoToolbox/AVFoundation I would imagine
- GPU Model: M2
- Plugins: none
- Reverse Proxy: none
- Base URL: none
- Networking: Bridge/NAT
- Storage: NFS
```

### Jellyfin logs

```shell
only FFMPEG logs
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jnorris441** [comment]
"mp4a.a6" is widely used for EAC3 so this is probably not what is causing my playback problem.

**Comment by jnorris441** [comment]
I have confirmed this is the reason it fails to play. AVPlayer will not tolerate a codec mismatch

**Comment by gnattu** [comment]
It used to on before iOS 17 though. I have no environment to simulate the pre-release version until weekends. Can you try with `mp4a.A6`(upper case A) and see if that works? The lower case oti technically violates the spec but is accepted for ages due to the usage. However, an upper case `mp4a.A6` oti is defined in RFC6381, but I'm not sure it is used for HLS as iOS 17 accepts all of them.

**Comment by jnorris441** [comment]
@gnattu No that did not work. I get the same playback error.

And although AVPlayer might have different rules than mediastreamvalidator, it still reports this:

```
Error: Playlist codec type doesn't match content codec type
--> Detail:  Playlist: mp4a, Content: ec-3
```

**Comment by jnorris441** [comment]
This is affecting my Jellyfin client app BTW. I added a local server to the app to rewrite the HLS manifest. i hope it's addressed eventually

**Comment by creekdrops** [comment]
I ran into this as well while working on a Jellyfin client for VisionOS 2. Similarly, there is also an issue with some older AC3 content transmitting as `mp4a.a5` which mediastreamvalidator apparently doesn't like either.

**Comment by gnattu** [comment]
Does iOS 18 reject it too? Or is it only an VisionOS issue?

**Comment by creekdrops** [comment]
I'll try to find some time to see compile Swiftfin for iOS 18 to test and see if the issue is present there as well.
