### ISSUE TITLE
Missing Re-Shuffle Queue, includes playing song

### ISSUE THREAD

**Issue by UltraHKR** [jellyfin/jellyfin#1213]
Let say you add a bunch of songs to the queue, you start playing a song then you hit the re-shuffle button, replace the queue the playing song is stopped and "shuffled".
This is not correct behavior, the current playing song should be left alone (first?) and playing, while all the others are reordered.

This happens on the WebUI, and AndroidTV among others. confirmed by anthonylavado (Jellyfin Core Team)

**Screenshots**
[https://imgur.com/UPr1moR](https://imgur.com/UPr1moR)

OS: Win2016 x64
Server version: jellyfin_10.2.2.windows-x64
Client version: jellyfin-androidtv_amazon-release_beta4 1.1.90a

First reported on Reddit: https://www.reddit.com/r/jellyfin/comments/b5y9ox/bug_android_tv_reshuffle_queue_includes_playing/

**Comment by UltraHKR** [comment]
How can I help to move this issue forward?

**Comment by JustAMan** [comment]
Is it still happening on Web UI in Jellyfin 10.4.0?

**Comment by cvium** [comment]
This is actually a feature request. Re-open on https://features.jellyfin.org if it's still wanted.
