### ISSUE TITLE
Cool URLs don't change: please stop changing repository format

### ISSUE THREAD

**Issue by selfhoster1312** [jellyfin/jellyfin#12130]
It's not a feature request, it's not a bug. URL format for packages has changed for 10.9 release.

The previous change broke existing URLs and broke the Yunohost package tests and people [installing/upgrading](https://github.com/YunoHost-Apps/jellyfin_ynh/issues/148).

```
61276 WARNING https://repo.jellyfin.org/releases/server/debian/versions/jellyfin-ffmpeg/5.0.1-5/jellyfin-ffmpeg5_5.0.1-5-bullseye_amd64.deb:
61277 WARNING 2024-05-21 14:48:29 ERROR 404: Not found.
```

It's ok to make change/improve. But please keep redirects on old URLs because [cool URLs don't change](https://www.w3.org/Provider/Style/URI). Or if you really want to break please announce it on the blog 1+ month in advance, or directly on downstream issue trackers.

Possibilities to fix:

- use HTTP redirects to keep old URLs alive
- use symlinks on the server to keep old URLs alive
- announce breaking change some time in advance

**Comment by cvium** [comment]
You expect us to keep every file forever?

**Comment by felix920506** [comment]
The format change of the repository was announced *Early March This Year*, which was *more than 3 months ago*.

Closing this as it does not reference an actual issue with Jellyfin.

**Comment by selfhoster1312** [comment]
> You expect us to keep every file forever?

Releases, yes. If you can't it's ok to ask for help from 3rd party mirrors. I don't expect the same from development snapshots or alpha versions.

> The format change of the repository was announced Early March This Year

Not really? The 10.9 testing post mentions plugin URL change, not Debian package URL change. It could have been a dedicated blog post, a "Information for packagers" section, or a "Breaking changes" section... 

> Closing this as it does not reference an actual issue with Jellyfin.

Thanks, i was just raising awareness about the issue to prevent future problems :+1:
