### ISSUE TITLE
IPTV plugin wont shown on the Home page

### ISSUE THREAD

**Issue by faust93** [jellyfin/jellyfin#1214]
**Describe the bug**
Plugins which supposed to have an UI element on the 'Home' page (IPTV in my case) does not appear there.

**To Reproduce**
1. Clone and build latest Jellyfin version from the GitHub.
2. Install IPTV plugin. Restart. Configure IPTV plugin.
3. Proceed to the 'Home' page
4. No IPTV plugin shown under 'My Media' or anywhere else.

**Expected behavior**
As for Jellyfin v.2.2.0 after installing and configuring there's an IPTV item shown under 'My Media' heading. The same expected behavior is for the latest Jellyfin version.

**Logs**
No any errors shown in the logs

**Screenshots**
Jellyfin 2.2.0
https://imgur.com/a/oh20JrJ
Jellyfin latest
https://imgur.com/a/8ND3b8u

**System (please complete the following information):**
 - OS: Running on plain Linux env (latest Arch x64)
 - Browser: Firefox 65.0.1
 - Jellyfin Version: latest built from github sources
 - Reverse proxy: no

**Comment by anthonylavado** [comment]
@faust93 This is currently expected behaviour, sadly. We made so many changes in 10.3 (which is kind of what the latest master branch is), that all plug-ins must be re-built. As a result, they won't work right until we do that, which is probably closer to the release.

**Comment by anthonylavado** [comment]
Basically, for stability, please use releases only :slightly_smiling_face: 

Otherwise, everything else is testing :sparkles:

**Comment by anthonylavado** [comment]
Closing for #1194
