### ISSUE TITLE
Ability to have a separate library based on Audio Language

### ISSUE THREAD

**Issue by fedonr** [jellyfin/jellyfin#12153]
For example, I have 5 movies in X language and 5 movies in Y Language. Now I want my library to show up all 10 movies, while for my parent's library I want only 5 movies to show up which are in X language.

Or if both X and Y can have separate library I can manage with that, as my parents won't need to go thru a huge library as they only watch movies in X language (audio)

**Comment by Bond-009** [comment]
Feature requests go [here](https://features.jellyfin.org/).
