### ISSUE TITLE
[Issue]: 10.9.6 FLAC "Artists" Tag Ignored

### ISSUE THREAD

**Issue by omniusaspirer** [jellyfin/jellyfin#12157]
### Please describe your bug

Music added prior to upgrading my server to 10.9.x correctly had the "Artists" tag scanned. Since updating no new music has featured artists recognized. This tag is used by Musicbrainz Picard for featured artists using a semicolon as a separator. I've only confirmed this bug for FLAC tags generated by Picard, not Id3 or any variants. It's also possible that Jellyfin is scanning this tag and some other mechanism is causing it not to be correctly populated into the database.   

This is a serious regression for anyone using Jellyfin for music and tagging their library with Picard.

### Reproduction Steps

Add new music under 10.9.x utilizing the Artists tag for featured artists. 

### Jellyfin Version

10.9.0

### Environment

```markdown
- OS: Arch Linux
- Linux Kernel: 6.9.4
- Virtualization: None
- Clients: Web, Finamp
- Browser: Firefox
- FFmpeg Version: 6.1.1
- Hardware Acceleration: Yes
- GPU Model: Intel Arc A380
- Plugins: None
- Reverse Proxy: Nginx
```

### Jellyfin logs

```shell
[2024-06-22 11:45:46.325 -05:00] [INF] Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/***/***/Music/Arlo Parks/My Soft Machine/Disk 1/07- Pegasus.flac\" -threads 0 -v warning -print_format json -show_streams -show_format"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shadowghost** [comment]
`Artists` tag is non-standard, we're currently thinking about how to properly handle it. Technically correct would be to configure picard to write multiple `Artist` tags.

**Comment by omniusaspirer** [comment]
Thanks for the response. I feel like there ideally needs to be some level of customization offered as music tagging sadly never coalesced around one true standard. In my own tagging multiple Artist tags are reserved for songs that are joint tracks, and I utilize the Artists tag when one artist is explicitly marked as a feature. I don't expect music apps to conform to that of course, but it's a differentiation I've chosen to make to best reflect the level of contribution made to each track in line with the artists labeling. 

I will also add that I do feel going against Picard defaults inevitably is going to lead to a lot of frustration for a lot of people, even if it's technically utilizing a non-standard tag. It's also a nontrivial ask to require someone to retag their library which can easily be hundreds of thousands of tracks curated over decades. I'm pretty excited to see the Jellyfin music ecosystem coming together with projects like Finamp, but unfortunately for me personally this is a step back as Jellyfin did previously respect the Artists tag.

**Comment by felix920506** [comment]
Duplicate #11411
