### ISSUE TITLE
[Issue]: Music library won't update correctly when source folder files change.

### ISSUE THREAD

**Issue by eightsheep67** [jellyfin/jellyfin#12172]
### Please describe your bug

i deleted an album folder then refresh the music library, the album still there with no source files. i have to delete it manully.
i change a music file name, and refresh the music library, then it will have 2 songs in the library.

### Reproduction Steps

i deleted an album folder then refresh the music library, the album still there with no source files. i have to delete it manully.
i change a music file name, and refresh the music library, then it will have 2 songs in the library.

### Jellyfin Version

10.9.0

### Environment

```markdown
- OS:dsm 7.2
- Linux Kernel:
- Virtualization:docker
```

### Jellyfin logs

```shell
none
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
Closing as #9259 duplicate
