### ISSUE TITLE
[Issue]: Recently Added Media is disappearing once watched

### ISSUE THREAD

**Issue by Gaffers2277** [jellyfin/jellyfin#12198]
### Please describe your bug

I noticed while i was on Jellyfin 10.8.x that once i had watched a new episode or movie it would disappear from my recently added lists. This has carried over to 10.9.7, if it is marked as watched it doesn't appear in the recently added sections on the home page but once i mark as unwatched they reappear.

### Reproduction Steps

1. Add new episode or movie =
2. Watch or mark as watched
3. Disappears from recently added

### Jellyfin Version

10.9.0

### Environment

```markdown
- OS:Windows 11
- Linux Kernel:N/A
- Virtualization:N/A
- Clients:Jellyfin Media Player 1.11.1
- Browser:FireFox
- FFmpeg Version:Bundled with Windows Installer
- Playback Method:Direct Play
- Hardware Acceleration:NVENC
- GPU Model:Nvidia GTX 960M
- Plugins:N/A
- Reverse Proxy:Nginx Reverse Proxy
- Base URL:jellyfin.mydomain.com
- Networking:N/A
- Storage:N/A
```

### Jellyfin logs

```shell
I dont see anything in the logs for the media being watched or visability in the recently added
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
This is an option configurable per user account.

Click the profile on the top right, go to "home" and the option will be in there.

**Comment by Gaffers2277** [comment]
> This is an option configurable per user account.
> 
> Click the profile on the top right, go to "home" and the option will be in there.

Well now i feel like a complete idiot. I looked through all the settings on the admin dashboard but didn't think to look at the client settings. Thank you
