### ISSUE TITLE
[Issue]: Extracted audio images are squished

### ISSUE THREAD

**Issue by StarTroop** [jellyfin/jellyfin#12194]
### Please describe your bug

Ever since the 10.9 update I've noticed that some of my music's cover art is being squished. It can be hard to notice sometimes as most of my music is pulling album art from the online sources, but for those lacking the art online, falling back to the extracted images displays the issue. For most albums imported after updating to 10.9 *with* online cover art, I can confirm the issue still persists by checking the individual songs' images.
Before 10.9, I did not have chapter image generation enabled, but I have enabled since. What I've noticed is that the extracted images from my audio are conforming to my chapter image extraction settings. i.e. I have chapter image resolution set to 360p, and my audio images are being resized to 640x360 (16:9 aspect ratio). I don't know if this behaviour existed pre-10.9 as I didn't use chapter image extraction then.
For note, I am managing all my music's metadata and embedded images with Musicbrainz Picard, and can confirm that the images are being embedded correctly, as they are pulled correctly in every other application.

### Reproduction Steps

1. Enabled chapter image generation and set resolution to 360p (or maybe anything other than original).
2. Delete images of an album and/or replace all images
3. If that album happens to pull cover art from online, check images for a single song in that album to see the extracted image.

### Jellyfin Version

10.9.0

### if other:

10.9.7

### Environment

```markdown
- OS: OpenMediaVault 6.9.16-1 (Shaitan)
- Linux Kernel: Linux 6.1.0-0.deb11.21-amd64
- Virtualization: Docker (linuxserver.io)
- FFmpeg Version: jellyfin-ffmpeg
- Storage: local
```

### Jellyfin logs

```shell
[2024-06-29 12:29:55.207 -04:00] [INF] [40] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/libraries/music/Rivers Cuomo/Alone XI ∶ The EWBAITE Years/volunteers   10.mp3\" -threads 0 -v warning -print_format json -show_streams -show_format"

I simply get this line for every track included in the replacement of metadata. No other pertinent info in the log.
```

### Please attach any screenshots here

![2024-06-29_12-38](https://github.com/jellyfin/jellyfin/assets/49848067/06c14f78-35bd-45af-b2ab-5fff8a373e1d)
![2024-06-29_12-39](https://github.com/jellyfin/jellyfin/assets/49848067/26777dcb-5c52-473f-a6a2-ac63f3f0a02d)
![2024-06-29_12-39_1](https://github.com/jellyfin/jellyfin/assets/49848067/f2b68ce6-269c-4c57-b709-6b13adefe0d0)
![2024-06-29_12-41](https://github.com/jellyfin/jellyfin/assets/49848067/bf5dce4f-b5d3-4fc8-89b4-1058b27ad5f9)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 1hitsong** [comment]
Here are some more examples, as I'm also experiencing this.

![image1](https://github.com/user-attachments/assets/d33c4452-3eb4-4874-9563-abdc540493cc)
Here you can see the extracted image in Jellyfin on the left, and on the right I've opened the image as it is saved inside the MP3 file. You'll notice the aspect ratio is off as it should be square.

![image2](https://github.com/user-attachments/assets/b064d790-c181-480f-8324-11c76619d634)
Here you can see several examples. All of these have square album art, but once extracted, the image sizes are off. They're much wider than they should be.

I've manually removed the images for all of these albums and replaced with the jpg cover art file, but the server is replacing my manual images with the stretched extracted images over and over again.

**Comment by 1hitsong** [comment]
Changing the Chapter Images Resolution had no image for me.

By default it was at 480. I changed it to match source, deleted the album, then added it back. No change, the image was still stretched.

As another test, I changed it to 360. The extracted cover is still 854 X 480.

So from my testing thus far, this value doesn't image album art extraction.

**Comment by 1hitsong** [comment]
Here are the steps I had to take to get the extracted images to match what's embedded in the files.

Navigate to: Admin / Libraries / Metadata

Change the resolution to `Match Source`

![image](https://github.com/user-attachments/assets/aaadd3db-5d6a-4152-b7c0-d175db544715)

In file explorer, navigate to Jellyfin's cache folder.

Delete the `extracted-audio-images` folder. If you don't delete this folder, it will not extract the images anew, it'll use the cached version that is as the incorrect resolution.

Back in the admin panel, trigger a scan for missing metadata, choosing to replace images.

Once the scan completed, the cover art now looks correct.

![image](https://github.com/user-attachments/assets/331cd954-1ce0-4de4-a55b-f17695cc7526)
