### ISSUE TITLE
[Issue]: Playback error when season has no files

### ISSUE THREAD

**Issue by TheAceMan** [jellyfin/jellyfin#12205]
### Please describe your bug

From a series screen it lists all seasons and has a play icon/option for seasons even if they have no files/media. If you try to play the season a "Playback Error Unable to find a valid media source to play." is displayed. This makes sense obviously but is misleading to someone not familiar with the backend files and/or meaning of the error.

Few options I could think of to make this easier for the end user:
- clearer error message that there are no files for this season vs unable to find files
- don't allow the play option on a season with no files
- otherwise indicate the season is not playable (greyed out or other indication)

### Reproduction Steps

Only have media for one season available of a series with multiple seasons. All seasons are shown on the series screen. Attempt to play a season with no files.

### Jellyfin Version

10.9.0

### Environment

```markdown
- OS:
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
No errors in Jellyfin log
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by solidsnake1298** [comment]
In the library settings for your shows, do you have the "Missing Episode Fetcher" metadata provider enabled?  This is almost certain the cause of these empty seasons.

**Comment by TheAceMan** [comment]
Thanks, yes I do the Missing Episode Fetcher on. That explains the why the episodes are there as I recently changed some Metadata settings. I do like the episodes showing but wish it was clearer that they were missing so the play functionality/error was handled better. If this is a narrow use case or working as intended feel free to close.

**Comment by solidsnake1298** [comment]
Settings > Display > "Display missing episodes within a season"

Is that checked?
