### ISSUE TITLE
[Issue]: error while playing episode

### ISSUE THREAD

**Issue by QB-Git** [jellyfin/jellyfin#12215]
### Please describe your bug

When I watch an episode I have many issue during playing. It's interrupt with black screen and "Une erreur sur le lecteur est arrivé. Nous allons réessayer" (An error on the player has occurred. We will try again).
It's not a problem of transcoding : no problem with other devices (pc, smartphone) and it's h264.

The problem appeared about 1 year ago. It's maybe the fault of my android tv version (android 10).

Server hardware : AOOSTAR R1
Client hardware : [XGIMI Horizon (videoprojector)](https://fr.xgimi.com/pages/horizon)

My projector soc is a MT9629 https://www.mediatek.com/products/digital-tv/mt9629 capable of decoding pretty much anything.
I think the problem is related to my android version.

The jellyfin version installed of my videoproject is the last : 0.16.11.

### Reproduction Steps

- Have Jellyfin Android tv with android 10 maybe ?
- Run an episode in 1080p .mkv with subtitle

### Jellyfin Version

10.9.0

### if other:

10.9.7

### Environment

```markdown
- OS: OpenMediaVault
- Linux Kernel: Linux openmediavault 6.1.0-21-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.90-1 (2024-05-03) x86_64 GNU/Linux
- Virtualization: Docker
- Clients: Android TV
- FFmpeg Version: ffmpeg version 6.0.1-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
- Playback Method: Direct Stream / Transcode
- Hardware Acceleration: QSV
- GPU Model: Intel(R) N100
- Plugins: none
- Reverse Proxy: none
- Base URL: none
- Networking: Host
- Storage: local
```

### Jellyfin logs

```shell
https://pastebin.com/0pa8gTvP
```

### Please attach any screenshots here

![image](https://github.com/jellyfin/jellyfin/assets/31781028/040b863f-db16-45ca-bd1a-1c2078e8bc95)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
This does not look like an actual Jellyfin bug. Please head to our chat rooms or forum for support. https://jellyfin.org/contact
