### ISSUE TITLE
[Issue]: Black screen when playing "fully compatible media".

### ISSUE THREAD

**Issue by frenchiveruti** [jellyfin/jellyfin#12210]
### Please describe your bug

Hello everyone.

I'm having the following issue:
**When I try to play a specific video file on my Jellyfin server I get a black screen and I can hear audio, but no video.**

I'm running jellyfin on OMV on an i5-4590 with 16GB of RAM.
The JF server is connected directly onto the router via a 1Gbps ethernet cable.
I am using an Onn 4K device on a Samsung TV also 4K, connected via the HDMI provided by the Onn device.
The Onn is connected to my LAN via WiFi (has no ETH port) and running on a 5.8Ghz network.
I am running the latest version of Jellyfin, 10.9.7
The Onn is using v0.16.11

I have a media file that is a REMUX 4K file with the following characteristics for the video:

```
Video
ID                          : 1
ID in the original source m : 4113 (0x1011)
Format                      : HEVC
Format/Info                 : High Efficiency Video Coding
Format profile              : Main 10@L5.1@High
HDR format                  : Dolby Vision, Version 1.0, Profile 7.6, dvhe.07.06, BL+EL+RPU, no metadata compression, Blu-ray compatible / SMPTE ST 2086, Version HDR10, HDR10 compatible
Codec ID                    : V_MPEGH/ISO/HEVC
Duration                    : 1 h 35 min
Bit rate                    : 70.2 Mb/s
Width                       : 3 840 pixels
Height                      : 2 160 pixels
Display aspect ratio        : 16:9
Frame rate mode             : Constant
Frame rate                  : 23.976 (24000/1001) FPS
Color space                 : YUV
Chroma subsampling          : 4:2:0 (Type 2)
Bit depth                   : 10 bits
Bits/(Pixel*Frame)          : 0.353
Stream size                 : 47.0 GiB (82%)
Language                    : English
Default                     : Yes
Forced                      : No
Color range                 : Limited
Color primaries             : BT.2020
Transfer characteristics    : PQ
Matrix coefficients         : BT.2020 non-constant
Mastering display color pri : Display P3
Mastering display luminance : min: 0.0020 cd/m2, max: 1000 cd/m2
Maximum Content Light Level : 10000 cd/m2
Maximum Frame-Average Light : 1578 cd/m2
Original source medium      : Blu-ray
``` 

I would like to know how do I start troubleshooting this, and where can the issue be.
The Jellyfin web admin panel says that the file is being played "natively" with full support

### Reproduction Steps

none, unless you can mirror my exact setup, happy to provide it. 

### Jellyfin Version

10.9.0

### Environment

```markdown
- OS: OMV 7.3.0-3; Debian Sandworm
- Linux Kernel: 6.1.0-22-amd64
- Virtualization: Docker
- Clients: 1
- Browser: Onn 4K JF TV App
- FFmpeg Version: Whatever it's brought with Docker Image
- Playback Method: JF Android App 
- Hardware Acceleration: Yes
- GPU Model: i5-4590 integrated
- Plugins: OpenSubtitles
- Reverse Proxy: no
- Base URL: none
- Networking: Server: eth 1Gbps, host: Wifi 5.8Ghz
- Storage: local
```

### Jellyfin logs

```shell
https://pastie.dev/JoAQ42.applescript
```

### FFmpeg logs

```shell
https://pastie.dev/65cSRN.x86asm
```

### Please attach any screenshots here

![image](https://github.com/jellyfin/jellyfin/assets/1095997/f65e35a8-9e13-41c7-af85-94180255ce64)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by frenchiveruti** [comment]
No ffmpeg log can be attached as the video is played in Direct Playing

**Comment by felix920506** [comment]
Closing invalid report.
External paste services should NOT be used when submitting logs.

**Comment by frenchiveruti** [comment]
> Closing invalid report. External paste services should NOT be used when submitting logs. Please open a new report that follows the instructions on the template.

There's a character limit of 65k on github, how do you suggest I go around that hard-limit?

**Comment by felix920506** [comment]
Upload the file as an attachment
