### ISSUE TITLE
[Issue]: Unicode characters break the song order & jellyfin is unable to play them.

### ISSUE THREAD

**Issue by viasux** [jellyfin/jellyfin#12227]
### Please describe your bug

Unicode characters break the song order & jellyfin is unable to play them. When I remove the unicode characters from the file, it shows up with the correct unicode characters in the webui lol...

### Reproduction Steps

1. have a flac file in an album with unicode characters
2. Try to play it

### Jellyfin Version

10.9.0

### if other:

10.9.7

### Environment

```markdown
- OS: Debian
- Linux Kernel: Latest Stable
- Virtualization: Docker
- Clients: Web
- Browser: Thorium
- FFmpeg Version:
- Playback Method: Web
- Hardware Acceleration: No
- GPU Model: N/A
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
N/A
```

### Please attach any screenshots here

![image](https://github.com/jellyfin/jellyfin/assets/47131867/f4ac3944-8745-4e61-9599-bc5229cfb925)
![image](https://github.com/jellyfin/jellyfin/assets/47131867/1e5a56b0-7391-419a-8872-fc4b4a274cdb)
![image](https://github.com/jellyfin/jellyfin/assets/47131867/d4c31c1b-ec74-424b-bc4e-654ea4ea00dd)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
I have albums with both album names and the track names being mostly non ascii and this isn't happening to me.

**Comment by slickwarren** [comment]
@viasux could you provide the unicode strings from the screenshot for better reproducibility steps?

**Comment by solidsnake1298** [comment]
Is your library on a NAS?  And the share is mounted via SMB?  If so, did you configure the mount to use UTF8?

**Comment by viasux** [comment]
> Is your library on a NAS? And the share is mounted via SMB? If so, did you configure the mount to use UTF8?

rclone & object storage

> @viasux could you provide the unicode strings from the screenshot for better reproducibility steps?

Só Danço Samba (Stereo Version)

**Comment by felix920506** [comment]
unfortunately this seems to be an issue specific to your setup. Please head to our forum or chat rooms for troubleshooting help. https://jellyfin.org/contact
