### ISSUE TITLE
[Issue]: Next Up and Continue Watching Fail to Update for Mixed Libraries

### ISSUE THREAD

**Issue by Orski174** [jellyfin/jellyfin#12225]
### Please describe your bug

When watching or marking stuff as played in the mixed library they show up in the next up or continue watching sections and will stay there until a complete metadata refresh is triggered. Under normal circumstances finishing an episode or movie would remove it from continue watching and next up and put the next episode in its place or remove it completely if the show is finished.

An example:
![image](https://github.com/jellyfin/jellyfin/assets/72353018/e11698de-5550-4ec4-9498-cf8fe35d3fcc)

This started happening in 10.9.4+. I can't really find any logs of interest or a possible cause to this.

### Reproduction Steps

1. Create a Mixed library.
2. Watch something.
3. Check Next up and Continue watching.

### Jellyfin Version

10.9.0

### if other:

10.9.7

### Environment

```markdown
- OS: Debian 12
- Linux Kernel: 6.8.4-3-pve
- Virtualization: Docker
- Clients: Android TV, Web Client, Findroid and Media PLayer for Desktop
- Browser: Firefox
- FFmpeg Version: 6.0.1-Jellyfin
- Playback Method: Client Players + MPV Shim
- Hardware Acceleration: Yes
- GPU Model: iGPU
- Plugins: Shoko
- Reverse Proxy: Traefik
- Base URL: /
- Networking: Traefik Network
- Storage: Mergerfs for Media, NVMe ssd for Jellyfin
```

### Jellyfin logs

```shell
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
Duplicate #12054
