### ISSUE TITLE
10.3.0 /Users/AuthenticateByName is broken

### ISSUE THREAD

**Issue by Tolriq** [jellyfin/jellyfin#1222]
Trying 10.3.0 RC1 and /Users//AuthenticateByName endpoint no more works to authenticate users.

Always returns auth errors with correct credentials (works with previous versions and with Emby)

Probably broken by the internal change to authentification, what is now the proper way to authenticate?

**Comment by cvium** [comment]
How are you authenticating?

**Comment by Tolriq** [comment]
Only prehashed sha256 and md5 ones are supported in the official API.

**Comment by cvium** [comment]
We no longer allow prehashed passwords. The plaintext password must be specified in the `Pw` parameter.

**Comment by Tolriq** [comment]
So 100% not compatible with Emby API, and 100% less secure for all those without Https.

Not sure closing my other issue about Emby compatibility for the future yesterday was nicely timed :p Started promoted Jellyfin as first class in my app then discover it no more works :(

Anyway can you then please ignore the Password and PasswordMd5 field if they are provided with the Pw field to allow authentication, and return a proper error message would be nice too.

**Comment by cvium** [comment]
> 100% less secure for all those without Https

I am not familiar with any API that supports prehashed passwords.

> Anyway can you then please ignore the Password and PasswordMd5 field if they are provided with the Pw field to allow authentication, and return a proper error message would be nice too.

I will discuss this with the team and get back to you. Afaik, those fields are already ignored though.

**Comment by Tolriq** [comment]
The fields are not ignored for sure just tested :)

Emby API did, now it doesn't ;) For this use case this is less secure, not really related to other applications, just a simple fact ;)

Anyway people can always adapt, but if you announce that you keep Emby compatibility for now then it's better to either do or properly announce and document that it's no more the case.

**Comment by joshuaboniface** [comment]
>100% less secure for all those without Https

Sending md5 hashed passwords over HTTP wasn't secure anyways, it's trivial to crack them and has been for years. The fact Emby tried to hide this via "prehashing" is a little disturbing. Nothing is secure over HTTP, at best the hashing was a bit of obfuscation. More evidence of their utter lack of understanding of web security...  The team and I take the opinion that we shouldn't be trying to create the idea that HTTP can be made secure - it can't - and that not using HTTPS and the implications thereof with regards to passwords/etc. over plaintext should be known to the administrators and acknowledged if they don't set up an HTTPS endpoint. The password is going over the wire anyways, whether it's in plain text or a (weak and long-cracked) hashed format really makes little difference from a security perspective.

Now that said, I'm just trying to wrap my head around this so I can provide feedback - I apologize since I haven't used Kodi/Yatse at all with Jellyfin. As I understand it, Yatse just talks to Kodi, and then Kodi is using Jellyfin as a backend, so really it's Kodi that's needing to authenticate correctly, yes? Or is there somewhere inside Yatse that actually requests and obtains the Jellyfin user password, hashes it, then sends it off?

The simplest solution is, if you already have the user's password somehow, just send that as mentioned. Really, whatever is easiest for you is acceptable.

**Comment by Tolriq** [comment]
Yatse is a direct complete client to Jellyfin and Emby and Plex and fully works with them without Kodi.

Supporting streaming/transcoding to any target, offline sync with smart sync and many many other things.

So as a full client I use the whole API directly and did authenticate with the recommended way.

Removing that is breaking API contract and you said you won't.
Yes Emby have many flaws and yes most md5/sha1 can be reversed. But it was here and is no more :)
I have adapted and next version will send only plain text password, but still breaking change and no more Emby compatible.
Since you're no more compatible maybe stop answering to "who is EmbyServer?" As the answer does not yet have indication this is Jellyfin.

**Comment by Tolriq** [comment]
And actually this is worse than just the UDP server that does not identify as Jellyfin but /System/Info/Public (That I currently do not use) also does not have indication that this is an Jellyfin server.

So only /System/Info have the info, but this require authentification that won't work as the consumer can't know it should use the simple password way without a proper error message.

**Comment by anthonylavado** [comment]
>And actually this is worse than just the UDP server that does not identify as Jellyfin but /System/Info/Public (That I currently do not use) also does not have indication that this is an Jellyfin server. ...

@Tolriq We’re looking at this internally right now. We’ll probably finally change this out as a result.

**Comment by Tolriq** [comment]
Thanks.

In all cases a different error message explaining unsupported authentication method would be nice so that consumers have a clue about the real auth issue and can warn user, automatically migrate the host to be a Jellyfin server.

**Comment by Tolriq** [comment]
Any decision made? Would be nice to know that I can warn / migrate users with a way to detect the issue for current users.

**Comment by anthonylavado** [comment]
@tolriq We want to do just about anything you need, or are recommending, so I am working on this today.

To recap, you need/are suggesting:

- [ ] UDP broadcast to only respond to “who is Jellyfin?”
- [ ] “.../system/info/public” to have a product name of “Jellyfin” (like in “.../system/info”

Then -
- [ ] an error message if someone/a client sends a pre-hashed password only? (“Password” and/or “PasswordMd5” only)
- [ ] the app should ignore “Password” and “PasswordMd5” if “pw” is provided (should this also return some type of message?)

**Comment by Tolriq** [comment]
@anthonylavado 

- [ ] UDP broadcast to only respond to “who is Jellyfin?”
Either that or have the returned message containing the product name as for the other end points.
I suppose adding the product name would be less breaking change.

- [ ]  “.../system/info/public” to have a product name of “Jellyfin” (like in “.../system/info”
Yes

- [ ] an error message if someone/a client sends a pre-hashed password only? (“Password” and/or “PasswordMd5” only)

That would be one of the first point too. Currently users in my app are configured as Emby client, without a proper error code, I can't auto migrate them to Jellyfin as 401 could really just be a wrong password. Proper code would be a 405 with clear text message.

- [ ] the app should ignore “Password” and “PasswordMd5” if “pw” is provided (should this also return some type of message?)
This is more a bonus point if you can address at least 1) and 3)

**Comment by dkanada** [comment]
@Tolriq just curious for future reference, do you handle the API for different media servers yourself or do you use provided clients such as Emby.ApiClient.Java? We will possibly heavily modify the API in a single large update in the future, but will update our API clients accordingly. At that point we would also definitely introduce official documentation for it.

**Comment by Tolriq** [comment]
I use my own very optimized code :) 

Yatse is a quite advanced client with different needs than most so would appreciate to be in the loop of the next API definition to be sure I can continue to provide everything to my users efficiently.

Once this is addressed I can provide licences to a few JellyFin devs so they can see why users generally prefer Yatse over official apps.

**Comment by joshuaboniface** [comment]
Should be fixed in 10.3.0 release to specifications requested.
