### ISSUE TITLE
[Issue]: Cannot Edit User on Firefox

### ISSUE THREAD

**Issue by naphipps** [jellyfin/jellyfin#12234]
### Please describe your bug

- Cannot open to edit any user
- Cannot create a user
- Complains that the userId was not provided
- If I try to manage a user's library access, it hangs and does not show my libraries too, but when attempting to add a new user, I can see all my libraries
- I'm thinking maybe when I removed a library, the users got mad somehow

### Reproduction Steps

1. Open Dashboard
2. Go to Users
3. Try to edit

### Jellyfin Version

10.9.0

### if other:

10.9.7

### Environment

```markdown
- OS: debian 12
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
Only logs produced are with React (listed in the browser logs below)
```

### Please attach any browser or client logs here

onmessage http://...:8096/web/7466.bundle.js?3a93c8aa75b061e11b13:2
node_modules.react-dom.bundle.js:2:82220
React Router caught the following error during render Error: Must supply a userId

### Please attach any screenshots here

![screenshot](https://github.com/jellyfin/jellyfin/assets/10482220/548a6808-1de3-40e3-b1df-fe673491de83)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by naphipps** [comment]
Ah, this is firefox (latest)
Now that I try Chrome, it works on Chrome. But this should work on Firefox too.

**Comment by felix920506** [comment]
Please try again in an incognito window.

**Comment by naphipps** [comment]
Incognito works. After that, it seems to now work in the normal too... That's a strange work around.

**Comment by aequis** [comment]
I have this issue as well on Firefox 128 on Windows 11. Using incognito mode doesn't fix it.

**Comment by felix920506** [comment]
anyone with further issues should open an issue on this repo: https://github.com/jellyfin/jellyfin-web
