### ISSUE TITLE
[Issue]: Direct playback of mpeg2 ts (recorded live tv) on Roku Ultra has incorrect duration

### ISSUE THREAD

**Issue by ch6574** [jellyfin/jellyfin#12244]
### Please describe your bug

Live TV recorded via HDHomeRun results in a mpeg2 ts file. Playing this back on a Roku Ultra with the mpeg2 codec enabled now results in direct playback (no transcoding), which is desired. The problem is the duration is wrong during playback, as it show a progress bar with many hours for the recording! Seeking ahead / back in time is also not possible.

Turning off this codec support results in transcoding to HEVC, however the duration is correctly reported and one can seek forwards and backwards.

### Reproduction Steps

1. Enable mpeg2 direct play in the Roku Jellyfin app's codec menu setting.
2. View a recorded live TV show in "recordings" and see a show reporting, say, 29mins. Click play.
3. Observe playback info reports direct play mpeg2video (expected)
4. Observe the seek forward/back progress bar reports recording duration is hours long (unexpected).
5. Observe seeking forwards or backwards in time fails (unexpected).

### Jellyfin Version

10.9.0

### if other:

10.9.7

### Environment

```markdown
- OS: Debian 12
- Linux Kernel: 6.8.8-2-pve
- Virtualization: lxc container
- Clients: Roku Jellyfin 2.0 build 7
- Browser: n/a
- FFmpeg Version: 6.0.1-Jellyfin
- Playback Method: Direct Play
- Hardware Acceleration: QSV
- GPU Model: Intel iHD driver for Intel(R) Gen Graphics - 23.1.1
- Plugins: none
- Reverse Proxy: none
- Base URL: none
- Networking: LAN
- Storage: local
```

### Jellyfin logs

```shell
[2024-07-09 01:50:30.672 +00:00] [INF] User policy for "tv". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
```

### FFmpeg logs

```shell
n/a
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ch6574** [comment]
Adding screenshot to illustrate of a 29min news show:

![dev1](https://github.com/jellyfin/jellyfin/assets/12574127/e1bfa26e-9aae-4373-848a-762da9f19f31)

See the playback time is 596,523 hours!

![dev2](https://github.com/jellyfin/jellyfin/assets/12574127/7dd7d6d9-4fb1-4f0d-9c8c-3388ee654b65)

**Comment by solidsnake1298** [comment]
I am thinking this is expected?  TS files don't have the kind of structure that lends itself to being a good container for storage.  It is a container meant for streaming.

What is the output when you run ffprobe on the TS file.

**Comment by ch6574** [comment]
"Is it expected" is a very good question, and I don't know. I guess why would Jellyfin support such a combination (direct play of a .ts) when it lacks basic features (like rewind), it just seems odd to not enforce a transcode or at least a remux.

ffprobe example:
```
$ ffprobe NBC\ Nightly\ News\ With\ Lester\ Holt\ S10E200.ts                          
ffprobe version 6.0.1-Jellyfin Copyright (c) 2007-2023 the FFmpeg developers                                                                                    
  built with gcc 12 (Debian 12.2.0-14)                                                                                                                          
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable
-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromap
rint --enable-opencl --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --en
able-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --
enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enabl
e-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc                                          
  libavutil      58.  2.100 / 58.  2.100                                                                                                                        
  libavcodec     60.  3.100 / 60.  3.100                                                                                                                        
  libavformat    60.  3.100 / 60.  3.100                                                                                                                        
  libavdevice    60.  1.100 / 60.  1.100                                                                                                                        
  libavfilter     9.  3.100 /  9.  3.100                                                                                                                        
  libswscale      7.  1.100 /  7.  1.100                                                                                                                        
  libswresample   4. 10.100 /  4. 10.100                                                                                                                        
  libpostproc    57.  1.100 / 57.  1.100                                                                                                                        
[mpeg2video @ 0x591ba8e54cc0] Invalid frame dimensions 0x0.                                                                                                     
    Last message repeated 46 times                                                                                                                              
[mpegts @ 0x591ba8e4edc0] PES packet size mismatch                                                                                                              
[mpegts @ 0x591ba8e4edc0] Packet corrupt (stream = 1, dts = 2055117712).                                                                                        
[mpegts @ 0x591ba8e4edc0] PES packet size mismatch                                                                                                              
[mpegts @ 0x591ba8e4edc0] Packet corrupt (stream = 2, dts = 2055132112).                                                                                        
Input #0, mpegts, from 'NBC Nightly News With Lester Holt S10E200.ts':                                                                                          
  Duration: 00:29:59.40, start: 21036.081244, bitrate: 6523 kb/s
  Program 1 
  Stream #0:0[0x71]: Video: mpeg2video (Main) ([2][0][0][0] / 0x0002), yuv420p(tv, top first), 1920x1080 [SAR 1:1 DAR 16:9], Closed Captions, 29.97 fps, 29.97 tbr, 90k tbn
    Side data:
      cpb: bitrate max/min/avg: 17598000/0/0 buffer size: 7995392 vbv_delay: N/A
  Stream #0:1[0x74](eng): Audio: ac3 ([129][0][0][0] / 0x0081), 48000 Hz, 5.1(side), fltp, 384 kb/s
  Stream #0:2[0x75](spa): Audio: ac3 ([129][0][0][0] / 0x0081), 48000 Hz, stereo, fltp, 192 kb/s
```

**Comment by solidsnake1298** [comment]
What if someone doesn't have the ability to transcode?  Hard coding that TS containers must be transcoded would break things for a lot of people on weaker systems.  Its always better to make transcoding/remuxing an option.

You could setup a post-recording script to remux the videos yourself.

```ffmpeg -fflags +genpts -i "{path}" -map 0 -codec copy new_file.mkv```

Something like that.  I don't record live TV, but I know you can post process the recordings.

**Comment by ch6574** [comment]
Here's my observations so far:

| # | Recording Codec | Recording Container| Roku Codecs |  Playback|
| -- | -- | -- | -- | --|
|1 | mpeg2 | ts | mpeg2 on<br/>hevc on | Direct Play :white_check_mark: , no ability to seek / bad time data :x: |
| 2 |  mpeg2 | mkv (remux 1) | mpeg2 on<br/>hevc on | Direct Play :white_check_mark:, with ability to seek :white_check_mark:|
|3 | mpeg2 | ts | mpeg2 off<br/>hevc on | Transcode to hevc :x:, with ability to seek :white_check_mark:|
| 4 |  mpeg2 | mkv (remux 1)  | mpeg2 off<br/> hevc on | Transcode to hevc :x:, remux back to .ts :question: , ability to seek :white_check_mark:|

Thus:

- ts+mpeg2 is problematic (item 1), but transcode to ts+hevc (item 3 & 4) is not.
- mkv+mpeg2 (item 2) is the best, but it's only available after a recording has completed once the post processing remux runs. Joining a live broadcast (like a sports game) means no ability to seek.
- Transcodes work, but should be unnecessary.

What I don't yet fully understand is why changing the video codec via a transcode, but still using the same ts container works. Maybe the original .ts is corrupted somehow, and the transcodes ones are good??

**Comment by gnattu** [comment]
Force transcode/remux for mpegts is extremely not feasible because the source file could be in a state that change a container will  cause desynced audio and video

**Comment by ch6574** [comment]
I can see that a remux on an active recording is a wild idea. :smile: 

So what I'm left thimking is either **[a]** the original recording is somehow broken (and is fixed via either a transcode or a remux) or **[b]** the Roku client has some kind of bug when in direct play mode.

**Comment by ch6574** [comment]
I've made a simple reproducer example here to further zoom in on the issue. Create two 10 second test files as follows:
```
ffmpeg -f lavfi -i "testsrc=duration=10:size=1920x1080" -c:v libx264 -pix_fmt yuv420p test_01.ts
ffmpeg -f lavfi -i "testsrc=duration=10:size=1920x1080" -c:v libx264 -pix_fmt yuv420p test_02.mkv
```
Then play them back via Firefox, Android, and Roku clients:

| Test | Firefox | Android | Roku |
| -- | -- | -- | -- |
| test_01 (h264 in a ts) | Direct Play :white_check_mark:  | Direct Play :white_check_mark:  | Direct Play, no seek/skip, shows 5h 45min long :x: |
| test_02 (h264 in a mkv) | Direct Play :white_check_mark:  | Direct Play :white_check_mark:  | Direct Play :white_check_mark:  |

So this bug report is ultimately about the problem test case above of the Roku client unable to handle a ts container the same way the other Jellyfin clients do.
