### ISSUE TITLE
[Issue]: Movies and Shows handle single letter subdirectories differently

### ISSUE THREAD

**Issue by reavessm** [jellyfin/jellyfin#12250]
### Please describe your bug

Movies that follow the structure of `/movies/A/A Movie ...` show up correctly as `A Movie` but shows following the structure of `/tvshows/A/A Show ...` do not.  They instead pick a unrelated show that starts with the letter and mark all subdirectories as seasons of the random show.  For instance, `/tvshows/A/Akame ga Kill` and `/tvshows/A/Adventure Time` are listed as seasons of `Alarm fur Cobra 11`, which does not actually exist on its own.

### Reproduction Steps

1. Have already configured movies and shows as toplevel directories under the root dirs
2. Have Sonarr/Radarr rename series folders from `{Series Title}` -> `{Series TitleFirstCharacter}/{Series Title}`
3. Rescan libraries
4. Enjoy movies but not shows

### Jellyfin Version

10.9.0

### if other:

10.9.7

### Environment

```markdown
- Virtualization: Docker (OpenShift)
- FFmpeg Version: 6.0.1-Jellyfin
- Storage: NFS
```

### Jellyfin logs

```shell
[12:31:54] [INF] [28] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/tvshows/N/Naruto/S1E19.mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
[12:31:55] [ERR] [32] Jellyfin.Plugin.Tvdb.Providers.TvdbEpisodeProvider: Episode S01E19 not found for series 0:S1E19
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felix920506** [comment]
Please follow the folder structure in the documentation. https://jellyfin.org/docs/general/server/media/shows
