### ISSUE TITLE
Finding external audio from included folders

### ISSUE THREAD

**Issue by Guru1-228** [jellyfin/jellyfin#12262]
I have a lot of TV shows with voiceovers in external files. These voiceovers are always located in nested directories. Jellyfin does not look into them, but searches next to the video. This forces me to either make redundant copies of the file or change the distribution structure.

Examlpe structure:
```
/Serials
    /Serial 1
        Season 1/
            Episode 1.mkv
            Episode 2.mkv
            /audio
                Episode 1.mka
                Episode 2.mka
```

**Comment by crobibero** [comment]
This is a feature request, and should be posted to https://features.jellyfin.org/
