### ISSUE TITLE
[Issue]: GET `/Items/{itemId}` API documentation is incorrect

### ISSUE THREAD

**Issue by CollinHeist** [jellyfin/jellyfin#12260]
### Please describe your bug

I am attempting to verify an item ID is valid by using the `GET` `/Items/{itemId}` API endpoint, and all queries to the endpoint are returning a 405 (Method Not Allowed) error. This occurs with valid and invalid IDs.

I have been referring to the [API Docs](https://api.jellyfin.org/), which shows `itemId` is a required path parameter, and userId is an optional query parameter. However, from [this thread](https://forum.jellyfin.org/t-solved-api-running-into-an-error-when-attempting-to-get-details-for-item-id) it looks like the endpoint must be prefixed by `/User/{userId}/` - which is not reflected in the API docs.

---

I would expect this endpoint to either return 404 if the provided itemID does not correspond to a valid item; a 200 return if it does; or the documentation to reflect that the `userId` paramter is a required path argument.

### Reproduction Steps

1. Grab the item ID of an episode/series from the web UI (I have also used ones returned via the `/Items` endpoint)
   ![Screenshot 2024-07-11 at 6 35 43 PM](https://github.com/user-attachments/assets/f7538035-2cd9-4032-8cd1-7106c535433d)

2. Submit the GET request:
    ```bash
    curl -v -X GET \
      'http://192.168.0.29:8097/Items/3999183b023f6d0a764b12ae218ccc30' \
      -H 'Authorization: MediaBrowser Token="my token"'
    ```

3. Observe the 405 response:
    ```bash
    *   Trying 192.168.0.29:8097...
    * Connected to 192.168.0.29 (192.168.0.29) port 8097
    > GET /Items/3999183b023f6d0a764b12ae218ccc30 HTTP/1.1
    > Host: 192.168.0.29:8097
    > User-Agent: curl/8.4.0
    > Accept: */*
    > Authorization: MediaBrowser Token="..."
    > 
    < HTTP/1.1 405 Method Not Allowed
    < Content-Length: 0
    < Date: Fri, 12 Jul 2024 00:42:09 GMT
    < Server: Kestrel
    < Allow: DELETE, POST
    < X-Response-Time-ms: 6121
    < 
    * Connection #0 to host 192.168.0.29 left intact
    ```
    
4. Make the request with the /Users/ prefix
    ```bash
    curl -v -X GET \
      'http://192.168.0.29:8097/Users/abcdef/Items/3999183b023f6d0a764b12ae218ccc30' \
      -H 'Authorization: MediaBrowser Token="my token"'
    ```
5. Observe the correct non-405 response

### Jellyfin Version

10.8.12 or older (please specify)

### if other:

10.8.10

### Environment

```markdown
- OS: Unraid (docker)
- Linux Kernel: Not sure
- Virtualization: Docker
- Clients: N/A (browser)
- Browser: N/A Firefox
- FFmpeg Version:  N/A
- Playback Method: N/A
- Hardware Acceleration: N/A
- GPU Model: None
- Plugins: None
- Reverse Proxy: N/A
- Base URL: N/A
- Networking: N/A
- Storage: N/A
```

### Jellyfin logs

```shell
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
The `/Users/{userId}/` endpoints were deprecated and hidden.

The curl command worked fine for me
```
 curl -v -X GET https://jellyfin.domain.tld/Items/f25016c0ac9a5abf65c43e0f9d4f52a7 -H 'Authorization: MediaBrowser Token="xxxxxxxxxxxxxxxxxxxxxxxxxx"'
Note: Unnecessary use of -X or --request, GET is already inferred.
* Host jellyfin.domain.tld:443 was resolved.
* IPv6: (none)
* IPv4: x.x.x.x
*   Trying x.x.x.x:443...
* Connected to jellyfin.domain.tld (x.x.x.x) port 443
* schannel: disabled automatic use of client certificate
* ALPN: curl offers http/1.1
* ALPN: server accepted http/1.1
* using HTTP/1.x
> GET /Items/xxxxxxxxxxxxxxxxxxxxxx HTTP/1.1
> Host: jellyfin.domain.tld
> User-Agent: curl/8.7.1
> Accept: */*
> Authorization: MediaBrowser Token="xxxxxxxxxxxxxxxxxxxxxxxxxx"
>
* Request completely sent off
* schannel: remote party requests renegotiation
* schannel: renegotiating SSL/TLS connection
* schannel: SSL/TLS connection renegotiated
< HTTP/1.1 200 OK
< Alt-Svc: h3=":443"; ma=2592000
< Content-Type: application/json; charset=utf-8
< Date: Fri, 12 Jul 2024 00:55:30 GMT
< Server: Caddy
< Server: Kestrel
< X-Response-Time-Ms: 5.344
< Transfer-Encoding: chunked
```

**Comment by CollinHeist** [comment]
When were they deprecated?

**Comment by crobibero** [comment]
For 10.9

https://github.com/jellyfin/jellyfin/issues/11074

**Comment by nielsvanvelzen** [comment]
You're trying to use a 10.9 endpoint with 10.8.

**Comment by CollinHeist** [comment]
I thought that as well, based on what crobibero said, but it looks like using the "old" endpoint still doesn't work; and the "new" one does not work after updating the server to 10.9. I'm trying to do some further searching

**Comment by CollinHeist** [comment]
Okay I updated my server to 10.9.7

![Screenshot 2024-07-12 at 6 10 11 PM](https://github.com/user-attachments/assets/227a0af8-526f-4eec-823f-495a6f7a4108)

and tried the request again:

```sh
curl -v -X GET http://192.168.0.29:8097/Items/3999183b023f6d0a764b12ae218ccc30 -H 'Authorization: MediaBrowser Token="xxx"'
```

And now receive a 400 request.

```bash
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 192.168.0.29:8097...
* Connected to 192.168.0.29 (192.168.0.29) port 8097
> GET /Items/3999183b023f6d0a764b12ae218ccc30 HTTP/1.1
> Host: 192.168.0.29:8097
> User-Agent: curl/8.4.0
> Accept: */*
> Authorization: MediaBrowser Token="xxx"
> 
< HTTP/1.1 400 Bad Request
< Content-Type: text/plain
< Date: Sat, 13 Jul 2024 00:02:20 GMT
< Server: Kestrel
< Transfer-Encoding: chunked
< X-Response-Time-ms: 1.5868
< 
* Connection #0 to host 192.168.0.29 left intact
Error processing request.%
```

The deprecated endpoint does work, but to use the new endpoint I needed to add `userId` as a query parameter.

```sh
curl -v -X GET 'http://192.168.0.29:8097/Items/3999183b023f6d0a764b12ae218ccc30?userId=xxx' -H 'Authorization: MediaBrowser Token="xxx"'
```

**Comment by crobibero** [comment]
The endpoint is user specific, so if you're using an api key you need to provide the user id.

**Comment by CollinHeist** [comment]
@crobibero That makes sense, thanks. Looks like the OpenAPI spec should be updated to indicate that argument is required

![Screenshot 2024-07-12 at 8 24 42 PM](https://github.com/user-attachments/assets/28482180-8f60-4bac-9239-9b84afb61bc7)

And I was referring to your [original comment](https://github.com/jellyfin/jellyfin/issues/12260#issuecomment-2224232834) in which you _did not_ include a userId but _did_ receive a valid response.

**Comment by crobibero** [comment]
The userId parameter isn't required when using a user token, which is how I tested the endpoint

The docs could probably be updated to state that the parameter is required when using an api key. Updating the docs would apply to a handful of endpoints that were recently added

**Comment by CollinHeist** [comment]
Oh that makes sense - thanks for clarifying. I am using an normal API key generated through the UI.

I agree updating the docs would be very helpful 👍🏻 If you'd like I can poke around the repo and submit a PR.

**Comment by cco** [comment]
Confirming undocumented behavior of API. The userId variable seems required to authorize against the universal endpoint, in addition to using an API key in env.
