### ISSUE TITLE
[Issue]: mp4 file downloaded when disable "Allow media downloads" in user profile,  playing mp4-file on chrome-android 

### ISSUE THREAD

**Issue by shoeychi** [jellyfin/jellyfin#12264]
### Please describe your bug

mp4 file was downloaded when disable "Allow media downloads" in user profile,  playing mp4-file on chrome-android.

mkv,flv files cannot be downloaded.

### Reproduction Steps

1. log in jellyfin on chrome-android
2. open in mp4 video file,(if other extension video file, e.g.: mkv video fie cannot be downloaded )
3. you will see the floating tab which has a "download" button.
4. download the current playing file which named "steam.mp4" 

### Jellyfin Version

10.9.0

### Environment

```markdown
- Jellyfin 10.9.7 docker on a synology NAS
- Clients: Android
- Browser: Chrome
- FFmpeg Version: ffmpeg version 6.0.1-Jellyfin
- Playback Method: Transcoding
- Hardware Acceleration: No
- Plugins: None
- Reverse Proxy: None
```

### Jellyfin logs

```shell
no logs
```

### FFmpeg logs

```shell
none
```

### Please attach any screenshots here

![WechatIMG213](https://github.com/user-attachments/assets/9ac22f26-0cb6-48d4-ae9d-4499dae587e2)
![WechatIMG214](https://github.com/user-attachments/assets/019e2437-4ff0-4ae8-afd4-9d0fce2925d2)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
There isn't anything we can do about that. That is your browser directly downloading the video stream.

**Comment by shoeychi** [comment]
how  does the browser  know the download link ? the jellyfin provides download link, leading to download "steam.mp4"

**Comment by shoeychi** [comment]
Huawei Broswer also has the same problem

**Comment by felix920506** [comment]
The browser has the link because it needs the link in order to play the video.

It isn't necessarily downloading the source file, it can only download the stream that is sent to the client for playback and nothing else.

**Comment by gnattu** [comment]
Technically as long as a browser can play a video it can download it. You have to send the video in some form to the client for it to be played. That's why DRM is a thing to make sure even if you downloaded that it will be non-playable trash. But adding DRM to jellyfin is out of scope.
