### ISSUE TITLE
IPTV Channel Groupings

### ISSUE THREAD

**Issue by kinv** [jellyfin/jellyfin#1227]
**Is your feature request related to a problem? Please describe.**

Currently Jellyfin does not support grouping channels, when you add a playlist it is just one big list of channels.
**Describe the solution you'd like**

I would love it if Jellyfin supported groupings. Most if not all iptv providers have channels grouped and works in iptv apps with the use of m3u_plus.

**Describe alternatives you've considered**
N/A
**Additional context**
Great job on Jellyfin, keep up the good work!

**Comment by groenator** [comment]
I can't wait for this feature to be implemented. It will make a big difference to jellyfin.

**Comment by kinv** [comment]
Yeah will be awesome to just be able to use one app for everything. Don't think it will be a priority, Devs have a long to do list I think. But don't ask don't get lol. Wish I had the knowledge to help out.
