### ISSUE TITLE
[Issue]: Localisation of "default" metadata flag in Audio/Subtitle track selector

### ISSUE THREAD

**Issue by jmercz** [jellyfin/jellyfin#12276]
### Please describe your bug

This issue is based on the closing recommendation of issue #12272 to split the described problems into separate issues, namely recommendation 1. Feel free to have a look into said issue, as it might give a better complete picture of the problems in the track selector.

This issue focuses on the localisation of the "default" flag, that is apparently handled differently for the audio and the subtitle track respectively.

### Reproduction Steps

With an audio track and a subtitle track both with the _default_ flag set and the following localisation options:
- Administration > Dashboard > General > Preferred display language: Deutsch [German]
- User > Settings > Display > Display language: Deutsch [German]

the track selector looks as follows:
![3_server-de_gui-de_environment-en](https://github.com/user-attachments/assets/ddffba67-1856-4935-9c87-d7808b3029c2)
The _default_ flag is localised to the preferred language in the subtitle ["Untertitel"] track selector (reading "Standard"). Contrary, the audio selector **is not localised** (still English, reading "Default"). The expected behaviour would be that both _default_ flags are localised according to the localisation setting.

The example given is for German, but should be reproducable for any language by changing the server wide preferred language under Administration > Dashboard > General > Preferred display language.

### Jellyfin Version

10.9.0

### Environment

```markdown
- OS: DSM 7.2.1-69057 Update 5
- Linux Kernel: unknown
- Virtualization: Docker
- Clients: universal
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
No actions are taken, thus no log file should be of any use here.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Bond-009** [comment]
Fixed by #12278
