### ISSUE TITLE
Syncs Lyrics Not Properly Parsed When TimeStamp is in [mm:ss.xxx] Format

### ISSUE THREAD

**Issue by Reapor-Yurnero** [jellyfin/jellyfin#12273]
**Describe The Bug**
Syncs Lyrics Not Properly Parsed When TimeStamp is in [mm:ss.xxx] Format. The only supported format is [mm:ss.xx]. But indeed a whole lot of LRC files in the wild is [mm:ss.xxx] or even something else. 

**Steps To Reproduce**
1. Create an LRC file with timestamp in [mm:ss.xxx] format
2. Play this song and show lyrics.

**Expected Behavior**
[mm:ss.xxx] timestamps should be parsed just like [mm:ss.xx] format as legit timestamps.

**Screenshots**
![image](https://github.com/user-attachments/assets/fb32c74c-e552-4cb4-bb94-7a19599454e3)

**System (please complete the following information):**
 - Platform: Windows
 - Browser: Chrome
 - Jellyfin Version: 10.9.7

**Additional Context**
This exact issue was also seen in navidrome which suppoted lyrics showing a bit earlier in late 2023. 
Check this [PR ](https://github.com/navidrome/navidrome/pull/2368) and the actual [PR](https://github.com/navidrome/navidrome/pull/2656) that fixed it. Seems to be a easy and straight-forward fix.

I suppose this is something done in the frontend side in Jellyfin. But let me know if this is wrong and I can repost in the core repo.

**Comment by Bond-009** [comment]
Duplicate https://github.com/jellyfin/jellyfin/issues/11518
