### ISSUE TITLE
Jellyfin updates keep resetting permissions when running as user other than "jellyfin"

### ISSUE THREAD

**Issue by zerbey** [jellyfin/jellyfin#12298]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

I'm using a custom username (let's call it fred) to run the Jellyfin server as it shares media directories with another program (let's call it George the Media program).  No issues until I update jellyfin, which resets all of its directories back to the jellyfin user and then fails to start.  Manually reverting everything back fixes the issue.

### Reproduction steps

Confirmed on stable and unstable on Ubuntu/Debian.  Running an update resets permissions on all working directories to a user name "jellyfin" even if a custom user is set.  

### What is the current _bug_ behavior?

Jellyfin fails to start with permissions issues.

### What is the expected _correct_ behavior?

Jellyfin should allow custom users to run and honor that configuration when upgrading.

Unless this is a design decision, then please mark as such and it needs to be a documentation rather than functionality bug. 

### Jellyfin Server version

Unstable

### Specify unstable release number

2024071505

### Specify version number

10.10.0

### Specify the build version

10.10.0

### Environment

```markdown
- OS: Ubuntu 22.04
- Linux Kernel: 5.15.0-116
- Virtualization: N/A
- Clients: N/A
- Browser: N/A
- FFmpeg Version: 6.0.1-Jellyfin
- Playback Method: Web
- Hardware Acceleration: nvenc
- GPU Model: Quadro P620
- Plugins: TheTVDB_13.0.0.0
- Reverse Proxy: N/A
- Base URL: http://[local IP censored]:8096/web/#/home.html
- Networking: Host
- Storage: NFS
```

### Jellyfin logs

```shell
Jul 17 12:44:05 larry jellyfin[4297]: Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 8: 'attempt to write a readonly database'.
Jul 17 12:44:05 larry jellyfin[4297]:    at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
Jul 17 12:44:05 larry jellyfin[4297]:    at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
Jul 17 12:44:05 larry jellyfin[4297]:    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
Jul 17 12:44:05 larry jellyfin[4297]:    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
Jul 17 12:44:05 larry jellyfin[4297]:    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
Jul 17 12:44:05 larry jellyfin[4297]:    at Emby.Server.Implementations.Data.SqliteExtensions.Execute(SqliteConnection sqliteConnection, String commandText)
Jul 17 12:44:05 larry jellyfin[4297]:    at Emby.Server.Implementations.Data.ManagedConnection.Execute(String commandText)
Jul 17 12:44:05 larry jellyfin[4297]:    at Emby.Server.Implementations.Data.BaseSqliteRepository.Initialize()
Jul 17 12:44:05 larry jellyfin[4297]:    at Emby.Server.Implementations.Data.SqliteItemRepository.Initialize()
Jul 17 12:44:05 larry jellyfin[4297]:    at Emby.Server.Implementations.ApplicationHost.InitializeServices()
Jul 17 12:44:05 larry jellyfin[4297]:    at Jellyfin.Server.Program.StartServer(IServerApplicationPaths appPaths, StartupOptions options, IConfiguration startupConfig)
Jul 17 12:44:05 larry jellyfin[4297]: [12:44:05] [INF] Running query planner optimizations in the database... This might take a while
Jul 17 12:44:05 larry jellyfin[4297]: [12:44:05] [INF] Disposing CoreAppHost
Jul 17 12:44:05 larry jellyfin[4297]: [12:44:05] [INF] Disposing PluginManager
Jul 17 12:44:05 larry systemd[1]: jellyfin.service: Deactivated successfully.
```

**Comment by solidsnake1298** [comment]
I seriously doubt this behavior is going to change when upgrading.

But, there is a cleaner way to resolve this.  Instead of changing the user Jellyfin runs as, you should create a new group.  Then add the jellyfin user and the user for this other program to this new group.  Set this new group as the owner of the shared files/folders.
