### ISSUE TITLE
Home screen same for all users ("Continue watching..." shows other user's activity)

### ISSUE THREAD

**Issue by Mugane** [jellyfin/jellyfin#12290]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

The first home screen "Continue watching..." shows other user's activity.

I created a new install with latest version on Windows 11 pro (Jellyfin Server 10.9.7). I created two non-admin users without passwords and proceeded to watch content with one of the accounts. That was yesterday. Today I logged out of that user and logged in as the other user to see if they could access all the media and I was greeted with a home screen that shows MY watch history (the watch history of the first user). This utterly defeats the purpose of having users to begin with.  Logging in as the second user from a different browser shows "up next" without the watch history of the first user (probably the expected behavior). So it sounds like there is an issue removing session/state information when switching users on the same device (at least when there is no watch history present for the second user).

### Reproduction steps

See description.

### What is the current _bug_ behavior?

See description

### What is the expected _correct_ behavior?

Each user sees their own watch history only! New users do not see any watch history.

### Jellyfin Server version

10.9.7

### Specify the build version

10.9.7

### Environment

```markdown
- OS: Windows 11 Pro
- Linux Kernel: NA
- Virtualization: Enabled, hardware
- Clients: web
- Browser: N/A All of them
- FFmpeg Version: unknown/irrelevant
- Playback Method: unknown/irrelevant
- Hardware Acceleration: unknown/irrelevant
- GPU Model: unknown/irrelevant
- Plugins: AudioDB 10.9.7.0, Discogs 1.0.0.0, MusicBrainz 10.9.7.0, NextPVR 11.0.0.0, OMDb 10.9.7.0, Studio Images 10.9.7.0, TMDb 10.9.7.0, TVHeadend 12.0.0.0
- Reverse Proxy: No
- Base URL: Not relevant/will not disclose.
- Networking: LAN
- Storage: NA
```

### Jellyfin logs

```shell
Won't share for privacy reasons.
```

### FFmpeg logs

```shell
N/A
```

### Client / Browser logs

N/A

### Relevant screenshots or videos

N/A

**Comment by felix920506** [comment]
Duplicate of https://github.com/jellyfin/jellyfin-web/issues/5615

**Comment by Mugane** [comment]
Sorry guys, duplicate didn't show up in my search.
