### ISSUE TITLE
Option to choose transcoding codec

### ISSUE THREAD

**Issue by ahizap** [jellyfin/jellyfin#12308]
Jellyfin supports HEVC and AV1 Transcoding but still defaults to H 264 all the time even though I am using the desktop client which supports HEVC. There should be an option to choose a preferred codec for transcoding in the settings.

**Comment by gnattu** [comment]
What you said does not reflect what the server actually does. You need to tell us more info.

**Comment by ahizap** [comment]
I have enabled "allow encoding in HEVC format" but when I play something and it's not playing in "Direct" jellyfin is still transcoding in H264 and not HEVC

![image](https://github.com/user-attachments/assets/79fb6449-1672-49a1-9733-29d49b35a8d9)

**Comment by gnattu** [comment]
Why you are not filing our github issue template providing logs, especially the transcoding logs? I can get nothing from your picture.

**Comment by gnattu** [comment]
Before wasting eveybody's time, if you go to settings->client settings in JMP, these options are enabled right?

<img width="874" alt="image" src="https://github.com/user-attachments/assets/64da1ea0-46e8-483d-8ca1-87cf6810ac33">

**Comment by ahizap** [comment]
My bad, never saw those settings. Thanks @gnattu it's working now I'm closing the issue
