### ISSUE TITLE
Multi-Resolution IPTV Streams Within Nested M3U's Not switching to higher resolution streams.

### ISSUE THREAD

**Issue by ctdgunner** [jellyfin/jellyfin#12307]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

It is quite common for m3u playlist of IPTV streams to be a collection of multiple master m3u's that have within them multiple resolutions of the same stream. Here is an example this is the URL for the Vevo Pop stream from SamsungTVPlus `https://jmp2.uk/SamsungTVPlus/USBC3600008WY.m3u8` the actual contents of this ".m3u8" file look exactly like this:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-MEDIA:LANGUAGE="en",AUTOSELECT=YES,FORCED=NO,INSTREAM-ID="CC1",TYPE=CLOSED-CAPTIONS,GROUP-ID="cc",DEFAULT=YES,NAME="English"
#EXT-X-STREAM-INF:CODECS="avc1.4d401e,mp4a.40.2",AVERAGE-BANDWIDTH=813600,RESOLUTION=640x360,FRAME-RATE=29.97,BANDWIDTH=1057680,CLOSED-CAPTIONS="cc"
../../../manifest/3722c60a815c199d9c0ef36c5b73da68a62b09d1/cc-shs19slqofvwj-ssai-prd/83ceee11-e521-4d92-957f-e1ebb3e00f93/0.m3u8
#EXT-X-STREAM-INF:CODECS="avc1.64001f,mp4a.40.2",AVERAGE-BANDWIDTH=1757200,RESOLUTION=848x480,FRAME-RATE=29.97,BANDWIDTH=2284360,CLOSED-CAPTIONS="cc"
../../../manifest/3722c60a815c199d9c0ef36c5b73da68a62b09d1/cc-shs19slqofvwj-ssai-prd/83ceee11-e521-4d92-957f-e1ebb3e00f93/1.m3u8
#EXT-X-STREAM-INF:CODECS="avc1.64001f,mp4a.40.2",AVERAGE-BANDWIDTH=3440800,RESOLUTION=1280x720,FRAME-RATE=29.97,BANDWIDTH=4473040,CLOSED-CAPTIONS="cc"
../../../manifest/3722c60a815c199d9c0ef36c5b73da68a62b09d1/cc-shs19slqofvwj-ssai-prd/83ceee11-e521-4d92-957f-e1ebb3e00f93/2.m3u8
#EXT-X-STREAM-INF:CODECS="avc1.640028,mp4a.40.2",AVERAGE-BANDWIDTH=5640800,RESOLUTION=1920x1080,FRAME-RATE=29.97,BANDWIDTH=7333040,CLOSED-CAPTIONS="cc"
../../../manifest/3722c60a815c199d9c0ef36c5b73da68a62b09d1/cc-shs19slqofvwj-ssai-prd/83ceee11-e521-4d92-957f-e1ebb3e00f93/3.m3u8
```

Now the issue here is truly I'd like to watch that HD stream listed last. And putting that original stream's URL in VLC will let me do that, it actually starts with the first one at a lower quality and then works its way up the chain if there is enough bandwidth. But Jellyfin doesn't do this, Jellyfin just loves that SD stream (or whichever one is listed first I think..)

### Reproduction steps

1. Sign into Jellyfin Web Client (version 10.9.7)
2. Navigate to Live TV (with M3U already configured ready to watch)
3. Watch a channel that has this multi resolution setup in a nested m3u.
4. Enjoy Standard Def Stream with a smile :)

### What is the current _bug_ behavior?

Currently it is not allowing me to watch (in this example shown above) the 1080p stream only the 360p stream. (I highly believe it is due to it appearing first in the nested m3u.)
[Log.txt](https://github.com/user-attachments/files/16318855/Log.txt)
[FFmpegLog.txt](https://github.com/user-attachments/files/16318856/FFmpegLog.txt)

### What is the expected _correct_ behavior?

1. Sign into Jellyfin Web Client (version 10.9.7) (or version 10.9.8 hopefully, since this is a very very important fix *wink* *wink*)
2. Navigate to Live TV (with M3U already configured ready to watch)
3. Watch a channel that has this multi resolution setup in a nested m3u.
4a. Enjoy he ability to select and watch a higher quality stream from the quality selector within the player (at all bitrates that are available)
or 4b. Start with an SD stream and watch as it improves to have more pixels than you know what to do with (1080p in this example with Vevo Pop shown above.)

### Jellyfin Server version

10.9.7

### Specify the build version

Release

### Environment

```markdown
- OS: Unraid 6.9.2
- Linux Kernel: Linux 5.10.28-Unraid x86_64
- Virtualization: Not really... Docker (Container ID: 8a32e56ddc21 | By: binhex/arch-jellyfin)
- Clients: n/a?
- Browser: Chrome 126.0.6478.182
- FFmpeg Version:
- Playback Method: Web Version 10.9.7
- Hardware Acceleration: Unknown
- GPU Model: None on server 3070 on client
- Plugins: AudioDB10.9.7.0,FinTube1.0.0.0,InPlayerEpisodePreview1.2.1.0,Intro Skipper0.2.0.12,MusicBrainz10.9.7.0,OMDb10.9.7.0,Open Subtitles20.0.0.0,Studio Images10.9.7.0,TMDb10.9.7.0,TMDb Trailers13.0.0.0
- Reverse Proxy: Not Currently In Use
- Base URL: local IP not shared out of network using any method currently
- Networking: Undaid Docker Bridge Network
- Storage: Local Unraid Pool, non-ZFS
```

### Jellyfin logs

```shell
Uploaded file under "What is the current _bug_ behavior?" Question
```

### FFmpeg logs

```shell
Uploaded file under "What is the current _bug_ behavior?" Question
```

**Comment by crobibero** [comment]
This is a feature request and should be directed here: https://features.jellyfin.org/
