### ISSUE TITLE
'tvg-chno=' tag not assigning channel numbers

### ISSUE THREAD

**Issue by rizzle95** [jellyfin/jellyfin#1230]
**Describe the bug**
`tvg-chno=` will not assign channel numbers.

**To Reproduce**

Each stream in the m3u file is in this format:

`#EXTINF:-1 tvg-chno="14" tvg-name="1080p" tvg-logo="C:\Users\Rizzle\Desktop\IPTV\logos\Sport 2 HD.png" group-title="1080",BT Sports 2 HD 1080p
http://myiptvprovider.com:80/Username/Password!!/375`

The number at the end of the www link is what jellyfin uses to assign the channel number

The only way I have been able to get jellyfin to not use the number at the end of the stream link is to use this format in the m3u file:

`#EXTINF:-1 tvg-name="1080p" tvg-logo="C:\Users\Rizzle\Desktop\IPTV\logos\Sport 2 HD.png" group-title="1080",BT Sports 2 HD 1080p`
`tvg-chno="14"`
`http://myiptvprovider.com:80/Username/Password!!/375`

However, when i have it formatted like this, FFmpeg returns an error code 1.

No matter where I place the `tvg-chno=` tag, the streams are always numbered by the number at the end of their relevant web address 

**Expected behavior**
By using the `tvg-chno=` tag, I expected Jellyfin the assign the value of that tag to the channel number of that stream

**Logs**

**Screenshots**

**System (please complete the following information):**
 - Browser: OS: Windows 10
 - Chrome
 - Jellyfin Version: 10.2.2
 - Reverse proxy: no

**Comment by fruhnow** [comment]
I tested this using the example line you have given and it worked straight away if you use correct M3U-Format. Everything except the link `http://myiptvprovider.com:80/Username/Password!!/375` has to be placed in one line with `#EXTINF:`

So using your example provided a correct formatting would look like this:

`#EXTINF:-1 tvg-chno="14" tvg-name="1080p" tvg-logo="Logo.png" group-title="1080",BT Sports 2 HD 1080p`
`http://myiptvprovider.com:80/Username/Password!!/375`

I tested this using the latest master.

**Comment by rizzle95** [comment]
Thanks for your effort mate!
I tested using the example you provided and I am still experiencing the same issue.

I have found that if I add a '?' to the end of the stream link, jellyfin will play the stream and ignores the number.

**Comment by fruhnow** [comment]
> Thanks for your effort mate!

You are very welcome!

I only examined the channel-number problem (which i couldn't reproduce sadly) as i can't test stuff regarding playback apart from in combination tvheadend.

If you want to dig deeper, maybe you can join our matrix channel (see repo main page) and ping me over there.
