### ISSUE TITLE
Memory leak after locked database

### ISSUE THREAD

**Issue by se7entynine** [jellyfin/jellyfin#12312]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

The Windows Jellyfin app UI freezed and I couldn't select anything. A restart of the windows app didn't resolve that problem either. 
I checked the docker stats: CPU 300%, Memory: 10GB ( normal for my setup is around 4GB memory usage and it doubled in a very short timeframe - 10ish minutes )
Checked Logs and it showed a lot of "database table is locked" errors. Increased memory usage started shortly after 6pm and thats also when the error messages pop up. 
Ubuntu LXC had enough performance reserves to handle the load - 16GB memory, 8 cores of Intel 14900k, no swap - so I guess the high memory usage is only a symptome and the database lock is the cause that froze jellyfin. 

Current workaround: restart of the jellyfin docker container

### Reproduction steps

No clue at all

### What is the current _bug_ behavior?

- locks database
- completely freezes Jellyfin and leaves it in an unusable state
- only resolvable through a container restart

### What is the expected _correct_ behavior?

No database lock

### Jellyfin Server version

10.9.7

### Specify the build version

10.9.7

### Environment

```markdown
- OS: Latest Proxmox with an Ubuntu 24.04 LXC 
- Linux Kernel:
- Virtualization: Latest Docker image
- Clients: Windows app but most likely all as the server "froze"
- Browser:
- FFmpeg Version:
- Playback Method: Direct Play
- Hardware Acceleration: QSV
- GPU Model: iGPU UHD770
- Plugins: AudioDB, Cover Art Archive, DLNA, Fanart, Intro Skipper, LDAP-Auth, MusicBrainz, OMDb, Open Subtitles, Playback Reporting, Reports, Session Cleaner, Studio Images, Subtitle extract, TMDb, TMDb Box Sets, TheTVDB, Themerr
- Reverse Proxy: yes, but not when the error happened ( Traefik )
- Base URL:
- Networking: 
- Storage: local
```

### Jellyfin logs

[Jellyfin_logs_bug.txt](https://github.com/user-attachments/files/16322108/Jellyfin_logs_bug.txt)

### Relevant screenshots or videos

From proxmox lxc summary page ( daily max values - every 30 minutes are saved -  sorry not very detailed ): 
Memory usage: 
![image](https://github.com/user-attachments/assets/d50ab9f3-6b05-4ec0-90cf-587e0e428759)
CPU usage: 
![image](https://github.com/user-attachments/assets/61ccf3f8-df61-443d-89a0-c31e51b25258)

**Comment by gnattu** [comment]
Potential fix: https://github.com/jellyfin/jellyfin/pull/11901

**Comment by se7entynine** [comment]
Thank you for the quick response. 
Is there any ETA when this update will get merged with the main release? It's still blocked for 2ish months...
 
I have no clue if your fix is the cause of my issue as someone in the comments said it happens only during a library scan ( which wasnt the case here ). Is the EFCore = EntityFrameworkCore ?

Here are the first few lines of the errors: 

`[2024-07-20 18:17:25.390 +02:00] [ERR] [710] Microsoft.EntityFrameworkCore.Database.Command: Failed executing DbCommand ("31,794"ms) [Parameters=["@p0='?' (DbType = DateTime), @p1='?', @p2='?' (DbType = Int32), @p3='?' (Size = 37), @p4='?', @p5='?' (DbType = UInt32), @p6='?' (Size = 25), @p7='?' (Size = 14), @p8='?' (DbType = Guid)"], CommandType='Text', CommandTimeout='30']"
""INSERT INTO \"ActivityLogs\" (\"DateCreated\", \"ItemId\", \"LogSeverity\", \"Name\", \"Overview\", \"RowVersion\", \"ShortOverview\", \"Type\", \"UserId\")
VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8)
RETURNING \"Id\";"  

[2024-07-20 18:17:25.393 +02:00] [ERR] [710] Microsoft.EntityFrameworkCore.Update: An exception occurred in the database while saving changes for context type '"Jellyfin.Server.Implementations.JellyfinDbContext"'."  
""Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.    
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 6: 'database table is locked'.  
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)  
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()  
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)  
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken
 cancellationToken)  
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)  
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)  
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)`

**Comment by JamsRepos** [comment]
Currently suffering with this every couple hours or so, i'm literally having to baby sit Jellyfin currently.

**Comment by se7entynine** [comment]
#11901 solved this issue.
