### ISSUE TITLE
POST at Library/VirtualFolders fails only with JSON input

### ISSUE THREAD

**Issue by arpj-rebola** [jellyfin/jellyfin#12335]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

The following POST request fails:
```
jq -Mcrn '{"collectionType": "movies", "refreshLibrary": true, "name": "FolderName"}' \
| curl --silent --fail-with-body --request POST \
--header "Content-Type: application/json" --header "Accept: application/json" \
--header "$REDACTED" --data @- "http://localhost:8096/Library/VirtualFolders"
```
with 400 response:
```
{"type":"https://tools.ietf.org/html/rfc9110#section-15.5.1","title":"One or more validation errors occurred.","status":400,"errors":{"name":["The name field is required."]},"traceId":"00-8f52d6115a6408b79f21bc792e1def6d-0b49a2ccecec2704-00"}
```

However, this succeeds with the expected result:
```
curl --silent --fail-with-body --request POST \
--header "Content-Type: application/json" --header "Accept: application/json" \
--header "$REDACTED" \
"http://localhost:8096/Library/VirtualFolders?collectionType=movies&refreshLibrary=true&name=FolderName"
```

Is this a bug or is JSON request content not supported?

### Reproduction steps

```
jq -Mcrn '{"collectionType": "movies", "refreshLibrary": true, "name": "FolderName"}' | curl --silent --fail-with-body --request POST --header "Content-Type: application/json" --header "Accept: application/json" --header "$REDACTED" --data @- http://localhost:8096/Library/VirtualFolders

curl --silent --fail-with-body --request POST --header "Content-Type: application/json" --header "Accept: application/json" --header "$REDACTED" "http://localhost:8096/Library/VirtualFolders?collectionType=movies&refreshLibrary=true&name=FolderName"
```

### What is the current _bug_ behavior?

The first requests receives a status 400 response claiming that the name field is missing, but it is not.

### What is the expected _correct_ behavior?

The request succeeds with status 204 and a new movie library named "FolderName" is created.

### Jellyfin Server version

10.9.8+

### Specify version number

10.9.8.0

### Specify the build version

10.9.8

### Environment

```markdown
- OS: KDE Neon
- Linux Kernel: Linux 5.19.0-28-generic x86_64
- Virtualization: Bare metal
- Clients: localhost
- Browser: No
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy: none
- Base URL:
- Networking: localhost
- Storage: local
```

### Jellyfin logs

```shell
(no [DBG] logs were produced)
```

**Comment by crobibero** [comment]
The api docs state that `name`, `collectionType`, `paths`, `refreshLibrary` are query parameters.

https://api.jellyfin.org/#tag/LibraryStructure/operation/AddVirtualFolder

**Comment by arpj-rebola** [comment]
Oops, my bad. Thanks a lot!
