### ISSUE TITLE
Changing the DataDir causes library settings to fail to save

### ISSUE THREAD

**Issue by joshuaboniface** [jellyfin/jellyfin#1235]
If a user changes the `JELLYFIN_DATA_DIR`, for instance from `/var/lib/jellyfin` to `/srv/jellyfin`, existing Libraries cannot have their settings, e.g. metadata providers, edited. There are other potential subtle bugs related to this too.

The symptom is an error like this on the web console when trying to save Library options, which fails:

```
Error: null name apiclientcore.js:861:24
    updateVirtualFolderOptions https://jf1/web/bower_components/apiclient/apiclientcore.js?v=10.3.0:861
    onDialogClosing https://jf1/web/components/medialibraryeditor/medialibraryeditor.js?v=10.3.0:121
    closeDialog https://jf1/web/components/dialogHelper/dialogHelper.js?v=10.3.0:223
    onHashChange https://jf1/web/components/dialogHelper/dialogHelper.js?v=10.3.0:58
    close https://jf1/web/components/dialogHelper/dialogHelper.js?v=10.3.0:212
    onload https://jf1/web/components/medialibraryeditor/medialibraryeditor.js?v=10.3.0:142
```

Ultimately the problem is with the Database. Individual libraries are stored in the `library.db` under the `TypedBaseItems` table as a `MediaBrowser.Controller.Entities.CollectionFolder` `type`. Two fields in these columns contain paths that are relevant:

```
sqlite> select data from TypedBaseItems where type='MediaBrowser.Controller.Entities.CollectionFolder';
{"CollectionType":"movies","PhysicalLocationsList":["/var/lib/jellyfin/root/default/Movies2","/srv/media/Video/Movies"],"PhysicalFolderIds":["ac775c53410b3210b1a5ce83b60ec25f"],"IsRoot":false,"LinkedChildren":[],"RemoteTrailers":[],"IsHD":false,"IsShortcut":false,"Width":0,"Height":0,"ExtraIds":[],"SupportsExternalTransfer":false}
```
```
sqlite> select Path from TypedBaseItems where type='MediaBrowser.Controller.Entities.CollectionFolder';
/var/lib/jellyfin/root/default/Movies2
```

If these directories do not match the `JELLYFIN_DATA_DIR`, the `libraryFolder` set at https://github.com/jellyfin/jellyfin/blob/master/Emby.Server.Implementations/Library/LibraryManager.cs#L1186 becomes `null`, thus causing the `ItemId` (https://github.com/jellyfin/jellyfin/blob/master/Emby.Server.Implementations/Library/LibraryManager.cs#L1195) and `LibraryOptions` (https://github.com/jellyfin/jellyfin/blob/master/Emby.Server.Implementations/Library/LibraryManager.cs#L1196) to be null as well. This results in an API result that does not contain these entries, which are required to set the configuration options as seen in the error.

The fix would seem to be making these database entries into relative directories and constructing the path live in the code, thus any future migration of the `JELLYFIN_DATA_DIR` would then be seamless.

The workaround is to manually edit the `library.db` database and replace the (old) `JELLYFIN_DATA_DIR` directory entries with the new one, e.g.

```
sqlite> update TypedBaseItems set data='{"CollectionType":"movies","PhysicalLocationsList":["/srv/jellyfin/root/default/Movies2","/srv/media/Video/Movies"],"PhysicalFolderIds":["ac775c53410b3210b1a5ce83b60ec25f"],"IsRoot":false,"LinkedChil
dren":[],"RemoteTrailers":[],"IsHD":false,"IsShortcut":false,"Width":0,"Height":0,"ExtraIds":[],"SupportsExternalTransfer":false}' where type='MediaBrowser.Controller.Entities.CollectionFolder' and Path='/var/lib/jellyfin/root/default/Movi
es2';                                 
sqlite> update TypedBaseItems set Path='/srv/jellyfin/root/default/Movies2' where Path='/var/lib/jellyfin/root/default/Movies2';
```

**Comment by WWWesten** [comment]
@joshuaboniface How can this be done under Windows? I have installed DB Browser for SQLite 3.11.2 Is any script for it? 
Thanks.

**Comment by WWWesten** [comment]
OK, I was able to manually fix the database, saving and some other glitches are fixed, but #1282 isn't fixed.

**Comment by thegranddesign** [comment]
@joshuaboniface's solution works but I have something that's slightly easier since you don't have to copy paste the existing data blob:

In this example I moved my data directory from `/var/lib/jellyfin` to `/home/jellyfin/data`.

Hope this helps everyone like me who was hitting their head against the wall on this issue!

```
UPDATE
  "TypedBaseItems"
SET
  "data" = REPLACE("data", '/var/lib/jellyfin/', '/home/jellyfin/data/'),
  "path" = REPLACE("path", '/var/lib/jellyfin/', '/home/jellyfin/data/')
;

**Comment by thegranddesign** [comment]
@anthonylavado I'm not sure why this was moved to "Done" but I can confirm this is still an issue in "10.7.7".

**Comment by anthonylavado** [comment]
@thegranddesign If I recall correctly, it's mainly that we know it's an issue right now, but would be solved by the larger database re-write. That said, there seems to be some interest in related "manual operations", so it may be worth adding a page to the documentation.

**Comment by thegranddesign** [comment]
@anthonylavado thank you and I appreciate all the hard work.
