### ISSUE TITLE
Music library : miss-interpreted artist

### ISSUE THREAD

**Issue by emaen** [jellyfin/jellyfin#12350]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

Jellyfin 10.9.8 : When tag "album artist" is set with two artists ( e.g : artist1/artist2  or  Artist1; artist2 ) then these two separate artists are considered just like one unique new artist !!

Using the same music library with Jellyfin 10.8.3 correctly works : the two artists are considered as separate ones.

### Reproduction steps

1 - With a music file : set the "album artist" tag with two names (e.g : Sting; Eric Clapton or Ravel/Mucci )

### What is the current _bug_ behavior?

"Sting; Eric Clapton" is considered as a unique person !

### What is the expected _correct_ behavior?

"Sting; Eric Clapton" should be considered as two separate artist participate to the same work.
( just as it was until 10.8.3, and maybe after 10.8.3... )

### Jellyfin Server version

10.9.8+

### Specify the build version

10.9.8

### Environment

```markdown
- OS: win 10

- Clients: browser, android
- Browser: brave

- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
none
```

### Relevant screenshots or videos

![01 - jellyfin- two artists 1](https://github.com/user-attachments/assets/066ee85a-062d-485d-b63a-e40f34b2a5a2)
![02 - jellyfin- two artists 2](https://github.com/user-attachments/assets/1e79e5f1-6c40-4fb1-9dfd-0a8ca44619ab)
![03 - jellyfin- two artists 3](https://github.com/user-attachments/assets/72eb7b62-d7bf-4c60-b5e7-3dc72be9b2af)
![04 - jellyfin- two artists 1 with 10 8 3](https://github.com/user-attachments/assets/77f03216-722c-481d-8607-a55717aa030b)
![05 - jellyfin- two artists 2 with 10 8 3](https://github.com/user-attachments/assets/4f55ea21-243f-4f6c-9efa-e08e61c64362)
![06 - jellyfin- two artists 3 with 10 8 3](https://github.com/user-attachments/assets/0bfe1685-859c-4bad-921b-61f791c75f16)

**Comment by gnattu** [comment]
See https://github.com/jellyfin/jellyfin/pull/12293

**Comment by emaen** [comment]
Ok !

Back to v 10.8.3 and waiting for v 10.10, so

Thank you !
