### ISSUE TITLE
Album art cannot be fetched from musicbrainz.org

### ISSUE THREAD

**Issue by BentiGorlich** [jellyfin/jellyfin#12363]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

If I have an album that is 
- on musicbrainz.org and has a cover art there
- not on theaudiodb.com

And I identified the album and told it to replace existing media it does not download the album art

### Reproduction steps

1. have the Dreamcatcher Album [VirtuouS] in your jellyfin music directory [link](https://music.youtube.com/playlist?list=OLAK5uy_k53Hho5-WThxyVuaAL8dd39YXS3ou9m8g)
2. It should automatically link the [musicbrainz entry](https://musicbrainz.org/release/8b83b48d-f873-4bbb-8da3-f3267cb23207) which has an image

### What is the current _bug_ behavior?

The album will show the group image if any, but definitely not the album image

### What is the expected _correct_ behavior?

The album should have the image that is on the "release" id of musicbrainz

### Jellyfin Server version

10.9.8+

### Specify the build version

 10.9.8

### Environment

```markdown
- OS: Debian 12
- Linux Kernel: 6.1.0-21-amd64
- Virtualization: none
- Clients: [Browser, Android, TV]
- Browser: LibreWolf 128.0.1
- FFmpeg Version: 6.0.1-Jellyfin
- Playback Method: Transcode
- Hardware Acceleration: Intl QuickSync
- GPU Model: UHD730
- Plugins: none
- Reverse Proxy: nginx
- Base URL: none
- Networking: none
- Storage: local
```

### Jellyfin logs

```shell
[INF] Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/{{READACTED}}/Musik/Dreamcatcher/[VirtuouS]/5 - Fireflies (Fireflies).mp3\" -threads 0 -v warning -print_format json -show_streams -show_format"
[INF] Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/{{READACTED}}/Musik/Dreamcatcher/[VirtuouS]/3 - STΦMP! (STΦMP!).mp3\" -threads 0 -v warning -print_format json -show_streams -show_format"
[INF] Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/{{READACTED}}/Musik/Dreamcatcher/[VirtuouS]/4 - 2 Rings (2 Rings).mp3\" -threads 0 -v warning -print_format json -show_streams -show_format"
[INF] Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/{{READACTED}}/Musik/Dreamcatcher/[VirtuouS]/1 - Intro ： 7' Dreamcatcher (Intro ： 7' Dreamcatcher).mp3\" -threads 0 -v warning -print_format json -show_streams -show_format"
[INF] Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/{{READACTED}}/Musik/Dreamcatcher/[VirtuouS]/2 - JUSTICE (JUSTICE).mp3\" -threads 0 -v warning -print_format json -show_streams -show_format"
[INF] Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/{{READACTED}}/Musik/Babymetal/RATATATA/1 - RATATATA.mp3\" -threads 0 -v warning -print_format json -show_streams -show_format
```

**Comment by robo45h** [comment]
I can confirm this issue in Jellyfin 10.9.11. I have a CD from 1993 by a local band. I use Musicbrainz Picard to get the CD ID and I created all the information for the Artist and Album (release) in Musicbrainz, including uploading the cover album art. The Jellyfin server properly identifies the album and puts the Musicbrainz ID into the metadata. But it does not properly install the image. Looking in the Dashboard, there is also no way to add Musicbrainz to the ImageFetchers lists for Artists or Albums. TheAudioDB is the only option listed (even though the text says you should select and rank your fetchers; there is only one option in each case.

**Comment by robo45h** [comment]
> I can confirm this issue in Jellyfin 10.9.11. I have a CD from 1993 by a local band. I use Musicbrainz Picard to get the CD ID and I created all the information for the Artist and Album (release) in Musicbrainz, including uploading the cover album art. The Jellyfin server properly identifies the album and puts the Musicbrainz ID into the metadata. But it does not properly install the image. Looking in the Dashboard, there is also no way to add Musicbrainz to the ImageFetchers lists for Artists or Albums. TheAudioDB is the only option listed (even though the text says you should select and rank your fetchers; there is only one option in each case.

Actually, after doing a lot of web searching, I found that installation of the "Creative Arts" plugin is required to get Musicbrainz images. The other metadata comes through with the core Jellyfin server, but the album (release) images only come through if you install and then enable the "Creative Arts" plugin.

**Comment by BentiGorlich** [comment]
Which plugin do I need to install to get the images from musicbrainz.org ?
I couldn't find a "Creative Arts" plugin, not via google and not in the jellyfin plugin search... I installed the "Artwork" plugin but that didn't help and I already have the "Studio Images" plugin enabled, as well as the "MusicBrainz" plugin

**Comment by felix920506** [comment]
Cover Art Archive plugin is required to pull cover art from Musicbrainz
