### ISSUE TITLE
Saving settings adds "/metadata" to metadata path

### ISSUE THREAD

**Issue by Nickbert7** [jellyfin/jellyfin#1238]
**Describe the bug**
By saving the settings on the general settings page, it adds "/metadata" to the metadata path

**To Reproduce**
1. Go to the general settings
2. Check Metadata Path
3. Click on 'save'
4. "/metadata" has been added to the metadata path

**Screenshots**
![2019-04-15_21-31-14](https://user-images.githubusercontent.com/14938497/56159917-26c32f80-5fc6-11e9-977a-f520d9d9d149.gif)

**System (please complete the following information):**
 - OS: Win 10 x64
 - Browser: Chrome
 - Jellyfin Version: 10.3.0_rc2
 - Reverse proxy: traefik

**Comment by joshuaboniface** [comment]
This is a long-inherited bug, and affects `transcoding-temp` too - what you specify ends up being the parent directory, then Jellyfin creates the actual directory under this. Should certainly be fixed. Why this then shows up repeatedly in the UI is a different matter however, and seems specific to metadata.

**Comment by Nickbert7** [comment]
The issue is fixed now
