### ISSUE TITLE
Reverse proxy stuck at logo after 10.9.9 update

### ISSUE THREAD

**Issue by clowncracker** [jellyfin/jellyfin#12399]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

After updating from version 10.9.8 to version 10.9.9, I cannot connect to Jellyfin via reverse proxy via the app.  I tried downgrading to version 10.9.8 and I can log back in.

Findroid seems to works, so the problem is either with the offical app or something within Jellyfin. 

### Reproduction steps

Open Jellyfin for Android and it just shows the logo.

### What is the current _bug_ behavior?

Open Jellyfin for Android and it just shows the logo.

### What is the expected _correct_ behavior?

I should be able to open the app.

### Jellyfin Server version

10.9.9+

### Specify the build version

10.9.9

### Environment

```markdown
- OS: Unraid
- Docker: https://hub.docker.com/r/linuxserver/jellyfin
```

### Jellyfin logs

```shell
N/A
```

**Comment by felix920506** [comment]
Please try an incognito window.

**Comment by clowncracker** [comment]
> Please try an incognito window.

The issue is with the Jellyfin app, not the web browser.  I can log in from the browser.  It looks like someone else is having the same issue here: https://forum.jellyfin.org/t-reverse-proxy-stuck-at-logo-post-updating-from-10-9-8-to-10-9-9?pid=31878#pid31878

**Comment by Raul824** [comment]
thanks it's me who is having issues and I didn't know whether it was a bug or my config issue so instead I raised in forums troubleshooting.

It seems reverse proxy is not working in chromium browser as well as firefox not even in incognito mode at my end.
In the jellyfin app I tried clearing data and cache but still nothing it gets stuck at logo and nginx shows lots of 404 error.

If I tried connecting directly using IP and port the home page opens but whenever I play anything it gives error media not supported although hardware transcoding is enabled and setup correctly at my end.

I rolled back to 10.9.8 and everything is working fine without doing any changes in nginx config.

**Comment by clowncracker** [comment]
Downgrading from 10.9.8 and then reupgrading to 10.9.9 solved the issue.  Not sure why it didn't work the first time.

**Comment by Raul824** [comment]
@clowncracker  did you checked the web version in dashboard. It is working as web version will have cached data of 10.9.8 web server and when you clean that cache it will get stuck again at the same logo.

**Comment by hkup859** [comment]
Incognito worked for me. It seems like it's just a caching issue from what I can tell.
