### ISSUE TITLE
Shuffle episode not really random

### ISSUE THREAD

**Issue by Jerroder** [jellyfin/jellyfin#12409]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

When shuffling a TV show, the "random" episodes are often the same. I've been shuffling the same TV show while having lunch/dinner and I have to re-do it like 10 times because it's episodes I've seen in the past week 95% of the time.

I also found [this post](https://features.jellyfin.org/posts/2797/random-not-so-random) from a few days ago.

I just tried on a 10-episode TV show and I got episode 8 three times out of 10 shuffles, with twice in a row. It then came 5 times out of 20 shuffles.
Finally, out of 50 shuffles, episode 2 and 8 came out 8 and 7 times respectively, with episode 3 and 7 coming out twice each.

I don't know if these numbers really reflect the non-randomness but it's really annoying when it plays an episode for the 15th time in a week.

### Reproduction steps

1. Go to any TV show
2. Click on the "Shuffle" button

### What is the current _bug_ behavior?

"Shuffle" doesn't seem to give a random episode but the sames ones 95% of the time.

### What is the expected _correct_ behavior?

"Shuffle" should be really random.

### Jellyfin Server version

10.9.9+

### Specify the build version

10.9.9

### Environment

```markdown
- OS: Debian 12
- Linux Kernel: 6.6.13+bpo-amd64
- Virtualization: KVM
- Clients: iOS, Windows
- Browser:
- FFmpeg Version: 6.0.1-Jellyfin
- Playback Method: Direct
- Hardware Acceleration: QSV
- GPU Model: Arc A380
- Plugins:
- Reverse Proxy: nginx
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
irrelevant
```

**Comment by EthanDotLog** [comment]
If this got fixed 2 years ago why is it still a thing?

**Comment by Andrew-T-Smith** [comment]
Agreed. Something feels wrong here still. A TV series with 100+ episodes loads the same exact first episode on shuffle between two instances of jellyfin i have. Possibly a coincidence but it doesnt feel that way

**Comment by AltruisticRambler** [comment]
Same here! Not just with TV though - I mostly use jellyfin as a music service and notice the same 50 or so songs are frequently the only result of a library shuffle despite having 500ish songs! Would love if this gets looked at again 🙂

**Comment by Jerroder** [comment]
It used to be much worse, I did notice improvements after updating to 10.10 but I noticed it does still happen a little.

**Comment by ooobii** [comment]
This is still very much an issue, I wonder what regression caused this but to show it's face again...
