### ISSUE TITLE
Jellyfin-10.9.9 amd64 build on the repo doesn't support AVIF

### ISSUE THREAD

**Issue by ikelos** [jellyfin/jellyfin#12412]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

Using jellyfin 10.9.8 (and retesting with 10.9.9) installed through Gentoo using the repo version of jellyfin, adding a library of type "Home videos and photos" containing AVIF files, does not show any AVIF files, despite the 10.9.0 release notes suggesting that AVIF is now supported.

### Reproduction steps

1. Sign in to Jellyfin
2. Dashboard -> Libraries -> Libraries -> Add Media Library
3. Select content type "Home Videos and Photos"
4. Select a foldering containing valid AVIF files.
5. Rescan the metadata for the folder to be sure.

### What is the current _bug_ behavior?

No AVIF files are displayed or indexed, even when logging is set to "debug", the AVIF files do not appear to be even scanned or mentioned in the logs.

### What is the expected _correct_ behavior?

AVIF files are found, indexed and displayed.

### Jellyfin Server version

10.9.9+

### Specify version number

10.9.9

### Specify the build version

10.9.9

### Environment

```markdown
- OS: Gentoo
- Linux Kernel: 6.10.0-x86_64
- Virtualization: None
- Clients: Browser
- Browser: Firefox, Chrome
- FFmpeg Version: 6.1.1 (Gentoo -r8)
- Playback Method: N/A
- Hardware Acceleration: None
- GPU Model: None
- Plugins: AudioDB, MusicBrainz, OMDb, Studio Images, TMDb
- Reverse Proxy: None
- Base URL: None
- Networking: Host
- Storage: SSHFS
```

### Jellyfin logs

```shell
[2024-08-08 21:24:36.219 +01:00] [DBG] [37] MediaBrowser.Providers.Folders.CollectionFolderMetadataService: Running "CollectionFolderImageProvider" for "/var/lib/jellyfin-example/root/default/Example"
[2024-08-08 21:24:36.225 +01:00] [DBG] [37] MediaBrowser.Providers.Folders.FolderMetadataService: Running "FolderImageProvider" for "/var/lib/jellyfin-example/media/private/example"
[2024-08-08 21:24:36.228 +01:00] [DBG] [37] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshStart c695b6d09756667e466c18d0063b845b
[2024-08-08 21:24:36.230 +01:00] [DBG] [37] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress c695b6d09756667e466c18d0063b845b 5
[2024-08-08 21:24:36.235 +01:00] [DBG] [37] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress c695b6d09756667e466c18d0063b845b 10
[2024-08-08 21:24:36.235 +01:00] [DBG] [37] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress c695b6d09756667e466c18d0063b845b 50
[2024-08-08 21:24:36.235 +01:00] [DBG] [39] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshComplete c695b6d09756667e466c18d0063b845b
```

### FFmpeg logs

```shell
No ffmpeg*.log section listed in Dashboard > Logs
```

### Client / Browser logs

Browser not relevant since no images listed in the folder (suggesting the server hasn't seen the images).

### Additional information

Upstream bug (suggesting filing a bug here) at https://bugs.gentoo.org/937584

Gentoo ebuild gets the package to install from https://repo.jellyfin.org/files/server/linux/stable/v10.9.9/amd64/jellyfin_10.9.9-amd64.tar.xz.

The commit that allegedly adds avif support is at https://github.com/jellyfin/jellyfin/commit/681be595cea8254cbac5bbb3bdc9083c4780db21 which seems quite minimal and suggests another library is involved.

The library that processes images seems to be SkiaSharp, the assembly packaged with jellyfin-bin seems to be reported as 2.88.0.0.  The latest version of which SkiaSharp appears to be 2.88.8 (https://github.com/mono/SkiaSharp/tree/v2.88.8).  It appears that AVIF *encoding* wasn't exposed until 2.88.1, but it's not clear if that affected decoding.

**Comment by ikelos** [comment]
Thanks for your response.  The fact that the official documentation says it was added in 10.9 when it was apparently not, is a bug.  It is specifically mentioned on the 10.9 release notes (4th point under general) at https://jellyfin.org/posts/jellyfin-release-10.9.0/, as I said in my report.

"We now support AVIF and WEBP images for Pictures libraries."

* If the official release documentation is incorrect, it should be updated.
* If the release documentation was accurate, then the feature isn't working correctly.
* If the release notes were generated from merge requests automatically (such as https://github.com/jellyfin/jellyfin/commit/681be595cea8254cbac5bbb3bdc9083c4780db21) they should be vetted more closely to ensure users do not waste anyone's time trying to find a feature that is then mentioned in both the commit logs, and the official release documentation but which for which Jellyfin actually has no support.  It's quite confusing...

**Comment by nielsvanvelzen** [comment]
Only the file extensions listed in this part of the code can be scanned by our photo provider. So the linked PR does not fully implement support for AVIF.

https://github.com/jellyfin/jellyfin/blob/master/src/Jellyfin.Drawing/ImageProcessor.cs#L78-L106

**Comment by ikelos** [comment]
Ah, ok, perfect!  So, having just tested, it seems that simply renaming the `.avif` file to `.jpg` suddenly *does* show the image in the image library, meaning the format is already properly supported but is being filtered out by the file extension.

Do you need me to create a pull request adding the extension to that list, or is it easy enough for someone that already works on the code to fix it?

**Comment by nielsvanvelzen** [comment]
You may open a pull request for it, make sure to target the release-10.9.z branch.

**Comment by ikelos** [comment]
Ok, I won't be able to test it though, since I don't have all the dotnet toolchain to test it out.
