### ISSUE TITLE
10.9 not working on QNAP and container station

### ISSUE THREAD

**Issue by fpizzuta** [jellyfin/jellyfin#12436]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

I recreated my container from 10.8.13 to 10.9.8 and the latest. When 10.9.x starts, it immediately experiences the following error, which continues to appear in the log.

```
GC: Failed to initialize GCToOSInterface
GC initialization failed with error 0x80004005
Failed to create CoreCLR, HRESULT: 0x80004005
```
I need to be on 10.9.8 or later, or my Google TV app won't connect. 

### Reproduction steps

On Qnap with container station, recreate the container using 10.9.8 or later, and you will see the error in the container log.

### What is the current _bug_ behavior?

Jellyfin is not available.

### What is the expected _correct_ behavior?

Jellyfin will be available. 

### Jellyfin Server version

10.9.9+

### Specify the build version

10.9.8+

### Environment

```markdown
- OS:
- Linux Kernel:
- Virtualization: docker on Qnap container station
- Clients: mobile, pc, and google tv
- Browser: safari, chrome, and jellyfin app
- FFmpeg Version:
- Playback Method: browser and app
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
GC: Failed to initialize GCToOSInterface
GC initialization failed with error 0x80004005
Failed to create CoreCLR, HRESULT: 0x80004005
```

**Comment by gnattu** [comment]
What's the kernel version on your QNAP device? If it is too old it may fail to run dotnet 8 with errors like this.

**Comment by fpizzuta** [comment]
Kernel is 4.2.8. 
Model is TS-932PX.

**Comment by fpizzuta** [comment]
Still getting same issue. NAS is only 2 years old. I guess I will have to move Jellyfin to another device. Thank you for the quick response.

**Comment by gnattu** [comment]
It's QNAP that ships a 2-year-old NAS with a kernel released on December 15, 2015, or roughly 9 years ago, so that's not your fault. Unfortunately, there's very little we can do to overcome this.
