### ISSUE TITLE
Missing translation or old setting? (LaunchWebAppOnStartup)

### ISSUE THREAD

**Issue by Nickbert7** [jellyfin/jellyfin#1243]
Is the "LaunchWebAppOnStartup" setting a missing translation or an old setting not used anymore?
Changes to this setting cannot be saved.

![image](https://user-images.githubusercontent.com/14938497/56283856-2a180180-6113-11e9-9bfa-70863143c6b0.png)

**System (please complete the following information):**
 - OS: Win 10 x64
 - Browser: Chrome
 - Jellyfin Version: 10.3.0_rc2
 - Reverse proxy: Traefik

**Comment by Nickbert7** [comment]
I just found additional missing strings:
![image](https://user-images.githubusercontent.com/14938497/56290454-7cf9b500-6123-11e9-93a2-029733ce2b17.png)
![image](https://user-images.githubusercontent.com/14938497/56290461-7f5c0f00-6123-11e9-8574-f8ad0e306ac0.png)

**Comment by joshuaboniface** [comment]
Should be fixed in 10.3.0 release.
