### ISSUE TITLE
Song list : filter + random impossible

### ISSUE THREAD

**Issue by ludovicjardel** [jellyfin/jellyfin#12433]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

Filter is not taken into account when you clic on random buton in the songs list

### Reproduction steps

goto songs list
clic on filter (select whatever filter you want)
The list is filtered 
click on the random icon
The filter is not taken into account 

### What is the current _bug_ behavior?

songs not in the displayed list are played

### What is the expected _correct_ behavior?

It should be possible to use random AND filters
Only the songs displayed in the list should be played

### Jellyfin Server version

10.9.9+

### Specify the build version

10.9.9

### Environment

```markdown
tested on Android 12 and web (lastest version of chrome)
```

### Jellyfin logs

```shell
NA
```

**Comment by sevenrats** [comment]
Hey please open your feature request at 
features.jellyfin.org
