### ISSUE TITLE
Downloading for offline viewing

### ISSUE THREAD

**Issue by ItsNik-yaml** [jellyfin/jellyfin#12455]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

So I have been using jellyfin for quite some time now and I noticed that when you lock your device (I tested it on an unrooted Google Pixel 7a and a Windows 11 Chromium based browser), the download will fail.

### Reproduction steps

1. Open Jellyfin / Findroid / Any Jellyfin Client
2. Log in to your server
3. Start to download your Series / Movie / ...
4. Lock your device
5. It will fail

### What is the current _bug_ behavior?

Well like I already mentioned the downloads will fail

### What is the expected _correct_ behavior?

I would expect that the downloads would continue just like using Netflix / Disney+ 

### Jellyfin Server version

10.9.9+

### Specify the build version

10.9.9

### Environment

```markdown
- OS: TrueNas Scale
- Linux Kernel:
- Virtualization: K3S
- Clients: Jellyfin Web, Findroid
- Browser: Chromium based
- FFmpeg Version: latest
- Playback Method: Direct Stream
- Hardware Acceleration:
- GPU Model: Intel i3 6100 Integrated GPU
- Plugins: Fanart
- Reverse Proxy: nope
- Base URL: none available on HelmChart for Truenas
- Networking: Host
- Storage: local
```

### Jellyfin logs

```shell
/
```

### Additional information

Running on TrueNas Scale

2 vDevs all disks are HDDs (rather slow but they work)
Network: Local 1Gbit, Otherwise 40 Mbit Up, 100 Mbit down

**Comment by crobibero** [comment]
This is a client issue. Please open issues in the respective client repositories.
