### ISSUE TITLE
Playback issue with new video files added 

### ISSUE THREAD

**Issue by Sarxzer** [jellyfin/jellyfin#12458]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

Since recently, when I add a video file and scan the folder, Jellyfin is able to find it, name it an get every metadata, but when I try to launch the video, I get a "Playback failed due to a fatal player error.". Using vlc, I check the codec, resolution etc but they are the same as other working video files.

### Reproduction steps

I don't know how to reproduce this bug. 

### What is the current _bug_ behavior?

I get an error when I try to launch a recently added video, and it never did that. 

### What is the expected _correct_ behavior?

Launching the video without error. 

### Jellyfin Server version

10.9.9+

### Specify the build version

10.9.9

### Environment

```markdown
- OS:Windows 
- Linux Kernel:none
- Virtualization:
- Clients:All
- Browser:All
- FFmpeg Version:
- Playback Method:I don't know 
- Hardware Acceleration:none, nvenc 
- GPU Model:RTX 4060
- Plugins:Anilist, Open Subtitles
- Reverse Proxy:none
- Base URL:none
- Networking:host
- Storage:local
```

### Jellyfin logs

```shell
[log_20240816.txt](https://github.com/user-attachments/files/16641368/log_20240816.txt)
```

### Client / Browser logs

[localhost-1723839874793.log](https://github.com/user-attachments/files/16641456/localhost-1723839874793.log)

**Comment by gnattu** [comment]
Jellyfin is unable to locate ffmpeg in your install. Did you set env var or the config to overwrite the location, and point to an invalid path?

**Comment by Sarxzer** [comment]
> Jellyfin is unable to locate ffmpeg in your install. Did you set env var or the config to overwrite the location, and point to an invalid path?

No I didn't modify the path to FFmpeg, and I can't do it from the dashboard

**Comment by gnattu** [comment]
> No I didn't modify the path to FFmpeg, and I can't do it from the dashboard

That field is read-only on dashboard and if you see that field is empty it means Jellyfin does not find a valid ffmpeg

You can try what another user with similar issue did here : https://github.com/jellyfin/jellyfin/issues/12411#issuecomment-2276582704

You can also remove the encoding config file. Depends on your install, it is either
```
%LOCALAPPDATA%\jellyfin\config\encoding.xml
``` 

or

```
%ProgramData%\Jellyfin\Server\config\encoding.xml
```

You can just type the path into the address bar of the file manager to directly go to the folder and delete the file.

Doing so will reset the encoding config to default.

**Comment by Sarxzer** [comment]
I don't have FFmpeg in the environmental variables

**Comment by gnattu** [comment]
Have you tried removing the files I mentioned?

**Comment by Sarxzer** [comment]
Now it work, thanks you a lot!
