### ISSUE TITLE
UPnP: miniupnpd port redirect not renewing

### ISSUE THREAD

**Issue by ralvarezt** [jellyfin/jellyfin#12470]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

Using the last version of Jellyfin, 10.9.9, enabling the UPnP port redirect option in the network settings results in an initial request to the IGD and the port gets forwarded, but the port forward lease is not maintained, causing an expiration.

Thu Aug 15 20:32:01 2024 daemon.notice miniupnpd[3251]: remove port mapping 8096 TCP because it has expired

The only workaround  so far to this problem is to *NOT* use this option and manually open the port in the router configuration. This workaround is not a solution, if that functionality is not properly implemented please remove the UPnP Port redirect option from the configuration page.

### Reproduction steps

Go to the Jellyfin Control panel, Network, remote access, enable the UPnP port redirect option, save and restart server.
The port redirect stays on for the lease duration, afterwards it gets expired and the remote access doesn't work even if the option is still on.

### What is the current _bug_ behavior?

The port redirect stays on for the lease duration, afterwards it gets expired and the remote access doesn't work even if the option is still on.

### What is the expected _correct_ behavior?

The upnp redirect is renewed before its expiration and the redirect stays active.

### Jellyfin Server version

10.9.9+

### Specify the build version

10.9.9

### Environment

```markdown
- OS: Debian Linux 12
- Linux Kernel: 6.6.32
- Virtualization: LXC
- Clients: Browser, Android, etc..
- Browser: Firefox
- FFmpeg Version: N/A
- Playback Method: N/A
- Hardware Acceleration: vaapi
- GPU Model: N/A
- Plugins: N/A
- Reverse Proxy: NO
- Base URL: http://jellyfin.lan:8096
- Networking: Bridge/NAT
- Storage: local
```

### Jellyfin logs

```shell
N/A
```

### Client / Browser logs

OpenWRT router log:

Thu Aug 15 20:32:01 2024 daemon.notice miniupnpd[3251]: remove port mapping 8096 TCP because it has expired

**Comment by gnattu** [comment]
This is unfortunately an implementation specific compatibility problem because we explicitly requires the lease lifetime to be 0, and in upnp definition it means 'indefinite', and most implementation will treat this map as forever mapping so it never expires. Your specific router adding a finite lifetime to lifetime=0 will not only break jellyfin but also a lot of other upnp clients, and force a upnp mapping request for like every 10 minutes will cause problems on another set of routers where those routers will open new ports over and over and never close the old ones. For your specific router you cannot use the upnp unfortunately but it should work for other routers that don't expire lifetime=0 leases.
