### ISSUE TITLE
Incorrect Formatting of .lrc Files Without Spaces Between Timestamps and Lyrics

### ISSUE THREAD

**Issue by TreeTrunk221** [jellyfin/jellyfin#12489]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

Description:
When uploading .lrc files, the formatting of the displayed lyrics depends on whether there is a space between the timestamp and the lyrics. If the .lrc file is formatted with a space, such as: 
[00:03.24] Ooh, ooh
[00:09.19] I, I just woke up from a dream
...
The lyrics display properly. However, when the .lrc file is formatted without a space between the timestamp and the lyrics, such as:
[00:00.000]Comes a rainstorm, put your rubbers on your feet
[00:06.873]Comes a snowstorm, you can get a little heat
...
The lyrics do not display correctly

### Reproduction steps

Upload an .lrc file with a space between timestamps and lyrics.
Observe that the lyrics are displayed correctly.
Upload an .lrc file without a space between timestamps and lyrics.
Observe that the lyrics are not displayed correctly.

### What is the current _bug_ behavior?

The .lrc file only displays the lyrics correctly when there is a space between the timestamp and the lyrics. When the space is omitted, the formatting is incorrect.

### What is the expected _correct_ behavior?

The .lrc file should display the lyrics correctly, regardless of whether or not there is a space between the timestamp and the lyrics.

### Jellyfin Server version

10.9.9+

### Specify the build version

10.9.9

### Environment

```markdown
- OS:Windows 11
- Linux Kernel:none
- Virtualization:
- Clients:All
- Browser:Brave
- FFmpeg Version:Jellyfin Media Player 1.11.1
- Playback Method:FLAC
- Hardware Acceleration:None
- GPU Model:RTX3090
- Plugins:
AniDB9.0.0.0
Status Active
AniSearch5.0.0.0
Status Active
AudioDB10.9.9.0
Status Active
Bookshelf11.0.0.0
Status Active
DLNA2.0.0.0
Status Active
Discogs1.0.0.0
Status Active
IMVDb4.0.0.0
Status Active
MusicBrainz10.9.9.0
Status Active
OMDb10.9.9.0
Status Active
OPDS Feed5.0.0.0
Status Active
Playback Reporting15.0.0.0
Status Active
Reports17.0.0.0
Status Active
Studio Images10.9.9.0
Status Active
Subtitle Extract4.0.0.0
Status Active
TMDb10.9.9.0
Status Active
VGMdb4.0.0.0
Status Active
Webhook15.0.0.0
Status Active
- Reverse Proxy:
- Base URL:
- Networking:TCP
- Storage:Many
```

### Jellyfin logs

```shell
Error processing request.
```

### Relevant screenshots or videos

![image](https://github.com/user-attachments/assets/9b49bfd8-28ec-4a13-9cd6-4201717d0afe)
![image](https://github.com/user-attachments/assets/d7523d48-faa9-4869-b5e2-060e083943b3)

### Additional information

Thank you!

**Comment by felix920506** [comment]
Related #11518 
Feels like upstream issue
