### ISSUE TITLE
hardlinks are treated as separate files which results in showing 2 entries for same episode/movie

### ISSUE THREAD

**Issue by c--w** [jellyfin/jellyfin#12491]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

When using sonnar or radarr to download new episodes/movies they have option to make hardlinks instead of copies (moving/renaming is not an option as it is often the case that content is still seeding in torrent client).
In such setup Jellyfin does not recognize that original file (downloaded by torrent client) and it's hardlink (created by sonnar/radarr) are the exact same file so in Jellyfin UI there is a duplicated entry for every such file. 

### Reproduction steps

Create hardlink for a media file inside library folder.

### What is the current _bug_ behavior?

Duplicated entry in Jellyfin UI for file with created hardlink.

### What is the expected _correct_ behavior?

Recognize hardlinks and don't show duplicated entries in UI

### Jellyfin Server version

10.9.9+

### Specify version number

10.9.9

### Specify the build version

10.9.9

### Environment

```markdown
- OS: Ubuntu
- Linux Kernel: 5.15.0-118-generic
- Virtualization:
- Clients: Web/Android
- Browser: Chrome
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
logs are not relevant - both files (original and hardlink) are found and processed by ffmpeg without errors and show same info properties in library
```

**Comment by sjorge** [comment]
(Unfortunately) jellyfin is path based, this applies to symlink and bind-mounts also.

The only way to avoid this is to remove one of the two paths from your library, or drop a `.ignore` file in one of the two series folders.

**Comment by Bond-009** [comment]
Working as intended.
