### ISSUE TITLE
Rename DLNA Server

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin#125]
When using the built in DLNA server, Jellyfin still identifies itself as “Emby”. We need to find the relevant line(s) in the code, and change it to the correct name.

(Thanks to Qurqar for reporting this in Riot/Matrix.)

**Comment by BnMcG** [comment]
I've submitted a PR that should do the trick, I think. If somebody could test it I'd be grateful.

**Comment by anthonylavado** [comment]
Merged in to dev. Thanks @BnMcG!
