### ISSUE TITLE
docker wipe out config folder

### ISSUE THREAD

**Issue by icf20** [jellyfin/jellyfin#1250]
1h ago there was a container update pushed  for some odd reason this update deleted everything on the /config folder and the users+ library+plugins had to be reconfigured

**Comment by sparky8251** [comment]
We recently pushed a 10.3.0 container in prep for the official 10.3.0 release. Guess you have autoupdate set in your docker management system.

How did you setup the docker container originally?

What was the complete command used/what ports, volumes, and options were set in the GUI?

No data should be being deleted.

**Comment by evertonstz** [comment]
I use ouroboros to pull new images, I didn't lost plugins and the data at /config seems to be fine, but after the update jellyfin refuses to work, seems to be related with ffprobe:

`ERROR(S): Option 'ffprobe' is unknown.`

[https://pastebin.com/Vt4wNurt](full log)

**Comment by icf20** [comment]
> Guess you have autoupdate set in your docker management system.
yep i have watchtower set to update

> How did you setup the docker container originally?

i dont follow you, what do you mean ? the folder setup?

**Comment by sparky8251** [comment]
Kind of? I'm asking for info on if you used volume or if you used the host filesystem and how you had it configured.

I'm kind of curious if you had volumes set so the update created new volumes making it appear that the config folder was wiped out.

**Comment by icf20** [comment]
is was all like the doc guide nothing fancy
disk1_cache_/blabla/cache/jellyfin for /cache
zfspool/blabla/config/jellyfin for /config
zfspool/blabla/multimedia for /media

**Comment by sparky8251** [comment]
Hmm... I wonder if @nvllsvm pushed a defective container that did something before pushing a corrected one?

We have had no other reports of a deletion of config data inside docker or otherwise so its hard to say what happened here.

I just hope you had backups so this is just a minor inconvenience for you :(

**Comment by evertonstz** [comment]
@sparky8251 I'm pretty sure he pushed at least two containers for the new version, the first one I got automatically with ouroboros and the second one I pulled manually right after I reported my problems here. The fist push he did wasn't even starting here, but my config files were not touched.

**Comment by nvllsvm** [comment]
@evertonstz Please share the output of this command. Do you know which image ID was the culprit?
```
docker image history jellyfin/jellyfin
```

**Comment by evertonstz** [comment]
@nvllsvm I sadly had to remake my server two days ago since I had a hardware failure, but since Ouroboros do notify me on Gotify I have the last notification it sent me about Jellyfin:

`jellyfin updated from 11e6303e05 to fa07cdd18e`

**Comment by sparky8251** [comment]
This appears resolved to me. Closing.
