### ISSUE TITLE
Catalogue does not load the plugin

### ISSUE THREAD

**Issue by rajinstar** [jellyfin/jellyfin#12515]
In my server, the plugin's catalog does not load that's why I can not install or uninstall any plugin to my Jellyfin server. Would anyone be able to solve the problem for me? I will send you the log file. Please solve the issue as soon as possible.

[Log_20240826.txt](https://github.com/user-attachments/files/16746351/Log_20240826.txt)

![image](https://github.com/user-attachments/assets/bd1c5b06-f97b-4293-a0d3-1c28453580fc)

**Comment by Bond-009** [comment]
Please fill out the issue template.

**Comment by Bond-009** [comment]
```
System.MissingMethodException: Method not found: 'Void MediaBrowser.Model.Plugins.PluginInfo..ctor()'.
   at n0tFlix.Channel.Crunchyroll.Plugin.GetPluginInfo()
```
From your logs it seems like you have an unsupported plugin installed, please delete the Crunchyroll plugin manually.

**Comment by Bond-009** [comment]
You also have an invalid plugin repo specified, you should remove that too.
`https://raw.githubusercontent.com/ShokoAnime/Shokofin/master/manifest-unstable.json`
