### ISSUE TITLE
Wrong client IP in activity log

### ISSUE THREAD

**Issue by platinum55** [jellyfin/jellyfin#1254]
**Describe the bug**
In the Admin-View on the right side "Activity" shows any user with the docker internal gateway IP address, in my case 172.17.0.1.
I looked into the packetflow with tcpdump and the packets have the correct (external) source-address. Seems to be a problem inside jellyfin

**System (please complete the following information):**
 - OS: Docker
 - Browser: Chrome
 - Jellyfin Version: 10.3.0
 - Reverse proxy: no

**Comment by sparky8251** [comment]
Unfortunately, docker obscures this information from the server (has to do with the container routing).

I do not know if we can fix this at all. Are there programs that can accurately report web client IPs on the server? I havent seen any...

**Comment by iojeda** [comment]
Hi I have this same issue.
![image](https://github.com/jellyfin/jellyfin/assets/5243583/ee77f278-465c-4e85-8576-f62b7af34cc7)
I am running Jellyfin in a Docker container.
I am using Nginx as a reverse proxy and also using Cloudflare for Web Application Firewall.
In Nginx I added a custom configuration so the real-ip is obtained from cf-connecting-ip

real_ip_header CF-Connecting-IP;

Nginx access logs register the Real client IP correctly (and this Nginx is on a Docker container itself)
However this is not the case for Jellyfin Server Activity logs.

Any clue on how to fix this (if it is a configuration issue from my side) or is it really a bug (I doubt it)?
Thanks
