### ISSUE TITLE
"Better" UI

### ISSUE THREAD

**Issue by Ondjultomte** [jellyfin/jellyfin#12563]
I'd like to see better, more clearer, not clean nor flat, ui.

Look at Emby and jellyseerr

Examples from Emby
Clear marking in the meny

![image](https://github.com/user-attachments/assets/466749cd-d0b9-4ba3-ac29-bfebacf33849)

Upper meny, clear and intuative what objects are optins and which is currently "marked"

![image](https://github.com/user-attachments/assets/2931b627-982f-431d-b4f0-f9b814d6ad96)

Jellyseerr also has a moern intuative UI, not too flat and easy to see what is a meny and just info text etc.

![image](https://github.com/user-attachments/assets/04333641-0b89-420b-b123-6ac8cb76e963)

**Comment by Bond-009** [comment]
So.. rounded corners? You can do that with custom CSS if you want. Not an issue.

**Comment by Ondjultomte** [comment]
I dont knwo, but not as flat :) something to accentuate little more that there is a meny. ok details but still there could improve the uix
