### ISSUE TITLE
Jellyfin 10.9.10 deb12 does not start service with core-dump because /var/cache/jellyfin is not chown'ed as jellyfin:jellyfin

### ISSUE THREAD

**Issue by MacharaStormwing** [jellyfin/jellyfin#12564]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

As the title states, when installing jellyfin on debian 12 the service does not start, failing with a core-dump.

### Reproduction steps

- Install jellyfin 10.9.10 from current debian repo.
- The jellyfin.sources file contains:
Types: deb
URIs: https://repo.jellyfin.org/debian
Suites: bookworm
Components: main
Architectures: amd64
Signed-By: /etc/apt/keyrings/jellyfin.gpg

- check with sudo systemctl status jellyfin. service is enabled but failed to start because of a core-dump.

### What is the current _bug_ behavior?

As explained, the service does not start but ends up with a core-dump, not even getting as far as logging anything in /var/log/jellyfin

### What is the expected _correct_ behavior?

Jellyfin should start up correctly.

I have found out this is because the caching directory /var/cache/jellyfin has chown jellyfin:adm.

Running
sudo chown jellyfin:jellyfin /var/cache/jellyfin
and restarting jellyfin with
sudo systemctl start jellyfin

Fixes the issue.

### Jellyfin Server version

10.9.9+

### Specify version number

10.9.10

### Specify the build version

10.9.10

### Environment

```markdown
- OS: Debian 12.6
- Linux Kernel: 6.1
- Virtualization: Proxmox 8.2
- Clients: -
- Browser: -
- FFmpeg Version: ?
- Playback Method: -
- Hardware Acceleration: -
- GPU Model: -
- Plugins: -
- Reverse Proxy: -
- Base URL: -
- Networking: -
- Storage: -
```

### Jellyfin logs

```shell
There are no log files in /var/log/jellyfin
```

**Comment by felix920506** [comment]
How are you installing Jellyfin? With the script or using the provided .deb package and apt?

**Comment by MacharaStormwing** [comment]
I tried both.
It did not work in either way.

**Comment by joshuaboniface** [comment]
So just to be clear, `/var/cache/jellyfin` existed, but was owned `root:root`?

**Comment by MacharaStormwing** [comment]
Not exactly.
It existed but was owned by jellyfin:adm instead of jellyfin:jellyfin
