### ISSUE TITLE
Issue with wrong metadata for shows

### ISSUE THREAD

**Issue by Scrub000** [jellyfin/jellyfin#12569]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

On downloaded shows such as NOVA or Man vs Wild, the episodes don't match what is shown on Jellyfin. File names are left as is from Linux ISO torrent sites.

### Reproduction steps

Download older show from Linux ISO torrent site
Place it where Jellyfin can see it
Notice that some episodes are different to what Jellyfin thinks they are

### What is the current _bug_ behavior?

Episodes don't match the metadata. E.g. a video on space is actually about animals.

### What is the expected _correct_ behavior?

Each episode is correct.

### Jellyfin Server version

10.9.10+

### Specify the build version

Not sure, but latest Docker build

### Environment

```markdown
- OS: OpenMediaVault
- Linux Kernel:
- Virtualization: Docker
- Clients: Server, All
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
On mobile so don't have
```

**Comment by maher-nakesh** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by felix920506** [comment]
Please follow the naming scheme defined in the document.

**Comment by felix920506** [comment]
Screenshots please.
