### ISSUE TITLE
Jellyfin 10.3 not showing library in Yatse 9.1.5

### ISSUE THREAD

**Issue by buggyro** [jellyfin/jellyfin#1257]
Hello,
I updated this morning to Jellyfin 10.3.
I removed and then re-added the Jellyfin server to Yatse as Jellyfin type per Jellyfin instructions.
Authentication worked, but the movies and TV Shows library would not show up.
Upon checking the Jellyfin log i found this warning:
[WRN] "USER" is not permitted to access Library "Media Folders".
The user is setup to access only some libraries in the Library access tab of the users settings.
If i check "Enable access to all libraries", then the library shows up in Yatse, and the warning does not appear.
This was not the case before.

1. Setup a user to have access only to some of the libraries you have in Jellyfin.
2. Add the Jellyfin server to Yatse, with the user above.
3. Library does not show up in Yatse

**Expected behavior**
In 10.2.2 this worked out of the box, showing the library, after adding the user in Yatse.

**Logs**
[WRN] "USER" is not permitted to access Library "Media Folders".

**System (please complete the following information):**
 - OS: Ubuntu 18.04.02 server
 - Browser: N/A
 - Jellyfin Version: 10.3.0
 - Reverse proxy: none

**Comment by anthonylavado** [comment]
I don’t have Yatse myself to test, but are you using the latest version? @tolriq let us know he recently pushed out an update that would handle our authentication changes...

**Comment by Tolriq** [comment]
If the host is correctly added then authentification is OK.

For the rest I have not tested all the cases but only use the default admin and a test account that have access to all.

Sounds like an issue in Jellyfin. @anthonylavado If you have android device as said in other post just mail mail and I'll send you licences.

**Comment by buggyro** [comment]
Yatse is latest version 9.1.5 released on 18.04.2019.
Authentication succeeds ok. I deleted then re added the server in Yatse per Jellyfin update instructions.
To view the library you don't need the paid version on Yatse, you need to only to play media on local devize (android phone).

**Comment by Tolriq** [comment]
Licence is needed for all non Kodi host add :(

**Comment by buggyro** [comment]
I didn't know, i already had license when i installed Jellyfin.

**Comment by buggyro** [comment]
Please let me know if you need any more logs or info.
Thanks

**Comment by Tolriq** [comment]
For Yatse part as always: https://yatse.tv/wiki/debug-yatse-kodi-remote :)

**Comment by Tolriq** [comment]
Pinging here :)  @anthonylavado did you get my answer to your mail? I see that no promo code where used and they have expiration date :)

**Comment by anthonylavado** [comment]
@tolriq There should have been three used... I will follow up.

**Comment by sparky8251** [comment]
Is this still an issue or can it be closed? I know we had issues around auth that spred into a few of the 10.3.z releases that could have caused this. They *should* all be fixed now...

**Comment by buggyro** [comment]
It is solved. I closed it.
Thank you.
