### ISSUE TITLE
[Bug] Number of items in collection reflects Unwatched only

### ISSUE THREAD

**Issue by rxbrad** [jellyfin/jellyfin#12580]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

In the Movies view with no filters applied, a collection of 4 movies (1 watched, 3 unwatched) shows a "3" in the upper-right corner.  No filters are applied to this view, so expected behavior would be that both watched and unwatched films are included in this count.

![image](https://github.com/user-attachments/assets/e469fb20-643a-45dc-b9b0-c25b1145d119) 
![image](https://github.com/user-attachments/assets/c8c5494d-67c0-447c-a831-e3edbbfa8eda)

![image](https://github.com/user-attachments/assets/dd13a178-a860-4b2e-9dba-6031dfa03691)

### Reproduction steps

Create a collection with 4 movies.  Set 1 to watched status, and 3 to unwatched.  Browse to the Movie library, with no filters on, in any view (posters, banners, etc).

### What is the current _bug_ behavior?

Number indicator counts only unwatched movies

### What is the expected _correct_ behavior?

Number indicator should count all movies.

### Jellyfin Server version

10.9.10+

### Specify the build version

10.9.10

### Environment

```markdown
- Virtualization: Docker container: jellyfin/jellyfin:10.9.10
- Clients: Android / Web
- Browser: Firefox / Chrome
```

### Jellyfin logs

```shell
n/a
```

**Comment by felix920506** [comment]
This is working as intended.
