### ISSUE TITLE
Search in webUI does not find words in different order

### ISSUE THREAD

**Issue by Medrantol** [jellyfin/jellyfin#12596]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

When using the search box in the WebUI, searching for 2 or more words in different order than the original title, won't give any results. eg: "new world" = result ok,  "world new" = no results. Also, adding spaces return no results ([issue here](https://github.com/jellyfin/jellyfin/issues/11868). Same problem applies when adding "( )" or similar symbols.

### Reproduction steps

Click on the magnifying glass in the WebUI
Enter some words of the name of a movie, not in the same order.
See no results
Type exactly the title of the movie give results.

### What is the current _bug_ behavior?

no search results

### What is the expected _correct_ behavior?

search results

### Jellyfin Server version

10.9.10+

### Specify the build version

10.9.6

### Environment

```markdown
- OS: Windows 10
- Linux Kernel: none
- Virtualization: none
- Clients: Browser
- Browser: Chromium: 128.0.6613.27
- FFmpeg Version: N/A
- Playback Method: N/A
- Hardware Acceleration: N/A
- GPU Model: N/A
- Plugins: none
- Reverse Proxy: N/A
- Base URL: none
- Networking: Host
- Storage: local
```

### Jellyfin logs

```shell
N/A
```

**Comment by crobibero** [comment]
Yes, this is working as implemented and therefore not a bug.
