### ISSUE TITLE
Null value in External Ids from TMDB Plugin

### ISSUE THREAD

**Issue by jorensanbar** [jellyfin/jellyfin#12658]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

When scanning a new TV show (Anime) the External ID information cannot be obtained from TMBD

### Reproduction steps

1. Create a new folder for "Konjiki no Gash Bell!! (2003) [tmdbid=35894]" > Season 01
2. Put any file for episode S01E07
3. Scan the library

### What is the current _bug_ behavior?

When the scan starts, it fails to obtain the External IDs for IMDB and TVDB. It only obtains the External IDs for FreeBase and TVRAGE.

In this image, the external Ids return null for IMDB and TVDB. But Firebase and TVRage can get the values.

![367929955-1ea900c2-74ed-4f04-84c9-e0f11b807caf](https://github.com/user-attachments/assets/c687b242-b0e1-4852-95da-bd3d802d93b9)

All extenal id exist in web:
IMDB+TVDB+FreeBase+TVRAGE
![367930031-d6a0b274-2d45-4cdc-9e6d-7337bb351233](https://github.com/user-attachments/assets/5497fd84-3ed1-4eca-a8fe-ad527b2ca3b0)

### What is the expected _correct_ behavior?

Get the IDs and assign them to the episode so that other Providers can fill in the missing information.

### Jellyfin Server version

10.9.11+

### Specify the build version

10.9.11

### Environment

```markdown
- OS: DEBIAN
- Virtualization: DOCKER
- Clients: Android TV, Web
- Browser: Chrome, Firefox
- Plugins: TMDB, TVDB, AniDB
```

### Jellyfin logs

```shell
-none-
```

**Comment by felix920506** [comment]
It is supposed to be a dash, not an equal sign. Please try with the dash in place of the equal sign.

**Comment by jorensanbar** [comment]
Hello Felix!

The report is not about identification, the equal sign is allowed and enabled in Emby Naming.

The report shows a failure in the extraction of information.. 

If you see the images, the information extracted from the episode is incomplete. (External ID Method). In the episode information there is data for the External IDs of IMDB, TVDB, FreeBase and TVRage, but if you look at the model, it only contains information for FreeBase and TVRage, the rest is null.

**Comment by felix920506** [comment]
This is Jellyfin and the code base has diverged from Emby many years ago. Please follow the convention Jellyfin uses.

**Comment by jorensanbar** [comment]
Changed to dash, clear the collections and library, scan again and error continues, don't get the external id's for episodes.

The identification of the series is exactly the same with Dash or with Equal.

**Comment by felix920506** [comment]
The interface in your screenshot doesn't really look like Jellyfin. What is the software you are using?

**Comment by jorensanbar** [comment]
> The interface in your screenshot doesn't really look like Jellyfin. What is the software you are using?

Is Source Code of Jellyfin.

BTW: This error is due to the TMDB API, since they have a cache of more than 8 hours, for this reason, although the information is displayed on the page, the API does not provide the same information.

I had to create a system to connect to the API and review the information in real time.

![imagen](https://github.com/user-attachments/assets/9efed9d4-36b3-49f3-84ac-076daadff511)
