### ISSUE TITLE
core-dump

### ISSUE THREAD

**Issue by htttito** [jellyfin/jellyfin#1265]
I hope anyone can help!
Ubuntu Server 18.04

My error:

jellyfin.service - Jellyfin Media Server
   Loaded: loaded (/lib/systemd/system/jellyfin.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/jellyfin.service.d
           └─jellyfin.service.conf
   Active: failed (Result: core-dump) since Sat 2019-04-20 21:33:22 CEST; 5s ago
  Process: 3184 ExecStart=/usr/bin/jellyfin ${JELLYFIN_RESTART_OPT} ${JELLYFIN_FFMPEG_OPT} ${JELLYFIN_SERVICE_OPT} ${JELLYFIN_NOWEBAPP_OPT} (code=dumped, signal=ABRT)
 Main PID: 3184 (code=dumped, signal=ABRT)

Apr 20 21:33:22 server systemd[1]: jellyfin.service: Service hold-off time over, scheduling restart.
Apr 20 21:33:22 server systemd[1]: jellyfin.service: Scheduled restart job, restart counter is at 10.
Apr 20 21:33:22 server systemd[1]: Stopped Jellyfin Media Server.
Apr 20 21:33:22 server systemd[1]: jellyfin.service: Start request repeated too quickly.
Apr 20 21:33:22 server systemd[1]: jellyfin.service: Failed with result 'core-dump'.
Apr 20 21:33:22 server systemd[1]: Failed to start Jellyfin Media Server.

**Comment by pedro-araujo** [comment]
Have you tried to delete the directory /var/lib/jellyfin/plugins/ ?

Old Emby plugins need to be reinstalled.

**Comment by htttito** [comment]
OK i will test it

**Comment by htttito** [comment]
Thank you very very much !!! That helps :-)  (tvheadend plugin)

**Comment by dukenukemx** [comment]
I wanna say thanks as this was my problem too.  The TVHeadEnd plugin was broken for me as well.  I had to  delete it under /var/lib/jellyfin/plugins/ as suggested by @pedro-araujo .
