### ISSUE TITLE
Scan Library no longer respecting item lock state for recreating directories

### ISSUE THREAD

**Issue by CHNOK** [jellyfin/jellyfin#12677]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

Previously for Jellyfin 10.8.x version and at least 10.9.4 and earlier versions, setting item lock states would prevent recreation of item directories in libraries without using the item's refresh metadata.

Example 1: You would scan your media library and a new item would populate. You might have a special alongside your regular season 1 in one physical folder which would automatically create a 'Specials' folder.
   To get around this, you could for a long time temporarily set the special to an existing season then merge by using the "Scan for new and updated files" to delete the virtual folder. Locking the item after this would prevent library-wide scans from automatically re-creating the original directories after the episode was set back to season 0/as a special.

Current implementation now ignores item lock status and re-scans and then recreates the items default folder states. This forces much stricter file directory management to maintain a neat and tidy library for media even in cases where it would interrupt seeding and makes Jellyfin less usable as a plug-and-play option for many common TV show folder hierarchies.

### Reproduction steps

1. Add a new series to the Jellyfin media directory
2. Login with an admin account in Chrome/Firefox
3. Wait for automatic library scan or manually initiate
4. Go to item and find unwanted virtual folder in cases where physical folder doesn't exist specifically for season
5. Set episode to existing season and re-scan to remove virtual folder
6. Lock item
7. Wait for next library scan or begin one
8. Find manual file management overridden

### What is the current _bug_ behavior?

The overwriting of custom folder merges and the scanning of files in locked items.

### What is the expected _correct_ behavior?

A show should not and did not have its folder directory re-scanned and recreated  for versions 10.8.x and early 10.9.x. and should be skipped for scanning for new media or recreating folders during library-wide scan when locked.

### Jellyfin Server version

10.9.11+

### Specify the build version

10.9.11

### Environment

```markdown
- OS: Windows 11
- Linux Kernel:
- Virtualization: N/A
- Clients:Browser
- Browser: Firefox 130
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
[2024-09-21 12:33:50.924 -08:00] [INF] [61] MediaBrowser.Providers.TV.SeriesMetadataService: Removing virtual season 0 in series "Supernatural"
[2024-09-21 12:33:50.925 -08:00] [INF] [61] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "Specials", Path: "", Id: a4610363-0727-357a-0e26-1dc036cf0bfe
[2024-09-21 12:34:14.698 -08:00] [INF] [42] MediaBrowser.Providers.TV.SeriesMetadataService: Creating Season "Specials" entry for "Supernatural"
```

### Additional information

Likely related to the series of reworks to season handling starting from #12240.

**Comment by JPVenson** [comment]
Hey this is not a bug but intended. The previous behavior was a unintended mistake.
For jellyfin the folder structure always comes first and we do not take "seeding" into any account when designing our architecture.
You can use `.ignore` files as the intended way to exclude folders.

**Comment by CHNOK** [comment]
@JPVenson That is unfortunate. The catch-all solution you provided with adding a `.ignore` simply removes a folder from your library during the next scan media task instead of excluding a series from being re-scanned which doesn't apply to what I was trying to do unless I'm missing some other usage. Please correct if not.

For the sake of anyone else who comes across this issue. Altogether ignoring this context specifically for a minute. Unless the design schema plans to have no situation where "scan media library" is allowed to exclude an item period, is there any other _intended_ method currently or planned that prevents re-scanning of specific items?

**Comment by JPVenson** [comment]
i am not aware of any existing feature.jellyfin.org request but please check yourself.
