### ISSUE TITLE
Multiple ffmpeg processes while using chromecast

### ISSUE THREAD

**Issue by platinum55** [jellyfin/jellyfin#1268]
**Describe the bug**
When using Chromecast Player, and especially when seeking via Chromecast, the Jellyfin Server spawns parallel ffmpeg processes, saturating both the CPU and response time of the web-frontend.

I looked thoroughly and found that chromecast seems to switch between bitrates, thus making Jellyfin spawning multiple ffmpeg transcoding processes, like this(ps aux | grep ffm):

```
root     18387  143  2.8 875744 229508 ?       Rl   01:35  32:32 /usr/local/bin/ffmpeg -ss 00:50:56.057 -f matroska,webm -i file:/stuff/movies/xxxxxxxxx.mkv -map 0:0 -map 0:1 -map -0:s -codec:v:0 libx264 -force_key_frames expr:gte(t,n_forced*5) -vf scale=trunc(min(max(iw\,ih*dar)\,1920)/2)*2:trunc(ow/dar/2)*2 -copyts -avoid_negative_ts disabled -start_at_zero -pix_fmt yuv420p -preset superfast -crf 23 -maxrate 9360001 -bufsize 18720002 -profile:v high -level 4.1 -x264opts:0 subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none -vsync -1 -map_metadata -1 -map_chapters -1 -threads 2 -codec:a:0 aac -strict experimental -ac 2 -ab 384000 -af volume=2 -y /config/transcoding-temp/2c62c074fb1e5b59b6e0991d21cc782d.mkv
root     18511  139  2.8 874856 228980 ?       Rl   01:36  30:07 /usr/local/bin/ffmpeg -ss 01:31:06.966 -f matroska,webm -i file:/stuff/movies/xxxxxxxxx.mkv -map 0:0 -map 0:1 -map -0:s -codec:v:0 libx264 -force_key_frames expr:gte(t,n_forced*5) -vf scale=trunc(min(max(iw\,ih*dar)\,1920)/2)*2:trunc(ow/dar/2)*2 -copyts -avoid_negative_ts disabled -start_at_zero -pix_fmt yuv420p -preset superfast -crf 23 -maxrate 9360001 -bufsize 18720002 -profile:v high -level 4.1 -x264opts:0 subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none -vsync -1 -map_metadata -1 -map_chapters -1 -threads 2 -codec:a:0 aac -strict experimental -ac 2 -ab 384000 -af volume=2 -y /config/transcoding-temp/b699c0b9f11317d92249c4bb7bf9bd7d.mkv

```

As you can see, each process uses >100% CPU, thus reduces the maximum possible users watching movies in parallel, which is of course bad.

**To Reproduce**

1. Start movie via chromecast
2. connect the jellyfin via ssh
3. ps aux | grep ffm
4. Seek in the video which is just playing
5. ps aux | grep ffm
6. See multiple ffmpeg instances for the same user/movie

**Expected behavior**
Jellyfin should kill any existing ffmpeg process for this user/movie when spawning a new one(thru seek or something else)

**System (please complete the following information):**
 - OS: Docker
 - Browser: Chrome
 - Jellyfin Version: 10.3.0 (git pull & build yesterday)
 - Reverse proxy: no

**Additional context**
Tried to reduce the bitrate via "Playback" Settings for the user, but chromecast still switches bitrate in playback(the user who is watching doesnt notice this)

**Comment by surdu** [comment]
In my case it also causes the streaming to stall on Chromecast on an AMD Athlon 220GE @3.4GHz. 

Also, after the playback is terminated, the ffmpeg processes continue to be alive and keep my CPU at 100%.

**Comment by mazzystr** [comment]
I'm seeing this behavior also but not all the time. I have tons of cpu/memory on my box so I'll get 10 ffmpeg processes running before I start noticing a problem.  The problem manifests itself as cyclic 10 sec of good streaming then a 5 sec pause.  I have to manually kill the procs then everything is awesome again.

**Comment by mazzystr** [comment]
```
[root@cube ~]# ps -ef | grep ffmpeg
root     3964691 3964678  0 20:47 ?        00:00:00 /bin/sh -c dotnet /jellyfin/jellyfin.dll     --datadir /config     --cachedir /cache     --ffmpeg /usr/local/bin/ffmpeg
root     3964708 3964691  2 20:47 ?        00:00:59 dotnet /jellyfin/jellyfin.dll --datadir /config --cachedir /cache --ffmpeg /usr/local/bin/ffmpeg
root     3964745 3964708 99 20:47 ?        02:14:59 /usr/local/bin/ffmpeg -ss 00:00:17.392 -i file:/media/Movies/A.I. Artificial Intelligence (2001)/ A.I. Artificial Intelligence (2001).mkv -map 0:0 -map 0:2 -codec:v:0 libx264 -force_key_frames expr:gte(t,n_forced*5) -copyts -avoid_negative_ts disabled -start_at_zero -filter_complex [0:4]scale=1920:1080:force_original_aspect_ratio=decrease[sub];[0:0][sub]overlay,scale=trunc(min(max(iw\,ih*dar)\,1920)/2)*2:trunc(ow/dar/2)*2 -pix_fmt yuv420p -preset superfast -crf 23 -maxrate 4538692 -bufsize 9077384 -profile:v high -level 4.1 -x264opts:0 subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none -vsync -1 -map_metadata -1 -map_chapters -1 -threads 0 -codec:a:0 ac3 -ac 6 -ab 384000 -y /config/transcoding-temp/fe775060b4e99e019ed11ae234b76f7d.mkv
root     3965765 3964708 99 20:49 ?        01:31:48 /usr/local/bin/ffmpeg -ss 00:00:20.594 -i file:/media/Movies/blah.mkv -map 0:0 -map 0:2 -codec:v:0 libx264 -force_key_frames expr:gte(t,n_forced*5) -copyts -avoid_negative_ts disabled -start_at_zero -filter_complex [0:4]scale=1920:1080:force_original_aspect_ratio=decrease[sub];[0:0][sub]overlay,scale=trunc(min(max(iw\,ih*dar)\,1280)/2)*2:trunc(ow/dar/2)*2 -pix_fmt yuv420p -preset superfast -crf 23 -maxrate 2552000 -bufsize 5104000 -profile:v high -level 4.1 -x264opts:0 subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none -vsync -1 -map_metadata -1 -map_chapters -1 -threads 0 -codec:a:0 ac3 -ac 6 -ab 384000 -y /config/transcoding-temp/1536ea3e37727110623f8f2235640b22.mkv
root     3978871 3964708 99 21:15 ?        00:27:19 /usr/local/bin/ffmpeg -ss 00:00:21.880 -i file:/media/Movies/blah.mkv -map 0:0 -map 0:2 -codec:v:0 libx264 -force_key_frames expr:gte(t,n_forced*5) -copyts -avoid_negative_ts disabled -start_at_zero -filter_complex [0:4]scale=1920:1080:force_original_aspect_ratio=decrease[sub];[0:0][sub]overlay,scale=trunc(min(max(iw\,ih*dar)\,1920)/2)*2:trunc(ow/dar/2)*2 -pix_fmt yuv420p -preset superfast -crf 23 -maxrate 4669367 -bufsize 9338734 -profile:v high -level 4.1 -x264opts:0 subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none -vsync -1 -map_metadata -1 -map_chapters -1 -threads 0 -codec:a:0 ac3 -ac 6 -ab 384000 -y /config/transcoding-temp/b58796c73e18bb215098c257e33388ff.mkv
root     3983741 3964047  0 21:25 pts/0    00:00:00 grep --color=auto ffmpeg
```

**Comment by wippozippo** [comment]
I'm experiencing the same issue, ffmpeg processes don't get killed and they build up until I have 3-4 and playback starts to stutter. I then have to kill all the processes and restart playback. 

It happens for me like this: 
I start playback of an episode
I realize I selected the wrong subtitles and change them, for me this just kills the subtitles
I stop playback
Start new playback with correct subtitles, but this time it's choppy because I have multiple ffmpeg instances running
I then kill them using task manager and restart playback

I don't use hardware encoding

**Comment by LukeAbellSmith** [comment]
I am also having this problem.
Pretty much exactly like Platinum described.

**Comment by JustAMan** [comment]
Got any server logs? Preferably with debug enabled.

**Comment by LukeAbellSmith** [comment]
Not on hand, but I can enable debug if you tell me how, and I can upload one if/when it happens again.

**Comment by LukeAbellSmith** [comment]
I found some logs.  10MB of them. 
Any chance you can tell me what you're looking for, or have a quick way to sanitize them?

**Comment by JustAMan** [comment]
Here's how to enable debug logging: https://github.com/jellyfin/jellyfin/issues/1130#issuecomment-474083964

It's pretty hard to describe what I'm looking for, mostly information on how ffmpeg transcode was launched or stopped. Your first potential term to search the logs for would be "transcode" I think.

**Comment by LukeAbellSmith** [comment]
You want the Jellyfin log, right? not the ffmpeg log?

**Comment by JustAMan** [comment]
> You want the Jellyfin log, right? not the ffmpeg log?

Yes. ffmpeg logs aren't needed here

**Comment by LukeAbellSmith** [comment]
Well, I removed all the SQL queries, and sanitized it a bit. Hopefully this helps. If I get the lag issue again, I'll post that log.
[jellyfin_072.log](https://github.com/jellyfin/jellyfin/files/3759464/jellyfin_072.log)

**Comment by wippozippo** [comment]
Actually this issue hasn't appeared anymore for me since updating to 10.4.0.

**Comment by JustAMan** [comment]
@LukeAbellSmith thanks! Nothing standing out in the logs, so if you face the issue again in 10.4.0 or later please report back.

**Comment by surdu** [comment]
I too don't see the problem anymore after upgrading to the latest version. There was a _hint_ of lag at some point, but it quickly recovered. Glad to see this fixed 😁

**Comment by LukeAbellSmith** [comment]
This seems to have happened to me again at least once. I'll try to post the log next time it happens.

**Comment by mcrosson** [comment]
I just ran into this same issue. I'm seeing >1 ffmpeg process using nvenc whenever I seek using the chromecast protocol on a shield tv. If i use the native android tv app on the shield tv it works fine, single ffmpeg processing using nvenc and no stutters.

I've also seen this issue happen when I turn subs on/off (srt and pgs inside mkv).

I'm currently running Jellyfin 10.5.5. inside docker on a xeon cpu with gtx 1060 gpu.

**Comment by neopc10** [comment]
This is fixed on the new unstable caster.

**Comment by rafwes** [comment]
@neopc10 

Are we getting this on the next 10.6 point release? Or is this only meant for a later major release? Thanks!

**Comment by neopc10** [comment]
Try going to Settings->Playback and switching to the Nightly/Unstable Chromecast client.
