### ISSUE TITLE
Hardware acceleration playback error on old Intel GPU

### ISSUE THREAD

**Issue by grabbel** [jellyfin/jellyfin#12694]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

on Jellyfin 10.8.13 Hardware acceleration works as expected.
Jellyfin runs as a service under a locale account.
upgrading to:
10.10.0 Build version 2024092305
and 10.9.11

every file i play that needs transcoding i get:
Playback failed due to a fatal player error
downgrading to 10.8.13 Hardware acceleration works as expected and i can play all files.

### Reproduction steps

Reproduction steps:
Play any mediafile that requieres transcoding.

### What is the current _bug_ behavior?

Playback failed due to a fatal player error

### What is the expected _correct_ behavior?

transcoding the file using Hardware acceleration as it does on 10.8.13 

### Jellyfin Server version

10.9.11+

### Specify unstable release number

 2024092305

### Specify the build version

 10.10.0

### Environment

```markdown
- OS:Windows 10
- Clients: firefox/chromecast
- FFmpeg Version: ffmpeg version 7.0.2-Jellyfin
- Playback Method:
- Hardware Acceleration:yes qsv
- GPU Model: HD4600
- intel driver 20.19.15.5171 (latest for HD4600)
```

### Jellyfin logs

```shell
ffmpeg.exe -analyzeduration 200M -probesize 1G -f matroska,webm -init_hw_device d3d11va=dx11:,vendor=0x8086 -init_hw_device qsv=qs@dx11 -filter_hw_device qs -hwaccel d3d11va -hwaccel_output_format d3d11 -noautorotate -threads 2 -i file:"*cut*.mkv" -noautoscale -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_qsv -preset veryfast -b:v 292000 -maxrate 292000 -bufsize 584000 -profile:v:0 high -level 41 -g:v:0 72 -keyint_min:v:0 72 -vf "setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,hwmap=derive_device=qsv,scale_qsv=w=960:h=402:format=nv12" -codec:a:0 libfdk_aac -ac 2 -ab 128000 -af "volume=2" -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type fmp4 -hls_fmp4_init_filename "F:\transcoding-temp\5ac2b5fc4facf28fd240b15f666342ac-1.mp4" -start_number 0 -hls_segment_filename "F:\transcoding-temp\5ac2b5fc4facf28fd240b15f666342ac%d.mp4" -hls_playlist_type vod -hls_list_size 0 -y "F:\transcoding-temp\5ac2b5fc4facf28fd240b15f666342ac.m3u8"


ffmpeg version 7.0.2-Jellyfin Copyright (c) 2000-2024 the FFmpeg developers
  built with clang version 18.1.8
  configuration: --cc=clang --pkg-config-flags=--static --extra-cflags=-I/clang64/ffbuild/include --extra-ldflags=-L/clang64/ffbuild/lib --prefix=/clang64/ffbuild/jellyfin-ffmpeg --extra-version=Jellyfin --disable-ffplay --disable-debug --disable-doc --disable-sdl2 --disable-ptx-compression --enable-lto=thin --enable-gpl --enable-version3 --enable-schannel --enable-iconv --enable-libxml2 --enable-zlib --enable-lzma --enable-gmp --enable-chromaprint --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libharfbuzz --enable-libass --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libwebp --enable-libvpx --enable-libzimg --enable-libx264 --enable-libx265 --enable-libsvtav1 --enable-libdav1d --enable-libfdk-aac --enable-opencl --enable-dxva2 --enable-d3d11va --enable-d3d12va --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      59.  8.100 / 59.  8.100
  libavcodec     61.  3.100 / 61.  3.100
  libavformat    61.  1.100 / 61.  1.100
  libavdevice    61.  1.100 / 61.  1.100
  libavfilter    10.  1.100 / 10.  1.100
  libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100
[AVHWDeviceContext @ 00000173d61a79c0] Using device 8086:0412 (Intel(R) HD Graphics 4600).
[AVHWDeviceContext @ 00000173d6225440] Error creating a MFX session: -9.
Device creation failed: -1313558101.
Failed to set value 'qsv=qs@dx11' for option 'init_hw_device': Unknown error occurred
Error parsing global options: Unknown error occurred
```

**Comment by gnattu** [comment]
> Jellyfin runs as a service under a locale account.

Please don't. Run as service will usually break hardware acceleration due to driver and windows context isolations. If you want to use hardware acceleration please run as tray app and try again. See https://github.com/intel/cartwheel-ffmpeg/issues/334 for more info and we can help you little.

**Comment by grabbel** [comment]
Ok i reinstalled 10.9.11 being logged in and not through remote desktop or as service and run jellyfin as tray app.
Unfortunately i get the same error.

```
[AVHWDeviceContext @ 0000021b7437b340] Using device 8086:0412 (Intel(R) HD Graphics 4600).
[AVHWDeviceContext @ 0000021b72d0b480] Error creating a MFX session: -9.
Device creation failed: -1313558101.
Failed to set value 'qsv=qs@dx11' for option 'init_hw_device': Unknown error occurred
Error parsing global options: Unknown error occurred
```

**Comment by gnattu** [comment]
Then you are facing a even more nasty bug that Intel does not want to fix: https://github.com/intel/libvpl/issues/105

I'm sorry but you have to stick to FFmpeg 5 now.  Download it from https://repo.jellyfin.org/?path=/ffmpeg/windows/latest-5.x/amd64 and overwrite the one in your jellyfin install folder.

**Comment by grabbel** [comment]
> Then you are facing a even more nasty bug that Intel does not want to fix: [intel/libvpl#105](https://github.com/intel/libvpl/issues/105)
> 
> I'm sorry but you have to stick to FFmpeg 5 now. Download it from https://repo.jellyfin.org/?path=/ffmpeg/windows/latest-5.x/amd64 and overwrite the one in your jellyfin install folder.

Thx going back to FFmpeg 5 seems to work with 10.9.11

**Comment by nyanmisaka** [comment]
@gnattu I think this patch should fix all the problems. Just retry the old function if the new one fails. But I'm not sure when Intel will remove these deprecated functions.

https://trac.ffmpeg.org/ticket/10537

**Comment by gnattu** [comment]
I'm still a little bit concerned about adding such things that we don't know when will stop working. We can try that to see if it helps though.

**Comment by nyanmisaka** [comment]
> I'm still a little bit concerned about adding such things that we don't know when will stop working. We can try that to see if it helps though.

Considering that Intel actually mentions in the documentation to use MFX_DEPRECATED_OFF to disable compiler warnings, I guess they won't remove it anytime soon.

https://github.com/intel/libvpl/blob/5f6bd8a1e753c8f63a3fd8b36894d6968b808a6d/api/vpl/mfxsession.h#L91

For comparison, OpenCL in FFmpeg is also built on top of the deprecated 1.2 version.

**Comment by nyanmisaka** [comment]
Hi @grabbel, can you help us test whether this patched ffmpeg7 can work properly in your environment?

https://github.com/jellyfin/jellyfin-ffmpeg/actions/runs/11013770444/artifacts/1971716405

**Comment by grabbel** [comment]
> Hi @grabbel, can you help us test whether this patched ffmpeg7 can work properly in your environment?

Yes no problem just tried it and it works in my environment playing files and Hardware acceleration.
It throws the error and fallbacks using the other routine and playback starts.

`ffmpeg version 7.0.2-Jellyfin Copyright (c) 2000-2024 the FFmpeg developers
  built with clang version 18.1.8
[AVHWDeviceContext @ 000002b556fe6740] Using device 8086:0412 (Intel(R) HD Graphics 4600).
[AVHWDeviceContext @ 000002b5570688c0] Error creating a MFX session: -9.
Input #0, matroska,webm, from 'file:H:\***.mkv':`

**Comment by nyanmisaka** [comment]
> > Hi @grabbel, can you help us test whether this patched ffmpeg7 can work properly in your environment?
> 
> Yes no problem just tried it and it works in my environment playing files and Hardware acceleration. It throws the error and fallbacks using the other routine and playback starts.
> 
> `ffmpeg version 7.0.2-Jellyfin Copyright (c) 2000-2024 the FFmpeg developers built with clang version 18.1.8 [AVHWDeviceContext @ 000002b556fe6740] Using device 8086:0412 (Intel(R) HD Graphics 4600). [AVHWDeviceContext @ 000002b5570688c0] Error creating a MFX session: -9. Input #0, matroska,webm, from 'file:H:\***.mkv':`

Thanks for confirming this. Our new ffmpeg will automatically fall back to the old initialization method when the default method fails.
