### ISSUE TITLE
Discussion: Central servers/phone home/discovery etc

### ISSUE THREAD

**Issue by jkaberg** [jellyfin/jellyfin#127]
I'd like to start up an discussion around the old functionality that Emby (and Plex) seem's so fond of; namely connecting to their central servers for discovery etc. 

IMHO this should be optional, while not "locking" anyone out of the experience as is (clients etc. should work as normal, the user just need to enter the correct server url). I think that Jellyfin should try to bundle whatever it can into the server core (assets etc.), while obviously stuff like remote API's will need to external (the fewer external calls the better).

I saw the issue over at https://github.com/jellyfin/jellyfin/issues/7, however my take on that one was it was about assets and not connecting clients/servers.

**Comment by JustAMan** [comment]
Could you please elaborate more on what you want to achieve by centralizing something? What benefits to end users?

**Comment by RazeLighter777** [comment]
I am against centralizing in any way. If you do include it, it should be opt in rather than opt out.

**Comment by joshuaboniface** [comment]
Ideally we'd like to remove *all* centralization functionality as part of the direction change we seek to make with Jellyfin over Emby. Ultimately the server should never be calling out anywhere except the metadatabases and the user in complete control of their data.

**Comment by SpootDev** [comment]
Eh.....Emby's call home BS is one of the reasons I dumped Emby long ago.   I hate software that calls home.  About the only thing that doesn't bother me is version checks and that should be optional too.  IMHO.

**Comment by gerroon** [comment]
There are no central servers as far as I can tell. So the idea of keeping old functionality is not going to work with the current fork. Current fork tries to do the opposite of what you are asking for.

Maybe some community members can get together and run some central servers as you put it, but not sure if there is code for such servers atm.

**Comment by bobberb** [comment]
Being charitable, the OP would appreciate some "discovery" (of other libraries I can only presume) via federation or p2p sharing-to-non-users functionality.

**Comment by jkaberg** [comment]
My intention is to NOT centralized (the opposite) jellyfin et all (think you guys misread my intentions). 

What I mean is that I want the "centralized experience" to survive while removing any centralized components, eg clients should work as before without calling home to some central server.

Same with assets such as JS/CSS etc., they should be bundled rather then externally linked.

I repeat, **I DO NOT** want Jellyfin to call any external servers other then the really necessary ones (TMDB, TVDB etc..)

**Comment by SpootDev** [comment]
Ah, yes, misread some of the intentions then.  Yeah, I also prefer to have the js/css min'd and included in the server itself.  CDN's can be handy but can be a PITA as well.

**Comment by JustAMan** [comment]
I think we already have all assets bundled in. If that is not the case please open a separate issue.

**Comment by hawken93** [comment]
I think it is the case that you have to enter the URL to connect, and the jellyfin apps are on their way as far as I can tell.

Nextcloud seems to have an idea that I would not mind exploring:
"Trusted servers
Federation allows you to connect with other trusted servers to exchange the user directory. For example this will be used to auto-complete external users for federated sharing."

I think this idea could be explored, but the degree of integration can give everything from a little work (redirect to neighbor servers) to massive amounts of work (combining search results and libraries..)

**Comment by hawken93** [comment]
I want to add that for the plugin catalogue case and other cases where we would want to phone somewhere, making it configurable is key to allow someone the freedom to run it in their own ecosystem
