### ISSUE TITLE
Adding folder to library results in erroneous path could not be found error

### ISSUE THREAD

**Issue by bugfixin** [jellyfin/jellyfin#1270]
**Describe the bug**

**To Reproduce**

1. Build linux-x64 from master branch of git via ./build linux-x64 all
2. Add a new media library
3. Click the + icon next to Folders
4. Select a folder
5. Select "OK"
6. Error message appears with "The path could not be found. Please ensure the path is valid and try again." but folder is added.

**Expected behavior**
No error message to appear.

**Logs**
```
[05:41:08] [ERR] Error processing request
System.NullReferenceException: Object reference not set to an instance of an object.
   at Emby.Server.Implementations.Services.ServiceHandler.CreateRequest(HttpListenerHost host, IRequest httpReq, RestPath restPath, ILogger log
ger)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, IResponse httpRes, I
Logger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localP
ath, CancellationToken cancellationToken)
```

**Screenshots**

![image](https://user-images.githubusercontent.com/31485244/56465923-9ae24680-63bd-11e9-8c85-a90be677d1e3.png)

**System (please complete the following information):**
 - OS: Debian
 - Browser: Chrome
 - Jellyfin Version: 10.3.0 (master branch
 - Reverse proxy: none

**Additional context**

**Comment by bugfixin** [comment]
Further testing this seems to only occur with the master branch of jellyfin as of right now - the release-10.3.z branch does not exhibit this behavior.

In testing this, I created a new VM to check whether it was related to old configurations, which led me to discover that with the build process described above on the master branch, it is impossible to get past the first page of the startup wizard.

**Comment by bugfixin** [comment]
Diving into this, this occurs because the content type is submitted as application/x-www-form-urlencoded when RequestHelper.GetRequestReader is not expecting it - this results in the deserializer within ServiceHandler's CreateContentTypeRequest method being null, and causing that method to return null as well. This behavior changes in https://github.com/jellyfin/jellyfin/commit/157a86d0f139d149083036e6ea962e0fd7d77057 , before that, the CreateContentTypeRequest method will not return null when deserializer is null.

Checking whether deserializer is null and returning `Task.FromResult(host.CreateInstance(requestType))` if so seems to resolve this issue, but I'm not sure the implications thereof, or if a new deserialiser should be created

**Comment by cvium** [comment]
Nice work. It wouldn't be a proper release without @Bond-009 breaking things.

**Comment by bugfixin** [comment]
Haha, luckily it's not in a release yet - PR will come in the morning if no one beats me to it.
