### ISSUE TITLE
The TV series will show 'two folders' on a same series.

### ISSUE THREAD

**Issue by Travel2Here** [jellyfin/jellyfin#12715]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

The TV series directory will show two folders when structure like 'TV series name/season/episode' ; 
if remove the 'season' structure ,store the files like 'series name/season01episode01.mkv, it will be correct,showing one folder, but this structure is inconvenient in file management. maybe it's a bug?
Previous versions didn't have this problem (10.8.x) can't remember exactly which minor version.

### Reproduction steps

--

### What is the current _bug_ behavior?

as img:

<img width="646" alt="image" src="https://github.com/user-attachments/assets/5ef9765c-cd0a-4be5-a6dc-7f13398bf74c">

### What is the expected _correct_ behavior?

1 folder with season name.

### Jellyfin Server version

Master

### Specify the build version

10.9.11

### Environment

```markdown
Linux Kernel: 5.15
```

### Jellyfin logs

```shell
stdout: [09:07:26] [INF] [20] Main: Startup complete 0:00:22.6320678
stdout: [09:07:28] [INF] [70] Emby.Server.Implementations.ScheduledTasks.TaskManager: 清理合集和播放列表 Completed after 0 minute(s) and 0 seconds
stdout: [09:08:26] [INF] [74] Emby.Server.Implementations.ScheduledTasks.TaskManager: 更新插件 Completed after 0 minute(s) and 57 seconds
stdout: [09:09:33] [INF] [74] Emby.Server.Implementations.IO.LibraryMonitor: TV (/media-c/Videos/TV) will be refreshed.
stdout: [09:09:33] [INF] [74] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 113.108.77.55 request
stdout: [09:09:38] [INF] [39] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media-c/Videos/TV/凡人歌 Born to be the One (2024)/第1季/凡人歌.Born.to.be.the.One.S01E03.2024.2160p.WEB-DL.H265.AAC.mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
stdout: [09:09:39] [INF] [39] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media-c/Videos/TV/凡人歌 Born to be the One (2024)/第1季/凡人歌.Born.to.be.the.One.S01E04.2024.2160p.WEB-DL.H265.AAC.mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
stdout: [09:09:39] [INF] [56] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media-c/Videos/TV/凡人歌 Born to be the One (2024)/第1季/凡人歌.Born.to.be.the.One.S01E02.2024.2160p.WEB-DL.H265.AAC.mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
stdout: [09:09:40] [INF] [56] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/media-c/Videos/TV/凡人歌 Born to be the One (2024)/第1季/凡人歌.Born.to.be.the.One.S01E01.2024.2160p.WEB-DL.H265.AAC.mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
stdout: [09:09:40] [INF] [20] MediaBrowser.Providers.TV.SeriesMetadataService: Creating Season 第 1 季 entry for 凡人歌
```

**Comment by peskyAdmin** [comment]
i noticed this happened with tvdb plugin. just make sure that file name contains, "SXXEYY" in title and refresh all metadata

**Comment by Travel2Here** [comment]
> i noticed this happened with tvdb plugin. just make sure that file name contains, "SXXEYY" in title and refresh all metadata

The filename is inclusive of this naming, the problem is in the folder structure. If there are sub-levels it will happen as I said. A folder in the root directory is fine. The core is characterized by this.（For an operation like refreshing metadata, it is definitely did every time. even includes deleting source files and re-entering.）

**Comment by felix920506** [comment]
Please provide a screenshot of your folder structure.

**Comment by Travel2Here** [comment]
> Please provide a screenshot of your folder structure. 

hi,pls see my log info.

**Comment by Travel2Here** [comment]
<img width="708" alt="image" src="https://github.com/user-attachments/assets/8a31ca74-8cfa-44fb-9c40-80e29f3b4cf1">

<img width="787" alt="image" src="https://github.com/user-attachments/assets/e87a065b-f207-404f-9160-c7c5dfb01f22">

**Comment by felix920506** [comment]
Please rename your folders and files according to the naming scheme in the documentation. 
https://jellyfin.org/docs/general/server/media/shows

**Comment by Travel2Here** [comment]
> Please rename your folders and files according to the naming scheme in the documentation. 
> https://jellyfin.org/docs/general/server/media/shows

OK, As it turns out, the naming of the season must be in English...thx
