### ISSUE TITLE
Activity log - disable “user is online from” and “user has disconnected from”

### ISSUE THREAD

**Issue by billkenney** [jellyfin/jellyfin#12713]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

I’m running the latest stable server, latest iOS app, latest Android tv app, etc. In the admin dashboard, my activity log is spammed with alternating “user is connected from device” and “user has disconnected from device” every few minutes. I just figured out how to delete the entries from the activity log with sqlite3, and it went from 48k+ entries to 9k entries. These activity logs make it nearly impossible to find any relevant activity using the app. I’d love to know how to disable this. I don’t care when users or devices connect or disconnect. 

### Reproduction steps

Sign in, go to dashboard, scroll to activity log, scroll through endless pages of irrelevant connect/disconnect messages

### What is the current _bug_ behavior?

Sign in, go to dashboard, scroll to activity log, scroll through endless pages of irrelevant connect/disconnect messages

### What is the expected _correct_ behavior?

To see what movie/show was watched, when it started, when it finished

### Jellyfin Server version

10.9.11+

### Specify the build version

10.9.11

### Environment

```markdown
Ubuntu 22.04. I’m using Caddy for the reverse proxy. Base url is through a hosting provider which points to my ip address.
```

### Jellyfin logs

```shell
there’s a picture of the activity logs
```

### Relevant screenshots or videos

![IMG_2959](https://github.com/user-attachments/assets/0ac441fb-5ac6-4249-b144-4edda70ab875)

**Comment by crobibero** [comment]
There is no way to disable this.

**Comment by billkenney** [comment]
I came up with a workaround (for Ubuntu). While it doesn't disable these logs, it does clear them from the database. I created a crontab that executes a script every 15 minutes and deletes these logs from the database.

Create a script and make it executable (chmod +x /path/to/script.sh) with the following contents:
#!/bin/bash
sudo sqlite3 /var/lib/jellyfin/data/jellyfin.db "delete from ActivityLogs where name like '%has disconnected from%' or name like '%is online from%';"

Run 'sudo crontab -e' and add this to the bottom:
*/15 * * * * /bin/bash /path/to/script.sh

**Comment by cdhowie** [comment]
@billkenney You can make the query more resilient in terms of not accidentally matching rows where e.g. media might contain the text "has disconnected from" or "is online from" (unlikely but possible) as well as probably more performant, by matching on the `Type` column instead:

```
DELETE FROM ActivityLogs WHERE Type IN ('SessionStarted', 'SessionEnded');
```

**Comment by billkenney** [comment]
> @billkenney You can make the query more resilient in terms of not accidentally matching rows where e.g. media might contain the text "has disconnected from" or "is online from" (unlikely but possible) as well as probably more performant, by matching on the `Type` column instead:
> 
> ```
> DELETE FROM ActivityLogs WHERE Type IN ('SessionStarted', 'SessionEnded');
> ```

@cdhowie someone posted a similar revision to make it work with their language (the last comment https://forum.jellyfin.org/t-solved-remote-user-constantly-online-disconnected?page=2):
`sudo sqlite3 /var/lib/jellyfin/data/jellyfin.db "delete from ActivityLogs where Type like 'SessionStarted' or Type like 'SessionEnded';"`

**Comment by cdhowie** [comment]
Yeah, that's essentially the same except the query is more verbose and needlessly uses the `LIKE` operator (a bit silly when the right operand does not contain a wildcard).
