### ISSUE TITLE
Add more useful debug logging

### ISSUE THREAD

**Issue by joshuaboniface** [jellyfin/jellyfin#1273]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Jellyfin debug logs are next to useless in a lot of places, because not very much aside from HTTP logs are logged to the debug filter. I'd like to see a LOT more `LogDebug` statements everywhere in the code, providing more information about what functions and events are actually occurring in the backend code and hence making debugging problems easier.

**Describe alternatives you've considered**
Hacking these in and rebuilding to test things. It's a huge waste of time.

**Additional context**
I'm not worried about verbosity, debug logs *should* be very verbose. I think without these the debug logs are close to useless for debugging actual code issues since few functions log what they're actually doing. Debug log statements are also *super* useful for `grep`ing through the code to find where things are happening, since variable names and such are inconsistent between components.

We could also maybe turn *down* the debugging output of the HTTP server, since it tends to spew out a lot of logs that are only somewhat helpful.

For an idea of what I mean, see the 4 `LogDebug` statements in https://github.com/jellyfin/jellyfin-plugin-ldapauth/blob/master/LDAP-Auth/LDAPAuthenticationProviderPlugin.cs When enabled, they show in the logs what stages of the authentication the code is at, thus revealing where failures are occurring to within a couple dozen LoC.

**Comment by oddstr13** [comment]
It may be worth considering a separate log file for the http server?

**Comment by joshuaboniface** [comment]
That is a very good idea, especially since it's a real HTTP server now. They could even be managed entirely separately form the main "debug" logs, i.e. a different section in `logging.json`.
