### ISSUE TITLE
Jellyfin's access control is abnormal on my device

### ISSUE THREAD

**Issue by ForgottenZ** [jellyfin/jellyfin#12761]
### Discussed in https://github.com/jellyfin/jellyfin/discussions/12760

<div type='discussions-op-text'>

<sup>Originally posted by **ForgottenZ** October  1, 2024</sup>
I found that this URL can be accessed directly without the need for an apikey or login
https://[YourIP]/Videos/[Video ID]/stream.mp4
I think this is a bit dangerous. Is it a bug?

I have already opened Jellyfin to the public network, so I don't think it's suitable for users from the Internet because it can be unreliable at times, and I have also added CDN configuration for Jellyfin, which I think also increases the risk of CDN traffic consumption.

Q:I can't find the video ID,how did u get that?
A:When you watch a video on the web version, use F12 to go to "Network", pause and replay, and then you will see a similar URL with me.

* English is not my mother tongue. I use a translation program for this. If you think I am wrong, please point it out to avoid misunderstanding. Thank you. </div>

**Comment by sjorge** [comment]
Already reported a few times e.g. https://github.com/jellyfin/jellyfin/issues/6721 , there is a big main issue that covers most of these issues: https://github.com/jellyfin/jellyfin/issues/5415

**Comment by felix920506** [comment]
Yes this is a potential security issue, but no this isn't that big of a risk because the chance that an external attacker will be able to guess an ID of media is essentially 0 due to how many possible combinations there exist.
Closing as it is already reported in #5415
