### ISSUE TITLE
transcoding-temp folder not cleanup up well

### ISSUE THREAD

**Issue by platinum55** [jellyfin/jellyfin#1277]
**Describe the bug**
watched a movie around 9pm, the mkv is still in the transcoding-temp folder and eats up alot of disk space at 1am - not other user watched the movie. I tried to run the task "clean up cache" but it didnt cleaned the transcoding-temp folder

**Expected behavior**
the temp file should be deleted after the user exits the movie

**System (please complete the following information):**
 - OS: Docker
 - Browser: [Chrome
 - Jellyfin Version: 10.3.0
 - Reverse proxy: no

**Comment by PrplHaz4** [comment]
These seem to happen more when a transcoded stream is not "exited" cleanly - like hitting the back arrow in a browser (```.../Sessions/Playing/Stopped``` is never called).

```transcoding-temp``` is stored in the datadir not the cache dir, so the cache-clearing task wouldn't be completely accurate - it probably warrants its own cleanup task, with an "expiration" configuration so that only old transcodes are deleted.

cc @anthonylavado

**Comment by sickHamm** [comment]
on android; kill  jellyfin client  also will not "exited" cleanly,  ffmpeg will run always and fill the “transcoding-temp” quickly 。

### log
```
[19:46:48] [ERR] AcceptWebSocketAsync error
jellyfin[147]: System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handsha
```

**Comment by mazzystr** [comment]
I see the same issue... The temp files never go away for godssake, Lol!

Do I need a cron job to clean up?

<img width="626" alt="Screen Shot 2019-08-13 at 11 51 50 AM" src="https://user-images.githubusercontent.com/2479463/62956623-47a76000-bdc1-11e9-881d-df1ab270b52f.png">

**Comment by anthonylavado** [comment]
> Do I need a cron job to clean up?
@mazzystr That's a good way to solve it for now. I'm gonna push up the prio on this a little bit, but it's still a semi-difficult problem to solve.

For example, if we clean up in an automated fashion, how do we know we aren't wiping out a session in progress? Also, what if you just stopped watching for a little bit, and wanted to resume later? It's faster if the transcoding is already done.

Maybe for now just a maintenance task that lets you clean it on demand.

**Comment by mazzystr** [comment]
I wish I didn't have to transcode at all... I suppose a dir size status and a button to clean up is as good of a feature as any.  I'm still gonna do a find and rm every morning at 4am.

**Comment by PrplHaz4** [comment]
@anthonylavado optimizing for the scenarios where performance would improve seems to be less important (to me at least) than potentially crashing a server by filling up a disk.  This will likely become more of a problem as people have much longer-running Jellyfin installations.

This could be mitigated by setting an age threshold on the modify date or running the task less-frequently (both of which would be arbitrary and imperfect even with the ability to configure)...

A scheduled task can be enabled/disabled easily enough if there are problems.

**Comment by anthonylavado** [comment]
@PrplHaz4 It's not about performance, but rather just doing it right.

**Comment by anthonylavado** [comment]
So I've just created and merged #1622 for the server. It's not perfect, but it should do the trick for most people (I hope).

In the next version (10.4), there will be a scheduled task that is disabled by default. It can be enabled and scheduled to run whenever you'd like (every 24h, every two days, etc). Whenever it runs, it will delete any file in the transcoding-temp folder that hasn't been modified in more than 24 hours.

**Comment by mazzystr** [comment]
Nice work gents!

**Comment by cvium** [comment]
Since the scheduled task has been added, I'm closing this to avoid clutter.

**Comment by kopax** [comment]
Hello, I am having jellyfin failing to start totally because of a hard drive being full. I use a nas for the metadata but I didn't know transcoding was happening in the `config/data/transcodes` directory, can I safely remove it ?

**Comment by anthonylavado** [comment]
@kopax Items in there can be safely deleted (just make sure no one is watching!).

**Comment by RTUnit** [comment]
You are welcome to try transcodes directory cleanup script: https://github.com/RTUnit/Jellyfin-Transcodes-cleanup

**Comment by gaming09** [comment]
> You are welcome to try transcodes directory cleanup script: https://github.com/RTUnit/Jellyfin-Transcodes-cleanup
> 
> The script will automatically start when you start watching media. It will determine which TS file is currently buffered by player. It will delete already watched TS files, and will pause and resume FFMPEG to avoid exceeding too much space per one client.
> 
> In my server I mounted 512MB RAM drive for `/config/transcodes` and I can watch 2-3 clients in 4K 80Mbps (TS file size is about 50 MB per file).

any steps on how to do this in Jellyfin hosted on Unraid? im a bit confused about the steps - I already have the ramdisk set up and a  transcode directory on that
