### ISSUE TITLE
Wrong German Translation in User Administration

### ISSUE THREAD

**Issue by 0x00c** [jellyfin/jellyfin#12784]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

In the users administration there is a "last seen" information beneath the users profile image, but the text is cut off and not readable. In german the translation is also wrong. This not only results in the text being incorrect in terms of content, but the text is also cut off on the field so that it cannot be read in full.

![image](https://github.com/user-attachments/assets/476cb9de-fcf8-47ac-9b57-3b5ff9981ca1)

(This also seems to affect some english strings, too, for example "last seen about 2 months ago" (it only displays up to '2')

### Reproduction steps

1. Sign into Jellyfin
2. Open Administration section
3. Go to "Users"

### What is the current _bug_ behavior?

Last seen is translated to: "Zuletzt angesehen" (which means: "last watched")

### What is the expected _correct_ behavior?

Last seen is translated to: "Zuletzt gesehen" (which means: "last seen")

### Jellyfin Server version

10.9.11+

### Specify the build version

10.9.11

### Environment

```markdown
- OS: Windows Server 2022
- Clients: Browser
- Browser: Chrome 129 + Firefox 131
- Plugins: none
- Reverse Proxy: none
- Base URL: none
```

### Jellyfin logs

```shell
(not relevant)
```

### Additional information

This bug does probably not occur on higher resolutions as 1920 x 1080 or if the zoom level is less than 100%

**Comment by crobibero** [comment]
This is a two-part issue. 
The German translation for that string can be edited in weblate: https://translate.jellyfin.org/translate/jellyfin/jellyfin-web/de/?q=last+seen&sort_by=-priority%2Cposition&checksum=

The truncation is a minor issue and should be recreated in jellyfin-web if desired.
