### ISSUE TITLE
Add support for arm64 platform

### ISSUE THREAD

**Issue by ngosang** [jellyfin/jellyfin#1279]
I have an Odroid-C2 board as multimedia center. The problem is the architecture is arm64 and you are not providing packages. The main distribution for Odroid boards is Ubuntu.
I tried to install .NET SDK and build from source, but the board doesn't have enough RAM for compilation.
Please, give support for this architecture. Emby does => https://emby.media/linux-server.html

**Comment by DrPandemic** [comment]
:wave: There's a arm64 build on [Docker Hub](https://hub.docker.com/r/jellyfin/jellyfin/tags). Right now, the latest arm64 build is `10.3.1-arm64`. If you really want to build it yourself, you could try to follow the [dockerfile for arm64](https://github.com/jellyfin/jellyfin/blob/master/Dockerfile.arm64).

**Comment by ngosang** [comment]
I can't run Docker images because I have few RAM available... Will be really nice to have .deb packages. It's too much work to do the cross compilation for each release... Meanwhile I'm using Emby.

**Comment by DrPandemic** [comment]
I've been running docker on a Raspberry Pi 3 Model B+ (which has 1GB of RAM) and it has been running many services smoothly.

After reading [the doc](https://jellyfin.readthedocs.io/en/latest/administrator-docs/installing/#repository) I realized that the team is already building a `armhf` .deb https://repo.jellyfin.org/releases/server/debian/jellyfin_10.3.1-1_armhf.deb

**Comment by ngosang** [comment]
armhf = arm 32bits
arm64 or aarch64 = arm 64bits
Most new NAS and board computers use 64 bits processors. I'm requesting to add arm64 builds of deb packages for debian and ubuntu. Thank you!

**Comment by joshuaboniface** [comment]
I've got some sample `.deb` files up on the repo - if you could test them out and let me know if they're functional that would be helpful (I don't have any arm64 test hardware):

https://repo.jellyfin.org/releases/server/debian/jellyfin_10.3.1-1_arm64.deb
https://repo.jellyfin.org/releases/server/ubuntu/jellyfin_10.3.1-1_arm64.deb

**Comment by ngosang** [comment]
Missing package jellyfin-ffmpeg for arm64
```
xxxxx@xxxxx:~# sudo dpkg -i jellyfin_10.3.1-1_arm64.deb 
Selecting previously unselected package jellyfin.
dpkg: considering removing emby-server in favour of jellyfin ...
dpkg: yes, will remove emby-server in favour of jellyfin
(Reading database ... 61194 files and directories currently installed.)
Preparing to unpack jellyfin_10.3.1-1_arm64.deb ...
Removed /etc/systemd/system/multi-user.target.wants/emby-server.service.
Unpacking jellyfin (10.3.1-1) ...
dpkg: dependency problems prevent configuration of jellyfin:
 jellyfin depends on at; however:
  Package at is not installed.
 jellyfin depends on jellyfin-ffmpeg; however:
  Package jellyfin-ffmpeg is not installed.

dpkg: error processing package jellyfin (--install):
 dependency problems - leaving unconfigured
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Processing triggers for systemd (237-3ubuntu10.20) ...
Errors were encountered while processing:
 jellyfin
```

**Comment by joshuaboniface** [comment]
Right, I forget my own setup >.< What Ubuntu release are you on @ngosang ?

**Comment by ngosang** [comment]
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

**Comment by joshuaboniface** [comment]
OK an arm64 jellyfin-ffmpeg is up too:

https://repo.jellyfin.org/releases/server/ubuntu/jellyfin-ffmpeg_4.0.3-6-bionic_arm64.deb

If everything works I'll release officially!

**Comment by ngosang** [comment]
@joshuaboniface It works very well.
When you release it let me know. I want to reinstall with the official repository, to keep it updated. => https://jellyfin.readthedocs.io/en/latest/administrator-docs/installing/#repository_1

**Comment by Modna** [comment]
@ngosang 
Silly question - I installed the ffmpeg .deb file on my nvidia Jetson Nano.

The build was successful, but how do I go about running Jellyfin?

**Comment by joshuaboniface** [comment]
@ngosang @Modna 10.3.2 is now out, with arm64 fully in the repository now - if you enable the repository you should be able to pull that in!

**Comment by ngosang** [comment]
@joshuaboniface Thank you very much!!! It's working well. I'm closing this.
@Modna You can install now form repositories, check my previous link. Jellyfin is installed as a systemd service and it's started after installation. You can check if it's running with `systemctl status jellyfin`. You can get the URL from the logs or open in the browser `http:// your_board_ip :8096`
