### ISSUE TITLE
Audio transcoding information

### ISSUE THREAD

**Issue by HanaO00** [jellyfin/jellyfin#12794]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

Hello I don't really know if this is a solution, in the Finamp client I activated the transcoding in AAC but jellyfin in the dashboard says that there is no transcoding and that the media is read without transcoding

### Reproduction steps

1. In the finamp settings (android) enable transcoding (AAC) 
2. In the jellyfin dashboard, look at the information about transcoding

### What is the current _bug_ behavior?

The transcode log is created, the media sent is in AAC but jellyfin says that there is no transcoding, even with a different source (flac, or other...)

### What is the expected _correct_ behavior?

Show information about audio transcoding

### Jellyfin Server version

10.9.11+

### Specify the build version

10.9.11

### Environment

```markdown
- OS:Debian
- Virtualization:Docker
- Clients:Finamp android
```

### Jellyfin logs

```shell
No logs
```

**Comment by felix920506** [comment]
This is an issue with the client. Please report the issue to Finamp.
