### ISSUE TITLE
Streaming Performance With Limited Bandwidth

### ISSUE THREAD

**Issue by DigitalCharon** [jellyfin/jellyfin#12803]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

I have ~15Mbps of bandwidth from the jellyin server to the client (tested with librespeed hosted on the same machine). The video stream I'm trying to play is ~2Mbps. 2 is significantly less than 15 but jellyfin cannot maintain the stream. 
![Screenshot_20241010_113035_Jellyfin](https://github.com/user-attachments/assets/8adb2ff2-84aa-4d41-b7ba-e61240776567)
![downloadfile](https://github.com/user-attachments/assets/660b65c3-6078-497a-a6ae-220c2be59c3b)

### Reproduction steps

1. have limited bandwidth
2. try to stream something
3. experience stutters and buffering

### What is the current _bug_ behavior?

stream stutters and buffers

### What is the expected _correct_ behavior?

stream plays properly

### Jellyfin Server version

10.9.11+

### Specify the build version

10.9.11

### Environment

```markdown
- OS:Ubuntu 24.04
- Linux Kernel: 6.8.0-45-generic
- Virtualization: docker
- Clients: android
- Browser: no
- FFmpeg Version: whatever's in the docker container
- Playback Method: direct play
- Hardware Acceleration: yes
- GPU Model: gpu in a galaxy fold 5. 
- Plugins: anidb, audiodb, kodi sync queue, musicbrainz, omdb, studio images, tmdb
- Reverse Proxy: apache2
- Base URL: /jellyfin
- Networking: wireguard
- Storage: 7 12tb drives in a zfs for media. pcie gen 4 ssd for logs/config
```

### Jellyfin logs

```shell
There's not an error log for stream buffering is there?
```

**Comment by felix920506** [comment]
You are likely facing a problem with QoS. TCP traffic generally gets higher priority than UDP traffic, which wireguard uses. There is no way we can fix this.

**Comment by DigitalCharon** [comment]
Thats not the problem since both the speedtest and jellyfin stream go over the same vpn tunnel
