### ISSUE TITLE
fast forward no auto resume playback? need press okay to resume.

### ISSUE THREAD

**Issue by ericvlog** [jellyfin/jellyfin#12810]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

using android tv jellyfin, face to above problem, when fast foward it should it auto resume played, instead need to press okay to resume.

### Reproduction steps

played,fast foward ....no resume untill press okay.

### What is the current _bug_ behavior?

no

### What is the expected _correct_ behavior?

no

### Jellyfin Server version

10.9.11+

### Specify version number

android tv jellyfin

### Specify the build version

Jellyfin Android Tv

### Environment

```markdown
Jellyfin android tv
```

### Jellyfin logs

```shell
no logs
```

### FFmpeg logs

```shell
no
```

### Client / Browser logs

android tv jellyfin

### Relevant screenshots or videos

nope

### Additional information

yes.

**Comment by crobibero** [comment]
This is not a bug, but working as designed.
