### ISSUE TITLE
Jellyfin keeps updating Trakt plugin from stable repo to unstable which then reports as Not Supported

### ISSUE THREAD

**Issue by dd900** [jellyfin/jellyfin#12827]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

Jellyfin keeps replacing the "working" stable Trakt v25.0.0.0 with "not supported" unstable v25.2410.9.0

I uninstalled the unstable version and restarted to make sure it was gone. I then reinstalled the Stable version and restarted the server. All was good for about 10 minutes then I noticed 25.2410.9.0 had popped up in my plugins again. The stable version was showing Superseded and the Unstable version was showing a restart was needed. Restarted and it still reports as Not Supported. I've uninstalled and reinstalled about three times now and it just keeps happening. The Stable version works fine and there is no need for Jellyfin to be updating my plugins to unstable versions.

### Reproduction steps

1. Install Trakt Stable v25.0.0.0
2. Restart server
3. Wait 10 minutes or update plugins

### What is the current _bug_ behavior?

Non working unstable version is getting installed over a working stable version.

### What is the expected _correct_ behavior?

That Jellyfin does not update stable versions of apps to unstable versions unless I do it manually.

### Jellyfin Server version

10.9.11+

### Specify the build version

10.9.11

### Environment

```markdown
- OS: linux - docker
- Networking: host
- Storage: local
```

### Jellyfin logs

```shell
[2024-10-15 14:40:01.235 -04:00] [INF] [96] Emby.Server.Implementations.Updates.InstallationManager: Plugin "installed": "Trakt" "25.2410.9.0"
```

**Comment by crobibero** [comment]
You need to remove the unstable repo if you are on a stable version of Jellyfin. This is working as intended.

**Comment by dd900** [comment]
I don't see this as being an actual solution. I don't at the moment, but I previously was using a plugin from the unstable branch as it was the only one I could get to work. If that were still the case deleting the unstable repo would be unsatisfactory. Plugins should only be updated from the repos they were installed from. Thanks for your quick response. I will follow your advice and delete the unstable repo for now.

**Comment by oddstr13** [comment]
Unstable repo is :drum:… Unstable!

The unstable repo is only intended for use when testing new changes, especially for testing the upcoming server release with plugins around release time, and it is not intended to be used on a stable server.

If you for some reason need a plugin from there on your production instance, you may be best off installing the plugin manually, or maintaining your own plugin repo (see [jprm – Jellyfin Plugin Repository Manager](https://github.com/oddstr13/jellyfin-plugin-repository-manager))
