### ISSUE TITLE
Recommendations: Unclear wording for "Movies directed by"

### ISSUE THREAD

**Issue by dnno** [jellyfin/jellyfin#12823]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

I have several movies by a certain director in my library. This director also happens to be an actor. On the recommendations page all movies of that director (both as an actor and a director) show up under the headline "Directed by ...".

The wording comes from the i18n key "RecommendationDirectedBy".

### Reproduction steps

1. Find a director that also works as an actor
2. Add movies from that director to the library, also add a movie where the director appears as an actor.
3. Watch a movie where the person was the director
4. Look at the movie recommendations page and find the section "Directed by ..."

### What is the current _bug_ behavior?

All movies where the director directed and also appears as an actor are shown.

### What is the expected _correct_ behavior?

I would expect to see only movies that were actually directed by the given director. Not the movies were they starred as an actor.

Alternative: Use a different, more relaxe wording. But I think the i18n key is pretty clear in its expectation.

### Jellyfin Server version

10.9.11+

### Specify the build version

10.9.11

### Environment

```markdown
- OS: 
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
-
```

**Comment by JPVenson** [comment]
This is currently by design. Please open a feature request instead.
An person is either stored as an Actor or Director. There is currently no way to have them both be "the same" person in the database.

**Comment by dnno** [comment]
Hmm, but doesn't explain the  behaviour that I'm seeing, does it? If the recommendations page would only show media connected to the director person, then movies were the same person appears as an actor shouldn't show up? I might misunderstand the situation, though...

**Comment by JPVenson** [comment]
Well it does. If the Actor "Christian Bale" and the Director "Christian Bale" are not the same entry in the database, they have no connection between them. They are considered 2 seperate persons.

I dont say i like this behavior but its not a _bug_ per-se.

**Comment by Arcturuss** [comment]
Then why a separate person entity (the Actor) appears in the recommendations under the title "Directed by"?
