### ISSUE TITLE
10.3.X not downloading TVDB Metadata

### ISSUE THREAD

**Issue by SenorSmartyPants** [jellyfin/jellyfin#1282]
**Describe the bug**
No metadata for tv episodes has been downloaded since upgrade to 10.3.0-1. Episode images are grabbed but that's it.

**Comment by WWWesten** [comment]
Seems this issue https://github.com/jellyfin/jellyfin/issues/1235 is related.

**Comment by WWWesten** [comment]
Issue #1235 is related only partially. Seems TheTVDb provider disabled for episodes, even weblink is removed from episode page. I don't know is it done accidentally or intentionally. May be copyright issues or TheTVDb API changes or validity of access key for API?

**Comment by WWWesten** [comment]
@anthonylavado thanks!

**Comment by SenorSmartyPants** [comment]
Any progress on this?

**Comment by anthonylavado** [comment]
Have to bring in @cvium on this... IIRC, the v2 API does not have the full season ZIP download, which is what was used for episode data.

I believe Emby is still using the v1 API, which is supposed to have died in October 2017, but is still running. You can't even get API keys for the old version anymore (when we did have it working, it was with a borrowed key from a user).

**Comment by WWWesten** [comment]
And there is no way to download per episode?
Even if the episode description is loaded from TheMovieDB, the title takes the form Episode #nnn. Why?

**Comment by WWWesten** [comment]
Why not revert to api v1? Moving to v2 is breaking experience.

**Comment by cvium** [comment]
Have you made sure that the tvdb episode provider is enabled for your libraries?

> Why not revert to api v1? Moving to v2 is breaking experience.

No

**Comment by cvium** [comment]
Add `Public` to https://github.com/jellyfin/jellyfin/blob/master/MediaBrowser.Providers/TV/TheTVDB/TvdbEpisodeProvider.cs#L21

**Comment by anthonylavado** [comment]
Will do in a few hours if no one beats me to it. Adding to next patch

**Comment by WWWesten** [comment]
> Have you made sure that the tvdb episode provider is enabled for your libraries?
![tvdb](https://user-images.githubusercontent.com/4700006/56987214-40f43480-6ba6-11e9-86af-9bf0f05fbf4f.PNG)

It's  even not on the list!

**Comment by anthonylavado** [comment]
@WWWesten Yes, he was unaware that it was missing. Another change surrounding dependency injection changed the way this behaved, so it was unintentionally missing. This recent PR (#1332) fixes this. It will be part of the next release.

**Comment by WWWesten** [comment]
> this release is soon...

Great! Thanks.

**Comment by WWWesten** [comment]
Still TheTVDB episode provider does not work with 10,3,2. TheTVDB appears listed now.

**Comment by anthonylavado** [comment]
@WWWesten Is this still an issue for you in 10.3.3? Fixes usually only move forward, we don't correct previous releases.

**Comment by WWWesten** [comment]
> @WWWesten Is this still an issue for you in 10.3.3? Fixes usually only move forward, we don't correct previous releases.
10.3.**3**? Where is the release? I did not find this either on the git or on the repo.

**Comment by anthonylavado** [comment]
@WWWesten Sorry, I was confused. So it's still not working for you in 10.3.2? I will test further again

**Comment by SenorSmartyPants** [comment]
I'm not sure if it's related to what I'm seeing in #1356

**Comment by WWWesten** [comment]
@anthonylavado
> So it's still not working for you in 10.3.2?
Yep! It is sad. But anyway thanks for Your effort.

**Comment by anthonylavado** [comment]
So I've set up a brand new testing install, set up a TV Shows library, and turned off everything except for The TVDB. All metadata has been downloaded. It appears to be working...

Just to be safe, I even recreated my TV Shows library on my actual main Jellyfin install, and everything came back for over 300 episodes of TV. I'm not sure where it's failing for you at this point.

**Comment by jomp16** [comment]
When I updated the docker container, I needed to check the TheTVDB in the
library config for episode provider (it was unchecked).

Can you make sure to see if the library has TheTVDB checked? Click in
advanced options to see everything.

Em ter, 7 de mai de 2019 2:24 AM, Anthony Lavado <notifications@github.com>
escreveu:

**Comment by kusochi** [comment]
These lines appear in logs when I try to refresh metadata on any episode (TheTVDB is enabled):

[2019-05-07 20:40:41.129 +02:00] [INF] HttpClientManager "POST": "https://api.opensubtitles.org/xml-rpc"
[2019-05-07 20:40:42.085 +02:00] [INF] HttpClientManager "POST": "https://api.opensubtitles.org/xml-rpc"
[2019-05-07 20:40:42.940 +02:00] [ERR] Failed to retrieve episode with id null
TvDbSharper.TvDbServerException: Your JWT token is missing or expired; Not authorized
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SeriesClient.GetEpisodesAsync(Int32 seriesId, Int32 page, EpisodeQuery query, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.TryGetValue[T](String key, String language, Func`1 resultFactory)
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.GetEpisodeTvdbId(Int32 seriesTvdbId, EpisodeQuery episodeQuery, String language, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.TheTVDB.TvdbEpisodeProvider.GetMetadata(EpisodeInfo searchInfo, CancellationToken cancellationToken)

**Comment by anthonylavado** [comment]
@kusochi That looks like the error in #1356, we'll need to dig there.

**Comment by jomp16** [comment]
@WWWesten did you see https://github.com/jellyfin/jellyfin/issues/1342?

It's about the English fallback issue.

**Comment by WWWesten** [comment]
About problems with russian metadates from TVDB: https://forum.jellyfin.org/t/troubles-with-russian-specifications/314

**Comment by anthonylavado** [comment]
@WWWesten I’m so sorry, GitHub is a difficult place to discuss this.

There are a few issues in total I think:
* TVDB not available (should be fixed already)
* TVDB not downloading, JWT error (#1356)
* TVDB doesn’t fallback to English (#1342)

Which ones are you experiencing? If it’s the others, I think it’s best to move to those issues, and close this one. If it’s different, we should make a new issue for tracking it.

**Comment by SenorSmartyPants** [comment]
Metadata is downloading for me now. I had the JWT issue after I started this one. A restart of JF fixed that issue for me. This issue could be closed as far as I am concerned. But I know I'm not the only one that's added to this issue.
