### ISSUE TITLE
Keyboard shortcuts in player

### ISSUE THREAD

**Issue by noah2121** [jellyfin/jellyfin#1283]
Most streaming platforms allow the user to use their keyboard instead of clicking buttons for pause, play and skip.

Netflix has a pretty simple list of keyboard shortcuts here (https://help.netflix.com/en/node/24855). I think it is a familiar standard to use.

These shortcuts do not exist in Jellyfin and would be a nice addition.

**Comment by DrPandemic** [comment]
This is specific UIs. If you are talking the web UI, this issue should be moved to https://github.com/jellyfin/jellyfin-web

**Comment by DrPandemic** [comment]
I just realized that there's already keyboard shortcuts in jellyfin-web. 

- `f` for fullscreen
- `space` or `enter` to play/pause
- `m` for mute
- `shift + arrows` for navigation

**Comment by dkanada** [comment]
Yeah they aren't documented and need to be cleaned up. I would like to add `jkl` for navigation like youtube does, space and enter often have issues with browsers.

**Comment by DrPandemic** [comment]
You are right. We could do like youtube and show the shortcut in the tooltips

![image](https://user-images.githubusercontent.com/3250155/56691096-0a518200-66ad-11e9-8f55-3dbd538f79ad.png)

Let me bring that on riot to see if people has opinions. I would personally also go for `jkl` with `f` and `m`.
