### ISSUE TITLE
Import Playlist from emby/plex/trakt/imdb

### ISSUE THREAD

**Issue by kesm** [jellyfin/jellyfin#1285]
Hi, 

In order to find easily medias in our big librairies it could be great to have a plugin that import playlists from different origins : 

Plex, Emby, Trakt, Imdb

There is already a script that does this for plex (importing from trakt/imdb) and I think this could be a great addition to jellyfin while waiting for dynamic playlists.

**Comment by lostmypillow** [comment]
Doesn't the Trakt plugin do that?

**Comment by kesm** [comment]
Nop trakt plugin only sync watched status between trakt website and jellyfin library

**Comment by pb1051** [comment]
I agree this would be a great item to add support for. I use a service that allows me to export playlists from all my services, but I don't think I have a way to get them in Jellyfin.

**Comment by hbooo** [comment]
Could be nice to also choose if we want to import them into playlist or collection

**Comment by pb1051** [comment]
The links do not work for me.

**Comment by anthonylavado** [comment]
@pb1051 There was a small outage, but it was brief and fixed. Do they work for you now?

**Comment by pb1051** [comment]
Negative.

"ERR_TUNNEL_CONNECTION_FAILED"

**Comment by anthonylavado** [comment]
@pb1051 That’s so bizzare. It loads here. Cc @joshuaboniface

**Comment by anthonylavado** [comment]
@pb1051 So that error message appears to be from Chrome. If you're able to reach the Repos (https://repo.jellyfin.org/releases/) and the Forum (https://forum.jellyfin.org/), then you should be able to reach the Features page. They're all hosted on DigitalOcean here in Toronto.
