### ISSUE TITLE
Playback failed due to a fatal player error.

### ISSUE THREAD

**Issue by Innomen** [jellyfin/jellyfin#12851]
Sure is annoying when you're not given the information you need right? If you don't want blank issue reports maybe don't have blank error messages?

P.S. What logs? 
"The file or folder /var/log/jellyfin does not exist."

o.o

**Comment by JPVenson** [comment]
The issue template asks for a lot more then just logs. Use it.

**Comment by Innomen** [comment]
> The issue template asks for a lot more then just logs. Use it.

heheh you don't say? So more information is needed, who knew? Maybe populate the error messages? 

As if I'm the first guy sick of worthless empty cryptic error messages. There's so many ways you could improve this situation, like include all the known information you'd ask for in an offshoot of the error message. Link directly to a partially pre-filled error reporter.

I've been seeing inexcusably empty error messages for decades now. I'm so sick of it, especially now.

inb4 the oldest empty replies:
The oldest rant on the internet: 
Cracks me up how the FOSS community thinks it's above monopolistic behavior what what else would you call this level of disregard for end users BUT a recognition of monopoly status? (Don't like our error messages? Tough shit, it's jellyfin or bust and we know it.) Same song for 30 years, FOSS guy makes thing, people use thing, foss guy gets monopoly, someone complains, everyone and their mom is like "you can't do better!1!1!" When no one on this side of the fence would tolerate that nonsense argument from MS et al. /smh

Everyone knows I'm right about this, but all the fanboys will appear and defend the princess if the censors don't remove me first. 

I'm thrilled that I'm gonna get to watch coders get replaced by AI. And if anyone ever acts surprised, or implies they didn't earn it... /smh

**Comment by thornbill** [comment]
The power of open source is that anyone can help to improve things they are passionate about. This is not the way to accomplish that.

**Comment by joshuaboniface** [comment]
>I've been seeing inexcusably empty error messages for decades now. I'm so sick of it, especially now.

Be the change you want to see in the world. Everyone involved in this project donates their free time to it because they're interested in working on it. Same as every open-source project. If you don't like how it's being done, well, donate *your* time or quite whinging about what other people give you *for free*.
