### ISSUE TITLE
jellyfin's secondary classification is incorrect

### ISSUE THREAD

**Issue by AlephZHAO** [jellyfin/jellyfin#12872]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

When using jellyfin, it keeps appearing that the secondary directory categories for movies and TV shows are incorrect

### Reproduction steps

For example, in the /movie/US/example/example.exe directory, jellyfin will only recognise the entire episode as ‘US’, and will not reflect the secondary organisation of directories for movies at all.

### What is the current _bug_ behavior?

In the /movie/US/example/example.exe directory, jellyfin will only recognise the entire episode as ‘US’, and will not reflect the secondary organisation of directories for movies at all.

### What is the expected _correct_ behavior?

For example, in the /movie/US/example/example.exe directory, jellyfin should first show the ‘Movie’ folder, then the ‘US’ folder, then show the example movie, then play it!

### Jellyfin Server version

10.9.11+

### Specify the build version

10.9.11

### Environment

```markdown
- OS:QTS
- Linux Kernel:6.1
- Virtualization:None
- Clients:Android
- Browser:Chrome 93
- FFmpeg Version:10.9.11-Jellyfin
- Playback Method:Direct Play
- Hardware Acceleration:None
- GPU Model:None
- Plugins:None
- Reverse Proxy:None
- Base URL:None
- Networking:Host
- Storage:Local
```

### Jellyfin logs

```shell
I'll provide further information if required.
```

**Comment by sevenrats** [comment]
you are just not following supported naming conventions.  if you want to do it like this you have to add each subdirectory as a root of your library, and ensure that, within each root directory, you obey our naming conventions.

**Comment by sevenrats** [comment]
https://jellyfin.org/docs/general/server/media/movies/
