### ISSUE TITLE
That replay is the problem. Please read what the discussion is about. Don't just close it after skimming over it.

### ISSUE THREAD

**Issue by IsJustaGhost** [jellyfin/jellyfin#12878]
There exists an endpoint that allows clients to store client preferences. As an example it is used in the web client to store home screen preferences.

_Originally posted by @crobibero in https://github.com/jellyfin/jellyfin/discussions/12875#discussioncomment-11055473_

The issue is the web client does not "store" home screen preferences. It's temporary at best.

**Comment by felix920506** [comment]
Please open an issue in the web client repo and fill out the template there. https://github.com/jellyfin/jellyfin-web
