### ISSUE TITLE
Playback of ISO-Files in Kodi in Addon-Mode is not possible

### ISSUE THREAD

**Issue by psychofaktory** [jellyfin/jellyfin#12888]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

With Jellyfin for Kodi in Addon-Mode it's not possible to navigate through DVD menus from iso-files.

I previously used Jellyfin 10.8.13 with Jellyfin for Kodi in Native Mode where there was no problem with this. But since the upgrade, adding a networkpath for the libraries isn't possible anymore. 

I also tried to specify the Samba share directly as a directory in the Jellyfin library. However, the log displayed this error message:
`[14:46:29] [ERR] [119] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request: Could not find a part of the path '/run/s6-rc:s6-rc-init:LpLeBO/servicedirs/svc-jellyfin/\\10.20.20.10\Movies'. URL GET /Environment/DirectoryContents.` 
With version 10.8.13 the same SMB path works.

The workaround over editing the options.xml and adding the <NetworkPath> section didn't work because Kodi still uses the directory entered under <Path>.

### Reproduction steps

1. Connect Jellyfin for Kodi in Addon-Mode with the server
2. Try to play an ISO-File with a DVD menu

### What is the current _bug_ behavior?

You can not navigate through the DVD menu

### What is the expected _correct_ behavior?

I would either expect that:
- the navigation in dvd menus of iso files works in addon mode
- the function can be stored in the directory of the respective library of the NetworkPath as in previous versions
- the Kodi addon prefers the path entered under <NetworkPath> when manually adjusting the options.xml
- the setting of an SMB path as the directory of the library works without errors.

### Jellyfin Server version

10.10.0+

### Specify the build version

10.10.0

### Environment

```markdown
- OS: Unraid 6.12.13
- Linux Kernel: 6.1.106
- Virtualization: Docker
- Clients: Libreelec 12.0.1 on Raspberry Pi 3B
- Browser: Firefox 128.3.1esr (64-Bit)
- FFmpeg Version: 7.0.2-5
- Playback Method: Addon Mode without transcoding
- Hardware Acceleration: VAAPI
- GPU Model: AMD Ryzen 3 PRO 4350G
- Plugins: Kodi Sync Queue
- Reverse Proxy: nginx
- Base URL: none
- Networking: Bridge
- Storage: local, SMB
```

### Jellyfin logs

```shell
[14:46:29] [ERR] [119] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request: Could not find a part of the path '/run/s6-rc:s6-rc-init:LpLeBO/servicedirs/svc-jellyfin/\\10.20.20.10\Movies'. URL GET /Environment/DirectoryContents.
```

**Comment by crobibero** [comment]
This is not a bug. Playback of media with a dvd menu has never been supported from the server.
