### ISSUE TITLE
Feature Request: Preconfigure Server URL and User Credentials in Jellyfin App

### ISSUE THREAD

**Issue by Website123456789** [jellyfin/jellyfin#12886]
Feature Request: Preconfigure Server URL and User Credentials in Jellyfin App**

**Description:**
I would like to request a feature that allows for the preconfiguration of the server URL and (optionally) user credentials within the Jellyfin application. This would streamline the user experience by automatically filling in these details, so users do not need to manually enter them each time they use the app.

**Use Case:**
This feature would be beneficial for:
- Family or shared home setups where multiple devices need to connect to the same server.
- Public or corporate environments where Jellyfin is set up on multiple devices.
- Users who find it challenging to repeatedly enter the server URL or credentials on mobile devices.

**Proposed Functionality:**
- Add an option in Jellyfin settings or a configuration file to pre-fill the server URL.
- Optionally, allow secure storage of user credentials with a “Remember me” option for automatic login.

**Security Consideration:**
- To keep data secure, consider implementing encrypted storage for any saved credentials or session tokens.

Thank you for considering this feature request! I believe this addition could significantly improve the Jellyfin experience for many users.

**Comment by felix920506** [comment]
https://features.jellyfin.org
