### ISSUE TITLE
Unable to search by tag in 10.10.0

### ISSUE THREAD

**Issue by lanceli93** [jellyfin/jellyfin#12898]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

Search by tag is a cool feature added in 10.9.11, but I found that this feature is not available in the latest 10.10.0.

### Reproduction steps

Add the media library and search a specific tag.

### What is the current _bug_ behavior?

No result presented.

### What is the expected _correct_ behavior?

We should see the movies with the specific tag.

### Jellyfin Server version

10.10.0+

### Specify the build version

 10.10.0

### Environment

```markdown
- OS: Windows 11
- Linux Kernel:
- Virtualization:
- Clients: Edge Chromium
- Browser: Microsoft Edge
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins: No plugin
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
No related logs.
```

**Comment by felix920506** [comment]
Working as intended. It was removed in 10.10 for performance reasons.

**Comment by lanceli93** [comment]
@felix920506  Thank you for the update. Is it possible to add it as an optional feature? Filtering tag or genre is really helpful.

**Comment by nielsvanvelzen** [comment]
The generic search doesn't search in tags anymore, but you can filter by tag. If you click on a tag when viewing the details of an item you'll go to a page that filters to that tag only.

Url looks like `/web/#/list.html?type=tag&tag=TagName`

**Comment by Soranokuni** [comment]
Sorry for necro but I need this feature for a home studio I am setting up, is there a bugtracker or detailed explanation for the "performance" reasons? 
Is it just taking a bit more to search or there is a big issue.
