### ISSUE TITLE
Adding shared network folder via Samba as media folder not possible

### ISSUE THREAD

**Issue by psychofaktory** [jellyfin/jellyfin#12890]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

I tried to specify a Samba share directly as a directory in the Jellyfin library as described in the documentation. However I got an error.
With version 10.8.13 the same SMB path works.

### Reproduction steps

In the Jellyfin server, navigate to the Libraries section of the admin dashboard.
    Create a new library
    Select the media folder
    Enter the path to your network share in the "Shared network folder" textbox like that:
            Guest User - \\192.168.0.10\share_name or
            Custom User - \\user:password@192.168.0.10\share_name

Make sure permissions of the share are set correctly.

### What is the current _bug_ behavior?

The following error message appears:
"An error occurred when adding a media directory. Please make sure that the path is valid and that Jellyfin has the necessary access rights."

### What is the expected _correct_ behavior?

The path can be accessed

### Jellyfin Server version

10.10.0+

### Specify the build version

10.10.0

### Environment

```markdown
- OS: Unraid 6.12.13
- Linux Kernel: 6.1.106
- Virtualization: Docker
- Clients: Libreelec 12.0.1 on Raspberry Pi 3B
- Browser: Firefox 128.3.1esr (64-Bit)
- FFmpeg Version: 7.0.2-5
- Playback Method: Addon Mode without transcoding
- Hardware Acceleration: VAAPI
- GPU Model: AMD Ryzen 3 PRO 4350G
- Plugins: Kodi Sync Queue
- Reverse Proxy: nginx
- Base URL: none
- Networking: Bridge
- Storage: local, SMB
```

### Jellyfin logs

```shell
[14:46:29] [ERR] [119] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request: Could not find a part of the path '/run/s6-rc:s6-rc-init:LpLeBO/servicedirs/svc-jellyfin/\\10.20.20.10\Movies'. URL GET /Environment/DirectoryContents.
```

**Comment by nielsvanvelzen** [comment]
You need to mount your network share to your system, then point Jellyfin to that folder.

**Comment by psychofaktory** [comment]
> You need to mount your network share to your system, then point Jellyfin to that folder.

When setting up the native mode, the documentation clearly states that the path to the network share must be stored in the Libraries section of the admin dashboard:
https://jellyfin.org/docs/general/clients/kodi#native-mode

How else should Native Mode work if the media is stored on a NAS, for example, and is to be accessed from different clients?

**Comment by nielsvanvelzen** [comment]
Jellyfin 10.10 released only yesterday and our documentation is still being updated.

**Comment by gnattu** [comment]
> When setting up the native mode, the documentation clearly states that the path to the network share must be stored in the Libraries section of the admin dashboard:

https://github.com/jellyfin/jellyfin.org/pull/1173

This only means the doc needs to be fixed :)

**Comment by psychofaktory** [comment]
OK, I wasn't aware that this had changed.

Since DVD menus from ISO files are not supported in add-on mode, native mode was the only way to use these media until now.
What alternatives are there for this scenario after the elimination of native mode?
