### ISSUE TITLE
Remove Emby Premium check from Android TV app

### ISSUE THREAD

**Issue by dinki** [jellyfin/jellyfin#129]
I did see that the Emby Android TV app still requires activation for use with DVR/Live TV.  Is this something that can be changed in the forked server code or would this be a rewrite in the app code?  If the later, is the app code available to be modified?

The android app on my phone works fine for dvr/livetv (it did initially tell me I needed Premium Sub but still works) but Android TV requires Emby Premium Subscription.  Chrome browser works fine as well.  Thinking this may be an app side issue?

**Comment by bfayers** [comment]
AFAIK my pull here: https://github.com/jellyfin/jellyfin-androidtv/pull/1 should do this

**Comment by bfayers** [comment]
I have confirmed now that my pull (now merged) here: https://github.com/jellyfin/jellyfin-androidtv/pull/1 resolved the issue of premiere checks existing

**Comment by JustAMan** [comment]
@dinki please check and close the issue if it is fixed by @bfayers PR.

**Comment by dinki** [comment]
@bfayers provided an APK a few days ago and in testing it I've found that the Premium checks have been removed and all areas are open!  Great work.  Closing this issue.
