### ISSUE TITLE
Not playing mp4 files with HEVC Codec

### ISSUE THREAD

**Issue by Thunder7754** [jellyfin/jellyfin#12921]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

This only occured a few days ago, but I can no longer play .mp4 files with HEVC encoding. This has worked previously as I watched most of a series like this (all the same file and encoding) and now I cant play any episode. I did not consciously update anything Jellyfin related since then. I updated to the latest build and the bug still occurs. I can play the files on the host system and when I either change the codec or the file format while maintaining the codec I can also play it in Jellyfin. 
But with .mp4 files with HEVC encoding I get stuck in an endless loading screen with the blue circle and the backdrop image.
I have checked the logs and it is not even registered that I tried to play the file and my hardware stays idle. 
I am using the Jellyfin Server directly on Windows and have tried restarting both PC and Jellyfin and tried different devices and browsers (Firefox, Edge, Chrome, Safari(Phone)) - all other file / codec combination work as far as I can tell. 

### Reproduction steps

1. Log in to your account
2. Locate a file with .mp4 and HEVC encoding
3. Click play 

### What is the current _bug_ behavior?

 I get stuck in an endless loading screen with the blue circle and the backdrop image when trying to play .mp4 files with HEVC encoding.

### What is the expected _correct_ behavior?

The file should play normally.

### Jellyfin Server version

10.10.0+

### Specify the build version

10.10.0

### Environment

```markdown
- OS:Windows 11
- Linux Kernel: none
- Virtualization: natively on Windows
- Clients: Browser, Phone, Laptop
- Browser: Firefox, Chrome, Edge, Safari
- FFmpeg Version: 7.0.2-Jellyfin Copyright (c) 2000-2024 the FFmpeg developers built with clang version 18.1.8
- Playback Method: transcode (i think)
- Hardware Acceleration: none (but tried NVENC as well)
- GPU Model: RTX 3080
- Plugins: AudioDB, MusicBrainz, OMDb, OpenSubtitles, Studio Images, TMDb
- Reverse Proxy: none
- Base URL: 
- Networking: local
- Storage: local
```

### Jellyfin logs

```shell
The newest log reads: Error processing request.
```

### FFmpeg logs

```shell
There is no log generated when trying to play the file, it just loads indefinitely and never generates a log.
```

### Client / Browser logs

![image](https://github.com/user-attachments/assets/8e207cd4-a1cc-41f9-b44d-8304992b52dd)

**Comment by Thunder7754** [comment]
I did not change this option, nor did I even knew it existed. The weird thing is that it does not happen with .mkv HEVC files and also occurs in browsers like safari on my phone.

**Comment by felix920506** [comment]
Please provide the following info:
1. more logs
2. Media info of the file
3. Is transcoding for this account disabled?

**Comment by Thunder7754** [comment]
Media info of one file that plays and doesnt play is identical in all parameters except container parameter

Container mp4 vs mkv
Video
Title: 1080p HEVC SDR
Codec: HEVC
Codec tag: hvc1
AVC: No
Profile: Main
Level: 120
Resolution: 1872x1080
Aspect ratio: 26:15
Anamorphic: No
Interlaced: No
Framerate: 23.976025
Bitrate: 2523 kbps
Bit depth: 8 bit
Video range: SDR
Video range type: SDR
Color space: bt709
Color transfer: bt709
Color primaries: bt709
Pixel format: yuv420p
Ref frames: 1

Transcoding is enabled, I cant unfortunately provide more logs as when a file doesnt play no log is generated.

However, changing the setting nyanmisaka mentioned from its default to 1 did help. Why I had to do this now, I do not know, for firefox i could imagine it changed with the 132.0 release as Microsoft PlayReady encrypted media playback was rolled out and that might have affected it? Why it changed on other devices I do not know.

**Comment by nyanmisaka** [comment]
Then it may be that the new version of Firefox is incorrectly reporting that it has HEVC support and passing jellyfin-web's `canPlayType()` check.

You can restore `media.wmf.hevc.enabled` to default and use this page to check the status of HEVC support.
https://shaka-player-demo.appspot.com/support.html

```
// chrome 130
    "video/mp4; codecs=\"hev1.1.6.L93.90\"": true,
    "video/mp4; codecs=\"hvc1.1.6.L93.90\"": true,
    "video/mp4; codecs=\"hev1.2.4.L153.B0\"; eotf=\"smpte2084\"": true,
    "video/mp4; codecs=\"hvc1.2.4.L153.B0\"; eotf=\"smpte2084\"": true,
```

**Comment by Thunder7754** [comment]
"video/mp4; codecs=\"hev1.1.6.L93.90\"": true,
    "video/mp4; codecs=\"hvc1.1.6.L93.90\"": true,
    "video/mp4; codecs=\"hev1.2.4.L153.B0\"; eotf=\"smpte2084\"": true,
    "video/mp4; codecs=\"hvc1.2.4.L153.B0\"; eotf=\"smpte2084\"": true

Seems to look the same for me

**Comment by nyanmisaka** [comment]
> ```
> "video/mp4; codecs=\"hev1.1.6.L93.90\"": true,
> "video/mp4; codecs=\"hvc1.1.6.L93.90\"": true,
> "video/mp4; codecs=\"hev1.2.4.L153.B0\"; eotf=\"smpte2084\"": true,
> "video/mp4; codecs=\"hvc1.2.4.L153.B0\"; eotf=\"smpte2084\"": true
> ```
> 
> Seems to look the same for me

If this is the behavior by default, then Firefox is lying about its HEVC decoding capability.

**Comment by Thunder7754** [comment]
Alright, then I am gonna report it to Firefox and fix it temporarily by changing the `media.wmf.hevc.enabled` variable to 1. Still interesting, that it only affects mp4 files and mkv works fine. 
Okay, thank you!

**Comment by nyanmisaka** [comment]
> Alright, then I am gonna report it to Firefox and fix it temporarily by changing the `media.wmf.hevc.enabled` variable to 1. Still interesting, that it only affects mp4 files and mkv works fine. Okay, thank you!

There is only Webm support in the browser, and Webm is just a subset of MKV.

So we disabled direct play of MKV files and serve it via HLS + remuxing.
