### ISSUE TITLE
jellyfin make milions of temp files .jpg and fill inode linux

### ISSUE THREAD

**Issue by canapaio** [jellyfin/jellyfin#12937]
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

with the latest jellyfin updates, the server creates millions of temporary .jpg files by filling the ext4 inode
when I reboot the system it takes hours to delete all the temporary files, and I have to delete them before the reboot otherwise the server stays booting for hours.
my next test is to put a memory disk in fstab for the /tmp folder
the logs show no errors on these files

### Reproduction steps

open folder /tmp/jellyfin/nnnnnnnnnn/*

### What is the current _bug_ behavior?

everyday

### What is the expected _correct_ behavior?

everyday

### Jellyfin Server version

10.10.0+

### Specify the build version

main

### Environment

- OS: arm64 ubuntu 22.04
- Linux Kernel: 5.10
- Virtualization: no
- Clients: jellyfinweb
- Browser: firefox
- FFmpeg Version: 
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:

### Jellyfin logs

irrelevant

**Comment by felix920506** [comment]
Please provide logs during the time period of those files being created.

**Comment by solidsnake1298** [comment]
I was able to replicate.  Just doing a library scan places files in /tmp/jellyfin.  After the scan finished the files were not cleaned up.

**Comment by tangyl2000** [comment]
The QNAP system frequently experiences RAMDisk / or /tmp capacity shortage errors. Because the/tmp capacity of my qnap (464c2) is only 64M.

**Comment by gnattu** [comment]
> The QNAP system frequently experiences RAMDisk / or /tmp capacity shortage errors. Because the/tmp capacity of my qnap (464c2) is only 64M.

We recommend you set the `TMPDIR` env var to point to an ssd to not use the system temp if it is that limited. 64MB could be too small for trickplay temp in some cases.

**Comment by felix920506** [comment]
Fixed by #12940
