### ISSUE TITLE
ClientCapabilities returns lists of PlayableMediaTypes and SupportedCommands with extra commas

### ISSUE THREAD

**Issue by jarnedemeulemeester** [jellyfin/jellyfin#12948]
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

When the Jellyfin server returns `ClientCapabilities` the `PlayableMediaTypes` and `SupportedCommands` lists contain extra commas.
This causes errors in the Jellyfin Kotlin SDK because it cannot deserialize a comma to the correct Enum type.

### Reproduction steps

Can be reproduced on own Jellyfin server and stable demo server using any client. For these steps a web browser is used.

1. Make sure the developer tools are open to see the network requests
2. Log in to the stable demo server
3. Look at the response for `authenticatebyname` request (it is probably fine if it's the first sign in of the hour)
4. Log out
5. Log in
6. Observe the response of  the `authenticatebyname` request, the lists of `PlayableMediaTypes` and `SupportedCommands` inside of `SessionInfo` -> `Capabilities` contain extra commas

### What is the current _bug_ behavior?

Returns a list with extra commas:
```
"Capabilities": {
    "PlayableMediaTypes": [
        "Audio",
        ",",
        "Video"
    ],
    "SupportedCommands": [
        "MoveUp",
        ",",
        "MoveDown",
        ",",
        "MoveLeft",
        ",",
        "MoveRight",
        ",",
        "PageUp",
        ",",
        "PageDown",
        ",",
        "PreviousLetter",
        ",",
        "NextLetter",
        ",",
        "ToggleOsd",
        ",",
        "ToggleContextMenu",
        ",",
        "Select",
        ",",
        "Back",
        ",",
        "SendKey",
        ",",
        "SendString",
        ",",
        "GoHome",
        ",",
        "GoToSettings",
        ",",
        "VolumeUp",
        ",",
        "VolumeDown",
        ",",
        "Mute",
        ",",
        "Unmute",
        ",",
        "ToggleMute",
        ",",
        "SetVolume",
        ",",
        "SetAudioStreamIndex",
        ",",
        "SetSubtitleStreamIndex",
        ",",
        "DisplayContent",
        ",",
        "GoToSearch",
        ",",
        "DisplayMessage",
        ",",
        "SetRepeatMode",
        ",",
        "SetShuffleQueue",
        ",",
        "ChannelUp",
        ",",
        "ChannelDown",
        ",",
        "PlayMediaSource",
        ",",
        "PlayTrailers"
    ],
    "SupportsMediaControl": true,
    "SupportsPersistentIdentifier": false
},
```

### What is the expected _correct_ behavior?

Returns a list without extra commas:
```
"Capabilities": {
    "PlayableMediaTypes": [
        "Audio",
        "Video"
    ],
    "SupportedCommands": [
        "MoveUp",
        "MoveDown",
        "MoveLeft",
        "MoveRight",
        "PageUp",
        "PageDown",
        "PreviousLetter",
        "NextLetter",
        "ToggleOsd",
        "ToggleContextMenu",
        "Select",
        "Back",
        "SendKey",
        "SendString",
        "GoHome",
        "GoToSettings",
        "VolumeUp",
        "VolumeDown",
        "Mute",
        "Unmute",
        "ToggleMute",
        "SetVolume",
        "SetAudioStreamIndex",
        "SetSubtitleStreamIndex",
        "DisplayContent",
        "GoToSearch",
        "DisplayMessage",
        "SetRepeatMode",
        "SetShuffleQueue",
        "ChannelUp",
        "ChannelDown",
        "PlayMediaSource",
        "PlayTrailers"
    ],
    "SupportsMediaControl": true,
    "SupportsPersistentIdentifier": false
},
```

### Jellyfin Server version

10.10.0+

### Specify the build version

 10.10.1

### Environment

- OS: Arch Linux
- Linux Kernel: 6.6.59
- Clients: Chromium and Findroid
- Browsers: Chromium 130
- Jellyfin: 10.10.0 and 10.10.1

### Jellyfin logs

Nothing can be observed from the logs as it is just a json serialization issue that is not logged.

### Additional information

The issue probably originates from https://github.com/jellyfin/jellyfin/pull/12587

As a side note `SessionInfo` actually contains duplicate `PlayableMediaTypes` and `SupportedCommands` lists. The lists in the root of `SessionInfo` are correct but the ones in `Capabilities` are broken.

```
{
    "SessionInfo": {
        ...
        "Capabilities": {
            "PlayableMediaTypes": [
                "Audio",
                ",",
                "Video"
            ],
            "SupportedCommands": [
                "MoveUp",
                ",",
                "MoveDown",
                ",",
                "MoveLeft",
                ...
            ],
            "SupportsMediaControl": true,
            "SupportsPersistentIdentifier": false
        },
        "PlayableMediaTypes": [
            "Audio",
            "Video"
        ],
        ...
        "SupportedCommands": [
            "MoveUp",
            "MoveDown",
            "MoveLeft",
            ...
        ]
}
```

**Comment by felix920506** [comment]
should be fixed by #12949
