### ISSUE TITLE
"MediaType": "Unknown" in Users API for ALL Libraries

### ISSUE THREAD

**Issue by fa1rid** [jellyfin/jellyfin#12958]
I'm trying to access the API using this:

`http://IP:8096/Users/1F85B409957E4B2FB012C66E5D277324/items/`

The response for ALL Libraries for "MediaType": "Unknown"

Here is a snippet of the response:

```
{
  "Items": [
    {
      "Name": "Movies",
      "ServerId": "....",
      "Id": "....",
      "ChannelId": null,
      "IsFolder": true,
      "Type": "CollectionFolder",
      "UserData": {
        "PlaybackPositionTicks": 0,
        "PlayCount": 0,
        "IsFavorite": false,
        "Played": false,
        "Key": "....",
        "ItemId": "00000000000000000000000000000000"
      },
      "ImageTags": {
        "Primary": "552dd224b6f2539adc4a6900110daade"
      },
      "BackdropImageTags": [],
      "ImageBlurHashes": {
        "Primary": {
          "552dd224b6f2539adc4a6900110daade": "WF6[U8xvZ$s9Sho}x]ofaJjFbbkW4TM{kDRks:V@DiRjkqX8niV@"
        }
      },
      "LocationType": "FileSystem",
      "MediaType": "Unknown"
    }
  ]
}
```
All libraries show correct type in the dashboard, e.g.:

![Image](https://github.com/user-attachments/assets/86cacb65-94b0-4fd9-a09c-475ab5589d2a)

Any idea what's going on?
Using v10.10.1 on Windows.

**Comment by nielsvanvelzen** [comment]
A library can't have a media type

**Comment by fa1rid** [comment]
Sorry I meant there is no `collectionType` in the response. I edited the post now. Please check.
