### ISSUE TITLE
Kodi Sync Issue

### ISSUE THREAD

**Issue by dacook8** [jellyfin/jellyfin#12956]
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

I´m syncing Jellyfin to Kodi via Jellyfin-Plugin in native mode (samba share).
Jellyfin is running in docker on Synology
Kodi is running on Fire-Stick
the synology local volume "/volume2/Medien" is mounted as "/media" in docker-image and shared on samba "smb://192.168.1.98/Medien"

After upgrading from 10.9.11 to 10.10.0 (and 10.10.1), the files can not be started in kodi, because the path is mapped wrong in the file in kodi-db:

old behaivor 10.9.x
kodi DB enty= smb://192.168.1.98/Medien/Filme/...

new behaivor 10.10.x
kodi DB enty= /media/Filme/...

Kodi Logs:
```2024-11-04 13:56:00.873 T:8933     info <general>: VideoPlayer::OpenFile: videodb://movies/titles/10318?xsp=....
2024-11-04 13:56:00.878 T:9194     info <general>: Creating InputStream
2024-11-04 13:56:00.879 T:9194    error <general>: GetDirectory - Error getting /media/Filme/...
2024-11-04 13:56:00.937 T:9194    error <general>: CVideoPlayer::OpenInputStream - error opening [videodb://movies/titles/10318?xsp=....
2024-11-04 13:56:00.938 T:9194     info <general>: CVideoPlayer::OnExit()
2024-11-04 13:56:00.954 T:9011     info <general>: Deleting settings information for files videodb://movies/titles/10318?xsp=....
2024-11-04 13:56:01.026 T:9058    error <general>: EXCEPTION: Kodi is not playing any file
```

### Reproduction steps

upgrading from 10.9.11 to 10.10.0 (and 10.10.1)

### What is the current _bug_ behavior?

kodi DB enty= /media/Filme/...

### What is the expected _correct_ behavior?

kodi DB enty= smb://192.168.1.98/Medien/Filme/...

### Jellyfin Server version

10.10.0+

### Specify the build version

10.10.0

### Environment

- OS:
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:

### Jellyfin logs

-

**Comment by crobibero** [comment]
smb share network pathing was deprecated in 10.9 and removed in 10.10, so this is expected.
