### ISSUE TITLE
Old plugin folders not deleted at plugin update

### ISSUE THREAD

**Issue by RealGreenDragon** [jellyfin/jellyfin#12959]
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

After plugin update and Jellyfin restart new versions are installed but old versions folders are not deleted.
This has no effect until the plugin is disabled or deinstalled: at such point Jellyfin loads ALL folders and you found multiple versions of the plugin installed, each also updated at latest version !!

It happens now with TheTVDB plugin update from v17 to v18, but it also happened in past with all other non-bundled plugins and various Jellyfin versions.

When I discovered the issue I think was my Jellyfin setup but now happens again with fresh Jellyfin 10.10 instance.

### Reproduction steps

Update non bundled plugin to new version (automatically or manually).

### What is the current _bug_ behavior?

Previous version folders are still present.

### What is the expected _correct_ behavior?

When new version is correctly installed old folders must be deleted.

### Jellyfin Server version

10.10.0+

### Specify the build version

10.10.1

### Environment

- OS: Debian 12 on RPi4
- Virtualization: Docker (linuxserver image)
- Storage: local USB2 HDD with EXT4 filesystem
- Clients: Jellyfin Media Player, Android TV
- Browser: Firefox
- Plugins: TMDb Box Sets v11.0.0.0; TheTVDB v17.0.0.0 (and next v18.0.0.0)

### Jellyfin logs

[2024-11-03 16:19:55.242 +01:00] [INF] [8] Emby.Server.Implementations.Updates.InstallationManager: Plugin "installed": "TheTVDB" "18.0.0.0"
[2024-11-03 16:19:55.283 +01:00] [INF] [8] Emby.Server.Implementations.ApplicationHost: App needs to be restarted.
...
[2024-11-03 16:36:07.685 +01:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "TheTVDB" "18.0.0.0"

**Comment by alvitali** [comment]
Same thing is happening to me with some plugins, not with others. I just keep going into the Plugins folder and deleting them manually - there's weird stuff happening when I try to uninstall a plugin from the Server UI but there are still older versions present in the Plugins folder

**Comment by sjorge** [comment]
What is your RemoveOldPlugins setting set to in system.xml ? (AFAIK there is no web ui counter part to change it)

```
sjorge@<host>:~$ sudo grep RemoveOldPlugins /etc/jellyfin/system.xml
  <RemoveOldPlugins>true</RemoveOldPlugins>
```

**Comment by alvitali** [comment]
> What is your RemoveOldPlugins setting set to in system.xml ? (AFAIK there is no web ui counter part to change it)
> 
> ```
> sjorge@<host>:~$ sudo grep RemoveOldPlugins /etc/jellyfin/system.xml
>   <RemoveOldPlugins>true</RemoveOldPlugins>
> ```

Yeah, indeed... Running in docker, with the command `docker exec -it jellyfin grep RemoveOldPlugins config/config/system.xml` (for anybody else with docker), I get
```<RemoveOldPlugins>false</RemoveOldPlugins>```

It's funny that sometimes old plugins do get deleted though. Can I change the value manually to `true`? Is that supposed to be the default setting?

**Comment by RealGreenDragon** [comment]
@sjorge thanks for the idea, I didn't know this Jellyfin setting. Here my value (I use Jellyfin in docker via linuxserver image):

```
root@greendragon:/config# grep RemoveOldPlugins system.xml
  <RemoveOldPlugins>false</RemoveOldPlugins>
```

As there is no way to change it through UI, there are reasons to keep it `false` by default?

After a quick search the parameter `RemoveOldPlugins` is discussed only in issue #13058 where @Shadowghost argue it should be `true` now.

However seems it is not `true`, as now I have `false` and my Jellyfin instance has been installed from scratch via linuxserver image in version 10.10.0.

**Comment by sjorge** [comment]
I had it set to true and that seems to work. Although I only had one plugin update since changing it.I have no idea what the default should be, mine was false too but I upgraded from 10.9.x~ sjorgeOn 24 Nov 2024, at 18:26, RealGreenDragon ***@***.***> wrote:﻿
@sjorge thanks for the idea, I didn't know this Jellyfin setting. Here my value (I use Jellyfin in docker via linuxserver image):
***@***.***:/config# grep RemoveOldPlugins system.xml
  <RemoveOldPlugins>false</RemoveOldPlugins>

As there is no way to change it through UI, there are reasons to keep it false by default?
After a quick search the parameter RemoveOldPlugins is discussed only in issue #13058 where @Shadowghost argue it should be true now.
However seems it is not true, as now I have false and my Jellyfin instance has been installed from scratch via linuxserver image in version 10.10.0.

**Comment by RealGreenDragon** [comment]
Updated also on my side and seems to solve the issue.

I opened PR #13102 to set `RemoveOldPlugins` parameters `true` by default (obviously all are free to discuss if PR is needed).
