### ISSUE TITLE
Scheduled Tasks start not logged anymore in Jellyfin 10.10

### ISSUE THREAD

**Issue by RealGreenDragon** [jellyfin/jellyfin#12960]
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

I see in v10.10 Scheduled Tasks start is not logged anymore but only the task end.

It is an intended behavior?

### Reproduction steps

Run a Scheduled Task.

### What is the current _bug_ behavior?

Scheduled Task start does not appear in log.

### What is the expected _correct_ behavior?

Scheduled Task start appear in log.

### Jellyfin Server version

10.10.0+

### Specify the build version

10.10.1

### Environment

- OS: Debian 12 on RPi4
- Virtualization: Docker (linuxserver image)
- Storage: local USB2 HDD with EXT4 filesystem
- Clients: Jellyfin Media Player, Android TV
- Browser: Firefox
- Plugins: TMDb Box Sets v11.0.0.0; TheTVDB v18.0.0.0

### Jellyfin logs

<start log missing>
[2024-11-04 20:02:07.689 +01:00] [INF] [12] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Aggiorna i plugin" Completed after 0 minute(s) and 2 seconds

**Comment by gnattu** [comment]
This is an intended change to reduce log verbosity and those logs are now in the debug level.
