### ISSUE TITLE
More memory and CPU Usage after enabling TrickPlay

### ISSUE THREAD

**Issue by jarvisnexus** [jellyfin/jellyfin#12974]
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

I am running Jellyfin on my raspberry PI 4 with 8GB RAM. Along with it I used Plex and Other *arr apps as well. It was working fine until I upgraded to Jellyfin version 10.10.1. I have never seen Jellyfin using more than 25% CPU Usage before even when accessing from multiple devices.

I am not sure whats exactly causing this issue. But the only change I made is enabling TrickPlay.

After enabling it, I could see more memory and CPU Usage. The problem here is that I didn’t accessed the Jellyfin instance at all. No videos were playing. No devices were connected. It took more than 50% on the Idle state.

From the logs, I couldn’t infer anything. Seems like everything is normal.

### Reproduction steps

1. Install latest version of Jellyfin (10.10.1) Docker.
2. Goto Settings -> Check Enable TrickPlay for Movies/Show or any Library 
3. Logout and wait for few mins.
4. You could see the CPU and Memory Usage Spike after enabling TrickPlay TrickPlay.

### What is the current _bug_ behavior?

Jellyfin takes more CPU and Memory Usage in Idle state after enabling TrickPlay.

### What is the expected _correct_ behavior?

Jellyfin shouldn’t consume more CPU/RAM usage in idle state.

### Jellyfin Server version

10.10.0+

### Specify the build version

10.10.1

### Environment

- OS: DietPi with Casa OS
- Linux Kernel: None
- Virtualization: Docker
- Clients: Android TV and iPhone
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins: Only Necessary Plugins
- Reverse Proxy:none
- Base URL:none
- Networking:Bridge
- Storage:local

### Jellyfin logs

Jellyfin.Networking.PortForwardingHost: Stopping NAT discovery
jellyfin  | [13:05:42] [INF] [22] Jellyfin.Networking.PortForwardingHost: Starting NAT discovery
jellyfin  | [13:05:59] [INF] [22] Emby.Server.Implementations.ScheduledTasks.TaskManager: Webhook Item Added Notifier Completed after 0 minute(s) and 0 seconds
jellyfin  | [13:07:30] [INF] [22] Emby.Server.Implementations.ScheduledTasks.TaskManager: Webhook Item Added Notifier Completed after 0 minute(s) and 0 seconds
jellyfin  | [13:08:46] [INF] [22] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 192.168.1.2 closed
jellyfin  | [13:08:46] [INF] [25] Emby.Server.Implementations.Session.SessionManager: Logging out access token 7dccc6e59d97482c85803bd2946ff30e
jellyfin  | [13:08:47] [INF] [3] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.
jellyfin  | [13:08:47] [INF] [21] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.
jellyfin  | [13:08:47] [INF] [3] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.
jellyfin  | [13:08:47] [INF] [21] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.
jellyfin  | [13:08:48] [INF] [3] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.
jellyfin  | [13:08:48] [INF] [21] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.
jellyfin  | [13:08:50] [INF] [10] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.
jellyfin  | [13:08:52] [INF] [21] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.
jellyfin  | [13:08:52] [INF] [11] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.
jellyfin  | [13:08:52] [INF] [16] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.
jellyfin  | [13:08:52] [INF] [10] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.
jellyfin  | [13:08:53] [INF] [16] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.
jellyfin  | [13:08:53] [INF] [10] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.
jellyfin  | [13:09:01] [INF] [10] Emby.Server.Implementations.ScheduledTasks.TaskManager: Webhook Item Added Notifier Completed after 0 minute(s) and 0 seconds
jellyfin  | [13:10:32] [INF] [23] Emby.Server.Implementations.ScheduledTasks.TaskManager: Webhook Item Added Notifier Completed after 0 minute(s) and 0 seconds
jellyfin  | [13:11:11] [INF] [24] Jellyfin.Server.Implementations.Trickplay.TrickplayManager: Finished creation of trickplay files for /DATA/Media/TV Shows/Agatha All Along/Season 1/Agatha All Along - S01E06 - Familiar By Thy Side.mkv
jellyfin  | [13:11:11] [INF] [26] Jellyfin.Server.Implementations.Trickplay.TrickplayManager: Creating trickplay files at 320 width, for /DATA/Media/TV Shows/Agatha All Along/Season 1/Agatha All Along - S01E03 - Through Many Miles of Tricks and Trials.mkv [ID: eb2b57b7-f16a-4356-074e-d6e8640a0970]
jellyfin  | [13:11:11] [INF] [26] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Trickplay generation: /usr/lib/jellyfin-ffmpeg/ffmpeg -loglevel error -i file:"/DATA/Media/TV Shows/Agatha All Along/Season 1/Agatha All Along - S01E03 - Through Many Miles of Tricks and Trials.mkv" -an -sn -vf "fps=0.10000000149011612,setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale=trunc(min(max(iw\,ih*(a*sar))\,320)/2)*2:trunc(ow/(a*sar)/2)*2,format=yuv420p" -threads 1 -c:v mjpeg -qscale:v 4 -fps_mode passthrough -f image2 "/tmp/jellyfin/a08f04cd02414a998fe711f61c6e717a/%08d.jpg"
jellyfin  | [13:12:03] [INF] [16] Emby.Server.Implementations.ScheduledTasks.TaskManager: Webhook Item Added Notifier Completed after 0 minute(s) and 0 seconds
jellyfin  | [13:13:34] [INF] [16] Emby.Server.Implementations.ScheduledTasks.TaskManager: Webhook Item Added Notifier Completed after 0 minute(s) and 0 seconds
jellyfin  | [13:15:05] [INF] [25] Emby.Server.Implementations.ScheduledTasks.TaskManager: Webhook Item Added Notifier Completed after 0 minute(s) and 0 seconds
jellyfin  | [13:16:36] [INF] [3] Emby.Server.Implementations.ScheduledTasks.TaskManager: Webhook Item Added Notifier Completed after 0 minute(s) and 0 seconds
jellyfin  | [13:18:07] [INF] [11] Emby.Server.Implementations.ScheduledTasks.TaskManager: Webhook Item Added Notifier Completed after 0 minute(s) and 0 seconds
jellyfin  | [13:19:38] [INF] [23] Emby.Server.Implementations.ScheduledTasks.TaskManager: Webhook Item Added Notifier Completed after 0 minute(s) and 0 seconds
jellyfin  | [13:21:09] [INF] [11] Emby.Server.Implementations.ScheduledTasks.TaskManager: Webhook Item Added Notifier Completed after 0 minute(s) and 0 seconds
jellyfin  | [13:22:00] [INF] [3] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for jarvis has succeeded.
jellyfin  | [13:22:00] [INF] [3] Emby.Server.Implementations.Session.SessionManager: Current/Max sessions for user jarvis: 0/0
jellyfin  | [13:22:00] [INF] [3] Emby.Server.Implementations.Session.SessionManager: Creating new access token for user 871ed328-035c-4d72-b1ef-6ba366d9d1f7
jellyfin  | [13:22:01] [INF] [21] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 192.168.1.2 request
jellyfin  | [13:22:40] [INF] [21] Emby.Server.Implementations.ScheduledTasks.TaskManager: Webhook Item Added Notifier Completed after 0 minute(s) and 0 seconds
jellyfin  | [13:22:49] [INF] [21] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
jellyfin  | [13:23:01] [INF] [24] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
jellyfin  | [13:23:13] [INF] [22] Emby.Server.Implementations.Session.SessionWebSocketListener: Lost 1 WebSockets.
jellyfin  | [13:24:11] [INF] [8] Emby.Server.Implementations.ScheduledTasks.TaskManager: Webhook Item Added Notifier Completed after 0 minute(s) and 0 seconds
jellyfin  | [13:25:42] [INF] [14] Emby.Server.Implementations.ScheduledTasks.TaskManager: Webhook Item Added Notifier Completed after 0 minute(s) and 0 seconds
jellyfin  | [13:27:13] [INF] [10] Emby.Server.Implementations.ScheduledTasks.TaskManager: Webhook Item Added Notifier Completed after 0 minute(s) and 0 seconds
jellyfin  | [13:28:44] [INF] [10] Emby.Server.Implementations.ScheduledTasks.TaskManager: Webhook Item Added Notifier Completed after 0 minute(s) and 0 seconds

### Relevant screenshots or videos

https://github.com/user-attachments/assets/951864a2-c0c8-4623-8bd2-afd565e608b9

**Comment by gnattu** [comment]
Raspberry Pi 4 is very slow for trickplay image generation and the image generation will take a long time on a slow CPU. You can check the "Only generate images from key frames" from trickplay settings to speed it up significantly but it could still be very slow on a raspberry pi. You just wait for the images to be generated and the CPU will down to normal.

**Comment by jarvisnexus** [comment]
I understand that Raspberry Pi 4 doesn’t have that much power for generating TrickPlay images. But, why it constantly consuming so much cpu/memory usage that too in the idle state. This is something we need to look into it. 

Is it tries to generate TrickPlay images eveytime during library scanning?

**Comment by crobibero** [comment]
Depends on your settings, but in your logs we can see the following which tells us that your server isn't idle but is actively running TrickPlay generation.

```
jellyfin  | [13:11:11] [INF] [24] Jellyfin.Server.Implementations.Trickplay.TrickplayManager: Finished creation of trickplay files for /DATA/Media/TV Shows/Agatha All Along/Season 1/Agatha All Along - S01E06 - Familiar By Thy Side.mkv
jellyfin  | [13:11:11] [INF] [26] Jellyfin.Server.Implementations.Trickplay.TrickplayManager: Creating trickplay files at 320 width, for /DATA/Media/TV Shows/Agatha All Along/Season 1/Agatha All Along - S01E03 - Through Many Miles of Tricks and Trials.mkv [ID: eb2b57b7-f16a-4356-074e-d6e8640a0970]

```

**Comment by jarvisnexus** [comment]
Oh, Now I get it. I didn’t see those entries in the logs earlier.

In my settings, I have checked all three flags.

- Enbale trickplay image extraction
- Enable trickplay image generation during library scan
- Save trickplay images next to media.

I have disabled all those TrickPlay settings. Now, everything went back to normal.
