### ISSUE TITLE
API Password break

### ISSUE THREAD

**Issue by Floflobel** [jellyfin/jellyfin#1297]
**Describe the bug**
I perform the creation of my user accounts with a script in Python to facilitate the management of the parameters.
I copied my script from my Emby server to test it on a Jellyfin server, everything works fine except password management.

I look at the documentation of the API but it is not yet completed with the parameters to data.

I'm posting my script below, I was doing the password reset at first because there was a problem on Emby that forced me to go through this step.

**To Reproduce**

```
def post(post_wanted, post_data):
        response = requests.post(api_url_base + post_wanted + '?api_key=' + api_token, data=post_data, headers=headers)
        if args.debug:
                print(response.url)
                print(response.status_code)
                print("\n")

def get(get_wanted, get_data):
        response = requests.get(api_url_base + get_wanted + '?api_key=' + api_token, data=get_data, headers=headers)
        return response


for username in args.username:

        # create user
        wanted = 'Users/New'
        data_json = '{"Name":"' + username + '"}'
        post(wanted, data_json)

        # get userid
        wanted = 'Users'
        get_all_user = get(wanted, None).json()
        for user in get_all_user:
                #print user['Name'] + ' ' + user['Id']

                if username == user['Name']:
                        # post user policy for select user
                        data_json = general_policy
                        wanted = 'Users/' + user['Id'] + '/Policy'
                        post(wanted, data_json)
                        # post password for select user
                        data_json = '{\"Id\":\"' + user['Id'] + '\",\"CurrentPassword\":\"\",\"CurrentPw\":\"\",\"NewPw\":\"' + password + '\",\"ResetPassword\":true}'
                        wanted = 'Users/' + user['Id'] + '/Password'
                        post(wanted, data_json)
                        data_json = '{\"Id\":\"' + user['Id'] + '\",\"CurrentPassword\":\"\",\"CurrentPw\":\"\",\"NewPw\":\"' + password + '\",\"ResetPassword\":false}'
                        wanted = 'Users/' + user['Id'] + '/Password'
                        post(wanted, data_json)`
```

I also tried to spend the next json: 
```{"CurrentPw":"","NewPw":"test"}```

**Comment by oddstr13** [comment]
See #1299 , quite possibly related.

**Comment by bugfixin** [comment]
I don't think the fix for 1299 will fix this, as the submission is json here.

Two things to check: is it possible to verify the content-type is being set to application/json correctly with the python, and is it possible to test with a user whose current password is set to a non-blank?

**Comment by oddstr13** [comment]
https://stackoverflow.com/a/26344315

```python
r = requests.post('http://example.com/post', json={"key": "value"})
```
This should also make your code a lot cleaner!

**Comment by sparky8251** [comment]
Is this still an issue? If not we should close this issue.

**Comment by nwithan8** [comment]
Reopen? This still seems to be broken. Constantly getting a 500 error

**Comment by anthonylavado** [comment]
@nwithan8 What’s happening?

**Comment by nwithan8** [comment]
Getting a 500 error when attempting to POST request to change a user's password.

**Comment by JustAMan** [comment]
Could you please post your code you're trying to run, and some relevant bits from Jellyfin log?

**Comment by nwithan8** [comment]
Demoing with a web request application:

POST https://myip.com/jellyfin/Users/{userID}/Password?api_key={apiKey}
Headers:
```
content-type: application/json
accept: application/json
```
Body:
```
{
  "Id": "{UserId}",
  "CurrentPw": "{currentPassword}",
  "NewPw": "{newPassword}!",
  "ResetPassword": true
}
```
Returns:
```500 Internal Server Error: Object reference not set to an instance of an object.```

Log from request:
`[2019-12-02 13:46:00.947 -05:00] [ERR] Error processing request
System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaBrowser.Api.BaseApiService.AssertCanUpdateUser(IAuthorizationContext authContext, IUserManager userManager, Guid userId, Boolean restrictUserPreferences)
   at MediaBrowser.Api.UserService.PostAsync(UpdateUserPassword request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)`

**Comment by JustAMan** [comment]
Is this with JF 10.4.2?

**Comment by nwithan8** [comment]
I believe so. Whatever the latest Docker version is/was as of Dec. 2

**Comment by JustAMan** [comment]
@Bond-009 or @cvium does this ring a bell for you?

**Comment by D347HxD** [comment]
Has anyone come to a solution for this?

**Comment by nwithan8** [comment]
Yes, thanks to @callmekory, turns out you need to reset the password first, THEN set a password.

**Comment by dkanada** [comment]
Can you post an example here for future discussion? We definitely need to overhaul the password reset at some point.

**Comment by callmekory** [comment]
Here are some examples from the code I'm working on right now for a project. Hope this helps in the future for the next person.

```js
/**
 * Resets the password for the specified user
 * @param userID User ID of user to reset password
 */
const resetPassword = async (userID) => {
  const response = await post(`${host}/Users/${userID}/Password`)
    .headers({ 'X-Emby-Token': token })
    .send({
      Id: userID,
      ResetPassword: true
    })

  console.log(response.body)
  console.log(response.code)
}

/**
 * Set the password of the specified user
 * @param userID User ID of the user to set password
 */
const setUserPassword = async (userID) => {
  const response = await post(`${host}/Users/${userID}/Password`)
    .headers({ 'X-Emby-Token': token })
    .send({
      Id: userID,
      CurrentPw: '',
      NewPw: 'newPass'
    })

  console.log(response.body)
  console.log(response.code)
}
```

**Comment by dkanada** [comment]
That is the strangest way possible to design a password reset.

**Comment by callmekory** [comment]
If I could suggest that we be able to manage user accounts with only the API key? Right now you can to login via the app THEN use that auth token to make changes. We're using 2 separate authorizations atm and it could be migrated to simple the API key
