### ISSUE TITLE
CSS theming issues since 10.10.1 on Ubuntu

### ISSUE THREAD

**Issue by chp-1960** [jellyfin/jellyfin#12983]
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

After upgrading to version 10.10.1 on Ubuntu, I face CSS theming issues.
All my css defined themes are broken in that release an I had to uninstall them from the general section.

**Nota :** I use personal themes and, for testing purposes, downloaded themes.

I see this behavior on the web client and in JMP.

Is it a known bug?
How can I correct this?
or
How can I rollback to 10.10.0 build?  

### Reproduction steps

**How to reproduce :** 
In the "General" section of the Dashboard, under custom CSS, if I set any of my previously (and working) themes I face all the theming is lost with no backgrounds, pictures, colors, sizes, icons,... defined in the css description.
If I reset (leave blank) the custom CSS field, the "standard" included themes are used.

### What is the current _bug_ behavior?

No more css user defined themes

### What is the expected _correct_ behavior?

Entering a user css defined theme should be applied after "Apply"

### Jellyfin Server version

10.10.0+

### Specify the build version

10.10.1

### Environment

- OS:
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:

### Jellyfin logs

none

### FFmpeg logs

none

### Client / Browser logs

none

**Comment by nielsvanvelzen** [comment]
Each release contains changes to the DOM and elements will get have classes removed or added. You'll need to update your custom CSS to adapt for the new release yourself.

**Comment by chp-1960** [comment]
Hummm... I suspected it could be something like that.

It's very disturbing to me. I spent years composing my themes, inspired by the work of others (I'm not a programmer), proud of what I've accomplished and I don't see myself redoing them at all.

Why not include backwards compatibility in this case? And even reading the release notes, I can't find the necessary information about which ones are obsolete or modified.

**Comment by joshuaboniface** [comment]
Ultimately, from an overall project perspective, themes have always been a user customization thing and not part of our workflows; this is why we do not provide alternate themes with the project itself - one theme is enough work. As the WebUI changes both for cleanup and to add new features, there will be changes to the underlying CSS and DOM. Web is mainly the work of one man, and I don't think burdening him even further with the idea that "3rd party or custom themes must remain compatible between major versions" is a reasonable ask.

For something this in-depth, fully reviewing the full release changelog (i.e. the full list of PRs) would be the only viable solution. It is up to theme authors to keep on top of this, update their themes (ideally, during the pre-release testing windows or by following unstable releases directly), and handle any changes as needed.

Longer-term, as the WebUI stabilizes a bit more and there's less cleanup, this will probably get easier. But for now, expect regular breakage of themes as the WebUI continues to evolve.

**Comment by chp-1960** [comment]
Well, I never asked for support, by the Jellyfin team, of alternative css themes developed by users. I was talking about the continuation of the support of these "historical" and "self-made" css themes that have required, for some users, a long time and passion to develop these css themes.

Making them incompatible, even for reasons of evolution of Jellyfin and with a wave of the hand, without even warning, as I read above, can be very damaging for many. The minimum is, in my humble opinion, to allow to continue to support them as is and as it was the case until the 10.10.0 build.

If it is not a desire displayed for changes in the way of supporting these user css themes, it is perhaps a bug in Jellyfin and that is why I opened this ticket.
