### ISSUE TITLE
Jellyfin not recognizing correct web directory

### ISSUE THREAD

**Issue by NickCloudAT** [jellyfin/jellyfin#12980]
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

After starting up my jellyfin server today, I noticed that the web client would not load and just show a blank page.

I typed "jellyfin" in my server and got the following information:

![Image](https://github.com/user-attachments/assets/eafb124f-4f75-4ce4-922f-81a6db7e6a37)

The error at the bottom tells me, it can't find the directory at "/usr/lib/jellyfin/bin/jellyfin-web". And yes, that is correct. There is not web-directory at that path because for me it is, and always has been, at "/usr/share/jellyfin/web". It even shows in the service that it sets that path with --webdir:
![Image](https://github.com/user-attachments/assets/c07c0c82-8767-4ff1-bf9a-324541678181)

I don't really know why the hell it's not working. Jellyfin is installed on this maschine with apt, no docker or smth.

### Reproduction steps

I dont have any.

### What is the current _bug_ behavior?

Web directory is not recognized correctly

### What is the expected _correct_ behavior?

Web directory should be recognized correctly

### Jellyfin Server version

10.10.0+

### Specify the build version

I can not access the dashboard

### Environment

- OS: Ubuntu 22.04.5 LTS

### Jellyfin logs

Log seems empty

**Comment by gnattu** [comment]
If you just type Jellyfin it won't use custom folder, and no Jellyfin run by systemd services does not affect just type in "jellyfin" in the console. What you want to do is to start Jellyfin with systemd.

**Comment by NickCloudAT** [comment]
> If you just type Jellyfin it won't use custom folder, and no Jellyfin run by systemd services does not affect just type in "jellyfin" in the console. What you want to do is to start Jellyfin with systemd.
> 
> For your original "just blank" problem we are unable to help you without further info. Have you tried clear browser cache first?

I have already tried to clear my browser cache and also use another browser. Actually as I see now, the Android App also does not load the server.

**Comment by NickCloudAT** [comment]
Ok, fixed it myself.. Seems like the web directory was corrupt or smth.. No errors in log though hinting to anything like that...

Pulled down a backup of the web folder, working again now.
