### ISSUE TITLE
Add support for Ubuntu 19.04

### ISSUE THREAD

**Issue by eglia** [jellyfin/jellyfin#1300]
Jellyfin and jellyfin-ffmpeg currently can't be installed on Ubuntu 19.04 because of missing dependencies for libssl, libx264 and libx265.

A workaround is to use the docker build.

**Comment by joshuaboniface** [comment]
Can you confirm the exact error(s) on Ubuntu 19.04? It was just released the other day and it hasn't been on my radar.

**Comment by eglia** [comment]
```
The following packages have unmet dependencies.
 jellyfin : Depends: libssl1.0.0 but it is not installable or
                     libssl1.0.2 but it is not installable
 jellyfin-ffmpeg : Depends: libx264-152 but it is not installable
                   Depends: libx265-160 (>= 2.8) but it is not installable
```

Ubuntu 19.04 only ships the following libraries:

```
libssl1.1
libx264-155
libx265-165
```

**Comment by joshuaboniface** [comment]
I've put some test packages up. IIRC there were potential compatibility issues with libssl1.1 but feedback welcome!

https://repo.jellyfin.org/releases/server/disco/

**Comment by eglia** [comment]
The jellyfin-ffmpeg package can be installed, however the jellyfin package still depends on libssl1.0.0 and can't be installed.

**Comment by joshuaboniface** [comment]
Whoops I guess my change didn't build in. I uploaded a new version - can you try again?

**Comment by eglia** [comment]
Thanks, everything seems to work fine. However, I use a nginx reverse proxy, so I'm not sure if I'm actually using the libssl dependency...

**Comment by joshuaboniface** [comment]
Maybe not but it's loaded on startup, so if it didn't crash hard it *should* be OK IIRC.

**Comment by EraYaN** [comment]
libssl is used for the client side by dotnet core as well (when it talks to some webservice over TLS)

**Comment by anthonylavado** [comment]
Can this be clsoed now?
