### ISSUE TITLE
add a server option to force transcoding of images

### ISSUE THREAD

**Issue by cipitaua** [jellyfin/jellyfin#13008]
Some clients cannot determine the proper rotation of images, e.g.

https://github.com/jellyfin/jellyfin-web/issues/3593
https://github.com/jellyfin/jellyfin-tizen/issues/73
https://github.com/jellyfin/jellyfin-tizen/issues/304
https://github.com/jellyfin/jellyfin-webos/issues/114

which in particular makes portrait photos shown in landscape, with wrong orientation.

It would be needed an option to pre-process the photos at server level, so to circumvent any client side issue.

As a side advantage, that could in principle also permit to chose among a set of upscaling algorithms, possibly improving the rendered quality.

**Comment by felix920506** [comment]
Please send feature requests to https://features.jellyfin.org/

**Comment by robbah** [comment]
Is this really a feature request is what i am thinking? It looks to me more like a fix for buggy clients.
