### ISSUE TITLE
Jellyfin 10.10.1 Google Cast Unsupported on Macos 13.7.1

### ISSUE THREAD

**Issue by rruggiero** [jellyfin/jellyfin#13015]
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

After upgrading to 10.10.1 on macos 13.7.1 (Ventura) Google cast stopped working.  I restored to version 10.9.6 from time-machine backups restarted the WiFi connection on the iMac and on the Samsung TV and casting started working once again.

Please tell me how to get the logfiles you want to track down the issue.

Regards,

Rick

### Reproduction steps

1. Sign on to Jellyfin web interface
2. Click on Google Cst icon top right of screen

### What is the current _bug_ behavior?

Can only see:
    My Device

### What is the expected _correct_ behavior?

Can see:
    My Device
    Pioneer VSX-832-DLNA
    Samsung Q60AA 55 TV-DLNA
    Sony Bravia.....

### Jellyfin Server version

10.10.0+

### Specify version number

10.10.1

### Specify the build version

unknown now

### Environment

```markdown
- OS: MacOS
- Linux Kernel:
- Virtualization:
- Clients: Browser
- Browser: Firefox, Google Chrome, Microsoft Edge
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
Not sure what to search for
```

### FFmpeg logs

```shell
No longer available without reinstalling 10.10.1
```

**Comment by crobibero** [comment]
You need to update the DLNA plugin when updating to 10.10.

**Comment by rruggiero** [comment]
Hi,

Thank you for quick response. 

I am running the latest version 5.0.0.0. I just tried to uninstall it and reinstall it, but who know what it actually did.

Kind regards,

Rick

**Comment by rruggiero** [comment]
Well, this problem has persisted with **10.10.3** as well.

I am running **JellyFIn 10.10.3** and **DLNA 5.0.0** (Refer to attached images) for details.

<img width="269" alt="Image" src="https://github.com/user-attachments/assets/d58a7bd7-20e3-4d8d-955d-ccd708b134b1" />
<img width="827" alt="Image" src="https://github.com/user-attachments/assets/33b1dc35-526b-4251-a6dd-d52fd95f3bcc" />
<img width="294" alt="Image" src="https://github.com/user-attachments/assets/453b28c9-980f-4bf4-bcfb-3b3806c469da" />
<img width="363" alt="Image" src="https://github.com/user-attachments/assets/6936de1a-731d-4757-9f24-2f96f6079343" />

**Comment by felix920506** [comment]
Please make sure the following conditions are met:
1. You are accessing the server using Chrome browser
2. [You are connecting to the server over HTTPS] OR [You are connecting to the server using localhost as IP]

**Comment by rruggiero** [comment]
Thank you for your message.  I generally use firefox, but have also tried with chrome, safari and edge.  I have no problem connecting to my TVs with Apple Airplay, but each time I install 10.10+ I end up with this problem and the only reason why I updated again (yesterday) is becasue of my TV (Android) not being able to connect to the 10.9.6 version that was working fine.

I also only use HTTP (http://localhost:8096, or http://imac2.domainname:8096)

**Comment by felix920506** [comment]
I an unable to reproduce this issue on a macOS 14.5 server using the latest weekly build.
You need https and use chrome in order for google cast to work.
Please head to our forum or chat rooms for troubleshooting. https://jellyfin.org/contact

**Comment by rruggiero** [comment]
Was the https requirement added to 10.10+?I have never used https over the past few years of using JellyFin.Kindest regards,Rick Ruggiero---Sent from my iPhoneOn 16 Dec 2024, at 12:21 pm, felix920506 ***@***.***> wrote:﻿
I an unable to reproduce this issue on a macOS 14.5 server using the latest weekly build.
You need https and use chrome in order for google cast to work.
Please head to our forum or chat rooms for troubleshooting. https://jellyfin.org/contact

**Comment by gnattu** [comment]
It is enforced by Google that you need secure context (either https or localhost) to use Cast
