### ISSUE TITLE
Trickplay images not shown during fast-forwarding.

### ISSUE THREAD

**Issue by samthesamman** [jellyfin/jellyfin#13012]
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

Trickplay images are not showing during fast-forwarding.

### Reproduction steps

1. Turn on Trickplay and wait until the process is completed
2. Open movie/show and hover over scrubber bar with cursor to confirm Trickplay images generated.
3. Press the fast-forward button and notice the Trickplay images don't appear. 

### What is the current _bug_ behavior?

No trickplay images shown during fast-forwarding.

### What is the expected _correct_ behavior?

The trickplay images should appear during fast-forwarding. This is especially important for devices that don't have a mouse/cursor input. Trickplay images on fast-forward are expected since other video platforms all have these.

### Jellyfin Server version

10.10.0+

### Specify the build version

10.10.0

### Environment

```markdown
- OS: Ubuntu 24.04
- Linux Kernel:
- Virtualization: Docker
- Clients: All
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
N/A
```

### FFmpeg logs

```shell

```

**Comment by crobibero** [comment]
This is a client specific issue. Which client are you reporting this for?

**Comment by samthesamman** [comment]
Android (using both html and integrated video players), Android TV, web, and MacOS client. The Android client with integrated player doesn't have fast forward button but when I try to scrub by dragging no trickplay images show at all. 

My Trickplay process has not yet completed but I know it has completed for the movies I'm testing since I can see the Trickplay images when I hover my mouse over the scrubber for the selected movies.

**Comment by crobibero** [comment]
Closing as this is a feature request for all clients.
Please direct your request to https://features.jellyfin.org/

**Comment by gnattu** [comment]
I think the progress bar is draggable on touchscreen

**Comment by samthesamman** [comment]
It's not visible for me on iPad or Android app when I drag on the scrubber.

**Comment by gnattu** [comment]
It is visible for me on iPad
