### ISSUE TITLE
Resuming doesn't work

### ISSUE THREAD

**Issue by Vitorvlv** [jellyfin/jellyfin#1301]
**Describe the bug**
Resume doesn't work. If I have watched something and left it at some point, I have to restart it from the beginning to be able to watch it.
I'm also not able to jump around the video once it happens. 

It happens with every video I have in my catalog, with the example I provided, i'm playing it with direct play, no transcoding.

Edit: As of 10.3.3 this issue is still happening

**To Reproduce**

1. Watch something to the point that jellyfin records the point you stopped
2. Leave
3. Go back to it
4. Black screen

**Expected behavior**
It should play normally from the point I stopped watching.

**Screenshots**
https://gfycat.com/ThirdArcticHeterodontosaurus

**System (please complete the following information):**
 - OS: Manjaro
 - Browser: Firefox
 - Jellyfin Version: 10.3.1
 - Reverse proxy: none

**Comment by anthonylavado** [comment]
Is this is the web interface, or through a client?

**Comment by bugfixin** [comment]
The screencap looks to be the web interface - I'm curious if this is resolved by #1287

**Comment by Vitorvlv** [comment]
> Is this is the web interface, or through a client?

Yeah, it is the web interface.

**Comment by anthonylavado** [comment]
I missed the screenshot. This really _shouldn't_ have been hit by #1287, but it's entirely possible. Stay tuned for 10.3.2 soon.

**Comment by Vitorvlv** [comment]
Hi, the issue hasn't been fixed with 10.3.2.
Here's a screencap showing it:
https://gfycat.com/ElementaryScholarlyCaecilian

**Comment by anthonylavado** [comment]
Just to be entirely sure, because I can’t make it out from here:
Is this in incognito/private mode to avoid cache issues when testing?
Can we get the logs from the time you are trying to resume?

Thank you :-)

**Comment by Vitorvlv** [comment]
[logs jellyfin.zip](https://github.com/jellyfin/jellyfin/files/3134423/logs.jellyfin.zip)

Hey, sorry, I wans't sure what to look for exactly, so I'm just sending you the complete logs.
I tried in incognito mode and it also didn't work.

**Comment by bugfixin** [comment]
I see a lot of ffmpeg failures there - Do you have space in /var/lib/jellyfin/transcoding-temp/?

Can you explicitly run `/usr/bin/ffmpeg -ss 00:02:18.000 -fflags +genpts -noaccurate_seek -f matroska,webm -i file:"/mnt/hdsecundario/Media/TV/Seinfeld/Season 7/Seinfeld.S07E11.The.Rye.1080p.AMZN.WEBRip.DD2.0.x264-NTb.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 copy -bsf:v h264_mp4toannexb -copyts -vsync -1 -codec:a:0 aac -strict experimental -ac 2 -ab 192000  -f segment -max_delay 5000000 -avoid_negative_ts disabled -start_at_zero -segment_time 6 -segment_time_delta -138 -individual_header_trailer 0 -break_non_keyframes 1 -segment_format mpegts -segment_list_type m3u8 -segment_start_number 23 -segment_list "/var/lib/jellyfin/transcoding-temp/46fff9e693657d097b38bf0b2e66e71c.m3u8" -y "/var/lib/jellyfin/transcoding-temp/46fff9e693657d097b38bf0b2e66e71c%d.ts" ` in a terminal and let us know what errors it shows?

**Comment by Vitorvlv** [comment]
Here's the output in the terminal:

```
ffmpeg version n4.1.3 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20181127
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-nvdec --enable-nvenc --enable-omx --enable-shared --enable-version3
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Guessed Channel Layout for Input Stream #0.1 : stereo
Input #0, matroska,webm, from 'file:/mnt/hdsecundario/Media/TV/Seinfeld/Season 7/Seinfeld.S07E11.The.Rye.1080p.AMZN.WEBRip.DD2.0.x264-NTb.mkv':
  Metadata:
    encoder         : libebml v1.3.4 + libmatroska v1.4.5
    creation_time   : 2017-06-18T17:04:56.000000Z
  Duration: 00:22:48.99, start: 0.000000, bitrate: 14704 kb/s
    Chapter #0:0: start 0.430000, end 43.590000
    Metadata:
      title           : Opening Credits, Elaine attends a performance
    Chapter #0:1: start 43.590000, end 590.591000
    Metadata:
      title           : Hot and heavy
    Chapter #0:2: start 590.591000, end 591.130000
    Metadata:
      title           : Break
    Chapter #0:3: start 591.130000, end 1301.137000
    Metadata:
      title           : Making everything right
    Chapter #0:4: start 1301.137000, end 1368.993000
    Metadata:
      title           : End Credits
    Stream #0:0: Video: h264 (High), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)
    Metadata:
      BPS             : 14477616
      BPS-eng         : 14477616
      DURATION        : 00:22:48.993000000
      DURATION-eng    : 00:22:48.993000000
      NUMBER_OF_FRAMES: 32823
      NUMBER_OF_FRAMES-eng: 32823
      NUMBER_OF_BYTES : 2477469403
      NUMBER_OF_BYTES-eng: 2477469403
      _STATISTICS_WRITING_APP: mkvmerge v12.0.0 ('Trust / Lust') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v12.0.0 ('Trust / Lust') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2017-06-18 17:04:56
      _STATISTICS_WRITING_DATE_UTC-eng: 2017-06-18 17:04:56
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:1(eng): Audio: eac3, 48000 Hz, stereo, fltp (default)
    Metadata:
      BPS             : 224000
      BPS-eng         : 224000
      DURATION        : 00:22:48.960000000
      DURATION-eng    : 00:22:48.960000000
      NUMBER_OF_FRAMES: 42780
      NUMBER_OF_FRAMES-eng: 42780
      NUMBER_OF_BYTES : 38330880
      NUMBER_OF_BYTES-eng: 38330880
      _STATISTICS_WRITING_APP: mkvmerge v12.0.0 ('Trust / Lust') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v12.0.0 ('Trust / Lust') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2017-06-18 17:04:56
      _STATISTICS_WRITING_DATE_UTC-eng: 2017-06-18 17:04:56
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:2: Subtitle: subrip
    Metadata:
      BPS             : 96
      BPS-eng         : 96
      DURATION        : 00:21:36.795000000
      DURATION-eng    : 00:21:36.795000000
      NUMBER_OF_FRAMES: 353
      NUMBER_OF_FRAMES-eng: 353
      NUMBER_OF_BYTES : 15607
      NUMBER_OF_BYTES-eng: 15607
      _STATISTICS_WRITING_APP: mkvmerge v12.0.0 ('Trust / Lust') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v12.0.0 ('Trust / Lust') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2017-06-18 17:04:56
      _STATISTICS_WRITING_DATE_UTC-eng: 2017-06-18 17:04:56
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:3: Subtitle: subrip
    Metadata:
      BPS             : 91
      BPS-eng         : 91
      DURATION        : 00:21:36.879000000
      DURATION-eng    : 00:21:36.879000000
      NUMBER_OF_FRAMES: 353
      NUMBER_OF_FRAMES-eng: 353
      NUMBER_OF_BYTES : 14771
      NUMBER_OF_BYTES-eng: 14771
      _STATISTICS_WRITING_APP: mkvmerge v12.0.0 ('Trust / Lust') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v12.0.0 ('Trust / Lust') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2017-06-18 17:04:56
      _STATISTICS_WRITING_DATE_UTC-eng: 2017-06-18 17:04:56
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:4: Subtitle: subrip
    Metadata:
      BPS             : 91
      BPS-eng         : 91
      DURATION        : 00:21:36.879000000
      DURATION-eng    : 00:21:36.879000000
      NUMBER_OF_FRAMES: 353
      NUMBER_OF_FRAMES-eng: 353
      NUMBER_OF_BYTES : 14771
      NUMBER_OF_BYTES-eng: 14771
      _STATISTICS_WRITING_APP: mkvmerge v12.0.0 ('Trust / Lust') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v12.0.0 ('Trust / Lust') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2017-06-18 17:04:56
      _STATISTICS_WRITING_DATE_UTC-eng: 2017-06-18 17:04:56
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (eac3 (native) -> aac (native))
Press [q] to stop, [?] for help
[segment muxer @ 0x559d11746380] Value -138.000000 for parameter 'segment_time_delta' out of range [0 - 9.22337e+12]
[segment muxer @ 0x559d11746380] Error setting option segment_time_delta to value -138.
Could not write header for output file #0 (incorrect codec parameters ?): Numerical result out of range
Error initializing output stream 0:1 -- 
[aac @ 0x559d1174d700] Qavg: -nan
Conversion failed!
```

> I see a lot of ffmpeg failures there - Do you have space in /var/lib/jellyfin/transcoding-temp/?
I believe I do, how do I check something like that ? And If I don't, how would I go about fixing it ?

**Comment by doguitar** [comment]
I have this same issue. Playing a video from anywhere but the beginning doesn't work if it's transcoded. 

In all the problem ffmpeg logs I have the a negative `segment_time_delta` (which how I found this bug report).

Let me know if there's anything I can do to help debug this.

**Comment by jofr49** [comment]
Same problem to resuming tv shows. For films, it works perfectly ! 
I renamed all my tv shows with naming convention, as "My shows S01E01" then re-updated the metadata of TV Shows library, but still don't work.
For info, i'm using the embycon plugin on kodi 17 and 18.

**Comment by Vitorvlv** [comment]
@jofr49 now that you mentioned it, movies actually work fine, the problem only shows up on tv shows hahaha.


Welp, that's weird. I'm also using the correct naming convention and everything.

**Comment by jofr49** [comment]
> @jofr49 now that you mentioned it, movies actually work fine, the problem only shows up on tv shows hahaha.
> 
> Welp, that's weird. I'm also using the correct naming convention and everything.

Well, i'm not feeling alone anymore ! I'm not completely fool ;-)
I tried to remove the (group automatically  tv shows...) option in "advanced options" for Tv Shows library. Then I updated the metadata.
But same thing, I can't resume an episode to an old progress spot.
I observed in the jellyfin.log, as soon as I play a shows episode, every seasons of the show
are verified (is EligibleForDirectStrem:True).... It doesn't appear for a movie. 
I join a log file
[jellyfin_002.log](https://github.com/jellyfin/jellyfin/files/3261649/jellyfin_002.log)

Thank's

**Comment by jofr49** [comment]
I tried to play a tv show (Bones S01E01) from the movies library and the resuming works perfectly !
So I think it's a problem with the tv shows library.

My 2 cents ;-)

**Comment by doguitar** [comment]
Can you two attach the `ffmpeg-transcode-*` logs for a failed a successful example? 

I'm looking into the issue and I want to confirm my suspicions about what your successful commands are going to look like.

For anyone else looking into this, I suspect that the issue is stemming from [this](https://github.com/FFmpeg/FFmpeg/commit/3bfd409e59e8ce9f168bfa07f20bbe869af37522#diff-17f90a02c9b2e8374313f1379a61796e) change in ffmpeg. I'm trying to figure out what value _should_ be.

**Comment by jofr49** [comment]
There are ffmpeg-transcode and ffmpeg-remux logs. 
[ffmpeg-transcode-8e36a5c8-0175-4b5d-b250-be0d62237d87.txt](https://github.com/jellyfin/jellyfin/files/3263142/ffmpeg-transcode-8e36a5c8-0175-4b5d-b250-be0d62237d87.txt)
[ffmpeg-remux-edbce138-2c11-4bdd-b10a-7473b48a56b5.txt](https://github.com/jellyfin/jellyfin/files/3263143/ffmpeg-remux-edbce138-2c11-4bdd-b10a-7473b48a56b5.txt)

I never (or not often) use web browser or android app to play a movie or a tv show to avoid transcoding, because the cpu of my server is not so beefy for that.
If I try to resume to my web browser (Firefox), it works perfectly. Even a tv show (like Flash).
Thank's

**Comment by doguitar** [comment]
The current implementation for the `segment_time_delta` parameter is as follows:

```
            if (isEncoding && startNumber > 0)
            {
                var startTime = state.SegmentLength * startNumber;
                timeDeltaParam = string.Format("-segment_time_delta -{0}", startTime);
            }
```

Note the dash preceding the startTime in the string format, forcing the value to be negative. This is invalid according to [this recent(ish) ffmpeg change](https://github.com/FFmpeg/FFmpeg/commit/3bfd409e59e8ce9f168bfa07f20bbe869af37522#diff-17f90a02c9b2e8374313f1379a61796e). Emby has the same issue with the resolution being [rolling back to the "correct" ffmpeg version](https://github.com/MediaBrowser/Emby/issues/3470), presumably before that change was included.

I can confirm that either removing forced negative allows me to resume/seek, as does removing the use of the variable completely (I was unable to discern a difference). 

```segment_time_delta delta
Specify the accuracy time when selecting the start time for a segment, expressed as a duration specification. Default value is "0".

When delta is specified a key-frame will start a new segment if its PTS satisfies the relation:
PTS >= start_time - time_delta

This option is useful when splitting video content, which is always split at GOP boundaries, in case a key frame is found just before the specified split time.

In particular may be used in combination with the ffmpeg option force_key_frames. The key frame times specified by force_key_frames may not be set accurately because of rounding issues, with the consequence that a key frame time may result set just before the specified time. For constant frame rate videos a value of 1/(2*frame_rate) should address the worst case mismatch between the specified time and the time set by force_key_frames.```

I'm not familiar enough with ffmpeg and video encoding to really understand the purpose. If anyone can speak to the purpose of including the `segment_time_delta` and what the value should be I think it would resolve this issue.

**Comment by jofr49** [comment]
@doguitar  Can I change this parameter somewhere, easily ? Or is it into the program itself and compiled ?

**Comment by doguitar** [comment]
It's in the compiled code. I'm guessing you're using the docker container (I think everyone using the docker container _should_ be having this issue...)? The only real option you'd have to work around that would be to link an older ffmpeg binary over the top of the docker's binaries.

**Comment by jofr49** [comment]
Ok. I'm using an lxc container with debian stretch package though. So I think it's a machine container instead of application container ?
Do you think the problem still the same ?

**Comment by doguitar** [comment]
The logs you linked earlier don't have the problem I've found because you're on an older ffmpeg version. `ffmpeg version 4.0.4 ` from the look of your logs. Jellyfin is still passing the negative number but the older version of ffmpeg doesn't have the checks in place to validate the range so it accepts it. I don't know _what_ it does with the negative number but it does accept it...

**Comment by jofr49** [comment]
I installed ffmpeg from debian repository and jellyfin-ffmpeg package from jellyfin repo.
Is it a problem to have both on the same machine ?
Thanks for your work anyway !

**Comment by doguitar** [comment]
There's no issue with running both. You're install of jellyfin is pointing at the jellyfin ffmpeg.

**Comment by doguitar** [comment]
I've found [this PR664](https://github.com/jellyfin/jellyfin/pull/664) which addresses this issue. However, it was reverted for introducing other bugs which I also experienced. It seems like the real issue is using ffmpeg => 4.1.

**Comment by doguitar** [comment]
After further investigation, the docker image I was using was not the official docker image and had a newer, unsupported version of ffmpeg included. I'd recommend @Vitorvlv  take a look and see if he's doing the same thing. From the looks of his logs, he's also using an unsupported version of ffmpeg (4.1).

Assuming that's the case, this issue can probably be closed.

**Comment by jofr49** [comment]
I reinstalled the jellyfin server and I tested again to launch an episode of tv show and a movie. There is some information:
If I launch an episode of a tv show, like Flash, FROM the android app to the embycon addon for kodi (cast) 17 or 18, the episode start always to the beginning.
Though, if I play the same episode directly from kodi embycon addon (Without the jellyfin Android app), the episode resuming correctly to the last progress.
Same thing using the emby web and casting to embycon addon.
For a movie, everything works well. I can resuming to the last progress without any problem !
I tried with emby server, and it seems to be the same problem with tv shows.
I expect I am clear ;-)

jellyfin server version: 10.3.5
Thank's

**Comment by Vitorvlv** [comment]
Yep, using ffmpeg 4.1.

Seems like a good explanation. I just saw on the project roadmap that support for 4.1 ffmpeg is planned, so I guess just wait until then.

I guess that's that, will close the issue now.

**Comment by goliath888** [comment]
I happens to me the same with tv shows and Android client app. So, this is normal then? (If I understood the lasts post correcty?) And will be fixed in the future with the support for 4.1 ffmpeg?

**Comment by Vitorvlv** [comment]
If I remember correctly 4.1 support was already implemented. Might be wrong, not a developer.

But assuming you are on the latest version I think you should open a new issue for it.

**Comment by JustAMan** [comment]
That's completely new bug, currently known, we're working on it.
For reference: https://github.com/jellyfin/jellyfin-web/issues/899
