### ISSUE TITLE
Trickplay images are not generated

### ISSUE THREAD

**Issue by felixschndr** [jellyfin/jellyfin#13020]
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

The creation of trickplay images does not seem to work for me. The task to create the images ran:
![Image](https://github.com/user-attachments/assets/5bc21a76-11b9-42e1-80c3-9ee93b8d9a36)
and
![Image](https://github.com/user-attachments/assets/6f50335e-c2fe-45fc-a67a-1f00b68991e5)
However there are no directories for the trickplay images
```bash
root@4e849a952827:/config/data/metadata/library# find . -name "trickplay" -type d | wc -l
0
```
(This directory comes from https://github.com/jellyfin/jellyfin/issues/11850)

As a consequence I don't see trickplay images no matter the player. I can't see any errors regarding problems creating the images.

I see the dummy images for each chapter of a movie, but not the trickplay images. E.g.
![Image](https://github.com/user-attachments/assets/5328d5ce-fac0-4bd0-8006-a99237729770)

On androidTv I don't see any images when scrubbing through the videos (I am running the newest beta which supports trickplay).

Jellyfin trickplay settings:
![Image](https://github.com/user-attachments/assets/8cd0d89b-5d3e-4ed9-90c1-31add95ed5f3)

### Reproduction steps

Run task to create the images

### What is the current _bug_ behavior?

As a consequence I don't see trickplay images no matter the player. 

### What is the expected _correct_ behavior?

See created images in webplayer.

### Jellyfin Server version

10.10.0+

### Specify the build version

10.10.0

### Environment

```markdown
- OS: Ubuntu 22.04
- Linux Kernel: 6
- Virtualization: Docker
- Clients: Web, Android, AndroidTV
- Browser: Chrome
- FFmpeg Version: ffmpeg version 7.0.2-Jellyfin
- Playback Method: Direct
- Hardware Acceleration:
- GPU Model:
- Plugins: IntroSkipper
```

### Jellyfin logs

```shell
[14:16:19] [INF] [157] Emby.Server.Implementations.ScheduledTasks.TaskManager: Trickplay-Bilder generieren Completed after 0 minute(s) and 0 seconds
```

**Comment by crobibero** [comment]
You need to enable it per-library.
![Image](https://github.com/user-attachments/assets/35fad2bf-755e-4cd8-a3ec-5c1fbab27b81)

**Comment by felixschndr** [comment]
Thank you very much, I was certainly not aware of this
