### ISSUE TITLE
Unable to use networked drive or share as library folder

### ISSUE THREAD

**Issue by smidley** [jellyfin/jellyfin#1303]
**Describe the bug**
Installed latest Jellyfin this morning and set it up from scratch. I am unable to use a mapped network drive or UNC path to a share as a library folder. Not sure if this has ever worked in Jellyfin, but this works in Emby. OS is Server 2019.

**To Reproduce**

1. Go to Library
2. Click on add folder
3. Mapped drive doesn't show up.
4. Try manually entering UNC path and receive error "Unable to find specified path"

**Expected behavior**
I would expect my mapped network drive letter to show up.

**System (please complete the following information):**
 - OS: Windows Server 2019
 - Browser: Any
 - Jellyfin 10.3.1
 - Reverse proxy: None

**Additional context**
Reddit thread with additional info here: https://www.reddit.com/r/jellyfin/comments/bgmra0/unable_to_use_networked_drive_or_share_as_library/

**Comment by marcrentschler** [comment]
I have the exact same problem with Jellyfin.

**Comment by JustAMan** [comment]
How did you install Jellyfin? Via installer or via script? If via installer, did you launch it as a service?
Also please put in your OS and JF version for us to be sure.

**Comment by marcrentschler** [comment]
I installed the newest stable version with the installer on Windows 10 and launched it as a service. It didn't work.

Then I installed that same version on the same machine but without the service and now it works.

**Comment by JustAMan** [comment]
This is not an issue with Jellyfin per se, see https://www.reddit.com/r/jellyfin/comments/dgc7nt/whats_up_with_windows_and_1040/

That said, @anthonylavado has an improved version of Windows installer in the works which would make this clearer.

**Comment by krizly** [comment]
@JustAMan I'm not sure that's the case, I have just setup a clean install of Jellyfin on a new install of Windows 10 which is on connected to a domain. Signed in to Windows10 with UserX, set Jellyfin service to run as UserX. Have mapped drives to D and Z under UserX, but neither show up when trying to add folders to a library, and trying to manually add the server path in the 'Shared Network Folder' field fails.

**Comment by JustAMan** [comment]
paging @EraYaN for he should know better than me
