### ISSUE TITLE
Chinese characters can't be rendered in subtitles.

### ISSUE THREAD

**Issue by freejool** [jellyfin/jellyfin#13040]
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

my issue is like [https://jellyfin.org/docs/general/administration/troubleshooting#text-not-rendering-properly](url)

I install the font to my client system, the subtitles are still squares.

I'm sure it's rendered on client side because when set Settings->Subtitles->Burn subtitles to "All", it renders OK.

This is the header of my ASS subtitle file.

> [Script Info]
; Script generated by Aegisub 3.2.2                                   
; 本WEB版外挂字幕由 风吹来的那片云 双语合并
Synch Point: 0
ScriptType: v4.00+
PlayResX: 0
PlayResY: 0
WrapStyle: 0
Timer: 100.0000
> 
> [V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,方正黑体_GBK,20,&H00FFFFFF,&HF0000000,&H00000000,&H32000000,0,0,0,0,100,100,0,0,1,2,1,2,5,5,2,134

I assume that rendering it requires "方正黑体_GBK" font. I downloaded it and installed it.

I think this shows the font is installed.

in my browser's console
![in my browser's console](https://github.com/user-attachments/assets/1a4557c8-b324-4305-854d-49a307c1b7c3)

I CAN play srt subtitles which does not specifie font.

When checking browser logs, I found useful infomation. it might be the encoding of Chinese chatacters.

The "GBK" in font name indicates that the font use GBK encoding and the log shows jellyfin is looking for some unicode char.

But this can't explain why it can be rendered on the server side.

System info:
MacOS 15.0
Safari Version 18.0 (20619.1.26.31.6) (also tried Chrome Version 130.0.6723.117 (Official Build) (arm64))
I'm not sure where to look for Jellyfin version, but I use docker compose and just pulled the image tag latest.

### Reproduction steps

Play that video and load the font.

### What is the current _bug_ behavior?

the Chinese characters in subtitles are rendered as squares.

### What is the expected _correct_ behavior?

the Chinese characters in subtitles are rendered as it should be.

### Jellyfin Server version

10.10.0+

### Specify the build version

10.10.1

### Environment

```markdown
- OS: Archlinux
- Linux Kernel: 6.11.8-arch1-2
- Virtualization: Docker
- Clients: MacOS 15.0
- Browser: Safari Version 18.0 (20619.1.26.31.6) (also tried Chrome Version 130.0.6723.117 (Official Build) (arm64))
- FFmpeg Version: come with docker image
- Playback Method: Transcode
- Hardware Acceleration: NVENC
- GPU Model: RTX2060
- Plugins: none related
- Reverse Proxy: caddy
- Base URL: /web/#/video
- Networking: host
- Storage: local
```

### Jellyfin logs

```shell
nothing relative
```

### FFmpeg logs

```shell

```

### Client / Browser logs

> libass: Glyph 0x5230 not found in font for (方正黑体_GBK, 400, 0)

**Comment by freejool** [comment]
#3683 is a solution.

Is that the client will only load some English font, CJK font must be downloaded from server in "fall back font folder"?

**Comment by felix920506** [comment]
You need to setup fallback fonts. https://jellyfin.org/docs/general/administration/configuration#fallback-fonts

**Comment by freejool** [comment]
But client is not going to load local font? For what?

**Comment by felix920506** [comment]
Because of how ASS subtitles are rendered they cannot use local fonts. All the fonts have to come from the server.
