### ISSUE TITLE
MissingMethodException: MediaBrowser.Controller.IMediaSegmentManager.GetSegmentsAsync

### ISSUE THREAD

**Issue by HarHarLinks** [jellyfin/jellyfin#13050]
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

Due to other issues, I came across the Intro Skipper now being at https://github.com/intro-skipper/intro-skipper, so I updated/migrated there from the previous repo, which lead me to running the tasks and noticing they fail after a short time.

### Reproduction steps

1. Install Intro-Skipper
2. Run the scheduled task for detection

### What is the current _bug_ behavior?

Task fails after few minutes

### What is the expected _correct_ behavior?

Task completes

### Jellyfin Server version

10.10.0+

### Specify the build version

10.10.2

### Environment

```markdown
- OS: Debian 11
- Linux Kernel: 5.10.0
- Virtualization: Docker
- Clients:
- Browser:
- FFmpeg Version: Docker
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins: Intro Skipper
- Reverse Proxy: nginx
- Base URL: none
- Networking: Bridge
- Storage: local
```

### Jellyfin logs

```shell
jellyfin  | [22:30:49] [ERR] [39] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error executing Scheduled Task
jellyfin  | System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<System.Collections.Generic.IEnumerable`1<MediaBrowser.Model.MediaSegments.MediaSegmentDto>> MediaBrowser.Controller.IMediaSegmentManager.GetSegmentsAsync(System.Guid, System.Collections.Generic.IEnumerable`1<Jellyfin.Data.Enums.MediaSegmentType>)'.
jellyfin  |    at IntroSkipper.Manager.MediaSegmentUpdateManager.UpdateMediaSegmentsAsync(IReadOnlyList`1 episodes, CancellationToken cancellationToken)
jellyfin  |    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
jellyfin  |    at IntroSkipper.Manager.MediaSegmentUpdateManager.UpdateMediaSegmentsAsync(IReadOnlyList`1 episodes, CancellationToken cancellationToken)
jellyfin  |    at IntroSkipper.ScheduledTasks.BaseItemAnalyzerTask.<>c__DisplayClass6_0.<<AnalyzeItems>b__4>d.MoveNext()
jellyfin  | --- End of stack trace from previous location ---
jellyfin  |    at System.Threading.Tasks.Parallel.<>c__53`1.<<ForEachAsync>b__53_0>d.MoveNext()
jellyfin  | --- End of stack trace from previous location ---
jellyfin  |    at IntroSkipper.ScheduledTasks.BaseItemAnalyzerTask.AnalyzeItems(IProgress`1 progress, CancellationToken cancellationToken, IReadOnlyCollection`1 seasonsToAnalyze)
jellyfin  |    at IntroSkipper.ScheduledTasks.DetectIntrosTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
jellyfin  |    at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
```

### FFmpeg logs

```shell

```

**Comment by crobibero** [comment]
This isn't a server issue, the plugin that you have installed isn't compatible with the version of Jellyfin you have installed.

**Comment by jumoog** [comment]
#13051
