### ISSUE TITLE
IPv6 mapped IPv4 address is always considered remote

### ISSUE THREAD

**Issue by n12c** [jellyfin/jellyfin#13054]
Suppose 192.0.2.0/24 is the local network and `Allow remote connections to this server` is off. Then

```
curl -sSf -H 'X-Forwarded-For: 192.0.2.0' http://localhost:8096/system/info/public
```
succeeds, while
```
curl -sSf -H 'X-Forwarded-For: ::ffff:192.0.2.0' http://localhost:8096/system/info/public
```
fails with a 503.

If `Allow remote connections to this server` is turned on, both requests succeed.

Server version 10.10.1
Web version 10.10.1
Build version 10.10.1

**Comment by Shadowghost** [comment]
Please provide logs. A 503 can be anything.

**Comment by n12c** [comment]
I checked again but this 503 doesn't seem to be associated with any log output from the server.

**Comment by n12c** [comment]
While I admit to knowing nothing about the Jellyfin server codebase, that doesn't seem consistent with https://github.com/jellyfin/jellyfin/pull/12094. It seems like this should in principle work.
