### ISSUE TITLE
Some h264 videos (encoding dependent) when streamed by remuxing play poorly: wrong framerate, dropped frames; ffmpeg logs warnings "Non-monotonic DTS ... This may result in incorrect timestamps in the output file."

### ISSUE THREAD

**Issue by tsuereth** [jellyfin/jellyfin#13052]
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

Select video files, which are encoded in h264 - and stream to the `jellyfin-web` player by remuxing (not transcoding) - play back poorly, at a visibly lower framerate than the original video.  In some cases so many frames are dropped that the video may even appear to freeze, although the stream is still running and other channels (audio and subtitles) are fine.

When this occurs, the Jellyfin server's log file for the stream, `FFmpeg.Remux-*` will include frequent warnings from the ffmpeg command performing the remux:

> [vost#0:0/copy @ 0x56517bc84400] Non-monotonic DTS; previous: -1001, current: -1001; changing to -1000. This may result in incorrect timestamps in the output file.
[vost#0:0/copy @ 0x56517bc84400] Non-monotonic DTS; previous: 2002, current: 2002; changing to 2003. This may result in incorrect timestamps in the output file.
[vost#0:0/copy @ 0x56517bc84400] Non-monotonic DTS; previous: 6006, current: 6006; changing to 6007. This may result in incorrect timestamps in the output file.
[vost#0:0/copy @ 0x56517bc84400] Non-monotonic DTS; previous: 9009, current: 9009; changing to 9010. This may result in incorrect timestamps in the output file.
[vost#0:0/copy @ 0x56517bc84400] Non-monotonic DTS; previous: 13013, current: 13013; changing to 13014. This may result in incorrect timestamps in the output file.
...

As the warning implies, ffmpeg is considering the original video's "non-monotonic" decoding timestamps (DTS) as invalid for the output format (the HLS mux), and changing them.  So, yeah, it adjusts frame timings to produce a wrongly-timed video.  🥳 

### Reproduction steps

1. Simply play an affected video file - in a format which can be remuxed rather than transcoded (such as H264 in an MKV container), with non-monotonic timestamps in the source data - through the jellyfin-web client.
   * ~Unfortunately I'm not permitted to share the example video files I know of, and I also don't yet know how to reproduce the condition in a fabricated test video.~
   * *Update December 5*: See issue comments for an example repro video (Big Buck Bunny transcode), and method for producing videos which trigger this behavior (H.264 output from AMDVCE, possibly NVENC).

### What is the current _bug_ behavior?

Playback is overall poor, due to mis-timed (appearing skipped or dropped) video frames.

### What is the expected _correct_ behavior?

The remuxed video plays back the same (with frames appearing at correct times) as the original video file.

### Jellyfin Server version

10.10.0+

### Specify the build version

10.10.2

### Environment

```markdown
- OS: multiple (docker + Windows 11)
- Linux Kernel: any
- Virtualization: any
- Clients: jellyfin-web
- Browser: any
- FFmpeg Version: 7.0.2-Jellyfin
- Playback Method: Remux
- Hardware Acceleration: n/a
- GPU Model: n/a
- Plugins: none
- Reverse Proxy: none
- Base URL: local/private
- Networking: local
- Storage: local
```

### Jellyfin logs

```shell
Jellyfin log snippet:

[2024-11-17 00:55:19.268 +00:00] [INF] [30] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "me". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2024-11-17 00:55:19.268 +00:00] [INF] [30] Jellyfin.Api.Helpers.MediaInfoHelper: RemoteClientBitrateLimit: 15000000, RemoteIP: "192.168.1.1", IsInLocalNetwork: True
[2024-11-17 00:55:19.708 +00:00] [INF] [27] Jellyfin.Api.Controllers.DynamicHlsController: Current HLS implementation doesn't support non-keyframe breaks but one is requested, ignoring that request
[2024-11-17 00:55:19.718 +00:00] [INF] [27] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: "/usr/lib/jellyfin-ffmpeg/ffmpeg" "-analyzeduration 200M -probesize 1G -fflags +genpts -f matroska  -i file:\"... affected file.mkv\" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 copy -bsf:v h264_mp4toannexb -start_at_zero -codec:a:0 copy -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 6 -hls_segment_type fmp4 -hls_fmp4_init_filename \"dc85ff3deaa651baeaa1dccdc51afd57-1.mp4\" -start_number 0 -hls_segment_filename \"/cache/transcodes/dc85ff3deaa651baeaa1dccdc51afd57%d.mp4\" -hls_playlist_type vod -hls_list_size 0 -y \"/cache/transcodes/dc85ff3deaa651baeaa1dccdc51afd57.m3u8\""
```

### FFmpeg logs

```shell
Abridged FFmpeg.Remux example log:

[omitted private file information]

/usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -probesize 1G -fflags +genpts -f matroska  -i file:"... affected file.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 copy -bsf:v h264_mp4toannexb -start_at_zero -codec:a:0 copy -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 6 -hls_segment_type fmp4 -hls_fmp4_init_filename "dc85ff3deaa651baeaa1dccdc51afd57-1.mp4" -start_number 0 -hls_segment_filename "/cache/transcodes/dc85ff3deaa651baeaa1dccdc51afd57%d.mp4" -hls_playlist_type vod -hls_list_size 0 -y "/cache/transcodes/dc85ff3deaa651baeaa1dccdc51afd57.m3u8"


ffmpeg version 7.0.2-Jellyfin Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto=auto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libxml2 --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libharfbuzz --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      59.  8.100 / 59.  8.100
  libavcodec     61.  3.100 / 61.  3.100
  libavformat    61.  1.100 / 61.  1.100
  libavdevice    61.  1.100 / 61.  1.100
  libavfilter    10.  1.100 / 10.  1.100
  libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100
Input #0, matroska,webm, from '... affected file.mkv':

[omitted private file information]

[out#0/hls @ 0x56517bc59b80] Codec AVOption threads (set the number of threads) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
[hls @ 0x56517bc7ef80] Opening '/cache/transcodes/dc85ff3deaa651baeaa1dccdc51afd57-1.mp4' for writing
Output #0, hls, to '/cache/transcodes/dc85ff3deaa651baeaa1dccdc51afd57.m3u8':
  Metadata:
    encoder         : Lavf61.1.100
  Stream #0:0: Video: h264 (High), yuv420p(tv, bt709, progressive), 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 23.98 fps, 23.98 tbr, 24k tbn (default) (original)
  Stream #0:1: Audio: aac (LC), 48000 Hz, stereo, fltp (default) (original)
Press [q] to stop, [?] for help
[vost#0:0/copy @ 0x56517bc84400] Non-monotonic DTS; previous: -1001, current: -1001; changing to -1000. This may result in incorrect timestamps in the output file.
[vost#0:0/copy @ 0x56517bc84400] Non-monotonic DTS; previous: 2002, current: 2002; changing to 2003. This may result in incorrect timestamps in the output file.
[vost#0:0/copy @ 0x56517bc84400] Non-monotonic DTS; previous: 6006, current: 6006; changing to 6007. This may result in incorrect timestamps in the output file.
[vost#0:0/copy @ 0x56517bc84400] Non-monotonic DTS; previous: 9009, current: 9009; changing to 9010. This may result in incorrect timestamps in the output file.
[vost#0:0/copy @ 0x56517bc84400] Non-monotonic DTS; previous: 13013, current: 13013; changing to 13014. This may result in incorrect timestamps in the output file.

[... "Non-monotonic DTS" warnings continue until the stream has completed ... ]
```

### Additional information

In a local Jellyfin server build, I found that adding `-copytb 1` to ffmpeg options resolves this behavior, and *doesn't appear to* cause side-effects in other streams (remuxes or transcodes) in my fairly limited testing.  PR incoming in a moment.

**Comment by tsuereth** [comment]
--> https://github.com/jellyfin/jellyfin/pull/13053

**Comment by bakedhorse** [comment]
Can confirm from the side of NVENC h264 video files having same issue.... over 1000 of them from a month of ripping and handbraking.
They're working just fine on 10.9.11.

**Comment by tsuereth** [comment]
Oh interesting, yeah...!  I didn't check it as a regression until today, but now I can confirm **this behavior arose in the `jellyfin-ffmpeg` 7.x update.**

In a local build of Jellyfin `master`, I swapped the ffmpeg binaries out for older 6.x ones, and an affected video's playback appeared normal + there were no "Non-monotonic DTS" warnings logged.

This last `jellyfin-ffmpeg` 6.x release does not exhibit the behavior: https://github.com/jellyfin/jellyfin-ffmpeg/releases/tag/v6.0.1-8

```
ffmpeg version 6.0.1-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 13-win32 (GCC)
  configuration: --prefix=/opt/ffmpeg --arch=x86_64 --target-os=mingw32 --cross-prefix=x86_64-w64-mingw32- --pkg-config=pkg-config --pkg-config-flags=--static --extra-version=Jellyfin --disable-ffplay --disable-debug --disable-doc --disable-sdl2 --disable-ptx-compression --disable-w32threads --enable-pthreads --enable-shared --enable-lto --enable-gpl --enable-version3 --enable-schannel --enable-iconv --enable-libxml2 --enable-zlib --enable-lzma --enable-gmp --enable-chromaprint --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libass --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libwebp --enable-libvpx --enable-libzimg --enable-libx264 --enable-libx265 --enable-libsvtav1 --enable-libdav1d --enable-libfdk-aac --enable-opencl --enable-dxva2 --enable-d3d11va --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
```

The next `jellyfin-ffmpeg` release, 7.0.2-1 does behave as I initially described in this issue: https://github.com/jellyfin/jellyfin-ffmpeg/releases/tag/v7.0.2-1

```
ffmpeg version 7.0.2-Jellyfin Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 13-win32 (GCC)
  configuration: --prefix=/opt/ffmpeg --arch=x86_64 --target-os=mingw32 --cross-prefix=x86_64-w64-mingw32- --pkg-config=pkg-config --pkg-config-flags=--static --extra-version=Jellyfin --disable-ffplay --disable-debug --disable-doc --disable-sdl2 --disable-ptx-compression --disable-w32threads --enable-pthreads --enable-shared --enable-lto=auto --enable-gpl --enable-version3 --enable-schannel --enable-iconv --enable-libxml2 --enable-zlib --enable-lzma --enable-gmp --enable-chromaprint --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libharfbuzz --enable-libass --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libwebp --enable-libvpx --enable-libzimg --enable-libx264 --enable-libx265 --enable-libsvtav1 --enable-libdav1d --enable-libfdk-aac --enable-opencl --enable-dxva2 --enable-d3d11va --enable-d3d12va --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      59.  8.100 / 59.  8.100
  libavcodec     61.  3.100 / 61.  3.100
  libavformat    61.  1.100 / 61.  1.100
  libavdevice    61.  1.100 / 61.  1.100
  libavfilter    10.  1.100 / 10.  1.100
  libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100
```

**Comment by bakedhorse** [comment]
Since it's `jellyfin-ffmpeg` causing issues, swapping to the older binaries seem to be the best thing to do for anyone having it until a fix is applied. So far from doing this, things seem to work fine.

Using docker compose, you want to download the [6.0.1-8](https://github.com/jellyfin/jellyfin-ffmpeg/releases/tag/v6.0.1-8) binaries from the portable zip files and extract `ffmpeg` and `ffprobe`. For me I put them in the same folder as the `docker-compose.yml` file.

And then add these into the `docker-compose.yml` volume section, for swapping in the older binaries through docker. (You need to change these if you put the binaries in a different folder other than the one with `docker-compose.yml`)
```
- ./ffmpeg:/usr/lib/jellyfin-ffmpeg/ffmpeg
- ./ffprobe:/usr/lib/jellyfin-ffmpeg/ffprobe
```

**Comment by tsuereth** [comment]
That did the trick!  I downloaded a jellyfin-ffmpeg artifact from that PR build: https://github.com/jellyfin/jellyfin-ffmpeg/actions/runs/12251132346

And confirmed it fixes the playback behavior (and no longer warns about "Non-monotonic DTS") in a local Jellyfin build.  Version info pasted below, the rest of the log isn't interesting because ... nothing went wrong.  :)

```
ffmpeg version 7.0.2-Jellyfin Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 13-win32 (GCC)
  configuration: --prefix=/opt/ffmpeg --arch=x86_64 --target-os=mingw32 --cross-prefix=x86_64-w64-mingw32- --pkg-config=pkg-config --pkg-config-flags=--static --extra-version=Jellyfin --disable-ffplay --disable-debug --disable-doc --disable-sdl2 --disable-ptx-compression --disable-w32threads --enable-pthreads --enable-shared --enable-gpl --enable-version3 --enable-schannel --enable-iconv --enable-libxml2 --enable-zlib --enable-lzma --enable-gmp --enable-chromaprint --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libharfbuzz --enable-libass --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libwebp --enable-libvpx --enable-libzimg --enable-libx264 --enable-libx265 --enable-libsvtav1 --enable-libdav1d --enable-libfdk-aac --enable-opencl --enable-dxva2 --enable-d3d11va --enable-d3d12va --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      59.  8.100 / 59.  8.100
  libavcodec     61.  3.100 / 61.  3.100
  libavformat    61.  1.100 / 61.  1.100
  libavdevice    61.  1.100 / 61.  1.100
  libavfilter    10.  1.100 / 10.  1.100
  libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100
```

**Comment by bakedhorse** [comment]
Can confirm this has fixed the problem for NVENC h264 encoded files as well! 
Thank you, and glad I could give some input.
