### ISSUE TITLE
10.10.2 upgrade broken, wrong/missing web resource path

### ISSUE THREAD

**Issue by jaykayenn** [jellyfin/jellyfin#13055]
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

Upgrading Jellyfin 10.10.1 -> 10.10.2 results in broken installation that cannot start. Its looking for files at non-existent path /usr/lib/jellyfin/bin/jellyfin-web
apt reinstall didn't work either. 

### Reproduction steps

1. apt upgrade from a running 10.10.1 -> 10.10.2 (noble2404)

Additional troubleshooting steps taken:

1. Reboot
2. apt reinstall

Same results. 

### What is the current _bug_ behavior?

jellyfin.service = dead
`Nov 17 10:54:07 JKNSERVER2 jellyfin[1327]:    at Jellyfin.Server.Migrations.MigrationRunner.PerformMigrations(IMigrationRoutine[] migrations, MigrationOptions migrationOptions, Actio>Nov 17 10:54:07 JKNSERVER2 jellyfin[1327]:    at Jellyfin.Server.Migrations.MigrationRunner.Run(CoreAppHost host, ILoggerFactory loggerFactory)
Nov 17 10:54:07 JKNSERVER2 jellyfin[1327]:    at Jellyfin.Server.Program.StartServer(IServerApplicationPaths appPaths, StartupOptions options, IConfiguration startupConfig)
Nov 17 10:54:07 JKNSERVER2 jellyfin[1327]: [10:54:07] [INF] Running query planner optimizations in the database... This might take a while
Nov 17 10:54:07 JKNSERVER2 jellyfin[1327]: [10:54:07] [INF] Disposing CoreAppHost
Nov 17 10:54:07 JKNSERVER2 jellyfin[1327]: [10:54:07] [INF] Disposing MusicBrainzArtistProvider
Nov 17 10:54:07 JKNSERVER2 jellyfin[1327]: [10:54:07] [INF] Disposing MusicBrainzAlbumProvider
Nov 17 10:54:07 JKNSERVER2 jellyfin[1327]: [10:54:07] [INF] Disposing PluginManager
Nov 17 10:54:07 JKNSERVER2 systemd[1]: jellyfin.service: Deactivated successfully.`

jellyfin CLI command, error:
`Main: The server is expected to host the web client, but the provided content directory is either invalid or empty: /usr/lib/jellyfin/bin/jellyfin-web.`

### What is the expected _correct_ behavior?

Start jellyfin as normal. 

### Jellyfin Server version

10.10.0+

### Specify version number

10.10.2

### Specify the build version

10.10.2+noble2404

### Environment

```markdown
- OS:LM22 (Ubuntu 24.04)
- Linux Kernel: 6.8
- Virtualization: no
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration: y
- GPU Model: NV3060ti
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
logfile 0 bytes
```

### FFmpeg logs

```shell

```

**Comment by maste9** [comment]
Same here with the docker image. 

When the server updated to the new 10.10.2 image the server immediately stopped to function and couldn't be started anymore:

The only obvious failure message in the logs was that jellyfin tried to open a m3u-playlist-file but failed with insufficient privileges for its assumed path. The server exited with Code 0 after that.


Specifiying the image's version to 10.10.1 and starting the server left me with a fine working jellyfin server again.

**Comment by YaKillaCJ** [comment]
Can confirm. Did no other changes but update from 10.10.1 to 10.10.2. Getting an error about playlist being read only in logs. [FTL] [1] Main: Error while starting server

**Comment by IamDan77** [comment]
Yep same issue. Updated and now the server wont start.

Unraid docker

**Comment by miguelpedregosa** [comment]
Same issue in a LXC container

**Comment by thornbill** [comment]
It sounds like this could be a duplicate of https://github.com/jellyfin/jellyfin/issues/13048 but can’t confirm without a full error trace.

**Comment by jaykayenn** [comment]
> It sounds like this could be a duplicate of [#13048](https://github.com/jellyfin/jellyfin/issues/13048) but can’t confirm without a full error trace.

Perhaps as a dependency. But this post highlights the missing path error shown when trying to run Jellyfin 10.10.2.

**Comment by joshuaboniface** [comment]
The missing path issue is an entirely separate one from the playlists not being writable. The latter is tracked in the above issue Bill posted.

The missing path will be due to a configuration error. Can you post your `/etc/default/jellyfin`, `/lib/systemd/system/jellyfin.service`, /etc/systemd/system/jellyfin.service.d/*` and `systemctl status jellyfin` contents/outputs.

Basically somehow, the `JELLYFIN_WEB_OPT=` envvar and thus `--webdir=/usr/share/jellyfin/web` is not being set properly. This is what it *should* be for `.deb` installs; if it's anything else it's somehow wrong.

**Comment by jaykayenn** [comment]
> The missing path issue is an entirely separate one from the playlists not being writable. The latter is tracked in the above issue Bill posted.
> 
> The missing path will be due to a configuration error. Can you post your `/etc/default/jellyfin`, `/lib/systemd/system/jellyfin.service`, `/etc/systemd/system/jellyfin.service.d/*` and `systemctl status jellyfin` contents/outputs.
> 
> Basically somehow, the `JELLYFIN_WEB_OPT=` envvar and thus `--webdir=/usr/share/jellyfin/web` is not being set properly. This is what it _should_ be for `.deb` installs; if it's anything else it's somehow wrong. The `/etc/default/jellyfin` which sets this [comes from packaging and was not changed for 10.10.2](https://github.com/jellyfin/jellyfin-packaging/blob/master/debian/conf/jellyfin) (but was for unrelated things in 10.10.1).
> 
> Note as well that you _cannot_ just call `jellyfin` with `.deb` packages and expect it to work; the locations are not "the defaults" of the program under Debian; you need to source `/etc/default/jellyfin` first and then set the options (like you see in `/lib/systemd/system/jellyfin.service`) if you want to try to run it outside of systemd.

Ok, thanks for the explanation. Seems I misunderstood how Jellyfin runs. 
Unfortunately, I don't have configs/logs any more as I've restored my previous system snapshot. But from the jellyfin.service tail I posted above, it appears to match #13048 
Closing as duplicate.

**Comment by alex-veri** [comment]
Same here. Error was pointing to missing permissions to a m3u8 playlist file.

```
System.UnauthorizedAccessException: Access to the path '/mnt/nas_server/media_server/2_music/Vange Leonel/[1991] Vange/Vange Leonel - Vange.m3u8' is denied.
 ---> System.IO.IOException: Permission denied
```

To workaround it I gave the file 777 permission and restarted Jellyfin service. After that I deleted the file because I didn't need it.
