### ISSUE TITLE
Multiple version TV drama issues

### ISSUE THREAD

**Issue by homerLL** [jellyfin/jellyfin#13061]
I have two video files of the same TV drama with different voiceovers
One version is in English and the other version is in Chinese
May I ask how to name a video file so that two can be merged into one display

**Comment by TheMelmacian** [comment]
Put both video files in a separate Folder. The folder name and the first part of the video files need to be exactly the same:

```
Movie Name (2024)/
├─ Movie Name (2024) - Chinese.mkv
└─ Movie Name (2024) - English.mkv
```

see: https://jellyfin.org/docs/general/server/media/movies#multiple-versions-of-a-movie

**Comment by homerLL** [comment]
> Put both video files in a separate Folder. The folder name and the first part of the video files need to be exactly the same:将两个视频文件放在单独的文件夹中。文件夹名称和视频文件的第一部分需要完全相同：
> 
> ```
> Movie Name (2024)/
> ├─ Movie Name (2024) - Chinese.mkv
> └─ Movie Name (2024) - English.mkv
> ```
> 
> see: https://jellyfin.org/docs/general/server/media/movies#multiple-versions-of-a-movie请参阅： https://jellyfin.org/docs/general/server/media/movies#multiple-versions-of-a-movie
> 
> Episodes of TV-Shows/serials don't support auto merge and need to be merged manually.电视节目/连续剧的剧集不支持自动合并，需要手动合并。

Does it mean that TV drama recognition and merging are not supported now?

**Comment by TheMelmacian** [comment]
For episodes of shows there is PR that will add support for automatic merging of different versions: https://github.com/jellyfin/jellyfin/pull/8004

Until the feature is rolled out, you can merge them manually:
- in the web client go down to the episode level
- mark both episodes you want to merge (long click)
- open the menu in the appearing top bar and select merge items

**Comment by homerLL** [comment]
Ok, I understand. Thank you for your answer
