### ISSUE TITLE
Movie library scraping, imdb provider

### ISSUE THREAD

**Issue by patsaindon** [jellyfin/jellyfin#1307]
My movie library has 1600 movies and all movies are named this way: YEAR/Movie title/imdb_id.ext. 

Installed Jellyfin to my nas to test it. Pretty much the same as my Emby setup, except when it scanned my movie library, it did not scrape all my movies. If I go manually to to insert the imdb_id in the field to identify, it will see. Not an issue with Emby.

**Comment by anthonylavado** [comment]
Just a question - the Emby wiki doesn't seem to say this is supported... If you were to copy a few movies to a separate folder, and add it again to Emby (as a new library), does it work automatically?

Ref: https://github.com/MediaBrowser/Wiki/wiki/Movie-naming

**Comment by patsaindon** [comment]
Here is my couchpotato config.ini:
[renamer]
file_name = <imdb_id>.<ext>
from = /downloads/
to = /movies/
folder_name = <year>/<namethe>

Every new movie file downloaded use this convention and couchpotato will notify emby to scan for the new file and in minutes, the new media appears in the client.

**Comment by anthonylavado** [comment]
I think what's happening is that CouchPotato's notification actually *tells* Emby what movie the file is. I'd bet if you just added a movie on its own, without the CouchPotato notifications, it probably wouldn't identify it.

We could look at a way of identifying the movie from the filename having an ID, but I don't know how well it'll perform. We do already look at the title and folder for clues, so we'll have to see.

**Comment by patsaindon** [comment]
Did change the path of my library on my emby container and rescan my entire
library and it scrapes my movies correctly.

**Comment by patsaindon** [comment]
Finally, it's working. Just needed to be more patient.

It got through my entire library, took more time than Emby. But I got the
transcoding now.

**Comment by DrPandemic** [comment]
:wave: @patsaindon, is this issue fixed? If you consider it fixed, could we close it?
