### ISSUE TITLE
Jellyfin Metadata does not discover correctly over 999 episodes for series

### ISSUE THREAD

**Issue by D0ublek1ll** [jellyfin/jellyfin#13074]
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

When jellyfin discovers a series that has quad digit absolute episode numbers, it does not correctly match the episode's metadata to the episode number.

I found this similar issue, which is not the exact case but probably the same kind of solution could be applied here. https://github.com/jellyfin/jellyfin/issues/7656

### Reproduction steps

1. Have a serie (Anime) in jellyfin with over 1000 episodes that use absolute episode numbering and without metadata provided by a 3rd party source (Like sonarr).
2. Episodes must be numbered with quad digits (Eg: 0001, 0352, 1001, 1200, etc).
3. Let jellyfin update the show's metadata.

### What is the current _bug_ behavior?

In this usecase jellyfin discards the 4th position of the episode number and matches everything based on the first 3 positions.
For example:
- Episodes numbered 0001-0009 get the metadata for episode 0.
- Episodes numbered 0010-0019 get the metadata for episode 1.
- Etc.

### What is the expected _correct_ behavior?

Jellyfin is supposed to fetch the correct metadata for the episode number when using the absolute display order, even for episode numbers higher than 999.

### Jellyfin Server version

10.10.0+

### Specify the build version

 10.10.1

### Environment

```markdown
- OS: Debian 12
- Linux Kernel: 
- Virtualization: Qemu/KVM
- Clients: Any
- Browser: Any
- FFmpeg Version: Unrelated
- Playback Method: Unrelated
- Hardware Acceleration: Unrelated
- GPU Model: Unrelated
- Plugins: Unrelated
- Reverse Proxy: nginx
- Base URL: none
- Networking: Host/Direct
- Storage: SMB
```

### Jellyfin logs

```shell
Scowered for an hour, nothing relevant in the logs.
```

### FFmpeg logs

```shell

```

### Relevant screenshots or videos

![Image](https://github.com/user-attachments/assets/6d930c35-8490-4c06-8f3f-bede94f3673b)

**Comment by D0ublek1ll** [comment]
Example filenames:
- Pokemon - 0001 - Pokemon Choose You.mkv
- Pokemon - 0002 - Pokemon Emergency.mkv
- etc
Files located in \smb\media\Anime\Pokémon\Season 1\

I also tried this without leading zero's, the issue then only exists for episode numbers higher than 999.

**Comment by JPVenson** [comment]
Closed as resolved in chat.
Missed episode prefix: EXXSXXXX

**Comment by bzzbrr** [comment]
This is solved by using the season/episode identifier as outlined in the docs.  `Pokemon - 0001.mkv` does not work for episodes greater than 999, but `Pokemon - S01E0001.mkv` works correctly.

Using just the episode numbers with no such identifier will sometimes work but is not the intended way to name files, and in edge cases like this one will cause problems.
