### ISSUE TITLE
Subsonic Client Support

### ISSUE THREAD

**Issue by screwfaze** [jellyfin/jellyfin#1308]
**Describe the feature you'd like**
Subsonic Client support so we can use already existing apps with Jellyfin

**Additional context**

**Comment by screwfaze** [comment]
There was some discussion in Reddit about this but I do not see it here so thought I should add.

**Comment by sparky8251** [comment]
If someone wants to tackle this, this should be done in a plugin.

**Comment by screwfaze** [comment]
Please someone try and create this plugin if not too much trouble would be awesome!!!
