### ISSUE TITLE
File's default audio/subtitles track overrides preferences

### ISSUE THREAD

**Issue by carlosjfcasero** [jellyfin/jellyfin#13080]
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

When a file has a default audio/subtitles track, the audio language preference is ignored (therefore you have to manually change audio/subtitles of every single movie/episode of a show if you want to watch it in a different language).
"Set audio track based on previous item" and "Set subtitle track based on previous item" options don't work either.

### Reproduction steps

1. File has "A" default audio track
2. File has "B" default subtitles 
3. Preferred audio language is set to "C" globally in user preferences
4. Preferred subtitles language is set to "D" globally in user preferences

### What is the current _bug_ behavior?

File is reproduced with audio "A" and subtitles "B" ignoring both user preferences and "Set audio track based on previous item" and "Set subtitle track based on previous item" options.

### What is the expected _correct_ behavior?

File is reproduced with audio "C" and subtitles "D" adjusting to user preferences or based on previous item

### Jellyfin Server version

10.10.0+

### Specify the build version

10.10.3

### Environment

```markdown
- OS:
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
NA
```

### FFmpeg logs

```shell

```

**Comment by felix920506** [comment]
working as intended
