### ISSUE TITLE
Make pagination of libraries in the web UI optional/configurable

### ISSUE THREAD

**Issue by ryanwalder** [jellyfin/jellyfin#1311]
I dislike pagination when browsing libraries in the web ui and would very much like to be able to disable it (or configure something like max per page).

Obviously this could cause long load times/lag on huge libraries so it should be either configurable or handled gracefully. Plex does this very nicely for a point of reference.

**Comment by anthonylavado** [comment]
It's not the nicest named (I like your title more), but we've got this at #1237.

**Comment by ryanwalder** [comment]
Ah, I searched for pagination but was in the wrong repo! Cheers.

**Comment by anthonylavado** [comment]
It was here first, I only just moved it. No worries! :-)
