### ISSUE TITLE
Cannot mount a volume with the path "/jellyfin" in a Docker Container

### ISSUE THREAD

**Issue by TroubleDog54** [jellyfin/jellyfin#13115]
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

I recently migrated my Jellyfin installation from a Debian bare-metal install to a Docker container, following [the example from the documentation.](https://jellyfin.org/docs/general/administration/migrate#using-docker-compose-yaml) After creating a `docker-compose.yml` file with the volume `/jellyfin:/jellyfin`, the container fails to start with the following error message:

```
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/jellyfin/jellyfin": stat /jellyfin/jellyfin: no such file or directory: unknown
```

I have found a workaround by creating a volume for each directory in `/jellyfin`. My current setup looks like this:
```
jellyfin:
  image: jellyfin/jellyfn
  ...
  volumes:
    - type: bind
      source: /jellyfin/Movies
      target: /jellyfin/Movies
      read_only: false
    - type: bind
      source: /jellyfin/Shows
      target: /jellyfin/Shows
      read_only: false
```

### Reproduction steps

1. Create an entry in `/etc/fstab` to mount a drive in the `/jellyfin` directory
2. Launch a non-docker instance of Jellyfin[^1] and setup a library in the `/jellyfin` directory
3. Shut down the non-docker instance
4. Create a `docker-compose.yml` file with the following content:
```services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 107:114
    network_mode: 'host'
    restart: 'unless-stopped'
    environment:
      - JELLYFIN_CACHE_DIR=/var/cache/jellyfin
      - JELLYFIN_CONFIG_DIR=/etc/jellyfin
      - JELLYFIN_DATA_DIR=/var/lib/jellyfin
      - JELLYFIN_LOG_DIR=/var/log/jellyfin
    volumes:
      - /etc/jellyfin:/etc/jellyfin
      - /var/cache/jellyfin:/var/cache/jellyfin
      - /var/lib/jellyfin:/var/lib/jellyfin
      - /var/log/jellyfin:/var/log/jellyfin
      - /jellyfin:/jellyfin
```
5. Run `docker compose up`
6. Notice the error

[^1]: I'm unsure if this is needed for the bug to reproduce (I haven't tested installing Docker from the get-go), but I thought I'd include it anyway.

### What is the current _bug_ behavior?

The Docker container fails to start with an error:
```
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/jellyfin/jellyfin": stat /jellyfin/jellyfin: no such file or directory: unknown
```

### What is the expected _correct_ behavior?

The Docker container starts normally and the volume is passed through.[^2]

[^2]: I've just started with Docker today, I apologise for not using the correct terminology.

### Jellyfin Server version

10.10.0+

### Specify the build version

10.10.3

### Environment

```markdown
- OS: Debian 12 Bookworm
- Linux Kernel: 6.1.0-28-amd64
- Virtualization: Docker (Docker Engine)
- Clients:
- Browser:
- FFmpeg Version: 7.0.2-Jellyfin
- Playback Method:
- Hardware Acceleration: None
- GPU Model:
- Plugins: Kodi Sync Queue, OpenSubtitles, OMDb, TMDb, Studio Images, MusicBrainz, AudioDB
- Reverse Proxy:
- Base URL:
- Networking:
- Storage: Local external hard drive mounted at `/jellyfin`
```

### Jellyfin logs

```shell
admin@compaq-server:~/docker/jellyfin$ docker compose up -d
[+] Running 8/8
 ✔ jellyfin Pulled                                                                                                            75.6s 
   ✔ 2d429b9e73a6 Pull complete                                                                                               17.7s 
   ✔ 4f4fb700ef54 Pull complete                                                                                               18.0s 
   ✔ d3c5a9eb63bf Pull complete                                                                                               53.9s 
   ✔ 0c3ecb9b5c34 Pull complete                                                                                               60.3s 
   ✔ e493bb265d44 Pull complete                                                                                               61.2s 
   ✔ a8dfec6b522d Pull complete                                                                                               67.8s 
   ✔ 1d310ab153a0 Pull complete                                                                                               70.8s 
[+] Running 0/1
 ⠙ Container jellyfin  Starting                                                                                                8.1s 
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/jellyfin/jellyfin": stat /jellyfin/jellyfin: no such file or directory: unknown
admin@compaq-server:~/docker/jellyfin$
```

### FFmpeg logs

```shell

```

**Comment by gnattu** [comment]
The path you want to mount overrides the Jellyfin install path in the container which is not supported

**Comment by felix920506** [comment]
Closing, reason described in above comment
