### ISSUE TITLE
Copyright prevention measures

### ISSUE THREAD

**Issue by Scrub000** [jellyfin/jellyfin#13112]
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

Hello Jellyfin developers,

It has come to my attention that we have potentially illegal use-cases via third-party software such as Radarr, Sonarr, Prowlarr, and so fourth.

What measures are being taken to attempt to block end-users from violating copyright protections?

Thanks,
A concerned citizen.

### Reproduction steps

---

### What is the current _bug_ behavior?

---

### What is the expected _correct_ behavior?

---

### Jellyfin Server version

10.10.0+

### Specify the build version

*

### Environment

```markdown
*
```

### Jellyfin logs

```shell
*
```

### FFmpeg logs

```shell

```

**Comment by joshuaboniface** [comment]
What other software people run or what they do with it is none of concern nor business.

**Comment by gnattu** [comment]
We strictly prohibit the discussion of tools that is commonly used for piracy within our community and are enforcing our community guidelines seriously. However, as an open-source project and in accordance with the terms of the GPL license, we are unable to prevent users from utilizing such tools independently. Statements such as “you cannot use our server with those tools” are incompatible with the GPL, and we are not held liable for any illegal activities as described by the term in GPL license:

> This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

We don't promote copyright infringement behaviors. And this is all we can do.
