### ISSUE TITLE
Administrators Can Always Delete Collections

### ISSUE THREAD

**Issue by JPKribs** [jellyfin/jellyfin#13148]
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

This is either a permission issue or a visual issues. I don't have a huge opinion on which one but I just wanted to report this.

If the user is an Administrator, they can delete Collections even if they don't have Collection deletion permissions granted here:

![Image](https://github.com/user-attachments/assets/499378e4-840a-440a-9872-c46eaf26ffa1)

### Reproduction steps

1. Create or use an Administrator Account
2. Remove 'Delete' > 'Collections' permissions
3. Attempt to delete a Collection
4. Succeed!

### What is the current _bug_ behavior?

Either the UI shouldn't disallow Administrators from deleting collections (Likely a Web change) since they always can or the Deletion block on Collections should prevent deletion even for administrators.

### What is the expected _correct_ behavior?

I don't have a big opinion. Ya'll are way better sources for this than I am but I would think either:

1. Administrators always have Collections checked in Deletion
2. Block Administrators from deleting Collections if Collections is not checked in Deletion
3. Administrators don't have the option to enable/disable Collections in Deletion since Administrators always have this right

I'm impartial to 2 but I would also guess that is a huge amount of work. Mostly, I just wanted this issue for 'UI should match permission reality.'

### Jellyfin Server version

10.10.0+

### Specify version number

10.10.3

### Specify the build version

10.10.3

### Environment

```markdown
- OS: Debian (Docker)
- Linux Kernel: Linux 6.1.0-27-amd64
- Virtualization: Docker - Official Jellyfin Image
- Clients: Jellyfin-Web 10.10.3 & Swiftfin (Main)
- Browser: Safari, Firefox, Chrome, iPhone
- FFmpeg Version: N/A
- Playback Method: N/A
- Hardware Acceleration: N/A
- GPU Model: N/A
- Plugins: N/A
- Reverse Proxy: N/A
- Base URL: N/A
- Networking: N/A
- Storage: N/A
```

### Jellyfin logs

```shell
N/A
```

### FFmpeg logs

```shell
N/A
```

### Client / Browser logs

N/A

### Relevant screenshots or videos

![Permissions](https://github.com/user-attachments/assets/499378e4-840a-440a-9872-c46eaf26ffa1)
![Delete Still Available](https://github.com/user-attachments/assets/4c368949-026e-4e12-a415-404c7e9ea426)

### Additional information

This is really a super low priority. Collections make sense that an Administrator can delete them it's more just, the permission for DeleteFromFolder should either disallow Collections since it doesn't impact permission to delete OR the folder permissions should actually prevent deletion.

IMO, the latter is better but that sounds like way more overhead to resolve.

Lemme know if this is a UI bug where Collections shouldn't exist in the Folders and I can open up an issue over there!

**Comment by Shadowghost** [comment]
Admins always have full permission on anything. That's why it's an Admin.

**Comment by JPKribs** [comment]
I see what's going on now. An Admin can always delete a collection even the userPolicy.enableContentDeletion doesn't include Collections. If I include Collections to userPolicy.enableContentDeletion for a non-Admin, it doesn't actually enable deleting anything.

The issue is Collections shouldn't be an option for userPolicy.enableContentDeletion on the UI since it doesn't actually change anything since that is handled at the Admin/Non-Admin level.
