### ISSUE TITLE
Trickplay images for HDR content not tonemapped properly

### ISSUE THREAD

**Issue by guiweber** [jellyfin/jellyfin#13142]
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

Trickplay images for HDR content look unsaturated/gray compared to how it is supposed to look. 

### Reproduction steps

1. Enable Trickplay on the server
2. Add an HDR movie to your library
3. Wait for the trickplay images to be extracted
4. Using Jellyfin Media Player, play the movie comparing the video image to the trickplay image at various locations

### What is the current _bug_ behavior?

Trickplay images for HDR content look unsaturated/gray compared to how it is supposed to look. 

### What is the expected _correct_ behavior?

Trickplay images for HDR content should be tonemapped to look similar to the actual video file.

### Jellyfin Server version

10.10.0+

### Specify the build version

10.10.3

### Environment

```markdown
- OS: TrueNas
- Virtualization: Docker
- Clients: Jellyfin Media Player
- Browser: Firefox
- FFmpeg Version: ?
- Playback Method: Native
- Hardware Acceleration: VAAPI
- GPU Model: Ryzen 9000 integrated GPU
- Enable hardware decoding: On
- Enable hardware accelerated MJPEG encoding: On
```

### Jellyfin logs

```shell
N/A
```

### FFmpeg logs

```shell

```

### Relevant screenshots or videos

![Image](https://github.com/user-attachments/assets/11fc974b-7d62-49d6-9c8b-36f5b367a109)

![Image](https://github.com/user-attachments/assets/76543515-4681-4fb5-a433-84176e7f6f8e)

**Comment by gnattu** [comment]
You need to enable tonemap in the transcoding settings.

**Comment by guiweber** [comment]
@gnattu Indeed, thanks! It would be great if this was communicated to the user somehow (or at least put in the documentation), I don't think it's mentioned anywhere that transcoding options affect trickplay image generation.
