### ISSUE TITLE
vaapi transcode 10bit hevc is garbled

### ISSUE THREAD

**Issue by scurrvy2020** [jellyfin/jellyfin#1315]
**Describe the bug**
When using VAAPI transcode of a 10bit HEVC file the video is green and garbled. 

**To Reproduce**
1. Turn on VAAPI transcode
2. Play a 10bit HEVC video file
3. observe garbled video

**Expected behavior**
Clear video.  I think the 10bit is not being correct translated to an 8bit h.264 file. 

**Logs**
no errors received. 

**System (please complete the following information):**
 - OS:Docker Jellyfin v10.2.2
 - Browser: chromium
 - Jellyfin Version: 10.2.2
 - Reverse proxy: apache

**Comment by EraYaN** [comment]
This might be a hardware problem, please provide what hardware you are running. Not everything supports HEVC 10-bit properly.

**Comment by oddstr13** [comment]
Green and garbled sounds like my first encounter with Hi10P many years ago - before installing appropriate codecs.

Your GPU/drivers does probably not support 10bit HEVC decoding.

**Comment by k1lln1n3** [comment]
I'm seeing the same behavior with AMD and Intel drivers. I'm not sure its the output but lets see what we can find.

>Clear video. I think the 10bit is not being correct translated to an 8bit h.264 file.

Can you grab the ffmpeg commend outputted when you see it? we might need to specify `-pix_fmt yuv420p` or something. Ill try to test this as well to see if it can fix the problem.
