### ISSUE TITLE
“China Broadcasting Network” is unable to connect

### ISSUE THREAD

**Issue by DylanLLLLLLL** [jellyfin/jellyfin#13156]
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

I have several SIM cards in my phone(iOS18), including China Unicom and China Mobile, both of which can connect to my NAS. However, the SIM card from China Broadcasting Network (CBN) cannot connect. My CBN SIM card works fine for regular internet access, but the Jellyfin app cannot connect to the NAS. I have also tried using a mobile hotspot, but any connection through CBN's network fails to connect to my NAS. I contacted CBN customer service, and they informed me that Jellyfin has not yet opened access for CBN's network, as CBN is a newly established company.

### Reproduction steps

Normal operation, but after changing the sim card, the nas cannot be connected.

### What is the current _bug_ behavior?

Unable to connect to nas

### What is the expected _correct_ behavior?

normal connection

### Jellyfin Server version

10.10.0+

### Specify the build version

can not find，just a light user

### Environment

```markdown
- OS:
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
can not find，just a light user
```

### FFmpeg logs

```shell

```

**Comment by felix920506** [comment]
How dis you set up remote access?

**Comment by felix920506** [comment]
Please head to our forums or chat rooms for troubleshooting 
https://jellyfin.org/contact
