### ISSUE TITLE
jellyfin adapt emby applications

### ISSUE THREAD

**Issue by leopkks** [jellyfin/jellyfin#1317]
add script /scripts/apploader.js
add script /manifest.json
add script /strings/
index.php

by adding these scripts below
emby applications
playstore among others back
to work
it is possible to adapt these settings

to jellyfin
to work
the applications

when you add these codes
applications pick up again
to emby
playstore , ios

**Comment by leopkks** [comment]
and only download the official script
copy the above scripts
and make the adaptation
to run the applications

add script /scripts/apploader.js
add script /manifest.json
add script /strings/
index.php

**Comment by leopkks** [comment]
I'm waiting, thanks from now on
community thanks
and me too XD

**Comment by sparky8251** [comment]
We will not be fighting Emby to unblock ourselves from their app. The plan you laid out here is non-trivial and Emby will immediately push a new update that's even harder to bypass.

There is no winning this for us.
