### ISSUE TITLE
Automated Restart Crashes Server

### ISSUE THREAD

**Issue by djohnson1865** [jellyfin/jellyfin#1320]
**Describe the bug**
The Server Occasionally automatically restarts and does not come back. A restart of the systemd service fixes the problem. 

**To Reproduce**
1. Install Jellyfin from Ubuntu (or Debian) repository
2. Let run for a period
3. On idle Service will have attempted to restart and be stopped

**Expected behavior**
Service should continue running after restart.

**Logs**
```
[2019-04-27 11:30:41.728 +00:00] [INF] App needs to be restarted.
[2019-04-27 11:30:41.731 +00:00] [INF] "Check for plugin updates" Completed after 0 minute(s) and 1 seconds
[2019-04-27 11:30:41.774 +00:00] [INF] ExecuteQueuedTasks
[2019-04-27 11:45:41.749 +00:00] [INF] Automatically restarting the system because it is idle and a restart is required.
[2019-04-27 11:45:41.751 +00:00] [INF] Calling RestartInternal
[2019-04-27 11:45:41.753 +00:00] [INF] Disposing "CoreAppHost"
[2019-04-27 11:45:41.754 +00:00] [INF] Disposing "ActivityLogWebSocketListener"
[2019-04-27 11:45:41.755 +00:00] [INF] Disposing "SessionInfoWebSocketListener"
[2019-04-27 11:45:41.757 +00:00] [INF] Disposing "ScheduledTasksWebSocketListener"
[2019-04-27 11:45:41.757 +00:00] [INF] Disposing "SessionWebSocketListener"
[2019-04-27 11:45:41.758 +00:00] [INF] Disposing "EmbyTV"
[2019-04-27 11:45:41.758 +00:00] [INF] Disposing "ApiEntryPoint"
[2019-04-27 11:45:41.759 +00:00] [INF] Disposing "ServerEntryPoint"
[2019-04-27 11:45:41.759 +00:00] [INF] Disposing "EntryPoint"
[2019-04-27 11:45:41.759 +00:00] [INF] Disposing "DeviceAccessEntryPoint"
[2019-04-27 11:45:41.759 +00:00] [INF] Disposing "LibraryMonitorStartup"
[2019-04-27 11:45:41.759 +00:00] [INF] Disposing "AutomaticRestartEntryPoint"
[2019-04-27 11:45:41.760 +00:00] [INF] Disposing "ExternalPortForwarding"
[2019-04-27 11:45:41.761 +00:00] [INF] Disposing "LibraryChangedNotifier"
[2019-04-27 11:45:41.763 +00:00] [INF] Disposing "RecordingNotifier"
[2019-04-27 11:45:41.764 +00:00] [INF] Disposing "ServerEventNotifier"
[2019-04-27 11:45:41.767 +00:00] [INF] Disposing "StartupWizard"
[2019-04-27 11:45:41.767 +00:00] [INF] Disposing "UdpServerEntryPoint"
[2019-04-27 11:45:41.767 +00:00] [INF] Disposing "UserDataChangeNotifier"
[2019-04-27 11:45:41.768 +00:00] [INF] Disposing "DeviceManagerEntryPoint"
[2019-04-27 11:45:41.768 +00:00] [INF] Disposing "CollectionManagerEntryPoint"
[2019-04-27 11:45:41.768 +00:00] [INF] Disposing "ActivityLogEntryPoint"
[2019-04-27 11:45:41.771 +00:00] [INF] Disposing "DlnaEntryPoint"
[2019-04-27 11:45:41.772 +00:00] [INF] Disposing SsdpDevicePublisher
[2019-04-27 11:45:41.884 +00:00] [INF] Disposing PlayToManager
[2019-04-27 11:45:41.886 +00:00] [INF] Disposing DeviceDiscovery
[2019-04-27 11:45:41.890 +00:00] [INF] Disposing SsdpCommunicationsServer
[2019-04-27 11:45:41.892 +00:00] [INF] "SsdpCommunicationsServer" disposing _BroadcastListenSocket
[2019-04-27 11:45:41.896 +00:00] [INF] "SsdpCommunicationsServer" Disposing 2 sendSockets
[2019-04-27 11:45:41.896 +00:00] [INF] "SsdpCommunicationsServer" disposing sendSocket from "0.0.0.0"
[2019-04-27 11:45:41.896 +00:00] [INF] "SsdpCommunicationsServer" disposing sendSocket from "10.0.0.x"
[2019-04-27 11:45:41.897 +00:00] [INF] Disposing "Notifications"
[2019-04-27 11:45:41.900 +00:00] [INF] Disposing "EntryPoint"
[2019-04-27 11:45:41.904 +00:00] [INF] Starting new instance
[2019-04-27 11:45:41.906 +00:00] [INF] Executable: "/usr/lib/jellyfin/restart.sh"
[2019-04-27 11:45:41.906 +00:00] [INF] Arguments: "--restartpath=/usr/lib/jellyfin/restart.sh --ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg  "
 ```

**System (please complete the following information):**
 - OS: Ubuntu 18.04 (LXD container)
 - Kernel: 4.19.0-2-amd64
 - Browser: All
 - Jellyfin Version: 10.0.3.1
 - Reverse proxy: nginx

**Additional context**

Jellyfin is installed in an LXD container on a Debian 9 hypervisor. Also it has had the data directory restored from an older version of Jellyfin (10.2.1)

**Comment by MindrustUK** [comment]
Seeing the same behaviour:

- Dist: Ubuntu 18.04.2 LTS
- Kernel: 4.15.0-48-generic
- Browser: All
- Jellyfin Version: 10.0.3.1

Additional:
Jellyfin installed in a Linux KVM machine running on Proxmox VE.

**Comment by anthonylavado** [comment]
Yes, the automated restart script is a very bad hack that we know about. It will have to be revised at some point

cc @joshuaboniface

**Comment by djohnson1865** [comment]
I am not convinced that the restart script is the issue. The script is identical in 10.0.3.1 and 10.0.2.1, but the behavior is not seen in 10.0.2.1. I think it may be something else within the restart logic, though I am not super familiar with the codebase, so I can't posit as to what the issue may be.

**Comment by sxldier** [comment]
Does anything happen when you execute the restart script manually? 

I experienced the same issue on my CentOS installation.
I checked the file executed (/usr/libexec/jellyfin/restart.sh) and it was using `at`, which wasn't installed. 
I had to install it and start/enable the service, `atq`.

**Comment by djohnson1865** [comment]
Running the restart.sh script manually restarts as expected. It is running in an Ubuntu 18.04 container, which has `at` installed by default. So that is not an issue here.

**Comment by djohnson1865** [comment]
Although pressing restart via the dashboard produces the same behavior as the automated restart. Which leads me to a problem in the internal restart logic. Not the script itself, hacky as it may be.

**Comment by utiltiy** [comment]
I have the same problerms. My watchdog grep every minute the ps aux from jellyfin, if the prozess is down follows a restart.
My crash.log with restart's:
`Restarting jellyfin:     Fr 14. Jun 00:28:01 CEST 2019
Restarting jellyfin:     Fr 14. Jun 01:14:01 CEST 2019
Restarting jellyfin:     Fr 14. Jun 02:00:01 CEST 2019
Restarting jellyfin:     Fr 14. Jun 05:01:01 CEST 2019
Restarting jellyfin:     Fr 14. Jun 05:47:01 CEST 2019
Restarting jellyfin:     Fr 14. Jun 06:33:01 CEST 2019
Restarting jellyfin:     Fr 14. Jun 08:49:01 CEST 2019
Restarting jellyfin:     Fr 14. Jun 11:05:01 CEST 2019
Restarting jellyfin:     Fr 14. Jun 12:51:01 CEST 2019
Restarting jellyfin:     Fr 14. Jun 15:07:01 CEST 2019
Restarting jellyfin:     Fr 14. Jun 15:53:01 CEST 2019
Restarting jellyfin:     Fr 14. Jun 16:39:01 CEST 2019
Restarting jellyfin:     Fr 14. Jun 18:55:01 CEST 2019
Restarting jellyfin:     Fr 14. Jun 20:26:01 CEST 2019
Restarting jellyfin:     Sa 15. Jun 00:12:01 CEST 2019
Restarting jellyfin:     Sa 15. Jun 04:43:01 CEST 2019
Restarting jellyfin:     Sa 15. Jun 05:29:01 CEST 2019
Restarting jellyfin:     Sa 15. Jun 06:15:01 CEST 2019
Restarting jellyfin:     Sa 15. Jun 07:01:01 CEST 2019
Restarting jellyfin:     Sa 15. Jun 07:47:01 CEST 2019
Restarting jellyfin:     Sa 15. Jun 08:33:01 CEST 2019
Restarting jellyfin:     Sa 15. Jun 09:19:01 CEST 2019
Restarting jellyfin:     Sa 15. Jun 10:50:01 CEST 2019
Restarting jellyfin:     Sa 15. Jun 11:36:01 CEST 2019
Restarting jellyfin:     Sa 15. Jun 12:22:01 CEST 2019
Restarting jellyfin:     Sa 15. Jun 13:53:01 CEST 2019
Restarting jellyfin:     Sa 15. Jun 14:39:01 CEST 2019
Restarting jellyfin:     Sa 15. Jun 15:25:01 CEST 2019
Restarting jellyfin:     Sa 15. Jun 16:56:01 CEST 2019
Restarting jellyfin:     Sa 15. Jun 17:42:01 CEST 2019
Restarting jellyfin:     Sa 15. Jun 18:28:01 CEST 2019
Restarting jellyfin:     Sa 15. Jun 19:14:01 CEST 2019
Restarting jellyfin:     Sa 15. Jun 22:30:01 CEST 2019
Restarting jellyfin:     Sa 15. Jun 23:16:01 CEST 2019
Restarting jellyfin:     So 16. Jun 00:47:01 CEST 2019
Restarting jellyfin:     So 16. Jun 01:33:01 CEST 2019
Restarting jellyfin:     So 16. Jun 03:26:01 CEST 2019
Restarting jellyfin:     So 16. Jun 07:12:01 CEST 2019
Restarting jellyfin:     So 16. Jun 08:43:01 CEST 2019
Restarting jellyfin:     So 16. Jun 09:29:01 CEST 2019
Restarting jellyfin:     So 16. Jun 11:00:01 CEST 2019
Restarting jellyfin:     So 16. Jun 12:46:01 CEST 2019
Restarting jellyfin:     So 16. Jun 14:17:01 CEST 2019
Restarting jellyfin:     So 16. Jun 15:48:01 CEST 2019
Restarting jellyfin:     So 16. Jun 17:19:02 CEST 2019
Restarting jellyfin:     So 16. Jun 18:05:01 CEST 2019
Restarting jellyfin:     So 16. Jun 20:06:01 CEST 2019
Restarting jellyfin:     So 16. Jun 21:07:01 CEST 2019
Restarting jellyfin:     So 16. Jun 22:38:01 CEST 2019
Restarting jellyfin:     So 16. Jun 23:39:01 CEST 2019
Restarting jellyfin:     Mo 17. Jun 00:25:01 CEST 2019
Restarting jellyfin:     Mo 17. Jun 01:11:01 CEST 2019
Restarting jellyfin:     Mo 17. Jun 04:12:01 CEST 2019
Restarting jellyfin:     Mo 17. Jun 04:58:01 CEST 2019
Restarting jellyfin:     Mo 17. Jun 05:44:01 CEST 2019
Restarting jellyfin:     Mo 17. Jun 06:30:01 CEST 2019
Restarting jellyfin:     Mo 17. Jun 07:16:01 CEST 2019
Restarting jellyfin:     Mo 17. Jun 08:02:01 CEST 2019
Restarting jellyfin:     Mo 17. Jun 09:33:01 CEST 2019
Restarting jellyfin:     Mo 17. Jun 10:19:01 CEST 2019
Restarting jellyfin:     Mo 17. Jun 11:05:01 CEST 2019
Restarting jellyfin:     Mo 17. Jun 11:51:01 CEST 2019
Restarting jellyfin:     Mo 17. Jun 12:37:01 CEST 2019
Restarting jellyfin:     Mo 17. Jun 13:23:01 CEST 2019
Restarting jellyfin:     Mo 17. Jun 15:39:01 CEST 2019
Restarting jellyfin:     Mo 17. Jun 16:40:01 CEST 2019
Restarting jellyfin:     Mo 17. Jun 19:41:01 CEST 2019
Restarting jellyfin:     Mo 17. Jun 20:27:01 CEST 2019
Restarting jellyfin:     Mo 17. Jun 21:58:01 CEST 2019
Restarting jellyfin:     Mo 17. Jun 22:44:01 CEST 2019
Restarting jellyfin:     Mo 17. Jun 23:30:01 CEST 2019`

**Comment by hoffleit** [comment]
I guess the problem is that that script /usr/lib/jellyfin/restart.sh will be called as user jellyfin, who has not the necessary privileges to run systemctl nor service (nor /etc/init.d/jellyfin). So all the methods to start the server will fail.

My workaround on a Debian system was to include this line in /etc/sudoers:

`jellyfin ALL=NOPASSWD: /bin/systemctl restart jellyfin`

and to replace /usr/lib/jellyfin/restart.sh with this:

```
#!/bin/bash
sudo systemctl restart jellyfin
```

**Comment by joshuaboniface** [comment]
That's interesting - the Debian package contains a sudoers entry that allows that script to run systemctl, and it already has a sudo command in it. What platform are you on?

From my experience (and I do experience this too), it's able to execute the "restart" command, but the server never starts back up, only shuts down. To be honest this entire thing is a gross hack and we should really work on a proper in-app restart functionality, but that's its own can of worms.

**Comment by utiltiy** [comment]
The /etc/sudoers.d file "jellyfin-sudoers" was changed here: https://github.com/jellyfin/jellyfin/commit/f0e74c2c6b3fa8c94f0da222cde20a6b173db0b0

Is that the problem?

**Comment by joshuaboniface** [comment]
Shouldn't be, that's the commit that made it actually work. Specifically, the `sudo` is [here](https://github.com/jellyfin/jellyfin/commit/f0e74c2c6b3fa8c94f0da222cde20a6b173db0b0#diff-3a0761ee2fd9bc21be6bab2ecdb27f25R17) and that sudoers config should allow the jellyfin user to execute any of those commands.

As mentioned, it does work for me, but about 1/3 of the time, the "systemctl restart jellyfin" shuts down the process and that's it, it just hangs and never starts back up.

Maybe it's time to reinvestigate this script for 10.4.0.

**Comment by utiltiy** [comment]
The diffrent systems to start / stop / restart can be this a problem? Here, i use debian buster with systemd and i have these problems before i use my "watchdog" to restart jellyfin if the prozess is gone.

**Comment by oddstr13** [comment]
Is there not a way to tell systemd to restart thr process if it exits? And then just shut down Jellyfin and expect systemd to handle the restart?

**Comment by joshuaboniface** [comment]
@oddstr13 There is, but then we'd have to have consistent exit codes :confused: 

However, I did write a better `restart.sh` that, at least from my testing right now, is working perfectly every time with the existing packaged `/etc/sudoers.d/jellyfin-sudoers` rules. If you want to give it a shot and confirm it works for you guys too, we can get it into the next release (10.3.6).

```
#!/bin/bash

get_service_command() {
    for command in systemctl service; do
        if which $command &>/dev/null; then
            echo $command && return
        fi
    done
    echo "sysv"
}

cmd="$( get_service_command )"
echo "Using system control command '$cmd' to restart Jellyfin..."                                                                                                                                                                              
case $cmd in
    'systemctl')
        echo "sleep 2; /usr/bin/sudo /usr/bin/systemctl restart jellyfin" | at now 
        ;;
    'service')
        echo "sleep 2; /usr/bin/sudo /sbin/service jellyfin restart" | at now 
        ;;
    'sysv')
        echo "sleep 2; /usr/bin/sudo /etc/init.d/jellyfin restart" | at now 
        ;;
esac
exit 0
```

Functionally it seems like it's the same as the other one, but without the funky logic, however for whatever reason this one is working consistently.

**Comment by djohnson1865** [comment]
@joshuaboniface The updated script did not seem to help with my borked install (I have kept an older version around without the issues for the time being). A fresh install works fine without any libraries set up, but if I add my media Libraries the restart behavior crops up again. The new script does not seem to affect the issue one way or the other. However, the logic is much more human-readable, so I might suggest incorporating it into 10.3.6 anyways.

**Comment by djohnson1865** [comment]
Oh, FYI, systemctl is not at /usr/bin/systemctl in Debian or Ubuntu. My installs have it at /bin/systemctl.

**Comment by djohnson1865** [comment]
@joshuaboniface So after some more testing, the new script works (when I modify the full path) when directly invoked from the command line, but not when called via the restart button within the dashboard. In addition, the restart button works on a fresh install with no libraries, but once libraries are added (or at least my libraries) the behavior crops up again, though works occasionally. Also,  I thought something like this might be a little more portable. Kind of hacky, but it should work. Does not fix my restart issues from jellyfin, but works when directly invoked.
```
#!/bin/bash

get_service_command() {
    for command in systemctl service; do
        if which $command &>/dev/null; then
            echo $command && return
        fi
    done
    echo "sysv"
}

cmd="$(get_service_command)"
cmd_path="$( /usr/bin/which $cmd)"

echo "Using system control command '$cmd' to restart Jellyfin..."                                                                 
case $cmd in
    'systemctl')
        echo "sleep 2; /usr/bin/sudo $cmd_path restart jellyfin" | at now
        ;;
    'service')
        echo "sleep 2; /usr/bin/sudo $cmd_path jellyfin restart" | at now
        ;;
    'sysv')
        echo  "sleep 2; /usr/bin/sudo /etc/init.d/jellyfin restart" | at now
        ;;
esac
exit 0
```

**Comment by utiltiy** [comment]
I replace the old script with the new on, i hope my watchdog must not work ;)

**Comment by djohnson1865** [comment]
Definitely does not entirely fix the problem, just had an automated restart kill the server with the new script.

**Comment by utiltiy** [comment]
Yes, the problem is present again:

Restarting jellyfin:     Do 27. Jun 21:37:01 CEST 2019
Restarting jellyfin:     Do 27. Jun 23:53:01 CEST 2019
Restarting jellyfin:     Fr 28. Jun 00:39:01 CEST 2019
Restarting jellyfin:     Fr 28. Jun 01:25:01 CEST 2019
Restarting jellyfin:     Fr 28. Jun 02:11:01 CEST 2019
Restarting jellyfin:     Fr 28. Jun 03:42:01 CEST 2019
Restarting jellyfin:     Fr 28. Jun 08:13:01 CEST 2019
Restarting jellyfin:     Fr 28. Jun 10:29:01 CEST 2019

**Comment by joshuaboniface** [comment]
@djohnson1865 Good suggestion with the whole "which" thing, but I think that's actually the exact source of the problem - the sudoers is only configured for `/usr/bin/systemctl` right now, and of course the path seems to matter there. Let me do some more experimenting with the sudoers config, maybe we can eliminate that by using a no-path version (e.g. just `systemctl` instead of `/usr/bin/systemctl`).

**Comment by joshuaboniface** [comment]
Wait, nevermind, that's already handled:

```
  5 Cmnd_Alias RESTARTSERVER_SYSTEMD = /usr/bin/systemctl restart jellyfin, /bin/systemctl restart jellyfin
  6 Cmnd_Alias STARTSERVER_SYSTEMD = /usr/bin/systemctl start jellyfin, /bin/systemctl start jellyfin
  7 Cmnd_Alias STOPSERVER_SYSTEMD = /usr/bin/systemctl stop jellyfin, /bin/systemctl stop jellyfin
```
And sudoers does not like pathless binary entries.

As to why it's failing inside Jellyfin, it's *probably* a sudoers-related issue. The paths have to match exactly. `at` should be sending an email to the account that called it (i.e. `jellyfin`) so if you can view that it will show the exact error, and it displays some of it in a full `journalctl -f` output.

**Comment by djohnson1865** [comment]
Well, mail isn't set up on this system as I am running jellyfin in an LXD container. But You are correct, it is sudoers related.

```
Jun 28 00:48:24 new-jellyfin sudo[2408]: pam_unix(sudo:auth): conversation failed
Jun 28 00:48:24 new-jellyfin sudo[2408]: pam_unix(sudo:auth): auth could not identify password for [jellyfin]
Jun 28 00:48:24 new-jellyfin sudo[2408]: jellyfin : command not allowed ; TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/bin/systemctl restart jellyfin
Jun 28 00:48:24 new-jellyfin atd[2405]: pam_unix(atd:sesssion): session closed for user jellyfin
```

**Comment by djohnson1865** [comment]
@joshuaboniface What is the rate of automated restart? Is there a way to modify it locally? The issue seems to be more consistent with the automatic restarts, the button through the UI only fails intermittently. Would be nice not to need to wait around for the server to fail when debugging.

**Comment by utiltiy** [comment]
I modify the sudoers and my restart lock so:

`jellyfin ALL=NOPASSWD: /bin/systemctl restart jellyfin`

`Jun 29 08:04:44 jellyfin sudo[25268]: jellyfin : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/systemctl restart jellyfin
`

**Comment by djohnson1865** [comment]
> Well, mail isn't set up on this system as I am running jellyfin in an LXD container. But You are correct, it is sudoers related.
> 
> ```
> Jun 28 00:48:24 new-jellyfin sudo[2408]: pam_unix(sudo:auth): conversation failed
> Jun 28 00:48:24 new-jellyfin sudo[2408]: pam_unix(sudo:auth): auth could not identify password for [jellyfin]
> Jun 28 00:48:24 new-jellyfin sudo[2408]: jellyfin : command not allowed ; TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/bin/systemctl restart jellyfin
> Jun 28 00:48:24 new-jellyfin atd[2405]: pam_unix(atd:sesssion): session closed for user jellyfin
> ```

I think this was actually a red herring. After looking at the journalctl results from an automated restart, still not starting from the restart, but no apparent error messages or errors of any kind that I can tell at the time. After this log the jellyfin service is dead and there are not entries from pam, sudo, or atd which indicate the `at` command was ever called.

```
Jun 29 04:49:56 new-jellyfin jellyfin[7868]: [04:49:56] [INF] Automatically restarting the system because it is idle and a restart is required.
Jun 29 04:49:56 new-jellyfin jellyfin[7868]: [04:49:56] [INF] Calling RestartInternal
Jun 29 04:49:56 new-jellyfin jellyfin[7868]: [04:49:56] [INF] Disposing CoreAppHost
Jun 29 04:49:56 new-jellyfin jellyfin[7868]: [04:49:56] [INF] Disposing ActivityLogWebSocketListener
Jun 29 04:49:56 new-jellyfin jellyfin[7868]: [04:49:56] [INF] Disposing SessionInfoWebSocketListener
Jun 29 04:49:56 new-jellyfin jellyfin[7868]: [04:49:56] [INF] Disposing ScheduledTasksWebSocketListener
Jun 29 04:49:56 new-jellyfin jellyfin[7868]: [04:49:56] [INF] Disposing SessionWebSocketListener
Jun 29 04:49:56 new-jellyfin jellyfin[7868]: [04:49:56] [INF] Disposing EmbyTV
Jun 29 04:49:56 new-jellyfin jellyfin[7868]: [04:49:56] [INF] Disposing ApiEntryPoint
Jun 29 04:49:56 new-jellyfin jellyfin[7868]: [04:49:56] [INF] Disposing ServerEntryPoint
Jun 29 04:49:56 new-jellyfin jellyfin[7868]: [04:49:56] [INF] Disposing EntryPoint
Jun 29 04:49:56 new-jellyfin jellyfin[7868]: [04:49:56] [INF] Disposing DeviceAccessEntryPoint
Jun 29 04:49:56 new-jellyfin jellyfin[7868]: [04:49:56] [INF] Disposing LibraryMonitorStartup
Jun 29 04:49:56 new-jellyfin jellyfin[7868]: [04:49:56] [INF] Disposing AutomaticRestartEntryPoint
Jun 29 04:49:56 new-jellyfin jellyfin[7868]: [04:49:56] [INF] Disposing ExternalPortForwarding
Jun 29 04:49:56 new-jellyfin jellyfin[7868]: [04:49:56] [INF] Disposing LibraryChangedNotifier
Jun 29 04:49:56 new-jellyfin jellyfin[7868]: [04:49:56] [INF] Disposing RecordingNotifier
Jun 29 04:49:56 new-jellyfin jellyfin[7868]: [04:49:56] [INF] Disposing ServerEventNotifier
Jun 29 04:49:56 new-jellyfin jellyfin[7868]: [04:49:56] [INF] Disposing StartupWizard
Jun 29 04:49:56 new-jellyfin jellyfin[7868]: [04:49:56] [INF] Disposing UdpServerEntryPoint
Jun 29 04:49:56 new-jellyfin jellyfin[7868]: [04:49:56] [INF] Disposing UserDataChangeNotifier
Jun 29 04:49:56 new-jellyfin jellyfin[7868]: [04:49:56] [INF] Disposing DeviceManagerEntryPoint
Jun 29 04:49:56 new-jellyfin jellyfin[7868]: [04:49:56] [INF] Disposing CollectionManagerEntryPoint
Jun 29 04:49:56 new-jellyfin jellyfin[7868]: [04:49:56] [INF] Disposing ActivityLogEntryPoint
Jun 29 04:49:56 new-jellyfin jellyfin[7868]: [04:49:56] [INF] Disposing DlnaEntryPoint
Jun 29 04:49:56 new-jellyfin jellyfin[7868]: [04:49:56] [INF] Disposing SsdpDevicePublisher
Jun 29 04:49:56 new-jellyfin jellyfin[7868]: [04:49:56] [INF] Disposing PlayToManager
Jun 29 04:49:56 new-jellyfin jellyfin[7868]: [04:49:56] [INF] Disposing DeviceDiscovery
Jun 29 04:49:56 new-jellyfin jellyfin[7868]: [04:49:56] [INF] Disposing SsdpCommunicationsServer
Jun 29 04:49:56 new-jellyfin jellyfin[7868]: [04:49:56] [INF] SsdpCommunicationsServer disposing _BroadcastListenSocket
Jun 29 04:49:56 new-jellyfin jellyfin[7868]: [04:49:56] [INF] SsdpCommunicationsServer Disposing 2 sendSockets
Jun 29 04:49:56 new-jellyfin jellyfin[7868]: [04:49:56] [INF] SsdpCommunicationsServer disposing sendSocket from 0.0.0.0
Jun 29 04:49:56 new-jellyfin jellyfin[7868]: [04:49:56] [INF] SsdpCommunicationsServer disposing sendSocket from 10.X.X.X
Jun 29 04:49:56 new-jellyfin jellyfin[7868]: [04:49:56] [INF] Disposing Notifications
Jun 29 04:49:56 new-jellyfin jellyfin[7868]: [04:49:56] [INF] Disposing EntryPoint
Jun 29 04:49:56 new-jellyfin jellyfin[7868]: [04:49:56] [INF] Starting new instance
Jun 29 04:49:56 new-jellyfin jellyfin[7868]: [04:49:56] [INF] Executable: /usr/lib/jellyfin/restart.sh
Jun 29 04:49:56 new-jellyfin jellyfin[7868]: [04:49:56] [INF] Arguments: --restartpath=/usr/lib/jellyfin/restart.sh --ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg
Jun 29 04:49:56 new-jellyfin jellyfin[7868]: Using system control command 'systemctl' to restart Jellyfin...
```

**Comment by djohnson1865** [comment]
@utiltiy The default sudoers file for jellyfin has entries which should be semantically equivalent to what you posted. Has that modification solved the problem for you with restarts? When they succeed on my system the journal output is equivalent for me, but they are still not consistently working.

**Comment by utiltiy** [comment]
The problem is with the changes not solved, but a little bit better while jellyfin can now execute restarts. Before was it a problem with the right's for the user jellyfin / sudo and path to the system files. The entries in my watchdog log are fewer ;)

**Comment by djohnson1865** [comment]
@joshuaboniface Just for reference, I modified the restart script to just run "systemctl restart jellyfin" in order to rule out any strange race conditions or anything in the script being called and jellyfin itself, and the automated restarts still often fail, which tells me that something about the internal restart logic of the underlying infrastructure may be the problem. I had glanced at the code, but am not extremely versed in .NET development so didn't go mucking about too much to try to debug.

**Comment by kevin201** [comment]
> > I modify the sudoers and my restart look so:
> > `jellyfin ALL=NOPASSWD: /bin/systemctl restart jellyfin`
> > `Jun 29 08:04:44 jellyfin sudo[25268]: jellyfin : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/systemctl restart jellyfin `
> 
> @utiltiy The default sudoers file for jellyfin has entries which should be semantically equivalent to what you posted. Has that modification solved the problem for you with restarts? When they succeed on my system the journal output is equivalent for me, but they are still not consistently working.

I know this was a long time ago now, but I've just spent much too long with the same problem, only to find that the 

`#includedir /etc/sudoers.d/`

line was actually missing from the /etc/sudoers file.

As soon as I added that, the

`$ sudo -U jellyfin -l
User jellyfin is not allowed to run sudo on [machine]`

changed to 

`$ sudo -U jellyfin -l
Matching Defaults entries for jellyfin on [machine]:
    env_reset, mail_badpass,
    secure_path=/usr/local/sbin\:/usr/local/bin\:/usr/sbin\:/usr/bin\:/sbin\:/bin\:/snap/bin, !requiretty

Runas and Command-specific defaults for jellyfin:
    Defaults!/sbin/service jellyfin restart, /usr/sbin/service jellyfin restart !requiretty
    Defaults!/sbin/service jellyfin start, /usr/sbin/service jellyfin start !requiretty
    Defaults!/sbin/service jellyfin stop, /usr/sbin/service jellyfin stop !requiretty
    Defaults!/usr/bin/systemctl restart jellyfin, /bin/systemctl restart jellyfin !requiretty
    Defaults!/usr/bin/systemctl start jellyfin, /bin/systemctl start jellyfin !requiretty
    Defaults!/usr/bin/systemctl stop jellyfin, /bin/systemctl stop jellyfin !requiretty
    Defaults!/etc/init.d/jellyfin restart !requiretty
    Defaults!/etc/init.d/jellyfin start !requiretty
    Defaults!/etc/init.d/jellyfin stop !requiretty

User jellyfin may run the following commands on hp-nas:
    (ALL : ALL) NOPASSWD: ALL
    (ALL) NOPASSWD: /sbin/service jellyfin restart, /usr/sbin/service jellyfin restart
    (ALL) NOPASSWD: /sbin/service jellyfin start, /usr/sbin/service jellyfin start
    (ALL) NOPASSWD: /sbin/service jellyfin stop, /usr/sbin/service jellyfin stop
    (ALL) NOPASSWD: /usr/bin/systemctl restart jellyfin, /bin/systemctl restart jellyfin
    (ALL) NOPASSWD: /usr/bin/systemctl start jellyfin, /bin/systemctl start jellyfin
    (ALL) NOPASSWD: /usr/bin/systemctl stop jellyfin, /bin/systemctl stop jellyfin
    (ALL) NOPASSWD: /etc/init.d/jellyfin restart
    (ALL) NOPASSWD: /etc/init.d/jellyfin start
    (ALL) NOPASSWD: /etc/init.d/jellyfin stop
    (ALL) NOPASSWD: /bin/mount
    (ALL) NOPASSWD: /bin/umount
`

Putting this here on the off-chance that it might help someone else making the same error!
