### ISSUE TITLE
Jellyfin + Samsung TV App Brightness Issue

### ISSUE THREAD

**Issue by deten** [jellyfin/jellyfin#1323]
Ocassionally I have an issue where a show playing shuffle will sometimes become "Dark".  I have checked to make sure its not a TV setting and it is not.  This problem started up about 2-4 weeks ago (that I noticed).

The fix for it is oddly emby specific.  By force closing the app and playing the episode/show again it will be fine.  It usually does not happen if I play one show right off, but it will if I put it on shuffle or play all.

Samsung TV: UN65KS8000
Samsung Emby App Version: 1.0.53 (I stopped updating and Jellyfin works fine with this version).
Jellyfin Version: 10.3.1

Thanks!

**Comment by deten** [comment]
I just checked Watchtower and it looks like the last times Jellyfin Updated was 4/22/19, then 4/19/19 and before that 3/15/19.

I feel like it hasn't been going on THAT long (3/15) but not THAT short (4/22).

**Comment by anthonylavado** [comment]
Is it HDR content by chance?

**Comment by deten** [comment]
> Is it HDR content by chance?

I am confident it is not.

**Comment by deten** [comment]
Seems to have resolved itself when Jellyfin updated recently.
