### ISSUE TITLE
Comics do not have cover

### ISSUE THREAD

**Issue by JillianTo** [jellyfin/jellyfin#13243]
**Describe The Bug**
When adding a new comic book or refreshing the image metadata for an existing one, it will not add the cover as a primary image. The format I am using is cbz, which worked in 10.9. 

**Steps To Reproduce**
1. Create a media library with the 'Books' content type. Choose directory of cbz files
2. Scan library or refresh metadata with 'Replace all metadata' and 'Replace existing images' selected

**Expected Behavior**
The first image in the cbz should be set as the primary image for the comic. 

**Logs**
No related errors seen in log

**Screenshots**
Old issues scanned in an older version still have their cover, but a new issue scanned in the current version does not have a cover. When refreshing the metadata for a comic that has a cover in the current version, it will remove its cover. 
![Image](https://github.com/user-attachments/assets/294c6ffb-fb3d-416d-85c4-4e54bac3f376)

**System (please complete the following information):**
 - Platform: Fedora Linux 40
 - Browser: Firefox
 - Jellyfin Version: 10.10.2

**Additional Context**
#6287

**Comment by felix920506** [comment]
After rescanning the entire library and waiting for it to finish, does the cover show up if you refresh the entire page?

**Comment by JillianTo** [comment]
I did a 'Scan for new and updated files' and 'Search for missing metadata' without the replace options checked on my whole library and it did not change anything. I tried creating a new library pointing to the same directory, and it has all the same covers my original comics library has, but still does not have covers for newly added issues.
