### ISSUE TITLE
Unable to disable local artwork/posters

### ISSUE THREAD

**Issue by neofright** [jellyfin/jellyfin#13256]
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

I can't find any way of disabling local artwork in JellyFin. I have a bunch of jpegs in the same folder as my movies and they are showing up instead of the scraped posters.

I don't want to move, delete, or change their permissions as recommended [here](https://forum.jellyfin.org/t-completely-disable-external-posters).

Is there any way to disable this feature completely?

### Reproduction steps

.

### What is the current _bug_ behavior?

.

### What is the expected _correct_ behavior?

Local posters are disabled.

### Jellyfin Server version

10.10.0+

### Specify the build version

10.10.3

### Environment

```markdown
- OS: Linux
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
.
```

### FFmpeg logs

```shell

```

**Comment by felix920506** [comment]
Please head to our forum or chat rooms for general questions. https://jellyfin.org/contact
