### ISSUE TITLE
Entire Folder Ignored when a Single Video File is present in the root

### ISSUE THREAD

**Issue by tuaris** [jellyfin/jellyfin#13266]
**Describe The Bug**
You have a folder with other folders and video's within each folder.  Jellyfin will display each folder and it's corresponding video's correctly.  However, once you add a single video file in that 'root' folder, the other sub folders and corresponding video's will no longer be browseable.

**Steps To Reproduce**

1. Create a root folder
2. Add sub folders
3. Add video's to the sub folders
4. Add one video to the root folder
5. Add the root folder to Jellyfin
6. Only the video file at the root of the folder is visible.  

**Expected Behavior**
All sub folders and video's should be visible.  If I have the "Display a folder view to show plain media folders", I should see all my sub folders.

**System (please complete the following information):**
 - Platform: FreeBSD
 - Browser: Firefox
 - Jellyfin Version: 10.10.3

**Additional Context**
This behavior occurs regardless of whether you have the "Display a folder view to show plain media folders" option enabled.  For added context, Emby has corrected this problem in a recent release.

**Comment by A-Star100** [comment]
I am having a similar issue, my root folder contains subfolders with separate videos inside them, but my setup doesn't have a video in the root folder. Jellyfin randomly misses a lot of these videos (some, not all), especially ones in nested subfolders and I can't see them in the web UI, no matter how many times I rescan or rename the videos.

**System:**

Platform: macOS (ARM)
Browser: Chrome
Jellyfin Version: 10.10.3

**Comment by felix920506** [comment]
please head to our forum or chat rooms for troubleshooting. https://jellyfin.org/contact
