### ISSUE TITLE
Authenticate error when new login with finamp app anf it as already accessed to the server

### ISSUE THREAD

**Issue by proline** [jellyfin/jellyfin#13267]
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

Hello,

I am using finamp, and due to a bug I nedded to install a previous version.
When I tried to login I got this error from the application : finamp could not fetch the response for post .... authenticate by name status code 403 error processing request.
On the server in devices I removed the the app try to log ans it works.
For me it looks like a problem from the jellyfin server.
I think I already had this problem with the jellyfin app too

### Reproduction steps

1 install finamp
2 log in
3 remove finamp
4 reinstall finamp
5 try to login

### What is the current _bug_ behavior?

Login forbidden

### What is the expected _correct_ behavior?

If I reinstall the app I should login again without remove the client from the server

### Jellyfin Server version

10.10.0+

### Specify the build version

10.10.3

### Environment

```markdown
- OS: debian 12
- Linux Kernel: 6.1.0-28-amd64
- Virtualization:
- Clients: finamp
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
[ERR] Error processing request: "[ip address] User is at their maximum number of sessions". URL "POST" "/Users/AuthenticateByName".
```

### FFmpeg logs

```shell

```

**Comment by felix920506** [comment]
Please report the issue to Finamp.

**Comment by proline** [comment]
I don't understand? For me it is the server that refuse the connection for bad reasons.

**Comment by felix920506** [comment]
403 is an issue on the client side.

**Comment by nielsvanvelzen** [comment]
The server is rejecting the login because you have a maximum amount of sessions configured for the user
