### ISSUE TITLE
TVHeadend Plugin: Avoid Unnecessary Transcoding for x264 Streams

### ISSUE THREAD

**Issue by ShahinNasseri** [jellyfin/jellyfin#13261]
Hi,

I’m using Jellyfin with the TVHeadend plugin to stream live TV channels. The server is configured to serve the video as x264, which can be played directly in a browser without requiring any transcoding.

However, I noticed that Jellyfin is transcoding the x264 video before serving it to the browser, even though this step shouldn’t be necessary.

Could you guide me on how to configure Jellyfin to avoid unnecessary transcoding in this scenario? Is there a specific setting or a known issue with the TVHeadend plugin that might cause this behavior?

I’d appreciate any advice or documentation references that could help me resolve this.

Thank you!

**Comment by gnattu** [comment]
LiveTV sources from TVHeadend has extra compatibility issues that would need transcoding due to audio/video out of sync issues with browsers.

**Comment by ShahinNasseri** [comment]
> LiveTV sources from TVHeadend has extra compatibility issues that would need transcoding due to audio/video out of sync issues with browsers.

Thank you for the explanation regarding the compatibility issues and the need for transcoding to handle audio/video sync issues with browsers.

However, I’m experiencing a significant delay when starting a channel. It takes approximately 8 seconds for the initialization and playback to begin. This feels unusually long, especially for switching between live TV channels.

Is there any way to optimize or reduce this delay? Are there settings or configurations, either in Jellyfin or the TVHeadend plugin, that can help speed up the initialization process?

Any guidance on how to address this would be greatly appreciated.

**Comment by felix920506** [comment]
Working as intended. There is no real way around the problem you are having.
