### ISSUE TITLE
pins not working after 10.3.1.0 upgrade

### ISSUE THREAD

**Issue by brianjmurrell** [jellyfin/jellyfin#1326]
**Describe the bug**
PINs are not allowing login after upgrade from 10.2.1 to 10.3.1

**To Reproduce**

1. Upgrade to 10.3.1
2. Try to log in with a previously working PIN

**Expected behavior**
I should be able to log in

**Logs**
```
[2019-04-29 15:47:36.125 -04:00] [ERR] Error authenticating with provider "Default"
System.Exception: Invalid username or password
   at Emby.Server.Implementations.Library.DefaultAuthenticationProvider.Authentica>
   at Emby.Server.Implementations.Library.UserManager.AuthenticateWithProvider(IAu>
[2019-04-29 15:47:36.146 -04:00] [INF] Authentication request for "Brian" "has bee>
[2019-04-29 15:47:36.152 -04:00] [ERR] Invalid user or password entered.
```
 - OS: Fedora 29
 - Browser: Chrome
 - Jellyfin Version: 10.3.1
 - Reverse proxy: None

**Additional context**
An existing logged in user still works but any attempt to log in any other user by either password or PIN fails.

To pile on, the "forgot my password" process is completely broken and/or completely un-intelligible.  I am redirected to a webpage:

![image](https://user-images.githubusercontent.com/559317/56923112-c0dfa900-6a97-11e9-925b-6b83c5367bd3.png)

where the link in the above screenshot leads to:

![image](https://user-images.githubusercontent.com/559317/56923161-db198700-6a97-11e9-812f-5569369eb6c8.png)

and `/var/lib/jellyfin/passwordreset4.json` contains:

```json
{"Pin":"AA-BB-CC-DD","UserName":"General","PinFile":"/var/lib/jellyfin/passwordreset4.json","ExpirationDate":"2019-04-29T16:28:58.6643187-04:00"}
```

I have no idea what I am supposed to do with this.  Guessing at putting that PIN into the input box and clicking the `${ButtonSubmit}` button does nothing.

I am basically completely locked out of my Jellyfin system with no clear path as to how to remedy this.

**Comment by anthonylavado** [comment]
_From Matrix chat_ (ty @bugfixin)

https://github.com/jellyfin/jellyfin/commit/bef665be364ce1477d09ed268f68c19e0099922f#diff-0cad5db83844b175e1fe7dd334e0e705

>^ broke here, particularly hasConfiguredEasyPassword
>how much trouble a missing ! can cause :P

**Comment by anthonylavado** [comment]
#1333 should at least allow pin users to login with their password, have not tested with the pin just yet

**Comment by anthonylavado** [comment]
Also the password reset page thing (#1076) was fixed by https://github.com/jellyfin/jellyfin-web/pull/229, but that wasn't in the release. We've backported it as https://github.com/jellyfin/jellyfin-web/pull/296.

**Comment by DrPandemic** [comment]
If no one tried to tackle the password upgrade issues by this weekend, I'll give it a try.

**Comment by DrPandemic** [comment]
https://github.com/jellyfin/jellyfin/pull/1372 should fix this issue
