### ISSUE TITLE
screen-grabber cannot generate thumbnails in libraries using remote shares

### ISSUE THREAD

**Issue by Samg381** [jellyfin/jellyfin#13283]
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

I have a Jellyfin 10.10.3 instance (bare metal, not docker) running on a Debian 12 machine on my home network. The instance is configured with the following media libraries:

1. A local library on the Debian machine itself.
2. A NFS share from a Synology NAS also on the LAN.
3. A SMB share from a Windows host also on the LAN.

I am able to see and play media files in each share, so that aspect is working well. My issue is with **thumbnail generation.**

My preference is to generate thumbnails instead of fetching from movie databases. As such, I have enabled **only** the 'screen grabber' on all three media libraries, and adjusted it's priority to the top. I have also disabled 'realtime monitoring' on the remote libraries based on my research on this isssue.

Despite this, **screen-grabber thumbnails are not generated for the remote libraries**. Thumbnails **are** generated for the local library, however.

### Reproduction steps

1. Install Jellyfin on a bare-metal linux client.
2. On a different host within the same LAN, configure either an SMB or NFS share with some sample videos.
3. On the Jellyfin machine, mount the share in `/mnt/` or a directory of your choosing.
4. Sign into Jellyfin using an admin account.
5. Within the admin dashboard, and beneath Libraries, click `Add Media Library`
6. Configure a new media library and select the newly mounted share as the source folder.
7. For both `Image fetchers (Movies)` and `Image fetchers (Shows)` deselect every checkbox except for `screen grabber`, and move it to the top.
8. Click OK, and click `Scan All Libraries`.
9. Wait some time (in my case several days) and check if thumbnails have appeared.

### What is the current _bug_ behavior?

Screen-grabber thumbnails do not appear for media files within libraries utilizing remote shares.

### What is the expected _correct_ behavior?

Screen-grabber thumbnails should appear for media files within libraries utilizing remote shares.

### Jellyfin Server version

10.10.0+

### Specify the build version

10.10.13

### Environment

```markdown
- OS: Debian 12
- Linux Kernel: 6.1.0-17-amd64
- Virtualization: None. Jellyfin installed bare metal.
- Clients: Browser
- Browser: Firefox 133.0
- FFmpeg Version: jellyfin-ffmpeg7
- Playback Method: Direct play, transcode
- Hardware Acceleration: none
- GPU Model: none
- Plugins: none
- Reverse Proxy: none
- Base URL: none
- Networking: Host
- Storage: local, NFS, SMB
```

### Jellyfin logs

```shell
Attached below.
```

### FFmpeg logs

```shell
Attached below.
```

### Additional information

[jellyfin.txt](https://github.com/user-attachments/files/18246653/jellyfin.txt)
[ffmpeg.txt](https://github.com/user-attachments/files/18246654/ffmpeg.txt)

**Comment by Samg381** [comment]
**Update:** I completely re-installed Jellyfin, and re-created the libraries from the remote shares. Interestingly, this time, many of the thumbnails within the remote shares _were_ generated. 

That said, about 10% of the thumbnails still refused to generate.. however there is no commonality surrounding the share being remote/local, so I suspect this is now an encoding issue, or something more specific to ffmpeg. Attached are some new ffmpeg errors for the remaining thumbnails that won't generate.

[jellyfin-log-new-ffmpeg-errors.txt](https://github.com/user-attachments/files/18246986/jellyfin-log-new-ffmpeg-errors.txt)

**Comment by gnattu** [comment]
Either your CPU or the connection to the remote files are too slow to generate the thumbnails in time which makes jellyfin thinks the generation is hanging and just killed FFmpeg process. 

You can edit the `system.xml` and add `ImageExtractionTimeoutMs` to be a very huge value like 10 minutes.

If it is due to having a weak CPU you can try https://github.com/jellyfin/jellyfin/pull/12744 first to see if that make things better.

**Comment by Samg381** [comment]
That seemed to improve things, thanks. Still a few failures, but less this time. I will close this for now. If #12744 doesn't fix it, I will re-open.
