### ISSUE TITLE
WALL·E (WALL-E) movie is detected as "Walls Have Ears"

### ISSUE THREAD

**Issue by erkexzcx** [jellyfin/jellyfin#13284]
Hello. I am using Jellyfin `10.10.3` (docker, from linuxserver) and it works great. I just noticed that one movie is missing in my library, while it should be - **WALL·E**:

https://www.themoviedb.org/movie/10681-wall-e

However, it is being matched as `Walls Have Ears` movie:

https://www.themoviedb.org/movie/906359-sciany-maja-uszy

Here is how my path looks like:

```bash
# Movies library added as /media/Movies
/media/Movies/WALL·E (2008)/movie.mkv
```

The actual movie behind `Walls Have Ears` is an actual WALL·E movie, just Jellyfin doesn't recognize it properly.

I confirm that all other movies (that I checked) are detected properly and working great, except this one movie. Maybe a special character is an issue here? It's part of the name after all. https://www.themoviedb.org/movie/10681-wall-e 🤔

**Workaround**

Edit movie's identity in Jellyfin, and specify proper TMDB ID and Jellyfin now shows it properly.

**Comment by felix920506** [comment]
This isn't really something we can fix without breaking lots of other setups. The best way would be to specify a Tmdb or IMDb id.
