### ISSUE TITLE
Jellyfin audio track selection

### ISSUE THREAD

**Issue by Siscos06** [jellyfin/jellyfin#13295]
I’ve been using Jellyfin’s app for AppleTV for quite a while and even though is incredibly useful, there’s something it’s been driving me crazy.

The problem I have is that I’ve got different video versions which I want to play in my Apple TV. However since there’s no way to choose between the available tracks I’m unable to watch my media in whichever language I want.

The feature I’m requesting is basically something similar to the web browser, where you can choose from a dropdown menu the audio track you want to use.

**Comment by felix920506** [comment]
Please file your issue in this repo using the provided issue template. https://github.com/jellyfin/Swiftfin
