### ISSUE TITLE
Shows always prefer pulling episode metadata from TMDB, even if a TVDB ID is specified in the folder name

### ISSUE THREAD

**Issue by K4rakara** [jellyfin/jellyfin#13294]
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

If you specify a TVDB ID in the name of a folder, it is _not_ preferred for sourcing metadata for episodes- it instead unconditionally prefers TMDB. This is problematic in one particular case- When including special features for a show in the "Season 00" folder, as these two sources tend to disagree on the ordering/numbering of the "episodes" that make up the specials.

### Reproduction steps

1. Create a folder for a series that you know has different ordering of its specials on TVDB vs TMDB. For this example, I'll use Over the Garden Wall, so the folder should be named "Over the Garden Wall (2014) [tvdbid-281643]".
2. Create a "Season 00" folder within the series folder.
3. Place two files in the "Season 00" folder, "Over the Garden Wall S00E01 Tome of the Unknown.mkv" and "Over the Garden Wall S00E05 Behind Over the Garden Wall.mkv". These file names correspond to the TVDB ordering of the special episodes. I believe empty Matroska files will work for the sake of the example, but correct me if I am wrong.
4. Rescan the library that the series folder is a part of.

### What is the current _bug_ behavior?

In this case, "Tome of the Unknown" will have the correct metadata, as [both](https://thetvdb.com/series/over-the-garden-wall/episodes/5004838) [databases](https://www.themoviedb.org/tv/61617-over-the-garden-wall/season/0) agree on the episode numbering for this special in particular- but "Behind Over the Garden Wall" will have the metadata of "Behind the Scenes: 10th Anniversary Stop Motion Short", as the [episode numbering for "Behind Over the Garden Wall" on TVDB](https://thetvdb.com/series/over-the-garden-wall/episodes/6317379) corresponds to the [episode numbering for "Behind the Scenes: 10th Anniversary Stop Motion Short" on TMDB](https://www.themoviedb.org/tv/61617-over-the-garden-wall/season/0/episode/5).

As a workaround, users can temporarily number their specials using the TMDB ordering for "episodes". This won't break as long as you don't refresh metadata for the specials or change their filenames.

### What is the expected _correct_ behavior?

I think it would be fairly reasonable for at least "Season 00" to be pulled from the database specified by the series folder, to prevent confusion from users who are titling their specials folders using the TVDB numbering.

### Jellyfin Server version

10.10.0+

### Specify the build version

10.10.3

### Environment

```markdown
- OS: Ubuntu 24.04 LTS
- Linux Kernel: 6.8.0-49-generic
- Virtualization: Docker
- Clients: Browser
- Browser: Firefox
- FFmpeg Version: 7.0.2-Jellyfin
- Playback Method: Transcode
- Hardware Acceleration: None
- GPU Model: None
- Plugins: None
- Reverse Proxy: Nginx
- Base URL: None
- Networking: Bridge
- Storage: Cloud via rclone
```

### Jellyfin logs

```shell
n/a afaik? paging through the logs in admin doesn't appear to have anything relevant- at least not for this particular series. If there's a specific part in the `log_$timestamp.log` files that I'm missing, or a different log that I should be looking at entirely, let me know and I'll be happy to provide.
```

### FFmpeg logs

```shell

```

**Comment by K4rakara** [comment]
Apologies for the double title edit, it is late and I am tired 😅

**Comment by felix920506** [comment]
The order in which metadata providers are used is configurable in the settings for each library. The ID is only used for identification purposes and does not have any effect on the order or metadata providers used. 

Closing as this is working as intended.

**Comment by durantkiurs-code** [comment]
i have a similar issue with my anime folder. i set TMDB to be last in the order because my files are named using the season order. unfortunately for whatever reason many titles on tmdb ignore season order and stuff every episode into season 1 leading to jellyfin reading anything past season 1 as the raw file names. i went so far as to remove tmdb as a metadata source in every category for the library and the issue persists is this intentional? am i meant to manually configure each episode with the correct metadata, or upload each season as a separate show on tmdb myself?

**Comment by KintsugiUwU** [comment]
[durantkiurs-code](https://github.com/durantkiurs-code) 
I had to disable TMDB, then force a new metadata scan on the desired tv show, then lock that specific show metadata, and reenable TMDB. All this becuase there's not a setting in the tv show setting to prefer tm or tvdb

Working as intended yes, but if one release got metadata correctly on tv and wrong on tm, and tm is set as primary then you either do the workaround i mentioned, live with a wrong metadata or create a separate library with different preferences. Definitely not user friendly [felix920506](https://github.com/felix920506), all we ask is a simple setting to prefer tv or tm per tv show, we already have the option to choose the ordering
