### ISSUE TITLE
Docker: https port mapping missing from avaiable port - no host

### ISSUE THREAD

**Issue by antipiot** [jellyfin/jellyfin#1331]
**Is your feature request related to a problem? Please describe.**
No.
**Describe the solution you'd like**
Actually, docker configuration does not allow to map https port to internal network

I can actually map only the http port wich is working fin but i would like to be able to use custom https port without using "host" network configuration

**Describe alternatives you've considered**
tried custom port mapping to internal https port with a certificate but it doesen't work.
Is there a way to edit port configuration before?

**Comment by napcae** [comment]
Can you please describe your issue with more details and how to reproduce?

**Comment by antipiot** [comment]
Hello!

I cant use https on my jellyfin container:

Certificate setted up and is good but i can't access https port even when network is setted up as "host"

**Comment by napcae** [comment]
I already got that, please show me the commands you are using and screenshots of your config.

**Comment by antipiot** [comment]
Hello!

My bad: Everything working fine: Cert had bad rights: doing a chmod on it and everything started to work.
Sorry about that :-(
