### ISSUE TITLE
Remove EXPOSE from dockerfile

### ISSUE THREAD

**Issue by advancedslicedbanana** [jellyfin/jellyfin#1339]
**Describe the bug**
Even if user has selected different server port in config file, dockerfile will always expose 8096. 

**Expected behavior**
Dockerfile should not expose ports.

**Additional context**
This is especially problematic when attempting to deploy two instances of Jellyfin on one system using Docker.

**Comment by IBlackI** [comment]
Not an issue, see [Dockerfile](https://docs.docker.com/engine/reference/builder/#expose) reference.
The EXPOSE instruction does not actually publish the port. It functions as a type of documentation between the person who builds the image and the person who runs the container, about which ports are intended to be published.
