### ISSUE TITLE
Allow Custom Chapter Image Intervall

### ISSUE THREAD

**Issue by DeveloperOl** [jellyfin/jellyfin#1346]
I would love to set a custom time Intervall for the chapter image extractor.

The default of 5 min is too long in my opinion and I would love to set it to something around 10-30 secs (No worries about server load or disk space).

A simple field to edit that interval in the library would be very helpful.

**Comment by ninnghazad** [comment]
https://github.com/jellyfin/jellyfin/blob/64b6cfa3dc4c2eab8d0caf6a3506e9cb40ff5025/MediaBrowser.Providers/MediaInfo/FFProbeVideoInfo.cs#L548

**Comment by negulici-r-barnabas** [comment]
@DeveloperOl Hey, I've implemented it on my end. I created the pull requests. They still have to be reviewed and approved by the Jellyfin people.
