### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by Nosirus** [jellyfin/jellyfin#1348]
I notice that Jellyfin consumes much more memory than emby, in idle emby consume ~ 143Mib and ~ 1.4Gib for Jellyfin after 24h

After restarting the docker, Jellyfin 287Mib and 127Mib for emby

 - OS: Docker
 - Jellyfin Version: 10.3.2

**Comment by barolo** [comment]
I've noticed that too, upon start it consumes around 55 MB [ non docker version ] even after browsing and playing, then it slowly creeps into GBs

**Comment by barolo** [comment]
It takes approx 24h with two kodi clients and non-docker build to reach 1GB from 55 MB

**Comment by EraYaN** [comment]
Frankly this is probably due to the fact that there is enough RAM, Java can behave in the same way. It should reduce (garbage collect) it's RAM when something else asks for it. If this does not happen then there is a problem.
