### ISSUE TITLE
No resolution options when casting

### ISSUE THREAD

**Issue by n00bhax** [jellyfin/jellyfin#1349]
My chromecast (v3) isn't fast enough to receive 1080p content. My server is kinda shitty, but pc's and phones can handle the video's just fine. I would like to solve this by turning the resolution down when I'm watching on my chromecast, but there isn't an option to do this on the remote app/site.

**Comment by anthonylavado** [comment]
Further discussion is happening here: https://www.reddit.com/r/jellyfin/comments/bldvt7/buffering_when_casting_to_chromecast/
