### ISSUE TITLE
When deleting list the old channels still remains active. new version

### ISSUE THREAD

**Issue by leopkks** [jellyfin/jellyfin#1351]
When adding list of IPTV m3u8
the channels normally appear

however when deleting the list or updates it the old channels continues old the images only appears new channel added
it is not possible to delete the channels from the list
you have to erase the whole database
or access the script folders and find where the data is
to be deleted manually
because the new m3u8 added is not replacing the old list.

**Comment by fruhnow** [comment]
Have you tried clicking the "Refresh Guide" on the Admin -> Live-TV -> Live-TV Page after deleting the M3U-Tuner? IIRC you have to do that to get corresponding channels removed after deleting a tuner.

**Comment by leopkks** [comment]
I use docker remove list
I did this, but the old images are not disappearing.

**Comment by fruhnow** [comment]
Im quite unsure what you are trying to archieve with the docker cli command over here. I guess you should fill the jellyfin-github-template for raising issues at best to avoid misunderstanding.

**Comment by CtrlDelJ** [comment]
This issue is still present in Jellyfin 10.11.13 and 12
