### ISSUE TITLE
Reverse order for playlists

### ISSUE THREAD

**Issue by onny** [jellyfin/jellyfin#1353]
**Describe the solution you'd like**
Reverse sort a playlist so that the newest items are on top. In case of a large playlist you don't have to scroll down if you want to listen to the newest added tracks. New tracks on top is the default order in Spotify.

Best regard,
Jonas

**Comment by onny** [comment]
Ups sorry this belongs to jellyfin-web

**Comment by ldexterldesign** [comment]
👋 https://github.com/jellyfin/jellyfin-web/issues/7019
