### ISSUE TITLE
Add Simkl Support (via Plugin)

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin#1361]
**Describe the feature you'd like**
Some users on the forum have asked if we can add a plug-in with support for Simkl. It’s a scrobbling style service for media tracking.

See:
* https://www.simkl.com
* https://forum.jellyfin.org/t/simkl-integration/329/2?u=anthonylavado

**Additional context**
The current API key I have created for Jellyfin can be provided on request - it is limited to 1000 requests/day until we submit our app for “approval”.

**Comment by masyk** [comment]
Jellyfin added https://simkl.com/apps/jellyfin/
