### ISSUE TITLE
Remove episodes from next up

### ISSUE THREAD

**Issue by jnoy** [jellyfin/jellyfin#1362]
I had a glitch with my TV episodes being correctly identified, and now for series that I have already completed are all back in my next up feed. I do not see any way to manually remove them. I would like this to be a feature.

**Comment by joshuaboniface** [comment]
The easiest way to do this is to check "Watched" (the checkmark) on the episodes/seasons/series, which manually marks them watched and should get them removed from you next up.

**Comment by jnoy** [comment]
They were already check, but clearing it and rechecking seems to work. Doing it by episodes only works one episode at a time, so I just did it by seasons and it worked. Thanks for the help.
