### ISSUE TITLE
FFMPEG transcoding error + workaround

### ISSUE THREAD

**Issue by platinum55** [jellyfin/jellyfin#1364]
**Describe the bug**
Some mkv files fail to transcode/stream because of this bug:
https://trac.ffmpeg.org/ticket/6472

Jellyfin just stalls in the loading screen because of the ffmpeg process exits with returncode 1.

I tried the workaround which is posted in the ffmpeg tracker "-max_muxing_queue_size 198" - which is working, transcode runs!

Please implement this parameter until the ffmpeg bug is fixed

**System:**
 - OS: Docker
 - Browser: Chrome
 - Jellyfin Version: 10.3.2
 - Reverse proxy: no

**Comment by johnvick** [comment]
Can you please explain how to do this? It looks like it may solve my problem. Thanks.

**Comment by platinum55** [comment]
how to do what? I requested something here

**Comment by johnvick** [comment]
How do you implement the workaround -max_muxing_queue_size 198?

I can't see any way to input these command line parameters. I'm trying to get transcoding to work but it stops with ffmpeg error 1.

**Comment by platinum55** [comment]
I dont know, thats why I asked here. You need to modify to source I guess.

**Comment by platinum55** [comment]
this bug still exists in version 10.4.0 - maybe we can just detect the error message from ffmpeg:

`Too many packets buffered for output stream 0:0.
Conversion failed!`

and then start the encode with the option "-max_muxing_queue_size 198"

**Comment by ManuLinares** [comment]
This issue is still happening. I dont know where to add  "-max_muxing_queue_size 1024"

**Comment by jeremyj** [comment]
same here

**Comment by KiraSokolov** [comment]
same problem

**Comment by cvium** [comment]
This issue has been closed for almost 2 years... Also https://github.com/jellyfin/jellyfin/pull/3976 and https://github.com/jellyfin/jellyfin-web/pull/1842
