### ISSUE TITLE
photo library not showing image with JPG uppercase extention

### ISSUE THREAD

**Issue by myB0B** [jellyfin/jellyfin#1365]
**Describe the bug**
In many folders i have images with .jpg and .JPG extention.
images with uppercase extention (.JPG) are not show

**System (please complete the following information):**
 - OS: Ubuntu 18.04.02
 - Browser: All
 - Jellyfin Version: 10.3.2
 - Reverse proxy: apache2

**Comment by agrenott** [comment]
Good spot, I have the same issue.
At first glance, I think a lower case conversion here might help: https://github.com/jellyfin/jellyfin/blob/c713824bf960b1c0d33dde051da6115f329cbca8/MediaBrowser.Model/Net/MimeTypes.cs#L135
I'll give it a try.

**Comment by anthonylavado** [comment]
@agrenott That’s interesting... this line shows the dict should be doing an OrdinalIgnoreCase comparison, so I wonder what’s happening:

https://github.com/jellyfin/jellyfin/blob/c713824bf960b1c0d33dde051da6115f329cbca8/MediaBrowser.Model/Net/MimeTypes.cs#L68

**Comment by agrenott** [comment]
That's right, not the proper place. I've started debugging yesterday, didn't find the culprit yet. But I guess it will end up in something similar.

**Comment by agrenott** [comment]
Arg, finally got it, to see it's already fixed by someone else... :)

**Comment by anthonylavado** [comment]
Fixed in 10.4, whenever that will be.
