### ISSUE TITLE
Master release schedule and procedure

### ISSUE THREAD

**Issue by joshuaboniface** [jellyfin/jellyfin#137]
Now that we have a proper `develop` branch, let's discuss how we want to handle making regular releases into master.

#### My short-term vision while we move fast to get ourselves set up

Daily or every-other-day PRs that can merge the current `develop` into master, reviewed by 2+ of us after a test suite and ensuring that the PR passes CI.

#### My long-term vision

I'd love to aim for weekly "master" releases once get most of the big things done and start to move towards stable feature releases and bugfixes. Critical bugs can have specific PRs between weeks if needed, but ideally we don't change master any more frequently than that. These PRs could be reviewed by all of us and tested fully before release.

Also, maybe it is a good idea not to push much, if anything, into `master` once we get the release frequency established, even for documentation etc.

To clarify, I don't mean fixed dates, but a general "within about a week" idea. Skipping days/weeks is fine if there's breakage, or nothing to merge.

Thoughts/feedback?

**Comment by anthonylavado** [comment]
Since we have the CI, I feel good about this. After this big sprint of a week, it would be good to get some stability, just as we get packages out.

**Comment by JustAMan** [comment]
I agree with the idea. I even say we need to move all PRs via `develop`, even docs. Maybe have a separate doc repo?

I only think we should move to weekly only after we have basic platform coverage (I'd say rpm, maybe appImage and maybe MacOS remain).

**Comment by anthonylavado** [comment]
We have defined an internal release schedule at this point.
