### ISSUE TITLE
Limit parameter is not accurate in Latest Items API call

### ISSUE THREAD

**Issue by SenorSmartyPants** [jellyfin/jellyfin#1370]
**Describe the bug**
Calling /Users/{UserId}/Items/Latest with Limit parameter, I'll get less than the limit requested when there are more than the limit available.

**To Reproduce**

Go to http://localhost:8096/emby/Users/<USERID>/Items/Latest?GroupItems=true&IncludeItemTypes=episode&Limit=27&api_key=<APIKEY>
I'll get 26 items.
If I change Limit to 28, I'll get 27 items

**Expected behavior**

Limit parameter should be respected and accurate.

**Logs**
```
> [2019-05-11 11:00:38.926 -05:00] [WRN] "GetItemList" query time (slow): 664.3891. Query: "select type,data,EndDate,ChannelId,CommunityRating,IndexNumber,Width,Height,Name,Path,PremiereDate,ParentIndexNumber,ProductionYear,OfficialRating,RunTimeTicks,Size,DateModified,guid,ParentId,Audio,IsInMixedFolder,PrimaryVersionId,Album,CriticRating,IsVirtualItem,SeriesName,SeasonName,SeasonId,SeriesId,ProviderIds,Images,TotalBitrate,ExtraType,ExternalId,OwnerId,UserDatas.UserId,UserDatas.lastPlayedDate,UserDatas.playbackPositionTicks,UserDatas.playcount,UserDatas.isFavorite,UserDatas.played,UserDatas.rating from TypedBaseItems A left join UserDatas on UserDataKey=UserDatas.Key And (UserId=@UserId) where type=@type AND (played is null or played=@IsPlayed) AND IsVirtualItem=@IsVirtualItem AND TopParentId in ('137f89d261ef16df402821f8b84955c7','912303902b5dd42ee4e9c87a7bc308e9','9440fa44dde27465f922669883e839ae','fe31d6033ceb0300897d25ffff2f7f15') Group by PresentationUniqueKey ORDER BY DateCreated DESC LIMIT 135"
> [2019-05-11 11:00:39.016 -05:00] [WRN] HTTP Response 200 to "192.168.1.250". Time (slow): 0:00:00.7890954. "http://localhost:8096/emby/Users/5c0c92019ab2454a8bdcc7aba9abcdd6/Items/Latest?GroupItems=true&IncludeItemTypes=episode&Limit=27"
```
**Screenshots**

**System (please complete the following information):**
 - OS: Docker
 - Browser: Chrome
 - Jellyfin Version: 10.3.2

**Additional context**

**Comment by fruhnow** [comment]
Ive just spun up a Postman test case and **can't confirm** this is happening. (But I'm on Version 10.3.3)

e.g for Limit=8
`pm.test("limit is respected", function() {
    pm.expect(Object.keys(pm.response.json()).length).to.eql(8);
});`

Success: 
![image](https://user-images.githubusercontent.com/6041926/58759756-75556a80-852f-11e9-91b0-5e922a0bd114.png)

Failure:
![image](https://user-images.githubusercontent.com/6041926/58759763-8dc58500-852f-11e9-9da8-540bc4ac6850.png)

**Comment by SenorSmartyPants** [comment]
I think you need a lot of (unwatched) episodes. I hide watched episodes in the latest view. More than 5 episodes per series on average for this to start happening.

**Comment by sparky8251** [comment]
Odd... Definitely going to need some digging to see why this occurs at all. There is some good news in that you can typically find the API in the source if you search for its path. That might shed light on what its stupidly doing.

**Comment by SenorSmartyPants** [comment]
no stale please

**Comment by JustAMan** [comment]
Wild guess here - JF  is probably applying your `Limit` parameter to the initial query and then it filters out some elements from it. Sounds plausible?

**Comment by SenorSmartyPants** [comment]
It seems to me that they are taking the ```Limit``` parameter and multiplying it by 5 and using that as the SQL LIMIT. This is their attempt to guess how many unwatched episodes per series in their weird GROUP BY SQL statement. 

Relevant section from my initial log
```Group by PresentationUniqueKey ORDER BY DateCreated DESC LIMIT 135```

The SQL needs a rewrite.

**Comment by felix920506** [comment]
Does this API endpoint even exist in current versions?

**Comment by felix920506** [comment]
Hi, I was unable to reproduce this issue at the API endpoint documented here. https://api.jellyfin.org/#tag/UserLibrary/operation/GetLatestMedia

**Comment by SenorSmartyPants** [comment]
> I think you need a lot of (unwatched) episodes. I hide watched episodes in the latest view. More than 5 episodes per series on average for this to start happening.

Did you have series with lots of unwatched episodes in your testing?
