### ISSUE TITLE
Record series does nothing

### ISSUE THREAD

**Issue by skug67** [jellyfin/jellyfin#1371]
**Describe the bug**
If you click the "Record series" button on a program page, nothing happens

**To Reproduce**
1. Go to any page for a current or upcoming TV series episode
2. Click on 'Record series'
3. Nothing happens

**Expected behavior**
Button should turn red and change text to allow cancelling the schedule.

**Logs**
No log entries triggered by pressing the button

**System (please complete the following information):**
 - OS: Debian Buster
 - Browser: Safari (iOS), Opera/Chrome/Firefox (Windows)
 - Jellyfin Version: 10.3.2
 - Reverse proxy: apache/ssl

**Comment by anthonylavado** [comment]
This may be closed in favour of jellyfin/jellyfin-web#338, but waiting to do some triage first.

**Comment by anthonylavado** [comment]
This is fixed in https://github.com/jellyfin/jellyfin-web/pull/340, due in the next release (10.3.4).
