### ISSUE TITLE
proxy test no jellyfin adapt plugin

### ISSUE THREAD

**Issue by leopkks** [jellyfin/jellyfin#1375]
https://github.com/kodil/kodil/tree/master/repo/script.video.F4mProxy

to power wheel IPTV list
that works on kodi

example
of kodi things

in the folder

https://github.com/igor-rangel7l/AddOn_IgorList

from the igorlista
Where's the kodi addon?

it is possible to adapt create a plugin
for jellyfin
Thank you in advance.

**Comment by anthonylavado** [comment]
Sorry, we can’t help with adapting Kodi add-ons to Jellyfin. You can continue to use them in Kodi.

Also, we cannot help with any sources that may provide access to unlicensed video streams.
