### ISSUE TITLE
[feature] port to WD NAS: Western Digital PR4100

### ISSUE THREAD

**Issue by turnkit** [jellyfin/jellyfin#1379]
The WD My Cloud PR4100 uses a 1.6 GHz Quad-Core Intel Pentium N3710.  It's still in production.

Emby is running on the platform.  Please consider porting to it.  Thanks.

**Comment by turnkit** [comment]
Port still wanted.

**Comment by oddstr13** [comment]
I think this belongs on our shiney, brand new feature request tracker; 
https://features.jellyfin.org/
Could you please make a post there, to ease voting for the feature and gauging interest?

**Comment by oddstr13** [comment]
This feature request has been moved here; https://features.jellyfin.org/posts/220/port-to-wd-nas-western-digital-pr4100
