### ISSUE TITLE
Linting and conventions (inc. Drone CI)

### ISSUE THREAD

**Issue by BnMcG** [jellyfin/jellyfin#138]
Suggest that drone CI does some basic linting of C#, there don't appear to be any consistent conventions up until this point, but I think checking for the following would be a good start:

- Public methods before private methods
- Variable naming conventions (private, const, public, properties)

As for conventions, maybe just use the Resharper defaults (not sure if those are in turn sourced from a spec somewhere)? Those will be pretty common across all C# devs.

**Comment by BnMcG** [comment]
Happy new year! I think following this guide from Microsoft would be good general rules of thumb: https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/coding-conventions.

In terms of integrating with CI, something like StyleCop (https://github.com/StyleCop/StyleCop) should do the trick for us, as well as making sure code is ordered in a standard way in classes and other files (eg: public -> protected -> private declarations, fields being at the top of a class, etc).

**Comment by anthonylavado** [comment]
Closing, as @Bond-009 has been putting in validators when using VS/VSCode, and we also have JS checking for Web now. Also, moving away from Drone to Azure in general.
