### ISSUE TITLE
Jellyfin does not stream on Android Chrome

### ISSUE THREAD

**Issue by DeveloperOl** [jellyfin/jellyfin#1381]
**Describe the bug**
On my Android phone Jellyfin stops working sometimes. I can still navigate to the URL and browse all my movies, but as soon as I click on the play button of any movie I only get the spinning loader which keeps spinning forever. This happens without any obvious reason and applies to all media files. Restarting the phone fixes the issue, so it seems to be client side.

**Expected behavior**
The movie should start playing after I clicked on the play button.

**Logs**
Chrome debug console output on mobile phone:

`appRouter - processing path request /web#!/home.html`
`appRouter.js?v=10.3.2:412 appRouter - user is authenticated`
`appRouter.js?v=10.3.2:429 appRouter - proceeding to /web#!/home.html`
`apiclientcore.js?v=10.3.2:264 Requesting url without automatic networking: http://movies.cloud.ol/emby/Users/6e0cf3f…/Items/14df320…`
`apiclientcore.js?v=10.3.2:264 Requesting url without automatic networking: http://movies.cloud.ol/emby/Shows/30c76e2…/Episodes…se&IsMissing=false&UserId=6e0cf3f…&Fields=Chapters`
`apiclientcore.js?v=10.3.2:264 Requesting url without automatic networking: http://movies.cloud.ol/emby/Users/6e0cf3f…/Items/14df320…/Intros`
`apiclientcore.js?v=10.3.2:264 Requesting url without automatic networking: http://movies.cloud.ol/emby/Items/14df320…/Playback…ks=0&IsPlayback=true&AutoOpenLiveStream=true&MaxStreamingBitrate=140000000`
`apiclientcore.js?v=10.3.2:58 POST http://movies.cloud.ol/emby/Items/14df320…/Playback…ks=0&IsPlayback=true&AutoOpenLiveStream=true&MaxStreamingBitrate=140000000 408 (Request Timeout)`
`index.html#!/home.html:1 Uncaught (in promise) `

`Uncaught (in promise):`
body: (...)
bodyUsed: false
headers: Headers {}
ok: false
redirected: false
status: 408
statusText: "Request Timeout"
type: "basic"
url: "http://movies.cloud.ol/emby/Items/14df32030ce932d67c5bb2866ec5af6f/PlaybackInfo?UserId=6e0cf3f7b564409ba7c5c27ec6000bdf&StartTimeTicks=0&IsPlayback=true&AutoOpenLiveStream=true&MaxStreamingBitrate=140000000"
__proto__: Response

**System (please complete the following information):**
 - OS: Android 8.1.0 (Lineage OS)
 - Browser: Google Chrome
 - Jellyfin Version: 10.3.2
 - Reverse proxy: apache2, but problem persists without using a reverse proxy

**Comment by anthonylavado** [comment]
@DeveloperOl Sorry we haven't looked at this further. Are you still having issues with the latest Server, 10.3.7?
