### ISSUE TITLE
[bug] DVR JF 10.3.3

### ISSUE THREAD

**Issue by Ky-0** [jellyfin/jellyfin#1385]
The recording feature of JF does not work correctly - you press record series and it does nothing, press record and it states scheduled but it isn't (it generates a json file) but from what I can see it is not correct either. So the recording feature is broken.

Similar with the previous bug rasied but noticed that the record button is broken too - not just record series.

Config:
Debian 9 - REPO Install for JF
Chrome Browser [Version 74.0.3729.157]

**Comment by anthonylavado** [comment]
This may be closed in favour of jellyfin/jellyfin-web#338, but waiting to do some triage first.

**Comment by anthonylavado** [comment]
This is fixed in Jellyfin/Jellyfin-web#340, due in the next release (10.3.4).
