### ISSUE TITLE
[bug] Kodi Sync

### ISSUE THREAD

**Issue by Ky-0** [jellyfin/jellyfin#1387]
So I have installed the lastest version of JF 10.3.3 (was broken in the previous version too) and I have the plugin Kodi Quick Sync V2 installed but on Kodi launch it keeps saying that the quick sync has been disabled as I need to install the companion app which I have??

I can't use the Andorid TV app at the moment as it wont play certain files (tried 4k and got no audio) - which is expected as it's in beta still :)

Config:
Debian 9 - REPO Install for JF
Chrome Browser [Version 74.0.3729.157]

**Comment by sparky8251** [comment]
There arent too many folks working on Kodi integrations right now. Hopefully tagging this with "help wanted" gets this some extra visibility.
