### ISSUE TITLE
Trailers don't work when casting to chromecast

### ISSUE THREAD

**Issue by nickcorona** [jellyfin/jellyfin#1395]
Self-explanatory. The button just freezes in a pressed state and doesn't do anything.

**Comment by anthonylavado** [comment]
Hi @nickcorona - Could you clarify what you're seeing?
We have a Bug Template when creating a new issue, and it helps us figure out issues by asking a few questions. You can see what it looks like here: [Bug Report](https://github.com/jellyfin/jellyfin/issues/new?assignees=&labels=bug&template=bug_report.md)

**Comment by sparky8251** [comment]
Please correct the issue to follow the template or this issue will be closed. Thanks!

**Comment by nickcorona** [comment]
I don't know how reformatting my issue helps you solve it because it doesn't add any additional information.

If you're connected to Chromecasted through JellyFin android application, you can't play a trailer. The button just freezes and does nothing.

**Comment by nickcorona** [comment]
Not stale.

**Comment by JustAMan** [comment]
We request following a template for a reason.

For example, there is some important information we want you to tell us like server version and steps to reproduce. In its current form, this issue isn't actionable - i.e. we won't be able to easily reproduce it to see what's wrong and whether some of our actions fix it. This is the reason why we ask you to follow the template.

**Comment by nickcorona** [comment]
If you just log in to the app you'll see that the trailer doesn't button doesn't work. That's how you reproduce the issue. Instead of being a stickler for your template why don't you listen to what I'm telling you.
