### ISSUE TITLE
Swagger spec issues

### ISSUE THREAD

**Issue by athornz** [jellyfin/jellyfin#1404]
The current swagger spec has some issues which means API specs aren't defined properly.

For example, the user views API doesn't define the `UserId` parameter or a response type.
```
"/emby/emby/Users/{UserId}/Views": {
      "get": {
        "tags": [],
        "operationId": "GetUserViews",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "OK"
          }
        },
        "security": [
          {
            "api_key": []
          }
        ]
      }
    },
```

**Comment by sparky8251** [comment]
We are aware the docs suck. Unfortunately its what we inherited... Given the talks of a major API overhaul before the 11.0.z release, no one wants to really document the existing API.

We all agree the new API should be properly documented with parameters and response data samples. How we get there is uncertain.

Unfortunately, I am marking this "wontfix" and closing it. If someone wants to fix the swagger docs, all power to 'em, but we are just moving towards the new API which will be documented instead.
