### ISSUE TITLE
External subtitles in a wrong position while transcoding (Chrome)

### ISSUE THREAD

**Issue by Meiden-fc** [jellyfin/jellyfin#1405]
**Describe the bug**
The subtitles are being shown in the top of the screen and are half hidden by the address bar of the browser.

**To Reproduce**
1. Open a video with Chrome browser
2. Force transcoding (in this case it was 720p 4Mbps)
3. Choose external subtitles.
(It only happens in Chrome. Firefox shows subtitles properly)

**Expected behavior**
Subtitles must be just below the movie window.

**Logs**
Transconding log:
[transconding.txt](https://github.com/jellyfin/jellyfin/files/3219282/transconding.txt)

**Screenshots**
- Chrome:
![Captura de pantalla de 2019-05-25 11-58-46](https://user-images.githubusercontent.com/8806527/58367989-77437c00-7ee6-11e9-85c3-443704c2318e.png)
![Captura de pantalla de 2019-05-25 11-59-07](https://user-images.githubusercontent.com/8806527/58367990-77437c00-7ee6-11e9-99db-e5f8e7001a8b.png)

- Firefox:
![Captura de pantalla de 2019-05-25 12-04-24](https://user-images.githubusercontent.com/8806527/58367991-7f9bb700-7ee6-11e9-9989-181b5a0ca882.png)

**System (please complete the following information):**
 - OS: Server: Ubuntu 16.04 // Client: Ubuntu 18.04
 - Browser: Chrome (Firefox works fine)
 - Jellyfin Version: 10.3.3
 - Reverse proxy: yes

**Comment by poulpor** [comment]
I noticed this strange behavior too, only happening with Chrome, or chromium browsers  like Edge. Found a temporary fix in [reddit](https://www.reddit.com/r/jellyfin/comments/bjf3to/subtitle_placement_in_chrome_74/)  by changing subtitles size to smaller or larger font, anything but "normal", the subtitles are back in place.

**Comment by Meiden-fc** [comment]
I can confirm that it happens with Android apk beta9 as well.

**Comment by Dm3Ch** [comment]
I faced with this problem too. The only difference from TS case is that for me it happened when I watched with source resolution (I think there shouldn't be transcoding).

If it would help - here's my player "Nerd Stats":
```

Playback Info
Player:
Html Video Player
Play method:
DirectStream
Protocol:
https
Stream type:
HLS
Video Info
Player dimensions:
1440x789
Video resolution:
1920x1080
Direct Stream Info
Video codec:
H264 (direct)
Audio codec:
MP3
Original Media Info
Container:
mkv
Bitrate:
11.1 Mbps
Video codec:
H264 High
Video bitrate:
10.4 Mbps
Audio codec:
AC3
Audio bitrate:
640 kbps
Audio channels:
6
Audio sample rate:
48000 Hz
```

**Comment by olskar** [comment]
Could this be a dublicate of @298?

If so, should be fixed in latest chrome version

**Comment by Meiden-fc** [comment]
> Could this be a dublicate of [jellyfin/jellyfin-web#298](https://github.com/jellyfin/jellyfin-web/issues/298)
> 
> If so, should be fixed in latest chrome version

Yes it is, indeed. If it is fixed in latest Chrome version... what about Jellfin android apk?

**Comment by Dm3Ch** [comment]
I have checked, and on new (75) Chrome version subtitles works fine for me. 👍

**Comment by Meiden-fc** [comment]
Yes, I can confirm that this issue has been solved in last Chrome version.
