### ISSUE TITLE
Unable to login to Jellyfin through NGINX

### ISSUE THREAD

**Issue by Verequies** [jellyfin/jellyfin#1409]
**Describe the bug:**
Unable to login to Jellyfin when connecting through NGINX, connecting directly to the IP works, however I would rather not expose that..

**To Reproduce:**
Try to login through NGINX.

**Expected behavior:**
You're successfully logged in.

**Logs:**
You receive this message when trying to login:
`"Connection Failure - We're unable to connect to the selected server right now. Please ensure it is running and try again."`

In the browser console this is reported:
`/emby/Users/authenticatebyname:1 Failed to load resource: the server responded with a status of 400 ()`

**System:**
 - OS: Arch Linux
 - Browser: All
 - Jellyfin Version: 10.3.3
 - Reverse proxy: NGINX

**Comment by DrPandemic** [comment]
Could you share your NGINX config please? This might help someone find the problem.

**Comment by Verequies** [comment]
I was running 10.2.2 before this with the same config and all was well. Just been messing around a bunch with it and narrowed it down to my websocket parameters.

For some reason Jellyfin doesn't like:
```
#Main NGINX file
map $http_upgrade $connection_upgrade {

     default upgrade;
    ''      close;
}

# Socket parameters file
proxy_set_header       Upgrade $http_upgrade;
proxy_set_header       Connection "upgrade";

```

However its required for the websockets to work. If comment out those header lines, reload nginx, login, uncomment them, reload, and refresh. You can see the websockets connect without 404. 

However I then notice another error:
```
apiclientcore.js?v=10.3.3:58 POST https://media.example.com/emby/Sessions/Capabilities/Full 400
```

This is my server block:
```
# Jellyfin
server {

        listen                  *:443 http2 ssl;

        ssl_certificate         /path/to/example.com/ssl/fullchain.pem;
        ssl_certificate_key     /path/to/example.com/ssl/privkey.pem;
        ssl_trusted_certificate /path/to/example.com/ssl/fullchain.pem;

        include                 /path/to/example.com/config/ssl_params;

        server_name             media.example.com;

        location / {

                proxy_pass      http://jellyfin;
                include         /path/to/example.com/config/socket_params;

        }
}
```
This is my `ssl_params`:
```
ssl_session_cache               shared:SSL:10m;
ssl_session_timeout             10m;
ssl_session_tickets             off;

ssl_protocols                   TLSv1.2 TLSv1.3;
ssl_prefer_server_ciphers       on;
ssl_ecdh_curve                  secp521r1:secp384r1;
ssl_ciphers                     "ECDHE+ECDSA+CHACHA20:ECDHE+ECDSA+AESGCM:!AES128";

ssl_stapling                    on;
ssl_stapling_verify             on;

resolver                        1.1.1.1 1.0.0.1 valid=300s;
resolver_timeout                5s;

add_header                      Expect-CT "enforce; max-age=2592000; report-uri=\"https://report.example.com\"" always;
add_header                      Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;

```
And this is my `socket_param`:
```                                                        
proxy_http_version      1.1;
proxy_set_header        Upgrade $http_upgrade;
proxy_set_header        Connection "upgrade";
proxy_read_timeout      10s;
proxy_redirect          off;
proxy_set_header        Host $host;
proxy_set_header        X-Real-IP $remote_addr;
proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header        X-Forwarded-Proto $scheme;
```

**Comment by speedfreak01** [comment]
Do you have `location /embywebsocket { } ` configured? 

Make sure your config is the same as the docs, https://jellyfin.readthedocs.io/en/latest/administrator-docs/reverse-proxy/#nginx
That worked for me.

**Comment by Verequies** [comment]
@speedfreak01 Thanks heaps! I did not realise there was updated documentation. I had assumed it was a bug since everything was fine with 10.2.2.

**Comment by zuosc** [comment]
I have the same problem.  My Jellyfin version is 10.3.7

**Comment by Verwundert** [comment]
Hi,
I’m using Nginx Proxy Manager and can access my Jellyfin server from outside my home. I have configured it according to this guide: https://jellyfin.org/docs/general/networking/nginx#nginx-proxy-manager

However, when I enable an Access List (with username and password for Basic Auth), I can’t log into my server. When set to “Public,” it works fine.

Is there a solution for this?
