### ISSUE TITLE
Using library access breaks collections

### ISSUE THREAD

**Issue by CTalvio** [jellyfin/jellyfin#1410]
**Describe the bug**
Collections only work for users with full library access. Unchecking full access, even with all libraries checked, still causes this bug. Collections are visible, but they are empty (despite reporting their correct item count).

**To Reproduce**
Uncheck "Enable full access to all libraries" in user access settings.

**Expected behavior**
As long as the collections and relevant libraries are accessible to a user the contents of collections should be displayed.

**System (please complete the following information):**
 - OS: Linux mint 19.1 (Ubuntu bionic)
 - Browser: Any
 - Jellyfin Version: 10.3.3
 - Reverse proxy: nginx

**Comment by DrPandemic** [comment]
I tested https://github.com/jellyfin/jellyfin/pull/1394, and it does **not** fix it. So it's not directly linked to #1347.

This bug does not fully prevent the usage of collections, but it prevented me from finding them under `Movies > Collection`. Though, I was able to find and access collection from the home page.
![image](https://user-images.githubusercontent.com/3250155/58846659-f1de6b00-864d-11e9-966c-e0922eb37b7b.png)

**Comment by lukastribus** [comment]
CCing @cvium as the fix #1338 for issue #1278 may be relevant here.

**Comment by lukastribus** [comment]
This should be fixed in 10.3.4 by #1437

**Comment by CTalvio** [comment]
Addresses same issue as #1436
