### ISSUE TITLE
Search and record

### ISSUE THREAD

**Issue by skug67** [jellyfin/jellyfin#1414]
It would be great to be able to schedule future recordings for movies (or shows) that are not necessarily going to air within the range for which guide data has already been downloaded.  Something sort of like the MythTV/MythWeb "Power Search" option (wouldn't need to be quite that flexible -- just title search would probably be fine).

**Comment by dinki** [comment]
I'd like to see this too.  SageTV has a similar function.  It's a wildcard recording so that anything that matches the wildcard text will be recorded.
