### ISSUE TITLE
Can you implement a plug-in to fetch information from Douban.com ?

### ISSUE THREAD

**Issue by imaomao** [jellyfin/jellyfin#1416]
In China, access to websites such as TheTVDB is very slow.

**Comment by lenhoo** [comment]
> In China, access to websites such as TheTVDB is very slow.

It's true, I use proxy for TMDB or TVDB acceleration for now, hope Douban.com can be the optional service.

**Comment by yfdoor** [comment]
it's a good idea for this project and will get more users for Jellyfin.

**Comment by oddstr13** [comment]
This should probably be implemented in a plugin.

**Comment by Spyrx** [comment]
I'll give this plugin a shot. Could be a good way to learn a bit about the jellyfin codebase.

**Comment by Libitum** [comment]
I'm in developing of such a plugin: https://github.com/Libitum/jellyfin-plugin-douban
The main function works right even it's still in developing.
Welcome feedback :-)

**Comment by dkanada** [comment]
@Libitum that's excellent! Let us know if you want to include it in the organization or plugin repository at any point.

**Comment by Libitum** [comment]
@dkanada Thanks! I'm glad to see that it can be included by official! I think it's better to do it when it's ready for release v1.0. WDYT?
I will test it in my environment and improve it continually.

**Comment by dkanada** [comment]
Sounds good to me! Message me or another team member when you'd like to add it to the official plugin repository and we can build it for a release.

**Comment by Libitum** [comment]
Hi @dkanada Sorry for late response. I think it's ready for the project to be included in the plugin repository. I have tested it for weeks and implemented much features. Could you give me some help? Thanks!

**Comment by JustAMan** [comment]
cc @jellyfin/core

**Comment by dkanada** [comment]
@Libitum we have third party plugin repositories planned in the next month or so, would you be interested in that? They're literally just a JSON manifest pointing to ZIP files for each release, so you could even host it on GitHub if you wanted.

**Comment by yfdoor** [comment]
@dkanada ,@jellyfin/core, @JustAMan, @oddstr13, hope it can be relesaed in next version, thanks

**Comment by Libitum** [comment]
Do you mean the third party plugin repositories? That's cool! Looking forward to it, Thanks!

**Comment by dkanada** [comment]
@Libitum we added third party plugin repositories for 10.6.0, which will be released within a week. I think the best option for your plugin is to use that method :) it should be as simple as adding a JSON file to your GitHub repository pointing to binary releases.

Users would be able to add the repository with a URL like `https://github.com/Libitum/jellyfin-plugin-douban/blob/master/manifest.json` at the new repository page in the dashboard. I'll add a blog post soon with more information.

**Comment by Libitum** [comment]
@dkanada That's cool! Thank you very much!

**Comment by dkanada** [comment]
Had some time this morning, here's the [blog post](https://jellyfin.org/posts/plugin-updates) with more information. If you do create a repository feel free to include it in the [documentation](https://github.com/jellyfin/jellyfin-docs) somewhere! I should figure out a place on the main website to include a list of plugin repositories as well.

**Comment by Libitum** [comment]
@dkanada  That's cool! thanks for the awesome work! I will try it as soon as possible.
