### ISSUE TITLE
Searching for subtitles in opensubtitles errors out

### ISSUE THREAD

**Issue by balasankarc** [jellyfin/jellyfin#1424]
When searching for subtitles from Open Subtitles (Three dots => Edit Subtitles => Search icon), it comes back with ` No results found. ` message. On checking the server logs, I see the following
```

May 31 07:13:19 jellyfinserver jellyfin[546]: [07:13:19] [ERR] Error downloading subtitles from Open Subtitles
May 31 07:13:19 jellyfinserver jellyfin[546]: System.NullReferenceException: Object reference not set to an instance of an object.
May 31 07:13:19 jellyfinserver jellyfin[546]:    at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.Login(CancellationToken cancellationToken)
May 31 07:13:19 jellyfinserver jellyfin[546]:    at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.Search(SubtitleSearchRequest request, CancellationToken cancellationToken)
May 31 07:13:19 jellyfinserver jellyfin[546]:    at MediaBrowser.Providers.Subtitles.SubtitleManager.<>c__DisplayClass11_0.<<SearchSubtitles>b__3>d.MoveNext()
```

**System (please complete the following information):**

 - OS: Debian Sid
 - Browser: Firefox
 - Jellyfin Version: Jellyfin.Server 10.3.3.0
 - Reverse proxy: No

**Comment by anthonylavado** [comment]
Just to be sure - do you have the latest OpenSubtitles plug in installed? Should be version 3.0.0.0.

**Comment by balasankarc** [comment]
Yup. I do. :)

![image](https://user-images.githubusercontent.com/2379271/58684122-a8172b80-8394-11e9-8222-77245f571b40.png)

**Comment by dkanada** [comment]
Do you have an OpenSubtitles account set in the plugin?

**Comment by balasankarc** [comment]
> Do you have an OpenSubtitles account set in the plugin?

Yes.

**Comment by balasankarc** [comment]
Huh. I cleared the username/password, saved it, and then re-added credentials. Now it works. Some sort of cache?

Also, I thought username/password was optional for opensubtitle. If so, if login failed shouldn't it fallback to non-authenticated mode?

**Comment by dkanada** [comment]
Yeah that's really odd, I wouldn't expect it to get resolved with those steps. You're correct, the credentials are entirely optional, they provide whatever benefits OpenSubtitles has for authenticated requests. I believe you get quicker access to new subtitles or something.

**Comment by sparky8251** [comment]
Since this issue seems resolved for now, I am closing it. Folks are welcome to open a new issue if this recurs.
