### ISSUE TITLE
Remove Password Fix Code from #1406

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin#1425]
Placeholder issue to remove the PIN migration code introduced in #1406.

This should be removed either with or just after 10.4, so that enough users have gone through the silent fix.

**Comment by DrPandemic** [comment]
https://github.com/jellyfin/jellyfin/pull/1406/files#diff-0102c33c339071ab2b95b4a85598e951R187

**Comment by sparky8251** [comment]
I'd almost prefer we do not remove this in 10.4.z and remove it in 10.5.z.

If the goal of 10.4.0 has changed to be a super stable and largely bug free release before the big database rewrite in 10.5.0, we should keep the silent fix in 10.4.z.

At least then we can claim that folks need to upgrade to the stable and well fixed 10.4.z before they can use anything 10.5.z.

**Comment by JustAMan** [comment]
How come this was migrated as a feature?..

**Comment by anthonylavado** [comment]
Also we already took this out, possibly too early, but alas
