### ISSUE TITLE
Music Star Rating

### ISSUE THREAD

**Issue by WisdomCode** [jellyfin/jellyfin#1435]
**Describe the feature you'd like**
Beside the now common "favorit" button for organizing your favorite music, there is also the star rating, giving singular songs a number of stars between 1 and 5. 
I would love to see support for this more sophisticated way of rating your music. 
The stars can even be saved inside the mp3 file, so it would be nice to directly get them from there when scanning. For a supporting scanner, you may refer to banshee or ampache. For a working Tag editor fully supporting it, you may refer to eyed3. From their
[Code](https://github.com/nicfit/eyeD3/blob/857a56d976bac05b65c3ce9f7323dbc215deb348/src/eyed3/id3/frames.py), I concluded that this specific Tag is saved under the value 'POPM' (see Line 48). If you want help on this task, I'd be glad to help.

**Comment by ArnaudB88** [comment]
I would also love this feature. For me, it is a requirement to start using this system.

But I think saving the score should be done in the database so different users can rate different on one item.

**Comment by WisdomCode** [comment]
This is actually also possible in the metadata. There can be multiple ratings, lest under a name, email or similar value. However, I can see that point, but for keeping those values for interoperability, some way for writing and reading those values (it may be an api or something, not necessarily a default option) would be really nice.

**Comment by kyriakosbrastianos** [comment]
Just use the vorbis comment way that are simply named "RATING" and a value from 1 to 5 or 1 to 10. This kind of tag names are also recognized from kodi and other players. I see no reason to add name, email and other no standard values and make it incompatible to be read from other players.

**Comment by WisdomCode** [comment]
The Popularity is a standard way to save the star rating, I know at least 3 player working with those and its part of the original definition of idv3. It allows for multiple ratings on one song, like @ArnaudB88 requests. For the exact usage of naming etc., you may refer to those players using it (banshee, ampache etc). 
However, if this is a more popular way to save star rating, then this may be a better way to go. Maybe you could elaborate and explain in more detail how this works? Are these tag names recognized by emby already? What other players support it other than Kodi?
