### ISSUE TITLE
Folder based access control

### ISSUE THREAD

**Issue by balasankarc** [jellyfin/jellyfin#1438]
**Is your feature request related to a problem? Please describe.**

A way to provide more granular access to libraries. 

If I have a general library "TV Shows" with multiple folders as sources (English, Cartoons, Reality Show, Talk Shows) etc, and I want kids to access only Cartoons, I can't do it without moving it out to a new Library, thus breaking a sane library structure.

**Describe the solution you'd like**

The feature described in https://github.com/MediaBrowser/Wiki/wiki/New-Folder-based-Access-Control.

**Comment by pjeanjean** [comment]
Jellyfin already supports parental classification (even on folders) and parental access control.
This looks like what you should use for your specific issue.

**Comment by balasankarc** [comment]
@pjeanjean Oh, that's cool. Got any links for me to check what I need to do?

**Comment by pjeanjean** [comment]
I don't have a link, but it is pretty easy to do:
- Click on the 3 dots for a folder or an item
- > Edit metadata
- Set the parental classification metadata
- Go to your server's users management
- > Parental Control
- Set a maximum parental classification, and optionally disable all the media with no classification

**Comment by DrPandemic** [comment]
@balasankarc does this solve your issue?
