### ISSUE TITLE
Jellyfin user list is stuck loading indefinitely

### ISSUE THREAD

**Issue by whalehub** [jellyfin/jellyfin#1441]
**Describe the bug**
The user list is stuck loading indefinitely with an error being displayed in the browser console.

**To Reproduce**

1. Log into your Jellyfin website.
2. Click on the dashboard icon in the top right corner of the site.
3. Click on the "Users" tab on the left.

**Expected behavior**
I expect the user list to load normally.

**Logs**
N/A

**Screenshots**
v10.3.2
![59053311-69e8a300-8891-11e9-8a27-5f6d7f755d56](https://user-images.githubusercontent.com/44198148/59053941-dc0db780-8892-11e9-806a-cbb5a9aeaf8c.png)

v10.3.3
![vivaldi_2019-06-06_19-30-22](https://user-images.githubusercontent.com/44198148/59053354-8be22580-8891-11e9-995e-a75e0112198b.png)

**System (please complete the following information):**
 - OS: Docker
 - Browser: Chrome
 - Jellyfin Version: 10.3.3
 - Reverse proxy: Caddy

**Additional context**
This problem does not exist in Jellyfin 10.3.2, so one of the commits that were made between the release of v10.3.2 and v10.3.3 must have introduced this bug.

**Comment by anthonylavado** [comment]
Do any of the users have PINs?

**Comment by anthonylavado** [comment]
I would also check the server log when trying to load this page.

**Comment by whalehub** [comment]
This issue has been fixed in version v10.3.4.
