### ISSUE TITLE
Subtitles not working from library with a "Shared Network Folder" set.

### ISSUE THREAD

**Issue by TrisMcC** [jellyfin/jellyfin#1446]
**Describe the bug**
When using the web interface, subtitles are not working from a library with a "Shared Network Folder" set. The ffmpeg command includes the network folder path instead of the direct file path.

**To Reproduce**
1. Configure a library with a shared network path
2. View a video with embedded subtitles
3. Notice no subtitles

**Expected behavior**
Subtitles should be shown.

**Logs**
[log.txt](https://github.com/jellyfin/jellyfin/files/3268666/log.txt)

**System (please complete the following information):**
 - OS: Arch Linux
 - Browser: Firefox 67.0.1
 - Jellyfin Version: 10.3.4
 - Reverse proxy: no

**Comment by 0ddb0d** [comment]
Presumably this won't be noticeable on systems that have libsmbclient support compiled into ffmpeg.
