### ISSUE TITLE
Flattening TV Shows

### ISSUE THREAD

**Issue by charlox612** [jellyfin/jellyfin#1449]
I would like the ability to flatten TV shows especially single season shows, having all the episodes displayed on the first description page of the show. It's a bit weird to click into a show and having to click into its single season to access the episodes. I also found that occasionally the season poster for single-season shows are not well done, or someone would just lazily upload one of the DVDs cover. I've realized that I have a lot of single season shows and it was something that I appreciated in Plex but was one of the pet peeves I had with Emby. There are even multi-season shows that I feel shouldn't have been split up into seasons or the way TVDB does it.
It would be nice if it was implemented similarly to Plex where you can select to show or hide seasons either through default library settings with the added option of doing through the shows settings.

**Comment by 0ddb0d** [comment]
This is a good idea as it deals with mini-series and shows that are cancelled after one season as well as reducing the number of clicks required to get playback started.

That said it is more easily implemented as a client feature and probably should be requested as a [jellyfin-web](https://github.com/jellyfin/jellyfin-web/issues) or [jellyfin-react-client](https://github.com/jellyfin/jellyfin-react-client/issues) feature instead. The Samsung TV and Kodi clients have this feature already as they inherited it from Emby.

As a little background, this was requested multiple times before Jellyfin was forked from Emby (examples [here](https://emby.media/community/index.php?/topic/35468-req-skipping-the-seasons-screen-if-only-one-season-exists/), [here](https://emby.media/community/index.php?/topic/55031-turn-off-seasons/) and [here](https://emby.media/community/index.php?/topic/19156-a-few-questions-about-flattening-one-season-shows-and-strm-files/)) and one helpful user even explained [a workaround to manually flatten shows](https://emby.media/community/index.php?/topic/55031-turn-off-seasons/#entry534507) until such a feature was added.
