### ISSUE TITLE
Creating an user that already exists completely break Jellyfin

### ISSUE THREAD

**Issue by ferferga** [jellyfin/jellyfin#1450]
**Describe the bug**
Trying to create an user with the same name that one that already exists completely breaks the Jellyfin session (starting again from incognito should work)

**To Reproduce**

1. Create an user in dashboard
2. Login as that user (if you aren't already logged in with that user)
3. Create another user with the same name as the user created in step 1

**Expected behavior**
Catched error (with proper visual feedback) and no issues.

**Logs**
This log piece is written repeteadly when you attempt to access Jellyfin in system log.
````
Jun  9 19:46:24 ferferga-server jellyfin[31990]: [19:46:24] [ERR] Error processing request
Jun  9 19:46:24 ferferga-server jellyfin[31990]: System.IndexOutOfRangeException: Index was outside the bounds of the array.
Jun  9 19:46:24 ferferga-server jellyfin[31990]:    at MediaBrowser.Model.Cryptography.PasswordHash..ctor(String storageString)
Jun  9 19:46:24 ferferga-server jellyfin[31990]:    at Emby.Server.Implementations.Library.UserManager.GetLocalPasswordHash(User user)
Jun  9 19:46:24 ferferga-server jellyfin[31990]:    at Emby.Server.Implementations.Library.UserManager.GetUserDto(User user, String remoteEndPoint)
Jun  9 19:46:24 ferferga-server jellyfin[31990]:    at MediaBrowser.Api.UserService.Get(GetUser request)
Jun  9 19:46:24 ferferga-server jellyfin[31990]:    at lambda_method(Closure , Object , Object )
Jun  9 19:46:24 ferferga-server jellyfin[31990]:    at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
Jun  9 19:46:24 ferferga-server jellyfin[31990]:    at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost appHost, Object requestDto, IRequest req)
Jun  9 19:46:24 ferferga-server jellyfin[31990]:    at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken)
Jun  9 19:46:24 ferferga-server jellyfin[31990]:    at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
````

**System (please complete the following information):**
 - OS: Raspbian
 - Jellyfin Version: 10.3.3

**Additional context**
``System.ArgumentException: A user with the name 'ferferga' already exists is triggered when the user is created
``
appears in logs when the error is catched

**Comment by joshuaboniface** [comment]
I'm able to get the (expected) exception there:

```
un 09 14:01:53 jf1 jellyfin[11610]: [14:01:53] [ERR] Error processing request                                                                                                                                                  
Jun 09 14:01:53 jf1 jellyfin[11610]: System.ArgumentException: A user with the name 'jellyfin' already exists.
Jun 09 14:01:53 jf1 jellyfin[11610]:    at Emby.Server.Implementations.Library.UserManager.CreateUser(String name)
Jun 09 14:01:53 jf1 jellyfin[11610]:    at MediaBrowser.Api.UserService.Post(CreateUserByName request)                                                                                                                          
Jun 09 14:01:53 jf1 jellyfin[11610]:    at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
Jun 09 14:01:53 jf1 jellyfin[11610]:    at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, IResponse httpRes, ILogger logger, CancellationToken cancellation
Token)                                                                                                                                                                                                                                        
Jun 09 14:01:53 jf1 jellyfin[11610]:    at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)   
```

With no further breakage. Though it should definitely say something on the screen.

**Comment by ferferga** [comment]
> I'm able to get the (expected) exception there:
> 
> ```
> un 09 14:01:53 jf1 jellyfin[11610]: [14:01:53] [ERR] Error processing request                                                                                                                                                  
> Jun 09 14:01:53 jf1 jellyfin[11610]: System.ArgumentException: A user with the name 'jellyfin' already exists.
> Jun 09 14:01:53 jf1 jellyfin[11610]:    at Emby.Server.Implementations.Library.UserManager.CreateUser(String name)
> Jun 09 14:01:53 jf1 jellyfin[11610]:    at MediaBrowser.Api.UserService.Post(CreateUserByName request)                                                                                                                          
> Jun 09 14:01:53 jf1 jellyfin[11610]:    at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
> Jun 09 14:01:53 jf1 jellyfin[11610]:    at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, IResponse httpRes, ILogger logger, CancellationToken cancellation
> Token)                                                                                                                                                                                                                                        
> Jun 09 14:01:53 jf1 jellyfin[11610]:    at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)   
> ```
> 
> With no further breakage. Though it should definitely say something on the screen.

Hmm, well, maybe you should log in as "jellyfin" and then create the second user with the same name in order to break it?. I'm going to update the description to clarify this.

**Comment by sparky8251** [comment]
This will likely also require changes in the frontend to be considered fully fixed.
