### ISSUE TITLE
DLNA not discoverable

### ISSUE THREAD

**Issue by 97carmine** [jellyfin/jellyfin#1464]
**Describe the bug**
DLNA works but clients can not discover it.

**Additional context**
Possible bug related #1322 #972

**System:**
 - OS: Debian 9
 - Jellyfin Version: 10.3.5

**Comment by Namaretuklefu** [comment]
Same issue.
In server logs there is even message about creating profile for my TV but i am still unable to see server listed as possible source.

OS: Ubuntu server 19.04
Jellyfin version: 10.3.5

**Comment by sparky8251** [comment]
Does anyone have logs detailing the issue or potential steps we can use to reproduce this?

If DLNA was blanket broken we would know. Lots of major contributors use it daily. There is definitely more than meets the eye to whatever issue you both are facing.

**Comment by 97carmine** [comment]
The problem is that I can not see any report in the log, for example, as @Namaretuklefu says, the profiles are created for the TVs, in my case two, but none of them can "see" the DLNA server, like no smartphone or tablet.

**Comment by 97carmine** [comment]
I have solved the problem, I have changed in Control panel> Advance> Secure connection mode: Disabled.
For now, as the IPv4 network of my ISP is inside CG-NAT, I can not open ports, so it does not make much sense to configure the HTTPS connection or a reverse proxy.

I have done tests with the options and this is the result that I have obtained.

  _Secure connection mode_ status|_Enable automatic port mapping_ status|DLNA Discoverable status
--|--|--
Disabled|Yes/No|Yes
Preferred, but no required|Yes/No|? [1]
Handled by reverse proxy|Yes/No|No [^2]

[^1]: When changing the options to those parameters, if you select another option of the control panel (for example: Logs) and check the status of the parameters again, they are changed to:
_Secure connection mode: Disabled_ and _Enable automatic port mapping: Yes_.
It may be because I have not configured any of the parameters related to SSL.

[^2]: I selected this option because I had planned to configure a reverse proxy, but I have not done it, maybe that's why the DLNA server is not discoverable.

**Comment by 97carmine** [comment]
Solving this gub also solves this error: https://github.com/jellyfin/jellyfin-android/issues/148.

Due to similarity, @nonplusnl. You can confirm if this fix solves #1456.

**Comment by sparky8251** [comment]
Oh god... *those* settings again. We should flat remove them from the web ui. They are a constant source of problems for users because they do NOT act like people expect. I've only see them break things if someone changes them from the defaults.

**Comment by nonplusnl** [comment]
> Due to similarity, @nonplusnl. You can confirm if this fix solves #1456.

Indeed it does! Thanks a lot!
