### ISSUE TITLE
Genres sorting difference in /Items/Filters and /Items/Filters2. very minor

### ISSUE THREAD

**Issue by SenorSmartyPants** [jellyfin/jellyfin#1465]
**Describe the bug**

/Items/Filters outputs like this:
```
Genres: [
"Sci-Fi & Fantasy",
"Science-Fiction"
],
```
/Items/Filters2 outputs this:
```
Genres: [
{
Name: "Science-Fiction",
Id: "44a6a873a8ec54283c407e7193e7dd69"
},
{
Name: "Sci-Fi & Fantasy",
Id: "3d621c0b6dc1921bc93fa859f7512270"
}
],
```
Note that the orders are reversed.

**To Reproduce**

http://local:8096/emby/Items/Filters and http://local:8096/emby/Items/Filters2 API endpoints.

**Expected behavior**

Sorting order should be the same between the two endpoints.

**System (please complete the following information):**
 - OS: Docker
 - Browser:Chrome
 - Jellyfin Version: 10.3.5
 - Reverse proxy: no

**Comment by Bond-009** [comment]
AFAIK we don't guarantee any specific order with any API response.

**Comment by dkanada** [comment]
Hmmmmm I'd like to remove one or the other, looks like something that was added for compatibility.
