### ISSUE TITLE
Prevent (sub)folder scanning thru dotfile

### ISSUE THREAD

**Issue by platinum55** [jellyfin/jellyfin#1474]
I have some music albums folders in FLAC and MP3 in the same folder and want jellyfin to just scan one of them(the FLAC version). 

**Describe the solution you'd like**
A dotfile or something like ".dont-scan" would be very useful. Jellyfin should ignore folders which contains this magic file

**Describe alternatives you've considered**
Moving the MP3 folder out of the way works, but destroys my structure

**Comment by cvium** [comment]
Did you try https://github.com/MediaBrowser/Wiki/wiki/Excluding-files-&-folders?

**Comment by platinum55** [comment]
somehow I didn't find it, sorry and thanks alot!
