### ISSUE TITLE
Server keeps reading files from HDD after playback is stopped

### ISSUE THREAD

**Issue by regs01** [jellyfin/jellyfin#1475]
**Describe the bug**
Server keeps reading files from HDD after client playback is stopped. Even if DLNA client is completely stopped and disconnected. Whatever it's a direct play or transcode.

**To Reproduce**
1. Start playing something
2. Stop playing
2a. Or start playing another file
3. All files shows high HDD reading activity for very long. Files played with transcoding stops reading from disk in 5 minutes after playback is stopped.

**Expected behavior**
Well, somehow it should have less stress on HDD.

**System (please complete the following information):**
 - OS: Windows
 - Jellyfin Version: 10.3.5

**Comment by sparky8251** [comment]
This is likely because even if the client kills the stream, the transcode job for playback has already been queued and there is no process setup to end the transcode jobs.

Are you *sure* this happens with direct play? It seems very odd and I'd only expect it to happen with transcode. I'd also like to ask if this is replicable with the Web UI or if its DLNA clients only. Perhaps it's something specific to DLNA clients?

**Comment by sxales** [comment]
I am having the same problem in Jellyfin 10.3.6 with Windows 10 1903 build 18362.239. I have transcoding disabled in the user profiles by unchecking:

- Allow audio playback that requires transcoding
- Allow video playback that requires transcoding
- Allow media downloading and syncing that requires transcoding

So it should only be going over direct play. I don't see any ffmpeg instances in the task manager which would confirm that. 

Once I stop playback, I see very high disk usage for the Jellyfin task.

![Untitled](https://user-images.githubusercontent.com/29420152/61986621-17e11580-afd6-11e9-8af4-6fcf13eaf972.png)

I am thinking it has to do with the bitrate of the files. When I tried it on a few lower bitrate videos (~2mb/s) Jellyfin server continued reading the disk for only a few seconds after playback stopped. However, with high bitrate files (~17mb/s) it continues for much longer. Some times it comes down on its own after a few minutes and other times it has to be manually stopped by restarting Jellyfin. 

I am unable to test the high bitrate files in the web interface as I don't believe it supports 4k HDR video without transcoding. Although, the low bitrate file performed the same in the web interface and DLNA.

**Comment by JustAMan** [comment]
@sxales could you please re-check on Jellyfin 10.4.0? If it is still happening ping me and I'll reopen this issue.

**Comment by regs01** [comment]
Doesn't seem to happen with 10.4.0. Don't know who to blame, 10.4.0 or Windows 10 1909.
