### ISSUE TITLE
Folder scan issue on 10.3.5

### ISSUE THREAD

**Issue by forsomefun2** [jellyfin/jellyfin#1476]
**Describe the bug**

Library Scans Fail
ghost folders created as in they don't show up until a restart
...Please ensure the path is valid "
10.3.5

**To Reproduce**

1. Ubuntu 10.3.5 amd64
2. Attempt to add folder 
3. Click okay or arrow button
4a. Restart jellyfish see random folders if 1-3 done multiple times. 
4b scan folder see erroring out

fix
Downgrade to 10.3.4

**Comment by sparky8251** [comment]
Unfortunately, we are going to need more information to solve this bug.

Can you expand on what you mean by "Add folder"? I don't understand what you are describing at all...

**Comment by forsomefun2** [comment]
This was an attempt to add a Library
with at least one folder attached

You can of course add multiple folders to each library. But this error lead to no folders being added just an error message. 

When system is rebooted. Ghost folders appear even though an error has occurred prior. 
However any attempt to draw media from these folders fail

**Comment by sparky8251** [comment]
Ok. I understand now. Thanks for the extra info!

**Comment by DrPandemic** [comment]
My 0.02$ is that it's related to https://github.com/jellyfin/jellyfin/pull/1437. There's another folder permission PR that just got merged https://github.com/jellyfin/jellyfin/pull/1394 and it will be part of 10.3.6. You can wait for the next release to see if it fixes your issue, or you could test the current `10.3.z` branch.

**Comment by onny** [comment]
We already have 10.3.7 released. @forsomefun2 could you please try again and look if this issue does still exists?

**Comment by forsomefun2** [comment]
fixed
