### ISSUE TITLE
Next Up doesn't display special set to air after a season

### ISSUE THREAD

**Issue by SenorSmartyPants** [jellyfin/jellyfin#1479]
**Describe the bug**
Special with "display after season" did not display in next up after I watched last episode of said season.

**To Reproduce**

1. Add these episodes to your library.
```
Doctor Who (2005) 11x10 - The Battle of Ranskoor Av Kolos.mkv
Doctor Who (2005) 0x156 - Resolution.mkv
```
2. Watch/mark watched 11x10
3. 0x156 does not display in next up.

**Expected behavior**
Specials should be considered when calculating next up. All of the following metadata should be taken into account.
Airs before season
Airs after season
Airs before episode

**System (please complete the following information):**
 - OS: Docker
 - Browser: Chrome
 - Jellyfin Version: 10.3.5
 - Reverse proxy: no

**Comment by SenorSmartyPants** [comment]
This issue sounds similar to #1108.

**Comment by sparky8251** [comment]
Specials have lots of issues right now... I think a lot of it are just database limitations since we can't have multiple bits of info attached to each file, like an air order, season, and more.

Ideally, with the database rewrite we can add in this required information so that clients can finally be written to sort out the dumb specials issues.

**Comment by SenorSmartyPants** [comment]
IDK if this requires a database rewrite, maybe just the Next Up query. 

All the data is in JF already, and the episode is displayed in the correct spot in the season if you have the Library->"Display specials within seasons they aired in" setting checked.

**Comment by sparky8251** [comment]
Perhaps yes. I'll pull the blocked tag unless its proven there is a block.

Thanks for the report!

**Comment by KaXaSA** [comment]
How do you guys deal with this issue? Just change the specials' metadata to make them part of the season?
