### ISSUE TITLE
Playback speed

### ISSUE THREAD

**Issue by gerroon** [jellyfin/jellyfin#148]
It will awesome if Jellyfin offers palyback speed adjustment like Youtube and Vlc does. Basically the video can play faster or slower

**Comment by JustAMan** [comment]
Do you want quick-and-dirty version or good one? :) I mean, speed up or slow down a video should not be that big of a deal in `ffmpeg` (but video quality would suffer in any case I think), but most likely would require transcoding. Are you willing to pay the price? :)

Audio is another thing, if you blindly speed it up or down it changes pitch and tone. At least Youtube goes smart and modified the tempo. I think `ffmpeg` has a library for that (`rubberband` should be the one doing this thing), but that is something to be learnt.

**Comment by gerroon** [comment]
I am ok with transcoding, but transcoding will kick in only when the speed is adjusted right?

**Comment by Cerothen** [comment]
I am not entirely familiar with the web player but it should be possible right in the web client, I don't see why playback rate would be a serverside thing.

https://stackoverflow.com/questions/3027707/how-to-change-the-playing-speed-of-videos-in-html5

**Comment by JustAMan** [comment]
Nice find! I wonder what would happen to audio, though... Needs some experiments.

**Comment by kusochi** [comment]
This seems to be something the browser itself can do. On plain html5 video example [https://www.w3schools.com/html/html5_video.asp](https://www.w3schools.com/html/html5_video.asp) try right clicking the video and at least on Firefox there seems to be option to change playback speed in the right click menu. I don't think there's need to transcode it using `ffmpeg`. Is this something that can be added to the player ui as it seems to be a standard feature?

**Comment by gerroon** [comment]
@kusochi I seem to get speed menu only once, I set the playback speed, but then that menu is not available anymore in the right click menu

**Comment by bugfixin** [comment]
I agree this should be a client-side feature. I'm looking at implementing this for jellyfin-web, but would like some input regarding the expected UI for playback speed adjustments.

**Comment by kusochi** [comment]
I like the idea that the setting would be in the same "cogwheel menu" as the video quality setting selection. From there could open a submenu containing all the usual playback speed options like 0.5, 0.75, 1.0, 1.25 and 1.5 similar how they are in Youtube's player settings for example.

**Comment by wyzdic** [comment]
This is a very good idea, I really need this,Is it possible to implement this feature in the near future?
