### ISSUE TITLE
Stats for Nerds should show original media size ( in mega/gigabytes? )

### ISSUE THREAD

**Issue by naclander** [jellyfin/jellyfin#1492]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Stats for Nerds is great, but it should contain the total size of the file being played somewhere

**Describe alternatives you've considered**
Multiplying, in my head, the total bitrate by the run time to figure out the total media size 😛

**Additional context**
Jellyfin is fantastic, thanks for the continued work on the project

**Comment by cvium** [comment]
You mean under "Original Media Info"?

**Comment by naclander** [comment]
@cvium Yea, I think that would be the best place for it.

**Comment by MartinH0** [comment]
Lets assume you have a 4K Movie in a .mkv container.
The whole File is 50GB big.
- 35GB the Video
- 3 x 5GB for each Audio Stream.

What would you like to get displayed?
40GB (as this is the size that gets streamed) or 50GB as its the total filesize?
I would preffer 40GB (35GB V, 5GB A)

**Comment by DrPandemic** [comment]
I really don't know much about encoding, but my 2 cents would be that what's going over the wire is more interesting

**Comment by EraYaN** [comment]
The size should probably just be per stream, and since ffprobe does not report this data, I think we might then have to switch to MediaInfo. Cause it seems the only way to get stream size out of ffprobe is to do a null mux, and this reads (parts of?) the whole file.

and you get output like this:
```
video:5393338kB audio:280506kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
```
On my MacBook SSD that one take 5.2 seconds. But I feel it is not worth it.

On macOS:
```
brew install cask medainfo
```

then 
```
mediainfo --Output=JSON --Full file.mp4
```

The size is in the `StreamSize` field. One mayor thing is that for mp4 and mkv this program is MUCH faster.

**Comment by MartinH0** [comment]
> and you get output like this:

But does this also report the sze of all audio streams separately?

**Comment by EraYaN** [comment]
Well for ffprobe null mux only for the selected streams (see the command line)

**Comment by MartinH0** [comment]
Thats what I mean.
If you have 3 Audio streams you will not know what bandwidth you need to play it.

Like I mentioned here

> Lets assume you have a 4K Movie in a .mkv container.
> The whole File is 50GB big.
> 
> * 35GB the Video
> * 3 x 5GB for each Audio Stream.

**Comment by EraYaN** [comment]
That is exactly why I mentioned MediaInfo.

**Comment by cvium** [comment]
> If you have 3 Audio streams you will not know what bandwidth you need to play it.

You wouldn't be able to tell anyway. Most media doesn't use CBR. A 4k video with avg. 30 Mbit/s bitrate stream will likely spike to 80 Mbit/s for a few frames or more. You would need to analyze the file to determine the actual bandwidth required.

**Comment by 0ddb0d** [comment]
+1 for cvium's simple approach. Original file size or a flag for live/streaming content.

Frame rate information is similarly problematic and should also be approached with caution. There are good reasons why Kodi, Plex and Emby all simplified their media information features.

**Comment by naclander** [comment]
Yea, the total size of the original file is what I expected to see.
