### ISSUE TITLE
Split packaging (`deployment/`) from main repo

### ISSUE THREAD

**Issue by joshuaboniface** [jellyfin/jellyfin#1496]
I think we're at the point with the project where the OS packaging (Debian, Ubuntu, Fedora, etc.) can be split out, in order to be better managed independently from the core code. This gives us more flexibility to deal with packaging-related issues (like #1320) separately from the main release schedule.

Debian natively supports independent packaging in a separate Git repository, and I trust that Fedora supports a similar thing.

The main downside of this is that it breaks the centralized "build" script in the main repo, which relies on the existing bash-based deployment strategy. So it would require reworking of the build toolchain for the main repo. I think the greater flexibility is worth it, especially if we ever want to become "official" on the Debian side, but will leave this an open question. I think for this, the "default" should be Docker (i.e. if you want to build from source, build the official main docker image) which would remain where it is, along with a simple "build ZIP for windows" script in the root of the repo, and then building Linux OS packages would be independent repos.

Tentatively scheduled as part of 10.4.0, though no real timeline, and depending on everyone's feedback.

**Comment by anthonylavado** [comment]
For the macOS side, I’ll have to report back with what I can find for build automation. I’m hoping I don’t have to leave my Mac on when we’re planning a release.

**Comment by DrPandemic** [comment]
I don't think we'll need something like that. If we don't have access to a native mac, we could use https://github.com/kholia/OSX-KVM to have it running on KVM. This should be enough for our build requirements.

**Comment by EraYaN** [comment]
@anthonylavado Azure Pipelines has macOS machines, we can use those. No need for questionable legality virtualization.

**Comment by DrPandemic** [comment]
I didn't see it like that, you are totally right. Let's avoid Mac virtualisation.
