### ISSUE TITLE
Move to Jellyfin organization signing keys

### ISSUE THREAD

**Issue by JustAMan** [jellyfin/jellyfin#150]
RIght now at least Debian repo is signed by Joshua personal key.
We probably want to eventually move to a organization-owned keys.

**Comment by joshuaboniface** [comment]
This is really just a matter of renaming the key. I can do that later today.

**Comment by JustAMan** [comment]
I also think that private key should be stored somewhere accessible to other admins, so that it's reproducible not only on your boxes.

**Comment by joshuaboniface** [comment]
Yup, this was a quick solution. I'll do up a repo management doc for us so we can run multiple mirrors.

**Comment by joshuaboniface** [comment]
Keys have been prepped - I found that you can't rename a key, so I had to generate a new one.
