### ISSUE TITLE
NSIS based installer

### ISSUE THREAD

**Issue by crankdoofus** [jellyfin/jellyfin#1506]
**Is your feature request related to a problem? Please describe.**
The current windows installer is clunky and ugly. Looking for installer batch file after unzipping is not very user friendly.

**Describe the solution you'd like**
An elegant native windows gui based installer using NSIS at this stage.

**Describe alternatives you've considered**
None yet. 

**Additional context**

**Comment by EraYaN** [comment]
Might want to look at WiX a bit or even try out MSIX, since NSIS I think is a pain to work with. And MSIX seems to be "the way forward". (And MS MIT licensed it) AND it seems to also work on mac/linux? https://github.com/microsoft/msix-packaging

**Comment by oddstr13** [comment]
I've got a working installer going; [Jellyfin-Server-10.3.5-setup.exe](https://thoas.feralhosting.com/oddstr13/jellyfin/installer/Jellyfin-Server-10.3.5-setup.exe)

It's built using [Syrup](https://github.com/OpenShell-no/syrup), a program I made a few months back for another project.

I see you mentioned working on it in the forum thread, and I'm sorry if I've duplicated your effort on this.

I've not yet integrated it into the build system, but the steps I took to produce this installer is the following;
 * Download the release zip [jellyfin_10.3.5_windows-x64.zip](https://github.com/jellyfin/jellyfin/releases/download/v10.3.5/jellyfin_10.3.5_windows-x64.zip) and unzip to `src/`
 * Download the logo [icon-transparent.svg](https://github.com/jellyfin/jellyfin-ux/blob/master/branding/SVG/icon-transparent.svg) and render as a comfortably large `icon-transparent.png` using Inkscape
 * Download the [license](https://raw.githubusercontent.com/jellyfin/jellyfin/master/LICENSE) and convert line endings to `CRLF (Windows)`

**Finally, the command**
`syrup build --version=10.3.5 --name="Jellyfin Server" --company=Jellyfin --description="The Free Software Media System" --license=LICENSE --icon=icon-transparent.png --executable=jellyfin.exe --help-url="https://github.com/jellyfin/jellyfin/issues" --update-url="https://github.com/jellyfin/jellyfin/releases" --website-url="https://jellyfin.github.io/"`
**produces the setup file in** `artifacts/`

This should be fairly simple to integrate into the existing build scripts, by installing `nsis>=3.04`, `python3` and `python3-pip` in the docker image.

**Comment by crankdoofus** [comment]
> I've got a working installer going; [Jellyfin-Server-10.3.5-setup.exe](https://thoas.feralhosting.com/oddstr13/jellyfin/installer/Jellyfin-Server-10.3.5-setup.exe)
> 
> It's built using [Syrup](https://github.com/OpenShell-no/syrup), a program I made a few months back for another project.
> 
> I see you mentioned working on it in the forum thread, and I'm sorry if I've duplicated your effort on this.
> 
> I've not yet integrated it into the build system, but the steps I took to produce this installer is the following;
> 
> * Download the release zip [jellyfin_10.3.5_windows-x64.zip](https://github.com/jellyfin/jellyfin/releases/download/v10.3.5/jellyfin_10.3.5_windows-x64.zip) and unzip to `src/`
> * Download the logo [icon-transparent.svg](https://github.com/jellyfin/jellyfin-ux/blob/master/branding/SVG/icon-transparent.svg) and render as a comfortably large `icon-transparent.png` using Inkscape
> * Download the [license](https://raw.githubusercontent.com/jellyfin/jellyfin/master/LICENSE) and convert line endings to `CRLF (Windows)`
> 
> **Finally, the command**
> `syrup build --version=10.3.5 --name="Jellyfin Server" --company=Jellyfin --description="The Free Software Media System" --license=LICENSE --icon=icon-transparent.png --executable=jellyfin.exe --help-url="https://github.com/jellyfin/jellyfin/issues" --update-url="https://github.com/jellyfin/jellyfin/releases" --website-url="https://jellyfin.github.io/"`
> **produces the setup file in** `artifacts/`
> 
> This should be fairly simple to integrate into the existing build scripts, by installing `nsis>=3.04`, `python3` and `python3-pip` in the docker image.

Hey @oddstr13 , 
Thanks for sharing this. I'll give it a look.
For now, I've created a nsi script file and updated the build script to download nsis on the fly and compile the installer. I'm sure something similar can be done using method you've mentioned. It doesn't have any other dependencies and can be used by passing the appropriate flag to the build.
I've tried to include the basics for now and kept it as close to install script. Have a look at the PR (https://github.com/jellyfin/jellyfin/pull/1511) and I'll be happy to hear your comments.

**Comment by crankdoofus** [comment]
> Might want to look at WiX a bit or even try out MSIX, since NSIS I think is a pain to work with. And MSIX seems to be "the way forward". (And MS MIT licensed it) AND it seems to also work on mac/linux? https://github.com/microsoft/msix-packaging

Hey @EraYaN, 
Based on comment from @anthonylavado [here ](https://forum.jellyfin.org/t/nsis-based-windows-installer/466), I believe there is long term plan to use .NET Core 3 based packaging. 
I have worked with NSIS before, and I agree that each of the installers have their pros/cons. I feel NSIS is pretty easy to pick up and does plenty for the usage that we need today. It may not be a perfect solution but its better than what we have now (Terrible Jellyfin Installer).
