### ISSUE TITLE
Jellyfin showing up though content is empty?

### ISSUE THREAD

**Issue by Headhunter1231994** [jellyfin/jellyfin#1507]
Hi,

I'm trying to use Jellyfin on my  Samsung UE32H5500. (Win 10 is the platform.) The tv most of the time detects the server though the content is empty. While in the web interface, everything shows just fine.

Can someone help me?

Thanks!

Jordi

**Comment by anthonylavado** [comment]
Hey there! What app are you using on the TV?

**Comment by Headhunter1231994** [comment]
@anthonylavado the regular dlna feature on my tv. No other app. As in Samsubg Smart Hub>Network devices.

**Comment by 97carmine** [comment]
Have you tried another DLNA client such as VLC from a smartphone or PC?

**Comment by anthonylavado** [comment]
I think there are some fixes for this in 10.4, but I'd have to check.

**Comment by JustAMan** [comment]
Please update Jellyfin to 10.4.0 and re-check, it might be fixed.

**Comment by shiyouganai** [comment]
Hello, adding to this issue with my experience:
Jellyfin 10.4.1 (ARM)
Samsung UN48J6200
The TV detects the server, however no files are shown (empty). Web interface works, using "play to" the TV from the web interface works. This seems pretty much identical to the original report.

Is there any instruction for enabling and reading the DLNA logs?

**Comment by JustAMan** [comment]
@shiyouganai do you have non-empty base url set in Jellyfin (it was auto-set in 10.4.0, so you might not now it)? Please check and set it to empty if you don't use it, and check DLNA again.
