### ISSUE TITLE
Get Jellyfin listed on my.hdhomerun.com 3rd Party apps list

### ISSUE THREAD

**Issue by SenorSmartyPants** [jellyfin/jellyfin#1509]
**Is your feature request related to a problem? Please describe.**

Get listed along side other PVR apps on http://my.hdhomerun.com/

**Describe the solution you'd like**

Get Silicion Dust to link instructions on using HDHR with JF.

**Additional context**

This would help raise awareness of JF

**Comment by anthonylavado** [comment]
I do our Dev/Partner outreach, so I’ll look into this. Thanks!

**Comment by anthonylavado** [comment]
I've sent them an e-mail.
