### ISSUE TITLE
Hide thumbnails and titles for unseen episodes

### ISSUE THREAD

**Issue by sfkpmr** [jellyfin/jellyfin#1510]
**Describe the feature you'd like**
A feature that replaces thumbnails for unseen episodes with some sort of generic Jellyfin thumbnail, and either removes the titles, or renames them "unseen".

**Additional context**
Unseen episodes can often have thumbnails and titles that give away spoilers, such as a dead character appearing in a thumbnail giving away that they weren't really dead.

**Comment by oddstr13** [comment]
Same with episode summaries/description.
