### ISSUE TITLE
[Request] Set max concurrent stream limit, or total transcode limit.

### ISSUE THREAD

**Issue by sudodrew** [jellyfin/jellyfin#1526]
**Describe the feature you'd like**
For those of us with slower machines and internet, it would be great to be able to limit how many streams or users can be on at the same time.

1) Limit max concurrent streams per user
2) Limit max streams for entire server
3) Limit max transcodes per user
4) Limit max transcoes per server

**Additional context**

**Comment by anthonylavado** [comment]
Semi related to #1044.
