### ISSUE TITLE
Playback Error No Compatible Stream - Strange permissions

### ISSUE THREAD

**Issue by anihex** [jellyfin/jellyfin#1529]
**Describe the bug**
When revoking access to a library, it can affect other libraries as well.

**To Reproduce**
1. Add some libraries with content
2. Create at least 2 different users
3. Revoke access for a user on a library
4. Login as limited user
5. Try playing files from available libraries
6. It may tell you, there are no Compatible Streams

**Expected behavior**
In my instance I have 3 libraries:

- TV Series
- Movies
- Music

I've added a new user that can't access the movies - all other libraries are still accessable. Now he can't play music either. If he tries, he get's the message, there are no compatible streams.

Once I grant acces to `All libraries` it works again. )I tried the transcoing seetings too, no affect whatsoever.)

Also: While the limited user can see the artists and their albums, he can't see any title within. This is consistent with the message in the log. Strange however is, that the "Quick Mix" still works. But that's the only working button.

**Logs**
Admin-Access to everything:
```
[17:06:46] [INF] Playback stopped reported by app Jellyfin Web 10.3.5 playing Holodeck 4. Stopped at 176013 ms
[17:06:53] [INF] User policy for davyz. EnableAudioPlaybackTranscoding: False
[17:06:53] [INF] User policy for davyz. EnableAudioPlaybackTranscoding: False
[17:06:53] [INF] Setting range response values for /media/music/Das Modul/Urlaub Auf Der M.S. DOS (1996)/01 - Bootsektor.opus. RangeRequest: bytes=0- Content-Length: 5108951, Content-Range: bytes 0-5108950/5108951
```

Limited user
```
[17:08:54] [WRN] chris is not permitted to access Library Urlaub auf der M.S.DOS.
```

**System (please complete the following information):**
Docker (`docker version`)
```
Client:
 Version:           18.09.7-ce
 API version:       1.39
 Go version:        go1.12.6
 Git commit:        2d0083d657
 Built:             Tue Jul  2 01:00:04 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.7-ce
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.12.6
  Git commit:       2d0083d657
  Built:            Tue Jul  2 00:59:35 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

Linux: (`uname -a`)
```
Linux archlinux 5.1.15-arch1-1-ARCH #1 SMP PREEMPT Tue Jun 25 04:49:39 UTC 2019 x86_64 GNU/Linux
```

 - Browser: Firefox 67, Chromium 75.0.3770.90 ]
 - Jellyfin Version: Version: 10.3.5
 - Reverse proxy: nginx 1.16.0

**Comment by nonplusnl** [comment]
Having the same issue; only granting access to all libraries works. 
10.3.5 on Ubuntu 18.04 and Apache reverse proxy.
Experiencing the issue via web (Chrome and Edgium), and in Jellyfin Android app

**Comment by anihex** [comment]
I actually found a workaround to this issue. Two in fact. But none is a real good idea.

Workaround 1: Limit Access by using Tags. In "Parental Control" you can add a Tag to "Block items with tags". Afterwards you can add the tag to the library. This is not exactly a good workaround, since they can still access files within, if they have the link to it.

"Example Movie" in the lib "Movies" would still be accessible if the user has the URL to it.

Workaround 2: Using the "Maximum allowed parental rating". Just  limit the age limit at max e.g. "FSK-16". Now you can custom rate the lib at 18+ - even if it doesn't contain adult content.
This works better than Workaround 1 since the access to these files will be blocked completely. Even if the user has the URL to "Example Movie".

**Comment by NoShinSekai** [comment]
I have a very similar bug, but for me it's only with Collections, Music, and eBooks librairies. so, if the limited user has only access to some movie, or a TV show library, Everything is fine. I'm running on Windows Server + NGINX Reverse proxy and Jellyfin 10.3.6.

**Comment by anihex** [comment]
Since it seemed like this bug isn't important enough, I decided to take a look myself.
Turns out, it's a bug that was supposed to be fixed. (#1347). This should have been fixed with PR #1394.

And as pointed out at https://github.com/jellyfin/jellyfin/pull/1394#issuecomment-507908325 this will be fixed in 10.3.6.

Seems like I need to check this.

**Comment by anihex** [comment]
After upgrading to 10.3.6 the problem no longer occured for me. @NoShinSekai since you had this problem with 10.3.6, could you give me an example? Maybe I can look into it.

**Comment by joaojotta** [comment]
I am still having this issue in 10.3.7 and I'm using both a user with access limitations (but not libraries) as well as the admin user (unless there's a root user I don't know about).

**Comment by Ikaros1264** [comment]
In the ffmpeg-transcode.txt:
Failed to set value '/dev/dri/renderD128' for option 'vaapi_device': Invalid argument
Error parsing global options: Invalid argument

**Comment by JustAMan** [comment]
@Ikaros1264 what ffmpeg version you have and what installation type you use - docker or in "normal" OS?

**Comment by Ikaros1264** [comment]
I used the command 'apt-get install jellyfin'

**Comment by JustAMan** [comment]
You seem to be hi-jacking a seemingly unrelated issue, please open a new one following our template.
