### ISSUE TITLE
Addon or Section for Games 

### ISSUE THREAD

**Issue by michaelantonio** [jellyfin/jellyfin#1530]
Since the application faces to continue developing a good option and it would be the best thing to be able to have a complement of local game section or in the cloud, and to have a graphical interface such as **Retroarch** together with **LaunchBox Big Box**, which would make a fantastic experience for the players and it would be an opportunity for the application to revalidate to the other similar applications

**Comment by Xerrion** [comment]
I think this wouldn't make sense since Jellyfin is a "Media System", and not a Media/Software System.

**Comment by anthonylavado** [comment]
We removed the Emby games support several months ago, and don’t have plans to put it back in at this time.

More info here: https://github.com/jellyfin/jellyfin/issues/593

If someone wanted to bring back the collection type through a plug-in, that’s fine. The team here just mostly doesn’t believe it’s the best match up though.
