### ISSUE TITLE
Library Scan Hangs forever

### ISSUE THREAD

**Issue by Motophan** [jellyfin/jellyfin#1531]
Ubuntu LTS linuxserver docker image jellyfin 10.3.5

What will happen if it will get stuck at a certain percent and never progress further. It won't tell me what file is having difficulty identifying, it will silently sit doing nothing forever. I have to manually trigger rescan all libraries after figuring out what file is not properly identified to see any new files added since the last silent fail. 

Otherwise very good! 

https://pastebin.com/jMukpzR3

**Comment by cvium** [comment]
I see a couple of issues in that log. We need to add a null check here I guess https://github.com/jellyfin/jellyfin/blob/master/MediaBrowser.Providers/TV/TheTVDB/TvdbSeriesProvider.cs#L358

**Comment by Motophan** [comment]
Is there anything I can do on my end? Thanks for your response!

**Comment by Motophan** [comment]
I was talking to some of the developers on matrix and I have found a workaround for this problem, however this is not a fix. This is a temporary quick workaround that does not solve the underlying issue.

your log will unfortunately not tell you what show is hanging on, so you need to go to all of your libraries and find a show that doesn't have any cover art. click identify, and wait about a minute. If it loads forever that's the show that is hanging up your library. remove it, there is no other way that I know of to make jellyfin ignore it. You just have to delete it or move it outside what jellyfin can see. Rescan your library and if it hangs again do the same thing to the next show until it can complete a scan. 

A potential solution for this would be jellyfin to give up searching for files after 5 minutes or so, Mark that as failed, and continue down your library. Then extract pictures from the actual files, and blacklist scanning that specific folder for a week or something. This would make the scanner more robust and resilient to errors. My show it hung on was sanitized by sonarr renaming, and was a pretty popular show.

**Comment by deviousgeek** [comment]
Works fine here.

**Comment by dag420** [comment]
I tried to edit my original post.

Docker updated to 10.3.6 linuxserver container.
Host is Ubuntu 18.04 LTS

How to reproduce the bug: Add any of the following imdb titles that are known to cause the scanner to hang. When you click manually identify the page loads forever so you cannot set the information. Some shows setting the information is possible, but not on these and other titles. 

In my library the following titles cause the library to hang.
Imdb titles: tt0485301, tt0417299, tt0436992. 
When I try to manually identify them so the scanner will continue past these titles, it will say this in the logs: `
[02:09:21] [INF] Setting provider id's to item 3a84c0c2-b54d-84bf-b8ea-d9XXXXXd0-[showname redacted]: {"Tmdb":"6XXX2"}` where X's are redacted information

**Comment by CharlesCarnell** [comment]
Anything I can do to further help with this?

Would love to see this as a high-priority tofix.

**Comment by anthonylavado** [comment]
Right now, we need to figure out why any Of these titles would be hanging.

So, for anyone experiencing this issue, we’ll need information such as:
* name/IMDB ID of show with issue
* any log pieces around that show when trying to scan library
* what TV metadata providers you have enabled
* what language you have set for Jellyfin

This is mainly because we need to be sure just exactly what is being touched/what calls are being made, in order to troubleshoot.

**Comment by Motophan** [comment]
Provided logs to @anthonylavado and it does not appear to be a fixable issue. https://github.com/jellyfin/jellyfin/issues/1545?_pjax=%23js-repo-pjax-container is a duplicate issue. 

Only work around is continually rebooting container and identifying shows until a scan can complete. You can do 1-2 of them per reboot.

**Comment by anthonylavado** [comment]
There appear to be two parts to this.
1. A Network name is coming back as `null` from The TVDB, which fails to be added as a Studio
2. The scan hangs/crashes

In the logs, the only thing I can find as an error is the null issue. This issue I can replicate if needed, in certain circumstances. When I tried this, it did not stop scans, they proceeded as normal.

I have /some code to add the null check for the TV Studio item. I'm not sure if this causes the second issue, but we'll need to try it to see.

**Comment by anthonylavado** [comment]
From another contributor, some steps to try:
- In the TV Library settings, turn on Advanced Settings
- Try disabling The TVDB, and using TheMovieDB and The Open Movie Database
- For areas where TMDB or OMDB are not available, use any other provider (e.g. FanArt)

**Comment by anthonylavado** [comment]
To keep this issue updated, so far @Motophan has tested turning off The TVDB, and this appears to have worked. Obviously we'd like to have that extra metadata source on, but I would hesitate wanting to make anyone go through further testing unless they're comfortable doing so.

My PR for the nullcheck should be in soon, but it's easy enough to add to a test copy, if anyone wanted one.

**Comment by dag420** [comment]
I can configm TVDB set to off fixes this.

**Comment by JustAMan** [comment]
Is this still an issue in 10.4.0?

**Comment by evanfoster** [comment]
I'm hitting this issue with 10.4.2.

**Comment by JustAMan** [comment]
@evanfoster this is an old bug, most likely you're hitting https://github.com/jellyfin/jellyfin/issues/2059, please verify and report either there (if it seems the same to you) or create a new issue if it doesn't look the same as what you're seeing.

**Comment by evanfoster** [comment]
@JustAMan Awesome, thanks for the link! I'll go check that out.

**Comment by chuckofthenorth** [comment]
Not piling on, but in case it is helpful...   I can confirm I am seeing this same issue on version 10.4.2 running on Linux Docker:
**Host:** Kernel: 5.0.0-36-generic x86_64 bits (Peppermint 10)
**Docker version** 19.03.5, build 633a0ea838
**Image:** jellyfin/jellyfin:latest Digest: sha256:dce24426c4a2ea7770ad9a662482f21f606f0bce4ea50cf4bc4ac8f14d7eed78

I can confirm that trimming multiple space characters in all filenames helped it get further, but something else is still causing the issue. I also tried setting TVdb to the lowest priority in the tracker config, but it still stalls.  I don't see anything specific in the logs to help, but I'm still staring at them so if I do, I'll update.
