### ISSUE TITLE
Error downloading subtitles from "Open Subtitles"

### ISSUE THREAD

**Issue by ChnCdd** [jellyfin/jellyfin#1542]
Open Subtitles version : 3.0.0.0

> [2019-07-16 06:57:58.779 +00:00] [ERR] Error downloading subtitles from "Open Subtitles"
> System.MissingMethodException: Method not found: 'Void MediaBrowser.Common.Net.HttpRequestOptions.set_EnableHttpCompression(Boolean)'.
>    at OpenSubtitlesHandler.Utilities.SendRequestAsync(Byte[] request, String userAgent, CancellationToken cancellationToken)
>    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
>    at OpenSubtitlesHandler.Utilities.SendRequestAsync(Byte[] request, String userAgent, CancellationToken cancellationToken)
>    at OpenSubtitlesHandler.OpenSubtitles.LogInAsync(String username, String password, String language, CancellationToken cancellationToken)
>    at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.Login(CancellationToken cancellationToken)
>    at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.Search(SubtitleSearchRequest request, CancellationToken cancellationToken)
>    at MediaBrowser.Providers.Subtitles.SubtitleManager.<>c__DisplayClass11_0.<<SearchSubtitles>b__3>d.MoveNext()

The same error to https://github.com/jellyfin/jellyfin/issues/1424.
I try like that, cleared the username/password, saved it, and then re-added, can't work still.

**Comment by josephbeh** [comment]
same to me any master able save it?

**Comment by QYX-Ghost** [comment]
I got the same problem

**Comment by cvium** [comment]
Wrong repo. Please see https://github.com/jellyfin/jellyfin-plugin-opensubtitles/issues/8#issuecomment-514354080
