### ISSUE TITLE
Metadata (titles for seasons and episode names/description) Mismatch

### ISSUE THREAD

**Issue by Essasetic** [jellyfin/jellyfin#1543]
**Describe the bug**
On some shows (for some reason) the titles for seasons and episode description/title goes completely wrong. It grabs the right images and gets the right info for the actors. So I don't know what could cause this.

**To Reproduce**

NOTE: This is an issue with two shows I have. Which is the Office (US) and Regular Show.

1. Add show onto Jellyfin
2. Identify it/Refresh it's metadata
3. Wait for it to gather metadata.
4. See incorrect season titles/episode titles and descriptions for show.

**Expected behavior**

Season titles/episode titles and descriptions should be the same as what it is on the TVDB.
**Logs**

N/A

**Screenshots**

Unexpected behaviour
![bbf6216](https://i.redd.it/updj645mkna31.png)
Expected behaviour
![bbf6216](https://user-images.githubusercontent.com/34970796/61300628-3aa34b00-a7da-11e9-877c-ca8f8fb208cc.png)

**System (please complete the following information):**
 - OS: Docker
 - Browser: Vivaldi & Android
 - Jellyfin Version: 10.3.6
 - Reverse proxy: no

**Additional context**

N/A

**Comment by luke255** [comment]
I've found the same behaviour for The Office (US). I've discovered that thetvdb id is 73244 and the incorrect metadata is being pulled from this episode of an unrelated series which contains the same id in a different context: https://www.thetvdb.com/series/the-view/episodes/73244

**Comment by Mountaineer1024** [comment]
I suspect when scraping thetvdb, "the" is being dropped from the search title and then erroneous details are being returned.

I've witnessed problems with "The Good Place" and "The Boys".

**Comment by Essasetic** [comment]
Oddly, this got resolved in 10.3.7 for me. Might be TVDB updating or that it fixed a bug with scraping but it got the correct metadata for The Office (US) and Regular Show now. 

So in that case. I'll close the issue!
