### ISSUE TITLE
Error on upgrade to 10.3.6

### ISSUE THREAD

**Issue by daves00** [jellyfin/jellyfin#1544]
**Describe the bug**

I upgraded from the debian to the Ubuntu package. It all went smoothly until I encountered the followign issue during upgrade. I was controlling remotely and streaming to my Naim Uniti, stopped playback and then upgraded. I followed the installation instructions, and at the final stages got the error below. Since then I can play to devices EXCEPT the Naim Uniti.

Any help to resolve this issue much appreciated
 

Play to the Naim Uniti device remotely.
Stop playback
Follow the upgrade instructions for Ubuntu.

**Expected behavior**

Playback to Naim Uniti still functions

**Logs**

<details>
<summary>Click to View Logs</summary>

``` 
dave@nas01:/etc/apt/sources.list.d$ sudo service jellyfin status
● jellyfin.service - Jellyfin Media Server
   Loaded: loaded (/lib/systemd/system/jellyfin.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/jellyfin.service.d
           └─jellyfin.service.conf
   Active: active (running) since Tue 2019-07-16 19:24:16 BST; 49s ago
 Main PID: 4777 (jellyfin)
    Tasks: 18 (limit: 9313)
   CGroup: /system.slice/jellyfin.service
           └─4777 /usr/bin/jellyfin --restartpath=/usr/lib/jellyfin/restart.sh --ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg

Jul 16 19:24:38 nas01 jellyfin[4777]: [19:24:38] [ERR] Error updating device info for Uniti2-0D6C
Jul 16 19:24:38 nas01 jellyfin[4777]: MediaBrowser.Model.Net.HttpException: Bad Request
Jul 16 19:24:38 nas01 jellyfin[4777]:    at Emby.Server.Implementations.HttpClientManager.HttpClientManager.EnsureSuccessStatusCode(HttpResponseMessage response, HttpRequest
Jul 16 19:24:38 nas01 jellyfin[4777]:    at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMeth
Jul 16 19:24:38 nas01 jellyfin[4777]:    at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
Jul 16 19:24:38 nas01 jellyfin[4777]:    at Emby.Dlna.PlayTo.SsdpHttpClient.SendCommandAsync(String baseUrl, DeviceService service, String command, String postData, Boolean 
Jul 16 19:24:38 nas01 jellyfin[4777]:    at Emby.Dlna.PlayTo.Device.GetTransportInfo(TransportCommands avCommands, CancellationToken cancellationToken)
Jul 16 19:24:38 nas01 jellyfin[4777]:    at Emby.Dlna.PlayTo.Device.TimerCallback(Object sender)
Jul 16 19:24:44 nas01 jellyfin[4777]: [19:24:44] [INF] Check for plugin updates Completed after 0 minute(s) and 15 seconds
Jul 16 19:24:44 nas01 jellyfin[4777]: [19:24:44] [INF] ExecuteQueuedTasks
lines 1-20/20 (END)
``` 

</details>

**System (please complete the following information):**
 - OS: Ubuntu
 - Browser: Firefox - latest
 - Jellyfin Version:  10.3.6
 - Reverse proxy: none

**Comment by oddstr13** [comment]
This looks like it could be the content type bug in 10.3.6.
Could you try the 10.3.7beta1 build, and see if that fixes it?
```bash
wget https://repo.jellyfin.org/releases/server/ubuntu/versions/10.3.7b1/jellyfin_10.3.7-1_amd64.deb
sudo dpkg -i jellyfin_10.3.7-1_amd64.deb
```

**Comment by daves00** [comment]
Kapoow - That has worked - upgraded to the 10.3.7beta1

Awesome team Jellyfin! Thank you

**Comment by anthonylavado** [comment]
@daves00 Just for reference, 10.3.7 final is out, make sure you get it! :)

**Comment by daves00** [comment]
HI,

What is the best way to get 10.3.7.1 <final> to install over the top of the b1 i installed?

sudo apt update and then sudo apt install jellyfin is not applying any update - The message is 
N: Ignoring file je;;yfin_10.3.7-1_amd64.deb in directory /etc/apt/sources.list.d/ as it has an invalid filename extension

TIA

**Comment by anthonylavado** [comment]
@daves00 You can safely remove, then follow the regular install instructions for Debian/Ubuntu.

1. `sudo apt remove jellyfin`
2. https://jellyfin.readthedocs.io/en/latest/administrator-docs/installing/#ubuntu

(Go to the heading that reads “Repository”)
