### ISSUE TITLE
The media library scan has been stuck and cannot continue

### ISSUE THREAD

**Issue by ZhangTaihong** [jellyfin/jellyfin#1545]
当我尝试扫描媒体库的时候，它一直运行到85%左右就停止不工作了。我磁盘里的媒体无法全部扫描出来，并且刮削器也没有正常工作，已经尝试了好几次，都是这样。

-----Following from Google Translate------

When I tried to scan the media library, it stopped running until about 85% and stopped working. The media on my disk could not be scanned completely, and the scraper did not work properly. I have tried it several times, and it is like this.

**Comment by EraYaN** [comment]
Please do not ignore the issue template, please fill in all missing info. (Including log files)

**Comment by Motophan** [comment]
This is a duplicate issue of https://github.com/jellyfin/jellyfin/issues/1531 and there is no fix. This has been a bug since 9.3 without a fix.
