### ISSUE TITLE
Hardware transcoding fails on RPi 3

### ISSUE THREAD

**Issue by neilmusgrove** [jellyfin/jellyfin#1546]
**Describe the bug**
Jellyfin should be able to support hardware h264 transcoding on RPi via omx. This is built into the ffmpeg build produced for Jellyfin.
When testing it doesn't work and no video is displayed in the web interface. Disabling hardware encoding gets it working albeit slowly.

**To Reproduce**
When installed on Raspbian either natively or through Docker. Enable omx hardware encoding then try to stream with transcoding.

**Expected behavior**
Content should be transcoded with low cpu overhead

**Logs**
` [INF] /usr/lib/jellyfin-ffmpeg/ffmpeg -i file:"/path/1080p-h264.mp4" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_omx  -b:v 1276000 -maxrate 1276000 -bufsize 2552000 -force_key_frames "expr:gte(t,n_forced*3)" -vf "scale=trunc(min(max(iw\,ih*dar)\,720)/2)*2:trunc(ow/dar/2)*2" -copyts -vsync -1 -codec:a:0 copy -f segment -max_delay 5000000 -avoid_negative_ts disabled -start_at_zero -segment_time 3  -individual_header_trailer 0 -segment_format mpegts -segment_list_type m3u8 -segment_start_number 0 -segment_list "/var/lib/jellyfin/transcoding-temp/e35aceeb31f73db4f19422c6feed5426.m3u8" -y "/var/lib/jellyfin/transcoding-temp/e35aceeb31f73db4f19422c6feed5426%d.ts"
 [INF] FFMpeg exited with code 255`

**Screenshots**

**System (please complete the following information):**
 - OS: Raspbian Stretch on RPi 3
 - Browser: Firefox
 - Jellyfin Version: 10.3.6
 - Reverse proxy: no

**Additional context**

Let me know if I can provide any further information or testing. Thanks.

**Comment by EraYaN** [comment]
Please post the actual ffmpeg log. 255 (-1) is a generic exit code.

**Comment by neilmusgrove** [comment]
`/usr/lib/jellyfin-ffmpeg/ffmpeg -i file:"/path/1080p-h264.mp4" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_omx  -b:v 1276000 -maxrate 1276000 -bufsize 2552000 -force_key_frames "expr:gte(t,n_forced*3)" -vf "scale=trunc(min(max(iw\,ih*dar)\,720)/2)*2:trunc(ow/dar/2)*2" -copyts -vsync -1 -codec:a:0 copy -f segment -max_delay 5000000 -avoid_negative_ts disabled -start_at_zero -segment_time 3  -individual_header_trailer 0 -segment_format mpegts -segment_list_type m3u8 -segment_start_number 0 -segment_list "/var/lib/jellyfin/transcoding-temp/e35aceeb31f73db4f19422c6feed5426.m3u8" -y "/var/lib/jellyfin/transcoding-temp/e35aceeb31f73db4f19422c6feed5426%d.ts"


ffmpeg version 4.0.4 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18) 20170516
  configuration: --toolchain=hardened --prefix=/usr --target-os=linux --enable-cross-compile --extra-cflags=--static --enable-gpl --enable-static --disable-doc --disable-ffplay --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-libfontconfig --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libwebp --enable-libx264 --enable-libx265 --enable-libzvbi --enable-omx --enable-omx-rpi --enable-version3 --enable-vaapi --enable-vdpau --enable-cross-compile --cross-prefix=/usr/bin/arm-linux-gnueabihf- --arch=armhf
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'file:/path/1080p-h264.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    creation_time   : 2018-02-28T20:50:57.000000Z
    title           : 1080p-h264
    encoder         : Lavf57.83.100
    comment         : 1080p-h264
  Duration: 01:32:25.43, start: 0.000000, bitrate: 2730 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 2499 kb/s, 23.98 fps, 23.98 tbr, 11988 tbn, 47.95 tbc (default)
    Metadata:
      creation_time   : 2018-02-28T20:50:57.000000Z
      handler_name    : VideoHandler
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 224 kb/s (default)`

That's the end of the log. There doesn't appear to be a final error. It's the same every time I try it.

**Comment by EraYaN** [comment]
If you put your log between (three back ticks and a newline)
```
\`\`\` 
log text
\`\`\` 
```
it stops from putting emojis in the log and you get a nice formatted block. Please try the ffmpeg command in an ssh session, then you might also get the error on stderr, cause without it it's hard to say what went wrong.

**Comment by neilmusgrove** [comment]
```
[h264_omx @ 0x2a16b80] Using OMX.broadcom.video_encode
[segment @ 0x2a36e70] Opening '/var/lib/jellyfin/transcoding-temp/a1fbb820bdd87403d3ac8860531c4fa40.ts' for writing
[segment @ 0x2a36e70] Failed to open segment '/var/lib/jellyfin/transcoding-temp/a1fbb820bdd87403d3ac8860531c4fa40.ts'
Could not write header for output file #0 (incorrect codec parameters ?): Permission denied
Error initializing output stream 0:0 -- 
Conversion failed!
```
I tried playing with the parameters to isolate the problem but I'm not familiar enough with the construction of this more complex ffmpeg command to get it working.

**Comment by EraYaN** [comment]
It seems like it does not have write access to the `transcoding-temp` directory.

Also seeing the ffmpeg.c source code code 255 should only be returned when the program got a SIGTERM signal, it seems.

**Comment by neilmusgrove** [comment]
> It seems like it does not have write access to the `transcoding-temp` directory.

It reads like that, however the permissions on that folder look correct and transcoding without HW acceleration works and writes to that folder. It's not fast enough to keep up though.

**Comment by neilmusgrove** [comment]
Aah, my mistake. When I was running the command to test it I wasn't running as the right user (the jellyfin user). Rerunning as jellyfin gives:
```
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (h264_omx))
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
* failed to open vchiq instance
```

**Comment by neilmusgrove** [comment]
Right, that error is because the jellyfin user wasn't in the video group. Solved with:
```sudo usermod -a -G video jellyfin```
Not sure whether the raspbian packages can do this but imho it could do with either:

1. Done automatically
2. Some kind of message in the interface
3. Something in the docs

The first two are obviously bigger jobs and may encompass all types of hw enc. I'm happy to add a section to the docs regarding raspberry pi.

However it's still not a smooth playback because it's encoding at about 0.9x. I'll try and work out why that is because I think it should be faster than that.

**Comment by neilmusgrove** [comment]
Update. The issue now appears to be that Jellyfin is trying to resize the 1080p video to 640 pixels (that's my reading of the command) with
```
-vf "scale=trunc(min(max(iw\,ih*dar)\,640)/2)*2:trunc(ow/dar/2)*2"
```
This is testing on a remote connection with a slow speed coming from the server. Regardless of what settings i choose in the web browser the video is always resized. This vf is what slows the hardware encoding from 1.2x to 0.8x/0.9x. It looks like something is overriding the streaming settings specified in the web client.

I realise the pi3 is not a fast device but it will provide fast enough hardware transcoding with the right config which would be a great benefit to quite a few I think if we get it working. I will be looking at upgrading to a pi4 at some point and it will be interesting to see if this issue goes away.

**Comment by 0ddb0d** [comment]
It's slow because the decode and filtering (scaling) are done by the CPU.

For your next test add -c:v h264_mmal before your input and ditch the scaling, if that improves performance significantly then this might be worth pursuing.

**Comment by neilmusgrove** [comment]
Removing the scaling gives a big speed boost to around 1.2x. Strangely the hardware decoding h264_mmal (which I tested with the system ffmpeg because it's not enabled on the Jellyfin ffmpeg) seems to slightly slow encoding but not by much. It's difficult to say with certainty because there's a lot of variables however to me it looks like the transcoding would be fast enough for real time if there was no scaling being applied.

**Comment by JuliusFreudenberger** [comment]
I have tested hardware transcoding on a pi 4 4gb.
I experienced the same problem of no video showing up.
I can provide logs if needed.

**Comment by 0ddb0d** [comment]
That's a known ffmpeg issue https://trac.ffmpeg.org/ticket/8018 and unrelated to the problem being discussed here.

**Comment by JuliusFreudenberger** [comment]
Oh, sorry then.
But thank you for pointing me to the right issue!

**Comment by ferferga** [comment]
Are you running these commands using the ffmpeg bundled in the system or Jellyfin's own? Remember that Jellyfin includes its own version of ffmpeg (which isn't compiled with mmal, I'm trying to sort that out already)

**Comment by neilmusgrove** [comment]
Sorry, i don't have the Jellyfin on pi setup anymore so can't provide any more details. I bought an Intel chip device with QuickSync which obviously is far superior albeit more expensive. As far as i know the issue is that Jellyfin was forcing a resize rather than just a transcode, the pi can do the latter in hardware but struggles with the former on the cpu. A possible solution might be more fine-grained control of transcoding settings where you can choose the bitrate and size independently. Happy for you to close the issue if you think it's limited in impact.

**Comment by giejay** [comment]
I'm also trying to set hardware acceleration on my rpi3 but I can't seem to find the driver which I'm supposed to be using.

sudo lshw -c video

Gives me no results at all, when I enter the command without filtering for video, I don't see a gpu config. Did I somehow disable my gpu?

**Comment by ferferga** [comment]
@giejay You must use OpenOMX. That's what you mean?

You have the documentation under https://jellyfin.org/docs/general/administration/hardware-acceleration.html

**Comment by giejay** [comment]
@ferferga Yes, but my OS (Hypriot) was missing the HWA libraries in it's kernel. Yesterday I installed another OS (Raspbian), and now I have the missing library/device. Now the only thing is having a proper ffmpeg library, the current docker image doesn't ship the jellyfin one: https://github.com/jellyfin/jellyfin/issues/2126
