### ISSUE TITLE
Preserve Date Added On Rename

### ISSUE THREAD

**Issue by eglia** [jellyfin/jellyfin#1549]
I use Radarr to automatically download movies. One of its features is to upgrade existing media to higher quality, e.g. from 720p to 1080p. When doing this, it deletes the old file and then adds the new one. This causes Jellyfin to scan the new file into the library and resetting the date added. The upgraded movie now shows up in first position of the "Latest Movies" section on the home page. The same behaviour can be observed by simply renaming the file.

It would be nice if Jellyfin could preserve the date added of a movie if it was already in the database.

**Comment by oddstr13** [comment]
I think this makes sense for the DB rework
