### ISSUE TITLE
repo

### ISSUE THREAD

**Issue by penfolduk** [jellyfin/jellyfin#155]
repo not working

sudo apt install jellyfin
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package jellyfin

**Comment by DoctorMacc** [comment]
Did you add the package repository as mentioned in the Readme?

**Comment by penfolduk** [comment]
yeh that failed as well


Ign https://repo.jellyfin.org buster/main Translation-en_US
Ign https://repo.jellyfin.org buster/main Translation-en
W: Failed to fetch https://repo.jellyfin.org/debian/dists/buster/main/binary-amd64/Packages  gnutls_handshake() failed: Handshake failed

W: Failed to fetch https://repo.jellyfin.org/debian/dists/buster/main/binary-i386/Packages  gnutls_handshake() failed: Handshake failed

E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by penfolduk** [comment]
get Welcome to nginx! when click on repo URL

**Comment by penfolduk** [comment]
ubuntu 14.04.5 LTS

**Comment by penfolduk** [comment]
am using a vps server

**Comment by joshuaboniface** [comment]
@penfolduk Can you try it now and let me know? If it still doesn't work, please post the exact contents of your repo `.list` file and a test of `curl -v https://repo.jellyfin.org/debian/dists/buster/main/binary-amd64/Packages && date ` via a pastebin please, as that will help troubleshoot. 14.04 isn't that old so I'd like to make sure it works!

**Comment by thejacer87** [comment]
> 14.04 isn't that old so I'd like to make sure it works!

well LTS for it ends in 4 months... so it might not be crucial to support going forward IMO

**Comment by joshuaboniface** [comment]
Thought it was 5 years not 4, in that case it may be prudent to upgrade anyways @penfolduk , but I'm curious if this helps. In short I re-enabled SSLv3 support and ALL ciphers for the latest NGiNX so that should let slightly older systems work normally. I still get an A rating on the [SSLLabs site test](https://www.ssllabs.com/ssltest/index.html) so it's still quite secure.

**Comment by thejacer87** [comment]
it is 5 years....

14.04 release april 14, support end april 19

**Comment by penfolduk** [comment]
https://pastebin.com/Zp7dPUCq

**Comment by penfolduk** [comment]
apt update is fine now

**Comment by joshuaboniface** [comment]
Perfect, thanks for confirming. Closing this one out.

**Comment by penfolduk** [comment]
but
 get this on install


root@flussonic:~# sudo apt install jellyfin
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 jellyfin : Depends: ffmpeg but it is not installable
E: Unable to correct problems, you have held broken packages.
root@flussonic:~# sudo apt install jellyfin
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 jellyfin : Depends: ffmpeg but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by joshuaboniface** [comment]
Jellyfin depends on ffmpeg, so that package needs to be installed. It was removed from 14.04 for some reason, but tthis guide shows how to get it installed: https://www.faqforge.com/linux/how-to-install-ffmpeg-on-ubuntu-14-04/

**Comment by JustAMan** [comment]
Btw Ubuntu 16.04 has libav disguised as ffmpeg (found it out today in a hard way)... We may want to ship our own ffmpeg that is nee enough and is known to support all the switches we throw at it.

**Comment by joshuaboniface** [comment]
Ulgh damn you Canonical. I don't pike the idea of including our own since I'm sure we'll inevitibly get a "why does feature X not work" if we build it in strict GPL mode, which we'd have to. Do the later Ubuntus still do the same thing with `libav`? If not we can just add that PPA as part of the install guide.

**Comment by JustAMan** [comment]
I don't think they did, at least I cannot find a word about that. 
Though ffmpeg devs list official ppa's for Ubuntu at ffmpeg.org, so we can point people there.
