### ISSUE TITLE
Downloading media should preserve relative file path

### ISSUE THREAD

**Issue by uchagani** [jellyfin/jellyfin#1554]
**Describe the bug**
When you download media, the download files goes in the default download directory of the browser.  While this is fine, it would be better if the directory structure was preserved so episodes from two different series don't end up in one place.

**To Reproduce**

1. Go to a TV episode
2. Click on `...`
3. Click Download
4. Go to another TV episode
5.  Click on `...`
6.  Click Download
7.  Check download folder

**Expected behavior**
Episodes from different series should end up in their own directory to prevent similarly named files to end up in the same place.

**Screenshots**

**System (please complete the following information):**
 - OS: Ubuntu 19.04
 - Browser: Chrome
 - Jellyfin Version: 10.3.6
 - Reverse proxy: none

**Additional context**
I made this a bug instead of a feature request since downloading two files named the same might overwrite one another without preserving file paths.

**Comment by RazeLighter777** [comment]
AFAIK there is no way to specify a download path from an application, instead this must be done manually in the browser settings, unless the episodes were somehow combined in a zip archive or such.

**Comment by uchagani** [comment]
Could we show a SaveAs path dialog? This would allow the user to choose
their save location and if I remember correctly, the SaveAs location is
remembered by the browser for subsequent saves so that would help in saving
multiple files to the same location.

**Comment by LogicalPhallacy** [comment]
Can you not right click "save as" from your browser?

**Comment by EraYaN** [comment]
For browsers this is impossible without plugins. You will be better off configuring your browser to show you save as dialogs, although for downloading many files, you should just copy then straight for the original media storage.

**Comment by oddstr13** [comment]
The reason this is impossible to implement in jellyfin-web is due to sandboxing (security restrictions) in the browser. If Jellyfin could save files to specific directories, then any old website could look thru your files.

**Comment by uchagani** [comment]
@LogicalPhallacy right clicking and select Save As will save the web page and not the media
