### ISSUE TITLE
media files changed,but not refresh  in time

### ISSUE THREAD

**Issue by toyqiu** [jellyfin/jellyfin#1561]
I've deploy jellyfin docker to my NAS for days. And I find that an episode has been downloaded for about 1 hour into the document which has been add to media-library of Jellyfin,but it didn't show up.

**Comment by oddstr13** [comment]
On the dashboard, under Expert -> Scheduled tasks, there is a task called "Scan media library"
![image](https://user-images.githubusercontent.com/638706/61818765-d3c50800-ae51-11e9-8768-1c1e0693adf9.png)

I've got this task set to run every 15 minutes, as directory watching doesn't work with my particular filesystem setup.

![image](https://user-images.githubusercontent.com/638706/61818846-0a028780-ae52-11e9-88dc-33269c6d9c77.png)
I think the default is once every 12 hours.

Can you check and see if running the task (clicking the triangle play button) makes the media show up in your library?
If so, you may want to change the media scan interval to something lower.

**Comment by toyqiu** [comment]
> On the dashboard, under Expert -> Scheduled tasks, there is a task called "Scan media library"
> ![image](https://user-images.githubusercontent.com/638706/61818765-d3c50800-ae51-11e9-8768-1c1e0693adf9.png)
> 
> I've got this task set to run every 15 minutes, as directory watching doesn't work with my particular filesystem setup.
> 
> ![image](https://user-images.githubusercontent.com/638706/61818846-0a028780-ae52-11e9-88dc-33269c6d9c77.png)
> I think the default is once every 12 hours.
> 
> Can you check and see if running the task (clicking the triangle play button) makes the media show up in your library?
> If so, you may want to change the media scan interval to something lower.

thank you!

I mean,when I use plex,when an episode downloaded into the document,in minutes,it shows in the library.I prefer this rather than have all my library been updating  maybe 30-minutes rather intervals.

I've got really a lot of episodes and movies to manage and still be downloading new ones.

**Comment by anthonylavado** [comment]
We'll need to look into how we detect changes in the filesystem.

**Comment by toyqiu** [comment]
@anthonylavado 
> We'll need to look into how we detect changes in the filesystem.

YES! That's all I look forward to,for now.

**Comment by anthonylavado** [comment]
@toyqiu Just for reference here, what filesystem is used on your NAS?

**Comment by toyqiu** [comment]
@anthonylavado synology 216+ii  I think it's linux.
