### ISSUE TITLE
There is no "Folders" view option in Movies library

### ISSUE THREAD

**Issue by stiw47** [jellyfin/jellyfin#1563]
Hi guys. First of all, thanks for great open source and free media center. Not really issue and not sure is this real place (so please feel free to close/delete, etc.), but since this is a fork of Emby, I have to notice that "Folders" view is missing when I open Movies content type library. Why?
I'm talking about last option in top bar, right after Movies, Suggestions, Trailers, Favorites, Collections, Genres, [missing]Folders.
If this is important :) I am already Emby user and have a big library of 600+ cartoons for my and my friends children in our language (mostly long movie-cartoons). It is cool to put it in Movies content type library because of pulling metadata from internet, but some of those are series and it is pretty messy if someone exploring library in any other view instead of Folders view.
I was really excited when I found Jellyfin one week ago, cause I'm sure that will be better and better through the time and I don't need to worry which personal video will put on my own server cause it is open source. From other side, how much long transcoding and similar will be free of charge on Emby?

Sorry for unneeded long post for such a simple question, but once again, I'm really glad that exist something like Jellyfin, but from other side really trifle thing (very important for me :) ) is stopping me to switch permanent to Jellyfin. And I think there is more people who missing Folder view inside Movies library, so these are some my impression and question: Why is missing/Could it be added?

Thanks a lot.

![folders](https://user-images.githubusercontent.com/3337416/61849788-18d15480-aebb-11e9-9987-58531ac30ba6.jpg)

**Comment by anthonylavado** [comment]
> From other side, how much long transcoding and similar will be free of charge on Emby?
We never plan to charge for transcoding :-)

Regarding the folders view, it looks like this doesn't exist in the software. What version of Emby are you using? It may be something they added after the fork.

**Comment by stiw47** [comment]
Hi Anthony, thanks for your follow up. The Emby version is:

`[stiw47@archmedia ~]$ pacman -Qi emby-server
Name            : emby-server
Version         : 4.1.1.0-1
Description     : Bring together your videos, music, photos, and
                  live television
Architecture    : any
URL             : https://emby.media
Licenses        : custom
Groups          : None
Provides        : None
Depends On      : alsa-lib  aom  dotnet-runtime  fontconfig
                  fribidi  gmp  gnutls  lame  libass.so=9-64
                  libdrm  libfreetype.so=6-64  libjpeg-turbo
                  libmfx.so=1-64  libpng  libtheora
                  libva-drm.so=2-64  libva.so=2-64
                  libva-x11.so=2-64  libvorbisenc.so=2-64
                  libvorbis.so=0-64  libwebp  libx11
                  libx264.so=157-64  opus  skia-sharp  sqlite
                  zlib  zvbi
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 79.90 MiB
Packager        : Maxime Gauduin <alucryd@archlinux.org>
Build Date      : Tue 30 Apr 2019 12:00:44 PM CEST
Install Date    : Tue 30 Apr 2019 10:42:26 PM CEST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature

[stiw47@archmedia ~]$`

**Comment by anthonylavado** [comment]
@stiw47 I read up on it more, and this is indeed something they added after the fork, in 4.1 or so. This means we would have to create this function, it's not just something hidden.

**Comment by stiw47** [comment]
Cool then. Sorry for my mistake, didn't knew this. Thanks for your follow up again and thanks in advance if this function have been added in future.

**Comment by anthonylavado** [comment]
@stiw47 I have added it to our feature requests, if you’d like to vote for it :-)

https://features.jellyfin.org/posts/224/add-a-folder-view-to-libraries

**Comment by stiw47** [comment]
Thanks a lot, my man :) , already voted.

**Comment by wu-lee** [comment]
> @stiw47 I have added it to our feature requests, if you’d like to vote for it :-)
> 
> https://features.jellyfin.org/posts/224/add-a-folder-view-to-libraries

I've voted. There are a massive number of votes for this there now.

**Comment by mrx23dot** [comment]
Yeah it would be time to implement it after 2years :D

**Comment by stiw47** [comment]
:)

**Comment by SudoNova** [comment]
Guys this is important to have a metadata manager, as some (e.g. podcats) that are created by a third person might have not handled it well. Folder view is a nice good to have remedy, but my vote goes for metadata manager.

**Comment by cryptonoise** [comment]
This is the necessary function of all. Now 2023, and it is not implemented (
