### ISSUE TITLE
Kodi Sync Problem

### ISSUE THREAD

**Issue by NafiyX** [jellyfin/jellyfin#1565]
**Describe the bug**
New to Jellyfin, Please Help......
I running Jellyfin 10.3.7 on Proxmox with Lxc, in the webUI 
everything is OK , But in Coreelec with newest kodi addon 
caching artwork is very slow and case kodi crash!!
i checked the log , in the server there is many [WRN] HTTP Response 200
and in the kodi with many error-ERROR:CCurlFile::Stat - Failed: Timeout was reached
i try to disable the Secure connection in the server, but no luck

**System (please complete the following information):**
 - OS: ProxmoxVE,LXC,Unbuntu18.04
 - Browser: [e.g. Firefox, Chrome, Safari]
 - Jellyfin Version: 10.3.7
 - Reverse proxy: no,Lan
 - Coreelec: 9.02

**Logs**
[Jellyfin_Log.txt](https://github.com/jellyfin/jellyfin/files/3436877/Jellyfin_Log.txt)
[kodi_crashlog_20190726164545.log](https://github.com/jellyfin/jellyfin/files/3436878/kodi_crashlog_20190726164545.log)

**Comment by JustAMan** [comment]
Are you using "Jellyfin for Kodi" addon?
