### ISSUE TITLE
[Bug/Suggestion] E-Books Issues

### ISSUE THREAD

**Issue by Z3ROGRAV1TYx** [jellyfin/jellyfin#1566]
So, basically if you have an Book library, I'm not seeing any option to actually read the books. They come up but they don't have any play button or anything.

Ontop of this, it doesn't recognize common archive formats (Such as zip and cbz which are used for Manga and Doujins very often). Normally with most readers (MComix for example) you can just open the zip or cbz file and it opens properly no problem. On Jellyfin, these don't even show up. Jellyfin only seems to detect Epub files and such.

**Comment by anthonylavado** [comment]
Sadly, this isn't as much of a bug as it is a known issue which needs enhancement.

The book support isn't changed any from how we got it in the Emby 3.5.2 code, and as you mention, it doesn't include a reader.

It does recognize CBZ and CBR files, but as mentioned, there's no reader. You can pretty much just choose to download it.

We have some more requests in #569, but I'll keep this open until I can merge them.
