### ISSUE TITLE
Raspberry Pi support

### ISSUE THREAD

**Issue by FaZeBase** [jellyfin/jellyfin#157]
Are you planning to release docker images or packages to the Raspberry Pi ?

**Comment by JustAMan** [comment]
Eventually yes. I don't know if the has started already - so many volunteers... Maybe you can try and make a raspberry package? :)

**Comment by joshuaboniface** [comment]
Integrated builds have been completed. Step two is to set up an ARM test infrastructure and modify the build scripts accordingly.

**Comment by FaZeBase** [comment]
Tried to build it but got into an error

Here is a snippet of the logs

`WebSocket.cs(48,26): warning CS0169: The field 'WebSocket._protocols' is never used [/repo/SocketHttpListener/SocketHttpListener.csproj]
WebSocket.cs(54,21): warning CS0169: The field 'WebSocket._uri' is never used [/repo/SocketHttpListener/SocketHttpListener.csproj]
WebSocket.cs(44,22): warning CS0169: The field 'WebSocket._nonceCount' is never used [/repo/SocketHttpListener/SocketHttpListener.csproj]
Net/HttpConnection.cs(39,13): warning CS0414: The field 'HttpConnection._timeout' is assigned but its value is never used [/repo/SocketHttpListener/SocketHttpListener.csproj]
LinuxIsoManager.cs(147,38): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [/repo/Emby.IsoMounting/IsoMounter/IsoMounter.csproj]
SsdpDeviceLocator.cs(127,30): warning CS0168: The variable 'ex' is declared but never used [/repo/RSSDP/RSSDP.csproj]
SsdpDevicePublisher.cs(315,30): warning CS0168: The variable 'ex' is declared but never used [/repo/RSSDP/RSSDP.csproj]
DiscoveredSsdpDevice.cs(20,26): warning CS0414: The field 'DiscoveredSsdpDevice._Device' is assigned but its value is never used [/repo/RSSDP/RSSDP.csproj]
/usr/share/dotnet/sdk/2.2.100/Microsoft.Common.CurrentVersion.targets(1879,5): warning : The referenced project '../ThirdParty/taglib-sharp/src/taglib-sharp.csproj' does not exist. [/repo/Emby.Photos/Emby.Photos.csproj]
ImageProcessor.cs(301,48): warning CS0168: The variable 'ex' is declared but never used [/repo/Emby.Drawing/Emby.Drawing.csproj]
Playback/Progressive/AudioService.cs(14,7): warning CS0105: The using directive for 'MediaBrowser.Model.IO' appeared previously in this namespace [/repo/MediaBrowser.Api/MediaBrowser.Api.csproj]
Playback/StreamRequest.cs(18,21): warning CS0108: 'StreamRequest.Id' hides inherited member 'BaseEncodingJobOptions.Id'. Use the new keyword if hiding was intended. [/repo/MediaBrowser.Api/MediaBrowser.Api.csproj]
Playback/StreamRequest.cs(21,23): warning CS0108: 'StreamRequest.MediaSourceId' hides inherited member 'BaseEncodingJobOptions.MediaSourceId'. Use the new keyword if hiding was intended. [/repo/MediaBrowser.Api/MediaBrowser.Api.csproj]
Playback/StreamRequest.cs(24,23): warning CS0108: 'StreamRequest.DeviceId' hides inherited member 'BaseEncodingJobOptions.DeviceId'. Use the new keyword if hiding was intended. [/repo/StripCollageBuilder.cs(211,69): warning CS0612: 'SKBitmapResizeMethod' is obsolete [/repo/Emby.Drawing.Skia/Emby.Drawing.Skia.csproj]
StripCollageBuilder.cs(211,33): warning CS0618: 'SKBitmap.Resize(SKBitmap, SKBitmapResizeMethod)' is obsolete: 'Use ScalePixels(SKBitmap, SKFilterQuality) instead.' [/repo/Emby.Drawing.Skia/Emby.Drawing.Skia.csproj]
SkiaEncoder.cs(551,40): warning CS0612: 'SKBitmapResizeMethod' is obsolete [/repo/Emby.Drawing.Skia/Emby.Drawing.Skia.csproj]
SkiaEncoder.cs(553,21): warning CS0618: 'SKBitmap.Resize(SKBitmap, SKBitmapResizeMethod)' is obsolete: 'Use ScalePixels(SKBitmap, SKFilterQuality) instead.' [/repo/Emby.Drawing.Skia/Emby.Drawing.Skia.csproj]
SkiaEncoder.cs(561,29): warning CS0618: 'SKBitmap.Encode(SKWStream, SKEncodedImageFormat, int)' is obsolete: 'Use SKPixmap.Encode instead.' [/repo/Emby.Drawing.Skia/Emby.Drawing.Skia.csproj]
SkiaEncoder.cs(613,29): warning CS0618: 'SKBitmap.Encode(SKWStream, SKEncodedImageFormat, int)' is obsolete: 'Use SKPixmap.Encode instead.' [/repo/Emby.Drawing.Skia/Emby.Drawing.Skia.csproj]
PlayTo/Device.cs(505,30): warning CS0168: The variable 'ex' is declared but never used [/repo/Emby.Dlna/Emby.Dlna.csproj]
Manager/ProviderManager.cs(822,34): warning CS0168: The variable 'ex' is declared but never used [/repo/MediaBrowser.Providers/MediaBrowser.Providers.csproj]
Subtitles/SubtitleManager.cs(36,62): warning CS0067: The event 'SubtitleManager.SubtitlesDownloaded' is never used [/repo/MediaBrowser.Providers/MediaBrowser.Providers.csproj]
PhotoProvider.cs(13,7): error CS0246: The type or namespace name 'TagLib' could not be found (are you missing a using directive or an assembly reference?) [/repo/Emby.Photos/Emby.Photos.csproj]
PhotoProvider.cs(14,7): error CS0246: The type or namespace name 'TagLib' could not be found (are you missing a using directive or an assembly reference?) [/repo/Emby.Photos/Emby.Photos.csproj]
PhotoProvider.cs(15,7): error CS0246: The type or namespace name 'TagLib' could not be found (are you missing a using directive or an assembly reference?) [/repo/Emby.Photos/Emby.Photos.csproj]
PhotoProvider.cs(16,7): error CS0246: The type or namespace name 'TagLib' could not be found (are you missing a using directive or an assembly reference?) [/repo/Emby.Photos/Emby.Photos.csproj]
    64 Warning(s)
    4 Error(s)`

**Comment by FaZeBase** [comment]
Problem solved ! Pushing to Docker Hub

**Comment by FaZeBase** [comment]
Problem solved ! Pushing to Docker Hub

**Comment by joshuaboniface** [comment]
Oh nice! Yea I had a specific build reference to "linux-x64" but I take it that's fixed? Great news!

**Comment by FaZeBase** [comment]
Here ! You can get it here :

docker pull fzbasescu/jellyfinpie

**Comment by FaZeBase** [comment]
Yeah it didn't matter actually

**Comment by FaZeBase** [comment]
Yeah it didn't matter actually

**Comment by joshuaboniface** [comment]
Perfect, please feel free to do up a PR for the changes and we can make it part of the official builds!

**Comment by FaZeBase** [comment]
I just did one on the readme. Fell free to check it out

**Comment by joshuaboniface** [comment]
Perfect, can you add a description of how to build it as well? We want to automate all builds and that will help a lot!

**Comment by FaZeBase** [comment]
What I did is basically clone and build in my Pi. Problem was that TagLib wasn't cloned automatically and I manually did so and solved the issue.

**Comment by JustAMan** [comment]
Hmm, ideally we should have cross-build support for that... I don't think we'll be building releases on RPi-s.

**Comment by FaZeBase** [comment]
True but that should do at the moment

**Comment by FaZeBase** [comment]
Got cross-building  in DockerHub working

**Comment by nvllsvm** [comment]
Done
