### ISSUE TITLE
Docker image requires mesa-va-drivers package for VA-API transcoding on AMD

### ISSUE THREAD

**Issue by yesrod** [jellyfin/jellyfin#1587]
(I apologize if this is in the wrong place.  I couldn't decide if this was a bug because of a missing package, or a feature request because installing the package gets AMD VA-API transcoding working.  Please let me know and I'll move it to the feature request portal if needed.)

**Describe the bug**
Attempting to use VA-API transcoding in a Jellyfin 10.3.5 Docker container fails; when VA-API transcoding is enabled, and a user attempts to open a video that requires transcoding, the loading animation spins indefinitely.

Entering the docker container and using ```vainfo``` to query the status of VA-API on the system gives the following error:
```
root@jellyfin:/# vainfo --display drm --device /dev/dri/renderD128
libva info: VA-API version 1.1.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/r600_drv_video.so
libva info: va_openDriver() returns -1
vaInitialize failed with error code -1 (unknown libva error),exit
```

The ```r600_drv_video.so``` driver is provided by the ```mesa-va-drivers``` package.  After installing said package, vainfo provides information about the capabilities of the GPU, as expected:
```
root@jellyfin:/# vainfo --display drm --device /dev/dri/renderD128
libva info: VA-API version 1.1.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/r600_drv_video.so
libva info: Found init function __vaDriverInit_1_1
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.1 (libva 2.1.0)
vainfo: Driver version: Mesa Gallium driver 19.0.2 for AMD KAVERI (DRM 2.50.0, 4.19.0-0.bpo.5-amd64, LLVM 8.0.0)
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileNone                   : VAEntrypointVideoProc
```

In addition, after installing the ```mesa-va-drivers``` package in the Docker container, VA-API transcoding now works.  I confirmed that the GPU is being used to transcode by using ```radeontop``` on the host machine.

**To Reproduce**
1. Ensure that ```/dev/dri/renderD128``` and ```/dev/dri/card0``` are passed through to the Docker container by using the ```--device /dev/dri/renderD128 --device /dev/dri/card0``` options when running the container.
2. Go to 'Dashboard -> Transcoding'
3. Change the value in the 'Hardware Acceleration' dropdown to 'Video Acceleration API (VA API)(experimental)'
4. Select the 'Enable hardware encoding' checkbox.
5. Save the settings.
6. Attempt to play a video that requires transcoding for your client (or change resolution/rate in the web client settings to force transcoding).
7. The video will not play.  The loading animation spins indefinitely.

**Expected behavior**
It is expected that the video in question will be transcoded successfully and said video will play correctly when using VA-API transcoding on supported AMD hardware.

Installing the ```mesa-va-drivers``` package in the Docker container manually fixed the issue.

**System (please complete the following information):**
 - OS: Docker, via OpenMediaVault
 - Browser: Firefox 69.0b4 64-bit
 - Jellyfin Version: 10.3.5 (I will retest with the new 10.3.7 Docker container shortly to confirm)
 - Reverse proxy: none
 - Hardware: AMD A10-7870K APU with Radeon R7 GPU

**Comment by yesrod** [comment]
I can confirm that this package is still absent in the 10.3.7 Docker image, and that installing it manually still fixes the issue.

```
The following additional packages will be installed:
  libbsd0 libdrm-amdgpu1 libdrm-nouveau2 libdrm-radeon1 libedit2 libelf1 libllvm8 libx11-xcb1
  libxau6 libxcb-dri2-0 libxcb-dri3-0 libxcb-present0 libxcb-sync1 libxcb-xfixes0 libxcb1
  libxdmcp6 libxshmfence1 multiarch-support
The following NEW packages will be installed:
  libbsd0 libdrm-amdgpu1 libdrm-nouveau2 libdrm-radeon1 libedit2 libelf1 libllvm8 libx11-xcb1
  libxau6 libxcb-dri2-0 libxcb-dri3-0 libxcb-present0 libxcb-sync1 libxcb-xfixes0 libxcb1
  libxdmcp6 libxshmfence1 mesa-va-drivers multiarch-support
0 upgraded, 19 newly installed, 0 to remove and 30 not upgraded.
Need to get 16.1 MB of archives.
After this operation, 85.6 MB of additional disk space will be used.
```

**Comment by k1lln1n3** [comment]
I was able to get VAAPI working for my APUs without installing this package. Testing on 103.5 to 10.3.7, ensuring the proper permissions for the DRI device were in place, it worked fine. 

I'm wondering what device you're using so I can try and replicate this result. Let me know and ill try it out.

Also, could you try running the docker in a privileged mode to see if it will work without those libraries?

**Comment by yesrod** [comment]
My APU is an A10-7870K. 

I tried privileged mode with a previous docker container, but it didn't work at that time.  I can try again sometime in the near future when I get a moment.

At least for my system, the error message given by vainfo before I install that package is pretty definitive - the VA driver that it wants isn't present on the system.
