### ISSUE TITLE
Remove network handling

### ISSUE THREAD

**Issue by xoxys** [jellyfin/jellyfin#1591]
**Describe the bug**
I had some trouble getting a connection to a Jellyfin behind a reverse proxy with the android app. I had to enable external connections because the app try to get information from `/emby/System/Info/public` endpoint which does not work if external connections are not enabled. 

Anyway, I really dislike networking/firewalling/... stuff within an application, this should be handled by the network stack e.g. iptables, firewall or router because doing this in each application someone is running on a server would be a mess 😉

So what's the plan for the networking stuff? I see discussions about removing SSL handling in the GitHub issues. What do you think about simplifying the rest also and remove all these external/internal/restrictions networking stuff? Simply deliver HTTP content on a defined port/ip binding, no more magic.

I would like to discuss this but if you are happy with this setup feel free to close the issue.

**System (please complete the following information):**
 - Jellyfin Version: 10.3.7

**Comment by cvium** [comment]
The plan is to make it sane.

**Comment by xoxys** [comment]
And what does it mean?

**Comment by onny** [comment]
@xoxys I'm fine with the current implementation in Jellyfin. I think supporting port/ip filtering, ssl and other networking stuff is common practice for bigger standalone web applications, e.g. Gitlab, Emby, Plex, etc.
Further these settings are behind the Experts -> Advanced dialog and usually you don't have to touch them. At least in my reverse proxy configuration I didn't have to tweak that much.

Best regards,
Jonas

**Comment by xoxys** [comment]
@onny For me this is not very common and I've not seen it that often. As mentioned, if you have a more advanced setup things get complicated because you have to do steps twice. In my case I have to set some advanced settings to get the Android App working within my local Wlan because Wlan and Lan (which Jellyfin server is part of) are two different subnets.

If you're running Jellyfin with Docker you add a third network layer. That's the reason why it feels a bit odd to do networking stuff within an end user application.

But again, that was just a sharing of my opinion and experience :)

Best
Robert

**Comment by hawken93** [comment]
I still have the opinion that the IP field in the api is redundant and should be removed, and I don't know why it's there or what it solves.

**Comment by JustAMan** [comment]
We have added the ability to configure base URL, should be released in Jellyfin 10.4.1.
