### ISSUE TITLE
TVDB external links broken with TVDB v3 website

### ISSUE THREAD

**Issue by SenorSmartyPants** [jellyfin/jellyfin#1594]
**Describe the bug**

TVDB v2 links like https://www.thetvdb.com/?tab=episode&id=7223231 no longer bring up the expected episode page.

New links are formatted like this.
https://www.thetvdb.com/series/the-handmaids-tale/episodes/7223231

TVDB just launched v3 website. Perhaps they will fix this on their end.

**To Reproduce**

1. Go to a TV episode
2. Click on  TVDB link

**Expected behavior**

Link should go to correct details page.

**System (please complete the following information):**
 - OS: Docker
 - Browser: Chrome
 - Jellyfin Version: 10.3.7
 - Reverse proxy: no

**Comment by ThatNerdyPikachu** [comment]
Same thing with new images, posters, etc.

**Comment by anthonylavado** [comment]
So apparently they're aware, but have missed adding translators in for some formats.

https://forums.thetvdb.com/viewtopic.php?f=118&t=57574

**Comment by anthonylavado** [comment]
> Same thing with new images, posters, etc.

Apparently they were running an import overnight, so assuming that has cleared now, it's possible that this will be working again.
Ref: https://forums.thetvdb.com/viewtopic.php?f=118&t=57611

**Comment by anthonylavado** [comment]
To keep this updated again, they did perform a roll back some days ago:
https://forums.thetvdb.com/viewtopic.php?f=118&t=57711

**Comment by ThatNerdyPikachu** [comment]
This issue is now (mostly) resolved on their side -- can be safely closed.
