### ISSUE TITLE
{feature request] disable watch status for users

### ISSUE THREAD

**Issue by daveftw84** [jellyfin/jellyfin#1598]
i would love to use addons for kodi that syncs into the database but i dont want watch status shared between devices and would rather use kodi to handle all watch status locally. 
Any way of adding a flag to disable watch status for users? like a guest account?

**Comment by oddstr13** [comment]
Why is creating an account for each device not an option?

Feature requests should go here: https://features.jellyfin.org/
I'm closing this issue, you should vote or post on the feature tracker if this is still a feature you want.
