### ISSUE TITLE
Movie version ordering

### ISSUE THREAD

**Issue by texneus** [jellyfin/jellyfin#1599]
**Describe the bug**
Different versions of the same movie appear to list in the UI by file size and/or duration.  I have encountered a situation where the resulting default movie listed by Jellyfin is not the desired default.  For instance, movie "XYZ" contains a second version called "ABC".  In this instance "ABC" is the complete original movie, "XYZ", plus deleted and uncompleted scenes.  The resulting "ABC" version has both a larger filesize and is longer in duration than the theatrical release.  Jellyfin prefers "ABC" in favor of the Theatrical Release presumably because it believes it to be higher quality based on file size or is a "directors cut" type edition based on the longer length.

**To Reproduce**
Name two or more related tracks as required to enable movie versions where the "undesired" version is larger and/or longer than the other, ex:
```
XYZ
   |- XYZ - Theatrical Release.mkv (X GB, Y minutes)
   |- XYZ - ABC.mkv (X+ GB, Y+ minutes)
```

After scanning the library Jellyfin will list ABC as the default track for playback.  Thinking perhaps tracks were listed alphabetically I have renamed the files accordingly, but ABC is still the default track.
```
XYZ
   |- XYZ - 1. Theatrical Release.mkv
   |- XYZ - 2. ABC.mkv
```

**Expected behavior**
In this situation I think most people would prefer the Theatrical Release to be listed first.  I see no obvious way to change the order in the metadata or to specifically force an order in the Jellyfin UI.

**System (please complete the following information)**
 - OS: Docker under Debian 10
 - Browser: Firefox
 - Jellyfin Version: 10.3.7
 - Reverse proxy: None - LAN access only

**Additional context**
No doubt this is inherited from Emby, I've just never encountered a situation before where the default order doesn't make sense.

**Comment by cvium** [comment]
Movie versioning in Jellyfin is dumb and it doesn't really differentiate between them. It's possible it's just sorted alphabetically.

I think this is more a feature request and not a bug.

**Comment by GlassedSilver** [comment]
> Movie versioning in Jellyfin is dumb and it doesn't really differentiate between them. It's possible it's just sorted alphabetically.
> 
> I think this is more a feature request and not a bug.

unstale or new ticket, what would you suggest?

This is something that really gripes me. Especially because I have some films in 3D in addition to 2D.
Or how I have 4K versions which I prefer to be the default on everything that can direct play it, but I also sometimes keep smaller versions because I may select to pick those for portability and keeping some parts of my collection available to stream even on weaker remote connections.

Different cuts are an excellent reason why one would want this as well. Especially with custom grouping as a possibility and maybe rules.

**Comment by mbhayden14** [comment]
I'm having the exact same problem, and the only way I was able to get them to sort properly is by putting the info after the ' - ' in brackets. Don't know why, but it worked for me. Example:

XYZ
   |- XYZ - [1. Theatrical Release].mkv
   |- XYZ - [2. ABC].mkv

**Comment by GlassedSilver** [comment]
> I'm having the exact same problem, and the only way I was able to get them to sort properly is by putting the info after the ' - ' in brackets. Don't know why, but it worked for me. Example:
> 
> XYZ |- XYZ - [1. Theatrical Release].mkv |- XYZ - [2. ABC].mkv

Wow, that's extremely janky. I'd sure hope JF would aim for a better UX here.
