### ISSUE TITLE
Configurable time zone in per-user settings

### ISSUE THREAD

**Issue by Amolith** [jellyfin/jellyfin#1600]
At the moment, Jellyfin uses the time zone the user's browser report. Some privacy-enhancing extensions obscure this information and report something like (in my case) GMT. This causes issues with time everywhere in the UI. Below is a screenshot of what made me notice it.

![image](https://user-images.githubusercontent.com/29460675/62438541-69587580-b737-11e9-9cf7-0925291f2dac.png)

**Comment by onny** [comment]
Hey Amolith,
I think that this behavior is correct in so far that Jellyfin as a server has its own timezone and a user connecting to it, like your browser, has a separate one. For example a user connecting from a different region will have his/her own timezone.
So your browser has to tell the correct timezone/location to the Jellyfin web client ...

Best regards,
Jonas

**Comment by Amolith** [comment]
I agree that it should detect the user's timezone with what the browser reports by default (that just seems like common sense to me) but I would argue that the user should be able to _override_ that in their settings for cases like mine; when an extension is obfuscating their timezone for privacy reasons. I don't want to disable it globally and give *every website I visit* access to that simply because a single application I host relies on it to display something so basic.

**Comment by onny** [comment]
Good point!
So maybe this feature request also belongs to Jellyfin-web or to https://features.jellyfin.org

**Comment by Amolith** [comment]
Aha! I didn't know the feature request website existed or I would have added it there in the first place!
https://features.jellyfin.org/posts/238/configurable-time-zone-in-per-user-settings

Thank you!
