### ISSUE TITLE
I can't find my external hard drive

### ISSUE THREAD

**Issue by FabioCastilho** [jellyfin/jellyfin#1601]
Hello thanks for the work I am trying to adopt jellyfin but I run into a problem.
Jellyfin doesn't recognize my external hard drive any idea how I should proceed.

Raspberry Pi 3
Libreelec
(Docker) @

**Comment by RazeLighter777** [comment]
Is the drive mounted? Did you point jellyfin at its location?

**Comment by FabioCastilho** [comment]
Yes it is mounted by Libreelec automatically, but I can not find your way when I will add library in jellyfin, with emby works perfectly.

**Comment by FabioCastilho** [comment]
not list my folders 
![image](https://user-images.githubusercontent.com/21134162/62501473-7621ab80-b7c1-11e9-8a28-f412c8d8c9e1.png)

**Comment by onny** [comment]
> not list my folders
> ![image](https://user-images.githubusercontent.com/21134162/62501473-7621ab80-b7c1-11e9-8a28-f412c8d8c9e1.png)
So usually /var/media/HTPC should contain files _AND_ folders but looks like there is nothing here. So of course you have to check the permissions.
Which user is running the Jellyfin daemon and is this user allowed to browse ``/var/media/HTPC``.
Also please tell at least which version of Jellyfin you are running.

**Comment by FabioCastilho** [comment]
Hello sorry for the delay, I'm using the latest version available on the docker hub.
How do I give permission to the user?
![image](https://user-images.githubusercontent.com/21134162/62669085-af465100-b964-11e9-9981-9b488c5d9ff4.png)
Some folders within var / media / HTPC

**Comment by onny** [comment]
@FabioCastilho A good command to check the permissions for all directories leading to ``/var/media/HTPC`` is ``namei``. So please post the output of
```
namei -l /var/media/HTPC
```
It should look something like:
```
namei -l /media/6396f32d-b0d3-42a8-93cb-c4291e6ad716_/old
f: /media/6396f32d-b0d3-42a8-93cb-c4291e6ad716_/old
drwxr-xr-x root root /
drwxr-xr-x root root media
drwxr-xr-x onny onny 6396f32d-b0d3-42a8-93cb-c4291e6ad716_
drwxr-xr-x onny onny old
```
In this case, the ``r`` and the ``x`` in the last chmod sequence will show that every user will at least be able to access and read the contents of the folder.
Further, Docker or the user running it & Jellyfin needs to have accesss too. You can test this for example with:
```
sudo -u jellyfin ls /var/media/HTPC
```
But I have to admit that I have no experience in running Jellyfin inside Docker so maybe I'm missing something. For example, do you have to "mount" the local media directory inside the Docker container so it is accessible?

I looked into the documentation [here](https://jellyfin.readthedocs.io/en/latest/administrator-docs/installing/#containers) and it tells you can run the Jellyfin Docker container like this:
```
docker run -d \
--volume /path/to/config:/config \
--volume /path/to/cache:/cache \
--volume /path/to/media:/media \
--net=host \
jellyfin/jellyfin
```
This is just an example command. Of course you have to adapt the volume paths. Especially the last one is important. In your case it would look like: ``--volume /var/media/HTPC:/media``. So inside Jellyfin your media will be at ``/media`` and not ``/var/media/HTPC``.

Best regards,
Jonas

**Comment by FabioCastilho** [comment]
Hello, thanks for the help finally got the path is assembled automatically.
when I switched to my use the system could not find the hard drive.
If someone still needs help I leave the paths here.
`docker run -d \`

`--name jellyfin \`

`-v /storage/jellyfin/:/config \`

`-v /storage/jellyfin/cache:/cache \`

`-v /media:/media \`

`--net=host \`

`-e ServerIP=$(ip route get 9.9.9.9 | awk '{ print $NF; exit }') \`

`--restart=unless-stopped \`

`jellyfin/jellyfin`

RASPBERRY PI 3 + LIBREELEC 9 + DOCKER (ADDON)

**Comment by amirmasoud** [comment]
I could fix the problem by running following command to give access to media directories:

```shell
sudo setfacl -m u:jellyfin:rx /media/YOURNAME/
```

You can check further for the full installation process including the fixing permissions for media at this post https://www.linuxbabe.com/ubuntu/install-jellyfin-media-server-ubuntu-20-04

**Comment by samkcdev** [comment]
@amirmasoud Thanks! that fixed my issue. Now I am able to access my external HD

**Comment by ez2torta** [comment]
> I could fix the problem by running following command to give access to media directories:
> 
> sudo setfacl -m u:jellyfin:rx /media/YOURNAME/
> You can check further for the full installation process including the fixing permissions for media at this post https://www.linuxbabe.com/ubuntu/install-jellyfin-media-server-ubuntu-20-04

Thank you for this! i had to install acl to get that command to work but it did work perfectly :)
