### ISSUE TITLE
Anime doesn't scan properly when there's ≥100 episodes in a single season.

### ISSUE THREAD

**Issue by Munkenmo** [jellyfin/jellyfin#1604]
**Describe the bug**
In series with ≥100 Episodes in a single season, the scanner is failing to properly scan episodes 100+.  In the case of [Eyeshield 21 ](https://www.thetvdb.com/series/eyeshield-21/seasons/1), all episodes from 100+ have been labelled as episode 16

**To Reproduce**
1. Get a show such as [Eyeshield 21 ](https://www.thetvdb.com/series/eyeshield-21/seasons/1)
2. Give the episodes absolute numbering inside of a seasonal folder structure 
3. Install the Anime Plugin
4. Give the Anime Library the following metadata settings :

Series metadata :
- 1. TheTVDB
- 2. AniDB
- 3. AniSearch
- 4. AniList

Season metadata :
- 1. AniDB

Episode metadata:
- 1. AniDB
- 2. TheTVDB

5. Scan your Anime Library for new & updated files.
6. Go to Metadata and see that episodes 01-99 have scanned perfectly, whilst 100+ have been misidentified.

**Expected behavior**
All episodes within the season should be scanned and identified properly.

**Screenshots**
https://i.imgur.com/WAldAjK.png

**System (please complete the following information):**
 - OS: Ubuntu 18.04
 - Jellyfin Version: 10.3.7

**Additional context**

I think this may be unique to shows that transition from double to triple absolute digits in a single season that also contain >100 episodes.  
That may explain why One Piece Season 17 works (episodes 629-746), but Eyeshield 21 does not (episodes 01-145)

The workaround is manually editing metadata on a per episode basis, by :

1. Deleting the IMDB id
2. Correcting the TheTVDB id
3. Save
4. Refresh all metadata & replace existing images

Progress :

https://i.imgur.com/fYwd6Rs.png
https://i.imgur.com/8brhQNh.jpg

All finished :

https://i.imgur.com/hgRlVEs.png
https://i.imgur.com/S6mIYKG.png

I think this may be related to issue #1180

**Comment by adm-albayrme** [comment]
I've got the same issue with the latest version of Jellyfin installed. Black Clover and various other Anime like Toriko are all 3 digits Animes. What I see is that for example Episode 101 gets assigned the same info as Episode 1 and so forth
![Screenshot 2019-11-12 at 13 26 19](https://user-images.githubusercontent.com/10192704/68671704-3ac91280-0550-11ea-8ae9-18e9a8e7c618.png)
![Screenshot 2019-11-12 at 13 26 40](https://user-images.githubusercontent.com/10192704/68671705-3ac91280-0550-11ea-9754-2599b1652bf3.png)
![Screenshot 2019-11-12 at 13 27 02](https://user-images.githubusercontent.com/10192704/68671706-3ac91280-0550-11ea-8d1b-544d4ccf2c2d.png)


. So the whole library is a mess in the end. Bug is still open.

**Comment by JustAMan** [comment]
This could be fixed by https://github.com/jellyfin/jellyfin/pull/1929 which either is included in 10.4.1 or will be included in 10.4.2

**Comment by Munkenmo** [comment]
> This could be fixed by #1929 which either is included in 10.4.1 or will be included in 10.4.2

Can confirm that as of 10.4.2 this is fixed.

**Comment by noctrex** [comment]
Using the latest version 10.10.3 on a docker image, this problem seems to persist. Any series with over 100 episodes is recognized wrong.Episode 100 gets labeled as Season 0 Episode 1
