### ISSUE TITLE
tvheadend-jellyfin plugin

### ISSUE THREAD

**Issue by htttito** [jellyfin/jellyfin#1606]
I want to report a Bug - Problem?!
- The plugin start a Connection to tvheadend when you login into jellyfin. 
(The plugin should start when you watch TV?!)
- The plugin dont stop the Connection when you logout or stop watching tv? 
(That is the bigger Problem)

- Ubuntu-Server 18.04
- tvheadend  4.2.9

**Comment by anthonylavado** [comment]
Hi @htttito, I'll try this plugin again tonight to check. This may be a result of the same issues from #1520...

Overall though, using [Antennas](https://github.com/TheJF/antennas) provides a way better experience, as HDHomerun tuners have "native" support in Jellyfin.

**Comment by htttito** [comment]
@anthonylavado 
Hi! Did you check it? Is there a solution (not Antennas)?

**Comment by anthonylavado** [comment]
Hi @htttito - yes, the issues you described exist. Not sure where to take it forward from here though...

If I could find a good way of doing it, I would try and build out proper support for TVHeadend inside of Jellyfin, and that way you avoid needing a plug-in or Antennas. Like putting what Antennas does, inside of Jellyfin.

**Comment by dkanada** [comment]
@htttito if you are still having problems please open a new issue on the plugin repository.
