### ISSUE TITLE
Better Documentation

### ISSUE THREAD

**Issue by KannaDev** [jellyfin/jellyfin#1607]
A lot of people including me want to contribute to this amazing software. However due to the lack of proper documentation we can not go forward. The current documentation only talks about what is what, etc. Nothing ever mentions any kind of API to interact with the server.

**Comment by anthonylavado** [comment]
@KannaDev To be honest, we are still kind of exploring the API ourselves, since we plan to re-write it whenever we reach version 11.x.

There are _some_ resources here: https://github.com/jellyfin?utf8=%E2%9C%93&q=apiclient&type=&language=

Is there anything you'd like to see? Since you mention other possible contributors, do you know what they would like? We definitely want to encourage development.

**Comment by KannaDev** [comment]
@anthonylavado Thank you for the link will do check it out. Me and a couple other people want to work on a native iOS client for jellyfin.

**Comment by anthonylavado** [comment]
@kannadev Ah that would be most appreciated.

If you do know React-Native at all, we want to work on a client there so we can support a variety of platforms all at once: https://github.com/jellyfin/jellyfin-react-client

We also have a pretty active dev chat on Matrix if you want to join us: https://matrix.to/#/%23jellyfin-dev:matrix.org

**Comment by dkanada** [comment]
@KannaDev [this](https://github.com/jellyfin-archive/emby-apiclient-swift) repository might be of interest for you :) it's archived because we don't use it for anything but if someone starts working on it we would transfer it to the main organization.

**Comment by justpresident** [comment]
I am browsing the code for a week as well already trying to figure out where to start from. Have found this ticket accidentally. I would like to build a plugin that downloads automatically uploaded photos from cloud service to local filesystem and adds them to the library and have no clue where to start from and how to test.
It would be best to have some simple tutorials or videos explaining big component layout, where is a starting point. Also having some tests would be a great starting point.
I bet lots of people are struggling to start with it, especially non-C# devs like me.
