### ISSUE TITLE
Wrong API data returned after metadata provider change.

### ISSUE THREAD

**Issue by Tolriq** [jellyfin/jellyfin#1619]
Since the user does not seem to want to report to you I report it quickly without all necessary information.

https://community.yatse.tv/t/jellyfin-tv-shows-do-not-show-up-if-non-english-metadata/1962

It seems that when you update a show metadata provider language some values returned by the API for the shows are no more valid.

(probably the item.RecursiveItemCount but also maybe  item.ChildCount)

Sorry for not having more information and feel free to close if you can't reproduce as I'm just forwarding the info.

**Comment by onny** [comment]
Hm would be better to have a more detailed bug report here from the original user and on how to reproduce this ...

**Comment by Tolriq** [comment]
Really? :p I did ask him he ignored, I forward in case there's interest here. I can't force people to do things.

**Comment by joshuaboniface** [comment]
Thanks for this @Tolriq, I suppose 5 days isn't long in the grand scheme of things but it is definitely his responsibility to provide us the details, not much we can do without those.

**Comment by Tolriq** [comment]
After 8 years I'm ready to bet a million dollar we'll never hear anything from him unless there's another issue without workaround :)

Anyway if you do not have time to try to reproduce then feel free to close.

**Comment by Tolriq** [comment]
I guess it's the time to collet the million dollar ;)
