### ISSUE TITLE
RaspberryPi 4 "No usable version of the libssl was found"

### ISSUE THREAD

**Issue by wbingyin** [jellyfin/jellyfin#1620]
pi@raspberrypi:~ $ sudo dpkg -i jellyfin_10.3.7-1_armhf.deb 
正在选中未选择的软件包 jellyfin。
(正在读取数据库 ... 系统当前共安装有 100718 个文件和目录。)
准备解压 jellyfin_10.3.7-1_armhf.deb  ...
正在解压 jellyfin (10.3.7-1) ...
正在设置 jellyfin (10.3.7-1) ...
正在处理用于 systemd (241-5+rpi1) 的触发器 ...
pi@raspberrypi:~ $ jellyfin
[23:13:11] [INF] Jellyfin version: 10.3.7.0
[23:13:11] [INF] Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll"]
[23:13:12] [INF] Operating system: Linux 4.19.58.7
[23:13:12] [INF] Architecture: Arm
[23:13:12] [INF] 64-Bit Process: False
[23:13:12] [INF] User Interactive: True
[23:13:12] [INF] Processor count: 4
[23:13:12] [INF] Program data path: /home/pi/.local/share/jellyfin
[23:13:12] [INF] Web resources path: /usr/lib/jellyfin/bin/jellyfin-web/src
[23:13:12] [INF] Application directory: /usr/lib/jellyfin/bin/
No usable version of the libssl was found
已放弃
pi@raspberrypi:~ $

**Comment by onny** [comment]
Hey @wbingyin, thanks for trying out Jellyfin on the RaspPI4 :)
Try to install Jellyfin using the custom repo, see: https://jellyfin.readthedocs.io/en/latest/administrator-docs/installing/#debian

Best regards,
Jonas

**Comment by wbingyin** [comment]
> Hey @wbingyin, thanks for trying out Jellyfin on the RaspPI4 :)
> Try to install Jellyfin using the custom repo, see: https://jellyfin.readthedocs.io/en/latest/administrator-docs/installing/#debian
> 
> Best regards,
> Jonas

HI Jonas:
thanks!
I try to install Jellyfin using the custom repo, but it's not work,I also installed with RaspPi3B+,problem is same

**Comment by wbingyin** [comment]
I installed "libssl1.0.2",It's worked!

**Comment by wbingyin** [comment]
> > Hey @wbingyin, thanks for trying out Jellyfin on the RaspPI4 :)
> > Try to install Jellyfin using the custom repo, see: https://jellyfin.readthedocs.io/en/latest/administrator-docs/installing/#debian
> > Best regards,
> > Jonas
> 
> HI Jonas:
> thanks!
> I try to install Jellyfin using the custom repo, but it's not work,I also installed with RaspPi3B+,problem is same

I installed "libssl1.0.2",It's worked,Thanks!!
