### ISSUE TITLE
PlaybackInfo returning directplay for media with ac3 audio

### ISSUE THREAD

**Issue by vitorsemeano** [jellyfin/jellyfin#1630]
When playing a video file in android, and the device don't support ac3 natively, the method PlaybackInfo is giving a media source to direct play, even with the unsupported ac3 audio track.

I used the exoplayer implementation, but should be the same for any android that don't support  ac3 natively. The video file was a mkv container, with a video track encoded with h264 and audio track encoded with ac3.

**To Reproduce**
1. Open jellyfin android
2. Select a file with that specs
3. Play it
4. No sound, but video plays

**Expected behavior**
Video playing with audio. Should transcode the file to a compatible audio codec, since ac3 is not supported.

**Request**
http://192.168.1.2:8096/emby/Items/xxxxxxxxxxxxxxxxx/PlaybackInfo?UserId=yyyyyyyyyyyyyyy&StartTimeTicks=0&IsPlayback=true&AutoOpenLiveStream=true&AudioStreamIndex=1&MediaSourceId=856d7942665e30b014d593232bd11ffe&MaxStreamingBitrate=140000000

Request body
{"DeviceProfile":{"MaxStreamingBitrate":1500000,"MaxStaticBitrate":100000000,"MusicStreamingTranscodingBitrate":192000,"DirectPlayProfiles":[{"Container":"m4v,3gp,ts,mpegts,mov,xvid,vob,mkv,wmv,asf,ogm,ogv,m2v,avi,mpg,mpeg,mp4,webm,wtv,dvr-ms,iso","Type":"Video"},{"Container":"aac,mp3,mpa,wav,wma,mp2,ogg,oga,webma,ape,opus,flac","Type":"Audio"}],"TranscodingProfiles":[{"Container":"mkv","Type":"Video","AudioCodec":"aac,mp3","VideoCodec":"h264","Context":"Streaming"},{"Container":"mp3","Type":"Audio","AudioCodec":"mp3","Context":"Streaming","Protocol":"http"}],"ContainerProfiles":[],"CodecProfiles":[],"SubtitleProfiles":[{"Format":"srt","Method":"Embed"},{"Format":"subrip","Method":"Embed"},{"Format":"ass","Method":"Embed"},{"Format":"ssa","Method":"Embed"},{"Format":"pgs","Method":"Embed"},{"Format":"pgssub","Method":"Embed"},{"Format":"dvdsub","Method":"Embed"},{"Format":"vtt","Method":"Embed"},{"Format":"sub","Method":"Embed"},{"Format":"idx","Method":"Embed"},{"Format":"smi","Method":"Embed"}],"ResponseProfiles":[]}}

Response body

{"MediaSources":[{"Protocol":"File","Id":"xxxxxxxxxx","Path":"xxxxxxx.mkv","Type":"Default","Container":"mkv","Name":"xxxxxx","IsRemote":false,"ETag":"xxxxxx","RunTimeTicks":14392639488,"ReadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"RequiresClosing":false,"RequiresLooping":false,"SupportsProbing":true,"VideoType":"VideoFile","MediaStreams":[{"Codec":"h264","TimeBase":"1/1000","CodecTimeBase":"1001/60000","VideoRange":"SDR","DisplayTitle":"720P H264","NalLengthSize":"4","IsInterlaced":false,"IsAVC":true,"BitRate":1828807,"BitDepth":8,"RefFrames":1,"IsDefault":true,"IsForced":false,"Height":720,"Width":960,"AverageFrameRate":29.97003,"RealFrameRate":29.97003,"Profile":"High","Type":"Video","AspectRatio":"4:3","Index":0,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"PixelFormat":"yuv420p","Level":31},{"Codec":"ac3","TimeBase":"1/1000","CodecTimeBase":"1/48000","DisplayTitle":"Dolby Digital stereo Default","IsInterlaced":false,"ChannelLayout":"stereo","BitRate":448000,"Channels":2,"SampleRate":48000,"IsDefault":true,"IsForced":false,"Type":"Audio","Index":1,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Level":0}],"Formats":[],"Bitrate":2276807,"RequiredHttpHeaders":{},"DefaultAudioStreamIndex":1}],"PlaySessionId":"xxxxxx"}

**System (please complete the following information):**
Ubuntu Server 19.04 
Jellyfin 10.3.7
Modified version of jellyfin android, using exoplayer implementation, updated with current master.

**Additional context**
The server should return a url with a transcoded version of the file, since ac3 is not passed as a supported direct play format.

**Comment by JustAMan** [comment]
Could this be related to #2004?

**Comment by JustAMan** [comment]
Note that this could actually be fixed by https://github.com/jellyfin/jellyfin-android/pull/304
