### ISSUE TITLE
Some collections are empty.

### ISSUE THREAD

**Issue by 97carmine** [jellyfin/jellyfin#1635]
**Describe the bug**

When you force the scanning of media libraries, for some reason the collections are empty.

One way for collections to return to normal is to delete the library and re-add it.

Another is to add some content that belongs to one of the libraries. Using this method, of the two times I have forced the scanning of the media libraries, it once worked and the other did not.

**Screenshots**

![Screenshot_2019-08-16 Jellyfin](https://user-images.githubusercontent.com/6619414/63189301-337a9180-c053-11e9-92bb-e460a3099db5.png)

**System (please complete the following information):**
 - OS: Debian Buster
 - Jellyfin Version: 10.3.7
 - Reverse proxy: No

**Comment by JustAMan** [comment]
How are you making the collections?

**Comment by 97carmine** [comment]
No, they are created by the TMDb Box Sets plugin

**Comment by JustAMan** [comment]
Paging @cvium (plugin author)
