### ISSUE TITLE
Not starting on SSL port on system boot

### ISSUE THREAD

**Issue by brianjmurrell** [jellyfin/jellyfin#1638]
**Describe the bug**
When my system is restarted, when Jellyfin starts, it binds to the non-SSL port just fine but doesn't bind the to SSL port.  If I simply restart the service as soon as I notice this, it binds to the SSL port just fine.

**To Reproduce**

1. Install Jellyfin onto Fedora 30 from https://copr.fedorainfracloud.org/coprs/brianjmurrell/jellyfin/
1. Configure it to run on both non-SSL and SSL ports
1. Restart the machine
1. Notice that services on SSL don't work
1. Use `netstat -apn` to confirm that it's not listening on the SSL port
1. Use `systemctl` to restart `jellyfin.service`
1. Retry the SSL service

**Expected behavior**
Should start on SSL at boot.

**Logs**
I've already looked in the logs for any errors (or otherwise) about which ports it's listening on and didn't see anything.

**System (please complete the following information):**
 - OS: Fedora 30
 - Browser: N/A
 - Jellyfin Version: 10.3.7
 - Reverse proxy: no

**Comment by krazynez** [comment]
Having the same problem on my Arch install. The default port for 8096 is showing, but my default port 8920 is not showing with netstat.

**Comment by brianjmurrell** [comment]
To be clear though, it will start on port 8920 (in addition to 8096) if I `systemctl restart jellyfin.service` once the machine is up and running.

**Comment by brianjmurrell** [comment]
This doesn't seem to be a problem on 10.4.1 on EL7 now.  I will leave the ticket open for @krazynez to comment or let the stale-bot close as it sees fit.

**Comment by krazynez** [comment]
I switched from Arch back to Ubuntu and everything is good for me as well. Good to close.

**Comment by brianjmurrell** [comment]
> This doesn't seem to be a problem on 10.4.1 on EL7 now. I will leave the ticket open for @krazynez to comment or let the stale-bot close as it sees fit.

I have to take this back.  This does still seem to be a problem:

```
# ss -tpln  | grep jellyfin
LISTEN     0      128       [::]:80                    [::]:*                   users:(("jellyfin",pid=1435,fd=236))
```

Simply restarting the `jellyfin.service` enables it:

```
# ss -tpln  | grep jellyfin
LISTEN     0      128       [::]:443                   [::]:*                   users:(("jellyfin",pid=2630,fd=239))
LISTEN     0      128       [::]:80                    [::]:*                   users:(("jellyfin",pid=2630,fd=238))
```

So something about starting when the system starts is preventing binding to the SSL port, that works just fine when restarting after the system has started.

Is there some debugging suggestions (i.e. logging setting, etc.) that can be made to get to the bottom of this, given that it's so reproducible?
