### ISSUE TITLE
Can not get local trailers to play in webinterface

### ISSUE THREAD

**Issue by sl1288** [jellyfin/jellyfin#1639]
**Describe the bug**
Local trailers are found in the function "RefreshLocalTrailers", but are not playable in the webinterface.  LocalTrailerIds contains an GUID but LocalTrailerCount is 0.
As an result a youtube trailer is played.

**To Reproduce**
Create a trailers folder and put an File into this folder e.g.:
/Movie (2001)/Movie (2001).mkv
/Movie (2001)/trailers/Movie (2001).mkv
Rescan the Lib
Try to play the trailer in the webinterface

**System (please complete the following information):**
 - OS:  Windows
 - Browser: Chrome
 - Jellyfin Version: Commit 6766e04
 - Reverse proxy:  no

**Comment by anthonylavado** [comment]
I think all local trailers are broken as a result of Emby having moved the code to their “Cinema Mode” plugin, which we don’t have the source for. I think we’d need to recreate that plugin, or rebuild the feature, before it would work.
