### ISSUE TITLE
Jellyfin ignores <watched> tags when importing library

### ISSUE THREAD

**Issue by unikitty37** [jellyfin/jellyfin#1640]
**Describe the bug**
When importing an item that has an existing `.nfo` file, the `<watched>` tag is ignored and the item is imported as unwatched.

**To Reproduce**

1. Create a folder called `The 100/Season 01` in a TV library.
1. Place a video file called `The 100 - s01e01 - Pilot.mkv` in that folder.
1. Place the attached `.nfo` file in that folder: [nfofile.zip].(https://github.com/jellyfin/jellyfin/files/3512884/nfofile.zip)
1. Attempt to import the file that has just been added.

**Expected behavior**

The show is imported, and is marked as watched.

**Actual behaviour**
The show is imported, but is marked as unwatched. If Jellyfin is set to write `.nfo` files for that library, the file is changed to contain `<watched>false</watched>`, meaning the user must re-export from Emby before they can try re-importing.

**Logs**

No log errors. (Incidentally, selecting "enable debug logging" does not appear to stick — navigating away from the Logs settings page and back again shows it to be unticked, so if a debug log would help we might have a problem there…)

**Screenshots**

n/a

**System (please complete the following information):**
 - OS: Docker
 - Browser: Firefox
 - Jellyfin Version: 10.3.7
 - Reverse proxy: nginx

**Additional context**

As an Emby library can't be migrated by simply copying the files across, this is essential in order to allow a smooth migration. trakt.tv is not a useful alternative, as involves accepting a massive user agreement and privacy policy from a third party, and then uploading a load of private data for them to monetise. That seems to go against Jellyfin's open source ethos somewhat :)

**Comment by unikitty37** [comment]
As far as I'm aware, this is still an issue.

**Comment by anthonylavado** [comment]
Sorry about that, we’re fine tuning our bot. Will add the right label and move this up.

**Comment by JustAMan** [comment]
> As far as I'm aware, this is still an issue. I certainly haven't seen anything in the changelog indicating it's been fixed.

While what @anthonylavado says is true and we'll be tuning the stale settings, it would be good if original submitter would be checking on released versions, as his/her issue might be fixed as a side product of some unrelated PR. That is one of the reasons we have this stalebot enabled for.

**Comment by anthonylavado** [comment]
@unikitty37 So I found out why this isn't working. We forked with code from approximately May 2018. The feature had been turned off by that time: https://emby.media/community/index.php?/topic/47844-watched-status-no-longer-updating-from-nfo/

So, what we'll have to do, is create an enhancement to change this. A commenter says this may be available in code from 3.2.12.0 (for reference, we forked 3.5.2).

There is a good point raised - Emby can only take the NFO settings and apply them for one user, so this won't be a good fit for multi user environments. Part of that is already seen with the NFO Settings screen under library - you must choose a user to consider saving watched status from.

Sound good so far?

**Comment by unikitty37** [comment]
Ah — was just about to test against the current version but I guess you've saved me the effort there 😁

Yes, I'd forgotten about multiple users — an option to select which user to set them for (or none at all) would probably be best.

Since this is a one-off import rather than an ongoing sync, presumably there wouldn't be the problems described in the Emby thread.
