### ISSUE TITLE
[OSX] Can't run jellyfin binary - Error whilst attempting to create folder

### ISSUE THREAD

**Issue by roblav96** [jellyfin/jellyfin#1648]
Downloading the OSX portable tar.gz, tried executing the binary produces the following error:
```sh
~/Downloads/jellyfin_10.3.7
➤ ./jellyfin                                                                                                   22:40:49
Error whilst attempting to create folder
System.IO.IOException: The file '/Users/user/Downloads/jellyfin_10.3.7/jellyfin' already exists.
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Jellyfin.Server.Program.CreateApplicationPaths(StartupOptions options)
```

**Comment by anthonylavado** [comment]
Hey, can you let me know which version of macOS you’re using?

**Comment by roblav96** [comment]
```sh
➤ m info                                                                                                       21:28:24
ProductName:	Mac OS X
ProductVersion:	10.14.6
```

**Comment by anthonylavado** [comment]
Hrm okay. I run it on the latest Mojave and I’m okay... Re the .NET version, we build a self-contained binary, so you don’t need to have the runtime installed. We don’t use mono either (but I understand if you have it installed for dev/other reasons).

We don’t do a good job of promoting this, but are you willing to try my .app wrapper? It works on Mojave’s, and bundles the appropriate FFmpeg and FFprobe versions.

See here:
 https://github.com/jellyfin/jellyfin-server-macos/releases/latest

Steps:
* download Jellyfin-10.3.7.zip
* extract
* put “Jellyfin” in your Applications folder, and run

**Comment by crisclacerda** [comment]
I have the exact same problem here. 
Running on vanilla linux 5.10.76
Jellyfin 10.7.7
