### ISSUE TITLE
iptv can not play

### ISSUE THREAD

**Issue by sheiy** [jellyfin/jellyfin#1654]
log:
![image](https://user-images.githubusercontent.com/12210038/63360562-2934fc00-c3a1-11e9-8ee8-464bbfd8dc07.png)

iptvurl:
rtsp://123.147.113.84:554/04000001/01000000004000000000000000000231?AuthInfo=xxx&userid=

server type: docker

**Comment by onny** [comment]
Stream link doesn't work for me, looks like the server is down:
```
onny@onnuex ~> nmap 123.147.113.84 -p 554
Starting Nmap 7.70 ( https://nmap.org ) at 2019-08-20 21:13 CEST
Note: Host seems down. If it is really up, but blocking our ping probes, try -Pn
Nmap done: 1 IP address (0 hosts up) scanned in 3.07 seconds
```

**Comment by sheiy** [comment]
@onny  with my network the iptvurl  works good with potplayer

**Comment by sheiy** [comment]
iptv @anthonylavado

**Comment by marcosteam** [comment]
Same issue.
On XPEnology with docker,N3160,in my playlist some channel cannot play but potplayer can play it very well.
This is the m3u playlist:[m3u](https://files.catbox.moe/mli1w9.m3u)
CCTV1,3 cannot play.When I play the playlist by pot,it can be played.
