### ISSUE TITLE
Win7 sp1 install jellyfin, jellyfin service error can not be started, jellyfin application flashback.

### ISSUE THREAD

**Issue by cllcll** [jellyfin/jellyfin#1658]
**Describe the bug**
<Win7 sp1 install jellyfin, jellyfin service error can not be started, jellyfin application flashback.>

**Logs**

警告: 正在等待服务“Jellyfin (Jellyfin)”启动...
Start-Service : 无法启动服务“Jellyfin (Jellyfin)”。
所在位置 C:\jellyfin\install-jellyfin.ps1:216 字符: 36
+             Get-Service Jellyfin | Start-Service
+                                    ~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController)
   ServiceCommandException
    + FullyQualifiedErrorId : StartServiceFailed,Microsoft.PowerShell.Commands.StartServiceCommand

**System (please complete the following information):**
 - OS: [Windows7 sp1]
 - Browser: [ie8]
 - Jellyfin Version: [e.g. 10.3.7]

**Comment by PrplHaz4** [comment]
Try running the installer as admin - it sounds like the service was not created successfully.

**Comment by cllcll** [comment]
> Try running the installer as admin - it sounds like the service was not created successfully.

I have already tested the administrator to install it, and it doesn't work either. thanks for the reply.

**Comment by cllcll** [comment]
https://sm.ms/image/IkgMtX5VdDQaE3R
<a href="https://sm.ms/image/IkgMtX5VdDQaE3R" target="_blank"><img src="https://i.loli.net/2019/08/25/IkgMtX5VdDQaE3R.png" ></a>

[URL=https://i.loli.net/2019/08/25/IkgMtX5VdDQaE3R.png][IMG]https://i.loli.net/2019/08/25/IkgMtX5VdDQaE3R.png[/IMG][/URL]

**Comment by JustAMan** [comment]
Either NSSM or our Powershell scripts might be having an issue supporting Windows 7 (and I'm not sure anyone would want to fix that given Win7 is going to be deprecated soon), so you might have to create the service manually somehow or migrate to a newer version of Windows.

**Comment by cllcll** [comment]
> Either NSSM or our Powershell scripts might be having an issue supporting Windows 7 (and I'm not sure anyone would want to fix that given Win7 is going to be deprecated soon), so you might have to create the service manually somehow or migrate to a newer version of Windows.

Win7 as a server usage is still very low. I feel depressed when I hear this news.
