### ISSUE TITLE
System.OperationCanceledException: The operation was canceled.

### ISSUE THREAD

**Issue by valodiadeseynes** [jellyfin/jellyfin#1660]
Jellyfin is extremely slow all of a sudden. Connecting from the Kodi addon times out, and logging in from the web interface takes 30 seconds or so. It's even worse on the admin panel which takes several minutes to show any configuration related information (the page shows up but fields are empty).

System : 
Debian 10 x64
Jellyfin 10.3.7

I'm seeing this repeated in a loop in the server logs : 

```
Aug 22 11:00:35 prod-lan-tv jellyfin[339]: [11:00:35] [WRN] HTTP Response 200 to 192.168.1.31. Time (slow): 0:01:40.0392637. http://prod-lan-tv:8096/emby/system/info/public
Aug 22 11:01:07 prod-lan-tv jellyfin[339]: [11:01:07] [ERR] Error getting local Ip address information
Aug 22 11:01:07 prod-lan-tv jellyfin[339]: System.OperationCanceledException: The operation was canceled.
Aug 22 11:01:07 prod-lan-tv jellyfin[339]:    at System.Net.Http.HttpClient.HandleFinishSendAsyncError(Exception e, CancellationTokenSource cts)
Aug 22 11:01:07 prod-lan-tv jellyfin[339]:    at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
Aug 22 11:01:07 prod-lan-tv jellyfin[339]:    at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
Aug 22 11:01:07 prod-lan-tv jellyfin[339]:    at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
Aug 22 11:01:07 prod-lan-tv jellyfin[339]:    at Emby.Server.Implementations.ApplicationHost.IsIpAddressValidAsync(IpAddressInfo address, CancellationToken cancellationToken)
Aug 22 11:01:07 prod-lan-tv jellyfin[339]:    at Emby.Server.Implementations.ApplicationHost.GetLocalIpAddressesInternal(Boolean allowLoopback, Int32 limit, CancellationToken cancellationToken)
Aug 22 11:01:07 prod-lan-tv jellyfin[339]:    at Emby.Server.Implementations.ApplicationHost.GetLocalApiUrl(CancellationToken cancellationToken)
Aug 22 11:01:07 prod-lan-tv jellyfin[339]: [11:01:07] [WRN] HTTP Response 200 to 192.168.1.31. Time (slow): 0:01:40.0448539. http://192.168.1.12:8096/emby/system/info/public
```

Rebooting Jellyfin/the server doesn't change this behavior.

I know Jellyfin is quite IO hungry and it's setup on a HDD rather than a SSD but it was working correctly until yesterday and nothing in my logs indicate a HDD issue.

**Comment by onny** [comment]
Is it possible that some kind of background task is running like checking for plugin updates or updating the library?
You should try to disable these temporarily and check if this solves the issue.

**Comment by yukunyi** [comment]
I have same error. in 10.4.0 version.

**Comment by JustAMan** [comment]
Care to post how your network is configured on the host? This might indicate some problems when Jellyfin fails to understand your configuration.

**Comment by yukunyi** [comment]
I found this problem to occur when scanning the media library. During the problem, the console settings are empty. There is an api that has been pending until it times out. But this problem does not occur every time the media library is scanned.

**Comment by JustAMan** [comment]
Again, how is your network configured? What OS you're running on (Windows, Linux, ...), any firewall that might be prohibiting stuff?

**Comment by yukunyi** [comment]
It should not be the cause of the environment, I am running through the docker official image on the debian system, and this problem does not always exist, but it sometimes appears, so it will not be a network problem. Most of the time it is normal.

**Comment by yukunyi** [comment]
The database is sqlite.

**Comment by JustAMan** [comment]
@Bond-009 could this be a netcore bug?

**Comment by valodiadeseynes** [comment]
Sorry for the delay,

I've just changed my HDD for a newer one and I'm noticing that Jellyfin's web interface is working better (normally ?) now except for the first connection to the homepage.

However I'm still seeing these logs : (full log [here](https://pastebin.com/U3JgPk1E)

`Nov 10 18:38:53 prod-lan-tv jellyfin[346]: [18:38:53] [WRN] HTTP Response 200 to 192.168.1.50. Time (slow): 0:01:41.3593252. http://ajbl37-medias.e-dubreuil.fr/emby/system/info/public
Nov 10 18:39:04 prod-lan-tv jellyfin[346]: [18:39:04] [ERR] Error getting local Ip address information
Nov 10 18:39:04 prod-lan-tv jellyfin[346]: System.OperationCanceledException: The operation was canceled.
Nov 10 18:39:04 prod-lan-tv jellyfin[346]:    at System.Net.Http.HttpClient.HandleFinishSendAsyncError(Exception e, CancellationTokenSource cts)
Nov 10 18:39:04 prod-lan-tv jellyfin[346]:    at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
Nov 10 18:39:04 prod-lan-tv jellyfin[346]:    at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
Nov 10 18:39:04 prod-lan-tv jellyfin[346]:    at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
Nov 10 18:39:04 prod-lan-tv jellyfin[346]:    at Emby.Server.Implementations.ApplicationHost.IsIpAddressValidAsync(IPAddress address, CancellationToken cancellationToken)
Nov 10 18:39:04 prod-lan-tv jellyfin[346]:    at Emby.Server.Implementations.ApplicationHost.GetLocalIpAddressesInternal(Boolean allowLoopback, Int32 limit, CancellationToken cancellationToken)
Nov 10 18:39:04 prod-lan-tv jellyfin[346]:    at Emby.Server.Implementations.ApplicationHost.GetLocalApiUrl(CancellationToken cancellationToken)`

**Comment by JustAMan** [comment]
@valodiadeseynes please update Kodi addon to the very latest release (should be something about 0.3.6 or so), and either clean up "base URL" in server settings or set up a new connection in Kodi addon giving it full URL in form of "ip:port/jellyfin", for more see Release Notes: https://github.com/jellyfin/jellyfin/releases/tag/v10.4.1

**Comment by valodiadeseynes** [comment]
I followed your instructions (already was on version 0.3.6 for the kodi addon) and nothing's changed. I still see the same logs, Kodi's addon is still unable to connect to the server (even with a direct ip:port/jellyfin address) and the first loading of jellyfin's web interface takes at the very least 20 seconds (while as administrator, absolutely nothing is fetched from the config files from the web interface in the settings -> the fields are empty).

**Comment by baconfeet** [comment]
I'm having the exact same issue with 10.4.2

`[2019-11-26 13:37:51.405 -06:00] [ERR] Error getting local Ip address information
System.OperationCanceledException: The operation was canceled.
   at System.Net.Http.HttpClient.HandleFinishSendAsyncError(Exception e, CancellationTokenSource cts)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.ApplicationHost.IsIpAddressValidAsync(IPAddress address, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ApplicationHost.GetLocalIpAddressesInternal(Boolean allowLoopback, Int32 limit, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ApplicationHost.GetLocalApiUrl(CancellationToken cancellationToken)`
