### ISSUE TITLE
Setting password to blank does not mark users/public/[HasPassword] to false

### ISSUE THREAD

**Issue by ChessDragon136** [jellyfin/jellyfin#1661]
Server: 10.3.7

Steps to recreate:

1. Create user in Jellyfin with no password.
2. Run: http://SERVER:PORT/Users/Public?format=json
3. Confirm ,"HasPassword":false,"HasConfiguredPassword":false,"HasConfiguredEasyPassword":false
4. Set user password
5. Run: http://SERVER:PORT/Users/Public?format=json
6. Confirm ,"HasPassword":true,"HasConfiguredPassword":false,"HasConfiguredEasyPassword":false
7. Change password, leaving new password fields blank.
8. Run: http://SERVER:PORT/Users/Public?format=json

At this point, I would expect HasPassword to return false, but it still continues to return true. Logging in to the web interface presents me the login form which it would not do if logging in at step 3. Leaving the password field blank lets me log in.

**Comment by cvium** [comment]
Not an issue in 10.7
