### ISSUE TITLE
How to enable Guest public registration  ?

### ISSUE THREAD

**Issue by magadan** [jellyfin/jellyfin#1662]
Hello, 

I need the guest registration feature on Jellyfin, this feature exist and can be enabled ?

**Comment by onny** [comment]
I guess this feature is not yet implemented. Best way to request it is on this site: https://features.jellyfin.org

**Comment by anthonylavado** [comment]
Hi @magadan, this feature does not yet exist. As @onny suggests, the best way to request it is to add it to the feature site.

Thanks!

**Comment by gagzzz** [comment]
Hey,

I've added a comment 4 months ago on the feature site, but i've been told to ask on github about this feature.
What is the correct way then? :+1: 

thanks a lot!

**Comment by anthonylavado** [comment]
I take it you're referring to [this](https://features.jellyfin.org/posts/382/register-form), which I've just merged as a duplicate.
As a project, we don't accept bounties for any items. If you wanted to, you could contact any individual contributor to do so, but many of us will not take sponsorships to specifically implement tasks.

That said, this project is very promising: https://github.com/hrfee/jfa-go

**Comment by gagzzz** [comment]
Hello!

Thank you for your answer! It's really great to see jfa-go, that will help a lot for my project.
And thank you for the job on jellyfin :)
