### ISSUE TITLE
Docker image doesn't respect UID and GID

### ISSUE THREAD

**Issue by agilob** [jellyfin/jellyfin#1669]
I run docker image with environment properties:

```
    environment:
      - PUID=1000
      - PGID=1000
```
but jellyfin doesn't respect them and .nfo .srt files are always saved as root not my specified user.

You can easily spot here which files were created by sonarr and which by jellyfin.
```
-rw-r--r-- 1    0    0      44390 Aug 18 12:21 .en.srt
-rwxrwxrwx 1 1000 1000 1795542253 Aug 10 06:55 .mkv
-rwxrwxrwx 1 1000 1000       1533 Aug 11 15:26 .nfo
-rwxrwxrwx 1    0    0      25654 Aug 11 15:26 -thumb.jpg
```

To support easier backup of jellyfin directories I need to `chmod 777` or `chown` every few days.

**Comment by cvium** [comment]
Please see https://github.com/jellyfin/jellyfin/issues/477
