### ISSUE TITLE
slow library scan

### ISSUE THREAD

**Issue by charles-martel55** [jellyfin/jellyfin#1682]
Hi,

The library scan is terribly slow after the initial scan (~30 mins). I have ~2300 movies, I tested with v10.3.7.
In the past, I reported this issue with Emby, normally they fixed this with the 3.5.3.0. https://emby.media/community/index.php?/topic/55586-slow-library-scan/

I debuged jellyfin to find which part take more time to execute, I think this is method : 

`public IEnumerable<Video> FindTrailers(BaseItem owner, List<FileSystemMetadata> fileSystemChildren, IDirectoryService directoryService)`

When I disabled it, the scan takes less than ~30 seconds.
But I don't know enough the operation of jellyfin, to find a way to fix this issue.

Best regards.

**Comment by cvium** [comment]
Can you try this patch?

```
Index: MediaBrowser.Controller/Entities/BaseItem.cs
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- MediaBrowser.Controller/Entities/BaseItem.cs	(revision 595a68b822654b03c32a35060bf97234dbc6ef7c)
+++ MediaBrowser.Controller/Entities/BaseItem.cs	(date 1567081013000)
@@ -1472,26 +1472,29 @@
             var newItemIds = newItems.Select(i => i.Id);
 
             var itemsChanged = !item.LocalTrailerIds.SequenceEqual(newItemIds);
-            var ownerId = item.Id;
+            if (itemsChanged)
+            {
+                var ownerId = item.Id;
 
-            var tasks = newItems.Select(i =>
-            {
-                var subOptions = new MetadataRefreshOptions(options);
+                var tasks = newItems.Select(i =>
+                {
+                    var subOptions = new MetadataRefreshOptions(options);
 
-                if (i.ExtraType != Model.Entities.ExtraType.Trailer ||
-                    i.OwnerId != ownerId ||
-                    !i.ParentId.Equals(Guid.Empty))
-                {
-                    i.ExtraType = Model.Entities.ExtraType.Trailer;
-                    i.OwnerId = ownerId;
-                    i.ParentId = Guid.Empty;
-                    subOptions.ForceSave = true;
-                }
+                    if (i.ExtraType != Model.Entities.ExtraType.Trailer ||
+                        i.OwnerId != ownerId ||
+                        !i.ParentId.Equals(Guid.Empty))
+                    {
+                        i.ExtraType = Model.Entities.ExtraType.Trailer;
+                        i.OwnerId = ownerId;
+                        i.ParentId = Guid.Empty;
+                        subOptions.ForceSave = true;
+                    }
 
-                return RefreshMetadataForOwnedItem(i, true, subOptions, cancellationToken);
-            });
+                    return RefreshMetadataForOwnedItem(i, true, subOptions, cancellationToken);
+                });
 
-            await Task.WhenAll(tasks).ConfigureAwait(false);
+                await Task.WhenAll(tasks).ConfigureAwait(false);
+            }
 
             item.LocalTrailerIds = newItemIds.ToArray();
```

**Comment by charles-martel55** [comment]
Same issue with the patch.

**Comment by Lynxy** [comment]
In the same boat. 2,500 movies, 20,000 episodes, scan time is pretty erratic ranging from 20 to 240 minutes, and once in awhile never completes at all until restarting.

**Comment by JustAMan** [comment]
Does anyone have the same issue in 10.4.3?

**Comment by Lynxy** [comment]
I'm running 10.4.3 and still have this issue. Scans either finish on time (roughly 25% of the time), 2-4 hours over time (25% of the time), or not at all (running 3+ days no progress, 50% of the time).

**Comment by charles-martel55** [comment]
Hi,

I tried the 10.4.3 and I have the same issue.

**Comment by dkanada** [comment]
#2436 might improve this for music libraries

**Comment by charles-martel55** [comment]
Hi,

Same issue with the version 10.5.5.

**Comment by bugfixin** [comment]
I've been diving into this pretty hard and found that in my case, it's related to the folder structure of the library - one of the places JF searches for trailers and other extras is in subdirectories neighboring the movie file itself.

This makes sense if you have a movies library that always has the structure of `/movies/Title/Title.mp4` with extras in `/movies/Title/Extras/`, but if you have a "movies" directory with the following:

- 12 Angry Men/
- 28 Weeks Later/
- A Clockwork Orange/
- Vertigo/
- Mulan.mp4
- Nightcrawler.mp4

When it scans Mulan.mp4, jellyfin will look into the folders of 12 Angry Men, 28 Weeks Later, A ClockWork Orange, and Vertigo, trying to find trailers for Mulan.mp4. Then it'll do it again when it scans Nightcrawler.mp4.

I'm not sure if this behavior remains in 10.6, but I would have to imagine there are enough users with this type of directory structure that JF's trailer/extras search behavior should change.

**Comment by Lynxy** [comment]
Thanks for sharing your discovery @bugfixin. I am glad you found a solution to your slow scan problem and hope it helps others with a similar issue!

Unfortunately it does not appear to be a solution for me. I've checked my library structure and the root does not contain mixed directories/files like you described; it is composed entirely of directories.

My library scans are still erratic as I described previously, the only new information I can add is I haven't been as attentive to the Jellyfin server and I've let it go for 3 weeks straight on a single scan, never completing.

**Comment by bugfixin** [comment]
I'm not sure I'd call it a solution yet ;) Right now I'm hoping to perhaps add some sort of short-circuit to the code to skip the trailer search on raw media files in top level directories, or perhaps ignore neighbor directories that don't contain certain trailery strings...

That's interesting, I had high hopes for it being the primary driver of slow scans. With your scan issues, does the progress indicator hang at a certain %? Are you able to turn debug logging on and provide a complete log? Your issue may be unrelated to the slow FindTrailers method mentioned in the original issue report as well.

**Comment by dkanada** [comment]
Unfortunately, the problem is much more pervasive than a single issue. It's probably just a decade of feature additions to the library scans that increased the scan time to what we see today. One thing that might help this is the custom resolver settings that don't actually exist yet. In your case, we could have a `Movie Trailers` resolver that people could selectively disable if they don't expect any trailers, creating the short circuit you're after.

**Comment by bugfixin** [comment]
Certainly there's no golden commit that'll permanently solve slow scans for everyone, but at least in my case, skipping the search of 1,000+ subdirectories for each of the 2,000+ bare files makes an absolutely massive difference (minutes rather than hours for the complete library scan), and I think there are enough users who do use mixed directories and bare files that it's worth having sane defaults for that scenario even without custom resolver settings. 

I'd be happy to solve this either way, but I would need to have some sort of framework to look at for developing a custom resolver (I don't think it's there but I'd love to be corrected), so for the time being I'm looking at a simpler solution.

All that said, that only matters if the same problem is still here in 10.6, which I still need to test against.

**Comment by dkanada** [comment]
Custom resolvers are already supported, what we don't support is the configuration aspect. It would need to be an array setting on each library (or a global setting at first) and then a way to change it on the web client.
