### ISSUE TITLE
Movie identification

### ISSUE THREAD

**Issue by Nelo3D** [jellyfin/jellyfin#1684]
Some movies are wrongly identified with tmdb scrapper.

For example, Bichos. If you search Bichos in tmdb web, you get the same wrong movie that Jellyfin get. But, if you add the year to the search, you get the correct one.
The filename is Bichos (1998).

I guess that year is not passing to search API.

Greetings.

**Comment by onny** [comment]
Do you have just the file in your movies directory or do you also use sub directories like "/Bichos (1998)/Bichos.mkv". But you're right, this kind of filematching could be better ...

**Comment by Nelo3D** [comment]
Thanks for the reply.

I have Bichos (1998)/Bichos (1998).mkv

**Comment by JustAMan** [comment]
shoo bot

**Comment by Nelo3D** [comment]
Seems better the identification now.
