### ISSUE TITLE
Build script fails on v10.3.7

### ISSUE THREAD

**Issue by kaysond** [jellyfin/jellyfin#1688]
I'm trying to build the ubuntu package for 10.3.7.

If I run
```
git clone https://github.com/jellyfin/jellyfin.git
cd jellyfin/
git checkout v10.3.7
git submodule update --init
./build ubuntu-package-x64 package
```
Then I get the following error:
```
~/git/jellyfin/MediaBrowser.WebDashboard/jellyfin-web ~/git/jellyfin
Fetching origin
error: pathspec '(HEAD' did not match any file(s) known to git.
error: pathspec 'detached' did not match any file(s) known to git.
error: pathspec 'at' did not match any file(s) known to git.
error: pathspec 'v10.3.7)' did not match any file(s) known to git.
ERROR: 'jellyfin-web' branch '(HEAD detached at v10.3.7)' is invalid.
```
Weirdly, if I do a `git clone --recursive`, the build script seems to work fine on the current HEAD. As far as I can tell, the build script hasn't been changed since v10.3.7 so I'm not sure what I'm doing wrong...

Any help would be appreciated! Thanks.

**Comment by kaysond** [comment]
So the issue is that when you check out a tag, or if you're using jellyfin as a submodule (which I'm doing to create my own docker container), then the checkout fails: https://github.com/jellyfin/jellyfin/blob/a30876c3ff80323975c67447dff8ff4b4add4637/build#L193 

In my case the solution is to go into the submodule and do an explicit `git checkout <branch>` in my submodule. In the case of building a specific release version, one workaround is to checkout the branch and not the tag, but I don't think that will allow you to rebuild a specific version.

**Comment by anthonylavado** [comment]
>…one workaround is to checkout the branch and not the tag…

We do cut the tags from the release branches, so this would work perfectly fine.

At any rate, this is good to know so we can try to make adjustments where needed.

**Comment by kaysond** [comment]
@anthonylavado I'm curious why there's a need to check out a specific branch for the submodule at all? The script runs `git submodule update --init --recursive` which will automatically pull whatever commit is set up in the current repo. If you want the latest commit on that branch you can do `git submodule update --init --recursive --remote`. Presumably releases occur together so there's no need to explicitly pull that branch? In fact, the whole point of submodules is so you don't have to worry about this kind of stuff...

**Comment by anthonylavado** [comment]
I did not set this up. On the topic of build scripts, it would be best to tag @JoshuaBoniface

**Comment by joshuaboniface** [comment]
It is to avoid needing to deal with bumping the sub module commit all the time (which is a pain to keep track of), and also to allow flexibility when building (e.g. to choose a different web branch or tag for testing).

**Comment by kaysond** [comment]
@joshuaboniface makes sense. would you take a PR to fix this issue? I'm thinking just check if the branch contains "detached head" and then don't do another checkout

**Comment by joshuaboniface** [comment]
@kaysond Sure, feel free to PR and I'll make sure it works with the build infra.

**Comment by kaysond** [comment]
@joshuaboniface so the solution already exists and its just running `./build -b local`, which then doesn't touch the submodule
