### ISSUE TITLE
[bug] [documentation] Dead links (404)

### ISSUE THREAD

**Issue by berniegp** [jellyfin/jellyfin#1689]
At https://jellyfin.readthedocs.io/en/latest/#administrator-documentation

- Plugins: How to install plugins in Jellyfin.
- Port Bindings

Return a 404 page.

**Comment by onny** [comment]
Hey,
thanks for reporting. It would be better if you open this bug report at the jellyfin-docs repository here: https://github.com/jellyfin/jellyfin-docs

**Comment by berniegp** [comment]
Sorry about that! I didn't see that part in the contribution guide.

https://github.com/jellyfin/jellyfin-docs/issues/106
