### ISSUE TITLE
Jellyfin not automatically scanning for new added media

### ISSUE THREAD

**Issue by alculete** [jellyfin/jellyfin#1690]
**Describe the bug**
Jellyfin not scanning for new added media

**To Reproduce**

1. Download a new file
2. Add it to media folder
3. Go to your jellyfin media player
4. After more than 5 minutes the file is not added

**Expected behavior**
After adding the file to jellyfin media folder it should be scanned and added to the library automatically 

**System (please complete the following information):**
**OS:** Ubuntu 18.04.3 LTS x86_64 
**Host:** HP Compaq 6200 Pro MT PC 
**Kernel:** 4.15.0-58-generic 
**Packages:** 1169 
**CPU:** Intel i3-2120 (4) @ 3.300GHz 
**GPU:** Intel Integrated Graphics 
**Memory:**  7864MiB 
**Docker version:** 18.06.1-ce, build e68fc7a

**Comment by anthonylavado** [comment]
So this is actually highly dependent on the file system, and if “watch for changes” is enabled for the library. That said, there is a scheduled task you can enable to do this at a pre-set interval, if you want.

**Comment by alculete** [comment]
> So this is actually highly dependent on the file system, and if “watch for changes” is enabled for the library. That said, there is a scheduled task you can enable to do this at a pre-set interval, if you want.

Can't find that option on settings

**Comment by anthonylavado** [comment]
@alculete Which one? “Real time monitoring” is in the advanced settings for each library. It’s usually in by default, so I’m not too worried about that. If you wanted to try the scheduled task route, that’s in the Dashboard under Expert>Scheduled Tasks. “Scan media library”.


That said, to help with this, how is the media mounted? What is the file system?

**Comment by alculete** [comment]
My Linux runs on LVM, real-time monitoring was disabled. will test and report

**Comment by alculete** [comment]
Now is updating, thank you for your help

**Comment by adrianmak** [comment]
Then What is the "real time monitoring" for ? I supposed it is used to update library when new files in folder are detected.

**Comment by alculete** [comment]
> Then What is the "real time monitoring" for ? I supposed it is used to update library when new files in folder are detected.

yes, it is supposed to update when detects changes in your library

**Comment by Kruemmelspalter** [comment]
For me, with a docker volume this doesn't work. Do I need to change any permissions on the files / directories?

**Comment by VigibotDev** [comment]
My one stopped from auto refreshing after 7500 files... no server or software configuration change

**Comment by VigibotDev** [comment]
The log show

[2022-03-21 08:02:09.104 +01:00] [ERR] Error in Directory watcher for: "/mnt/localstorage/files"
System.IO.IOException: The configured user limit (8192) on the number of inotify watches has been reached, or the operating system failed to allocate a required resource.
[2022-03-21 08:02:09.104 +01:00] [INF] Stopping directory watching for path "/mnt/localstorage/files"

**Comment by DUOLabs333** [comment]
I have the same problem, using bindfs --- maybe that's why?

**Comment by wesbos** [comment]
My docker image doesn't refresh when new media is added either. Running on a synology. Emby worked fine. Any ideas?

**Comment by VigibotDev** [comment]
https://jellyfin.org/docs/general/administration/troubleshooting.html#real-time-monitoring ?

**Comment by wesbos** [comment]
Thanks - ill look at that. 

A fix for now - edit the DOM and make a setting for 3000000000, which is a scan about every 5 mins. My machine is pretty fast so it takes less than 1 min.

<img width="808" alt="Screenshot 2023-01-04 at 10 19 47 AM" src="https://user-images.githubusercontent.com/176013/210587996-4c9321d6-c4e5-4feb-99f8-60e8f873bb2f.png">

**Comment by VigibotDev** [comment]
Yes you have a lot of file and filesystem require this tuning :)

**Comment by alessandro-vitali** [comment]
I have the same issue, same log error. I'm also running Jellyfin in docker on a Synology, and even though I'm going to ditch Synology in the long term, I'd love to fix this issue with a less hacky way than setting the task trigger for the library scan to something below every few hours. I tried to follow the steps outlined in the link above (Jellyfin docs > Administration > Troubleshooting), but

Thing is, Synology's DSM linux flavor doesn't have a directory /sysctl.d in /etc. If I SSH into /etc. All I find there is a file called sysctl.conf, with the following content:

```shell
kernel.panic = 3
net.core.somaxconn = 65535
net.ipv4.tcp_tw_reuse  = 1
fs.protected_hardlinks = 1
fs.protected_symlinks = 1
kernel.syno_forbid_console=0
kernel.syno_forbid_usb=0
net.ipv6.conf.default.accept_ra_defrtr=0
net.ipv4.conf.default.accept_redirects=0
net.ipv6.conf.default.accept_redirects=0
net.ipv4.conf.default.send_redirects=0
net.ipv4.conf.default.secure_redirects=0
net.ipv6.conf.default.accept_ra=0
``` kernel.panic = 3

Now, can I just vim into the file, and append ```fs.inotify.max_user_watches=524288``` at the bottom? This looks like networking configuration however, probably not where this should go. I don't really understand the command though either, what does ```sysctl -p``` do?

Do any of you know how the hell Synology's OS handles this? Or am I just better off setting library scans to 15 mins. I'm worried this might increase I/O load to the hard drives a lot, especially when I'm syncing files through Syncthing and running other services in the background.

**Comment by wesbos** [comment]
I still have the problem. I had it setup to scan every 5 mins, but I was seeing massive lag in the system, likely because they were overlapping each other? 

So now I just manually hit the scan button when I know a show is added, but that is slow as well. 

Still searching for solutions

**Comment by alessandro-vitali** [comment]
@wesbos Solved it! You'll have to add a script that runs on every reboot of DSM (Control Panel > Task Scheduler > Create > Triggered Task > User defined script), with the following content: ```sysctl fs.inotify.max_user_watches=1048576;``` and then run it manually. 

The fix is described in this [Emby forum post](https://emby.media/community/index.php?/topic/106276-how-to-fix-rtm-not-working-caused-by-limited-inotify-instanceswatches/), but I found similar threads on the Synology forum as well ([example](https://community.synology.com/enu/forum/1/post/153190)), and it seems like a lot of Syncthing users on Synology had the (weirdly enough I didn't on the same machine). There's also an earlier Jellyfin Github bug report [describing a fix](https://github.com/jellyfin/jellyfin/issues/6353).

**Comment by FlavioB79** [comment]
Hi. Sorry for hi-jacking this thread: I've the same issue. Jellyfin running as Docker Container and the media libraries are NFS mounts on the Docker host. On those, "real-time monitoring" is enabled, but it still won't pick up the new files.
Thanks for helping!
