### ISSUE TITLE
Unable to start jellyfin server using docker

### ISSUE THREAD

**Issue by groenator** [jellyfin/jellyfin#1698]
**Describe the bug**
Until 10 min ago everything worked well, however, Jellyfin server doesn't startup. On boot I get the following error:

```
jellyfin-server | System.ArgumentNullException: Value cannot be null.
jellyfin-server | Parameter name: source
jellyfin-server |    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
jellyfin-server |    at Emby.Server.Implementations.LiveTv.EmbyTV.ItemDataProvider`1.GetAll()
jellyfin-server |    at Emby.Server.Implementations.LiveTv.EmbyTV.TimerManager.RestartTimers()
jellyfin-server |    at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.Start()
jellyfin-server |    at Emby.Server.Implementations.ApplicationHost.RunStartupTasksAsync()
jellyfin-server |    at Jellyfin.Server.Program.StartApp(StartupOptions options)
jellyfin-server |    at Jellyfin.Server.Program.Main(String[] args)
jellyfin-server |    at Jellyfin.Server.Program.<Main>(String[] args)
jellyfin-server |
jellyfin-server | Unhandled Exception: System.ArgumentNullException: Value cannot be null.
jellyfin-server | Parameter name: source
jellyfin-server |    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
jellyfin-server |    at Emby.Server.Implementations.LiveTv.EmbyTV.ItemDataProvider`1.GetAll()
jellyfin-server |    at Emby.Server.Implementations.LiveTv.EmbyTV.TimerManager.RestartTimers()
jellyfin-server |    at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.Start()
jellyfin-server |    at Emby.Server.Implementations.ApplicationHost.RunStartupTasksAsync()
jellyfin-server |    at Jellyfin.Server.Program.StartApp(StartupOptions options)
jellyfin-server |    at Jellyfin.Server.Program.Main(String[] args)
jellyfin-server |    at Jellyfin.Server.Program.<Main>(String[] args)
jellyfin-server | Aborted (core dumped)
```

**System (please complete the following information):**
 - OS: Docker
 - Jellyfin Version: 10.3.7.0
 - Reverse proxy: No

**Additional context**
One thing that I did was clearing up the cache/xmltv folder. It's very weird what's happening.

**Comment by onny** [comment]
So in this case it might miss some important temp file to start again. You could think about moving these cache/xmltv files from an other installation back to the docker data.

**Comment by groenator** [comment]
Ohh! I've deleted the files... now it make sense. That's fine, I'll wait
for the new version and install a fresh version.

Is no other way to recover?

**Comment by joshuaboniface** [comment]
@groenator I'm not sure why it would suddenly break, but can you try two things:

1. A fresh data folder (back up the old one of course).
2. The `jellyfin:nightly` docker with your existing library (and still backing it up of course).

I'm curious if it's the same as what #1709 fixed or not - in that case, both worked.

**Comment by groenator** [comment]
Sure! But you have to wait for a few days as I am on my holiday.
