### ISSUE TITLE
Add Dockerfile to build Debian package

### ISSUE THREAD

**Issue by nvllsvm** [jellyfin/jellyfin#17]
Building packages often requires multiple steps and customized environments. Having a Dockerfile to build the Debian package:

- Creates portable, reproducible build environments. 
- Allows one to build the Debian package on any system.
- Documents how exactly to build the package. Our ancestor project was notoriously bad at this.

In other words - one should be able to build a Debian package doing nothing more than this. This example assumes https://github.com/jellyfin/jellyfin/issues/18 has been implemented.
```
$ git clone https://github.com/jellyfin/jellyfin
$ cd jellyfin/jellyfin
$ docker build -f Dockerfile.debian_package .
```

**Comment by joshuaboniface** [comment]
The current build procedure is just as simple and has no dependency on Docker, just on the `dotnet-sdk-2.1` package and standard `debuild` framework. However I don't see a reason we can't do both, as long as the Docker setup doesn't preclude doing it the old-fashioned non-Docker way.

**Comment by nvllsvm** [comment]
@joshuaboniface One of the intentions of having this **in addition** to the Debian build files is that it will make CI/CD integration much nicer.

**Comment by joshuaboniface** [comment]
Yup agreed on the CI integration, just wanted to be sure!
