### ISSUE TITLE
unable to delete files 

### ISSUE THREAD

**Issue by alculete** [jellyfin/jellyfin#1711]
**Describe the bug**
Unable to remove media

**To Reproduce**

1. Select a media file
2. Delete the file
3. De file disappears 
4. Refresh the page (if is web interface or navigate away from the library and return) the deleted file appears again

**Expected behavior**
File should be deleted. It is not a permission

**Logs**
No error was detected on the log but de file is not deleted

**Screenshots**

**System (please complete the following information):**
OS: Ubuntu Server 18.04.3 LTS x86_64 
Host: HP Compaq 6200 Pro MT PC 
Kernel: 4.15.0-58-generic 
hell: bash 4.4.20 
Terminal: /dev/pts/0 
CPU: Intel i3-2120 (4) @ 3.300GHz 
[Log.txt](https://github.com/jellyfin/jellyfin/files/3568646/Log.txt)

Memory:  7864Mi

**Additional context**
When deleting the file desappears for a wile but the file is available on  the disk. The system runs on a LVM partition

**Comment by anthonylavado** [comment]
Are we sure it's not a permission issue? The program runs as the Jellyfin user...

**Comment by alculete** [comment]
Yes, I'm sure. I have a cronjob running every 30 min to change permission to 777 on media folder because  I had permission issues before using plex

**Comment by icf20** [comment]
i can add that jellyfin can delete files but not folders 

just pick a season folder to delete and nothing happens but if u pick an episode u can delete it

what OP say is true

here the log say the folder is deleted and the season is removed from UI 
a quick ssh in the machine it will tell you is not deleted
`[2019-09-04 17:55:20.112 +02:00] [INF] Deleting item, Type: "Season", Name: "Season 6", Path: `

then a library scan make the "deleted" season some back from the dead

`[2019-09-04 18:04:10.564 +02:00] [INF] Creating Season "Season 6" entry for`


the logs are from my own machine not OP

**Comment by Servh37** [comment]
I have the same issue regarding delete on the movies side as well in docker all all volume had the correct permission with the correct uid and gid able to delete individual tv shows have not try full series.

**Comment by riload35** [comment]
Same issue here.
When the movie placed at the root of the library, the deletion works but if the movie is placed in a subfolder (I use radarr) then the movie is not deleted despite the logs indicate that the deleting is OK.
I confirm that this is not a problem of permissions.

**Comment by arniom** [comment]
Same issue for me, i can delete one file/episode, but not the entire folder/season. Using docker, and the permission is good.

**Comment by wippozippo** [comment]
Same thing for me since I started using jellyfin. It can delete separate files but not folders, so it can delete individual tv episodes but not seasons, series or movie folders.

**Comment by 4luk** [comment]
Anyway to fix this or have to wait for an update? This happens in the Android and Web app. Thanks

**Comment by hrvstr** [comment]
Is this added to the latest stable build or do we have to install the nightly? I am still unable to delete media from the WebUI.

**Comment by anthonylavado** [comment]
Last Stable release was November, so this has not changed yet. New stable before the end of the month is in the works.

**Comment by thorthur** [comment]
From which version should we expect the issue to be fixed?

**Comment by regisb** [comment]
@thorthur This is fixed on my server running 10.5.0. As far as I am concerned, this can be closed.

**Comment by thorthur** [comment]
I concur, working fine on 10.5.2.
Thanks for the quick reply!
