### ISSUE TITLE
Can't fetch TVDB images in all languages

### ISSUE THREAD

**Issue by nbo21** [jellyfin/jellyfin#1712]
Trying to fetch images from TVDB that don't match the library's language doesn't work even when the all languages box is ticked.

For example, I created a library and set the preferred download language to Japanese. When I search for images, only Japanese images will show up. It won't find any images that are tagged as English or any other language.

FanArt and TheMovieDb images from other languages show up correctly. The default behavior seems to be to show English images even without the all languages option selected which makes sense because the vast majority of images are tagged as English. It would be great if it worked like this for TVDB as well.

**System:**
 - OS: Docker
 - Browser: Firefox
 - Jellyfin Version: 10.3.7
 - Reverse proxy: traefik

**Comment by anthonylavado** [comment]
Related: https://github.com/jellyfin/jellyfin/issues/1342
