### ISSUE TITLE
Consider increasing the value for the 'analyzeduration' and 'probesize' options

### ISSUE THREAD

**Issue by DominicMe** [jellyfin/jellyfin#1713]
I just setup Jellyfin and having an issue where systemd service periodically dies. Log is filled with the error below, it may or may not be the ultimate cause but just spams the log making it very difficult to find other errors if nothing else. What is this related to?

```
[matroska,webm @ 0x55ff2b771300] Could not find codec parameters for stream 7 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
jellyfin[10599]: Consider increasing the value for the 'analyzeduration' and 'probesize' options
```

There are also other AV related errors:

`[mp3float @ 0x55fc7c092000] Header missing`

`[mpeg4 @ 0x55715488ed00] Failed to parse extradata`

```
[matroska,webm @ 0x55747c6ed300] Could not find codec parameters for stream 5 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Sep 03 12:50:07 Server jellyfin[10599]: Consider increasing the value for the 'analyzeduration' and 'probesize' options
```

```
[13:13:16] [INF] Killing ffmpeg process
Sep 03 13:13:16 Server jellyfin[10599]: [13:13:16] [ERR] ffmpeg image extraction failed for file:"/mnt/pool/series/xxxxxxxx.mkv"
Sep 03 13:13:16 Server jellyfin[10599]: [13:13:16] [ERR] I-frame image extraction failed, will attempt standard way. Input: file:"/mnt/pool/series/xxxxxxx>
Sep 03 13:13:16 Server jellyfin[10599]: System.Exception: ffmpeg image extraction failed for file:"/mnt/pool/series/xxxxxxxxxxx.mkv"
Sep 03 13:13:16 Server jellyfin[10599]:    at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.ExtractImageInternal(String inputPath, String container, MediaStream videoStream, Nullable`1 imageStreamIndex, Nullable`1 threedF>
Sep 03 13:13:16 Server jellyfin[10599]:    at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.ExtractImage(String[] inputFiles, String container, MediaStream videoStream, Nullable`1 imageStreamIndex, MediaProtocol protocol,>
Sep 03 13:13:18 Server jellyfin[10599]: [matroska,webm @ 0x5568f0040300] Could not find codec parameters for stream 3 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
```

**System (please complete the following information):**
 - OS: Fedora 29
 - Browser: Chrome
 - Jellyfin Version:  10.3.7

**Comment by JustAMan** [comment]
Will be tunable when https://github.com/jellyfin/jellyfin/pull/1941 gets merged.

**Comment by jimmyd-be** [comment]
I have still have this issue in Jellyfin 10.6.4
```
matroska,webm @ 0x1d56d40] Could not find codec parameters for stream 8 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
```

Where can I configure this?

**Comment by Bond-009** [comment]
`JELLYFIN_FFmpeg__probesize` and `JELLYFIN_FFmpeg__analyzeduration` env vars

**Comment by ssyangchn** [comment]
> 
What value should be configured

**Comment by ssyangchn** [comment]
> `JELLYFIN_FFmpeg__probesize` and `JELLYFIN_FFmpeg__analyzeduration` env vars

What value should be configured

**Comment by iEvoken** [comment]
i got this error jellyfin-unstable (2022-01-09)

**Comment by punksinatra** [comment]
same issue 10.7.7
`Unsupported codec with id 98304 for input stream 3
Unsupported codec with id 98304 for input stream 3
[matroska,webm @ 0x55bc6f88c600] Could not find codec parameters for stream 6 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[matroska,webm @ 0x55bc6f88c600] Could not find codec parameters for stream 7 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Unsupported codec with id 98304 for input stream 3
Unsupported codec with id 98304 for input stream 3
[matroska,webm @ 0x56443087e600] Could not find codec parameters for stream 6 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[matroska,webm @ 0x56443087e600] Could not find codec parameters for stream 7 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Unsupported codec with id 98304 for input stream 3
Unsupported codec with id 98304 for input stream 3
[matroska,webm @ 0x5593781b7600] Could not find codec parameters for stream 7 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Unsupported codec with id 98304 for input stream 3
Unsupported codec with id 98304 for input stream 3
Unsupported codec with id 98304 for input stream 3
Unsupported codec with id 98304 for input stream 3
[matroska,webm @ 0x55ad72107600] Could not find codec parameters for stream 6 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[matroska,webm @ 0x55ad72107600] Could not find codec parameters for stream 7 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[matroska,webm @ 0x564308699600] Could not find codec parameters for stream 5 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[matroska,webm @ 0x564308699600] Could not find codec parameters for stream 6 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Unsupported codec with id 98304 for input stream 3
Unsupported codec with id 98304 for input stream 3
[matroska,webm @ 0x5597c2a54600] Could not find codec parameters for stream 6 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[matroska,webm @ 0x5597c2a54600] Could not find codec parameters for stream 7 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[05:31:17] [INF] [66] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
Unsupported codec with id 98304 for input stream 3
[matroska,webm @ 0x55bd29ad9600] Could not find codec parameters for stream 7 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Unsupported codec with id 98304 for input stream 3
Unsupported codec with id 98304 for input stream 3
[matroska,webm @ 0x5645d5bb3600] Could not find codec parameters for stream 6 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[matroska,webm @ 0x5645d5bb3600] Could not find codec parameters for stream 7 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Unsupported codec with id 98304 for input stream 3
Unsupported codec with id 98304 for input stream 3
Unsupported codec with id 98304 for input stream 3
[matroska,webm @ 0x55e6562ec600] Could not find codec parameters for stream 6 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[matroska,webm @ 0x55e6562ec600] Could not find codec parameters for stream 7 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Unsupported codec with id 98304 for input stream 3
Unsupported codec with id 98304 for input stream 3
Unsupported codec with id 98304 for input stream 3
[matroska,webm @ 0x55d926f91600] Could not find codec parameters for stream 7 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Unsupported codec with id 98304 for input stream 3
Unsupported codec with id 98304 for input stream 3
[matroska,webm @ 0x55f42a92a600] Could not find codec parameters for stream 6 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[matroska,webm @ 0x55f42a92a600] Could not find codec parameters for stream 7 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Unsupported codec with id 98304 for input stream 3
Unsupported codec with id 98304 for input stream 3
[matroska,webm @ 0x5625ebfbe600] Could not find codec parameters for stream 7 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Unsupported codec with id 98304 for input stream 3
Unsupported codec with id 98304 for input stream 3
Unsupported codec with id 98304 for input stream 3
[matroska,webm @ 0x559e4da69600] Could not find codec parameters for stream 6 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[matroska,webm @ 0x559e4da69600] Could not find codec parameters for stream 7 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Unsupported codec with id 98304 for input stream 3
Unsupported codec with id 98304 for input stream 3
Unsupported codec with id 98304 for input stream 3
Unsupported codec with id 98304 for input stream 3
Unsupported codec with id 98304 for input stream 3
Unsupported codec with id 98304 for input stream 3
Unsupported codec with id 98304 for input stream 3
[matroska,webm @ 0x55c64b5b4600] Could not find codec parameters for stream 7 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Unsupported codec with id 98304 for input stream 3
[05:32:17] [INF] [32] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
Unsupported codec with id 98304 for input stream 3
Unsupported codec with id 98304 for input stream 3
[matroska,webm @ 0x56328e42a600] Could not find codec parameters for stream 6 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[matroska,webm @ 0x56328e42a600] Could not find codec parameters for stream 7 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Unsupported codec with id 98304 for input stream 3
Unsupported codec with id 98304 for input stream 3
[matroska,webm @ 0x5566a065f600] Could not find codec parameters for stream 6 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[matroska,webm @ 0x5566a065f600] Could not find codec parameters for stream 7 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Unsupported codec with id 98304 for input stream 3
[matroska,webm @ 0x56388482b600] Could not find codec parameters for stream 7 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Unsupported codec with id 98304 for input stream 3`

**Comment by Al4ndil** [comment]
+1

Same issue for me...

**Comment by Entmatix** [comment]
Same issue with latest docker image.

**Comment by ThisIsTheOnlyUsernameAvailable** [comment]
> Same solution

The solution isn't clear to those of us who aren't intimately familiar with the code.  Setting environment variables is easy, but what should they be set to?  What units are those variables set in -- seconds, miliseconds, something else?

A couple of pointers would help people resolve the issue.

**Comment by Adanufgail** [comment]
https://ffmpeg.org/ffmpeg-formats.html seems to suggest that the default for probesize is 5000000  (5MB) and analyzeduration is 5000000 (5 seconds). I multipled both by 10 and it seems to have helped.

**Comment by fatmonk8** [comment]
> https://ffmpeg.org/ffmpeg-formats.html seems to suggest that the default for probesize is 5000000 (5MB) and analyzeduration is 5000000 (5 seconds). I multipled both by 10 and it seems to have helped.

Would you be able to give a step-by-step on how to change this? I am running Jellyfin through docker on Unraid.

**Comment by Adanufgail** [comment]
Unraid:
1. In Unraid, edit the docker container and scroll to the bottom.
2. Click "Add another Path, Port, Variable, Label, or Device."
3. Under "Config Type," choose "Variable."
4. Under "Name," enter "JELLYFIN_FFmpeg__probesize" and enter the same for "Key"
5. Under "Value" enter 50000000 (or whatever you would like to change it to, in Bytes).
6. Click "Add"
7. Repeat, with "JELLYFIN_FFmpeg__analyzeduration" and 50000000 (or whatever you would like in miliseconds).

Docker Compose (excerpt, add the other rows needed):
services:
  jellyfin:
    environment:
      - JELLYFIN_FFmpeg__probesize=50000000
      - JELLYFIN_FFmpeg__analyzeduration=50000000
