### ISSUE TITLE
DLNA disabled but Jellyfin still tries to bind to :1900

### ISSUE THREAD

**Issue by icf20** [jellyfin/jellyfin#1717]
**Describe the bug**

`Failed to bind to port 1900: Address already in use. DLNA will be unavailable`

**To Reproduce**

1. Go to Enable Dlna server and uncheck the option

**Expected behavior**

disable DLNA and stop the log spam

**Logs**
```
23:37:16] [ERR] Failed to bind to port 1900: Address already in use. DLNA will be unavailable
[23:38:16] [ERR] Failed to bind to port 1900: Address already in use. DLNA will be unavailable
[23:39:16] [ERR] Failed to bind to port 1900: Address already in use. DLNA will be unavailable
```
**Screenshots**

![image](https://user-images.githubusercontent.com/17784575/64384962-70c0b680-d036-11e9-9e92-063a1c5e5a17.png)

**System (please complete the following information):**
 - OS: docker

 - Jellyfin Version: 10.3.7

**Comment by joshuaboniface** [comment]
Something is already using the port. What does `netstat -plunt | grep 1900` show in your port list? If something is already listening for DLNA Jellyfin won't be able to on the port, that's just the nature of it.

**Comment by tyhawk** [comment]
I'm seeing the same error in my logs and in my case, I have DLNA disabled as well, so I don't expect any error messages every single minute. I'm running Jellyfin 10.3.7 in a Docker Swarm setup.
```
$ sudo netstat -plunt | grep 1900
udp6       0      0 :::1900                 :::*                                1366/dockerd
```
Turns out it was Plex. I had port 1900 mapped, but since it's for DLNA, I removed it from my config.
Then Jellyfin took over and the message disappeared from the logs.
```
$ sudo netstat -plunt | grep 1900
udp        0      0 0.0.0.0:1900            0.0.0.0:*                           11446/dotnet        
$ ps -ef | grep 11446
root     11446 11416  2 19:04 ?        00:03:00 dotnet /jellyfin/jellyfin.dll --datadir /config --cachedir /cache --ffmpeg /usr/local/bin/ffmpeg
myuser 16857 28941  0 21:31 pts/0    00:00:00 grep --color=auto 11446
```
So that solved it for me.

Still weird that Jellyfin grabs port 1900 with DLNA disabled and nags every minute when the port is already in use.

**Comment by JustAMan** [comment]
What is expected behaviour in your opinion?

**Comment by tyhawk** [comment]
@JustAMan If DLNA is disabled in Jellyfin, it should not try to bind to port 1900. Naturally, if DLNA is enabled, it should bind to port 1900.

**Comment by randalotto** [comment]
This issue still exists.

**Comment by MartenBE** [comment]
I still see this issue, even with UPnP and DLNA disabled in the dashboard. Can this be reopened?

**Comment by comfreak89** [comment]
Same for me. Jellyfin still binds to UPNP Port 1900 while disabled in the settings. I also restarted the daemon.

`root@jellyfin:~# netstat -tulpena |grep 1900
udp        0      0 0.0.0.0:1900            0.0.0.0:*                           110        1970687255 90909/jellyfin      
udp        0      0 192.168.178.242:1900    0.0.0.0:*                           110        1970738674 90909/jellyfin      
udp        0      0 127.0.0.1:1900          0.0.0.0:*                           110        1970738672 90909/jellyfin`

![Uploading Screenshot_1.png…]()

**Comment by cvium** [comment]
Auto discovery uses the same port

**Comment by makerio90** [comment]
is there a way to disable dlna before a docker container has been made? 1900 is in use and binding it to 1901 wont work.
