### ISSUE TITLE
Leaving local bind address blank slows Jellyfin and prevents Android login

### ISSUE THREAD

**Issue by thismachinechills** [jellyfin/jellyfin#1718]
**Describe the bug**
When the local bind address is not set on Jellyfin's backend, logging in via the Android app fails. Jellyfin's backend fails to detect the "LocalAddress" as reported by the `/emby/system/info/public` endpoint.

**To Reproduce**
1. Go to Jellyfin's admin dashboard.
2. Go to "Advanced"
3. Leave "Bind to local network address:" blank such that Jellyfin will bind to all IP addresses.
4. Try to login via the Android app. It will hang and then fail due to a "Connection Error". I couldn't get any relevant details using logcat with a Jellyfin Android app debug build.
5. Access the `/emby/system/info/public` REST endpoint via a web browser. It will hang for a long time. Eventually, you'll get this JSON response:

       {"WanAddress":"http://my-wan-ip:8096","ServerName":"jellyfin","Version":"10.3.7","ProductName":"Jellyfin Server","OperatingSystem":"Linux","Id":"myid"}

Backend logs will show this: 

    [2019-09-06 12:01:31.889 -04:00] [WRN] HTTP Response 200 to "10.255.0.4". Time (slow): 0:01:40.0651693. "http://my-lan-ip:8096/emby/system/info/public"

**Expected behavior**
1. I should be able to login via the Android app. 
2. Jellyfin should not hang for 1m40s when accessing the `/emby/system/info/public` endpoint. 
3. Jellyfin should return the correct "LocalAddress" at that endpoint.

**Logs**

    [2019-09-06 12:01:31.889 -04:00] [WRN] HTTP Response 200 to "10.255.0.4". Time (slow): 0:01:40.0651693. "http://my-lan-ip:8096/emby/system/info/public"
**Screenshots**
N/A

**System (please complete the following information):**
I am using the `linuxserver/jellyfin` Docker image via Docker Swarm with an overlay network, and I have the container port 8096 forwarded to the host node on port 8096. The host node is a low-powered `armv7l` board.

 - OS: Docker version 19.03.2 build 6a30dfc on Ubuntu 18.04LTS
 - Browser: Chrome
 - Jellyfin Version: 10.3.7 (backend), 0.9.2 (Android app)
 - Reverse proxy: None

**Additional context**
edit: I should note that while Android logins fail in this context, at no point does the web app fail to login. I am consistently able to use the web interface, however it is noticeably slower.

On the first few runs of Jellyfin's backend, I am able to log into the Android app **without having to set the local bind address**. It is only after a few days and reboots that I must set the local bind address to be able to login.

Setting the local bind address to the host node's LAN IP address allows me to login via the Android app instantly.

Given that there is a consistent 1m40s delay when accessing `/emby/system/info/public` without a local bind address set, there is probably a 100-second timeout somewhere on the backend.

From what I can tell, the Android app will hang waiting for a response from `/emby/system/info/public`, but because the Android app has a lower response timeout than the Jellyfin backend does, the Android app will stop waiting before the backend times out and returns a response.

As an aside, setting the local bind address in Jellyfin's backend causes the `/emby/system/info/public` endpoint to return a different response than when the local bind address is left blank.

Example:

1. Local bind address is set:

    `{"LocalAddress":"http://my-lan-ip:8096","WanAddress":"http://my-wan-ip:8096","ServerName":"jellyfin","Version":"10.3.7","ProductName":"Jellyfin Server","OperatingSystem":"Linux","Id":"myid"}`

2. Local bind address is not set:

    `{"WanAddress":"http://my-wan-ip:8096","ServerName":"jellyfin","Version":"10.3.7","ProductName":"Jellyfin Server","OperatingSystem":"Linux","Id":"myid"}`

**Comment by joshuaboniface** [comment]
@thismachinechills If you're willing to test it, can you try out the 10.4.0 nightlies (Docker tag `jellyfin:nightly`) and see if the issue still occurs there? Be sure to use a fresh data folder (or back up your stable one) first. I'm on the nightlies and unable to reproduce, but I do use a reverse proxy.

**Comment by thismachinechills** [comment]
Tested with the 10.4.0 release, and this is no longer a problem.
