### ISSUE TITLE
Home videos & photos: cast/people not working

### ISSUE THREAD

**Issue by mr-simba** [jellyfin/jellyfin#1719]
Hello,

If I add people - for example as actor - to videos of type “Home videos & photos”, these people show correctly on the video page under cast. But the linked people’s page shows only the name and no videos.

For example I have added “Grandma” as actor to several Home videos. Grandma shows up as cast on the video page. But if I click on the cast “Grandma”, then a page shows up with the name “Grandma” on top, but there are no videos with “Grandma” shown.

If I search by name “Grandma”, then on the result-page Grandma shows up under the people area. If I click on “Grandma”, again a page shows up with the name “Grandma” on top, but there are no videos with “Grandma” shown.

This only happens with videos of type “Home videos & photos”.

If I use videos of type “Movies”, then on the people’s pages there are all videos shown with that person as an actor.

Is there a problem or are people / cast simply not working for videos of type “Home videos & photos”?

By the way I also tested this with emby, and there the cast/people - page is working correctly also for home videos & photos.

**Comment by 1wonjae** [comment]
This is still an issue: 1) create a custom person by adding a new entry to a video as cast 2) go to that person's page 3) that page does not show the added video.

**Comment by felix920506** [comment]
Please open a new report.
