### ISSUE TITLE
Problem hostfxr.dll loading failed

### ISSUE THREAD

**Issue by ilham88** [jellyfin/jellyfin#1721]
C:\Users\User\Desktop>D:\PHP\jellyfin\system\jellyfin.exe -d D:\PHP\jellyfin\da
ta
Failed to load the dll from [D:\PHP\jellyfin\system\hostfxr.dll], HRESULT: 0x800
70057
The library hostfxr.dll was found, but loading it from D:\PHP\jellyfin\system\ho
stfxr.dll failed
  - Installing .NET Core prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409

How fix it??
.NET Core installed, and still error?
Thanks

**Comment by anthonylavado** [comment]
Hi there - it looks like this is a bug with Windows 7 and .NET (I'm assuming you're using Windows 7).

Please install this update from here: https://support.microsoft.com/en-ca/help/2533623/microsoft-security-advisory-insecure-library-loading-could-allow-remot
