### ISSUE TITLE
TVDB issue

### ISSUE THREAD

**Issue by snintendog** [jellyfin/jellyfin#1722]
TVDB returns Wrong Season of Battle star galactica 1978 when placing the series in a Season folder with Naming Structure SxEE - T.
I honestly believe its more on TVDB and their weird series structure being horribly messed up more than anything no anime using the Anime plugin has done this only TV shows that use the TVDB scraper and it seems random. Galactica 1980 did this as well and when i added speed racer then i had to rescan with the Anime plugin get it right. other shows that caused issues are due to the 3 in 1 rule like animaniacs and chalkzone.

Folder structure used is BattleStar Galactica>Season 1>episodes in the SxEE - T format, then identifying the Main series has 1978 Galactica, Main Series NFO is correct but Season1 and Episode NFOs are not.

The Typical Series get the Episodes that correspond to the Name and SxEE setup.

Don't have any logs beyond it just scrapping the wrong season for some reason.
[jellfin issues.txt](https://github.com/jellyfin/jellyfin/files/3586724/jellfin.issues.txt)

Some Screengrabs 
![jellfin issues 2](https://user-images.githubusercontent.com/5448989/64476814-9a2a3100-d161-11e9-9008-b6243b6e9ca1.PNG)
![jellfin issues 3](https://user-images.githubusercontent.com/5448989/64476815-9a2a3100-d161-11e9-8044-224d7812a173.PNG)
![jellfin issues](https://user-images.githubusercontent.com/5448989/64476816-9a2a3100-d161-11e9-989a-32fc4430026a.PNG)

**System (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox as the client
 - Jellyfin Version: 10.3.7
 - Reverse proxy: none

not much more than maybe more TV episode scrappers in the future if it is like i think it is on the fault of TVDB they are very sensitive of being called wrong and having it their way IMDB would be great but i heard they make people pay to use them as a source.

**Comment by anthonylavado** [comment]
@snintendog Thanks for filing the issue. As a sidenote, it's not enabled by default, but you can turn off TVDB and enable OMDB. OMDB data is very close to IMDB, but without the insane costs of using IMDB (we do pay for OMDB access). Give that a try in your Library settings.

**Comment by snintendog** [comment]
Alright Never knew OMDB had TV episodes as well Good to know thanke.

**Comment by joshuaboniface** [comment]
Yea, to be 100% honest, TVDB has been a complete nightmare for us to use reliably for the last ~6 months, between the constant random issues and their failed v3 API transition, and that's not even getting into metadata issues like you have here. If OMDB gets you the data better, I'd recommend it over TVDB any day.

**Comment by cvium** [comment]
I feel like this is a duplicate of https://github.com/jellyfin/jellyfin/issues/1467

**Comment by dkanada** [comment]
Yeah, I thought they handled API v3 very well. They gave devs advance notice to test out the new version, and then reverted the change within a week once they realized they were having issues. I can't comment on the data itself since I don't use the plugin.

**Comment by snintendog** [comment]
> 
> 
> I feel like this is a duplicate of #1467. I think your distrust of tvdb's api is misplaced.

with how hostile TVDB is toward users after browsing the web before even coming to post it here having an alternative is better best quote from them i found "its TVDB not DVDDB don't like then I'll ban you." in reference to how the TV airing order was not the correct order for episodes yet the DVD order had them correct. 

OMDB is working better even when i am using filebot so i can clearly say that yes TVDB is the issue this time around. Also the 11 o'clock hang i get with filebot if i try to search for something late at night dissapeared when i stopped using TVDB as a scraper there.
