### ISSUE TITLE
SSL configuration (self-signed) completely breaks local Chromecast even over http

### ISSUE THREAD

**Issue by bengalih** [jellyfin/jellyfin#1725]
**Describe the bug**
When configuring JF to use SSL using a self-signed certificate, you are unable to Chromecast to any local Google Device.

Some background on the issue via linked bug [here](https://github.com/jellyfin/jellyfin/issues/1396#issuecomment-529261947).

**To Reproduce**

1. Configure SSL using self-signed certificate on JF server.  "Secure connection mode:  Preferred, but not required."
2. Connect to JF server over non SSL port (servername:8096)
3. Select device to chromecast to
4. Attempt to play media
5. "MessageChromecastConnectionError" results.

**Expected behavior**
While it is clear that Google devices have a limitation of not being able to cast from a server with a self-signed cert, the issue is that JF appears to connect to the Google Device over this self-signed SSL connection *even if* the user is accessing JF over the http connection.

One should be able to connect to JF over an http connection locally and expect JF to be able to communicate with the Google device over this insecure channel. 

SSL should still be allowed as an enabled feature for users who need to access the system remotely.

**Logs**
I don't see any sort of messages in the console or log windows that appear to relate to the issues.  Specifically in steps 3-5 of the reproduction steps above don't seem to log anything of consequence.  I will be happy to look elsewhere, provide more logs if required (and instructed what to get).

**Screenshots**
None applicable at this time.

**System (please complete the following information):**
 - OS: Windows 10
 - Browser: 76.0.3809.132
 - Jellyfin Version: 10.3.7
 - Reverse proxy: none

**Additional context**
I feel that this is a bug since Jellyfin works to cast when SSL is not configured at all.
Configuring SSL for remote users should not *require* that local connections use http.
It appears that when configuring any type of SSL, JF is changing the "LAN address:" in the Dashboard to "https://" and transmitting this to the Google devices which then will fail to properly validate the self-signed cert.

Due to the difficult nature of getting 3rd party certs in many situations, JF should assume proper functionality with self-signed certs.  To allow compatibility with Google devices, there should be the ability to modify what LAN address is used.  It would make sense that if the user is accessing JF over the http port, then http should be advertised as the LAN address.

I believe the only way to get the desired functionality currently is to keep https entirely off on the JF server and configure a reverse proxy to handle only the remote connections.  While this should work (I have not tested yet), it is very cumbersome to require an additional 3rd party proxy server when it would seem possible to add an additional configuration section into JF to choose which protocol the LAN address uses.

**Comment by joshuaboniface** [comment]
@bengalih Does the behaviour change if the SSL setting is set to "Handled by reverse proxy"? I think this would just be a case of the Chromecast blindly trying the HTTPS endpoing, since this is preferred on that side, and it failing, and then it not retrying HTTP.

Self-signed certs are always going to be a bane, just because these "smart" (read dumb) devices choke on them. And in this case I'd lean towards this being a Chromecast issue rather than a Jellyfin issue.

>Due to the difficult nature of getting 3rd party certs in many situations, JF should assume proper functionality with self-signed certs. To allow compatibility with Google devices, there should be the ability to modify what LAN address is used. It would make sense that if the user is accessing JF over the http port, then http should be advertised as the LAN address.

With the existence of LetsEncrypt, this simply is no longer true. Getting 3rd party certs is trivial. Plus, a reverse proxy is almost always the ideal solution for this, as it's far more flexible in its SSL configuration than Jellyfin can ever be. They're trivial to set up even on Windows and well-documented.

**Comment by bengalih** [comment]
> @bengalih Does the behaviour change if the SSL setting is set to "Handled by reverse proxy"? I think this would just be a case of the Chromecast blindly trying the HTTPS endpoing, since this is preferred on that side, and it failing, and then it not retrying HTTP. Maybe changing that setting will help, though I'm not overly confident.
> 
No it doesn't work in either configuration (more questions on that below...)

> Self-signed certs are always going to be a bane, just because these "smart" (read dumb) devices choke on them. And in this case I'd lean towards this being a Chromecast issue rather than a Jellyfin issue.

Actually...this apparently is not true (again, more on that below...)

> With the existence of LetsEncrypt, this simply is no longer true. Getting 3rd party certs is trivial. Plus, a reverse proxy is almost always the ideal solution for this, as it's far more flexible in its SSL configuration than Jellyfin can ever be. They're trivial to set up even on Windows and well-documented. If you're accessing JF over the internet _anyways_, then at least one port has to be reachable, and making LE work in that case is thus easy.

I guess we will agree to disagree on this.  I'm fairly technical (worked in many IT jobs) and even so this took me quite a while to get going.  I've spent a good portion of the past week learning to setup nginx on my router as well as understanding how LE works and the limitations of the acme script.  While my ISP blocking port 80 isn't the standard, it isn't exactly unheard of and this means purchasing a DNS name or working solely with DDNS which complicates the situation even more.
Prior to JF I have had at least half a dozen different web services running on my media center for various purposes and all of them worked with relatively little configuration beyond knowing how to generate a self-signed cert and install that on devices.  I personally believe that issues like this are a barrier of entry to JF which is unfortunate because while I am still mainly a Plex user I like to see competition and thing more people should be trying JF out.

Anyway, let me talk a little more about the above points, because since I wrote that I have indeed got my nginx server up.  Despite the time I am glad I did so because once you have it all configured there are indeed some advantages other than using standard port forwards and configuring SSL on all your internal services.  My setup right now is like this:

- I use an A record of "server1" for my registered domain name "mydomain.com" that points to my router's WAN.
(This is actually a dynamic A record which my router keeps up-to-date.)

- I have multiple CNAME records configured such as "jellyfin.mydomain.com" which points to "server1.mydomain.com"

- Using the appropriate CNAME, the request hits my router and nginx directs it appropriately based on the server_name directives in my sites-enabled directory. 

- I have a self-signed certificate installed as the default certificate which currently all my nginx https proxied sites are using for the external connections.  For clarification when I say "self-signed" they are actually signed by an intermediate signing authority which was created by a self-signed RootCA.
This certificate is issued for server1.mydomain.com, but also has a wildcard SAN for *.mydomain.com.

In this configuration my chromecasting works perfectly!  By this I mean I am able to connect to https://jellyfin.mydomain.com and cast to my devices.  **_Therefore it is **untrue** that the Google mini devices will not work with self-signed certificates._**

A couple of comments about this based on the points we discussed above:
This all works great it my "Secure connection mode:" is set to "disabled."
When set to disabled, the dashboard advertises the following:

LAN address: http://10.10.10.100:8920
WAN address: http://jellyfin.mydomain.com:8920

The above make sense as far as JF is concerned, because I populated the "External Domain" field with jellyfin.intechral.com.  I'm not sure it really matters what it is set to in this mode since JF is simply going to serve out http to whatever hits it over 8920.  It is the responsibility of the reverse-proxy to handle all https connections.

Again, when set in this mode everything works fantastic.  I can connect either over the LAN address or the WAN address and stream to my devices.  Assuming:
- I connect to the WAN address of https://jellyfin.mydomain.com:443 which is my nginx server
- Technically I can't connect to the LAN address and cast because of the issue in Chrome only allowing casting to localhost over non-https sites.  However I can either cast fine from the JF server itself (i.e. opening up a webpage to localhost on that system).  Or, I can setup a port forward on any other system to forward 127.0.0.1:anyport to 10.10.10.100:8920 and can stream here.  This is a bit of a hack, but my point is that the casting works great as far as JF and the google device are concerned.  This is only needed because Chrome is a PITA.

What is further-more interesting is that if instead I set "Secure Connection Mode" to "Handled by reverse proxy" the dashboard advertises:

LAN address: https://10.10.10.100:8920
WAN address: https://jellyfin.mydomain.com:8920

A couple of reasons why the above doesn't make much sense:

a) As I argue above, especially if you are saying that https is being handled by a reverse proxy, there simply shouldn't be a need to access it over that proxy on your internal network.  Therefore I would argue that LAN connections should have the option of going over http.
b) More importantly, the WAN address would be incorrect when using a reverse proxy.  The reverse proxy will usually be accessible over 80/443 so to hit JF from the WAN you should be visiting those ports to have the reverse proxy direct you appropriately internally.  Advertising the WAN address with the local port seems to make no sense.

Regardless if you agree with those point or not, I can tell you that by far the biggest problem of setting the "Handled by reverse proxy" is that it simply doesn't work.  I am still able to connect to either the LAN address or  https://jellyfin.mydomain.com (no port 8920, remember I'm connecting to the reverse proxy) and I am able to enumerate and choose my cast device.  However, when I press play on the media absolutely nothing happens.  No play, no error, just nothing.

This is why I am very interested in what exactly the "Handled by reverse proxy" option is meant to do as it seemingly not only doesn't work, but actually breaks functionality that is available with simply "disabled."  I asked about this here (https://github.com/jellyfin/jellyfin/issues/1396#issuecomment-529680061) as well but didn't get a reply yet.

So in the end, I seem to have a working configuration using reverse-proxy and self-signed certificates, but why it is working doesn't seem to make much sense primarily because:
1) I've been told/read in multiple places that my google device won't work with a self-signed cert.
2) JF doesn't work when told it is working with a reverse-proxy, it only works if I tell it not to use http at all.

Any explanation for any of this?

**Comment by bengalih** [comment]
Recommended in #1396 to set the https port number to 443 (what nginx listens on).

Tried this, it doesn't work either:

Setting the public https port to 443 (which is what nginx listens on) does result in the Dashboard showing:

LAN Address:
https://10.10.10.102:8920
WAN Address:
https://jellyfin.mydomain.com:443

However things continue to not function as described in #1725.
For the record, if I change the local https port to 443 as well it also doesn't work.

**Comment by PrplHaz4** [comment]
This is still a problem, and there are numerous issues open to address the different parts.

@bengalih if you could provide your findings with 10.5.2 here that would be helpful: https://github.com/jellyfin/jellyfin-docs/issues/196

**Comment by Lerrrtaste** [comment]
This is not fixed
