### ISSUE TITLE
Multi-disc movies are not matched correctly

### ISSUE THREAD

**Issue by KeepBotting** [jellyfin/jellyfin#1745]
**Describe the bug**
Movies split across two or more files are not scanned properly. The first file is matched as if it is the entire film, while subsequent files are relegated to an "Additional Parts" section below the main page content (see screenshot). Playback stops as the first file concludes.

**To Reproduce**

1. Obtain a movie split across two files and apply sane naming scheme, e.g. `Movie.Name.CD1.mkv` and `Movie.Name.CD2.mkv`
2. Scan a library containing this movie
3. Note results similar to screenshot

**Expected behavior**

Scanner should recognize multi-disc titles and display correct runtime.
Playback should traverse multiple files if named according to the docs: https://jellyfin.readthedocs.io/en/latest/media/movies/

**Screenshots**

![](https://branon.me/files/NTQxOWF.png)

**Additional Information**
My exact directory structure and file naming scheme is as follows:
```
Total\ Recall\ (1990)
├── Total\ Recall\ (1990)-CD1.avi
├── Total\ Recall\ (1990)-CD1.idx
├── Total\ Recall\ (1990)-CD1.sub
├── Total\ Recall\ (1990)-CD2.avi
├── Total\ Recall\ (1990)-CD2.idx
├── Total\ Recall\ (1990)-CD2.sub
```

**System (please complete the following information):**
 - OS: Docker
 - Browser: Firefox
 - Jellyfin Version: `10.3.5`, `10.4.0`, `10.6.3`
 - Reverse proxy: nginx

**Comment by olebittner** [comment]
This issue is still valid.

Playing a multi-disc movie only plays the first disc and the next disc is shown under `Additional Parts`. Extras and BTCs will not be displayed at all.

**Example:**
The directory
```
The Lord of the Rings - The Fellowship of the Ring (2001) - Special DVD Extended Edition
├── The Lord of the Rings - The Fellowship of the Ring (2001) - Special DVD Extended Edition - dvd1.mkv
├── The Lord of the Rings - The Fellowship of the Ring (2001) - Special DVD Extended Edition - dvd2.mkv
├── extras
│   ├── A Day in the Life of a Hobbit.mkv
│   ├── Behind the Scenes.mkv
│   ├── Big-atures.mkv
│   ├── Bridge of Kazhad Dum - Prerender vs Final.mkv
│   ├── Costume Design.mkv
│   ├── Council of Elrond - Alternative Version.mkv
│   ├── Designing Middleearth.mkv
│   ├── Digital Grading.mkv
│   ├── Editorial - Assembling an Epic.mkv
│   ├── From Book to Script.mkv
│   ├── History of the World.mkv
│   ├── JRR Tolkien - Creator of Middleearth.mkv
│   ├── Location scouting - Amon Hen.mkv
│   ├── Musci for Middleearth.mkv
│   ├── Peter Jackson as Bilbo Baggins.mkv
│   ├── Scale.mkv
│   ├── Storyboards and Pre-Viz - Making Words into Images.mkv
│   ├── The Fellowship of the Cast.mkv
│   ├── The Road goes ever on ....mkv
│   ├── The Soundscapes of Middleearth.mkv
│   ├── The two Towers - Theatrical Preview.mkv
│   ├── Weta Digital.mkv
│   └── Weta Workshop.mkv
```
will be displayed as:
![Screenshot](https://i.imgur.com/SdmBd4I.jpg)

**System:**
- OS: Debian 10
- Browser: Firefox
- Jellyfin Version: 10.5.0
- Reverse proxy: nginx

**Comment by CoolDreamZ** [comment]
This issue also affects me as I have many multi-part movies and I want to migrate over to Jellyfin

**Comment by cvium** [comment]
This does not look like a bug. As far as I can tell not even Emby does what you want it to. Feature requests belong here: https://features.jellyfin.org

**Comment by giddie** [comment]
This feature request looks related: https://features.jellyfin.org/posts/198/handle-movies-with-multiple-split-files-as-one-item

**Comment by KeepBotting** [comment]
Thanks guys! :smile:

**Comment by wangdlhebei** [comment]
![1627639860(1)](https://user-images.githubusercontent.com/44386804/127638224-e15b1d0b-a585-4b15-9e05-d5e8c399ad9f.png)
我可能已找到问题处，请大家研究解决办法来呀，哈哈哈
