### ISSUE TITLE
Jellyfin crash System.IO.IOException Unable to read data from the transport

### ISSUE THREAD

**Issue by drgnomage** [jellyfin/jellyfin#175]
Behaviour:
Jellyfin keeps randomly crashing.

Logs:
Dec 15 11:36:49 Media dotnet[2669]:   Metadata:
Dec 15 11:36:49 Media dotnet[2669]:     encoder         : libebml v1.3.6 + libmatroska v1.4.9
Dec 15 11:36:49 Media dotnet[2669]:     creation_time   : 2018-12-02T08:17:59.000000Z
Dec 15 11:36:49 Media dotnet[2669]:   Duration: 00:22:03.42, start: 0.000000, bitrate: 3430 kb/s
Dec 15 11:36:49 Media dotnet[2669]:     Stream #0:0: Video: h264 (High), yuv420p(progressive), 1280x720, SAR 1:1 DAR 16:9, 23.98 fps, 23.98 tbr, 1k tbn, 96k tbc (default)
Dec 15 11:36:49 Media dotnet[2669]:     Metadata:
Dec 15 11:36:49 Media dotnet[2669]:       BPS-eng         : 3301969
Dec 15 11:36:49 Media dotnet[2669]:       DURATION-eng    : 00:22:03.406000000
Dec 15 11:36:49 Media dotnet[2669]:       NUMBER_OF_FRAMES-eng: 31729
Dec 15 11:36:49 Media dotnet[2669]:       NUMBER_OF_BYTES-eng: 546230832
Dec 15 11:36:49 Media dotnet[2669]:       _STATISTICS_WRITING_APP-eng: mkvmerge v23.0.0 ('The Bride Said No') 64-bit
Dec 15 11:36:49 Media dotnet[2669]:       _STATISTICS_WRITING_DATE_UTC-eng: 2018-12-02 08:17:59
Dec 15 11:36:49 Media dotnet[2669]:       _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
Dec 15 11:36:49 Media dotnet[2669]:     Stream #0:1: Audio: aac (HE-AAC), 48000 Hz, stereo, fltp (default)
Dec 15 11:36:49 Media dotnet[2669]:     Metadata:
Dec 15 11:36:49 Media dotnet[2669]:       BPS-eng         : 126718
Dec 15 11:36:49 Media dotnet[2669]:       DURATION-eng    : 00:22:03.421000000
Dec 15 11:36:49 Media dotnet[2669]:       NUMBER_OF_FRAMES-eng: 31018
Dec 15 11:36:49 Media dotnet[2669]:       NUMBER_OF_BYTES-eng: 20962737
Dec 15 11:36:49 Media dotnet[2669]:       _STATISTICS_WRITING_APP-eng: mkvmerge v23.0.0 ('The Bride Said No') 64-bit
Dec 15 11:36:49 Media dotnet[2669]:       _STATISTICS_WRITING_DATE_UTC-eng: 2018-12-02 08:17:59
Dec 15 11:36:49 Media dotnet[2669]:       _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
Dec 15 11:36:54 Media dotnet[2669]: UnhandledException
Dec 15 11:36:54 Media dotnet[2669]: System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer. ---> System.Net.Sockets.SocketException: Connection reset by peer
Dec 15 11:36:54 Media dotnet[2669]:    --- End of inner exception stack trace ---
Dec 15 11:36:54 Media dotnet[2669]:    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
Dec 15 11:36:54 Media dotnet[2669]:    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
Dec 15 11:36:54 Media dotnet[2669]:    at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
Dec 15 11:36:54 Media dotnet[2669]:    at System.Net.Security.SslState.ThrowIfExceptional()
Dec 15 11:36:54 Media dotnet[2669]:    at System.Net.Security.SslState.CheckThrow(Boolean authSuccessCheck, Boolean shutdownCheck)
Dec 15 11:36:54 Media dotnet[2669]:    at System.Net.Security.SslState.CheckOldKeyDecryptedData(Memory`1 buffer)
Dec 15 11:36:54 Media dotnet[2669]:    at System.Net.Security.SslState.HandleQueuedCallback(Object& queuedStateRequest)
Dec 15 11:36:54 Media dotnet[2669]:    at System.Net.Security.SslState.FinishHandshakeRead(Int32 newState)
Dec 15 11:36:54 Media dotnet[2669]:    at System.Net.Security.SslState.FinishHandshake(Exception e, AsyncProtocolRequest asyncRequest)
Dec 15 11:36:54 Media dotnet[2669]:    at System.Net.Security.SslState.RehandshakeCompleteCallback(IAsyncResult result)
Dec 15 11:36:54 Media dotnet[2669]:    at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
Dec 15 11:36:54 Media dotnet[2669]:    at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
Dec 15 11:36:54 Media dotnet[2669]:    at System.Net.AsyncProtocolRequest.CompleteUserWithError(Exception e)
Dec 15 11:36:54 Media dotnet[2669]:    at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
Dec 15 11:36:54 Media dotnet[2669]:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
Dec 15 11:36:54 Media dotnet[2669]: --- End of stack trace from previous location where exception was thrown ---
Dec 15 11:36:54 Media dotnet[2669]:    at System.Threading.ThreadPoolWorkQueue.Dispatch()
Dec 15 11:36:54 Media dotnet[2669]: System.IO.IOException
Dec 15 11:36:54 Media dotnet[2669]:    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
Dec 15 11:36:54 Media dotnet[2669]:    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
Dec 15 11:36:54 Media dotnet[2669]:    at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
Dec 15 11:36:54 Media dotnet[2669]:    at System.Net.Security.SslState.ThrowIfExceptional()
Dec 15 11:36:55 Media dotnet[2669]:    at System.Net.Security.SslState.CheckThrow(Boolean authSuccessCheck, Boolean shutdownCheck)
Dec 15 11:36:55 Media dotnet[2669]:    at System.Net.Security.SslState.CheckOldKeyDecryptedData(Memory`1 buffer)
Dec 15 11:36:55 Media dotnet[2669]:    at System.Net.Security.SslState.HandleQueuedCallback(Object& queuedStateRequest)
Dec 15 11:36:55 Media dotnet[2669]:    at System.Net.Security.SslState.FinishHandshakeRead(Int32 newState)
Dec 15 11:36:55 Media dotnet[2669]:    at System.Net.Security.SslState.FinishHandshake(Exception e, AsyncProtocolRequest asyncRequest)
Dec 15 11:36:55 Media dotnet[2669]:    at System.Net.Security.SslState.RehandshakeCompleteCallback(IAsyncResult result)
Dec 15 11:36:55 Media dotnet[2669]:    at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
Dec 15 11:36:55 Media dotnet[2669]:    at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
Dec 15 11:36:55 Media dotnet[2669]:    at System.Net.AsyncProtocolRequest.CompleteUserWithError(Exception e)
Dec 15 11:36:55 Media dotnet[2669]:    at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
Dec 15 11:36:55 Media dotnet[2669]:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
Dec 15 11:36:55 Media dotnet[2669]: --- End of stack trace from previous location where exception was thrown ---
Dec 15 11:36:55 Media dotnet[2669]:    at System.Threading.ThreadPoolWorkQueue.Dispatch()
Dec 15 11:36:55 Media dotnet[2669]: InnerException: System.Net.Sockets.SocketException
Dec 15 11:36:55 Media dotnet[2669]: System.Net.Sockets.SocketException (104): Connection reset by peer

My apologies for long log.

**Comment by anthonylavado** [comment]
Hi @drgnomage! :wave:

We've likely fixed this in the releases since you've tried. Do you still have this problem on our latest version, 10.2.2?

**Comment by drgnomage** [comment]
Hi @anthonylavado,

This exact issue seems to be fixed but I do occasionally still get crashes. I'll find the logs and see if I can find another issue with the same logs.
