### ISSUE TITLE
no restart button

### ISSUE THREAD

**Issue by moreje** [jellyfin/jellyfin#1755]
There is no restart button in the dashboard

**To Reproduce**
1. go to the Dasboard
2. search for restart. Only shutdown found

![Capture d’écran du 2019-09-14 12-17-06](https://user-images.githubusercontent.com/5374164/64906671-9f4f2900-d6e9-11e9-9eb1-4735dc343df5.png)

**System (please complete the following information):**
 - OS: Docker on Debian Host
 - Browser: Chrome
 - Jellyfin Version: Version: 10.3.7
 - Reverse proxy: no

**Comment by anthonylavado** [comment]
Similar to #893 (but still a separate issue). I think this is because we don't have a restart script for Docker though.

**Comment by moreje** [comment]
in Emby Docker, this button does not restart the docker itself, only the service I think.
in Jellyfin , my workaround is to set up autorestart policy to my docker...and use the shutdown button in the dashboard...
