### ISSUE TITLE
Not matching based on folder name (which contains episode information); matching on junk filename instead

### ISSUE THREAD

**Issue by yoasif** [jellyfin/jellyfin#1758]
**Describe the bug**

I have TV show episodes in that are sometimes organized like:

```
/Shows
    /Series
        /Season
            Episode S01E01
                badly-namedfile.mkv

```
These files are imported with the correct season and show, but are not matched to an episode, and so I see garbage filenames in season listings - and things are out of order. 

**To Reproduce**

1. Import file with path like: /data/tvshows/Show/Show s02/Show.S02E07.1080p.BluRay.x264/pDdWWgcjZN5YQqKEIvNkPSg2UVWAEKVl5b.mkv
2. Navigate to show season in web UI
3. File is shown without an episode number, with the correct season. Metadata like name is missing.

**Expected behavior**

Since the parent folder name of the badly named file is "Show.S02E07.1080p.BluRay.x264", I expect that the badly named file is imported as Show, season 2, episode 7.

**Logs**

**Screenshots**

![image](https://user-images.githubusercontent.com/152493/64914837-b3b21680-d727-11e9-85a1-5e7a8ce27024.png)

**System (please complete the following information):**
 - OS: [e.g. Docker]
 - Browser: [e.g. Firefox,]
 - Jellyfin Version: 10.3.7
 - Reverse proxy: none

**Additional context**

Plex does this correctly.

**Comment by anthonylavado** [comment]
Gonna say this is technically an enhancement. We handle the file naming as Emby did in 3.5.2, and they don't use Folder Path unless it is a DVD/BD rip with the appropriate folder structure.

**Comment by BugFixesAndPerformanceImprovements** [comment]
Is this being worked on? Having a library with thousands of files where this is the case would be a nightmare to go and rename each one individually.

**Comment by yllekz** [comment]
Can we please get an option to just display items based on their filename and/or folder names? I just installed Jellyfin and was also beset by this issue where it's reading a field that my files aren't actively populating. I'd rather have Jellyfin just use the folder/filename structure instead. Plex has an option for this.

**Comment by BugFixesAndPerformanceImprovements** [comment]
Seems to still be happening as of 10.7.7

<img width="830" alt="2021-09-21_045143" src="https://user-images.githubusercontent.com/58829078/134104751-028a8f30-5483-47b8-9eec-eac6abd81bc0.png">

**Comment by BugFixesAndPerformanceImprovements** [comment]
Glad to report that it's working as of 10.8.0-alpha1.

![working](https://user-images.githubusercontent.com/58829078/140195003-77048b75-c419-4db9-bbec-bed25e4a6f70.jpg)
