### ISSUE TITLE
Doesn't show up in roku, moving on.

### ISSUE THREAD

**Issue by Innomen** [jellyfin/jellyfin#1761]
This is a courtesy. Downloaded jellyfin, works on my windows 10 PC. Roku express on the same network sees nothing. Moving on. Sharing FWIW.

**Comment by anthonylavado** [comment]
Sorry, I'm not sure what you're asking/sharing?

**Comment by anthonylavado** [comment]
We don't have a Roku app published yet, as it is still in development: https://github.com/jellyfin/jellyfin-roku

Hopefully this will be completed at some point, at which time we'd invite you to try Jellyfin again 😄

**Comment by Innomen** [comment]
I found jellyfin looking for an open source DLNA server, so that my roku could find my desktop in the media player channel. Default windows media server showed up but none of the content would play. Roku tvs are everywhere, you should really make playing nice with roku a priority imo /shrugs

Good luck regardless :)
