### ISSUE TITLE
(JF 10.4.0) Clicking on a movie poster makes the page jump to the bottom

### ISSUE THREAD

**Issue by xplatinum** [jellyfin/jellyfin#1762]
**Describe the bug**
When browsing librairies or the dashboard, when you click on any link or even the background, it automatically scrolls the page all the way to the bottom.

**To Reproduce**
1. Open the library
2. Click on a movie or the background
3. Page jumps to the bottom

**System (please complete the following information):**
 - OS: Docker
 - Browser: Chrome
 - Jellyfin Version: [e.g. 10.4.0]

**Comment by joshuaboniface** [comment]
I can no longer replicate this on the current nightly in Chromium. Can anyone confirm?

**Comment by anthonylavado** [comment]
When testing the scrolling bug, I couldn't see it on Chrome or Safari as of yesterday's master.

**Comment by joshuaboniface** [comment]
OK, I think we can close this one out then, @xplatinum please let us know if you can test the latest nightlies for this and close if it looks OK now!

**Comment by xplatinum** [comment]
I was able to replicate the issue in the details page of a movie. If I
click beside the poster or around cast pictures (anywhere basically) the
page jumps to the bottom.

The main library view appears to be ok now as I was not able to replicate
it there.

**Comment by xplatinum** [comment]
I'll try it with another docker pull just to make sure I was using the latest nightly. I'll report back.

**Comment by joshuaboniface** [comment]
I can't replicate it on that page either in Chromium, maybe it's a weird cache issue?

**Comment by xplatinum** [comment]
I just did a docker pull to make sure I'm on the latest nightly and it's doing the same thing (in movie posters). Sometime it happens by just refreshing the page or clicking a library. As soon as the library loads it jumps to the bottom of the page.

I also disabled **all* my extensions and was still able to replicate.

Chrome Version 77.0.3865.90 (Official Build) (64-bit)

**Comment by xplatinum** [comment]
I don't know if it's worth anything but I went in developer mode (Elements) and when I replicate the issue by clicking the background this keeps flashing everytime I click.

class="skinHeader skinHeader-withBackground skinHeader-blurred headroom headroomDisabled headroom--unpinned"

**Comment by xplatinum** [comment]
Also not a cache issue. I did a clean install of Windows 10 in between each test.

**Comment by xplatinum** [comment]
It's also an issue on the sign-in page. I click in the password field and the focus/active field quickly goes through all other elements until it reaches the bottom.

This is getting spammed a thousand times in the Sources console of Chrome.

![log](https://i.imgur.com/IVj9jXn.png)

**Comment by dkanada** [comment]
@EraYaN were you the one messing with input for WebOS support?

**Comment by JustAMan** [comment]
@xplatinum did you check for this issue in earlier Jellyfin versions, like 10.3.7?
Also please specify exact JF version you're seeing this behaviour in.

**Comment by xplatinum** [comment]
@JustAMan the issue is not present in 10.3.7. I've tested this numerous times by going back and forth between that and nightly.

The issue started in 10.4.0 and has been present in every nightly that I've tried, including the latest one.

This bug is the reason why I'm staying on 10.3.7 at the moment. I'd love to test 10.4.0 more but it's unusable for me.

**Comment by xplatinum** [comment]
Bump

**Comment by xplatinum** [comment]
Issue has been fixed in 10.4.0 stable.

**Comment by xplatinum** [comment]
Celebrated too early. Issue still present in 1.40.0 stable.

**Comment by anthonylavado** [comment]
So, looking at this. For full disclosure, I'm running 10.4.0, and testing using Google Chrome on my Mac, and on a Windows machine. Both report a version of Version 77.0.3865.90 (Official Build) (64-bit).

> I was able to replicate the issue in the details page of a movie. If I click beside the poster or around cast pictures (anywhere basically) the page jumps to the bottom. The main library view appears to be ok now as I was not able to replicate it there.

I can't get this to happen on either version. I've tested with entries that have lots of information, including a full summary, cast & crew, and more like this, can't get it to happen.




> I don't know if it's worth anything but I went in developer mode (Elements tab) and when I replicate the issue by clicking the background this keeps flashing everytime I click.
> 
> class="skinHeader skinHeader-withBackground skinHeader-blurred headroom headroomDisabled headroom--unpinned"

This class changes based on whether or not you're at the top of the page, or scrolled down. When you're at the top, it should be:
`skinHeader skinHeader-withBackground skinHeader-blurred headroom semiTransparent`

When you have scrolled down, it is:
`skinHeader skinHeader-withBackground skinHeader-blurred headroom semiTransparent headroom--unpinned`

This differs from what you're reporting, which has the added class of "headroomDisabled".

> It's also an issue on the sign-in page. I click in the password field and the focus/active field quickly goes through all other elements until it reaches the bottom.
> 
> This is getting spammed a thousand times in the Sources console of Chrome.
> 
> ![log](https://camo.githubusercontent.com/5e00e299c9390d4beedd2b8af571e6b80d08cb22/68747470733a2f2f692e696d6775722e636f6d2f49566a396a586e2e706e67)

This is where things get interesting. That shouldn't be firing unless you're pressing the keyboard. The relevant file is here: https://github.com/jellyfin/jellyfin-web/blob/release-10.4.z/src/components/keyboardnavigation.js

Essentially, any press of Arrow Up, Right, Down, or Left, will trigger that message appearing in the console. It seems like either a keyboard key is stuck somewhere, or something you're pressing/doing on the system is emulating a keyboard key press.

Out of curiosity - is there any peripheral connected? Either wired, or wirelessly, that could be stuck? It could be a remote control in a desk drawer with something on it? Is there a bluetooth keyboard at the bottom of a backpack?

**Comment by xplatinum** [comment]
@anthonylavado You might be on to something! I have a Logitech G29 steering wheel attached. I will try to replicate the issue with it disconnected.

**Comment by xplatinum** [comment]
You were right, it was the steering wheel. Mystery solved. Thanks Anthony!

**Comment by joshuaboniface** [comment]
Navigation by steering wheel? :thinking: :laughing: Glad it's sorted!

**Comment by anthonylavado** [comment]
> Navigation by steering wheel? 🤔 😆 Glad it's sorted!

@joshuaboniface That's the best kind (when you're driving)

@xplatinum Glad to help! I used to do Tech Support, and this kind of thing would happen a lot 😆
