### ISSUE TITLE
HTTPS WebUI causes connection reset

### ISSUE THREAD

**Issue by dragon2611** [jellyfin/jellyfin#177]
Fresh install of Ubuntu 18.04 server, added jellyfish repo and enabled universe repo.

Jellyfish installs and starts successfully but the https port (8920) just leads to connection reset when attempting to access via both firefox and chrome.

Tried custom SSL Cert (self signed) incase it wasn't binding to an SSL cert and same issue.

I can see jellyfin binds to 8920 and there is no firewall configured on the machine running jellyfin at the moment.

`tcp        0      0 0.0.0.0:8920            0.0.0.0:*               LISTEN      1382/jellyfin`

`root@jellyfin:/etc/ssl# iptables -nvL
Chain INPUT (policy ACCEPT 770 packets, 277K bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 855 packets, 189K bytes)
 pkts bytes target     prot opt in     out     source               destination
root@jellyfin:/etc/ssl#`

**Comment by dragon2611** [comment]
Ah right it seems HTTPS does work if you add a custom certificate, the problem was it couldn't access the certificate file although there was no error/feedback to indicate this was the case.  

If possible jellyfin should install/use a self-signed cert out of the box to get started.
Letsencrypt support would be nice for those wanting to use a domain name but that's a feature request for further down the line ;-)

**Comment by joshuaboniface** [comment]
This was AFAIK an issue with Emby too, I'd recommend using a reverse proxy if at all possible. We haven't looked too much at the HTTP server code.

**Comment by dragon2611** [comment]
I now have it running behind HAproxy ;-)

**Comment by joshuaboniface** [comment]
A good choice, I do the same! This would be worth investigating though, or disabling altogether.

**Comment by JustAMan** [comment]
I think we'd better follow Unix philosophy and let simple tools do their jobs. I'd rather remove https from jellyfin completely offering ability to bind to local host only and add some docs in reverse proxying it, but not add self-signed certificate.

If you ship anything security-related you have to be sure it's uo to date, or it's just giving you false feeling of protection.

**Comment by joshuaboniface** [comment]
This is not so much a bug, as an incomplete feature.

Emby shipped a self-signed cert, which was likely generated on build to enable HTTPS mode by default. We aren't doing this because it's bad practice.

However, it appears that there is actually NO way of turning SSL support off inside the Emby settings menu. Which is also pretty ridiculous.

I've created a feature issue to get this fixed up, but for now the answer is that you must generate a self-signed (or legit) certificate and add it to the Emby configuration manually in the Advanced settings; OR use a reverse proxy (as you have done) to the HTTP port to get SSL support.

**Comment by JustAMan** [comment]
@dragon2611 can we close this issue as you've solved your particular problem? General discussion of HTTPS will be continued in #192.

**Comment by joshuaboniface** [comment]
Closing this one out as #192 tracks the underlying issue(s).
