### ISSUE TITLE
Music Videos and Books do not Appear in Favorites

### ISSUE THREAD

**Issue by jacobwhall** [jellyfin/jellyfin#1774]
Hi there,

When I click on Favorites on the home screen, favourited content from my Movies, TV Shows, and Music libraries appear. However, favourited Music Videos and Books do not appear.

I am using Jellyfin 10.3.7 hosted on Ubuntu.

**Comment by miguelrdev** [comment]
I am experiencing this issue. Favorites do not appear for my library of type 'Music Videos'.

Jellyfin Version: 10.7.7
Debian 11.1

If there are any logs that would be useful to provide, let me know.

**Comment by s7m0n** [comment]
same here. I only use type MusicVideos for my clips. 
None of them is listed in the favorites page.
Is there some other way to filter/search for favorites only?

**Comment by baberarjumand** [comment]
As of Mar 9 2025, this issue still exists in the latest versions of the Jellyfin server. I am unable to view my favorite music videos in the web interface and the Android client app.

Hope someone sees this and addresses this, seems like a rather simple bug to fix.

**Comment by theguymadmax** [comment]
As of February 17, 2025, [music videos](https://github.com/jellyfin/jellyfin-web/pull/6483) were added to the favorite sections on the master. It will be a new feature when Jellyfin 10.11 is released.
