### ISSUE TITLE
Windows installer (NSIS) creates incorrect data directories when spaces are included

### ISSUE THREAD

**Issue by BlackSiO2** [jellyfin/jellyfin#1776]
**Describe the bug**
When changing the default data location directory from C:\ProgramData\Jellyfin\Server to a directory containing a space such as C:\Test Data\Etc\Etc the installer will create the data directory with everything after the space removed.  In this example it would be C:\Test\

**To Reproduce**
Run windows installation (10.4.0 RC nightlies)
Change default data location directory to a directory containing a space
Check where the installer actually created the data location

**Expected behavior**
Manually chosen data directory in the installer should match the directory created by the installer.

**System (please complete the following information):**
 - OS: [Windows]
 - Browser: [N/A]
 - Jellyfin Version: [10.4.0 RC nightlies]
 - Reverse proxy: [N/A]

**Comment by anthonylavado** [comment]
Working on this.

**Comment by anthonylavado** [comment]
This is fixed in the next nightly.
