### ISSUE TITLE
WinTV HVR-950q not detected for TV

### ISSUE THREAD

**Issue by andrewfer000** [jellyfin/jellyfin#1778]
It seems that my WinTV 950q is not detected as a tuner for TV. There is support for M3U playlists and such. is there a way to work around this issue. JellyFin is the best media server I´ve worked with and this is the only issue keeping me from going away from PLEX and Kaffene/VLC

**Comment by andrewfer000** [comment]
Im using Ubuntu 19.04

**Comment by andrewfer000** [comment]
This issue seems to be getting no attention so im going to close this issue and open a different one

**Comment by cvium** [comment]
> This issue seems to be getting no attention so im going to close this issue and open a different one

That's not how this works

**Comment by anthonylavado** [comment]
@andrewfer000 Apologies, we’re all volunteers doing this in our spare time.

Hauppauge hardware isn’t natively supported. Others (like Plex) have written their own drivers to connect to them, or they use the V4L subsystem (Kaffene/VLC).

This means you’ll have to use another program in between. Right now, I use my Hauppauge through TVHeadend and Antennas.

I can describe more later.

**Comment by andrewfer000** [comment]
@anthonylavado

Thank you very much for this information. I never knew a program like TVHeadend existed.  If you know/have a quick setup guide I will be greatful if you can point me to it. Thank you I appreciate it!

**Comment by andrewfer000** [comment]
So I got TVheadend working well with some minor lag issues (and its kinda slow) here and there and playback errors on mobile but it works.
