### ISSUE TITLE
live TV only plays on local network

### ISSUE THREAD

**Issue by daveraver** [jellyfin/jellyfin#1780]
**Describe the bug**
Android 9 mobile plays live TV on local network by m3u tuner but not on remote networks. Media library plays on both network, local and remote.

**To Reproduce**

1. Play a live TV channel on remote networks
2. It hangs, nothing happens, even you cannot to exit from black screen on mobile device

**Expected behavior**
play a live TV channel on remote networks as I am able to do when I use the same server local network

**Logs**
nothing is reported on logs

**Screenshots**

**System (please complete the following information):**
 - OS: Docker on dietpi 
 - Browser/app: android 9 app
 - Jellyfin Version: 10.3.7 ls15 linuxserver.io

**Additional context**
Live tv doesn't work on chrome browser on local network on debian 9 pc inside the server with same server user as the one tested on android 9 mobile version.
I have tested with openvpn connection outside local network of course, and now I can play live TV perfectly.

**Comment by ddurdle** [comment]
Live TV fully works for me on the nightly, but it also worked for me on 10.3.7.

Is the ffmpeg being triggered when you playback?  If so, is there anything in the log?

You confirmed that your IPTV doesn't have any IP locks in place?  Some IPs restrict the number of IPs hitting a login account.

**Comment by daveraver** [comment]
I have to test better again, but now I have been able to see that SD channels doesnt work so I have to install ffmpeg for SD channels. Anyway my test was on 1 HD channel. I will test again, I have it mounted on a SBC rock64 RK3328. I will report again when I test it again. 
Thanks for your reply, mate

**Comment by anthonylavado** [comment]
I think we might have merged some stuff on this... Closing for now, look out for the next release of Android/Android TV.
