### ISSUE TITLE
Movies with a one-character title don’t show up in library

### ISSUE THREAD

**Issue by whtv** [jellyfin/jellyfin#1781]
In my case it’s a file named "A (1998).mkv" – a movie called A from 1998. It does show up (under a wrong title of course) if I rename it "A1 (1998).mkv".

**Comment by anthonylavado** [comment]
@whtv Hey there, could you provide us with some more information?

What version are you using? Which operating system?

**Comment by JustAMan** [comment]
I think it might be JF trying to be clever by dropping articles. Can you try with any 1-letter move that's not "A" to check this?

**Comment by anthonylavado** [comment]
I will say, I did try by renaming a blank video file as “A (1998).mkv” and it seemed to work for me...
