### ISSUE TITLE
hoping settings to let the jellyfin getting metadata through proxy

### ISSUE THREAD

**Issue by WarmColor** [jellyfin/jellyfin#1783]
On some locations, it's hard to get metadata from embedded metadata provider directly, such as imdb.
It will be appreciate if we have the settings to configure jellyfin getting metadata through proxy in later releases.

**Comment by JustAMan** [comment]
I think it can already be done by setting environment variables `http_proxy` and `https_proxy`, at least on Linux. Not sure we need to add support for this in the server itself.

**Comment by WarmColor** [comment]
> I think it can already be done by setting environment variables `http_proxy` and `https_proxy`, at least on Linux. Not sure we need to add support for this in the server itself.

Thank you, finally I figured it out. 
I installed docker version Jellyfin in Sonolygy NAS.
I run two another dockers, shadowsocks and privoxy.
One provide Socks5 proxy, the other turn it into http proxy, and then set http_proxy for Jellyfin docker in environment variable.

**Comment by biaji** [comment]
Is it possible to use socks proxy directly?

**Comment by WarmColor** [comment]
> Is it possible to use socks proxy directly?

老哥国人？
目前看没有办法直接使用Shadowssocks，开发组似乎也没有这个计划，
需要将Socks代理转成http代理再使用
![Snipaste_2020-04-17_14-20-11](https://user-images.githubusercontent.com/13973339/79538358-ca05c380-80b6-11ea-9b85-ba14d463dcf9.jpg)

**Comment by biaji** [comment]
> > Is it possible to use socks proxy directly?
> 
> 老哥国人？
> 目前看没有办法直接使用Shadowssocks，开发组似乎也没有这个计划，
> 需要将Socks代理转成http代理再使用
> ![Snipaste_2020-04-17_14-20-11](https://user-images.githubusercontent.com/13973339/79538358-ca05c380-80b6-11ea-9b85-ba14d463dcf9.jpg)

我也试着用privoxy做代理。但仍然失败： privoxy的log看到tmdb的访问一直报类似：
```
192.168.1.202 - - [30/Apr/2020:22:42:39 +0800] "CONNECT api.themoviedb.org:443 HTTP/1.1" 503 7784
```
兄弟有没有遇到类似的情况?

**Comment by biaji** [comment]
I look through the code and find jellyfin based on [HttpClient](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient) which doesn't support socks proxy directly.

Maybe I should modify HttpClientManager.cs  to add support for this feature.

**Comment by caryyu** [comment]
If somebody is interested in it and wants to learn ASP.NET, can look into here: https://stackoverflow.com/questions/52526095/how-to-configure-web-proxy-for-httpclient-created-directly-via-httpclientfactory

**Comment by LSTemp** [comment]
> I think it can already be done by setting environment variables `http_proxy` and `https_proxy`, at least on Linux. Not sure we need to add support for this in the server itself.

and this way ruined reverse proxy - nice solve! jellyfin now have access to any requiared sites, but i dont have access now to jellyfin web-inteface.

**Comment by secretxu** [comment]
how can i set proxy for jellyfin-server on windows？

**Comment by AnonymousWebHacker** [comment]
> > Is it possible to use socks proxy directly?
> 
> 老哥国人？ 目前看没有办法直接使用Shadowssocks，开发组似乎也没有这个计划， 需要将Socks代理转成http代理再使用 ![Snipaste_2020-04-17_14-20-11](https://user-images.githubusercontent.com/13973339/79538358-ca05c380-80b6-11ea-9b85-ba14d463dcf9.jpg)

If there are ways
You can use for example tun2sock , it simply raises a virtual interface, example eth2 , which in its configuration tells it to connect to a server, either http proxy, sock4, sock5 , shadowsock, wg ..etc

**Comment by AnonymousWebHacker** [comment]
> how can i set proxy for jellyfin-server on windows？

If you read the old comments, you can add a system-wide proxy, a global proxy,

**Comment by Lunaticzy** [comment]
> how can i set proxy for jellyfin-server on windows？

I had the same problem as you, I used [netch](https://github.com/netchx/netch) to solve it, and only set the process mode to use it, so that it could only proxy the jellyfin server.
