### ISSUE TITLE
Nightly's manually Zip's are not been created

### ISSUE THREAD

**Issue by jaylex32** [jellyfin/jellyfin#1784]
**Describe the bug**

The latest nightly's are not been created in zip to install it manually only with installer. Any fix? Thanks!!

**Comment by jaylex32** [comment]
please provide zip installation for the nightly's!

**Comment by anthonylavado** [comment]
Our build process has been changing, and all packages needed to be updated. As a result, the Windows ZIP was not being created. It should be available within the next nightly. Otherwise, we recommend using the officially released stable versions.

**Comment by jaylex32** [comment]
Ok, now the nightly builds are showing but there's no data inside the zip build, please fix!!

**Comment by joshuaboniface** [comment]
I can confirm the issue with the Zips, for whatever reason the `zip` command is failing for the Windows builds and compressing none of the files that are present, and Portable builds simply aren't completing. Taking a look.

**Comment by joshuaboniface** [comment]
Tonight's nightly should be good :+1:

**Comment by nextlooper42** [comment]
Since 11.10.2019 there has been no nightly release. Broken again? @anthonylavado

**Comment by anthonylavado** [comment]
>Since 11.10.2019 there has been no nightly release. Broken again? @anthonylavado 

@nextlooper42 Nightlies only get created if something gets merged. If nothing is merged, there are no nightlies needed because there are no changes.

**Comment by barolo** [comment]
@joshuaboniface It's still broken for linux/distros

**Comment by anthonylavado** [comment]
@barolo Yes, this is known. The master branch is going through a conversion to .NET Core 3.0, which is still in progress.
