### ISSUE TITLE
is there have a way to set max video quality?

### ISSUE THREAD

**Issue by sheiy** [jellyfin/jellyfin#1786]

**Comment by JustAMan** [comment]
Could you please elaborate your question? It's unclear to me what and where you want to set, and what is a desired outcome.

**Comment by sheiy** [comment]
I put a height quality video into jellyfin but my uplink bandwidth can not support play it ,  so I need a function to set the webplayer's max quality for all video to relieve video suspend.

**Comment by joshuaboniface** [comment]
@sheiy This is already a feature - each user has a configuration setting to set a max off-network video bandwidth, which then limits what they can stream out. For instance if you set this to 5Mbps, the most they could stream would be 5Mbps videos (and the server will transcode as required to enable this).

**Comment by sheiy** [comment]
@joshuaboniface great thanks,I found it
