### ISSUE TITLE
is there have a way to set use client decode

### ISSUE THREAD

**Issue by sheiy** [jellyfin/jellyfin#1792]

**Comment by anthonylavado** [comment]
Sorry, I’m not sure I understand. Do you mean to use the client machine to decode the video?

If so, it doesn’t really work without a native app, since we run in the browser.

**Comment by sheiy** [comment]
I see, thanks for your reply

**Comment by yunyuyuan** [comment]
@anthonylavado Could you guys give an option with native app,my server machine's CPU/GPU performance is not good,so I wish I can use native app decoding to watch some Hard-to-Decode(like 4K, H.265) videos.
