### ISSUE TITLE
Web frontend broken on Debian nightly packages 20190925 and 20190926

### ISSUE THREAD

**Issue by 0x20Man** [jellyfin/jellyfin#1799]
**Describe the bug**
Trying to access the web frontend using the Debian nightly packages 20190925 and 20190926 it display the error message: *"Could not find file 'jellyfin-web/index.html'."*

Package 20190924 works as expected.

**To Reproduce**
I tried to access to it via a reverse proxy and directly via IP address : port, same error message. In the proxy logs, these are the files it's trying to load:

```
redacted redacted - [26/Sep/2019:17:52:49 +0200] "GET /jellyfin HTTP/1.1" 302 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0"
redacted redacted - [26/Sep/2019:17:52:49 +0200] "GET /jellyfin/web/index.html HTTP/1.1" 404 50 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0"
redacted redacted - [26/Sep/2019:17:52:50 +0200] "GET /jellyfin/web/serviceworker.js HTTP/1.1" 404 56 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0"
redacted redacted - [26/Sep/2019:17:52:50 +0200] "GET /jellyfin/web/components/serviceworker/notifications.js HTTP/1.1" 404 96 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0"
```

 - OS: Debian Buster (both server and desktop)
 - Browser: Firefox 69
 - Jellyfin Version: jellyfin-nightly 20190926 and 20190925
 - Reverse proxy: lighttpd

**Comment by joshuaboniface** [comment]
This one is a known issue until #1793 is in - the Webpack build wasn't being put into the right place. Hopefully this will be fixed in tonight's nightly.

**Comment by 0x20Man** [comment]
I wasn't aware that was a known issue and wanted to track it. I'll try the new packages and keep you posted.

**Comment by joshuaboniface** [comment]
I'm glad you did, I only noticed it last night after fixing everything :)

**Comment by sachk** [comment]
I had the same issue, but I built from @joshuaboniface's pull request and it works fine now.

**Comment by 0x20Man** [comment]
With 20190927 It seems you also have fixed another issue I had with the web client about transcoding MKV, I did a quick test and it's working well here.
