### ISSUE TITLE
 GPG error: https://repo.jellyfin.org/linuxmint tina Release: Signed file isn't valid, got 'NODATA' 

### ISSUE THREAD

**Issue by lukastheblack** [jellyfin/jellyfin#1800]
I am trying to install jelly fin on Linux Mint using the method for Debian/Ubuntu listed on https://jellyfin.org/downloads/, but when I get to the _apt update_ step, I receive the error during apt update
```
E: Failed to fetch https://repo.jellyfin.org/linuxmint/dists/tina/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: The repository 'https://repo.jellyfin.org/linuxmint tina InRelease' is not signed.
```
After following the instructions, my jellyfin.list looks like 
`deb [arch=amd64] https://repo.jellyfin.org/linuxmint tina main`

Is this not a valid repository?

**Comment by anthonylavado** [comment]
So no, we don't have a specific Linux Mint repository. The closest you can do is switch it to the Ubuntu Bionic repository, so change the .list to:
`deb [arch=amd64] https://repo.jellyfin.org/ubuntu bionic main`
