### ISSUE TITLE
[Source build] ERROR: The linux-x64 platform requires the following utilities:   docker

### ISSUE THREAD

**Issue by barolo** [jellyfin/jellyfin#1806]
Platform: Linux Gentoo x64

I was building jellyfin from source for months with "build linux-x64 all", it was hassle free and took seconds. 
Now I'm getting this: "ERROR: The linux-x64 platform requires the following utilities:
  docker"
I don't want to use nor pull docker as dependency. Is there a new way to build I don't know?

**Comment by joshuaboniface** [comment]
We've moved to Dockerization of all builds to unify and streamline them, including the required building of jellyfin-web that now occurs. I recommend using the Docker build, however you can run the script `deployment/linux-x64/docker-build.sh` under your host system if you wish - just note that you now need `yarn` and `nodejs` to build the WebUI.

**Comment by barolo** [comment]
@joshuaboniface  tad more annoying but works for me. Thanks

**Comment by dkanada** [comment]
You should be able to still build manually, or else IDE builds wouldn't be working. The docker requirement is just for the build script.

**Comment by barolo** [comment]
> You should be able to still build manually, or else IDE builds wouldn't be working. The docker requirement is just for the build script.

I'm not familiar with net stuff, building script served me just fine, IDE for just this feels like an overkill unless I'm developing for it
