### ISSUE TITLE
AMD AMF not working when running as Windows service

### ISSUE THREAD

**Issue by qrizzz0** [jellyfin/jellyfin#1807]
**Describe the bug**
Hello.

I have been having trouble getting AMD AMF to work with Jellyfin as a Windows service.
Whenever I run Jellyfin as service and enable AMD AMF i get a "Failed to create Direct3D device" error from FFMPEG in the transcode log.

**To Reproduce**
1. Run Jellyfin as service
2. Enable AMD AMF
3. Try to play a video file

**Expected behavior**
Video getting transcoded

**Logs**
[Pastebin](https://pastebin.com/GpsUGtgi)

**System (please complete the following information):**
 - OS: Windows 10 LTSB 2016
 - Jellyfin Version: At least 10.3.x and 10.4.0

**Possible solution**
As per [this thread](https://stackoverflow.com/questions/56268560/using-directx-from-subprocess-executed-by-windows-service) on stackoverflow I've tried downloading the source of Jellyfin and editing:
Line 2551 in MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs 
from
`-hwaccel dxva2`
to
`-hwaccel d3d11va`

When compiled this seems to run fine and my files all play properly.
I do not know how to submit a PR for Jellyfin, nor can I argue whether or not this is a good solution, but it seems to work :)

**Comment by joshuaboniface** [comment]
That conditional looks very specific to Windows, and you're the first person we've even heard mention AMF on Windows, so if it works for you, let's do it! I'll do up a PR for you, though the instructions would be: 1. Fork the project, 2. Clone your project, 3. Check out a new branch (`git checkout -b fix-amf-win`), 4. Make changes, 5. `git commit`, 6. `git push -u origin fix-amf-win`, 7. Do PR on GitHub.
