### ISSUE TITLE
Jellyfin 10.3.7 ignores IP address binding (and the fact it's IPv4)

### ISSUE THREAD

**Issue by Zopieux** [jellyfin/jellyfin#1810]
**Describe the bug**
Jellyfin provides an "advanced" setting to set the binding address. This is completely ignored by the program after a restart. This doesn't even take the IP version into account: it always binds to `:::8096` (ie. all IPv6 interfaces) even though I specify an IPv4 (see *To reproduce*).

I don't know if this is .NET trying to be smart, but if I want to bind to `192.168.178.10`, it's not an alias to `0.0.0.0` let alone `[::]`. Please let me bind to the address I need.

Other confused users include: https://github.com/jellyfin/jellyfin/issues/1679#issuecomment-528875374

**To Reproduce**
```
Settings → Advanced → Bind to local network address:
192.168.1.1  (example, use an IPv4)
```

Reflected into system.xml:
```xml
<LocalNetworkAddresses>
  <string>192.168.178.10</string>
</LocalNetworkAddresses>
```

**Expected behavior**
```
$ netstat -plant | grep 8096
tcp       0      192.168.178.10:8096       0.0.0.0:*      LISTEN      676/dotnet
```

**Actual behavior**
```
$ netstat -plant | grep 8096
tcp6       0      0 :::8096                 :::*          LISTEN      676/dotnet
```

**System (please complete the following information):**
 - OS: Linux
 - Jellyfin Version: 10.3.7

**Comment by joshuaboniface** [comment]
Confirmed, even on the latest nightlies. Seems like the setting is definitely being ignored (either by .NET as you mention, or within JF).

Will try to dig into this and see if I can find why.

**Comment by joshuaboniface** [comment]
I believe I've found the issue. At https://github.com/jellyfin/jellyfin/blob/master/Emby.Server.Implementations/ApplicationHost.cs#L618 we only have Kestrel listening on anything, rather than on the specified IP addresses. Looks like some configuration that was missed when we implemented Kestrel. I've got a solution that I'm testing out now.
