### ISSUE TITLE
Subtitles don't get automatically downloaded after adding movie

### ISSUE THREAD

**Issue by cryptobank** [jellyfin/jellyfin#1821]
Using the OpenSubtitles plugin, subtitles do not get automatically downloaded until scheduled task (Download missing subtitles) runs, or I manually download them via Edit Subtitles.  I have it set to download English & Czech subtitles automatically.

**To Reproduce**
1) Setup automatic subtitle download
2) Add a movie
3) Observe that subtitles do not get downloaded

**Expected behavior**
Subtitles should get downloaded automatically immediately after adding a movie.

**Logs**
There are no errors in logs

**System (please complete the following information):**
- Ubuntu 10.4 nightly (same issue in 10.3.7)

**Comment by NotErikUden** [comment]
The plugin is not automatic, sorry. I believe there are other plugins that allow automatic subtitle download, yet I think OpenSubtitles won't allow you to download all subtitles from your entire media library in one go.
