### ISSUE TITLE
Can't Remove (Delete) Blank Movie folder from UI

### ISSUE THREAD

**Issue by bmcgonag** [jellyfin/jellyfin#1827]
**Describe the bug**
In the Web Interface, on the most recent version I believe, I am unable to delete a movie folder path that is blank.  

When trying to add my movie folder path, I submitted the path with nothing in it, and it took it.  Now when I use the controls in the UI to try and delete that entry, it gives the 'Delete' button, but it never goes away. 

I added my actual Movie folder path after it, and am able to delete that entry and re-add as needed, but can never get the blank entry to delete / remove, and it's causing log issues with scanning the Movies. 

**To Reproduce**

1. Go to 'Library'
2. Click on 'Movies >> Manage Library'
3. Add a blank entry for your first / only folder of media.
4. Try to now delete that entry.

**Expected behavior**
The folder entry, regardless of what's in the entry, should delete properly, and probably should not allow a blank entry to start with.

**Logs**

**Screenshots**
https://box.fixitdelrio.com/cloud/index.php/s/pMr3qkf28QdXZgC

Shared link above with video of issue.

**System (please complete the following information):**
 - OS: Linux Min 19 (based on Ubuntu 18.04)
 - Browser: All
 - Jellyfin Version: 10.1.0
 - Reverse proxy: None

**Additional context**

**Comment by anthonylavado** [comment]
@bmcgonag Hey there, just wanted to check - in this description, you've listed version 10.1.0. Is that correct?

I'm not able to replicate this under 10.3.7 and 10.4 right now...

**Comment by bmcgonag** [comment]
Correct. I’ll see if I can get a newer version. I’m honestly not even sure how I got a blank entry. 

I’m running in Linux Mint, so need to check the POA I think. Can’t recall if that’s how I set it up or not. 

Brian McGonagill

**Comment by bmcgonag** [comment]
Ok, I have updated to the lates version of Jellyfin, and it did resolve an issue with certain media screens locking up on Roku, but I still cannot get rid of the blank entry in my Movies setup area.  

Is there a place I could remove it manually somehow?

**Comment by bmcgonag** [comment]
I cleared the issue after a re-install, and re-import of data.  I am unable to re-create the issue.  Closing.

**Comment by phirestalker** [comment]
i am also having this issue on 10.6.4. I renamed the folder in docker compose file and then tried to delete the library and recreate it. It does a scan, but it never deletes the library. I even changed the name back to the original directory and it will still not delete it.

What else can i try?

**Comment by Skywalker8510** [comment]
im trying to delete a library and just nothing happens the console just says executeQueuedTasks

**Comment by AndrewDavis** [comment]
I figured out how to fix my deletion problem, on Linux Mint with a recent, up-to-date version of Jellyfin:

The problem is Flatpak. Since I installed it via. Linux Mint's Software Manager this time, and it was a Flatpak installation, there's some sort of "portal" system in Flatpak for which you need to enable filesystem access to Jellyfin... Note that this is separate from `chown`, `chmod`, `umask`, etc.

Solution:

`flatpak kill org.jellyfin.JellyfinServer`
`sudo flatpak override --filesystem=/path/to/media org.jellyfin.JellyfinServer`

And then start the server up again (you can use `flatpak run`).
