### ISSUE TITLE
Handle more status codes gracefully

### ISSUE THREAD

**Issue by flyer280** [jellyfin/jellyfin#1828]
In some circumstances HTTP status codes outside of the 200-299 range can be handled rather than failing the whole request. Seeing as 400-499 are client errors, the ability to logically handle the error if possible should be allowed.

For example opensubtitles responds with a 429 too many requests if their API limit is exceeded. Rather than failing the request completely and not letting the plugin know that it was a 429 code, the main code could allow it to be handled and pass the resultant information back to the plugin for handling rather than just erroring out and dumping the response information before it gets to the plugin.

**Comment by Bond-009** [comment]
Plugins aren't required to use the `HttpClientManager` provided by the server, they can(/maybe even should) use the `System.Net.Http.HttpClient` class.

**Comment by flyer280** [comment]
Is this true of "official" plugins as well? Or only for third-party plugins that anyone may make.
