### ISSUE TITLE
Sync doesn't appear to work

### ISSUE THREAD

**Issue by dragon2611** [jellyfin/jellyfin#183]
Pressing sync in the webui doesn't appear to do anything, also admin > sync just results in a spinning circle.
It was suggested in the subreddit that this might be down to proprietary emby code.

Ideally sync should work but if that's easier said than done either removing the buttons from the webUI or displaying some kind of informative error message would also be suitable

Edit: Opps managed to mash enter in the middle of typing the title

**Comment by JustAMan** [comment]
This is a feature that is inherently tied with centralized server which we do not plan to re-implement.

Please file separate feature request describing your desired use case (I presume it's ability to view certain media offline using some client, right?).

**Comment by dragon2611** [comment]
@JustAMan Actually I don't much care for sync, however if the feature is there it should work.  Even if the resolution ends up being remove the sync buttons that's an acceptable fix.
