### ISSUE TITLE
iPad Chrome playback broken in nightly-20190930

### ISSUE THREAD

**Issue by SenorSmartyPants** [jellyfin/jellyfin#1832]
**Media Info of the file**
Tried several h.264/AAC files in MKV. These used to play as direct stream, (with audio transcoded to mp3) but nothing happens now, circle just spins.

**Logs**

**Stats for Nerds Screenshots**

**Server System (please complete the following information):**
 - OS: Docker on Linux
 - Jellyfin Version: nightly-20190930
 - Hardware settings & device: [e.g. NVENC on GTX1060, VAAPI on Intel i7 8700K]
 - Reverse proxy: [e.g. no, nginx, apache, etc.]
 - Other hardware notes: [e.g. Media mounted in CIFS/SMB share, Media mounted from Google Drive]
 
**Client System (please complete the following information):**
 - Device: [e.g. Apple iPhone XS, Xbox One S, LG OLED55C8, Samsung Galaxy Note9, Custom HTPC]
 - OS: [e.g. iOS, Android, Windows, macOS]
 - Client: [e.g. Web/Browser, webOS, Android, Android TV, Electron]
 - Browser (if Web client): [e.g. Firefox, Chrome, Safari]
 - Client and Browser Version: [e.g. 10.3.4 and 68.0]

**Comment by joshuaboniface** [comment]
@anthonylavado Can you confirm this on your iPads?

**Comment by anthonylavado** [comment]
>@anthonylavado Can you confirm this on your iPads?

@joshuaboniface Most likely not - I have an iPad 3rd gen, which would be running iOS 9. The current release is iOS 13.

I’ll try on my iPhone though.

**Comment by anthonylavado** [comment]
Okay, just tested this on the 20191005 nightly, everything appears to be playing smoothly. This is using the dotnet source on macOS, with FFmpeg 4.0.3.

I'm getting the AAC audio repacked as MP3, the video is passed through, and it's a direct stream.

Are there any FFmpeg logs for you around the time you try to stream @SenorSmartyPants?

**Comment by SenorSmartyPants** [comment]
I don't have any logs for that time. I'll try updating to the newest nightly and testing again. But that may not be until next week.

**Comment by JustAMan** [comment]
Can you try and report on Jellyfin 10.4.0 release?

**Comment by SenorSmartyPants** [comment]
Video playback is working again. 

But this issue jellyfin/jellyfin-web#368 is still happening.

**Comment by anthonylavado** [comment]
>Video playback is working again.  ...

@SenorSmartyPants okay - ty for letting us know. Gonna follow up there.
