### ISSUE TITLE
No notification when user is locked out

### ISSUE THREAD

**Issue by dkanada** [jellyfin/jellyfin#1834]
**Description**
I saw code for a UserLockedOut notification but it doesn't seem to work. The user will just silently get disabled which is causing issues for lots of people.

**Reproduce**
1. Set user login attempt option
2. Input wrong password several times
3. User gets disabled with no notification

**Expected Behavior**
Notification shows up in the `Alerts` card in the dashboard so the administrator can take action.

**Comment by JustAMan** [comment]
@dkanada this doesn't feel like a regression from 10.3.7, so I'm moving this to "next release" project.

**Comment by barronpm** [comment]
Fixed by #3148
