### ISSUE TITLE
video ON won't play when using AMF as the hw accelerator.

### ISSUE THREAD

**Issue by ycllwl** [jellyfin/jellyfin#1837]
OS: Windows 10
Jellyfin Version: 10.3.7
Hardware：Using AMD R3 Pro 2200GE
                   GPU Radeon Vega8 Graphic 
                   Support VCN1.0

Hardware accelerated encoding cannot be enabled.
Start AMF Accelerated Coding Normally on PLEX and EMBY

log information
{"Protocol":"File","Id":"d1fc34052f744949c33a4924fee743eb","Path":"E:\\电影\\BDRe(重编)\\奇幻森林.The.Jungle.Book.2016.BluRay.1080p.x264.DTS-HD.MA.7.1-HDChina\\The.Jungle.Book.2016.BluRay.1080p.x264.DTS-HD.MA.7.1-HDChina.mkv","Type":"Default","Container":"mkv,webm","Size":16816454656,"Name":"The.Jungle.Book.2016.BluRay.1080p.x264.DTS-HD.MA.7.1-HDChina","IsRemote":false,"ETag":"3dd4cb12966c95ff44ed7cbddb5f175e","RunTimeTicks":63546458112,"ReadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"RequiresClosing":false,"RequiresLooping":false,"SupportsProbing":true,"VideoType":"VideoFile","MediaStreams":[{"Codec":"h264","TimeBase":"1/1000","CodecTimeBase":"1001/48000","VideoRange":"SDR","DisplayTitle":"1080P H264","NalLengthSize":"4","IsInterlaced":false,"IsAVC":true,"BitRate":21170595,"BitDepth":8,"RefFrames":1,"IsDefault":true,"IsForced":false,"Height":1038,"Width":1920,"AverageFrameRate":23.9760246,"RealFrameRate":23.9760246,"Profile":"High","Type":"Video","AspectRatio":"1.85:1","Index":0,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"PixelFormat":"yuv420p","Level":41},{"Codec":"dts","Language":"eng","TimeBase":"1/1000","CodecTimeBase":"1/48000","DisplayTitle":"Eng DTS 7.1 Default","IsInterlaced":false,"ChannelLayout":"7.1","BitDepth":24,"Channels":8,"SampleRate":48000,"IsDefault":true,"IsForced":false,"Profile":"DTS-HD MA","Type":"Audio","Index":1,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Level":0},{"Codec":"PGSSUB","Language":"eng","TimeBase":"1/1000","CodecTimeBase":"0/1","localizedUndefined":"Undefined","localizedDefault":"Default","localizedForced":"Forced","DisplayTitle":"Eng - Default","IsInterlaced":false,"IsDefault":true,"IsForced":false,"Type":"Subtitle","Index":2,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Level":0},{"Codec":"ass","Language":"Chs&Eng","localizedUndefined":"Undefined","localizedDefault":"Default","localizedForced":"Forced","DisplayTitle":"Chs&Eng","IsInterlaced":false,"IsDefault":false,"IsForced":false,"Type":"Subtitle","Index":3,"IsExternal":true,"IsTextSubtitleStream":true,"SupportsExternalStream":true,"Path":"E:\\电影\\BDRe(重编)\\奇幻森林.The.Jungle.Book.2016.BluRay.1080p.x264.DTS-HD.MA.7.1-HDChina\\The.Jungle.Book.2016.BluRay.1080p.x264.DTS-HD.MA.7.1-HDChina.Chs&Eng.ass"}],"Formats":[],"Bitrate":21170595,"RequiredHttpHeaders":{}}

D:\jellyfin\ffmpeg-4.2.1\bin\ffmpeg.exe -hwaccel dxva2 -i file:"E:\电影\BDRe(重编)\奇幻森林.The.Jungle.Book.2016.BluRay.1080p.x264.DTS-HD.MA.7.1-HDChina\The.Jungle.Book.2016.BluRay.1080p.x264.DTS-HD.MA.7.1-HDChina.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -codec:v:0 libx264 -pix_fmt yuv420p -preset veryfast -crf 23 -maxrate 3616000 -bufsize 7232000 -profile:v high -level 4.1 -x264opts:0 subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none -force_key_frames "expr:gte(t,n_forced*3)" -filter_complex "[0:2]scale=1920:1038:force_original_aspect_ratio=decrease[sub];[0:0][sub]overlay,scale=trunc(min(max(iw\,ih*dar)\,1280)/2)*2:trunc(ow/dar/2)*2" -copyts -vsync -1 -codec:a:0 libmp3lame -ac 2 -ab 384000 -af "volume=2" -f segment -max_delay 5000000 -avoid_negative_ts disabled -start_at_zero -segment_time 3  -individual_header_trailer 0 -segment_format mpegts -segment_list_type m3u8 -segment_start_number 0 -segment_list "D:\jellyfin\DATA\transcoding-temp\95f26fe5d873763947b95858a63a0bd1.m3u8" -y "D:\jellyfin\DATA\transcoding-temp\95f26fe5d873763947b95858a63a0bd1%d.ts"

ffmpeg version 4.2.1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.1.1 (GCC) 20190807
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[matroska,webm @ 0000020a0dc8e580] Could not find codec parameters for stream 2 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, matroska,webm, from 'file:E:\电影\BDRe(重编)\奇幻森林.The.Jungle.Book.2016.BluRay.1080p.x264.DTS-HD.MA.7.1-HDChina\The.Jungle.Book.2016.BluRay.1080p.x264.DTS-HD.MA.7.1-HDChina.mkv':
  Metadata:
    encoder         : libebml v1.2.3 + libmatroska v1.3.0
    creation_time   : 2016-08-07T01:13:31.000000Z
  Duration: 01:45:54.65, start: 0.000000, bitrate: 21170 kb/s
    Stream #0:0: Video: h264 (High), yuv420p(progressive), 1920x1038 [SAR 1:1 DAR 320:173], 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)
    Stream #0:1(eng): Audio: dts (DTS-HD MA), 48000 Hz, 7.1, s32p (24 bit) (default)
    Stream #0:2(eng): Subtitle: hdmv_pgs_subtitle (default)
[AVHWDeviceContext @ 0000020a0e3b2200] Failed to create Direct3D device
Device creation failed: -1313558101.
[h264 @ 0000020a0e53d8c0] No device available for decoder: device type dxva2 needed for codec h264.
Stream mapping:
  Stream #0:0 (h264) -> overlay:main (graph 0)
  Stream #0:2 (pgssub) -> scale (graph 0)
  scale (graph 0) -> Stream #0:0 (libx264)
  Stream #0:1 -> #0:1 (dts (dca) -> mp3 (libmp3lame))
Device setup failed for decoder on input stream #0:0 : Unknown error occurred

**Comment by JustAMan** [comment]
This is fixed in #1808, which in turn is available in Jellyfin 10.4.0. Please update :)
