### ISSUE TITLE
Slack notifications to Discord not working

### ISSUE THREAD

**Issue by TRaSH-** [jellyfin/jellyfin#1839]
**Describe the bug**

Jellyfin isn't sending any notifications to my Discord channel with the webhook i created.

**To Reproduce**

Set up slack notification exactly like it did with Emby,
added /slack at the end of the webhook.
When i click on test the notification the the discord channel works.
But the rest of the notifications don't show up

**Expected behavior**

Get all the wanted notifications in my discord channel

**Logs**

Checked the logs couldn't find any errors 
**Screenshots**

N/A
**System (please complete the following information):**
 - OS: Docker on unraid using linuxserver/jellyfin image
 - Browser: Chrome
 - Jellyfin Version: Version: 10.3.7
 - Reverse proxy: not on jellyfin

**Additional context**

N/A

**Comment by crobibero** [comment]
It’s working perfectly for me on Jellyfin 10.4.0 with slack plugin 3.0.0

**Comment by TRaSH-** [comment]
The test works fine for me also,
But the real notifications when a event happens don't get sended to the discord channel.

Verzonden met ProtonMail Mobile

-------- Oorspronkelijk bericht --------
Aan 13 okt. 2019 16:52, Cody Robibero wrote:

**Comment by crobibero** [comment]
Do other notification providers work?

**Comment by TRaSH-** [comment]
Need to test it,
I only use discord notifications for info like this.
And it's exactly the same line I use in Emby.
I'll try this evening when I get home

**Comment by TRaSH-** [comment]
okay when adding the email option slack(for discord) notification starts to work also,
removing email notification and slack(for discord) notification stops working.

**Comment by JustAMan** [comment]
So is this a Jellyfin issue, or a configuration issue?

**Comment by TRaSH-** [comment]
Jellyfin,
Because the exact slack address works in Emby (Testing/Comparing Side by Side)

And after some testing the slack notification works if you enable the email notifications,
As soon you disable the email notifications the slack notification stops working.

**Comment by JustAMan** [comment]
Can you check with 10.4.0 please?
