### ISSUE TITLE
Windows - 10.4 - DVR - EPG data via XML

### ISSUE THREAD

**Issue by travman1900** [jellyfin/jellyfin#1842]
**Describe the bug**
When i choose XMLtv via the drop down i get an error "Could not find file 'jellyfin-web\components\tvproviders\.template.html'."

**Expected behavior**
ability to navigate to my xml file

![image](https://user-images.githubusercontent.com/46836974/66249426-820de900-e6f0-11e9-85ad-3f32bf906633.png)

**System (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Jellyfin Version: 10.4 nightly (20191004)
 - Reverse proxy: NA

**Comment by travman1900** [comment]
Same issue arises for schedule direct

**Comment by travman1900** [comment]
I was able to get around that by using a paste from backed up app data info. into the livetv.xml folder in config

**Comment by anthonylavado** [comment]
Hrm. This doesn’t normally happen. Could you try the step here?


https://github.com/jellyfin/jellyfin/issues/453#issuecomment-451774597

**Comment by travman1900** [comment]
Well..... when i go do that step it works.

I wonder if by me pasting info from old xml resolved what i ran into? either way it appears resolved ill report if occurs again
