### ISSUE TITLE
If manually identifying series, seasons folders are renamed to series name

### ISSUE THREAD

**Issue by AkatsukiiDesu** [jellyfin/jellyfin#1843]
**Describe the bug**
When manually identifying a series, the season names are set to the name of the series

**To Reproduce**

1. Manually identify a series
2. Refresh webpage

**Expected behavior**
Seasons naming should stay as Season 1, etc

**Screenshots**
![image](https://user-images.githubusercontent.com/1811741/66257198-32efb300-e7d9-11e9-9069-9363369b477f.png)

**System (please complete the following information):**
 - OS: Docker
 - Browser: FF
 - Jellyfin Version: [e.g. 10.4.0 nightly]

**Comment by dkanada** [comment]
This might be someone's solution for absolute episode naming, are you using a plugin?

**Comment by dkanada** [comment]
This might be someone's solution for absolute episode naming, are you using any plugins?

**Comment by AkatsukiiDesu** [comment]
> 
> 
> This might be someone's solution for absolute episode naming, are you using any plugins?

I did have the Anime plugin enabled. I've rebuilt the library with just TVDB and it doesn't seem to cause the issue :)
