### ISSUE TITLE
Avatars gone after update to 10.4.0

### ISSUE THREAD

**Issue by drikqlis** [jellyfin/jellyfin#1848]
**Describe the bug**
After update from Jellyfin 10.3.7 to 10.4.0 avatars of users stopped displaying. The problem occurs becasuse path to image was not changed from /etc/jellyfin/users/generated-string to /etc/jellyfin/users/username. The avatars are recoverable from /etc/jellyfin/users/username and after uploading them again everthing works correctly.

**To Reproduce**

1. On 10.3.7 create user with avatar.
2. Update to 10.4.0.

**Expected behavior**

Paths should be updated after update.

**System (please complete the following information):**
 - OS: Ubuntu 18.04.2 LTS
 - Browser: Firefox
 - Jellyfin Version: 10.4.0
 - Reverse proxy: nginx

**Comment by thornbill** [comment]
I can reproduce this also. No errors in the server logs, but a 404 is returned when requesting the user image. If you remove the current image and re-add image, the image will load correctly.

**Comment by Strit** [comment]
Confirmed on arm64 docker image as well.

**Comment by tyhawk** [comment]
Confirmed. I had the same issue (also docker, Ubuntu 18.04 OS, but no reverse proxy).

**Comment by thornbill** [comment]
This seems to have magically corrected itself overnight on my server. I'm wondering if clearing Jellyfin's cache will resolve it.

**Comment by CountMurphy** [comment]
Confirmed on Arch linux as well. Clearing jellyfin's cache did not fix it for me. Had to reupload images.

**Comment by CountMurphy** [comment]
Odd, just like @thornbill the next day the server corrected itself.

**Comment by thornbill** [comment]
When I encountered this I tested a clean browser session in a private window and in a different browser as the issue persisted. I don’t believe it’s anything on the web side.

**Comment by JustAMan** [comment]
It might be some nightly task that generates stuff... however odd this sounds.

**Comment by dkanada** [comment]
Can anyone confirm if this is broken on the current stable or nightly releases?

**Comment by thornbill** [comment]
I think this was fixed in one of the 10.4.x releases. I have not seen it in a while.
