### ISSUE TITLE
Regression in path scanning for attributes

### ISSUE THREAD

**Issue by agilob** [jellyfin/jellyfin#1851]
Reproduce**

1. Go to `:8096/web`
2. See error `Value cannot be null. Parameter name: path`

**Expected behavior**
before 10.4 it used to correctly redirect to `web/index.html` same way it did when visiting url without subdirectory, it's either a regression, changed behaviour or inconsistent behaviour. Either way, it's inconsistent, as visiting `:8096/` redirects to `:8096/web/index.html` and produces correct webpage.

**System (please complete the following information):**
 - OS: docker 
 - Jellyfin Version: 10.4.0
 - Reverse proxy: traefik

**Comment by TiraelSedai** [comment]
Can confirm.
Workaroud: just go to `:8096/`

**Comment by Webbeh** [comment]
This regression also showed up differently to me.
I have jellyfin set up under a hostname with reverse proxy (apache), and updating from 10.3.7 to 10.4.0 messed up the URL Rewrite.
Before, the interface showed up nicely, and after update 10.4.0, accessing jellyfin either with hostname or with <ip>:8096 redirected me to https://web/index.html
https://github.com/jellyfin/jellyfin/commit/9c0a8350d6aa6fd13e418b5322a60dc5f720fa3a fixed it for me.
