### ISSUE TITLE
Check for plugin updates failed.

### ISSUE THREAD

**Issue by dragon2611** [jellyfin/jellyfin#186]
This shows in the dashboard under alerts

> Check for plugin updates failed
15/12/2018, 19:02:36
Running time: 0 seconds

> Resource temporarily unavailable Resource temporarily unavailable at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, String httpMethod) in /repo/Emby.Server.Implementations/HttpClientManager/HttpClientManager.cs:line 473 at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, String httpMethod) in /repo/Emby.Server.Implementations/HttpClientManager/HttpClientManager.cs:line 293 at Emby.Server.Implementations.Updates.InstallationManager.GetAvailablePackagesWithoutRegistrationInfo(CancellationToken cancellationToken) in /repo/Emby.Server.Implementations/Updates/InstallationManager.cs:line 214 at Emby.Server.Implementations.Updates.InstallationManager.GetAvailablePluginUpdates(Version applicationVersion, Boolean withAutoUpdateEnabled, CancellationToken cancellationToken) in /repo/Emby.Server.Implementations/Updates/InstallationManager.cs:line 399 at Emby.Server.Implementations.ScheduledTasks.PluginUpdateTask.Execute(CancellationToken cancellationToken, IProgress`1 progress) in /repo/Emby.Server.Implementations/ScheduledTasks/PluginUpdateTask.cs:line 68 at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options) in /repo/Emby.Server.Implementations/ScheduledTasks/ScheduledTaskWorker.cs:line 432

**Comment by anthonylavado** [comment]
Closed as this is how it's designed (for now)
