### ISSUE TITLE
Unable to Match to TheTVDB ID

### ISSUE THREAD

**Issue by rutskiuk** [jellyfin/jellyfin#1869]
I am unable to match shows using TheTVDB show IDs

1. Go to mismatched show (in my case Inside the Ambulance)
2. Click on Identify and use the correct TVDB show ID 326209 (https://www.thetvdb.com/series/inside-1)
3. Select the result, replace images
4. Show matches to Inside the Ambulance and the TVDB link shows https://www.thetvdb.com/?tab=series&id=320495

**Expected behavior**
To match with TVDB ID 326209 "Inside..."

**System (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Jellyfin Version: 10.3.7
 - Reverse proxy: no
[log_20191009.log](https://github.com/jellyfin/jellyfin/files/3704920/log_20191009.log)

**Comment by anthonylavado** [comment]
Sorry, I'm not sure I understand. Is it not showing the right matches, or does it go back to the bad one?

**Comment by rutskiuk** [comment]
When I try to mach "Inside..." by TheTVDB for "Inside..." which is 326209 it matches to "Inside The Ambulance" which is TheTVDB id 320495
It is already misidentified and giving it the correct TheTVDB does not correct the metadata, it matches it to the wrong show, trying to correct it again only replicates the problem.

**Comment by rutskiuk** [comment]
Now if I try to match the show I just get "unidentified" as a result

The TVDB ID is still 326209: https://thetvdb.com/series/inside-1

**Comment by rutskiuk** [comment]
I've tried again today and it's working :)
