### ISSUE TITLE
More secure user defaults

### ISSUE THREAD

**Issue by dragon2611** [jellyfin/jellyfin#187]
The default setting when a user is created is for them to be shown on the login screen, have no password and be able to remotely access the server.

Whilst I'm pretty sure this has come from Emby it is is horrible from a security perspective, especially for servers where remote access is enabled. I'd like to be able to change the settings so creating a user requires a password to be created and by default they're hidden from the login screen.

**Comment by bobberb** [comment]
c.f. #79

**Comment by winters-brown** [comment]
Any news on this?

**Comment by JustAMan** [comment]
@joshuaboniface why did you close this?..

**Comment by cvium** [comment]
He didn't. GitHub did

**Comment by TiraelSedai** [comment]
> The default setting when a user is created is for them to be shown on the login screen, have no password and be able to remotely access the server.

Right now user is hidden by default from the login screen. Should the issue be closed @JustAMan ?

**Comment by JustAMan** [comment]
Probably yes.

**Comment by Dracozny** [comment]
Is there an option to revert this? I'm using an internal server only. No intention of making it a public service and the User Icons make life easier for using a remote control.
