### ISSUE TITLE
Invalid paths in Music playlists (M3U/M3U8) cause log spam

### ISSUE THREAD

**Issue by iotku** [jellyfin/jellyfin#1876]
**Describe the bug**
Many of my music folders contain playlists (typically .m3u files, but some .m3u8 files) with apparently incorrect relative or non-relative paths and filenames with non-standard characters that appear to get decoded improperly (shows up as question marks).

As a result, during every media scan my terminal and log files are flooded with thousands of warnings:

`[WRN] Unable to find linked item at path: `

Of which multiple broken filenames (impossible to determine which, but likely with broken characters) cause my terminal to make a noise (Windows Background.wav)

Over the course of a day this results in approximately 60,000 pointless log entries
> grep -a "Unable to find linked item" log_20191009.log | wc -l
> 58415

and general annoyance from the sound.

**To Reproduce**

1. Have a lot of playlists which contain broken paths inside folders watched for Music library
2. Run a media scan
3. Watch your Terminal/Log fill with thousands of warnings

**Expected behavior**

I would expect that after the first attempt failing to find a path the invalid playlists would be ignored as to not continuously look for invalid paths every single media scan. (May this slow down scanning?)

Otherwise I would expect playlists to only be explicitly added and separate from the main media scan. (Why do I need playlists for a ton of albums with proper metadata that are already added to my library anyways?)

**Logs**

> [WRN] Unable to find linked item at path: [Any number of invalid filenames or paths]

**System (please complete the following information):**
 - OS: Windows
 - Browser: FireFox
 - Jellyfin Version: 10.4.0+ (Since: https://github.com/jellyfin/jellyfin/commit/ac9dfa8e93106d907bbf78fe2350adfa47c76cec)
 - Reverse proxy: nginx/directly

**Additional context**
Personally I don't have any use for playlists being scanned and added in automatically and would expect them to be completely separate from a standard media scan.

While I don't discount that other users may make extensive use of playlists, I would consider them redundant for my uses as it stands.

**Comment by SegiH** [comment]
I also opened up a ticket (#1874) for the same issue. When you add a song to an existing playlist on 10.4.0, something in the Jellyfin server causes it to update the playlist and change the path for every single track in the playlist from an absolute to a relative path.

I opened up each playlist and did a replace of ..\ with the absolute path for now to fix this. But if you add a song to the playlist, it'll do this again until the dev's fix this on the server.

**Comment by iotku** [comment]
I don't believe I've edited any playlists through jellyfin so I believe it's just loading up playlists that were already bad, unless simply being added to jellyfin modifies the playlists which would be quite concerning.

I don't believe that's the case here, but ideally I don't want jellyfin modifying any media files in my library directly (including playlists) and especially not without confirmation.

**Comment by SegiH** [comment]
Well the same thing may be happening automatically when you start JF after upgrading to 10.4

**Comment by clawoflight** [comment]
Only somewhat related to this issue, but not worth a new one:
Did handling of relative paths in playlist files change?
I have a lot of playlists with paths relative to the playlist file which worked in a previous version of jellyfin, but no longer.
Are the paths now relative to the library root or something?

**Comment by anthonylavado** [comment]
Right so the invalid path thing should be indirectly fixed by my playlist fix. It will still log a WRN if something isn't found, but the reasons for that should be valid now.
