### ISSUE TITLE
Checkmark is off center when using AddPlayedIndicator=true in the API

### ISSUE THREAD

**Issue by cewert** [jellyfin/jellyfin#1888]
**Describe the bug**
The image returned when using AddPlayedIndicator=true has the circle with checkmark but the checkmark is off center

**To Reproduce**
Use the roku client

Or use a browser to access the API:
1. Use the web client to view a movie or tv show detail page
2. Copy the id from the url (id=)
3. Open jellyfin web client in a new tab
4. Replace "/web/index.html#!/home.html" in the URL with "/Items/{ITEMID}/Images/Primary?AddPlayedIndicator=true" replacing {ITEMID} with the id copied from step 2
5. Observe check mark in top right corner of image

**Expected behavior**
Check mark should be centered

**Screenshots**
![Screenshot from 2019-10-11 21-55-19](https://user-images.githubusercontent.com/16514652/66692983-dfb2b000-ec71-11e9-8208-a8a821436bbc.png)

**System (please complete the following information):**
 - OS: Docker
 - Browser: Firefox
 - Jellyfin Version: 10.4.0
 - Reverse proxy: none

**Comment by onny** [comment]
Shouldn't we move this bug report to the Jellyfin-web repository?

**Comment by anthonylavado** [comment]
> Shouldn't we move this bug report to the Jellyfin-web repository?
@onny The checkmark is rendered by the server, and returned in the API. This is the right repo, really. This is going to be somewhere in the Skia commands

**Comment by dkanada** [comment]
@cewert is this still broken?

**Comment by cewert** [comment]
I just tested and yes this is still broken for me. I accessed the API and observed the behavior using the latest version of firefox as well as the roku client.

OS: Docker
Jellyfin: 10.4.3

**Comment by cewert** [comment]
I should have mentioned in the OP - the reason I created this issue is because the roku client uses this API param. @bisby also confirmed it was not working on his roku

**Comment by anthonylavado** [comment]
I forget if Android TV uses this or not. Will check.

**Comment by anthonylavado** [comment]
An update on what is now a very old thread. Android TV hasn't used this in a long time. The only known clients left are Roku and https://github.com/SenorSmartyPants/jellyfin-nmt by @SenorSmartyPants.

With Roku under increased development lately, we might be able to tackle generating client side watched indicators.

With that, though it may be some time away, we are considering deprecating this feature for 10.9.
