### ISSUE TITLE
The full commandline including secrets is exposed in the logs when error handling happens.

### ISSUE THREAD

**Issue by LogicalPhallacy** [jellyfin/jellyfin#189]
So when an error is thrown the entire commandline call used to run Jellyfin is exposed in the log. If you are running as a user with a stored password on windows this exposes credentials. It is a bit of an edge case but it should be sanitized. The OS detection is also wrong but that is a separate issue :)

Example from log(sanitized)

2018-12-15 12:28:10.611 Error HttpServer: Error processing request
        *** Error Report ***
        Version: 3.5.2.0
        Command line: C:\Users\Drago\AppData\Roaming\jellyfin\jellyfin.dll OBJECTNAME USERNAME PASSWORD
        Operating system: Microsoft Windows NT 6.2.9200.0
        64-Bit OS: True
        64-Bit Process: True
        User Interactive: True
        Processor count: 6
        Program data path: C:\Users\Drago\AppData\Roaming\jellyfin
        Application directory: C:\Users\Drago\AppData\Roaming\jellyfin
        MediaBrowser.Model.Net.HttpException: No such host is known No such host is known ---> System.Net.WebException: No such host is known No such host is known ---> System.Net.Http.HttpRequestException: No such host is known ---> System.Net.Sockets.SocketException: No such host is known

**Comment by anthonylavado** [comment]
@LogicalPhallacy Does this still happen? I haven't checked on other systems, least of all Windows right now (my box is down)

**Comment by LogicalPhallacy** [comment]
Not that I've noticed. My errors might be in the wrong places though. I can try and repro but I think it might be ok.
