### ISSUE TITLE
A skip intro button

### ISSUE THREAD

**Issue by Chicken-DEV** [jellyfin/jellyfin#1894]
I feel like you should be able to create a skip intro button by defining the start and end point of the intro. This could be especially useful for Anime or other series with long intros.

**Comment by anthonylavado** [comment]
Hey there @Chicken-DEV, would you be able to create this as a feature request on our feature site?

Thanks!!
https://features.jellyfin.org

**Comment by Chicken-DEV** [comment]
Oh, yesterday it was offline and I thought it would stay so for a longer time, but yeah I will go over there now. Thanks!
