### ISSUE TITLE
A way to capture db changes

### ISSUE THREAD

**Issue by ddurdle** [jellyfin/jellyfin#1895]
I was thinking today that one way of making multiple JellyFin instances in-sync with eachother before the time a real database could be used, is by capturing changes to the data on the JellyFin node.  Whether it is the application itself or a simple database trigger that captures INSERTS/UPDATES/DELETES, this "audit" data could then be leveraged to keep multiple instances "in-sync".

**Comment by onny** [comment]
Hey ddurdle,
could you give a use case when it is useful to run two Jellyfin instances in parallel?

Regards
Jonas

**Comment by ddurdle** [comment]
Could be used to:
1) keep the user data in sync for a user between instances
2) keep the library in sync between servers

**Comment by anthonylavado** [comment]
Well, in the long run, we plan to move from only SQLite to EFCore, with a new database schema. The idea behind this is to still keep SQLite around as a default, but then you could also use any number of other databases behind the scenes. Many of those would support replication and such, just like you’re looking for.

**Comment by ddurdle** [comment]
Yes, I've been watching those issues tracking the move to a real database framework interface to allow for a real database.  This is a great long term goal, but it is going to take a long time to get the application moved and tested to a proper database framework.

Over the weekend, I suddenly remembered that "in the meanwhile" one might be able to leverage something in the interm to play around with.  It is possible for anyone today to update the dbschema, without making a change to the application, to write an audit of changs to the data.  Doing something with that data would require some creativitiy.
