### ISSUE TITLE
Multistage Docker build strategy can break

### ISSUE THREAD

**Issue by justinfenn** [jellyfin/jellyfin#1906]
**Describe the bug**

The Dockerfile runs a multistage build, and [at one point](https://github.com/jellyfin/jellyfin/blob/9040ef87dc99462b1e85a5cb347f9ae8428bfa50/Dockerfile#L22) it copies the entire root directory from another image.  This includes system libraries and binaries like `rm`.  This basically works because everything that gets copied is self-consistent, but it can cause issues when some packages are upgraded later on.

I ran into an issue where the Docker build would fail during the `apt-get install` a few lines later.  It seems like `apt` is probably replacing some shared libraries or something that is incompatible with the binaries copied from the other image.  I saw a few different symptoms while investigating (see logs).

**To Reproduce**

1. Use `jellyfin/ffmpeg` with image id `76d3885fbbf3`
2. Update the first line of the Dockerfile to use .NET core 3.0 (I think this needs to be updated generally)
3. Run `docker build -t my-tag .`
4. See the error in the logs section below

**Expected behavior**

Running `docker build -t my-tag .` should complete successfully.

**Logs**

Initial problem:
```
Setting up libudev1:amd64 (237-3ubuntu10.31) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
E: Problem executing scripts DPkg::Post-Invoke 'rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true'
E: Sub-process returned an error code
```

Other failures I saw:

```
Segmentation fault (core dumped)
```

```
*** stack smashing detected ***: <unknown> terminated
Aborted (core dumped)
```

**System (please complete the following information):**

 - OS: Docker, Linux
 - Browser: N/A
 - Jellyfin Version: 10.4.0
 - Reverse proxy: N/A

**Comment by JustAMan** [comment]
cc @Bond-009 about .netcore 3.0 and @nvllsvm about Docker
