### ISSUE TITLE
Wrong audio file play when casting to Kodi 

### ISSUE THREAD

**Issue by Germwalker** [jellyfin/jellyfin#1910]
That bug is quite tricky, and running for a while. Sorry if it's not very clear.

**System**
Jellyfin 10.4.0 on Debian 10, bare-metal (intel)
Libreelec with Kodi, up to date (last release) on rasp 4
Kodi connected to Jellyfin as a user "Kodirasp" with Kodi Sync Queue enabled

**Describe the bug**
I am playing the files from Jelly, casting to Kodi via the Jelly user "Kodirasp". When i click on a song name from an album, Jelly send another one to Kodi, always the same one for a given album.

For example, i click on _"Marooned"_ from Pink Floyd album "The division bell", **but Kodi play _"High Hopes"_** (from the same album). Same problem when i want to listen any other song from the same album, "High Hopes" is played every times. The bug is present on every albums from the discography. I must manualy go to Kodi web interface and change the song. I can do it because even when playing a unique file, Jelly send the entire album, shuffled (but always in the same order). 

**Same problem** when clicking "Instant Mix" or "Random". I have the same shuffled album.
**No problem** when direclty playing the song from the web/pc/phone.
**No problem** when cliking the three dots -> read, for a single file. The good song is played on Kodi, nothing is played after.
**No problem** when constructing the Queue manualy : three dots -> Add to Queue. The Queue is well played on Kodi in the good order, then stop.

**The problem is the same for audio/Tv Shows files. I try to read the first episode, the very last is played on Kodi.**

**To Reproduce**
1. Connect Kodi to Jellyfin by creating a specific user "Kodirasp"
2. Cast to Kodi by selecting "Kodirasp" at the top right cast icon
3. Go to an album, click on a song name to play it
4. Another audio file from the same album is played, the entire album is sent, shuffled. 

**Expected behavior**
Jelly should send the corresponding song to Kodi when clicking on the file name, and just the file, not the album. When playing album from 1st to last song, Jelly should not shuffle it. 

**Logs**
I can provide the logs but unfortunately there is nothing related to this particular problem.

**Screenshots**
![image](https://user-images.githubusercontent.com/56682696/67010846-c2a53380-f0ee-11e9-800b-ef2fac062b28.png)

1 - Play by click on the file name. Wrong song played, entire album sent to Kodi, shuffled but always the same way.
2 - Same as 1, Jelly send the shuffled album.
3 - The order is different than 1 & 2 but the entire album is sent. Let me precise this later.
4 - Dots -> Read : OK. Unique file is well played. I use this with "Add to Queue" to manual play an album from the 1st to the last.

**System (please complete the following information):**
 - OS: Debian 10, Intel, x64
 - Browser: Firefox, Chrome, Android, Iphone ... Not related to client app/browser.
 - Jellyfin Version: 10.4.0
 - Reverse proxy: nginx

**Additional context**
The problem have always been present since the first boot of the system. I assume the bug is related to Jellyfin, i can be wrong. Even after 2 upgrades of both Jelly/Kodi systems, the bug is still here. 

Thank you all for reading.

**Comment by JustAMan** [comment]
Can this be related to https://github.com/jellyfin/jellyfin/issues/1724 ?

**Comment by Germwalker** [comment]
Yeah, #1724 is very similar !

**Comment by JustAMan** [comment]
I'm going to close this one as a duplicate then, in favor of #1724.

**Comment by Germwalker** [comment]
Okay, thank you. I'll try to investigate for a potential solution.
