### ISSUE TITLE
Issues Moving Old Config from .3.7 to .4.0 [Win 10]

### ISSUE THREAD

**Issue by Z3ROGRAV1TYx** [jellyfin/jellyfin#1913]
**Notes**

So, this may get confusing, I will try to be as detailed but easy to understand as possible. I honestly am even a bit confused myself. But I will try to state everything I have tried/did. Note, on Saturday, I did discuss this in the Matrix Discord so you can go back and read my conversation, Anthony (Anthony Lavado) was going back and forth with me for a while and helping my confusion with some stuff. I really appreciate his help, I know he was a little busy. I was told by JustAMan in the server to report this to the Github, so here it is.

**Backstory/Info**

So to start, I was trying to port my config from 10.3.7 to 10.4.0. I had went into the Matrix Jellyfin server to get some help to ensure I went about it properly. So I was told the dev had made a Reddit forum explaining upgrade instructions. I had read this over and over, and eventually understood barely. It's not that it was confusing, it was just very complicated and seemed like each thing had a pro or a con with no real answer.

Anyways, I would end up choosing option C I believe, which was basically to not install it as a service. So I would need to launch the exe to have Jellyfin running. I didn't see in the guide this stated, but the dev (Anthony) had stated to move the old config backup back to Appdata\Local\jellyfin (He stated it would normally go in %ProgramData% but due to me not installing it as a service, I would be placing the data back into Appdata\Local\jellyfin. 

Now, take note that originally on my original install of Jellyfin, I believe (I may be wrong) but I believe that I had it installed as a service. I know for a fact it did show up in services, and if I wanted to restart it or stop or run it I would go to services, right click Jellyfin and do it there. I never had to click an cmd.exe and a cmd prompt never sat in my taskbar/task tray. I'm noting this because I wasn't sure if it needed to be installed liek the old one, maybe something in the config files won't match or something if it's not installed the same way, you know. I wasn't sure. But this doesn't seem to be the case (as I state later on).

Now back to Appdata, after moving the backup of my jellyfin to appdata\local\jellyfin I launch Jellyfin's web gui.. now onto the actual issue/bug...

**Describe the bug**

So right away upon launching the web gui, I noticed an issue right away. I have 4 accounts, one is hidden, and 3 normally show. The hidden one plus one that shows are admin accounts, the other two aren't. I'm unsure if it's coincidence or not, but the admin account did not show at all, only the two "guest" accounts appeared. Also one of their profile pictures was blank. I tried logging into all the accounts using the local pins that I had setup. It gave a login error (Just stating invalid). I then try to use thier actual passwords, that worked (Even on the hidden account). Now I get in, and everything looks fine. I see my all my libraries, I see next up episodes and such. BUT if I scroll right to see the last two libraries (seperate tv and movies libraries) they are blank. Their library art is missing (the custom artwork I made). If I click either one, the cmd.exe for jellyfin just crashes and jellyfin shuts down. 

I opened it back up, went back onto the webgui and tried to go into server settings, everything looked fine and then it randomly crashed again. Relaunched, went back onto web gui, went back into server settings and it worked, but then I tried changing something and it still crashed. Relaunched, webgui and tried opening those libraries, still blank artwork and crashes when clicked. I also tried clicking a show (in the next up on the home page) and it crashed.

I had tried this a few times testing different things, and it just constantly crashed. I thought maybe that my backup didn't fully overwrite, so I completely uninstalled Jellyfin 10.4.0 and deleted any leftover folders and reinstalled same way. I then rewrited the appdata folder with the backup and nope same issues occur. I then considered that it may unfortunately be the actual backup that was screwed up. BUT I decided to uninstall 10.4.0 and delete leftover folders, and then go and install 10.3.7. I then put my backup into the appdata folder and it works perfectly fine. Just as it used to. So it's not my backup files.

Now remember when I stated that I wasn't sure if it needed to be installed the same? (As a service or not). Well with this 10.3.7 install, I didn't install it as a service (By accident actually) so I have to manually click the jellyfin.exe anytime I want to launch (and it sits in my taskbar along with caddy taking up visual space, quite annoying lmao but I'm going to leave it there because it works right now and I don't want to mess with it because this has become a PITA to be quite frank.) But yeah, it works. So it definitely is some issue with those config files and just 10.4.0 it seems. If I didn't replace those config files, I was brought to the wizard screen to create a new server. I didn't even want to bother with it, I would've if reverting to 10.3.7 didn't work, but that did so I didn't mess with it. I can't confirm whether that wizard would've worked. But I did go a couple steps in and it seems like it was creating fine. 

So I'm unsure what to do from there, I've just stopped messing with it and been using my 10.3.7 install. Hoping that 10.4 get's a bit smoothed out, and hoping I'm not the only one with this issue/this issue can be replicated by the devs to be fixed because that would be frustrating if not. 

**To Reproduce**
Not going to fill this out, because I'm really not sure what to put here. I went as detailed as I could above on what I did and what issues I encountered. It would be a mess to move any bit of it here so just read above.

**Logs**
I don't have any logs. I honestly didn't even think about it, and I really don't feel like uninstalling my working 10.3.7 to just redownload 10.4.0 (Again) and get logs that may or may not be helpful or even be present. But if you REALLY need me too, I guess I can just let me know.

**Screenshots**
Didn't have screenshots, sorry.

**System (please complete the following information):**
 - OS: Windows 10, Lastest.
 - Browser: Firefox Latest
 - Jellyfin Version: 10.4.0 (Issue), Reverted to 10.3.7
 - Reverse proxy: Caddy

**Additional Notes/Info:**

As for 10.4.0, I would like to hope that the install for Windows would be more straightforward very soon, that it can just run in task tray instead of sitting in taskbar, and also the ability to export/import settings directly through the webgui to not have to deal with all this crap of manually overwriting files, finding folders, etc. It would really be nice tbh. I was very confused on which install to do for a bit until discussing it in the Matrix server (A, B, C as per the devs reddit guide, which to note wasn't on the Jellyfin install page, which I think it should be.) I honestly hope all that get's simplified and honestly not needed tbh. Just one install, it just follows through like most programs. Emby was pretty simplified, I hope Jellyfin can become like that tbh. I understand everything takes time, I'm just throwing this stuff out here and ranting a little. Sorry. I really hope you guys keep up the good work, I hope to see Jellyfin become even more amazing than it already is. These complications and bugs really need to be smoothed out though. Thanks.

**Comment by dkanada** [comment]
see #1903 for an improved installer (tray icon is getting worked on)

**Comment by anthonylavado** [comment]
We've worked through most of this now.

**Comment by Z3ROGRAV1TYx** [comment]
Well yes and no, I still had an issues in the end and ultimately ended up needing to reset up the server from scratch instead of using old config. So far everything's been working good. But yeah I couldn't get things 100% with the old config for some reason. If that's the case for any future viewers, your best bet is just to resetup probably and unforunately.
