### ISSUE TITLE
Playlist allows for duplicates

### ISSUE THREAD

**Issue by SegiH** [jellyfin/jellyfin#1914]
**Describe the bug**
If you add a media file to a playlist, there is no warning to let you know that it already exists in the playlist. It seems strange to have a need for duplicates in the first place and is probably not something that most users would want anyways.

**To Reproduce**
1. Go to a song or video item in Jellyfin
2. Click the + to add it to a playlist
3. Nothing will warn you if the item is already in the playlist

**Expected behavior**
After talking to dkanada on IRC, he suggested that we not make any client side changes and instead print an error message to the server logs if a duplicate item is found.

**Logs**
Not relevant in this case

**Screenshots**
N/A

**System (please complete the following information):**
N/A This would be a server side change for all operating systems

**Additional context**
I plan on making a commit with a new method in Emby.Server.Implementation\Playlists\PlaylistManager.cs  that does a duplicate check

**Comment by dkanada** [comment]
@SegiH did you still want to go through with that pull request?

**Comment by SegiH** [comment]
Yes absolutely thanks
