### ISSUE TITLE
jellyfin package for Ubuntu 16.04 depends on libssl1.1 which doesn't exist

### ISSUE THREAD

**Issue by iissmart** [jellyfin/jellyfin#1935]
**Describe the bug**
The jellyfin package for Ubuntu 16.04 (Xenial) in the jellyfin repo depends on the libssl1.1 package, which doesn't exist in Ubuntu 16.04. This version of Ubuntu only supports up to libssl1.0.0.

**To Reproduce**
```bash
# cat /etc/apt/sources.list.d/jellyfin.list
deb [arch=amd64] https://repo.jellyfin.org/ubuntu xenial main

# apt list --upgradable -a
Listing... Done
jellyfin/unknown 10.4.0-1 amd64 [upgradable from: 10.3.7-1]
jellyfin/now 10.3.7-1 amd64 [installed,upgradable to: 10.4.0-1]

# apt-get upgrade jellyfin
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 jellyfin : Depends: libssl1.1 but it is not installable
E: Broken packages

# apt-cache search libssl1.1
<no output>
```

**Expected behavior**
If jellyfin is going to continue to support Ubuntu 16.04, the jellyfin package must not depend on libssl1.1.

**Logs**
N/A

**Screenshots**
N/A

**System (please complete the following information):**
 - OS: Ubuntu 16.04.6 LTS
 - Browser: N/A
 - Jellyfin Version: 10.4.0-1
 - Reverse proxy: N/A

**Additional context**
N/A

**Comment by JustAMan** [comment]
paging @joshuaboniface for comments

**Comment by joshuaboniface** [comment]
> If jellyfin is going to continue to support Ubuntu 16.04

This has been a massive headache since this damn SSL transition started. Dropping Xenial support seems reasonable.

**Comment by JustAMan** [comment]
With that said, we do understand that 16.04 is an LTS release, but it is becoming very hard to support in our current official packagings.
Anyone is open to make a 16.04 package and publish it on a PPA, I think, or just use Docker or other means to run JF (like compiling the package from source, should not be too hard).

Summary: Ubuntu 16.04 support was dropped in 10.4.x on purpose and we're currently not thinking about bringing it back.

**Comment by Kneit0r** [comment]
For those that still use 16.04, and need libssl1.1 working, try this:

wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.0g-2ubuntu4_amd64.deb
sudo dpkg -i libssl1.1_1.1.0g-2ubuntu4_amd64.deb

From: https://stackoverflow.com/questions/68148246/broken-php-and-libssl1-1-installation-on-ubuntu-16-04
