### ISSUE TITLE
Docker: add environment variables to skip setup wizard

### ISSUE THREAD

**Issue by Nautigsam** [jellyfin/jellyfin#1940]
When installing Jellyfin via Docker, we should be able to set some environment variables to answer the questions asked in the setup wizard and skip it. This ensures a more convenient way to deploy Jellyfin with no manual intervention i.e. fully replicable install.

We could get some inspiration from [Nextcloud](https://hub.docker.com/_/nextcloud) which offers several env variables to customize the install before even opening a browser.

**Comment by JustAMan** [comment]
I don't think this is easily doable now, most likely it would have to wait till we have our DB backend rewrite and then configuration rewrite...

**Comment by Nautigsam** [comment]
Are there some open discussions to follow progress on this matter, please?

**Comment by JustAMan** [comment]
Probably this: https://github.com/jellyfin/jellyfin/pull/1431

**Comment by sparky8251** [comment]
This is definitely something we should be do. You know... once the building blocks are in place.

**Comment by joshuaboniface** [comment]
It's definitely not doable now, short of seeing a template `system.xml` file. Jellyfin does not work like just about any other piece of software in this regard.

**Comment by xmha97** [comment]
Now can I skip wizard?
