### ISSUE TITLE
Posters/Thumbs not consistent through Library Screens

### ISSUE THREAD

**Issue by kcomplexes** [jellyfin/jellyfin#1943]
**Describe the bug**

 
**To Reproduce**

1. Go to 'Home', Movies are in poster format, while TV shows are in thumb format.
![1](https://user-images.githubusercontent.com/16506704/67629449-31d41200-f8bd-11e9-922f-dede4726ab8f.png)

or
1. Click on 'Movies' library. Here you can set view type to thumbs. The images show up as thumbs  as expected, 
![2](https://user-images.githubusercontent.com/16506704/67629450-31d41200-f8bd-11e9-85fb-437979ea8d88.PNG)
however...
2. Click on 'Suggestions'. They are posters again, often with discs. And no option to change it to Thumbs. 
![3](https://user-images.githubusercontent.com/16506704/67629451-326ca880-f8bd-11e9-8f05-686eab419f7d.PNG)

3. Same can be seen when clicking on ''Genres'

![4](https://user-images.githubusercontent.com/16506704/67629452-326ca880-f8bd-11e9-98d6-7e7c43062c98.PNG)

However,
1. The TV Shows library seems to follow the one format (thought still does not allow you to select a view type)
![5](https://user-images.githubusercontent.com/16506704/67629453-326ca880-f8bd-11e9-86df-585b65de5423.PNG)

**Expected behavior**

Expected behavior is that View Type, or the 'thumb' option in this case should be consistent across different screens within a library, or each screen should be able to be manually set.

**Logs**

Did not think required, will provide if they are helpful?

**System (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox,
 - Jellyfin Version: 10.0.04
 - Reverse proxy: no

**Additional context**
above were examples on Firefox. The same sort of thing occurs on android TV app (0.9.1). Can provide pictures if required.

I would like thumbs because for some reason half of my primary art for Movies is set to the disc.

Hopefully I haven't missed something completely obvious. Please let me know if you require any further information.

Thanks.

**Comment by Hakker** [comment]
Not the OP but it's still there and when it's mixed content it becomes cd posters. It could really benefit from more flexibility.

I set my anime for instance as Mixed because I don't want them between my series and movies along with their random or last added lists. So they become squares.
It would benefit if you could choose the thumb style. vertical, horizontal or square (cd style) per group you make.

**Comment by JustAMan** [comment]
@Hakker I suggest you open a new enhancement request.
