### ISSUE TITLE
[Temporary fix found] Jellyfin server crashes whenever there is a linux network interface change

### ISSUE THREAD

**Issue by Webbeh** [jellyfin/jellyfin#1944]
**Describe the bug**
Using a linux (Arch) server, everytime there is a network interface change (adding a new docker container, creating a new tunnel, disabling a network interface, ...), Jellyfin dumps core  and throws a
System.Net.NetworkInformation.NetworkInformationException (0x800004005).

**To Reproduce**
- Start jellyfin server
- create or delete a network interface of any kind (PPP, docker container, ...)

**Expected behavior**
....not crash, I guess ?

**Logs**
https://gist.github.com/Webbeh/bf7823d5f24fdccc61684011940b6a90

** System **
ArchLinux x86_64
Linux 4.19.80-1 (LTS)
Jellyfin 10.4.0 r18 (git 1176749f14)

**Comment by Bond-009** [comment]
Can you try with the latest master? This is a corefx issue and we recently moved to .Net Core 3.0.
Also, removing these lines should the issue: https://github.com/jellyfin/jellyfin/blob/master/Emby.Server.Implementations/Networking/NetworkManager.cs#L27-L28

**Comment by Webbeh** [comment]
So just updating to latest master doesn't do the trick. Trying to patch those files out.
