### ISSUE TITLE
mp2 to mp3 transcoding broken

### ISSUE THREAD

**Issue by ggogel** [jellyfin/jellyfin#1945]
Hello guys,

I've mentioned this issue already here: https://github.com/jellyfin/jellyfin/issues/1901#issuecomment-544026325
It has to do with HDR transcoding in 10.4.0. I've mentioned there that I've got issues with Live-TV, too. The thing is this bug is also in 10.3.7. When playing the a Live TV channel with a mp2 stereo audio stream from the Android or Fire TV app it's getting transcoded to mp3 and the transcoding fails. When I play it from Firefox Desktop the mp2 stream is transcoded to acc and it succeeds. I also tried channels with an ac3 stream on Android, which is also transcoded to mp3. Those work perfectly fine. 

Long story short: I can narrow this down to mp2 -> mp3 transcoding being broken.

**Media Info of the file**
This is the media info from a recording of the channel:
https://pastebin.com/w8kS1SvZ

**Logs**
Android (broken mp2 -> mp3):
https://pastebin.com/M4pL3bj4

FireFox (working mp2 -> aac):
https://pastebin.com/YEz7U64d

**Server System (please complete the following information):**
 - OS: Docker on Ubuntu 18.04
 - Jellyfin Version: I've tested 10.3.7 & 10.4.0
 - Hardware settings & device: VAAPI on Intel(R) Pentium(R) CPU G4600 @ 3.60GHz
 - Reverse proxy: nginx
 
**Client System (please complete the following information):**
 - Device: Oneplus 6, FireTv 2nd Gen
 - OS: Android

**adding from https://github.com/jellyfin/jellyfin/issues/1945#issuecomment-557198814**:
The issue is only on Android Mobile, Android TV and Fire TV.

- Jellyfin Android: 0.9.5
- Android TV: 0.10.2g
- Fire TV: 0.10.2a

**Comment by gerrit507** [comment]
Just wanted to add: It also fails with vaapi turned off.
https://pastebin.com/sQaSNnnX

**Comment by gerrit507** [comment]
It seems to be only Android related. When palying from Chrome Desktop it also transcodes mp2 to mp3 but it succeeds: https://pastebin.com/j08LTxV3

**Comment by JustAMan** [comment]
@gerrit507 what happens if you install Chrome mobile on your phone and try to play same file that fails in Android client?

Also next time please don't put "latest" as version, as it's impossible to reproduce after some time, "latest" is a moving target which might change its behavior between the time you submit a bug and the time a dev tries to dig into it.

**Comment by gerrit507** [comment]
It works with Chrome on Android. 

The issue is only on Android Mobile, Android TV and Fire TV.

versions:

- mobile: 0.9.5

- Android TV: 0.10.2g 

- Fire TV: 0.10.2a

**Comment by JustAMan** [comment]
@gerrit507 thanks, I've updated original issue with this versioning info.
Hopefully someone from @jellyfin/backend or @jellyfin/web could have a look into it.
