### ISSUE TITLE
[Privacy issue] User permissions don't work - Any user can play any media

### ISSUE THREAD

**Issue by omyno** [jellyfin/jellyfin#1946]
**Describe the bug**
A user without access to libraries can still access media in all libraries via search.

**To Reproduce**

1. Create user, don't grant permission to any libraries. 
2. Use search function to find media from other libraries
3. Find and play media that the user is not supposed to find.

**System (please complete the following information):**
 - OS: Docker
 - Browser: any
 - Jellyfin Version: https://hub.docker.com/layers/jellyfin/jellyfin/latest/images/sha256-af09b0edf3f5d0f6aecbe7745ff58097bb86b2c925f8c15488c3b47e6f9a5480
 - Reverse proxy: nginx

**Comment by KeepBotting** [comment]
Confirmed.

OS: Docker on Void Linux
Browser: any
Jellyfin version: 10.4.0
Reverse proxy: yes, nginx

**Comment by Z3ROGRAV1TYx** [comment]
Not having this exact issue personally, but would like to reference #2207 because I believe it's related.
OS: Windows 10
Jellyfin: 10.4.3
Reverse Proxy: Caddy

**Comment by gnattu** [comment]
When I am testing this, I found that if we give the user access to at least one library with contents, they he will no longer able to search for media that he does not have access to, nor able to see the suggestions from other libraries. Could you confirm this?

**Comment by sum01** [comment]
I just tested this. I have a user with access to all but 1 library. Tried to search for content in that disabled library and it doesn't show up. Tested with the web interface on server v10.6.4.
