### ISSUE TITLE
Install instructions for Nightly for  Debian Testing  throws apt error

### ISSUE THREAD

**Issue by gerroon** [jellyfin/jellyfin#1950]
This is the instruction from the site.

sudo apt install apt-transport-https
wget -O - https://repo.jellyfin.org/jellyfin_team.gpg.key | sudo apt-key add -
echo "deb [arch=$( dpkg --print-architecture )] https://repo.jellyfin.org/$( awk -F'=' '/^ID=/{ print $NF }' /etc/os-release ) $( awk -F'=' '/^VERSION_CODENAME=/{ print $NF }' /etc/os-release ) main" | sudo tee /etc/apt/sources.list.d/jellyfin.list
sudo apt update
sudo apt install jellyfin-nightly

```apt update
E: Malformed entry 1 in list file /etc/apt/sources.list.d/jellyfin.list (Component)
E: The list of sources could not be read.
```

```
cat /etc/apt/sources.list.d/jellyfin.list
deb [arch=amd64] https://repo.jellyfin.org/debian main

```

**Comment by joshuaboniface** [comment]
Once again it looks like Debian Testing has a broken `/etc/os-release`. Manually fill in `buster` before `main` in the list file line.

**Comment by JustAMan** [comment]
@joshuaboniface should we add a blurb like "if you cannot install stuff on Debian check that your line is correct: _example of correct line_" to the docs?
