### ISSUE TITLE
Invalid Subtitle Selection [Undefined]

### ISSUE THREAD

**Issue by GVLTodorov** [jellyfin/jellyfin#1955]
Area Subtitle selection.
On the Movie View I can't to see Bulgarian option
example of url:
***/web/index.html#!/itemdetails.html?id=f971794d2389058fced44b815646b4a4&serverId=533d528d41f5429490397da5056036e8**
![undefined](https://user-images.githubusercontent.com/51453974/67752937-95d11480-fa3c-11e9-87be-ef7490c7d44c.png)

subtitle example.
[example.zip](https://github.com/jellyfin/jellyfin/files/3782597/example.zip)

Server: linux
Version: 10.4.0
Operating System: Linux
Architecture: X64

Backend Response:
url:
*/Items/8961c250309957c24a7204c85019ab13/PlaybackInfo?UserId=29f87d231670404eb900026454377582&StartTimeTicks=0&IsPlayback=false&AutoOpenLiveStream=false&MaxStreamingBitrate=140000000

{
            "Codec": "srt",
            "localizedUndefined": "Undefined",
            "localizedDefault": "Default",
            "localizedForced": "Forced",
            "DisplayTitle": "Undefined",
            "IsInterlaced": false,
            "IsDefault": false,
            "IsForced": false,
            "Type": "Subtitle",
            "Index": 32,
            "IsExternal": true,
            "DeliveryMethod": "External",
            "DeliveryUrl": "/Videos/8961c250-3099-57c2-4a72-04c85019ab13/8961c250309957c24a7204c85019ab13/Subtitles/32/0/Stream.vtt?api_key=31702238ce674f9da37dc4edecd6fccc",
            "IsExternalUrl": false,
            "IsTextSubtitleStream": true,
            "SupportsExternalStream": true,
            "Path": "*/Downloads/El.Camino.A.Breaking.Bad.Movie.2019.1080p.NF.WEBRip.x265.10bit.SDR.DDP5.1.Atmos-MZABI/El.Camino.A.Breaking.Bad.Movie.2019.1080p.NF.WEB-DL.DDP5.1.Atmos.HEVC-MZABI.srt"
        }

**Comment by GVLTodorov** [comment]
Server: linux
Version: 10.4.0
Operating System: Linux
Architecture: X64

**Comment by JustAMan** [comment]
What exactly is wrong here, i.e. what you expected to see differently and what is desired output?
