### ISSUE TITLE
a theme.mp3 don´t work??

### ISSUE THREAD

**Issue by angeltonio** [jellyfin/jellyfin#1962]
I have my metadata saved it on the same folder of the files, you know...option nfo, but i put a mp3 file with name theme.mp3 to use this like emby and don´t work...why is that???....

Another thing if I have my offline metadata such as poster.jpg, landscape.jpg, etc. .. why does jellyfin take a long time to recognize it and make it available ?? ..

**Comment by anthonylavado** [comment]
We'll have to investigate. Also, file scanning is extremely slow, and it will likely be trying the web first. There is an order of priority you can set for some metadata, but I'm not sure if there are options for local ones to have higher priority from the start.

**Comment by angeltonio** [comment]
No, there is no option to add that local metadata have priority, and I think this would be a good option since scanning would be faster if done in this way for metadata that has already been downloaded .. greetings
