### ISSUE TITLE
Clicking play on show or season always plays first episode instead of next up

### ISSUE THREAD

**Issue by JonnyHaystack** [jellyfin/jellyfin#1975]
**Describe the bug**
Clicking play on a show or a season always plays the first episode regardless of progress in the show, instead of playing/resuming the "next up" episode. This isn't really useful or intuitive.

**To Reproduce**
1. Click the play button on a show/season of a show which you are already part way through
2. See that it starts playing from the very first episode

**Expected behavior**
Clicking the play button on a show or season should resume where you left off.

**System (please complete the following information):**
 - OS: Debian 10.1
 - Browser: qutebrowser
 - Jellyfin Version: 10.4.1
 - Reverse proxy: no

**Comment by JustAMan** [comment]
I would say this is more or less expected behaviour, it's in line with how "Play" button behaves for movies.
I would expect there to be a "Resume" button, though (much like for movies there).

Thoughts?

**Comment by JonnyHaystack** [comment]
I liked the way Plex handles it to be honest. They will always prompt you whether to resume or start from the beginning, which prevents you from accidentally losing your place. In Plex when you click on a show it will open the most recent unviewed/partially viewed episode and prompt you to resume it or play from the beginning. I found that very intuitive and it saves unnecessary clicks.

**Comment by JustAMan** [comment]
That makes sense. Could you please post it as a full-fledged feature request here: https://features.jellyfin.org/ ?

**Comment by JonnyHaystack** [comment]
Alright will do, thanks!

**Comment by JonnyHaystack** [comment]
Done https://features.jellyfin.org/posts/331/more-intuitive-play-resume-when-clicking-on-a-tv-show-movie

**Comment by JustAMan** [comment]
Thanks! I'm going to close this issue in favour of that feature request.
