### ISSUE TITLE
Unable to connect any android app (tv, smartphone) since yesterday server update

### ISSUE THREAD

**Issue by PhieF** [jellyfin/jellyfin#1976]
Hi, 

Since yesterday I am not able to connect android apps anymore to my server

the only thing it says on android is to check if the server is available

on server side the only error I have is

"Could not find handler for /jellyfin/socket"

it works well on web browser

**Comment by PrplHaz4** [comment]
@PhieF please see the release notes here, there was a breaking change introduced in 10.4.1: https://github.com/jellyfin/jellyfin/releases/tag/v10.4.1

Unless you have a need for the new basepath, your best bet is likely to set the basepath to blank (remove /jellyfin), then restart the server.  Then, if needed, re-set your android clients to use the blank-basepath URL as the server.

This should get you back to the intended default configuration...

**Comment by PhieF** [comment]
Thanks ! it works !
