### ISSUE TITLE
Upgrading from 10.4.0 to 10.4.1 breaks Emby client on WebOS

### ISSUE THREAD

**Issue by VoodooZ** [jellyfin/jellyfin#1978]
And yes... I did read the release notes about the URL change and modified my config accordingly.
Connecting to my Dashboard using my portable works fine.
But for some reason my Emby client (WebOS) gives auth failures.
I even tried adding a new server from scratch but same thing.
Is the URL change thing expected to affect clients? It would really suck to lose the ability to use Emby, even though I understand it's not "official".

I'm using Emby Theater client 1.0.9 on WebOS (65BP7 OLED)
Running Jellyfin on Centos 7.7.1908

Thanks in advance

**Comment by JustAMan** [comment]
We don't intend to support compatibility with Emby apps forever.
Note that they've deliberately broken compatibility with us in the early days of Jellyfin.

So I don't think this particular issue would get a lot of attention.

The only thing I can say is that we have a few more fixes for baseURL waiting to be released, so maybe some of those would fix Theater for you.

**Comment by VoodooZ** [comment]
I know but there seems to be a lot of people using it regardless (some use a path rewrite trick). I'm still using the old version that works without problem btw.  
I've tried the alternatives and they are far from fully featured. What's the recommend/supported one?
Because that's ultimately what makes or breaks Jellyfin if you ask me. 

But thanks for the suggestion, I've reverted back to 1.4 for now and was thinking of trying the next few update to see if it fixes it. Otherwise I guess I'll have to find something else to use.

**Comment by JustAMan** [comment]
Unless you would be able to show us some logs (and that should be client-side logs I fear, from WebOS itself) I don't think we'll be able to fix that. Maybe @EraYaN has some ideas as he was trying to work on WebOS-related stuff, though...

As for alternatives - I personally open JF web UI via TV's browser. That ain't pretty, and some stuff doesn't work in my WebOS2 (like 4K playback, as browser is FullHD there - blame crazy LG!), but it's passable for me for the time being.
