### ISSUE TITLE
Not able to connect to app after update

### ISSUE THREAD

**Issue by docfactory37** [jellyfin/jellyfin#1981]
**Describe the bug**
When I open the jellyfin app on and android  it will not connect.

Before update I was able to connect.

I'm using jellyfin im a docker contain by linuxserver/jellyfin

![Screenshot_20191105-222058_Jellyfin](https://user-images.githubusercontent.com/20963053/68203748-9d835100-001a-11ea-9286-2c9a93b59790.jpg)

**Comment by docfactory37** [comment]
![Screenshot_20191105-222303_Chrome](https://user-images.githubusercontent.com/20963053/68203854-df13fc00-001a-11ea-9a97-d55ff0046341.jpg)

**Comment by docfactory37** [comment]
Also cryed connecting jellyfin to kodi Same thing

![Screenshot_20191105-222803](https://user-images.githubusercontent.com/20963053/68204436-1931cd80-001c-11ea-8f21-92c832aca3fe.jpg)

**Comment by bitrvmpd** [comment]
Hello, maybe it has something to do with the Base URL change? 

Check if adding "/jellyfin" at the end of the host url fixes it. In your case `192.168.1.101:8096/jellyfin` or follow the steps here https://github.com/jellyfin/jellyfin/releases/tag/v10.4.1

**Comment by docfactory37** [comment]
Sorry guys I did some more investigation and pull the jellyfin/jellyfin docker container and this is not happening it is working as it should look to be and issue with that docker build not the proper docker image the you's provide I will be switching back.

It's a grate project love it sorry for the false alarm.

**Comment by sp00ling** [comment]
Thank you @bitrvmpd i iwll try that and also check that its not a Docker Build issue.
