### ISSUE TITLE
Can't add custom images

### ISSUE THREAD

**Issue by ferferga** [jellyfin/jellyfin#1983]
**Describe the bug**
Custom images to media can't be uploaded to the server through the "Edit media" option. Logs report ``System.ArgumentException: Requested value 'Images' was not found.``

**To Reproduce**
1. Choose an item in your library > 3 dots
2. Choose "Edit images" > +.
3. Upload the image

The loop will be spinning forever.

**Logs**
This is outputted in ``syslog`` after doing this: ``System.ArgumentException: Requested value 'Images' was not found.``

**System (please complete the following information):**
 - OS: Debian on Raspberry Pi 3B+
 - Browser: Chrome 78
 - Jellyfin Version: 10.4.1
 - Reverse proxy: nginx

**Comment by ferferga** [comment]
Seems related to the baseUrl change, only affecting users with custom baseUrls: https://www.reddit.com/r/jellyfin/comments/drzj0o/image_upload_broken_in_new_release/?utm_medium=android_app&utm_source=share

**Comment by exalented** [comment]
Arch Linux here.

This has been broken for me ever since the first release. I try to change any image, but the poster image and I get this infinite loading issue.

**Comment by ferferga** [comment]
@exalented Are you using a reverse proxy, right? Because this has been introduced in 10.4.1, known issues with this were all caused by reverse proxies.

That's a completely different issue.

**Comment by exalented** [comment]
> @exalented Are you using a reverse proxy, right? Because this has been introduced in 10.4.1, known issues with this were all caused by reverse proxies.
> 
> That's a completely different issue.

This is 100% correct. Sorry for the confusion.

**Comment by ferferga** [comment]
@exalented If you need help with it though I can try to help you, I also faced it when I configured it! :)

**Comment by ParadiseStudios** [comment]
I have this problem upon upgrading to 10.4.1 using docker image. If I could figure out how to downgrade I would. I am not using a custom url, it's an local ip address and I cannot remove /jellyfin from the url because it puts it back in automatically. Does anyone know how to use docker-compose pull jellyfin to a specific (10.4.0) version?

**Comment by ferferga** [comment]
This was finally fixed back in 10.4.1-10.4.2.
