### ISSUE TITLE
BaseUrl only allows for lowercase and setting it to something breaks Chromecast

### ISSUE THREAD

**Issue by exalented** [jellyfin/jellyfin#1984]
**Describe the bug**
You cannot set the BaseUrl to include an uppercase letter otherwise you're unable to login and when you do set the string lowercase then Chromecasting doesn't work.

**Expected behavior**
<BaseUrl>/Suss</BaseUrl>
*Able to login and utilize Chromecast*
**What actually happens**
<BaseUrl>/Wew</BaseUrl>
*Unable to login*
Or
<BaseUrl>[anythinglowercase]</BaseUrl>
*Still unable to Chromecast*

**System:**
 - OS: Arch Linux
 - Browser: Firefox, Chromium
 - Jellyfin Version: 10.4.1-1
 - Reverse proxy: nginx and direct access.

**Additional context**
Again this is running on Arch Linux installed through the AUR.

**Comment by JustAMan** [comment]
I wonder if https://github.com/jellyfin/jellyfin/pull/2020 could be fixing it

**Comment by exalented** [comment]
This is not fixed with jellyfin 10.4.2

**Comment by anthonylavado** [comment]
>This is not fixed with jellyfin 10.4.2

@exalented #2020 didn’t make it in, but it should be part of the next release.
