### ISSUE TITLE
Season Metadata provider only lists TheMovieDB

### ISSUE THREAD

**Issue by spoolr** [jellyfin/jellyfin#1985]
Version: 10.4.1
Operating System: Linux
Architecture: X6

When I select "TV Shows" as my Library Content type.  Season Metadata only lists TheMovieDB as a provider.  Consequently, I get no season info in my library.  The Library finds the series, and the latest TV episode, but the "Season" header has no info below it.  It just goes straight to "Cast".

Here are the available providers.  What file can I edit to reset these?

Language: English
Country: United States

Series metadata downloaders:
+TheTVDB
-TheMovieDb
+The Open Movie Database

Season metadata downloaders:
+TheMovieDb

Episode metadata downloaders:
+TheTVDB
-The Open Movie Database
-TheMovieDb

**Comment by anthonylavado** [comment]
I mentioned this briefly on our Matrix Chat, but for the sake of the issue:

TheMovieDV is the only supported Season Metadata Downloader right now. Contrary to their name, they do have information about TV Shows.

I think at the suggestion of another user, you enabled "Show Missing Seasons", which seems to have solved it, for now...
