### ISSUE TITLE
Jelly fin doesn't allow filtering by Provider IDs

### ISSUE THREAD

**Issue by RrrrobertB1992** [jellyfin/jellyfin#1990]
**Describe the bug**
Using Emby, you are able to filter API results using "AnyProviderIdEquals" with the value set as the provider.id.

**To Reproduce**
1. Append "AnyProviderIdEquals=imdb.IMDB" to the end of an API call, replacing IMDBID with an IMDBID you have in your server
2. Returned movies list includes all movies in my database

**Expected behavior**
Return only the movie with the provided provider ID/IDs

**Logs**

**System (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 70.0.0.1, Chrome 77.0.3865.90
 - Jellyfin Version: 10.4.1
 - Reverse proxy: No

**Additional context**
The API call I am using, which works correctly in Emby (Adjusted the Port, USERID and API key to use with JellyFin)
http://localhost:8096/Users/USERID/Items?Recursive=true&IncludeItemTypes=Movie&AnyProviderIdEquals=imdb.tt0103639&api_key=APIKEY
In Emby it returns only "Aladdin (1992)"
In Jellyfin it returns every movie

**Comment by JustAMan** [comment]
Jellyfin is not Emby, so this is not a bug but a feature request, re-classifying.

**Comment by cvium** [comment]
Re-open on https://features.jellyfin.org if it's still wanted
