### ISSUE TITLE
Multiple formats of the same video not being grouped

### ISSUE THREAD

**Issue by juicetin** [jellyfin/jellyfin#1996]
Based on this post here - https://www.reddit.com/r/jellyfin/comments/bj9g72/how_does_jellyfin_deal_with_multiple_formats_of/ from a member of the jellyfin core team (which points to this documentation page - https://github.com/MediaBrowser/Wiki/wiki/Movie-naming#multi-version-movies), Jellyfin should be able to handle multiple formats (in my case, qualities - i.e. 1080p, 480p, 720p, etc.) of the same video by using a folder name matching the base filename, with " - <quality>" appended after it, before the extension.

However, after trying this, jellyfin ends up creating as many records in the show as there are of the file, instead of having a dropdown letting you select the quality as mentioned in the above link.

**Comment by anthonylavado** [comment]
@jucietin - Could you show us how your files are currently named, and what directories they're in?

**Comment by juicetin** [comment]
@anthonylavado here's an example of two naming formats I tried

```
The Magicians (2015) - S04E12 - The Secret Sea Bluray-1080p/
  'The Magicians (2015) - S04E12 - The Secret Sea Bluray-1080p [Fast 720p30].mp4' 
  'The Magicians (2015) - S04E12 - The Secret Sea Bluray-1080p [Very Fast 480p30].mp4'
  'The Magicians (2015) - S04E12 - The Secret Sea Bluray-1080p [Very Fast 576p25].mp4'
```
```

The Magicians (2015) - S04E12 - The Secret Sea Bluray-1080p/
  'The Magicians (2015) - S04E12 - The Secret Sea Bluray-1080p - Fast 720p30.mp4' 
  'The Magicians (2015) - S04E12 - The Secret Sea Bluray-1080p - Very Fast 480p30.mp4'
  'The Magicians (2015) - S04E12 - The Secret Sea Bluray-1080p - Very Fast 576p25.mp4'
```

**Comment by juicetin** [comment]
I was following this thread that looked to be asking about the same functionality
https://www.reddit.com/r/jellyfin/comments/dvbmxz/how_do_i_host_same_series_bit_different_version/

And the long-press to group manual workaround works perfectly. Would definitely be amazing to figure out if the functionality is in fact working and the correct way to name the files just isn't common knowledge/documented officially yet!

**Comment by JustAMan** [comment]
cc @cvium who IIRC was the last one to touch that part of code

**Comment by anthonylavado** [comment]
@juicetin To follow up, it just looks like whatever does this automatically isn’t working.

**Comment by juicetin** [comment]
@anthonylavado thanks for the follow up! Any chance you could point towards the area(s) of choice responsible for this behavior? Might try and take a look at if I have some spare time

**Comment by juicetin** [comment]
@anthonylavado just wondering if there is work on this at the moment, or is it assigned just to have a member issue owner?

Mainly asking as I might try and set some time aside to poke around the code to in the next month and a half during down time, perhaps look at how it's being done for movies (where it's apparently working, I haven't tested movies myself), and see how much of that logic is or isn't reusable to work for tv shows.

**Comment by ilteoood** [comment]
Hi, any news about this?

**Comment by holow29** [comment]
Seems to be same/similar issue: https://github.com/jellyfin/jellyfin/issues/2112

**Comment by cvium** [comment]
Automatic grouping of episodes is currently not supported. See https://features.jellyfin.org/posts/251/multiple-versions-drop-down-on-tv-series
