### ISSUE TITLE
[Feature Request] Change Filepaths inside Media Libary

### ISSUE THREAD

**Issue by nerxses** [jellyfin/jellyfin#1999]
hi everyone,

when you click on "edit metadata" of any kind of video, photo, ... etc. It should be possible to change the location at which jellyfin thinks the file/folder resides. Currently you only see the path which jellyfin is accessing but you cannot change it. Jellyfin should not move the whole file, it should only move it's link to it.

The reason is the following: On a storage system build with SSDs for fast access and HDDs as long term storage the file gets, at some point, moved from the SSDs to the HDDs. The current version(10.4.1) of jellyfin cannot handle that. If the file is moved to another location, jellyfin deletes the old Series/photo and adds a new one. Therefore the old metadata is completely lost (Rating, Favorites, Watched, Progress).

**Comment by anthonylavado** [comment]
Would you be able to post this as a request on our features page? Thanks!

https://features.jellyfin.org

**Comment by nerxses** [comment]
@anthonylavado done https://features.jellyfin.org/posts/322/change-filepaths-inside-media-libary
