### ISSUE TITLE
Revert to previous version of Jellyfin? Nov 3 Update to Jellyfin stopped working with Samsung TV Emby App

### ISSUE THREAD

**Issue by deten** [jellyfin/jellyfin#2000]
**Describe the bug**
Prior to my container update on Nov 3, Jellyfin worked fine with the Samsung TV App. (Ihad disabled autoupdate on my samsung tv a long time ago).  After the Nov 3 update it stopped working.

Is there any way to revert back to a previous version or change the setting to reallow access?

**Comment by deten** [comment]
Solved by removing /jellyfin from Networking.  Then restarting the container.

**Comment by roondar** [comment]
I @deten, can you be more precise ? :)

**Comment by JustAMan** [comment]
@roondar just please, PLEASE read the release notes :P and follow them!

https://github.com/jellyfin/jellyfin/releases/tag/v10.4.1

**Comment by roondar** [comment]
> @roondar just please, PLEASE read the release notes :P and follow them!
> 
> https://github.com/jellyfin/jellyfin/releases/tag/v10.4.1

Thanks men, I haven't related the 2 things. :p

**Comment by deten** [comment]
![image](https://user-images.githubusercontent.com/6029514/69446476-5cbd5480-0d09-11ea-9770-26faec14c5c2.png)

![image](https://user-images.githubusercontent.com/6029514/69446431-3e575900-0d09-11ea-9341-eb806d80189a.png)
****

In settings go to Networking and scroll down to the one that says /jellyfin and delete, save and restart container.
