### ISSUE TITLE
Why does apt tell me that emby-server will be removed upon installation?

### ISSUE THREAD

**Issue by anohren** [jellyfin/jellyfin#2003]
I followed the install instructions. When running `sudo apt install jellyfin` it warns me that `emby-server` will be removed. Why? This blocks me from installing.

**Comment by joshuaboniface** [comment]
The `.deb` package `conflicts` with `emby-server` explicitly due to overlapping ports and several legacy items. To test out Jellyfin we recommend using a dedicated VM, Docker or the portable Linux binary package.

**Comment by anohren** [comment]
Thanks. I see.

Did I miss a mention of this in the Debian install instructions? I couldn't find one. 

As you can imagine I am not prepared to uninstall a working solution just to test a potential replacement, so this results in not trying Jellyfin at all.

> To test out Jellyfin we recommend using a dedicated VM, Docker or the portable Linux binary package.

Thanks, I might check it out.

**Comment by Czerwony-Kapturek** [comment]
Wanted to try jellyfin and it looks like my emby is now gone ;-(
There was no warning message unfortunately.
Conflicting ports are easy to fix, what are the "several legacy items"?
