### ISSUE TITLE
No audio in Chrome/Firefox

### ISSUE THREAD

**Issue by crobibero** [jellyfin/jellyfin#2004]
Version: 10.4.1
Browser: Chrome, Firefox

Issue: No audio plays in Chrome and Firefox, plays correctly in Edge. I have multiple files that have this issue and can replicate it 100% of the time. Please let me know if more information is needed to help debug.

[MediaInfo](https://github.com/jellyfin/jellyfin/files/3834012/the.flash.s06e01.info.txt)
[Edge ffmpeg](https://github.com/jellyfin/jellyfin/files/3834013/edge-ffmpeg-remux-3446f3d0-7b11-40b7-a415-747b95401dfc.txt)
[Firefox ffmpeg](https://github.com/jellyfin/jellyfin/files/3834014/firefox-ffmpeg-directstream-bb565484-f6a9-4920-8e62-d8ae5c743399.txt)
Chrome didn't create an ffmpeg log as it's direct playing.

**Comment by JustAMan** [comment]
I'm pretty sure it has something to do with the fact that your media file has audio encoded as `EAC3` (maybe even that it's a 6-channel thing matters).

I see that for Edge it was transcoded to just `AC3` (no `E`).

**Comment by crobibero** [comment]
Audio playback for this specific file is fixed, so I'm marking it as resolved!
