### ISSUE TITLE
Support for oauth2 authentication

### ISSUE THREAD

**Issue by sambhavsaggi** [jellyfin/jellyfin#2012]
**Describe the bug**

Allow logging in via oauth2

**To Reproduce**

1. Try to add oauth2 as a sign in solution (under plugins)

**Expected behavior**

Allow adding of oauth2 authenciation

**Logs**

n/a

**Screenshots**

n/a

**System (please complete the following information):**
 - OS: Debian Buster
 - Browser: Chromium 78.0.3904.87
 - Jellyfin Version: Jellyfin.Server 10.4.1.0
 - Reverse proxy: Using pfSense to port forward from inside Proxmox

**Additional context**

Pretty much like the LDAP authentication. A plugin would be nice

**Comment by JustAMan** [comment]
Can we have it as a feature request here please: https://features.jellyfin.org/ ?

**Comment by sambhavsaggi** [comment]
As this already exists on that page, I am closing this now.

https://features.jellyfin.org/posts/271/oauth-support

**Comment by 9p4** [comment]
I have created my own: https://github.com/9p4/jellyfin-plugin-sso

**Comment by ltzmax** [comment]
sad it has been staying on [planned](https://features.jellyfin.org/posts/271/oauth-support) since 2019. :|
