### ISSUE TITLE
Unable to save playback settings 

### ISSUE THREAD

**Issue by mazzystr** [jellyfin/jellyfin#2014]
**Describe the bug**
Something seems to be going on with the Playback app in Dashboard.  I am unable to save settings.  I get the spinny thing forever.  If I delete the coresponding file conf/encoding.xml it will be recreated with root:root and 666 permissions.  SELinux is disabled.

**System (please complete the following information):**
 - OS: Centos 7
 - Browser: Firefox
 - Container: jellyfin/jellyfin
 - Jellyfin Version: 10.4.1
 - Reverse proxy: haproxy

**Additional context**

**Comment by Bond-009** [comment]
Duplicate of #1881 and fixed by #2008
