### ISSUE TITLE
Playback controls disappearing from UI on iOS

### ISSUE THREAD

**Issue by deanishe** [jellyfin/jellyfin#2018]
**Describe the bug**

Play/pause and skip controls disappear from UI after being pressed on iOS 13.

**To Reproduce**

1. Start playback on iOS using Jellyfin UI
2. Wait for playback controls to fade out
3. Tap to make controls visible again
4. The play/pause button is gone

Only the play/pause and skip buttons appear to be affected.

**Expected behavior**

Buttons should not disappear from the UI

**Screenshots**

After pressing all three buttons:
![vlcsnap-2019-11-17-19h27m27s813](https://user-images.githubusercontent.com/747913/69011946-7577e400-0970-11ea-9690-8a7050a2ef1b.jpg)

[Screen recording on imgur](https://i.imgur.com/LE92u8W.mp4).

**System (please complete the following information):**
 - OS: iOS 13.1.3
 - Browser: Firefox, Safari
 - Jellyfin Version: 10.4.1
 - Reverse proxy: caddy

**Additional context**
Bug can be worked around by pressing a different button (subtitles, config) before the controls fade out. In this case, the playback controls do not disappear.

**Comment by Vitorvlv** [comment]
Seems to be this issue: https://github.com/jellyfin/jellyfin-web/issues/530
Also happening for me on the android app.

**Comment by deanishe** [comment]
Yes, it does appear to be the same issue. I did search existing issue, but always included "ios".

I should have had the sense to suspect it's a general mobile issue.

Thanks for the link to the existing issue.
