### ISSUE TITLE
Duplicated entries in 'upcoming' page for TV, and incorrect schedule

### ISSUE THREAD

**Issue by viggy96** [jellyfin/jellyfin#2023]
**Describe the bug**

**To Reproduce**

1. Go to 'TV Shows'
2. Click on 'Upcoming'

**Expected behavior**
Upcoming episodes should show up under the day they are going to air. 

**Screenshots**
![image](https://user-images.githubusercontent.com/9837626/69025441-ff39a880-0994-11ea-871c-7cb7b6b54dc9.png)
![image](https://user-images.githubusercontent.com/9837626/69025475-2bedc000-0995-11ea-826f-6860db37d3e0.png)

**System (please complete the following information):**
 - OS: Docker
 - Browser: Google Chrome
 - Jellyfin Version: 10.4.1
 - Reverse proxy: nginx

**Additional context**
I'm not sure where Jellyfin gets its show schedule information from, but it doesn't appear to be very accurate, possibly helping lead to the above where some entries are duplicated under multiple days. Also, some episodes aren't even listed even though they should be. In this example, you can see the Simpsons, Rick and Morty, Last Week Tonight, aren't listed under Sunday, even though they should be. Fairy Gone and Vinland Saga are listed under Monday instead (just below where screenshot ends). This is kinda confusing for users, for episodes to show up under the wrong day, or sometimes not at all.

**Comment by JustAMan** [comment]
Is this about aired episodes only (like, shown on normal TV)?

**Comment by viggy96** [comment]
Both aired and upcoming shown on TV. The schedule information appears to be incorrect, which seems to lead to duplicated entries such as what is shown above, when an episode airs on the next day compared to when Jellyfin thought the episode would air.

**Comment by viggy96** [comment]
Where does Jellyfin get its TV schedule data?

**Comment by PrplHaz4** [comment]
> Where does Jellyfin get its TV schedule data?

Wherever you tell it to in livetv setup. Schedules direct XML or iptv provider URL. Surprised you have anything showing if you haven't set those up.

**Comment by viggy96** [comment]
Even if you don't use live TV? Sonarr just grabs info from tvdb. I think that should be an option for those who don't use live TV at all.

**Comment by Protektor-Desura** [comment]
It does grab upcoming info from TVDB. But it has the dates all wrong. Sonarr handles the dates of upcoming shows correctly and even shows it in the Sonarr calendar the local time when the show will be on. So this is possible to do correctly and do it using C# because Sonarr is doing it correctly in C# and .NET.
https://github.com/Sonarr/Sonarr

This has still not been fix because I am showing shows as "Yesterday" when they should be today in Jellyfin 10.5.5. Everything in upcoming is off by one day.

**Comment by viggy96** [comment]
Just keeping this issue open.

**Comment by viggy96** [comment]
Is this issue fixed in the upcoming 10.7.0 release, when using TMDb as a source instead of theTVDB?

**Comment by crobibero** [comment]
I’m fairly certain that this is a TVDB issue, and not a Jellyfin issue. As far as I know, Sonarr grabs tvdb data and manipulates it to be correct.

**Comment by viggy96** [comment]
@crobibero Yeah, I just thought that with TVDB being phased out and not being included by default, and being spun out into a plugin instead, that Jellyfin would change its source for schedule data.

**Comment by crobibero** [comment]
The source of data is whatever you make it. I believe the tvdb plugin no longer adds future data, that has been moved to https://github.com/jellyfin/jellyfin-plugin-missingepisodeprovider

**Comment by viggy96** [comment]
Keeping this issue alive
