### ISSUE TITLE
Adding a folder to a library breaks other libraries with subfolders

### ISSUE THREAD

**Issue by trwnh** [jellyfin/jellyfin#2024]
### Description
Libraries containing a folder that is a subfolder of another library will incorrectly show as empty.

### Steps to reproduce
First try:
1. Created a library "All Media" and added `/media`. Loads correctly.
2. Created a library "Music" and added `/media/music`. Shows as empty.
3. Remove library "All Media". Suddenly, "Music" library works.

Removed all libraries and tried again:
1. Created a library "Music" and added `/media/music`. Works.
2. Created a library "Music and Movies" and added `/media/music` and `/media/movies`. Both libraries still work.
3. Created a library "All Media" and added `/media/`. Now "Music" is showing as empty again.

### System info
- Docker container `linuxserver/jellyfin` with volume mapping `/storage/media` to `/media`
- Web UI through Firefox at `home:8096`

### Implication

Instead of being able to simply define the root folder for a "mixed content" library, I am forced to add multiple folders, which makes for a tedious setup process while testing and evaluating Jellyfin for further usage. Either that, or I should use "mixed content" for all of my libraries, since this issue only seems to affect typed libraries.

**Comment by devbrian** [comment]
Feel like this could possibly be something implemented intentionally to prevent duplicates.
