### ISSUE TITLE
Manually add subtitles

### ISSUE THREAD

**Issue by jee-r** [jellyfin/jellyfin#2026]
Hello,
this is a feature request. 
It would be really useful to be able to add subtitles **manually*** from the web-ui as Kodi does.

what do you think?

*edit: by manualy i mean add a subtitle file from my computer (local storage), i think that plex has a similar feature but i'm not sure.

**Comment by RazeLighter777** [comment]
What's harder about just dropping them in the folder? It's probably faster that way anyway, because you don't have to upload each subtitle individually.

**Comment by jee-r** [comment]
Personally I don't always have access to my server in case i'm not at home (in other words if i'm not connected to my LAN) but if I have an internet connection i have always access to jellyfin.

This case happened to me 2 days ago, I was at a friend's house and we wanted to watch an episode but the subtitles were bad.

**Comment by ellidi** [comment]
This would be nice feature. And it would be great if Jellyfin could automatically detect subitles in a subfolder.

**Comment by garikaib** [comment]
I think it already does this if the subtitle file name matches the video file name.

> This would be nice feature. And it would be great if Jellyfin could automatically detect subtitles in a subfolder.

**Comment by jee-r** [comment]
> I think it already does this if the subtitle file name matches the video file name.
> 


As i said, this requires an access to the server filesystem sftp/ftp/samba which is not always possible.

**Comment by ellidi** [comment]
> I think it already does this if the subtitle file name matches the video file name.

Subfolder. As in a folder within the folder...

Like so:
Media directory -> Film from 1997 -> Subs -> 2_eng.srt

**Comment by garikaib** [comment]
> > I think it already does this if the subtitle file name matches the video file name.
> 
> Subfolder. As in a folder within the folder...
> 
> Like so:
> Media directory -> Film from 1997 -> Subs -> 2_eng.srt

Yeah, that also works but I think OP wants a way to add subtitles from the front end. For example, click on the captions button in player and in addition to the list of subtitles available there is an upload button. Uploading a subtitle will allow the player to use it to display captions. What's not clear is whether the OP wants these subtitles to go into the Video folder or temporary for that session for example.

In the wild, I have seen three implementations of this feature

1. An upload button as mentioned above and the subtitles only exist during that session
2. An upload where the file actually goes to the server and is stored there permanently
3. Instead of an upload button, there is a search button that allows the user to search various subtitle services e.g. OpenSubtitles and Addic7ed and downloads the file temporarily as above. These seems to be OP's preference since this is how Kodi does it when playing form say a Jellyfin server.
Examples of services that do this include Premiumize and Seedr.

**Possible solution**
This would be a cool feature but the reason why a lot of people are not clamouring for this is because there are solutions such as Bazarr. It would allow you to do all this but it's not tied into Jellyfin. What you could do is go to Bazarr search or upload subtitles there. Reload Jellyfin and you would be good to go.

**Comment by jee-r** [comment]
> What's not clear is whether the OP wants these subtitles to go into the Video folder or make those temporarily available for that session for example.

@garikaib Temporary would be sufficient

> An upload button as mentioned above and the subtitles only exist during that session

That's exactly what I was thinking.

I didn't know Bazarr, thanks for pointing that out. I'll take a look, this can be a workaround

**Comment by garikaib** [comment]
@jee-r it seems the feature you were looking for is now supported in the subtitles plugin. Just go to the Dashboard and install the plugin, restart Jellyfin, enter your OpenSubtitles username and password. Restart Jellyfin, Go to whatever movie/episode you want to add subtitles to, click on the three dots which are just to the right of the favourite button, click edit subtitles, select the preferred language in the dropdown box and click search, click on the download button and voila.

**Possible step**
It's possible you might have to go and edit Libray options to include search for subtitles after you have installed the subtitle plugin.
![Screenshot from 2020-01-05 15-54-52](https://user-images.githubusercontent.com/7372322/71781152-20ea0000-2fd4-11ea-9829-d3b51af7bd32.png)

**Comment by dkanada** [comment]
@garikaib you might be the first user I have seen using the light theme! If you can think of any improvements we would welcome a pull request, that theme is somewhat neglected.

**Comment by garikaib** [comment]
@dkanada I will definitely will. It is my prefered theme TBH I got sick of dark mode in every app. Sometimes dark mode looks good sometimes it doesn't.

**Comment by dkanada** [comment]
Sounds good. Just to make your search easier, the light theme can be found [here](https://github.com/jellyfin/jellyfin-web/blob/master/src/components/themes/light/theme.css) at the moment. The themes might get moved to the top directory at some point for better visibility though.

**Comment by ellidi** [comment]
> @jee-r it seems the feature you were looking for is now supported in the subtitles plugin. Just go to the Dashboard and install the plugin, restart Jellyfin, enter your OpenSubtitles username and password. Restart Jellyfin, Go to whatever movie/episode you want to add subtitles to, click on the three dots which are just to the right of the favourite button, click edit subtitles, select the preferred language in the dropdown box and click search, click on the download button and voila.
> 
> **Possible step**
> It's possible you might have to go and edit Libray options to include search for subtitles after you have installed the subtitle plugin.
> ![Screenshot from 2020-01-05 15-54-52](https://user-images.githubusercontent.com/7372322/71781152-20ea0000-2fd4-11ea-9829-d3b51af7bd32.png)

I'm pretty sure OP means that he wants to be able to upload subtitles from his local machine, and not use the subtitles plugin to download from a 3rd party site :)

**Comment by jee-r** [comment]
@[GitHub](github.com)

Thank’s for your answer @garikaib but like @ellidi said ~~i want~~ i’m asking for have the possibility to add subtitle manualy from localstorage (my computer) directly in the Jellyfin UI or through a plugin. The problem with OpenSubtitles it’s that he is don’t very friendly with other langage that english (i’m french), addic7ed would be a better source for example but that’s is an other issue :)

May be it could be good to open a similar issue on [https://github.com/jellyfin/jellyfin-plugin-opensubtitles](https://github.com/jellyfin/jellyfin-plugin-opensubtitles)

#jellyfin #subtitles #opensubtitle #addic7ed #plugin

(Originally published at: https://jeer.fr/micro/1578448367)

**Comment by JustAMan** [comment]
This feels like a feature request, which we collect here: https://features.jellyfin.org/

**Comment by jee-r** [comment]
@[GitHub](github.com)

@JustAMan Yes I’ve already submitted this feature there ;) [https://features.jellyfin.org/posts/324/manually-add-subtitles](https://features.jellyfin.org/posts/324/manually-add-subtitles)

#jellyfin #subtitle #feature

(Originally published at: https://jeer.fr/micro/1579082844)

**Comment by shmilyoo** [comment]
It is hard to find the film folder everytime.  this is the reason
I think this feature is greate

**Comment by etobroflovski** [comment]
YES YES please, opensubtitles doesnt have many indonesian language. i want manually add sub in the client side.

**Comment by jee-r** [comment]
@etobroflovski Feel free to support this feature request with a  :+1: 
https://features.jellyfin.org/posts/324/manually-add-subtitles
 https://github.com/jellyfin/jellyfin-plugin-opensubtitles/issues/31

**Comment by kopax** [comment]
I all, I've just searched on opensubtitles, and the 1st choice was unsync, I couldn't test the other choices from the UI because jellyfin seems to only download the first choice. I had to manually go on opensubtitles download and install them.

I agree that manually adding subtitles should be a possibility, so as editing.

Non admin users should also be able to use a permissions to download subtitles. 

Any progress on that one? Thanks a lot!

**Comment by coxde** [comment]
This is a great feature. Plex can upload subtitles via web front end. It is too annoying to connect to the server every time to upload subtitles, and it's not possible for multi-user instances.

**Comment by Ullmie02** [comment]
This feature has been implemented and will be available with version 10.7

**Comment by Mubelotix** [comment]
> This feature has been implemented and will be available with version 10.7

As of 10.8, this is still not available

**Comment by daullmer** [comment]
> > This feature has been implemented and will be available with version 10.7
> 
> As of version 10.8, this is still not available

There is. Click the three dots for an item and choose
<img width="208" alt="Bildschirm­foto 2023-03-05 um 15 27 21" src="https://user-images.githubusercontent.com/16425113/222966534-225ade7b-941e-4a51-aee6-639074c8952a.png">
In that dialog you can click the plus icon to upload something

**Comment by Mubelotix** [comment]
> > > This feature has been implemented and will be available with version 10.7
> > 
> > 
> > As of version 10.8, this is still not available
> 
> There is. Click the three dots for an item and choose <img alt="Bildschirm­foto 2023-03-05 um 15 27 21" width="208" src="https://user-images.githubusercontent.com/16425113/222966534-225ade7b-941e-4a51-aee6-639074c8952a.png"> In that dialog you can click the plus icon to upload something

Thank you for your response. Unfortunately that's only for admin users because the subtitles get stored on the server

**Comment by kopax-polyconseil** [comment]
> Thank you for your response. Unfortunately that's only for admin users because the subtitles get stored on the server


I don't see how a feature that upload on a server can be only for admins. If I follow that logic, you would not be able to use internet as you use it today. 

Point is, it should be available for both registered and admin users.

**Comment by alex-vincent** [comment]
Can this be re-opened? I don't see this being available for non-admin users. I want to allow my users to download the odd subtitle just like Plex without needing admin privleges

**Comment by shyonae** [comment]
+1 for this, it would be amazing to have access for non-admin users. I hope this gets picked up again soon!

**Comment by perler** [comment]
yes, please make this available for all users!

**Comment by tariel36** [comment]
Any update on that?

**Comment by Mubelotix** [comment]
Subtitle settings of [movie-web](https://sudo-flix.lol/) are the perfect example of what we need

![image](https://github.com/jellyfin/jellyfin/assets/42696684/b9636353-6eca-4cbf-98cd-f5473c33c87d)

**Comment by JoeHogan** [comment]
FWIW - I'm able to Edit Subtitles through the browser UI (using the Open Subtitles plugin) but there is no such option on the android app (Fire TV)... meaning when I'm trying to watch a movie on my TV, i don't have the option to search for subtitles (Edit Subtitles) - I have to use my computer to do this, which is a non-starter for me. This is the only feature missing from the android app that is keeping me from ditching Plex, which does this very well.
