### ISSUE TITLE
PlaybackErrorNoCompatibleStream

### ISSUE THREAD

**Issue by LearnToRunFast** [jellyfin/jellyfin#2029]
**Describe the bug**

All the movies showing this error except Chinese movie
**To Reproduce**

1. Turned on the acceleration: Video Acceleration API(VAAPI)
2. When I turn it off, everything works fine.
3. Using ds918+ 

**Expected behavior**

Playing all movie except Chinses movies showing PlaybackErrorNoCompatibleStrea, it's fine to play with IINA
**Logs**

**Comment by yurui105** [comment]
I experienced the same.I received the error **PlaybackErrorNoCompatibleStream** when I turned on the hardware acceleration to play 4K movies(MKV format).I'm tried to solve it via #1610 ,and can't solved it.
I received the same result in Docker、Ubuntu18.04 and Windows.

**Comment by CurtisDensmore** [comment]
Also seeing this on CentOS. 
Any videos that require transcoding seem to show this error. I had to back-rev to 10.3.7.

I can probably clone my vm, upgrade it to 10.4.1 and post a debug log, if needed.

**Comment by Ebrithil95** [comment]
Same for me with NVENV enabled and h265 content. Running in Docker

**Comment by cryptobank** [comment]
@yurui105 @jiangqinhua can you see if turn off hardware encoding (only leave hardware decoding on) fixes the issue?

**Comment by yurui105** [comment]
I tried to turn off the hardware encoding and jellyfin can play the 4K movies normal.But the CPU can’t transcoding the 4K movies,I can feel it not fluency.

I found other 4K movies not MKV format ,jellyfin not report the error PlaybackErrorNoCompatibleStream ,but I still can’t play it.the player interface have a circle still keep rotate.

**Comment by cryptobank** [comment]
Unfortunately (hardware) trans-coding in Jellyfin is in a pretty bad shape
at the moment. I've had a go at fixing it for 2 days now with mixed
results(I got 4k 10 bit hevc -> h264 working well but hit a problem with
burnt in subtitles) I don't have C# background so that doesn't help.

**Comment by JustAMan** [comment]
This has to be investigated on movie-by-movie basis.
So for each case it fails to transcode please post a separate `mediainfo /path/to/file.mkv` and the ffmpeg log.

**Comment by jaiherro** [comment]
[ffmpegLog.txt](https://github.com/jellyfin/jellyfin/files/3991309/ffmpegLog.txt)
[MediaInfoDunkirk.txt](https://github.com/jellyfin/jellyfin/files/3991311/Dunkirk.txt)

**Comment by JustAMan** [comment]
@jaiherro do you have _any_ movies that transcode successfully on your setup? Also this particular movie is 10-bit, I think we have (or had, not sure of the current state) some issues about supporting 10-bit movies (plus VAAPI support for 10-bit varies depending on hardware).

**Comment by jaiherro** [comment]
@JustAMan Yeah, all movies and TV shows transcode normally, so long as they're not HEVC/10-bit, not exactly sure which causes the issue but it's one of the two.

**Comment by JustAMan** [comment]
This is most likely caused by https://github.com/jellyfin/jellyfin/issues/1527

**Comment by PrplHaz4** [comment]
someone just posted on matrix their fix to this error message was:
```
sudo usermod -aG video jellyfin
sudo systemctl restart jellyfin
```

**Comment by JustAMan** [comment]
@joshuaboniface maybe we should do `usermod` within our `.deb` package installation?

**Comment by barolo** [comment]
@JustAMan 
> This is most likely caused by #1527


This particular issue could be solved by converting color space in software as vaapi accelerated 10->8bit is not supported yet; by using ` -vf "hwdownload,format=p010le,format=nv12,hwupload" `
it works, speed oscillates around 3x on AMD APU, which is fine for couple of streams [ cpu is barely used ]
But this would require per hardware workarounds...

**Comment by cvium** [comment]
Might be OK now. Let us know if it persists.
