### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by michaelizergit** [jellyfin/jellyfin#203]
Greetings,

My apologies in case this is not the right channel to address this. I'm a designer in development and an open source enthusiast, who exploring GitHub found your project and decided to propose a logo design for it. It's (of course) totally free and we would be working together to create the design that fits best. In case you agree, you could share some ideas you may have (colours, shapes, etc) so I have something to start with.

Kind regards and keep up the great work!

**Comment by anthonylavado** [comment]
Hey there! We haven't really settled on a direction just yet, but I know there's been some discussion in #101, and there's been some mockups posted by the community to Reddit (r/jellyfin). I'll bring in some of the admin team to help groom these.

**Comment by nvllsvm** [comment]
@michaelizergit Show us something:

- purple
- does not contain letters or symbols
- looks good by itself, but also looks good to the left of the text "Jellyfin"

Use your imagination for the rest. :)

**Comment by nvllsvm** [comment]
Comments belong on https://github.com/jellyfin/jellyfin/issues/101
