### ISSUE TITLE
Binding to specific IP causes live TV to fail

### ISSUE THREAD

**Issue by hobesman** [jellyfin/jellyfin#2030]
**Describe the bug**
When Jellyfin is set to bind to a specific IP, it stops responding on 127.0.0.1, which I imagine is expected. However, live TV still tries to communicate with 127.0.0.1 and therefore fails when Jellyfin is bound to a specific IP. 

**To Reproduce**
1. Go to 'Settings -> Advanced -> Networking'
2. Click on 'Bind to local network address:'
3. Enter IP of a specific NIC
4. Restart Jellyfin (to make binding take effect)
5. Try to watch live TV.
6. See only spinning wheel and error in log.

**Expected behavior**
Live TV transcoder would try to communicate with the chosen IP and/or the transcoder would have access to Jellyfin despite IP binding.

**Logs**
In the Jellyfin log folder, the ffmpeg log ends with "http://127.0.0.1:8096/LiveTv/LiveStreamFiles/7c19bce258d7497e8136e2af8bca0722/stream.ts: Unknown error"

**System (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Jellyfin Version: 10.4.1
 - Reverse proxy: IIS (but same error when bypassing proxy)

**Comment by JustAMan** [comment]
So it looks like Jellyfin should be always binding to `127.0.0.1` when "bind to all interfaces" isn't active

**Comment by hobesman** [comment]
That would be one solution. Or I imagine the other solution would be if the transcoder could be told to look for the stream.ts at the chosen IP. I'm not sure which makes more sense so I'll leave that to people who know more than I do. But it seems like one of those two would be necessary in order for live TV to work.

**Comment by hemchandpidikiti** [comment]
Mine is also a similar problem. I installed jellyfin on an existing server whose if is 10.42.0.1 and can provide some service and internet through the established wifi connection.
But when i click 10.42.0.1:8096 in browser i didnt get it.
the output is same as above issue.
{{{{{System.IO.IOException: Failed to bind to address http://[::]:8096: address already in use. ---> Microsoft.AspNetCore.Connections.AddressInUseException: Address already in use ---> System.Net.Sockets.SocketException: Address already in use}}}}}
But to bind in localhost i dont have gui in my server.i usually use it through command line interface.
how can i bind it to my ip and it should also not clash with my existing localhost page.
like.. if i say 10.42.0.1 my default service should come and for 10.42.0.1:8096 jellyfin should appear.

**Comment by JustAMan** [comment]
This should be fixed by https://github.com/jellyfin/jellyfin/pull/2798, released in 10.5.5.
Please report if it's still an issue, until then I'm closing this one.
