### ISSUE TITLE
Random stuttering (buffering ?) during playback

### ISSUE THREAD

**Issue by accountForIssues** [jellyfin/jellyfin#2033]
**Describe the bug**
The playback stops from a couple to several seconds at a time during playback of random files. Usually, it's the case with large (or high bit rate files) but I've had cases where it happens with smaller files as well and on the other hand, I've had larger files playback smoothly without any issues. This has been happening ever since I did my setup (about a month or so) and is completely random.

I thought it could be my network not being capable but I can easily transfer those same files at constant speed via Wifi. Moreover, I looked at the server dashboard upon playback and the red line is far ahead than the point at which the playback stops so it's not like it's buffering.

Sometimes, the playback gets stuck at the beginning and then the file plays back smoothly. At times, the playback gets stuck after some time and there are times when the playback gets stuck repeatedly.

The log here is of a restart of the server and the playback of one such file where it starts off fine and gets stuck after some time.

**Expected behavior**
Smooth playback

**Logs**
[directstream_log](https://pastebin.com/7U1ESWDu)
[jellyfin_log](https://pastebin.com/2ejn4arZ)
[media_info](https://i.postimg.cc/QCSM2tRw/Screenshot-2019-11-21-Jellyfin.png)

**System (please complete the following information):**
- Raspberry Pi 4 - 4GB version / LG OLED B9
 - OS: Raspbian Buster/LG webOS
 - Browser: Firefox 68 (as per logs)
 - Jellyfin Version: 10.4.1/10.4.0 (web)

**Additional context**
Media is on 5 TB Seagate external drive connected via USB 3.0 to the Pi.
Both the Pi and the TV are connected via ethernet.

Examining the logs, I see a few of these:

```
[2019-11-21 14:39:12.431 +01:00] [ERR] Error processing request: "The operation was canceled."
```

I'm pretty sure these are the times where the playback was stopped.

**Comment by JustAMan** [comment]
Can you gather debug logs (enabled as per https://github.com/jellyfin/jellyfin-docs/issues/159#issue-527168291) and post them here?

**Comment by accountForIssues** [comment]
Here's the debug log of an affected file. There were a few stutters in the first 10 minutes and then afterwards the playback was smooth with no issues. However, the playback stopped about 30 seconds before the end. I thought it was another random stutter but it didn't continue playing so I stopped the playback.
[jellyfin.zip](https://github.com/jellyfin/jellyfin/files/3879881/jellyfin.zip)

**Comment by accountForIssues** [comment]
I don't know if I should make another issue for this or it is already a known issue but I notice a few more things (possibly unrelated to the above issue).

Often times there will be a noticeable skip at the start of the last 30-40 secs of the playback. This is usually at the time when the next video info pops up and it happens regardless of whether the next video is option is enabled or not. It doesn't really affect the experience but it is noticeable.

Another issue is after the playback has finished and before the summary screen is shown, the last 30-40 seconds of the video is played back again at > 3x the speed without the audio. It looks like a very quick slideshow of the last 30-40s. Mostly it happens one time before the summary screen is shown but there have been times where I saw the loop 2-3 times before the summary screen.

I have attached the debug log of a playback where there was a skip and the "slideshow" happened once playback was finished.

I really hope I made it clear what is happening.
[jellyfin.zip](https://github.com/jellyfin/jellyfin/files/3880274/jellyfin.zip)

**Comment by JustAMan** [comment]
Could you also please check if that happens in Chrome?

**Comment by accountForIssues** [comment]
@JustAMan On the server dashboard in active devices, the LG TV comes up as Chrome and in the log, I saw Firefox hence I wrote Firefox but it's just the default browser, I don't know whether it's based on Chrome or Firefox.

Unfortunately, I don't think there is a way to install other browsers on WebOS and I cannot really test on my other devices as none of them are able to direct play the 4K HDR files except for my TV.

Is there anything in the logs that explains the skips/stutters/buffers ?

**Comment by JustAMan** [comment]
Heh, don't trust your TV for anything. Please try reproducing it with a PC/laptop :)
Also, what is average bitrate of your file that you're having problems with? Showing `mediainfo /path/to/file.mkv` would be good.

**Comment by accountForIssues** [comment]
I think I might have solved this.

The playback only seemed to stop and buffer while the media file is being transcoded for the web client. Once the file is completely transcoded (i.e., the red bar on the server dashboard is fully filled), there are no stops/buffers. Do note that as previously mentioned, the red bar was always far ahead of the playback so it was never an issue about waiting for the next stream.

The playback seemed to suffer at random timestamps during the demuxing/transcoding of the file. Eg., playing back the same media file, sometimes the playback will suffer at the start, sometimes after a minute or two and sometimes much later. Additionally, during this time, the jellyfin server page will become almost non responsive.

So after testing the hard drives and the network, I wondered whether it would be the SD card in the Pi. It's a Sandisk 128 GB Class 10 U3 V30 card (benchmark below). Running the transcoding, the server and the system might have been too much for the SD card (which was mainly meant for an Android smartphone).

I changed the transcoding path in Jellyfin to one of the media library hard drives. After this, I restarted the server and tested the usual problematic files. Playback is smooth with no issues.

The issue seems to gone but I would, however, would appreciate comments/opinions on the below questions.

- Does it make sense that the SD card would be the bottleneck or is my configuration peculiar or the SD card needs to be replaced ? Would a better card resolve the bottleneck or is it better just to boot off the sd card and run the entire file system externally on an SSD ?

- Since the playback was only suffering during the transcoding process, a solution to this might be not to demux/transcode the entire file at the start and maybe do, say, the next 5 minutes. Basically do it in batches. Btw, Is there a reason to demux/transcode the file entirely during the start of playback ?

The benchmarks of my SD card in case if one's interested;
![SDTestResults](https://user-images.githubusercontent.com/52367365/69764959-619f5f80-1172-11ea-8887-a01989fb2fef.png)

**Comment by JustAMan** [comment]
> Btw, Is there a reason to demux/transcode the file entirely during the start of playback ?

Yes. Pauses or throttling in transcoding are not implemented in upstream ffmpeg :) and transcoding on a chunk-by-chunk basis is something we eventually want to make (sometime in the future - too many limitations in existing codebase for now).

As for storing transcoded stuff on your SD card - I won't do this not only because of performance, but because it potentially stresses the card too much (though usual Pi OS already wears out SDs like crazy).

Also, given you seem to pinpoint the issue to transcode path being on SD, can we close this issue?

**Comment by accountForIssues** [comment]
Thanks for the information about ffmpeg and transcode folder.

I will close the issue now, hopefully everything works out. :)
