### ISSUE TITLE
Some features request

### ISSUE THREAD

**Issue by Mandrake158** [jellyfin/jellyfin#2037]
Hi there, so I wanted to ask for a few features that I think would be good to have implemented eventually; I used Plex a long time ago, then I found Emby and went they went closed source, it was pretty dissappointing, didn't know about Jellyfin till 5 months ago, and have been using it ever since. However it would be pretty cool to have
* A small checkbox or something under the Specials/Season 0 folder that allows us to put an episode as a movie, as there are many movies that are part of the series and on TVDB appear under the special season;, would be good to have a small "Movies" subtitle between "Seasons" and "Cast & Crew" with all of the movies the series has and their own movie poster (which can be retrieved from MovieDB or manually)
* Two versions of the same episode, this feature was on Emby and I was really confused on why it didn't work on Jellyfin, for example I got 2 versions of some AVGN episodes, one is the original and the other is the reupload he did on YouTube; and even tho they have the same name with a "-Original/Reupload" to make them different, on Jellyfin they appear as 2 different videos unlike Emby which shows them as the same with a drop down to choose from (like Jellyfin does with movies)
* Group shows by collections, like we can do with movies: it is mainly for anime, and for some anime that may have a more unconventional way of handling seasons (or have all Star Wars series under a Star Wars collection), I like how AniDB/Anilist/MAL treats each season of, lets say JoJo/Monogatari/Fate as a different series, with different OVAs attached, different plot and so on, would be good if we could have AniDB as the metadata and then make a collection for the series and have them there, showing in just 1 big collection and name them whatever we want, it would also be good if we are able to go to "collections" on our library, find Monogatari, and being able to sort them either by release date (by the date aired) or by the order we added it/we manually put. (Having a custom sorting would be useful for movies that have sequels then prequels like Star Wars, and you want to either watch it 1-6 or 4-6 and then 1-3)

**Comment by Mandrake158** [comment]
And having the option to mark a series as not seasonal or something, there are some animes that are ongoing (Like Boruto) or some others that only have 1 season, would be better to just have all the episodes as soon as you scroll down, instead of having to click "season 1" and then start seeing all the episodes

**Comment by JustAMan** [comment]
Please submit those as separate requests on https://features.jellyfin.org/, it's impossible to track them as they're squashed into single issue otherwise.

**Comment by Mandrake158** [comment]
Ok, done :) Thanks; I wrote the 2 versions a few months ago on the features page, and since I never got any comment, I thought that page was not up to date anymore

**Comment by anthonylavado** [comment]
@Mandrake158 I answered on one of them: https://features.jellyfin.org/posts/251/multiple-versions-drop-down-on-tv-series

**Comment by JustAMan** [comment]
@Mandrake158 if you've got all your requests captured there, could you please close this issue?
