### ISSUE TITLE
A lot of settings can't be changed and throw errors

### ISSUE THREAD

**Issue by ashtez** [jellyfin/jellyfin#2044]
**Describe the bug**
A lot of settings can't be changed and throw errors, for example the following : 
Changing language also throws an error, it's impossible to change DLNA settings, and so on.

**To Reproduce**
1. Go to a user settings
2. Change state of "Hide this user from login screens"
3. See error : the indicator spins endlessly

**Expected behavior**
Should change state.

**Logs**
- System.FormatException: Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx). 
-  at System.Guid.GuidResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument, String failureArgumentName, Exception innerException) 
-  at System.Guid.TryParseGuidWithNoStyle(ReadOnlySpan`1 guidString, GuidResult& result) 
-  at System.Guid.TryParseGuid(ReadOnlySpan`1 guidString, GuidStyles flags, GuidResult& result) 
-  at System.Guid..ctor(String g) 
-  at MediaBrowser.Api.UserService.Post(UpdateUser request) 
-  at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task) 
-  at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken) 
-  at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)

**Screenshots**
![image](https://user-images.githubusercontent.com/7687660/69479303-0715a480-0dfc-11ea-85ae-8318ee305b6b.png)

**System (please complete the following information):**
 - OS: Docker on QNap
 - Browser: Firefox
 - Jellyfin Version: 10.4.1
 - Reverse proxy: no

**Comment by triDcontrols** [comment]
Have you read the release notes? Dev's point this out, has to do with the base URL settings. 

https://github.com/jellyfin/jellyfin/releases

**Comment by ashtez** [comment]
I did read them yes. How is this related to this bug thread ?

**Comment by userdocs** [comment]
It does seem directly related to the use of the base URL (using nginx to proxypass)

With base URL set to  `/jellyfin` i get the end loading when trying to save this setting

![2019-11-24_18-39-25](https://user-images.githubusercontent.com/16525024/69499415-cb590880-0ee9-11ea-86b7-515a33f5f436.png)

Here is the log error.

~~~
[2019-11-24 18:37:50.041 +00:00] [ERR] Error processing request
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Emby.Server.Implementations.AppBase.BaseConfigurationManager.GetConfigurationType(String key)
   at MediaBrowser.Api.ConfigurationService.Post(UpdateNamedConfiguration request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
~~~

If i remove the base URL it saves and it should but breaks the nginx proxy pass setup

**Comment by JustAMan** [comment]
Most of these should be fixed by updating to 10.4.2, please update and report the outcome.

**Comment by userdocs** [comment]
10.4.2 seems to have fixed the bug as i experienced it.

1: I have a BaseURL set to `/jellyfin`

2: I set a custom path to FFmpeg

3: I can now save and update this configuration without the endless loading spinner.

So for me it is resolved.

**Comment by ashtez** [comment]
Ok, 10.4.2 works like a charm ! Well done, developers ! 

PS: accessing your Jellyfin via a VPN seems to require RemoteAccess = true --> no idea why.

**Comment by ashtez** [comment]
Ok, 10.4.2 works like a charm ! Well done, developers !
