### ISSUE TITLE
QuickSync/iHD transcoding on Linux requires pixel format nv12

### ISSUE THREAD

**Issue by cryptobank** [jellyfin/jellyfin#2046]
I've built a custom ffmpeg on my debian buster so that I can test --enable-mpx on Linux instead of VAAPI(which only works for decoding at the moment, this bug has been raised previously #1901 ) and I'm pleased to say that it works very well for both Hardware Decode and Encode. However Encoding fails until scale_qsv=format=nv12 option is specified. Once this option is specified, transcoding happens.

UPDATE:

I went one step further and moved all scaling to qsv_scale
-vf "scale_qsv=w=1920:h=1080:format=nv12"

and add -hwaccel qsv.

**Logs**
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (hevc_qsv) -> h264 (h264_qsv))
  Stream #0:2 -> #0:1 (eac3 (native) -> mp3 (libmp3lame))
Press [q] to stop, [?] for help
[h264_qsv @ 0x562b98526500] Current pixel format is unsupported
[h264_qsv @ 0x562b98526500] some encoding parameters are not supported by the QSV runtime. Please double check the input parameters.
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height

ffmpeg version N-95857-g89aa1342b1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --target-os=linux --extra-cflags='-march=native -O2' --enable-hardcoded-tables --enable-gpl --disable-doc --disable-ffplay --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-libfontconfig --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libwebp --enable-libx264 --enable-libx265 --enable-libzvbi --enable-omx --enable-version3 --enable-vaapi --arch=amd64 --enable-libmfx

**Server System (please complete the following information):**
 - OS: Debian Buster iHD driver running
 - Jellyfin Version: 10.4.1
 - Hardware settings & device: QuickSync iHD
 
**Client System (please complete the following information):**
 - Browser (if Web client): Chrome

**Comment by JustAMan** [comment]
> pix_fmt yuv420p

This one should be acceptable as a sane default for any 8-bit h264 video I think. @EraYaN thoughts/objections?

**Comment by cryptobank** [comment]
> > pix_fmt yuv420p
> 
> This one should be acceptable as a sane default for any 8-bit h264 video I think. @EraYaN thoughts/objections?

As I further discovered this is better passed as an option to scale_qsv. It reduced CPU load and improves transcode speed. As it stands theres currently 3 issues with QuickSync transcode.

1) hwaccel -qsv option is missing (this is required to enable ffmpeg quicksync transcoding! man ffmpeg)
2) Scaling is done in software instead of hardware. 
 -vf "scale=trunc(min(max(iw\,ih*dar)\,1920)/2)*2:trunc(ow/dar/2)*2" 
 should be 
-vf "scale_qsv=w=1920:h=1080"
3) Pixel format is required. Adding format=nv12 to scale_qsv.
-vf "scale_qsv=w=1920:h=1080:format=nv12"

I tested yuv420p but it says that h264_qsv doesn't support it. It will also not support pix_fmt option.
