### ISSUE TITLE
Playback error: PlaybackErrorNoCompatibleStream on 10.4.1

### ISSUE THREAD

**Issue by cydrex** [jellyfin/jellyfin#2048]
i reinstalled jellyfin and files that worked last week now wont play. all i get Playback error: PlaybackErrorNoCompatibleStream on every signle file ltv/movie).
OS: ubuntu 18.04
jf version: 10.4.1
logs dont have anything related to issue.
tried both chrome(on pc) and phone app to play any tv or movie and same issue happens. 
also i have issue with saving user settings (infinite loop when saving).

**Comment by cydrex** [comment]
update: i found out my FFmpeg paty is empty in jf panel

**Comment by JustAMan** [comment]
Please update to 10.4.2 and try saving.
Also how did you install JF - docker/apt install/etc?

**Comment by userdocs** [comment]
This specific issue was due to installing Jellyfin locally as non root and there bing no ffmpeg in the path.

As soon as you install ffpmeg or link to manually the error goes away.

You can consider this issue resolved.
