### ISSUE TITLE
Cannot disable subtitles

### ISSUE THREAD

**Issue by ctrom** [jellyfin/jellyfin#2051]
**Describe the bug**
When I play a video in my library, the subtitles are always on by default.

**To Reproduce**
1. Play a video that has subtitles
1. Wait for video to buffer
1. Turn off subtitles
1. Wait for video to buffer again
1. Watch without subtitles

**Expected behavior**
I have looked through the menus but haven't been able to find a way to turn off the subtitles.

**Screenshots**
Every time I start a video, I have to switch the subtitles off:

![image](https://user-images.githubusercontent.com/1041401/69500543-c3856e00-0ec1-11ea-888d-1ef306de2bc0.png)

**System (please complete the following information):**
 - OS: Docker
 - Browser: Chrome
 - Jellyfin Version: 10.4.0
 - Reverse proxy: traefik

**Additional context**

**Comment by BlackSiO2** [comment]
What you are looking for is found in the subtitles section, found by clicking the user icon in the upper right then by clicking the link for subtitles and finally changing the Subtitle mode to No Subtitles.
