### ISSUE TITLE
"Log file cleanup" task does not work

### ISSUE THREAD

**Issue by therealmelee** [jellyfin/jellyfin#2056]
**Describe the bug**
Across multiple installations through the official Docker, the "Log file cleanup" task has never actually deleted old logs (described by the task as being "Deletes log files that are more than 3 days old."

**To Reproduce**
1. Look at your log folder or click "Logs" in the admin dashboard sidebar.
2. See that there are logs (log_20191125.log) aged far greater than 3 days.
OR
3. Go to admin dashboard, "Scheduled Tasks"
4. Manually run "Log file cleanup"
5. See that the logs are exactly the same as they were before.

**Expected behavior**
Logs should be deleted as intended.

**System (please complete the following information):**
 - OS:  x64 official Docker
 - Browser: Chrome
 - Jellyfin Version: 10.4.2

**Additional context**
Logs folder is default:

Logs:
/config/log

Logs are being written, so the Docker must write access to that folder.

**Comment by excelite** [comment]
@therealmelee, the old emby log cleanup task explicitly excludes the .log logfiles and states that those are to be managed by semilog.

you can fix this by adding the following line to your /config/logging.json

`"retainedFileCountLimit": 3,`

below the "rollingInterval" entry:
`...
                                "rollingInterval": "Day",
                                "retainedFileCountLimit": 5,
...`
