### ISSUE TITLE
Windows Install Namespace Error

### ISSUE THREAD

**Issue by trumblejoe** [jellyfin/jellyfin#206]
It was necessary to add system.management.automation to one of the variables within the windows install .ps1 script. It's late so the specific variable name escapes me at the moment. Also, side note, it was attempting to write to my Documents & Settings folder for some purpose, but that error'd out (despite having admin permissions and having the Jellyfin folder in C: ).

**Comment by JustAMan** [comment]
@LogicalPhallacy could you please have a look?

**Comment by LogicalPhallacy** [comment]
What windows version are you on @trumblejoe ?

**Comment by trumblejoe** [comment]
Windows 7 SP1. The install did complete and I've watched something successfully.

**Comment by anthonylavado** [comment]
@trumblejoe/@logicalphallacy Do we still need this around?

**Comment by trumblejoe** [comment]
I ran it again at 10.2.0 and it was still an issue. The machine on in
question is running Windows 7.

**Comment by LogicalPhallacy** [comment]
What version of powershell is on the system? You can check this is
$PSVersionTable
