### ISSUE TITLE
Building Jellyfin on Ubuntu produces error The current .NET SDK does not support targeting .NET Standard 2.1.

### ISSUE THREAD

**Issue by cryptobank** [jellyfin/jellyfin#2061]
**Describe the bug**
Building on latest Ubuntu get loads of these errors - 

/dotnet-sdk/sdk/2.2.401/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(150,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Standard 2.1.  Either target .NET Standard 2.0 or lower, or use a version of the .NET SDK that supports .NET Standard 2.1. [/jellyfin/Emby.Drawing/Emby.Drawing.csproj]

**To Reproduce**
./build debian-package-x64

**Comment by cvium** [comment]
You need to install netcore 3.0 SDK.

**Comment by cryptobank** [comment]
> You need to install netcore 3.0 SDK.

nope, build still downloads dotnet 2.2 and ends in error.

**Comment by cryptobank** [comment]
Is there anyway to build jellyfin without having to re-download all the packages? It makes it difficult to write patches as each build takes like 10 minutes.

**Comment by JustAMan** [comment]
Simple "dotnet publish" in the root of server should do it (but to make an installable package from that you'd need more work).
