### ISSUE TITLE
LIVE tv epg CHANNEL ICON BUG

### ISSUE THREAD

**Issue by kokorono1** [jellyfin/jellyfin#2063]
**Describe the bug**
If there is no channel icon in TVHEADEND, a dummy image is created in Jellyfin Live TV GUIDE so the channel name is not visible.

**To Reproduce**

1. Go to 'LIVE TV -> guide'
2. Click on 'channel icon'

**Expected behavior**

**Screenshots**

![캡처1](https://user-images.githubusercontent.com/58217840/69634133-f764bd00-1094-11ea-98b5-b4b15cf92169.JPG)
![캡처2](https://user-images.githubusercontent.com/58217840/69634136-f7fd5380-1094-11ea-8af7-c0ea6d5d1308.JPG)

**System (please complete the following information):**
 - OS: Docker
 - Browser: Chrome
 - Jellyfin Version: 10.4.12
 - Reverse proxy: no
 - plugin: tvheadend

**Comment by JustAMan** [comment]
Can you open browser "developer console" (F12 if Chrome) and see if there are any errors there?

**Comment by Artiume** [comment]
I experience the same issue. I checked the console, but I couldn't find any red herrings. Only thing to add is that I noticed is that there's a blank image being saved to the channel. I deleted the blank image and returned to the channel. The Image Location now looked normal (with no missing icon warning), just missing an image.

**Comment by Artiume** [comment]
Shoo bot

**Comment by Shadowghost** [comment]
Should be fixed by https://github.com/jellyfin/jellyfin/pull/5996
