### ISSUE TITLE
unnecessary transcodes and looped playback after playback ends

### ISSUE THREAD

**Issue by accountForIssues** [jellyfin/jellyfin#2067]
**What happens ?**

Almost always before an episode ends, about 30-45 secs before, there has been a noticeable skip for a second or less around when the "Next Up" message pops up. Usually, I just ignored it and started the next episode or stopped the playback.

When I let it timeout to zero, I noticed a few things;

- After it goes down to zero, instead of starting the next episode, it replays the last 30-45 seconds (right after the "skip" happened) without any sound.
OR
- It does the same thing as above but it's sped up.
OR
- It does the same thing as number 1 but in a slightly different way: Let's say it replays the last 30 seconds and then, it replays the last 20 seconds and then the last 10 seconds and so on.. (I haven't calculated the difference between the loops but it's something like that)

**Logs**

I took a look at the logs and I noticed that there are multiple ffmpeg directstream logs for each episode. (I am assuming it's not by design and that the file is demuxed/transcoded entirely upon start of playback as 01x02 and 01x03 played back fine with no skips nor loops)

eg. according to the logs;

when the playback starts, the file is demuxed/transcoded into 0 to 202 ts files. I verified that the xxx202.ts is the last part of the file.
and then I assume during that "skip", more .ts files are created.
After the 202 ts is played, there are 203 - 222 ts files.
Once that is done, there are 223 - 228 ts files.
Once that is done there is 229.ts and
then finally 230.ts

Once all that is over, the next episode is played normally.

So the files 203 to 230 ts files are completely unnecessary and I have no idea why it's happening.

I have included all the ffmpeg-directstream logs (sorted by episode) and the main jellyfin.log.
[jellyfin_logs.zip](https://github.com/jellyfin/jellyfin/files/3899641/jellyfin_logs.zip)

Any ideas ?

**System (please complete the following information):**
 - OS: Raspbian 10 on Raspberry Pi 4

 - Jellyfin Version: 10.4.2

**Comment by accountForIssues** [comment]
I have created a debug log for 2 episodes and I just realized that for the second episode, once the actual episode is finished, it replayed the last several minutes so it's not just 30-45 seconds as I previously said but seems to be random.

It looks like once the actual episode ends. the transcode starts
`Starting transcoding because currentTranscodingIndex=null`
and then it repeats at least one more time once that transcode stream is played until
`PingTranscodingJob PlaySessionId="-------------" isUsedPaused: True`
and then the next episode is loaded.

This
`PingTranscodingJob PlaySessionId="-------------" isUsedPaused: True`
is not being called the first time an episode ends and the transcoding job seems to start during the normal playback which might be causing the "skip" that I mentioned.

Debug log and media info of the episodes fully played
[jellyfin-debug.zip](https://github.com/jellyfin/jellyfin/files/3901685/jellyfin-debug.zip)

**Comment by JustAMan** [comment]
What client are you using, some browser? If so, gathering web console log (or even better log and replay file) would be awesome. For Chrome see https://developers.google.com/web/tools/chrome-devtools/network/reference#save-as-har

**Comment by accountForIssues** [comment]
I thought I mentioned it in the OP but I guess I didn't.

The client is an LG OLED TV so I don't know if it's possible to get those logs :(

The TV is the only device in my home that can direct stream those files so I can't test on other devices.
