### ISSUE TITLE
logfile size can increase until the system runs out of memory

### ISSUE THREAD

**Issue by excelite** [jellyfin/jellyfin#2069]
**Describe the bug**
The Logfiles are rotated only on a daily basis, there is currently no limit of the implemented/configured.

This can lead to a logfile larger that the available memory of the system and therefore reuslt in undefined/faulty behavior.

**To Reproduce**

1. log a large amount of messages in a single day

**Expected behavior**
Jellyfin should trigger a kogrotation.

**Logs**
not applicable

**Screenshots**
not applicable

**System (please complete the following information):**
 - OS: any
 - Browser: not applicable
 - Jellyfin Version: 10.4.2
 - Reverse proxy: not applicable

**Additional context**
The logging module uses the serilog package and the async sink. Later has the option to add a filesize based trigger for logrotation that can be configured in logging.json

**Comment by JustAMan** [comment]
Could you please clarify what this issue is about, setting a saner default or providing docs guidance on setting it?

**Comment by excelite** [comment]
Yes, I would add a default limit of about 100MB, since it seems that there are a couple people running jellyfin on raspberries.

My personal logfiles sizes range in  vales from 10 to 30 MB for daily usage of my family (4 users), therefore it should be a suitable size.

This issue actually was just for myself, since I stumbled across the proper settings, I'm about to create a PR for this and #2056
