### ISSUE TITLE
Transcoding temp cleanup job not running on schedule

### ISSUE THREAD

**Issue by Numline1** [jellyfin/jellyfin#2075]
**Describe the bug**
The "Transcoding temp cleanup" job ignores its triggers. Other jobs run fine, this one just says "Last ran 2 months ago" unless its manually triggered. The manual run works just fine.

**To Reproduce**
1. Set "Transcoding temp cleanup" to run every 15 minutes
![image](https://user-images.githubusercontent.com/12192684/69883280-527ff500-12cb-11ea-9b99-ae0c5d55e328.png)
2. Wait... :)

**Expected behavior**
The job should run every 15 minutes. This same issue happens when you set the job to run every 24 hours and so on, the setting is completly ignored.

**Logs**
No logs available, manual run throws no errors, scheduled run never runs.

**Screenshots**
![image](https://user-images.githubusercontent.com/12192684/69883321-878c4780-12cb-11ea-891c-786c9abcf0a3.png)

**System (please complete the following information):**
 - OS: Docker
 - Browser: Firefox
 - Jellyfin Version: 10.4.2
 - Reverse proxy: Traefik

Thanks for having a look at this issue ;)

**Comment by whalehub** [comment]
I'm experiencing this issue as well, but it appears to be a purely visual bug. I have my task set to run at midnight every day and while the GUI continues to say that the last time it ran was several days ago, the `transcoding-temp` folder is actually being cleaned up at midnight every day.

**Comment by Numline1** [comment]
I've just checked and you might be right @whalehub

I've ran out of 50GB of storage assigned to my JF VM several times, but I guess I've been binging too many tv sho... err, I mean, Linux ISO shows.

**Comment by anthonylavado** [comment]
I have confirmed that scheduling this does not work. Will need to investigate.

**Comment by Numline1** [comment]
@anthonylavado I've just checked the transcoding-temp folder and it seems my old files were actually deleted, despite the job saying it hasn't been executed in several weeks. It might just be a visual bug.

**Comment by anthonylavado** [comment]
There’s a few things to note:
* If playback stops cleanly, then the transcoding temp file for that session should automatically get deleted
* upon restarting JF, the transcoding temp gets cleared

It could just be that your system’s in good shape :-)

**Comment by Numline1** [comment]
Oh okay, oops, didn't know about that first part. I'll try to fail some transcodings just to double check, but I'm sure you're probably right :)

**Comment by ac2323** [comment]
I'm having this issue. The scheduled task does not run on schedule, but does work manually.

**Comment by angelfor3v3r** [comment]
Same here. The task never runs, but on app restart it's fine. As a temporary solution I made my Jellyfin restart every 2 days. I also run Jellyfin's transcoding directory on a ramdisk so it's really bad when files linger for 4-5+ days.
