### ISSUE TITLE
Block items with tags doesn't remove show from Next Up

### ISSUE THREAD

**Issue by SenorSmartyPants** [jellyfin/jellyfin#2079]
**Describe the bug**

If a user as a tag set in "Block items with tags" on a tv series, the series is hidden from view in Latest and the tv library view, but not in Next Up.

**To Reproduce**

Edit user to add tag "hidden" to Block Items with tags.
go to series that exists in Next Up view for previous user, edit metadata, add tag "hidden" to series.

**Expected behavior**

Episodes should be hidden from view in Next Up if the series or season they are from is tagged to be hidden from a user.

**System (please complete the following information):**
 - OS: Docker,
 - Browser: Chrome
 - Jellyfin Version: 10.4.1
 - Reverse proxy: no

**Comment by SenorSmartyPants** [comment]
After some more testing, it seems this works fine. Shows just don't disappear until Next Up is updated by watching an episode of something else.

**Comment by JustAMan** [comment]
I still feel it's a bug, hiding should be applied immediately...

**Comment by muldermatthijs** [comment]
I agree, when I block content for a specific user, it shouldn't show up in "Next Up". I saw this issue today.

**Comment by virgil9306** [comment]
This is still an issue

**Comment by btrfs-d** [comment]
This is still an issue.

**Comment by C0rn3j** [comment]
Dupe of https://github.com/jellyfin/jellyfin/issues/3559, fixed in master.
