### ISSUE TITLE
Creating a tag with a single quote in the name causes SQL crashes

### ISSUE THREAD

**Issue by SenorSmartyPants** [jellyfin/jellyfin#2080]
**Describe the bug**

This is a bug as old as time. 

**To Reproduce**

Edit series metadata, add tag "Don't Show"
Edit user, block items with tag, add tag "Don't Show"
watch explosions.

**Expected behavior**

no crashes

**Logs**

**System (please complete the following information):**
 - OS: Docker
 - Browser: Chrome
 - Jellyfin Version: 10.4.1
 - Reverse proxy: no

**Comment by dkanada** [comment]
I added the confirmed label because we need to keep this open until it gets resolved. As mentioned previously, the server should never crash from a client request.

**Comment by dkanada** [comment]
Might as well mention that adding devices with names that include special characters will also crash the server.

**Comment by JustAMan** [comment]
This is also most likely a security issue as (I guess) it fails due to SQL injection.
