### ISSUE TITLE
Resuming Audio

### ISSUE THREAD

**Issue by ovnx** [jellyfin/jellyfin#2084]
Resuming audio should be available, particularly for things like audio books. Menu in admin interface only shows "Resume Video" settings.

**Comment by JustAMan** [comment]
This looks like a part of https://features.jellyfin.org/posts/243/audiobook-support

**Comment by dkanada** [comment]
This has been implemented for AudioBook items, which are available when using the book library.

**Comment by LeifAndersen** [comment]
Given that @Tolriq is unwilling to add syncing with book libraries in the Yatse app[1], would it be possible to enable this on music libraries as well as book ones?

[1]: https://community.yatse.tv/t/jellyfin-audiobooks-not-recognized-as-music/3180/5
