### ISSUE TITLE
DLNA not discoverable when using self signed certificate

### ISSUE THREAD

**Issue by brianclinkenbeard** [jellyfin/jellyfin#2085]
**Describe the bug**
DLNA is not discoverable, at least on iOS applications, when using a self-signed cert for SSL. On "Preferred, but not required" mode with a self-signed certificate, all apps tested will not be able to discover Jellyfin. 

Switching the secure connection mode to "Disabled" or removing the cert location line from `system.xml` and then restarting will cause Jellyfin to be discovered again.

**To Reproduce**

1. Create self-signed cert
2. Provide p12 cert path
3. Restart

**System (please complete the following information):**
 - Jellyfin Version: 10.4.2
 - Reverse proxy: no

**Comment by anthonylavado** [comment]
Is the self-signed cert installed and trusted on your device? Usually these aren’t, which could be why it fails.

**Comment by brianclinkenbeard** [comment]
Nope. But I would imagine this to be unexpected behavior for a lot of users since they will use a self-signed cert for one reason or another, trust it on their computer or through their browser, and not think of why DLNA does not work for their other devices.

Also, even with the connection mode on "Preferred, but not required", there is no way to discover the non-SSL DLNA server. There isn't any other option than disabling self-signed SSL since I believe for many devices, there is no way to trust certs (for example, I don't think this is possible for gaming consoles).

Perhaps there is someway for the DLNA to fallback on non-SSL for this option? Or, at least, maybe a note can be given when setting the SSL certificate about how self-signed certs can make DLNA not work/certificates need to be trusted.

**Comment by army1349** [comment]
I don't think it has anything to do with self signed certificate.
I think DLNA does work only with Secure connection mode: Disabled and that is the main bug.

**Comment by PrplHaz4** [comment]
> I don't think it has anything to do with self signed certificate.
> I think DLNA does work only with Secure connection mode: Disabled and that is the main bug.

I think this is closer to the answer. The server does not respond to clients with the right port for anything but `Disabled`.  More info on ssl/DLNA behavior in #2568
