### ISSUE TITLE
Audiobooks: Combining Single-File CD rips with One-File-Per-Chapter based folders breaks sorting

### ISSUE THREAD

**Issue by McGlear** [jellyfin/jellyfin#2087]
Audiobook series aren't sorted correctly in the jellyfin library view when some of the episodes are single files and others are multiple files (one per chapter) in an episode folder.

Audiobooks
--John Sinclair
----(100) Episode 100
------Chapter1.mp3
------Chapter2.mp3
----(104) Episode 104
------Episode104.mp3
----(113) Episode 113 
------Chapter1.mp3
------Chapter2.mp3

This folder structure results in the following jellyfin library order:

(100) Episode 100 (Folder)
(113) Episode 113 (Folder)
(104) Episode 104

![20191201_jellyfin_book_sorting](https://user-images.githubusercontent.com/8162769/69911997-c3d2bb80-1423-11ea-81ab-4cfea4e9e1e9.PNG)

Expected behaviour:
(100) Episode 100 (Folder)
(104) Episode 104
(113) Episode 114 (Folder)

This problem is regarded "not a bug, but a feature" [within emby](https://emby.media/community/index.php?/topic/77201-question-single-files-in-folders-and-sub-folders-not-scanneddisplayed-correctly/):
"over the years this is what our audience has wanted to avoid the extra click, so that's why we do that."

I'd nonetheless like an option to switch back to the correctly sorted library view, even if it comes at the expense of an extra click - cherry on top: Let the user decide on a per-library-basis?

EDIT:
As it wasn't clear from my first post: Not only do the single files end up at the bottom of the list, they also don't get sorted based on their folder _at all_. In the above image, you can see that they all get sorted in seemingly random order (and what you can not see: They get sorted based on their individual file name, instead of the name of their parent folder - when organizing my library, I took good care of the folder structure, but didn't change the file names, so some of them are labeled 01_name.mp3 - as that was a standard setting when ripping CDs as a single track - while others are named based on their episode number instead).

**Comment by JustAMan** [comment]
This feels like a feature request, which we collect at https://features.jellyfin.org/

**Comment by McGlear** [comment]
Maybe I misunderstand what the Sort By Folder Option is supposed to accomplish, then. Currently, Folder names are completely ignored for single files. Note that in the above screenshot, the singlets are not only appearing at the end of the library (and changing that might be the topic of a feature request), but they are also in the wrong order, because they get sorted based on file name, rather than folder name.
Side-note: Sorting my library by "Name" currently yields the exact same result: Singlets are again sorted by file(!) name, rather than metadata. Is _that_ intended?

**Comment by JustAMan** [comment]
Oh, I think I misread what you wanted to do, sorry about that. Yeah, it indeed does look like a bug.
