### ISSUE TITLE
Can't Discover Jellyfin Server (Ubuntu)

### ISSUE THREAD

**Issue by pc-v2** [jellyfin/jellyfin#2091]
**Describe the bug**
i can't log into my server via android (jellyfin app & yatse)

**To Reproduce**
1. Open Jellyfin Mobile App
2. Search Server
4. Unavailable

**Expected behavior**
Jellyfin mobile connected to server

**System (please complete the following information):**
 - OS: POP_OS - Browser: [Firefox]
 - Jellyfin Version: [e.g. 10.4.2]
 - Reverse proxy: [no]

**Comment by anthonylavado** [comment]
@pc-v2 Please try adding “/Jellyfin” to the end of your server address.

See the release notes for 10.4.1 if you’d like to change this: https://github.com/jellyfin/jellyfin/releases/tag/v10.4.1
