### ISSUE TITLE
Episodes not listing

### ISSUE THREAD

**Issue by gxgani** [jellyfin/jellyfin#2101]
**Describe the bug**
When browsing a TV Show, episodes don't load/list for some or take long time to show up. If you look at the following screen recording, you'll notice that some show contain over 400+ episodes and the listing works for one and not for the latter.

**Screen-recording**
https://streamable.com/uejwk

**System (please complete the following information):**
 - OS: CentOS Linux 7 (Core) x86_64 
 - Browser: Chrome/FireFox
 - Jellyfin Version: 10.4.2-1
 - Reverse proxy: nginx
 - CPU: Intel i3-2130 (4) @ 3.400GHz
 - Kernel: 3.10.0-1062.7.1.el7.x86_64
 - Memory: 8GB

**Additional context**
Is this hardware bottleneck?

**Comment by JustAMan** [comment]
@dkanada does this look like a frontend bug to you?

**Comment by gxgani** [comment]
Edited context: In the above the TV show, some shows contain over 400+ episodes, while some lists, some take time and the last one does not list at all but I am able to play the default episode.

Note: I am performing these actions after jellyfin has completed scanning library. I've re-uploaded the screen recording.

**Comment by JustAMan** [comment]
I wonder if this is related to https://github.com/jellyfin/jellyfin-web/issues/602
