### ISSUE TITLE
[Feature request] Multi Version Episodes

### ISSUE THREAD

**Issue by ashtez** [jellyfin/jellyfin#2112]
Hello,

With TV Shows, I put each episode in its own folder, and was wondering if you could allow multi-version. It already exists for movies ([see this](https://github.com/MediaBrowser/Wiki/wiki/Movie-naming#multi-version-movies)). 

Thanks

**Comment by Z3ROGRAV1TYx** [comment]
https://features.jellyfin.org/posts/198/handle-movies-with-multiple-split-files-as-one-item

https://features.jellyfin.org/posts/251/multiple-versions-drop-down-on-tv-series

https://features.jellyfin.org/posts/174/better-handling-of-movie-versions-in-multiple-directories

**Comment by ashtez** [comment]
Oh I am so sorry.

**Comment by ashtez** [comment]
It's possible ! 

Here is the how to : 

Hi there!
So I've looked in to this a bit further. Turns out this is available, it just doesn't happen automatically.

To do this in the meanwhile, follow these steps:

    Click into the detail page for an episode that has multiple versions
    Long click on the episode in the "More from Season..." section
    Click boxes will appear, select all versions of the episode
    At the top right, use the "..." menu and choose "Group Versions"

The changes won't show up immediately, you'd have to go back a page for them to appear.

We'll look into making this automatic!

Copied from [Jellyfin Project features request](https://features.jellyfin.org/posts/251/multiple-versions-drop-down-on-tv-series)

**Comment by ashtez** [comment]
Well, I don't know if this is usefull, but Anthony Lavado list of instructions does this :

Call
`function combineVersions(apiClient, selection)`
in Jellyfin Web, which triggers
`public void Post(MergeVersions request)`
in Jellyfin server.

**Comment by manzajaro** [comment]
Hi!

How is this topic going? Will be implemented?

I have this problem,

El pionero S01E01 - 1080.strm
El pionero S01E01 - 720.strm
El pionero S01E01 - 420.strm

Jellyfin doesn't group them automatically :(

**Comment by Artiume** [comment]
@manzajaro  What version are you on? the strm files should've merged

**Comment by manzajaro** [comment]
Hi @Artiume , thanks for your response 

I am in version 10.5.5

<img width="959" alt="Captura" src="https://user-images.githubusercontent.com/6926926/84058224-31563a80-a9b9-11ea-836a-3858935ac776.PNG">

**Comment by ashtez** [comment]
Any news on this ?

**Comment by crobibero** [comment]
This is on hold until the librarydb is migrated to efcore

**Comment by cvium** [comment]
As part of issue cleanup I am closing feature requests. It seems this covers it https://features.jellyfin.org/posts/251/multiple-versions-drop-down-on-tv-series
