### ISSUE TITLE
[bug] [API] /Items API query TotalRecordCount off by one

### ISSUE THREAD

**Issue by chaosinnovator** [jellyfin/jellyfin#2116]
**Describe the bug**
The Items API query's `TotalRecordCount` is off by one (too low). Example: 50 items in library, `TotalRecordCount` = 49.

**To Reproduce**
1. Go to a library item list (easiest to see with a small library <100 items)
2. Open network console and check the latest "Items?..." request, response preview

**Expected behavior**
`TotalRecordCount` = `ActualTotalRecords`

**Screenshot**
![image](https://user-images.githubusercontent.com/36967580/70379909-40fca580-18e8-11ea-8d36-1ed7ceb4cbee.png)

**Comment by JustAMan** [comment]
I feel that it's somehow related to https://github.com/jellyfin/jellyfin/issues/1370
