### ISSUE TITLE
Can't install jellyfin as a service on Windows 10

### ISSUE THREAD

**Issue by CutterXYZ** [jellyfin/jellyfin#2119]
**Describe the bug**
The installer stops with the following error when Jellyfin 10.4.3 is installed as a service on Win10: "Could not configure the Jellyfin Server service account".

**To Reproduce**
1. Right-click on the installer, click "Run as administrator..."
2. Select "Install as a service". 
3. Keep "Install server service" checked, click Next. Keep the default install folder, data folder and network account option. Click next to install.

**Expected behavior**
Jellyfin is correctly installed.

**Logs**
N/A

**Screenshots**
![Screenshot of the installer after error](https://i.imgur.com/4rf3xDf.png)

**System (please complete the following information):**
 - OS: Windows 10 64-bit
 - Browser: N/A
 - Jellyfin Version: 10.4.3
 - Installed Plugins: none
 - Reverse proxy: no

**Additional context**
A previous "basic" (non-service) installation of Jellyfin was previously removed without deleting the data folder.

**Comment by anthonylavado** [comment]
@CutterXYZ Hi there. This is a currently known issue for Windows installs that don’t have English as the main language.

To fix this in the meanwhile, go to the services list (services.msc), right click on JellyfinServer, and choose Properties.

There should be a tab for log on (Log On As in the English version), where you can choose an account. Set it to the Network Service account (whatever the equivalent will be in your language pack).

You could also just leave it as the Local System account, which is the old behaviour, but that isn’t recommended for other reasons.

**Comment by CutterXYZ** [comment]
Thanks. After I set the service's account to Network Service, the Jellyfin service doesn't start anymore. Here is the event created in Windows' logs after an unsuccessful service startup:

> The Jellyfin Server service terminated with the following service-specific error: 
> The system cannot join or substitute a drive to or for a directory on the same drive.

If I set the account to Local System account the service starts properly again.

**Comment by anthonylavado** [comment]
It’s possible it already made the configuration under Local System, and Network Service can’t read it now.

You can use Local System, just be safe and don’t install plugins you don’t trust :-)

**Comment by CutterXYZ** [comment]
Hi,
I'm still getting the error on installation of 1.6.0. Any chance for this bug to be fixed please :) ?

Thanks.

**Comment by anthonylavado** [comment]
@CutterXYZ I'm adding it to my list at https://github.com/jellyfin/jellyfin-server-windows/issues/29, but to confirm - it still works for you as Local System, right?

**Comment by CutterXYZ** [comment]
Thanks. It works as Local System yes, but perhaps with more user rights than necessary.

**Comment by vitaprimo** [comment]
I'm getting the same error with Windows in English, no lang packs; I'm using a gMSA to run Jellyfin so it gets automatic privileges to run as a service and to access network shares.

I too had Jellyfin in tray before, _but_, it was the same data folder from Jellyfin that originally was installed as a service--I switched because the dedicated service account would lose the _run as a service_ right randomly because...Windows.

**Comment by LillyWho** [comment]
> @CutterXYZ I'm adding it to my list at [jellyfin/jellyfin-server-windows#29](https://github.com/jellyfin/jellyfin-server-windows/issues/29), but to confirm - it still works for you as Local System, right?

The problem still persists today. However, I just fixed it by manually adding the Network Service account to the permissions record of the Jellyfin folder, as well as all library folders. The service then can successfully start under that account. The installer would have to do the same thing automatically, and it would work.

**Comment by LillyWho** [comment]
Can't get any logs, because I don't know where Jellyfin would have its data directory under the Network Service account.
