### ISSUE TITLE
Not working on windows

### ISSUE THREAD

**Issue by chintan9** [jellyfin/jellyfin#2121]
I try to upgrade to 10.4.3 from 10.3.7 it did not work at all. 

How to reset jellyfin to update?

**Comment by charithjayasanka** [comment]
Faced the same issue here

**Comment by anthonylavado** [comment]
Hi there 👋 
Sorry for the delay. Could you let us know what error you're seeing? Is Jellyfin not running?

If you were using an older version before 10.4.3, please let us know:
- What version you were using (e.g. 10.3.7)
- How it was installed/run (e.g. Set up the service, or just running the .exe)

**Comment by chintan9** [comment]
used as set up service and v10.3.7 on windows10

**Comment by charithjayasanka** [comment]
I switched to using docker. Now it's working fine. But the issue might persist with windows.

**Comment by chintan9** [comment]
I do not want use docker.

**Comment by telans** [comment]
You still haven't even described what is going on other than "it did not work". No one here is telepathic, and chances are it is spitting out some logs somewhere that you haven't been bothered to look for

**Comment by chintan9** [comment]
@telans I will put all logs which in two days.

**Comment by chintan9** [comment]
@telans  It working right now. Thanks for support. Sorry for delay.

I removed everything from jellyfin related files and registry.  After I reboot machine and it works now. 

I also found another copy jellyfin running under roaming folder. 

Can we use this kind issue template https://github.com/stevemao/github-issue-templates/blob/master/conversational/ISSUE_TEMPLATE.md  for this project ?
