### ISSUE TITLE
Bad Norwegian translation

### ISSUE THREAD

**Issue by rkarlsba** [jellyfin/jellyfin#2124]
**Describe the bug**
The Norwegian translation of this software is extremely bad

**To Reproduce**
Select Norwegian language

**Expected behavior**
A somewhat clear and concise language is printed

**Logs**
None

**Screenshots**
Not necessary

**System (please complete the following information):**
Irrelevant

**Additional context**
I would like to help fixing the Norwegian translation, be it Bokmål or Nynorsk. Where can I start out?

**Comment by chaosinnovator** [comment]
Maybe start at the [Weblate](https://translate.jellyfin.org/projects/jellyfin/jellyfin-core) instance?

**Comment by dkanada** [comment]
Most of the strings would be found in the [web](https://translate.jellyfin.org/projects/jellyfin/jellyfin-web/) translations, but we also have a few other clients added there as well.

**Comment by esmorun** [comment]
I've been working on improvements to the norwegian translation, but there are some strings that doesn't seem to be available for translation.

When playing a movie and viewing playback info, there's stil a lot of english in there:
Playback Info
Avspiller: Html Video Player
Avspillingsmetode: Transcode
Protocol: https
Stream type: HLS
Video Info
Player dimensions: 1850x912
Video resolution: 1920x816
Transcoding Info
Videokodek: H264
Lydkodek: MP3
Bithastighet: 11.3 Mbps
Fremgang for omkoding: 1.0%
Original Media Info
Kontainer: mkv
Størrelse: 444.6 MiB
Bithastighet: 4.0 Mbps
Videokodek: HEVC Main 10
Bithastighet på video: 2.7 Mbps
Lydkodek: AAC LC
Bithastighet for lyd: 320 kbps
Lydkanaler: 6
Samplingsfrekvens for lyd: 48000 Hz

Also, on the library settings page where you set up metadata sources, the following english words aren't translated:
Series
Season
Episode

Additionally, when I browse a library and sort it by genre, the genres are in english. Adventure, Comedy, Drama etc.

**Comment by dkanada** [comment]
The genres are in English because those are probably picked up by the metadata provider, which may or may not respect your chosen language based on what languages the provider supports.

Regarding the rest of the strings, we have a lot of duplicate strings in the web client right now. I have spent some time cleaning this up (pretty sure there were originally 600 more strings last year before the fork) but there's still a lot of work left. You may have encountered a duplicate string that hasn't been translated yet.

**Comment by JustAMan** [comment]
Should we close this issue? It doesn't feel measureable or actionable to me (how to measure if translation is "good"), but rather requires string-by-string work in our weblate.

**Comment by esmorun** [comment]
> Should we close this issue? It doesn't feel measureable or actionable to me (how to measure if translation is "good"), but rather requires string-by-string work in our weblate.

I've worked my way through all the norwegian strings and made lots of improvements where I felt they were needed, the translation is good in the latest nightly build so I think the bug can be closed. :)
