### ISSUE TITLE
Unexpected behaviour with Disc Numbers in audio files and folders

### ISSUE THREAD

**Issue by Mcewan71** [jellyfin/jellyfin#2128]
'Disc 0' and 'Disc 1' appearing for some single disc albums in music library (Windows 10.4.3). Verified not a tagging issue by going through tag details of affected files and folders. 

Going through details of affected files indicates no clear reproducible issue. Bug?

**Comment by JustAMan** [comment]
Care to post a little bit more info about problematic files? Also we have a template which we expected to be followed...
