### ISSUE TITLE
Failure to serve content to Kodi

### ISSUE THREAD

**Issue by i418c** [jellyfin/jellyfin#2129]
**Describe the bug**
Trying to play any file through Kodi results in the server throwing an exception and responding with 500.

**To Reproduce**
1. Fresh Jellyfin/Kodi installs
2. Set up Kodi's Jellyfin plugin in addon mode
3. Sync
4. Try to play any video file

**Expected behavior**
The video to play

**Logs**
[kodi.log](https://github.com/jellyfin/jellyfin/files/3937392/kodi.log)
[jellyfin.log](https://github.com/jellyfin/jellyfin/files/3937393/jellyfin.log)

**System (please complete the following information):**
 - Server OS: Ubuntu Server 18.04
 - Jellyfin Version: 10.4.3
 - Installed Plugins: Kodi Sync
 - Reverse proxy: no

 - Client OS: Manjaro on kernel 5.3.12-1
 - Kodi Version: 18.4
 - Kodi Plugin Version: 0.3.6

**Additional context**
The only other issue I found with this sort of error message was https://github.com/jellyfin/jellyfin/issues/1611 but that specifically relates to forced transcodes.  Transcoding is not a prerequisite for this issue to appear as shown by the logs.

**Comment by Dec-F** [comment]
v10.4.2 also has this problem. Is normal in v10.4.0

**Comment by JustAMan** [comment]
@mcarlton00 @TrueTechy @oddstr13 anything rings a bell for you?

**Comment by mcarlton00** [comment]
@Dec-F have you tried the kodi addon version 0.4.0?  I notice your logs are still mentioning trying to reach the server at `/emby` endpoints.  This is been depreciated, but should still be working.

The other question is do you have a baseurl set in your server?  Easy way to check is when you load the home page, do you get `server_url/jellyfin/path` or just `server_url/path` in the URL bar?

**Comment by i418c** [comment]
@mcarlton00 
I've tried with 0.4.0 and the baseurl set to /jellyfin with the same result.  The log messages that were spat out are the same as before.

**Comment by mcarlton00** [comment]
I'm still not able to replicate this.  I've tried every Kodi version from 18.3 through the current 19 alpha with both addon 0.4.0 and the current master, and with and without a baseurl set.  No errors in the Jellyfin logs, no errors in the Kodi logs except for the overzealous logging that's getting cleaned up, and playback starts fine.

The only thing I haven't tested at this point is Native playback mode because I don't have a good way of doing so.  Which playback mode do you have setup in your Kodi install, Native or Add-on?  It can be found at Add-Ons -> Jellyfin -> Settings -> Sync -> Playback Mode

**Comment by i418c** [comment]
I've retried again with Jellyfin 10.5.0 and Kodi plugin 0.5.1 with the same results.
@mcarlton00 The playback mode is addon per the steps to reproduce in the initial report.

**Comment by mcarlton00** [comment]
Can you pull fresh logs please?  I may have found the issue but it's be helpful to check it with the current version.  We've been having some issue with translations and unicode characters, and I see that referenced in your 0.3.6 logs, so I want to verify that's still happening.  Also, what language is your Kodi set to?  Replicating that will help with my debugging.

**Comment by i418c** [comment]
Here are some new logs.  Kodi is set to English with character set 'Default.'
[jellyfin.log](https://github.com/jellyfin/jellyfin/files/4366121/jellyfin.log)
[kodi.log](https://github.com/jellyfin/jellyfin/files/4366122/kodi.log)

**Comment by oddstr13** [comment]
This issue is most likely fixed by #3585, which is in the Jellyfin 10.6.0 release

**Comment by i418c** [comment]
I can confirm this is fixed.
