### ISSUE TITLE
Can't delete playlist item from api

### ISSUE THREAD

**Issue by mcarlton00** [jellyfin/jellyfin#2130]
**Describe the bug**
It's possible to add items to a playlist using the api without any issues.

When deleting an item the server returns a 204, but the item isn't removed from the playlist.

**To Reproduce**
Python:
```
r = requests.delete('http://192.168.0.200:8096/Playlists/$PLAYLISTID/Items?UserId=$USERID&EntryIds=$ITEMID', headers=headers_data)
```

**Expected behavior**
$ITEMID to be deleted from the playlist

**Logs**
With debug logging enabled, the only output is
```
[01:45:35] [DBG] Saving /config/data/playlists/Testlist [playlist] to Emby Xml.
[01:45:35] [DBG] Saving /config/data/playlists/Testlist [playlist] to Emby Xml.
```

**System (please complete the following information):**
 - OS: Docker
 - Browser: N/A
 - Jellyfin Version: 10.4.3
 - Installed Plugins: N/A
 - Reverse proxy: N/A

**Additional context**
Oddly enough, it appears that the web UI uses the same exact api call and that works properly

**Comment by dkanada** [comment]
Deleting the entire playlist also doesn't work as far as I can tell.

**Comment by mcarlton00** [comment]
I think that used to work, but I haven't tried in a while.  The issue at the time (2-3 months ago) was that it would delete the playlist from the system, but not remove the files from the disk.  So during the next library scan the deleted playlist would come back.

**Comment by sfescape** [comment]
As of 10.8.10 this is not working. The related item (delete playlist) does work, but trying to delete an item in a playlist returns 204 but does not actualyl remove the item from the playlist.
