### ISSUE TITLE
API - Audio files aren't returned in 'Latest' api call

### ISSUE THREAD

**Issue by mcarlton00** [jellyfin/jellyfin#2131]
**Describe the bug**
When calling `/Items/Latest` in the api, it seems to be unable to return Audio files directly.  I've only been able to pull MusicAlbum types

**To Reproduce**
Python:
```
r = requests.get(f'{api_url}/Users/{user_id}/Items/Latest?'
                 f'IncludeItemTypes=Audio&ParentId={library_id}', headers=headers_data)
```
Where `library_id` is a Music library

**Expected behavior**
Be able to pull recent tracks, not just albums

**System (please complete the following information):**
 - OS: Docker
 - Jellyfin Version: 10.4.3

**Comment by mcarlton00** [comment]
Still present.  Probably more an enhancement than a bug

**Comment by Aanok** [comment]
You can pull recent tracks if you pass `groupitems=false`. Note this will mean you'll ONLY get individual items, so if you query for e.g. both episodes and seasons you'll get redundant information.
