### ISSUE TITLE
Add commit message guidelines

### ISSUE THREAD

**Issue by sauerj** [jellyfin/jellyfin#214]
The emby repository is full of bad commit messages. Mostly only a title is provided but **no** information **what** the commit changes and **why** these changes are made. References to issues the commit is fixing are missing to.

The latest commit to the jellyfin repository seems to follow the same puristic commit message style.

I know writing good commit messages takes some time but it will help make jellyfin a much better place than the emby repo is.
It will help contributors or code reviewers to understand what a commit is trying to do and why.

Please do not take this personally, I really do appreciate all your work on jellyfin, just want to make jellyfin better and much more open than emby will ever be.

**Comment by PrplHaz4** [comment]
I think these are good recs (per https://chris.beams.io/posts/git-commit/)

- Descriptive subject completing "if applied this commit will..." (required, < 50 chars)
- Use body for what/why vs how (optional, preferably 72 char width)
- Use last line for linking issues/PRs...etc (required where available)

More detail/guidelines available at the link, but I tried to pull out what I thought was most important.

**Comment by anthonylavado** [comment]
We've read the Chris Beams post and agree. We are working on this.

**Comment by sparky8251** [comment]
I'm willing to take a crack at writing up this wiki document if you'd like. At the very least, I can do most of the legwork so you guys don't have to spend as much time on it.

**Comment by JustAMan** [comment]
Feel free to!

**Comment by sauerj** [comment]
It is also recommended to split commits into logical pieces.
A commit which fixes an issue should not change other code than needed to fix the issue. Personally I think it should not even be in the same PR that a fix for a certain issue.

**Comment by anthonylavado** [comment]
We have this covered in https://jellyfin.readthedocs.io/en/latest/contributor-docs/contributing-code/#pull-request-guidelines
