### ISSUE TITLE
Scanning library crashing

### ISSUE THREAD

**Issue by kmnb** [jellyfin/jellyfin#2140]
**Describe the bug**

Scanning library can't finished because it's always crashing a d ends up with error "a task is cancelled"

**To Reproduce**

1. Go to Scheduled Task
2. Click on scan library or scan all library
3. Wait

Filtered Log example of all errors http://termbin.com/9if7

**Expected behavior**

Scan should finish

**Logs**

Filtered Log to show only errors
http://termbin.com/9if7

**System (please complete the following information):**
 - OS: Ubuntu

 - Jellyfin Version: 10.4.3

**Comment by telans** [comment]
I've also been having this. No reason given in debug logs. I managed to scan my full library after ~50 or so scans (timer for every 15 minutes), and since then it hasn't failed when just picking up an episode or two

**Comment by Bond-009** [comment]
Any stack traces?

**Comment by EvineDeng** [comment]
I have the same situation, so I have backtracked the version to 10.4.1.

**Comment by lopoki** [comment]
> Any stack traces?
https://defuse.ca/b/wwexaLxz
