### ISSUE TITLE
FanArt pic doesn't show

### ISSUE THREAD

**Issue by ryoii** [jellyfin/jellyfin#2145]
**Describe the bug**
FanArt picture doesn't show in the background. It works on version 10.4.2 but 10.4.3 doesn't.

**To Reproduce**

1. Go to home page on web
2. Click on any video to show detail
3. Can't see the backgroud picture

**Additional context**
Windows 10 x64
jellyfin version 10.4.3

**Comment by BlackSiO2** [comment]
I think you may be referring to the media backdrops?  Can you check to make sure that backdrops are still enabled?  To do that, click the user icon in the upper right, followed by selecting display and finally ensure that Backdrops is checked.

**Comment by ryoii** [comment]
> I think you may be referring to the media backdrops? Can you check to make sure that backdrops are still enabled? To do that, click the user icon in the upper right, followed by selecting display and finally ensure that Backdrops is checked.

Thanks, it works.

Previously it was set separately on the home page and the detail page, and the latter was always displayed, now it seems to be configured together
