### ISSUE TITLE
Wrong AppData path with NSSM

### ISSUE THREAD

**Issue by EffeF** [jellyfin/jellyfin#215]
When I manually launch `jellyfin.exe` the server data is saved in:
`C:\Users\username\AppData\Roaming\jellyfin\...`
Starting jellyfin as a service with NSSM:
`C:\WINDOWS\system32\config\systemprofile\AppData\Roaming\jellyfin\...`

Don't know if this is a problem with NSSM or jellyfin. At the moment I have been using Windows Task Scheduler.

**Comment by JustAMan** [comment]
What user name is used to launch Jellyfin as a service? If you set none then Windows uses LOCAL_SYSTEM by default, which user profile is exactly what you wrote.

**Comment by EffeF** [comment]
Thanks, I had not set up the user on NSSM. Now it works properly.

**Comment by JustAMan** [comment]
@LogicalPhallacy could you please provide some short guide on using your installer, so we can add that to Wiki?

**Comment by anthonylavado** [comment]
Gonna reopen to keep track of adding that to the Wiki
