### ISSUE TITLE
JellyFin for me 100% my wife Humm (iPhone)

### ISSUE THREAD

**Issue by waynerigley** [jellyfin/jellyfin#2157]
OK so i have JellyFin running on my server no issues, JellyFin on my Google Pixel, but my wife has a iPhone 6S and we could not find an app to support the JF, there are so many apps that suggest trials and such, but figured i would ask here first as you all would know best. Is there an app for the iPhone if not is using Chrome on the iPhone the best solution? thanks all in advance

**Comment by telans** [comment]
https://testflight.apple.com/join/TcFUEVEb
