### ISSUE TITLE
Unable to recognize some movies

### ISSUE THREAD

**Issue by thymbahutymba** [jellyfin/jellyfin#2166]
Some movies aren't recognized properly from the MovieDbProvider due to errors on the title parsing. Follows the list of the indicted movies:
```
The.Hunger.Games.ITA.ENG.AC3.BDRip.1080p.X265_ZMachine.mkv
Star.Wars.A.New.Hope.ITA.ENG.AC3.BDRip.1080p.X265_ZMachine.mkv
Star.Wars.Attack.of.the.Clones.ITA.ENG.AC3.BDRip.1080p.X265_ZMachine.mkv
Star.Wars.Return.of.the.Jedi.ITA.ENG.AC3.BDRip.1080p.X265_ZMachine.mkv
Star.Wars.The.Empire.Strikes.Back.ITA.ENG.AC3.BDRip.1080p.X265_ZMachine.mkv
Star.Wars.The.Phanom.Menace.ITA.ENG.AC3.BDRip.1080p.X265_ZMachine.mkv
Star.Wars.The.Revenge.of.the.Sith.ITA.ENG.AC3.BDRip.1080p.X265_ZMachine.mkv
A.Good.Day.To.Die.Hard.ITA.ENG.AC3.BDRip.1080p.X264-ZMachine.mkv
'Harry.Potter.and.the.Philosopher.s.Stone.Extended.(2001).ITA.ENG.AC3.BDRip.1080p.X265_ZMachine.mkv'
The.Hobbit.An.Unexpected.Journey.Extended.ITA.ENG.AC3.BDRip.1080p.X264-ZMachine.mkv
The.Hobbit.The.Battle.Of.The.Five.Armies.Extended.2014.ITA.ENG.BDRip.1080p.H264-Fratposa.mkv
The.Hobbit.The.Desolation.of.Smaug.Extended.ITA.ENG.AC3.BDRip.1080p.X264_ZMachine.mkv
```
Except for one missing letter on the following movie _Star.Wars.The.Phanom.Menace.ITA.ENG.AC3.BDRip.1080p.X265_ZMachine.mkv_ the `t` on Phantom word, all others movies have the same issue (even this one after the correction). 

These are some example of what I'm talking about:
```
[INF] MovieDbProvider: Finding id for item: A.Good.Day.To.Die.Hard.ITA.ENG
[INF] MovieDbProvider: Finding id for item: The.Hobbit.The.Desolation.of.Smaug.ITA.ENG
[INF] MovieDbProvider: Finding id for item: Star.Wars.The.Empire.Strikes.Back.ITA.ENG
[INF] MovieDbProvider: Finding id for item: Star.Wars.The.Phanom.Menace.ITA.ENG
```
I moved ITA.ENG after 1080p in the title, so what follows contains in the first line the old name and in the second line the new name:
```
The.Hobbit.An.Unexpected.Journey.Extended.ITA.ENG.AC3.BDRip.1080p.X264-ZMachine.mkv
The.Hobbit.An.Unexpected.Journey.Extended.AC3.BDRip.1080p.ITA.ENG.X264-ZMachine.mkv
```
This leads to: `[INF] MovieDbProvider: Finding id for item: The.Hobbit.An.Unexpected.Journey.Extended` that is correctly recognized.

I don't know if the issue is here or somewhere else and I don't even know C# but this if statement should be never executed due to previous else https://github.com/jellyfin/jellyfin/blob/master/Emby.Naming/Video/ExtraResolver.cs#L49

**Comment by cvium** [comment]
This is fixed by having a sane folder structure eg. `The Hunger Games\The.Hunger.Games.ITA.ENG.AC3.BDRip.1080p.X265_ZMachine.mkv` works just fine.
