### ISSUE TITLE
Media download in apps

### ISSUE THREAD

**Issue by TheManchineel** [jellyfin/jellyfin#217]
Currently when I try to download media from mobile apps it asks me to buy Emby Premiere. Doesn't this project also unlock all features along with making them free? (I.e. like emby-unlocked did?)

**Comment by nvllsvm** [comment]
The Android apps validate Premiere status with Emby-owned servers. There's nothing we can do about this.

Was this working for you with emby-unlocked?

**Comment by TheManchineel** [comment]
Honestly I had not tried it myself, I only had read online about it being able to let you use Emby Premiere for free. The fact that they were using remote authentication for downloads is even one less reason to stay on the proprietary Emby. For the time being, until Jellyfin apps are developed, I guess I'll stay on Yatse (which just implemented support for JellyFin) and has several features including downloads (not free though).

**Comment by nvllsvm** [comment]
Closing - cannot fix official Emby apps.

**Comment by PrplHaz4** [comment]
@anthonylavado worth maintaining a wiki page for known incompatibilities or breakages?
