### ISSUE TITLE
Tv Episodes identified incorrectly in 10.4.2 and 10.4.3

### ISSUE THREAD

**Issue by SenorSmartyPants** [jellyfin/jellyfin#2171]
**Describe the bug**
Some TV Episodes are identified incorrectly in versions after 10.4.1. 

**To Reproduce**

Some Show 25x39 - [WEBDL-720p][x264] Some Episode.mkv mis-identified as S01E25
That Other Show 1x07 [WEBDL-1080p][EAC3 5.1][x264] - Chapter 7.mkv misidentified as S01E01

**Expected behavior**

Correctly id shows based on SSxEE number, as was occuring in 10.4.1 and lower.

**System (please complete the following information):**
 - OS: Docker
 - Browser: Chrome
 - Jellyfin Version: 10.4.2 and 10.4.3
 - Installed Plugins: Fanart, Trakt, 
 - Reverse proxy: no

**Comment by ioogithub** [comment]
I can confirm this bug. I have installed the docker image for the first time and every episode is mislabeled as the season number.

Example: Every episode in Season 3 of a show is Episode 3 with the same title and metadata.

Coorrect:

Season 3 - Episode 1
- Episode 2
- Episode 3

has become:

Season 3 - Episode 3
-Episode 3
-Episode 3

etc. It actually did this to my entire collection, every show and every episode is incorrectly labeled as the season number.

**Comment by SenorSmartyPants** [comment]
I backed down to 10.4.1 and rescanned

**Comment by ioogithub** [comment]
I will try the same thing and I can see if it fixes my issue. Do you know if it is possible to revert to an earlier release when using a docker container? I am using the command from the install page to launch my Jellyfin version:

`docker run -d -v /srv/jellyfin/config:/config -v /srv/jellyfin/cache:/cache -v /media:/media --net=host **jellyfin/jellyfin:latest**`

I would assume the version number is the ":latest" part.  Is it possible to specify **jellyfin/jellyfin:10.4.1** for example?

Unfortunately docker is the only way I can get jellyfun to run, none of the packages support my OS.

**Comment by SenorSmartyPants** [comment]
Yes, latest is the tag in docker hub. Ask recent releases are tagged by version number

**Comment by ioogithub** [comment]
Thanks for the assistance. I did run the docker run command with the jellyfin/jellyfin:10.4.1 and it finds the image, pulls it in, downloaded it then it returns an ID, digest, status etc., it looks like it is going to work however it doesn't start the webserver, there is no page at http://localhost:8096/.

I tried it with jellyfin/jellyfin:10.4.2, same thing, it finds the image, downloads it and runs it however no webpage. If I do a netstat there is definitely no listener there.

If I repeat the run command with :10.4.3 or with :latest it runs as expected and I can see the dotnet listener on port 8096.

I even cleared all containers and images and started fresh, only the 10.4.3 release seems to work. Any ideas on why the older releases don't work in this way? Am I missing something conceptually?

**Comment by anthonylavado** [comment]
@ioogithub When you go to 10.4.1, try “http://localhost:8096/jellyfin”.

**Comment by ioogithub** [comment]
Hi, I did try that however I don't see a webpage there, yes it doesn't start. Did the URL change from 10.4.3 to 10.4.1. Even if it did I can verify with netstat there is no listener on that port with anything other than :latest

I don't have any plugins downloaded. Should it work this way? Should I be able to do a clean run of jellyfin/jellyfin:10.4.1 and get a webpage or am I missing something? I am brand new to docker (and jellyfin) so not sure what is normal.

It is very reproducible, If I do a run jellyfin/jellyfin:10.4.3 or run jellyfin/jellyfin:latest, I get a webpage, if I do a jellyfin/jellyfin:10.4.2 or jellyfin/jellyfin:10.4.1, nothing at all. I thought maybe these older packages don't have the webserver in them or are incomplete in some way?

Unfortunately I really can't run 10.4.3 at all this bug effectively kills my whole TV library, every episode title and metadata is overwritten by the same episode over and over so there is no way to navigate the media in jellyfin.

**Comment by anthonylavado** [comment]
@ioogithub Those older releases wouldn’t be touched by anything recent. They’re fully self-contained, which is why we create tags for every version. Of note - the web server is part of the core software of Jellyfin. If it’s not running, then Jellyfin isn’t starting up…

Are there any logs you can get at all? I don’t know where those are kept for our Docker releases, but on my bare metal Debian install, it’s at `/var/log/jellyfin`.

**Comment by SenorSmartyPants** [comment]
What's any progress on this? I've been staying on 10.4.1 so episodes will be identified properly, but I just ran into the bug where DVD ordered episodes are pulling the wrong image #2088  (which looks like it might have been fixed in 10.4.3). 

So I don't currently have a version without bugs for my primary uses.

Thanks for everything the team has done in JF so far.

**Comment by JustAMan** [comment]
Can you share with us an exact name of the file being mis-identified? Preferably with full path (at least include its directory).

**Comment by SenorSmartyPants** [comment]
Watchmen (2019)/Watchmen 1x03 [WEBDL-720p][EAC3 5.1][h264][-TBS] - She Was Killed by Space Junk.mkv

Get's identified as Season 1 episode 1

**Comment by Bond-009** [comment]
Can you check the latest master?

**Comment by SenorSmartyPants** [comment]
No, I run ARM servers. #2286

**Comment by SenorSmartyPants** [comment]
Just tested this with the ARM nightly. Still has the same problems with Watchmen and Daily show

**Comment by SenorSmartyPants** [comment]
Can't the scanner changes that broke this just be rolled back?

**Comment by Artiume** [comment]
The issue stems from

> 
> 
> Can't the scanner changes that broke this just be rolled back?

https://github.com/jellyfin/jellyfin/pull/2104/files

Here's your changes. If you would like to try and improve the scanner, I would start here.
