### ISSUE TITLE
Webp Art Support

### ISSUE THREAD

**Issue by XVicarious** [jellyfin/jellyfin#2172]
WEBP seems to be supported internally with the image caches, but you can still only use JPEG or PNG files for posters, arts, etc though the Edit Images feature for media items. It'd be cool to be able to use WEBP.

**Comment by JustAMan** [comment]
Isn't it closed by your PR https://github.com/jellyfin/jellyfin-web/pull/649 ?

**Comment by XVicarious** [comment]
Yep
