### ISSUE TITLE
Plugins catalogue and update failure 

### ISSUE THREAD

**Issue by gllyrjones** [jellyfin/jellyfin#2174]
**Describe the bug**
Plugins catalogue will not load and plugin update task will fail - apparently a missing certificate in the docker image 

**To Reproduce**

1. Go to plugins
2. Click on catalogue 

**Expected behavior**
Should update and see catalogue 

**Logs**
https://ibb.co/qWCfY3w

**System (please complete the following information):**
 - OS: docker
 - Browser: 
 - Jellyfin Version: 10.4.3
 - Installed Plugins: opensubtitles, playback reports 
 - Reverse proxy: apache2

**Additional context**

**Comment by BnMcG** [comment]
What makes you say there's a missing certificate in the Docker image? Nothing in the screenshot you've attached immediately jumps out at me as being a certificate issue.

**Comment by PrplHaz4** [comment]
Make sure you can reach the internet from inside the container.

**Comment by gllyrjones** [comment]
> What makes you say there's a missing certificate in the Docker image? Nothing in the screenshot you've attached immediately jumps out at me as being a certificate issue.

One of the developers eluded to it on reditt.

**Comment by gllyrjones** [comment]
> Make sure you can reach the internet from inside the container.

It's downloading all the meta data for movies so I assume it can connect. However when i manually search to identify some missing meta data it never it never returns any info.

**Comment by gllyrjones** [comment]
> Make sure you can reach the internet from inside the container.

You were right - in the docker create thingy i changed --net=host to -p 8096 and it worked immediately. Big thanks.

**Comment by PrplHaz4** [comment]
@gllyrjones if you want to use DLNA or HDHR LiveTV you'll need to use --net=host - I get around this by having the container on macvlan and a bridge network.

**Comment by Disposaber** [comment]
@PrplHaz4 can you explain how did you do the bridge?

**Comment by PrplHaz4** [comment]
> 
> 
> @PrplHaz4 can you explain how did you do the bridge?

@Disposaber It is very much dependent on what you're trying to setup - in most instances, you should be able to access the internet using --net=host or the default bridge network.

see more here: https://docs.docker.com/network/bridge/
