### ISSUE TITLE
Genre disappeared when choose Jellyfin language "Chinese Simplified"

### ISSUE THREAD

**Issue by NJCCJohnWason** [jellyfin/jellyfin#2177]
**Describe the bug**

Genre disappeared when choose Jellyfin language "Chinese Simplified"

**To Reproduce**

1.I not a native English user ,so when I create new media reps I find the movie genre is normally display
2.When I switched the Jellyfin language to "Chinese Simplified",I want to watch movie then find all Genre is disappeared 

**Expected behavior**

**Logs**

**Screenshots**
I think picture is more impressive

When my language is English 

![图片](https://user-images.githubusercontent.com/17756284/71301542-1e37ba00-23db-11ea-87c2-d08847b7bb3f.png)

When my language is Chinese Simplified

![图片](https://user-images.githubusercontent.com/17756284/71301560-5c34de00-23db-11ea-8075-e4ed25b49eb7.png)

**System (please complete the following information):**
 - OS: windows
 - Browser: Firefox
 - Jellyfin Version: 10.5.0
 - Installed Plugins: none
 - Reverse proxy: no
**Additional context**
In the beginning  I thought that is my Jellyfin version problems ,so I updated to latest version  and bugs still like that

**Comment by anthonylavado** [comment]
We’ll have to check what the metadata sources report for that language.

**Comment by NJCCJohnWason** [comment]
> 
> 
> We’ll have to check what the metadata sources report for that language.

Thank for your reply,that thing make me feel confused

**Comment by NJCCJohnWason** [comment]
> 
> 
> We’ll have to check what the metadata sources report for that language.

And I check the movie that controlled by .nfo file,and it's have same problem genres  just gone when I switched to Chinese Simplified

**Comment by anthonylavado** [comment]
@NJCCJohnWason Interesting. Thank you for that test!

I wonder if we need to check something in the translation and fallback code...

**Comment by NJCCJohnWason** [comment]
Thank for you relpy but,the problem will **only happen** in languag of Chinese Simplified .
It's such weird.
I think picture is more convictive than words
Here is the Deteil of movie when I switch language to **Chinese Simplified**
The genre is gone...
![图片](https://user-images.githubusercontent.com/17756284/71329552-94febf80-2561-11ea-8113-057b617fec17.png)
Here is the Deteil of movie when I switch language to **Chinese Traditional** (that's nearly to Chinese Simplified)
The genre is OK...
![图片](https://user-images.githubusercontent.com/17756284/71329577-b19af780-2561-11ea-9c8d-2c7930fa1fcb.png)
and Thank you for your endeavour for the such good project again

**Comment by anthonylavado** [comment]
Thank you! That helped me find it. It’s a problem in the translations. I’ll fix it soon. It won’t show up until the next version.

Example:
```
Genre: {0} => 风格

Genre: {0} => 類型 : {0}

```
