### ISSUE TITLE
nvidia-docker --gpus does not transcode

### ISSUE THREAD

**Issue by Arcanum417** [jellyfin/jellyfin#2182]
**Describe the bug**
Hw encoding / decoding using nvidia GPU in docker does not work with nvidia-docker --gpus param.

**To Reproduce**

1. Install GTX 960 in your rig (GPU with nvenc support)
1. Install Arch (thats what I did I imagine this is not Arch issue)
1. Inall `nvidia` package (nvdia drivers)
1. verify GPU drivers with `nvidia-smi`
3. Install docker
2. Install nvidia-container-toolkit https://github.com/NVIDIA/nvidia-docker
3. werify that works with `docker run --gpus all nvidia/cuda:9.0-base nvidia-smi`
1. Place .mp4 x264 video in /root/test/test.mp4
2. run `docker run --volume /root/test:/test --gpus all jrottenberg/ffmpeg:4.1-nvidia -hwaccel cuvid -c:v h264_cuvid -i /test/test.mp4 -vf scale_npp=-1:720 -c:v h264_nvenc -preset slow -f null -` that works
3.  run
```
docker run -d \
--gpus all \
--volume /root/appdata:/config \
--volume /root/cache:/cache \
--volume /root/test:/media \
--net=host \
--restart=unless-stopped \
jellyfin/jellyfin
```
4. Go to http://yourip:8086 and do firsttime setup, add /media to your library
5. in playback settings enable hw transcode for nvenc enable all settings if your gpu supports it
6. try to play the video, it error with no streams available, in logs :
```
[h264_cuvid @ 0x559195d65c80] Cannot load libnvcuvid.so.1
[h264_cuvid @ 0x559195d65c80] Failed loading nvcuvid.
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (h264_cuvid) -> h264 (h264_nvenc))
  Stream #0:1 -> #0:1 (aac (native) -> mp3 (libmp3lame))
Error while opening decoder for input stream #0:0 : Operation not permitted
```

**Expected behavior**
Video plays transcoded using GPU. `nvidia-smi` run on host shows the job.

**Logs**
https://gist.github.com/Arcanum417/612f20921336ab14f56489f67276fc51

**System (please complete the following information):**
 - OS: Arch
 - Browser: Chrome
 - Jellyfin Version: 10.4.3
 - Installed Plugins: None
 - Reverse proxy: no

**Comment by Arcanum417** [comment]
Also, the same thing works with https://hub.docker.com/r/linuxserver/jellyfin

**Comment by JustAMan** [comment]
@Arcanum417 can you check for permission issues with the user inside your container? Maybe adding to `video` group, or whatever is needed to access NVENC? As Jellyfin is not running as `root` I think.

**Comment by antipiot** [comment]
Hello!
I'm facing the exact same issue: DId you get it sorted out?

`http://10.0.0.129:8096/videos/dcdbd376-5d37-6fe2-526c-0874213808e2/hls1/main/0.ts?DeviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6NzIuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC83Mi4wfDE1ODExODA3NjI3OTM1&MediaSourceId=dcdbd3765d376fe2526c0874213808e2&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=1&SubtitleStreamIndex=5&VideoBitrate=1291987692&AudioBitrate=320000&PlaySessionId=07ec9021ed5d4a54b7d0ae718b6e6e8a&api_key=67d270cc9d6e4b4a8f093e261f1b17ed&SubtitleMethod=Encode&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=87d381e6f9ace50e2b35bd80ab8a42c9&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51&TranscodeReasons=SubtitleCodecNotSupported&allowVideoStreamCopy=false&allowAudioStreamCopy=false

{"Protocol":"File","Id":"dcdbd3765d376fe2526c0874213808e2","Path":"/data/movies/Pacific Rim (2013).mkv","Type":"Default","Container":"mkv,webm","Size":6406501888,"Name":"Pacific Rim (2013)","IsRemote":false,"ETag":"87d381e6f9ace50e2b35bd80ab8a42c9","RunTimeTicks":78769922048,"ReadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"RequiresClosing":false,"RequiresLooping":false,"SupportsProbing":true,"VideoType":"VideoFile","MediaStreams":[{"Codec":"hevc","TimeBase":"1/1000","CodecTimeBase":"1001/24000","VideoRange":"SDR","DisplayTitle":"4K HEVC","IsInterlaced":false,"BitRate":6506546,"RefFrames":1,"IsDefault":true,"IsForced":false,"Height":2160,"Width":3840,"AverageFrameRate":23.9760246,"RealFrameRate":23.9760246,"Profile":"Main 10","Type":"Video","AspectRatio":"16:9","Index":0,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"PixelFormat":"yuv420p10le","Level":150},{"Codec":"aac","Language":"fre","TimeBase":"1/1000","CodecTimeBase":"1/48000","Title":"French 7.1","DisplayTitle":"Fre AAC 7.1 Default","IsInterlaced":false,"ChannelLayout":"7.1","BitRate":320000,"Channels":8,"SampleRate":48000,"IsDefault":true,"IsForced":false,"Profile":"HE-AAC","Type":"Audio","Index":1,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Level":0},{"Codec":"aac","Language":"eng","TimeBase":"1/1000","CodecTimeBase":"1/48000","Title":"English 7.1","DisplayTitle":"Eng AAC 7.1","IsInterlaced":false,"ChannelLayout":"7.1","BitRate":320000,"Channels":8,"SampleRate":48000,"IsDefault":false,"IsForced":false,"Profile":"HE-AAC","Type":"Audio","Index":2,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Level":0},{"Codec":"PGSSUB","Language":"eng","TimeBase":"1/1000","CodecTimeBase":"0/1","Title":"English PGS","localizedUndefined":"Undefined","localizedDefault":"Default","localizedForced":"Forced","DisplayTitle":"English PGS","IsInterlaced":false,"IsDefault":false,"IsForced":false,"Type":"Subtitle","Index":3,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Level":0},{"Codec":"PGSSUB","Language":"fre","TimeBase":"1/1000","CodecTimeBase":"0/1","Title":"French PGS","localizedUndefined":"Undefined","localizedDefault":"Default","localizedForced":"Forced","DisplayTitle":"French PGS","IsInterlaced":false,"IsDefault":false,"IsForced":false,"Type":"Subtitle","Index":4,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Level":0},{"Codec":"PGSSUB","Language":"fre","TimeBase":"1/1000","CodecTimeBase":"0/1","Title":"French forced PGS","localizedUndefined":"Undefined","localizedDefault":"Default","localizedForced":"Forced","DisplayTitle":"French forced PGS - Default","IsInterlaced":false,"IsDefault":true,"IsForced":true,"Type":"Subtitle","Index":5,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Level":0},{"Codec":"subrip","Language":"eng","TimeBase":"1/1000","CodecTimeBase":"0/1","Title":"English SRT","localizedUndefined":"Undefined","localizedDefault":"Default","localizedForced":"Forced","DisplayTitle":"English SRT","IsInterlaced":false,"IsDefault":false,"IsForced":false,"Type":"Subtitle","Index":6,"IsExternal":false,"IsTextSubtitleStream":true,"SupportsExternalStream":true,"Level":0},{"Codec":"subrip","Language":"fre","TimeBase":"1/1000","CodecTimeBase":"0/1","Title":"Frensh SRT","localizedUndefined":"Undefined","localizedDefault":"Default","localizedForced":"Forced","DisplayTitle":"Frensh SRT","IsInterlaced":false,"IsDefault":false,"IsForced":false,"Type":"Subtitle","Index":7,"IsExternal":false,"IsTextSubtitleStream":true,"SupportsExternalStream":true,"Level":0},{"Codec":"subrip","Language":"fre","TimeBase":"1/1000","CodecTimeBase":"0/1","Title":"French forced","localizedUndefined":"Undefined","localizedDefault":"Default","localizedForced":"Forced","DisplayTitle":"French forced","IsInterlaced":false,"IsDefault":false,"IsForced":false,"Type":"Subtitle","Index":8,"IsExternal":false,"IsTextSubtitleStream":true,"SupportsExternalStream":true,"Level":0}],"Formats":[],"Bitrate":7146546,"RequiredHttpHeaders":{}}

/usr/lib/jellyfin-ffmpeg/ffmpeg -c:v hevc_cuvid  -resize 1920x1080 -i file:"/data/movies/Pacific Rim (2013).mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -codec:v:0 h264_nvenc -pix_fmt yuv420p -preset default -b:v 13013092 -maxrate 13013092 -bufsize 26026184 -profile:v high -force_key_frames:0 "expr:gte(t,0+n_forced*3)" -filter_complex "[0:5]scale=3840:2160:force_original_aspect_ratio=decrease[sub];[0:0][sub]overlay" -copyts -vsync -1 -codec:a:0 aac -strict experimental -ac 2 -ab 320000 -af "volume=2" -f hls -max_delay 5000000 -avoid_negative_ts disabled -start_at_zero -hls_time 3 -individual_header_trailer 0 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/config/data/transcoding-temp/transcodes/transcodes/727f4670b8cbae8c304391a752ec2f05%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/config/data/transcoding-temp/transcodes/transcodes/727f4670b8cbae8c304391a752ec2f05.m3u8"


ffmpeg version 4.2.1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.4.0-1ubuntu1~18.04.1)
  configuration: --toolchain=hardened --prefix=/usr --target-os=linux --enable-cross-compile --extra-cflags=--static --enable-gpl --enable-static --disable-doc --disable-ffplay --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-libfontconfig --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libwebp --enable-libx264 --enable-libx265 --enable-libzvbi --enable-omx --enable-omx-rpi --enable-version3 --enable-vaapi --enable-vdpau --arch=amd64 --enable-nvenc --enable-nvdec
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[matroska,webm @ 0x5582e6f9eb80] Could not find codec parameters for stream 3 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[matroska,webm @ 0x5582e6f9eb80] Could not find codec parameters for stream 4 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[matroska,webm @ 0x5582e6f9eb80] Could not find codec parameters for stream 5 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, matroska,webm, from 'file:/data/movies/Pacific Rim (2013).mkv':
  Metadata:
    title           : Pacific Rim (2013) - 4KLight
    creation_time   : 2019-07-04T13:33:16.000000Z
    ENCODER         : Lavf58.20.100
  Duration: 02:11:16.99, start: 0.000000, bitrate: 6506 kb/s
    Chapter #0:0: start 0.000000, end 549.090000
    Metadata:
      title           : Chapter 1
    Chapter #0:1: start 549.090000, end 1115.781000
    Metadata:
      title           : Chapter 2
    Chapter #0:2: start 1115.781000, end 1384.299000
    Metadata:
      title           : Chapter 3
    Chapter #0:3: start 1384.299000, end 1980.353000
    Metadata:
      title           : Chapter 4
    Chapter #0:4: start 1980.353000, end 2564.854000
    Metadata:
      title           : Chapter 5
    Chapter #0:5: start 2564.854000, end 3001.623000
    Metadata:
      title           : Chapter 6
    Chapter #0:6: start 3001.623000, end 3669.624000
    Metadata:
      title           : Chapter 7
    Chapter #0:7: start 3669.624000, end 4485.064000
    Metadata:
      title           : Chapter 8
    Chapter #0:8: start 4485.064000, end 4941.269000
    Metadata:
      title           : Chapter 9
    Chapter #0:9: start 4941.269000, end 5529.899000
    Metadata:
      title           : Chapter 10
    Chapter #0:10: start 5529.899000, end 6115.567000
    Metadata:
      title           : Chapter 11
    Chapter #0:11: start 6115.567000, end 6697.816000
    Metadata:
      title           : Chapter 12
    Chapter #0:12: start 6697.816000, end 7160.987000
    Metadata:
      title           : Chapter 13
    Chapter #0:13: start 7160.987000, end 7337.788000
    Metadata:
      title           : Chapter 14
    Chapter #0:14: start 7337.788000, end 7876.827000
    Metadata:
      title           : Chapter 15
    Stream #0:0: Video: hevc (Main 10), yuv420p10le(tv, bt2020nc/bt2020/smpte2084), 3840x2160 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 23.98 tbc (default)
    Metadata:
      BPS-eng         : 5840342
      DURATION-eng    : 02:11:16.869000000
      NUMBER_OF_FRAMES-eng: 188855
      NUMBER_OF_BYTES-eng: 5750451136
      _STATISTICS_WRITING_APP-eng: mkvmerge v35.0.0 ('All The Love In The World') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2019-07-04 13:33:16
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:1(fre): Audio: aac (HE-AAC), 48000 Hz, 7.1, fltp (default)
    Metadata:
      title           : French 7.1
      BPS-eng         : 318057
      DURATION-eng    : 02:11:16.992000000
      NUMBER_OF_FRAMES-eng: 184617
      NUMBER_OF_BYTES-eng: 313167533
      _STATISTICS_WRITING_APP-eng: mkvmerge v35.0.0 ('All The Love In The World') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2019-07-04 13:33:16
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:2(eng): Audio: aac (HE-AAC), 48000 Hz, 7.1, fltp
    Metadata:
      title           : English 7.1
      BPS-eng         : 320062
      DURATION-eng    : 02:11:16.992000000
      NUMBER_OF_FRAMES-eng: 184617
      NUMBER_OF_BYTES-eng: 315141539
      _STATISTICS_WRITING_APP-eng: mkvmerge v35.0.0 ('All The Love In The World') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2019-07-04 13:33:16
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:3(eng): Subtitle: hdmv_pgs_subtitle
    Metadata:
      title           : English PGS
      BPS-eng         : 31167
      DURATION-eng    : 02:10:32.116000000
      NUMBER_OF_FRAMES-eng: 3670
      NUMBER_OF_BYTES-eng: 30513506
      _STATISTICS_WRITING_APP-eng: mkvmerge v35.0.0 ('All The Love In The World') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2019-07-04 13:33:16
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:4(fre): Subtitle: hdmv_pgs_subtitle
    Metadata:
      title           : French PGS
      BPS-eng         : 22567
      DURATION-eng    : 02:10:40.165000000
      NUMBER_OF_FRAMES-eng: 3138
      NUMBER_OF_BYTES-eng: 22116528
      _STATISTICS_WRITING_APP-eng: mkvmerge v35.0.0 ('All The Love In The World') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2019-07-04 13:33:16
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:5(fre): Subtitle: hdmv_pgs_subtitle (default) (forced)
    Metadata:
      title           : French forced PGS
      BPS-eng         : 592
      DURATION-eng    : 02:10:40.165000000
      NUMBER_OF_FRAMES-eng: 68
      NUMBER_OF_BYTES-eng: 581065
      _STATISTICS_WRITING_APP-eng: mkvmerge v35.0.0 ('All The Love In The World') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2019-07-04 13:33:16
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:6(eng): Subtitle: subrip
    Metadata:
      title           : English SRT
      BPS-eng         : 59
      DURATION-eng    : 02:10:32.116000000
      NUMBER_OF_FRAMES-eng: 1835
      NUMBER_OF_BYTES-eng: 58054
      _STATISTICS_WRITING_APP-eng: mkvmerge v35.0.0 ('All The Love In The World') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2019-07-04 13:33:16
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:7(fre): Subtitle: subrip
    Metadata:
      title           : Frensh SRT
      BPS-eng         : 44
      DURATION-eng    : 02:10:40.165000000
      NUMBER_OF_FRAMES-eng: 1568
      NUMBER_OF_BYTES-eng: 44056
      _STATISTICS_WRITING_APP-eng: mkvmerge v35.0.0 ('All The Love In The World') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2019-07-04 13:33:16
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:8(fre): Subtitle: subrip
    Metadata:
      title           : French forced
      BPS-eng         : 0
      DURATION-eng    : 02:10:40.165000000
      NUMBER_OF_FRAMES-eng: 34
      NUMBER_OF_BYTES-eng: 978
      _STATISTICS_WRITING_APP-eng: mkvmerge v35.0.0 ('All The Love In The World') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2019-07-04 13:33:16
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
[hevc_cuvid @ 0x5582e6fd1c40] Cannot load libnvcuvid.so.1
[hevc_cuvid @ 0x5582e6fd1c40] Failed loading nvcuvid.
Stream mapping:
  Stream #0:0 (hevc_cuvid) -> overlay:main (graph 0)
  Stream #0:5 (pgssub) -> scale (graph 0)
  overlay (graph 0) -> Stream #0:0 (h264_nvenc)
  Stream #0:1 -> #0:1 (aac (native) -> aac (native))
Error while opening decoder for input stream #0:0 : Operation not permitted`

my run command looks like:

`docker run -d  --runtime=nvidia\
  --name=jellyfin \
  -e PUID=1000 \
  -e PGID=100 \
  -e NVIDIA_DRIVER_CAPABILITIES=all \
  -p 8096:8096 \
  -p 8920:8920 \
  -v /sharedfolders/data/docker/jellyfin/config:/config \
  -v /sharedfolders/data/docker/jellyfin/movies:/data/movies \
  --restart unless-stopped \
  --gpus all \
  -e NVIDIA_VISIBLE_DEVICES=all \
  linuxserver/jellyfin`

Did you get it working?
