### ISSUE TITLE
Support custom resolvers

### ISSUE THREAD

**Issue by nielsvanvelzen** [jellyfin/jellyfin#2187]
Currently all library types (tv shows, movies, music etc.) have their own "resolver" to import media. They all have a certain folder structure the user should follow, and when the users does just that nothing will go wrong (mostly).

But what if the user is stubborn and has his own folder structure and doesn't want to change that?

I made some custom resolvers for myself and they work excellent, I can not import my custom structure to Jellyfin with almost no problems. But the way I did this is not officially supported and does cause some problems because the Jellyfin resolvers still work.

# What I did

_I made multiple resolvers but for this issue I'll use the simplest I made_

I made a class `MusicResolver` in my own plugin that implements the `IItemResolver` and `IMultiItemResolver` interfaces. It sets the `ResolverPriority` to `First` so it will get called before most default resolvers. The `ResolveMultiple` function always returns null so it isn't actually implemented. The `ResolvePath` function checks if the `CollectionType` is non-null and if it equals the `Music`  type.

Next it just does some basic stuff checking what kind of file it is resolving and returns a class extending BaseItem.

**This works great!** Except for the fact that files my resolver ignores will be imported by the next resolver found.

# What I'd like to see changed

As Jellyfin already supports this functionality quite well I'd like to extend it with some customization. Firstly; I'd like to change the resolver(s) used from the user interface. My suggestion would be to have this work the same as metadata downloaders: The user can choose per library which resolver to use. I'd suggest to only support one per library instead of multiple.

## Possible implementation
This can be implemented in 2 ways:
 1. Merge existing resolvers (the "official" one for audio is 3 separate resolvers working together: AudioResolver, MusicAlbumResolver and MusicArtistResolver, see https://github.com/jellyfin/jellyfin/tree/f1fc6ef59f669abcae33b3a6db627683364eb8ff/Emby.Server.Implementations/Library/Resolvers/Audio)
 2. Add a new class (lets call it "scanner for now) which contains a list/function to clarify which resolvers to use

Additional properties should be added to the resolver/scanner for identification. Just like providers a Name should be added. Additionally in some way we should define for which library types the scanner/resolver works. Providers do this using a generic.

Jellyfin should have a way to determine which scanner/resolver is the "official" default and use that. When multiple scanners/resolvers are found for a certain library type the user can change the one used in the library settings. (option is hidden by default, or a disabled input or something like that)

# Use-cases
 - Custom scanners for non-standard library structures
 - Provide multiple structures for users (for example; the music library supports a flat-structure and a album based structure by guessing. If we separate this to multiple scanners/resolvers the user can choose their variant in the library settings)
 - Improve library-scan speed because we don't have to use ALL resolvers for each library, only the one selected by the user.

**TL;DR:** Improve support for customized resolvers in plugins.

**Comment by JustAMan** [comment]
cc @Bond-009 and @cvium for feedback

**Comment by Bond-009** [comment]
Sounds good to me :+1: 
Current solution is a mess

**Comment by dkanada** [comment]
I think I prefer the second method to the first. We could just add a new plugin category for resolvers and you could have the first entry. The you just need to implement a page somewhere to select active resolvers.

**Comment by nielsvanvelzen** [comment]
Example for a custom resolver plugin: https://github.com/nielsvanvelzen/jellyfin-plugin-resolver

I need to to some more work before I can call it stable. This PR is the one thing that is needed from the Jellyfin side to finish it.

**Comment by dkanada** [comment]
> This PR is the one thing that is needed from the Jellyfin side to finish it.

You mean the configuration option listed above?

**Comment by nielsvanvelzen** [comment]
I meant "issue" instead of "PR"... it was late. Without proper support a custom resolver needs to use some hacks to get it working at the moment.
