### ISSUE TITLE
[Feature Request] Add setting for path of transcoding-temp folder

### ISSUE THREAD

**Issue by firstrose** [jellyfin/jellyfin#2189]
**Describe the bug**

Playing back frequently requires transcoding. The default transcoding-temp folder is in jellyfin's data folder, that is not friendly for SSD-based system drive. Redirecting transcoding-temp folder to non-SSD drive will incrase SSD's lifespan.

**System (please complete the following information):**
 - Jellyfin Version: 10.4.3

**Comment by Nickbert7** [comment]
The setting should already be available
Settings --> Playback --> Transcode path
![20191224_133748](https://user-images.githubusercontent.com/14938497/71413463-9825a880-2652-11ea-8e68-b2c979658f4f.jpg)
