### ISSUE TITLE
Collection empty 

### ISSUE THREAD

**Issue by gllyrjones** [jellyfin/jellyfin#2190]
**Describe the bug**
When adding movies to a collection, movies will not appear in collection after. Some random movies will appear. 

**To Reproduce**
Right click on movie, add to collection, select collection. 

**Expected behavior**
Movie should appear in collection

**System (please complete the following information):**
 - OS: [ Docker, Debian]
 - Browser: firefox and mobile phone
 - Jellyfin Version: 10.4.3
 - Reverse proxy: apache

**Comment by NJCCJohnWason** [comment]
Do you ever try restart the jellynfin service
or reboot system

**Comment by gllyrjones** [comment]
Yep, no, joy. Just added 10 movies to a collection. Only 3 appeared. Thanks

**Comment by anthonylavado** [comment]
Any plugins installed? Like TMDB Boxsets?

What metadata providers are turned on for the movie library?

**Comment by gllyrjones** [comment]
No plugins. Metadata provides are the open movie db and moviedb. Thanks.

**Comment by texneus** [comment]
I'm having the same issue, more or less.  Starting with 10.4.2 under Debian/Docker I noticed several movies had "fallen out" of collections they were previously in.  I cannot get them back in a collection manually or automatically (scanning with the boxset plugin).  Problem still exists in 10.4.3.

Possible clue:  All movies that dropped out have multiple versions (I.e. a theatrical and an extended edition).

**Comment by jcvara** [comment]
Expanding on the previous comment by @texneus, I have the same problem with a boxset that has dropped one movie after I've added a version to the movie folder, but I have noticed that every time I scan with the boxset plugin it adds a duplicate CollectionItem to the collection's xml, like this:

```xml
  <CollectionItems>
    <CollectionItem>
      <Path>/data/movies/A Dog's Journey (2019)/A Dog's Journey (2019) - [Dual] [FHD].mp4</Path>
    </CollectionItem>
    <CollectionItem>
      <Path>/data/movies/A Dog's Purpose (2017)/A Dog's Purpose (2017) - [Dual] [FHD].mkv</Path>
    </CollectionItem>
    <CollectionItem>
      <Path>/data/movies/A Dog's Purpose (2017)/A Dog's Purpose (2017) - [Dual] [FHD].mkv</Path>
    </CollectionItem>
    >...several more duplicates...<
  </CollectionItems>
```

Jellyfin info (showing on dashboard):

Version: 10.4.3
Operating System: Linux
Architecture: X64

I'm using the linuxserver/jellyfin:latest docker image in a QNAP nas.

I have tried restarting the container, rescanning the library, removing and adding the files again, and removing the collection from path-to-config/data/data/collections/ to no avail.

**Comment by JustAMan** [comment]
paging @cvium

**Comment by Artiume** [comment]
Is this still an issue

**Comment by JustAMan** [comment]
Did you check if https://github.com/jellyfin/jellyfin/pull/3117 fixes that?

**Comment by gllyrjones** [comment]
I've had no issues since, so can be closed, thanks

**Comment by ethancedwards8** [comment]
I think this should be reopened, I'm having this issue and its really annoying.

**Comment by ethancedwards8** [comment]
I just checked the xml file and it has duplicate entries. I'm using the most recent jellyfin docker image.

**Comment by cvium** [comment]
Make a new issue and fill out the issue template. Your issue is not the same as the original issue.
