### ISSUE TITLE
Moving movie files to a new directory makes JF think it was newly added.

### ISSUE THREAD

**Issue by SenorSmartyPants** [jellyfin/jellyfin#2196]
**Describe the bug**
Keeping the movie file name the same, but moving it to a new directory will make JF set a new added date for that movie. This will make the movie show up in Latest movies, even thou it has been in JF for while a while.

**System (please complete the following information):**
 - OS: Docker
 - Browser: Chrome
 - Jellyfin Version: 10.4.1

**Comment by cvium** [comment]
How is that a bug?

**Comment by telans** [comment]
> How is that a bug?

I would say because it's not a new file at all, nor was it deleted or re-added at a later date, only the filepath was changed. That doesn't make it newly "added", but newly changed

**Comment by cvium** [comment]
There's no concept of moving. Only deletions and additions. Without keeping a file hash, jf can't know it's the same file.

It is not a bug.

**Comment by SenorSmartyPants** [comment]
Bug or feature, it doesn't work in a way this user expects. I see a couple ways this could be resolved. 

A file hash wouldn't necessarily be needed if the file name is the same, obviously it would be the same movie or TV episode, even if the resolution changed. 

Or an option could be added to use the file creation or modification time as the time added to JF. 

But neither of those would resolve the other issue that happened, which was that the movies I moved were no longer in the collection they were in before.

**Comment by SenorSmartyPants** [comment]
Apparently this option already existed. I'm not sure if I had it set to use file creation date before when I posted this issue. 
![Untitled](https://user-images.githubusercontent.com/991618/71934377-e74afd80-3169-11ea-9ff3-4987d9a8bffa.png)

**Comment by SenorSmartyPants** [comment]
With this option found I consider this closed. Please reopen if anyone disagrees.
