### ISSUE TITLE
VAAPI connection fails to initialise.

### ISSUE THREAD

**Issue by MLWeber** [jellyfin/jellyfin#2199]
Hi,

I am trying to move over to jellyfin from emby, but I cannot get hw transcoding to work. I am running CentOS 7 with an i7 9700 and try to use VAAPI, but I get the following error:

> ffmpeg version 4.2.1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.4.0-1ubuntu1~18.04.1)
  configuration: --toolchain=hardened --prefix=/usr --target-os=linux --enable-cross-compile --extra-cflags=--static --enable-gpl --enable-static --disable-doc --disable-ffplay --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-libfontconfig --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libwebp --enable-libx264 --enable-libx265 --enable-libzvbi --enable-omx --enable-omx-rpi --enable-version3 --enable-vaapi --enable-vdpau --arch=amd64 --enable-nvenc --enable-nvdec
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[AVHWDeviceContext @ 0x55a995014240] libva: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so init failed
[AVHWDeviceContext @ 0x55a995014240] Failed to initialise VAAPI connection: -1 (unknown libva error).
Device creation failed: -5.
Failed to set value '/dev/dri/renderD128' for option 'vaapi_device': Input/output error
Error parsing global options: Input/output error

I made sure that it is not a permission issue by adding the jellyfin user to the 'video' group. I also temporarily chmodded /dev/dri/renderD128 to 777, just to be sure, but it did not help.
I tried the official docker image, the linuxserver/jellyfin image and the rpm package, but the error is consistent. HW transcoding works fine with plex or emby.

Edit: 
I installed the libva, libva-utils and libva-intel-driver packages from the rpmfusion repo, but they seem to be outdated. I haven't managed to build a recent version yet, but I will try that next.

vainfo gives the following output:

> [root@srv5309 libva-2.6.0]# vainfo
error: can't connect to X server!
libva info: VA-API version 0.40.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib64/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_40
libva error: /usr/lib64/dri/i965_drv_video.so init failed
libva info: va_openDriver() returns -1
vaInitialize failed with error code -1 (unknown libva error),exit

Any assistance in debugging my vaapi issues would be appreciated.

PS: Enabling debug logging does not produce any relevant output.

**Comment by codamon** [comment]
Hello, I've got the same issue, please check it out, thanks.

The environment:
Unraid 6.8.0
CPU 9600K 

> http://192.168.1.90:8096/videos/7523b47a-6224-c62b-2dd7-eb6d827eeb7a/hls1/main/0.ts?DeviceId=TW96aWxsYS81LjAgKE1hY2ludG9zaDsgSW50ZWwgTWFjIE9TIFggMTBfMTRfNikgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzc5LjAuMzk0NS43OSBTYWZhcmkvNTM3LjM2fDE1NzY3NTY0MzczNzE1&MediaSourceId=7523b47a6224c62b2dd7eb6d827eeb7a&VideoCodec=h264&AudioCodec=mp3,aac&AudioStreamIndex=1&VideoBitrate=292000&AudioBitrate=128000&PlaySessionId=8038ee1c04c84755824a06669eac6f01&api_key=715c1c08a3a044abb8b8ecf422a2adf4&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=f6af0825977cdb6c50218b467878b39b&SegmentContainer=ts&MinSegments=2&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51&TranscodeReasons=ContainerBitrateExceedsLimit&allowVideoStreamCopy=false&allowAudioStreamCopy=false
> 
> {"Protocol":"File","Id":"7523b47a6224c62b2dd7eb6d827eeb7a","Path":"/movies/xxxx.mp4","Type":"Default","Container":"mov,mp4,m4a,3gp,3g2,mj2","Size":3754525952,"Name":"MMND-143","IsRemote":false,"ETag":"f6af0825977cdb6c50218b467878b39b","RunTimeTicks":71929856000,"ReadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"RequiresClosing":false,"RequiresLooping":false,"SupportsProbing":true,"VideoType":"VideoFile","MediaStreams":[{"Codec":"h264","CodecTag":"avc1","Language":"eng","TimeBase":"1/29970","CodecTimeBase":"8982241/538391070","VideoRange":"SDR","DisplayTitle":"1080P H264","NalLengthSize":"4","IsInterlaced":false,"IsAVC":true,"BitRate":3974745,"BitDepth":8,"RefFrames":1,"IsDefault":true,"IsForced":false,"Height":1080,"Width":1920,"AverageFrameRate":29.96975,"RealFrameRate":29.97,"Profile":"Main","Type":"Video","AspectRatio":"16:9","Index":0,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"PixelFormat":"yuv420p","Level":40},{"Codec":"aac","CodecTag":"mp4a","Language":"eng","TimeBase":"1/48000","CodecTimeBase":"1/48000","DisplayTitle":"Eng AAC stereo Default","IsInterlaced":false,"ChannelLayout":"stereo","BitRate":194474,"Channels":2,"SampleRate":48000,"IsDefault":true,"IsForced":false,"Profile":"LC","Type":"Audio","Index":1,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Level":0}],"Formats":[],"Bitrate":4175763,"RequiredHttpHeaders":{}}
> 
> /usr/lib/jellyfin-ffmpeg/ffmpeg -hwaccel vaapi -hwaccel_output_format vaapi -vaapi_device /dev/dri/renderD128 -i file:"/movies/xxxx.mp4" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_vaapi  -b:v 292000 -maxrate 292000 -bufsize 584000 -profile:v high -level 41 -force_key_frames:0 "expr:gte(t,0+n_forced*3)" -vf "format=nv12|vaapi,hwupload,scale_vaapi=w=426:h=238" -copyts -vsync -1 -codec:a:0 libmp3lame -ac 2 -ab 128000  -f hls -max_delay 5000000 -avoid_negative_ts disabled -start_at_zero -hls_time 3 -individual_header_trailer 0 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/transcode/transcodes/d448ded406cb0b1640f7e81124a9f377%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/transcode/transcodes/d448ded406cb0b1640f7e81124a9f377.m3u8"
> 
> 
> ffmpeg version 4.2.1 Copyright (c) 2000-2019 the FFmpeg developers
>   built with gcc 7 (Ubuntu 7.4.0-1ubuntu1~18.04.1)
>   configuration: --toolchain=hardened --prefix=/usr --target-os=linux --enable-cross-compile --extra-cflags=--static --enable-gpl --enable-static --disable-doc --disable-ffplay --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-libfontconfig --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libwebp --enable-libx264 --enable-libx265 --enable-libzvbi --enable-omx --enable-omx-rpi --enable-version3 --enable-vaapi --enable-vdpau --arch=amd64 --enable-nvenc --enable-nvdec
>   libavutil      56. 31.100 / 56. 31.100
>   libavcodec     58. 54.100 / 58. 54.100
>   libavformat    58. 29.100 / 58. 29.100
>   libavdevice    58.  8.100 / 58.  8.100
>   libavfilter     7. 57.100 /  7. 57.100
>   libswscale      5.  5.100 /  5.  5.100
>   libswresample   3.  5.100 /  3.  5.100
>   libpostproc    55.  5.100 / 55.  5.100
> [AVHWDeviceContext @ 0x563fbbc98480] libva: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so init failed
> [AVHWDeviceContext @ 0x563fbbc98480] Failed to initialise VAAPI connection: -1 (unknown libva error).
> Device creation failed: -5.
> Failed to set value '/dev/dri/renderD128' for option 'vaapi_device': Input/output error
> Error parsing global options: Input/output error

**Comment by MLWeber** [comment]
Okay I got it working by building the latest versions of libva, libva-utils, intel-vaapi-driver and then jellyfin-ffmpeg myself. I would prefer to use docker but I don't know how I can pass the shared libraries to the container, so I'm using the rpm package for now.

I assume the docker images use outdated libva packages.
