### ISSUE TITLE
chown in docker container can override any directory ownerships on system

### ISSUE THREAD

**Issue by sauerj** [jellyfin/jellyfin#220]
The entrypoint of the docker container changes the permissions of the `/config` and `/media` directory to the environment variables `PUID` and `PGID`.

This can be used to change the ownership of any directory on the system as long the user can run the `docker` command. 
After owning the directory the attacker will be able to read files when the `others` permission allow reading. This is mostly the default setting.

The docker container **should never** change any ownership of volume directories. When the permissions of the config or media volumes are not correct jellyfin should fail with `permission denied`.

Test case: docker-user is allowed to run `docker` command

as `root`
```
mkdir /tmp/root-only
chmod 700 /tmp/root-only
echo super secret > /tmp/root-only/secret
```
as docker-user (1002/1002) who is allowed to run `docker` thru `sudo`
```
sudo docker run -e PUID=1002 -e PGID=1002 -p 8096:8096 -v /tmp/root-only:/config jellyfin/jellyfin
cat /tmp/root-only/secret
super secret
```

**Comment by sauerj** [comment]
I am currently preparing a pull request.

**Comment by sauerj** [comment]
The `sauerj/jellyfin` docker image has the patch applied and running the test described above will result in a failing start with error:

```
Unhandled Exception: System.AggregateException: One or more errors occurred. (Access to the path '/config/logs' is denied.) ---> System.UnauthorizedAccessException: Access to the path '/config/logs' is denied. ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Emby.Server.Implementations.Logging.FileLogger..ctor(String path) in /repo/Emby.Server.Implementations/Logging/SimpleLogManager.cs:line 172
   at Emby.Server.Implementations.Logging.SimpleLogManager.ReloadLogger(LogSeverity severity, CancellationToken cancellationToken) in /repo/Emby.Server.Implementations/Logging/SimpleLogManager.cs:line 52
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAllCore(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at MediaBrowser.Server.Mono.MainClass.Main(String[] args)
Aborted
```

**Comment by anthonylavado** [comment]
@nvllsvm Mind taking a look when you've got a moment?

**Comment by nvllsvm** [comment]
Doesn't matter if it's hidden behind sudo: docker access == root access. 
```
sudo docker run -v /:/host alpine chown -hR 123:456 /host
```

I don't want to remove chown entirely because it breaks using the container without mounting the `/config` volume.

**Comment by nvllsvm** [comment]
I'm working on an alternative.

**Comment by sauerj** [comment]
Okay, I was not aware of this. Well I have still the opinion that the container should not change ownership on the host.

I recognized this when I mounted my jellyfin config from a NFS server without no_squash_root enabled. The permissions and ownership was correct but container start fails because of the chown call.

**Comment by nvllsvm** [comment]
Fix available in the `jellyfin/jellyfin:develop` image. Will be deployed to `latest` eventually.
