### ISSUE TITLE
Jellyfin transcodes/burns in subtitles unnecessarily

### ISSUE THREAD

**Issue by maemigh** [jellyfin/jellyfin#2203]
**Media Info of the file**
.mkv container, h264 video, ac3 audio, ASS subtitles

Jellyfin recognizes TV with the "LG Smart TV" profile. The TV can handle .mkv, h264 video stream and ac3 audio stream, but not with ASS subtitles. SRT style subs are supported (and even listed in the Jellyfin profile). When playing via DLNA, Jellyfin insists on burning in the subtitles (transcoding video). This isn't necessary as a much, much speedier option exists to simply convert only the ASS subs to SRT subs:

`ffmpeg -i in.mkv -c copy -c:s srt out.mkv`

**Server System (please complete the following information):**
 - OS: Docker
 - Jellyfin Version: 10.4.3
 - Hardware settings & device: VAAPI Synology DS218+
 - Reverse proxy: no
 - Other hardware notes: none
 
**Client System (please complete the following information):**
 - Device: LG OLED65C7P
 - OS: webOS
 - Client: webOS

**Comment by EraYaN** [comment]
Well ASS->SRT is a lossy conversion. So that is why it's not done.

**Comment by JustAMan** [comment]
Note that ASS is now supported in master (most likely would be available in 10.5 when it hits), but there were reports of it crashing WebOS browser.

What WebOS version do you have btw?
