### ISSUE TITLE
.lrc External lyrics file support

### ISSUE THREAD

**Issue by adan89lion** [jellyfin/jellyfin#2218]
**Describe the bug**

I created many .lrc synced lyrics files for my music collection, but Jellyfin isn't recognising it.

**To Reproduce**

1. Have a synced lyrics file named the samed as the .mp3 music file.
2. Play music in Jellyfin (Web, Android)
3. No lyrics loaded.

**Expected behavior**

Be able to show lyrics as it is a common feature as a music player.

**Logs**

**Screenshots**

**System (please complete the following information):**
 - OS: Android, Chrome OS
 - Browser: Chrome 79
 - Jellyfin Version: 10.4.3
 - Installed Plugins: No
 - Reverse proxy: nginx (Synology Reverse Proxy)

**Additional context**

**Comment by JustAMan** [comment]
Was it ever supported? If not, this looks like a feature request which belongs here: https://features.jellyfin.org/

**Comment by adan89lion** [comment]
@JustAMan Sorry, I'm new to Jellyfin and I thought it was supposed to support LRC lyrics as it is integrated among most of the music players.

**Comment by JustAMan** [comment]
@adan89lion you can always make a feature request :) just post it to the appropriate service.
