### ISSUE TITLE
Download transcoded Videos 

### ISSUE THREAD

**Issue by spacekookie** [jellyfin/jellyfin#2235]
Sometimes an Internet connection isn't good enough to stream media, or I want to save stuff on my device to see while offline.

I can download videos, but that doesn't help me if my source videos are uncompressed bruray rips at 10G an episode 🙈

So feature request: a download where my server first transcoded it into a different quality. I would like to choose what size and Bitrate to output, then instead of streaming a video, just start a streaming download.

**Comment by anthonylavado** [comment]
Hey there! 👋
We’re aware of the request (it is very popular). We’ll be adding this when we can. You can vote (or make other feature requests) here: https://features.jellyfin.org/posts/284/convert-option-similar-to-plexs-optimise

**Comment by dkerlee** [comment]
Similar to sync for offline l? That’s got to be a request somewhere?

**Comment by pktiuk** [comment]
This feature is now discussed here: https://features.jellyfin.org/posts/57/support-download-of-transcoded-files

**Comment by kevincox** [comment]
The linked feature request isn't the same thing at all. OP is talking about downloading transcoded files while the feature request is talking about eager transcoding on the sever.

Better GitHub issue: https://github.com/jellyfin/jellyfin/issues/1129

It was also moved to a feature request: https://features.jellyfin.org/posts/57/support-download-of-transcoded-files#
