### ISSUE TITLE
No playback with self signed certificates

### ISSUE THREAD

**Issue by devlin016** [jellyfin/jellyfin#2237]
nothing seems to playback via some browsers like the ps4 due to self signed certificates but other browsers like chrome on linux mint doesnt have a problem......i test playback on ps4 via http and everything worked it is something with the certificates... i love the idea of jellyfin but with emby self signed certificates worked never had issues with any thing browsers or kodi app.. i did have issues with it on the android app though but i didnt care about that....

**Comment by JustAMan** [comment]
I'm sorry but I'm kind of disbelieving that on Emby self-signed certificates worked and on Jellyfin they magically stopped, as this is something that is not dependent on which service uses them, but rather on whether remote platform trusts them.

I can believe that Emby app (be it XBox or Android or whatever) just trusts certificates blindly, but if it is so, it's very bad practice which we won't be employing.

So I don't think we can do anything here so far.
