### ISSUE TITLE
Transcoding using VAAPI with burn-in subtitles fails (FFMPEG 4.2.1)

### ISSUE THREAD

**Issue by goncalossilva** [jellyfin/jellyfin#2238]
**Describe the bug**

This is a continuation of #642. I am unable to transcode a regular mp4 + srt, or mkv, or any other video with subtitles, when using VAAPI with subtitle burn-in enabled.

The log ends with:

```
Impossible to convert between the formats supported by the filter 'Parsed_hwupload_1' and the filter 'auto_scaler_0'
Error reinitializing filters!
Failed to inject frame into filter network: Function not implemented
Error while processing the decoded data for stream #0:0
Conversion failed!
```

**To Reproduce**
1. Enable VAAPI and hardware encoding
2. Ensure subtitles are burned-in (e.g. enforce burn-in in subtitles settings, and ensure the profile in use does not support srt)
3. Play a video with subtitles

**System (please complete the following information):**
 - OS: Docker (in a Synology DS218+)
 - Browser: Not in the browser, playing in a Panasonic Viera ST50 with SRT support removed (as it doesn't really support it)
 - Jellyfin Version: 10.4.3
 - Installed Plugins: Anime
 - Reverse proxy: no

**Additional context**
As discussed later in #642, the error is related with the order and the specific parameters that are used when subtitles must be burned in. The current (broken) format is:

`-vf "format=nv12|vaapi,hwupload,subtitles=filename='sub.srt',setpts=PTS -0/TB,hwmap"`

A working format with ~2.5x speed-up is:

`-vf "scale_vaapi,hwmap=mode=read+write+direct,format=nv12,subtitles=filename='sub.srt',setpts=PTS -0/TB,hwmap"`

The changes from the existing (broken) parameter list are:
* Starting with `scale_vaapi`
* Following it with hwmap, particularly `hwmap=mode=read+write+direct`
* Limiting to the `nv12` format (both work, but this is more correct)
* _Not_ including `hwupload`

Everything else is the same. This is very similar to [ffmpeg's samples](https://trac.ffmpeg.org/wiki/Hardware/VAAPI) under "Burn subtitles into the video while transcoding".

I can try patching EncodingHelper.cs, but I am not comfortable with C#, the particular flow in the file, nor the best approach to testing other cases with the fix applied. But if no one else is willing, happy to give it a try. :+1:

**Comment by JustAMan** [comment]
@cryptobank do you want to take a shot since you tackled vaapi recently? :)

**Comment by cryptobank** [comment]
@JustAMan wheres the setting to force burning-in subtitles?

**Comment by cryptobank** [comment]
@goncalossilva can you try running a nightly (2.5.0) to see if the the changes i made already for another different issue also fix this? (we are forcing scale_vaapi already)

**Comment by goncalossilva** [comment]
> @JustAMan wheres the setting to force burning-in subtitles?

User settings -> Subtitles
* Subtitle mode: Always play subtitles

Also, the DLNA profile in use should not have subtitle (i.e. srt) support, enforcing transcoding.

> @goncalossilva can you try running a nightly (2.5.0) to see if the the changes i made already for another different issue also fix this? (we are forcing scale_vaapi already)

I would love to, but I am running this on Synology via Docker. I don't know how else to run it. The latest nightly build for Docker is 3 months old. 😕

**Comment by PrplHaz4** [comment]
> > @goncalossilva can you try running a nightly (2.5.0) to see if the the changes i made already for another different issue also fix this? (we are forcing scale_vaapi already)
> 
> I would love to, but I am running this on Synology via Docker. I don't know how else to run it. The latest nightly build for Docker is 3 months old. 😕

Knew we'd get some mileage out of this. Here's how you can test in docker: https://jellyfin.org/docs/general/contributing/development.html#building-and-testing-inside-a-docker-container

**Comment by goncalossilva** [comment]
Yeah, this is incredibly useful. If it's not fixed on nightly, I can easily test a fix myself. Following it right now, thanks!

**Comment by goncalossilva** [comment]
Unfortunately I cannot test the latest master. The update went fine, and the dashboard shows I'm running 10.5.0, but when I try to connect to it from the TV I get a "Couldn't connect to server" error. Logging doesn't show anything relevant either, only these 2 entries every time there is an error:

```
[2020-01-14 20:51:37.298 +00:00] [DBG] Found matching device profile: "Panasonic Viera"
[2020-01-14 20:51:37.310 +00:00] [DBG] Found matching device profile: "Panasonic Viera"
```

**Comment by PrplHaz4** [comment]
> 
> 
> Unfortunately I cannot test the latest master. The update went fine, and the dashboard shows I'm running 10.5.0, but when I try to connect to it from the TV I get a "Couldn't connect to server" error. Logging doesn't show anything relevant either, only these 2 entries every time there is an error:
> 
> ```
> [2020-01-14 20:51:37.298 +00:00] [DBG] Found matching device profile: "Panasonic Viera"
> [2020-01-14 20:51:37.310 +00:00] [DBG] Found matching device profile: "Panasonic Viera"
> ```

Are you trying to test by connecting with DLNA? If so there's an open issue preventing browsing libraries with DLNA :-/
See Issue: https://github.com/jellyfin/jellyfin/issues/2164

**Comment by goncalossilva** [comment]
Yes, I was. That's how I reproduced the issue in the first place. :/ I've also tried checking out @cryptobank's last commit directly (d063300af481fe385ce1fb61b440217cdd89ef04), but that also fails. I will subscribe to that one and re-test this once it's addressed. Thanks!

**Comment by cryptobank** [comment]
Can you please provide logs

**Comment by goncalossilva** [comment]
Logs are provided above. Regarding the this particular issue, in the OP. Regarding the DLNA issue when trying to test, a couple of comments above (that's all there is from me connecting via DLNA and it failing).

**Comment by cryptobank** [comment]
Can you please provide full ffmpeg log output that includes the changes i've published recently?

**Comment by cryptobank** [comment]
I'm actually having problem trying to force burning subs. I can only test this on the web player. 1) Subtitles -> Always Play Subtitles and Burn Subtitles -> All Complex Formats. I'm using a subrip (SRT) subtitle but I can't force it to transcode. (tried this on both h264 and h265 10 bit). Only tried this on nightly atm.

**Comment by goncalossilva** [comment]
Sorry, but as explained above, I can't test your fix due to #2164. It doesn't even get to a point where I can play a video to pass on the ffmpeg command and output.

**Comment by JustAMan** [comment]
@cryptobank SRT are simple text-only subs, your best bet is using some picture-based ones like PGS.

**Comment by cryptobank** [comment]
@goncalossilva @JustAMan graphical subtitles burning works as expected on 9.5. What I'm trying to test is burning in SRT subtitles as the original post indicated.

> scale_vaapi,hwmap=mode=read+write+direct,format=nv12,subtitles=filename='sub.srt'

**Comment by JustAMan** [comment]
You have to use a client which cannot render any subtitles whatsoever. I think you should be able to hack your web player so it reports that it doesn't support subs... maybe @dkanada has any pointers on how to achieve this?
