### ISSUE TITLE
[bug] Can't call /Items api without UserId

### ISSUE THREAD

**Issue by mregni** [jellyfin/jellyfin#2246]
**Describe the bug**
The GetItems API call (/Items?query=...) has an optional parameter "UserId" but when you call the API without UserId it returns an "Object not set to an instance of an object" exception.

**To Reproduce**
1. Make a call to xxx.xxx.xxx.xxx:xxxx/Items
2. Supply the needed authentication headers
3. Returns "Object not set to an instance of an object"

**Expected behavior**
Returns list of items defined in the query without the need of a UserId.

**Logs**
```
[2020-01-09 12:23:48.455 +01:00] [ERR] Error processing request
System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaBrowser.Api.UserLibrary.ItemsService.GetQueryResult(GetItems request, DtoOptions dtoOptions, User user)
   at MediaBrowser.Api.UserLibrary.ItemsService.GetItems(GetItems request)
   at MediaBrowser.Api.UserLibrary.ItemsService.Get(GetItems request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

**System (please complete the following information):**
 - OS: Windows
 - Browser: Postman
 - Jellyfin Version: 10.4.3
 - Installed Plugins: none
 - Reverse proxy: none

**Additional context**
After looking at the code I think I found the problem.
Problem starts in the MediaBrowser.Api.UserLibrary.ItemService file in the `QueryResult<BaseItemDto> GetItems(GetItems request)` function. First line of that function calls the user manager to fetch the user. If no UserId is provided the user variable is set to null.
2 lines below that the `QueryResult<BaseItem> GetQueryResult(GetItems request, DtoOptions dtoOptions, User user)` is called with the user == null (because I didn't supplied a user id in the query parameters).
The line where it crashes (I guess) is line 216 (` bool isInEnabledFolder = user.Policy.EnabledFolders.Any(i => new Guid(i) == item.Id);`). Since user is null user.Policy will crash the call.

![image](https://user-images.githubusercontent.com/22617019/72065459-8bee4c00-32de-11ea-9f2a-e9f8f28ff203.png)

**Comment by Bond-009** [comment]
AFAIK `GetQueryResult` isn't supposed to be called without a user, would making "UserId" a required parameter fix this issue for you?

**Comment by mregni** [comment]
That would fix the issue yes. But how would you get a list of all media when you only have an API key? I'm creating support for jellyfin in EmbyStat and I just need a list of all media for a certain library. I'm not really bound to a certain user at that point. 

Is there another API I can call to get that info maybe?

**Comment by anthonylavado** [comment]
I figure the reason for this requirement is to ensure that a user only gets information about the libraries they have access to. I’m not sure if there’s another endpoint to work with though.

**Comment by anthonylavado** [comment]
@mregni Is there an endpoint that works for you in Emby right now?

**Comment by dkanada** [comment]
That request sounds like a valid use case so we should probably try to support it.

**Comment by mregni** [comment]
Yes, when I call the /Items endpoint on Emby without userId it returns a list of all items for that parentId.

**Comment by cvium** [comment]
Still not fixed in 10.7

**Comment by nielsvanvelzen** [comment]
UserId is required since #6176.

**Comment by cvium** [comment]
Closing since it has been "fixed".

**Comment by std4453** [comment]
So this means that I have to create some dummy user for API calls? Absurd.

Meanwhile, docs for `/Items` still says `string or null`, I guess that should be replaced?

**Comment by jasongdove** [comment]
I think the current behavior is unexpected and undesirable - an API Key should be able to enumerate items without having to pretend to be a particular user (who may not even exist the next time the API is called).
