### ISSUE TITLE
Fork Anime Plugin

### ISSUE THREAD

**Issue by rangeroob** [jellyfin/jellyfin#225]
Was wondering if this plug-in could get incorporated into the GitHub group. I was using it with emby but sadly it seems not to work with jellyfin

here a the repo: https://github.com/MediaBrowser/Emby.Plugins.Anime

**Comment by JustAMan** [comment]
It could, given it has gpl license. @joshuaboniface @nvllsvm thoughts?

**Comment by joshuaboniface** [comment]
Confirmed GPL - forking.

**Comment by joshuaboniface** [comment]
Forked - https://github.com/jellyfin/jellyfin-plugin-anime

I don't have Anime to test, but PRs welcome!
