### ISSUE TITLE
Regex doesn't allow for years past 2019

### ISSUE THREAD

**Issue by mcarlton00** [jellyfin/jellyfin#2252]
**Describe the bug**
The regex found here doesn't will begin failing on new things added starting in 2020.

https://github.com/jellyfin/jellyfin/blob/0a39e54984ae2eb7ab9ec3382a9122a6de9e56b1/Emby.Naming/Common/NamingOptions.cs#L179

**Comment by Bond-009** [comment]
It's best we wait till #2105 is merged to prevent regressions
