### ISSUE TITLE
Download multiple episodes

### ISSUE THREAD

**Issue by brianjmurrell** [jellyfin/jellyfin#2253]
Downloading episodes from the Jellyfin server to a Jellyfin client is a great feature.  It's tedious to download a season of episodes, or all episodes of all seasons of shows.

It would be useful to have a _Download_ menu item at the Season and Show levels in addition to the existing Episodes menus.

**Comment by chris-echoz** [comment]
It would be very useful to have this option both for individual seasons and entire series. Shouldn't be too demanding on the server side either with a fast algorithm that works on a stream of data. LZ4, for instance.

**Comment by brianjmurrell** [comment]
@jfeversole @hectormartinezdev Can I ask why the thumbs down on this one?  What are your objections?

**Comment by hectormartinezdev** [comment]
I understood that you want Jellyfin to download episodes and I think that
Jellyfin shouldn't do that. I think it should be responsibility of the user
to do that.

However, you also say that this feature is available at the Episode level.
Can you expand on this? Probably I'm not getting this right.

**Comment by Berjou** [comment]
I think that the feature that @brianjmurrell is talking about here is for a jellyfin user to download episodes from a jellyfin instance to its local device, not for jellyfin to download episodes from somewhere on the internet.

**Comment by Shadowghost** [comment]
He requested the possibility to download multiple episodes as a batch from the jellyfin server to his local device instead of manually clicking the download button on every episode one after another.

**Comment by jfeversole** [comment]
I think that's where the confusion came from for both Hector and I. However, I think we are all aware that the reason Brian inquired as to why we reacted that way was to remove the "stale" label rather than any desire to hear our thoughts. Regardless, I've removed the 👎 for a 👍!

**Comment by brianjmurrell** [comment]
@jfeversole No, in fact I did inquire so that I could understand what the objections were.  Clearly my description was unclear and the responses from you and @hectormartinezdev clarified that.  I have clarified  my original description.

I could have just replied with my standard "Piss off stale-bot" response if I was just looking to "unstale" the issue.  :smile:

**Comment by hectormartinezdev** [comment]
I changed my vote too. Thanks for updating the issue!

**Comment by brianjmurrell** [comment]
Anyone?  Can we please have @stalebot not operate on **feature-request** issues as they are feature requests and those tickets will not go stale as they will be closed when the feature code has landed.

**Comment by crobibero** [comment]
Features belong on https://features.jellyfin.org/, not as a github issue.

**Comment by brianjmurrell** [comment]
Why is there a feature-request label then?

**Comment by brianjmurrell** [comment]
Does https://features.jellyfin.org/ provide tracking of feature requests, like subscribing to github tickets, or are they just filed there and no way to know if any updates have been made to the request, such as votes, or it actually being implemented and closed?

**Comment by cvium** [comment]
Please re-open on https://features.jellyfin.org/ if you haven't already.

**Comment by brianjmurrell** [comment]
Go vote!  https://features.jellyfin.org/posts/1130/download-multiple-episodes
