### ISSUE TITLE
[bug] [Backend] No UPNP results when base URL not null

### ISSUE THREAD

**Issue by ThibaultNocchi** [jellyfin/jellyfin#2256]
**Describe the bug**

Hello, I use VLC to browse my library via the UPNP tab on a computer on the same LAN as the server. I also use Nginx to reverse proxy the server so I put a base URL ("/jellyfin/") in Jellyfin' settings. But VLC doesn't find anymore the Jellyfin server. Once I remove the base URL in the settings, it appears in VLC.
**To Reproduce**

1. Set a base URL other than none in Jellyfin' settings.
2. Open VLC on the same LAN, open the UPNP tab and see that Jellyfin doesn't appear.
3. Retry without any base URL, it should work.

**Expected behavior**

I think the server should be discovered even though there is a base URL, but I don't know if it is a technical restriction as I don't know the tech.
**Logs**

DLNA or UPNP doesn't seem to log anything, but maybe I'm looking at the wrong place?

**System (please complete the following information):**
 - OS: DietPi (flavour of Debian) on RPI 4
 - Jellyfin Version: 10.4.3
 - Installed Plugins: OpenSubtitles, TMDB Box Sets, Trakt
 - Reverse proxy: Nginx

Thanks!

**Comment by Bond-009** [comment]
I think this should be fixed in master

**Comment by PrplHaz4** [comment]
The base URL for DLNA issue was fixed in master, but libraries are still not showing up for any DLNA clients. 

https://github.com/jellyfin/jellyfin/issues/2164
