### ISSUE TITLE
"Video Playback Started" Notification to Slack does not respect "Monitor Activity From" selection

### ISSUE THREAD

**Issue by kennyluk** [jellyfin/jellyfin#2262]
**Describe the bug**
Setting up Notification "Video Playback Started" with a "Monitor Activity From" only 1 user will instead monitor activity from all users.

**To Reproduce**

1. Install Slack notification and confirm it is work.
2. Setup Video Playback Started notification for first user and unselect all others (1 out of 4 in our case)
3. Play video on any user other than the user checked in step 2.
4. Notification on slack will still be sent.

**Expected behavior**
1. No notification to slack.

**Logs**
N/A

**Screenshots**
N/A

 - OS: MacOS 10.14.6
 - Browser: Firefox 72.0.1
 - Jellyfin Version: 10.4.3
 - Installed Plugins: Email, IPTV, LDAP, Playback Reporting, Slack, TMDB, Trakt
 - Reverse proxy: Caddy

**Additional context**

**Comment by eltiel** [comment]
Can confirm that the same issue happens with Gotify Notifications.

**Comment by mr-mental** [comment]
Same issue here.

**Comment by eltiel** [comment]
Issue still persists.

**Comment by thisis-mental** [comment]
Issue still persists. 
Annoying as I want to be notified only for my other users not myself :(

**Comment by TraumaGuy** [comment]
Still persists. Same with telegram notification plugin.

Also, same behavior happens with the "video playback stopped" notification.

**Comment by fkieber** [comment]
Same issue with email notification
