### ISSUE TITLE
Allow multiple clients to view a stream

### ISSUE THREAD

**Issue by sparky8251** [jellyfin/jellyfin#227]
I am unsure of how Emby was architected and thus ignorant of how feasible this would be in Jellyfin.

That said, I think it would be quite cool to allow for multiple clients to be at roughly the same point in a stream, allowing you to view the same content at the same time as someone else over the internet is.

Thinking maybe being able to switch to multicasting so the same transcoded frames get sent to every connected party. Maybe an option to toggle who can pause/play/skip (all or just stream owner for example).

Not sure of an easier way to handle this, but right now I use OBS and an RTMP server. Not terribly resource efficient... Would be awesome if one day, if the distant future, Jellyfin supported this natively.

Just referencing #42 to point out that load balancing along with being able to multicast a stream might solve some of the use cases found at scale in addition to distant friends just trying to watch the same episode in lockstep.

**Comment by BobOkisama** [comment]
This would be amazing for something like plextogether... a really cool way a bunch of friends can all gather and watch the same movie without murdering your job. I would love to see this in the future, would be really cool.

**Comment by sparky8251** [comment]
I wouldn't even know where to begin honestly. I'd assume you would have to pick some format and resolution that all clients can work with, but with the number of clients it might be easier to limit to say... the web interface only.

Think once things calm down a bit and more about the underlying code is understood, I'll make an attempt at implementing something like this myself.

**Comment by BobOkisama** [comment]
I assume that it is not currently possible to do a MULTICAST (keep in mind that) stream for anything other than a single resolution, that being whatever you are streaming in. Now if you wanted to have multiple streams and people all time synced, that's totally different. If we wanted to do a multicast with multi-resolutions, I would think your stream would have to actually have all of those resolutions streaming at once, then the client would only display the one they want to use. I would think that should be possible, much like you can have more than one audio stream attached or subtitles, just have you sending say 5 different resolutions at once and they just tune into the one they fits. Should not be too bad if you are direct play with no transcoding going on.

Yeah, so the other way would be just individual streams with a time sync controller everyone is connecting to, that is how plextogether does it I think. Either way, these would be really fun to see.

**Comment by freebsdsa** [comment]
Based on the original post multicast is not even an option for what is being asked. **_You cannot multicast on the public Internet. You can only multicast across the public Internet to another site by using a tunnel that supports multicast._** So this would need to be a unicast based setup. I second the notion of a time sync method instead. Maybe a websocket to sync the video time stamp and even controls to each client in the "shared" stream. So any party can stop/play/FF/RW and everyone would be in sync still.

**Comment by Ryonez** [comment]
This is a feature I'd be very interested in as well.

Atm there's a site called SyncLounge. This site allows multiple people to watch a show together and isn't even restricted to them using the same plex server.

While building this into jellyfin would be difficult, a complimentary standalone service like this could work extremely well. SyncLounge's code is here on [github](https://github.com/samcm/SyncLounge). It is MIT licensed though, so I'm not sure if we're allowed to look at it for ideas on how to do something similar for jellyfin.
