### ISSUE TITLE
Video Crash Upon Import

### ISSUE THREAD

**Issue by dannymichel** [jellyfin/jellyfin#2276]
**Describe the bug**

Playing video will go black and/or stop upon media import on 10.4.2, 10.4.3, and 10.5.
Attached are logs for both 10.4.2 and 10.5 when this happens. 
**To Reproduce**

1. Play a video
2. Import any tv show/movie or full season of a tv show.
3. Video you are currently watching during the import will go black and/or stop

**Logs**
https://www.dropbox.com/s/lnpj6bkfuyz4rrp/jellyfin.zip

**System (please complete the following information):**
 - OS: Ubuntu 18 amd64 native(non docker)
 - Browser: Any
 - Jellyfin Version: 10.4.2/10.4.3/10.5
 - Installed Plugins: None
 - Reverse proxy: nginx

**Comment by Artiume** [comment]
```
[2020-01-13 17:21:34.514 +00:00] [INF] ExecuteQueuedTasks
[2020-01-13 17:21:36.240 +00:00] [INF] Executing "Transcoding temp cleanup"
[2020-01-13 17:21:36.419 +00:00] [INF] "Transcoding temp cleanup" Completed after 0 minute(s) and 0 seconds
[2020-01-13 17:21:36.421 +00:00] [INF] ExecuteQueuedTasks
[2020-01-13 17:21:57.860 +00:00] [INF] "Cache file cleanup" Completed after 0 minute(s) and 46 seconds
[2020-01-13 17:21:57.915 +00:00] [INF] ExecuteQueuedTasks
[2020-01-13 17:22:08.704 +00:00] [INF] Received a SIGTERM signal, shutting down
[2020-01-13 17:22:08.723 +00:00] [INF] Disposing "CoreAppHost"
[2020-01-13 17:22:08.724 +00:00] [INF] Disposing "ActivityLogWebSocketListener"
```
Disable all queued tasks. Once of them is causing the SIGTERM. You watching a video is not part of the failure. You are probably just noticing the failures because you're actively using it.

**Comment by dannymichel** [comment]
How do i disable all queued tasks?

**Comment by dannymichel** [comment]
Wait, this looks familiar. That's me actually stopping jf manually and starting it up again.

**Comment by dannymichel** [comment]
jf isn't crashing itself because when i press the back button and replay the video it only takes about a second to start the video back up. the video just goes black and/or stops and them i have to go back and start it again. those shutdowns are me shutting it down purposely

**Comment by Artiume** [comment]
Alright, new plan. purge all logs and then attempt the failure. Once you get a failure, send me the logs.

**Comment by dannymichel** [comment]
the video going black happened between 6:30pm and 7:15pm around 15 minutes before and after 19:05(24 hour time)

last time i purged all the logs and sent the only log left there upon a video crash i was told ``need all logs not just ffmpeg log``.

when i purge all the logs the only log left is a single ffmpeg log.

**Comment by Artiume** [comment]
can you retest the video and see if the video is the source of the problem? What client was the video playing on? I want that ffmpeg log

**Comment by dannymichel** [comment]
this has been happening for months with different videos.
chrome

**Comment by Artiume** [comment]
ok. since you have proper timestamps, can you send me all ffmpeg logs between 6pm and 8pm

**Comment by dannymichel** [comment]
[YfWccfoGIZNiriXPfxdErnPY.txt](https://github.com/jellyfin/jellyfin/files/4057206/YfWccfoGIZNiriXPfxdErnPY.txt)
[yjGTTkIhCYsVCbCSXAVWXuOP.txt](https://github.com/jellyfin/jellyfin/files/4057207/yjGTTkIhCYsVCbCSXAVWXuOP.txt)

**Comment by Artiume** [comment]
Where is your media located in relation to your server? Cloud, local?

**Comment by Artiume** [comment]
Notes: 

anamorphic ratio
[SAR 1000:1333 DAR 89625:89311], SAR 4:3 DAR 239:134converted to [SAR 4:3 DAR 239:134]

This appears like the stream is cut off from ffmpeg. Network?
video:192903kB audio:4917kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown

similar situation
https://trac.ffmpeg.org/ticket/2754

Expected ending to ffmpeg
```
video:23477kB audio:1106kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
[libx264 @ 0x55e3fccbbe40] frame I:24    Avg QP:23.22  size:100205
[libx264 @ 0x55e3fccbbe40] frame P:1559  Avg QP:25.68  size: 11932
[libx264 @ 0x55e3fccbbe40] frame B:2648  Avg QP:30.48  size:  1146
[libx264 @ 0x55e3fccbbe40] consecutive B-frames:  8.4% 17.9% 19.9% 53.8%
[libx264 @ 0x55e3fccbbe40] mb I  I16..4: 24.0%  0.0% 76.0%
[libx264 @ 0x55e3fccbbe40] mb P  I16..4:  2.5%  0.0%  0.0%  P16..4: 29.4%  0.0%  0.0%  0.0%  0.0%    skip:68.2%
[libx264 @ 0x55e3fccbbe40] mb B  I16..4:  0.1%  0.0%  0.0%  B16..8:  5.1%  0.0%  0.0%  direct: 1.8%  skip:93.1%  L0:38.9% L1:36.8% BI:24.3%
[libx264 @ 0x55e3fccbbe40] coded y,uvDC,uvAC intra: 75.6% 54.4% 31.1% inter: 5.6% 3.4% 0.4%
[libx264 @ 0x55e3fccbbe40] i16 v,h,dc,p: 23% 50% 17% 10%
[libx264 @ 0x55e3fccbbe40] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 19% 26% 12%  9%  8%  5%  6%  7%  7%
[libx264 @ 0x55e3fccbbe40] i8c dc,h,v,p: 34% 38% 22%  6%
[libx264 @ 0x55e3fccbbe40] Weighted P-Frames: Y:0.0% UV:0.0%
[libx264 @ 0x55e3fccbbe40] kb/s:2724.66
```

FFmpeg is at fault for some reason. Are you building or using repository?

**Comment by dannymichel** [comment]
heres a brand new crash for you
[ffmpeg-remux-63cffc8d-20a7-4e56-b802-3d764fccdb12.txt](https://github.com/jellyfin/jellyfin/files/4057281/ffmpeg-remux-63cffc8d-20a7-4e56-b802-3d764fccdb12.txt)
[ffmpeg-transcode-b6666cdd-46fb-4a71-bf71-768eec112c13.txt](https://github.com/jellyfin/jellyfin/files/4057282/ffmpeg-transcode-b6666cdd-46fb-4a71-bf71-768eec112c13.txt)
[jellyfin.log](https://github.com/jellyfin/jellyfin/files/4057284/jellyfin.log)

**Comment by dannymichel** [comment]
> Where is your media located in relation to your server? Cloud, local?

rclone mount/mergerfs

**Comment by Artiume** [comment]
First one failed. Second one looks good. Yeah, I think it might be network related. what's your speed connection?

**Comment by dannymichel** [comment]
i'm on ovh gigabit

**Comment by dannymichel** [comment]
wouldn't a fix for this(if this is what is happening) be to somehow make jellyfin hold a moment before it goes black or stops when the source isnt being read anymore?(especially considering how many people now and in the future will be mounting cloud)?

**Comment by Artiume** [comment]
It appears to be affecting the remuxes more than transcodes. If it is due to being over the network, the limitation lies within ffmpeg. Limiting bitrate would kill two birds with 2 stones, limitiing the bitrate and forcing it to transcode. that's no real solution though :P. A few more crash logs should confirm it. 

The anamorphic ratio weirds me out too, but if that was buggy, it would be seen more visually, not with a stream failing.

**Comment by dannymichel** [comment]
i see

**Comment by Artiume** [comment]
Send me your mergerfs command, I want to see if I can improve it

**Comment by dannymichel** [comment]
```
/usr/bin/mergerfs /home/user/local:/mnt/drive /mnt/mergerfs -o rw,async_read=false,use_ino,allow_other,func.getattr=newest,category.action=all,category.create=ff,cache.files=partial,dropcacheonclose=true
```

**Comment by Artiume** [comment]
So a few of my options are older but I haven't had issues with it so I haven't changed it. I mount mine in fstab so i have the nonempty so i can live mount it when i add additional drives. the 0 0 is for fstab.

`
/mnt/disc1:/mnt/disc2 /home/artiume/shared fuse.mergerfs direct_io,use_ino,atomic_o_trunc,big_writes,default_permissions,splice_move,splice_read,splice_write,allow_other,sync_read,minfreespace=15G,umask=022,uid=1000,gid=1000,fsname=union,nonempty 0 0
`

**Comment by dannymichel** [comment]
"It looks like you have an old version as you have many old options set that are replaced and a ton of defaults that aren't needed."
<img width="851" alt="Screen Shot 2020-01-14 at 7 08 56 AM" src="https://user-images.githubusercontent.com/1161544/72343475-f1ef2080-369c-11ea-8d81-8cca57a895d0.png">

**Comment by Artiume** [comment]
I definitely need to upgrade my parameters, but it works lol.
```
artiume@noder:~$ mergerfs --version
mergerfs version: 2.21.0
FUSE library version: 2.9.7
fusermount version: 2.9.7
using FUSE kernel interface version 7.19
```
Any more issues so far?

**Comment by dannymichel** [comment]
no more issues than the one i currently have.

**Comment by Artiume** [comment]
Try my mergerfs and see what happens. Mine is a known working configuration even if yours is newer. I need to eliminate possibilities if you want to fix this.

**Comment by JustAMan** [comment]
@dannymichel is there any chance that not only your media, but some other JF files (like transcoding temp or /var/lib/jellyfin) are also network-mounted?

**Comment by JustAMan** [comment]
This line
```
[2020-01-14 04:03:58.084 +00:00] [WRN] HTTP Response 204 to "162.158.63.20". Time (slow): 0:01:43.821912. "http:///Sessions/Playing/Progress"
```
looks _very_ suspicios - it took almost two minutes for your JF server to respond to a simple request.

**Comment by dannymichel** [comment]
> @dannymichel is there any chance that not only your media, but some other JF files (like transcoding temp or /var/lib/jellyfin) are also network-mounted?

nothing but my library is network mounted



> This line
> 
> ```
> [2020-01-14 04:03:58.084 +00:00] [WRN] HTTP Response 204 to "162.158.63.20". Time (slow): 0:01:43.821912. "http:///Sessions/Playing/Progress"
> ```
> 
> looks _very_ suspicios - it took almost two minutes for your JF server to respond to a simple request.

why do you think this happened?

**Comment by JustAMan** [comment]
No idea, but that's something definitely not right. Maybe @Bond-009 or @cvium have any ideas...

**Comment by Bond-009** [comment]
Depends, how many user account does the instance have?

**Comment by dannymichel** [comment]
> Depends, how many user account does the instance have?

2 accounts

**Comment by dannymichel** [comment]
i just did 2 things: 1. installed a fresh install and scan on my mac using rclone to mount without mergerfs, scanned, and got black screen. 2. asked my friend to do the same thing on his windows machine, scanned while watching his own video and got black screen... What this shows me is that no matter what the OS or machine, rclone mount or rclone/mergerfs mount.... Scanning media libraries while watching a video WILL give you black screen no matter what your system config is. Furthermore, as we know from previous GitHub 'issues', there are no logs(debug mode or not) that support this. It's just a thing that happens. It took us about 3 hours between the 2 of us to reproduce this(again... ive shared logs before but the event is undetectable). Now everyone can chose to write this off as 'oh well its just his setup' or understand/know that this is a huge bug and begin troubleshooting what it can possibly be knowing there are no logs that they can use to troubleshoot

**Comment by Artiume** [comment]
This is what I use to monitor my system, found a link for mac
https://becomethesolution.com/blogs/mac/how-to-install-glances-eye-on-your-system-mac-os-x

**Comment by Artiume** [comment]
I believe this might be fixed with this. https://github.com/jellyfin/jellyfin/pull/2365

**Comment by dannymichel** [comment]
I can test this by pulling jellyfin/jellyfin:beta or would i have to build?

**Comment by Artiume** [comment]
I believe the nightly will be ready around 3 am est. You'll have to build if you want to test it today.

```
All package builds begin with these two steps:

Clone the repository:
git clone https://github.com/jellyfin/jellyfin.git
cd jellyfin

Initialize the submodules:
git submodule update --init

Docker

Build the Docker image:
docker build -t $USERNAME/jellyfin .

```

**Comment by dannymichel** [comment]
I dont know enough to understand how that one line of code can fix so many issues including mine and those other 2, bit i will test this.

**Comment by Artiume** [comment]
So here's my theory. On a non-server edition of windows, you're allowed to open up 16 tcp connections at once. I think that because of the missing certificates, your computer opens  a tcp connection but it fails to connect. Then it subsequently fails to close the tcp connections. At which point, you reach your tcp connection limit and it starts closing others to open new ones. Just a theory.

**Comment by dannymichel** [comment]
Video stopped(not black screen like on 10.4, but stopped) on a fresh install/scan.
```
docker run -d \
--volume /home/myusername/.config/docker/jellyfin:/config \
--volume /home/myusername/.cache/jellyfin:/cache \
--volume /mnt/mergerfs/media:/media \
--user 1000:1000 \
--publish 8098:8096 \
--publish 8928:8920 \
--restart=unless-stopped \
myusername/jellyfin:latest
```

**Comment by Artiume** [comment]
Hmm, well that's different. Was hoping it'd fix it. I'm not versed in windows troubleshooting, but i'm sure there's logs reporting something useful

**Comment by dannymichel** [comment]
It is very different. Video stopping but not black screen is something I haven't seen. Might the fact that jellyfin is rendered almost impossible to browse during scans an imports have something to do with whatever issue this is?

**Comment by Artiume** [comment]
Do you run this on an hdd or ssd?

**Comment by dannymichel** [comment]
SSD

**Comment by dannymichel** [comment]
Intel Xeon E3-1230v6 - RAM 32GB LEG - 2x 2TB SATA Datacenter Class Soft RAID

And yes, I set data=writeback and made the nesesary changes to etc/sysctl.conf and etc/limits.conf

My setup is flawless, fast and performs amazingly during high internet activity and/or disk I/O

**Comment by Artiume** [comment]
So with the browser is locking up, that sounds like io. Did you try out glances? It might let you know of any bottlenecks you could make a ram disk if you can spare the ram. 

I don't know raid so I wouldn't know. Not sure what data=writeback does lol. 

Perhaps this is related

**Comment by dannymichel** [comment]
i actually did try out glances more so because i like the idea of it than troubleshooting for this.
using it for this wouldn't apply because my friend and people on my discord server are on different machines and operating systems and they are getting black screen and/or video stops themselves.

**Comment by dannymichel** [comment]
but yes, with my limited knowledge, i feel like the video stop/black screen is fully a jellyfin ffmpeg issue, while the slow browsing during import is another issue

**Comment by Artiume** [comment]
So if there's an oi issue, it can cause any program to halt. you could try running emby/plex while importing on jellyfin. if it does, it isolates it to the jf scanning behavior

You can put glances on any OS with pip. I still think it's useful for troubleshooting this, you just might not know what to look for, or it might not show itself, just more data points. Wouldn't hurt to keep it around.
https://glances.readthedocs.io/en/stable/install.html

**Comment by Artiume** [comment]
When the new linuxserver jellyfin nightly comes out, try that image as well

**Comment by dannymichel** [comment]
This seems to have been partially fixed. I'm not getting video stops as often as before.

**Comment by dannymichel** [comment]
fixed in https://github.com/jellyfin/jellyfin/pull/2379
