### ISSUE TITLE
Permissions issue when transferring to MergerFS

### ISSUE THREAD

**Issue by GideonWolfe** [jellyfin/jellyfin#2280]
**Describe the bug**

When I attempt to launch jellyfin in docker while mounting volumes located at a mergerFS store, I receive errors about read only permossions

**To Reproduce**

1. Set up jellyfin with regular filesystem
2. Create mergerfs pool at `/data` where ALL my media is located
3. Change docker volume mounts to point at media on `/data`
4. Restart JF

**Expected behavior**

Jellyfin  starts normally because the files mounted inside the container should be *exactly the same*.

**Logs**

```
[08:44:17] [INF] Loading assemblies
[08:44:18] [FTL] Error while starting server.
ReadOnly: SQLitePCL.pretty.SQLiteException: attempt to write a readonly database
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
   at SQLitePCL.pretty.StatementImpl.MoveNext()
   at SQLitePCL.pretty.DatabaseConnection.Execute(IDatabaseConnection This, String sql)
   at Emby.Server.Implementations.Data.BaseSqliteRepository.GetConnection(Boolean _)
   at Emby.Server.Implementations.Security.AuthenticationRepository.Initialize()
   at Emby.Server.Implementations.ApplicationHost.GetAuthenticationRepository()
   at Emby.Server.Implementations.ApplicationHost.RegisterResources(IServiceCollection serviceCollection)
   at Emby.Server.Implementations.ApplicationHost.InitAsync(IServiceCollection serviceCollection)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
[08:44:19] [INF] Disposing CoreAppHost
[08:44:19] [INF] Received a SIGTERM signal, shutting down

```

Now if I try to switch back to the old docker compose file, which mounts the same files but NOT the ones located at the `mergerFS` pool, Jellyfin container hangs without exiting at this message:

```
[08:52:16] [INF] Setting cache path to /cache
[08:52:16] [INF] Loading assemblies
```
So I can't start it whatsoever!

**Screenshots**

**System (please complete the following information):**
 - OS: [e.g. Docker, Debian, Windows]: Ubuntu 18.04 (running n docker compose)
 - Browser: [e.g. Firefox, Chrome, Safari] FF
 - Jellyfin Version: [e.g. 10.0.1] Latest docker image
 - Installed Plugins: [e.g. none, Fanart, Anime, etc.] None
 - Reverse proxy: [e.g. no, nginx, apache, etc.] Traefik

**Additional context**

I tried to fix this error in my JF directory by changing permissions and... I messed *everything up*. I set the whole thing up in a new folder system, *then* created my mergerFS pool, but now it says those same files are read only?

**Comment by sarbian** [comment]
SQLite requires mmap. MergerFS needs some specific config for mmap to work. Did you do that config ? ( see https://github.com/trapexit/mergerfs#plex-doesnt-work-with-mergerfs )

**Comment by GideonWolfe** [comment]
Ah, looks like that part was left out of seemingly every tutorial on the internet :roll_eyes: will I get any negative effects from disabling `direct_io`?

**Comment by sarbian** [comment]
The file memory cache is less efficient but there are ways to mitigate it and honestly I did not notice a difference. Read the "page caching" section on the same MergerFS page to have more information. 
mmap is required for many apps anyway so you may not have a choice.

**Comment by GideonWolfe** [comment]
Gotcha. Looking at the page it looks like `direct_io` is deprecated anyways, and I never even explicitly enabled it...

**Comment by JustAMan** [comment]
I'm sorry but I fail to see why this is an issue with Jellyfin :)

**Comment by GideonWolfe** [comment]
@JustAMan I now know that it isn't, I just suspected it was since Jellyfin was the only container complaining about the new setup! Seems to be fixed now, I moved the database off of the MergerFS pool.

**Comment by LennyLip** [comment]
same issue with fresh installer/jellyfin_10.7.6_windows-x64.exe

**Comment by SMooxx** [comment]
Any clue on how to make jellyfin work under mergerFS?

Describe the bug

When I attempt to launch jellyfin on Ubuntu 20.04 while mounting volumes located at a mergerFS pool, I could get jellyfin scan the media folder.

To Reproduce

1. Set up jellyfin with regular filesystem
2. Create mergerfs pool at /home/user where ALL my media is located in /home/user/rtorrent/download. I have 4 hard drivers (/dev/sdb, dev/sdc, dev/sdd, dev/sde). And I use mergerfs to merge them into a 44TB pool.
![image](https://user-images.githubusercontent.com/9960618/151947554-48b51fb3-7c57-42e1-9c7f-57f0af1fe0cd.png)
and My mergerfs option is as follows.
`/mnt/sd* /home/user fuse.mergerfs defaults,nonempty,allow_other,use_ino,minfreespace=150G,ignorepponrename=true,cache.files=partial,dropcacheonclose=true,category.create=mfs,fsname=mergerfs 0 0`
3. Add jellyfin to **user** group and `sudo setfacl -R -m u:jellyfin:rx /home/user/rtorrent/download` to make sure jellyfin has the right permission.

but jellyfin can't scan the media folder (/home/user/rtorrent/download) at all. 
every time I tried to add /home/user/rtorrent/download to jellyfin, it got blank.
![image](https://user-images.githubusercontent.com/9960618/151948800-0eb758db-88cd-4abb-9e9a-bd8935632d7d.png)


I can only add the folders one by one like this into jellyfin, then it can scan and add them to the library.

> /mnt/sdb/rtorrent/download
> /mnt/sdc/rtorrent/download
> /mnt/sdd/rtorrent/download
> /mnt/sde/rtorrent/download


any clude to fix this? Thanks.

**Comment by Shadowghost** [comment]
The Jellyfin user does not only need access to `/home/user/rtorrent/download` but also (by user, group or other) requires r+x access to any folder above the location (`/home`, `/home/user` and `/home/user/rtorrent`).

**Comment by BlackDub** [comment]
> The Jellyfin user does not only need access to `/home/user/rtorrent/download` but also (by user, group or other) requires r+x access to any folder above the location (`/home`, `/home/user` and `/home/user/rtorrent`).

After looking 500 post, this fixed my problem! Change permissions of **ABOVE** (each disk) location work!
