### ISSUE TITLE
homepage still shows nightly docker image

### ISSUE THREAD

**Issue by fightforlife** [jellyfin/jellyfin#2285]
**Describe the bug**

**To Reproduce**

1. Go to https://jellyfin.org/downloads/  
-> nightly docker image is shown
2. Go to https://hub.docker.com/r/jellyfin/jellyfin/tags?page=1&name=nightly&ordering=last_updated
-> last nightly build is 3 months ago

**Expected behavior**
Nightly docker image is build "nightly" or website doesnt give option for nightly docker image.

**Just to be sure no user use these nightly builds to verify some PRs.**

**Comment by dkanada** [comment]
I don't think this is an issue. It's true the docker nightly is broken right now but that's exactly why we advertise nightly as a development build that shouldn't be run for stability.

**Comment by JustAMan** [comment]
Homepage showing nightly is not an issue, nightly being broken is :)
Hopefully fixed by https://github.com/jellyfin/jellyfin/pull/2286
