### ISSUE TITLE
there's a green bar at bottom of screen while playing on Chrome

### ISSUE THREAD

**Issue by ss1969** [jellyfin/jellyfin#2292]
**Describe the bug**
Jellyfin newest version, play back at chrome v79.0.3945.117 , windows 10 1909, nvidia 1080 graphics card. using hardware transcode @ VAAPI. x264 source works fine, but x265 10bit source will have a greenbar like this.
firefox / andorid client works fine. this must be a chrome issue.

**To Reproduce**
try play back on chrome as described above.

**Expected behavior**
no green bar.

**Logs**
ffmpeg: 
http://klym.top:8096/System/Logs/Log?name=ffmpeg-transcode-737c8de9-e28d-4746-8348-fb6ff7cfa3ca.txt&api_key=646a0a63351441ed9d6fd6be63c7fb1d

**Screenshots**
![eyodl1rkvpa41](https://user-images.githubusercontent.com/1011526/72606222-401b5280-392f-11ea-9222-eb3ef141d121.jpg)

**System (please complete the following information):**
 - OS: win10 1909
 - Browser: chrome v79.0.3945.117
 - Jellyfin Version: 10.4.3
 - Installed Plugins: none
 - Reverse proxy: none

**Additional context**
some discussion here： 
https://www.reddit.com/r/jellyfin/comments/eoja6t/why_theres_a_green_bar_at_bottom_of_screen_while/

**Comment by barolo** [comment]
@ss1969 it's a vappi/driver [ it always confuses me where in the stack it actually belongs ] whatever bug, same shit happens on recent AMD with 10bit hevc

**Comment by JustAMan** [comment]
If it's resolution which borks `h264_vaapi` we can make it pad to needed one.
@ss1969 can you provide mediainfo of problematic file?

**Comment by WhereDoesTheCodeGo** [comment]
Created an account just to discuss this! Hi! Anyways the issue as far as I can tell is (for intel QuickSync anyways) is that the dimensions of the output file from ffmpeg has to be a multiple of 16, so for example 1080 / 16 = 67.5, which causes this issue. I would think rounding up or down and passing those dimensions would fix it. 

More info is discussed here:
https://software.intel.com/en-us/forums/media/topic/735761

**Comment by smidley** [comment]
I'm having this same issue when playing via the Android TV app on an nvidia shield TV.

**Comment by JustAMan** [comment]
@nyanmisaka could you please take a look? (pinging here after Matrix discussion)

**Comment by WhereDoesTheCodeGo** [comment]
Bumping this as I am hoping this might be a simple fix, I would really love to use QuickSync for transcoding but this is making me pump the breaks.

**Comment by barolo** [comment]
Is this related? https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/4184
There seems to be an issue with hevc cropping, fix is still in pipeline
