### ISSUE TITLE
Docker Hub Nightly builds are all amd64

### ISSUE THREAD

**Issue by SenorSmartyPants** [jellyfin/jellyfin#2296]
**Describe the bug**
Nightly builds are all AMD64. There are no ARM or ARM64 builds.

**To Reproduce**

1. Go to https://hub.docker.com/r/jellyfin/jellyfin/tags
2. Scroll down to nightly
3. See error

**Expected behavior**

All arch should be built and deploed.

**Screenshots**

https://hub.docker.com/r/jellyfin/jellyfin/tags
![image](https://user-images.githubusercontent.com/991618/72645215-af497480-3938-11ea-8985-6713c244a875.png)

**Comment by PrplHaz4** [comment]
Probably related: https://github.com/jellyfin/jellyfin/pull/2286#issuecomment-575474196

**Comment by Artiume** [comment]
This should be fixed

**Comment by SenorSmartyPants** [comment]
New nightly builds are all still marked amd64.

**Comment by Artiume** [comment]
Yeah, noticing that. It was supposed to be fixed by https://github.com/jellyfin/jellyfin/pull/2302 but it appears not.

**Comment by anthonylavado** [comment]
Paging @nvllsvm

**Comment by SenorSmartyPants** [comment]
Any progress on this? I still can't pull ARM nightlys.

**Comment by Artiume** [comment]
Fixed.

```
a829d4c03c49 linux/amd64 184.57 MB
1bf8ba5f746a linux/arm 196.72 MB
1e33434011fb linux/arm64 204.89 MB
```
