### ISSUE TITLE
No builds for ubuntu eoan after 10.4.0

### ISSUE THREAD

**Issue by olskar** [jellyfin/jellyfin#2298]
**Describe the bug**
When running Ubuntu Eoan Ermine it is not possible to update jellyfin beyond 10.4.0. 
I am not sure why this is, but if I change eoan in my sources.list to bionic, 10.4.3 gets installed

**To Reproduce**
Run Ubuntu 19.10
Add repository according to instructions in https://jellyfin.org/docs/general/administration/installing.html#ubuntu
sudo apt update
sudo apt install jellyfin

**Expected behavior**
Latest version should be installed

**System (please complete the following information):**
Ubuntu 19.10

**Comment by uchagani** [comment]
With 10.5.0 being released can we get a build for this please?

**Comment by joshuaboniface** [comment]
Fixed.

```
$ sudo reprepro -b /srv/repository/ubuntu list eoan
eoan|main|amd64: jellyfin 10.5.0-1
eoan|main|amd64: jellyfin-ffmpeg 4.2.1-5-eoan
eoan|main|armhf: jellyfin 10.5.0-1
eoan|main|arm64: jellyfin 10.5.0-1
```
