### ISSUE TITLE
Replace links to https://emby.media 

### ISSUE THREAD

**Issue by LogicalPhallacy** [jellyfin/jellyfin#23]
As part of the overall renaming, lots of links direct to https://emby.media for no particular reason. Those should be redirected to either a website for jellyfin (long term, to enable using them as documentation and proper service links) or to this GitHub project (short term, just to prevent confusion)

**Comment by JustAMan** [comment]
I'd say let them point to Wiki for now... Any volunteers for cleaning stuff up?

**Comment by anthonylavado** [comment]
I have plans to do this this evening.

**Comment by LogicalPhallacy** [comment]
I'll leave it to you then, if you'd rather not I'm willing to as well. Note that we might want to (as part of this effort) relink the images that are sourced from the emby GitHub to ones sourced from this as well.

**Comment by joshuaboniface** [comment]
Subtask of #25
