### ISSUE TITLE
TVDB Season poster image search results displayed twice

### ISSUE THREAD

**Issue by SenorSmartyPants** [jellyfin/jellyfin#2301]
**Describe the bug**
JF is duplicating season poster results from TVDB

**To Reproduce**

1. Select a TV Season
2. Edit Images,Primary image search
3. See duplicate posters.

**Expected behavior**

Only display images once.

**Screenshots**

TVDB season posters
![image](https://user-images.githubusercontent.com/991618/72670771-29e0c580-3a07-11ea-9f56-ce701f8b806b.png)

JF search results
![image](https://user-images.githubusercontent.com/991618/72670767-20575d80-3a07-11ea-896b-0c7801f3a1c7.png)

**System (please complete the following information):**
 - OS: Docker
 - Browser: Chrome
 - Jellyfin Version: 10.4.1
 - Installed Plugins: Fanart
 - Reverse proxy: no

**Additional context**

**Comment by SenorSmartyPants** [comment]
This issue doesn't appear on all series. The Venture Bros has been confirmed by me. Not sure if this is a JF or TVDB issue at the moment.

**Comment by SenorSmartyPants** [comment]
I think this maybe related to the fact that Venture Bros has an official season 1 and a DVD season 1, both with the same set of posters

https://www.thetvdb.com/series/the-venture-bros/seasons/official/1
https://www.thetvdb.com/series/the-venture-bros/seasons/dvd/1

I haven't figured out how to pull info directly from TVDB API to see what is the direct response.

**Comment by dkanada** [comment]
It sounds like that might be the issue to me.
