### ISSUE TITLE
[Feature] Add sentry for optional error tracking

### ISSUE THREAD

**Issue by cromefire** [jellyfin/jellyfin#2306]
I'd like to propose to add [Sentry](https://docs.sentry.io/platforms/dotnet/) to allow catching had-to-catch errors from "production" instances (especially if they don't show up in the logs).

I'd like there to be just an option in the web ui or in some config file to add a dsn.

If you don't give it a dsn it just does nothing.

**Comment by JustAMan** [comment]
Note that we track feature requests here: https://features.jellyfin.org/

**Comment by cromefire** [comment]
https://features.jellyfin.org/posts/416/add-sentry-for-optional-error-tracking
