### ISSUE TITLE
[Question/Feature Request] multiple rating sources and uniqueids in nfo

### ISSUE THREAD

**Issue by accountForIssues** [jellyfin/jellyfin#2308]
I don't know if this has been done and in a future release but I use tinyMediaManager to scrape my media before importing it to jellyfin.

The great thing about tMM is not only is it fast but it allows instant fine grained editing of various parameters. Anyways, one of things I can do is have multiple ratings. They write multiple ratings to the nfo in the Kodi format.
```
<ratings>
     <rating default="false" max="10" name="trakt">
       <value>7.39136</value>
      <votes>787</votes>
    </rating>
     <rating default="true" max="10" name="rottenTomatoes">
       <value>87</value>
      <votes>99</votes>
    </rating>
</ratings>
```

Currently, Jellyfin only sees <rating> and <criticrating> and ignores the other tags.

It also ignore <uniqueid> tags as well:
```
  <uniqueid default="false" type="tmdb">348</uniqueid>
  <uniqueid default="true" type="imdb">tt0078748</uniqueid>
  <uniqueid default="false" type="tmdbSet">8091</uniqueid>
```

and adds its own tags 
```
  <imdbid>tt0078748</imdbid>
  <tmdbid>348</tmdbid>
```

It would be great to see it support these additional tags. I also have my own rotten tomatoes scraper for TV shows as well so it would be awesome to see a "tomato" and a "popcorn" score. You can have different kinds of "icons" for each rating type.

It seems that Emby supports these new tags via Nfometadata plugin with a fairly recent [update](https://emby.media/community/index.php?/topic/74558-nfo-files-uniqueid/).

Is there something like the plugin in the works or are these new tags to be supported in the future ?

**Comment by haschmich** [comment]
I'm also using tinyMediaManager because it's by far the easiest and most comfortable way I've seen to keep metadata in check. I am facing the same problem as the OP and would love to see Jellyfin support the ratings structure as outlined above.

**Comment by ne0phyte** [comment]
+1
The missing ratings currently keep me from using NFOs. Would be great if JF could pick up ratings and uniqueids from NFOs.

See https://kodi.wiki/view/NFO_files/Movies#Movie_nfo_Tags

**Comment by micha910** [comment]
Same here, I would wish it too that jellyfin to be able to read the rating tags in nfo files.

**Comment by advarksauce** [comment]
Yes please this would be great to support multiple ratings. I would love to see all the ratings or at least be able to tell which rating service it pulled it from (instead of generic community/critic rating)

**Comment by felix920506** [comment]
Please submit feature requests to https://features.jellyfin.org
