### ISSUE TITLE
Feature request: kodi library integration

### ISSUE THREAD

**Issue by fullmetal1** [jellyfin/jellyfin#2310]
This is probably a really complicated flow and has only one use case and that use case is well out of the norm, but basically the idea is that if kodi and jellyfin are on the same machine, then jellyfin has the ability to read the kodi db and import its TV show list/movie list/watched flag/etc and sync additions back to kodi.

**Comment by JustAMan** [comment]
I don't understand why you want to specialize this thing, we already have this scenario working for the (more complex) case of when Kodi is running on a separate device. Adding support for this one requires a lot of work with very low benefit.

I would advise you to use https://github.com/jellyfin/jellyfin-kodi/ and https://github.com/jellyfin/jellyfin-plugin-kodisyncqueue plugin like other Kodi guys do, and ignore the fact that you host Kodi and JF on the same machine.

**Comment by fullmetal1** [comment]
I didn't know how well jellyfin-kodi integrates into kodi. showing movies and tv shows in the library is a Godsend. I can just use jellyfin for the database functionality, and turn kodi into a client for jellyfin, instead of using kodi to store db information on its own.

Closing because feature already implemented
