### ISSUE TITLE
Once an album is assigned to an artist, there is no way to change such assignment

### ISSUE THREAD

**Issue by gnattu** [jellyfin/jellyfin#2315]
**Describe the bug**

The Album Artist still show up as the old value even though all files in the folder has changed their metadata to the new value.
**To Reproduce**

1. Import an album into Jellyfin
2. Change the album artist embedded in the music files to a new value
3. Refresh the Library
4. The old album artist still shows the old value.

**Expected behavior**

The album artist should be the new value, not the old one

**Logs**

**Screenshots**

**System (please complete the following information):**
 - OS: Windows Server 2019
 - Browser: Safari included in iOS
 - Jellyfin Version: 10.4.3
 - Installed Plugins: Anime
 - Reverse proxy: nginx

**Additional context**

Current(dirty) workaround is to rename the folder or rename all music files, to let Jellyfin thought those files are "new" ones, not the ones that is "imported".

**Comment by dkanada** [comment]
I believe the same issue exists for genres, have you seen this at all?

**Comment by azndante** [comment]
I am looking for a way to change this other than retagging and refreshing metadata from files again.

**Comment by asp1re7** [comment]
Its very annoying. This issue is still persists. I can't change the artists. For Ex. I have three Hans Zimmers in my artists list and the albums show up separately to each of the artists. Also trying to assign the correct Artist at the metadata editor under People doesn't work. The data is not saved. When I open the metadata editor again it resets the assigned artists under People.

**Comment by gitdev-bash** [comment]
This issue still persists. I can't change the album artist anywhere. Musicbrainz has the correct value, but somehow i am getting a completely random value for a single album. Also i can't seem change the value anywhere in the GUI. Editing the NFO file causes Jellyfin to overwrite it again to the random value.

**Comment by NetBUG** [comment]
Hi
I see the same issue. 
I've got a messy collection; Jellyfin is able to group something together, but there is no explicit way to change artist title for all files that got into some selection.

The interface shows the list of all possible __Artist__ field values grouped together, but there is no way to go to **Edit metadata** and update Artist/Genre fields for all files in selection.
<img width="785" alt="image" src="https://github.com/user-attachments/assets/1c94c45f-d155-4ca4-9a20-644b0b090316">

That would also be useful in case ID3 tags have been written in a wrong encoding, and I'd like to bulk convert **H\xe4matom** to **Hämatom**.

<img width="929" alt="image" src="https://github.com/user-attachments/assets/1d0dc7aa-5d2d-42fd-b7a4-b14e0ef0a724">

**Comment by felix920506** [comment]
Please open a new report.
