### ISSUE TITLE
DLNA debug messages not logged

### ISSUE THREAD

**Issue by PrplHaz4** [jellyfin/jellyfin#2317]
**Describe the bug**

Logging statements in [BaseControlHandler.cs](https://github.com/jellyfin/jellyfin/blob/master/Emby.Dlna/Service/BaseControlHandler.cs) do not make it to the log or console.

**To Reproduce**

1. Turn on DLNA debug logging and set log level to "Debug" in logging.json
2. Restart Jellyfin
3. Connect to Jellyfin via DLNA
4. Do not see any control messages logged

**Expected behavior**

DLNA control messages are logged.

**Logs**

**Screenshots**

**System (please complete the following information):**
 - OS: Docker
 - Browser: Firefox
 - Jellyfin Version: 10.4.3, 10.5-dev
 - Installed Plugins: none
 - Reverse proxy: none

**Additional context**

Not sure when this was last working...

**Comment by PrplHaz4** [comment]
This seems to have been fixed somewhere late in the 10.5.0 dev cycle with other logging changes...

https://github.com/jellyfin/jellyfin/releases/tag/v10.5.0

**Comment by JustAMan** [comment]
Probably fixed by https://github.com/jellyfin/jellyfin/pull/2297
