### ISSUE TITLE
Specials are sorted before normal episodes

### ISSUE THREAD

**Issue by 0x6273** [jellyfin/jellyfin#2318]
**Describe the bug**

Navigating to a season of a show that has specials (bonus videos, things like an interview with the makers, or a creditless op/ed) displays those specials before the normal episodes, and clicking "Play" starts playing them first.

It is possible to fix this manually for each special, by going to the metadata editor, setting season number to 0, saving and reloading the page, then setting the previously hidden "Airs after season" option. But assuming that a special aired after the normal episodes should be the default behavior, since that's pretty much always the case.
**To Reproduce**

1. Have a show with specials, that are in the same directory as the normal episodes.
2. Navigate to the show and then to a season that has specials.
3. Notice that the specials are displayed above the normal episodes.
4. Click the "Play" button at the top.
5. The first special starts playing, rather than the first actual episode.

**Expected behavior**

Specials are usually watched after the actual show, so it would make a lot more sense if they were ordered after the normal episodes by default, unless they are tagged with the "Airs before season" option.

**Logs**

No log errors.

**Screenshots**

**System (please complete the following information):**
 - OS: Docker
 - Browser: Firefox
 - Jellyfin Version: 10.4.3
 - Installed Plugins: Anime
 - Reverse proxy: nginx

**Additional context**

**Comment by GlassedSilver** [comment]
Is this actually fixed or why did OP let this get staled?
