### ISSUE TITLE
TVDB provides season metadata, but JF doesn't download it.

### ISSUE THREAD

**Issue by SenorSmartyPants** [jellyfin/jellyfin#2319]
**Describe the bug**

thetvdb.com provides season metadata (Name, overview) but JF does not download it, or list TVDB as a season metadata downloader.

**To Reproduce**

1. Go to Libraries
2. Manage a TV Library
3. Scroll down to Season Metadata Downloaders
4. TVDB is not listed as an option. 

**Expected behavior**

Season name and metadata should be downloaded from TVDB
example season with data
https://www.thetvdb.com/series/miracle-workers-2019/seasons/official/2

**System (please complete the following information):**
 - OS: Docker
 - Browser: Chrome
 - Jellyfin Version: 10.4.1
 - Installed Plugins: Fanart,
 - Reverse proxy: no

**Additional context**

**Comment by Ullmie02** [comment]
I've noticed the same bug a few weeks ago. It appeared from one day to the other. I didn't update Jellyfin.
I think this is much more a bug than an enhancement because TVDB used to work as a season metadata provider.

**Comment by anthonylavado** [comment]
I forgot to update this - I believe this is fixed in the next version. Let me confirm.

@Ullmie02 It shouldn’t have appeared, unless you’re running a nightly

**Comment by anthonylavado** [comment]
Nothing has been done in this area so it shouldn’t have appeared at all.

That said, we have a revamped TVDB module on the way...

**Comment by Ullmie02** [comment]
I've just tested it again. I created a new blank Docker container with the latest version (10.4.3). TVDB is not listed as a Season Metadata Provider, just TheMovieDb

**Comment by cvium** [comment]
You are mistaken. They do now explicitly provide season metadata. Website != API.

thetvdb: https://api.thetvdb.com/swagger#/
themoviedb: https://developers.themoviedb.org/3/tv-seasons/get-tv-season-details

**Comment by Ullmie02** [comment]
Then they must have changed their API recently or their documentation is quite bad. I don't see any option to get Season posters in the docs. But I know for a fact that Jellyfin is able to download Season posters from TVDB.

**Comment by anthonylavado** [comment]
> Then they must have changed their API recently or their documentation is quite bad.

Actually both

>But I know for a fact that Jellyfin is able to download Season posters from TVDB.
That's from here: https://github.com/jellyfin/jellyfin/blob/master/MediaBrowser.Providers/TV/TheTVDB/TvdbSeasonImageProvider.cs

**Comment by Ullmie02** [comment]
Is there a reason to leave this issue open? It seems to me we won't get this feature because of the API limitation.

**Comment by SenorSmartyPants** [comment]
If it's not in the API then I'm fine with closing the issue.
