### ISSUE TITLE
iOS App Won’t Connect

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin#232]
Using the publicly available version of Emby for iOS (version 1.7.0 at the time of writing), it will not connect to a Jellyfin instance.

When performing the automatic scan, it does not identify any available servers. Entering the IP address manually and attempting to connect returns a message:

“This Emby Server needs to be updated...” including a malformed URL (hah!).

Reviewing the server logs, it appears that the app reaches out to:
`http://{server}:8096/emby/system/info/public`

This page returns some JSON like this:
```json
{"LocalAddress":"http://{serverip}:8096","WanAddress":"0.0.0.0","ServerName":"MyServer","Version":"3.5.2.0","OperatingSystem":"Linux","Id":"{GUID}"}
```

It looks like we may have to return version 3.5.3 to retain compatibility, and this situation may change further when 3.6 is released.

**Comment by joshuaboniface** [comment]
This should be pretty easy to fix up, re: changing the versioning to 3.5.3. But 3.6 is going to break a lot of stuff, and my feedback on that specific to DBs is in #233.

**Comment by anthonylavado** [comment]
So from what I can tell in 3.5.3, there were only small changes (that we publicly know about anyway). These are listed here:
https://emby.media/emby-server-353-released.html

We should probably be able to version bump with little difficulty then. In the meanwhile, I'll work on getting a development environment set up so I can test this at home.

**Comment by anthonylavado** [comment]
So, I did some more investigating. Bumping the version alone isn't enough. You must also change the `manifest.json` file.

This file is typically serverd from: `http://{serverip}:8096/emby/web/manifest.json`

It is located in `MediaBrowser.WebDashboard` under `dashboard-ui`. It usually looks like this:
```json
  "name": "Jellyfin",
  "short_name": "Jellyfin",
  "start_url": "/web/index.html",
  "description": "The open media solution.",
  "lang": "en-US"
```

If you change at least `name` and `short_name` back to "Emby", both auto discovery and connecting will work.

**Comment by anthonylavado** [comment]
Okay, so further digging reveals that updating the version in `SharedVersion.cs` is not required, but changing `name` to Emby is all that's required.

My earlier statement on auto discovery was wrong - this still doesn't allow that. I'll have to bring that up in another issue.

**Comment by anthonylavado** [comment]
This is fixed by #238. I’ll open a new issue for the discovery function. Thanks @joshuaboniface!

**Comment by Floflobel** [comment]
Is not work with the last version

**Comment by nvllsvm** [comment]
@Floflobek the Emby team has unfortunately decided to block our server in a number of their apps already.

**Comment by Zegorax** [comment]
@nvllsvm Is there any workaround for this ? This message is displayed inside the app : 
![image](https://user-images.githubusercontent.com/20574959/52367032-64965b80-2a4b-11e9-9b15-63da264ec77b.png)

**Comment by anthonylavado** [comment]
Hi @Zegorax! :wave:

There is no workaround for this at this time. It is no longer possible to use the Emby app on iOS/tvOS with Jellyfin.

That said, there are a few options:
- Using the web interface through Safari (iOS only)
- Using a DLNA app, like VLC or Infuse (iOS/tvOS)

**Comment by Zegorax** [comment]
Oh that's sad :(

So the spoof in the PR is not working as expected ?

When I have some time I will try to work on it.

**Comment by anthonylavado** [comment]
@zegorax That’s right. The spoof isn’t working.

We know how the check works and how to get around it, but it would just five minutes for them to defeat our fix. We decided in the end that it’s not worth it, and it’s better to make Jellyfin work with the web, and it’s own apps.

For that reason, I don’t recommend you spend too much time on it. They’ll just update again and it will stop working.

**Comment by Floflobel** [comment]
Hello, from an iphone how can we cast on a chromecast? We are obliged to have a computer with chrome installed on it or a workaround exists under iOS?
This is the only blocking point for me to switch to Jellyfin
