### ISSUE TITLE
TMDB season provider doesn't import season name.

### ISSUE THREAD

**Issue by SenorSmartyPants** [jellyfin/jellyfin#2320]
**Describe the bug**

TMDB season provider doesn't import season name.

**Details**
This was commented out in Emby days. Not sure what that comment refers to.
https://github.com/jellyfin/jellyfin/blob/d4de78693fcaf97aa5a94124b35e4d6145bdfa55/MediaBrowser.Providers/Tmdb/TV/TmdbSeasonProvider.cs#L66-L67

**Expected behavior**

Season name should be imported

**System (please complete the following information):**
 - OS: Docker
 - Browser: Chrome
 - Jellyfin Version: 10.4.1
 - Installed Plugins: Fanart
 - Reverse proxy: no

**Comment by dkanada** [comment]
I think they wanted the TMDB plugin to have a configuration page with options to disable individual fields such as name or description, which doesn't exist at the moment.

**Comment by SenorSmartyPants** [comment]
Since none of the metadata providers have configuration pages as far as I can see, maybe season name import could be turned back on?

**Comment by SenorSmartyPants** [comment]
Any updates on this? I just upgraded to 10.70.0 and tried refreshing some seasons with names. No names imported. I have TMDB set as my only season metadata provider, it looks like it grabbed writers for the seasons I refreshed. It did not save a TMDB season ID, not sure if it is supposed to.

**Comment by cvium** [comment]
It breaks stuff. We cannot enable it at this time.

**Comment by ThePeoplesBards** [comment]
> Any updates on this? I just upgraded to 10.70.0 and tried refreshing some seasons with names. No names imported. I have TMDB set as my only season metadata provider, it looks like it grabbed writers for the seasons I refreshed. It did not save a TMDB season ID, not sure if it is supposed to.

Do you use underscores in your naming path? I noticed TMDB does not support searching with "_" so none of my files are found by TMDB as I do not use spaces in file names. This could be the cause #5583

**Comment by SenorSmartyPants** [comment]
I'm trying to look into this issue. What are some other issues with more details on how it breaks stuff. Debugging so far, it seems as thou TMDB returns the correct season name, on initial tv scan, and manual identify. But I have a rather limited set of test series at the moment.

**Comment by SenorSmartyPants** [comment]
I've found #4134 and #5111
