### ISSUE TITLE
Sort Title Issues

### ISSUE THREAD

**Issue by robjloranger** [jellyfin/jellyfin#2324]
A collection of movies does not honor the sort title value. Movies appear to be sorted by release date instead. This is evident with collections of movies with prequels produced later on. i.e. Star Wars. (this is without using the box set plugin so likely not the same as #1321)

**To Reproduce**

1. Have at least Star Wars ep III and ep IV
2. Create a collection with the movies
3. Change the sort title values to something sane, i.e. Star Wars 3 and Star Wars 4 (I have tried numeric digits as well as roman numerals)
4. See titles still sorted by release date
5. Remove from collection and see titles sorted as described with sort title values

**Expected behavior**

Titles should sort by the provided sort title value regardless of being in a collection.

**Screenshots**
![2020-01-22-095619_922x859_scrot](https://user-images.githubusercontent.com/13278126/72920279-d53a9480-3cfd-11ea-827f-ba9530dab1dc.png)
![2020-01-22-100115_870x393_scrot](https://user-images.githubusercontent.com/13278126/72920465-306c8700-3cfe-11ea-82b9-b14c79fbaf43.png)
![2020-01-22-100129_849x376_scrot](https://user-images.githubusercontent.com/13278126/72920469-319db400-3cfe-11ea-8177-e87d451baa8e.png)

**System (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: all (ff, chrome, android app)
 - Jellyfin Version: 10.4.3
 - Installed Plugins: none
 - Reverse proxy: no

**Comment by TK-3375** [comment]
I am bumping in that topic with the same problem here with Jellyfin 10.11.4

I put my movies in a star wars folder, and each movie in it's own folder as well :

- Star Wars\Star Wars - Episode I - The Phantom Menace (1999)
- Star Wars\Star Wars Episode II - Attack of the Clones (2002)

And so on. I also tried the "sort title" trick, and changing the collection sort order by "filename" but nothing seems to work in the web interface

Using docker jellyfin/jellyfin:latest
cat /etc/debian_version : 12.12
uname -a : Linux halcyon 6.1.0-13-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29) x86_64 GNU/Linux
using nginx and letsencrypt
