### ISSUE TITLE
Random black/stopped video

### ISSUE THREAD

**Issue by chnaski** [jellyfin/jellyfin#2327]
The video stopped at 1:55pm and 4:32pm
[jellyfin.zip](https://github.com/jellyfin/jellyfin/files/4100142/jellyfin.zip)

**Comment by JustAMan** [comment]
Please use proper issue reporting template - we request some information for a reason.

**Comment by Artiume** [comment]
Should be fixed with https://github.com/jellyfin/jellyfin/pull/2365
