### ISSUE TITLE
Cant scan mounted rclone/mergerfs in docker container

### ISSUE THREAD

**Issue by dannymichel** [jellyfin/jellyfin#2339]
this applies to 10.4.3, 10.4.3, and 10.5 docker containers
`docker run --restart=unless-stopped -d --volume /opt/docker/jellyfin:/config --volume /opt/docker/cache/jellyfin:/cache --volume /mnt/mergerfs/media:/mnt/mergerfs/media --name jellyfin --publish 8096:8096 --publish 8920:8920 jellyfin/jellyfin`
there are no logs for this even in log debug mode.
it just fails to scan and says 'failed'

**Comment by Artiume** [comment]
Your docker container is running as root due to your config. What are the permissions looking like for the mount?

**Comment by lopoki** [comment]
I can scan mounted rclone/mergerfs in docker container, but the scan always stuck at around 80%

**Comment by Artiume** [comment]
@lopoki so that's the scanner progress bar not reporting correctly. The scan gets to 80 before it starts using ffprobe to analyze the files. Watch the log files and ensure progress continues, but it'll eventually finish.

**Comment by dannymichel** [comment]
> Your docker container is running as root due to your config. What are the permissions looking like for the mount?

the permissions of the mount were user:user but doesnt root have permissions for everything?

**Comment by Artiume** [comment]
not if you have it squash root permissions
