### ISSUE TITLE
Embedded images in audio files capped at 600px

### ISSUE THREAD

**Issue by ferferga** [jellyfin/jellyfin#2345]
**Describe the bug**

Artwork embedded in audio files of any format )is capped to a maximum 600x600 resolution, downscaling images in Jellyfin's library from the original sources.

**To Reproduce**
1. Add a song with an embedded artwork greater than 600x600
2. Wait for the library scan and open the "Edit images" option of the element

**Expected behavior**
Use original resolution images, extracting them from the metadata or directly reading them from the file during playback

**Screenshots**
* File in Jellyfin
![Sin título](https://user-images.githubusercontent.com/10274099/73223304-f10ec200-4165-11ea-8190-3b400ee21c95.png)
* File's metadata as read by MP3tag.

![Sin título](https://user-images.githubusercontent.com/10274099/73223335-0126a180-4166-11ea-8da0-c8dda5411145.png)

**System (please complete the following information):**
 - OS: Debian Buster on Pi 3
 - Browser: Chrome
 - Jellyfin Version: 10.4.3

**Additional context**
Tested MP3 and FLAC, but I suppose this is unrelated and just depends on the music scanner/skia processing, so I believe all formats are affected.

**Comment by ferferga** [comment]
Dumb bot... This is still happening!

**Comment by ferferga** [comment]
Still relevant

**Comment by RubenTeixeira** [comment]
This issue returned for me in  10.9 :( 
The difference is does seem to work well for 700x700. Seems it does the rescale for bigger than that.
