### ISSUE TITLE
Jellyfin stuck and can't finish new Library scans

### ISSUE THREAD

**Issue by lopoki** [jellyfin/jellyfin#2350]
**Describe the bug**
Jellyfin stuck and can't finish new Library scans. After a clean install and setup few libraries. Scan of the libraries stuck at around 80% for days. Rebooting, canceling scans, choosing different scan mode, reinstalling jellyfin server, all does not solving the issue.

See logs: https://defuse.ca/b/wwexaLxz

**Logs**
See logs: https://defuse.ca/b/wwexaLxz

**Screenshots**

**System (please complete the following information):**
 - OS: ubuntu 18.04
 - Browser: Chrome,
 - Jellyfin Version: 10.4.3
 - Installed Plugins: default plugins
 - Reverse proxy: nginx

**Comment by Artiume** [comment]
So there's multiple phases to the scanner. Phase 1 is Scan entire library to determine what files exist. Phase 2 is to use ffprobe to analyze the files to determine codecs and media info. If Image Extractor is enabled, it will extract the images at this point as well. The overall issue with the scanner is Phase 1 takes you to 80% but that's fastest part. So now it feels like it's 'stuck'. What do your logs say? Is it continuing the ffprobe process or is it actually stuck?

**Comment by YShow** [comment]
Same thing happening to me, it stops the scanning in about 80% - 86.4%, it worked untill last week normally but now it cant detect new movies or series, i tried a clean setup again and it wouldn't add even a single movie or series and the only weird thing that appeared on the logs is this 

> [matroska,webm @ 0x557edd7170c0] Could not find codec parameters for stream 2 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size                      
Consider increasing the value for the 'analyzeduration' and 'probesize' options

I also tried rebuilding ffmpeg from the jellyfin repo, using nightly jellyfin and still the same thing

**Comment by Artiume** [comment]
This should help with the problem. It was just merged
https://github.com/jellyfin/jellyfin/pull/1941

**Comment by YShow** [comment]
I tried the nightly branch with this merge but still got the error, i don't know how to use these variables, i tried this:

> env JELLYFIN_FFmpeg__probesize=2G JELLYFIN_FFmpeg__analyzeduration=400M ./jellyfin

but still gave me the same error and no movies or series are scanned or got the metadata

**Comment by Artiume** [comment]
Hmmm, I'm not sure. So the commands have to be used at runtime. That being said, I'm not sure what values or exactly how to use the ENV.

**Comment by YShow** [comment]
@Artiume @lopoki In my case it seems its cause by IPV6, as stated on the issue https://github.com/jellyfin/jellyfin/issues/1002 if IPV6 fails it doesn't try IPV4 and when that happens it stop scanning all others movies and series so it stays like the images above. @lopoki can you see if you have IPV6 enabled and if so disable it a see if it works
