### ISSUE TITLE
"Save artwork into media folders" just spins for DVR library. Doesn't properly save poster/fanart/episode art

### ISSUE THREAD

**Issue by classicjazz** [jellyfin/jellyfin#2366]
**Describe the bug**
Two problems:
1.) If you enable "Save artwork into media folders", you just see the spinner. Happens every time on multiple machines.
2.) In the absence of enabling "Save artwork into media folders", expected artwork isn't saved to recorded shows.
3.) Because, I can't enable "Save artwork into media folders", its not clear whether that function works properly.

**To Reproduce**
Create a separate library for your DVR'ed shows. Enable "Save artwork into media folders". All you see is a spinner:

<img width="829" alt="spinner" src="https://user-images.githubusercontent.com/7338491/73596780-7d690e00-44f3-11ea-99ce-6a43fb60c690.png">

You can wait was long as you want. It just keeps spinning. If you refresh and return to this page, the checkbox is unchecked.

Current behavior:
* Writes fanart as -thumb.jpg rather than extracting a frame from the episode as thumb.jpg.
* Does NOT write fanart.jpg even though that asset is available (written as -thumb.jpg).
* Does NOT write poster.jpg even though it is an available asset from Schedules Direct.
* Does NOT write season0x-poster.jpg.

I am using SchedulesDirect in the US for OTA TV guide and DVR. Ideally, I would turn off all image downloading and just use their data + episode image / frame extraction.

**Expected behavior**
1. No or very brief spinner.
2. "Save artwork into media folders" is checked on subsequent refreshes

* Write fanart.jpg 
* Write poster.jpg 
* Write season0x-poster.jpg
* Create a proper episode thumbnail from the show footage.

**Logs**

**Screenshots**

**System (please complete the following information):**
 - OS: Docker on Synology NAS
 - Browser: Firefox, Chrome, Safari
 - Jellyfin Version: 10.4.3
 - Installed Plugins: none
 - Reverse proxy: no

**Additional context**
This is an important issue because it impacts third party players that use local artwork instead of remote scrapers. For example, right now JellyFin is a better DVR than Plex. But it lacks an Apple TV client, so Plex or Infuse is a better player.

**Comment by Artiume** [comment]
So it sounds like a permissions issue. whats the id inside the container compared to the media folder?

**Comment by classicjazz** [comment]
Would you please recommend terminal commands to give you that info?

Here's how I configured it:
* I used the Synology GUI to download, edit, and run the JellyFin docker container.
* I created config, cache, and dvr shared folders in the Synology GUI and mapped them in the JellyFin container as writable mounted folders. 
* Additionally, I have several video folders that are write only (e.g. home videos, TV shows from DVD/BR).

If it's a permissions issue, it seems strange because there are no issues recording video/NFOs/an episode thumbnail in the DVR folder (which is where the artwork should be written too). And I am enabling "Save artwork into media folders" for the DVR library (which is exclusively mapped to the DVR folder), not the read only folders associated with the TV Shows library.

**Comment by Artiume** [comment]
You're right, the nfo would flag as well. I'm not having this issue so it might be fixed on master. 

The enable image Extraction, are you enabling that at the same time or was that previously enabled?

`sudo docker exec -it jellyfin id`

Posting any command after the container name (hopefully its named jellyfin) will run the following command inside the container. You can also use something like

`sudo docker exec -it jellyfin stat /path/to/media`

This will give you a look of how the container sees the permissions of the mount. 

This will list all active containers and show details such as container names. 
`sudo docker container ls`

**Comment by classicjazz** [comment]
Helpful. Thank you.

```
$ sudo docker exec -it jellyfin-jellyfin id
uid=0(root) gid=0(root) groups=0(root)

$ sudo docker exec -it jellyfin-jellyfin stat /dvr
Access: (0000/d---------)  Uid: (    0/    root)   Gid: (    0/    root)

```

**Comment by Artiume** [comment]
Ok, that's weird. The folder has no properties tied to it.

See if you can create files manually
`sudo docker exec -it jellyfin-jellyfin touch /dvr/testfile`

This should fix it
`sudo docker exec -it jellyfin-jellyfin chmod -r 755 /dvr`

**Comment by classicjazz** [comment]
Sorry, I excerpted the original output

```
$ sudo docker exec -it jellyfin-jellyfin stat /dvr
  File: /dvr
  Size: 1234      	Blocks: 0          IO Block: 4096   directory
Device: 29h/41d	Inode: 256         Links: 1
Access: (0000/d---------)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2020-02-01 22:00:03.052960946 +0000
Modify: 2020-02-01 22:00:02.732960081 +0000
Change: 2020-02-01 22:00:02.732960081 +0000
 Birth: -

``` 

This properly executes:
` sudo docker exec -it jellyfin-jellyfin touch /dvr/testfile`

But this:```

$  sudo docker exec -it jellyfin-jellyfin chmod -r 755  /dvr
chmod: cannot access '755': No such file or directory
```

**Comment by Artiume** [comment]
Ah, make it -R instead of lowercase and try it again

Here's a good read if you want to learn more 
https://www.linux.org/threads/file-permissions-chmod.4124/

**Comment by classicjazz** [comment]
`sudo docker exec -it jellyfin-jellyfin chmod -R 777 /dvr/`

has no errors

But still spinning wheel of (in)progress when I select "Save artwork into media folders"...

However, I just unchecked the default metadata downloaders and didn't touch "Save artwork into media folders" and it also has the spinning wheel of (in)progress.

**Comment by Artiume** [comment]
So, you're thinking it's not limited to the save artwork. Just the options folder itself is letting you modify it?

**Comment by classicjazz** [comment]
The only folder that I cannot modify its options is the DVR folder. Just tested all the other read-only libraries and I could enable/disable metadata downloaders without issue. To be clear, that doesn't mean that metadata could be downloaded because they are still read-only (I don't want the stored metadata to be changed). But they don't spin infinitely like DVR library/folder does.

Also, even if we solve for the spinning and enabling "Save artwork into media folders", I am not sure that solves for the expected behavior or writing the fanart.jpg, poster.jpg, season0x-poster.jpg, and episode thumbnail from the show footage.

**Comment by Artiume** [comment]
Hmm... Is the library saved as a mixed type or TV shows?  I could check my local files and see how it's saved, but it should be fine. And just to make sure, this is the native jellyfin turner, not the livetv plugin, right?

**Comment by classicjazz** [comment]
I am using the TV show library type.

Separate from this bug, I proposed creating a DVR library type (based on live TV categories). See here:
https://github.com/jellyfin/jellyfin-web/issues/750

I am using the native JellyFin tuner for HDhomerun. I am not using any plugins whatsoever.

**Comment by Artiume** [comment]
So i posted my pics in that one. maybe mimic my settings to see if you can get it to save.

**Comment by classicjazz** [comment]
I believe that the only difference in our settings is that I download 14 days of guide data and use /dvr for my stored recordings. And I am using 10.4.3 while you are using master?

**Comment by Artiume** [comment]
Yeah, if that's the case, you should be fine to shift to master to fix it. Only big regressions I know of for browsers is Firefox ESR issues
