### ISSUE TITLE
"Naming Conventions for Jellyfin" should probably be renamed

### ISSUE THREAD

**Issue by chowbok** [jellyfin/jellyfin#237]
Most people are going to see "Naming Conventions for Jellyfin" and assume it means how to name one's media files so that Jellyfin sees them correctly. Maybe come up with a different name for that page.

**Comment by anthonylavado** [comment]
@joshuaboniface Perhaps we should change this to surrounding Code Style?

**Comment by joshuaboniface** [comment]
Yea I think that's fine.

**Comment by joshuaboniface** [comment]
Renamed to https://github.com/jellyfin/jellyfin/wiki/Jellyfin-Coding-Style!
