### ISSUE TITLE
Add support for Referer in m3u

### ISSUE THREAD

**Issue by win98se** [jellyfin/jellyfin#2376]
**Media Info of the file**
None

**Logs**
None

**FFmpeg Logs**
None

**Stats for Nerds Screenshots**
None

**Server System (please complete the following information):**
 - OS: Windows 10 Version 1909 (OS Build 18363.592)
 - Jellyfin Version: 10.4.3
 - Hardware settings & device: Not applicable
 - Reverse proxy: None
 - Other hardware notes: None
 
**Client System (please complete the following information):**
 - Device: PC
 - OS: Windows 10 Version 1909 (OS Build 18363.592)
 - Client: Web browser
 - Browser (if Web client): Google Chrome
 - Client and Browser Version: 81.0.4040.5 dev

Some m3u8 links require the HTTP `Referer` header pointing to their own site instead of somewhere else, or else they give 403 Forbidden error.

[This is one example of m3u's with the `Referer` header.](https://github.com/freeview/iptv/blob/master/playlist/my.m3u)

**Comment by LaserKaspar** [comment]
This would be awesome!

**Comment by felix920506** [comment]
Please do not attempt to revive ancient threads.
