### ISSUE TITLE
Auto discovery protocol no more works with a base url

### ISSUE THREAD

**Issue by Tolriq** [jellyfin/jellyfin#2380]
Tested on a few nightly releases including https://repo.jellyfin.org/releases/server/windows/nightly/jellyfin-nightly_20200204_windows-x64.zip on windows portable mode.

As soon as you configure a base url in the settings and restart Jellyfin it stops answering to discovery packets.
As soon as you remove the base url and restart it answers again.

**Comment by JustAMan** [comment]
cc @Bond-009

**Comment by Bond-009** [comment]
Any logs?

**Comment by Tolriq** [comment]
There's no logs and no error shown in the console. Is there some advanced settings to log more?

**Comment by Bond-009** [comment]
https://jellyfin.org/docs/general/administration/connectivity.html#debug-logging

**Comment by Tolriq** [comment]
@Bond-009 
Logs are strictly identical except:

```[2020-02-12 20:02:38.345 +01:00] [DBG] Ping test result to "http://192.168.1.80:8096/system/ping". Success: True```
vs 
```[2020-02-12 20:01:00.665 +01:00] [DBG] Ping test result to "http://192.168.1.80:8096//jellyfin/system/ping". Success: False```

Please note that I add jellyfin in settings and it automatically add the /

And that while ```http://192.168.1.80:8096/jellyfin/system/ping``` does work, ```http://192.168.1.80:8096//jellyfin/system/ping``` does not and redirect.

So it's normal that this test fails.

Should be pretty easy to reproduce.

**Comment by Tolriq** [comment]
That PR fix the issue :)
