### ISSUE TITLE
Can't play live tv on 10.5.0

### ISSUE THREAD

**Issue by dannymichel** [jellyfin/jellyfin#2383]
```
apiclientcore.js POST 500 (Internal Server Error)
Uncaught (in promise) Response type: "basic"redirected: false, status: 500, ok: false
```

**Comment by PrplHaz4** [comment]
Please fill out the issue log with repro steps, tv source and include server logs. Title should prob be 10.5.0-dev as 10.5.0 doesn't exist yet.

**Comment by olskar** [comment]
I think I have the same problem. This is on nightly 2020-02-18 and Chrome. Those errors are from chrome console. Nothing interesting in jellyfinlogs with debug turned on. 

`POST http://192.168.1.90:8096/jellyfin/Items/4ef4455ba54ead1345227c4141f67de6/PlaybackInfo?UserId=65ae4b9b4ba14915a4622cfad3f7ac96&StartTimeTicks=0&IsPlayback=true&AutoOpenLiveStream=true&MaxStreamingBitrate=140000000 500 (Internal Server Error)
getFetchPromise @ apiclientcore.js?v=10.5.0:58
ApiClient.fetch @ apiclientcore.js?v=10.5.0:266
ApiClient.ajax @ apiclientcore.js?v=10.5.0:287
ApiClient.getPlaybackInfo @ apiclientcore.js?v=10.5.0:684
getPlaybackInfo @ playbackmanager.js?v=10.5.0:526
getPlaybackMediaSource @ playbackmanager.js?v=10.5.0:2652
(anonymous) @ playbackmanager.js?v=10.5.0:2433
Promise.then (async)
playAfterBitrateDetect @ playbackmanager.js?v=10.5.0:2415
(anonymous) @ playbackmanager.js?v=10.5.0:2291
Promise.then (async)
(anonymous) @ playbackmanager.js?v=10.5.0:2287
Promise.then (async)
(anonymous) @ playbackmanager.js?v=10.5.0:2283
Promise.then (async)
playInternal @ playbackmanager.js?v=10.5.0:2265
(anonymous) @ playbackmanager.js?v=10.5.0:2230
Promise.then (async)
playWithIntros @ playbackmanager.js?v=10.5.0:2207
(anonymous) @ playbackmanager.js?v=10.5.0:2036
Promise.then (async)
(anonymous) @ playbackmanager.js?v=10.5.0:2034
Promise.then (async)
PlaybackManager.self.play @ playbackmanager.js?v=10.5.0:2032
executeAction @ shortcuts.js?v=10.5.0:218
onClick @ shortcuts.js?v=10.5.0:360
onClick @ emby-itemscontainer.js?v=10.5.0:17
index.html#!/home.html:1 Uncaught (in promise) Response {type: "basic", url: "http://192.168.1.90:8096/jellyfin/Items/4ef4455ba5…OpenLiveStream=true&MaxStreamingBitrate=140000000", redirected: false, status: 500, ok: false, …}`
