### ISSUE TITLE
"PremiereDate" metadata point for music albums doesn't need to be a full datestring

### ISSUE THREAD

**Issue by mcarlton00** [jellyfin/jellyfin#2391]
**Describe the bug**
The "PremiereDate" when accessing a music album through the API is a full datestring + timestamp instead of just a date.

```
(Pdb) pp item
{'AlbumArtist': 'Imagine Dragons',
 'AlbumArtists': [{'Id': '480f930cbccbd6e340b7ed6a039b4756',
                   'Name': 'Imagine Dragons'},
                  {'Id': 'c38e0f8aa8bcbda488cb1b137dc97923',
                   'Name': 'Various Artists'}],
 'ArtistItems': [{'Id': '480f930cbccbd6e340b7ed6a039b4756',
                  'Name': 'Imagine Dragons'}],
 'Artists': ['Imagine Dragons'],
 'BackdropImageTags': [],
 'Id': 'ba21ff66941fbb475717d6c56e1da1d5',
 'ImageTags': {'Primary': 'ae77f1c6e9c1c79237e4f10563b5dd3d'},
 'IsFolder': True,
 'LocationType': 'FileSystem',
 'Name': 'Believer',
 'ParentBackdropImageTags': ['400da997ab74e8c00ddc5b3945d16cf9'],
 'ParentBackdropItemId': '480f930cbccbd6e340b7ed6a039b4756',
 'ParentLogoImageTag': '0aee83397679e2b6b7835044c391dc6b',
 'ParentLogoItemId': '480f930cbccbd6e340b7ed6a039b4756',
 'PremiereDate': '2012-09-04T00:00:00.0000000Z',
 'ProductionYear': 2012,
 'RunTimeTicks': 26261970944,
 'ServerId': '0e23a5ed08c84a159ea7d7aea7ff5e67',
 'Type': 'MusicAlbum',
 'UserData': {'IsFavorite': False,
              'Key': 'MusicAlbum-MusicBrainzReleaseGroup-8bcb5dcd-88bd-4651-9822-51b069b5e0d9',
              'PlayCount': 0,
              'PlaybackPositionTicks': 0,
              'Played': False}}
```
**To Reproduce**

1. Retrieve a music album from the API

**Expected behavior**

`'PremiereDate': '2012-09-04T00:00:00.0000000Z'` should probably be returned as just `'PremiereDate': '2012-09-14`

**System (please complete the following information):**
 - OS: Docker
 - Browser: API
 - Jellyfin Version: 10.4.3
 - Installed Plugins: Kodi Sync Queue, TMDB Box Sets
 - Reverse proxy: nginx

**Comment by JustAMan** [comment]
But why? :) I mean, what's wrong with having some extra precision?

**Comment by mcarlton00** [comment]
shoo bot

**Comment by dreadedhamish** [comment]
> But why? :) I mean, what's wrong with having some extra precision?

It isn't more precise. Albums don't have release times - adding a specific release time makes it less precise.

**Comment by cvium** [comment]
It's a common DTO right now. We would need to make a new DTO _just_ for albums and artists. I don't consider this a bug at all. If the client doesn't care about the time, then strip it. The Z means it's UTC, so just don't convert it to local time and strip the time portion.
