### ISSUE TITLE
Jellyfin breaks the admin page of TP-Link router

### ISSUE THREAD

**Issue by PookaMustard** [jellyfin/jellyfin#2401]
**Describe the bug**
Whenever an instance of Jellyfin is open, it becomes near impossible to actually use the admin page of my router, in this case a TP-Link TD-W8961N. At best the page works for a few seconds before it stops responding. When it starts responding again, the user is logged out, and further attempts result in the same events. This also happened on a fresh factory reset of the router.

This has happened with Jellyfin as a service. After messing with the settings to find the culprit, it appears the suspect at hand is the DLNA setting "Enable DLNA Play To." Recent testing also found that "Enable automatic port forwarding" under Networking is also a culprit, making the UPnP port forwarding the most likely cause of the issue. The issue doesn't occur when UPnP is disabled on the router. The router doesn't produce logs for the issue.

**To Reproduce**
1. Run Jellyfin as user with server management permissions
2. Go to dashboard, DLNA settings, and make sure Enable DLNA Play To is checked, then save settings.
3. Open admin page (192.168.1.1 or equivalent). Login and navigate through the menus until the navigation stops responding. Wait until the login screen is shown again, and repeat once more.
4. Uncheck Enable DLNA Play To, save settings.
5. Restart Jellyfin
6. Open admin page, login and navigate through menus. Notice the navigation continues normally.

**Expected behavior**
Admin page to load normally and stay accessible until I leave it.

**System:**
 - OS: Windows 10
 - Browser: Firefox/Chrome
 - Jellyfin Version: 10.4.3 Stable and 10.5.0 Nightly
 - Installed Plugins: None
 - Reverse proxy: None

**Additional context**
I've had this issue for a couple days without finding any working solutions on search engines. When doing a fresh restart of the router, I've also disabled stuff like local static IPs and most importantly Jellyfin. When the router worked normally, I turned Jellyfin back on, and this was promptly followed by the router acting up. I realized that the source of the problem was Jellyfin and kept troubleshooting until I found the exact source.

**Comment by Artiume** [comment]
Can you go ahead and shift to nightly? Dlna has been through a lot of improvements

**Comment by PookaMustard** [comment]
I have switched over to the 10.5.0 nightly and tested it a couple minutes ago. The issue still remains.
My router did not log anything relevant: the latest logs were from yesterday night when Jellyfin was off.

**Comment by Artiume** [comment]
I need logs from when jellyfin dlna is on. Turn it on, replicate the admin page issue, the  off dlna and check the logs. 

Do you have dlna issues with Emby or plex?

**Comment by PookaMustard** [comment]
Yep, the router still does not produce logs when DLNA is on. I've been all over the settings for the router and there's nothing for logs save for the lone system logs page, which only shows the logs and lets you clear or save them. [I've attached what was there](https://github.com/jellyfin/jellyfin/files/4199006/logs.zip), as well as the Jellyfin logs for today.

I never used Emby and haven't used Plex DLNA so cannot say, but I am willing to install and test them in pursuit of fixing this bug.

**Comment by Artiume** [comment]
Yeah, I don't see anything really weird in the logs. Go ahead and try Plex's DLNA. It can at least narrow it down to the JF service and not your router's uPnP functionality. 

Saving this for later lol
https://tele9752.wikia.org/wiki/UPNP

**Comment by PookaMustard** [comment]
I went ahead, tried Plex, and enabled the DLNA server. For some reason, I could never get it to detect my TV like JF does. Here are my DLNA settings for Plex. Only media renderer discovery interval was cut from 60 to 5. Admin page working fine.
![image](https://user-images.githubusercontent.com/19552979/74477844-bb334280-4eb4-11ea-9627-5dac067bd64e.png)

**Comment by Artiume** [comment]
Just to make sure, both JF and plex are on the local subnet and aren't on a bridge of some sort?

**Comment by PookaMustard** [comment]
Yes. No special tricks. The only thing I changed on the router is to give the laptop hosting JF/Plex a static IP address.

**Comment by Artiume** [comment]
I'm not sure. I think a deeper level investigation would be to use Wireshark or some sort of network analyzer but that's beyond me

**Comment by Artiume** [comment]
No clue man, it's weird. Could you disable upnp on your router and then see if JF can impact the admin page?

**Comment by PookaMustard** [comment]
Done that! Shutting off UPnP prevents JF from impacting the admin page even with DLNA Play To enabled.

**Comment by anthonylavado** [comment]
Weird... I have an Archer C7 v2 and this has never happened to me.

**Comment by JustAMan** [comment]
One of the reasons is that in JF currently DLNA option is actually toggling both DLNA discovery and UPnP port forwarding (inherited bad design). So either your router is misbehaving on port forward requests, or JF is sending them badly.

We should have those as separate settings anyway (and disable port forwarding by default).

**Comment by PookaMustard** [comment]
OK, I'm a little bit more free (for now).  So should I wait until the DLNA option is uncoupled from UPnP port forwarding? I'd love to see if the issue is not JF related but caused by UPnP in general - not sure where to start researching that.

**Comment by Artiume** [comment]
In the networking tab, ensure this is disabled. I want to defang upnp/dlna as much as possible. See if there's a specific setting that's causing the issue. 
 `Enable automatic port mapping: Attempt to automatically map the public port to the local port via UPnP. This may not work with some router models.`
DLNA Page, disable `Enable DLNA Play To` and `Blast alive messages` 

I can't find anything else to disable, but this should at least let us verify it's enabling dlna that causes it and nothing else

**Comment by PookaMustard** [comment]
I already had `Enable automatic port mapping` disabled along with allowing remote connections to the server, and `Blast alive messages` was also disabled. But I tried again just to be sure with all of those disabled - admin page works fine.

I took the cue from your suggestion and enabled remote connections and automatic port mapping - admin page impacted! This is with DLNA play to _disabled._ So the culprit is very likely the UPnP port mapping. The difference is that the automatic port mapping setting does say it may not work on some router models, but DLNA play to doesn't.

Sidenote: you might want to make it clear that disabling UPnP port forwarding requires a restart of JF - the admin page returns to normal after a restart, not after disabling the offending settings.

**Comment by Artiume** [comment]
Awesome. I'll add a note for upnp

**Comment by Artiume** [comment]
Did enabling port mapping require restarting or was it to disable it only?

**Comment by PookaMustard** [comment]
Enabling DLNA did not require restart, _disabling it_ does. I'll test and reply with more info.

**Comment by PookaMustard** [comment]
I have installed 10.6.0 today and...yeah. DLNA Play To still causes the router to freak out.

Reproduction steps and system information (aside from the updated JF) are the same as last time. No further testing done.

**Comment by Artiume** [comment]
Perhaps 10.7 will fix it, here's some of the PR's that might do the trick.

https://github.com/jellyfin/jellyfin/pull/3536
https://github.com/jellyfin/jellyfin/pull/3257

**Comment by PookaMustard** [comment]
The PC that was hosting my Jellyfin server was out of commission for a while. I recently put it back online and updated my Jellyfin from 1.6.x to 1.7.5. The problem still persists: enable DLNA Play To, save, open the admin page, and watch as it slows down to a crawl in short intervals and logs you out. To workaround it, disable DLNA Play To, save, restart Jellyfin.

I'll try to be more vigilant this time. No promises though, I'm already pretty busy with work.
