### ISSUE TITLE
VAAPI does not work

### ISSUE THREAD

**Issue by Dragon988** [jellyfin/jellyfin#2408]
**Describe the bug**
VAAPI gives a "NoCompatibleStream" error even with H.264 encoding/decoding. On both nightly and stable builds.

 - OS: Debian 10
 - Browser: Firefox/chrome
 - Jellyfin Version: both stable and nightly
 - Installed Plugins: none
 - Reverse proxy: none

**Comment by nyanmisaka** [comment]
Please provide ffmpeg logs and your GPU model.

**Comment by Dragon988** [comment]
> Please provide ffmpeg logs and your GPU model.

UHD 630. intel_gpu_top shows no usage and CPU is transcoding.

I'll grab the logs in a bit but all I'm doing is streaming rips made by makemkv.

**Comment by Artiume** [comment]
so Vaapi cant decode h264 10bit. the ffmpeg logs are important :)

**Comment by Dragon988** [comment]
> so Vaapi cant decode h264 10bit. the ffmpeg logs are important :)

```
[2020-02-14 16:48:25.705 -08:00] [INF] /usr/lib/jellyfin-ffmpeg/ffmpeg -hwaccel vaapi -hwaccel_output_format yuv420p -vaapi_device /dev/dri/renderD128 -i file:"/mnt/media/$
[2020-02-14 16:48:25.756 -08:00] [ERR] FFMpeg exited with code 134
[2020-02-14 16:48:25.814 -08:00] [WRN] cannot serve "/var/lib/jellyfin/transcoding-temp/transcodes/transcodes/transcodes/transcodes/transcodes/transcodes/754397c155d68ddc6$
[2020-02-14 16:48:25.814 -08:00] [ERR] Error processing request: "Could not find file '/var/lib/jellyfin/transcoding-temp/transcodes/transcodes/transcodes/transcodes/trans$
[2020-02-14 16:48:25.827 -08:00] [INF] Playback stopped reported by app "Jellyfin Web" "10.5.0" playing "Atomic Blonde". Stopped at "0" ms
```

```
     _STATISTICS_WRITING_APP-eng: MakeMKV v1.14.7 linux(x64-release)
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-02-13 18:44:21
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID
    Stream #0:1(eng): Audio: dts (DTS-HD MA), 48000 Hz, 7.1, s32p (24 bit) (default)
    Metadata:
      title           : Surround 7.1
      BPS-eng         : 4671040
      DURATION-eng    : 01:54:44.298666666
      NUMBER_OF_FRAMES-eng: 645403
      NUMBER_OF_BYTES-eng: 4019604104
      SOURCE_ID-eng   : 001100
      _STATISTICS_WRITING_APP-eng: MakeMKV v1.14.7 linux(x64-release)
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-02-13 18:44:21
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID
    Stream #0:2(eng): Audio: dts (DTS), 48000 Hz, 5.1(side), fltp, 1536 kb/s
    Metadata:
      title           : Surround 5.1
      BPS-eng         : 1509000
      DURATION-eng    : 01:54:44.298666666
      NUMBER_OF_FRAMES-eng: 645403
      NUMBER_OF_BYTES-eng: 1298550836
      SOURCE_ID-eng   : 001100
      _STATISTICS_WRITING_APP-eng: MakeMKV v1.14.7 linux(x64-release)
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-02-13 18:44:21
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID
    Stream #0:3(eng): Audio: ac3, 48000 Hz, stereo, fltp, 192 kb/s
    Metadata:
      title           : Stereo
      BPS-eng         : 192000
      DURATION-eng    : 01:54:44.320000000
      NUMBER_OF_FRAMES-eng: 215135
      NUMBER_OF_BYTES-eng: 165223680
      SOURCE_ID-eng   : 001103
      _STATISTICS_WRITING_APP-eng: MakeMKV v1.14.7 linux(x64-release)
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-02-13 18:44:21
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID
    Stream #0:4(eng): Audio: ac3, 48000 Hz, stereo, fltp, 192 kb/s
    Metadata:
      title           : Stereo
      BPS-eng         : 192000
      DURATION-eng    : 01:54:44.320000000
      NUMBER_OF_FRAMES-eng: 215135
      NUMBER_OF_BYTES-eng: 165223680
      SOURCE_ID-eng   : 001104
      _STATISTICS_WRITING_APP-eng: MakeMKV v1.14.7 linux(x64-release)
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-02-13 18:44:21
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID
    Stream #0:5(eng): Subtitle: hdmv_pgs_subtitle (default)
    Metadata:
      BPS-eng         : 31533
      DURATION-eng    : 01:47:34.468854166
      NUMBER_OF_FRAMES-eng: 2411
      NUMBER_OF_BYTES-eng: 25441395
      SOURCE_ID-eng   : 001200
      _STATISTICS_WRITING_APP-eng: MakeMKV v1.14.7 linux(x64-release)
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-02-13 18:44:21
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID
Stream mapping:
  Stream #0:0 (h264) -> overlay:main (graph 0)
  Stream #0:5 (pgssub) -> scale (graph 0)
  scale_vaapi (graph 0) -> Stream #0:0 (h264_vaapi)
  Stream #0:1 -> #0:1 (dts (dca) -> aac (native))
Press [q] to stop, [?] for help
[matroska,webm @ 0x5610fb395d00] sub2video: using 1920x1080 canvas
ffmpeg: i965_encoder.c:1692: intel_enc_hw_context_init: Assertion `encoder_context->mfc_context' failed.
```

**Comment by Dragon988** [comment]
Nevermind, this is infact a iGPU issue as it doesn't work on my windows laptop either but nvenc does.

I thought regular bluray didn't have 10bit profiles?

You can replicate this by using makemkv and transcoding the resulting .mkv file.

**Comment by Artiume** [comment]
Are those the full ffmpeg logs? I was expecting more before `_STATISTICS_WRITING_APP-eng: MakeMKV v1.14.7 linux(x64-release) _STATISTICS_WRITING_DATE_UTC-eng: 2020-02-13 18:44:21 _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID  `


Here's the mapping you're doing. I'm not sure the bit of your media since the logs are incomplete but you didn't use vaapi to decode so I think the bit might not be the problem. Those pgs subs look suspicious in any case. 
```
Stream mapping: 
Stream #0:0 (h264) -> overlay:main (graph 0) 
Stream #0:5 (pgssub) -> scale (graph 0) 
scale_vaapi (graph 0) -> Stream #0:0 (h264_vaapi) 
Stream #0:1 -> #0:1 (dts (dca) -> aac  
```

`ffmpeg: i965_encoder.c:1692: intel_enc_hw_context_init: Assertion encoder_context->mfc_context' failed.`

Try this, I think it's libs you might be missing. I hope it isn't non-free but it might be. 
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=910486

**Comment by Dragon988** [comment]
I've encoded one of the makemkv's into a regular H264 file with audio passthrough using handbrake and it still will not play using vaapi on the linux server or quicksync on my windows laptop.

NVENC works fine. I'm pretty sure at this point it's not an issue on my end as I've replicated the problem on two different devices with different hardware.

The only thing they have in common is the 630 iGPU.

**Comment by Artiume** [comment]
Try this
https://superuser.com/questions/1462402/ffmpeg-not-working-using-h264-vaapi/1462586

**Comment by Dragon988** [comment]
That fixed it!

**Comment by Artiume** [comment]
Awesome! I'm glad we could get it working. I'm not sure which section of the documents to update.

I was thinking perhaps we could suggest libraries to install here 
https://jellyfin.org/docs/general/administration/hardware-acceleration.html#setup
Or here
https://jellyfin.org/docs/general/administration/installing.html#packages-1 

You want to make some updates to how you think it would've been helpful?
