### ISSUE TITLE
Playlists aren't user specific

### ISSUE THREAD

**Issue by mcarlton00** [jellyfin/jellyfin#2410]
**Describe the bug**

Users have access to other users' playlists, rather than just their own.

**To Reproduce**

1. Create 2 users (UserA and UserB)
2. Create a playlist with UserA
3. UserB can't see the playlists folder
4. Create a playlist with UserB
5. Both users can see each other's playlists.

**Expected behavior**

Playlists should be limited in scope to the user who created them

**System (please complete the following information):**
 - OS: Yes
 - Browser: Yes
 - Jellyfin Version: 10.4.3 -> Feb 10 nightly

**Additional context**
Originally found by Matrix user "fossy"

**Comment by fosslinux** [comment]
This is accurate.

As well, each user can access media they do not have permission to in playlists. This is rather unrelated however, and I am told is a different more general permissions issue.

**Comment by JustAMan** [comment]
Note that there's actually some code that works with user-level playlists (at least in terms of reading them), so maybe we just don't have proper code in place to create them.

**Comment by Ling128** [comment]
Wish this issues could be fixed soon

**Comment by TheNamelessWonderer** [comment]
This issue also affects collections. If a user creates a collection on the server it is visible to everyone on the server.

**Comment by Methatronc** [comment]
I confirm the issue concerning the not-user specific playlist with Jellyfin Web 10.7.6.
However the last point concerning the collection is for me a feature instead of a bug, as I use the collection as a way to organize the movies for my users. Pease do not change this or if you do add a toggle allowing to decide as admin if a particular collection should be user-specific or not.

**Comment by rikrdo89** [comment]
Playlist created via the web interface or mobile app are showing up across all users, instead of being user specific. I tested on Jellyfin 10.7.7. Hopefully this issue gets taken care of soon.

**Comment by LubricantJam** [comment]
This still exists on 10.8 also. A user should be able to specify whether a playlist is public or not.

**Comment by Debouelesmorts** [comment]
Yes, the problem still exists with the latest versions (I'm talking about playlists, for collections, it's not surprising and it's the same for Plex). For a server with many users, this is a big problem...I love Jellyfin and I'm grateful for all the work done, but something like this would make me go back to Plex...

**Comment by CPU-Blanc** [comment]
Still present on 10.8.5
What's more is not only do other users have access to each other's playlists, it appears as though they can also edit and delete items from them.

**Comment by caretakerscurse** [comment]
As of Version: 10.8.10, still exists.

Are there any plans to change this?
Thank you, --cc

**Comment by crobibero** [comment]
Fixed by https://github.com/jellyfin/jellyfin/pull/9746

**Comment by Wraaath** [comment]
Still happening to me on vers. 10.8.13
