### ISSUE TITLE
[Feature] Move EasyPin auth from Plugin

### ISSUE THREAD

**Issue by crobibero** [jellyfin/jellyfin#2411]
https://github.com/jellyfin/jellyfin-plugin-ldapauth/pull/24#issuecomment-585078312

Move EasyPin authentication from plugin to core server

**Comment by JustAMan** [comment]
Can you provide a reason?

**Comment by dkanada** [comment]
The goal of EasyPIN is to allow convenient password input for devices like TVs and such so making it an auth provider might not work.

**Comment by JustAMan** [comment]
Why it won't work as a separate auth provider?.. I would think it could be an ideal candidate to join default and ldap ones.

**Comment by dkanada** [comment]
Wouldn't that be the same as simply setting the default password to a string of four numbers?

**Comment by JustAMan** [comment]
No? The whole point of having different pin and password is extra security when outside and relaxed when inside a trusted LAN.

**Comment by dkanada** [comment]
The question here is whether we want to keep the PIN methods in the authentication provider interface, not remove the PIN entirely.

**Comment by dkanada** [comment]
I brought up some thoughts in #2492 with @Polpetta regarding the authentication flow.
