### ISSUE TITLE
"Copy Stream URL" does not work on Firefox

### ISSUE THREAD

**Issue by h1nk** [jellyfin/jellyfin#2412]
**Describe the bug**
Using the "Copy Stream URL" function on Mozilla Firefox does not work, but it does work on Chromium.

**To Reproduce**
1. Use Firefox
2. Go to a music album in your Jellyfin instance
3. Click the ellipsis button for a music track
4. Click "Copy Stream URL"
5. Clipboard is unchanged

**Expected behavior**
The stream URL for the selected item should be copied to your clipboard.

**System (please complete the following information):**
 - OS: Ubuntu 18.04.4 LTS
 - Browser: Mozilla Firefox 72.0.2
 - Jellyfin Version: 10.4.3 (`jellyfin:latest` Docker Hub tag)
 - Installed Plugins: none/default Docker Hub image
 - Reverse proxy: nginx

**Additional context**
Issue is reproducible while using a freshly created Firefox profile (`firefox -P`) as well as `--safe-mode` to disable any potentially conflicting browser addons.

**Comment by neuroid** [comment]
See https://github.com/jellyfin/jellyfin-web/issues/557
