### ISSUE TITLE
Cant save network options

### ISSUE THREAD

**Issue by Peronia** [jellyfin/jellyfin#2414]
**Describe the bug**
When I change the "local networks" option unter "networking" and click save - nothing get saved.

**To Reproduce**

1. Go to "networking"
2. Change the field from "local networks"
3. Click on "save"
4. Refresh the site
5. Nothing will get saved

**Expected behavior**
I expected that the setting get saved that I can reboot the server to take this effect.

**Logs**
The arent any issues in the log.

**Screenshots**
The change that should get saved:
![image](https://user-images.githubusercontent.com/25049991/74602404-5d674c00-50a8-11ea-828f-22270aafb664.png)
After pagereload:
![image](https://user-images.githubusercontent.com/25049991/74602415-7839c080-50a8-11ea-99b6-4fef585a8dd4.png)
That also not working:
![image](https://user-images.githubusercontent.com/25049991/74602423-8ee01780-50a8-11ea-829d-a05dd932e0b7.png)

**System (please complete the following information):**
 - OS: Debian Buster
 - Browser: Chrome
 - Jellyfin Version: 10.4.3
 - Installed Plugins: Reports
 - Reverse proxy: no

**Comment by PrplHaz4** [comment]
Make sure your secure connection mode is disabled unless you have an SSL cert loaded - that will prevent the page from saving.

**Comment by dkanada** [comment]
Does the loading animation continue endlessly or does a dialog show up when you click save?

**Comment by Peronia** [comment]
Im currently using only http.
2 dialogs popup:
![image](https://user-images.githubusercontent.com/25049991/74682672-fd1afc00-51c6-11ea-90b3-5dbac4e4f573.png)
![image](https://user-images.githubusercontent.com/25049991/74682685-06a46400-51c7-11ea-950f-e6cf510bba4c.png)

I say always "verstanden" and then nothing happens. No loading cycle, nothing. When I reload the page, all changes are gone.

**Comment by Artiume** [comment]
So instead of trying CIDR notation, try subnet masking notation. I'm not sure if that'll work. I use 192.168.1.0/255.255.255.0

I'm running nightly so it might be a 10.4.3 problem. I was able to use both CIDR and subnet masking.

**Comment by Peronia** [comment]
Subnet masking notation don't work.
It looks like you've already fixed the problem, is there a workaround?

**Comment by Artiume** [comment]
You could try directly editing config files but I don't know if the bug was a frontend or backend issue. You could potentially bork your system

**Comment by Peronia** [comment]
Shuold I wait for the next release to use this option?

**Comment by Artiume** [comment]
Yes. Soon :)

**Comment by mark-monteiro** [comment]
I think this should be fixed with this PR: https://github.com/jellyfin/jellyfin-web/pull/929

@Peronia  There's a new release that just came out today. can you try updating and confirm if this was fixed?

**Comment by Peronia** [comment]
This bug is fixed, but I found another one. The OS cant be propper detected
![23-03-_2020_15-24-49](https://user-images.githubusercontent.com/25049991/77326825-aac78080-6d1a-11ea-86c6-fd1543e0f7b0.png)

**Comment by mark-monteiro** [comment]
@Peronia Can you open a new issue for the OS detection issue using our bug report template? I'm going to close this issue since the original problem has been resolved.

**Comment by Artiume** [comment]
@Peronia No need to make a new issue. It's already fixed

https://github.com/jellyfin/jellyfin-web/pull/939
