### ISSUE TITLE
Ignore studio tags from episode

### ISSUE THREAD

**Issue by accountForIssues** [jellyfin/jellyfin#2415]
**Describe the bug**
The networks tab under TV shows currently displays TV shows and it's episodes for each of the networks.

**To Reproduce**
1. Go to Networks Tab under TV Show.
2. Click on a Network, eg. HBO.
3. You'll see Episodes of Westworld and Westworld as the results.

**Expected behavior**
Only show Westworld as the result. It's understood that if Westworld aired on HBO, all the episodes were aired on HBO as well.

**Additional context**
I use tinyMediaManager to scrape all my media before Jellyfin scans everything. Jellyfin doesn't have access to internet scraping and writing nfos locally. Everything is handled via tMM.

tMM exports Kodi supported nfo files and Jellyfin has no trouble reading them (besides a few not-so-important tags).

I don't know what Jellyfin would do if allowed to scrape on it's own but currently all the episode nfos also have "studio" tags that are inherited from the "tvshow" nfo. This is normal behaviour under Kodi style nfo which Jellyfin supports.

So I'm assuming while reading metadata, Jellyfin reads the studio tag of the episode and imports it into it's metadata store which is fine but when displaying the results, it should only display a TV show and not it's episodes.

The solution is either to ignore the studio tag from episode metadata while scraping (don't know if it has any use) and only keep it from tv-show nfo or season nfo.
OR
While querying, only query items of 'tv show' type with the 'selected network'.

---
I hope I made the issue clear. I think it should be fairly easy to correct.

**Comment by realityfabric** [comment]
This is still an issue in 2024. I am working around the issue by removing the studio tags from episodes.

It also includes movies with studio tags. I don't mind this, but was confused at first because it is under the TV section.

A potential fix for this issue would be adding a filter to display only shows/movies/episodes and allow the admin to set a default.

**Comment by felix920506** [comment]
@realityfabric please open a new issue.

**Comment by realityfabric** [comment]
It isn't exactly a bug, and it looks like feature requests are meant to be submitted elsewhere. I'll look into submitting there, thank you!
