### ISSUE TITLE
Thumbnails not showing when on Wi-Fi

### ISSUE THREAD

**Issue by SemperVis** [jellyfin/jellyfin#2417]
**Describe the bug**
When the device is on Wi-Fi, the thumbnails are all blacks.

**To Reproduce**
1. Go on the main page with a device on Wi-Fi.
2. See error

**Expected behavior**
See the thumbnails as if I was on ethernet.

**Logs**
Don't know which log could be useful

**Screenshots**
[Screenshot](https://i.imgur.com/cK8d0pX.png?1)
![cK8d0pX](https://user-images.githubusercontent.com/1011526/74674618-d8bd2080-51c2-11ea-8c0e-6112b22fe805.png)

**System (please complete the following information):**
 - OS: Debian
 - Browser: Firefox, Chrome, Safari
 - Jellyfin Version: 10.4.3
 - Installed Plugins: Fanart, Open Subtitles
 - Reverse proxy: NGINX

**Comment by JustAMan** [comment]
Are you passing through same reverse proxy when you're on ethernet? There's no code to detect wifi vs ethernet, so it must be something in your setup that triggers this behaviour.

I think you'd have to dig deeper to see not only the bug manifestation, but something that causes it. Without that I doubt we would be able to help you.

Looking into browser console would certainly help.
