### ISSUE TITLE
Add support for TV air/release order

### ISSUE THREAD

**Issue by joshuaboniface** [jellyfin/jellyfin#243]
Add support for choosing between TV air order and release order when fetching Metadata. This was a longterm grip I had with Emby, and fixing this manually is a pain. It should be an option when grabbing the metadata in the first place.

**Comment by SenorSmartyPants** [comment]
Do you mean choosing between "standard" episode numbering based on air date and episode numbering based on "dvd" order. I'm using the terminology that TVDB uses.

Isn't that what the series "display order" is for? Or is that only display and episodes are still numbered by air date?

**Comment by SenorSmartyPants** [comment]
So I just did this in Jellyfin without too much hassle.

I have "The Venture Bros." in my collection saved and number in dvd episode order.

Jellyfin imports them and assumes aired order which is incorrect. 
Go to Series, Edit Metadata, set display order to DVD, Save.
Then still on the series, select refresh metadata, Replace all metadata and check replace existing images.

That got everything fine as far as I can see. My problem in the past was that I wouldn't check replace existing images and I would have the wrong episode screenshots.

**Comment by joshuaboniface** [comment]
Huh well that's easy! If only I had been able to find documentation from that project on it :roll_eyes: Thanks a lot @SenorSmartyPants !

**Comment by SenorSmartyPants** [comment]
No problem. Anyway I can save you time so you can work on making things better!

**Comment by JustAMan** [comment]
@joshuaboniface I think this warrants a wiki page.
