### ISSUE TITLE
FLAC playback interrupts on Firefox on specific songs

### ISSUE THREAD

**Issue by DoctorMacc** [jellyfin/jellyfin#2430]
On very specific music files (I believe they are always FLAC), playback will *always* stop at the same spot. Sometimes, after several minutes, the playback resumes; I believe after a certain point the music will always resume (not the same duration for every file). This does not happen on Chrome but it does happen on Firefox.

**Media Info of the file**
```
Container flac
Path /mnt/media/Music/Panic! at the Disco/Too Weird to Live, Too Rare to Die!/02 - Miss Jackson (ft. Lolo).flac
Size 22 MB
Audio
Title FLAC stereo
Codec FLAC
Layout stereo
Channels 2 ch
Sample rate 44100 Hz
Bit depth 16 bit
Default No
```
Always stops at 31-32 seconds

```
Container flac
Path /mnt/media/Music/Billy Joel/An Innocent Man/05 - Tell Her about it.flac
Size 74 MB
Audio
Title FLAC stereo
Codec FLAC
Layout stereo
Channels 2 ch
Sample rate 88200 Hz
Bit depth 24 bit
Default No
```
Stops at around 1:48.

**Logs**
```
[2020-02-04 12:34:08.606 -05:00] [WRN] HTTP Response 204 to "EXTERNALIP". Time (slow): 0:00:00.685086. "http://jellyfin.domain.com/Sessions/Playing/Progress"
[2020-02-04 12:34:11.974 -05:00] [ERR] Error processing request: "A task was canceled."
[2020-02-04 12:34:12.083 -05:00] [WRN] HTTP Response 204 to "INTERNALIP". Time (slow): 0:00:00.5124965. "http://jellyfin.domain.com/Sessions/Playing/Progress"
[2020-02-04 12:34:12.572 -05:00] [WRN] HTTP Response 200 to "EXTERNALIP". Time (slow): 0:00:00.6112023. "http://jellyfin.domain.com/Items/03f694e813f42344829f80a56731af76/Images/Primary?maxHeight=318&maxWidth=212&tag=094fad7527ffab3a2aab41ce1df4d2c3&quality=90"
```
**FFmpeg Logs**
No FFMPEG transcode logs. `ffplay` version 4.2.2 plays the file with no issues on Solus Linux.

**Server System (please complete the following information):**
 - OS: Debian VM in FreeNAS
 - Jellyfin Version: 10.4.3 and 20200219 nightly.
 - Hardware settings & device: No hardware decoding, Xeon E5649
 - Reverse proxy: Nginx
 - Other hardware notes: All media stored on NFS share
 
**Client System (please complete the following information):**
 - Device: Firefox
 - OS: macOS and Linux
 - Client: Browser
 - Browser (if Web client): Firefox
 - Client and Browser Version:  Various / New versions

**Comment by telans** [comment]
Is there anything logged in the Firefox console?

**Comment by DoctorMacc** [comment]
`Requesting url without automatic networking: https://jellyfin.domain.com/Sessions/Playing/Progress` but it's not tied to the stopping.

**Comment by JustAMan** [comment]
Can you try downloading that FLAC file and play it in Firefox directly? I think I heard about Firefox having issues reading some FLAC files...

**Comment by JustAMan** [comment]
@DoctorMacc see this: https://github.com/jellyfin/jellyfin/issues/1471#issuecomment-569536306

**Comment by DoctorMacc** [comment]
Opening the files directly in Firefox does cause them to stop. Closing this then since it's not a Jellyfin issue. Thanks for the help.
