### ISSUE TITLE
Enhancement : Ignore Files In Scanned Libraries

### ISSUE THREAD

**Issue by evoelise** [jellyfin/jellyfin#2437]
Request for an enhancement to ignore files the match a list of wildcards when scanning a library.

I have a JellyFin server running on Unix but in the media libraries I have many auto-generated .m3u files that contain Windows paths and these fail on a Linux server which fills the Jellyfin server logs with loads of errors (this obscures real issues).

My suggestion is to add a option on the libraries to specify a comma separated list of file wildcards that cause scanning to ignore any files that match.

**Comment by Artiume** [comment]
A filter would definitely be nice. Something else that probably should be done with M3U specifically is to maintain a record of its timestamp. If the timestamp hasn't been touched, don't rescan the file.

**Comment by Fleshgrinder** [comment]
My situations is different but requires the ability to ignore things via patterns as well:

```
[19:13:21] [ERR] [9] LibraryMonitor: Error in Directory watcher for: /media/music
System.UnauthorizedAccessException: Access to the path '/media/music/@eaDir/SYNO@.fileindexdb' is denied.
[19:13:21] [INF] [9] LibraryMonitor: Stopping directory watching for path /media/music
```

These `@eaDir` directories with super special permissions are created by my Synology NAS for shared folders and in this particular case by the Synology Drive application. I now need to change ownership so that Jellyfin can read these files or it refuses to index my music.

I found [this](https://www.reddit.com/r/jellyfin/comments/ama9ss/is_it_possible_to_have_jelly_fin_not_add_certain/) and [this](https://www.reddit.com/r/jellyfin/comments/awldea/ignore_smallsample_files/) Reddit threads where the same or similar features where requested.

**Comment by Fleshgrinder** [comment]
Active

**Comment by evoelise** [comment]
This enhancement is still required.

**Comment by dovry** [comment]
Plex has a `.plexignore` file you can place with your media to ignore files that match what you write in it.

https://support.plex.tv/articles/201381883-special-keyword-file-folder-exclusion/

**Comment by Shadowghost** [comment]
It's not like we don't know about this. The feature just has no priority at the moment for anyone on the team. PRs are as always welcome though.

**Comment by crobibero** [comment]
> 
> 
> Plex has a `.plexignore` file you can place with your media to ignore files that match what you write in it.
> 
> https://support.plex.tv/articles/201381883-special-keyword-file-folder-exclusion/

We already have this.
https://github.com/jellyfin/jellyfin/blob/a814d01f8c6edab930877031cd9e323f9ceda9d0/Emby.Server.Implementations/Library/LibraryManager.cs#L654

**Comment by evoelise** [comment]
Something like the `.plexignore` file would work but it would probably be more user friendly to add this to the web site configuration pages.

The Jellyfin `.ignore` file is different and ignores all files in this directory and sub directories rather than just ignoring by wild cards.

**Comment by cryodream** [comment]
IMHO, the `.plexignore` files is the **most useful and powerful** way to implement ignore system.
A couple of suggestions:
* Please, either use the same `.plexignore` filename, or support it as an alternative name.
* Please, add support for `.plexignore` files first. Configuring this in the UI would be nice, but way less important, than the functionality itself.

**Comment by cvium** [comment]
> Please, either use the same .plexignore filename, or support it as an alternative name.

That will never happen.

**Comment by howlett** [comment]
Yes, I would also like to see a way to hide specific filetypes for my raw images.

**Comment by nielsvanvelzen** [comment]
It should be possible to create a plugin implementing the IResolverIgnoreRule interface if you want additional ignore rules. It might be possible to create one that reads .plexignore files too.

**Comment by cvium** [comment]
This belongs on our feature request site: https://features jellyfin.org

**Comment by arition** [comment]
For anyone who interested: I created a plugin that will read `.jellyfinignore` files and ignore corresponding files.

https://github.com/arition/jellyfin-plugin-ignore

**Comment by cholzer79** [comment]
> For anyone who interested: I created a plugin that will read `.jellyfinignore` files and ignore corresponding files.
> 
> https://github.com/arition/jellyfin-plugin-ignore

How do I install this? :)

**Comment by arition** [comment]
> > For anyone who interested: I created a plugin that will read `.jellyfinignore` files and ignore corresponding files.
> > https://github.com/arition/jellyfin-plugin-ignore
> 
> How do I install this? :)

Check https://jellyfin.org/docs/general/server/plugins/index.html#manual

**Comment by snakyjake1** [comment]
> For anyone who interested: I created a plugin that will read `.jellyfinignore` files and ignore corresponding files.
> 
> https://github.com/arition/jellyfin-plugin-ignore

Is there a "manifest.json" file so I can install via Jellyfin UI?

**Comment by Cyph3r** [comment]
+1

**Comment by petronny** [comment]
> Is there a "manifest.json" file so I can install via Jellyfin UI?

Hi, I create a `manifest.json` for the jellyfinignore plugin here: https://github.com/petronny/jellyfin-plugin-ignore/raw/master/manifest.json  
And I've also created a PR for that. https://github.com/arition/jellyfin-plugin-ignore/pull/3
Please use 
https://github.com/arition/jellyfin-plugin-ignore/raw/master/manifest.json instead when the PR is merged.
