### ISSUE TITLE
Enable real time monitoring : on, delete file, poster movie still present

### ISSUE THREAD

**Issue by lelamamalgache** [jellyfin/jellyfin#2438]
Hello jellyfin devs :)

**Describe the bug**
When i delete a movie from radarr (database and file), the movie is still present on my jellyfin library even if the library has the checkox is tick "Enable real time monitoring : changes to files will be processed immediately, on supported file systems"

**System (please complete the following information):**
 - OS: Nas synology, docker
 - Virtualization: docker
 - Clients: browser
 - Browser: Chrome
 - Jellyfin : linuxserver-jellyfin Version 10.4.3
 - Reverse Proxy: linuxserver-letsencrypt
 - Base URL: https://jellyfin.domain.fr
 - Storage: local

**To Reproduce**
delete a movie file from a windows share then wait 2 minutes, go to jellyfin, the poster movie is still present on jellyfin and when you try to play it "PlaybackErrorNoCompatibleStream"

Someone from radarr discord, test it with emby, the poster movie has been correctly remove.

Could you have a look on it ?

Regards,

le lama malgache

**Comment by Bond-009** [comment]
Real time monitoring doesn't work on all filesystems

**Comment by Artiume** [comment]
To add on to @Bond-009's statement, Nfs doesn't support inotify (one of the methods for Linux) but I wrap the file system with mergerfs and it's RTM capable.

What's your local file system for the media?

**Comment by lelamamalgache** [comment]
Thank for your replies,

Sorry if i say something stupid :
i think my file system is "Btrfs" on my synology nas
for sharing, i'm using afp and smb, i could active also nfs which is disabled

jellyfin is running on a docker linuxserver-jellyfin

**Comment by Artiume** [comment]
Figured out the issue `delete a movie file from a windows share then wait 2 minutes `. Remote file systems don't support inotify.  Btrfs supports inotify, but the media isn't local in that instance. You'll have to do what I do and use a wrapper file system, I personally use mergerfs, but I don't know how well it'd work for your synology.

**Comment by lelamamalgache** [comment]
Ok thanks for your help, i checked on web about inotify emby and synology, that smells unresolved or tricky, i prefer to wait the task "media scan library" than type some random commands to my nas :)

Which files system could you recommand for Real time monitoring ? maybye that will help others people

**Comment by Artiume** [comment]
So mergerfs is a [union file system](https://en.wikipedia.org/wiki/Union_mount).

here's the instructions for Synology. They don't seem too bad, but I don't run Synology so I don't know.
https://github.com/trapexit/mergerfs/wiki/Installing-MergerFS-on-a-Synology-NAS

Another option is to use API keys between Jellyfin and Sonarr/Radarr. This might be an easier method, but I never set it up lol.

**Comment by lelamamalgache** [comment]
yes i have seen "Installing-MergerFS-on-a-Synology-NAS", i don't want to use it

i used API keys between Jellyfin and Sonarr/Radarr, works for new movie or upgrade but doesn't work for delete
