### ISSUE TITLE
After upgrading from 10.3 to 10.4.3, can't use the moviedb to get movie information

### ISSUE THREAD

**Issue by lsl061085** [jellyfin/jellyfin#2445]
OS: [Ubuntu Server 18.04.2]
Clients: [Browser]
Browser: [ Chrome 79]
Jellyfin Version: [10.4.3, stable 20191207]

Error Logs：
[2020-02-23 15:22:26.695 +08:00] [ERR] "TmdbImageProvider" failed in GetImageInfos for type "Movie"
System.Net.Http.HttpRequestException: Network is unreachable ---> System.Net.Sockets.SocketException: Network is unreachable

I use curl in Ubuntu server to test that the cover image of the moviedb can be downloaded and saved normally.
```
curl -o test.jpg https://image.tmdb.org/t/p/w500/wWzGAWmdX7IL1mOYyhiYKso0FrI.jpg
 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                                     Dload  Upload   Total   Spent    Left  Speed
100 70838  100 70838    0     0  48058      0        0:00:01  0:00:01 --:--:-- 48058
```

**Comment by XiaolinYi** [comment]
same problem as me

**Comment by JustAMan** [comment]
Can you provide logs with more context?

Also cc @cvium and @Bond-009

**Comment by lsl061085** [comment]
> Can you provide logs with more context?
> 
> Also cc @cvium and @Bond-009

Now I can get movie information through the moviedb scraper by adding an available IP to hosts. The firewall should block the network link to api.themoviedb.org.
