### ISSUE TITLE
Clean up the portable release package

### ISSUE THREAD

**Issue by iWangJiaxiang** [jellyfin/jellyfin#2450]
**Describe the bug**

The portable release package `jellyfin_10.4.3_portable.tar.gz` contains unnecessary assemblies like `XUnit` and `CodeCoverage` folder. 

**To Reproduce**

1. Download <https://github.com/jellyfin/jellyfin/releases/download/v10.4.3/jellyfin_10.4.3_portable.tar.gz>
2. See contents inside

**Expected behavior**

Since this is a release package, I think we should remove/ignore those contents in `DevOps` package stage.

**Screenshots**

![image](https://user-images.githubusercontent.com/19409802/75114954-67cfaa00-5695-11ea-854e-e2942b970603.png)

![image](https://user-images.githubusercontent.com/19409802/75114969-859d0f00-5695-11ea-8f09-953c12fafaa6.png)

**Comment by dkanada** [comment]
cc @Bond-009

**Comment by Bond-009** [comment]
Should be fixed in master, can you check the nightlies?

**Comment by iWangJiaxiang** [comment]
@Bond-009 Thank you. Fixed indeed~
