### ISSUE TITLE
How to sort my media library ?

### ISSUE THREAD

**Issue by backtracker** [jellyfin/jellyfin#2453]
for example I want put music library  to the first place，How can i do it?

**Comment by Artiume** [comment]
Here ya go

https://jellyfin.org/docs/general/server/media/music.html

**Comment by backtracker** [comment]
Sorry，You misunderstood me @Artiume 
 [![1582526246.png](https://i.postimg.cc/pX9R1dVh/1582526246.png)](https://postimg.cc/SJpBnkMk)
You misunderstood me，I want put “音乐” to the "Movies" place。How can i do it ?

**Comment by AkatsukiiDesu** [comment]
If you click on the Person icon (2nd from the left in the top right hand side) and then go to the "Home" option, there will be an option to change the library order. If you need any more help please let me know.

**Comment by backtracker** [comment]
@AkatsukiiDesu  tks

**Comment by JustAMan** [comment]
@backtracker can this issue be closed?

**Comment by backtracker** [comment]
question solved
