### ISSUE TITLE
Media content identified as needing Profiles

### ISSUE THREAD

**Issue by Artiume** [jellyfin/jellyfin#2454]
**Describe the bug**

Media items are being identified as needing profiles. Doesn't seem right.

**Logs**

`[2020-02-23 20:08:44.760 -05:00] [INF] [13] App: Profile: "Unknown Profile", No direct play profiles found for Path: "/media/Documentaries/Treasures of Ancient Egypt/Season 1/Treasures of Ancient Egypt - S01E02 - The Golden Age HDTV-720p.mkv"`
**Screenshots**

**Additional context**

nightly20200223

**Comment by dkanada** [comment]
What client?

**Comment by Artiume** [comment]
No client running. This is during database initialization
