### ISSUE TITLE
HTTP Response Warning sensitivity

### ISSUE THREAD

**Issue by Artiume** [jellyfin/jellyfin#2455]
Should this be giving a slow warning for half a second? maybe bump it up to 2 seconds or something?
`[2020-02-23 19:55:15.788 -05:00] [WRN] [26] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to "199.229.249.167". Time (slow): 0:00:00.5072683. "http://domain/Users/effe87127b6b4ff2934121a09e9ca045/Items/Latest?Limit=16&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=c248dc0bec4b0ce8fb01231d1f12c5c1"`
also, any reason it'd be accessing it over http but using my fqdn? Seems like it should be https

**Comment by dkanada** [comment]
@Bond-009 I thought this was changed to debug level?

**Comment by PrplHaz4** [comment]
> also, any reason it'd be accessing it over http but using my fqdn? Seems like it should be https

I think the reason is secure connection settings. Jellyfin is not proxy aware so unless you have an SSL cert loaded it doesn't know you're using ssl.

**Comment by Artiume** [comment]
I don't think that'd be it. If it's attempting it via by my FQDN, it'd still go through my reverse proxy. I also tried changing the network setting to Handled by Reverse Proxy and same issue. I feel like it should either It pass through 127.0.0.1 or use https

**Comment by PrplHaz4** [comment]
> 
> 
> I don't think that'd be it. If it's attempting it via by my FQDN, it'd still go through my reverse proxy. I also tried changing the network setting to Handled by Reverse Proxy and same issue. I feel like it should either pass through 127.0.0.1 or use https

That log entry is from the jf web server - is your proxy connecting to the jf web server using ssl?

**Comment by Artiume** [comment]
No, but if the web server is using the FQDN (just like a browser), it doesn't need the ssl. Currently, I think it's creating mixed content. Let me see what happens when I close port 80 on my router (I have HSTS loaded so for normal browsers this is an acceptable approach). If I start getting errors, it's mixed content, if it doesn't, it's not actually using my FQDN but incorrectly reporting it as so

**Comment by PrplHaz4** [comment]
> 
> 
> No, but if the web server is using the FQDN (just like a browser), it doesn't need the ssl cert. Currently, I think it's creating mixed content. Let me see what happens when I close port 80 on my router (I have HSTS loaded so for normal browsers this is an acceptable approach). If I start getting errors, it's mixed content, if it doesn't, it's not actually using my FQDN but incorrectly reporting it as so

Probably worth a new issue...

If the jf web server is receiving the request from the RP over http not https, why would it log https?
```
browser (https:443) -> RP (https:443) -> jf server (http:8096) -> log (http)
```

I'm more surprised the logged url doesn't specify port 8096

**Comment by Artiume** [comment]
So I closed port 80 and not receiving any errors for it using http. Yeah, if it was using 8096 at all, it would say it in the url. I'll dig into it more later with debug mode on.

**Comment by eltiel** [comment]
> Should this be giving a slow warning for half a second? maybe bump it up to 2 seconds or something?

Was this never changed? It still shows up as a warning for half a sec. It's generating way too many log entries

**Comment by Artiume** [comment]
Try deleting your logging.json file and restarting

**Comment by eltiel** [comment]
I already did. This is the latest, no?

```
{
    "Serilog": {
        "MinimumLevel": {
            "Default": "Information",
            "Override": {
                "Microsoft": "Warning",
                "System": "Warning"
            }
        },
        "WriteTo": [
            {
                "Name": "Console",
                "Args": {
                    "outputTemplate": "[{Timestamp:HH:mm:ss}] [{Level:u3}] [{ThreadId}] {SourceContext}: {Message:lj}{NewLine}{Exception}"
                }
            },
            {
                "Name": "Async",
                "Args": {
                    "configure": [
                        {
                            "Name": "File",
                            "Args": {
                                "path": "%JELLYFIN_LOG_DIR%//log_.log",
                                "rollingInterval": "Day",
                                "retainedFileCountLimit": 3,
                                "rollOnFileSizeLimit": true,
                                "fileSizeLimitBytes": 100000000,
                                "outputTemplate": "[{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz}] [{Level:u3}] [{ThreadId}] {SourceContext}: {Message}{NewLine}{Exception}"
                            }
                        }
                    ]
                }
            }
        ],
        "Enrich": [ "FromLogContext", "WithThreadId" ]
    }
}
```

**Comment by Artiume** [comment]
mine doesnt have 
```
                "Microsoft": "Warning",
                "System": "Warning
```
is that a windows specific thing? but yeah, that looks like mine

**Comment by PrplHaz4** [comment]
> 
> 
> mine doesnt have
> 
> ```
>                 "Microsoft": "Warning",
>                 "System": "Warning
> ```
> 
> is that a windows specific thing? but yeah, that looks like mine

No, it was introduced here to make logs less chatty: https://github.com/jellyfin/jellyfin/pull/2500 - it should have been applied to yours (via the new migration) if you upgraded to 10.5.0

**Comment by eltiel** [comment]
I'll still getting tons of this:

`[2020-03-11 00:02:56.122 +08:00] [WRN] [43] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 204 to "42.190.73.1". Time (slow): 0:00:01.1268363. "http://domain/Sessions/Playing/Progress"`

**Comment by Bond-009** [comment]
It's normal (for now)

**Comment by markuschaaf** [comment]
A year has past. And this still spams my logs. A feature that cannot be turned off is considered a bug. Please remove that warning or make it configurable or explain where to change it.

**Comment by Artiume** [comment]
https://github.com/jellyfin/jellyfin/blob/9360fecb316973181a120027f70b311b219740cd/MediaBrowser.Model/Configuration/ServerConfiguration.cs#L431

**Comment by crobibero** [comment]
> A year has past. And this still spams my logs. A feature that cannot be turned off is considered a bug. Please remove that warning or make it configurable or explain where to change it.

You can disable the warning entirely or change the threshold by editing system.xml in the config directory
