### ISSUE TITLE
Add "Comments" field

### ISSUE THREAD

**Issue by chowbok** [jellyfin/jellyfin#246]
It would be nice if movies/episodes had an additional metadata field for comments, for information that doesn't fit in the other fields.

**Comment by EraYaN** [comment]
We are moving all feature and enhancement requests to our new Fider platform [here](https://features.jellyfin.org/). This new platform lets people vote on and better manage such requests.
This request now lives [here](https://features.jellyfin.org/posts/52/add-comments-field).
