### ISSUE TITLE
Assign Users to TV Tuners

### ISSUE THREAD

**Issue by ExeCuteUK** [jellyfin/jellyfin#2460]
Hello,

Would it be possible to 
- Add users to specific TV Tuners ?
- Remove any live tv options on the home screen for users who do not have any TV Tuner access.

This would be able to help with issues such as children having access to M3U's with adult content.

It would also allow me to control stream limits which are set on each M3U Playlist and only allow specific users to access the tuner with the correct playlist so it does not "oversubscribe".

Would be an amazing feature for me as it would allow me to stop having to use external IPTV apps and have everything running fluid within JF.

**Comment by anthonylavado** [comment]
Created a feature request on your behalf here: https://features.jellyfin.org/posts/461/assign-users-to-tv-tuners
