### ISSUE TITLE
Book covers aspect ratio incorrect

### ISSUE THREAD

**Issue by w111a** [jellyfin/jellyfin#2461]
**Describe the bug**
When viewing the homepage of Jellyfin, the cover pictures for the books section are in the wrong aspect ratio; causing part of the cover to be cut off. 

**System (please complete the following information):**
 - OS: UnRaid 6.8.2
 - Virtualization: Docker
 - Clients: All
 - Browser: Firefox, Chrome
 - Jellyfin Version:10.4.3
 - Installed Plugins: Bookshelf, Fanart, 
 - Reverse Proxy: nginx
 - Base URL: none
 - Storage: local

**To Reproduce**
1. Go to the Jellyfin homepage
2. View cover images in the 'latest books' section.
3. Displayed similar to a music album instead of a movie poster. Causing part of the image to be cut off. 

**Expected behavior**
See an image with the proper aspect ratio which would display the complete image.

**Screenshots**
As discussed https://github.com/jellyfin/jellyfin-plugin-bookshelf/pull/6

**Additional context**
Upon further investigation it appears the problem persists throughout the books section. However, entering into the author 'folder', the complete cover image is shown, but still with the wrong aspect ratio.

**Comment by dkanada** [comment]
I looked into this and the issue was indeed on the server. It wasn't reporting the proper aspect ratio for the primary image when requested.

**Comment by NovaCyntax** [comment]
I have this issue but in the actual books overview, not the "Latest Books" section on the homepage. Similar experience with Authors.
