### ISSUE TITLE
Playback stops after a few seconds with remuxing to webm

### ISSUE THREAD

**Issue by cromefire** [jellyfin/jellyfin#2468]
**Media Info of the file**

Video: vp9 profile 0
Audio: opus
Subtitles: turned off

**Logs**

No useful information

**FFmpeg Logs**

No logs created

**Stats for Nerds Screenshots**

![image](https://user-images.githubusercontent.com/26320625/75278063-8060d100-5809-11ea-9c2b-337b337348c7.png)

**Server System (please complete the following information):**
 - OS: Linux
 - Jellyfin Version: 10.4.3
 - Hardware settings & device: Not applicable
 - Reverse proxy: apache
 - Other hardware notes: Media on NFS share mounted into container via LXD
 
**Client System (please complete the following information):**
 - Device: Desktop
 - OS: Linux
 - Client: Web
 - Browser (if Web client): FF
 - Client and Browser Version: 73

**Comment by Artiume** [comment]
The title is incorrect in that it didn't remux, it Direct Played.

Any error issues in the browser console logs? FF is seeing the issue, can you test Chrome as well?

The version is 10.4.3, can you test nightly?

**Comment by cromefire** [comment]
> The title is incorrect in that it didn't remux, it Direct Played.

It states webm as container, which is not supported by firefox and it includes subtitles firefox could not play, when I add subtitles it transcodes

> Any error issues in the browser console logs? FF is seeing the issue, can you test Chrome as well?

No, I'll test Chrome

> The version is 10.4.3, can you test nightly?

Not easily it's installed via deb packages

**Comment by cromefire** [comment]
Chrome plays mkv directly so...

**Comment by Artiume** [comment]
>     The title is incorrect in that it didn't remux, it Direct Played.
> It states webm as container, which is not supported by firefox and it includes subtitles firefox could not play, when I add subtitles it transcodes 

It says webm but that's just because there's currently a bug that reports **all** mkv as webm :P

>     The version is 10.4.3, can you test nightly?
> Not easily it's installed via deb packages

I'd like to verify it's a real bug though. I don't care about 10.4.3 at this point, it's legacy.

**Comment by cromefire** [comment]
> It says webm but that's just because there's currently a bug that reports all mkv as webm :P

It correctly shows mkv in chrome and also delivers stream.mkv to chrome and stream.webm to ff

> I'd like to verify it's a real bug though. I don't care about 10.4.3 at this point, it's legacy.

Is there a nightly deb?

**Comment by Artiume** [comment]
https://jellyfin.org/downloads/

If you aren't getting ffmpeg logs, ffmpeg isn't being called.

**Comment by cromefire** [comment]
Same problem on nightly

**Comment by Artiume** [comment]
Check console errors to see what's coming up, if this is the same issue that I think it is, that's going to be only place to find error reports.

**Comment by cromefire** [comment]
No errors in the console

**Comment by cromefire** [comment]
Confirmed: it's because it's mkv
