### ISSUE TITLE
Extras no longer work

### ISSUE THREAD

**Issue by cryptobank** [jellyfin/jellyfin#2484]
I can no longer see Special features. This used to work and stopped working recently. I'm on a nightly about a week old.

My directory structure is MovieName/MovieName.mkv
and extras go to MovieName/Extras.

**Comment by JustAMan** [comment]
Can you check if they still work for your file structure on 10.4.3?

**Comment by cryptobank** [comment]
I can confirm this isn't working on 10.4.3 either, strange. It definitely used to work a while back.

**Comment by logic** [comment]
This happened to me after upgrading to today's 10.5 release, fwiw.

**Comment by JustAMan** [comment]
What about 10.5.0? We most likely aren't going to fix 10.4.x.

**Comment by dtparr** [comment]
Seeing this in 10.5.0.  There were a few folder names that were working before in addition to extras.  None seem to be now.
