### ISSUE TITLE
Include commit sha in application version

### ISSUE THREAD

**Issue by nvllsvm** [jellyfin/jellyfin#249]
**Current**
The application version has not changed since the fork from Emby. It has been the same for every release thusfar. It is thus a bug two different releases have the same version.

**Desired**
The application version, currently specified in [`SharedVersion.cs`](https://github.com/jellyfin/jellyfin/blob/master/SharedVersion.cs#L3), includes the commit sha.

The current commit sha may be retrieved from the command line with `git rev-parse HEAD`

**Reason**
Jellyfin has no versioning pattern defined as all versions have been the same, albeit for different releases. Having the commit sha would allow one to know the specific code base used.

**Potential Issues**
Including the commit sha in API payloads may break existing clients.

**Comment by JustAMan** [comment]
I think we should better settle on some proper versioning instead and up it at each release.
Showing `sha` somewhere in the UI is definitely worth having, though.

**Comment by anthonylavado** [comment]
I think we should close this, and move to another, fresh discussion on how to represent this.

Sound good?
