### ISSUE TITLE
Feature request - dashboard - actives devices - monitoring real time

### ISSUE THREAD

**Issue by lelamamalgache** [jellyfin/jellyfin#2494]
Hello devs :)

**Describe the bug**
From the "dashboard", then "actives devices", we can see people connected and what they are watching with the real time of the tv show or the movie, if i wait like 2 minutes the time is the same (see screenshot below)

If i want to get the new real time of the tv show show or the movie, i have to refresh the page with F5 or click again to the dashboard button.

**System (please complete the following information):**
 - Virtualization: docker
 - Clients: web browser or android app mobile
 - Browser: chrome
 - Jellyfin Version: linuxserver-jellyfin:latest
 - Reverse Proxy: nginx

**Feature request**
Get the real time of the active device and the item which is played

**Screenshots**
<img width="642" alt="dashboard" src="https://user-images.githubusercontent.com/58141187/75635911-72042200-5c1a-11ea-897e-e6b1cc6e7ed0.png">

**Comment by eltiel** [comment]
I can see the play time ticking every few seconds without needing to refresh the page. Might be something to do with not having websockets configured?

**Comment by hayer** [comment]
Works here, it updates every few seconds. Sometimes it can skip backwards or forwards a few seconds, but it works.

Can you check your developer console for errors? [If you don't know how](https://developers.google.com/web/tools/chrome-devtools/open).

**Comment by lelamamalgache** [comment]
OK, i did some tests

**PC**
it works on LAN with the local ip http://192.168.2.3:8096
it doesn't work on LAN with the fqdn of the reverse proxy linuxserver-letsencrypt https://jellyfin.domain.fr

**Mobile with only 4G**
it doesn't work on WAN with the fqdn of the reverse proxy linuxserver-letsencrypt https://jellyfin.domain.fr

**Developer console**
https://jellyfin.domain.fr  chrome (error)
```
apiclientcore.js?v=10.4.3:352 WebSocket connection to 'wss://jellyfin.domain.fr/socket?api_key=6b72033ed9264a41a725e6982605f001&deviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzc5LjAuMzk0NS44OCBTYWZhcmkvNTM3LjM2fDE1NzcyMjAxMDc4Njg1' failed: Error during WebSocket handshake: Unexpected response code: 404
ApiClient.openWebSocket @ apiclientcore.js?v=10.4.3:352
```

https://jellyfin.domain.fr microsoft edge (error)
`SCRIPT12008: SCRIPT12008: WebSocket Error: Incorrect HTTP response. Status code 404, Not Found`

http://192.168.2.3:8096 chrome & microsoft edge
no error, just two warnings







`

**Comment by hayer** [comment]
Which reverse proxy are you using? What does the configuration look like? Have you checked that your `Base URL` is set correctly in Jellyfin settings?

**Comment by lelamamalgache** [comment]
hey hayer :)

```
docker run -d \
       --name=letsencrypt \
       --cap-add=NET_ADMIN \
       --net=linuxserver \
       -v /volume1/Docker-config/Letsencrypt:/config \
       -e TZ=Europe/Paris \
       -e PUID=1026 \
       -e PGID=100 \
       -e URL=domain.fr \
       -e ONLY_SUBDOMAINS=true \
       -e SUBDOMAINS=jellyfin \
       -e VALIDATION=ovh \
       -e dns_ovh_endpoint=ovh-eu \
       -e dns_ovh_application_key=12345 \
       -e dns_ovh_application_secret=12345 \
       -e dns_ovh_consumer_key=12345 \
       -p 1443:443 \
       -p 180:80 \
linuxserver/letsencrypt:latest
```

i haven't set a Base URL, should i ?

screenshot of my network settings of jellyfin
<img width="616" alt="1" src="https://user-images.githubusercontent.com/58141187/75678905-eed0e380-5c8e-11ea-8335-67c3274ba1f5.png">
<img width="628" alt="2" src="https://user-images.githubusercontent.com/58141187/75678920-f3959780-5c8e-11ea-895e-cb05d3d6e92e.png">
<img width="617" alt="3" src="https://user-images.githubusercontent.com/58141187/75678929-f85a4b80-5c8e-11ea-820f-5512331929c0.png">

**Comment by hayer** [comment]
Sorry I can see now that my question was a bit unclear. 

Could you post your nginx reverse proxy configuration? :)

**Comment by JustAMan** [comment]
@lelamamalgache what your logs show is that something (probably your reverse proxy listening on your FQDN) doesn't pass websockets properly.
This doesn't sound like a Jellyfin bug or limitation...

**Comment by lelamamalgache** [comment]
```
# make sure that your dns has a cname set for jellyfin, if jellyfin is running in bridge mode, the below config should work as is, although,
# the container name is expected to be "jellyfin", if not, replace the lines "set $upstream_jellyfin jellyfin;" with "set $upstream_jellyfin <containername>;"
# for host mode, replace the lines "proxy_pass http://$upstream_jellyfin:8096;" with "proxy_pass http://HOSTIP:8096;" HOSTIP being the IP address of jellyfin
# in jellyfin settings, under "Advanced" change the public https port to 443, leave the local ports as is, set the "external domain" to your url,
# and set the "Secure connection mode" to "Handled by reverse proxy"

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name jellyfin.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    location / {
        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_jellyfin jellyfin;
        proxy_pass http://$upstream_jellyfin:8096;
		
        proxy_set_header Range $http_range;
        proxy_set_header If-Range $http_if_range;
    }
	
    location ~ (/jellyfin)?/embywebsocket {
        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_jellyfin jellyfin;
        proxy_pass http://$upstream_jellyfin:8096;
		
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $http_connection;
   }
}
```
as they put in comment at the begin, i have modified the https port public 8920 to 443 and set my https://jellyfin.domain.fr to the url base, then restart all my containers, i couldn't acess to my jellyfin server throw reverse proxy, so i removed the fqdn on the field url base, it's working for access but doesn't work for real time monitoring

**Comment by aptalca** [comment]
@lelamamalgache you're using a really old proxy conf. Here's the current version: https://github.com/linuxserver/reverse-proxy-confs/blob/master/jellyfin.subdomain.conf.sample

**Comment by lelamamalgache** [comment]
thank you @aptalca , that fixed my problem of realtime monitoring actives devices and also the text message to send to users.

thank you @hayer to helping me :)
