### ISSUE TITLE
Rebrand

### ISSUE THREAD

**Issue by nvllsvm** [jellyfin/jellyfin#25]
- [x] Rename "Emby" to "Jellyfin" in all user-facing text
- [x] Replace all Emby logos
- [x] Replace all [emby.media](https://emby.media) links with [jellyfin.media](https://jellyfin.media)

**Comment by joshuaboniface** [comment]
Gonna start on item 1 now, hopefully it's not that hard.

**Comment by dkanada** [comment]
I would just say remove the links entirely, it looks like most of them are only referencing services we probably won't implement like connect and premiere. Seems like a useless addition when used for troubleshooting help as well, anyone would know to visit the website or repository for information.

Examples:
[sign up to connect](https://github.com/jellyfin/jellyfin/blob/e3b27706e53b777ad8ba3822a63a553498a31bfa/MediaBrowser.WebDashboard/dashboard-ui/connectlogin.html#L35)
[server update needed](https://github.com/jellyfin/jellyfin/blob/21a8d273782a1a71678131f17ebaafd2b997f286/MediaBrowser.WebDashboard/dashboard-ui/scripts/selectserver.js#L66)
[share using connect](https://github.com/jellyfin/jellyfin/blob/21a8d273782a1a71678131f17ebaafd2b997f286/MediaBrowser.WebDashboard/dashboard-ui/bower_components/emby-webcomponents/itemcontextmenu.js#L203)

**Comment by anthonylavado** [comment]
@dkanada I did change the links (as part of #23, merged in #32), with the note that they'll probably require more changes. Right now, this is more of a cleanup effort as we're trying to stabilize.

I'd imagine it's possible to remove some of the connect stuff, and the other signup link stuff, but we'd need to be sure we're not affecting something else first.

**Comment by JustAMan** [comment]
@drakus72 it's already pointing to non-existing mb3admin.local :) but it might be harder to completely remove it instead of simply shutting down home phoning.

**Comment by virtualdxs** [comment]
Might we want jellyf.in rather than jellyfin.media? Just a possibility. Domain's not taken.

**Comment by joshuaboniface** [comment]
@virtualdxs I debated grabbing that one too, but didn't really seem worth it - we already have 2.

**Comment by bfayers** [comment]
As a result of #332 and #27 is this done now?

**Comment by JustAMan** [comment]
I believe this should now be closed. @nvllsvm if you disagree please reopen.
