### ISSUE TITLE
i386 Debian support

### ISSUE THREAD

**Issue by joshuaboniface** [jellyfin/jellyfin#250]
It looks like Microsoft is in no hurry to support the `i386` architecture on Linux, cf. https://github.com/dotnet/core/issues/322

While we would one day like to support this, at this time we can't due to the lack of a framework.

This issue serves mostly as a notice of this, and will be reopened if and when Microsoft releases an `i386` .NET Core build.

**Comment by MagischerStock** [comment]
According to 
https://github.com/dotnet/runtime/issues/7335#issuecomment-1099573662
there is a build pipeline, SDKs for .NET 6 and .NET 7 preview 3, and a Nuget feed with the AppHosts etc here:
https://github.com/Servarr/dotnet-linux-x86
