### ISSUE TITLE
Add CODECS field to HLS master playlist

### ISSUE THREAD

**Issue by YouKnowBlom** [jellyfin/jellyfin#2505]
**Describe the bug**
Currently there is no `CODECS` field added to streams when generating the HLS master playlist. This breaks HLS playback on devices such as Chromecasts.

[Spec](https://tools.ietf.org/html/rfc8216#section-4.3.4.2)

**System (please complete the following information):**
 - OS: Linux
 - Virtualization: Docker
 - Clients: Google Cast
 - Browser: Chrome
 - Jellyfin Version: nightly
 - Playback: Transcode to TS
 - Installed Plugins: none
 - Reverse Proxy: nginx
 - Base URL: none
 - Networking: host
 - Storage: local

**Expected behavior**
Every `EXT-X-STREAM-INF` (in HLS Master playlist) should contain a CODECS field where all codecs found in the stream should be listed.

**Comment by YouKnowBlom** [comment]
I suppose `FRAME-RATE` and `RESOLUTION` could be included as well for future proofing.

This [fine poetry](https://github.com/jellyfin/jellyfin/blob/5276c75cdeb079cd0b24c4b2dc574a584d5817b6/MediaBrowser.Api/Playback/Hls/DynamicHlsService.cs#L729) says those are required for tvOS

**Comment by Artiume** [comment]
What's remaining for this? It's exciting that chromecast will be fully unlocked :)

**Comment by dkanada** [comment]
The field itself has been added so I'd say we can close this and open issues in the future if we come across bugs in the implementation.
