### ISSUE TITLE
Support changes to logging configuration defaults

### ISSUE THREAD

**Issue by mark-monteiro** [jellyfin/jellyfin#2511]
**Describe the bug**
Changes to default logging settings are not propagated to existing users who already have a `logging.json` settings file.

**Solution**
* On server startup write a `logging.default.json` file if one does not exist using the defaults bundled as a resource
* On server startup check for changes to default logging settings by comparing the hash of `logging.default.json` with the bundled resource file. If there are differences, move `logging.default.json` to `logging.default.old.json` (If overwriting, log a warning to the console but indicate this is normal when updating the server.). After the file has been moved, write the bundled resource file to `logging.default.json`
* Update logging configuration to first load `logging.default.json` and then merge `logging.json` over top of it
* Bonus points: perform a one time file move of `logging.json` to `logging.user.json` and load that file instead
* This should also be accompanied by an associated update in the documentation for logging configuration

**Comment by JustAMan** [comment]
> * If there are differences, move `logging.default.json` to `logging.default.old.json` (overwriting if necessary)

This should emit a warning to the logs (which could state that it is okay if you've just updated your Jellyfin instance).
