### ISSUE TITLE
Implement configuration file versioning

### ISSUE THREAD

**Issue by joshuaboniface** [jellyfin/jellyfin#2516]
In a number of cases so far, we've had need to forcibly modify configurations of upgraded systems in order to prevent user impact. i.e. Base URL, and now Transcode Throttling and Logging changes. There has been no good solution in the current setup that has allowed this to happen seamlessly.

I propose we implement configuration file versioning for both `server.xml` and `logging.json` to allow the server to detect when updates are required and make any adjustments, without repeating the change on restart/upgrade/etc.

I'm not sure how well C# supports something like this, but it does seem to me to be fairly easy to hack in and then have a "migrations" component that (a) verifies versions, and (b) can be used to apply config schema changes if required.

**Comment by JustAMan** [comment]
@joshuaboniface LOL I was faster with making a PR than you with making an issue 👅

**Comment by joshuaboniface** [comment]
@JustAMan *Get out of my brain...*

**Comment by Artiume** [comment]
Another issue is forced livetv transcoding. I had to make another config entry for it.

**Comment by JustAMan** [comment]
What do you mean here, did you make a new option to not flip a default, or what?

**Comment by Artiume** [comment]
https://github.com/jellyfin/jellyfin/pull/2160/files

 MediaBrowser.Model/Users/UserPolicy.cs  > LoC98 `ForceRemoteSourceTranscoding = false;` 

this will only be present in newly created users

**Comment by JustAMan** [comment]
I think ASP.NET `IConfiguration` used here is smart enough to default to _some_ value.
Plus adding an option to all users' configs isn't an easy task :)

**Comment by Artiume** [comment]
I'll try toggling the feature on users that don't have the variable and see if it's smart enough to add it to the config
