### ISSUE TITLE
EF Core Migration - Add User Permissions/Preferences

### ISSUE THREAD

**Issue by mark-monteiro** [jellyfin/jellyfin#2517]
Add user related permissions and preference from existing database schema (so far, only xml based ones have been added).

**Comment by grravity** [comment]
Want to point this issue out, and suggest it be highly looked into.

Actors and actresses leak over, like custom made ones or ones pulled from plugins. I think right there a start would be to allow admin to isolate plugins to certain people. For example if I have a plugin installed, and it pulls "actor profiles", it would be nice to be able to limit them from showing up at all for only certain users.

I'd say also ideally if an actor was created and added to a library specifically, then it shouldn't show up at all also if the other users don't have access to that library. But that could possibly cause issues or be more of a PITA. I think the plugin piece is a good start.

Also this issue occurs with collections, for example if a user creates a collection, and adds a picture to it, and doesn't put any content in it, that collection is visible to all users. Now if the creator of the collection, adds a file from a library that those users don't have access to, the collection disappears for them which is great. But there was no need for them to have been able to see that collection in the first place.

These are _shamelessly_ MASSIVE and Risky issues for people who run NSFW libraries in the same Jellyfin install as they run their Movies and other videos, and don't want to provide all users access to all users obviously. 
I know this is a nicher case, but this could fuck over a lot of people, I know I've seen people complain about this before, and I think permissions and library access NEEDS to be done well to avoid issues like this. It's not always NSFW content, people may have libraries for family videos, etc. that they don't want leaking over. Running two Jellyfin servers alongside each other for specific libraries is more resource intensive and more of a PITA to maintain. I think this is very important though set of issues, and should be worked on. Again my opinion though.
