### ISSUE TITLE
EF Core Migration - System Wide Settings

### ISSUE THREAD

**Issue by mark-monteiro** [jellyfin/jellyfin#2519]
Implement storage of system wide settings. Avoid "node" specific settings like bound IP, ports, hw accel, etc while migrating settings like default UI culture, metadata language, etc

**Comment by mark-monteiro** [comment]
I wonder if the ASP Configuration framework would be setter suited for this?
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.1

**Comment by sevenrats** [comment]
@mark-monteiro should this be reviewed by the team or closed?

**Comment by mark-monteiro** [comment]
This issue is related to moving existing settings (currently stored in XML files) into the database, but I don't think there is consensus on whether this is desirable. This may be better suited as a discussion or an issue in jellyfin-meta.

**Comment by sevenrats** [comment]
moved to https://github.com/jellyfin/jellyfin-meta/discussions/58
