### ISSUE TITLE
Migration failing after upgrade to 20200306 nightly

### ISSUE THREAD

**Issue by Shadowghost** [jellyfin/jellyfin#2530]
**Describe the bug**
I upgraded from 20200304 to 20200306 nightly and now server crashes on startup (see log section).

**System:**
 - OS: Debian 10 x86_64
 - Virtualization: none
 - Jellyfin Version: 10.5.0, nightly 20200306
 - Installed Plugins: manually uninstalled all to check if they're preventing startup
 - Reverse Proxy: nginx
 - Base URL: none
 - Networking: Host
 - Storage: local software RAID5 (mdadm)

**To Reproduce**
Setup 20200304 nightly and upgrade to 20200306.

**Expected behavior**
Jellyfin not crashing on startup and properly applying migrations.

**Logs**
```
jellyfin[13749]: [00:21:12] [INF] Jellyfin version: 10.5.0
jellyfin[13749]: [00:21:12] [INF] Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--restartpath=/usr/lib/jellyfin/restart.sh", "--ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg", ""]
jellyfin[13749]: [00:21:12] [INF] Operating system: Linux
jellyfin[13749]: [00:21:12] [INF] Architecture: X64
jellyfin[13749]: [00:21:12] [INF] 64-Bit Process: True
jellyfin[13749]: [00:21:12] [INF] User Interactive: True
jellyfin[13749]: [00:21:12] [INF] Processor count: 4
jellyfin[13749]: [00:21:12] [INF] Program data path: /var/lib/jellyfin
jellyfin[13749]: [00:21:12] [INF] Web resources path: /usr/lib/jellyfin/bin/jellyfin-web
jellyfin[13749]: [00:21:12] [INF] Application directory: /usr/lib/jellyfin/bin/
jellyfin[13749]: [00:21:12] [INF] Setting cache path: /var/cache/jellyfin
jellyfin[13749]: [00:21:12] [INF] Loading assemblies
jellyfin[12326]: [00:12:19] [WRN] Version check shows Jellyfin was updated: previous version=null, current version=10.5.0.0
jellyfin[12326]: [00:12:19] [FTL] Error while starting server.
jellyfin[12326]: System.NullReferenceException: Object reference not set to an instance of an object.
jellyfin[12326]:    at Jellyfin.Server.Migrations.Run(CoreAppHost host, ILogger logger)
jellyfin[12326]:    at Jellyfin.Server.CoreAppHost.TryMigrate()
jellyfin[12326]:    at Jellyfin.Server.Program.StartApp(StartupOptions options)
 [00:12:19] [INF] Disposing CoreAppHost
jellyfin[12326]: [00:12:19] [INF] Disposing ActivityLogWebSocketListener
jellyfin[12326]: [00:12:19] [INF] Disposing SessionInfoWebSocketListener
jellyfin[12326]: [00:12:19] [INF] Disposing ScheduledTasksWebSocketListener
jellyfin[12326]: [00:12:19] [INF] Disposing SessionWebSocketListener
jellyfin[12326]: [00:12:19] [INF] Disposing EmbyTV
jellyfin[12326]: [00:12:19] [INF] Received a SIGTERM signal, shutting down
```

**Comment by HackingPheasant** [comment]
I also ran into this issue. **202005** is fine, but **202006** is not

**Comment by Matt07211** [comment]
I also ran into this issue. **202005** is fine, but **202006** is not

**Comment by joshuaboniface** [comment]
Confirmed. Work is still in progress to fix, so we've delayed tonight's nightly until the fix is in. Short term avoid upgrading from 04/05 to 06.

**Comment by ThatNerdyPikachu** [comment]
*03/05 :)

**Comment by mooninite** [comment]
For those that are curious this commit is were the regression lies: 9eef0e8ca0e3359239ab68fcadbf2d65084f12e6

**Comment by Shadowghost** [comment]
Just a proposition from my side: Keep the latest 3 nightlies in the repo so we can rollback if something is wrong. Right now my server is stuck not working (not a problem since I expect that to happen on nightly, but would still be a nice addition).

**Comment by Evo-c** [comment]
Hopefully okay to post this, downloaded the netcore version right before the latest commit breaking this. Replacing with this file gets it working again.

https://1drv.ms/u/s!Aq6oMNN8XmEPg_JO7pYjjptriZTm5g?e=x7Z5dg

**Comment by Matt07211** [comment]
> Just a proposition from my side: Keep the latest 3 nightlies in the repo so we can rollback if something is wrong. Right now my server is stuck not working (not a problem since I expect that to happen on nightly, but would still be a nice addition).

They hold onto a decent amount of nightlies already tho?
https://repo.jellyfin.org/releases/server/linux/versions/nightly/
I can see nightlies dating back to 2020-01-21 to 2020-03-06

**Comment by joshuaboniface** [comment]
Yep, we keep at least 14 days of nightlies (usually more).

This should be fixed by tonight's nightly, just verified master myself and it's starting up again, so I'll close this out. The build kicks off at about 2AM EST.

**Comment by joshuaboniface** [comment]
@Shadowghost Unfortunately, at least for our Debian/Ubuntu repo using `reprepro`, it only allows a single version of any given package. That said the raw files are still there at https://repo.jellyfin.org/releases/server/debian/versions/nightly/, so if this happens you can grab the last working one and manually install it - apt will take care of future upgrades from there.

**Comment by Shadowghost** [comment]
Thanks for the info! I tried installing an old version with apt and an explicit version number which did not work (because of the reason stated above). Maybe the direct link to the package index should be mentioned in the docs too?
