### ISSUE TITLE
*.SRT are not loaded in Kodi

### ISSUE THREAD

**Issue by masca90021** [jellyfin/jellyfin#2533]
External *.srt are not loaded in Kodi. They appear as disabled and enabling them has no effect. I have them in UTF-8.

 - OS: [Windows]
 - Clients: [Kodi Leia]
 - Jellyfin Version: [e.g. 10.5.0, nightly 20200302]
 - Playback: [Direct Play, Remux, Direct Stream, Transcode] 
 - Installed Plugins: [Kodi Sync and Trakt]
 - Reverse Proxy: [None]
 - Base URL: [localhost:8096]
 - Networking: [Host]
 - Storage: [Local]

**Comment by olskar** [comment]
Can this be related? 

@2507

**Comment by dkanada** [comment]
@olskar you could be right

**Comment by masca90021** [comment]
Yeah, seems to be the case. When transcoded the external subtitles are just ignored completely. I saw that the issue was started for Android, that's why I opened this windows one.
