### ISSUE TITLE
EF Core Migration - Author Details 

### ISSUE THREAD

**Issue by Artiume** [jellyfin/jellyfin#2544]
Currently the author, musician, directors and so on don't have details. Add metadata details so that they can be searchable or sortable if wanted.

**Comment by JustAMan** [comment]
cc @sparky8251 @EraYaN

**Comment by EraYaN** [comment]
The Entity `Person` would be the one to add the fields to. Though do note that none of the entities have their final field lists. Do you have an idea of what details you would want?

**Comment by Artiume** [comment]
So one thing that I would like to do is have relations between authors and artists. For example, we could have Family for Will Smith. or common Directors that they've worked with. Films filmed in LA and so on.

![image](https://user-images.githubusercontent.com/20715731/79139815-fb178880-7d84-11ea-887c-cb779d9eac68.png)

**Comment by Shadowghost** [comment]
Shoo bot
