### ISSUE TITLE
Failed RPM build on COPR.

### ISSUE THREAD

**Issue by brianjmurrell** [jellyfin/jellyfin#2550]
**Describe the bug**
COPR RPM build failure

**System (please complete the following information):**
 - OS: Fedora, EL7

From the [build.log](https://copr-be.cloud.fedoraproject.org/results/brianjmurrell/jellyfin/fedora-rawhide-x86_64/01298335-jellyfin/build.log.gz):

```
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.fNa7Lu
+ umask 022
+ umask 022
+ cd /builddir/build/BUILD
+ cd /builddir/build/BUILD
+ cd /builddir/build/BUILD
+ cd /builddir/build/BUILD
+ rm -rf jellyfin-10.5.0
+ rm -rf jellyfin-10.5.0
+ /usr/bin/gzip -dc /builddir/build/SOURCES/jellyfin-web-10.5.0.tar.gz
+ /usr/bin/gzip -dc /builddir/build/SOURCES/jellyfin-web-10.5.0.tar.gz
+ /usr/bin/tar -xof -
+ /usr/bin/tar -xof -
+ STATUS=0
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ '[' 0 -ne 0 ']'
+ /usr/bin/tar -xof -
+ /usr/bin/tar -xof -
+ /usr/bin/gzip -dc /builddir/build/SOURCES/jellyfin-10.5.0.tar.gz
+ /usr/bin/gzip -dc /builddir/build/SOURCES/jellyfin-10.5.0.tar.gz
+ STATUS=0
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ '[' 0 -ne 0 ']'
+ cd jellyfin-10.5.0
+ cd jellyfin-10.5.0
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
++ mktemp -d
++ mktemp -d
+ web_build_dir=/tmp/tmp.bUTLhKfhUw
+ web_build_dir=/tmp/tmp.bUTLhKfhUw
~/build/BUILD/jellyfin-web-10.5.0 ~/build/BUILD/jellyfin-10.5.0
~/build/BUILD/jellyfin-web-10.5.0 ~/build/BUILD/jellyfin-10.5.0
+ web_target=/builddir/build/BUILD/jellyfin-10.5.0/MediaBrowser.WebDashboard/jellyfin-web
+ web_target=/builddir/build/BUILD/jellyfin-10.5.0/MediaBrowser.WebDashboard/jellyfin-web
+ pushd ../jellyfin-web-10.5.0
+ pushd ../jellyfin-web-10.5.0
+ nodejs-yarn install
+ nodejs-yarn install
yarn install v1.21.1
yarn install v1.21.1
[1/4] Resolving packages...
[1/4] Resolving packages...
[2/4] Fetching packages...
[2/4] Fetching packages...
error Couldn't find the binary git
error Couldn't find the binary git
```

Has some new dependency on `git` been introduced into whatever `yarn install` does?  Maybe a new/first dependency using a git repo?

If so, a `BuildRequires: git` likely needs adding to the specfile.

[`mock`](https://github.com/rpm-software-management/mock) can be used (requires a Linux system/docker container to run on, which can be done with [GitHub Actions](https://github.com/features/actions) -- I'm not familiar with Azure Pipelines as a CI engine) to create a CI test for PRs to prevent this sort of thing from happening in the future.  `mock` validates that an RPM's `BuildRequires:` is complete and that no new build dependencies have been introduced.

**Comment by brianjmurrell** [comment]
Or you can of course just use [COPR](https://copr.fedorainfracloud.org/) to build-test each PR as an additional CI stage.  COPR can report status back to GitHub.

**Comment by dkanada** [comment]
@brianjmurrell if you want to make a quick addition to the CI we would definitely merge that. We were thinking of moving the entire build process to CI anyways, so this would get COPR much closer.

**Comment by brianjmurrell** [comment]
Have [GitHub Actions](https://github.com/features/actions) been enabled on this repo?

**Comment by dkanada** [comment]
We use Azure at the moment.

**Comment by brianjmurrell** [comment]
Indeed, I am aware of this.  However is there any issues with enabling [GitHub Actions](https://github.com/features/actions) also?

In all honesty I am just not interested in learning how to build Azure pipelines.

GitHub actions report in the Checks tab just like Azure pipelines would so it would just look like yet another Check.

**Comment by joshuaboniface** [comment]
I'd indeed love for us to use Mock to get this building automatically - I've got no issues using GitHub Actions for this if it's fully supported.

For now I'll manually add Git to the deps for 10.5.1.

**Comment by brianjmurrell** [comment]
> I've got no issues using GitHub Actions

Have they been enabled for this repo?  Although now that it's out of beta, maybe this is something that doesn't need to specifically be done and it's just enabled for everyone who wants to use it.  If I can find some time, I will see if this is the case.
