### ISSUE TITLE
Trying to uninstall default plugins could remove the whole jellyfin directory.

### ISSUE THREAD

**Issue by jahmad** [jellyfin/jellyfin#2555]
**Describe the bug**
Trying to uninstall default plugins could remove the whole jellyfin directory.

**System:**
 - OS: Debian
 - Virtualization: Docker 
 - Jellyfin Version: 10.5.0

**To Reproduce**
1. Go to dashboard -> Plugins
2. Uninstall AudioDB or MusicBrainz
3. The Container will be broken and need to be recreated when using official image. OR It will go loading forever on linuxserver image.

**Expected behavior**
Either uninstall succeeded, or just disable uninstallation completely.

**Logs**
official image:
> [INF] [76] Emby.Server.Implementations.Updates.InstallationManager: Deleting plugin directory "/jellyfin"
> [INF] [76] ServerConfigurationManager: Saving system configuration
> [INF] [76] ServerConfigurationManager: Setting cache path: "/config/cache"
> [INF] [76] App: App needs to be restarted.

linuxserver image:
> [INF] [47] Emby.Server.Implementations.Updates.InstallationManager: Deleting plugin directory "/usr/lib/jellyfin/bin"
> [ERR] [47] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Access to the path '/usr/lib/jellyfin/bin' is denied."

**Comment by JustAMan** [comment]
Hi @jahmad 

Both AudioDB and MusicBrainz are not ordinary plugins, they're baked inside.
That said, I agree that allowing it to be deleted is a bug.

Paging @dkanada
