### ISSUE TITLE
Music Metadata will not fetch correct information

### ISSUE THREAD

**Issue by xevidos** [jellyfin/jellyfin#2557]
**Describe the bug**
I have attempted to add the following two songs to my media library.
/Music/Maroon 5/Memories/Memories.mp3
/Music/Hall & Oats/H2O/Family Man.mp3

The memories song showed up in an album by The Super 3, and the family man song shows up as Big Girl.  No matter how many times I change the metadata on the song or the album by changing the audiodbid or the musicbrainzid then clicking refresh metedata.  The metadata never changes.  Also any metadata changes I make, save correctly, but then after I click refresh metadata to get the rest of the missing meta ( track number and such ), everything I entered gets reset back to blank values.

**System (please complete the following information):**
 - OS: Centos 8
 - Virtualization: Docker
 - Clients: Firefox, Chrome
 - Browser: Chrome 80.0.3987.132, Firefox 73.0.1
 - Jellyfin Version: 10.5.0
 - Playback: Unknown
 - Installed Plugins: Anime, AudioDB MusicBrainz, openSubtitles
 - Reverse Proxy: Apache
 - Base URL: yes
 - Networking: Default Docker networking
 - Storage: Local

**To Reproduce**
1. Add song
2. See that it's metadata is wrong
3. Updated metadata ID to fetch correct information
4. Refresh metadata ( both Search for Missing and Replace All )
5. See that metadata is reset to what it was before step 3.

**Expected behavior**
Metadata should be pulled and updated.

**Logs**
No errors shown in logs.

Edit: Punctuation

**Comment by xevidos** [comment]
The local file metadata was overwriting the jellyfin metadata.

**Comment by Artiume** [comment]
> Also any metadata changes I make, save correctly, but then after I click refresh metadata to get the rest of the missing meta ( track number and such ), everything I entered gets reset back to blank values.

you can't teach the scanner to fix the right file so any alterations you make, you need to lock the metadata profile to prevent the scanner from reverting changes.

> The local file metadata was overwriting the jellyfin metadata. Is this intended or should metadata entered by jellyfin overwrite the local file metadata?

What do you mean by the local file metadata exactly? 

> The memories song showed up in an album by The Super 3, and the family man song shows up as Big Girl. No matter how many times I change the metadata on the song or the album by changing the audiodbid or the musicbrainzid then clicking refresh metedata. The metadata never changes. 

@dkanada you aware of this at all?

**Comment by dkanada** [comment]
I have seen reports of the ID fields being incorrectly labeled on web but that's all.
