### ISSUE TITLE
Remote "watch together" feature?

### ISSUE THREAD

**Issue by qub** [jellyfin/jellyfin#2558]
Would it be difficult to implement an option to sync two viewing sessions on the same Jellyfin server (or optionally across two instances)? I'm not familiar with the code base so I thought I'd throw the question out to those that are.

[SyncLounge](http://synclounge.tv/) seems to be a third party option someone wrote for Plex. I think that if it's not difficult to implement natively, people could consider this feature a huge plus for Jellyfin as well as a possible way to distinguish itself from the commercial options.

**Comment by JustAMan** [comment]
Can you make a formal feature request at https://features.jellyfin.org/ ?

**Comment by mark-monteiro** [comment]
FYI, this is being worked on here: https://github.com/jellyfin/jellyfin/pull/2733

**Comment by neopc10** [comment]
^

**Comment by dkanada** [comment]
This has been implemented so the issue can be closed, have fun with the feature!

**Comment by dkanada** [comment]
@crobibero gotta go fast :laughing:
