### ISSUE TITLE
[Build] Centos Dockerfile upgrade to Centos 8

### ISSUE THREAD

**Issue by Artiume** [jellyfin/jellyfin#2563]
tried to update build to centos8 and this error occurred.

```
 ---> Running in 7faeca83375a
error: rpmdb: damaged header #173 retrieved -- skipping.
error: rpmdbNextIterator: skipping h#     173 blob size(55540): BAD, 8 + 16 * il(78) + dl(54284)
Extra Packages for Enterprise Linux 8 - x86_64  5.7 MB/s | 5.9 MB     00:01
Last metadata expiration check: 0:00:02 ago on Mon Mar  9 02:52:25 2020.
Module or Group 'buildsys-build' is not available.
Error: Nothing to do.
The command '/bin/sh -c yum install -y @buildsys-build rpmdevtools yum-plugins-core libcurl-devel fontconfig-devel freetype-devel openssl-devel glibc-devel libicu-devel git' returned a non-zero code: 1
```

**Comment by Artiume** [comment]
https://centos.pkgs.org/8/rpmfusion-free-updates-x86_64/buildsys-build-rpmfusion-30-2.el8.x86_64.rpm.html


https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/system_administrators_guide/sec-working_with_package_groups

**Comment by kjkeane** [comment]
Just going to leave some notes here on what I have found.

I don't think `@buildsys-build` exists anymore, I was getting failures for that missing on CentOS 7.  I am also not sure it's needed anywhere, removing that I was able to continue.

After removing `@buildsys-build` I ran into
```
No match for argument: yum-plugins-core
Error: Unable to find a match: yum-plugins-core
```

This is because this package is now replaced with `dnf-plugins-core` in CentOS/RHEL 8, so replacing `yum-plugins-core` with the DNF equivalent package worked.

Other than the rpmdbNextIterator errors and cache warnings this Dockerfile builds for CentOS 8.
```Docker
FROM centos:8
# Docker build arguments
ARG SOURCE_DIR=/jellyfin
ARG PLATFORM_DIR=/jellyfin/deployment/centos-package-x64
ARG ARTIFACT_DIR=/dist
ARG SDK_VERSION=3.1
# Docker run environment
ENV SOURCE_DIR=/jellyfin
ENV ARTIFACT_DIR=/dist

# Prepare CentOS environment
RUN yum update -y \
 && yum install -y epel-release

# Install build dependencies
RUN yum install -y rpmdevtools dnf-plugins-core libcurl-devel fontconfig-devel freetype-devel openssl-devel glibc-devel libicu-devel git

# Install recent NodeJS and Yarn
RUN curl -fSsLo /etc/yum.repos.d/yarn.repo https://dl.yarnpkg.com/rpm/yarn.repo \
 && rpm -i https://rpm.nodesource.com/pub_8.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm \
 && yum install -y yarn

# Install DotNET SDK
RUN rpm -Uvh https://packages.microsoft.com/config/rhel/7/packages-microsoft-prod.rpm \
 && rpmdev-setuptree \
 && yum install -y dotnet-sdk-${SDK_VERSION}

# Create symlinks and directories
RUN ln -sf ${PLATFORM_DIR}/docker-build.sh /docker-build.sh \
 && mkdir -p ${SOURCE_DIR}/SPECS \
 && ln -s ${PLATFORM_DIR}/pkg-src/jellyfin.spec ${SOURCE_DIR}/SPECS/jellyfin.spec \
 && mkdir -p ${SOURCE_DIR}/SOURCES \
 && ln -s ${PLATFORM_DIR}/pkg-src ${SOURCE_DIR}/SOURCES

VOLUME ${ARTIFACT_DIR}/

COPY . ${SOURCE_DIR}/

ENTRYPOINT ["/docker-build.sh"]
```

**Comment by kjkeane** [comment]
Ok, revisited the `@buildsys-build` group and it installs these packages.
```
epel-rpm-macros
gcc-c++
```

I'm going to see if RHEL 8 has a similar group or packages.

**Comment by kjkeane** [comment]
The above packages exist, just not the `@buildsys-build` group.

**Comment by Artiume** [comment]
From chat:

+RUN curl -sL https://rpm.nodesource.com/setup_10.x | bash -

+RUN yum -y install nodejs

- && rpm -i https://rpm.nodesource.com/pub_8.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm \

**Comment by kjkeane** [comment]
So I'm not sure you need the `yum-plugins-core` or `dnf-plugins-core`.  The Dockerfile doesn't use any of the plugins listed here.  You can double check, but you may be able to handle it all in one build with CentOS 7/8 without the package.

https://dnf-plugins-core.readthedocs.io/en/latest/
