### ISSUE TITLE
[Enhancement] Fork Emby Studio images repo and update StudiosImageProvider

### ISSUE THREAD

**Issue by SenorSmartyPants** [jellyfin/jellyfin#2567]
**Describe the bug**
JF pulls studio thumbs/posters from an Emby github repo. 

https://github.com/jellyfin/jellyfin/blob/master/MediaBrowser.Providers/Studios/StudiosImageProvider.cs

Current source for logos
https://github.com/MediaBrowser/Emby.Resources/tree/master/images/imagesbyname

**Expected behavior**

JF should pull studio logos from its own repo, or a 3rd party provider.

- Fork this repo.
- Update StudiosImageProvider to pull from new JF repo
- Add missing logos
- Make StudiosImageProvider a plugin

**Comment by SenorSmartyPants** [comment]
Just found this site. Probably don't have an API thou.

https://logos.fandom.com/

**Comment by Artiume** [comment]
This has been discussed in the chat a few times. I think @thornbill was looking into picons as an option. I was looking into Wikimedia as possibly an alternative as well.

**Comment by thornbill** [comment]
Unfortunately we are unable to fork the Emby repository as it is not properly FOSS licensed. That is why we have continued to use that repository and need a FOSS replacement.

**Comment by Artiume** [comment]
https://query.wikidata.org/#%23defaultView%3AImageGrid%0ASELECT%20%3Fitem%20%3FitemLabel%20%3Fpic%0AWHERE%0A{%0A%3Fitem%20wdt%3AP31%20wd%3AQ1254874%20.%20%23%20television%20network%0A%3Fitem%20wdt%3AP154%20%3Fpic%20%23%20logo%20image%0ASERVICE%20wikibase%3Alabel%20{%20bd%3AserviceParam%20wikibase%3Alanguage%20%22[AUTO_LANGUAGE]%2Cen%22%20}%0A}
Wikidata

https://commons.wikimedia.org/wiki/Category:SVG_logos_of_television_channels_and_networks
Wikimedia

https://github.com/picons/picons/tree/master/build-source/logos
Picons

https://github.com/XBMC-Addons/resource.images.studios.white/tree/master/resources
Kodi
