### ISSUE TITLE
Add BlurHash to items

### ISSUE THREAD

**Issue by MrTimscampi** [jellyfin/jellyfin#2569]
### Description

For jellyfin-web, we'd like to be able to display a blurred version of artworks as a placeholder during page load.

Our proposal for this is to use [BlurHash](https://github.com/woltapp/blurhash) to generate a hash of an item's images during scan, that would then be sent along with it's information on API calls.

The license is MIT, so it's GPL-compatible, and it has many implementations available:

- .NET
- C
- Clojure
- Dart
- Elm
- Go
- Java
- Kotlin
- Nim
- PHP
- Python
- Ruby
- Rust and WebAssembly
- Swift
- TypeScript

This means it'd be available to all existing clients and would give good options for new potential clients.

**Comment by nielsvanvelzen** [comment]
This would be nice to have for ATV too.

**Comment by GranPC** [comment]
I've tried implementing this in my instance as an experiment, and it seems to work fine, but the browser hangs for a bit while decoding the blurhashes if your library is big enough.

It seems like a decent part of the overhead comes from the `linearTosRGB` function in the JS version of blurhash, while the rest comes from the process of drawing the blurhash to a canvas and extracting the data URL from that. I'll do some more research to see if this can be optimized.

**Comment by MrTimscampi** [comment]
@GranPC If you can, PRs to the relevant repositories would be very appreciated :)

**Comment by GranPC** [comment]
Yep, will upload in a bit! Having some issues with the Docker build environment, it randomly broke last night. I'll definitely need help with the PR, I've got a couple of questions :) 

On March 26, 2020 9:59:44 AM GMT+01:00, Julien Machiels <notifications@github.com> wrote:
>@GranPC If you can, PRs to the relevant repositories would be very
>appreciated :)
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/jellyfin/jellyfin/issues/2569#issuecomment-604309082

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by GranPC** [comment]
There we go! See #2676 and jellyfin/jellyfin-web#987

**Comment by candry7731** [comment]
is there an api call to get the blurhash url?
