### ISSUE TITLE
[Enhancement] Music Art

### ISSUE THREAD

**Issue by leaty** [jellyfin/jellyfin#2571]
I've been using Emby side-by-side Jellyfin for the singular purpose of fetching Music Art, but this unfortunately only works for Album Art, unless I allow Emby to store images inside of my music library, which I'd rather not have to do.

Ability to add sources for fetching art both for albums and artists, including fanart, would just be fantastic. It would erase Emby so hard off my server. Is this anywhere on the roadmap for jellyfin?

**Comment by dkanada** [comment]
We already support artist images as well.

**Comment by leaty** [comment]
Then I'm certainly missing something, I only have the option "Image Extractor" under Audio Image Fetchers. This is on 10.5.0. Would you kindly point me in the right direction?

**Comment by dkanada** [comment]
Album and artist images are extracted automatically if I recall. We have some information in the documentation on common filenames for certain media types, maybe music has been documented already.

**Comment by leaty** [comment]
Ahh, sorry if I've been unclear. My question is for _fetching_ art from the internet, just like it fetches metadata. Not extracting from what already exists.

**Comment by dkanada** [comment]
Ah, there should also be checkbox lists for albums and artists. If there aren't, you should go to the plugin menu and enable MusicBrainz and AudioDB, or download some other providers.

**Comment by leaty** [comment]
Well would you look at that! I didn't know you'd have to enable them as plugins, because both MusicBrainz and TheAudioDB show up under "Music Album/Artist metadata downloaders" even when they're disabled as plugins. But after enabling them, they also show up under "Image Fetchers".

If anyone else stumbles on this I just want to point out that I had to manually create the following three directories as well.
/var/lib/jellyfin/plugins
/var/cache/jellyfin/audiodb-artist
/var/cache/jellyfin/audiodb-album

Thanks so much! Also bye emby `pacman -Rns emby-server`

**Comment by dkanada** [comment]
The two AudioDB folders should have been created automatically at least, very interesting.
