### ISSUE TITLE
File naming can break entire library

### ISSUE THREAD

**Issue by csyperski** [jellyfin/jellyfin#2577]
**Describe the bug**

It seems that files named as described below can break the import of video files into a Movie library.  

"Godfather.Part2.disk1.mkv" and "Godfather.Part2.disk2.mkv"

My guess is there is a some weird recursive issue going on with the movie title, "Godfather.Part2", having part2 in it and the two part file (disk1 & disk2).

No useful logs are collected even when set to Debug.  When the following titled files are encountered, it appears to break the entire import scan.  

**System (please complete the following information):**
 - OS: Ubuntu 18.04
 - Virtualization: KVM
 - Clients: Browser
 - Browser: Chrome 80
 - Jellyfin Version: 10.5.0
 - Playback: N/A
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: /
 - Networking: Host
 - Storage: ZFS

**To Reproduce**

Add two valid video files with the following names: 
"Godfather.Part2.disk1.mkv" and "Godfather.Part2.disk2.mkv"

Plus some other valid files that are not multipart

Then do a library -> scan library 

Then attempt to view the library in the browser, only multi-part files were then shown in my setup.  

**Expected behavior**

The files to be imported as a Single Movie "Godfather Part 2" that exists in two files.  

**Logs**

None usagable

**Screenshots**
None

**Additional context**
None

**Comment by dkanada** [comment]
I think `Part X` is another keyword for split movies, but I'd have to check the code again.

**Comment by csyperski** [comment]
@dkanada  I believe it is, as there are other movies named in that same manner.  I think the issue is that a single file or set of files can break a whole library in my case.  I would expect that the scanner just abort on the single file, not tank the library.

**Comment by Artiume** [comment]
@Bond-009 what do you think?
