### ISSUE TITLE
Fork Trakt plugin

### ISSUE THREAD

**Issue by SenorSmartyPants** [jellyfin/jellyfin#258]
https://github.com/MediaBrowser/trakt

Fork any other plugins whose licensing would permit it.

**Comment by bfayers** [comment]
Starting a list of ones with licenses:
- https://github.com/MediaBrowser/GameBrowser
- https://github.com/MediaBrowser/EmbyReports
- https://github.com/MediaBrowser/Emby.AutoOrganize
- https://github.com/MediaBrowser/Tvheadend
- https://github.com/MediaBrowser/Emby.Plugins.Anime
- https://github.com/MediaBrowser/TuneIn
- https://github.com/MediaBrowser/Prowl
- https://github.com/MediaBrowser/Pushover
- https://github.com/MediaBrowser/Pushbullet
- https://github.com/MediaBrowser/IPTV
- https://github.com/MediaBrowser/email-notifications
- https://github.com/MediaBrowser/Pushalot
- https://github.com/MediaBrowser/Tou.tv
- https://github.com/MediaBrowser/Emby.Plugins (This has a few, weirdly)
- https://github.com/MediaBrowser/NotifyMyAndroid
- https://github.com/MediaBrowser/Emby.Channels (Lots)
- https://github.com/MediaBrowser/emby-tvmaze
- https://github.com/MediaBrowser/roku-bif
- https://github.com/MediaBrowser/NextPVR


That seems to be all the plugins that have licenses.

Heres the ones that don't have any licenses listed atalls
- https://github.com/MediaBrowser/NfoMetadata
- https://github.com/MediaBrowser/Last.fm
- https://github.com/MediaBrowser/Fanart.tv
- https://github.com/MediaBrowser/DVBViewerTVPlugin
- https://github.com/MediaBrowser/MediaBrowser.Plugins.VuPlus
- https://github.com/MediaBrowser/MediaBrowser.Plugins.TWiT
- https://github.com/MediaBrowser/MediaPortalTVPlugin
- https://github.com/MediaBrowser/Emby.Theater.Plugins (lots in here, as these are plugins for just emby theater)

**Comment by joshuaboniface** [comment]
I've grabbed all the free software ones, and will upload them to our org soon.

**Comment by bfayers** [comment]
@joshuaboniface I'm guessing the answer is nothing but; can we do anything with non-licenseds

**Comment by JustAMan** [comment]
@bfayers we can look at the ideas (but not at implementations!) and re-implement if desired. Anything else poses legal risks if I understand licensing at all.

**Comment by joshuaboniface** [comment]
That's right, nothing we can do aside from reimplement - no license is an implied default copyright to the author, so it's not Free Software.

**Comment by bfayers** [comment]
Fair enough.
