### ISSUE TITLE
Feature Request: respect m3u folders for livetv to group channels

### ISSUE THREAD

**Issue by Robsta86** [jellyfin/jellyfin#2580]
Hi, 

I would like to request additional functionality for the live tv function. I have an IPTV provider that provides m3u with options files. One of the functionalities that come with these files is grouping channels into folders.

When I load this m3u into Kodi I see the channels grouped by country, making it really easy to navigate my channels.

Could you please add functionality like this to Jellyfin?

**Comment by Artiume** [comment]
we'll need a sample file to test with :). If you want to provide a sanitized m3u, that'd work.

**Comment by anthonylavado** [comment]
Also - Feature requests are best taken here: https://features.jellyfin.org

**Comment by jimgrove1985** [comment]
You need to figure out a way to parse the group-title part of an M3U playlist as that determines which group a channel gets assigned to.

#EXTINF:-1 tvg-id="Test1" tvg-name="Test Channel 1" tvg-logo="" **group-title="GROUP 1"**,Test Channel 1
http://Link.To.Channel/etc/.......

This used to work brilliantly with the IPTV plugin for Plex, might be worth having a look at their code to see how they did it: https://github.com/Cigaras/IPTV.bundle/blob/master/Contents/Code/m3u_parser.py

**Comment by msj33** [comment]
This feature request lives here: https://features.jellyfin.org/posts/186/iptv-channel-groupings

This is my personal showstopper for not migrating from KODI just yet

**Comment by petitbou0169** [comment]
It just lacks the list by category! and frankly after that it's clean!
