### ISSUE TITLE
Playback On Ubuntu Download

### ISSUE THREAD

**Issue by wsteven-son** [jellyfin/jellyfin#2585]
Followed official installation instructions for Jellyfin install on Ubuntu. Currently running Ubuntu-18.04.3-4.14-minimal-odroid on an Odroid HC1. Jellyfin setups up as expected, but videos only play on the Google Play app. Videos wont play in browser or on Apple Jellyfin App.

**Comment by dkanada** [comment]
We're going to need more information than that to find a solution.

**Comment by wsteven-son** [comment]
Thanks for the quick response, I was actually able to resolve the issue. A simple transcribing setting. Thanks again
