### ISSUE TITLE
'/web' should open home page

### ISSUE THREAD

**Issue by alashow** [jellyfin/jellyfin#2593]
**Describe the bug**
Currently, when you open `/web` path on Jellyfin web server (example.com/jellyfin/web), it fails with 400 http error and message: 
`Value cannot be null. (Parameter 'path')`

**System (please complete the following information):**
 - Jellyfin Version: 10.5.0
 - Reverse Proxy: nginx
 - Base URL: jellyfin

**Expected behavior**
`/web` path should open the homepage as `/web/index.html` does.

**Additional context**
I noticed this when I left closed the browser mid playback on PS4, then when I opened it back it started loading last url  `/web/index.html#!/videoosd.html'` which redirects to `/web` when opened without clicking play button.

**Comment by alex9099** [comment]
Can reproduce that without a reverse proxy (accessing directly :8096)
