### ISSUE TITLE
CPU usage doing nothing

### ISSUE THREAD

**Issue by goliath888** [jellyfin/jellyfin#2599]
My cpu usage is between 10-15% and Jellyfin apparently is doing nothing. 

This is the CPU usage from the docker contaier. See the timestamps
![image](https://user-images.githubusercontent.com/61027944/76701522-3d847180-66c2-11ea-84bc-24ca8bc2f24d.png)

And in the log the last entry is from:
[13:01:03] [INF] [30] App: User Changes Sync Finished Taking 00:00:00.1035025

So, what is it doing? 

Server:
JellyFin on Docker (LinuxServer image)
JellyFin version Versión: 10.5.0

**Comment by mark-monteiro** [comment]
This may be a duplicate of https://github.com/jellyfin/jellyfin/issues/2589#issuecomment-605632727. Can you try the workaround there and see if it resolves the issue?

**Comment by goliath888** [comment]
Not sure why but this issue was already answered and solved...
