### ISSUE TITLE
"Display missing episodes within seasons" option only works if TVDB is activated

### ISSUE THREAD

**Issue by Vitorvlv** [jellyfin/jellyfin#2602]
Describe the bug
Given the recent issues with TVDB I've deactivated and am using primarily tmdb. After making the switch I've noticed that the missing episode/seasons were not showing up anymore. I don't know if 
that's intentional or not, or if it's something that can only be done with tvdb. 

But if possible I would really like this option to work with other providers.

System :
 - OS: Manjaro
 - Virtualization: [e.g. Docker, KVM, LXC]
 - Clients: Web Browser
 - Browser: Firefox 74.0
 - Jellyfin Version:10.5.0
 - Installed Plugins: AudioDB, Fanart, MusicBrainz
 - Base URL: none
 - Networking: Host
 - Storage: Local

[logs](https://pastebin.com/raw/K2fm6SsF)

**Comment by dkanada** [comment]
That's actually expected, the missing episodes are scraped from TVDB internally. This isn't a very good solution but there's no easy way to make it agnostic without some provider changes.

**Comment by Vitorvlv** [comment]
I see, could I leave this issue open as a feature request then?

**Comment by JustAMan** [comment]
I would rather leave it as it is but make it emit a warning or something when you select this option and don't select TVDB.
