### ISSUE TITLE
RPM version not updated for 10.5.1

### ISSUE THREAD

**Issue by brianjmurrell** [jellyfin/jellyfin#2609]
https://github.com/jellyfin/jellyfin/blob/aadff77531e4f15e5dcac0e5c9b6520b74124b77/deployment/fedora-package-x64/pkg-src/jellyfin.spec#L10

**Comment by Artiume** [comment]
10.5.1 had a lot of issues and failed to properly to deploy for a lot of systems. We're re-releasing it as 10.5.2 soon to try again. Let us know if .2 has issues

**Comment by JustAMan** [comment]
10.5.1 was a building failure, so closing this.
