### ISSUE TITLE
dot-net 3.1 not really available

### ISSUE THREAD

**Issue by brianjmurrell** [jellyfin/jellyfin#2610]
**Describe the bug**
dot-net 3.1 is really not very universally available (on Linux).

It is marginally available in [@dotnet-sig/dotnet-preview](https://copr.fedorainfracloud.org/coprs/g/dotnet-sig/dotnet-preview/) but even there, it's build was only successful on Fedora 31.  They are not even building for EL7 and it failed EL8 and all other versions of Fedora.

**Comment by mark-monteiro** [comment]
The instructions to install. NET Core in fedora can be found here: https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-fedora30
