### ISSUE TITLE
'Group movies into collections option' doesn't work

### ISSUE THREAD

**Issue by ggdaynight** [jellyfin/jellyfin#2611]
**Describe the bug**
Enabling the "Group movies into collections" does nothing
Older versions (< 10.5.0) of Jellyfin grouped the movies into collection inside the Movies folder.
 
**System (please complete the following information):**
 - OS: Linux 4.15.0-88-generic x86
 - Virtualization: Docker version 19.03.8
 - Browser: Firefox 74
 - Jellyfin Version: 10.5.0
 - Installed Plugins: just the default ones, no additional ones

**Pre-Steps**
1. Spin up new docker container
2. Add Movies library
3. Scan Library
4. Create some Collections

**To Reproduce**
1. Go to 'Dashboard' -> 'Libraries' -> 'Display'
2. Tick in 'Group movies into collections'
3. Go back to 'Movies' library
4. See error: Collections don't appear

**Expected behavior**
If you have Movie collection, e.g. Jumanji Collections, you should not see the movies separately in the Movies folder, just the collection in its place. (In this case the Jumanji Collections.)

**Comment by ashtez** [comment]
Same, also on docker version.

**Comment by BaronGreenback** [comment]
I've noticed all my collections have multiple repeats of the same movies.

<?xml version="1.0" encoding="utf-8" standalone="yes"?> GB-18 12/01/2020 21:06:44 false A post-apocalyptic horror film series focused on survivors of a fictional, blood-borne disease called Rage after the disease has decimated Great Britain. 28 Days/Weeks Later Collection 2002-10-31 PremiereDate 2002 1565 D:\Films\28 Weeks Collection\28 Days Later... (2002)\28 Days Later... (2002).avi D:\Films\28 Weeks Collection\28 Weeks Later (2007)\28 Weeks Later (2007).avi D:\Films\28 Weeks Collection\28 Days Later... (2002)\28 Days Later... (2002).avi D:\Films\28 Weeks Collection\28 Weeks Later (2007)\28 Weeks Later (2007).avi D:\Films\28 Weeks Collection\28 Days Later... (2002)\28 Days Later... (2002).avi D:\Films\28 Weeks Collection\28 Weeks Later (2007)\28 Weeks Later (2007).avi D:\Films\28 Weeks Collection\28 Days Later... (2002)\28 Days Later... (2002).avi D:\Films\28 Weeks Collection\28 Weeks Later (2007)\28 Weeks Later (2007).avi D:\Films\28 Weeks Collection\28 Days Later... (2002)\28 Days Later... (2002).avi D:\Films\28 Weeks Collection\28 Weeks Later (2007)\28 Weeks Later (2007).avi D:\Films\28 Weeks Collection\28 Days Later... (2002)\28 Days Later... (2002).avi D:\Films\28 Weeks Collection\28 Weeks Later (2007)\28 Weeks Later (2007).avi D:\Films\28 Weeks Collection\28 Days Later... (2002)\28 Days Later... (2002).avi D:\Films\28 Weeks Collection\28 Weeks Later (2007)\28 Weeks Later (2007).avi D:\Films\28 Weeks Collection\28 Days Later... (2002)\28 Days Later... (2002).avi D:\Films\28 Weeks Collection\28 Weeks Later (2007)\28 Weeks Later (2007).avi D:\Films\28 Weeks Collection\28 Days Later... (2002)\28 Days Later... (2002).avi D:\Films\28 Weeks Collection\28 Weeks Later (2007)\28 Weeks Later (2007).avi D:\Films\28 Weeks Collection\28 Days Later... (2002)\28 Days Later... (2002).avi D:\Films\28 Weeks Collection\28 Weeks Later (2007)\28 Weeks Later (2007).avi

**Comment by coldshouldermedia** [comment]
In my case, it is not ALL movie collections, just some of them.  Also thought I should mention that I'm using the TVDb Box Sets plugin.  Screenshots for reference:

In the Movies tab, we can see Child's Play 1, 2, and 3 all broken out, while Cinderella is displaying a group:

![5aMjD5Z6jr](https://user-images.githubusercontent.com/54368516/79888305-a3e36a80-83b9-11ea-9293-b908bff6f7c0.png)

Where as in the collection tab, we can see that TMDb Box Sets plugin has created collections for all of these movies:

![dIDyR5CYrK](https://user-images.githubusercontent.com/54368516/79888286-9af29900-83b9-11ea-80c4-400f7f70182a.jpg)

**Comment by Artiume** [comment]
This could be related https://github.com/jellyfin/jellyfin/issues/2565

**Comment by ashtez** [comment]
@JustAMan Thank you !
