### ISSUE TITLE
Why Ubuntu's newest version is still 10.5.0?????

### ISSUE THREAD

**Issue by FanyangMengDev** [jellyfin/jellyfin#2612]
https://repo.jellyfin.org/releases/server/ubuntu/versions/10.5.1/

Cannot upgrade via apt-get upgrade because of this. Please fix it, thanks.

**Comment by pc-v2** [comment]
binary still not available

**Comment by Shadowghost** [comment]
Just be a bit patient, it takes some time to build and get it up...

**Comment by Artiume** [comment]
10.5.1 build failed for most repositories. it'll cause issues to re-release it so the plan is to release 10.5.2 this weekend.

**Comment by FanyangMengDev** [comment]
@Artiume Thank you so much for your update. I will look forward to it.
