### ISSUE TITLE
Fix h/x264 AAC MKV (audio)

### ISSUE THREAD

**Issue by ldexterldesign** [jellyfin/jellyfin#2614]
**Media Info of the file**

```
Playback Info
Player: Html Video Player
Play method: DirectPlay
Protocol: http
Stream type: Video

Video Info
Player dimensions: 1792x1026
Video resolution: 853x480
Dropped frames: 1
Corrupted frames: 0

Original Media Info
Container: mkv
Size: 322.2 MiB
Bitrate: 732 kbps
Video codec: H264 High
Video bitrate: 540 kbps
Audio codec: AAC LC
Audio bitrate: 192 kbps
Audio channels: 2
Audio sample rate: 44100 Hz
```

**Logs**

No logs generated before/during/after playback

**FFmpeg Logs**

Dashboard says "direct playing" so I presume no muxing or transcoding is taking place

**Stats for Nerds Screenshots**

<img width="1792" alt="Screenshot 2020-03-16 at 16 33 27" src="https://user-images.githubusercontent.com/1715809/76774179-e35bdd00-67a3-11ea-823f-c567d0f98039.png">

**Server System (please complete the following information):**
 - OS: Docker on Linux
 - Jellyfin Version: 10.4.3
 - Hardware settings & device: 2.6 GHz 6-Core Intel Core i7 & Intel UHD Graphics 630 1536 MB
 - Reverse proxy: n/a
 - Other hardware notes: n/a
 
**Client System (please complete the following information):**
 - Device: MacBook Pro (16-inch, 2019)
 - OS: macOS, 10.15.3 (19D76)
 - Client: Web/Browser
 - Browser (if Web client): Vivaldi 
 - Client and Browser Version: 2.11.1811.47 (Stable channel) (64-bit)

Hi,

Thanks for amazing software

Hope you're well

In brief, I have issues playing anything using h/x264 AAC MKV, specifically audio but occasionally video too

I created a thread with [v]ivaldi, which has more info' (inc. sample video file)

If you have any issues (e.g. questions/queries) then happy to help

Keep up sterling work!

Hope to hear back

Sincerely

v: https://forum.vivaldi.net/topic/44944/fix-h-x264-aac-mkv-audio

**Comment by JustAMan** [comment]
Could you please explain here what exact issue you're facing? Also did you try other browser?

**Comment by ldexterldesign** [comment]
Hi,

Thanks for reply

Please read my vivaldi thread in addition to my OP

Hope to hear back

Sincerely

**Comment by JustAMan** [comment]
I did, but I still don't know what type of issue you're seeing.
Also, a suggestion would be to download the file (that is said to be direct played) and try opening it in Vivaldi. If it plays normally but has issues in JF - it's our problem, if it still plays wrongly in Vivaldi - that's their bug :)

**Comment by ldexterldesign** [comment]
> I still don't know what type of issue you're seeing?

Did you try to play the (dropbox) file I linked to in my vivaldi OP in jellyfin?:

* If yes then do you hear audio
* If no then hopefully this answers your question

> Also, a suggestion would be to download the file (that is said to be direct played) and try opening it in Vivaldi. If it plays normally but has issues in JF - it's our problem, if it still plays wrongly in Vivaldi - that's their bug :)

👉 https://forum.vivaldi.net/post/354617

Based on our logic it's a jellyfin issue, no?

Cheers

**Comment by JustAMan** [comment]
Heh, I don't see you there trying what I said (trying to play the file directly from disk, not from some storage which might transcode on the fly).

**Comment by ldexterldesign** [comment]
https://forum.vivaldi.net/post/357758

Apologies and thanks!
