### ISSUE TITLE
run jellyfin.exe auto open the site

### ISSUE THREAD

**Issue by huanx9** [jellyfin/jellyfin#2619]
I want add jellyfin to “strat up”  but run jellyfin.exe auto open the site

What should I do?

run   jellyfin.exe  /?    or  other way

~~my English is bad ..  hope you can know my means.. thank you  :)~~

**Comment by mark-monteiro** [comment]
Are you trying to run jellyfin.exe but NOT have it open the site automatically?

**Comment by huanx9** [comment]
You're right .   can you help me ?

**Comment by PrplHaz4** [comment]
> 
> 
> You're right . can you help me ?

Open system.xml and set this to false:
`<AutoRunWebApp>false</AutoRunWebApp>`

**Comment by huanx9** [comment]
thanks!!!!!!!
