### ISSUE TITLE
playback using custom domain on chromecast

### ISSUE THREAD

**Issue by justinrush** [jellyfin/jellyfin#2624]
**Media Info of the file**
Filetype doesn't appear to matter

**Logs**
Each time I click play, I see something like this:
`[01:25:17] [INF] [156] App: User policy for admin. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[01:25:17] [INF] [156] App: Bitrate exceeds DirectStream limit: media bitrate: 11555742, max bitrate: 1500000
[01:25:17] [INF] [156] App: Profile: Unknown Profile, Path: /media/hd-7/2.Guns/2 Guns.mkv, isEligibleForDirectPlay: True, isEligibleForDirectStream: False
[01:25:17] [INF] [156] App: Profile: Unknown Profile, No direct play profiles found for Path: /media/hd-7/2.Guns/2 Guns.mkv`

**Server System (please complete the following information):**
 - OS: jellyfin docker image on kubernetes 1.16.8
 - Jellyfin Version: 10.5.0
 - Hardware settings & device: i7-8559U
 - Reverse proxy: NGINX L7
 - Other hardware notes: NFS PVs
 
**Client System (please complete the following information):**
 - Device: Android or web client, Chromecast

Not sure if I am posting this in the right area.

When I deploy an https L7 via NGINX using an internal only domain, or when I deploying an L4 (MetalLB) and attempt to use the internal domain name, Casting to chromecast does not work.  It looks like it will work, but nothing ever happens after hitting play.

I did some testing today and believe the reason for this is that the Jellyfin client, web or android, is passing the URL of the jellyfin server into the Chromecast.  Google, in their infinite wisdom, has hardcoded the DNS servers on the Chromecast to their public DNS servers.  Since this is an internal facing domain it isn't resolvable by the Chromecast.

I'm not sure of the right way around it, but Plex seems to get it around it somehow.  Is there any work being done in this area?  for the moment I can use the L4 via IP address to get around this, but ideally I'd like to use a generic L7 proxy referenced by potentially various domain names (jellyfin-int for internal, jellyfin-ext for externally facing, etc).

**Comment by JustAMan** [comment]
There should be a workaround for now, see https://github.com/jellyfin/jellyfin/issues/1396#issuecomment-579341368

**Comment by justinrush** [comment]
> There should be a workaround for now, see [#1396 (comment)](https://github.com/jellyfin/jellyfin/issues/1396#issuecomment-579341368)

Thats a way to do it, but straight up blocking the most commonly used DNS entry in the world feels a bit excessive.

**Comment by JustAMan** [comment]
You can assign a static IP to chromecast dongle and block only it.
Again, this is a workaround, a proper solution is something else for sure.

**Comment by mholt** [comment]
I also experience this issue, and I am totally not surprised if this is a problem with Chromecast more than with Jellyfin. Indeed, DNS lookups for a custom domain within my network resolve to an internal IP address, and since playback is not working, I _assume_ Chromecast is doing its own DNS lookups (grr).

>  Google, in their infinite wisdom, has hardcoded the DNS servers on the Chromecast to their public DNS servers.

Do you have a source for this? I haven't found anything useful about this.

**Comment by BaronGreenback** [comment]
FYI #3339 provides the capability to obtain the router's external ip address via Upnp.

**Comment by BaronGreenback** [comment]
would like to keep this one open - there is a similar issue with dlna and host names.
