### ISSUE TITLE
Music # Artists # poster missing

### ISSUE THREAD

**Issue by lelamamalgache** [jellyfin/jellyfin#2625]
Hello devs :)

Jellyfin has detected my all library music, i have all poster of albums except artists poster

**Describe the bug**
in my music library, there is no poster for all artists

**System (please complete the following information):**
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Chrome 80
 - Jellyfin Version: 10.5.0

in my lidarr metadata, i have activate "Write Metadata to Audio Files" and "Scrub Existing Tags"
in my music library of jellyfin, in advanced option, i have ticked all checkbox

**Screenshots**

<img width="884" alt="albums" src="https://user-images.githubusercontent.com/58141187/76920817-b9eaa080-68cc-11ea-86f8-7a7dd50765b4.png">
<img width="861" alt="artists" src="https://user-images.githubusercontent.com/58141187/76920838-c7078f80-68cc-11ea-9e2e-13ad3947fce8.png">

**Comment by dkanada** [comment]
I'm guessing this was the SimpleArtistDetection I enabled to fix scan times. You can't change it from the web client but it should be available in the server config file somewhere on your system. Just set it to `true` and then recreate the library. It might work with a simple rescan but I'm not sure.

**Comment by lelamamalgache** [comment]
i have already this option to true and my artists posters are missing.

<img width="785" alt="musicadvanced" src="https://user-images.githubusercontent.com/58141187/76948830-ec65bf00-6907-11ea-8c47-54daae1b09df.png">

**Comment by amatriain** [comment]
Seeing the same here, docker installation.
I tried setting EnableSimpleArtistDetection in ```/config/config/system.xml``` both to true and false and rescanning the library. Same result, artist posters are missing.

**Comment by robwent** [comment]
Getting the same on Ubuntu.

I tried changing the `EnableSimpleArtistDetection` to false in `etc/jellyfin/system.xml`
restarted the service, removed the library, deleted any artist meta under `/jellyfin/metadata/artists`
then added the library back again and still have no artist images.

If I try and manually identify an artist by adding an ID from theaudiodb then nothing comes back in the search. So it feels like something is wrong with the agents?

**Comment by robwent** [comment]
Could it be related to this?
https://github.com/jellyfin/jellyfin/pull/2154

**Comment by lelamamalgache** [comment]
hello,

i don't know if it's the new version of jellyfin 10.5.3

I have succeeded to get posters for artists.
1) Dashboard > plugins
2) settings AudioDB and MusicBrainz
3) tick all checkboxes
4) go to your music library, then replace metadata missing and tick the checkbox replace all posters

**Comment by robwent** [comment]
@lelamamalgache Thankyou!
I just checked "Enable this provider for metadata searches on artists and albums." and then went to libraries and refreshed the music one for missing metadata. 
I can see the artist images starting to come through.

Maybe the wording needs changing here or enabling by default as I would have thought that if this option was off then there would be no meta for albums either but that did work before the change.

**Comment by JustAMan** [comment]
So @lelamamalgache can we close this issue as solved then?

**Comment by lelamamalgache** [comment]
By default, this option is not enabled.

If you think users should enabled it  manually, i will close this issue
or
if you think you will implement this option enabled by default, i let open

as you want

**Comment by robwent** [comment]
I don't think the option makes sense.

> Enable this provider for metadata searches on artists and albums.

When it's unchecked, meta is downloaded for albums but not artists.
When it is checked, it downloads meta for both.

The description suggests that nothing would download if it's unchecked, but it does.
If no meta downloaded when the option is off it would be more obvious that it's an issue with a setting.

**Comment by JustAMan** [comment]
Let's ask @dkanada

**Comment by 27md** [comment]
i'm having the same issue, tried everything listed above.

**Comment by dkanada** [comment]
We disabled it by default because music metadata doesn't respect the library settings, so it was always collecting metadata even when explicitly disabled. Adding this global flag overrides the library settings, and it's better to default to a setting that doesn't access the internet.

**Comment by robwent** [comment]
But it still collects album metadata even if this option is off.
So the wording of the option doesn't make sense as it shouldn't collect any album meta when unchecked?

**Comment by dkanada** [comment]
It could be collecting the information from another source, but if not that would be a bug.

**Comment by lelamamalgache** [comment]
artist poster are filled by audiodb, so if you have some missing artist posters, go to audiodb, create an account, then upload poster

**Comment by robwent** [comment]
It's not that some are missing.

I installed jellyfish, set up a music library and pointed it to the same folder I use with Plex.

It started downloading meta for albums without having to do anything.
No meta was downloaded for artists at all.

After checking the option which states that it controls meta for both albums and artists, the artist meta then started to populate.

So it seems to me that album meta downloads even when the option is off which is confusing because, according to the description of the option, nothing should download until the checkbox has been ticked.

**Comment by 27md** [comment]
> Getting the same on Ubuntu.
> 
> I tried changing the `EnableSimpleArtistDetection` to false in `etc/jellyfin/system.xml`
> restarted the service, removed the library, deleted any artist meta under `/jellyfin/metadata/artists`
> then added the library back again and still have no artist images.
> 
> If I try and manually identify an artist by adding an ID from theaudiodb then nothing comes back in the search. So it feels like something is wrong with the agents?
i get this too, when i try to identify artist i get an empty page

**Comment by robwent** [comment]
@27md try https://github.com/jellyfin/jellyfin/issues/2625#issuecomment-610109954

**Comment by 27md** [comment]
i tried it, now some (around 30%) of artists show images, other's still don't
some just don't link to musicbrainz but weirdly when i click identify and just type the name it works

**Comment by robwent** [comment]
It might be that they are still updating? I think it took quite a while for mine to complete.
There were still a few missing at the end but I've collected some weird music over the years and others that aren't tagged properly.

**Comment by 27md** [comment]
nope, 5 days later some still have no poster. some of them are not recognized but others when i click identify and i choose the artist it shows correctly

**Comment by 27md** [comment]
Also Clairo for example, it didn't identify her, when i did manually the biography won't show even tho it's on musicbrainz

**Comment by ferferga** [comment]
@27md Can you rerun scans again? Nothing changes unless you have automated tag refreshing active or scan manually, so it shouldn't make a difference the amount of days passed.

Do also note that MusicBrainz has quite tight API restrictions and rate limitations, so, as other pointed, it can take quite a while. If some artists are missing, repeat the scanning as many times as possible, until you see that no new images appear for them. Once that happens, check that those artists have a photo in musicbrainz.

Biographies doesn't work for me either, but that's a completely unrelated issue.

Closing this for now as the original issues has been resolved. Open a new one if you deem it necessary.
