### ISSUE TITLE
DLNA server not discoverable when secure connection mode set to "Handled by reverse proxy"

### ISSUE THREAD

**Issue by mcrapts** [jellyfin/jellyfin#2630]
**Describe the bug**
The DLNA server not discoverable when secure connection mode set to "Handled by reverse proxy". I have a public domain name that resolves my Jellyfin server, and I want to be able to locally use DLNA and publicly use the Chromecast. With secure connection mode set to "Disabled", DLNA works but I'm only able to use Chromecast locally because it will connect to the local IP address. Changing the secure connection mode to "Handled by reverse proxy" will solve this, but then will break DLNA discoverability.

**System (please complete the following information):**
 - OS: Ubuntu
 - Virtualization: Docker
 - Clients: DLNA clients
 - Browser: not applicable
 - Jellyfin Version: 10.4.3 and 10.5.0
 - Playback: not applicable
 - Installed Plugins: not applicable
 - Reverse Proxy: Nginx
 - Base URL: none
 - Networking: host
 - Storage: local

**To Reproduce**
1. Go to Admin > Advanced > Networking
2. Set secure connection mode to "Handled by reverse proxy"
3. Try to discover the the DLNA server using a DLNA client
4. Server will not be found

**Expected behavior**
DLNA server will be found

**Logs**
No errors.

**Comment by Artiume** [comment]
Known issue

https://github.com/jellyfin/jellyfin/issues/2259 

Set secure mode to Disabled. Using a reverse proxy, there is no difference in functionality

**Comment by mcrapts** [comment]
It won't break the Chromecast functionality completely, but setting the mode to "Disabled" means that it will connect to the local IP adress according to the /System/Info/Public endpoint, which is not availabile publicly, so this means that it will only work on the local network.

**Comment by PrplHaz4** [comment]
Does your domain name resolve to your local IP inside the network?

I started a table here to document the URL returned as secure connection mode changes: https://github.com/jellyfin/jellyfin-docs/issues/196

**Comment by mcrapts** [comment]
No, it resolves to my public IP address.

**Comment by Artiume** [comment]
Secure Connection Mode has been deprecated and removed in 10.6 so hopefully this will be fixed. 

https://github.com/jellyfin/jellyfin-web/pull/1140
