### ISSUE TITLE
Docker ARM updated to v3.5.3-4 2018-12-20?

### ISSUE THREAD

**Issue by SenorSmartyPants** [jellyfin/jellyfin#264]
Was the docker ARM container updated to the latest release?

Dashboard version reports 3.5.2.0.

Playing videos via DLNA doesn't work, which was supposed to be fix in the title release.

Android clients can't connect to JF server.

**Comment by nvllsvm** [comment]
Should be.

The version in the dashboard is incorrect in the latest release.

DLNA requires `--net=host` to be used. I'm assuming you tried that since you were commenting on another issue regarding that.

As for Android, not sure why that isn't working.

**Comment by SenorSmartyPants** [comment]
Correct, using --net=host.

DLNA server is visible and browsable. But when attempting to play a video VLC displays an error message.

**Comment by anthonylavado** [comment]
Re-opened #223. We'll need to continue investigating and gather logs.
