### ISSUE TITLE
version 10.5.1 >10.5.2

### ISSUE THREAD

**Issue by dga4130-renato** [jellyfin/jellyfin#2652]
Nightly release still says 10.5.0 while 10.5.2 is allready released

**Comment by dga4130-renato** [comment]
I believe this breaks some plugins, 
https://github.com/jellyfin/jellyfin-plugin-reports/issues/21
can this be fixed ?

**Comment by telans** [comment]
I think this was just fixed with https://github.com/jellyfin/jellyfin/pull/2730

**Comment by dga4130-renato** [comment]
> I think this was just fixed with #2730

ok thanks, hope will get in next nightly build then !

**Comment by dga4130-renato** [comment]
This is not fixing the problem as the version is still 10.5.0 and many plugins claim 
System.IO.FileNotFoundException: Could not load file or assembly 'MediaBrowser.Common, Version=10.5.2.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Talking about this also on reddit. nightly has to bump uo to 10.5.2 also
https://www.reddit.com/r/jellyfin/comments/frn39o/jellyfin_crashing_when_installing_plugin/
