### ISSUE TITLE
[bug] new 10.5.0 page layout disappeared.

### ISSUE THREAD

**Issue by emaen** [jellyfin/jellyfin#2659]
Hi !

When first started, new v.10.5.0 layout is ok.
If I made a "refresh metadatas" for an artist ( music section ) or for all library, then layout fallback to old version.
Layout fallback on web viewer and android app.
Closing jellyfin and restart it made new layout available again.
But when refreshing metadatas, falls back to old version again.

Windows seven
Portable jellyfin ( from 10.4.3 to 10.5.0 by renaming to "old", "system" folder as explained )
Jellyfin not set as service.

**Comment by emaen** [comment]
It's account related.
Using a second account, let's see the new layout, while primary account still using old layout !

**Comment by Bond-009** [comment]
Did you try clearing your browser cache?

**Comment by emaen** [comment]
Yes, I did right now : it's the same thing : old layout, not the new one.

**Comment by JustAMan** [comment]
Can you record a shot clip demonstrating the behaviour?

**Comment by emaen** [comment]
Sorry for this late answer.
I've updated to 10.5.2 with a fresh install ( erased all appdata/local/jellyfin datas ) and no longer have this trouble with the layout.
Thank you for your interest !

**Comment by JustAMan** [comment]
Closing then. Feel free to re-open if you would see the issue again.
Happy Jellyfinning!
