### ISSUE TITLE
Creating a playlist with photos gives error

### ISSUE THREAD

**Issue by Coloradohusky** [jellyfin/jellyfin#2663]
**Describe the bug**
Making the playlist works fine, but when clicking on the playlist, gives the message "Playback Error: There was an issue with the client profiling and the server isn't sending a compatible media format".

**System (please complete the following information):**
 - OS: Windows
 - Virtualization: None
 - Clients: Browser
 - Browser: Chrome 80.0.3987.149
 - Jellyfin Version: 10.5.2
 - Playback: Direct Play
 - Installed Plugins: None
 - Reverse Proxy: None
 - Base URL: None
 - Networking: Host
 - Storage: Local

**To Reproduce**

1. Click and hold on picture
2. Go to top right and click on '...'
3. Click 'Add to playlist'
4. Add to a playlist or create a new playlist
5. Go to home
6. Click 'Playlists'
7. Click on your playlist and see the error

**Expected behavior**
The playlist should play the images added to it

**Logs**
Using Jellyfin (View Console) in debug mode doesn't show any errors

**Comment by JustAMan** [comment]
Please provide server logs, even if they don't contain any errors.

**Comment by Coloradohusky** [comment]
[Here's the log.](https://github.com/jellyfin/jellyfin/files/4430511/log.log)

The playlist I named 'Stuff', and creation of the playlist happens in line 1822, at ]2020-04-03 20:46:19.806 -04:00]. Logs are in debug mode, and below is a picture of what pops up when I make a playlist of photos.

![playback_error](https://user-images.githubusercontent.com/45430066/78415041-41365480-75ed-11ea-80ed-c9873c719ec6.png)

**Comment by Coloradohusky** [comment]
Still occurs on 10.5.3.

**Comment by JustAMan** [comment]
The log above doesn't show any errors, is it because it's where you make a playlist instead of the one you actually trying to open a playlist?

**Comment by Coloradohusky** [comment]
I both make it and try to open it during that log, however no errors show up in the log, just on my screen with the popup

**Comment by JustAMan** [comment]
Okay, thanks for the info.

**Comment by Coloradohusky** [comment]
Same error happens in 10.5.5.
