### ISSUE TITLE
Only movie extras with suffixes are loaded in after 10.5.2

### ISSUE THREAD

**Issue by dtparr** [jellyfin/jellyfin#2665]
**Describe the bug**
In earlier versions, any video in a movie's 'extras' folder (along with a couple other specific names like 'behind the scenes') would load up as Special Features.  In 10.4.3 and 10.5.0, that was broken entirely (see #2484 ).  In 10.5.2, #2642 appears to have partially corrected the issue.  Based on a quick perusal, it appears that now files in 'extras', 'behind the scenes', and 'deleted scenes' that end in certain suffixes (e.g. -deleted, -featurette, -behindthescenes, etc.) are being loaded in as special features.  However, files that contain no suffix, or an inappropriate suffix (e.g. -other) are not being pulled in as special features.

I checked the docs and didn't find anything about how to name extras.  If this is an intentional design decision, feel free to close.  It's less about having a particular preference to how they're pulled and more about being consistent.  

**System (please complete the following information):**
 - OS: Ubuntu 18.04
 - Virtualization: LXC
 - Clients: Web
 - Browser: Firefox 74
 - Jellyfin Version: 10.5.2
 - Playback: N/A
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: [e.g. none, yes: /example]
 - Networking: macvlan
 - Storage: local

**To Reproduce**
Place video in extras subfolder of movie, such as 
/Movies/MovieName/extras/SomeSpecialFeature1.mkv
/Movies/MovieName/extras/SomeSpecialFeature2-deleted.mkv

**Expected behavior**
Both files would be treated as special features.  Currently only '2' would be.

**Logs**
N/A

**Comment by cryptobank** [comment]
I surely hope its not meant to work this way as i will have to spend about a week maybe 2 renaming every single special feature file on my NAS.

**Comment by dkanada** [comment]
@mark-monteiro and @Bond-009 this might be the problem with extras right now.

**Comment by mark-monteiro** [comment]
> @mark-monteiro and @Bond-009 this might be the problem with extras right now.

Yeah, this was also mentioned [in another comment](https://github.com/jellyfin/jellyfin/pull/2642#issuecomment-603159592). I've been meaning to look into this, but haven't had the time yet. The whole extras identification is a bit of a mess, I will probably open a few PRs by the end of it.
