### ISSUE TITLE
Can not display CJK glyphs in .ass subtitles

### ISSUE THREAD

**Issue by frankyifei** [jellyfin/jellyfin#2670]
I run Jellyfin on windows system.
from browser console:
```
libass: Shaper: FriBidi 1.0.8 (SIMPLE) HarfBuzz-ng 2.6.4 (COMPLEX)
subtitles-octopus-worker.js:270 libass: Using font provider fontconfig
subtitles-octopus-worker.js:270 libass: Added subtitle file: '/sub.ass' (2 styles, 2714 events)
subtitles-octopus-worker.js:270 libass: Neither PlayResX nor PlayResY defined. Assuming 384x288
libass: fontselect: Using default font: (方正黑体_GBK, 400, 0) -> /assets/default.woff2, 0, (none)
libass: Glyph 0x6253 not found, broken font? Trying all charmaps
libass: Glyph 0x6253 not found in font for (方正黑体_GBK, 400, 0)
libass: fontselect: Using default font: (方正黑体_GBK, 400, 0) -> /assets/default.woff2, 0, (none)
```
方正黑体 is the font defined in ass file. I have this font in my windows system. I dont know what is this default.woff2. There is no such file in that folder inside jellyfin.
I do not have fontconfig on my windows system.

**Comment by frankyifei** [comment]
Octopus does have its own default font though. I believe it is the reason why this problem was not pick up. If it was not tested against CJK .ass, nobody will notice this. It is better if sever side could provide fonts for CJK. The woff2 is about 10mb.

**Comment by frankyifei** [comment]
is there anyone can give me a hint that how to use the included jellyfin-noto fonts? I need to figure out how to get the path of the woff2 files as JavascriptSubtitlesOctopus needs fonts path. Jellyfin-noto was included as a yarn package, I don't know how to get the font path from javascript side.

**Comment by FunnyFly-ZW** [comment]
Same problem, watching this issue.

**Comment by Alice-Schuberg** [comment]
I thought it would be resolved in 10.5.3 #2653, but this issue remains

[assLog.txt](https://github.com/jellyfin/jellyfin/files/4437531/assLog.txt)

**Comment by frankyifei** [comment]
> I thought it would be resolved in 10.5.3 #2653, but this issue remains
> 
> [assLog.txt](https://github.com/jellyfin/jellyfin/files/4437531/assLog.txt)

This is about javasubtitlesoctopus do not have a fallback CJK fonts. see https://github.com/jellyfin/jellyfin-web/issues/934

**Comment by MrTimscampi** [comment]
Please test 10.5.3.

SubtitleOctopus was updated to 4.0.0, which claims to fix your issue.

**Comment by frankyifei** [comment]
> Please test 10.5.3.
> 
> SubtitleOctopus was updated to 4.0.0, which claims to fix.ASS subtitles not having a CJK-compatible fallback font.

No, `@JustAMan` is considering to reuse Jellyfin-noto but it has not happened. [his comment](https://github.com/jellyfin/jellyfin-web/issues/934#issuecomment-608074015)
Modify `jellyfin-web\components\htmlvideoplayer\plugin.js` is the best way to add custom fonts now.

**Comment by sheiy** [comment]
Same problem

**Comment by nyanmisaka** [comment]
> Same problem

Please try this function in 10.7 version. https://github.com/jellyfin/jellyfin/pull/3683

**Comment by Gateswong** [comment]
A quick and dirty fix is to copy your woff2 font to `jellyfin-web/assets/default.woff2`.

For my case, I added this in my docker-compose:

```
services:
    app:
        image: jellyfin/jellyfin
        volumes:
            - ./fonts/woff2/NotoSansCJKsc-Regular.woff2:/jellyfin/jellyfin-web/assets/default.woff2
```

This should solve the problem, but it should be only considered as a temporary solution.

**Comment by rebroccoli** [comment]
:+1: Same problem...

**Comment by POFK** [comment]
Same problem

**Comment by felix920506** [comment]
This issue can be solved by installing fallback fonts in web or installing system fonts on the server when burning in subtitles. Is this still relevant?

**Comment by ana-rchy** [comment]
same problem on nixos, already have cjk system fonts and a cjk fallback font set
