### ISSUE TITLE
what it means in dashboard activity devices displaying：“direct playing”

### ISSUE THREAD

**Issue by stingwan** [jellyfin/jellyfin#2673]
**Media Info of the file**

**Logs**

**FFmpeg Logs**

**Stats for Nerds Screenshots**

**Server System (please complete the following information):**
 - OS: [e.g. Docker on Linux, Docker on Windows, Debian, Windows]
 - Jellyfin Version: [e.g. 10.0.1]
 - Hardware settings & device: [e.g. NVENC on GTX1060, VAAPI on Intel i7 8700K]
 - Reverse proxy: [e.g. no, nginx, apache, etc.]
 - Other hardware notes: [e.g. Media mounted in CIFS/SMB share, Media mounted from Google Drive]
 
**Client System (please complete the following information):**
 - Device: [e.g. Apple iPhone XS, Xbox One S, LG OLED55C8, Samsung Galaxy Note9, Custom HTPC]
 - OS: [e.g. iOS, Android, Windows, macOS]
 - Client: [e.g. Web/Browser, webOS, Android, Android TV, Electron]
 - Browser (if Web client): [e.g. Firefox, Chrome, Safari]
 - Client and Browser Version: [e.g. 10.3.4 and 68.0]

**Comment by Artiume** [comment]
Direct Play means the client fully supports the media file as is and does not need conversion for support.

https://jellyfin.org/docs/general/clients/codec-support.html
