### ISSUE TITLE
Getting HTTP error code 404 when trying to save hardware acceleration settings

### ISSUE THREAD

**Issue by erkexzcx** [jellyfin/jellyfin#2677]
**Describe the bug**
Hardware acceleration cannot be enabled on my Raspberry Pi 4. Once I click save and get past the warning - I get error that tells me to try again later. In browser console it shows 404...

**System:**
 - OS: Arch Linux armv7h (server) and Arch Linux X86_64 (client)
 - Virtualization: No
 - Clients: PC Browser
 - Browser: Latest official Google Chrome (from AUR, binary release)
 - Jellyfin Version: 10.5.2-1 (debian binary, downloaded from official jellyfin repo)
 - Playback: N/A
 - Installed Plugins: None
 - Reverse Proxy: None
 - Base URL: None
 - Networking: N/A
 - Storage: N/A

**To Reproduce**
1. Install [jellyfin-bin](https://aur.archlinux.org/packages/jellyfin-bin/) from AUR on Raspberry Pi 4 (Arch Linux ARM)
2. Go to Jellyfin web interface --> Playback.
3. Select Hardware acceleration from dropdown.
4. Click "Save".
5. Skip warning that says "Enabling hardware acceleration may cause instability...".
6. Get another popup (error), saying "There was an error processing the request. Please try again later.".
7. Check browser's console and notice 404 error. Also nothing has happened, no settings were saved.

**Expected behavior**
Successfully save selected settings

**Logs**
None. See screenshot.

**Screenshots**
![image](https://user-images.githubusercontent.com/5955795/77678494-e8860c80-6f99-11ea-8ab9-8028f9516afa.png)

**Additional context**
I am author & maintainer of [jellyfin-bin](https://aur.archlinux.org/packages/jellyfin-bin/) package. :)

**Comment by dkanada** [comment]
I looked into this and discovered that all configurable paths will throw an error if the directory doesn't exist, which isn't ideal.

**Comment by nyanmisaka** [comment]
> I looked into this and discovered that all configurable paths will throw an error if the directory doesn't exist, which isn't ideal.

It seems that the `transcodes` and `metadata` folders are not created automatically during installation, at least on archlinux. Unless I manually create these two folders, there will be no error when saving the settings.

**Comment by erkexzcx** [comment]
> I looked into this and discovered that all configurable paths will throw an error if the directory doesn't exist, which isn't ideal.

So do these folders are expected to be created by the installer, or by Jellyfin app?

Looks like these folders exist on the system, and in overall `/var/lib/jellyfin` seem to have correct permissions:
```
[root@storager jellyfin]# ls -la
total 36
drwxr-xr-x  9 jellyfin jellyfin 4096 Mar 26 17:53 .
drwxr-xr-x 25 root     root     4096 Mar 26 11:05 ..
drwxr-xr-x  3 jellyfin jellyfin 4096 Mar 26 14:29 .aspnet
drwxr-xr-x  4 jellyfin jellyfin 4096 Mar 26 14:45 config
drwxr-xr-x  5 jellyfin jellyfin 4096 Mar 26 14:32 data
drwxr-xr-x  2 jellyfin jellyfin 4096 Mar 26 17:53 log
drwxr-xr-x  6 jellyfin jellyfin 4096 Mar 26 17:49 metadata
drwxr-xr-x  3 jellyfin jellyfin 4096 Mar 26 14:29 root
drwxr-xr-x  2 jellyfin jellyfin 4096 Mar 26 17:53 transcodes
[root@storager jellyfin]# pwd
/var/lib/jellyfin
[root@storager jellyfin]#
```

**Comment by stevleibelt** [comment]
Almost the same for me.
I have a transcoding-temp.

```
[user@maschine jellyfin]$ pwd
/var/lib/jellyfin
[user@maschine jellyfin]$ ls -al
total 9
drwxr-xr-x  9 jellyfin jellyfin  9 Mar 13 19:09 .
drwxr-xr-x 22 root     root     23 Mar 26 00:00 ..
drwxr-xr-x  3 jellyfin jellyfin  3 Mar 13 19:09 .aspnet
drwxr-xr-x  4 jellyfin jellyfin  9 Mar 13 19:09 config
drwxr-xr-x  5 jellyfin jellyfin 16 Mar  1 23:11 data
drwxr-xr-x  2 jellyfin jellyfin  5 Mar 26 00:07 log
drwxr-xr-x  6 jellyfin jellyfin  6 Mar  2 13:58 metadata
drwxr-xr-x  3 jellyfin jellyfin  3 Mar  1 23:07 root
drwxr-xr-x  2 jellyfin jellyfin  2 Mar  1 23:07 transcoding-temp
```

**Comment by erkexzcx** [comment]
OK I haven't touched anything. Just randomly went to settings, set hardware acceleration and clicked save - settings are now saved without any error. Feel free to close this issue. No idea what happened...

**Comment by JustAMan** [comment]
@dkanada @nyanmisaka were you able to reproduce the issue?

**Comment by nyanmisaka** [comment]
> @dkanada @nyanmisaka were you able to reproduce the issue?

Yes. Usually, the `metadata` and `transcodes/transcoding-temp` folders are not created automatically when jellyfin is installed for the first time. Therefore, the interface language set during initialization will not take effect and cannot be saved manually. Until you manually create these folders.

**Comment by JustAMan** [comment]
@erkexzcx this should be fixed now, could you please re-test?
