### ISSUE TITLE
MusicAlbum and MusicArtist items cannot be marked played

### ISSUE THREAD

**Issue by Aanok** [jellyfin/jellyfin#2687]
**Describe the bug**
In the context of a Music library:
- If you send a POST to the `/Users/{UserId}/PlayedItems/{Id}` endpoint to mark a MusicAlbum or MusicArtist item as played has no effect, the item remains marked as unplayed.
- If you mark as played all tracks within an album, the album item itself is not marked as played.
- If you mark as played all tracks under an artist, the artist itself is not marked as played.

**System:**
 - OS: Debian 9.12
 - Virtualization: None, installed from apt
 - Clients: All
 - Browser: Any
 - Jellyfin Version: 10.5.2

**To Reproduce**
Use your favourite client to mark a MusicAlbum or MusicArtist as played.

Alternatively, mark played all tracks under an album or artist.

**Expected behavior**
The MusicAlbum or MusicArtist items are marked played.

Of note: watching all episodes of a TV show season or series correctly marks either as played. Likewise, playing all tracks in a Folder within a Books library correctly marks the entire Folder as played.

Of further note: when a Music library is accessed via the Folder view and thus the artist and albums are presented as Folder items, the Played property is set correctly for the album but not the artist.

**Logs**
Nothing shows up.

**Comment by JustAMan** [comment]
I don't think music was expected to have a "played" state at all. Let's ask @dkanada

**Comment by Aanok** [comment]
The bug is still present.

**Comment by Aanok** [comment]
I confirm this is still the case with 10.6.4.

**Comment by Simonmicro** [comment]
> I don't think music was expected to have a "played" state at all. Let's ask @dkanada

Imagine a user using Jellyfin for podcasts... I would need that too :)

**Comment by Aanok** [comment]
> Imagine a user using Jellyfin for podcasts... I would need that too :)

For podcasts you should use a Books library, those track progress and watched status correctly. The items won't show up in Next Up, though. The web client also doesn't show them in Favorites.

**Comment by Simonmicro** [comment]
Oooh, _Audio_-Books! I thought that category would be for pdf files... Like the photos category is also for non-video/music files!

I propose a name change :grin:

**Comment by cvium** [comment]
This is basically a feature request. Re-open at https://features.jellyfin.org.

MusicAlbum and MusicArtist aren't real entities in the current db schema. They are basically just "folders" for encapsulating songs.

**Comment by Aanok** [comment]
@cvium I can't say I really agree with this. You're talking about an implementation detail, but there is no way to know about this from a user's point of view, whether end user or API user: the application behaves inconsistently in a very arbitrary manner. To me, this is a bug caused by (whatever the Emby people where drinking when they designed) the schema.

Now, if you mean to say this isn't worth addressing until the DB rewrite, that's 100% valid on the other hand!

**Comment by cvium** [comment]
Both. It works as "intended" even if it's terrible UX. And it's not worth fixing until the db rewrite.
