### ISSUE TITLE
DLNA: folder "Continute watching" is empty

### ISSUE THREAD

**Issue by rchovan** [jellyfin/jellyfin#2688]
Continue watching does not work for DLNA. When I play and stop watch movie from web browser, or Jellyfin app, then I can see it "Continue watching" on browser, or mobile app. But this information is not available over DLNA. Does not matter if I star movie over DLNA, or I want to continue over DLNA, folder Continue watching is empty.

**System :**
 - OS: main OS Debian, running in docker 
 - Virtualization: Docker
 - Clients: DLNA (LG WebOS)
 - Jellyfin Version: 10.5.2
 - Playback: does not matter
 - Installed Plugins: auto organize 
 - Reverse Proxy: none, available only from LAN
 - Base URL: none
 - Networking: Host
 - Storage: local

**To Reproduce**

1. Connect over DLNA
2. Navigate to "Continue watching" folder
3. nothing is displayed 

**Expected behavior**
Show media which belongs to actual library and are valid for resume playback.

**Logs**
can't find anything usable in logs. If you can instruct me what should I debug, I can provide more useful logs.

**Comment by JustAMan** [comment]
There should be some DLNA debug options somewhere, right @prplhaz4?
Also I think DLNA was bugged this way from the beginning, so it's a long-standing inherited issue if my memory serves me well.

**Comment by PrplHaz4** [comment]
> There should be some DLNA debug options somewhere, right @PrplHaz4?
> Also I think DLNA was bugged this way from the beginning, so it's a long-standing inherited issue if my memory serves me well.

Admin dashboard -> dlna -> debug logging

This is likely a bug in how the dynamic folder is generated and the fact that dlna does  not track playback progress (so if purely dlna there will be no way to make something in-progress)
