### ISSUE TITLE
last fm scrobbling 

### ISSUE THREAD

**Issue by screwfaze** [jellyfin/jellyfin#269]
This would be an awesome feature.

Thanks

**Comment by LeoVerto** [comment]
Libre.fm and ListenBrainz would also be nice to have so implementing this should probably done in a pretty modular way.

**Comment by Cerothen** [comment]
One would think much like the Trakt plugin it should be fully possible to implement just as a plugin rather than as the core code.

Still though, being able to scobble music would be nice if possible on a per user basis.

**Comment by dbogdanov** [comment]
Is https://github.com/Veisen/Last.fm related?

**Comment by anthonylavado** [comment]
@dbogdanov Kind of? That user ported the original plugin from Emby, but since the original is unlicensed, we can't host it/share it.
