### ISSUE TITLE
Subfolders 3+ deep in the library are mishandled

### ISSUE THREAD

**Issue by AncientMystic** [jellyfin/jellyfin#2691]
when adding new media all files added under the 3rd subfolder are counted as the content itself and not a folder although it will display as a folder and even load cover art related to what is inside but the item itself is always empty either counting the folder as an empty folder or an empty item by itself.

example /folder1/folder2/folder3/ 
all folders falling under the place of folder3 will be empty lets say we have /folder1/folder2/title of folder/ the "title of folder" will be there but it is always empty even though content exists inside the folder the media scan seems to stop 3 steps deep into subfolder scanning. 

**System (please complete the following information):**
 - OS: Windows server 2012 R2
 - Virtualization: none
 - Clients: none
 - Browser: Konqueror 5.0.97 based on chrome like all browsers now, from a linux laptop others do not seem to display correctly icons display as text and cannot click enitre sections of the options for some reason (possibly iss or another conflicting application?) 
 - Jellyfin Version: 10.5.2
 - Playback: none
 - Installed Plugins: defaults
 - Reverse Proxy: none, local network only
 - Base URL: none just ip to server
 - Networking: irrelevant
 - Storage: local storage

**To Reproduce**
add any supported file 3+ folders deep and watch no file appear in the library with the added folder that contains it.

**Expected behavior**
folder or file listed as present nothing deeper, no files and missing folders, it seems to have a depth limit on the library scan

edit: pdf files and audios seem to have the most problems being sorted into the library, but it will also skip folders with folders inside because its 3+ deep.

**Comment by JustAMan** [comment]
@AncientMystic I tried to edit the title to represent the issue you described more precisely. Could you please verify I did so correctly?

**Comment by davispuh** [comment]
I've also same issue using latest v10.5.5

**Comment by hxck** [comment]
I'm having the same issue in 10.5.5.

The films show when browsing on the website with Firefox 78.0.2, but they don't show in the Roku app.

Running in docker 19.03.12-ce on Manjaro (kernel 5.6.16-1-MANJARO)

**Comment by ferferga** [comment]
@hxck We believe the problem it's fully present in 10.6 but can you update? We oy support the latest version

**Comment by davispuh** [comment]
Yup, it's still present. Doesn't find those movies.

**Comment by ferferga** [comment]
This might need a retest. @davispuh @AncientMystic can you guys spin a copy of your server with unstable docker image?

If that's much hassle, let's wait for 10.7RC1.

**Comment by Ullmie02** [comment]
I think we fixed this issue somewhere. I tried with the following paths in a movie library and the show up as expected:

- `/media/Test/Sagas/Fantasy/JK/Harry Potter/Harry Potter (2001)/Harry Potter (2001).mp4`
- `/media/Test/Sagas/Fantasy/JK/Harry Potter/Harry Potter und die Heiligtümer des Todes (2011)/Harry Potter und die Heiligtümer des Todes (2011).mp4`

`/media/Test` is the folder I added as a library.

**Comment by Cockhash** [comment]
I'm experiencing exactly the same problem (also described in #3073) in version 10.7.1.
"Other" content type is respecting the folder structures but "Movies" content type just mixes all video files into one.

**Comment by holow29** [comment]
> I'm experiencing exactly the same problem (also described in #3073) in version 10.7.1.
> "Other" content type works fine but "Movies" content type just mixes all video files from all subfolders into the Library folder and doesn't respect the folder structures.

I believe this issue is separate from what you referenced. This issue had to do with the video files not showing up at all whereas the issue you referenced is related to the folder structure being destroyed on import. (Basically, I think this issue has been correctly solved and closed; you might want to post your experience in 3073)
