### ISSUE TITLE
Noticeable distortion in transcoded music

### ISSUE THREAD

**Issue by PeterCxy** [jellyfin/jellyfin#2695]
**Describe the bug**

When playing over the Internet and "Music Quality" is set to 320kbps (and of course also applies to below) to force transcode my flac music, there is noticeable distortion (like, not just "sounds worse", but actual distortion) in the resulting audio which should not be supposed to happen in formats like mp3 and aac. The distortion is exaggerated when the source audio is Sony's "High-Res" files (24-bit / 96kHz, purchased from Mora)

Unfortunately I don't have a file that can reproduce this exact issue that I have permission to redistribute; however I tried quite some files and most of them show distortion when transcoded by Jellyfin, especially those "High-Res" ones (though I don't have much of those).

**System (please complete the following information):**

 - Virtualization: Docker
 - Browser: Tested on latest Firefox
 - Jellyfin Version: 10.5.2

**To Reproduce**

1. Go to Settings - Playback
2. Set music quality to 320kbps (or below)
3. Play a music
4. Notice distortion (especially in higher frequencies like hi-hats)

**Expected behavior**

Music should not be distorted this much at 320kbps using any sensible modern encoding.

**Additional context**

Is there an easy way to check what encoding is currently being sent to the client browser? I suspect this may be a codec selection thing or related to jellyfin-ffmpeg, but not sure.

**Comment by PeterCxy** [comment]
From `F12` I can see `AudioCodec: "aac"` in request parameters. It makes even less sense now: I'm pretty sure I shouldn't be able to hear any difference between a 320kbps aac and a "lossless" file

**Comment by PeterCxy** [comment]
Ok it looks like it's related to ffmpeg's aac codec. I guess I should close this issue here because it's not really something fixable by jellyfin.

**Comment by JustAMan** [comment]
There's a PR open to prefer Fraunhofer AAC if your ffmpeg has it compiled: https://github.com/jellyfin/jellyfin/pull/2715
Note that due to license conflicts in ffmpeg we cannot redistribute that ffmpeg, but you may build it yourself (e.g. by using my pet repo https://github.com/JustAMan/ffmpeg-standalone-build )
