### ISSUE TITLE
Poster ignored if movie is multipart and not public (imdb,tmdb)

### ISSUE THREAD

**Issue by millallo** [jellyfin/jellyfin#2697]
**Describe the bug**
I'have some homemade multi-part movies whit poster associated but Jellyfin prefers to extract thumbnails instead of using the poster. Only single-part movies are presented with the poster.
Public multi-part movies (imdb or tmdb) don't present this kind of problem. I tried all possible variations of Library Configuration but without success.

**System (please complete the following information):**
 - OS:  Debian
 - Virtualization: no
 - Clients: Browser
 - Browser: Firefox 74
 - Jellyfin Version: 10.5.2
 - Installed Plugins: none
 - Base URL: none
 - Networking: Host
 - Storage: local

**To Reproduce**
Filesystem of my Test Library:
<img width="177" alt="Screenshot 2020-03-28 at 15 03 52" src="https://user-images.githubusercontent.com/1112565/77824779-60bd1100-7105-11ea-95f2-be0a83b0131b.png">

**Expected behavior**
Both movies should be presented with the their poster, but only test1 works. Test2 is shown with a thumbnail of test2-cd1.avi.

**Logs**
No error logs

**Screenshots**
<img width="416" alt="Screenshot 2020-03-28 at 14 58 04" src="https://user-images.githubusercontent.com/1112565/77824706-f1dfb800-7104-11ea-9935-f44f4f8acb13.png">

**Comment by progtologist** [comment]
Can you try renaming `test2-poster.jpg` to `test2-cd1-poster.jpg`?

**Comment by millallo** [comment]
Renamed and poster is displayed. I was wrong naming it or it is an issue?

**Comment by progtologist** [comment]
Can't say if it is intended behavior or not, it's up to the devs to decide I guess, but I knew it is "working" like that.

**Comment by Artiume** [comment]
I would say it's working as intended but it could definitely be fixed to be more intelligent and not require the asinine naming.
