### ISSUE TITLE
Episodes in older seasons showing up multiple times on a list

### ISSUE THREAD

**Issue by adatamonk** [jellyfin/jellyfin#2701]
**Describe the bug**
This bug is really strange. Basically for any older season of any tv series, the episodes are listed repeatedly .... even though there is just one file per episode on storage 

**System (please complete the following information):**
 - OS: Ubuntu 18.04
 - Virtualization: Docker
 - Clients: Browser, Android, Fire Stick
 - Jellyfin Version: latest 10.5.2

**To Reproduce**
1. Go to any show
2. Click on an older season (not current season)
3. See the episodes listed multiple times

**Expected behavior**
one line per episode

**Screenshots**
https://i.imgur.com/fkq2GX1.png

**Comment by agamus** [comment]
upon further investigation, it looks like if I have mutiples copies of a file it shows up twice? any way to combine these?

**Comment by dkanada** [comment]
Are they different resolutions or something?

**Comment by agamus** [comment]
yes sometimes, but other times I had 2 copies of the file .... does jellyfin not "merge" this into one?

**Comment by dkanada** [comment]
We try to avoid messing with files as much as possible, so I don't believe so. We even suggest mounting your library without write permissions to avoid any possible issues.

**Comment by agamus** [comment]
that's fair, but would it not be more efficient to not display the episode multiple times? I was thinking if multiple files exist it should show the episode once (maybe with a drop down of all the quality profiles or copies of the episode)
