### ISSUE TITLE
Plugins crash

### ISSUE THREAD

**Issue by dga4130-renato** [jellyfin/jellyfin#2707]
ubuntu 19.10
Fanart and reports plugin crash when installing. 
server locked up
[bug.txt](https://github.com/jellyfin/jellyfin/files/4399064/bug.txt)

**Comment by telans** [comment]
I'm fairly sure this is an issue with the seperate plugins as they require updating.

**Comment by dga4130-renato** [comment]
yeah i realize that 4.0.0 is installing but not working. 5.0.0 is crashing everything.
it's the plug-in anyway. tested now
