### ISSUE TITLE
Subtitles don't appear, "Fetching additional data" indefinitely

### ISSUE THREAD

**Issue by CutterXYZ** [jellyfin/jellyfin#2710]
Sometimes Jellyfin doesn't display the subtitles and the message "Fetching additionnal data" is displayed indefinitely in the player. In this example the subtitles are encoded in UTF8 and stored in the mkv file being played. I've tried restarting the server and refreshing the library. I've had this bug in previous versions already. I couldn't find an error in the logs.

**Media Info of the file**
the.kominsky.method.s01e01.720p.webrip.x264-strife
Containermkv
PathD:\Downloads\BitTorrent\Séries\The.Kominsky.Method.S01.720p.WEBRip.x264-STRiFE\the.kominsky.method.s01e01.720p.webrip.x264-strife.mkv
Size724 MB
Video
Title720P H264
CodecH264
AVCYes
ProfileHigh
Level41
Resolution1280x678
Aspect ratio640:339
InterlacedNo
Framerate23.976025
Bitrate2992 kbps
Bit depth8 bit
Pixel formatyuv420p
Ref frames1
NAL4
Audio
TitleEng Dolby Digital+ 6 ch Default
Languageeng
CodecEAC3
Channels6 ch
Sample rate48000 Hz
DefaultYes
Subtitle
TitleEng
Languageeng
CodecSUBRIP
DefaultNo
ForcedNo
ExternalNo

**Logs**
no error found in logs

**Stats for Nerds Screenshots**

**Server System (please complete the following information):**
 - OS: Windows 10 64-bit
 - Jellyfin Version: 10.5.2
 - Hardware settings & device: i7 860, no hardware acceleration
 - Reverse proxy: no
 - Other hardware notes: media stored locally
 
**Client System (please complete the following information):**
 - Device: the server
 - OS: Windows 10
 - Client: Web browser
 - Browser: Firefox
 - Client and Browser Version: 75.0b10

**Comment by eltiel** [comment]
I believe it is a known problem, similar to this https://github.com/jellyfin/jellyfin/issues/2650

I've tested that it is fixed in the latest nightly. Give it a try.

**Comment by CutterXYZ** [comment]
I confirm it's fixed in today's nightly. Thanks!

**Comment by mrkylegp** [comment]
I don't believe this is fixed entirely. I'm on 10.5.5 and this is still happening to me.

**Comment by Scripty** [comment]
This is still an issue with 10.10.7

**Comment by e-v-o-l-v-e** [comment]
10.11.4 too, at least on web

**Comment by josephch5** [comment]
same, 10.11.5

**Comment by josephch5** [comment]
> same, 10.11.5

Fixed at least on web by changing the setting "Allow subtitle extraction on the fly" to off in the dashboard -> playback -> transcoding :)
