### ISSUE TITLE
Add chapters to movies.

### ISSUE THREAD

**Issue by vvttll** [jellyfin/jellyfin#2713]
First, say that I love Jellyfin. Is amazing !!

I have a request that perhaps, more people may be interested in and that I think is not implemented:
Would it be possible to put "chapters" in the movies? In other words, a 1 hour movie, for example to be able to mark/add this:
Chapter 1 begins at 00:00:00
Chapter 2 at 00:12:21
Chapter 3 at 00:23:12
Chapter 4 at 00:39:56
.............

It would be very very interesting.

Greetings to all and congratulations on the great work !!!!

**Comment by JustAMan** [comment]
Jellyfin has this support from the very beginning. Enable chapter extraction in the settings ans re-scan your library :)

**Comment by vvttll** [comment]
Yes, but you can edit this ???

**Comment by JustAMan** [comment]
Not at the moment I think. You can file a feature request here: https://features.jellyfin.org/

**Comment by vvttll** [comment]
Do it !! thanks !
