### ISSUE TITLE
Having issue with MKV file

### ISSUE THREAD

**Issue by flxlocle** [jellyfin/jellyfin#2714]
I'm having an issue with playing MKV file. After I convert this file into MP4 it worked perfectly. Wonder if there is a fix to this issue?
Thank you.

![Error](https://user-images.githubusercontent.com/53885793/77868618-e32ef900-7209-11ea-89c4-dbfec7cde887.PNG)

```
http://localhost:8096/videos/2f9fb77b-f68e-d704-3879-a1df8ee31c7e/live.m3u8?DeviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzgwLjAuMzk4Ny4xNDkgU2FmYXJpLzUzNy4zNnwxNTg1NDEwNTkzODg0&MediaSourceId=2f9fb77bf68ed7043879a1df8ee31c7e&VideoCodec=h264&AudioCodec=mp3,aac&VideoBitrate=139808000&AudioBitrate=192000&PlaySessionId=1d633a07a7b14cceb52709899256550b&api_key=05858847c762448f98ce08516f982f20&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=3510fc5ffc7246def2e3c15d6cbe836e&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline,high10&h264-level=51

{"Protocol":"File","Id":"2f9fb77bf68ed7043879a1df8ee31c7e","Path":"C:\\Media\\Shows\\The.Legend.Of.Korra.S01-S04.1080p.BluRay.x264-AR\\The.Legend.Of.Korra.S01.1080p.BluRay.x264-DeBTViD\\The.Legend.Of.Korra.S01E01.1080p.BluRay.x264-DeBTViD.mkv","Type":"Default","Container":"mkv","Name":"The.Legend.Of.Korra.S01E01.1080p.BluRay.x264-DeBTViD","IsRemote":false,"ETag":"3510fc5ffc7246def2e3c15d6cbe836e","ReadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"RequiresClosing":false,"RequiresLooping":false,"SupportsProbing":true,"VideoType":"VideoFile","MediaStreams":[],"MediaAttachments":[],"Formats":[],"RequiredHttpHeaders":{}}

C:\Program Files\Jellyfin\Server\ffmpeg.exe -hwaccel vaapi -hwaccel_output_format vaapi -vaapi_device /dev/dri/renderD128 -i file:"C:\Media\Shows\The.Legend.Of.Korra.S01-S04.1080p.BluRay.x264-AR\The.Legend.Of.Korra.S01.1080p.BluRay.x264-DeBTViD\The.Legend.Of.Korra.S01E01.1080p.BluRay.x264-DeBTViD.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -sn -codec:v:0 libx264 -pix_fmt yuv420p -preset veryfast -crf 23 -maxrate 139808000 -bufsize 279616000 -profile:v high -level 4.1 -x264opts:0 subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none -force_key_frames "expr:gte(t,n_forced*3)" -flags -global_header -vsync -1 -codec:a:0 libmp3lame -ac 2 -ab 192000  -f segment -max_delay 5000000 -avoid_negative_ts disabled -start_at_zero -segment_time 3  -individual_header_trailer 0 -segment_format mpegts -segment_list_entry_prefix "hls/fa9d01ef208b6d349a765468e9a82400/" -segment_list_type m3u8 -segment_start_number 0 -segment_list "C:\ProgramData\Jellyfin\Server\transcodes\fa9d01ef208b6d349a765468e9a82400.m3u8" -y "C:\ProgramData\Jellyfin\Server\transcodes\fa9d01ef208b6d349a765468e9a82400%d.ts"


ffmpeg version N-95234-g35a63a9127 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.2.0 (Rev2, Built by MSYS2 project)
  configuration:  --disable-static --enable-shared --enable-amf --enable-bzlib --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-iconv --enable-lzma --enable-nvenc --enable-zlib --enable-sdl2 --enable-ffnvcodec --enable-nvdec --enable-gmp --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libdav1d --disable-debug --enable-fontconfig --enable-libass --enable-libbluray --enable-libfreetype --enable-libmfx --enable-libmysofa --enable-libopencore-amrnb --enable-libopenjpeg --enable-libsnappy --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libwavpack --enable-libwebp --enable-libxml2 --enable-libzimg --enable-libshine --enable-gpl --enable-libxvid --enable-libopenmpt --enable-version3 --enable-libsvtav1 --enable-librtmp --enable-gnutls --extra-cflags=-DLIBTWOLAME_STATIC --extra-libs=-lstdc++ --extra-cflags=-DLIBXML_STATIC --shlibdir=/local64/bin-video
  libavutil      56. 35.100 / 56. 35.100
  libavcodec     58. 59.101 / 58. 59.101
  libavformat    58. 33.100 / 58. 33.100
  libavdevice    58.  9.100 / 58.  9.100
  libavfilter     7. 62.100 /  7. 62.100
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
Unrecognized option 'vaapi_device'.
Error splitting the argument list: Option not found 
```

 

System:
- OS: Windows 10
 - Jellyfin Version: 10.5.2
 - Hardware settings & device:  VAAPI on Intel i5 7th gen
 - Reverse proxy: no

**Comment by nyanmisaka** [comment]
VAAPI is a video acceleration API **on Linux**, but obviously your platform is Windows. To use VAAPI HWA, please install Linux such as Ubuntu 18.04 LTS and refer to the guide to configure it.

https://jellyfin.org/docs/general/administration/hardware-acceleration.html

**Comment by flxlocle** [comment]
But even with hardware transcoding set to non, it can not stream MKV file, but after encode MKV file to MP4, MP4 version of the same file streams with no problem.

**Comment by nyanmisaka** [comment]
> But even with hardware transcoding set to non, it can not stream MKV file, but after encode MKV file to MP4, MP4 version of the same file streams with no problem.

Can I get the ffmpeg log that you failed to play when encoding with software?

**Comment by Artiume** [comment]
Firefox doesn't support mkv and Chrome pseudo supports mkv via tricking Chrome into thinking it's a webm file. When you converted the file, did you also convert the video codec?

**Comment by flxlocle** [comment]
> Firefox doesn't support mkv and Chrome pseudo supports mkv via tricking Chrome into thinking it's a webm file. When you converted the file, did you also convert the video codec? 

No, I did not convert the codec, it’s still h264 MPEG4 avc.

**Comment by flxlocle** [comment]
> > But even with hardware transcoding set to non, it can not stream MKV file, but after encode MKV file to MP4, MP4 version of the same file streams with no problem.
> 
> 
> 
> Can I get the ffmpeg log that you failed to play when encoding with software?


http://localhost:8096/videos/5c02bf73-ce53-b488-3a1f-43885d92f672/live.m3u8?DeviceId=TW96aWxsYS81LjAgKGlQaG9uZTsgQ1BVIGlQaG9uZSBPUyAxM18zXzEgbGlrZSBNYWMgT1MgWCkgQXBwbGVXZWJLaXQvNjA1LjEuMTUgKEtIVE1MLCBsaWtlIEdlY2tvKSBNb2JpbGUvMTVFMTQ4fDE1ODU0MTUwOTQzNTk1&MediaSourceId=5c02bf73ce53b4883a1f43885d92f672&VideoCodec=h264&AudioCodec=ac3,eac3,mp3,aac&VideoBitrate=139808000&AudioBitrate=192000&PlaySessionId=ffe7ba9e54a547f7bd5594dc678dd70a&api_key=b70ac6a71eed4b36a40a2aacd9a5748e&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=72e632760eff5c1c92129ff0a5e9f571&SegmentContainer=ts&MinSegments=2&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51&TranscodeReasons=ContainerNotSupported

{"Protocol":"File","Id":"5c02bf73ce53b4883a1f43885d92f672","Path":"C:\\Media\\Shows\\The.Legend.Of.Korra.S01-S04.1080p.BluRay.x264-AR\\The.Legend.Of.Korra.S02.1080p.BluRay.x264-TENEIGHTY\\The.Legend.Of.Korra.S02E01.1080p.BluRay.x264-TENEIGHTY.mkv","Type":"Default","Container":"mkv","Name":"The.Legend.Of.Korra.S02E01.1080p.BluRay.x264-TENEIGHTY","IsRemote":false,"ETag":"72e632760eff5c1c92129ff0a5e9f571","ReadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"RequiresClosing":false,"RequiresLooping":false,"SupportsProbing":true,"VideoType":"VideoFile","MediaStreams":[],"MediaAttachments":[],"Formats":[],"RequiredHttpHeaders":{}}

C:\Program Files\Jellyfin\Server\ffmpeg.exe -init_hw_device qsv=hw -filter_hw_device hw  -i file:"C:\Media\Shows\The.Legend.Of.Korra.S01-S04.1080p.BluRay.x264-AR\The.Legend.Of.Korra.S02.1080p.BluRay.x264-TENEIGHTY\The.Legend.Of.Korra.S02E01.1080p.BluRay.x264-TENEIGHTY.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -sn -codec:v:0 h264_qsv -preset 7 -look_ahead 0 -b:v 139808000 -maxrate 139808000 -bufsize 279616000 -profile:v high -level 4.1 -force_key_frames "expr:gte(t,n_forced*3)" -vf "format=nv12|qsv,hwupload=extra_hw_frames=64" -flags -global_header -vsync -1 -codec:a:0 ac3 -ac 2 -ab 192000  -f segment -max_delay 5000000 -avoid_negative_ts disabled -start_at_zero -segment_time 3  -individual_header_trailer 0 -segment_format mpegts -segment_list_entry_prefix "hls/2b7597483e1a1f6aafb6fba73abe263a/" -segment_list_type m3u8 -segment_start_number 0 -segment_list "C:\ProgramData\Jellyfin\Server\transcodes\2b7597483e1a1f6aafb6fba73abe263a.m3u8" -y "C:\ProgramData\Jellyfin\Server\transcodes\2b7597483e1a1f6aafb6fba73abe263a%d.ts"


ffmpeg version N-95234-g35a63a9127 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.2.0 (Rev2, Built by MSYS2 project)
  configuration:  --disable-static --enable-shared --enable-amf --enable-bzlib --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-iconv --enable-lzma --enable-nvenc --enable-zlib --enable-sdl2 --enable-ffnvcodec --enable-nvdec --enable-gmp --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libdav1d --disable-debug --enable-fontconfig --enable-libass --enable-libbluray --enable-libfreetype --enable-libmfx --enable-libmysofa --enable-libopencore-amrnb --enable-libopenjpeg --enable-libsnappy --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libwavpack --enable-libwebp --enable-libxml2 --enable-libzimg --enable-libshine --enable-gpl --enable-libxvid --enable-libopenmpt --enable-version3 --enable-libsvtav1 --enable-librtmp --enable-gnutls --extra-cflags=-DLIBTWOLAME_STATIC --extra-libs=-lstdc++ --extra-cflags=-DLIBXML_STATIC --shlibdir=/local64/bin-video
  libavutil      56. 35.100 / 56. 35.100
  libavcodec     58. 59.101 / 58. 59.101
  libavformat    58. 33.100 / 58. 33.100
  libavdevice    58.  9.100 / 58.  9.100
  libavfilter     7. 62.100 /  7. 62.100
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
[AVHWDeviceContext @ 0000023daf9c6740] Failed to create Direct3D device
Device creation failed: -1313558101.
Failed to set value 'qsv=hw' for option 'init_hw_device': Unknown error occurred
Error parsing global options: Unknown error occurred

**Comment by nyanmisaka** [comment]
> [AVHWDeviceContext @ 0000023daf9c6740] Failed to create Direct3D device
> Device creation failed: -1313558101.
> Failed to set value 'qsv=hw' for option 'init_hw_device': Unknown error occurred
> Error parsing global options: Unknown error occurred

Make sure your Intel Graphic driver is up to date and do not install Jellyfin as a Windows service when using QSV HWA. It does not currently support non-interactive interfaces or headless system.
