### ISSUE TITLE
Base URL bug in a fresh install v10.5.2 [FIXED]

### ISSUE THREAD

**Issue by castillo92** [jellyfin/jellyfin#2717]
**Describe the bug**
After normal installation, and following the official instruction, when I entered into jellybean instance, web page shows:

**System (please complete the following information):**
 - OS: Debian 10
 - Virtualization: No
 - Clients: Browser
 - Browser: Chrome 80.0.3987.149 (Build oficial) (64 bits)
 - Jellyfin Version: Jellyfin version: "10.5.2"
 - Playback: Not now
 - Installed Plugins: Anyone
 - Reverse Proxy: Aapache
 - Base URL: Fresh install, none modded
 - Networking: Host and NAT
 - Storage: Local, HDD mount

**To Reproduce**

I installed Jellyfin following instructions from https://jellyfin.org/downloads/
```
sudo apt install apt-transport-https
wget -O - https://repo.jellyfin.org/jellyfin_team.gpg.key | sudo apt-key add -
echo "deb [arch=$( dpkg --print-architecture )] https://repo.jellyfin.org/$( awk -F'=' '/^ID=/{ print $NF }' /etc/os-release ) $( awk -F'=' '/^VERSION_CODENAME=/{ print $NF }' /etc/os-release ) main" | sudo tee /etc/apt/sources.list.d/jellyfin.list
sudo apt update
sudo apt install jellyfin

sudo systemctl enable jellyfin.service
sudo systemctl start jellyfin.service
```

In the Web-server side:
First enabling modules (already enabled)
`sudo a2enmod proxy proxy_http ssl proxy_wstunnel
`
And made the modifications in the vHost of Apache:
I do not write here the HTTPS part
```
# Media Server Jellyfin
        ProxyPreserveHost On
        ProxyPass "/socket" "ws://127.0.0.1:8096/socket"
        ProxyPassReverse "/socket" "ws://127.0.0.1:8096/socket"

        ProxyPass "/jellyfin/" "http://127.0.0.1:8096/jellyfin/"
        ProxyPassReverse "/jellyfin/" "http://127.0.0.1:8096/jellyfin/"
        Redirect permanent /jellyfin /jellyfin/
```

**Expected behavior**
Entering in https://my_home.com/jellyfin/    I expected to see the "First run wizard" but only see a blank page showing in plain text: "**Unable to find the specified file.**"

And the URL change from
`https://my_home.com/jellyfin/web/index.html         ->        https://my_home.com/web/index.html`

This behavior made me think that the base url was wrong

**How I fixed it**
Changing base URL by CLI, following instruction of release 10.4.1 
https://github.com/jellyfin/jellyfin/releases/tag/v10.4.1

```
	sudo systemctl stop jellyfin
	sudo nano /etc/jellyfin/system.xml

<BaseUrl>                  ->                        <BaseUrl>/jellyfin</BaseUrl>

	sudo systemctl start jellyfin
	sudo systemctl status jellyfin
```

And my question is... It is a bug? Adding /jellyfin are not mandatory behavior since version 10.4?

Why my /etc/jellyfin/system.xml did not have the new BaseUrl line? It is a bug?

Thanks you very much for your efforts

**Comment by dkanada** [comment]
Correct, the base URL is no longer required.

**Comment by castillo92** [comment]
> Correct, the base URL is no longer required.

But, in the official docs to make a ProxyPass with Apache said the sub url /jellyfin

If the /etc/jellyfin/system.xml does not have the right base url, it does not work.

My problem is that base url by default is: /      and we have to change in /etc/jellyfin/system.xml to make Jellyfin works

**Comment by Artiume** [comment]
The default is /, until you change it inside the system settings, it's going to assume that it is located at /, if you wanted the baseUrl to be /jellyfin2/, how would it know?

**Comment by castillo92** [comment]
> The default is /, until you change it inside the system settings, it's going to assume that it is located at /, if you wanted the baseUrl to be /jellyfin2/, how would it know?

Thanks you, I thought the default base URL was /jellyfin because I read wrong the official documentation. My fault.

Thanks you and everyone the comments. I am going to close this issue, because now it is clear.
