### ISSUE TITLE
repo.jellyfin.org Offline (and v6 not accepting PING)

### ISSUE THREAD

**Issue by MadMakz** [jellyfin/jellyfin#272]
`Connecting to repo.jellyfin.org (repo.jellyfin.org)|172.81.180.233|:443... failed: Connection refused.`
`Connecting to repo.jellyfin.org (repo.jellyfin.org)|2602:ffb6:2:0:f816:3eff:fef9:65ca|:443... failed: Network is unreachable.`

I just wanted to make the switch from Emby to Jellyfin and above errors occured.

**Comment by bfayers** [comment]
https://old.reddit.com/r/jellyfin/comments/a9ftd1/jellyfin_statement_on_recent_code_changes/ecixuk7/

**Comment by nvllsvm** [comment]
Reopening - it's completely a valid issue.

**Comment by joshuaboniface** [comment]
Yup let's leave it open until we fix the issues and can get a fresh build.
