### ISSUE TITLE
Missing intel driver

### ISSUE THREAD

**Issue by leonardpitzu** [jellyfin/jellyfin#2724]
in order to do transcoding an Intel driver is needed. Currently the driver is missing from the docker image provided.

**System (please complete the following information):**
 - OS: Linux (Synology DSM)
 - Virtualization: Docker
 - Jellyfin Version: 10.5.2
 - Playback: Transcode

**To Reproduce**

1. just play a movie that needs transcoding - it will not work and in the logs ffmpeg will error out with code -134

**Expected behavior**
video playback should work flawless

**Additional context**
temporary solution:
`sudo docker exec --user root -it jellyfin sh -c 'echo "deb http://http.us.debian.org/debian stable main contrib non-free" | tee -a /etc/apt/sources.list && apt-get update && apt-get install -y i965-va-driver-shaders && vainfo'
`

**Comment by Shadowghost** [comment]
This is know and intentional since the driver is non-free and not compatible with GPL (so jellyfin can't redistribute it inside a prebuilt imager). Options about circumventing it are being discussed right now.

**Comment by JustAMan** [comment]
cc @nyanmisaka who is trying to overcome this

**Comment by nyanmisaka** [comment]
Hello there! Can you try this?
https://github.com/jellyfin/jellyfin/issues/2726#issuecomment-609046408

The jellyfin image created in this way will include a free Intel vaapi driver, and there will be no problem with transcoding anymore.

**Comment by leonardpitzu** [comment]
Seems ok with the above pull request. Testez on Synology NAS. Thanks!

**Comment by pizidehao** [comment]
![git](https://user-images.githubusercontent.com/7310863/79375046-962d7f80-7f8a-11ea-91bd-368929b0c43c.png)
Run your code it reports an error

**Comment by Artiume** [comment]
I believe this can be closed out
