### ISSUE TITLE
Can't install any plugins or update them

### ISSUE THREAD

**Issue by MohandL3G** [jellyfin/jellyfin#2748]
**Describe the bug**
I can't install any Plugins and I can't even update them, it always fail, I don't know why this happens.
I just want to install Trakt Plugin to keep track of what I've been watching, also I use a program called [MBCord](https://github.com/oonqt/MBCord), but it also [doesn't work](https://github.com/oonqt/MBCord/issues/5).
I also tried to install Trakt Plugin manually, it installed and I activated it, but it doesn't sync my library, it always fails.
I don't use any proxy and all other sites works will, even VPN doesn't work, changing to another Network and it's the same, but Jellyfin works on my old laptop, it's this laptop which Jellyfin doesn't work perfectly on.

**System**
 - OS: Windows 10 x64 (1909)
 - Virtualization: none
 - Clients: Browser
 - Browser: Chrome 80.0.3987.162
 - Jellyfin Version: 10.5.2
 - Playback: Direct Play
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: none
 - Networking: Host
 - Storage: local

**To Reproduce**
Click on "Scheduled Tasks"
Click on "Start" for "Update Plugins"

-------------------------------------------------

Click on "Plugins"
Select "Catalog"

**Expected behavior**
It should show me all Plugins when I go to Catalog, and update my Plugins.

**Logs**
[Jellyfin log.txt](https://github.com/jellyfin/jellyfin/files/4423988/Jellyfin.log.txt)

**Screenshots**
![Annotation 2020-04-03 001423](https://user-images.githubusercontent.com/31743237/78305127-7fc20580-7540-11ea-9f98-252739e2982a.jpg)

-------------------------------------------------

![Annotation 2020-04-03 001424](https://user-images.githubusercontent.com/31743237/78305231-aed87700-7540-11ea-895e-89e6401f25a0.jpg)

**Additional context**
My Laptop info:
[DxDiag.txt](https://github.com/jellyfin/jellyfin/files/4424053/DxDiag.txt)

**Comment by lelamamalgache** [comment]
#1623 Plugin Update/Uninstall is failing on Windows

**Comment by MohandL3G** [comment]
As I understand from this issue #1623 this isn't a network problem as I though, it has something to do with adminisrator on Windows, and that it can't access some dll files.
I noticed that Jellyfin is running under My Current Accout "MohandL3G" I used this [method](https://www.gabsoftware.com/tips/run-cmd-or-any-process-as-system-account-on-windows/) to run it as "SYSTEM", but this also didn't work.

I also wanted to delete Plugins folder under `C:\ProgramData\Jellyfin\Server\plugins\` and that might help me with this issue, but I don't have this folder.

**Comment by mark-monteiro** [comment]
@MohandL3G Can you access this URL normally from a browser (Chrome, Firefox etc.)? https://repo.jellyfin.org/releases/plugin/manifest.json

This is the URL the server loads when retrieving the list of plugins.

**Comment by MohandL3G** [comment]
@mark-monteiro Yes I can access it.

**Comment by JustAMan** [comment]
So this seems to be either .netcore issue or your machine setup issue. Maybe a firewall is blocking, or some program trying to intercept https traffic (MITM attack)? There certainly is no authentication on the repo, which the logs claim is the reason for failure.

**Comment by tophat17** [comment]
I'm having the same issue but on the docker version of jellyfin. Any fixes?

**Comment by crobibero** [comment]
> 
> 
> I'm having the same issue but on the docker version of jellyfin. Any fixes?

You're probably running into https://github.com/jellyfin/jellyfin/issues/4688

**Comment by MohandL3G** [comment]
> I'm having the same issue but on the docker version of jellyfin. Any fixes? 

I just tried everything for about a week or more, then I learned about Docker and start using it, and it just works on Docker for me.
