### ISSUE TITLE
Cant parse XMLTV data

### ISSUE THREAD

**Issue by bjorklund** [jellyfin/jellyfin#2750]
**Describe the bug**
I cant download XMLTV data. Got error in Jellyfin log file.

**System (please complete the following information):**
 - OS: Ubuntu 18.04
 - Jellyfin Version: 1.5.2.0 and 15.0.0

**To Reproduce**
1. Test XMLTV data from https://ppmtv.tvip.xyz/epg_temp_dl/output-epgs/sweden.xml
2. Check log file.

**Logs**
System.Xml.XmlException: Data at the root level is invalid. Line 1, position 1.

**Comment by JustAMan** [comment]
Please provide a little more of Jellyfin logs.
