### ISSUE TITLE
Update plugins failed

### ISSUE THREAD

**Issue by smidley** [jellyfin/jellyfin#2753]
On the latest version of JF  Server 10.5.2 running on windows server 2019.

Getting the following error:
Access to the path 'Jellyfin.Plugin.Reports.dll' is denied. at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel) at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive) at System.IO.Directory.Delete(String path, Boolean recursive) at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(PackageVersionInfo package, CancellationToken cancellationToken) at Emby.Server.Implementations.Updates.InstallationManager.InstallPackageInternal(PackageVersionInfo package, CancellationToken cancellationToken) at Emby.Server.Implementations.Updates.InstallationManager.InstallPackage(PackageVersionInfo package, CancellationToken cancellationToken) at Emby.Server.Implementations.ScheduledTasks.PluginUpdateTask.Execute(CancellationToken cancellationToken, IProgress`1 progress) at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)

**Comment by mark-monteiro** [comment]
This is a known existing issue on windows being tracked in #1623. There is a workaround here to uninstall plugins: https://github.com/jellyfin/jellyfin/issues/1623#issuecomment-538581937. Once a plugin is uninstalled you can install it again at the latest version to 'update' it.
