### ISSUE TITLE
Top-level "Folders" UserView empty when user missing "access to all libraries"

### ISSUE THREAD

**Issue by Aanok** [jellyfin/jellyfin#2754]
It seems Media Folders permission problems as reported by #1436 have not been solved completely.

**Describe the bug**
When a user's Access permissions do not "Enable access to all libraries" but selectively allow only some (or all) of them on an individual basis, the top Folder view is presented empty regardless of permissions.

This is an example configuration for a test case:

![Screenshot_2020-03-26 Jellyfin](https://user-images.githubusercontent.com/18417628/77637644-442ea680-6f56-11ea-9867-fd243002587a.png)
![Screenshot_2020-03-26 Jellyfin(2)](https://user-images.githubusercontent.com/18417628/77639615-4f370600-6f59-11ea-9d25-ccab7d78325f.png)

This is the response you get for an example query run with the above test user:
```
curl -i -H "x-emby-token: ${token}" "${server}/users/${userid}/items?parentid=${foldersviewid}"

HTTP/2 200 
server: nginx/1.14.2
date: Thu, 26 Mar 2020 10:42:32 GMT
content-type: application/json; charset=utf-8
content-length: 48
expires: 0
access-control-allow-headers: Accept, Accept-Language, Authorization, Cache-Control, Content-Disposition, Content-Encoding, Content-Language, Content-Length, Content-MD5, Content-Range, Content-Type, Date, Host, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Origin, OriginToken, Pragma, Range, Slug, Transfer-Encoding, Want-Digest, X-MediaBrowser-Token, X-Emby-Authorization
access-control-allow-methods: GET, POST, PUT, DELETE, PATCH, OPTIONS
access-control-allow-origin: *
strict-transport-security: max-age=63072000

{"Items":[],"TotalRecordCount":0,"StartIndex":0}
```

Of note: **Jellyfin correctly honours access permissions for individual items** (e.g. a TV show, a song or even a whole library), it is just the top Folders view that is inaccessible no matter what.

Of further note: trying to access a forbidden resource returns an empty list of items like above and an HTTP status code of 200. There should really be indication of what's happening with either a 403 status code or similar, or an error in the JSON itself.

**System:**
 - OS: Debian 9.12
 - Virtualization: None, installed from apt
 - Clients: All
 - Browser: Firefox 74
 - Jellyfin Version: 10.5.2
 - Installed Plugins: AudioDB 10.5.2.0, MusicBrainz 10.5.2.0, Open Subtitles 7.0.0.0
 - Reverse Proxy: nginx, but also on direct connection
 - Base URL: /jellyfin
 - Networking: Host
 - Storage: Local

**To Reproduce**
1. Configure a user with selective access to libraries, making sure the Folders view is enabled.
2. Try and access the Folders view.

**Expected behavior**
The user can access the Folders view.

**Logs**
```
[2020-03-26 11:43:02.893 +01:00] [WRN] "test_user" is not permitted to access Library "Folders".
```

**Comment by Aanok** [comment]
The bug is still present.

**Comment by dstar4138** [comment]
I believe this is still present. Same with the "Playlists" pseudo library.

**Comment by Aanok** [comment]
The bug is still present in 10.6.4.

**Comment by dstar4138** [comment]
bad bot.
