### ISSUE TITLE
Adding to m3u8 playlist in read only location 

### ISSUE THREAD

**Issue by SegiH** [jellyfin/jellyfin#2756]
**Describe the bug**
I have a music library set up on Jellyfin nightly on Debian Stretch. My music is on external storage that was read only (more on that later). In my Music directory, I have a directory called Playlists with all of my m3u8 playlists. 

When I try to add a song to an m3u8 playlist, there should be a check to see if the playlist location is even writable or not and immediately display a message if it isn't. 

What currently happens when you add a song to an m3u8 playlist that is located in a read only location is that as soon as you click on the Add button after selecting the playlist from the platlist dropdown,, you get a never ending spinning wheel that remains even if you navigate to a different view. Refreshing the page is the only way to get rid of it.

**System (please complete the following information):**
 - OS: Raspbian
 - Virtualization: no
 - Clients: Firefox, Android, Chrome, Edge (Just kidding I'd never use Edge)
 - Browser: Firefox 74
 - Jellyfin Version: Nightly
 - Playback: Direct Play
 - Installed Plugins: None
 - Reverse Proxy: Traefik
 - Base URL: None
 - Networking: N/A
 - Storage: External USB

**To Reproduce**
Assuming you have a library in Jellyfin that is mounted on a read-only location and your playlist is in your library.

1. Go to any song
2. Click on the plus to add to a playlist and select the playlist (selecting add to playlist from the 3 dot menu has the exact same effect)
3. Click on Add
4. You get a never ending spinning wheel as tries to add the song to the m3u8 and Jelllyfin appears to run slower.

**Expected behavior**
There should be an alert displayed along the lines of 

"Error: This library is a read-only location and the playlist cannot be updated" and terminate immediately. 

**Logs**
System.UnauthorizedAccessException: Access to the path '/mnt/external/Music/Play
lists/Guitar - Practice.m3u8' is denied.

**Screenshots**
None

**Additional context**
After enabling write access to my music library, Jellyfins' web UI seemed much more responsive. Clicking on the 3 dot menu or plus icon to add a song to a playlist responded much more quickly. I know that this is purely subjective for me but upgrading from 10.5.1 (which was causing Jellyfin to constantly crash for me) to nightly yesterday as well as making my library writable has made a very noticeable improvement in the WEB UI.

**Comment by JustAMan** [comment]
Please provide server logs when you try to update read-only library (also errors from web browser console [typically F12 opens that] are welcome).
