### ISSUE TITLE
Latest Section

### ISSUE THREAD

**Issue by Netsurve** [jellyfin/jellyfin#2759]
OS : Arch
DE : Kde
JELLYFIN : Version: 10.5.2

Is there a way to hide the latest section in the home folder , without marking all the videos watched

![screen](https://user-images.githubusercontent.com/63149132/78440204-9c109000-766f-11ea-9f2b-6d9d2aa7e8c8.png)

So I want to be able to have a collection of videos in folder 1 and have no other sections in the home folder, I want to control the videos within the folder i.e mark then watch or unwatched in the folder

**Comment by Artiume** [comment]
Profile > Home > Personalize each `Home screen section` to your liking.

That what you're looking for?

**Comment by Netsurve** [comment]
Thanks , sorry I search but missed the profile/home section
