### ISSUE TITLE
RAM Usage

### ISSUE THREAD

**Issue by vonAlenberg** [jellyfin/jellyfin#2760]
**Describe the bug**

`dotnet` process is using about 1.6GB RAM without any media playback happening.

**System:**
 - OS: Arch Linux LTS kernel
 - Virtualization: Docker via Docker-Compose
 - Clients: Android
 - Browser: FF 72.0.2
 - Installed Plugins: none
 - Reverse Proxy: Traefikv2
 - Networking: bridge
 - Storage: local

**Comment by telans** [comment]
Why is this a bug?

**Comment by vonAlenberg** [comment]
Because I'm sure you don't want to tell me Jellyfin uses double the RAM in idle state than my whole DE KDE...

**Comment by JustAMan** [comment]
How did you measure its RAM consumption?

**Comment by manzajaro** [comment]
Hi,

I want to ask a question.

When jellyfin has just started it consumes about 300MB RAM

![Captura3](https://user-images.githubusercontent.com/6926926/79967719-7bc63b00-848f-11ea-9eb7-a0a6cdf30122.PNG)

When it carry several hours, the consume increase to 2GB RAM.

![Captura](https://user-images.githubusercontent.com/6926926/79968416-5a198380-8490-11ea-9c84-e7bcc5b58b83.PNG)

Capture time is 11:00, you can see last log is 10.31

![Captura2](https://user-images.githubusercontent.com/6926926/79968454-68679f80-8490-11ea-9fc2-83dd22379dda.PNG)

It is not an excessive consumption to not be doing anything?

**Comment by JustAMan** [comment]
so I wonder if it might be some sessions or websockets leaking... something we try to prevent in a new PR by @OancaAndrei

**Comment by OancaAndrei** [comment]
I noticed those `WebSocketException`s as well, they seem to happen when a browser is closed and it isn't given the time to properly close the connection. On Chrome mobile this happens quite often, even when simply putting the app in background. Jellyfin doesn't seem to like that.

This exception does indeed hint toward the websockets leaking.

**Comment by OancaAndrei** [comment]
#2162 seems to fix the "websockets leaking" issue already.

**Comment by manzajaro** [comment]
Thanks @OancaAndrei.

I will try it in the next release :) , I will comment  on the results

**Comment by ddonindia** [comment]
this should be reopened

**Comment by cvium** [comment]
Based on what?
