### ISSUE TITLE
Can't skip ahead or resume on jellyfin Android app.

### ISSUE THREAD

**Issue by bnichs5** [jellyfin/jellyfin#2761]
I am unable to skip ahead, rewind, or resume on the Android app. If I try to do any of that, it just restarts the movie that I'm watching. I've tried it for multiple movies of different formats. Most common format is .mp4 it is coming from an .strm file though. I disabled all transcoding and only allow directplay and directstream.

Works just fine from any web browser including chrome mobile. 

I am running jellyfin nightly 10.5.0 server on windows 10. And client wise is Android Pie on my phone, Nvidia shield tv, and a 4k firetv stick. 

Installed plugin is playback reporting. I tried reports plugin but that caused jellyfin to not even start up so I removed it.

Logs can be found at pastebin.com/nMj6z2CU

This has been a problem on all versions of jellyfin for me starting from over a year ago. Let me know if you need more info. Thanks for all your hard work!

**Comment by Artiume** [comment]
This is tracked under this ticket https://github.com/jellyfin/jellyfin-web/issues/899
