### ISSUE TITLE
Fresh Jellyfin docker install. Works 100% but log shows error every second

### ISSUE THREAD

**Issue by zilexa** [jellyfin/jellyfin#2763]
**Describe the bug**
The log shows the following error, although I deleted the container, the mounted volumes, the image and installed the docker image fresh. Fresh configuration of Jellyfin.  Everything works as expected. But this error is shown constantly (before I installed plugins)
```
[2020-04-04 23:03:52.848 +02:00] [ERR] [26] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Access token is invalid or expired."
```

**System (please complete the following information):**
 - OS: Ubuntu Budgie 19.10
 - Virtualization: Docker
 - Clients: Vero4K (Kodi Native Mode, NFS mounts), Android
 - Browser: Firefox 74
 - Jellyfin Version: latest
 - Playback: Direct Play 
 - Installed Plugins: Kodi Sync Queue, Trakt 
 - Reverse Proxy: none
 - Base URL: no just IP:port, I only play on my LAN, not remotely
 - Networking: [e.g. Host, Bridge/NAT]
 - Storage: all is stored on the same hostPC Jellyfin Docker is running on. Kodi client native mode (NFS mount)

**Expected behavior**
No error in the log. 

**Logs**
```
[2020-04-04 23:03:52.848 +02:00] [ERR] [26] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Access token is invalid or expired."
```

**Comment by Bond-009** [comment]
Have you cleared your browser cache?

**Comment by zilexa** [comment]
> Have you cleared your browser cache?
That solved it thanks.
