### ISSUE TITLE
Same foldername on different path will be marked as duplicate

### ISSUE THREAD

**Issue by ryperx** [jellyfin/jellyfin#2764]
**Describe the bug**
I have for example 2 series folders, on in the main path /series and an additional in a other libaray /test/series
The sub folder doesnt get scanned and in the log i see duplicate path message/error

**To Reproduce**
As described, create a folder and a additional folder with same name but other location. 
I then used these 2 folder in different librarys and the sub folder will be marked as duplicate

example: 
/series
/test/series

Folder /test/series will be marked as duplicate
I tried 3 times to create a new config, every time with same result.

**Expected behavior**
Shouldnt be marked as duplicate

**System (please complete the following information):**
 - OS: Docker
 - Browser: Firefox
 - Jellyfin Version: 10.5.2

**Additional context**
Problem was resolved in the moment i renamed one folder different example /test/series1 would be enough.

**Comment by JustAMan** [comment]
Could you please post the server logs here? Just saying what you see there is not enough for us to root-cause the issue.

**Comment by ryperx** [comment]
Mmh, i try now out to reproduce the problem but cant with my working installation.
Will try the next day a new docker and try it out.
