### ISSUE TITLE
Problem with string on Scheduled Actions page

### ISSUE THREAD

**Issue by Boki40** [jellyfin/jellyfin#2766]
![image](https://user-images.githubusercontent.com/59022978/78470188-bd34b780-7727-11ea-9a29-e734dc1f6dcd.png)

It is not possible to translate it right. In Hungarian it looks like Last ran: 3 minutes ago, taking 9 **minutes ago**

the date format is not part of the Webplate platrofm, its a built in timestamp or something (I'm not an expert).

**Comment by ZadenRB** [comment]
I can confirm that this isn't a translation issue, as it says the same in English:
<img width="1904" alt="Screen Shot 2020-04-07 at 11 34 06 AM" src="https://user-images.githubusercontent.com/20938000/78701253-f43fd000-78c3-11ea-93a4-faa5773c390b.png">
