### ISSUE TITLE
HTTP Slow Connection error in Log while using https only?

### ISSUE THREAD

**Issue by ryperx** [jellyfin/jellyfin#2770]
**Describe the bug**
Hey people,

i use jellyfin docker with an traefik proxy and with https (example https://sub.domain.com/)

I see this error many times in my log and i have the feeling the server isnt runny really snappy.

[17:38:05] [WRN] [81] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to 172.16.0.1. Time (slow): 0:00:00.5914128. http://sub.domain.com/Items/123123/Images/Primary?maxHeight=600&maxWidth=400&tag=12312312cad&quality=90

What is me confusing me, in the log i see the http url and this url cant work because i have only https configured to work. (http port disable in traefik and on router)
Is this causing the error or is this another problem. The 172.16.0.1 is the IP of my local router.

I set in the jellyfin config the secure connection to "proxy is handling this", but still why there is http in the log? Could it be possible it is necessary to tell jellyfin to redirect to https?

I have this idea, because for nextcloud i need to set an additional setting in the config.php

'overwriteprotocol' => 'https'

Can i ignore this error completly or is this a problem?

**System (please complete the following information):**
 - OS: Linux
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Firefox
 - Jellyfin Version: 10.5.2

 - Reverse Proxy:Traefik 2.2

**Logs**

**Additional context**

**Comment by JustAMan** [comment]
What is the protocol which your reverse proxy is using to talk to Jellyfin? My guess is it's plain http, that's what JF is receiving. If so, that log line is perfectly fine (as long as you completely block http port on your router, in terms of security).

**Comment by ryperx** [comment]
Yes you are right, traefik is talking with jellyfin with the http port. The problem is the http port is completly blocked on my router. 
Wouldnt this be a problem when jelllyfin is trying to connect over http/port 80 what is blocked?
For example in nextcloud it was a must to define a rule that nextcloud is doing the correct redirect to https else it wasnt working fine, only really slowly.
Wouldnt this not the exact same problem with jellyfin? When Jellyfin is trying to redirect the client to http which isnt working because blocked on router.

**Comment by JustAMan** [comment]
This is fine. You as a client is talking to traefik over https, and traefik is talking to JF over http.
All working as intended. JF won't try to redirect you to http port.
