### ISSUE TITLE
Wrong FFmpeg path on Docker ARM image

### ISSUE THREAD

**Issue by NullEnt1ty** [jellyfin/jellyfin#2778]
**Describe the bug**
The Docker ARM (32-bit) image seems to use a wrong path for FFmpeg. Jellyfin is started with the argument `--ffmpeg /usr/lib/jellyfin-ffmpeg` which points to a directory that **contains** the FFmpeg binary. Therefore, the correct path should be: `/usr/lib/jellyfin-ffmpeg/ffmpeg`

**System (please complete the following information):**
 - OS: Raspbian Buster
 - Virtualization: Docker 19.03.8
 - Clients: Browser, Kodi
 - Browser: Firefox 74
 - Jellyfin Version: 10.5.3
 - Playback: Direct Play
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: none
 - Networking: Host
 - Storage: local

**To Reproduce**
1. Run `docker run jellyfin/jellyfin:10.5.3` on a 32-bit ARM device
2. Look for the log entry
    > [WRN] [4] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: SetByArgument: File not found: /usr/lib/jellyfin-ffmpeg

**Expected behavior**
FFmpeg to be found by Jellyfin

**Logs**
> [WRN] [4] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: SetByArgument: File not found: /usr/lib/jellyfin-ffmpeg

**Additional context**
I think the bug was introduced with this PR: https://github.com/jellyfin/jellyfin/pull/2499

**Comment by nyanmisaka** [comment]
https://github.com/jellyfin/jellyfin/blob/master/Dockerfile.arm#L77
```
    "--ffmpeg", "/usr/lib/jellyfin-ffmpeg/ffmpeg"]
```
