### ISSUE TITLE
SSA subtitles produce a playback error

### ISSUE THREAD

**Issue by PoepiePeppie** [jellyfin/jellyfin#2781]
Whenever I play a file that has internal MKV subtitles Jellyfin will give me a playback error saying "there was an issue with the client profiling and the server isn't sending a compatible media format"
After troubleshooting a bit in the matrix channel we found out octopus.js is producing an error when trying to look for subtitles.
![image](https://user-images.githubusercontent.com/29727357/78513471-32e26700-77ac-11ea-8dae-e1b4d13ecb1e.png)

 **steps to reproduce the behavior: **
1. use 10.5.3
2. open up a file with internal subtitles in SSA format
3. It gives the playback error.

**Expected behavior**
It plays files with SSA subtitling.

**Logs**
Direct stream log
[https://pastebin.com/qm78Rz4i](https://pastebin.com/qm78Rz4i)
transcode log
[https://pastebin.com/9EZ2BEPM](https://pastebin.com/9EZ2BEPM)

**Screenshots**
![image](https://user-images.githubusercontent.com/29727357/78513471-32e26700-77ac-11ea-8dae-e1b4d13ecb1e.png)

**System:**

    

- OS: Debian
- Virtualization: None
- Played on browser
- Browser: Firefox 74.1
- Jellyfin Version: 10.5.3
- Playback: Direct Play/Transcoding
- Installed Plugins: OpenSubtitles
- Reverse Proxy: Apache
- Base URL: /jellyfin
- Storage: Local

**Comment by ItsPaulHawkins** [comment]
Having the same issue, how did you roll back to 10.5.2? I understand that you can do that pretty easily on Docker, but I don't have Docker atm. I'm running proxmox with Ubuntu Server installed.  Is it possible to roll back without losing metadata / user data?
