### ISSUE TITLE
Hardware aceleration Exynos V4L2 MFC get's stuck - Odroid HC2

### ISSUE THREAD

**Issue by IvanpAEG** [jellyfin/jellyfin#2789]
**Media Info of the file**
![imagen](https://user-images.githubusercontent.com/34457043/78588490-0a577d00-783f-11ea-885e-0f245901413d.png)

**FFmpeg Logs**
FFmpeg version: ffmpeg version 4.2.1 (docker inside)
[ffmpeg-transcode-a57a65a9-7452-4dd8-baaa-9b99d72933d3.txt](https://github.com/jellyfin/jellyfin/files/4439975/ffmpeg-transcode-a57a65a9-7452-4dd8-baaa-9b99d72933d3.txt)

**Server System (please complete the following information):**
Hardware: Odroid-HC2
OS: Linux debian stretch 9,12 (kernel 4.14.150-odroidxu4)
Jellyfin version: 10.5.3 (docker arm)
Reverse proxy: nginx
Other hardware notes: Media mounted from Google Drive using Rclone
 
**Client System (please complete the following information):**
 - Device: PC / Xiaomi Box S / Fire TV
 - OS: Android, Windows
 - Client: Web/Browser, Android TV, Fire TV
 - Browser (if Web client): Firefox
 - Client and Browser Version: Firefox 74.0.1 (64-bit)

Hi, as described before I'm using recent jellyfin docer (10.5.3) and Exynos v4l2m2m hardware aceleration. 

I'm getting stuck here with this media file:

`[h264_v4l2m2m @ 0x1af79a0] driver 's5p-mfc' on card 's5p-mfc-enc'
[h264_v4l2m2m @ 0x1af79a0] Using device /dev/video11
[h264_v4l2m2m @ 0x1af79a0] driver 's5p-mfc' on card 's5p-mfc-enc'
[h264_v4l2m2m @ 0x1af79a0] h264 profile not found
[h264_v4l2m2m @ 0x1af79a0] Encoder adjusted: qmin (0), qmax (51)`

If I try v4l2m2m encoding with other files it's work but with this show tv it's get stuck.

**Comment by nyanmisaka** [comment]
It seems that the format of this video is h264 high10, which is a non-standard format that is not supported by the hardware. We may need to avoid using V4L2 hardware encoding in this particular situation.

```
Stream #0:1(jpn): Video: h264 (High 10), yuv420p10le(tv, bt709/unknown/unknown, progressive)

[h264_v4l2m2m @ 0x1af79a0] h264 profile not found
```
