### ISSUE TITLE
Jellyfin forum

### ISSUE THREAD

**Issue by joshuaboniface** [jellyfin/jellyfin#28]
As mentioned in #3 a forum might be a good idea, to have a more stable place to discuss than the chat long-term. I can spin up something basic to get going, but feedback welcome before I do.

**Comment by joshuaboniface** [comment]
Stable meaning "messages don't dispensary into the scrollback ether in a few hours".

**Comment by anthonylavado** [comment]
Discourse is great forum software.

**Comment by joshuaboniface** [comment]
The subreddit is probably a good place to start: https://reddit.com/r/jellyfin/

I'll close this out and revisit if we get requests for this.

**Comment by PrplHaz4** [comment]
Info that shouldn't disappear should be wiki'd....medium term info, reddit should work, and short term riot is good...if we only have 3 places we need to check, we're in good shape.

**Comment by joshuaboniface** [comment]
Yup those 3 seem like a good mix.
