### ISSUE TITLE
[bug] Client Profiling in Web Browser

### ISSUE THREAD

**Issue by NolanWelser** [jellyfin/jellyfin#2803]
**How I Installed Jellyfin**
Upgraded from 10.4.3 at each step up to 10.5.3

**Platform and OS**
Windows 10
Jellyfin Installer (not portable)

**Jellyfin Log**
[jellyfin log.txt](https://github.com/jellyfin/jellyfin/files/4447870/jellyfin.log.txt)

**ffmpeg logs**
ffmpeg generated three different log files between hitting play, getting the error popup, and then going to the logs dashboard page.
[ffmpeg log 1.txt](https://github.com/jellyfin/jellyfin/files/4447876/ffmpeg.log.1.txt)
[ffmpeg log 2.txt](https://github.com/jellyfin/jellyfin/files/4447877/ffmpeg.log.2.txt)
[ffmpeg log 3.txt](https://github.com/jellyfin/jellyfin/files/4447878/ffmpeg.log.3.txt)

**Screenshot**
![Screenshot from 2020-04-07 21-54-50](https://user-images.githubusercontent.com/1728348/78737553-c7200b80-791d-11ea-8d52-c7539af2d716.png)

**Description of Problem**
I'm not sure exactly which server version started this problem, but I know for a fact it was present on 10.5.2 and is still present on 10.5.3. From what I can gather from reading the logs, Jellyfin no longer knows what my client is (Firefox, Linux) and changing browser to Chromium also does not help. Anything that direct plays works (Kodi, MPV) and the FireTV and Android apps are still recognized client profiles and will transcode correctly.

**Comment by apcrcom** [comment]
Same issue here.

**Comment by rmoe88** [comment]
New user to jellyfin (big fan of the project), and I have this exact error.  I'm running jellyfin on debian headless server, and the client is either emby client on roku or ios safari.  Only some media does it.  Just wanted to bump it so it was more visible as to being an issue.

**Comment by Bond-009** [comment]
This looks like a web issue, @dkanada @MrTimscampi ?

**Comment by MrTimscampi** [comment]
@Bond-009 Seems like it's not happening only on web (See the comment from @rmoe88 about Roku)

Not sure where that could come from, since it only seems to happen on some files.

**Comment by JustAMan** [comment]
@NolanWelser can you check if it happens without HW acceleration?
@nyanmisaka can you look at it, seems it's AMF acceleration, can it be related?
@rmoe88 got server/ffmpeg logs? The fact that you're seeing same client error message doesn't mean the error is the same.

**Comment by dkanada** [comment]
Yeah, the first step for transcode issues should always be to disable the hardware acceleration.

**Comment by nyanmisaka** [comment]
> @nyanmisaka can you look at it, seems it's AMF acceleration, can it be related?

The AMF HWA looks normal and has produced 49 HLS slices, and then exits with the normal return value of 0.
```
[hls @ 000001fcfd256800] Opening 'C:\ProgramData\Jellyfin\Server\transcoding-temp\08c58eb01dc7946153dc890d849fc2b10.ts' for writing
. . .
[hls @ 000001fcfd256800] Opening 'C:\ProgramData\Jellyfin\Server\transcoding-temp\08c58eb01dc7946153dc890d849fc2b148.ts' for writing
frame= 3488 fps= 55 q=-0.0 Lsize=N/A time=00:02:25.59 bitrate=N/A speed=2.31x    
```

`[2020-04-07 21:55:52.079 -04:00] [INF] [24] App: FFMpeg exited with code 0`

**Comment by NolanWelser** [comment]
@JustAMan @nyanmisaka I can confirm turning off HWA doesn't change anything

**Comment by JustAMan** [comment]
Okay, please gather logs from browser console (F12 typically brings it up) from the moment you open up video page through clicking "Play" and up until it errors out.

**Comment by NolanWelser** [comment]
[firefox log.txt](https://github.com/jellyfin/jellyfin/files/4483995/firefox.log.txt)

**Comment by JustAMan** [comment]
I would say it has something to do with CORS settings.
Relevant errors are:
```
Content Security Policy: The page’s settings blocked the loading of a resource at wss://jellyfin.iseven77.com/socket?api_key=723283ce53d841fa82dbd29d7b72ef50&deviceId=TW96aWxsYS81LjAgKFgxMTsgVWJ1bnR1OyBMaW51eCB4ODZfNjQ7IHJ2OjczLjApIEdlY2tvLzIwMTAwMTAxIEZpcmVmb3gvNzMuMHwxNTgyODQyMTkzNjUy (“default-src”). apiclientcore.js:372:24
```

and

```
Content Security Policy: The page’s settings blocked the loading of a resource at blob:https://jellyfin.iseven77.com/e1efa1cd-fe5f-4732-96fb-2fdae195f36a (“worker-src”).
```

Do note that the second one is actually the bit of HLS being delivered to your browser. Do you have a reverse proxy set up?

**Comment by NolanWelser** [comment]
I am using nginx, and I noticed those as I posted the log but my config appears to be the same as the example shown in the docs, but I will review it again

**Comment by NolanWelser** [comment]
Problem solved! I removed what I had for these two lines and copy pasted them from the docs:
`add_header Strict-Transport-Security "max-age=31536000" always;`
and
`add_header Content-Security-Policy "default-src https: data: blob:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' https://www.gstatic.com/cv/js/sender/v1/cast_sender.js; worker-src 'self' blob:; connect-src 'self'; object-src 'none'; frame-ancestors 'self'";`
and added "/socket" on the proxy_pass setting for the /socket location, which I apparently forgot when creating the config, but functioned up until this point.
