### ISSUE TITLE
Strange behavior with "various artist" tag

### ISSUE THREAD

**Issue by emaen** [jellyfin/jellyfin#2806]
**Describe the bug**
I've some music albums with 'albumartist' tag tagged as "various artist".
In jeffyfin, they appear in a "Various Artist" key.

First Issue : 
 - In the 'Various Artits' key there is only one "Albums" key that take as titlte, the first album title encountered by jellyfin.

Second Issue : 
- When enter in this 'Albums' key, ALL tracks are listed under each other regardless existing album structure. Albums are ignored. Tracks are listed as non-album tracks, but they ARE album tracks.

**System (please complete the following information):**
 - OS: Windows 7
 - Virtualization: No
 - Clients: Browser  and Android app
 - Browser: Firefox 74.0 & Android app
 - Jellyfin Version: 10.5.2 portable. (zip file, not the one for .net)
 - Playback: Just navigate in the interface.
 - Installed Plugins: None.
 - Reverse Proxy: None.
 - Base URL: ?!?!?
 - Networking: localhost:8096
 - Storage: Hard disk on PC, where the browser is installed. Android App access local network by wifi

**To Reproduce**
- Have some albums music with 'albumartist' tag tagged as 'Various Artist'
- Navigate the interface to 'Various Artist' key.

**Expected behavior**
Having tracks listed in their own Album structure.

**Screenshots**
![image](https://user-images.githubusercontent.com/29975718/78781508-ad73d800-79a0-11ea-9342-f6a2937286c8.png)
![jellyfin2](https://user-images.githubusercontent.com/29975718/79387129-6d49c200-7f6b-11ea-8df8-2fb042ceaa90.jpg)

**Comment by doctorlard** [comment]
I get this too; I have an "Assassin's Creed Soundtrack" album by "Various Artists" that contains 1,000 tracks from all the other Various Artists albums on disk. I have Jellyfin 10.5.2 on Ubuntu 18.04 (installed from repo.jellyfin.org). At this point, in mid-post, I notice that apt can update to 10.5.4 so I'll try that... nope, no change (although, I would probably have to remove and re-index the folder, which I didn't do)

**Comment by emaen** [comment]
Yes, I confirm this issue is still affects me with latest release ( v 10.6.2 ) with windows 10.

**Comment by YR-ZR0** [comment]
Can confirm also that this issue is still present running version 10.6.3. For context the audio organization tool beets (https://github.com/beetbox/beets) will put songs that are not tied to a album in a "Non-Album" folder with the following structure Non-Album/[Artist name]/[song].mp3, This structure causes the same issue as first mentioned in April.

**Comment by NotSoCheezyTech** [comment]
Still here on 10.6.4
