### ISSUE TITLE
Having trouble with VAAPI on HEVC files

### ISSUE THREAD

**Issue by Vitorvlv** [jellyfin/jellyfin#2807]
Hey guys, I'm at loss on how to fix this, I was hoping [this](https://github.com/jellyfin/jellyfin/pull/2503) would solve it but since it didn't I now believe the issue might be on my end and would like some help troubleshooting it if possible.

The web client throws me this: "There was an issue with the client profiling and the server isn't sending a compatible media format."

And I've attached jellyfin and ffmpeg logs. 

OS: Manjaro
Jellyfin version: 10.5.3
Browser: Firefox 75.0
Mesa version: 20.0.4

[jf ffmpeg log](https://github.com/jellyfin/jellyfin/files/4450614/jf.ffmpeg.log)
[jf log](https://github.com/jellyfin/jellyfin/files/4450615/jf.log)

**Comment by nyanmisaka** [comment]
`[Parsed_scale_vaapi_2 @ 0x557c19ff49c0] Failed to render parameter buffer: 6 (invalid VASurfaceID).`

I guess you are probably using an AMD GPU. This problem will be solved in mesa 20.1, it affects AMD GPU can not decode HEVC video.

I talked about this before in #2503. You can also try to build one manually, which is how I solved it for my AMD GPU.

**Comment by Vitorvlv** [comment]
I missed that, sorry.

Thanks for helping!
