### ISSUE TITLE
Unable to playback TV Show libraries

### ISSUE THREAD

**Issue by DonnerPartyOfOne** [jellyfin/jellyfin#281]
Adding any folder as the "TV Shows" content type results in all playback attempts from the web GUI and Android Emby app returning:

"No compatible streams are currently available. Please try again later or contact your system administrator for details."

Adding the exact same folder as the "Movies" content type results in correct playback (with other bug-related caveats.) But, of course, the organization is wrong.

Logs show nothing interesting - no errors or warnings, just the GET/POST for UI stuff.

**Comment by Mountaineer1024** [comment]
#1013 
I resolved this issue by resetting all chrome flags to defaults in chrome://flags

Worth a shot if you are having this problem in Chrome.

**Comment by anthonylavado** [comment]
Does this still happen for anyone on the latest version (10.2.2)?

Thanks!

**Comment by DonnerPartyOfOne** [comment]
Sorry for not keeping up with this, I wasn't using a media server for a while. I tested again a few days ago and this bug seems to be fixed.
