### ISSUE TITLE
Nightly Docker builds missing?

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [jellyfin/jellyfin#2811]
There hasn't seem to have been any builds to the ``nightly`` tag in a few days, meanwhile all the other nightly builds all working.

**Comment by gardner** [comment]
It looks like build is failing after this: https://github.com/jellyfin/jellyfin/commit/be538d427787bfd167489745961a734c4d3abc7f
or maybe this: https://github.com/jellyfin/jellyfin/commit/838b20a2d7b2b245410ef58539721554d687d53b

You can see more info here: https://dev.azure.com/jellyfin-project/jellyfin/_build?definitionId=1&repositoryFilter=1&branchFilter=2

**Comment by fengapappit** [comment]
Last nightly build pushed to dockerhub was a month ago.

There are stable releases dating a week.

I think that the concept of nightly is not really working since a while :-|

**Comment by dkanada** [comment]
Nightlies are working for Ubuntu and Debian, we just have trouble with Docker right now. The build process is going through some growing pains at the moment.
