### ISSUE TITLE
Music Library not completely indexing in 10.5.3

### ISSUE THREAD

**Issue by daves00** [jellyfin/jellyfin#2815]
My media library was indexed completely in an earlier version of JellyFin (version unknown)
Since upgrading to 10.5.3 large parts of my music library are missing from the index, as exhibited when i search by either artist, album, or use the A-Z index

**** I have just tried down-grading back to 10.4.x, and this also has the same behaviour ****

**System (please complete the following information):**
 - OS:  Ubuntu 18.4.04 LTS (Bionic)
 - Virtualization: None
 - Clients: Browser
 - Browser: Firefox 74.01
 - Jellyfin Version: 10.5.3
 - Playback: DLNA to a HiFi Streamer
 - Installed Plugins: None
 - Reverse Proxy: None
 - Base URL: Default
 - Networking: Simple home LAN
 - Storage: Local software RAID

**To Reproduce**
Carry out a search by artist or by album

**Expected behavior**
More albums to be shown as search results. Interesting in recently played there are missing albums shown, but when clicking on the albums there are no tracks shown

**Logs**
No related errors or warnings shown when removed and re-added Music library.

Only errors shown below (IP address deliberately obscured by me)

[2020-04-09 06:52:25.567 +01:00] [INF] ExecuteQueuedTasks
[2020-04-09 06:52:25.628 +01:00] [ERR] Error in Directory watcher for: "/mnt/mediastore/music"
System.IO.IOException: The configured user limit (8192) on the number of inotify watches has been reached, or the operating system failed to allocate a required resource.
[2020-04-09 06:52:25.628 +01:00] [ERR] Error in Directory watcher for: "/mnt/mediastore/videos"
System.IO.IOException: The configured user limit (8192) on the number of inotify watches has been reached, or the operating system failed to allocate a required resource.
[2020-04-09 06:52:25.629 +01:00] [INF] Stopping directory watching for path "/mnt/mediastore/videos"
[2020-04-09 06:52:25.629 +01:00] [INF] Stopping directory watching for path "/mnt/mediastore/music"
[2020-04-09 06:52:25.630 +01:00] [INF] Watching directory /mnt/mediastore/videos
[2020-04-09 06:52:25.656 +01:00] [INF] Watching directory /mnt/mediastore/music
[2020-04-09 07:07:04.408 +01:00] [INF] WS "http://xxx.xxx.xxx.xxx:8096/socket?api_key=b1e101d58f0f4dd7b919bb1ee829e837&deviceId=TW96aWxsYS81LjAgKEFuZHJvaWQgNy4wOyBUYWJsZXQ7IHJ2OjY3LjApIEdlY2tvLzY3LjAgRmlyZWZveC82Ny4wfDE1NjEzMzI1NTkxNTA1". UserAgent: "Mozilla/5.0 (Android 7.0; Tablet; rv:68.0) Gecko/68.0 Firefox/68.0"

**Screenshots**

**Additional context**

**Comment by daves00** [comment]
It would be very helpful to have either a logging mode that will output all folders scanned successfully,
or (probably more difficult ...) to have a stand alone utility that would scan and output the folders scanned plus any code exceptions that occur during the scanning.

If the scanning is done in smallish number of classes please highlight the class names to me and I might get a chance to review and work out how best to diagnose the issue.

Thanks

**Comment by Artiume** [comment]
[2020-04-09 06:52:25.628 +01:00] [ERR] Error in Directory watcher for: "/mnt/mediastore/music"
System.IO.IOException: The configured user limit (8192) on the number of inotify watches has been reached, or the operating system failed to allocate a required resource.

https://en.wikipedia.org/wiki/Inotify

run this

`echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`

**Comment by daves00** [comment]
Thank you - This has certainly improved matters!!

I still have something in the media library that is causing problems - I have about 4 errors being thrown:

Error in "ffprobe"
System.Exception: ffprobe failed - streams and format are both null.

This seems to stop the library scan completing successfully.
I've looked at the SQLite database holding the library, and can see albums showing in the database table that are not showing via the UI/search

My thinking regards the best way of resolving this is to totally wipe the music items from the library.
I am proficient with SQL, however having looked at the schema it does not look trivial to do this - so two possibilities

1. Do any of the dev's working on JF have a utility to wipe a library at the DB level
2. I move all the music items out of the library so JF deletes the DB entries, and then move them back as this is fairly close to a rebuild of the music library

3. I considered renaming the folder containing the music files, however this will impact Samba shares I have setup, and likely to cause more problems with Samba which has proved "troublesome" in the past

Any advice gratefully recevied

**Comment by Artiume** [comment]
If you delete the library, it should purge it from the Db. I'm not proficient at SQL so any enlightening there would be helpful for me as well ^.^ 

>Error in "ffprobe"
System.Exception: ffprobe failed - streams and format are both null.

Could it be a permissions issue? Are you directly reading stuff from the Samba share or are you using a wrapper such as MergerFS around it? I highly recommend it for networked shares.

**Comment by daves00** [comment]
There seems to be some "feature" that doesn't delete the db rows for  library dropped - they seem to be held and then re-used when the library is added - one of the WS service calls parameters isNew for the library. The Smba is external to this issue, as the music library is a locally mounted raid array (raid 1) - the Samba share is to support pseudo DLNA devices (Sonos Play 1 - original version). 

I will look into MergeFS - thank you. 

If i move the music album folder out AND delete the artist folder then this seems to flush the database issues (deletes the rows for that artist) , which I feel are backwards compatibility related. I can then move, recreate the artist folder, and move the album folders back into the library and everything then works well (now inotify limits increased) - but i have a lot ... of artist folders
