### ISSUE TITLE
Emby.Server.Implementations.HttpServer.HttpListenerHost

### ISSUE THREAD

**Issue by arajooj** [jellyfin/jellyfin#2818]
**Describe the bug**
My jellyfin, when idle, will always appear the same error message (image attached).

"
[00:03:44] [ERR] [17] Emby.Server.Implementations.HttpServer.HttpListenerHost: Could not find handler for / socket
[00:03:44] [ERR] [17] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: Unable to find the specified file.
"

**System (please complete the following information):**
 - OS: Windows 10 x64
 - Clients: Browser, Android
 - Browser: Chrome 80
 - Jellyfin Version: 10.5.3
 - Playback: [Direct Play, Remux, Direct Stream, Transcode] 
 - Installed Plugins: Anime
 - Reverse Proxy: nginx
 - Storage: local, and cloud]

**Screenshots**
![image](https://user-images.githubusercontent.com/37886774/78958620-fd48c100-7abe-11ea-9d10-9171df1418b0.png)

I wonder if it is something I should be concerned about?

**Comment by Artiume** [comment]
Could you bypass nginx and see if it's related to your proxy?

**Comment by arajooj** [comment]
You are right, I entered the jelly by the local address, and not that "socket" message, when I enter through the reverse proxy ... it gives the error.

Error consists of, the jelly console trying to use a page called _"/socket"._
When at the local address:         http://localhost:42020/socket **(OK)**
When at the external address:   https://mydomain.com/socket **(FAIL)**

What can be happening? my nginx configuration is below.

![image](https://user-images.githubusercontent.com/37886774/79037892-6d347580-7bab-11ea-8e30-02d800ba9c3f.png)

Ps.: In this folder 443, there is only one file called **offline.html**, which warns that the server is offline.

**Comment by arajooj** [comment]
> Could you bypass nginx and see if it's related to your proxy?

You are right, I entered the jelly by the local address, and not that "socket" message, when I enter through the reverse proxy ... it gives the error.

Error consists of, the jelly console trying to use a page called _"/socket"._
When at the local address:         http://localhost:42020/socket **(OK)**
When at the external address:   https://mydomain.com/socket **(FAIL)**

What can be happening? my nginx configuration is below.

![image](https://user-images.githubusercontent.com/37886774/79037892-6d347580-7bab-11ea-8e30-02d800ba9c3f.png)

Ps.: In this folder 443, there is only one file called **offline.html**, which warns that the server is offline.

**Comment by dkanada** [comment]
If you look in the reverse proxy documentation, sockets need an extra rule to work properly.

**Comment by arajooj** [comment]
So ... I'm an ass
It was just reading the documentation of own jelly to solve this, sorry to disturb.

For those who have this problem:

[Jelly Newtorking Nginx Proxy Docs](https://jellyfin.org/docs/general/networking/nginx.html)

![image](https://user-images.githubusercontent.com/37886774/79038763-4a598f80-7bb2-11ea-87be-6d1e1ea094f0.png)

**Comment by jfranki** [comment]
I'm having this exact problem but in my case I'm running Jellyfin in a Docker container on a Synology NAS. I use the Let's Encrypt certificate along with the built-in inverse proxy of the NAS. Is there anything I can do to fix it?
