### ISSUE TITLE
 Add filesystem permissions check for relevant folders

### ISSUE THREAD

**Issue by sparky8251** [jellyfin/jellyfin#282]
Would be nice to have a little notification on the library panel letting you know if permissions don't seem to be set right for a library folder, possibly preventing reading/writing of files.

Same for the metadata/cache/etc under the settings panel.

That way its a bit more apparent why the server is acting funny if its filesystem permissions related.

**Comment by sevenrats** [comment]
Feature requests belong at our Fider instance. I have taken the liberty of migrating it for you:
https://features.jellyfin.org/posts/2350/the-server-should-have-a-filesystem-permissions-check-for-relevant-folders
