### ISSUE TITLE
Minor Jellyfin Vulnerability - wizard exposed to internet upon install

### ISSUE THREAD

**Issue by JustTom2** [jellyfin/jellyfin#2824]
After installing from Jellfin repo a port is forwarded via NAT PMP and the wizard is accessible from the internet.

**Comment by JustTom2** [comment]
To replicate install jellyfin from official repo onto a debian system via apt (unsure if this will apply to other distros)

Router must have NAT PMP enabled. 

Proceed to access wizard externally

**Comment by anthonylavado** [comment]
See #2275 for some work.

**Comment by mark-monteiro** [comment]
I think this should be resolved with #2775 which disables port forwarding by default (maybe that's what you meant to link to in your comment @anthonylavado )

**Comment by JustTom2** [comment]
Checked if this issue is resolved on the 03/05/2020. 

Issue is still present at least on linuxserver/jellyfin docker image. I know this is not the offical container but they are normally quick on updating (5 days ago last update).

Same issue, installerwizard appears to open a port via NAT PMP if the router allows it to port 8096 and 8920. 

You really don't want an unconfigured jellyfin pointing to the internet. Would allow downloading of media files by an attacker if the user did not immediatly set up jellyfin after installing it. (port opens upon install of package from repo in my previous tests)

**Comment by anthonylavado** [comment]
@JustTom2 Because of the larger change this presents, we didn't backport it in to the release builds (those are arguably only bug fixes). We'll definitely have this in 10.6, and the Nightlies (once they're started back up again)

**Comment by JustTom2** [comment]
Understood, thanks for the hard work.

**Comment by cvium** [comment]
UPnP is no longer enabled by default
