### ISSUE TITLE
Jellyfin correctly identifies season, but grabs cover for different season

### ISSUE THREAD

**Issue by sext** [jellyfin/jellyfin#2828]
**Describe the bug**

Jellyfin grabs the wrong thumbnail for the season despite being explicitly told the TheTVDB ID.

**System (please complete the following information):**
 - OS: [e.g. Debian, Windows] Debian
 - Virtualization: [e.g. Docker, KVM, LXC] Docker
 - Clients: [Browser, Android, Fire Stick, etc.] All
 - Browser: [e.g. Firefox 72, Chrome 80, Safari 13] Chrome (latest)
 - Jellyfin Version: [e.g. 10.4.3, nightly 20191231] 10.5.3
 - Playback: [Direct Play, Remux, Direct Stream, Transcode] Not relevant
 - Installed Plugins: [e.g. none, Fanart, Anime, etc.] None
 - Reverse Proxy: [e.g. none, nginx, apache, etc.] nginx
 - Base URL: [e.g. none, yes: /example] None
 - Networking: [e.g. Host, Bridge/NAT] Bridge (Docker)
 - Storage: [e.g. local, NFS, cloud] Local (volume shared through Docker) 

**To Reproduce**

1. Add https://www.thetvdb.com/series/masterclass to TV shows identified explicitly by ID.
2. Season 1's poster will show as Season 10's despite Season 1 having a poster of its own. If you delete it and pull metadata it will again pull Season 10's cover.

**Expected behavior**
The correct season's cover should show.

**Logs**

**Screenshots**

**Additional context**
Jellyfin correctly identifies it as the correct season on the top and the correct season numbers for each file within that season. Not sure why it would be seeking Season 10. I thought it may have been because I named the folder "Season 01" at first, but experimenting with a rename to "Season 1" did not show any difference.

**Comment by hamburglar2160** [comment]
When you're in "edit images" for each season are primary images provided for the correct season?

You're going to want to use the Fanart plugin to get higher quality and more accurate season art in my experience.

**Comment by sext** [comment]
@hamburglar2160 No, the only image provided inside of Jellyfin is the incorrect one for season 10. Thanks for the tip, I've enabled the plugin and I'll check it out.

I think my primary concern with filing this bug though is simply to bring attention to the fact that the default agent (TheTVDB) seems to be grabbing the incorrect season image despite the correct info being in Jellyfin and the website having the correct season image when I check it by hand. If it isn't a legit bug somehow, then I'm happy to deal with the incorrect grab manually; I just want to help improve Jellyfin. Is there any further debug info I can submit?

**Comment by KevinYobeth** [comment]
is there any update regarding this?
