### ISSUE TITLE
PPA missing for Debian & Ubuntu. Focal version not there

### ISSUE THREAD

**Issue by dga4130-renato** [jellyfin/jellyfin#2832]
As in the jellyfin main page is told how to install jellyfin on ubuntu with 

echo "deb [arch=$( dpkg --print-architecture )] https://repo.jellyfin.org/$( awk -F'=' '/^ID=/{ print $NF }' /etc/os-release ) $( awk -F'=' '/^VERSION_CODENAME=/{ print $NF }' /etc/os-release ) main" | sudo tee /etc/apt/sources.list.d/jellyfin.list

Error:14 https://repo.jellyfin.org/ubuntu focal Release
  404  Not Found [IP: 68.183.204.194 443]

the repository does not exist !

**Comment by joshuaboniface** [comment]
Focal has been added to the repository.

**Comment by webdawg** [comment]
docs need updated, focal needs added:
https://jellyfin.org/docs/general/administration/installing.html#ubuntu
