### ISSUE TITLE
TV-Series episode detection improvement

### ISSUE THREAD

**Issue by buliaoyin** [jellyfin/jellyfin#2839]
**Problem:**

TV documentations(mkv) in folders named like this:

Earth.From.Space.2019.E01.WEB-DL.1080p.H264.AAC.2Audio.mkv
Earth.From.Space.2019.E02.WEB-DL.1080p.H264.AAC.2Audio.mkv

were all detected as season 20 episode 19.

**Expect:**

Detect as season 1 episode 01/02

**Comment by lelamamalgache** [comment]
Hello @buliaoyin 

Follow the recommandations of the documentation
https://jellyfin.org/docs/general/server/media/shows.html

**Comment by buliaoyin** [comment]
@lelamamalgache

**Comment by buliaoyin** [comment]
@lelamamalgache 

It will be better to support this name format which widely used by many PT sites when the TV show has only one season. 
And I think this support would not take bad effect on other known name format.

Thanks

**Comment by buliaoyin** [comment]
https://github.com/jellyfin/jellyfin/blob/75226c18ab1b1e91370d568456e46780fcbf9d77/Emby.Naming/Common/NamingOptions.cs#L256

**Comment by buliaoyin** [comment]
https://github.com/jellyfin/jellyfin/blob/75226c18ab1b1e91370d568456e46780fcbf9d77/Emby.Naming/Common/NamingOptions.cs#L256

I think change this line with 
```
new EpisodeExpression(@"[\._ -]()[Ee][Pp]?_?([0-9]+)([^\\/]*)$"),
```
would fix this issue, but I'm not able to build jellyfin with source code to verify it currently.

**Comment by Artiume** [comment]
@Bond-009 would be a good source to discuss the regex improvement. For misidentified regex, i have this tracker ticket

https://github.com/jellyfin/jellyfin/issues/2441

**Comment by dearjoey** [comment]
how about this problem.

**Comment by cvium** [comment]
#2441 is a nice consolidation effort, but I do prefer individual issues for tracking fixes
