### ISSUE TITLE
Add sidebar to wiki

### ISSUE THREAD

**Issue by sparky8251** [jellyfin/jellyfin#284]
Worked out how to add a sidebar to the wiki allowing for links to headers inside of a specific page.

[Gist of the sidebar md file is here](https://gist.github.com/sparky8251/331bfdf9d6a51b54f95a1b08d94591af).

[Can see what it looks like and how it works here](https://github.com/sparky8251/jellyfin-wiki/wiki).

**Comment by anthonylavado** [comment]
We're planning to make a repo that can build out the Wiki so stay tuned. If I get a chance, I will add your sidebar suggestion in before hand :smile:

**Comment by joshuaboniface** [comment]
Added!
