### ISSUE TITLE
10.5.3 some subtitles cannot be centered

### ISSUE THREAD

**Issue by Jetzow527** [jellyfin/jellyfin#2840]
Some of my SUP captions cannot be in the middle of the screen. How can I solve this problem?

**Media Info of the file**

**Logs**

**FFmpeg Logs**

**Stats for Nerds Screenshots**

**Server System (please complete the following information):**
 - OS:Docker on Linux (918+,DSM6.22)
 - Jellyfin Version: 10.5.3
 - Hardware settings & device: VAAPI on Intel G4560T
 - Reverse proxy: no
 - Other hardware notes: non
 
**Client System (please complete the following information):**
 - Device: Windows,WEB,Redmi Note7Pro,Android TV
 - OS:Android, Windows
 - Client: Web/Browser,Android, Android TV
 - Browser (if Web client):Chrome
 - Client and Browser Version: [e.g. 10.3.4 and 68.0]

**Comment by Jetzow527** [comment]
I had some screenshots comparing Jellyfin and Emby's locations, but I didn't know how to post them.

**Comment by nyanmisaka** [comment]
Can I have your ffmpeg logs? The screenshot can be dragged directly in the input box.

**Comment by Jetzow527** [comment]
> Can I have your ffmpeg logs? The screenshot can be dragged directly in the input box.

Yes,this is the ffmpeg log.

[ffmpeg Log.zip](https://github.com/jellyfin/jellyfin/files/4467387/ffmpeg.Log.zip)

The screenshot:
![play with emby1](https://user-images.githubusercontent.com/63544104/79082703-2ab19b00-7d5b-11ea-94d4-ae4192cce0bb.jpg)
![play with emby2](https://user-images.githubusercontent.com/63544104/79082706-2c7b5e80-7d5b-11ea-81b5-a64140d760d7.jpg)
![play with jellyfin1](https://user-images.githubusercontent.com/63544104/79082707-2d13f500-7d5b-11ea-8118-b2d55de45653.jpg)
![play with jellyfin2](https://user-images.githubusercontent.com/63544104/79082708-2dac8b80-7d5b-11ea-8d10-4998a40a0907.jpg)
![play with jellyfin3](https://user-images.githubusercontent.com/63544104/79082709-2e452200-7d5b-11ea-8508-286e8f0d3958.jpg)

**Comment by nyanmisaka** [comment]
`
/usr/lib/jellyfin-ffmpeg-dev/ffmpeg -hwaccel vaapi -hwaccel_output_format vaapi -vaapi_device /dev/dri/renderD128 -i file:"/media1/电影/伸冤人.The.Equalizer.2014.BluRay.2160p.x265.10bit.HDR.2Audio.mUHD-FRDS/The.Equalizer.2014.BluRay.2160p.x265.10bit.HDR.2Audio.mUHD-FRDS.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -codec:v:0 h264_vaapi  -b:v 14616000 -maxrate 14616000 -bufsize 29232000 -profile:v high -level 41  -force_key_frames:0 "expr:gte(t,1200+n_forced*3)" -g 72 -keyint_min 72 -sc_threshold 0 -filter_complex "[0:3]scale=1920:800[sub];[0:0]format=nv12|vaapi,hwupload,scale_vaapi=w=1920:h=800:format=nv12,hwdownload[base];[base][sub]overlay,format=nv12,hwupload" -start_at_zero -vsync -1 -codec:a:0 libmp3lame -ac 2 -ab 384000 -af "volume=2" -copyts -avoid_negative_ts disabled -f hls -max_delay 5000000 -y /tmp/output.mp4
`

Try this command and see if it works.
The output is located in `/tmp/output.mp4`

**Comment by Jetzow527** [comment]
> `/usr/lib/jellyfin-ffmpeg-dev/ffmpeg -hwaccel vaapi -hwaccel_output_format vaapi -vaapi_device /dev/dri/renderD128 -i file:"/media1/电影/伸冤人.The.Equalizer.2014.BluRay.2160p.x265.10bit.HDR.2Audio.mUHD-FRDS/The.Equalizer.2014.BluRay.2160p.x265.10bit.HDR.2Audio.mUHD-FRDS.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -codec:v:0 h264_vaapi -b:v 14616000 -maxrate 14616000 -bufsize 29232000 -profile:v high -level 41 -force_key_frames:0 "expr:gte(t,1200+n_forced*3)" -g 72 -keyint_min 72 -sc_threshold 0 -filter_complex "[0:3]scale=1920:800[sub];[0:0]format=nv12|vaapi,hwupload,scale_vaapi=w=1920:h=800:format=nv12,hwdownload[base];[base][sub]overlay,format=nv12,hwupload" -start_at_zero -vsync -1 -codec:a:0 libmp3lame -ac 2 -ab 384000 -af "volume=2" -copyts -avoid_negative_ts disabled -f hls -max_delay 5000000 -y /tmp/output.mp4`
> 
> Try this command and see if it works.
> The output is located in `/tmp/output.mp4`

Ok, I'll try.

**Comment by Jetzow527** [comment]
> `/usr/lib/jellyfin-ffmpeg-dev/ffmpeg -hwaccel vaapi -hwaccel_output_format vaapi -vaapi_device /dev/dri/renderD128 -i file:"/media1/电影/伸冤人.The.Equalizer.2014.BluRay.2160p.x265.10bit.HDR.2Audio.mUHD-FRDS/The.Equalizer.2014.BluRay.2160p.x265.10bit.HDR.2Audio.mUHD-FRDS.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -codec:v:0 h264_vaapi -b:v 14616000 -maxrate 14616000 -bufsize 29232000 -profile:v high -level 41 -force_key_frames:0 "expr:gte(t,1200+n_forced*3)" -g 72 -keyint_min 72 -sc_threshold 0 -filter_complex "[0:3]scale=1920:800[sub];[0:0]format=nv12|vaapi,hwupload,scale_vaapi=w=1920:h=800:format=nv12,hwdownload[base];[base][sub]overlay,format=nv12,hwupload" -start_at_zero -vsync -1 -codec:a:0 libmp3lame -ac 2 -ab 384000 -af "volume=2" -copyts -avoid_negative_ts disabled -f hls -max_delay 5000000 -y /tmp/output.mp4`
> 
> 尝试此命令，看看它是否有效。
> 输出位于`/tmp/output.mp4`

It's running, but I can't read it.
![20200413083749](https://user-images.githubusercontent.com/63544104/79083647-23da5680-7d62-11ea-90c0-b4a4d2eb10e0.png)

**Comment by nyanmisaka** [comment]
Ctrl+C to abort it.
Check the output to see if the subtitle position is normal.

**Comment by Jetzow527** [comment]
> Ctrl+C to abort it.
> Check the output to see if the subtitle position is normal.

Yes, the caption is in the center now. How can I improve my jellyfin?
![20200413084749](https://user-images.githubusercontent.com/63544104/79083886-7bc58d00-7d63-11ea-883b-254835fc5817.png)

**Comment by nyanmisaka** [comment]
> Yes, the caption is in the center now. How can I improve my jellyfin?
> ![20200413084749](https://user-images.githubusercontent.com/63544104/79083886-7bc58d00-7d63-11ea-883b-254835fc5817.png)

I have located the issue and will resolve it in my recent PR.  Thank you for the test.

**Comment by Jetzow527** [comment]
> > 是的，标题现在在中间。如何改善果冻？
> > ![20200413084749](https://user-images.githubusercontent.com/63544104/79083886-7bc58d00-7d63-11ea-883b-254835fc5817.png)
> 
> 我已找到问题，并将在我最近的PR中解决。谢谢您的测试。

The problem actually existed in last year's release, but has never been resolved.

Looking forward to your good news!

**Comment by Jetzow527** [comment]
> > Yes, the caption is in the center now. How can I improve my jellyfin?
> > ![20200413084749](https://user-images.githubusercontent.com/63544104/79083886-7bc58d00-7d63-11ea-883b-254835fc5817.png)
> 
> I have located the issue and will resolve it in my recent PR. Thank you for the test.
May I ask, when can this PR be submitted?

**Comment by nyanmisaka** [comment]
> May I ask, when can this PR be submitted?

https://github.com/jellyfin/jellyfin/pull/2809
