### ISSUE TITLE
Jellyfin doesn't create its folders at first boot

### ISSUE THREAD

**Issue by ferferga** [jellyfin/jellyfin#2854]
After installing Jellyfin for the first time, Jellyfin doesn't create the directories it needs to run.

**System**
Ubuntu 18.04 amd64

**Steps to reproduce**
* Fire a blank Linux VM with Ubuntu 18.04 amd64
* Install Jellyfin as instructed in jellyfin.org
* Go to setup wizard and finish it
* Login and go to Dashboard. Try to change the language in 'General' tab and Save.

``Error processing request: "/var/lib/jellyfin/metadata does not exist". URL: "http://localhost:8096/System/Configuration"``

**Expected behaviour**
Jellyfin must create everything it needs to function properly when installing

![image](https://user-images.githubusercontent.com/10274099/79121833-8d745800-7d96-11ea-9794-945bb55c52a4.png)

**Comment by nyanmisaka** [comment]
The `transcoding-temp/transcodes` folder is also not created.

**Comment by ferferga** [comment]
Thanks @nyanmisaka, title changed.

**Comment by anthonylavado** [comment]
Current debugging in chat points to an issue introduced starting with 10.5.0.
