### ISSUE TITLE
Unicode problem with .smi

### ISSUE THREAD

**Issue by Alice-Schuberg** [jellyfin/jellyfin#2859]
**Describe the bug**

Since 10.5.x, subtitles do not appear in most videos
Looking at the log, the video with subtitles is encoded as euc-kr, and the video with no subtitles is encoded as utf-16le.

**System (please complete the following information):** 
os : sysnology nas docker
ver : 10.5.4
web : chrome

**To Reproduce**

2 new videos that were not in the library (or rename the video) (maybe subtitle cache)
Same subtitle encoded asni or utf-8 and utf-16le
Video playback

asni, utf-8 video has subtitles
utf-16le video does not have subtitles

**Logs**

[Log.txt](https://github.com/jellyfin/jellyfin/files/4470293/Log.txt)
line 292, 306

[test-sub.zip](https://github.com/jellyfin/jellyfin/files/4470325/test-sub.zip)
Same subtitles with different encodings

**Additional context**

The easiest solution to add a character language setting to encode

It also loses the country mark in the process of converting subtitles.
Subtitle preference option is useless
![캡처](https://user-images.githubusercontent.com/39822140/79136453-0225b180-7dec-11ea-87db-75dbf39c084c.PNG)

And also Korean .ass problem like #2670 [web#934](https://github.com/jellyfin/jellyfin-web/issues/934)

**Comment by HelloWorld017** [comment]
I think it is related to #1540.
Recently, I have noticed that UTF-16LE / UTF-16BE Encoding name is given with lower case.
But in the code ([SubtitleEncoder.cs#L420](https://github.com/jellyfin/jellyfin/blob/master/MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs#L420)) it only matches the upper case.
I think it should be `Equals("UTF-16BE", StringComparison.OrdinalIgnoreCase)`.

**Comment by dkanada** [comment]
@Alice-Schuberg has this been resolved on the latest version?

**Comment by Alice-Schuberg** [comment]
> @Alice-Schuberg has this been resolved on the latest version?

No, it has not been resolved in 10.5.5. I solved by replacing all subtitles with ansi.

**Comment by Paosder** [comment]
I had similar problem related with this issue. 

Moreover, if this problem occurs in specific video, subtitle won't appears until you delete subtitle data in jellyfin(`config/data/subtitle`) manually. 😭  

I found that encoder parses only first executing video's subtitle(some subtitle file to `SRT` format, e.g: `smi` -> `srt`), then it comes to 0kb data(means no parsed data, see details below) when it fails to parse(I guess) but put it on jellyfin's subtitle data directory(it seems caching subtitles)(#3001). Then subtitle won't work until remove subtitle data(not real subtitle file, jellyfin's subtitle data, `config/data/subtitle/[file_id]`). I think encoder must check its parsed data, then cancel generating subtitle data when its empty.
![image0](https://user-images.githubusercontent.com/20926881/82170643-01f36700-9900-11ea-9464-fca05e8eed21.png)

To workaround for these issues, as @Alice-Schuberg mentioned(https://github.com/jellyfin/jellyfin/issues/2859#issuecomment-628367698) is good approach, but it won't work if it already parsed once with subtitle file that has specific encoding(e.g `UTF-16LE`), so you have to remove jellyfin's subtitle data manually. 
+ `SAMI(smi)` with `UTF-8` also works so you don't have to set all subtitles to `ANSI`, however `webVTT` won't work whether its format type (seems converter has some issues with parsing `vtt` files into `srt` 😢).
