### ISSUE TITLE
All my films are duplicate on my jellyfin

### ISSUE THREAD

**Issue by andy86money** [jellyfin/jellyfin#2867]
**Media Info of the file**

**Logs**

**FFmpeg Logs**

**Stats for Nerds Screenshots**

**Server System (please complete the following information):**
 - OS: [e.g. Docker on Linux, Docker on Windows, Debian, Windows]
 - Jellyfin Version: [e.g. 10.0.1]
 - Hardware settings & device: [e.g. NVENC on GTX1060, VAAPI on Intel i7 8700K]
 - Reverse proxy: [e.g. no, nginx, apache, etc.]
 - Other hardware notes: [e.g. Media mounted in CIFS/SMB share, Media mounted from Google Drive]
 
**Client System (please complete the following information):**
 - Device: [e.g. Apple iPhone XS, Xbox One S, LG OLED55C8, Samsung Galaxy Note9, Custom HTPC]
 - OS: [e.g. iOS, Android, Windows, macOS]
 - Client: [e.g. Web/Browser, webOS, Android, Android TV, Electron]
 - Browser (if Web client): [e.g. Firefox, Chrome, Safari]
 - Client and Browser Version: [e.g. 10.3.4 and 68.0]

**Comment by andy86money** [comment]
Hi I'm trying to figure out why everytime I upload a movie. It appears twice in my jellyfin ?

**Comment by Artiume** [comment]
Don't know. What does the file naming look like for your files? Also fill out the details for your report, are you on latest or an older version?

**Comment by andy86money** [comment]
I believe I'm on the latest version
/home/username/media/movies that's what it looks like

**Comment by Artiume** [comment]
What about file names? And please just fill out the initial report. Still doing know you're OS or type of install. We haven't seen this issue before so it's all going to be based on your system details until we can reproduce the issue

**Comment by andy86money** [comment]
Where do I find the initial report I dnt even know how or where

**Comment by Artiume** [comment]
It's the initial comment of the ticket.

---
Media Info of the file

Logs

FFmpeg Logs

Stats for Nerds Screenshots

Server System (please complete the following information):

OS: [e.g. Docker on Linux, Docker on Windows, Debian, Windows]Jellyfin Version: [e.g. 10.0.1]Hardware settings & device: [e.g. NVENC on GTX1060, VAAPI on Intel i7 8700K]Reverse proxy: [e.g. no, nginx, apache, etc.]Other hardware notes: [e.g. Media mounted in CIFS/SMB share, Media mounted from Google Drive]

Client System (please complete the following information):

Device: [e.g. Apple iPhone XS, Xbox One S, LG OLED55C8, Samsung Galaxy Note9, Custom HTPC]OS: [e.g. iOS, Android, Windows, macOS]Client: [e.g. Web/Browser, webOS, Android, Android TV, Electron]Browser (if Web client): [e.g. Firefox, Chrome, Safari]Client and Browser Version: [e.g. 10.3.4 and 68.0]

**Comment by andy86money** [comment]
I hope this helps. TV shows and music did not have doubles idk why movies
does.

**Comment by hkpanchani** [comment]
Same movies appearing twice. 
![image](https://user-images.githubusercontent.com/35301566/121332259-51566c00-c935-11eb-9407-b5a2be45f49e.png)

Jellyfin version 10.7.5.0 on debian AMDx64

**Comment by Artiume** [comment]
Go to Dashboard > Libraries > Display

Check 'group movies into collections'

**Comment by b-m-f** [comment]
Same thing is happening for me.
