### ISSUE TITLE
10.5.4 windows installer EXE installs 10.5.3?

### ISSUE THREAD

**Issue by RicLund** [jellyfin/jellyfin#2870]
I'm upgrading from 10.5.0 with the 10.5.4 EXE from here but it actually installed (and the installer wizard says it's installing) 10.5.3? @joshuaboniface

**Comment by RicLund** [comment]
Filename is jellyfin_v10.5.4-x64_windows.exe

**Comment by RicLund** [comment]
File version in metadata is also 10.5.3.0 so looks like there's just a mixup with what file was posted.

**Comment by anthonylavado** [comment]
Known issue - we have to post a fix still

**Comment by anthonylavado** [comment]
This should be fixed now. Please redownload the Windows version.
