### ISSUE TITLE
Audio playback causes firefox tabs to crash

### ISSUE THREAD

**Issue by KristupasSavickas** [jellyfin/jellyfin#2878]
**Describe the bug**
Some music tracks seem to be crashing my Firefox browser tab (see the screenshot for what I mean exactly) at specific timestamps. Starting the track past the timestamp that causes the crash works fine. On chromium (tested with `Chromium 81.0.4044.92 snap`) the track plays fine.

I haven't pinpointed this to a specific format yet, but all the music on my server is FLAC. I'm unable to attach a log from the browser, as the developer tools crash together with the tab. See the attached server log for more details.

**System (please complete the following information):**
 - OS: Client: Ubuntu 20.04 beta (happens on 19.10 too), server: Debian Buster
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Fifrefox 75.0
 - Jellyfin Version: 10.5.4
 - Playback: Direct Play 
 - Installed Plugins: AudioDB, Kodi Sync Queue, MusicBrainz, Open Subtitles, Playback Reporting, Trakt, [Last.fm](https://github.com/jesseward/jellyfin-plugin-lastfm) (outdated, but seems to be working fine)
 - Reverse Proxy: Traefik
 - Base URL: none
 - Networking: Docker
 - Storage: local

**Logs**
https://gist.github.com/KristupasSavickas/b2cf8a895ab2661da3ffa80a7a4119b5 (the relevant logs begin at around `2020-04-15 13:18:04.156`)

**Screenshots**
![Screenshot_20200415_124145](https://user-images.githubusercontent.com/1362643/79327932-f2a68580-7f1d-11ea-99cc-0035d77d380b.png)

**Additional context**
I can provide login to my server to Jellyfin maintainers or upload the copy of the audio files that cause this. Please let me know if you need any additional information to help solve this.

**Comment by Artiume** [comment]
Can you verify that the track is Direct Playing.

Force it to transcode during the crash point, does it still crash? 

Can you pull up the media info for the song.

**Comment by KristupasSavickas** [comment]
@Artiume 

> Can you verify that the track is Direct Playing.
![Screenshot_20200415_135149](https://user-images.githubusercontent.com/1362643/79329321-43b77900-7f20-11ea-936e-4b1a46841ed2.png)

So I guess it is.

> Force it to transcode during the crash point, does it still crash?

How do I do that? I see no options for changing the quality of audio on the web/
> Can you pull up the media info for the song.
```
ffprobe 01\ Dance\ Yrself\ Clean.flac 
ffprobe version 4.1.4-1~deb10u1 Copyright (c) 2007-2019 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --prefix=/usr --extra-version='1~deb10u1' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Input #0, flac, from '01 Dance Yrself Clean.flac':
  Metadata:
    ALBUM           : This Is Happening
    ALBUM ARTIST    : LCD Soundsystem
    album_artist    : LCD Soundsystem
    ALBUMARTIST_CREDIT: LCD Soundsystem
    ALBUMARTISTSORT : LCD Soundsystem
    MUSICBRAINZ_ALBUMSTATUS: Official
    MUSICBRAINZ_ALBUMTYPE: album
    ARTIST          : LCD Soundsystem
    ARTIST_CREDIT   : LCD Soundsystem
    ARTISTSORT      : LCD Soundsystem
    ASIN            : B00EMKVDJ6
    BPM             : 0
    CATALOGNUMBER   : 791401-PRL2
    COMPILATION     : 0
    COMPOSER        : James Murphy
    COMPOSERSORT    : Murphy, James
    RELEASECOUNTRY  : US
    DATE            : 2010-05-12
    YEAR            : 2010
    disc            : 1
    DISCTOTAL       : 1
    DISCC           : 1
    TOTALDISCS      : 1
    LABEL           : Parlophone
    PUBLISHER       : Parlophone
    LANGUAGE        : eng
    LYRICIST        : James Murphy
    MUSICBRAINZ_ALBUMARTISTID: 2aaf7396-6ab8-40f3-9776-a41c42c8e26b
    MUSICBRAINZ_ALBUMID: daaf88a4-61e4-4852-8d1f-f4db8382ea9c
    MUSICBRAINZ_ARTISTID: 2aaf7396-6ab8-40f3-9776-a41c42c8e26b
    MUSICBRAINZ_RELEASEGROUPID: 8898e5eb-48aa-4eea-8569-d3a2e9adaf02
    MUSICBRAINZ_RELEASETRACKID: 8d63e000-29d9-4436-b5a0-283935a2f0d0
    MUSICBRAINZ_TRACKID: 2351cd90-50cc-4862-bba0-6fa8b807b4e3
    MEDIA           : CD
    ORIGINALDATE    : 2010-05-12
    R128_ALBUM_GAIN : 0
    R128_TRACK_GAIN : 0
    TITLE           : Dance Yrself Clean
    track           : 1
    TRACKTOTAL      : 9
    TRACKC          : 9
    TOTALTRACKS     : 9
  Duration: 00:08:56.11, start: 0.000000, bitrate: 724 kb/s
    Stream #0:0: Audio: flac, 44100 Hz, stereo, s16
```

**Comment by Artiume** [comment]
Music transcoding is only accessible for manipulation via mobile. User settings > playback > music transcoding.


I want to say the global bitrate throttler would also work as well.

**Comment by KristupasSavickas** [comment]
Looks to be a Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1528265
