### ISSUE TITLE
Incorrect etags in /Users/{UserId}/Items when using the Recursive flag

### ISSUE THREAD

**Issue by firecore** [jellyfin/jellyfin#2881]
**Describe the bug**
- The server responds with incorrect etags for /Users/{UserId}/Items when the `Recursive` flag is set to `true`

**System:**
- OS: macOS 10.15.4, Windows 10 1909
- Clients: cURL, Postman, Infuse
- Jellyfin: v10.4.3, v10.5.3, v10.5.4

**To Reproduce**
- Index a library with movies or TV shows in Jellyfin 
- Call `/Users/{UserId}/Items` with `Fields=Etag`
- Call `/Users/{UserId}/Items` with `Fields=Etag&Recursive=true`
- Inspect the Etag parameter in the responses
- Run the same test with Emby server

**Actual behavior**
- With `Fields=Etag&Recursive=true`, the server responds with the same etag for all of the items
- Emby returns correct Etags for similar recursive requests (https://hastebin.com/raw/izopuwaxav)

**Expected behavior**
- The server responds with correct etags for /Users/{UserId}/Items with or without the `Recursive` flag

**Logs**
- API call with Recursive: https://hastebin.com/raw/uhuzuhoged
- API call w/o Recursive: https://hastebin.com/raw/osohiqefey
- Server Logs: https://hastebin.com/raw/ekuguhaqik

**Additional context**
- 3rd party clients may heavily rely on recursive batch requests as they provide substantially higher throughput. At the same time, incorrect etags may prevent timely content updates.

**Comment by anthonylavado** [comment]
Investigating - thus far, unable to replicate with Jellyfin 10.5.4 on Debian GNU/Linux 10 (buster)       (Kernel: Linux 4.19.0-6-amd64).

**Comment by anthonylavado** [comment]
Able to replicate this with a new library, testing on macOS.

**Comment by anthonylavado** [comment]
We've located the issue. Look at the following statement:

https://github.com/jellyfin/jellyfin/blob/b76f570583d607898064e21b6431aa30bffe97f7/MediaBrowser.Controller/Entities/BaseItem.cs#L2747-L2753

In this function, DateLastSaved is getting a null from the User element (because User doesn't have a saved date), and thus this is getting cast to `"0"`. This is happening with every item, so the result is always the same.

**Comment by mark-monteiro** [comment]
@anthonylavado Here's the result of my quick investigation. `DateLastSaved` is only set in `LibraryManager.UpdateItems`, but not in `LibraryManager.CreateItems`. So a quick fix would be to initialize the value in the `LibraryManager.CreateItems` method, or the `BaseItem` constructor.

But I think the correct solution would be to remove the assignment from `LibraryManager.UpdateItems` and push the logic down a level into `SqliteItemRepository.SaveItems` (which is used by both methods in `LibraryManager`)

**Comment by anthonylavado** [comment]
In the Matrix Chat, @Bond-009 proposed removing this line: https://github.com/jellyfin/jellyfin/blame/5c669d7ad7145eb2b54ec88a8636a28ea4eefcd1/MediaBrowser.Controller/Entities/BaseItem.cs#L552

In current testing, this may be the fix. It would explain why an older library, established in the pre-10.4 days would have worked (my Debian server).

**Comment by anthonylavado** [comment]
In further testing, I can confirm that this fixes the issue. The change was part of https://github.com/jellyfin/jellyfin/pull/1898, which was implemented in 10.4.1.

Creating a fix now.

**Comment by esmondmissen** [comment]
I still seem to be having this issue. If recursive is set to true all tags are the same.
