### ISSUE TITLE
TheTVDB Remote Query get "Undefined" result.

### ISSUE THREAD

**Issue by billyinferno** [jellyfin/jellyfin#2885]
**BUG**
The RemoteSearch/Series querys resulted in undefined result.

**System:**
 - OS: Ubuntu 18.04
 - Jellyfin Version: 10.5.4

**To Reproduce**
1. Identify TV Series
2. Put TVDB ID **372626**
3. Press Search
4. Resulted page will be showed as Undefined.

**Expected behavior**
Should show correct TVDB series (trying to get the series directly using TVDB API is working)
https://imgur.com/mGzbugP

TVDB URL for the show: https://www.thetvdb.com/series/372626-like

**Logs**
No error log showed on the jellyfin log.

**Screenshots**
Result Page:
https://imgur.com/TXtLsWY

JSON Response from the call:
https://imgur.com/QhRUvin
No name being mentioned there (hence got Undefined).

**Comment by dennisrpnw** [comment]
still happening
