### ISSUE TITLE
[Enhancement] Library Watched Status Toggle

### ISSUE THREAD

**Issue by Artiume** [jellyfin/jellyfin#2889]
Adding Audio Books, you can either add them as Books or as Music. Adding them as books has some limitations, and adding them as Music doesn't work since there's no memory for watched status.

I think it'd be a nice improvement to add a toggle on Music Libraries to remember watched status. 

Hm. Why not add the toggle to every library?

**Comment by w111a** [comment]
I really like this idea. I was going to start an issue about the file structure audiobooks must be in to work propperly as a "book" library ( not organised by author ) but I think your approach is much more flexible. As you stated, this would allow us to use audiobooks as "music" and track progress.
