### ISSUE TITLE
Guide freezes on iOS

### ISSUE THREAD

**Issue by skug67** [jellyfin/jellyfin#2890]
When accessing the Guide for LiveTV on iOS the grid is displayed and is filled in but the screen then freezes.

 - OS: Debian
 - Virtualization: KVM
 - Clients: iOS (Safari, Chrome, etc)
 - Browser: All iOS and only iOS
 - Jellyfin Version: 10.5.4, has been present since at least 10.5.2
 - Playback: n/a 
 - Installed Plugins: AudioDB/IPTV/KodiSyncQueue/MuiscBrainz/TMDBBoxSets
 - Reverse Proxy: apache
 - Base URL: yes: /jellyfin
 - Networking: occurs over both LAN and NAT-ed firewall
 - Storage: local/

**To Reproduce**
1. Go to Guide on an iOS device
2. Wait for guide to load
3. No interaction possible thereafter

**Expected behavior**
Expect to be able to scroll through guide and select programs

**Logs**

[2020-04-15 20:51:32.544 -04:00] [ERR] Could not find handler for "/socket"
[2020-04-15 20:51:32.544 -04:00] [ERR] Error processing request: "Unable to find the specified file". URL: "http://192.168.0.140:8096/socket?deviceId=TW96aWxsYS
81LjAgKE1hY2ludG9zaDsgSW50ZWwgTWFjIE9TIFggMTBfMTVfNCkgQXBwbGVXZWJLaXQvNjA1LjEuMTUgKEtIVE1MLCBsaWtlIEdlY2tvKSBWZXJzaW9uLzEzLjEgU2FmYXJpLzYwNS4xLjE1fDE1ODYzOTQ4MjkwNDE1"

**Comment by Artiume** [comment]
Can you test this on Safari Mobile and see if you receive the same behavior?

**Comment by skug67** [comment]
Yes.  Same result on Safari/Chrome and the Jellyfin app.

**Comment by skug67** [comment]
And I should add that I've tested it both with and without the BaseUrl and via direct access on port 8096 as well as via the reverse proxy.

**Comment by Artiume** [comment]
Is this only on your phone or does it happen on an ios desktop environment as well? If so, maybe the console browser could show something

**Comment by skug67** [comment]
Huh.  All I've got is an iPad which is where I'm having the problem.  But just checked on my son's iPhone and no problem there.  Not sure what an "ios desktop environment" is.

**Comment by Artiume** [comment]
MacOS on a desktop, I'm not a Mac guy 😅. Odd that it's isolated to one specific device especially when they share the same environment. Probably an odd one, but does your device name have spaces or an apostrophe in it? I recall that being an issue that was fixed.

**Comment by skug67** [comment]
No apostrophe....

**Comment by Artiume** [comment]
Can I get the iPad model number

**Comment by skug67** [comment]
iPad Pro (3rd generation/2018 model, 11-inch)

**Comment by skug67** [comment]
iOS version 13.4.1, although recently updated and the problem was there on the immediately prior version of iOS as well.

**Comment by skug67** [comment]
Probably should have thought of this earlier, but a full clear of my iOS Safari cache (as opposed to just for the jellyfin site) seems to have solved the problem.
