### ISSUE TITLE
Clicking on a playlist item starts the playing from the top

### ISSUE THREAD

**Issue by gerroon** [jellyfin/jellyfin#2891]
**Describe the bug**
Clicking on a playlist item starts the playlist from the top of the playlist instead of playing from the clicked item and down.

**System (please complete the following information):**
 - OS:  Debian testing
 - Browser: Firefox
 - Jellyfin Version: 10.5.4-1
 - Playback: Direct
 - Installed Plugins: Kodi
  - Storage: local

Steps

Make a new playlist
Add bunch of items to playlist 
Select Play On device and choose another client
Open the playlist
Click on an item from somewhere in the middle of the playlist
It will play from the top down on the cast client

**Comment by Maxr1998** [comment]
I can confirm this also happens for albums.

- OS: Ubuntu 18.04 Server/Docker
- Browser: Vivaldi/Official Android App
- Jellyfin Version: 10.5.4-1
- Playback: Direct
- Plugins: None
- Storage: local

**Comment by rigrig** [comment]
Still happening for both albums and playlists with Chromecast
Jellyfin version: 10.6.4, in docker
Browser: chromium 85.0.4183.59

**Comment by Maxr1998** [comment]
Still occurring in 10.7.1, should probably be reopened.

**Comment by Maxr1998** [comment]
Not fixed yet (I think).

**Comment by ppittle** [comment]
Wasn't able to repro casting to a web client on `10.8.4` (b344771):
![GH-2891](https://user-images.githubusercontent.com/1190907/185539287-0dbecae5-54e7-4698-9477-8c9b1da7bf55.gif)

Is this only broken using a specific player?
