### ISSUE TITLE
Connections on users

### ISSUE THREAD

**Issue by andy86money** [jellyfin/jellyfin#2892]
Hi can u please install a feature to control how many connections we can limit our users too I dont want to buffer at my house **PLEASE DO NOT OPEN FEATURE REQUEST ISSUES ON GITHUB**

**Feature requests should be opened on our dedicated [feature request](https://features.jellyfin.org/) hub so they can be appropriately discussed and prioritized.**

However, if you are willing to contribute to the project by adding a new feature yourself, then please ensure that you first review our [documentation](https://docs.jellyfin.org/general/contributing/development.html) on contributing code. Once you have reviewed the documentation, feel free to come back here and open an issue here outlining your proposed approach so that it can be documented, tracked, and discussed by other team members.

**Comment by ConfusedPolarBear** [comment]
Feature requests are best taken [here](https://features.jellyfin.org). Please search for a similar one and, if you can't find one like yours, make a new one. However, [this](https://features.jellyfin.org/posts/59/account-based-stream-limit) request looks similar to what you describe with limits for:
* Max concurrent streams per user
* Max streams for entire server
* Max transcodes per user
* Max transcodes per server
