### ISSUE TITLE
Windows Stable v10.5.4 installer error

### ISSUE THREAD

**Issue by marineris** [jellyfin/jellyfin#2895]
**Describe the bug**
I'm a new user and trying to install JF for the first time. I downloaded the Stable "jellyfin_v10.5.4-x64.exe" file but got the message "This app can't run on your PC" from Windows. I then downloaded jellyfin_v10.5.3-x64 and the install wizard starts fine. I noticed the 10.5.4 downloaded 2 files ("jellyfin_v10.5.4-x64.exe" and "jellyfin_v10.5.4-x64.exe.part") whereas v10.5.3 only has the .exe and shows the JF logo as the thumbnail. I have not installed 10.5.3, is it considered stable or should I wait for the 10.5.4 fix?

**System (please complete the following information):**
 - OS: Windows 10 1909
 - Virtualization: none
 - Clients: windows installer
 - Browser: Firefox 
- Jellyfin Version: Stable 10.5.4
- Playback: N/A
 - Installed Plugins: N/A
 - Reverse Proxy: none
 - Base URL:  ??
 - Networking: N/A
 - Storage: local

**To Reproduce**
1. Go to https://jellyfin.org/downloads/#windows
2. Click on Stable
3. Download/save "jellyfin_v10.5.4-x64.exe "
4. Run .exe, See error

**Expected behavior**
Runs Install Wizard 

**Logs**
N/A

**Screenshots**
Can be acquired if requested

**Additional context**
 I noticed the 10.5.4 downloaded 2 files ("jellyfin_v10.5.4-x64.exe" and "jellyfin_v10.5.4-x64.exe.part") whereas v10.5.3 only has the .exe and shows the JF logo as the thumbnail. 

EDIT: In the description I mistakenly wrote one instance of v10.4.3 when I meant v10.5.3. Regardless, both v10.4.3 and v10.5.3 installers start fine and v10.5.4 does not.

**Comment by anthonylavado** [comment]
It sounds like 10.5.4 didn’t download correctly for you. Could you delete it and try it from GitHub? Let me get you a link.

**Comment by anthonylavado** [comment]
https://github.com/jellyfin/jellyfin/releases/download/v10.5.4/jellyfin_v10.5.4-x64_windows.exe

**Comment by marineris** [comment]
Great, thanks! The one from the website is now working too.
