### ISSUE TITLE
Port Forwarding Always Maps HTTP Port

### ISSUE THREAD

**Issue by mark-monteiro** [jellyfin/jellyfin#2901]
**Describe the bug**
There is no option to exclusively port forward HTTPS. If port forwarding is enabled, both HTTP and HTTPS port forwarding rules are always created. When HTTPS is enabled, it is likely that HTTP port forwarding is not desired.

**To Reproduce**
1. Go to Network Settings in the dashboard
2. Enable port forwarding
3. See that port forwarding is always enabled for HTTP and there is no way to disable it while still creating a port forward rule for HTTPS

**Expected behavior**
When port forwarding is turned on, only HTTPS port forwarding should be enabled by default. Port forwarding the HTTP port should be an additional opt-in configuration option.

**Comment by gotton** [comment]
I suggest you use virtual host and add a permanent redirection on https.

**Comment by BaronGreenback** [comment]
Enhancement made in upcoming UPnP plugin.

**Comment by HybridSarcasm** [comment]
This has been open quite a while. Can this be re-produced with the current build? If so, please update the bug report details. Thanks!

**Comment by sevenrats** [comment]
removing stale confirmed label. needs reproduction.
