### ISSUE TITLE
Jellyfin (View Console) keeps crashing

### ISSUE THREAD

**Issue by RandomDelta6** [jellyfin/jellyfin#2909]
Describe the bug

On launching Jellyfin (view console), it launches, stays for a a blink and you miss it moment and then closes automatically. I managed to get a screenshot of the terminal a few moments before it crashed. I have noticed a big paragraph to appear on console just before the windows crashes. unfortunately it is so quick, I am unable to get it on a screenshot. I don't have any plugins install and the installation is pretty much all stock, nothing modified. I would like to point out that all functions are working normally as far as I can see on the server. It is installed in the basic install method.

System (please complete the following information):

OS: Windows 10
Virtualization: Enabled
Clients: Browser
Browser: Chrome Version 81.0.4044.113
Jellyfin Version: 10.5.4
Playback: N/A
Installed Plugins: None
Reverse Proxy: none
Base URL: N/A
Networking: N/A
Storage: 1TB HDD 500GB NVMe SSD

To Reproduce

Launch Jellifin view console

Expected behavior

The View console is not expected to crash and is expected to display what esactly jellifin is doing on the PC

Logs

Even with debug turned on, I was unable to find anything relevant in the logs.

Screenshots

Attached screenshot of console.

Any help would be appreciated !!!
![Annotation 2020-04-17 142555](https://user-images.githubusercontent.com/53912269/79627795-012cb100-8159-11ea-8928-f1d60688a01f.png)

**Comment by anthonylavado** [comment]
The "View Console" option actually starts a copy of the server with the console open. This will crash if the server is already running (like as a Service or using the tray app).

With the "View Console" window closed, open the Task Manager, and go to the Details tab. If `jellyfin.exe` shows up in the list, it is already running in the background, and that's why the View Console option is crashing.

Is there any particular reason you want the console on the screen? Everything it shows should be written in the text logs.

**Comment by RandomDelta6** [comment]
I have tried  killing the jellyfin.exe process and then again launched the view console. But it still keeps crashing.

The text logs don't seem to be generating always for some reason. If logs don't generate, restarting the pc helps. Also, I like to keep an eye on what exactly jellyfin is doing

**Comment by mark-monteiro** [comment]
@RandomDelta6 Can you provide the logs from an instance when the view console crashes?

**Comment by anthonylavado** [comment]
@RandomDelta6 also, did you install Jellyfin with the basic option, or the service/advanced option?

**Comment by BaronGreenback** [comment]
If there is nothing in the Jellyfin log. What's showing in the event log in windows?

**Comment by RandomDelta6** [comment]
I installed as basic install. I had installed the latest nightly (april8) . I later moved onto the jellyfin stable and now I don't face this issue .

But for some reason, plugins fail to install for me on the stable version.

**Comment by RandomDelta6** [comment]
Issues solved in release 10.5.5

**Comment by thereddestdog** [comment]
> Is there any particular reason you want the console on the screen? Everything it shows should be written in the text logs.

Ever use WireShark? Live logging is very useful vs static text
