### ISSUE TITLE
Unique Server Software

### ISSUE THREAD

**Issue by Essasetic** [jellyfin/jellyfin#291]
To fully branch out of Emby. Will there eventually be server software completely seperate to Emby? This would open up the doors to brand new unique features and would remove the limitations of the current Emby server software. It would also get rid of the "premiere" issues people are having and allow people to use it on whatever device they want completely free.

**Comment by Essasetic** [comment]
> 
> 
> This is already the case. Jellyfin is completely separate from Emby. The trouble is all the close sourced clients, not the server.

Ah my bad. Will this eventually be resolved or is that impossible?

**Comment by EraYaN** [comment]
Well it just requires writing new clients.

**Comment by anthonylavado** [comment]
Yes, Jellyfin in its current state is basically separate from Emby. As mentioned, the clients were mostly closed source, but we grabbed the last open source versions of many of them, and have forked those as well. Progress is slower on those, as the current server "works" with the current Emby apps for the time being.

There is the thought of eventually re-writing this, or creating a new, more modular project, but that's further down the line. This current code gives us a good base to start from, and we'll keep going with it as long as we can.
