### ISSUE TITLE
Jellyfin (code=killed, signal=ILL)

### ISSUE THREAD

**Issue by sabharwalrahul91** [jellyfin/jellyfin#2912]
Hi,

I installed jellyfin on Debian with arm-hf arch

i used default repository and installed latest version.
i have tried multiple times but always received this error.

here is the output i receive on command :
`sudo service jellyfin status`  

  

> jellyfin.service - Jellyfin Media Server
> 
>    Loaded: loaded (/lib/systemd/system/jellyfin.service; enabled; vendor preset: enabled)
>   Drop-In: /etc/systemd/system/jellyfin.service.d
>            └─jellyfin.service.conf
>    Active: failed (Result: signal) since Sat 2020-04-18 18:11:33 IST; 32min ago
>   Process: 28091 ExecStart=/usr/bin/jellyfin ${JELLYFIN_RESTART_OPT} ${JELLYFIN_FFMPEG_OPT} ${JELLYFIN_SERVICE_OPT} ${JELLYFIN_
>  Main PID: 28091 (code=killed, signal=ILL)
> 
> Apr 18 18:11:33 LS441D2CE systemd[1]: jellyfin.service: Service RestartSec=100ms expired, scheduling restart.
> Apr 18 18:11:33 LS441D2CE systemd[1]: jellyfin.service: Scheduled restart job, restart counter is at 6.
> Apr 18 18:11:33 LS441D2CE systemd[1]: Stopped Jellyfin Media Server.
> Apr 18 18:11:33 LS441D2CE systemd[1]: jellyfin.service: Start request repeated too quickly.
> Apr 18 18:11:33 LS441D2CE systemd[1]: jellyfin.service: Failed with result 'signal'.
> Apr 18 18:11:33 LS441D2CE systemd[1]: Failed to start Jellyfin Media Server.

> 

Hope anyone could help me

**Comment by telans** [comment]
If you're still having this issue, you need to post logs from jellyfin itself rather than from systemd
