### ISSUE TITLE
Allow users to make custom UIs

### ISSUE THREAD

**Issue by Essasetic** [jellyfin/jellyfin#292]
This would be a game changer for the software as it would make it more appealing and more friendly (in some cases). If someone replicated the Netflix UI (for example) then that would make the average Emby user want to switch because it looks more appealing and more friendly.

**Comment by sparky8251** [comment]
Is this for the web UI, a particular client, or everything?

**Comment by Essasetic** [comment]
Everything (if possible). Mainly because you can customise it so it's optimal for whatever device you go on.

**Comment by sparky8251** [comment]
In that case, would you want UIs synced by user account across all apps or set individually for each?

Same theme (but designed for different screen sizes) would require all apps to be rewritten to support the same kind of UI framework.

Being able to set a theme for each app would just require each app to be able to handle themeing. The web UI already can (how extensive I'm unsure) and that's the only one in this repo. Might want to open companion issues in each apps repos if that's the case.

**Comment by Essasetic** [comment]
@sparky8251 I do think there should be an option to turn on synchronization of all accounts/apps or turn it off and set it manually for each user. However I understand a feature of this caliber probably won't make it into Jellyfin for quite a while. But yeah I'll open up the companion issues with the apps soon.
