### ISSUE TITLE
Review Use of "\d" in regexes

### ISSUE THREAD

**Issue by mark-monteiro** [jellyfin/jellyfin#2923]
using `\d` n regexes does not perform as expected, and in many cases `[0-9]` should be preferred (as discovered [here](https://github.com/jellyfin/jellyfin/pull/2915#discussion_r410921281)).

* [x] Review existing uses of `\d` and replace with `[0-9]` where appropriate
* [ ] Consider adding this to the docs somewhere. Not sure where this would be appropriate to document, perhaps some discussion is needed here

**Comment by d-pizarro** [comment]
More Info...

From: https://en.wiktionary.org/wiki/%E0%A9%A9
੩ Represents the number 3 (three) in the Gurmukhi script.

From: https://www.rexegg.com/regex-quickstart.html
Character | Legend | Example | Sample Match
-- | -- | -- | --
\d | Most engines: one digitfrom 0 to 9 | file_\d\d | file_25
\d | .NET, Python 3: one Unicode digit in any script | file_\d\d | file_9੩

**Comment by ATahma** [comment]
This issue can be closed since #5142 has been merged
