### ISSUE TITLE
Unable to enable NVidia NVENC H/W Acel.

### ISSUE THREAD

**Issue by ooobii** [jellyfin/jellyfin#2924]
**Describe the bug**
This server will be doing a few more things than it is probably supposed to, and with a good, low power GPU like a 1050, I thought I could take some workload off of the CPU and give it to the card instead. Unable to enable NVIDIA-based hardware acceleration on Windows Server 2019 Essentials w/NVIDIA drivers.

**System (please complete the following information):**
 - OS: Windows Server 2019 Essentials
 - Hardware: Intel i7-3770 (4C/8T) @ 3.4GHz; 8GB DDR3 @ 1866MHz; NVidia GTX 1050 2GB
 - Virtualization: None (Service-based installation);
 - Clients: Browser, Roku, Google Chromecast
 - Browser: Chrome 81.0.4044.113
 - Jellyfin Version: 10.5.4
 - Playback: Transcode
 - Installed Plugins: None
 - Reverse Proxy: None
 - Base URL: None
 - Networking: Host
 - Storage: Local RAID Array

**To Reproduce**
1. Install Jellyfin as service (use local system account) on Windows Server 2019. Configure all other settings as default.
2. Login to local administration dashboard. Navigate to Server > Playback.
3. Under "Hardware Acceleration:," select 'Nvidia NVENC'.
5. Check all encoding options.
4. Click "Save" at bottom of page, displayed with "Hardware Acceleration" warning about possible instability. Click "Got It".
5. Dialog saying "There was an error processing the request. Please try again later" appears.

**Expected behavior**
Jellyfin should be loading the Nvidia NVENC library from the driver's installation base. It has worked before (this version, this OS), not sure what has changed!

**Logs**
[I'm not sure where the best logs to pull would be]

**Screenshots**
Windows Version:
![image](https://user-images.githubusercontent.com/60083197/79694207-e9c6f400-823c-11ea-90bb-5f58ae3e3b12.png)

Driver Installation Details w/ Versioning of official download:
![image](https://user-images.githubusercontent.com/60083197/79694252-33afda00-823d-11ea-8065-35969833c948.png)

Transcoding settings (original):
![image](https://user-images.githubusercontent.com/60083197/79694729-2e07c380-8240-11ea-947c-6b1fb867d677.png)

Transcoding settings (proposed changes):
![image](https://user-images.githubusercontent.com/60083197/79694778-922a8780-8240-11ea-85a6-38bb92f5ffa3.png)

Error Dialog (with "Saved Changes" notif?):
![image](https://user-images.githubusercontent.com/60083197/79694792-a53d5780-8240-11ea-9a6b-c9282fb15f2c.png)
Settings do not apply after a refresh of the Transcoding settings page.

**Comment by nyanmisaka** [comment]
I haven't tested NVENC in the server version of Windows but at least it is available on Windows 10 Pro. Can I have your ffmpeg log?

**Comment by ooobii** [comment]
> I haven't tested NVENC in the server version of Windows but at least it is available on Windows 10 Pro. Can I have your ffmpeg log?
>)
Thanks for your fast reply! The only logs I have available are the general "log_*" files (even after playing something). But, at the time of the error occurring through the web interface, this line shows up in the log:
`[2020-04-19 13:43:37.712 -04:00] [ERR] [60] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "C:\ProgramData\Jellyfin\Server\transcodes does not exist". URL: "http://localhost:8096/media/System/Configuration/encoding"`

Maybe I need to enable additional logging somehow?

**Comment by ooobii** [comment]
Sorry, closed issue by mistake.

**Comment by ooobii** [comment]
Played something with a different file type, here is my ffmpeg log (attached)
[ffmpeg-transcode-394e8caf-a005-48a9-8279-bbd1a7778984.txt](https://github.com/jellyfin/jellyfin/files/4499858/ffmpeg-transcode-394e8caf-a005-48a9-8279-bbd1a7778984.txt)

**Comment by ooobii** [comment]
I played a file with a different encoding, and an ffmpeg log generated (attached, redacted IP & host name)
[ffmpeg-transcode-394e8caf-a005-48a9-8279-bbd1a7778984.txt](https://github.com/jellyfin/jellyfin/files/4499861/ffmpeg-transcode-394e8caf-a005-48a9-8279-bbd1a7778984.txt)

**Comment by nyanmisaka** [comment]
From this log I can find that you have not enabled hardware acceleration, is playback normal at this time?

**Comment by ooobii** [comment]
Yes. playback is normal, and the process is utilizing CPU resources.
I actually was able to fix the issue by changing hardware encoding settings _after_ first playing video that required the 'ffmpeg' encoder. 

I think that directories required by the hardware transcoding settings page are not created until the 'ffmpeg' encoder is initialized/utilized for the first time on the server, judging by the error posted in the general log file before the attached ffmpeg log.

**Comment by nyanmisaka** [comment]
Please create these two folders and try to save the HWA settings again.

```
cmd
mkdir -p C:\ProgramData\Jellyfin\Server\transcodes
mkdir -p C:\ProgramData\Jellyfin\Server\metadata
```

Same issue https://github.com/jellyfin/jellyfin/issues/2854

**Comment by ooobii** [comment]
I think that the directories were created when ffmpeg actually ran for the first time, because cmd says the directories already exists:
![image](https://user-images.githubusercontent.com/60083197/79695794-cd2fb980-8246-11ea-98c8-fbc8577dd646.png)

(sorry for so many comment edits, commenting as I troubleshoot myself) In my last comment, I stated the settings saved after the ffmpeg encoder was utilized, but now playback is broken with hardware encoding enabled.

**Comment by nyanmisaka** [comment]
Can I have a ffmpeg log when using NVENC? It should include `h264_nvenc`.

**Comment by ooobii** [comment]
Playback is broken with NVENC 😢 In the browser, I get an error in plaintext that says:
`Value cannot be null. (Parameter 'path')`

**Comment by ooobii** [comment]
Interestingly enough, after enabling hardware encoding w/ NVidia NVENC and restarting the service, everything is working as expected!

I'm still not sure what a root cause could be, but being this isn't a normal use case, I don't think it's a big deal. Thanks for letting me bounce off you, I hope to be able to contribute once I learn my way around the project structure 😄

**Comment by nyanmisaka** [comment]
It was great to see that the problem was solved. The root of the problem may be that Jellyfin did not find the transcodes path when it was first started, and somehow it was not possible to resolve the HWA issue until after transcoding once and restarting.

**Comment by ooobii** [comment]
Wouldn't be a bad idea to have the server/web controller create these directories when the server switches to & from transcoding modes. I'd make a pull request if I knew where to start looking 😞
