### ISSUE TITLE
Videos with undefined audio

### ISSUE THREAD

**Issue by fabianski7** [jellyfin/jellyfin#2947]
**Describe the bug**
Many of my videos have not defined the language of the audio; the same for subtitles. They appear with "Undefined". And it often has the same name for different languages, l[ike this one](https://upload.vaa.red/sNwVX#DOtF6hSePbdU8uiJiLuSyy03lapUo7cX) (both are displayed as "Und AAC stereo Default")..

This is not a problem with Jellyfin, but since they are not identified through a specific language then it is not possible to choose a default option for the whole series. So I have to change the language and subtitles every time I start a new episode.

Since there is only one subtitle available in the folder, using the "always play subtitles" option works, I would say, 80% of the time. It's not ideal but it's not bad either.
The real problem is the audio of the video, it always has to change.

**System (please complete the following information):**
 - OS: Archlinux with kernel 5.6.4
 - Clients: Browser and Android
 - Browser: Ungoogled Chromium 81.0.4044.92
 - Jellyfin Version: 10.5.4-1 (AUR repository)
 - Playback: Direct play
 - Installed Plugins: none
 - Storage: local

**To Reproduce**
1. A video file without the languages set 
2. Try to make one of these languages the standard for all the other episodes in the series
3. So you fail

**Expected behavior**
So my suggestion would be that jellyfin has an option to force the second language of the audio available in the file. Since not all series have this problem, then it could be applied only to a specific series, not globally.

**Additional context**
I'm sorry I didn't go into enough technical detail on this problem. I have little knowledge of it.
*As I don't think this is exactly a feature request, so I thought the best place to report this would be here at github itself.

**Comment by Artiume** [comment]
Perhaps this PR might fix the issue https://github.com/jellyfin/jellyfin/pull/2788

**Comment by fabianski7** [comment]
any chance of this pull request being included in the next update?

**Comment by Artiume** [comment]
It'll be available in 10.6. If you want to build the PR to see if it fixes your issue, If it doesn't, maybe the PR could be tweaked to fix your issue.

**Comment by fabianski7** [comment]
I forked the repository and applied the pull request, but it doesn't seem to solve this problem I described.

The audios still have the same name (screenshot [1](https://upload.vaa.red/hGDBH#4zYRzrQGkM9x78lH6E2C1ZXeUpL3lZyF) and [2](https://upload.vaa.red/FBWAF#Yk6HS5Hdvp0u4yu13Qe7nmtuUv8Qnslp)) and you can't choose an option to be the default. The first option is always the one jellyfin uses.

**Comment by ThatNerdyPikachu** [comment]
@fabianski7 Can you give me a mediainfo of the files?

**Comment by fabianski7** [comment]
[Screenshot
](https://upload.vaa.red/2wceYd#cDQi3l9yvJZjASIS1icn0FasZc2COoaz)
**Video**
```
Title 720P H264
Codec H264
Codec tag avc1
AVC Yes
Profile High
Level 40
Resolution 1278x720
Aspect ratio 16:9
Interlaced No
Framerate 23.973648
Bitrate 1398 kbps
Bit depth 8 bit
Pixel format yuv420p
Ref frames 1
NAL 4
```

**Audio**
```
Title Und AAC stereo Default
Language und
Codec AAC
Codec tag mp4a
Profile LC
Layout stereo
Channels 2 ch
Bitrate 127 kbps
Sample rate 48000 Hz
Default Yes
```
**Audio**
```
Title Und AAC stereo Default
Language und
Codec AAC
Codec tagmp4a
Profile LC
Layout stereo
Channels 2 ch
Bitrate 159 kbps
Sample rate 48000 Hz
Default Yes
```

**Subtitle**
```
Title Undefined
Codec SRT
Default No
Forced No
External Yes
```

**Comment by ThatNerdyPikachu** [comment]
> [Screenshot
> ](https://upload.vaa.red/2wceYd#cDQi3l9yvJZjASIS1icn0FasZc2COoaz)
> **Video**
> ```
> Title 720P H264
> Codec H264
> Codec tag avc1
> AVC Yes
> Profile High
> Level 40
> Resolution 1278x720
> Aspect ratio 16:9
> Interlaced No
> Framerate 23.973648
> Bitrate 1398 kbps
> Bit depth 8 bit
> Pixel format yuv420p
> Ref frames 1
> NAL 4
> ```
> 
> **Audio**
> ```
> Title Und AAC stereo Default
> Language und
> Codec AAC
> Codec tag mp4a
> Profile LC
> Layout stereo
> Channels 2 ch
> Bitrate 127 kbps
> Sample rate 48000 Hz
> Default Yes
> ```
> **Audio**
> ```
> Title Und AAC stereo Default
> Language und
> Codec AAC
> Codec tagmp4a
> Profile LC
> Layout stereo
> Channels 2 ch
> Bitrate 159 kbps
> Sample rate 48000 Hz
> Default Yes
> ```
> 
> **Subtitle**
> ```
> Title Undefined
> Codec SRT
> Default No
> Forced No
> External Yes
> ```

Can you give me a [Mediainfo](https://mediaarea.net/en/MediaInfo) dump instead? (This will let me see more data than Jellyfin currently shows)

**Comment by fabianski7** [comment]
[here](https://bin.privacytools.io/?f1185f5e8ae3415a#zvVNrDu8GbFAXUvZDOoh23xHqX6EgGrkNOAbeq9ArIo=)

**Comment by ThatNerdyPikachu** [comment]
It doesn't look like there are embedded titles in these tracks. What are you wanting it to show that it isn't?

**Comment by fabianski7** [comment]
Maybe I didn't explain this bug in the best way. But what happens is that the two audios in the video have the same name and apparently the file doesn't tell the language of this audio either. So I can't set a default language for the episodes in this series, since jellyfin can't differentiate the two audio sources.

Sometimes it even treats the two sources as if they were the same. So even if you change the audio source it still plays in the previous language (this happened in the android app)

**Comment by fabianski7** [comment]
the problem with the subtitles has happened few times so far (actually, since I reported the bug it hasn't happened anymore, lol)

**Comment by Artiume** [comment]
the subtitle reset should be fixed :)

**Comment by fabianski7** [comment]
I used MediaInfo to compare the information with another file and realized these two differences compared to the file we were discussing.

```
Audio #1:
Title: English
Language: English

Audio #2
Title: Portuguese
Language: Portuguese
```

This complements my previous explanation, jellyfin doesn't seem to work very well when the file doesn't provide this information.

**Comment by fabianski7** [comment]
I uploaded the two files into [this folder](https://mega.nz/folder/oZNnlCwA#5QgVUGE9VU9zRNKNAaFTTQ)

**Comment by ThatNerdyPikachu** [comment]
> I realized that it's possible to define the audio track and subtitle individually for each episode in the most recent version of jellyfin and I thought the same could be done for the whole series or for a specific season, so I closed the issue. But I was wrong.

How exactly do you do this from the web ui? Can't check my own instance right now, but I'll probably write a script to do this for myself for an entire season (and I'll open source it!)

**Comment by fabianski7** [comment]
when accessing a series, simply click on the [information icon (i)](https://upload.vaa.red/xwksK#vQbXkWNWGLZHJSPBKO2BXTmjZRd6AXRT) in the episode
