### ISSUE TITLE
Distorted Audio in IceCat

### ISSUE THREAD

**Issue by jfrederickson** [jellyfin/jellyfin#2948]
**Describe the bug**
I'm experiencing distorted audio when attempting to play video using the web player in IceCat (a fork of Firefox). Voices sound extremely deep and the audio crackles. Audio works fine on other pages in IceCat, and Jellyfin playback works fine in Chromium on the same machine.

**System (please complete the following information):**
 - OS: Guix System
 - Clients: Browser
 - Browser: IceCat 68.7.0esr
 - Jellyfin Version: 10.5.4-1
 - Playback: Transcode(?)
 - Installed Plugins: AudioDB, Kodi Sync Queue, MusicBrainz
 - Reverse Proxy: Apache
 - Base URL: /jellyfin
 - Networking: Host
 - Storage: Local

**To Reproduce**

1. Go to Jellyfin web UI in IceCat
2. Click on a video to start streaming playback

**Expected behavior**

Video plays with correct-sounding audio

**Additional context**
When I play these files in Chromium, the quality is shown as "Auto - Direct", whereas in IceCat it's shown as "Auto 1080p - 60 fps". I'm not sure if that means that Jellyfin is trying to transcode when played in IceCat.
[MediaInfo for the file in question](https://github.com/jellyfin/jellyfin/files/4507562/mediainfo.txt)

**Comment by Artiume** [comment]
When you watch the video, hit the Playback Stats,thatll give you more info. It sounds like it's Direct Steaming (audio and container only). I wonder what's causing the quality issue. For more reading, check out the docs. https://jellyfin.org/docs/general/clients/codec-support.html

It looks like it's transcoding aac audio. To see if it's a false positive, disable audio transcoding in your user admin profile. Post the ffmpeg logs that are generated. If not do, then it Direct Played.
