### ISSUE TITLE
Check warning count as part of CI process

### ISSUE THREAD

**Issue by mark-monteiro** [jellyfin/jellyfin#2954]
We should add a check to the CI process that counts the number warnings in the build and fails if it is above some threshold 'N'. The threshold should be in a file committed to the repository and reduced on each PR so that over time we reduce the number of warnings to zero.

Also proposed is that this CI check would function to replace a lot of the manual reviews of styling issues in PRs. Basically, as long as the number of warnings goes down its fine to ignore other minor styling issues in the code review.

**Comment by sevenrats** [comment]
Moved to https://github.com/jellyfin/jellyfin-meta/discussions/59
