### ISSUE TITLE
Do not Automatically Launch Web Browser

### ISSUE THREAD

**Issue by mark-monteiro** [jellyfin/jellyfin#2959]
As discussed in https://github.com/jellyfin/jellyfin/pull/2943#issuecomment-616829984, launching the web browser should not be done by the server, but should be handled by the associated windows or macOS wrapper application.

* Remove the logic to auto-launch the web browser from the server (`StartupWizard.cs` `BrowserLauncher.cs`, etc)
* Remove the associated configuration properties `AutoRunWebApp` and `NoAutoRunWebApp`
* Update the Visual Studio launch profile to automatically launch the browser to make things easy for developers
* Update the "Server is loading..." text response [in HttpListenerHost](https://github.com/jellyfin/jellyfin/blob/master/Emby.Server.Implementations/HttpServer/HttpListenerHost.cs#L523) to instead return a simple HTML page with some basic styling and a loading message. This doesn't need to be too fancy, it can be improved in a follow-up PR later. The HTML page should also contain some JavaScript to poll the server until the server has finished loading and then refresh the page.

  This would be a good opportunity to remove this loading message functionality from from HttpListenerHost entirely and move it to a middleware handler in the new ASP pipeline
* Update the Windows/macOS wrapper to automatically launch the browser. These would be separate PRs in their respective repositories and can be completed by other devs. Since the server now has a proper loading page, they should be able to ping the server until they get any response and then launch the browser (instead of waiting for loading to complete)

**Comment by anthonylavado** [comment]
@mark-monteiro Did you mean macOS?

---

So I missed this entirely.

Right now the Windows and macOS tray/wrappers are not as fancy as you might think. At their heart, they launch/stop a Jellyfin process running in the background. They do have some options on what arguments to start the server with (like `--noautorunwebapp`) depending on user settings.

With this change, things become more difficult. How do I know when the server is finished startup? It's not just as easy as launching it right after the server process, because I could be too early/fast. I might end up with a "localhost not found". Even if I check for a page, the server does have its own "Server is loading, please wait…" page before it's ready. I imagine in some complex environments, this page may be up longer than 1 or 2 seconds, so a delayed browser start won't work reliably (and might make the user feel like Jellyfin isn't working, but I suppose that already happens).

This will of course add more code to the wrappers as well. I know the Windows one is just some more C#/.NET work, but since I can barely hack together the macOS one, it'll likely stay as a manual browser launch there for the foreseeable future.

**Comment by anthonylavado** [comment]
I should note - both wrappers already have a menu item to launch the web UI. It just kicks to the shell and says "open this URL with your default browser". So that functionality is there at least.

I guess the concerns come with:
*first time setup
* whether or not this is a behaviour people expect (need to check how Emby and Plex do this)

**Comment by mark-monteiro** [comment]
@anthonylavado yes, macOS. This came up as a suggestion as a result of a code review with @Bond-009 and @dkanada, so maybe they have some other ideas. But I agree that at the very least we need to check whether our console users would prefer to have this functionality removed, or the default changed to not launch the app.

**Comment by anthonylavado** [comment]
Talking to @Bond-009 in chat, I'll make it just not automatically launch the web UI for now, and users can open it with the menu item if needed. This will still suck for first time setup though.

**Comment by mark-monteiro** [comment]
Here's a potential solution: Replace the "server is loading..." message with a proper HTML page response that has a very basic loading page. The page can include some basic styling and a small amount of JavaScript to ping the server and refresh the page when it is ready.

Then the client wrappers should be safe to open up a browser immediately and users will also get an even better loading experience than we have now.

**Comment by mark-monteiro** [comment]
Anyone in @jellyfin/backend see issues with the proposed solution in my comment above? If I get some thumbs up I'll remove the `discussion needed` tag. This could be a good task for one of the newer devs to pick up, I think it's a relatively isolated piece of functionality

**Comment by JustAMan** [comment]
I am fine with that page. It makes sense for other use cases as well.

**Comment by mark-monteiro** [comment]
Okay, the issue description is updated with the new approach and I've updated the labels again. Maybe a bit of a stretch now for the `good first issue` label but I've tried to add as much detail as possible to make it easier :)

If there's any holes in the approach or description let me know and I can update

**Comment by avokado1337** [comment]
I have no idea if I should have ever started to tackle this issue as my first ever, but I thought I should at least try after I saw the "good first issue" label. I am deeply sorry if this created any inconvenience for anyone.

About removing the logic of auto-launching browser, as far as I understand after the building is complete browser should not be started at all? Or does it mean that browser should not be started from the server? I did edit the `StartupWizard.cs` and `BrowserLauncher.cs`, but after the build browser still opened up with the main page of Jellyfin. I am building nowebclient version. 

Thanks in advance!

**Comment by mark-monteiro** [comment]
@avokado1337 Yes, we _don't_ want the server to launch the browser at on normal startup. If nothing has changed since I made this issue, this functionality can be removed by updating StartupWizard and BrowserLauncher (as you mentioned you did already).

However, when running from an IDE (Visual Studio, or VS Code), we _do_ want the browser to launch after building, for convenience for developers. In Visual Studio this is controlled by the IDE settings file [launchsettings.json](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-3.1#development-and-launchsettingsjson) (there is similar functionality for VS Code, but I am not familiar with it).

Maybe your browser is still being launched by the IDE and not the server code?

**Comment by mark-monteiro** [comment]
@crobibero I can see the first three points from this issue were implemented in #4164, but have the last two points also been implemented?

**Comment by crobibero** [comment]
> 
> 
> @crobibero I can see the first three points from this issue were implemented in #4164, but have the last two points also been implemented?

Got trigger happy, I don't think the last two points have been implemented

**Comment by dkanada** [comment]
Number four should probably be opened in the respective repositories.

**Comment by Coderdude112** [comment]
Are there any updates on this issue? Jellyfin opening chrome isn't fun

**Comment by crobibero** [comment]
> 
> 
> Are there any updates on this issue? Jellyfin opening chrome isn't fun

Jellyfin doesn't open the browser as of 10.7. This issue is still open because there are remaining items to fix in this issue.

**Comment by Coderdude112** [comment]
Gotcha, Thanks for the hyper quick response internet stranger!

**Comment by soer7022** [comment]
Is this issue still relevant? I would like to work on it for Hacktoberfest :)

**Comment by cvium** [comment]
I don't think this is a good hacktoberfest issue

**Comment by soer7022** [comment]
Alright, thanks for the headsup 👍

**Comment by berneymark** [comment]
I hope this issue gets resolved, I just host files from my PC for my flatmates and I in the living room. It's a terrible experience having Firefox jump in my face every single time I reboot my PC. At least a toggle to turn it off would be lovely.

**Comment by Bond-009** [comment]
Closing as fixed

**Comment by TheOverpassArsonist** [comment]
At the risk of necroing, why was this closed as fixed? For me on linux everytime I start the jellyin flatpak from the commandline I still get the browser automatically opening, should this not be happening?

**Comment by Puhpine4915** [comment]
this is definitely still a thing unfortunately

**Comment by Bond-009** [comment]
Blame the flatpak, not us.
https://github.com/flathub/org.jellyfin.JellyfinServer/blob/master/data/jellyfin.sh#L71C8-L79

**Comment by AFulgens** [comment]
If anybody is looking for the solution for Flatpak opening automatically, it's "fixable" via this issue https://github.com/flathub/org.jellyfin.JellyfinServer/issues/500 and then this FAQ link https://github.com/flathub/org.jellyfin.JellyfinServer/wiki/FAQ-%E2%80%94-Frequently-Asked-Questions#how-to-launch-the-application and it's basically starting Jellyfin via

```
flatpak run --command=jellyfin org.jellyfin.JellyfinServer
```

(adding the command option bypasses the sh linked above by Bond-009, avoiding @'ing them to avoid an unnecessary notification towards them)
