### ISSUE TITLE
Delete episodes after watched Plugin

### ISSUE THREAD

**Issue by SenorSmartyPants** [jellyfin/jellyfin#296]
This is a feature request for an plugin to provide missing delete after watched functionality. Plex provides this feature, but afaik Emby never has.

- Plugin would add UI to set per series rules for when episodes should be deleted.
- Set number of days/weeks after watching when episode will be deleted. I would like the ability to either configure this list in plugin settings. Some might like only after 1 day or 1 week as options. Others (such as myself) would like longer options, out to 5 weeks.
- List of users per series that need to have watched episode before it will be deleted. Have an "All" option to handle any users added after series is configured. List all users in the system with a checkbox for each user.

**Comment by szmania** [comment]
Yes please.

**Comment by JustAMan** [comment]
Major feature requests should go to https://features.jellyfin.org/

**Comment by spupuz** [comment]
please need it

**Comment by serzhshakur** [comment]
you can use Sanitarr - a tool to automatically delete watched items

https://github.com/serzhshakur/sanitarr
