### ISSUE TITLE
No trailers found. Install the Trailer channel to enhance your movie experience by adding a library of internet trailers

### ISSUE THREAD

**Issue by Gabriel-p** [jellyfin/jellyfin#2963]
**Describe the bug**
What is the Trailer channel?

**System (please complete the following information):**
 - Jellyfin Version:  10.4.3

**To Reproduce**

1. Go to 'Movies'
2. Click on 'Trailers'

**Expected behavior**
Trailers for the movies should show, or a clear way to obtain them should be displayed. As it is, it tells you to install a "Trailers channel" and I have no idea what that is (an old plugin that was removed?).

**Comment by dennis800121** [comment]
Please! I would also like an answer to this.

**Comment by crobibero** [comment]
It looks like Emby has a Trailers plugin for premium members, so I'd consider this to be a feature request

**Comment by crobibero** [comment]
There is now a trailer plugin https://github.com/crobibero/jellyfin-plugin-tmdb-trailers
You can add it from my repo (https://repo.codyrobibero.dev/manifest.json)

**Comment by mike-feldmeier** [comment]
This bug was erroneously closed.  This report is clearly stating that the trailers subsection of the movies section is empty and stating that the trailers channel needs to be installed, but there is none to be installed.  The plugin proposed by crobibero, though very nice, doesn't actually seem to address the point of this bug.  If the plugins approach of adding a trailer icon to each movie is the way forward, fine, it seems to work well (for me anyway).  In that case, the trailers subsection should be removed to eliminate the confusion it is causing.

**Comment by mevouc** [comment]
I can confirm @mike-feldmeier's comment. The plugin provided by @crobibero does not change the behavior of the Trailers section in Movies library. The same message is displayed as before, without telling the user what to do to fix it.

The issue should not have been closed.

**Comment by GlassedSilver** [comment]
What the heck... I thought I was going cray cray. So... it's not even supplied? :/

**Comment by cvium** [comment]
I cannot confirm. I agree that the message might be a little odd, but installing the plugin by crobibero (https://github.com/jellyfin/jellyfin/issues/2963#issuecomment-683123395) gives me this view:

![image](https://user-images.githubusercontent.com/675118/110250359-301f6180-7f7b-11eb-8d08-dd2d7635a3f7.png)

**Comment by StuartMorrisAU** [comment]
https://github.com/crobibero/jellyfin-plugin-tmdb-trailers is now archived, so it appears there's no longer a supported trailers channel.

**Comment by crobibero** [comment]
I don’t think there will be another as YouTube has been making it difficult for third-party apps to download video… I guess there could be a plugin that uses youtube-dl to stream but I think that is out of scope for the server to support

**Comment by michaelkrieger** [comment]
My script which sorts may movies uses youtube-dl to download to a trailer.mp4 file in each folder.  Some have them, and some don’t, particularly depending on availability.  These show, for each movie, as the trailers button.

We could arguably show the trailers that we do have in the Trailers section.

**Comment by ismay** [comment]
Or, instead of trying to retrofit functionality into an area that apparently is a holdover from the Emby code, Jellyfin could remove the trailers section. Then if it turns out that there is a clearly delineated idea and need for a trailers section in the UI it could be developed like any other feature. I'd rather not have it than have it be broken or quickly implemented to fill a gap in the UI.

**Comment by ismay** [comment]
Yeah sure it sounds like a perfectly fine idea, but I'd just remove menu item until the functionality is actually there.

**Comment by Potplanty** [comment]
Still wondering why the hell this trailers section still exists, still unworking, over a year and a half later. If it's not going to be addressed, just remove the entire section.

**Comment by dannymichel** [comment]
> Still wondering why the hell this trailers section still exists, still unworking, over a year and a half later. If it's not going to be addressed, just remove the entire section.

Feb 2022, section still there, still not working, no plugin

**Comment by ArchemedIan** [comment]
> > FYI the plugin still works, and was updated this year at least. it should not be removed imo. just dont use it if you dont want trailers. the message could be changed to be more accurate like maybe "you need a trailer provider plugin" instead of channel
> 
> If it still works then the Jellyfin team should add a link inside Jellyfin that tells you where to get it. I'm still unsure what is compatible. Mind linking whatever it is that you're using so we aren't still in the dark for another two years?

https://github.com/crobibero/jellyfin-plugin-tmdb-trailers, the same one mentioned in the beginning of this thread, except I'm using the manifest in the readme not the one in the thread comment. 

the channel still looks weird if you go to the trailer section of movies, but on the home screen it looks and works fine:

![image](https://user-images.githubusercontent.com/105951210/198096222-07b3ab27-f664-4c0d-a6a2-7b9d2d420b82.png)


![image](https://user-images.githubusercontent.com/105951210/198096506-9f6e0eff-8514-47b4-a68c-1a45b002a920.png)

**Comment by ArchemedIan** [comment]
> If it still works then the Jellyfin team should add a link inside Jellyfin that tells you where to get it. 

respectfully disagree. if they did that then if the developer dies or for whatever reason stops developing the plugin, Like was the case for awhile, then they'll be linking to a dead plugin and you'll then complain as well. 

it's simpler to let the user figure things out for themselves

**Comment by crcfail** [comment]
Is there some obvious reason I'm missing as to why we can't just CHOOSE which tabs are shown in each library, so I can remove the trailer tab? (ie. Movies, Suggestions, Trailers, Favorites, Collections, Genres)

**Comment by GlassedSilver** [comment]
> > If it still works then the Jellyfin team should add a link inside Jellyfin that tells you where to get it.
> 
> respectfully disagree. if they did that then if the developer dies or for whatever reason stops developing the plugin, Like was the case for awhile, then they'll be linking to a dead plugin and you'll then complain as well.
> 
> it's simpler to let the user figure things out for themselves.

Why not just link and warn about the potential "risk".

How is letting the user figure out EVERYTHING without guidance simpler than just telling the user which options exist? You got it done in a one-liner, surely JF could do the same job...

This approach of "let the user figure it out" is exactly what typically holds back FOSS software.
A good UI gives you options and explanations when needed or useful whilst not forcing you to open up a manual for basic functionality.

**Comment by Maltavius** [comment]
IMO the Trailer-tab should just list all media that is in a Folder named Trailer in all libraries or ends with -trailer.<format>
Use the Poster and title from the parent item to make it look good.

**Comment by ArchemedIan** [comment]
> How is letting the user figure out EVERYTHING without guidance simpler than just telling the user which options exist?

Well I suspect it isn't, for you, the user that has to actually dust off and use their brain to solve a problem. 

> A good UI gives you options and explanations 

Do I need to call the police and report a man holding a gun to your head saying "use jellyfin," or are you gonna be ok finding some other free program with a "good ui"

> You got it done in a one-liner, surely JF could do the same job...

so make a pull request with the changes you want. if it makes so much sense, I'm sure it will be merged in no time.

this is not Netflix. this is not customer support, we are not reading from a script in a call center in India. this is a free open source program, you're free to make any changes you want to, and build it yourself. the gihub issues are not where you air your grievances, not for your opinions, its where you report a bug, not get help with a bug, report it. the issues are for the benefit of the DEVS OF JELLYFIN not you. most of those benefits just happen to normally trickle down. 

>This approach of "let the user figure it out" is exactly what typically holds back FOSS software.
no, this approach of "the original should fix every problem," rather than contributing yourself by fixing the problem yourself, and the dev abandoning the project like jellyfin was for years, is what holds back FOSS software. ignorant, entitled users, who feel no responsibility to understand how any software they use actually works, and entitlement to fixes for free, is the problem.

**Comment by ArchemedIan** [comment]
> IMO the Trailer-tab should just list all media that is in a Folder named Trailer in all libraries or ends with -trailer. Use the Poster and title from the parent item to make it look good.

one could make a trailer provider plugin that does that, which is why its designed this way. maybe try fiver to get a DEV to make one for you.

**Comment by jellykells** [comment]
> I don't care how many likes your immature comment farms from non-devs, you're not entitled to free work. deal with it. I think you should stick to your little bash and docker projects until you learn a something other than a scripting or markup language.

This is pretty hilarious considering your repos are almost exclusively AutoHotkey scripts :joy_cat: 
Maybe you should take your unproductive toxicity somewhere else

**Comment by jellykells** [comment]
On the topic of this issue, having to search the issue tracker for "No trailers found" in order to find out how to actually get working trailers is pretty unfriendly.
The docs at https://jellyfin.org/docs/general/clients/web-config#youtube-trailers also don't seem to be very enlightening.

**Comment by mevouc** [comment]
> On the topic of this issue, having to search the issue tracker for "No trailers found" in order to find out how to actually get working trailers is pretty unfriendly. The docs at https://jellyfin.org/docs/general/clients/web-config#youtube-trailers also don't seem to be very enlightening.

I strongly agree with this. If no changes are to be made inside Jellyfin and people are getting toxic about documenting it in the UI, at least give more context and info in the jellyfin.org docs is a good idea... it's good to have a simple way to disable it, but it probably be a good point to have a line or two about the fact that it's meant to work with external plugins. The way this docs section is currently written, it feels like it's something that should just work but is disabled for a reason that is not explained.

**Comment by ArchemedIan** [comment]
>  considering your repos are almost exclusively AutoHotkey scripts 

I'm not the one here crying some code isn't how I like it, begging people to change it. My code makes money, I'm contractually obligated to keep it off GitHub.
