### ISSUE TITLE
Files with embedded PGS subtitles fail to play during VAAPI transcode

### ISSUE THREAD

**Issue by cryptobank** [jellyfin/jellyfin#2964]
**Media Info of the file**
General
Unique ID                                : 150349097641055732064262250740385071567 (0x711C2ED43A8372DB8B33D7ADD83C41CF)
Complete name                            : /run/user/1000/gvfs/smb-share:server=blob,share=video/Movies/Lawrence of Arabia/Lawrence.Of.Arabia.mkv
Format                                   : Matroska
Format version                           : Version 4
File size                                : 30.9 GiB
Duration                                 : 3 h 46 min
Overall bit rate                         : 19.5 Mb/s
Encoded date                             : UTC 2020-04-22 07:29:09
Writing application                      : mkvmerge v44.0.0 ('Domino') 64-bit
Writing library                          : libebml v1.3.10 + libmatroska v1.5.2

Video
ID                                       : 1
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L5.1@Main
Codec ID                                 : V_MPEGH/ISO/HEVC
Duration                                 : 3 h 46 min
Bit rate                                 : 19.3 Mb/s
Width                                    : 3 840 pixels
Height                                   : 1 744 pixels
Display aspect ratio                     : 2.2:1
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 10 bits
Bits/(Pixel*Frame)                       : 0.120
Stream size                              : 30.5 GiB (99%)
Default                                  : Yes
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709

Audio
ID                                       : 2
Format                                   : Opus
Codec ID                                 : A_OPUS
Duration                                 : 3 h 46 min
Bit rate                                 : 209 kb/s
Channel(s)                               : 6 channels
Channel layout                           : L R C Ls Rs Cb LFE
Sampling rate                            : 48.0 kHz
Frame rate                               : 50.000 FPS (960 SPF)
Compression mode                         : Lossy
Stream size                              : 338 MiB (1%)
Writing library                          : Lavc58.71.100 libopus
Language                                 : English
Default                                  : No
Forced                                   : No

Text
ID                                       : 3
Format                                   : PGS
Muxing mode                              : zlib
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Duration                                 : 3 h 35 min
Bit rate                                 : 21.6 kb/s
Count of elements                        : 3719
Stream size                              : 33.3 MiB (0%)
Language                                 : English
Default                                  : No
Forced                                   : No

**FFmpeg Logs**

/usr/lib/jellyfin-ffmpeg/ffmpeg -hwaccel vaapi -hwaccel_output_format vaapi -vaapi_device /dev/dri/renderD128 -i file:"" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -codec:v:0 h264_vaapi  -b:v 40003162 -maxrate 40003162 -bufsize 80006324 -profile:v high -level 41  -force_key_frames:0 "expr:gte(t,0+n_forced*3)" -g 72 -keyint_min 72 -sc_threshold 0 -filter_complex "[0:2]scale=3840:1636:force_original_aspect_ratio=decrease[sub];[0:0],hwdownload[base];[base][sub]overlay,format=nv12,hwupload" -start_at_zero -vsync -1 -codec:a:0 libmp3lame -ac 2 -ab 320000 -af "volume=2" -copyts -avoid_negative_ts disabled -f hls -max_delay 5000000 -hls_time 3 -individual_header_trailer 0 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/var/lib/jellyfin/transcoding-temp/transcodes/1adf981ff0b4fabd65bd5fba43ebac89%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/var/lib/jellyfin/transcoding-temp/transcodes/1adf981ff0b4fabd65bd5fba43ebac89.m3u8"

ffmpeg version 4.2.1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --disable-doc --disable-ffplay --disable-shared --disable-libxcb --disable-vdpau --disable-sdl2 --disable-xlib --enable-gpl --enable-version3 --enable-static --enable-libfontconfig --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libwebp --enable-libx264 --enable-libx265 --enable-libzvbi --arch=amd64 --enable-amf --enable-nvenc --enable-nvdec --enable-vaapi
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[matroska,webm @ 0x5616f3b9fd00] Could not find codec parameters for stream 2 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, matroska,webm, from 'file:/srv/Data/Video/Movies/Lawrence of Arabia/Lawrence.Of.Arabia.mkv':
  Metadata:
    encoder         : libebml v1.3.10 + libmatroska v1.5.2
    creation_time   : 2020-04-22T07:29:09.000000Z
  Duration: 03:46:15.02, start: -0.007000, bitrate: 19521 kb/s
    Stream #0:0: Video: hevc (Main 10), yuv420p10le(tv, bt709), 3840x1744 [SAR 1:1 DAR 240:109], 23.98 fps, 23.98 tbr, 1k tbn, 23.98 tbc (default)
    Metadata:
      BPS-eng         : 19301244
      DURATION-eng    : 03:46:15.020000000
      NUMBER_OF_FRAMES-eng: 325475
      NUMBER_OF_BYTES-eng: 32751848044
      _STATISTICS_WRITING_APP-eng: mkvmerge v44.0.0 ('Domino') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-04-22 07:29:09
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:1(eng): Audio: opus, 48000 Hz, 5.1, fltp
    Metadata:
      ENCODER         : Lavc58.71.100 libopus
      BPS-eng         : 209041
      DURATION-eng    : 03:46:15.015000000
      NUMBER_OF_FRAMES-eng: 678751
      NUMBER_OF_BYTES-eng: 354718357
      _STATISTICS_WRITING_APP-eng: mkvmerge v44.0.0 ('Domino') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-04-22 07:29:09
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:2(eng): Subtitle: hdmv_pgs_subtitle
    Metadata:
      BPS-eng         : 21644
      DURATION-eng    : 03:35:08.479000000
      NUMBER_OF_FRAMES-eng: 3719
      NUMBER_OF_BYTES-eng: 34925311
      _STATISTICS_WRITING_APP-eng: mkvmerge v44.0.0 ('Domino') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-04-22 07:29:09
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
[AVFilterGraph @ 0x5616f3d67080] No such filter: ''
Error initializing complex filters.
Invalid argument

**Server System (please complete the following information):**
 - OS: Debian Buster
- jellyfin/unknown,now 10.5.4-1 amd64 [installed]
- jellyfin-ffmpeg/unknown,now 4.2.1-7-buster amd64 [installed,automatic]
 
**Client System (please complete the following information):**
 - OS: Linux
 - Client: Web/Browser, 
 - Browser (if Web client): Chrome

**Comment by nyanmisaka** [comment]
I can confirm that this issue is on the Server side, and ffmpeg has no problem. Please give me some time to investigate. This problem occurs when using VAAPI and 4K transcoding to 4k and burning-in graphical subtitles.

**Comment by nyanmisaka** [comment]
I have located the issue. If the requested resolution is 4k, then `request.height/width, request.MaxHeight/MaxWidth` are somehow null, causing some filter commands to be missing. I will solve it in my PR.

**Comment by bloodsplatter** [comment]
> I have located the issue. If the requested resolution is 4k, then `request.height/width, request.maxHeight/maxWidth` are somehow null, causing some filter commands to be missing.
> I will try to solve it in my PR.

Which PR is this? I wanna follow it to keep updated.

**Comment by jaen** [comment]
I have also encountered this problem while running jellyfin from the `linuxserver/jellyfin:20200615-ls86` container.

**Comment by jaen** [comment]
PLS leave it alone bot. @nyanmisaka could you tell us why that PR was closed without merging? Was the issue fixed elsewhere? Was the fix not that easy?

**Comment by nyanmisaka** [comment]
> PLS leave it alone bot. @nyanmisaka could you tell us why that PR was closed without merging? Was the issue fixed elsewhere? Was the fix not that easy?

Hi! I think this issue should be fixed in JF 10.7.
#3940 was closed as it has been included in another PR.

**Comment by jaen** [comment]
@nyanmisaka sorry for taking so long to check this, but I think this works now for me.

The playback choppy, but I guess that's expected when the tonemapping is being done on the CPU. The subtitles disappear when I enable tonemapping, but I guess that's a separate issue (I guess I should file it?) and this one can be closed. Thanks for all the hard work!

**Comment by nyanmisaka** [comment]
Hey! Tonemapping on Intel will conflict with PGS burn-in for now. Will try to resolve it in the future.
https://github.com/jellyfin/jellyfin-meta/issues/1#issuecomment-739138464
