### ISSUE TITLE
Link to documentation on docker-hub page not correct

### ISSUE THREAD

**Issue by avpnusr** [jellyfin/jellyfin#2972]
**Description**

The hyperlinks on the docker-hub page of this project "https://hub.docker.com/r/jellyfin/jellyfin" are not correct. They lead to a "page not found" on readthedocs.io

I just noticed this today - sorry if this is not the correct way of reporting this!

Regards,

avpnusr

**Comment by PrplHaz4** [comment]
This probably belongs in jellyfin-docs and is a duplicate of https://github.com/jellyfin/jellyfin-docs/issues/253

**Comment by avpnusr** [comment]
@PrplHaz4 you are completely right - I close this
