### ISSUE TITLE
Episode marked as watched trough the API doesn't show up in the UI

### ISSUE THREAD

**Issue by wilmardo** [jellyfin/jellyfin#2973]
**Describe the bug**

As the title states, an episode marked as watched trough the API doesn't show up in the UI. A movie on the other hand works perfectly the same way.

**System (please complete the following information):**
 - OS: Linuxserver.io flavoured Debian(?)
 - Virtualization: Docker
 - Clients: Browser, Android
 - Browser: Firefox
 - Jellyfin Version: 10.5.4
 - Playback: Direct Play
 - Installed Plugins: none
 - Reverse Proxy: nginx-ingress
 - Base URL: none
 - Networking: Kubernetes
 - Storage: Ceph

**To Reproduce**

Mark an episode as watched with a POST to `Users/<uid>/PlayedItems/<episode_id>` and look in the UI at the item still being unwatched.

**Expected behavior**
The episode marked as watched in the UI

**Logs**
When I request the episode afterwards it returns played True in the UserData:
```
{
   "IsFavorite":False,
   "Key":"10201",
   "LastPlayedDate":"2020-01-27T21:11:43.6447906Z",
   "PlayCount":1,
   "PlaybackPositionTicks":0,
   "Played":True
}
```
But is still unwatched in the UI, I tried refreshing the library, restarting etc but to no avail.
The movies I marked as watched the same way are showing up as watched.

**Additional context**
The code used can be found here:
https://github.com/wilmardo/migrate-plex-to-jellyfin

Hopefully this can be fixed and users can migrate easily from Plex without the use of Trakt :)

**Comment by Artiume** [comment]
@Cobayegunther you made the E2J migrator tool, you experience anything like this?

**Comment by CobayeGunther** [comment]
Sort of, I had an issue similar but for a movie. i've not yet looked at this to provide information.
For tv shows, everything works fine in my side using the same api endpoint as @wilmardo
 `Users/{userid}/PlayedItems/{episodeid}?api_key={apikey}`

Therefore, i noticed when posting a lot of played status that  jellyfin server was sort of caching the requests, maybe 50-100, and then delay the next request when writing db.
have you tried requesting the episode after a restart of the server to see if the status was really written or just cached ?

I'll try to find time to reproduce and debug my issue with the movie

**Comment by wilmardo** [comment]
@CobayeGunther Thanks for the response! I have restarted and even updated the Jellyfin server in the meantime.
The weird thing is, the API responds with `watched: true` in the UserData of the episode so the query seems to have run against the db.
Only the UI doesn't seem to use this value since all the `watched: true` episodes are still unwatched in the UI.

**Comment by wilmardo** [comment]
@CobayeGunther Did you have a change to look at this in the meantime?

**Comment by CobayeGunther** [comment]
No, sorry. IT is just a hobby for me so I must wait holidays to have time.
do you have this error with new jelly versions to ? 10.5.5 / new 10.6 ?
