### ISSUE TITLE
DLNA not works on LG TV

### ISSUE THREAD

**Issue by razzi71** [jellyfin/jellyfin#2974]
Hello,
At the beggining I want to say, that I am new with jellyfin and docker. 
I have checked some issue like #1322 , #2623, #2259 
I have a installed jellyfin with docker on ubuntu 18.04 LTS Server.
My container is setup as host.
Secure mode is disable.
I have changed IgnoreVirtualInterfaces to true
I checked also BaseURL - /jellyfin
I am using nginx to reverse proxy:
  
  location /jellyfin {
              proxy_pass http://127.0.0.1:8096;
    }

I am using HTTP right now and port forwarding only on my router 80 -> 80 to the server.
My domain is forwarded also to public IP of my router.
I want to have access outside my network so I have to setup base URL.
When I setup Base URL like: /jellyfin - Jellyfin is accessible from Internet in App on Andorid, but my LG TV does not see te media server through DLNA. When i clear base url and restart LG TV is seeing the server. When I have set BaseURL I can share media from web interface, but I have to use laptop for this. Do you know what is going on and how can I solve the problem ?

Many thanks in advance.

PS. Jellyfin is wonderful and very good application, many thanks for this !

EDIT: additional info, I cannot trigger media from android app from. It does not matter if I am connecting from internet or locally. I can only trigger from Web Interface when I am connect local network with laptop.

**Comment by TiraelSedai** [comment]
Not sure what DLNA has to do with 80 port and ngnix

**Comment by razzi71** [comment]
on port 80 is only forwarding from internet through the router. Generally we can skip this, but I wanted to describe whole configuration in details, you wrong understand issue i guess
