### ISSUE TITLE
Can't open the server on server, and just nothing happened

### ISSUE THREAD

**Issue by pokliuy** [jellyfin/jellyfin#2977]
**Describe the bug**
![image](https://user-images.githubusercontent.com/43649460/80272691-43786400-86fe-11ea-80c7-efd91d07e5d7.png)

It is a mistake that cannot be opened at all !!!
It is useless to uninstall the reinstallation!
But everything worked fine before.

**System:**
 - OS: Winodws
 - Virtualization: Not
 - Clients: Browser, Android,but not clients's wrong
 - Browser: Chrome 81
 - Jellyfin Version: 10.5.3 stable

**To Reproduce**
1. Click on ....

**Expected behavior**
Just be okay to open this good guy.

**Comment by telans** [comment]
I assume this is fixed after a reboot or similar seeing as it's looking at temp?

**Comment by telans** [comment]
https://github.com/jellyfin/jellyfin-server-windows/issues/27
