### ISSUE TITLE
API - Users/AuthenticateByName, 'Parameter appname" is missing' if X-Emby-Authentication not supplied

### ISSUE THREAD

**Issue by smurancsik** [jellyfin/jellyfin#2979]
**Describe the bug**
Calling the api endpoint POST /Users/authenticatebyname without X-Emby-Authorization header, the error message is:
Value cannot be null. (Parameter 'appName')

**System (please complete the following information):**
 - OS: [e.g. Debian, Windows] : Debian 10
 - Virtualization: [e.g. Docker, KVM, LXC]: Docker
 - Clients: [Browser, Android, Fire Stick, etc.]: Insomnia API tester
 - Browser: [e.g. Firefox 72, Chrome 80, Safari 13] not relevant
 - Jellyfin Version: [e.g. 10.4.3, nightly 20191231]: 10.5.3
 - Playback: [Direct Play, Remux, Direct Stream, Transcode]  not relevant
 - Installed Plugins: [e.g. none, Fanart, Anime, etc.] not relevant
 - Reverse Proxy: [e.g. none, nginx, apache, etc.] not relevant
 - Base URL: [e.g. none, yes: /example] not relevant
 - Networking: [e.g. Host, Bridge/NAT] not relevant
 - Storage: [e.g. local, NFS, cloud] not relevant

**To Reproduce**
1. Open postman / insomnia / postwoman
2. Set endpoint to POST http://jellyfinaddress/Users/authenticatebyname
3. Fill out JSON input: {"Username":"test","Pw":"test1234"}
4. Don't add Auth header
5. Send

**Expected behavior**
Appropriate error message based on what header is missing.

**Comment by deerparker** [comment]
I think you are missing the Authorization header.  This isnt the same as the X-Emby-Authorization header for the other calls.

Key - Authorization
Value (as one long string) - MediaBrowser Client="your_client_name", Device="your_device", DeviceId="your_device_id", Version="your_version_number"

**Comment by smurancsik** [comment]
I know that X-Emby-Authroization was missing, but the error message I am getting does not correspond what the application misses.

**Comment by z3ntu** [comment]
I've just hit this as well while exploring the API in swagger. The only clue I've gotten outside of the "Error processing request." message was in the jellyfin log `System.ArgumentNullException: Value cannot be null. (Parameter 'appName')` which lead me here. Perhaps this should be better handled by returning an error that says that X-Emby-Authorization must be set. From just looking at the header I thought you'd call some login endpoint and then you pass in some token via this header for authorization but it's more like a client identification instead.

**Comment by crobibero** [comment]
If you want to just sent a token, use `X-Emby-Token`

We're still playing catch-up on documenting everything, so you're more then welcome to make a PR at https://github.com/jellyfin/jellyfin-docs with your suggestions

**Comment by z3ntu** [comment]
I'd rather rename this header, maybe something like `X-Jellyfin-ClientId` (or keep Emby in the name). I'll keep exploring the API in the coming days so I should have a better understanding then.
Also regarding docs, I don't see anything for the API there yet, am I missing something or is it not documented yet (apart from Swagger - which looks really good compared to 10.6.4 :slightly_smiling_face:  )

**Comment by themegaphoenix** [comment]
> I'd rather rename this header, maybe something like `X-Jellyfin-ClientId` (or keep Emby in the name). I'll keep exploring the API in the coming days so I should have a better understanding then.
> Also regarding docs, I don't see anything for the API there yet, am I missing something or is it not documented yet (apart from Swagger - which looks really good compared to 10.6.4 🙂 )

Try this:
https://api.jellyfin.org/
