### ISSUE TITLE
Use domain to access can't login:Connection Failure

### ISSUE THREAD

**Issue by zhangdp** [jellyfin/jellyfin#2988]
**Describe the bug**

**System (please complete the following information):**
 - OS: [Linux]
 - Virtualization: [Docker]
 - Clients: [Browser]
 - Browser: [Chrome 81]
 - Jellyfin Version: [10.5.4]
 - Playback: [] 
 - Installed Plugins: [none]
 - Reverse Proxy: [nginx]
 - Base URL: [https://home.xxxx.com:8920]
 - Networking: [Host]
 - Storage: [local]

![error](https://user-images.githubusercontent.com/26567414/80308428-96870f80-8801-11ea-9577-ac784d73c6e8.png)
![nginx](https://user-images.githubusercontent.com/26567414/80308166-f1b80280-87ff-11ea-9812-86f65d73718a.png)
![log](https://user-images.githubusercontent.com/26567414/80308248-6d19b400-8800-11ea-82e4-22a4f5f13d99.png)

**Comment by crobibero** [comment]
Please attach the Jellyfin logfile.

**Comment by zhangdp** [comment]
[log_20200426.txt](https://github.com/jellyfin/jellyfin/files/4535345/log_20200426.txt)
thanks

**Comment by Justsofun** [comment]
Does your nginx config include the /socket entry as seen in the documentation [here](https://jellyfin.org/docs/general/networking/nginx.html)?

I had the same problem and that solved it.

**Comment by zhangdp** [comment]
thanks，I add “proxy_set_header X-Forwarded-Host $http_host;”, and it works well now
