### ISSUE TITLE
[10.5.5] Playback cannot be started

### ISSUE THREAD

**Issue by kekonn** [jellyfin/jellyfin#2993]
**Media Info of the file**
General
Unique ID                                : 165608041447106560127880152651805841101 (0x7C96F2D7CE34CCD5CC3E4E75799D56CD)
Complete name                            : V:\Series\Westworld\Season 02\Westworld - S02E06 - Phase Space - WEB-DL-720p.mkv
Format                                   : Matroska
Format version                           : Version 4
File size                                : 1.72 GiB
Duration                                 : 59 min 23 s
Overall bit rate                         : 4 141 kb/s
Encoded date                             : UTC 2018-05-28 01:00:02
Writing application                      : mkvmerge v19.0.0 ('Brave Captain') 64-bit
Writing library                          : libebml v1.3.5 + libmatroska v1.4.8

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L3.1
Format settings                          : CABAC / 5 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 5 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 59 min 23 s
Bit rate                                 : 3 499 kb/s
Width                                    : 1 280 pixels
Height                                   : 720 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.158
Stream size                              : 1.45 GiB (84%)
Default                                  : Yes
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709

Audio
ID                                       : 2
Format                                   : E-AC-3
Format/Info                              : Enhanced AC-3
Commercial name                          : Dolby Digital Plus
Codec ID                                 : A_EAC3
Duration                                 : 59 min 23 s
Bit rate mode                            : Constant
Bit rate                                 : 640 kb/s
Channel(s)                               : 6 channels
Channel layout                           : L R C LFE Ls Rs
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Delay relative to video                  : 9 ms
Stream size                              : 272 MiB (15%)
Language                                 : English
Service kind                             : Complete Main
Default                                  : Yes
Forced                                   : No

Text #1
ID                                       : 3
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 59 min 12 s
Bit rate                                 : 27 b/s
Count of elements                        : 416
Stream size                              : 12.0 KiB (0%)
Language                                 : English
Default                                  : No
Forced                                   : No

Text #2
ID                                       : 4
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 59 min 12 s
Bit rate                                 : 33 b/s
Count of elements                        : 526
Stream size                              : 14.5 KiB (0%)
Title                                    : SDH
Language                                 : English
Default                                  : No
Forced                                   : No

Menu
00:00:00.000                             : en:HBO
00:00:04.225                             : en:Previously On
00:00:34.225                             : en:Studio Logo
00:00:40.225                             : en:Opening Credits
00:02:18.225                             : en:Bernard wrestles with a choice
00:05:02.225                             : en:Teddy and Dolores prepare for a train ride
00:08:17.225                             : en:Hale sends a message
00:11:26.225                             : en:Musashi challenges Tanaka
00:19:44.225                             : en:Lawrence questions Grace's readiness
00:21:48.225                             : en:The Cradle fights back
00:25:15.225                             : en:Akane puts Sakura to rest
00:30:53.225                             : en:The Man in Black offers to even the score
00:37:13.225                             : en:Bernard heads inside the Cradle
00:41:34.225                             : en:Ashley meets the new security
00:42:38.225                             : en:Maeve returns to a familiar story
00:51:22.225                             : en:Teddy uses the last of his mercy
00:55:10.225                             : en:Bernard finds an old friend
00:57:20.225                             : en:End Credits
00:58:32.225                             : en:On The Next Westworld

**Logs**
[server.log](https://github.com/jellyfin/jellyfin/files/4537077/server.log)

**FFmpeg Logs**
[ffmpeg.log](https://github.com/jellyfin/jellyfin/files/4537084/ffmpeg.log)

**Stats for Nerds Screenshots**
N/A

**Server System (please complete the following information):**
 - OS: Docker on DSM 6.2
 - Jellyfin Version: 10.5.5
 - Hardware settings & device: VAAPI on Intel Celeron J3455
 - Reverse proxy: nginx
 - Other hardware notes: Synology DS1019+ running docker
 
**Client System (please complete the following information):**
 - Device: Custom built desktop
 - OS: Windows 10 version 2004
 - Client: Browser
 - Browser (if Web client): Firefox
 - Client and Browser Version: 75

**Comment by bloodsplatter** [comment]
If I read the server logs correctly, it says Direct Stream is possible, so why is it trying to transcode in the first place? But on the other hand, I think this is related to the burn in subs issue.

**Comment by Artiume** [comment]
So ffmpeg never errors out, are there more ffmpeg logs available? Looking inside the actual logs, I see web socket issues. Can you bypass your reverse proxy and see if the issues still exist?



> If I read the server logs correctly, it says Direct Stream is possible, so why is it trying to transcode in the first place? But on the other hand, I think this is related to the burn in subs issue. (#2964)

What makes you suspect you were trying to burn in? You had srt subs, they shouldn't be burned. So you'd have to show me the exact line where it says direct stream capable but I imagine it was probably just saying that your user was allowed to direct stream, not referencing the actual media file

**Comment by bloodsplatter** [comment]
> I imagine it was probably just saying that your user was allowed to direct stream, not referencing the actual media file.

That will likely be the case. I saw it in the url. Other ffmpeg logs below:

[ffmpeg-directstream-b686da9d-1cb5-46a2-9f00-24acdaee9829.txt](https://github.com/jellyfin/jellyfin/files/4540254/ffmpeg-directstream-b686da9d-1cb5-46a2-9f00-24acdaee9829.txt)
[ffmpeg-transcode-9e3840df-b50d-4f3d-a98d-b59d2884b148.txt](https://github.com/jellyfin/jellyfin/files/4540255/ffmpeg-transcode-9e3840df-b50d-4f3d-a98d-b59d2884b148.txt)

**Comment by bloodsplatter** [comment]
Also: bypassing the reverse proxy doesn't help. These are all the log files generated when attempting playback without the reverse proxy:
[log.zip](https://github.com/jellyfin/jellyfin/files/4540280/log.zip)

**Comment by Artiume** [comment]
if you turn hwa off, does it work

**Comment by bloodsplatter** [comment]
No

**Comment by bloodsplatter** [comment]
These logs are from the playback attempt with HWA off (ffmpeg logs only)
[log(1).zip](https://github.com/jellyfin/jellyfin/files/4540327/log.1.zip)

**Comment by bloodsplatter** [comment]
Also, when I try looking for ffmpeg in the container, it doesn't seem to be there:

```bash
root@jellyfin:/# command -v ffmpeg
root@jellyfin:/# cd /usr/bin
root@jellyfin:/usr/bin# ls -la | grep ffmpeg
root@jellyfin:/usr/bin#
```

**Comment by Artiume** [comment]
It's located elsewhere iirc. And ffmpeg does exist for you. Otherwise you'd never get ffmpeg logs :P. Not sure whats with the file not passing, did it work with 10.5.4

**Comment by bloodsplatter** [comment]
Yes. Worked just fine, upgraded and poof. Even tried installing the nonfree intel drivers again just to be sure about the HWA

**Comment by bloodsplatter** [comment]
So the error is missing what file? The video?

**Comment by Artiume** [comment]
Can you try a fresh install?

**Comment by bloodsplatter** [comment]
In what way? Resetting the docker? Or deleting everything, including the library database?

**Comment by Artiume** [comment]
Change the config folder location will do it for docker. It'll create a new database without touching your original. Once you test it, you can restore the config path.

**Comment by joshuaboniface** [comment]
At first, I thought the issue was masked by log sanitization, but I don't think you modified that log to remove the `/usr/share/jellyfin-ffmpeg/ffmpeg` right?

If not looks like there's no FFmpeg binary path being populated. 

Can you verify in the "Playback" settings what "FFmpeg path:" is set to?

**Comment by joshuaboniface** [comment]
Wow I'm slow, that's a problem.

Let me review the build logs to see what might be up. The binary should be in `/usr/share/jellyfin-ffmpeg/ffmpeg` inside the container now.

**Comment by joshuaboniface** [comment]
Verified that the build did successfully install `jellyfin-ffmpeg`, so it should be there. Trying to replicate.

**Comment by joshuaboniface** [comment]
Cannot replicate, the file is indeed there:

```
$ docker run -it --entrypoint=/bin/bash jellyfin/jellyfin:latest
root@df773cec25c7:/# ls /usr/lib/
apt  dpkg  gcc  jellyfin-ffmpeg  locale  mime  os-release  ssl  tmpfiles.d  x86_64-linux-gnu
root@df773cec25c7:/# ls /usr/lib/jellyfin-ffmpeg/
ffmpeg  ffprobe  lib
```

I second @Artiume, try removing then reinstalling the container and it should be OK. Might be an upgrade artifact. As long as the config volumes are still the same it should be seamless.

**Comment by bloodsplatter** [comment]
It's not, I'm afraid. I'm still having the issue. Logs of the completely fresh container are attached
[log(2).zip](https://github.com/jellyfin/jellyfin/files/4540530/log.2.zip)

**Comment by joshuaboniface** [comment]
If you get shell in the container, is the binary in `/usr/lib/jellyfin-ffmpeg` as expected? If you manually set it in the UI, does that work?

**Comment by bloodsplatter** [comment]
Yes the binary is in the right place. Turns out the ffmpeg path was cleared in the settings. I checked the "clean" container and it had the same issue.

**Comment by joshuaboniface** [comment]
Great, glad that solved it. I'm not sure why the config path is empty still though, that CLI flag should definitely be overriding it. Maybe at some point a single space was saved in the config by accident (I've done that a few times in the UI for other settings).

**Comment by bloodsplatter** [comment]
But if that was the case it shouldn't be happening on the clean container, just my usual container.

**Comment by joshuaboniface** [comment]
Oh I had assumed you kept the config on the fresh container. That's very strange. I believe @mark-monteiro ran into this same issue as well.

**Comment by bloodsplatter** [comment]
No, it wasn't just a clear container, it was a completely clean install.

**Comment by mark-monteiro** [comment]
If I remember correctly, this was my repro steps (this was all via running with Visual Studio):
1. Have an existing working installation
2. Add `--datadir="C:/temp"` command line flag to simulate a fresh install
3. ffmpeg path setting was gone

**Comment by bloodsplatter** [comment]
So you agree that on a fresh install, the ffmpeg path is empty?

**Comment by mark-monteiro** [comment]
> So you agree that on a fresh install, the ffmpeg path is empty?

No, in my scenario I was working locally and running via Visual Studio, it wasn't an 'install'. I think in my case this is actually the expected behavior since it doesn't look like ffmpeg is part of the repository? @joshuaboniface Maybe you can confirm, is this something we need to add the the repository README as a setup step for local development? Specify a path to ffmpeg?

**Comment by bloodsplatter** [comment]
My problem is fixed anyway. If you want to keep this open until the reason the path was empty was found, feel free.
