### ISSUE TITLE
automatically generate art cover from the video

### ISSUE THREAD

**Issue by 1ndeed** [jellyfin/jellyfin#2994]
Not everyone uses jellyfin to watch movie... right? I use this to watch some short videos. It would be very nice if it could make **one frame of the video** as the **thumnail**. Thanks.

**Comment by 1ndeed** [comment]
I rescanned the library and it shows... Maybe in the next update make it there in the first place?

**Comment by Artiume** [comment]
The image extractor is called Screen Grabber when you are creating a library, it is part of the initial media scan :)
