### ISSUE TITLE
Building on Windows not possible: Missing "deployment\windows\build-jellyfin.ps1"

### ISSUE THREAD

**Issue by Spamm00r** [jellyfin/jellyfin#2998]
**Describe the bug**
I follow the instructions for building on windows frome here: https://jellyfin.org/docs/general/administration/building.html

3. Run the Jellyfin build script:
And I fail at: deployment\windows\build-jellyfin.ps1 -verbose

There is no .ps1 in the code that git checked out.

Is the build guide outdated or the file missing?

**System (please complete the following information):**
 - OS: [Windows]

**To Reproduce**

Follow Build guide from: https://jellyfin.org/docs/general/administration/building.html

Until step 3 . ps1 script is not available in the downloaded git code.

**Expected behavior**
Buidl guide: https://jellyfin.org/docs/general/administration/building.html

Schould work as described.

**Logs**

PS C:\Jellyfin> cd .\jellyfin\
PS C:\Jellyfin\jellyfin> git submodule update --init
PS C:\Jellyfin\jellyfin> set-executionpolicy unrestricted

Execution Policy Change
The execution policy helps protect you from scripts that you do not trust. Changing the execution policy might expose
you to the security risks described in the about_Execution_Policies help topic at
https:/go.microsoft.com/fwlink/?LinkID=135170. Do you want to change the execution policy?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): y
PS C:\Jellyfin\jellyfin> deployment\windows\build-jellyfin.ps1 -verbose
deployment\windows\build-jellyfin.ps1 : The module 'deployment' could not be loaded. For more information, run
'Import-Module deployment'.
At line:1 char:1
+ deployment\windows\build-jellyfin.ps1 -verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (deployment\windows\build-jellyfin.ps1:String) [], CommandNotFoundExcept
   ion
    + FullyQualifiedErrorId : CouldNotAutoLoadModule

**Comment by pixelbath** [comment]
I believe `deployment` refers to the folder where you cloned Jellyfin - it should probably read as follows:

> 3. Navigate to the folder where Jellyfin was cloned:
>
> `cd c:\path-to-folder\jellyfin`
>
> 4. Run the Jellyfin build script:
> 
> `.\windows\build-jellyfin.ps1 -verbose`

This file is in the expected location for me (I cloned to `C:\Users\[my-username]\Documents\Repos\jellyfin`):
![image](https://user-images.githubusercontent.com/4740954/81121865-eeea9b00-8eec-11ea-9496-7a25ece6577c.png)

**Comment by Spamm00r** [comment]
Ok Now I get the error:

> Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       08.05.2020     13:39                dialogs
d-----       08.05.2020     13:43                dist
d-----       08.05.2020     13:39                helpers
d-----       08.05.2020     13:39                legacy
-a----       08.05.2020     13:39           8494 build-jellyfin.ps1
-a----       08.05.2020     13:39             12 dependencies.txt
-a----       08.05.2020     13:39          22773 jellyfin.nsi


PS C:\Jellyfin\jellyfin\windows> .\build-jellyfin.ps1 -verbose


    Directory: C:\Jellyfin\jellyfin\windows\dist


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       08.05.2020     13:43                jellyfin-win-nsis
Resolve-Path : Cannot find path 'C:\Jellyfin\jellyfin\jellyfin-ux' because it does not exist.
At C:\Jellyfin\jellyfin\windows\build-jellyfin.ps1:29 char:23
+ $ResolvedUXLocation = Resolve-Path $UXLocation
+                       ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Jellyfin\jellyfin\jellyfin-ux:String) [Resolve-Path], ItemNotFoundEx
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.ResolvePathCommand

VERBOSE: Starting Build Process: Selected Environment is win-x64
VERBOSE: windowsversion-Architecture: win-x64
VERBOSE: InstallLocation: C:\Jellyfin\jellyfin\windows\dist\jellyfin-win-nsis
VERBOSE: DotNetVerbosity: Minimal
Microsoft (R) Build Engine version 16.5.0+d4cbfca49 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: Jellyfin.Server
Copy-Item : Cannot find path 'C:\Jellyfin\jellyfin\windows\LICENSE' because it does not exist.
At C:\Jellyfin\jellyfin\windows\build-jellyfin.ps1:174 char:1
+ Copy-Item .\LICENSE $ResolvedInstallLocation\LICENSE
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Jellyfin\jellyfin\windows\LICENSE:String) [Copy-Item], ItemNotFoundE
   xception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand

VERBOSE: Finished


PS C:\Jellyfin\jellyfin\windows>

**Comment by dkanada** [comment]
We have moved the Windows wrapper to [this](https://github.com/jellyfin/jellyfin-server-windows) repository, and the main server will only build executables now. The file you're looking for has also moved to that location.

**Comment by PrplHaz4** [comment]
If you're not trying to build the installer, it should be as simple as installing .net core 3.1, cloning the repo, and running `dotnet build`.  This should get you a working executable that will run from any directory.
```
mkdir c:\tmp
cd c:\tmp
git clone https://github.com/jellyfin/jellyfin.git
cd c:\tmp\jellyfin
dotnet build
``

**Comment by Spamm00r** [comment]
Yes the guide is outdated.

1. The ps1 file was not there when I was trying to build, and now it is there. 

2. The proper way of building is as PrplHaze writes and described in:

https://github.com/jellyfin/jellyfin/blob/master/README.md

And the build works fine.

Issue closed.
