### ISSUE TITLE
Create mailing list?

### ISSUE THREAD

**Issue by chowbok** [jellyfin/jellyfin#3]
I'd like to follow the development of this. Can a mailing list for developers and users be created (assuming one doesn't yet exist)?

**Comment by anthonylavado** [comment]
@chowbok One hasn't been created, but at the time being, the plan is to keep this as a buildable version, and eventually we are moving away from Emby as a whole.

**Comment by joshuaboniface** [comment]
I think the chat is sufficient for now, given that it's open source and widely used by us already. Mailing lists seem... obsolete in 2018, I honestly would rather us set up a forum and get a Reddit community going, though if there's more interest we can revisit it.
