### ISSUE TITLE
Rebrand and publish on Nuget

### ISSUE THREAD

**Issue by LeoVerto** [jellyfin/jellyfin#30]
This shouldn't be too hard, seems to just need for someone to edit the [relevant files](https://github.com/jellyfin/jellyfin/tree/master/Nuget) and click a couple buttons.

**Comment by sparky8251** [comment]
We have a Nuget org now iirc. Can movement on this happen?

**Comment by anthonylavado** [comment]
We've now got our modules up. Can this be closed then?

http://nuget.org/profiles/Jellyfin
