### ISSUE TITLE
Make clicking on an item's name do something

### ISSUE THREAD

**Issue by dinki** [jellyfin/jellyfin#300]
It's a bit weird that when you try to click on the name of video (like circled in red) that it doesn't do anything:

![image](https://user-images.githubusercontent.com/2521542/50528698-72a0a600-0ab5-11e9-86ee-464beab438ac.png)

Can this be changed to start playback or at the very least bring up the information page?

**Comment by nvllsvm** [comment]
Agreed - especially when it works for only TV shows in in "Now Playing". It takes one to the show's homepage. 

![o](https://user-images.githubusercontent.com/6550543/50528923-4db13080-0abf-11e9-93d7-6fc710de5668.png)

**Comment by Numline1** [comment]
I make it a rule not to agree with people watching Adam Sandler movies, but I've noticed this as well, would be a nice QoL improvement :) +1

**Comment by dinki** [comment]
I've got lots of movies I haven't watched, but this isn't one of them. Lol

**Comment by LeoVerto** [comment]
What would be the expected behaviour here? Just playing the movie or something else?

Breaking consistency with the link in "Now Playing" also seems like a bad idea to me so perhaps that should be changed as well?

**Comment by nvllsvm** [comment]
I like the idea of going to the info page for the clicked item - much like how the Now Playing link works now.

**Comment by Bond-009** [comment]
Fixed by #26

**Comment by LeoVerto** [comment]
> Fixed by #26

Don't you mean jellyfin/jellyfin-web#26? :P

**Comment by Numline1** [comment]
Nice change, thanks :P 👍
