### ISSUE TITLE
Vaapi error on 10.5.5 version (Synology Docker)

### ISSUE THREAD

**Issue by viriatusX** [jellyfin/jellyfin#3000]
Hi guys,
Sorry for my poor experience with Github. I have one problem i not found any solution...
I just installed Jellyfin 10.5.5 on my NAS trought Docker. 
I followed these steps :
1. Install Docker.
2. Export JSON of container 
3. Replace "Devices" for :   "devices" : [
      {
         "CgroupPermissions": "rwm",
         "PathInContainer": "/dev/dri/renderD128",
         "PathOnHost": "/dev/dri/renderD128"
      }
   ], 
4. Import JSON 
5. Chmod 777 /dev/dri/renderD128.
6. Activate VAAPI on Jellyfin settings.

Do I have to do more steps? I not understand too much.....

I get the error.: "There was an issue with the client profiling and the server isn't sending a compatible media format ". Almost of the files transcodes OK, but anothers i get this error. If I selected Intel Quick Sync works all files, for that i think it could be the vaapi transcoding.

Thanks.

**Comment by poulpor** [comment]
I don't know if it may change something or not, but my json devices looks like this and vaapi works good:
   "devices" : [
      {
         "CgroupPermissions" : "rwm",
         "PathInContainer" : "/dev/dri",
         "PathOnHost" : "/dev/dri"
      }
   ],

**Comment by viriatusX** [comment]
> Hi, Synology owner here too, I don't know if it may change something or not, but my json devices looks like this and vaapi works good:
> "devices" : [
> {
> "CgroupPermissions" : "rwm",
> "PathInContainer" : "/dev/dri",
> "PathOnHost" : "/dev/dri"
> }
> ],
> And in _Settings/Dashboard/Playback/VA API Device:_/dev/dri/renderD128

Thanks for your reply.
You install the official jellyfin docker with root permissions or by defect?
You not change the permissions on renderD128? 
Only put "devices" : [
{
"CgroupPermissions" : "rwm",
"PathInContainer" : "/dev/dri",
"PathOnHost" : "/dev/dri"
}
], 

and its work?
Can you test 4K Full? 
Thanks for your reply.

**Comment by poulpor** [comment]
My bad, I should have specified that I'm using linuxserver/jellyfin and ffmpeg path is _/usr/lib/jellyfin-ffmpeg/ffmpeg_
4k is hardware transcoding fine (see htop command in ssh screeshot)
![Capture d’écran 2020-04-28 à 14 36 22](https://user-images.githubusercontent.com/49480426/80487846-c1867600-895d-11ea-8a67-86ccb87a4106.png)

**Comment by viriatusX** [comment]
> My bad, I should have specified that I'm using linuxserver/jellyfin with root permissions and ffmpeg path is _/usr/lib/jellyfin-ffmpeg/ffmpeg_
> 4k HEVC Main 10 video is hardware transcoding fine (see htop command in ssh screeshot)
> ![Capture d’écran 2020-04-28 à 14 36 22](https://user-images.githubusercontent.com/49480426/80487846-c1867600-895d-11ea-8a67-86ccb87a4106.png)

it doesn't work for me :( outside the docker have you configured something on the NAS? Have you installed the Intel Va drivers or something else?

**Comment by poulpor** [comment]
I didn't install specific intel drivers, but could you confirm dev/dri folder is present when you ssh to your nas? Are Plex and/or videostation hardware transcoding OK?

**Comment by viriatusX** [comment]
Yes. /dev/dri exist on my NAS. I not test Plex or Videostation... I will try later...
something I do not do well.  sure

**Comment by poulpor** [comment]
What is the result of this ssh command?
cat /usr/syno/etc/codec/activation.conf

**Comment by viriatusX** [comment]
cat: /usr/syno/etc/codec/activation.conf: No such file or directory

Not exist this directory...

**Comment by poulpor** [comment]
I'm not 100% sure but I think your problem is not with Jellyfin but your synology installation. To get activation.conf, you have to install video station package then play some videos whit it to get the file to exist.

**Comment by viriatusX** [comment]
Yes! I transcode one file with Video station and with:  cat /usr/syno/etc/codec/activation.conf.

{"success":true,"activated_codec":["h264_dec","h264_enc","hevc_dec","ac3_dec"],"                   token":"f7809b61808fddff2f5126c204958db8"}

**Comment by poulpor** [comment]
great, so now hardware transcode is activated on your nas, you should retry with jellyfin.

**Comment by viriatusX** [comment]
Nothing.... not work. I try restart NAS but nothing. With Video Station for example, transcode correctly Just Mercy, but with Jellyfin, i get the error.: "There was an issue with the client profiling and the server isn't sending a compatible media format ". I not understand.....
My Docker config is OK, no?
[https://i.imgur.com/NE7JCm5.png](url)
[https://i.imgur.com/goWKJzZ.png](url)

**Comment by poulpor** [comment]
which docker are you using? jellyfin/jellyfin? I would recommend linuxserver/jellyfin, works better on synology, from my experience. here is my json, it's your to adapt to your specific setup (PUID,PGID, media folders, TZ, etc...).

[linuxserver-jellyfin1.syno.json.zip](https://github.com/jellyfin/jellyfin/files/4546551/linuxserver-jellyfin1.syno.json.zip)

**Comment by viriatusX** [comment]
I'm from Spain, the TZ is the same. I modified the PUID for that me, but nothing.... not work. Would be permissions problems for anithing?
I attach you my JSON modified with my data. Can you try to import to another container and test?
(https://easyupload.io/8zd7s6)

**Comment by poulpor** [comment]
Testing your json wouldn't be relevant, but I think you might have a problem with your docker path "/Internacional/config and cache. Docker containers datas should be stored in something like  **volume1/docker/**appname, a folder created when you installed docker package, with the right permissions. I won't try to mess with it by installing docker datas elsewhere so you might displace config and data to a jellyfin folder inside /volumeX/docker which might exists.

**Comment by viriatusX** [comment]
I have Docker installed on volume1. The movies in Volume 2. I would create Inside volume1 the path docker and inside the subfolders config and cache)? And allow permissions for "admin" and "video" groups users?

The file /dev/dri/renderD128 has "Video" group users and "root" user. Can i modify something?

**Comment by viriatusX** [comment]
I found the problem.... Jellyfin doesn't work with full bluray with AACS2 or another type of Protection. For this reason, all of my remux transcodes well but not almost of my full bluray collection :)

**Comment by Artiume** [comment]
Can this be resolved or does anyone else still have synology vaapi issues?

**Comment by viriatusX** [comment]
Solved :) Thanks!
