### ISSUE TITLE
Subtitle encoding error

### ISSUE THREAD

**Issue by a13087635768** [jellyfin/jellyfin#3002]
**Describe the bug**

**System (please complete the following information):**
 - OS: unraid
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Chrome 
 - Jellyfin Version: 10.5.5
 - Playback: Direct Play
 - Installed Plugins: empty
 - Reverse Proxy: empty
 - Base URL: yes:/http://192.168.2.20:8000/
 - Networking: Bridge
 - Storage:local

**To Reproduce**

![image](https://user-images.githubusercontent.com/23163284/80488887-a2094080-8991-11ea-9127-d2da230e0087.png)
![image](https://user-images.githubusercontent.com/23163284/80488928-ae8d9900-8991-11ea-81bb-fb3d0695aa06.png)

I don't know what format the subtitle is encoded but there is a problem with the display.

[Subtitle example.zip](https://github.com/jellyfin/jellyfin/files/4545832/Subtitle.example.zip)

**Comment by a13087635768** [comment]
It is normal to use 10.4.x

**Comment by Artiume** [comment]
With 10.5, ASS subtitles are rendered by the browser and aren't burned-in. We're having issues with non-Latin characters due to this. This is being tracked by https://github.com/jellyfin/jellyfin/issues/2670 and https://github.com/jellyfin/jellyfin/issues/3006

Closing ticket.
