### ISSUE TITLE
High CPU usage for security camera footages

### ISSUE THREAD

**Issue by MateEke** [jellyfin/jellyfin#3004]
**Describe the bug**
I have a library where my security camera stores it's footages. A new file created every time if there is motion. Jellyfon constantly does something with this library what makes a very high cpu usage.

**System (please complete the following information):**
 - OS: Ubuntu 18.04
 - Virtualization: Docker
 - Jellyfin Version: 10.5.5
 - Installed Plugins: AudioDB, MusicBrainz, Open Subtitles, Trakt
 - Reverse Proxy: nginx
 - Base URL: none
 - Networking: host
 - Storage: local

**To Reproduce**
Create a directory and constantly add new files

**Expected behavior**
Low CPU usage (for example Plex has access to the same library without any issues)

**Logs**
no errors

**Screenshots**
![image](https://user-images.githubusercontent.com/11072174/80506718-441b2f80-8976-11ea-8970-7435fa801c6f.png)

**Comment by dkanada** [comment]
Just to make sure, do you mean high CPU usage on your browser or on the server?

**Comment by MateEke** [comment]
Sorry, on the server.

**Comment by PrplHaz4** [comment]
Some troubleshooting you can do:
1. Turn off scanning/metadata providers for the library
2. Turn off Real Time Monitoring of the library
2. Make sure UPnP port forwarding is disabled (this has caused high cpu usage in some cases)

**Comment by MateEke** [comment]
Already tried all of this steps - metadata is unnecessary for this kind of content, and I don't use upnp.
Real time monitoring maybe related to the issue, but if I turn it off how could I see added footages? Trigger scanning manually every time when need to access the files? Scanning of this library is VERY slow.

**Comment by PrplHaz4** [comment]
> 
> 
> Already tried all of this steps - metadata is unnecessary for this kind of content, and I don't use upnp.
> Real time monitoring maybe related to the issue, but if I turn it off how could I see added footages? Trigger scanning manually every time when need to access the files? Scanning of this library is VERY slow.

You can turn it off to verify that is the issue, then it can be addressed in a more direct way.

From the sound of it, it takes so long to scan every time the library is updated, it hasn't finished by the next time a motion alarm is triggered.

**Comment by MateEke** [comment]
I have played a bit with the settings. Turning off real time monitoring "solves" the issue. The strange is, that when only a single new footage is added (around 30s, 3MB) the library scanning still takes a lot of time and resources, maybe it rescans all of the files?
