### ISSUE TITLE
Android device doesn't appear in other devices' Play To menu

### ISSUE THREAD

**Issue by CutterXYZ** [jellyfin/jellyfin#3008]
**Describe the bug**
My Android device doesn't appear in my other devices' Play To menu when connected with the Jellyfin app through a reverse proxy. When the Android device is connected directly to the server, bypassing the reverse proxy, it appears in the Play To menu. When the device is connected on a mobile browser, even through the reverse proxy, it is seen by the other devices.

**System (please complete the following information):**
 - OS: Windows 10
 - Virtualization: no
 - Clients: Jellyfin app
 - Browser: Firefox 76
 - Jellyfin Version: 10.5.5
 - Playback: N/A
 - Installed Plugins: OpenSubtitles
 - Reverse Proxy: caddy
 - Base URL: none
 - Networking: local network on ISP's router
 - Storage: local

**To Reproduce**

1. On the Android device: open Jellyfin app, connect using the server's public IP address.
2. On any other device, tap on "Play To" and look for the Android device in it.

**Expected behavior**
The other devices should see the Android device in the menu.

**Logs**
No error in logs

**Screenshots**

**Additional context**
I've recently put Jellyfin behind a reverse proxy and updated to version 10.5.5. Jellyfin is bound to 127.0.0.1.

**Comment by aferpa94** [comment]
I'm not having this issue. Tried right now opening the android app in one device and the browser in another and I can see the android device on the menu. I can connect to it and play content remotely. Check your user settings and maybe your caddy config.

**Comment by CutterXYZ** [comment]
How does your caddy config look ? Mine is very simple: it listens on my public DNS and redirects to localhost:8096.

**Comment by aferpa94** [comment]
I'm not using caddy, i'm using Nginx as shown on the [docs](https://jellyfin.org/docs/general/networking/nginx.html).

**Comment by eltiel** [comment]
Are your websockets configured properly? I had a similar experience when I overlooked them.

**Comment by CutterXYZ** [comment]
Caddy's documentation states that they're supposed to be "just working" out of the box.

**Comment by CutterXYZ** [comment]
Caddy is configured to encrypt everything and I was connecting to my server without specifying the https:// prefix. Caddy responded to all requests with a 308 code and the app didn't seem to follow the redirection to https URLs.

If I connect to the server with the https:// prefix this bug doesn't happen anymore.
