### ISSUE TITLE
Metdata is not loaded for collections

### ISSUE THREAD

**Issue by misterbit-pro** [jellyfin/jellyfin#3009]
**Describe the bug**
The metadata is not loaded when i open a movie over the collections
View when its opened in the collections:
![image](https://user-images.githubusercontent.com/47662866/80577103-9ad04a00-8a06-11ea-9b47-2bad8353cb55.png)
View when its opened in the library:
![image](https://user-images.githubusercontent.com/47662866/80577139-acb1ed00-8a06-11ea-8efb-2e3110773492.png)

**System:**
 - OS: Debian 10
 - Virtualization: Docker
 - Clients: Browser, Android App
 - Browser: Firefox 68esr
 - Jellyfin Version: 10.5.5 
 - Installed Plugins: Fanart, Anime
 - Reverse Proxy: nginx
 - Base URL: none
 - Networking: host
 - Storage: jellyfin SSD, media on HDD

**To Reproduce**
1. Go to Collections
2. Click on your desired collection
3. Click on desired movie
4. See page in first screenshot

**Expected behavior**
See page like second screenshot

**Comment by faizpuru** [comment]
I have the same issue !

**Comment by Artiume** [comment]
This has been fixed and is slated for 10.6, resolving ticket
