### ISSUE TITLE
IPTV Plugin doesnt support UDP protocol

### ISSUE THREAD

**Issue by heroes1412** [jellyfin/jellyfin#3011]
I have IPTV stream such as
`#EXTM3U TEST
#EXTINF:-1,VTV1 HD
udp://@225.1.2.249:30120`

but i dont know how to add new IPTV Stream, it only supports HTTP/FILE/RTMP/RTSP

**Comment by heroes1412** [comment]
#EXTM3U TEST
#EXTINF:-1,VTV1 HD
udp://@225.1.2.249:30120

**Comment by Artiume** [comment]
@PrplHaz4 You ever encounter UDP streams?

**Comment by PrplHaz4** [comment]
@Artiume sorry, not for IPTV, but the first part of this issue might be more simple than that...

@heroes1412 put this into a text file with the .m3u extension, make it available to Jellyfin (drop it in one of your library folders or something), and add it as a M3U Tuner.  Very odd that the address starts with `@` - I removed it, but if you need a user/pw there you can put it back...  Also, if you're running in docker, you will need to make sure the UDP port is forwarded.

```
#EXTM3U TEST
#EXTINF:-1,VTV1 HD
udp://225.1.2.249:30120
```

**Comment by PrplHaz4** [comment]
@heroes1412 sorry, just realizing you're using the IPTV plugin, not LiveTV.

Last I tried, the IPTV plugin didn't work out of the box for me - but you may want to open an issues there to track: https://github.com/jellyfin/jellyfin-plugin-iptv

Since it requires adding a protocol in the dropdown, this would prob be a (minor) feature request.

**Comment by heroes1412** [comment]
hi @PrplHaz4 ,
i tried add 1 IPTV record (IPTV Plugin) udp://225.1.2.249:30120 with 4 methods, everything works but get much scratches...
maybe jellyfin read data from IPTV stream and relay (re-stream) to client? is there anyway to bypass this (client will stream directly from iptv address)?

**Comment by PrplHaz4** [comment]
> 
> 
> hi @PrplHaz4 ,
> i tried add 1 IPTV record (IPTV Plugin) udp://225.1.2.249:30120 with 4 methods, everything works but get much scratches...
> maybe jellyfin read data from IPTV stream and relay (re-stream) to client? is there anyway to bypass this (client will stream directly from iptv address)?

yes, that is likely what is happening...

Currently there is nothing in Jellyfin (that I know of) to tweak ffmpeg inputs for UDP but that is probably what is needed to improve the picture.

As far as clients direct playing UDP - I'm not sure if it actually works in JF or not, but you'd have to create a custom profile for the client that includes UDP as a supported protocol.

Have you tried to open the udp stream or m3u directly in the client?  I'm guessing most browsers and mobile apps would not support a udp stream as input...

**Comment by heroes1412** [comment]
yes bro,
i tried play udp stream by POT Player (or VLC Player), very smoothly... no scratch....
