### ISSUE TITLE
HEVC Transcode Profile Issues

### ISSUE THREAD

**Issue by iwalton3** [jellyfin/jellyfin#3018]
Update: I didn't realize the HEVC support was already released. This issue still applies, but the primary goal was to be able to declare HEVC transcode support by default. This will now have to be delayed until most Jellyfin servers are on a release where it would be disabled by default, so I am just going to release MPV Shim with HEVC transcoding disabled by default.

I have added initial support for requesting Jellyfin to transcode media to HEVC for remote streaming to MPV Shim. This is especially useful for remote residential servers where bandwidth may be extremely constrained, as using HEVC allows for double the video quality or concurrent users.

The main issue is the server owner does not have control over if HEVC transcoding is enabled. CPU-based transcoding to HEVC can use 3-6 times the processing power of a h264 transcode, which seriously impacts server owners. I don't think it is reasonable to enable it by default without hardware acceleration, but right now the only place it can be disabled is on my end in the profile by not declaring support. This is not ideal.

Additionally, when testing CPU transcoding, the quality was awful. The CRF of 28 seems to be too high, and the default veryfast profile probably doesn't help the quality of the x265 encoder either. (It appears to be more sensitive to these settings than x264.) I have not tested GPU transcoding quality. Currently, the profile can be changed in the web UI, but you must edit `/etc/jellyfin/encoding.xml` to change the crf.

If you want to test HEVC transcoding, you can use the most recent version of Jellyfin MPV Shim. You need to manually enable support using the `c` menu from inside MPV or the [config file](https://github.com/iwalton3/jellyfin-mpv-shim#configuration). You can confirm the file is hevc by pressing `i` during playback.

**Comment by Spamm00r** [comment]
Thanks for releasing this version.

I have no quality issues with it. On the contrary, compared to h264, the quality is much better. I do however max out the quality settings and let hevc_nvenc transcode at the best settings possible, as in my situation, the upload speed is the limiting factor and the transcoding HW is powerufl enough to handle the task. My GTX 1060 doesn't even need to turn on the fans when transcoding a 60 Gig UHD to a streamable level.

Therefore the only thing I have to limit is the bitrate and tweak to match my upload speed limit.

I however always use HW acceleration. Preferably nvenc or at least Intel Quick Snyc. Otherwise ffmpeg will max out my CPU. And that is unnecessary and inefficient, when a HW transcoder like nvenc or quick sync is available.

As far as I know,  Jellyfin with mpv shim Desktop is the only client, that supports hevc transcoding now. No more get request hacking with VLC.

Good Job!

**Comment by normanu** [comment]
This actually solves the issues I was having playing through Jellyfin Web, 
https://github.com/jellyfin/jellyfin/issues/3780

It plays on the full 4K.
Can I also use MPV as transcoder for Jellyfin instead of ffmpeg ?

**Comment by iwalton3** [comment]
> Can I also use MPV as transcoder for Jellyfin instead of ffmpeg ?

What do you mean by that? MPV is a player, it can't be used to transcode videos as part of a media server.

**Comment by normanu** [comment]
Ah yes, I made a thinking mistake there.
Would be nice to have it integrated in the Web player.

I saw here someone who got HEVC streaming working with Plex and a Chromecast.
Would it be possible to use these profiles on Jellyfin?

https://www.reddit.com/r/PleX/comments/62t5nf/working_h265hevc_direct_play_into_chromecast/

**Comment by iwalton3** [comment]
>  Would be nice to have it integrated in the Web player.

It can be integrated with the web player as a desktop application, but you can't run MPV in a web browser without developing browser plugins.

Currently, the MPV Shim project allows easy playback to MPV from the web player, especially with the desktop mode which comes pretty close to the desired experience. (The difference is MPV is a separate window.) Actual full integration in the form of a desktop application will likely come later with the [official electron client](https://github.com/jellyfin/jellyfin-desktop/issues/12).

**Comment by Spamm00r** [comment]
I assume that you will be able to direct stream HEVC from jellyfin server to the HEVC capable receiver if you properly setup the profile.

What we discussed in this thread was making  mvp shim request an hevc stream from the jellyfin server. And it worked flawlessly after iwalton3 added it in.

There is no change needed on the Jellyfin server side. All you need to do is request a hevc stream from the server. 

Unfortunately the client applications that are able to request a hevc stream are limited. mpv shim is the only application that I know that can do this.

You can play hevc stream on vlc if you hack the request to the jellyfin server. 

I also have a hevc capable android tablet, but unfortunately the jellyfin app does not request hevc streams to that device. All it is required is to tell the server to send a hevc stream. My android device is capable of decoding hevc on a hardware level.

I just have a 3rd gen Chromecast, so I can not test HEVC direct streaming on it.

What I do alternatively is stream the hevc content to my desktop and then cast my desktop to the Chromecast on the WIFI.

**Comment by normanu** [comment]
Not sure, it doesn't seem to work in Chrome.
And not on the Chromecast.
Also in Edge it is not on the original resolution. 
Thats actually the same on the mpv shim until you disable the transcoding in the menu.
