### ISSUE TITLE
CI for binary package release builds

### ISSUE THREAD

**Issue by rigtorp** [jellyfin/jellyfin#3019]
I see that there are scripts for building all the binary package releases, but no CI automation for them. It should be possible to create GitHub actions that creates these release artifacts automatically when tags are created or nightly for a nightly release.

Is this something you would want help with?

**Comment by rigtorp** [comment]
After #3020 is merged it should be possible to build the container using `podman build -t jellyfin/jellyfin .`  inside the Github Actions Ubuntu 18.04 environment.

**Comment by dkanada** [comment]
We are somewhat set on Azure for all our CI at the moment so that would be ideal.

**Comment by rigtorp** [comment]
Azure Pipelines and Github actions is the same technology as I understand. Anyway after you merge #3020 I might try get some pipeline ymls working. You currently don't have CI for packages and container images right?
