### ISSUE TITLE
Current Password Hashing mechanism is weak

### ISSUE THREAD

**Issue by LogicalPhallacy** [jellyfin/jellyfin#302]
Right now the user auth mechanism in jellyfin is a hashed password. Space is there for a salt and there is some subroutine that also does unsalted SHA1 "easy passwords". SHA1 has been considered weak for a while, and with no salt in play, we might as well be storing passwords in plaintext. We should look at using KeyDerivation.Pbkdf2 with at least SHA256.

The difficulty here will be conversion without breaking existing users.

**Comment by sparky8251** [comment]
I would alert the user before making such changes. If the changes makes the DB not backwards compatible, the user should have the choice of backing out and downgrade to an older version/backup the DB before continuing.

Just making breaking changes to the DB schema unannounced will certainly piss off a lot of people.

**Comment by EraYaN** [comment]
You can do it like Kodi does, just number the database on each migration and leave all old databases with version number attached.

**Comment by sparky8251** [comment]
If we do this, we want to prevent manual edits to the password in the database from working. At least to some degree.

Adding in an unsalted password hash on an admin account should ideally not result in access. Maybe version 10.0.x has this fix in it, and 10.1.x breaks compat with all older database versions requiring you to use 10.0.x to migrate an older DB.
