### ISSUE TITLE
Green Line at the bottom of HEVC videos

### ISSUE THREAD

**Issue by RandomDelta6** [jellyfin/jellyfin#3021]
**Describe the bug**
A green bug appears at the bottom of all HEVC 10 bit videos when using Intel Quicksync HWA. Occurs in app as well as on the webclient. 

**System (please complete the following information):**
 - OS: Windows 10 1909
 - Virtualization: No
 - Clients:Chrome Browser, Android 8,9,10
 - Browser: Chrome 81
 - Jellyfin Version: 10.5.5 Stable
 - Playback:Transcode (Direct play is not working even though some target devices are capable of HEVC playback )
 - Installed Plugins: none
 - Reverse Proxy:none
 - Base URL: none
 - Networking: none
 - Storage: local

**To Reproduce**
Playback any HEVC 10 bit video. Width of green bar changes depending on resolution . HEVC 12 bit files not playing back.

**Expected behavior**
No green bar

![Annotation 2020-05-01 150048](https://user-images.githubusercontent.com/53912269/80796347-92ba0b00-8bbc-11ea-868f-9acd30e3f8f0.png)

**Comment by nyanmisaka** [comment]
It is a small problem caused by `scale_qsv` filter in ffmpeg. 
I will solve it when we update to ffmpeg 4.3.

**Comment by RandomDelta6** [comment]
Thanks for the reply!
Any eta on the update?
Hope it's sorted out soon! I really like jellyfin but this issue is kinda annoying...
