### ISSUE TITLE
Video playback started notification sent even if user not monitored

### ISSUE THREAD

**Issue by thisis-mental** [jellyfin/jellyfin#3023]
**Describe the bug**
"Video playback started" notification is sent when a playback is started even if the user is not monitored.
The impacted user started a playback through the web client.

**System**
- Version: 10.5.5
- Operating System: Linux / Docker
- Architecture: X64

**To Reproduce**
1. Activate notification "Video playback started"
2. Select 1 user
3. Keep 1 user unselected
4. Choose your admin user as target
5. Select a notification channel like Slack
6. Start playback on both a monitored and unmonitored users

**Expected behavior**
You should receive a notification only for the monitored user

**Screenshots**
![unknown](https://user-images.githubusercontent.com/35723598/80812425-3fe65080-8bc8-11ea-9e07-09fb80ecbd98.png)

**Comment by eltiel** [comment]
Duplicate of https://github.com/jellyfin/jellyfin/issues/2262

I don't think this is high on the priority list for a fix.
