### ISSUE TITLE
Hardware acceleration with PGS subtitles hangs indefinitely

### ISSUE THREAD

**Issue by mholt** [jellyfin/jellyfin#3028]
**Describe the bug**

I think there are 2 issues here, but I'll just post the info I know and let you decide! :)

Initiated from [this reddit thread](https://www.reddit.com/r/jellyfin/comments/g8ox3j/hardware_acceleration_on_raspberry_pi_4_not/for798a/?context=8&depth=9) which has a little more background.

Hardware-accelerated encoding of a stream with PGS subtitles hangs indefinitely on Raspberry Pi 4. After disabling subtitles, stream works fine, but there's still an error in the logs either way (appears a couple times):

```
[matroska,webm @ 0x1b92af0] Stream #5: not enough frames to estimate rate; consider increasing probesize
[matroska,webm @ 0x1b92af0] Could not find codec parameters for stream 3 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
```

- One issue is that the video doesn't play at all
- Another issue might be those errors

**System (please complete the following information):**
 - OS:  MacOS (server is running on Linux, Raspbian, Raspberry Pi 4)
 - Virtualization: none
 - Clients: Browser, Android
 - Browser: Firefox 75
 - Jellyfin Version: 10.5.5
 - Playback: Transcode, I think? 
 - Installed Plugins: none
 - Reverse Proxy: Caddy
 - Base URL: /
 - Networking: Host? Just a regular LAN
 - Storage: local

**To Reproduce**

0. [Enable the OMX hardware acceleration on Raspberry Pi](https://jellyfin.org/docs/general/administration/hardware-acceleration.html#raspberry-pi-3-and-4)
1. Get a mkv file with PGS subtitles that need to be burned in (I don't really know how this works -- MP4s with soft subs don't have this problem)
2. Enable a subtitle track before playing
3. Play the file

**Expected behavior**

The video should play, I suppose. And from that reddit thread, the other commenter helping me said that the "unspecified size" logs should not happen either, like a bug that was thought to have been fixed already. That might be a separate issue, not sure.

**Logs**

See logs from both a working stream (no subs) and non-working stream (with subs) here: https://gist.github.com/mholt/1511cf85f8ca983bdd6ddd93ba430e07

**Screenshots**

n/a

**Additional context**

When subs are enabled, it's just a black screen forever, and the web UI kinda freezes and I have to reload it to go back.

Let me know what other information you need!

**Comment by mholt** [comment]
Oh nooooo don't close it 😭

**Comment by mholt** [comment]
I am not aware that this is fixed; please leave open.

**Comment by mholt** [comment]
Not fixed yet.

**Comment by sparky002** [comment]
I get the same error although I'm not using a raspi. Using the latest Jellyfin docker on Unraid.

**Comment by nyanmisaka** [comment]
Not an issue. The processor of RPI4 cannot handle subtitle burn-in.

**Comment by mholt** [comment]
Sorry, but what do you mean, it "cannot handle" it?

**Comment by nyanmisaka** [comment]
Software based subtitle burn-in is a cpu intensive task, the cpu of Pi4 is not fast enough to do it on the fly.

**Comment by mholt** [comment]
Can the GPU perform this?

**Comment by nyanmisaka** [comment]
GPU scaling filter hasn’t been implemented yet, not to mention the GPU overlay filter.
https://github.com/jc-kynesim/rpi-ffmpeg/issues/42

**Comment by EliteElectronic** [comment]
With hardware acceleration enabled, I found PGS Subtitles ONLY work on the Jellyfin Media Player APP Windows version.
All others does not work! I also tried Jellyfin Media Player APP on Roku DOES NOT work.  
Why only Jellyfin Media Player APP Windows version work ??? !!!
My main player is Jellyfin Media Player APP on Roku and all of my movies are Bluray rip with PGS Subtitles.
Jellyfin team, please look into this and make hardware acceleration PGS Subtitles work everywhere !
Thank you !!!
