### ISSUE TITLE
Hidden files "._" created by Mac OS cause duplicate library items in Windows 10

### ISSUE THREAD

**Issue by bringmecoffeeortea** [jellyfin/jellyfin#3032]
My media is on an external drive formatted exFAT that is accessed by Mac OS and Windows 10 via Bootcamp. I usually use Plex and just tried Jellyfin. The initial scan resulted in duplicate entries for almost all TV episodes and movies (two posters, etc.). I determined that a separate entry is being created for hidden files (e.g. movie.mkv and ._movie.mkv). In addition to the awkwardness of the duplicate entry, trying to play one of the hidden files causes Jellyfin to hang. I understand the Mac OS creates these files. Something to do with the file system 
[https://support.jungledisk.com/hc/en-us/articles/200812844-Why-are-we-seeing-copies-of-files-starting-with-periods-and-underscores-in-Windows-
](https://support.jungledisk.com/hc/en-us/articles/200812844-Why-are-we-seeing-copies-of-files-starting-with-periods-and-underscores-in-Windows-)

**System (please complete the following information):**
 - OS: OS Catalina and Windows 10
 - Virtualization: don't know what this means
 - Clients: Browser
 - Browser: Firefox
 - Jellyfin Version: 10.5.5 stable
 - Playback: 
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: ?
 - Networking: 
 - Storage: local

**Comment by Artiume** [comment]
So there's two things we could do. Fix your file system or add an ignore rule for `._*`. Once the ignore rule is made, the scanner will still scan the duplicates, making your scan take longer. 

Your link is a trap by the way, try clicking it ;). I think this bug should be added to the docs as a warning to others. From the link, I found this advise.

> Or, if you'd rather run a command that causes all files and folders beginning with a period (to include period-underscore files) to become invisible, open Command Prompt, then run this: `attrib +H J:\.* /S /D` (but be sure to change the drive from J to the drive letter of your choice)
Note that this attrib option will run through every file and folder on your drive, so this could take quite a long time, depending on the size of your disk.

**Comment by bringmecoffeeortea** [comment]
Ha, thanks I fixed the link. 

I used to run Paragon HFS+ so I could read the Mac drive from Windows, but I found it a bit funky so now I'm using exFAT so both operating systems can read the media.

An ignore rule sounds like the best option. The files were hidden in Windows 10 as well, but the scanner still saw them. I assume invisible/hidden means the same.

**Comment by rigtorp** [comment]
Need to add a ignore rule here: Emby.Server.Implementations/Library/CoreResolutionIgnoreRule.cs

**Comment by rigtorp** [comment]
Or maybe here https://github.com/jellyfin/jellyfin/blob/07c4dfd8fe7331b80389ae5002397ae134b14f9e/Emby.Server.Implementations/IO/LibraryMonitor.cs#L53
