### ISSUE TITLE
Add the function of playing videos from OneDrive or Google Drive directly

### ISSUE THREAD

**Issue by jy3344511** [jellyfin/jellyfin#3036]
If the jellyfin can play videos from OneDrive or Google Drive directly，that's awesome。

**Comment by Artiume** [comment]
There is a feature request for this at https://features.jellyfin.org/posts/348/cloud-direct-stream

Until a plugin is created to handle this feature, you have to use something such as rclone to mount your drives. Closing ticket.

**Comment by chiragnahata** [comment]
How to add it ?

**Comment by 3bagorion33** [comment]
Yeah, I'd like to know that too. Very detailed guide for dummies on how to install an app on Windows, but not a line about non-obvious things. Lost one user in my face, bye.
