### ISSUE TITLE
Fedora 32 is out and emby packages are only for 31

### ISSUE THREAD

**Issue by yodatak** [jellyfin/jellyfin#3040]
Hi there is i think some low changes so i think adapting for fedora 32 seem to be easy ;)
The 31 version install for now i have to test if all works !

**Comment by yodatak** [comment]
I just rebuild it on Fedora 32 its work with using this 
```
wget https://repo.jellyfin.org/releases/server/fedora/jellyfin-10.5.5-1.fc31.src.rpm
sudo dnf builddep jellyfin-10.5.5-1.fc31.src.rpm
rpmbuild --rebuild jellyfin-10.5.5-1.fc31.src.rpm

```
And i got jellyfin-10.5.5-1.fc32.x86_64.rpm :tada:

**Comment by Artiume** [comment]
> Fedora 32 is out and emby packages are only for 31

Who's package? 😜

**Comment by yodatak** [comment]
Hi maybe we have to make a modification of this file for build for fedora 31 and fedora 32 ?
https://github.com/jellyfin/jellyfin/blob/master/deployment/Dockerfile.fedora.amd64
https://github.com/jellyfin/jellyfin/blob/master/deployment/build.fedora.amd64
https://github.com/jellyfin/jellyfin/blob/master/.ci/azure-pipelines-package.yml
https://github.com/jellyfin/jellyfin/blob/master/build.yaml
Maybe duplicate the fedora build to build Fedora 31 and 32 ?
