### ISSUE TITLE
Jellyfin Doesn't Handle Episodes with Decimal Points

### ISSUE THREAD

**Issue by SethiPandi** [jellyfin/jellyfin#3047]
**Describe the bug**
Some shows have an episode 2.5, or 10.5, for example. I believe there can be many reasons for this such as a special OVA which gets dubbed an episode number, or to release something when something is delayed which recaps back in the show, etcetc

When we have an episode 2.5, however, it gets displayed as episode 2, with episode 2 metadata.

**System (please complete the following information):**
 - OS: Ubuntu 18.04
 - Virtualization: Docker / Docker Compose
 - Clients: Browser
 - Browser: Firefox 75 and Chromium 81.0.4044.129
 - Jellyfin Version: 10.5.4
 - Playback: N/A
 - Installed Plugins: None
 - Reverse Proxy: None
 - Base URL: None
 - Networking: Host
 - Storage: Local

**To Reproduce**
1. Add a show that has a ".5" episode in it, such as Goblin Slayer.
2. Visit its episode selection.
3. See a duplicate episode.

**Expected behavior**
I would expect it to use the number specified, ie "10.5", not "10", even if it doesn't match an episode (ie database/API doesn't return a result) it should still say the episode number in the file name at the very least.

**Screenshots**
![image](https://user-images.githubusercontent.com/22801583/80923464-47525900-8d84-11ea-94da-11632d5ad3af.png)

![image](https://user-images.githubusercontent.com/22801583/80923474-56390b80-8d84-11ea-894e-bb5273c382f9.png)

![image](https://user-images.githubusercontent.com/22801583/80923571-e7a87d80-8d84-11ea-812f-33488deb6bb2.png)

**Comment by Artiume** [comment]
This is the main regex issue tracker. If you want to add your details there, that'd be helpful

**Comment by SethiPandi** [comment]
I can confirm this issue persists in 10.6.4.
I'll just close the issue however as this is a part of #2441 and further discussion is taking place there.
