### ISSUE TITLE
jellfin 10.5.5 cpu usage is keeping run about 18% on ubuntu 18.04.4

### ISSUE THREAD

**Issue by kent79** [jellyfin/jellyfin#3051]
This is a new install machine. After I installed Jellyfin, I type "top" command. It find out jellfin process as below is keeping run.
/usr/bin/jellyfin --restartpath=/usr/lib/jellyfin/restart.sh --ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg

**Comment by plexxman** [comment]
Provide more details, logs, use the template.

**Comment by kent79** [comment]
658 jellyfin  20   0 4422564 139156  69344 S  18.2  1.9   1:25.74 jellyfin

Above is the "top" command info. , 18.2 is 18.2% cpu usage. The server is idle, but the cpu is keeping ruuning. I try to kill the process, but it will be re run again. There is work fine for server, exception of this issue. I don't know is it normal.

**Comment by mknart** [comment]
I have the same issue and think I have narrowed it down. By disabling UPnP, the CPU usage is down from twenty percent to below one when idle. 

In settings.xml:
```
<EnableUPnP>false</EnableUPnP>
```

**Comment by kent79** [comment]
It works. Many Thanks

**Comment by jeroen7s** [comment]
had same issue, disabling UPnP fixed it for me as well.
Why does that feature consume so much CPU?

**Comment by robocopAlpha** [comment]
> In settings.xml:
> 
> ```
> <EnableUPnP>false</EnableUPnP>
> ```

This worked for me as well. Thanks @mknart !

**Comment by robocopAlpha** [comment]
> In settings.xml:
> 
> ```
> <EnableUPnP>false</EnableUPnP>
> ```

This worked for me as well, although for me the setting was in ```system.xml```. Thank you @mknart !

**Comment by ThibaultNocchi** [comment]
This also worked for me. I guess it is probably linked to #2589 and maybe the PR #3383 could somehow help resolving this.

**Comment by BaronGreenback** [comment]
SSDP DeviceDiscovery isn't filtered. Whilst not a great CPU hog - it will be part.

We could be limitted down to  urn:schemas-upnp-org:device:MediaRenderer and urn:schemas-upnp-org:device:MediaServer

Is there any other devices we need?

**Comment by BaronGreenback** [comment]
Been playing with implementing DLNA subscriptions.

DLNA PlayTo is currently setup to start a 1 second timer that polls the device, the moment a DLNA device is detected regardless of whether it is used or not. My forthcoming PR will delay this until the first interaction with the device.

Again, not a lot - but it's something.
