### ISSUE TITLE
Significant distortion on audio

### ISSUE THREAD

**Issue by tknx** [jellyfin/jellyfin#3055]
**Describe the bug**
On specific scenes (e.g., typically those that are somewhat loud to begin with), significant distortion happens with popping noises as compared to the same scene in Plex.

**System (please complete the following information):**
 - OS: Slackware Unraid
 - Virtualization: Docker
 - Clients: Mac OS X
 - Browser: Chrome 81
 - Jellyfin Version: 10.5.5
 - Playback: No idea
 - Installed Plugins: None
 - Reverse Proxy: None
 - Base URL: N/A
 - Networking: Bridge
 - Storage: Local server

**To Reproduce**

1. Go to '...': Movie with loud audio (e.g., The Dark Knight Rises when we see the flying vehicle come out of the alley)
2. Click on '....': Wait for a loud noise
3. See error: Hear significant audio distortion and popping even if the volume of Jellyfin is set quite low. 

**Expected behavior**
Better audio quality and no popping

**Logs**

**Screenshots**

**Additional context**

**Comment by Artiume** [comment]
Are any ffmpeg logs produced?

**Comment by tknx** [comment]
Here is the ffmpeg log I have from today...
[log_20200504.log](https://github.com/jellyfin/jellyfin/files/4578383/log_20200504.log)

**Comment by Artiume** [comment]
Those are your system logs, ffmpeg logs should be generated alongside those logs.

**Comment by tknx** [comment]
I am not seeing ffmpeg logs in that folder
<img width="436" alt="Screen Shot 2020-05-13 at 09 49 00" src="https://user-images.githubusercontent.com/29260341/81841237-ff0f0580-94fe-11ea-9092-8c4ea5905441.png">

If there is a setting to turn it on, happy to do so.

**Comment by Artiume** [comment]
If there's no ffmpeg logs, no transcoding/conversion involved and the original audio is causing the issue. Can you pay the media directly in the browser and see if it occurs

**Comment by tknx** [comment]
Now I have an ffmpeg log - no idea why it suddenly appeared in the folder.

These are the most recent few - the key static occurs at 50:54

[ffmpeg-transcode-67ee6721-2e25-4201-a23e-350a8ac0354d.txt](https://github.com/jellyfin/jellyfin/files/4623847/ffmpeg-transcode-67ee6721-2e25-4201-a23e-350a8ac0354d.txt)

[ffmpeg-transcode-67ee6721-2e25-4201-a23e-350a8ac0354d.txt](https://github.com/jellyfin/jellyfin/files/4623853/ffmpeg-transcode-67ee6721-2e25-4201-a23e-350a8ac0354d.txt)

[ffmpeg-transcode-00659f10-6c34-4e0b-b6b2-08de256f63b6.txt](https://github.com/jellyfin/jellyfin/files/4623855/ffmpeg-transcode-00659f10-6c34-4e0b-b6b2-08de256f63b6.txt)
