### ISSUE TITLE
Add Integration Tests

### ISSUE THREAD

**Issue by mark-monteiro** [jellyfin/jellyfin#3057]
This is a tracking issue for adding integration tests to each endpoint in the server. 

This task is part of the migration to the ASP.NET Web API and should target the **old** ServiceStack endpoints. Once these integration tests are in place for the old endpoints on the `master` branch, they can be updated on the `api-migration` feature branch to use the migrated ASP.NET Web API endpoints in order to help ensure that no breaking changes have occurred during the migration.

Some guidance on writing these integration tests:

1. Integration tests have already been completed for the BrandingService endpoints (see [source](https://github.com/jellyfin/jellyfin/blob/master/tests/MediaBrowser.Api.Tests/BrandingServiceTests.cs)). It can be used as a rough guide for how to implement the tests for other services.
1. According to the Microsoft guidelines for writing integration tests:

   > Don't write integration tests for every possible permutation of data and file access with databases and file systems. Regardless of how many places across an app interact with databases and file systems, a focused set of read, write, update, and delete integration tests are usually capable of adequately testing database and file system components. Use unit tests for routine tests of method logic that interact with these components. In unit tests, the use of infrastructure fakes/mocks result in faster test execution.
  
   In general, each endpoint should have a single test that checks for a successful response from that endpoint. Integration tests do not need to test error responses, nor do they need to test every single permutation of input parameters.

**Emby.Dlna/Api**
- [ ] DlnaServerService [19]
- [ ] DlnaService [6]

**Emby.Notifications/Api**
- [ ] NotificationsService [7]

**MediaBrowser.Api**
- [x] BrandingService [3]
- [ ] ChannelService [5]
- [ ] ConfigurationService [6]
- [ ] DisplayPreferencesService [2]
- [ ] EnvironmentService [7]
- [ ] FilterService [2]
- [ ] ItemLookupService [12]
- [ ] ItemRefreshService [1]
- [ ] ItemUpdateService [3]
- [ ] LocalizationService [4]
- [ ] PackageService [4]
- [ ] PlaylistService [5]
- [ ] PluginService [8]
- [ ] SearchService [1]
- [ ] SuggestionsService [1]
- [ ] TvShowsService [4]
- [ ] UserService [14]
- [ ] VideosService [3]
**/Attachments**
- [ ] AttachmentService [1]
**/Devices**
- [ ] DeviceService [7]
**/Images**
- [ ] ImageByNameService [6]
- [ ] ImageService [44]
- [ ] RemoteImageService [4]
**/Library**
- [ ] LibraryService [25]
- [ ] LibraryStructureService [8]
**/LiveTv**
- [ ] LiveTvService [39]
**/Movies**
- [ ] CollectionService [3]
- [ ] MoviesService [1]
- [ ] TrailersService [1]
**/Music**
- [ ] AlbumsService [2]
- [ ] InstantMixService [7]
**/Playback**
- [ ] MediaInfoService [5]
- [ ] UniversalAudioService [4]
**/Hls**
- [ ] DynamicHlsService [8]
- [ ] HlsSegmentService [5]
- [ ] VideoHlsService [1]
**/Progressive**
- [ ] AudioService [4]
- [ ] VideoService [40]
**/ScheduledTasks**
- [ ] ScheduledTaskService [5]
**/Sessions**
- [ ] ApiKeyService [3]
- [ ] SessionService [16]
**/Subtitles**
- [ ] SubtitleService [7]
**/System**
- [x] ActivityLogService [1]
- [ ] SystemService [10]
**/UserLibrary**
- [ ] ArtistsService [3]
- [ ] GenresService [2]
- [ ] ItemsService [3]
- [ ] MusicGenresService [2]
- [ ] PersonsService [2]
- [ ] PlaystateService [9]
- [ ] StudiosService [2]
- [ ] UserLibraryService [10]
- [ ] UserViewsService [2]
- [ ] YearsService [2]

**MediaBrowser.WebDashboard/Api**
- [ ] DashboardService [6]

**Comment by mark-monteiro** [comment]
@jellyfin/backend Looking for feedback or other guidelines that could be added here for writing the integration tests. They are working for one service already, but it is a very simple one so there may be some other nuanced scenarios we need to think about to put in the guidelines

**Comment by crobibero** [comment]
How will authentication work? Are we going to use Moq, or how are we going to test for data existing

**Comment by mark-monteiro** [comment]
> How will authentication work? Are we going to use Moq, or how are we going to test for data existing

Hmm good questions, maybe I should have implemented tests for a more involved service before creating this issue haha. I haven't thought about how to do those things yet, I specifically chose a simple controller just to get something working. Maybe someone should just get those things working for as an example and open a PR so we can discuss there, I would probably be fine with any approach that works.

**Comment by crobibero** [comment]
I just tried playing with an authenticated endpoint. I think we need a static database for testing, or at least a static admin user / regular user.

When we move to non self-rolled auth we can use this: https://github.com/DOMZE/fake-authentication-jwtbearer

**Comment by cvium** [comment]
See https://cov.b0n.dev/jellyfin/
