### ISSUE TITLE
Dull colors after transcoding HEVC

### ISSUE THREAD

**Issue by rderensy** [jellyfin/jellyfin#3058]
**Media Info of the file**
Title: 4K HEVC
Codec: HEVC
Profile: Main 10
Level: 150
Resolution: 3840x2160
Aspect ratio:16:9
Interlaced: No
Framerate: 25
Bitrate: 12405 kbps
Pixel format: yuv420p10le
Ref frames: 1

**Stats for Nerds Screenshots**
[Here's](https://imgur.com/cJY2Wrl) the video played with VLC on my computer, and [here's](https://imgur.com/5JKwaKn) the same scene played in Jellyfin.
Transcoding is set to preset Medium and CRF 18.

**Server System (please complete the following information):**
 - OS: Debian 10.3
 - Jellyfin Version: 10.5.5-1
 - Hardware settings & device: 4 cores virtualized, no hardware acceleration, 4GB of memory
 
**Client System (please complete the following information):**
 - Device: Custom computer + Dell laptop + Apple iPhone 7 and 11 Pro
 - OS: Windows 10, Fedora and iOS 13
 - Client: Web Browser and Jellyfin iOS app
 - Browser (if Web client): Firefox
 - Client and Browser Version: Firefox 76.0, Jellyfin iOS app 1.1.1(1)

**Comment by Kiina** [comment]
Are you trying to watch HDR content on a SDR monitor? If yes, everything is working as intended. VLC tries to do terrible tone-mapping on the HDR content to SDR while jellyfin leaves it alone

**Comment by rderensy** [comment]
Oh, I haven't thought about that. Since this file on Plex was looking the same as in VLC, I assumed it was a Jellyfin problem, but the video is HDR indeed, thank you!

**Comment by wobblywob** [comment]
Don't know if it's relevant, but I'm seeing a similar thing transcoding a 50 GB file - top left plex, then VLC, bottom Jellyfin ([pic](https://imgur.com/a/RfRvRbk)). I don't know exactly how the file is supposed to look like, but Jellyfin is noticeably duller. Both are transcodes of the highest possible quality, Plex says "Convert to 4K Maximum 51.7 Mbps" whereas Jellyfin shows Quality 4k - 120 Mbps. I don't know enough about these things to tell you more. The dullness looks the same on a retina macbook and a 34” UWQHD (3440 x 1440) panel.

This is the playback data from jellyfin:
```
Playback Info
Player:Html Video Player
Play method:Transcode
Protocol:https
Stream type:HLS
Video Info
Player dimensions:1243x675
Video resolution:3840x2160
Dropped frames:300
Corrupted frames:0
Transcoding Info
Video codec:H264
Audio codec:MP3
Bitrate:103.7 Mbps
Transcoding progress:8.7%
Transcoding framerate:21 fps
Reason for transcoding:SubtitleCodecNotSupported
Original Media Info
Container:webm
Size:59.2 GiB
Bitrate:52.1 Mbps
Video codec:HEVC Main 10
Video bitrate:51.7 Mbps
Audio codec:TRUEHD
Audio channels:8
Audio sample rate:48000 Hz
Audio bit depth:24
```

**Comment by nyanmisaka** [comment]
> Don't know if it's relevant, but I'm seeing a similar thing transcoding a 50 GB file - top left plex, then VLC, bottom Jellyfin ([pic](https://imgur.com/a/RfRvRbk)). I don't know exactly how the file is supposed to look like, but Jellyfin is noticeably duller. Both are transcodes of the highest possible quality, Plex says "Convert to 4K Maximum 51.7 Mbps" whereas Jellyfin shows Quality 4k - 120 Mbps. I don't know enough about these things to tell you more. The dullness looks the same on a retina macbook and a 34” UWQHD (3440 x 1440) panel.
> 
> 
> 
> This is the playback data from jellyfin:
> 
> ```
> 
> Playback Info
> 
> Player:Html Video Player
> 
> Play method:Transcode
> 
> Protocol:https
> 
> Stream type:HLS
> 
> Video Info
> 
> Player dimensions:1243x675
> 
> Video resolution:3840x2160
> 
> Dropped frames:300
> 
> Corrupted frames:0
> 
> Transcoding Info
> 
> Video codec:H264
> 
> Audio codec:MP3
> 
> Bitrate:103.7 Mbps
> 
> Transcoding progress:8.7%
> 
> Transcoding framerate:21 fps
> 
> Reason for transcoding:SubtitleCodecNotSupported
> 
> Original Media Info
> 
> Container:webm
> 
> Size:59.2 GiB
> 
> Bitrate:52.1 Mbps
> 
> Video codec:HEVC Main 10
> 
> Video bitrate:51.7 Mbps
> 
> Audio codec:TRUEHD
> 
> Audio channels:8
> 
> Audio sample rate:48000 Hz
> 
> Audio bit depth:24
> 
> ```

Please configure and enable the HDR tone mapping in jellyfin 10.7.

**Comment by wobblywob** [comment]
@nyanmisaka thank you! I had someone explain HDR to me since then and it makes sense now.
