### ISSUE TITLE
Tv show(anime): episode sequence is wrong when using absolute display order

### ISSUE THREAD

**Issue by kerhbal** [jellyfin/jellyfin#3062]
**Describe the bug**
for anime, episode sequence is wrong when using absolute display order
in my case, **there is no mismatch**, just the sequence is wrong.

**System (please complete the following information):**
 - OS: Linux raspberrypi 4.19.66-v7+ #1253 SMP armv7l
 - Virtualization: none
 - Clients: browser
 - Browser: Safari 13.0.5
 - Jellyfin Version: Jellyfin.Server 10.5.5.0
 - Playback: not related
 - Installed Plugins: AudioDB, MusicBrainz 
 - Reverse Proxy: none
 - Base URL: none
 - Networking: host
 - Storage: local

**To Reproduce**
**My folder:**(I copied these two episodes to a new library just as a test case)
```
.
└── Naruto
    └── s01
        ├── Naruto.s01e001.x264_aac.mkv
        └── Naruto.s01e036.x264_acc.mkv
```
- when using aired display order(the normal one):
you can see the episode1 and episode36 are in the correct order
<img width="1229" alt="Xnip2020-05-06_18-22-16" src="https://user-images.githubusercontent.com/11629684/81244256-e32bd100-8fdf-11ea-8bfd-8d3ebebc313e.png">

- when using absolute display order:
you can see that the titles are correct, which means there is no mismatch, but the number before titles are both `1`, and the sequence is wrong
<img width="1210" alt="Xnip2020-05-06_21-15-05" src="https://user-images.githubusercontent.com/11629684/81244378-43bb0e00-8fe0-11ea-893f-e9273a59fcf7.png">

**Expected behavior**
in both scenarios(aired or absolute display order), the episode with title "Enter: Naruto Uzumaki!"(the first episode) should list before any other episodes.

Thank you!

**Comment by Artiume** [comment]
related issues
https://github.com/jellyfin/jellyfin/issues/1180
https://github.com/jellyfin/jellyfin/issues/2446

**Comment by dominikh** [comment]
This doesn't really seem related to either of those issues.

What I think is happening here is that the episode number field in the metadata gets incorrectly populated from the season-based numbering, not the absolute numbering.

For example, consider https://www.thetvdb.com/series/is-this-a-zombie

When using absolute display order, this occurs: 

![image](https://user-images.githubusercontent.com/39825/85345124-ec222480-b4f1-11ea-882b-ddcecb922c19.png)

The first three "episode 1" are the first episodes in season 2, season 1 and season 0 respectively. Looking at the metadata, all 3 episodes have season 1 and episode 1. The same pattern continues with the other episodes.

The incorrect sorting is then merely a side-effect of sorting on the incorrect episode numbers. All 1's followed by all 2's and so on.

**Comment by kerhbal** [comment]
@dominikh this totally makes sense, thank you for sharing!

**Comment by lmaonator** [comment]
Ran into the same issue.

It seems like the Tvdb plugin correctly queries the metadata with absoluteNumber but then doesn't handle "absolute" order in MapEpisodeToResult():
https://github.com/jellyfin/jellyfin/blob/93fe595e5e9863874c1973e4f2d7f3c85549d3f9/MediaBrowser.Providers/Plugins/TheTvdb/TvdbEpisodeProvider.cs#L151-L163
It seems to only check for "dvd" order if I understand it right.

**Comment by lmaonator** [comment]
I can't reproduce this for episode 36 in the OP, only for S02E01 which is absolute order E58 as explained by @dominikh above.
I submitted a pull request for that case.
