### ISSUE TITLE
Grouping not working as expected

### ISSUE THREAD

**Issue by conkydong** [jellyfin/jellyfin#3064]
Grouping does not work as expected. One can group the movies manually, but each movie is still listed as a single movie, so there are duplicates. But if one clicks on one of these duplicates, the other grouped versions here are selectable.

Furthermore I noticed in my „Cube“ trilogy that although „Cube Zero“ is included in the automatically generated collection, it also stands alone. Movies grouped into a collection shouldn't be listed outside the collection.

 - OS: OpenMediaVault 5 (Debian Buster)
 - Virtualization: Docker
 - Jellyfin Version: 10.5.5
 - Installed Plugins: AudioDB (10.5.5.0), Email Notifications (4.0.0.0), Fanart (4.0.0.0), Kodi Sync Queue (4.0.0.0), musicBrainz (10.5.5.0), Open Subtitles (7.0.0.0), TMDb Box Sets 5.0.0.0
 - Networking: Host
 - Storage: 2x 8TB HDD as 16GB Stripe, 1x 3TB HDD, 1x 4TB HDD

**To Reproduce**
1. Select movies for grouping
2. Click on ... -> group movies

**Expected behavior**
Grouped Movies should be listed as one movie without duplicates.

**Screenshots**
[https://imgur.com/a/jUvmV9R](https://imgur.com/a/jUvmV9R)
[https://imgur.com/a/ovhxaC3](https://imgur.com/a/ovhxaC3)

**Comment by Artiume** [comment]
Related https://github.com/jellyfin/jellyfin/issues/3064

**Comment by Artiume** [comment]
Fixed by https://github.com/jellyfin/jellyfin/pull/3117

**Comment by 1024mb** [comment]
This problem is still happening on 10.6.2.
