### ISSUE TITLE
Movie-type libraries don't respect folder structure the way Mixed Content does

### ISSUE THREAD

**Issue by ToxicFrog** [jellyfin/jellyfin#3073]
**Describe the bug**
When a Movie collection is created, it flattens all movies found into a single long list, discarding all folder structure. Unlike Mixed Content collections, there is no option to "sort by subfolders" and no display of subfolders.

Collections are meant to be a workaround for this, but are currently broken (#2826 et al) and are an imperfect replacement even when working, since they can't be nested -- e.g. there is no way to replicate a folder structure like "Courses -> {general topic} -> {semester} -> {course name} -> {lecture date}".

Mixed Content has other issues, but does properly display subfolders.

**System (please complete the following information):**
 - OS: NixOS
 - Virtualization: N/A
 - Clients: Browser & DLNA
 - Browser: Chrome 81
 - Jellyfin Version: 10.5.4
 - Playback: N/A
 - Installed Plugins: AudioDB, Open Subtitles, Kodi Sync Queue
 - Reverse Proxy: nginx
 - Base URL: /
 - Networking: host
 - Storage: local zfs

**To Reproduce**
Create a suitably structured movie library (where each * stands in for some number of video files, or directories containing single movies):
```
Test Library/
  Courses/
    Introductory Linguistics/*
    History of Writing Systems/*
  Documentaries/*
  * some other random movies in here too
```
Then import it as a library of type Movies.

Open the library and observe that every single movie in any of those subfolders has been smashed together into a single giant list. The "sort" setting is available, but there is no "folder sort" option as there is in Mixed Content libraries. "Filter" allows filtering by tags, but not by subfolders, and can't be used over DLNA in any case.

**Expected behavior**
It displays the "other random movies" along with "Courses" and "Documentaries" subfolders; opening one of those shows its contents. (I.e. similar behaviour to Mixed Content.)

**Comment by Artiume** [comment]
Part of the issue is probably https://github.com/jellyfin/jellyfin/issues/2691
