### ISSUE TITLE
Casting Movies with DirectPlay/DirectStream with unsupported subtitles not displayed does not work

### ISSUE THREAD

**Issue by StripedMonkey** [jellyfin/jellyfin#3079]
I've started digitizing some of my rather large DVD collection, and something I've noticed is that anything I've ripped personally isn't streamable for some reason. According to the logs it's something about subtitles, even if the subtitles are disabled. This is true of basically every movie or Series I've ripped using MakeMKV. I could potentially re-encode the subtitles to something else, but that would be less than desirable. Even not displaying subtitles would be a bit nicer than refusing to play altogether. Everything I've ripped  seems to have the same issue, I might be able to provide a clip/example if desired. 

I saw that there was a similar issue, #376 
**Media Info of the file**

[Example](https://github.com/jellyfin/jellyfin/files/4602790/mediainfo.txt)

**Logs**

```
jellyfin[2004]: [INF] Profile: Unknown Profile, Path: /<path>/Movie.mkv, isEligibleForDirectPlay: False, isEligibleForDirectStream: False
jellyfin[2004]: [INF] Not eligible for DirectPlay due to unsupported subtitles
jellyfin[2004]: [INF] Not eligible for DirectStream due to unsupported subtitles

```

**Server System (please complete the following information):**
 - OS: Linux (Ubuntu)
 - Jellyfin Version: Jellyfin.Server 10.5.5.0
 - Hardware settings & device: VAAPI fx-8320
 - Reverse proxy: N/A
 - Other hardware notes: None
 
**Client System (please complete the following information):**
 - Device: Google Pixel 3a to some Vizio TV
 - OS: Android 10
 - Client: Android App V1.0.0

**Comment by Artiume** [comment]
vobsub subtitles currently have to be burned in. We're working on using webvtt to display VOBSUB amd PGSSUB subtitles, but for now, it requires transcoding.

https://jellyfin.org/docs/general/clients/codec-support.html

**Comment by StripedMonkey** [comment]
I can understand that limitation, but currently my issue is that I can't play the movie with subs, without subs, or anything in between. It simply refuses to be played **at all**. Unless I stream a web tab on my phone I can't get squat to show up.
Even if the subtitles aren't compatible selecting a movie and trying to play it without subtitles is a reasonable expectation.

**Comment by Artiume** [comment]
On the page showing the media, do you have subtitles enabled or turned off?

**Comment by StripedMonkey** [comment]
If you're talking about on the mobile app yes, I've got the subtitles turned off. I assume that because the vobsub is in the mkv container it's being considered when playing no matter what.

**Comment by StripedMonkey** [comment]
Yes, it's still impossible to play a video which contains VobSub subtitles no matter if you've got subtitles enabled or disabled. While it would be nice to have subtitles the fact that an mkv which contains them cannot be played is the primary issue I have.

**Comment by daviddavo** [comment]
It doesn't work in the browser either.

I tried to download external subtitles, but it still refuses to play.

**Comment by StripedMonkey** [comment]
As in casting from the browser or actually playing them at all in the browser? Because if it's the latter that would be a separate issue.

**Comment by daviddavo** [comment]
I have transcoding disabled. If I enable transcoding, It seems to burn in the subtitles in the video stream and works fine, sorry for reopening the issue.

**Comment by tltucker** [comment]
If you use mkvtoolnix and embed a .SRT file, jellyfin recognizes it, and plays the subtitle correctly.

You can use mkvmerge and mkvextract to extract the sub file (it makes a pair of .idx/.sub files) and use vobsub2srt or this website: https://subconverter.com/convert-sub-idx-to-srt-online to convert it to .srt

That is a bit of hassle, but it does work.

**Comment by StripedMonkey** [comment]
Is this a replacement or adding it alongside? I have done something somewhat similar, but to be honest I'd like to be able to keep these files as "Original" straight from the disk as possible. In my case I've archived my DVD collection in original quality/content and done my best not to re-encode more than I have to.

**Comment by tltucker** [comment]
I had to use mkvtoolnix to remove/unmark the original subtitles, then add the .srt subtitles.. It worked very well.

**Comment by Bond-009** [comment]
Still an issue on the latest version?

**Comment by Bond-009** [comment]
Closing as stale (and can't reproduce with androidtv)
