### ISSUE TITLE
Changing directories of a library causes the library to be rebuilt from scratch

### ISSUE THREAD

**Issue by mahriman** [jellyfin/jellyfin#3080]
**Describe the bug**
If you manage a library and add a directory containing your media and remove the old directory from the library settings, Jellyfin will remove the references to the old directory and do a re-scan of the library, believing all the media files found in the the current directory are new.

**System (please complete the following information):**
 - OS: Windows 10
 - Jellyfin Version: 10.5.4
 - Storage: Moving from sshfs mounted directories to Samba/Windows File Sharing mounted drive letters.

**To Reproduce**
1. Have a functional library of your choosing, e.g. TV Shows, at one location.
2. Set up a secondary location for the same directory, e.g. an alternate mount point
3. Manage the library, add the new mountpoint and delete the old one and save.
4. Jellyfin will treat all files in the new path as new additions to the library as references to the old library no longer exist.

**Expected behavior**
It'd be nice if there could be some kind of check prior to deleting the references for the old path in the library if the basename is the same as the new path, or some kind of comparison of directory contents to see if they are virtually (exactly) the same. I get that the current behavior is expected, but I'm not sure it's the right way if one changes the the source of one's library files.

**Comment by mahriman** [comment]
Still an issue IMO

**Comment by VigibotDev** [comment]
Same problem here, multi terabytes library multiples days rescan is a pain. remember to make location abstraction mount on linux !

**Comment by hachre** [comment]
still the case in 2024
