### ISSUE TITLE
Collections doesn't respect Sort title

### ISSUE THREAD

**Issue by mahriman** [jellyfin/jellyfin#3082]
**Describe the bug**
Collections seem to always show contents sorted on year, rather than Sort title

**System (please complete the following information):**
 - Clients: Browser
 - Browser: Chrome 80
 - Jellyfin Version: 10.5.4

**To Reproduce**
1. Create collection and add a number of movies or tv shows
2. Change Sort title
3. (Entries are still sorted by Year)

**Expected behavior**
Jellyfin ought to respect the Sort titlel even in collections.

**Comment by mahriman** [comment]
Still doesn't respect sort title.

**Comment by Gsuss** [comment]
Hey! I ran over the same problem and you can change the sorting filter in the collection options. Go to the collection, show more options, edit labels and before the "Genres" there is an option "Show order". Sorry if the name is not exactly like that, I used the word-by-word translation.

**Comment by mahriman** [comment]
@Gsuss Thank you.
For reference, this is in the Edit metadata menu for the respective collection.
