### ISSUE TITLE
Album Art gets tiled (4 Squares) if Music Album folder contains playlist

### ISSUE THREAD

**Issue by iotku** [jellyfin/jellyfin#3088]
**Describe the bug**
During the initial scan of my music library most Album art is set correctly (presumably from the Musicbrainz DB) in a satisfactory manor, however should there be a m3u (or likely m3u8) file in the directory the Album also gets populated into the playlist section of my music library of which the playlist section shows Album Art in a tiled 4 square pattern.

The issue is that the 4 square title version of the Album art becomes the *main* image for the Album rather than just the main image of the album cover that previous existed in full size.

**To Reproduce**

1. Add an Album to a Music Libarary that contains a m3u or m3u8 playlist (linking to the tracks of the album)
2. Scan your library (Likely the first time should Album art exist in Musicbrainz the art will be correct) 
3. After a while (perhaps the next scan after the Album art exists), you will receive the annoying tiled version of the Album art as well as it existing in your playlist section of your Music Library

**Expected behavior**

The album art remains the full, non-tiled, version.

**Logs**
N/A

**Screenshots**
Example: https://i.imgur.com/Ix5tKuB.png

**System (please complete the following information):**
 - OS: Debian
 - Browser: Firefox, Chrome (Shouldn't matter)
 - Jellyfin Version: 10.4.3

Might be more related to jellyfin proper (didn't realize I was in web when I posted this), not certain if the interface is causing it or just the scan

**Comment by bastidest** [comment]
I have the same issue. It seems like it only applies to music **without embedded album art**. Music with embedded album art does not change:

![image](https://user-images.githubusercontent.com/1242917/81499744-07ccc500-92ce-11ea-8940-d4856965ddcc.png)

**Comment by andra5** [comment]
I also have this issue on the latest version (10.6.3)

**Comment by iotku** [comment]
Still having this issue in 10.7.0 (RC2)

**Comment by Deep-Six** [comment]
Having this issue  stil on debian package (Raspian) 10.7.5-1

**Comment by GitHubGeek** [comment]
Still an issue. Running latest official docker image

**Comment by GitHubGeek** [comment]
Hi @cvium apologies for mentioning you out of the blue.

This issue is definitely current - Can you please un-stale it? Thanks!

**Comment by wesleyeleazar** [comment]
10.7.7 and this also occurs on mine. Noticed that the albums with the tiled art indeed contain an m3u. But not all albums that contain an m3u are affected (yet). And just noticed that albums without an m3u have never been afflicted by this issue.

**Comment by tomnehek** [comment]
Can confirm this is still an issue.

**Comment by Whayme** [comment]
Is anyone aware of a workaround?

**Comment by wesleyeleazar** [comment]
> Is anyone aware of a workaround?

Confirmed that removing the m3u files relieved me of the issue. In my case, those files aren’t needed, anyway.

**Comment by chilipepperhott** [comment]
This is happening to me as well. Not big deal at all, but it does kind of defeat the purpose of having album art at all. If there is someone working on a fix, let me know. Otherwise I may look into it myself.

**Comment by tomnehek** [comment]
> Still an issue on 1.8.0 (docker).

Can confirm.

**Comment by jakelandau** [comment]
Still an issue on 10.7.7 Windows 10 x64. I'm concerned that this bug has been apparently present for several years without a fix.

**Comment by rom4nik** [comment]
This issue seems to have been fixed by upgrading my server to 10.8.2, which includes fix from #8163.
