### ISSUE TITLE
FFMPEG: Transcoding fail if audio as too much delay at start of the movie.

### ISSUE THREAD

**Issue by Ashyni** [jellyfin/jellyfin#3090]
When the client need audio transcoding.
FFMPEG error:
`Too many packets buffered for output stream 0:0.32:22.77 bitrate=N/A speed=N/A`
The other audio track doesn't have this issue, a slight timing difference between the two.
`Delay relative to video                  : 24s 0 ms`

**Media Info of the file**
https://pastebin.com/hGdTQvay

**Server Logs**
https://pastebin.com/8AnMhjKS

**FFmpeg Logs**
Failed Log:
https://pastebin.com/aibGDnFD

Workaround with `-max_muxing_queue_size 1024` `512 failed`
https://pastebin.com/x9Qv4A0k

Starting later `-ss 00:00:21.000` works too.

**Server System (please complete the following information):**
 - OS: [Docker on Linux]
 - Jellyfin Version: [10.5.5]
 - Hardware settings & device: [NVENC on GT710]
 - Reverse proxy: [Traefik]
 - Other hardware notes: [Media mounted from Google Drive]
 
**Client System (please complete the following information):**
 - OS: [Android, Windows]
 - Client: [Web/Browser]
 - Browser (if Web client): [Firefox, Chrome]
 - Client and Browser Version: [10.5.5 and 76.0]

**Comment by 64br137** [comment]
Override this issue by adding silence to the audio stream of the MKV. When the ffmpeg try to transcode the file and the stream has some delay to start (audio stream) got this error.
