### ISSUE TITLE
Refresh TV Guide  with XMLTV

### ISSUE THREAD

**Issue by mircoCampanella** [jellyfin/jellyfin#3097]
**Describe the bug**
the refreshguide remains blocked at 15% and if you try to stop it remains blocked

you can find the xml file here
www.epgitalia.tv/xml/guide.gzip

**Comment by Artiume** [comment]
The issue and current method of fixing it is inside this ticket. Resolving ticket as duplicate.

https://github.com/jellyfin/jellyfin/issues/1932
