### ISSUE TITLE
MPEG4 with NVDEC

### ISSUE THREAD

**Issue by LaG4ch3tt3** [jellyfin/jellyfin#3101]
**Describe the bug**

I have a problem with hardware acceleration with MPEG4 files. When I launch a file of this type there is no hardware decoding. However, the boxes are well checked but when I launch a film, the boxes are unchecked. There is no hardware decoding.

I don't have the problem with H264 and H265 files

**System (please complete the following information):**
 - OS: Debian 10
 - Virtualization: Docker
 - Browser: Chrome 81.0.4044.138
 - Jellyfin Version: 10.5.5
 - Playback: Transcode
 - Installed Plugins: none
 - Reverse Proxy: none
 - Graphic card: GTX 1650

**To Reproduce**

1. Go to 'playback'
2. Select Nvidia NVENC and check all the boxes, then save
3. Play a MPEG4 file
4. Open a new tab
5. Go to 'playback' and see the boxes for hardware decoding are unchecked

**Comment by Artiume** [comment]
From the looks of it, mpeg4 isn't supported by NVDEC

https://developer.nvidia.com/video-encode-decode-gpu-support-matrix

**Comment by LaG4ch3tt3** [comment]
Thank's for the reply. After some researches, I've found this doc : https://developer.nvidia.com/nvidia-video-codec-sdk.

The supported codecs are : MPEG-2, VC-1, H.264 (AVCHD), H.265 (HEVC), VP8, VP9
