### ISSUE TITLE
Removed library refuses to go away

### ISSUE THREAD

**Issue by dddddddavid** [jellyfin/jellyfin#3103]
**Describe the bug**

I created a new library for photos using the web interface. I later removed the library using 'remove library on the libraries tab of the dashboard.

The photos library still shows on the homepage; 'latest photos' are still shown on the homepage; 'Photos' is still shown on the metadata manager. Photos doe not show on the libraries page of the dashboard

**System (please complete the following information):**
 - OS: raspbian
 - Virtualization:
 - Clients: Firefox Ubuntu / Morph UT

 - Jellyfin Version: [e.g. 10.5.5]

 - Installed Plugins: [e.g. none, Fanart, Anime, etc.]
 - Reverse Proxy: [e.g.Apache.]
 
 - Storage: [local]

**To Reproduce**
1. Create new library - type Photos
2. Link to photos library folder on local drive
3. Wait an hour or so while it scans 13GB of photos
4. Decide it's a bit glitch
5 dashboard -> libraries -> click on the corner of 'photos' -> 'remove library
**Expected behavior**

Photos library disappears entirely from everywhere

**Logs**

Nothing there

**Screenshots**

**Additional context**

**Comment by dddddddavid** [comment]
Update - it finally disappeared 12+ hours later

**Comment by Gabriel-p** [comment]
@dddddddavid I believe you can close the issue yourself if it was reasolved

**Comment by telans** [comment]
@dkanada should be closed

**Comment by demaniak** [comment]
> Update - it finally disappeared 12+ hours later

It sounds like the scheduled library scan sorted out the issue.

I had similar problem - taking the hint from this, I triggered a full lib scan.
And yes, it seemed to resolve my issue also.
