### ISSUE TITLE
Android phone cant resume or skip ahead. Firestick 4k only plays a minute of a movie and then exits to choose a server screen

### ISSUE THREAD

**Issue by bnichs5** [jellyfin/jellyfin#3107]
Android phone cant resume or skip ahead. Firestick 4k only plays a minute of a movie and then exits to choose a serve screen.

I have a oneplus 6T with the latest software updates for android and this app. I was told the newest update would address the not being able to resume and skip ahead but its doesnt appear to have done so. I'm streaming .strm files and inside are links to a mp4 AVC movie with aac2.0 audio(This format is playable on almost every device known to man). I also disabled all transcoding. only directplay.

Something new on the Firstick 4k which I've never experienced before is that after 1 or 2 mins of playing a movie, it will exit out of the movie to the choose a server screen. I've tried with multiple movies and they each do this. 

The Server is windows 10 Jellyfin 10.5.5 Stable

Any help would be greatly appreciated. Thanks!

**Comment by Artiume** [comment]
.strm files are still having issues. Media which is local to the server has proper playback. The ticket tracking strm issues is here. It hasn't received a lot of traction since none of the dev use strm files. 
Closing ticket as duplicate. 
https://github.com/jellyfin/jellyfin/issues/2543
