### ISSUE TITLE
Can't set back the correct Identity for series

### ISSUE THREAD

**Issue by ggdaynight** [jellyfin/jellyfin#3109]
**Describe the bug**
- Had the correct Identity for the 'Dust' TV series
- Jellyfin changed it for something different (with meta update(?))
- If I try to set the Identity for the series with TheTVDB Id:: 357506,
   it finds the series (one item yellow blank poster, name: Dust, year 2016)
- Jellyfin doesn't change it

**System (please complete the following information):**
 - OS: Linux
 - Virtualization: Docker
 - Jellyfin Version: 10.5.5

**To Reproduce**
Check the description above.

**Expected behavior**
Change the metadata accordingly. 

**Logs**
jellyfin       | [13:38:09] [ERR] [35] MediaBrowser.Providers.TV.TheTVDB.TvdbSeriesProvider: Failed to retrieve actors for series 357506
jellyfin       | TvDbSharper.TvDbServerException: The given series ID does not exist; not found
jellyfin       |    at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
jellyfin       |    at TvDbSharper.Clients.SeriesClient.GetActorsAsync(Int32 seriesId, CancellationToken cancellationToken)
jellyfin       |    at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.TryGetValue[T](String key, String language, Func`1 resultFactory)
jellyfin       |    at MediaBrowser.Providers.TV.TheTVDB.TvdbSeriesProvider.FetchSeriesData(MetadataResult`1 result, String metadataLanguage, Dictionary`2 seriesProviderIds, CancellationToken cancellationToken)
jellyfin       | [13:38:15] [INF] [35] MediaBrowser.Api.ItemLookupService: Setting provider id's to item fed4f17d-b4ad-7e8c-8ec8-a99828f4bfda-Dust Up: {"Tvdb":"357506"}
jellyfin       | [13:38:15] [ERR] [90] MediaBrowser.Providers.TV.TheTVDB.TvdbSeriesProvider: Failed to retrieve actors for series 357506
jellyfin       | TvDbSharper.TvDbServerException: The given series ID does not exist; not found
jellyfin       |    at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
jellyfin       |    at TvDbSharper.Clients.SeriesClient.GetActorsAsync(Int32 seriesId, CancellationToken cancellationToken)
jellyfin       |    at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.TryGetValue[T](String key, String language, Func`1 resultFactory)
jellyfin       |    at MediaBrowser.Providers.TV.TheTVDB.TvdbSeriesProvider.FetchSeriesData(MetadataResult`1 result, String metadataLanguage, Dictionary`2 seriesProviderIds, CancellationToken cancellationToken)
jellyfin       | [13:38:15] [INF] [35] App: MovieDbProvider: Finding id for item: Dust
jellyfin       | [13:38:16] [ERR] [96] MediaBrowser.Providers.TV.TheTVDB.TvdbSeriesProvider: Failed to retrieve series with remote id tt1928499
jellyfin       | TvDbSharper.TvDbServerException: No records are found that match your query; Resource not found
jellyfin       |    at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
jellyfin       |    at TvDbSharper.Clients.SearchClient.SearchSeriesAsync(String value, String parameterKey, CancellationToken cancellationToken)
jellyfin       |    at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.TryGetValue[T](String key, String language, Func`1 resultFactory)
jellyfin       |    at MediaBrowser.Providers.TV.TheTVDB.TvdbSeriesProvider.GetSeriesByRemoteId(String id, String idType, String language, CancellationToken cancellationToken)
jellyfin       | [13:38:16] [ERR] [90] MediaBrowser.Providers.TV.TheTVDB.TvdbSeriesProvider: Failed to retrieve series with id null
jellyfin       | TvDbSharper.TvDbServerException: The given series ID does not exist; ID: 0 not found
jellyfin       |    at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
jellyfin       |    at TvDbSharper.Clients.SeriesClient.GetAsync(Int32 seriesId, CancellationToken cancellationToken)
jellyfin       |    at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.TryGetValue[T](String key, String language, Func`1 resultFactory)
jellyfin       |    at MediaBrowser.Providers.TV.TheTVDB.TvdbSeriesProvider.FetchSeriesData(MetadataResult`1 result, String metadataLanguage, Dictionary`2 seriesProviderIds, CancellationToken cancellationToken)
jellyfin       | [13:38:17] [ERR] [95] TmdbSeasonProvider: No metadata found for 2019
jellyfin       | MediaBrowser.Model.Net.HttpException: Not Found
jellyfin       |    at Emby.Server.Implementations.HttpClientManager.HttpClientManager.EnsureSuccessStatusCode(HttpResponseMessage response, HttpRequestOptions options)
jellyfin       |    at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
jellyfin       |    at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
jellyfin       |    at MediaBrowser.Providers.Tmdb.Movies.TmdbMovieProvider.GetMovieDbResponse(HttpRequestOptions options)
jellyfin       |    at MediaBrowser.Providers.Tmdb.TV.TmdbSeasonProvider.FetchMainResult(String id, Int32 seasonNumber, String language, CancellationToken cancellationToken)
jellyfin       |    at MediaBrowser.Providers.Tmdb.TV.TmdbSeasonProvider.DownloadSeasonInfo(String id, Int32 seasonNumber, String preferredMetadataLanguage, CancellationToken cancellationToken)
jellyfin       |    at MediaBrowser.Providers.Tmdb.TV.TmdbSeasonProvider.GetSeasonInfo(String seriesTmdbId, Int32 season, String preferredMetadataLanguage, CancellationToken cancellationToken)
jellyfin       |    at MediaBrowser.Providers.Tmdb.TV.TmdbSeasonProvider.GetMetadata(SeasonInfo info, CancellationToken cancellationToken)
jellyfin       | [13:38:17] [ERR] [90] TmdbSeasonProvider: No metadata found for 2020
jellyfin       | MediaBrowser.Model.Net.HttpException: Not Found
jellyfin       |    at Emby.Server.Implementations.HttpClientManager.HttpClientManager.EnsureSuccessStatusCode(HttpResponseMessage response, HttpRequestOptions options)
jellyfin       |    at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
jellyfin       |    at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
jellyfin       |    at MediaBrowser.Providers.Tmdb.Movies.TmdbMovieProvider.GetMovieDbResponse(HttpRequestOptions options)
jellyfin       |    at MediaBrowser.Providers.Tmdb.TV.TmdbSeasonProvider.FetchMainResult(String id, Int32 seasonNumber, String language, CancellationToken cancellationToken)
jellyfin       |    at MediaBrowser.Providers.Tmdb.TV.TmdbSeasonProvider.DownloadSeasonInfo(String id, Int32 seasonNumber, String preferredMetadataLanguage, CancellationToken cancellationToken)
jellyfin       |    at MediaBrowser.Providers.Tmdb.TV.TmdbSeasonProvider.GetSeasonInfo(String seriesTmdbId, Int32 season, String preferredMetadataLanguage, CancellationToken cancellationToken)
jellyfin       |    at MediaBrowser.Providers.Tmdb.TV.TmdbSeasonProvider.GetMetadata(SeasonInfo info, CancellationToken cancellationToken)
jellyfin       | [13:38:18] [ERR] [35] TmdbSeasonProvider: No metadata found for 2018
jellyfin       | MediaBrowser.Model.Net.HttpException: Not Found
jellyfin       |    at Emby.Server.Implementations.HttpClientManager.HttpClientManager.EnsureSuccessStatusCode(HttpResponseMessage response, HttpRequestOptions options)
jellyfin       |    at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
jellyfin       |    at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
jellyfin       |    at MediaBrowser.Providers.Tmdb.Movies.TmdbMovieProvider.GetMovieDbResponse(HttpRequestOptions options)
jellyfin       |    at MediaBrowser.Providers.Tmdb.TV.TmdbSeasonProvider.FetchMainResult(String id, Int32 seasonNumber, String language, CancellationToken cancellationToken)
jellyfin       |    at MediaBrowser.Providers.Tmdb.TV.TmdbSeasonProvider.DownloadSeasonInfo(String id, Int32 seasonNumber, String preferredMetadataLanguage, CancellationToken cancellationToken)
jellyfin       |    at MediaBrowser.Providers.Tmdb.TV.TmdbSeasonProvider.GetSeasonInfo(String seriesTmdbId, Int32 season, String preferredMetadataLanguage, CancellationToken cancellationToken)
jellyfin       |    at MediaBrowser.Providers.Tmdb.TV.TmdbSeasonProvider.GetMetadata(SeasonInfo info, CancellationToken cancellationToken)
jellyfin       | [13:38:18] [ERR] [96] TmdbSeasonProvider: No metadata found for 2016
jellyfin       | MediaBrowser.Model.Net.HttpException: Not Found
jellyfin       |    at Emby.Server.Implementations.HttpClientManager.HttpClientManager.EnsureSuccessStatusCode(HttpResponseMessage response, HttpRequestOptions options)
jellyfin       |    at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
jellyfin       |    at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
jellyfin       |    at MediaBrowser.Providers.Tmdb.Movies.TmdbMovieProvider.GetMovieDbResponse(HttpRequestOptions options)
jellyfin       |    at MediaBrowser.Providers.Tmdb.TV.TmdbSeasonProvider.FetchMainResult(String id, Int32 seasonNumber, String language, CancellationToken cancellationToken)
jellyfin       |    at MediaBrowser.Providers.Tmdb.TV.TmdbSeasonProvider.DownloadSeasonInfo(String id, Int32 seasonNumber, String preferredMetadataLanguage, CancellationToken cancellationToken)
jellyfin       |    at MediaBrowser.Providers.Tmdb.TV.TmdbSeasonProvider.GetSeasonInfo(String seriesTmdbId, Int32 season, String preferredMetadataLanguage, CancellationToken cancellationToken)
jellyfin       |    at MediaBrowser.Providers.Tmdb.TV.TmdbSeasonProvider.GetMetadata(SeasonInfo info, CancellationToken cancellationToken)
jellyfin       | [13:38:19] [ERR] [96] TmdbSeasonProvider: No metadata found for 2017
jellyfin       | MediaBrowser.Model.Net.HttpException: Not Found
jellyfin       |    at Emby.Server.Implementations.HttpClientManager.HttpClientManager.EnsureSuccessStatusCode(HttpResponseMessage response, HttpRequestOptions options)
jellyfin       |    at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
jellyfin       |    at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
jellyfin       |    at MediaBrowser.Providers.Tmdb.Movies.TmdbMovieProvider.GetMovieDbResponse(HttpRequestOptions options)
jellyfin       |    at MediaBrowser.Providers.Tmdb.TV.TmdbSeasonProvider.FetchMainResult(String id, Int32 seasonNumber, String language, CancellationToken cancellationToken)
jellyfin       |    at MediaBrowser.Providers.Tmdb.TV.TmdbSeasonProvider.DownloadSeasonInfo(String id, Int32 seasonNumber, String preferredMetadataLanguage, CancellationToken cancellationToken)
jellyfin       |    at MediaBrowser.Providers.Tmdb.TV.TmdbSeasonProvider.GetSeasonInfo(String seriesTmdbId, Int32 season, String preferredMetadataLanguage, CancellationToken cancellationToken)
jellyfin       |    at MediaBrowser.Providers.Tmdb.TV.TmdbSeasonProvider.GetMetadata(SeasonInfo info, CancellationToken cancellationToken)

**Comment by Artiume** [comment]
Can you update? 10.4.3 is old

**Comment by ggdaynight** [comment]
> Can you update? 10.4.3 is old

Sorry, I haven't updated that line. It's 10.5.5.
