### ISSUE TITLE
Admin-configurable streaming quality profiles

### ISSUE THREAD

**Issue by DesertCookie** [jellyfin/jellyfin#3112]
A client-universal implementation of remote streaming profiles that can be configured in the admin panel, to match the server's computing and connectivity capabilities.

Illustration:
![Example of the Configuration Page](https://i.imgur.com/YCU2VYU.png)

---

State: *In discussion*

# Why

* **Too many options currently**: [twenty-six](https://imgur.com/a/eri19p2)!
* **Options some people don't need**: for example, with 11Mbps server uplink 10 of 26 options are effectively useless.
* **More control for administrators**: to configure profiles fitting their library, hardware, and internet connection.
* **Better user experience**: through less clutter and potentially higher server performance.
* No more feature requests for new resolution options like [this one](https://features.jellyfin.org/posts/551/allow-1440p-playback).

# How

* Configurable list in the admin panel; for example in `Playback → Streaming`.
* When adding a profile: popup in which resolution, video codec and options, audio codec and options, etc. can be specified.
* Client asks the server for a list of available quality profiles when connecting to the server; determines which are available client-side: no 1080p option for 720p video (like currently).
* …

## Ideas

* Multiple video- and audio-codec settings per profile: `x264 10Mbps Fast CRF23` for 1080p30 video, `x264 15Mbps Fast CRF23` for 1080p60 video; `MP3 2.0 256Kbps` when `AAC 2.0 160Kbps` is not supported by the client.
* Specify a profile by simply pasting an FFmpeg CLI command.
* Allow profiles to be available in LAN/WAN/both.
* Allow profiles to be device-specific (e.g.: only available on desktop/mobile).
* …

---

### Current work-around for Jellyfin Web

By editing `qualityoptions.js` located in `…/Jellyfin/Server/jellyfin-web/components/`, the remote-streaming quality options displayed to clients using a webbrowser can be configured. For example:

```javascript
qualityOptions.push({ name: '1080p - 10 Mbps', maxHeight: 1080, bitrate: 10000001 });
```

---

Related FR: [Limit selectable video quality server-side](https://features.jellyfin.org/posts/431/limit-selectable-video-quality-server-side)

**Comment by DesertCookie** [comment]
_Anti-stale_

**Comment by HavermansStef** [comment]
Migrated to feature requests on features.jellyfin.org; 
https://features.jellyfin.org/posts/858/admin-configurable-streaming-quality-profiles

Issue to be closed.

**Comment by Wr0ngName** [comment]
Hello,

Just to summarize:

https://features.jellyfin.org/posts/858/admin-configurable-streaming-quality-profiles
https://features.jellyfin.org/posts/431/limit-selectable-video-quality-server-side
https://features.jellyfin.org/posts/551/allow-1440p-playback
https://github.com/jellyfin/jellyfin/pull/3928
And probably others...

What is the status of all this? It's been three years without any feedback anywhere.

I'd be happy to help but the current status about that is a mess. At this point, I am not even sure there isn't a PR lost somewhere with this already implemented.

Or maybe it is expected that everyone with this need will just have to modify the core files accordingly...

Thanks for the update.

**Comment by viniciusmr** [comment]
For anyone arriving late: 
The feature request is actually here: https://features.jellyfin.org/posts/431/limit-selectable-video-quality-server-side 
The above one was marked as duplicate. People are still actively commenting on it, but can't vote. And many don't notice the "duplicate" tag, so I'm posting just for better visibility.
