### ISSUE TITLE
Unused strings in the Localization Files

### ISSUE THREAD

**Issue by barronpm** [jellyfin/jellyfin#3120]
**Describe the bug**
Currently, the "HeaderCameraUploads" string in the localization files is unused and should be removed. Further investigation should be done on if there are other unused strings.

**Comment by jlechem** [comment]
I will remove the unused item.

**Comment by joshuaboniface** [comment]
Quoting my reply from #4308 

>Since these are all handled by Weblate, removing them here is not ideal as there will be bi-directional confusion (merge conflicts here, Weblate going screwy there).

>They waste a miniscule amount of space and don't hurt anything, and peacemeal cleanup is a pain until we get most of the strings normalized.

>I'm going to close this out; please don't be discouraged by this, it's just how the system is set up.

Basically, removing strings from translations - or making any changes to translations at all - should be done only through Weblate. I believe there's a mass-cleanup option of some kind, but I haven't looked into it in detail.

In effect the translation folder should be off-limits from the GitHub side.
