### ISSUE TITLE
Add VideoToolbox to FFmpeg HWA options

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin#3121]
VideoToolbox is the name of the low-level framework that provides access to Apple's encoding and decoding for H.264 and HEVC on macOS. It will automatically use an optimized software or hardware decoder, according to system configuration on a Macintosh computer.

We should integrate the option to select this for FFmpeg, as it would greatly improve the experience for macOS users. It would shift the burden from being entirely CPU, to using GPU when available.

Some relevant information here: https://brandur.org/fragments/ffmpeg-h265

The key options seem to be replacing `libx265` with `hevc_videotoolbox`, and replacing `libx264` with `h264_videotoolbox`.

**Comment by Artiume** [comment]
VideoToolBox looks to be built into ffmpeg already so we should be good on that end

**Comment by raouldc** [comment]
@anthonylavado @Artiume is this issue still valid?
It looks like VideoToolbox support was added [here](https://github.com/jellyfin/jellyfin/blob/ea0489a98e138b83277da36b6b1ff7f095285e05/MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs#L79) in this [PR](https://github.com/jellyfin/jellyfin/pull/2809)

**Comment by anthonylavado** [comment]
Implemented as of 10.6.0.
