### ISSUE TITLE
Add config option to perform database migrations manually

### ISSUE THREAD

**Issue by mark-monteiro** [jellyfin/jellyfin#3123]
As discussed [here](https://github.com/jellyfin/jellyfin/pull/2970#discussion_r424863646), users should have the option of performing database migrations manually instead of having the server perform them automatically at startup.

This provides two benefits:
1. Users can have control over how/when their database is migrated
2. The Jellyfin application does not need to have schema change permission on the database

The approach would be as follows (some pseudo code already exists [here](https://github.com/jellyfin/jellyfin/pull/2970#discussion_r424863646)):
- add a new config setting to determine if automatic migrations are enabled
- If automatic migrations are enabled, run them at startup
- If not enabled, check if the database is at the latest migration. If not, log the migration script to the console and throw an exception to fail startup

Adding the `discussion needed` tag so we can confirm whether we actually want this feature and, if we do, whether automatic migrations should be the default, or an opt-in option

**Comment by JustAMan** [comment]
Just to clarify - is this about migrations from raw sqlite to efcore, or about further migrations from one efcore version to another?

**Comment by mark-monteiro** [comment]
> Just to clarify - is this about migrations from raw sqlite to efcore, or about further migrations from one efcore version to another?

This is about making schema changes to the new EF core database, for example [this one](https://github.com/jellyfin/jellyfin/blob/master/Jellyfin.Server.Implementations/Migrations/20200514181226_AddActivityLog.cs) that created the `ActivityLogs` table in the database.

It's a bit confusing because there are also the other [migration routines](https://github.com/jellyfin/jellyfin/tree/master/Jellyfin.Server/Migrations/Routines), which we are using to transfer database from the old ones to the new EF ones. But I am not referring to those.

Our initial migrations should pretty much exclusively be creating tables, which is pretty safe but at some point we will eventually start adding migrations to change the schema for existing tables that contain data at which point we might have users that want to be more careful with how the data is migrated.

**Comment by cvium** [comment]
This is easily fixed with backups. Withholding migrations just means they can't run the server until they perform the migrations. Re-open on https://features.jellyfin.org if it's still wanted.
