### ISSUE TITLE
Remove 'partial' keyword from entity classes

### ISSUE THREAD

**Issue by mark-monteiro** [jellyfin/jellyfin#3125]
As discussed [here](https://github.com/jellyfin/jellyfin/pull/2970#discussion_r424870084), we no longer need the `partial` keyword on the EF model classes since they are no longer code-generated using the schema designer tool.

Adding the `discussion needed` tag because I think @EraYaN had some reservation about doing this.

**Comment by EraYaN** [comment]
The `partial` is very useful if you want to separate the data stuff with any other business logic. I do agree that is can make for confusing implementations, but we can make it work either way I think.

**Comment by mark-monteiro** [comment]
I agree that `partial` can be useful in certain scenarios, but in my experience it's more common to put business logic in a service class or something. IMO, for now, the `partial` keyword should be removed and can be added back in at a later date if that functionality is really needed for something.

**Comment by barronpm** [comment]
Fixes as of #4018
