### ISSUE TITLE
Fullscreen button

### ISSUE THREAD

**Issue by wille** [jellyfin/jellyfin#3128]
Recently used jellyfin on a "smart tv" and there was no way to make the video full screen. I guess it is because double clicking was not supported by the remote controller and there was no full screen button anywhere on the page.

What is the reasoning to not have a fullscreen button in the bottom right corner as most other media players?

My proposed solution is to at least show it on devices where user input might be limited.

**Comment by dkanada** [comment]
There should already be a fullscreen button so this might be a bug.

**Comment by pkoryzna** [comment]
I can confirm the fullscreen button is missing on my LG CX OLED TV when using the web UI.

**Comment by Bond-009** [comment]
@pkoryzna Please open a new issue at https://github.com/jellyfin/jellyfin-web
