### ISSUE TITLE
No Support for AV1

### ISSUE THREAD

**Issue by Artiume** [jellyfin/jellyfin#3129]
AV1 is most likely told in the browser that it isn't supported. Causing the format to be transcoded. That said, ffmpeg also doesnt have any support yet either.

```
Stream mapping:
  Stream #0:1 -> #0:0 (? (?) -> h264 (libx264))
  Stream #0:0 -> #0:1 (aac (native) -> aac (native))
Decoder (codec av1) not found for input stream #0:1
```

other note:
why did it convert my audio??? damn poetry

**Comment by cromefire** [comment]
Ref: jellyfin/jellyfin-ffmpeg#39

**Comment by cromefire** [comment]
Ref: jellyfin/jellyfin-web#1241
