### ISSUE TITLE
Memory leak on playback of specific files

### ISSUE THREAD

**Issue by Shalarice** [jellyfin/jellyfin#3131]
Hello guys,

I have redeployed my Jellyfin this week-end hoping to resolve a few problems. Given that I am starting from scratch I spent some time trying to isolate some problems that I encountered.

**Environment:** 
Server
Docker running the latest image: from linuxserver/jellyfin.
running on a Ubuntu server for which I have allocated 2x2 cpus and 8 gbs of RAM.

Client
Chrome on a local network client (tested on 4 different machines)

**Issue:**

Playback of certain files (could only find one at the moment) causes memory that ultimately will crash the browser.

![image](https://user-images.githubusercontent.com/27188920/82123862-a8f1ca80-9769-11ea-83d6-92979ae9ee46.png)

Here are the information regarding the file itself:

![image](https://user-images.githubusercontent.com/27188920/82124150-24a04700-976b-11ea-8fbb-0c9c6e1bc2d3.png)

I was able to have the file playing without any issues in edge as well as firefox. 

edit incorrect file details were attached.

**Comment by Shalarice** [comment]
Static=true&mediaSourceId=6f28e866701df6c10cc22296407fc496&deviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzgwLjAuMzk4Ny4xMjIgU2FmYXJpLzUzNy4zNnwxNTgzMDk4NDY0NDMz&Tag=45d3b85b0c41bf562f9e27d6771b12ee"
[2020-05-16 11:54:56.282 -04:00] [ERR] [58] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "The operation was canceled". URL: "http://apps:9005/Videos/6f28e866701df6c10cc22296407fc496/stream.mov?

**Comment by ferferga** [comment]
I think this is fixed in #2168
