### ISSUE TITLE
TV Series / Anime : Jellyfin doesn't fetch covers and infos despite being able to identify it correctly

### ISSUE THREAD

**Issue by tuxrinku** [jellyfin/jellyfin#3141]
**Describe the bug**
Some Anime series are not fetched at all. When I click on "Identify" and search for it, jellyfin finds the correct cover but doesn't apply the changes.

**System (please complete the following information):**
 - OS: LibreELEC
 - Virtualization: Docker
 - Clients: All
 - Browser: Firefox 76
 - Jellyfin Version: 10.5.5
 - Playback: /
 - Installed Plugins: none
 - Reverse Proxy: nginx
 - Base URL: none
 - Networking: Host
 - Storage: local

**To Reproduce**

1. Select a non-fetched Anime/TV Series
2. Click on 'Identify'
3. Search for the Serie
4. Select the correct one and click OK
5. It goes back to the list and nothing happens

**Expected behavior**
It would change the information with the correct data.

**Screenshots**
Here I try to get the informations for Bakuman:
![Capture du 2020-05-19 17-42-24](https://user-images.githubusercontent.com/53600460/82347794-5b3ec180-99f8-11ea-96a3-bd198adafff6.png)
![Capture du 2020-05-19 17-43-30](https://user-images.githubusercontent.com/53600460/82347828-65f95680-99f8-11ea-8316-6e2ee6a9354d.png)
![Capture du 2020-05-19 17-43-58](https://user-images.githubusercontent.com/53600460/82347859-6f82be80-99f8-11ea-94a1-7abe4654779f.png)
It finds the correct cover and data on the "Identify" menu, but when clicking OK, it goes back to the show list and nothing happens

**Comment by pythonInRelay** [comment]
Install the Anime plugin bro. Also Jellyfin works better if you show downloaded data in Japanese for Anime, though everything will be in Japanese and that may be annoying if you cannot read it.

Installing the plugin should fix your problems in English though.

**Comment by tuxrinku** [comment]
Alright, after some tweaking with the Anime plugin, it worked out. Thanks
