### ISSUE TITLE
Next up broken from the start

### ISSUE THREAD

**Issue by PartTheSeas** [jellyfin/jellyfin#3145]
Hey guys.

I'm a new Jellyfin user, coming from Emby.

The next up tab, so TV shows that are next up to watch, is broken for me on the initial setup of the server. It shows random episodes in next up, all with "S01E01". Apprently it shouldn't, as I didn't watch a minute worth of episodes, but it's having entries of almost all shows showing in the next up hub.

**System (please complete the following information):**
 - OS: [Windows 10]
 - Clients: [Chrome]
 - Browser: [New microsoft Edge browser]
 - Jellyfin Version: [Stable, 10.5.5]
 - Installed Plugins: [Defaul, AudioDb and Musicbrainz]
 - Reverse Proxy: [none]
 - Base URL: [none]
 - Networking: [Not sure]
 - Storage: [local]

**To Reproduce**
Not sure how to reproduce this. Maybe it's related to the "Show missing episodes within TV shows"-feature

**Expected behavior**
Show only upcoming/next episodes of actually watched TV shows

**Screenshots**

![bug 1](https://user-images.githubusercontent.com/38896845/82432106-dbfccc80-9a8f-11ea-9d27-6d93f6346c11.PNG)
![bug 2](https://user-images.githubusercontent.com/38896845/82432110-dd2df980-9a8f-11ea-96ac-8138b8f63d29.PNG)
![bug 3](https://user-images.githubusercontent.com/38896845/82432113-ddc69000-9a8f-11ea-87d5-12f438248632.PNG)

**Additional context**
I've had this issue with emby way earlier, but I'm not sure how to resolve it. I already tried switching off the "Show missing episodes within series" feature on both the server side and my Jellyfin user settings, but to no avail

**Comment by PartTheSeas** [comment]
Is there any other way than reinstalling the entire server? Sorry, I don't mean to appear impatient, I just wanna get everything sorted quickly, so I can get my friends on the server again. I love Jellyfin already! It's like a mature and improved emby :D Very good job guys!

**Comment by PartTheSeas** [comment]
And another thing which might be correlated is, that there are only 2 entries for "Latest TV Shows", but I have over 400 shows added to the TV show library

![bug 4](https://user-images.githubusercontent.com/38896845/82448116-98af5780-9aa9-11ea-9eec-ba716796c81e.PNG)

**Comment by Artiume** [comment]
It's a known issue. There's something wrong with the initialization of the libraries. If you toggle the first episode as watched then unwatched, it _should_ clear it. As for Latest TV Shows, i've noticed it usually with larger shows that have been recently added. It feels like there's a limited number of new episodes it shows and a large show 'fills' it with all of its episodes. This has been known for a while, but without means to effectively reproduce the root cause, we can't fix it.
