### ISSUE TITLE
IPTV won't play with VAAPI hardware transcoding

### ISSUE THREAD

**Issue by Nazar78** [jellyfin/jellyfin#3146]
Hi all,

VAAPI works well with local media but it seems there's issues playing any URL stream from the IPTV plugin while hardware transcoding is set to VAAPI. The URL stream would only play if the hardware transcoding is set to off but playing local media without hardware transcoding would suffer badly unless going back to the settings to toggle VAAPI off or on which is not accessible for non admins. Probably best to implement sort of fallback if the hardware transcoding failed?

I've tested with both ffmpeg (4.1.4-1\~deb10u1) from Debian 10 and jellyfin-ffmpeg (4.2.1) from 10.5.5 both failed to play on the GUI. However this copied from a working local media hardware transcoding profile (basically I just switch the input) ran on the command line it works, so think it's a bug?

`/usr/bin/ffmpeg -hwaccel vaapi -hwaccel_output_format vaapi -vaapi_device /dev/renderD128 -i https://d2e1asnsl7br7b.cloudfront.net/7782e205e72f43aeb4a48ec97f66ebbe/index_5.m3u8 -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_vaapi -b:v 712483 -maxrate 712483 -bufsize 1424966 -profile:v high -level 41 -force_key_frames:0 "expr:gte(t,0+n_forced*3)" -g 72 -keyint_min 72 -sc_threshold 0 -start_at_zero -vsync -1 -codec:a:0 libmp3lame -ac 2 -ab 287518 -copyts -avoid_negative_ts disabled -f hls -max_delay 5000000 -hls_time 3 -individual_header_trailer 0 -hls_segment_type mpegts -start_number 0 -hls_segment_filename /root/.local/share/jellyfin/transcodes/31454dc2debc21c1be1c23d79b01d845%d.ts -hls_playlist_type vod -hls_list_size 0 -y /root/.local/share/jellyfin/transcodes/31454dc2debc21c1be1c23d79b01d845.m3u8`

> ffmpeg version 4.1.4-1\~deb10u1 Copyright (c) 2000-2019 the FFmpeg developers
>   built with gcc 8 (Debian 8.3.0-6)
>   configuration: --prefix=/usr --extra-version='1~deb10u1' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
>   libavutil      56. 22.100 / 56. 22.100
>   libavcodec     58. 35.100 / 58. 35.100
>   libavformat    58. 20.100 / 58. 20.100
>   libavdevice    58.  5.100 / 58.  5.100
>   libavfilter     7. 40.101 /  7. 40.101
>   libavresample   4.  0.  0 /  4.  0.  0
>   libswscale      5.  3.100 /  5.  3.100
>   libswresample   3.  3.100 /  3.  3.100
>   libpostproc    55.  3.100 / 55.  3.100
> [hls,applehttp @ 0x555a79fdef00] Opening 'https://d2e1asnsl7br7b.cloudfront.net/7782e205e72f43aeb4a48ec97f66ebbe/index_5_13364047.ts?m=1587787541' for reading
> [hls,applehttp @ 0x555a79fdef00] Opening 'https://d2e1asnsl7br7b.cloudfront.net/7782e205e72f43aeb4a48ec97f66ebbe/index_5_13364048.ts?m=1587787541' for reading
> Input #0, hls,applehttp, from 'https://d2e1asnsl7br7b.cloudfront.net/7782e205e72f43aeb4a48ec97f66ebbe/index_5.m3u8':
>   Duration: N/A, start: 7681.912889, bitrate: N/A
>   Program 0
>     Metadata:
>       variant_bitrate : 0
>     Stream #0:0: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
>     Metadata:
>       variant_bitrate : 0
>     Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
>     Metadata:
>       variant_bitrate : 0
> Stream mapping:
>   Stream #0:0 -> #0:0 (h264 (native) -> h264 (h264_vaapi))
>   Stream #0:1 -> #0:1 (aac (native) -> mp3 (libmp3lame))
> Press [q] to stop, [?] for help
> [hls @ 0x555a7a5d4f80] Opening '/root/.local/share/jellyfin/transcodes/31454dc2debc21c1be1c23d79b01d8450.ts' for writing
> Output #0, hls, to '/root/.local/share/jellyfin/transcodes/31454dc2debc21c1be1c23d79b01d845.m3u8':
>   Metadata:
>     encoder         : Lavf58.20.100
>     Stream #0:0: Video: h264 (h264_vaapi) (High), vaapi_vld(progressive), 1920x1080 [SAR 1:1 DAR 16:9], q=-1--1, 712 kb/s, 25 fps, 90k tbn, 25 tbc
>     Metadata:
>       encoder         : Lavc58.35.100 h264_vaapi
>     Stream #0:1: Audio: mp3 (libmp3lame), 48000 Hz, stereo, fltp, 287 kb/s
>     Metadata:
>       encoder         : Lavc58.35.100 libmp3lame
> [hls @ 0x555a7a5d4f80] Opening '/root/.local/share/jellyfin/transcodes/31454dc2debc21c1be1c23d79b01d8451.ts' for writing
> [https @ 0x555a7a2b6340] Opening 'https://d2e1asnsl7br7b.cloudfront.net/7782e205e72f43aeb4a48ec97f66ebbe/index_5_13364049.ts?m=1587787541' for reading
> [hls @ 0x555a7a5d4f80] Opening '/root/.local/share/jellyfin/transcodes/31454dc2debc21c1be1c23d79b01d8452.ts' for writing
> [https @ 0x555a7a2d9480] Opening 'https://d2e1asnsl7br7b.cloudfront.net/7782e205e72f43aeb4a48ec97f66ebbe/index_5_13364050.ts?m=1587787541' for reading
> [hls @ 0x555a7a5d4f80] Opening '/root/.local/share/jellyfin/transcodes/31454dc2debc21c1be1c23d79b01d8453.ts' for writing

**Media Info of the file**
IPTV plugin with any URL e.g.: https://d2e1asnsl7br7b.cloudfront.net/7782e205e72f43aeb4a48ec97f66ebbe/index_5.m3u8

**Logs**

> [2020-05-20 23:07:57.409 +08:00] [ERR] [35] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://192.168.1.6:8096/videos/22d2250e-ee98-d108-38dc-769e49969762/live.m3u8?DeviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzgwLjAuMzk4Ny4xNDkgU2FmYXJpLzUzNy4zNnwxNTg1MTM1NTMyMzU0&MediaSourceId=549a455846e6ceffc5242d448077ca70&VideoCodec=h264&AudioCodec=mp3,aac&VideoBitrate=808001&AudioBitrate=192000&PlaySessionId=3faa6d529f044fc58298448f14b08a66&TranscodingMaxAudioChannels=2&RequireAvc=false&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline,high10&h264-level=51&TranscodeReasons=ContainerNotSupported&allowVideoStreamCopy=false"
> System.InvalidOperationException: Nullable object must have a value.
>    at System.Nullable`1.get_Value()
>    at MediaBrowser.Controller.MediaEncoding.EncodingHelper.GetScalingFilters(EncodingJobInfo state, Nullable`1 videoWidth, Nullable`1 videoHeight, Nullable`1 threedFormat, String videoDecoder, String videoEncoder, Nullable`1 requestedWidth, Nullable`1 requestedHeight, Nullable`1 requestedMaxWidth, Nullable`1 requestedMaxHeight)
>    at MediaBrowser.Controller.MediaEncoding.EncodingHelper.GetOutputSizeParam(EncodingJobInfo state, EncodingOptions options, String outputVideoCodec)
>    at MediaBrowser.Api.Playback.Hls.VideoHlsService.GetVideoArguments(StreamState state, EncodingOptions encodingOptions)
>    at MediaBrowser.Api.Playback.Hls.BaseHlsService.GetCommandLineArguments(String outputPath, EncodingOptions encodingOptions, StreamState state, Boolean isEncoding)
>    at MediaBrowser.Api.Playback.BaseStreamingService.StartFfMpeg(StreamState state, String outputPath, CancellationTokenSource cancellationTokenSource, String workingDirectory)
>    at MediaBrowser.Api.Playback.Hls.BaseHlsService.ProcessRequestAsync(StreamRequest request, Boolean isLive)
>    at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
>    at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
>    at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)

**FFmpeg Logs**
No logs produced.

**Stats for Nerds Screenshots**
NA. Just a pop-up: Playback Error - There was an issue with the client profiling and the server isn't sending a compatible media format.

**Server System (please complete the following information):**
 - OS: Debian 10 (Buster).
 - Jellyfin Version: 10.5.5-1.
 - Hardware settings & device: Asustor Nimbustor 4.
 - Reverse proxy: NA.
 - Other hardware notes: NA.

**Edited**: Missed out the client info. Basically the issue happened on any client platform I've tested, Chrome browser, Android and Tizen 5.0.

**Comment by Artiume** [comment]
the ffmpeg command you posted, was it the m3u8 or the local file? what was the difference in the commands? And everything works except when using VAAPI + LiveTV?

**Comment by Nazar78** [comment]
> the ffmpeg command you posted, was it the m3u8 or the local file? what was the difference in the commands? And everything works except when using VAAPI + LiveTV?

The fflpeg command I posted the input was m3u8 from this link https://d2e1asnsl7br7b.cloudfront.net/7782e205e72f43aeb4a48ec97f66ebbe/index_5.m3u8.

The difference is only the input. ***There was no ffmpeg log produced during the error. I think it didn't even reach to that point where ffmpeg supposed to be called***. So out of curiosity I copied the ffmpeg command from an existing log for a local file with VAAPI then ran it with the input -i replaced with the m3u8 URL and it transcoded successfully. I also checked the output the audio/video is ok.

Yes everything works (local file + VAAPI) except when using VAAPI + LiveTV (via the IPTV plugin).

**Comment by Artiume** [comment]
are you able to watch that link via VLC or the native Live TV? I tried accessing it but it doesnt want to work for me. Inside the m3u8 file is

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:4
#EXT-X-MEDIA-SEQUENCE:13381607
#EXTINF:4.000,
index_5_13381607.ts?m=1587787541
#EXTINF:4.000,
index_5_13381608.ts?m=1587787541
#EXTINF:4.000,
index_5_13381609.ts?m=1587787541
#EXTINF:4.000,
index_5_13381610.ts?m=1587787541
#EXTINF:4.000,
index_5_13381611.ts?m=1587787541
#EXTINF:4.000,
index_5_13381612.ts?m=1587787541
#EXTINF:4.000,
index_5_13381613.ts?m=1587787541
#EXTINF:4.000,
index_5_13381614.ts?m=1587787541
#EXTINF:4.000,
index_5_13381615.ts?m=1587787541
#EXTINF:4.000,
index_5_13381616.ts?m=1587787541
```
afaik, they need to link to actual URLs and not relative URLs. I might be wrong though

**Comment by Nazar78** [comment]
> are you able to watch that link via VLC or the native Live TV? I tried accessing it but it doesnt want to work for me. Inside the m3u8 file is

@Artiume thank you for looking into this issue. Yes it's working with VLC 3.0.10 Win10, please refer to the screenshot:
![image](https://user-images.githubusercontent.com/2883688/82559852-e491f780-9ba2-11ea-949b-9629afca1219.png)

I believe relative URLs should work fine as absolute URLs too. I tested loading the absolute URL in VLC it works but not with JF IPTV whilst using VAAPI unless VAAPI is off: https://d2e1asnsl7br7b.cloudfront.net/7782e205e72f43aeb4a48ec97f66ebbe/index_5_13381607.ts?m=1587787541

I also modified the index_5.m3u8 file to add the absolute URL into it then serve it from nginx load into JF IPTV plugin, same thing it failed using VAAPI. Again if VAAPI is off, it works, it's also working from VLC:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:4
#EXT-X-MEDIA-SEQUENCE:13382032
#EXTINF:4.000,
https://d2e1asnsl7br7b.cloudfront.net/7782e205e72f43aeb4a48ec97f66ebbe/index_5_13382032.ts?m=1587787541
#EXTINF:4.000,
https://d2e1asnsl7br7b.cloudfront.net/7782e205e72f43aeb4a48ec97f66ebbe/index_5_13382033.ts?m=1587787541
#EXTINF:4.000,
https://d2e1asnsl7br7b.cloudfront.net/7782e205e72f43aeb4a48ec97f66ebbe/index_5_13382034.ts?m=1587787541
#EXTINF:4.000,
https://d2e1asnsl7br7b.cloudfront.net/7782e205e72f43aeb4a48ec97f66ebbe/index_5_13382035.ts?m=1587787541
#EXTINF:4.000,
https://d2e1asnsl7br7b.cloudfront.net/7782e205e72f43aeb4a48ec97f66ebbe/index_5_13382036.ts?m=1587787541
#EXTINF:4.000,
https://d2e1asnsl7br7b.cloudfront.net/7782e205e72f43aeb4a48ec97f66ebbe/index_5_13382037.ts?m=1587787541
#EXTINF:4.000,
https://d2e1asnsl7br7b.cloudfront.net/7782e205e72f43aeb4a48ec97f66ebbe/index_5_13382038.ts?m=1587787541
#EXTINF:4.000,
https://d2e1asnsl7br7b.cloudfront.net/7782e205e72f43aeb4a48ec97f66ebbe/index_5_13382039.ts?m=1587787541
#EXTINF:4.000,
https://d2e1asnsl7br7b.cloudfront.net/7782e205e72f43aeb4a48ec97f66ebbe/index_5_13382040.ts?m=1587787541
#EXTINF:4.000,
https://d2e1asnsl7br7b.cloudfront.net/7782e205e72f43aeb4a48ec97f66ebbe/index_5_13382041.ts?m=1587787541
```
You can test any of these list from here https://github.com/iptv-org/iptv it works in VLC but not JF whilst VAAP is turned on.
