### ISSUE TITLE
Yadif deinterlace too slow on Raspberry Pi

### ISSUE THREAD

**Issue by K5HV** [jellyfin/jellyfin#3156]
**Describe the bug**
Jellyfin uses yadif to deinterlace video.
This metod is too slow on some machines when 1080i videos is playing.

**System (please complete the following information):**
 - OS: Raspbian / Debian
 - Virtualization: none
 - Clients: Browser, Android
 - Browser: Chrome 84, PS4
 - Jellyfin Version: 10.5.5
 - Playback: Transcode
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: none
 - Networking: Host
 - Storage: local

**To Reproduce**
1. Play 1080i video
2. Video will shutter (RPi4 produces around 20 FPS for 25 FPS video)

**Expected behavior**
Jellyfin should allow to use different (faster) deinterlacing method (or allow to disable it when using HW transcoding).

**Logs**
N/A

**Screenshots**
N/A

**Additional context**
I've written small bash wrapper around ffmpeg to disable yadif when ffmpeg is executed. Video works fine on all tested platforms.
h264_omx produces progressive video anyway. Using yadif seems to be unnecessary.

**Comment by Artiume** [comment]
Fixed in nightly ;) 

![Screenshot_20200522-192125_Chrome](https://user-images.githubusercontent.com/20715731/82715521-7bbd8480-9c61-11ea-8c47-74ee0db01d7a.jpg)
