### ISSUE TITLE
Can't control playback via voice on Chromecast to Google Mini/Nest device.

### ISSUE THREAD

**Issue by bengalih** [jellyfin/jellyfin#3157]
**Describe the bug**
When casting to a Google Mini/Nest the casting app appears to have no integration with the OS on the hardware.  The Mini/Nest is totally unaware that media is playing and does not respond to voice controls to pause, stop, or identify the media.

I believe Plex suffers from the last issue as well - namely it cannot tell you what specific media file has been cast.  It can however control the playback of the media.

Due to this it is impossible to stop playback in some cases.  Sometimes you can have Google do something else ("Ok Google, Play music from Spotify") and this will override the playing media cast from JF.  You can then terminate the Spotify stream.  If you are still connected with the original session with JF you can sometimes control it from the app.  This of course is cumbersome and totally against the point of having a voice controlled device.  Half of the time, we are forced to actually unplug the mini in order to prevent the stream from continuing playback.

Setting volume to 0 of course helps, but you can't resume/rewind/etc missed media.  Also, if you are wanting to do something else before the media ends, your entire session is hijacked by the JF cast stream.

**System (please complete the following information):**
 - OS: Windows
 - Virtualization: none
 - Clients: Google Mini/Nest (Android/Windows casting)
 - Browser: Chrome
 - Jellyfin Version:  10.5.5
 - Playback: n/a
 - Installed Plugins: none
 - Reverse Proxy: nginx
 - Base URL: none
 - Networking: direct
 - Storage: local

**To Reproduce**

1. Cast to device
2. Try to pause/stop via voice commands

P.S.  I apologize if this is a duplicate.  I seem to recall bringing this up in another issue perhaps, but I believe it deserves its own and I couldn't find reference while searching.

**Comment by neopc10** [comment]
This works on 10.6 on the unstable player now or will by the time you read this. Skip/previous track, not yet, but play/pause works.

**Comment by bengalih** [comment]
> This works on 10.6 on the unstable player now or will by the time you read this. Skip/previous track, not yet, but play/pause/rw/ff works.

Would love to test, but:
https://github.com/jellyfin/jellyfin/issues/3712
