### ISSUE TITLE
Bug search letter Q

### ISSUE THREAD

**Issue by petitbou0169** [jellyfin/jellyfin#3159]
**Describe the bug**

Good morning, sir,

I have a problem with the letter Q not being able to display the movies. The circle turns but it doesn't display anything, except on the other letters I have no problem. 

**System (please complete the following information):**
 - OS: UBUNTU 18.04
 - Clients: Browser and android TV
 - Browser: Firefox / chrome / IE
 - Jellyfin Version: 10.5.5
 - Playback: 
 - Installed Plugins: none
 - Reverse Proxy: apache
 - Base URL: /
 - Networking: Bridge
 - Storage: local

**To Reproduce**

2. Click on 'letter Q'
3. Scroll down to ''

**Expected behavior**

**Logs**

> [2020-05-23 10:36:42.043 +00:00] [INF] Jellyfin version: "10.5.5"
> [2020-05-23 10:36:42.054 +00:00] [INF] Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--restartpath=/usr/lib/jellyfin/restart.sh", "--ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg", ""]
> [2020-05-23 10:36:42.056 +00:00] [INF] Operating system: "Linux"
> [2020-05-23 10:36:42.056 +00:00] [INF] Architecture: X64
> [2020-05-23 10:36:42.057 +00:00] [INF] 64-Bit Process: True
> [2020-05-23 10:36:42.057 +00:00] [INF] User Interactive: True
> [2020-05-23 10:36:42.057 +00:00] [INF] Processor count: 12
> [2020-05-23 10:36:42.057 +00:00] [INF] Program data path: "/var/lib/jellyfin"
> [2020-05-23 10:36:42.057 +00:00] [INF] Web resources path: "/usr/lib/jellyfin/bin/jellyfin-web"
> [2020-05-23 10:36:42.057 +00:00] [INF] Application directory: "/usr/lib/jellyfin/bin/"
> [2020-05-23 10:36:42.144 +00:00] [INF] Setting cache path: "/var/cache/jellyfin"
> [2020-05-23 10:36:42.158 +00:00] [INF] Loading assemblies
> [2020-05-23 10:36:44.852 +00:00] [INF] Kestrel listening on all interfaces
> [2020-05-23 10:36:44.918 +00:00] [INF] Running startup tasks
> [2020-05-23 10:36:44.944 +00:00] [INF] Daily trigger for "Extract Chapter Images" set to fire at 05/24/2020 02:00, which is 15:23:15.0557526 from now.
> [2020-05-23 10:36:44.970 +00:00] [INF] Found ffmpeg version "4.2.1"
> [2020-05-23 10:36:45.009 +00:00] [INF] Available "decoders": ["h264", "h264_cuvid", "hevc", "hevc_cuvid", "mpeg2video", "aac", "ac3", "mp3"]
> [2020-05-23 10:36:45.016 +00:00] [INF] Available "encoders": ["libx264", "h264_amf", "h264_nvenc", "h264_v4l2m2m", "h264_vaapi", "libx265", "hevc_amf", "hevc_nvenc", "hevc_vaapi", "mpeg4", "msmpeg4", "aac", "ac3", "libmp3lame", "libopus", "libvorbis", "srt"]
> [2020-05-23 10:36:45.017 +00:00] [INF] FFmpeg: SetByArgument: "/usr/lib/jellyfin-ffmpeg/ffmpeg"
> [2020-05-23 10:36:45.017 +00:00] [INF] ServerId: "832cccf206a54c518ad78f817a62a4b2"
> [2020-05-23 10:36:45.079 +00:00] [INF] Executed all pre-startup entry points in 0:00:00.0572652
> [2020-05-23 10:36:45.080 +00:00] [INF] Core startup complete
> [2020-05-23 10:36:45.082 +00:00] [INF] Loading live tv data from "/var/lib/jellyfin/data/livetv/timers.json"
> [2020-05-23 10:36:45.222 +00:00] [INF] Executed all post-startup entry points in 0:00:00.1420593
> [2020-05-23 10:36:45.222 +00:00] [INF] Startup complete 0:00:03.2912265
> [2020-05-23 10:36:47.951 +00:00] [INF] "StartupTrigger" fired for task: "Update Plugins"
> [2020-05-23 10:36:47.955 +00:00] [INF] Queueing task "PluginUpdateTask"
> [2020-05-23 10:36:47.964 +00:00] [INF] Executing "Update Plugins"
> [2020-05-23 10:36:47.995 +00:00] [INF] "Update Plugins" Completed after 0 minute(s) and 0 seconds
> [2020-05-23 10:36:48.027 +00:00] [INF] ExecuteQueuedTasks
> [2020-05-23 10:36:52.988 +00:00] [INF] Watching directory /home/Seriestv
> [2020-05-23 10:36:55.004 +00:00] [INF] Watching directory /home/Films
> [2020-05-23 10:37:04.784 +00:00] [ERR] Error encoding image
> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Skia unable to read image /home/Seriestv/One Tree Hill/fanart.jpg')
>    at Jellyfin.Drawing.Skia.SkiaEncoder.EncodeImage(String inputPath, DateTime dateModified, String outputPath, Boolean autoOrient, Nullable`1 orientation, Int32 quality, ImageProcessingOptions options, ImageFormat selectedOutputFormat)
>    at Emby.Drawing.ImageProcessor.ProcessImage(ImageProcessingOptions options)
> [2020-05-23 10:37:07.148 +00:00] [ERR] Error encoding image
> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Skia unable to read image /home/Seriestv/One Tree Hill/fanart.jpg')
>    at Jellyfin.Drawing.Skia.SkiaEncoder.EncodeImage(String inputPath, DateTime dateModified, String outputPath, Boolean autoOrient, Nullable`1 orientation, Int32 quality, ImageProcessingOptions options, ImageFormat selectedOutputFormat)
>    at Emby.Drawing.ImageProcessor.ProcessImage(ImageProcessingOptions options)
> [2020-05-23 10:37:07.190 +00:00] [ERR] Error encoding image
> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Skia unable to read image /home/Seriestv/One Tree Hill/fanart.jpg')
>    at Jellyfin.Drawing.Skia.SkiaEncoder.EncodeImage(String inputPath, DateTime dateModified, String outputPath, Boolean autoOrient, Nullable`1 orientation, Int32 quality, ImageProcessingOptions options, ImageFormat selectedOutputFormat)
>    at Emby.Drawing.ImageProcessor.ProcessImage(ImageProcessingOptions options)
> [2020-05-23 10:37:13.978 +00:00] [ERR] Error encoding image
> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Skia unable to read image /home/Seriestv/One Tree Hill/fanart.jpg')
>    at Jellyfin.Drawing.Skia.SkiaEncoder.EncodeImage(String inputPath, DateTime dateModified, String outputPath, Boolean autoOrient, Nullable`1 orientation, Int32 quality, ImageProcessingOptions options, ImageFormat selectedOutputFormat)
>    at Emby.Drawing.ImageProcessor.ProcessImage(ImageProcessingOptions options)
> [2020-05-23 10:37:14.021 +00:00] [ERR] Error encoding image
> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Skia unable to read image /home/Seriestv/One Tree Hill/fanart.jpg')
>    at Jellyfin.Drawing.Skia.SkiaEncoder.EncodeImage(String inputPath, DateTime dateModified, String outputPath, Boolean autoOrient, Nullable`1 orientation, Int32 quality, ImageProcessingOptions options, ImageFormat selectedOutputFormat)
>    at Emby.Drawing.ImageProcessor.ProcessImage(ImageProcessingOptions options)
> [2020-05-23 10:37:21.511 +00:00] [ERR] Error encoding image
> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Skia unable to read image /home/Seriestv/One Tree Hill/fanart.jpg')
>    at Jellyfin.Drawing.Skia.SkiaEncoder.EncodeImage(String inputPath, DateTime dateModified, String outputPath, Boolean autoOrient, Nullable`1 orientation, Int32 quality, ImageProcessingOptions options, ImageFormat selectedOutputFormat)
>    at Emby.Drawing.ImageProcessor.ProcessImage(ImageProcessingOptions options)
> [2020-05-23 10:39:44.110 +00:00] [WRN] HTTP Response 200 to "127.0.0.1". Time (slow): 0:00:00.5252869. "http://*****/Items/79bc6e8179e1661ff16e38570d4734e5/Images/Backdrop/0?tag=ca281680457e1f8dc7afb0dd0ec8c36a&maxWidth=2880&quality=70"
> [2020-05-23 10:40:41.570 +00:00] [ERR] Error encoding image
> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Skia unable to read image /home/Seriestv/The Shield/poster.jpg')
>    at Jellyfin.Drawing.Skia.SkiaEncoder.EncodeImage(String inputPath, DateTime dateModified, String outputPath, Boolean autoOrient, Nullable`1 orientation, Int32 quality, ImageProcessingOptions options, ImageFormat selectedOutputFormat)
>    at Emby.Drawing.ImageProcessor.ProcessImage(ImageProcessingOptions options)
> [2020-05-23 10:40:48.105 +00:00] [ERR] Error encoding image
> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Skia unable to read image /home/Seriestv/The Shield/poster.jpg')
>    at Jellyfin.Drawing.Skia.SkiaEncoder.EncodeImage(String inputPath, DateTime dateModified, String outputPath, Boolean autoOrient, Nullable`1 orientation, Int32 quality, ImageProcessingOptions options, ImageFormat selectedOutputFormat)
>    at Emby.Drawing.ImageProcessor.ProcessImage(ImageProcessingOptions options)
> [2020-05-23 10:41:28.110 +00:00] [ERR] Could not find handler for "/web/index.html"
> [2020-05-23 10:41:28.115 +00:00] [ERR] Error processing request: "Unable to find the specified file". URL: "http://*****/web/index.html"
> [2020-05-23 10:41:28.770 +00:00] [ERR] Could not find handler for "/web/index.html"
> [2020-05-23 10:41:28.772 +00:00] [ERR] Error processing request: "Unable to find the specified file". URL: "http://****/web/index.html"
> [2020-05-23 10:41:29.388 +00:00] [ERR] Could not find handler for "/web/index.html"
> [2020-05-23 10:41:29.389 +00:00] [ERR] Error processing request: "Unable to find the specified file". URL: "http://******/web/index.html"
> [2020-05-23 10:41:30.005 +00:00] [ERR] Could not find handler for "/web/index.html"
> [2020-05-23 10:41:30.006 +00:00] [ERR] Error processing request: "Unable to find the specified file". URL: "http://******/web/index.html"
> [2020-05-23 10:41:44.141 +00:00] [WRN] HTTP Response 200 to "127.0.0.1". Time (slow): 0:00:00.5414144. "http://******/Items/d9aeb7532a344280d7b3c08dd72e3772/Images/Backdrop/0?tag=2010bddd090f9248fdf71c84b9627295&maxWidth=2880&quality=70"
> 

**Screenshots**

**Additional context**

**Comment by crobibero** [comment]
The only thing I see in the logs is a SKIA error. Can you try removing the file ‘ /home/Seriestv/One Tree Hill/fanart.jpg’?

**Comment by Artiume** [comment]
I was able to search for `Q` and it worked. I wonder what the issue is
