### ISSUE TITLE
Support OPTIONS Requests in new ASP endpoints

### ISSUE THREAD

**Issue by mark-monteiro** [jellyfin/jellyfin#3161]
When the web client sends an OPTIONS request to the new endpoints, the server responds with a 405 (Method Not Allowed). The new ASP pipeline should be updated to handle these requests.

Without this update, any new ASP endpoints cannot be tested from the web client.

**Comment by crobibero** [comment]
Might be a CORS issue?
https://stackoverflow.com/a/31519601/11704592

**Comment by mark-monteiro** [comment]
Ah, that would make sense. Those requests are only sent when running the web client as a  standalone app (i.e. not bundled with the server).

I don't know anything about CORS though, maybe someone else in @jellyfin/backend has an idea of how it needs to be configured.

I was able to find where these requests are handled in the lagacy endpoints though: https://github.com/jellyfin/jellyfin/blob/master/Emby.Server.Implementations/HttpServer/HttpListenerHost.cs#L447. Perhaps we can just copy that implementation over to a middleware on the new API?
