### ISSUE TITLE
Add Authentication Support To Swagger UI

### ISSUE THREAD

**Issue by mark-monteiro** [jellyfin/jellyfin#3162]
Currently authenticated endpoints cannot be tested from SwaggerUI. To steps to add support for this is in the Swashbuckle documentation: https://github.com/domaindrivendev/Swashbuckle.AspNetCore#add-security-definitions-and-requirements

For Jellyfin, this will look something like this in [ApiServiceCollectionExtensions.cs](https://github.com/jellyfin/jellyfin/blob/167e96d212f01cdf56a97e494f89e9321293d766/Jellyfin.Server/Extensions/ApiServiceCollectionExtensions.cs#L91):

```cs
return serviceCollection.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new OpenApiInfo { Title = "Jellyfin API", Version = "v1" });
    c.AddSecurityDefinition(AuthenticationSchemes.CustomAuthentication, new OpenApiSecurityScheme
    {
        Type = SecuritySchemeType.ApiKey,
        In = ParameterLocation.Header,
        Name = "X-Emby-Token",
        Description = "API key header parameter"
    });

    var securitySchemeRef = new OpenApiSecurityScheme
    {
        Reference = new OpenApiReference { Type = ReferenceType.SecurityScheme, Id = AuthenticationSchemes.CustomAuthentication },
    };

    // TODO: Apply this with an operation filter instead of globally
    // https://github.com/domaindrivendev/Swashbuckle.AspNetCore#add-security-definitions-and-requirements
    c.AddSecurityRequirement(new OpenApiSecurityRequirement
    {
        { securitySchemeRef, Array.Empty<string>() }
    });
});
```

**Comment by Ullmie02** [comment]
This should be fixed now. But is there a place somewhere on the site to explain how to obtain the key? One solution I found working was accessing a log and copying the api key from the url of the log file, but I'm sure this is not the best method.

**Comment by dkanada** [comment]
Several endpoints will include the API key, and you can also manually request one from the web client if you want, but none of those are ideal.
