### ISSUE TITLE
New certificate not used without restart

### ISSUE THREAD

**Issue by brianjmurrell** [jellyfin/jellyfin#3166]
**Describe the bug**
If I place a new/updated certificate in the location that Jellyfin has been configured to find it, it is not recognised until I restart Jellyfin.

**System (please complete the following information):**
 - OS: Fedora 31
 - Virtualization: None
 - Clients: N/A
 - Browser: N/A
 - Jellyfin Version: 10.5.4
 - Playback: N/A
 - Installed Plugins: N/A
 - Reverse Proxy: none
 - Base URL: none
 - Networking: native
 - Storage: N/A

**To Reproduce**

1. Configure Jellyfin to serve HTTPs with a certificate
2. Observe certificate info such as issue/expiry date in browser or using `openssl s_client`, etc.
3. Replace certificate with updated certificate
4. Repeat #2 and observe the new certificate is not being used

**Expected behavior**
Should be able to replace certificate with interrupting users by restarting Jellyfin.

After-all, Jellyfin is smart enough to see new media when it shows up, why can it not see a new certificate?

**Logs**
N/A

**Screenshots**
N/A

**Additional context**
N/A

**Comment by mark-monteiro** [comment]
This is not supported by Kestrel, but should be supported once .NET 5 lands later this year. Here is the relevant update announcement from Microsoft: https://github.com/aspnet/Announcements/issues/419

**Comment by brianjmurrell** [comment]
Nice.  Thanks for the update.  Looking forward to when this is a reality for Jellyfin.

**Comment by cvium** [comment]
The announcement that Mark is referencing is only for hotloading config changes in a config that we don't actually use. And even if we did use it, a cert change would not be detected unless you rename it and change the config.

> After-all, Jellyfin is smart enough to see new media when it shows up, why can it not see a new certificate?

It technically can if we use `ServerCertificateSelector` delegate to retrieve the SSL cert, but this is called on every request and creates an overhead. It can mitigated somewhat if we just return AppHost.Certificate, but then some other mechanism will have to update that property when the cert changes, either automatically with inotify or with a button in the admin interface.

Either way, it's not a high priority. I'm also trying to clean out issues and feature requests belong here: https://features.jellyfin.org.

**Comment by brianjmurrell** [comment]
> Either way, it's not a high priority. I'm also trying to clean out issues and feature requests belong here: https://features.jellyfin.org.

Just because it's not a high priority **bug** doesn't mean it's not a bug.  IMHO, it's a bug to put a new certificate in place and it not be used automatically.

To have to restart Jellyfin for the new certificate interrupts all users of JF at the time (does it not?).  In some installations, JF could be getting used 24x7 making a restart to replace the certificate impossible.

**Comment by cvium** [comment]
It's not a bug. And if you insist on calling it a bug, then yell at upstream.

I sincerely hope that anyone with such a volume of users that they cannot afford 2 mins to restart are using a reverse proxy or some kind of container orchestration.

**Comment by brianjmurrell** [comment]
It's really annoying to have to repeat oneself at https://features.jellyfin.org.

**Comment by brianjmurrell** [comment]
https://features.jellyfin.org/posts/1129/automatically-read-new-certificate
