### ISSUE TITLE
Episode release dates off by one day

### ISSUE THREAD

**Issue by Bodertz** [jellyfin/jellyfin#3181]
I don't know if I'm missing something obvious, but each episode's release date as displayed on the episode page does not match the release date as shown in the metadata for the episode.

For example, go the the episode page for Twin Peaks Season 1 Episode 1.

The date, which I interpret to be the release date, is '4/7/1990': [Image](https://i.imgur.com/8Z4E8iu.png)

Click on 'More', then 'Edit metadata'.  Scroll down to the release date.

The date is displayed as '04/08/1990': [Image](https://i.imgur.com/71lAB7t.png)

Can you reproduce this?  Am I misinterpreting something?

**Comment by Artiume** [comment]
I think it's because some dates are referencing UTC and other times, it'll reference Local Time so depending on when you check dates, they might change. There's another issue ticket somewhere that points this out on TV Shows > Upcoming

**Comment by Bodertz** [comment]
Thank you, I hadn't even considered that.

**Comment by Artiume** [comment]
https://github.com/jellyfin/jellyfin-web/issues/369
