### ISSUE TITLE
Jellyfin doesn't exit gracefully with exit code 143

### ISSUE THREAD

**Issue by Mint-M** [jellyfin/jellyfin#3182]
**Describe the bug**
Jellyfin doesn't exit gracefully when it is stopped with systemd.

**System (please complete the following information):**
 - OS: Fedora 32 with kernel 5.6.13-300
 - Virtualization: no
 - Jellyfin Version: 10.5.5

**To Reproduce**

1. Build rpm package from official src rpm. rpmbuild --rebuild jellyfin-10.5.5-1.fc31.src.rpm
2. Install the rpm package and related dependency.
3. Start jelly from systemd and stop it.
4. jellyfin.service exits with code 143 and its status shows failed.

**Expected behavior**

jellyfin.service can exit gracefully.

**Logs**

systemd[1]: Stopping Jellyfin is a free software media system that puts you in control of managing and streaming your media....
jellyfin[826]: [10:28:24] [INF] [2] Main: Received a SIGTERM signal, shutting down
jellyfin[826]: [10:28:24] [INF] [2] App: Disposing CoreAppHost
jellyfin[826]: [10:28:24] [INF] [2] App: Disposing ActivityLogWebSocketListener
jellyfin[826]: [10:28:24] [INF] [2] App: Disposing SessionInfoWebSocketListener
jellyfin[826]: [10:28:24] [INF] [2] App: Disposing ScheduledTasksWebSocketListener
jellyfin[826]: [10:28:24] [INF] [2] App: Disposing SessionWebSocketListener
jellyfin[826]: [10:28:24] [INF] [2] App: Disposing EmbyTV
jellyfin[826]: [10:28:24] [INF] [2] App: Disposing ApiEntryPoint
jellyfin[826]: [10:28:24] [INF] [2] App: Disposing ServerEntryPoint
jellyfin[826]: [10:28:24] [INF] [2] App: Disposing EntryPoint
jellyfin[826]: [10:28:24] [INF] [2] App: Disposing DeviceAccessEntryPoint
jellyfin[826]: [10:28:24] [INF] [2] App: Disposing LibraryMonitorStartup
jellyfin[826]: [10:28:24] [INF] [2] App: Disposing ExternalPortForwarding
jellyfin[826]: [10:28:24] [INF] [2] App: Disposing LibraryChangedNotifier
jellyfin[826]: [10:28:24] [INF] [2] App: Disposing RecordingNotifier
jellyfin[826]: [10:28:24] [INF] [2] App: Disposing ServerEventNotifier
jellyfin[826]: [10:28:24] [INF] [2] App: Disposing StartupWizard
jellyfin[826]: [10:28:24] [INF] [2] App: Disposing UdpServerEntryPoint
jellyfin[826]: [10:28:24] [INF] [2] App: Disposing UserDataChangeNotifier
jellyfin[826]: [10:28:24] [INF] [2] App: Disposing DeviceManagerEntryPoint
jellyfin[826]: [10:28:24] [INF] [2] App: Disposing CollectionManagerEntryPoint
jellyfin[826]: [10:28:24] [INF] [2] App: Disposing ActivityLogEntryPoint
jellyfin[826]: [10:28:24] [INF] [2] App: Disposing DlnaEntryPoint
jellyfin[826]: [10:28:24] [INF] [2] Dlna: Disposing SsdpDevicePublisher
jellyfin[826]: [10:28:24] [INF] [2] Dlna: Disposing PlayToManager
jellyfin[826]: [10:28:24] [INF] [2] Dlna: Disposing DeviceDiscovery
jellyfin[826]: [10:28:24] [INF] [2] Dlna: Disposing SsdpCommunicationsServer
jellyfin[826]: [10:28:24] [INF] [2] Dlna: SsdpCommunicationsServer disposing _BroadcastListenSocket
jellyfin[826]: [10:28:24] [INF] [2] Dlna: SsdpCommunicationsServer Disposing 2 sendSockets
jellyfin[826]: [10:28:24] [INF] [2] Dlna: SsdpCommunicationsServer disposing sendSocket from 0.0.0.0
jellyfin[826]: [10:28:24] [INF] [2] Dlna: SsdpCommunicationsServer disposing sendSocket from 192.168.50.3
jellyfin[826]: [10:28:24] [INF] [2] App: Disposing NotificationEntryPoint
jellyfin[826]: [10:28:24] [INF] [2] App: Disposing EntryPoint
systemd[1]: jellyfin.service: Main process exited, code=exited, status=143/n/a
systemd[1]: jellyfin.service: Failed with result 'exit-code'.
systemd[1]: Stopped Jellyfin is a free software media system that puts you in control of managing and streaming your media..
systemd[1]: jellyfin.service: Consumed 1min 8.641s CPU time.

**Additional context**
I'm not sure whether the application exits with code 0 or 'SuccessExitStatus=143' is added to the systemd unit file is the correct way to fix it.

**Comment by rorlork** [comment]
Same thing happening to me in CentOS 7. I am sidestepping the issue but it would be best that it returned a proper code. It seems like this might be 128+15, where 15 is the value for SIGTERM, but I don't know why that would be returned instead of actually 15.

**Comment by Hetsh** [comment]
Also observing this behaviour on debian (see: [Dockerfile](https://github.com/Hetsh/docker-jellyfin/blob/master/Dockerfile))

**Comment by amo13** [comment]
Still the same with the 10.7.0 release.

**Comment by amo13** [comment]
Still the same with the 10.7.6 release.

**Comment by zeus86** [comment]
This is quite annoying, because i added an override to the jellyfin-unit to mount a ramdisk for cache and transcode, but the systemd-unit always entered `failed` instead of `exited` state when stopping the unit, thus systemd is not fully recognizing that the unit has been stopped gracefully.

**Comment by jackun** [comment]
Pretty sure it is just exiting with SIGTERM so
```
[Service]
SuccessExitStatus=143
```
