### ISSUE TITLE
Unreasonable systemd unit dependency setting

### ISSUE THREAD

**Issue by Mint-M** [jellyfin/jellyfin#3183]
**Describe the bug**
After=network.target is a wrong setting for applications which requires network.

**System (please complete the following information):**
system independent bug

**To Reproduce**
The unreasonable setting might be harmless although it should be fixed.

**Additional context**
According to the document of systemd, network-online.target means that the network is configured and applications which need network is ready to be started.
https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/

Many other applications including nginx have fixed this bug recently. This problem actually exists in tons of applications if taking a look at RH bugzillia.
https://github.com/nginxinc/nginx-wiki/pull/507
https://github.com/openresty/openresty/issues/590
https://bugzilla.redhat.com/show_bug.cgi?id=1119787

Please evaluate if other dependency is needed for jellyfin.
syslog.target network-online.target remote-fs.target nss-lookup.target

**Comment by Mint-M** [comment]
not fixed yet

**Comment by joshuaboniface** [comment]
All reasonable suggestions. `network-online.target` is definitely better, and `remote-fs.target` would be good too. A PR would be welcome; if not, I'll fix this up soon.
