### ISSUE TITLE
Creating new user with illegal character outputs Error Proccessing Request 

### ISSUE THREAD

**Issue by Zusier** [jellyfin/jellyfin#3189]
This is a mix of a bug and feature request so I'm sorry if this is the wrong place. So the 'bug' occurs when you have illegal characters such as a space, when you go to save changes, it outputs "There was an error processing the request. Please try again later."

For slightly newer users that might not know to check the server log, so instead of this it could display something like: Usernames can only contain unicode symbols, dashes, numbers etc (the message obviously shouldn't list etc, im just trying to give an example 

To Reproduce: Make a new user, put a space somewhere in it. Receive the error and check server log/terminal

**Comment by Artiume** [comment]
the question is, should we allow spaces in usernames? it could create subtle bugs everywhere

**Comment by Zusier** [comment]
Thats not the problem, I think people can live with UserExample instead of User Example if it would cause bugs, but the error outputted when having a space in the username isn't very specific.

**Comment by Artiume** [comment]
Yeah, it should be more graceful
