### ISSUE TITLE
Casting broken on nightly (10.6)

### ISSUE THREAD

**Issue by mcarlton00** [jellyfin/jellyfin#3190]
**Describe the bug**

Running nightly built on 2020-05-26, casting to at least some clients is broken.  Mopidy and Kodi both tested, MPV shim very likely also affected.  Other targets (chromecast, etc) unconfirmed right now.

**System (please complete the following information):**
 - OS: Ubuntu
 - Virtualization: Docker
  - Browser: Firefox 76
 - Jellyfin Version: nightly 20200526
 - Reverse Proxy: none
 - Base URL: none

**To Reproduce**

1. Run client capable of being a cast receiver (mopidy, kodi, mpv)
2. Cast to client
3. Varying levels of failure, but it no worky

**Expected behavior**

It works

**Additional context**

Nightly is currently sending more data than 10.5.5 was, with some types that don't match.

10.5.5 data payload:
```
{'ControllingUserId': '3920b99003194448a2a9d4f0bedd3d82',
 'Id': 'ae2436edc6b91b11d72aeaa67f84e0ea',
 'ItemIds': ['cd281c0022009532ed59819095ebf714',
             '822ce1b5fcedbd8050242e3d807f9521',
             '1178cf3ef4a674daafe3893a998e0317'],
 'PlayCommand': 'PlayNow',
 'StartIndex': 0}
```

Nightly data payload:
```
{'AudioStreamIndex': None,
 'ControllingUserId': '82fb57e4-199a-4b2d-bf95-679337ffce86',
 'ItemIds': ['0c2b0ead-f730-885d-1d44-e1d8b368cffc',
             '7327849f-e4a7-a322-4db4-892139e1ce6e',
             'a24e6b4a-ee3f-97fd-f004-c6d9eb02fbe4'],
 'MediaSourceId': None,
 'PlayCommand': 'PlayNow',
 'StartIndex': 0,
 'StartPositionTicks': None,
 'SubtitleStreamIndex': None}
```
Mopidy in particular is expecting `StartPositionTicks` to be an int.  Unsure what's failing on the others yet

**Comment by Bond-009** [comment]
Can you trace the commit that causes this?
Shouldn’t take too long with git bisect

**Comment by mcarlton00** [comment]
I started working backwards but didn't find where it happened, I probably need to go another round and be thorough.

Kodi and MPV are both working with 3315, Mopidy is easy enough to fix client side.  I don't know that we have any third party casting clients that will break with this or if we need to track down the source of where it changed

**Comment by mcarlton00** [comment]
This has been fixed
