### ISSUE TITLE
Long pauses during 4K playback using reverse proxy

### ISSUE THREAD

**Issue by whozur** [jellyfin/jellyfin#3198]
**Media Info of the file**
![media](https://user-images.githubusercontent.com/65986731/83079850-9ca32280-a031-11ea-89e5-c2890107500b.png)

**Logs**
[bad-nginx-serverlog.txt](https://github.com/jellyfin/jellyfin/files/4693564/bad-nginx-serverlog.txt)
[bad-nginx-proxybufferoff.txt](https://github.com/jellyfin/jellyfin/files/4693566/bad-nginx-proxybufferoff.txt)

**FFmpeg Logs**
[bad-ffmpeg-transcode-7c9dacf0-d9d8-4afc-b049-59c32ad9937d.txt](https://github.com/jellyfin/jellyfin/files/4693572/bad-ffmpeg-transcode-7c9dacf0-d9d8-4afc-b049-59c32ad9937d.txt)

**Stats for Nerds Screenshots**
![nerds-bad](https://user-images.githubusercontent.com/65986731/83079852-9d3bb900-a031-11ea-919d-ebc13cd673c1.png)

**Server System:**
 - OS: Windows 10 Pro x64
 - Jellyfin Version: 10.5.5
 - Hardware settings & device: NVENC on GTX1050ti
 - Reverse proxy: nginx
 - Other hardware notes: Media mounted via iSCSI
 
**Client System:**
 - Device: Custom HTPC
 - OS: Windows 10 Pro x64

 - Client: Web
 - Browser (if Web client): Edge (but tried with Chrome and Firefox)
 - Client and Browser Version: Microsoft Edge 44.18362.449.0

**nginx Configuration Files **
[nginx.conf.txt](https://github.com/jellyfin/jellyfin/files/4692220/nginx.conf.txt)
[jellyfin.conf.txt](https://github.com/jellyfin/jellyfin/files/4692219/jellyfin.conf.txt)

I also tried it with Proxy Buffering on and saw the same thing. Here's the log from that:
[bad-nginx-proxybufferon.txt](https://github.com/jellyfin/jellyfin/files/4693573/bad-nginx-proxybufferon.txt)

If I look at the network transfer rates from the server under the two configurations (buffering off and buffering on ) I do see a difference but the playback behavior is the same:
![nginx-withproxybufferingoff-taskman](https://user-images.githubusercontent.com/65986731/83079857-9dd44f80-a031-11ea-995f-3347eaf03d9b.gif)
![nginx-withproxybufferingon-taskman](https://user-images.githubusercontent.com/65986731/83079858-9e6ce600-a031-11ea-9dc2-8db05a4b39b8.gif)

If I expose the http port and connect directly from the internet to Jellyfin it do not have issue. Logs and Stats for Nerds Screenshot from that:
[good-ffmpeg-transcode-6d63bdca-a0c3-4aaa-8817-4d1db970fa23.txt](https://github.com/jellyfin/jellyfin/files/4693575/good-ffmpeg-transcode-6d63bdca-a0c3-4aaa-8817-4d1db970fa23.txt)
[good-serverlog.txt](https://github.com/jellyfin/jellyfin/files/4693576/good-serverlog.txt)
![nerds-good](https://user-images.githubusercontent.com/65986731/83079855-9d3bb900-a031-11ea-822e-99f51e8d3964.png)

**Comment by ferferga** [comment]
I only used Nginx and Apache so I'm going to give my feedback based on Nginx. Just a quick look before I go afk, maybe there is some other things that can be improved:

* Why only one worker?
* Why no push is commented out? This kind of applications benefit from that
* Why no tcp_nodelay property is set in the config file?

**Comment by whozur** [comment]
Updated the nginx.conf based on @ferferga's suggestions but I still see the same issue.
[updated-nginx.conf.txt](https://github.com/jellyfin/jellyfin/files/4693591/updated-nginx.conf.txt)

I'm experimenting with the Cache Video Streams configuration [here](https://github.com/jellyfin/jellyfin-docs/blob/0012ef48130a07f47fe2496ec9f0b8f3b80a8f30/general/networking/nginx.md#cache-video-streams) but I'm not an nginx expert and hit a problem. When I try to play a file I get a Playback Error - There was an issue with the client profiling and the server isn't sending a compatible media format.

Here's the updated jellyfin.conf and server log:
[updated-jellyfin.conf.txt](https://github.com/jellyfin/jellyfin/files/4693598/updated-jellyfin.conf.txt)
[updated-bad-nginx-proxybufferoff.txt](https://github.com/jellyfin/jellyfin/files/4693636/updated-bad-nginx-proxybufferoff.txt)

Of course, nginx may be a moot point. Two things I forgot to note before: 1) Caddy2 exhibits the same behavior as nginx and 2) if I disable hardware acceleration I *do not* see the issue.

**Comment by ferferga** [comment]
@whozur Did you try without the cache first?

**Comment by Artiume** [comment]
I can't really help with the cache config, not sure what's up with it. I do think my theory about the bandwidth upload limit being exceeded makes sense. Any luck with monitoring traffic via the router

**Comment by whozur** [comment]
@ferferga I never got the nginx cache config working... due to some other issues, I switched to Caddy2. It's working well for my other apps and it's easy for me to manage :)

@Artiume, I'll check out traffic monitoring via the router. Anything in particular I should look for or logs you're interested in? Thx.

**Comment by Artiume** [comment]
nothing in particular, just bandwidth usage

**Comment by whozur** [comment]
I ended up changing a few things in my set up, including moving from nginx to caddy2, and I can no longer reproduce this issue.

**Comment by Artiume** [comment]
Could you post both configs for later? I'd like to test it when I have time
