### ISSUE TITLE
Jellyfin Ldap Plugin size limit exceeded

### ISSUE THREAD

**Issue by ellismk** [jellyfin/jellyfin#3200]
OS: CentOS 8.1.1911
Jellyfin: 10.5.4
Ldap Plugin: 6.0.0.0
Windows 2016 AD
I have all of this working on my Test system which does not have the number of users as the production system.  When I try on the production system I get a LDAP size limit exceeded error in the logs.  Using the ldapsearch command line query works just fine.  Is there some setting to make the Ldap plugin handle a large number of users?

**Comment by ellismk** [comment]
I got this to work by changing the LDAP filter to search a much smaller group of users to avoid the size limit error.  Still think the plugin should be able to handle large amount of users.

**Comment by crobibero** [comment]
Duplicate of https://github.com/jellyfin/jellyfin-plugin-ldapauth/issues/39
