### ISSUE TITLE
Multiple Connection Segmented Streaming

### ISSUE THREAD

**Issue by Robertomcat** [jellyfin/jellyfin#3206]
Hello, good morning.

I've been using Jellyfin and PLEX for a while now, and previously I was using 7 Mb bandwidth, so I had to watch both the series and the movies on both platforms in quite low quality.

Now, I have increased the bandwidth to 30 Mb, because they have incorporated fibre optics in the village, and by incorporating this bandwidth I have had a new problem on both platforms. There have been comments on the PLEX forum, but I don't think anyone here has reported on it.

The problem has been that both PLEX and Jellyfin use one thread to send the stream to the customer, so they never use all the bandwidth to create a buffer for a few seconds, and then ask for the file as required.

Here are some links related to the problems that PLEX has in this aspect, and that surely can be corrected in Jellyfin.

https://forums.plex.tv/t/feature-request-multiple-connection-segmented-streaming/19035

https://forums.plex.tv/t/better-internet-streaming-using-multiple-parallel-connections-or-threads/236442

https://forums.plex.tv/t/request-multi-segmented-streaming-ideally-to-speed-up-remote-streaming/92706

Thank you for the project.

**Comment by Artiume** [comment]
I might be wrong, but wouldn't HTTP/2 provide this function with its ability to multi-thread connections

**Comment by Robertomcat** [comment]
> 
> 
> I might be wrong, but wouldn't HTTP/2 provide this function with its ability to multi-thread connections

The tests I have done have been on LAN and WAN, and to reproduce any file I have encountered the same problem as with PLEX, after testing with the iperf tool.

I am not an expert in networks, so I made this instance public to see if anyone could clarify my query. Thank you!

**Comment by Artiume** [comment]
can i see your test results with iperf?

**Comment by Robertomcat** [comment]
This is the result of iperf, having a bandwidth of 30/30, and iperf is working just as well as both PLEX and jellyfin. But when you download anything from the Internet (gdrive, steam, epic...) it takes up all the bandwidth, which is not the case with jellifin.

Jellyfin is installed on an ML110 G9 server with an E5-2630L V4 processor, 64 GB RAM, 8 × 10 TB in RAID 5 and 600/600 bandwidth, so there is no problem when it comes to retransmission.

Download-upload
![iperf](https://user-images.githubusercontent.com/17690060/83628426-b8aa4500-a598-11ea-9f85-05f5bab85181.jpg)

**Comment by Artiume** [comment]
One of the issues I imagine is the buffer band that's built into the ffmpeg stream. Can you post some ffmpeg logs? I'll show you what I'm talking about

**Comment by Robertomcat** [comment]
Here's the file. Thank you.
[ffmpeg.txt](https://github.com/jellyfin/jellyfin/files/4723713/ffmpeg.txt)

**Comment by Artiume** [comment]
So for your direct stream logs, I actually didn't see a buffer. Maybe that's because it's not transcoded? I'm not sure. I was expecting to find something like this

`-codec:v:0 h264_qsv -preset 7 -look_ahead 0 -b:v 15298600 -maxrate 15298600 -bufsize 30597200 -profile:v high`
As you can see the buffer is double of the max bitrate. That's to ensure no buffering during peak bitrate.

**Comment by Robertomcat** [comment]
> 
> 
> So for your direct stream logs, I actually didn't see a buffer. Maybe that's because it's not transcoded? I'm not sure. I was expecting to find something like this
> 
> `-codec:v:0 h264_qsv -preset 7 -look_ahead 0 -b:v 15298600 -maxrate 15298600 -bufsize 30597200 -profile:v high`
> As you can see the buffer is double of the max bitrate. That's to ensure no buffering during peak bitrate.

Is a direct retransmission, but at no time do I occupy the bandwidth of 30 Mb, it retransmits the file with maximum peaks of 15 Mb, and the retransmission is between 7 Mb and 15 Mb + or -.

The good thing would be that I make buffer occupying the bandwidth of my 30/30 connection, and once I have created a buffer of X time, start sending the file when the client needs it, also being able to occupy the entire bandwidth.
