### ISSUE TITLE
Problem with Artist folder containing album folders and files

### ISSUE THREAD

**Issue by davidcheeeese** [jellyfin/jellyfin#3210]
When a Artist folder contain albums subfolders and separate files (singles) not stored on a subfolder, all titles are grouped in one album ignoring others available.

 - OS: Archlinux
 - Clients: All
 - Browser: All
 - Jellyfin Version: 10.5.5
 - Base URL: None
 - Storage: local

**To Reproduce**
- Create an Artist folder in your music library
- Add files and albums
- Scan library
- Check artist listing (see attached screenshots) and the displayed album

**Expected behavior**
I was hoping to have all albums displayed and in bonus files too on the artist page

**Screenshots**
![kraftwerk_listing_1](https://user-images.githubusercontent.com/58604809/83353001-d0db5380-a34f-11ea-91a2-ea1a11b22039.png)
Resulting
![kraftwerk_with_files](https://user-images.githubusercontent.com/58604809/83353013-e486ba00-a34f-11ea-92ef-9bc7a61f54de.png)
![kraftwerk_with_files_listing](https://user-images.githubusercontent.com/58604809/83353019-ecdef500-a34f-11ea-99ea-20ceadb87103.png)

![kraftwerk_listing_2](https://user-images.githubusercontent.com/58604809/83353028-f6685d00-a34f-11ea-84fb-8d747c549a1c.png)
Resulting
![kraftwerk_without_files](https://user-images.githubusercontent.com/58604809/83353105-80182a80-a350-11ea-9170-cbb145145548.png)
![kraftwerk_without_files_listing](https://user-images.githubusercontent.com/58604809/83353109-85757500-a350-11ea-888b-5e759981e87e.png)

**Comment by Fabeuss** [comment]
same here, but thanks a lot for reporting this bug, I finally understand why I had this problem in my library, and I can finally fix all that !

**Comment by davidcheeeese** [comment]
Found duplicate with #3169
