### ISSUE TITLE
File played with wrong video codec

### ISSUE THREAD

**Issue by Videl** [jellyfin/jellyfin#3213]
**Describe the bug**
With mpv-shim, while asking for h265 as shown by the url, I get the video in h264:

* http://server/hls1/main/0.ts?DeviceId=id&MediaSourceId=fileid&VideoCodec=h265,hevc,h264,mpeg4,mpeg2video&AudioCodec=aac,mp3,ac3,opus,flac,vorbis&AudioStreamIndex=1&VideoBitrate=9616000&AudioBitrate=384000&PlaySessionId=ec0594e7885f4fa295c20528f90d04f0&api_key=ef744d2519ce4730a5062ef4bc4a920d&TranscodingMaxAudioChannels=6&RequireAvc=false&Tag=804aa977b17a4b5a43ae3d12027a54e0&SegmentContainer=ts&BreakOnNonKeyFrames=False&TranscodeReasons=ContainerNotSupported,VideoCodecNotSupported,AudioCodecNotSupported

Is the following command line for ffmpeg normal? Is the bsf:v argument normal?

* ``/usr/lib/jellyfin-ffmpeg/ffmpeg -fflags +genpts -i file:"filepath" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 copy -bsf:v h264_mp4toannexb -vsync -1 -codec:a:0 aac -ac 6 -ab 384000  -copyts -avoid_negative_ts disabled -f hls -max_delay 5000000 -hls_time 6 -individual_header_trailer 0 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/config/transcodes/...ts" -hls_playlist_type vod -hls_list_size 0 -y "/config/transcodes/...m3u8"``

Here's the file data:
```

{
  "Protocol": "File",
  "Id": "fileid",
  "Path": "filepath",
  "Type": "Default",
  "Container": "mkv,webm",
  "Size": 1978557952,
  "Name": "filename",
  "IsRemote": false,
  "RunTimeTicks": 30805118976,
  "ReadAtNativeFramerate": false,
  "IgnoreDts": false,
  "IgnoreIndex": false,
  "GenPtsInput": false,
  "SupportsTranscoding": true,
  "SupportsDirectStream": true,
  "SupportsDirectPlay": true,
  "IsInfiniteStream": false,
  "RequiresOpening": false,
  "RequiresClosing": false,
  "RequiresLooping": false,
  "SupportsProbing": true,
  "VideoType": "VideoFile",
  "MediaStreams": [
    {
      "Codec": "h264",
      "TimeBase": "1/1000",
      "CodecTimeBase": "1001/48000",
      "VideoRange": "SDR",
      "DisplayTitle": "720P H264",
      "NalLengthSize": "4",
      "IsInterlaced": false,
      "IsAVC": true,
      "BitRate": 5138257,
      "BitDepth": 8,
      "RefFrames": 1,
      "IsDefault": true,
      "IsForced": false,
      "Height": 720,
      "Width": 1280,
      "AverageFrameRate": 23.976025,
      "RealFrameRate": 23.976025,
      "Profile": "High",
      "Type": "Video",
      "AspectRatio": "16:9",
      "Index": 0,
      "IsExternal": false,
      "IsTextSubtitleStream": false,
      "SupportsExternalStream": false,
      "PixelFormat": "yuv420p",
      "Level": 31
    },
    {
      "Codec": "eac3",
      "Language": "eng",
      "TimeBase": "1/1000",
      "CodecTimeBase": "1/48000",
      "DisplayTitle": "Eng Dolby Digital+ 6 ch Default",
      "IsInterlaced": false,
      "Channels": 6,
      "SampleRate": 48000,
      "IsDefault": true,
      "IsForced": false,
      "Type": "Audio",
      "Index": 1,
      "IsExternal": false,
      "IsTextSubtitleStream": false,
      "SupportsExternalStream": false,
      "Level": 0
    },
    {
      "Codec": "subrip",
      "Language": "eng",
      "TimeBase": "1/1000",
      "CodecTimeBase": "0/1",
      "localizedUndefined": "Undefined",
      "localizedDefault": "Default",
      "localizedForced": "Forced",
      "DisplayTitle": "Eng",
      "IsInterlaced": false,
      "IsDefault": false,
      "IsForced": false,
      "Type": "Subtitle",
      "Index": 2,
      "IsExternal": false,
      "IsTextSubtitleStream": true,
      "SupportsExternalStream": true,
      "Level": 0
    },
    {
      "Codec": "subrip",
      "Language": "eng",
      "TimeBase": "1/1000",
      "CodecTimeBase": "0/1",
      "Title": "SDH",
      "localizedUndefined": "Undefined",
      "localizedDefault": "Default",
      "localizedForced": "Forced",
      "DisplayTitle": "SDH - Eng",
      "IsInterlaced": false,
      "IsDefault": false,
      "IsForced": false,
      "Type": "Subtitle",
      "Index": 3,
      "IsExternal": false,
      "IsTextSubtitleStream": true,
      "SupportsExternalStream": true,
      "Level": 0
    },
    {
      "Codec": "srt",
      "Language": "chi",
      "localizedUndefined": "Undefined",
      "localizedDefault": "Default",
      "localizedForced": "Forced",
      "DisplayTitle": "Chi",
      "IsInterlaced": false,
      "IsDefault": false,
      "IsForced": false,
      "Type": "Subtitle",
      "Index": 4,
      "IsExternal": true,
      "IsTextSubtitleStream": true,
      "SupportsExternalStream": true,
      "Path": "file"
    },
    {
      "Codec": "srt",
      "Language": "fre",
      "localizedUndefined": "Undefined",
      "localizedDefault": "Default",
      "localizedForced": "Forced",
      "DisplayTitle": "Fre",
      "IsInterlaced": false,
      "IsDefault": false,
      "IsForced": false,
      "Type": "Subtitle",
      "Index": 5,
      "IsExternal": true,
      "IsTextSubtitleStream": true,
      "SupportsExternalStream": true,
      "Path": "file"
    }
  ],
  "MediaAttachments": [],
  "Formats": [],
  "Bitrate": 5138257,
  "RequiredHttpHeaders": {}
}
```

**System:**

Tried jellyfin server on two systems:

 - OS: Windows, Debian
 - Virtualization: none, Docker
 - Clients: mpv-shim
 - Jellyfin Version: v10.5.5
 - Playback: Transcode

**To Reproduce**
mpv-shim settings: 
* always transcode: true
* transcode to h265: true
* change video quality: (something other than default format)

**Expected behavior**
When I push the "i" shortcut to see informations, I expect to see "Video: h265", but there is "h264".

I tried debugging on my own but I didn't manage to debug on one thread only?
I think at some point the state StreamState object ends up with the h264 video codec.
I believe it is linked to method ``EncodingHelper.TryStreamCopy`` but maybe I just got confused by all the threads getting triggered. 
Is it possible to lock on a thread when debugging? 🐙

**Comment by Artiume** [comment]
Our hls currently cannot stream h265, only h264. We did have a pr that fixed this but we had to remove it for 10.6 because it changed the api too much on such short notice. I believe this was the pr

https://github.com/jellyfin/jellyfin/pull/2573
