### ISSUE TITLE
Too many ffmpeg processes spawned 

### ISSUE THREAD

**Issue by mirolm** [jellyfin/jellyfin#3215]
**Describe the bug**

I noticed that when i play a H265 video and it needs to be transcoded to play sometimes it spawns alot ffmpeg processes which can eat all system memory and make my system crawl because of the swapping. Strangely enough it does not happen every time but in 1 of 10-15 times such video is played this happens. 

My System Specs are: HP EliteDesk 800G1 USDT, Intel i5-4570S, 8GB RAM (around 3GB is free at all times), 500GB HDD

This system has various things installed on it - nginx, php, mysql, postgre, rtorrent, flood, sonarr, jackett, jellyfin, samba and so on. It is moderately busy but CPU rare climbs to more than 1.5 load average even when transcode is active.

It transcodes with VAAPI, but this cpu can only transcode H264 and when H265 video is played it is transcoded by the CPU. I suppose it starts to extract all this fonts, subs and so on in paralel and spawns alot ffmpeg processes to do to. Maybe it is good idea to limit the number of processes in order to prevent swapping on configurations with lower amount of RAM.

**System (please complete the following information):**
 - OS: Debian Buster 10
 - Virtualization: none
 - Clients: Browser
 - Browser: Chromium 83.0.4103.61 (Official Build) Arch Linux (64-bit)
 - Jellyfin Version: 10.5.5
 - Playback: Transcode 
 - Installed Fanart, Anime
 - Reverse Proxy: nginx
 - Base URL: none
 - Networking: Host
 - Storage: local

**To Reproduce**
1. Start to play a new movie from the begining. It does not happen if you continue to play one you started previously.
2. Look at the console of the linux box
3. Sometimes alot of ffmpeg processes are spawned - more than 10-15. Every one of them eats like 100 - 200 MB RAM.
4. See how all memory is eaten and machine starts to swap, load average gets to more than 20 on a 4 core system.
5. After like 30-60 seconds things go back to normal. Maybe this processes finish their task and release the memory.

**Expected behavior**

Number of ffmpeg processes should be limited.

**Logs**

[Log_jellyfin.txt](https://github.com/jellyfin/jellyfin/files/4711539/Log_jellyfin.txt)
[Log_transcode.txt](https://github.com/jellyfin/jellyfin/files/4711540/Log_transcode.txt)

**Screenshots**

The below screenshot i managed to get, barely avoided the heavy swapping. In this case it went away after 5 seconds. But sometimes i get not so lucky and the system is unresponsive for alot longer.

![image](https://user-images.githubusercontent.com/9135358/83363589-402e6300-a3a3-11ea-8bee-3186d936518b.png)

**Additional context**

None.

**Comment by Artiume** [comment]
Can you disable VAAPI (and upload clean logs without your domain) and see if that helps?

**Comment by mirolm** [comment]
Without VAAPI load average jumped from 1.5 to 3.5 in normal situations. Still played okay.

When i switched to the next episode again i saw alot ffmpeg processes and system swapped.

![image](https://user-images.githubusercontent.com/9135358/83431645-54746d80-a440-11ea-99ec-10a16f903e74.png)
![image](https://user-images.githubusercontent.com/9135358/83431684-6524e380-a440-11ea-8a73-285e114929b5.png)

Attached below you can find the jellyfin logfile:

[Log_No_VaAPI.txt](https://github.com/jellyfin/jellyfin/files/4712402/Log_No_VaAPI.txt)

**Comment by mirolm** [comment]
I noticed that the above file has more than 40 streams - all related to subtitbles. Maybe jellyfin tries to extract them all and doing so in paralel it eats all the memory.

[file_info_nazo.log](https://github.com/jellyfin/jellyfin/files/4715090/file_info_nazo.log)

Usually i play shows from HorribleSubs for example and they have only 4 streams - 1 video, 1 audio, 1 subtitles, 1 subtitle font.

[file_info_hina.log](https://github.com/jellyfin/jellyfin/files/4715094/file_info_hina.log)

**Comment by Artiume** [comment]
Try turning off subtitle extraction on the fly

**Comment by mirolm** [comment]
Will try that and see if this workarounds the issue.

In the log there is a request to extract each attachment. Why not batch all attachments in one request:

````
/usr/lib/jellyfin-ffmpeg/ffmpeg -dump_attachment:17 /media/lv2/download/temp/3bc21c18-9479-6e3b-65c8-9e3967700fa -dump_attachment:6 /media/lv2/download/temp/86ebddfe-fb82-4a4e-0916-00dc68485c76 -i file:"/media/lv2/download/temp/Mysterious.Girlfriend.X.S01E13.013.Bluray-1080p-Cleo.mkv" -t 0 -f null null
````

**Comment by Artiume** [comment]
if batching works better, go for it. A lot of design choices are either legacy or bandaids

**Comment by mirolm** [comment]
I tested and extracted all 47 streams at once and it took less than a second. It should work faster because the container file is parsed only once and all streams get extracted. It should use less memory, cpu and will not trash hard disk to read the input file so many times.

Sadly making the changes in the jellyfin code is beyond me. Trying to do some troubleshooting is all i can do.

When i get home will try to turn off the subtitle extraction option and see how jellyfin will react.

**Comment by Artiume** [comment]
Thanks for digging into it. Troubleshooting takes time too and every minute saved is worth it. Let's see what the extractor does and if that's the code that controls the logic, it'll make it a lot easier to fix

**Comment by mirolm** [comment]
Removeing sub extraction did not help:

![image](https://user-images.githubusercontent.com/9135358/83539811-353d1500-a500-11ea-97a9-f19ebf80293a.png)

**Comment by zatricky** [comment]
I'm seeing this same issue affecting server stability. Per the suggestions, sure enough, the media did have **many** streams.
Streams: 1 video (h264) stream, 1 audio (aac) stream, 9 subtitle (ssa) streams, and 60 font (mostly ttf) attachments.

The results without "fixing" the media:
A few seconds after pressing play, the server becomes unresponsive due to high CPU ; Some of the ffmpeg processes are also killed each time due to OOM ; The highest count of simultaneous ffmpeg processes (a simple `ps aux | grep -c f[f]mpeg` ) I could view before the server became unresponsive was 62. The server is a 4GB VM dedicated to Jellyfin.

Disabling the "Allow subtitle extract on the fly" option resulted in a typical "incompatible" codecs-related error in Chrome.

Based on the numbers, it seems _every_ stream spawns an additional ffmpeg process, regardless of stream-type. After analysing the subtitles, only 1 subtitle interested me and, in those subs, only 3 fonts were referred to. I removed the 8 extra subtitles and the 57 extraneous fonts using ffmpeg. As a result, playback works again. However, this only fixed a single episode. I certainly don't want manually to do this for all episodes. :-/

**Comment by Artiume** [comment]
on the fly shouldn't attempt to extract everything at once but only the requested streams. all the subtitle info should be gotten during the initial scan so there's no reason to do it live.

**Comment by mirolm** [comment]
This are usually fonts not subs. In some anime videos there are alot of fonts, because they change them to show different character voices and stuff. When such video is handled by jellyfin it extracts all fonts and spawns tons of ffmpeg processes to do so. This can cause swapping and bring disk subsystem to a crawl.

**Comment by mirolm** [comment]
Jellyfin 10.7 is still trashing the disk when trying to extract attachments from video files. Tho so far i have not seen my system swap it still takes like 10 or more seconds to extract them all and during this time hard disk is maxed.

I still think that instead of spawning paralel ffmpeg processes to extract multiple attachments jellyfin should do 1 process with all requests batched into it. Maybe paralel processes is not a big deal with faster storage devices, but with older and slower ones it hurts for sure.

I hope this is reevaluated and fixed in future versions.

**Comment by cvium** [comment]
It requires a bunch of changes... https://github.com/jellyfin/jellyfin-web/blob/release-10.7.z/src/plugins/htmlVideoPlayer/plugin.js#L1051-L1056

**Comment by mirolm** [comment]
I noticed things get better when i changed kernel io shedulers with the below udev rules from [arch wiki](https://wiki.archlinux.org/index.php/improving_performance#Kernel's_I/O_schedulers):

# set scheduler for NVMe
ACTION=="add|change", KERNEL=="nvme[0-9]n[0-9]", ATTR{queue/scheduler}="none"
# set scheduler for SSD and eMMC
ACTION=="add|change", KERNEL=="sd[a-z]|mmcblk[0-9]*", ATTR{queue/rotational}=="0", ATTR{queue/scheduler}="mq-deadline"
# set scheduler for rotating disks
ACTION=="add|change", KERNEL=="sd[a-z]", ATTR{queue/rotational}=="1", ATTR{queue/scheduler}="bfq"

This changed sheduler for my hard drive where videos are stored to bfq and now things load a little faster.
