### ISSUE TITLE
TMDB Does not fetch season images correctly

### ISSUE THREAD

**Issue by Darksecond** [jellyfin/jellyfin#3217]
**Describe the bug**
Using TMDB for 'Season Image Fetchers' does not fetch season images.

From doing some research it looks like TMDB does not return season images in their response. 
I've made a forum post at their forums to get more information with a possible solution. (https://www.themoviedb.org/talk/5ed404861b157d001f55279a).

**System:**
 - OS: Ubuntu 18.04
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Firefox 76
 - Jellyfin Version: 10.5.5
 - Playback: N/A
 - Installed Plugins: FanArt
 - Reverse Proxy: traefik
 - Base URL: none
 - Networking: NAT
 - Storage: NFS

**To Reproduce**
1. Enable TMDB as a season image fetch and move it to the top.
2. I also have TMDB as a metadata fetcher, although I do not know if this matters.
3. Fetch images for a series (so rescan with replace images for example)
4. It should show the correct season images, instead it does not, falling back to either another provider (like fanart), or the main series image.

**Expected behavior**
I expect jellyfin to fetch TMDB season images.

**Additional context**
It looks like this

**Comment by Artiume** [comment]
https://github.com/jellyfin/jellyfin/blob/f8e8bfc3996bcc3b28b620b508c3b43441002c8c/MediaBrowser.Providers/Tmdb/TV/TmdbSeasonImageProvider.cs#L71

Here's the URL builder for Tmdb Season Images

**Comment by Darksecond** [comment]
> 
> 
> https://github.com/jellyfin/jellyfin/blob/f8e8bfc3996bcc3b28b620b508c3b43441002c8c/MediaBrowser.Providers/Tmdb/TV/TmdbSeasonImageProvider.cs#L71
> 
> Here's the URL builder for Tmdb Season Images

Looks like the issue is rather a bit down in https://github.com/jellyfin/jellyfin/blob/f8e8bfc3996bcc3b28b620b508c3b43441002c8c/MediaBrowser.Providers/Tmdb/TV/TmdbSeasonImageProvider.cs#L67 . It fetches the season metadata, (which is supposed to include season images, but doesn't always).

So it's probably in this line, or at least file https://github.com/jellyfin/jellyfin/blob/f8e8bfc3996bcc3b28b620b508c3b43441002c8c/MediaBrowser.Providers/Tmdb/TV/TmdbSeasonProvider.cs#L26

**Comment by Neolel** [comment]
https://www.themoviedb.org/talk/5ed404861b157d001f55279a
There was a reply on TMDb 2 days after the latest reply here. Which seems to be the fix. Just to make sure you noticed.

**Comment by joelliang** [comment]
Hi @Ullmie02 , It seems you are the author of the TMDb image provider. Could you please help to fix this issue? I'd like to have the seaon poster for my Anime (https://www.themoviedb.org/tv/37854/seasons).

**Comment by Ullmie02** [comment]
I could reproduce the issue that the TMDB season images showed the series images because of a copy/paste mistake. The linked PR should fix it
