### ISSUE TITLE
Create SyncPlay groups before playback starts

### ISSUE THREAD

**Issue by mcarlton00** [jellyfin/jellyfin#3228]
**Describe the bug**

It should probably be possible to create a SyncPlay session before starting playback.  As of right now the process is:

1. Start a playback session
2. Pause the video
3. Create a session
4. Get other members to join
5. Unpause the video

This seems a bit clunky from a UX perspective and seems as though it could be optimized to allow sessions to be created before playback starts.

**System (please complete the following information):**
 - OS: Linux
 - Virtualization: Docker
 - Jellyfin Version: nightly 20200530
 - Reverse Proxy: nginx

cc @OancaAndrei for thoughts

**Comment by OancaAndrei** [comment]
I totally agree. I think this will be fixed with the upcoming changes.

**Comment by mcarlton00** [comment]
shoo bot, you have no power here
