### ISSUE TITLE
mp4 playback on Panasonic Viera

### ISSUE THREAD

**Issue by JSYShaggy** [jellyfin/jellyfin#3233]
When trying to play mp4 files on a Panasonic TV the files are not supported. Other file types play fine. All files play on an older Sony Bravia and iPhone, the same files also play on both TVs when streamed with Emby running on the same server. When comparing the DLNA profiles on Emby and Jellyfin both are identical for Panasonic Viera and General.

**Media Info of the file**

Scoob.2020.1080p.WEBRip.x264.AAC5.1-[YTS.MX]
Containermp4
PathD:\Media Server\Movies\Childrens\Scoob.2020.1080p.WEBRip.x264.AAC5.1-[YTS.MX].mp4
Size1769 MB
Video
Title1080P H264
CodecH264
Codec tagavc1
AVCYes
ProfileHigh
Level41
Resolution1920x800
Aspect ratio2.40:1
InterlacedNo
Framerate23.976025
Bitrate2249 kbps
Bit depth8 bit
Pixel formatyuv420p
Ref frames1
NAL4
Audio
TitleUnd AAC 5.1 Default
Languageund
CodecAAC
Codec tagmp4a
ProfileLC
Layout5.1
Channels6 ch
Bitrate384 kbps
Sample rate48000 Hz
DefaultYes

**Logs**

**FFmpeg Logs**
None

**Stats for Nerds Screenshots**
None

**Server System (please complete the following information):**
 - OS: Windows
 - Jellyfin Version: 10.5.5
 - Hardware settings & device: None
 - Reverse proxy: None
 - Other hardware notes: None
 
**Client System (please complete the following information):**
 - Device: Panasonic Viera TX-40EX600B
 - OS: ?
 - Client: File Server

**Comment by svemonix** [comment]
I do have the same issue with my Panasonic 55CX700. It is impossible to play any mp4 files through jellyfin's DLNA (exclamation mark in the file list & "file not supported" message when trying to play). I've seen similar issues reported on Emby's forum in the past.

It does work fine with other DLNA servers like Plex, mini-dlna, etc.

Surprisingly, the issue occurs even with a DLNA profile that should allow all direct play.

**Comment by JSYShaggy** [comment]
I managed to get most mp4s to play. I removed all the direct play movie profiles and added them back in one at a time. I managed to narrow it down to the mov profile - when I added this all mp4s broke when I removed it they worked again. The odd thing is though that unrelated movies which worked with the normal profile stopped working when I removed the mov profile even when though they weren't movs. I've started to look at developing so hope one day I can contribute

**Comment by svemonix** [comment]
Thanks JSYShaggy for the investigation.

It sounds like there's something wrong with the way the DLNA profile is read or applied. In any case, it would explain why a dummy direct play 'all' profile doesn't work as MOV would be part of it.

Following your findings, I ended up creating a new profile based upon the PS4 since it doesn't contain MOV and has the most common formats. It seems to work even though I haven't tested thoroughly. I can play MP4 and MKV.

What types of movies ended broken when MP4 were fine?

**Comment by svemonix** [comment]
While testing further my PS4 based profile, I had some issues with a few MKV which I couldn't play and were identified by the TV as MPEG-PS.

It turned out that the MKV I couldn't play had embedded subtitles in PGS or SUB format but none of the Jellyfin default profiles have those included.

So this time, I created a new profile based upon the Panasonic one and did the following:
- add SUB, PGS, PGSSUB to the subtitle profiles
- remove the MOV container from Direct Play
=> Now all seems to work just fine!

**Comment by millallo** [comment]
Hi scemonix,
I have some issues with MKV, can you share your custom Panasonic xml?

thanks

**Comment by svemonix** [comment]
My XML looks like this:

`<?xml version="1.0"?>
<Profile xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Name>55CX725</Name>
  <Identification>
    <FriendlyName>VIERA</FriendlyName>
    <ModelNumber />
    <SerialNumber />
    <ModelName />
    <DeviceDescription />
    <ModelUrl />
    <Manufacturer>Panasonic</Manufacturer>
    <ManufacturerUrl />
    <Headers>
      <HttpHeaderInfo name="User-Agent" value="Panasonic MIL DLNA" match="Substring" />
    </Headers>
  </Identification>
  <FriendlyName />
  <Manufacturer>Jellyfin</Manufacturer>
  <ManufacturerUrl>https://github.com/jellyfin/jellyfin</ManufacturerUrl>
  <ModelName>Jellyfin Server</ModelName>
  <ModelNumber>01</ModelNumber>
  <ModelUrl>https://github.com/jellyfin/jellyfin</ModelUrl>
  <SerialNumber />
  <EnableAlbumArtInDidl>false</EnableAlbumArtInDidl>
  <EnableSingleAlbumArtLimit>false</EnableSingleAlbumArtLimit>
  <EnableSingleSubtitleLimit>false</EnableSingleSubtitleLimit>
  <SupportedMediaTypes>Audio,Photo,Video</SupportedMediaTypes>
  <UserId />
  <AlbumArtPn>JPEG_SM</AlbumArtPn>
  <MaxAlbumArtWidth>480</MaxAlbumArtWidth>
  <MaxAlbumArtHeight>480</MaxAlbumArtHeight>
  <MaxIconWidth>48</MaxIconWidth>
  <MaxIconHeight>48</MaxIconHeight>
  <MaxStreamingBitrate>140000000</MaxStreamingBitrate>
  <MaxStaticBitrate>140000000</MaxStaticBitrate>
  <MusicStreamingTranscodingBitrate>192000</MusicStreamingTranscodingBitrate>
  <MaxStaticMusicBitrate xsi:nil="true" />
  <SonyAggregationFlags />
  <ProtocolInfo>http-get:*:video/mpeg:*,http-get:*:video/mp4:*,http-get:*:video/vnd.dlna.mpeg-tts:*,http-get:*:video/avi:*,http-get:*:video/x-matroska:*,http-get:*:video/x-ms-wmv:*,http-get:*:video/wtv:*,http-get:*:audio/mpeg:*,http-get:*:audio/mp3:*,http-get:*:audio/mp4:*,http-get:*:audio/x-ms-wma:*,http-get:*:audio/wav:*,http-get:*:audio/L16:*,http-get:*:image/jpeg:*,http-get:*:image/png:*,http-get:*:image/gif:*,http-get:*:image/tiff:*</ProtocolInfo>
  <TimelineOffsetSeconds>10</TimelineOffsetSeconds>
  <RequiresPlainVideoItems>false</RequiresPlainVideoItems>
  <RequiresPlainFolders>false</RequiresPlainFolders>
  <EnableMSMediaReceiverRegistrar>false</EnableMSMediaReceiverRegistrar>
  <IgnoreTranscodeByteRangeRequests>false</IgnoreTranscodeByteRangeRequests>
  <XmlRootAttributes />
  <DirectPlayProfiles>
    <DirectPlayProfile container="mpeg,mpg" audioCodec="ac3,mp3,pcm_dvd" videoCodec="mpeg2video,mpeg4" type="Video" />
    <DirectPlayProfile container="mkv" audioCodec="aac,ac3,dca,mp3,mp2,pcm,dts" videoCodec="h264,mpeg2video" type="Video" />
    <DirectPlayProfile container="ts,mpegts" audioCodec="aac,mp3,mp2" videoCodec="h264,mpeg2video" type="Video" />
    <DirectPlayProfile container="mp4,m4v" audioCodec="aac,ac3,mp3,pcm" videoCodec="h264" type="Video" />
    <DirectPlayProfile container="avi" audioCodec="pcm" videoCodec="mpeg4" type="Video" />
    <DirectPlayProfile container="flv" audioCodec="aac" videoCodec="h264" type="Video" />
    <DirectPlayProfile container="mp3" audioCodec="mp3" type="Audio" />
    <DirectPlayProfile container="mp4" audioCodec="aac" type="Audio" />
    <DirectPlayProfile container="jpeg" type="Photo" />
  </DirectPlayProfiles>
  <TranscodingProfiles>
    <TranscodingProfile container="mp3" type="Audio" audioCodec="mp3" estimateContentLength="false" enableMpegtsM2TsMode="false" transcodeSeekInfo="Auto" copyTimestamps="false" context="Streaming" enableSubtitlesInManifest="false" minSegments="0" segmentLength="0" breakOnNonKeyFrames="false" />
    <TranscodingProfile container="ts" type="Video" videoCodec="h264" audioCodec="ac3" estimateContentLength="false" enableMpegtsM2TsMode="false" transcodeSeekInfo="Auto" copyTimestamps="false" context="Streaming" enableSubtitlesInManifest="false" minSegments="0" segmentLength="0" breakOnNonKeyFrames="false" />
    <TranscodingProfile container="jpeg" type="Photo" estimateContentLength="false" enableMpegtsM2TsMode="false" transcodeSeekInfo="Auto" copyTimestamps="false" context="Streaming" enableSubtitlesInManifest="false" minSegments="0" segmentLength="0" breakOnNonKeyFrames="false" />
  </TranscodingProfiles>
  <ContainerProfiles>
    <ContainerProfile type="Photo">
      <Conditions>
        <ProfileCondition condition="LessThanEqual" property="Width" value="1920" isRequired="true" />
        <ProfileCondition condition="LessThanEqual" property="Height" value="1080" isRequired="true" />
      </Conditions>
    </ContainerProfile>
  </ContainerProfiles>
  <CodecProfiles>
    <CodecProfile type="Video">
      <Conditions>
        <ProfileCondition condition="LessThanEqual" property="Width" value="1920" isRequired="true" />
        <ProfileCondition condition="LessThanEqual" property="Height" value="1080" isRequired="true" />
        <ProfileCondition condition="LessThanEqual" property="VideoBitDepth" value="8" isRequired="false" />
      </Conditions>
      <ApplyConditions />
    </CodecProfile>
  </CodecProfiles>
  <ResponseProfiles>
    <ResponseProfile container="ts,mpegts" type="Video" orgPn="MPEG_TS_SD_EU,MPEG_TS_SD_NA,MPEG_TS_SD_KO" mimeType="video/vnd.dlna.mpeg-tts">
      <Conditions />
    </ResponseProfile>
    <ResponseProfile container="m4v" type="Video" mimeType="video/mp4">
      <Conditions />
    </ResponseProfile>
  </ResponseProfiles>
  <SubtitleProfiles>
    <SubtitleProfile format="srt" method="Embed" />
    <SubtitleProfile format="srt" method="External" />
    <SubtitleProfile format="sub" method="Embed" didlMode="" />
    <SubtitleProfile format="pgs" method="Embed" didlMode="" />
    <SubtitleProfile format="pgssub" method="Embed" didlMode="" />
  </SubtitleProfiles>
</Profile>`

**Comment by i-m-d** [comment]
Hello,

 I just delete fon direct play "mov" and magically mp4 plays OK.
