### ISSUE TITLE
Scanning fails on titles with spaces after migrating to 10.5.5

### ISSUE THREAD

**Issue by usstattik** [jellyfin/jellyfin#3234]
**Describe the bug**

Migrated from 10.4.3 to 10.5.5.  New films were showing up in the library with no metadata or images.  This was only happening on titles with spaces in them.  Titles without spaces show up fine in the library.  Scanning worked fine on titles with spaces in 10.4.3.

**System (please complete the following information):**
 - OS: Debian on KVM
 - Virtualization: Docker
 - Clients: Browser, Android
 - Jellyfin Version: 10.5.5
 - Playback: Direct Play
 - Installed Plugins: Tract 9.0.0.0
 - Reverse Proxy: None
 - Storage: CIFS

**To Reproduce**
Add title with a space and initiate a scan.

**Expected behavior**
Title with scan should show up in library with metadata and images.

**Logs**
I can provide whatever is needed.

**Comment by Ullmie02** [comment]
I'm using file names with spaces too and don't see your described behavior. Could you please provide your logs after you scanned the library?

**Comment by usstattik** [comment]
[jellyfin.zip](https://github.com/jellyfin/jellyfin/files/4800762/jellyfin.zip)

Thanks for the reply.  Here are the logs.  Let me know if you need anything else.

**Comment by Ullmie02** [comment]
Does this happen for all your movies with spaces of only for some of them?
How are your files structured? Do you have each movie in a separate sub-folder?

**Comment by usstattik** [comment]
It's happens to all films with spaces in their name after upgrading to 10.5.5.  Earlier films with spaces that have already been scanned are fine.  If I take a film with spaces and replace the spaces with a period, the film gets scanned correctly.  It's almost as if I have a checkbox ticked somewhere that is prohibiting this.  My films are all in one directory.

**Comment by Ullmie02** [comment]
Could you try adding one movie in a separate folder like `movies/Moviename with spaces (Year)/Moviename with spaces (Year).ext`?
If this doesn't recognize the movie correctly, could you try for add a separate library on a local filesystem and not on CIFS and try if the issue persists?

**Comment by usstattik** [comment]
I added a movie to **film/film name/ film name (year)** and it failed to scan.
I added another movie with spaces to a local folder(ext4) and created a new library with it and that failed the scan as well.
Are there any log entries I should be looking for when troubleshooting this?  I appreciate your assistance.

**Comment by Ullmie02** [comment]
In the log entries you provided you can see in lines 1451-1516 a warning that "Unable to find linked item at path" and some text with a weird encoding.
I think somehow your paths break something with the encoding so the movies don't get recognized properly.

**Comment by usstattik** [comment]
I noticed that too.  The interesting thing is that the movies appear to be found during the scan (lines 1440, 1143-1146) so the path doesn't seem to be problem at that step.  It's the next step that generates "Unable to find linked item at path".

**Comment by usstattik** [comment]
Did some more testing.  Got some interesting results.

This doesn't scan.
movie name 2020 1080p ac3.mkv
movie.name 2020.180p.ac3.mkv

But this does scan.
movie.name.2020.1080p.ac3.mkv
movie name.2020 1080p ac3.mkv
movie name (2020) 1080p ac3.mkv

So the key appears to be the separator between the name and year.  As long as somethig is there(other than a space) the file can be scanned.
