### ISSUE TITLE
PhoenixAdult plugin for Jellyfin is now supported

### ISSUE THREAD

**Issue by mukalaaa** [jellyfin/jellyfin#3241]
so we all know the amazing plex plugin for adult metadata "Phoenixadult" has been recently made available for jellyfin users. 
It is amazing and it is working great for my porn library. 

Now, it took me a while to figure out how to set it up manually with jellyfin but now that I know the steps thanks to the developer of the plugin, all is working fine now. 

I believe this is a huge bonus for jellyfin and its community but i was wondering if there was a way to include this plugin in your catalog to automate the updates and make it easier for the users to download it. 

Thanks a lot for amazing work you guys are doing, cheers!

**Comment by dkanada** [comment]
Are you one of the developers for the plugin?  We have some ideas about how to solve this but no firm solution yet.

**Comment by mukalaaa** [comment]
I am not a developer but I have been using the plugin for years "testing every new version". that was when I was fully in Plex world. But now, I am more into open source apps such as jellyfin and we have been asking the developer to make the jump to jellyfin and they finally did. 

Now, I am trying to facilitate integrating this amazing plugin with jellyfin

**Comment by crobibero** [comment]
10.6 came with support for 3rd party plugin repos

**Comment by dkanada** [comment]
I'd like to also mention that we have a section in the docs to list all third party repositories so users can discover them better if you do end up creating one!
