### ISSUE TITLE
Simple issue with multiple versions show up as individual titles.

### ISSUE THREAD

**Issue by kwm1800** [jellyfin/jellyfin#3242]
**Describe the bug**
Despite it is named correctly. Some files still show up as individual titles rather than combined.

**System (please complete the following information):**
 - OS: Ubuntu Server
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Firefox Web
 - Jellyfin Version: 10.6.0 Nightly (6/2/2020)
 - Playback: N/A

**To Reproduce**
Named files such as
Star Wars; Episode 1 The Phantom Menace (1999) - 4K.mkv
Star Wars; Episode 1 The Phantom Menace (1999) - 1080p.mp4

Will be treated as individual titles. rather than single title.

**Expected behavior**
Should produce just one title with two versions, instead of 2 titles.

**Additional context**
I believe the issue is caused by having different file extensions. The ones with same extension (e.g same mkv for both versions) work without any issues. Only titles with multiple versions of different file extensions have this problem.

The solution would be make jellyfin ignore file extension altogether for handling multiple versions.

**Comment by harry71019** [comment]
Maybe check if the folder name is matching the filenames? Because I also have videos with different file extensions that work ok. (Showing 3 versions with mkv/m2ts/ts)

**Comment by harry71019** [comment]
If that's the case I would suggest you to first try to have the name of folders and files be coherent. 
(Sorry my example filename is not in english)
![image](https://user-images.githubusercontent.com/59645782/83943434-1671a380-a7ca-11ea-86e3-b0a074873e6d.png)
![image](https://user-images.githubusercontent.com/59645782/83943437-22f5fc00-a7ca-11ea-9141-47f925441ca1.png)
But as you can see here the versions show up correctly so I would urge you to try so. If you could post how your folders and files are named that would be great and maybe we could sort the problem out or find a bug. Good luck!

**Comment by kwm1800** [comment]
As I said, The folder name is written as

WALL·E (2008)

and the files are named as

WALL·E - 4K.mkv
WALL·E - 1080p.mp4

Now, The real issue is that "Group Versions" seems broken. It is alright if those files are shown as separated titles, but the problem is when I choose these two and select "Group Versions", it actually does not group them together. Instead there will be still 2 duplicated titles, now with two duplicated versions as well.

Just let you know Emby also posts the files as separated title, but at least its "Group Versions" works; it will properly combine them into a single title.

I guess this "Group Versions" is a separated bug, right?

**Comment by harry71019** [comment]
I haven't used the group versions function so I can't give you guidance on that. However, if you just want the versions function to work the folder name has to be the exact same as the filename befor the hyphen. So in your case the file name would be: 
WALL·E (2008) - 4K.mkv
WALL·E (2008) - 1080p.mkv
Or you could just change your folder name to only
WALL·E
hope that helps!

**Comment by kwm1800** [comment]
> 
> 
> I haven't used the group versions function so I can't give you guidance on that. However, if you just want the versions function to work the folder name has to be the exact same as the filename befor the hyphen. So in your case the file name would be:
> WALL·E (2008) - 4K.mkv
> WALL·E (2008) - 1080p.mkv
> Or you could just change your folder name to only
> WALL·E
> hope that helps!

Well, that's what I did for that particular title but there is no way I can apply same method on other titles. There are other instances watching the folder; any significant change will disrupt a lot of apps I've been running.

I have to confess I moved to Emby and I have zero problems regarding duplicates now. But I will still make bug report on Group Versions.

**Comment by villagra** [comment]
The only way to group movies is having the same movie name as the folder + " - [extrainfo]". That worked.
But none of these methods worked for series episodes.
