### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by woosade** [jellyfin/jellyfin#3249]
I would like to know if there is any way to install Jellyfin in cpanel, having access to SSH from the Hosting account

**Comment by ABotelho23** [comment]
afaik cPanel doesn't offer a VPS, it's just web hosting. I don't believe it would work with Jellyfin.

**Comment by Jose197n** [comment]
> afaik cPanel doesn't offer a VPS, it's just web hosting. I don't believe it would work with Jellyfin.

I have a complete server divided into vps, the fact is that I would like to be able to use one of those vps that I have installed cpanel to create an account and install Jellyfin there, perhaps using rpm and SSH. I wanted to know if it is possible to save hardware and ip consumption. If it can not posible, it would be a shame and there would be no other option but to create another vps.
