### ISSUE TITLE
Some media does not transcode on iOS 12.4.7

### ISSUE THREAD

**Issue by Spiritreader** [jellyfin/jellyfin#3263]
**Describe the bug**
Some media with an iOS 12.4.7 device is no longer transcoded.
Instead, a crossed out playback button appears and the media does not load.
No ffmpeg transcode log is created and above the struck through play icon is an infinite spinner.

I've previously commented this on #3224, but this seems like it's maybe a separate issue so I opened a new one.

![image](https://user-images.githubusercontent.com/18438899/83957306-75d1c100-a867-11ea-87d5-2c7b0f10906e.png)

**System (please complete the following information):**
- OS: iOS 12.4.7 iPad
- Browser: Apparently same as iOS version, I don't know much about apple devices, only use the ipad for streaming
- Jellyfin Version: nightly-20200607
- Playback: Remux or Transcode
- Reverse Proxy: Yes
- Base URL: None
- Networking: Remote
- Storage: Local

**To Reproduce**
1. Load a media library with incompatible media file
2. Click play for any media that requires Transcoding or Remuxing.
3. Observe struck through playback icon, no playback

**Expected behavior**
The media plays like it used to in 10.5.5

**Logs**
Unfortunately I can't plug my ipad to my PC to show the console as I don't have a device set up for debugging.
But this is what the server logs report about the stream. I've also included a transcode log from 10.5.5 where it was working.

10.6.0
[ServerConsole-Safari_new.txt](https://github.com/jellyfin/jellyfin/files/4751554/ServerConsole-Safari_new.txt)

10.5.5
[ffmpeg-transcode.txt](https://github.com/jellyfin/jellyfin/files/4742032/ffmpeg-transcode.txt)
Transcode reasons for ffmpeg: TranscodeReasons=ContainerNotSupported,VideoCodecNotSupported,AudioCodecNotSupported,ContainerBitrateExceedsLimit

**Comment by anthonylavado** [comment]
@Spiritreader There was a new nightly released, can you try that one and let us know?

**Comment by YouKnowBlom** [comment]
I can't seem to reproduce this on the latest nightly. I've tried on an iPad Pro as well as an iPad gen7 both running iOS 12.9.

If the issue still exists on the latest nightly, could you run `ffprobe -show_streams -show_format` on an uplayable file and attach the output.

**Comment by Spiritreader** [comment]
Sorry for the delay.
Still happening on nightly-20200609. 

Here's the requested ffprobe log
[ffprobe.txt](https://github.com/jellyfin/jellyfin/files/4755940/ffprobe.txt)

Thank you for looking into this!

**Comment by Spiritreader** [comment]
I have discovered another different tv show that doesn't play
[ffprobe_l.txt](https://github.com/jellyfin/jellyfin/files/4761872/ffprobe_l.txt)
[ServerConsole_l.txt](https://github.com/jellyfin/jellyfin/files/4761874/ServerConsole_l.txt)

**Comment by Spiritreader** [comment]
I have determined the pattern on which media files play and which don't.
Direct stream seems to work fine.
If I force transcoding by setting the quality to 480p 420kbps I cannot play anything.

Only direct stream works, **all** non direct-stream transcodes fail.

**Comment by m00nsl47r** [comment]
I've been having the same issue with 10.5.4 and 10.5.5, ios 13.5 on a simulator, and on and iphone 11. This happens when using both the web client in safari and the expo client (git master, running in the sim, and the app store release).

Has anyone tested this with HTTP, rather than HTTPS? I just tried without going through my nginx proxy that manages the SSL certs and it works fine, automatically detecting the right profile and transcoding properly (at least as far as i can tell). 

I think it is related to the socket path not being configured as described [here](https://jellyfin.org/docs/general/networking/nginx.html). That's just conjecture, I don't actually have access to the nginx.conf file being used (I can test that further with another nginx instance if its helpful, but it's tough to do that with self-signed certs). However, I do get the error message in #2818 which is indicative of that config issue so I think it's a good guess.

**Comment by m00nsl47r** [comment]
(Not sure if I'm supposed to edit or reply again, will reply again)

I fixed the nginx socket issue but the same thing happens anyway (on 10.5.4 and 10.5.5), so I don't think it was that. The issue occurs when going through nginx but not when connecting directly. I haven't tested connecting via https directly to jellyfin, because of issues with my local config. I'll try to do that next.

**Comment by Spiritreader** [comment]
I have **finally** found a way how to get the debug console output from a webkit browser without owning a Mac... 
~~I've started pulling my hair out getting remote debugging to work for weeks until~~ I noticed I can just use Chrome for iOS.

My findings repeated:
- DirectStream **works**
- full transcode **does not work**

Anyway, long story short: This happens when trying to transcode
```
DEBUG app is hidden
ERROR media element error: 3
DEBUG playbackmanager playback error type: mediadecodeerror
```

here's the full (sanitized) debug log. I have only removed the server address and the playback queue.
[browser-console.txt](https://github.com/jellyfin/jellyfin/files/4810695/browser-console.txt)

**Comment by YouKnowBlom** [comment]
> @m00nsl47r I think we're having different issues. My issue is unrelated to any nginx configuration because transcoding works on all versions prior to 10.6.0 and I also can't get transcodes to work without reverse-proxying. In addition to that, direct-stream works fine, even on 10.6
> 
> I have **finally** found a way how to get the **debug console output from a webkit browser** without owning a Mac... 
> ~~I've started pulling my hair out getting remote debugging to work for weeks until~~ I noticed I can just use Chrome for iOS.
> 
> My findings repeated:
> - DirectStream **works**
> - full transcode **does not work**
> 
> Anyway, long story short: This happens when trying to transcode
> ```
> DEBUG app is hidden
> ERROR media element error: 3
> DEBUG playbackmanager playback error type: mediadecodeerror
> ```
> 
> @YouKnowBlom, do you know how to interpret this error message with respect to jellyfin?
> 
> here's the **full webkit (sanitized) debug** log. I have only removed the server address and the playback queue.
> [browser-console.txt](https://github.com/jellyfin/jellyfin/files/4810695/browser-console.txt)
> 

Awesome! That's what I guessed was the issue but has nothing to back it up with since I couldn't reproduce it :p.

Optimally I'd need the master.m3u8 that is fetched on playback start. You can get it by having the debug console open while starting a video, then looking under the network tab. This file may have your token in it so feel free to remove that.

**Comment by Spiritreader** [comment]
Unfortunately I can't get the master.m3u8 on my iPad, however I can just fetch it on my desktop using the URL in the debug log.
Is this enough?

Here it is:

[master.m3u8.txt](https://github.com/jellyfin/jellyfin/files/4812526/master.m3u8.txt)

**Comment by YouKnowBlom** [comment]
That works. I can't seem to find any issue with that in particular, all the fields look correct to me.

Could we link up on riot and discuss this a bit further? https://matrix.to/#/@a_blom:matrix.org

**Comment by Spiritreader** [comment]
Of course, I messaged you. Thanks again!

**Comment by YouKnowBlom** [comment]
So far I've had 3 confirmed cases, all happening on iOS 12.4.7. I've tested with 12.2 and it works fine which leads me to believe something may changed between those versions.

**Comment by ladrua** [comment]
Confirm same issue on iOS 12.4.8

**Comment by Bloham** [comment]
I just wanted to confirm this issue on my iPhone 6 Version 12.4.5 but also on my iPad Air 2 Version 13.5.1

I described the problem also in detail in the support forum here: https://forum.jellyfin.org/t/ios-does-not-transcode/2611

If I can do something to solve the problem, I’m happy to help!

**Comment by Schroedingers-Cat** [comment]
All my iOS devices on 13.6 are affected by this (Browser and App) - playback of FLAC media fails while mp3 works fine. I also have the websockets added to my nginx proxy.
Playback of transcoded FLAC files works on macOS via Firefox and on Android with the Jellyfin app.

**Comment by nyanmisaka** [comment]
@YouKnowBlom 

We currently cannot get a certain video level from some hardware encoder such as NVENC. It depends on target video resolution and bitrate. If we specify a level but the GPU doesn't support it, the transcoding will fail.

On iOS12 if the CODECS field is inconsistent with the actual codec and profile, Safari will not try to play. However it is no that strict on iOS13. Safari will ignore this field and start to play.

I think we should drop this field `CODECS="avc1.42e00a,mp4a.40.2"` at this time as it is optional.

**`
CODECS: (Optional, but recommended) A quoted string containing a comma-separated list of formats, where each format specifies a media sample type that's present in a media segment in the playlist file. Valid format identifiers are those in the ISO file format name space defined by RFC 6381 [RFC6381].
`** _[reference](https://developer.apple.com/documentation/http_live_streaming/example_playlists_for_http_live_streaming/creating_a_master_playlist)_

**Comment by YouKnowBlom** [comment]
> 
> We currently cannot get a certain video level from some hardware encoder such as NVENC. It depends on target video resolution and bitrate. If we specify a level but the GPU doesn't support it, the transcoding will fail.
> 

Ah alright, that's annoying. Is there no reliable way to get the level of the output file?

> On iOS12 if the CODECS field is inconsistent with the actual codec and profile, Safari will not try to play. However it is no that strict on iOS13. Safari will ignore this field and start to play.
> 
> I think we should drop this field `CODECS="avc1.42e00a,mp4a.40.2"` at this time as it is optional.
>

Only issue I see with that is that both Chromecast and Shaka on web will have issues playing HLS content. I agree it may be worth it to remove it until we can be sure we have something that works though.

**Comment by nyanmisaka** [comment]
> Ah alright, that's annoying. Is there no reliable way to get the level of the output file?

There is no reliable way to determine the output level in some HWA encoders. This requires hardware capability testing to select a certain level. We should fix it in 10.6.1 hotfix first and then look for a better solution.

**Comment by ladrua** [comment]
It's working with fix from pull request https://github.com/jellyfin/jellyfin-web/pull/1659

**Comment by Schroedingers-Cat** [comment]
Any idea why this is also happening with audio files like FLAC? The linked PR seems to be about video files exclusively.

**Comment by Spiritreader** [comment]
While testing for this issues, I found that there seems to be a problem with audio files in general that is unrelated to iOS as I can't get FLAC transcoding to work on all devices and operating systems, not only iOS

**Comment by ladrua** [comment]
Not directly related, but having similar issues with the Kodi addon

**Comment by anthonylavado** [comment]
FLAC and other add ones will need separate issues please 🙂
