### ISSUE TITLE
Music quality setting not working as expected

### ISSUE THREAD

**Issue by Hirsch2k2** [jellyfin/jellyfin#3265]
**Describe the bug**
If I set the Internet quality setting (User Settings, Playback, Music Quality) to a certain bitrate it does not transcode music to this bitrate. Instead it checks if the original file bitrate is higher or lower than the selected bitrate. If Original file bitrate is lower, it streams directly. If it is higher, it transcodes but not to the selected bitrate setting but always in my case to AAC 128 kbps. Which is not much.

**System (please complete the following information):**
 - OS: [e.g. Debian, Windows]
Raspbian Buster
 - Virtualization: [e.g. Docker, KVM, LXC]
none
 - Clients: [Browser, Android, Fire Stick, etc.]
Chrome 83

 - Jellyfin Version: [e.g. 10.4.3, nightly 20191231]
10.5.5

**To Reproduce**
Set User Settings, Playback, Music quality, Internet quality to something not 128 kbps
Play high bitrate audio file with bitrate higher than selected setting
Check transcode log for transcoded bitrate

**Expected behavior**
The Music quality, Internet quality setting should be respected and audio files should be transcoded to the bitrate selected there if the selected bitrate is lower than the bitrate of the original file. If the bitrate selected is higher than the original file, no transcoding should happen.

**Comment by cairobraga** [comment]
The exact same thing is happening to me: I've set up my User Settings, Playback, Music Quality, Internet Quality to 96kbps and the transcode is still happening at AAC ~128kbps when I used my mobile internet.

My OS is Win7, my client was the official android app and my Jellyfin version is 10.6.0 stable.

**Comment by patrickkfkan** [comment]
Same here with Jellyfin 10.6.4. In fact, if you look at the logs, the ffmpeg commands used for transcoding do not have the bitrate options set (so transcoding to aac always results in 128kbps which is the ffmpeg default).

**Comment by binarydad** [comment]
In my case, I'm setting it to 128kbps and it's still streaming MP3 and FLAC at full quality.

**Comment by jfmcbrayer** [comment]
I'm seeing the same thing as most people here. I want to stream low bitrate AAC for data-saving on mobile, and I altered the Android app Gelli to request 32kbps streams. Jellyfin does transcode the requested streams - but only to 128kbps.

**Comment by iPwnWolf** [comment]
I would love to be able to manually set the quality in the player aswell just like it is possible with video playback.

**Comment by solidsnake1298** [comment]
Could not reproduce with server version 10.8.12, Android client 2.5.3, Pixel 6a (Android 14).  Selected 256Kbps for Internet Quality and was given 256Kbps AAC from a FLAC file..

`/usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M  -i file:"/media/library/Music/Prizm/All Night/PRIZM - All Night - 01 All Night.flac" -map_metadata -1 -map_chapters -1 -thread
s 0   -acodec libfdk_aac -ab 256000 -ac 2 -vn -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_n
umber 0 -hls_segment_filename "/media/ramdisk/transcodes/a4a45924deb0864ac9a3b84c71659777%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/media/ramdisk/transcodes/a4a45924deb0864
ac9a3b84c71659777.m3u8"

`
