### ISSUE TITLE
Jellyfin doesn't detect "Le cœur a ses raisons" despite correct naming and NFOs.

### ISSUE THREAD

**Issue by LeVraiRoiDHyrule** [jellyfin/jellyfin#3272]
**Describe the bug**

Jellyfin doesn't detect one of my series called "Le cœur a ses raisons". https://www.thetvdb.com/series/80741 The files are all correctly named along with a full NFO and pictures created by Tiny Media Manager. Folder structure is correct too.

That's the only serie or movies that have this issue. Everything else (more than 1000 files) are detected.

I don't think it's because of the "œ" in the name because I tried telling Tiny Media Manager to rename everything by replacing the "œ" by "oe" but it still doesn't work. Jellyfin doesn't detect the serie and doesn't add it to the library.
I don't know what's causing the issue.

I don't know what I should show you to give you more details to help. Don't hesitate to ask me to show something I didn't include in the report.

**System (please complete the following information):**
 - OS: Raspberry Pi 4 (no Docker)
 - Virtualization: No
 - Clients: Concerns all (Firefox, chrome, edge, Kodi......)
 - Browser: Concerns all
 - Jellyfin Version: 10.5.5
 - Playback: Concerns all
 - Installed Plugins: Kodi sync queue, Trakt
 - Reverse Proxy: None
 - Base URL: my public IP
 - Networking: Inside and outside the network
 - Storage: External NTFS HDD

**To Reproduce**

Download this serie, it won't be detected by Jellyfin

**Expected behavior**

Jellyfin should detect the serie and add it to the library like the rest of my 8tb drive.

**Logs**

There is no error log

**Screenshots**

Nothing to show, it just doesn't detect the serie.

**Additional context**

I don't know what I should show you to give you more details to help. Don't hesitate to ask me to show something I didn't include in the report.

**Comment by lelamamalgache** [comment]
Salut, Hello,

To help you, i downloaded only the first episode of the tv show. I don't have any problems.
<img width="105" alt="cover" src="https://user-images.githubusercontent.com/58141187/84090589-8cf0ea00-a9f2-11ea-91d3-0c7d80759ecc.png">
<img width="529" alt="folder" src="https://user-images.githubusercontent.com/58141187/84090595-8ebaad80-a9f2-11ea-8c96-f8fb7239d1b9.png">

i recommand you to add the year of the tv show on the folder like the screenshot, that will help you a lot to discover the right tv show, it's also work for movies.
If it's not work better, you should : 

1. dashboard > libraries > tvshow
2. click right on your tv show library, then manage the library
3. show advanced options
4. then tick all checkboxes, then refresh your library

**Comment by LeVraiRoiDHyrule** [comment]
Hi
Thanks a lot for your answer. Thanks for having taken the time to download an episode to help me.

The name of the serie folder already includes the year. Tiny Media Manager include it for me. Here is my folder structure for the serie:

https://imgur.com/a/auOmcpb

https://imgur.com/a/FQBWsa4

All my series are renamed according to this scheme, I never had any problem.

I tried editing the advanced settings and tick all checkboxes, but the serie is still not detected. I can't figure out why it doesn't work for this serie only.

**Comment by lelamamalgache** [comment]
it's strange the folder name is correct and you add the year at the end.
i put my tv show library settings to compare with our, maybe you will find something which could be help.
<img width="506" alt="pic1" src="https://user-images.githubusercontent.com/58141187/84128137-75405280-aa40-11ea-965d-13f7491cc1f4.png">
<img width="499" alt="pic2" src="https://user-images.githubusercontent.com/58141187/84128138-75d8e900-aa40-11ea-82dd-c2d79a574b12.png">
<img width="489" alt="pic3" src="https://user-images.githubusercontent.com/58141187/84128127-73768f00-aa40-11ea-830f-347c24818b25.png">
<img width="486" alt="pic4" src="https://user-images.githubusercontent.com/58141187/84128128-740f2580-aa40-11ea-9a7d-7368c34f7777.png">
<img width="482" alt="pic5" src="https://user-images.githubusercontent.com/58141187/84128129-740f2580-aa40-11ea-8e0d-a945f4745dbf.png">
<img width="503" alt="pic6" src="https://user-images.githubusercontent.com/58141187/84128131-74a7bc00-aa40-11ea-8bd0-a8d0c7b57d32.png">
<img width="510" alt="pic7" src="https://user-images.githubusercontent.com/58141187/84128289-aae53b80-aa40-11ea-8fef-c557064026d6.png">

**Comment by LeVraiRoiDHyrule** [comment]
Just tried isolating the serie in a new folder, and creating a new library just for this serie, it still doesn't work. I checked exactly the same checkboxes as you.

**Comment by lelamamalgache** [comment]
could you also check if the order each service like thetvdb, themoviedb, because you can up and down for priority.
you can also try to rename your path like mine, just for the first episode
Le cœur a ses raisons (2005)\S1\01x01.avi
and at the end you could set manually the tv show by click right on your tv show, then click on identify

**Comment by LeVraiRoiDHyrule** [comment]
Ok, I just moved the serie from the internal SD card of the pi (where it was originally stored) to the external HDD I also use. And now it's detected. I don't understand what's the different, as both folders are added to the library exactly the same way.

I am no expert but I think there is a bug hiding somewhere behind that.
