### ISSUE TITLE
MusicBrainz not available as an Image Fetcher

### ISSUE THREAD

**Issue by just-an-alt** [jellyfin/jellyfin#3283]
**Describe the bug**
I noticed that despite some of my albums having "MusicBrainz Album" links, no cover art was downloaded. After investigating the issue, I found that "MusicBrainz" is not available as an Album image fetcher. I assume this is the cause of my issue.

**System (please complete the following information):**
 - OS: Armbian
 - Virtualization: Linuxserver.io's docker image
 - Clients: Firefox 77
 - Jellyfin Version: 10.5.5

**To Reproduce**
1. Go to Libraries, and then select "Manage library" on a music library.
2. Enable "Show advanced settings"
3. Scroll down to "MusicAlbum Image Fetchers"
4. Be suprised by the fact that MusicBrainz is not listed as an available fetcher

**Expected behavior**
MusicBrainz should be available as an Image fetcher.

**Screenshots**
Album without cover art, but with a MusicBrainz link:
![](https://i.imgur.com/cxMvvCI.png)

The MusicBrainz link (with a cover!):
![](https://i.imgur.com/Y7gdqds.png)

Image Fetcher settings:
![](https://i.imgur.com/4srwFdZ.png)

MusicBrainz plugin settings:
![](https://i.imgur.com/222Rw52.png)

**Comment by Darkwolf1515** [comment]
I too have enabled it in the plugins, I have zero idea why it wont show up, it filled in whatever gaps for songs without embedded art in plex, it was a life saver, please fix it.

**Comment by Darkwolf1515** [comment]
So it is meant to work this way from what I spoke to one of the devs about, have no idea why its broken.

**Comment by swever826** [comment]
It seems to still be broken. AudioDB doesn't have some album covers that MusicBrainz has. It would be cool to add it to also fetch images.

I see this issue is 5 years old though 😭

**Comment by Shadowghost** [comment]
Musicbrainz itself does not supply images, they are coming from CoverArtArchive for which we have a plugin.

**Comment by swever826** [comment]
OK I installed that plugin you mentioned and now I have the missing album images 🥳 thanks!!
