### ISSUE TITLE
Latest Emby Android breaks with jellyfin

### ISSUE THREAD

**Issue by BobOkisama** [jellyfin/jellyfin#329]
The latest Emby android app 3.0.28 no longer works with jellyfin.

**Comment by sparky8251** [comment]
Judging by the convos last night in dev, this is not just an API version bump to 3.5.3. They did in fact change something.

We either need to release our own android app or reverse engineer fixes for the server.

**Comment by BobOkisama** [comment]
Yeah, app now looks at version at the minimum and prompts you to update the server and will not let you any further. 3.0.27 does still work if you roll back.

On a personal level, I would prefer we roll our own app, on principal alone if not anything else, but then again I do not do anything more than script so I got no money to put where my mouth is.

**Comment by sparky8251** [comment]
Well... I copied the `3.5.3` Emby `manifest.json` to JF and bumped up to that version number. Still failed to connect.

I then tried the 3.5.3 Emby manifest with JF set to version `3.6.0.0` and `3.6.0.81` with no changes.

I have not tried:

* Running Emby `3.5.3` and connecting with the new Android app
* Capturing `3.5.3` server traffic and seeing if it sends files other than `manifest.json` and `/web/strings/en-US.json` (which appears to be a lang file for the apps UI)
* Trying with any Emby server `3.6.0.*` if its required for the Android app (can't imagine it is)

**Comment by BobOkisama** [comment]
So, as everyone thought they have quite literally just forced their app to not work with jellyfin. I cannot say I am surprised honestly, but hey at least that gives us a future to look forward to where we do not use their insanely UGLY app ;P Maybe I should start learning how to do some mobile code.

**Comment by sparky8251** [comment]
Sure seems petty if true.

**Comment by BobOkisama** [comment]
Not to make excuses for them... but they are a closed source business now so I mean letting a free version use their product would probably be a bad idea fiscally speaking. It seems petty, but they likely think of this product as theirs now so really this is not surprising in the least.

**Comment by cvium** [comment]
```
            if ((result || '').toLowerCase().indexOf(String.fromCharCode(106) + String.fromCharCode(101) + String.fromCharCode(108) + String.fromCharCode(108)) !== -1) {
                return Promise.reject();
            }
```

**Comment by joshuaboniface** [comment]
This is a "won't fix", we're working on the Cordova app instead, and aren't going to waste time in a cat-and-mouse game with upstream. This just moves up the timeline.

**Comment by hawken93** [comment]
3.0.27 available on apkmirror does work, for reference :)
