### ISSUE TITLE
Organize all build systems and homogenize all scripts and instructions

### ISSUE THREAD

**Issue by EraYaN** [jellyfin/jellyfin#331]
We should really have all build scripts and required files for packages in one folder.

I propose something like

`deployment/build.common.sh` The platform independent script (functions).
`deployment/build_all.sh` The build every target script (cross compiling).
`deployment/<platform>/README.md` The instructions.
`deployment/<platform>/build.sh` The local build script, sources common script.
`deployment/<platform>/package.sh` The local package script. Optional.
`deployment/<platform>/sign.sh` The local signing script. Optional

With a README.md in every platform folder having the full instructions for beginning, AND for updating a repo and submodules. (For returning users)

EDIT: Amended files. No use of make.

**Comment by joshuaboniface** [comment]
A couple methods, specifically Debian, need their build configs in a particular way (I.e. how they are now). I'd rather keep everything separate, and wrote a unified build script that just makes every build easy to run. I've been working on this and hope to have something ready very soon!

**Comment by EraYaN** [comment]
I think my main issue is it cluttering the main source tree. Now it's just unraid/debian but add all linux flavours and all Dockerfiles and you get a mess.

I was busy putting it in proper subfolders and writing one script for every platform. (With the actual build/clean as a function)

`build.sh`
and 
`package.sh`

So your "build-all" super-script could loop over every folder and build every artifact.

**Comment by joshuaboniface** [comment]
Ooh ok, I like that sort of setup - awaiting the PR!

**Comment by joshuaboniface** [comment]
That it does!
