### ISSUE TITLE
Central hosted service for client login and status

### ISSUE THREAD

**Issue by Fmstrat** [jellyfin/jellyfin#3314]
Hi, I think I'm in the right place (vs the feature site) because I'm willing to contribute this. In my day job I build APIs that support millions of secure medical records between systems (i.e. this is my wheelhouse), and I think a hosted API service to ease logins that could be expanded in the future would be a good addition to Jellyfin.

Work seems to be progressing since last I checked on the new data model (https://github.com/jellyfin/jellyfin/pull/2293), which is great news for any central-service based features like this one. So, the idea:

- The Jellyfin team hosts an API service in the cloud at `api.jellyfin.org`
  - *Note: I would be happy to provide this infrastructure in AWS, Azure, or my personal favorite, Linode, initially*
- An endpoint of `/api/v1/login/get_code` would allow a client, such as the Roku client with it's terrible keyboard to request a 5 character `code`.
- The user would then go to their Jellyfin server's web portal and a specific page that asks for the `code`.
- After typing it in, the web portal directs to an API endpoint of `/api/v1/login/check_code` It would also send a login `token` for the current user and a `uri` for the server back to the central service
- During this time, every few seconds the client is making a request to `api/v1/login/get_response`, which, once complete, would return the `uri` and `token` to use moving forward

This would be completely optional in the UI, allowing a user to manually specify information or use a code.

There may be a way to do E2E encryption on the `token` and `uri` if there were concerns there from users, however this is a pretty standard practice in many apps people use. Personally I'm a security nut and this wouldn't bother me since Jellyfin would be a trusted entity (running their software).

Lastly, this could be an optional step towards future central storage. For instance, adopting the Mozilla model, we could add an accounts system that would allow for media watched status and rating storage fully encrypted in the cloud. This would mean a secure system where installing a new server could restore all watched status for users, or synchronization of status between multiple servers (https://github.com/jellyfin/jellyfin/issues/481).

If there is interest from the team, I'd be happy to build the API layer.

**Comment by Fmstrat** [comment]
Note: As the API service would be open source, user's could also host their own central service if they chose (but would need to manually alter/compile apps as there is no easy way to say, change it in an Android/iOS/Roku client).

**Comment by crobibero** [comment]
Thank you for the suggestion, but we stand firm on not having a centralized login system.

There is currently an open PR for code-based login (https://github.com/jellyfin/jellyfin/pull/2888), so logging in on applications without full keyboards should be simpler in the future.

**Comment by joshuaboniface** [comment]
> Thank you for the suggestion, but we stand firm on not having a centralized login system.

To put it another way, every instance of Jellyfin in every configuration should, at least after populating the library metadata and installing plugins, not require any sort of Internet access to function, and be able to stand entirely on its own in an isolated network. Any service that breaks this assumption will not be provided.

**Comment by sparky8251** [comment]
This isn't to say you cant do this (we even have a pluggable authentication provider system you can utilize for this), just that we won't make it a core project.

If you make it we are open to putting links to it in our docs and such so it can gain visibility.

**Comment by Fmstrat** [comment]
Thanks for the feedback, it makes sense if this is a policy decision. I'm not sure setting it up as a plug-able interface would work since it's something that would need to be integrated into TV apps for it to truly be useful.

As for the policy specifically, I get that this is probably a differentiating position for Jellyfin, however it is a shame since it does limit many integration features like the aforementioned server sync (that could be part of an "optional" core service whether that service is self-hosted or using the one provided by Jellyfin (think of the Mozilla sync model)). In any event, thanks, and I'll close this out.
