### ISSUE TITLE
<host>/web/ should redirect to <host>/web/index.html

### ISSUE THREAD

**Issue by Thalhammer** [jellyfin/jellyfin#3362]
**Describe the bug**
If you miss or somehow drop the index.html from the url it should redirect you to the index instead of giving an error.

**System (please complete the following information):**
 - OS: Ubuntu 18.04
 - Virtualization: LXC (Proxmox VE 6.2)
 - Clients: Browser
 - Browser: Chrome 83
 - Jellyfin Version: 10.5.5
 - Playback: None
 - Installed Plugins:AudioDB;Fanart;IPTV;MusicBrainz;Playback Reporting;Reports
 - Reverse Proxy: none
 - Base URL: none
 - Networking: Direct via Linux Bridge
 - Storage: NFS to VM on the same VM Host (FreeNAS)

**To Reproduce**
1. Enter <host>/web/ into browser
2. Admire the beautifull error message

**Expected behavior**
Redirect to /web/index.html instead of giving an 400 error.

**Comment by Artiume** [comment]
https://github.com/jellyfin/jellyfin-web/issues/559

The issue is noted here.
