### ISSUE TITLE
Jellyfin as URL Base does not resolve, emby does

### ISSUE THREAD

**Issue by RlndVt** [jellyfin/jellyfin#337]
To set up a reverse proxy you need set the URL base to 'emby'. This is great for backwards compatibility with emby, but being able to use 'jellyfin' as URL base would be preferable.

Currently using jellyfin as base url gives the following error:

'Unable to find the specified file.'

**Comment by skug67** [comment]
I suspect the problem/difference lies in whether you give emby/jellyfin a dedicated DNI (virtual host) or whether you use a catchall hostname and run your proxy based on suburl (which I do, and which it sounds like RlndVt does as well.

**Comment by Cerothen** [comment]
the "/emby" is hard coded into the software somewhere (there was an old discussion about it on the Emby forums), but it is optional. Either /web/index.html or /emby/web/index.html are valid. really the base url should be configurable rather than just updating the hardcode to jellyfin.

**Comment by JustAMan** [comment]
That is what I intended to do :)

**Comment by RlndVt** [comment]
Sorry for the delay, didn't expect such fast responses!

I don't have much more to add, you guys guessed/figured out what I meant and also how I would like it solved (configurably)! 

Happy New Year and good luck with this project in 2019!

**Comment by anthonylavado** [comment]
Closing in favour of #691 as a master tracking issue.
