### ISSUE TITLE
10.6.0 tv show metadata, wrong title

### ISSUE THREAD

**Issue by lelamamalgache** [jellyfin/jellyfin#3374]
Hello,

**Describe the bug**
i have a bug on the title of one tvshow which name is "the-bureau"
https://thetvdb.com/series/the-bureau
all metadata are correct

**System (please complete the following information):**
 - Virtualization: docker
 - Clients: browser
 - Jellyfin Version: 10.6.0
 - Reverse Proxy: linuxserver-letsencrypt

**To Reproduce**

1. Dashboard >general > language > french
2. click right on my tv show > identify > tvdb : 294564
3. the name of the tv show is named "Bureau Raampoort" in jellyfin

**Expected behavior**
the name of the tv show should be "Le bureau des légendes"

I have checked the other titles for foreign language, i can't find "Bureau Raampoort"
https://thetvdb.com/series/the-bureau
i don't know where did it get this wrong title ?

**Screenshots**

![image](https://user-images.githubusercontent.com/58141187/85074491-e90af980-b1bc-11ea-9c38-4a82b6972628.png)

![image](https://user-images.githubusercontent.com/58141187/85074571-10fa5d00-b1bd-11ea-90b9-369f9dba0dd3.png)

![image](https://user-images.githubusercontent.com/58141187/85074668-3be4b100-b1bd-11ea-95a8-fe05256d514f.png)

**Comment by crobibero** [comment]
https://github.com/jellyfin/jellyfin/issues/2441
