### ISSUE TITLE
[bug] 10.6.0 Library scan empties library if folder is .dotfolder

### ISSUE THREAD

**Issue by janvs0** [jellyfin/jellyfin#3375]
After upgrading from 10.5.5-amd64 to 10.6.0 (20200618 and 19) on Ubuntu 20.04 using a Photo library on a .dotfolder all library items get deleted upon (re)scanning the library.
Re-adding the library does not bring them back (rescan takes < 1s.).

**Comment by crobibero** [comment]
Does this still happen with the latest unstable build?

**Comment by dkanada** [comment]
This should be resolved on the latest unstable branch (maybe not nightly) but please let us know if it's still an issue and we can keep looking.

**Comment by janvs0** [comment]
Hi @crobibero @dkanada , thank you for your efforts. I've just tested this on 20200628.3-unstable and it still behaves the same (deletes the library's contents).

**Comment by Bond-009** [comment]
This was intentionally added, but will be configurable in the future

**Comment by janvs0** [comment]
Thanks @Bond-009. As you say, something along the lines of `<LibraryScanHidden>true|false</LibraryScanHidden>` in system.xml would be nice to have. :+1:

**Comment by joshuaboniface** [comment]
Was this solved in a satisfactory way?

**Comment by janvs0** [comment]
I understood the intended fix for this is to read ignore globs from file rather than having an on/off toggle (which the previous PR's accomplished). While I still personally use these as a workaround I'm also working on a new PR to be able to read globs from file.
Thanks @joshuaboniface !
