### ISSUE TITLE
Mark series or season as watched or unwatched functionality

### ISSUE THREAD

**Issue by reynn** [jellyfin/jellyfin#3389]
**Describe the bug**

Noticed the latest nightly has a bug that causes the follow to behavior. I have a TV series that is completely watched, I attempted to mark the show as unwatched to start a rewatch of it. Only the very first episode was actually marked as unwatched the rest remained the same. Same goes the other way of all unwatched to all watched.

**System (please complete the following information):**
 - OS: Ubuntu 20.04
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Firefox 77
 - Jellyfin Version: nightly 20200619
 - Reverse Proxy: Traefik
 - Networking: Host
 - Storage: local

**To Reproduce**

1. Go to any 'TV Series' that is marked as watched
2. Click on 'watched'
4. Refresh page to see it only marked the first episode as watched.

**Expected behavior**

All episodes are marked either watched/unwatched

**Comment by crobibero** [comment]
I experience this if I refresh while the request is still processing.
Ideally, the change would keep processing even after the request is cancelled.
