### ISSUE TITLE
user library access  issue

### ISSUE THREAD

**Issue by grafixeyehero** [jellyfin/jellyfin#339]
user library access  setting is not respond on windows platform
![untitled-1](https://user-images.githubusercontent.com/32230989/50561138-e8587c00-0d18-11e9-8133-98e83cb9418f.jpg)

**Comment by nvllsvm** [comment]
Thanks for filing an issue! Please take a screenshot of the issue and provide more context.

**Comment by grafixeyehero** [comment]
on library acces does not show the media folder

**Comment by joshuaboniface** [comment]
Turns out not to be a frontend issue - tracking in #352 for consistency.
