### ISSUE TITLE
10.6.0 IgnorePatterns.cs @eaDir

### ISSUE THREAD

**Issue by lelamamalgache** [jellyfin/jellyfin#3391]
**Describe the bug**
Hello, i have an @eaDir file on my synology share for tv show, it should be not shown in jellyfin
https://github.com/jellyfin/jellyfin/blob/9af6eda0b495649e3a77694b2bb30abad1a26484/Emby.Server.Implementations/Library/IgnorePatterns.cs

**System (please complete the following information):**
 - Virtualization: docker
 - Clients: browser
 - Browser: chrome
 - Jellyfin Version: linuxserver-jellyfin:nightly
 - Reverse Proxy: linuxserver-letsencrypt
 - Storage: btrfs synology

**Expected behavior**
do not show or ignore the @eaDir

**Screenshots**
![image](https://user-images.githubusercontent.com/58141187/85202977-b66f1700-b30a-11ea-9314-2118f73649cf.png)

![image](https://user-images.githubusercontent.com/58141187/85202998-dbfc2080-b30a-11ea-9e69-5b4ef52248f0.png)

**Comment by anthonylavado** [comment]
Did this happen in 10.5.5 as well, or only in 10.6.0?

**Comment by lelamamalgache** [comment]
not happen on 10.5.5, only on 10.6.0
