### ISSUE TITLE
Server crashes when playing on Android TV

### ISSUE THREAD

**Issue by M0ssTee** [jellyfin/jellyfin#3396]
**Describe the bug**
I am able to connect to the server, sign in, and navigate to the show I want to watch on an Android TV.  When I select play, the server crashes and the Android TV looses connection of course.  Playback works fine on the Windows 10 machine the server is installed on.

**System (please complete the following information):**
 - OS: Windows 10
 - Virtualization: n/a
 - Clients: AndroidTV
 - Browser: Firefox 77.0.1
 - Jellyfin Version: 10.5.5
 - Playback: n/a
 - Installed Plugins: AudioDB, AutoOrganize, Email Notifications, MusicBrainz, Open Subtitles, TMDB box sets
 - Reverse Proxy: none
 - Base URL: none
 - Networking: ??
 - Storage: local

**To Reproduce**

1. Start server on Windows 10.
2. Open Jellyfin app on AndroidTV.
3. Connect to local server using IP address and port number.
4. Sign in to Jellyfin account.
5. Select a show and press play to begin playback.

**Expected behavior**
Show will begin playing on Android TV.

**Logs**
[logs](https://pastebin.com/acvqRBZ9)

**Additional context**
May be unrelated but I am connecting using a new router.

**Comment by BaronGreenback** [comment]
Did you restart the server after the crash?

I can see this error in the log - which points to the andriod app doing something, then the logs of the server restarting.

[2020-06-20 20:12:02.684 -04:00] [ERR] [54] App: AcceptWebSocketAsync error
System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
 ---> Microsoft.AspNetCore.Connections.ConnectionResetException: An existing connection was forcibly closed by the remote host.

**Comment by M0ssTee** [comment]
Yes; after having trouble with playback, I right clicked on icon in the taskbar and noticed that the Stop Jellyfin was greyed out and Start Jellyfin was an option, so I started it back up again.
