### ISSUE TITLE
Unable to access web ui on latest nightly

### ISSUE THREAD

**Issue by Influence365** [jellyfin/jellyfin#3397]
**Describe the bug**
when trying to access the web ui thought serverip:8096 it just shows a 403 forbidden page

**System (please complete the following information):**
 - OS: windows
 - Virtualization: Docker
 - Clients: chrome(win10), ipadOS(jellyfin app and safari), android(chrome)
 - Browser: Chrome 83, latest IOS app
 - Jellyfin Version: nightly 
 - Reverse Proxy: none
 - Networking: Bridge
 - Storage: local

**To Reproduce**
1. Update to latest nightly
2. Go to serverip:8096
3. See forbidden page

**Expected behavior**
Access web UI with logon screen

**Logs**
Chrome Dev tools console:
Failed to load resource: the server responded with a status of 403 (Forbidden)
:8096/favicon.ico:1 Failed to load resource: the server responded with a status of 403 (Forbidden)
index.html#!/home.html:1 Failed to load resource: the server responded with a status of 403 (Forbidden)

-Docker - no relevant logs

**Screenshots**
![2020-06-21-forbidden](https://user-images.githubusercontent.com/18101008/85221812-deb05180-b3ae-11ea-8776-030d573a0209.jpg)

**Additional Info**
This was working in nightly-20200620.
I am accessing on local network, and have no devices blacklisted/whitelisted

**Comment by crobibero** [comment]
The only place in server that returns `Forbidden` without logging anything is when validating the request ip. Can you look in your `system.xml` and see if you have a field for `EnableRemoteAccess`? In my unstable server I have `<EnableRemoteAccess>true</EnableRemoteAccess>`.

**Comment by Influence365** [comment]
I was accessing it on the local network, and had enable remote connections disabled. 
Enabling remote connections fixes the issue.
