### ISSUE TITLE
Jellyfin Server Restart Times

### ISSUE THREAD

**Issue by Protektor-Desura** [jellyfin/jellyfin#3403]
I will say the restart times on the Jellyfin server are less than ideal. It generally takes about 10-20 minutes for me to restart my Jellyfin server. Yes I know that I probably have way more space and items than most. I have 30+TB of space and I have 4301 movies, and 1655 TV Series with 50236 episodes. Almost everything is in HEVC/AAC/MKV format.

It would be nice if the load time could be reduced somehow.

**Comment by whalehub** [comment]
@Protektor-Desura Are you storing Jellyfin's application data on an SSD or a spinning disk? My library size is about the same as yours and it takes less than a minute to restart Jellyfin for me.

**Comment by Protektor-Desura** [comment]
I am currently using a spinning disk. I want to move to an SSD eventually but haven't yet.

**Comment by Bond-009** [comment]
Is this still an issue in the latest alpha release?
