### ISSUE TITLE
10.6.0 - Library scans yet is missing from Home and Metadata Manager

### ISSUE THREAD

**Issue by telans** [jellyfin/jellyfin#3406]
**Describe the bug**
Building jellyfin master via VS Code results in a server that scans media and searches metadata without issue - yet the library remains invisible in every other location aside for the "Libraries" section of the Dashboard.

Despite this, backdrops from the added shows are displayed on the home screen - even with Metadata Manager not being aware of any shows/libraries.

I do not believe this is an issue with running jellyfin through VS Code, as checking out the 10.5.5 branch for both jellyfin and jellyfin-web results in a working server with correct library addition when run through the same steps as shown below.

Test media is using the same folder layout as with a working 10.5.5 server.

**System (please complete the following information):**
 - OS: Gentoo
 - Virtualization: N/A
 - Clients: Browser (jellyfin-web git)
 - Browser: Firefox 77.0.1
 - Jellyfin Version: c334903 debug
 - Dotnet SDK Version: 3.1.301
 - Playback: N/A
 - Installed Plugins: N/A
 - Reverse Proxy: N/A
 - Base URL: N/A
 - Networking: localhost
 - Storage: Local

**To Reproduce**
1. Set up a working jellyfin VS Code workspace.
2. Ensure all user cache/config directories are clean from jellyfin remenants.
3. Press F5 to build the project.
4. Set up server with default settings (not that changing the settings makes a difference).
5. Add a media library.
7. Once completed, navigate to the home page or metadata manager.
8. Notice library is not available, yet backdrop from added shows are shown.

**Expected behavior**
Media libraries are available after addition.

**Logs**
Debug log after initial server setup:
https://gist.githubusercontent.com/telans/444f44efa67b0ead44d0643861167a64/raw/7c87638e35ee50d3253d6b42c39f166573f26595/log_20200622.log

**Screenshots**
![Screenshot from 2020-06-22 13-06-24](https://user-images.githubusercontent.com/45819748/85239822-c3664480-b489-11ea-9a4c-b5c7a870468c.png)
![Screenshot from 2020-06-22 13-07-47](https://user-images.githubusercontent.com/45819748/85239824-c4977180-b489-11ea-9fe0-c4e24c6265e2.png)
![Screenshot from 2020-06-22 13-07-58](https://user-images.githubusercontent.com/45819748/85239825-c5300800-b489-11ea-9629-a714bb036bd1.png)
![Screenshot from 2020-06-22 13-08-10](https://user-images.githubusercontent.com/45819748/85239826-c5c89e80-b489-11ea-81b6-9da670097ea7.png)

**Comment by dmitrylyzo** [comment]
@telans Could you look response of `/Users/{UserId}/Views` endpoint (at Network tab in browser DevTools)?

**Comment by telans** [comment]
@dmitrylyzo 
```
HTTP/1.1 200 OK
Date: Tue, 23 Jun 2020 09:47:38 GMT
Content-Type: application/json; charset=utf-8
Server: Microsoft-NetCore/2.0, UPnP/1.0 DLNADOC/1.50
Transfer-Encoding: chunked
Content-Encoding: gzip
Expires: 0
Vary: Accept-Encoding
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Accept, Accept-Language, Authorization, Cache-Control, Content-Disposition, Content-Encoding, Content-Language, Content-Length, Content-MD5, Content-Range, Content-Type, Cookie, Date, Host, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Origin, OriginToken, Pragma, Range, Slug, Transfer-Encoding, Want-Digest, X-MediaBrowser-Token, X-Emby-Authorization
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, PATCH, OPTIONS
Access-Control-Allow-Origin: localhost:8096
```

**Comment by dmitrylyzo** [comment]
I meant `Preview`/`Response`.
Should be something like this
```js
{Items: [,…], TotalRecordCount: 10, StartIndex: 0}
Items: [,…]
0: {Name: "Музыка", ServerId: "2ef384e0375541169cffc85ddb94bcea", Id: "4f0f2b090066ebab07e7c41b7e565b11",…}
1: {Name: "Музыкальные видео", ServerId: "2ef384e0375541169cffc85ddb94bcea",…}
2: {Name: "ТВ-передачи", ServerId: "2ef384e0375541169cffc85ddb94bcea",…}
3: {Name: "Фильмы", ServerId: "2ef384e0375541169cffc85ddb94bcea", Id: "b853ad1780b36e82af77f6d2445b7c22",…}
4: {Name: "Фотографии", ServerId: "2ef384e0375541169cffc85ddb94bcea",…}
5: {Name: "Playlists", ServerId: "2ef384e0375541169cffc85ddb94bcea",…}
6: {Name: "Фильмы2", ServerId: "2ef384e0375541169cffc85ddb94bcea", Id: "8e820d2ccda820884c92b70831ddac85",…}
7: {Name: "Эфир", ServerId: "2ef384e0375541169cffc85ddb94bcea", Id: "6763d5f623678cbe5e94bb0bbbed76c8",…}
8: {Name: "Коллекции", ServerId: "2ef384e0375541169cffc85ddb94bcea",…}
9: {Name: "Музыка1", ServerId: "2ef384e0375541169cffc85ddb94bcea", Id: "d12bb05755da2928e82596ffa5147809",…}
TotalRecordCount: 10
StartIndex: 0
```

**Comment by telans** [comment]
Ah righto:
`{"Items":[],"TotalRecordCount":0,"StartIndex":0}`

**Comment by cvium** [comment]
@telans How are you adding the library? During the wizard or after? Using default values?

**Comment by telans** [comment]
Adding during or after installing with default or changed settings never changes the outcome

**Comment by cvium** [comment]
I am using the latest commit from jf master and jf-web master, and I can't reproduce the issue.

**Comment by telans** [comment]
Strange, I just reproduced it. Would supplying the db help?

**Comment by dkanada** [comment]
@barronpm maybe this is related to the user database migration?

**Comment by cvium** [comment]
@telans Maybe 🙂

**Comment by telans** [comment]
[jellyfin-data.tar.gz.zip](https://github.com/jellyfin/jellyfin/files/4819259/jellyfin-data.tar.gz.zip)

Just strip the zip should anyone want to take a gander

**Comment by barolo** [comment]
I have the same issue and I'm also on Gentoo

**Comment by dkanada** [comment]
What do your user settings look like? Maybe a dump of that JSON object would shed some light on the issue. Another cause might be the library access for that user on the dashboard.

**Comment by cvium** [comment]
Looks like your library.db is missing the collections folder `/home/telans/.local/share/jellyfin/root/default/TV Shows`.

I don't know why that row isn't created when you add a library folder. Can you try again and watch out for errors in the console and network tab?

**Comment by telans** [comment]
There are definitely no errors on the web side within network or console. When running jellyfin I'm noticing `Exception thrown: 'System.IO.FileNotFoundException' in System.Private.CoreLib.dll` a few times within the dotnet debug console. Not sure what that's referring to though.

Dotnet debug log:https://gist.githubusercontent.com/telans/384b282b0b3d1ac1fc552f3dc91e3194/raw/0a984dbe4620193621fbe5a8e948fb7b784a97ff/jellyfin-dotnet-debug.log

Jellyfin debug log: https://gist.githubusercontent.com/telans/b6cb28ba322c5ddb8aba9317338da4ab/raw/17c7cc88ef8e4960144caf19f7d0998a58f3d92b/log_20200624.log

The only errors I'm seeing within jellyfin logs is the update check and DLNA messages.

[jellyfin-data.tar.gz.zip](https://github.com/jellyfin/jellyfin/files/4822029/jellyfin-data.tar.gz.zip)
(still no library.db within the root/default folder)

**Comment by telans** [comment]
@dkana regarding user library access, unchecking "Enable access to all libraries" doesn't give the option to enable access to the library

![Screenshot from 2020-06-24 09-30-48](https://user-images.githubusercontent.com/45819748/85466096-a8b4dc80-b5fd-11ea-856e-372973ad4530.png)

**Comment by barronpm** [comment]
> 
> 
> @barronpm maybe this is related to the user database migration?

I took a look at the users table, everything looked good to me

**Comment by cvium** [comment]
@telans Have you tried starting a new library scan (after setting up the server)?

**Comment by telans** [comment]
Scans complete instantly and everything looks good within the logs apart from `Error updating user's last activity date` which is already part of a different issue

[log_20200624.log](https://github.com/jellyfin/jellyfin/files/4824130/log_20200624.log)

I don't think there's anything I can do to test aside from bisecting? (Bit of an issue with not being able to complete the wizard for half of the commits)

**Comment by cvium** [comment]
If I do a scan with your DB it fails to find the files of course, but it adds the collection folder to the library.db.

**Comment by telans** [comment]
Well that's discouraging. Seeing as it does work for me with 10.5.5, I'll bisect and see where it ends up.

**Comment by telans** [comment]
> I'll bisect and see where it ends up

That didn't get anywhere, kept running into issue where jellyfin was broken on master, so I couldn't log in etc.

Matrix response so everything's in one place:

![Screenshot from 2020-06-25 17-07-53](https://user-images.githubusercontent.com/45819748/85657881-b1dda080-b706-11ea-8de6-6413e2e40e7d.png)

**Comment by dkanada** [comment]
It seems to be a server issue, so you could run the same web client and simply bisect the backend if you still wanted to give it a try.

**Comment by cvium** [comment]
@telans Can you try setting the jellyfin launch CLI argument `--datadir` to something else?

**Comment by telans** [comment]
I thought that would cause errors with mismatching pull requests or something but apparently not

Offending commit: f144acdc9614bed64d7f8842356293a94a3b754a
Confirmed by reverted on top of master

**Comment by cvium** [comment]
No, I see what the issue is now.

Your datadir is in `.local`, which is ignored by this https://github.com/jellyfin/jellyfin/commit/f144acdc9614bed64d7f8842356293a94a3b754a#diff-82b49921e083ed1196848dc2e74c80fbR45-R46. We should only be ignoring hidden _files_, not directories.

**Comment by dmitrylyzo** [comment]
> We should only be ignoring hidden _files_, not directories.

What if some hidden (service, OS specific) subfolder in the library will contain media files (not hidden)?
They should not be scanned.
Maybe we just shouldn't filter `datadir` and other jellyfin folders?

**Comment by cvium** [comment]
> Maybe we just shouldn't filter `datadir` and other jellyfin folders?

Yes, that would be ideal. Not sure how feasible it is in spaghetti land though.

**Comment by rigtorp** [comment]
Ugh, I don't understand why datadir is using this filter. Sorry about this regression, @cvium fix looks fine.
