### ISSUE TITLE
10.6.0 tasks clean logs broken

### ISSUE THREAD

**Issue by lelamamalgache** [jellyfin/jellyfin#3410]
**Describe the bug**
Hello, i clicked on those 3 tasks at 10:24 22/06/2020
![image](https://user-images.githubusercontent.com/58141187/85265331-64e19c00-b472-11ea-83e9-7ba466253cbc.png)
logs are still present
![image](https://user-images.githubusercontent.com/58141187/85265529-b25e0900-b472-11ea-9b55-600ff9022e15.png)

**System (please complete the following information):**
 - Virtualization: docker
 - Clients: browser
 - Browser: chrome
 - Jellyfin Version: linuxserver-jellyfin:nightly
 - Reverse Proxy: linuxserver-letsencrypt
 - Storage: btrfs synology

**Logs**
[Log_2206.txt](https://github.com/jellyfin/jellyfin/files/4812117/Log_2206.txt)

**Comment by Bond-009** [comment]
The `DeleteLogFileTask` task only deletes the ffmpeg logs older than the configured log retention days (which is 3 by default)
