### ISSUE TITLE
10.6.0 unable to detect files for a new tv show

### ISSUE THREAD

**Issue by lelamamalgache** [jellyfin/jellyfin#3413]
**Describe the bug**
Hello, i have a new tv show named "Heirs of the Night (2019)", jellyfin detects the new tv show, but it can't detect files inside to fill episodes.

- I have only this tv show which bug
- i use sonarr to normalize my media
- i run a clean log and run a manual scan (detect new files or modifications) to the tv show library which do not fix my issue with this tv show

**System (please complete the following information):**
 - Virtualization: docker
 - Clients: Browser
 - Browser: Chrome
 - Jellyfin Version: linuxserver-jellyfin:nightly
 - Installed Plugins: AudioDB, MusicBrainz, OMDb, TheTVDB
 - Reverse Proxy: linuxserver-letsencrypt
 - Storage: btrfs synology

**Logs**
[Log_tvshow_scan.txt](https://github.com/jellyfin/jellyfin/files/4812650/Log_tvshow_scan.txt)
[01x01.txt](https://github.com/jellyfin/jellyfin/files/4812843/01x01.txt)

**Screenshots**
![image](https://user-images.githubusercontent.com/58141187/85276172-aded1c80-b481-11ea-87af-628e23fd5e64.png)
![image](https://user-images.githubusercontent.com/58141187/85276259-cf4e0880-b481-11ea-9f4e-9cc62c67354b.png)

![image](https://user-images.githubusercontent.com/58141187/85276123-9d3ca680-b481-11ea-9cc5-b7f03ab0fd28.png)

**Comment by nvllsvm** [comment]
Same problem here with movies.

**Comment by Bond-009** [comment]
Can you try again with the latest master? #3409 fixed a scan issue

**Comment by lelamamalgache** [comment]
Hello, it works ! well done, thank you @Bond-009
