### ISSUE TITLE
Add support for Dynamic Playlists

### ISSUE THREAD

**Issue by klada** [jellyfin/jellyfin#342]
Hi,

it would be super handy if Jellyfin would support dynamic playlists, based on search criteria like tag information.

Example: Playlist which would dynamically contain all songs which have "%metal%" in their genre tag. This playlist would then include all sub-genres, such as "Power Metal", "Speed Metal", etc.

Also playcounts would probably be interesting for dynamic playlists. Playlists such as "played more than 5 times" would also be cool.

This has been a long requested feature in Emby, but the developers there did not seem to be interested in improving the music management part. Maybe Jellyfin can change this situation.

**Comment by WisdomCode** [comment]
I find the description rather complicated.
The desired feature is available under the name 'Smart Playlist' in numerous powerful Music organizers, such as ITunes, Banshee or Ampache. 
I would also love to see this feature. If the exact workings of such a thing are not precise enough from this request, I may add some screenshots on how other software provide this.

**Comment by philippk80** [comment]
Would love that too!
