### ISSUE TITLE
Local trailer from the "trailers" folder is not used.

### ISSUE THREAD

**Issue by sl1288** [jellyfin/jellyfin#3422]
With an directory structure like this:
\Film (2000)\Film (2000).mkv
\Film (2000)\trailers\Film (2000).mkv
\Film (2000)\Extras\Honest Trailer.mkv

The File "\Film (2000)\Extras\Honest Trailer.mkv" is played as a local trailer.

With an directory structure like this:
\Film (2000)\Film (2000).mkv
\Film (2000)\trailers\Film (2000).mkv

It does play an youtube trailer.

This was working in an older version, see issue #1639

**Comment by sl1288** [comment]
Tested version: https://github.com/jellyfin/jellyfin/commit/a69397d7141a6f8fde840cb53516244785243de8

Trailer playback does work with this folder structure now:
\Film (2000)\Film (2000).mkv
\Film (2000)\trailers\Film (2000).mkv

But with this structure "\Film (2000)\Extras\Honest Trailer.mkv" is still played, instead of "\Film (2000)\trailers\Film (2000).mkv"
\Film (2000)\Film (2000).mkv
\Film (2000)\trailers\Film (2000).mkv
\Film (2000)\Extras\Honest Trailer.mkv

**Comment by cvium** [comment]
Caused by this line https://github.com/jellyfin/jellyfin/blob/8045a488ceccc5c85195be3ef694a418c1c326aa/Emby.Server.Implementations/Library/LibraryManager.cs#L2779

extras > trailers.

Whether the existence of a `trailers` folder means it should ignore `extras` is up for debate.

**Comment by taylor-schneider** [comment]
any fixes?

**Comment by crobibero** [comment]
https://github.com/jellyfin/jellyfin/pull/7028

**Comment by hasezoey** [comment]
i dont know the current state of this issue, but i would also be in favor of having the folder `trailers` take priority over `extras`
