### ISSUE TITLE
minor bug on 10.6.0 nightly 2020-06-23, Remote doesnt update

### ISSUE THREAD

**Issue by ikomhoog** [jellyfin/jellyfin#3424]
When im playing a video on my pc, thats hooked up to the TV, i can use my android phone as a remote by clicking on the cast button and then my pc jellyfin session.
all the buttons work, but the interface is not updated, this makes skipping using the timeline slider impossible since it works but its not at the correct time(it stays at 0 untill you use it), this is the same for the volume slider.
Also when i use the timeline it shows "--:--" instead of an actual time.
The notification on my phone with almost the same controls IS updated.
the notification update rate is not stable, it can update every second or there can be a 5 second delay, its mostly(every 1-2 seconds though).

might be related:
when pressing on the cast button again, it doesnt do anything.
when i close the jellyfin app the notification also stays there and i cannot close it, I need to connect as a remote again and stop the media to make the notification go away.

**System (please complete the following information):**
 - OS: host: Unraid 6.8.2 (linux) 
 - Virtualization: Docker
 - Clients: Chrome, Firefox, android10, chromecast, Windows 10(chrome), Ubuntu 20.04(firefox)
 - Browser: Chrome 83.0.4103.106, firefox and the android app
 - Jellyfin Version: nightly 20200623 or nightly 20200622 (dont know when exactly it updates but i just updated it).
 - Playback: All 
 - Installed Plugins: AudioDB 10.6.0.0, MusicBrainz 10.6.0.0, OMDb 10.6.0.0, Open Subtitles 7.0.0.0, TMDb Box Sets 5.0.0.0, TheTVDB 10.6.0.0, but they dont work on nightly anyway
 - Reverse Proxy: nginx
 - Base URL: jellyfin.mydomain.com
 - Networking: Bridge
 - Storage: local

1. play any media in the browser
2. use your phone and also open jellyfin (this also works on an incognito chrome tab)
3. click on the cast button and select your pc's session
4. the bottom of your screen should have the current timeline but its not updating.
5. click on the bottom to open the remote and there you can also see that the volume slider is not working.
6. use the buttons and you can see that everything does work but is just not updated to the current values of the pc session

i expect the timeline to be the same as the timeline on the current active session im trying to control, and the same for the volume.

There are no errors

**Comment by crobibero** [comment]
Is this from within the Jellyfin android app?

**Comment by ikomhoog** [comment]
only the notification is caused by the app, the browser doesnt make a notification.
the rest im describing can be reproduced in the browser(chrome and firefox) on pc(windows 10 and ubuntu 20.04) and an android phone with: the app, chrome or firefox.

**Comment by ferferga** [comment]
Caused by #3428

**Comment by ikomhoog** [comment]
@ferferga Just saw that your issue was fixed and tested this one again, its solved now.
