### ISSUE TITLE
tvshow wrong metadatas, unable to identify correclty

### ISSUE THREAD

**Issue by lelamamalgache** [jellyfin/jellyfin#3426]
**Describe the bug**
Hello, i have a new tv show named "Gigantes (2018)", jellyfin got wrong metadata for this tvshow.

- When i try to identify manualy by the name and the year.
- When i try to identify by imdb tt6970690 or themoviedb 82533

For the both, jellyfin showed me the good poster but the process can't finish and finaly get the same wrong metadata (poster, descriptions, resume episodes)

**System (please complete the following information):**
 - Virtualization: docker
 - Clients: browser
 - Browser: chrome
 - Jellyfin Version: linuxserver-jellyfin:nightly 20200623
 - Reverse Proxy: linuxserver-letsencrypt
 - Storage: btrfs synology

**To Reproduce**

1. create a folder name "Gigantes (2018)"
2. scan you library
3. try to get good metadata

**Logs**

[Log_23068_identify.txt](https://github.com/jellyfin/jellyfin/files/4821365/Log_23068_identify.txt)

**Screenshots**

wrong poster
![image](https://user-images.githubusercontent.com/58141187/85445953-35c34b80-b594-11ea-84db-1d85c8cdfe40.png)

selecting the good poster
![image](https://user-images.githubusercontent.com/58141187/85445147-5e971100-b593-11ea-9a2a-9c74125c9b9a.png)

**Comment by kazimpaktv** [comment]
I share this information quite a bit so I thought it would be helpful to me as well to have 
some of the best pins in one post.

<a href="https://paktvdramas.pk/">PakTVDramas</a>

**Comment by cvium** [comment]
@kazimpaktv You thought wrong.
