### ISSUE TITLE
JF wont show information for multi-part ISOs with local metadata

### ISSUE THREAD

**Issue by 1024mb** [jellyfin/jellyfin#3427]
**Describe the bug**

I have some Blu-ray ISOs that consist of 2 or more discs and are named following the standard: `Movie (1234) - Disc #.iso` but JF wont show any information for them, they have local metadata as I have set up JF to only use local and to not use any provider. JF does recognizes the additional part (disc 2) but nothing is shown for those entries (see image). Probably related to #2697?

**System (please complete the following information):**
 - OS: Windows 10
 - Virtualization: 
 - Clients:
 - Browser:
 - Jellyfin Version: 10.6.0 nightly
 - Playback: 
 - Installed Plugins: 
 - Reverse Proxy: 
 - Base URL: 
 - Networking:
 - Storage: local

**To Reproduce**

1. Add multi part movies (ISO images)
2. Scan the library
3. Look at the new entry

**Expected behavior**
Local metadata should be used so Poster, Overview and all other stuff should be present.
**Screenshots**
![firefox_2020-06-23_15-51-12](https://user-images.githubusercontent.com/9301204/85461238-ba4ca480-b569-11ea-8d9b-bc2e9a318e96.png)

**Comment by bingzhangdai** [comment]
Similar issue found in TV Shows. I have a multi-part episode with name
![image](https://user-images.githubusercontent.com/9895061/89736478-3eb4a180-da9c-11ea-9fe9-0a54625567a6.png)

In the JF web, It won't show the metadata correctly, at least no description,
![image](https://user-images.githubusercontent.com/9895061/89736505-758ab780-da9c-11ea-820f-b9e889474136.png)
(episode two shows correctly)

**Comment by bingzhangdai** [comment]
Any follow up?

**Comment by 1024mb** [comment]
Issue still present in latest stable.

**Comment by 1024mb** [comment]
This is still happening in 10.8.7

**Comment by bingzhangdai** [comment]
just comment to active this issue

**Comment by bingzhangdai** [comment]
still exists

**Comment by 1024mb** [comment]
This is still happening, and is not only with ISO files, with multi-part video files too.
@felix920506 what data is missing from the report? I see you placed this issue in Insufficient Data but you have made no comment here.

**Comment by felix920506** [comment]
ISOs are not supported. Please open a new report for video files.
