### ISSUE TITLE
Live TV abnormally buffering

### ISSUE THREAD

**Issue by Protektor-Desura** [jellyfin/jellyfin#3430]
On both Android TV client and Roku client my Live TV is buffering all the time. It will play 1-2 minutes then buffer and skip and then play 1-2 minutes, then buffer and skip. Live TV does NOT do this on VLC (stand alone) or Android IPTV client.

**Comment by crobibero** [comment]
Please fill out the bug report template.

**Comment by Ricas13** [comment]
Change your default LiveTV player to libVLC.
