### ISSUE TITLE
Login with remote connections denied raises 500 rather than authentication failed

### ISSUE THREAD

**Issue by RealOrangeOne** [jellyfin/jellyfin#3452]
**Describe the bug**

Login on remote network raises 500 rather than authentication failed. This happens with either easy pin or password.

**System (please complete the following information):**
 - OS: Ubuntu
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Firefox
 - Jellyfin Version: 10.5.5
 - Reverse Proxy: Traefik
 - Base URL: None

**To Reproduce**
Uncheck "Allow remote connections to this jellyfin server" for user.

Switch to a machine outside the network (tether via phone), and login

**Expected behavior**

Authentication failed message (probably something generic)

**Logs**
```
jellyfin    | [12:25:45] [ERR] [162] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: http://****/Users/authenticatebyname
jellyfin    | MediaBrowser.Controller.Authentication.AuthenticationException: Forbidden.
jellyfin    |    at Emby.Server.Implementations.Library.UserManager.AuthenticateUser(String username, String password, String hashedPassword, String remoteEndPoint, Boolean isUserSession)
jellyfin    |    at Emby.Server.Implementations.Session.SessionManager.AuthenticateNewSessionInternal(AuthenticationRequest request, Boolean enforcePassword)
jellyfin    |    at MediaBrowser.Api.UserService.Post(AuthenticateUserByName request)
jellyfin    |    at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
jellyfin    |    at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
jellyfin    |    at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

**Comment by crobibero** [comment]
This has been fixed in 10.6-unstable. I now get "You are not authorized to access the server at this time. Please contact your server administrator for more information."
