### ISSUE TITLE
10.6.0 new EFCore database locked issue

### ISSUE THREAD

**Issue by Spiritreader** [jellyfin/jellyfin#3459]
**Describe the bug**

When operating the jellyfin dashboard or reloading the page, the web interface hangs for ~20-30 seconds.
It looks like this is due to the database being locked at this time.
Operation resumes as normal once the lock is released, however I don't think this is expected behavior.

**System (please complete the following information):**
 - OS: Unraid
 - Virtualization: Docker
 - Clients: All
 - Browser: All
 - Jellyfin Version: 20200626.3-unstable

**To Reproduce**

1. Open dashboard
2. Change settings or leave dashboard
3. Web interface hangs, exceptions in the provided logs show up after a while

Reproducing this is not consistent as it can work for hours without issue and it happens intermittently without any pattern. Maybe some concurrency issue?

**Expected behavior**

No hangups, during the navigation of jellyfin

**Logs**

I've attached an excerpt of the server log when the exception occurs.
[server-db-table-locked.log](https://github.com/jellyfin/jellyfin/files/4838934/server-db-table-locked.log)

@barronpm what's your take on this?

**Comment by BaronGreenback** [comment]
I saw similar database locks when tracing db concurrency issues. #3457.
