### ISSUE TITLE
freenas plugin

### ISSUE THREAD

**Issue by icf20** [jellyfin/jellyfin#346]
is there any chance to get a official plug-in for freenas?

i am asking because docker on freenas is complicated and will be more like a VM thing

**Comment by DoctorMacc** [comment]
This is tied with #95 as it seems the biggest step to get Jellyfin on the FreeBSD platform is .NET support.

**Comment by DoctorMacc** [comment]
For now, yes. I'd recommend leaving this open as when FreeBSD support is fulfilled in one way or another we'll have to see if we can get a spot on the plugin store.

**Comment by Mengine** [comment]
You could just set up a virtual linux node on your freenas, and install jellfyin on top of that.

**Comment by DoctorMacc** [comment]
I'm hoping for a native implementation, especially to make transferring from Emby to Jellyfin as simple as possible. One could set up Jellyfin on a Linux virtual machine in FreeNAS but if there's already an existing library location on the NAS it's hard to transfer over to the VM.

**Comment by icf20** [comment]
@Mengine there is no ram for that :crying_cat_face:

**Comment by ninnghazad** [comment]
jellyfin in debian vm under freenas works well. as well as it works under linux atm.

**Comment by Henry78** [comment]
To further clarify this: It *is* possible to run jellyfins docker image on FreeNAS, but like @icf20 mentioned: FreeNAS is mostly built on storage optimized boxes (lacks CPU power, in my case even VT-d) and uses the always memory hungry ZFS. So running a VM (Docker support in FreeNAS is realized via a Rancher VM) is a subpar solution to running a FreeNAS Plugin (FreeBSD iocage jail).

**Comment by texneus** [comment]
Although I absolutely agree a native FreeBSD solution is strongly needed, I just wanted to throw out for reference that I am currently evaluating Docker Jellyfin using a BHyve Debian virtual machine under XigmaNAS 11.2 and it seems to be working well (so far...).  It is definitely possible, but absolutely not a practical solution for most.

**Comment by balarpan** [comment]
Hi! How about already in ports .Net version?
[https://www.freshports.org/lang/linux-dotnet-cli/](https://www.freshports.org/lang/linux-dotnet-cli/)

**Comment by doug0162** [comment]
I believe those ports require a kernel module which gives FreeBSD the ability to execute Linux binaries.

**Comment by balarpan** [comment]
> I believe those ports require a kernel module which gives FreeBSD the ability to execute Linux binaries.
It's not a problem:
kldload linux64
cd /usr/ports/emulators/linux_base-c7 && make install clean
and append 4 rows to /etc/fstab according instruction in port in line above.

For me the main problem is to run .net DLL which comes in Portable package [https://repo.jellyfin.org/releases/server/portable/](https://repo.jellyfin.org/releases/server/portable/)

**Comment by balarpan** [comment]
Sorry, can't check write now FreeNAS installation, but any way it should be a potential solution for FreeBSD itself.

**Comment by elementalwindx** [comment]
ohhh I wish this was done already. LOVE free and truly open source projects. Shame Emby went the way it did. Now if only this project could get an official plugin for freenas I think many would be happiest.

**Comment by reesericci** [comment]
I'm just gonna try running the docker container in a jail. Let's see how that goes!

**Comment by Gizmo203** [comment]
Still waiting and wishing as well. Can't wait to uninstall Plex and upgrade to Jellyfin

**Comment by reesericci** [comment]
Apparently iXSystems is coming out with another product, called TrueNAS scale. It's basically FreeNAS/TrueNAS Core but built on Debian Linux instead of FreeBSD and it will use docker for containerization rather than Jails. Jellyfin will become a reality!

**Comment by Gizmo203** [comment]
TrueNAS core looks interesting but it a branch that won't have a stable release for an unknown amount of years. Freenas/TrueNAS has 10million ish downloads if my memory is right. That means right out of the gate huge amount of new jellyfin followers, and supporters.

**Comment by klebdotio** [comment]
So, If I were to pick up a Dell Poweredge R200, I would have the CPU performance for Jellyfin, so I could run it in a VM on FreeNAS?

**Comment by reesericci** [comment]
yea

**Comment by klebdotio** [comment]
would I have significant performance issues trying to do this?

**Comment by reesericci** [comment]
no

**Comment by nolanshah** [comment]
There's now unofficial support for .NET on FreeBSD x64 based on the [build docs](https://github.com/dotnet/runtime/blob/main/docs/workflow/README.md) and https://github.com/dotnet/runtime/issues/14537, so it should be possible to get a hacky-but-working Jellyfin installation.

**Comment by sec** [comment]
You want this https://github.com/Thefrank/jellyfin-server-freebsd  ? :)

**Comment by oddstr13** [comment]
Related feature request https://features.jellyfin.org/posts/221/freenas-plugin, please vote for this feature if the above linked repo doesn't fulfill your needs.
