### ISSUE TITLE
10.6 Unable to Connect

### ISSUE THREAD

**Issue by zalaare** [jellyfin/jellyfin#3468]
**Describe the bug**

**System (please complete the following information):**
 - OS: NixOS 20.03
 - Virtualization: Docker
 - Clients: Browser, Jellyin-Desktop, Android
 - Browser: Edge Chromium, Chrome
 - Jellyfin Version: Nightly/Unstable/10.6
 - Playback: n/a
 - Installed Plugins: n/a
 - Reverse Proxy: nginx, none
 - Base URL: none
 - Networking: host
 - Storage: local

**To Reproduce**

1. Have working jellyfin/jellyfin:10.5.5 server
2. Upgrade/Switch to jellyfin/jellyfin:nightly
3. Fail

**Expected behavior**

Expect to be able to successfully connect to running server
```
System.FormatException: An invalid IP address was specified.
 ---> System.Net.Sockets.SocketException (22): Invalid argument
   --- End of inner exception stack trace ---
   at System.Net.IPAddressParser.Parse(ReadOnlySpan`1 ipSpan, Boolean tryParse)
   at System.Net.IPAddress.Parse(String ipString)
   at Emby.Server.Implementations.Networking.NetworkManager.IsInPrivateAddressSpace(String endpoint, Boolean checkSubnets)
   at Emby.Server.Implementations.Networking.NetworkManager.IsInPrivateAddressSpace(String endpoint)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.ValidateHost(String host)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[14:28:09] [INF] [10] Emby.Server.Implementations.ScheduledTasks.TaskManager: StartupTrigger fired for task: Update Plugins
[14:28:09] [INF] [10] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queueing task PluginUpdateTask
[14:28:09] [INF] [4] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing Update Plugins
[14:28:09] [ERR] [4] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: http://<dns_name>/ScheduledTasks?IsEnabled=true
System.FormatException: An invalid IP address was specified.
 ---> System.Net.Sockets.SocketException (22): Invalid argument
   --- End of inner exception stack trace ---
   at System.Net.IPAddressParser.Parse(ReadOnlySpan`1 ipSpan, Boolean tryParse)
   at System.Net.IPAddress.Parse(String ipString)
   at Emby.Server.Implementations.Networking.NetworkManager.IsInPrivateAddressSpace(String endpoint, Boolean checkSubnets)
   at Emby.Server.Implementations.Networking.NetworkManager.IsInPrivateAddressSpace(String endpoint)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.ValidateHost(String host)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[14:28:09] [ERR] [11] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: http://<hostname>:8097/
```

**Additional context**

I straight port-forwarded the running server port (8097) and tested without nginx in between, but got the same result (the above log chunk that just is using http://<hostname>:8097/ is from my client trying to get in.
Coming in through the outside, and inside using my regularly used dns entry is the other chunk.

**Comment by iotku** [comment]
Are you certain jellyfin is set to use port 8097? By default the non-https port is 8096

**Comment by BaronGreenback** [comment]
Maybe time to review #3257?

**Comment by masterkoppa** [comment]
I also experienced the same symptoms described here when I upgraded to 10.6.

The solution was to manually edit `system.xml` and remove the entry in `LocalNetworkAddresses` to be empty (even if there was a valid ip there before). After doing so, and restarting the jellyfin container things worked correctly.

`system.xml` before
```
  <LocalNetworkAddresses>
    <string>0.0.0.0</string>
  </LocalNetworkAddresses>
```

I made a complete backup of my config files pre-upgrade in case there's anything there of interest.

**Comment by zalaare** [comment]
@masterkoppa This worked for me as well.

**Comment by BaronGreenback** [comment]
Just submitted a PR as fixing this, breaks DLNA.  (https://github.com/jellyfin/jellyfin/pull/3515)

**Comment by davispuh** [comment]
I just updated to 10.6.0 and getting this same error. Looks like many things are broken with this release...

In browser shows `Error processing request.`
Log:

```
dotnet[41145]: [20:44:10] [ERR] [16] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: http://jelly/
dotnet[41145]: Syystem.Net.Sockets.SocketException (22): Invalid argument
dotnet[41145]:    --- End of inner exception stack trace ---
dotnet[41145]:    at System.Net.IPAddressParser.Parse(ReadOnlySpan`1 ipSpan, Boolean tryParse)
dotnet[41145]:    at System.FormatException: An invalid IP address was specified.
dotnet[41145]:  ---> Sstem.Net.IPAddress.Parse(String ipString)
dotnet[41145]:    at Emby.Server.Implementations.Networking.NetworkManager.IsInPrivateAddressSpace(String endpoint, Boolean checkSubnets) in /mnt/AUR/jellyfin/src/jellyfin-10.6.0/Emby.Server.Implementations/Networking/NetworkManager.cs:line 155
dotnet[41145]:    at Emby.Server.Implementations.Networking.NetworkManager.IsInPrivateAddressSpace(String endpoint) in /mnt/Dati/Pakotnes/Repozitoriji/AUR/jellyfin/src/jellyfin-10.6.0/Emby.Server.Implementations/Networking/NetworkManager.cs:line 124
dotnet[41145]:    at Emby.Server.Implementations.HttpServer.HttpListenerHost.ValidateHost(String host) in /mnt/Dati/Pakotnes/Repozitoriji/AUR/jellyfin/src/jellyfin-10.6.0/Emby.Server.Implementations/HttpServer/HttpListenerHost.cs:line 319
dotnet[41145]:    at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken) in /mnt/AUR/jellyfin/src/jellyfin-10.6.0/Emby.Server.Implementations/HttpServer/HttpListenerHost.cs:line 427
```

**Comment by BaronGreenback** [comment]
One of the problems with implementing so many changes across such as variety of platforms, each of which being almost unique,

Keep a look out for 10.6.1. It includes many fixes that have emerged.

**Comment by gxgani** [comment]
10.6 w/ nginx reverse proxy, unable to access jellyfin even with localnetworkaddress removed.

**Comment by juantascon** [comment]
having the same issue, however changing it to `0.0.0.0` doesn't fix it, could it be because my jellyfin is behind a proxy?

**Comment by BaronGreenback** [comment]
@juantascon - don't put anything into the field - leaving it blank <LocalNetworkAddresses/>

**Comment by TwizzyDizzy** [comment]
> having the same issue, however changing it to 0.0.0.0 doesn't fix it, could it be because my jellyfin is behind a proxy?

@juantascon try removing the entire `<LocalNetworkAddresses>...</LocalNetworkAddresses>` block. It will get re-added as empty entity - fixed it for me.

**Comment by Enzo-Matrix** [comment]
This issue still exists in 10.6.1

**Comment by TwizzyDizzy** [comment]
@Enzo-Matrix for me it's working now with this in `system.xml`:

```
...
  <LocalNetworkAddresses>
    <string>127.0.0.1</string>
  </LocalNetworkAddresses>
...
```

```
# ss -tlpn | grep jelly
LISTEN    0         128              127.0.0.1:8096             0.0.0.0:*        users:(("jellyfin",pid=11112,fd=307))
```

**Comment by BaronGreenback** [comment]
@Enzo-Matrix - can you post your logs please?

**Comment by Enzo-Matrix** [comment]
@BaronGreenback Turns out the first 10.6.1 combined build released on July 19 was the issue. Jellyfin server in that build was still 10.6.0 and jellyfin web was 10.6.1. I am now running the build from July 27 and this issue has bee resolved.
