### ISSUE TITLE
Thousands of DNS queries to letsencrypt verification domain when jellyfin is running

### ISSUE THREAD

**Issue by 10481** [jellyfin/jellyfin#347]
Okay, sorry for the back and forth editing on this. I wanted to make sure what I was seeing was directly tied to jellyfin and not specifically appearing to be a letsencrypt issue. That's not to say that it isn't a mixture of both though with my server's settings.

I've noticed a massive amount of hits to `cert.int-x3.letsencrypt.org` that are correlated directly to playback from jellyfin remotely. If I stop jellyfin (much to the dismay of users) for a specified amount of time, then these hits also stop. Is it possible that maybe this is related to the WAN detection issues as seen on the jellyfin dashboard? I don't have older logs from a week ago when I was still using emby, but it's quite possible that these `cert.int-x3.letsencrypt.org` are replacing hits that used to be `my.domain.com`.

OS: Arch linux
Server: Jellyfin 3.5.2.0 with settings migrated from Emby 3.5.3 via backup and restore plugin
The hardware, domain and certificate are all identical

I don't think it's really a high priority or anything, but it's an unfamiliarity after starting up with jellyfin and I don't want to run into any issue with letsencrypt. Here's a screenshot showing the amount of hits that can register in a short amount of time as well as a [pastebin of the activity.](https://pastebin.com/vn7zh6wH) It's just basic browsing of the selection before playback, but it will do this for all remote devices throughout playback as well.

![screenshot_2019-01-01_11-22-32](https://user-images.githubusercontent.com/16447243/50576208-8f90ee00-0dc1-11e9-8d0d-d66ba9507b23.png)

**Comment by JustAMan** [comment]
It might be what icanhazip service resolves to...

**Comment by 10481** [comment]
That certainly could be. I haven't dug into it (quite literally) to see what's going on. I'm more than happy to do that when I get a chance to. Hopefully someone else that has any sort of service up to monitor DNS traffic might also chime in as well to answer if they see anything similar.

**Comment by sparky8251** [comment]
[icanhazip does not try and make AAAA queries if you check it in the source.](https://github.com/jellyfin/jellyfin/blob/f8a720d3d8adbdb1f092a42e592dae37ba3f25bb/Emby.Server.Implementations/ApplicationHost.cs#L2064)

As for if its resolving to LE, `dig ipv4.icanhazip.com` results in `ipv4.icanhazip.com.     276     IN      A       147.75.40.2` and `dig -x 147.75.40.2` results in `147.in-addr.arpa.       10122   IN      SOA     z.arin.net. dns-ops.arin.net. 2017026375 1800 900 691200 10800` so it looks like a no to me.

Wonder why its doing that for you? Hows certbot configured for you?

**Comment by 10481** [comment]
Certbot is set on a systemd timer to run twice per day and shows no errors and the certificate has been automatically renewing for about a year. The command it runs is `ExecStart=/usr/bin/certbot renew --quiet --agree-tos  --deploy-hook "systemctl reload nginx.service"` and that's it. I'm currently sitting at 17,000+ hits over the last 24 hours. It's so incredibly strange because it comes to a halt only when I stop jellyfin's service.

[Here's an hour's worth of debug level logs](https://pastebin.com/Dy2q8QvR)

**Comment by brianjmurrell** [comment]
Much of the log is playback progress being reported to the server every 10 seconds.  I suppose that is done to keep the server apprised of where it should resume from in the case of an ungraceful disconnect from the client.

So, there will be lots of queries for `my.domain.com`, 6 per minute at the above 10 second interval.  Not sure how/why that is correlating into `cert.int-x3.letsencrypt.org` queries though.  Some kind of certificate [revocation] verification mechanism perhaps?  I'd hope there'd be some level of caching for that sort of thing though and not a verification for every lookup.

**Comment by 10481** [comment]
A decent amount of it is cached, yes. Likely the majority based on a small sample size. I'm going to set up a vm with a fresh install of jellyfin and not import any info as I did for this install to keep it as clean as possible and compare.

**Comment by 10481** [comment]
I'm certainly no expert in this field, but I've finally correlated things by running emby and jellyfin and comparing them and the difference is that for whatever reason, jellyfin conflates `my.domain.com` and my server's hostname, which we'll call `server` with the letsencrypt domain. So when emby runs, it will show hits to `server` and `my.domain.com` whereas when jellyfin runs, it shows everything as `cert.int-x3.letsencrypt.org`, which explains why two common queries went missing and one new one showed up considerably more, although still cached.

**Comment by 10481** [comment]
Ultimately a clean install of jellyfin and not using the restore plugin to bring over settings has cleaned things up quite a bit. Before doing this, I didn't even have a section reporting my WAN address. It only showed LAN. I just assumed it was removed. I now see the icanhazip hits as well as someone mentioned previously. Migrating the server settings clearly broke some things.Everything seems to be much more in line with what it was under emby. Thanks everyone.
