### ISSUE TITLE
Disappearing users with accented characters on the name

### ISSUE THREAD

**Issue by teacupx** [jellyfin/jellyfin#3470]
Hello. I noticed some problem recently. I had several users on my server, one of them with non-english (accented) characters in its user name.

Well, I noticed that user has just disappeared, and had to re-create it (this time I replaced the accented characters with their unaccented equivalent). It used to work fine in the past, the user was able to log in and watch movies.

I am not sure when the issue happened, but it was recently. It could be when I upgraded to the latest 10.5.5 release. I am using deb packages, on a Debian Stretch with armhf architecture.

I can see the directory for the old user, with the accented characters in the name, under /etc/jellyfin/users. But it is not showing up in the user list at the Admin panel, nor the person can log in with that username.

On the other hand, I just created a different test user with accented characters in the name, and it works fine.

**Comment by crobibero** [comment]
Can you give an example of the accents in the name that failed to migrate?

**Comment by teacupx** [comment]
It had an á
