### ISSUE TITLE
<watched> tag in nfo files are not automatically set. Needs manual refresh of metadata

### ISSUE THREAD

**Issue by gadric** [jellyfin/jellyfin#3486]
**Describe the bug**
I enabled nfo for meta data. For my user (which is the only one), I activated to save the <watched> status of files in the nfo files. 

In the first run, jellyfin stored the current status in the nfo files correctly. But, when I watched a movie or a media file, the watched status is not updated in the nfo files. I have changed the scan Intervall of libraries and restarted jellyfin, but nothing changed. The only way to update the status in the nfo files is to manually refresh the meta data. This workaround seems not usable to me.  

**System (please complete the following information):**
- OS: Debian 10
- Virtualisation: Docker
- Client: iOS
- Browser: Chrome, Firefox
- Jellyfin Version: 10.5.5
- Playback: direct play
- Installed Plugins: IPTV, AudioDB, TMDb Box sets, Trakt
- Reserve Proxy: none
- Base URL: non
- Networking: host
- Storage: Local, ext4

**To Reproduce**
Described in 1. 

**Expected behavior**
After the media files have been watched, Jellyfin should update the <watched> tag in the nfo file to „true“

**Logs**
No log files 

**Screenshots**
No Screenshots

**Additional context**
None

**Comment by anthonylavado** [comment]
Related to #1640.
