### ISSUE TITLE
(Intel QSV)the server isn't sending a compatible media format.

### ISSUE THREAD

**Issue by ssyangchn** [jellyfin/jellyfin#3488]
**Describe the bug**
When QSV hardware acceleration is enabled, after selecting subtitles, it prompts that there is a problem with the client configuration file, and the server does not send a compatible media format. Turn off the subtitles and play them successfully

**System:**
 - OS: win10 x64, i5-8250U, UHD Graphics 620, Radeon 500 Series
 - Virtualization: no
 - Clients: Browser
 - Browser: Chrome 83
 - ellyfin Version: 10.5.5
 - Playback: Transcode
 - Installed Plugins: Fanart, Anime, etc
 - Reverse Proxy: none
 - Base URL: none
 - Networking: Bridge/NAT
 - Storage: I use RaiDrive mapping the google drive to local

**To Reproduce**

enable QSV HW, paly one HEVC 10bit movie and select a subtities, and then  prompts the error tip

**Expected behavior**
play success

**Logs**
ffmpeglog
[ffmpeg-transcode-7f575f1c-be00-4297-a71b-fc86a1164f74.txt](https://github.com/jellyfin/jellyfin/files/4858161/ffmpeg-transcode-7f575f1c-be00-4297-a71b-fc86a1164f74.txt)

**Screenshots**

![批注 2020-07-01 213307](https://user-images.githubusercontent.com/15191505/86250081-b57b9680-bbe2-11ea-811a-9a6ebf293fb2.png)
![2](https://user-images.githubusercontent.com/15191505/86250098-bad8e100-bbe2-11ea-8730-9e24cea6dcf0.png)
![3](https://user-images.githubusercontent.com/15191505/86250111-c0362b80-bbe2-11ea-8b78-79b1de41f940.png)

**Additional context**

**Comment by nyanmisaka** [comment]
It is a known upstream issue. https://github.com/Intel-Media-SDK/MediaSDK/issues/2031
