### ISSUE TITLE
Remote rendering through hooks or other means

### ISSUE THREAD

**Issue by userbradley** [jellyfin/jellyfin#3514]
As per the discussion on Reddit with u/djbon2112, I have been asked to make a feature request for remote rendering infrastructure. 

The idea we were throwing around was to be able to spin up render farms on public cloud, but we know that no one is that rich....
Our second idea was to use something like WOL with a dedicated render box, but to be able to conserve power etc, it would need to be WOL.

For some of us, we would like to toy with the idea for being able to either send WOL packets to a host or to be able to spin up new instances via something like terraform and then use ansible to provision the server, or in our home labs spin up vm's as per needed to run remote encoding jobs.

This can be achived in many ways; but the best one I could come up with as of now as have the ability to specify how rendering should take place based on file types, encoding and active users.

If the video is a 4K video and the network has the throughput, it should be transcoded off the box, same for if there are 8+ users logged in. As well as being able to set a default transcode option of `remote` or `local` 

Secondly, depending on if you have chosen `remote` it will give you the option for specifying a server to use as a remote encoding host, and then send wol packets once an account logs in, which would be enough time for the server to boot (linux is usualllly fast to boot) and then to accept transcode jobs.
Thirdly, if remote is picked, be able to specify [a] script(s) to run as well as input for the transcode boxes. (How ever this may have issues with things like running on public cloud as you never know what IP address, so possibly store these values in file and allow for scripts to update them)

I'm happy to help out with the ansible stuff and terraform where I can, I'm not amazing, but I am learning it and usually manage to figure stuff out.

**Comment by userbradley** [comment]
Worth mentioning this was [the comment string](https://www.reddit.com/r/jellyfin/comments/hirn1b/ever_wanted_to_run_your_jellyfin_transcoding_on/fwi2e6t?utm_source=share&utm_medium=web2x) in question

**Comment by joshuaboniface** [comment]
Oh I was actually thinking specifically for rffmpeg ;-) Though having it here is OK for now.

**Comment by userbradley** [comment]
Do you want me to move this to your repo and close this one?

**Comment by joshuaboniface** [comment]
Yea let's do that, I was going to transfer the issue but can't between orgs.

**Comment by BaronGreenback** [comment]
PR #3257 contains a wake on lan implementation for exactly this purpose. 

WakeOnLAN.cs
