### ISSUE TITLE
Kinopoisk metadata plugin

### ISSUE THREAD

**Issue by LinFor** [jellyfin/jellyfin#3520]
Hello. I made some small plugin to fetch metadata from [Kinopoisk](https://www.kinopoisk.ru/). It's an extremely influential movie website for a Russian-speaking audience. So, the “kinopoisk rating” for a Russian-speaking audience is more recognizable and authoritative than the IMDB rating.

I published sources under permissive license on github: https://github.com/LinFor/jellyfin-plugin-kinopoisk
Also I made compiled binary for 10.6 abi and made repository manifest for ease plugin installation: https://raw.githubusercontent.com/LinFor/jellyfin-plugin-kinopoisk/master/dist/manifest.json

Feel free to use it if you want, and what to do next to promote it to main repository?

**Comment by dkanada** [comment]
I would love a section in our documentation for third party manifests such as this one, feel free to add it somewhere on [this](https://jellyfin.org/docs/general/server/plugins/index.html) page. @oddstr13 has a tool to automate the manifest creation and updates if you're interested, I don't know if we have it published anywhere yet though. @crobibero you might also want to add your manifest to the list.

**Comment by oddstr13** [comment]
The script isn't fully polished yet, but it can be found at https://github.com/oddstr13/jellyfin-plugin-repository-manager
