### ISSUE TITLE
LiveTV Recording Series - Adjusting Settings Cancels Future Recordings

### ISSUE THREAD

**Issue by bbalz** [jellyfin/jellyfin#3523]
**Describe the bug**
When you setup a series to be recorded, it shows that all subsequent episodes will be recorded.  However, if you adjust the series settings (ie: record on time, record 1 minute afterwards, record only new episodes, etc), the subsequent series are no longer showing a red dot and if you find them in the guide it shows they will not be recorded.  

Any adjustments to the settings seems to screw up the future recordings unless you manually set them to record again, which defeats the purpose of telling it to record the series.

**System (please complete the following information):**
 - OS: Windows
 - Virtualization: N/A
 - Clients: AndroidTV
 - Browser: Brave
 - Jellyfin Version: 10.5.5
 - Playback: Direct Play
 - Installed Plugins: Kodi Sync Queue, Playback Reporting, Telegram Notification
 - Reverse Proxy: caddy2
 - Base URL: none
 - Networking: N/A
 - Storage: local

**To Reproduce**

1. Select a TV series to record
2. Go into series settings
3. Adjust any setting (record only new episodes or adjust timing of when recording starts)
4. Go back to viewing anything else in Jellyfin
5. Go back into LIVE TV and view Series and see future recordings are no longer going to record.

**Expected behavior**
When adjusting series settings, future recordings remain selected to record.

**Logs**

**Screenshots**

**Additional context**

**Comment by wernerbw** [comment]
Have same issue; VERY AGGRAVATING!

**Comment by daneric2020** [comment]
Same issue here.  Basically, when setting up a series recording and modifying any setting it cancels all recordings for that series.

**Comment by eservello** [comment]
Ditto. This is a problem on my setup too exactly as described by bbalz on 7/7/2020. Search for a TV series, press "Record Series" and accept default settings. Show appears in Series listing and in Schedule listing. Modify any series recording settings, and no episodes in that series list show recording turned on, and everything disappears from the Schedule listing.

    OS: Windows 10 20H2
    Virtualization: native
    Clients: Browser (PC/Tablet)
    Browser: Edge, Firefox, Chrome
    Jellyfin Version: 10.6.4
    Playback: Jellyfin client (on server), LAN stream
    Installed Plugins: default only
    Reverse Proxy: none
    Base URL: none
    Networking: LAN only
    Storage: local

**Comment by bbalz** [comment]
Commenting to keep this bug from going stale.

**Comment by dymekd** [comment]
Same issue here. This is what is keeping me on Plex.

**Comment by danadux** [comment]
Do others not have this issue?

**Comment by bbalz** [comment]
It's the only reason I still keep Plex running.  It's dedicated to Live TV recordings and managing that.

Once it's solved then Plex is getting uninstalled.

**Comment by kpfleming** [comment]
Just installed Jellyfin (removed Emby) and seeing this behavior too.

**Comment by kpfleming** [comment]
In my case I don't even need to *change* any settings; just clicking the 'Series Settings' link after clicking "Record Series" causes this to happen. If I avoid clicking that link then the future episodes are marked for recording as expected.

**Comment by kpfleming** [comment]
FWIW, this issue is still present in 20220524.11-unstable.

**Comment by arazilsongweaver** [comment]
I have duplicated this issue with Jellyfin build 10.8.6 while testing the new Schedules Direct image fix. I scheduled about a half dozen series recordings, modified each series entry to suit my needs, and ultimately ended up with an blank Scheduled page under the Live TV section.
