### ISSUE TITLE
Consistency of episode numbering/title

### ISSUE THREAD

**Issue by Neolel** [jellyfin/jellyfin#3526]
This isn't something important but I noticed some inconsistencies in titling/numbering episodes on Jellyfin. Some screenshots will help what I exactly mean by that. The library, media controller and title of episode which is sent to MPV shim all look different. 
![Library](https://i.imgur.com/4yPZM9K.png)
![Media Controller](https://i.imgur.com/jj3cFb2.png)
![Title sent to MPV shim](https://i.imgur.com/P9vRMam.png)

Personally, I like the S00E00 or 0x00 one the best. But I feel like, one should be chosen and used consistently to have a more consistent experience overall.

**Comment by iwalton3** [comment]
If Jellyfin decides to standardize on a specific scheme let me know and I'll change it in MPV Shim.

**Comment by dkanada** [comment]
I've wanted to use `S00E00` everywhere for quite some time but it hasn't exactly been a high priority.

**Comment by nielsvanvelzen** [comment]
Ping me when we've made a decision on this, I'll try to apply it consistently in our Android apps.
