### ISSUE TITLE
TV show versions still have to be manually merged.

### ISSUE THREAD

**Issue by Darkwolf1515** [jellyfin/jellyfin#3543]
TV shows with multiple versions have to be merged manually, not automatically like movies. 

**Platforms** 

All of them.

**To Reproduce**
-Have two versions of a TV episode
-Watch as they do not merge

**Expected behavior**
They merge automatically. 

**Additional context**
I noticed that there will be support for sorting the multi version movies in 10.7 https://github.com/jellyfin/jellyfin-web/pull/1237 , any chance this can be extended to TV shows?

**Comment by DesertCookie** [comment]
Issue #1237 only makes minor Javascript changes to improve the ordering client-side. Your request sounds like something that has to be done server-side during the library scan. I'd like to help but I'm out of my depth.

Other than that, I'd love to see this too as I have lots of 4K series.

**Comment by holow29** [comment]
Seems like the same as these:
https://github.com/jellyfin/jellyfin/issues/2112
https://github.com/jellyfin/jellyfin/issues/1996

**Comment by Darkwolf1515** [comment]
Still a thing.

**Comment by rgaborieau** [comment]
> Still a thing.

I agree. Didn't found anything to fix. Bug or feature ?

**Comment by Darkwolf1515** [comment]
> > Still a thing.
> 
> I agree. Didn't found anything to fix. Bug or feature ?

Both?

**Comment by cvium** [comment]
Feature request. Please re-open here if it doesn't already exist: https://features.jellyfin.org
