### ISSUE TITLE
"Block items with tag" entry still shows up in "Up Next"

### ISSUE THREAD

**Issue by lreinink** [jellyfin/jellyfin#3559]
**Describe the bug**
After adding a tag to a series and restricting a user's access to that tag, it is properly removed from the Series folder. However, the series still shows up in "Up Next".

**System (please complete the following information):**
Raspberry Pi 4 4GB
Client: web browser, Firefox 78.0.2 (64-bit), Mac.
Jellyfin Version: Version: 10.5.5

**To Reproduce**
Add tag to a series that has already been watched once (so it shows up in Up Next).
Restict a user's access to that tag.
Log in with that user, the episode still shows up in Up Next.

**Expected behavior**
The episode (and entire series) does not show up in Up Next

**Comment by virgil9306** [comment]
This is still an issue

**Comment by pixelomer** [comment]
This is still an issue. Restricted TV shows also show up in "Latest TV Shows" and they can even be played even though they shouldn't be visible at all.

**Comment by Applesauce314** [comment]
it looks like this may have been fixed by commit https://github.com/jellyfin/jellyfin/commit/81746666ded02f844605fb26bc1c0ac2dd650bb0 .
It's not in 10.8.13, but it is in master.
