### ISSUE TITLE
Songs with special characters in filename added to .m3u8 playlist with incorrect file path

### ISSUE THREAD

**Issue by mikikuri** [jellyfin/jellyfin#3567]
**Describe the bug**
When a user adds a song with special characters in its filename to a pre-existing .m3u8 playlist, it will save the song to the playlist with an incorrect file path, and the song will not appear on the playlist in Jellyfin.

**System (please complete the following information):**
 - OS: Windows 10 (Docker), Ubuntu 20.04
 - Virtualization: Docker (Windows only)
 - Clients: Chrome, Jellyfin Android App
 - Browser: Chrome 83
 - Jellyfin Version: 10.5.5 (Ubuntu), 10.5.5 (Docker on Win10), 10.6.0 Nightly (Docker on Win10)
 - Playback: Direct Play
 - Installed Plugins: AudioDB, Fanart, MusicBrainz, OMDb, TheTVDB
 - Reverse Proxy: None
 - Base URL: None
 - Networking: Default
 - Storage: NFS

**To Reproduce**
1. Create a .m3u8 playlist file
2. Re-scan media in Jellyfin to pick up the playlist file
3. Add a song with special/foreign characters to the imported playlist
4. Open play list, song will not be available for playback
5. Open .m3u8 file in a text editor and see incorrect file path

**Expected behavior**
Songs with should be added to the .m3u8 playlist file with a relative filepath.

**Additional context**
For background, my playlists are saved on my NAS in the "music" folder with the following file structure:
-music
--playlists
---Playlist.m3u8
--EN Artists
--KR Artists
---ArtistName
----SongName.flac

An example of the issue is that I have the following 2 songs, 1 with a Korean filename and 1 with an English filename:
- 01 Madonna.mp3
- 01 샤이보이.mp3

When trying to save these into the playlist in Jellyfin this is what's generated in the playlist.m3u8 file:
![image](https://user-images.githubusercontent.com/67615080/87562968-07074380-c702-11ea-8263-4cf1b756917b.png)
- The song with the English filename will be correctly added to the list with a relative file path, which is the expected result.
- The song with the Korean filename defaults to an absolute file path, with a doubled up file path starting with /nas/music

This issue only occurs when using externally saved .m3u8 playlists. If I create a playlist within Jellyfin and add the above songs to it, there is no issue.

It appears Emby users also have this issue:
- [https://emby.media/community/index.php?/topic/72898-m3u-playlist-issue/](url)
- [https://emby.media/community/index.php?/topic/62970-track-not-added-to-playlist-special-characters/](url)

**Comment by BaronGreenback** [comment]
PlaylstManager.cs [529] uses Uri.MakeRelativeUri.

According to this http://www.blooberry.com/indexdot/html/topics/urlencoding.htm and RFC 1738, Uri.MakeRelativeUri only supports ASCII 7 bit characters.
```

"...Only alphanumerics [0-9a-zA-Z], the special characters "$-_.+!*'()," [not including the quotes - ed], and reserved characters used for their reserved purposes may be used unencoded within a URL."
```

**Comment by BaronGreenback** [comment]
What are you using to create the original .m38u file?

**Comment by mikikuri** [comment]
@BaronGreenback ahhh your comment pointed me in the right direction. Found out that the mount was missing a iocharset=utf8 setting. Got it working, thanks.
