### ISSUE TITLE
Could not connect to server

### ISSUE THREAD

**Issue by pojhm91c7iwk** [jellyfin/jellyfin#3574]
**Describe the bug**
The new update of Jellyfin mobile apps does not allow to connect to a local deployment of Jellyfin server.  By local deployment, I mean the local installation of Jellyfin server that is not exposed to the internet.  A simple example would be, being able to access Jellyfin at http://192.168.1.x:8096/. 

This is already working with the devices which have already added the local server successfully with previous version of Jellyfin apps.  Now, if you try to connect to server located at http://192.168.1.x:8096/, it gives "Could not connect to server" error.

**System (please complete the following information):**
 - Clients: iPhone, iPad OS
 - Jellyfin Version: 1.1.1 (1), Expo Version: 37.0.0

**To Reproduce**
1. Install Jellyfin iOS or iPad OS App
2. Click on 'Add Server'
3. Type 'http://192.168.1.x:8096/'
4. See error "Could not connect to server"

**Expected behavior**
1. Install Jellyfin iOS or iPad OS App
2. Click on 'Add Server'
3. Type 'http://192.168.1.x:8096/'
4. See your media libraries

**Comment by bigbearxl** [comment]
That's weird. Mine connect thru both local and Public IP (192.168.x.x:8096 or 49.228.xxx.xx:8096) work fine
But when connect thru ddns Jellyfin app will not work (Still accessible by web)

**Comment by pojhm91c7iwk** [comment]
I reinstall Jellyfin but still have the same issue.  I am able to access it on web fine, but the iOS and iPad specifically wouldn't add it.
