### ISSUE TITLE
Docker/Linux Path too long error

### ISSUE THREAD

**Issue by Protektor-Desura** [jellyfin/jellyfin#3583]
I'm running Ubuntu 20.04 and Jellyfin 10.5.5 in docker. The issue is that I am getting this error and it won't even try to detect the show because of this error. The path was created by Sonarr so clearly the path isn't too long for Sonarr or the OS because it updates and renames the files no problem. The directory/path length allowed needs to be expanded.

```
[19:18:32] [ERR] [14] LibraryMonitor: Error watching path: /media/tv
System.IO.PathTooLongException: The path '/media/tv/The Disastrous Life of Saiki K. (2016)/Season 01' is too long, or a component of the specified path is too long.
   at System.IO.Enumeration.FileSystemEnumerator`1.FindNextEntry(Byte* entryBufferPtr, Int32 bufferLength)
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at System.IO.FileSystemWatcher.RunningInstance.AddDirectoryWatchUnlocked(WatchedDirectory parent, String directoryName)
   at System.IO.FileSystemWatcher.RunningInstance.AddDirectoryWatchUnlocked(WatchedDirectory parent, String directoryName)
   at System.IO.FileSystemWatcher.RunningInstance.AddDirectoryWatchUnlocked(WatchedDirectory parent, String directoryName)
   at System.IO.FileSystemWatcher.RunningInstance..ctor(FileSystemWatcher watcher, SafeFileHandle inotifyHandle, String directoryPath, Boolean includeSubdirectories, NotifyFilters notifyFilters, CancellationToken cancellationToken)
   at System.IO.FileSystemWatcher.StartRaisingEvents()
   at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
   at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
   at Emby.Server.Implementations.IO.LibraryMonitor.<>c__DisplayClass30_0.<StartWatchingPath>b__0()
```

**Comment by BaronGreenback** [comment]
This looks to be a hangover from windows which could only support 259 character paths (+null at the end).

There is a workaround that may work. Preceed your folder path with \\?\ so c:\hello becomes \\?\c;\hello.

Some functions work with this, others don't.

Let us know how you get on.

https://social.technet.microsoft.com/Forums/windows/en-US/7355dfef-4db7-4873-ba3c-1d8acefc6f86/syntax-for-long-path-support-with-uncs?forum=winserverfiles

**Comment by Protektor-Desura** [comment]
I'm using Linux so I don't need c: anything in my path and it would just confuse docker and Jellyfin as to where to find the file.

The full path for one of the files, created by Sonarr is:
/mnt/storage/tv/The Disastrous Life of Saiki K. (2016)/Season 01/The Disastrous Life of Saiki K. - S01E03 - A Genius Magician!! Uryoku Chouno + Second Encounter (on TV)! Uryoku Chouno + How Shady! Dark Reunion! + Beachside Summer Story + A New School Term Starts! The Melancholy of Nendou [HDTV-720p x265 AAC].mkv

Here is another:
/mnt/storage/tv/The Disastrous Life of Saiki K. (2016)/Season 02/The Disastrous Life of Saiki K. - S02E04 - The Disastrous Life of Imu Rifuta + April Fools' Deceit! + Spring's Ultimate Weapon + Recycle! Trash Cleanup Competition + Cutting Through the Silence, the Ghost in the Music Room [HDTV-1080p h265 AAC].mkv

Sonarr created these which is also C# and written in .NET, just like Jellyfin. So this is possible and not issue of the language or compiler but something in Jellyfin code.

**Comment by BaronGreenback** [comment]
A workaround was implemented in .Net 4.7 in which an additional xml setting in the .net manefest extended the length. 

Parts of jellyfin are in .Net 2.1. Taken from a 9 year old post - "Microsoft has confirmed that it is a problem with the current implementation(s) of .NET that you cannot reliably find out what the maximum path size is as supported by the CLR." 

However, it does look someone has produced a work around. https://github.com/peteraritchie/LongPath

**Comment by BaronGreenback** [comment]
Jellfyfin uses the https://docs.microsoft.com/en-us/dotnet/api/system.io.filesystemwatcher.path?view=netcore-2.2 object to monitor the folders and this is what is crashing.

Is there any reason you have such long file names?

**Comment by Protektor-Desura** [comment]
This is what Sonarr creates automatically and renames to automatically because that is the actual length of the episode name in TVDB. I would assume they must be using a higher version of netcore or something because Sonarr handles long filenames and paths no problems and they also are C# and .NET and running on Linux as well. I use Sonarr, Radarr, Lidarr and Bazarr and have no issues with them. If you want the episode name in the filename, which I do for all my TV shows, then this is what ends up being used because that is what is in the metadata database at TVDB.

**Comment by BaronGreenback** [comment]
JF 10.7 runs under net 5.0 which supports file paths > 240 characters by default.
