### ISSUE TITLE
Manually merging media versions still show 2 of them on library

### ISSUE THREAD

**Issue by Manuel5cc** [jellyfin/jellyfin#3588]
**Describe the bug**
Two versions of the same movie in different folders can be merged manually by long click / select / group versions. When done, there are still two items in the library, both showing the number of versions available.

**System (please complete the following information):**
 - OS: Raspbian
 - Virtualization: Docker
 - Clients: Browser
 - Jellyfin Version: 10.5.5
 - Base URL: none
 - Networking: bridge
 - Storage: local

**To Reproduce**
1. Have 2 versions of the same content in the library, different folders.
2. Long click / select both / group versions

**Expected behavior**
I was expecting that only one item will remain on the library with the two versions.

**Screenshots**
[https://ibb.co/qgyRgmj](https://ibb.co/qgyRgmj)

**Comment by Artiume** [comment]
Go to Dashboard > Library > Display > and check mark `Group movies into collections`, see if that fixes the issue
