### ISSUE TITLE
Replace API keys/Investigate Metadata Services

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin#36]
In a few different areas, there are API keys for TheMovieDB and The TVDB. We should probably remove these.

Since there doesn't appear to be any better alternative metadata providers, I feel we should continue using these, and we can get API keys of our own for the project.

There are a few concerns however:
- TheMovieDB allows use in non-commercial projects without cost, but there is a rate limit (see [FAQ](https://www.themoviedb.org/faq/api))
- TheMovieDB is created by user contributions, but there are terms to agree to in order to use the data (see [API - Terms of Use](https://www.themoviedb.org/documentation/api/terms-of-use))

- The TVDB does have data available with less onerous terms (all I could find was the line at the bottom of [their website](https://www.thetvdb.com))
- The TVDB doesn't appear to rate-limit, or if they do, it's not obviously mentioned (see [API](https://api.thetvdb.com/swagger))

We can avoid hits on the TMDB API by following a similar approach to Firecore for their Infuse program. See: https://firecore.com/forum/topic/18385

Another option is to go all out and not include API keys, but make this user configurable somehow. That might be a future goal however, and I don't know if anything in the terms of either provider discourages/prohibits that type of use.

**Comment by joshuaboniface** [comment]
I'd rather us sign up for a single one, maybe explain the situation and work out a deal with them. Having to roll your own was sonething I hated about Streama.

**Comment by JustAMan** [comment]
There's even easier approach, much like *streama* does - make an empty field so the user fill their token inside, and not ship a built-in Jellyfin token at all.

That said, I'm not objecting to contacting TMDB and TVDB about special key... but don't have time now to do so, would anyone step up to it?

**Comment by anthonylavado** [comment]
> There's even easier approach, much like _streama_ does - make an empty field so the user fill their token inside, and not ship a built-in Jellyfin token at all.

That's what I meant to begin with really.

We should try to reach out to them at some point soon. Hopefully something can be worked out. I would think the order here is:
1. Replace currently shipped keys with our own (default)
2. Make it a user fillable option

That way, even if we can't broker a deal with them, someone can still put in their own user keys, which would then not add to one key making a huge number of requests.

**Comment by anthonylavado** [comment]
Linking this for review as well:

https://github.com/jellyfin/jellyfin/blob/21a8d273782a1a71678131f17ebaafd2b997f286/MediaBrowser.Providers/Music/MusicBrainzAlbumProvider.cs#L815

Looks like MB is just rate-limited in code. Must investigate how to better integrate.

**Comment by anthonylavado** [comment]
From discussion in [Riot/Matrix](https://matrix.to/#/!LCLiMJSFwJyNyVtqxj:matrix.org/$15446639292305475skQXn:matrix.org?via=matrix.org&via=t2bot.io&via=ifargle.com&via=half-shot.uk):

1. Change the API keys to new ones really soon
2. Implement the ability to have user supplied keys (just in case)
3. Explore the idea of caching, but this is low priority

**Comment by joshuaboniface** [comment]
I've contact The Movie DB to discuss. I've also signed up for MusicBrainz at @LeoVerto 's mention as a non-profit organization. Awaiting replies there. Still need to find contacts for The TV DB.

**Comment by joshuaboniface** [comment]
Found and contacted TheTVDB as well.

**Comment by anthonylavado** [comment]
Just to provide an update - on last check (Saturday night), we haven't received any communication back yet.

**Comment by BobOkisama** [comment]
Oddly, everything is now working for me. I had to manually go and re-identify each movie, but once done it was able to connect, get all art, and even can search additional art now.

**Comment by anthonylavado** [comment]
For OpenSubtitles, there is a small manual process. I'll get this started: http://trac.opensubtitles.org/projects/opensubtitles/wiki/DevReadFirst

**Comment by joshuaboniface** [comment]
I've never heard back from any of the API services. I strongly dislike *forcing* the user to use their own API keys (this was, honestly, my #1 reason for not using Streama, because I *personally* don't agree to their ToS, though on a project level I would). I'm not sure how best to proceed here.

**Comment by anthonylavado** [comment]
@JoshuaBoniface - We proceed as normal getting regular API keys for these services as best as possible. If it breaks, it breaks. If you did try contacting them all, the we have the receipt to prove we tried.

**Comment by joshuaboniface** [comment]
I've obtained API keys for:

* TheMovieDB
* TheTVDB
* TheAudioDB
* FanArt.tv

Integrated in PR #540

**Comment by anthonylavado** [comment]
Okay, this satisfies this Issue for me. We can come back to adding user supplied keys at a later time.
