### ISSUE TITLE
After updating to 10.6 I am unable to find it through UPnP. Still able to resume playing previous UPnP media.

### ISSUE THREAD

**Issue by drazil100** [jellyfin/jellyfin#3610]
**Describe the bug**
On both foobar2000 for iOS and vlc for iOS my jellyfin stopped showing up as an option. On foobar2000 for iOS I was able to resume what I was playing previously which I have confirmed in jellyfin's log is coming from jellyfin. 

**System (please complete the following information):**
 - OS: Debian
 - Clients: Foobar2000 and VLC for iOS
 - Jellyfin Version: 10.6.0
 - Playback: ???
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: none
 - Networking: ???
 - Storage: local

**Comment by Jonas2903** [comment]
I have a similar issue after updating to 10.6. My LG Web OS TV, Windows and VLC on Android are not able to find the server via UPnP. I run Debian 10 and Jellyfin Docker (Host Network). No Base URL. I can not find any error in the logs like "can not bind port" or so.
Only interesting info-line is:
` Emby.Dlna.Main.DlnaEntryPoint: DLNA Session created for "[LG] webOS TV UH610V" - "LG TV" `

So somehow it "sees" the device/TV.

**Comment by drazil100** [comment]
The part that most confuses me is how I was able to resume playing the album I was previously playing and skip forward and backwards through the album without issues. The server is clearly still running. It's just for whatever reason not visible. 

For some additional information I tried to navigate to more by the artist and it told me the folder was empty. I have literally never used this button so maybe it has never done anything over UPnP. I don't really want to try downgrading just to find out. Figure it was at least worth a mention anyway.
![image](https://user-images.githubusercontent.com/17794391/87932095-8ec9b680-ca50-11ea-8cd7-357e7c2b72ee.jpeg)
![image](https://user-images.githubusercontent.com/17794391/87932117-9721f180-ca50-11ea-987a-2c2e790ac9a1.png)

**Comment by PrplHaz4** [comment]
Can confirm I'm seeing similar behavior with the DLNA server not being discoverable on 10.6.0.

A quick wireshark compare (to 10.5) seems to point to SSDP NOTIFY messages not being sent at all on 10.6.0

The M-SEARCH message is still present on 10.6.0, which is probably why PlayTo works but Discovery does not.

@BaronGreenback did any of your DLNA changes mistakenly get merged into 10.6.0?

**Comment by BaronGreenback** [comment]
There was a breaking change (error not design). Putting the local lan network address into the network field and it will work.

**Comment by BaronGreenback** [comment]
@drazil100 There are a few issues around uPnP and 

https://github.com/jellyfin/jellyfin/pull/3536 - is a rewrite of the PlayTo
https://github.com/jellyfin/jellyfin/pull/3529 - filters SSDP to only media devices
https://github.com/jellyfin/jellyfin/pull/3383 - Incorporates Mono.NAT into Jellyfin and corrects some uPNP forwarding/processing issues.
https://github.com/jellyfin/jellyfin/pull/3257 - Is a network backend rewrite (which amongst other things, corrects the breaking change with Local LAN address range) and provides DNLA filtering.

**Comment by BaronGreenback** [comment]
@Jonas2903 Try PR#3383 above - it if doesn't work - enable logging (Think it's Mono.NAT.Searcher).
It has extensive logging including additional soap response processing.

**Comment by Jonas2903** [comment]
Thank you @BaronGreenback for your help. I set the local network (for me to 192.168.0.0/24) and it works fine. Maybe this should be mentioned in the documentation or in the DLNA tab. I didn't try your PR#3383.

**Comment by PrplHaz4** [comment]
> 
> 
> Thank you @BaronGreenback for your help. I set the local network (for me to 192.168.0.0/24) and it works fine. Maybe this should be mentioned in the documentation or in the DLNA tab. I didn't try your PR#3383.

Thanks from me too (I was even on that other discussion - didn't know it had already happened :)!  Applied the same fix, restarted the server and now seeing the discovery messages.

@joshuaboniface this should be called out as a breaking change in the release notes for 10.6.0 IMO

**Comment by BaronGreenback** [comment]
As I said above the change was in error and not by design. It was reported in PR #3515 - however, that PR would affect an earlier PR to fix something else. Nothing is easy with this code at the moment.

**Comment by ptasznikarium** [comment]
Thanks @BaronGreenback this was a fix for me as well.

Interestingly, I had some music playing over my wi-fi speaker (using it's own client on Android) just before upgrading to 10.6.0, and although I could not see JF share anymore, resuming music worked (played few songs, so definitely not cached), so although JF share was not showing anymore, it was still accessible
