### ISSUE TITLE
VAAPI Transcoding failing FFmpeg

### ISSUE THREAD

**Issue by freddag** [jellyfin/jellyfin#3612]
**Describe the bug**
VAAPI Transcoding failing the client gets the following
Playback Error
This client isn't compatible with the media and the server isn't sending a compatible media format.

maybe an issue with the free intel va driver that was added 
https://github.com/jellyfin/jellyfin-ffmpeg/pull/33
Though the nonfree version don't work either in 10.6.0 as far as I can tell
(Might be barking up the wrong tree with that one.)  
worked in 10.5.5 with the workaround of installing the non-free i965-va-driver-shaders.
all the docker-compose mounts look correct in the docker file and the Jellyfin config hasn't changed between the update.

**System (please complete the following information):**
 - OS: Debian
 - Virtualization: Docker 
 - Clients: Browser
 - Browser: Chrome 84
 - Jellyfin Version: 10.6.0
 - Playback: Transcode
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: none
 - Networking: NAT
 - Storage: local

**To Reproduce**

Updated to 10.6.0 from 10.5.5

**Expected behavior**
Playback of the film via transcoding

**Logs**
jellyfin    | [23:21:38] [INF] [66] MediaBrowser.Api.Playback.Hls.DynamicHlsService: Current HLS implementation doesn't support non-keyframe breaks but one is requested, ignoring that request
jellyfin    | [23:21:38] [INF] [66] MediaBrowser.Api.Playback.Hls.DynamicHlsService: /usr/lib/jellyfin-ffmpeg/ffmpeg -i file:"/media/Movies/The 40 Year Old Virgin (2005).avi" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_vaapi  -b:v 4077850 -maxrate 4077850 -bufsize 8155700 -profile:v high -level 41  -force_key_frames:0 "expr:gte(t,0+n_forced*3)" -g 75 -keyint_min 75 -sc_threshold 0 -vf "format=nv12|vaapi,hwupload,scale_vaapi=format=nv12" -start_at_zero -vsync -1 -codec:a:0 libmp3lame -ac 2 -ab 112000  -copyts -avoid_negative_ts disabled -f hls -max_delay 5000000 -hls_time 3 -individual_header_trailer 0 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/transcode/cf08c1c99b8b7058cef05d04ac737df5%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/transcode/cf08c1c99b8b7058cef05d04ac737df5.m3u8"
jellyfin    | [23:21:38] [ERR] [63] MediaBrowser.Api.Playback.Hls.DynamicHlsService: FFMpeg exited with code 1
jellyfin    | [23:21:38] [WRN] [66] MediaBrowser.Api.Playback.Hls.DynamicHlsService: cannot serve /transcode/cf08c1c99b8b7058cef05d04ac737df50.ts as transcoding quit before we got there

FFmpeg logs:
`./ffmpeg -i file:"/media/Movies/The 40 Year Old Virgin (2005).avi" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_vaapi  -b:v 4077850 -maxrate 4077850 -bufsize 8155700 -profile:v high -level 41  -force_key_frames:0 "expr:gte(t,0+n_forced*3)" -g 75 -keyint_min 75 -sc_threshold 0 -vf "format=nv12|vaapi,hwupload,scale_vaapi=format=nv12" -start_at_zero -vsync -1 -codec:a:0 libmp3lame -ac 2 -ab 112000  -copyts -avoid_negative_ts disabled -f hls -max_delay 5000000 -hls_time 3 -individual_header_trailer 0 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/transcode/cf08c1c99b8b7058cef05d04ac737df5%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/transcode/cf08c1c99b8b7058cef05d04ac737df5.m3u8"
ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --disable-doc --disable-ffplay --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-gpl --enable-version3 --enable-static --enable-libfontconfig --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libwebp --enable-libx264 --enable-libx265 --enable-libzvbi --arch=amd64 --enable-libzimg --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-vdpau --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvenc --enable-nvdec --enable-ffnvcodec --enable-libdav1d
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, avi, from 'file:/media/Movies/The 40 Year Old Virgin (2005).avi':
  Metadata:
    encoder         : VirtualDubMod 1.5.4.1 (build 2066/release)
  Duration: 02:07:08.40, start: 0.000000, bitrate: 774 kb/s
    Stream #0:0: Video: mpeg4 (Advanced Simple Profile) (XVID / 0x44495658), yuv420p, 640x360 [SAR 1:1 DAR 16:9], 652 kb/s, 25 fps, 25 tbr, 25 tbn, 25 tbc
    Stream #0:1: Audio: mp3 (U[0][0][0] / 0x0055), 44100 Hz, stereo, fltp, 112 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (mpeg4 (native) -> h264 (h264_vaapi))
  Stream #0:1 -> #0:1 (mp3 (mp3float) -> mp3 (libmp3lame))
Press [q] to stop, [?] for help
[mpeg4 @ 0x560c737c4300] Video uses a non-standard and wasteful way to store B-frames ('packed B-frames'). Consider using the mpeg4_unpack_bframes bitstream filter without encoding but stream copy to fix it.
[hwupload @ 0x560c73a4f380] A hardware device reference is required to upload frames to.
[Parsed_hwupload_1 @ 0x560c737dac40] Query format failed for 'Parsed_hwupload_1': Invalid argument
Error reinitializing filters!
Failed to inject frame into filter network: Invalid argument
Error while processing the decoded data for stream #0:0
[libmp3lame @ 0x560c737b3900] 4 frames left in the queue on closing
Conversion failed!
`

**Screenshots**

**Additional context**
there is every possibility the ffmeg logs are not showing anything useful because I just copied the command from the jellyfin logs.

**Comment by freddag** [comment]
#3631 
seems to be real issue

**Comment by nyanmisaka** [comment]
this should fix it https://github.com/jellyfin/jellyfin/pull/3615/commits/d4c6415f9908715f8cd6f90fd754d300d007c06f

**Comment by jjkalucki** [comment]
I can confirm.
Most of my movies aren't working since 10.6.0.
After adding extra parameters in front of ffmpeg command line everything works as expected, they are:
-init_hw_device vaapi=intel:/dev/dri/renderD128 -hwaccel vaapi -hwaccel_output_format vaapi -hwaccel_device intel
They are missing in the original line which is:
/usr/lib/jellyfin-ffmpeg/ffmpeg \
-filter_hw_device intel \
-i file:"/srv/storage/TVShows/abc.avi" \
-map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_vaapi \
-b:v 4850984 -maxrate 4850984 -bufsize 9701968 \
-profile:v high -level 41  -force_key_frames:0 "expr:gte(t,0+n_forced*3)" \
-g 75 -keyint_min 75 -sc_threshold 0 -vf "format=nv12|vaapi,hwupload,scale_vaapi=format=nv12" \
-start_at_zero -vsync -1 -codec:a:0 libmp3lame -ac 2 -ab 127704 \
-copyts -avoid_negative_ts disabled -f hls -max_delay 5000000 -hls_time 3 -individual_header_trailer 0 \
-hls_segment_type mpegts -start_number 0 \
-hls_segment_filename "/var/lib/jellyfin/transcodes/3866f653fc8b13ec95d039c63d615def%d.ts" \
-hls_playlist_type vod -hls_list_size 0 -y "/var/lib/jellyfin/transcodes/3866f653fc8b13ec95d039c63d615def.m3u8"

**Comment by jjkalucki** [comment]
Thank you.
