### ISSUE TITLE
Empty plugin catalog after clean 10.6 install

### ISSUE THREAD

**Issue by pkreuzt** [jellyfin/jellyfin#3619]
After a clean install (using deb repository), I have only 4 plugins: MusicBrainz, AudioDB, OMDb and TheTVDB, which I suppose are default installed. Cannot install some more using Catalog tab because it's empty. 

**System:**
 - OS: Raspbian armhf
 - Virtualization: none
 - Clients: Browser
 - Browser: Chromium 83
 - Jellyfin Version: 10.6
 - Playback: Direct Play
 - Installed Plugins:  MusicBrainz, AudioDB, OMDb and TheTVDB
 - Reverse Proxy: nginx
 - Base URL: none (but using nginx redirect as described in https://github.com/jellyfin/jellyfin/issues/1979#issuecomment-570965456 )
 - Networking: host
 - Storage: local

**To Reproduce**
1. Go to Control Panel / Advanced / Plugins
2. Click on Catalog Tab
3. See it's empty

**Expected behavior**
Should show a list of available plugins to install

**Screenshots**
![Captura de pantalla_2020-07-20_18-01-21](https://user-images.githubusercontent.com/6936840/87959361-49ce7000-caa2-11ea-8bda-db69bf6327be.png)

**Comment by crobibero** [comment]
Already fixed by https://github.com/jellyfin/jellyfin/pull/3616
For now just add the repo manually: https://repo.jellyfin.org/releases/plugin/manifest-stable.json
