### ISSUE TITLE
MusicBrainz is enabled but fails to save any metadata

### ISSUE THREAD

**Issue by joytrekker** [jellyfin/jellyfin#3623]
Running 10.6.0 on the official docker image.

I just did a fresh install and scanned my music library. MusicBrainz shows up as a metadata downloader. However after completing the initial library scan there are no artist images or MusicBrainz ids. There are no ids on the album pages or in the MusicBrainz fields when I view a tracks metadata. Enabling MusicBrainz as a metadata provider on the plugin page and doing a full metadata rescan dosn't work either.

All of my music is tagged with MusicBraiz picard and correctly showed the ids when I used Jellyfin 10.5.5.
The log does not show any info relating to musicbrainz or errors scanning as far as I can tell.

**Comment by OdinGitDat** [comment]
Same problem here, "TheAudioDB" and "Fanart" don't work either.

**Comment by crobibero** [comment]
The plugin likely isn't actually enabled. This will be fixed in 10.6.1 by https://github.com/jellyfin/jellyfin/pull/3634 and #3660

**Comment by OdinGitDat** [comment]
Ah yea the checkbox for "Enable this provider for metadata searches on artists and albums" is unchecked every time I check plugin settings.
