### ISSUE TITLE
[10.6] Could not apply migration

### ISSUE THREAD

**Issue by dbnaruto** [jellyfin/jellyfin#3625]
**Describe the bug**

After upgrading to Jellyfin 10.6, the application did not seem to start. I checked the logs (attached below) and it indicated that the `Applying migration '"MigrateUserDatabase"'` process was failing, and the application stopping and starting to tray again, looping endlessly.

The error mentioned that the XML Root element was missing. Looking at this class mentioned in the log `https://github.com/jellyfin/jellyfin/blob/master/Jellyfin.Server/Migrations/Routines/MigrateUserDb.cs` and my installation, somehow the `policy.xml` for my admin user was empty (but the file still existed), causing the marshaling process to trow an exception.

After deleting the empty `policy.xml` the application started without issue.

**System (please complete the following information):**

- **OS**: Ubuntu Mate 18.04
- **Virtualization**: none
- **Clients**: none
- **Browser**: none
- **Jellyfin Version**: 10.6.0
- **Playback**: none
- **Installed Plugins**: OpenSubtitles
- **Reverse Proxy**: nginx
- **Base URL**: none
- **Networking**: Host
- **Storage**: local

**To Reproduce**

   Start an upgraded Jellyfin instance with an empty `policy.xml` for a user.

**Expected behavior**

Jellyfin should be able to boot after upgrade and computer restart. (Maybe new process to handle empty/invalid user data .xmls?)

**Logs**

[Could_not_apply_migration.log](https://github.com/jellyfin/jellyfin/files/4949356/Could_not_apply_migration.log)

**Screenshots**

None

**Additional context**

None

**Comment by arnaudsm** [comment]
Same problem here with docker version.

**Comment by lrossouw** [comment]
Encountered same issue on Ubuntu upgrade.  The username with alphabetically first name policy.xml was empty. Deleting it let the service start.
