### ISSUE TITLE
[10.6] No admin user after migration

### ISSUE THREAD

**Issue by dbnaruto** [jellyfin/jellyfin#3628]
**Describe the bug**

Related to https://github.com/jellyfin/jellyfin/issues/3625

After resolving the issue mentioned in the above issue, my previously admin user is no longer an admin. Changes to the `policy.xml` do not seem to change the user after restarts and there I can't find any documentation on creating a new admin user from scratch.

I've seen suggestions to change the value `IsStartupWizardCompleted` in `system.xml` to `false`, but after going through the initial prompts, the only makes a new, non-admin user. (That process also seems to replace an existing user instead of making a new user, but that is not what I am concerned about right now.)

**System (please complete the following information):**
 - OS: Ubuntu Mate 18.04
 - Virtualization: none
 - Clients: Browser
 - Browser: Firefox 78 (for new user creation)
 - Jellyfin Version: 10.6.0
 - Playback: none
 - Installed Plugins: OpenSubtitles
 - Reverse Proxy: nginx
 - Base URL: none
 - Networking: Host
 - Storage: local

**To Reproduce**

1. Start an upgraded Jellyfin instance with an empty policy.xml for the only admin user.
2. Try to restore admin access or create new admin.

**Expected behavior**
Ability to create new admin user or fix current user from command line.

**Logs**
None

**Screenshots**
none

**Additional context**
none

**Comment by JonasHogman** [comment]
Workaround suggestion: You want to run sqlite3 on /var/lib/jellyfin/data/jellyfin.db, find your soon to be admin user Id in the Users table, then find a row in your Permissions table which has both that user Id as the Guid and the Kind column as 0 (as per https://github.com/jellyfin/jellyfin/blob/master/Jellyfin.Data/Enums/PermissionKind.cs, that's the admin Kind). The Value in that column should originally be 0 indicating the user isn't an admin, and you just need to change it to 1.

**Comment by cvium** [comment]
A workaround has been posted and we're now in 10.7. If it's still a widespread issue we can consider fixing it, but it doesn't seem necessary as it is right now.
