### ISSUE TITLE
Local Network Pin Number don't work in 10.6.0

### ISSUE THREAD

**Issue by Protektor-Desura** [jellyfin/jellyfin#3630]
Normally I have local pin numbers turn on and the local pin blank so I don't need to login when local. Now that doesn't work. In fact even setting the local pin per user to 1234 doesn't work. It only takes the full password to login.

**Comment by crobibero** [comment]
I can't replicate with my instance. Can you double check that Dashboard -> Networks -> LAN networks has the IP [range] you're attempting to log in from locally?

**Comment by Protektor-Desura** [comment]
Now it is working. I don't believe I had to set that before or it lost the setting when I upgraded.

**Comment by eyeson** [comment]
I also had this problem, but only on one of my jellyfin instances. One works without that setting set, the other stopped working until I set it.
