### ISSUE TITLE
HEVC on VAAPI & AMD AMF on Jellyfin 10.6.0 Docker

### ISSUE THREAD

**Issue by Protektor-Desura** [jellyfin/jellyfin#3631]
On Jellyfin 10.6.0 the render group has been fixed for /dev/dvi/renderD128 but VAAPI will not transcode HEVC because the docker does not include Mesa 20.1 or higher. I can't fix this using the last fix because you have switched the base image away from Ubuntu and over to Debian Buster which doesn't have a ppa for the newest Mesa. So you will have to compile these yourself and add the updated libraries to the docker image or switch the docker image back to Ubuntu, more specifically Ubuntu 20.04 and then let us use the PPA to upgrade the Mesa libs to at least Mesa 20.1.

If this isn't done then VAAPI and HEVC hardware transcoding will never work and AMD AMF transcoding will never work.

**Comment by Protektor-Desura** [comment]
I can verify that any codec other then HEVC works with the current setup. But the second you get HEVC involved in anyway then it breaks. H.264, MPEG2, VC1 all work without any issues.

**Comment by Protektor-Desura** [comment]
Still an issue.

**Comment by viggy96** [comment]
IMO, Jellyfin's official image should include an updated version of Mesa to aid users who use AMD instead of NVIDIA. There are users out there who refuse to buy NVIDIA products who would benefit from this.

**Comment by Protektor-Desura** [comment]
I tried to recommend that but got shot down.

**Comment by yesrod** [comment]
Bullseye is frozen; it has the newer version of Mesa needed.  Once the official Docker containers update to Bullseye, we'll be set.

**Comment by viggy96** [comment]
@yesrod That's not really a solution though. Mesa is not updated often enough in Debian stable. Debian testing might be a more suitable choice.

**Comment by viggy96** [comment]
Could we at the very least have the backports repository enabled in the image to have a more updated Mesa version?

**Comment by NCLI** [comment]
Still a huge issue.

**Comment by crobibero** [comment]
This is not an issue in 10.8

**Comment by viggy96** [comment]
Just out of curiosity, how was this issue "solved"? Because I fear that this issue will keep cropping up, until a permanent solution is found, like enabling the backports repo, or switching the Jellyfin container image back to Ubuntu, and including a repo like ppa:kisak/kisa-mesa.

**Comment by Shadowghost** [comment]
This issue was fixed by moving to bullseye as base image for the docker images. It includes the required version of mesa.

**Comment by viggy96** [comment]
Will bullseye-backports be added, so that Mesa doesn't fall to far behind in the future? And will the appropriate backports repo be added to future Jellyfin container image releases, when it's rebased onto the lastest Debian stable image for time?

**Comment by Protektor-Desura** [comment]
It would be far better to use a base of Ubuntu but for some reason they are totally opposed to it so I will continue to do my own thing instead so that I have a working solution and up to date solution at all time.

**Comment by viggy96** [comment]
@Protektor-Desura I agree it would be a _better_ solution to switch to an Ubuntu base image. Then I would include Valve's Mesa PPA, ppa:kisak/turtle.

But Debian backports repos seem like an okay solution IMO, since it looks like they're not _too_ far behind.

**Comment by viggy96** [comment]
As it stands now, this issue is going to keep cropping up, until it's fixed properly.
