### ISSUE TITLE
10.6 Unable to View Playlists Unless User Has Created One

### ISSUE THREAD

**Issue by omniusaspirer** [jellyfin/jellyfin#3636]
**Describe the bug**
Upon updating to 10.6 I noticed that I was unable to view any of my previous music playlists until creating a new playlist after the update, which then allowed me to see all my preexisting playlists. This is a regression from 10.5.5 on which a user was able to see all server playlists regardless of whether they had personally created one. 

**System (please complete the following information):**
 - OS: Ubuntu 18.04
 - Virtualization: n/a
 - Clients: All
 - Browser: All
 - Jellyfin Version: 10.6
 - Playback: n/a
 - Installed Plugins: none
 - Reverse Proxy:none
 - Base URL: none
 - Storage: local

**To Reproduce**
Create a playlist on one user, then note that playlist is not visible on another user until 2nd user creates a playlist.

**Expected behavior**
All server playlists should be visible to all users regardless of whether they have personally created a playlist (ideally playlists could optionally be flagged as public/shared but that would be a feature request).

**Logs**
n/a

**Screenshots**
n/a

**Additional context**
n/a

**Comment by crobibero** [comment]
I just tested 10.5, it looks like users without created playlists were not able to see other users' playlists.
Digging through the current code I see where playlists are being dropped, but this looks to require a much larger fix.

**Comment by omniusaspirer** [comment]
There was absolutely a change somewhere in the 10.6 update which removed the ability for users to see even their own playlists unless they create a new playlist post 10.6. Worse still, if that user deletes the new 10.6 playlist they once again lose the ability to see their own pre-10.6 playlists, thus forcing the creation of permanent dummy playlists by each user with a previous playlist or the recreation of all old playlists. 

Just one of my personal playlists contained over 1200 items, so while I could manually go through them all and force my users to do the same if a lesser quick fix to seeing a users own playlists could be implemented it would be appreciated.

**Comment by omniusaspirer** [comment]
I just recalled that the reason users were able to see playlists without creating them was because I'd put in m3u playlists which *were* visible to all users regardless of whether they'd created their own. This then allowed them to see other users playlists as well. Unfortunately the 10.6 update simply deleted any non XML playlist from the playlists directory so that workaround feels less viable after being once-bitten.

**Comment by FazeThree71** [comment]
Regarding the m3u playlists tidbit - I've always removed these from my folders so that Jellyfin would handle the playlists internally. So for me, the m3u file doesn't apply but I have the same issue.

**Comment by michaelhthomas** [comment]
Still seeing the same issue in 10.6.4. Can confirm that creating a new playlist as an affected user resolves the issue, for some reason. Using internal playlists only.

**Comment by Vodes** [comment]
Just gonna bump this and say that the same thing is also happening to me. Ubuntu 18.04, Jellyfin 10.6.4

**Comment by Shadowghost** [comment]
Will be tackled when the library db rewrite is done because playlist handling (obviously) isn't done properly in it's current implementation with the current db.

**Comment by Vodes** [comment]
Ah okay thanks for letting us know.

**Comment by Dengesiz07** [comment]
Firstly, I'm a newbee on github.

I'm using docker image jellyfin/jellyfin:latest (10.8.0). Just wanted to report that I'm having kind of similar trouble with playlists as well. 

That is; playlists work well for root user and the next user I have created for myself. However all the other users I create have the same issue. They make their first playlist, it's created with success but when they navigate to Home page then click on "Playlists" then there's this loading circle for forever. They cannot access even their own playlist.

**Comment by Back4More420** [comment]
This happens to me as well. Uninstall reinstall, removed any file location address with . in them( Lord.of.the.Rings.mp4) after they are made and show up for everyone they disappear.
Windows 10
Jellyfin Version: 10.8.9   Architecture: X64
Clients: All
Browser: All
Playback: n/a
Installed Plugins: none
Reverse Proxy:none
Base URL: none
Storage: local
The playlists are still in C:\ProgramData\Jellyfin\Server\data\playlists but wont show again until I remove them and remake playlists for every user!

**Comment by Back4More420** [comment]
Sorry Plugins was wrong I have AudioDB, Bookshelf, Cover art archive,MusicBrainz, OMDB, OPDS, opensubtitle, Reports, skin manager, studio images, TMDB, TVDB, Thanks

**Comment by Back4More420** [comment]
Sorry for so many posts. I noticed I had MANY playlists when I first installed Jellyfin so I removed 45 or so made by music m3u files in music library and the playlist finally showed up on android tv but still disappear when a scan library happens. I have a lifetime license on plex but I am done with them so when this is fixed I will be shutting down plex. This is the only thing holding me back from switching everyone to Jelly. I will donate same amount for a lifetime license to Jellyfin soon. Thanks

**Comment by Divarin** [comment]
Wow, came here to see if this was a known bug and quite surprised to see it has been open for almost 3 years.

**Comment by phatina** [comment]
Any news about this?

**Comment by phatina** [comment]
> Fixed in master by #9770 #9746 #9466 and #8526 The PRs enforce that users are only able to access their own and global playlists from the filesystem. Playlists beween users need to be explicitly shared (UI implementation of that in jellyfin-web is still pending).

I tried the mentioned workaround by creating one empty playlist and then the other shared popped up. Okay, I'll wait for an upcoming release...

**Comment by Back4More420** [comment]
My own playlist STILL disappears with a scan using 10.8.10! I read on another thread this would be fixed with new release BUT STILL BROKEN!

**Comment by Back4More420** [comment]
My own playlist STILL disappears with a scan using 10.8.10! I read on another thread this would be fixed with new release BUT STILL BROKEN! I created an empty playlist and my real playlist did a scan and the only playlist shown is the empty one!

**Comment by cvium** [comment]
Please stop. You're upset, we get it.

**Comment by Back4More420** [comment]
> Please stop. You're upset, we get it.

UM I am reporting a problem not venting.  Still broken!

**Comment by Shadowghost** [comment]
Writing in caps does imply some things...

Nonetheless I can not reproduce this behaviour on current master.

**Comment by Back4More420** [comment]
> Writing in caps does imply some things...
> 
> Nonetheless I can not reproduce this behaviour on current master.

Here is a link to a video showing it is still not working.  https://rumble.com/v2tb7wq-jellyfin-playlist-is-still-broken-after-4-years.html       
 I understand some people think you are yelling when using caps but caps can emphasize a word or phrase also.

**Comment by crobibero** [comment]
Your video shows 10.8.10, current master is 10.9.

**Comment by Back4More420** [comment]
> Your video shows 10.8.10, current master is 10.9.

Thank you. When will that be up for me to download or is this an unstable version?

**Comment by stom66** [comment]
I am also having this problem running 10.8.10.

Creating a playlist allows users to see all playlists made on the server. Removing that same playlist stops the user from being able to see any playlists at all. It appears that all users must own at least 1 playlist created since 10.6 to be able to see playlists at all.

I see 10.9 was mentioned a couple of months ago, but I cannot see where to upgrade to this latest verison - there's currently nothing under the GH releases tab and the index of releases at repo.jellyfin.org shows 10.8.10 as the latest available version.

**Comment by Shadowghost** [comment]
10.9 is work in progress (it's the `unstable` version availabe either via docker or our Debian/Ubuntu repos).
