### ISSUE TITLE
10.6 XML Playlist Not Deleted When All Tracks Removed but Unable to Add More Tracks

### ISSUE THREAD

**Issue by omniusaspirer** [jellyfin/jellyfin#3637]
**Describe the bug**
If a user creates a new playlist but removes all tracks from that playlist, the playlist will no longer be rendered in the web UI but will still exist on disk. Attempting to add a song to that playlist by name will then create a new folder/playlist instead of adding tracks to the existing XML playlist.

**System (please complete the following information):**
 - OS: Ubuntu 18.04
 - Virtualization: n/a
 - Clients: All
 - Browser: All
 - Jellyfin Version: 10.6
 - Playback: n/a
 - Installed Plugins: none
 - Reverse Proxy:none
 - Base URL: none
 - Storage: local

**To Reproduce**
Create a new playlist. Remove all songs. Note that the folder will still exist in ".../data/playlists". If the user attempts to add a song to that playlist it will create a new folder with that name and a '1' appended to allow for folder creation.

**Expected behavior**
If all songs are removed the UI should either continue to render the empty playlist and allow for proper deletion/track addition, or delete the playlist entirely from disk.

**Logs**
None generated.

**Screenshots**
n/a

**Additional context**
n/a

**Comment by anthonylavado** [comment]
Did this work previously in an older version? It's okay if you're unsure.

**Comment by omniusaspirer** [comment]
> Did this work previously in an older version? It's okay if you're unsure.

Unfortunately I'm not sure. Removing all songs from a playlist is somewhat unusual behavior, so I only uncovered this issue when trying to diagnose some other issues after this update.
