### ISSUE TITLE
IP not logged alongside failed login attempts on 10.6

### ISSUE THREAD

**Issue by amo13** [jellyfin/jellyfin#3648]
**Describe the bug**
After my update to jellyfin 10.6, the IPs are not logged any more alongside failed login attempts. Therefore my fail2ban filter can't monitor failed login attempts to jellyfin.

Earlier discussion on this was here: #1489

I hope anyone can confirm the issue I am seeing or confirm that jellyfin 10.6 should still be logging IPs. Thank you.

**System (please complete the following information):**
 - OS: archlinux
 - Jellyfin Version: 10.6.0
 - Reverse Proxy: nginx

**Log**
[2020-07-21 21:38:58.579 +02:00] [ERR] [60] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Invalid username or password entered". URL: "http://###############/Users/authenticatebyname"

**Expected Log**
[2020-07-21 21:38:58.579 +02:00] [ERR] [60] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "[12.34.56.78] Invalid username or password entered". URL: "http://###############/Users/authenticatebyname"

**Comment by crobibero** [comment]
The log line changed to 
```
[2020-07-21 16:12:05.327 -04:00] [INF] [8] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for "$username" has been denied (IP: "$IP").
```

**Comment by amo13** [comment]
> The log line changed to
> 
> ```
> [2020-07-21 16:12:05.327 -04:00] [INF] [8] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for "$username" has been denied (IP: "$IP").
> ```

You are absolutely right, thank you for pointing that out! I missed it because I saw the old log line that I used before in my fail2ban filter.

**Comment by amo13** [comment]
For whomever might be looking for this, here is my fail2ban filter file (`/etc/fail2ban/filter.d/jellyfin.conf`)
```
# Fail2Ban for jellyfin

[Definition]
datepattern = %%Y-%%m-%%d %%H:%%M:%%S(?:[.,]%%f\d*)?(?:\s*%%z)?

failregex = ^.*: Authentication request for ".*" has been denied \(IP: "<HOST>"\)

ignoreregex = ^.*\[INF\] \[\d+\] TaskManager:.*$
              Unsupported codec with id.*$
              ^.*\[INF\] \[\d+\] Emby\.Drawing\.ImageProcessor:.*$
              ^.*\[INF\] \[\d+\] LibraryMonitor.*$
              ^.*\[WRN\] \[\d+\] Emby\.Server\.Implementations\.HttpServer\.Htt$
              \sat MediaBrowser.*$
              ^.*\[ERR\] \[\d+\] MediaBrowser.MediaEncoding.*$
              \sat System.IO.*$
```

**Comment by drikqlis** [comment]
What about when wrong username is entered? I don't see anything in the logs with IP about it.

**Comment by amo13** [comment]
> What about when wrong username is entered? I don't see anything in the logs with IP about it.

I noticed that too, but I just said to myself that entering wrong user names is no security threat anyway...
