### ISSUE TITLE
collections getting deleted after library scan

### ISSUE THREAD

**Issue by scr44tch** [jellyfin/jellyfin#3650]
**Describe the bug**
I created some collections manually, after a library scan they were all gone.
i tried it multiple times

**System (please complete the following information):**
 - OS: Debian 10
 - Jellyfin Version: 10.6

**To Reproduce**

create collection manually, add movies manually, scan library, --> collections are gone

**Expected behavior**
collections not getting deleted after a library scan

**Logs**
[2020-07-21 21:52:46.493 +02:00] [DBG] [26] MediaBrowser.Controller.Entities.BaseItem: Removed item: /home/user/.config/Jellyfin/data/collections/Winter [boxset]
[2020-07-21 21:52:46.493 +02:00] [INF] [26] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "BoxSet", Name: "Winter", Path: "/home/user/.config/Jellyfin/data/collections/Winter [boxset]", Id: 1f0ca47f-10bb-e7ec-ac24-be8d7e921de8

update:

- fresh jellyfin 10.6 install via swizzin on Debian Buster
- collections were created by tmdb boxset and manually
- all fine
- update library
- collections are gone in jellyfin, but are still in the collections folder

after a library scan jellyfin collections are empty, but the collections are still available on disk.
am i the only one experiencing this?

**Comment by gdtwst** [comment]
I was running into the same issue where both my collections and playlists were being deleted after every library scan. Seems like Jellyfin will remove them from your library if your Jellyfin data directory is inside a dot folder, which seems to be related to issue #3681. I had originally set the environment variable `JELLYFIN_DATA_DIR` to `/home/jellyfin/.local/share/jellyfin` which was causing this issue. Moving the data directory outside of the dot folder and setting the variable to the new directory restored the collections and playlists on the disk and they survived library rescans.
