### ISSUE TITLE
GetImageBlurHash too slow

### ISSUE THREAD

**Issue by bocca** [jellyfin/jellyfin#3652]
**Describe the bug**
During scanning of folders full of jpg pictures, the generation of the blurred image with GetImageBlurHash uses 95% of the total scanning time. Tested with NProfiler. For each picture, it takes 3 seconds to generate de blurred image in my computer. It's so slow, and the functional gain is so small, that I think it should be considered a bug. Please, improve its performance, or at least allow to disable the generation of blurred images. I have tested to compile a modified Emby.Drawing.dll assembly removing the call to GetImageBlurHash, and the scan time improved drastically.

**System (please complete the following information):**
 - OS: Windows 10
 - Virtualization: None
 - Clients: None
 - Browser: Chrome
 - Jellyfin Version: 10.6.0
 - Playback: Not applicable
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: none
 - Networking: Not applicable
 - Storage: local

**To Reproduce**
1. Add a folder with jpeg pictures (for example, of 4600x2500 res, 5mb each aprox.)
2. Start a library scan
3. Wait to the scan

**Expected behavior**
For each image it should take less than 100 milliseconds (estimation).

**Logs**
No errors.

**Screenshots**
Not applicable.

**Additional context**
Pictures taken from different reflex cameras and edited with different image editors.

**Comment by millallo** [comment]
I experienced the same behaviour on linux too, with thousand of 6000x4000 resolution jpegs.
Is it possible to generate blurhashes from cache files instead of original ones?

**Comment by cvium** [comment]
This should be fixed already.

**Comment by BL4D35M1TH** [comment]
Still not fixed.

**Comment by cvium** [comment]
Gonna need a bit more information than that. Images are resized to max 128x128 pixels before blurhash is computed.
