### ISSUE TITLE
Watched State shows up in main view, but was never watched

### ISSUE THREAD

**Issue by misterbit-pro** [jellyfin/jellyfin#3655]
**Describe the bug**
In the main view you can see a series with state watched true so the checkmark in the corner shows up, but the show was never watched and if you got to the detailed view the state is false like it should be. This only happends if you have to libares with the same path f.E. /jellyfin/media/animes/ in the first libary in the other libary were the problem was found, I have /jellyfin/media/animes/shows as path and then there is also a /jellyfin/media/animes/movies/ were this problem does not come up.

**System:**
 - OS: Debian 10
 - Virtualization: Docker
 - Clients: Browser
 - Browser: newest Firefox stable
 - Jellyfin Version: 10.6, but happend also in 10.5.5 (I thought I will wait unitl 10.6 if the problem gets fixed)
 - Installed Plugins: Fanart, Anime, etc
 - Reverse Proxy: nginx
 - Base URL: none
 - Networking: docker network
 - Storage: HDD

**To Reproduce**
1. Go to Animes-Shows libary
2. Hover over a show or look for checkmark in the right corner
3. See error (some have it, some not)

**Expected behavior**
See watched state false as in default view

**Screenshots**
![grafik](https://user-images.githubusercontent.com/47662866/88152374-389d7480-cc04-11ea-8441-f8bd6c0b643d.png)
![grafik](https://user-images.githubusercontent.com/47662866/88152697-b1043580-cc04-11ea-9b80-ef4378888e0e.png)

**Comment by misterbit-pro** [comment]
Any comments? Can this be fixed?

**Comment by misterbit-pro** [comment]
Any updates?

**Comment by cvium** [comment]
We do not support libraries sharing folders like that unfortunately. Subject to change when the library db is rewritten, but for the foreseeable future you will simply have to split your files.
