### ISSUE TITLE
Can't access jellyfin 10.6.0 through by web client

### ISSUE THREAD

**Issue by kent79** [jellyfin/jellyfin#3656]
I just upgraded from 10.5.5 to 10.6.0 in last few days ago. Everything is ok until Today. I can't access it through by web now. The log is show "[ERR] Error processing request: "Access token is invalid or expired". ". But it is ok access though by Android client. I am using ubuntu 18.04.4. Please help me. Thanks.

**Comment by kent79** [comment]
Just reinstall browser. The issue is fixed

**Comment by Stramondroid** [comment]
> Just reinstall browser. The issue is fixed

Reinstall browser?  Like Chrome, uninstall.  Reinstall and its fixed?  Seems odd.  I will try full uninstall of JF server first.

**Comment by Stramondroid** [comment]
I have reinstalled numerous times, only to receive Error processing request. when accessing the client via any browser.

**Comment by kent79** [comment]
You may check the log first.  Is the same message like "[ERR] Error processing request: "Access token is invalid or expired" ? If the same, you can try to resintall browser.
