### ISSUE TITLE
Jellyfin docker on synology does not wrk after trying to update to latest version

### ISSUE THREAD

**Issue by CaiSter** [jellyfin/jellyfin#3658]
I tried updating my Jellyfin image on my Synology NAS using this guide below.

https://mariushosting.com/synology-how-to-update-docker-image/

However, after following the directions, I can no longer access my Jellyfin server via the browser. 
Going to 192.168.1.2:8096 no longer works. 

**System (please complete the following information):**
 - OS: [Synology Dsm]
 - Virtualization: [Docker]
 - Clients: [Browser.]
 - Browser: [Firefox]
 - Jellyfin Version: [10.6.0]

**Comment by Artiume** [comment]
What do your logs say

**Comment by CaiSter** [comment]
`Here is the log. 

[jellyfin logs.txt](https://github.com/jellyfin/jellyfin/files/4963006/jellyfin.logs.txt)
`
I also saw this post on reddit. [https://www.reddit.com/r/jellyfin/comments/huct4x/jellyfin_1060_released/fymkf4q/](url), but I checked my system.xml file and i already had remote access set as "true".

**Comment by crobibero** [comment]
At this point in the log Jellyfin hasn't completed startup.
