### ISSUE TITLE
Notifications Aren't Enabled Upon Server Restart

### ISSUE THREAD

**Issue by bbalz** [jellyfin/jellyfin#3661]
**Describe the bug**
When you enabled notifications, save them they work but when you restart the Jellyfin server those notifications are no longer disabled and you must go back in and enabled them.

**System (please complete the following information):**
 - OS: Windows
 - Virtualization: N/A
 - Clients: Browser
 - Browser: Brave Version 1.11.97 Chromium: 84.0.4147.89 (Official Build) (64-bit)
 - Jellyfin Version: 10.6
 - Playback: 
 - Installed Plugins: X
 - Reverse Proxy: X
 - Base URL: X
 - Networking: X
 - Storage: X

**To Reproduce**

1. Go to notifications
2. Enabled notification you want
3. Save
4. Restart Jellyfin server
5. Check notifications to see the ones you enabled, saved to see that they are now not enabled.

**Expected behavior**
Notifications to remain enabled upon a server restart.

**Logs**

**Screenshots**

**Additional context**

**Comment by crobibero** [comment]
Fixed by #3552

**Comment by bbalz** [comment]
Fixed by #3552
