### ISSUE TITLE
Apache Virtual Host with Reverse Proxy breaks syncplay

### ISSUE THREAD

**Issue by CountMurphy** [jellyfin/jellyfin#3662]
**Describe the bug**
If I start syncplay on my local network with localIp:8096 it works fine. 
If I start syncplay over subdomain link (jellyfin.dnsName.com) all I can do is create groups, but nothing can join them. I've been using this setup with apache on Jellyfin since the project began without issue.

**System (please complete the following information):**
 - OS: Arch Linux
 - Virtualization: None
 - Clients: Browser
 - Browser: Firefox 78, Chromium 84
 - Jellyfin Version: 10.6
 - Playback: Direct Play
 - Installed Plugins: none
 - Reverse Proxy:apache
 - Base URL: none
 - Networking: Host
 - Storage: local

**To Reproduce**

1. Go to library
2. Click on media to play
3. Click Syncplay button
4. Click create group
5. On client machine: click syncplay
6. On Client machine: click group. Nothing happens

**Expected behavior**
Client machine should start playing synced media

**Logs**
Zero Errors in log about syncplay. Only entries are "Leave Group"

**Comment by crobibero** [comment]
Please make sure your apache config has websockets: https://jellyfin.org/docs/general/networking/apache.html

**Comment by CountMurphy** [comment]
Yup, that was the problem. Thank you!
