### ISSUE TITLE
Jellyfin treats 1080 as the episode number if the title includes 1080p

### ISSUE THREAD

**Issue by Starmann** [jellyfin/jellyfin#3669]
**Describe the bug**

**System (please complete the following information):**
 - OS: Windows 10 64bit Education
 - Virtualization: None
 - Clients: Browser (though it doesn't matter)
 - Browser: Firefox 78
 - Jellyfin Version: 10.6.0
 - Playback: Direct Stream
 - Installed Plugins: Anime
 - Reverse Proxy: None
 - Base URL: /web/index.html#!/details
 - Networking: localhost
 - Storage: HDD

**To Reproduce**

1. Create a new video, or download one. Give it an episode number followed by 1080p. My title was "[ZetaRebel] Mobile Suit Gundam - 01 - Gundam Rising!! (BD x264 1080p 8-bit FLAC)"
2. Open Jellyfin
3. Look at the episode number
4. It will be 1080

**Expected behavior**
I expect the episode number to be 1.

**Logs**
No error message, just some incorrect parsing.

**Screenshots**

I think my explanation was clear enough but here's a screenshot just in case it'll help

![](https://cdn.discordapp.com/attachments/735650534207258715/735668485698617384/unknown.png)

**Additional context**

I feel like the code for parsing titles is the weakest part of Jellyfin. As a stopgap solution, I'd love a configuration option for defining a show's episode naming format. Adding a show is one of the first things people do, and thus should be a more polished experience. While parsing titles is a hard problem to solve, I feel like most title problems could be ignored by the default format discarding anything in brackets or parenthesis as those are often used for metadata.

**Comment by Bond-009** [comment]
Can you give the full path of the file?

**Comment by whalehub** [comment]
@Starmann All the major media server applications (Plex, Emby, Jellyfin) expect you to name your files properly. In this case, the file should be called:

`Mobile Suit Gundam (1979) - S01E01 - Gundam Rising!! (BD x264 1080p 8-bit FLAC)`

**Comment by Starmann** [comment]
@Bond-009 `E:\Movies\[ZetaRebel] Mobile Suit Gundam (BD x264 1080p 8-bit FLAC)\[ZetaRebel] Mobile Suit Gundam - 01 - Gundam Rising!! (BD x264 1080p 8-bit FLAC).mkv`

**Comment by Starmann** [comment]
@whalehub I wasn't aware of that. I feel like there should be a tool to help you rename them properly.

**Comment by Bond-009** [comment]
Just changing the path to `E:\Movies\[ZetaRebel] Mobile Suit Gundam\[ZetaRebel] Mobile Suit Gundam - 01 - Gundam Rising!! (BD x264 1080p 8-bit FLAC).mkv`
should do the trick

**Comment by whalehub** [comment]
@Starmann There are a few different tools you can use for that purpose. The one I personally use and can recommend is a free one called [TV Rename](https://www.tvrename.com/) (GitHub: https://github.com/TV-Rename/tvrename). Another popular option is FileBot, but that's a paid product.

**Comment by shincurry** [comment]
+1

Almost all my anime files, the episode number will be recognized as 1080, so it is not convenient to automatically download the correct metadata from MovieDB or TVDB.

Maybe can refer to this project https://github.com/soruly/aniep to implement an algorithm for identifying the episode number from anime filename.

Or provider a tool to automatically set the incremental episode number according to the file name alphabeta order.

**Comment by whalehub** [comment]
> Or provider a tool to automatically set the incremental episode number according to the file name alphabeta order.

@shincurry You can do that with something like [Bulk Rename Utility](https://www.bulkrenameutility.co.uk).

**Comment by kerberjg** [comment]
I can do you one better, my movies’ year often gets recognized as “1920”
