### ISSUE TITLE
Plugins catalog

### ISSUE THREAD

**Issue by iNfRaSoNiC13** [jellyfin/jellyfin#3670]
Hello,
I have a problem with the latest build 10.6.0 when clicking on Plugins Catalog I got this message "No available plugins." 
And I can't install plugins!
WIndows user.

**Comment by ppcdubai** [comment]
I'm having a similar problem on Ubuntu with Docker (I'm running Linuxserver/jellyfin) 
I can see the Plugin library, but when I go to catalogue it just loads forever. Nothing in the logs about the catalogue, there are only log entries for HTTP get requests for installed plugins.

**Comment by Havokdan** [comment]
I managed to solve the problem thanks to a tip I saw on Jellyfin's reddit, just adding the official repository manually, the address is https://repo.jellyfin.org/releases/plugin/manifest-stable.json

**Comment by pedro-rivero** [comment]
Running 10.6.0 on linux arm (a raspberry pi 4).
Same issue as iNfRaSoNiC13, "no available plugins", and when trying to use Havokdan solution I get ppcdubai problem, the plugin catalog just loads forever

**Comment by oshura3** [comment]
> I managed to solve the problem thanks to a tip I saw on Jellyfin's reddit, just adding the official repository manually, the address is https://repo.jellyfin.org/releases/plugin/manifest-stable.json and restarting the application.
> I use in Windows 10 x64.

This solved the issue for me. Thanks @Havokdan

**Comment by lunarnexus** [comment]
I'm having the same issue.  "No available plugins".  After adding the repo and restarting the server, it still doesn't populate the list under "catalog".  I'm using the linuxserver/jellyfin docker image.

**Comment by Havokdan** [comment]
Another detail, at least for those who use windows, is that I also had to redo the installation of Jellyfin to the root of the hd, because some plugins and functions were not working correctly when installing in folders that require administrative permissions.

**Comment by pkreuzt** [comment]
Plugin catalog still empty with Jellyfin 10.6.1. At least for my deb installed armhf version.

**Comment by crobibero** [comment]
For those still having issues, do you have anything under repositories?

**Comment by radriaanse** [comment]
Not sure if helpful, but after the 10.6.1 update it's working again here on x86 Arch Linux.
The logs show this on first restart:

```
Jul 29 21:26:49 hostname jellyfin[111484]: [21:26:49] [INF] [1] Jellyfin.Server.Migrations.MigrationRunner: Applying migration 'ReaddDefaultPluginRepository'
```

**Comment by C0sm1x** [comment]
I added the repo, restarted, and still nothing. :(

**Comment by flatline-studios** [comment]
Using the `linuxserver/jellyfin` docker image. Just trying to install the `Kodi Sync Queue` plugin led to a never ending loading wheel.

To resolve it:

1. Navigate to: Dashboard -> [Advanced] Plugins -> [Top Tabs] Repositories
2. Delete the Jellyfin Stable repository that's there, it seems to be broken.
3. Add a new repository. Name it whatever, `Jellyfin Fixed`, for example, and input: `https://repo.jellyfin.org/releases/plugin/manifest-stable.json` as the `Repository URL`.
4. Restart the docker container, `docker container restart jellyfin`, replacing jellyfin with the container name your container has.
5. Wait for it to restart...
6. Navigate to: Dashboard -> [Advanced] Plugins -> [Top Tabs] Catalogue
7. Install whatever plugin(s) you want. `Kodi Sync Queue`, for example.
8. Repeat step 4 and 5.
9. Navigate to: Dashboard -> [Advanced] Plugins -> [Top Tabs] My Plugins.
10. Your newly installed plugin(s) should be there, and able to be configured (if said plugin has a configuration).

Not sure why the original repository that comes with the image doesn't seem to work though.

**Comment by GAPPSRefusenik** [comment]
Issue persists with version 10.6.4 on Windows x64. I tried reinstalling to root folder C:\ and starting the Tray application with administrative privileges. I manually deleted and added the stable repo. Still it shows no plugins available.

**Comment by taskhawk** [comment]
Still happening for me too. Ubuntu 20.04, Jellyfin 10.8.12, installed through apt.

I've tried the solutions mentioned in this issue but the Catalog tab is still stuck loading forever.

**Comment by zQueal** [comment]
Still happening.

**Comment by redplusblue** [comment]
@flatline-studios's solution worked for me, catalog shows up. Just replaced `<jellyfin>` in `docker container restart <jellyfin>`  with the container id for jellyfin, which I found by using `docker ps -a`. 

> Using the `linuxserver/jellyfin` docker image. Just trying to install the `Kodi Sync Queue` plugin led to a never ending loading wheel.
> 
> To resolve it:
> 
>     1. Navigate to: Dashboard -> [Advanced] Plugins -> [Top Tabs] Repositories
> 
>     2. Delete the Jellyfin Stable repository that's there, it seems to be broken.
> 
>     3. Add a new repository. Name it whatever, `Jellyfin Fixed`, for example, and input: `https://repo.jellyfin.org/releases/plugin/manifest-stable.json` as the `Repository URL`.
> 
>     4. Restart the docker container, `docker container restart jellyfin`, replacing `jellyfin` with the container name your container has.
> 
>     5. Wait for it to restart...
> 
>     6. Navigate to: Dashboard -> [Advanced] Plugins -> [Top Tabs] Catalogue
> 
>     7. Install whatever plugin(s) you want. `Kodi Sync Queue`, for example.
> 
>     8. Repeat step 4 and 5.
> 
>     9. Navigate to: Dashboard -> [Advanced] Plugins -> [Top Tabs] My Plugins.
> 
>     10. Your newly installed plugin(s) should be there, and able to be configured (if said plugin has a configuration).
> 
> 
> Not sure why the original repository that comes with the image doesn't seem to work though.
