### ISSUE TITLE
Enable blurred placeholders for images

### ISSUE THREAD

**Issue by iNfRaSoNiC13** [jellyfin/jellyfin#3672]
Hello,
with the new version I get a 3-5 seconds refresh of all images in my library, using "Enable blurred placeholders for images"
When I disable it (as intended) the images are  not showing for several seconds.
This was not the case with 10.5.0. Is there a way to prevent this from happening? Thank you for your hard work.

**Comment by ferferga** [comment]
@iNfRaSoNiC13 Hello. I guess that's because they aren't downloaded yet. It's that what you mean?

Otherwise, detail the issue a little bit more, please.
