### ISSUE TITLE
NFO Reader/Writer Doesn't Process All Roles

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin#3686]
**Describe the bug**
As reported on [the forums](https://forum.jellyfin.org/t/metadata-getting-overwritten/2456/19), the NFO Reader/Writer is clobbering metadata that is valid.
Part of this is the fact that it doesn't handle entries for crew properly (such as producer, composer). When reading these in, it treats them as "actor" since it doesn't have person types for those other positions. When it writes back, it adds a second entry for them as an actor, and thus modifies the user's correct info on disk.

**System (please complete the following information):**
 - Jellyfin Version: Verified on 10.5.5, and continues with 10.6.0

**To Reproduce**
* Disable all external metadata providers.
* Add media matching the example NFO provided here: https://forum.jellyfin.org/t/metadata-getting-overwritten/2456/16?u=anthonylavado
* Perform a refresh of the library to pick up this new media.
* Observe the NFO content is modified.

**Expected behavior**
Jellyfin should respect the data in the NFO if it is provided, and handle the additional information correctly. The controls for reading/writing NFO should be split and made clearer. I'll make a new issue for that.

**Additional context**
I know NFOs are just text files, but if there is a spec of some kind, we should look to fully support it.

**Comment by Artiume** [comment]
>Disable all external metadata providers.'

We should add a metadata priority for NFO so we dont have to disable metadata providers.

**Comment by timo95** [comment]
> We should add a metadata priority for NFO so we dont have to disable metadata providers.

https://features.jellyfin.org/posts/745/make-nfo-an-adjustable-metadata-provider
