### ISSUE TITLE
Jellyfin recognizes all but one episode in series.

### ISSUE THREAD

**Issue by wfdewith** [jellyfin/jellyfin#3688]
**Describe the bug**
Jellyfin does not recognize `tv/Chuck/Season 3/Chuck - S03E06 - Chuck Versus the Nacho Sampler - [HDTV-1080P][AC3 5.1][X265].mkv` but it does recognize `tv/Chuck/Season 3/Chuck S03E06.mkv`.
This is the only episode in the entire series with that problem. For example, `tv/Chuck/Season 3/Chuck - S03E05 - Chuck Versus First Class - [HDTV-1080P][AC3 5.1][X265].mkv` works fine.

**System:**
 - OS: Debian
 - Virtualization: Docker
 - Clients: Multiple
 - Jellyfin Version: 10.6.0
 - Storage: CIFS Docker volume

**Logs**
N/A

**Comment by cvium** [comment]
Cannot reproduce in 10.7. If it persists we'll need more information such as enabled providers, debug logs and general folder structure.
