### ISSUE TITLE
[10.6] Jellyfin Transcodes AAC to MP3 on Chromium

### ISSUE THREAD

**Issue by mirolm** [jellyfin/jellyfin#3689]
**Describe the bug**

In previous version 10.5.5 I was watching series encoded by [HorribleSubs] using DirectPlay - both video and audio was directly streamed. With 10.6 video is directly streamed, but audio is decoded from AAC to MP3.

**System (please complete the following information):**
 - OS: Debian Buster
 - Virtualization: none
 - Clients: Browser
 - Browser: Chromium 84.0.4147.89 (Official Build) Arch Linux (64-bit)
 - Jellyfin Version: 10.6.0
 - Playback: Direct Stream 
 - Installed Plugins: Anime
 - Reverse Proxy: nginx
 - Base URL: none
 - Networking: Host
 - Storage: local

**To Reproduce**

1. Start to play a video encoded from [HorribleSubs]
2. Click on Playback Data
3. Video us played with DirectStream instead of Direcplay.

**Expected behavior**

Such videos should play with DirectPlay as they was in 10.5.5

**Logs**

[jellyfin20200724.txt](https://github.com/jellyfin/jellyfin/files/4973614/jellyfin20200724.txt)
[ffmpeg-directstream-13e94a3d-0967-46ab-b74f-f96866f866dc.txt](https://github.com/jellyfin/jellyfin/files/4973616/ffmpeg-directstream-13e94a3d-0967-46ab-b74f-f96866f866dc.txt)

**Screenshots**

![image](https://user-images.githubusercontent.com/9135358/88421484-53810c00-cdf1-11ea-8f23-116eeea5750a.png)

**Additional context**

none.

**Comment by shirt-dev** [comment]
This is an issue for me as well

**Comment by nyanmisaka** [comment]
It should be fixed in 10.7.

**Comment by SenorSmartyPants** [comment]
Since 10.7 RC1 was coming out I finally decided to upgrade my 10.5.5 install to 10.6.4. Trying to keep things nice and stable for the family viewing. And this is the first issue I noticed.

I'm curious to know which change fixes this issue.

Thanks for all the work. Love the Jellyfin.

**Comment by nyanmisaka** [comment]
https://github.com/jellyfin/jellyfin/pull/4405 ;)

**Comment by brianjmurrell** [comment]
> It should be fixed in 10.7.

Will this fix the problem of a video that has both ac3 and aac not transcoding the ac3 to mp3?  Or is the selection of a supported audio stream from multiple audio streams a different issue?

**Comment by nyanmisaka** [comment]
Unfortunately the html video player `hls.js` we use doesn't support AC3.

**Comment by brianjmurrell** [comment]
@nyanmisaka If you are replying to [my comment](https://github.com/jellyfin/jellyfin/issues/3689#issuecomment-755289875) then you have **completely** missed the point.

That media file has **both** AC3 and AAC audio streams in it.  Shouldn't Jellyfin be playing the AAC audio stream directly instead of transcoding the AC3 to mp3?

**Comment by nyanmisaka** [comment]
IIRC only Edge supports AC3 playback.

**Comment by shirt-dev** [comment]
Doesn't the client have an option to select audio tracks?

**Comment by nyanmisaka** [comment]
> Doesn't the client have an option to select audio tracks?

Sure it does. Both audio and subtitle tracks can be selected.
To avoid AC3 transcoding I think using android client with exoplayer or external player is a better choice.

**Comment by brianjmurrell** [comment]
> IIRC only Edge supports AC3 playback.

Again, the point is that the media file has **both** an AC3 and AAC track.

**Comment by brianjmurrell** [comment]
> using android client with exoplayer or external player is a better choice.

On Chome on Linux?

**Comment by brianjmurrell** [comment]
So, while there is a selector (now?  when did this show up):

![image](https://user-images.githubusercontent.com/559317/120716658-5b3f2180-c494-11eb-98c0-4b131b1dc961.png)

(that both say Default, BTW) to be able to choose a track that won't incur transcoding, couldn't/shouldn't this selection be automated by determining the available hardware/capabilities on the playback device and automatically selecting an audio track that matches the capabilities and doesn't need transcoding?
