### ISSUE TITLE
If Jellyfin is installed to a path with spaces (Like "C:\Program Files\..." transcoding will fail when trying to run ffmepeg

### ISSUE THREAD

**Issue by hunterwerlla** [jellyfin/jellyfin#3695]
**Describe the bug**
If Jellyfin is installed to a path with spaces (Like "C:\Program Files\..." encoding will fail when trying to run ffmpeg, reporting "FFMpeg exited with code 1". Attempting to run the command it spits out will also fail because the path to ffmpeg is unquoted. Moving the install to a path without spaces fixes transcoding.

**System (please complete the following information):**
 - OS: Windows
 - Virtualization: None
 - Clients: [Browser, Android, Fire Stick, etc.]
 - Browser: [e.g. Firefox 72, Chrome 80, Safari 13]
 - Jellyfin Version: 10.6.0

**To Reproduce**

1. Install Jellyfin to the default path
2. Try to do something that requires transcoding, like casting to a chromecast device with ass subs

**Expected behavior**
Transcoding will work.

**Logs**
I did not save them

**Comment by BaronGreenback** [comment]
![image](https://user-images.githubusercontent.com/22121540/88455301-30477280-ce6c-11ea-88f0-5b3d1a4c0db3.png)

My path has a space in it, and I have no issue.

You say ffmpeg exits with error code 1 - this means that that it is actually running - so discounts a path issue, but points to a command line argument issue.

Could really do with logs to investigate further.
