### ISSUE TITLE
Notification settings are not preserved after server restart for 10.6.0

### ISSUE THREAD

**Issue by lldsolitude** [jellyfin/jellyfin#3698]
After upgrading to 10.6.0, notification settings are not preserved after server restart. I have to enable "new content added" notification every time after jellyfin server restarts.

Jellyfin version: 10.6.0.
OS: Debian 10.

**Comment by BaronGreenback** [comment]
Should be fixed with https://github.com/jellyfin/jellyfin/pull/3552
