### ISSUE TITLE
Build alternative to emby plugin store

### ISSUE THREAD

**Issue by LeoVerto** [jellyfin/jellyfin#37]
Removing all connections to emby.media has broken the plugin installation system. We should either launch or own one or come up with an alternative, perhaps more manual plugin installation method.

**Comment by DeftNerd** [comment]
Manual plugin installation is good, but so is the ability to manually add new stores. 

It could be as simple as RSS feeds that allow publishing of plugin updates. This will allow any default store to be clear of any controversial plugins, but people can add feeds for other plugins.

In theory, the plugin store interface would just merge all the configured plugin feed results to give a unified list.

Plugins should be able to be categorized by the feed author and have info like plugin DL links (support multiple links, with different protocols like http, https, ftp, etc), version number, date of update, an update channel (production, beta, alpha), changelog info, plugin description, thumbnail links and their dimensions, and DL counts.

It might be worth considering allowing plugin feeds to publish a HTTP PUT URL for some kind of voting or review  mechanism.

If a user installs a CSPAN viewer plugin, they should be able to leave feedback or upvite the plugin. This could allow users to sort the merged plugin store interface by ratings or popularity.

I could dive into this and come up with a simple spec and implementation if you want.

**Comment by JustAMan** [comment]
One of easiest starts could be taking releases from github (for plugins, that is).
This way, "one plugin - one github repo" approach could be used.

**Comment by nvllsvm** [comment]
In addition to the still existing repositories, I also have local copies of the following repositories with the latest code before the were deleted.

- MediaBrowser/Dropbox
- MediaBrowser/GoogleDrive
- MediaBrowser/IMVDb
- MediaBrowser/Lastfm
- MediaBrowser/MovieDb
- MediaBrowser/PodCasts
- MediaBrowser/SubDb
- MediaBrowser/cordova-chromecast
- MediaBrowser/cordova-chromecast-ios

Trying to figure automations to push them to the emby-mirror org.

**Comment by joshuaboniface** [comment]
@nvllsvm I think I got a bunch of those, are any more missing? That just means the last step is setting up a manifest.

**Comment by anthonylavado** [comment]
tagging #259

**Comment by anthonylavado** [comment]
Closing as most requirements now satisfied.
