### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by htttito** [jellyfin/jellyfin#3713]
Hi!

The language is always English.
If you safe your language in userprofil, or somewhere...
Browser: Firefox
System: Ubuntu 18.04/20.04
Jellyfin: Last Version

PS.: I love jellyfin...I only want to help killing errors... :-)

**Comment by crobibero** [comment]
I'm not sure what you're asking? I just changed my display language from Auto to Danish, and after a refresh everything was displayed in Danish

**Comment by xyx208** [comment]
i think  he want to say:my display language set auto is not work?

**Comment by htttito** [comment]
Hi! I solved the Problem. Firefox language was wrong ...de-at. Now i changed it to de-de and everything was OK...

**Comment by zzc-tongji** [comment]
I have met the same problem in version 10.6.0. I change `Dashboard > General > Preferred display language` to `Chinese Simplified` but not work.

**Comment by zzc-tongji** [comment]
Could someone reopen this issue? (or I will create a new one.)

**Comment by crobibero** [comment]
> 
> 
> I have met the same problem in version 10.6.0 on Docker. I change `Dashboard > General > Preferred display language` to `Chinese Simplified` but not work.

I just tested with my local install and it seems to be working. Make sure you refresh the browser after saving.

![image](https://user-images.githubusercontent.com/24963659/88686412-4ba4be80-d0b4-11ea-937a-04c9b435cc27.png)

**Comment by zzc-tongji** [comment]
I got it. Jellyfin saves the language setting in browser cookies rather than server itself, so refreshing is required. Thanks.

**Comment by snowe2010** [comment]
Wait, so is there no way to force it to always be English? I've got one movie with German audio set as the default for some reason and am unable to watch on Roku due to it defaulting to German. There's no way to change the audio stream on Roku, and I have my preferred language set as English, yet it still continues to use German.
