### ISSUE TITLE
Artists disappear when not exactly matching folder structure

### ISSUE THREAD

**Issue by seaeagle1** [jellyfin/jellyfin#3729]
Not sure if there's a bug here or lack of documentation, but after two days I figured out why some artists were missing from my library.

**Steps**
Import music files in disk/artist/album/track - name.mp3 makeup
Change display name of artist (either manually or through metadata scan/download)
Artist disappears from artist overview (both new and old name)
Naming artist back to exact folder name (and locking it to prevent automatic change) recovers situation

**Background**
I have been importing my music files from my Mezzmo server, which pretty much ignores file structure and indexes entirely based on metadata tags (and has some of the best 'smart playlists' btw), so may have been biased by working that way.
In naming my files I typically remove special characters from the filenames to avoid trouble on less fancy filesystems. Jellyfin recovers these during the metadata scan, which causes a mismatch between the metadata and filesystem. From what I gather, it does create a virtual artist with the correct name, and somehow either the two artist entities get in conflict, or the music files get attached to the invisible one. Files are discoverable as tracks or albums.

**Potential solution**
Imho this either needs good documentation and/or a big warning on editing artist names, or the internal connection between artist and music files should be made based on id/location instead of name.

**Comment by seaeagle1** [comment]
After some further messing around, it seems that the metadata scan renames the Artist object, but not the Artist metadata on the songs, which causes the song and artist to lose their connection (and disappear, since the correctly-named artist does no longer have any songs, while there's no artist object for the wrongly-tagged songs). This still is a bit confusing behaviour, but seems to make more sense library-wise.

**Comment by n-buck** [comment]
Hi
I'm not 100% sure if it is the same issue, but my Artists with any special-characters (like Tiësto or Queensrÿche) have disappeared too.
I haven't renamed anything, tough. Just re-scanned the library. But I'm also not 100% sure if the artists have ever existed as they should.

It seems to work now, tough.
What I did:

- Updated Jellyfin-image to newest version
- Rescanned all metadata of the artist in question (I think this fixed it)

The log looked like this:


> [2020-08-09 01:13:42.279 +00:00] [INF] [979] App: Deleting dead "b6ec788257f02c22b59ad9ae4c880b6e" "DJ TiÃ«sto" "MusicArtist".
 [2020-08-09 01:13:42.279 +00:00] [INF] [979] LibraryManager: Deleting item, Type: "MusicArtist", Name: "DJ TiÃ«sto", Path: "/config/metadata/artists/DJ TiÃ«sto", Id: b6ec7882-57f0-2c22-b59a-d9ae4c880b6e
[2020-08-09 01:13:42.282 +00:00] [INF] [979] App: Deleting dead "06a16a5a2c817885750a89f9f888f77b" "Dani KÃ¶nig" "MusicArtist".
