### ISSUE TITLE
Can't read certain FLAC files

### ISSUE THREAD

**Issue by Jerroder** [jellyfin/jellyfin#3731]
**Describe the bug**
I can play all of my FLAC music but I have one album for which I get :
````
Playback Error
This client isn't compatible with the media and the server isn't sending a compatible media format.
````

**System (please complete the following information):**
 - OS: Debian 10
 - Virtualization: KVM
 - Clients: Browser
 - Browser: Firefox 78.1.0esr
 - Jellyfin Version: 10.6.1 but also present in 10.5
 - Playback: Direct Play I believe
 - Installed Plugins: none,
 - Reverse Proxy: none
 - Base URL: none
 - Networking: LAN
 - Storage: local

**Logs**
````
[2020-07-28 15:44:07.497 +02:00] [INF] GetPostedPlaybackInfo profile: DeviceProfile { Name: null, Id: null, Identification: null, FriendlyName: null, Manufacturer: null, ManufacturerUrl: null, ModelName: null, ModelDescription: null, ModelNumber: null, ModelUrl: null, SerialNumber: null, EnableAlbumArtInDidl: False, EnableSingleAlbumArtLimit: False, EnableSingleSubtitleLimit: False, SupportedMediaTypes: "Audio,Photo,Video", UserId: null, AlbumArtPn: null, MaxAlbumArtWidth: 0, MaxAlbumArtHeight: 0, MaxIconWidth: null, MaxIconHeight: null, MaxStreamingBitrate: 8000000, MaxStaticBitrate: 8000000, MusicStreamingTranscodingBitrate: 128000, MaxStaticMusicBitrate: null, SonyAggregationFlags: null, ProtocolInfo: null, TimelineOffsetSeconds: 0, RequiresPlainVideoItems: False, RequiresPlainFolders: False, EnableMSMediaReceiverRegistrar: False, IgnoreTranscodeByteRangeRequests: False, XmlRootAttributes: [], DirectPlayProfiles: [DirectPlayProfile { Container: "opus", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "mp3", AudioCodec: "mp3", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "aac", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "m4a", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "m4b", AudioCodec: "aac", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "flac", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "webma", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "webm", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "wav", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "ogg", AudioCodec: null, VideoCodec: null, Type: Audio }], TranscodingProfiles: [TranscodingProfile { Container: "ts", Type: Audio, VideoCodec: null, AudioCodec: "aac", Protocol: "hls", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: null, MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }], ContainerProfiles: [], CodecProfiles: [], ResponseProfiles: [], SubtitleProfiles: [] }
[2020-07-28 15:44:07.506 +02:00] [INF] User policy for "user". EnableAudioPlaybackTranscoding: True
[2020-07-28 15:44:07.506 +02:00] [INF] RemoteClientBitrateLimit: 700000000, RemoteIp: "xx.xx.xx.xx", IsInLocalNetwork: True
````

**Additional context**
I passed two different FLAC files (one that works, one that doesn't) through MediaInfo to check if it was a codec or bitrate issue or whatever but they seem identical. The one that works:
````
Format                                   : FLAC
Format/Info                              : Free Lossless Audio Codec
Duration                                 : 6 min 35 s
Bit rate mode                            : Variable
Bit rate                                 : 860 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 44.1 kHz
Bit depth                                : 16 bits
Compression mode                         : Lossless
Stream size                              : 40.6 MiB (99%)
Writing library                          : libFLAC 1.3.2 (UTC 2017-01-01)
````

The one that doesn't:
````
Format                                   : FLAC
Format/Info                              : Free Lossless Audio Codec
Duration                                 : 3 min 46 s
Bit rate mode                            : Variable
Bit rate                                 : 871 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 44.1 kHz
Bit depth                                : 16 bits
Compression mode                         : Lossless
Stream size                              : 23.5 MiB (93%)
Writing library                          : libFLAC 1.2.1 (UTC 2007-09-17)
````

**Comment by neteroster** [comment]
I also met the problem and I found that after clearing the cover of the FLAC file, it can be played properly.

**Comment by rderensy** [comment]
I suspect that the writing library is too old (2007). Re-encoding the file with ffmpeg and `-c:a flac` has solved this.

**Comment by Salamandar** [comment]
Same issue here. Also, the logs pointed to an artwork issue, and clearing the cover in the audio metadata solved the issue. Here are 2 images, one that works one that doesn't.
![Maximum Overload_doeswork](https://user-images.githubusercontent.com/6552989/106486554-0ec9e200-64b2-11eb-853a-3a78a1ffe54f.jpg)
![Ultra Beatdown_doesnotwork](https://user-images.githubusercontent.com/6552989/106486560-112c3c00-64b2-11eb-88df-f64263385b75.jpg)

**Comment by rderensy** [comment]
Good thing you bring this up, I just checked and after re-encoding with ffmpeg with `-c:a copy`, the pixel format went from yuvj420p (for the non-working file) to rgb24 (for the same file, re-encoded) so I guess that is the problem since nothing else changed.

**Comment by Salamandar** [comment]
@rderensy The image is not the issue here. I have 2 files with the SAME `metaflac --list` output, but one is working (edited with easytag) the other is not.

**Comment by rderensy** [comment]
Issue still occurring with Firefox ESR 78.11.0 and Jellyfin 10.7.5. It works when reading the file with the windows desktop app, iOS app and Brave (chromium based) though, only Firefox is broken.

**Comment by Salamandar** [comment]
Yeah, still occurs. Editing the metadatas solves the issue so i batch-edited all my flac files but... that's not a solution.

**Comment by rderensy** [comment]
Still happening on Firefox 91.1.0esr

**Comment by elnicko** [comment]
I can confirm the issue on 0.40.0-FREEBSD (8799358).

Before re-encoding the images in the files (added by Easytag) are reported as "mjpeg (Baseline), yuvj420p":
```
ffprobe 1.flac
  ...
  ...
  Stream #0:0: Audio: flac, 44100 Hz, stereo, s16
  Stream #0:1: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 793x793 [SAR 1:1 DAR 1:1], 90k tbr, 90k tbn, 90k tbc (attached pic)
```
I'm using the following command to re-encode:
```
ffmpeg -i '1.flac' -c:a flac -compression_level 12 '2.flac'
``` 
After re-encoding images get reported as "png, rgb24(pc)":
```
ffprobe 1.flac
  ...
  ...
  Stream #0:0: Audio: flac, 44100 Hz, stereo, s16
  Stream #0:1: Video: png, rgb24(pc), 793x793 [SAR 1:1 DAR 1:1], 90k tbr, 90k tbn, 90k tbc (attached pic)
```

**Comment by seanbruno** [comment]
I just ran into this today on FreeBSD 102.0 (64-bit).  Re-encoding the FLAC files in question does indeed resolve the issue for me.  I have posted a "broken" file [here](https://people.freebsd.org/~sbruno/john_lee_hooker-baby_lee_with_robert_cray.flac) for anyone who wants to try and debug/patch further.

**Comment by thornbill** [comment]
Checking that sample, I see

```
Audio file with ID3 version 2.3.0, contains:FLAC audio bitstream data, 16 bit, stereo, 44.1 kHz, 9963660 samples
```

ID3 tags are not supported by the FLAC spec. Most players seem to just ignore them, but Firefox will not play files that contain them.

**Comment by AngelPone** [comment]
Same issue. I fixed it by changing the webp artwork to jpg.

**Comment by IrmatDen** [comment]
> Same issue. I fixed it by changing the webp artwork to jpg.
Thank a lot for posting this!

**Comment by Bond-009** [comment]
@holotone  see @thornbill response
> ID3 tags are not supported by the FLAC spec. Most players seem to just ignore them, but Firefox will not play files that contain them.

**Comment by holotone** [comment]
@Bond-009 I use the app Mp3Tag to edit what I assume is the ID3 tag on all most all of my FLAC files so I don't think that's it. Only a small minority of albums do not work.

**Comment by knuurr** [comment]
Just to bump this thread, I've experienced this very issue.

I encountered issue with certain FLAC files (some, but not all) that I just couldn't play inside browser.

I tested them not only through Jellyfin but also through Navidrome, and the same files I checked also wouldn;t play.

- would play fine via AIMP on Windows 10
- would play fine from Navidrome/jellyfin when MS Edge was used, instead of Firefox.

I wonder if there is any mitigation for Firefox possible as it seems there is issue with Firefox browser.

**Comment by holotone** [comment]
Heya @knuurr , I figured out that the problem is caused by FLAC files that are tagged with MP3 ID3 tags. Most browsers ignore it but for some reason Firefox refuses to play them. You can solve the issue by using a tagger to remove the MP3 ID3 tags and replace them with FLAC tags. In the app mp3tag you can just select all the tracks, cut all tags, and paste all tags and it'll paste them back as proper FLAC tags.

Hope that helps!

**Comment by Shadowghost** [comment]
A technical FYI on that: per spec adding ID3 to FLAC is not supported behavior, FLAC only supports VorbisComment. So all in all mp3tag writing it is technically breaking the spec and any browser silently dropping it is accepting incorrect FLAC.

**Comment by kwhat** [comment]
can i get a command line Linux method of making this work? Its pretty disappointing that my first experience with Jellyfin is this error.

**Comment by rderensy** [comment]
@kwhat assuming you're using bash: cd into the directory with the FLAC files and run `for name in *.flac; do old_name="$name.orig"; mv $name $old_name; ffmpeg -i $old_name -c:a flac -c:v copy $name; done`

Then you can `rm *.orig` if you want to delete the original files (maybe makes sure it works before doing so).

**Comment by kwhat** [comment]
@rderensy Thanks for that! I ended up with `find . -name '*.flac' -exec mv '{}' '{}'.orig \; -exec ffmpeg -i '{}'.orig -c:a flac -c:v copy '{}' \; -exec rm '{}'.orig \;` and it worked!

**Comment by HackerDaGreat57** [comment]
@kwhat your code snippet worked for me, my Firefox is now happily playing my previously-broken FLAC files from a Jellyfin server. (I am posting this comment because it is impossible to react with 'thumbs up' for some reason and I wanted to confirm that the commands work)
