### ISSUE TITLE
Jellyfin silently dies

### ISSUE THREAD

**Issue by w1kl4s** [jellyfin/jellyfin#3733]
**System:**
 - OS:  Debian
 - Virtualization: LXC
 - Clients: All
 - Browser: All
 - Jellyfin Version: 10.6.1-1
 - Playback: Any
 - Installed Plugins: Anime
 - Reverse Proxy: nginx
 - Base URL: none
 - Networking: Host
 - Storage: local

**To Reproduce**
Can't reliably reproduce what causes the issue, seems to happen at any moment from starting playback up to ~5 minutes. 

**Expected behavior**
Working playback.

**Logs**
Even with debug logs, all i'm getting is occasional
```
Jul 28 20:36:22 media jellyfin[111]: [20:36:22] [ERR] [48] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: <snip>
Jul 28 20:36:22 media jellyfin[111]: System.MissingMethodException: Method not found: 'System.Collections.Generic.List`1<MediaBrowser.Controller.Entities.User> MediaBrowser.Controller.Library.PlaybackProgressEventArgs.get_Users()'.
Jul 28 20:36:22 media jellyfin[111]:    at Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint._sessionManager_PlaybackProgress(Object sender, PlaybackProgressEventArgs e)
Jul 28 20:36:22 media jellyfin[111]:    at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
```

And after that single 
```
Jul 28 20:36:31 media jellyfin[111]: [20:36:31] [DBG] [35] Emby.Server.Implementations.HttpServer.HttpListenerHost: Sending HTTP Response 500 in response to <snip>
```
**Additional context**
Occasionally, jellyfin throws a segfault like:
```
[Fri Jul 17 18:07:08 2020] jellyfin[24455]: segfault at 66 ip 00007f3f799c7c2d sp 00007f3f76b5dd00 error 4 in libcoreclr.so[7f3f79859000+24e000]
[Fri Jul 17 21:38:48 2020] jellyfin[29612]: segfault at 41 ip 00007f0410742c2d sp 00007f03027f8990 error 4 in libcoreclr.so[7f04105d4000+24e000]
[Fri Jul 17 21:39:22 2020] jellyfin[36865]: segfault at 41 ip 00007f7f34863c2d sp 00007f7e257f6990 error 4 in libcoreclr.so[7f7f346f5000+24e000]
[Sun Jul 26 15:36:19 2020] jellyfin[5706]: segfault at 200000014 ip 00007f612a422e25 sp 00007ffeb4a3ec30 error 4 in libcoreclr.so[7f612a256000+2ef000]
[Sun Jul 26 15:37:04 2020] jellyfin[8188]: segfault at 200000014 ip 00007f5a5cb78e25 sp 00007fff455d0450 error 4 in libcoreclr.so[7f5a5c9ac000+2ef000]
[Sun Jul 26 20:54:04 2020] jellyfin[28349]: segfault at 31 ip 00007f53da478c2d sp 00007f53d760ed00 error 4 in libcoreclr.so[7f53da30a000+24e000]
```
However it's not consistent with unavailability, sometimes it appears when jellyfin becomes unresponsible, and sometimes it just crashes and systemd gets it up like nothing happened.

**Comment by bugfixin** [comment]
When you say "Silently dies" - does this mean that the jellyfin processes are still running, but unresponsive? Or that the JF processes literally crash to termination?

**Comment by w1kl4s** [comment]
The former. Processes are still running, ports are listening, however everything is locked up, requests time out, and nothing gets appended to the log.

**Comment by bugfixin** [comment]
In that case, take a look at https://github.com/jellyfin/jellyfin/issues/3558 this issue - your use of lxc+debian made my ears perk up
