### ISSUE TITLE
SyncPlay disconnected from group in between each item of a playlist

### ISSUE THREAD

**Issue by twright** [jellyfin/jellyfin#3734]
**Describe the bug**
When playing a playlist and using the SyncPlay feature with a remote user, we experienced that syncplay was disconnected (with a left group notification) and we had to re-enable it (both on the our side and remote side) after the start of each entry on the playlist.

I am not sure if this is a bug, per say, but at the very least it is a missing feature which violates the reasonable user expectation that SyncPlay would continue for each item in a playlist (there is no way to discover that this would not be the case from the UI). The current behaviour in this case certainly leads to a suboptimal user experience (for the user perspective, synchronisation is stopped for no obvious reason), and I would imagine this use case is fairly common (watching a playlist of videos with a remote user).

Incidentally, other than this issue, SyncPlay worked perfectly. Thank you for this excellent new feature.

**System (please complete the following information):**
 - OS: Raspbian 
 - Virtualization: None
 - Clients: Browser (Fedora, Windows)
 - Browser: Chrome 84
 - Jellyfin Version: 10.6.1-1
 - Playback: Transcode
 - Installed Plugins: AudioDB, MusicBrainz, OMDb, Playback reporting, TMDb Boxsets, TheTVDB
 - Reverse Proxy: none
 - Base URL: /web/index.html#!/details?id=d5abc4993972a9c52cff9d37963ff8c8&serverId=cfaeb57c900447d5a573e59e50dc4499
 - Networking: N/A
 - Storage: local (Btrfs RAID)

**To Reproduce**
1. Create a Playlist
2. Click on Click on Play for first item (I have not tested if the same behaviour occurs if clicking the play button for the overall playlist).
3. Enable SyncPlay (click on SyncPlay button and create group)
4. Get another user to join group
5. Wait for end of first Playlist item
4. Get SyncPlay ended notification; playback continues for both local and remote user, but playback is no longer synchronised
**Expected behavior**
SyncPlay continues for each subsequent item of the playlist

**Comment by crobibero** [comment]
Playlists are currently not implemented in SyncPlay. Here is the WIP PR that is implementing that: https://github.com/jellyfin/jellyfin/pull/3194

**Comment by twright** [comment]
Thank you for pointing me to that PR. I will check it out and might try out the code to see how well it handles this use case.

**Comment by twright** [comment]
This issue is still open until PR #3149 is merged.
