### ISSUE TITLE
[bug] Having trouble transcoding PGSSUB subtitles

### ISSUE THREAD

**Issue by GJHNK** [jellyfin/jellyfin#3737]
**Describe the bug**

I tried to play moives in my NAS with transcoding. The hardware acceleration (VAPPI) is enabled, but some issues are encounterd. First, I can't play most of my 4K HEVC 10bit moives. Second, a few can be played but with obvious playback freeze. The straming got stuck every few seconds. Third, a few of my 1080p h264 8bit movies can't be played as well. Other moives play smoothly.

**System:**

- Hardware: Synology DS 920+
- OS: DSM 6.2.3-25426 Update 2
- Virtualization: Docker
- Clients: Browser
- Browser: Chromium 84.0.4147.105 (Official Build)  (64-bit)
- Jellyfin Version: 10.6.1
- Playback: Transcoding
- Installed Plugins: None

**To Reproduce**

Install jellyfin/jellyfin:lastest from Docker in DSM
Turn on Hard acceleration (VAPPI) following instructions from jellyfin.org
Start to play a video in moive library 
Expected behavior

**Logs**

1. hevc 10bit can't play
[jellyfin log hevc no play.txt](https://github.com/jellyfin/jellyfin/files/4992481/jellyfin.log.hevc.no.play.txt)
[hevc 10bit no paly.txt](https://github.com/jellyfin/jellyfin/files/4992482/hevc.10bit.no.paly.txt)

2. hevc 10bit paly but freeze
[jellyfin log hevc freeze.txt](https://github.com/jellyfin/jellyfin/files/4992489/jellyfin.log.hevc.freeze.txt)
[hevc 10bit freeze.txt](https://github.com/jellyfin/jellyfin/files/4992490/hevc.10bit.freeze.txt)

3. h264 8bit can't paly
[jellyfin log h264 no play.txt](https://github.com/jellyfin/jellyfin/files/4992493/jellyfin.log.h264.no.play.txt)
[h264 8bit no play.txt](https://github.com/jellyfin/jellyfin/files/4992494/h264.8bit.no.play.txt)

4. h264 8bit play well
[jellyfin h264 paly well.txt](https://github.com/jellyfin/jellyfin/files/4992527/jellyfin.h264.paly.well.txt)
[h264 play wll.txt](https://github.com/jellyfin/jellyfin/files/4992528/h264.play.wll.txt)

**Screenshots**

1. can't paly
![no play](https://user-images.githubusercontent.com/43900492/88756775-102ef080-d197-11ea-8d29-3c38d8b6e87f.png)

2. hevc 10bit play but freeze
![hevc freeze](https://user-images.githubusercontent.com/43900492/88756345-01940980-d196-11ea-9a8c-7c8c72b8c490.png)

3. h264 8bit play smoothly
![h264 play well](https://user-images.githubusercontent.com/43900492/88756374-1375ac80-d196-11ea-837f-26c363ffcdba.png)

**Comment by nyanmisaka** [comment]
Are you sure you have turned on VAAPI correctly like this?

![Screenshot from 2020-07-29 18-28-18](https://user-images.githubusercontent.com/14953024/88789766-b72c8000-d1c9-11ea-8452-27b62cd07fb4.png)


From log your problem occurred when burning in the PGSSUB subs, but I cannot reproduce it.

**Comment by GJHNK** [comment]
Thank you for your reply. I'm sure VAAPI is tured on. Here's the screenshot of transcode setting.
![Transcoding](https://user-images.githubusercontent.com/43900492/88815282-c0c7df00-d1ed-11ea-9803-54f92c9aade6.png)

And you are absolutely right. The transcoing works when PGSSUB subs turned off. Additionally, I tried to play the same content without sub on my iPad Pro's safafi, and it works just fine. So, I guess the freezing issue I mentioned is more likely caused by chrome's caching mechanism rather than Jellyfin's setting.
![Transcoding successful](https://user-images.githubusercontent.com/43900492/88868337-82104400-d242-11ea-91f3-6fa3c1d89de4.png)

Is it possible to solve the PGSSUB issue? I'm not sure if it would help but I've extracted one of the sub track using MKVToolnix.
[sup.zip](https://github.com/jellyfin/jellyfin/files/4998171/sup.zip)

**Comment by nyanmisaka** [comment]
Should be fixed in jeff 10.7.

**Comment by EliteElectronic** [comment]
Jellyfin cannot play PGS subtitles with hardware acceleration turned on.
When hardware acceleration enabled, I get below error when playing videos with PGS subtitles.
PGSSUB Playback Error This client isn't compatible with the media and the server isn't sending a compatible media format.

I tried playing on Chrome and Safari browser and Jellyfin Media Player APP on Roku without any luck.
When I turned off hardware acceleration and played the exact same video files with PGS Subtitles, it just fine without any issues.

I found PGS Subtitles ONLY work on the Jellyfin Media Player APP Windows version.
Why only Jellyfin Media Player APP Windows version works ??? !!!

My main player is Jellyfin Media Player APP on Roku and all of my movies are Bluray rip with PGS Subtitles.
Jellyfin team, please look into this and make hardware acceleration PGS Subtitles work everywhere for us!
Thank you !!!
