### ISSUE TITLE
Checkboxes in built-in plugin configurations are broken (10.6.1, Windows)

### ISSUE THREAD

**Issue by Norde** [jellyfin/jellyfin#3739]
**Describe the bug**
Plugins settings are not saved despite the popup message "settings saved"
Related to #3705

Normaly fixed by #3633 / #3634
Is there any behavior specific to Windows?

**System (please complete the following information):**
 - OS: Windows
 - Virtualization: none
 - Clients: Browser
 - Browser: Firefox 78.0.2 and 79
 - Jellyfin Version: stable 10.6.1

**Comment by esmondmissen** [comment]
This seems to be working for me on 10.6.2

**Comment by dkanada** [comment]
Excellent, we did push a fix so I think it's resolved now.

**Comment by Norde** [comment]
I confirm : its fixed in 10.6.2
Thanks !
