### ISSUE TITLE
Info to create Debug logs is innacurate

### ISSUE THREAD

**Issue by bengalih** [jellyfin/jellyfin#3745]
JF documentation says that to enable Debug logging we should edit `logging.json` in the data directory.
On Windows at least, no `logging.json` file exists, but a `logging.default.json` does.

This appears to have the same results (hard to tell, but it appears one does get at least some DBG messages when enabled in this file).

Can the documentation be updated to reflect the proper name of the file as this can lead to confusion.

**System (please complete the following information):**
 - OS: Windows
 - Virtualization:none
 - Clients: Browser
 - Browser: Chrome 84.0.4147.89 
 - Jellyfin Version: 10.6
 - Playback: Stream to Chromecast
 - Installed Plugins: Pushbullet
 - Reverse Proxy: NGINX
 - Base URL: no
 - Networking: see attached
 - Storage: local

**Comment by BaronGreenback** [comment]
Find the file logging.default.json in the jellyfin data folder.

The first part is how to enable debugs - default can be "information", "debug", "warning"
this will enable debug logs for everything

You can tweek individuals by using the default and override sections.

The module names appear in the logging.
Below will show warnings for everything except "Emby.Dlna.Main.DlnaEntryPoint" which will show debugs info.

The modules tend to follow the git hub paths - but not always as some modules haven't been moved across.

{
    "Serilog": {
        "MinimumLevel": {
            "Default": "Warning",
            "Override": {
                "Microsoft": "Warning",
                "System": "Warning",
	        "Emby.Dlna.Main.DlnaEntryPoint" : "Debug"
            }
        },

**Comment by bengalih** [comment]
Ok, thanks.

I believe someone needs to update the documentation here:

https://jellyfin.org/docs/general/administration/troubleshooting.html#:~:text=Debug%20Logging,to%20debug%20as%20seen%20below.&text=Jellyfin%2010.4.

To show that the file is called "logging.default.json" not "logging.json"
