### ISSUE TITLE
Can no longer change volume when web page is split 50/50 on the screen for Music.

### ISSUE THREAD

**Issue by Urworstnit3m3r** [jellyfin/jellyfin#3746]
**Describe the bug**
After the update there seems to have been some work done with the UI which has now made it so that you can not change the volume if the web page is shrunk down past a point.

A lot of the time I have my web browser split in a 50% left / 50% right mode on my 24" 1080p display which makes the volume slider disappear and go to a volume button which you can only press to mute the volume.

I have found that if I expand the window over the 50% mark just a little bit the volume slider returns. Also it returns if I zoom out the window from 100%.

Also noticed I lose the heart, shuffle and repeat icons.

This seems to only affect Music playback. 

**System (please complete the following information):**
 - Client OS: EndeavourOS (Arch Linux) with Gnome desktop
 - OS: CentOS 7
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Firefox latest version
 - Jellyfin Version: 10.6.1
 - Installed Plugins: AudioDB, MusicBrainz, OMDb, Playback Reporting,TheTVDB
 - Reverse Proxy: traefikv2
 - Base URL: none
 - Networking: Bridge/NAT
 - Storage: NFS

**To Reproduce**
1. Go to Jellyfin home screen
2. Click on the ... menu for music, click shuffle to start playing
3. Move the browser window to 50% left or right mode by dragging the window all the way to the left or right of the screen and let it auto resize or do super key + left or right arrow key
4. See volume slider go to volume button with only click to mute function

**Screenshots**
Browser in full screen mode:
![Screenshot from 2020-07-29 18-10-37](https://user-images.githubusercontent.com/37315608/88863454-8861da00-d1c8-11ea-970b-ab46bd21f0c5.png)
Browser in 50% screen mode:
![Screenshot from 2020-07-29 18-10-21](https://user-images.githubusercontent.com/37315608/88863523-ab8c8980-d1c8-11ea-9462-b28aac6a3adb.png)

**Comment by neopc10** [comment]
unstale
