### ISSUE TITLE
Unable to decode video using the core graphics card

### ISSUE THREAD

**Issue by yyxida** [jellyfin/jellyfin#3751]
**Describe the bug**

**System (please complete the following information):**
 - OS: Debian
 - Virtualization:Docker
 - Clients:all
 - Browser: all
 - Jellyfin Version: 10.6.1
 - Playback: Transcode
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: none
 - Networking: Host
 - Storage: local

**To Reproduce**

1. Go to 'play'
2. Click on 'Hardware Acceleration'
3. Scroll down to 'Video Acceleration API (VAAPI)'
4. play the video
5. Unable to load

**Expected behavior**

Normal playback using hardware decoding
**Logs**

log

```
[05:26:10] [INF] [27] MediaBrowser.Api.Playback.Hls.DynamicHlsService: /usr/lib/jellyfin-ffmpeg/ffmpeg -ss 00:00
 :06.000 -hwaccel vaapi -noaccurate_seek -hwaccel_output_format vaapi -vaapi_device /dev/dri/renderD128 -i file:"
/media/disk2/映画/[VCB-Studio] Gekijouban KanColle [Ma10p_1080p]/[VCB-Studio] Gekijouban KanColle (DC Ver.) [Ma1
0p_1080p][x265_flac].mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h2
 64_vaapi  -b:v 11863184 -maxrate 11863184 -bufsize 23726368 -profile:v high -level 41  -force_key_frames:0 "expr
 :gte(t,6+n_forced*3)" -g 72 -keyint_min 72 -sc_threshold 0 -vf "format=nv12|vaapi,hwupload,scale_vaapi=format=nv
 12" -start_at_zero -vsync -1 -codec:a:0 libmp3lame -ac 2 -ab 192000  -copyts -avoid_negative_ts disabled -f hls 
 -max_delay 5000000 -hls_time 3 -individual_header_trailer 0 -hls_segment_type mpegts -start_number 2 -hls_segmen
 t_filename "/config/transcodes/53001154ebfca020a65c17fd5e6635e8%d.ts" -hls_playlist_type vod -hls_list_size 0 -y
 "/config/transcodes/53001154ebfca020a65c17fd5e6635e8.m3u8"                                                     
 [05:26:10] [ERR] [34] MediaBrowser.Api.Playback.Hls.DynamicHlsService: FFMpeg exited with code 1    

```
ffmpeg log:

```
Stream mapping:
 Stream #0:0 -> #0:0 (hevc (native) -> h264 (h264_vaapi))
  Stream #0:1 -> #0:1 (flac (native) -> mp3 (libmp3lame))
Press [q] to stop, [?] for help
 [hevc @ 0x555f6ccaed00] No support for codec hevc profile 2.
 [hevc @ 0x555f6ccaed00] Failed setup for format vaapi_vld: hwaccel initialisation returned error.

```
**Screenshots**

 https://i.loli.net/2020/07/30/HXdWjZ3EVFhaDyI.jpg
**Additional context**

The cpu uses the relatively rare I7-5775C and the core graphics card is an Intel Iris Pro Graphics 6200, perhaps it's rare so there's no support? (can be driven in the system)
Thanks.

**Comment by Shadowghost** [comment]
You're trying to handle HEVC - which is not supported by your integrated graphics card (Broadwell CPU) ([source](https://en.wikipedia.org/wiki/Intel_Quick_Sync_Video#Hardware_decoding_and_encoding)). You can still use your onboard GPU to transcode other formats - you can disable not supported formats in hw transcoding settings.

**Comment by nyanmisaka** [comment]
`[hevc @ 0x555f6ccaed00] No support for codec hevc profile 2.`
Your iGPU doesn't support HEVC (profile 2) decoding.

Consider turning off HEVC decoding to use SW decoding and HW encoding.
