### ISSUE TITLE
Github page doesn't tell how to run the server without web front-end correctly

### ISSUE THREAD

**Issue by JPUnD** [jellyfin/jellyfin#3752]
**Describe the bug**
In the bottom of this github page, in the section Hosting [The Web Client Separately ](https://github.com/jellyfin/jellyfin#hosting-the-web-client-separately) the flag to not use the web front-end is said to be `--nowebcontent` but in my system it only works with `--nowebclient`.
Running `sudo /usr/lib/jellyfin/bin/jellyfin --datadir /var/lib/jellyfin --cachedir /var/cache/jellyfin --nowebcontent` returns `Option 'nowebcontent' is unknown.`

**System (please complete the following information):**
 - OS: Manjaro ARM on a Raspberry Pi 4
 - Jellyfin Version: 10.6.1.0
 - Networking: Localhost

**To Reproduce**
1. Install Jellyfin server package
2. Run with flag `--nowebcontent`
3. Get error

**Expected behavior**
Expected Jellyfin to start it's server without web front-end, crashes instead.

**Logs**
```
sudo /usr/lib/jellyfin/bin/jellyfin --datadir /var/lib/jellyfin --cachedir /var/cache/jellyfin --nowebcontent                 
Jellyfin.Server 10.6.1.0
Copyright ©  2019 Jellyfin Contributors. Code released under the GNU General Public License

ERROR(S):
  Option 'nowebcontent' is unknown.

  -d, --datadir             Path to use for the data folder (database files, etc.).

  --nowebclient             Indicates that the web server should not host the web client.

  -w, --webdir              Path to the Jellyfin web UI resources.

  -C, --cachedir            Path to use for caching.

  -c, --configdir           Path to use for configuration data (user settings and pictures).

  -l, --logdir              Path to use for writing log files.

  --ffmpeg                  Path to external FFmpeg executable to use in place of default found in PATH.

  --service                 Run as headless service.

  --noautorunwebapp         Run headless if startup wizard is complete.

  --package-name            Used when packaging Jellyfin (example, synology).

  --restartpath             Path to restart script.

  --restartargs             Arguments for restart script.

  --published-server-url    Jellyfin Server URL to publish via auto discover process

  --help                    Display this help screen.

  --version                 Display version information
```

**Additional context**
After looking through the previous output, i'm wondering what does the flag `--noautorunwebapp` actually does. Also after running Jellyfin without web front-end, going to Jellyfin server in my browser actually shows up something called "Swagger UI", was that suppose to happen?
I was going to test if the server was working as expected, but I only have the Jellyfin app on Android, because i'm not sure which one I should use on the desktop to mimic the web interface on the browser, and I can't add any users, I'm stuck in the login screen with no accounts because this is a new server and doesn't have any users.

**Comment by dkanada** [comment]
That flag is a relic if I recall correctly, and we should honestly remove it from the server. The one you're looking for should be `--nowebcontent` but there must be an error somewhere.

**Comment by JPUnD** [comment]
> That flag is a relic if I recall correctly, and we should honestly remove it from the server. The one you're looking for should be `--nowebcontent` but there must be an error somewhere.

Which flag is a relic? The `--noautorunwebapp`?

And when it comes to the flag `--nowebcontent` it doesn't work, it's simply not recognized, I have to use `--nowebclient` to get rid of the web interface, and when doing so going to the Jellyfin server reveals something named Swagger UI where the web UI should be.

**Comment by crobibero** [comment]
to host jellyfin without the webui, run with both flags: `--noautorunwebapp --nowebclient`
This will start Jellyfin without opening the browser to the endpoint docs.

**Comment by JPUnD** [comment]
Ah okay got it, right now it's scanning my library, but i'm pretty sure i tried running both of those flags and still got that Swagger UI page in my browser, but i supposed i couldn't get rid of that, although i wanted to to save resources, but i'll test again once this is done reading my library.

**Comment by crobibero** [comment]
its possible that if you started the server without the flag `noautorunwebapp` it's stored in config. This flag doesn't disable anything- it just makes Jellyfin not open the browser. SwaggerUI will still be loaded.

**Comment by JPUnD** [comment]
Ah, the server is running on a headless Raspberry Pi so i wouldn't notice the diference of having or not having that flag, so SwaggerUI cannot by disabled no matter how it goes?

**Comment by crobibero** [comment]
SwaggerUI itself takes minimal resources, so I wouldn't worry about it. What I would do is edit `system.xml` and set `AutoRunWebApp` to `false` so you don't have to worry about the flag.
