### ISSUE TITLE
Selector for multiple audio streams inside player for LiveTV

### ISSUE THREAD

**Issue by flowlee** [jellyfin/jellyfin#3765]
**Description**
There is currently no way to switch between multiple audio tracks from inside the player UI when watching a LiveTV stream.

**To Reproduce**
1. Play a channel with multiple audio tracks
2. Try to change to a different audio track while the video is playing ;)

**Expected behavior**
There should be a UI element to select a different audio track in the player overlay

**System**
 - OS: Docker on Ubuntu Server 16.04, TV stream via TVHeadend plugin
 - Browser: Firefox
 - Jellyfin Version: 10.5.0

**Comment by sevenrats** [comment]
no code means not a bug. moved to https://features.jellyfin.org/posts/2357/selector-for-multiple-audio-streams-inside-player-for-livetv
