### ISSUE TITLE
OPF files being imported as a book in Jellyfin 10.6.1

### ISSUE THREAD

**Issue by Protektor-Desura** [jellyfin/jellyfin#3766]
When I create a book library and have Jellyfin 10.6.1 scan my books directory it is importing the metadata.opf files as if they are books. It never did this before. This is on a brand new library and new scan of the books directory. If you go in to the "book" it will let you try and download the metadata.opf file like it is a book you can download and read. It should be reading these opf files as the metadata they are, instead of thinking they are books.

![Screenshot (46)](https://user-images.githubusercontent.com/1195496/89053895-82314200-d31d-11ea-9d08-5387b12732ea.png)

**Comment by vrokolos** [comment]
Same here! Need a fix
