### ISSUE TITLE
Please do not force push to repository

### ISSUE THREAD

**Issue by sauerj** [jellyfin/jellyfin#377]
I forked from jellyfin/master at commit c9a24cc216bc56fdb273d4ad467a1481086bce84

Today I wanted to update my personal fork but ran in a ton of merge conflicts.

I think somehow the commit was rewritten to d43a086164916c9319a6cf373a51512ef2bc62a6

Please be careful when doing this. It will break forked repositories and is not recommended.

**Comment by nvllsvm** [comment]
We had to force push due to code being inadvertently being relicensed in this repo. We don't expect to do it anymore.

**Comment by sauerj** [comment]
Sorry I must have missed that over the holidays. Force updated my fork to remove the unlicensed code.
