### ISSUE TITLE
ANDROID TV Jellyfin loads the subtitle from wrong episode after going to the next one.

### ISSUE THREAD

**Issue by ixanx** [jellyfin/jellyfin#3776]
Android TV based on Android7.1
Steps to reproduce:

> Open Jellyfin app

> Select a TV Show

> Select an episode, press play

> Select the subtitle, everything is going fine for now. After the episode ended, let it automatically go to the next one.

> The next episode loads the same subtitle as the previous episode, so I have to go back and select the new episode alone.

**Comment by olskar** [comment]
I can confirm this bug also. Using 10.6.1 but was present in 10.5 as well.

**Comment by olskar** [comment]
Dupe of https://github.com/jellyfin/jellyfin-androidtv/issues/108 ?
