### ISSUE TITLE
HEVC playback issue

### ISSUE THREAD

**Issue by normanu** [jellyfin/jellyfin#3780]
**Media Info of the file**
Video
Title4K HEVC
CodecHEVC
ProfielMain
Niveau153
Resolutie3840x2160
Beeld verhouding16:9
InterlacedNo
Beeldverversing24
Bitrate15969 kbps
Pixel formaatyuv420p
Ref beeld1

**Logs**
[libx264 @ 0x55a87d3abf80] 264 - core 152 r2854 e9a5903 - H.264/MPEG-4 AVC codec - Copyleft 2003-2017 - http://www.videolan.org/x264.html - options: cabac=1 ref=1 deblock=1:0:0 analyse=0x1:0 me=dia subme=0 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=4 chroma_me=0 trellis=0 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=0 threads=24 lookahead_threads=4 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=1 keyint=72 keyint_min=37 scenecut=0 intra_refresh=0 rc_lookahead=10 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 vbv_maxrate=31939 vbv_bufsize=63879 crf_max=0.0 nal_hrd=none filler=0 ip_ratio=1.40 aq=1:1.00
frame=   36 fps=0.0 q=0.0 size=N/A time=-577014:32:22.77 bitrate=N/A speed=N/A    
frame=   92 fps= 92 q=0.0 size=N/A time=-577014:32:22.77 bitrate=N/A speed=N/A    
frame=  143 fps= 95 q=0.0 size=N/A time=-577014:32:22.77 bitrate=N/A speed=N/A    
Too many packets buffered for output stream 0:0.

and

[libx264 @ 0x55d25fbf1b80] using SAR=1/1
[libx264 @ 0x55d25fbf1b80] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x55d25fbf1b80] profile Main, level 4.1
[libx264 @ 0x55d25fbf1b80] 264 - core 152 r2854 e9a5903 - H.264/MPEG-4 AVC codec - Copyleft 2003-2017 - http://www.videolan.org/x264.html - options: cabac=1 ref=1 deblock=1:0:0 analyse=0x1:0 me=dia subme=0 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=4 chroma_me=0 trellis=0 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=0 threads=24 lookahead_threads=4 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=1 keyint=250 keyint_min=24 scenecut=40 intra_refresh=0 rc_lookahead=10 rc=crf mbtree=0 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 vbv_maxrate=10616 vbv_bufsize=21232 crf_max=0.0 nal_hrd=none filler=0 ip_ratio=1.40 pb_ratio=1.30 aq=1:1.00
frame=   44 fps=0.0 q=0.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
frame=   99 fps= 97 q=0.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
frame=  150 fps= 98 q=0.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
Too many packets buffered for output stream 0:0.
[libx264 @ 0x55d25fbf1b80] frame I:5     Avg QP: 9.25  size: 53566
[libx264 @ 0x55d25fbf1b80] frame P:44    Avg QP:13.36  size: 33593
[libx264 @ 0x55d25fbf1b80] frame B:80    Avg QP:15.39  size: 12046
[libx264 @ 0x55d25fbf1b80] consecutive B-frames: 12.4% 10.9% 11.6% 65.1%
[libx264 @ 0x55d25fbf1b80] mb I  I16..4: 70.3%  0.0% 29.7%
[libx264 @ 0x55d25fbf1b80] mb P  I16..4: 37.4%  0.0%  0.0%  P16..4: 27.4%  0.0%  0.0%  0.0%  0.0%    skip:35.1%
[libx264 @ 0x55d25fbf1b80] mb B  I16..4:  5.3%  0.0%  0.0%  B16..8: 23.7%  0.0%  0.0%  direct: 8.5%  skip:62.6%  L0:41.1% L1:43.5% BI:15.4%
[libx264 @ 0x55d25fbf1b80] coded y,uvDC,uvAC intra: 27.0% 37.9% 11.2% inter: 9.1% 15.9% 0.1%
[libx264 @ 0x55d25fbf1b80] i16 v,h,dc,p: 40% 31% 12% 17%
[libx264 @ 0x55d25fbf1b80] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 19% 28% 16%  7%  8%  6%  7%  4%  7%
[libx264 @ 0x55d25fbf1b80] i8c dc,h,v,p: 47% 30% 13%  9%
[libx264 @ 0x55d25fbf1b80] Weighted P-Frames: Y:18.2% UV:9.1%
[libx264 @ 0x55d25fbf1b80] kb/s:4032.98
Conversion failed!

**Server System (please complete the following information):**
 - OS: Docker on Linux
 - Jellyfin Version: 10.7.0 and older
 - Hardware settings & device: Software
 - Reverse proxy: HAProxy
 - Other hardware notes: Media on ZFS
 
**Client System (please complete the following information):**
I tried streaming above file I have in 4k x265 streaming to the Chromecast, but it stays on playing and won't play.
I can also not play it in Chrome, but it works in Edge although it downscales to 1920x1080 instead of playing at 4K.
Can Jellyfin not play above format?

**Comment by nyanmisaka** [comment]
Can you try to add `-max_muxing_queue_size 1024` after `ffmpeg` commands and verify if it works?

**Comment by normanu** [comment]
> Can you try to add `-max_muxing_queue_size 1024` after `ffmpeg` commands and verify if it works?

Where can I set this?
