### ISSUE TITLE
Change of log message category. (HTTP listener timing)

### ISSUE THREAD

**Issue by BaronGreenback** [jellyfin/jellyfin#3781]
Given that there isn't much the end user could do with this information, and that it fills up the logs - wouldn't it be a good idea of changing this to a debug message?

[WRN] [48] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to 73.57.110.212. Time (slow): ....

**Comment by telans** [comment]
That log output doesn't seem to exist anymore on master, only in release branches.

**Comment by crobibero** [comment]
> That log output doesn't seem to exist anymore on master, only in release branches.

The message has moved to https://github.com/jellyfin/jellyfin/blob/master/Jellyfin.Server/Middleware/ResponseTimeMiddleware.cs

**Comment by telans** [comment]
> The message has moved

Would a PR chaning this to Debug level be welcome or do people want it left as Warning/Informational?

**Comment by cvium** [comment]
If people don't want the warning they can just disable it in the server settings. Seems rather pointless to change it to debug if the point is to hide it.

**Comment by telans** [comment]
> If people don't want the warning they can just disable it in the server settings. Seems rather pointless to change it to debug if the point is to hide it.

Either I'm really blind, or it doesn't seem to be hooked up to anything in the UI

**Comment by cvium** [comment]
For whatever reason, it's not. You will have to edit system.xml manually. It could be argued that it should be off by default, but we're also still in a "breaking stuff fast" stage, so it's nice to have.

**Comment by BaronGreenback** [comment]
Thx - can't remember submitting this one!

**Comment by PrplHaz4** [comment]
> 
> 
> For whatever reason, it's not. You will have to edit system.xml manually. It could be argued that it should be off by default, but we're also still in a "breaking stuff fast" stage, so it's nice to have.

I was mistakenly thinking this was about the websocket keepalive messages.  For anyone following, it looks like the correct config keys are:
```xml
<EnableSlowResponseWarning></EnableSlowResponseWarning>
<SlowResponseThresholdMs></SlowResponseThresholdMs>
```
