### ISSUE TITLE
Kodi plugin: native mode doesn't add tv shows

### ISSUE THREAD

**Issue by Brutus11111** [jellyfin/jellyfin#3791]
**Describe the bug**
When using Kodi with native mode, it doesn't add tv shows like it adds movies. 

**System (please complete the following information):**
 - OS: [e.g. Debian, Windows]
Arch Linux
 - Virtualization: [e.g. Docker, KVM, LXC]
N/A
 - Clients: [Browser, Android, Fire Stick, etc.]
Kodi
 - Browser: [e.g. Firefox 72, Chrome 80, Safari 13]
Chromium 83
 - Jellyfin Version: [e.g. 10.4.3, nightly 20191231]
Version: 10.6.0
 - Playback: [Direct Play, Remux, Direct Stream, Transcode] 
Native
 - Installed Plugins: [e.g. none, Fanart, Anime, etc.]
Kodi Sync Queue
 - Reverse Proxy: [e.g. none, nginx, apache, etc.]
N/A
 - Base URL: [e.g. none, yes: /example]
?
 - Networking: [e.g. Host, Bridge/NAT]
N/A
 - Storage: [e.g. local, NFS, cloud]
SMB

**To Reproduce**
Open Kodi
Add SMB shares for movies and tv shows
Install Jellyfin plugin
Add Jellyfin server
When Asked for All/Movies/TV shows, select all
It will now add all movies and it goes through TV shows
Only movies are added

**Expected behavior**
I expect TV shows to get added the same way it's adding movies. 

**Logs**
https://termbin.com/k2fp

**Comment by Brutus11111** [comment]
Update: I have this issue on my PC and my (android) TV. On my TV the TV shows randomly appeared. It's still not working on my PC.

**Comment by holow29** [comment]
Is your Jellyfin library setup for TV Shows or do you have it set to mixed media or something else? Also, since this is more about the plugin/native mode, I think it probably belongs in https://github.com/jellyfin/jellyfin-kodi instead.
