### ISSUE TITLE
Overlapping libraries aren't working

### ISSUE THREAD

**Issue by ghost** [jellyfin/jellyfin#3797]
I don't really got a description, but I'll describe the setup:

1. So, I created my MUSIC folder that contains music I want to listen to on a private Jellyfin account, here named PRIVATE which is linked to a MUSIC library. This is accessible on this account only(don't allow all folder access, grant access to this folder). | Folder directory example: /MUSIC/ | Make this directory first
2. Have a directory in this folder named, for example, GUEST MUSIC, and add this as another library. Assign this to a new user, here named GUEST, and only allow this user access to this folder(via the same way as the previous depiction).  | Folder directory example: /MUSIC/GUEST MUSIC/ | Make this directory second
-----
Excepted result: the PRIVATE user will be able to see all music, including music in the GUEST MUSIC folder(as it's a directory in the MUSIC folder), and the GUEST user will be able to see, and only see, the music in the GUEST MUSIC folder.

Actual result: The PRIVATE user can access all music(expected), but the GUEST user can't see any, including that in the GUEST MUSIC directory(unexpected).

**Comment by Shadowghost** [comment]
Known issue (happens every time you have two libraries referencing the same local directory) due to bad database concept (afaik itemID is generated from local path - which breaks the above setup). Sadly there's no temporary fix I know of until the library database is fully migrated to EFCore.

**Comment by hwittenborn** [comment]
I'll look into that stuff, haven't really heard of itemID or EFCore or any of that stuff, but I'll take your input on it.

**Comment by BaronGreenback** [comment]
Workaround is to use a shortcut, UNC or junction point to the folder so that the path is different, causing a unique itemID to be created.

**Comment by hwittenborn** [comment]
Sorry for not clarifying/asking this earlier, but

> Known issue (happens every time you have two libraries referencing the same local directory) due to bad database concept (afaik itemID is generated from local path - which breaks the above setup). Sadly there's no temporary fix I know of until the library database is fully migrated to EFCore. @Shadowghost 

Is the setup you're describing creating two libraries referencing the same directory(exactly)? My setup(for demonstration purposes) anyway is --
1. A Library for all of my music | /Music/
2. Another library for a subdirectory of my music, primarily for a **guest account(irrelevant)** | /Music/Guest/

**Comment by BaronGreenback** [comment]
/Music/ contains /Music/Guest/ so when /Music/Guest/ gets parsed, it is already found in the database as being part of /Music/ whose parent is the /Music/ folder, hence the issue - so JF doesn't add it again.

I take it your non-windows based, so i'd keep /Music/ but create a mount point to /Music/Guest and call it something else.

that way both paths will be unique and one won't be part of the other.

Hope that makes sense.

**Comment by hwittenborn** [comment]
Yep, makes sense! I'll look into implementing it shortly. Not sure if I should close it now that there is a workaround in place(or to keep it open since it's not a native feature), feel free to do with it what you want.
