### ISSUE TITLE
Not able to Save LDAP Setting 

### ISSUE THREAD

**Issue by docfactory37** [jellyfin/jellyfin#3798]
**Describe the bug**
I had to reinstall Jellyfin after i rebuilt my server and when i add the detials to the LDAP plugin it will not save the change and create the xml in the plugin config folder

**System (please complete the following information):**
 - OS: Ubuntu Server 18.04
 - Virtualization: install on the OS
 - Browser: google Chrome (i have also tried firefox)
 - Jellyfin Version: 10.6.2
 - Installed Plugins: LDAP Version 9.0.0

**To Reproduce**
i input the required information in the fields and then click save it reloads with on information inputed.
i then check the jellyfin Plugin config folder and no config file created.

**Expected behavior**
when items are add to the fields and you save it should create the config file and save the inputeed information

**Logs**

**Screenshots**

![image](https://user-images.githubusercontent.com/20963053/89155166-a73ae480-d5ab-11ea-9d28-4a9b78244053.png)

**Comment by zehnerGIT** [comment]
known bug:
https://forum.jellyfin.org/t/network-settings-do-not-stick/1454
https://github.com/jellyfin/jellyfin-plugin-template/issues/8
https://github.com/jellyfin/jellyfin-plugin-ldapauth/issues/21
https://github.com/jellyfin/jellyfin/issues/2628
...

**Comment by docfactory37** [comment]
@zehnerGIT is there an ETA on when this will be fixed as i know alot of people are having the same issue? and is there a work around for now?

**Comment by zehnerGIT** [comment]
sorry, I have no insights, when or if this gets fixed. 
I hope the fix comes sooner than later, because with this bug it's very hard for addon developers to deploy new addons.

**Comment by FDrebin** [comment]
Looking at the Jellyfin LDAP Plugin, looks like there was a merge to fix this, or at least that's how I am reading it : https://github.com/jellyfin/jellyfin-plugin-ldapauth/pull/45

**Comment by docfactory37** [comment]
hi @FDrebin,

im on Jellyfin server version 10.6.2 and LDAP plugin version 9.0.0 and it dose not save any setting or create the config file, if it created the config  file o would have just manually edited it and see if that worked. i did have it  working before i had to rebuild my Server from scratch.

**Comment by kopax** [comment]
Same issue here, 8.0.0 and can't save settings, using latest jellyfin image.

**Comment by mami7880** [comment]
Same here.
Jellyfin Version: 10.6.4
LDAP-Auth-Plugin Version: 9.0.0
OS: Ubuntu Server 20.04

**Comment by LukasK13** [comment]
Any updates here?

**Comment by crobibero** [comment]
I just tested with Jellyfin 10.7rc1, LDAP v10; and I can still not replicate the issue.
As I mentioned previously- attempting to save will cause the page to refresh the first time, but will save properly the second time.

**Comment by crobibero** [comment]
Closing in favor of https://github.com/jellyfin/jellyfin-plugin-ldapauth/issues/56

**Comment by kopax** [comment]
Hi, I am testing right now, I used to try with version 9 so this may change the deal.
