### ISSUE TITLE
Improve config handling

### ISSUE THREAD

**Issue by chriscowley** [jellyfin/jellyfin#38]
Not sure I have a solution, but the configuration could jellyfin could do with an improvement. I would like to use my Kubernetes cluster to host Jellyfin. The "correct" way to configure it would be `ConfigMap`s or environment for Jellyfin's config. However, currently, the `config` volume contains 11785 files. 

```
[chris@ovirt01 emby]$ find config/ -type f | wc -l
11785
```

Even ignoring the `config/metadata` folder and I have nearly 300 files.

This includes a huge amount of stuff that is simply cache, metadata and defaults. These have no place in the config directory.

By all means this directory can be mounted as a volume, but should be called something else (metadata?). Config needs to come from a (ideally) a single file and/or environment variables.

**Comment by joshuaboniface** [comment]
I think this has been gradually solved by various cleanups. Currently on 10.0.1, there are only 30 files in the config dir:

```
joshua@test5.i.bonilan.net /etc/jellyfin $ find . -type f -printf c | wc -c
30
```

Considering this solved; if not please let me know @chriscowley !

**Comment by joshuaboniface** [comment]
I think this has been gradually solved by various cleanups. Currently on 10.0.1, there are only 30 files in the config dir:

```
joshua@test5 /etc/jellyfin $ find . -type f -printf c | wc -c
30
```

Considering this solved; if not please let me know @chriscowley !
