### ISSUE TITLE
Black library images

### ISSUE THREAD

**Issue by Bond-009** [jellyfin/jellyfin#3826]
**Describe the bug**
The library images are all black

**System (please complete the following information):**
 - OS: Debian
 - Virtualization: /
 - Clients: Browser
 - Browser:Firefox
 - Jellyfin Version: master
 - Playback: /
 - Installed Plugins: TMDb Box Sets
 - Reverse Proxy: /
 - Base URL: /
 - Networking: /
 - Storage: /

**To Reproduce**

1. Go to the home page

**Screenshots**
![image](https://user-images.githubusercontent.com/21289123/89406130-ff452880-d71c-11ea-9cc8-ac0e86bb5130.png)

**Comment by Ullmie02** [comment]
Maybe caused by #3772?

**Comment by Bond-009** [comment]
Fixed by #3860
