### ISSUE TITLE
Metadata Cache for People

### ISSUE THREAD

**Issue by gottsman** [jellyfin/jellyfin#3830]
**Describe the bug**
/data/metadata/People appears to have multiple subdirectories with the same initial. Causes confusion with rsync snapshot script which moves files around unnecessarily.

Midnight Commander appears to have multiple directories with same name

Left hand side -> 3 'S' characters, 2 'U' characters, lowercase 'd'
Right hand side -> 2 'A' characters, 3 'E' characters
![jellyfin metadata cache](https://user-images.githubusercontent.com/6173136/89468813-3c71e080-d746-11ea-8b85-96312bab3db4.png)

**System (please complete the following information):**
 - OS: Centos 8
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Chrome
 - Jellyfin Version: Nightly - LinuxServer container
 - Playback: N/A
 - Installed Plugins: none currently
 - Reverse Proxy: Traefik
 - Base URL: none
 - Networking: Bridge
 - Storage: local

**To Reproduce**
1. N/A

**Expected behavior**
clean metadata cache with proper character formatting

**Logs**
Can be provided

**Screenshots**
See above

**Additional context**
Previously installed plugins, but have since removed. Not sure if those could create the issue.

**Comment by bugfixin** [comment]
I don't particularly see this as a bug with jellyfin - these directories are named differently, it's just your file browsing that is not correctly rendering the characters. E.g. I have O and Ó directories, 'O' has many people, but 'Ó' has a person named Ólafur Darri Ólafsson. This shouldn't cause files to move around unnecessarily, as rsync should interpret the different directories correctly and copy them as-is. 

Is it possible for you to perform an ls -lah of your directories to see an unfiltered

**Comment by gottsman** [comment]
I think the name that is causing the problem is "da'Vinchi". What's weird is that the lower case "d" subdirectory is created locally, but never makes it to the backup file system on unRAID with rsync. Something is getting munched and its always transferring/deleting the "d" and "D" directory contents.

Is there a way to convert the name to avoid the apostrophe? 

```
[kevin@hondo People]$ ls -lah
total 1.3M
drwxr-xr-x   37 kevin kevin 4.0K Jul 30 06:42 .
drwxr-xr-x    7 kevin kevin  100 Jul 30 08:36 ..
drwxr-xr-x    3 kevin kevin   29 Jul 29 20:40 5
drwxr-xr-x 2220 kevin kevin  64K Aug 14 17:26 A
drwxr-xr-x    8 kevin kevin  183 Jul 30 05:18 Á
drwxr-xr-x 1338 kevin kevin  40K Aug 13 17:15 B
drwxr-xr-x 1774 kevin kevin  56K Aug 13 17:15 C
drwxr-xr-x    3 kevin kevin   31 Jul 30 06:42 d
drwxr-xr-x 1739 kevin kevin  52K Aug 13 17:15 D
drwxr-xr-x 1024 kevin kevin  32K Aug 13 17:15 E
drwxr-xr-x    7 kevin kevin  139 Jul 30 05:46 É
drwxr-xr-x    3 kevin kevin   34 Jul 30 06:38 È
drwxr-xr-x  547 kevin kevin  16K Aug 14 17:26 F
drwxr-xr-x  950 kevin kevin  28K Aug 13 17:15 G
drwxr-xr-x  684 kevin kevin  20K Aug 13 03:54 H
drwxr-xr-x  298 kevin kevin  12K Aug 13 03:54 I
drwxr-xr-x 3281 kevin kevin  92K Aug 13 17:15 J
drwxr-xr-x 1245 kevin kevin  36K Aug 13 03:54 K
drwxr-xr-x 1288 kevin kevin  36K Aug 13 17:15 L
drwxr-xr-x 2480 kevin kevin  76K Aug 14 17:26 M
drwxr-xr-x  750 kevin kevin  24K Aug 14 17:26 N
drwxr-xr-x  213 kevin kevin 8.0K Aug 10 05:05 O
drwxr-xr-x    7 kevin kevin  162 Jul 30 06:38 Ó
drwxr-xr-x 1012 kevin kevin  32K Aug 14 17:26 P
drwxr-xr-x   22 kevin kevin 4.0K Aug 10 05:06 Q
drwxr-xr-x 1730 kevin kevin  52K Aug 13 17:15 R
drwxr-xr-x 1912 kevin kevin  56K Aug 13 17:15 S
drwxr-xr-x    3 kevin kevin   34 Jul 30 03:57 Š
drwxr-xr-x    3 kevin kevin   39 Jul 30 05:45 Ș
drwxr-xr-x 1292 kevin kevin  36K Aug 13 17:15 T
drwxr-xr-x   45 kevin kevin 4.0K Aug  9 23:44 U
drwxr-xr-x    3 kevin kevin   38 Jul 30 05:18 Ú
drwxr-xr-x  394 kevin kevin  12K Aug 13 03:54 V
drwxr-xr-x  451 kevin kevin  16K Aug 14 17:26 W
drwxr-xr-x   19 kevin kevin 4.0K Aug 13 03:54 X
drwxr-xr-x  155 kevin kevin 8.0K Aug 10 12:03 Y
drwxr-xr-x  124 kevin kevin 4.0K Aug 13 03:54 Z
[kevin@hondo People]$ ls -lah d
total 4.0K
drwxr-xr-x  3 kevin kevin   31 Jul 30 06:42  .
drwxr-xr-x 37 kevin kevin 4.0K Jul 30 06:42  ..
drwxr-xr-x  2 kevin kevin   24 Jul 30 06:42 "da'Vinchi"
[kevin@hondo People]$ 
```
