### ISSUE TITLE
Add `max-age=...` to Audio/videos API `Cache-Control` header

### ISSUE THREAD

**Issue by ExNG** [jellyfin/jellyfin#3842]
Currently the server responds when a media is requested (from `http://jellyfin/Audio/*` or `http://jellyfin/videos/*`) with the media and a `Cache-Control` header which just allows caching, but doesn't specify how long the file should be kept.
This leads to clients re-requesting the media every time its being played either when in loop or selected by the user.

I am not quite sure if there is already someone working this or something similar, thus i would be thankful for some feedback on this topic.

If this proposal is approved i would of course work on and submit the corresponding change in the source code.

Cache Control Header reference:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#Expiration

**Comment by cvium** [comment]
Cache what exactly?

**Comment by ExNG** [comment]
Cache the response body which should be either the audio file or a video piece, if i am right?

**Comment by cvium** [comment]
That's not really cacheable though

**Comment by ExNG** [comment]
Could you please elaborate on why its not cacheable. I thought in the case of audio it simply set as the audio source of the html audio element, which would mean it being able to cache the response body.

**Comment by cvium** [comment]
Assuming the browser respects cache headers for audio and video, it would only work for direct play. Transcodes have a unique ID generated every time.

**Comment by cvium** [comment]
Feature requests belong here btw: https://features.jellyfin.org/

But as I said, I don't think this is very useful and most users probably won't appreciate their cache being filled up.
