### ISSUE TITLE
Tags are cleared after updating library

### ISSUE THREAD

**Issue by NunzioDev** [jellyfin/jellyfin#3843]
**Describe the bug**
I updated from 10.5 to 10.6 and the software deleted all the tags I had entered (I checked library.db).
I have tried to restore library.db, but the next time the library is scanned they are deleted; I tried to uninstall and reinstall, but the result hasn't changed.

I tried adding new tags, via browser, and they are not deleted after library scan.

Is there a procedure I can use to import the old tags into a clean installation, without entering them manually?

**System:**
 - OS: Manjaro
 - Virtualization: none
 - Clients: Browser
 - Browser: Firefox 79, Chrome 80
 - Jellyfin Version: 10.6
 - Playback: 
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: none
 - Networking: Host
 - Storage: local

**To Reproduce**
1. Stop service
2. Replace library.db 
2. Start service
3. Go to Music tab
4. Select an item
5. Open Metadata and check the existence of tag inside tag's section 
6. Wait for the update to complete
7. Go to Music tab
8. Select previous item
9. Open Metadata and tag's section is empty

**Logs**
The system did not generate any logs during and after the scan procedure.

**Comment by mobamoba** [comment]
Same here. And you can't save tags anymore - edit the Metadata, add a Tag, click Save Changes then go look again and you'll see it's not there as if it was either instantly deleted or never saved to begin with.

**Comment by NunzioDev** [comment]
This is still an issue.

**Comment by Ullmie02** [comment]
Manually added tags get cleared during a library scan with "Search for missing metadata" but not with "Scan for new and updated files"

**Comment by Shadowghost** [comment]
Has been fixed in 10.9.6

**Comment by narvik01** [comment]
My manually added tags are still disappearing in 10.10.6.
