### ISSUE TITLE
[REQUEST/HELP] How to play an IPTV stalker service through Jellyfin.

### ISSUE THREAD

**Issue by MrPerson156** [jellyfin/jellyfin#3844]
Hi,
I have a paid IPTV stalker service which uses a dynamic DNS and a Mac address to authenticate but I can't figure out How to implement it into Jellyfin. All of the channels work fine in Kodi with the stalker add-on, but I would like all of my media to be all in one place for easy access.

I have tried the live TV menu and the IPTV plugin, but there are no options for a Mac address.
Does anybody know how to do this and/or is there a plugin?

Thanks in advance.

**Comment by shorewall** [comment]
I just solved the same issue in a two steps way, by a trick.
I catch the stalker link to be played (quickly because the link token expires) and I'm passing it to vlc for a local http ts restream.
Then added a dummy m3u list to jellyfin having as single url pointing the local link where vlc restream the stalker flow.
Jellyfin in that way is able to push the stream to my Lg tv.

**Comment by MrPerson156** [comment]
@shorewall Thanks for the reply.
I would love to try out the steps that you are using, could you please point me to a guide or explain the steps. I have been trying to catch the stalker link for 2 days now and I haven't managed it. Any help would be amazing.
Thanks again!

**Comment by shorewall** [comment]
I'm on Linux and I'we written the Stalker player myself using bash :-). So It's easy to catch the stalker link and pass it to cvlc for restreaming. It is now an automated task for my code.
On linux, I used tcpdump to catch the flow at the beginning and the final link pushed to the player.
If U re on win I cannot help U too much.

**Comment by MrPerson156** [comment]
Hi, I have a windows and a Mac machine, no linux though. I tried using Wireshark on Mac, but the Iptv service blocked it.

**Comment by shorewall** [comment]
U could try tcpdump for win. Sniffing all the the http traffic content on you pc network card and grepping for some tags. The stalker protocol in nothing else thant an http flow and some more headers containing tokens al like as the mac address.
When you see a flow containing a similar content: portal.php?type=...&action=create_link&cmd=....   then you get back a json containink the full link.

**Comment by MrPerson156** [comment]
Hi again,
I have found a Kodi plugin which will extract the links, and also works on windows, so I am going to try that. Would the links constantly break in Jellyfin if the token always changes though?

**Comment by shorewall** [comment]
Yes, the stalker token changes at any connectiona attempt. Thas why i extract the link and as fast as possible i pass the link to vlc for local restream. Jellyfin has to know a simple m3u list having a single entry as like a s this: http://local_testream_ip:port.
This is static. So every link you start using stalker / vlc restreming always to teh same address and then jellyfin will restream via dlna to yout tv.

**Comment by MrPerson156** [comment]
Does this mean that Only 1 channel can be played at a time then. The point of this project is to replace my moms old freest pvr box, so Will this method let her just choose what channel she wants to play and then play it, or will I need to restroom it each time?

**Comment by shorewall** [comment]
For what I know usually a stalker server allow only one active link at the same time. If I'm runnng a live flow starting a new one will trop the currently active one. Unless you pay more to have mode than one concurrent session.
So the limit is not the one entry m3u. But the stalket itself. But you could try using more than one concurrent ocal restreaming and adding more entries into the m3u.

**Comment by MrPerson156** [comment]
Thanks, ill give that a try. Its a shame that there is no plugin for Jellyfin like their is for Kodi, that would have been awesome.

**Comment by shorewall** [comment]
The problem is not jellyfin itself. A normal usual m3u is well supported. But a stalker link has a variablke token.
And that's completely another story. May be U can have a classic m3u provider using static links inside the m3u, so the problem is solved.

**Comment by MrPerson156** [comment]
Thanks for the reply, I now have a subscription with this service for a year, so I don't really want to waste it. They won't give me an m3u static link because they are worried about hackers. I just thought that it was strange that it works in Kodi but not Jellyfin.

**Comment by MrPerson156** [comment]
I have ended up just using STB emu pro on my Firestick to get the tv working, I will close this now. Thanks for all your help!
