### ISSUE TITLE
Cannot transcode 4K/HEVC video, ffmpeg AVFilterGraph reports No such filter: ''

### ISSUE THREAD

**Issue by ChaddyOwl** [jellyfin/jellyfin#3845]
**Describe the bug**

I'm trying to play a 4k/HEVC movie on a Chrome browser, but transcoding is failing, and Jellyfin reports that "This client isn't compatible with the media and the server isn't sending a compatible media format.".
Looking at the ffmpeg-transcode log, I see the following error:
`[AVFilterGraph @ 0x5599c1f55780] No such filter: ''
Error initializing complex filters.
Invalid argument`

Based on this message, I feel that there may be a format error in the `-filter_complex` parameter in the ffmpeg command, but I don't know enough about how this should be formatted to know for sure.

The command being executed is:
`/usr/lib/jellyfin-ffmpeg/ffmpeg -hwaccel vaapi -hwaccel_output_format vaapi -vaapi_device /dev/dri/renderD128 -i file:"/media/Movies/Star Wars The Rise of Skywalker (2019)/Star Wars The Rise of Skywalker (2019) WEBDL-2160p.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -codec:v:0 h264_vaapi  -b:v 49566976 -maxrate 49566976 -bufsize 99133952 -profile:v high -level 41  -force_key_frames:0 "expr:gte(t,0+n_forced*3)" -g 72 -keyint_min 72 -sc_threshold 0 -filter_complex "[0:3]scale=3840x1608[sub];[0:0],hwdownload[base];[base][sub]overlay,format=nv12,hwupload" -start_at_zero -vsync -1 -codec:a:0 libmp3lame -ac 2 -ab 384000 -af "volume=2" -copyts -avoid_negative_ts disabled -f hls -max_delay 5000000 -hls_time 3 -individual_header_trailer 0 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/config/transcodes/e862aa3f640364df6528bdfee3144dba%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/config/transcodes/e862aa3f640364df6528bdfee3144dba.m3u8"`

I've attached the full transcode log for this attempt.

**System (please complete the following information):**
 - OS: Linux / Synology DS918+
 - Virtualization: Docker (official Jellyfin)
 - Clients: Browser
 - Browser: Chrome Version 84.0.4147.105
 - Jellyfin Version: 10.6.2
 - Playback: Transcode 
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: none
 - Networking: Host
 - Storage: Local

**To Reproduce**

**Expected behavior**

**Logs**

[SWTROS_ffmpeg_transcode.txt](https://github.com/jellyfin/jellyfin/files/5043953/SWTROS_ffmpeg_transcode.txt)

**Screenshots**

**Additional context**

**Comment by dearjoey** [comment]
I have encountered the same problem.

**Comment by ChaddyOwl** [comment]
I can confirm that my original issue is fixed, as of Jellyfin 10.6.4. Thanks!

**Comment by Hunter259** [comment]
How did you fix this? I am having the same issue but I'm also on 10.6.4. Same exact error.

**Comment by ChaddyOwl** [comment]
> How did you fix this? I am having the same issue but I'm also on 10.6.4. Same exact error.

@Hunter259 I'm assuming that the linked Pull Request fixed my problem. After upgrading from 10.6.2 -> 10.6.4, playing the same file in Chrome now no longer has problems. I can see that the ffmpeg command generated has changed, and the `-filter` component is no longer present (looks to be replaced by a `-vf` component).
The only other change for me is that the version of Chrome has been updated since my 10.6.2 testing (now at 87.0.4280.88), but I don't know if that has any impact.

**Comment by Hunter259** [comment]
Mine actually still has -filter_complex. Very strange.

**Comment by ChaddyOwl** [comment]
Looks like I can reproduce it. The quoted PR mentioned problems with subtitles.
I wasn't aware that I had subtitles enabled in the past. In my recent tests, subtitles were set to "Off" and it works fine. But if I enable subtitles (set to English), I get my original error once again, and I see the `-filter_complex` component in the ffmpeg command.
I'll re-open this bug. Thanks!

**Comment by crobibero** [comment]
If possible can you please retry with 10.7~rc1

**Comment by ChaddyOwl** [comment]
@crobibero I just spun up a container with 10.7-rc1, and tried the same test, and in this version it looks to be working, both with and without subtitles. With subtitles, the `-filter_complex` component is present, but the filter definition looks to be formatted better. Here's the full filter definition in the command now:
`-filter_complex "[0:3]scale=3840x1608[sub];[0:0]scale_vaapi=format=nv12,hwdownload[base];[base][sub]overlay,format=nv12,hwupload"`
Thanks!

**Comment by nyanmisaka** [comment]
Fixed in https://github.com/jellyfin/jellyfin/commit/db07510017dc589da38698fd5e5f9afc55092334

**Comment by ChaddyOwl** [comment]
As noted above, this looks to be fixed in 10.7-rc1, so I'll close this.
