### ISSUE TITLE
Cast API & SyncPlay Support

### ISSUE THREAD

**Issue by iwalton3** [jellyfin/jellyfin#3855]
I recently released SyncPlay support for MPV Shim, which works great, but [can only be accessed through MPV Shim's menu](https://github.com/iwalton3/jellyfin-mpv-shim/releases/tag/v1.7.0) and not the casting application. Right now when you cast a SyncPlay session from the web app, it starts playback normally on MPV Shim and produces an error message on the controlling client.

I shipped the desktop client with a temporary workaround that proxies join requests from the web UI to the client, but a similar trick cannot be used for other clients casting to the application.

I can think of two main options to make this work correctly:

 - Option 1: When the controlling application casts to another application through SyncPlay, the server should send the regular playback request as well as a SyncPlay command to enable SyncPlay. This should also work in all applications that are compatible with SyncPlay today.
 - Option 2: When the controlling application casts to another application through SyncPlay, the server should send the regular playback request with the SyncPlay group ID included in the request. The client would then be able to join. This is also part of MPV Shim, but nothing currently uses it. (Simply add a `SyncPlayGroup` parameter to the `PlayNow` command arguments.)

**Comment by iwalton3** [comment]
This needs to be looked at.

**Comment by nielsvanvelzen** [comment]
Is this issue since 10.7 or 10.6?

CC @OancaAndrei maybe you could look at this

**Comment by OancaAndrei** [comment]
> Is this issue since 10.7 or 10.6?

Since 10.6. Support for Remote sessions/Chromecast was under work, but I had to pause it because the Chromecast receiver was/is seeing a major rewrite.

I think that I can split and port some code to support Remote sessions though. Shouldn't take long.

**Comment by OancaAndrei** [comment]
I think I went for option 1 which requires the *receiver application* to have an open `ws` connection.
The *caster application* requests to join a SyncPlay group then does the same for the session under control. The *receiver application* will receive the message to enable SyncPlay through the `ws` as usual.

Playback control then happens using SyncPlay messages.

Do you think that this flow can work for the MPV Shim as well? For the Chromecast I had to also create a new dedicated session for it, as the web-client was sharing it directly. I can backport this "session fork" method too if it is needed.

**Comment by iwalton3** [comment]
It sounds like that will work. MPV Shim already establishes a websocket session for all playback control. SyncPlay is completely broken in MPV Shim due to the API changes, so that will likely need attention. Thankfully I don't think anything else is obviously broken. 

> I can backport this "session fork" method too if it is needed.

This isn't needed for SyncPlay, but it could resolve my issue with having to create two sessions for the web client and Python backend. (Right now I just send creds to the python backend instead, but I could use session fork to avoid that.)

**Comment by OancaAndrei** [comment]
I think I'll drop the "fork session" idea and opt for the *Quick Connect* auth instead, as it looks more secure than sharing the auth token. I'll have to see if it can be used under the hood even when it's disabled on the server.

**Comment by mpeter50** [comment]
The issue still exists. I think the issue should be reopened, and marked with a "confirmed" tag or something that makes the stale bot calm down.
