### ISSUE TITLE
Better error message for wrong ffmpeg path

### ISSUE THREAD

**Issue by LeoVerto** [jellyfin/jellyfin#387]
Right now having the ffmpeg path not set just results in playback failing and a cryptic error in the logs like this:

    [20:08:04] [ERR] Error starting ffmpeg
    System.InvalidOperationException: Cannot start process because a file name has not been provided.

Detecting whether the ffmpeg path is set correctly and if not, displaying an appropriate message to either administrators only/users in general (possibly even before playback is started) should be simple enough to implement and be a useful quality of life improvement.

**Comment by JustAMan** [comment]
I think we should make ffmpeg version check at startup, I remembered seeing quite a few issues people had which were solved by just installing ffmpeg. 

Plus current code works correctly only with 4.0.x, so any version mismatch should be a warning at least.

**Comment by joshuaboniface** [comment]
Agreed, but what's weird is on Debian, even though the `ffmpeg path` in the UI is empty and shows a red error, playback doesn't fail to find it at `/usr/bin/ffmpeg`. @LeoVerto does setting it in the UI fix the playback failure? If so we should focus on making sure that's populated with a sane default for each platform as well.

**Comment by LeoVerto** [comment]
This issue isn't about the UI, that is #478. I clarified the title a bit but this is purely about improving the error message when the ffmpeg path isn't set correctly.
