### ISSUE TITLE
Jellyfin keeps restarting since upgrade to 10.6.2

### ISSUE THREAD

**Issue by Legogris** [jellyfin/jellyfin#3883]
**System (please complete the following information):**
 - OS: debian
 - Virtualization: docker (linuxserver image)
 - Jellyfin Version: 1.0.6.2
 - Installed Plugins:
  - Anime (9.0.0.0)
  - AudioDB (10.6.2.0)
  - Fanart (5.0.0)
  - Kodi Sync Queue (5.0.0.0)
  - MusicBrainz (10.6.2.0)
  - OMDb (10.6.2.0)
  - Open Subtitles (9.0.0.0)
  - Playback Reporting (7.0.0.0)
  - TheTVDB (10.6.2.0)

**To Reproduce**
This is an upgrade from 10.5.5.
Jellyfin keeps restarting since the upgrade, always within ~0.5-5 min of starting.
Even enabling debug logs I see nothing standing out neither in jellyfin logs, stderr or stdout.

The one pattern I notice it that it seems to happen right or shortly after this:

```
[02:28:30] [INF] [5] Emby.Server.Implementations.ScheduledTasks.TaskManager: StartupTrigger fired for task: Update Plugins
[02:28:30] [INF] [5] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queueing task PluginUpdateTask
[02:28:30] [INF] [11] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing Update Plugins
[02:28:30] [WRN] [17] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 204 to 10.1.1.6. Time (slow): 0:00:01.0857497. http://xxx/Sessions/Playing/Progress
[02:28:31] [INF] [17] Emby.Server.Implementations.ScheduledTasks.TaskManager: Update Plugins Completed after 0 minute(s) and 1 seconds
[02:28:31] [INF] [17] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
```

This seems to be separate from the two other issues I filed recently:
https://github.com/jellyfin/jellyfin/issues/3881 (updated all plugins to most recent versions, which made errors at startup disappear)
https://github.com/jellyfin/jellyfin/issues/3882 (while this also seems to trigger a crash immediately in the rare instance that jellyfin manages to stay alive long enough, it seems like a plugin bug and a separate issue)

**Comment by Legogris** [comment]
All plugins removed, one by one, with restart between. Still same result.

**Comment by Legogris** [comment]
Same behavior with latest nightly build

**Comment by Legogris** [comment]
Rolling back to 10.5.5 (after restoring the entire config folder from pre-upgrade backup) and no crashes anymore. I can't think of further directions for debugging , so leaving this here for now unless anyone has any ideas.

**Comment by Legogris** [comment]
Fingers crossed that this is resolved by https://github.com/jellyfin/jellyfin/pull/3831

**Comment by Legogris** [comment]
Unfortunately same issue with deb release `20200815.3-unstable`

**Comment by Legogris** [comment]
strace of the thread causig the crash
https://gist.github.com/Legogris/e4ba55fe088d29a06ed817a86bfa0d39

**Comment by ssyangchn** [comment]
same issues in 10.6.3

**Comment by Legogris** [comment]
@ssyangchn In my case, it seems this is due to the sqlite database now being used in `writeahead` mode whereas pre-10.6 it was in `delete` or `truncate`. This causes issues if the database is stored on a non-local filesystem. What's the fs of your config directory?

**Comment by alex9099** [comment]
Not sure if this is somehow related:

```
Unhandled exception. System.Net.NetworkInformation.NetworkInformationException (2): An error was encountered while querying information from the operating system. ---> System.AggregateException: One or more errors occurred. (Could not find a part of the path '/sys/class/net/veth8e59bf2/mtu'.)
 ---> System.IO.DirectoryNotFoundException: Could not find a part of the path '/sys/class/net/veth8e59bf2/mtu'
```

I'm getting spammed by that, not sure if that is a reason for it to be failing a lot on me. Either videos don't load, or they simply stop giving sound or a rewind out of nowhere. Not sure if that is somehow related to the bug on this issue
