### ISSUE TITLE
Actors pictures missing when using only local metadata

### ISSUE THREAD

**Issue by 1024mb** [jellyfin/jellyfin#3888]
**Describe the bug**

All the actors images are missing when only local metadata is used.

**System (please complete the following information):**
 - OS: Windows 10
 - Virtualization:
 - Clients: Browser, Android
 - Browser: Firefox
 - Jellyfin Version: 10.6.2
 - Playback:
 - Installed Plugins:
 - Reverse Proxy:
 - Base URL:
 - Networking:
 - Storage: local

**To Reproduce**

1. Add a library and disable all providers
2. Browse an entry (movie/tv show/whatever)

**Expected behavior**

To see the actor images.

**Screenshots**

![firefox_2020-08-13_01-55-40](https://user-images.githubusercontent.com/9301204/90103471-2ea0fa00-dd08-11ea-8b71-02064c59f319.png)

**Additional context**

I didn't know if this is a bug or a feature request.  
The actor pictures are stored on folders named `.actors`, one for each movie/TV show. Kodi is able to show the images so I guess the naming/storing conventions are respected.

**Comment by 1024mb** [comment]
Still happening.

**Comment by 4ndreasH** [comment]
same for me (jellyfin_10.7.0~rc2)

**Comment by natrius** [comment]
i created a custom folder for testing `export\mediafiles\family\metadata\name name\poster.jpg` and added in the nfo `<thumb>/export/mediafiles/family/metadata/name name/poster.jpg</thumb>` as well. But it does not get filled this way, is it possible Jellyfin can not handle if these pictures are somewhere else?

**Comment by jfranki** [comment]
I believe #4989 did not solve this issue as the problem is still happening (10.7.6), therefore I think this should be reopened.

**Comment by crobibero** [comment]
> I believe #4989 did not solve this issue as the problem is still happening (10.7.6), therefore I think this should be reopened.

The PR that you've linked was not in the 10.7.x release.

**Comment by wyq977** [comment]
> I copied all actor picture files as described below. It works, but at the ooment an actorimage in Jellyfin will only be shown if I at least click it once in Jellyfin Cast&Crew. (But of course I don´t want to click every actor image... I try to find a solution for that)
> 
> https://www.reddit.com/r/jellyfin/comments/b7huxv/actor_thumbnails_where_does_jellyfin_look_for_them/ //metadata/People/C/Chiwetel Ejiofor/poster.jpg
> 
> I would prefer it when files in the movie directory (.actors) could be used.
> 
> Regards, Marc

Can confirm that this is still happening in 10.7.7 so I hope this issue could be reopened. I only use local metadata downloaded from tmm or Sonarr, photos of the actors only shows up when I clicked on it at least once. 

And actor image location/url are specified in `tvshow.nfo`:

e.g.

```
  <actor>
    <name>Johnny Galecki</name>
    <role>Leonard Hofstadter</role>
    <thumb>https://image.tmdb.org/t/p/h632/gkwMiwHX7lmfjORRJi6T6SM3ppo.jpg</thumb>
    <profile>https://www.themoviedb.org/person/16478</profile>
    <tmdbid>16478</tmdbid>
  </actor>
  <actor>
    <name>Jim Parsons</name>
    <role>Sheldon Cooper</role>
    <thumb>https://image.tmdb.org/t/p/h632/sa05slVgacuXe94UFnQs4rfqZL4.jpg</thumb>
    <profile>https://www.themoviedb.org/person/5374</profile>
    <tmdbid>5374</tmdbid>
  </actor>
```


```
Version: 10.7.7

Operating System: Darwin

Architecture: X64
```

**Comment by cvium** [comment]
> Can confirm that this is still happening in 10.7.7 so I hope this issue could be reopened.

I can confirm that the fix is still not in 10.7.x. It is, however, in 10.8-alpha/master/unstable. So no, it will not be reopened.

**Comment by wyq977** [comment]
ty for the update and the fix!

**Comment by deltonio2** [comment]
I have the same problem with version 10.8.0.
However, if I click on the actor, his photo is displayed correctly.
If I go back to the film, the thumbnails displays well.

![1](https://i.ibb.co/tJsJBRD/1.png)

![2](https://i.ibb.co/bJNSzS0/2.png)

![3](https://i.ibb.co/x3XH8kG/3.png)
