### ISSUE TITLE
Unstable: DLNA path wrong in DlnaServerController

### ISSUE THREAD

**Issue by BaronGreenback** [jellyfin/jellyfin#3906]
In DlnaServerController.cs the HttpGet are wrong for the 3 services. (The names are repeated).

They should be

[HttpGet("{serverId}/ContentDirectory")]
[HttpGet("{serverId}/ContentDirectory.xml", Name = "GetContentDirectory_2")]

[HttpGet("{serverId}/MediaReceiverRegistrar")]
[HttpGet("{serverId}/MediaReceiverRegistrar.xml", Name = "GetMediaReceiverRegistrar_2")]

[HttpGet("{serverId}/ConnectionManager")]
[HttpGet("{serverId}/ConnectionManager.xml", Name = "GetConnectionManager_2")]

**Comment by BaronGreenback** [comment]
Also Emby.Dlna.ControlResponse.cs

does implement the .ToString method - so dlna browsing isn't working

**Comment by BaronGreenback** [comment]
Jellfyfin.Api.Controllers.AudioController.cs need the following additions - as dlna uses stream.mp3

public async Task<ActionResult> GetAudioStream

        [HttpGet("{itemId}/stream.mp3", Name = "GetAudioStream_2")]
        [HttpHead("{itemId}/stream.mp3", Name = "HeadAudioStream_2")]

**Comment by crobibero** [comment]
Are you saying the route is needed? It's already there under 
```
[HttpGet("{itemId}/{stream=stream}.{container?}", Name = "GetAudioStreamByContainer")]
[HttpHead("{itemId}/{stream=stream}.{container?}", Name = "HeadAudioStreamByContainer")]
```

**Comment by BaronGreenback** [comment]
Yes - but it doesn't seem to match.

**Comment by BaronGreenback** [comment]
Have you seen my comment on the 1st item (shouldn't edit)

DlnaServerController.cs needs

[HttpGet("{serverId}/MediaReceiverRegistrar")]
[HttpGet("{serverId}/MediaReceiverRegistrar/MediaReceiverRegistrar")]
[HttpGet("{serverId}/MediaReceiverRegistrar/MediaReceiverRegistrar.xml", Name = "GetMediaReceiverRegistrar_2")]

[HttpGet("{serverId}/ConnectionManager")]
[HttpGet("{serverId}/ConnectionManager/ConnectionManager")]
[HttpGet("{serverId}/ConnectionManager/ConnectionManager.xml", Name = "GetConnectionManager_2")]

[HttpGet("{serverId}/ContentDirectory")]
[HttpGet("{serverId}/ContentDirectory/ContentDirectory")]
[HttpGet("{serverId}/ContentDirectory/ContentDirectory.xml", Name = "GetContentDirectory_2")]
