### ISSUE TITLE
Can't search for channel name from live TV

### ISSUE THREAD

**Issue by ThaChillera** [jellyfin/jellyfin#3909]
**Describe the bug**
When using the liveTV feature, searching for the channel name displays no results

**System (please complete the following information):**
 - OS: Ubuntu
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Firefox 79
 - Jellyfin Version: 10.6.2
 - Playback: None
 - Installed Plugins: Nothing relevant
 - Reverse Proxy: nginx
 - Base URL: private
 - Networking: Host
 - Storage: local/not relevant

**To Reproduce**

1. Add an m3u IPTV link - not sure if I can share a link since the stream isn't legal but it serves 68000 channels (a lot!)
2. Wait for it to obtain channel/guide data (took me 10 hours)
3. Use search function - No results!

**Expected behavior**
When I have multiple channels that contain the name Cartoon Network, I expect that searching for 'Cartoon' will list all or atleast some of them

**Logs**
Some excerpts of the log when attempting to search, including some errors it posts: [log.txt](https://github.com/jellyfin/jellyfin/files/5081399/log.txt)

**Additional context**
This IPTV service contains 68000 channels, this might be a factor in non-performant searching.

**Comment by seanbirkhead** [comment]
Same Problem on Windows

**Comment by Anan5a** [comment]
Same problem 
Server is debian 10 and search on live tv doesn’t work on any client!

**Comment by ThaChillera** [comment]
I can confirm this issue still exists

**Comment by cocool97** [comment]
Is it an error or a missing feature ?
I cannot look for channel names neither, but I don't get any errors

**Comment by ThaChillera** [comment]
Don't get any errors either afaik, just not the search results I'd expect

**Comment by nicrgren** [comment]
I've got the same issue. It seems channels are not included in search, no errors.

**Comment by dennisstorm-lab** [comment]
Same issue for me.

**Comment by thornbill** [comment]
Fixed in https://github.com/jellyfin/jellyfin-web/pull/2683.

Channels now have a dedicated row and display when searching in the Live TV library.
