### ISSUE TITLE
Unable to connect to Jellyfin on first start

### ISSUE THREAD

**Issue by quentinus95** [jellyfin/jellyfin#3923]
**Describe the bug**
I'm trying to start the app, but I can't pass the first screen of the wizard. Screen locks on a loading spinner when clicking on `Next` on the language selection screen.

**System (please complete the following information):**
 - OS: Debian
 - Virtualization: Docker
 - Clients: Web
 - Browser: Chrome 84
 - Jellyfin Version: docker.io/jellyfin/jellyfin:10.6.3
 - Playback: N/A
 - Installed Plugins: N/A
 - Reverse Proxy: N/A
 - Base URL: None
 - Networking: N/A
 - Storage: NFS

**To Reproduce**
Start a new container and try to use the wizard.

**Expected behavior**
Being able to log in the app.

**Logs**
When clicking on Next, server-side:

![image](https://user-images.githubusercontent.com/8060564/90401876-e0408200-e09e-11ea-9cda-b3fc60560240.png)

```
[13:19:29] [INF] [20] Jellyfin.Api.Auth.CustomAuthenticationHandler: CustomAuthentication was not authenticated. Failure message: Invalid user
```

Client-side:

```
Error opening web socket: Error: Cannot open web socket without access token.
bundle.js?v=17:266 Requesting url without automatic networking: https://<redacted>/Startup/Configuration
bundle.js?v=17:266 Requesting url without automatic networking: https://<redacted>//Startup/Configuration
bundle.js?v=17:266 POST https://<redacted>/Startup/Configuration net::ERR_ABORTED 400
w @ bundle.js?v=17:266
value @ bundle.js?v=17:266
value @ bundle.js?v=17:266
(anonymous) @ start.js?v=17:1
Promise.then (async)
save @ start.js?v=17:1
onSubmit @ start.js?v=17:1
dispatch @ bundle.js?v=17:25
m.handle @ bundle.js?v=17:25
/web/index.html?start=wizard#!/wizardstart.html?start=wizard:1 Uncaught (in promise) Response {type: "basic", url: "<redacted>/Startup/Configuration", redirected: false, status: 400, ok: false, …}
```

When trying to login using the login form (bypassing the wizard), server-side, trying to connect with username `jellyfin`, no password:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Emby.Server.Implementations.ResourceFileManager.GetResourcePath(String basePath, String virtualPath)
   at MediaBrowser.WebDashboard.Api.DashboardService.Get(GetDashboardResource request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

**Comment by csveritas** [comment]
Same issue on Debian 4.19 in docker behind reverse proxy, but when I click the back arrow I also see 
```
jellyfin         | [02:50:30] [ERR] [68] Emby.Server.Implementations.HttpServer.HttpListenerHost: Could not find handler for /controllers/auth/login.js
jellyfin         | [02:50:30] [ERR] [68] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: Unable to find the specified file. URL: http://<internalDomain>/controllers/auth/login.js?v=21
```
Looks like a broken reference to the file that's actually at `/web/controllers/auth/login.js` ?

**Comment by johnhamelink** [comment]
I'm also experiencing this issue, it happened to me while modifying the poster of a TV show. The iOS app continues to work fine: it seems to be an issue with the web component only.

**Comment by quentinus95** [comment]
It looks like this has been fixed in `10.6.4`.

**Comment by CalebFenton** [comment]
I'm having the same issue with 10.6.4 on Windows. I'm getting this error in the log when trying to get past the very first screen in the setup wizard:
```[2020-12-18 15:11:02.583 -08:00] [INF] [6] Jellyfin.Api.Auth.CustomAuthenticationHandler: "CustomAuthentication" was not authenticated. Failure message: "Invalid user"
[2020-12-18 15:11:02.592 -08:00] [INF] [10] Jellyfin.Api.Auth.CustomAuthenticationHandler: "CustomAuthentication" was not authenticated. Failure message: "Invalid user"
```

**Comment by zenodotus280** [comment]
For anyone else reading this in the future, try switching between your local IP, localhost, and 127.0.0.1. Takes a minute and may save you hours - it did for me.
