### ISSUE TITLE
Jellyfin pops up in Windows Explorer and Doesn't Require Signing In

### ISSUE THREAD

**Issue by hwittenborn** [jellyfin/jellyfin#3926]
OS of Host: Ubuntu 20.04.1

Issue:
After recently doing some things for my parents laptop, I opened the File Explorer on Windows 10 to see my Jellyfin instance pop up. After clicking it to see what would happen, I saw that it didn't prompt for a password or anything, it just connected.

I'm not sure if this is Jellyfin-related or not, but it's a big security issue if anything somehow got exposed.

**Comment by PrplHaz4** [comment]
This is probably the Jellyfin DLNA server - disable it if you don't want it to show up on your network, or assign a user with limited permissions as the DLNA "Default user" to restrict how much is visible on the local network.

**Comment by hwittenborn** [comment]
That looks like it might've been it, I've disabled it, will check everything tomorrow.

**Comment by anthonylavado** [comment]
It is indeed the DLNA server.
