### ISSUE TITLE
Jellyfin on Chromecast always reports being idle regardless of playback status

### ISSUE THREAD

**Issue by 4ntsu** [jellyfin/jellyfin#3963]
**Describe the bug**
When casting to a Chromecast device from the Android app or from Google Chrome, regardless of the actual media playback status, when the Chromecast device is queried for its status the result is "Idle (Jellyfin for Google Cast)".

**System (please complete the following information):**
 - OS: Arch Linux
 - Virtualization: LXC (Proxmox)
 - Clients: Android app or Chrome browser casting to Chromecast (2nd gen)
 - Browser: Google Chrome 84
 - Jellyfin Version: 10.6.3
 - Playback: both transcoding and direct
 - Installed Plugins: AudioDB, Kodi Sync Queue, MusicBrainz, OMDb, Open Subtitles, TVHeadend, TheTVDB
 - Reverse Proxy: nginx
 - Base URL: none
 - Networking: Internal, on the same subnet. Internal DNS points the server's fqdn to the local address of the proxy to avoid hairpin NAT.
 - Storage: NFS

**To Reproduce**

1. Open the Jellyfin app on Android or the browser page in Google Chrome.
2. Click the "cast" icon and select a Chromecast device.
3. Play a video. Video starts playing on the TV connected to the Chromecast.
4. Query the Chromecast's status with an application like [go-chromecast](https://github.com/vishen/go-chromecast), for example:
`go-chromecast --device-name "TV" status`
5. The application returns:
`Idle (Jellyfin for Google Cast), volume=1.00 muted=false`

**Expected behavior**
Upon being queried, the device should return the current playback status (playing, buffering, paused, etc). All other applications tested (Youtube, Disney+, MX Player, Spotify) report their status correctly. Examples:

```
$ go-chromecast --device-name "TV" status
[Ycz6TXrP-W8] YouTube (PLAYING), title="FINALLY... a Ryzen Mini PC!", artist="", time remaining=515s/929s, volume=1.00, muted=false

$ go-chromecast --device-name "TV" status
Prod MXPlayer (PLAYING), title="some_video.mp4", artist="", time remaining=4s/676s, volume=1.00, muted=false
```

**Logs**
N/A

**Screenshots**
N/A

**Additional context**
While this does not affect the actual playback of media, it's not the expected behaviour, and prevents go-chromecast from controlling media playback, since the device reports as not playing anything:
```
$ go-chromecast --device-name "TV" pause
unable to pause cast application: media not yet initialised, there is nothing to pause
```

**Comment by SteveDinn** [comment]
This might be better suited to the [jellyfin-chromecast](https://github.com/jellyfin/jellyfin-chromecast/issues) repo.

**Comment by 4ntsu** [comment]
Apologies and thanks for pointing me to the correct repo. I will reopen the issue there.
