### ISSUE TITLE
[bug]Primary image keeps reverting to default image after library sync on movies that has an image file in its path

### ISSUE THREAD

**Issue by Mmollle** [jellyfin/jellyfin#3964]
Running jellyfin (10.6.3) as a docker.

What im trying to do: Change the Primary image, either by downloading it automatically or manually adding it through the Edit Images feature

Problem: This mostly works without any complications BUT in cases where the movie has an image file that resides within the same folder as the movie and it uses this as the default primary image. After I change to a different image, on the next library sync it reverts back to the old default image again.

**Comment by Mmollle** [comment]
To add some further information:

I find this behaviour a bit annoying. I dont think that just because there is an image file inside a movies folder it should be forcing this image to be the Primary image of the movie.

How to reproduce:
Have an image file inside the same folder as a movie. This image should automatically be applied as the Primary image on the next sync, even if you previously have chosen a different Primary image this one will be overridden. Try to change to a different Primary image. On the next sync the image from the file will be back as the Primary image.

**Comment by hurricane-footsore** [comment]
The issue still exists or has returned for me in 10.11.11 windows.
