### ISSUE TITLE
Virtual "TV Shows" and "Movies" library folders show nothing within unless user has access to all libraries

### ISSUE THREAD

**Issue by SteveDinn** [jellyfin/jellyfin#3978]
**Describe the bug**

Unless a user has the "Enable access to all libraries" checkbox checked in the "Access" tab of the user dashboard, that user can see nothing inside the virtual "TV Shows", "Movies", and "Music" folders created when one or more library folders are "automatically grouped" from the "Home" section of the user's preferences.

**System (please complete the following information):**
 - OS: Ubuntu 16.04
 - Virtualization: docker
 - Clients: Browser
 - Browser: latest stable Chrome on Ubuntu 20.04
 - Jellyfin Version: 10.6.3
 - Base URL: None
 - Networking: host

**To Reproduce**

1. Have a library.
2. Uncheck **Users / [User] / Access / Allow access to all libraries** and check all libraries explicitly. 
3. Log in as that user.
4. Select some libraries under **User / Settings / Home / Library Folders**
5. Browse to the new virtual folder created on the home screen.
6. See no content.

**Expected behavior**

The user should be able to see whatever content in the virtual consolidated folder that they have access to, regardless if they have access to "all libraries" or each library explicitly.

**Logs**

[2020-08-24 23:58:01.052 -03:00] [WRN] [77] MediaBrowser.Api.UserLibrary.ItemsService: "guest" is not permitted to access Library "TV Shows".

**Comment by rayures** [comment]
Having the same issue. 

have a library with many folders/shows (ie: /series/ ), that works fine. 
created a new library which has one show/folder ( ie: /series/show1/). 

when selecting that new library on the home screen it is empty.

**Comment by PrplHaz4** [comment]
> 
> 
> Having the same issue.
> 
> have a library with many folders/shows (ie: /series/ ), that works fine.
> created a new library which has one show/folder ( ie: /series/show1/).
> 
> when selecting that new library on the home screen it is empty.
> 
> users with access to all libraries have this issue.
> user with only access to this new library has this issue.
> 
> logs have a warning in them:
> Emby.Server.Implementations.Library.LibraryManager: Found duplicate path: "/data/tvshows/show1"

This looks like a different issue as it is not resolved by "Enable Access to All Libraries", and has a different error log...so open a new issue with the details....

**Comment by crobibero** [comment]
fixed by https://github.com/jellyfin/jellyfin/pull/4002
