### ISSUE TITLE
Hidden Directory Not Recognized

### ISSUE THREAD

**Issue by zzc-tongji** [jellyfin/jellyfin#3979]
Hidden directories and files (name with the prefix `.`) are not recognized. Paths included hidden directories can be added but will be ignored when scanning.

The problem happens after version 10.6.0 (which does not happen in version 10.5.x).

**Comment by LolHens** [comment]
Just wanted to comment on this because I actually find this behavour desirable. I use directories with a dot prefix to save things like iso images of my disks and other files next to my movies and I really want jellyfin to exclude these.
