### ISSUE TITLE
Display/sort order for Money Heist  unavailable 

### ISSUE THREAD

**Issue by LeducH** [jellyfin/jellyfin#3986]
**Describe the bug**
Add 'Money Heist' to the library 
THETVDB.COM SERIES ID 327417

There is no option for Netflix order 

**System (please complete the following information):**
 - OS: [Debian,]
 - Virtualization: [Docker,]
 - Clients: [Browser,.]
 - Browser: [ Chrome 80,]
 - Jellyfin Version: Version: 10.6.2
 - Playback: [Direct Play, ] 
 - Installed Plugins: [ none,.]

 - Storage: [e.g. local, NFS, cloud]

**To Reproduce**

1. Go to 'TV Shows'
2. Click on the show 'money heist'
3. click on 'edit metadata'
4. see there is no option for the Display order 'Netflix' 

**Expected behavior**

There is a  option for 'Netflix' Display order  

check [tvdb](https://www.thetvdb.com/series/la-casa-de-papel) for display option 
**Logs**

**Screenshots**

**Additional context**

**Comment by NikolaTesla17** [comment]
As far as I can tell, the server doesn't really support this functionality yet. I don't believe display order is scraped for any shows. Perhaps make a feature request [here](https://features.jellyfin.org/)?

**Comment by LeducH** [comment]
Still not working

**Comment by kooolarpan** [comment]
Please fix this issue.

**Comment by cvium** [comment]
No. https://forums.thetvdb.com/viewtopic.php?p=175881#p175881
