### ISSUE TITLE
No artist picture shown if artist name contain special characters

### ISSUE THREAD

**Issue by emaen** [jellyfin/jellyfin#3990]
**Describe the bug**
- I've got a few music artists  whose picture (folder.jpg) are not shown
All artist have a correct folder structure and all of them have a correct 'folder.jpg' file.
- It seems to be produced when artist name contain specials characters
ex : 'Jean-michel Jarre' (dash) or 'AC/DC' (slash) or 'Bill haley & his comets' or 'Gary Clark Jr.' (final point)
BUT it perfectly works for 'Björk' (ö seems to not be a problem)
- Metadata structure seems to be revelant

**System (please complete the following information):**
 - OS: windows seven
 - Virtualization: no
 - Clients: Browser and Android
 - Browser: firefox and chromium ( all version)
 - Jellyfin Version: 10.6.2 and before
 - Playback: 
 - Installed Plugins: 
 - Reverse Proxy:
 - Base URL: none
 - Networking: 
 - Storage:local and smb

**To Reproduce**
having music artits with name with a special character

**Expected behavior**
see folder.jpg picture of the artist

**Logs**

**Screenshots**
![jellyfin special characters - 1](https://user-images.githubusercontent.com/29975718/91311341-44f09080-e7b3-11ea-96e5-f0a314fee1f5.jpg)
![jellyfin special characters - 2](https://user-images.githubusercontent.com/29975718/91311493-72d5d500-e7b3-11ea-92b5-34fcdd2d0f0e.jpg)
![jellyfin special characters - 3](https://user-images.githubusercontent.com/29975718/91312602-b5e47800-e7b4-11ea-9ee6-11eee3c12c5d.jpg)
![jellyfin special characters - 4](https://user-images.githubusercontent.com/29975718/91312610-b977ff00-e7b4-11ea-957d-8c9841ddb20d.jpg)

**Additional context**

**Comment by emaen** [comment]
I'm confirming that this issue is still affects me with v 10.6.4 and with v 10.7. rc1

See below : 
Red circles : names with an "-"  where no pictures were found by jellyfin ( but "folder.jpg", provided by myself, still exists in artist folder).
Yellow circles : names with an "-" where I must put an image by using" Jellyfin GUI > modify image " in order to have one.

![jellyfin-names](https://user-images.githubusercontent.com/29975718/103153053-e56cb680-478d-11eb-9f4b-9314cae9d0b5.jpg)

**Comment by emaen** [comment]
Using jellyfin 10.7.5 and after a clean install ( deleted all the database then let jellyfin reconstruct it) : 

Most of the issue is gone BUT still some names makes trouble.
Ex : AC/DC, Bill Haley & his comets or Boney M.

For each one of these artists, 'folder.jpg' file is not used ( not find ?) and the used path is jellyfin database path, not the artist folder path !!
![jellyfin bug name 1](https://user-images.githubusercontent.com/29975718/120768419-6ccc0c00-c51c-11eb-9689-6714162ac301.jpg)
![jellyfin bug name 2](https://user-images.githubusercontent.com/29975718/120768437-6fc6fc80-c51c-11eb-91a2-d8b30caac67b.jpg)
![jellyfin bug name 3](https://user-images.githubusercontent.com/29975718/120768452-72295680-c51c-11eb-9d7e-6770e34f318c.jpg)

**Comment by lstrojny** [comment]
Observing the same issue for the band "Phantom/Ghost" which is stored in a folder "Phantom_Ghost", shows up as "Phantom" and doesn't show an image

**Comment by galettof** [comment]
Witnessing the same issue with artist named B*Witched

**Comment by one-new-message** [comment]
Cannot reproduce, even with B*Witched. However, I'm on `master` and noticing that even though all the images seem to be fetched correctly, the artists view displays nothing and says there are zero artists. Albums work fine. Since I haven't paid attention to changes in `master` since the last release, I'm not sure what is responsible.

**Comment by felix920506** [comment]
Can anyone confirm if this issue is still present on Master?

**Comment by solidsnake1298** [comment]
I cannot reproduce on 10.8.13 nor 10.9.  I even have some of the same artists that the OP mentioned.  I think this is a long since fixed issue.

**Comment by one-new-message** [comment]
agreed--have not encountered this issue in recent memory. plus I scoured the codebase and ran some tests and found nothing. most likely this issue can be closed.

**Comment by one-new-message** [comment]
update on this: i was able to reproduce quite easily on `master` in a new docker container on linux. will need to work on building for windows if i am to test in a working environment

**Comment by emaen** [comment]
Hello all !
I not so sure it's close.
I've just tried to reproduce with : 
"Elli & Jacno"
"R.E.M."
"T.Rex"

Each time I've made an artist folder with album Folder in it and all the folder.jpg, fanart.jpg, logo. jpg

It perfectly works for "Elli & Jacno". No problem.

But It works strange for the two others : R.E.M. and T.rex are set by jellyfin with a artist image wich is NOT the folder.jpg provided !! Certainly come from the internet BUT I've set "data search from internet" to NEVER !!

So may be still a problem with name with "." in it...



![jellyfin-1](https://github.com/jellyfin/jellyfin/assets/29975718/d434b6be-53af-4a3c-8c3c-69d5f3013994)
![jellyfin-2](https://github.com/jellyfin/jellyfin/assets/29975718/56499222-8b0a-425e-8ca4-80872f67093a)
![jellyfin-3](https://github.com/jellyfin/jellyfin/assets/29975718/4ea272c4-df51-46a0-a52d-055b3d6f635b)
![jellyfin-4](https://github.com/jellyfin/jellyfin/assets/29975718/2b5038b1-652d-46a1-b317-7157b187bee0)
![jellyfin-5](https://github.com/jellyfin/jellyfin/assets/29975718/735ce154-a658-423d-ba97-f7a565a599b2)
![jellyfin-6](https://github.com/jellyfin/jellyfin/assets/29975718/cc64c1b1-b98d-4bbf-bc39-710a1a834aa1)
