### ISSUE TITLE
Movies that user doesn't have access to make up the library thumbnail

### ISSUE THREAD

**Issue by SteveDinn** [jellyfin/jellyfin#3995]
**Describe the bug**

I have my kids accounts set up to only allow PG and below, yet several of their libraries thumbnails are comprised of movies that are above that rating.

![Screenshot_20200826-202805](https://user-images.githubusercontent.com/3911507/91366795-17b7d880-e7db-11ea-98c2-0c14ee4bd447.jpg)
*Terminator 3 is not rated G*

**System (please complete the following information):**
 - OS: Ubuntu 18.04
 - Virtualization: docker
 - Clients: browser
 - Browser: Chrome stable x64
 - Jellyfin Version: 10.6.3

**To Reproduce**

I don't have a way to reliably reproduce this, but just have a user profile that had access restricted by rating and look at the library thumbnails.

**Expected behavior**

Library thumbnails should be comprised of movies the user is allowed to watch.

**Comment by cvium** [comment]
The thumbnails are server-wide and not per-user. This is not a bug, but a feature request.
