### ISSUE TITLE
Get rid of binary blobs

### ISSUE THREAD

**Issue by JustAMan** [jellyfin/jellyfin#4]
I have already replaced some binary blobs with compiled from source files, but there are some more to go. We need them to be built from source with good enough license, as now they're taken from a repo with missing license, thus their legal state is unclear.

Also we'd have to fork here the repos I used via git submodules (I guess submodules still point to my personal repos). 

Remove:

- [X] `ThirdParty/emby/Emby.Server.Connect.dll` https://github.com/jellyfin/jellyfin/pull/22
- [X] `ThirdParty/emby/Emby.Server.Sync.dll` https://github.com/jellyfin/jellyfin/pull/22
- [x] `ThirdParty/emby/Emby.Server.MediaEncoding.dll` https://github.com/jellyfin/jellyfin/pull/154
- [x] `ThirdParty/taglib/TagLib.Portable.dll` https://github.com/jellyfin/jellyfin/pull/41

**Comment by lxp** [comment]
It looks like with commit https://github.com/jellyfin/jellyfin/commit/dec3644c31c343179fd8cf8ed771a357e9b8aa20 MediaBrowser.MediaEncoding was removed and replaced with the closed-source Emby.Server.MediaEncoding.

**Comment by lxp** [comment]
In commit https://github.com/jellyfin/jellyfin/commit/758445db59a0346e3e91d639fc69fa07517c0d63 `Emby.Server.Implementations.Sync` was removed and replaced with a binary blob.

Same applies to `Emby.Server.Implementations.Connect` which was removed and replaced with a binary blob in commit https://github.com/jellyfin/jellyfin/commit/8c0bf131342a8d24d96e597596e68f8934e275fe.

**Comment by joshuaboniface** [comment]
I've moved over the submodules in #13, let me know what others we might need to create and I can add them to the org, or if we want to just leave them in the main repo that's also an option.

**Comment by JustAMan** [comment]
Submodules seem to be correct. Now we probably need to replace remaining blobs with earlier commits as found by @lxp. I was not able to find a repo with defined license. Source for remaining blobs was, if I'm not mistaken, in Emby.Common, but that repo did not have any license at all, so I decided not to fork it.

**Comment by joshuaboniface** [comment]
Hopefully it isn't too hard to revery tgose files back to their non-blob versions from whats in this repo, but I haven't dug into it yet.

**Comment by nvllsvm** [comment]
Only `Emby.Server.MediaEncoding.dll` remains from the Emby-specific blobs.

**Comment by ethanhs** [comment]
It appears that `Taglib.Portable` is just https://github.com/timheuer/taglib-sharp-portable which is LGPL 2.1, so it should be very easy to remove that "blob".

**Comment by nvllsvm** [comment]
Working on the last one here https://github.com/nvllsvm/jellyfin/tree/encoding

**Comment by nvllsvm** [comment]
@MatMaul has removed the final Emby blob!
