### ISSUE TITLE
Almost 1GB of memory usage

### ISSUE THREAD

**Issue by oscargb1** [jellyfin/jellyfin#4003]
**Describe the bug**
Jellyfin isn't working on anything at the moment, but uses almost 1GB of memory. Is this normal?

**System (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Edge 86.0.615.3
 - Jellyfin Version: 10.6.3 (linuxserver image)
 - Installed Plugins: Playback Reporting, TMDb Box Sets, Theme Songs, Trakt
 - Reverse Proxy: none
 - Base URL: none
 - Networking: Host
 - Storage: local

**To Reproduce**
Start the docker container and leave it running a few minutes. Memory usage will start to go up until ~1GB

**Expected behavior**
Less memory usage, ~500MB.

**Screenshots**
![image_2020-08-28_14-51-24](https://user-images.githubusercontent.com/26852261/91563274-e0623c80-e93e-11ea-822f-ed5a642ee933.jpg)

**Comment by oscargb1** [comment]
I'm new to programming but could this be because it never frees up memory? Or is this because it uses the .NET framework?

**Comment by Vakrehus** [comment]
This is not a bug for me. Jellyfin runs with 1.1GB in Docker. I have 16GB in total.

**Comment by barronpm** [comment]
This is known, The way "caching" was done previously was just storing things in dictionary's, so inevitably given enough time the entire database would be stored in memory. I fixed this for 10.7.

**Comment by da-anda** [comment]
@barronpm I am running 10.7. nightly (linuxserver image) and my container currently uses 1.5 GB of RAM. Since I'm fairly new using jellyfin, my library is quite small still (~50 movies, 12 episodes, ~300 albums), but I do use the tvheadend PVR add-on, so have EPG data as well. The uptime is something like 5 days and I haven't really used it much, so it was mostly idle.

**Comment by Darcidride** [comment]
> This is known, The way "caching" was done previously was just storing things in dictionary's, so inevitably given enough time the entire database would be stored in memory. I fixed this for 10.7.

My 10.6.4 jellyfin is eating ~20GB of 36GB of memory, in fact it's mainly cached memory, but honestly, it's not a behavior I was expecting :)
![image](https://user-images.githubusercontent.com/8619233/106914498-fac5f080-66fc-11eb-84cc-8028a504e1ab.png)
