### ISSUE TITLE
Auto discovery does not work in docker. 

### ISSUE THREAD

**Issue by Darkwolf1515** [jellyfin/jellyfin#4011]
**Describe the bug**
Running in synology docker, auto discovery does not work.

**To Reproduce**
Run a docker container jellyfin, try to use mpv shim or infuse or any app with auto discovery support, watch as it cant find the server.

**Expected behavior**
Apps like mpv shim, or infuse to be able to see my server through auto discovery .

=
**System (please complete the following information):**
 - OS: Synology docker
 - Jellyfin Version: 10.6.3

https://github.com/jellyfin/jellyfin-kodi/issues/229 Someone else unable to use it with docker.

**Comment by PrplHaz4** [comment]
Is your docker network in host or macvlan?  If it's in a bridge network I believe it will only broadcast to the internal docker network.

**Comment by Darkwolf1515** [comment]
> 
> 
> Is your docker network in host or macvlan? If it's in a bridge network I believe it will only broadcast to the internal docker network.

Uses bridge.

**Comment by Musi13** [comment]
Auto discovery (DLNA) requires host networking as is noted in [the docs](https://jellyfin.org/docs/general/administration/installing.html#docker)

**Comment by PrplHaz4** [comment]
> 
> 
> Auto discovery (DLNA) requires host networking as is noted in [the docs](https://jellyfin.org/docs/general/administration/installing.html#docker) (and this is the case for any media server because of how DLNA is implemented)

A slight correction to this - DLNA has a discovery component but "AutoDiscovery" has been used as a term for non-DLNA/SSDP/UPnP discovery.

@Darkwolf1515 I think you can use `--published-server-url=https://jf.mydomain.com` to publish a non-docker-internal domain or ip (it's a recently added feature) for AutoDiscovery.

https://jellyfin.org/docs/general/administration/configuration.html#main-configuration-options

**Comment by prayag17** [comment]
How do I set `PublishedServerUrl` in a docker container?

**Comment by prayag17** [comment]
Setting it gives the below error

`
[ERR] [25] Jellyfin.Networking.Manager.NetworkManager: Unable to parse bind override: http://prns.org:8096
`

I have edited the domain in this log

**Comment by PrplHaz4** [comment]
> Setting it gives the below error
> 
> `[ERR] [25] Jellyfin.Networking.Manager.NetworkManager: Unable to parse bind override: http://prns.org:8096`
> 
> I have edited the domain in this log

That sounds like an error on a different field.

If not that's probably a new bug - you should open a new issue and fill out the template.
