### ISSUE TITLE
Restart doesn't work on RPM installations

### ISSUE THREAD

**Issue by brianjmurrell** [jellyfin/jellyfin#4016]
**Describe the bug**
```
Aug 30 14:34:01 pvr.example.com jellyfin[11131]: [14:34:01] [INF] [78] Main: Starting new instance
Aug 30 14:34:01 pvr.example.com jellyfin[11131]: [14:34:01] [INF] [78] Main: Executable: /usr/libexec/jellyfin/restart.sh
Aug 30 14:34:01 pvr.example.com jellyfin[11131]: [14:34:01] [INF] [78] Main: Arguments: --webdir=/usr/share/jellyfin-web --restartpath=/usr/libexec/jellyfin
Aug 30 14:34:01 pvr.example.com jellyfin[11131]: Detected service control platform 'systemctl'; using it to restart Jellyfin...
Aug 30 14:34:01 pvr.example.com jellyfin[11131]: /usr/libexec/jellyfin/restart.sh: line 27: at: command not found
```

Looks like `at` needs to be an RPM dependency.  That said, it seem odd that `at` is used to restart the service.  Why not just issue a `systemctl restart jellyfin.service`?

**Comment by sysadmin75** [comment]
I took a quick look at this.  You are correct the `at` package is a dependency.   The restart script pipes the restart command into ``at`. 
```
case $cmd in
    'systemctl')
        echo "sleep 2; /usr/bin/sudo $( which systemctl ) restart jellyfin" | at now
        ;;
```
I agree with @brianjmurrell, why not just execute the `systemctl` command directly, instead of passing it to `at`?

**Comment by anthonylavado** [comment]
It is an old, old, holdover from Emby: https://github.com/MediaBrowser/Emby.Build/blob/5dc8da5eeb69bf4b96523549ceb7efbd435953e4/builders/emby-server/debfiles/restart.sh

**Comment by joshuaboniface** [comment]
I think the reason for `at` had to do with the script terminating itself if it wasn't put into `at`. But I think it's worth a shot. Check the PR I'm about to tag to this issue.
