### ISSUE TITLE
[Information] No hardware acceleration on Raspberry Pi OS 64-bit

### ISSUE THREAD

**Issue by MichaIng** [jellyfin/jellyfin#4023]
We received some report from our RPi OS 64-bit testers, that enabling hardware accelerated transcoding in Jellyfin (via OpenMAX) fails: https://github.com/MichaIng/DietPi/issues/3743#issuecomment-682189310
```
Stream mapping:
Stream #0:0 -> #0:0 (h264 (native) -> h264 (h264_omx))
Stream #0:1 -> #0:1 (dts (dca) -> mp3 (libmp3lame))
Press [q] to stop, [?] for help
[h264_omx @ 0x55aa8e8fe0] /opt/vc/lib/libbcm_host.so not found
```

We build our images onto the official Raspbian (now Raspberry Pi OS 32-bit) and for testing as well offer an image based on Raspberry Pi OS 64-bit, which is still in beta phase:
- Issue tracker repo: https://github.com/raspberrypi/Raspberry-Pi-OS-64bit
- Download: https://downloads.raspberrypi.org/raspios_arm64/images/
- Lite download: https://downloads.raspberrypi.org/raspios_lite_arm64/images/

There is two reason, from what we found:
- The userland part for the RPi/VC firmware has been moved from `/opt/vc` to the regular `/usr/lib` and `/usr/bin` locations. Since the error message misses `/opt/vc/lib/libbcm_host.so`, it seems like this path is somewhere hardcoded and needs to be changed for the 64-bit builds, likely for 32-bit builds as well in near future. The file list of the `libraspberrypi0` and `libraspberrypi-bin` builds on the RPi OS 64-bit image looks like this:
    ```
    /usr/lib/aarch64-linux-gnu/libbcm_host.so.0
    /usr/lib/aarch64-linux-gnu/libdebug_sym.so.0
    /usr/lib/aarch64-linux-gnu/libdtovl.so.0
    /usr/lib/aarch64-linux-gnu/libvchiq_arm.so.0
    /usr/lib/aarch64-linux-gnu/libvcos.so.0
    /usr/bin/dtmerge
    /usr/bin/dtoverlay
    /usr/bin/dtoverlay-post
    /usr/bin/dtoverlay-pre
    /usr/bin/tvservice
    /usr/bin/vcgencmd
    /usr/bin/vchiq_test
    /usr/bin/vcmailbox
    /usr/bin/dtparam
    ```
- The `libopenmaxil.so` is missing completely. Reason seems to be [this](https://github.com/raspberrypi/userland/commit/f97b1af1b3e653f9da2c1a3643479bfd469e3b74) commit which leads to the very reduced shared libraries and binaries shipped with the RPi VC firmware for 64-bit. Probably there is not much that Jellyfin can do about that, but I wanted to make you aware of this in case similar bug reports reach you.

**Comment by FredMcAwesome** [comment]
Any update on this now that Raspberry Pi 64-bit is out of beta? [Meant to include hardware acceleration now.](https://www.raspberrypi.com/news/raspberry-pi-os-64-bit/#comment-1580064)

**Comment by nyanmisaka** [comment]
The 32bit only OMX and MMAL has been deprecated in 10.8.0. V4L2 can be used to access RPI’s video encoder.

**Comment by MichaIng** [comment]
Right, OMX and MMAL are for the legacy RPi framebuffer driver, while nowadays KMS is used by default and V4L2 should be used.
