### ISSUE TITLE
Add support for  HTTP/2 on the backend

### ISSUE THREAD

**Issue by sparky8251** [jellyfin/jellyfin#403]
If you take a look at the page load process and time for the web UI you can see its a huuuge amount of tiny files loaded one by one. For example, if I disable cache and watch the main library page it takes 146 requests and 10.5 seconds to load 1.6MB of data.

Looking into it, its all HTTP/1.1 requests which means its all done in sequence rather than allowing for parallel requests.

We should look into adding HTTP/2 support and preferring it over HTTP/1.1. Bet it would dramatically improve web UI performance.

**Comment by EraYaN** [comment]
Since we switched to Kestrel the backend supports HTTP/2. Not sure if it is enabled though, it should be on by default. Though it will only work for HTTPS connections.
