### ISSUE TITLE
Emby->Jellyfin installation migration issues

### ISSUE THREAD

**Issue by brianjmurrell** [jellyfin/jellyfin#404]
It seems that the database(s) have fully-qualified paths in them, so when migrating databases from Emby to Jellyfin, once they have been copied to /var/lib/jellyfin/ they will still refer to data/files in /var/lib/emby-server/.

There are two solutions.  One more elegant longer term solution of doing a database dump to text, fixing up FQPNs and then importing the result into new databases in Jellyfin.  That will take a bit of work to get done.

Another quick, short-term solution is that if /var/lib/emby-server/ doesn't already exist, indicating that this is an installation on a machine without an existing Emby installation, that a convenience symlink be created for those users that want to then copy their database and files from a different Emby machine and have them just work.  I have tested that and initial tests indicate that it seems to work.

If the /var/lib/emby-server/ directory does exist, then it's a side-by-side install and once the database(s) are copied into /var/lib/jellyfin/ the existing /var/lib/emby-server/ paths will just work.  This mode does have a slight risk that Jellyfin will corrupt a file in /var/lib/emby-server, but on second though, permissions should prevent that if the Jellyfin and Emby-servers are run as different users, which they should be.  /var/lib/emby-server/[some directories] would need world read permission for Jellyfin to be able to read them.  Not sure if that is currently the case or not.

**Comment by sparky8251** [comment]
As a corollary to this issue, it's very likely this is the cause of issues migrating an existing DB between OSes. I know Windows -> Linux migrations don't work.

**Comment by bjoernfan** [comment]
Hello,

I've had issues updating the database. It doesn't always fail 100% (as I'm seeing new content, not sure if I'm seeing all content though), but the Admin dashboard alerts lists a lot of "Scan media library failed" for the scheduled library content updates. First, I got this message (sorry about formatting, this is what it looks like to me):

```
Could not find a part of the path '/var/lib/emby/root/default/Collections'. at System.IO.Enumeration.FileSystemEnumerator`1.Cre
ateDirectoryHandle(String path, Boolean ignoreNotFound) at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory,
 EnumerationOptions options) at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, E
numerationOptions options) at System.IO.Enumeration.FileSystemEnumerableFactory.DirectoryInfos(String directory, String express
ion, EnumerationOptions options) at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTar
get searchTarget, EnumerationOptions options) at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemEntries(String p
ath, Boolean recursive) in /repo/Emby.Server.Implementations/IO/ManagedFileSystem.cs:line 927 at MediaBrowser.Controller.Provid
ers.DirectoryService.GetFileSystemEntries(String path) in /repo/MediaBrowser.Controller/Providers/DirectoryService.cs:line 38 a
t MediaBrowser.Controller.IO.FileData.GetFilteredFileSystemEntries(IDirectoryService directoryService, String path, IFileSystem
 fileSystem, IServerApplicationHost appHost, ILogger logger, ItemResolveArgs args, Int32 flattenFolderDepth, Boolean resolveSho
rtcuts) in /repo/MediaBrowser.Controller/IO/FileData.cs:line 56 at MediaBrowser.Controller.Entities.CollectionFolder.CreateReso
lveArgs(IDirectoryService directoryService, Boolean setPhysicalLocations) in /repo/MediaBrowser.Controller/Entities/CollectionF
older.cs:line 314 at MediaBrowser.Controller.Entities.CollectionFolder.RequiresRefresh() in /repo/MediaBrowser.Controller/Entit
ies/CollectionFolder.cs:line 206 at MediaBrowser.Providers.Manager.MetadataService`2.RefreshMetadata(BaseItem item, MetadataRef
reshOptions refreshOptions, CancellationToken cancellationToken) in /repo/MediaBrowser.Providers/Manager/MetadataService.cs:lin
e 72 at MediaBrowser.Controller.Entities.BaseItem.RefreshMetadata(MetadataRefreshOptions options, CancellationToken cancellatio
nToken) in /repo/MediaBrowser.Controller/Entities/BaseItem.cs:line 1430 at MediaBrowser.Controller.Entities.Folder.RefreshChild
Metadata(BaseItem child, MetadataRefreshOptions refreshOptions, Boolean recursive, IProgress`1 progress, CancellationToken canc
ellationToken) in /repo/MediaBrowser.Controller/Entities/Folder.cs:line 571 at MediaBrowser.Controller.Entities.Folder.RefreshM
etadataRecursive(List`1 children, MetadataRefreshOptions refreshOptions, Boolean recursive, IProgress`1 progress, CancellationT
oken cancellationToken) in /repo/MediaBrowser.Controller/Entities/Folder.cs:line 538 at MediaBrowser.Controller.Entities.Folder
.ValidateChildrenInternal2(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMe
tadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService) in /repo/MediaBrowser.Controller/Entities/Fo
lder.cs:line 508 at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, CancellationToken ca
ncellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService dire
ctoryService) in /repo/MediaBrowser.Controller/Entities/Folder.cs:line 346 at MediaBrowser.Controller.Entities.UserRootFolder.V
alidateChildrenInternal(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetad
ata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService) in /repo/MediaBrowser.Controller/Entities/UserR
ootFolder.cs:line 144 at Emby.Server.Implementations.Library.LibraryManager.ValidateTopLibraryFolders(CancellationToken cancell
ationToken) in /repo/Emby.Server.Implementations/Library/LibraryManager.cs:line 1072 at Emby.Server.Implementations.Library.Lib
raryManager.PerformLibraryValidation(IProgress`1 progress, CancellationToken cancellationToken) in /repo/Emby.Server.Implementa
tions/Library/LibraryManager.cs:line 1087 at Emby.Server.Implementations.Library.LibraryManager.ValidateMediaLibraryInternal(IP
rogress`1 progress, CancellationToken cancellationToken) in /repo/Emby.Server.Implementations/Library/LibraryManager.cs:line 10
51 at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options) in /repo/Emby.Server.
Implementations/ScheduledTasks/ScheduledTaskWorker.cs:line 431
```

Running the UPDATES in the previous comment (with a minor tweak), I'm getting this:

```
Exception of type 'SQLitePCL.pretty.SQLiteException' was thrown. at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 
rc) at SQLitePCL.pretty.StatementImpl.MoveNext() at Emby.Server.Implementations.Data.SqliteItemRepository.SaveItem(BaseItem ite
m, BaseItem topParent, String userDataKey, IStatement saveItemStatement) in /repo/Emby.Server.Implementations/Data/SqliteItemRe
pository.cs:line 1071 at Emby.Server.Implementations.Data.SqliteItemRepository.SaveItemsInTranscation(IDatabaseConnection db, L
ist`1 tuples) in /repo/Emby.Server.Implementations/Data/SqliteItemRepository.cs:line 669 at SQLitePCL.pretty.DatabaseConnection
.<>c__DisplayClass20_0.b__0(IDatabaseConnection db) at SQLitePCL.pretty.DatabaseConnection.RunInTransaction[T](IDatabaseConnect
ion This, Func`2 f, TransactionMode mode) at SQLitePCL.pretty.DatabaseConnection.RunInTransaction(IDatabaseConnection This, Act
ion`1 action, TransactionMode mode) at Emby.Server.Implementations.Data.SqliteItemRepository.SaveItems(List`1 items, Cancellati
onToken cancellationToken) at Emby.Server.Implementations.Library.LibraryManager.UpdateItems(List`1 items, BaseItem parent, Ite
mUpdateType updateReason, CancellationToken cancellationToken) in /repo/Emby.Server.Implementations/Library/LibraryManager.cs:l
ine 1911 at Emby.Server.Implementations.Library.LibraryManager.UpdateItem(BaseItem item, BaseItem parent, ItemUpdateType update
Reason, CancellationToken cancellationToken) in /repo/Emby.Server.Implementations/Library/LibraryManager.cs:line 1948 at MediaB
rowser.Controller.Entities.BaseItem.UpdateToRepository(ItemUpdateType updateReason, CancellationToken cancellationToken) in /re
po/MediaBrowser.Controller/Entities/BaseItem.cs:line 2324 at MediaBrowser.Providers.Manager.MetadataService`2.SaveItem(Metadata
Result`1 result, LibraryOptions libraryOptions, ItemUpdateType reason, CancellationToken cancellationToken) in /repo/MediaBrows
er.Providers/Manager/MetadataService.cs:line 221 at MediaBrowser.Providers.Manager.MetadataService`2.RefreshMetadata(BaseItem i
tem, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken) in /repo/MediaBrowser.Providers/Manager/Metada
taService.cs:line 199 at MediaBrowser.Controller.Entities.BaseItem.RefreshMetadata(MetadataRefreshOptions options, Cancellation
Token cancellationToken) in /repo/MediaBrowser.Controller/Entities/BaseItem.cs:line 1430 at Emby.Server.Implementations.Library
.LibraryManager.ValidateTopLibraryFolders(CancellationToken cancellationToken) in /repo/Emby.Server.Implementations/Library/Lib
raryManager.cs:line 1068 at Emby.Server.Implementations.Library.LibraryManager.PerformLibraryValidation(IProgress`1 progress, C
ancellationToken cancellationToken) in /repo/Emby.Server.Implementations/Library/LibraryManager.cs:line 1087 at Emby.Server.Imp
lementations.Library.LibraryManager.ValidateMediaLibraryInternal(IProgress`1 progress, CancellationToken cancellationToken) in 
/repo/Emby.Server.Implementations/Library/LibraryManager.cs:line 1051 at Emby.Server.Implementations.ScheduledTasks.ScheduledTa
skWorker.ExecuteInternal(TaskOptions options) in /repo/Emby.Server.Implementations/ScheduledTasks/ScheduledTaskWorker.cs:line 4
31 
```

My change to the UPDATE was to replace /var/lib/emby after replacing /var/lib/emby-server. Not sure I had any of the latter but I did have a lot of the former.

This is using Debian, recently migrated from Emby. Using the Debian repos in both cases.

I'm also having issues with the loading circle animations never going away and having to restart the server. Not sure what the issue is here, I'm having problems understanding the logging. But I'm also having other issues recently, QEMU/libvirt related leading to my qemu processes for my virtual machines turning into zombie processes and stuff, so I can't right now say what's Jellyfin and what's server environment things, but sometimes, from what I'm seeing from Jellyfin, I'm thinking it might be database locking issues, or file system checks timing out (but I'm not seeing that otherwise so not sure), but I have yet to see that (or anything else) reflected in the Jellyfin logs.

Also, as a quick fix a few days ago, I symlinked /var/lib/emby to /var/lib/jellyfin but my first error message appeared when I had that as well, which I find odd. (The full path in the beginning of the error message actually existed at the time, and was owned by jellyfin).

So ending my ramble, I just wanted to say: Also consider Emby installations apparently might use  /var/lib/emby instead of /var/lib/emby-server.

**Comment by sparky8251** [comment]
Most of the symptoms you describe could be related to the FQPNs stored in the database. Even the locking up of the UI with the loading circle is another common symptom migrators have.

It's definitely odd how picky the DB is about its location on the filesystem.

**Comment by brianjmurrell** [comment]
I don't know that the location of the DB (i.e. `.db` files) is particularly important.  It's the shameless (by the emby team) placing of FPQNs of all of the other collateral in the database.  They should be relative to the _configured_ collateral directories and FQPNs constructed with the concatenation of those.

**Comment by sparky8251** [comment]
Well, the fact that there are FQPNs causes Emby users issues too. I'd say its legacy code rather than intentional.

Migrations such as the following do not work for Emby (and thus Jellyfin):

Windows <--> Linux
Windows <--> Docker
Linux <--> Docker
and potentially different variants of Linux <--> Linux depending how how its packaged and installed.

**Comment by brianjmurrell** [comment]
I could believe Windows <--> {Linux,Docker} might be challenging but I don't see why Linux <--> {Linux,Docker} should be challenging.

**Comment by sparky8251** [comment]
None of these should be challenging. But thanks to the FQPNs, they seem to be. Part of the larger DB cleanup. If you've looked around, I wrote up docs showing what was in most of them, It's pretty bad

**Comment by LogicalPhallacy** [comment]
Yeah if FQPNs can be limited or even excised (with the use of variables/library base dirs) it would greatly enhance portability. There's not even a / vs \ barrier anymore. The only major hazard to interop I would forsee is that *nix and BSD are case sensitive and Windows is not, so if you have files/folders with only case differences that'll bite you, but that will bite you at a File system level before you even got to DB migration.

**Comment by EraYaN** [comment]
These queries are the ones I used to successfully move a library folder (so not the cache data folder). Note that some use `\\` because they are JSON based columns.
```sql
UPDATE MediaItems SET Path = REPLACE(Path,"D:\media\","M:\"), Images = REPLACE(Images,"D:\media\","M:\"), data = REPLACE(data,"D:\\media\\","M:\\");

UPDATE mediastreams SET Path = REPLACE(Path,"D:\media\","M:\");

UPDATE MediaStreams2 SET Path = REPLACE(Path,"D:\media\","M:\");

UPDATE TypedBaseItems SET Path = REPLACE(Path,"D:\media\","M:\"), Images = REPLACE(Images,"D:\media\","M:\"), data = REPLACE(data,"D:\\media\\","M:\\");
```

Do not forget to edit all paths found in `\programdata\root\default\*\*.mblink` files, `\programdata\root\default\*\options.xml` files, all found paths in `\programdata\config\**\*.xml` files. And all other files that a grep will show you.
