### ISSUE TITLE
No support for 24-192 music

### ISSUE THREAD

**Issue by neopc10** [jellyfin/jellyfin#4040]
Jellyfin-server does not have any interest in transcoding/resampling high resolution audio. 

On the latest Chrome, jf-web outright refuses to play with quality set to 'auto,' while the Google Cast CAF receiver starts tossing around this same "max bitrate is 100000" junk that blocks direct playback of files the hardware supports. [MediaBrowser.Api.Playback.MediaInfoService: Bitrate exceeds DirectPlay limit: media bitrate: 6660849, max bitrate: 1000000]. The AppID I'm running has "Limit flac to 96kHz 24bit #52" code merged. 

Somewhere in the server code is an arbitrary "don't play anything that has a bitrate above 1000000 on Google Cast" which may have served the 7 year old model of the Chromecast well but severely limits or forbids playback on anything relatively modern.

![image](https://user-images.githubusercontent.com/1365322/91983406-9dff7d80-ecf9-11ea-9949-f6db8b9256b2.png)

**Logs**
For the CAF receiver client
https://pastebin.com/VBZmgbRX
For 10.6.4 web on latest Chrome
https://pastebin.com/AmbbWXtt

**Comment by dkanada** [comment]
Just out of curiosity, can you try direct play and then transcode on [Gelli](https://github.com/dkanada/gelli) and then let me know if it works? That would narrow down the issue to either server or the web client.

**Comment by neopc10** [comment]
Radio silence from Gelli.

**Comment by neopc10** [comment]
By the way, generally speaking, Gelli does transcode, but never to the bitrate specified.

**Comment by YouKnowBlom** [comment]
Strange, from the logs I can't see anything related to the changes in jellyfin/jellyfin-chromecast#52

**Comment by grravity** [comment]
Can confirm this issue still exists, it doesn't even seem to transcode it. Makes a lot of music simply unplayable.

**Comment by seniorm0ment** [comment]
keep open

**Comment by lmateovf** [comment]
I think this is still happening
I have Windows 10 and last stable version of Jellyfin at the moment
Help would be appreciated

**Comment by Shadowghost** [comment]
Might be fixed by #8850

**Comment by felix920506** [comment]
I just tested playing back 24bit 192khz flac in the web client via Chrome and it is working normally without issues on master for both web and server.

**Comment by solidsnake1298** [comment]
Could not reproduce on 10.8.11 in Chrome on Chrome OS.  24-bit ,192Khz music played normally.

**Comment by felix920506** [comment]
Closing this as it should already be fixed and it couldn't be reproduced on latest versions of Jellyfin.
