### ISSUE TITLE
Jellyfin floods the log when running alongside Wireguard

### ISSUE THREAD

**Issue by lldsolitude** [jellyfin/jellyfin#4044]
**Describe the bug**

Jellyfin floods the log when running alongside Wireguard with the following error:
```
Sep  3 20:44:21 omv jellyfin[21356]: [20:44:21] [ERR] [162] Emby.Dlna.Main.DlnaEntryPoint: Error sending socket message from 172.31.100.3 to 239.255.255.250:1900
Sep  3 20:44:21 omv jellyfin[21356]: System.Net.Sockets.SocketException (0xFFFFFFFF): Bad value for ai_flags
Sep  3 20:44:21 omv jellyfin[21356]:    at System.Net.Sockets.Socket.DoBeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint endPointSnapshot, SocketAddress socketAddress, OverlappedAsyncResult asyncResult)
Sep  3 20:44:21 omv jellyfin[21356]:    at System.Net.Sockets.Socket.BeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP, AsyncCallback callback, Object state)
Sep  3 20:44:21 omv jellyfin[21356]:    at Emby.Server.Implementations.Net.UdpSocket.SendToAsync(Byte[] buffer, Int32 offset, Int32 size, IPEndPoint endPoint, CancellationToken cancellationToken)
Sep  3 20:44:21 omv jellyfin[21356]:    at Rssdp.Infrastructure.SsdpCommunicationsServer.SendFromSocket(ISocket socket, Byte[] messageData, IPEndPoint destination, CancellationToken cancellationToken)
```
`172.31.100.3` is the IP of the Wireguard interface. The error does not occur if Wireguard is started after Jellyfin. I use DLNA regularly so I would like to keep it enabled.

**System (please complete the following information):**
 - OS: Debian 10.5
 - Virtualization: none
 - Jellyfin Version: 10.6.4
 - Reverse Proxy: none
 - Base URL: none
 - Networking: Host

**Comment by Stampede10343** [comment]
I am seeing this as well, although I attempted to turn DLNA off and I'm still seeing the logs.

**Comment by BaronGreenback** [comment]
System.Net.Sockets.SocketException (0xFFFFFFFF): Bad value for ai_flags is access denied. Suspect it's because the sockets are being blocked due to the Wireguard.

SsdpCommunicationsServer is the DLNA server publisher - so i'd check that PlayTo and DLNA server are disabled.

FYI: The DLNA objects is still created even though it's not enabled. (PR submitted).

https://github.com/jellyfin/jellyfin/pull/3994 should help. DLNA can be completely disabled, along with the autodiscovery which also uses sockets. You can also restrict sockets to certain address ranges.

**Comment by lldsolitude** [comment]
@BaronGreenback Could you please point out which specific setting in #3994 I should use to restrict sockets to certain address ranges? I would still like to keep DLNA enabled.

**Comment by schoentoon** [comment]
Having the same issue, tried explicitly setting LocalNetworkSubnets to the non-wireguard interface. But even after restarting jellyfin the same messages keep popping up in the logs.

**Comment by BaronGreenback** [comment]
If your running #3994 - can you enable network logging and see what is recorded. I might have an incling of what it could be. 

"Serilog": {
        "MinimumLevel": {
            "Override": {
	       "Jellyfin.Networking.Manager" : "Debug",
               "Jellyfin.Networking.Udp" : "Debug",

**Comment by schoentoon** [comment]
I did not quite realize this was a pull request despite reading through it to find the LocalNetworkSubnets option (only to realize I could just set it through the web interface). I'll try to run from that branch tomorrow and enable network logging for you.

**Comment by BaronGreenback** [comment]
Came across an article where it says you need to bind to the wireguard interface.

Try putting your external ip address into the "Bind to local network address:" field in your network settings.

If the field is empty, JF binds to the "any" address.

**Comment by schoentoon** [comment]
I could not reproduce the log flooding with #3994 and the logging overrides it seems like. Unless I'm missing something, logging output regardless https://gist.github.com/schoentoon/0a2babe54b13dac62c12e1ab26bbb8f4

**Comment by schoentoon** [comment]
Also I just tried binding directly to the wireguard interface and the same log flood was happening. Same with binding to another (non wireguard) interface.

**Comment by eh8** [comment]
Same result as @schoentoon , still happening in 10.6.4

**Comment by eh8** [comment]
I went into the DLNA settings within the admin dashboard and disabled the first option `Enable DLNA play to`, now my logs are normal again.

**Comment by mika91** [comment]
> I went into the DLNA settings within the admin dashboard and disabled the first option `Enable DLNA play to`, now my logs are normal again.

Same result here... but I need DLNA, so keep it enabled.

JellyFin is running in docker (host mode to allow DLNA) , on an UNRAID box.

**Comment by PrplHaz4** [comment]
> 
> 
> > I went into the DLNA settings within the admin dashboard and disabled the first option `Enable DLNA play to`, now my logs are normal again.
> 
> Same result here... but I need DLNA, so keep it enabled.
> 
> System (please complete the following information):
> 
> OS: Unraid 6.8.3
> Virtualization: docker (host network)
> Jellyfin Version: 10.6.4
> Networking: Host
> Reverse Proxy: none

Sounds like DLNA is trying to multicast over your wireguard interface (which I"m guessing is not allowed?)

I'm guessing you want DLNA to work over your local network while still being able to serve jf over wireguard?

**Comment by mika91** [comment]
No need to serve JF through the wireguard interface, I use nginx reverse proxy for external access. (I use wireguard to secure NAS from/to VPS access)
But I guess some people will use wireguard anyway.

**Comment by PrplHaz4** [comment]
> 
> 
> No need to serve JF through the wireguard interface, I use nginx reverse proxy for external access. (I use wireguard to secure NAS from/to VPS access)
> But I guess some people will use wireguard anyway.

You may be able to set JF to listen on your local LAN only 
- Settings -> Network -> Bind to Local Network Address

Put in the local network IP of your JF server and then it should stop trying to send things over the wireguard interface.  More control over this stuff is coming in 10.7...

**Comment by mika91** [comment]
Ok thanks.
I'll try as soon as possible

**Comment by makuser** [comment]
Just posting to keep this ticket from being marked as stale.
