### ISSUE TITLE
Unable to change user settings immediately after first install

### ISSUE THREAD

**Issue by sparky8251** [jellyfin/jellyfin#405]
Not sure if everyone else can see this, but if I go through the first install wizard and immediately try and edit my users settings, I get that multicolored loading circle and it gets stuck.

Closing out all Jellyfin pages and going back then allows me to change user settings.

There seems to be something about the way the UI handles logins and a user reported oddities when one tab is one user and another is on a different tab that are very similar.

Without looking, I wonder if you aren't actually logged in as your user properly when you exit the setup wizard, causing bugs with the user specific parts of the UI.

Quick fix can be to dump you to the login page rather than the dashboard once you finish the wizard.

**Comment by cvium** [comment]
Did you check the console? It could just be some "dead" JS like Sync or Connect.

**Comment by sparky8251** [comment]
No. Mostly opened this so it's not forgotten about and is looked into.

**Comment by cvium** [comment]
I tested it. It's broken.

<img width="1230" alt="image" src="https://user-images.githubusercontent.com/675118/50710372-1d433680-106b-11e9-9b5f-8206df7e81b5.png">

**Comment by sparky8251** [comment]
Well, at least its not just me then. Bug confirmed!

**Comment by sparky8251** [comment]
As parting of testing for another bug, I can also confirm this is an inherited bug from Emby 3.5.2.0.

**Comment by drago-96** [comment]
I get that too.

In my case, the error I get is `Must supply a userId` from `ApiClient.prototype.getUser` at `apiclient.js:1081:24`.

I think this is due to poor redirecting at the end of the installation wizard: the url of the page "you have completed the installation" is `http://localhost:8096/web/index.html?start=wizard#!/wizardfinish.html`.
If I click on "finish", I get to the page `http://localhost:8096/web/index.html?start=wizard#!/dashboard.html`, while it should be `http://localhost:8096/web/index.html#!/dashboard.html`; and every time I click on something, I always go to `http://localhost:8096/web/index.html?start=wizard#!something`.
If I remove the `start=wizard` bit from the url, everything works fine, so I don't think (at least this specific bug) it's a session/cookie/login thing.

Maybe the presence of the `start=wizard` parameter conflicts with the userId parameter of the edit user page, which is `http://localhost:8096/web/index.html#!/useredit.html?userId=fc4e16d2dc3c4f26a3138a425cad83e5`

**Comment by ploughpuff** [comment]
I'm experiencing something similar when using the "-programdata" switch to reference an empty folder, thereby forcing a clean start.  After the install wizard has completed I'm unable to edit the user details.  The proposed workaround (close browser, repoen) is not working for me.  My workaround is to manually type the username into the empty textbox and save; in fact you can type anything into the textbox and save it still works!!  After this the username and policy details are displayed correctly.

![capture](https://user-images.githubusercontent.com/33969763/51329077-a3e51400-1a6c-11e9-8144-6a87ee42e1de.PNG)

**Comment by ploughpuff** [comment]
Can confirm this behaviour is due to the 'start=wizard' text being retained in the url after setup has finished.  Manually removing it and the user page works as expected.

**Comment by ploughpuff** [comment]
I didn't appreciate the jellyfin-web module required updating outside of jellyfin, but now my issue is resolved.

Is my approach below correct please?

```
C:\git_repos\jellyfin>git submodule status
 4678528d0028685b45c7c6daa2e24b72a363535b MediaBrowser.WebDashboard/jellyfin-web
 ee5ab21742b71fd1b87ee24895582327e9e04776 ThirdParty/taglib-sharp (taglib-sharp-2.1.0.0-244-gee5ab21)

C:\git_repos\jellyfin>git submodule deinit MediaBrowser.WebDashboard/jellyfin-web
Cleared directory 'MediaBrowser.WebDashboard/jellyfin-web'
Submodule 'MediaBrowser.WebDashboard/jellyfin-web' (https://github.com/jellyfin/jellyfin-web.git) unregistered for path 'MediaBrowser.WebDashboard/jellyfin-web'

C:\git_repos\jellyfin>cd MediaBrowser.WebDashboard

C:\git_repos\jellyfin\MediaBrowser.WebDashboard>git clone -b dev https://github.com/jellyfin/jellyfin-web
Cloning into 'jellyfin-web'...
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 125421 (delta 2), reused 6 (delta 2), pack-reused 125413 eceiving objects: 100% (125421/125421), 56.68 MiBReceiving objects: 100% (125421/125421), 57.64 MiB | 2.73 MiB/s, done.

Resolving deltas: 100% (78107/78107), done.
Checking out files: 100% (659/659), done.

C:\git_repos\jellyfin\MediaBrowser.WebDashboard>cd jellyfin-web

C:\git_repos\jellyfin\MediaBrowser.WebDashboard\jellyfin-web>git status
On branch dev
Your branch is up to date with 'origin/dev'.

nothing to commit, working tree clean

C:\git_repos\jellyfin\MediaBrowser.WebDashboard\jellyfin-web>git remote -v
origin  https://github.com/jellyfin/jellyfin-web (fetch)
origin  https://github.com/jellyfin/jellyfin-web (push)

```

**Comment by Bond-009** [comment]
@ploughpuff you don't need to deinit it, you can just go to the submodule, and checkout the dev branch.

**Comment by joshuaboniface** [comment]
Yea we definitely need a better way to handle that submodule... it's too easy to miss unless you're using one of the build scripts that takes it into account.
