### ISSUE TITLE
Docker test image

### ISSUE THREAD

**Issue by cromefire** [jellyfin/jellyfin#4056]
## Problem
E2E testing is currently nearly impossible because you have to set up a server and fill it with data somehow.
## Solution
But many CI systems allow you to run docker images side by side with your tests, so an official test image, that contains a few, small snippets that are already added to the library (with some fake metadata or so) and 2 preconfigured users (admin & user) with auth. It could be created either by directly inserting data into the db or by using the web apis

## Alternatives
- Build your own test image automatically
  - Hard to do: You have to make sure everything was added to the library correctly
  - Breakage: It may break between releases
- Build your own test image manually
  - No reproducibility: You may make error when trying to configure it

If you have more alternatives, I'll gladly consider them, but for now that seems to be it

**Comment by PrplHaz4** [comment]
Well, there's already unstable images being built - the next step could be running simple scripts inside them to get things set up - this could be incorporated into CI to build a dedicated image later if it proves reliable...

Here's some related stuff I've run across recently that made me think of jf integration testing:

This project has some bash and python scripts that set up a bare jf instance that might be an easy/hacky starting point.  I'm not sure what .Net Core has in the way of support for db fixtures, which will be obsoleted quickly at the pace the conversion to EF is moving....
- https://github.com/turnkeylinux-apps/mediaserver/pull/20/files

This project has some sample media with unit tests for mediainfo that seem pretty useful:
- https://github.com/UniversalMediaServer/UniversalMediaServer/pull/2238
