### ISSUE TITLE
Unstable: DLNA profiles only support case sensitive regexp matching.

### ISSUE THREAD

**Issue by BaronGreenback** [jellyfin/jellyfin#4060]
The web interface states under dlna profile identification:- "A case-insensitive substring or regex expression."

However, only a case sensitive reg expression test is only performed (DlnaManager.cs / IsRegexMatch)

In addition if the string contains any reg exp characters then it fails to match.

**Comment by PrplHaz4** [comment]
I've been meaning to do some testing in this area with the eventual goal of being able to use regex (or even whole profiles) from UMS: https://github.com/UniversalMediaServer/UniversalMediaServer/tree/master/src/main/external-resources/renderers

**Comment by BaronGreenback** [comment]
@PrplHaz4 Nice!

**Comment by BaronGreenback** [comment]
https://github.com/jellyfin/jellyfin/pull/4061
