### ISSUE TITLE
Add "-restartexitcode" Option for in-app service restart

### ISSUE THREAD

**Issue by Wuerfelbecher** [jellyfin/jellyfin#408]
As the title says, exit jellyfin with a configurable exit code so that systemd can restart the service per user request without a custom [sudo-policy](https://github.com/jellyfin/jellyfin/blob/master/debian/bin/jellyfin-sudoers) or [restart script](https://github.com/jellyfin/jellyfin/blob/master/debian/bin/restart.sh), at least on systems running systemd.

The additional line in the jellyfin.service file: 
```ini
[Service]
RestartForceExitStatus=3
```

**Comment by Bond-009** [comment]
What exactly is the goal?
* Auto restarting on crash?
* Auto restarting on shutdown?
* Letting Jellyfin restarts be handled by external scripts?

**Comment by Wuerfelbecher** [comment]
Currently in the Debian package when a restart is requested via the Web-UI jellyfin calls `/usr/lib/jellyfin/restart.sh` which uses sudo to restart itself.

Exiting jellyfin with a custom exit code allows systemd to [force restart the service](https://www.freedesktop.org/software/systemd/man/systemd.service.html#RestartForceExitStatus=) without calling any scripts that use sudo to do the same thing (at least on systems with systemd).

Automatic service restarts are already handled by systemd.

**Comment by joshuaboniface** [comment]
I actually agree with this 100%. Might be better to just pick one and stick with it, rather than making it configurable though: perhaps code 128?

It's worth noting that the server already does this - even if the restart script fails, the daemon tries to shut itself down with `RestartInternal` (log snippit below). The only problem is it returns a 0 exit code, so it's impossible to tell it apart from a legit shutdown.

```
Feb 04 00:33:36 jf1 jellyfin[22201]: [00:33:36] [INF] Calling RestartInternal
[...shutdown messages]
Feb 04 00:33:36 jf1 jellyfin[22201]: [00:33:36] [INF] Executable: /usr/lib/jellyfin/restart.sh
Feb 04 00:33:36 jf1 jellyfin[22201]: [00:33:36] [INF] Arguments: --datadir=/var/lib/jellyfin --configdi
r=/etc/jellyfin --logdir=/var/log/jellyfin --cachedir=/var/cache/jellyfin --restartpath=/usr/lib/jellyfin/restart.sh --ffmpeg=/srv/ffmpeg-4.0.3-64bit-static/ffmpeg --ffprobe=/srv/ffmpeg-4.0.3-64bit-static/ffprobe                          
Feb 04 00:33:36 jf1 systemd[1]: jellyfin.service: Succeeded.
```

After this, `systemctl status` reports:

```
● jellyfin.service - Jellyfin Media Server
   Loaded: loaded (/lib/systemd/system/jellyfin.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/jellyfin.service.d
           └─jellyfin.service.conf
   Active: inactive (dead) since Mon 2019-02-04 00:33:36 EST; 2s ago
  Process: 22201 ExecStart=/usr/bin/jellyfin --datadir=${JELLYFIN_DATA_DIRECTORY} --configdir=${JELLYFIN_CONFIG_DIRECTO...
 Main PID: 22201 (code=exited, status=0/SUCCESS)
```

**Comment by sevenrats** [comment]
moved to https://features.jellyfin.org/posts/2351/add-restartexitcode-option-for-in-app-service-restart
