### ISSUE TITLE
Update README and Other locations with the new documentation link and close wiki.

### ISSUE THREAD

**Issue by EraYaN** [jellyfin/jellyfin#410]
Now that the readthedocs is live, we should update the README and for example the subreddit sidebar. After that we can hide the wiki here.

**Comment by sparky8251** [comment]
While we are at it, it looks like parts of the readme are now out of sync with the wiki like the about section. Might be best to sync them up?

**Comment by anthonylavado** [comment]
This is partially done with #447, but we haven't closed the wiki yet.

**Comment by joshuaboniface** [comment]
The wiki isn't closed yet, but I plan to just delete the pages soon.

**Comment by Bond-009** [comment]
Closed the wiki
