### ISSUE TITLE
VAAPI with HD7560D not working

### ISSUE THREAD

**Issue by webermar** [jellyfin/jellyfin#4119]
I just cannot get jellyfin to encode in H.264 via vaapi despite vainfo telling me its possible:

On Ubuntu Host:
error: can't connect to X server!
libva info: VA-API version 1.1.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/r600_drv_video.so
libva info: Found init function __vaDriverInit_1_1
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.1 (libva 2.1.0)
vainfo: Driver version: Mesa Gallium driver 20.3.0-devel for AMD ARUBA (DRM 2.50.0 / 4.15.0-117-generic, LLVM 10.0.1)
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileNone                   : VAEntrypointVideoProc

its exactly the same output inside the docker container.

In my despair, I installed oibaf ppa drivers (ppa:oibaf/graphics-drivers) but nothing changed.
What does work, however, is decoding. Its just that when I try to watch something with encoding enabled, it won't work.

**Media Info of the file**
Every H.264 encoded file.

**Logs**
(Tail output of one 1080p H.264 mkv file):
[matroska,webm @ 0x55fc4172a7c0] sub2video: using 1440x1080 canvas
[h264_vaapi @ 0x55fc41769a00] Driver does not support some wanted packed headers (wanted 0xd, found 0).
[h264_vaapi @ 0x55fc41769a00] Driver does not support packed sequence headers, but a global header is requested.
[h264_vaapi @ 0x55fc41769a00] No global header will be written: this may result in a stream which is not usable for some purposes (e.g. not muxable to some containers).
Output #0, hls, to '/config/data/transcodes/536917a2c2263750f999b0221db2d181.m3u8':
  Metadata:
    encoder         : Lavf58.45.100
    Stream #0:0: Video: h264 (h264_vaapi) (High), vaapi_vld, 1440x1080 [SAR 1:1 DAR 4:3], q=-1--1, 4352 kb/s, 23.98 fps, 90k tbn, 23.98 tbc (default)
    Metadata:
      encoder         : Lavc58.91.100 h264_vaapi
    Stream #0:1: Audio: mp3 (libmp3lame), 48000 Hz, stereo, fltp, 384 kb/s (default)
    Metadata:
      encoder         : Lavc58.91.100 libmp3lame
[h264_vaapi @ 0x55fc41769a00] Failed to end picture encode issue: 5 (invalid VAContextID).
[h264_vaapi @ 0x55fc41769a00] Encode failed: -5.
Video encoding failed
[libmp3lame @ 0x55fc41779880] 3 frames left in the queue on closing
Conversion failed!

**Server System (please complete the following information):**
 - Docker on Ubuntu 18.04 LTS
 - Jellyfin Version: 10.6.4 (x64)
 - Hardware settings & device: AMD A8 5500 APU with Radeon HD7560D via VAAPI, via BIOS I gave 512MB of RAM dedicated to iGPU
 - Reverse proxy: nginx
 - Other hardware notes: config on SSD, media on local RAID
 
**Client System (please complete the following information):**
 - Device: PC
 - OS: Windows 10
 - Client: Firefox (recent one)

**Comment by nyanmisaka** [comment]
This may be a driver issue for early GCN series or you gpu is unable to handle the transcoding pipeline.
AMD only provided Mesa VAAPI support for old GCN graphics cards not long ago, but it is still unstable.
