### ISSUE TITLE
One-word TV shows often misidentified

### ISSUE THREAD

**Issue by fffrankieh** [jellyfin/jellyfin#4132]
**Describe the bug**
TV shows with one-word names (with or without a preceding "The") are often misidentified.

**System (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Virtualization: none
 - Clients: n/a
 - Browser: n/a
 - Jellyfin Version: 10.6.4
 - Playback: n/a
 - Installed Plugins: default (AudioDB, MusicBrainz, OMDb, TheTVDB)
 - Reverse Proxy: n/a
 - Base URL: none
 - Networking: n/a
 - Storage: local

**To Reproduce**
1. Have TV shows with one-word names in clearly named folders, like "Condor (2018)" or "The Defenders (2017)".
2. Add the folder(s) containing those shows to a Jellyfin library.
3. Wait for the library scan to finish.
4. View the Jellyfin library in any client.

**Expected behavior**
The shows are correctly identified.

**Observed behavior**
The shows are either misidentified in strange ways (the idenitified show names have more or different words than the actual show names) or are not identified at all (and display no metadata other than what's assumed from the folder and file names).

**Logs**
Timestamps are removed for brevity; nothing else is changed. The image search lines might not be relevant, but I left them in just in case.

<details>
<summary>"The Boys (2019)" is misidentified as "Water Boys (2019)".</summary>
<pre>
[INF] TmdbSearch: Finding id for item: "the boys" (2019)
[WRN] HTTP Response 200 to "127.0.0.1". Time (slow): 0:00:01.6237554. "http://localhost:8096/Items/RemoteSearch/Series"
[WRN] HTTP Response 200 to "127.0.0.1". Time (slow): 0:00:01.1429729. "http://localhost:8096/Items/RemoteSearch/Image?imageUrl=https%3A%2F%2Fimage.tmdb.org%2Ft%2Fp%2Foriginal%2FpiVO3qgxDlsQgjVypqICphS4rzu.jpg&ProviderName=TheMovieDb"
[WRN] HTTP Response 200 to "127.0.0.1". Time (slow): 0:00:01.4648319. "http://localhost:8096/Items/RemoteSearch/Image?imageUrl=https%3A%2F%2Fimage.tmdb.org%2Ft%2Fp%2Foriginal%2FncJAzlVu44RN9ZWWsxI5SCFuOP3.jpg&ProviderName=TheMovieDb"
[WRN] HTTP Response 200 to "127.0.0.1". Time (slow): 0:00:01.7542046. "http://localhost:8096/Items/RemoteSearch/Image?imageUrl=https%3A%2F%2Fimage.tmdb.org%2Ft%2Fp%2Foriginal%2FmY7SeH4HFFxW1hiI6cWuwCRKptN.jpg&ProviderName=TheMovieDb"
[INF] Setting provider id's to item 63bda359-c258-c7c0-1f78-2a4324490560-"Water Boys (2019)": "{\"Tmdb\":\"76479\"}"
</pre>
</details>

<details>
<summary>"Caprica (2010)" is not identified, despite log entries showing that it was.</summary>
<pre>
[INF] TmdbSearch: Finding id for item: "caprica" (null)
[WRN] HTTP Response 200 to "127.0.0.1". Time (slow): 0:00:01.5612469. "http://localhost:8096/Items/RemoteSearch/Series"
[WRN] HTTP Response 200 to "127.0.0.1". Time (slow): 0:00:01.1727594. "http://localhost:8096/Items/RemoteSearch/Image?imageUrl=https%3A%2F%2Fm.media-amazon.com%2Fimages%2FM%2FMV5BMjAxMjM4NDQyMV5BMl5BanBnXkFtZTcwMjEyNDYzMg%40%40._V1_SX300.jpg&ProviderName=The%20Open%20Movie%20Database"
[WRN] HTTP Response 200 to "127.0.0.1". Time (slow): 0:00:01.824231. "http://localhost:8096/Items/RemoteSearch/Image?imageUrl=https%3A%2F%2Fimage.tmdb.org%2Ft%2Fp%2Foriginal%2FwGCdHYsx0aY5Z5236XTC6JQMpNn.jpg&ProviderName=TheMovieDb"
[INF] Setting provider id's to item d84f3d5c-da44-9043-0e86-b0093b34a088-"Caprica (2010)": "{\"Tmdb\":\"877\"}"
</pre>
</details>

<details>
<summary>"Condor (2018)" is misidentified as "The Legend of the Condor Heroes (2017)".</summary>
<pre>
[INF] TmdbSearch: Finding id for item: "Condor" (2018)
[WRN] HTTP Response 200 to "127.0.0.1". Time (slow): 0:00:01.6109993. "http://localhost:8096/Items/RemoteSearch/Series"
[INF] Setting provider id's to item d54fed23-7184-039a-0fe9-3a72ba06f941-"The Legend of the Condor Heroes (2017)": "{\"Tmdb\":\"71146\"}"
</pre>
</details>

<details>
<summary>"The Defenders (2017)" is misidentified as "Voltron: Legendary Defender (2016)".</summary>
<pre>
[INF] TmdbSearch: Finding id for item: "The Defenders" (2017)
[WRN] HTTP Response 200 to "127.0.0.1". Time (slow): 0:00:04.1411014. "http://localhost:8096/Items/RemoteSearch/Series"
[INF] Setting provider id's to item f81779e5-23eb-f177-0e7b-63082b0195c2-"Voltron: Legendary Defender": "{\"Imdb\":\"tt4230076\"}"
</pre>
</details>

<details>
<summary>"Origin (2018)" is misidentified as "Origins (2017)".</summary>
<pre>
[INF] TmdbSearch: Finding id for item: "origin" (2018)
[WRN] HTTP Response 200 to "127.0.0.1". Time (slow): 0:00:02.5205698. "http://localhost:8096/Items/RemoteSearch/Series"
[WRN] HTTP Response 200 to "127.0.0.1". Time (slow): 0:00:01.2387599. "http://localhost:8096/Items/RemoteSearch/Image?imageUrl=https%3A%2F%2Fm.media-amazon.com%2Fimages%2FM%2FMV5BMDM1NmMyYjQtYzc4MC00ZWVkLWIzNDMtZDg5ZjlmYWEzNTZhXkEyXkFqcGdeQXVyNjE4NTc2MDg%40._V1_SX300.jpg&ProviderName=The%20Open%20Movie%20Database"
[WRN] HTTP Response 200 to "127.0.0.1". Time (slow): 0:00:01.6661684. "http://localhost:8096/Items/RemoteSearch/Image?imageUrl=https%3A%2F%2Fimage.tmdb.org%2Ft%2Fp%2Foriginal%2Fesec4AKT1BVNeQbPMO9rCHHvSvd.jpg&ProviderName=TheMovieDb"
[INF] Setting provider id's to item 81223a7f-dc8b-e0a8-2166-a4488d51f6ea-"Origins (2017)": "{\"Tmdb\":\"82875\"}"
</pre>
</details>

<details>
<summary>"Vikings (2013)" is misidentified as "Vikings (2012)".</summary>
No log entries mention "Vikings", but metadata and images for the wrong show (the 2012 documentary series) are displayed, so identification somehow happened without being logged.
</details>

<details>
<summary>"The Witcher (2019)" is misidentified as "A Discovery of Witches (2018)".</summary>
<pre>
[INF] TmdbSearch: Finding id for item: "the witcher" (null)
[WRN] HTTP Response 200 to "127.0.0.1". Time (slow): 0:00:02.3997156. "http://localhost:8096/Items/RemoteSearch/Series"
[WRN] HTTP Response 200 to "127.0.0.1". Time (slow): 0:00:01.0688129. "http://localhost:8096/Items/RemoteSearch/Image?imageUrl=https%3A%2F%2Fm.media-amazon.com%2Fimages%2FM%2FMV5BOGFjMTQxNGQtMTExMC00ZGMyLTk5M2QtNDdhNjMwNWY4ZWZhXkEyXkFqcGdeQXVyNjU1OTg4OTM%40._V1_SX300.jpg&ProviderName=The%20Open%20Movie%20Database"
[WRN] Cannot fetch image from "https://www.thetvdb.com/banners/seasons/5dc27f167f6b9.jpg"
[WRN] HTTP Response 200 to "127.0.0.1". Time (slow): 0:00:01.2390132. "http://localhost:8096/Items/RemoteSearch/Image?imageUrl=https%3A%2F%2Fm.media-amazon.com%2Fimages%2FM%2FMV5BOGE4MmVjMDgtMzIzYy00NjEwLWJlODMtMDI1MGY2ZDlhMzE2XkEyXkFqcGdeQXVyMzY0MTE3NzU%40._V1_SX300.jpg&ProviderName=The%20Open%20Movie%20Database"
[WRN] HTTP Response 200 to "127.0.0.1". Time (slow): 0:00:01.4801909. "http://localhost:8096/Items/RemoteSearch/Image?imageUrl=https%3A%2F%2Fimage.tmdb.org%2Ft%2Fp%2Foriginal%2F5Su6Cq1icggn2ObdsYgZyjABizA.jpg&ProviderName=TheMovieDb"
[WRN] HTTP Response 200 to "127.0.0.1". Time (slow): 0:00:02.2088792. "http://localhost:8096/Items/RemoteSearch/Image?imageUrl=https%3A%2F%2Fimage.tmdb.org%2Ft%2Fp%2Foriginal%2FzrPpUlehQaBf8YX2NrVrKK8IEpf.jpg&ProviderName=TheMovieDb"
[INF] Setting provider id's to item 99c40146-922c-d534-19cf-45f11e75ecf5-"A Discovery of Witches": "{\"Tmdb\":\"71912\"}"
</pre>
</details>

**Screenshots**
n/a

**Additional context**
Interestingly, the logs show the _right_ IDs (mostly TMDb, but one IMDb) for all of these shows (for example, 71912 is the right ID for The Witcher on TheMovieDB), but the wrong names, and the metadata for the wrongly-named show is what gets downloaded and applied. 

My TV shows library has 55 shows have one-word names, 7 of which were misidentified (13% failure rate), and 64 shows with multi-word names, none of which were misidentified.

- Series metadata downloaders are (1) TheTVDB, (2) TheMovieDB, and (3) The Open Movie Database.
- Season metadata downloaders are (1) TheMovieDB.
- Episode metadata downloaders are (1) TheTVDB and (2) TheMovieDb. The Open Movie Database is listed as an option, but is not checked.

I believe these are the defaults, unless I accidentally clicked something while adding the library yesterday.

**Comment by Larvitar** [comment]
`MediaBrowser.Providers\Plugins\TheTvdb\TvdbSeriesProvider.cs`

```
        internal static bool IsValidSeries(Dictionary<string, string> seriesProviderIds)
        {
            return seriesProviderIds.ContainsKey(MetadataProvider.Tvdb.ToString()) ||
                   seriesProviderIds.ContainsKey(MetadataProvider.Imdb.ToString()) ||
                   seriesProviderIds.ContainsKey(MetadataProvider.Zap2It.ToString());
        }
```
This always returns `true` therefore TVDB will never search by name. In this case search results are returned by TheMovieDb. TheMovieDb returns proper results but then again TVDB messes up on `GetMetadata` and fills metadata with wrong series. The whole code for `GetSearchResults` in TVDB plugin looks unfinished. It returns too many unrelated results, processes series names improperly etc. I can look into this and submit a PR, but maybe someone is already working on it?

**Comment by Larvitar** [comment]
LoL. It looks like it's theTVDB itself that's broken. Example:
`https://www.thetvdb.com/search`
Searching for `witcher` returns results that are more or less accurate, but if you add year - `witcher 2019` it returns 3 results, none of which is even remotely related and the first one is `Yamada-kun and the Seven Witches (2013)`

**Comment by Larvitar** [comment]
@fffrankieh I have a prototype fix for theTvDB search.

I've tried reproducing your problems with almost exact same setup (10.6.4, Ubuntu 20.04) and I have not been able to. All of those series are identified properly. What are your language settings for this library?

**Comment by fffrankieh** [comment]
If it's still useful to know, the library is set to English / United States.

Thanks for taking a look at these.

**Comment by whalehub** [comment]
Another example is _Dark (2017)_ which is misidentified as _The Dark Side of the Sun (2017)_.
