### ISSUE TITLE
希望增加手机端上传照片和视频功能，修改场景下的剧集图片中文显示的名称。谢谢

### ISSUE THREAD

**Issue by lin824858785** [jellyfin/jellyfin#4133]
感谢Jellyfin如此优秀的多媒体软件，众多程序员的无私奉献。
希望增加手机端上传照片和视频功能，手机拍摄的短视频或照片可以上传到jellyfin服务器上。
场景下的第一集、第二集、第三集希望改成第一章、第二章、第三章，中文集与章代表的意思不同。谢谢
![aa](https://user-images.githubusercontent.com/71211683/93014907-840e4680-f5e7-11ea-95c0-09e6df69e5a0.jpg)

**Comment by Darkwolf1515** [comment]
使用谷歌翻译

照片上传已从程序中删除，不会再回来。


这些是程序自动生成的章节，如果电影缺少其自己的章节，将使用这些程序。

希望这可以帮助！

**Comment by ZhiboWong** [comment]
> 使用谷歌翻译
> 
> 照片上传已从程序中删除，不会再回来。
> 
> 这些是程序自动生成的章节，如果电影缺少其自己的章节，将使用这些程序。
> 
> 希望这可以帮助！

为什么不支持照片上传功能了？多棒的功能，市面少缺少多媒体服务。
