### ISSUE TITLE
TV seasons renamed to show name after manual identification

### ISSUE THREAD

**Issue by fffrankieh** [jellyfin/jellyfin#4134]
**Describe the bug**
After using the "Identify" dialog to manually identify a show, all seasons of the show are renamed to the name of the show.

For example, "Condor (2018)" was misidentified as "The Legend of the Condor Heroes (2017)" in the initial library scan. After I used the "Identify" dialog to find and select the right show, both seasons were named "Condor" instead of "Season 1" and "Season 2".

This also happens when re-identifying a show as itself. For example, "Alien Nation (1989)" was correctly identified during the initial library scan. I used the "Identify" dialog to search for "Alien Nation" and selected the same show. After the metadata refresh finished and the dialog disappeared, the single season had been renamed to "Alien Nation" instead of "Season 1".

This problem was previously reported in #1843, but that issue was closed by the stale bot and I wasn't sure if new replies would be seen. Also, unlike that issue, the TV shows I have are not anime, and I have not installed any additional plugins or changed any options relating to metadata.

**System (please complete the following information):**
 - OS: Ubuntu 18.04
 - Virtualization: none
 - Clients: Browser
 - Browser: Firefox 80
 - Jellyfin Version: 10.6.4
 - Playback: n/a
 - Installed Plugins: default (AudioDB, MusicBrainz, OMDb, TheTVDB)
 - Reverse Proxy: n/a
 - Base URL: none
 - Networking: n/a
 - Storage: local

**To Reproduce**
1. Go into a TV shows library.
2. Click the "..." menu on any show.
3. Click "Identify" in the menu.
4. Type a show name.
5. Click the "Search" button.
6. Click a show in the search results.
7. Click the "OK" button.
8. Wait for the dialog to disappear.

**Expected behavior**
The seasons within the show are named "Season 1", "Season 2", and so on.

**Observed behavior**
All seasons are named "Show Name".

**Logs**
<details>
<summary>Log snippet</summary>
<p>Timestamps are truncated for brevity; nothing else is changed.</p>
<pre>
[03:07:42.328] [INF] TmdbSearch: Finding id for item: "Alien Nation" (null)
[03:07:45.042] [WRN] HTTP Response 200 to "127.0.0.1". Time (slow): 0:00:02.7240278. "http://localhost:8096/Items/RemoteSearch/Series"
[03:07:49.245] [INF] Setting provider id's to item 3aab32c6-71dd-35f3-6099-e861d3f5a0f5-"Alien Nation": "{\"Tmdb\":\"5383\"}"
[03:07:52.611] [INF] OnRefreshStart "3aab32c671dd35f36099e861d3f5a0f5"
[03:07:52.613] [INF] OnRefreshStart "8a57308fb788e3b23dfc67cdc2c4b49c"
[03:07:52.620] [INF] OnRefreshComplete "8a57308fb788e3b23dfc67cdc2c4b49c"
[03:08:11.168] [INF] OnRefreshComplete "3aab32c671dd35f36099e861d3f5a0f5"
[03:08:11.168] [WRN] HTTP Response 204 to "127.0.0.1". Time (slow): 0:00:21.9348486. "http://localhost:8096/Items/RemoteSearch/Apply/3aab32c671dd35f36099e861d3f5a0f5?ReplaceAllImages=false"
</pre></details>

**Screenshots**
n/a

**Additional context**
n/a

**Comment by esmondmissen** [comment]
Similar thing happens with music artists. When I manually identify the artist it renames all the albums to one of the artists albums. For example I manually identified Adele which changed all her albums to her album "25"

**Comment by Larvitar** [comment]
`MediaBrowser.Providers\Plugins\Tmdb\TV\TmdbSeasonProvider.cs:69`

``` C#
                    // Don't use moviedb season names for now until if/when we have field-level configuration
                    // result.Item.Name = seasonInfo.name;

                    result.Item.Name = info.Name;
```
I think when using `Identify` `info.Name` includes series name for some reason. I can't check it though because `Identify` is not working for me on `master` branch. We could just remove this line since we don't want to overwrite it anyway but why is `info.Name` set to series name in the first place?

**Comment by cvium** [comment]
@fffrankieh Not something I can reproduce in master/unstable. Which providers do you have enabled for tv?

**Comment by Larvitar** [comment]
> @fffrankieh Not something I can reproduce in master/unstable. Which providers do you have enabled for tv?

Is `Identify` working for you at all? It was not when I tried it last week. It would search and find results properly but after clicking "Save changes" no data was saved and metadata providers were not run. It happened for everything not only seasons. Actually I think that even simply editing metadata was not possible

**Comment by fffrankieh** [comment]
> @fffrankieh Not something I can reproduce in master/unstable. Which providers do you have enabled for tv?

Just the default ones, unless I clicked a checkbox by accident. Here are all the settings for my TV library; the first two (in bold) are the only ones I changed on purpose:

- **Preferred download language: English**
- **Country: United States**
- Special season display name: Specials
- [ ] Prefer embedded titles over filenames
- [ ] Prefer embedded episode information over filenames
- [x] Enable real time monitoring
- Series metadata downloaders:
   - [x] TheTVDB
   - [x] TheMovieDb
   - [x] The Open Movie Database
- Season metadata downloaders:
   - [x] TheMovieDb
- Episode metadata downloaders:
   - [x] TheTVDB
   - [x] TheMovieDb
   - [ ] The Open Movie Database
- Automatically refresh metadata from the internet: Never
- Metadata savers:
   - [ ] Nfo
- Series Image Fetchers:
   - [x] TheTVDB
   - [ ] TheMovieDb
- Season Image Fetchers:
   - [x] TheTVDB
   - [x] TheMovieDb
- Episode Image Fetchers:
   - [x] TheTVDB
   - [ ] TheMovieDb
   - [ ] The Open Movie Database
   - [x] Screen Grabber
- [ ] Save artwork into media folders
- [ ] Download images in advance
- [ ] Automatically merge series that are spread across multiple devices
- [x] Display missing episodes within seasons
- [ ] Enable chapter image extraction
- [ ] Enable chapter image extraction during the library scan

**Comment by Mange** [comment]
I have the same issue.

I was trying to refresh my library with TheTVDB at the bottom since images stopped working from them, but now I get this issue instead.
