### ISSUE TITLE
local network detection does not work with local ipv6 address and local dns name

### ISSUE THREAD

**Issue by daniel1v** [jellyfin/jellyfin#4141]
**Describe the bug**
local network detection does not work with ipv6 ula address, for example fd00::/8. it basically works when trying to connect to server directly via ipv6 address. but when trying to connect to the server via local dns name (http://jellyfin.fritz.box:8096) the connection is refused.

connecting over local dns only works when i whitelist the global ipv6 client ip. but as the global ip changes whenever the router reconnects to the internet, jellyfin should also respect the local client addresses, which could be set to not change.

**System (please complete the following information):** 
- OS: Raspbian Buster
 - Virtualization: Docker
 - Clients: testetd with browser, android, antroidtv
 - Browser: ms edge chromium
 - Jellyfin Version: 10.6.4
 - Playback: --
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: none
 - Networking: host
 - Storage: local

**To Reproduce**
restrict jellyfin server to local ips (no external connection) and type in a (ula) ipv6 address mask. then connect via dns name. jellyfin refuses the connection and shows "forbidden"

**Expected behavior**
jellyfin should recognize that the client is on the local network and accept the connection

**Logs**
event is not logged

**Comment by BaronGreenback** [comment]
IPv6 is not supported in JF yet (hoping for 10.7) - hence your issues. At the basic level - it cannot parse an IPv6, or understand IPv6 dns lookups.

**Comment by daniel1v** [comment]
> IPv6 is not supported in JF yet (hoping for 10.7) - hence your issues. At the basic level - it cannot parse an IPv6, or understand IPv6 dns lookups.
> 
> There is a test version at #3994, however this is based upon the unstable so some things may not work at the moment (dlna playTo being one of them).
>
> Take a look at the TrustAllIP6Interfaces option - it might suit your setup.

Okay, thank you for your answer. So I will leave this issue open until it works.

**Comment by Silkas01** [comment]
Is that function still not implemented or have I just not figured out yet how to set it up? I am currently running Version 10.8.5 inside the docker container and have the same problems as described above.

**Comment by Shadowghost** [comment]
https://github.com/jellyfin/jellyfin/pull/8147 should make this work
