### ISSUE TITLE
Syncplay does not continue past the first episode when shuffled.

### ISSUE THREAD

**Issue by kurumushi** [jellyfin/jellyfin#4155]
**Describe the bug**
When playing a tv show on shuffle, sync play works fine for the first episode, but sync is turned off after the first episode

**System (please complete the following information):**
 - OS: Linux
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Firefox 80.0.1
 - Jellyfin Version: 10.6.4
 - Playback: Direct Play
 - Installed Plugins: None
 - Reverse Proxy: nginx
 - Base URL: none
 - Networking: Host
 - Storage: local

**To Reproduce**

1. Play a tv show on shuffle.
2. Create a sync group, and join the group on a second client
3. Wait for the video to move to the  next episode
4. Both clients continue to play, but leave the sync group and play different episodes.

**Expected behavior**
The sync group should be continued, and future episodes played in sync

**Comment by OancaAndrei** [comment]
Playlist support is under development in this PR #3194.
