### ISSUE TITLE
BaseUrl breaks DLNA Server functionality.

### ISSUE THREAD

**Issue by BaronGreenback** [jellyfin/jellyfin#4161]
The dlna server used the DLNA base url functionality within its descriptions, enabling shorter url's to be used within it xml description.

However, it looks like this shorting of service urls is not supported (at least in UPnP Tools - which I have to assume is correct).

The result is that services cannot be parsed. eg, **Look at the serviceUrl** - BaseUrl is set to Jellyfin/

![image](https://user-images.githubusercontent.com/22121540/93328586-d633af80-f813-11ea-9910-c79a4f5d9e3a.png)

**Comment by BaronGreenback** [comment]
Fixed in https://github.com/jellyfin/jellyfin/pull/4162

**Comment by PrplHaz4** [comment]
I think this also fixes #2377 and closes #3481
