### ISSUE TITLE
Playing Image Always Starts with the First One

### ISSUE THREAD

**Issue by zzc-tongji** [jellyfin/jellyfin#4167]
It is a bug in version 10.6.4.

In a photo library, it will always start at the first image when playing an image.

![image](https://user-images.githubusercontent.com/20331014/93415118-c39b9380-f870-11ea-98dc-4d4538b8f430.png)

**It should start with the current one (especially when viewing a photo library with a large amount of image).**

**Comment by fgebh** [comment]
Hi, have the same issue.
In my case it happens for largen amount of pictures in one folder (>1000). 
When I click on the thumbnail, it opens always the same (which is the first in the folder) picture.

Version: 10.6.4.

**Comment by thiendang18** [comment]
Hi, i have the same issue.
In my case it happens for largen amount of pictures in one folder (>1000).
Version: Jellyfin 10.7.0 Release Candidate 3
@crobibero

**Comment by michal-olszanowski** [comment]
The issue persists in version 10.7.7.

**Comment by VirgilChen97** [comment]
I can confirm that this issue persists in version 10.7.7.
