### ISSUE TITLE
"The container field is required." error

### ISSUE THREAD

**Issue by mehmetistif** [jellyfin/jellyfin#4168]
**Describe the bug**
No playback in chrome, opera, edge, ps4 browser.

**System (please complete the following information):**
 - OS: Windows
 - Clients: Browser
 - Browser: Chrome 85, ps4 7.55
 - Jellyfin Version: 10.7.0, nightly 20200916.4
 - Playback: Direct Play, Transcode
 - Reverse Proxy: none
 - Base URL: none
 - Networking: localhost
 - Storage: local

**To Reproduce**

1. To play on any media

**Expected behavior**

**Logs**
No log on the server side.
Client side error is: 
{"type":"https://tools.ietf.org/html/rfc7231#section-6.5.1","title":"One or more validation errors occurred.","status":400,"traceId":"|c3f5c63d-4ecebcb7c60cb541.","errors":{"container":["The container field is required."]}}

**Screenshots**
![image](https://user-images.githubusercontent.com/25367667/93427566-b01b1780-f8c6-11ea-8ce9-5b24dca8bf99.png)

**Additional context**
If this changes applied in source code (DynamicHlsController.cs, every controller needs container param), no error on client side and playback is running without problem:
[FromRoute, Required] string container,
-->
[FromRoute] string? container,

Container = container,
-->
Container = container ?? "mp4",

**Comment by BaronGreenback** [comment]
https://github.com/jellyfin/jellyfin/pull/4173
