### ISSUE TITLE
Unstable - Error deserializing item with JSON

### ISSUE THREAD

**Issue by blablup** [jellyfin/jellyfin#4172]
Hello,

I still get the Error, I thought it should be fixed by #MR3951 (https://github.com/jellyfin/jellyfin/pull/3951). Maybe  commit 9ddf550b43b3dcaa1129e369242bd664632bff03 broke it again?
 
```
Sep 17 13:58:05 media jellyfin[21454]: [13:58:05] [DBG] AuthenticationScheme: CustomAuthentication was successfully authenticated.
Sep 17 13:58:05 media jellyfin[21454]: [13:58:05] [ERR] Error deserializing item with JSON: {"SpecialFeatureIds":[],"LocalTrailerIds":[],"RemoteTrailerIds":[],"TmdbCollectionName":null,"AdditionalParts":[],"LocalAlternateVersions":[],"LinkedAlternateVersions":[],"Timestamp":null,"SubtitleFiles":[],"HasSubtitles":false,"IsPlaceHolder":false,"DefaultVideoStreamIndex":0,"VideoType":"VideoFile","IsoType":null,"Video3DFormat":null,"AspectRatio":null,"Size":"2083739494","Container":"mov,mp4,m4a,3gp,3g2,mj2","DateLastSaved":"2020-08-11T17:50:35.1846658Z","RemoteTrailers":[{"Url":"https://www.youtube.com/watch?v=sPXByAnJWNc","Name":"Die Stunde des Verbrechens - Trailer"}],"IsHD":true,"IsShortcut":false,"ShortcutPath":null,"Width":1280,"Height":720,"ExtraIds":[],"SupportsExternalTransfer":false}
Sep 17 13:58:05 media jellyfin[21454]: System.Text.Json.JsonException: The JSON value could not be converted to System.Nullable`1[System.Int64]. Path: $.Size | LineNumber: 0 | BytePositionInLine: 376.
```

I get this Error if I try to modify Metadata. Also depending on which fields are filled I get Error responses from server like:
{"type":"https://tools.ietf.org/html/rfc7231#section-6.5.1","title":"One or more validation errors occurred.","status":400,"traceId":"|7cead06d-45afd8ac33c5f67a.","errors":{"request":["The request field is required."],"$.ProductionYear":["The JSON value could not be converted to System.Nullable`1[System.Int32]. Path: $.ProductionYear | LineNumber: 0 | BytePositionInLine: 562."]}}

**System (please complete the following information):**
 - OS: Debian 10.5
 - Virtualization: LXC
 - Clients: Browser
 - Browser: Firefox 80
 - Jellyfin Version: 20200913.1-unstable or build from source
 - Reverse Proxy: nginx
 - Base URL: none

**To Reproduce**

1. Go to 'Metadata Manager'
2. Click on 'any Movie'
3. Change a value and save

**Comment by BaronGreenback** [comment]
Getting a similar JSON error trying to edit dlna profiles.

![image](https://user-images.githubusercontent.com/22121540/93617729-4423d680-f9ce-11ea-8067-8b2c7136bf21.png)

![image](https://user-images.githubusercontent.com/22121540/93617840-66b5ef80-f9ce-11ea-80de-e09eb406d7d5.png)

Exception:-

```
System.InvalidOperationException
  HResult=0x80131509
  Message=Cannot get the value of a token type 'String' as a number.
  Source=System.Text.Json
  StackTrace:
   at System.Text.Json.Utf8JsonReader.TryGetInt64(Int64& value)
   at System.Text.Json.Utf8JsonReader.GetInt64()
   at System.Text.Json.Serialization.Converters.Int64Converter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Converters.NullableConverter`1.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at MediaBrowser.Common.Json.Converters.JsonNullableStructConverter`1.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options) in C:\code\jellyfin\MediaBrowser.Common\Json\Converters\JsonNullableStructConverter.cs:line 35
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
```

**Comment by BaronGreenback** [comment]
fix outlined here https://geeks.ms/jorge/2020/03/18/cannot-get-the-value-of-a-token-type-number-as-a-string-con-system-text-json/

**Comment by BaronGreenback** [comment]
https://github.com/dotnet/runtime/issues/30255

**Comment by BaronGreenback** [comment]
https://github.com/dotnet/runtime/pull/42239

Custom handlers and number convertors are mutually exclusive.

**Comment by BaronGreenback** [comment]
Fix https://github.com/jellyfin/jellyfin/pull/4180

**Comment by layomia** [comment]
> Custom handlers and number convertors are mutually exclusive.

What do you mean by this?

The issue here appears to be that a custom converter for a number type is not doing a check for whether the number payload is written as a number or a string. I left a comment in https://github.com/jellyfin/jellyfin/pull/4180 that suggests the recommended way to do this.

Unless the [`JsonNumberHandling` feature](https://github.com/dotnet/runtime/pull/39363) new in .NET 5 is being used here, I don't believe that the issue has any thing to do with https://github.com/dotnet/runtime/pull/42239.

**Comment by BaronGreenback** [comment]
dotnet/runtime/#42239 was referenced as it states in the code the shows the comment "'JsonNumberHandlingAttribute' cannot be placed on a property, field, or type that is handled by a custom converter".

The JsonNumberHandling feature is being used in jsOnDefaults.cs

**Comment by layomia** [comment]
> "'JsonNumberHandlingAttribute' cannot be placed on a property, field, or type that is handled by a custom converter".

Was this exception thrown when running your own code? I can't see anything that indicates that. 

I've looked at the settings in [`JsonDefaults.cs`](https://github.com/jellyfin/jellyfin/blob/master/MediaBrowser.Common/Json/JsonDefaults.cs), and the number handling setting is specified globally on `JsonSerializerOptions`. The above exception is only thrown when `JsonNumberHandlingAttribute` is placed on a property or type which also has a custom converter.

**Comment by crobibero** [comment]
This is fixed in master.
