### ISSUE TITLE
Startup wizard incorrect routes

### ISSUE THREAD

**Issue by ottodoesntknow** [jellyfin/jellyfin#4179]
**Describe the bug**
By this [PR](https://github.com/jellyfin/jellyfin-web/pull/1647) on jellyfin-web, startup wizard routes changed to nested folders. But in Jellyfin 10.6.4 startup wizard old routes are still present, making it impossible to launch and just getting a blank page:
```
abc@0d9dd5cad1c5:/usr/share/jellyfin/web/controllers/wizard$ ls -la
total 28
drwxr-xr-x  2 root root 4096 Sep 13 08:21 .
drwxr-xr-x 12 root root 4096 Sep 13 08:21 ..
-rw-r--r--  1 root root  331 Aug 30 22:45 finish.js
-rw-r--r--  1 root root  930 Aug 30 22:45 remoteaccess.js
-rw-r--r--  1 root root 2224 Aug 30 22:45 settings.js
-rw-r--r--  1 root root 1333 Aug 30 22:45 start.js
-rw-r--r--  1 root root 1535 Aug 30 22:45 user.js
```
Wil there be a quick patch for this?

**System (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Edge 87.0.637.0
 - Jellyfin Version: 10.6.4 (linuxserver image)
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: none
 - Networking: Host
 - Storage: local

**To Reproduce**
1. Create a new container with latest linuxserver stable image
2. Go to http://localhost:8096
3. You are greeted with a blank page, and the error shows up in the logs

**Expected behavior**
Jellyfin should use the new startup wizard routes.

**Logs**
`Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: Could not find a part of the path '/usr/share/jellyfin/web/controllers/wizard/start/index.js'. URL: http://192.168.0.19:8096/web/controllers/wizard/start/index.js?v=18`

**Comment by dkanada** [comment]
That pull request can't be the issue because it has not been included in a release yet.

**Comment by oscargb1** [comment]
Oops I thought it was the issue. Anyway, Jellyfin still thinks the wizard directory has a nested folder structure.
