### ISSUE TITLE
Blank/frozen video if scrubbing (or not) while direct streaming

### ISSUE THREAD

**Issue by mholt** [jellyfin/jellyfin#4188]
**Describe the bug**

I noticed that when scrubbing (sliding the bar along the bottom to change the current time in the video) on a video that is "Direct Streaming" the video will freeze or blank (show a black screen):

- On mobile (the Jellyfin android app) the audio will continue.
- On desktop, the whole player freezes and no audio continues either.

Edit: I'm not 100% sure one needs to always scrub in order to reproduce; letting the video play will also cause it.

**System (please complete the following information):**
 - OS: Debian, macOS, Chromecast, Android
 - Virtualization: none
 - Clients: Chrome, Firefox
 - Browser: Latest Chrome and Firefox
 - Jellyfin Version: 10.6.4
 - Playback: Direct Stream
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: none
 - Networking: Host
 - Storage: local

**To Reproduce**

Play a video that requires direct streaming. Scrub to somewhere in the middle while it is playing.

**Expected behavior**

The video scrubs to that position and plays normally.

**Logs**

Can definitely post some if they're deemed relevant; but there are no errors; everything looks normal and good in the logs, and the transcodes folder is populated.

**Screenshots**
(just a black screen with the controls, not much to show)

**Additional context**

In the admin dashboard, the video (while playing) is described as:

> The media is compatible with the device regarding resolution and media type (H.264, AC3, etc), but is in an incompatible file container (mkv, avi, wmv, etc). The video will be re-packaged on the fly before streaming it to the device.

And it shows a red progress bar that very quickly gets to the end of the video, while the blue progress bar is toward the beginning where the player is. This all looks correct, and the directstream logs all look good (and the transcodes folder is populated). But the video still freezes.

Scrubbing on videos that do not need "direct streaming" (i.e., already encoded as mp4 or something compatible with the player) works just fine. I do have hardware acceleration enabled but I do not believe that is the problem: transcoding works fine (and when I disable it, I still experience the problem, and have confirmed that the GPU is not doing the work as the CPU spikes then).

Anyway, is this a known issue? Am happy to drill down more, just give me some pointers.

See also: https://www.reddit.com/r/jellyfin/comments/ivknzt/blankfrozen_video_while_direct_streaming/

**Comment by mholt** [comment]
Still an issue as far as I can tell

**Comment by ocervell** [comment]
+1

**Comment by mholt** [comment]
Still an issue as far as I can tell

**Comment by bartlomiejborzucki** [comment]
I have come across a temporary solution. I copy the link of the file stream to the VLC application and then I can play the video (using Chromecast) from there. This is neither a convenient nor pleasant solution, but it works. Is there a chance to fix this bug?

**Comment by sevenrats** [comment]
It's not clear that this is a bug as these appear to be the symptoms of an underpowered transcode.

**Comment by mholt** [comment]
@sevenrats Actually, it's not underpowered transcode. The NVIDIA GeForce RTX 2700 Super is seeing low utilization. It encodes 4K HDR videos at thousands of frames per second using Handbrake. And this GPU has no problem scrubbing through transcodes in other software. The usual delay is about 1-2 seconds of latency.

This bug report is specifically for Direct Streaming -- as I understand it, that is the opposite of transcoding.

The bug report is about a broken scrubber.

**Comment by sevenrats** [comment]
@mholt "Direct Stream" means that your audio track is being reencoded, which is done in software on the CPU.  It's not a matter of being over or under-powered, it's a matter of time.  You can't scrub to a space in the video that has not yet been reencoded. When you do, you essentially reset the transcode (of the audio stream).  This reset of the reencoding process is very likely what is causing the latency you experience.  You can explore this by watching the transcode happen in your dashboard. Compare seeking within the completed reencode to seeking outside it, and let me know if you think this may be the case. We can reopen if you think it's still an issue.

**Comment by bartlomiejborzucki** [comment]
I have the same issue, and I don't think it's related to transcoding.
In my case, it looks like this: When you start a movie on Chromecast (e.g., on a Philips TV) from the very beginning, the movie works fine and can be watched without any problems, even in excellent quality. However, if you try to fast-forward the movie, for instance to the 30th minute, the above-described problem arises. Sometimes, after fast-forwarding the movie to the 30th minute, the picture freezes - there's a freeze frame, while the sound restarts from the beginning of the movie.

**Comment by mholt** [comment]
Ok, thanks for explaining, I learned something! It's been a few years so let me see next chance I get when this happens.

**Comment by srcrist** [comment]
I believe that this should resume after a delay, though. Even if they are scrubbing to an area where the stream has not been remuxed to the new container. Does the stream resume after some time, or does it never resume? If the latter, that seems like a bug. Especially considering the above information about the stream continuing in VLC.

**Comment by mholt** [comment]
Yeah. I've also had success through a media link to VLC. For me, the video never resumes playing, even after like 30 seconds.

If/when I can, I'll try to get a screen recording but I don't know if I'll have a chance anytime soon...

**Comment by srcrist** [comment]
I'm going to reopen this and move it to our testing triage for now, because it's probably worth seeing why the resume is not happening. My understanding is that a delay in playback is expected, but that playback should not break entirely. We've got a serious backlog, so it may take a bit to get tested. But feel free to add whatever you can come up with. No rush on that either.

**Comment by simmonsil** [comment]
This appears to still be an issue, happening to me on latest version 10.11.0. Direct Streaming playback will completely freeze and never resume. This happens to me after just letting the video play for a couple minutes or I if I scrub forward it will freeze and never resume. If I force full transcoding, the video unfreezes and begins working and I can scrub back and forth completely fine.
