### ISSUE TITLE
Huge disk IO performance issue in Docker

### ISSUE THREAD

**Issue by Gerben321** [jellyfin/jellyfin#4190]
I've asked on Reddit about it, but not answers. I'm seeing HUGE HDD read speeds on my Synology NAS with the Jellyfin Docker image. There are two modest libraries added for movies and series, and I've disabled the watcher. Was looking like a nice package in the start, but I've had several times that my whole NAS started to freeze. Here's the original post with info and a screenshot: https://www.reddit.com/r/jellyfin/comments/igjkh0/high_disk_read_speeds_with_jellyfin_in_docker/

Today I've seen 220mb/s read speeds. I then shut down the Docker container and the system went back to normal. Any idea why this is? It's really starting to become a showstopper which forces me back to a MySQL database for Kodi.

**Comment by Artiume** [comment]
It might be related to this fellow
https://github.com/jellyfin/jellyfin/issues/2355

**Comment by Gerben321** [comment]
I don't seem to have any ffmpeg references in my logs.

**Comment by ssamjh** [comment]
This is still a problem. I have discovered two workarounds.

1. If you are using CPU encoding, enable the "throttle transcodes" options. And you could also apply option 2 as a boost.
2. Create a RAMDISK and pass that through to the VM as detailed here: https://forum.jellyfin.org/t/transcoding-to-ram/174/4
