### ISSUE TITLE
Unrecognized option 'speed'. ffmpeg transcoding

### ISSUE THREAD

**Issue by RandolphNimmer** [jellyfin/jellyfin#4193]
**Media Info of the file**
Taxi S01E01 Like Father, Like Daughter
Containermkv
PathD:\Shows\Taxi (1978-1983)\Season 01\Taxi S01E01 Like Father, Like Daughter.mkv
Size242 MB
Video
Title480p H264
CodecH264
AVCNo
ProfileMain
Level31
Resolution716x478
Aspect ratio4:3
InterlacedNo
Framerate23.976025
Bitrate1369 kbps
Bit depth8 bit
Pixel formatyuv420p
Ref frames1
NAL0
Audio
TitleEng AAC stereo Default
Languageeng
CodecAAC
ProfileLC
Layoutstereo
Channels2 ch
Bitrate192 kbps
Sample rate48000 Hz
DefaultYes
Subtitle
TitleEng
Languageeng
CodecASS
DefaultNo
ForcedNo
ExternalNo

**Logs**
{"Protocol":"File","Id":"9cfbb8947d61d0224837fe61c4b24f9f","Path":"D:\\Shows\\Taxi (1978-1983)\\Season 01\\Taxi S01E01 Like Father, Like Daughter.mkv","Type":"Default","Container":"mkv,webm","Size":253583408,"Name":"Taxi S01E01 Like Father, Like Daughter","IsRemote":false,"ETag":"2ebcfdb792b781623b1350295aa44cc9","RunTimeTicks":14813849600,"ReadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"RequiresClosing":false,"RequiresLooping":false,"SupportsProbing":true,"VideoType":"VideoFile","MediaStreams":[{"Codec":"h264","ColorTransfer":"bt709","ColorPrimaries":"smpte170m","TimeBase":"1/1000","CodecTimeBase":"1001/48000","VideoRange":"SDR","DisplayTitle":"480p H264","NalLengthSize":"0","IsInterlaced":false,"IsAVC":false,"BitRate":1369439,"BitDepth":8,"RefFrames":1,"IsDefault":true,"IsForced":false,"Height":478,"Width":716,"AverageFrameRate":23.976025,"RealFrameRate":23.976025,"Profile":"Main","Type":"Video","AspectRatio":"4:3","Index":0,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"PixelFormat":"yuv420p","Level":31},{"Codec":"aac","Language":"eng","TimeBase":"1/1000","CodecTimeBase":"1/48000","Title":"Stereo","DisplayTitle":"Eng AAC stereo Default","IsInterlaced":false,"ChannelLayout":"stereo","BitRate":192000,"Channels":2,"SampleRate":48000,"IsDefault":true,"IsForced":false,"Profile":"LC","Type":"Audio","Index":1,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Level":0},{"Codec":"ass","Language":"eng","TimeBase":"1/1000","CodecTimeBase":"0/1","localizedUndefined":"Undefined","localizedDefault":"Default","localizedForced":"Forced","DisplayTitle":"Eng","IsInterlaced":false,"IsDefault":false,"IsForced":false,"Type":"Subtitle","Index":2,"IsExternal":false,"IsTextSubtitleStream":true,"SupportsExternalStream":true,"Level":0}],"MediaAttachments":[],"Formats":[],"Bitrate":1561439,"RequiredHttpHeaders":{}}

C:\Program Files\Jellyfin\Server\ffmpeg.exe -c:v h264_cuvid -resize 716x478 -i file:"D:\Shows\Taxi (1978-1983)\Season 01\Taxi S01E01 Like Father, Like Daughter.mkv" -map 0:0 -map 0:1 -map -0:s -codec:v:0 libvpx -force_key_frames "expr:gte(t,n_forced*5)" -pix_fmt yuv420p -speed 16 -quality good -profile:v 0 -slices 8 -crf 10 -qmin 0 -qmax 50 -maxrate:v 3423598 -bufsize:v 6847196 -b:v 3423598 -vsync -1 -map_metadata -1 -map_chapters -1 -threads 7 -codec:a:0 libvorbis -ac 2 -ab 192000  -y "C:\ProgramData\Jellyfin\Server\transcodes\4e0ddb4b77f25591f15be495e3a2d76e.webm"

ffmpeg version n4.3.1-1-g4c6eb642fe Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 10.1.0 (Rev3, Built by MSYS2 project)
  configuration:  --disable-static --enable-shared --cc='ccache gcc' --cxx='ccache g++' --disable-ffplay --disable-debug --enable-gpl --enable-version3 --enable-bzlib --enable-iconv --enable-lzma --enable-zlib --enable-sdl2 --enable-fontconfig --enable-gmp --enable-libass --enable-libzimg --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libwebp --enable-libx264 --enable-libx265 --enable-libdav1d --enable-opencl --enable-dxva2 --enable-d3d11va --enable-amf --enable-libmfx --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvenc --enable-nvdec --enable-ffnvcodec --enable-gnutls --shlibdir=/local64/bin-video
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Unrecognized option 'speed'.
Error splitting the argument list: Option not found

**FFmpeg Logs**
C:\Program Files\Jellyfin\Server\ffmpeg.exe -c:v h264_cuvid -resize 716x478 -i file:"D:\Shows\Taxi (1978-1983)\Season 01\Taxi S01E01 Like Father, Like Daughter.mkv" -map 0:0 -map 0:1 -map -0:s -codec:v:0 libvpx -force_key_frames "expr:gte(t,n_forced*5)" -pix_fmt yuv420p -speed 16 -quality good -profile:v 0 -slices 8 -crf 10 -qmin 0 -qmax 50 -maxrate:v 3423598 -bufsize:v 6847196 -b:v 3423598 -vsync -1 -map_metadata -1 -map_chapters -1 -threads 7 -codec:a:0 libvorbis -ac 2 -ab 192000  -y "C:\ProgramData\Jellyfin\Server\transcodes\4e0ddb4b77f25591f15be495e3a2d76e.webm"

ffmpeg version n4.3.1-1-g4c6eb642fe Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 10.1.0 (Rev3, Built by MSYS2 project)
  configuration:  --disable-static --enable-shared --cc='ccache gcc' --cxx='ccache g++' --disable-ffplay --disable-debug --enable-gpl --enable-version3 --enable-bzlib --enable-iconv --enable-lzma --enable-zlib --enable-sdl2 --enable-fontconfig --enable-gmp --enable-libass --enable-libzimg --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libwebp --enable-libx264 --enable-libx265 --enable-libdav1d --enable-opencl --enable-dxva2 --enable-d3d11va --enable-amf --enable-libmfx --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvenc --enable-nvdec --enable-ffnvcodec --enable-gnutls --shlibdir=/local64/bin-video
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
**Unrecognized option 'speed'.
Error splitting the argument list: Option not found**

**Stats for Nerds Screenshots**
Not available

**Server System (please complete the following information):**
 - OS: Windows 10
 - Jellyfin Version: 10.6.4
 - Hardware settings & device: NVENC hardware accelerated on GTX 1060
 - Reverse proxy: nginx
 - Other hardware notes: Media is on local SSD
 
**Client System (please complete the following information):**
 - Device: Microsoft Surface
 - OS: Windows 10
 - Client: Web Client
 - Browser (if Web client): Chrome
 - Client and Browser Version: Not sure about browser version, but should be the latest because auto updates are enabled., Client version is 10.6.4

NOTE: I had her try it in Microsoft Edge as well, where video worked but audio did not.

**Comment by nyanmisaka** [comment]
In general, chrome supports h264 playback. But it requested vp9 format instead of h264 format in your case.
You may need to update your chrome and enable NVENC decoders and encoder in Jellyfin dashboard.

Download the new ffmpeg with libvpx encoder down below and extract all into the root folder of Jellyfin.

[ffmpeg-4.3.1-vpx.zip](https://github.com/jellyfin/jellyfin/files/5259317/ffmpeg-4.3.1-vpx.zip)

NVIDIA driver >= 450.51 is required.

**Comment by RandolphNimmer** [comment]
Excellent thank you for the help, I'll give that a try. Any way to force chrome to request h264 instead of vp9? I'll have the user update Chrome

**Comment by nyanmisaka** [comment]
> Excellent thank you for the help, I'll give that a try. Any way to force chrome to request h264 instead of vp9? I'll have the user update Chrome

Chrome reported to Jellyfin that it does not support h264, so vp9 was chosen. I think updating to the recent Chrome 85 should support h264 in most cases. If it is on some specific distro of Linux, users may need to install these software decoders manually.

> edit: forgot to mention, nvenc and nvdec/purevideo are enabled in the dashboard. do you have a paypal/crypto for tips/donations

Thanks! [buymeacoffee.com/nyanmisaka](www.buymeacoffee.com/nyanmisaka)

> edit2: User did not need to update Chrome, and the newer ffmpeg binary/libraries fixed the issue. Thank you. I also went ahead and enabled hardware decode/encode for vp8, vp9, and x264 because it was disabled by default in Jellyfin. Would be more than glad to buy you lunch if you shoot me somewhere to send it.

This is what I expected. But if Chrome supports h264 for direct play, then there is no need to transcode.
Currently, only a few hardware decoders are enabled by default. In the future, I may add a function that may automatically detect hardware capabilities, which will be much more convenient then.
