### ISSUE TITLE
HLS Error: Type: networkError Details: levelLoadTimeOut Fatal: false

### ISSUE THREAD

**Issue by maximeaudy** [jellyfin/jellyfin#4201]
**Describe the bug**

I installed jellyfin in a docker container, I have a reverse proxy with nginx which redirects to the port of the container, but when I launch a video, it loops

**Logs in navigator**
HLS Error: Type: networkError Details: levelLoadTimeOut Fatal: false

Logs in container
MediaBrowser.Api.Playback.Hls.VideoHlsService: FFMpeg exited with code 1

**Comment by sumeetkpatel** [comment]
I'm also getting this but only on certain Live TV m3u8 streams

**Comment by cvium** [comment]
Please re-open and fill out the issue template properly. We need the complete logs, not random snippets you think is relevant. There's not enough information here 🤷
