### ISSUE TITLE
Jellyfin ASUSTOR package support

### ISSUE THREAD

**Issue by sparky8251** [jellyfin/jellyfin#421]
[Requested by a user on reddit.](https://www.reddit.com/r/jellyfin/comments/acrltj/jellyfin_asustor_package_support/)

Looks like it has its own package repo. [See these developer guides on how to proceed.](http://developer.asustor.com/document/App_Central_Developer_Guide_2.0.0_0801.pdf)

**Comment by Dm3k1** [comment]
Looking forward to this

**Comment by weiyideai520** [comment]
Also Looking forward to this

**Comment by sevenrats** [comment]
moved to https://features.jellyfin.org/posts/2354/jellyfin-asustor-package-support
