### ISSUE TITLE
[bug] Windows installer - service not running, shortcuts not created

### ISSUE THREAD

**Issue by mickert** [jellyfin/jellyfin#4218]
**Description**
After installation (fresh) with jellyfin_10.6.4_windows-x64.exe, and subsequent reinstall:
1. Some shortcuts are created in Administrator profile, not in the profile of the user requesting the install or the all users profile.
2. Creation of desktop shortcut "Jellyfin Server.lnk" fails.
3. No jellyfin process is running so no web console is available at http://localhost:8096

**To Reproduce**
1. Download Jellyfin installer from https://repo.jellyfin.org/releases/server/windows/stable/installer/jellyfin_10.6.4_windows-x64.exe
2. Install with option "Basic Install" (leave all default)
3. Check start menu, administrator start menu, try to open http://localhost:8096
4. (check for jellyfish process and/or listening processes on tcp 8096 using tasklist and netstat)

**Expected behavior**
1. Jellyfin is correctly installed, service is running
2. Installer asks to install for everyone or only for this user (in case of "basic" install)
a. Case 'everyone': shortcuts get created in all user profile
b. Case 'this user': shortcuts are created in the user profile of the user requesting the install / elevation, not under the Administrator account.
3. (Installer asks if it should create desktop shortcuts.)
4. (Installer asks if it should launch the web console for further configuration)

**Logs**
N/A

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/18481543/94373080-36bfc800-0103-11eb-9111-e4c326c82923.png)
![afbeelding](https://user-images.githubusercontent.com/18481543/94373186-03ca0400-0104-11eb-8a2d-2a82142eec50.png)

**System**
- OS: Windows 10 Pro x64 (10.0.18363.1082)
- User account: Not "Administrator", non privileged user. installer asked for elevation correctly.
- Browser: N/A
- Jellyfin Version: 10.6.3
- Installed Plugins: none
- Reverse proxy: N/A
 
**Work arounds**
Browse to the Administrator's  AppData\Roaming\Microsoft\Windows\Start Menu\Programs\ directory directory and copy the "Jellyfin Server" directory to: "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\"

**Comment by mohd-akram** [comment]
I'm getting the same error.
