### ISSUE TITLE
Database not being written to in docker containers

### ISSUE THREAD

**Issue by sparky8251** [jellyfin/jellyfin#422]
For me and at least one other, at least the users.db is not being written to properly inside of docker containers.

Opening the users.db file results in an empty database UNLESS you copy the cache files users.db-shm and users.db-whl as well.

I am really curious as to whether or not this behavior is consistent with other methods of running Jellyfin as this is really not good.

**Comment by anthonylavado** [comment]
I can check on my non-Docker Debian and macOS copies today.

**Comment by hawken93** [comment]
in work we had trouble with docker things not updating their databases, I'm kinda personally interested in this

**Comment by hawken93** [comment]
It's weird because I thought sqlite did sync writes when anyone commits a transaction, I think it's really unexpected...

**Comment by sparky8251** [comment]
That's what I'm saying, there is no code to commit and close the db connection during normal operation so its never written into the db proper.

When its shutdown outside of a container, it gets the right signal and follows the proper codepath to do so but docker doesn't seem to send that proper signal.
