### ISSUE TITLE
Chromecast disconnects after a minute of phone sleep (OnePlus 5T)

### ISSUE THREAD

**Issue by twiclo** [jellyfin/jellyfin#4224]
Jellyfin server version: 10.6.2
Android app version: 1.0.2

If I play a video on my TV via Chromecast and put my phone to sleep it will disconnect after what seems like only a minute. I know OnePlus has been pretty heavy handed on battery saving measures but other apps such as YouTube are able to maintain the connection. I've turned off every battery saving setting I could for jellyfin to no avail

**Comment by seitensei** [comment]
My understanding is that Expo/the mobile app doesn't currently have fully functioning background support, so the app is probably terminated within a short period of entering background, even if you aren't sleeping.
