### ISSUE TITLE
Total play time incorrect in artist view.

### ISSUE THREAD

**Issue by d3ssen** [jellyfin/jellyfin#4237]
**Describe the bug**
When looking at an artist that has multiple albums, the total play time (of all songs/albums) is incorrect.
But looking at an album from that artist shows the correct total play time for all songs in that album.

While the artist view shows '39 mins' of total play time for all songs in all albums of that artist, one album from that artist already has a total play time of '56 mins'.

**System (please complete the following information):**
 - OS: Ubuntu 18.04
 - Virtualization: Docker
 - Clients: Browser, Android.
 - Browser: Chrome 85
 - Jellyfin Version: 10.6.3
 - Playback: Direct Play, Transcode] 
 - Installed Plugins: AudioDB, MusicBrainz, OMDb, Open Subtitles, TheTVDB
 - Reverse Proxy: apache
 - Base URL: none
 - Networking: NAT
 - Storage: local (separate system within same network)

**To Reproduce**
1. Click any artist that has multiple albums
2. Check **x mins** underneath artist name
3. Click any album from that artist
4. Check **x mins** for that album

**Expected behavior**
When looking at artist expect to be shown correct total play time for all songs in all albums.

**Logs**

**Screenshots**

![image](https://user-images.githubusercontent.com/17850118/94529506-1e9e9480-023a-11eb-83ea-ba8fcb1098c9.png)
![image](https://user-images.githubusercontent.com/17850118/94529573-32e29180-023a-11eb-8cda-3f83018d55a8.png)

**Additional context**

**Comment by cmt29** [comment]
I can reproduce this on Jellyfin 10.8.13 running on Raspberry Pi 4 (6.1.0-rpi7-rpi-v8). So I think this bug should be reopened.

**Comment by greigm** [comment]
Still an issue in 10.11.6.
