### ISSUE TITLE
ffmpeg asking for user input

### ISSUE THREAD

**Issue by WGrobler** [jellyfin/jellyfin#4238]
**Describe the bug**
I am having problems playing hi-res media files on my Jellyfin. I was trying to play the Hobbit and after about 30 minutes of playback it jumps back to earlier in the movie. Upon investigation into the ffmpeg logs I found the following:

> Enter command: <target>|all <time>|-1 <command>[ <argument>]
> 
> Parse error, at least 3 arguments were expected, only -1 given in string ''

I'm not familiar with ffmpeg, but from what I can find it seems that ffmpeg is asking for an input. Multiple support questions can be found with the same error when users are running scripts that require ffmpeg to loop. Apparently the default of ffmpeg is set up to run in interactive mode, when the loop happens it asks for an input. Because it is run in a script the response is null and therefore it crashes. Changing ffmpeg to run in non-interactive mode should fix these types of errors. But I am unfamiliar with the Jellyfin code or the ffmpeg implementation so I could not test it. 

I believe that due to the higher bitrate of the video file, my Jellyfin needs to loop and then ffmpeg crashes. When playing shorter/lower quality files the ffmpeg buffer is not filled up and therefore it works perfectly.

From what I can found ffmpeg can be changed to non-interactive by adding these tags tags:
-stdin - Enable interaction on standard input. On by default unless a pipe is detected.
-nostdin - To explicitly disable console interactions. Without -y this will cause ffmpeg to error out

If someone can direct me on how to change the ffmpeg mode for Jellyfin, I can test it.

**System (please complete the following information):**
 - OS: Debian, Windows
 - Virtualization: LXC
 - Clients: Android TV
 - Jellyfin Version: 10.6.4
 - Playback: Transcode
 - Installed Plugins: AudioDB, MusicBrainz, OMDb, TheTVDB, Track
 - Reverse Proxy: nginx
 - Base URL: none
 - Networking: Host
 - Storage: NFS

**Logs**

> ffmpeg logs
> http://media.lan:8096/videos/aeb8af07-47bb-94ed-a013-bb3befd0a354/stream.mkv?DeviceId=33dfad9f26798f51&MediaSourceId=aeb8af0747bb94eda013bb3befd0a354&VideoCodec=h264&AudioCodec=aac,mp3&AudioStreamIndex=1&VideoBitrate=1069929&AudioBitrate=93707&StartTimeTicks=54664030000&PlaySessionId=d3f66325417846a19fdef04ffbfac1db&api_key=669f8dfc5c4d4e6c890af40b38f9fcbe&SubtitleMethod=Encode&CopyTimestamps=true&RequireAvc=false&Tag=e3248b284045ac116264fc551ab4821f&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51&h264-maxrefframes=4&aac-audiochannels=2&mp3-audiochannels=2&TranscodeReasons=ContainerBitrateExceedsLimit&allowVideoStreamCopy=false&allowAudioStreamCopy=false&allowAudioStreamCopy=false
> 
> {"Protocol":"File","Id":"aeb8af0747bb94eda013bb3befd0a354","Path":"/mnt/data_storage/data_server/Movies/The Hobbit - The Desolation of Smaug (2013)/The Hobbit - The Desolation of Smaug (2013) 1080p AAC.mp4","Type":"Default","Container":"mov,mp4,m4a,3gp,3g2,mj2","Size":2208430592,"Name":"The Hobbit - The Desolation of Smaug (2013) 1080p AAC","IsRemote":false,"ETag":"e3248b284045ac116264fc551ab4821f","RunTimeTicks":96780369920,"ReadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"RequiresClosing":false,"RequiresLooping":false,"SupportsProbing":true,"VideoType":"VideoFile","MediaStreams":[{"Codec":"h264","CodecTag":"avc1","Language":"und","TimeBase":"1/24000","CodecTimeBase":"1001/48000","VideoRange":"SDR","DisplayTitle":"1080p H264","NalLengthSize":"4","IsInterlaced":false,"IsAVC":true,"BitRate":1727710,"BitDepth":8,"RefFrames":1,"IsDefault":true,"IsForced":false,"Height":800,"Width":1920,"AverageFrameRate":23.976025,"RealFrameRate":23.976025,"Profile":"High","Type":"Video","AspectRatio":"2.40:1","Index":0,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"PixelFormat":"yuv420p","Level":41},{"Codec":"aac","CodecTag":"mp4a","Language":"eng","TimeBase":"1/48000","CodecTimeBase":"1/48000","DisplayTitle":"Eng AAC stereo Default","IsInterlaced":false,"ChannelLayout":"stereo","BitRate":93707,"Channels":2,"SampleRate":48000,"IsDefault":true,"IsForced":false,"Profile":"LC","Type":"Audio","Index":1,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Level":0},{"Codec":"srt","Language":"eng","localizedUndefined":"Undefined","localizedDefault":"Default","localizedForced":"Forced","DisplayTitle":"Eng","IsInterlaced":false,"IsDefault":false,"IsForced":false,"Type":"Subtitle","Index":2,"IsExternal":true,"IsTextSubtitleStream":true,"SupportsExternalStream":true,"Path":"/mnt/data_storage/data_server/Movies/The Hobbit - The Desolation of Smaug (2013)/The Hobbit - The Desolation of Smaug (2013) 1080p AAC.eng.srt"}],"MediaAttachments":[],"Formats":[],"Bitrate":1825519,"RequiredHttpHeaders":{}}
> 
> /usr/share/jellyfin-ffmpeg/ffmpeg -ss 01:31:06.403 -f mov,mp4,m4a,3gp,3g2,mj2 -i file:"/mnt/data_storage/data_server/Movies/The Hobbit - The Desolation of Smaug (2013)/The Hobbit - The Desolation of Smaug (2013) 1080p AAC.mp4" -map 0:0 -map 0:1 -map -0:s -codec:v:0 libx264 -force_key_frames "expr:gte(t,n_forced*5)" -vf "scale=trunc(min(max(iw\,ih*dar)\,720)/2)*2:trunc(ow/dar/2)*2" -copyts -avoid_negative_ts disabled -start_at_zero -pix_fmt yuv420p -preset superfast -crf 23 -maxrate 1069929 -bufsize 2139858 -profile:v high -level 4.1 -x264opts:0 subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none -vsync -1 -map_metadata -1 -map_chapters -1 -threads 0 -codec:a:0 aac -ac 2 -ab 93707  -y "/var/lib/jellyfin/transcodes/d9b0e5666b7527f0b2f387d22347a1a5.mkv"
> 
> 
> ffmpeg version 4.2.1 Copyright (c) 2000-2019 the FFmpeg developers
>   built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
>   configuration: --toolchain=hardened --prefix=/usr --target-os=linux --enable-cross-compile --extra-cflags=--static --enable-gpl --enable-static --disable-doc --disable-ffplay --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-libfontconfig --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libwebp --enable-libx264 --enable-libx265 --enable-libzvbi --enable-omx --enable-omx-rpi --enable-version3 --enable-vaapi --enable-vdpau --arch=amd64 --enable-nvenc --enable-nvdec --enable-amf
>   libavutil      56. 31.100 / 56. 31.100
>   libavcodec     58. 54.100 / 58. 54.100
>   libavformat    58. 29.100 / 58. 29.100
>   libavdevice    58.  8.100 / 58.  8.100
>   libavfilter     7. 57.100 /  7. 57.100
>   libswscale      5.  5.100 /  5.  5.100
>   libswresample   3.  5.100 /  3.  5.100
>   libpostproc    55.  5.100 / 55.  5.100
> Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'file:/mnt/data_storage/data_server/Movies/The Hobbit - The Desolation of Smaug (2013)/The Hobbit - The Desolation of Smaug (2013) 1080p AAC.mp4':
>   Metadata:
>     major_brand     : isom
>     minor_version   : 1
>     compatible_brands: isomavc1
>     creation_time   : 2014-03-19T06:52:09.000000Z
>   Duration: 02:41:18.04, start: 0.000000, bitrate: 1825 kb/s
>     Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709/bt709/unknown), 1920x800 [SAR 1:1 DAR 12:5], 1727 kb/s, 23.98 fps, 23.98 tbr, 24k tbn, 47.95 tbc (default)
>     Metadata:
>       creation_time   : 2014-03-19T06:52:09.000000Z
>       handler_name    : video.264#trackID=1:fps=23.976 - Imported with GPAC 0.5.0-rev
>     Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 93 kb/s (default)
>     Metadata:
>       creation_time   : 2014-03-19T06:52:36.000000Z
>       handler_name    : GPAC ISO Audio Handler
> Stream mapping:
>   Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
>   Stream #0:1 -> #0:1 (aac (native) -> aac (native))
> Press [q] to stop, [?] for help
> [libx264 @ 0x562e3fdb5dc0] using SAR=1/1
> [libx264 @ 0x562e3fdb5dc0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2
> [libx264 @ 0x562e3fdb5dc0] profile Main, level 4.1
> [libx264 @ 0x562e3fdb5dc0] 264 - core 148 r2748 97eaef2 - H.264/MPEG-4 AVC codec - Copyleft 2003-2016 - http://www.videolan.org/x264.html - options: cabac=1 ref=1 deblock=1:0:0 analyse=0x1:0 me=dia subme=0 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=4 chroma_me=0 trellis=0 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=0 threads=6 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=1 keyint=250 keyint_min=23 scenecut=40 intra_refresh=0 rc_lookahead=10 rc=crf mbtree=0 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 vbv_maxrate=1069 vbv_bufsize=2139 crf_max=0.0 nal_hrd=none filler=0 ip_ratio=1.40 pb_ratio=1.30 aq=1:1.00
> Output #0, matroska, to '/var/lib/jellyfin/transcodes/d9b0e5666b7527f0b2f387d22347a1a5.mkv':
>   Metadata:
>     encoder         : Lavf58.29.100
>     Stream #0:0: Video: h264 (libx264) (H264 / 0x34363248), yuv420p, 720x300 [SAR 1:1 DAR 12:5], q=-1--1, 23.98 fps, 1k tbn, 23.98 tbc (default)
>     Metadata:
>       encoder         : Lavc58.54.100 libx264
>     Side data:
>       cpb: bitrate max/min/avg: 1069000/0/0 buffer size: 2139000 vbv_delay: -1
>     Stream #0:1: Audio: aac (LC) ([255][0][0][0] / 0x00FF), 48000 Hz, stereo, fltp, 93 kb/s (default)
>     Metadata:
>       encoder         : Lavc58.54.100 aac
> frame=   68 fps=0.0 q=23.0 size=       1kB time=01:31:09.73 bitrate=   0.0kbits/s speed=1.09e+04x    
> frame=  162 fps=162 q=22.0 size=     772kB time=01:31:13.40 bitrate=   1.2kbits/s speed=5.46e+03x    
> _... REMOVED FRAME LINES ..._
> frame=55945 fps=164 q=24.0 size=  268990kB time=02:10:00.22 bitrate= 282.5kbits/s speed=22.9x    
> frame=56033 fps=164 q=23.0 size=  269623kB time=02:10:03.64 bitrate= 283.0kbits/s speed=22.9x    
> Enter command: <target>|all <time>|-1 <command>[ <argument>]
> 
> Parse error, at least 3 arguments were expected, only -1 given in string ''
> frame=56054 fps=149 q=23.0 size=  269755kB time=02:10:04.53 bitrate= 283.1kbits/s speed=20.8x    
> frame=56140 fps=149 q=25.0 size=  270075kB time=02:10:08.20 bitrate= 283.4kbits/s speed=20.7x    
> frame=56231 fps=149 q=23.0 size=  270468kB time=02:10:11.87 bitrate= 283.6kbits/s speed=20.7x    
> frame=56300 fps=149 q=-1.0 Lsize=  270978kB time=02:10:15.11 bitrate= 284.0kbits/s speed=20.7x    
> video:242743kB audio:27054kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.437646%
> [libx264 @ 0x562e3fdb5dc0] frame I:1178  Avg QP:18.43  size: 20706
> [libx264 @ 0x562e3fdb5dc0] frame P:19042 Avg QP:19.82  size:  7727
> [libx264 @ 0x562e3fdb5dc0] frame B:36080 Avg QP:22.60  size:  2135
> [libx264 @ 0x562e3fdb5dc0] consecutive B-frames: 10.8%  9.3%  5.7% 74.1%
> [libx264 @ 0x562e3fdb5dc0] mb I  I16..4: 19.0%  0.0% 81.0%
> [libx264 @ 0x562e3fdb5dc0] mb P  I16..4: 15.4%  0.0%  0.0%  P16..4: 66.4%  0.0%  0.0%  0.0%  0.0%    skip:18.1%
> [libx264 @ 0x562e3fdb5dc0] mb B  I16..4:  2.6%  0.0%  0.0%  B16..8: 28.3%  0.0%  0.0%  direct:13.1%  skip:56.0%  L0:31.7% L1:43.3% BI:25.0%
> [libx264 @ 0x562e3fdb5dc0] coded y,uvDC,uvAC intra: 57.4% 45.4% 15.1% inter: 21.4% 9.7% 0.1%
> [libx264 @ 0x562e3fdb5dc0] i16 v,h,dc,p: 35% 25% 26% 15%
> [libx264 @ 0x562e3fdb5dc0] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 24% 18% 14%  9%  8%  7%  7%  6%  8%
> [libx264 @ 0x562e3fdb5dc0] i8c dc,h,v,p: 50% 20% 22%  8%
> [libx264 @ 0x562e3fdb5dc0] Weighted P-Frames: Y:4.3% UV:1.3%
> [libx264 @ 0x562e3fdb5dc0] kb/s:846.85
> [aac @ 0x562e3fdb7140] Qavg: 163.528

**Comment by bvd13** [comment]
I'm having this problem on Jellyfin 10.8.1
