### ISSUE TITLE
How to use SRT / ass subtitles in BDMV format ?

### ISSUE THREAD

**Issue by dashi0611** [jellyfin/jellyfin#4239]
Because the built-in subtitles can't recognize the language, I tried to use the SRT / ass file, but none of them will be displayed

![image](https://user-images.githubusercontent.com/72114998/94634967-1743bd80-0304-11eb-9cc3-e01dc2374ea0.png)
![image](https://user-images.githubusercontent.com/72114998/94634988-232f7f80-0304-11eb-82d0-948564626147.png)

There is no problem with MKV format. but BDMV format, I tried to put SRT / ass file together with NFO, but it didn't show up

**Comment by dashi0611** [comment]
Can I mark the language manually when the built-in subtitle cannot recognize the language?

**Comment by dashi0611** [comment]
No problem with version 10.7

**Comment by kangbeicai** [comment]
是把jellyfin升级到10.7 就可以对BDMV加载字幕了嘛？

**Comment by nyanmisaka** [comment]
> 是把jellyfin升级到10.7 就可以对BDMV加载字幕了嘛？

Please wait for the upcoming 10.7, you will allowed to use your own fonts for subtitles.
See https://github.com/jellyfin/jellyfin/pull/3683

**Comment by kangbeicai** [comment]
> > 是把jellyfin升级到10.7 就可以对BDMV加载字幕了嘛？
> 
> Please wait for the upcoming 10.7, you will allowed to use your own fonts for SSA/ASS subtitles.
> See #3683

thank you for your reply! I‘m trying to watch BDMV format in jellyfin, but it didn't allow me to choose the audio track and subtitles. I also try the unstable 10.7 in dockerhub, but it doesn't work. Will the upcoming official version of 10.7 allow it ?

**Comment by nyanmisaka** [comment]
This PR might be useful for you. https://github.com/jellyfin/jellyfin/pull/4169

**Comment by ukanuk** [comment]
Where should NFO file be located for a BDMV or VIDEO_TS folder backup? Jellyfin docs aren't explicit.

Kodi says put `index.nfo` in BDMV folder and `VIDEO_TS.nfo` in VIDEO_TS subfolder. A bit invasive, and different from what's shown in original post above. https://kodi.wiki/view/NFO_files/Movies

Also see #9254 and https://features.jellyfin.org/posts/1989/bdmv-movie-nfo-path

**Comment by MrPeteypoo** [comment]
Thanks for this, I was having the same issue because I bought the 4K version of Sakra from Germany and needed English subtitles to be picked up. The following structure worked for me:
![image](https://github.com/user-attachments/assets/7c9e9f90-1a55-4038-aea9-b430734e81f0)
