### ISSUE TITLE
Add Live TV display preferences

### ISSUE THREAD

**Issue by MrChip53** [jellyfin/jellyfin#4244]
**Describe the bug**
When the DisplayPreferencesController was wrote it appears support for Live TV custom preferences were left out. This will break Live TV settings for the Android clients and the Web clients. I'm sure other clients will break also.

Can someone add this back in please?

One of the relevant core files:

https://github.com/jellyfin/jellyfin/blob/master/Jellyfin.Api/Controllers/DisplayPreferencesController.cs

Relevant web files for examples of functionality:

https://github.com/jellyfin/jellyfin-web/blob/25cddbcce3ef1c603e0a1576f7bd5e300553795a/src/components/guide/guide-settings.js

https://github.com/jellyfin/jellyfin-web/blob/e2aff662038bdf0fb730f9811975a02bb13a52be/src/scripts/settings/userSettings.js

**Comment by crobibero** [comment]
Which fields are missing?
`livetv-channelorder`, `livetv-favoritechannelsattop`?

**Comment by MrChip53** [comment]
I actually found this issue trying to fix a bug on the android tv client. I would copy and paste these for you but I'm on mobile at the moment so this is the best I can do.

These are the specific values that web and android tv use. Currently, they are stored inside the CustomPrefs json object inside the userpreferences.db file.

So if my memory if correct the current path the clients use is root->CustomPrefs->"livetv/guide-preference".

https://www.github.com/jellyfin/jellyfin-androidtv/tree/master/app%2Fsrc%2Fmain%2Fjava%2Forg%2Fjellyfin%2Fandroidtv%2Fui%2Flivetv%2FTvManager.java

Lines 147-154
