### ISSUE TITLE
Add health check endpoint

### ISSUE THREAD

**Issue by maxirus** [jellyfin/jellyfin#4246]
Add a health check endpoint to Jellyfin so that probes can "ping" it on a short cadence to ensure Jellyfin is up and healthy.

This should return a simple HTTP status code (ie. 200 OK). Anything other than `200` would indicate an unhealthy state for Jellyfin. Health Check endpoint/port should always run on HTTP (not HTTPS).

**Comment by PrplHaz4** [comment]
IMO, https://jellyfin.mydomain.com/System/Info/Public seems to fit the bill fine, no?  It does not force HTTP (it listens where the server does), but I'm not sure that should be a hard requirement.

**Comment by cvium** [comment]
There are different ways to handle health checks. I think the built-in one makes sense to explore: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-3.1

That said, feature requests belong here https://features.jellyfin.org

**Comment by crobibero** [comment]
Additionally, health checks were added in https://github.com/jellyfin/jellyfin/pull/4045

**Comment by PrplHaz4** [comment]
> 
> 
> Additionally, health checks were added in #4045

This currently returns `200 OK` - `Healthy` on master
`https://jftest2.mydomain.com/health`
