### ISSUE TITLE
Unstable installer link resolves to 404 error page

### ISSUE THREAD

**Issue by ryanjoachim** [jellyfin/jellyfin#4251]
**Describe the bug**
Attempting to download the latest Unstable installer from `https://repo.jellyfin.org/releases/server/windows/unstable/installer` brings you to a 404 error page.

**System (please complete the following information):**
 - OS: Windows
 - Clients: Browser (Firefox, Edge Chromium)
 - Browser: [e.g. Firefox 72, Chrome 80, Safari 13]

**To Reproduce**
1. Go to https://repo.jellyfin.org/releases/server/windows/unstable/
2. Click on **installer**
3. See error

**Expected behavior**
The latest Unstable installer will begin downloading, or I will see a page listing available downloads to choose from.

**Comment by crobibero** [comment]
This is not a bug, the installer is currently built manually per release.
