### ISSUE TITLE
PlayAll/Shufflle of Mixed Photos and Videos only plays videos 

### ISSUE THREAD

**Issue by trizzone52** [jellyfin/jellyfin#4256]
When pressing Play All or Shuffle in a Photo library, there are 2 behaviors:
-If there's any videos in the folder, it only plays videos. 
-If there is no videos, it slideshows the pictures. 

This discrepancy in behavior is especially pronounced when there is only one or two videos among 1000s of photos. It would be nice if there was one behavior regardless of whether there was video mixed in with the Photos, either always playing Photos or always shuffling all of both videos and photos.

This was tested on a fresh install of jellyfin 10.6.4 on Debian Buster.

**Comment by VerbTheNoun95** [comment]
This is happening to me as well on a similar system (jellyfin 10.6.4, raspberry pi with debian buster). I tried moving all the videos out and now shuffle/play all in the root of the photo library results in a playback error (says it's attempting to serve an incompatible format). I can shuffle/play all in all subdirectories in the same library, though.

**Comment by VerbTheNoun95** [comment]
For what it's worth, I found out why this is happening and wrote the solution [here](https://www.reddit.com/r/jellyfin/comments/le5ohc/any_way_to_get_more_verbose_logs_when_playing/). Turns out it looks only for audio and video, and not photos. Adding the "photo" tag in the client fixes it. This only works for the browser client, though.

**Comment by joskapista44** [comment]
The problem is still exist, I have the same issue. It only slideshows the pictures for me. :(

**Comment by JohnEridium** [comment]
Same here, in a mixed album of images and videos, Jellyfin only shows videos. The linked solution does not seem to be applicable anymore because I can’t find the file „playbackmanager.js“ anymore.
