### ISSUE TITLE
subtitles-octopus-worker.data cannot get loaded

### ISSUE THREAD

**Issue by nyanmisaka** [jellyfin/jellyfin#4258]
**Describe the bug**

Get HTTP ERROR 404 from localhost:8096/web/libraries/subtitles-octopus-worker.data

**System (please complete the following information):**
 - OS: [Debian, Windows]
 - Clients: [Browser]
 - Browser: [Edge 85, Chrome 85]
 - Jellyfin Version: [10.7.0, nightly 20201002]
 - Playback: [Direct Play, Remux, Direct Stream, Transcode] 
 - Reverse Proxy: [none]
 - Base URL: [none]
 - Networking: [Host, Bridge/NAT]

**To Reproduce**
1. Select a SSA/ASS subtitle.
2. Play the video.
3. `subtitles-octopus` cannot render the subtitle.
4. See error from console.
5. Automatically fallback to subtitle burn-in.

**Expected behavior**
Subtitle can be rendered without using sub burn-in.

**Logs**
``
bundle.js?v=3:220 Worker error:  ErrorEvent {isTrusted: true, message: "Uncaught Error: Not Found : http://localhost:8096/web/libraries/subtitles-octopus-worker.data", filename: "http://localhost:8096/web/libraries/subtitles-octopus-worker.js", lineno: 1, colno: 2432, …}
``

`HTTP ERROR 404 http://localhost:8096/web/libraries/subtitles-octopus-worker.data`

**Additional context**
File with `.data` extension cannot be downloaded.

I am not sure of the mime type of such files.
https://github.com/jellyfin/jellyfin/blob/master/MediaBrowser.Model/Net/MimeTypes.cs

**Comment by crobibero** [comment]
All non-standard extensions will need to be added manually
