### ISSUE TITLE
Identify external HI/CC/SDH subtitles

### ISSUE THREAD

**Issue by morpheus65535** [jellyfin/jellyfin#4291]
As discussed on #jellyfin-dev:matrix.org, I'm working to have a common naming convention for external hearing-impaired / close captioned / deaf hearing subtitles. Here's what is the proposed naming:

1. Movie.en.hi.srt
2. Movie.en.cc.srt
3. Movie.en.sdh.srt

All of them should be recognized as English subtitles and having the tag identified in Jellyfin UI would be nice.

Kodi already support them. Plex have implemented it in their new Movie Agent. I' ve been talking with Luke from Emby and he agreed to implement it in Emby.

It would be nice to have Jellyfin join the club. :-)

**Comment by oddstr13** [comment]
Do you a link to a specification for the formatting of this?

**Comment by morpheus65535** [comment]
Nothing specific but here's the code that we use to determine if an external subtitles if hearing-impaired: https://github.com/morpheus65535/bazarr/blob/master/libs/subliminal_patch/core.py#L625-L641

**Comment by kooolarpan** [comment]
any updates on it?
