### ISSUE TITLE
Incorrect number of episodes on the jellyfin webpage for a given series

### ISSUE THREAD

**Issue by ghost** [jellyfin/jellyfin#4293]
**Describe the bug**
When Jellyfin was starting up, the NFS library decided to unmount itself.
This resulted in an incorrect number of episodes being reported for each show (e.g. a show that has 175 episodes shows only 43 on the cover). When I select the season I can still see all the episodes, but the number of them on the web interface is just incorrect. 

**System**
 - OS: Alpine Linux
 - Virtualization: Docker
 - Clients: Browser
 - Storage: overlayfs/NFS
 - I have no plugins installed

**To Reproduce**
1. Restart the container
2. In the same instant unmount the library
3. The chapters amount will show up incorrectly

**Expected behavior**
Upon restart, with the library mounted again, the chapters amount should go back to normal

**Screenshots**
https://imgur.com/a/f6BxKsT

**Comment by Tureenhilr8** [comment]
Managed to fix it by stopping the container and deleting /config.
