### ISSUE TITLE
Remove Premiere and Connect references?

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin#43]
In various spots, there are references to Premiere and Connect. Some of these were just links for more info (see #32 where I changed some of these).

We should look at how we can effectively “remove” these entries/links from the UI, so users don’t encounter them.

I imagine the underlying code can be left as is for now (if there’s no way to call it, is it really there?). That way if we opt to rebuild connect somehow, we have somewhere to start from.

**Comment by JustAMan** [comment]
I vote for complete removal. I can not imagine the need for re-implementing Connect if we never plan to do paid features... and I rather we do not. Paid support is fine, though, if someone asks.

**Comment by ajdunevent** [comment]
I have a lifetime Emby Premiere subscription which I got at the beginning of 2016 when the project was, as far as I knew, fully open source and, I think, before the nag screens and moving of important features to paid only (offtopic: imagine how irritated I am about their license bait-and-switch).  Though I have no right to weigh in on this topic as I'm not even remotely a developer, I also vote for complete removal.  If something like Premiere is left in, it should only unlock at most very minor, optional features (like a "Thanks for your support" badge and, I don't know, maybe an alternative color theme).  And, most importantly, the developers should be willing to accept without grief that their open source project might be forked to allow those very minor, optional features without payment.

**Comment by joshuaboniface** [comment]
@JustAMan I firmly said as much on Reddit, so definitely - let's just strip it all out.

I already hid the badge on the Admin Dashboard page.

**Comment by napcae** [comment]
Information: This issue is being worked on in [PR 412](https://github.com/jellyfin/jellyfin/pull/412).

**Comment by anthonylavado** [comment]
I can agree on this. Closing.
