### ISSUE TITLE
Breaking API Change: /Items/:id:/PlaybackInfo

### ISSUE THREAD

**Issue by iwalton3** [jellyfin/jellyfin#4311]
The PlaybackInfo endpoint used to accept arguments both from the query string and from a JSON body, but now only accepts them from a query string. The web client is known to use the query string, while Kodi and MPV Shim are using JSON.

**Comment by cvium** [comment]
ASP.NET Core Web Api does not support this in a nice way.

**Comment by dkanada** [comment]
It sounds like updating the web client would be best if we absolutely can't make this work.
