### ISSUE TITLE
TMDB - Missing support for episode groups

### ISSUE THREAD

**Issue by nextlooper42** [jellyfin/jellyfin#4322]
**Describe the bug**
TVDB has support for episode ordering, TMDB is missing this implementation so media player (Kodi for example) doesn't know how to properly order complicated series like Doctor Who with all specials and stuff.

**System**
 - OS: Windows 10
 - Browser: Firefox 81
 - Jellyfin Version: 10.6.4

**To Reproduce**
1. Add show to library with TMDB metadata provider only
2. Wait for scan
3. It will download episodes and seasons, but not ordering (eg. Aired Order, DVD Order, Absolute Order...)

**Expected behavior**
Be able to download and use this ordering (Kodi addon supports it for TVDB).

**Documentation**
https://developers.themoviedb.org/3/tv/get-tv-episode-groups

**Comment by cvium** [comment]
Not a bug, but a missing feature. https://features.jellyfin.org/
