### ISSUE TITLE
TMDB - Refresh metadata button doesn't work on shows/movies

### ISSUE THREAD

**Issue by nextlooper42** [jellyfin/jellyfin#4323]
**Describe the bug**
Scanner is not able to pull new/updated metadata from TMDB, instead will always show old.

**System**
 - OS: Windows 10
 - Browser: Firefox 81
 - Jellyfin Version: 10.6.4

**To Reproduce**
1. Click on three dot button on movie/show
2. Click on Refresh metada
3. Nothing gets updated

**Expected behavior**
Refresh metadata according to availible data on TMDB.

**Comment by cvium** [comment]
TMDB data is cached for 2 days. The cache is reduced to 1 hour in master.
