### ISSUE TITLE
Missing "Secure Connection Mode" Drop Down Options

### ISSUE THREAD

**Issue by KyleMiles** [jellyfin/jellyfin#4332]
[This documentation](https://jellyfin.org/docs/general/networking/letsencrypt.html#lets-encrypt-and-docker), at the bottom, says:
> Then, click the "Secure Connection Mode" dropdown, and select "Handled by reverse proxy".

Either I'm blind, or this isn't an actual option.

Latest Docker, Latest Ubuntu, Latest Everything; I just provisioned my server and (tried to) set up this project
 
**To Reproduce**

1. Go to 'Dashboard'
2. Click on 'Settings'
3. It's not there?

**Expected behavior**
For the option to be there, or for your docs to be up-to-date.

**Screenshots**
![image](https://user-images.githubusercontent.com/7171118/96070669-a7d6dd80-0e6e-11eb-9883-170e4d09162e.png)

**Additional Context**
I just want to be able to host SSL from two domains, which nginx handles just fine.  Any guidance on this would be appreciated. Thank you!

**Comment by Artiume** [comment]
10.6.X changed the networking interface and the documentation needs to be updated. As long as the Reverse Proxy and Jellyfin are on the same host/same network, you don't need to worry about enabling https within Jellyfin itself and just do it via nginx.
