### ISSUE TITLE
Turn on language consistency plugin on Weblate

### ISSUE THREAD

**Issue by comradekingu** [jellyfin/jellyfin#4337]
Can't add new translations for https://translate.jellyfin.org/projects/jellyfin/jellyfin-roku/ no way to add nb_NO
My account is https://translate.jellyfin.org/user/comradekingu/ if you want me to do it.

**Comment by dkanada** [comment]
I believe that's because Roku only supports a limited set of languages at the moment so new languages were turned off for the time being, but someone else will have to comment. We could add a custom internationalization system for better language support, but that doesn't exist yet.

**Comment by comradekingu** [comment]
Ah that makes sense. Add that as an announcement in the component, and nobody will have to wonder :)
Closing this.
