### ISSUE TITLE
Server dont scan all files and folders

### ISSUE THREAD

**Issue by weinic** [jellyfin/jellyfin#4344]
Hello,

i used jellifin on a Debian Server.

When i created a library (Video, Audio, ...  ) and added a folder to this, jellyfin scanned the folder.
But in some folders there are subfolders and these are no longer   because there is a video file in the parent folder. (*.mkv File)

**Comment by cvium** [comment]
Two libraries cannot share subfolders if that's what you're saying. Also... respect the dang issue template.
