### ISSUE TITLE
actor Doesn't work，loading always

### ISSUE THREAD

**Issue by ltove** [jellyfin/jellyfin#4352]
**Describe the bug**

**System (please complete the following information):**
 - OS: [synology]
 - Virtualization: [Docker]
 - Clients: [Browser]
 - Browser: [Chrome]
 - Jellyfin Version: [e.g. 10.6.4]
 - Networking: [Bridge/NAT]
 - Storage: [NFS]
Why do I install jellyfin on nas, but when I click on the metadata actor, it keeps turning around and cannot connect to other videos?

[2020-10-20 14:39:49.439 +00:00] [WRN] [41] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 500 to "172.17.0.1". Time (slow): 0:01:40.0295382.

why？？？？who can help me ??

**Comment by HaoChuh** [comment]
Same issue on Cent OS, Jellyfin version 10.6.4.

**Comment by fhyoga** [comment]
same issue

[16:37:14] [ERR] [31] Jellyfin.Server.Middleware.ExceptionMiddleware: Error proc
essing request: The request was canceled due to the configured HttpClient.Timeou
t of 100 seconds elapsing. URL GET /Users/015c24f47eb24e61b7021200a6e13946/Items
/692f37aa41c983ece856aa1803d4a467.                                              
[16:37:14] [WRN] [31] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HT
TP Response from http://192.168.2.177:8096/Users/015c24f47eb24e61b7021200a6e1394
6/Items/692f37aa41c983ece856aa1803d4a467 to 192.168.2.61 in 0:01:40.0413449 with
 Status Code 500                                                                
[16:37:14] [INF] [28] Emby.Server.Implementations.HttpServer.WebSocketManager: W
S 192.168.2.61 closed                                                           
[16:37:28] [ERR] [60] Jellyfin.Server.Middleware.ExceptionMiddleware: Error proc
essing request: The request was canceled due to the configured HttpClient.Timeou
t of 100 seconds elapsing. URL GET /Users/015c24f47eb24e61b7021200a6e13946/Items
/03f879f226af852c6d158d824bb5e5b0.

**Comment by cvium** [comment]
Any chance you can provide some more logs? And also the name of the actor and the movies that you have.

**Comment by coco2015224** [comment]
I found this issue is gone if I modify "setting->display->Library page size:" to 50.

**Comment by fhyoga** [comment]
> I found this issue is gone if I modify "setting->display->Library page size:" to 50.

it not work for me

**Comment by JamYiz** [comment]
It's very slow to show the movies sorted by actor.

**Comment by jackpgao** [comment]
```bash
cat <<EOF > /etc/hosts
> 127.0.0.1   localhost
::1 localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
172.17.0.2  nyanmisaka-jellyfin



13.224.161.90 api.themoviedb.org
13.35.7.102 api.themoviedb.org
13.225.103.26 api.themoviedb.org
13.226.191.85 api.themoviedb.org
13.225.103.110 api.themoviedb.org
52.85.79.89 api.themoviedb.org
13.225.41.40 api.themoviedb.org
13.226.251.88 api.themoviedb.org
> EOF

```

**Comment by stormyyd** [comment]
Same issue here.

Through reading the source code, I found that the jellyfin will always trying to fetching actor metadata from TMDB, which is blocked in China AFAIK. So you will get that error and the web page keep loading.

There is two ways to fix that:
1. Let jellyfin access internet through a proxy, or using hosts [like this](https://github.com/jellyfin/jellyfin/issues/4352#issuecomment-1163887173), mentioned by @jackpgao.
2. Disable jellyfin's TMDB actor metadata fetcher.

I cannot find a way to achieve method 2 through the web interface, so I go directly to changing the configuration file `config/system.xml`.

Add the following lines like this:
```diff
diff --git a/system.xml b/system.xml
--- a/system.xml
+++ b/system.xml
@@ -127,6 +127,17 @@
       <DisabledImageFetchers />
       <ImageFetcherOrder />
     </MetadataOptions>
+    <MetadataOptions>
+      <ItemType>Person</ItemType>
+      <DisabledMetadataSavers />
+      <LocalMetadataReaderOrder />
+      <DisabledMetadataFetchers>
+        <string>TheMovieDb</string>
+      </DisabledMetadataFetchers>
+      <MetadataFetcherOrder />
+      <DisabledImageFetchers />
+      <ImageFetcherOrder />
+    </MetadataOptions>
   </MetadataOptions>
   <SkipDeserializationForBasicTypes>true</SkipDeserializationForBasicTypes>
   <ServerName />
```

Then restart jellyfin, problem gone!

Related source file: [MediaBrowser.Controller/BaseItemManager/BaseItemManager.cs](https://github.com/jellyfin/jellyfin/blob/f954df2341174eaa0e5f3815b5cfd43efe76fe6e/MediaBrowser.Controller/BaseItemManager/BaseItemManager.cs#L38)

**Comment by kurtice** [comment]
This is a DNS pollution problem.
To solve this problem,
1. go to website https://dnschecker.org/#A/api.themoviedb.org, to get the IP of api.themoviedb.org. You can find a location where it's nearby your location at the map. Normally there are 4 IPs. Choose any of the four.
2. Modify hosts file of JELLYFIN, adding [52.84.18.87 api.Themoviedb.org ](replacing IP which you got at step 1, and without add []) to the hosts.
3. restart jellyfin. the problem should go.

**Comment by viakiba** [comment]
> 这里同样的问题。
> 
> 通过阅读源代码，我发现 jellyfin 总是试图从 TMDB 中获取演员元数据，这在中国 AFAIK 中被阻止。所以你会得到那个错误并且网页继续加载。
> 
> 有两种方法可以解决这个问题：
> 
> 1. 让 jellyfin 通过代理访问互联网，或者使用[这样](https://github.com/jellyfin/jellyfin/issues/4352#issuecomment-1163887173)的主机，由@jackpgao.
> 2. 禁用 jellyfin 的 TMDB actor 元数据提取器。
> 
> 无法通过web界面实现方法二，直接去修改配置文件`config/system.xml`。
> 
> 像这样添加以下行：
> 
> ```diff
> diff --git a/system.xml b/system.xml
> --- a/system.xml
> +++ b/system.xml
> @@ -127,6 +127,17 @@
>        <DisabledImageFetchers />
>        <ImageFetcherOrder />
>      </MetadataOptions>
> +    <MetadataOptions>
> +      <ItemType>Person</ItemType>
> +      <DisabledMetadataSavers />
> +      <LocalMetadataReaderOrder />
> +      <DisabledMetadataFetchers>
> +        <string>TheMovieDb</string>
> +      </DisabledMetadataFetchers>
> +      <MetadataFetcherOrder />
> +      <DisabledImageFetchers />
> +      <ImageFetcherOrder />
> +    </MetadataOptions>
>    </MetadataOptions>
>    <SkipDeserializationForBasicTypes>true</SkipDeserializationForBasicTypes>
>    <ServerName />
> ```
> 
> 然后重启jellyfin，问题就解决了！
> 
> 相关源文件：[MediaBrowser.Controller/BaseItemManager/BaseItemManager.cs](https://github.com/jellyfin/jellyfin/blob/f954df2341174eaa0e5f3815b5cfd43efe76fe6e/MediaBrowser.Controller/BaseItemManager/BaseItemManager.cs#L38)

Solved my problem, thank you!

**Comment by duzhuoshanwai** [comment]
> Same issue here.
> 
> Through reading the source code, I found that the jellyfin will always trying to fetching actor metadata from TMDB, which is blocked in China AFAIK. So you will get that error and the web page keep loading.
> 
> There is two ways to fix that:
> 
> 1. Let jellyfin access internet through a proxy, or using hosts [like this](https://github.com/jellyfin/jellyfin/issues/4352#issuecomment-1163887173), mentioned by @jackpgao.
> 2. Disable jellyfin's TMDB actor metadata fetcher.
> 
> I cannot find a way to achieve method 2 through the web interface, so I go directly to modifying the configuration file `config/system.xml`.
> 
> Adding the following lines like this:
> 
> ```diff
> diff --git a/system.xml b/system.xml
> --- a/system.xml
> +++ b/system.xml
> @@ -127,6 +127,17 @@
>        <DisabledImageFetchers />
>        <ImageFetcherOrder />
>      </MetadataOptions>
> +    <MetadataOptions>
> +      <ItemType>Person</ItemType>
> +      <DisabledMetadataSavers />
> +      <LocalMetadataReaderOrder />
> +      <DisabledMetadataFetchers>
> +        <string>TheMovieDb</string>
> +      </DisabledMetadataFetchers>
> +      <MetadataFetcherOrder />
> +      <DisabledImageFetchers />
> +      <ImageFetcherOrder />
> +    </MetadataOptions>
>    </MetadataOptions>
>    <SkipDeserializationForBasicTypes>true</SkipDeserializationForBasicTypes>
>    <ServerName />
> ```
> 
> Then restart jellyfin, problem gone!
> 
> Related source file: [MediaBrowser.Controller/BaseItemManager/BaseItemManager.cs](https://github.com/jellyfin/jellyfin/blob/f954df2341174eaa0e5f3815b5cfd43efe76fe6e/MediaBrowser.Controller/BaseItemManager/BaseItemManager.cs#L38)

it works well , thank you

**Comment by srcrist** [comment]
This problem is caused by a regional networking issue conflicting with an intended design. There is nothing, unfortunately, that Jellyfin can do to make this work. Head over to our feature requests at features.jellyfin.org if you'd like to open a feature request to make this an optional integration.

Closing this issue as it is not actually a bug.

**Comment by ZhelinCheng** [comment]
@stormyyd 
I am currently using version 10.9.6 and found that the MetadataOptions configuration is missing. How can I resolve this issue?

**Comment by stormyyd** [comment]
> @stormyyd I am currently using version 10.9.6 and found that the MetadataOptions configuration is missing. How can I resolve this issue?

I am using 10.9.7, which is fine.

And I am also trying to create a fresh instance by Docker, it shows that the `MetadataOptions` is still there. If you mean there is no a `MetadataOptions` item with `ItemType` equals to `Person`, that's the expected behaviour. As I mentioned before, you need to **ADD** a new `MetadataOptions` item with `ItemType` equals to `Person`, rather than modify a exist one.

If you mean there is no any `MetadataOptions` in `system.xml` at all, I'd like to sugguest you to run a fresh instance by Docker like I do, and coping the related config to your `system.xml`.

Here is an example:

```text
$ docker run -d -v /tmp/jellyfin/config:/config jellyfin/jellyfin:10.9.7
$ rg -C 5 "MetadataOptions" /tmp/jellyfin/config/config/system.xml
37-  <MaxAudiobookResume>5</MaxAudiobookResume>
38-  <InactiveSessionThreshold>0</InactiveSessionThreshold>
39-  <LibraryMonitorDelay>60</LibraryMonitorDelay>
40-  <LibraryUpdateDuration>30</LibraryUpdateDuration>
41-  <ImageSavingConvention>Legacy</ImageSavingConvention>
42:  <MetadataOptions>
43:    <MetadataOptions>
44-      <ItemType>Book</ItemType>
45-      <DisabledMetadataSavers />
46-      <LocalMetadataReaderOrder />
47-      <DisabledMetadataFetchers />
48-      <MetadataFetcherOrder />
49-      <DisabledImageFetchers />
50-      <ImageFetcherOrder />
51:    </MetadataOptions>
52:    <MetadataOptions>
53-      <ItemType>Movie</ItemType>
(...)
```

**Comment by physicsmeGH** [comment]
> Same issue here.
> 
> Through reading the source code, I found that the jellyfin will always trying to fetching actor metadata from TMDB, which is blocked in China AFAIK. So you will get that error and the web page keep loading.
> 
> There is two ways to fix that:
> 
> 1. Let jellyfin access internet through a proxy, or using hosts [like this](https://github.com/jellyfin/jellyfin/issues/4352#issuecomment-1163887173), mentioned by [@jackpgao](https://github.com/jackpgao).
> 2. Disable jellyfin's TMDB actor metadata fetcher.
> 
> I cannot find a way to achieve method 2 through the web interface, so I go directly to modifying the configuration file `config/system.xml`.
> 
> Adding the following lines like this:
> 
> diff --git a/system.xml b/system.xml
> --- a/system.xml
> +++ b/system.xml
> @@ -127,6 +127,17 @@
>        <DisabledImageFetchers />
>        <ImageFetcherOrder />
>      </MetadataOptions>
> +    <MetadataOptions>
> +      <ItemType>Person</ItemType>
> +      <DisabledMetadataSavers />
> +      <LocalMetadataReaderOrder />
> +      <DisabledMetadataFetchers>
> +        <string>TheMovieDb</string>
> +      </DisabledMetadataFetchers>
> +      <MetadataFetcherOrder />
> +      <DisabledImageFetchers />
> +      <ImageFetcherOrder />
> +    </MetadataOptions>
>    </MetadataOptions>
>    <SkipDeserializationForBasicTypes>true</SkipDeserializationForBasicTypes>
>    <ServerName />
> Then restart jellyfin, problem gone!
> 
> Related source file: [MediaBrowser.Controller/BaseItemManager/BaseItemManager.cs](https://github.com/jellyfin/jellyfin/blob/f954df2341174eaa0e5f3815b5cfd43efe76fe6e/MediaBrowser.Controller/BaseItemManager/BaseItemManager.cs#L38)

This used to work for some time for me but after some recent update of jellyfin it went back to the same old behavior (clicking on actor results in perpetual loading).
Checking the logs, I found that Jellyfin's trying to fetch actor data from TVDB (which is also not accessible in China) this time.

I tried a similar change in the system.xml file, just changing the <string>TheMovieDb</string> field to TheTVDB. This doesn't stop Jellyfin from trying to access TVDB. I had to disable the entire TVDB plugin for it to not get stuck.

I wonder if there's a more elegant solution than this.

**Comment by physicsmeGH** [comment]
> Same issue here.
> 
> Through reading the source code, I found that the jellyfin will always trying to fetching actor metadata from TMDB, which is blocked in China AFAIK. So you will get that error and the web page keep loading.
> 
> There is two ways to fix that:
> 
> 1. Let jellyfin access internet through a proxy, or using hosts [like this](https://github.com/jellyfin/jellyfin/issues/4352#issuecomment-1163887173), mentioned by [@jackpgao](https://github.com/jackpgao).
> 2. Disable jellyfin's TMDB actor metadata fetcher.
> 
> I cannot find a way to achieve method 2 through the web interface, so I go directly to modifying the configuration file `config/system.xml`.
> 
> Adding the following lines like this:
> 
> diff --git a/system.xml b/system.xml
> --- a/system.xml
> +++ b/system.xml
> @@ -127,6 +127,17 @@
>        <DisabledImageFetchers />
>        <ImageFetcherOrder />
>      </MetadataOptions>
> +    <MetadataOptions>
> +      <ItemType>Person</ItemType>
> +      <DisabledMetadataSavers />
> +      <LocalMetadataReaderOrder />
> +      <DisabledMetadataFetchers>
> +        <string>TheMovieDb</string>
> +      </DisabledMetadataFetchers>
> +      <MetadataFetcherOrder />
> +      <DisabledImageFetchers />
> +      <ImageFetcherOrder />
> +    </MetadataOptions>
>    </MetadataOptions>
>    <SkipDeserializationForBasicTypes>true</SkipDeserializationForBasicTypes>
>    <ServerName />
> Then restart jellyfin, problem gone!
> 
> Related source file: [MediaBrowser.Controller/BaseItemManager/BaseItemManager.cs](https://github.com/jellyfin/jellyfin/blob/f954df2341174eaa0e5f3815b5cfd43efe76fe6e/MediaBrowser.Controller/BaseItemManager/BaseItemManager.cs#L38)

This used to work for some time for me but after some recent update of jellyfin it went back to the same old behavior (clicking on actor results in perpetual loading).
Checking the logs, I found that Jellyfin's trying to fetch actor data from TVDB (which is also not accessible in China) this time.

I tried a similar change in the system.xml file, just changing the <string>TheMovieDb</string> field to TheTVDB. This doesn't stop Jellyfin from trying to access TVDB. I had to disable the entire TVDB plugin for it to not get stuck.

I wonder if there's a more elegant solution than this.

**Comment by camemb3rt** [comment]
Is there a way to disable the Actors/People metadata altogether?
I really couldn't care less who the actors are and this might sound crazy but I find knowing how the voice actors of animated stuff look to be really immersion-breaking.
I already tried disabling the scheduled task and locking the "People" section but whenever I add a new show it'll grab it regardless.

**Comment by danny100chan** [comment]
> Same issue here.
> 
> Through reading the source code, I found that the jellyfin will always trying to fetching actor metadata from TMDB, which is blocked in China AFAIK. So you will get that error and the web page keep loading.
> 
> There is two ways to fix that:
> 
> 1. Let jellyfin access internet through a proxy, or using hosts [like this](https://github.com/jellyfin/jellyfin/issues/4352#issuecomment-1163887173), mentioned by [@jackpgao](https://github.com/jackpgao).
> 2. Disable jellyfin's TMDB actor metadata fetcher.
> 
> I cannot find a way to achieve method 2 through the web interface, so I go directly to modifying the configuration file `config/system.xml`.
> 
> Adding the following lines like this:
> 
> diff --git a/system.xml b/system.xml
> --- a/system.xml
> +++ b/system.xml
> @@ -127,6 +127,17 @@
>        <DisabledImageFetchers />
>        <ImageFetcherOrder />
>      </MetadataOptions>
> +    <MetadataOptions>
> +      <ItemType>Person</ItemType>
> +      <DisabledMetadataSavers />
> +      <LocalMetadataReaderOrder />
> +      <DisabledMetadataFetchers>
> +        <string>TheMovieDb</string>
> +      </DisabledMetadataFetchers>
> +      <MetadataFetcherOrder />
> +      <DisabledImageFetchers />
> +      <ImageFetcherOrder />
> +    </MetadataOptions>
>    </MetadataOptions>
>    <SkipDeserializationForBasicTypes>true</SkipDeserializationForBasicTypes>
>    <ServerName />
> Then restart jellyfin, problem gone!
> 
> Related source file: [MediaBrowser.Controller/BaseItemManager/BaseItemManager.cs](https://github.com/jellyfin/jellyfin/blob/f954df2341174eaa0e5f3815b5cfd43efe76fe6e/MediaBrowser.Controller/BaseItemManager/BaseItemManager.cs#L38)

This work in 2025! 
disable it also make people load fast as hell
Many thanks!

**Comment by lydigaga** [comment]
> 我也遇到同样的问题。
> 
> 通过阅读源代码，我发现 Jellyfin 会一直尝试从 TMDB 获取演员元数据，而据我所知，TMDB 在中国是被屏蔽的。所以你会看到那个错误，网页也会一直加载。
> 
> 有两种方法可以解决这个问题：
> 
> 1. 让 Jellyfin 通过代理服务器访问互联网，或者使用[像这样的](https://github.com/jellyfin/jellyfin/issues/4352#issuecomment-1163887173)主机，如上文所述。[@jackpgao](https://github.com/jackpgao)。
> 2. 禁用 Jellyfin 的 TMDB 演员元数据获取器。
> 
> 我无法通过网页界面实现方法 2，所以我直接修改配置文件`config/system.xml`。
> 
> 添加以下几行代码，如下所示：
> 
> diff --git a/system.xml b/system.xml
> --- a/system.xml
> +++ b/system.xml
> @@ -127,6 +127,17 @@
>        <DisabledImageFetchers />
>        <ImageFetcherOrder />
>      </MetadataOptions>
> +    <MetadataOptions>
> +      <ItemType>Person</ItemType>
> +      <DisabledMetadataSavers />
> +      <LocalMetadataReaderOrder />
> +      <DisabledMetadataFetchers>
> +        <string>TheMovieDb</string>
> +      </DisabledMetadataFetchers>
> +      <MetadataFetcherOrder />
> +      <DisabledImageFetchers />
> +      <ImageFetcherOrder />
> +    </MetadataOptions>
>    </MetadataOptions>
>    <SkipDeserializationForBasicTypes>true</SkipDeserializationForBasicTypes>
>    <ServerName />
> 然后重启 Jellyfin，问题就解决了！
> 
> 相关源文件：[MediaBrowser.Controller/BaseItemManager/BaseItemManager.cs](https://github.com/jellyfin/jellyfin/blob/f954df2341174eaa0e5f3815b5cfd43efe76fe6e/MediaBrowser.Controller/BaseItemManager/BaseItemManager.cs#L38)

10.11.5 The version is still valid. Thank you.
