### ISSUE TITLE
directory navigation will occasionally fail

### ISSUE THREAD

**Issue by dkanada** [jellyfin/jellyfin#4353]
**Describe the Bug**

I believe this is related to hidden directories, which will disable the directory browser entirely on library creation.

**System:**

 - OS: Linux
 - Virtualization: None
 - Clients: Browser
 - Browser: Chrome
 - Jellyfin Version: Unstable
 - Playback: None
 - Installed Plugins: None
 - Reverse Proxy: Nginx
 - Base URL: None
 - Networking: Host
 - Storage: Local

**Reproduce**

Attempt to create a library, and any directory with dotfiles will trigger the bug.

**Expected Behavior**

The directory browser should show a list at the current location.

**Logs**

`[17:49:42] [ERR] [17] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request: Could not find file '/home/user/.steampath'. URL GET /Environment/DirectoryContents.`

**Comment by crobibero** [comment]
Does this work in 10.6.4?
