### ISSUE TITLE
BasePlugin DirectoryNotFoundException on LoadConfiguration

### ISSUE THREAD

**Issue by xaviergxf** [jellyfin/jellyfin#4357]
**Describe the bug**
When running for the first time the project BasePlugin doesn't has a file created and thrown DirectoryNotFoundException. Here at the BasePlugin.cs:

```
        private TConfigurationType LoadConfiguration()
        {
            var path = ConfigurationFilePath;

            try
            {
                return (TConfigurationType)XmlSerializer.DeserializeFromFile(typeof(TConfigurationType), path);
            }
            catch//DirectoryNotFoundException when path doesnt exist.
            {
                return (TConfigurationType)Activator.CreateInstance(typeof(TConfigurationType));
            }
        }
```
 Jellyfin should verify if path doesn't exists, instead of relying on an unknown exception.

**System (please complete the following information):**
 - OS: Windows
 - Virtualization: None
 - Clients:  NA
 - Jellyfin Version: master branch

**To Reproduce**
Execute jellyfin for the first time

**Comment by cvium** [comment]
Not a bug. Using Exists is indeed faster than throwing and catching exceptions but not a bug...
