### ISSUE TITLE
Jellyfin becomes progressively slower with every new user account

### ISSUE THREAD

**Issue by whalehub** [jellyfin/jellyfin#4364]
### Describe the bug
The library scan and search feature and the loading time of the media overview page (what you see right after logging in) all become progressively slower with every new user account that is created on a Jellyfin instance. For example, on a Jellyfin instance with around 500 user accounts, a library scan that takes five minutes to complete with one user now takes half a day to finish, a search that would finish in 1-2 seconds takes 15-20 seconds to complete and loading the media overview takes 10 seconds instead of 1-2 seconds.

### System
 - **OS:** Debian
 - **Virtualization:** Docker
 - **Clients:** Browser
 - **Browser:** Chrome 86
 - **Jellyfin Version:** 10.6.4
 - **Installed Plugins:** none
 - **Reverse Proxy:** nginx
 - **Base URL:** none
 - **Networking:** bridge
 - **Storage:** local

#### Prerequisites
- Linux
- Docker
- Python
- Pip
- Virtualenv

#### Steps
01. Set up a fresh dockerized instance of Jellyfin and go through the setup process.
02. Add a new library with a small amount of media (100 movies maximum) with the option `Enable real-time monitoring` disabled and the option `Download images in advance` enabled.
03. Wait for Jellyfin to finish the initial scan for fetching the metadata.
04. Start the `Scan Media Library` task once the initial scan has finished and write down the time it takes to complete.
05. Create an API key in the Jellyfin admin dashboard.
06. Create a new virtualenv on the Linux host OS and activate it.
07. Install the dependencies `argparse`, `cryptography`, `requests` and `yourls` in the virtualenv with `pip`.
08. Download the following Python script to your virtualenv: [create-jellyfin.py](https://gist.githubusercontent.com/whalehub/3964bdca8670885157a455345d5ecb18/raw/fcda22d9bd10ab4100b12b36a20d4c0533102b9e/create-jellyfin-user.py)
09. Edit it and fill in the variables `JELLYFIN_URL`, `JELLYFIN_API_KEY`, `JELLYFIN_ADMIN_USERNAME` and `JELLYFIN_ADMIN_PASSWORD`.
10. Create 100 new Jellyfin accounts like this:
```bash
for i in test-user-{001..100}; do python3 create-jellyfin-user.py -l 20 "${i}"; done
```
11. Start the `Scan Media Library` task again and write down the time it takes to complete.
12. Repeat steps 10 (with `{101..200}`, `{201..300}`, etc.) and 11 until satisfied.

**Test results (97 movies)**
```
1 user: 2-3 seconds
100 users: 10 seconds
500 users: 35 seconds
```

### Expected behavior
The peformance of these Jellyfin features should not be affected by the number of user accounts, certainly not to such a drastic degree.

**Comment by cvium** [comment]
Granted I only have 39 movies, but this is what I get: `Emby.Server.Implementations.ScheduledTasks.TaskManager: Scan Media Library Completed after 0 minute(s) and 4 seconds`

**Comment by whalehub** [comment]
@cvium How many users did you test it with?

**Comment by cvium** [comment]
I followed the steps minus number of movies and environment

**Comment by whalehub** [comment]
@cvium So does that mean you tested it with 100 users or 500? Also, can you try to reproduce the issue on Linux?

**Comment by cvium** [comment]
I tested it with 1 and 100. I don't think 500 is a reasonable case. It'd be far more interesting to reproduce it with fewer users and a larger (dummy) library.

I expect 100 users to be quite an edge case for 99% of users.

**Comment by whalehub** [comment]
@cvium While it's true that the slowdowns are most noticeable in edge case scenarios, I can't think of a reason why the performance of these features would be affected by the number of users in the database in the first place. It's not like Jellyfin has to query each user individually when you perform a search, start a library scan or visit the media overview page.

I should also note that these performance issues did not exist in Jellyfin 10.4.x and 10.5.x with the same number of users. It has only been an issue since the 10.6.x series of releases. If you want, I can try to narrow it down to a specific release within that series.

**Comment by cvium** [comment]
The problem is that the users are fetched from the database on every library item refresh progress message. We will add some caching.

**Comment by whalehub** [comment]
@cvium I don't understand - why was it designed like that?

**Comment by dkanada** [comment]
You'll have to go back at least five years to find the answer.

**Comment by cvium** [comment]
The in-memory cache was removed during the EFCore migration of the Users table.

**Comment by whalehub** [comment]
@dkanada If you're saying that this is a design decision that Jellyfin inherited from Emby at the time of the fork, then it can't be what's causing these performance issues. As I mentioned in a previous comment, these issues didn't exist in Jellyfin 10.4.x and 10.5.x and I have the data to prove it.

I just performed a test with two fresh dockerized Jellyfin instances. I added the same movie library with 97 items to each instance, waited for Jellyfin to finish the initial scan, changed to the `Scheduled Task` tab, started the `Scan Media Library` task, manually and copied the output from the log file. The results of the test are listed below.

### Jellyfin 10.5.5

- 1 user
```
[2020-10-27 16:07:43.432 +01:00] [INF] [29] TaskManager: "Scan Media Library" Completed after 0 minute(s) and 1 seconds
```

- 100 users
```
[2020-10-27 16:12:40.050 +01:00] [INF] [59] TaskManager: "Scan Media Library" Completed after 0 minute(s) and 1 seconds
```

- 500 users
```
[2020-10-27 16:19:08.746 +01:00] [INF] [63] TaskManager: "Scan Media Library" Completed after 0 minute(s) and 1 seconds
```

### Jellyfin 10.6.0

- 1 user
```
[2020-10-27 16:32:43.771 +01:00] [INF] [13] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Scan Media Library" Completed after 0 minute(s) and 1 seconds
```

- 100 users
```
[2020-10-27 16:38:03.577 +01:00] [INF] [23] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Scan Media Library" Completed after 0 minute(s) and 5 seconds
```

- 500 users
```
[2020-10-27 16:46:04.870 +01:00] [INF] [5] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Scan Media Library" Completed after 0 minute(s) and 33 seconds
```

These numbers demonstrate that the commit that introduced these performance issues must have been merged between at some point between the release of Jellyfin 10.5.5 and 10.6.0, i.e. between April 27th and and July 20th 2020. The culprit must be one of these commits: https://github.com/jellyfin/jellyfin/compare/v10.5.5...v10.6.0

I also want to reiterate that Jellyfin becomes slower with each user across the board. It's not just the library scans that become much slower, it's the search function, the time it takes to load the media overview page and all of the dashboard pages (the user list, device list, etc.). The user list on Jellyfin 10.5.5, for example, loads nearly instantly (<1 second) with 500 users whereas it takes a good 4-5 seconds to load on Jellyfin 10.6.0.

**Comment by crobibero** [comment]
We don’t have plans for a 10.6.5 release, so it will be in the 10.7 release.

**Comment by cvium** [comment]
Solved by https://github.com/jellyfin/jellyfin/pull/4377

**Comment by whalehub** [comment]
@cvium I can confirm that 9bf2f4d fixes the issue for me. I tried out `jellyfin/jellyfin:20201030.5-unstable` just now and it reduced the library scan time from ten hours to three minutes. The performance of all the other affected features is back to 10.5.x levels as well. 👍 

@barronpm Thanks for the quick fix!
