### ISSUE TITLE
Not casting to chromecast 10.6.4

### ISSUE THREAD

**Issue by Marthaarman** [jellyfin/jellyfin#4365]
**Describe the bug**
When hitting the cast button, it acts like if nothing happened. I already tried the suggestions from
https://github.com/jellyfin/jellyfin/issues/3852
But unfortunately this is not working. Maybe i'm not able to find the correct LocalAddress parameter values though, any suggestions?

location /System/Info/Public {
    add_header Content-Type "application/json; charset=utf8";
    return 200 '{"LocalAddress": "https://cast.mysite.com","ServerName": "cast.mysite.com","Version": "10.6.4","ProductName": "raspberrypi","OperatingSystem": "Linux","Id": "11a001fd36a449a69f5005883c96379f"}';
}

**System (please complete the following information):**
 - OS: Raspbian
 - Clients: Firefox, ios app
 - Browser: Firefox
 - Jellyfin Version: 10.6.4
 - Installed Plugins: none
 - Reverse Proxy: nginx
 - Base URL: none
 - Networking: Host?
 - Storage: local

**To Reproduce**

go to web platform
click on chromecast button
Click the device you'd like to stream to
Nothing happens

**Expected behavior**
Should become a blue icon and the chromecast should respond

**Comment by jeroen7s** [comment]
Does Firefox even work with Chromecast? I thought Firefox never supported it?

**Comment by Marthaarman** [comment]
> 
> 
> Does Firefox even work with Chromecast? I thought Firefox never supported it?

I'm not sure it is about firefox itself. Anyhow, it is neither working on other devices / apps (iphone & android jellyfin app)

**Comment by jeroen7s** [comment]
ah oke,
if it was just Firefox, it would probably be normal, since Firefox on desktop doesn't have Chromecast support 
(only Android does, because it can integrate with the native Android Libraries for Chromecast)

**Comment by hawken93** [comment]
@Marthaarman It looks a lot like you have the issue that got fixed.
The workaround should have worked fine I think. The client side fix has been merged to master.

Could you try either one of them again? One possibility is that you got a cached result while testing so that your workaround had not applied yet.
Another possibility is that maybe chromecast doesn't like your ssl certificate? But if it's a valid letsencrypt certificate, this can be ruled out.
