### ISSUE TITLE
Artwork from TheTVDB isn't downloading

### ISSUE THREAD

**Issue by Panja0** [jellyfin/jellyfin#4368]
**Describe the bug**
Download artwork (poster, backgrounds etc) is not working for TheTVDB.

**System (please complete the following information):**
 - OS: Linux (Synology)
 - Virtualization: Docker
 - Jellyfin Version: 10.6.4
 - Installed Plugins: None
 - Reverse Proxy: NGINX
 - Base URL: https://jellyfin.mydomain.com
 - Networking: Bridge (also tried macvlan)
 - Storage: local

**To Reproduce**
1. Add TV Serie library
2. Do a scan

**Expected behavior**
Should download poster art, season art etc from TheTVDB

**Logs**
https://pastebin.com/2qR77W15

**Comment by Panja0** [comment]
Any one that can help me out!

**Comment by crobibero** [comment]
I quickly looked at the logfile and the exceptions that you're having are tvdb website errors.

**Comment by Panja0** [comment]
Thanks for checking and yes I noticed the to.
But what I don’t get is why my Plex server is scraping correctly from TheTVDB and Jellyfin is not. If there was a problem with my connection to TheTVDB that should be for both than...

**Comment by cvium** [comment]
Plex has their own cache.

**Comment by Panja0** [comment]
I’ve tried doing a scan over VPN as well. Same problem.

**Comment by Panja0** [comment]
When I do an "indentify" serie and fill in the TheTVDB id I get 2 results, one for TheMoviesDB and one for TheTVDB which does not have a picture. See attached screenshot.

![Screenshot - 2020-10-27 at 09 05 57](https://user-images.githubusercontent.com/12939350/97273508-c2786180-1833-11eb-8422-5e8e89148b6a.png)

**Comment by Panja0** [comment]
Any one have a clue what is going on here?

**Comment by Panja0** [comment]
I guess it's time to go back to Plex than. :-(
Thanks all for the time and help! Cheers

**Comment by cvium** [comment]
Looks like images aren't being attached to the search result in the tvdb plugin.

**Comment by Panja0** [comment]
Ok. Thanks! Hopefully it will be fixed soon.

**Comment by Panja0** [comment]
Any news on this?

**Comment by Panja0** [comment]
@cvium 
Do you have any insight when it will be fixed?
I still want to change over to Jellyfin from Plex but this is holding me back.

**Comment by cvium** [comment]
Next version, 10.7. No release date yet

**Comment by Panja0** [comment]
Ok, thanks!
No ETA, I get it. But is this days, weeks or months?
Just want to adjust my strategy with this info

**Comment by CutterXYZ** [comment]
Same issue. Is there a way to install the new plugin on 10.6.4 in the meantime ?

**Comment by Panja0** [comment]
A temp fix would be great!

**Comment by Panja0** [comment]
@cvium 
I noticed this bug has been closed, why is that?
As far as I can tell it's not fixed yet.

**Comment by oddstr13** [comment]
Fixed by https://github.com/jellyfin/jellyfin-plugin-tvdb/pull/4

The fix will be available with the release of 10.7, which will hopefully be out before Christmas.

Your current temp fix is to manually grab the wanted pictures and upload them via the «Edit images» dialog.

Future fixes to the TVDB provider can be made independent of the server release cycle, courtesy of it now being split out to a separate plugin.

---

Closing this issue as solved.

**Comment by CustomerJFK** [comment]
Hi 
same issue!
But I can't install the version 1.0.0.0 or 2.0.0.0!!!
The system shows me I have already installed the version 10.6.4.0!?!
Where is the problem?????

**Comment by crobibero** [comment]
> Hi
> same issue!
> But I can't install the version 1.0.0.0 or 2.0.0.0!!!
> The system shows me I have already installed the version 10.6.4.0!?!
> Where is the problem?????

As the comment directly before you says, the fix will be available with the plugin in 10.7.

**Comment by CustomerJFK** [comment]
And when will it be available?
What must I do??!!!

**Comment by cvium** [comment]
> What must I do??!!!

Panic!!!! 😱
