### ISSUE TITLE
DLNA is Using HTTPS

### ISSUE THREAD

**Issue by SonnTakuu** [jellyfin/jellyfin#4370]
**Describe the bug**

**System (please complete the following information):**
 - OS: Synology DSM
 - Virtualization: Docker
 - Clients: [kodi]
 - Jellyfin Version: 10.6.4
 - Playback: Direct Play
 - Networking: HOST
 - Storage: local

**To Reproduce**

1. Go to 'Network' and set HTTPS port on 10069; and set the SSL Cert.
2. Click on 'my DLNA Device' to play a video
3. See error

**Logs**
15:58:54.520 T:3420   DEBUG: CFileCache::Open - opening <videos/0facdc23-211e-c1dd-52cd-b6f4ad67efca/stream.mov> using cache
15:58:54.520 T:3420   DEBUG: CurlFile::Open(0x5ad6e70) https://10.0.0.6:10069/videos/0facdc23-211e-c1dd-52cd-b6f4ad67efca/stream.mov?DeviceId=uuid:a1c962ac-5f48-1985-44ce-b847aa510abd&MediaSourceId=0facdc23211ec1dd52cdb6f4ad67efca&Static=true&AudioStreamIndex=1&Tag=e8bd3b84ed0837ed417401067159d132&dlnaheaders=true
15:58:54.535 T:1364   DEBUG: ------ Window Init (DialogBusy.xml) ------
15:58:54.645 T:3420   ERROR: CCurlFile::FillBuffer - Failed: Peer certificate cannot be authenticated with given CA certificates(60)
15:58:54.645 T:3420   ERROR: CCurlFile::Open failed with code 0 for https://10.0.0.6:10069/videos/0facdc23-211e-c1dd-52cd-b6f4ad67efca/stream.mov?DeviceId=uuid:a1c962ac-5f48-1985-44ce-b847aa510abd&MediaSourceId=0facdc23211ec1dd52cdb6f4ad67efca&Static=true&AudioStreamIndex=1&Tag=e8bd3b84ed0837ed417401067159d132&dlnaheaders=true:
15:58:54.645 T:3420   ERROR: XFILE::CFileCache::Open - failed to open source <https://10.0.0.6:10069/videos/0facdc23-211e-c1dd-52cd-b6f4ad67efca/stream.mov?DeviceId=uuid:a1c962ac-5f48-1985-44ce-b847aa510abd&MediaSourceId=0facdc23211ec1dd52cdb6f4ad67efca&Static=true&AudioStreamIndex=1&Tag=e8bd3b84ed0837ed417401067159d132&dlnaheaders=true>
15:58:54.645 T:3420   ERROR: CVideoPlayer::OpenInputStream - error opening [https://10.0.0.6:10069/videos/0facdc23-211e-c1dd-52cd-b6f4ad67efca/stream.mov?DeviceId=uuid:a1c962ac-5f48-1985-44ce-b847aa510abd&MediaSourceId=0facdc23211ec1dd52cdb6f4ad67efca&Static=true&AudioStreamIndex=1&Tag=e8bd3b84ed0837ed417401067159d132&dlnaheaders=true]
15:58:54.645 T:3420  NOTICE: CVideoPlayer::OnExit()

**Additional context**
my SSL Cert only for my domain and not for the LAN ip adress, so it cannot be authenticated with given CA certificates. How to resolve that to use the http port?

**Comment by PrplHaz4** [comment]
There are considerable changes to DLNA and network configurability coming up in 10.7 (see #3994) - which should help.

One of the things we found was that some DLNA clients don't resolve hostnames and some don't support HTTPS - do you know if that's the case for your client? 

So, this issue will evolve to either:
- DLNA PlayTo uses server IP not domain when Jellyfin is served over HTTPS
- Force DLNA PlayTo Location to use HTTP and IP Address

For some hacks/quick fixes, you may be able to look at some of the Chromecast threads to see if rewriting LocalAddress also changes DLNA PlayTo location...

**Comment by BaronGreenback** [comment]
Notes to self: Kestrel always listens on port 80 regardless of https status.

**Comment by BaronGreenback** [comment]
DLNA is v1.1 and therefore does not support playback over https; a warning message is now logged if the dlna server is enabled and only https is enabled. Any request from https will be converted to a http

Also be aware that there are also some general dlna issues around domain names being included in the urls. We support it, some dlna devices don't.
