### ISSUE TITLE
Jellyfin Nightly Login

### ISSUE THREAD

**Issue by hotio** [jellyfin/jellyfin#4372]
Who knows the secret to get rid of/get passed the login screen on a new install with Jellyfin nightlies?

![screenshot](https://user-images.githubusercontent.com/26902309/97188377-bb097780-17a3-11eb-9072-52a89a5b71fe.png)

**Comment by crobibero** [comment]
https://github.com/jellyfin/jellyfin-web/pull/1918
To manually start the wizard navigate to `{host}/web/index.html#!/wizardstart.html`

**Comment by barrystaes** [comment]
So this bug has not been fixed apparently.

Still seeing this problem in 2024 .. after doing new Jellyfin installations. 

I suggest the broken login page includes the correct link, so people can click. But ideally it just redirects of course.

**Comment by felix920506** [comment]
@barrystaes please open a new report instead of attempting to revive an old one
