### ISSUE TITLE
No Genre's Displaying

### ISSUE THREAD

**Issue by mbluett88** [jellyfin/jellyfin#4373]
Jellyfin 10.6.4 installed in Docker 19.03.13, build 4484c46d9d on Linux Mint 20.

No Genres display after clicking on the Genres tab.
 (That is:  Suggestions / Albums / Album Artists / Artists / Playlists, ... Genres)

Clicking on a specific song Genres are displayed.

This is a newly installed Jellyfin, as of yesterday. 

Metadata was scanned from MusicBrainz.

**Comment by mbluett88** [comment]
Interestingly today I see the genres are now being displayed.

Have no idea what happened. In any case, there is some sort of a problem which caused this significant delay the the Genre page being populated. It should not have to take an entire day or so to populate this page especially when the other pages were populated without problem.

**Comment by Extarys** [comment]
What I think happened here is the Genres table might be created after the main scan is complete.
Maybe you clicked the Genres tab while the server was still scanning and processing data.
