### ISSUE TITLE
First install does not launch initial setup wizard

### ISSUE THREAD

**Issue by wwwutz** [jellyfin/jellyfin#4374]
**Describe the bug**

When building jellyfin/jellyfin-web  / master  from scratch, running as user with no previous config/data I get redirected to `web/index.html#!/login.html` asking for a username ( which obviously does not exist yet ).

**System :**
 - OS: ubuntu 20.04.1 LTS (Focal Fossa)
 - Clients: Browser
 - Browser: Brave Version 1.15.75 Chromium: 86.0.4240.99 (Official Build) (64-bit)
 - Jellyfin Version: 10.7.0.0 / master a814d01f8c6edab930877031cd9e323f9ceda9d0 - Sun Oct 25 16:56:24 2020 -0400
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: none
 - Networking: host / localhost
 - Storage: local

**To Reproduce**
1. build latest jellyfin / jellyfin-web master
1. start up with empty config/data: `./jellyfin --datadir /tmp/jfdata --cachedir /tmp/jfcache --configdir /tmp/jfconfig --logdir /tmp
1. point browser at 127.0.0.1:8096
1. get redirect to login page URL `http://127.0.0.1:8096/web/index.html#!/login.html` asking for username/password

**Expected behavior**
On first install the initial setup wizard should start up

The last 'good' commit I found bisecting was e33824d28667df0344420d42032fbb01e9f8f659 but I had a ton of skips. At least the initial setup wizard pops up somehow. The redirected URL is `http://127.0.0.1:8096/web/index.html?start=wizard#!/wizardstart.html?start=wizard` which is fine.  It stalls anyway, maybe because of latest jellyfin-web. So bisecting only gave a hint.

**Logs**
the log line on console when opening 
```
[21:49:48] [DBG] [5] Jellyfin.Server.Middleware.BaseUrlRedirectionMiddleware: Normalizing an URL at /
```
but that might not be related

Complete log:
[log_20201026.log](https://github.com/jellyfin/jellyfin/files/5441503/log_20201026.log)

**Additional context**
I'm testing on ubuntu as user `jellyfin` from source/git. no packages installed whatsoever.

I'm building/testing with this script ( use at your own risk )
[mybuild-debug.sh.txt](https://github.com/jellyfin/jellyfin/files/5441508/mybuild-debug.sh.txt)
`rm -rf ~/jellytest; ./mybuild-debug.sh.txt`

**Comment by crobibero** [comment]
This is not a server bug, and should be fixed by this pr
https://github.com/jellyfin/jellyfin-web/pull/1918
