### ISSUE TITLE
Missing support for Ubuntu 20.10 Groovy

### ISSUE THREAD

**Issue by INeDiA** [jellyfin/jellyfin#4379]
**Describe the bug**
Repo for groovy is missing, can't install.
Using repo for 20.04 does not solve the issue (missing dependencies for jellyfin-ffmpeg).

**System (please complete the following information):**
 - OS: Ubuntu 20.10

**To Reproduce**
echo "deb [arch=$( dpkg --print-architecture )] https://repo.jellyfin.org/$( awk -F'=' '/^ID=/{ print $NF }' /etc/os-release ) $( awk -F'=' '/^VERSION_CODENAME=/{ print $NF }' /etc/os-release ) main" | sudo tee /etc/apt/sources.list.d/jellyfin.list

output: deb [arch=amd64] https://repo.jellyfin.org/ubuntu groovy main

sudo apt update
output: E: The repository 'https://repo.jellyfin.org/ubuntu groovy Release' does not have a Release file.

**Comment by nyanmisaka** [comment]
jellyfin-ffmpeg requires a rebuild with this pr. https://github.com/jellyfin/jellyfin-ffmpeg/pull/53

**Comment by rr222cy** [comment]
> 
> 
> jellyfin-ffmpeg requires a rebuild with this pr. [jellyfin/jellyfin-ffmpeg#53](https://github.com/jellyfin/jellyfin-ffmpeg/pull/53)

Any updates regarding this or workarounds in the meantime?

**Comment by joshuaboniface** [comment]
Try using the latest LTS version (20.04) of the repo instead. If that doesn't work, the rebuild will be coming in the next day or two.

**Comment by rr222cy** [comment]
> 
> 
> Try using the latest LTS version (20.04) of the repo instead. If that doesn't work, the rebuild will be coming in the next day or two.

Thank you for the quick reply! I'll just wait for the rebuild then 👍

**Comment by danielsbrewer** [comment]
I'm having the same issue on as raspberry pi 3. Ubuntu server 20.10 is the default install. Changing the repro to focal produces an error in jellyfin-ffmpeg. Any updates. Thanks.

**Comment by f1yankees** [comment]
Same issue here, does not work for 20.10.

While you can force apt to work by replacing "groovy" with "focal", it still fails at jellyfin-ffmpeg:
` jellyfin-ffmpeg : Depends: libx264-155 but it is not installable
                   Depends: libx265-179 (>= 3.2) but it is not installable`

So this is not supported on Ubuntu 20.10 at all at the moment.

**Comment by nyanmisaka** [comment]
> While you can force apt to work by replacing "groovy" with "focal" in the Jellyfin.list source file, it still will fail when installing jellyfin-ffmpeg:
> 
> > jellyfin-ffmpeg : Depends: libx264-155 but it is not installable
> > Depends: libx265-179 (>= 3.2) but it is not installable

Here are some jellyfin-ffmpeg packages for groovy.
https://github.com/jellyfin/jellyfin-ffmpeg/pull/54#issuecomment-737396700

**Comment by f1yankees** [comment]
> > While you can force apt to work by replacing "groovy" with "focal" in the Jellyfin.list source file, it still will fail when installing jellyfin-ffmpeg:
> > > jellyfin-ffmpeg : Depends: libx264-155 but it is not installable
> > > Depends: libx265-179 (>= 3.2) but it is not installable
> 
> Here are some jellyfin-ffmpeg packages for groovy.
> [jellyfin/jellyfin-ffmpeg#54 (comment)](https://github.com/jellyfin/jellyfin-ffmpeg/pull/54#issuecomment-737396700)

Thank you, a combination of installing the .deb jellyfin-ffmpeg package locally and using the focal repo for the rest worked.

**Comment by joshuaboniface** [comment]
Groovy should be coming along with 10.7.0-rc4 (and 10.7.0 when it drops) - we just had to add it to the `reprepro` repository, and the new ffmpeg will get added there as well. For now the manual `.deb` method is the preferred workaround.
