### ISSUE TITLE
Error when playing video: This client isn't compatible with the media and the server isn't sending a compatible media format

### ISSUE THREAD

**Issue by Nightlychaos** [jellyfin/jellyfin#4382]
**Describe the bug**
Multiple video files won't play. Mostly with the MKV file format, HEVC as the video codec and AAC as the audio codec

**System (please complete the following information):**
 - OS: Debian
 - Virtualization: None
 - Clients: Browser
 - Browser: Chrome, firefox, and the playstation 4 browser
 - Jellyfin Version: 10.6.4
 - Playback: Transcoding and directplay
 - Installed Plugins: Only anime apart from preinstalled
 - Reverse Proxy: none
 - Base URL: 
 - Networking: Host
 - Storage: local

**To Reproduce**
1. Go to a movie/tv show that uses HEVC as the video codec and AAC as the audio codec on the web client
2. Start it
3. See error 'This client isn't compatible with the media and the server isn't sending a compatible media format.'

**Expected behavior**
The file is supposed to play normally

**Logs**
[hevc_cuvid @ 0x5598bd8d0440] Cannot load libnvcuvid.so.1
[hevc_cuvid @ 0x5598bd8d0440] Failed loading nvcuvid.
Error while opening decoder for input stream #0:0 : Operation not permitted

**Screenshots**

**Additional context**
ONLY happens when using NVENC

**Comment by crobibero** [comment]
Are other codecs able to transcode with NVENC?

**Comment by nyanmisaka** [comment]
Your card may not support HEVC or the driver is not properly installed.

**Comment by NightMachinary** [comment]
[**@Nyanmisaka**](https://github.com/nyanmisaka) commented on [Oct 28, 2020, 6:15 AM GMT+3:30](https://github.com/jellyfin/jellyfin/issues/4382#issuecomment-717659721 "2020-10-28T02:45:04Z - Replied by Github Reply Comments"):
> Your card may not support HEVC or the driver is not properly installed.

Can't it just use software decoding?

**Comment by abhidwiv** [comment]
same problem here

**Comment by cvium** [comment]
Please don't post in old closed issues. Create a new one...

**Comment by marine1988** [comment]
i have same probleonly when using hw decoding
