### ISSUE TITLE
TV Show and Movie Title sorting is weird.

### ISSUE THREAD

**Issue by Protektor-Desura** [jellyfin/jellyfin#4386]
Jellyfin isn't sorting TV shows and movies properly when there are periods and quotes in the beginning of the title.

The "Hentai" Prince and the Stony Cat. It's the second show with .hack being the first show.
"A.I.C.O. -Incarnation-" is in with the I's.
"ēlDLIVE" is in the E's which seems expected.
"A.I. Artificial Intelligence" and "The A.I. Race" and "A.I. Rising" in movies are in the I's.
"Æon Flux" is at the end of TV shows which I would expect.

**Comment by vincenavarro** [comment]
(Responding to avoid the wrath of stale bot.) 

I can confirm as of April 5th, 2021 I am experiencing this bug with titles starting with A.I. Would love to submit a pull request but I don't speak C# 😞
