### ISSUE TITLE
Error: Failing to Load Custom PFX File 

### ISSUE THREAD

**Issue by EchoApeiron** [jellyfin/jellyfin#4390]
**Describe the bug**
When setting up native SSL in Jellyfin with a certificate registered from my registrar it fails to load the file. Using the certificate files in my nginx reverse proxy they have no issues at all working. Since they are in pem format I used the following openssl command to create the new certificate file: 

`openssl pkcs12 -export -out custom.pfx -inkey server.key -in server.pem`

I even added the certificate chain and it still failed to load. Tried with and without a password on the certificate file and it failed. See logs section for the error thrown when trying to load the certificate file. Verified with netstat as well that the port never opens: 

```
root@hinata:/home/dpezzimenti@digiecho.xyz# netstat -tulpn | grep jellyfin
tcp6       0      0 :::8096                 :::*                    LISTEN      41106/jellyfin
udp        0      0 10.0.0.245:45909        0.0.0.0:*                           41106/jellyfin
udp        0      0 0.0.0.0:7359            0.0.0.0:*                           41106/jellyfin
udp        0      0 127.0.0.1:49076         0.0.0.0:*                           41106/jellyfin
udp        0      0 10.0.0.245:32784        0.0.0.0:*                           41106/jellyfin
udp        0      0 127.0.0.1:58107         0.0.0.0:*                           41106/jellyfin
udp        0      0 0.0.0.0:34352           0.0.0.0:*                           41106/jellyfin
udp        0      0 10.0.0.245:59111        0.0.0.0:*                           41106/jellyfin
udp        0      0 0.0.0.0:1900            0.0.0.0:*                           41106/jellyfin
udp        0      0 127.0.0.1:42954         0.0.0.0:*                           41106/jellyfin

```

**System (please complete the following information):**
 - OS: Ubuntu
 - Virtualization: Baremetal - No Virtualization
 - Clients: Chrome, PS4, Android
 - Browser: 86.0.4240.111 (Official Build) (64-bit)
 - Jellyfin Version: Jellyfin.Server 10.6.4.0
 - Playback: N/A
 - Installed Plugins: LDAP-Authentication
 - Reverse Proxy: nginx
 - Base URL: none
 - Networking: NAT
 - Storage: local

**To Reproduce**

1. Gather certificates from registrar
2. Issue openssl command to create PKCS #12 formatted certificate
    - `openssl pkcs12 -export -out custom.pfx -inkey server.key -in server.pem`
    - Set password for increased security
3. Keep in location Jellyfin can read the file 
4. Point Jellyfin to the custom cert in admin dashboard, provide password
5. Enable HTTPS in Jellyfin Console
6. Save settings, restart services 
7. Validate SSL import with netstat command and viewing logs 
    - `netstat -tulpn | grep jellyfin`
    - `tail -n 100 /var/log/jellyfin/jellyfin<latest_date>.log`

**Expected behavior**

SSL to enable successfully or to provide an error related to issues with the certificate. 

**Logs**
```
[2020-10-29 12:26:35.905 +00:00] [ERR] Error loading cert from "/etc/nginx/ssl/home/custom.pfx"
Interop+Crypto+OpenSslCryptographicException: error:2006D002:BIO routines:BIO_new_file:system lib
   at Interop.Crypto.CheckValidOpenSslHandle(SafeHandle handle)
   at Internal.Cryptography.Pal.OpenSslX509CertificateReader.FromFile(String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(String fileName, String password)
   at Emby.Server.Implementations.ApplicationHost.GetCertificate(CertificateInfo info)

```

**Screenshots**

**Additional context**

**Comment by cvium** [comment]
Did you check permissions? https://github.com/dotnet/runtime/issues/24051

**Comment by EchoApeiron** [comment]
The permissions have read across user, group, global: 

```
root@hinata:/etc/nginx/ssl/home# ls -la
total 52
drwxr-xr-x 2 root root 4096 Oct 29 12:23 .
drwxr-xr-x 3 root root 4096 Oct 16 08:33 ..
-rw-r--r-- 1 root root 4135 Oct 16 08:50 chain.pem
-rw-r--r-- 1 root root 6149 Oct 29 12:26 custom.pfx
-rw-r--r-- 1 root root 1679 Oct 16 07:56 server.key
-rw-r--r-- 1 root root 2065 Oct 16 08:50 server.pem
```

**Comment by peterbaumert** [comment]
Same here, are there any news?

**Comment by cvium** [comment]
The cert needs execute perms

**Comment by h0wardch3ng** [comment]
pfx cert is shit.
