### ISSUE TITLE
Dependencies for OpenCL required for Hardware Tone Mapping

### ISSUE THREAD

**Issue by antsh415** [jellyfin/jellyfin#4396]
I am trying to work with the linuxserver.io team to include the needed dependencies to enable the hardware based tone mapping in Jellyfin.

May I request some help defining the needed OpenCL drivers and dependencies that are needed to enable this?

**Comment by nyanmisaka** [comment]
See https://github.com/jellyfin/jellyfin/pull/3442#issuecomment-700951920

For Nvidia: `nvidia-opencl-icd` and their closed source driver on debian/ubuntu.

For AMD: [amdgpu-pro](https://amdgpu-install.readthedocs.io/en/latest/install-installing.html) closed driver with OpenCL installed.
`./amdgpu-pro-install -y --opencl=pal,legacy`
