### ISSUE TITLE
The API does not seem to authenticate on 10.7 (Error 401)

### ISSUE THREAD

**Issue by PJkeeh** [jellyfin/jellyfin#4399]
**System (please complete the following information):**
 - OS: Ubuntu 20.04
 - Virtualization: docker(-compose)
 - Clients: PyEmby, Firefox, PostMan, curl
 - Browser: Firefox 83.0.1
 - Jellyfin Version: 10.7
 - Reverse Proxy: Both no proxy and Nginx fail
 - Base URL: Both no base url and /jellyfin fail

Steps: 
Make an API key
Use it to go to http://192.168.1.2:8096/jellyfin/Sessions?api_key=key_here
Expected: Get a Json File
Got: Error 401

Doing the exact same on 10.6.4 does work.

**Comment by crobibero** [comment]
Fixed by https://github.com/jellyfin/jellyfin/pull/4330
