### ISSUE TITLE
Next Up broken (regression?)

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [jellyfin/jellyfin#4418]
**Describe the bug**
The first episode of every TV series shows up in my Up Next section. I cannot fix this by marking and unmarking the affected episode as watched.

**System (please complete the following information):**
 - OS: Void Linux
 - Clients: Web
 - Browser: Edgium Version 86.0.622.58
 - Jellyfin Version: 10.6.4

**To Reproduce**
1. Scan a new show in

**Expected behavior**
For Next Up to comprise of shows that have 1 or more episode already watched.

**Logs**
n/a

**Screenshots**
n/a

**Additional context**
Probably a regression like #3145

**Comment by cvium** [comment]
Looks like it's intentional.
![image](https://user-images.githubusercontent.com/675118/98086546-398aa700-1e7f-11eb-897e-3a2e5532b586.png)

**Comment by eltiel** [comment]
> **Describe the bug**
> The first episode of every TV series shows up in my Up Next section. I cannot fix this by marking and unmarking the affected episode as watched.

Does marking the whole TV series as unplayed (not the episode) solve the problem?

**Comment by ThatNerdyPikachu** [comment]
@cvium was correct.
