### ISSUE TITLE
DLNA is always enabled with no access control

### ISSUE THREAD

**Issue by 9p6** [jellyfin/jellyfin#4431]
**Describe the bug**
It's not possible to disable DLNA access. The value of option `Enable DLNA server` is ignored.

Limiting access by assigning to DLNA a user with limited library access is also ineffective/broken as it seems to block access to directory listings and not the actual content. E.g. I was able to save a bookmark to a library subdir in VLC Local Network browser before switching DLNA `Default user` and then still being able to access content after the switch.

I also think it would be suitable to ask (or at least inform) the user during setup wizard if he wants to enable DLNA at all. The current default is to allow unrestricted access to whole library for entire local network.

**System (please complete the following information):**
 - OS: Ubuntu 20.04
 - Virtualization: none
 - Clients: VLC on Android, curl
 - Jellyfin Version: 10.6.4
 - Reverse Proxy: none
 - Base URL: none
 - Networking: local
 - Storage: local

**To Reproduce**
1. Go to `Devices` -> `DLNA` 
2. Uncheck `Enable DLNA server`
3. Save and restart jellyfin
4. DLNA access is still possible

**Expected behavior**
DLNA access not possible

**Additional context**
All streaming endpoints seem to be unprotected and all is required is knowledge of UUID
```
curl -o out http://192.168.1.14:8096/videos/bc1bb5fa6f7a6eb3019354699f90214e/stream.mov
```
This sucks. Why even bother with setting up users and passwords?

**Comment by BaronGreenback** [comment]
Fixed in new network backend. (#3994) 

The cause is that the dlna class is always instantiated regardless of this settings. Similarly the api will always respond.

**Comment by 9p6** [comment]
Thanks! I will test once this PR lands.

**Comment by 9p6** [comment]
@BaronGreenback Hey, I can see you divided your original PR into multiple smaller ones. Can you point me to the one relevant to this issue?

**Comment by BaronGreenback** [comment]
Afraid the dlna changes didn't make 10.7 as it was decided that they would be better as plugins - something that I'm currently working upon. (three plugins consisting of - dlna server, dlna playto and upnp)

They are planned to be reviewed as soon as 10.7 is released.

**Comment by 9p6** [comment]
Oh cool so the DLNA stuff is going to be entirely optional that's good news.

Can't this bug be fixed for 10.7 though I mean the option `Enable DLNA server` must have worked properly at some point in the past?

**Comment by BaronGreenback** [comment]
Just submitted https://github.com/jellyfin/jellyfin/pull/4821#issuecomment-748376756 to get some dlna disabling done. 

Check 17.0 RC2 and let us know if it's fixed.

**Comment by 9p6** [comment]
Will do. Thanks for the fix!

**Comment by 9p6** [comment]
I just tested 10.7 RC2: DLNA access is now blocked immediately after toggling the option. The following message appears in server log
> [22:34:30] [INF] [238] Emby.Dlna.Main.DlnaEntryPoint: Disposing SsdpDevicePublisher

The access is still possible using direct stream URL `/videos/<uuid>/stream.mkv`. I will file another bug for this.
