### ISSUE TITLE
Server is advertising Remote IP

### ISSUE THREAD

**Issue by Anan5a** [jellyfin/jellyfin#4442]
**Describe the bug**
Right now anyone can see my server origin IP like this
![Screenshot_20201108_200935](https://user-images.githubusercontent.com/16373480/98467407-469cf280-21ff-11eb-801e-8f6abcac321a.png)
by requesting ```http://example.com/system/info/public```
This is bad for security,  the server should advertise ```127.0.0.1``` instead

**System (please complete the following information):**
 - OS:  Debian
 - Virtualization: -
 - Clients: Browser
 - Browser: Firefox
 - Jellyfin Version: 10.6.4
 - Playback: -
 - Installed Plugins: -
 - Reverse Proxy: nginx
 - Base URL: -
 - Networking: Host
 - Storage: local

**To Reproduce**

Any standard installation should yield same result!

**Expected behavior**

**Logs**

**Screenshots**

**Additional context**

How can I change so that it only reports 127.0.0.1 ?
If I disable remote access to the server, the reverse proxy does not work as well!

**Comment by BaronGreenback** [comment]
Could you explain more, as I'm not exactly sure what you're getting at? If i know the url to the server - I can just do a lookup to get your IP.

**Comment by Anan5a** [comment]
@BaronGreenback  no you cannot if the server is behind a reverse proxy, like ```cloudflare```

BTW closing this, because updating bind address in Dashboard>Network solved this leak, but jellyfin should not expose the IP by default

**Comment by Anan5a** [comment]
Reopening, Since version `10.7.6 ` it reappeared 
ananta@sayem:~$ curl https://ms.example.com/system/info/public
{"LocalAddress":"http://xx.xx.xx.233:8096","ServerName":"ms.example.com","Version":"10.7.6","ProductName":"Jellyfin Server","OperatingSystem":"Linux","Id":"32ef5c80303b468b8e4059b93749b771","StartupWizardCompleted":true}
ananta@sayem:~$

**Comment by genofire** [comment]
Same Problem with an caddy proxy -> this LocalAddress is not accessible ...
