### ISSUE TITLE
Crashes and constant stuttering on Raspberry Pi 3B with Kodi plugin

### ISSUE THREAD

**Issue by random-human-being** [jellyfin/jellyfin#4451]
My setup is a Raspberry Pi 3 with Libreelec 9.2.4, Kodi 18.8.0. I store my films/series on an external HDD with its own power supply. Jellyfin server 10.6.4 is installed via the Docker addon; the image is from jellyfin/jellyfin. It syncs to Kodi on the same machine via the plugin; it's currently working in native mode (switching to plugin mode massively increase load times before starting a video, but everything else is identical as far as I can tell).

The setup was working perfectly before I installed Docker and Jellyfin, but has since been stuttering and occasionally freezing. I initially thought this was due to some issue with DLNA, as occasionally these issues happened while my LG TV was scanning Jellyfin's DLNA share. However after disabling the latter and disconnecting the TV from the network it seems nothing has changed. I still get stuttering and I got a crash less than an hour ago.

No warning (like the lightning bolt or the red thermometer) are shown by the Raspberry Pi, at all.

I've tried changing all possible settings in both Kodi and Jellyfin (plugin and server), but it makes no difference.

Kodi log: https://pastebin.com/ULKw4e0X
Jellyfin log: https://pastebin.com/BpSfzC2G

Here's what I was watching when it froze the last time: https://pastebin.com/TQKUstz0
As you can see it's a pretty standard video. The issue I'm having seems to be independent of bitrate (remuxes and high quality encodes stutter/freeze just as much as WEB-DLs), although it looks like scenes with a lot of sudden motion are more affected.
The freeze on the video above was around the 40 minutes mark, but the video is perfectly fine and will not freeze if I watch it again. The same thing happened for previous freezes.

They both stop just around the moment the whole system crashed. Actually, some of the lines in the Jellyfin log might go a bit further than it, but if I tried to access anything on the Pi in any way (SSH, Jellyfin Android client, Transmission web interface, Kore remote) it just kept trying to connect forever. The TV merely showed a static image of the frozen frame.

I had already posted about the issue here: https://www.reddit.com/r/jellyfin/comments/jmmvfr/stuttering_with_kodi_native_mode_files_on_same/
and here: https://forum.kodi.tv/showthread.php?tid=358223&pid=2987568#pid2987568
I'm adding these last two links in case I might have forgotten some details.

I'm honestly at my wits' end. I've been struggling with this for weeks, and I have no idea what else could I possibly do. I spend a lot of time watching films, and that has been a nightmare ever since I've installed Jellyfin.

**Comment by leaderdog** [comment]
I posted on your reddit thread.

again, I'm not using pi, but windows 10 server and windows 10 with kodi to watch on htpc.  I changed every piece of hardware in my htpc except the ram, did memtest for that, with no improvement.  Continual stutters, and occasionally the audio would turn into a digital mess.

What I did to finally fix the issue is download the latest K-lite codec pack.  Kodi apparently is missing or doesn't have an updated codec so it struggles with some files.  Once I put on the codec pack all shows/movies play smooth and I have no stuttering anymore.  I tested with 1080p raised by wolves which was the worst offender of the bunch for me and it plays great now.

Maybe a direction you can look into.

**Comment by random-human-being** [comment]
I think I might have fixed the stuttering, at least to some extent, by lowering the number of threads the Jellyfin plugin can use to sync metadata. I'm not sure it has fixed my crashes, but so far it seems promising. I'll add more details and updates as I test this further.
