### ISSUE TITLE
NVENC on Unraid not working

### ISSUE THREAD

**Issue by ich777** [jellyfin/jellyfin#4453]
NVENC is not working with the template on Unraid

**System (please complete the following information):**
 - OS: Unraid 6.9.0beta30 (Custom Slackware)
 - Virtualization: Docker
 - Clients: Firefox, Android
 - Browser: Firefox 78.4.0esr, Chrome
 - Jellyfin Version: jellyfin/jellyfin:latest (from Dockerhub
 - Playback: Transcode
 - Installed Plugins: noting
 - Reverse Proxy: LAN only
 - Base URL: LAN only '/'
 - Networking: Bridge
 - Storage: local

**To Reproduce**
1. Install Jellyfin through the template provided in Unraid and add your GPU UUID as value to the variable 'NVIDIA_VISIBLE_DEVICES'
2. Setup Jellyfin
3. Enable NVENC video transcode in the options
4. Play back the video file and change the bitrate to something lower than the file
5. Error appers that the client doesn't support the video format
(if you disable NVENC and do transcoding over the CPU it works just fine)

**Expected behavior**
Transcoding is working

**Additional context**
Just investigating why this isn't working and wanted to let you know.
Also tried to add the variable 'NVIDIA_DRIVER_CAPABILITIES' with the value 'all' but that also doesn't work, tried multiple files with your container and also Linuxserver.io container, on your's the playback doesn't work on Linuxserver.io container the playback works just fine.

**Comment by crobibero** [comment]
Have you installed https://github.com/NVIDIA/nvidia-docker?

**Comment by ich777** [comment]
@crobibero yes I have installed all dependencies and also the Nvidia driver to run applications so that I can run hardware accelerated applications inside Docker containers.

As I wrote above, the Linuxserver.io container from Jellyfin works just fine, only the official container from Jellyfin doesn't work wirth hardware transcoding.

**Comment by ich777** [comment]
@crobibero if you need any further help or someone to test something feel free to ask ;)
No stranger to developing Docker containers...

**Comment by crobibero** [comment]
Please attach an ffmpeg log of a NVENC transcode not working. As far as I know it has worked in our container for quite some time.

**Comment by ich777** [comment]
@crobibero found the problem, there was a variable missing (NVIDIA_DRIVER_CAPABILITIES) from the template:
https://github.com/djaydev/docker-virt-manager/blob/master/UnRaid/template/jellyfin.xml

Already created a pull request and should be fixed hopefully soon ;)
