### ISSUE TITLE
Way to disable embedded (misrepresented) posters!

### ISSUE THREAD

**Issue by Anan5a** [jellyfin/jellyfin#4454]
**Describe the bug**
Right now jellygin uses embedded posters in video if available and doesn’t look for posters in internet or use screen grabber to get an image from the video itself. 

This should not be the case, because many *encoders* (sorry 🙃) wrongfully add Their own logo instead of actual posters
Here's an example 
![Screenshot_2020-11-10-13-08-53-39_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/16373480/98641823-9510d500-2356-11eb-8ac1-1dd66dc6b3e5.jpg)

How can I tell jellyfin to ignore these embedded posters?

**System (please complete the following information):**
 - OS: debian 
 - Virtualization: -
 - Clients: all
 - Browser: -
 - Jellyfin Version: 10.6.4
 - Playback: -
 - Installed Plugins: -
 - Reverse Proxy: nginx
 - Base URL: -
 - Networking: Host
 - Storage: local

**To Reproduce**

1. Add media with misrepresented embedded poster

**Expected behavior**

Fetch from internet or screen grab
**Logs**

**Screenshots**

**Additional context**

**Comment by frogcrush** [comment]
I believe that's the case by design; I don't think saying "this should not be the case" makes sense. 

Have you tried refreshing the metadata, and choosing "Replace all images"?

**Comment by Anan5a** [comment]
@frogcrush yep, just tried that, "replace all image" has no effect!
