### ISSUE TITLE
Wrong Download link & Copy Stream URL

### ISSUE THREAD

**Issue by CheChu10** [jellyfin/jellyfin#4461]
When i have multiple versions of the same video, when i selected another one than the first load, this doesn't change to 'selected' in HTML.

When u click on one on both options (Download & Copy Stream URL), always see the first version who was selected at first load, no what you selected.

Thank you so much.

Have a good day.

**Comment by solidsnake1298** [comment]
Could not reproduce in 10.8.12.  Correct versions of a movie were downloaded and stream url pointed to the correct version.  Tried both Jellyfin web and JMP 1.9.1.

**Comment by CheChu10** [comment]
Hello, @solidsnake1298 , yes. I can confirm this was fixed, I don't know in what version, but nowadays is working properly. Thank you so much! :)
