### ISSUE TITLE
Fanart.tv is reliant on tvdb being identified. 

### ISSUE THREAD

**Issue by Darkwolf1515** [jellyfin/jellyfin#4472]
**Describe The Bug**
After removing TVDB from my providers, fanart.tv is no longer able to provide art for my shows.

**Steps To Reproduce**

1.Remove TVDB from your metadata providers
2. See that fanart.tv fails to find anything.

**Expected Behavior**
Fanart.tv to find artwork

**System (please complete the following information):**
 - Platform: Docker
 - Browser: Firefox
 - Jellyfin Version: 10.6.4

**Comment by crobibero** [comment]
Looking briefly at fanart tv api docs (https://fanarttv.docs.apiary.io/#reference/tv/get-show/get-images-for-show) it requires a tvdb api key. The only thing I can recommend is to switch to the TvMaze provider which should also provide TheTVDB ids.

**Comment by Darkwolf1515** [comment]
> 
> 
> Looking briefly at fanart tv api docs (https://fanarttv.docs.apiary.io/#reference/tv/get-show/get-images-for-show) it requires a tvdb api key. The only thing I can recommend is to switch to the TvMaze provider which should also provide TheTVDB ids.

Enabling it and placing it at the bottom of my providers should work right?

**Comment by crobibero** [comment]
Yes, that should work fine.


Closing as this isn't something we can fix
