### ISSUE TITLE
Error playing h264 file: "Too many packets buffered for output stream 0:0. Conversion failed!"

### ISSUE THREAD

**Issue by antipiot** [jellyfin/jellyfin#4483]
Hello Everybody!

I encounter this error playing a MKV H264 file.
This happens either using Nvenc or not.

File plays well on desktop with VLC

i'm not sure why this file needs to be transcoded because as far as i know h264 can be direct played.

If you need more infos, please let me know
**Media Info of the file:**
[mediainfos.txt](https://github.com/jellyfin/jellyfin/files/5542126/mediainfos.txt)

**Server logs:**
[logs.txt](https://github.com/jellyfin/jellyfin/files/5542128/logs.txt)
Another server logs:
[Log3.txt](https://github.com/jellyfin/jellyfin/files/5577323/Log3.txt)

**Transcode logs:**
[transcode.txt](https://github.com/jellyfin/jellyfin/files/5542129/transcode.txt)

Another transcode log

 for another file:
[Log2.txt](https://github.com/jellyfin/jellyfin/files/5577319/Log2.txt)

**Server System (please complete the following information):**
 - OS: Docker
 - Jellyfin Version: [e.g. 10.6.4]
 - Hardware settings & device: With and without Nvenc on Quadro p400
 - Reverse proxy: Nginx
 
**Client System (please complete the following information):**
 - Device: Firefox 
 - OS: Windows 10
 - Client: Web/Browser
 - Browser (if Web client): Firefox 
 - Client and Browser Version: latest atm

**Comment by BaronGreenback** [comment]
Also showing lots of

**Comment by antipiot** [comment]
update:
It works fine on Microsoft Edge - so it's not format related

**Comment by Delgan** [comment]
Is it the same issue as reported in #3960?

It may worth trying to update Jellyfin to v10.7.0-rc1.

**Comment by antipiot** [comment]
> It may worth trying to update Jellyfin to v10.7.0-rc1. It worked for me.

Yes, 10.7 is working - tried as soon as it went out.
