### ISSUE TITLE
Marking season as Watched is really slow

### ISSUE THREAD

**Issue by kvaster** [jellyfin/jellyfin#4496]
**Describe the bug**

I've created simple media folder. It consists of 6 seasons of following movie: https://thetvdb.com/series/luntik
Jellyfin setup is clean, without any plugin.

After scan I'm trying to mark whole series as watched - and this is really really slow. Also IO consumtion is really big during this period.

Emby works instantly this same setup.

**System (please complete the following information):**
 - OS: Gentoo
 - Virtualization: no, linux
 - Jellyfin Version: 10.6.4
 - Installed Plugins: none
 - Storage: local

**To Reproduce**
1. Scan sample media folder
2. Open Luntik series
3. Click on 'watched' on season 1 (it have 80 series).
4. It will take 50-60 seconds to finish. Also you can see changing number of unwatched series one by one.
Also linux will show high IO (iowait) during this period of time.

**Expected behavior**
Marking as watched should be fast enough. Emby can do it instantly.

**Logs**
```
[2020-11-16 22:35:02.759 +03:00] [WRN] [26] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to "192.168.116.20". Time (slow): 0:00:52.3381393. "http://media:8097/Users/96be1832c8d04ffb9b3188b1aa1a6074/PlayedItems/6154fa2eace69b64c38f09b71f716262?DatePlayed=20201116223410"
```

**Screenshots**
![image](https://user-images.githubusercontent.com/1070273/99299601-7a5dc500-285c-11eb-8818-844e6843a23b.png)

**Comment by kvaster** [comment]
It seems that jellyfin opens sqlite database in TRUNCATE mode. Switching to WAL mode eliminates all problems with database speed. Is there any reason for not using WAL mode ?

**Comment by cvium** [comment]
> 
> 
> It seems that jellyfin opens sqlite database in TRUNCATE mode. Switching to WAL mode eliminates all problems with database speed. Is there any reason for not using WAL mode ?

We had an issue with WAL: https://github.com/jellyfin/jellyfin/issues/1655

**Comment by kvaster** [comment]
Personally I think that this is a bad decision.

Sqlite works really slow in truncate mode. Also emby is using wal mode for sqlite3 database and I had no problems with this for years. Also I'm using patched version of jellyfin for more then a month already (with WAL enabled) and also I see no any problems

I found some info about growing WAL file: https://stackoverflow.com/questions/7250883/sqlite3-wal-checkpoint-v2-always-returns-sql-busy.

I will try to make some huge tests at my place, but personally I see no any problems right now. Maybe this 'lock' is already fixed...
At least it will be good to have this configurable...

**Comment by nielsvanvelzen** [comment]
> Also emby is using wal mode for sqlite3 database and I had no problems with this for years. 

But we're not emby

> Also I'm using patched version of jellyfin for more then a month already (with WAL enabled) and also I see no any problems

> At least it will be good to have this configurable...

We could maybe add a option to the system.xml config for that, feel free to open a PR :)

**Comment by kvaster** [comment]
I'm sorry about compare :)
I will make a PR a little bit later than. Thanks.
