### ISSUE TITLE
4:3 content on screen with aspect ratio different than 16:9 causes double black bars

### ISSUE THREAD

**Issue by gabri94** [jellyfin/jellyfin#4498]
**Describe the bug**
As in the title, while watching 4:3 content on not 16:9 screens (like macbook, which is 16:10) or different resolutions casuses both the webplayer and jellyfin-mpv-shim to sorround the video with black bars on both sides, downsizing the image.

**System (please complete the following information):**
 - OS: Debian and OS X
 - Clients: Browser, Jelllyfin-mpv-shim
 - Browser: Safari, Chrome, Firefox
 - Jellyfin Version: 10.6.4
 - Playback: Transcoding from H265, DirectPlay

**To Reproduce**

1. Play a 4:3 content and resize the windows to a non standard aspect ratio or play a 4:3 content fullscreen on a macbook (16:10 screen)

**Expected behavior**
I expect the player to always maximize the picture.

**Screenshots**
![Screenshot using webplayer on firefox](https://user-images.githubusercontent.com/2878661/99324598-f237e980-2874-11eb-9409-4964bd93d89a.png)

![Screenshot with jellyfin-mpv-shim](https://user-images.githubusercontent.com/2878661/99324635-011e9c00-2875-11eb-814e-ad98ac82eedd.png)

**Comment by Artiume** [comment]
Can I get the ffmpeg logs. We have issues with anamorphic ratio's and I just want to make sure this doesn't have the same source issue

**Comment by gabri94** [comment]
Sorry for the disturbance, looking at the ffmpeg log i realized the file is 1920*1080 (thus 16:9) and the bars are burned in.
Closing.
