### ISSUE TITLE
FFmepg master as of 20181211

### ISSUE THREAD

**Issue by bobberb** [jellyfin/jellyfin#45]
https://medium.com/@ewoutterhoeven/dav1d-0-1-0-release-the-first-benchmarks-5404360e44e3

Master branch has had dav1d for some time now. Better codec support than emby could be very simple as I believe this is only a compilation switch away from being enabled.

**Comment by JustAMan** [comment]
Just a FYI... I'm trying to build ffmpeg from master with hardware acceleration and most of available codecs, and it's been more than a day now, so I'm not confident about "one switch away" ;-)

**Comment by anthonylavado** [comment]
Moving to close this.
We currently bundle 4.03 for Debian/Ubuntu, and are compatible with it on other platforms.
We are working on 4.1 support for all. While neither include dav1d yet, I believe we're looking away from building ffmpeg if we can help it, and instead bundle with whatever's out there whenever possible.
