### ISSUE TITLE
Emby Premiere Message in Samsung TV App

### ISSUE THREAD

**Issue by ChessDragon136** [jellyfin/jellyfin#451]
Good day all

Firstly I want to say thank you for continuing to develop this open source. I used to love Emby and its principles and wrote the original Samsung TV app for the older non Tizen Samsung TV's. 

I currently use Jellyfin with the modern Samsung TV app and I get the Emby Premiere nag message every day when I use it. I appreciate they never released the source for this but I assume that there must be some client / server communication to determine if the server is premiere or not. Is it possible to fake this communication to trick this app (and others if applicable) into thinking it is premiere enabled? 

Kind Regards,

ChessDragon136

**Comment by bfayers** [comment]
Hi, the other apps seem to do their checking locally, atleast the androidtv one did so I had to make the responses to the checks always true in its code.

In terms of responding to apps like that I enquired about doing it before but people in riot suggested it could technically be considered piracy and we should just be modifying source code of apps we do have and/or creating new apps.

**Comment by bfayers** [comment]
>I appreciate they never released the source for this

I think they did?

Might need some forking of these things:
* https://github.com/MediaBrowser/SamsungSmartTV
* https://github.com/michael-lurquin/Emby-Samsung-SmartTV-Series-D

**Comment by ChessDragon136** [comment]
That's my source for the older Samsung TV's, Emby / MediaBrowser took it from the following before they would recognise me as an app developer - https://github.com/ChessDragon136/OLD-MediaBrowser.SamsungUnofficial  

As for piracy, it is a very weak argument to disable a message for features that are not present in the server anyway? And you wouldn't be altering the app, only the server response message which is open source. My thoughts anyway. My problem is we have 5 Samsung TV's which use it and I get complaints daily, but do not want to support / pay for features I don't want to remove a nag message. Especially as it's built partially of my own code, it does take the mick...

**Comment by bfayers** [comment]
@ChessDragon136 Yep, just noticed it's yours. Any chance you can join our matrix channel? https://matrix.to/#/#jellyfin:matrix.org

**Comment by sparky8251** [comment]
Our experience with the checking has been mixed. Some apps both check themselves and the server and it varies on what they check.

We have an official logo and are near an official UI accent color to replace the emby greens. Would be awesome if you wanted to work on the jellyfin fork for us!

**Comment by ChessDragon136** [comment]
Out of curiosity how does an app know if it is Emby premiere of not without checking the server? Do users have to input their premiere key in each app individually? 

As for how much help I can be, I doubt it will be much.. The Samsung OrSay OS was rather different from Tizen, and I never touched anything server side. Regardless, there always were some similarities which I can never prove as I never saw the closed source of their Tizen. 

As for the Samsung store, well, good luck. It took about 2 years for me. Emby had the same experience and still isn't worldwide. Another reason to make server side only changes for this one!

**Comment by sparky8251** [comment]
We've found checks to m3badmin.com or some such. A telemetry and misc tasks domain Emby ran. It was also used for plugins.

Having checks against that site forcibly return true has fixed some of the other premium apps on top of making it so the queries to the server return true.

Sad to hear that it is so difficult for the Samsung TV store. We will have to look into this some more once the huge piles of code cleanup die down.

Already removed something like 275KLoC from the server just by relying on .Net Core modules and removing code that is flat out unused. And we are *maybe* a quarter of the way through cleanup!

**Comment by ChessDragon136** [comment]
@dkanada  Short version

Samsung Orsay was the OS used in TV's from around 2010 - 2014
Samsung Tizen replaced this in 2015 onwards.

My client was written for Orsay, mostly in html and js.
To make it work with Tizen is unknown as I never really looked into Tizen, but it is based on HTML webkit, and all the Samsung remote control operations and such were modified heavily. I expect it would be a lot of work and not a project for the near future..

**Comment by dkanada** [comment]
Thanks for the quick summary :) according to this [link](https://emby.media/community/index.php?/topic/31461-emby-for-samsung-status-release-notes-tizen-orsay/) OrSay is no longer accepting new apps so we would have to target Tizen for a Samsung TV client.

In case anyone is wondering about the TV clients, I found a nice [wikipedia page](https://en.wikipedia.org/wiki/List_of_smart_TV_platforms_and_middleware_software) to look through OS support. Most of them support either Android Roku, or Fire TV. Android TV apps can be published to Amazon's platform with modifications, but I am not sure yet about the situation with Roku.

**Comment by ChessDragon136** [comment]
More for reference but it appears that the old Orsay apps can be migrated to Tizen :) 
https://developer.samsung.com/tv/develop/migrating-applications/migrating-legacy-platform-to-tizen

I'm not promising anything but if and when I have time I will make an attempt at it.

**Comment by bfayers** [comment]
@ChessDragon136 Thanks for that link; I can have a look at doing it at some point. I don't have a samsung tizen TV to test with however.

**Comment by ChessDragon136** [comment]
@bfayers I've had a slow afternoon so I've installed the SDK and taken a look. My original server class seems to operate ok and can pull the public info from the server with no issues. Now got to migrate my filesystem bits and i may be able to log in with it tomorrow. Video playback looks much more simplified than it was, and that just leaves the IME.. Documentation is actually usable as well which it wasnt for Orsay. 

Leave it with me for a while as I'm sure you can work on many more things than I can. Thankfully my developer status is still in tact so I can enable dev on my TV's.  Famous last words - It may not be a complete re-write!

**Comment by bfayers** [comment]
>Famous last words - It may not be a complete re-write!

@ChessDragon136 Great news!

**Comment by davehope** [comment]
@ChessDragon136 thanks for your efforts on the Emby Orsay app. I've used it for years with few issues.

It's a shame Samsung are stopping new apps for the H series TVs, 2014 doesn't feel that long ago. Does that mean there are no options to install via USB etc that the Jellyfin project could make use of for these older devices?

**Comment by ChessDragon136** [comment]
@davehope The install would be the same as before - sideloaded through the developer menu , and loaded from a local http server. 

If you have it installed still, try pointing it to the JellyFin server and see if it works. I don't have any older tv's around anymore.

**Comment by anthonylavado** [comment]
Just as a note to all - when I get access approved (darn org perms), I will transfer this issue to the Samsung-TV repo.

And @ChessDragon136, we're happy you're here :+1:

**Comment by JustAMan** [comment]
If someone can point me to docs on how to sideload apps to my Tizen of 2015 make I can try to be an alpha/beta tester 😄  My dnsmasq and nginx are always ready if they're enough.

**Comment by deten** [comment]
I have the KS8000 Samsung tv (I think "K" is the 2016 models).

I have this issue where the EMBY app will put me on the 10 second wait as well.  Not sure if that is Tizen or is it something else?  I would love to find a way to end this nonsense.

**Comment by ChessDragon136** [comment]
It's built into the app.. 

However I've made some good progress on migrating my original Orsay (Older Samsung TV's) app to Tizen. Most of the UI is implemented, and video playback works. Once the code is more stable I'll push to my Github as it'l make a good base for most TV OS's (WebOS for LG should take little work). 

I have no ETA as it will be a long time before it is on the Samsung market (its soo slow to get approved, see how long it took Emby to do it!!) , but I am hoping I may be able to do a limited alpha test - depends on if Samsung will let me have a limited device app certificate.

**Comment by anthonylavado** [comment]
@ChessDragon136 If you need any assistance, please let me know. I’m the current acting “relationship” manager when it comes to web services and app stores.

If you’ve got something I can use to contact Samsung and set up this relationship in an “official” Jellyfin way, I’m all ears.

**Comment by deten** [comment]
I was curious if theres been any progress on this.  I am fortunate I turned off autoupdate on EMBY app, because i've heard they have blocked Jellyfin (maybe?) but I have the 10s wait.  Thanks!

**Comment by ChessDragon136** [comment]
I have an internal build that works with videos but still needs a lot of tidyup before I can push to GitHub, but it will still be a long time before it hits any marketplace due to Samsung being very slow and meticulous..

**Comment by anthonylavado** [comment]
There is a new roadmap document that is being created. I'm closing this item though. If there is any code available, or any maintainers, please reach out!

**Comment by ChessDragon136** [comment]
Ok just so it's public, I have uploaded my current work to GitHub: [https://github.com/ChessDragon136/JellyFin-SamsungTizenTV]

This is not for public use, it will not work, but I have uploaded it as my time is sporadic to work on it and I wanted others to see / have access to it if needed. This isn't to say I'm not still working on it, simply that my time is limited by life!
