### ISSUE TITLE
Debian GPG key about to expire (2020-12-15)

### ISSUE THREAD

**Issue by DavorJ** [jellyfin/jellyfin#4528]
This key: https://repo.jellyfin.org/debian/jellyfin_team.gpg.key is valid until 2020-12-15. 

It might cause trouble next month?

**Comment by joshuaboniface** [comment]
Very good catch. I knew I should've made it valid for longer!

**Comment by joshuaboniface** [comment]
A new key has been exported with no date attached. Available in the same place.

Now, getting this to people is a bit of a pain, but I will make an announcement post in various places.

**Comment by joshuaboniface** [comment]
I've also pushed the key to the Ubuntu keyserver: sudo apt-key adv --keyserver keyserver.ubuntu.com --recv 49023CD01DE21A7B

**Comment by joshuaboniface** [comment]
We've announced this on the blog, on Reddit, and on Matrix, so hopefully that gets the word out. I'll leave this open until after Dec 15th (and pinned) in case it does cause issues, so it's easy to find.

**Comment by adamroyjones** [comment]
For anyone looking for the blog post: https://jellyfin.org/posts/jellyfin-apt-key/
