### ISSUE TITLE
Could not find file 'dashboard-ui/components/tvproviders/.template.html'.

### ISSUE THREAD

**Issue by halfagascan** [jellyfin/jellyfin#453]
Receive this error on a clean clone attempt at running jellyfin dev
Host machine: Linux Deli 4.19.4-arch1-1-ARCH #1 SMP PREEMPT Fri Nov 23 09:06:58 UTC 2018 x86_64 GNU/Linux
Using Firefox 63.0.3 (64-bit) and/or Opera Version:57.0.3098.91
docker run -d     --volume /home/jerry/emby/programdata:/config  --volume /mnt/emby/share1:/mnt/share1  --volume /mnt/emby/share2:/mnt/share2  --device /dev/dri/renderD128  --publish 8096:8096 --publish 8920:8920 --net=host  --env UID=1000  --env GID=1000 --env TZ=America/Mexico_City jellydev
Connecting to the server from a windows 10 desktop and Waterfox 56.2.5 allows the xmltv guide data address to be completed, and viewable from the linux desktop

**Comment by bfayers** [comment]
Documented before.
https://github.com/jellyfin/jellyfin/issues/57 kinda.

The solution is to go look at the url it will end with `?type=xmltv` change this to `?type=xmltva` press enter, refresh. change it back to `?type=xmltv` press enter press refresh, repeat until it works.

**Comment by anthonylavado** [comment]
@halfagascan Is this still an issue for you on the latest version (10.2.2)?

Closing in 48h otherwise, as it appears to be working.

**Comment by halfagascan** [comment]
Working fine here, thanks
