### ISSUE TITLE
Cannot Save Metadata To Folder

### ISSUE THREAD

**Issue by grravity** [jellyfin/jellyfin#4536]
Unsure if this is a bug or intentional, which is why I'm placing here and not Fider. 

Issue: In the metadata manager, you cannot save Peoples & Studios metadata to a folder

Reproduce: Go to metadata manager, click a folder, add People or Studios metadata, save.

Expected Results: Expect it to apply those fields to all the files within that folder.
And if that metadata is removed from the folder metadata, it removes it from all those files.

Actual Results: After clicking save, then clicking off that folder and back on,  the recently adder entry has just disappeared.

______

Related Suggestion: Add a checkbox after each field you want to apply to all subfiles. For example, if someone wants the People, Genre fields to apply to all files under that folder, they only check those two, and are able to edit the other fields on the folder automatically.

On the files themselves, they could have a symbol to make it clear they inherit the metadata from the master folder. It would also make dealing with custom metadata on those files easier.

For example if you add an actor to People in the folder metadata, it will apply to all files under that folder. But then if you wish to add a second actor to only one of those files under that folder you can easily discern which one is inherited from the master folder and which isn't. This is more of an issue with more than 2 metadata additions, but just trying to provide a clear example.

**Comment by BaronGreenback** [comment]
Works in 10.7.0

**Comment by grravity** [comment]
Will check it out once stable is released, and close if so!
