### ISSUE TITLE
Checkpoint database files on service stop

### ISSUE THREAD

**Issue by ploughpuff** [jellyfin/jellyfin#454]
As a developer, it would be nice if the database files were checkpointed on service stop, so the .db files reflected the system at shutdown.

Jellyfin uses Write-Ahead Logging instead of a rollback journal for its database approach.  Stopping Jellyfin via the command line (sudo service jellyfin stop) does not checkpoint the databases, leaving the -wal and -shm files present.  Shutdown via the GUI does checkpoint.

**Comment by sparky8251** [comment]
Ah. This is related to #422. Maybe close 422 and make this the real tracker for this issue?

**Comment by joshuaboniface** [comment]
This might actually be simple to fix if that's the case. The GUI shutdown just calls a script IIRC.

**Comment by JustAMan** [comment]
@joshuaboniface this sounds like a workaround. I think we should make sure that transactions are really committed instead...
@sparky8251 can you provide a list of dbs that are not closed properly? You said in #422 that some dbs are closed properly and some aren't.

**Comment by ploughpuff** [comment]
I'm running a modified build with journal mode set to DELETE.  Might be a quick fix for this too:
https://sqlite.org/pragma.html#pragma_journal_mode

Does anyone know what benefits WAL mode offers us specifically?  Once the media libraries are scanned and written, most access to the db are read?
https://sqlite.org/wal.html
