### ISSUE TITLE
[bug] Cannot join syncplay group behind Nginx reverse proxy using Safari on macOS/iOS

### ISSUE THREAD

**Issue by linetrimmer** [jellyfin/jellyfin#4540]
I am running into an issue getting syncplay to work on macOS and iOS devices using Safari as the browser. I am using an Nginx reverse proxy with Cloudflare, and I have followed the example configuration outlined [here](https://jellyfin.org/docs/general/networking/nginx.html). Syncplay works perfectly on Chrome; only Safari has this issue. I'm not sure if there is something missing from my Nginx config since it does work on Chrome.

**System:**
Server OS: Linux, Docker (linuxserver)
Jellyfin Version: 10.6.4
Installed Plugins: trakt
Storage: rclone mount
Client Browser: Safari
Client OS: macOS and iOS

**Nginx config:**
```
server {
    server_name                [domain] www.[domain];
    location / {
        proxy_pass http://172.17.0.1:8096;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Protocol $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_buffering off;
    }
    location /socket {
        # Proxy Jellyfin Websockets traffic
        proxy_pass http://172.17.0.1:8096;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Protocol $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
    }
    listen 443 ssl http2;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_certificate /config/keys/[domain].pem;
    ssl_certificate_key /config/keys/[domain].key;
    ssl_client_certificate /config/keys/cloudflare.crt;
    ssl_verify_client on;

    # Security / XSS Mitigation Headers
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";

    # Content Security Policy
    # See: https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP
    # Enforces https content and restricts JS/CSS to origin
    # External Javascript (such as cast_sender.js for Chromecast or YouTube embed JS for external trailers) must be whitelisted.
    add_header Content-Security-Policy "default-src https: data: blob:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' https://www.gstatic.com/cv/js/sender/v1/cast_sender.js; worker-src 'self' blob:; connect-src 'self'; object-src 'none'; frame-ancestors 'self'";

    real_ip_header CF-Connecting-IP;
    set_real_ip_from 103.21.244.0/22;
    set_real_ip_from 103.22.200.0/22;
    set_real_ip_from 103.31.4.0/22;
    set_real_ip_from 104.16.0.0/12;
    set_real_ip_from 108.162.192.0/18;
    set_real_ip_from 131.0.72.0/22;
    set_real_ip_from 141.101.64.0/18;
    set_real_ip_from 162.158.0.0/15;
    set_real_ip_from 172.64.0.0/13;
    set_real_ip_from 173.245.48.0/20;
    set_real_ip_from 188.114.96.0/20;
    set_real_ip_from 190.93.240.0/20;
    set_real_ip_from 197.234.240.0/22;
    set_real_ip_from 198.41.128.0/17;
    set_real_ip_from 2400:cb00::/32;
    set_real_ip_from 2606:4700::/32;
    set_real_ip_from 2803:f800::/32;
    set_real_ip_from 2405:b500::/32;
    set_real_ip_from 2405:8100::/32;
    set_real_ip_from 2c0f:f248::/32;
    set_real_ip_from 2a06:98c0::/29;
}
```

**To Reproduce**
Start playing a video
Create a syncplay group
**Expected behavior**
A syncplay group has been created, and you are inside of it. The syncplay icon changes to reflect that you are in a group. Other users can see and join the group.
**Actual behavior**
A syncplay group has been created, but you are not in it. The syncplay icon still shows that you are not in a group, and clicking it again shows that there is an open group with your user inside of it (although you are not actually in it). Others can join the group, but their playback does not affect yours (since you're not in it).

**To Reproduce Pt. 2**
Attempt to join a syncplay group created by another user.
**Expected behavior**
You join the syncplay group and the video starts to load.
**Actual behavior**
Nothing :(

**Comment by EduFdezSoy** [comment]
can confirm this on linux too, whenever jellyfin is under a reverse proxy syncplay will not work (v. 10.6.4)

**Comment by Wepwawetcode** [comment]
Can confirm as well. Syncplay doesn't work. 10.6.4

**Comment by miicha** [comment]
I'm using apache and had the same issue there, but could resolve it with a little addition:

`ProxyPass /socket ws://localhost:8096/socket/`

If not already done you have to `a2enmod proxy_wstunnel` hope that helps you to figure out the changes to your nginx config...

**Comment by starryloki** [comment]
have same issue in the lastest release, can not syncplay only in safari under nginx.
