### ISSUE TITLE
LiveTV Guide Data not auto-populating

### ISSUE THREAD

**Issue by Artiume** [jellyfin/jellyfin#4565]
10.6.4

I have to manually refresh guide data to get it to appear. I tried setting pull 1 day worth of EPG but the issue is still requiring manual intervention.

![test](https://user-images.githubusercontent.com/20715731/100023100-5cd7b080-2db2-11eb-9720-3818da4114d8.png)

![test](https://user-images.githubusercontent.com/20715731/100023254-a1fbe280-2db2-11eb-84d2-b073abf1ab31.png)

**Comment by crobibero** [comment]
I can't replicate this- do you have the Scheduled Task "Refresh Guide" enabled and have triggers?

**Comment by Artiume** [comment]
yep. ran 21 hours ago, taking 10 minutes yet my epg data is currently empty. i actually didn't realize it had a task, i always tinkered with the dvr setting. i'm going to set the dvr to 2 days and the task to 12 hours

**Comment by Artiume** [comment]
The new settings weren't successful. 

![Screenshot_20201126-023201_Jellyfin](https://user-images.githubusercontent.com/20715731/100320744-a6312700-2f8f-11eb-8719-ae0c346a854a.jpg)
