### ISSUE TITLE
Ubuntu 20.10 Groovy does not have a Release file

### ISSUE THREAD

**Issue by rr222cy** [jellyfin/jellyfin#4569]
**Describe the bug**
The repository 'https://repo.jellyfin.org/ubuntu groovy Release' does not have a Release file is presented in the terminal after running the download/installation commands. To be specific it's the `sudo apt update` that triggers the error.

**System (please complete the following information):**
- OS: Ubuntu 20.10
- Latest release of Jellyfin (tried both stable and unstable)

**To Reproduce**
Run the following in the terminal
```
sudo apt install apt-transport-https
wget -O - https://repo.jellyfin.org/jellyfin_team.gpg.key | sudo apt-key add -
echo "deb [arch=$( dpkg --print-architecture )] https://repo.jellyfin.org/$( awk -F'=' '/^ID=/{ print $NF }' /etc/os-release ) $( awk -F'=' '/^VERSION_CODENAME=/{ print $NF }' /etc/os-release ) main" | sudo tee /etc/apt/sources.list.d/jellyfin.list
sudo apt update
sudo apt install jellyfin
```
`sudo apt update` triggers the error in the terminal

**Expected behavior**
To be able to run `sudo apt update` and `sudo apt install jellyfin` after adding the repository for Ubuntu 20.10

**Logs**
Output from terminal:
```
Ign:5 https://repo.jellyfin.org/ubuntu groovy InRelease                   
Err:6 https://repo.jellyfin.org/ubuntu groovy Release
  404  Not Found [IP: 68.183.204.194 443]
Reading package lists... Done
E: The repository 'https://repo.jellyfin.org/ubuntu groovy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Additional context**
Tried the repo for Focal Fossa which instead gives an error about the jellyfin-ffmpeg version not being supported. See: https://github.com/jellyfin/jellyfin/issues/4379

I should also add that I made this bug report since this seems to be 2 different bugs, where the linked post discusses the jellyfin-ffmpeg issue. But perhaps I'm wrong, nevertheless I felt it worth pointing out separately.

**Comment by Creazy-youyou** [comment]
Refer to the document file installation "deb [arch=amd64] https://repo.jellyfin.org/ubuntu focal main" Have the same problem

**Comment by danielsbrewer** [comment]
I'm having the same issue on as raspberry pi 3. Ubuntu server 20.10 is the default install. Any updates. Thanks.

**Comment by StructByLightning** [comment]
Same issue on my fairly recent install of 20.04.

**Comment by nyanmisaka** [comment]
Closed in https://github.com/jellyfin/jellyfin/issues/4379#issuecomment-776489554

**Comment by swap-17** [comment]
I used stacer to disable this in the repository section.
I dunno if I've fixed it or screwed but the error disappeared.
*linux noobie*
![image](https://user-images.githubusercontent.com/70678703/113489000-26880b80-94df-11eb-89ad-14fbe8f081f0.png)
