### ISSUE TITLE
Sort by Release Date fails to fallback to Year

### ISSUE THREAD

**Issue by Artiume** [jellyfin/jellyfin#4593]
If the release date is null, it is counted as year 0. It should fallback to the Year set in the metadata so that it can be sorted in approximately the correct order.

![test](https://user-images.githubusercontent.com/20715731/100406569-30cb6200-3034-11eb-8d98-7c7f2d782556.png)

![test](https://user-images.githubusercontent.com/20715731/100406461-e21dc800-3033-11eb-9b75-0358383450c4.png)

![test](https://user-images.githubusercontent.com/20715731/100406515-0d081c00-3034-11eb-90d7-7027de1d093d.png)

**Comment by zotabee** [comment]
Still exists as of today in Jellyfin version: "10.7.7"

Where does that date come from ? Because the data from TheMovieDB seems complete. And JellyFin manages to shows the correct year too.
