### ISSUE TITLE
Add ARM docker releases

### ISSUE THREAD

**Issue by SenorSmartyPants** [jellyfin/jellyfin#46]
Please add ARM docker versions.

Here are links to the closed source Emby versions.

https://hub.docker.com/r/emby/embyserver_arm32v7/
https://hub.docker.com/r/emby/embyserver_arm64v8/

Also, Emby dockers are quite a bit smaller. Not sure why that is.

**Comment by aptalca** [comment]
Would there be interest in having linuxserver.io maintain the docker images? We maintain multi-arch images with a robust jenkins builder. Let us know

**Comment by anthonylavado** [comment]
@aptalca That sounds interesting. We'll have to consult with the others. cc @joshuaboniface @nvllsvm

**Comment by nvllsvm** [comment]
@aptalca You're more than welcome to maintain images in the `linuxserver` namespace on Docker Hub. I'm going to maintain the images in the `jellyfin` namespace for now.

I've added arm and arm64 images to the `jellyfin/jellyfin:latest` manifest.
