### ISSUE TITLE
Live TV Sort by Android TV

### ISSUE THREAD

**Issue by BrunoN17** [jellyfin/jellyfin#4600]
**Describe the bug**
Hi everyone!
When going to Live TV, on every reset the sort by changes from Channel number to Last played, not memorizing the last selected option

**System (please complete the following information):**
 - OS: Android TV
 - Virtualization: Proxmox
 - Clients: Android TV

**To Reproduce**

1. Go to Live TV
2. Click on Settings
3. Scroll down to Sort by
4. Select sort by Channel number
5. Reset Android TV box
6. Open the App
7. Go to Live TV
8. Chanel ordered by last played again

**Expected behavior**
It should keep the last option selected, in this case, order by Channel number

**Comment by nielsvanvelzen** [comment]
This is fixed for the next release of the android tv app 👍

**Comment by BrunoN17** [comment]
Hi @nielsvanvelzen 

Sorry to reopen the issue but I don't know how to contact you directly 🙈

First let me thank you very much for the super fast response!

That's great news! Do you know more or less when it will be released?

Thanks!

**Comment by nielsvanvelzen** [comment]
No problem - commenting on a closed issue won't re-open it. We're still working on some things for the next android tv version and I can't give any ETA. I'm hoping it will be before February though.

**Comment by cadteach1** [comment]
Can confirm this bug as well.  Version 0.11.5 running.  Look forward to next release.
