### ISSUE TITLE
Can't play any movie on 10.7.0 with Chromecast

### ISSUE THREAD

**Issue by w00deyboi** [jellyfin/jellyfin#4616]
**Describe the bug**
Tried using unstable 10.7 because of the HDR tone mapping feature. Chromecast play does not work, it finds the device and connects to it successfully, the ready to cast page appears on the TV, but playback does not work, no matter what settings I use. Out of curiosity I downgraded to 10.6.4, it works flawlessly.

**System (please complete the following information):**
 - OS: Windows 10 x64 20H2
 - Virtualization: No
 - Clients: Browser, Chromecast
 - Browser: Latest Chrome
 - Jellyfin Version: 10.7
 - Playback: Nvidia hardware encoded, no hardware encoded
 - Installed Plugins: None
 - Reverse Proxy: None
 - Base URL: None
 - Networking: Host
 - Storage: Local

**To Reproduce**

1. Install 10.7
2. Open webpage through localhost address
3. Cast to Chromecast
4. Play any movie, it won't launch
5. If you play a movie on the webpage and then try to connect to chromecast it gives the error message: MessageChromecastConnectionError

**Expected behavior**
Play the movie on chromecast

**Comment by beshekh** [comment]
Same problem here. 😢

**Comment by hawken93** [comment]
Do you use chromecast with a LAN-only domain name?

**Comment by hawken93** [comment]
Previously the browser would ask the server if it knew an address that the chromecast would understand better. This caused breakage because it's hard for the server to know how things should reach it.

Now the address you connect to jellyfin with needs to be reachable by the chromecast as well, no magic. So for example http://192.168.1.123:8096/ could work while http://localhost:8096/ probably fails.

In addition to that, the chromecast always uses 8.8.8.8 / 8.8.4.4 as DNS server. Workarounds for that include redirecting DNS to your local nameserver, or pointing an internet-resolvable name to your server address. Preferrably petition google to change it so that chromecast uses the DHCP provided DNS server.

**Comment by w00deyboi** [comment]
the lan server ip can't even find the chromecast, I suppose because chrome thinks I try to connect to an ip with http, I added my server ip to an exception list in chrome to treat it as an https address. Now it finds the chromecast, but the problem still persists. If I try to play any movie it gives me the error: MessageChromecastConnectionError. Tried editing the hosts file and give a domain to my IP, it still can only connect to the chromecast.

**Comment by w00deyboi** [comment]
To exclude the chromecast weird DNS usage, I registered a free domain name, and port forwarded 8096 to my server, it still can't even recognize chromecast in http mode, if I set it to treat as https in chrome, then I can connect, but still no playback

**Comment by hawken93** [comment]
You're right. I wasn't aware of that. https://www.reddit.com/r/PleX/comments/b4ruhd/casting_to_chromecast_without_secure_connection/
Around one year ago they decided that it only will connect to https. So let's summarize:
- Chromecast uses 8.8.8.8/8.8.4.4 for name resolution
- Chromecast only connects if the client is on https
- Then on 10.7 it will connect to whatever address the browser connects to.

Given this, the only option I see is to get a letsencrypt certificate and make sure that a connection to the internet https address will work. Then as long as the certificate is valid, it's possible to update DNS and point it back to the lan address if you're not comfortable having it online.

I'll try the exception list thing you mentioned and see if I can make that work..

**Comment by w00deyboi** [comment]
Sorry if my questions from now on are stupid, but my networking skills are quite on a beginner level. I am able to setup a router with wifi wpa2psk, ipv4/v6 setup, managing DHCP pools. I've only setup so far game servers and opened ports to make them work, and some webservers in the past to test. I've never did an https server. I've read a couple of posts on this subject before trying to get help here, I think what you mean is that I either get an ssl certificate for the jellyfin server, or I've found that I can make a reverse proxy and it'll do it.

I plan to use jellyfin on the LAN, My family have no desire to watch any movies on the go, if we do, then we usually do it offline. So would you explain this to me in a bit more detail what should I do to make this work, perhaps give me a link or tutorial what you think explains it well, because honestly I've only gotten more confused so far about what I should do in order to host https.

**Comment by hawken93** [comment]
Hi, so you are absolutely correct that the reverse proxy can help you get ssl up. https://jellyfin.org/docs/general/networking/caddy.html

The reason you have to put something on your WAN address to get an SSL certificate, is that letsencrypt connects to you to check that you have the authority over that IP before it signs you a certificate.

To establish this in a more permanent way, I would recommend using nginx + certbot, because nginx can let you make sure that only LAN clients are actually allowed to connect to jellyfin. But I don't feel like every user should have to go through this just to have the chromecast working.

I have noticed that the jellyfin app is allowed to cast anyway, so for the app I suspect that things will be better, although my chromecast still doesn't seem to like my app. I'm still looking at that..

**Comment by hawken93** [comment]
I'm trying to get started developing for the chromecast now. Everything just behaves really inconsistent. I couldn't even get chromium on my laptop to start playback on the chromecast for any configuration, even with 10.6.4. The app works with any configuration on 10.6.4. I'm starting to think that chromium/chrome is an evil browser :p

**Comment by w00deyboi** [comment]
Well, I managed to get reverse proxying working, I can load the website with the noip address. Chromecast playback works on 10.6.4, however now when I try it with the latest 10.7 it doesn't recognize my Chromecast, and playback also does not work on anything.

It gives me this error in the cmd window:
[19:46:13] [WRN] [93] Jellyfin.Api.ModelBinders.CommaDelimitedArrayModelBinder: Error converting value.
System.FormatException: UserData is not a valid value for ItemFields.
 ---> System.ArgumentException: Requested value 'UserData' was not found.
   at System.Enum.TryParseByName(RuntimeType enumType, String originalValueString, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, UInt64& result)
   at System.Enum.TryParseInt32Enum(RuntimeType enumType, String originalValueString, ReadOnlySpan`1 value, Int32 minInclusive, Int32 maxInclusive, Boolean ignoreCase, Boolean throwOnFailure, TypeCode type, Int32& result)
   at System.Enum.TryParse(Type enumType, String value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at Jellyfin.Api.ModelBinders.CommaDelimitedArrayModelBinder.GetParsedResult(IReadOnlyList`1 values, Type elementType, TypeConverter converter)

Also I have constantly this error message with 10.7 if this matters: Jellyfin.Api.Auth.CustomAuthenticationHandler: CustomAuthentication was not authenticated. Failure message: Invalid token.

Yeah I decided to go with chromecast and bought one recently because of the low price and I thought it would be much easier to watch movies with it than setup a raspberry pie. Boy was I wrong :D

**Comment by w00deyboi** [comment]
I tested web playback on the lan address, and it works fine, chromecast does not appear but that's no surprise because of http. It seems like something is blocking the whole playback from the internet, but can't figure out what, I enabled every external access setting in jellyfin

**Comment by hawken93** [comment]
I paid google their developer signup fee for chromecast and I'm slowly trying to look into things and understand how this thing behaves or doesn't. My suspicion is that in addition to the known limitations, there is lots of stuff that could be buggy or go wrong. I'd be really happy if it worked with the right workarounds.

**Comment by briandipalma** [comment]
Works flawlessly casting via the cast option in Chrome (Hamburger menu -> Cast), using http and local IP or local hostname. On Android Jellyfin and within Jellyfin web it doesn't even find any devices to cast...what is Chrome doing differently?

**Comment by idittansikte** [comment]
For me the web and android client finds the chromecasts but when I "play" a move I get "MessageChromecastConnectionError" in a popup. It seem to come from the chromecast client (maybe the actual chromecast?). No additional traces can be found in the server logs. I did a tcpdump on the server and the chromecast send packets to the server when pressing play.

**Comment by BongoEADGC6** [comment]
Chromecast seems to half work in my scenario. It works with the Web version, but the Android application does not work. However, I do notice that the Android client cast function still does not initiate the Beta version of the Chromecast client, even when the "unstable" version is selected in the playback settings. The web client does call the unstable version properly. You can see this in the cast menu once the splash screen is loaded on your Chromecast.

- Kubernetes build on image: linuxserver/jellyfin:version-20201209.13-unstable
- nginx ingress settings to override /System/Info/Public endpoint (see notes)
- Chromecast Unstable version under "playback" settings

Nginx Ingress settings:
```
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/server-snippet: |
      location ~* /System/Info/Public {
        add_header Content-Type "application/json; charset=utf8";
        return 200 '{"LocalAddress": "https://jelly.example.com","ServerName":"jelly.example.com","Version":"10.7.0","ProductName":"Jelly
fin Server","OperatingSystem":"Linux","Id":"youridstringhere","StartupWizardCompleted":true}';
      }
```

**Comment by idittansikte** [comment]
I got both web and android to work! I did not know the Chromecast "unstable/stable" setting existed, I thought it was something that was selected when building the server when I saw comments about it. Anyhow, I needed to reload the tab in web and **clear the cache** on Jellyfin app in Android application settings after setting unstable. Thanks a lot, I am so happy now having everything working behind a reverse proxy without any dirty hacks.

**Comment by BongoEADGC6** [comment]
@idittansikte What version of the Android app are you currently running?

**Comment by idittansikte** [comment]
@BongoEADGC6 2.2.2

**Comment by adriangoransson** [comment]
I'm having the exact same issues as @idittansikte was having.
Where are you choosing the stable/unstable chromecast client? I'm running jellyfin unstable in docker (20201209.18-unstable) and can see no such option in the dashboard of the web client.

**Comment by idittansikte** [comment]
@adriangoransson It's not in the dashboard settings, it's at <user> -> playback -> Advanced -> Chromecast Version.

**Comment by w00deyboi** [comment]
Tried on rc1 what idittansikte suggested, unstable does indeed work with regular x264 movies. However as soon as I try to play x265 HDR movies, it won't let me, I can play it with a trick though: if I start playing it in the browser and then try to cast it to the chromecast, it works about 50% of the time, but it's very buggy, it hangs often, subtitles go out of sync if I fast forward.

**Comment by idittansikte** [comment]
I also have problems playing most of my x265 HDR movies, x264 1080p always works. The jellyfin chromecast receiver seem to be very strict on what to direct play and are forcing transcoding (e.g. ac3 and mkv direct play is always disabled even though some chromecast can play this kind of content). My server has some problems transcoding some x265 HDR content (idk if its too heavy for my server or chromecast, it's almost 50-60GB and 60000bitrate) but I have not figured out why. Either it's very slow or just aborts right away.

**Comment by Ixanis** [comment]
I'm also experiencing this issue. No chromecasts in the list since the last time I updated jellyfin.

**Comment by SigHunter** [comment]
I still have this issue with unstable 20201231.7 on windows. 
Android App (2.2.3) cast button finds the chromecast but playback never starts. Error Message "MessageChromecastConnectionError". 
JF Server is accessible via duckdns domain with letsencrypt cert from the internet. Tried the "unstable" and "stable" Chromecast Setting in the app. Even with debug logging enabled there is not much usable output. only thing that is logged when I try playback:
`[2020-12-31 16:35:10.994 +01:00] [DBG] [50] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was not authenticated.
[2020-12-31 16:35:21.555 +01:00] [DBG] [50] Emby.Server.Implementations.Session.SessionWebSocketListener: Watching 2 WebSockets.
[2020-12-31 16:35:21.558 +01:00] [INF] [50] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2020-12-31 16:35:21.801 +01:00] [DBG] [41] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2020-12-31 16:35:21.805 +01:00] [DBG] [41] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2020-12-31 16:35:21.820 +01:00] [DBG] [44] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2020-12-31 16:35:21.822 +01:00] [DBG] [44] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2020-12-31 16:35:21.931 +01:00] [DBG] [50] Jellyfin.Api.Auth.CustomAuthenticationHandler: Error authenticating with "CustomAuthenticationHandler"
MediaBrowser.Controller.Authentication.AuthenticationException: Request does not contain a token.
   at Emby.Server.Implementations.HttpServer.Security.AuthService.Authenticate(HttpRequest request)
   at Jellyfin.Api.Auth.CustomAuthenticationHandler.HandleAuthenticateAsync()
[2020-12-31 16:35:21.935 +01:00] [DBG] [50] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was not authenticated.
[2020-12-31 16:35:22.063 +01:00] [DBG] [41] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2020-12-31 16:35:22.066 +01:00] [DBG] [41] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2020-12-31 16:35:24.016 +01:00] [DBG] [40] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS "mypublicIP" received message: WebSocketMessage`1 { MessageType: KeepAlive, MessageId: 00000000-0000-0000-0000-000000000000, ServerId: null, Data: null }`

**Comment by Codex-** [comment]
Same issue with latest daily too. Attempted both stable and unstable chromecast settings, no dice sadly.

**Comment by hawken93** [comment]
From my reading of this, the main complaint seems to be that the android app doesn't behave well? It runs jellyfin 10.6 and thus has the 10.6 problem (curl -fs `http://myserver/System/Info/Public` to see what it really tries to connect to), in addition I think the stable chromecast version probably breaks with 10.7 I think because it asks for /mediabrowser URLs, check your server logs and see if it asks for things that aren't there. If jellyfin wants to keep stable working then those URLs must be reinstated, but nightly is not far away from becoming more useful.

**Comment by dessalines** [comment]
This is still an issue. Chromecast playback is completely broken on 10.7

**Comment by idittansikte** [comment]
I have previously converted all my media to mp4/aac-2-channel to be able to direct play to chromecast due to all the problems but now with 10.7 jellyfin insists to open a hls-ts stream due to `TranscodeReasons=SecondaryAudioNotSupported` even though the mp4 only have one audio track with aac 2.

The hls-ts stream plays fine for 30 seconds then it freezes. I don't know if it is a jellyfin/jellyfin-chromecast issue or a jellyfin/jellyfin issue.

However, I removed all ProfileCondition::IsSecondaryAudio from jellyfin-chromecast and self-hosted the chromecast receiver and it now works again.

**Comment by Codex-** [comment]
> Same issue with latest daily too. Attempted both stable and unstable chromecast settings, no dice sadly.

With the newest versions of everything, I found that I can only play via cast if I use a version of jellyfin-android build via android studio (not the gradle tasks): https://github.com/jellyfin/jellyfin-android/issues/324

If I cast via the web app, the cast loads the chromecast app, but pressing play or any other control does nothing despite the messages being sent correctly:
![image](https://user-images.githubusercontent.com/8297838/111891098-d4fa6e00-8a54-11eb-9a6b-e71989d8f79d.png)

Happy to help further with this, looks like i'd need to get chromecast app debugging going 🤔

**Comment by oischinger** [comment]
@Codex- I get the same error with latest jellyfin and chromecast nightly.
Are you also running your instance behind a reverse proxy?

**Comment by Codex-** [comment]
@oischinger nope, same network, nothing unusual.

I gave up in the end, haven't had enough time to investigate the bug, debugging the chromecast client seems painful so just need to set it up

**Comment by eyJhb** [comment]
My comment here https://github.com/jellyfin/jellyfin/issues/4918#issuecomment-898971142 might aid some of you.
If the Chromecast can connect, do as @hawken93 says, check the DNS (remember Chromecast is hardcoded to 8.8.8.8 and 8.8.4.4, so do natting or block the IPs).
Ensure that your Jellyfin servers runs on HTTPS, and _not_ selfsigned, as a selfsigned cert will make you able to connect to the Chromecast, but not cast anything (might be possible to get around, but extra thing to debug).

Also, if using a reverse proxy, try to run without it.

**Comment by jmarcgit** [comment]
Hi, I just installed jellyfin and had the same issue. I use a local DNS and created a self signed certificate for my server. Of course it doesn't work because you send the same URL to the chromecast which can't 1/ resolve the host name and can't 2/ accept a self signed certificate. HTTPS is requred to discover the Chromecast in the network.

Using the server IP address in the URL solved issue 1. I bet that using a free subdomain DNS on the Internet will work also.

But one need to buy a verified certificate to solve issue 2. Or you could send the HTTP url to the Chromecast when HTTPS is ,not enforced. I know this can be a privacy breach when streaming on the go. Maybe adding an dedicated option in the config could be acceptable. What do you think ?

**Comment by srcrist** [comment]
Is anyone able to confirm that this remains an issue in 10.8.11?
