### ISSUE TITLE
Direct streaming bug - compatible media format

### ISSUE THREAD

**Issue by bekon16** [jellyfin/jellyfin#4618]
Hi,

I would like to report some bug related to direct streaming.
I have one movie, video codec h264, container MKV, first audio channel: AAC - everything satisfied to direct stream.
I'm trying to play the same video file (not in the same time), from the same account on two different computers (both of them are Windows 10 machines with newest Chrome web browser - incognito mode - without any plugins).
And on one of them i got: "This client isn't compatible with the media and the server isn't sending a compatible media format"

This is log from jellyfin for computer with error (normall Dell laptop, with i7 cpu, 16GB ram and integrated GPU):
[error_log.txt](https://github.com/jellyfin/jellyfin/files/5612800/error_log.txt)

This is log from jellyfin for computer without error:
[good_log.txt](https://github.com/jellyfin/jellyfin/files/5612802/good_log.txt)

Here is output from ffmpeg -i command:
[ffmpeg_output.txt](https://github.com/jellyfin/jellyfin/files/5612804/ffmpeg_output.txt)

Version of JellyfIn: Version: 10.6.4
Version of OS: Debian 10.6,   4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64 GNU/Linux

Can anyone check whats going on? Looks like some bug for me.
If you need any addiotional logs, files or something else - just let me know.

**Comment by Artiume** [comment]
For whatever reason, it looks like it's trying to DirectPlay the file on the computer that it's erroring out on.

**Comment by bekon16** [comment]
Hi, this bug report can be closed. It was happened because of incomplete content security policy on reverse proxy - was to restrict.
