### ISSUE TITLE
Open API generation - Blurhash Image Types

### ISSUE THREAD

**Issue by Camc314** [jellyfin/jellyfin#4624]
**Describe the bug**
The OpenAPI spec is producing an incorrect spec. The properties of BaseItemDTo.ImageBlurHashes.Primary is not a dictionary

**System (please complete the following information):**
 - OS: N/A
 - Virtualization: Docker
 - Clients: N/A
 - Browser: N/A
 - Jellyfin Version: Latest Nightly 
 - Playback: N/A
 - Installed Plugins: AudioDB, MusicBrainz, OMDb, Playback reporting
 - Reverse Proxy: none
 - Base URL: none
 - Storage: local

**To Reproduce**
1. Pull a copy of the latest openapi.json from `{baseurl}/api-docs/openapi.json`
2. Navigate to `BaseItemDTo` -> `ImageBlurHashes`
3. The properties of image types are incorrect
For example: Incorrect:
```
"Primary": {
  "type": "object",
  "properties": {
    "string": {
      "type": "string",
      "format": "string"
    }
  }
},
```

**Expected behavior**
The property should be a dictionary as seen [here](https://swagger.io/docs/specification/data-models/dictionaries/)
```
"Primary": {
  "type": "object",
  "additionalProperties":
    type: string
  }
},
```

**Logs**
N/A

**Screenshots**
N/A

**Additional context**
N/A

**Comment by nielsvanvelzen** [comment]
jellyfin-apiclient-java currently uses a "hook" which always replaces the blurhash properties with a map (dictionary type in Kotlin).

https://github.com/jellyfin/jellyfin-apiclient-java/blob/master/openapi-generator/src/main/kotlin/org/jellyfin/openapi/hooks/model/ImageMapsHook.kt

_Commenting here so I'm notified when something changes with this property._

**Comment by crobibero** [comment]
There are two properties with custom mappings, should both be removed?

https://github.com/jellyfin/jellyfin/blob/926d8212989583d3481d3d5d46e5efd63aa49a4c/Jellyfin.Server/Extensions/ApiServiceCollectionExtensions.cs#L286

**Comment by crobibero** [comment]
I think I have the mapping correct now, just to confirm- this is the new output

```json
"ImageBlurHashes": {
	"type": "object",
	"properties": {
		"Primary": {
			"type": "object",
			"additionalProperties": {
				"type": "string"
			}
		},
		"Art": {
			"type": "object",
			"additionalProperties": {
				"type": "string"
			}
		},
		"Backdrop": {
			"type": "object",
			"additionalProperties": {
				"type": "string"
			}
		},
		"Banner": {
			"type": "object",
			"additionalProperties": {
				"type": "string"
			}
		},
		"Logo": {
			"type": "object",
			"additionalProperties": {
				"type": "string"
			}
		},
		"Thumb": {
			"type": "object",
			"additionalProperties": {
				"type": "string"
			}
		},
		"Disc": {
			"type": "object",
			"additionalProperties": {
				"type": "string"
			}
		},
		"Box": {
			"type": "object",
			"additionalProperties": {
				"type": "string"
			}
		},
		"Screenshot": {
			"type": "object",
			"additionalProperties": {
				"type": "string"
			}
		},
		"Menu": {
			"type": "object",
			"additionalProperties": {
				"type": "string"
			}
		},
		"Chapter": {
			"type": "object",
			"additionalProperties": {
				"type": "string"
			}
		},
		"BoxRear": {
			"type": "object",
			"additionalProperties": {
				"type": "string"
			}
		},
		"Profile": {
			"type": "object",
			"additionalProperties": {
				"type": "string"
			}
		}
	},
	"description": "Gets or sets the primary image blurhash.",
	"nullable": true
}
```
