### ISSUE TITLE
Change only Live-TV Part from 10.7 over 10.6.4 stable

### ISSUE THREAD

**Issue by morbificagent** [jellyfin/jellyfin#4640]
Because LiveTV from 10.6.4 doesnt work with my streams i have compiled the git version and livetv was working great. But there were so many problems with it as Kodi couldnt connect anymore like the AndroidTV-App too... And all of my plugins where gone and could not be installed again.
Also the Network-Settings i made in the webinterface werent written to the right config-file (as it has changed?)
All in all everything was a mess after that.

I ended in rolling back to the 10.6.4.

Did i anything wrong in compiling the git-version of 10.7 and installing the .deb over my existing 10.6.4 on Ubuntu 20.04 ? Or is it too much "beta"?

And if it is like that, would it be possible to copy only the files which are relevant for the live-tv part from the compiled .deb to the 10.6.4 so i could keep the working version and only change its live-tv part?

_Originally posted by @morbificagent in https://github.com/jellyfin/jellyfin/issues/4511#issuecomment-732801734_

**Comment by nyanmisaka** [comment]
I think some clients are incompatible with 10.7 for now, but hopefully they may get fixed when 10.7 is released.

**Comment by morbificagent** [comment]
@nyanmisaka Yes it looks like this. :-(

But as the live-tv-part is working great on 10.7 i would like to copy the relevant files over the 10.6.4 files.
Does anyone has an idea which files this should be so i could give it a try?

**Comment by nielsvanvelzen** [comment]
You could just wait a few weeks until 10.7 is released. At that point all clients should work with it.

**Comment by nyanmisaka** [comment]
There are many migrations between 10.6 and 10.7, so it is hard to backport things related to LiveTV.

Stay tuned and wait for the upcoming 10.7 RC1 in a few days.

**Comment by morbificagent** [comment]
@all ok, i will wait until it will be released... thought it would be further away.
