### ISSUE TITLE
No Login possible and cannot reach the Server

### ISSUE THREAD

**Issue by mbbaal** [jellyfin/jellyfin#4655]
Describe the bug
can't log in on any device always get ERR_CONNECTION_REFUSED

System (please complete the following information):
 - OS: Linux Home Assistant
 - Virtualization: Docker
 - Clients: any Device, Browser, Android Phone, Nvidia Shield, Kodi
 - Browser: Chrome Version 87.0.4280.88
 - Jellyfin Version: LABEL build_version=Linuxserver.io version:- 10.6.4-1-ls86 Build-date:- 2020-12-03T09:14:13-05:00 <<<hope it's the right one Docker is on Latest
 - Playback: No
 - Reverse Proxy: No
 - Base URL: http://192.168.xxx.xx:8096/
 - Storage: Local on my Openmediavault Server is reachable

To Reproduce
- Used Watchtower to Update my Docker Images

Logs:
[log_20201124.log](https://github.com/jellyfin/jellyfin/files/5641578/log_20201124.log)

I am not sure if i ts the right on its from my Server Directly I hope it helps.

Thanks in Advance

**Comment by cvium** [comment]
Looks like a configuration problem on your end. We do not support the use of Watchtower or any other automatic container updates.
