### ISSUE TITLE
Jellyfin Content able to accessed without using specified username and Password

### ISSUE THREAD

**Issue by Samk19** [jellyfin/jellyfin#4658]
Able to Access jellyfin server without a login on jellyfin server.
All computers on the same network are able to access files on jellyfin server without using jellyfin server username and password.

Big problem if you live in a shared apartment.

**System (please complete the following information):**
 - OS: Windows
 - Jellyfin Version: 10.6.4
 - Storage: local

**To Reproduce**

1. Start Jellyfin server
2. Connect a new device (Laptop/desktop) to the same network as jellyfin server
3. check the option of enable discover devices 
4. jellyfin server listed in my computer/this pc as network device

**Expected behavior**
Jellyfin device is discoverable on any computer and anyone can access the contents of jellyfin server without using jellyfin username or password.
options like open and copy are enabled.

Though the discovery of the server is ok, it should not be possible for any user without jellyfin username and password to access the contents of the server. So users with jellyfin server passwords can only stream and access content to their authorized devices.

**Screenshots**
![Screenshot (6)](https://user-images.githubusercontent.com/36104528/101177574-faae6380-366d-11eb-8fb8-0ef11baba533.png)
![Screenshot (7)](https://user-images.githubusercontent.com/36104528/101177583-fda95400-366d-11eb-8f83-d655ab1ca444.png)
![Screenshot (8)](https://user-images.githubusercontent.com/36104528/101177589-fe41ea80-366d-11eb-991e-ad04f5f5e06d.png)
![Screenshot (9)](https://user-images.githubusercontent.com/36104528/101177593-00a44480-366e-11eb-81b8-209e943efc60.png)

**Additional context**
Big Problem if you are using an SBC as jellyfin server and your dorm-mates start to download (Copy paste videos) from your jellyfin server.
Any solution?

**Comment by dkanada** [comment]
You can disable this by turning off DLNA in the settings.

**Comment by cvium** [comment]
Not a bug. That is how DLNA works. You can disable it as dkanada mentioned.
