### ISSUE TITLE
Transcoding Fails- Works with Plex/HDHR App/VLC

### ISSUE THREAD

**Issue by gary-hammer** [jellyfin/jellyfin#4659]
**Describe the bug**
Will not play any channel that needs transcoding from my HDHR tuner.

**System (please complete the following information):**
 - OS: Pop!OS 20.10
 - Virtualization: None
 - Clients: Android app on phone and Shield Tube, PC via Browser
 - Browser: Firefox and MS Edge- Current versions
 - Jellyfin Version: 10.6.4
 - Playback: Direct Play or Transcode
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: none
 - Networking: LAN
 - Storage: local

**To Reproduce**

1. Go to 'Live TV'
2. Click on 'Affected Channel'
3. Play
4. See spinning ball

**Expected behavior**
Channel should play

**Logs**
Attached as txt files

**Screenshots**
N/A

**Additional context**
Had worked in the recent past, now this channel alone has issues.
Working fine on Plex and the HDHR app. Also VLC using the feed URL from the tuner.
The common thread in the failed logs is the profile:

x264 [error]: invalid profile: constrainedbaseline
[libx264 @ 0x561e04c88bc0] Error setting profile constrainedbaseline.
[libx264 @ 0x561e04c88bc0] Possible profiles: baseline main high high10 high422 high444
Conversion failed!
[Tune-Error.txt](https://github.com/jellyfin/jellyfin/files/5643479/Tune-Error.txt)
[Failcp-ffmpeg-transcode-8fb1755c-e681-4eb0-b1ff-97c0791da3d8.txt](https://github.com/jellyfin/jellyfin/files/5646370/Failcp-ffmpeg-transcode-8fb1755c-e681-4eb0-b1ff-97c0791da3d8.txt)
[Failnv-ffmpeg-transcode-5ac705fe-a910-4c06-a8d6-a362c6fb8521.txt](https://github.com/jellyfin/jellyfin/files/5646371/Failnv-ffmpeg-transcode-5ac705fe-a910-4c06-a8d6-a362c6fb8521.txt)
[Good-ffmpeg-directstream-6b5b1d39-26c6-4a99-9da6-c5f95c7bc1cf.txt](https://github.com/jellyfin/jellyfin/files/5646372/Good-ffmpeg-directstream-6b5b1d39-26c6-4a99-9da6-c5f95c7bc1cf.txt)

**Comment by crobibero** [comment]
If possible please test with the latest 10.7 RC

**Comment by gary-hammer** [comment]
> If possible please test with the latest 10.7 RC

I'm game, but 10.7 will install but does not have jellyfin-ffmpeg and that fails to install due to 
The following packages have unmet dependencies:
 jellyfin-ffmpeg : Depends: libx264-155 but it is not installable
                   Depends: libx265-179 (>= 3.2) but it is not installable
E: Unable to correct problems, you have held broken packages

**Comment by Artiume** [comment]
@crobibero For the transcode error, I suspect it's the same issue as this one.

https://github.com/jellyfin/jellyfin-android/issues/202

for whatever reason our Stream Builder fails on encoding with CB. and for whatever reason, CB takes priority when mentioned. It might be because it's the first one listed.

**Comment by nyanmisaka** [comment]
`constrainedbaseline` this issue should be fixed in 10.7.

@gary-hammer 
Can you update your apt by using `sudo apt update` and try to reinstall our latest jellyfin-ffmpeg 4.3.1-3?

**Comment by gary-hammer** [comment]
@nyanmisaka That version was already installed, so apt update shows nothing.
jellyfin-ffmpeg/unknown,now 4.3.1-3-focal amd64 [installed,automatic]

**Comment by nyanmisaka** [comment]
You can give a try on 10.7-rc1 now.

**Comment by gary-hammer** [comment]
@nyanmisaka I attempted an install of rc1 yesterday on another server and it didn't go well. I'll wait for rc2.

**Comment by cvium** [comment]
@gary-hammer Please re-test with 10.7.1

**Comment by gary-hammer** [comment]
The 10.7.6 build has resolved my issue, playing Live TV well on my Sony with Android TV.
