### ISSUE TITLE
TMDb Scanner not pulling correct images for season, episodes

### ISSUE THREAD

**Issue by sanecito** [jellyfin/jellyfin#4668]
**Describe the bug**

Jellyfin has TV Show scanners set to 1. AniDB and 2. TMDb, but despite having TMDb TV show id set, and there being a season image in TMDb, Jellyfin seems to be pulling season image data from TVDb for season, and an unknown image source for episode despite the edit image selection having an image from TMDb.

**System (please complete the following information):**
 - OS: EndeavourOS
 - Virtualization: None
 - Clients: Browser
 - Browser: Firefox 83
 - Jellyfin Version: 10.6.4_1-1 (AUR: jellyfin-server-bin, jellyfin-web-bin)
 - Playback: N/A
 - Installed Plugins: Standard + TMDB Boxset, TV Maze, Anime
 - Reverse Proxy: None
 - Base URL: N/A
 - Networking: N/A
 - Storage: NAS

**To Reproduce**

1. Create directory and file structure in your TV Show library: Super Sentai > Season 38 > スーパー戦隊シリーズ - 38x01 - 
Starting Station: Let's Ride the Limited Express Train.[video media file extension]
2. Scan library for new files
3. Validate TMDb id in series meta data shows 45253
4. Validate you get an image (see below) of the opening credits rather than the [image shown for episode 1 in TMDb](https://www.themoviedb.org/tv/45253/season/38/episode/1)

**Expected behavior**

The image shown for season/episode in TMDb is the one used for Jellyfin if TMDb is the only live action media scanner source

**Logs**

N/A

**Screenshots**

![seriesmeta](https://user-images.githubusercontent.com/3056597/101235606-af25a500-36c1-11eb-8b23-bb593e6db68f.png)
![Seasonmeta](https://user-images.githubusercontent.com/3056597/101235610-bd73c100-36c1-11eb-9ae5-bba243af9192.png)
![episodemeta](https://user-images.githubusercontent.com/3056597/101235613-c06eb180-36c1-11eb-8e78-2015be072239.png)
![sentaiseason](https://user-images.githubusercontent.com/3056597/101235628-daa88f80-36c1-11eb-9eab-0ba9edb55129.png)
Note as shown that in addition to the issue of the opening credits image being used on Jellyfin, it's nowhere to be found in the selectable images so it's unclear the source. Furthermore, the image listed for TMDb is the older image which is no longer the primary image for this episode.
![imagemeta](https://user-images.githubusercontent.com/3056597/101235630-dd0ae980-36c1-11eb-93d4-b0b811c7f916.png)

**Additional context**

Semi-related comment on my trying to work this issue: there doesn't seem to be a TMDb id field at either the season or episode level within Jellyfin like other meta data providers

**Comment by cvium** [comment]
Images are separate from metadata under the Advanced Settings toggle (removed in 10.7 iirc).

![image](https://user-images.githubusercontent.com/675118/101242842-60493100-36fc-11eb-9138-4f3de0f72b62.png)

**Comment by Ullmie02** [comment]
With these settings
![image](https://user-images.githubusercontent.com/16425113/102643235-3e6d9680-415f-11eb-8a81-434a955cc3b3.png)
I as well can't replicate your issue. The image for the episode 38x01 is the one shown in TMDb
![image](https://user-images.githubusercontent.com/16425113/102643416-87254f80-415f-11eb-9999-962d70d749d4.png)
without me manually selecting it which is also possible:
![image](https://user-images.githubusercontent.com/16425113/102643528-b340d080-415f-11eb-9190-df737646df00.png)

Could you please verify that you have enabled the TMDb Episode Image Fetcher and get back to us if you still can't find the correct episode image

**Comment by sanecito** [comment]
> Images providers are separate from metadata under the Advanced Settings toggle (removed in 10.7 iirc). Please verify that TMDb is enabled as an image fetcher for season and episode.
> 
> ![image](https://user-images.githubusercontent.com/675118/101242842-60493100-36fc-11eb-9138-4f3de0f72b62.png)

Thanks this was it; failed to see there's more fetcher configs in the Advanced view
