### ISSUE TITLE
Client IP address is wrong by default when behind a proxy

### ISSUE THREAD

**Issue by thornbill** [jellyfin/jellyfin#4670]
**Describe the bug**
The client IP address reported by Jellyfin will be the IP address of the proxy by default. To work around this, you currently have to set known proxies manually in the server dashboard.

**System (please complete the following information):**
 - OS: Debian
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Any
 - Jellyfin Version: 10.7
 - Playback: N/A
 - Installed Plugins: None
 - Reverse Proxy: Caddy
 - Base URL: None
 - Networking: Bridge
 - Storage: N/A

**To Reproduce**
1. Go to the server dashboard when Jellyfin is served by a reverse-proxy
2. View the IP addresses in the activity log

**Expected behavior**
If there is a single X-Forwarded-For header, it needs to treat it as authoritative, regardless of the known proxies setting.

**Logs**
N/A

**Screenshots**

**Additional context**
N/A

**Comment by joshuaboniface** [comment]
Did some more research, this is a part of the ASP.NET middleware. There's additional flexibility there to support whole netblocks, which would be ideal, and it would also be ideal to have a checkbox to disable this checking and have it off by default.
