### ISSUE TITLE
Plugins issues 10.7.0

### ISSUE THREAD

**Issue by l3oncoder** [jellyfin/jellyfin#4677]
There seem to be an issue with installing plugins such as anime & fanart

* Emby.Server.Implementations.ApplicationHost: Error loading types from Jellyfin.Plugin.Anime,
* Emby.Server.Implementations.ApplicationHost: Error loading types from Jellyfin.Plugin.fanart,

**Comment by BaronGreenback** [comment]
Have you upgraded the plugins to the latest?

**Comment by crobibero** [comment]
I don’t think we’ve released builds for 10.7 plugins yet

**Comment by TheNamelessWonderer** [comment]
Nope there are no releases currently for plugins but most of them can be compiled from source.

**Comment by crobibero** [comment]
Plugins have now been released
