### ISSUE TITLE
[DOCKER] Linuxserver.io > Official Jellyfin Container

### ISSUE THREAD

**Issue by vegedb** [jellyfin/jellyfin#4687]
**Describe the bug**
Everything in docker-compose is kept the same, Only changed the line **jellyfin/jellyfin** from linuxserver/jellyfin. 
Jellyfin starts fresh no matter what.

**System (please complete the following information):**
 - OS: [Rasbian RP4 32bit]
 - Virtualization: [Docker]
 - Jellyfin Version: [10.6.4]

**To Reproduce**

1. go docker-compose.yml
2. change the line linuxserver/jellyfin to **jellyfin/jellyfin**
3. type docker-compose up
4. check ip:8096
5 It starts a FRESH library 

**Expected behavior**
Should retain the library created from linuxserver.io

**Comment by crobibero** [comment]
https://github.com/linuxserver/docker-jellyfin/issues/22
