### ISSUE TITLE
Shows libraries stop scanning halfway through

### ISSUE THREAD

**Issue by MrTimscampi** [jellyfin/jellyfin#4691]
**Describe the bug**
On a clean server running 10.7 RC1, "Shows" libraries will stop scanning halfway through the files.

Unscanned items will appear like this and don't contain any episodes or seasons:
![image](https://user-images.githubusercontent.com/19396809/101273768-ad7ae080-3798-11eb-9ab5-6a0728a83c1a.png)

Triggering a new scan with "Search for missing metadata" and "Replace existing images" will scan and match part of the files before stopping again.

**System (please complete the following information):**
 - OS: Debian 10
 - Virtualization: Docker
 - Clients: Web, Vue
 - Browser: Firefox 82
 - Jellyfin Version: 10.7 RC1
 - Playback: n/a
 - Installed Plugins: None
 - Reverse Proxy: None
 - Base URL: None
 - Networking: Exposed port 8096 via Docker
 - Storage: NFS

**To Reproduce**
1. Start a fresh server
2. Go through the wizard
3. Go to Dashboard > Libraries and add a new TV library
4. Enable TMDB and OMBD for the providers
5. Start the scan
6. Wait for a bit

**Expected behavior**
The scan should complete in one go, not stop partway through.

**Logs**
Can't find any fully relevant logs, but I have a lot of these when doing the scans:

```
[2020-12-06 06:59:59.501 +00:00] [ERR] [594] MediaBrowser.Providers.Manager.ProviderManager: "TmdbSeriesImageProvider" failed in GetImageInfos for type "Series" at "/data/TV/Marvel's Agent Carter (2015)"
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, IReadOnlyCollection`1 preferredLanguages, CancellationToken cancellationToken, Nullable`1 type)
```

And these:
```
[2020-12-06 06:57:25.709 +00:00] [ERR] [274] Emby.Server.Implementations.Library.LibraryManager: Cannot get image dimensions for "/config/metadata/library/4b/4b7478752232589b426d26259838c137/poster.edl"
Non-success codec result: Unimplemented
Jellyfin.Drawing.Skia.SkiaCodecException: Exception of type 'Jellyfin.Drawing.Skia.SkiaCodecException' was thrown.
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
```

**Screenshots**

**Additional context**

**Comment by MrTimscampi** [comment]
After a re-scan, metadata is fetched but seasons still appear empty:
![image](https://user-images.githubusercontent.com/19396809/101273919-17e05080-379a-11eb-88a9-272a603f4087.png)

However they do appear when fetching latest episodes:
![image](https://user-images.githubusercontent.com/19396809/101273926-35151f00-379a-11eb-93d9-79e100153bbf.png)

**Comment by MidnightSnowleopard** [comment]
I've seen this for several shows I have as well but was able to get them to show up by modifying the file names to something closer to what Jellyfin seems to expect.  It especially seems to be having issues with shows not having every episode in its own season folder.  I've had to create folders for shows even with only one season with all the episodes clearly labeled as season 1 that worked previously.

**Comment by nielsvanvelzen** [comment]
I'm experiencing the same issue with my custom resolver (nielsvanvelzen/jellyfin-plugin-resolver). What I think might be the cause is that an episode uses "ParentIndexNumber = 1" and normally the librarymanager (or wherever resolvers are called from..) will search for the parent and create a season dynamically. I think this creation part is failing right now.
In the metadata editor nothing shows up underneath the series (no season/episodes).

**Comment by nielsvanvelzen** [comment]
I'm 80% the cause is #4177 removing the DummySeasonProvider. This class looked for series with episodes directly attached and created a season between them.

**Comment by nielsvanvelzen** [comment]
Updated to jellyfin_20201211.7-unstable and this issue is not fixed for me. Tried updating the item with missing seasons at first and rescanning my entire library after that.

**Comment by SigHunter** [comment]
this bug happened to my new install with 20201227.7-unstable. i have 50 tv shows of which about 5 were correctly scraped and have poster images, the scan finnished and "scan all libraries" does nothing new but most of the shows do not have any images. selecting an individual tv show and "replace metadata & replace images" corrects it most of the time

**Comment by ManuLinares** [comment]
Same here, it fails to scrape, even when I force it with "Identify".

```
ene 17 16:04:28 think jellyfin[158170]: [16:04:28] [ERR] [221] MediaBrowser.Providers.Manager.ProviderManager: TmdbSeriesImageProvider failed in GetImageInfos for type Series at /mnt/nasdata/Library/Series/Wandavision (2021)
ene 17 16:04:28 think jellyfin[158170]: System.ArgumentNullException: Value cannot be null. (Parameter 'source')
ene 17 16:04:28 think jellyfin[158170]:    at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
ene 17 16:04:28 think jellyfin[158170]:    at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
ene 17 16:04:28 think jellyfin[158170]:    at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, IReadOnlyCollection`1 preferredLanguages, CancellationToken cancellationToken, Nullable`1 type)
```

**Comment by yesimanoob** [comment]
This seems to be back. It's been reproing for me for many weeks now.

`[2021-06-28 22:07:14.253 +09:00] [ERR] [19] MediaBrowser.Providers.Manager.ProviderManager: "TmdbSeriesImageProvider" failed in GetImageInfos for type "Series" at "/sharedfolders/videos/tv/[SHOWNAME]"
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, IReadOnlyCollection`1 preferredLanguages, CancellationToken cancellationToken, Nullable`1 type)`

**Comment by cvium** [comment]
That log line is just a warning and doesn't halt anything.

**Comment by yesimanoob** [comment]
Well, all of my recent new shows are failing to update images after manually being identified. I have no idea what is broken but something is. :(

**Comment by jmaris** [comment]
Also experiencing this issue...

**Comment by Geranospiza** [comment]
Exact same issue here.

**Comment by williamthrilliam** [comment]
Same here. Re-scanning my entire library fixes it.
