### ISSUE TITLE
Missing IPTV channels with 411 channels M3U

### ISSUE THREAD

**Issue by cocool97** [jellyfin/jellyfin#4704]
**Describe the bug**
I've imported a 411 channels IPTV playlist but the WEB & Android applications only display 258 of them. 
There are no pattern in displayed channels, neither in missing channels.

**System (please complete the following information):**
 - OS: [e.g. Debian, Windows] ```Linux server 5.4.0-56-generic #62-Ubuntu SMP Mon Nov 23 19:20:19 UTC 2020 x86_64 GNU/Linux```
 - Virtualization: [e.g. Docker, KVM, LXC] ```Docker```
 - Clients: [Browser, Android, Fire Stick, etc.] ```Web (Firefox) & Android 10 application```
 - Browser: [e.g. Firefox 72, Chrome 80, Safari 13] ```Firefox 83```
 - Jellyfin Version: [e.g. 10.4.3, nightly 20191231] ```10.6.4```
 - Playback: [Direct Play, Remux, Direct Stream, Transcode] 
 - Installed Plugins: [e.g. none, Fanart, Anime, etc.] `None`
 - Reverse Proxy: [e.g. none, nginx, apache, etc.] `None`
 - Base URL: [e.g. none, yes: /example]
 - Networking: [e.g. Host, Bridge/NAT]
 - Storage: [e.g. local, NFS, cloud]

**To Reproduce**

1. Try to import a M3U playlist with more than 411 channels listed. 
2. See if all channels are imported.

**Expected behavior**
All 411 channels are imported and display in the various interfaces (Web, Android application...)

**Logs**
I've set the `DEBUG` mode and seen many things : 
- `grep "Found m3u channel" log_20201206.log | wc -l` returns `411` as expected.
- `grep "has 0 new programs" log_20201206.log | wc -l` returns `411` as expected.
- The file `/cache/[uuid]` contains ```411``` records as expected.
- No errors are shown in logs.

**Other informations**
I unfortunately cannot share the IPTV playlist.
When I open the playlist in VLC there are 411 channels listed.

**Comment by crobibero** [comment]
If possible can you please try 10.7-rc1?

**Comment by cocool97** [comment]
I've just tried this release and the problem keeps appearing...
Any other things I can try / provide to help solving the problem ?
