### ISSUE TITLE
RC - Chromecast still not working

### ISSUE THREAD

**Issue by BaronGreenback** [jellyfin/jellyfin#4707]
Reports from here https://github.com/jellyfin/jellyfin/issues/3852#issuecomment-739429096 saying there's still an issue.

**Comment by tyhawk** [comment]
https://jellyfin.mydomain.com/System/Info/Public:
`{"LocalAddress":"http://10.0.1.19:8096","ServerName":"Jellyfin","Version":"10.7.0","ProductName":"Jellyfin Server","OperatingSystem":"Linux","Id":"8dae97e3b7b64e69a6a8e47afda7d406","StartupWizardCompleted":true}`

... and the Chromecast issue still doesn't seem to be resolved without using the ' known' workarounds.

**Comment by hawken93** [comment]
So is your client on the rc release?

**Comment by tyhawk** [comment]
> So is your client on the rc release? jellyfin-web 10.7.0-rc1 should not look at System/Info/Public. The app might still because it's on stable I believe.

No, de client is on stable. So I guess my confirmation should be taken with a spoon full of salt ;-)

**Comment by idittansikte** [comment]
This is very related or duplicate of #4616

**Comment by idittansikte** [comment]
I got both web and android to work!. Anyhow, I needed to select **unstable** in Chromecast setting in Jellyfin interfaceand also reload the tab in web and **clear the cache** on Jellyfin app in Android application settings. I can confirm it now works behind a reverse proxy without any dirty hacks.
