### ISSUE TITLE
Authorization header parsing is prone to issues

### ISSUE THREAD

**Issue by nielsvanvelzen** [jellyfin/jellyfin#4739]
**Describe the bug**

The current implementation of the authorization header parsing has (at least) the following issues:

- A value can't contain any commas
- A value can't start or end with a doublequote
- A value can't contain special characters
  - HTTP Headers only allow ASCII characters
  - There is no option to encode/decode the values (using base64 or urlencoding)
- When a value contains HTML characters like `<` it will htmlencode them
  - This causes issues when displaying the names in non-web clients
  - Web does not escape the HTML
  - This was some sort of "fix" for XSS issues

**Sources**

https://github.com/jellyfin/jellyfin/blob/79578521b8083588638ecdf70262346055b4db41/Emby.Server.Implementations/HttpServer/Security/AuthorizationContext.cs#L243-L284

https://github.com/jellyfin/jellyfin/blob/79578521b8083588638ecdf70262346055b4db41/Emby.Server.Implementations/HttpServer/Security/AuthorizationContext.cs#L286-L290

**Proposed changes**

Fixing the XSS thingy needs changes in jellyfin-web. The others could be fixed by rewriting the header parsing and allowing some sort of encoding. This could easily be done with backwards compatibility.

**Related issues**
jellyfin/jellyfin-web#718

**Comment by tommasodotNET** [comment]
I was taking a look at this. Since the comma is used to split the authorization headers, another separator character should be chosen.

**Comment by nielsvanvelzen** [comment]
I don't think we can change that part. That would break all existing clients. I don't think we need to change it too, a value can be wrapped in double quotes so we should just not split on the comma inside of quotes.

**Comment by tommasodotNET** [comment]
That makes sense. And is linked to the second point of your list "A value can't start or end with a double quote".

**Comment by nielsvanvelzen** [comment]
Some quick thoughts (I think I mentioned a few in the start post):
- values not wrapped in a double quote are allowed but can not contain special characters or commas
- values wrapped in double quote can contain anything allowed in a header (ASCII), including a comma
  - the current implementation always strips all doublequotes from start and end of string, even multiples. We will use this existing behavior but use it for something useful
- values may be urlencoded (they will always be urldecoded)
  - this one makes sure we can use special charaters
  - this one might change existing behavior slightly but I consider it "worth it" - it won't break anything
- no html encoding happens in server, a client should escape it

**Comment by tommasodotNET** [comment]
I see. So in order to split the values by commas allowing to have commas inside the value would be something like
`parts = authorizationHeader.Split("\",");`

**Comment by nielsvanvelzen** [comment]
I'd say don't use the Split function but write a parser that loops trough all characters instead. That way you can easily add escaping etc.

**Comment by cvium** [comment]
Fixed in https://github.com/jellyfin/jellyfin/pull/4799
