### ISSUE TITLE
Issue Updates

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin#474]
As of the release of 10.0.0, we should review these issues and see what's still open/what can be resolved.

- [x] #410
- [ ] #311
- [ ] #259 
- [ ] jellyfin/jellyfin-docs#12
- [x] #95 
- [x] #36 
- [x] #25 
- [x] jellyfin/jellyfin-ux#3
- [x] #7 
- [x] #359 
- [ ] #331 
- [ ] #149 
- [ ] #87 
- [x] #223 
- [ ] #303

**Comment by joshuaboniface** [comment]
Commented on #411
Closed #95 
Commented on #36 
@JustAMan closed #25 
https://github.com/jellyfin/jellyfin-ux/pull/3 has been merged
Closed #7 
Closed #359 (a while ago)
#331 is still pending final reviews and merging of #335 
#87 is still pending feedback
#223 was closed by owner, but superseded by the total breakage of Chromecasting
#303 should remain until we confirm it's all sorted - some of this could have been related to the above

**Comment by anthonylavado** [comment]
Closing this for now, will move issues to a project board for better grooming.
