### ISSUE TITLE
Library metadata provider selection is not respected

### ISSUE THREAD

**Issue by oddstr13** [jellyfin/jellyfin#4740]
**Describe the bug**
Enabled state for metadata providers in the library settings is ignored

**System (please complete the following information):**
 - OS: Ubuntu
 - Virtualization: none
 - Clients: Browser
 - Browser: Firefox 83
 - Jellyfin Version: 10.7.0-rc1
 - Playback: N/A
 - Installed Plugins: Bookshelf, Cover Art Archive, Fanart, *Kitsu*, Kodi Sync Queue, Playback Reporting, Reports, TV Maze
 - Reverse Proxy: none
 - Base URL: none
 - Networking: N/A
 - Storage: local / samba

**To Reproduce**

1. Disable metadata providers when creating a library
2. See metadata getting fetched from all providers

**Expected behavior**

Only enabled providers getting used.

**Logs**

```
Dec 08 21:47:13 1070L jellyfin[15390]: [21:47:13] [DBG] MediaBrowser.Providers.TV.EpisodeMetadataService: Running EpisodeNfoProvider for /media/foo.mkv
Dec 08 21:47:13 1070L jellyfin[15390]: [21:47:13] [DBG] MediaBrowser.Providers.TV.EpisodeMetadataService: EpisodeNfoProvider returned no metadata for /media/foo.mkv
Dec 08 21:47:13 1070L jellyfin[15390]: [21:47:13] [DBG] MediaBrowser.Providers.TV.EpisodeMetadataService: Running KitsuIoEpisodeProvider for /media/foo.mkv
Dec 08 21:47:13 1070L jellyfin[15390]: [21:47:13] [DBG] MediaBrowser.Providers.TV.EpisodeMetadataService: KitsuIoEpisodeProvider returned no metadata for /media/foo.mkv
Dec 08 21:47:13 1070L jellyfin[15390]: [21:47:13] [DBG] MediaBrowser.Providers.TV.EpisodeMetadataService: Running TvMazeEpisodeProvider for /media/foo.mkv
Dec 08 21:47:13 1070L jellyfin[15390]: [21:47:13] [DBG] Jellyfin.Plugin.TvMaze.Providers.TvMazeEpisodeProvider: [GetMetadata] Starting for foo
Dec 08 21:47:13 1070L jellyfin[15390]: [21:47:13] [DBG] MediaBrowser.Providers.TV.EpisodeMetadataService: Running TmdbEpisodeProvider for /media/foo.mkv
Dec 08 21:47:13 1070L jellyfin[15390]: [21:47:13] [DBG] MediaBrowser.Providers.TV.EpisodeMetadataService: Running OmdbEpisodeProvider for /media/foo.mkv
Dec 08 21:47:13 1070L jellyfin[15390]: [21:47:13] [DBG] MediaBrowser.Providers.TV.EpisodeMetadataService: OmdbEpisodeProvider returned no metadata for /media/foo.mkv
Dec 08 21:47:13 1070L jellyfin[15390]: [21:47:13] [DBG] MediaBrowser.Providers.TV.EpisodeMetadataService: Running TvMazeEpisodeImageProvider for /media/foo.mkv
```

**Screenshots**

![image](https://user-images.githubusercontent.com/638706/101540260-0e283a00-39a0-11eb-8331-f17f8230650a.png)

**Additional context**

https://github.com/jellyfin/jellyfin-plugin-anime/issues/94#issuecomment-740046835

**Comment by EraYaN** [comment]
Reproduced this on jellyfin/jellyfin:unstable@sha256:becd960e63856bf04beac8536453bbfde5c607fe6904cf3c9d40471c5719352c with the Shokofin plugin installed. It seems to be only the Shokofin ImageProvider though for regular shows where Shoko providers were all disabled.
