### ISSUE TITLE
Continue watching for new libraries doesn't show up

### ISSUE THREAD

**Issue by voarsh2** [jellyfin/jellyfin#4746]
OS: Debian
Virtualization: LXC and Docker
Clients: Browser
Browser: Chrome
Jellyfin Version: 10.6.4

**Describe the bug**

Only initial movie/tv shows (initial import) seems to have content show up in continue watching.
Adding places afterwards, content does not show up in continue watching

**To Reproduce**

Add media libraries after initial import.

**Expected behavior**

New folders movies/tv shows, after watching to show up in continue watching

**Logs**

**Screenshots**

**Additional context**

**Comment by crobibero** [comment]
What version of Jellyfin are you using?
What OS is your server running?

Please actually fill out the template.

**Comment by voarsh2** [comment]
Done.

**Comment by cvium** [comment]
@voarsh2 What exactly is the issue? Are you adding more episodes of a show you're watching? But in a _new_ library?
