### ISSUE TITLE
Select only movies that have 2 or more genres

### ISSUE THREAD

**Issue by chaplin89** [jellyfin/jellyfin#4752]
Hi,
is there a way to filter a movie with 2 or more genres?
For example, let's say I want to filter all the movies that are classified both as 'Horror' AND 'Mistery' at the same time, is there a way to do this?

I was not able to do this:
- If I click on 'Movies' -> 'Filter' and select 2 genres, jellyfin will show me all the movies that have at least one of the two
- If I click on 'Genres' -> Select a genre (i.e. 'horror') -> 'Filter' and select another genre, jellyfin will show me again movies that have at least one of categories selected (wich does not make sense for me since I was clicking on a specific genre so I expect to do the filtering only on movies beloging to that specific genre)

Thanks

**Comment by cvium** [comment]
Currently not possible. When we get a chance to rewrite the DB it will be easier. Currently it's an OR expression https://github.com/jellyfin/jellyfin/blob/db530e61f5ac7047f8c5b88b3a30aa17e9253bbc/Emby.Server.Implementations/Data/SqliteItemRepository.cs#L4115 and we're unlikely to change it before the rewrite.

**Comment by VigibotDev** [comment]
> Currently not possible. When we get a chance to rewrite the DB it will be easier. Currently it's an OR expression
> 
> https://github.com/jellyfin/jellyfin/blob/db530e61f5ac7047f8c5b88b3a30aa17e9253bbc/Emby.Server.Implementations/Data/SqliteItemRepository.cs#L4115
> and we're unlikely to change it before the rewrite.

Thanks, I replaced this OR with AND on my version and I love it ! OR is a non-sense for genre, movies we want to filter, not accumulate !

**Comment by BRUHItsABunny** [comment]
I ran into a similar situation but for tags instead of genres. I ended up making a similar local modification by modifying the IL instructions and turn `OR` into `AND` using dnSpy
