### ISSUE TITLE
Unable to load Channel Data from the server on some channels

### ISSUE THREAD

**Issue by cpankonien** [jellyfin/jellyfin#4768]
Certain channels error out with subject error message. I can paste the same stream url as is listed in the .m3u file into VLC and it plays, so the url is known to be good. What specifically does this error message mean? Does it mean that Jellyfin cannot get the stream url data from the .m3u file, or that it can not stream data from the stream url listed in the .m3u file?

**Comment by crobibero** [comment]
Please fill out the issue template so we have a better idea of what the issue is

**Comment by nielsvanvelzen** [comment]
Replaced by #4770
