### ISSUE TITLE
[Feature Request] PGUID and PUID

### ISSUE THREAD

**Issue by bott0r** [jellyfin/jellyfin#477]
Its quite common to set the user and group uid (std is 1000) which runs the docker container/jellyfin within the docker container with an environmental variable. Please consider introducing them.

**Comment by LeoVerto** [comment]
PUID/PGID has been removed in #226 in favor of Docker's `--user`-option.

If you're using Docker Compose, adding the line `user: "$PUID:$PGID"` to the service declaration should function as a drop-in replacement.

**Comment by bott0r** [comment]
Yes, this is  true. Howeber From my limited experience is that when you use the --user option you have to create and chown the folders which you intend to use with (e.g. -v /whatever ) on the hostmachine beforehand, you don't have to do this when utilizing puid or pgid.

**Comment by nvllsvm** [comment]
These environment variables are the implementation details to solving problems. Please clarify the problem you're trying to solve in the title and description then reopen.
