### ISSUE TITLE
"Unable to load Channel Data from the server" on some channels

### ISSUE THREAD

**Issue by cpankonien** [jellyfin/jellyfin#4770]
Certain channels error out with subject error message. I can paste the same stream url as is listed in the .m3u file into VLC and it plays, so the url is known to be good. What specifically does this error message mean? Does it mean that Jellyfin cannot get the stream url data from the .m3u file, or that it can not stream data from the stream url listed in the .m3u file?
**System**
 - OS: Ubuntu 20.04.1LTS
 - Virtualization: none
 - Clients: Roku 4200x, 4260x
 - Browser: n/a
 - Jellyfin Version: 10.6.4
 - Playback: IPTV stream 
 - Installed Plugins: AudioDB, MusicBrainz, OMDb, TheTVDB
 - Reverse Proxy: none

Go to Live TV
Try to play certain channels.
Error "Unable to load Channel Data from server" occurs.

Expected behavior - channel plays normally.

Additional context - What specifically does this error message mean? Does it mean that Jellyfin cannot get the stream url data from the .m3u file, or that Jellyfin is unable to stream data from the stream url listed in the .m3u file?

**Comment by crobibero** [comment]
Does this only happen on the Roku client, or can you also reproduce this with the web player?

**Comment by cpankonien** [comment]
Good point...it also never loads in web player, you just get a spinning circle that never really errors out. I was a network operations technician prior to retirement so I'd really like to know exactly what the error message means.

**Comment by crobibero** [comment]
If you post the server and ffmpeg log I might be able to get an answer for you

**Comment by cpankonien** [comment]
OK, not sure exactly which you need so here is the latest ffmpeg-transcode and what I guess is the server log,let me know if you need something else.
[ffmpeg-transcode-f03b29a5-a823-4d36-8d5a-8db8ed52da3d.txt](https://github.com/jellyfin/jellyfin/files/5683005/ffmpeg-transcode-f03b29a5-a823-4d36-8d5a-8db8ed52da3d.txt)
[jellyfin20201212_002.log](https://github.com/jellyfin/jellyfin/files/5683008/jellyfin20201212_002.log)

**Comment by crobibero** [comment]
I don't see  anything in the log saying that playback failed in either log, so I'm not sure what the issue could be

**Comment by cpankonien** [comment]
Yea, I looked through the logs too, didn't really see anything that looked like an error but then unless it was obvious, I might not see it. Thanks for looking, I appreciate it. The really weird thing is that channels that used to work fine now error out with that error message, so I am at a loss trying to troubleshoot the issue. As I mentioned, the same url works fine when pasted into VLC, so it does not appear to be a network issue, or at the least the url is ok.

**Comment by cpankonien** [comment]
Now unable to watch any live tv at all. I downloaded a new .m3u file from provider with a slightly different channel lineup. Format of .m3u file is exactly the same as the one that used to work. Stream urls checked in vlc, they work fine. Guide data also looks fine. Any troubleshooting ideas welcome!

**Comment by cpankonien** [comment]
updating server to 10.7rc2 seems to have fixed this issue.
