### ISSUE TITLE
Metadata permissions

### ISSUE THREAD

**Issue by Nodens-** [jellyfin/jellyfin#4772]
The files are created with 644 permissions which prevents Medusa from updating them when updating the directory since both Jellyfin and Medusa (and I obviously most other similar software in standard configurations) are running under their own user accounts.
Can permissions be switched to 664 instead so that we have the option to add user to group?
A user setting for permission mask would be ideal but that would entail more work.

EDIT:
Jellyfin version: 10.7.0 installed from RPM
OS Version: Fedora 33
Parent directory permissions: 775 for the entire tree and owned by the user running Medusa and samba group. jellyfin user is a member of the samba group.
Podman/Docker: No.

For the sake of completeness, libraries have directories also on remote FUSE filesystems but the permission conflict has been observed on local btrfs filesystem. On the FUSE side of things permissions should not be an issue as they're overridden anyhow.

**Comment by Extarys** [comment]
Hmm, are you using Docker? I know the linuxserver image have the options to set the user/group id and a umask. Not sure about the official image but you could try.

**Comment by Artiume** [comment]
can you fill out the issue ticket properly please. Is this a  repo install or docker? have you changed the parent directories to 664 so the child files that get created will follow  inheritance policies. this doesn't seem like a bug

**Comment by Nodens-** [comment]
Sorry. My bad for assuming that this was simple and just the default options. I am editing the original post now.

**Comment by andresbott** [comment]
for everyone searching for the same, in my case:
1. use a shared group with rw permissions between services 
2. set the setgid bit on the media root folder (and all child if they don't have it yet) 
3. overwriting the systemd service umask
_/etc/systemd/system/jellyfin.service.d/jellyfin.service.conf_

```
[Service]
UMask=0007
```

**Comment by Anutrix** [comment]
Just faced this issue. Hope, someone can add a commented line like:
```
#UMask=0022
```
in https://github.com/jellyfin/jellyfin-packaging/blob/master/debian/conf/jellyfin.service.conf
