### ISSUE TITLE
server IP autodetect issue with Docker

### ISSUE THREAD

**Issue by toxic0berliner** [jellyfin/jellyfin#4779]
Hello,
I'm using jellyfin 10.6.4 with the Linux server.io docker container. When a client (kodi) scans the network for existing jellyfin servers, it does find the proper server displayName but trying to use it fails since it tries to use an ip in 172.x.x.x which is the internal IP of the container behind the docker NAT. I have proper port forwarding in place, but I need to manually input the proper host IP in the client otherwise it doesn't work.
It would be nice to have some setting in jellyfin admin to tell it what name/host should be used by clients so it can advertise the proper hostname for itself. This can only be a setting input by admin since jellyfin cannot properly discover it, especially if we want to allow users like me to put jellyfin behind a http proxy (I see no way for jellyfin to discover my proxy settings... I don't expect it to, just allow me to setup jellyfin to play nice with it)
In this new field I would input either the docker host IP 192.168.x.x or the FQDN of the proxy.
This way when scanning the network for a server, a client would discover something usable.
This might also help for another issue I have with thumbnails not showing up in kodi when I use the proxy url while they work properly when I use the docker host IP in kodi, but that might be another issue on my proxy settings or in kodi, will investigate further on this, anyway this "public hostname" field might be used for security also to check http host header and discard requests from disallowed proxies for example (opnSense has this on the referer http header for example)
Thanks in advance.

**Comment by Artiume** [comment]
https://jellyfin.org/docs/general/administration/configuration.html#main-configuration-options

this is done at the binary level so it should work for our docker image and lsio as well.  set an env for JELLYFIN_PublishedServerUrl=ip or domain
