### ISSUE TITLE
Podcast Support

### ISSUE THREAD

**Issue by s1mpleman** [jellyfin/jellyfin#479]
Podcast support 

As the title says, add back in podcast support. It would be nice for these to be treated like a first class citizen and not require a plugin. 

Something similar to the current implementation by Airsonic would be nice. 

Possible features: 
Downloadable podcasts into local folder
Auto tagging from RSS feed
Reading of current tags
Allow customizing of tag from interface. Either write back to file, or create nfo.

**Comment by sparky8251** [comment]
Was this previously available in Jellyfin? If so, was it a plugin that is now broken? Just hoping to get some info for whomever decides to tackle this.

**Comment by NotExpectYet** [comment]
Plugin that's now broken from what I remember.

**Comment by JustAMan** [comment]
> As the title says, add back in podcast support. It would be nice for these to be treated like a first class citizen and not require a plugin.

Any reason for adding it to core instead of a plugin? Not saying it won't happen or anything, just curious.

**Comment by s1mpleman** [comment]
I just feel they're part of the whole media centre system. Which to me would be, Movie/TV Show/Music/Podcast/Audiobook. These are all non-interactive means of consuming knowledge or entertainment, Games/eBooks would be interactive media in that sense. As it requires more human input to continue. 

I just believe it would be easier to bake into the next up/on deck type systems if it's treated similarly to movies/music and shows. That's is just my end-user perspective there, no idea if it would make it easier for coding terms, but consumption terms to me certainly would.
