### ISSUE TITLE
Range requests on endpoints

### ISSUE THREAD

**Issue by ferferga** [jellyfin/jellyfin#4797]
Range requests should be possible in our  generic endpoints so clients can request specific parts of the file.

Specially useful for books.

**Comment by erfianugrah** [comment]
Just wanna bump this up for videos as well for direct play, big chonko mp4 can be more readily cached with range requests or multi part

**Comment by sevenrats** [comment]
moved https://features.jellyfin.org/posts/2358/range-requests-on-endpoints
