### ISSUE TITLE
Plugins not working in 10

### ISSUE THREAD

**Issue by BobOkisama** [jellyfin/jellyfin#480]
Plugins like CinemaMode, Trailers and Coverart are no longer working in 10.x. I used the hell out of those three pretty hard, CinemaMode to play my custom intros(pre-rolls), Coverart for the easy to see quality designations, and trailers for.. well trailers ;P

These were working in the docker version before 10.

**Comment by anthonylavado** [comment]
It's believed these stopped working because of a change in logging. Some work is happening in #486, but it's not done yet.

**Comment by anthonylavado** [comment]
Also the TVHeadEnd & IPTV Plugins as noted by pw-h: https://github.com/jellyfin/jellyfin/issues/499#issue-396624785

**Comment by joshuaboniface** [comment]
*All* compiled plugins are broken by the logging change, and there is no easy way to revert it without stripping out all that code which is beneficial for multiple reasons, confirmed by @Bond-009 . If the plugins are Free Software (e.g. if they have a `jellyfin-plugin-*` fork in our org) or are managed by a 3rd party under a Free Software license, we can work on getting them rebuilt for Jellyfin. If they're paid/proprietary, unfortunately there's not much we can do to correct this.

**Comment by PrplHaz4** [comment]
So, to clarify a bit, the work being done by @Bond-009 is to support rebuilding plugins to work with Jellyfin, not to enable existing builds of emby plugins to work, correct?  (to remove the expectation that people will be able to use existing builds of Emby plugins with Jellyfin)

**Comment by Bond-009** [comment]
@PrplHaz4 Correct, It's not worth all the work it would take to making already build plugins compatible.

**Comment by BobOkisama** [comment]
Well, I might be boned then on Cinemamode and coverart....
I guess it would be a good time to ask if we can bake pre-rolls directly into Jellyfin like they are in plex, and perhaps baking in some quick way to see a movies quality from the coverart. I see both those functions as useful. I know, low priority of course.

**Comment by Bond-009** [comment]
We can always try to recreate them, if a lot of people find it important.

**Comment by joshuaboniface** [comment]
I'd actually rather bake *all* the FOSS plugins into the core, and just have them all disabled by default, if that's possible. Then the compilation of them can all be done at build/package time. Not sure how feasible this is at the moment, but is a good future feature project.

Recreating coverart for music seems like a great idea, and something that should likely just be in the core - after all we grab "cover art" for Movies/TV as part of the core functionality. It seems (logically) like that was split out just to provide yet another "premium feature hook". Cinemamode would be a lot harder I think, BUT if we get UI skinning set up as planned, that should be trivial.

**Comment by JustAMan** [comment]
> I'd actually rather bake _all_ the FOSS plugins into the core, and just have them all disabled by default, if that's possible. Then the compilation of them can all be done at build/package time. 

I don't agree on baking all stuff in - the more we have in core the harder it is to maintain it.
Making plugins be compiled by our org along with official builds and published in a org-provided repo is a good thing to do, though.

**Comment by acarroz** [comment]
The Kodi Sync Queue plugin is located [here](https://github.com/LukePulverenti/Emby.Kodi.SyncQueue) and it is GPL. What changes related to logging are needed? I can probably make those.

**Comment by anthonylavado** [comment]
Okay, looks like the reasoning for this is resolved, and this should be replaced by a request for the three plugins (Cinema Mode, Cover Art, and Trailers).

Regarding the Kodi Sync Queue plugin, I believe we already have something going.
