### ISSUE TITLE
Ubuntu bionic repo signature invalid

### ISSUE THREAD

**Issue by mikqu** [jellyfin/jellyfin#4802]
**Describe the bug**
I ran apt update on my server, and get an error at the jellyfin repo.

**System (please complete the following information):**
 - OS: 4.15.0-128-generic #131-Ubuntu SMP Wed Dec 9 06:57:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 VPS on Hetzner

**Logs**
Err:10 https://repo.jellyfin.org/ubuntu bionic InRelease
  The following signatures were invalid: EXPKEYSIG 49023CD01DE21A7B Jellyfin Team <team@jellyfin.org>
Fetched 3,385 B in 1s (2,312 B/s)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://repo.jellyfin.org/ubuntu bionic InRelease: The following signatures were invalid: EXPKEYSIG 49023CD01DE21A7B Jellyfin Team <team@jellyfin.org>
W: Failed to fetch https://repo.jellyfin.org/ubuntu/dists/bionic/InRelease  The following signatures were invalid: EXPKEYSIG 49023CD01DE21A7B Jellyfin Team <team@jellyfin.org>
W: Some index files failed to download. They have been ignored, or old ones used instead.

**Screenshots**

**Additional context**

**Comment by dkanada** [comment]
We cycled the keys for Ubuntu and Debian, so you'll need to pull the new ones. This shouldn't happen again because the new ones have no expiry date.

**Comment by crobibero** [comment]
https://jellyfin.org/posts/jellyfin-apt-key/

**Comment by fengyuclub** [comment]
`wget -O- https://repo.jellyfin.org/jellyfin_team.gpg.key | sudo apt-key add -`  The problem is solved

**Comment by mikqu** [comment]
Thanks, I have fixed it as per your comments.
