### ISSUE TITLE
CBZ comic books opens completely zoomed in, no way to zoom out to read the page.

### ISSUE THREAD

**Issue by mahenkpatel** [jellyfin/jellyfin#4808]
**Describe the bug**
The comic book files opens completely zoomed in and there is no option to reduce the page size resulting in only the top left of page filling up the browser window. No way to read rest of the page.

Happens on CBZ files, did not test on CBR, PDFs work fine.

**System (please complete the following information):**
 - OS: Ubuntu 20.04
 - Virtualization: Docker
 - Clients: Browser, Android App
 - Browser: Firefox Latest
 - Jellyfin Version: 10.7.0
 - Storage: Local

**To Reproduce**
Add comic books with cbz file types.
Read the file from client (browser or android app)

**Expected behavior**
Comic books page should fit the browser window.

**Comment by Artiume** [comment]
@thornbill do you know if this is fixed?

**Comment by thornbill** [comment]
I don't recall seeing this, but I only tested with a simple test file.

**Comment by Suwmlee** [comment]
test in 10.7.0-rc2, still have the bug.... 

![20210101112928](https://user-images.githubusercontent.com/4210529/103433015-ba1e1780-4c24-11eb-8948-b2f0bc4c1fed.png)

**Comment by Lyky35** [comment]
i have the opposite issue its zoomed out too much, and can't zoom in.
![image](https://user-images.githubusercontent.com/36609323/104647933-2d3d7a00-5678-11eb-88d0-86a0b2913604.png)

**Comment by syasidev** [comment]
I have the same problem. Put this code in "Custom css" and it looks like normal.
However, this problem needs to be fixed.

.slider-zoom-container { text-align: center; height: 100%; }
.swiper-slide-img { height: 100%; }
.slideshowSwiperContainer { height: 100%; }

**Comment by thornbill** [comment]
@Lyky35 it looks like that is either the EPUB or PDF reader not CBZ. Feel free to open an issue for it though in https://github.com/jellyfin/jellyfin-web/.
