### ISSUE TITLE
Multiple Servers Support

### ISSUE THREAD

**Issue by screwfaze** [jellyfin/jellyfin#481]
Please add support for multiple servers in different locations.

Thanks

**Comment by cvium** [comment]
Multiple servers how exactly? What's the use case you have in mind?

**Comment by joshuaboniface** [comment]
Yes, please describe the end goal/problem you want to solve. The idea of clustering servers (to provide better transcoding scalability and redundancy) has been discussed previously, however that's not a short-term feature.

**Comment by screwfaze** [comment]
Hi,

First of all I am not expecting this to be done anytime soon so please take your time and do all the important stuff like clients and issues with code. What I would like is the ability to have a master server that has the metadata and slave servers that sync back to it. Most important is playstate so no matter which server a user logs onto they can just continue where they left off.

Thanks

**Comment by screwfaze** [comment]
Hi,

First of all I am not expecting this to be done anytime soon so please take your time and do all the important stuff like clients and issues with code. What I would like is the ability to have a master server that has the metadata and slave servers that sync back to it. Most important is playstate so no matter which server a user logs onto they can just continue where they left off.

Thanks

**Comment by RazeLighter777** [comment]
You could always use a reverse proxy and make a failover system manually if you really need this, but I don't see this as a short-term goal nor a priority.

**Comment by joshuaboniface** [comment]
(Just deleted the dupe comment)

This does seem like a cool idea, and yea it wouldn't be on the roadmap very soon, but as part of the idea of redundant Emby it's pretty much a requirement to have this sort of functionality. Thanks for suggesting it!

@RazeLighter777 I've tried doing that, and it went, poorly to say the least. Probably the best way to implement this is actually the DB work that @sparky8251 has started looking into: once we have the DB implemented as a pluggable module instead of hardcoded SQLite, we could have multiple instances share a database which gets us most of the way there.

**Comment by screwfaze** [comment]
I think this could be very cool the redundancy part would be awesome imagine your server is unreachable for some reason you just get redirected to another server, or based on bandwidth you get connected to the best Server.

**Comment by LogicalPhallacy** [comment]
The work of moving the backend to ORM with an option to use a dedicated SQL server should in theory allow this.

**Comment by Fmstrat** [comment]
@cvium @joshuaboniface @LogicalPhallacy 

Would creating a version of https://github.com/jellyfin/jellyfin/blob/aca4d678a2a6aa46b57837d3a6c1bc9d4c537d7b/Emby.Server.Implementations/Data/BaseSqliteRepository.cs that uses MariaDB/MySQL be a step towards this? Basically modularize that file? If so, maybe I could take a stand at that. I've written a number of apps that synchronize Plex databases via Sqlite and via the API, but would love to switch to a provider I can do this natively with.

The big use case to me is having a remote "master" server and a local server at home rsync'd together and connected to the same database. When at home, have DNS take users to the local server, and internet users on the remote server.

**Comment by anthonylavado** [comment]
@Fmstrat This is what we’re waiting on in order to support other databases: https://github.com/jellyfin/jellyfin/pull/1431

**Comment by Fmstrat** [comment]
@anthonylavado thanks for pointing me there, I've jumped into that conversation. It seems like that is a full overhaul, which looks to be a positive shift forward. With the size of that and the time it will take to test once it is complete, is there any interest in short-term support for MariaDB? As the SQL I see in the app is pretty portable between Sqlite and MariaDB, it doesn't seem like a big undertaking to make a secondary library that mirrors the Sqlite structure.

**Comment by loligans** [comment]
Me and a friend have a JellyFin server and it would be cool if we could connect them together, so that on the frontend client side it combines both of our libraries.

**Comment by Hu1buerger** [comment]
This thread mentioned redundancy and distribution.

Imo distribution would be cool. 

What i imagine is
- n servers take part in a cluster 
- 1 server acts as the master of the cluster
- once a client request a video, the client gets a response to fetch the video from the slave that is carrying the file. That slave will act the same as jellyfin is currently handling the post catalog delivery.

Further:
A master slave design is not necessary. All that would be needed is that all cluster nodes announce their videos they are carrying.

As of today i didn't look into the delivery of content via jellyfin, a link would be appreciated.
But after that not much would be needed to set this up.

The networking would be interesting. Either the master will proxy traffic to the slaves, which would increase the load on the master, or the clients fetch the file directly from the node wan access needed. 
Mostlikely both paths direct and tunnels would sensical.

**Comment by billouetaudrey** [comment]
Hey I vote for multiple server too :) I have mine and friend so can be cool to add both to the client app :)

Thanks
