### ISSUE TITLE
Metadata for person not collected from metadata downloader.

### ISSUE THREAD

**Issue by snakyjake1** [jellyfin/jellyfin#4810]
**Describe the bug**
The metadata for a person is not collected from metadata downloader.

Identifying metadata exists for IMDb Person Id and TheMovieDb Person Id.

Example:
IMDb=nm0814064
TheMovieDb=85838-hope-summers

But Jellyfin isn't downloading the image, or the biography information.

**System (please complete the following information):**
 - OS: Windows
 - Jellyfin Version: Version: 10.6.4

**To Reproduce**
1)  Identify actor.
2)  Refresh metadata.
3)  No image and not biography information was collected/downloaded.

Also:
1)  If I manually Identify using IMDb Person ID nm0814064, no search results are returned.

**Expected behavior**
Expect to see actor's image and full biography from IMDb.

If I click on the IMDb and TheMovieDb links, the links successfully get me to the external website with the information I expect.

**Logs**
No errors.

**Extra Info**
I also notice on other people, the full metadata is not downloaded until I do a manual refresh for each person (the global refresh doesn't do it).
Then I have to wait.
Then I have to manually refresh the webpage to see it.  There's no page auto refresh.

**Comment by cvium** [comment]
We use omdbapi for the imdb data and it does not support searching people. Tmdb is bugged and will be fixed.
