### ISSUE TITLE
Jellyfin cant create .nfo files on samba shares, instead  creates zero size .nfo files

### ISSUE THREAD

**Issue by gerroon** [jellyfin/jellyfin#4826]
**Describe the bug**
It ssounds to me that Jellyfin is not able to create .nfo files in the shared medias folders insetad it just creates 0 size .nfo files while throwing errors.

**System (please complete the following information):**
 - OS: Debian
 - Clients: Browser, Android
 - Browser:Firefox 76, Chrome 80
 - Jellyfin Version: 10.6.0.4 Systemd
 - Storage: local, Samba

I tested this also with Docker on Debian and it still has the same issue. 

**To Reproduce**

Enable .nfo storage in the media library
Set the media library path to a samba share

**Expected behavior**
It should not throw and error

The shares has fully r/w and even jellyfin user can create and remove files from those shares as I tested it manually 

like in those shared media folders

 `su - jellyfin && touch test.file`

Another point is that Jellyfin can actually delete media files from those shared media folders if the user asks for it. SO not sure how there can be a permission issue.

**Logs**

ls from the share (on the samba server
```
 users          0 Dec 19 11:50 #AskZBrush - “How can I load reference images into ZBrush as a separate subtools”.nfo       
users          0 Dec 19 11:50 #AskZBrush - “How can I increase the size of t~s created when using the Extractor Brush”.nfo

```

```
Dec 19 11:51:16 PC jellyfin[2565891]:    at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
Dec 19 11:51:16 PC jellyfin[2565891]:    at System.IO.FileStream.FlushWriteBuffer()
Dec 19 11:51:16 PC jellyfin[2565891]:    at System.IO.FileStream.Dispose(Boolean disposing)
Dec 19 11:51:16 PC jellyfin[2565891]:    at System.IO.Stream.Close()
Dec 19 11:51:16 PC jellyfin[2565891]:    at MediaBrowser.XbmcMetadata.Savers.BaseNfoSaver.SaveToFile(Stream stream, String path)
Dec 19 11:51:16 PC jellyfin[2565891]:    at MediaBrowser.XbmcMetadata.Savers.BaseNfoSaver.Save(BaseItem item, CancellationToken cancellationToken)
Dec 19 11:51:16 PC jellyfin[2565891]:    at MediaBrowser.Providers.Manager.ProviderManager.SaveMetadata(BaseItem item, ItemUpdateType updateType, IEnumerable`1 savers)
Dec 19 11:51:18 PC jellyfin[2565891]: [11:51:18] [ERR] [27] MediaBrowser.Providers.Manager.ProviderManager: Error in metadata saver
Dec 19 11:51:18 PC jellyfin[2565891]: System.UnauthorizedAccessException: Access to the path '/media/PLAY/media/029 ZBrush Surface Noise Dynamesh Boolean [_sShAmCLwMg].nfo' is denied.
Dec 19 11:51:18 PC jellyfin[2565891]:  ---> System.IO.IOException: Permission denied
Dec 19 11:51:18 PC jellyfin[2565891]:    --- End of inner exception stack trace ---
Dec 19 11:51:18 PC jellyfin[2565891]:    at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
Dec 19 11:51:18 PC jellyfin[2565891]:    at System.IO.FileStream.FlushWriteBuffer()
Dec 19 11:51:18 PC jellyfin[2565891]:    at System.IO.FileStream.Dispose(Boolean disposing)
Dec 19 11:51:18 PC jellyfin[2565891]:    at System.IO.Stream.Close()
Dec 19 11:51:18 PC jellyfin[2565891]:    at MediaBrowser.XbmcMetadata.Savers.BaseNfoSaver.SaveToFile(Stream stream, String path)
Dec 19 11:51:18 PC jellyfin[2565891]:    at MediaBrowser.XbmcMetadata.Savers.BaseNfoSaver.Save(BaseItem item, CancellationToken cancellationToken)
Dec 19 11:51:18 PC jellyfin[2565891]:    at MediaBrowser.Providers.Manager.ProviderManager.SaveMetadata(BaseItem item, ItemUpdateType updateType, IEnumerable`1 savers)
Dec 19 11:51:19 PC jellyfin[2565891]: [11:51:19] [ERR] [16] MediaBrowser.Providers.Manager.ProviderManager: Error in metadata saver
Dec 19 11:51:19 PC jellyfin[2565891]: System.UnauthorizedAccessException: Access to the path '/media/PLAY/media/03 - OpenCV with Python - Imshow in OpenCV and Matplotlib.nfo' is denied.
Dec 19 11:51:19 PC jellyfin[2565891]:  ---> System.IO.IOException: Permission denied
Dec 19 11:51:19 PC jellyfin[2565891]:    --- End of inner exception stack trace ---
Dec 19 11:51:19 PC jellyfin[2565891]:    at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
Dec 19 11:51:19 PC jellyfin[2565891]:    at System.IO.FileStream.FlushWriteBuffer()
Dec 19 11:51:19 PC jellyfin[2565891]:    at System.IO.FileStream.Dispose(Boolean disposing)
Dec 19 11:51:19 PC jellyfin[2565891]:    at System.IO.Stream.Close()
Dec 19 11:51:19 PC jellyfin[2565891]:    at MediaBrowser.XbmcMetadata.Savers.BaseNfoSaver.SaveToFile(Stream stream, String path)
Dec 19 11:51:19 PC jellyfin[2565891]:    at MediaBrowser.XbmcMetadata.Savers.BaseNfoSaver.Save(BaseItem item, CancellationToken cancellationToken)
Dec 19 11:51:19 PC jellyfin[2565891]:    at MediaBrowser.Providers.Manager.ProviderManager.SaveMetadata(BaseItem item, ItemUpdateType updateType, IEnumerable`1 savers)
^C



```

**Comment by AlexandreFoley** [comment]
I'm having the same problem on manjaro, there's no variation of permissions that will make jellyfin accept to write in a nfo file.
The permissions on my cifs mounted media library is currently 777 for both files and folders...
Whatever the problem might be, it's not a lack of permissions.

**Comment by AlexandreFoley** [comment]
I suspect jellyfin is more generally wonky with the writes on the samba filesystem. the jpeg downloaded by jellyfin also show as 0 size files.

This is puzzling as the web interface display images. Could jellyfin be storing those somewhere else as well?

**Comment by hawken93** [comment]
Jellyfin does store a whole bunch of stuff locally, it's just in those few cases where the user wants it that it does writes to the library. My jellyfin instance has read only access on purpose.

It's weird that it gives unauthorized access issues in this case. There are a few things that usually can affect this:
* systemd service can have statements that locks down the process further.
* selinux or apparmor

If you could provide details about how this is set up on your system it would be very helpful.

**Comment by AlexandreFoley** [comment]
Apparmor isn't supported on Manjaro, and i have not install SElinux.

**Comment by Artiume** [comment]
What OS is hosting the samba share?

**Comment by AlexandreFoley** [comment]
regarding more details:

OS: manjaro
clients: browser
browser: firefox 84+, chromium
Jellyfin Version: 10.6.4, Systemd
storage: local and samba
SElinux: no
apparmor: no

The samba is loaded on startup by the following entry in fstab
`//192.168.0.174/Media        /home/jellyfin     cifs    credentials=/mnt/media_cred,uid=960,gid=985,file_mode=0777,dir_mode=0777 0 0`

the jellyfin folder where the share is mounted currently has permissions set to 777
/home has permissions 755 (standard)
The samba mount is mounted using the credentials of a user that has full control. The server uses ACL.
It is mounted as owned by the jellyfin user (uid=960), and group that grant access to my admin user (jellyfin is also member)

My current permissions are much more permissive than i like, it is in trying to get jellyfin to behave that i set it so.

**Comment by AlexandreFoley** [comment]
@Artiume Trunas 12.0-U1 in my case

**Comment by AlexandreFoley** [comment]
@hawken93 Regarding systemd, should i look anywhere beyond the jellyfin service file?

I took a glance into it the jellyfin.service, nothing that affect permissions beyond asigning the service to the user jellyfin.

**Comment by gerroon** [comment]
My Samba server is Debian Testing, Jellyfin is running under Docker. 

Like others noted this cant be a permission issue given Jellyfin can remove the video files from the same samba locations.

**Comment by gerroon** [comment]
Bug or not?

**Comment by gerroon** [comment]
It looks like this has been  reported in the forum as well

https://forum.jellyfin.org/t/user-group-permissions/2367

**Comment by kn-f** [comment]
Seems like a common issue in .NET core: [(https://github.com/dotnet/runtime/issues/42790)]
Looks like that if you use _FileShare.None_ instead of _FileShare.Read_ when creating the stream, it will work.
This is invoked in file [BaseNfoSaver.cs](https://github.com/jellyfin/jellyfin/blob/cc92f7afe599c9d1c4bfa35a67f6e89d1a790107/MediaBrowser.XbmcMetadata/Savers/BaseNfoSaver.cs#L209) line 209.
Unfortunately I'm no .NET developer so I cannot check but I'd appreciate if someone could, thank you!

**Comment by BaronGreenback** [comment]
If it is indeed this issue, then there are bigger ramifications than just this - ImageSaver, AlbumProvider, ArtistProvider, StudioImageProvider etc.

**Comment by AlexandreFoley** [comment]
As I reported before, images that jellyfin tried to save on the share suffered the same fate as the .nfo.

**Comment by BaronGreenback** [comment]
Just come across this https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=902431.

Although not exact - describes a similar issue - can create a file, but can't read it back.

**Comment by AlexandreFoley** [comment]
Nothing but jellyfin has trouble writing to the share. I don't think it's related at all.

**Comment by gerroon** [comment]
I would like to reiterate that this issue that Jellyfin has is not limited to CIFS (Samba), I have the same issue with NFS because I thought it was limited to CIFS initially. Then I tried it with NFS with the same outcome.

**Comment by BaronGreenback** [comment]
@gerroon JF uses the standard dotnet functions to create the file - this is no magic code - it's a 1 line command that is replicated throughout the system.

The thing we need to discover, is why is it not working here when it's working in other places.

**Comment by AlexandreFoley** [comment]
@BaronGreenback I'm fairly sure the answer is the issue in dotnet that kn-f linked to. Instead of keeping looking for something else to blame, perhaps our energy would be better spent trying to figure a test that could tell us whether it is the case.

> this is no magic code

Yeah.. Nobody said it was.

**Comment by BaronGreenback** [comment]
Can someone try https://github.com/jellyfin/jellyfin/pull/4985 and post the relevant part of the logs please?

**Comment by BaronGreenback** [comment]
Additional question: Have you got any system watchers in place and running?

Are there any "watching directories" entries in the log?

**Comment by AlexandreFoley** [comment]
I have entries of that sort in jellyfin's log:

`[2021-01-08 10:12:59.626 -05:00] [INF] [4] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory /home/jellyfin/Media/TV
[2021-01-08 10:12:59.630 -05:00] [INF] [88] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory /home/jellyfin/Media/Films
[2021-01-08 10:13:00.520 -05:00] [INF] [93] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory /home/jellyfin/Media/Musique
[2021-01-08 10:13:00.530 -05:00] [INF] [26] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory /home/jellyfin/Media/Livres
`
Sometimes followed by entries from the kodisyncqueue plugin

I'll setup a test system for that commit and try it out.

**Comment by BaronGreenback** [comment]
Thanks - starting to have an inkling that the watcher is detecting the file being truncated pre-write and is then causing a lock when it tries to read it. Quite a bit of stuff online about this being an issue - as the watcher class doesn't wait until the file is completely written before kicking in.

Would also explain why this isn't happening when we use this function elsewhere.

**Comment by gerroon** [comment]
I have 2 libs (onn the same samba share) one has realtime monitoring enabled and the otherone does not and both has the same .nfo issue.

**Comment by AlexandreFoley** [comment]
I'm not getting access denied error on my test setup. the nfo *and jpeg* are saving correctly to the share.
Is that expected with the changes you made BaronGreenback?

Here's a log output if i refresh the metadata when .nfo are already present:
[log_nfo_present.txt](https://github.com/jellyfin/jellyfin/files/5791511/log_nfo_present.txt)
And the log when i refresh the metadata and no NFO are present.
[log_createnfo.txt](https://github.com/jellyfin/jellyfin/files/5791512/log_createnfo.txt)

**Comment by BaronGreenback** [comment]
I excluded the folder from the SystemWatcher - if i re-add it, can you download and re-check. 

That way we can be 100% sure that that is the root cause?

**Comment by BaronGreenback** [comment]
Your path to ffmpeg isn't set - so ffmprobe isn't running.

**Comment by AlexandreFoley** [comment]
Sure, i can try another commit. Which is it that I should download?

**Comment by BaronGreenback** [comment]
Same one if you can - you'll need to redownload it.

https://github.com/jellyfin/jellyfin/pull/4985/files

I've commented out the watching code - if we've found the issue - this should error.

**Comment by AlexandreFoley** [comment]
We'll have to disregard my previous logs. Seems debian on WSL is not subject to that problem, I can't reproduce with jellyfin 10.6.4 on it. I'll have to setup a new test machine.

**Comment by AlexandreFoley** [comment]
Alright, so I have setup a docker running debian testing on my manjaro machine. This time it reproduce the problematic behavior with jellyfin 10.6. 
Once again, everything within the cifs mount has 777 permision (everything and everyone has read/write). The Jellyfin server is owned by the user that launched it, and the mounted folder is owned by that same user.

So running the commit 13178d3 I get the following messages in the log when updating the metadata if no nfo or jpg is present: [log1.txt](https://github.com/jellyfin/jellyfin/files/5812091/log1.txt)
It creates size 0 nfo and jpg files


And i get [log2.txt](https://github.com/jellyfin/jellyfin/files/5812092/log2.txt) if i scan the library again, with the size zero files present.


My apologies for taking so long, I tried to run the jellyfin server from source directly on manjaro without success, and i had to repair a botched kernel update..

**Comment by kn-f** [comment]
@BaronGreenback @AlexandreFoley I've tried to compile the source (main branch) on a virtualbox machine with no luck.
It's stuck at the wizard tutorial trying to load the languages.

If I could get some help on this I'd be more than happy to do some testing as well.

**Comment by BaronGreenback** [comment]
@AlexandreFoley That error is caused by the system not knowing where FFMPeg is installed. 

There is currently an open bug, that if the system hasn't got the correct version it isn't detected (https://github.com/jellyfin/jellyfin/pull/4963), so it might have to be registered manually.

The setting is in **encoding.xml** (I'm running windows)

```
<EncoderAppPath>C:\Program Files\Jellyfin\Server\ffmpeg.exe</EncoderAppPath>
<EncoderAppPathDisplay>C:\Program Files\Jellyfin\Server\ffmpeg.exe</EncoderAppPathDisplay>
```

**Comment by BaronGreenback** [comment]
@kn-f Thought we'd fixed that one. Could you open up a new issue and upload your logs so we can take a look?

**Comment by AlexandreFoley** [comment]
Yeah I forgot to install ffmpeg again.
Did that, no change in behavior.
[log1.txt](https://github.com/jellyfin/jellyfin/files/5815028/log1.txt)
[log2.txt](https://github.com/jellyfin/jellyfin/files/5815031/log2.txt)

**Comment by kn-f** [comment]
> @kn-f Thought we'd fixed that one. Could you open up a new issue and upload your logs so we can take a look?

@BaronGreenback thanks, I've just opened issue #5022

**Comment by kn-f** [comment]
@BaronGreenback @gerron Finally I managed to setup a test environment and compile the code.
Effectively changing the access permission files are being created properly.
So it seems that it's more an issue on DOTNET rather than on anything else.

**Comment by gerroon** [comment]
> @BaronGreenback @gerron Finally I managed to setup a test environment and compile the code.
> Effectively changing the access permission files are being created properly.
> So it seems that it's more an issue on DOTNET rather than on anything else.

Thanks for testing it. It was pretty clear to me that it was some code somewhere in Jellyfin, becasue it did not make any sense whatsoever.

**Comment by kn-f** [comment]
> > @BaronGreenback @gerron Finally I managed to setup a test environment and compile the code.
> > Effectively changing the access permission files are being created properly.
> > So it seems that it's more an issue on DOTNET rather than on anything else.
> 
> Thanks for testing it. It was pretty clear to me that it was some code somewhere in Jellyfin, becasue it did not make any sense whatsoever.

@gerroon Strictly speaking this is not a Jellyfin bug, it's a .NET bug. Unfortunately Jellyfin (like other software) is facing the consequences.

**Comment by gerroon** [comment]
Sure, I was not implying that JF devs were at fault here. However this is unfortunately a quite sucky bug whether it is from JF or NET. I hope that JF devs can find a work around.

**Comment by gerron** [comment]
I think I was accidentally tagged in this comment thread.

**Comment by BaronGreenback** [comment]
@kn-f Could you try this PR?

https://github.com/jellyfin/jellyfin/pull/5106
