### ISSUE TITLE
Spinning circle on edit profile page.  404 from server

### ISSUE THREAD

**Issue by dinki** [jellyfin/jellyfin#483]
I'm looking to change my profile picture.  Went to the profile page (myprofile.html) and I see the form but am greeted with a spinning circle.  I brought this up in chat and @sparky8251 confirmed he sees it too.  Pulled this from his log:

`Source map error: request failed with status 404 Resource URL: http://192.168.1.41:8096/web/bower_components/hlsjs/dist/hls.min.js?v=10.0.0.0`

@LeoVerto mentioned:

> interesting how the version string is appended as a GET parameter. seeing as we haven't really changed that version before that might very well be the cause

**Comment by KristupasSavickas** [comment]
I'veused Emby for a about a year and the spinning circle thingy still haunts me in my sleep. Something should be done about it, as it keeps infinitely spinning way more than it should without producing error messages visible to the user in any kind.

**Comment by sparky8251** [comment]
Well, in this particular case its a regression. We certainly can look to fixing the other endless loading circles, but we will need folks to find a way to reproduce it.

No reproduction means it'll be much much harder (if not impossible) to fix.

Working on a fix for the regression now!

**Comment by Rudy-MS** [comment]
Can confirm this on my end. I had a emby server 3.5.X that I could easily change the profile pic. Did a Jellyfin upgrade from Emby....still worked just fine. Did a "apt purge jellyfin" from my Debian server to do clean install of Emby for troubleshooting another issue...still worked. After doing that I did a clean install of Jellyfin and all of sudden I couldn't change the profile picture. Got the dreaded spinning circle.
