### ISSUE TITLE
DLNA PlayTo partially broken

### ISSUE THREAD

**Issue by Keridos** [jellyfin/jellyfin#4832]
**Describe the bug**
DLNA-PlayTo is partially broken on both 10.6 and 10.7.2 on my Samsung Smart TV

- [x]  on 10.7 Jellyfin takes a long time to even find ia playto device -> BaronGreenback found the bug and fixed it in his dev env
- [ ] Forwarding, skipping time does not work -> resets time to start of movie
- [ ] pausing broken -> pauses correctly but on resume fast forward of video from start to current position, audio seems fine
- [ ] Playback sometimes does not start at all
- [ ] Playback starts really really slow (showing loading circle on TV for 2 minutes f.ex.)

**System (please complete the following information):**
 - OS: debian
 - Virtualization: Docker
 - Clients: Samsung Smart TV Q82(*)
 - Browser: Firefox 83
 - Jellyfin Version: 10.6.4/10.7-rc1/10.7.2
 - Playback: Transcode/DirectPlay
 - Installed Plugins:  None
 - Reverse Proxy: traefik
 - Base URL: yes: http(s)://jellyfin.domain.tld
 - Networking: Host
 - Storage local

**To Reproduce**

1. try to select the TV in Playto device selection
2. When its selected successfully try to play movie, one of several things happens:
3. A: the movie playback does not start at all. No indication of any playback on either the TV or jellyfin
3. B: the movie starts successfully
3. C: the TV shows a loading circle for a while (few minutes) and maybe the playback starts
4. If it started playback, try fast forwarding (does nothing) or skipping time: that always resets the time to 0:00 effectively restarting the playback.

**Expected behavior**
DLNA PlayTo should work fine.

**Logs**
TODO: Grab logs for all the different failing things

**Additional context**
This is likely several bugs affecting the system all at once. I created this to track the progress on the DLNA PlayTo features so please leave it open, this Issue will likely be heavily updated by me in the future.

@BaronGreenback is working on a set of plugins for 10.8 replacing the old DLNA system. As 10.7 seems to be nearing the release I'd like to focus my testing more on his work.

(*) this very likely affects a lot more devices than just the TV I tested it with.

**Comment by louregni** [comment]
Hello, it seems I have the same issue. But I discovered something, when I play a movie from LG TV using DLNA, in the logs of jellyfin it always transcode using ffmpeg.

But I disabled all transcoding stuff in the jellyfin user profile used by the TV.
So ffmpeg start to transcode for no reason, and I can't forward the media.

**Comment by BaronGreenback** [comment]
This **may** fix the intermittent playback if it was caused by an invalid character in the xml request.

https://github.com/jellyfin/jellyfin/pull/5025

**Comment by Keridos** [comment]
bump, this issue is still active
