### ISSUE TITLE
Cannot add shared folder in Jellyfin

### ISSUE THREAD

**Issue by kauniss** [jellyfin/jellyfin#4834]
Issue: Cannot add shared folder in Jellyfin (yes I have checked all current/closed issues without any help)

OS: macOS Catalina 10.15.7
Jellyfin 10.6.4 (Darwin, x64), latest stable release
Installed where: local (iMac main SSD drive)
Shared folder location: local (iMac main SSD drive)
How I installed Jellyfin: Downloaded installer dmg from https://repo.jellyfin.org/releases/server/macos/stable/ 
What I’m ultimately trying to do: Get Jellyfin4Kodi running properly using native mode.

I am trying to set up my shared folder (beware: never done this before). I have jellyfin and Kodi installed, have followed all steps in your official Kodi guidance up until this specific part (adding shared drive in jellyfin). So I’ve created a shared folder in macOS, verified it works as I can access it from another computer (smb://192.168.xx.xxx\folder). But Jellyfin won’t recognise this as I try to add it in “optional shared folder”, as instructed is necessary to get Kodi running with Jellyfin in native mode: I only get “the path could not be found”. I’ve tried writing it as instructed in your Kodi documents (https://jellyfin.org/docs/general/clients/kodi.html), ie.: “\\192.168.xx.xxx\folder”. 

What am I missing?

Others have mentioned this issue but not specifically on Mac. Apparently I need to somehow mount the shared drive to Jellyfin, but I do not know how to do this.

Please help?

**Comment by kauniss** [comment]
I may have found a work-around. In the webUI: Adding the folder pathway first, clicking OK and saving, then re-entering and adding the shared folder path: //user:password@192.168.xx.xxx/folder. Adding these values im any other way did not work for me as it got stuck loading.

**Comment by NaturalBornCamper** [comment]
Shouldn't this be opened instead of closed if it's a known bug? I'm having this issue as well, cannot add sources shared over Samba, nothing happens.
Tested on Emby and Plex, works perfectly so it's not a network issue

**Comment by cvium** [comment]
We don't support network shares. You have to mount them to the filesystem to use them in jellyfin.

**Comment by NaturalBornCamper** [comment]
> We don't support network shares. You have to mount them to the filesystem to use them in jellyfin.

I thought that might be the case and I did end up mounting them, however I was wondering why there was the following option if network shares are not supported:
![image](https://user-images.githubusercontent.com/1697306/161468968-09045e13-58ed-4200-91c1-8f8cc2a2170d.png)

And I suppose it can't be used to play the files directly from clients since they are encoded anyways

**Comment by cch85** [comment]
That is not for mounting a remote share in Jellyfin, this is for providing the shared network path to a Jellyfin client (i.e Kodo) dso it access to the media directly instead through jellyfin.

**Comment by wkearney99** [comment]
an alternative is to use your filesystem to mount them.  with an entry in /etc/fstab like this one:
`//192.168.x.x/sharename/directory /mnt/network/servername/sharename/directory cifs credentials=/etc/samba/.credentials/.servername,iocharset=utf8,vers=2.1,sec=ntlmssp,nosetuids,uid=jellyfin,gid=media,_netdev 0 0`

Note this takes the added step of NOT putting your samba credentials in the fstab file.  

Then you're just telling JF to read the library from the local "/mnt/network/servername/sharename/directory" location.  Doesn't have to use that name, you can have fstab mount the share onto any existing path, I just find it handy to put network share mounts in /mnt/network

**Comment by srussell1979** [comment]
Bill, is there any way I can pick your brain about network shared library with jellyfin. I have been beating my head against the wall trying to figure it out.

**Comment by wkearney99** [comment]
Sure, what are you trying to do, and how is it failing?

As I mentioned above, I use the underlying operating system to mount the network shares as parts of the local filesystem.  That lets JF add them as if all the media was local on the box.

The key is making a fake mount point on the local drive, then overlaying that with a network mount.

I have a 'fake' path at /mnt/network/servername/sharename, created using 'mkdir -p /mnt/network/servername/sharename'  where servername is the name of my network fileserver, and sharename is the shared folder on that server.  So if my server was called "media" and the expose shared folder was called "videos" then I'd use /mnt/network/media/videos as the fake path mounting point.  

Note, I'm saying 'fake' here even though it is a real path of folders on the local filesystem.  I put them under /mnt as that's a common place for mount points.  Using /mnt/network makes it mentally "neater" for long term support when I come looking at this configuration at a later date.

Ok, so with this fake mount point ready to go, I then use the /etc/fstab file to handle overlaying the actual network share on another machine onto this particular part of the local filesystem.  I'm putting the 'videos' share from the 'media' server onto the /mnt/network/media/videos part of the filesystem.

This means that any folders within the \\media\videos share will now show up as folders under the /mnt/network/media/videos folder.  Get it?  Now any/all folders like \\media\videos\movies could be seen like /mnt/network/media/videos/movies to Jellyfin.

The rest of the /etc/fstab parameters are telling the operating system how to be specific about how the share gets mounted and file access is managed.  For more info on this do some searching on /etc/fstab CIFS and SAMBA.

**Comment by wkearney99** [comment]
Oh, and github is manging double leading backslash \ characters I used above to note the \ \ media \ videos share. (lose the space between \ \ )

**Comment by srussell1979** [comment]
hello, thank you for the responce.  I finally have the shares working but I was unable to get the shares to load back up after a reboot.  Can you let me know what I have done wrong please.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
