### ISSUE TITLE
Can't support new version of Sony ARW raw images 

### ISSUE THREAD

**Issue by gfeng85** [jellyfin/jellyfin#4843]
Can't support new version of Sony ARW raw images (e.g token by Sony a7m3 Camera).
Old version of ARW can support well (e.g token by Sony a7r2 Camera).

**Comment by crobibero** [comment]
Please fill out the issue template so we can have some sort of idea of what you're trying to do.

**Comment by Artiume** [comment]
Does it recognize that the files are ARW images and fails to render them or are they not found as photos? Request a sample file.

**Comment by gfeng85** [comment]
> Does it recognize that the files are ARW images and fails to render them or are they not found as photos? Request a sample file.

They can find as photos but fails to render.
when I preview the arw file ,console windows can see this
```


Non-success codec result: InvalidInput
Jellyfin.Drawing.Skia.SkiaCodecException: Exception of type 'Jellyfin.Drawing.Skia.SkiaCodecException' was thrown.
   at Jellyfin.Drawing.Skia.SkiaHelper.EnsureSuccess(SKCodecResult result)
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info)
   at Emby.Server.Implementations.Dto.DtoService.GetPrimaryImageAspectRatio(BaseItem item)
```
Sample file is too big to upload(80MB,because it's raw image file of camera). I can send e-mail to you

**Comment by crobibero** [comment]
Looks like you already created the upstream issue https://github.com/mono/SkiaSharp/issues/1565. 
I don't think this is something we can fix

**Comment by gfeng85** [comment]
> Does it recognize that the files are ARW images and fails to render them or are they not found as photos? Request a sample file.
i upload example files here
https://github.com/gfeng85/BugsForSkiaSharp
