### ISSUE TITLE
ios connection issue

### ISSUE THREAD

**Issue by Jargo56** [jellyfin/jellyfin#4851]
**Describe the bug**

I have Jellyfin setup with a subdomain. I am using a reverse proxy (swag) to connect to the Jellyfin docker on my unraid server.  When I connect to the URL I setup through a web browser remotely it connects fine.  When I put the same URL into the IOS app it can't find the server. I have not tested the Roku app, yet.

**System (please complete the following information):**
 - OS: [e.g. Debian, Windows] Unraid
 - Virtualization: [e.g. Docker, KVM, LXC] Docker
 - Clients: [Browser, Android, Fire Stick, etc.] Chrome (Works) latest iOS version.
 - Browser: [e.g. Firefox 72, Chrome 80, Safari 13]
 - Jellyfin Version: [e.g. 10.4.3, nightly 20191231]  10.6.4
 - Playback: [Direct Play, Remux, Direct Stream, Transcode] 
 - Installed Plugins: [e.g. none, Fanart, Anime, etc.] none
 - Reverse Proxy: [e.g. none, nginx, apache, etc.] nginx(swag)
 - Base URL: [e.g. none, yes: /example] jellyfin.mydomain.net
 - Networking: [e.g. Host, Bridge/NAT]
 - Storage: [e.g. local, NFS, cloud]

**To Reproduce**

**Expected behavior**

**Logs**

**Screenshots**

**Additional context**

**Comment by Jargo56** [comment]
Error on my end with proxy

**Comment by Joeharrison94** [comment]
> Error on my end with proxy

@Jargo56 I am having this issue with swag, all apps work but not ios, any ideas on how to fix ?
