### ISSUE TITLE
NVENC failing on 10.6.4 - any file that needs transcoding

### ISSUE THREAD

**Issue by lravelo** [jellyfin/jellyfin#4858]
**Media Info of the file**
﻿General
Unique ID                                : 319443384262385344712349426288976923564 (0xF0528ED46ADC1C2D97751D3B0BC70BAC)
Complete name                            : Ray Donovan - S02E09 - Snowflake.mkv
Format                                   : Matroska
Format version                           : Version 2
File size                                : 433 MiB
Duration                                 : 55 min 17 s
Overall bit rate                         : 1 096 kb/s
Writing application                      : HandBrake 0.10.1 2015030800
Writing library                          : Lavf55.12.0

Video
ID                                       : 1
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main@L4@Main
Codec ID                                 : V_MPEGH/ISO/HEVC
Duration                                 : 55 min 17 s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Writing library                          : x265 1.5:[Windows][GCC 4.9.0][64 bit]
Encoding settings                        : wpp / ctu=64 / tu-intra-depth=1 / tu-inter-depth=1 / me=1 / subme=2 / merange=57 / no-rect / no-amp / max-merge=2 / temporal-mvp / no-early-skip / no-fast-cbf / rdpenalty=0 / no-tskip / no-tskip-fast / strong-intra-smoothing / no-lossless / no-cu-lossless / no-constrained-intra / fast-intra / open-gop / interlace=0 / keyint=240 / min-keyint=24 / scenecut=40 / rc-lookahead=15 / bframes=4 / bframe-bias=0 / b-adapt=0 / ref=2 / weightp / no-weightb / aq-mode=1 / aq-strength=1.00 / cbqpoffs=0 / crqpoffs=0 / rd=2 / psy-rd=0.30 / psy-rdoq=0.00 / signhide / lft / sao / no-sao-non-deblock / b-pyramid / cutree / rc=2 / pass / bitrate=900 / qcomp=0.60 / qpmin=0 / qpmax=51 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / ipratio=1.40 / pbratio=1.30
Default                                  : Yes
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709
Duration_Source                          : General_Duration

Audio
ID                                       : 2
Format                                   : AAC LC SBR
Format/Info                              : Advanced Audio Codec Low Complexity with Spectral Band Replication
Commercial name                          : HE-AAC
Format settings                          : NBC
Codec ID                                 : A_AAC-5
Duration                                 : 55 min 17 s
Channel(s)                               : 6 channels
Channel layout                           : C L R Ls Rs LFE
Sampling rate                            : 48.0 kHz
Frame rate                               : 23.438 FPS (2048 SPF)
Compression mode                         : Lossy
Delay relative to video                  : -105 ms
Title                                    : Surround
Language                                 : English
Default                                  : Yes
Forced                                   : No
Duration_Source                          : General_Duration

Text 1
ID                                       : 3
Format                                   : ASS
Codec ID                                 : S_TEXT/ASS
Codec ID/Info                            : Advanced Sub Station Alpha
Compression mode                         : Lossless
Language                                 : English
Default                                  : No
Forced                                   : No

Text 2
ID                                       : 4
Format                                   : ASS
Codec ID                                 : S_TEXT/ASS
Codec ID/Info                            : Advanced Sub Station Alpha
Compression mode                         : Lossless
Language                                 : English
Default                                  : No
Forced                                   : No

Menu
00:00:00.000                             : :00:00:00.000
00:01:52.320                             : :00:01:52.112
00:11:54.005                             : :00:11:46.581
00:23:55.809                             : :00:23:45.716
00:32:21.564                             : :00:32:21.481
00:43:03.455                             : :00:43:03.372
00:53:22.407                             : :00:53:15.609

**Logs**

```
[2020-12-23 22:31:15.881 -05:00] [INF] [148] MediaBrowser.Api.Playback.Hls.DynamicHlsService: /usr/lib/jellyfin-ffmpeg/ffmpeg -i file:"/media/TV/Ray Donovan/Season 2/Ray Donovan - S02E09 - Snowflake.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_nvenc -pix_fmt yuv420p -preset slow -b:v 5478930 -maxrate 5478930 -bufsize 10957860 -profile:v high  -g 72 -keyint_min 72 -sc_threshold 0 -vf "scale=trunc(min(max(iw\,ih*dar)\,1920)/2)*2:trunc(ow/dar/2)*2" -start_at_zero -vsync -1 -codec:a:0 libmp3lame -ac 2 -ab 320000 -af "volume=2" -copyts -avoid_negative_ts disabled -f hls -max_delay 5000000 -hls_time 3 -individual_header_trailer 0 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/config/transcodes/9ec27cccdac2e14d063f2b0e0da37357%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/config/transcodes/9ec27cccdac2e14d063f2b0e0da37357.m3u8"
[2020-12-23 22:31:15.992 -05:00] [ERR] [35] MediaBrowser.Api.Playback.Hls.DynamicHlsService: FFMpeg exited with code 1
[2020-12-23 22:31:16.001 -05:00] [WRN] [35] MediaBrowser.Api.Playback.Hls.DynamicHlsService: cannot serve "/config/transcodes/9ec27cccdac2e14d063f2b0e0da373570.ts" as transcoding quit before we got there
[2020-12-23 22:31:16.002 -05:00] [ERR] [35] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Could not find file '/config/transcodes/9ec27cccdac2e14d063f2b0e0da373570.ts'". URL: "http://192.168.1.*:8096/videos/d1b5bf0f-ee3f-cdf0-b4fc-25a2835f1bee/hls1/main/0.ts?DeviceId=TW96aWxsYS81LjAgKFgxMTsgVWJ1bnR1OyBMaW51eCB4ODZfNjQ7IHJ2OjgwLjApIEdlY2tvLzIwMTAwMTAxIEZpcmVmb3gvODAuMHwxNTk5NTY3OTU1NDE5&MediaSourceId=d1b5bf0fee3fcdf0b4fc25a2835f1bee&VideoCodec=h264&AudioCodec=mp3,aac&AudioStreamIndex=1&VideoBitrate=139680000&AudioBitrate=320000&PlaySessionId=6dd71c500b8f45299c79e5711dab2b48&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=4904573c08a1f45f0432c4e6a8c33dfb&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51&h264-deinterlace=true&TranscodeReasons=VideoCodecNotSupported&allowVideoStreamCopy=false&allowAudioStreamCopy=false,false"
```

**FFmpeg Logs**
```
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (native) -> h264 (h264_nvenc))
  Stream #0:2 -> #0:1 (ac3 (native) -> mp3 (libmp3lame))
Press [q] to stop, [?] for help
[h264_nvenc @ 0x56451ccf8740] dl_fn->cuda_dl->cuInit(0) failed -> CUDA_ERROR_UNKNOWN: unknown error
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
[libmp3lame @ 0x56451ccf91c0] 3 frames left in the queue on closing
Conversion failed!
```

**Stats for Nerds Screenshots**
None

**Server System (please complete the following information):**
 - OS: docker on ubuntu
 - Jellyfin Version: 10.6.4
 - Hardware settings & device: NVENC on GTX1060
 - Reverse proxy: no
 - Other hardware notes: media mounted via NFS.  this was working before perfectly but either a recent container update or some OS patch caused this to stop.  This happens on any file that needs transcoding. No driver updates for the GTX 1060 have been installed.  Currently running on 450.57.  Host is a Proxmox server with GPU passthrough configured.
 
**Client System (please complete the following information):**
 - Device: Apple iPhone XS, Roku TV, PC
 - OS: iOS/Roku OS/Linux Mint
 - Client: iOS App, Jellyfin Roku app
 - Browser (if Web client):
 - Client and Browser Version: [e.g. 10.3.4 and 68.0]

**Comment by antipiot** [comment]
Hello!
I'm facing this aswell, it looks like to be not related to jellyfin: 
i just started to dig into this but it looks to be driver related with linux 5.9.

Same results with jellyfin 7.0RC1 wuch was working some times ago.

**Comment by nyanmisaka** [comment]
@antipiot Thanks for reminding.

`[h264_nvenc @ 0x56451ccf8740] dl_fn->cuda_dl->cuInit(0) failed -> CUDA_ERROR_UNKNOWN: unknown error`
Not an Jellyfin issue but just because Nvidia driver is incompatible with kernel 5.9.

Close it for now.

**Comment by antipiot** [comment]
In case of need, assuming you didnt have purged the old kernels, here's what i did to recover playback:

backup - snapshot your system
uninstall everything nvidia related: i used: 
`apt-get remove --purge nvidia-driver libnvcuvid1 libnvidia-encode1 libcuda1 nvidia-smi`
`apt-get remove nvidia-docker2`

Edit grub to boot old kernel: (this is the part where i assume you have the same conf as me)
make a backup if you feels the need of this file
`nano /etc/default/grub`
edit GRUB_DEFAULT - put 2
![image](https://user-images.githubusercontent.com/26579988/103148510-b12ed100-4760-11eb-9426-192c0aeac20b.png)
`update-grub`

reboot the host
`reboot now`

check you're on 5.8 kernel:
`uname -r`

Reinstall everything back

`distribution=$(. /etc/*-release;echo $VERSION_CODENAME)`
`apt-get install -t $distribution-backports nvidia-driver libnvcuvid1 libnvidia-encode1 libcuda1 nvidia-smi`
`apt-get install nvidia-docker2`

Re enable Nvenc - Enjoy

Hope it helped someone.

**Comment by crobibero** [comment]
Looks like NVIDIA put out a driver for 5.9+
https://forums.developer.nvidia.com/t/download-nvidia-driver-r455-for-linux-kernel-5-9/159776

**Comment by antipiot** [comment]
@crobibero - thanks for the information.
Do you know or can you explain to me why it looks stable on the nvidia side but is in experimental debian repo?
Is it safe to install?

**Comment by lravelo** [comment]
I'm not running this new kernel though.  Running `uname -r` on my Ubuntu VM I get the following version
`4.15.0-128-generic`

**Comment by lravelo** [comment]
So I was able to fix this by installing a later driver and CUDA package (460.27.04 and 11.2 respectively).  I'll give this a shot for the next few days but it looks good so far.

**Comment by crobibero** [comment]
> 
> 
> @crobibero - thanks for the information.
> Do you know or can you explain to me why it looks stable on the nvidia side but is in experimental debian repo?
> Is it safe to install?

I tried to install it but I was missing some dependencies. My guess is that debian only puts "long-lived" drivers in the backports repo, and 455 is currently "short-lived"
