### ISSUE TITLE
When starting playback, main page of Jellyfin comes up and covers the playing movie/episode.

### ISSUE THREAD

**Issue by lockheed** [jellyfin/jellyfin#4862]
I noticed this behaviour first about 2 weeks ago and it happenes every time I click Play on any film or episode in the library.
Once clicked, the playback starts but it is immediately covered with the Home page of Jellyfin (playback continues).

To fix it, I have to again find that film/episode in the menus and click play. Then, playback restarts and this time it is not overlayed with Home.

Restarting client or docker container makes no difference.

Jellyfin Version: 10.6.4 in docker container.
Arch Linux.
Client: Windows 10
Browsers:  Vivaldi and Chromium.

**Comment by Artiume** [comment]
This might be limited to windows or chrome and vivaldi as I intentionally do this on Firefox to force metadata pulling on content that hasnt been fully scanned yet. I click play on something, open another tab and once the video is ready, it takes control of the window. Can you test firefox to see if maybe this is limited to windows?

**Comment by lockheed** [comment]
This is a bit tricky, because it does not always happen, even on Windows with Vivaldi/Chromium.
I tested it on Firefox/Linux, it did not occur that time.

**Comment by ocervell** [comment]
+1, getting this on Chromecast sometimes too !

**Comment by ortango** [comment]
@Artiume

yes this happens with firefox (on linux) as well. i experience the issue fairly frequently.
