### ISSUE TITLE
Reinstall plugin after uninstall fails - playback reporting

### ISSUE THREAD

**Issue by antipiot** [jellyfin/jellyfin#4869]
**Describe the bug**
I've uninstalled playback reporting plugin and the reinstallation fails with error:
"ResourceNotFoundException: Package not found: Playback Reporting"

**System (please complete the following information):**
 - OS: debian
 - Virtualization: docker
 - Jellyfin Version: 10.6.4

**To Reproduce**
try to install Playback reporting plugin after uninstall

**Expected behavior**
Plugin gets installed successfully :-)

**Logs**
[jelly_log.txt](https://github.com/jellyfin/jellyfin/files/5742981/jelly_log.txt)

**Comment by BaronGreenback** [comment]
Plugin management has been redeveloped for 10.7. Currently waiting for review into 10.7RC2.
