### ISSUE TITLE
Scrubbing a mkv file results in black screen, doesn't play

### ISSUE THREAD

**Issue by mholt** [jellyfin/jellyfin#4873]
**Describe the bug**

When playing a mkv file that needs transcoding, scrubbing to a random part of the video results in a black screen, and playing stops. When I hit Play again, the pause button appears in its place but the timer isn't moving and nothing is playing.

**System (please complete the following information):**
 - OS: Ubuntu 20.04
 - Virtualization: none
 - Clients: Web, seen it on Android too.
 - Browser: Chrome 87
 - Jellyfin Version: 10.6.4
 - Playback: transcoding, direct play
 - Installed Plugins: none
 - Reverse Proxy: Caddy
 - Base URL: none
 - Networking: host
 - Storage: local

**To Reproduce**

Play an MKV file that needs transcoding -- I think I've also seen it on direct play.

**Expected behavior**

The video should scrub to the scrub point and keep playing.

**Logs**

```
[INF] Current HLS implementation doesn't support non-keyframe breaks but one is requested, ignoring that request
```

^ Even if that is why playing stops, playing should not stop; scrubbing is a basic function like play/pause that should work, even if it doesn't scrub exactly to a keyframe.

**Screenshots**

**Additional context**

Let me know if you need any more info

**Comment by mholt** [comment]
Not fixed yet.

**Comment by mueslimak3r** [comment]
i have this issue too

**Comment by adrenasxxx** [comment]
i've still the issue on 10.8.10

**Comment by mholt** [comment]
Sigh

**Comment by danni-storm** [comment]
I would also be willing to share the file for testing if that would be helpful.

**Comment by Lowxorx** [comment]
Hi, i'm also having this issue - version 10.9.3

**Comment by maksg** [comment]
Same issue here on 10.9.7.
However I figured that if I play with `Allow video/audio playback that requires transcoding` options in user's settings, then right after saving it sometimes works but only once. It doesn't matter if the options are on or off and when I go back and try to play the movie again it no longer lets me scrub.

**Comment by shimmyx** [comment]
Still same issue on latest version of Jellyfin 10.8.13

**Comment by shimmyx** [comment]
> [@shimmyx](https://github.com/shimmyx) the latest version is 10.10.6, please stop using ancient versions.

So, funnily enough I went and updated to the latest version as you mentioned, and the issue persists. The screen is black, audio is playing, and whenever moving through the timeline it takes forever, the client becomes unresponsive or outright refuses to move forward in the timeline. Oh and everytime I click anything that requires it to move forward, it will seem to 'load' the file from scratch, as the screen from the metada will appear for like 5s or more and then finish loading (whilst still being black and showing no video)

Format is MKV with subs AAC 2 channel

```
Video
Title: 1080p HEVC SDR
Codec: HEVC
Profile: Main 10
Level: 120
Resolution: 1920x1080
Aspect ratio: 16:9
Interlaced: No
Framerate: 23.976025
Bitrate: 2077 kbps
Bit depth: 10 bit
Video range: SDR
Video range type: SDR
Pixel format: yuv420p10le
Ref frames: 1

Audio
Title: Stereo - English - AAC - Default
Language: eng
Codec: AAC
Profile: LC
Layout: stereo
Channels: 2 ch
Bitrate: 155 kbps
Sample rate: 48000 Hz
Default: Yes
Forced: No
External: No

Audio
Title: Stereo - Japanese - AAC
Language: jpn
Codec: AAC
Profile: LC
Layout: stereo
Channels: 2 ch
Bitrate: 161 kbps
Sample rate: 48000 Hz
Default: No
Forced: No
External: No

Subtitle
Title: Signs and Songs(Moby JJ) - English - Default - ASS
Language: eng
Codec: ASS
Default: Yes
Forced: No
External: No

Subtitle
Title: Full Subs(Moby JJ) - English - ASS
Language: eng
Codec: ASS
Default: No
Forced: No
External: No

Image
Codec: MJPEG
Profile: Baseline
Resolution: 640x360
Bit depth: 8 bit
Colour space: bt470bg
Pixel format: yuvj420p
Ref frames: 1
```
