### ISSUE TITLE
Black/Green Screen (and other weird issues) while playback ( Nvidia HEVC Transcoding)

### ISSUE THREAD

**Issue by Joly0** [jellyfin/jellyfin#4879]
Just wanted to bring this up here aswell, as i reported the same Problem over at the Emby forums and it is fixed there now.

For some movies (i couldnt precisely tell or why, just some) playback results in a black screen that would turn into a normal screen sometime, going back to a black screen or green screen, split screen or some other weird variation of playback like video and audio desync. 

I checked everything (the hardware, software, movie, reinstalled everything and god knows what else i tried).
The solution over at Emby was to implement another Hardware Decoder (NVDEC.EX) in the latest Version, which instantly fixed the problem, so i assume its a problem with the decoder.

It would be nice, if this decoder, or some variation, could be implemented into Jellyfin aswell.

**Comment by nyanmisaka** [comment]
None of the videos in my library have this problem.
Please provide a video sample so that I can reproduce this issue.

**Comment by Joly0** [comment]
How exactly should i provide a sample? It happens with a few movies and those are roughly 40-60gb each, so difficult to just upload one somewhere.

**Comment by Joly0** [comment]
Otherwise sure i can just record the problem and send the video wirh some screenshots here, idlf that helps

**Comment by nyanmisaka** [comment]
Screenshot/video of corrupted frames and transcoding log. Also your Nvidia card model.

**Comment by Joly0** [comment]
https://emby.media/community/index.php?/topic/89884-buggy-playback-when-using-gpu-transcoding/ Maybe this helps, its my forum post for emby

**Comment by nyanmisaka** [comment]
If the green screen occurs at the beginning of the video, can you use ffmpeg to help me capture a 10s snippet of it? I need it to verify my idea.

`ffmpeg -i source.mp4 -an -sn -c:v copy -ss 20 -t 10 -y snippet.mp4`

**Comment by Joly0** [comment]
I made a 10 seconds clip, its roughly 70mb in size and shows the problem perfectly. How should i send it to you? I could upload the snippet here, but i would prefer to send it non-publicly if possible.

**Comment by nyanmisaka** [comment]
send DM to nyanmisaka using Matrix.
https://jellyfin.org/contact/

**Comment by danejur** [comment]
Also getting the same issue with various 4K HDR videos. I see a PR has been created that will resolve the issue. Thanks, @nyanmisaka!
