### ISSUE TITLE
Intel QSV worse than the intel-vaapi driver w/ PGSSUBS

### ISSUE THREAD

**Issue by ricardoandren** [jellyfin/jellyfin#4883]
Using an intel celeron j3455 w/ 16 gb of ram, I get worse fps when using the intel-media-va-driver-non-free then the i965-va-driver-shaders

Media is encoded in H265 and transcoded to h264 with subtitles burnt-in.

![afbeelding](https://user-images.githubusercontent.com/17046242/103307086-8322e880-4a0f-11eb-931d-b245e1f13615.png)
W/ intel-media-va-driver using VAAPI

![afbeelding](https://user-images.githubusercontent.com/17046242/103307257-e745ac80-4a0f-11eb-83ae-197f9fdbbf32.png)
W/ i965-va-driver-shaders using Intel QSV

**Comment by ricardoandren** [comment]
![afbeelding](https://user-images.githubusercontent.com/17046242/103307414-40addb80-4a10-11eb-89d8-aa8027d8a3b2.png)

**Comment by nyanmisaka** [comment]
Not a jellyfin issue.

iHD has performance regression compared with i965 when using VAAPI. Use QSV with iHD instead.

**Comment by ricardoandren** [comment]
Im on linux, QSV goes through vaapi.

**Comment by nyanmisaka** [comment]
Can you share ffmpeg transcoding logs?

**Comment by ricardoandren** [comment]
https://pastebin.com/bJa3yCXe i965
https://pastebin.com/xW8A6sRf iHD

**Comment by ricardoandren** [comment]
The issue was MJPEGS being incorrectly identified by ffmpeg and failing the transcoding, which led to ffmpeg trying to software decode instead. FPS is now stable at 130
