### ISSUE TITLE
[web app] Wrong "latest movies" image format in home

### ISSUE THREAD

**Issue by drago-96** [jellyfin/jellyfin#489]
When I open the Jellyfin home from the web browser, the movies in the "Latest" category have a weird look
![jellyfin](https://user-images.githubusercontent.com/22937313/50777261-68439080-129b-11e9-8ee1-f2443b6d4465.png)

This is what I get in Emby
![emby](https://user-images.githubusercontent.com/22937313/50777315-85785f00-129b-11e9-815e-a289a9c567c1.png)

The issue seems to be that Jellyfin is creating a backdrop-format card, while requesting the Primary image for the movie.
I think this has something to do with [this line](https://github.com/jellyfin/jellyfin/blob/5a66cbd75a74b7676cd6b16af0b8651af70d23af/MediaBrowser.WebDashboard/dashboard-ui/bower_components/emby-webcomponents/homesections/homesections.js#L224) or the cardBuilder module, but I don't know exactly how this JS is executed, so I can't debug any further.

**Comment by sparky8251** [comment]
The spacing is different on mine. Still off as you said though.

I'll look into it!

**Comment by sparky8251** [comment]
What version are you on? The line you linked to doesn't exist in our latest release as far as I can see.

**Comment by sparky8251** [comment]
Looking into it and comparing against Emby 3.5.2.0 there is a significant change in the CSS being applied.

Jellyfin applies `.overflowSquareCard` while Emby applies `overflowPortraitCard`. Hopefully this is a simple revert of a commit and we are good to go.

**Comment by drago-96** [comment]
I have NO idea why, but scanning some TV Shows seems to fix it
![immagine](https://user-images.githubusercontent.com/22937313/50790562-84592900-12bf-11e9-9e1c-d1c4627ff6dc.png)

Now the movies have correctly the class `.overflowPortraitCard`, while the TV shows have the `.overflowBackdropCard`.

**Comment by sparky8251** [comment]
We found the problem. Opening a PR soon. Apparently, there was a rounding error in `MediaBrowser.Controller/Entities/Movies/Movie.cs` where we removed a `double` variable of `2`.

It's fixed by making the `2` a `2.0` in the division.

**Comment by drago-96** [comment]
Wow, incredible!
Great work!
