### ISSUE TITLE
Transcoding causes drive wearout

### ISSUE THREAD

**Issue by SkewedZeppelin** [jellyfin/jellyfin#4893]
Consider the following use case:
SSD for the host system
NAS for the media/or another drive

The working directory on Linux by default is /var/lib/jellyfin/transcodes.
https://github.com/jellyfin/jellyfin/blob/536ac4c11cfff5349b973892f206fe5cfb0ae6f0/MediaBrowser.Common/Configuration/EncodingConfigurationExtensions.cs#L35
Transcodes therefore get written to disk.
Wearing out the drive over time.
This would impact SSDs the most, but even hard drives wear out from writes.

This should be modified to use the system's temporary directory instead.

**Comment by crobibero** [comment]
You can already use the system's temp directory, I do it currently.
I don't think defaulting the transcoding directory to the temp path is a good move- not all hosts have enough temp storage to transcode.

**Comment by SkewedZeppelin** [comment]
@crobibero 
> not all hosts have enough temp storage

That is a good point.
Maybe check if there is an abundance of space in /tmp? or at least a note in the docs?

**Comment by vegedb** [comment]
Erm, do you even docker? Its been an option since the dawn of time lol.

**Comment by Blackclaws** [comment]
Its actually easy on linux to just mount a tmpfs at that folder. On Windows that might be a different story. But I don't think there is a tmpfs equivalent anyway.

The wear on HDDs is actually quite limited and even SSDs need a lot of constant writing to actually wear out noticably. So I think its not that big an issue.

**Comment by SkewedZeppelin** [comment]
> The wear on HDDs is actually quite limited

A lot of consumer hard drives actually have TBW limits under 150.

And if you just chuck a $20 120GB SSD into your server, that likely only has a
40TBW rating.

I just think users need to be aware and be able to account for this.
I personally do not use Jellyfin.
