### ISSUE TITLE
Jellyfin 10.7.0 stuck on using web player on android

### ISSUE THREAD

**Issue by vegedb** [jellyfin/jellyfin#4894]
**Describe the bug**
Android app forced to use web based player even when exo/external is selected

**To Reproduce**

1. Use 10.7.0 RC
2. Jellyfin 2.2.3
3. Change to external player

**Expected behavior**
10.6.4 works great so I expect this is a bug.

**Additional context**
More info here
[https://github.com/jellyfin/jellyfin-android/issues/269](https://github.com/jellyfin/jellyfin-android/issues/269)

**Comment by Ullmie02** [comment]
This is not a server issue. Please use the jellyfin-android issue you mentioned if you still have problems
