### ISSUE TITLE
Watched status is applied to copies of TV Series in separate libraries

### ISSUE THREAD

**Issue by exterrestris** [jellyfin/jellyfin#4895]
**Describe the bug**
When marking a TV series as watched in a given library, copies of that series in other libraries will also be marked as watched.

**System (please complete the following information):**
 - OS: Windows
 - Clients: Browser
 - Browser: Firefox 84
 - Jellyfin Version: 10.6.3
 - Playback: n/a 
 - Installed Plugins: Default Plugins + Trakt, Pushover, Kodi Sync, Playback Reporting
 - Reverse Proxy: Traefik
 - Base URL: /
 - Storage: Local

**To Reproduce**
1. Create two or more TV libraries (Library 1, Library 2, etc.)
2. Add any TV series to Library 1
3. Create a copy of the TV series in **another folder** and add that folder to Library 2
4. Mark the TV series as watched in Library 1
5. Go to Library 2, and see that the series is marked as watched there as well

**Expected behaviour**
Watched status is only changed for the library in which the status was set

**Additional context**
Same behaviour doesn't seem to be present for movies.

Marking a season as unwatched in Library 2 after the above does not affect the watched status for the relevant episodes in Library 1, but the season 'overview' in Library 1 does show as unwatched.

My use case for this is for reaction videos. I have several libraries for different reactors, where I am at different stages in watching the shows they are reacting to. Most have an overlap in shows, and I also typically have the original show in my main TV library. As I am at different points with each reactor, I need the watched status to be accurate and not affect other libraries.

If you want an alternative use case, I can easily see the idea of wanting to track whether episodes with commentaries have been watched, which would not be possible using multiple versions in the same library.

**Comment by Artiume** [comment]
https://github.com/jellyfin/jellyfin/issues/1481

**Comment by exterrestris** [comment]
Not sure #1481 applies, as that issue is about including the same file in multiple libraries, whereas this issue is explicitly about _different_ files in separate libraries which happen to have the same metadata

**Comment by exterrestris** [comment]
Still an issue in 10.7.5

**Comment by exterrestris** [comment]
Still an issue in 10.7.6

**Comment by sevenrats** [comment]
@exterrestris This is the desired behavior. You can work around it by using symlinks to ensure that the file in each library has a unique filesystem path.

**Comment by Shadowghost** [comment]
Even if you do that it is quite possible that this does not help if both series have the same external IDs since watched state is not only tracked for item id but also for all external ids

**Comment by sevenrats** [comment]
Per team chat I am wrong and the unique fs path is not enough to fix this.
Per cvium:
https://github.com/jellyfin/jellyfin/blob/18a311d32fd6e3cdfed466017bda46566a013106/MediaBrowser.Controller/Entities/BaseItem.cs#L1393
https://github.com/jellyfin/jellyfin/blob/18a311d32fd6e3cdfed466017bda46566a013106/MediaBrowser.Controller/Entities/TV/Episode.cs#L153
https://github.com/jellyfin/jellyfin/blob/95ab603a40b96499e3a3b732f31aacc458ca8a2c/MediaBrowser.Controller/Entities/TV/Series.cs#L168
"the userdatas table contains a lot of duplicated data since it uses so many "keys"

this thread is a feature request to change this behavior.

**Comment by sevenrats** [comment]
moved to feature request https://features.jellyfin.org/posts/2362/fix-watch-status-in-the-db-for-the-same-media-in-different-libraries

**Comment by exterrestris** [comment]
@sevenrats The files in this case do have unique file paths - given the use case I honestly don't see how they could possibly _not_ have unique file paths

**Comment by cvium** [comment]
> @sevenrats The files in this case do have unique file paths - given the use case I honestly don't see how they could possibly _not_ have unique file paths

sevenrats merely misunderstood the issue at first. Fact remains that this behaviour is a design choice made once upon a time. Any movie or episode with imdb or tvdb id will have its user specific data synchronized, which includes stuff like played state.
