### ISSUE TITLE
Emby Native Apps (Fork?)

### ISSUE THREAD

**Issue by bfayers** [jellyfin/jellyfin#49]
Might be a decent idea to be forking all the apps we can while they're still open source.

The android app went under ages ago, but this I've found a repo that seems to be the latest.

- Android: https://github.com/hatharry/emby-android
- Emby Theater (Electron): https://github.com/MediaBrowser/emby-theater-electron
- Kodi Addon: https://github.com/MediaBrowser/plugin.video.emby
- Emby Theater (Windows): https://github.com/MediaBrowser/emby-theater-windows
- Emby Theater (Pi): https://github.com/MediaBrowser/emby-theater-pi
- Windows Media Centre: https://github.com/MediaBrowser/MediaBrowser.Classic
- Samsung Smart TV: https://github.com/MediaBrowser/SamsungSmartTV
- Roku: https://github.com/MediaBrowser/Emby.Roku
- Chrome App (Seems unused?): https://github.com/MediaBrowser/emby-chromeapp
- Windows Phone (lol): https://github.com/MediaBrowser/Emby.WindowsPhone
- Emby Theater Plugins: https://github.com/MediaBrowser/Emby.Theater.Plugins

**Comment by DoctorMacc** [comment]
There's never been source code for the iOS app? Makes sense anyway from what I know about App Store licensing, and the iOS app for Emby could be much improved.

**Comment by JustAMan** [comment]
iOS app was (at least that's my impression from reading source) once having same code as Android - they were both as html5 apps based on Cordova. I wasn't able to build them, though, after about an hour or so, thus I stopped trying.

**Comment by bfayers** [comment]
@DoctorMacc seems @JustAMan is correct looking at the one i linked it seems to have notes about building iOS.

**Comment by JustAMan** [comment]
Whoever starts this - I think my account holds one of most recent still open source version of mobile apps.

**Comment by bfayers** [comment]
@JustAMan just checked, same version (for android app) as the on I linked (same most recent commit)

**Comment by joshuaboniface** [comment]
Will work on forking all of these to the `jellyfin` org as-is tonight.

**Comment by dcrdev** [comment]
@joshuaboniface forking the existing ones is a good step -

One thing that annoyed me about upstream is that feature parity was not maintained across platforms - could we potentially look at a common codebase?

If we want to continue the upstream trend of writing apps in html then that common codebase would likely be wrapped around Cordova (or similar), but if we wanted something a little more native (is that the right word?) maybe Xamarin?

**Comment by DoctorMacc** [comment]
+1 for more native - I use Emby mobile on iOS for music and it likes to stutter when you do anything remotely related to multitasking. Potentially this is because of the way the app was designed, or its codebase?

**Comment by joshuaboniface** [comment]
https://github.com/MediaBrowser/MediaBrowser.Classic and https://github.com/MediaBrowser/Emby.Theater.Plugins both have no license, so they've been skipped.

The others are in the process of being renamed and moved to the Jellyfin org.

**Comment by XVicarious** [comment]
>having same code as Android - they were both as html5 apps based on Cordova.

This explains why the app has always felt so... Website like. I had a suspicion.

**Comment by JustAMan** [comment]
@XVicarious  Well, html5 apps were supposed to ease the development, like... make one app that works everywhere? :)
With some obvious downsides on performance suffering and non-native look-and-feel sometimes.

**Comment by SpootDev** [comment]
The kodi add-on is/was maintained by others than the "core" devs.  That being said, if they try to lock that down poke me with a stick.   I have 60 commits that I would want them to pull.

**Comment by joshuaboniface** [comment]
@SpootDev Thanks, we forked it only because the main repo is under the MediaBrowser org - hopefully we can just keep being supported officially and don't need to fork, but we have the backup just in case!

**Comment by XVicarious** [comment]
Yeah, that's understandable. However it lead to some classic HTML problems
(that are usually the fault of bad CSS) like text leading off the screen
(filenames) and therefore extending the view. Always bugged me. I should
join them on Matrix to talk about an app. I think they were talking
Flutter. I'll help out in any way I can.

**Comment by SpootDev** [comment]
Oh, I agree with taking a snap of it @joshuaboniface as they could just delete it whenever they want.  I generally try to do that with any deps I use as well as I've had dev's pull their lib off github.

**Comment by sparky8251** [comment]
With all the apps we know of forked and being worked on in various stages, does this issue need to remain open anymore?

**Comment by joshuaboniface** [comment]
I don't think so, we have forked all we can. Closed.
