### ISSUE TITLE
VIRT supposed to be so high? [10.7.0RC2]

### ISSUE THREAD

**Issue by ricardoandren** [jellyfin/jellyfin#4909]
Dont know if this counts as a bug but htop is showing a very high use of VIRT memory, this is more of a question than a bug report. But if its not supposed to be so high its a bug report. I just upgraded to 10.7.0RC2 from 10.6.4 and installed the new jellyfin-web config instead of keeping the old one.

![afbeelding](https://user-images.githubusercontent.com/17046242/103438889-60bfe380-4c38-11eb-8112-969fc6cbb017.png)

**Comment by crobibero** [comment]
According to the dotnet team, high VIRT is not an issue.
https://github.com/dotnet/runtime/issues/9199
