### ISSUE TITLE
Chromecasts not detected when accessing website via HTTP

### ISSUE THREAD

**Issue by SteveDinn** [jellyfin/jellyfin#4917]
**Describe the bug**

I have an HTTPS site for my Jellyfin instance that is mapped via a reverse proxy (Caddy). When I access Jellyfin via this name, I am able to see my local Chromecast devices.
When I access the same Jellyfin instance via its non-proxied IP address via HTTP the "Google Cast" menu item does not show.

**System (please complete the following information):**
 - OS: Ubuntu 20.04 on RPi 4
 - Virtualization: Docker
 - Clients: Windows 10, Android 10
 - Browser: Chrome 87.0.4280.88, 64-bit
 - Jellyfin Version: 10.7.0 RC2
 - Playback: n/a
 - Installed Plugins: Trakt
 - Reverse Proxy: Caddy
 - Base URL: None
 - Networking: Host
 - Storage: Local

**To Reproduce**

- Access Jellyfin via reverse proxied HTTPS address.
- See "Google Cast" appear in the menu from the cast icon.
- Access same Jellyfin instance via non-proxied HTTP IP address.
- See that "Google Cast" menu item is no longer present in the cast icon menu.

**Expected behavior**

*Google Cast* menu item shows no matter how the Jellyfin instance is accessed.

**Logs**

None, other than the normal logs.

**Screenshots**

![image](https://user-images.githubusercontent.com/3911507/103443898-ae891b80-4c39-11eb-8fe0-12307dfea050.png)

**Additional context**

This might seem like a weird bug, because why not just use the HTTPS site all the time, right? It stems from another issue that is a Chromecast specific one that I'll detail in a separate feature request.

**Comment by nielsvanvelzen** [comment]
Google does not allow the casting library on non-https domains.

See https://developers.google.com/cast/docs/chrome_sender

**Comment by SteveDinn** [comment]
This can't be true. I have many local servers that are able to cast just fine via their HTTP-only internal IP URLs.

If this is the case, is there a recommended course of action here? I've written up my situation in this feature request, but I guess that's moot now :(

https://features.jellyfin.org/posts/993/advertise-media-urls-to-chromecasts-via-local-ip-when-cc-is-on-the-same-network

**Comment by ferferga** [comment]
Closing in favor of jellyfin/jellyfin-chromecast#110 .
