### ISSUE TITLE
[web dashboard] No running tasks progress bar

### ISSUE THREAD

**Issue by drago-96** [jellyfin/jellyfin#492]
The progress bar for running tasks such as library scan isn't there anymore.
Here the fix is easy: for some crazy reason, [this line](https://github.com/jellyfin/jellyfin/blob/5a66cbd75a74b7676cd6b16af0b8651af70d23af/MediaBrowser.WebDashboard/dashboard-ui/scripts/dashboardpage.js#L220) tries to disable the "Update Application" button (removed [here](https://github.com/jellyfin/jellyfin/commit/fe16fc7523d2c5bf1fa37df33b538ed2f5a64d99#diff-ee0e13a7d18365f8e262bc7a836e5e0a)) when a task is running, I think.

**Comment by sparky8251** [comment]
Should be fixed with #412 based on looking at what it changes.
