### ISSUE TITLE
10.7.0 RC-2 Not working in Synology NAS - Docker

### ISSUE THREAD

**Issue by Oatavandi** [jellyfin/jellyfin#4925]
**Describe the bug**
While doing a clean install of 10.7.0 RC2 for docker. There are issues. Please find the attached screenshots for reference.
Same steps followed for doing a clean install with stable and 10.7.0 RC-1 no issues.
Even when upgrading from 10.6.4, same error. Also removed plugins and tried but same error.

**System (please complete the following information):**
 - OS: Linux in Synology NAS
 - Virtualization: Docker
 - Jellyfin Version: 10.7.0 RC-2
 - Installed Plugins: No plugins installed. Clean install (doing a new fresh setup)

**To Reproduce**

1. docker pull jellyfin/jellyfin:stable-rc
2. docker run -d \
 --name jellyfin_new \
 --user root:root \
 --volume /volume1/jellyfin_new/config:/config \
 --volume /volume1/jellyfin_new/cache:/cache \
 --volume /volume1/jellyfin_new/media:/media \
 --volume /volume1/media/video/movies/4K:/media/4k \
 --volume /volume1/media/video/movies/HD:/media/hd \
 --volume /volume1/media/video/tv\ shows:/media/tv\ shows \
 --volume /volume1/media/music:/media/music \
 -p 2016:8096 \
 -e TZ=Asia/Singapore \
 --restart=unless-stopped \
 jellyfin/jellyfin:stable-rc 

3. See error <Refer Attached>

**Expected behavior**

Install and get started without any issue.
**No issues with installing latest stable or 10.7.0 RC-1**

**Logs**

Refer attachements

**Screenshots**

<img width="827" alt="Screenshot 2021-01-02 at 5 21 56 PM" src="https://user-images.githubusercontent.com/70758372/103454619-e028e200-4d20-11eb-9671-e7dbda531da5.png">
<img width="531" alt="Screenshot 2021-01-02 at 5 26 07 PM" src="https://user-images.githubusercontent.com/70758372/103454624-ed45d100-4d20-11eb-85f3-bb4b666e764c.png">
<img width="968" alt="Screenshot 2021-01-02 at 5 26 41 PM" src="https://user-images.githubusercontent.com/70758372/103454628-f5057580-4d20-11eb-881a-164e58cafd30.png">

**Additional context**

**Comment by Oatavandi** [comment]
I am using the same params for all versions of installations.
--user root:root 
is working for latest stable, 10.7.0 RC-1, even for earlier unstable builds before 10.7.0 RC-2

**Comment by Oatavandi** [comment]
docker pull jellyfin/jellyfin:20201210.25-unstable - WORKING

**Some Changes happened between this which is breaking the docker - Clean Installation**

docker pull jellyfin/jellyfin:20201211.3-unstable - ERROR

**Comment by crobibero** [comment]
Our upstream image changed from `mcr.microsoft.com/dotnet/core/sdk:${DOTNET_VERSION}-buster` to `mcr.microsoft.com/dotnet/sdk:${DOTNET_VERSION}-buster-slim`

https://github.com/dotnet/dotnet-docker/issues/1927

I don't see any other changes that could have had any effect on what you're trying to do, but this change happened on Nov 16.

**Comment by Oatavandi** [comment]
> Our upstream image changed from `mcr.microsoft.com/dotnet/core/sdk:${DOTNET_VERSION}-buster` to `mcr.microsoft.com/dotnet/sdk:${DOTNET_VERSION}-buster-slim`
> 
> [dotnet/dotnet-docker#1927](https://github.com/dotnet/dotnet-docker/issues/1927)
> 
> I don't see any other changes that could have had any effect on what you're trying to do, but this change happened on Nov 16.

I tried installing multiple version and found something happened between these two versions. I am not sure what happened. 
Now not able to upgrade from previous version or do a clean install.

**Comment by CyanBC** [comment]
I'm also recieving some new errors setting up a new/clean environment for the docker image in ubuntu 20.04 LTS. It seems that the user mapping is failing where it didn't before. I have preferenced using anonymized root users (giving the docker-compose an aributrary user ID which is mapped to root but is otherwise harder to do access escalation attacks (https://www.cloudsavvyit.com/5211/privileged-vs-root-in-docker-whats-the-difference/). I've set up all of my dockers this way thus far, mapped to user: 1000:1000 without any issue.

This latest docker release gives me this error:
```
root@odroid:/odroid/compose_yaml/jellyfin# docker-compose up
Creating jellyfin ... done
Attaching to jellyfin
jellyfin    | Unhandled Exception
jellyfin    | System.UnauthorizedAccessException: Access to the path '/config/log' is denied.
jellyfin    |  ---> System.IO.IOException: Permission denied
jellyfin    |    --- End of inner exception stack trace ---
jellyfin    |    at System.IO.FileSystem.CreateDirectory(String fullPath)
jellyfin    |    at System.IO.Directory.CreateDirectory(String path)
jellyfin    |    at Jellyfin.Server.Program.CreateApplicationPaths(StartupOptions options)
jellyfin    |    at Jellyfin.Server.Program.StartApp(StartupOptions options)
jellyfin    |    at Jellyfin.Server.Program.<Main>(String[] args)
jellyfin    | Unhandled exception. System.UnauthorizedAccessException: Access to the path '/config/log' is denied.
jellyfin    |  ---> System.IO.IOException: Permission denied
jellyfin    |    --- End of inner exception stack trace ---
jellyfin    |    at System.IO.FileSystem.CreateDirectory(String fullPath)
jellyfin    |    at System.IO.Directory.CreateDirectory(String path)
jellyfin    |    at Jellyfin.Server.Program.CreateApplicationPaths(StartupOptions options)
jellyfin    |    at Jellyfin.Server.Program.StartApp(StartupOptions options)
jellyfin    |    at Jellyfin.Server.Program.<Main>(String[] args)
```

If I change my user from user: 1000:1000 to user: 0:0 or user: root:root I don't have permission issues anymore.

Perhaps these things are related?

**Comment by Oatavandi** [comment]
Same error even following the documentation steps
https://jellyfin.org/docs/general/administration/install/synology.html

**Comment by Oatavandi** [comment]
> Our upstream image changed from `mcr.microsoft.com/dotnet/core/sdk:${DOTNET_VERSION}-buster` to `mcr.microsoft.com/dotnet/sdk:${DOTNET_VERSION}-buster-slim`
> 
> [dotnet/dotnet-docker#1927](https://github.com/dotnet/dotnet-docker/issues/1927)
> 
> I don't see any other changes that could have had any effect on what you're trying to do, but this change happened on Nov 16.

Is there anything related to dotnet version upgraded from 5.0 to 5.0.1?
As I can see some changes happened to upgrade the dot version to 5.0.1 on 09-Dec-2020. The issue started from 10-Dec-2020.

**Comment by Oatavandi** [comment]
Finally found the solution, but this is something weird

I had to uninstall the docker then again install 

Then installing 10.7.0 RC2 is working fine.
Seems something is not getting cleared in Synology NAS Docker 

Closing the issue as this not the bug in Jellyfin
