### ISSUE TITLE
[10.7 RC2] Jellyfin fails to play video if VA-API cannot hardware transcode

### ISSUE THREAD

**Issue by mirolm** [jellyfin/jellyfin#4927]
**Describe the bug**

After upgrade to Jellyfin 10.7 RC2 i noticed that videos encoded with HEVC refuse to play. In 10.6 they was playing. I digged and found that my cpu (Intel i5-4570S) has capability to decode via VA-API only MPEG2, VC1 and H264. I looked in the Dashboard / Playback and found that HEVC, VP8, VP9 are checked too. It seemed strange because this cpu has no hardware capability to decode them (maybe i checked them by mistake dunno). After unchecking the formats that are not supported (HEVC / VP8 / VP9). The videos started to play as usual with software transcoding. It seems that 10.7 RC2 refuses to fallback to software if hardware transcoding fails.

With 10.6 this videos play fine and fallback to software if hadrware transcoding did not work for some reason.

vainfo supported formats output:

````
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264MultiviewHigh      :	VAEntrypointVLD
      VAProfileH264MultiviewHigh      :	VAEntrypointEncSlice
      VAProfileH264StereoHigh         :	VAEntrypointVLD
      VAProfileH264StereoHigh         :	VAEntrypointEncSlice
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileJPEGBaseline           :	VAEntrypointVLD
````

**System (please complete the following information):**
 - OS: Debian Buster x64
 - Virtualization: None
 - Clients: Browser
 - Browser: Chromium 87.0.4280.88 (Official Build) Arch Linux (64-bit)
 - Jellyfin Version: 10.7 RC2
 - Playback: Transcode 
 - Installed Plugins: none
 - Reverse Proxy: nginx
 - Base URL: none
 - Networking: Host
 - Storage: local

**To Reproduce**

1. Go to Dashboard / Playback
2. Check VA-API
3. Check Hardware Decoding For
4. Check if there is format that cannot be hardware transcoded and it is enabled
5. Play a video in that format - it fails
6. Go back and uncheck the unsupported formats.
7. Same video plays without issues transcoding in software.

**Expected behavior**

Jellyfin should not let us select unsupported hardware transcode formats in the Playback section, or at least fallback to software transcoding should work as in 10.6..

**Logs**

[jellyfin.log](https://github.com/jellyfin/jellyfin/files/5760146/jellyfin.log)
[ffmpeg-transcode.log](https://github.com/jellyfin/jellyfin/files/5760147/ffmpeg-transcode.log)

**Screenshots**

None

**Additional context**

None

**Comment by nyanmisaka** [comment]
Software fallback hasn't been implemented for now.

This is not a specific issue on VAAPI, but rather as an improvement.

**Comment by mirolm** [comment]
This is nice to hear. Maybe then it will be good as a part of the upgrade to uncheck/disable the formats that are not supported for hardware transcode to prevent further confusion. Another step can be to put it in the documentation / upgrade notes, so people are aware and will take care of this manually.

**Comment by nyanmisaka** [comment]
I think HEVC hw decoding is disabled by default.

**Comment by cvium** [comment]
Hardware accelerated transcoding is an advanced feature. We do not currently have any means of checking the server capabilities.

Also, feature requests belong here: https://features.jellyfin.org
