### ISSUE TITLE
centos8.3 jellyfin-10.7.0~rc2 error

### ISSUE THREAD

**Issue by angelsion** [jellyfin/jellyfin#4938]
jellyfin-10.7.0~rc2-1.el7.x86_64.rpm                                                                                                                         1.2 kB/s | 3.9 kB     00:03    
error：
 conflicting requests
  - nothing provides jellyfin-web < 10.7 needed by jellyfin-10.7.0~rc2-1.el7.x86_64

**Comment by cvium** [comment]
Should be fine now? Let us know if it's not fixed...
