### ISSUE TITLE
Replace MediaBrowser.Model/Net/MimeTypes.cs to be based on the IANA mime-type XML.

### ISSUE THREAD

**Issue by EraYaN** [jellyfin/jellyfin#494]
The current way is error prone (hence there are some mim-type errors)

So we should be using something like the IANA XML of the Apache mime.types file and a resource and just have this class parse it and classify things.

**Comment by anthonylavado** [comment]
This still needs to be done, right?

**Comment by EraYaN** [comment]
Yes.

**Comment by cvium** [comment]
https://www.nuget.org/packages/MimeTypes/

**Comment by forresthopkinsa** [comment]
I'll try to tackle this.

**Comment by holahmeds** [comment]
Should this be closed now that #6941 is merged?
