### ISSUE TITLE
Skia missing in ARM Docker

### ISSUE THREAD

**Issue by SenorSmartyPants** [jellyfin/jellyfin#495]
jellyfin         | 2019-01-07T17:46:11.742072364Z [11:46:11] [INF] Skia not available. Will fallback to NullIMageEncoder. {0}
jellyfin         | 2019-01-07T17:46:11.742357884Z System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibSkiaSharp: cannot open shared object file: No such file or directory
jellyfin         | 2019-01-07T17:46:11.742549828Z    at SkiaSharp.SkiaApi.sk_color_premultiply(SKColor color)
jellyfin         | 2019-01-07T17:46:11.742629822Z    at SkiaSharp.SKPMColor.PreMultiply(SKColor color)
jellyfin         | 2019-01-07T17:46:11.742697150Z    at Emby.Drawing.Skia.SkiaEncoder.LogVersion() in /repo/Emby.Drawing.Skia/SkiaEncoder.cs:line 82
jellyfin         | 2019-01-07T17:46:11.742766145Z    at Emby.Drawing.Skia.SkiaEncoder..ctor(ILogger logger, IApplicationPaths appPaths, Func`1 httpClientFactory, IFileSystem fileSystem, ILocalizationManager localizationManager) in /repo/Emby.Drawing.Skia/SkiaEncoder.cs:line 35
jellyfin         | 2019-01-07T17:46:11.742832390Z    at Jellyfin.Server.Program.getImageEncoder(ILogger logger, IFileSystem fileSystem, StartupOptions startupOptions, Func`1 httpClient, IApplicationPaths appPaths, IEnvironmentInfo environment, ILocalizationManager localizationManager) in /repo/Jellyfin.Server/Program.cs:line 221

**Comment by sparky8251** [comment]
Known issue with SkiaSharp actually. We are working on it!

**Comment by SenorSmartyPants** [comment]
You folks are on the ball. Didn't see an issue for it so I created this one. 

Keep up the good work.

**Comment by sparky8251** [comment]
I don't think its part of any open issues. It was found as part of our build system overhaul PR and is being addressed there!

**Comment by nvllsvm** [comment]
Fixed with https://github.com/jellyfin/jellyfin/pull/534
