### ISSUE TITLE
Syncplay freezes stream for some participants during playback

### ISSUE THREAD

**Issue by xkronusx** [jellyfin/jellyfin#4953]
**Describe the bug**

Watching a video using Syncplay one of the users videos will freeze and never resume. It usually happens around 20 minutes or so into a video. Rejoining the group does not resolve the issue, only making a new group can resolve the issue. At the same time the old group will be stuck in the groups manager.

**System (please complete the following information):**
 - OS: Ubuntu 18.04.5 LTS
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Chrome and Firefox (Windows 10)
 - Jellyfin Version: 10.7.0 RC2 stable 
 - Playback: Direct Stream (Until MPV Shim is updated to handle new Syncplay changes)
 - Installed Plugins:  None (plugins were causing seg faults on upgrade)
 - Reverse Proxy: Traefik (All traffic was internal LAN)
 - Storage: Local

**To Reproduce**
1.  Start video
2. Open group
3. Other user joins
4. Watch for about 20 minutes a user will freeze up.

**Additional context**
If any additional testing is needed or context let me know, I've been trying to test out a bunch of scenarios to make sure everything works.

**Comment by atomheartother** [comment]
This also happens to me pretty often, at least once per viewing session. Some similarities:

- Docker virtualization (through `linuxserver/jellyfin`)
- I use no plugins
- Traefik as reverse-proxy

**Comment by duckinator** [comment]
Same problem, newer version of Jellyfin, not using Docker or Traefik.

**System (please complete the following information):**

* OS: Ubuntu 20.04.2 LTS
* Virtualization: libvirt/qemu-kvm
* Clients: Browser
* Browser: Firefox 88.0.1 on FreeBSD and Firefox 89.0b10 (developer edition) Manjaro Linux
* Jellyfin Version: 10.7.5
* Playback: Transcode
* Installed Plugins: AudioDB, Bookshelf, Kitsu, Kodi Sync Queue, MusicBrainz, OMDb, TheTVDB
* Reverse Proxy: Caddy
* Storage: Local

**Comment by Bond-009** [comment]
Closing as stale

**Comment by duckinator** [comment]
This issue is not resolved; please re-open it.

It's still an ongoing problem with Jellyfin 10.8.12. As best I can tell, the browser and operating system for the client don't seem to be relevant. It's bad enough I basically can't use Syncplay.

I've confirmed it's still a problem using Firefox 120.0 on FreeBSD, Manjaro Linux, and Windows 10; but as mentioned here it also affects Chrome and older versions of Firefox.

**Comment by bombaglad** [comment]
Can confirm this still happens on the latest release (in docker under unraid). Seems to mostly be an issue if also transcoding, direct play is much more reliable.

**Comment by felix920506** [comment]
Can this be renamed to not contain "10.7.0 RC2" or any version number in the title?
