### ISSUE TITLE
centos8.3 Unable to connect to Jellyfin on first start

### ISSUE THREAD

**Issue by angelsion** [jellyfin/jellyfin#4954]
jellyfin：10.6.4
centos8.3
To Reproduce
Start a new container and try to use the wizard.

Expected behavior
Being able to log in the app.

Logs
When clicking on Next, server-side:
![image](https://user-images.githubusercontent.com/29788994/103598395-66e4e700-4efa-11eb-8d78-51b871406379.png)
`[2021-01-05 09:47:53.000 +08:00] [INF] [11] Jellyfin.Api.Auth.CustomAuthenticationHandler: "CustomAuthentication" was not authenticated. Failure message: "Invalid user"
`

web:
![image](https://user-images.githubusercontent.com/29788994/103598506-b0cdcd00-4efa-11eb-94f8-267089ba166e.png)
![image](https://user-images.githubusercontent.com/29788994/103598513-b4f9ea80-4efa-11eb-9c50-1336e46726b7.png)

**Comment by cvium** [comment]
@angelsion can you test with 10.7.1?

**Comment by angelsion** [comment]
> @angelsion can you test with 10.7.1?
i tried
