### ISSUE TITLE
Albums detail pages show crazy large number (like 121795) of tracks

### ISSUE THREAD

**Issue by gerroon** [jellyfin/jellyfin#497]
Hi

It seems like the albums are showing wrong numbers like  121795 tracks. Please see the image for what is going on. The album actually only has 18 tracks.

It seems like all albums I have in Jellyfin have wrong track numbers like this (121795) whether they have couple tracks or more.

![asdsadsa](https://user-images.githubusercontent.com/8519469/50785984-2241f900-12aa-11e9-9ae1-671238152263.png)

**Comment by sparky8251** [comment]
@gerroon, if you you could test older versions of JF and see if one of them doesn't have this bug, that would be great.

We've noticed a few regressions that came about in 10.0.0 that weren't present in 3.5.2-5 and one of them *might* be related to this.

**Comment by anthonylavado** [comment]
I believe this is fixed by #680?

**Comment by anthonylavado** [comment]
Currently running a test build with #680 included. This issue doesn't appear to occur anymore. Watch for this in the next release.

**Comment by gerroon** [comment]
I still see it, I am using 10.1.0.1 on Debian

**Comment by anthonylavado** [comment]
@gerroon - 10.1.0 doesn’t have the fix it in, it came after that release. The next one (10.2.0) is currently in a release candidate, if you feel like trying it. I have gone through several tests and can confirm this is fixed :slight_smile:

**Comment by gerroon** [comment]
Ok thanks for the update, I will test it and report it here.

**Comment by anthonylavado** [comment]
Oh wow - we never closed this. This was definitely fixed in that release.
