### ISSUE TITLE
Access control missing for stream URLs

### ISSUE THREAD

**Issue by 9p6** [jellyfin/jellyfin#4971]
**Describe the bug**
The user interface option `Copy Stream URL` allows generating a urls of a form
`http://<host>:<port>/Items/<id>/Download?api_key=<key>`
which are protected with an API key however the actual URL used for streaming of a form
`http://<host>:<port>/videos/<id>/stream.<extension>`
features no access control.

**System (please complete the following information):**
 - Jellyfin Version: 10.7.0~rc2

**To Reproduce**
1. Find out id of the media
2. Use above URL template to access it without authorization

**Expected behavior**
Streaming endpoints should have access control

**Comment by crobibero** [comment]
Duplicate of https://github.com/jellyfin/jellyfin/issues/1501
