### ISSUE TITLE
Missing Chinese Simplified, Chinese Traditional and Chinese Traditional (Hong Kong) locales in language settings

### ISSUE THREAD

**Issue by ootrey** [jellyfin/jellyfin#4979]
Under **User Setting** → **Display** → **Display language**, the options of **Chinese Simplified**, **Chinese Traditional** or **Chinese Traditional (Hong Kong)** exist:

![image](https://user-images.githubusercontent.com/61690048/103970731-e517e680-51a3-11eb-9eb9-9c408a65ba08.png)

However, under **Setting** → **Server** → **General** → **Preferred display language**, **Chinese Traditional (Hong Kong)** is missing:

![image](https://user-images.githubusercontent.com/61690048/103970794-08429600-51a4-11eb-8c94-b28f102b29b3.png)

In **Library Settings**, **Chinese** is not separated and it is the only option available: 

![image](https://user-images.githubusercontent.com/61690048/103970902-42ac3300-51a4-11eb-9f5b-b94e24fbaa50.png)

In this case, **Chinese** will be assumed **Chinese Simplified**. As a result, there is no way to fetch **Chinese Traditional (Hong Kong)** metadata.

**Comment by crobibero** [comment]
What version are you running?
I think I saw a PR come through that was supposed to fix this recently

**Comment by ootrey** [comment]
> What version are you running?
> I think I saw a PR come through that was supposed to fix this recently

Version 10.6.4

**Comment by Ullmie02** [comment]
Yes this was fixed in jellyfin/jellyfin-web#2280
The new languages will be available in 10.7.0

**Comment by ootrey** [comment]
I have checked it in the 2021-01-08 unstable build. Still **Chinese** is the only one option:

![image](https://user-images.githubusercontent.com/61690048/103996780-47d5a600-51d5-11eb-986b-a70e60d190b0.png)

Even if **Chinese** and **Hong Kong S.A.R.** are both selected in **Library Settings**, the metadata is in **Chinese Simplified** rather than **Chinese Traditional (Hong Kong)**.

![image](https://user-images.githubusercontent.com/61690048/103997189-bb77b300-51d5-11eb-8be5-eb4bbd2bd4a2.png)

**Comment by Ullmie02** [comment]
Sorry for closing this issue. I didn't look closely.
The pull request I created will add Chinese Traditional and Chinese Hong Kong as additional languages. I tested it and selecting Chinese Hong Kong will now pull the Chinese Hong Kong metadata from TMDb
