### ISSUE TITLE
Playlist corrupted? A bunch of tracks from same album show same first track repeated over and over

### ISSUE THREAD

**Issue by mholt** [jellyfin/jellyfin#4983]
**Describe the bug**

A few days ago I added a bunch of songs from the same album to a playlist. The playlist has existed for a long time without problems. But today after loading the web client and navigating to the playlist, all the songs are the same. There are the same number of tracks, but they're all pointing to the first track (lexicographically) in the album folder. It's just repeated N times in the album.

It was fine for a while but today it's not. I have confirmed that no changes to the files have occurred. I can still play them normally with VLC.

Metadata management/collection is off.

**System (please complete the following information):**
 - OS: Ubuntu 20.04
 - Virtualization: none
 - Clients: browser
 - Browser: Chrome
 - Jellyfin Version: 10.6.4
 - Playback: direct
 - Installed Plugins: none
 - Reverse Proxy: Caddy
 - Base URL: none
 - Networking: host
 - Storage: local

**To Reproduce**

Unfortunately I do not know how to reproduce this :( I know that is not helpful. Sorry.

**Expected behavior**

Songs in a playlist should not be replaced by repeating the same one over and over again.

**Logs**

None that I know of. Let me know if you need anything specifically.

Any tips to restore the playlist without having to recreate it? Will be happy to follow troubleshooting suggestions.

**Comment by mholt** [comment]
Not fixed yet.

**Comment by srcrist** [comment]
Closing this issue as it does not reference a reproducible Jellyfin bug.
