### ISSUE TITLE
Jellyfin 10.7.0~rc2 not playing on Chromecast from android phone

### ISSUE THREAD

**Issue by cedjo** [jellyfin/jellyfin#4990]
**Describe the bug**
cannot cast a movie to chromecast from android phone.

**System (please complete the following information):**
 - OS: linux
 - Virtualization: docker
 - Clients: chromecast
 - Browser: [e.g. Firefox 72, Chrome 80, Safari 13]
 - Jellyfin Version: [e.g. 10.4.3, nightly 20191231]
 - Playback: [Direct Play, Remux, Direct Stream, Transcode] 
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: none
 - Networking: [e.g. Host, Bridge/NAT]
 - Storage: [e.g. local, NFS, cloud]

**To Reproduce**
cast a movie from my android phone to chromecast, receive a message on phone: Error, messagechromecastconnectionerror

**Expected behavior**
movie to be played on the chromecast

the same setup works perfectly from jellyfin 10.6.4 on the same infrastructure.

I do not know how to find logs to help solving this bug.

**Comment by crobibero** [comment]
https://github.com/jellyfin/jellyfin-chromecast/issues/113

**Comment by hawken93** [comment]
see: https://github.com/jellyfin/jellyfin-android/issues/281
