### ISSUE TITLE
Live Stream goes back a few seconds

### ISSUE THREAD

**Issue by danielalexis** [jellyfin/jellyfin#4996]
When i try to play a Livestream froma m3u file after a few seconds it goes back altough i have the Auto-loop live streams enabled

**FFmpeg Logs**
Revelant Part:
[http @ 0x56219ee24380] Will reconnect at 30078532 in 0 second(s), error=End of file.
[mpegts @ 0x56219ee23580] Packet corrupt (stream = 0, dts = 3116692800).
frame=11510 fps= 62 q=17.0 size=N/A time=00:07:40.48 bitrate=N/A dup=2274 drop=5 speed= 2.5x    
[h264 @ 0x56219ee30180] mmco: unref short failure
    Last message repeated 1 times
[h264 @ 0x56219ee30180] number of reference frames (0+5) exceeds max (4; probably corrupt input), discarding one
[h264 @ 0x56219f0daf00] mmco: unref short failure
    Last message repeated 1 times
[h264 @ 0x56219f0daf00] number of reference frames (0+5) exceeds max (4; probably corrupt input), discarding one
[libmp3lame @ 0x56219ee2e240] Queue input is backward in time
[segment @ 0x56219ef6fd40] Non-monotonous DTS in output stream 0:1; previous: 41448328, current: 41442208; changing to 41448329. This may result in incorrect timestamps in the output file.
[segment @ 0x56219ef6fd40] Non-monotonous DTS in output stream 0:1; previous: 41448329, current: 41444368; changing to 41448330. This may result in incorrect timestamps in the output file.
[h264 @ 0x56219f172500] mmco: unref short failure
    Last message repeated 1 times
[h264 @ 0x56219f172500] number of reference frames (0+5) exceeds max (4; probably corrupt input), discarding one
[segment @ 0x56219ef6fd40] Non-monotonous DTS in output stream 0:1; previous: 41448330, current: 41446528; changing to 41448331. This may result in incorrect timestamps in the output file.
[h264 @ 0x56219ee2d300] mmco: unref short failure
    Last message repeated 1 times
[h264 @ 0x56219ee2d300] number of reference frames (0+5) exceeds max (4; probably corrupt input), discarding one

Note: I have the Auto-loop live streams option enabled but seems when reconnecting it repeats/cant feed data well

**Server System:**
 - OS: Pop-OS 20.04 (Ubuntu-based)
 - Jellyfin Version: 10.6.4
 - Hardware settings & device: NVENC on GTX1060, VAAPI on Intel i7 8500
 - Reverse proxy: nginx
 
**Client System (please complete the following information):**
 - Device: PC
 - OS: Windows 10
 - Client: Web/Browser
 - Browser (if Web client): Firefox, Chrome

**Comment by cvium** [comment]
If it works up to a certain point but then fails when reconnecting it smells like an ffmpeg or stream issue, neither of which I'm not sure we can do much about.

@nyanmisaka any ideas?

**Comment by danielalexis** [comment]
Probably a error with FFmpeg, i no longer use the feature so idk if its still buggy

**Comment by SmokeyBR** [comment]
yes this is still buggy, same behaviour as reported also if you record the stream it will record in a loop of 2minutes and advancing every few seconds resulting in extensive hours of recording.

i recorded a program that had 1 hour the end result was a recording of 7 hours.
