### ISSUE TITLE
Add to Kickball/awesome-selfhosted list

### ISSUE THREAD

**Issue by nvllsvm** [jellyfin/jellyfin#5]
Open a pull request to add jellyfin to https://github.com/Kickball/awesome-selfhosted

**Comment by nvllsvm** [comment]
I'll open a pull request to add once all blobs are removed. https://github.com/jellyfin/jellyfin/issues/4
This is so we can land on the main list instead of the non-free list.

**Comment by nvllsvm** [comment]
https://github.com/Kickball/awesome-selfhosted/pull/1587

**Comment by sparky8251** [comment]
This was merged in 11 hours ago. Likely safe to close.
