### ISSUE TITLE
.NET Core SDK Telemetry

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin#50]
As reported in the [Riot](https://riot.im/app/#/room/#jellyfin:matrix.org) room, there are some commands for .NET Core that send back telemetry to Microsoft (see reference: https://docs.microsoft.com/en-us/dotnet/core/tools/telemetry)

At present, the commands that do this are believed to be:

- dotnet build
- dotnet pack
- dotnet restore
- dotnet run

According to the reference page, there is an environment variable that can be used to disable these. We should include this in our instructions/package/build so that we don't accidentally send out details without permission.

(thanks to qurqar in #jellyfin for reporting this.)

**Comment by dcrdev** [comment]
Definitely we should raise awareness of this

**Comment by anthonylavado** [comment]
Just re-opening to track a future PR for the Debian build file, as mentioned in #80

**Comment by anthonylavado** [comment]
@joshuaboniface Are you able to check if the Debian build stuff can have this env variable put in?

**Comment by joshuaboniface** [comment]
It's been added.
