### ISSUE TITLE
询问作者，本人遇到个小问题，就是每部电影成功扫描后，在jellyfin中点演员，会发现一直转圈，好像不能关联到其他电影，求助？！

### ISSUE THREAD

**Issue by liuzj288** [jellyfin/jellyfin#5001]
**Describe the bug**

询问作者，本人遇到个小问题，就是每部电影成功扫描后，在jellyfin中点演员，会发现一直转圈，好像不能关联到其他电影，求助？！
**System (please complete the following information):**
 - OS: [e.g. Debian, Windows]
 - Virtualization: [e.g. Docker, KVM, LXC]
 - Clients: [Browser, Android, Fire Stick, etc.]
 - Browser: [e.g. Firefox 72, Chrome 80, Safari 13]
 - Jellyfin Version: [e.g. 10.4.3, nightly 20191231]
 - Playback: [Direct Play, Remux, Direct Stream, Transcode] 
 - Installed Plugins: [e.g. none, Fanart, Anime, etc.]
 - Reverse Proxy: [e.g. none, nginx, apache, etc.]
 - Base URL: [e.g. none, yes: /example]
 - Networking: [e.g. Host, Bridge/NAT]
 - Storage: [e.g. local, NFS, cloud]

**To Reproduce**

**Expected behavior**

**Logs**

**Screenshots**

**Additional context**

**Comment by hawken93** [comment]
I'm sorry, we can't understand this. Can you fill in the form and maybe reach out on matrix to find someone to help you translate?

**Comment by CyanBC** [comment]
Google translate:
```
Asking the author, I encountered a small problem, that is, after each movie is successfully scanned, I clicked on the actors in jellyfin, and I found that I kept turning around, as if I couldn't connect to other movies, please help? !
```

I also have this issue. That is, I think, if I click on a show for which an actor thumbnail (image) is not present, and click on it (or on the (...) jellyfin will start "loading" and never resolve. It doesn't lock the browser and the server still responds, but one would expect to go into the actor metadata. In my case, clicking on the actor only works when there is an image there.

**Comment by tobylibo** [comment]
I also have this issue. In addition, with the latest iPhone full-screen mobile phone, when playing videos, the bottom bar of the iPhone cannot be automatically hidden, but will always be displayed, which affects the viewing experience. I have reacted to this bug before. Later, although the ios app was updated recently, But this bug still exists.

**Comment by Ullmie02** [comment]
@tobylibo Your issue with the iOS home indicator is being tracked in jellyfin/jellyfin-expo#188

**Comment by hawken93** [comment]
I think it will help if someone that know how can produce steps to reproduce. I also think the debugging for this probably starts in web, so maybe transfer it there?

**Comment by HaoChuh** [comment]
I think it's the same as #jellyfin/jellyfin/issues/4352.

**Comment by cvium** [comment]
Closing as a duplicate of #4352

**Comment by Chensama-cat** [comment]
2025年我也遇到了这个问题。。只有极少数演员可以关联，其余的点击后永远都是转圈圈然后提示超时。
