### ISSUE TITLE
Support for ARMv6 (Raspberry Pi 1 & Zero)

### ISSUE THREAD

**Issue by MichaIng** [jellyfin/jellyfin#5011]
Hi, I'm not sure if this is reported correctly here or if APT repository related issues should be reported elsewhere?

The mirror direction currently does not respect the Raspbian vs Debian suites which breaks installs on ARMv6 RPi models. https://repo.jellyfin.org/raspbian is redirected to https://fra1.mirror.jellyfin.org/debian in one particular case, pulling the ARMv7 binaries which cause a SEGV on RPi 1 and Zero models.

For reference: https://dietpi.com/phpbb/viewtopic.php?p=29662#p29662

**Comment by MichaIng** [comment]
Ah many thanks, didn't know about this limitation from .NET side. I see now the "raspbian" repo just needs to exist to work with `$( awk -F'=' '/^ID=/{ print $NF }' /etc/os-release )` from the download page, it makes all sense then. I'll mark the issue as closed and keep an eye on the .NET issue instead.

**Comment by Shadowghost** [comment]
Tbh I don't think running Jellyfin on an RPi with 512MB of RAM will give you a satisfying experience.
