### ISSUE TITLE
Request: better metadata manager

### ISSUE THREAD

**Issue by drago-96** [jellyfin/jellyfin#502]
In my opinion the current metadata manager has one big flaw: I can't edit file by file.

Example from the real world: I had the Harry Potter 7 movies named as `Harry.Potter.and.the.Deathly.Hallows.Part.1.mkv` and  `Harry.Potter.and.the.Deathly.Hallows.Part.2.mkv`.
When I first scan the library, Jellyfin (or rather Emby) decided that they were the same movie, and I wasn't able to split them. The only thing I could do was renaming them adding the year, and rescanning the library.

Now, I know that one should have better naming practices, but I think that the whole reason metadata exist is "I've got this file, tell me a bunch of infos".
I don't know how metadata are implemented now, but I'd very much like if Jellyfin could implement a metadata manager based on files. Like the one that already exists, but with a "filesystem" view on the left.
In this way, I think it should also be easy to add a flag "hide this file from the library", which is something someone might like.

**Comment by sparky8251** [comment]
There are several issues related to this. I'll be opening a new issue and referencing this one it it.
