### ISSUE TITLE
Screen stuck at language wizard - Local build 

### ISSUE THREAD

**Issue by kn-f** [jellyfin/jellyfin#5022]
**Describe the bug**
When I build Jellyfin locally and access to the wizard, I get stuck at language selection page and cannot proceed.
The drop-down box is not showing anything and there's a "loading" symbol on the screen.

**System (please complete the following information):**
 - OS: Ubuntu 20.4 (under VirtualBox)
 - Virtualization: none in the virtualized box
 - Clients: Browser
 - Browser: Firefox 79
 - Jellyfin Version: main branch on 14/1/2021
 - Playback: N/A
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: none
 - Networking: inside VM
 - Storage: local

**To Reproduce**
This is the method I've used that brought me further. With other methods the server is not starting due to errors.
***Jellyfin Build***
1. git clone https://github.com/jellyfin/jellyfin.git
2. cd jellyfin
3. dotnet run --project Jellyfin.Server --webdir /xxx/jellyfin-web/
***Jellyfin Web Build***
1. git clone https://github.com/jellyfin/jellyfin-web.git
2. cd jellyfin-web
3. yarn install
4. yarn serve

**Expected behaviour**
When I access to localhost:8080, I would expect to get to the wizard and the wizard should work

**Logs**
- No errors reported on the terminal where the server is running
- Errors reported on the web console: see screenshot below
**Screenshots**
Web page:
![image](https://user-images.githubusercontent.com/10064696/104617752-1dc82c00-568c-11eb-9068-20968ad47373.png)
Errors:
![image](https://user-images.githubusercontent.com/10064696/104617177-6af7ce00-568b-11eb-8d00-406cd159d395.png)

**Additional context**
Please refer to issue #3132 as the described behaviour seems the same

**Comment by Ullmie02** [comment]
I can't reproduce this problem. I think you're running the wrong commands in the wrong order. These are the correct commands to set you environment up for server development/testing:

1. Clone jellyfin/jellyfin-web
2. Run `yarn install` and `yarn build:production` in the web repository
3. Clone jellyfin/jellyfin
4. Run `dotnet run --project Jellyfin.Server --webdir /path/to/jellyfin-web/dist`

Then you can access the local build of Jellyfin at `http://localhsot:8096`
Note: It is important that you pass the dist directory as the `webdir` argument. This folder gets created during `yarn build:production`

**Comment by kn-f** [comment]
@Ullmie02 works like a charm, thanks a lot!
Maybe would be beneficial updating the docs especially indicating to use `yarn build:production` and point at the directory created by the build process.
