### ISSUE TITLE
Previous/Next Episode Should be Synced in Shared Players

### ISSUE THREAD

**Issue by SethFalco** [jellyfin/jellyfin#5023]
**Describe the bug**

If I'm in a group with other users, we're able to play, pause, and change timestamp in sync effortlessly.  
However, in a series, going to the next or previous episode disbands the group.

I believe this behavior is unexpected; this behavior makes the user have to recreate the group between every episode.

**System (please complete the following information):**
 - OS: Ubuntu 18.04.5 LTS x86_64
 - Virtualization: Docker
 - Clients: Browser
 - Browser: 84.0.2 (64-bit)
 - Jellyfin Version: 10.6.4
 - Playback: Direct Stream / Transcode
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: none
 - Networking: Host
 - Storage: Local

**To Reproduce**

1. Go to an episode of a series.
2. Press the button to create a group.
3. Have another client join the group.
4. Press the button to go to the next episode.

**Expected behavior**

The group should go to the next episode together.

**Logs**

N/A

**Screenshots**

![out](https://user-images.githubusercontent.com/22801583/104654008-be821000-56bb-11eb-9dca-60a8e7e27d4f.gif)  
> Example of the behavior occuring with two side-by-side clients.

**Additional context**

N/A

**Comment by crobibero** [comment]
https://github.com/jellyfin/jellyfin/pull/3194
