### ISSUE TITLE
jellyfin doesn't show the poster of multi-video folder , even if poster be assigned in .nfo  

### ISSUE THREAD

**Issue by eromoe** [jellyfin/jellyfin#5028]
I found this issue only happen on folders contain multiple video files  .

For example:
this is a movie which have two files 
![image](https://user-images.githubusercontent.com/3938751/104808386-cdce9e00-5820-11eb-894f-9ea17b379f69.png)

nfo contain poster :
```
  <poster>ASFB-132-poster.jpg</poster>
  <thumb>ASFB-132-thumb.jpg</thumb>
  <fanart>ASFB-132-fanart.jpg</fanart>
```

Instead, jellyfin show files seperated 
![image](https://user-images.githubusercontent.com/3938751/104808421-2867fa00-5821-11eb-9a1a-7a825a48263c.png)

**System (please complete the following information):**
 - OS: windows
 - Jellyfin Version: 10.6.4

This case is similar to https://github.com/jellyfin/jellyfin/issues/2697 . 
But .nfo should be in charge of rendering

**Comment by Ullmie02** [comment]
Yes, currently Jellyfin doesn't read the `poster`, `thumb` and `fanart` nfo tags. But I'm not even sure your nfo file gets picked up. The nfo filename should either be:

- the same as your mkv files but with the .nfo fileextension instead of the .mkv file extension, or
- movie.nfo.

**Comment by eromoe** [comment]
Could it be possible to treat a folder with only one `.nfo` file as a movie folder ?
Because we usually don't like to mix up many different movies with their nfo , poster ... at same folder, provide this option to user would be much ideal I think .

**Comment by Ullmie02** [comment]
The pictures you provided show two video files in one folder and two items in Jellyfin.
It these two video files should be parsed as multiple versions (e.g. one theatrical release and a directors cut) of the same movie, you have to name them according to our [naming guidelines](https://jellyfin.org/docs/general/server/media/movies.html#multiple-versions-of-a-movie)

**Comment by eromoe** [comment]
It would be much more kind for us if we don't need to rename those files.
1. Usually a movie torrent would have a top folder 
2. Usually the downloaded files  already have ordered by the their name. 
3. If a torrent have multiple different movies , in wrost case,  it would list all movies in same layer without any .nfo files or posters.  Only on this case  we need rename the files and put them into correct folder

So I think it would be a very good option if  could provide .

**Comment by IamMattM** [comment]
I have the same problem as you whereby the video lock is not maintained and the Hub reverts to the Google photos slides while the jellyfin server audio part of the stream can still be heard. Nowhere is the jellyfin app to be found within the hub User interface.

Jellyfin server: 
Version: 10.8.0
Operating System: Linux
Architecture: X64

Nest Hub Gen1 : 
Fuschia O.S> version: 6.20211109.1.3166212
Cast Frimware Version: 1.60.302700

**Comment by srcrist** [comment]
The need to adhere to the naming conventions in the Jellyfin documentation is an intentional design choice that various aspects of the server use to parse the media and its metadata. Closing this issue as it is not actually a bug.
