### ISSUE TITLE
Able to go negative page numbering

### ISSUE THREAD

**Issue by agilob** [jellyfin/jellyfin#503]
This is probably inherited from Emby and linked to a race condition on request-> response level.

1. Click on next page (takes a few seconds - network lag)
2. Click twice on previous page, wait a few seconds
3. Repeat

![screenshot_20190107_215438](https://user-images.githubusercontent.com/2544251/50795705-ff720d80-12c6-11e9-894e-64c057f9031e.png)

Seems like the "previous page" button is only disabled when lower boundary is 0:

![screenshot_20190107_215727](https://user-images.githubusercontent.com/2544251/50795805-57107900-12c7-11e9-829b-5cf8a879ceb0.png)

**Comment by cvium** [comment]
I would like to add that it's a general problem. I accidentally added the same library twice because of a slow response.

**Comment by hawken93** [comment]
Looking at the pagination code I want to note that splitting the paginator code from the individual libraries so it can share common logic is a possible improvement

**Comment by hawken93** [comment]
**performance optimalization possibility**

The javascript calls ApiClient.GetItems() before filtering them to the current page. This means that each pagination actually downloads information about all the items in the library before filtering them on the client side. This wastes lots of resources and should be done on the server side.

**Comment by JustAMan** [comment]
> Looking at the pagination code I want to note that splitting the paginator code from the individual libraries so it can share common logic is a possible improvement

This seems to be the most fruitful approach, usually the less _almost_ copy-paste is there the easier it is to maintain stuff.

**Comment by hawken93** [comment]
to quote myself: I don't think I'll be trying to unify the pagination code in this PR, but if someone wants do that that then please merge them before this

**Comment by hawken93** [comment]
I'm ready for review on the PR above now :)

**Comment by hawken93** [comment]
@cvium I've also fixed the library double adding thing, so now it shows the loading indicator and ignores multiple presses until the action has returned a result :)
