### ISSUE TITLE
Cannot edit Play Lists. Play lists created and where media added show up empty

### ISSUE THREAD

**Issue by tchap2** [jellyfin/jellyfin#5034]
**Describe the bug**
Upon creation of a Playlist, list cannot be edite nor deleted.
WHen adding several medias to an existing Play List, play list contents show empty.

**System (please complete the following information):**
 - OS:  - UNRAID
 - Virtualization: [e.g. Docker, KVM, LXC]
 - Docker
 - Clients: [Browser, Android, Fire Stick, etc.]
 - ALL browsers, ALL smartpads/phones, local WEB gui from docker
 - Browser: [e.g. Firefox 72, Chrome 80, Safari 13]
 - ALL of them
 - Jellyfin Version: [e.g. 10.4.3, nightly 20191231]
 - unknown
 - Playback: [Direct Play, Remux, Direct Stream, Transcode] 
 - Installed Plugins: [e.g. none, Fanart, Anime, etc.]
 - none
 - Reverse Proxy: [e.g. none, nginx, apache, etc.]
 - Base URL: [e.g. none, yes: /example]
 - Networking: [e.g. Host, Bridge/NAT]
 - Storage: [e.g. local, NFS, cloud]
 - local server

**To Reproduce**

**Expected behavior**

edit or delete a list. 
see contents of list

**Logs**

**Screenshots**

**Additional context**

**Comment by cvium** [comment]
Any logs?
