### ISSUE TITLE
Jellyfin client cannot play .MKV files but Infuse connected to Jellyfin server can.

### ISSUE THREAD

**Issue by tchap2** [jellyfin/jellyfin#5035]
**Describe the bug**

MKV files cannot be played

**System (please complete the following information):**
 - OS: [e.g. Debian, Windows]
 - UNRAID
 - Virtualization: [e.g. Docker, KVM, LXC]
 - Docker
 - Clients: [Browser, Android, Fire Stick, etc.]
 - ALL listed
 - Browser: [e.g. Firefox 72, Chrome 80, Safari 13]
 - ALL listed
 - Jellyfin Version: [e.g. 10.4.3, nightly 20191231]
 - Playback: [Direct Play, Remux, Direct Stream, Transcode] 
 - Installed Plugins: [e.g. none, Fanart, Anime, etc.]
 - none
 - Reverse Proxy: [e.g. none, nginx, apache, etc.]
 - Base URL: [e.g. none, yes: /example]
 - Networking: [e.g. Host, Bridge/NAT]
 - Storage: [e.g. local, NFS, cloud]

**To Reproduce**

**Expected behavior**

play mkv files.

**Logs**

**Screenshots**

**Additional context**

**Comment by svemonix** [comment]
This is most likely not a bug. Different clients have different playback capabilities.

**Comment by cvium** [comment]
Not enough information...
