### ISSUE TITLE
Cannot change WEB GUI port

### ISSUE THREAD

**Issue by tchap2** [jellyfin/jellyfin#5036]
**Describe the bug**
Upon changin webgui port, the GUI cannot be accessed

**System (please complete the following information):**
 - OS: [e.g. Debian, Windows]
 - UNRAID jellyfin/jellyfin
 - Virtualization: [e.g. Docker, KVM, LXC]
 - docker
 - Clients: [Browser, Android, Fire Stick, etc.]
 - browser
 - Browser: [e.g. Firefox 72, Chrome 80, Safari 13]
 - ALL
 - Jellyfin Version: [e.g. 10.4.3, nightly 20191231]
 - jellyfin/jellyfin
 - Playback: [Direct Play, Remux, Direct Stream, Transcode] 
 - Installed Plugins: [e.g. none, Fanart, Anime, etc.]
 - Reverse Proxy: [e.g. none, nginx, apache, etc.]
 - Base URL: [e.g. none, yes: /example]
 - Networking: [e.g. Host, Bridge/NAT]
 - Storage: [e.g. local, NFS, cloud]

**To Reproduce**

**Expected behavior**

**Logs**

**Screenshots**

**Additional context**

**Comment by cvium** [comment]
The web ui doesn't have its own port. Please include more details...
