### ISSUE TITLE
Cannot access web GUI

### ISSUE THREAD

**Issue by tchap2** [jellyfin/jellyfin#5037]
**Describe the bug**

Installed jellyfin/jellyfin on UNRAID as a docker
cann start webgui with default port 8096

**System (please complete the following information):**
 - OS: [e.g. Debian, Windows]
 - Virtualization: [e.g. Docker, KVM, LXC]
 - Clients: [Browser, Android, Fire Stick, etc.]
 - Browser: [e.g. Firefox 72, Chrome 80, Safari 13]
 - Jellyfin Version: [e.g. 10.4.3, nightly 20191231]
 - Playback: [Direct Play, Remux, Direct Stream, Transcode] 
 - Installed Plugins: [e.g. none, Fanart, Anime, etc.]
 - Reverse Proxy: [e.g. none, nginx, apache, etc.]
 - Base URL: [e.g. none, yes: /example]
 - Networking: [e.g. Host, Bridge/NAT]
 - Storage: [e.g. local, NFS, cloud]

**To Reproduce**

**Expected behavior**

**Logs**

**Screenshots**

**Additional context**

**Comment by Ullmie02** [comment]
Hey @tchap2
This usually means you haven't mapped your Docker ports correctly. To access the Jellyfin Web UI (hosted inside a docker Container) on Host Port 8096, you have to map the container port 8096 to the host port 8096. If you change the Port the Jellyfin Webserver listens on in the Jellyfin settings (like you mentioned in #5036)  you have to change the Docker Port Mapping. Simply set the port you entered in the Jellyfin settings as your container port. But bear in mind that you can only access Jellyfin from outside the Docker container with the host port you set.
