### ISSUE TITLE
Jellyfin never releases memory

### ISSUE THREAD

**Issue by fristys** [jellyfin/jellyfin#5041]
**Describe the bug**
I've recently switched from Plex to Jellyfin via the official Docker image and have noticed that the container's memory usage climbs steadily as it's used, but never goes back down once its idle or unused. The only fix I have for it right now is to restart the container when it gets quite high. Could this be a possible memory leak? Any ideas for a solution?

**System:**
 - Virtualization: Docker
 - Jellyfin Version: 10.6.4
 - Installed Plugins: None
 - Reverse Proxy: none
 - Networking: Host
 - Storage: local

**Comment by Hyask** [comment]
It seems I have the same kind of behavior running Jellyfin 10.6.4 from linuxserver.io's Docker image, on an Helios 64 NAS. After a fresh start, it takes less than 400MB of RAM to run fine, and after some time, even my whole swap has been filled up. I will update how many time later, as I'm still measuring precisely, but it seems to be about a day or two.

**Comment by Sidefix** [comment]
I am also observing similar behavior when running on Ubuntu x64 with Jellyfin 10.7.0rc2

The memory utilization on startup will be around 200-400MB and then steadily climb and will never drop unless restarted.

**Comment by svemonix** [comment]
From what I see in my Docker with the official 1.6.4:
1. the memory usage grows with the server usage
2. it feels like it is .NET that is not releasing memory like if .NET in the container was not aware of the physical memory available on the host.
3. Limiting the physical memory available to the container seems to work fine as a workaround. I've been doing that for months.

**Comment by ddurdle** [comment]
I'm finding similar on both the official docker image and on the linuxserver.io docker.  

What I noticed is that when a folder or full scan is performed, the memory will increase rapidly and not settle down afterwards.  Repeated scans will cause it to increase the same amount each time.  Eventually the system runs out of memory.

My library db size is 2GB and it seems each scan causes the memory consumed to increase by 2GB.  After letting it settle after many hours, it might drop a few hundred MB, if no subsequent scans are done.

Has been happening on 10.7.0-RC1 - 10.7.1.  Cannot reproduce the issue on 10.4, 10.5, 10.6.3

**Comment by ddurdle** [comment]
> From what I see in my Docker with the official 1.6.4:
> 
> 1. the memory usage grows with the server usage
> 2. it feels like it is .NET that is not releasing memory like if .NET in the container was not aware of the physical memory available on the host.
> 3. Limiting the physical memory available to the container seems to work fine as a workaround. The memory usage climbs to the limit value, garbage collection kicks in and memory usage drops to a fresh start level. I've been doing that for months.


3. is a good idea but doesn't help.  I did some tests on my 2GB library.db install.  I'll allocate it 2.5GB memory and 2.5GB swap.  I'll start up the container, it'll do it's customary cycle of the db.  Not sure what's it exactly doing, but it cycles through the db creating a db-journal of equivalent size, loading the entire db into memory.  I'll see it do this, then it drops the memory back down to 1GB after it has successfully started.  If I invoke a scan it'll start leaking memory immediately and instead of forcing it to release the garbage, the container crashes when it's out of memory.

**Comment by cvium** [comment]
I'm kind of curious how your library.db is this big. What is the size of your library?

> If you want a quick test case, all you need to do is boot up a JF and hit full library scan, let it finish and hit it again. It'll never release enough of the memory it consumes as part of the scan and it'll quickly crash.

My library.db is only 104 MB but no matter how many times I hit Scan all libraries button the memory usage doesn't grow excessively.

![image](https://user-images.githubusercontent.com/675118/112227393-e3e94800-8c2f-11eb-8550-7d74826c1f4c.png)


Regarding this https://github.com/jellyfin/jellyfin/issues/5592#issuecomment-805017177, you don't need a debug version to dump the memory.

**Comment by danilevy1212** [comment]
This is happening to me in my raspberry pi, still an issue

**Comment by Paraxes** [comment]
Same here with the server version on a Synology NAS DS918+. Can easily be checked/confirmed with repeated library scans.

**Comment by skill7899** [comment]
Also occurring in PVE, when i use lxc run jellyfin ,  Can easily be checked/confirmed with repeated library scans.

**Comment by cvium** [comment]
I use lxc and I don't have any issues
