### ISSUE TITLE
Cache+Metadata filling up space on local storage on NAS

### ISSUE THREAD

**Issue by natrius** [jellyfin/jellyfin#5044]
**Describe the bug**

Installed JellyFin on my Helios64 and it filled up all the space on my NAS with "cache" and "metadata". In the settings i was able to change the path but unfortunately this did not move the existing data so i had to do that manually because my nas was not even able to start OpenMediaVault or JellyFin.

**System (please complete the following information):**
 - OS: Armbian
 - Virtualization: none
 - Clients: FF
 - Browser: FF
 - Jellyfin Version: 10.6.4
 - Playback: [Direct Play, Remux, Direct Stream, Transcode] 
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: none
 - Storage: NAS

**To Reproduce**
1. Install JellyFin on a Server with 14GB space
2. Load movies until space is full
3. Change path to metadata and cache
4. Cache and Metadata stays and space is still full

**Expected behavior**
Ask if existing metadata and cache should get moved when changing path.

**Comment by BaronGreenback** [comment]
The system worked as expected. 

Moving of metadata/cache and files is outside of the scope of JF, and is an administrative function.

**Comment by natrius** [comment]
In this case, ask when installing if this data should be stored there or choose another location. With the hint, this might need a lot of space.  This is in the scope of JF in my opinion :)

**Comment by natrius** [comment]
Is there anything that can be done to solve this? This way its basically useless to install jellyfin on a NAS currently :/
