### ISSUE TITLE
Fail2ban Regex Filter - HowTo

### ISSUE THREAD

**Issue by gotton** [jellyfin/jellyfin#5057]
Hello,

A little how-to to create a filter and a jail for Jellyfin 10.6.4 working with Fail2ban. Could need a modification if logs synthax evolved. This little how-to assumed that you already have Fail2ban running and up to date :

You need to know the localisation of Fail2ban jail and conf and the localisation of logs for jellyfin (in my case here /var/log/jellyfin/).

I'm using ubuntu 20.04 and nano as editor. 

**FIRST STEP** : create a jail

`sudo nano /etc/fail2ban/jail.d/jellyfin.local`

And add this to the file : 

[jellyfin]
backend = auto
enabled = true
port = 80,443
protocol = tcp
filter = jellyfin
maxretry = 3
bantime = 86400
findtime = 43200
logpath = /var/log/jellyfin/jellyfin*.log

save and exit, then : 

**SECOND STEP :** Create Filter

`sudo nano /etc/fail2ban/filter.d/jellyfin.conf`

And add this to the knew file (thanks to @sebres from F2B) : 

`[Definition]`
`failregex = ^(?:\[\]\s+)?\[INF\] Authentication request for "[^"]*" has been denied \(IP: "<HOST>"\)\.$`

save and exit

You're done.

**STEP 3 :** Test 

You can try it via this command (in this exemple, i choose a log specificaly because i knew it was containing the information needed).

`fail2ban-regex /var/log/jellyfin/jellyfin20210117.log /etc/fail2ban/filter.d/jellyfin.conf`

Then you need to restart Fail2ban to use the jail : 

`sudo systemctl restart fail2ban.service`

That's it.

**Comment by Ullmie02** [comment]
Thanks for your contribution!
However, I think this doesn't belongs here as this is not a bug or a feature request. I think the best place for this would either be the [Jellyfin Documentation](https://docs.jellyfin.org) or our [Forum](https://forum.jellyfin.org). Feel free to open a Pull Request at our [Dokumentation repo](https://github.com/jellyfin/jellyfin-docs)!

**Comment by cvium** [comment]
https://github.com/jellyfin/jellyfin-docs/blob/20e56b8b32c98d015adf6b0b1565564f788a224a/general/networking/fail2ban.md
