### ISSUE TITLE
Folders are not correctly parsed

### ISSUE THREAD

**Issue by mikebakke** [jellyfin/jellyfin#5059]
**Describe the bug**
I have a library structure organised in folders - example:
ARTIST
       => BEASTIE BOYS
            - file1.mp4
            - file2.mp4
       => BEYONCE
            - file1.mp4
       => BRIAN WILSON
            - file1.mp4
            - file2.mp4

After scanning the folders with multiple files are all displayed first in the correct sequence as expected and opening them correctly shows the files inside them.

However - all the folders with one file only are displayed after the last multi-file folder. In addition the title of the single file is lost - all that is displayed is the folder (artist) name. 

See screenshot.
**System (please complete the following information):**
 - OS: ubuntu
 - Virtualization: docker
 - Clients: firefox, android
 - Jellyfin Version: 10.6.4
  - Storage: local

**To Reproduce**

**Expected behavior**
I expect every folder to be displayed as a folder and inside, whatever files with the correct filename

**Screenshots**
![folders](https://user-images.githubusercontent.com/55141164/104947456-b1af3600-59b3-11eb-9507-6cd20d72105d.png)

**Comment by nonobio** [comment]
Hi,
It is similar to my issued: https://github.com/jellyfin/jellyfin/issues/9221#issuecomment-1636713205
