### ISSUE TITLE
User avatars are accessible without authentification

### ISSUE THREAD

**Issue by MayeulC** [jellyfin/jellyfin#5060]
**Describe the bug**
Not sure this is a huge liability, but user avatars can be accessed without authentication.

**System (please complete the following information):**
 - OS: Debian
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Firefox
 - Jellyfin Version: 10.7.0 (unstable tag)
 - Installed Plugins: none
 - Reverse Proxy: nginx
 - Base URL: [e.g. none, yes: /example]
 - Networking: Host
 - Storage: local

**To Reproduce**
1. Log in as a user
2. Open user profile
3. Set a user picture
4. In a private browsing session, open the picture URL (https://example.com/Users/aaaaaaaabcdesomethingabcde/Images/Primary)

**Expected behavior**
At least only logged in users should be able to see the picture.

Maybe only allow relevant users like administrators, and those in the synclpay group to see the picture... I haven't explored profiles much yet.

**Comment by crobibero** [comment]
That’s expected, the profile images are displayed on the login page for public users.

**Comment by MayeulC** [comment]
Thank you for pointing this out. But then, wouldn't that apply only to such public users?

I don't mind too much since the "user string" (?) would be hard to bruteforce, but since it is a static identifier, it could be indexed by a search engine if it ends up somewhere.

**Comment by nielsvanvelzen** [comment]
Some of our clients will save user information after signing into them once. When they show those users on the login screen they need to fetch the profile picture too.
