### ISSUE TITLE
The Fedora/CentOS stable release appears to be tracking ahead of the other distros

### ISSUE THREAD

**Issue by jceresini** [jellyfin/jellyfin#5061]
https://jellyfin.org/downloads/

The CentOS and Fedora stable releases pages (https://repo.jellyfin.org/releases/server/fedora/stable/ and https://repo.jellyfin.org/releases/server/centos/stable/) provide links to install 10.7rc2

I noticed that macos, windows, generic linux, and docker all provide 10.6.4 as the stable release (I didn't check arch or debian)

I'm new to jellyfin and I typically run centos, so I started with 10.7 since it was listed as the stable release. I've run into some issues with the KodiSyncQueue plugin, and found a few issues in github indicating known issues with some 10.7 releases. I'm guessing Centos and Fedora should list 10.6.4 as the stable release, and I assume I wouldn't be having issues if that's what I had started with.

To be completely honest, the various error messages I got in Kodi almost turned me away from Jellyfin. Now that I realize it may just be because I'm running a release candidate I'll probably start fresh and give it another try. I wanted to let you know in case others have similar issues.

**Comment by cvium** [comment]
Shouldn't happen again
