### ISSUE TITLE
Sync Play with music can't empty playlist 

### ISSUE THREAD

**Issue by Uatschitchun** [jellyfin/jellyfin#5065]
**Describe the bug**
When using Syncplay to play music, it's not possible to empty the playlist. Choosing the option in playlist's menu simply does nothing 

**System (please complete the following information):**
 - OS: Linux 
 - Virtualization: Docker
 - Clients: Browser, jellyfin app 
 - Browser: Opera 
 - Jellyfin Version: unstable 
 - Playback: Direct Play

**To Reproduce**
Start a Syncplay group, start playing music or add music to playlist, go to playlist menu and choose 'clear playlist' 

**Expected behavior**
Expected behavior would be it working like without Syncplay

**Logs**
Haven't got any logs yet, will provide if needed

**Comment by OancaAndrei** [comment]
Thanks for the finding.
This is probably an issue on the client side not calling the proper endpoint. I'll have to check as I've probably missed that button.

Does removing a single item from the playlist work?

*I hope to find some free time in the following weeks as this looks like something easy to fix (unfortunately I'm a bit busy lately).*

**Comment by Uatschitchun** [comment]
Tested: Removing single items from playlist works!
