### ISSUE TITLE
Video stream title attribute overwrites Video codec in Jelly library view

### ISSUE THREAD

**Issue by rayures** [jellyfin/jellyfin#5066]
**Describe the bug**

When a mkv video stream has the attribute 'title' set, this information is being used in the library view as 'video' information instead of the video codec info. i think the codec info should always be displayed.

**System (please complete the following information):**
 - OS: Debian
 - Virtualization: Docker
 - Clients: [Browser, Android, Fire Stick, etc.]
 - Browser: [e.g. Firefox 72, Chrome 80, Safari 13]
 - Jellyfin Version: Master 2021-01-20
 - Playback: 
 - Installed Plugins: 
 - Reverse Proxy: 
 - Base URL: 
 - Networking:
 - Storage:

**To Reproduce**

**Expected behavior**

**Logs**

**Screenshots**

mkv with video stream 'title' set: 
![image](https://user-images.githubusercontent.com/5716188/105202139-f2d55080-5b41-11eb-948f-f43773f0946c.png)
jelly library: 
![image](https://user-images.githubusercontent.com/5716188/105201719-793d6280-5b41-11eb-92cf-c9e0be85f48c.png)

when removing the 'title'  from the video stream via mkvtoolnix the resulting mkv has no 'title' attribuut. 
![image](https://user-images.githubusercontent.com/5716188/105202205-0385c680-5b42-11eb-9ebd-2c9ab249a394.png)

and jelly displays:
![image](https://user-images.githubusercontent.com/5716188/105202243-0f718880-5b42-11eb-92cc-540a6c37857d.png)

video information shows: 
![image](https://user-images.githubusercontent.com/5716188/105202734-958dcf00-5b42-11eb-835e-22b7b9417dd7.png)

so, question isperhaps, is 'title' used properly with 'video' information?

**Additional context**

**Comment by BaronGreenback** [comment]
Which client are you using - so i can trace back where the property is coming from?

Is it effecting anything else - or just a display thing?

**Comment by rayures** [comment]
Jellyfin-web as client. 

Just a display thing.
