### ISSUE TITLE
HDR Tone Mapping is very slow in Jellyfin (19fps, 70% cpu) compared to Plex (60fps, 20% cpu) - Intel 9th gen VAAPI

### ISSUE THREAD

**Issue by pgjensen** [jellyfin/jellyfin#5067]
**Describe the bug**
When HDR Tone Mapping is enabled and transcoding is required, it can never keep up on my modern Xeon E2276G system with iGPU.

**System (please complete the following information):**
 - OS: Ubuntu 20.04 LTS with HWE 5.8 kernel
 - Virtualization: No
 - Clients: Android, Android TV
 - Browser: Chrome 87
 - Jellyfin Version: 10.7.0-rc2
 - Playback: Transcode
 - Installed Plugins: None
 - Reverse Proxy: None
 - Base URL: None
 - Networking: Host
 - Storage: Local

**To Reproduce**

1. Download the sample file "The World In HDR 4K Demo.mkv" from https://drive.google.com/file/d/1rJFffBPl69B3hFKAPaxKYrtmXcnWcdF8/view
2. Add it as a Movie (I used the movie "FAKE (2016)"
3. Enable Hardware Transcoding and HDR Tone Mapping (defaults)
4. Watch it on an SDR device and notice the stuttering constantly occurring
5. See in the Dashboard the low fps (19) of transcoding
6. Repeat the same steps in the latest Plex Media Server/client
7. See the video smoothly transcode

**Expected behavior**
Faster transcoding on hardware that supports it

**Logs**
Plex transcode:
```
/usr/lib/plexmediaserver/Plex Transcoder -codec:0 hevc -hwaccel:0 vaapi -hwaccel_fallback_threshold:0 10 -hwaccel_output_format:0 vaapi -hwaccel_device:0 vaapi -codec:1 vorbis -analyzeduration 20000000 -probesize 20000000 -i /mnt/storage/movies-uhd-test/FAKE.2016.2160p.UHD.HDR.The.World.In.HDR.4K.Demo-Jellyfin/The World In HDR 4K Demo.mkv -filter_complex [0:0]hwupload[0];[0]scale_vaapi=w=2276:h=1280:format=p010[1];[1]hwmap=derive_device=opencl[2];[2]tonemap_opencl=tonemap=mobius:format=nv12:m=bt709:p=bt709:r=tv[3];[3]hwmap=derive_device=vaapi:reverse=1[4];[4]hwupload[5] -filter_complex [0:1] aresample=async=1:ocl='stereo':rematrix_maxval=0.000000dB:osr=44100[6] -map [5] -codec:0 h264_vaapi -b:0 8408k -maxrate:0 11211k -bufsize:0 22422k -r:0 59.939999999999998 -force_key_frames:0 expr:gte(t,0+n_forced*1) -map [6] -metadata:s:1 language=eng -codec:1 aac -b:1 115k -f dash -seg_duration 1 -init_seg_name init-stream$RepresentationID$.m4s -media_seg_name chunk-stream$RepresentationID$-$Number%05d$.m4s -window_size 5 -delete_removed false -skip_to_segment 1 -time_delta 0.0625 -manifest_name http://127.0.0.1:32400/video/:/transcode/session/xlbgccgiq81dzxrou7rklxf4/fdcbbcb3-c41f-4e73-8d7f-b63c86c4b84c/manifest?X-Plex-Http-Pipeline=infinite -avoid_negative_ts disabled -map_metadata -1 -map_chapters -1 dash -start_at_zero -copyts -vsync cfr -init_hw_device vaapi=vaapi: -filter_hw_device vaapi -y -nostats -loglevel quiet -loglevel_plex error -progressurl http://127.0.0.1:32400/video/:/transcode/session/xlbgccgiq81dzxrou7rklxf4/fdcbbcb3-c41f-4e73-8d7f-b63c86c4b84c/progress
```

Jellyfin transcode:
```
 /usr/lib/jellyfin-ffmpeg/ffmpeg -hwaccel vaapi -init_hw_device vaapi=va:/dev/dri/renderD128 -init_hw_device opencl=ocl@va -hwaccel_device va -hwaccel_output_format vaapi -filter_hw_device ocl -i file:/mnt/storage/movies-uhd-test/FAKE.2016.2160p.UHD.HDR.The.World.In.HDR.4K.Demo-Jellyfin/The World In HDR 4K Demo.mkv -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_vaapi -b:v 27877813 -maxrate 27877813 -bufsize 55755626 -profile:v:0 high -level 41 -force_key_frames:0 expr:gte(t,0+n_forced*3) -vf scale_vaapi=format=p010:out_range=limited,hwmap,tonemap_opencl=format=nv12:primaries=bt709:transfer=bt709:matrix=bt709:tonemap=hable:desat=0:threshold=0.8:peak=0,hwmap=derive_device=vaapi:reverse=1 -start_at_zero -vsync -1 -codec:a:0 aac -ac 2 -ab 384000 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_segment_filename /mnt/ramdisk/jellyfin/transcodes/93db3d0581b6970c31b902d042ec0f78%d.ts -hls_playlist_type vod -hls_list_size 0 -y /mnt/ramdisk/jellyfin/transcodes/93db3d0581b6970c31b902d042ec0f78.m3u8
```
**Screenshots**
None

**Additional context**
- Using the latest Intel VAAPI drivers from https://software.intel.com/content/www/us/en/develop/topics/graphics-linux-drivers.html on Ubuntu 20.04 LTE with HWE kernel 5.8 - Version: 21.01.18793+i455~u20.04
- CPU uitilization on Jellyfin is 70%
- CPU utilization on Plex is 20%
- Maxrate on Jellyfin is very high (27877813) vs Plex (11211k), but even changing jellyfin to match doesn't make a difference (tried "-b:v 8408k -maxrate 11211k -bufsize 22422k")

**Comment by pgjensen** [comment]
[Log.txt](https://github.com/jellyfin/jellyfin/files/5844084/Log.txt)

Attached Jellyfin log

**Comment by nyanmisaka** [comment]
Plex is tonemapping and transcoding to `scale_vaapi=w=2276:h=1280:format=p010` while jellyfin kept the original resolution `scale_vaapi=format=p010` 3840x2160. I don't think Intel Gen9.5 iGPU can handle 4k tonemapping well.

**Comment by pgjensen** [comment]
> Plex is tonemapping and transcoding to `scale_vaapi=w=2276:h=1280:format=p010` 2276x1280 while Jellyfin kept the original resolution `scale_vaapi=format=p010` 3840x2160. I don't think Intel Gen9.5 iGPU can handle 4k tonemapping well. Try to lower the target bitrate.

I adjusted that in the jellyfin commandline and the FPS jumped to 48fps but the CPU utilization was still at 70% compared to much lower in Plex.

Is there a way to force the transcoding to 1080p resolution that would at least keep up?  I'd rather lose a little quality but be able to watch the content on my SDR devices (or situations that require a transcode).

**Comment by ThierryBegin** [comment]
I retried with latest docker version and the issue still persist, its really the only last thing keeping me from dumping plex. For some reason the CPU is always also being used when transcoding with the gpu ( im using a p2000) .

**Comment by pgjensen** [comment]
I recently switched away from VAAPI to NVENC and have the same problems, so I don't think it's necessarily specific to Intel vs nVidia, but rather ffmpeg implementation.

**Comment by wuzzboy** [comment]
Same here, tonemaping kills my system allso.

**Comment by nyanmisaka** [comment]
> Same here, tonemaping kills my system allso.

Can you share the ffmpeg transcoding log and your GPU model?

**Comment by ThierryBegin** [comment]
> > Same here, tonemaping kills my system allso.
> 
> Can you share the ffmpeg transcoding log and your GPU model?

I did a reddit post a while back, maybe it will help: https://www.reddit.com/r/jellyfin/comments/mzb5f8/transcode_hdr_content/
I also went on the Matrix support channel and we couldn't figure it out. I guess just not many people do hdr content to sdr yet.

**Comment by nyanmisaka** [comment]
> I also went on the Matrix support channel and we couldn't figure it out. I guess just not many people do hdr content to sdr yet.

I think the overhead is caused by the limited PCIe bandwidth when using OpenCL tonemap filter. Can you install the jellyfin-ffmpeg 4.4-1 from [here](https://drive.google.com/drive/folders/1u13Ot4A0YySraS_7y06XwfErj7W0NUIO?usp=sharing) and run the command down below to test performance.

Minimum required Nvidia driver versions:
Linux: 455.28 or newer
Windows: 456.71 or newer

4k HDR(PQ) -> 1080p SDR(BT709) 15M
```
/usr/lib/jellyfin-ffmpeg/ffmpeg -hwaccel cuda -hwaccel_output_format -autorotate 0 -i "HDR.mp4" -an -sn -vf "scale_cuda=w=1920:h=1080:format=p010,setparams=colorspace=bt2020nc:color_trc=smpte2084:color_primaries=bt2020,tonemap_cuda=tonemap=bt2390:desat=0:peak=0:format=nv12" -c:v h264_nvenc -preset medium -bf 0 -b:v 15000000 -y SDR_1080p.mp4
```

4k HDR(PQ) -> 4k SDR(BT709) 30M
```
/usr/lib/jellyfin-ffmpeg/ffmpeg -hwaccel cuda -hwaccel_output_format -autorotate 0 -i "HDR.mp4" -an -sn -vf "scale_cuda=format=p010,setparams=colorspace=bt2020nc:color_trc=smpte2084:color_primaries=bt2020,tonemap_cuda=tonemap=bt2390:desat=0:peak=0:format=nv12" -c:v h264_nvenc -preset medium -bf 0 -b:v 30000000 -y "SDR_4k.mp4"
```

**Comment by ThierryBegin** [comment]
I get this: 
`/usr/lib/jellyfin-ffmpeg/ffmpeg -hwaccel cuda -hwaccel_output_format -autorotate 0 -i "HDR.mp4" -an -sn -vf "scale_cuda=w=1920:h=1080:format=p010,setparams=colorspace=bt2020nc:color_trc=smpte2084:color_primaries=bt2020,tonemap_cuda=tonemap=bt2390:desat=0:peak=0:format=nv12,setparams=colorspace=bt709:color_trc=bt709:color_primaries=bt709" -c:v h264_nvenc -preset medium -bf 0 -b:v 15000000 -y SDR_1080p.mp4
ffmpeg version 4.4-Jellyfin Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-gpl --enable-version3 --enable-static --enable-libfontconfig --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --arch=amd64 --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-vdpau --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvenc --enable-nvdec --enable-ffnvcodec
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'HDR.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 1
    compatible_brands: isom
    creation_time   : 2016-10-24T05:33:14.000000Z
  Duration: 00:01:26.10, start: 0.000000, bitrate: 71567 kb/s
  Stream #0:0(und): Video: hevc (Main 10) (hvc1 / 0x31637668), yuv420p10le(tv, bt2020nc/bt2020/smpte2084), 3840x2160 [SAR 1:1 DAR 16:9], 71382 kb/s, 59.94 fps, 59.94 tbr, 60k tbn, 59.94 tbc (default)
    Metadata:
      creation_time   : 2016-10-24T06:29:51.000000Z
      handler_name    : Video Media Handler
      vendor_id       : [0][0][0][0]
      encoder         : HEVC Coding
  Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 192 kb/s (default)
    Metadata:
      creation_time   : 2016-10-24T06:29:51.000000Z
      handler_name    : Sound Media Handler
      vendor_id       : [0][0][0][0]
Option hwaccel (use HW accelerated decoding) cannot be applied to output url 0 -- you are trying to apply an input option to an output file or vice versa. Move this option before the file it belongs to.
Error parsing options for output file 0.
Error opening output files: Invalid argument
`

**Comment by nyanmisaka** [comment]
> Error parsing options for output file 0.
> Error opening output files: Invalid argument

Change `SDR_1080p.mp4` to `/tmp/SDR_1080p.mp4`

**Comment by ThierryBegin** [comment]
Same issue apparently:
```
/usr/lib/jellyfin-ffmpeg/ffmpeg -hwaccel cuda -hwaccel_output_format -autorotate 0 -i "HDR.mp4" -an -sn -vf "scale_cuda=format=p010,setparams=colorspace=bt2020nc:color_trc=smpte2084:color_primaries=bt2020,tonemap_cuda=tonemap=bt2390:desat=0:peak=0:format=nv12,setparams=colorspace=bt709:color_trc=bt709:color_primaries=bt709" -c:v h264_nvenc -preset medium -bf 0 -b:v 30000000 -y "/tmp/SDR_4k.mp4"
ffmpeg version 4.4-Jellyfin Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-gpl --enable-version3 --enable-static --enable-libfontconfig --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --arch=amd64 --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-vdpau --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvenc --enable-nvdec --enable-ffnvcodec
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'HDR.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 1
    compatible_brands: isom
    creation_time   : 2016-10-24T05:33:14.000000Z
  Duration: 00:01:26.10, start: 0.000000, bitrate: 71567 kb/s
  Stream #0:0(und): Video: hevc (Main 10) (hvc1 / 0x31637668), yuv420p10le(tv, bt2020nc/bt2020/smpte2084), 3840x2160 [SAR 1:1 DAR 16:9], 71382 kb/s, 59.94 fps, 59.94 tbr, 60k tbn, 59.94 tbc (default)
    Metadata:
      creation_time   : 2016-10-24T06:29:51.000000Z
      handler_name    : Video Media Handler
      vendor_id       : [0][0][0][0]
      encoder         : HEVC Coding
  Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 192 kb/s (default)
    Metadata:
      creation_time   : 2016-10-24T06:29:51.000000Z
      handler_name    : Sound Media Handler
      vendor_id       : [0][0][0][0]
Option hwaccel (use HW accelerated decoding) cannot be applied to output url 0 -- you are trying to apply an input option to an output file or vice versa. Move this option before the file it belongs to.
Error parsing options for output file 0.
Error opening output files: Invalid argument
```

**Comment by nyanmisaka** [comment]
> Same issue apparently:

Oops. I put one parameter at wrong place.
Try this again.

```
/usr/lib/jellyfin-ffmpeg/ffmpeg -hwaccel cuda -hwaccel_output_format cuda -i "HDR.mp4" -an -sn -vf "scale_cuda=format=p010,setparams=colorspace=bt2020nc:color_trc=smpte2084:color_primaries=bt2020,tonemap_cuda=tonemap=bt2390:desat=0:peak=0:format=nv12,setparams=colorspace=bt709:color_trc=bt709:color_primaries=bt709" -c:v h264_nvenc -preset medium -b:v 15000000 -bf 0 -y "/tmp/SDR_1080p.mp4"
```

**Comment by pgjensen** [comment]
> > Same issue apparently:
> 
> Oops. I put one parameter at wrong place.
> Try this again.
> 
> ```
> /usr/lib/jellyfin-ffmpeg/ffmpeg -hwaccel cuda -hwaccel_output_format cuda -i "HDR.mp4" -an -sn -vf "scale_cuda=format=p010,setparams=colorspace=bt2020nc:color_trc=smpte2084:color_primaries=bt2020,tonemap_cuda=tonemap=bt2390:desat=0:peak=0:format=nv12,setparams=colorspace=bt709:color_trc=bt709:color_primaries=bt709" -c:v h264_nvenc -preset medium -b:v 15000000 -bf 0 -y "/tmp/SDR_1080p.mp4"
> ```

I ran this on /tmp/jellyfish-140-mbps-4k-uhd-hevc-10bit.mkv and it did keep up with ~32fps, but pegged one of my cpus at 100% the whole time.

**Comment by ThierryBegin** [comment]
133fps here, 25-30% cpu usage, not bad! now, not sure why it's not working with jellyfin-docker or installed normally. what do I need to do next step to make it work with JF ?

**Comment by nyanmisaka** [comment]
> I ran this on /tmp/jellyfish-140-mbps-4k-uhd-hevc-10bit.mkv and it did keep up with ~32fps, but pegged one of my cpus at 100% the whole time.

First, hardware acceleration doesn't mean no CPU usage at all.
FFmpeg have to demux, transcode and remux the frames.
Nvidia drivers itself also have some works that need to be done by one or more CPU thread.
In this pipeline, you transcoded a 4k HDR video to 4k SDR video within Cuda kernels without using any CPU based filters. But without HWA, even if a high end 8C16T CPU, the realtime fps can't reach 20fps.

What's your GPU model and PCIe bandwidth? I can get 80~100fps on a GTX 1050 4G(PCIe 3.0 x16 slot) using this command.

**Comment by nyanmisaka** [comment]
> 133fps here, 25-30% cpu usage, not bad! now, not sure why it's not working with jellyfin-docker or installed normally. what do I need to do next step to make it work with JF ?
> -edit- let me validate with another file...
> Confirming it's working. so just need to figure out the docker/native install issue

It should work with this PR #6327. You don't need to configure OpenCL runtime inside the docker.
Try it now if you want to run a custom build on that branch.

**Comment by pgjensen** [comment]
> > I ran this on /tmp/jellyfish-140-mbps-4k-uhd-hevc-10bit.mkv and it did keep up with ~32fps, but pegged one of my cpus at 100% the whole time.
> 
> First, hardware acceleration doesn't mean no CPU usage at all.
> FFmpeg have to demux, transcode and remux the frames.
> Nvidia drivers itself also have some works that need to be done by one or more CPU threads.
> 
> In this pipeline, you transcoded a 4k HDR video to 4k SDR video in Cuda kernels without using any CPU based filters. But without HWA, even if a high end 8C16T CPU, the realtime fps can't reach 20fps.
> 
> What's your GPU model and PCIe bandwidth? I can get 80~100fps on a GTX 1050 4G(PCIe 3.0 x16 slot) using this command.

nVidia Quadro P400 at pcie 3.0 x16 on a dual xeon e5-2680v4

**Comment by nyanmisaka** [comment]
> nVidia Quadro P400 at pcie 3.0 x16 on a dual xeon e5-2680v4

 256 Cuda cores and 2G VRAM of it should be the limitation. However GTX 1050 have 640 cuda cores.

I think it can handle up to two 4K streams or eight 1080p streams with Cuda tonemapping enabled.

**Comment by wuzzboy** [comment]
I have xeon E3-1270v5 and p400 v2. Works just fine with plex.

**Comment by nyanmisaka** [comment]
> I have xeon E3-1270v5 and p400 v2. Works just fine with plex.

It should work fine too in new jellyfin release with the PR I mentioned above.
So how about the CPU usage? Is there no CPU usage on ffmpeg or nvidia driver IRQ?

**Comment by wuzzboy** [comment]
That seems to do the trick. Cpu ideling away and gpu 100%. Is there an easy way for a noob to get this into "production" ?

**Comment by nyanmisaka** [comment]
Assumes you have the dotnet sdk 5 installed and want to get a native build of this PR:
```
git clone --branch tonemap-overlay --depth=1 https://github.com/nyanmisaka/jellyfin.git
cd jellyfin
./build.sh -t native -p ubuntu.amd64
cd ../bin/ubuntu.amd64
sudo apt install ./*.deb
```

If you want to get the BT.2390 option in web:
```
git clone --branch bt2390 --depth=1 https://github.com/nyanmisaka/jellyfin-web.git
cd jellyfin-web
./build.sh -t native -p debian.amd64
cd ../bin/debian.amd64
sudo apt install ./*.deb
```

(`ubuntu.amd64` can be replaced with `debian.amd64` or `windows.amd64`, use `./build.sh --help` for more details)

**Comment by wuzzboy** [comment]
I got an issue with the jellyfin web
`./build.sh -t native -p debian.amd64
./build.sh: line 38: deployment/build.debian.amd64: No such file or directory`

**Comment by nyanmisaka** [comment]
> Cant see an ubuntu file in the deployment folder.

Use `debian.amd64` instead.

**Comment by wuzzboy** [comment]
> > Cant see an ubuntu file in the deployment folder.
> 
> Use `debian.amd64` instead.

./build.sh -t native -p debian.amd64
./build.sh: line 38: deployment/build.debian.amd64: No such file or directory

**Comment by nyanmisaka** [comment]
> > > Cant see an ubuntu file in the deployment folder.
> > 
> > 
> > Use `debian.amd64` instead.
> 
> ./build.sh -t native -p debian.amd64
> ./build.sh: line 38: deployment/build.debian.amd64: No such file or directory

Should be `debian`.
