### ISSUE TITLE
4K HDR 10-bit movie not transcoding (Nvdia, Hvec, Ubuntu 20.04)

### ISSUE THREAD

**Issue by JerreBor** [jellyfin/jellyfin#5072]
**Media Info of the file**
![image](https://user-images.githubusercontent.com/28572014/105342100-37172e00-5be0-11eb-9252-d3bf885b7dfe.png)

**Logs**
[Jellyfinlogs (pastebin)](https://pastebin.com/uSG4bAQg)

**FFmpeg Logs**
[Transcoding logs (pastebin)](https://pastebin.com/DRe8WHqW)

**Stats for Nerds Screenshots**
The media does not start playing.

**Server System (please complete the following information):**
 - OS: Docker on Ubuntu 20.04
 - Jellyfin Version: 10.6.4
 - Hardware settings & device: Nvidia GTX 1060 (3gb), Driver version 460.32.03
 - Reverse proxy: no
 - Other hardware notes: Media mounted on different drive than Jellyfin (shouldn't be the issue, right?).
 
**Client System (please complete the following information):**
 - Device: Google Chrome on Windows 10 Laptop
 - OS: Windows 10
 - Client: Browser
 - Browser (if Web client): Google Chrome
 - Client and Browser Version: 87.0.4280.141
 
 The logs mention: `Cannot load libnvidia-encode.so.1`. When I run `apt list --installed | grep 'libnvidia-encode'` I see `libnvidia-encode-460/focal-updates,focal-security,now 460.32.03-0ubuntu0.20.04.1 amd64 [installed]` so it is in fact installed.
 
 Looking forward to your answers!

**Comment by crobibero** [comment]
Have you installed https://github.com/NVIDIA/nvidia-docker

**Comment by JerreBor** [comment]
Yes, `sudo docker run --rm --gpus all nvidia/cuda:11.0-base nvidia-smi` returns:
![image](https://user-images.githubusercontent.com/28572014/105351912-8021af00-5bed-11eb-8a54-38086475c574.png)

**Comment by crobibero** [comment]
What about inside of the Jellyfin container?

**Comment by JerreBor** [comment]
`sudo docker exec -it jellyfin_jellyfin_1 nvidia-smi` returns the same as before.

**Comment by cvium** [comment]
Seems related to https://forums.developer.nvidia.com/t/cannot-load-libnvidia-encode-so-1/117652
