### ISSUE TITLE
[10.7-RC2] Can't direct play 2.1 FLAC files on iOS when transcoding

### ISSUE THREAD

**Issue by TheNamelessWonderer** [jellyfin/jellyfin#5083]
**Describe the bug**

Due to https://github.com/jellyfin/jellyfin-web/issues/2249 a fix was implemented in https://github.com/jellyfin/jellyfin/pull/4860. However this fix has caused another issue. If the video is transcoding, it forces it to 2 channels even though it should be able to play 3 channels just fine.

**System (please complete the following information):**
 - OS: macOS
 - Virtualization: Native
 - Clients: Jellyfin iOS App (iPad Air 2 on 14.3)
 - Browser: Based on Safari
 - Jellyfin Version: 10.7-RC2
 - Playback: Transcode
 - Installed Plugins: Kodi Sync Queue, Playback Reporting. TV Maze, MusicBrainz, OMDb, AudioDB
 - Reverse Proxy: Nginx
 - Base URL: None
 - Networking:Host
 - Storage: NFS

**To Reproduce**

1. Enabled fMP4-HLS in the iOS settings and enable burn in subtitles to get the video to transcode.
2. Play a file with 2.1 FLAC audio
3. Open playback data and see that it is only 2 channels

**Expected behavior**

The audio should be 3 channel.

**Screenshots**

![image](https://user-images.githubusercontent.com/56267607/105581548-8350a280-5d87-11eb-96cd-ea939dd446e8.png)

**Additional Information**
I'm not sure if this only happens when transcoding or not. Seeing as the files are H264 High they are always transcoded when played back on my iPad.

**Comment by TheNamelessWonderer** [comment]
Just tested 10.7-RC3 and it is still an issue on this build.

**Comment by nyanmisaka** [comment]
Since the audio track is direct, the 2ch in Transcoding Info can be ignored. This should be a report error.

**Comment by TheNamelessWonderer** [comment]
Thank you should this one be left open then?

**Comment by TheNamelessWonderer** [comment]
Was this fixed?
