### ISSUE TITLE
[API] Handle versioning in the System/Info* endpoint properly

### ISSUE THREAD

**Issue by EraYaN** [jellyfin/jellyfin#509]
Right now #508 will change the API version back to emulate Emby.

This issue should track that, we need to properly address this.

Maybe with a `System/InfoEx` endpoint.

**Comment by Tolriq** [comment]
If you add another endpoint and yet want to be compatible, current end point in all cases will need to have a way to know that you are jellyfin, checking that new endpoint on Emby would not make sense. And if you stay fully compatible then consumer would only check the info see it's pure emby and don't try jellyfin.
So not really sure a new end point would bring anything.

**Comment by EraYaN** [comment]
I suppose the HTTP code 200 vs 404 would be enough of a check?

**Comment by Tolriq** [comment]
That's still an useless call using network, cpu and so battery :)

There's already an API to identify hosts and it's API, there's no point of adding a new endpoint to do the exact same thing.

The SystemInfo already contains everything to describe the system info except the fact that you are JellyFin. What would the other end point do anyway? Return a different version number?

**Comment by Tolriq** [comment]
Yes most keys are optional already and the API is designed to add new keys in fields.

No consumer should crash on unknown key or they are badly coded and can't support any change on the backend side ;)

I really suggest to add an optional isJellyFin:true as long as you are fully compatible with Emby.

**Comment by Tolriq** [comment]
Yep perfect and keep compat for others too.

**Comment by sevenrats** [comment]
@EraYaN what is the status of this issue?

**Comment by EraYaN** [comment]
ProductName is still present in the public Info response and the version is correctly identifies 10.x.x. So it's probably fixed? I can't really remember if this is enough of a fix, and it probably is.

**Comment by srcrist** [comment]
Closing issue as fixed by https://github.com/jellyfin/jellyfin/pull/508. If anyone still experiences any issues with this, please open a new issue with additional details.
