### ISSUE TITLE
Folder type recognition error!!

### ISSUE THREAD

**Issue by zelohon** [jellyfin/jellyfin#5094]
You want to add a custom selection mode for each folder, such as movies, music, TV series, pictures, etc

Because if you like the current automatic recognition sometimes may not be accurate!!!

Because I encountered a problem, a folder with different audio-visual folder will not be recognized!!

Mixed type can't be recognized normally!!

**Comment by cvium** [comment]
Please fill out the issue template and be sure to include screenshots, logs etc.
