### ISSUE TITLE
code duplication: DeepCopy and CopyProperties

### ISSUE THREAD

**Issue by Bond-009** [jellyfin/jellyfin#5096]
`CopyProperties` in Jellyfin.Api/Helpers/ClassMigrationHelper.cs
and
`DeepCopy` in MediaBrowser.Controller/Entities/BaseItemExtensions.cs
do basically the same thing.

**Comment by BaronGreenback** [comment]
My bad - think I'm responsible for the top one. It's used to migrate the network settings out of system.xml and into network.xml

**Comment by BaronGreenback** [comment]
Code is removed in https://github.com/jellyfin/jellyfin/pull/5482

**Comment by HavermansStef** [comment]
Issue is merged and can be closed. I just confirmed. `CopyProperties` has been removed.
