### ISSUE TITLE
[10.7.0RC3] Fix redirects from /web/index.html#!/video to /web/

### ISSUE THREAD

**Issue by ricardoandren** [jellyfin/jellyfin#5098]
Summary: Windows 10 Firefox AMD64, 

Opening jellyfin https://................/web/index.html#!/video by accident causes white screen and doesnt redirect to main, I think it should redirect to the main screen, because the autocorrecting urls are realy janky in the search bars and will sometimes autocorrect to https://................/web/index.html#!/video instead of https://................/ which produces some weird results like the white screen and sometimes a video playing in the background of the main screen.

![afbeelding](https://user-images.githubusercontent.com/17046242/105634995-13164f80-5e61-11eb-90e9-c7aa83ea8e7a.png)

**Comment by crobibero** [comment]
What version of Jellyfin are you running?

**Comment by ricardoandren** [comment]
10.7.0rc3

**Comment by ricardoandren** [comment]
nginx was the issue.
