### ISSUE TITLE
Add details/content to Wiki

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin#51]
We call out the Wiki in the readme, but there's nothing there yet.

I've added the default "welcome" page, with a note that more details are yet to come.

Need to quickly sketch out what will go in there, and start adding content.

I'm thinking:
- Project overview (same as readme)
- Quick Goals (point to code of conduct)
- Currently known/supported builds/packages list
- Install instructions for supported builds

**Comment by joshuaboniface** [comment]
Added a naming convention to ensure we all capitalize the name consistently:

https://github.com/jellyfin/jellyfin/wiki/Naming-Conventions-for-Jellyfin

**Comment by sparky8251** [comment]
We have our own docs repo now. This should either be closed or moved to it.
