### ISSUE TITLE
Unstable Chromecast always replays episode

### ISSUE THREAD

**Issue by krutburken** [jellyfin/jellyfin#5109]
**Describe the bug**
When you use the Unstable Chromecast client, it always replays the same episode regardless if Play next is chosen or not. Stable does not have this issue. Don't know if this has been reported already (found nothing obvious after searching)

**System (please complete the following information):**
 - OS: CentOS
 - Virtualization: Docker
 - Clients: Chromecast
 - Browser: Chrome 89
 - Jellyfin Version: 10.7.0-rc3
 - Reverse Proxy: nginx

**To Reproduce**
1. Choose Unstable Chromecast under playback
2. Connect to device and cast episode
3. Scrub to close to end of episode and wait until it finishes
4. The same episode replays from beginning

**Expected behavior**
Next episode should play

**Logs**
Can't see any error or other things that look obviously out of place

**Comment by hamburglar2160** [comment]
https://github.com/jellyfin/jellyfin-chromecast/pull/107
