### ISSUE TITLE
[Question] should I be able of watching a H.265 10Bit movie ?

### ISSUE THREAD

**Issue by Morgan-6Freedom** [jellyfin/jellyfin#5114]
**Server System (please complete the following information):**
 - OS: Docker on Linux
 - Jellyfin Version: [e.g. 10.0.1]
 - Hardware settings & device: Old laptop
 - Reverse proxy: no
 
**Client System (please complete the following information):**
 - Device: Windows 10 + chrome web app & Jellyfin android official app

I have uploaded a H.265 10bit movie in my library. However it is not listed in the library
![image](https://user-images.githubusercontent.com/49686866/106014912-3db11400-60be-11eb-8537-838c37411eea.png)

This documentation says that H265 10 bit is not working on android & chrome : https://jellyfin.org/docs/general/clients/codec-support.html

However, it also says that "If the media is incompatible for any reason, Jellyfin will use FFmpeg to convert the media to a format that the client can process". 

So I have two questions :

1. Is is compatible or not ? Will it be converted automatically ?
2. Even if it's not compatible, should I see it inside the folder in the library view ?

**Comment by nyanmisaka** [comment]
1. Desktop chrome is capable of decoding H264 10-bit videos but it doesn't support HEVC.
Edge on supported hardware with hevc plugin installed, mpv-shim, android client EXO/external player, Safari/iOS client with fMP4-HLS enabled do support HEVC playback. If the HEVC 10-bit file should be played in DirectPlay or Remux HEVC(direct) method. Transcoding will happen when the client doesn't support HEVC or 10bit.

2. Video with incompatible format or bit depth won't be hidden in your library.

**Comment by Morgan-6Freedom** [comment]
Thank you for this explanation.
So the fact that my movie is not listed is nothing about h256, hevc or 10bits.
So Why does the movie is not listed?

**Comment by nyanmisaka** [comment]
Check the permission of the folder and movie naming.
https://jellyfin.org/docs/general/server/media/movies.html

**Comment by WWWesten** [comment]
nyanmisaka, You wrote:
> 1. Edge on supported hardware with hevc plugin installed
but Microsoft removed HEVC support from Edge Chromium and HEVC plugin not found in Edge store.

**Comment by nyanmisaka** [comment]
@WWWesten 

Microsoft have pulled the free HEVC plugin from OEM no long ago.
Here are the links of free and non-free versions.

Free: https://www.free-codecs.com/hevc_video_extension_download.htm
Non-free: https://www.microsoft.com/store/productId/9NMZLZ57R3T7

**Comment by cvium** [comment]
> 
> 
> Check the permission of the folder and movie naming.
> [jellyfin.org/docs/general/server/media/movies.html](https://jellyfin.org/docs/general/server/media/movies.html)

@Morgan-6Freedom Can you please respond?

**Comment by Morgan-6Freedom** [comment]
@nyanmisaka @cvium 
My music folder and my movie folder have the same permissions. But jellyfin only finds my musics.
![image](https://user-images.githubusercontent.com/49686866/114271569-4c973980-9a12-11eb-9f1d-92080a5b5a93.png)

**Comment by cvium** [comment]
Can you take a screenshot of the libraries in the admin dashboard?

And when you when, do you see any errors in the log?

**Comment by Morgan-6Freedom** [comment]
@cvium this ?
![image](https://user-images.githubusercontent.com/49686866/114272207-8158c000-9a15-11eb-9d63-f0f4824db0ae.png)

**Comment by cvium** [comment]
Yes. Thanks. And apologies for my last sentence. Autocorrect...

Do you see any errors in the logs when you scan?

It might be a problem that your music library also contains the movie folder. I think you'll have better results if you put your music in a separate folder.

**Comment by Morgan-6Freedom** [comment]
this is the things I found in the log about "movie":

> [2021-04-10 09:15:34.069 +00:00] [INF] [37] Emby.Server.Implementations.Library.LibraryManager: Found duplicate path: "/media/movies"

> [2021-04-10 13:32:49.758 +00:00] [ERR] [36] Emby.Server.Implementations.HttpServer.HttpListenerHost: Could not find handler for "/movies.html"

> [2021-04-10 13:32:49.759 +00:00] [ERR] [36] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Unable to find the specified file". URL: "http://MYURL/movies.html?topParentId=25056ac45ddab19c8f70b2ea3add33cc"

> [2021-04-10 13:33:26.888 +00:00] [INF] [48] Emby.Server.Implementations.IO.LibraryMonitor: "A MOVIE NAME (1977)" ("/media/movies/MOVIE NAME (1977)") will be refreshed.

> [2021-04-10 13:33:26.888 +00:00] [INF] [48] Emby.Server.Implementations.IO.LibraryMonitor: "movies" ("/media/movies") will be refreshed.

**Comment by cvium** [comment]
> Library.LibraryManager: Found duplicate path: "/media/movies"

Your libraries have to be in separate folders.

**Comment by Morgan-6Freedom** [comment]
@cvium it's working great now. I can see my movies. This issue can be closed. Thank you.
