### ISSUE TITLE
Forced Direct Playback of Opus Audio Results to No Audio

### ISSUE THREAD

**Issue by Roddyboii** [jellyfin/jellyfin#5116]
**Media Info of the file**
Container: MKV
Video Codec: HEVC 10bit SDR
Audio Codec: Opus 2ch Japanese
Subtitles: ASS English

**Stats for Nerds Screenshots**
![20210127_235024](https://user-images.githubusercontent.com/78095397/106017429-67d4f700-60fb-11eb-822f-ecfd81ac97ce.png)

**Server System (please complete the following information):**
 - OS: Windows 10 64 bit
 - Jellyfin Version: 10.7.0-rc2, 10.7.0-rc3 (current)
 - Hardware settings & device: Ryzen 5 3400G, AMD AMF
 - Reverse proxy: Caddy (ipv6 link w/ duckdns), Ngrok free (for users that don't have ipv6 yet, my router is behind cgnat)
 - Other hardware notes: None
 
**Client System (please complete the following information):**
 - Device: Samsung Galaxy J3 Emerge (Sprint), Some Vivo phone my friend uses, Huawei Nova 5T
 - OS: Android 6, Android 10
 - Client: Jellyfin Android 2.2.3, Browser
 - Browser (if Web client): Fennec F-Droid 84.1.4, Via 4.1.2, Chrome Latest

This is my first time posting a bug report on github so sorry if I made any mistakes.

I'm currently using a Galaxy J3 Emerge as my temporary phone which uses Android 6 Marshmallow and whenever I would play any video with opus audio, Jellyfin attempts to directly play it without transcoding ~~but my android version doesn't support native opus playback.~~ My friend has also tested this on his Vivo phone with the same android version.

The video plays and subtitle works but I get no audio. Tested on both the android client and on different types of browsers.

Update: Tested on a Huawei Nova 5T (Android 10), Chrome browser and still no audio. So android version is not the issue here. Still confused as to why there's no audio.

**Comment by lemmi23** [comment]
I got the same issue here when trying to play a video with audio in Opus. Works fine on windows 10 PC but i get no sound on android device (tryed both phone and tablet with Android 9).
Even though they are able to decode opus (For exemple, downloading the video and playing it with VLC orMXplayer works but playing from Jellyfin server result in no audio).
