### ISSUE TITLE
Voice actors from multiple languages all displayed

### ISSUE THREAD

**Issue by NotErikUden** [jellyfin/jellyfin#5122]
Every voice character for a certain media library that I have is being displayed with all their international counterparts. Meaning if there is one character in a TV show, the crew and cast information within that show's section within Jellyfin will contain the actual voice actor behind that character multiple times for all the different languages. It is easier shown than explained:

![image](https://user-images.githubusercontent.com/52011431/106184510-eb492380-61a1-11eb-9c34-a89c9e7f4528.png)

Meaning for all the varieties of characters a show might have, the only one displayed will be the first one, sixteen times. This, of course, is not technically wrong behavior, since all of these people do voice the character displayed. Yet I have everything in Jellyfin set to English, except that metadata is always downloaded and displayed in German.  Up to this point, however, Jellyfin always displayed the original voice actor behind the character (all other media libraries also do not face this issue), which I also prefer. I do not know why this behavior is occuring seemingly at random, which is why I am asking here for help. I have a lot of plugins installed, making this, possibly, not a Jellyfin main bug, but I do not have any other place to go to, since I have not found any person on the internet having a similar problem. 

 - OS: Windows
 - Virtualization: none
 - Clients: all
 - Browser: all
 - Jellyfin Version: 10.6.4
 - Installed Plugins: Anime (9.0.0.0), AudioDB, Bookshelf, Cover Art Archive, MusicBrainz, OMDb, Open Subtitles, Playback Reporting, Reports, TheTVDB.
 - Reverse Proxy: none
 - Storage: HDD

**To Reproduce**
No clue
I think it may have something to do with the Anime plugin, since this only occurs with Anime and only after I installed the plugin, yet there is nothing to configure within that plugin that lets me choose what voice actors should be displayed. Also, the voice actors that are being displayed are completely random, some from Brazil, China, Denmark, etc. 

**Screenshots**
![image](https://user-images.githubusercontent.com/52011431/106186017-f4d38b00-61a3-11eb-9e9e-a9b293f7dc96.png)
![image](https://user-images.githubusercontent.com/52011431/106186074-07e65b00-61a4-11eb-888d-f2a4c4df3d67.png)

If you got any ideas, please post them here. Otherwise, this is an awfully specific bug that doesn't seem to occur to anyone but me and is most likely caused by plugins, so I recommend having this on the lowest possible priority.

**Comment by benpro** [comment]
```
pacman -Qi jellyfin-bin
Name            : jellyfin-bin
Version         : 10.7.7-2
Description     : The Free Software Media System
Architecture    : x86_64
URL             : https://jellyfin.org/
Licenses        : GPL2
Groups          : None
Provides        : jellyfin
Depends On      : jellyfin-web-bin=10.7.7  jellyfin-server-bin=10.7.7
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : jellyfin  jellyfin-git
Replaces        : None
Installed Size  : 0.00 B
Packager        : Unknown Packager
Build Date      : 2021年09月07日 18時53分39秒
Install Date    : 2021年09月07日 18時54分07秒
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : None
```

Same issue please reopen.

**Comment by HirschBerge** [comment]
Just have an option to filter out language's that aren't available.
