### ISSUE TITLE
Can't open the server

### ISSUE THREAD

**Issue by claudioortiz1** [jellyfin/jellyfin#5124]
**Describe the bug**
my jellyfin server just won't open, it was working at first, but not anymore, I have tried entering the localhost ip address: 8096, and dont work, i dont have any other app using the port

 - OS: [Windows]
 - Virtualization: i really dont know, sorry :p - 
 - Clients: Browser
 - Browser: Chrome 80
 - Jellyfin Version: 10.5.5
 - Playback: Direct Play
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: none
 - Networking: Host
 - Storage: local

**To Reproduce**

1. Go to 'jellyfin 10.5.5'
2. Click on 'jellyfin.exe'
3. See error

**Expected behavior**
the app runs perfectly and i can use my server :)

i cant find the logs :c

**Comment by M0ssTee** [comment]
What error message are you seeing when you run jellyfin.exe?

**Comment by cvium** [comment]
10.5.5? We don't really support that version anymore.
