### ISSUE TITLE
10.7.0 RC3: Disallowed playback for a certain user starts playback anyway 

### ISSUE THREAD

**Issue by WWWesten** [jellyfin/jellyfin#5126]
**Describe the bug**

All media playback are disallowed for a certain user's profile in the admin interface (Users > Username > Profile). When this user clicks on the play icon, pop-ups the window with message: "Playback of this content is currently restricted. Please contact your server administrator for more information." This is expected. But after click on the button "Got It" playback is started/

**System:**
 - OS: [Windows 10 64bit]
 - Virtualization: [none]
 - Clients: [Web-client, Android TV ]
 - Browser: [e.g. Edge Chromium 88.0.705.53, Chrome 88.0.4324.104]
 - Jellyfin Version: [10.7.0, RC3]
 - Playback: [Direct Play, Remux, Direct Stream, Transcode] 
 - Installed Plugins: [Fanart, AudioDB, Bookshelf, MusicBrainz, OMDb, TMDb Box Sets, TV Maze, TheTVDB.]
 - Reverse Proxy: [none]
 - Base URL: [none]
 - Networking: [NAT]
 - Storage: [local]

**To Reproduce**

**Expected behavior**

If media playback are disallowed for a certain user then playback must not started.

**Logs**

**Screenshots**

**Additional context**

**Comment by cvium** [comment]
I have a fix for the web UI, but fixing it in the server seems like a larger change.

**Comment by WWWesten** [comment]
Fixed.
