### ISSUE TITLE
Transcoding with ffmpeg fails with "Too many packets buffered for output stream 0:1"

### ISSUE THREAD

**Issue by Nocifer** [jellyfin/jellyfin#5133]
I've just made a feature request about this (https://features.jellyfin.org/posts/1030/ffmpeg-too-many-packets-buffered-for-output-stream-0-1) but since it's a problematic behavior that can be considered kind of a bug (even though it's not really Jellyfin's bug) I figured it might be better to instead post about it here.

I'm not trying to pester the dev team by spamming them about my issue, I'm just not sure if this should be filed as a feature or a bug, so I'm sorry if I'm breaking some kind of netiqeuette by double posting.
***********
**Describe the bug**

I recently got bit by this:

```
Stream mapping:
Stream #0:0 -> #0:0 (av1 (libdav1d) -> h264 (h264_nvenc))
Stream #0:1 -> #0:1 (opus (native) -> aac (native))
Press [q] to stop, [?] for help
Too many packets buffered for output stream 0:1.
[aac @ 0x563c103997c0] Qavg: 42378.297
[aac @ 0x563c103997c0] 2 frames left in the queue on closing
Conversion failed!
```

This is due to a known and apparently very prevalent (under the right conditions) ffmpeg bug as documented here:

https://trac.ffmpeg.org/ticket/6375

There is a way to fix this behavior, which is to add the argument 

`-max_muxing_queue_size XXXX`

to ffmpeg's transcoding command, where XXXX is a number up to 9999 (see the 5th to last comment in the linked bug report for more details).

Even better, as chance would have it, even though this bug was first reported years ago (I've found reports about it dating from the 2.x days), it has recently been officially fixed (see the last two comments in the linked bug report for details and a link to the commit that fixed it).

The problem I see here is threefold:
- This fix will probably not be backported and will only apply to the next ffmpeg release.
- The next ffmpeg release may yet be a long while to come.
- Most Linux distributions will take even longer to pull the next ffmpeg release in their repos and make it available to their end users.

So I propose/ask for one of the following:

- Either implement the ability for the user to customize ffmpeg's transcoding command arguments (this would futureproof against similar bugs, and would also not risk producing new issues by changing Jellyfin's tried and tested defaults).
- Or, since we're so far talking about a single bug that has a fix that can be applied relatively harmlessly ("relatively" because it's been mentioned that an actually broken input stream can make ffmpeg hang when the muxing queue is set to a large enough number), apply that fix by default. In other words, make it so that Jellyfin by default transcodes with e.g. "-max_muxing_queue_size 1024" added as an argument.

**System (please complete the following information):**
 - OS: Arch Linux
 - Jellyfin Version: 10.6.4 and presumably also 10.7+
 - Playback: Transcode

**To Reproduce**
1. Try to transcode a video file that contains "somewhat sparse video or audio frames" (taken from the previously linked bug report).
2. Fail.
3. Visit the previously linked bug report and read to your heart's content (it also contains video samples that exhibit this behavior).

**Comment by nyanmisaka** [comment]
https://github.com/jellyfin/jellyfin/pull/3975
We have had an option to increase that value in 10.7. And we default it to 2048 for months without seeing any issue again.
![2021-01-30 230208](https://user-images.githubusercontent.com/14953024/106359878-50db1280-6350-11eb-9130-fde780c980da.png)

**Comment by Nocifer** [comment]
Ah, so this issue is actually already fixed with 10.7? Great work, thanks!

**Comment by Nocifer** [comment]
Hmm, something seems wrong here. I just updated my Jellyfin server to 10.7 and everything works smoothly so far, but I still get this error when trying to play that same problematic file, and I still don't see a `-max_muxing_queue_size 2048` argument in 10.7. For comparison, here's the ffmpeg transcode command from 10.6.4:

`/usr/bin/ffmpeg -i file:"/home/nocifer/test.mkv" -map 0:0 -map 0:1 -codec:v:0 h264_nvenc -force_key_frames "expr:gte(t,n_forced*5)" -vf "scale=trunc(min(max(iw\,ih*dar)\,1280)/2)*2:trunc(ow/dar/2)*2,subtitles='/home/nocifer/test.mkv:si=0'" -copyts -avoid_negative_ts disabled -start_at_zero -pix_fmt yuv420p -preset default -b:v 3813938 -maxrate 3813938 -bufsize 7627876 -profile:v high -vsync -1 -map_metadata -1 -map_chapters -1 -threads 0 -codec:a:0 aac -ac 2 -ab 192000  -y "/var/lib/jellyfin/transcodes/5a9de29b29b7a75af1a077772b02b6c4.mkv"`

And here's the one from 10.7:

`/usr/bin/ffmpeg -i file:"/home/nocifer/test.mkv" -map 0:0 -map 0:1 -codec:v:0 h264_nvenc -mpegts_m2ts_mode 1 -force_key_frames "expr:gte(t,n_forced*5)" -vf "scale=trunc(min(max(iw\,ih*dar)\,min(1920\,1080*dar))/2)*2:trunc(min(max(iw/dar\,ih)\,min(1920/dar\,1080))/2)*2,subtitles='/home/nocifer/test.mkv:si=0'" -copyts -avoid_negative_ts disabled -start_at_zero -pix_fmt yuv420p -preset default -b:v 3813938 -maxrate 3813938 -bufsize 7627876 -profile:v:0 high -vsync -1 -map_metadata -1 -map_chapters -1 -threads 0 -codec:a:0 aac -ac 2 -ab 192000 -y "/var/lib/jellyfin/transcodes/7297f8b6312b24c6540ace989d74102c.mkv"`

I also tried to change the default 2048 to 9999 to see if maybe it's an issue of Jellyfin having kept the (non-existent) previous value because I upgraded from 10.6.4, but that was no good either.

I'm just grasping at straws here, but could the fact that this is an AV1-encoded file be relevant?

**Comment by crobibero** [comment]
Looking at the source for`-max_muxing_queue_size`, it looks like the argument is only for HLS streams

**Comment by Nocifer** [comment]
Hmm, so the actual problem is that I'm trying to stream this via a Chromecast, which (I presume) doesn't use HLS, and thus `-max_muxing_queue_size` isn't applicable? Well, bummer. I guess for now I'll just download a different version of the file I'm having issues with, and hope that the next time I happen to encounter this, ffmpeg will have pushed a new release with the new fix included, which will hopefully work for all use cases and not only for HLS.

Thank you for your help.

**Comment by Nocifer** [comment]
Just leaving this here as a postmortem FYI: I just compiled and tested the latest ffmpeg master (for some weird reason this simple solution did not occur to me at all when I first reported the issue, even though I knew and even mentioned that there was a fix included in the git master... *facepalm*) and at last my file plays and streams correctly. So FYI, with the next ffmpeg release (4.4 and up) this issue has really been properly fixed.
