### ISSUE TITLE
Add support for ".actors" folder

### ISSUE THREAD

**Issue by chang19901** [jellyfin/jellyfin#5134]
*jellyfin 10.7.0 RC3: Can you add recognition of actor's photos under ".actors", ".actors" folders are in the parent catalogue or under each movie folder, folders are hidden properties, spaces between actors' names are replaced by _, thank you

**Comment by cvium** [comment]
Please re-open on https://features.jellyfin.org

**Comment by jfranki** [comment]
Please vote this feature on [https://features.jellyfin.org/posts/770/local-actors-folder-support-for-thumbnails](url)
