### ISSUE TITLE
10.7.0 RC3: .ignore files getting ignored

### ISSUE THREAD

**Issue by tod31** [jellyfin/jellyfin#5135]
**Describe the bug**
Jellyfin scans folders which contain an ".ignore" file and adds their content to the library.

**System (please complete the following information):**
 - OS: Synology DSM
 - Virtualization: Docker
 - Clients: [Browser, Android, Fire Stick, etc.]
 - Browser: [e.g. Firefox 72, Chrome 80, Safari 13]
 - Jellyfin Version: 10.7.0 RC3
 - Playback: [Direct Play, Remux, Direct Stream, Transcode] 
 - Installed Plugins: AudioDB, MusicBrainz, OMDb, TMDb Box Set, The TVDB
 - Reverse Proxy: none
 - Base URL: none
 - Networking: [e.g. Host, Bridge/NAT]
 - Storage: local

**To Reproduce**
Upgraded from 10.7.0 RC2 to RC3 yesterday. Automatic library scan got triggered in the evening. Tomorrow morning I noticed several movies which are located in an .ignorred folder as newest addition to the library.

**Expected behavior**
Folders containing an .ignore file should be excluded from the library scan.

https://github.com/jellyfin/jellyfin/issues/1474
https://forum.jellyfin.org/t/how-to-exclude-a-folder-let-it-not-be-scanned/697
https://www.reddit.com/r/jellyfin/comments/ama9ss/is_it_possible_to_have_jelly_fin_not_add_certain/efqnvi4

**Logs**
no errors

**Screenshots**
![ignore_1](https://user-images.githubusercontent.com/11574078/106358900-4cdad080-630f-11eb-855f-f1169986d5e5.png)
![ignore_2](https://user-images.githubusercontent.com/11574078/106358901-4e0bfd80-630f-11eb-9342-b3f54279d072.png)

**Additional context**

**Comment by keniji** [comment]
I seem to have the same issue... After I have "upgraded" my docker incident from the stable (latest) version to the unstable version, media files which were ignored with the .ignore files, are now start to be added and be shown in the library...
As I can see now my Jellyfin is version 10.7.0, how can I see which RC it is?

**Comment by keniji** [comment]
I guess this issue could relate to the PR #4906 ? As the PR mentioned, the `IgnoreInaccessible` is set to `true`, and then the files have attributes **`FileAttributes.Hidden`** and `FileAttributes.System` will be skipped:
[EnumerationOptions.AttributesToSkip Property (System.IO) | Microsoft Docs](https://docs.microsoft.com/en-us/dotnet/api/system.io.enumerationoptions.attributestoskip?view=net-5.0)

And the `.ignore` files are just some hidden files, I guess then they're ignored? I'm not good at coding, so maybe someone have a look at it? Many thanks!

**Comment by nextlooper42** [comment]
Ehm...

.ignore is NOT working at all in 10.7.1. At least not in shows, i have Extras folder with ".ignore" (i want jellyfin to skip that) and its getting scanned no matter what. :D

**Comment by keniji** [comment]
> Ehm...
> 
> .ignore is NOT working at all in 10.7.1. At least not in shows, i have Extras folder in every Season folder with ".ignore" (i want jellyfin to skip that) and its getting scanned no matter what. :D

I've backed to the stable release, since the metadata page is kept loading (#5269) and do not know why it's still not fixed... But at least I can say this ".ignore" file issue does not exist in the stable release (10.7.0).

**Comment by DexLuther** [comment]
I'm on windows 10.8.0, and found this issue through Googling because I have it happen. Happened on the last stable release too (I forget what the version number was), but figured an update was around the corner and figured it wasn't that big a deal.

It seems intermittent. I have extra folders that it's correctly ignoring and I have other folders that it refuses to ignore.
