### ISSUE TITLE
Networksettings are ignored when configured in webinterface

### ISSUE THREAD

**Issue by morbificagent** [jellyfin/jellyfin#5136]
Hi together,

I was using jellyfin stable version before i builded the actual git version to try it out.
I didnt delete anything and builded and installed it over the 1.6 stable version.

Most is working...
But now changing my networksettings isnt possible anymore. If i change some settings via the webinterface they arent used after a service restart.

My log says it uses /etc/jellyfin/ as config dir (ubuntu 20.04).
But when i take a look at this dir there are two files with networksettings in it.
System.xml and network.xml

Could anyone explain which file is used? Do i need both? And has anyone an idea why the configuration via webinterface isnt working?

Many thanks

**Comment by BaronGreenback** [comment]
network.xml is the file that is used - all the network settings were moved across in this release.

The fields in system.xml is to enable a successful migration. Any network setting changes to system.xml will be ignored.

**Comment by morbificagent** [comment]
Hey Baron,

Thanks for the explanation.

But do you have an idea why the changes made in the webinterface arent reflected to the system?

And can i delete the network parts from the system.xml so they cant confuse me?

**Comment by BaronGreenback** [comment]
Have you got the latest web client?

You can delete the settings from system.xml but next time you change settings the blank placeholders will be created. Got to think of a better way of migrating the settings, and removing the properties whilst following the jf coding.

**Comment by cvium** [comment]
Cannot reproduce in 10.7.2
