### ISSUE TITLE
Jellyfin cant list every movie

### ISSUE THREAD

**Issue by stumpyofpain** [jellyfin/jellyfin#5140]
**Describe the bug**
i am planning to change from emby to jellyfin and installed jellyfin last weekend.
i added every library and scanned them.
on my client i can see, that i have 674 movies, in the plugin "reports" i can see all 1008 movies, which nearly matches with my 1014 movies on emby.

**System (please complete the following information):**

 - OS: Ubuntu 20.04
 - Virtualization: LXC on Proxmox
 - Clients:  Android Jelly
 - Browser: Firefox 85, Chrome  88.0.4324.104,
 - Jellyfin Version: 10.6.4
 - Playback: / 
 - Installed Plugins: anime, aduiodb, fanart, musicbrainz, omdb, open subtitles, playback reporting, reports, skin manager, tmdb box sets, thetvdb, theme songs, trakt
 - Reverse Proxy: nginx
 - Base URL: yes : /jellyfin
 - Networking: ?
 - Storage: zfs pool on proxmox, mounted in lxc, shared via smb

**To Reproduce**

1. add library movies
2. scan library
3. go to dashboard, select the movie library
4. See missing movies compared to emby or the report plugin

**Expected behavior**
That every movie i have is in my library.

**Logs**
?

**Comment by BaronGreenback** [comment]
Hasn't grouped films into collections - and only counting the collection as 1 item???

**Comment by stumpyofpain** [comment]
ah ty, that was my problem.
didnt see that option before.
turned it off and i got my 1k + movies.

can be closed :)
