### ISSUE TITLE
[Arch Linux ]Jellyfin crash (Error processing request: "A task was canceled".)

### ISSUE THREAD

**Issue by TechieAndroid** [jellyfin/jellyfin#5143]
**Describe the bug**

**System (please complete the following information):**
 - OS: [Arch Linux x64 Kernel v5.10.11-zen2-1-zen]
 - Clients: [Android 10 with Jellyfin v2.2.3 and a Chromecast 2nd gen model]
 - Jellyfin Version: [AUR packages of jellyfin, jellyfin-server, jellyfin-web all v10.6.4]
 - Playback: [Direct Play] 
 - Installed Plugins: [none]
 - Reverse Proxy: [none]
 - Base URL: [N/A]
 - Networking: [N/A]
 - Storage: [local]

**To Reproduce**
Playing content with certain codecs.

**Expected behavior**
I don't expect any errors/crashing.

**Logs**

[log_20210131.log](https://github.com/jellyfin/jellyfin/files/5901690/log_20210131.log)

**Comment by cvium** [comment]
Looks to me like one of your drives is disconnected and is causing havoc...

**Comment by TechieAndroid** [comment]
> Looks to me like one of your drives is disconnected and is causing havoc...

That wouldn't be it. All the drives are in good condition. And on top of that Plex works just fine.

**Comment by cvium** [comment]
I see a bunch of `"Input/output error"` though and you're missing a path `/media/austin/3TB-EXT4/HDD/Educational`.

Please upload the ffmpeg logs.

**Comment by TechieAndroid** [comment]
It's been almost 3 mouths. I don't think I have those logs anymore. It would've been nice to know that I needed to upload them back when I opened to issue.

**Comment by cvium** [comment]
We're looking into improving the issue template to make it more clear. Let us know if you encounter the issue again. Closing for now.
