### ISSUE TITLE
Fallback font is not applied to burn-in subtitles during transcoding 

### ISSUE THREAD

**Issue by acc557** [jellyfin/jellyfin#5145]
Related to https://github.com/jellyfin/jellyfin/pull/3683

Fallback font is not applied to burn-in subtitles during transcoding. All CJK characters are mapped and shown as hollow squares in the default font which contains no CJK characters.

**System (please complete the following information):**
 - OS: Ubuntu
 - Virtualization:  Docker
 - Clients: TV with DLNA support
 - Browser:  Firefox 72
 - Jellyfin Version:  4bcf684b7241af10c15459cf83cb93e536471c8c
 - Playback:  Transcode with burn-in subtitles 
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: none
 - Networking: Host
 - Storage: local

**Comment by nyanmisaka** [comment]
Fallback fonts is currently only available for `JavascriptSubtitlesOctopus` for the time being.
You don't have to burn-in with it, SSA/ASS subtitles can be rendered by your browser.

**Comment by acc557** [comment]
Thanks for the clarification, I got it working :)
