### ISSUE TITLE
Chapter-based skip intro/outro/credits feature

### ISSUE THREAD

**Issue by hawken93** [jellyfin/jellyfin#515]
Just going to leave this here so it won't be forgotten.

@dkanada (...) my suggestion was, jellyfin already has chapter support I think, lets you select chapters to skip to, lots of mkvs have "intro" and "credits" chapters or whatever, so we just add basic search for these chapters and add a skip button (...) if I remember this when the UI stuff is done I will look into the current chapter support, it must all be handled in the javascript

@hawken93 hmm.. I would probably add server side metadata to be able to tag chapters and have the server side detect them to have less client side issues, and then just send the client a special list of the chapters that are intro, outro, credits... that way it's easier to replicate it across clients consistently
also ability to correct them in metadata manager

**Comment by dkanada** [comment]
One thing to note is that Jellyfin already has a very basic credit skip feature, but I believe it simply adds a modal about a minute before the episode ends. This would be a much more useful solution.

I am still undecided on whether or not the metadata for this feature would be better handled with the existing chapter feature or a custom solution by Jellyfin. The intro and credits are already properly tagged in lots of shows and it makes sense to build on that, but it would mean less client support.
