### ISSUE TITLE
Media seeking not posible via DLNA

### ISSUE THREAD

**Issue by arabek** [jellyfin/jellyfin#5152]
While i can seek any non-recoded (as in streamed directly) content from UMS/PMS to my LG CX
i can't seem to reproduce that behavior on Jellyfin.

**System:**
 - OS: Linux
 - Virtualization: no
 - Clients: LG CX builtin galery DLNA client
 - Jellyfin Version: [e.g. 10.6.4]
 - Playback: Direct Stream &| Remux
 - Installed Plugins: none
 - Reverse Proxy: none
 - Networking: LAN
 - Storage: local

**Expected behavior**
Should be able to seek the stream/file via DLNA as in UMS/PMS

**Comment by RoroTiti** [comment]
I second this 👍

**Comment by twdkeule** [comment]
I think this worked before 10.7.0 or 10.7.1

**Comment by cvium** [comment]
Fixed in 10.7.2

**Comment by arabek** [comment]
Confirmed working. Thanks! <3

**Comment by qkhanhpro** [comment]
Hi. I face the same issue with my LG TV UM7400
I am starting Jellyfin directly from the source code, on the master branch. Can someone help point me to the commit that fixed this issue ?
Thanks a lot!
