### ISSUE TITLE
Poster and other images aren't fetched correctly

### ISSUE THREAD

**Issue by moritzleick** [jellyfin/jellyfin#5153]
**Describe the bug**
When I want to edit the images of a movie or show they aren't loaded from the providers

**System (please complete the following information):**
 - OS: DSM (Synology)
 - Virtualization: Docker
 - Clients: Browser, Android, iOS
 - Browser: Firefox 85.0
 - Jellyfin Version: 10.7.0 rc3
 - Installed Plugins: AudioDB, Cover Art Archive, Fanart, MusicBrainz, OMDb, Open Subtitles, TV Maze, TheTVDB
 - Reverse Proxy: nginx
 - Base URL: none
 - Networking: Bridge
 - Storage: local

**To Reproduce**
1. Select a movie or show
2. Click on the dots and select "Edit images"
3. Under Primary (or others) click on the search button

**Expected behavior**
I expect to see previews of the available pictures and be able to download them

**Logs**
[log.txt](https://github.com/jellyfin/jellyfin/files/5911460/log.txt)

**Screenshots**
![Unbenannt](https://user-images.githubusercontent.com/48221072/106607637-72f4b080-655b-11eb-92c4-e312966f5fd8.PNG)

**Comment by cvium** [comment]
> System.Net.Http.HttpRequestException: Resource temporarily unavailable (image.tmdb.org:80)

Your log indicates a problem with the tmdb api. It must have been having issues. Try again.

**Comment by moritzleick** [comment]
The problem is still there.
I've also had it a couple of days before opening the issue..
And for fanart it doesn't even know the service:

> System.Net.Http.HttpRequestException: Name or service not known (assets.fanart.tv:443)
