### ISSUE TITLE
API returns an empty array for music videos related to an artist or album

### ISSUE THREAD

**Issue by MrTimscampi** [jellyfin/jellyfin#5156]
**Describe the bug**

The API request for music videos on artists or album pages returns an empty array

**System (please complete the following information):**
 - OS: ArchLinux
 - Virtualization: KVM
 - Clients: Browser
 - Browser: Firefox 84
 - Jellyfin Version: unstable 20210202
 - Playback: n/a
 - Installed Plugins: n/a
 - Reverse Proxy: none
 - Base URL: none
 - Networking: Host
 - Storage: NFS

**To Reproduce**

1. Add a music library
2. Add a music video library
3. Edit the music videos to add an artist and album present in the music library (Or use an NFO)

**Expected behavior**

The "Music Videos" section on the artist and album page should be filled in with the relevant items. It is currently appearing, but is empty.

**Logs**

Request URL:
```
http://192.168.1.78:8096/Users/7c55f3cd317f4e46b4b31ed28157370e/Items?SortOrder=Ascending&IncludeItemTypes=MusicVideo&Recursive=true&Fields=AudioInfo,ParentId,PrimaryImageAspectRatio,BasicSyncInfo,AudioInfo,ParentId,PrimaryImageAspectRatio,BasicSyncInfo&Limit=10&StartIndex=0&CollapseBoxSetItems=false&AlbumArtistIds=288d339924c40ef5702ab532155a5a09&SortBy=SortName
```

The AlbumArtistIds is correct for both the music video and the albums.

**Screenshots**

![Screenshot_2021-02-02 Jellyfin(1)](https://user-images.githubusercontent.com/19396809/106716237-7c832480-65fe-11eb-9b27-3a53c8fdbaae.png)
![Screenshot_2021-02-02 Jellyfin](https://user-images.githubusercontent.com/19396809/106716239-7db45180-65fe-11eb-91c7-d324a85fa493.png)

**Additional context**

**Comment by Ullmie02** [comment]
For the artists page, sending the artist id as parameter `ArtistId` instead of `AlbumArtistId` works fine.
The header is most likely displayed because the artist BaseItem has the property `MusicVideoCount: 1`.

The endpoint which gets called by the album page does return the correct data but doesn't display it.

**Comment by Ullmie02** [comment]
```
http://localhost:8096/Users/b147c70085a245cca4958b895826b618/Items?SortBy=SortName&SortOrder=Ascending&IncludeItemTypes=MusicVideo&Recursive=true&Fields=PrimaryImageAspectRatio,BasicSyncInfo,CanDelete,MediaSourceCount&AlbumIds=d00a9c4307484bdcb6e91e2c9b267bcf
```
is the album request which returns data for me

**Comment by SenorSmartyPants** [comment]
Can confirm this doesn't work for me either in 10.7.1. Video with one Artist set, Artist data has MusicVideoCount: 1, "Music Video" header is display but no items.

Music video list is displayed correctly for the director linked to videos.
