### ISSUE TITLE
Metadata writing is not working

### ISSUE THREAD

**Issue by TKFRvisionOfficial** [jellyfin/jellyfin#5160]
**Describe the bug**
If I try to update the info like picture or the info text, so you rescan...it just sets a blank picture. 

**System (please complete the following information):**
 - OS: Ubuntu Server?!
 - Virtualization: Docker
 - Clients: Browser
 - Jellyfin Version: 10.7.0-rc3
 - Reverse Proxy:  nginx
 - Storage: samba

**To Reproduce**

1. Click on movie
2. refresh metadata
3. wait for load to finish 

**Expected behavior**
set a proper picture and media data

**Logs**
[2021-02-03 17:58:26.009 +00:00] [ERR] [46] MediaBrowser.Providers.Manager.ProviderManager: Error in metadata saver
System.UnauthorizedAccessException: Access to the path '/media/.movies/Friday the 13th (1980)/friday_the_13th_1980.nfo' is denied.

**Screenshots**
![nope](https://user-images.githubusercontent.com/52245132/106788785-b598b480-6651-11eb-971b-c305c8cd42ee.png)

**Additional context**
Altough it creates the picture and nfo files it cant write to them...permissions are there tho. Again it could have something to do with the samba but i am not sure. 

Sorry for my english...I have a headache.

**Comment by crobibero** [comment]
Should be fixed by https://github.com/jellyfin/jellyfin/pull/5106

**Comment by BachoSeven** [comment]
I still see this: 

```
    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
dic 23 18:43:21 server dotnet[56075]:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
dic 23 18:43:21 server dotnet[56075]:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
dic 23 18:43:21 server dotnet[56075]:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
dic 23 18:43:21 server dotnet[56075]:    at MediaBrowser.XbmcMetadata.Savers.BaseNfoSaver.SaveToFile(Stream stream, String path) in /home/main-builder/pkgwork/src/jellyfin-10.7.7/MediaBrowser.XbmcMetadata/Savers/BaseNfoSaver.cs:line 209
dic 23 18:43:21 server dotnet[56075]:    at MediaBrowser.XbmcMetadata.Savers.BaseNfoSaver.Save(BaseItem item, CancellationToken cancellationToken) in /home/main-builder/pkgwork/src/jellyfin-10.7.7/MediaBrowser.XbmcMetadata/Savers/BaseNfoSaver.cs:line 197
dic 23 18:43:21 server dotnet[56075]:    at MediaBrowser.Providers.Manager.ProviderManager.SaveMetadata(BaseItem item, ItemUpdateType updateType, IEnumerable`1 savers) in /home/main-builder/pkgwork/src/jellyfin-10.7.7/MediaBrowser.Providers/Manager/ProviderManager.cs:line 695
dic 23 18:43:22 server dotnet[56075]: [18:43:22] [ERR] [15] MediaBrowser.Providers.Manager.ProviderManager: Error in metadata saver
dic 23 18:43:22 server dotnet[56075]: System.UnauthorizedAccessException: Access to the path '/mnt/2tb/Serie/Game Changer (dropout.tv) [720p]/Promo.nfo' is denied.
dic 23 18:43:22 server dotnet[56075]:  ---> System.IO.IOException: Permission denied
dic 23 18:43:22 server dotnet[56075]:    --- End of inner exception stack trace ---
```

**Comment by crobibero** [comment]
Please open a new issue, and fill out the template.
