### ISSUE TITLE
Playback/Transcode issue

### ISSUE THREAD

**Issue by leozanelato** [jellyfin/jellyfin#5163]
**Media Info of the file**
The.Grand.Tour.S01E01.720p.WEBRiP.x265.ShAaNiG
Formatomkv
LocalD:\ARQUIVO\SERIES\The.Grand.Tour-2016\S01\The.Grand.Tour.S01E01.720p.WEBRiP.x265.ShAaNiG.mkv
Tamanho350 MB
Vídeo
Title720p HEVC SDR
CodecHEVC
PerfilMain
Nível93
Resolução1280x720
Proporção da tela16:9
EntrelaçadoNo
Taxa de quadros23.976025
Bitrate687 kbps
Intervalo do vídeoSDR
Formato de pixelyuv420p
Quadros de referência1
Áudio
TitleInglês - AAC - Stereo - Default
Idiomaeng
CodecAAC
PerfilHE-AAC
Interfacestereo
Canais2 ch
Bitrate192 kbps
Taxa da amostra48000 Hz
PadrãoYes

**Logs**
<Erro na Reprodução
Este cliente não é compatível com a media e o servidor não está enviando um formato de mídia compatível.>

**Server System:**
 - OS: Windows
 - Jellyfin Version: 10.7.0 rc3 installable
 - Hardware settings & device: NVENC on GTX970
 
[FFmpeg.Transcode-2021-02-04_15-37-38_182bd7deb275ed5107ca66b2c5c6d61f_9186cd67.log](https://github.com/jellyfin/jellyfin/files/5927972/FFmpeg.Transcode-2021-02-04_15-37-38_182bd7deb275ed5107ca66b2c5c6d61f_9186cd67.log)

**Comment by manjotsc** [comment]
You can search your gpu here https://developer.nvidia.com/video-encode-and-decode-gpu-support-matrix-new, GTX 970 doesn't not support NVENC Encoding.

**Comment by nyanmisaka** [comment]
```
[hevc_cuvid @ 00000193dfc7c780] Codec hevc_cuvid is not supported.
```

Try to Update your Nvidia driver.
**The minimum required driver version is: Linux: 418.30, Windows: 450.51.**

**Comment by leozanelato** [comment]
> ```
> [hevc_cuvid @ 00000193dfc7c780] Codec hevc_cuvid is not supported.
> ```
> 
> Try to Update your Nvidia driver.
> **The minimum required driver version is: Linux: 418.30, Windows: 450.51.**

I do have the lastest one, from last week i think, 460.09 or something like that

**Comment by leozanelato** [comment]
> ```
> [hevc_cuvid @ 00000193dfc7c780] Codec hevc_cuvid is not supported.
> ```
> 
> Try to Update your Nvidia driver.
> **The minimum required driver version is: Linux: 418.30, Windows: 450.51.**

Maybe is something with hevc and gtx970 they seem to not like each other. GTX 970 does support nvenc right? I dont know man

**Comment by nyanmisaka** [comment]
oops! I thought GTX 970 was able to decode HEVC video. Uncheck the HEVC checkbox in playback settings.
https://developer.nvidia.com/video-encode-and-decode-gpu-support-matrix-new

**Comment by leozanelato** [comment]
> oops! I thought GTX 970 was able to decode HEVC video. Uncheck the HEVC checkbox in playback settings.
> https://developer.nvidia.com/video-encode-and-decode-gpu-support-matrix-new

Oh Man, that worked wonderfully, thank you for your help and your time.
