### ISSUE TITLE
thumbnail images are broken for installed plugins

### ISSUE THREAD

**Issue by dkanada** [jellyfin/jellyfin#5167]
I tried multiple methods to get the image working for installed plugins but I'm pretty sure the relevant property will never get assigned a value. Here are my suggestions to get it working for the next update.

1. Change `PluginPath` to `PluginUrl` and simply cache the repository image locally when installing.
2. Pass the URL directly with the installed plugin object to avoid a useless `HasImage` property and custom endpoint for images.
3. Match the JSON property names for repository plugins exactly to reduce confusion, namely the camel casing.

This is only slightly related, but there doesn't seem to be any required directory structure for the plugin ZIP files themselves, is that correct? I seem to recall the manifest being a new requirement but didn't notice anything in the code.

cc @BaronGreenback

**Comment by dkanada** [comment]
I suppose if we were matching other media types, the image would get its own endpoint, but I still feel like plugins don't need to be that complicated to get working.

**Comment by BaronGreenback** [comment]
> I tried multiple methods to get the image working for installed plugins but I'm pretty sure the relevant property will never get assigned a value. Here are my suggestions to get it working for the next update.
> 
> 1. Change `PluginPath` to `PluginUrl` and simply cache the repository image locally when installing.
> 2. Pass the URL directly with the installed plugin object to avoid a useless `HasImage` property and custom endpoint for images.
> 3. Match the JSON property names for repository plugins exactly to reduce confusion, namely the camel casing.
> 
> This is only slightly related, but there doesn't seem to be any required directory structure for the plugin ZIP files themselves, is that correct? I seem to recall the manifest being a new requirement but didn't notice anything in the code.
> 
> cc @BaronGreenback

@dkanada - it was "designed" to work in relative isolation this way:

PluginPath should contain the path to image in the plugin folder. (The image would be part of the zip auto-installed)
The API [HttpGet("{pluginId}/{version}/Image")] does the necessary to return the image to the client.
The global system setting DisablePluginImages has to be set to **false**

NB: PluginPath was originally PluginUrl, but was renamed as it points to a local file. (Remote were discounted so that it would work offline)

**Comment by BaronGreenback** [comment]
> I suppose if we were matching other media types, the image would get its own endpoint, but I still feel like plugins don't need to be that complicated to get working.
> 
> Perhaps we should remove the name and description properties from the DLL files and simply copy the JSON directly from the repository on installation. It would provide more info and better offline support.

The plugin sub-system is complex . Having the properties in the dll, does cause issues - as they are only accessible post-creation. I think a local plugin db is the way to go.

**Comment by BaronGreenback** [comment]
Treat repository images separately. 

Like the DLL/properties thing, the plugin images aren't accessible as they are in the plugin zip - so a url is used.
Where there are multiple versions of a plugin over multiple repo's, it's first come first served for the selection of the url.
As the image is remote, no API is provided for this.

**Comment by dkanada** [comment]
After looking at the flag in the server configuration, we should definitely remove that soon. I'm also pretty sure there's still an issue with the plugin image. I think it's a property mismatch with the repository JSON, which still uses `ImageUrl` while the local manifest uses the `ImagePath` property. That field is never explicitly set within the code so it must get populated from something else, like the repository data.

Regardless, I think this should be solved without removing either property. The remote data would still include a URL and the local manifest would store a path to the local copy similar to the plugin's configuration file. I agree we should remove all metadata from the DLLs themselves, and in that case we should also leave the image outside the ZIP files. There are only three metadata fields populated from the local files (name, description, and now the thumbnail image) so removing the former two would still leave the image tied to a specific version. I can definitely say it's convenient to avoid version-specific metadata when possible and I think the image falls within that category.

I would suggest the plugin object (within the repository metadata) keeps its `ImageUrl` field, and a local copy is made on installation. This would keep the offline functionality and avoid versioning issues, which I absolutely hate.

**Comment by BaronGreenback** [comment]
The manifest image path is in MediaBrowser.Common.Plugins.Manifest.cs

```
       /// <summary>
        /// Gets or sets the ImagePath
        /// Gets or sets a value indicating whether this plugin has an image.
        /// Image must be located in the local plugin folder.
        /// </summary>
        [JsonPropertyName("imagePath")]
        public string? ImagePath { get; set; }
```

Its expecting **imagePath** in the manifest not imageUrl.

**Process**
At present the repository code system works with PackageInfo record. (MediaBrowser.Model.Updates.PackageInfo). Each package contains one or more VersionInfo records (MediaBrowser.Model.Updates.VersionInfo).  

The PackageInfo has the ImageUrl property, as these details are what are used in the web. (Package info + versions)
PackageInfo properties are on a first found basis, as they could be duplicated across repo's.

The install API is passed the packageId and the version number and then downloads the plugin zip file.

Went with the current method is it cuts out the complexities of downloading the associated image, then updating the local manifest.

**Comment by dkanada** [comment]
Where exactly is the `ImagePath` property expected though? I already tried in the repository JSON and didn't get it working.

**Comment by BaronGreenback** [comment]
It's in the manifest json in the plugin zip.
