### ISSUE TITLE
Emby Samsung TV App - Details do not load

### ISSUE THREAD

**Issue by davehope** [jellyfin/jellyfin#517]
When using the Emby Samsung TV app to connect to Jellyfin 10.0.0.0, a loading animation is displayed when trying to load media details. Pressing "Play" on the remote so as to bypass details screen is a workaround.

This occurs in the latest Emby app for Samsung Orsay (reported as Emby Thearer 0.112). Older versions of the app worked, despite reportinf the same version number. There has not been a release of the app since the fork, so I do not believe this is related to the Android issue.

The app also breaks with Emby Server 3.5.3.0, but is apparently addressed in a future server version:

https://emby.media/community/index.php?/topic/66805-samsung-app-playback-issue-ue55ku6000/#entry670984

Logging here as seems to he a server side fix.

**Comment by davehope** [comment]
Below are the jelyfin.log entries when the problem occurs:

> [2019-01-09 18:13:55.935 +00:00] [INF] "HTTP GET" "http://10.99.99.92:8096/emby/Users/556f811206634645a5fc2335b0d7ed68/Items/c6914e108432fef29b517dfb579bc1b2". UserAgent: "Mozilla/5.0 (SmartHub; SMART-TV; U; Linux/SmartTV+2014; Maple2012) AppleWebKit/537.42+ (KHTML, like Gecko) SmartTV Safari/537.42+"
> [2019-01-09 18:13:55.956 +00:00] [INF] HTTP Response 200 to "10.99.99.53". Time: "21""ms". "http://10.99.99.92:8096/emby/Users/556f811206634645a5fc2335b0d7ed68/Items/c6914e108432fef29b517dfb579bc1b2" ""
> [2019-01-09 18:13:56.098 +00:00] [INF] "HTTP GET" "http://10.99.99.92:8096/emby/Items/c6914e108432fef29b517dfb579bc1b2/ThemeMedia?UserId=556f811206634645a5fc2335b0d7ed68&InheritFromParent=true&EnableThemeSongs=true&EnableThemeVideos=false". UserAgent: "Mozilla/5.0 (SmartHub; SMART-TV; U; Linux/SmartTV+2014; Maple2012) AppleWebKit/537.42+ (KHTML, like Gecko) SmartTV Safari/537.42+"
> [2019-01-09 18:13:56.117 +00:00] [INF] HTTP Response 200 to "10.99.99.53". Time: "19""ms". "http://10.99.99.92:8096/emby/Items/c6914e108432fef29b517dfb579bc1b2/ThemeMedia?UserId=556f811206634645a5fc2335b0d7ed68&InheritFromParent=true&EnableThemeSongs=true&EnableThemeVideos=false" ""
> [2019-01-09 18:13:56.213 +00:00] [INF] "HTTP GET" "http://10.99.99.92:8096/emby/Items/c6de13bf38f9dddbdd2122245653bc27/Images/Backdrop/0?tag=da651b64eb36dcaee7a24346628adf77&maxWidth=1536&quality=60". UserAgent: "Mozilla/5.0 (SmartHub; SMART-TV; U; Linux/SmartTV+2014; Maple2012) AppleWebKit/537.42+ (KHTML, like Gecko) SmartTV Safari/537.42+"
> [2019-01-09 18:13:56.227 +00:00] [INF] HTTP Response 200 to "10.99.99.53". Time: "14""ms". "http://10.99.99.92:8096/emby/Items/c6de13bf38f9dddbdd2122245653bc27/Images/Backdrop/0?tag=da651b64eb36dcaee7a24346628adf77&maxWidth=1536&quality=60" ""
> [2019-01-09 18:13:56.372 +00:00] [INF] "HTTP GET" "http://10.99.99.92:8096/emby/Items/c6914e108432fef29b517dfb579bc1b2/Images/Primary?maxWidth=640&tag=f44a6a7b354a8a69493232b7efb9279e&quality=50". UserAgent: "Mozilla/5.0 (SmartHub; SMART-TV; U; Linux/SmartTV+2014; Maple2012) AppleWebKit/537.42+ (KHTML, like Gecko) SmartTV Safari/537.42+"
> [2019-01-09 18:13:56.377 +00:00] [INF] "HTTP GET" "http://10.99.99.92:8096/emby/Items/c6de13bf38f9dddbdd2122245653bc27/Images/Logo?tag=7abba92ce45c064393d5f4298d4a6ba1&quality=90". UserAgent: "Mozilla/5.0 (SmartHub; SMART-TV; U; Linux/SmartTV+2014; Maple2012) AppleWebKit/537.42+ (KHTML, like Gecko) SmartTV Safari/537.42+"
> [2019-01-09 18:13:56.445 +00:00] [INF] HTTP Response 200 to "10.99.99.53". Time: "73""ms". "http://10.99.99.92:8096/emby/Items/c6914e108432fef29b517dfb579bc1b2/Images/Primary?maxWidth=640&tag=f44a6a7b354a8a69493232b7efb9279e&quality=50" ""
> [2019-01-09 18:13:56.475 +00:00] [INF] HTTP Response 200 to "10.99.99.53". Time: "98""ms". "http://10.99.99.92:8096/emby/Items/c6de13bf38f9dddbdd2122245653bc27/Images/Logo?tag=7abba92ce45c064393d5f4298d4a6ba1&quality=90" ""
> ^C

On the screen at the time a logo, thumbnail, title, duration and short-description of the TV episode can be seen.

**Comment by 0ddb0d** [comment]
> cc @ChessDragon136

He was not involved with this version of the Samsung client, only the 1.x and 2.x Orsay clients. The rewritten version that davehope is talking about was never available on the Emby repo.

@davehope As an aside, are you able to extract this version from your TV or capture a copy of the zip from the Samsung App Store? I would like to try it on an older model as I'm currently stuck using a hacked up version of the 1.x client.
