### ISSUE TITLE
Image Meta Data for a movie is public, only needs direct URL, no auth needed

### ISSUE THREAD

**Issue by aleda145** [jellyfin/jellyfin#5177]
**Describe the bug**
The image meta data for a movie is public, all that is needed is its URL to see the image. 

**System (please complete the following information):**
 - OS: Debian
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Firefox 84.0.2
 - Jellyfin Version: latest tag on dockerhub
 - Playback: -
 - Installed Plugins: none
 - Reverse Proxy: traefik
 - Base URL: yes, /items
 - Networking: Host
 - Storage: local

**To Reproduce**

1. Go to a series/movie
2. Right click on the image metadata for the movie/tv
3. Click inspect element
4. See the background image: url() with a link in the inspector
5. Copy the link, open in a private window where you are not logged into jellyfin
6. Image loads

**Expected behavior**
That if a user is not authenticated it should not see the image meta data and would be redirected to the jellyfin login screen

This is true for both the metadata that jellyfin captures, as well as user added images, which could be cause for privacy concerns.

**Logs**
No error logs

**Screenshots**
none

**Additional context**
While I would expect that crawling the generated hash for the image is impossible, I did not expect this image to be public.

Also: Thank you so much for maintaining this project. It is great and I love it :heart:

**Comment by Yetangitu** [comment]
There are more public endpoints in the API, I just happened upon one when looking for the cause of #5195:

```
https://jellyfin.example.org/web/configurationpages?pageType=PluginConfiguration&EnableInMainMenu=false
```

...produces results which, while mostly harmless, increase the attack surface.

**Comment by cvium** [comment]
Known issue. We have an issue detailing known security-related issues: #5415
