### ISSUE TITLE
Option to disable .nfo creation for DVR recordings

### ISSUE THREAD

**Issue by osscombat** [jellyfin/jellyfin#5178]
Is it possible to completely disable the creation of .nfo metadata files for the DVR recodings?
I've disabled everything regarding metadata, including "Metadata savers: NFO" for the recordings library, but the .nfo files are still created with every recording.

**Comment by Ullmie02** [comment]
Yes, there is currently no option to disable .nfo metadata for DVR recordings

**Comment by osscombat** [comment]
Got it, thanks for clarification!

вс, 7 февр. 2021 г., 18:59 David Ullmer <notifications@github.com>:
