### ISSUE TITLE
[Naming Bug] Quality Versions

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [jellyfin/jellyfin#5191]
**Describe the bug**
According to (https://jellyfin.org/docs/general/server/media/movies.html) to distinguish between versions, each filename needs to have a space, hyphen, space, and then a label. Ex. (2 Fast 2 Furious (2003) - 1080P.mp4) This works perfectly, I see just the quality of each movie when the they are grouped together.

I noticed that you can't have anything else in the title after the movie name and before the quality info. Ex. (2 Fast 2 Furious (2003) [8bit] [AVC] [DTS-HD MA-5.1]-FraMeSToR - Remux-1080p.mkv) This does not work, I see the whole file names for both the movies when they are grouped together.

When naming it the first way (2 Fast 2 Furious (2003) - 1080P.mp4) you are taking out alot of information form the file name, just in case you need it in the future.

**System (please complete the following information):**
 - OS: Linux
 - Virtualization: N/A
 - Clients: Browser
 - Browser: Firefox
 - Jellyfin Version: 10.6.3
 - Playback: N/A
 - Installed Plugins: : N/A
 - Reverse Proxy: nginx
 - Base URL: : N/A
 - Networking: N/A
 - Storage:  N/A

**To Reproduce**

**Expected behavior**
Have it only show the quality info no mater what's before the quality tag.

**Screenshots**

**Additional context**

**Comment by Cookie-Monster-Coder** [comment]
Issue still remains.

**Comment by cvium** [comment]
As a workaround you could remove the last hyphen?
