### ISSUE TITLE
Voice Chat on Syncplay

### ISSUE THREAD

**Issue by itsmecom** [jellyfin/jellyfin#5192]
Hello,
First of All, A Great thanks to the Jellyfin team and its contributors. Jellyfin is being a great media server.

Voice Chat on syncplay could be the killer feature and it will make Jellyfin unique from its alternatives. 

Watching a movie with friends remotely and chatting about the movie scenes would be great experience. 
Please Jellyfin Team, Implement this voice chat feature.

Its really a pain to use third party chat services and switching between two tabs. this also destroys the fullscreen experience.

Please make it happen.
Thank you Jellyfin Team.

**Comment by crobibero** [comment]
https://features.jellyfin.org/posts/740/add-chat-to-syncplay

**Comment by itsmecom** [comment]
Yeah, i saw that post.
is this feature is in work?
when can i expect this feature?
