### ISSUE TITLE
Feature Request: View users access from Library Management

### ISSUE THREAD

**Issue by timonoj** [jellyfin/jellyfin#5201]
Hi! 

Currently the user library access control is handled from the user's management tab. And this is all well and good. But when you try to see which specific users can reach a specific library, it would be way more useful to have it from the library management section, too. 
In short:
Currently, you can view from users which libraries each one can access.
I'd like to ask for each library to view which users can access it.

Thanks!

**Comment by crobibero** [comment]
I think this would make for a good plugin.
Feature requests belong here: features.jellyfin.org, not as a github issue
