### ISSUE TITLE
Can not use hardware acceleration with Intel CPU or NVIDIA GPU

### ISSUE THREAD

**Issue by vflanker** [jellyfin/jellyfin#5203]
**Describe the bug**

Recently I want to enhance my jellyfin server by adding a NVIDIA GPU card. However I failed and I will show my details below. Before that I have some questions:
- Running a Jellyfin LXC container on **Proxmox VE** system, is there any possible to use hardware acceleration by add GPU card?(I test and failed)
- If not use a GPU card, I can use VAAPI on a Intel PC?(I test and failed)

**NVIDIA GPU**
- VM OS/LXC OS:Ubuntu18.04/Debian10
- Virtualization: KVM/LXC
- NVIDIA Driver: 440.100
- CUDA:10.02
- cuDNN:7.6.5
- `/dev/dri/card0/1`:yes
- `/dev/dri/renderD128`:yes

- **LXC**: The LXC has been deleted from my server, but I do exactly as this [post](https://nathanlabadie.com/proxmox-nvidia-and/),so you can reproduce by reading this.
- **VM**:  Also deleted, and I do as the [PVE official wiki](https://pve.proxmox.com/wiki/Pci_passthrough).

I have a DELL R720 server with a KVM system named **Proxmox VE** running on it. And I has 3 NVIDIA card: **GT1030**,**GTX1050** and **Tesla K80**. These Week I tried to use GT1030 as my decoding hardware but failed( no matter VM with PCIE passthrough or LXC with `lxc.mount.entry`). But the NVIDIA CUDA works fine and I can see the bandwidth test program PASS.
And Then I realized that I shoud choose decoder type to 'NVENC'. But I failed again. So if there is any clear tutorial for jellyfin to work with NVIDIA GPU? And if there is a range limited for GPU selection? I have check the official documentation but I could not have the conclusion so I'm here to ask you fellow for a official answer, thank you. I have work on it for several days but end with many many failure. Sometime will find my NVIDIA GPU card useless than a cheap Raspberry Pi 3 Board.

**Intel iGPU**
- OS: Ubuntu 18.04
- CPU: Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz
- Virtualization: None or Docker
- `'dev/dri/card0`:yes
- `dev/dri/renderD128`:yes

After failed on virtual machine or LXC, I turns to a real machine: my computer Getac V110 with Intel CPU I5. I try the real machine or docker but all failed. I have exec command `usermod -aG video jellyfin` so `jellyfin` has the privilege to access the hardware.

Here is the error output:
```
Input #0, asf, from 'file:/media/test.wmv':
  Metadata:
    WMFSDKNeeded    : 0.0.0.0000
    DeviceConformanceTemplate: AP@L3
    WM/WMADRCPeakReference: 32767
    WM/WMADRCPeakTarget: 32767
    WM/WMADRCAverageReference: 3628
    WM/WMADRCAverageTarget: 3628
    WMFSDKVersion   : 11.0.5721.5275
    IsVBR           : 0
    artist          : attackers
    copyright       : attackers
  Duration: 00:50:31.06, start: 0.000000, bitrate: 6012 kb/s
    Stream #0:0: Audio: wmapro (b[1][0][0] / 0x0162), 44100 Hz, stereo, fltp, 256 kb/s
    Stream #0:1: Video: vc1 (Advanced) (WVC1 / 0x31435657), yuv420p, 1920x1080, 5744 kb/s, 30 fps, 30 tbr, 1k tbn, 1k tbc
Stream mapping:
  Stream #0:1 -> #0:0 (vc1 (native) -> vp8 (libvpx))
  Stream #0:0 -> #0:1 (wmapro (native) -> vorbis (libvorbis))
Press [q] to stop, [?] for help
Impossible to convert between the formats supported by the filter 'graph 0 input from stream 0:1' and the filter 'auto_scaler_0'
Error reinitializing filters!
Failed to inject frame into filter network: Function not implemented
Error while processing the decoded data for stream #0:1
Conversion failed!
```

**Conclusion**
Anyway I am a big fan of jellyfin. But I relly want my jellyfin can work fine on my DELL R720 Server, which running a KVM managed by Proxmox VE and armed with NVIDIA GPU Cards(one of the GT1030, GTX1050, Tesla K80, for now I only test the GT1030)

Thanks for reading this issue.

**Comment by vflanker** [comment]
Adding for NVIDIA LXC Sence:
- decoder: NVENC
- nvidia-smi: OK
- video format: MP4
- decoder action: convert to 720P 5Mbps
- decoder result:
![image](https://user-images.githubusercontent.com/30745146/107511996-2f481980-6be1-11eb-96a5-029e3ae9bcd1.png)


**decoder log**

- cmd
```
/usr/lib/jellyfin-ffmpeg/ffmpeg -c:v h264_cuvid -resize 1280x720 -i file:"/home/test.mp4" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_nvenc -pix_fmt yuv420p -preset default -b:v 3807344 -maxrate 3807344 -bufsize 7614688 -profile:v high  -g 90 -keyint_min 90 -sc_threshold 0 -start_at_zero -vsync -1 -codec:a:0 libmp3lame -ac 2 -ab 192656  -copyts -avoid_negative_ts disabled -f hls -max_delay 5000000 -hls_time 3 -individual_header_trailer 0 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/var/lib/jellyfin/transcodes/09e0979ede41fcf7ca5179e91328302c%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/var/lib/jellyfin/transcodes/09e0979ede41fcf7ca5179e91328302c.m3u8"
```

- output
```
ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --disable-doc --disable-ffplay --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-gpl --enable-version3 --enable-static --enable-libfontconfig --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --arch=amd64 --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-vdpau --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvenc --enable-nvdec --enable-ffnvcodec
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'file:/home/test.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    artist          : PREMIUM
    encoder         : Lavf58.12.100
    copyright       : PREMIUM
  Duration: 02:27:20.05, start: 0.000000, bitrate: 5707 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 5504 kb/s, 29.97 fps, 29.97 tbr, 11988 tbn, 59.94 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 192 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (h264_cuvid) -> h264 (h264_nvenc))
  Stream #0:1 -> #0:1 (aac (native) -> mp3 (libmp3lame))
Press [q] to stop, [?] for help
[h264_nvenc @ 0x555637f87bc0] OpenEncodeSessionEx failed: unsupported device (2): (no details)
[h264_nvenc @ 0x555637f87bc0] No capable devices found
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
[libmp3lame @ 0x555637f8b140] 3 frames left in the queue on closing
Conversion failed!
```
So why is that?

**Comment by nyanmisaka** [comment]
GT 1030 doesn't support NVENC. Please disable hardware encoding option.
https://developer.nvidia.com/video-encode-and-decode-gpu-support-matrix-new

**Comment by ikomhoog** [comment]
In the docker setup, did you add the variables "-e 'NVIDIA_VISIBLE_DEVICES'='{INSERT YOUR GPU UID HERE}' -e 'NVIDIA_DRIVER_CAPABILITIES'='all'" and  "--runtime=nvidia"?

The GPU UID looks like: GPU-XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX

@nyanmisaka he/she said "I has 3 NVIDIA card: GT1030,GTX1050 and Tesla K80.", the GTX1050 supports NVENC

**Comment by vflanker** [comment]
Yes I've read this before. So the GTX1050 and Tesla K80 can do？Seems that K80 won't work. But now I found an much more easy way：use jellyfin-mpv-desktop，along with DLNA the player can use local resource to decode.

**Comment by vflanker** [comment]
unfortunately I don't add these to docker setup. In my case, docker run in an Intel Laptop without NVIDIA, and LXC and VM run in an Server with NVIDIA GPU.But thanks because you enlighten me very much. Now I know that NVIDIA Card must run under NVENC mode，and Cards should be in NVENC list but not  in NUDEC list only.So what about the Intel Vaapi mode？I can not make it in my Intel laptop no matter with docker or not.

**Comment by vflanker** [comment]
> In the docker setup, did you add the variables "-e 'NVIDIA_VISIBLE_DEVICES'='{INSERT YOUR GPU UID HERE}' -e 'NVIDIA_DRIVER_CAPABILITIES'='all'" and "--runtime=nvidia"?
> 
> The GPU UID looks like: GPU-XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
> 
> @nyanmisaka he/she said "I has 3 NVIDIA card: GT1030,GTX1050 and Tesla K80."
> the GTX1050 supports NVENC so that should be set to encode instead of the GT1030, he/she isn't all out of options

unfortunately I don't add these to docker setup. In my case, docker run in an Intel Laptop without NVIDIA, and LXC and VM run in an Server with NVIDIA GPU.But thanks because you enlighten me very much. Now I know that NVIDIA Card must run under NVENC mode，and Cards should be in NVENC list but not  in NUDEC list only.So what about the Intel Vaapi mode？I can not make it in my Intel laptop no matter with docker or not.

**Comment by vflanker** [comment]
> GT 1030 doesn't support NVENC. Please disable hardware encoding option.
> https://developer.nvidia.com/video-encode-and-decode-gpu-support-matrix-new

Yes I've read this before: https://developer.nvidia.com/video-encode-and-decode-gpu-support-matrix-new
 
So the GTX1050 and Tesla K80 can do？Seems that K80 won't work cause it does not show up in NVENC list. And now I'm clear that NVIDIA card can only work under NVENC Mode(also required the card support the features), thank you!

But now I found an much more easy way：use jellyfin-mpv-desktop，along with DLNA the player can use local resource to decode. It similarly solved the problem if we use jellyfin in LAN.

What do you think about it？
