### ISSUE TITLE
Require HTTPS not working

### ISSUE THREAD

**Issue by 9p6** [jellyfin/jellyfin#5205]
**Describe the bug**
After setting Require HTTPS option in Networking settings HTTP access is still allowed on 8096 port

**System (please complete the following information):**
 - OS: Ubuntu 20.04.2
 - Virtualization: none
 - Clients: Browser
 - Browser: Firefox 85.0.1
 - Jellyfin Version: 10.7.0~rc3
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: none
 - Networking: Host
 - Storage: local

**Comment by crobibero** [comment]
Did you restart after changing the setting?

**Comment by 9p6** [comment]
Ah yes I did I just thought it will stop listening on 8096 and haven't noticed it started redirecting to HTTPS port. Sorry for the noise.

**Comment by crobibero** [comment]
It’s hard to tell without a log attached, but I believe it may have still been listening to 8096 if you had DLNA enabled

**Comment by 9p6** [comment]
What happens is that it opens both ports one for HTTP (8096) the other for HTTPS (8920). The former redirects to the latter.
```
GET /web/index.html HTTP/1.1
Host: localhost:8096
User-Agent: curl/7.68.0
Accept: */*
 
HTTP/1.1 307 Temporary Redirect
Date: Wed, 10 Feb 2021 13:05:12 GMT
Server: Kestrel
Content-Length: 0
Location: https://localhost:8920/web/index.html
X-Response-Time-ms: 0
```
What I expected is to start listening on single port (8920) for both HTTP and HTTPS traffic with redirect to HTTPS. Because now connecting to 8920 for HTTP results in error.
