### ISSUE TITLE
Jellyfin server doesn't run

### ISSUE THREAD

**Issue by jmax-moh** [jellyfin/jellyfin#5206]
I have installed Jellyfin in the latest version and when I press **jellyfin tray app** nothing happens and no jellyfin icon appears in the toolbar, I have read all the suggestions and methods but the server doesn't run and I cann't find anything in **http://localhost:8096** and jellyfin isn't running in services.msc and in TEMP folder , in add I copied the web HTMLs to xampp path and the pages appeared...!! - please help me as soon as you can

 - OS: [Windows 7]
 - Clients: [Browser]
 - Browser: [Chrome 80]
 - Jellyfin Version: [10.6.4]
 - Installed Plugins: [none]
 - Reverse Proxy: [none]
 - Networking: [Host]
 - Storage: [local]

**Comment by zenodotus280** [comment]
I was having all sorts of problems similar to this. Try using 172.0.0.1 instead of localhost.
