### ISSUE TITLE
Every non admin user can control the entire server and even login as admin with his session token

### ISSUE THREAD

**Issue by Zaaaaac** [jellyfin/jellyfin#5210]
**Describe the bug**
Every non admin user can control the entire server and even login as admin with his session token.

**System (please complete the following information):**
 - OS: Ubuntu 20.04
 - Virtualization: All
 - Clients: All
 - Browser: All
 - Jellyfin Version: Tested on 10.6.4 & nightly 10.7.0-rc3
 - Playback: None
 - Installed Plugins: None
 - Reverse Proxy: None
 - Base URL: None
 - Networking: Default
 - Storage: Local

**To Reproduce**
1. Login as non admin user
2. Get your session token/api key
3. Use it to make any admin api call or even edit the user ID in local storage to login with it

**Expected behavior**
No admin access with users tokens

**Comment by crobibero** [comment]
I can't replicate this. How are you getting the session token / api key?
What endpoint are you hitting that is allowing access?

**Comment by Zaaaaac** [comment]
1. Get your token : 
![1](https://user-images.githubusercontent.com/32309259/107632883-695bfe80-6c67-11eb-99f1-694b86ef00d8.png)

2. Make an admin api call :
![2](https://user-images.githubusercontent.com/32309259/107632884-69f49500-6c67-11eb-89a8-972b303a6efa.png)

3. Login as admin :
![3](https://user-images.githubusercontent.com/32309259/107632886-69f49500-6c67-11eb-8db0-6a30e1f5ec6a.png)

**Comment by nielsvanvelzen** [comment]
I tried this and I did not get any admin privileges. The only thing that could be considered a bug is that jellyfin-web showed admin only components, the dashboard did not work though (could not save pages and only some showed data). 

Besides, from what I see in your screenshots the only thing you copied over is the user **id**, not the accesstoken.

**Comment by GermanCoding** [comment]
I think I understand what @Zaaaaac did, but there are a few errors in their procedure.

"Step 2: Make an admin api call" - you're calling the /Users endpoint, which is currently **not** an admin endpoint, but can be accessed from any authenticated user. I do not why, but that's how it currently is in code. So getting every user (and their id) on the server seems to be possible for every authenticated user at the moment.

"Step 3: Login as admin" - this shows the admin ui and the admin's user data, but actually trying to do anything privileged there caused 403 Forbidden errors on the API endpoints.

As soon as you know a user's id, you do really get some data. If you modify your local storage to use an admin's user id, the UI starts showing the admin dashboard and the admin user's data (continue watching, favorites etc), but you cannot perform any admin-only API calls there as your session is still not privileged.

You can still mess with the others user data - you can for example list or modify their favorites, recently watched, their progress on movies and series, see what they watched  and so on, but you do **not** gain admin access. You basically get access to other users data, without gaining their privileges.

It's a bit of a weakness of the Jellyfin API, that simply having a user's id + having some authentication token (from any other user) exposes much of the data of the other user. Most of the API simply takes the user id as a parameter, without checking if the current session is allowed to view data of that user.
