### ISSUE TITLE
Not loading season images (TMDB or TVDB)

### ISSUE THREAD

**Issue by jagiella** [jellyfin/jellyfin#5211]
For TV series it is not loading / showing the images for the different seasons which are provided by thetvdb.com or themoviedb.org
It's always using the image of the series instead.

I know, that there was an issue with TVDB in the past. So I have tested TVDB only, TMDB only, TMDB + TVDB as image source for season images. Always ends up choosing the series primary image for all seasons as image.

OS: arm64, armbian
Hardware: Odroid C2
Jellyfin: 10.6.4-1

**Comment by yxwangcs** [comment]
I believe this is fixed by https://github.com/jellyfin/jellyfin/commit/dc73d044de83110c28b33000cf0d5d8628f3d99e, which is (at least) included in the latest 10.7.0-rc3.

**Comment by jagiella** [comment]
Ah thanks! That's good to know!
Unfortunately, I have to wait for the official release of 10.7.0 as the unstable builds are currently not running on arm64 (at least not my setup).
