### ISSUE TITLE
Fallback support for ipv6 

### ISSUE THREAD

**Issue by prayag17** [jellyfin/jellyfin#5219]
**Describe the bug**
Hello, I recently added ipv6 support to network 'bridge' in docker cause I wanted to connect to my docker containers outside my house and ipv4 port forwarding was not an option and my ISP uses CGNAT on ipv4. I was disappointed to know that JF doesn't have fallback support for ipv6, though I love Jellyfin and have been using it for over 6 months now. Is it going to be added in jellyfin 10.7.0? BTW my processor is an armhf based cpu

Edit: Please tell me if there is a beta available with this functionality on docker. Thank you in advance

**Comment by BaronGreenback** [comment]
There are multiple IP6 sub-systems in JF. Which aspect are you talking about and how are you accessing it?

**Comment by BaronGreenback** [comment]
https://github.com/jellyfin/jellyfin/pull/5735 has been submitted that provides this functionality.
