### ISSUE TITLE
Unable to create playlist and scan for metadata didn't work

### ISSUE THREAD

**Issue by GraphiPerso** [jellyfin/jellyfin#5225]
**Describe the bug**
When I start to create a playlist it load indefinitely and never create one
When I search for metadata, nothing work... 

I was on 10.5 and this two features worked perfectly! I had another bug on it (playing some short movie stopped at the middle every time  but work perfectly on vlc) so I try 10.6.3 then 10.6.4 then now on the last unstable version from today! 

I'm on windows and i try chrome and firefox. Both up to date 
Plugins : anime (make an error at loading), audiodb, covert art archive, fanart (malfunctioning), music brains, omdb (even uncheck, it only makes some proposition on this thing... only work in english and I want title in my language), opensubtitle, thetvdb 
Didn't work on local host and also on other devices

**Comment by cvium** [comment]
Please upload server logs and browser console errors. I cannot reproduce this.
