### ISSUE TITLE
Fails to identity movies with filename using 'Movie TitleThe' formatting

### ISSUE THREAD

**Issue by thedwillis** [jellyfin/jellyfin#5227]
**Describe the bug**
In order to ensure I don't end up with hundreds of movies that's name starts with 'The' all grouped together, I use a 'Movie TitleThe' formatting for the folder name that is available in radarr, which provides a folder name like 'A-Team, The (2010)' (the filename within the folder is still 'The A-Team (2010).mkv'), sadly this causes Jellyfin to fail to auto identify the movie and I have to manually match all the movies using this format.

**System (please complete the following information):**

- OS: Docker
- Virtualization: None
- Clients: Web, Android TV
- Browser: Firefox 85 on Windows
- Jellyfin Version: 10.6.4

**Comment by jdrempel** [comment]
I'll second this. My format is "Dark Knight Rises, The (2012)".

- OS: Docker
- Virtualization: None
- Clients: Web, Amazon FireTV
- Browser: FF85 (Pop!_OS)
- Jellyfin Version: 10.6.4

**Comment by Funsponge** [comment]
I'm still having this issue, was this ever addressed?

**Comment by jozlod** [comment]
Has anyone found a fix or work around for this?
I really don't want to rename all my movie folders, and I also don't want to manually identify everything.

**Comment by JtMotoX** [comment]
Why was this issue closed without a solution?
