### ISSUE TITLE
[10.7.0 nightly] Dashboard and activity don't show any information

### ISSUE THREAD

**Issue by MrLemur** [jellyfin/jellyfin#5232]
**Describe the bug**
Loading the dashboard or activity page on either web or Android app doesn't actually show any information. This is with a clean install.

**System (please complete the following information):**
 - OS: Ubuntu 20.04
 - Virtualization: Docker
 - Clients: Browser 
 - Browser: Edge 90
 - Jellyfin Version: Linuxserver image 20210213.2-unstable
 - Playback: N/A
 - Installed Plugins: none
 - Reverse Proxy: Traefik
 - Base URL: None
 - Networking: Bridge
 - Storage: Local

**To Reproduce**
1.  Click on dashboard, activity and server information missing.
2. Click on Activity, nothing displayed

**Expected behavior**
Dashboard and activity show the expected information

**Logs**
When trying to load dashboard:
![image](https://user-images.githubusercontent.com/17055328/107856793-97397280-6e22-11eb-8c70-7e722cd37f63.png)

When trying to load activity:
![image](https://user-images.githubusercontent.com/17055328/107856804-a0c2da80-6e22-11eb-83c4-ce0d0d927f0f.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/17055328/107856767-58a3b800-6e22-11eb-8867-69c3115a0bec.png)
![image](https://user-images.githubusercontent.com/17055328/107856781-73762c80-6e22-11eb-93c3-c67aa18415a2.png)

**Comment by crobibero** [comment]
Closed in favor of issue in the web repo.
