### ISSUE TITLE
[Feature request] Extra subtitle sources

### ISSUE THREAD

**Issue by TheLonelinessOfHS** [jellyfin/jellyfin#5233]
Hello, first of all, I would like to thank you for your brilliant project. It is almost perfect for me. 

However, there is a little issue that, as a Chinese language user, the opensubtitles library is not quite satisfactory. In Emby, there are extra plugins like addic7ed and the subdb. I am wondering if you could officially provide plugins for them?

This plugin author https://github.com/n0tMaster have these plugins which used to work. However, in the recent versions they stopped working. I would be much appreciated if you could kindly provide extra subtitle sources. Thank you.

**Comment by cvium** [comment]
Please re-open on https://features.jellyfin.org
