### ISSUE TITLE
Native Linux Support

### ISSUE THREAD

**Issue by TechieAndroid** [jellyfin/jellyfin#5237]
Are there any plans to work on coding a Linux variant that doesn't depend on dotnet?

Is there currently a project open for that that is accepting contributors?

**Comment by crobibero** [comment]
If you want to run a linux variant that works without installing dotnet, you can always publish "self-contained", which bundles the dotnet framework into the output, though I'm not entirely sure why you would want to do that...

https://docs.microsoft.com/en-us/dotnet/core/deploying/#publish-self-contained

**Comment by oddstr13** [comment]
We actually do produce the self contained builds (separate installation of .NET is not needed).
The download size of the Jellyfin debs would be significantly smaller if we could rely on .NET framework being available on all platforms.

That being said, even tho we use the dotnet framework, that does not make it non-native.
We do not depend on emulation or translation layers such as WINE, just on the framework being installed (or, in our case, bundled) – This is no different than depending on GTK or Qt.

I am not aware of any other server projects that aim to implement the Jellyfin API at this time.
