### ISSUE TITLE
How can stream only audio from iptv to my upnp renderer

### ISSUE THREAD

**Issue by MX10-AC2N** [jellyfin/jellyfin#5246]
Hello,
I am using Jellyfin with yunohost. It works fine, however I'm having a problem.
I installed the IPTV extension in order to add links to WebRadio, it works very well, I have read access to the various radios that I have installed but when I try to send the sound to my upnp amp nothing happens ..
My amp is clearly visible by Jellyfin I can read my audio files there without any problem .. I therefore think that it is a problem at the transcoding level .. I should be able to stream only the sound (in wav would be the best or so mp3 or wma) coming from a radio link configured in iptv in Jellyfin, finally I think ?
Thank you...

**Comment by BaronGreenback** [comment]
can you enable dlna debugging in the web client, and enable debugging in the logging, then upload your log file please?

**Comment by MX10-AC2N** [comment]
[Log.txt](https://github.com/jellyfin/jellyfin/files/6096966/Log.txt)

**Comment by BaronGreenback** [comment]
If is being returned a transport is locked error from the AVR265 device. 

This usually means it's either busy, or something else is connected to it.

Also seen that the path used to connect to this device is over https.
Soap requests (the method of how the communications work) will work over https, however it may cause issues in the dlna as it isn't officially supported in version 1.1

**Comment by MX10-AC2N** [comment]
Thank @BaronGreenback,
I have no error return, my AVR265 device is available I can play on it my music very well, but I cannot send only the sound of my web-radio installed as iptv in jellyfin. .I have surely missed some things in the profiles of my upnp device ..? or in transcoding ??
link of web-radio example : https://stream.radiofrance.fr/fipreggae/fipreggae_hifi.m3u8?id=radiofrance

**Comment by BaronGreenback** [comment]
Does your device support m3u8 files?

If not, then i don't think this will work, due to the way dlna is designed.

The idea is that the url for the stream is passed to the device. In this case the url returns a file containing a list of streams, and not an individidual stream.

I assume you're playing the M3U8 file on JF, and are attempting to cast it?

**Comment by MX10-AC2N** [comment]
No indeed, my device only accepts mp3, and wma, however I manage to stream in lpcm (therefore in wav) via SWYH-RS (https://github.com/dheijl/swyh-rs)
The idea was to play the web-radio on jellyfin and send the audio stream to my amp .. but I don't know how to adjust the dlna parameters for transcoding .m3u8 to .lpcm ..?

**Comment by BaronGreenback** [comment]
You can't. m3u8 is basically a text file of links, and isn't a codec. If you open the file in a text editor, you'll see what i mean.

This would come under feature request - as we'd have to edit how the code works.

**Comment by MX10-AC2N** [comment]
OK, thank..

**Comment by MX10-AC2N** [comment]
swyh-rs works fine for this use, you can see..

**Comment by BaronGreenback** [comment]
Thanks - i'll take a look at their implementation - and see if i can impliment it into the unstable after 10.7 is released.

**Comment by MX10-AC2N** [comment]
I updated to 10.7 finally that to crash, I had to make a complete installation again .. 
Before I used the IPTV plugin available in the catalog of extensions, to add links to my favorites web-radios to broadcast them to my upnp / dlna amplifier ... Unfortunately since version 10.7 the plugin no longer works ..
Is there a way to add a web-radio option in Jellyfin ?   I have a few links with different shapes, all of them are perfectly readable with vlc, so I can imagine that ffmpeg must be able to read and convert this kind of link..
