### ISSUE TITLE
Build instructions for macOS are wrong, also won't build

### ISSUE THREAD

**Issue by DanielSmedegaardBuus** [jellyfin/jellyfin#5247]
**Describe the bug**
The linked-to wiki page on building from source lists that for Mac, we should `./build <platform> all`. This (`./build macos all`) results in `Unknown option macos`. The build script suggests something like `./build -t native -p macos`, but this gives, `Cross-building is not supported for native builds, use 'docker' builds on amd64 for cross-building.`

What gives?

**System (please complete the following information):**
 - OS: OS X
 - Virtualization: None
 - Jellyfin Version: Current git master @91ee1b1d02944c0cd1b935261ebab08973e68260

**To Reproduce**

1. Git clone repo
2. cd jellyfin
3. git submodule update --init
4. Commands described above

**Expected behavior**
Starts to build

**Logs**
Output as quoted above.

**Comment by nielsvanvelzen** [comment]
Try `dotnet restore && dotnet build` (with dotnet installed)

**Comment by DanielSmedegaardBuus** [comment]
Thanks Niels, I'll give it a try once qt is finished building (usually takes about two million years :D )

Seems this is just outdated documentation, then. I went back through the release tags, and at some version (forget which), the expected build arguments matched those from the wiki. Didn't see any mention of the `dotnet` dependency, though.

Cheers :)

**Comment by anthonylavado** [comment]
I should also add - if you want the .app, that requires much more work. There's a rough example in the CI of jellyfin-server-macos.
