### ISSUE TITLE
Live TV low def channels do not work properly with hardware transcoding enabled

### ISSUE THREAD

**Issue by Ulrar** [jellyfin/jellyfin#5248]
**Describe the bug**
Hi,

Live TV on standard definition channels does not work if hardware transcoding is enabled (intel >= 10th gen, using the iHD driver). HD channels seem to be working perfectly fine, and of course the local library also works well when transcoded.

If I disable hardware transcoding then all channels work fine.
Ireland is using the old DVB-T for broadcasting.

**System (please complete the following information):**
 - OS: Debian buster
 - Virtualization: Docker, linuxserver/jellyfin:nightly
 - Clients: Any
 - Browser: Any
 - Jellyfin Version: nightly build
 - Playback: Transcoded
 - Installed Plugins: None
 - Reverse Proxy: HAProxy
 - Base URL: /
 - Networking: Macvlan, so dedicated IP
 - Storage: N/A

**To Reproduce**
1. Move to the republic of Ireland :)
2. Get a newer intel cpu
2. Try to use LiveTV with hardware transcoding enabled

**Expected behavior**
Be able to watch any channels with hardware transcoding enabled.

**Logs**
Attaching the transcoding log : [transcode.log](https://github.com/jellyfin/jellyfin/files/5990779/transcode.log)

**Screenshots**
N/A

**Additional context**
Low def channels do load, but I get one very pixelated frame every few seconds, with the audio screeching from time to time. If I disable hardware transcoding they work fine, the picture isn't HD of course but it's not nearly as pixelated and of course it's fluid with audio.
Attaching a screenshot of the video when hardware transcoding is on.
![image](https://user-images.githubusercontent.com/873423/108105138-242f3680-7084-11eb-901c-47651d87b345.png)

The tuner is a HDHomeRun Quatro, and I get the same behaviour when using it directly from Jellyfin and when going through TVHeadend. Kodi connecting directly to TVHeadend can play anything fine, but the ratio is wrong by default, I have to adjust it by hand for the low def channels. Maybe the hardware transcoding gets confused by the ratio in the stream ?

Transcoding those channels take basically no resources, is there some way of disabling hardware transcoding for livetv only as a workaround ?

**Comment by Ulrar** [comment]
Hi

This is still an issue.

**Comment by Traace** [comment]
Same issue with current jellyfin stable...

**Comment by Ulrar** [comment]
Still an issue

**Comment by gnattu** [comment]
cc @nyanmisaka 

It seems like deinterlace is not working properly with vaapi, can you reproduce this with QSV?

**Comment by nyanmisaka** [comment]
@Ulrar Can you record the live tv to a video clip and play it in Jellyfin with VA-API HWA enabled? If this reproduces the issue, please provide the clip so I can reproduce it on my side as well.
```
/usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 3000000 -user_agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.85 Safari/537.36" -fflags +igndts -i "http://127.0.0.1:8096/LiveTv/LiveStreamFiles/6bc2431f64cf413fa7f24286e32df9b9/stream.ts" -c:v copy -c:a copy -sn -t 60 -y /path/to/60s_clip.ts
```

In the meantime you can try using QSV instead of VA-API. The former usually has better performance on Intel hardware.
