### ISSUE TITLE
Upgrade from 10.6.4 to 10.7.0-rc3 breaks Network bindings

### ISSUE THREAD

**Issue by nerxses** [jellyfin/jellyfin#5254]
**Describe the bug**
After my Upgrade from 10.6.4 to 10.7.0-rc3 Jellyfin is listening on all available interfaces. The web interface of jellyfin shows that it should bind to 127.0.0.1 and also the .xml configs (/var/lib/jellyfin/config/network.xml and /var/lib/jellyfin/config/system.xml). Both files contain the following:
```xml
  <EnableRemoteAccess>false</EnableRemoteAccess>
  <LocalNetworkSubnets />
  <LocalNetworkAddresses>
    <string>127.0.0.1</string>
  </LocalNetworkAddresses>
```
But the startup log shows:
```
Feb 17 10:50:31 archlinux jellyfin[57041]: [10:50:31] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : [127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
Feb 17 10:50:31 archlinux jellyfin[57041]: [10:50:31] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : []
Feb 17 10:50:31 archlinux jellyfin[57041]: [10:50:31] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: [127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
Feb 17 10:50:31 archlinux jellyfin[57041]: [10:50:31] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: []
Feb 17 10:50:31 archlinux jellyfin[57041]: [10:50:31] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind exclusions: []
Feb 17 10:50:31 archlinux jellyfin[57041]: [10:50:31] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
Feb 17 10:50:33 archlinux jellyfin[57041]: [10:50:33] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: OMDb 10.7.0.0
Feb 17 10:50:33 archlinux jellyfin[57041]: [10:50:33] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: MusicBrainz 10.7.0.0
Feb 17 10:50:33 archlinux jellyfin[57041]: [10:50:33] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: AudioDB 10.7.0.0
```

**System:**
 - OS: Arch with Kernel 5.10.16-arch1-1
 - Virtualization: Arch is running as VM on an ESXi (6.7.U3)
 - Jellyfin Version: 10.7.0-rc3
 - Installed Plugins: none
 - Reverse Proxy: nginx
 - Base URL: none
 - Networking: Host
 - Storage: local

**To Reproduce**
1. install 1.7.0-rc3 server set Bind-Address in settings via web or via configs to 127.0.0.1
2. restart server
3. startup log should look the same listen on all interfaces (settings gets ignored)

**Expected behavior**
Setting "Bind to local network address:" (Admin->Dashboard->Networking) should work as advertised

**Comment by BaronGreenback** [comment]
FYI: /var/lib/jellyfin/config/system.xml is superseded and no longer used if /var/lib/jellyfin/config/network.xml is present.

The code works on my system, so that reduces it down to a possible issue in the virtual interface detection method.

Could you let me know what interfaces you have, **and the names of them** please - I suspect that is where the problem lies.

Also, could attempt to set IgnoreVirtualInterfaces to false in the config? 

If the issue is in the virtual interface detection code, this **should** negate the issue, or at least change what's happening.

**Comment by BaronGreenback** [comment]
https://github.com/jellyfin/jellyfin/pull/5274
