### ISSUE TITLE
Read WebVTT subtitles info (language, notes, kind) from file for subtitle selection

### ISSUE THREAD

**Issue by Salamandar** [jellyfin/jellyfin#5256]
WebVTT files are supported, and they can include language information.

For now, the only information shown in the subtitle selection menu is a 3-letters language derived from the filename.

If specified in the file header, the language (and/or kind) should be shown there instead.

That's part-feature part-bug report ;)

**Comment by cvium** [comment]
We do not accept feature requests on github. Please use https://features.jellyfin.org/.

You also ignored the issue template. It's neither a sufficiently detailed bug report nor feature request.
