### ISSUE TITLE
Audio streams with a long "delay relative to video" value are silent

### ISSUE THREAD

**Issue by CutterXYZ** [jellyfin/jellyfin#5257]
I have a problem with a video where the audio stream in french is silent while the other language plays fine. Both streams have the same format, bitrate, sample rate and channel configuration. **The only difference is that the french audio stream has a Delay relative to video of 9 seconds.** The video is played in a web browser. The audio streams are transcoded from EAC to AAC (both logs are linked below). This is probably not a transcoding issue, because I can hear the audio in the transcoded .ts files when I open them in an audio player.

**Media Info of the file**
General
Unique ID                                : 8690252385426319950154507233088031501 (0x689AE85D0595A7115AADED3EFE8CB0D)
Complete name                            : D:\Downloads\BitTorrent\Séries\The Boys\The.Boys.2019.S01.MULTi.1080p.10bit.WEBRip.x265-NSP\The.Boys.2019.S01E01.MULTi.1080p.10bit.WEBRip.x265-NSP.mkv
Format                                   : Matroska
Format version                           : Version 4
File size                                : 1.04 GiB
Duration                                 : 1 h 0 min
Overall bit rate                         : 2 481 kb/s
Encoded date                             : UTC 2019-07-28 10:36:59
Writing application                      : mkvmerge v29.0.0 ('Like It Or Not') 64-bit
Writing library                          : libebml v1.3.6 + libmatroska v1.4.9

Video
ID                                       : 1
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L4@Main
Codec ID                                 : V_MPEGH/ISO/HEVC
Duration                                 : 1 h 0 min
Bit rate                                 : 1 197 kb/s
Width                                    : 1 920 pixels
Height                                   : 816 pixels
Display aspect ratio                     : 2.35:1
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 10 bits
Bits/(Pixel*Frame)                       : 0.032
Stream size                              : 515 MiB (48%)
Language                                 : English
Default                                  : Yes
Forced                                   : No

Audio #1
ID                                       : 2
Format                                   : E-AC-3
Format/Info                              : Enhanced AC-3
Commercial name                          : Dolby Digital Plus
Codec ID                                 : A_EAC3
Duration                                 : 1 h 0 min
Bit rate mode                            : Constant
Bit rate                                 : 640 kb/s
Channel(s)                               : 6 channels
Channel layout                           : L R C LFE Ls Rs
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Stream size                              : 275 MiB (26%)
Language                                 : English
Service kind                             : Complete Main
Default                                  : Yes
Forced                                   : No

Audio #2
ID                                       : 3
Format                                   : E-AC-3
Format/Info                              : Enhanced AC-3
Commercial name                          : Dolby Digital Plus
Codec ID                                 : A_EAC3
Duration                                 : 59 min 59 s
Bit rate mode                            : Constant
Bit rate                                 : 640 kb/s
Channel(s)                               : 6 channels
Channel layout                           : L R C LFE Ls Rs
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Delay relative to video                  : 9 s 984 ms
Stream size                              : 275 MiB (26%)
Language                                 : French
Service kind                             : Complete Main
Default                                  : No
Forced                                   : No

[...]

Menu
00:00:00.000                             : en:Amazon Original
00:00:05.000                             : en:Ratings
00:00:15.000                             : en:Studio Logo
00:00:27.000                             : en:Superheroes to the rescue
00:02:35.000                             : en:A love cut short
00:06:39.000                             : en:Meet Starlight
00:09:07.000                             : en:Saying goodbye to Robin
00:11:56.000                             : en:An important phone call
00:13:07.000                             : en:Hughie wants to make things right
00:14:59.000                             : en:A great time to be a superhero
00:19:11.000                             : en:A-Train seems to be everywhere
00:20:06.000                             : en:How bad do you want to be in the seven?
00:24:25.000                             : en:Billy makes Hughie an offer
00:28:58.000                             : en:Supes let loose
00:31:18.000                             : en:Never let them see you cry
00:32:19.000                             : en:Someone's trying to hide something
00:34:53.000                             : en:Negotiations for a new hero
00:36:56.000                             : en:Figure out who you are
00:41:26.000                             : en:Hughie accepts the offer
00:42:42.000                             : en:The first meeting of the new Seven
00:44:19.000                             : en:Hughie does his part
00:51:19.000                             : en:Madelyn caves on the deal
00:52:03.000                             : en:An unexpected visitor
00:57:03.000                             : en:Some bumpy turbulence
00:58:10.000                             : en:End Credits

**Logs**
[Jellyfin log](https://pastebin.com/yvq2DCKK)

**FFmpeg Logs**
[Transcode log for silent audio stream](https://pastebin.com/bRu5XSqz)
[Transcode log for good audio stream](https://pastebin.com/Wu0nqMda)

**Server System (please complete the following information):**
 - OS: Windows 10
 - Jellyfin Version: 10.7.0~RC3
 - Hardware settings & device: software encoding on x64 Intel CPU
 - Reverse proxy: caddy
 - Other hardware notes: N/A
 
**Client System (please complete the following information):**
 - Device: desktop computer (server)
 - OS: Windows 10
 - Client: web browser
 - Browser (if Web client): Firefox
 - Client and Browser Version: 86.0

**Comment by CutterXYZ** [comment]
Replaced playback statistics with MediaInfo tool output.

**Comment by CutterXYZ** [comment]
The problem is the duration of the "Delay relative to video" attribute of the audio stream. I've tried different values for it: if the audio stream is set to start 7 seconds or more after the video, it is silent.

This is all in the web player, the Android app doesn't have this problem.

**Comment by zedocrob** [comment]
I've noticed the same problem here, to bad because i've remuxed a bunch of videos with audio delays.

**Comment by CutterXYZ** [comment]
The problem persists with Jellyfin web 10.7.6.
