### ISSUE TITLE
The Photos Need documentation + fetaure request

### ISSUE THREAD

**Issue by spirillen** [jellyfin/jellyfin#5259]
I have now been using jellyfin for a couple of month and overall satisfied, but... I do find a few hick ups here and there.

This issue would stick to the Photo module.

As I like to collect some screenshots from tv-shows and movies I'm feeling I'm missing the ability to actually link these together also And this is my biggest annoyance tagging people, it's not working at all.

![image](https://user-images.githubusercontent.com/44526987/106357012-d4224700-6303-11eb-876d-45ea99ce1c53.png)

I have several times tried to add actor x, actor z, actor y and then locked the field people

![image](https://user-images.githubusercontent.com/44526987/106357041-f87e2380-6303-11eb-93f7-f0986cf199a3.png)

But every single time I have hit the save button, well nothing is stored at all, like nothing

There is also lacking information, or I haven't found them at all, to how it might be possible to add a `*.nfo` file inside the folder, what should it be named, and what tags would be supported.

To my believe the photo module should be supporting linking to all other contents:
  1. Movies
  2. Music
  3. Tv-shows
  4. Books
  5. Music Videos
  6. People / artist

![image](https://user-images.githubusercontent.com/44526987/106357095-46932700-6304-11eb-8f66-9ef882b4de91.png)

**Comment by Nichgon** [comment]
This happened to me as well. I haved check to save .nfo but nothing is saved to the folder instead it saved to jellyfin database.

**Comment by spirillen** [comment]
[@ping](https://mypdns.org/ping)

**Comment by spirillen** [comment]
> This looks more like a bug than a documentation issue, I'm moving it to the server so we can fix the behavior.

Any update on this??
