### ISSUE TITLE
Parse poster/thumb/fanart in NFO files for Movies and TV Shows

### ISSUE THREAD

**Issue by SenorSmartyPants** [jellyfin/jellyfin#5262]
**Describe the bug**
Parse artwork information provided in kodi style NFO files. Currently only actor thumbs are parsed.

**System (please complete the following information):**
 - OS: Armbian
 - Virtualization: Docker
 - Clients: Browser, Android
 - Browser: Chrome 88
 - Jellyfin Version: nightly

**Expected behavior**

Artwork specified should be read from NFO and given highest priority (or local image files should)

**Additional context**

TV Shows seem to have the most varied options for artwork in NFOs
https://kodi.wiki/view/NFO_files/TV_shows

**Comment by SenorSmartyPants** [comment]
Pinging @Ullmie02 . You have made the most recent changes to NFOParser classes.

**Comment by Ullmie02** [comment]
If you are talking about the `thumb` tab, then yes, I don't think this is implemented at the moment.
But I was planning to implement it in the future.

**Comment by SenorSmartyPants** [comment]
Yes, the `thumb` tag and the `fanart` tag
