### ISSUE TITLE
Extra features treated as episodes

### ISSUE THREAD

**Issue by ieure** [jellyfin/jellyfin#5264]
**Describe the bug**

I ripped my Seinfeld DVD set and put it on my Jellyfin server.  I have things organized like:

```
Seinfeld/
Seinfeld/Seinfeld.S05E01.The.Mango.mkv
Seinfeld/extras/Seinfeld.S05E01.The.Mango.Deleted.Scene.mkv
Seinfeld/extras/Seinfeld.S05E01.The.Mango.Inside.Look.mkv
Seinfeld/extras/Seinfeld.S05.Bloopers.mkv
```

The blooper reel correctly ends up in Specials, but Jellyfin thinks the deleted scene and inside look are episodes, even though they're inside the `extras/` folder.  It shows three copies of S05E01 in the episode list for the show.

**System (please complete the following information):**
 - OS: Debian 10 Buster
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Firefox
 - Jellyfin Version: 10.6.4
 - Playback: n/a
 - Installed Plugins: None
 - Reverse Proxy: none
 - Base URL: none
 - Networking: Host
 - Storage: Local

**To Reproduce**

1. Put media in an organization like the one I describe.
2. Scan the library.
3. Go to Seinfeld season 5.
4. Observe that there are three copies of S05E01, two of which are incorrectly labeled special features.

**Expected behavior**

Anything in an `extras/` folder should be treated as an extra, not an episode.

I suppose I could work around this by naming the special features `Seinfeld.S05-01.The.Mango.Inside.Look.mkv` or something like that, but I'd rather keep the naming scheme & I think this is a legit bug regardless.

**Logs**
n/a

**Screenshots**

**Additional context**

**Comment by kkanungo17** [comment]
Can confirm the bug on 10.6.4 and 10.7-RC3. Quite annoying because it clutters up the episode list even if there's a special features section for it.

**Comment by crobibero** [comment]
From what I can remember specials should go either in `Season 0` or a `Specials` folder, but I could be wrong

**Comment by kkanungo17** [comment]
Specials are different from Special Features.
