### ISSUE TITLE
Wait-IO on server is very high when doing anything on  jellyfin

### ISSUE THREAD

**Issue by YodaQ** [jellyfin/jellyfin#5267]
If jellyfin is not doing anything the cpu usage and wait-io is normal but as soon as i start doing anything like updating a plugin or scanning the library wait io spikes very high. In the case of scanning a library since it take over 24 hours it means that my servers wait-io is constantly high slowing everything down and sometimes making jellyfin unusable.

**Comment by Emil-G** [comment]
That seems normal.. If you have slow disks/or a lot of content, of course the CPU needs to wait for disk operations.
