### ISSUE TITLE
/System/Logs/Log should send UTF-8 in Content-Type header

### ISSUE THREAD

**Issue by Nothing4You** [jellyfin/jellyfin#5272]
**Describe the bug**
Viewing logs in a browser results in broken umlauts/special characters.

**System (please complete the following information):**
 - OS: Linux
 - Virtualization: –
 - Clients: Browser
 - Browser: Firefox 85
 - Jellyfin Version: 10.6.4
 - Playback: –
 - Installed Plugins: –
 - Reverse Proxy: nginx
 - Base URL: /
 - Networking: –
 - Storage: –

**To Reproduce**
1. Do an action that puts umlauts in the log file. In my case a German episode containing ü in the episode title.
2. OpenSubtitles plugin downloads a subtitle, puts a line like `[INF] Saving subtitles to "/var/lib/jellyfin/metadata/library/xx/xxxx/Series - S01E01 - äöü.eng.srt"` in the logs
3. Opening the log file with e.g. vim confirms that the file is UTF-8 encoded and the characters look correct
4. Open the log viewer in a browser and you get broken umlauts

**Expected behavior**
Umlauts are displayed correctly.

**Logs**
Firefox console:
```
The character encoding of the plain text document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the file needs to be declared in the transfer protocol or file needs to use a byte order mark as an encoding signature.
```

**Screenshots**

**Additional context**
Currently the server sends the following HTTP header: `content-type: text/plain`
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type) `Content-Type: text/html; charset=UTF-8` should be a working alternative that would resolve this issue.

**Comment by Bond-009** [comment]
Should be fixed in 10.7 #4564
