### ISSUE TITLE
MediaStreams Array not mirroring Media Files Tracks

### ISSUE THREAD

**Issue by neilsb** [jellyfin/jellyfin#5279]
When a subtitle track has an undefined language it appears at the end of the `MediaStreams` array when querying the details of an item, rather than at the actual track position in the media file.  This results in the `MediaStreams` array not matching the structure of the Media File.

As an example, in this [official sample mkv file](https://github.com/Matroska-Org/matroska-test-files/blob/master/test_files/test5.mkv) has track 6 appears to be a subtitle track with no language:

![image](https://user-images.githubusercontent.com/5013482/108631689-fb7fb600-7462-11eb-855e-846de4fcc37c.png)

But when querying the item details from Jellyfin the results are (Track 6 appears in Position 10)

![image](https://user-images.githubusercontent.com/5013482/108631702-0f2b1c80-7463-11eb-88fb-efc7d5a2632a.png)

Would either expect the order of the `MediaStreams` array to match the source file, to allow use of the Array Index to identify the track in the file, or for the `MediaStrams[x].Index` field to reference the file's track index.

Edit: This is happening on latest 10.7 docker images

**Comment by cvium** [comment]
Cannot reproduce

**Comment by neilsb** [comment]
So the file [has moved](https://raw.githubusercontent.com/Matroska-Org/matroska-test-files/cf0792be144ac470c4b8052cfe19bb691993e3a2/test_files/test5.mkv) since the issue was posted but the seems to be exactly the same, and I still get the same results on 7.10.1 and Unstable (latest docker)

Requests to `/Users/{UserId}/Items/{ItemId}` still returns the same as above, with the Spanish subtitles in position 7 (and property `Index` has value 7 also) and the latest VLC (3.0.12) is showing the Italian subtitle track as being track 8.

Having said all that, using ffmpeg it does show the same order the API

```
Stream #0:1: Audio: aac (LC), 48000 Hz, stereo, fltp (default)
    Stream #0:2(eng): Subtitle: subrip (default)
    Stream #0:3(hun): Subtitle: subrip
    Stream #0:4(ger): Subtitle: subrip
    Stream #0:5(fre): Subtitle: subrip
    Stream #0:6(spa): Subtitle: subrip
    Stream #0:7(ita): Subtitle: subrip
    Stream #0:8(eng): Audio: aac (LC), 22050 Hz, mono, fltp
    Metadata:
      title           : Commentary
    Stream #0:9(jpn): Subtitle: subrip
    Stream #0:10: Subtitle: subrip
```

So maybe the problem is VLC?
