### ISSUE TITLE
Max bitrate= auto not working in Fire stick tv

### ISSUE THREAD

**Issue by Bandid0** [jellyfin/jellyfin#5281]
**Describe the bug**

**windows 10 x64:**
 - Clients: Fire Stick TV
 - Jellyfin Version: 10.8.0 20210221.10-unstable
 - Playback: Transcode
 - Installed Plugins :none
 - Storage: local

**Comment by nielsvanvelzen** [comment]
Please repost this issue in https://github.com/jellyfin/jellyfin-androidtv and include the information required in the template.
