### ISSUE TITLE
No 10.0.1-arm release on docker hub

### ISSUE THREAD

**Issue by SenorSmartyPants** [jellyfin/jellyfin#529]
I'm running a banana pi M1 and pull the image jellyfin/jellyfin. Running this at 16:46 UTC does not pull an update. I checked the tags on docker hub and the 10.0.1-arm version is not there.

```
Pulling jellyfin (jellyfin/jellyfin:latest)...
latest: Pulling from jellyfin/jellyfin
Digest: sha256:4f6d341dd793aa5d65bb80c4e82d2831908562a9d5768529186d41d4e7cbfed7
Status: Image is up to date for jellyfin/jellyfin:latest
```

**Comment by SenorSmartyPants** [comment]
10.0.1-arm version exists now.

But pulling from latest tag still doesn't grab it yet.

**Comment by LeoVerto** [comment]
Docker's `latest` tag is quite primitive and usually just redirects to another tag, in this case the `amd64` one, which is what people on most systems need to use.

If you want the arm version you will always have to explicitly specify that tag.

**Comment by nvllsvm** [comment]
@LeoVerto - incorrect, the latest tag is a manifest of the amd64, arm, and arm64 images. Docker should automatically pick the appropriate image when using the `latest` tag.

All 10.0.1 images have been pushed and the latest should resolve.
