### ISSUE TITLE
gaps between tracks ...

### ISSUE THREAD

**Issue by daves00** [jellyfin/jellyfin#5294]
Well, how to start, I know the jellyfin crew are excellent so i'm asking here first ....

Albums such as many pink floyd, have no gaps between the tracks. When ripped and I play them back they have gaps, which is bad in this case.

What is the cause of this gap?

I use the following:

1. I rip using fairstars free CD ripper - it seems to work very well
2. I run Jellyfin on my NAS, plenty of ram, reasonable processor and nothing other than Ubuntu running on the NAS
3. I stream to a Naim Uniti 2

I am not missing (as far as i can tell) any of the music in the tracks, they just don't flow seamlessly between one track and the next as they would with the original CD (i.e. there is a noticeable gap)

Is the likely cause Jellyfin? the Naim not pre-fetching the next track (stream)? the way the fairstars rips the tracks (i really hope not - re-ripping all my cd's .. ugh) - but at least an easy solution

The Jellyfin software runs smoothly on a HP mirocserver (Gen 8 , Xeon CPU, upgraded RAM, Unbuntu "Bionic"), no log errors, but Jellyfin does highlight a slow CPU on startup. That said it handles streaming ripped DVD's without any hiccups etc, therefore think CPU speed is an unlikely culprit.

Thanks for any insight you can provide
Dave

**Comment by dkanada** [comment]
Music players will always have a gap between tracks unless they specifically support gapless playback. The only Jellyfin client I know about that supports gapless right now is Gelli, but there may be more.

**Comment by chrstfer** [comment]
@dkanada what would it take to get gapless playback in the various official clients? Would any of your work on Gelli apply to the android client using exoplayer?

**Comment by dkanada** [comment]
ExoPlayer supports gapless with minor changes, the important part is using direct playback with a compatible format. If the official Android client started using ExoPlayer for music libraries it would support gapless automatically.

**Comment by chrstfer** [comment]
I believe the android client is transitioning to exoplayer already. Its an
option for the video player right now (client version 2.2.3 with server
10.7-rc4). Not sure about the audio player yet but I assume it will
ultimately also be based on exoplayer, if it isn't already.
