### ISSUE TITLE
Incomplete filename display 

### ISSUE THREAD

**Issue by itsangwu** [jellyfin/jellyfin#5295]
**Describe the bug**
When using the Mixed Content library, the displayed filename will get cut off prematurely. Using another type of library (such as Photo pointing to the same path) have no such display issue.

**System (please complete the following information):**
 - OS: unRAID
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Firefox 85
 - Jellyfin Version: 10.6.4
 - Playback: NA 
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: none
 - Networking: Bridge
 - Storage: local

**To Reproduce**
1. Go to create a library using "Mixed Content." Only used Screen Grabber and no other metadata downloader.
2. Go back to home page and view the library's displayed file and its filename

**Expected behavior**
The filename should be displayed fully

**Logs**
NA

**Screenshots**
"Mixed Content" library display
![image](https://user-images.githubusercontent.com/47978526/108759848-84a1f600-7512-11eb-8888-393377ca2009.png)

"Photo" library display pointing to the same path
![image](https://user-images.githubusercontent.com/47978526/108760084-d185cc80-7512-11eb-99dc-037c2b491ee7.png)

**Comment by ii41** [comment]
This problem still exists to me. The filenames shown for all my videos are incomplete, which the parts after (inclusive) the first closing bracket (`]`) missing. I'm running 10.8.1 on MacOS.

**Comment by ForsakenRei** [comment]
Do we have any update on this? I'm having the exact same issue with my anime library.
