### ISSUE TITLE
Display view artist or artists 

### ISSUE THREAD

**Issue by msaphoto06** [jellyfin/jellyfin#5298]
Hello, sorry for my english, i am a french user. I use a lot of multiple artists and am having trouble setting up jellyfin. My IDs use "artist" and "artists". it works perfectly under kodi but not under jellyfin: example: artistA and artistB - Track1 (id: artist = artistA and artistB | artists = artistA // artistB) Under Kodi and Jellyfin, he can see that there are several artists but the display of the song is different: Kody displays well artistA and artistB - track 1 Jellyfin displays artistA, artistB - track 1. Additionally, with jellyfin for kodi it displays artistA / artistB - track1. thanks for the help

**Comment by cvium** [comment]
Please fill out the issue template and provide screenshots
