### ISSUE TITLE
Add support for LDAP authentication

### ISSUE THREAD

**Issue by sparky8251** [jellyfin/jellyfin#53]
If I'm not mistaken, Emby supports LDAP authentication but only through a paid plugin. LDAP support would streamline authentication and allow Emby to be used in larger deployments working better with #42 in a multi-server environment.

Plus, even with a small setup, LDAP dramatically reduces the administration load around managing user accounts.

**Comment by anthonylavado** [comment]
This is something that is highly desired by @joshuaboniface so I know this will get some attention. Right now, the focus is stability, but this is gonna be high up on the list after that.

**Comment by sparky8251** [comment]
Oh yeah. Only opened this so its on the issue board. 

Not expecting this to happen for some time, especially with so much organization and stabilization work going on.

I plan on watching this for developments in the future :)

**Comment by XVicarious** [comment]
Yeah, I figured that was the case as I just laid jellyfin over my Emby
stuff. I'm sure it's permissable to use the plugin as long as you guys
arent shipping it.

**Comment by drago-96** [comment]
It would be wonderful if you also added Kerberos auth.
Or at least enable authentication via the REMOTE_USER header, so I can put Jellyfin behind a ProxyPass and make Apache/nginx deal with the auth.

**Comment by LogicalPhallacy** [comment]
@JustAMan This should likely be tagged as a feature for netcore3. I am going to try and get to it before then, but LDAP support on netcore is dodgy right now as it relies on a port of an old java lib.

**Comment by joshuaboniface** [comment]
To work on the suspense.... IT WORKS! We do have a working LDAP plugin thanks to @LogicalPhallacy and some hacks to it by myself. It should be available along with the 10.3.0 release.
