### ISSUE TITLE
Support for OIDC or SAML IdP

### ISSUE THREAD

**Issue by davmin** [jellyfin/jellyfin#530]
I'd like to see support for external identity providers and SSO in the future, namely keycloak.

**Comment by mgrandl** [comment]
+1 for OIDC. I know LDAP is coming, but I think OIDC would be much nicer.

**Comment by JasonN3** [comment]
This would be extremely limited. The point of OIDC and SAML is so the app doesn't know your password because it never did the authentication. Instead the application redirects you to the IdP's site, they do the authentication, and then they tell the application whether you knew the password or not and what roles you're assigned. The mobile app and the Kodi plugin aren't web browsers so they can't redirect you to the IdP's site. You could potentially open a link in the default browser, but then you run in to the issue of knowing when the user is done logging in. You have no visibility or control of the external browser.

If someone still wants to give this an attempt, I can recommend using jellyfin-plugin-ldapauth as a base and then adjusting the code to use OneLogin's OpenID Connect library to do the OIDC processing. You would still need to add a link to the login page to kickstart the OIDC process and you would need to figure out a way to handle connections that don't come from the web interface.

**Comment by Rob4001** [comment]
I would be interested in making a pass at this, Although I don't think you would be able to make an LDAP style plugin for this. 
The basic OIDC handling would have to be done on a callback endpoint, which could be made generic across multiple OIDC providers, but each provider (at least some of the main ones : Google, Facebook, etc) and one for custom self hosted solutions.

Most likely this callback would, on successful login, convert to the default X-Emby-Authorization based access token system.

I am sure that once this system is in place we could look into the native support for OIDC on the apps/smart TV clients, I know Android/IOS apps can open "pop up" web browser components to complete this task

**Comment by danieljkemp** [comment]
IMO worring about OIDC in most apps, especially android/TVs is overthinking
it. Easypin already exists, either direct users to use that, or the full
solution could use an application key system at the user level.

**Comment by dkanada** [comment]
It's not a terrible idea, it would just require a lot of work since each client would need it's own implementation. We don't technically have any other plugin types that require such a thing yet.

**Comment by danieljkemp** [comment]
The work would be on the server side actually. Here is an example of how it
would work:

1. User logs in via OIDC and the account is created in Jellyfin matching
the OIDC user.
2. User creates an application password using the UI, (right below easy
pin).
3. User logs in on their android/TV/etc application using their standard
username, and  the application password created in step 2.

This is also the flow used by many applications when needing to setup
third-party access where it is undesirable to use the user's main login on
a third party application. Here is a page describing how the idea works
with google accounts:
https://support.google.com/accounts/answer/185833?hl=en.

**Comment by Rob4001** [comment]
So I have spent a bit of time getting used to the code base, probably going to base off the api-migration branch although this will probably require modification on both Server and Web. 

Plan of action:

1. Create Admin page to configure OIDC provider (authority URL, Client ID, Client Secret, Auth Name, If Users Created, Other security requiremests/claims etc)
2. Create API endpoint (/users/oidc/providers) to allow clients to access this config
3. Modify the login page to include sign in buttons under the manual login form, these will direct users to OIDC Provider login page (specifically using authorization_code flow)
4. Create web page to act as OIDC callback with parameters for provider name (set in redirect url) and auth code
5. Create API endpoint (/users/oidc/login/{provider}) to:
a. Communicate with OIDC Provider to fetch Token
b. Validate Token with OIDC Signing keys etc
c. Attempt to link Token sub claim with known user. If there is a linked user account, return Successful Auth Response with Standard Auth Token, redirect to home etc. If no linked account return account linked required response, proceed to 6
6. OIDC callback page will ask user to authenticate using Username/Password to link account OR if account creation enabled they can request a new account be created.
7. Create API endpoints for Account link (/users/oidc/link) or new user (/users/oidc/new)

The only real question is how to store the account linking, would it be better to add a new related table to store (UserID,ProviderID/Name,ProviderSubValue) or somehow modify the existing User object to include reference to this?

**Comment by quentinus95** [comment]
Can this issue be reopened?

**Comment by crobibero** [comment]
This is a feature request, so it belongs in https://features.jellyfin.org.
A request already exists for it here: https://features.jellyfin.org/posts/230/support-for-oidc
