### ISSUE TITLE
Subtitle not show when transcoding file with rclone from OneDrive

### ISSUE THREAD

**Issue by heroes1412** [jellyfin/jellyfin#5300]
**Describe the bug**

**System (please complete the following information):**
 - OS: Windows Server 2019 x64
 - Virtualization: None , running on physical server
 - Clients: Chrome Browser, Android Mobile
 - Browser: Chrome 87 and latest, jellyfin mobile apk latest
 - Jellyfin Version: 10.6.4
 - Playback: Transcode (HEVC files)
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: none
 - Networking: NAT
 - Storage: Onedrive with rclone 
rclone mount onedrive: E:\Setup\Jellyfin\Repo2 --vfs-cache-mode writes  --use-mmap --daemon-timeout=10m --vfs-read-chunk-size 10M --vfs-read-chunk-size-limit 512M --cache-dir E:\Setup\Cache --allow-other --dir-cache-time 8h --drive-chunk-size 128M --log-level INFO --log-file E:\Setup\Cache\rclone.log --timeout 1h --config "E:\Setup\rclone\rclone.conf"

**Expected behavior**
Subtitle show normally

**Logs**

**Screenshots**

**Additional context**
i tried create a new library with local HEVC file, but subtitle show normally.

**Comment by BaronGreenback** [comment]
not familiar with rclone. How are the paths encoded?

I know there is a PR to fix an issue caused when a file is accessed via http, but the subs are local. (PR https://github.com/jellyfin/jellyfin/pull/5278)

**Comment by heroes1412** [comment]
> not familiar with rclone. How are the paths encoded?
> 
> I know there is a PR to fix an issue caused when a file is accessed via http, but the subs are local. (PR #5278)

I try 2 method:
1. Sub embedded in mkv file
D:\onecloud\film.mkv
2. External sub
D:\onecloud\film.str

Path is ascii code, non unicode character, no more than 255 character in path...

**Comment by heroes1412** [comment]
i see (fetching additional data endlessly)....
i tried the repository with Plex, subtitle load well. The issue will only appear with Emby.

**Comment by cvium** [comment]
Embedded subtitles are extracted on-the-fly, but a separate ffmpeg process is spun up for the extraction, which means it has the read the entire file _again_ and I imagine it can be quite slow when done via an rclone mount.

If you force subtitle burn-in it should be "resolved". There's unfortunately no other fix atm.

**Comment by heroes1412** [comment]
> If you force subtitle burn-in it should be "resolved"
how can i do that?

**Comment by cvium** [comment]
> 
> 
> > If you force subtitle burn-in it should be "resolved"
> 
> how can i do that?

If you set the resolution or bitrate lower than the file it will transcode. I don't think it's possible to force it in other ways.

**Comment by heroes1412** [comment]
maybe it cannot be resolved. Because i tried use Jellyfin in WebOS LG TV, jellyfin client no need transcode to play the file. But subtitle still not show.
