### ISSUE TITLE
Absence of the "Group movie into collection" button

### ISSUE THREAD

**Issue by mife-02** [jellyfin/jellyfin#5309]
I may be wrong but I searched for it in some places and didn't found it 
Jellyfin version : 10.7 rc3

**Comment by cvium** [comment]
I don't think we ever had a dedicated button for it. You can merge two movies by long clicking them (this activates multi-select) and then opening the context menu.

![image](https://user-images.githubusercontent.com/675118/110634332-229bee80-81aa-11eb-8987-5a9a7426bfe9.png)

**Comment by mife-02** [comment]
nono, there was !
Let me find the screenshot

**Comment by mife-02** [comment]
![image](https://user-images.githubusercontent.com/79696191/110652990-28e79600-81bd-11eb-943f-6a6c4ba15509.png)

I finally found it in the settings. It was juste very hard to see :p
