### ISSUE TITLE
Movie versions not stacking with BluRay folders

### ISSUE THREAD

**Issue by speedstyle** [jellyfin/jellyfin#5318]
Movie versions and extras are not correctly detected and merged in BDMV format.

**System:**
 - OS/Virtualization: Docker for Windows
 - Jellyfin Version: tested on 10.6.4 (jellyfin:latest) and 10.8.0 (jellyfin:unstable)
 - Installed Plugins: none
 - Storage: local NTFS drive, mapped to `/media`

**To Reproduce**
Create a folder structure analogous to:
/media/movies
- /Inception (2010)
    - /Inception (2010) - 2160p/BDMV
    - /Inception (2010) - 1080p/BDMV
    - /Extras
        - /Bonus Disc/BDMV
- /Catch Me If You Can (2002)
    - /Catch Me If You Can (2002) - 1080p.mkv
    - /Catch Me If You Can (2002) - 720p.mkv
    - /Extras
        - /Bonus.mkv

**Expected behavior**
Both films show up identically, with two versions and some extras clips. (Bonus Disc might only show one clip, but the versions should still be merged.)

**Actual behaviour**
File-based formats are merged correctly, but BDMV folders all show separately.

![image](https://user-images.githubusercontent.com/27833850/109408106-48412080-797e-11eb-85e6-fca61bd00ad8.png)

**Comment by speedstyle** [comment]
Reproduced in the latest `jellyfin:unstable`.

**Comment by EnGyUncia** [comment]
I confirm that! Same thing on my instance.
System:
  - OS/Virtualization: Linux x64
  - Jellyfin Version: 10.8.7 stable
  - Installed Plugins: standard
  - Storage: local drive

File structure:
- /Harry Potter and the Half-Blood Prince (2009)
    - /Harry Potter and the Half-Blood Prince (2009) - 1080P
       - /BDMV
    - /extras
       - /BDMV
Actually extras BDMV container doesn't show at all. 

If i rename my "extras" folder into something like "Harry Potter and the Half-Blood Prince (2009) - Directors Cut" - it shows in jellyfin, but as a separate movie, as it should. But it's not another version of the same movie - it's extra-content!
