### ISSUE TITLE
DLNA profile not being detected correctly

### ISSUE THREAD

**Issue by filipe-silva** [jellyfin/jellyfin#5319]
Hi, so I have an LG tv with webOs 2.0, and it can direct play h264 and mpeg4, however when it comes to h264 it can't.
This is a 10 bit file:
![imagem](https://user-images.githubusercontent.com/4389874/109414579-7db03300-79ab-11eb-8134-17d13feb85bd.png)

I have a custom profile made for the tv, and did this for the codecs part:
![imagem](https://user-images.githubusercontent.com/4389874/109414497-16927e80-79ab-11eb-8804-1bebc8ff56db.png)

And this for the direct play:
![imagem](https://user-images.githubusercontent.com/4389874/109414517-24480400-79ab-11eb-8bf5-58fb154d11a1.png)

Suffice to say it doesn't work. I need some help, how to force transcoding for video files of h264 10bit?
What am I missing?
I've search the docs, emby docs, and the web but couldn't figure it out, some leads would be most appreciated, thank you.

**Comment by BaronGreenback** [comment]
From what I've learnt writing DLNA profiles are a bit of a dark art.

The dlna xml profile file should be under config/dlna/user - can you post that please?

**Comment by filipe-silva** [comment]
Hi @BaronGreenback  I can't seem to find the folder location.
I have it installed on linux (ubuntu server 20.04), any idea where it might be?

**Comment by BaronGreenback** [comment]
Running windows myself. According to the docs - it's here

$XDG_DATA_HOME/jellyfin
or
$HOME/.local/share/jellyfin

**Comment by filipe-silva** [comment]
Finally found it, it was in:
/etc/jellyfin/dlna/user

It's attached, had to change the extension to txt but it's the custom profile xml I've been tinkering with.
[LG47.txt](https://github.com/jellyfin/jellyfin/files/6057941/LG47.txt)

**Comment by BaronGreenback** [comment]
I submitted a PR's last night that might help - it looks like some of the profiles aren't being detected by the stream sub-system.

**Comment by filipe-silva** [comment]
If you said what I think, then I saw that too.
Basically while trying out several things, I saw in the log that when I used BubbleUpnp to send the stream to the TV it wasn't recognized as the TV profile but as a generic profile. 
So then I tried using the TV to select the stream and voilá it transcoded correctly.

**Comment by srcrist** [comment]
Does this issue still exist in version 10.8.11? It sounds as if it might have been fixed by PRs in 2021, but remains open. Can anyone provide relevant, recent feedback?

**Comment by filipe-silva** [comment]
I'll update to that version, and check if it still happens.

**Comment by filipe-silva** [comment]
Well, I honestly don't know which file I used back then. 
I'm also on windows now and have had a new install.
I've been testing some 10 bit, but they are H.265/HEVC codec. All seem to be working ok (no subs but that's a me problem), I'll close it.
