### ISSUE TITLE
subtitles not complete

### ISSUE THREAD

**Issue by Cloneg** [jellyfin/jellyfin#5323]
**Describe the bug**
 Subtitle with this format are not complete. It just shows on screen the first line eg: "este lugar se convertirá". 

311
00:16:46,465 --> 00:16:49,009
Una vez que la gente se entere

de que ustedes están aquí,

312
00:16:49,092 --> 00:16:51,470
este lugar se convertirá

en un maldito zoológico.

[subs.zip](https://github.com/jellyfin/jellyfin/files/6430256/subs.zip)

**System (please complete the following information):**
 - OS: windows (also happens in android tv, android)
 - Virtualization: [e.g. Docker, KVM, LXC]
 - Clients: browser
 - Browser: chrome 88
 - Jellyfin Version: 10.6.4
 - Playback: Direct Stream, Transcode
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: none
 - Networking: [e.g. Host, Bridge/NAT]
 - Storage: local

**To Reproduce**

Play any show with subtitles with this format.

**Expected behavior**
 It should show on screen "este lugar se convertirá en un maldito zoológico." in two lines. When using an external media player like vlc it shows both lines.

**Logs**

**Screenshots**

web
![image](https://user-images.githubusercontent.com/67025623/109425845-6461b380-79b8-11eb-8998-967cc7016737.png)
android tv
![image](https://user-images.githubusercontent.com/67025623/109425621-22843d80-79b7-11eb-962c-6c0d133750a6.png)
vlc windows (same in android)
![image](https://user-images.githubusercontent.com/67025623/117210233-06d55300-adbd-11eb-94ef-6171e0a041b8.png)

**Additional context**
 This also happens in last versions of android tv and android.

**Comment by Bond-009** [comment]
Should be fixed by #4984
