### ISSUE TITLE
When using a reverse proxy, different sessions cannot find each other, breaking remote control

### ISSUE THREAD

**Issue by hawken93** [jellyfin/jellyfin#533]
found this while looking at #496
Turns out I could not find any devices to remote control because I was using a reverse proxy, and somehow that breaks the functionality.

I think jellyfin must be looking at the originating ip, and somehow rely on that to identify sessions. Maybe a security measure. But it breaks this..

**Comment by sparky8251** [comment]
Poke at various proxy settings like transparent and such. One such setting out to exist that will fix your problem.

It seems unlikely to me that this is a problem with the server. I've found all number of web apps break in odd ways if I don't set the reverse proxy *perfectly*.

**Comment by hawken93** [comment]
I can't make it transparent, that's not possible for my usecase. In my case I'm using apache in front of it

**Comment by sparky8251** [comment]
Well, not claiming transparent is the missing setting. But if it is, it might not be trivial to fix it in the actual code vs turning on the setting.

**Comment by hawken93** [comment]
```
<VirtualHost bla bla>
    bla bla bla...

    ProxyPass / http://bla:8096/
    ProxyPassReverse / http://bla:8096/
    RewriteEngine On
    RewriteRule ^/embywebsocket(.*) ws://bla:8096/embywebsocket$1 [P,QSA]
</VirtualHost>
```
Turns out that we have to proxy websocket with GET parameters nowadays.

**Comment by hawken93** [comment]
Should be documented...
