### ISSUE TITLE
When scanning libraries in rc4 version, I get an error in the console and the server closes

### ISSUE THREAD

**Issue by JulioNahum** [jellyfin/jellyfin#5331]
**Describe the bug**
When wanting to put a library of Movies, jellyfin recognizes it as if it were a category of OTHERS. And when wanting to scan, it throws me the following error and suddenly the server closes:

**System (please complete the following information):**
 - OS: [Windows 10]
 - Jellyfin Version: [10.7.0 rc4]

**Screenshots**

https://imgur.com/d4lyzE0

**Comment by JulioNahum** [comment]
UPGRADE:
I found the error. I saw the console before the server was shut down due to the error, and everything seems to indicate that the error is the TMDb Box Set plugin. When deleting it, and rescanning, the server does not suffer any relevant errors, and continues scanning for the moment.

**Comment by Bond-009** [comment]
TMDb Box Set plugin doesn't support 10.7 yet

**Comment by JulioNahum** [comment]
Oh, a thousand apologies, with the rc3 version it worked perfectly for me. But ready. I deleted it and it works out of 10 for me, except with the two bugs that I already opened a ticket for them to review.

**Comment by JulioNahum** [comment]
> TMDb Box Set plugin aún no es compatible con 10.7

Oh, a thousand apologies, with the rc3 version it worked perfectly for me. But ready. I deleted it and it works out of 10 for me, except with the two bugs that I already opened a ticket for them to review.
