### ISSUE TITLE
Thumbnails very big in file size on phone

### ISSUE THREAD

**Issue by jsddsfoh** [jellyfin/jellyfin#5344]
**Describe the bug**
If I open a folder with 100-200 pictures on my Laptop, thumbnails are generated and transferred to it. Can verify it with developer tools in browser, each picture has some kB.
If I open the same folder on my android phone, with browser or app, according traffic meter, nearly the full file size is transfered.

**System (please complete the following information):**
 - OS: [e.g. Debian, Windows]
 - Virtualization: [e.g. Docker, KVM, LXC]
 - Clients: Windows 10 Vivaldi and Firefox, Android app and browser
 - Browser: 
 - Jellyfin Version: 10.6.4
 - Playback: [Direct Play, Remux, Direct Stream, Transcode] 
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: nonoe
 - Networking: Host
 - Storage: local

**To Reproduce**

1. Go to a folder with pictures, 5MiB size each picture
2. Click on --
3. Scroll down to the end
4. See transferred file size. Also, because of lage thumbnails on phone, scrolling up and down is laggy. oneplus 7t pro used.

**Expected behavior**
I expect small thumbnails also on android

**Logs**

**Screenshots**

**Additional context**

**Comment by Bellusterra** [comment]
Getting the same result on ios web and on the ios App. Cannot scroll down the page without significant stuttering and lag. I have a lot of folders, but the same directory opens well and is quick on desktop web client. Also does not appear to be respecting any cache, nginx reverse proxy cache is filling up, but with no change in thumbnail generation and lag. Appear to only be generated when in frame and pulled down each time from the server.

**Comment by Bond-009** [comment]
This is a clients issue, they control the image requests.
