### ISSUE TITLE
Metadata Retrieval Error

### ISSUE THREAD

**Issue by DillFrescott** [jellyfin/jellyfin#5346]
**Describe the bug**
Error while fetching metadata from TVDB.

**System (please complete the following information):**
 - OS: Ubuntu Server 20.04 LTS
 - Virtualization: none
 - Clients: Browser
 - Browser: Firefox 86.0
 - Jellyfin Version: 10.6.4
 - Playback: n/a
 - Installed Plugins: just default plugins
 - Reverse Proxy: Caddy
 - Base URL: none
 - Networking: Not Sure
 - Storage: local

**To Reproduce**
1. Acquire Re:Zero season 2
2. Transfer episodes to Jellyfin
3. All first 13 episodes show up as episode 2.

**Expected behavior**
They should show up as episode 1-13 and not 13 episode 2's.

**Logs**
No error logs.

**Screenshots**
https://i.ibb.co/VjwNYF5/jellyfin-issue.gif

**Additional context**
I tried editing the TVDB and IMDb data manually and refreshing the metadata, it doesn't work :(

**Comment by BaronGreenback** [comment]
Looks like it might be fixed with PR #5339

**Comment by DillFrescott** [comment]
Ok. Thank you!

**Comment by DillFrescott** [comment]
I'm now on version 10.7.1 and it's still doing it...

**Comment by DillFrescott** [comment]
I managed to "fix" it by manually editing the metadata for each episode and refreshing...
