### ISSUE TITLE
Might not be a bug but is unstable supposed to say version 10.8.0?

### ISSUE THREAD

**Issue by ikomhoog** [jellyfin/jellyfin#5350]
**Describe the bug**
Like the title says I just noticed while testing on unstable that it says version 10.8.0
Is this planned?
Am I supposed to make bug reports about these kind of things in the unstable branch or should I just let them be?

**System (please complete the following information):**
 - OS: Unraid
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Chrome
 - Jellyfin Version: 10.8.0? 10.7.0-RC4 Unstable
 - Playback: -
 - Installed Plugins: -
 - Reverse Proxy: nginx
 - Base URL: jellyfin.domain.com
 - Networking: bridge
 - Storage: local

**To Reproduce**

1. Install Unstable
2. Look at version

**Comment by Shadowghost** [comment]
It's intentional since 10.7 is feature frozen and detached from master in it's own branch (10.7.z). What's developed in master is 10.8.
