### ISSUE TITLE
[Bug] Jellyfin Mac installer builds are not updated

### ISSUE THREAD

**Issue by ModdedGamers** [jellyfin/jellyfin#5351]
**Describe the bug**
The mac .dmg RC build is not updated to 10.7.0-RC4

**System (please complete the following information):**
 - OS: macOS
 - Virtualization: N/A
 - Clients: N/A
 - Browser: N/A
 - Jellyfin Version: N/A
 - Playback: N/A 
 - Installed Plugins: N/A
 - Reverse Proxy: N/A
 - Base URL: N/A
 - Networking: N/A
 - Storage: N/A

**To Reproduce**

1. Go to https://repo.jellyfin.org/releases/server/macos/stable-rc/
2. See that the latest .dmg build is 10.7.0-RC3
3. 
**Expected behavior**
Updated build for RC4.
**Logs**
N/A

**Screenshots**
N/A

**Additional context**
N/A

**Comment by nielsvanvelzen** [comment]
It's up now :)

**Comment by ModdedGamers** [comment]
Thanks!
