### ISSUE TITLE
ToList Usage

### ISSUE THREAD

**Issue by shortspider** [jellyfin/jellyfin#5355]
**Describe the bug**
In looking at the code I noticed that `ToList` is used quite liberally. Take the following as an example (but there are lots more):
![image](https://user-images.githubusercontent.com/5712543/109748185-6c7f4600-7ba6-11eb-809b-8b5f9b07277b.png)
The problem with the above is that every call to `ToList` creates a copy of the `IEnumerable`. So in the above we create a copy of `_profiles.Values` (this may or may not be needed depending on thread safety) and we then create a another copy after we order and filter the first copy. This second copy at least isn't needed at all since the method states that it returns an `IEnumerable`. This copying is death by 1000 cuts since we need to spend CPU allocating the memory for the copy, doing the copy, and then collecting the original and copy when the GC kicks in.

There are a number of usages like this in the code. I'd like to take a crack at fixing them but wanted to know how best to go about it. One big PR? A PR per class or namespace? I understand this isn't exactly a bug report but it's not a feature request either so I thought I'd post here. Please feel free to close and direct me somewhere else if that's more appropriate.

**Comment by crobibero** [comment]
I would recommend a class per class/namespace, large PRs tend to stick around as they’re less likely to be reviewed

**Comment by dkanada** [comment]
I'd say LoC is a better indicator of review turnaround time. Anything under 200 LoC is usually pretty fast here so if you can fit everything within that size it could be fine :p

**Comment by cvium** [comment]
Your example is not terribly great. The first `.ToList()` is probably superfluous given the lock on the `_profiles` object. But the last `.ToList()` is necessary. LINQ is evaluated lazily, so you have to force the enumeration inside the lock.

**Comment by shortspider** [comment]
@cvium I mean, you still are pointing out that one `ToList` is unneeded so I think it serves as a decent example. The lock does complicate it though.
@crobibero @dkanada thanks for the feedback, I'll try and go by class/namespace while keeping the LoC down.

**Comment by Bond-009** [comment]
@cvium Do we want to keep this open? All the biggest allocations should already be fixed, no?

**Comment by cvium** [comment]
The ToList usage is still a bit excessive in some places, so dunno

**Comment by felix920506** [comment]
Please head to the development channel in our chat rooms to discuss the matter further. https://jellyfin.org/contact

**Comment by sarah-strawberries** [comment]
My classmates @happystar9 and @jesus-sunuc and I are interested in helping out with this; any input on what we should get started with?

**Comment by sjorge** [comment]
> My classmates [@happystar9](https://github.com/happystar9) and [@Jesus-sunuc](https://github.com/Jesus-sunuc) and I are interested in helping out with this; any input on what we should get started with?

Felix's message above is still valid, hop over to the development chat on matrix or discord and ask there. It can take bit for someone to reply with timezones and all being a thing.
