### ISSUE TITLE
Fast forward and rewind not working

### ISSUE THREAD

**Issue by Nagamorich** [jellyfin/jellyfin#5358]
I have installed jellyfin android tv 0.11.5 on my android tv box running android 8.1.0. The fast forward and rewind controls do not work. I have tried the native player, vlc, mx pro and uplayer but the issue is the same. The run time of the stream is working but the progress bar does not move. I can stop and restart the stream. It appears to be an android 8.1 problem because everything is fine on an android 9.0 box. There is no os upgrade for the android 8.1 box. Is there a fix please?

**Comment by crobibero** [comment]
This is a known issue. https://github.com/jellyfin/jellyfin-androidtv/issues/308
