### ISSUE TITLE
Creacting an empty collection, invokes thousand unwatched items

### ISSUE THREAD

**Issue by HavermansStef** [jellyfin/jellyfin#536]
When I created a new collection, Jellyfin made it seems there are thousand unwatched item in the collection.

https://i.imgur.com/rE09A6U.png

Working on 10.0.1.0, Windows 10 64b

**Comment by anthonylavado** [comment]
Ooooh. Is this different than a Box Set? (I've never used collections :sweat_smile: )

**Comment by JustAMan** [comment]
@HavermansStef could you please provide the steps to reproduce what you saw? And maybe something unusual in server logs?

**Comment by HavermansStef** [comment]
My movies --> Collections
--> The plus button
--> Name it Star Wars and check search internet for artwork
--> Press ok

Leave the collection empty

Go to collections. 
You got an empty collection with thousands of items which results in an error when pressed to play.
This is the full log and another picture proof. 
[New Text Document.txt](https://github.com/jellyfin/jellyfin/files/2772276/New.Text.Document.txt)
.
https://i.imgur.com/nZko0i9.png

**Comment by JustAMan** [comment]
@anthonylavado this looks similar to what you described about your music collections getting added total amount of elements in your library. Can you link here to that issue if one exists?

**Comment by anthonylavado** [comment]
This may be fixed by #680.

**Comment by anthonylavado** [comment]
Currently running a test build with #680 included. This issue doesn't appear to occur anymore. Watch for this in the next release.
