### ISSUE TITLE
Jellyfin randomly stops with rc4

### ISSUE THREAD

**Issue by undead9786** [jellyfin/jellyfin#5365]
**Describe the bug**
RC3 was working fine and when upgrading to RC4 jellyfin randomly stops

**System (please complete the following information):**
 - OS: Windows
 - Virtualization: N/A
 - Clients: N/A
 - Browser: N/A
 - Jellyfin Version: 1.7.0 rc4
 - Playback: N/A
 - Installed Plugins: N/A
 - Reverse Proxy: N/A
 - Base URL: [e.g. none, yes: /example]
 - Networking: N/A
 - Storage: N/A

**To Reproduce**

1. Just randomly stops

**Expected behavior**
Not stop

**Logs**
If logs are needed please let me know what to do to get what you need.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by ikomhoog** [comment]
Do you have the TMDb Box Sets plugin installed?
There is currently a bug where it crashes when refreshing library metadata.
try comparing your logs with mine in https://github.com/jellyfin/jellyfin/issues/5348
if it is the same, disabling TMDb Box sets will fix this until it's updated.

**Comment by undead9786** [comment]
So far 4 hours and still running since I disabled that. Will keep an eye out.

**Comment by undead9786** [comment]
24 hours and still running so looks like you were right about the plugin.

**Comment by cvium** [comment]
Ok, closing as it must've been fixed by https://github.com/jellyfin/jellyfin/pull/5339
