### ISSUE TITLE
please re-open incorrectly closed bug report #5348

### ISSUE THREAD

**Issue by ikomhoog** [jellyfin/jellyfin#5367]
I reported a bug https://github.com/jellyfin/jellyfin/issues/5348, then there was a pull request attached.
The pull request was finished and closed the issue, but the problem is not solved in the latest unstable release.

Sorry if I'm too impatient with opening a new bug report.
But there are people who were already on the right path.

**Comment by crobibero** [comment]
Plugin issues belong in the plugin-specific repo

**Comment by ikomhoog** [comment]
But getting metadata with the build-in identify button is not a plugin or is it? it's not showing up as a plugin.
I only talked about the plugin because it also had problems and is doing things with TMDb and metadata.
But the main issue of that bug report is about no results when using the identify button.
Also I already made a plugin specific bug report on the plugin page jellyfin/jellyfin-plugin-tmdbboxsets#32
