### ISSUE TITLE
"Latest" links on Home screen do not link to recently added content. 

### ISSUE THREAD

**Issue by pmcdon1** [jellyfin/jellyfin#5372]
When I click on the links "Latest Movies", "Latest Shows" etc. The resulting page lists every title in the library in alphabetical order and not the expected shortlist of recently added content. 

 - OS: Ubuntu 20.10.0
 - Virtualization: Docker Image: jellyfin/jellyfin:10.7.0-rc4
 - Clients: Firefox, Android
 - Browser: Firefox, Chrome
 - Jellyfin Version: Docker Image: jellyfin/jellyfin:10.7.0-rc4
 - Playback: N/A
 - Installed Plugins: None
 - Reverse Proxy: None
 - Base URL: None
 - Networking: Host
 - Storage: Local

**To Reproduce**

1. On the home screen.
2. Click on 'Latest Movies' OR 'Latest Shows'
3. A page loads which displays the Entire movie catalog.
4. The expected result is a shortlist of recently added content.

**Expected behavior**
The expected result is a shortlist of recently added content.

**Logs**
N/A

**Screenshots**
N/A

**Additional context**
The installation is the official docker container. The install was a fresh install. The existing home/user/docker/jellyfn directory was deleted and browser cache was purged before container creation.

**Comment by ikomhoog** [comment]
Clicking on 'Latest Movies' should bring you to the same place as opening the Movie library and clicking on suggestions.
Does that work for you?
What is the URL you get sent to?
Mine is:
```
https://jellyfin.mydomain.com/web/index.html#!/movies.html?topParentId=f137a2dd21bbc1b99aa5c0f6bf02a805&tab=1
```
Are there any errors logged in jellyfin or the browser(f12)?

**Comment by cvium** [comment]
Cannot reproduce in 10.7.1.
