### ISSUE TITLE
Executable Missing Post Windows Updates/Reboot

### ISSUE THREAD

**Issue by graintiger** [jellyfin/jellyfin#5374]
When trying to run Jellyfin today both the Jellyfin.Windows.Tray,exe and jellyfin.exe are both no longer present in the installation directory - all other files look to be intact.

Server was working fine when first installed a week ago however today looking to connect realising the tray app was not running both the above noted files no longer exist.

PC has been rebooted since the installation but I would not expect that to have caused such an issue. The only windows updates that have installed since the installation of Jellyfin are assorted security intelligence updates for Microsoft Defender Antivirus and the 2021-20 cumulative update preview for Windows 10 Version 20H2 for x64-based Systems.

Windows Defender is not enabled as my main threat protection and the protection history  and scan logs from software being used show nothing as being quarantined or removed.

Windows 10 Pro 10.0.19042
Jellyfin 10.7.0-rc3

**Comment by anthonylavado** [comment]
I've had a few reports of EXEs going missing, but it only ever seems to happen once and then never again. Now that the full release is out, try that, and feel free to ping me if this needs to be re-opened 🙂
