### ISSUE TITLE
Plugin versions are no longer displayed correctly ( nightly 20210303 )

### ISSUE THREAD

**Issue by EVOTk** [jellyfin/jellyfin#5379]
**Describe the bug**

**System (please complete the following information):**
 - OS: DSM 6.2.3-3
 - Virtualization: Docker
 - Clients: Web Client
 - Browser: Firefox 86
 - Jellyfin Version: nightly 20210303
 - Installed Plugins: Trakt, Gotify
 - Reverse Proxy: SWAG
 - Networking: Bridge
 - Storage: local

**To Reproduce**

1. Go to 'dashboard'
2. Click on 'Extensions'
3. See version are "[object Object]" for all Extensions
![C3bCrLR](https://user-images.githubusercontent.com/45015615/110097704-a49da900-7d9f-11eb-853d-d389f7bffae2.png)

The plugins still work correctly despite this display problem.

**Comment by Bond-009** [comment]
My bad I think

**Comment by EVOTk** [comment]
Thx @Bond-009

**Comment by EVOTk** [comment]
Hello,
the layout has changed, but the bug is still present on nightly-20210307

![](https://i.imgur.com/9NDlccd.png)

**Comment by crobibero** [comment]
![image](https://user-images.githubusercontent.com/24963659/110249596-1575ca00-7f34-11eb-90e2-845d59818cb3.png)
I can't reproduce this with latest master, so likely something didn't build properly.

**Comment by EVOTk** [comment]
It's Okay for me.
Thx!
