### ISSUE TITLE
Applying search results on library entries (especially series)

### ISSUE THREAD

**Issue by Larvitar** [jellyfin/jellyfin#5390]
This is a follow up to what I wrote in #5384. 

When "Identify" is used on a library entry Jellyfin calls `RefreshFullItem` sending already existing `Item` and search result:
[ItemLookupController.cs](https://github.com/jellyfin/jellyfin/blob/master/Jellyfin.Api/Controllers/ItemLookupController.cs#L296)
```c#
            var item = _libraryManager.GetItemById(itemId);
...
            item.ProviderIds = searchResult.ProviderIds;
            await _providerManager.RefreshFullItem(
                item,
                new MetadataRefreshOptions(new DirectoryService(_fileSystem))
                {
                    MetadataRefreshMode = MetadataRefreshMode.FullRefresh,
                    ImageRefreshMode = MetadataRefreshMode.FullRefresh,
                    ReplaceAllMetadata = true,
                    ReplaceAllImages = replaceAllImages,
                    SearchResult = searchResult
                }, CancellationToken.None).ConfigureAwait(false);
```
This behaviour leads to two issues:
1. (Common) Fields from previous (misidentified) entry may be copied to the new one if a provider does not return this particular field (as stated in a TODO here: [MetadataService.cs](https://github.com/jellyfin/jellyfin/blob/master/MediaBrowser.Providers/Manager/MetadataService.cs#L767) ) . 
2. (Series related) All children (seasons and episodes) will not be reintentified. This is not an issue with TVDB or TmDb providers, as those seem to always rely on `SeriesProviderIds`, but it will be an issue for any provider that sets season and episode IDs. It wil set an ID to every episode during first library scan and then after user uses "Identify" on a series, season/episode IDs will not be changed and still point to wrong entries.

The way I see it during `ApplySearchCriteria` item should be just dropped, recreated with only info from `searchResult` - `Name`, `ProviderIds` and `ProductionYear` (hopefully keeping guid?) - and a full folder scan should be started instead of a metadata refresh, but right now I don't understand this code well enough to implement it myself and I'm not sure how it might impact other entries like collections, albums etc.

**Comment by RemuxKid** [comment]
I can confirm having this bug too! Thank you so much for the pull req :)
