### ISSUE TITLE
plugin manifest resource unavailable

### ISSUE THREAD

**Issue by spannerman79** [jellyfin/jellyfin#5397]
**Describe the bug**

Resource location failure for updating json for plugins

**System (please complete the following information):**
 - OS: [e.g. Debian, Windows]: Linux (QNAP)
 - Virtualization: [e.g. Docker, KVM, LXC] Docker
 - Clients: [Browser, Android, Fire Stick, etc.] N/A
 - Browser: [e.g. Firefox 72, Chrome 80, Safari 13] N/A
 - Jellyfin Version: [e.g. 10.4.3, nightly 20191231] 10.6.4
 - Playback: [Direct Play, Remux, Direct Stream, Transcode] N/A 
 - Installed Plugins: [e.g. none, Fanart, Anime, etc.]
 - Reverse Proxy: [e.g. none, nginx, apache, etc.] None
 - Base URL: [e.g. none, yes: /example]
 - Networking: [e.g. Host, Bridge/NAT] Same issue when switched to host (normally on bridge)
 - Storage: [e.g. local, NFS, cloud] NAS

**To Reproduce**

1. Start server and monitor log output

**Expected behavior**

_Seriously?! alright if you want this info.._

To not have the falure of the json lookup for plugins.

**Logs**

```
[16:00:14] [INF] [10] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing Update Plugins
[16:00:20] [ERR] [15] Emby.Server.Implementations.Updates.InstallationManager: An error occurred while accessing the plugin manifest: https://repo.jellyfin.org/releases/plugin/manifest-stable.json
,System.Net.Http.HttpRequestException: Resource temporarily unavailable
```

**Screenshots**

N/A - I have not seen **once** where a dev wants to see a screenshot of logs when text or a paste service would be preferred.
**Additional context**

Album art, meta, etc has no issue being downloaded for the content that I have - so not a http/https issue.

**Comment by crobibero** [comment]
I don’t see how an error code of “Temporarily Unavailable” is a bug.

**Comment by anthonylavado** [comment]
>N/A - I have not seen **once** where a dev wants to see a screenshot of logs when text or a paste service would be preferred.

It's a template. It has to apply to many situations for many different reasons. A reason for screenshots is explained on the line right above where you wrote this.
>If applicable, add screenshots to help explain your problem.

(Note this line is hidden in the publicly posted issue.)

**Comment by spannerman79** [comment]
“Temporarily Unavailable” **is** a bug, considing that I do not run the http server that has the URI of `https://repo.jellyfin.org/releases/plugin/manifest-stable.json`

How the hell can I control it hm @crobibero ??  My magic??  How innately foolish to make such a statement.

**Comment by joshuaboniface** [comment]
It's not a bug because one of a dozen reasons could cause it none of which are related to the code. Is your Internet connected? Is the server down for maintenance? Is there a routing loop on the Internet? Have you tried vising the URL in in your browser? Via `curl` from your CLI where you're running Jellyfin? Please try these troubleshooting steps.

In addition to the lack of detail, your tone is unacceptable. This is a volunteer project. We don't owe you anything. Help us help you and cut out the attitude.

**Comment by oddstr13** [comment]
A quick search seems to indicate that `Resource temporarily available` may indicate that you are having DNS issues.

https://stackoverflow.com/a/63174034/1035647

This almost certainly not a bug in Jellyfin, and most likely has to do with your (or your ISPs) network setup.
If this is on our end, then it would've at worst have been a temporary issue with our DNS provider.

You should troubleshoot this issue from your end, using tools such as nslookup/dig/host, ping/traceroute/mtr and just plain opening https://repo.jellyfin.org/releases/plugin/manifest-stable.json in your browser. If you cannot access that URL, then there is a networking issue somewhere between your computer and our server, most likely somewhere closer to your computer than our server, considering I'm not seeing any issues from my end.

This link should show you which mirror is getting selected for you, and a list of mirrors you can attempt to ping/traceroute to.
https://repo.jellyfin.org/releases/plugin/manifest-stable.json?mirrorlist
