### ISSUE TITLE
Blank Easy PIN doesn't work

### ISSUE THREAD

**Issue by 12nick12** [jellyfin/jellyfin#5413]
**Describe the bug**

When enabling easy pin code it doesn't work if you leave it blank. You first have to input a PIN then save then reset the PIN for a blank PIN to work. 

**System (please complete the following information):**
 - OS: [e.g. Debian, Windows]: Rasbpain
 - Virtualization: [e.g. Docker, KVM, LXC]: Hardware
 - Clients: [Browser, Android, Fire Stick, etc.]: WebGUI
 - Browser: [e.g. Firefox 72, Chrome 80, Safari 13]: Edge Chromium
 - Jellyfin Version: [e.g. 10.4.3, nightly 20191231]:  10.6.4 (From the repo)
 - Playback: [Direct Play, Remux, Direct Stream, Transcode] : Not playing media, just trying to log in
 - Installed Plugins: [e.g. none, Fanart, Anime, etc.]: None
 - Reverse Proxy: [e.g. none, nginx, apache, etc.]: This was direct and with NGiNX RP
 - Base URL: [e.g. none, yes: /example]: No
 - Networking: [e.g. Host, Bridge/NAT]: Direct
 - Storage: [e.g. local, NFS, cloud]: NFS

**To Reproduce**

1. Create user
2. Enable Easy PIN
3. Leave Easy PIN bank
4. Blank PIN/Passwd not work
5. Create PIN
6. Hit reset PIN
7. Leave it blank (there will be asterisk in the PIN box)
8. Hit save
9. Now it works as expected :-)

**Expected behavior**

**Logs**

**Screenshots**

**Additional context**

**Comment by random-human-being** [comment]
Same issue on Jellyfin 10.7.6 (Docker version, Libreelec host).
Tested with both Firefox and the WebOS browser.
Logging in with a blank "Easy PIN" doesn't work, but as OP said adding a generic one and resetting it works.
This has to be repeated for each account.
