### ISSUE TITLE
Black screen final 10.7.0

### ISSUE THREAD

**Issue by litris** [jellyfin/jellyfin#5425]
**Describe the bug**

**System (please complete the following information):**
 - OS: [Ubuntu 18.04 server]
 - Virtualization: [none]
 - Clients: [Browser, iOS app]
 - Browser: [Firefox, Safari]
 - Jellyfin Version: [stable 10.7.0]
 - Playback: [Direct Play] 
 - Installed Plugins: [none]
 - Reverse Proxy: [none]
 - Base URL: [none]
 - Networking: [host]
 - Storage: [NFS]

**To Reproduce**

**Expected behavior**

Updated to version 10.7.0 and both the black screen appears in iOS and Web.

I used the default option at Ubuntu server to keep config.json

**Logs**

**Screenshots**

Black Screen

![8180738B-60AF-43A2-9ABA-7826C174D23D](https://user-images.githubusercontent.com/2809283/110436957-1e41d980-80b5-11eb-95a0-7625dd3379b0.png)

**Additional context**

I open directly from Github because I just opened a report from the IOS app and it's not shown in the github.

If he shows up, then delete him.

Thank you.

**Comment by khannover** [comment]
Same on DietPi after upgrading today

**Comment by zfuller** [comment]
I had the same issue as reported when upgrading to the latest version (10.7.0) via the jellyfin repo from 10.6.4. At first I had this same issue as reported. When upgrading the jellyfin package first time around I selected dpkg No, to keep the current version of '/usr/share/jellyfin/web/config.json' the same. which resulted in jellyfin no longer loading/displaying a blank page.

On reinstallation of the latest version, I selected dpkg Yes to use the package maintainers version of '/usr/share/jellyfin/web/config.json' which fixed the issue of the blank screen for me.

There were a lot of changes in the config.json.

what i had in my config.json on 10.6.4
```json
{
    "multiserver": false
}
```

what was in config.json on 10.7.0
```json
{
  "includeCorsCredentials": false,
  "multiserver": false,
  "themes": [
    {
      "name": "Apple TV",
      "id": "appletv"
    }, {
      "name": "Blue Radiance",
      "id": "blueradiance"
...
    }, {
      "name": "WMC",
      "id": "wmc"
    }
  ],
  "servers": [],
  "plugins": [
    "playAccessValidation/plugin",
... 
    "chromecastPlayer/plugin"
  ]
}
```

Jellyfin did not log any errors for me and the process was running without any errors

**Comment by khannover** [comment]
> I had the same issue as reported when upgrading to the latest version (10.7.0) via the jellyfin repo from 10.6.4. When upgrading the jellyfin package first time around I selected dpkg No, to keep the current version of '/usr/share/jellyfin/web/config.json' the same. which resulted in jellyfin no longer loading/displaying a blank page.
> 
> On reinstallation of the latest version, I selected dpkg Yes to use the package maintainers version of '/usr/share/jellyfin/web/config.json' which fixed the issue of the blank screen for me.
> 
> There were a lot of changes in the config.json.
> 
> what i had in my config.json on 10.6.4
> 
> ```json
> {
>     "multiserver": false
> }
> ```
> 
> what was in config.json on 10.7.0
> 
> ```json
> {
>   "includeCorsCredentials": false,
>   "multiserver": false,
>   "themes": [
>     {
>       "name": "Apple TV",
>       "id": "appletv"
>     }, {
>       "name": "Blue Radiance",
>       "id": "blueradiance"
> ...
>     }, {
>       "name": "WMC",
>       "id": "wmc"
>     }
>   ],
>   "servers": [],
>   "plugins": [
>     "playAccessValidation/plugin",
> ... 
>     "chromecastPlayer/plugin"
>   ]
> }
> ```
> 
> Jellyfin did not log any errors for me and the process was running without any errors

Same on dietpi. I just added an empty plugins array to the config.json and it seemed to be working:

{
    "multiserver": false,
    "plugins": []
}

**Comment by dkanada** [comment]
@khannover since media playback on web is also handled with plugins, it will be broken until you at minimum add the plugins for the formats you want to consume.

**Comment by khannover** [comment]
> @khannover since media playback on web is also handled with plugins, it will be broken until you at minimum add the plugins for the formats you want to consume.

Yes i see. Can you post an example? Is there something like a default?

**Comment by ferferga** [comment]
@litris You can simply run ``sudo apt remove --purge jellyfin-web && sudo apt install --reinstall jellyfin-web``

**Comment by ferferga** [comment]
@litris That would never purge your library data, as you're doing it for the ``jellyfin-web`` package, not ``jellyfin-server``, so my command does indeed erase all the files **related to jellyfin-web** and reinstall them from scratch, doing indeed **the same thing as was proposed above: copy the config.json from this repo into the install**

In fact, I would assure that ``--purge`` on ``jellyfin-server`` wouldn't remove your library as well, only what's inside ``/etc/jellyfin``, the directory that's marked as the one that holds the configuration in the deb packages. At least that was the case for 10.4.X (when I had to run it in my instance) and only configuration (not library was erased).

We can't fix that in our side: It's the user responsibility to check properly the dialogs that are prompted during the package installations, they exist for a reason. That dialog should appear only if an user has modified the config.json file so conflicts can be fixed.

My config.json was never touched and it was upgraded properly, without dialogs.

**Comment by litris** [comment]
> @litris That would never purge your library data, as you're doing it for the `jellyfin-web` package, not `jellyfin-server`, so my command does indeed erase all the files **related to jellyfin-web** and reinstall them from scratch, doing indeed **the same thing as was proposed above: copy the config.json from this repo into the install**
> 
> In fact, I would assure that `--purge` on `jellyfin-server` wouldn't remove your library as well, only what's inside `/etc/jellyfin`, the directory that's marked as the one that holds the configuration in the deb packages. At least that was the case for 10.4.X (when I had to run it in my instance) and only configuration (not library was erased) so, if no changes in that front were made by @joshuaboniface, only real configuration files and not data would be purged for `jellyfin-server` as well.
> 
> We can't fix that in our side: It's the user responsibility to check properly the dialogs that are prompted during the package installations, they exist for a reason. That dialog should appear only if an user has modified the config.json file so conflicts can be fixed.
> 
> My config.json was never touched and it was upgraded properly, without dialogs.

Okay! thank you.

My config.json was never touched but by default the facility advises to leave the previous one.

I mean press enters.

It should be a new default config.json because the one who modifies config.json can do it after it's a minority.

The rest will stop working as I have happened to me and many in forums.

**Comment by thorian93** [comment]
Let me just add in addition to @litris point: When doing automated upgrades (I use Ansible), the default of that tool is to keep the local version I think. I am aware that that is my responsibility, but I did not touch the file either, so shouldn't the file be overwritten without questions?

**Comment by ferferga** [comment]
@thorian93 No, that depends on dpkg and we can't override their defaults. We also don't set up that prompt, is up to dpkg.

We're trying to fix this in web so the client just loads defaults if the file is invalid.

I haven't edited the file and I did not receive the prompt so, somehow, you edited it at some point (a simple open and save might have modified the line endings for you). 

Not at all people is reporting this error so definitely something happened in the systems of those users that received the prompt and don't recall editing the file.

**Comment by litris** [comment]
> @thorian93 No, that depends on dpkg and we can't override their defaults. We also don't set up that prompt, is up to dpkg.
> 
> We're trying to fix this in web so the client just loads defaults if the file is invalid.
> 
> I haven't edited the file and I did not receive the prompt so, somehow, you edited it at some point (a simple open and save might have modified the line endings for you).
> 
> Not at all people is reporting this error so definitely something happened in the systems of those users that received the prompt and don't recall editing the file.

Not here.

But I've set this server up in over 20 people and everyone has called me to fix it for you.

He thinks that the one who modifies the file is the one who should then choose the right option.

The one who does not change it by default should be the right one.

In this case, the change of config.json.

The one who modifies it knows and is the one who has to be careful.

It's just an opinion.

Ahh perfect with the solution in movies with 23.976xxx fps took a while, but you'll get it.

Thank you, I had already left it for impossible and I was almost erasing Jellyfin.

Because almost all the servers had all the movies in 23,xxx fps and they all used iOS to play them.

It was a long time without being able to watch movies and install everyone plex that I don't like anything. 😅

**Comment by thorian93** [comment]
> @thorian93 No, that depends on dpkg and we can't override their defaults. We also don't set up that prompt, is up to dpkg.
> 
> We're trying to fix this in web so the client just loads defaults if the file is invalid.
> 
> I haven't edited the file and I did not receive the prompt so, somehow, you edited it at some point (a simple open and save might have modified the line endings for you).
> 
> Not at all people is reporting this error so definitely something happened in the systems of those users that received the prompt and don't recall editing the file.

Well I sure see your point and of course packaging can be a challenging topic, I saw that in other projects. So no blaming from me at all.

To clarify my situation:

My `config.json` resides in `/usr/share/jellyfin/web/config.json`, which is unusual as it should be in `/etc/jellyfin/` I would think.
That is, why I am certain to never have touched that file. I would merely have copied it to `/etc/jellyfin/` which I never did.
Also I would assume that a file in `/usr/share/` is a system file and not to be altered by the user. Maybe the file locations can be improved? For example there the "system" file in `/usr/share/` and a "user" file in `/etc/jellyfin/` or similar. Am I making sense?

I don't want to get on anyone's nerves, I just want to make sure we are not acting on wrong or at least inaccurate presumptions.
