### ISSUE TITLE
OpenAPI specification not published for 10.7.0 and 10.7.0~rc4

### ISSUE THREAD

**Issue by nielsvanvelzen** [jellyfin/jellyfin#5426]
**Describe the bug**
The OpenAPI specification available at https://repo.jellyfin.org/releases/openapi/ was not released for the 4th release candidate and the stable build. Looking at Azure the unit tests seem to have failed causing the pipeline to halt.

https://dev.azure.com/jellyfin-project/jellyfin/_build/results?buildId=26576&view=logs&jobId=c13f50be-40fa-55ea-9864-e9bc7c81964b

I'd appreciate if @jellyfin/core can manually upload the spec (including rc4 for archival purposes).

**Comment by nielsvanvelzen** [comment]
10.7.0~rc4, 10.7.0 and 10.7.1 have been uploaded manually now. Keeping the issue open until 10.7.2 publishes correctly though.

**Comment by cvium** [comment]
10.7.2 was published correctly
