### ISSUE TITLE
Fresh installation now working.

### ISSUE THREAD

**Issue by Robpizza** [jellyfin/jellyfin#5429]
**Describe the bug**
I just installed ubuntu 20.04 and followed the installation tutorial of the wiki, but the webui installation gets stuck after clicking on next on the first page.

**System (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS
 - Virtualization: LXC
 - Clients: Browser
 - Browser: Chrome 88.0.4324.190
 - Jellyfin Version: 10.6.4
 - Playback: /
 - Installed Plugins: /
 - Reverse Proxy: /
 - Base URL: /
 - Networking: Bridge
 - Storage: local

**To Reproduce**
https://jellyfin.org/docs/general/administration/installing.html#ubuntu
I followed this, the webUI does load, AFTER I edited the system.xml to add the machine IP to the <LocalNetworkAdrresses> tag, because it binds to the TCP6 interface... even though this is disabled.

**Expected behavior**
Well, that I can proceed in the installation.

**Logs**

> [2021-03-09 09:23:39.490 +00:00] [INF] Jellyfin version: "10.6.4"
> [2021-03-09 09:23:39.506 +00:00] [INF] Environment Variables: ["[JELLYFIN_ARGS, $JELLYFIN_WEB_OPT $JELLYFIN_RESTART_OPT $JELLYFIN_FFMPEG_OPT $JELLYFIN_SERVICE_OPT $JELLYFIN_NOWEBAPP_OPT]", "[JELLYFIN_LOG_DIR,>
> [2021-03-09 09:23:39.508 +00:00] [INF] Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--webdir=/usr/share/jellyfin/web", "--restartpath=/usr/lib/jellyfin/restart.sh", "--ffmpeg=/usr/lib/jellyfin-ffmpeg/ff>
> [2021-03-09 09:23:39.509 +00:00] [INF] Operating system: "Linux"
> [2021-03-09 09:23:39.509 +00:00] [INF] Architecture: X64
> [2021-03-09 09:23:39.510 +00:00] [INF] 64-Bit Process: True
> [2021-03-09 09:23:39.510 +00:00] [INF] User Interactive: True
> [2021-03-09 09:23:39.510 +00:00] [INF] Processor count: 4
> [2021-03-09 09:23:39.510 +00:00] [INF] Program data path: "/var/lib/jellyfin"
> [2021-03-09 09:23:39.510 +00:00] [INF] Web resources path: "/usr/share/jellyfin/web"
> [2021-03-09 09:23:39.510 +00:00] [INF] Application directory: "/usr/lib/jellyfin/bin/"
> [2021-03-09 09:23:39.674 +00:00] [INF] Setting cache path: "/var/cache/jellyfin"
> [2021-03-09 09:23:39.681 +00:00] [INF] Loading assemblies
> [2021-03-09 09:23:40.972 +00:00] [INF] Kestrel listening on all interfaces
> [2021-03-09 09:23:41.063 +00:00] [INF] Running startup tasks
> [2021-03-09 09:23:41.071 +00:00] [INF] Daily trigger for "Extract Chapter Images" set to fire at 03/10/2021 02:00, which is 16:36:18.9283951 from now.
> [2021-03-09 09:23:41.136 +00:00] [INF] Found ffmpeg version "4.3.1"
> [2021-03-09 09:23:41.153 +00:00] [INF] Available "decoders": ["h264", "h264_qsv", "h264_cuvid", "hevc", "hevc_qsv", "hevc_cuvid", "mpeg2video", "mpeg2_qsv", "mpeg2_cuvid", "mpeg4", "mpeg4_cuvid", "msmpeg4", ">
> [2021-03-09 09:23:41.163 +00:00] [INF] Available "encoders": ["libx264", "h264_amf", "h264_nvenc", "h264_qsv", "h264_v4l2m2m", "h264_vaapi", "libx265", "hevc_amf", "hevc_nvenc", "hevc_qsv", "hevc_vaapi", "mpe>
> [2021-03-09 09:23:41.170 +00:00] [INF] Available hwaccel types: ["vdpau", "cuda", "vaapi", "qsv", "drm", "opencl"]
> [2021-03-09 09:23:41.171 +00:00] [INF] FFmpeg: SetByArgument: "/usr/lib/jellyfin-ffmpeg/ffmpeg"
> [2021-03-09 09:23:41.171 +00:00] [INF] ServerId: "bb5684510c274826b12ea5cfbc998e0e"
> [2021-03-09 09:23:41.394 +00:00] [INF] Registering publisher for "urn:schemas-upnp-org:device:MediaServer:1" on "192.168.200.89"
> [2021-03-09 09:23:41.408 +00:00] [INF] Executed all pre-startup entry points in 0:00:00.2277255
> [2021-03-09 09:23:41.408 +00:00] [INF] Core startup complete
> [2021-03-09 09:23:41.511 +00:00] [INF] Executed all post-startup entry points in 0:00:00.1032791
> [2021-03-09 09:23:41.512 +00:00] [INF] Startup complete 0:00:02.1602389
> [2021-03-09 09:23:44.105 +00:00] [INF] "StartupTrigger" fired for task: "Update Plugins"
> [2021-03-09 09:23:44.106 +00:00] [INF] Queueing task "PluginUpdateTask"
> [2021-03-09 09:23:44.109 +00:00] [INF] Executing "Update Plugins"
> [2021-03-09 09:23:44.750 +00:00] [INF] "Update Plugins" Completed after 0 minute(s) and 0 seconds
> [2021-03-09 09:23:45.000 +00:00] [INF] ExecuteQueuedTasks
> [2021-03-09 09:23:58.902 +00:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid user"
> [2021-03-09 09:24:07.855 +00:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid user"
> [2021-03-09 09:24:07.866 +00:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid user"

`

**Screenshots**
[Screenshot](https://imgur.com/a/xrBbbMl)

**Additional context**
This LXC container is running on a ProxmoxVE

**Comment by Robpizza** [comment]
UPDATE,

the jellyfin-server package got updated just a sec ago, but now it doesnt redirect to the installation wizard, luckely the url autocompleted. but this could be a future problem.

**Comment by BaronGreenback** [comment]
A fix for the IP6 bug has been submitted.
