### ISSUE TITLE
Find missing tags and replace images is deleting items

### ISSUE THREAD

**Issue by ferferga** [jellyfin/jellyfin#5430]
**Describe the bug**
Rfreshing images in a music library deletes the items in the library (*not in the filesystem*)

**System (please complete the following information):**
 - OS: Debian Buster
 - Clients: Web
 - Browser: Edge Chromium on Windows 10
 - Jellyfin Version: 10.7
 - Reverse Proxy: nginx

**To Reproduce**
1. Go to Dashboard > Libraries
2. Click on the '...' menus in a music library and select "Scan library".
3. Choose "Search missing tags" and tick the "Replace existing images checkbox"
4. You will start seeing less items in the library as they're being removed

**Expected behavior**
Images are replaced and nothing is removed

**Logs**
This is a sample message that appear for each item:
`` Removing item, Type: "Folder", Name: "The Weeknd", Path: "/home/ferferga/jellymusic/The Weeknd"``

**Additional context**
Scanning the library again recovers all the metadata (IsFavorite, playlists, etc) correctly, so it's not a major deal breaker either luckily :)

This is how the entity is stored in the database:

```
{"CollectionType":"music","PhysicalLocationsList":["/var/lib/jellyfin/root/default/M\u00FAsica","/home/ferferga/jellymusic"],"PhysicalFolderIds":["74bf7eb70292ccb780841d03f7bb09f9"],"IsRoot":false,"LinkedChildren":[],"DateLastSaved":"2021-03-09T09:53:25.6037785Z","RemoteTrailers":[],"IsHD":false,"IsShortcut":false,"Width":0,"Height":0,"ExtraIds":[],"SupportsExternalTransfer":false}
```

Attached the ``options.xml`` (renamed to .txt so GitHub takes it) file as well
[options.txt](https://github.com/jellyfin/jellyfin/files/6108076/options.txt)

**Comment by cvium** [comment]
Cannot reproduce.
