### ISSUE TITLE
Jellyfin not starting if wireguard server is running on the same machine

### ISSUE THREAD

**Issue by Jhyrachy** [jellyfin/jellyfin#5446]
**Describe the bug**
Jellyfin server does not start if the same machine has wireguard installed

**System (please complete the following information):**
 - OS: Arch
 - Virtualization: Docker (but also tried the pkg install)
 - Jellyfin Version: 10.7.1

**To Reproduce**

Install wireguard.  
Start jellyfin

**Expected behavior**
 jellyfin should start

**Logs**

from systemd logs:
Mar 09 01:14:18 vmi*.contaboserver.net dotnet[278]: Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'CommandLine, Version=2.8.0.0, Culture=neutral, PublicKeyToken=***'. Access is denied.
[logJellyfin.txt](https://github.com/jellyfin/jellyfin/files/6110306/logJellyfin.txt)

**Comment by BaronGreenback** [comment]
Have to ask, but has the user that JF runs under got access to the location of the assembly CommandLine ?

**Comment by Jhyrachy** [comment]
It should have.

Until yesterday everything worked fine.  
But then everything broke once wireguard was installed.

After that I tried removing it, reinstalling it from aur, running with docker, but it never worked again
