### ISSUE TITLE
After upgrading to 10.7.x via apt Jellyfin still shows previously installed version number, appears not to be upgrading sub-packages

### ISSUE THREAD

**Issue by r0bbie** [jellyfin/jellyfin#5448]
**Describe the bug**
I upgraded from Jellyfin 10.6.4 to 10.7.0 on Ubuntu earlier today. Running `apt info` confirms it seems to have successfully upgraded:

```Package: jellyfin-server
Version: 10.7.0-1
Priority: optional
Section: misc
Maintainer: Jellyfin Team <team@jellyfin.org>
Installed-Size: 131 MB
Depends: at, libsqlite3-0, libfontconfig1, libfreetype6, libssl1.1
Recommends: jellyfin-web
Breaks: jellyfin (<< 10.6.0)
Replaces: jellyfin (<< 10.6.0)
Homepage: https://jellyfin.org/
Download-Size: 37.9 MB
APT-Sources: https://repo.jellyfin.org/ubuntu focal/main amd64 Packages
Description: Jellyfin is the Free Software Media System.
```
Despite this, when I go to the Admin Dashboard, it still shows 10.6.4 as the installed version, which was the version I was upgrading from. I've manually restarted Jellyfin a couple times just in case something was being cached there, but no luck.

**System (please complete the following information):**
Jellyfin 10.7.0 upgraded from 10.6.4, on Ubuntu 20.04

**To Reproduce**
1. Be on Jellyfin 10.6.4 (in my case)
2. Upgrade Jellyfin via apt. Seems to successfully complete
3. Go to Admin Dashboard - still shows old version as installed

**Expected behavior**
Should show new version 10.7.0 in Dashboard

**Logs**
Had a quick look at the log and couldn't see any errors during the upgrade. If there are any logs which are helpful to provide though please let me know.

**Screenshots**
![image](https://user-images.githubusercontent.com/1804229/110515016-d300e880-80ff-11eb-9987-9e3f52445ca2.png)

**Edit**
As noted below, the issue appears to be that when upgrading to 10.7.x via `apt install jellyfin` as in the Jellyfin documentation, the sub-packages jellyfin-server, jellyfin-web, and jellyfin-ffmpeg are not upgraded. These do show as upgradeable however when you run `apt list --upgradable`, and manually upgrading the three packages individually seems to solve the issue.

**Comment by r0bbie** [comment]
This issue persists following upgrade to 10.7.1.

**Comment by JonEllis** [comment]
I see the same issue, and also the CLI agrees with the version in the admin dashboard:
```
$ jellyfin --version
Jellyfin.Server 10.6.4.0
```

10.7.0 introduced a new network config option for a reverse proxy IP address which I was planning to update, but this option does not appear in my admin panel under networking as I expected (small chance I'm looking in the wrong place of course).

This makes me wonder whether the apt packages for 10.7.0 and 10.7.1 are actually 10.6.4 for some reason?

**Comment by JonEllis** [comment]
Right, I've had a quick poke, and I believe that upgrading the meta-package `jellyfin` does not cause the upgrade of the sub-packages `jellyfin-server`, `jellyfin-web`, and `jellyfin-ffmpeg`.

They were correctly listed in the upgradable packages list for me.
```
apt list --upgradable
```

Once those sub-packages were upgraded, then I see the correct version in the web interface and CLI.
The new reverse proxy option also appeared in the network config.

**Comment by r0bbie** [comment]
Can confirm after manually upgrading the three sub-packages everything seems to be working smoothly / upgraded properly, and am now on 10.7.2.

Assume this issue should remain open however, presumably those subpackages should be upgraded automatically when upgrading jellyfin via apt, as seemed to happen in the past? Will rename the issue to more accurately reflect what the problem is.

**Comment by joshuaboniface** [comment]
OK, I see what's happening.

Seems like the metapackage isn't getting proper version tags in its depends lines:

```
joshua@jf1 ~ $ apt info jellyfin
Package: jellyfin
Version: 10.7.6-1
[...]
Depends: jellyfin-server, jellyfin-web, jellyfin-ffmpeg (>= 4.2.1-2)
[...]
```

So that's definitely a bug on our side.

What's curious, though, is that all 3 packages should be showing updates from the repo at the same time. Did `apt upgrade` not show `jellyfin-server` and `jellyfin-web` as upgradeable at the same time as `jellyfin`?

**Comment by apellegr06** [comment]
Hello,

I have the same issue, after upgrading the GUI still display version 10.6.4, and if I try again to install the version 10.7.0 👍 

sudo apt install jellyfin=10.7.7-1
Reading package lists... Done
Building dependency tree
Reading state information... Done
jellyfin is already the newest version (10.7.7-1).
0 upgraded, 0 newly installed, 0 to remove and 239 not upgraded.

Have you find a solution ?

**Comment by raqmudy** [comment]
hi same here

root@media /home/click# apt info jellyfin
Package: jellyfin
Version: 10.7.7-1
Priority: optional
Section: misc
Maintainer: Jellyfin Packaging Team <packaging@jellyfin.org>
Installed-Size: 9216 B
Depends: jellyfin-server, jellyfin-web, jellyfin-ffmpeg (>= 4.2.1-2)
Homepage: https://jellyfin.org
Download-Size: 2256 B
APT-Manual-Installed: yes
APT-Sources: https://repo.jellyfin.org/debian buster/main amd64 Packages
Description: Provides the Jellyfin Free Software Media System
 Provides the full Jellyfin experience, including both the server and web interface.

root@media /home/click# apt-get upgrade jellyfin-server jellyfin-web jellyfin-ffmpeg
Reading package lists... Done
Building dependency tree       
Reading state information... Done
jellyfin-ffmpeg is already the newest version (4.3.1-1-buster).
jellyfin-server is already the newest version (10.6.4-1).
jellyfin-web is already the newest version (10.6.4-1).
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@media /home/click# apt-get upgrade jellyfin                                    
Reading package lists... Done
Building dependency tree       
Reading state information... Done
jellyfin is already the newest version (10.7.7-1).
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@media /home/click# 


how I can upgrade and update to last version

regards

**Comment by joshuaboniface** [comment]
@raqmudy Please post the contents of your `/etc/apt/sources.list.d/jellyfin.list` and `/etc/os-release` files. The repo definitely has the correct data:

```
buster|main|amd64: jellyfin 10.7.7-1
buster|main|amd64: jellyfin-ffmpeg 4.3.2-1-buster
buster|main|amd64: jellyfin-server 10.7.7-1
buster|main|amd64: jellyfin-web 10.7.7-1
buster|main|amd64: libssl1.0.2 1.0.2q-2
buster|main|amd64: libssl1.0.2-dbgsym 1.0.2q-2
```

```
 new Debian package, version 2.0.
 size 2256 bytes: control archive=636 bytes.
     433 bytes,    12 lines      control              
     215 bytes,     3 lines      md5sums              
 Package: jellyfin
 Version: 10.7.7-1
 Architecture: all
 Maintainer: Jellyfin Packaging Team <packaging@jellyfin.org>
 Installed-Size: 9
 Depends: jellyfin-server, jellyfin-web, jellyfin-ffmpeg (>= 4.2.1-2)
 Section: misc
 Priority: optional
 Multi-Arch: foreign
 Homepage: https://jellyfin.org
 Description: Provides the Jellyfin Free Software Media System
  Provides the full Jellyfin experience, including both the server and web interface.
```

(note no version on the depends there)

**Comment by r0bbie** [comment]
Just to flag, this issue has reoccured for me on the latest Jellyfin 10.8.10-1 (upgrading from 10.8.9-1 on Ubuntu via apt)

Upgrading the sub-packages manually (jellyfin-server, jellyfin-web, and jellyfin-ffmpeg5) solved it for me as before.

**Comment by r0bbie** [comment]
Just another note this is continuing to happen as of 10.9.7! (all sub-packages need to be manually upgraded individually each time on Ubuntu)
