### ISSUE TITLE
[docker] Upgrade to 10.7.0 - Can't connect to server if not on LAN network

### ISSUE THREAD

**Issue by tuxrinku** [jellyfin/jellyfin#5449]
**Describe the bug**
Since the upgrade to 10.7.0 (from 10.6.4), I can't connect to the server from any network outside the LAN. For example, when I'm connected to home wifi, there's no problem accessing the server, but when switching to 4G it doesn't connect.

**System (please complete the following information):**
 - OS: Ubuntu
 - Virtualization: Docker
 - Clients: Browser, Android
 - Browser: Firefox 86
 - Jellyfin Version: 10.7.0
 - Reverse Proxy: nginx
 - Base URL: default

**Comment by kellcomnet2** [comment]
@tuxrinku is your NGINX also in docker?

**Comment by tuxrinku** [comment]
Yes it is, and I never had such problems before. I tried to put the docker IP of my nginx proxy container in the known proxies field, restarted jellyfin but still the same. I've been able to connect with 4G earlier(like 1 hour ago), but it stopped working again without changing anything, so I'm not sure it's related to proxy.

**Comment by kellcomnet2** [comment]
@tuxrinku It could be a red herring, but I have the following in my known proxies, 192.168.1.42, 172.18.0.6, 172.18.0.1
192.168.1.42 <- Actual host IP
172.18.0.6 <- NGINX docker IP
172.18.0.1 <- Jellyfin docker IP

The fact that some can connect and others can't leads me to rule out known proxies issue.... are they all using http/https or is it a mix?

**Comment by tuxrinku** [comment]
I tried to set the IPs like you did, but still can't connect using 4G.
The server is only accessible with HTTPS. I redirect HTTP to HTTPS.

**Comment by kellcomnet2** [comment]
@tuxrinku Ok, I'm tapping out that was the only thought I had based on my experiences.

**Comment by tuxrinku** [comment]
Thanks for your time. For now I guess I'll go back to 10.6.4 until a possible fix for this comes out.

**Comment by tuxrinku** [comment]
My god, I was so focalized on jellyfin that I forgot about my fail2ban container... And guess what, my multiple attempts on 4G got me banned myself... Now everything is fine... I guess I need some sleep
