### ISSUE TITLE
[10.7.0] Jellyfin web client not loading

### ISSUE THREAD

**Issue by Johnystar** [jellyfin/jellyfin#5453]
**Describe the bug**

After updating to the latest version of Jellyfin (10.7.0), the web UI doesn't load anymore. The only way I've been able to access Jellyfin at all was via the Jellyfin MPV Shim client. The UI doesn't load in Google Chrome, Firefox or in the Android client.

**System (please complete the following information):**
 - OS: DietPi (based on Raspbian)
 - Virtualization: no
 - Clients: Browser, Android
 - Browser: Chrome, Firefox (any)
 - Jellyfin Version: 10.7.0
 - Playback: n/a
 - Installed Plugins: Anime, AudioDB, MusicBrainz, OMDb
 - Reverse Proxy: nginx (all traffic is going through Cloudflare - might be relevant)
 - Base URL: none
 - Networking: Host (I think?)
 - Storage: local

**To Reproduce**

1. (system described above, upgraded from a working Jellyfin 10.6.4 configuration)
2. try accessing Jellyfin via a web browser or the Android client

**Expected behavior**

The Jellyfin Web client UI should show up

**Logs**

Couldn't find any relevant logs. (all log files seem empty accessed through any combination of ``sudo``, ``chmod`` and ``cat`` that I could think of)

**Screenshots**

![image](https://user-images.githubusercontent.com/29976879/110542276-24719d80-8129-11eb-8b06-aa8b07ce52d4.png)

**Additional context**

Can't think of any.

**Comment by crobibero** [comment]
See the following issues:
https://github.com/jellyfin/jellyfin-web/issues/2494
https://github.com/jellyfin/jellyfin-web/issues/2493
