### ISSUE TITLE
jellyfin:latest - Remote access - Whitelist not working

### ISSUE THREAD

**Issue by Shiwigy** [jellyfin/jellyfin#5459]
Hi,

After upgrading to the latest docker container of jellyfin/jellyfin:latest (10.7) whitelist IP-addresses no longer works.
When remote access is enabled and two IP-addresses is whitelisted, i still gain access from any public IP address that is not in the whitelist. I'm greated by the login page and can successfully login, expected behavior would be a page saying Forbidden like in the old jellyfin/jellyfin:10.6.4.

Im running this behind the docker container linuxserver/swag (nginx proxy).

**Comment by BaronGreenback** [comment]
Could you upload the network.xml settings file please?

**Comment by Shiwigy** [comment]
Attached network.xml, IP is obfuscated of course

`<?xml version="1.0" encoding="utf-8"?>
<NetworkConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <EnableUPnP>false</EnableUPnP>
  <PublicPort>8096</PublicPort>
  <UPnPCreateHttpPortMap>false</UPnPCreateHttpPortMap>
  <EnableIPV6>false</EnableIPV6>
  <EnableIPV4>true</EnableIPV4>
  <EnableSSDPTracing>false</EnableSSDPTracing>
  <UDPSendCount>2</UDPSendCount>
  <UDPSendDelay>100</UDPSendDelay>
  <IgnoreVirtualInterfaces>true</IgnoreVirtualInterfaces>
  <VirtualInterfaceNames>vEthernet*</VirtualInterfaceNames>
  <GatewayMonitorPeriod>60</GatewayMonitorPeriod>
  <TrustAllIP6Interfaces>false</TrustAllIP6Interfaces>
  <PublishedServerUriBySubnet />
  <AutoDiscoveryTracing>false</AutoDiscoveryTracing>
  <AutoDiscovery>true</AutoDiscovery>
  <PublicHttpsPort>8920</PublicHttpsPort>
  <HttpServerPortNumber>8096</HttpServerPortNumber>
  <HttpsPortNumber>8920</HttpsPortNumber>
  <EnableHttps>false</EnableHttps>
  <EnableRemoteAccess>true</EnableRemoteAccess>
  <BaseUrl />
  <LocalNetworkSubnets />
  <LocalNetworkAddresses />
  <RequireHttps>false</RequireHttps>
  <RemoteIPFilter>
    <string>185.xx.xxx.xx</string>
  </RemoteIPFilter>
  <IsRemoteIPFilterBlacklist>false</IsRemoteIPFilterBlacklist>
  <KnownProxies />
</NetworkConfiguration>
`

And this is me logged in from a completly diffrent ip.
is online from Chrome Android
IP address: 79.xx.xxx.xx

In 10.6.4 im greated by the Forbidden page as expected.

**Comment by BaronGreenback** [comment]
Looks to be a logic flip in the IsRemoteIPFilterBlacklist setting.

Just published fix: https://github.com/jellyfin/jellyfin/pull/5495
