### ISSUE TITLE
Unable to delete Library/Plugins on unstable

### ISSUE THREAD

**Issue by ikomhoog** [jellyfin/jellyfin#5463]
**Describe the bug**
I was using unstable and wanted to remove a library and it wouldn't be removed.
Also tried it with plugins and they also didnt have any effect.
Disabling the plugins did work.

There is no logging whatsoever when trying a delete.

I couldnt reproduce it in vscode but can reliably reproduce it in docker, even on a clean container

On the current 10.7.0 release there are no problems

**System (please complete the following information):**
 - OS: UnRaid
 - Virtualization: Docker
 - Clients: Browser, Android App
 - Browser: Chrome
 - Jellyfin Version: unstable (20210310.2 but also noticed it earlier)
 - Playback: -
 - Installed Plugins: TMDb Box Sets, TVDb, Opensubtitles (which i tried to delete)
 - Reverse Proxy: nginx
 - Base URL: jellyfin.schalkwijk.dev
 - Networking: bridge
 - Storage: local

**To Reproduce**
1. Update container to 20210310.2
2. try to delete a library/plugin
3. notice there is no feedback or library/plugin removed

**Comment by BaronGreenback** [comment]
Due to the way the system is implemented - any change in the status of a server side plugin requires the application to be restarted.

**Comment by ikomhoog** [comment]
That is correct, that works on 10.7.0 but not on the unstable branch.
On 10.7.0 when you remove a plugin its status changed to "restart" and after a restart it's gone.
On unstable the status stays active, and after a restart the plugin is still active.

The library deletion should not require a server restart, and it works correctly on 10.7.0, but also doesn't do anything on unstable
