### ISSUE TITLE
DLNA remuxes into a .mov container

### ISSUE THREAD

**Issue by svemonix** [jellyfin/jellyfin#5465]
**Describe the bug**
I have all transcoding deactivated but for some reason most of my media accessed by VLC (other clients have the same issue) via DLNA end up being remuxed into a .mov container. The worst part is that the remuxed media doesn't seem to be playable (i.e. playback doesn't starts).

**System (please complete the following information):**
 - Virtualization: Docker - official Jellyfin image
 - Clients: VLC through DLNA (same issue from my TV, PS4, etc.)
 - Jellyfin Version: 10.7.0 (stable but also RC 3 and 4 maybe earlier too, 10.6.4 was fine)
 - Installed Plugins: only the default ones
 - Base URL: none
 - Networking: host
 - Storage: local

**To Reproduce**

1. Open VLC
2. Play a standard h264+AAC stereo .mp4
3. Jellyfin starts remuxing into a .mov
4. Playback never starts

**Expected behavior**
The file should direct play.

**Logs**
[log_20210310.log](https://github.com/jellyfin/jellyfin/files/6115640/log_20210310.log)
[FFmpeg.Remux-2021-03-10_12-48-12_651d47f12de374212955bfeb2f30c484_02ecf656.log](https://github.com/jellyfin/jellyfin/files/6115642/FFmpeg.Remux-2021-03-10_12-48-12_651d47f12de374212955bfeb2f30c484_02ecf656.log)

**Comment by BaronGreenback** [comment]
Couple of patches were merged today to do with dlna and profile detection.

I'm currenty looking at the dlna sub-system - as i'm getting exactly the same issue.

**Comment by seaeagle1** [comment]
Very similar problem here. So far I figured out that it shows similar behaviour for specific device profiles (although it doesn't always use .mov to remux).

As you can see here, the log complains about not-listed codecs for the second movie (also gives a TranscodeReason in the URL), but the first one appears like is should DirectPlay, except it doesn't.
`[2021-03-10 19:07:27.186 +00:00] [INF] [9] Emby.Dlna.ContentDirectory.ContentDirectoryService: Profile: "VLC", Path: "\\192.168.0.4\FilmShare\Films\40 Days and 40 Nights\40 Days and 40 Nights.avi", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2021-03-10 19:07:27.189 +00:00] [INF] [9] Emby.Dlna.ContentDirectory.ContentDirectoryService: Profile: "VLC", Path: "\\192.168.0.4\FilmShare\Films\After the Sunset\After the Sunset (2004).mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2021-03-10 19:07:27.190 +00:00] [INF] [9] Emby.Dlna.ContentDirectory.ContentDirectoryService: Profile: "VLC", No video direct play profiles found for "\\192.168.0.4\FilmShare\Films\After the Sunset\After the Sunset (2004).mkv" with codec "h264"`

`[2021-03-10 19:09:18.573 +00:00] [INF] [6] Jellyfin.Api.Helpers.TranscodingJobHelper: /usr/lib/jellyfin-ffmpeg/ffmpeg -fflags +genpts -f avi -i file:"/mnt/Film/Films/40 Days and 40 Nights/40 Days and 40 Nights.avi" -map 0:0 -map 0:1 -map -0:s -codec:v:0 copy -mpegts_m2ts_mode 1 -copyts -avoid_negative_ts disabled -start_at_zero -vsync -1 -map_metadata -1 -map_chapters -1 -threads 0 -codec:a:0 copy -y "/var/lib/jellyfin/transcodes/b347957a20a5247fe9c326f37a735809.avi"
[2021-03-10 19:09:20.401 +00:00] [WRN] [18] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://192.168.0.5:8096/videos/54a555e1-3494-38d3-9b24-1de5ed48ae29/stream.avi?DeviceProfileId=9f649eb005ee72f27ff01580901f2c2b&DeviceId=test&MediaSourceId=54a555e1349438d39b241de5ed48ae29&AudioStreamIndex=1&Tag=716b867ca057fa4c41964b013f44d216&dlnaheaders=true" to "192.168.0.102" in 0:00:01.8310093 with Status Code 200`

**Comment by BaronGreenback** [comment]
It looks like it may be fixed by today's PR. 

Fix 1 was that profileId wasn't being included in the Url for the dlna request (PlayTo). (It might be the same for the dlna server - i've yet to check.)

Fix 2: was that the logic for profile detection for streams included code that was impossible to reach. This has been corrected.

I'm currently working on testing the dlna plugins (10.X release) and as as such are debugging this entire process.

**Comment by patrickmerz** [comment]
I have the same problem (transcoding w/o need), but I could not even set dlna logging, better said, switching dlna logging on does not produce more log output.
System: Win 10, Jellyfin 10.7.0 portable edition
