### ISSUE TITLE
Library Page Size Resets with Every Login

### ISSUE THREAD

**Issue by m-weathers** [jellyfin/jellyfin#5469]
Edit: Changing settings in Settings -> Display (like library page size) and then clicking save doesn't actually save them unless you manually click the log out button. If you change library page size and then later exit the tab, the settings won't save.

 - OS: Whatever Linux is running in Docker jellyfin/jellyfin
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Microsoft Edge
 - Jellyfin Version: 10.7.0
 - Playback:
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: none
 - Networking: Host
 - Storage: local

1. Log in.
2. Settings -> Display -> Page size set to 0 and save.
3. Exit tab without logging out and log back in, page size will be reset to 100.

Expected behavior is that display settings will be saved between sessions for the same user after the save button is pressed.

**Comment by gemstonevirus** [comment]
As this is true for all display settings, title of this issue should be updated.
