### ISSUE TITLE
Sort by Release Date Is Sorting by Name

### ISSUE THREAD

**Issue by malcolm-weathers** [jellyfin/jellyfin#5470]
All other sort methods appear to be working, but sort by release date is sorting by name instead.

 - OS: Whatever Linux is in Docker jellyfin/jellyfin
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Microsoft Edge
 - Jellyfin Version: 10.7.0
 - Playback:  
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: none
 - Networking: Host
 - Storage: local

1. Go to Libraries -> Movies.
2. Sort By -> Release Date
3. Sorting is alphabetical.

Expected behavior is that sorting by release date will sort by release date and not alphabetically. In 10.6.x this behaved as expected, so it appears to be a new issue in 10.7.

**Comment by elvis0288** [comment]
it will not be completely true at least in my testing (i was about to post this issue) so if i sort by name i got this:
![image](https://user-images.githubusercontent.com/7027367/110812036-2d748300-827f-11eb-933e-6617577947eb.png)

but if i sort by release date i got this:
![Uploading image.png…]()

but yes it is totally broken.. i usually watch movies from oldest to newest and now i cannot do that

**Comment by cvium** [comment]
Works for me. Please verify that the Release Date is correct. The year that is shown below the poster is not the Release Date.
