### ISSUE TITLE
Screenplay v1.5.8 WebOS client cannot log into Jellyfin 10.7.0

### ISSUE THREAD

**Issue by g-a-c** [jellyfin/jellyfin#5484]
**Describe the bug**

I'm an LG WebOS TV owner, and due to the lack of native WebOS app availability, I have been using Screenplay successfully for several versions. Since my Docker Jellyfin instance automatically updated to 10.7.0 I can no longer authenticate with Screenplay because:
```
[22:59:38] [DBG] [11] Jellyfin.Api.Auth.CustomAuthenticationHandler: Error authenticating with CustomAuthenticationHandler
MediaBrowser.Controller.Authentication.AuthenticationException: Request does not contain a token.
   at Emby.Server.Implementations.HttpServer.Security.AuthService.Authenticate(HttpRequest request)
   at Jellyfin.Api.Auth.CustomAuthenticationHandler.HandleAuthenticateAsync()
[22:59:38] [DBG] [11] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was not authenticated.
```
I took a look at the authentication code with my limited knowledge of C# and a can-do attitude, and thought I could fix this by using my reverse proxy (Traefik) to inject an `X-Emby-Token` header on all requests, but this did not work.

I have had to revert to Jellyfin 10.6.4 to restore my playback functionality as this is the only usable option (I have a separate bug to file about the 10.7.0 web UI on the WebOS browser)

**System (please complete the following information):**
 - OS: Debian 10/buster
 - Virtualization: Docker
 - Clients: LG WebOS, Screenplay v1.5.8
 - Browser: n/a
 - Jellyfin Version: 10.7.0
 - Playback: n/a
 - Installed Plugins: none
 - Reverse Proxy: Traefik
 - Base URL: none
 - Networking: host access to Traefik, "internal" reverse proxy leg over default Docker NAT network
 - Storage: local

**To Reproduce**

1. install Screenplay from the LG App Store on a WebOS TV
2. open Screenplay application
3. enter Jellyfin hostname
4. when presented with the user list, select a user and enter the correct password
5. see error on screen, and "does not contain a token" error in debug-level logs

**Expected behavior**

To be logged in successfully as the chosen user

**Logs**

```
[22:59:38] [DBG] [11] Jellyfin.Api.Auth.CustomAuthenticationHandler: Error authenticating with CustomAuthenticationHandler
MediaBrowser.Controller.Authentication.AuthenticationException: Request does not contain a token.
   at Emby.Server.Implementations.HttpServer.Security.AuthService.Authenticate(HttpRequest request)
   at Jellyfin.Api.Auth.CustomAuthenticationHandler.HandleAuthenticateAsync()
[22:59:38] [DBG] [11] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was not authenticated.
```

**Screenshots**

**Additional context**

**Comment by ikomhoog** [comment]
I had the same issue but with just chrome on windows,
I was still logged in when updating.
After logging out, clearing my cache and logging back in I didn't receive the error anymore.

**Comment by crobibero** [comment]
Screenplay is an Emby client. It was by chance that it worked up until now

**Comment by g-a-c** [comment]
> Screenplay is an Emby client. It was by chance that it worked up until now

Yeah, I get that. But unfortunately there is no first-party Jellyfin WebOS app yet, so it's the only way I'm able to access my Jellyfin library from my WebOS television (DLNA has never worked properly for me as I see no sources presenting themselves on the TV). Given that there's no app yet provided by the Jellyfin team, it's a little annoying that there was no consideration for keeping the Screenplay workaround alive, but no matter, I will just have to stay on Jellyfin 10.6.4 until your app is complete. Thanks for the response.
