### ISSUE TITLE
OpenAPI version spec should have valid characters

### ISSUE THREAD

**Issue by ferferga** [jellyfin/jellyfin#5488]
The schema we're using ``vX`` is not compatible with [npm](https://docs.npmjs.com/about-semantic-versioning) or [Maven](https://bintray.com/jellyfin/jellyfin-apiclient-java/jellyfin-apiclient-java) and we're using the server version (in the case of **npm**) and custom versioning (in the case  of Maven)

We should have a ``1.X.Y`` versioning schema, [as defined in npm's semantic versioning](https://docs.npmjs.com/about-semantic-versioning), which is compatible everywhere and use the ``2.X.Y`` for the *future* definition (after #5121 is merged)

The change to the ``1.X.Y`` schema should be backported, so we can solve the current mess of versioning in our api clients and, ideally, all apiclients, regardless their language, should use the same versioning.

**Comment by crobibero** [comment]
After sleeping on it I think having the version be tied to server version would be better as we would be less likely to not bump the version when API changes are made.
We could have the “v2” of the spec be v11.0.0.1 or something when we move ahead there

**Comment by ferferga** [comment]
@crobibero Sounds good!
