### ISSUE TITLE
Can't log in after upgrade to 10.7.0

### ISSUE THREAD

**Issue by brianjmurrell** [jellyfin/jellyfin#5489]
**Describe the bug**
Can't log in after upgrade to 10.7.0.

**System (please complete the following information):**
 - OS: Fedora 33
 - Virtualization: None
 - Clients: Browser
 - Browser: Chrome 88
 - Jellyfin Version: 10.7.0
 - Playback: N/A
 - Installed Plugins: Unknown
 - Reverse Proxy: None
 - Base URL: none
 - Networking: Native
 - Storage: Local

**To Reproduce**

1. Go to main page
2. Try to log in

**Expected behavior**
Should get logged in.

**Logs**
```
[2021-03-11 09:05:03.378 -05:00] [ERR] [102] Jellyfin.Server.Implementations.Users.UserManager: Error authenticating with provider "Default"
MediaBrowser.Controller.Authentication.AuthenticationException: Specified user does not exist.
   at Jellyfin.Server.Implementations.Users.DefaultAuthenticationProvider.Authenticate(String username, String password, User resolvedUser)
   at Jellyfin.Server.Implementations.Users.UserManager.AuthenticateWithProvider(IAuthenticationProvider provider, String username, String password, User resolvedUser)
[2021-03-11 09:05:03.378 -05:00] [INF] [102] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for "Brian" has been denied (IP: "10.75.22.1").
[2021-03-11 09:05:03.384 -05:00] [ERR] [102] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request: "Invalid username or password entered". URL "POST" "/Users/authenticatebyname".
```

**Additional context**
The user does exist however:

```
$ sudo sqlite3 /var/lib/jellyfin/data/jellyfin.db
SQLite version 3.34.1 2021-01-20 14:10:07
Enter ".help" for usage hints.
sqlite> select * from Users where Username='Brian';
7F6961EB-4584-41A0-8D26-AA673417A20C||Jellyfin.Server.Implementations.Users.DefaultAuthenticationProvider|0|0||0|0|1|1|1|8|0|2019-11-06 12:22:56.858011|2019-10-16 20:34:11.6792887||0||0||Jellyfin.Server.Implementations.Users.DefaultPasswordResetProvider|1|1|1|0|0||0|0|Brian
sqlite> 
```

**Comment by WhatSupQuebec** [comment]
do you have this screen when you try to connect to your jellyfin ?
![image](https://user-images.githubusercontent.com/71474060/110862228-3cfac880-828d-11eb-91fc-ab4ecde8a098.png)

**Comment by brianjmurrell** [comment]
No.  That's just a completely black screen.

**Comment by Resurrection2981** [comment]
> 当您尝试连接至果冻时，您有此屏幕吗？
> ![图像](https://user-images.githubusercontent.com/71474060/110862228-3cfac880-828d-11eb-91fc-ab4ecde8a098.png)

![image](https://user-images.githubusercontent.com/45873933/110917871-60894600-8355-11eb-8506-8c3c5f67f0a5.png)
Same for me.

**Comment by Resurrection2981** [comment]
Solved https://github.com/jellyfin/jellyfin-web/issues/2493

**Comment by brianjmurrell** [comment]
No.  Not solved.  @Resurrection2981, @WhatSupQuebec.

Your issues are very clearly not the same as this issue that I opened.  Please don't hijack my issue for you your unrelated issue.

**Comment by brianjmurrell** [comment]
The following process seems to have resolved the issue:

```
# systemctl stop jellyfin.service
# mv /var/lib/jellyfin/data/jellyfin.db{,.bak}
# systemctl start jellyfin.service
[ Go to JF URL, get asked to log in even though there are no Users in the JF DB now]
# systemctl stop jellyfin.service
# mv /var/lib/jellyfin/data/jellyfin.db{.bak,}
# systemctl start jellyfin.service
```

I was then presented with the users and could log in as one.
