### ISSUE TITLE
Unable to delete users in Unstable branch

### ISSUE THREAD

**Issue by Sidefix** [jellyfin/jellyfin#5496]
**Describe the bug**
Attempting to delete any user from the dashboard in the unstable branch does nothing. There is no log output when the button is pressed, it appears as though the button is completely non-functional.

**System (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chromium Edge 90
 - Jellyfin Version: unstable 20210310.6
 - Playback: n/a
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: /web/index.html#!/userprofiles.html

**To Reproduce**
1. Go to Dashboard
2. Click on Users
3. Click on ellipses on any given user
4. Select Delete
5. Confirm deletion

**Expected behavior**
The user should be deleted

**Logs**
No errors, no log output on this operation

**Comment by ikomhoog** [comment]
I also noticed this for libraries and plugins in https://github.com/jellyfin/jellyfin/issues/5463

**Comment by Sidefix** [comment]
Above pull request fixed the issue. No longer occurring in unstable 20210411.17.
