### ISSUE TITLE
jellyfin very good but More need subdirectory

### ISSUE THREAD

**Issue by tiantang1995124** [jellyfin/jellyfin#5502]
We need subdirectory classification In movies and TV, there are more categories to show on TV, such as thrillers, epics, happy ，India, South Korea, Japan and so on. All the media are displayed on the home page, which is very messy， thank for jellyfin team

**Comment by tiantang1995124** [comment]
For example, the home page has two mixed contents: Yanni and Lady Gaga. Rename the collection to music. Although Yanni and Lady Gaga can be added to the collection to display Yanni and Lady Gaga in the music collection, the interface can still display a Yanni and Lady Gaga that has been added to the collection. I don't need to display the content that has been added to the collection in a non collection

**Comment by nielsvanvelzen** [comment]
Feature requests should be posted to https://features.jellyfin.org
