### ISSUE TITLE
Typo in 10.7 changelog

### ISSUE THREAD

**Issue by strugee** [jellyfin/jellyfin#5516]
**Describe the bug**

The 10.7 changelog contains this text:

> New QuickConnect functionality for (disabled by default)

Seems like there's supposed to be a noun after "for".

(I'm omitting the rest of the issue template since it's obviously not relevant.)

**Comment by strugee** [comment]
Still exists; /cc @joshuaboniface to hopefully get this resolved since it's so trivial

**Comment by strugee** [comment]
Still present 😕: https://github.com/jellyfin/jellyfin/releases/tag/v10.7.0

**Comment by Bond-009** [comment]
It's not a big deal
