### ISSUE TITLE
Jellyfin doesn't stream files if they are symbolic links

### ISSUE THREAD

**Issue by pixelomer** [jellyfin/jellyfin#5521]
**Bug description**
When a video file (or any other type of media) is placed directly into the media folder, it can be played just fine. However, if a symbolic link is placed instead of the file itself, the video is still recognized by Jellyfin but it becomes unplayable. This issue is not reproducible in Jellyfin 10.6.4 (stable).

**System:**
 - OS: Raspbian Lite
   - `uname -a`: `Linux 5.10.17-v7l+ #1403 SMP Mon Feb 22 11:33:35 GMT 2021 armv7l GNU/Linux`
 - Virtualization: Docker version 20.10.5, build 55c4c88
 - Clients: Infuse for iOS, jellyfin-mpv-shim
 - Browser: Firefox 86.0.1 on macOS
 - Jellyfin Version: 10.7.0 (stable)
   - Docker image: `jellyfin/jellyfin`
   - Tag: `10.7.0`
 - Playback: Direct Play
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: /
 - Networking: `--net=host`
 - Storage: Physically attached SSD mounted in the container using `-v`

**To Reproduce**

1. Put a video file in the media folder (eg. `/media/MyVideo.mkv`)
2. Create a symbolic link to this video file from somewhere else (eg. A TV show directory)
```
mkdir -p /media/shows/MyAmazingShow/Season\ 01
cd /media/shows/MyAmazingShow/Season\ 01
ln -s ../../../MyVideo.mkv S01E01.mkv
```
3. Try playing this video using a client
4. Get either no response or an error

**Expected behavior**
Jellyfin should be able to stream a media file regardless of whether the media folder contains the file itself or a symbolic link to it.

**Logs**
The server does not log anything about this issue, even with debug level logging. The logs below are from `jellyfin-mpv-desktop`.
```
2021-03-13 23:01:40,600 [   DEBUG] media: Using direct url.
2021-03-13 23:01:40,620 [   ERROR] mpv: mkv: Invalid EBML length at position 137
2021-03-13 23:01:40,620 [   ERROR] mpv: mkv: Invalid EBML length at position 139
2021-03-13 23:01:40,620 [ WARNING] mpv: mkv: Unexpected end of file (no clusters found)
2021-03-13 23:01:40,620 [ WARNING] mpv: mkv: mkv metadata beyond end of file - incomplete file?
2021-03-13 23:01:40,620 [   ERROR] mpv: cplayer: No video or audio streams selected.
2021-03-13 23:01:40,621 [    INFO] mpv: cplayer: 
2021-03-13 23:02:10,601 [   ERROR] player: Timeout when waiting for media duration. Stopping playback!
```

**Additional context**  
My media files are stored in a single separate folder rather then directly in the media folders for various reasons. My media folders are full of symbolic links to that folder. This setup has worked just fine in 10.6.4 but it no longer works in 10.7.0 because of this issue.

**Workaround**
Mounting the media folder somewhere else using `bindfs` with the option `resolve-symlinks` and using the mount in Jellyfin seems to work.

**Comment by valmar** [comment]
I am also affected. A workaround is to use hard links, but this is not always possible

**Comment by cvium** [comment]
I think another workaround is to symlink directories instead of files.

**Comment by pixelomer** [comment]
As I've already said in the issue description, another workaround is using `bindfs`. It's the best workaround in my opinion since it doesn't require making modifications to the current media folder.

**Comment by jrb0001** [comment]
reflinks (cp --reflink) are another workaround.

Requirements/limitations:
- Link and target must be on the same filesystem.
- Must be supported by the filesystem.
- Link behaves like a fully independent file, just without using any extra storage initially. Changes aren't propagated after creation.

Advantages:
- Better performance than `bindfs` because it is inside the kernel.
- Doesn't need ownership or write access to the target (hardlinks do if sysctl fs.protected_hardlinks=1).
- Works with files (unlike the directory symlink workaround).
