### ISSUE TITLE
Jellyfin doesn’t detect drive mounted to the device

### ISSUE THREAD

**Issue by 54601** [jellyfin/jellyfin#5523]
**Describe the bug**
I’ve mounted a smb shared folder as ‘Z:\’ in my system. However, in jellyfin only ‘C:\’ and ‘Network’ showed up. When chooses ‘Network’, nothing shows up. I have set the network I connected to as ‘family’, as well as enabled discover on every type of network. And I can browse Z:\ in my file manager. So I think this may be a bug or a setting problem from jellyfin.

**System (please complete the following information):**
 - OS: Windows 10
 - Virtualization: No
 - Clients: Browser
 - Browser: Edge
 - Jellyfin Version: 10.4.3
 - Playback: NULL 
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: what’s that?
 - Networking: what’s that?
 - Storage: SMB

**To Reproduce**

As mentioned above

**Expected behavior**

I imagine I can use my NAS as media database, without the need to download everything on my computer.

**Logs**
I’m currently re-installing jellyfin, I will paste the Logs if the problem repeats.

**Comment by 54601** [comment]
My jellyfin version is 10.7.0, sorry about the mistake

**Comment by 54601** [comment]
I am stupid, I find out that I can type in the smb link in the upper blank instead of the lower one says shared network links.

**Comment by OceanDu** [comment]
> I am stupid, I find out that I can type in the smb link in the upper blank instead of the lower one says shared network links.

Same problem as you, but I don’t understand your solution, can you describe it in detail?
