### ISSUE TITLE
Streaming to Chromecast through Android app doesn't work, Chromecast doesn't show up at all

### ISSUE THREAD

**Issue by fighuass** [jellyfin/jellyfin#5526]
**Describe the bug**

Ever since I started using Jellyfin (10.6.4) Chromecast casting has never worked. There's no error, no indications in logs, it simply doesn't show up at all (casting from the Android app). Still present in 10.7.0.

**System (please complete the following information):**
 - OS: Ubuntu 20.04.1 (where the Jellyfin server is located)
 - Virtualization: None.
 - Clients: I use the Android client from F-Droid on my tablet to cast to my 2nd gen Chromecast.
 - Browser: Not applicable.
 - Jellyfin Version: 10.7.0
 - Playback: Not applicable.
 - Installed Plugins: None.
 - Reverse Proxy: None.
 - Base URL: Not sure.
 - Networking: My Ubuntu PC is connected to the internet by ethernet cable.
 - Storage: Local, library is stored on secondary HDD.

**To Reproduce**

1. Open Android Jellyfin app.
2. Open any media.
3. Tap cast button.
4. Look for Chromecast. Doesn't show up in my case, only "my device".

**Expected behavior**

I expect my Chromecast to show up after tapping the cast button, so that I can cast the media to it through Jellyfin. In Plex this does work.

**Logs**

This one is from back when I used 10.6.4 but the principle is the same: https://cryptpad.fr/file/#/2/file/7j9iDplk+4BkHEqqMgD-onL7/

(The device on 192.168.178.21 is my tablet)

**Screenshots**

![Screenshot_20210314-105435_Jellyfin](https://user-images.githubusercontent.com/28998263/111064393-ba038900-84ab-11eb-8328-426788c75b3f.jpg)

(Mijn apparaat means my device)

**Comment by jfranki** [comment]
In my case, my Libreelec running Kodi with Jellyfin (jellyfin-kodi 0.7.0) won't appear either. I used to be able to pick a movie/episode from my Android phone, bacause it usually is more convenient and faster, and launch it in the TV. I THINK it was with 10.6.2.

**Comment by DHandspikerWade** [comment]
You mentioned you installed the app via F-Droid, try the Google Play version. If I remember correctly Chromecast requires a Google specific library that isn't shipped in the FDroid version

**Comment by jfranki** [comment]
I use the official one, and with a reverse proxy and HTTPS.

**Comment by DoubleAJ** [comment]
I have the same problem, however it only appeared when upgrading to 10.7.0. With the previous version the cast feature was working just fine.
I tried by connecting via:
- Web client (on Firefox, Chrome and Chromium)
- Android client app

I have a Chromecast and a Chromecast Ultra. Neither show up in the cast menu. I only see "My device" when I am in the web client, and I see "My Device" + "Firefox - Jellyfin web" when I am in the Android app.

> Also noticed you don't have a reverse proxy. Make sure you're using HTTPS. Chromecast requires a secure connection. Plex works around it by sending it through one of their servers, which Jellyfin can't/won't do.

Is this (HTTPS) a very recent requirement? I had no such problem before upgrading to 10.7.0.

**Comment by fighuass** [comment]
Just tried the GPlay version without HTTPS, didn't work.

I suppose I'll have to figure out how to enable HTTPS.

**Comment by eyJhb** [comment]
@fighuass HTTPS is required for the new version, so that has to be enabled somehow.
Also it cannot be a self signed certificate, as the Chromecast will most likely not play from that.

Any reason for the issue to stay open? :)

**Comment by srcrist** [comment]
Closing this issue as it does not reference a reproducible Jellyfin bug. Please visit our support communities on the forums or the Matrix/Discord server for assistance with troubleshooting playback issues.
