### ISSUE TITLE
Different movies missidentified as different versions of same movie

### ISSUE THREAD

**Issue by carlosrllodra** [jellyfin/jellyfin#5528]
**Describe the bug**

Movies with matching file name beginnings are missidentified as different movie versions, instead of as different movies.
These file names *do not follow* the naming convention explained in the documentation, that is, they are not named `movie - whatever` (with space-hypen-space separator, as documented here: https://jellyfin.org/docs/general/server/media/movies.html )

As an example, if I have 4 files in the same subdirectory:

- American_Pie__xxx_yyy.avi
- American_Pie_2__xxx_yyy.avi
- American_Pie_3__A_subtitle__xxx_yyy.avi
- American_Pie_4__Subtitle__HHH_xxx_yyy.mkv

Then all of then are incorrectly identified as different versions of the same movie, instead of different movies.

I'm not sure, since I don't use jellyfin everyday, but I would bet this happened after updating to 10.7

**System (please complete the following information):**
 - OS: Ubuntu 20.10
 - Virtualization: no
 - Clients: browser
 - Browser: Firefox 86
 - Jellyfin Version: 10.7.0
 - Playback: N/A 
 - Installed Plugins: AudioDB, Cover Art Archive, MusicBrainz, OMDb, TMDB Box Sets
 - Reverse Proxy: none
 - Base URL: none
 - Networking: not virtualized
 - Storage: local

**To Reproduce**

1. Add some files named as above.
2. Let jellyfin discover them, or rescan the library
3. Go to movie library
4. They are misidentified as 3 versions of the same movie instead of 3 different movies.

**Expected behavior**

Files named similarly should not be identified as same-movie-versions *when they do not follow* the documented naming convention.

**Logs**

**Screenshots**

![imagen](https://user-images.githubusercontent.com/59733246/111066580-01941000-84c0-11eb-8632-c56f28c517df.png)

**Additional context**

**Comment by crobibero** [comment]
What is the full path for these movies?

**Comment by carlosrllodra** [comment]
They are all in the same subdirectory under movie library root.
Following the same example, their path would be: `.../Comedy/American_Pie/`

The last directory matches the beginning of all file names.

**Comment by rderensy** [comment]
As documented in the [article you linked](https://jellyfin.org/docs/general/server/media/movies.html) you should create 4 directories, one for each movie.

**Comment by cvium** [comment]
We made some fixes for multi-version detection in 10.7, which may have affected your setup. As your naming scheme isn't supported I'm closing this.

**Comment by carlosrllodra** [comment]
Well, my naming scheme does not match what is documented: I am *not* using the `' - '` separator required for multi-version detection, so it shouldn't apply versioning (or on the other hand, documentation should be fixed).

Anyway, it would be nice to have some means to manually fix these incorrect multi-versioning...

**Comment by cvium** [comment]
`_` was re-added as a separator in 10.7 due to some old unit tests.

I'm going to revert that part because I think it's a excessive. That said, when your naming scheme doesn't match the documentation you have to expect some weirdness at times.

**Comment by carlosrllodra** [comment]
Thanks, @cvium
