### ISSUE TITLE
build.sh fails on Fedora because dpkg is missing

### ISSUE THREAD

**Issue by heylix** [jellyfin/jellyfin#5529]
Building current master fails on Fedora.

```
$ ./build.sh -t native -p linux.amd64
which: no dpkg in (/usr/lib64/ccache:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/heylix/.dotnet/tools:/home/heylix/.local/bin:/home/heylix/bin)
Cross-building is not supported for native builds, use 'docker' builds on amd64 for cross-building.
```

Same with the fedora target.

**Comment by Harnish** [comment]
I am building a patch like this.  Can someone with arm64 and armhf tell me what "uname -m" outputs?

` do_build_native() {
-    if [[ ! -f $( which dpkg ) || $( dpkg --print-architecture | head -1 ) != "${PLATFORM##*.}" ]]; then
+    if [[ $( uname -m | head -1 ) != "${PLATFORM##*.}" ]]; then
         echo "Cross-building is not supported for native builds, use 'docker' builds on amd64 for cross-building."
         exit 1
     fi
@@ -43,7 +43,7 @@ do_build_native() {
 }

 do_build_docker() {
-    if [[ -f $( which dpkg ) && $( dpkg --print-architecture | head -1 ) != "amd64" ]]; then
+    if [[ $( uname -m | head -1 ) != "x86_64" ]]; then
         echo "Docker-based builds only support amd64-based cross-building; use a 'native' build instead."
         exit 1
     fi`
