### ISSUE TITLE
Support binding to socket

### ISSUE THREAD

**Issue by plexxman** [jellyfin/jellyfin#553]
This is a low priority but nice option for those like me who use a reverse proxy like Nginx. Reducing a little bit the TCP overhead by proxy passing to an unix socket instead of a TCP one is cool! I'm not a developer but found this interesting article about the subject:

https://www.lloydkinsella.net/2018/03/12/using-net-core-kestrel-with-nginx-and-unix-sockets/

**Comment by wtayl0r** [comment]
Could this work with docker? surely you'd need to mount a unix socket which I don't think is currently possible

**Comment by aferpa94** [comment]
Of course it would work, in fact, I had mariadb dockerized and connected via unix socket with a nextcloud container. You just mount the path of the socket as a normal storage mount. Unix sockets are files.

**Comment by JustAMan** [comment]
Yet another point of moving to Kestrel it seems...
