### ISSUE TITLE
Jellyfin webclient doesn't load after updating to 10.7.0

### ISSUE THREAD

**Issue by Arghh** [jellyfin/jellyfin#5530]
**Describe the bug**

**System (please complete the following information):**
 - OS: dietpi (rasperrypi 4)
 - Virtualization: none
 - Clients: browser
 - Browser: chrome, firefox
 - Jellyfin Version: 10.7

**To Reproduce**
Open Jellyfins Client in Browser.
This Expection happens while loading plugins:
```
main.3309837d9db1402ea3a1.bundle.js:2 returning instance from getOrAddApiClient
main.3309837d9db1402ea3a1.bundle.js:2 defining core routes
main.3309837d9db1402ea3a1.bundle.js:2 Begin getAvailableServers
main.3309837d9db1402ea3a1.bundle.js:2 loading installed plugins
main.3309837d9db1402ea3a1.bundle.js:2 e
main.3309837d9db1402ea3a1.bundle.js:2 Uncaught (in promise) TypeError: Cannot read property 'map' of undefined
    at main.3309837d9db1402ea3a1.bundle.js:2
(anonymous) @ main.3309837d9db1402ea3a1.bundle.js:2
Promise.then (async)
(anonymous) @ main.3309837d9db1402ea3a1.bundle.js:2
(anonymous) @ main.3309837d9db1402ea3a1.bundle.js:2
Promise.then (async)
(anonymous) @ main.3309837d9db1402ea3a1.bundle.js:2
Promise.then (async)
(anonymous) @ main.3309837d9db1402ea3a1.bundle.js:2
(anonymous) @ main.3309837d9db1402ea3a1.bundle.js:2
(anonymous) @ main.3309837d9db1402ea3a1.bundle.js:2
```

**Screenshots**
The exepction gets thrown on this location. E is undefined.
![2021-03-14 17_11_03-Window](https://user-images.githubusercontent.com/9199258/111075465-5481bd80-84e8-11eb-9978-e320614c5ce5.png)

the location /var/lib/jellyfin/plugins/ is empty. I had plugins installed before the update. Altho I am not sure in want folder the plugins are stored on dietpi.

I had the following plugins installed:
audioDB, Email Notification, MusicBrainz, OMDb, Open Subtitles, Playback Report, Reports, TheTVDB

Can you help?

**Comment by FFAxKenny** [comment]
Same problem with me:

OS: debian buster
Virtualization: none
Clients: browser
Browser: chrome, firefox
Jellyfin Version: 10.7

**Comment by crobibero** [comment]
This looks like a cache issue, can you please retry in private / incognito mode?

**Comment by nielsvanvelzen** [comment]
Almost certain this is jellyfin/jellyfin-web#2493

**Comment by Arghh** [comment]
I didn't get asked if I wanted to keep the original config.json but after the installation it showed:
![2021-03-14 19_06_56-Window](https://user-images.githubusercontent.com/9199258/111079095-bb0ed780-84f8-11eb-93d9-454aded516e5.png)

it says config.json was created and the old config will be saved.

but before and after the install the /usr/share/jellyfin/web/config.json my has one entry:
{
    "multiserver": false
}
nothing else.

should I replace it with the https://github.com/jellyfin/jellyfin-web/blob/master/src/config.json ?

Thanks

**Comment by nielsvanvelzen** [comment]
Replacing it or adding the missing properties should fix it.

**Comment by Arghh** [comment]
that did fix the issue. ty @nielsvanvelzen for your help.
