### ISSUE TITLE
Grouping Broken in 10.7

### ISSUE THREAD

**Issue by alwe2710** [jellyfin/jellyfin#5537]
**Describe the bug**
Multiple Versions get combined in 10.6, but not in 10.7

**System (please complete the following information):**
 - OS: Windows
 - Virtualization: none
 - Clients: Browser
 - Browser: Chrome
 - Jellyfin Version: 10.7.0
 - Installed Plugins: Fanart, Playback Reporting, Reports, Skin Manager, Theme Songs
 - Reverse Proxy: none
 - Base URL: none
 - Storage: local

**To Reproduce**

1. Name Movies with " - " in same folder, like in the documentation
2. Scan Library

**Expected behavior**
Movies Should be displayed as one entry

**Logs**
There is no real error to display

**Screenshots**
![Screenshot 2021-03-15 120437](https://user-images.githubusercontent.com/17453692/111144078-df18fa00-8586-11eb-9e7b-5645ab9326fb.png)

**Additional context**
I tried to do a library scan in 10.6 and then open 10.7. As long as 10.7 didn't rescan the library. The movies persisted in the combined form. After a scan they get split up again.
Jellyfin-web 10.7.0 with Jellyfin-server 10.6.4 also works as expected

**Comment by cvium** [comment]
Most likely fixed by https://github.com/jellyfin/jellyfin/pull/5461
