### ISSUE TITLE
server crash on connection reset in android client

### ISSUE THREAD

**Issue by dkanada** [jellyfin/jellyfin#554]
I believe this crash was introduced after 10.0.0 because it only happens on my dev build and not my production server, which is still on an older version. This will be a blocking issue for any release of the android client. I posted the error code [here](https://pastebin.com/f3umd8ny) if it helps at all. Still not sure what action causes it on the client side, but I feel like the server shouldn't crash from a client action regardless.

**Comment by anthonylavado** [comment]
@dkanada When you get a chance, let me know if you still think this is a concern.
