### ISSUE TITLE
Very low framerate with tone mapping enabled

### ISSUE THREAD

**Issue by conkydong** [jellyfin/jellyfin#5546]
**Problem**
I recently upgraded to 1.7.0 and tried to enable tone mapping. Unfortunately with enabled tone mapping 4K HEVC HDR10 videos are not really playing as fast they could with my Nvidia Quadro P2000. The framerate is extremly low (about 4 to 6 fps).

Hardware acceleration with NVENC and OpenCL is enabled and working. 

**Media Info of the file**
[https://pastebin.com/tw0bDNnn](https://pastebin.com/tw0bDNnn)

**Logs**
[nvidia-smi](https://pastebin.com/JrjXutVT)
[log](https://pastebin.com/sn1C7u40)
[clinfo](https://pastebin.com/yZ244pjM)
[ffmpeg-debug](https://pastebin.com/SUJKjc76)

**FFmpeg Logs**
https://pastebin.com/hXSrL7Gj

**Server System:**
- Board: J5005-ITX (1.5 GHz)
- RAM: 32 GB
- GPU: Nvidia Quadro P2000 (5 GB) with NVENC (Driver version: 460.39) and OpenCL installed
- STORAGE: 2x 8 GB WD Red in Raid 0, OS on SSD (in USB case), SanDisk Extreme PRO USB 3.1 as transcoding cache
- OS: OpenMediavault 5.6.2-1 (Usul)    
- Kernel: Linux 5.10.0-0.bpo.3-amd64
- Network: 1 Gbit/s cabled
- Jellyfin version: Latest - 1.7.0 (docker)
 
**Client System**

- Device: PC with AMD Ryzen 2700x, 32 GB RAM, AMD RX 6800 XT
- OS: Windows 10
- Client: Jellyfin Web
- Browser: Firefox 86.0.1 (64Bit)

**Comment by nyanmisaka** [comment]
I think the PCIe 2.0 x1 slot has caused a heavy overhead for P2000.

**Comment by cvium** [comment]
PCIe 2.0 x1 is limited to 500 MB/s, but shouldn't that be enough?

**Comment by conkydong** [comment]
> 
> 
> I think the PCIe 2.0 x1 slot has caused a heavy overhead for P2000.

Would a riser work then?

**Comment by nyanmisaka** [comment]
I think you can use QSV and VPP tonemapping instead. You can expect to get 30fps+ on 4k videos. We don't have a native `tonemap_cuda` filter so the memory copy through PCIe link can not be avoided.

**Comment by conkydong** [comment]
I just recently bought the P2000.
Also I just seem to can't get QSV to work.

**Comment by nyanmisaka** [comment]
> PCIe 2.0 x1 is limited to 500 MB/s, but shouldn't that be enough?

AFAIK we need at least PCIe 3.0x8 to get decent performance.

**Comment by nyanmisaka** [comment]
> I just recently bought the P2000.
> Also I just seem to can't get QSV to work.

Please use the JF 10.7 image from linuxserverio and install the lastest Intel driver inside it by following https://dgpu-docs.intel.com/installation-guides/ubuntu/ubuntu-focal.html

**Comment by conkydong** [comment]
> 
> 
> > I just recently bought the P2000.
> > Also I just seem to can't get QSV to work.
> 
> Please use the JF 10.7 image from linuxserverio and install the lastest Intel driver inside it by following https://dgpu-docs.intel.com/installation-guides/ubuntu/ubuntu-focal.html

I'm using the official JF image, how do i migrate my existing database to the linuxserver.io image?

**Comment by nyanmisaka** [comment]
> I'm using the official JF image, how do i migrate my existing database to the linuxserver.io image?

https://github.com/linuxserver/docker-jellyfin#parameters

```

-v /config | Jellyfin data storage location. This can grow very large, 50gb+ is likely for a large collection.
```

**Comment by conkydong** [comment]
> 
> 
> > I'm using the official JF image, how do i migrate my existing database to the linuxserver.io image?
> 
> https://github.com/linuxserver/docker-jellyfin#parameters
> 
> ```
> 
> -v /config | Jellyfin data storage location. This can grow very large, 50gb+ is likely for a large collection.
> ```

Tried that, not working. If I use the linuxserver.io image, the setup wizard shows up.

**Comment by cvium** [comment]
Closing as it looks like it's a bandwidth issue. If you continue to have issues with QSV, it might be easier to join our [matrix channels](https://jellyfin.org/contact/) and ask for help.
