### ISSUE TITLE
RE: Jellyfin Disappears after New Tab

### ISSUE THREAD

**Issue by wolverine79936** [jellyfin/jellyfin#5548]
It doesn't seem to matter which browser I use to open Jellyfin OR a new tab in, but if I open a new tab, Jellyfin just goes to a black screen and stops playing. I have to refresh the screen.

I tried opening a new tab in Edge - black screen. I tried open Jelly in Edge and then opening a tab in Chrome - black screen. So, hopefully someone has some idea of what is going on here. I just don't know of anywhere else to ask about this. Sorry if this is the wrong place, but it is also a bug.

**Comment by cvium** [comment]
I can't reproduce it. Do you have sufficient RAM?
