### ISSUE TITLE
Jellyfin has problems importing playlist because file importer is case sensitive 

### ISSUE THREAD

**Issue by the-nothingman** [jellyfin/jellyfin#5549]
**Describe the bug**
I'm not sure if this is a feature request or a bug report but Jellyfin has problems importing playlist from other programs on windows system. On windows files and file paths are not case sensitive and exported playlist (in my case from music player/organizer Musicbee) usually ignore capitals when exporting to m3u8 files. The issue comes when Jellyfin imports these playlist they are missing songs because it can't see there's no difference between :

F:\Music\CHELSEA WOLFE\Anhedonia\- CHELSEA WOLFE - Anhedonia (Feat. Emma Ruth Rundle).flac
F:\Music\Chelsea Wolfe\Anhedonia\- CHELSEA WOLFE - Anhedonia (Feat. Emma Ruth Rundle).flac

F:\Music\Two Minutes To Late Night\Wrecking Ball\- Two Minutes to Late Night -  Wrecking Ball  (With Mutoid Man + Mlny Parsonz).flac
F:\Music\Two Minutes to Late Night\Wrecking Ball\- Two Minutes to Late Night -  Wrecking Ball  (With Mutoid Man + Mlny Parsonz).flac

F:\Music\Cryovile\Cryovile Songs and Covers\- Elena Siegman - The One (Cryovile Cover).flac
F:\Music\cryovile\Cryovile Songs and Covers\- Elena Siegman - The One (Cryovile Cover).flac

**System (please complete the following information):**
 - OS: [Windows]
 - Jellyfin Version: [e.g. 10.7.0,]
 - Storage: [local]

**To Reproduce**

1. Import any m3u8 file with mismatching capitalizations even when file spelling and paths are the same

**Additional context**
I'm not sure if this is a problem related to other file systems but I think there should be at least an option to disable case sensitive matching of file names/paths

**Comment by BaronGreenback** [comment]
https://www.howtogeek.com/354220/how-to-enable-case-sensitive-folders-on-windows-10/ ???

**Comment by the-nothingman** [comment]
I've looked over that article and its not an easy fix the, the file structure change has to be done on a per directory basis (cause it doesn't alter subfolders) which for me is changing and double checking about 4700 folders

**Comment by cvium** [comment]
The problem is the database. The path in the playlist is compared to the Path column in library.db and that is inherently case sensitive.
