### ISSUE TITLE
Nvidia Transcode, No Device Available

### ISSUE THREAD

**Issue by waddoo123** [jellyfin/jellyfin#5552]
**Describe the bug**
Having set the docker parameters for the --runtime-nvidia, nvidia GPU's ID, and parameters, I am unable to transcode using the GTX 1660. The logs are citing a "no device available for decoder".

**System (please complete the following information):**
 - OS: Linux/Unraid
 - Virtualization: Docker
 - Clients: Browser, Android, iOS
 - Browser: Firefox 72, Chrome OS
 - Jellyfin Version: 10.7
 - Playback: Transcode
 - Installed Plugins: none.
 - Reverse Proxy: nginx
 - Base URL: local for now. 
 - Networking: Bridge
 - Storage: Unraid NFS
 
**To Reproduce**

1. Setup JellyFin docker per instructions
2. Select 4k HEVC SDR or 4K HEVC HDR video to transcode
3. View ffmpeg logs and observe error. 

**Expected behavior**
The ffmpeg to show transcoding behavior. Activity listed in the nvidia-smi however it is empty. 

**Logs**
The 4K HEVC SDR movie transcode log has the following:

```
[matroska,webm @ 0x55ec830e1180] Could not find codec parameters for stream 4 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options

[AVHWDeviceContext @ 0x55ec837f1800] cu->cuInit(0) failed -> CUDA_ERROR_UNKNOWN: unknown error Device creation failed: -1313558101.
[hevc @ 0x55ec83325180] No device available for decoder: device type cuda needed for codec hevc. Stream mapping:
Stream #0:0 -> #0:0 (hevc (native) -> h264 (h264_nvenc))
Stream #0:1 -> #0:1 (copy)
Device setup failed for decoder on input stream #0:0 : Unknown error occurred
```

The 4K HEVC HDR Movie transcode log as the following:

```
[AVHWDeviceContext @ 0x5625c1e2e880] cu->cuInit(0) failed -> CUDA_ERROR_UNKNOWN: unknown error Device creation failed: -1313558101.
[hevc @ 0x5625c1e2ff40] No device available for decoder: device type cuda needed for codec hevc. Stream mapping:
Stream #0:0 -> #0:0 (hevc (native) -> h264 (h264_nvenc))
Stream #0:1 -> #0:1 (eac3 (native) -> aac (native))
Device setup failed for decoder on input stream #0:0 : Unknown error occurred

Transcode of 1080p HEVC SDR
ffmpeg version 4.3.1-Jellyfin Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-gpl --enable-version3 --enable-static --enable-libfontconfig --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --arch=amd64 --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-vdpau --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvenc --enable-nvdec --enable-ffnvcodec
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
...
[AVHWDeviceContext @ 0x56049d85cb00] cu->cuInit(0) failed -> CUDA_ERROR_UNKNOWN: unknown error
Device creation failed: -1313558101.
[hevc @ 0x56049d86cb80] No device available for decoder: device type cuda needed for codec hevc.
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (native) -> h264 (h264_nvenc))
  Stream #0:1 -> #0:1 (aac (native) -> aac (native))
Device setup failed for decoder on input stream #0:0 : Unknown error occurred
```

**Screenshots**
![Nvidia Settings](https://user-images.githubusercontent.com/80661527/111248952-e8cb4d80-85d8-11eb-9293-1c62c1016b9c.JPG)

**Additional context**
My docker...

```
root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='jellyfin' --net='bridge' -e TZ="America/Chicago" -e HOST_OS="Unraid" -e 'NVIDIA_VISIBLE_DEVICES'='GPU-201c0321-0f64-c185-4e78-ded96ed40231' -e 'PUID'='99' -e 'PGID'='100' -p '8096:8096/tcp' -p '8920:8920/tcp' -p '1900:1900/udp' -v '/mnt/user/Entertainment/Movies/':'/movies':'rw' -v '/mnt/user/Entertainment/TV Shows/':'/tv':'rw' -v '/mnt/user/Entertainment/Music/':'/music':'rw' -v '/mnt/user/appdata/jellyfin':'/config':'rw' --runtime=nvidia 
```

![Nvidia-si](https://user-images.githubusercontent.com/80661527/111249198-524b5c00-85d9-11eb-805b-01a2bfac8a06.JPG)

Please help with any additional troubleshooting steps I may have missed. I would like to get this resolved!

**Comment by ikomhoog** [comment]
I have almost the same buti have driver capabilities added: 
-e 'NVIDIA_DRIVER_CAPABILITIES'='all'
or for UnRaid UI style
![image](https://user-images.githubusercontent.com/9083045/111322406-30011f00-8669-11eb-9a92-af5d5823b8c1.png)

**Comment by waddoo123** [comment]
> I have almost the same buti have driver capabilities added:
> -e 'NVIDIA_DRIVER_CAPABILITIES'='all'
> or for UnRaid UI style
> ![image](https://user-images.githubusercontent.com/9083045/111322406-30011f00-8669-11eb-9a92-af5d5823b8c1.png)

If you look under additional parameters there already is this setting in place. At least there was in the docker app I grabbed on Unraid.

**Comment by ikomhoog** [comment]
>If you look under additional parameters there already is this setting in place. At least there was in the docker app I grabbed on Unraid.

That's why I find it weird that it isn't in your executed docker string you posted:

>Additional context
My docker...
>
```
root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='jellyfin' --net='bridge' -e TZ="America/Chicago" -e HOST_OS="Unraid" -e 'NVIDIA_VISIBLE_DEVICES'='GPU-201c0321-0f64-c185-4e78-ded96ed40231' -e 'PUID'='99' -e 'PGID'='100' -p '8096:8096/tcp' -p '8920:8920/tcp' -p '1900:1900/udp' -v '/mnt/user/Entertainment/Movies/':'/movies':'rw' -v '/mnt/user/Entertainment/TV Shows/':'/tv':'rw' -v '/mnt/user/Entertainment/Music/':'/music':'rw' -v '/mnt/user/appdata/jellyfin':'/config':'rw' --runtime=nvidia 
```

 please make sure you get it in there, when I do it it appears right after the "NVIDIA_VISIBLE_DEVICES"

**Comment by waddoo123** [comment]
Leaving a note for those that may struggle with the same issue I did, another reboot after the nvidia driver install is what made the difference for me.
