### ISSUE TITLE
Jellyfin 10.7 crashes immediately with Failed to create CoreCLR, HRESULT: 0x8007000E

### ISSUE THREAD

**Issue by uumas** [jellyfin/jellyfin#5554]
**Describe the bug**
When trying to run jellyfin 10.7 it immediately crashes with the error `Failed to create CoreCLR, HRESULT: 0x8007000E`. This happens even when running a simple `jellyfin --version`. I suspect this is triggered by a hardened kernel (grsec) as I'm trying to run this on a shared hosting provider but there's nothing relevant in the kernel logs. Jellyfin 10.6 works fine so something must have changed with 10.7.

**System (please complete the following information):**
 - OS: Debian buster x86_64
 - Jellyfin Version: 10.7.0
 - Installed Plugins: none

**To Reproduce**
1. Run jellyfin --version

**Logs**
```
uumas@lakka ~/jellyfin> jellyfin-server_10.6.4/jellyfin --version
Jellyfin.Server 10.6.4.0
uumas@lakka ~/jellyfin> jellyfin-server_10.7.0/jellyfin  --version
Failed to create CoreCLR, HRESULT: 0x8007000E
```

**Comment by uumas** [comment]
This also occurs with 10.7 rc1 so the regression happened between 10.6.4 and 10.7rc1

**Comment by crobibero** [comment]
Almost countless changes happened between 10.6 and 10.7, so that doesn’t really help us. If there are no additional logs I’m not sure how we can help, but my gut is telling me that this might be a dotnet bug, not a Jellyfin bug.

**Comment by uumas** [comment]
[Here](https://p.kapsi.fi/?4694833932cbcec4#CJ35yjTVGv8jLkxevVLpkXCK2xDe9uu58bxWBQ4HWmgR)'s an strace, maybe that could help. Unfortunately it is really verbose :-/

**Comment by crobibero** [comment]
I see this in the strace
```
mmap(NULL, 77309419520, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = -1 ENOMEM (Cannot allocate memory)
```

It looks like your system is running out of RAM during startup

**Comment by uumas** [comment]
:thinking: that doesn't seem reasonable. There's more than 100G of ram available and the per-user virtual memory limit is 64G, a simple `jellyfin --version` shouldn't come close to exhausting that. I've also tried it on 3 systems with the same grsec kernel and all fail.

**Comment by crobibero** [comment]
Here's an issue for the same error code
https://github.com/dotnet/runtime/issues/13027

Here's an issue for dotnet5 on grsec
https://github.com/dotnet/runtime/issues/46462

To me this doesn't look like a Jellyfin bug, but a dotnet bug.

**Comment by uumas** [comment]
Alright, the virtual memory limit is the problem after all. Jellyfin wants to reserve 78G(!) of vmem which is more than the maximum of 64G allowed. I still wouldn't call that expected behaviour though.
