### ISSUE TITLE
CORs Support

### ISSUE THREAD

**Issue by qazero** [jellyfin/jellyfin#557]
Could you please implement CORs support for strm files?

**Comment by JustAMan** [comment]
@qazero for ignorant people like me, what exactly is "CORs support"?

**Comment by 65001** [comment]
It looks like Cross Origin Resource Support according to a quick google search.

**Comment by qazero** [comment]
Correct, CORs stands for Cross Origin Resource Support. This comes in very handy when dealing with strm files where you need to pass certain parameters to the strm source server where the video is being fetched in order to authenticate. This is a requirement to get google drive transcoded videos to play via strm.

**Comment by ddurdle** [comment]
I'd like to help with this.

I believe it has to be implemented at the client app level.  For KODI, they allow plugins/etc to communicate headers that need to be communicated along with the URL by allowing developers to supply a | in the url.  Everything after | is considered a header to be added to the URL request.  When I looked at the inner workings of Plex, they are doing the same for the purpose of relaying their Plex Tokens from the Plex central server to the Plex hosted media server.

The goal here would be, whenever a url is interpreted from the jellyfin server to the client, the client app should watch for any | and treat all data following the | to be sent in the http header of the url request.

This will allow enabling use of streaming services that require authentication headers.
