### ISSUE TITLE
Fedora install fails

### ISSUE THREAD

**Issue by davesargrad** [jellyfin/jellyfin#5572]
Hi. 

I am trying to follow [these ](https://jellyfin.org/docs/general/administration/installing.html#fedora)instructions.

The instructions dont provide a sample that includes a proper RPM link.

Rather the instructions say: "sudo dnf install (link to version jellyfin server you want to install)"

The fact is the link that I want to use is the one that will work, and its not clear what that should be!

The instructions do link to a [repository ](https://jellyfin.org/downloads/#fedora)that I [navigated ](https://repo.jellyfin.org/releases/server/fedora/stable/)to find  some possible fedora links.

I've tried this link: https://repo.jellyfin.org/releases/server/fedora/stable/server/jellyfin-10.6.4-1.fc31.x86_64.rpm

I'm assuming that I need a different link.

I get the following error:
![image](https://user-images.githubusercontent.com/48793689/111808414-5bbf1780-88aa-11eb-84ad-af61d2710d88.png)

Can someone please tell me what the proper command is for the latest stable release on fedora.

I do think that the documentation page should also provide a more complete example.

Thanks.

**Comment by crobibero** [comment]
Here’s the list of stable fedora builds.
https://repo.jellyfin.org/releases/server/fedora/stable/

Nobody on the team uses Fedora, so if you want better documentation feel free to make a PR with suggested changes.

**Comment by davesargrad** [comment]
Ok.. It looks like I needed the following:

```
sudo dnf install https://repo.jellyfin.org/releases/server/fedora/stable/server/jellyfin-server-10.6.4-1.fc31.x86_64.rpm

sudo dnf install https://repo.jellyfin.org/releases/server/fedora/versions/stable/web/10.6.4/jellyfin-web-10.6.4-1.fc31.noarch.rpm

sudo dnf install https://repo.jellyfin.org/releases/server/fedora/stable/server/jellyfin-10.6.4-1.fc31.x86_64.rpm
```

**Comment by davesargrad** [comment]
I think I understand the first two links.. what is the third one?

**Comment by davesargrad** [comment]
@crobibero Thanks for your response!! Great to know that there is support. Do you think that the 10.6.4-1 version I've used should be ok on fedora? I could use a ubuntu server if that is what you are more used to.. Right now I have a fedora VM and would prefer to stick with that if I can.

**Comment by davesargrad** [comment]
![image](https://user-images.githubusercontent.com/48793689/111811758-c4f45a00-88ad-11eb-9292-1f973221e776.png)

**Comment by davesargrad** [comment]
Quite painless thus far on fedora.. 

![image](https://user-images.githubusercontent.com/48793689/111811999-0553d800-88ae-11eb-9a8c-4687b7be95e8.png)

Excited to use jellyfin!

**Comment by crobibero** [comment]
I could be wrong but I think the `jellyfin` package depends on `jellyfin-server` and `jellyfin-web`, but that might require a proper Fedora repository

**Comment by davesargrad** [comment]
Yes .. it did depend on them.. I guess my question should have been clearer.. Why do I need the jellyfin package (what does it do)? I'd think the server and the web element would be everything (server/client).

**Comment by crobibero** [comment]
This blog post will hopefully give you the information you’re looking for: https://jellyfin.org/posts/packaging-updates/

**Comment by davesargrad** [comment]
Thanks. I'll close this issue. One last question. I have 3 proper videos in my media folder... yet jellyfin  only seems to show one of them. It actually showed another, but then i added one and it only shows that one now.

![image](https://user-images.githubusercontent.com/48793689/111815359-f2430700-88b1-11eb-961a-c283908424bc.png)

I'm sure this is a simple config thing.. any idea what i should look at?

**Comment by crobibero** [comment]
Based on the docs that should work, so I’m not sure what it’s doing 
https://jellyfin.org/docs/general/server/media/movies.html

**Comment by davesargrad** [comment]
One other question I have .. and I hope then I'll be all good. I dont want to use the jellyfin web app.. I just want to be able to browse to a link to stream the video (i have another client).

When I click on the video to get the stream URL I get this:

http://192.168.56.101:8096/Items/2ec917d7ca2637453016217f4887784e/Download?api_key=c5bd71c909994e48ac732e0780b705fd

However that is not a stream URL (its a download URL). I dont want to download the video, I want to stream it. 

When I click on media info.. I see the following path:
/jellyfin/jellyfish-25-mbps-hd-hevc.mp4

Presumably I can append this to the server address:
http://192.168.56.101:8096/

But that doesnt work either:
![image](https://user-images.githubusercontent.com/48793689/111817018-dccedc80-88b3-11eb-8b37-7150e012f06e.png)


Guidance?

**Comment by davesargrad** [comment]
> Based on the docs that should work, so I’m not sure what it’s doing
> https://jellyfin.org/docs/general/server/media/movies.html

Thanks.. I'll dig.. I'm sure I'll figure it out.

**Comment by davesargrad** [comment]
Interestingly  . in the log i see one of those videos:

![image](https://user-images.githubusercontent.com/48793689/111818769-f07b4280-88b5-11eb-89ef-f39cd944e96f.png)

Yet it doesnt show up.

The other interesting thing is jellyfin discovered an online video seemingly :)

![image](https://user-images.githubusercontent.com/48793689/111818853-0ab52080-88b6-11eb-80e4-f5be859fcc5d.png)

**Comment by davesargrad** [comment]
If I delete the jellyfish movie.. and recreate the library.. then it finds small :)
![image](https://user-images.githubusercontent.com/48793689/111820037-659b4780-88b7-11eb-8baf-6a8b3d04e194.png)

**Comment by davesargrad** [comment]
Ok.. folder structure fixed that:
![image](https://user-images.githubusercontent.com/48793689/111820348-c0cd3a00-88b7-11eb-83fb-7fc7e221e3d7.png)

Now I just need to figure out the streaming URL
