### ISSUE TITLE
Copy Stream URL is providing a download URL rather than a Stream URL

### ISSUE THREAD

**Issue by davesargrad** [jellyfin/jellyfin#5573]
When I click on Copy Stream URL I expect to get a URL that I can use with another client that wants to stream video.

However I get a download URL instead (even though there is a separate download link provided):
http://192.168.56.101:8096/Items/022e685401c61352eff3b789ecd6959f/Download?api_key=c5bd71c909994e48ac732e0780b705fd

I dont want the client application to download the linked movie.. I want the stream to be available to that client, similar to the following streams (the big-buck-bunny below is a perfect example):

https://youtu.be/jNgP6d9HraI

http://cdnapi.kaltura.com/p/1878761/sp/187876100/playManifest/entryId/1_usagz19w/flavorIds/1_5spqkazq,1_nslowvhp,1_boih5aji,1_qahc37ag/format/applehttp/protocol/http/a.m3u8

https://www.radiantmediaplayer.com/media/big-buck-bunny-360p.mp4

**Comment by crobibero** [comment]
What client are you trying to play with? This sounds more like a feature request then a bug report.

**Comment by davesargrad** [comment]
> What client are you trying to play with? This sounds more like a feature request then a bug report.

@crobibero I'm trying to simply browse to it with my browser. Browsers have built in support to stream a variety of videos.. If you click on the last example I provided (which is an mp4).. you'll see that it will stream directly into your browser.

I assumed that jellyfin would support standard streams (such as HLS, DASH, etc).. Maybe I need to put the file into a different format?

**Comment by crobibero** [comment]
I guess I don’t see the reason behind doing this. Jellyfin would have to magically know the supported formats for whatever client is trying to steam the video, or default to using the web player’s supported formats. Additionally, you wouldn’t get any playback reporting.

**Comment by davesargrad** [comment]
> I guess I don’t see the reason behind doing this. Jellyfin would have to magically know the supported formats for whatever client is trying to steam the video, or default to using the web player’s supported formats. Additionally, you wouldn’t get any playback reporting.

Well.. the reason for using clients other than the Jellyfin provided client is because there are many.. As long as the jellyfin server exposes its streams in standards such as HLS.. that service needs to know nothing of the client.. The video service API is simply a contract between client and service..

I'd assume that Jellyfin can support HLS or Dash.. they are global standards.

**Comment by davesargrad** [comment]
Well.. looks like others have made this request as well. I hope they act on it.

https://features.jellyfin.org/posts/13/hls-adaptive-streaming-movies-using-pre-encoded-files-with-jellyfin

**Comment by cvium** [comment]
Hello, you can always view the latest stable API here https://api.jellyfin.org/#operation/GetMasterHlsVideoPlaylist

**Comment by davesargrad** [comment]
@cvium Thanks!! I am digging and it certainly looks like HLS is supported by jellyfin.. I'll read the link that you sent to see if that has some details.

**Comment by davesargrad** [comment]
@cvium 
Thats what I needed.. Thanks. 

Got it working with this link:

http://192.168.56.101:8096/Videos/022e685401c61352eff3b789ecd6959f/main.m3u8?api_key=c5bd71c909994e48ac732e0780b705fd

**Comment by thisisjaymehta** [comment]
Jellyfin should give this stream URL instead of Download URL when clicking "Copy Stream URL"

**Comment by sureshfizzy** [comment]
> Jellyfin should give this stream URL instead of Download URL when clicking "Copy Stream URL"

I too face the same issue, due to this if a single user has access to jellyfin account he can send stream url to many anonymous users without any security concerns which is quite big loop hole

**Comment by MCH170** [comment]
I have the same issue. Are there step by step instructions on how to solve it?

**Comment by Florin-Popescu** [comment]
this issue is still relevant. I'm getting it right now when clicking "Copy Stream URL". Why is this closed?

**Comment by cvium** [comment]
Because it's not a bug

**Comment by Andrewpk** [comment]
At the very least it should be renamed "Copy Download URL" - still seems like a bug.
