### ISSUE TITLE
Can't play media in 10.7

### ISSUE THREAD

**Issue by fatraaij** [jellyfin/jellyfin#5578]
**Describe the bug**
Title says it all, I can't play media in the latest version of Jellyfin server. Media simply has no "play button" except music which has a play button but nothing starts playing. Nothing worked except the Gelli app for android (which transcodes). After trial and error and looking through the logs I restored a backup and now everything is working again.

**System:**
 - OS: Ubuntu Server 20.04.2 LTS
 - Virtualization: LXC
 - Clients: Browser, Android, iOS, etc
 - Browser: Firefox 86.01
 - Jellyfin Version: 10.7.0
 - Playback: Direct Play (I guess)
 - Installed Plugins: Opensubtitles,TVDB,AudioDB,MusicBrainz
 - Reverse Proxy: nginx (with config file from jellyfin docs)
 - Base URL: /web/#!/home.html
 - Networking: Accessible through port forwarding
 - Storage: NFS mounted in Container

**Expected behavior**
There should be a play button in the web player. Play buttons in Android/iOS apps don't do anything.

**Logs**
Logs simply have no entry's because media isn't clickable.

**Comment by dmitrylyzo** [comment]
If you upgraded from 10.6.x, you probably left old `/usr/share/jellyfin/web/config.json`.
Old config didn't have plugin list. Without plugins, Jellyfin has no players - no `Play` button.
There is a [fix](https://github.com/jellyfin/jellyfin-web/pull/2503) that is supposed to be backported.
For now, try to replace config with [this one](https://raw.githubusercontent.com/jellyfin/jellyfin-web/release-10.7.z/src/config.json).

**Comment by madscientist42** [comment]
Nope.  When you move a fresh copy of the config to fix the black screen from out of GitHub, it's broken this way.

Do ANY of you test your stuff?

**Comment by madscientist42** [comment]
And I just did a fresh re-install to see if it was anything of any of that- and now it's just HUNG.  I'm not going to belabor this as it's not germane to the ticket in question.  This is a wake-up call, guys.

**Comment by cvium** [comment]
I'm awake, thanks.

**Comment by MrTimscampi** [comment]
![image](https://user-images.githubusercontent.com/19396809/111973867-39720780-8aff-11eb-9ef1-151b220db4e7.png)

**Comment by MrTimscampi** [comment]
@fatraaij Make sure you are using the stable version and not one of the release candidates. We had the issue you describe during the RC process, but it was fixed, as far as we know.

@madscientist42 In addition to not being a dick, could you please not hijack Github issues to try to troubleshoot an unrelated issue. You have a black screen, OP doesn't. 

Please try to fill a proper issue for it or (even better) try to reach the team through one of the troubleshooting channels, since the goal of Github issues isn't to help you troubleshoot an issue on your end but to keep track of actual issues (And it seems to be the former here, as far as we can tell).

**Comment by fatraaij** [comment]
Hi,
First time I tried upgrading to 10.7.0 I kept my original config but later edited it as I got the same black screen @madscientist42 is talking about. I've upgraded again (this time to 10.7.1) and now everything works. I don't know if it has to do with .1 or my incompetence trying to copy over the new config in the previous upgrade attempt.

**Comment by cvium** [comment]
I'm glad it was resolved and thank you for the kind words. Closing.
