### ISSUE TITLE
Add ability to arrange by release date in "Latest" at home screen

### ISSUE THREAD

**Issue by screwfaze** [jellyfin/jellyfin#558]
Would be good to have library option to arrange by release date instead of date added. When moving files around my hard drives latest keeps changing by date I move things.

**Comment by drago-96** [comment]
Uhm, I have the option to sort by "Release Date" by clicking on the AZ button at the top of each library...

**Comment by screwfaze** [comment]
Yes that sounds right thanks for all the hard work you guys are doing.

**Comment by T0W1** [comment]
![Screenshot from 2019-05-15 17-26-49](https://user-images.githubusercontent.com/50248556/57789499-54bca080-7739-11e9-931b-b5d265c933ca.png)
