### ISSUE TITLE
Jellyfin Docker on Synology DSM using > 10Gb of RAM

### ISSUE THREAD

**Issue by davbro63** [jellyfin/jellyfin#5592]
**Describe the bug**

I see the Jellyfin Docker container consuming more and more RAM as it runs / serves files over DLNA.
The latest count was 11.5Gb out of 20Gb available on the NAS

**System (please complete the following information):**
 - OS: Docker on Synology DS1621+
 - Virtualization: Docker
 - Clients: VLC, DLNA
 - Browser: N/A
 - Jellyfin Version: 10.7.1
 - Playback: DLNA
 - Installed Plugins: None
 - Reverse Proxy: None
 - Base URL: None
 - Networking: Host
 - Storage: Local

**To Reproduce**

The excess RAM can be reproduced each time by:
1. Restart the Docker Container in the Synology DSM Docker manager
2. Stream movies over DLNA that have an issue, reported under #5591 
3. RAM will rise continually until the Docker container is restarted
4. After a restart of the container, RAM will not rise until streaming over DLNA is attempted again

**Expected behavior**

RAM should not be consumed to the detriment of other applications running on the same system

**Logs**
N/A

**Screenshots**
N/A

**Additional context**
N/A

**Comment by cvium** [comment]
Need to see the output of `htop` or similar

**Comment by davbro63** [comment]
htop on the host shows:
![image](https://user-images.githubusercontent.com/11368646/112119278-228dec80-8bb5-11eb-8043-0475ac0c2317.png)
Portainer shows:
![image](https://user-images.githubusercontent.com/11368646/112119343-32a5cc00-8bb5-11eb-82c3-336b0886a28d.png)
Synology's Docker container manager shows:
![image](https://user-images.githubusercontent.com/11368646/112119427-46513280-8bb5-11eb-8191-d3f678b18c5e.png)

**Comment by cvium** [comment]
From your htop output I only see 375 MB actual usage. Where's the other 6 GB? Your Virt memory is high but that just seems like how .NET works and shouldn't cause any issues.

**Comment by davbro63** [comment]
Thanks, the figure given in Portainer and Synology of ~6Gb was what concerned me.
The values above are from this morning, I have seen it as high as 11.5Gb in both views.

**Comment by davbro63** [comment]
It's now showing over 12Gb, the increase happened when I started playing videos over DLNA:
![image](https://user-images.githubusercontent.com/11368646/112133890-11001100-8bc4-11eb-9a8a-d1b06937059d.png)
and Portainer shows:
![image](https://user-images.githubusercontent.com/11368646/112133925-1c533c80-8bc4-11eb-9bf6-fa96c1c60c1e.png)

**Comment by cvium** [comment]
But what does htop say? I wouldn't necessarily trust Portainer nor Synology. Playing a video should result in a memory increase since ffmpeg is loading the file into memory while it transcodes. If it's _direct play_ it should of course mostly remain the same as the file is simply streamed.

**Comment by davbro63** [comment]
htop shows:
![image](https://user-images.githubusercontent.com/11368646/112141373-1f065f80-8bcd-11eb-8955-39b2520f111a.png)
for the Synology view:
![image](https://user-images.githubusercontent.com/11368646/112141424-2ded1200-8bcd-11eb-9aa2-42b0a16eeb27.png)
And Portainer view:
![image](https://user-images.githubusercontent.com/11368646/112141622-68ef4580-8bcd-11eb-86f0-2ea3393c4519.png)

**Comment by ddurdle** [comment]
I'm finding similar on both the official docker image and on the linuxserver.io docker.  

What I noticed is that when a folder or full scan is performed, the memory will increase rapidly and not settle down afterwards.  Repeated scans will cause it to increase the same amount each time.  Eventually the system runs out of memory.

My library db size is 2GB and it seems each scan causes the memory consumed to increase by 2GB.  After letting it settle after many hours, it might drop a few hundred MB, if no subsequent scans are done.

Has been happening on 10.7.0-RC1 - 10.7.1.  Cannot reproduce the issue on 10.4, 10.5, 10.6.3

**Comment by cvium** [comment]
@ddurdle As always, we need to see actual proof of this like the output of htop before and after a "memory increasing event". And possibly something like https://docs.microsoft.com/en-us/dotnet/core/diagnostics/debug-memory-leak or https://www.jetbrains.com/help/dotmemory/Working_with_dotMemory_Command-Line_Profiler.html#instant and then send us the dump.

**Comment by ddurdle** [comment]
> @ddurdle As always, we need to see actual proof of this like the output of htop before and after a "memory increasing event". And possibly something like https://docs.microsoft.com/en-us/dotnet/core/diagnostics/debug-memory-leak or https://www.jetbrains.com/help/dotmemory/Working_with_dotMemory_Command-Line_Profiler.html#instant and then send us the dump.

Is there a debug version of the JF docker image with the required debug toolchain indicated by the microsoft article?

**Comment by cvium** [comment]
Starting from 10.7.2 workstation GC will be the default #5769
