### ISSUE TITLE
IPTV 6.0.0.0 is unsupported on Windows Service x64 

### ISSUE THREAD

**Issue by vtyr** [jellyfin/jellyfin#5601]
**Describe the bug**
IPTV 6.0.0.0 is unsupported on Windows Service x64 

**System (please complete the following information):**
 - OS: Windows
 - Virtualization: Service
 - Clients: [Browser, Android, Fire Stick, etc.]
 - Browser :Chrome
 - Jellyfin Version: 10.7.1
 - Installed Plugins: OpenSubs, IPTV

**To Reproduce**

1. Go to Plugins
2. Install IPTV
3. Restart Service
4. IPTV shows as "not supported"

**Expected behavior**
IPTV supported

**Comment by crobibero** [comment]
IPTV is built into Jellyfin and the plugin has been archived.

**Comment by vtyr** [comment]
> IPTV is built into Jellyfin and the plugin has been archived.

Is this now called Live TV? If so, I've added my m3u file but there's no channels available 9all categories are empty, movies etc) even after a full scan
