### ISSUE TITLE
Playback issues with Samsung UE48JE6050

### ISSUE THREAD

**Issue by Thalhammer** [jellyfin/jellyfin#5603]
**Describe the bug**
Beginning with version 10.7.0 DLNA playback on Samsung TV UE48JE6050 is broken.
Apart from the fact that all my videos are transcoded/muxed now (which is unnecessary since the tv supports them), this muxing also breaks playback. The video starts fine, but after about 2 seconds video does a jump and after that audio is delayed by about 1 second. I use the official docker image, but I dont think thats relevant. I am currently back to version 10.6.4 which works fine for playback, but this is not a permanent solution as I'd really like to get the fix for #3361 .

**System (please complete the following information):**
 - OS: Docker image (jellyfin/jellyfin:latest) on a ubuntu 20.04 host.
 - Virtualization: Docker 20.10.5 in a Ubuntu 20.04 KVM on a Proxmox Host (container is in network=host mode)
 - Clients: Samsung Smart TV UE48J6050 (current firmware).
 - Browser: -
 - Jellyfin Version: 10.7.0 
 - Playback: Direct-Play (should) / Transcode (is)
 - Installed Plugins: AudioDB, IPTV, Kodi Sync Queue, MusicBrainz, OMDB, Playback Reporting, Reports, TheTVDB
 - Reverse Proxy: none
 - Base URL: none
 - Networking: Bridged to LAN
 - Storage: NFS on the same host

**To Reproduce**
1. Buy a Samsung U48J6050 (other samsung may be similar)
2. Install version 10.7.0
3. Watch it break

**Expected behavior**
It works fine (as it did before).

**Logs**
I dont have any (more) but it is easy to reproduce on my system. That said, the log contained nothing special, except it seems to always call transcode with ffmpeg (even if it does nothing, like transcoding from mkv to mkv with copy for video,audio,everything). This was not present on 10.6.4

**Screenshots**
-

**Additional context**
During playing around with 10.7.0 I created a copy of the dlna profile which was still present when I switched back to 10.6.4.
10.6.4 had the same issue in the beginning but since I knew it worked before, I removed the profile and voilà it worked again.
I thus believe it is an issue related to the DLNA profile. However I could not find any obvious differences in the file between 10.6.4 and 10.7.0.
I'll look more into it though.
EDIT: I just did a diff between the "Samsung Smart TV.xml" of my current install and the latest one in github, however they are byte identical.

**Comment by cvium** [comment]
Don't take this the wrong way, but it's not really for you to decide if the logs are "nothing special". We request them for a reason.

That said this seems similar to https://github.com/jellyfin/jellyfin/issues/5591, which might be fixed by #5600.

**Comment by cvium** [comment]
#5600 fixes broken direct streaming on DLNA, but if the media is supposed to direct play then that is a separate issue. Reopening.

But @Thalhammer we need the ffmpeg logs...

**Comment by Thalhammer** [comment]
> But @Thalhammer we need the ffmpeg logs...

There is no ffmpeg output in the docker log, do I need to enable them somewhere ?

**Comment by cvium** [comment]
If it's transcoding/remuxing, then it should create an ffmpeg log file in the jellyfin log dir, which by default is in <jellyfin config dir>/log

**Comment by sajati** [comment]
Same problem on my samsung tyzen TV, don't remember the version. only play the intro and then closed or jump to next movie

**Comment by Thalhammer** [comment]
Ok so I did some more tests now:
Stock install of 10.7.0 shows "This filetype is not supported" when trying to play it, which is ironic since the tv would support it without any work from jellyfin.
If I edit the profile and remove dts as a sound format from mkv, I can play the video but sound is not correctly synced.
I did a [video](https://youtu.be/aon3blgkZV0) showing the issue (pardon the german ui text and sound). You can clearly see the video jump at the start which in it self wouldnt be an issue, but it desyncs the audio, which lags after the video. You can clearly see the delay on the gunshot in the car. Also as a result of the transcoding the video seeking/progressbar doesnt work anymore.
10.6.4 on the same machine (also in docker) works fine and correctly displays seeking and audio in sync.

I have attached the logs of jellyfin both 10.7.0 and 10.6.4 as well as the ffmpeg log of 10.7.0 (10.6.4 doesnt have one since it never called ffmpeg).

[video showing issue on tv](https://youtu.be/aon3blgkZV0)
[docker_log_10_6_4.txt](https://github.com/jellyfin/jellyfin/files/6199859/docker_log_10_6_4.txt)
[docker_log_10_7.txt](https://github.com/jellyfin/jellyfin/files/6199860/docker_log_10_7.txt)
[ffmpeg-remux_10_7.txt](https://github.com/jellyfin/jellyfin/files/6199861/ffmpeg-remux_10_7.txt)

**Comment by BaronGreenback** [comment]
@cvium  

Came across this error whilst testing the dlna playTo. From memory i think https://github.com/jellyfin/jellyfin/pull/5622 fixed the issue.
