### ISSUE TITLE
JF DB migration is faulty

### ISSUE THREAD

**Issue by Haarolean** [jellyfin/jellyfin#5604]
**Describe the bug**
After upgrade (via docker-compose pull) from 10.5.5 to 10.7.1 I can't neither login with my admin account nor reset the password nor create a new admin account.

**System (please complete the following information):**
 - OS: debian
 - Virtualization: docker
 - Clients: N/A
 - Browser: N/A
 - Jellyfin Version: 10.5.5 -> 10.7.1
 - Playback: N/A
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: idk
 - Networking: docker bridge
 - Storage: local

**To Reproduce**

1. Install 10.5.5
2. Set all the things up
3. Update to 10.7.1
4. ???

**Expected behavior**
I can login with previous credentials.

**Logs**
no errors

**Screenshots**

**Additional context**
1. PIN auth is not available (why?)
2. My credentials does not work at all now.
3. I tried resetting the password via UI, but no luck, jellyfin is run in a container so it doesn't recognise this network a 'home network'
4. I tried setting IsStartupWizardCompleted to false and creating a new account. But it's not an admin account for some reason.
5. I checked jellyfin.db, all previous users (except for previous admin account) are lost. 
6. I've set new user's password hash for the old one, still can't login. Rows are identical except for UUIDs ofc.

Finally fixed the user via this query:
update Permissions set Value = 0 where Kind = 2 and Permission_Permissions_Guid = 'uuid';

x

**Comment by makunterry** [comment]
You should clean the browser cache and cookies.

**Comment by Nautigsam** [comment]
@makunterry Does not fix the problem. I get the following logs:
```
[13:04:01] [ERR] [44] Jellyfin.Server.Implementations.Users.UserManager: Error authenticating with provider Default
MediaBrowser.Controller.Authentication.AuthenticationException: Specified user does not exist.
   at Jellyfin.Server.Implementations.Users.DefaultAuthenticationProvider.Authenticate(String username, String password, User resolvedUser)
   at Jellyfin.Server.Implementations.Users.UserManager.AuthenticateWithProvider(IAuthenticationProvider provider, String username, String password, User resolvedUser)
[13:04:01] [INF] [44] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for admin has been denied (IP: 192.168.33.1).
[13:04:01] [ERR] [44] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request: Invalid username or password entered. URL POST /Users/authenticatebyname.
```

**Comment by cedricraud** [comment]
+1, I encountered exactly the same issue, with the same bump (10.5.5 → 10.7.1)

**Comment by Haarolean** [comment]
bump

**Comment by barronpm** [comment]
I was unable to replicate this behavior. One thing I could potentially think of is if you had two users with the same name but different capitalization, but I don't think that would cause the described behavior.

**Comment by Haarolean** [comment]
> I was unable to replicate this behavior. One thing I could potentially think of is if you had two users with the same name but different capitalization, but I don't think that would cause the described behavior.

Hey, thanks for checking this out. I'll try to reproduce it again on my side.

**Comment by Haarolean** [comment]
way outdated
