### ISSUE TITLE
Library Access to other users and Syncplay - BUG

### ISSUE THREAD

**Issue by itsmecom** [jellyfin/jellyfin#5607]
1. i have disabled all library access to a particular user. But the files in the library are visible on search for that user. How can i stop it?

2. i have set user can "able to only join syncplay". when that user click on syncplay button and join the existing session. once the session is closed over. the option in dashboard automatically changes to "allow users to create syncplay" option for that user.

**Comment by cvium** [comment]
1. Known limitation. No fix.
2. Sounds like a new bug.

**Comment by itsmecom** [comment]
these both bugs happens on 10.6 and in 10.7.1 versions too

**Comment by itsmecom** [comment]
Any Follow Up, Anybody working to fix these issue?

**Comment by itsmecom** [comment]
is this issues fixed, can anyone tell.

**Comment by Bond-009** [comment]
Closing as stale
