### ISSUE TITLE
Music Video Library Issues

### ISSUE THREAD

**Issue by ramon-kramer** [jellyfin/jellyfin#5608]
**Describe the bug**
No Music Videos are listed on Artist page.

**System (please complete the following information):**
 - OS: Debian
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Firefox 86
 - Jellyfin Version: 10.7.1
 - Installed Plugins: IMVDb
 - Reverse Proxy: apache
 - Storage: local

**To Reproduce**
1. Go to Music Video Library
2. Click on a Video (not play)
3. Click on Artist Name (or search for an Artist with Music Videos and open Artist page)
3. Scroll down to Music Videos
4. See no Videos listed here

**Expected behavior**
Artist Page should list all Music Videos of this Artist. This works on Emby Server, Music Videos are additionally listed on Artist page in normal Music Library.

![Screenshot_2021-03-24 Jellyfin](https://user-images.githubusercontent.com/45063149/112269275-731a4e00-8c78-11eb-8a44-0151bdc37f50.png)
![Screenshot_2021-03-24 Jellyfin1](https://user-images.githubusercontent.com/45063149/112269503-bbd20700-8c78-11eb-9db4-72cc7e151af1.png)

**Comment by Killface1980** [comment]
Same here. No music videos are display. Everything is tagged properly.

Seems like the Artist id isn't properly added to the music videos.
