### ISSUE TITLE
Special features no longer get populated

### ISSUE THREAD

**Issue by liggy1** [jellyfin/jellyfin#561]
According to [naming conventions](https://github.com/MediaBrowser/Wiki/wiki/Movie-naming#movie-extras), it is possible to add special features for a film in a sub-folder. Looking at table _TypedBaseItems_ in library.db I can find the references to my special features and feeding latest Emby stable releases with the Jellyfin config, the Special Items are displayed, however Jellyfin since 3.5.2-5 seems unable to fill the _specialsContent_ div in MediaBrowser.WebDashboard\dashboard-ui\itemdetails.html. This seems to be done in function _renderSpecials_ in MediaBrowser.WebDashboard\dashboard-ui\scripts\itemdetailpage.js and here is where my skills end to track this much further.

**Comment by drago-96** [comment]
The issue is not in the frontend: it's the API which returns an object with `SpecialFeatureCount`equal to 0.

**Comment by liggy1** [comment]
I tried to further debug with that information and this seems to come from `public IEnumerable<BaseItem> GetExtras()` and `public IEnumerable<BaseItem> GetExtras(ExtraType[] unused)` in MediaBrowser.Controller\Entities\BaseItem.cs

Seems the first one should return all extras, while the second one is supposed to return all extras matching the ExtraType values in the unused parameter. As I'm not a C# programmer I was not able to find out, why the `ThemeVideoIds.Select` command does not return anything and comparing to the latest available Emby source of that file indicates that things have changed a lot here when this file went closed source.
