### ISSUE TITLE
PDFs >=~40 Megabytes in size, never finish loading

### ISSUE THREAD

**Issue by zachron** [jellyfin/jellyfin#5610]
**Describe the bug**
When loading pdfs that are bigger then ~40M the console displays a 
`Uncaught (in promise) undefined`
`inputManager: tried to process command with no action assigned: unknown ` 
and the loading indicator never stops and pdf never loads

**System (please complete the following information):**
 - OS: Linux
 - Virtualization: None
 - Clients: Browser
 - Browser: Firefox 86
 - Jellyfin Version: 10.7.1 
 - Playback: Books
 - Installed Plugins: None
 - Reverse Proxy: nginx
 - Base URL: none
 - Networking: host
 - Storage: local

**To Reproduce**
1. make a books library with some PDFs that are >= ~40M
2. try to view them

**Expected behavior**
PDF will load correctly, like PDFs that are < 40M do.

**Logs**
no errors are reported in the server log

**Additional context**
It appears to only happen with firefox, i cannot replicate it in chrome, safari, or any other browser i have access to, but i can reliably replicate it on multiple machines with firefox.

**Comment by crobibero** [comment]
Please fully fill out the issue template, including server logs.
