### ISSUE TITLE
When wanting to scan any library, it is automatically canceled.

### ISSUE THREAD

**Issue by JulioNahum** [jellyfin/jellyfin#5616]
When wanting to scan any library, it is automatically canceled.

Since a few days when updating to 10.7.1 of the jellyfin server, and wanting to scan some libraries, there comes a point where it cancels itself. And leave the scan halfway. And one has to do it manually to finish the process.

**Comment by ferferga** [comment]
Hello

There's no known issue about this currently. With the provided information there's no way of knowing what's exactly going on.

Please, fill the template accordingly and open a new issue.
