### ISSUE TITLE
SendMessageCommand should be using FromBody

### ISSUE THREAD

**Issue by BrianCArnold** [jellyfin/jellyfin#5628]
All parameters for the API Endpoint are marked as [FromQuery] as of 3/26/2021

Permalink to current SessionController implementation:  
https://github.com/jellyfin/jellyfin/blob/6946e58ca4ee904615146b3a702663cc630f5ad6/Jellyfin.Api/Controllers/SessionController.cs#L312

The current implementation of sendMessageCommand in apiClient.js is passing the options in the POST body, rather than sending the parameters as query string parameters.

Note: I have a commit to resolve this issue, which I will include in a pull request to resolve this.

**Comment by BrianCArnold** [comment]
I originally created the pull request for the javascript side because the server and kotlin api seemed to agree with each other and tried to fix it with the smallest change necessary.
I'll make linked pull requests for the SessionController.cs, Kotlin API, and check all other API projects to make sure they all POST the information in the body. Thanks.

**Comment by crobibero** [comment]
Just as a heads up, the Kotlin sdk is auto-generated, so changes aren't required there.

**Comment by BrianCArnold** [comment]
Ahh, thanks, that would explain why they match. Just about done with the API change.

There's a few unrelated minor edge case bugs in the SessionController I've noticed, is that something I should submit a separate pull request for, or would lumping them in with this be acceptable?

**Comment by BrianCArnold** [comment]
My normal workflow is in GitLab or Azure DevOps. If I need to add anything to this pull request, or if I've forgotten something, please let me know.

**Comment by BrianCArnold** [comment]
These pull requests should resolve the issue for the API and all clients that implement that call to the APIs
