### ISSUE TITLE
Google phishing detected

### ISSUE THREAD

**Issue by eniac111** [jellyfin/jellyfin#5630]
This is ridiculous!

Google was detected my home JellyFin instance as a phishing site. It was accessible to internet but it was only used by my family. It appears that the media corporations mafia is attacking us?

![phishing](https://user-images.githubusercontent.com/895904/112645384-158c2a00-8e4f-11eb-813d-76bd1ada8f07.png)

![google](https://user-images.githubusercontent.com/895904/112645507-36ed1600-8e4f-11eb-874f-c3eddd1c8be3.png)

robots.txt is working just fine: 
```
User-agent: *
Disallow: /
```

**Comment by anthonylavado** [comment]
Your site can appear on the Safe Browsing watch list for a variety of reasons, including manual reports. This would be beyond our control.

I would suggest that you report the detection problem to Google 🙂
