### ISSUE TITLE
Allow clients to send log messages to server

### ISSUE THREAD

**Issue by neilsb** [jellyfin/jellyfin#5646]
Allow clients to be able to send Log Messages to server to be included in a server log.  This would be useful for a couple of reasons:

1. For clients which have no (or very limited) logging capabilities (e.g. Roku, Smart TVs etc) it would allow the ability to logs to retained somewhere for analysis if required - without having to use an external service
2. It would allow server owners to more easily collate and provide logs for clients which are having problems for issues reporting / debugging

**Comment by MrTimscampi** [comment]
Format proposal:
```json
{
  timestamp: "", // ISO time stamp
  level: "info", // One of debug/info/warning/error (maybe trace?)
  userId: "", // Optional user ID
  client: "", // Client name
  version: "", // Client version
  deviceId: "", // Device ID
  message: "" // Message
}
```

**Comment by nielsvanvelzen** [comment]
Sending single messages in JSON is not a great idea for the Android apps. The apps produce a lot of log messages (when including  those from the dependencies) and serializing all of those to a JSON document is wasteful of the devices resources (and potentially slow).

The original idea to post logs to the server was for crash logs. In Android TV this is generated by ACRA. The crashreport includes some metadata and one big string with the log lines. I think we should just implement an endpoint to PUT a textfile to the logs directory (name is chosen by server) for that use-case.

Logs should ideally support bulk uploads, and I'd prefer pushing txt files for that too (with the authorization header containing the information from the client/device/user).

**Comment by MrTimscampi** [comment]
We could/should probably do both, I think.

A crash-log endpoint through the API, and a log upload via the websocket.

This way, we have the best of both worlds.

**Comment by crobibero** [comment]
It might be possible to send logs to a different file depending on client using https://github.com/serilog/serilog-sinks-map
