### ISSUE TITLE
Kodi Unable to receive message from server in 10.7.1

### ISSUE THREAD

**Issue by serenity666** [jellyfin/jellyfin#5649]
Describe the bug
Kodi Unable to receive message from server.
![image](https://user-images.githubusercontent.com/64485323/112826232-4bcfe080-90bf-11eb-97eb-8dd562a8fd0c.png)
But in the remote control interface, Kodi can receive messages normally
![image](https://user-images.githubusercontent.com/64485323/112825569-808f6800-90be-11eb-824d-d1ee6d18f8d2.png)
Everything is OK in 10.6.4.
 - OS: [synology]
 - Virtualization: [ Docker]
 - Clients: [kodi, Android]
 - Browser: [ Chrome ]
 - Jellyfin Version: [10.7.1]

**Comment by BrianCArnold** [comment]
I believe this is the same issue as #5628, which I have a pull request in to resolve.
