### ISSUE TITLE
Transcoding from H.264 Level 4.2 to H.264 Level 4.1 doesn't trigger changing the framerate 

### ISSUE THREAD

**Issue by sandervankasteel** [jellyfin/jellyfin#5656]
**Describe the bug**
Transcoding from H.264 Level 4.2 to H.264 Level 4.1 doesn't trigger transcoding with changing the framerate. 

I have some h.264 Level 4.2 (1920x1080p, *50fps*) media files, which I am trying to cast to my Chromecast Gen 2. FYI: a Chromecast Gen 2, only supports h.264 Level 4.1. 

The maximum fps, for level 4.1 according to [Wikipedia](https://en.wikipedia.org/wiki/Advanced_Video_Coding#Levels) is 1920x1080@30.1 fps and thus transcoding Level 4.2 to Level 4.1 h.264 with 50fps, on level 4.1 is out-of-spec. 

This lack of framerate transcoding behavior is causing jerky playback because the Chromecast is still trying to playback the supplied stream, but throttles because it doesn't have the power to handle 30+ fps @ 1920x1080 material. 

**System:**
 - **OS**: Debian
 - **Virtualization**: Docker-compose (with custom Dockerfile for AMD hardware-based transcoding using Ubuntu Focal)
 - **Clients**: Chromecast Gen 2 (using Jellyfin-chromecast 'unstable')
 - **Jellyfin Version**: 10.7.1
 - **Playback**: Transcoding

**To Reproduce**
Try to cast mentioned files (which applies to this situation) to a Chromecast and see in the logs that the output stream doesn't transcode to a different framerate. 

**Expected behavior**
See an output stream that adheres to the spec. ie. h.264 level 4.1, 1920x1080p @ 30 fps.

**Logs**
[ffmpeg.Transcode-2021-03-29_19-22-22.level42-to-level41-fps-missing.log](https://github.com/jellyfin/jellyfin/files/6223685/ffmpeg.Transcode-2021-03-29_19-22-22.level42-to-level41-fps-missing.log)

**Screenshots**
Not applicable

**Additional context**
1. I am unsure if this is a bug in Jellyfin (or FFmpeg, for even allowing such out-of-spec transcoding), but if this isn't a bug in Jellyfin, then please let me know and I will report this bug with ffmpeg. 

2. I found a test file at the Kodi Wiki which matches the specs of the files, I am casting to my Chromecast (https://drive.google.com/file/d/0BwxFVkl63-lEbVptTVZ2NENURHM/view).

**Comment by sandervankasteel** [comment]
I just tried it with Jellyfin 10.7.2, but the same issue still occurs.

**Comment by sandervankasteel** [comment]
I tried it with Jellyfin 10.7.5, but this still happens.

**Comment by sandervankasteel** [comment]
Still occurs with Jellyfin 10.7.6.

**Comment by srcrist** [comment]
Are you able to confirm that this issue still exists in 10.8.11?

**Comment by sandervankasteel** [comment]
> Are you able to confirm that this issue still exists in 10.8.11?

To be honest, I can't confirm that behaviour anymore because a while back I replaced my old Gen 2 Chromecast with an Android TV based Chromecast. 

However, the link to the test file still works. So if somebody still has the hardware for it, they should be able confirm whether or not this is still an issue.
