### ISSUE TITLE
Music video library doesn't load art from .nfo file 

### ISSUE THREAD

**Issue by nialister** [jellyfin/jellyfin#5658]
**Describe the bug**
I have music video library with metadata stored in .nfo file. All data are loaded normally except "art" tag. If i create library and choose Screen Grabber as image fetcher then it replaces all images to new. If i uncheck Screen Grabber then images are not loading at all. Poster and fanart are present on disk, paths are valid, but images aren't displayed on the server. For movie type library everything works as expected.

**System (please complete the following information):**
 - OS: Windows 10
 - Virtualization: -
 - Clients: Browser
 - Browser: Firefox 87
 - Jellyfin Version: 10.7.1
 - Installed Plugins: -
 - Storage: local

**To Reproduce**
Create a .nfo file for movie/video and add art tag to it. 
Create music video library with stored metadata in .nfo files and check Screen Grabber.
See all images in tag <art> are replaced and new images displayed on server.
or
Create a .nfo file for movie/video and add art tag to it. 
Create music video library with stored metadata in .nfo files and uncheck Screen Grabber.
See that .nfo files haven't changed but no images are loaded on server.

**Expected behavior**
I expect that if i create library with metadata store in .nfo files and there are valid paths in art tag, then server loads these images. And if paths are invalid or i choose "replace images" in metadata update option, then paths in art tag need to be replaced.

I attach some screenshots
![sc1](https://user-images.githubusercontent.com/81285853/112943822-0d7c0500-9143-11eb-8f2d-05f406744e12.PNG)
![sc2](https://user-images.githubusercontent.com/81285853/112943842-1371e600-9143-11eb-9359-f578b33d97d0.PNG)

**Comment by Ullmie02** [comment]
So you have your Art paths in your nfos like this?
```
<art>C:\Path\To\Art.jpg</art>
```
This tag is currently not supported by Jellyfin.

**Comment by Degrian** [comment]
Yeah, you're right, i have paths like this. So what can i do with that? Or maybe i can use another tag?

**Comment by Ullmie02** [comment]
The current stable version 10.7.x has no tags for that purpose. The next major release (10.8.0) will have support for
```
<thumb aspect="poster">C:\Path\To\Art.jpg</thumb>
```

**Comment by daullmer** [comment]
Closing this issue as 10.8 is released with support for the thumb tag
