### ISSUE TITLE
Server /root dir filling up

### ISSUE THREAD

**Issue by RebelCoderRU** [jellyfin/jellyfin#5665]
I am trying to understand why, during Jellyfin playback, my / root directory (can't find the exact path) on my Linux server is filling up. This causes my server to stop working in a lot of cases as `mysql` db cant operate and other services on this server stop functioning.

In some cases I see storage is freed after Jellyfin playback is stopped, but in some it does not. If 2-3 people are using the server to watch stuff, it just fills up my root dir and breaks the server.

Is it decoding a video and saves a new copy somewhere in some cache folder? If yes, can it be disabled or directory changed to other drive where I have a ton of space?

Here is just one user watching 1080p video:
![jf](https://user-images.githubusercontent.com/20476773/113101298-3795fb80-9205-11eb-9a67-c28375e78f0c.gif)

**Comment by BaronGreenback** [comment]
Cache files are generated at playback. Take a look to the cache directory in the instructions, and see if that helps.

https://jellyfin.org/docs/general/administration/configuration.html

**Comment by RebelCoderRU** [comment]
Thanks! I have seen this page. And I know that cache is in my: `$HOME/.cache/jellyfin`. The problem is that my `home` partition is a separate partition and not a part of my `/root' partition. This is why I was wondering why my `/` partition is used during the jellyfin media playback. I can't find the exact location to which it is writing into.

**Comment by dmitrylyzo** [comment]
@RebelCoderRU Check where is `Transcodes` dir? At the same place on Dashboard.

**Comment by RebelCoderRU** [comment]
Here you can see that my `home` where the cache dir is, is not shrinking in size during the playback, but `root` is:

![root](https://user-images.githubusercontent.com/20476773/113120666-7e422080-921a-11eb-8bb4-4f55a9b22f83.gif)

**Comment by RebelCoderRU** [comment]
Thanks! I just had to change the transcoding dir. I have created a new cache folder structure on my other large capacity drive and now it uses that:

```
jf_cache$ tree ./
├── cache
├── metadata
└── transcodes
```
