### ISSUE TITLE
Identify functionality stopped working

### ISSUE THREAD

**Issue by XiovV** [jellyfin/jellyfin#5667]
**Describe the bug**
After the 10.7.0 update the Identify functionality stopped working. It used to work flawlessly with any of my shows and movies before the update, but now after the Identify process is done nothing changes, even after clearing the cache in the browser. I tried following the [naming convention](https://jellyfin.org/docs/general/server/media/shows.html) but that also didn't work.

**System (please complete the following information):**
 - OS: Ubuntu Server 20.10
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Firefox 87
 - Jellyfin Version: 10.7.0
 - Playback: Direct Stream
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: none
 - Networking: Bridge/NAT
 - Storage: local

**To Reproduce**

1. Go to "TV Shows"
2. Click on "Identify"
3. Enter show name in the "Name" text box
4. Click on the blue "Search" button
5. Click on the show Jellyfin found
6. Wait for it to finish
7. The thumbnail stays like this (see first screenshot), instead of changing to the picture I selected in the Identify screen.

**Expected behavior**
The show's thumbnail and episode thumbnails + names should be changed, but they stay the same.

**Logs**

**Screenshots**
What the thumbnails look like now
![image](https://user-images.githubusercontent.com/20326947/113151827-c589da80-9235-11eb-9f47-0907ed0a1bd9.png)

What the thumbnails used to look like
![image](https://user-images.githubusercontent.com/20326947/113152944-e999eb80-9236-11eb-8c07-62fc6b198168.png)

**Additional context**

**Comment by cvium** [comment]
A couple of things:

1. Latest version is 10.7.1
2. Need to know which metadata provider you chose (it should be written below every result)

**Comment by XiovV** [comment]
@cvium Updated to 10.7.1. This is the search result:
![image](https://user-images.githubusercontent.com/20326947/113181570-3d65fe00-9252-11eb-8580-53dc470a001b.png)

**Comment by oliroe** [comment]
I had the same issue. Not sure why but the upgrade to 10.7.1 disabled the metadata provider on my movies library but after enabling one the problem went away

**Comment by cvium** [comment]
@XiovV  Anything in the logs?

**Comment by XiovV** [comment]
@cvium I fixed the issue by enabling some settings in the metadata settings page.

**Comment by cvium** [comment]
> @cvium I fixed the issue by enabling some settings in the metadata settings page.

Which settings?

**Comment by XiovV** [comment]
> > @cvium I fixed the issue by enabling some settings in the metadata settings page.
> 
> Which settings?

I just tried finding them but I couldn't for some reason. They were somewhere in the Dashboard page under the Admin category.

**Comment by XiovV** [comment]
Oh I figured it out. I clicked on my TV Shows library inside the Libraries page and I enabled more metadata providers.

**Comment by cvium** [comment]
Ok. I tested this and it seems it can be replicated if you disable the TMDb Series Image provider. Identify will show the result and a poster, but only the metadata is applied. It's a bit odd behaviour imo, but it works as intended.

**Comment by XiovV** [comment]
It is a bit odd, yes. Don't know if the update broke it or what, because I hadn't played with the settings at all before updating.

**Comment by cvium** [comment]
TVDB was removed in 10.7. It lives on as a plugin, but you have to install it first.
