### ISSUE TITLE
Add Jetson-ffmpeg (nvmpi) support

### ISSUE THREAD

**Issue by countbuggula** [jellyfin/jellyfin#5674]
Currently, while there are arm64 jellyfin builds, and you can use an external ffmpeg library, jetson-ffmpeg creates a codec called nvmpi, Which Jellyfin doesn't recognize because it's looking for nvenc.  Adding support for nvmpi/jetson-ffmpeg would enable low-cost Jetson Nano or Xavier boards to provide quality and high-performant transcoding at a fraction of the price of dedicated nvidia GPUs.
[jetson-ffmpeg](https://github.com/jocover/jetson-ffmpeg)
[Discussion on the Emby boards](https://emby.media/community/index.php?/topic/87866-jetson-nano-now-has-hardware-ffmpeg-support/)

**Comment by cvium** [comment]
We do not have required hardware, but we do accept pull requests.

Since this is a feature request it actually belongs here https://features.jellyfin.org.

**Comment by countbuggula** [comment]
> We do not have required hardware, but we do accept pull requests.
> 
> Since this is a feature request it actually belongs here https://features.jellyfin.org.

Sorry about that, I didn't see where feature requests went until just now.  I'll post there.
