### ISSUE TITLE
Videos are loading at increadibly slow rate

### ISSUE THREAD

**Issue by Dandyliar** [jellyfin/jellyfin#5678]
**Describe the bug**
When either myself or others are loading videos the videos load very slowly and then play for a couple seconds, video stops and continues to buffer and this cycle repeats. The videos are playing/ downloading at approximately 1Mbps when attempting to download the video the download also goes at this 1Mbps limit. The docker host is speed testing at 500/500 Mbps, I have rebooted the host/ docker and remade the entire container just to rule out anything that might have gotten corrupted. The videos will transcode absolutely fine

**System (please complete the following information):**
 - Virtualization: Docker
 - Clients: Browser (Firefox and Chrome), Android
 - Browser: Firefox 87.0, Chrome 89.0.4389.90 
 - Jellyfin Version: 10.7.1
 - Playback: Direct Play, Remux, Direct Stream, Transcode 
 - Installed Plugins: None
 - Reverse Proxy: Traefik
 - Base URL: 
 - Networking: Docker bridge driver
 - Storage: NAS

**Expected behavior**
For video to play at full speed without throttling 

**Logs**
No apparent errors asides from browser being throttled on chrome (HLS Error: Type: mediaError Details: bufferStalledError Fatal: false
HLS Error: Type: mediaError Details: bufferNudgeOnStall Fatal: false)

**Comment by henrikx** [comment]
Having the same issue. When using Jellyfin MPV Shim, the issue does not happen at all. It seems like Jellyfin Web is not requesting video buffer far enough ahead, so it often just barely manages to download in time and otherwise stops the until the delayed request is completed.

**Comment by Footsiefat** [comment]
Having the same issue here. Pretty disapointed honestly that there is no solution

**Comment by henrikx** [comment]
Should be fixed by https://github.com/jellyfin/jellyfin-web/pull/2857

**Comment by Footsiefat** [comment]
Yo thx

**Comment by taylor-schneider** [comment]
Also experiencing this issue im afraid

**Comment by JPVenson** [comment]
The issue was mostly resolved for me after upgrading to 10.8.0.

**Comment by srcrist** [comment]
Issue closed as fixed per comments.
