### ISSUE TITLE
eBooks support

### ISSUE THREAD

**Issue by drago-96** [jellyfin/jellyfin#569]
Currently the books "feature" seems pretty broken to me: I'm not able to identify and scrape metadata of any item, and I can't open a book.
I hope we could add some kind of support, in particular:
 * Implement the "Book" and "Author" types (like "Artist" and "Album" in music)
 * Scrape some metadata from some provider (googling I found https://isbndb.com/ and https://openlibrary.org/)
 * Add a viewer for the browser, at least for .pdf and .epub formats

I know it's a lot of work for a feature not many would use, but maybe, in the future...

**Comment by MI3Guy** [comment]
It would be great if there was support for "Series" metadata as well.

**Comment by EraYaN** [comment]
I mean this should probably be a plugin.

But for the mean time: have a look at Calibre. You might want to integrate a calibre plugin, we could never ever match the amount of features that a program like calibre has.

https://calibre-ebook.com/

And for android, I think MoonReader used to be very nice, and just plain iBooks works a treat on iOS.
