### ISSUE TITLE
Problems setting up live tv guide data

### ISSUE THREAD

**Issue by dinki** [jellyfin/jellyfin#57]
I'm trying to set up live tv guide data and when I click on xmltv or Schedules Direct I get this error:

Could not find file '/dashboard-ui/components/tvproviders/.template.html'.

**Comment by drakus72** [comment]
I think it isn't calling the schedulesdirect.template.html file correctly.

**Comment by drakus72** [comment]
Once you add a tuner(s) it should work.

**Comment by dinki** [comment]
I did add the tuner first. I have two hdhomerun devices configured and they do play but I can't configure the guide data

**Comment by drakus72** [comment]
using docker?

**Comment by dinki** [comment]
Correct

**Comment by drakus72** [comment]
is it set to bridge? If so change to host. Was having the same problem messing with it on unraid and once i changed from bridge to host it worked perfectly.

**Comment by dinki** [comment]
Yes. Set to bridge. Will try host tomorrow. Thanks for the tip. 

Does DVR work?

**Comment by drakus72** [comment]
Yes so far in my testing it does.

**Comment by dinki** [comment]
Confirmed that running in host mode does not exhibit the problem but running in bridge mode does exhibit the problem.

**Comment by Li-Ion** [comment]
Its fix with v10.0.1 for me

**Comment by sparky8251** [comment]
Reading this over, its hard to say if this is still an issue. Can this be closed now or not?

**Comment by JustAMan** [comment]
There were some fixes for XmlTv done, so they probably fixed the issues.
@dinki can you please check and close the issue if it is fixed for you?

**Comment by dinki** [comment]
I am continuing to run in host mode which fixed it for me a month ago.  Seems that 10.0.1 fixed Li-Ion's issue so I'm guessing it's safe to close it.  My original problem was resolved so I will close it.
