### ISSUE TITLE
Plugins won't remain disabled

### ISSUE THREAD

**Issue by redactedscribe** [jellyfin/jellyfin#5700]
**Describe the bug**
When I disable a plugin, it reads Status: Restart, and so I shutdown the server and start it up again. Once I'm in the Dashboard, checking the plugins shows that the plugin is now disabled. Restarting the server another time and now checking the plugins, shows that the plugin has been re-enabled. All plugins that I disable get re-enabled ("all" meaning the three that I've been trying to disable). 

**System (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 87
 - Jellyfin Version: 10.7.1 (from [scoop](https://github.com/lukesampson/scoop-extras/blob/master/bucket/jellyfin.json))
 - Installed Plugins: Playback Reporting, Reports, Trakt, others...
 - Storage: local

**Expected behavior**
Plugins should remain disabled.

**Logs**
```json
[INF] [1] Main: Jellyfin version: 10.7.1
[INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, C:\\Users\\<user>\\scoop\\apps\\jellyfin\\current\\data\\log]"]
[INF] [1] Main: Arguments: ["C:\\Users\\<user>\\scoop\\apps\\jellyfin\\current\\system\\jellyfin.dll", "-d", "C:\\Users\\<user>\\scoop\\apps\\jellyfin\\current\\data"]
[INF] [1] Main: Operating system: Windows
[INF] [1] Main: Architecture: X64
[INF] [1] Main: 64-Bit Process: True
[INF] [1] Main: User Interactive: True
[INF] [1] Main: Processor count: 16
[INF] [1] Main: Program data path: C:\Users\<user>\scoop\apps\jellyfin\current\data
[INF] [1] Main: Web resources path: C:\Users\<user>\scoop\apps\jellyfin\current\system\jellyfin-web
[INF] [1] Main: Application directory: C:\Users\<user>\scoop\apps\jellyfin\current\system\
[INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: X:\<path>\jellyfin\cache
...
[INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
...
[INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Skipping disabled plugin 9.0.0.0 of Playback Reporting
[INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Skipping disabled plugin 11.0.0.0 of Reports
[INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Skipping disabled plugin 11.0.0.0 of Trakt
...
[INF] [1] Emby.Server.Implementations.ApplicationHost: Executed all pre-startup entry points in 0:00:00.0913521
[INF] [1] Emby.Server.Implementations.ApplicationHost: Core startup complete
...
[INF] [1] Main: Startup complete 0:00:03.0764291
[INF] [26] Emby.Server.Implementations.ScheduledTasks.TaskManager: StartupTrigger fired for task: Update Plugins
[INF] [26] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queuing task PluginUpdateTask
[INF] [18] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing Update Plugins
[INF] [15] Emby.Server.Implementations.ScheduledTasks.TaskManager: Update Plugins Completed after 0 minute(s) and 1 seconds
```

After second restart:
```json
[INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.PlaybackReporting, Version=9.0.0.0, Culture=neutral, PublicKeyToken=null from C:\Users\<user>\scoop\apps\jellyfin\current\data\plugins\Playback Reporting_9.0.0.0\Jellyfin.Plugin.PlaybackReporting.dll
[INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.Reports, Version=11.0.0.0, Culture=neutral, PublicKeyToken=null from C:\Users\<user>\scoop\apps\jellyfin\current\data\plugins\Reports_11.0.0.0\Jellyfin.Plugin.Reports.dll
[INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Trakt, Version=11.0.0.0, Culture=neutral, PublicKeyToken=null from C:\Users\<user>\scoop\apps\jellyfin\current\data\plugins\Trakt_11.0.0.0\Trakt.dll
...
[INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Playback Reporting 9.0.0.0
[INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Reports 11.0.0.0
[INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Trakt 11.0.0.0
```

**Additional context**
My settings and data (cache/, config/, data/, etc) were originally in use with the stable Windows server (downloaded via https://jellyfin.org/downloads), but then I uninstalled it and installed it via scoop instead. Next, I transferred my settings/data to scoop's install location. The only thing I noticed that was weird was that the Settings > Metadata paths were still pointing to C:\ProgramData\Jellyfin\Server\root\default. Though inadvisable, I edited the library.db and fixed those paths to the new scoop install location. Before I did this, editing the metadata settings for libraries would hang on the rotating saving circle. After the edit, there was no more issue. Maybe something else in my configuration is causing the plugins to re-enable? It's odd that their disabled state saves only for a single restart, else I'd think it's perhaps a matter of no write permission.

Thanks.

**Comment by BaronGreenback** [comment]
Can you disable the plugin, then post the contents of the meta.json file that is in the plugin folder please?

It looks like the wrong state might be being stored.

**Comment by redactedscribe** [comment]
After disabling a plugin and shutting the server down:
```json
{
  "category": "General",
  "changelog": "Add authentication to plugin endpoints\n",
  "description": "Show reports for playback activity",
  "guid": "5c534381-91a3-43cb-907a-35aa02eb9d2c",
  "name": "Playback Reporting",
  "overview": "Collect and show user play statistics",
  "owner": "jellyfin",
  "targetAbi": "10.7.0.0",
  "timestamp": "2020-12-06T00:15:48.0000000Z",
  "version": "9.0.0.0",
  "status": "Disabled",
  "autoUpdate": true,
  "imagePath": ""
}
```

After starting up the server again:
```json
{
  "category": "General",
  "changelog": "Add authentication to plugin endpoints\n",
  "description": "Collect and show user play statistics",
  "guid": "5c534381-91a3-43cb-907a-35aa02eb9d2c",
  "name": "Playback Reporting",
  "overview": "Collect and show user play statistics",
  "owner": "jellyfin",
  "targetAbi": "10.7.0.0",
  "timestamp": "2020-12-06T00:15:48.0000000Z",
  "version": "9.0.0.0",
  "status": "Active",
  "autoUpdate": true,
  "imagePath": ""
}
```

Interestingly, Playback Reporting's description changes once the plugin disables, which may or may not indicate something. I don't know if the others do that, but they do get marked as `"status": "Disabled"`, and automatically re-enabled like Playback Reporting does.

Something else I noticed is that, with the meta.json open in VS Code, the file refreshes itself (sets `"status": "Active"`) after `[INF] [14] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks` appears in the console output. I assume the file refresh in VS Code is immediate.

```json
[INF] [1] Main: Startup complete 0:00:03.1769982
[INF] [8] Emby.Server.Implementations.ScheduledTasks.TaskManager: StartupTrigger fired for task: Update Plugins
[INF] [8] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queuing task PluginUpdateTask
[INF] [10] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing Update Plugins
[INF] [14] Emby.Server.Implementations.ScheduledTasks.TaskManager: Update Plugins Completed after 0 minute(s) and 1 seconds
[INF] [14] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
```

I'm guessing one of the scheduled tasks is causing the plugins to re-enable?

**Comment by redactedscribe** [comment]
> I'm guessing one of the scheduled tasks is causing the plugins to re-enable? Likely the PluginUpdateTask which is the only task out of all the listed scheduled tasks with a trigger of "On application startup".

I disabled the "On application startup" trigger and the plugins remain disabled, no matter how many times I restart the server.

**Comment by BaronGreenback** [comment]
Looks to be a few issues here.

1. The plugin should not be upgraded - so i suspect there is something awry with the version detection.
2. Should we be upgrading disabled plugins?
3. We shouldn't be re-enabling plugins post upgrade. Unless the load state was an error - it should stay the same. (eg, disabled, active)
