### ISSUE TITLE
Resume Audio books not working correctly

### ISSUE THREAD

**Issue by tombomb** [jellyfin/jellyfin#5703]
**Describe the bug**
All my audio books are ripped into single m4b's with some being 13:24:55 or 28:58:04 in the case of mistborn book 2 (this is a long book series).  With the change (https://github.com/jellyfin/jellyfin/pull/4891) books are no longer saving position.  I have done a good amount of testing on it, and it seems like the settings are backwards? 

Setting as below seems to mark books as played after 1 min, instead of marked as played if played till 1 min from the end and starting to save position after 1 min of play. its also listed as continue listening even after 1 second of playing.
![image](https://user-images.githubusercontent.com/544509/113641340-6c61e280-964b-11eb-9c84-b57dc9c45f27.png)

Setting as below seems to allow tracking book progress upto 100 mins (1:40) and then its marked as complete, instead of not marking a book as not played unplayed under 100 mins and marking it as played if its been playing for more then 1 min.
![image](https://user-images.githubusercontent.com/544509/113642418-c6fc3e00-964d-11eb-8af9-a19867a4a982.png)

With the new changes keeping books in a single file makes it impossible to keep track of position of books that are longer then 100 mins.

Judging by the comments on https://github.com/jellyfin/jellyfin/pull/4891/commits/cd979e6b6291d426f3e180e36b5a8ba68c208cbd#diff-c1f87f62ea1d5291e0845030039c65395f16744a78716712abd7c9f281f0ae60R308 and https://github.com/jellyfin/jellyfin/pull/4891/commits/cd979e6b6291d426f3e180e36b5a8ba68c208cbd#diff-c1f87f62ea1d5291e0845030039c65395f16744a78716712abd7c9f281f0ae60R302 it seems like some of the backend math needs to be reworked.

**System (please complete the following information):**
 - OS: Unbuntu
 - Virtualization: Docker
 - Clients: Browser & Android
 - Browser: Chrome 89
 - Jellyfin Version: 10.7.1 
 - Playback: [Direct Play, Remux, Direct Stream, Transcode] 
 - Installed Plugins: [e.g. none, Fanart, Anime, etc.]
 - Reverse Proxy: traefik 2
 - Base URL: none
 - Networking: Bridge/NAT
 - Storage: local

**To Reproduce**

1. Go to an audio book and start playing it
2. Scrub to part of the book where you left off (past 100 mins)
3. let it play for a min or two to trigger the saving of location
4. hit stop
5. go home to see that save location is not saved

**Expected behavior**
Save location on books correctly

**Logs**

**Screenshots**

**Additional context**
I do love the idea of splitting out books from normal content, but this little bug needs to get fixed to make books work.

**Comment by Artiume** [comment]
https://github.com/jellyfin/jellyfin/blob/1361ccd9ea54c521de7b29ebc4d15fb3214c05da/Emby.Server.Implementations/Library/UserDataManager.cs#L254

Might need to invert the logic here,  sorry about that!
