### ISSUE TITLE
Websockets don't get de-referenced properly in some cases, breaking websockets

### ISSUE THREAD

**Issue by heyhippari** [jellyfin/jellyfin#5705]
**Describe the bug**

Not sure how to reproduce it, but sometimes, websockets are seemingly not de-referenced properly.

Broadcast messages, like the ones generated by LibraryChangeNotifier, fail to send due to trying to send one through a non-existing socket connection (See logs below)

Restarting the server fixes it, probably due to the pool of websocket being cleaned at reboot?

**System (please complete the following information):**
 - OS: Arch
 - Virtualization: KVM on Proxmox
 - Clients: Browser, Vue
 - Browser: Firefox 84
 - Jellyfin Version: 10.7.1
 - Playback: n/a
 - Installed Plugins: AniDB, Apple Music, AudioDB, Fanart, Last.fm, Musicbrainz, OMDb
 - Reverse Proxy: Nginx
 - Base URL: none
 - Networking: Host
 - Storage: NFS

**To Reproduce**

1. Somehow manage to break a websocket. Not sure how.
2. Open another websocket connection.
3. No broadcast messages are sent.

**Expected behavior**

Websockets should be properly de-references and/or the message sender should be smart enough to not choke on an invalid socket.

**Logs**

![image](https://user-images.githubusercontent.com/19396809/113692430-d6bb6700-96cd-11eb-8966-3b7e49cd1c43.png)

**Comment by MrTimscampi** [comment]
I doubt this has been fixed, since there was no changes to the message system.

**Comment by cvium** [comment]
I also can't reproduce it

**Comment by MrTimscampi** [comment]
It was found when adding websocket support to Vue, so I'm guessing it's fairly difficult to reproduce as you'd have to break Vue in a specific way.

**Comment by srcrist** [comment]
Is anyone able to confirm that this issue still exists in 10.8.11? This issue has become quite stale and confirmation or closure is probably warranted, at this point.
