### ISSUE TITLE
Unable to use the new version of Jellyfin

### ISSUE THREAD

**Issue by Osolemio44** [jellyfin/jellyfin#5715]
I So far I was using jellyfin version 10.6.4 but had problems in some videos where they were interrupted and there was no way to continue watching them. So today I have decided to update to the latest version. My Jellyfin server is a Docker image inside a Synology NAS. As in your documentation you do not have a tutorial on how to update a version of jellyfin in docker using the GUI, I deleted the image that I had installed and installed the most recent one. I think it's 10.7.1 but I can't be sure since I can't find the version number anywhere. The problem is that no matter what you do, the web is blocked and there is no way to use it. I attach a screenshot so you can see what state the web is in. I have already deleted and reinstalled the latest version 2 times. What do I do? (I don't have any Docker knowledge)
![chrome_0h600dqdaS](https://user-images.githubusercontent.com/55595063/113831376-d5e70b80-9787-11eb-85f2-bf086c36a8ab.jpg)
I selected te jellyfin latest version in the Registry window of Docker in my Synology ( https://registry.hub.docker.com/r/jellyfin/jellyfin/)

**Comment by ikomhoog** [comment]
try to clear your browser cache

**Comment by Osolemio44** [comment]
thanks. 
clearing with mayus+F5 didnt work, but clearing ALL cache from the browser config did work.
