### ISSUE TITLE
Chromecast with Google TV: No audio on most Dolby 5.1 files, one known working file.

### ISSUE THREAD

**Issue by TaakoMagnusen** [jellyfin/jellyfin#5720]
**Media Info of the file**

File 1 - The Wolf of Wallstreet (Works **most** of the time. randomly takes forever to load and i need to force close app):

```
The Wolf of Wallstreet 2013 BluRay 1080p DD5.1 x265-D3FiL3R
Container mkv
Path /media/The Wolf Of Wallstreet/The Wolf of Wallstreet 2013 BluRay 1080p DD5.1 x265-D3FiL3R.mkv
Size 3839 MB

Video
Title 1080p HEVC SDR
Codec HEVC
Profile Main
Level 150
Resolution 1920x1080
Aspect ratio 16:9
Interlaced No
Framerate 23.976025
Bitrate 2983 kbps
Video range SDR
Pixel format yuv420p
Ref frames 1


Audio
Title English - Dolby Digital - 5.1 - Default
Language eng
Codec AC3
Layout 5.1
Channels 6 ch
Bitrate 512 kbps
Sample rate 48000 Hz
Default Yes
```

File 2 - The Lego Movie 2(Video plays without audio with "Downmix to Stereo" **disabled**, **refuses to play at all with that setting enabled**):

```
The.Lego.Movie.2.The.Second.Part.2019.1080p.BluRay.H264.AC3.DD5.1

Container mp4
Path /media/The.Lego.Movie.Collection.1080p.BluRay.H264.AC3.DD5.1.Will1869/The.Lego.Movie.2.The.Second.Part.2019.1080p.BluRay.H264.AC3.DD5.1.mp4
Size 3088 MB

Video
Title 1080p H264 SDR
Codec H264
Codec tag avc1
AVC Yes
Profile Main
Level 40
Resolution 1920x804
Aspect ratio 2.40:1
Interlaced No
Framerate 23.976025
Bitrate 3569 kbps
Bit depth 8 bit
Video range SDR
Color space bt709
Color transfer bt709
Color primaries bt709
Pixel format yuv420p
Ref frames 1
NAL 4

Audio
Title English - Dolby Digital - 5.1 - Default
Language eng
Codec AC3
Codec tag ac-3
Layout 5.1
Channels 6 ch
Bitrate 448 kbps
Sample rate 48000 Hz
Default Yes
```

File 3 - The Lego Ninjago Movie (same behavior as File 2
```
The.LEGO.Ninjago.Movie.2017.1080p.BluRay.H264.AC3.DD5.1
Container mp4
Path /media/The.Lego.Movie.Collection.1080p.BluRay.H264.AC3.DD5.1.Will1869/The.LEGO.Ninjago.Movie.2017.1080p.BluRay.H264.AC3.DD5.1.mp4
Size 3103 MB

Video
Title 1080p H264 SDR
Codec H264
Codec tag avc1
AVC Yes
Profile Main
Level 40
Resolution 1920x808
Aspect ratio 2.40:1
Interlaced No
Framerate 23.976025
Bitrate 3817 kbps
Bit depth 8 bit
Video range SDR
Color space bt709
Color transfer bt709
Color primaries bt709
Pixel format yuv420p
Ref frames 1
NAL 4

Audio
Title English - Dolby Digital - 5.1 - Default
Language eng
Codec AC3
Codec tag ac-3
Layout 5.1
Channels 6 ch
Bitrate 448 kbps
Sample rate 48000 Hz
Default Yes

``` 

**Logs**
[log_20210407.log](https://github.com/jellyfin/jellyfin/files/6272909/log_20210407.log)

**FFmpeg Logs**
[FFmpeg.Transcode-2021-04-07_08-44-13_9a6828d8a0cabcd9cdf45307480b0014_2e20f45f.log](https://github.com/jellyfin/jellyfin/files/6272912/FFmpeg.Transcode-2021-04-07_08-44-13_9a6828d8a0cabcd9cdf45307480b0014_2e20f45f.log)
[FFmpeg.Transcode-2021-04-07_08-44-14_9a6828d8a0cabcd9cdf45307480b0014_24cbf8cc.log](https://github.com/jellyfin/jellyfin/files/6272913/FFmpeg.Transcode-2021-04-07_08-44-14_9a6828d8a0cabcd9cdf45307480b0014_24cbf8cc.log)
[FFmpeg.Transcode-2021-04-07_08-44-14_9a6828d8a0cabcd9cdf45307480b0014_78427c31.log](https://github.com/jellyfin/jellyfin/files/6272914/FFmpeg.Transcode-2021-04-07_08-44-14_9a6828d8a0cabcd9cdf45307480b0014_78427c31.log)
[FFmpeg.Transcode-2021-04-07_08-44-32_9a6828d8a0cabcd9cdf45307480b0014_a946fd93.log](https://github.com/jellyfin/jellyfin/files/6272915/FFmpeg.Transcode-2021-04-07_08-44-32_9a6828d8a0cabcd9cdf45307480b0014_a946fd93.log)
[FFmpeg.Transcode-2021-04-07_08-44-33_9a6828d8a0cabcd9cdf45307480b0014_645691a9.log](https://github.com/jellyfin/jellyfin/files/6272916/FFmpeg.Transcode-2021-04-07_08-44-33_9a6828d8a0cabcd9cdf45307480b0014_645691a9.log)
[FFmpeg.Transcode-2021-04-07_08-44-34_9a6828d8a0cabcd9cdf45307480b0014_f584ecca.log](https://github.com/jellyfin/jellyfin/files/6272917/FFmpeg.Transcode-2021-04-07_08-44-34_9a6828d8a0cabcd9cdf45307480b0014_f584ecca.log)
[FFmpeg.Transcode-2021-04-07_08-44-43_9a6828d8a0cabcd9cdf45307480b0014_99491ba7.log](https://github.com/jellyfin/jellyfin/files/6272918/FFmpeg.Transcode-2021-04-07_08-44-43_9a6828d8a0cabcd9cdf45307480b0014_99491ba7.log)
[FFmpeg.Transcode-2021-04-07_08-44-44_9a6828d8a0cabcd9cdf45307480b0014_7ff7532f.log](https://github.com/jellyfin/jellyfin/files/6272919/FFmpeg.Transcode-2021-04-07_08-44-44_9a6828d8a0cabcd9cdf45307480b0014_7ff7532f.log)
[FFmpeg.Transcode-2021-04-07_08-44-45_9a6828d8a0cabcd9cdf45307480b0014_df64f078.log](https://github.com/jellyfin/jellyfin/files/6272920/FFmpeg.Transcode-2021-04-07_08-44-45_9a6828d8a0cabcd9cdf45307480b0014_df64f078.log)
[FFmpeg.Transcode-2021-04-07_08-44-56_9a6828d8a0cabcd9cdf45307480b0014_fd62ca51.log](https://github.com/jellyfin/jellyfin/files/6272921/FFmpeg.Transcode-2021-04-07_08-44-56_9a6828d8a0cabcd9cdf45307480b0014_fd62ca51.log)
[FFmpeg.Transcode-2021-04-07_08-44-57_9a6828d8a0cabcd9cdf45307480b0014_5e19d515.log](https://github.com/jellyfin/jellyfin/files/6272922/FFmpeg.Transcode-2021-04-07_08-44-57_9a6828d8a0cabcd9cdf45307480b0014_5e19d515.log)
[FFmpeg.Transcode-2021-04-07_08-44-57_9a6828d8a0cabcd9cdf45307480b0014_35dac034.log](https://github.com/jellyfin/jellyfin/files/6272923/FFmpeg.Transcode-2021-04-07_08-44-57_9a6828d8a0cabcd9cdf45307480b0014_35dac034.log)
[FFmpeg.Transcode-2021-04-07_08-45-10_9a6828d8a0cabcd9cdf45307480b0014_731ee4a1.log](https://github.com/jellyfin/jellyfin/files/6272924/FFmpeg.Transcode-2021-04-07_08-45-10_9a6828d8a0cabcd9cdf45307480b0014_731ee4a1.log)
[FFmpeg.Transcode-2021-04-07_08-45-11_9a6828d8a0cabcd9cdf45307480b0014_9088e2c3.log](https://github.com/jellyfin/jellyfin/files/6272926/FFmpeg.Transcode-2021-04-07_08-45-11_9a6828d8a0cabcd9cdf45307480b0014_9088e2c3.log)

**Stats for Nerds Screenshots**
N/A

**Server System (please complete the following information):**
 - OS: Unraid (Linux)
 - Jellyfin Version: 10.7.0
 - Hardware settings & device: Intel i5-10400
 - Reverse proxy: None
 
**Client System (please complete the following information):**
 - Device: [Chromecast with Google TV](https://store.google.com/product/chromecast_google_tv) 
 - OS: Android TV
 - Client: Android TV Jellyfin App 0.11.5 (**The native android TV app, not chromecasting**)

**BACKGROUND**

I have just started using Jellyfin and only have a handful of files on my server right now to try. But I noticed that many files with Dolby 5.1 audio do not play audio out of the Chromecast with Google TV, even though the video works perfectly. I have one file (File 1: `The Wolf of Wallstreet 2013 BluRay 1080p DD5.1 x265`) where the audio and video work perfectly. But other files i tried (Files 2 and 3) which also have Dolby 5.1 audio play video fine but no audio comes out.

Someone on the unofficial Jellyfin discord mentioned my device may not support Dolby 5.1 audio codec (which would be suspicious considering The Wolf Of Wallstreet had audio), and suggested i try "Downmix to Stereo". According to many sources (https://forums.plex.tv/t/what-codecs-are-supported-on-the-new-google-tv-chromecast/638378) the Chromecast With Google TV **does support Dobly 5.1 audio** but i tried "Downmix to Stereo" anyway to see what happened. With that option enabled files 2 and 3 don't start at all! It results in a bunch of errors popping up that said "Playback Error Encountered... Trying again" until eventually it says "Too many errors encountered".

I'm trying to understand:

1) Why The Wolf Of Wallstreet file works perfectly and the Lego movies do not play audio even though they are both Dolby 5.1
2) Why "Downmix to Stereo" causes this error toast preventing any video/audio playback
3) How to get my files to actually play.

I attached a whole bunch of logs above and here are my manual notes from each trial:

Direct Audio
Bitstream DTS audio disabled
```
8:33 - wolf of wallstreet
long loading period then crash

8:35 - lego ninjago
video plays
no audio

8:35 - wolf of wallstreet
video and audio works perfect

8:36 - lego movie 2
video plays
no audio

8:37 wolf of wallsrreet
infinite loading period, had to exit to home screen, got black screen when i opened Jellyfin again, had to force close jellyfin app

8:40 - wolf of wallstreet
video plays and audio plays perfectly
```

Changing setting to "Downmix to stereo"
Bitstream DTS audio still disabled

```
8:42 - wolf of wallstreet
infinite load, had to force stop app

8:43 - wolf of wallstreet
video and audio work fine

8:44 - lego movie 2
Playback error encountered, will retry

8:44:30 - lego movie 2
Playback error encountered, will retry

8:44:41 - lego movie 2
Playback error encountered, will retry

8:44:54 - lego movie 2
Playback error encountered, will retry

8:45:00 - lego movie 2
Playback error encountered, will retry

8:45:30 - wolf of wallstreet
infinite load, had to force stop app
```

For some reason not all of the ffmpeg logs were captured, i can't find any of the ffmpeg logs before 8:44; i'm not sure why this is, maybe its because the trials before 8:44 didn't use "Downmix to Stereo" so ffmpeg was not needed?

I'd also like to note that all these files work perfectly when i switch from my Chromecast with google TV to my Macbook Pro running chrome.

**Comment by cvium** [comment]
It might be related to https://github.com/jellyfin/jellyfin/issues/5591

**Comment by TaakoMagnusen** [comment]
should i have posted this in https://github.com/jellyfin/jellyfin-androidtv ?

**Comment by TaakoMagnusen** [comment]
I've confirmed this is an issue with the Android TV Jellyfin app. I installed the Jellyfin Add-on for Kodi using the steps outlined [here](https://jellyfin.org/docs/general/clients/kodi.html#install-jellyfin-for-kodi-add-on) and all my media files play perfectly fine.

So the question is: what in the Jellyfin Android TV app is causing the issue? Is there any way for me to collect debug logs of the android TV app? Maybe take a bugreport and offload to my computer using ADB? How do you capture a bugreport on Chromecast with Google TV?
