### ISSUE TITLE
boot loop when port is set to 80

### ISSUE THREAD

**Issue by altered-beast** [jellyfin/jellyfin#5723]
server boot loops when port is switched to 80 

**System (please complete the following information):**
 - OS: ubuntu 20.04
 - Virtualization: running on a vultr vps
 - Clients: one person on linux another on windows
 - Browser: firefox
 - Jellyfin Version: 10.7.1
 - Playback: n/a
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: none
 - Networking: i think NAT but not entirely sure
 - Storage: local

**To Reproduce**
set port to 80 in config page
save settings 
restart ( sudo systemctl restart jellyfin)
you will then see in systemctl status it has failed to start and the amount of processes will rise then it will crash
(note only tested in http)

**Expected behavior**
jellyfin runs on port 80 without boot looping

**Logs**
un able to provide at this moment as the server is offline i will try to download them when it is next up

**Comment by crobibero** [comment]
This sounds like a permissions issue. As far as I know the service needs to be running as root in order to actually listen on any port under 1024

**Comment by altered-beast** [comment]
that would make sense ill test when the server is next up

**Comment by zynexiz** [comment]
Jellyfin runs on it's own user and don't have privileges to use ports below 1024 (only root have that as mentioned before). It's not advisable to run the service as root though, the best practise is to use a reverse proxy instead. Then you can use port 80 without issue, and also secure the server in a better way.

**Comment by altered-beast** [comment]
tested running it as root and worked prefectly. will definetly consider using reverse proxy in future
