### ISSUE TITLE
Live TV - concurrent stream - not live

### ISSUE THREAD

**Issue by sebitr** [jellyfin/jellyfin#5724]
**Describe the bug**
Steps to reproduce:
1) Start a live TV stream with a 1st user
2) Wait (20 minutes for example)
3) Start a live TV stream for same channel with a 2nd user
—> it’s impossible to watch the channel live for 2nd user. Playback starts when first user has started the first stream (20 minutes in the example)

**System (please complete the following information):**
 - OS: ubuntu
 - Virtualization: docker
 - Clients: Browser, Android, ios
 - Jellyfin Version: 10.7.0
 - Storage: local
- TV source: m3u

**Comment by skug67** [comment]
I'm having the same problem using HDHomeRun (even when additional tuners are available).

**Comment by kellcomnet2** [comment]
+1 with HDHomeRun, it seems like it starts playing the start of a video file that allows for rewinding live tv. Sometimes I can seek to the end but not always.

**Comment by Asdoos** [comment]
Yes - please Fix that... :)

**Comment by phips2** [comment]
I have the same problem. If a second user also start the LiveTv he will start at the beginning of the first user. The CPU runs nearly at 100% to get the transcoding to the current play time of the first user. If the CPU is potenial you can foreward to live playing after about one minute. Like Asdoos said, the bug not exists on 10.6.4.

**Comment by asgardius** [comment]
I'm using live tv feature to listen my personal Icecast radio station. This problem still appear at Jellyfin 10.7.5. Sometimes my server sends me a replay of my radio station instead a live transmission without an active session. As a quick fix i clear transcode cache and restart my server. Here is my server log. My server appear as jellyfin.example.com, my radio station as icecast.example.com and client IP address as 127.0.0.1
[jellyfin.log](https://github.com/jellyfin/jellyfin/files/6502438/jellyfin.log)

**Comment by exterrestris** [comment]
Doesn't even need to be a second user - starting playback on a channel that is currently recording does exactly the same.

**Comment by nikhil96widhani** [comment]
I can confirm the same issue happening with me. Please fix

**Comment by nikhil96widhani** [comment]
I have done some tests and it seems like jellyfin streams from the start of TS buffer but if we fast forward slider to end it becomes live again. We can only fast forward on browser mode but there is no option in android tv/app . If livestream can play from end of the buffer instead of start then this might be fixed. I am just trying to give suggestions not sure if this will work or make sense in terms of development perspective.

**Comment by nikhil96widhani** [comment]
> +1 with HDHomeRun, it seems like it starts playing the start of a video file that allows for rewinding live tv. Sometimes I can seek to the end but not always.

Agree to this

**Comment by cvium** [comment]
If someone is feeling adventurous they can test this PR https://github.com/jellyfin/jellyfin/pull/6538
