### ISSUE TITLE
List of favorites incomplete

### ISSUE THREAD

**Issue by Marenz** [jellyfin/jellyfin#5727]
**Describe the bug**
Since my update to 10.7.0, my list of favorites is incomplete (or it was completely gone, can't say for sure).
However upon looking at individual former favorite artists, they STILL are marked as favorite. The filter just doesn't list them anymore.
If I un-favorite them and then favorite them again, they show up.

**System (please complete the following information):**
 - OS: OpenSuse 10.2 Leap
 - Virtualization: Docker
 - Clients: All.
 - Browser: Vivaldi 3.7.2218.45
 - Jellyfin Version: Problem visible starting at 10.7.0. Now at 10.7.1
 - Playback: -
 - Installed Plugins: none
 - Reverse Proxy: nginx
 - Base URL: none
 - Networking: NAT
 - Storage: local

**To Reproduce**

1. Go to any view that displays favorites.
2. See incomplete list

**Expected behavior**
A full list of all my favorite artists.

**Additional context**
I manually looked at the db file "library.db" and did `select key from UserDatas where isFavorite = true;` and this did list *ALL* of my favorites. I could not notice any difference in the rows that showed up and that didn't show up in the jellyfin view.

**Comment by Marenz** [comment]
Small update: My fav. artists that don't show up in the list no longer show up as fav. when I go to their respective artist page.
I believe this happened after I updated 10.7.0 -> 10.7.1.

**Comment by Marenz** [comment]
The issue still exists.

**Comment by HybridSarcasm** [comment]
This has been open quite a while. Can this be re-produced with the current build? If so, please update the bug report details. Thanks!

**Comment by Marenz** [comment]
It's fine for me to close it for now, I can re-open it when and if I see it again

**Comment by srcrist** [comment]
Closing issue as stale. Feel free to open another issue if the problem persists in 10.8.11+
