### ISSUE TITLE
Wrong covers for libraries

### ISSUE THREAD

**Issue by definitio** [jellyfin/jellyfin#573]
**Describe the bug**
Covers for libraries include thumbnails for media from other libraries with same type.

**To Reproduce**
1. Create library 'foo' with type 'TV Shows' (for example, same behaviour with other types)
2. Add media 'a' and 'b' to it
3. Create library 'bar' with type 'TV Shows' (must be same as previous)
4. Add media 'c' and 'd' to it
5. Covers of 'foo' and 'bar' will not match its content.

**Expected behavior**
Covers should contain only thumbnails for this library.

**Logs**
Please paste any log errors.

**Screenshots**
This is content of my library "Сериалы":
![screenshot_20190113_110548](https://user-images.githubusercontent.com/37266727/51087104-2bc6d780-1768-11e9-925f-6ee57d3442ff.png)

Cover for library "Сериалы" has thumbnails for its content and content of library "Аниме", but library "Аниме" has thumbnails only from library "Сериалы":
![screenshot_20190113_011409](https://user-images.githubusercontent.com/37266727/51087106-2d909b00-1768-11e9-8466-3e5bae46cf83.png)

**System (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Chrome
 - Jellyfin Version: 10.0.1

**Additional context**
Tried to delete metadata and covers. New covers always have same problems.

**Comment by bobberb** [comment]
Confirmed here as well.

**Comment by rpatterson** [comment]
I can confirm this issue here too.  Latest Jellyfin from the Ubuntu apt repo running under up-to-date Ubuntu disco.  Happened on my first try with Jellyfin, IOW on a fresh Jellyfin scan of my existing Emby library.

**Comment by rpatterson** [comment]
It looks like this might be pretty low on the list.  I'm very eager to switch to Jellyfin, but unfortunately this bug is a blocker for me as there are cover images for one library that I definitely don't want all users to see.  ;-)  I'd love to support this open source project as an occasional contributor, so maybe I'll try my hand at fixing this.  Any tips as to where to start looking for this bug would be a big help, @nvllsvm, @joshuaboniface , @anthonylavado?

**Comment by 12nick12** [comment]
I also have this issue. I have a library that no-one needs to see

**Comment by anthonylavado** [comment]
I’ll try to look at it, but I also have no idea where it is at the moment.

**Comment by anthonylavado** [comment]
Initial reports are that PR #680 may have fixed this. Will try to replicate and then patch to test.

**Comment by anthonylavado** [comment]
Currently running a test build with #680 included. This issue doesn't appear to occur anymore. Watch for this in the next release.

**Comment by hawken93** [comment]
Cool :) there's some more things to fix with the library thumbnail that it will include the same picture more than once, but that for another issue

**Comment by definitio** [comment]
Fixed in 10.2.0.
