### ISSUE TITLE
Sort albums by last played (of any song on it)

### ISSUE THREAD

**Issue by AndreCarvalho** [jellyfin/jellyfin#5745]
Being able to re-listen to the recently played albums is one of my most missed features from Subsonic. It's possible to do something similar but on the Songs tab.
I've looked at the code and it seems it that this is done with `DatePlayedComparer`. Would this implementation work as is with albums as the `BaseItem`, and thus is just a matter of exposing the UI widget? Or would it need a different implementation?
Thanks

**Comment by Bond-009** [comment]
Feature requests go here: https://features.jellyfin.org/
