### ISSUE TITLE
Unable to bind to loopback

### ISSUE THREAD

**Issue by BaronGreenback** [jellyfin/jellyfin#5761]
I'm having the same issue described in the original post. I am trying to bind to localhost but instead Jellyfin is binding to all addresses. This is a security and privacy issue.

```
[INF] Defined LAN addresses : [127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[INF] Defined LAN exclusions : []
[INF] Using LAN addresses: [127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[INF] Using bind addresses: []
[INF] Using bind exclusions: []
...
[INF] Kestrel listening on Any IP4 Address
```

I was looking at the code and it appears as though the config isn't getting parsed correctly: https://github.com/jellyfin/jellyfin/blob/0e5d4a3bcfaa07c3cd1c0085a5940b1c13f1ae20/Jellyfin.Networking/Manager/NetworkManager.cs#L926-L950. All that code should do is take the addresses provided and add to them, but the result is empty. So I would think that somehow the values aren't being read from the config as expected.

```xml
<!-- relevant part of network.xml -->
<IgnoreVirtualInterfaces>false</IgnoreVirtualInterfaces>
<LocalNetworkSubnets />
<LocalNetworkAddresses>
	<string>127.0.0.1</string>
</LocalNetworkAddresses>
```

```xml
<!-- relevant part of system.xml -->
<IgnoreVirtualInterfaces>false</IgnoreVirtualInterfaces>
<LocalNetworkSubnets />
<LocalNetworkAddresses>
	<string>127.0.0.1</string>
</LocalNetworkAddresses>
```

It appears as though a lot of network settings are written to both config files. It is confusing to me which is used. (Although in this case it appears that none are).

The fact that this accidentally included all addresses is also concerning. Maybe the configuration should be updated to require an explicit `0.0.0.0` or `::` to listen on all addresses? That way this can't happen again and it will be harder to misconfigure.

**Comment by BaronGreenback** [comment]
https://github.com/kevincox : moved this to it's own issue.

**Comment by BaronGreenback** [comment]
Could you let me know what version of JF you are running please?

The settings in system.xml are obsolete. There is a PR in to remove them.

**Comment by BaronGreenback** [comment]
Have just run your config here - and it working as expected. First thing that springs to mind is that .net isn't returning the localhost address as being active on any of the interfaces. ("invalid" interfaces addresses are removed as part of the startup).

**Comment by kevincox** [comment]
I am running `10.7.1`.

My full network.xml:

```
			<NetworkConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
				<RequireHttps>false</RequireHttps>
				<BaseUrl />
				<PublicHttpsPort>443</PublicHttpsPort>
				<HttpServerPortNumber>8096</HttpServerPortNumber>
				<HttpsPortNumber>1</HttpsPortNumber>
				<EnableHttps>false</EnableHttps>
				<PublicPort>80</PublicPort>
				<UPnPCreateHttpPortMap>false</UPnPCreateHttpPortMap>
				<EnableIPV6>false</EnableIPV6>
				<EnableIPV4>true</EnableIPV4>
				<EnableSSDPTracing>false</EnableSSDPTracing>
				<UDPSendCount>0</UDPSendCount>
				<UDPSendDelay>100</UDPSendDelay>
				<IgnoreVirtualInterfaces>false</IgnoreVirtualInterfaces>
				<VirtualInterfaceNames>vEthernet*</VirtualInterfaceNames>
				<GatewayMonitorPeriod>60</GatewayMonitorPeriod>
				<TrustAllIP6Interfaces>false</TrustAllIP6Interfaces>
				<PublishedServerUriBySubnet />
				<AutoDiscoveryTracing>false</AutoDiscoveryTracing>
				<AutoDiscovery>false</AutoDiscovery>
				<RemoteIPFilter />
				<IsRemoteIPFilterBlacklist>false</IsRemoteIPFilterBlacklist>
				<EnableUPnP>false</EnableUPnP>
				<EnableRemoteAccess>true</EnableRemoteAccess>
				<LocalNetworkSubnets />
				<LocalNetworkAddresses>
					<string>127.0.0.1</string>
				</LocalNetworkAddresses>
				<KnownProxies />
			</NetworkConfiguration>
```

Log:

```
[INF] Jellyfin version: 10.7.1
[INF] Environment Variables: ["[JELLYFIN_kestrel__socket, true]", "[JELLYFIN_hostwebclient, false]", "[JELLYFIN_LOG_DIR, /var/lib/jellyfin/log]", "[JELLYFIN_DefaultRedirectPath, web/]", "[JELLYFIN_kestrel__socketPath, /run/jellyfin/sock]"]
[INF] Arguments: ["/nix/store/2mdhjzkf258i6915b4bak5nw7j10h357-jellyfin-10.7.1/opt/jellyfin/jellyfin.dll", "--ffmpeg", "/nix/store/rv7fjxcx143vlq3hbpqb9b02p51ivi3a-ffmpeg-4.3.2-bin/bin/ffmpeg", "--datadir", "/var/lib/jellyfin", "--cachedir", "/var/cache/jellyfin"]
[INF] Operating system: Linux
[INF] Architecture: X64
[INF] 64-Bit Process: True
[INF] User Interactive: True
[INF] Processor count: 4
[INF] Program data path: /var/lib/jellyfin
[INF] Web resources path: /nix/store/2mdhjzkf258i6915b4bak5nw7j10h357-jellyfin-10.7.1/opt/jellyfin/jellyfin-web
[INF] Application directory: /nix/store/2mdhjzkf258i6915b4bak5nw7j10h357-jellyfin-10.7.1/opt/jellyfin/
[INF] Setting cache path: /var/cache/jellyfin
[INF] Defined LAN addresses : [127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[INF] Defined LAN exclusions : []
[INF] Using LAN addresses: [127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[INF] Using bind addresses: []
[INF] Using bind exclusions: []
[INF] Loading assemblies
[INF] Loaded assembly MediaBrowser.Plugins.SmtpNotifications, Version=9.0.0.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/Email_9.0.0.0/MediaBrowser.Plugins.SmtpNotifications.dll
[INF] Loaded assembly MailKit, Version=2.10.0.0, Culture=neutral, PublicKeyToken=4e064fe7c44a8f1b from /var/lib/jellyfin/plugins/Email_9.0.0.0/MailKit.dll
[INF] Loaded assembly BouncyCastle.Crypto, Version=1.8.8.0, Culture=neutral, PublicKeyToken=0e99375e54769942 from /var/lib/jellyfin/plugins/Email_9.0.0.0/BouncyCastle.Crypto.dll
[INF] Loaded assembly MimeKit, Version=2.10.0.0, Culture=neutral, PublicKeyToken=bede1c8a46c66814 from /var/lib/jellyfin/plugins/Email_9.0.0.0/MimeKit.dll
[INF] Loaded assembly Jellyfin.Plugin.OpenSubtitles, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/Open Subtitles_10.0.0.0/Jellyfin.Plugin.OpenSubtitles.dll
[INF] Loaded assembly OpenSubtitlesHandler, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/Open Subtitles_10.0.0.0/OpenSubtitlesHandler.dll
[INF] Loaded assembly Trakt, Version=11.0.0.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/Trakt_11.0.0.0/Trakt.dll
[INF] Loaded plugin: Email Notifications 9.0.0.0
[INF] Loaded plugin: Open Subtitles 10.0.0.0
[INF] Loaded plugin: Trakt 11.0.0.0
[INF] Loaded plugin: OMDb 10.7.1.0
[INF] Loaded plugin: MusicBrainz 10.7.1.0
[INF] Loaded plugin: AudioDB 10.7.1.0
[INF] Kestrel listening on Any IP4 Address
[INF] Kestrel listening to unix socket /run/jellyfin/sock
```

**Comment by kevincox** [comment]
Is there a reason to remove invalid interface addresses? It seems like that will be "handled" when Jellyfin tries to bind and it fails. No need to try and be "smart" about it.

**Comment by 3sychk** [comment]
Possible workaround would be be to run it in a docker and only expose the port(s) to localhost ( -p 127.0.0.1:8096:8096)

**Comment by BaronGreenback** [comment]
Haved tested this on my system as well as mocking you network settings - and localhost is being selected correctly.

The onlly thing that it can be is _bindAddresses = CreateIPCollection(lanAddresses).Union(_interfaceAddresses); 

I''ll throw some more test units up (which are run cross platform) to see if i can trace down the issue.

**Comment by kevincox** [comment]
Hmm, it appears that `Union` actually performs an intersection...

https://github.com/jellyfin/jellyfin/blob/a890a8509228f6a357a6986549afc492da74b146/MediaBrowser.Common/Net/NetworkExtensions.cs#L232-L255

**Comment by kevincox** [comment]
I'm still kind of bewildered by all of this code. I can't find out *why* it is doing what it is doing. It seems to me it should be simple. I say what IP to bind and it calls with that address. Instead the code is looping around in circles doing IDK what and ultimately failing. Am I missing a reason for this or can most of this code just be removed?

**Comment by BaronGreenback** [comment]
It's validating the addresses that have been entered actually exist in the address ranges on the network cards.

Stops the system from crashing when an _invalid_ ip is entered - which in turn reduces the number of support calls here.

**Comment by BaronGreenback** [comment]
Can you enable debug logging, restart JF and re-upload the startup log please?

Network debugging is enabled by editting _logging.default.json_ and adding the line _"Jellyfin.Networking.Manager.NetworkManager": "Debug",_ under _Override_

```
{
    "Serilog": {
        "MinimumLevel": {
            "Default": "Information",
            "Override": {
		"Jellyfin.Networking.Manager.NetworkManager": "Debug",
```

**Comment by kevincox** [comment]
> It's validating the addresses that have been entered actually exist in the address ranges on the network cards.

This will be done by the OS when you try to bind the socket.

> Stops the system from crashing when an invalid ip is entered 

Crashing due to invalid configuration is much preferable to falling back to a less secure configuration.

> which in turn reduces the number of support calls here.

Not getting support calls because people don't know that something is broken isn't exactly solving the problem.

**Comment by kevincox** [comment]
```
[INF] Jellyfin version: 10.7.1
[INF] Environment Variables: ["[JELLYFIN_kestrel__socketPath, /run/jellyfin/sock]", "[JELLYFIN_LOG_DIR, /var/lib/jellyfin/log]", "[JELLYFIN_hostwebclient, false]", "[JELLYFIN_kestrel__socket, true]", "[JELLYFIN_DefaultRedirectPath, web/]"]
[INF] Arguments: ["/nix/store/2mdhjzkf258i6915b4bak5nw7j10h357-jellyfin-10.7.1/opt/jellyfin/jellyfin.dll", "--ffmpeg", "/nix/store/rv7fjxcx143vlq3hbpqb9b02p51ivi3a-ffmpeg-4.3.2-bin/bin/ffmpeg", "--datadir", "/var/lib/jellyfin", "--cachedir", "/var/cache/jellyfin"]
[INF] Operating system: Linux
[INF] Architecture: X64
[INF] 64-Bit Process: True
[INF] User Interactive: True
[INF] Processor count: 4
[INF] Program data path: /var/lib/jellyfin
[INF] Web resources path: /nix/store/2mdhjzkf258i6915b4bak5nw7j10h357-jellyfin-10.7.1/opt/jellyfin/jellyfin-web
[INF] Application directory: /nix/store/2mdhjzkf258i6915b4bak5nw7j10h357-jellyfin-10.7.1/opt/jellyfin/
[INF] Setting cache path: /var/cache/jellyfin
[DBG] Refreshing interfaces.
[DBG] Discovered 1 interfaces.
[DBG] Interfaces addresses : [192.168.0.250/24]
[DBG] Refreshing LAN information.
[DBG] Using LAN interface addresses as user provided no LAN details.
[INF] Defined LAN addresses : [127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[INF] Defined LAN exclusions : []
[INF] Using LAN addresses: [127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[INF] Using bind addresses: []
[INF] Using bind exclusions: []
```

**Comment by kevincox** [comment]
This is still present on 10.7.6. Can we please address this security vulnrability?

**Comment by crobibero** [comment]
> This is still present on 10.7.6. Can we please address this security vulnrability?

A PR was merged and released that fixed this error. If you’re still having this error, please open a new issue.

**Comment by kevincox** [comment]
Well apparently it wasn't fixed because it is still happening. Ah well, 3rd issue lucky https://github.com/jellyfin/jellyfin/issues/6272
