### ISSUE TITLE
10.7.2 fails to build on Fedora and EL7

### ISSUE THREAD

**Issue by brianjmurrell** [jellyfin/jellyfin#5783]
10.7.2 fails to build on Fedora and EL7:

https://download.copr.fedorainfracloud.org/results/brianjmurrell/jellyfin/fedora-33-x86_64/02129055-jellyfin/build.log.gz

I don't know enough about .Net to know why though.

**Comment by joshuaboniface** [comment]
We're aware. I'm debating whether to just tag 10.7.3 or force-up the 10.7.2 tag to include the fix and let it rebuild. If the latter is OK and won't break COPR I'll just do that.

**Comment by brianjmurrell** [comment]
Yeah, I'm not sure what COPR does when you rewrite tags.

**Comment by joshuaboniface** [comment]
I'd prefer to try the rewrite if only to see for sure how it handles it. If it fails, can a manual build be retriggered?

**Comment by brianjmurrell** [comment]
Yeah, it could be.

**Comment by joshuaboniface** [comment]
OK I will do that then and update here. I think the confusion amongst user of a 10.7.3 when there was no 10.7.2 outweights the confusion of us with regards to the tag rewrite - every build failed, not just Fedora ;-)

**Comment by joshuaboniface** [comment]
OK the new Web tag has been forced up (and Azure kicked off a build for it).

I'm doing some test builds with Server first to be sure then will do the same there. :crossed_fingers:

**Comment by joshuaboniface** [comment]
Builds passed, and server tag updated as well. If COPR doesn't auto-accept it in the next few mins please retrigger manually and that should be it.

**Comment by brianjmurrell** [comment]
So far, no new build on COPR.  So, re-writing tags does not look like a good thing.

**Comment by oddstr13** [comment]
Fedora and CentOS packages have been built and published:
https://repo.jellyfin.org/releases/server/fedora/stable/
https://repo.jellyfin.org/releases/server/centos/stable/
