### ISSUE TITLE
Emby's roku app no longer works with Jellyfin

### ISSUE THREAD

**Issue by rangeroob** [jellyfin/jellyfin#579]
**Describe the bug**
 The emby roku app does not load jellyfin anymore after an upgrade to version 10.0.1.

**To Reproduce**
1) Try and load emby roku app
2) It will display a error of wrong server version and then not continue to load jellyfin 

**Expected behavior**

To load the emby roku app and be able to use jellyfin.

**System (please complete the following information):**
 - Roku
 - Server Version: Debian Stretch (9)
 - Jellyfin Version:  10.0.1

**Comment by JustAMan** [comment]
This is most likely not our issue but Emby intentionally breaking compatibility like they did for Android and Chromecast at least.
This should be solved by eventually making our own Roku app.

**Comment by m0nik3r** [comment]
While not the most aesthetically pleasing, the old public code works correctly, though you'll need to install it via developer mode on your roku - https://github.com/jellyfin/jellyfin-roku

**Comment by sparky8251** [comment]
Can this issue be closed? It's likely upstream breaking Roku on us (purposefully or not).

**Comment by JustAMan** [comment]
We're not playing cat-and-mouse game here, Emby apps are intentionally broken for Jellyfin server.
To use Roku with Jellyfin either find and sideload (if possible) old version of Emby app or wait (or better contribute to!) Jellyfin Roku app following the repo link provided by @m0nik3r.

**Comment by rpatterson** [comment]
FWIW, I recently tested the Emby Roku app connected to a Jellyfin server and it worked as far as I could tell.  I tested both Movies and TV Shows.
