### ISSUE TITLE
Can not connect from outside my home network

### ISSUE THREAD

**Issue by Tina-otoge** [jellyfin/jellyfin#5790]
When I'm accessing Jellyfin from outside my home network, such as when using mobile data, the page loads indefinitely on the web client. In other clients such as the official Android client I can not connect at all "`Connection can not be established. Please check the hostname and your network connection.`"

I can access other services running on the same machine (such as file explorer, torrent clients, SSH, etc) in or outside my network using my public Internet facing IP, so I can confirm my machine is accessible from outside.

If I use my public IP while connected to my home network, it works too. Which is surprising. I can use my domain name which redirects to my public IP, or type the IP directly, they both give the same result, I can access Jellyfin while on my home network but not when outside.

**System:**
 - OS: Fedora (ARM)
 - Virtualization: Podman (using the Dockerhub image)
 - Clients: Browser, Jellyfin android app, Gelli android app
 - Browser: Desktop: Firefox 87.0 / Mobile: Firefox 84.1.4
 - Jellyfin Version: 10.7.2
 - Playback: Direct Play
 - Installed Plugins: None
 - Reverse Proxy: Caddy
 - Base URL: /jellyfin
 - Networking: Not sure
 - Storage: NFS, samba

**Logs**

Jellyfin server does not seem to have any relevant error, I can only see
```
[12:49:27] [WRN] [20] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://MY_DNS/jellyfin/Users/485d6438f3a04814a6783fbeb7e57481 to MY_MOBILE_DATA_IP in 0:00:01.1525509 with Status Code 200
```
When I try to load the page but nothing that looks like an error.

However in the web client JS console, if I try to load the page while I'm connected to an account (previously connected while on home network) I can see
```
Uncaught (in promise) SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
```
This happens between `initAfterDependencies promises resolved` and `using default fonts` logs.

If I try to load the page after a log out / private browser window, the client loads but I'm asked to connect to a server, if I try to enter my server address I get the popup "Connection Failure" "We're unable to connect to the selected server right now. Please ensure it is running and try again".

**Comment by jedthe3rd** [comment]
Are your ports forwarded correctly on your router? Specifying the domain name will actually just route internally because it knows where it eventually will end up. I would also check any firewall rules.

**Comment by Tina-otoge** [comment]
Traffic goes through a Caddy reverse proxy on /jellyfin on port 80, that's how I access all my other apps running on this machine too and it works (in and outside the network), each app running through a different reverse proxy.
Jellyfin worked before upgrading to 10.7 too, so I don't believe it's an error in my network setup. But maybe something that changed 10.7 that makes it not work on Caddy's default reverse proxy setting anymore? I'm not sure what to investigate.

**Comment by Tina-otoge** [comment]
Uh, turns out I was just facing the exact same issue as #5575, had to enable "Allow remote connections to this server" which sounds obvious, I'm guessing I didn't need it before upgrading to 10.7 because of the reverse proxy? Anyway I fixed my issue by enabling this option. Closing this.
