### ISSUE TITLE
Can't display files in Chinese

### ISSUE THREAD

**Issue by pochacho99** [jellyfin/jellyfin#5797]
**Describe the bug**
Movie file name is in Chinese and displays properly in OS, but when scanned by Jellyfin, it shows up as mixed symbols.

**System (please complete the following information):**
 - OS: Windows
 - Clients: Any
 - Browser: Any
 - Jellyfin Version: 10.7.2 Windows
 - Storage: NAS

**To Reproduce**
Scan movie folder

**Expected behavior**

![Jellyfin](https://user-images.githubusercontent.com/39760089/114525484-b7e24500-9c78-11eb-8f3b-2630fcf9d58d.png)
**Screenshots**

**Additional context**
Plex on the same server scans the file correctly. Windows shows the file name correctly in Chinese

**Comment by BaronGreenback** [comment]
Could you post the name of the file so i've got the characters to use for testing please?

**Comment by pochacho99** [comment]
The folder has about 20 files with Chinese names. Plex can pick them up all fine, and i can see them named correctly in File Explorer. Unfortunately Jellyfin does not give me any indication which file it is pointing to, just some mixed symbols. Here are some examples of the file names i have just copied from File Explorer so hopefully they keep the same encoding, but i can't be sure if they are referring to the example above:

大內密探零零發
大话西游2之仙履奇缘
大话西游1之月光宝盒

**Comment by BaronGreenback** [comment]
Just tested on mine - and it seems to work.

Could you upload your system.xml file please?

Also what culture settings have you got defined in windows?

**Comment by pochacho99** [comment]
Where is the system.xml file located in Windows?

I've got the Chinese language packs installed, but display language is set to English US. I have this same exact setup for all my other PCs and don't have this problem.

**Comment by pochacho99** [comment]
i spun up a Docker version and everything is scanning fine, thanks for your help
