### ISSUE TITLE
C# Expressions that are always false or true

### ISSUE THREAD

**Issue by EraYaN** [jellyfin/jellyfin#581]
**Additional context**
ReSharper based rule set as the source.
Some are Guid == null, some are other idiosyncrasies that mean the code needs looking at.

[exp_always_true_false.zip](https://github.com/jellyfin/jellyfin/files/2753538/exp_always_true_false.zip)
[exp_always_true_false_v2.zip](https://github.com/jellyfin/jellyfin/files/2797570/exp_always_true_false_v2.zip)

**Comment by JustAMan** [comment]
@EraYaN is this fixed by #657?

**Comment by EraYaN** [comment]
Only partly I think.

**Comment by JustAMan** [comment]
Can you please update the report then?
