### ISSUE TITLE
how to Hide continue watching?

### ISSUE THREAD

**Issue by DarshZero** [jellyfin/jellyfin#5817]
Hello,
i wanna hide continue watching.
Thank you.

**Comment by Anti-ctrl** [comment]
I dont have Jellyfin in English, but i will try my best here:
go to the Hamburger Menu, on the Left side -> click Settings. Go to start page/front page or what ever similar its called. There you can see "continue watching". Set it to "none" and click save on the bottom of the Page. 

Done.

Hope it helps.
