### ISSUE TITLE
Transcoding fails without manually setting /dev/dri/renderD128 permission

### ISSUE THREAD

**Issue by bradgy** [jellyfin/jellyfin#5818]
**Describe the bug**
Transcoding fails without manually setting /dev/dri/renderD128 permission

**System (please complete the following information):**
 - OS: Ubuntu 20.04 server
 - Virtualization: none for jellyfin; behind traefik rev proxy running in docker
 - Clients: Android, Kodi, Firefox/browser
 - Browser: Firefox 87.0
 - Jellyfin Version: 10.7.2
 - Playback: Transcode only, directly play/stream unaffected
 - Installed Plugins: TVDB
 - Reverse Proxy: traefik in docker
 - Storage: local btrfs

**To Reproduce**
1. Play file and ensure it will try to transcode by choosing a low bitrate manually
2. See that it fails

**Expected behavior**
1. Regular playback of the file

**Logs**
https://pastebin.com/vq5Gfvxw
https://pastebin.com/6WXLpcvj (after changing renderD128 permission to 666; see below)

**Additional context**
Potential link with /dev/dri/renderD128 permission. At boot it is 660; changing to 666 using chmod works around this issue but doesn't persist after reboot. Added my username to the render and video groups, that didn't do anything. Haven't tried adding the jellyfin user to those groups yet (is the username 'jellyfin'?).

**Comment by crobibero** [comment]
I believe the service user is `jellyfin`, so please try adding that user to the group.

**Comment by bradgy** [comment]
sudo usermod -a -G render jellyfin
sudo usermod -a -G video jellyfin
sudo reboot
ls -lah /dev/dri/renderD128
`crw-rw----+  1 root render 226, 128 Apr 15 11:54 renderD128`

Tried to play file with transcoding, worked on browser and android devices. Seemed like adding the jellyfin service user to render group (maybe also video group) solved the issue for me. Thanks @crobibero
