### ISSUE TITLE
IPv6 error for jellyfin repo

### ISSUE THREAD

**Issue by ackr-8** [jellyfin/jellyfin#5821]
Issue:
Jellyfin repo doesn't work with IPv6 but the ipv6 AAAA record is added to the domain. 

Fix : 
Either remove the AAAA record or fix the hosting server.

**Comment by nielsvanvelzen** [comment]
Please provide more information, like the mirror your using etc.

Connecting over ipv6 to the repository works fine for me.

**Comment by ackr-8** [comment]
Im connected to the elb1.jellyfin.org mirror and I am  using the debian repo. I cant update the system as jellyfin repo timesout. I tried to access the url on a browser and it too timed out

**Comment by ackr-8** [comment]
My nearest fastly mirror is in Singapore (If the jellyfin repo is hosted with fastly).

**Comment by BaronGreenback** [comment]
Are you able to test PR's - we have https://github.com/jellyfin/jellyfin/pull/5735 which should enable auto fallback to ip4. It needs testing, and this seems perfect.

**Comment by ackr-8** [comment]
The workaround mentioned here [https://github.com/jellyfin/jellyfin/issues/1002](#1002) works but its a band-aid as the server ip of your website keeps changing from time to time.

**Comment by BaronGreenback** [comment]
website ip addresses do change which is why dns is used. If that is the cause of the issue, then whatever dns server you are using may have it's ttl set too high.

**Comment by ackr-8** [comment]
Its not a DNS issue as I am using Cloudflare's DNS, its a routing issue as if I do a ping I get the IP address of the website but connection times out. Can you use a VPN to Singapore and test it as the mirror I am connected to is in Singapore and check by the ping command to verify whether its a IPv6 address or IPv4.

**Comment by ackr-8** [comment]
Thanks the routing issue is fixed.
