### ISSUE TITLE
DLNA PlayTo uses external address if the device gets discovered first by a notify

### ISSUE THREAD

**Issue by jrb0001** [jellyfin/jellyfin#5822]
**Describe the bug**
There seem to be two ways for a DNLA Play To device to get discovered:
- If Jellyfin queries it, then the response is received on the socket bound to the specific interface address and GetBindInterface selects the correct address based on the local subnets.
- If the device sends a notify, then it is received by the socket bound to IPv4 wildcard. GetBindInterface gets called with 0.0.0.0 and returns the external address (which isn't reachable from the device).

Depending how the device gets discovered, playback either works, or the device can't connect to Jellyfin because of firewalling.

**System (please complete the following information):**
 - OS: Ubuntu 20.04
 - Virtualization: LXC
 - Clients: Kodi on Android as DLNA Play To target
 - Browser: FF 87 to start the playback
 - Jellyfin Version: Jellyfin.Server 10.7.2.0 (.deb amd64 10.7.2-1)
 - Playback: Makes no difference
 - Installed Plugins: none
 - Reverse Proxy: caddy from the browser, none from Kodi
 - Base URL: none
 - Networking: veth to a bridge, to a series of switches and (towards Kodi) an AP.
 - Storage: local

**To Reproduce**
1. Configure an external address which isn't reachable from KODI (for example doesn't exist or with firewalling).
2. Start KODI.
2. Start Jellyfin.
3. Use another device to play something via DLNA to Kodi-> works.
4. Restart KODI.
5. Use another device to play something via DLNA to Kodi -> doesn't work.

**Expected behavior**
Playback always works.

**Logs**
If Jellyfin starts after Kodi:
```
[10:58:07] [DBG] Attempting to create PlayToController from location http://172.20.1.72:1906/
[10:58:07] [DBG] GetBindInterface: Source: True, External: False:
[10:58:07] [DBG] 172.20.1.74/32: GetBindInterface: Has found matching interface. 172.20.1.74
[10:58:07] [DBG] Dlna Device.Start
[10:58:07] [INF] No matching device profile found. The default will need to be used.
FriendlyName:Tablet
Manufacturer:XBMC Foundation
ManufacturerUrl:http://kodi.tv/
ModelDescription:Kodi - Media Renderer
ModelName:Kodi
ModelNumber:19.0 (19.0.0) Git:20210218-f44fdfbf67
ModelUrl:http://kodi.tv/
SerialNumber:
[10:58:07] [INF] DLNA Session created for Tablet - Kodi
```

If Kodi starts after Jellyfin:
```
[10:58:36] [DBG] Attempting to create PlayToController from location http://172.20.1.72:1266/
[10:58:36] [DBG] GetBindInterface: Source: True, External: True:
[10:58:36] [DBG] Any IP4 Address: GetBindInterface: Selected first external interface. 169.254.10.87
[10:58:36] [DBG] Dlna Device.Start
[10:58:36] [INF] No matching device profile found. The default will need to be used.
FriendlyName:Tablet
Manufacturer:XBMC Foundation
ManufacturerUrl:http://kodi.tv/
ModelDescription:Kodi - Media Renderer
ModelName:Kodi
ModelNumber:19.0 (19.0.0) Git:20210218-f44fdfbf67
ModelUrl:http://kodi.tv/
SerialNumber:
[10:58:36] [INF] DLNA Session created for Tablet - Kodi
```

**Additional context**
I am aware that I could override the external address, but Jellyfin is connected to two different subnets with potential DLNA devices and there is no address that works for both (firewalling).

**Comment by jrb0001** [comment]
I look at the code and my main questioin is: Why does `PlayToManager.AddDevice()` use the bind address of the SSDP socket?

Wouldn't it be better if it would take the source address of the SSDP packet (response or notify)? Or if it would extract it from the Location header?

I think those two options would be more reliable and also more intuitive for the "Published Server URIs" option (assuming it does what I think it does)?

Just let me know what you prefer and I can open a PR for it (currently running such a patched version to test it).

**Comment by lililala6868** [comment]
[168kaijiangwang](http://www.1685950.com)

**Comment by BaronGreenback** [comment]
Cause: GetBindInterface is expecting an external ip as the parameter, not the local ip.
