### ISSUE TITLE
fractional width causes validation error when retrieving "main" image

### ISSUE THREAD

**Issue by rmalchow** [jellyfin/jellyfin#5829]
**Describe the bug**

when the UI tries to load the main image (this may or may not affect other images, i have only ever noticed on the main image), it will sometimes sends a fractional width, such as:

```$JELLYFIN_URL/Items/..../Images/Primary?fillHeight=535&fillWidth=356.75```

to which the API responds with and error:

```The value '356.75' is not valid.```

- i have HiDPI with fractional scaling enabled 
- client is firefox on fedora 33 with cinnamon. 

**Expected behavior**

either the client or the API should round the value.

**Comment by cvium** [comment]
Thanks for the report, but we're aware. https://github.com/jellyfin/jellyfin-web/issues/2587
