### ISSUE TITLE
jellyfish service returns /proc/net/route access is denied

### ISSUE THREAD

**Issue by jerto** [jellyfin/jellyfin#5830]
**Describe the bug**
I installed Jellyfish on an Ubuntu 18.04 server following this procedure : https://jellyfin.org/docs/general/administration/installing.html#ubuntu

The install went fine but the service failed starting

**System (please complete the following information):**
 - OS: Ubuntu 18.04
 - Virtualization: None
 - Clients: Browser, Android
 - Browser: Brave Version 1.22.71 Chromium: 89.0.4389.114 (Build officiel) (64 bits)
 - Jellyfin Version: 10.7.2
 - Playback: 
 - Installed Plugins: none
 - Reverse Proxy: apache
 - Base URL: https://jellyfin.mydomain.com
 - Networking:host
 - Storage: local

**To Reproduce**
Just install Jellyfish on an Ubuntu 18.04 server

**Expected behavior**
The jellyfish service should be started

**Logs**
System.UnauthorizedAccessException: Access to the path '/proc/net/route' is denied.
 ---> System.IO.IOException: Permission denied

**Troubleshooting**
I disabled the service and tried starting jellyfish with the following command :
 cd  /usr/lib/jellyfin/bin
./jellyfin

That worked.

I created a bash file with this command and a service to launch this file.
That worked too.

So I have a running jellyfish now.

**Comment by BaronGreenback** [comment]
ifrc the dotnet function that retreives network information - also checks route information for purposes i don't know.

https://github.com/jellyfin/jellyfin/pull/5773 should not handle this correctly and fall back to dns if there are any permission issues

**Comment by lililala6868** [comment]
[点击幸运飞艇中大奖](http://www.1685950.com) 
[168kaijiangwang](http://www.1685950.com)
