### ISSUE TITLE
10.7.0 last usable version

### ISSUE THREAD

**Issue by SimplyCorbett** [jellyfin/jellyfin#5833]
Hi there,

I'm using the generic linux package.

The last working version is 10.7.0 (https://repo.jellyfin.org/releases/server/linux/versions/stable/combined/10.7.0/)

Any version past this (including. unstable) just doesn't work.

The only error listed (and this works on 10.7.0):

```
jellyfin@primary ~/start $ sh ./jellyfin.sh
./jellyfin.sh: line 6: /home/jellyfin/start/jellyfin/jellyfin: No such file or directory
```

```
#!/bin/bash
JELLYFINDIR="/home/jellyfin/start"
FFMPEGDIR="/usr/bin"

$JELLYFINDIR/jellyfin/jellyfin \
 -d $JELLYFINDIR/data \
 -C $JELLYFINDIR/cache \
 -c $JELLYFINDIR/config \
 -l $JELLYFINDIR/log \
 --ffmpeg $FFMPEGDIR/ffmpeg
```

**Comment by Dynamic-Gravity** [comment]
I receive the same error using the generic Linux package as well.

**Comment by taigrr** [comment]
Confirmed when running from Docker. Playback shows as 404s in the browser with the message "This client isn't compatible with the media and the server isn't sending a compatible media format."

Reverting to 10.7.0 fixes things. Perhaps there is an issue with a shared library?

**Comment by Pwnulatr** [comment]
Am also having this issue with Docker on Firefox. Error occurs in the Web player, Jellyfin Desktop, Android and iOS. Doesn't occur on Roku for some reason, as that is the only working client in my setup.

**Comment by dmitrylyzo** [comment]
> `./jellyfin.sh: line 6: /home/jellyfin/start/jellyfin/jellyfin: No such file or directory`

On Matrix, there was a user with the same error. It was missing `libc.musl-x86_64.so.1`. We ended up combining the server and the web archives manually.

To check that:
```sh
ldd /home/jellyfin/start/jellyfin/jellyfin
```

10.7.5 seems to be built without libc.musl.

**Comment by taigrr** [comment]
@dmitrylyzo is absolutely correct on this one.

**Comment by Bond-009** [comment]
Closing as stale
