### ISSUE TITLE
Jellyfin file permissions.

### ISSUE THREAD

**Issue by bjwest** [jellyfin/jellyfin#5849]
Jellyfin refuses to play or delete media if it doesn't have executable permissions on the media directory.  Not only are media files are not executable, but leaving the executable flag set on a directory it is not needed is a security risk.

Jellyfin Server 10.6.4.0
Ubuntu server Ubuntu 20.04.2 LTS

**Comment by oddstr13** [comment]
The executable bit on directories controls the ability to change directory to, and list contents of the directory.
Without the executable bit set, Jellyfin can't open the directory.

**Comment by oddstr13** [comment]
This page contains more details on permissions https://wpollock.com/AUnix1/FilePermissions.htm

**Comment by bjwest** [comment]
I apologize, I can be a bit brain dead at times.  I've been using Linux for well over 20 years and knew that before today when it seems to have erased itself from my memories.
