### ISSUE TITLE
CustomAuthentication was not authenticated on new installation

### ISSUE THREAD

**Issue by bpepple** [jellyfin/jellyfin#5855]
**Describe the bug**
After doing a fresh installation, go to the web interface for the first time, and watch in horror as it gets stuck in a loop and not start the configuation wizard.

**System (please complete the following information):**
 - OS: Raspberry Pi OS
 - Virtualization: N/A
 - Clients: Browser
 - Browser: Firefox 87
 - Jellyfin Version: 10.7.2
 - Playback: N/A
 - Installed Plugins: None
 - Reverse Proxy: None
 - Base URL: jellyfin_ip_address:8096
 - Storage: local

**To Reproduce**
1. Go to jellyfin_ip_address:8096, and watch as it gets caught in a loop.

**Expected behavior**
The configuration wizard starts.

**Logs**
Apr 18 10:59:14 jellyfin jellyfin[525]: [10:59:14] [INF] Update Plugins Completed after 0 minute(s) and 1 seconds
Apr 18 10:59:14 jellyfin jellyfin[525]: [10:59:14] [INF] ExecuteQueuedTasks
Apr 18 11:01:20 jellyfin jellyfin[525]: [11:01:20] [WRN] Slow HTTP Response from http://192.168.86.180:8096/System/Info/Public to 192.168.86.121 in 0:00:00.7091403 with Status Co
Apr 18 11:01:20 jellyfin jellyfin[525]: [11:01:20] [INF] CustomAuthentication was not authenticated. Failure message: Invalid token.
Apr 18 11:01:20 jellyfin jellyfin[525]: [11:01:20] [INF] CustomAuthentication was not authenticated. Failure message: Invalid token.
Apr 18 11:01:20 jellyfin jellyfin[525]: [11:01:20] [INF] CustomAuthentication was not authenticated. Failure message: Invalid token.
Apr 18 11:01:20 jellyfin jellyfin[525]: [11:01:20] [INF] CustomAuthentication was not authenticated. Failure message: Invalid token.
Apr 18 11:01:20 jellyfin jellyfin[525]: [11:01:20] [INF] CustomAuthentication was not authenticated. Failure message: Invalid token.
Apr 18 11:01:21 jellyfin jellyfin[525]: [11:01:21] [INF] AuthenticationScheme: CustomAuthentication was challenged.
Apr 18 11:01:21 jellyfin jellyfin[525]: [11:01:21] [INF] AuthenticationScheme: CustomAuthentication was challenged.

**Screenshots**
N/A

**Comment by crobibero** [comment]
This isn’t a server issue, but a web/apiclient issue.
Should be fixed by https://github.com/jellyfin/jellyfin-apiclient-javascript/pull/187

**Comment by bpepple** [comment]
Ok, hopefully they will push this quickly since it's a pretty big blocker on new installations. Closing.
