### ISSUE TITLE
Backdrops not showing in home

### ISSUE THREAD

**Issue by Evoley** [jellyfin/jellyfin#586]
**Describe the bug**
If "Enable backdrops" is enabled the home menu doesn't show any backdrops after switching to a different menu. To add to this... this problem also happens at startup too. 

**To Reproduce**
1. Go to a different menu ( doesn't matter which one )
2. Click on the house

**Expected behavior**
The backdrop to still be there after changing menus

**Logs**
Logs will be attached

**Screenshots**

**System (please complete the following information):**
 - OS: Windows 10 x64
 - Browser: Chrome Version 72.0.3626.53 (Official Build) beta (64-bit) , Firefox Quantum 64.0.2 (64-bit)
 - Jellyfin Version: 10.0.1.0

**Additional context**
N/A

Expected outcome
![2019-01-14_15-59-41](https://user-images.githubusercontent.com/10457130/51140787-705c7c80-1815-11e9-8060-f7845aeaaa4e.png)

What happens
![2019-01-14_15-51-35](https://user-images.githubusercontent.com/10457130/51140604-f62bf800-1814-11e9-9565-ead5622eb5e7.png)
![2019-01-14_15-53-20](https://user-images.githubusercontent.com/10457130/51140605-f62bf800-1814-11e9-86b4-658752751dd5.png)

[log_20190114 - Copy.log](https://github.com/jellyfin/jellyfin/files/2757026/log_20190114.-.Copy.log)
[log_20190114.log](https://github.com/jellyfin/jellyfin/files/2757015/log_20190114.log)

**Comment by sparky8251** [comment]
This was working in earlier versions of JF at least. I wiped and started over on the 10.0.0 release but I recall this working before that.

How far back or if its a common issue for everyone? Unsure at this time.

More of a regression than a bug imo.

**Comment by Evoley** [comment]
This actually happens on Emby too. At least on versions 3.5.2.0 and 3.5.3.0. One thing I noticed about trying to replicate this problem on Firefox is that the backdrops don't even show at all.

**Comment by sparky8251** [comment]
Weird... Because it certainly used to work for me. AND I exclusively use Firefox....

**Comment by Evoley** [comment]
Happens in Vivaldi too.

**Comment by nkmerrill** [comment]
Hello,

I found a fix here: jellyfin/jellyfin-web/pull/42

You can implement this fix immediately by copying the autobackdrop.js file from my PR to your {jellyfindir}\jellyfin-web\src\scripts folder.

Let me know how it works for you.

Thanks.

**Comment by Evoley** [comment]
@nkmerrill Late reply but it seems to be working.
