### ISSUE TITLE
TMDB Episode provider is not saving External IDs other than TVDB

### ISSUE THREAD

**Issue by SenorSmartyPants** [jellyfin/jellyfin#5869]
https://github.com/jellyfin/jellyfin/blob/8f99bdd07ce037b633993f06f5a68dcb293d6828/MediaBrowser.Providers/Plugins/Tmdb/TV/TmdbEpisodeProvider.cs#L124-L127

TMDB can provide multiple external IDs, as well as TMDB id. But only TVDB is being saved.

episodeResult.id equals TMDB episode id.

```
external_ids: {
imdb_id: "tt14155862",
freebase_mid: null,
freebase_id: null,
tvdb_id: null,
tvrage_id: null
}
```

**Comment by SenorSmartyPants** [comment]
Please also set TMDBId, which TMDB does not consider external, but JF would.

Something like this.

```
            if (!string.IsNullOrEmpty(episodeResult.Id))
            {
                item.SetProviderId(MetadataProvider.Tmdb, episodeResult.Id);
            }
```

**Comment by cvium** [comment]
@SenorSmartyPants I can add the tmdb id as well, but the links will not show in the UI due to the way this has been coded.

**Comment by SenorSmartyPants** [comment]
Having links in the UI would be great if not too much trouble.
