### ISSUE TITLE
Multi-part movie not stacking

### ISSUE THREAD

**Issue by legends2k** [jellyfin/jellyfin#5871]
Two CD parts of a movie isn't stacked as one; it's showing CD2 under _Additional Parts_ as `Big Buck Bunny (2008)-cd2.avi` and the total length of the movie isn't a sum of the duration of both videos, but just CD1's.

```
.
└── Big Buck Bunny (2008)
    ├── Big Buck Bunny (2008)-cd1.avi
    └── Big Buck Bunny (2008)-cd2.avi
```

I've read both [Jellyfin's][1] and [Emby's][2] naming documentation.

[1]: https://jellyfin.org/docs/general/server/media/movies.html
[2]: https://support.emby.media/support/solutions/articles/44001159102-movie-naming

**System:**
 - OS: GNU/Linux (DietPi)
 - Virtualization: None
 - Clients: Browser and Android app
 - Browser: Firefox 87
 - Jellyfin Version: Jellyfin.Server 10.7.2.0
 - Installed Plugins: AudioDB, MusicBrainz, OMDb
 - Storage: Local

**To Reproduce**
1. Create the directory structure above with any video split into two parts 1 and 2
2. Add root directory to media library through web interface
3. Click on the video
4. See that `cd2` is shown under _Additional Parts_
    - Also notice that the duration of the movie/video is just `cd1`'s length and not `cd1` + `cd2`'s length

**Expected behavior**
- Both `cd1` and `cd2` should be internally clubbed
- No additional parts should be shown
- Time should be a sum of both parts
- When played, the video should transition to `cd2` at the end of `cd1`

**Comment by cvium** [comment]
You're describing the ideal behaviour, but that's not how it works nor has it ever. I therefore don't see it as a bug.

**Comment by cvium** [comment]
There's a feature request for it here https://features.jellyfin.org/posts/198/handle-movies-with-multiple-split-files-as-one-item.

But until the library db is rewritten I don't think it's something that is easily accomplished.
