### ISSUE TITLE
Can't download new subtitles from Open Subtitles

### ISSUE THREAD

**Issue by fatraaij** [jellyfin/jellyfin#5895]
**Describe the bug**
I cant download any new subtitles from Open Subtitles. The scheduled task is not working nor is trying to download it via the "Edit Subtitles" menu on a movie/episode. I have the latest version (10.0.0.0) of the Open Subtitles plugin installed.

**System**
- OS: Ubuntu Server 20.04.2 LTS
- Virtualization: LXC on Debian (Proxmox)
- Clients: Browser, Android, iOS, etc
- Jellyfin Version: 10.7.2
- Installed Plugins: AudioDB,MusicBrainz,OMDb,Open Subtitles,TheTVDB
- Reverse Proxy: nginx (with config file from jellyfin docs)
- Base URL: /web/#!/home.html
- Networking: Accessible via reverse proxy (through port forwarding)
- Storage: NFS mounted in Container

**To Reproduce**
1. Have the Open Subtitles plugin installed.
2. Configure the plugin. (credentials, enable in applicable libraries)
3. Have media without subtitles already downloaded.
4. Watch the logs flood :)

**Expected behavior**
I expect the Open Subtitles plugin to download subtitles for my media.

**Logs**
`[2021-04-22 15:58:04.678 +00:00] [ERR] Error downloading subtitles from "Open Subtitles"
System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at XmlRpcHandler.XmlRpcGenerator.DecodeMethodResponse(String xmlResponse)
   at OpenSubtitlesHandler.OpenSubtitles.LogInAsync(String username, String password, String language, CancellationToken cancellationToken)
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.Login(CancellationToken cancellationToken)
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.Search(SubtitleSearchRequest request, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Subtitles.SubtitleManager.SearchSubtitles(SubtitleSearchRequest request, CancellationToken cancellationToken)`

**Comment by ikomhoog** [comment]
Have you confirmed your opensubtitles username and password?
To my knowledge there is no check for those when you save them.
I had these errors when my username started with a capital, so please double check your credentials.

**Comment by fatraaij** [comment]
I checked my credentials multiple times and they were correct. For testing purposes I even made a new account with a short all lower case username.

**Comment by ikomhoog** [comment]
Sorry, I cannot reproduce this on my side, leaving this for someone who can reproduce it.

**Comment by theroflcoptr** [comment]
This might be the same as https://github.com/jellyfin/jellyfin-plugin-opensubtitles/issues/41

**Comment by fatraaij** [comment]
@R0flcopt3r Yep, seems like it. I'm closing it because it is a duplicate then :)
