### ISSUE TITLE
LiveTV transcoding failure when bind to local network address

### ISSUE THREAD

**Issue by kbuddy** [jellyfin/jellyfin#5897]
**Describe the bug**

Setting:
  Networking:
    Bind to local network address: 192.168.1.10

jellyfin will only listen on 192.168.1.10
127.0.0.1 will not listen, but livetv transcode will still connect 127.0.0.1

**System (please complete the following information):**
 - OS: QTS 4.5.2
 - Virtualization: Docker
 - Clients: Browser
 - Browser:  Chrome 89
 - Jellyfin Version: 10.7.2
 - Playback: Transcode
 - Installed Plugins: none
 - Reverse Proxy: nginx
 - Base URL: none
 - Networking: Host
 - Storage: local

**To Reproduce**

1. Go to 'Dashboard => Networking => Bind to local network address'
2. Set Bind to local network address value : 192.168.1.10
3. Go to LiveTV , will play failed

**Expected behavior**
normal play

**Logs**

Jellyfin.Api.Helpers.TranscodingJobHelper: /usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 3000000 -fflags +igndts -hwaccel vaapi -hwaccel_output_format vaapi -vaapi_device /dev/dri/renderD128 -i "http://127.0.0.1:8096/LiveTv/LiveStreamFiles/46a71e5b64a44ab09cd426c1d42015b2/stream.ts" -map_metadata -1 -map_chapters -1 -threads 0 -sn -codec:v:0 h264_vaapi -b:v 9616000 -maxrate 9616000 -bufsize 19232000 -profile:v:0 high -level 41  -force_key_frames:0 "expr:gte(t,n_forced*3)" -vf "format=nv12|vaapi,hwupload,deinterlace_vaapi=rate=frame,scale_vaapi=format=nv12" -start_at_zero -flags -global_header -vsync cfr -codec:a:0 aac -ac 2 -ab 384000 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_base_url "hls/b5e033111e4a9162d29fce240fcfa251/" -hls_playlist_type event -hls_segment_filename "/transcode/b5e033111e4a9162d29fce240fcfa251%d.ts" -y "/transcode/b5e033111e4a9162d29fce240fcfa251.m3u8"

**Screenshots**

**Additional context**

**Comment by BaronGreenback** [comment]
Are you able to test https://github.com/jellyfin/jellyfin/pull/5905 ?

**Comment by kbuddy** [comment]
> Are you able to test #5905 ?

Sorry, I don't have the ability to create a complete test environment.

**Comment by wolfallein** [comment]
I believe I have the same problem. On my setup, Jellyfin (10.7.7) runs inside a docker container and I use a proxy server.

I set the jellyfin container to use my proxy server with environment variables:

```
      - http_proxy=http://192.168.4.3:3128
      - https_proxy=http://192.168.4.3:3128
      - no_proxy=127.0.0.1
```
When I try to play LiveTV the video starts but I only get a few frames.
Checking the proxy server (squid) logs, I see that jellyfin tries to use proxy for 127.0.0.1

```
1636320410.249      1 192.168.4.192 TCP_MISS/503 4026 GET http://127.0.0.1:50152/ping - HIER_DIRECT/127.0.0.1 text/html
```

FFMpeg logs show:

```
Input #0, mpegts, from 'http://127.0.0.1:8096/LiveTv/LiveStreamFiles/1bf770c2d1e04be7889d21f56e0731ff/stream.ts':
```

@BaronGreenback How can I try to test PR #5905 inside my docker container to check if this can solve the issue? Let me know if more info is needed.

Thank you
