### ISSUE TITLE
Consolidated Roadmap

### ISSUE THREAD

**Issue by dcrdev** [jellyfin/jellyfin#59]
I'd like to put in some significant time this weekend to development on this, but I feel the direction at the moment is slightly fragmented - 

Have we considered creating a roadmap and pushing feature requests to something like:
https://feathub.com ?

Additionally have some questions that I'd like some feedback on:
- I see at the moment there's work being done migrated startup preferences to an App.config file. The App.config concept isn't really used in .NET Core, would it not make more sense to migrate this to a platform agnostic json manifest and store this in /etc/default and %\AppData in windows?

- Since clearly there is significant interest in WIndows builds, what is the plan for the service daemon here. Since .NET core does not support the service controller API is windows only and therefore does not exist in .NET core. I've been using this wrapper around the .NET Core compatibility layer for months at work: https://github.com/PeterKottas/DotNetCore.WindowsService . Thoughts?

- Any reason we can't get rid of ImageMagick and solely use Skia? Upstream are already doing this on their .NET Core builds.

- Packaging - what's the plan here? So many distros don't have the .NET Core runtime and SDKs in their core repos (I'm mainly talking RHEL/CentOS and Fedora) , so is the plan here to just provide instructions on where thes dependencies can be sourced from? Or is providing self contained packages a consideration as upstream is already doing?

- Packaging - again, for the benefit of packaging systems that require valid upstream source urls - again mainly rpm. Can we split packaging off into another repo within this Org?

Cheers

**Comment by ryanjerskine** [comment]
> I see at the moment there's work being done migrated startup preferences to an App.config file. The App.config concept isn't really used in .NET Core, would it not make more sense to migrate this to a platform agnostic json manifest and store this in /etc/default and %\AppData in windows?

I'm a big fan of using environment variables for simple configuration. You also have the benefit of not having to bake all of the configuration into a docker image. https://12factor.net/config

**Comment by dcrdev** [comment]
@ryanjerskine even better yes - we'd probably have to pick those environment variable up from the init script and pass them as args to the server component, but definitely feasible and a good suggestion.

**Comment by anthonylavado** [comment]
> Have we considered creating a roadmap and pushing feature requests to something like:
> https://feathub.com ?

IIRC, @joshuaboniface set up a link in the Readme, but something about that website unsettles me. It seems like it's pretty stale, and a few of the projects they showcase don't even use Feathub anymore. I was considering another repo in the Org for feature requests. I don't know where we could collaborate on a roadmap, but definitely one will go in the Wiki once we have it.

**Comment by ryanwalder** [comment]
A platform agnostic config file (JSON would by nice). I kinda disagree with the envars options (if the only way), this is about as far away from a 12factor app as you can get.

**Comment by dcrdev** [comment]
@ryanwalder sure but if this was picked up from the init script and passed in as runtime args - it would be entirely optional. In certain circumstances event beneficial.

In any case my overarching point is that the App.config concept is deprecated in the .net core ecosystem.

**Comment by dcrdev** [comment]
Cool I was going have a go, but if you want to do it great.

For my packages I wrote a simple wrapper around mock that might make your life easier:
https://raw.githubusercontent.com/dcrdev/brimstone/master/brimstone

**Comment by ryanwalder** [comment]
Neat, will take a little look when I get some time. Glad to help, I can't code for toffee but I can definitely sysadmin my way out a paper bag.

I assume the end goal is CI outputting builds to distro specific repos (and docker)?

**Comment by BnMcG** [comment]
> Since clearly there is significant interest in WIndows builds, what is the plan for the service daemon here. Since .NET core does not support the service controller API is windows only and therefore does not exist in .NET core. I've been using this wrapper around the .NET Core compatibility layer for months at work: https://github.com/PeterKottas/DotNetCore.WindowsService . Thoughts?

I think [NSSM](https://nssm.cc/) is also a popular tool for this, not sure what the pro's/con's between the two are.

**Comment by joshuaboniface** [comment]
> I see at the moment there's work being done migrated startup preferences to an App.config file. The App.config concept isn't really used in .NET Core, would it not make more sense to migrate this to a platform agnostic json manifest and store this in /etc/default and %\AppData in windows?

I think this makes a lot of sense, anything we can do to avoid Mono/legacy cruft is a good thing.

> Any reason we can't get rid of ImageMagick and solely use Skia? Upstream are already doing this on their .NET Core builds.

Skia from what I've read sounds good, better than keeping a bad fork of ImageMagick around. Like the idea!

> Packaging - what's the plan here? So many distros don't have the .NET Core runtime and SDKs in their core repos (I'm mainly talking RHEL/CentOS and Fedora) , so is the plan here to just provide instructions on where thes dependencies can be sourced from? Or is providing self contained packages a consideration as upstream is already doing?

> Packaging - again, for the benefit of packaging systems that require valid upstream source urls - again mainly rpm. Can we split packaging off into another repo within this Org?

I'm not in a huge rush to support RHEL distros - Debian-based is far more commonly used, along with Docker. I think instructions-only for .NET Core is fine, and we can split this out if someone is willing to take it on or expresses interest in it (I'm 100% Debian).

**Comment by jeffkeller87** [comment]
@anthonylavado regarding a wiki roadmap: here's the [high-level feature wiki page](https://github.com/jeffkeller87/jellyfin/wiki/Feature-Prioritization) I started the other day (and probably got lost in the Riot room). I don't have permissions to add it to this repo, so it's in my fork. Things have been moving quickly so this may not be that relevant anymore--sharing in the event it's useful as a starting point.

**Comment by Bond-009** [comment]
AFAIK Skia is already being used and ImageMagick serves as a fallback.

**Comment by LogicalPhallacy** [comment]
Since Windows is the only platform that really utilizes the "Service" model refactoring the project to support it natively I probably not worth the time, especially since there are valid reasons that someone might not want emby to run as a windows service. While I personally have a dislike of NSSM it is VERY good at what it does and its a perfectly fine option for anyone who wants the native binaries to run as a Service on windows.

Replacing App.config with something more modern is fairly inconsequential, but the more Linux-y collection of environment variables is particularly frustrating on Windows. Traditionally when those are used on windows they get stored in the registry. Right now Jellyfin is very very clean for a windows app, near as I can tell it confines itself to a few directories in userspace which makes it eligible for several of the windows modernization efforts (sandboxed apps, clean install/uninstall) with a fairly minor amount of effort. A JSON config would be preferable here IMO because it lets us keep that cleanliness.

**Comment by joshuaboniface** [comment]
@dcrdev Any further thoughts on this? Things have moved quite a bit over the last 3 weeks.

**Comment by sparky8251** [comment]
Is it time to close this issue? About a month since a there was substantial conversation on it.
