### ISSUE TITLE
Move to upstream NLangDetect

### ISSUE THREAD

**Issue by JustAMan** [jellyfin/jellyfin#590]
**Problem:**
A lot of code to maintain, which is bad. Seems like I found one more 3rd party thing integrated into the source tree: NLangDetect (e.g. https://github.com/jellyfin/jellyfin/blob/4b5fbaa4cd064813155ac5ef366f6e1c597d355e/Emby.Server.Implementations/TextEncoding/NLangDetect/NLangDetectException.cs#L1). Apparently original source: https://github.com/marek-stoj/NLangDetect

**Solution:**
Migrate to that 3rd party code to avoid maintaining it ourselves. If this is impossible by just using it as a NuGet dependency - fork it and make a NuGet package.

**Comment by Bond-009** [comment]
IMO a better solution would be porting the original project from Java to C#, it was more maintained.
https://github.com/shuyo/language-detection

**Comment by cvium** [comment]
> 
> 
> IMO a better solution would be porting the original project from Java to C#, it was more maintained.
> https://github.com/shuyo/language-detection

There's a newer C# port: https://github.com/pdonald/language-detection

**Comment by JustAMan** [comment]
Alas, that's impossible to use. Apache 2.0 is not compatible with GPL2 we have in core...

**Comment by cvium** [comment]
Damn, that sucks.

Btw, there's no license on the original project. Is porting considered a derived work? And would anyone even be allowed to port it and distribute it under a different license?

**Comment by JustAMan** [comment]
Looking closer original java lib is also apache 2.0, and porting is considered derivative work, so we can't use it in any form :(
