### ISSUE TITLE
Casting with Chromecast (NEXT/PREVIOUS keys not working)

### ISSUE THREAD

**Issue by EFCAugure** [jellyfin/jellyfin#5908]
Describe the bug

Hello,
i noticed this issue under the Jellyfin Android project but i had no answer for monthes (maybe because this is not related to Android?)
I am running the latest Android release (2.2.3) on the Playstore on my Oneplus 6 (Android 10).
I am running Jellyfin unstable 20210424.
I managed to cast movies and / or music on my Chromecast.
What is not working are the NEXT and PREVIOUS keys (play/pause are working good) to switch to the next song (playlist or in an album view).
It's the same with movies and TV shows.
Does anyone have the same problem or has a solution?

Thanks for your help!
Lionel

To Reproduce

    Start casting from my phone to my Chromecast
    Select a song playlist
    Play the first song
    Press NEXT button to switch to second song

Expected behavior
I expect to listen to the second song but it keeps restarting the current song only (idem for the previous button)

System (please complete the following information):

    App version: 2.2.3
    Android version: OxygenOS 10.3.8
    Device manufacturer and model: Oneplus 6
    Jellyfin server version: latest rc : 10.7.0 20210424
    The type of video player implementation used: integrated player (ExoPlayer)]

**Comment by HybridSarcasm** [comment]
This has been open quite a while. Can this be re-produced with the current build? If so, please update the bug report details. Thanks!

**Comment by Bond-009** [comment]
Closing as stale
