### ISSUE TITLE
Could not connect remotely using the app while I could connect remotely

### ISSUE THREAD

**Issue by RJswap** [jellyfin/jellyfin#5923]
**Describe the bug**
The server is not recognize by the Jellyfin app remotely but is accessible remotely using a browser and the same adress.

**System :**
 - OS: [Synology OS]
 - Virtualization: [Docker]
 - Clients: [Windows, Android]
 - Browser: [Firefox]
 - Jellyfin Version: [e.g. 10.7.2]
 - Installed Plugins: [Half of plugins available.]
 - Reverse Proxy: [yes]
 - Base URL: [https://mydomain.fr]

**To Reproduce**

1. Open a Jellyfin client app
2. Enter the adress of my server https://mydomain.fr
3. Click on connect
4. See error (connection failed)

**Expected behavior**

Show the login page of the server

**Logs**

I don't to where to find log.

**Screenshots**

![image](https://user-images.githubusercontent.com/61156795/116244066-da3f8c80-a767-11eb-9bcd-e50d4cae1d43.png)
![jellybrowser](https://user-images.githubusercontent.com/61156795/116244998-c8121e00-a768-11eb-969d-9689b4c45546.png)
![nginx config](https://user-images.githubusercontent.com/61156795/116245772-93529680-a769-11eb-8400-902b91051ac0.png)

**Additional context**

What I don't understand is that my reverse proxy setup works because I can access to my server remotely but the jellyfin app does not found it.

**Comment by mysther** [comment]
Hello @RJswap,

I don't have this problem on my side :/

System :
- OS: [Synology OS]
- Virtualization: [Docker]
- Clients: [Android]
- Browser: [Firefox]
- Jellyfin Version: [10.7.2]
- Installed Plugins: N/A
- Reverse Proxy: [yes]
- Base URL: [https://**play.**mydomain.fr]

and 
![image](https://user-images.githubusercontent.com/50944755/116263205-7920b480-a779-11eb-8681-5e94d193aa21.png)

**Comment by RJswap** [comment]
Thanks for your reply !
Mine has these settings :
![image](https://user-images.githubusercontent.com/61156795/116297786-efcea980-a79b-11eb-8cb4-57bb79f5ddd8.png)

**Comment by Bond-009** [comment]
Closing as stale
