### ISSUE TITLE
S3 or Bucket storage for external storage

### ISSUE THREAD

**Issue by williamgh2019** [jellyfin/jellyfin#5925]
Hi,

Now Object Storage in the cloud VM is cheaper than Block Storage, it would be better if jellyfin has option to connect external storage like Object Storage to save all media on the server and cost saving on media storage and faster with CDN.

**Comment by nielsvanvelzen** [comment]
Features go to https://features.jellyfin.org

**Comment by cvium** [comment]
Before you go writing feature requests for this I have to say that this is not a feature that we will ever work on. We will not support cloud-based, network-based (SMB etc.) or alternative filesystems (RAR-mounting etc.).

**Comment by mffan0922** [comment]
> 

May I ask why......

**Comment by mffan0922** [comment]
> Before you go writing feature requests for this I have to say that this is not a feature that we will ever work on. We will not support cloud-based, network-based (SMB etc.) or alternative filesystems (RAR-mounting etc.).

May I ask why.......
I have the same demand， and I believe I am not the only one who need this function, can you please support this? thx

**Comment by cvium** [comment]
We do not want the added support burden (bugs, new providers, configuration etc.). There is already stuff like rclone that can mount cloud storages to your local filesystem.

**Comment by mffan0922** [comment]
OK.... I understand
