### ISSUE TITLE
Chromecast not connecting (Reverse Proxy, SSL with Cloudflare Cert)

### ISSUE THREAD

**Issue by Lerrrtaste** [jellyfin/jellyfin#5926]
**Describe the bug**
Can't connect Jellyfin to Chromecast 

**System:**
 - OS: Unraid 6.9.2
 - Virtualization: Docker
 - Clients: Android
 - Jellyfin Version: 10.7.2
 - Installed Plugins: none
 - Reverse Proxy: nginx
 - Base URL: /
 - Networking: Bridge (with HTTP Port Mapping)

**My Configuration**
- HTTPS disabled in Jellyfin Settings
- Reverse Proxy using Nginx (to HTTP Port, but with SSL) and config copied from Documentation
- Using SSL Certificate by Cloudflare
- Published Server URIs is set
- Tried stable and unstable Chromecast version in the App

**Explanation**
I can see all Cast supporting devices under "Cast Devices" in the App.
Strange thing is, casting to a Nest Hub **works just fine**. Only the Chromecast TV Stick (1st gen) won't connect. When selecting it, the app keeps showing its loading animation, but the Chromecast does not show a reaction (not even the Logo appears).
I have to close and reopen the app to try again, otherwise the Device selection Popup does not show after Clicking "Cast Devices".

**Logs**
No Logs. Not even a error message. Just infinite loading animation.

**Comment by Lerrrtaste** [comment]
Update: It does work via Chrome so the problem is probably only related to the android app

**Comment by Lerrrtaste** [comment]
Update 2: I tried a second phone and from there it works fine too. So it must be something with my Galaxy S10 ...

**Comment by Bond-009** [comment]
Closing as stale
