### ISSUE TITLE
How to change the logo

### ISSUE THREAD

**Issue by MadMacMig** [jellyfin/jellyfin#5928]
This isn't a bug more of a how to.

I have been trying to change the Jellyfin web logo but every time I put in the custom css code to change the logo, I just end up getting no logo at all. I have no clue why this is. One more thing is that I'd like to change the favicon and the colour scheme, how would I go about doing that?

I am using the windows 10 Jellyfin server and yes, I am all up to date.

The code that I have used and have not gotten anywhere.
`/* Custom logo*/
.imgLogoIcon {
content: url(C:\Users\migue\Desktop\ANTARYScloudS.png) !important; }
/* Main Drawer Mobile Logo*/
.adminDrawerLogo img {
content: url(C:\Users\migue\Desktop\ANTARYScloudS.png) !important; }
/* Home Page Logo*/
.pageTitleWithLogo {
background-image: url(C:\Users\migue\Desktop\ANTARYScloudS.png) !important; } `

**Comment by MadMacMig** [comment]
I also have a suggestion

How about an easy way in the admin's settings where you can change the name, logo and colours.

**Comment by erennnars** [comment]
Just right click on the logo and open inspector, /assets/img/banner-light.png for me ,  then you can go to that directory, put your own logo and name it banner-light.png

**Comment by DanielVukelich** [comment]
Having a way to change the logo and favicon from the admin UI would be helpful for docker users, so we don't have to mount volumes just to edit the assets folder.  It would also be nice if it were possible to change the browser tab text for the login page and the home page.  Instead of the tab saying "Jellyfin", it would be the name of my service.

**Comment by crobibero** [comment]
Feature requests belong at https://features.jellyfin.org/

Either way, this is not a server issue.
