### ISSUE TITLE
Remove Games

### ISSUE THREAD

**Issue by cvium** [jellyfin/jellyfin#593]
**Is your feature request related to a problem? Please describe.**
The games service is half-assed, requires a separate plugin and manual install steps and is basically a glorified gallery given that no clients really support it. It should be removed as it's not even in the spirit of Jellyfin.

**Describe the solution you'd like**
Remove https://github.com/jellyfin/jellyfin/blob/dev/MediaBrowser.Api/GamesService.cs and related classes.

**Describe alternatives you've considered**
There are none.

**Additional context**
Not even the upstream project really believes in this feature: https://emby.media/community/index.php?/topic/62513-36037-giving-games-some-love/?p=619211

**Comment by JustAMan** [comment]
Games might be implemented via using browser emulators. But I think if they are implemented in any way it should be via plugin, so I support removing them from core.

**Comment by RazeLighter777** [comment]
I second this change. Adding games is a clear example of feature bloat. Jellyfin is a media server, and its core functionality should reflect that. Perhaps re adding the functionality in an addon is the most prudent choice.
