### ISSUE TITLE
Jellfin won't detect folders in user home directory.

### ISSUE THREAD

**Issue by apoorv569** [jellyfin/jellyfin#5931]
**Describe the bug**

Jellfin won't detect folders in user home directory.

**System (please complete the following information):**
 - OS: Ubuntu Server 21.04
 - Virtualization: No
 - Clients: Browser
 - Browser: Firefox
 - Jellyfin Version: 10.7.2.0

I fresh installed `Ubuntu` server edition 21.04, and installed `Jellyfin` on it, everything is great, but for some reason `Jellyfin` won't show any folders in `/home/username/`. I tried changing permissions to 777, 775, also tried `chown` to `root` both user and group and also `chown` to `jellyfin` nothing worked. I can't figure out what the problem is, already tried uninstalling and installing again as well.

**Comment by crobibero** [comment]
Please fill out the issue template, it’s there for a reason.

**Comment by aweadi11sun** [comment]
This problem is still occurring on ubuntu 23.04 with the latest flathub jellyfin server on firefox. Why was the issue closed in the first place since it doesn't appear to be solved?
