### ISSUE TITLE
Cant display Pictures on remote device

### ISSUE THREAD

**Issue by JonathanBrose** [jellyfin/jellyfin#5932]
If I cast content to the jellyfin app on tv or jellyfin in the browser i can watch Videos, but if i click on images nothing happens. If i click on them without casting it displays fine on my phone
using the latest version of jellyfin docker, and latest release of the android app

**Comment by smartypantsuk** [comment]
I have similar issues,  but with viewing photos on any device.
I can open a folder and swipe through the photos but then there it's no way to get back or out and it crashes. If I try using the android app to remote control my media PC and display photos on that,  they don't show up at all,  like in your case.

**Comment by mikebakke** [comment]
I hit this today on a standalone 10.7.5 version on a Pi. Pictures are visible to browse but clicking will not load and display the image. On a separate docker running 10.7.1 all is good.

The 10.7.5 log contains messages about being unable to get image dimensions and throwing exceptions for skia.skiencoder.

**Comment by mikebakke** [comment]
OK - I don't believe my issue is Jellyfin now. The images were failing to load in the Brave browser from a Linux Mint desktop and Macbook Air. However - I just fired up a laptop running MX linux and accessed from Brave on that and the images load just fine. Firefox works from Mint and Chrome from Android so it must be a setting in Brave I've configured differently between the machines - will look and try to isolate

**Comment by mikebakke** [comment]
There were no material config differences. The eventual solution was to nuke ALL cache and cookies in the Brave browsers on Mint and Macbook - works as intended now

**Comment by BaronGreenback** [comment]
@JonathanBrose image casting via DLNA PlayTo is currently being developed.

**Comment by JonathanBrose** [comment]
> @JonathanBrose image casting via DLNA PlayTo is currently being developed.

Does this mean if i remotely control a Jellyfin session on my browser with my phone, internally it uses DLNA PlayTo?
That would be very surprising to me, because the remote control work with DLNA PlayTo and DLNA disabled in the settings.

Viewing Pictures via remote control is still not working, I even tried running the newest 10.8.0 alpha 5, but still no luck.
Any updates on this?

**Comment by felix920506** [comment]
Is this still an issue?
