### ISSUE TITLE
Jellyfin cant find folders

### ISSUE THREAD

**Issue by erennnars** [jellyfin/jellyfin#5935]
**Describe the bug**
Jellyfin cant find newly created / some of the non-newly created folders. When i checked /etc/passwd because i couldnt give jellyfin root permissions and there is no jellyfin user at all

**System (please complete the following information):**
 - OS:Ubuntu 20.0.4 Server
 - Virtualization: Docker
 - Clients: Firefox
 - Browser: Firefox 72
 - Jellyfin Version:10.7.2-1-LS110 
 - Reverse Proxy: nginx/traefik
 - Base URL: media.domain.tld
 - Storage: local, external vfat

**To Reproduce**
Click add media library
chose wherever you mounted the external drive,
the folder doesnt show up, do chmod 777, still doesnt work
Try giving jellyfin sudo rights, user jellyfin doesnt exist

**Expected behavior**
I should be able to add my media libraries,
there should be a user named jellyfin

**Screenshots**
![image](https://user-images.githubusercontent.com/59098807/116617336-66a7a600-a946-11eb-9d21-4c8d46773bb3.png)

![image](https://user-images.githubusercontent.com/59098807/116617446-8212b100-a946-11eb-8ba5-8e959866f240.png)

**Comment by crobibero** [comment]
Did you mount the `/usr/music` folder into the Jellyfin container?

**Comment by apoorv569** [comment]
I'm having same problem.

**Comment by crobibero** [comment]
> I'm having same problem.

Saying this doesn’t add anything to the issue.

**Comment by erennnars** [comment]
> 
> 
> Did you mount the `/usr/music` folder into the Jellyfin container?

Oh i didnt , i was not aware that i should mount a folder into a folder . I will try and add the results.

**Comment by erennnars** [comment]
> 
> 
> Did you mount the `/usr/music` folder into the Jellyfin container?

Thanks a lot this worked after hours of reading documents and trying
