### ISSUE TITLE
Bandcamp music not working

### ISSUE THREAD

**Issue by Johnystar** [jellyfin/jellyfin#5940]
**Describe the bug**
FLAC music downloaded from Bandcamp doesn't correctly load embedded tags and can't be played or downloaded.

**System (please complete the following information):**
 - OS: DietPi v7.0.2
 - Virtualization: none
 - Clients: Tested with Jellyfin Media Player and the Brave web browser (Chromium based)
 - Browser: Brave 1.23.73 (Chromium 90.0.4430.85)
 - Jellyfin Version: 10.7.2 (updated to 10.7.5 since)
 - Playback: Direct play (Jellyfin Media Player) 
 - Installed Plugins: AnidDB, AniList, AniSearch, Anime, Anime (again), AudioDB, MusicBrainz, OMDb, Playback Reporting, Reports
 - Reverse Proxy: nginx
 - Base URL: none, using a separate subdomain
 - Networking: don't know
 - Storage: external drive

**To Reproduce**
1. Download music from Bandcamp (FLAC format) - [WiiU Grooves from Dj CUTMAN](https://music.djcutman.com/album/wiiu-grooves) is "name your price"
2. Load it into Jellyfin just like with any other piece of media
3. Tags loaded incorrectly or not at all and the media can't be played or downloaded

**Expected behavior**
Media gets tagged based on the tags embedded in the file and can be played just like any other piece of media. (and downloaded too)

**Logs**
```
[2021-04-30 20:50:52.371 +02:00] [INF] session.RemoteEndPoint : "192.168.1.47"
[2021-04-30 20:50:52.372 +02:00] [INF] StartPlaybackTimer : event_playing_id     = "b2b3d2015a65dbc19f78a4a0c5378fdd"
[2021-04-30 20:50:52.372 +02:00] [INF] StartPlaybackTimer : event_user_id        = "20b9057276404f05b690c17104cf20d6"
[2021-04-30 20:50:52.372 +02:00] [INF] StartPlaybackTimer : event_user_id_int    = 1
[2021-04-30 20:50:52.372 +02:00] [INF] StartPlaybackTimer : session_playing_id   = ""
[2021-04-30 20:50:52.372 +02:00] [INF] StartPlaybackTimer : session_user_id      = "20b9057276404f05b690c17104cf20d6"
[2021-04-30 20:50:52.372 +02:00] [INF] StartPlaybackTimer : play_method          = "na"
[2021-04-30 20:50:52.372 +02:00] [INF] StartPlaybackTimer : e.ClientName         = "Jellyfin Media Player"
[2021-04-30 20:50:52.372 +02:00] [INF] StartPlaybackTimer : e.DeviceName         = "ocean-desktop"
[2021-04-30 20:50:52.372 +02:00] [INF] StartPlaybackTimer : ItemName             = "Not Known - 01 - Dj CUTMAN - WiiU Grooves - Hot Tea & Firmware Updates (Not Known)"
[2021-04-30 20:50:52.373 +02:00] [INF] StartPlaybackTimer : ItemId               = "b2b3d2015a65dbc19f78a4a0c5378fdd"
[2021-04-30 20:50:52.373 +02:00] [INF] StartPlaybackTimer : ItemType             = "Audio"
[2021-04-30 20:50:52.373 +02:00] [INF] StartPlaybackTimer : Details do not match for play item
[2021-04-30 20:50:52.373 +02:00] [INF] StartPlaybackTimer : Exited
  ```

**Screenshots**
![image](https://user-images.githubusercontent.com/29976879/116743405-2b19e400-a9f9-11eb-9082-9e7124f7b9db.png)
No artist name

**Additional context**
I think that's all.

**Comment by Darkwolf1515** [comment]
Music I’ve downloads from bandcamp has been fine, your artist probably just forgot to add their tags. Nothing special about how bandcamp tags stuff, it’s the same as any flac.

**Comment by Johnystar** [comment]
> Music I’ve downloaded from bandcamp has been fine, your artist probably just forgot to add their tags. Nothing special about how bandcamp tags stuff, it’s the same as any flac.
> 
> download mp3tag and take a look that it’s correct.

I've editted all of the tags with [EasyTAG](https://wiki.gnome.org/Apps/EasyTAG) (Gnome project) and this happens only and with all of my music that I downloaded from Bandcamp. Weird it doesn't happen to you.

I'll look further into it on my side, but this really only happens to me with Bandcamp music and with all of it, even after editting the tags with EasyTAG. I'll especially take a look at mp3tag when I have the time and see if that helps, would be great if Jellyfin could deal with these files like any other media player though. ([Lollypop](https://wiki.gnome.org/Apps/Lollypop) (also Gnome) handles the files just fine)

**Comment by Johnystar** [comment]
@Darkwolf1515 Mp3tag, unfortunately, isn't available for Linux and I don't have access to a working Windows machine.

**Comment by Darkwolf1515** [comment]
![image](https://user-images.githubusercontent.com/65789901/116930483-adcabb00-ac14-11eb-89a1-4b49702fb508.png)
Works fine for me, how are your folder set up? (no, i retagged nothing)

**Comment by Johnystar** [comment]
> ![image](https://user-images.githubusercontent.com/65789901/116930483-adcabb00-ac14-11eb-89a1-4b49702fb508.png)
> Works fine for me, how is your folder set up? (no, i retagged nothing)
> 
> Should be set up like this
> ![image](https://user-images.githubusercontent.com/65789901/116930665-e66a9480-ac14-11eb-8083-c899340764e5.png)

yeah, that is how I have it set up as well

![image](https://user-images.githubusercontent.com/29976879/116938947-cadea880-ac6b-11eb-984e-fc6e1738c0c0.png)

I'm wondering if it could be somehow related to the host machine I'm using. It's a Raspberry Pi 4 running DietPi with Jellyfin installed from official repositories and the media being stored on an ext4 partition on an external drive.

I double-checked if the problem is still there and it certainly is, even after refreshing the tags.

There is one more thing I could think of.  There used to be an NTFS partition on the disk and at one point I encountered an I/O error. I ended up powering off the host machine, copying the files from the drive somewhere else, reformatting it completely, and putting everything back onto an ext4 partition on the drive. I wonder if that I/O error could've possibly messed up Jellyfin's metadata database, even though it's saved on the Pi's microSD card...

**Comment by Johnystar** [comment]
![image](https://user-images.githubusercontent.com/29976879/118944312-bdf0d300-b954-11eb-8c7e-c98856a82189.png)
Still a problem, even after updating to the newest version. (currently on 10.7.5)

**Comment by Johnystar** [comment]
No longer a Bandcamp-only problem.
![image](https://user-images.githubusercontent.com/29976879/119009540-835a5b00-b993-11eb-9f88-f685c4678130.png)
Same happened to an Animal Crossing New Horizons gamerip album. Still no idea why, all of the albums show up just fine in Lollypop.
![image](https://user-images.githubusercontent.com/29976879/119009673-a97ffb00-b993-11eb-88cd-4958ffbb2ff6.png)
![image](https://user-images.githubusercontent.com/29976879/119009757-c0265200-b993-11eb-8728-b2ecf9db614f.png)
![image](https://user-images.githubusercontent.com/29976879/119009808-c9afba00-b993-11eb-96ea-19880d84c13e.png)

**Comment by Johnystar** [comment]
![image](https://user-images.githubusercontent.com/29976879/119896878-f0e02b80-bf3f-11eb-8618-c2f94e250774.png)
Added Antidote today, which I bought from Beatport in ``wav`` audio format and losslessly converted to ``flac`` via Audacity and then tagged with EasyTAG as I do with all my music.

**Comment by Johnystar** [comment]
This issue still persists, however, I'll be reinstalling Jellyfin from the ground up on a new server soon. I'm hoping that this reinstallation could maybe solve the issue somehow.

**Comment by Johnystar** [comment]
Now that I've reinstalled Jellyfin on a different server everything seems to be working fine again. My guess is that the cache or something like that got corrupted before and wasn't able to correct itself. Whatever the case may be, this issue is now solved for me.
