### ISSUE TITLE
QSV Hardware Decoding issue

### ISSUE THREAD

**Issue by vayed** [jellyfin/jellyfin#5947]
Hey there,

because my CPU is running on 100% while transcoding 4k Movies. I tried to use Hardware Decoding. But it will not work. Everytime I get the same error from ffmpeg. Because I'm not familiar with ffmpeg I have no Idea whats the issue.

**Media Info of the file**
endstation-pets.2016-2160p
Containermkv
PfadM:\Filme\Pets.2016.GERMAN.DL.2160p.UHD.BluRay.x265-ENDSTATiON\endstation-pets.2016-2160p.mkv
Größe9211 MB
Video
Title4K HEVC HDR
CodecHEVC
ProfilMain 10
Level153
Auflösung3840x2076
Seitenverhältnis1.85:1
Interlaced/ZeilensprungverfahrenNo
Bildrate23.976025
Bitrate14895 kbps
Video-BereichHDR
Farbraumbt2020nc
Farbübertragungsmpte2084
Hauptfarbenbt2020
Pixelformatyuv420p10le
Ref Frames1
Audio
TitleGer - Dolby Digital+ - 6 ch - Default
Spracheger
CodecEAC3
Kanäle6 ch
Bitrate1152 kbps
Sample-Rate48000 Hz
StandardYes

**FFmpeg Logs**
ffmpeg version n4.3.1-Jellyfin Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10.2.0 (Rev6, Built by MSYS2 project)
  configuration:  --disable-static --enable-shared --cc='ccache gcc' --cxx='ccache g++' --extra-version=Jellyfin --disable-ffplay --disable-debug --enable-gpl --enable-version3 --enable-bzlib --enable-iconv --enable-lzma --enable-zlib --enable-sdl2 --enable-fontconfig --enable-gmp --enable-libass --enable-libzimg --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libdav1d --enable-opencl --enable-dxva2 --enable-d3d11va --enable-amf --enable-libmfx --enable-cuda --enable-cuda-llvm --disable-cuda-nvcc --enable-cuvid --enable-nvenc --enable-nvdec --enable-ffnvcodec --enable-gnutls
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[matroska,webm @ 0000009269474100] Could not find codec parameters for stream 5 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[matroska,webm @ 0000009269474100] Could not find codec parameters for stream 6 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[matroska,webm @ 0000009269474100] Could not find codec parameters for stream 7 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Guessed Channel Layout for Input Stream #0.1 : 5.1
Input #0, matroska,webm, from 'file:M:\Filme\Pets.2016.GERMAN.DL.2160p.UHD.BluRay.x265-ENDSTATiON\endstation-pets.2016-2160p.mkv':
  Metadata:
    encoder         : libebml v1.3.5 + libmatroska v1.4.8
    creation_time   : 2018-02-05T18:38:42.000000Z
  Duration: 01:26:27.18, start: 0.000000, bitrate: 14895 kb/s
    Chapter #0:0: start 0.000000, end 305.847000
    Metadata:
      title           : Chapter 1
    Chapter #0:1: start 305.847000, end 564.063000
    Metadata:
      title           : Chapter 2
    Chapter #0:2: start 564.063000, end 798.839000
    Metadata:
      title           : Chapter 3
    Chapter #0:3: start 798.839000, end 1083.665000
    Metadata:
      title           : Chapter 4
    Chapter #0:4: start 1083.665000, end 1334.458000
    Metadata:
      title           : Chapter 5
    Chapter #0:5: start 1334.458000, end 1731.855000
    Metadata:
      title           : Chapter 6
    Chapter #0:6: start 1731.855000, end 1974.847000
    Metadata:
      title           : Chapter 7
    Chapter #0:7: start 1974.847000, end 2215.838000
    Metadata:
      title           : Chapter 8
    Chapter #0:8: start 2215.838000, end 2547.294000
    Metadata:
      title           : Chapter 9
    Chapter #0:9: start 2547.294000, end 2686.767000
    Metadata:
      title           : Chapter 10
    Chapter #0:10: start 2686.767000, end 3021.226000
    Metadata:
      title           : Chapter 11
    Chapter #0:11: start 3021.226000, end 3285.407000
    Metadata:
      title           : Chapter 12
    Chapter #0:12: start 3285.407000, end 3573.987000
    Metadata:
      title           : Chapter 13
    Chapter #0:13: start 3573.987000, end 3756.544000
    Metadata:
      title           : Chapter 14
    Chapter #0:14: start 3756.544000, end 4032.361000
    Metadata:
      title           : Chapter 15
    Chapter #0:15: start 4032.361000, end 4386.840000
    Metadata:
      title           : Chapter 16
    Chapter #0:16: start 4386.840000, end 4564.601000
    Metadata:
      title           : Chapter 17
    Chapter #0:17: start 4564.601000, end 4728.056000
    Metadata:
      title           : Chapter 18
    Chapter #0:18: start 4728.056000, end 4798.835000
    Metadata:
      title           : Chapter 19
    Chapter #0:19: start 4798.835000, end 5187.182000
    Metadata:
      title           : Chapter 20
    Stream #0:0: Video: hevc (Main 10), yuv420p10le(tv, bt2020nc/bt2020/smpte2084), 3840x2076 [SAR 1:1 DAR 320:173], 23.98 fps, 23.98 tbr, 1k tbn, 23.98 tbc (default)
    Metadata:
      BPS             : 8195022
      BPS-eng         : 8195022
      DURATION        : 01:26:27.182000000
      DURATION-eng    : 01:26:27.182000000
      NUMBER_OF_FRAMES: 124368
      NUMBER_OF_FRAMES-eng: 124368
      NUMBER_OF_BYTES : 5313634063
      NUMBER_OF_BYTES-eng: 5313634063
      _STATISTICS_WRITING_APP: mkvmerge v17.0.0 ('Be Ur Friend') 64-bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v17.0.0 ('Be Ur Friend') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2018-02-05 18:38:42
      _STATISTICS_WRITING_DATE_UTC-eng: 2018-02-05 18:38:42
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:1(ger): Audio: eac3, 48000 Hz, 5.1, fltp (default)
    Metadata:
      BPS             : 1152000
      BPS-eng         : 1152000
      DURATION        : 01:26:27.168000000
      DURATION-eng    : 01:26:27.168000000
      NUMBER_OF_FRAMES: 162099
      NUMBER_OF_FRAMES-eng: 162099
      NUMBER_OF_BYTES : 746952192
      NUMBER_OF_BYTES-eng: 746952192
      _STATISTICS_WRITING_APP: mkvmerge v17.0.0 ('Be Ur Friend') 64-bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v17.0.0 ('Be Ur Friend') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2018-02-05 18:38:42
      _STATISTICS_WRITING_DATE_UTC-eng: 2018-02-05 18:38:42
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:2(eng): Audio: truehd, 48000 Hz, 7.1, s32 (24 bit)
    Metadata:
      BPS             : 4764449
      BPS-eng         : 4764449
      DURATION        : 01:26:27.125000000
      DURATION-eng    : 01:26:27.125000000
      NUMBER_OF_FRAMES: 6224550
      NUMBER_OF_FRAMES-eng: 6224550
      NUMBER_OF_BYTES : 3089224414
      NUMBER_OF_BYTES-eng: 3089224414
      _STATISTICS_WRITING_APP: mkvmerge v17.0.0 ('Be Ur Friend') 64-bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v17.0.0 ('Be Ur Friend') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2018-02-05 18:38:42
      _STATISTICS_WRITING_DATE_UTC-eng: 2018-02-05 18:38:42
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:3(eng): Audio: ac3, 48000 Hz, 5.1(side), fltp, 640 kb/s
    Metadata:
      BPS             : 640000
      BPS-eng         : 640000
      DURATION        : 01:26:27.168000000
      DURATION-eng    : 01:26:27.168000000
      NUMBER_OF_FRAMES: 162099
      NUMBER_OF_FRAMES-eng: 162099
      NUMBER_OF_BYTES : 414973440
      NUMBER_OF_BYTES-eng: 414973440
      _STATISTICS_WRITING_APP: mkvmerge v17.0.0 ('Be Ur Friend') 64-bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v17.0.0 ('Be Ur Friend') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2018-02-05 18:38:42
      _STATISTICS_WRITING_DATE_UTC-eng: 2018-02-05 18:38:42
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:4(ger): Subtitle: subrip (default) (forced)
    Metadata:
      BPS             : 1
      BPS-eng         : 1
      DURATION        : 01:24:43.829000000
      DURATION-eng    : 01:24:43.829000000
      NUMBER_OF_FRAMES: 27
      NUMBER_OF_FRAMES-eng: 27
      NUMBER_OF_BYTES : 689
      NUMBER_OF_BYTES-eng: 689
      _STATISTICS_WRITING_APP: mkvmerge v17.0.0 ('Be Ur Friend') 64-bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v17.0.0 ('Be Ur Friend') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2018-02-05 18:38:42
      _STATISTICS_WRITING_DATE_UTC-eng: 2018-02-05 18:38:42
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:5(ger): Subtitle: hdmv_pgs_subtitle
    Metadata:
      BPS             : 830
      BPS-eng         : 830
      DURATION        : 01:24:43.829000000
      DURATION-eng    : 01:24:43.829000000
      NUMBER_OF_FRAMES: 54
      NUMBER_OF_FRAMES-eng: 54
      NUMBER_OF_BYTES : 527742
      NUMBER_OF_BYTES-eng: 527742
      _STATISTICS_WRITING_APP: mkvmerge v17.0.0 ('Be Ur Friend') 64-bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v17.0.0 ('Be Ur Friend') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2018-02-05 18:38:42
      _STATISTICS_WRITING_DATE_UTC-eng: 2018-02-05 18:38:42
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:6(ger): Subtitle: hdmv_pgs_subtitle
    Metadata:
      BPS             : 32280
      BPS-eng         : 32280
      DURATION        : 01:24:58.802000000
      DURATION-eng    : 01:24:58.802000000
      NUMBER_OF_FRAMES: 2518
      NUMBER_OF_FRAMES-eng: 2518
      NUMBER_OF_BYTES : 20573778
      NUMBER_OF_BYTES-eng: 20573778
      _STATISTICS_WRITING_APP: mkvmerge v17.0.0 ('Be Ur Friend') 64-bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v17.0.0 ('Be Ur Friend') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2018-02-05 18:38:42
      _STATISTICS_WRITING_DATE_UTC-eng: 2018-02-05 18:38:42
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:7(eng): Subtitle: hdmv_pgs_subtitle
    Metadata:
      BPS             : 42079
      BPS-eng         : 42079
      DURATION        : 01:26:00.072000000
      DURATION-eng    : 01:26:00.072000000
      NUMBER_OF_FRAMES: 3390
      NUMBER_OF_FRAMES-eng: 3390
      NUMBER_OF_BYTES : 27141908
      NUMBER_OF_BYTES-eng: 27141908
      _STATISTICS_WRITING_APP: mkvmerge v17.0.0 ('Be Ur Friend') 64-bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v17.0.0 ('Be Ur Friend') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2018-02-05 18:38:42
      _STATISTICS_WRITING_DATE_UTC-eng: 2018-02-05 18:38:42
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (hevc_qsv) -> h264 (h264_qsv))
  Stream #0:1 -> #0:1 (eac3 (native) -> aac (native))
Press [q] to stop, [?] for help
Error creating a QSV device
qsv hwaccel requested for input stream #0:0, but cannot be initialized.
[hevc_qsv @ 00000092694b3340] Error initializing the MFX video decoder: invalid handle (-6)
Error while decoding stream #0:0: Invalid argument

**Server System:**
 - OS: Windows Server 2012 R2
 - Jellyfin Version: 10.7.2
 - Hardware settings & device: QSV on Intel Xeon E3-1245
 - Reverse proxy: no
 - Other hardware notes: no
 
**Client System (please complete the following information):**
 - Device: Chromecast, Android Phone
 - OS: Android TV, Android

**Comment by nyanmisaka** [comment]
HEVC 10-bit decoding is supported since Kaby Lake processors. So the Haswell processor doesn't support it.
