### ISSUE TITLE
Refreshing of media libraries stopps with error 

### ISSUE THREAD

**Issue by Battlestar1965** [jellyfin/jellyfin#5959]
**Describe the bug**
When trying to (re)scan the media libraries, the process starts, but stops after a few seconds with an error message in the log file.
The process stops after approximately 34 to 36 % according to the visible process bar.
Problem is, all the cover thumnails of the movies / tv Shows are not visible, although they ar present in the corresponding folders.

**System (please complete the following information):**
 - OS: Windows 10 Home
          Version	20H2

 - Virtualization: [e.g. Docker, KVM, LXC] what do you mean with that?
 - Clients:  Browser, Android on TV
 - Browser: MS Edge
 - Jellyfin Version: 10.7.2
 - Playback: [Direct Play, Remux, Direct Stream, Transcode] 
 - Installed Plugins: "Bookshelf" "5.0.0.0"
 "Fanart" "6.0.0.0"
 "Open Subtitles" "10.0.0.0"
"Reports" "11.0.0.0"
"TheTVDB" "4.0.0.0"
"TMDb Box Sets" "7.0.0.0"
 "TV Maze" "5.0.0.0"
"OMDb" "10.7.2.0"
 "MusicBrainz" "10.7.2.0"
"AudioDB" "10.7.2.0"
 - Reverse Proxy: [e.g. none, nginx, apache, etc.] häh?
 - Base URL: http://localhost:8096/
 - Networking: [e.g. Host, Bridge/NAT] häh?
 - Storage: Movies and TV Shows on external harddrives connected via USB

**To Reproduce**

1. Go to ADMIN  - Overview
2. Click on "Scan all Libraries"
3. Go to "Planned Tasks"
4. See error at "Library - Scan Media Libray"

**Expected behavior**
When some or all the of cover thumbnails of the movies and tv shows in the libraries are not shown on the UI, i usually refresh/ rescan the libraries and the covers are visible again. Expected behaviour....simply (re)scan all libraries to 100 % and do not stop with an error message after approximately 34 to 37 %

> **Logs**
[log_20210503_1.log](https://github.com/jellyfin/jellyfin/files/6413633/log_20210503_1.log)

**Screenshots**

**Additional context**
Tried my best...sorry...english is not my native language....

**Comment by cvium** [comment]
The problem is two-fold.

1. Server is not handling the exception.
2. tvdb plugin shouldn't be throwing an exception.

**Comment by Battlestar1965** [comment]
Update on the library scan issue

I got a new pc, fresh and updated windows installation, new installation of jellyfin 10.7.5 stable version and entirely new setup of the libraries in jellyfin. Initial scan of the libraries worked.

After that every attempt to rescan the libraries failed after a few seconds as it happend before with jellyfin 10.7.2 on the other pc

log file attached
[log_20210512.log](https://github.com/jellyfin/jellyfin/files/6463843/log_20210512.log)

**Comment by Battlestar1965** [comment]
Another and from my side last update on library scan issue.

Deinstalled 10.7.5 complete including all settings etc. Reinstalled 10.6.4, all is working just fine. Scanning of library, rescanning/updating works fine, no problems.

**Comment by Bond-009** [comment]
Closing as stale
