### ISSUE TITLE
Live TV Recording naming format selection/chose own

### ISSUE THREAD

**Issue by drakus72** [jellyfin/jellyfin#597]
**Is your feature request related to a problem? Please describe.**
Currently when recording it adds the year to the dir name (EX: Touched by an Angel (1994)), before They added the year, I had no problems with recordings and complained to the other people and asked to have it changed back/choice/chose our own naming format. Example of recording problems is The Flash, it always grabs the metadata for older one from 1990 and not the one from 2014. I know this isn't the guide data, but something under the hood causing it to grab the wrong metadata and should be looked into as well.

**Describe the solution you'd like**
Would like to see an option to where we can choose our own naming format for recorded tv such as:

%showname %year/%showname - %S%E - %showtitle.ext

The %S would be S01 & %s would be S1 same with %E 01 or %e 1

This is just an example and I know there are more options like when you are tagging/renaming a mp3 file, everyone has their own naming structure they use.

I hope all this makes sense LOL
I feel that this would help with Jellyfin getting the wrong metadata for the show since it would be tagged correctly already.

**Comment by sparky8251** [comment]
Unsure if this is a regression, but at the least it should also be tagged with `bug` and `backend`.
