### ISSUE TITLE
Playback not working on 10.7.3

### ISSUE THREAD

**Issue by jmqm** [jellyfin/jellyfin#5971]
**Describe the bug**
Playback stopped working when I updated.
No modifications to the Docker image has been image.

**System:**
 - OS: Linux (Synology NAS)
 - Virtualization: Docker
 - Clients: Chrome Browser, Jellyfin Media Player, Jellyfin MPV Shim, Jellyfin Android
 - Browser: Chrome 90, JMP 1.5.0, MPV Shim 2.0.1
 - Jellyfin Version: 10.7.3
 - Playback: Direct Play, Remux, Direct Stream, Transcode
 - Installed Plugins: [e.g. none, Fanart, Anime, etc.]
 - Reverse Proxy: None
 - Base URL: HOSTNAME.local and IP
 - Networking: Bridge
 - Storage: NAS

**To Reproduce**
1. Go to any media's card.
2. Click on the play button.

**Expected behavior**
Play the video.

**Logs**
![image](https://user-images.githubusercontent.com/68612932/117087812-38471380-ad16-11eb-80fb-5178a949836b.png)

**Additional context**
No modifications to the image has been made.
This was a bug likely introduced with 10.7.3.

**Comment by crobibero** [comment]
This is already known and fixed by https://github.com/jellyfin/jellyfin/pull/5969
