### ISSUE TITLE
SyncPlay Forcing Remaking Group on Changing Series

### ISSUE THREAD

**Issue by aaron-warren** [jellyfin/jellyfin#5976]
**Describe the bug**

In the previous versions, it was possible to make a syncplay group and then choose whatever you wanted to watch. In the latest version, if you make a group the play button on any media stops working.

**System (please complete the following information):**
 - OS: Linux
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Edge 90.0.818.51
 - Jellyfin Version: 10.7.5
 - Playback: Direct Play
 - Installed Plugins: InfuseSync
 - Reverse Proxy: Nginx
 - Base URL: none
 - Networking: Host
 - Storage: Local

**To Reproduce**

1. Create a SyncPlay Group
2. Attempt to play any tv show or movie
3. Play button will not work, forces you to start the media and then make the group

**Expected behavior**

The media should be able to play just from clicking the play button instead of forcing you to leave the group, play the media, then remake the group.

**Logs**

[log_20210504.log](https://github.com/jellyfin/jellyfin/files/6425269/log_20210504.log)

**Comment by harsh0596** [comment]
This is happening to me too. Created a group in home page, had my friend join the group. When trying to play something, the network throws a 405:

![image](https://user-images.githubusercontent.com/11883323/143529699-581ae9d0-d029-440b-b8e9-ad5616054662.png)

cant find anything in the jellyfin dashboard logs

workaround of starting before creating group works for me

**Comment by rathmerdominik** [comment]
I bump this.
Still happening to this day
