### ISSUE TITLE
Show improved version information to users

### ISSUE THREAD

**Issue by joshuaboniface** [jellyfin/jellyfin#599]
A spin-off discussion from #508 and #509.

Let's discuss our opinions and philosophical arguments for various forms of improved user versioning information.

**Comment by joshuaboniface** [comment]
# What I'd like to see

1. A numerical version string that is consistent with our release versions.
1. On dev builds, a commit hash of where the repo was at build-time. Not just the main repo, but the `jellyfin-web` repo as well.

# Why?

1. Users need to see the version quickly but not be confused by additional information.
2. Developers need to be able to quickly troubleshoot where they are on each dev build.

**Comment by EraYaN** [comment]
I can modify the #508 to contain those pieces of info. But that won't reduce it's complexity in anyway. You will still need a script, a file and something to parse it. We can debate for a long time about what the least complex file format is, but frankly it really doesn't matter. For all I care it's fucking json if that makes anyone happy.

Long story short, we will end up if we want the above points at the same level of complexity regardless. All the other points are implementation details, and are frankly a lot more inconsequential.

**Comment by ploughpuff** [comment]
@joshuaboniface I have put together a 'help' page for devs when running from command line:
https://github.com/ploughpuff/jellyfin/commit/61eb8a9e3c4edc3dc513cb7755c5c2affcd2d827

Worth pursuing with?

**Comment by JustAMan** [comment]
Great find by @anthonylavado: https://github.com/AArnott/Nerdbank.GitVersioning

**Comment by EraYaN** [comment]
Well it will only stamp the current git version of one repo, AND it will not use a three part semver but only a 2 part semver. If you can live with that concession, I guess yes.
