### ISSUE TITLE
Add a webradio section and GUI ?

### ISSUE THREAD

**Issue by gordielachance** [jellyfin/jellyfin#5998]
One of the reason I would install a media server would be to be able to play my favorite web radios everywhere; including on any device of my home.

I’m just starting to have a look at Jellyfin; and it seems really good.
I’ve read it is possible to add live streams [using a m3u URL](https://jellyfin.org/docs/general/server/media/internet-radio.html), but this not really user-friendly.

When you create a new playlist, it is currently not possible to link a m3u URL using the frontend;
 Also, it would be so great to have a « web radios » section in the main menu...

Is there some developement on the roadmap for such a feature ?

Thanks!

**Comment by crobibero** [comment]
We don't have a roadmap, and feature requests belong at https://features.jellyfin.org/.
There are already a few "radio" feature requests: https://features.jellyfin.org/?query=radio

**Comment by gordielachance** [comment]
Okay, thanks!
