### ISSUE TITLE
Replace Emby Logging Mechanism with Log4Net

### ISSUE THREAD

**Issue by dcrdev** [jellyfin/jellyfin#60]
I've thought for a while know that the logging mechanism has been somewhat lacklustre - it's impossible to read, has no rotation options and is not rendered in any significant way within the interface.

Therefore I propose we replace logging with Apache Log4Net which is probably the most widely used logging framework within the .NET community. 

Specifically this would allow for 3 things:
- Easy logging to a SQLite database
- Strict formatting conventions
- Easily abstracted and extractable through a common interface - we could display this in a filterable datatable in the admin interface as oppose to a link to a text file.

**Comment by ryanjerskine** [comment]
Serilog is another option. Seems pretty popular with newer Core projects. Not sure on a feature comparison though.

**Comment by Bond-009** [comment]
I have used Serilog in the past, and really like it. It's super easy to set up and customize.

**Comment by JustAMan** [comment]
Fixed by #285
