### ISSUE TITLE
Subtitles play for 2 video files

### ISSUE THREAD

**Issue by Akirainblack** [jellyfin/jellyfin#6004]
**Describe the bug**
When playing an episode with built in subtitles (eg: The Blacklist.S02E09.Luther Braxton) they play correctly.
However when jellyfin then starts playing the next episode with no subs(eg: The Blacklist.S02E10.Luther Braxton - Conclusion) a message then pops up at the bottom saying something similar to loading subtitles and it loads the subtitles from the previous episode

**System (please complete the following information):**
 - OS: linux
 - Virtualization: docker
 - Clients: android
 - Browser: jellyfin app and browser
 - Jellyfin Version: 10.7.5
 - Playback: Direct Play
 - Installed Plugins: playback reporting, open subtitles
 - Reverse Proxy: none
 - Base URL: none
 - Networking: bridge
 - Storage: local

**To Reproduce**

1. Play an episode with built in subtitles (eg: The Blacklist.S02E11.Ruslan Denisov)
2. Watch the episode and let it start the next automatically (eg: The Blacklist.S02E12.The Kenyon Family)
3. Watch the episode and the subs from the previous episode play, with no way to disable them.

**Expected behavior**

Step 3 above... Watch episode without subs as it shouldn't have any.
**Logs**
Several thousand lines of logs. Anything in particular you're interested in?
This is the section with the playback information for the 2 videos
[playback.log](https://github.com/jellyfin/jellyfin/files/6440565/playback.log)

**Comment by Akirainblack** [comment]
No comment or acknowledgement?

**Comment by HybridSarcasm** [comment]
This has been open quite a while. Can this be re-produced with the current build? If so, please update the bug report details. Thanks!

**Comment by sevenrats** [comment]
@Akirainblack please open this issue in the appropriate client repo if you are able to reproduce it. Thank you for your contribution!
