### ISSUE TITLE
HTTP 415 when resetting password

### ISSUE THREAD

**Issue by TheDutchMC** [jellyfin/jellyfin#6007]
**Describe the bug**

When resetting a password, pressing submit does nothing and gives HTTP 415: Unsupported Media Type in the browser console

**System (please complete the following information):**
 - OS: [e.g. Debian, Windows] Ubuntu 20.04
 - Virtualization: [e.g. Docker, KVM, LXC] LXD LXC container
 - Clients: [Browser, Android, Fire Stick, etc.] Browser
 - Browser: [e.g. Firefox 72, Chrome 80, Safari 13] Edge, Chrome 90.0.818.51
 - Jellyfin Version: [e.g. 10.4.3, nightly 20191231] 10.7.0
 - Playback: [Direct Play, Remux, Direct Stream, Transcode] N.a 
 - Installed Plugins: [e.g. none, Fanart, Anime, etc.] None
 - Reverse Proxy: [e.g. none, nginx, apache, etc.] None
 - Base URL: [e.g. none, yes: /example] N.a
 - Networking: [e.g. Host, Bridge/NAT] Macvlan
 - Storage: [e.g. local, NFS, cloud] NFS

**To Reproduce**

1. Open the password reset screen
2. Enter your username, mine is an email address
3. Press Submit
4. Observe nothing happens, and observe errors in the browser console

**Expected behavior**

Something happens indicating what to do next

**Logs**

None were logged

**Screenshots**

![image](https://user-images.githubusercontent.com/28569170/117494393-8c4f3380-af74-11eb-9e9b-7490f33fcac4.png)

**Additional context**

**Comment by TheDutchMC** [comment]
After updating to 10.7.5, it displays the symptoms mentioned in #4129, so the PR there apparently did not fix it, or is not yet released :D

**Comment by TheDutchMC** [comment]
On which release should that be available then?

**Comment by nielsvanvelzen** [comment]
10.8 probably

**Comment by TheDutchMC** [comment]
Check. Will close this then as it seems fixed then.

Thanks!
