### ISSUE TITLE
Invalid repository after upgrading to Ubuntu 21.04

### ISSUE THREAD

**Issue by michelleDeko** [jellyfin/jellyfin#6011]
I upgraded from Ubuntu 20.10 to Ubuntu 21.04 and now the repository of jellyfin isn't working anymore. Error I get: 
Err:13 https://repo.jellyfin.org/ubuntu hirsute Release
  404  Not Found [IP: 2604:a880:cad:d0::cf3:f001 443]
Hit:14 https://packages.gitlab.com/gitlab/gitlab-ce/ubuntu hirsute InRelease

**System (please complete the following information):**
 - OS: Ubuntu 21.04
 - Virtualization: KVM

**To Reproduce**

1. Upgrade to Ubuntu 21.04

**Comment by sabas** [comment]
@michelleDeko I changed in the entry from hirsute to groovy and works at the moment while the developers create the new release

**Comment by srcrist** [comment]
Closing this issue as Ubuntu 21.04 has reached end of life.
