### ISSUE TITLE
Frontend not working on dev

### ISSUE THREAD

**Issue by taconaut** [jellyfin/jellyfin#602]
**Describe the bug**
When running Jellyfin on dev branch from Visual Studio, the loaded page shows: 'Could not find a part of the path 'jellyfin-web\src\index.html'.'
I do not encounter this issue on master.

**To Reproduce**
1. Checkout the Jellyfin repository
2. Switch to dev branch
3. Build application in Visual Studio
4. Run (Debug) Jellyfin.Server

**Expected behavior**
The Jellyfin frontend is being shown

**Logs**
Please paste any log errors.

**Screenshots**

**System (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Jellyfin Version: Current dev head (c2dd5baab7d4ff2c5cf089c394e3d7b12dd7de20)

**Comment by cvium** [comment]
Have you initialized the submodules? `git submodule update --init`

**Comment by taconaut** [comment]
I hadn't. Running it solved my issue. Thanks!

Is there a place I should have checked to be aware of this change?

**Comment by ploughpuff** [comment]
I had this last night.  Somehow flicking between branches caused my jellywin-web to become screwed.  I then received git errors like "warning: unable to rmdir 'MediaBrowser.WebDashboard/jellyfin-web': Directory not empty".

**Comment by cvium** [comment]
@taconaut https://jellyfin.readthedocs.io/en/latest/user-docs/building/

It's not really explicitly stated that the ui has been submoduled though.
