### ISSUE TITLE
Feature Request: Toggle folder type in "Other" library in web client

### ISSUE THREAD

**Issue by jd1123** [jellyfin/jellyfin#6021]
I am using the "Other" library type with various subfolders. When I add these folders, the server misidentifies some of them as "Show" types instead of listing it as a "Folder" type. As far as I can tell, there is no way to specify which type the folder should be in the web client.

I have found a workaround by manually editing the "library.db" file to change these entries, but this is tedious and error prone. It would be nice to be able to toggle the folder type in the web client.

```
UPDATE TypedBaseItems
SET type='MediaBrowser.Controller.Entities.Movies.Movie'
WHERE Path LIKE '%foldername%';

UPDATE TypedBaseItems
SET type='MediaBrowser.Controller.Entities.Folder'
WHERE Path='/path/to/foldername';

UPDATE TypedBaseItems
SET SeasonName=NULL
WHERE Path LIKE '%foldername%';

UPDATE TypedBaseItems
SET SeriesName=NULL
WHERE Path LIKE '%foldername%';

UPDATE TypedBaseItems
SET UnratedType='Movie'
WHERE Path LIKE '%foldername%';

UPDATE TypedBaseItems
SET UnratedType='Other'
WHERE Path='/path/to/foldername';

DELETE FROM TypedBaseItems WHERE SeriesName LIKE '%foldername%';
```

**Comment by crobibero** [comment]
Feature requests belong here: features.jellyfin.org/
