### ISSUE TITLE
Uploading subtitles requires a manual metadata refresh

### ISSUE THREAD

**Issue by rpthms** [jellyfin/jellyfin#6028]
When I upload a subtitle manually, I also have to do a "Refresh Metadata" before the subtitle actually
shows up on the Jellyfin Web interface.

**System (please complete the following information):**
 - OS: Ubuntu 20.04
 - Virtualization: Docker
 - Clients: Browser, Android
 - Browser: Firefox 88
 - Jellyfin Version: 10.7.5
 - Playback: Direct Play, Transcode
 - Reverse Proxy: nginx
 - Base URL: none
 - Networking: Host
 - Storage: local

**To Reproduce**

1. Go to a Movie/TV Show
2. Click on the '3 dots' icon and click 'Edit subtitles'
3. Click the '+' icon to manually upload a subtitle
4. Select the subtitle, choose the language and click 'Upload'

**Expected behavior**
I should be able to use the subtitles as soon as I upload them.

**Logs**
When I enable debug logging, I can see the LibraryMonitor ignoring changes to the subtitle:

```
[2021-05-11 07:33:59.139 +00:00] [INF] [40] MediaBrowser.Providers.Subtitles.SubtitleManager: Saving subtitles to "/jellyfin-media/Movies/Dunkirk (2017)/Dunkirk (2017).eng.srt"
[2021-05-11 07:33:59.156 +00:00] [DBG] [18] Emby.Server.Implementations.IO.LibraryMonitor: Ignoring change to "/jellyfin-media/Movies/Dunkirk (2017)/Dunkirk (2017).eng.srt"
[2021-05-11 07:33:59.156 +00:00] [DBG] [18] Emby.Server.Implementations.IO.LibraryMonitor: Ignoring change to "/jellyfin-media/Movies/Dunkirk (2017)/Dunkirk (2017).eng.srt"
```

**Screenshots**

1. Go to a Movie. In my case I'm using Dunkirk

![Screenshot_2021-05-11 Jellyfin](https://user-images.githubusercontent.com/10009712/117782132-f6aaf100-b25e-11eb-9155-e7050a74f15a.png)

2. Click the '3 dots' and then click 'Edit subtitles'

![Screenshot_2021-05-11 Jellyfin(1)](https://user-images.githubusercontent.com/10009712/117782323-21954500-b25f-11eb-8ccb-503edcd38b15.png)

3. Click the '+' icon to manually upload the subtitle

![Screenshot_2021-05-11 Jellyfin(2)](https://user-images.githubusercontent.com/10009712/117782436-412c6d80-b25f-11eb-817b-2cc47bb65bc0.png)

4. Select the subtitle, choose the language and hit 'Upload'

![Screenshot_2021-05-11 Jellyfin(3)](https://user-images.githubusercontent.com/10009712/117782566-602aff80-b25f-11eb-8847-080e3cd99777.png)

5. Subtitles don't show up

![Screenshot_2021-05-11 Jellyfin(4)](https://user-images.githubusercontent.com/10009712/117782880-ac763f80-b25f-11eb-9cd6-59be2f8c8da1.png)

6. Go to the '3 dots' and select 'Refresh metadata'

![Screenshot_2021-05-11 Jellyfin(5)](https://user-images.githubusercontent.com/10009712/117783025-cd3e9500-b25f-11eb-8d95-e0d14e35a62e.png)

7. Select 'Scan for new and updated files'

![Screenshot_2021-05-11 Jellyfin(6)](https://user-images.githubusercontent.com/10009712/117783135-e3e4ec00-b25f-11eb-8b3e-5fd0d6c185cb.png)

8. Subtitles finally show up

![Screenshot_2021-05-11 Jellyfin(7)](https://user-images.githubusercontent.com/10009712/117783187-f101db00-b25f-11eb-9741-b0017d9bee55.png)

**Comment by DanielVukelich** [comment]
I can confirm the same issue running 10.7.6 in a docker container.

**Comment by bigworm** [comment]
Same here...now 10.7.7 in docker.

**Comment by khannurien** [comment]
I can confirm too with 10.7.7 in Docker.

**Comment by minnyres** [comment]
Same problem with systemd in OpenSUSE.
