### ISSUE TITLE
Jellyfin uses 100% of CPU

### ISSUE THREAD

**Issue by Floflobel** [jellyfin/jellyfin#603]
**Describe the bug**
I installed the latest version of Jellyfin available on the debian repo. Then I played a movie for a few minutes and left jellyfin shot all night. The result is that I have 100% CPU usage.

**Logs**
I can send to PM 

**Screenshots**
![screenshot from 2019-01-17 11-57-34](https://user-images.githubusercontent.com/13889750/51313980-2a8af880-1a4f-11e9-90ce-1b61403c2004.png)

After a reboot:
![screenshot from 2019-01-17 11-57-54](https://user-images.githubusercontent.com/13889750/51313990-2f4fac80-1a4f-11e9-8c95-584e48c5d342.png)

And I display a memory leak:
![screenshot from 2019-01-17 12-02-37](https://user-images.githubusercontent.com/13889750/51314389-df251a00-1a4f-11e9-841e-3209a7047f84.png)

**System (please complete the following information):**
 - OS: Debian stretch
 - Jellyfin Version: 10.0.2-1

**Comment by Redsandro** [comment]
Not sure if related/relevant, but I occasionally observe the same with .NET `mono` apps like Jackett.

https://github.com/Jackett/Jackett/issues/2198

**Comment by joshuaboniface** [comment]
Exactly what process(es) are using the CPU time? Is it the main `jellyfin` process, or is there perhaps an `ffmpeg` stuck running? And if it's the main process, can you pastebin the logs?

**Comment by Floflobel** [comment]
I will try to reproduce and I send the informations.

**Comment by Floflobel** [comment]
I can not reproduce the bug for the moment.
