### ISSUE TITLE
Jellyfin ignores settings of "Internet streaming bitrate limit" and "Force transcoding of remote media sources such as Live TV"

### ISSUE THREAD

**Issue by erkexzcx** [jellyfin/jellyfin#6032]
**Describe the bug**

**System (please complete the following information):**
 - OS: Fedora 34
 - Virtualization: None, installed RPM packages directly
 - Clients: Browsers, Android smartphone, Android TV (stable apps)
 - Browser: latest Brave browser, latest Chrome browser, 
 - Jellyfin Version: 10.7.5 (I did not test with previous versions)
 - Playback: Jellyfin always provides direct stream and never transcodes, unless I set quality lower than the media, then it does.
 - Installed Plugins: None
 - Reverse Proxy: None
 - Base URL: None
 - Networking: Host
 - Storage: N/A

**To Reproduce**
.1. In dashboard --> users --> _any user_ --> "Force transcoding of remote media sources such as Live TV" enable this option
.2. Attempt to watch any IPTV stream - not transcoded.

.1. In dashboard --> users --> _any user_ --> "Internet streaming bitrate limit (Mbps)" set to e.g. 5mbps
.2. Attempt to watch any IPTV stream - not transcoded (direct play - incoming stream of 20.1mbps)

.1. In dashboard --> playback --> streaming --> "Internet streaming bitrate limit (Mbps)" set to e.g. 5mbps
.2. Attempt to watch any IPTV stream - not transcoded (direct play - incoming stream of 20.1mbps)

**Expected behavior**
IPTV streams force transcoded by Jellyfin, so it no longer lags for me (transcoding fixes the lag).

**Comment by naimo** [comment]
Thanks for this amazing software

I don't know about the "Force transcoding of remote media sources such as Live TV" setting, but I also get the "Internet streaming bitrate limit" parameter ignored

I set it to 5 (Mbps), and can see in the logs that it was taken into account

```
[16:47:08] [INF] [4] Jellyfin.Api.Helpers.MediaInfoHelper: Bitrate exceeds DirectStream limit: media bitrate: 48969776, max bitrate: 5000000

[16:47:08] [INF] [4] Jellyfin.Api.Helpers.MediaInfoHelper: Profile: Jellyfin Android, Path: movie.mkv, isEligibleForDirectPlay: False, isEligibleForDirectStream: False
```

But no transcoding happens, the dashboard says "The source file is entirely compatible with this client, and the session is receiving the file without modifications." and it seems to indeed be trying to stream it in original size/format.

My setup :
Version 0.7.7 on Linux X64, running in docker behind an nginx reverse proxy

**Comment by ThijmenGThN** [comment]
I'm able to vouch for this issue as well, setting max mb/s per user is being ignored.

_Would love to see a fix :)_

**Comment by wittekind** [comment]
Can confirm, as well.

**Comment by twicehopped** [comment]
I am also seeing this setting ignored.

Server:

Version: 10.7.7
Operating System: Windows
Architecture: X64

Client:

Roku Ultra (Roku Ultra)
Jellyfin Roku 1.4.12


Possibly same issue as: https://github.com/jellyfin/jellyfin/issues/6458 ?

**Comment by icedterminal** [comment]
It is a known issue with the *Integrated* player type. Change your Client settings to use *Web*. See #564
