### ISSUE TITLE
Direct stream not possible since 10.7.3

### ISSUE THREAD

**Issue by DEADC1DE** [jellyfin/jellyfin#6034]
**Media Info of the file**
Allgemein 
Format : Matroska 
Format-Version : Version 2 
Dateigröße : 1,31 GiB 
Dauer : 43 min 34s 
Gesamte Bitrate : 4 299 kb/s 
Kodierungs-Datum : UTC 2020-12-23 08:32:49 
Kodierendes Programm : mkvmerge v31.0.0 ('Dolores In A Shoestand') 64-bit 
verwendete Encoder-Bibliothek : libebml v1.3.6 + libmatroska v1.4.9 

Video 
ID : 1 
Format : AVC 
Format/Info : Advanced Video Codec 
Format-Profil : High@L4.1 
Format-Einstellungen : CABAC / 5 Ref Frames 
Format-Einstellungen für CABAC : Ja 
Format-Einstellungen für RefFrames : 5 frames 
Codec-ID : V_MPEG4/ISO/AVC 
Dauer : 43 min 34s 
Bitrate : 3 913 kb/s 
Breite : 1 280 Pixel 
Höhe : 720 Pixel 
Bildseitenverhältnis : 16:9 
Modus der Bildwiederholungsrate : konstant 
Bildwiederholungsrate : 25,000 FPS 
Color space : YUV 
Chroma subsampling : 4:2:0 
Bit depth : 8 bits 
Scantyp : progressiv 
Bits/(Pixel*Frame) : 0.170 
Stream-Größe : 1,19 GiB (91%) 
verwendete Encoder-Bibliothek : x264 core 161 r3015 4c2aafd 
Kodierungseinstellungen : cabac=1 / ref=5 / deblock=1:-3:-3 / analyse=0x3:0x113 / me=umh / subme=7 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=0 / chroma_qp_offset=-2 / threads=24 / lookahead_threads=4 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=25 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=crf / mbtree=1 / crf=19.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / ip_ratio=1.40 / aq=1:1.00 
Default : Ja 
Forced : Nein 

Audio #1 
ID : 2 
Format : AC-3 
Format/Info : Audio Coding 3 
Commercial name : Dolby Digital 
Codec-ID : A_AC3 
Dauer : 43 min 34s 
Bitraten-Modus : konstant 
Bitrate : 192 kb/s 
Kanäle : 2 Kanäle 
Channel layout : L R 
Samplingrate : 48,0 kHz 
Bildwiederholungsrate : 31,250 FPS (1536 SPF) 
Compression mode : Lossy 
Stream-Größe : 59,9 MiB (4%) 
Sprache : Deutsch 
Service kind : Complete Main 
Default : Ja 
Forced : Nein 

Audio #2 
ID : 3 
Format : AC-3 
Format/Info : Audio Coding 3 
Commercial name : Dolby Digital 
Codec-ID : A_AC3 
Dauer : 43 min 34s 
Bitraten-Modus : konstant 
Bitrate : 192 kb/s 
Kanäle : 2 Kanäle 
Channel layout : L R 
Samplingrate : 48,0 kHz 
Bildwiederholungsrate : 31,250 FPS (1536 SPF) 
Compression mode : Lossy 
Stream-Größe : 59,9 MiB (4%) 
Sprache : Englisch 
Service kind : Complete Main 
Default : Nein 
Forced : Nein 

**Logs**
[2021-05-12 14:27:15.687 +02:00] [INF] User policy for "user". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: False EnableAudioPlaybackTranscoding: True
[2021-05-12 14:27:15.687 +02:00] [INF] Profile: "Unknown Profile", Path: "/mnt/decrypt/01_TV_HD/Deadliest.Catch/Season.16/Deadliest.Catch.S16E06.The.Bleeding.Edge.HDTV-720p.mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2021-05-12 14:27:15.687 +02:00] [INF] Container: "mkv,webm", Video: "h264", Audio: "ac3" cannot be direct played by profile: "unknown profile" for path: "/mnt/decrypt/01_TV_HD/Deadliest.Catch/Season.16/Deadliest.Catch.S16E06.The.Bleeding.Edge.HDTV-720p.mkv"
[2021-05-12 14:27:15.687 +02:00] [INF] Profile: "Unknown Profile", Path: "/mnt/decrypt/01_TV_HD/Deadliest.Catch/Season.16/Deadliest.Catch.S16E06.The.Bleeding.Edge.HDTV-720p.mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2021-05-12 14:27:15.687 +02:00] [INF] Container: "mkv,webm", Video: "h264", Audio: "ac3" cannot be direct played by profile: "unknown profile" for path: "/mnt/decrypt/01_TV_HD/Deadliest.Catch/Season.16/Deadliest.Catch.S16E06.The.Bleeding.Edge.HDTV-720p.mkv"

**Server System (please complete the following information):**
 - OS: Debian Buster
 - Jellyfin Version: 10.7.3
 - Hardware settings & device: No Hardware transcoding
 - Reverse proxy: no
 - Other hardware notes: Google Drive
 
**Client System (please complete the following information):**
 - OS: Windows,
 - Browser (if Web client): Firefox, Chrome

![2021-05-12 15_00_08-Dreamboxx - Vivaldi](https://user-images.githubusercontent.com/74871883/117980198-00525880-b334-11eb-99af-3d07ba7d0e9d.png)

Since version 10.7.3 it is not possible to play files on clients who need audio transcoding. Last working version is 10.7.2.

Audio encoding is enabled, but Jelly didnt transocde audio only since 10.7.3.

**Comment by sum01** [comment]
Upgrade to v10.7.5. v10.7.3 and v10.7.4 had issues (that were quickly fixed).

**Comment by DEADC1DE** [comment]
I have testet now with a fresh install of 10.7.5 with exactly same issue.
https://pastebin.com/yVs9gKK7

**Comment by sum01** [comment]
https://github.com/jellyfin/jellyfin/issues/5978 seems similar

**Comment by crobibero** [comment]
This has already been fixed by https://github.com/jellyfin/jellyfin/pull/6022, no need to keep investigating.

**Comment by da-anda** [comment]
same issue for me on 10.7.5. Direct playback via remuxing does only work when video transcoding is also enabled. As soon as video transcoding is disabled in the user settings, remuxing fails

**Comment by konradbjk** [comment]
I am running 10.7.5 in a docker. Mine Jellyfin tries to transcode everything. If I disabled video transcoding, the player does not work.

I do have selected: Allow video playback that requires conversion without re-encoding
I already made modifications to my nginx proxy as per: https://jellyfin.org/docs/general/networking/nginx.html

Now when I go with an Android device and select External Player to VLC (as explained in https://forum.jellyfin.org/t/direct-streaming-playing-hevc-is-broken-on-android-android-tv/2855/2) it works on the direct play.
```
Jellyfin.Api.Helpers.MediaInfoHelper: Profile: "Android External Player", Path: "REDACTED", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
```
Now for the browser, I see:
```
Jellyfin.Api.Helpers.MediaInfoHelper: Profile: "Unknown Profile", Path: "REDACTED", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
```
Although, it sees the device correctly as:
```
Firefox
Jellyfin Web 10.7.5
Konrad, 8 minutes ago 
```
And then obviously
![Screenshot 2021-05-17 at 15 16 30](https://user-images.githubusercontent.com/31480935/118498727-a03e2680-b726-11eb-9260-d493b4115b1a.png)

Movies are in x265.

**Comment by Drakod** [comment]
Direct stream does not work on android tv "nvidia shield" and browser

works well on android "telephone" application

**Comment by konradbjk** [comment]
@Drakod it worked for my mobile once I changed the player to external.

Is there any reason why it does not work for the browser?

About the  Android TV - MiBox, I can direct stream using VLC as a player, not always works for libVLC.

**Comment by jpmvferreira** [comment]
I've just installed `jellyfin-media-player` and trying to play something, I've disabled transcoding for this specific user as I'm running Jellyfin on a RPI, I get an error saying:
```
This client isn't compatible with the media and the server isn't sending a compatible media format.
```

If I try to use `jellyfin-mpv-shim` like I used to, I get:
```
2021-05-22 12:25:27,415 [   DEBUG] event_handler: Handled Event Play: {'ItemIds': ['4357ee23df57a693f95acf690d706294'], 'StartPositionTicks': 3000000000, 'PlayCommand': 'PlayNow', 'ControllingUserId': '6c57ca2e93034eed8c8bbe76b294c4b7', 'ServerId': 'ef9030532a17425396a3a0315e6c2b4f'}
2021-05-22 12:25:27,434 [   DEBUG] urllib3.connectionpool: http://10.1.1.1:8096 "GET /Users/6c57ca2e93034eed8c8bbe76b294c4b7/Items/4357ee23df57a693f95acf690d706294 HTTP/1.1" 200 None
2021-05-22 12:25:27,435 [   DEBUG] event_handler: EventHandler::playMedia <jellyfin_mpv_shim.media.Media object at 0x7f002ae96be0>
2021-05-22 12:25:27,435 [   DEBUG] media: Bandwidth: local=True, bitrate=None, force=False
2021-05-22 12:25:27,452 [   DEBUG] urllib3.connectionpool: http://10.1.1.1:8096 "POST /Items/4357ee23df57a693f95acf690d706294/PlaybackInfo HTTP/1.1" 200 None
2021-05-22 12:25:27,453 [   ERROR] player: PlayerManager::play no URL found
```

Everything is up to date both in the server (Manjaro ARM) and in the client (Manjaro) with the server being installed from the official repositories and the client from the AUR.

**Comment by Bond-009** [comment]
Closing as stale
