### ISSUE TITLE
DLNA PlayTo:  Play photos or albums on TV

### ISSUE THREAD

**Issue by xiaolei0125** [jellyfin/jellyfin#6041]
Can JF(using DLNA PlayTo) play photos or albums on AndroidTV?  
I didn't find any relevant introduction or description.

**Comment by BaronGreenback** [comment]
Just got around to checking - photos doesn't seem to work via PlayTo on my system. Yet...

**Comment by BaronGreenback** [comment]
Have opened this as a bug here. https://github.com/jellyfin/jellyfin/issues/6125

Will close issue - and update that one, if that's ok?
