### ISSUE TITLE
Block items with tags doesn't hide from Latest

### ISSUE THREAD

**Issue by jackgovier** [jellyfin/jellyfin#6046]
**Describe the bug**
Duplicate of [#2079](https://github.com/jellyfin/jellyfin/issues/2079), when you block tags, the users impacted can still see the tagged material in the 'Latest' views.

**System (please complete the following information):**
 - OS: Debian
 - Virtualization: N/A
 - Clients: All
 - Browser:
 - Jellyfin Version: 10.7.5
 - Playback: N/A
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: none
 - Networking: Host
 - Storage: local

**To Reproduce**
1. Go to Edit Item Metadata for a newly added item
2. Add tag 'x' and save
3. Create user, go to Parental Control, under Block Item with Tags add 'x'
4. Go to home page, see item still in 'Latest' despite not appearing when browsed to.

**Expected behavior**
Item shouldn't be visible anywhere to this user

**Comment by ikhurramraza** [comment]
Experiencing the same issue

**Comment by Shadowghost** [comment]
Most likely being fixed by #8526
