### ISSUE TITLE
TV Shows with very large number of seasons fail to scan in

### ISSUE THREAD

**Issue by neopc10** [jellyfin/jellyfin#6055]
**Describe the bug**
For shows with ~90+ seasons, Jellyfin seems to give up at retrieving season data. Episodes are technically scanned in but are inaccessible from the Show details screen because there are no seasons. 
This is not a regression as it's never quite worked, nor has it appear to have been reported as there aren't a whole lot of shows with so many seasons. With the Missing Episode Fetcher for TVDB now working again, this can be easily reproduced with the Masterclass TVDB entry.

Debian, Docker, Server 10.7.5, TVDB plugin 5.0.0

**To Reproduce**
Create a TV show library with the TVDB "missing episode fetcher" enabled. Link the TV show with the TVDB external ID pointing to https://www.thetvdb.com/series/masterclass

**Expected behavior**
After all of the episode entries are generated, seasons should also be populated.

**Logs**
Nothing useful is logged--Episodes get scanned in but it clearly gives up on scanning the seasons in.

**Comment by Bond-009** [comment]
Closing as stale
