### ISSUE TITLE
Jellyfin 10.7.5 causes my router to slow to a crawl

### ISSUE THREAD

**Issue by adgoncal** [jellyfin/jellyfin#6059]
**Describe the bug**

When I start the Jellyfin container, my whole network becomes super slow, and ping shows more than 50% of packets getting dropped. As soon as I pause the Jellyfin container, everything is back to normal.

**System (please complete the following information):**
 - OS: Debian
 - Virtualization: Docker
 - Clients: Browser, Android, Fire Stick, Roku
 - Browser: Chrome 90
 - Jellyfin Version: 10.7.5
 - Playback: Direct Play
 - Installed Plugins: TVHeadend
 - Reverse Proxy: none
 - Base URL: no
 - Networking: host (docker macvlan)
 - Storage: local

**To Reproduce**

1. Start a docker container with image `jellyfin/jellyfin:stable`
2. Router processing power goes to 100% and network is unusable

**Expected behavior**
Network should not become unstable. Version 10.7.2 works fine.

**Logs**

**Additional context**
 I first noticed the network slow down 2 weeks ago, but did not have time to troubleshoot, so I stopped all my docker containers. Today I had some time and pin-pointed it to Jellyfin. I saw on the release notes that versions 10.7.3, 10.7.4, and 10.7.5 were all released on the same day, so I pinned the container to version 10.7.2 and everything works fine. I have not tried the other versions yet. 

I suspect this may be related to the issue on https://github.com/jellyfin/jellyfin/issues/5981 but disabling DLNA and UPnP did not help me.

My router is the Tp-Link Archer A7.

**Comment by BaronGreenback** [comment]
You can check if it's DLNA/UPnP related by running wireshark and filtering by "SSDP".

**Comment by FazeThree71** [comment]
> You can check if it's DLNA/UPnP related by running wireshark and filtering by "SSDP".

I literally ran into this and posted in /r/jellyfin my findings. https://www.reddit.com/r/jellyfin/comments/nnqiae/weird_networking_issue/

**Comment by cvium** [comment]
Fixed in master and 10.7.6 (ETA unknown)
