### ISSUE TITLE
Improve Playlists

### ISSUE THREAD

**Issue by screwfaze** [jellyfin/jellyfin#607]
Emby playlists have always been unimpressive to say the least so anything you can do to improve this would be much appreciated. Rearranging songs on playlists is very slow and songs don't always stay where you put them especially on Android. I have another issue for sharing playlists but thought to mention it here please add option to share with permissions to edit.
So please anything you can do to make playlists fun and easy to create  will be great. I'm sure other have good suggestions on this so feel free to add them.

Thanks

**Comment by Drondemovies** [comment]
Smart playlist like Kodi. Can create playlist by year, genre, tag, studio etc.

**Comment by onny** [comment]
You should really be more precise and ask for one feature request or enhancement in only one issue!

**Comment by JustAMan** [comment]
@screwfaze please make your issue title more precise and don't jam a lot of requests in one.
Would also be great if you can provide some specific improvement suggestions.

@Drondemovies @NotExpectYet your requests are about playlists, but they seem to me to be about "another" playlists (in original issue I see mostly audio playlists). Please open separate feature requests!

**Comment by screwfaze** [comment]
I am waiting for the big stuff to get fixed first then I will give as much info and suggestions as possible but without offline sync working not really using Jellyfin as much yet.
