### ISSUE TITLE
Infuse 7.0.1 Indexing failed for Jellyfin 

### ISSUE THREAD

**Issue by neesonqk** [jellyfin/jellyfin#6073]
**Describe the bug**

I have three medias configuration in Jellyfin - Collection, Movies, TV

When adding Jellyfin to infuse (ios) it prompts "Indexing failed for Jellyfin", however, when disable Movies from library from infuse, it works again, only when 'Movies' is ticked it starts to complain. Which means it doesn't index "Movies".

![IMG_2549](https://user-images.githubusercontent.com/7279067/118629888-9983e200-b800-11eb-95d2-463b9e95db7e.PNG)

No such an issue with all browsers and jellyfin native iOS app.

**System (please complete the following information):**
 - OS: Windows 10 20H2
 - Virtualization: N.A. 
 - Clients: iPhone 12 Pro Max, infuse 7.0.1
 - Browser: N.A.
 - Jellyfin Version: 10.7.5
 - Playback: N.A.
 - Installed Plugins: AudioDB, InfuseSync, MusicBrianz, OMDb, Open Subtitles.
 - Reverse Proxy: None
 - Base URL: Empty
 - Networking: Host
 - Storage: Local

**To Reproduce**

1. Open Infuse
2. Add Jellyfin server (three medias - Collections, Movies, TV and the Movies contains over 300+ files)
3. Infuse will start to fetch and index all content

**Expected behavior**

**Logs**

I found an exception from log when try to index again.

![image](https://user-images.githubusercontent.com/7279067/118631321-f3d17280-b801-11eb-8ee6-58708c3ee223.png)

**Screenshots**
![IMG_2548](https://user-images.githubusercontent.com/7279067/118631366-ff249e00-b801-11eb-86a7-296efc2a666c.PNG)

![IMG_2549](https://user-images.githubusercontent.com/7279067/118631371-00ee6180-b802-11eb-94f4-190ba47534a9.PNG)

**Comment by Bond-009** [comment]
Closing as stale
