### ISSUE TITLE
Failed Media Scan

### ISSUE THREAD

**Issue by brucesnelgrove** [jellyfin/jellyfin#6077]
**Describe the bug**

Music Library media scan fails at 48% 

**System (please complete the following information):**
 - OS: Mac Os 11.3.1

 - Clients: Mac Os, Roku , iOS
 - Browser: Chrome Brave
 - Jellyfin Version: 10.7.5
 - Playback: [Direct Play, Remux, Direct Stream, Transcode] 
 - Installed Plugins: [e.g. none, Fanart, Anime, etc.]
 - Reverse Proxy: audio db, fan art, music brainz, next pvr, omdb
 - Base URL: [e.g. none, yes: /example]
 - Networking: [e.g. Host, Bridge/NAT]
 - Storage: NAS
**To Reproduce**

Media scan of music files from any screen in Jellyfin fails at 48%

[Log-05-18-21.pdf](https://github.com/jellyfin/jellyfin/files/6502038/Log-05-18-21.pdf)

fails at 48%

**Logs**

**Screenshots**

**Additional context**

**Comment by Bond-009** [comment]
Closing as stale
