### ISSUE TITLE
Hide TV shows with no video files in folders

### ISSUE THREAD

**Issue by AKDub** [jellyfin/jellyfin#608]
When a TV show folder has no video files (not necessarily empty as other files could be there), don't show in the library.

I realise I could just delete them, but for various reasons I would prefer not to, so it would be useful if they didn't take up space when showing the library.

**Comment by SenorSmartyPants** [comment]
I'm running into this problem as well. I have some persistent files for certain series for a hardware player. These are not video files, but it makes JF list the series in my library even thou there are no video files associated with it.

**Comment by lennysh** [comment]
What was the point of moving this back in 2019 to the NEW voting platform if if still doesn't get any movement?  Currently has 167 votes, and no updates?

**Comment by jflix89** [comment]
Not having an option to hide shows/seasons that have an empty breaks other services such as Sonarr, this isn't an issue on Plex.
