### ISSUE TITLE
UserRootFolder.IsRoot is never set to true.

### ISSUE THREAD

**Issue by BaronGreenback** [jellyfin/jellyfin#6088]
UserRootFolder inherits from Folder.

Folder has a property called IsRoot. My assumption is that this should be true if the instance is UserRootFolder. (ie. a root folder)

UserRootFolder never sets this to true outside of the resolver, causing DLNA to return the wrong parent information.

From looking at the code, I suspect this is occuring in other places too.

**Comment by Bond-009** [comment]
Fixed
