### ISSUE TITLE
Pushover 4.0.0.0 Plugin not compatible

### ISSUE THREAD

**Issue by marc0janssen** [jellyfin/jellyfin#6091]
Hi There,

Any chance of getting the Pushover working again with Jellyfin 10.7.5

PLugin version Pushover == 4.0.0.0

**System (please complete the following information):**
 - OS: docker
 - Clients: macOS
 - Browser: safari 14
 - Jellyfin Version:10.7.5

**Comment by Bond-009** [comment]
Looks like it's archived https://github.com/crobibero/jellyfin-plugin-pushover
