### ISSUE TITLE
LDAP Authentication Plugin Status Malfunctioned

### ISSUE THREAD

**Issue by MetaBliss** [jellyfin/jellyfin#6097]
**Describe the bug**
 I have jellyfin installed as host on my Synology NAS with two user accounts. I recently installed Authelia, which is an authentication application that hardens the security of anything behind it. I wanted to use authelia and my LDAP server to authenticate users and then have them automatically routed to Jellyfin. 

I read that Jellyfin has an LDAP Authentication plugin. I went to the "plugin" section in the Admin Dashboard and from the catalog, I saw the LDAP Authentication plugin. I then proceeded to install the plugin. Then, I was told I need to restart Jellyfin. I did not see a "restart" button in the Jellyfin GUI (only a shutdown button) so I assume this means restarting the Jellyfin container within my Synology NAS Docker App. 

**Once Jellyfin was restarted this way, when I went back to the "plugin" section of my Jellyfin Admin account, and for the LDAP Authentication plugin it says the status is "malfunctioned".** (see picture below).  I have tried to uninstall and then install this LDAP plugin numerous times and each time after a docker container restart the status just says malfunctioned. There is no errors in the logs so I am unsure what the problem is. Can you please help? If there is another way to restart jellyfin besides restarting the docker container please advise. 

**System (please complete the following information):**
 - OS: Linux X64 Architecture on Synology NAS DS920+
 - Virtualization: Jellyfin Docker Container
 - Clients: Windows 10 Firefox Browser
 - Browser: FireFox Browser 88.0.1 (64-bit)
 - Jellyfin Version: 10.7.1
 - Installed Plugins: AudioDB, MusicBrainz, OMDb
 - Reverse Proxy: nginx proxy manager
 - Base URL: - Jellyfin is on a wildcard domain certificate using the following format jellyfin.domainname.com
 - Networking: Docker Host
 - Storage: Local storage on NAS

**Screenshots**
 Please see screenshot below with red circle on the problem plugin. I am not super technically savvy so I prefer making changes in the GUI but if thats not possible, some detailed instructions on fixing this the manual way would be helpful. 

![image](https://user-images.githubusercontent.com/84720384/119353352-c573ed00-bc70-11eb-985f-015647342f75.png)

**Comment by crobibero** [comment]
Even though you don't see any errors in the logs, please provide them anyway.
I'm 99% sure it's because you're running Jellyfin 10.7.1, and the plugin was built with a reference to a newer version of Jellyfin.

**Comment by coolmule0** [comment]
I solved this by installing the previous version (10.0.0.0)
