### ISSUE TITLE
Understanding the effect of EnableRemoteAccess with reverse-proxying

### ISSUE THREAD

**Issue by Zopieux** [jellyfin/jellyfin#6099]
**Describe the bug**
Setting up (nginx) reverse-proxy in front of Jellyfin used to work fine in 10.5.5 with `EnableRemoteAccess=false`, but it's no longer the case in 10.7.5. **I don't know if it's a bug or a feature, please help me clarify.**

**System (please complete the following information):**
- OS: some Linux
 - Jellyfin Version: 10.7.5
 - Reverse Proxy: nginx

**To Reproduce**
1. Make sure `EnableRemoteAccess` is false, add `127.0.0.1` and `::1` to `KnownProxies`, and in case that's relevant `192.168.0.0/16` to LAN networks, which is what I use at home
2. Setup nginx reverse-proxying
3. Attempt to go to [public nginx address that reverse-proxies Jellyfin]

**Expected behavior**
Using 10.5.5, this used to work fine. I could log in and access my Jellyfin instance.
Starting with 10.7.5 (did not test any intermediate version), with unchanged configuration, I am now presented with:
  * the "Select server" page through nginx
  * but the usual login page through direct access, bypassing nginx

If that's of any use, the reverse-proxified connection returns 200 OK but 0-byte responses for paths like `/system/info/public` so this suggests some middleware is early-answering empty responses for "protected" endpoints, even though they're originating from nginx, so localhost (which, again, is listed as `KnownProxies`).

If I set `EnableRemoteAccess` to `true`, everything works on 10.7.5, but it should not be necessary since Jellyfin is, technically, not directly accessible from the internet, and I very much don't want this to be the case. Why is `EnableRemoteAccess` necessary even though requests are coming from nginx, on the same machine, not the WAN? 

So, more than a bug, maybe this ticket is a question: how can I make sure to have Jellyfin *not* bind/listen/serve on anything other than my LAN, and still allow nginx-proxified requests to go through, without enabling `EnableRemoteAccess`? Did the semantics of `EnableRemoteAccess` change in 10.7.5? Thanks for your help.

**Server Logs**
No relevant server logs.

**Comment by cvium** [comment]
Since 10.7.0 reverse proxy handling in Jellyfin is more correct than previously. If you add your proxy IP to `KnownProxies` and configure your proxy to forward the actual client IP via the X-Forwarded-For header, Jellyfin will use the client IP wrt. `EnableRemoteAccess` etc. `EnableRemoteAccess` does not have any impact on which IP it will listen on, that is set with `LocalNetworkAddresses`.

**Comment by Zopieux** [comment]
Thanks for your prompt reply. Clarifying this in the docs might be a nice thing to have! Cheers.

**Comment by jameskimmel** [comment]
My feeling is that proxy and remote access should be grouped together in the settings because of this.
