### ISSUE TITLE
Increase fallback font file size limit

### ISSUE THREAD

**Issue by lauw0129** [jellyfin/jellyfin#6101]
Server System:
 - OS: Ubuntu 20.04 LTS
 - Jellyfin Version: 10.7.5
 - Hardware settings & device: Intel(R) Xeon(R) CPU E31245 @ 3.30GHz, 8 cores
 - Reverse proxy: nginx
 
Client System:
 - Device: PC
 - OS: Windows 10
 - Client: Web
 - Browser : Chrome
 - Client and Browser Version: 90.0.4430.212 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/62137079/119447911-2c71ce80-bd63-11eb-823b-cc8be5e068fa.png)

I found the fallback font size limit is 20mb. But I have some font file is greater than 20mb. So is there any way to increase the fallback font file size limit? Thank you

**Comment by Artiume** [comment]
it's set here. Making it configurable is feasible if someone has the time.

https://github.com/jellyfin/jellyfin/blob/94056049131a8573d7a4d0690da04c0e8bc240ad/Jellyfin.Api/Controllers/SubtitleController.cs#L485
