### ISSUE TITLE
live-tv artwork requires xmltv reload to update

### ISSUE THREAD

**Issue by krutburken** [jellyfin/jellyfin#6108]
**Describe the bug**
Artwork/images in livetv don't update when a new item starts playing, and requires a manual refresh of the xmltv-file (xml file has not changed).

**System (please complete the following information):**
 - OS: CentOS
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Firefox, Chrome 
 - Jellyfin Version: 10.7.5
 - Reverse Proxy: nginx
 - Networking: bridge
 - Storage: nfs

**To Reproduce**
1. Add live-tv channel (m3u,xmltv), see artwork
2. Wait for item to finish
3. Artwork for the new item will not be displayed
4. Manually reload xmltv guide and artwork will display again

**Expected behavior**
Artwork should automatically be updated when the item changes

**Server Logs**
No error is logged.

**Screenshots**
Before reload:
![Screenshot from 2021-05-26 12-02-08](https://user-images.githubusercontent.com/13684929/119643098-a9f91580-be1b-11eb-8348-dbefbc353cfe.png)

After reload:
![Screenshot from 2021-05-26 12-02-32](https://user-images.githubusercontent.com/13684929/119643109-ac5b6f80-be1b-11eb-9ac9-73fd94d4f70f.png)

**Comment by srcrist** [comment]
I am unable to reproduce this issue in 10.8.11. Are you able to confirm that this issue still exists for you in the latest release?

**Comment by thornygravy** [comment]
same thing happens to me still on 10.8.11 as well

**Comment by krutburken** [comment]
Still a thing.
