### ISSUE TITLE
Intel Quick Sync support/No HW Acceleration

### ISSUE THREAD

**Issue by Essasetic** [jellyfin/jellyfin#611]
<del>**FFmpeg (at the moment) is very confusing to setup on locked down NAS Operating System's like DSM.**
FFmpeg isn't offically supported on operating system's like DSM (Synology's OS). Because of this I am unable to do hardware transcoding thus making Jellyfin pratically unusable for my 218+.

<del>**Package FFmpeg support in the Docker package or make it easy to install.**
I would like FFmpeg to be packaged into the actual Docker builds. As this way it eases a lot of pain of trying to get FFmpeg to work (or sometimes it is impossible for the regular user to get it working).<del>

<del>I hope this won't be a problem in the future (especially because clients like Emby & Plex support hardware transcoding without any extra setup needed on NAS servers). This should help (at least for Synology NAS server's) on compiling and attempting to get FFmpeg merged: https://github.com/SynoCommunity/spksrc<del>

UPDATE: FFmpeg support is there (4.0.6 to be exact) however there is no Intel Quick Sync support. (Thus no HW acceleration). Reverting to an older version of FFmpeg with HW Acceleration support could fix this.

**Comment by Pilo11** [comment]
BobOkisama said in Issue #555 [https://github.com/jellyfin/jellyfin/issues/555#issuecomment-453742508](here): 

> I contacted van and he said it is not possible to bake in nvenc/nvdec and vaapi into a static build, so we certainly have to build our own

So we need a ffmpeg version in the docker container which is not a static build.

I chose "jrottenberg/ffmpeg:4.0-vaapi" as ffmpeg version for my docker container to use hardware accelerated VAAPI transcoding.

[https://github.com/jellyfin/jellyfin/issues/555#issuecomment-453738909](Dockerfile example)

**Comment by Essasetic** [comment]
@Pilo11 So that essentially means we'll have to get our own build for hardware transcoding? I hope 4.1 fixes it or it starts to handle it like Plex/Emby does.

**Comment by chilman408** [comment]
Hello,

I know this says enhancement only.  

But it should be a bug because under Transcoding section, the Intel Quick Sync option is there and as far as I can test, encoding is HW accelerated but none of the decoding is.  The decoding menu should be disabled until this is fixed.

Also, can someone point me to an ffmpeg build that works with intel quick sync for both encode and decode?

**Comment by EraYaN** [comment]
Quick Sync is Windows only, I believe.

On linux you need to pick VAAPI and on macOS videotoolbox.
