### ISSUE TITLE
Jellyfin not honoring custom device profiles

### ISSUE THREAD

**Issue by supersebbo** [jellyfin/jellyfin#6118]
**Describe the bug**
Jellyfin is not honoring custom device profiles.  

I have an Jellyfin Media Player client that I want to force the remuxing of MKV files to, so I create a custom profile that excludes the MKV container for Jellyfin Media Player clients, thereby forcing JF to remux MKV containers.  However this does not work, JF still allows the client to DirectPlay MKV containers. 

The client reports itself as 'Jellyfin Media Player' this is confirmed in the logs: 
![image](https://user-images.githubusercontent.com/29370445/119818408-0d9c4500-bee7-11eb-876e-a0cfa0e6a252.png)

I then create a custom Profile under DNLA->Profiles with the name 'Jellyfin Media Player':
![image](https://user-images.githubusercontent.com/29370445/119818498-315f8b00-bee7-11eb-9436-6a6ddd623d3b.png)

I create a DirectPlay profile for this device profile that specifically excludes the MKV containers (indicating the device does not support the MKV container and JF would need to Remux/transcode the content. 
![image](https://user-images.githubusercontent.com/29370445/119818659-5fdd6600-bee7-11eb-9aa9-c8faccc77ee1.png)

I find a file to test it with and confirm the file is MKV container:
![image](https://user-images.githubusercontent.com/29370445/119818722-74216300-bee7-11eb-83a0-ce6249cc7de5.png)

I play the test file from the Jellyfin Media Player client, the media should be remuxed or transcoded due to the profile, but it is not, the client is told to DirectPlay the media:
![image](https://user-images.githubusercontent.com/29370445/119818826-974c1280-bee7-11eb-95c6-eb2fd7d46506.png)

Checking the logs, I can see the DirectPlay profile information is not correctly being matched with the custom profile created and appears to be using a default profile. 
![image](https://user-images.githubusercontent.com/29370445/119819009-ce222880-bee7-11eb-8a10-fd9340e88755.png)

**System (please complete the following information):**
 - OS: Debian
 - Virtualization: KVM
 - Clients: Jellyfin Media Player
 - Jellyfin Version: 10.7.5

**To Reproduce**

1. Create a custom profile for a device based on the device's 'Name' (there are no further match criteria possible as Jellyfin Media Player reports 'null' for all other match criteria)
2. Create an explicit directplay profile for the device profile that excludes a specific container type
3. Play a test file matching the excluded container type
4. Jellyfin client will DirectPlay the media despite the profile indicating the container in invalid. 

**Expected behavior**
Jellyfin Server should remux or transcode the media as the profile indicated the container is not supported.

**Comment by BaronGreenback** [comment]
Any chance you could upload the custom profile? It should be in the config/dlna/user folder with a .xml extension.

**Comment by supersebbo** [comment]
`root@jellyfin:/etc/jellyfin/dlna/user# cat Jellyfin\ Media\ Player.xml
<?xml version="1.0" encoding="utf-8"?>
<Profile xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Name>Jellyfin Media Player</Name>
  <Identification>
    <FriendlyName />
    <ModelNumber />
    <SerialNumber />
    <ModelName />
    <ModelDescription />
    <ModelUrl />
    <Manufacturer />
    <ManufacturerUrl />
    <Headers />
  </Identification>
  <FriendlyName />
  <Manufacturer>Jellyfin</Manufacturer>
  <ManufacturerUrl>https://github.com/jellyfin/jellyfin</ManufacturerUrl>
  <ModelName>Jellyfin Server</ModelName>
  <ModelNumber>01</ModelNumber>
  <ModelUrl>https://github.com/jellyfin/jellyfin</ModelUrl>
  <SerialNumber />
  <EnableAlbumArtInDidl>false</EnableAlbumArtInDidl>
  <EnableSingleAlbumArtLimit>false</EnableSingleAlbumArtLimit>
  <EnableSingleSubtitleLimit>false</EnableSingleSubtitleLimit>
  <SupportedMediaTypes>Audio,Photo,Video</SupportedMediaTypes>
  <UserId />
  <AlbumArtPn>JPEG_SM</AlbumArtPn>
  <MaxAlbumArtWidth>480</MaxAlbumArtWidth>
  <MaxAlbumArtHeight>480</MaxAlbumArtHeight>
  <MaxIconWidth>48</MaxIconWidth>
  <MaxIconHeight>48</MaxIconHeight>
  <MaxStreamingBitrate>140000000</MaxStreamingBitrate>
  <MaxStaticBitrate>140000000</MaxStaticBitrate>
  <MusicStreamingTranscodingBitrate>192000</MusicStreamingTranscodingBitrate>
  <MaxStaticMusicBitrate xsi:nil="true" />
  <SonyAggregationFlags />
  <ProtocolInfo>http-get:*:video/mpeg:*,http-get:*:video/mp4:*,http-get:*:video/vnd.dlna.mpeg-tts:*,http-get:*:video/avi:*,http-get:*:video/x-matroska:*,http-get:*:video/x-ms-wmv:*,http-get:*:video/wtv:*,http-get:*:audio/mpeg:*,http-get:*:audio/mp3:*,http-get:*:audio/mp4:*,http-get:*:audio/x-ms-wma:*,http-get:*:audio/wav:*,http-get:*:audio/L16:*,http-get:*:image/jpeg:*,http-get:*:image/png:*,http-get:*:image/gif:*,http-get:*:image/tiff:*</ProtocolInfo>
  <TimelineOffsetSeconds>0</TimelineOffsetSeconds>
  <RequiresPlainVideoItems>false</RequiresPlainVideoItems>
  <RequiresPlainFolders>false</RequiresPlainFolders>
  <EnableMSMediaReceiverRegistrar>false</EnableMSMediaReceiverRegistrar>
  <IgnoreTranscodeByteRangeRequests>false</IgnoreTranscodeByteRangeRequests>
  <XmlRootAttributes />
  <DirectPlayProfiles>
    <DirectPlayProfile container="ts,avi,mpeg2ts" audioCodec="aac,ac3,eac3,mp3,dca,dts" videoCodec="hevc,h264" type="Video" />
    <DirectPlayProfile container="" type="Audio" />
  </DirectPlayProfiles>
  <TranscodingProfiles>
    <TranscodingProfile container="mp3" type="Audio" audioCodec="mp3" estimateContentLength="false" enableMpegtsM2TsMode="false" transcodeSeekInfo="Auto" copyTimestamps="false" context="Streaming" enableSubtitlesInManifest="false" minSegments="0" segmentLength="0" breakOnNonKeyFrames="false" />
    <TranscodingProfile container="ts" type="Video" videoCodec="h264" audioCodec="aac" estimateContentLength="false" enableMpegtsM2TsMode="false" transcodeSeekInfo="Auto" copyTimestamps="false" context="Streaming" enableSubtitlesInManifest="false" minSegments="0" segmentLength="0" breakOnNonKeyFrames="false" />
    <TranscodingProfile container="jpeg" type="Photo" estimateContentLength="false" enableMpegtsM2TsMode="false" transcodeSeekInfo="Auto" copyTimestamps="false" context="Streaming" enableSubtitlesInManifest="false" minSegments="0" segmentLength="0" breakOnNonKeyFrames="false" />
  </TranscodingProfiles>
  <ContainerProfiles />
  <CodecProfiles />
  <ResponseProfiles>
    <ResponseProfile container="m4v" type="Video" mimeType="video/mp4">
      <Conditions />
    </ResponseProfile>
  </ResponseProfiles>
  <SubtitleProfiles>
    <SubtitleProfile format="srt" method="External" />
    <SubtitleProfile format="sub" method="External" />
    <SubtitleProfile format="srt" method="Embed" />
    <SubtitleProfile format="ass" method="Embed" />
    <SubtitleProfile format="ssa" method="Embed" />
    <SubtitleProfile format="smi" method="Embed" />
    <SubtitleProfile format="dvdsub" method="Embed" />
    <SubtitleProfile format="pgs" method="Embed" />
    <SubtitleProfile format="pgssub" method="Embed" />
    <SubtitleProfile format="sub" method="Embed" />
    <SubtitleProfile format="subrip" method="Embed" />
    <SubtitleProfile format="vtt" method="Embed" />
  </SubtitleProfiles>`

**Comment by BaronGreenback** [comment]
From a quick look at the server code, it looks like a shallow clone of the dto object is being passed to the API, when a deep clone is required. (This is resulting in only the top level properties of the device profile being transmitted - hence the settings being _null_).

**Comment by BaronGreenback** [comment]
After further inspection - the profile that the player is sending is shown on the screen above is the device profile.

At present, this cannot be overriden.

**Comment by supersebbo** [comment]
So DLNA profiles only work when a client is accessing Jellyfin over DLNA?  I know that sounds like an obvious statement but I was under the impression a lot of Jellyfin was working via some DLNA mechanism in the background, even when the client was accessing from web or native Jellyfin clients. 

Is the overriding of Device profiles on the feature roadmap?  There are differences in performance and codec support across different devices running the same client (e.g. Android on native AndroidTV versus Android on Amazon FireTV). 

Thanks.

**Comment by BaronGreenback** [comment]
I've currently doing a substantial amount of work on the DLNA subsystems (moving them into plugins).

Part of this is around device profiles.

Would you be able to compile code and test a PR?

**Comment by srcrist** [comment]
Closing this issue as it does not reference a Jellyfin server bug. This process remains unsupported for now. If you would like the functionality to be added, submit a request at https://features.jellyfin.org/.
