### ISSUE TITLE
Music Playlists Empty When Library Is Removed/Added

### ISSUE THREAD

**Issue by seniorm0ment** [jellyfin/jellyfin#6130]
All music from playlists tracklists get removed upon removing the music library folder, and then adding a new path elsewhere (say transfer to a new drive).

This is a major issue, and I understand why it happens, however I think it needs to be worked on. Basically I need to go remember all the songs that were in my 50 playlists, and go manually readd them all which is insanely time consuming and frustrating.
Maybe consider hash matching the files or something so it detects file hashes not sure.

**Comment by omniusaspirer** [comment]
The issue is that Jellyfin playlist handling is basically the worst implementation possible as it's path based. I've been burned before as well. In the future your best bet is to find the actual generated XML playlist on disk (which is at least better than the old m3u8 that couldn't even handle special characters in song names....) and Ctrl+F replace all the relevant portion of your path.

**Comment by seniorm0ment** [comment]
This does work as expected, however it is still definitely not ideal and I think this is still a pretty big issue.

**Comment by seniorm0ment** [comment]
Actually I take that back, I thought it did but I guess not. I changed the paths over in the xml while jellyfin was not running and restarted jellyfin, and also tried rescanning the music library and the changed files don't show up in the playlists still.

**Comment by srcrist** [comment]
Are you able to confirm that this issue still exists in 10.8.11, and can you provide simple steps to reproduce the issue so others can test it? I'm not sure that I'm following the problem.

**Comment by danalderman** [comment]
I can confirm that a single playlist that I had created disappeared until I added a second playlist.  There seems to be an issue with starting with no playlists and then adding one, and it behaving strangely until you add a second playlist.
