### ISSUE TITLE
No matter what I try to do, my libraries are empty. However, my videos show up when I search.

### ISSUE THREAD

**Issue by doobersn** [jellyfin/jellyfin#6140]
**Describe the bug**
Nothing shows up in libraries but if I search for what I want to watch it shows up. I can only view content by searching for it.

**System (please complete the following information):**
 - OS: macOS Big Sur
 - Virtualization: [e.g. Docker, KVM, LXC]
 - Clients: Any device
 - Browser: Any browser
 - Jellyfin Version: Newest Version
 - Playback: [Direct Play, Remux, Direct Stream, Transcode] 
 - Installed Plugins: [e.g. none, Fanart, Anime, etc.]
 - Reverse Proxy: [e.g. none, nginx, apache, etc.]
 - Base URL: [e.g. none, yes: /example]
 - Networking: [e.g. Host, Bridge/NAT]
 - Storage: [e.g. local, NFS, cloud]

**To Reproduce**

**Expected behavior**
I expect my videos to be in the folder specified.

**Server Logs**

**FFmpeg Logs**

**Browser Console Logs**

**Screenshots**

**Additional context**

**Comment by timdelange** [comment]
Ive got this to work by moving the media files into grouped subdirs.  Still a bug in my opinion.  
This didnt work:
       /media/shows/myshow-se01e01.mkv
This DID work
      /media/shows/myshow/myshow-se01e01.mkv
