### ISSUE TITLE
Videos cannot be transcoded during web page access on the mobile client.

### ISSUE THREAD

**Issue by LancelotWG** [jellyfin/jellyfin#6147]
**Describe the bug**

**System (please complete the following information):**
 - OS: Debian
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Chrome 80
 - Jellyfin Version: 10.7.5
 - Playback: Transcode 
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: none
 - Networking: NAT
 - Storage: cloud

**To Reproduce**

1. Watch videos on mobile devices,
2. Watch videos on mobile devices.

**Expected behavior**
Normal transcoding playback

**Server Logs**
none

**FFmpeg Logs**
none

**Browser Console Logs**
none

**Screenshots**
none

**Additional context**
none

**Comment by Bond-009** [comment]
Closing as stale
