### ISSUE TITLE
LocalNetworkSubnets is not respected

### ISSUE THREAD

**Issue by mso42** [jellyfin/jellyfin#6152]
I have the following line in `$HOME/.config/jellyfin/network.xml`:

```xml
  <LocalNetworkSubnets>192.168.1.0/24</LocalNetworkSubnets>
```

But when starting, Jellyfin emits the messages:
```
[17:03:08] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : [::1/128,fc00::/7,fe80::/10,127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[17:03:08] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : []
[17:03:08] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: [::1/128,fc00::/7,fe80::/10,127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[17:03:08] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: []
[17:03:08] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind exclusions: []
```

(Note: I enabled IPV6 to confirm that I was editing the correct config file.)

I ran through the VSCode debugger and found that at this line: https://github.com/jellyfin/jellyfin/blob/9154f20b3404fb818b8c2e74af038547d2c16c40/Jellyfin.Networking/Manager/NetworkManager.cs#L619
`configuration.LocalNetworkSubnets` was equal to `{string[0]}`, which seems wrong to me. I tried to debug further but got lost in the indirection of the config management subsystem, not being a C# developer myself.

Happy to follow further debugging instructions.

**System (please complete the following information):**
 - OS: Arch Linux
 - Virtualization: None
 - Clients: None (running with `nowebclient`)
 - Browser: None (running with `nowebclient`)
 - Jellyfin Version: latest master at time of ticket writing (`9154f20b3404fb818b8c2e74af038547d2c16c40`)
 - Playback: N/A
 - Installed Plugins: None
 - Reverse Proxy: None
 - Base URL: default
 - Networking: Host
 - Storage: Local

**To Reproduce**

1. Set LocalNetworkSubnets to some value
2. Start Jellyfin

**Expected behavior**
Jellyfin filters interfaces to listen on by the values in LocalNetworkSubnets

**Server Logs**
No errors. Relevant log lines included above.

**Comment by BaronGreenback** [comment]
Internally LocalNetworkSubnets is defined as string [ ].
As such the xml saves it as
```
<LocalNetworkSubnets>
    <string>192.168.1.0/24</string>
</LocalNetworkSubnets>
```

**Comment by mso42** [comment]
Aha, thank you. I had assumed the comma-separated list was passed straight from the web UI into the XML.
