### ISSUE TITLE
Jellyfin watched indicator shows incorrect status when a movie as "Additional Parts"

### ISSUE THREAD

**Issue by carif** [jellyfin/jellyfin#6154]
**Describe the bug**
When having a movie which is split up into various parts (e.g. disk 1, disk 2) and you finish playing Part 1, Jellyfin doesn't automatically start Part 2. It however shows that you've only watched 50% of the entire movie, but once going back to the main menu this information is lost as well and Jellyfin seems to think the entire movie has been watched while in reality only e.g. disk 1.

**System (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS (Jellyfin Server, LXC), proxmox 6.4-6 (base OS for the server)
 - Virtualization: Docker within LXC
 - Clients: "Jellyfin Media Player" "1.6.0" on Windows 10
 - Jellyfin Version: 10.7.5
 - Playback: Direct Stream
 - Installed Plugins: e.g. none
 - Reverse Proxy: traefik
 - Storage: NAS Server (TrueNAS) with HDD

**To Reproduce**
1. Select a movie with multiple parts. When clicking on the movie it should show the movie information and "Additional Parts".
2. Play the first part to the end.
3. See how Jellyfin does not automatically start the "Addition Parts" , but remembers that you've only finished e.g. 1/2 parts, thus 50%.
4. Go back the dashboard.
5. Navigate back to the movie.
6. See how the movie is now listed as watched despite the "Additional Parts" not  have been watched yet.

**Expected behavior**
The "Additional Parts" should count to indicate whether the movie has been watched or not and additional parts should start automatically, like the next episode from a Show.

**Additional context**
Needs to be a movie which has "Additional Parts" like disk 1, disk 2 etc.

**Comment by srcrist** [comment]
This requires testing on the latest release. I have removed the stale tag for now. Are you able to confirm that this issue still exists in 10.8.11?

**Comment by carif** [comment]
> This requires testing on the latest release. I have removed the stale tag for now. Are you able to confirm that this issue still exists in 10.8.11?

I can confirm it's still an issue in 10.8.12.

**Comment by siwilk** [comment]
Still the issue in Jellyfin version 10.8.13 when naming multiple parts for episodes as suggested from the Jellyfin website. 2nd part doesn't follow up automatically.
