### ISSUE TITLE
Movie/Show with multiple subtitles for the same language but with different purposes not supported

### ISSUE THREAD

**Issue by MinecraftPlaye** [jellyfin/jellyfin#6155]
**Media Info of the file**
https://drive.google.com/file/d/1zeA0Ry6iPcVddDmOK4BlntELEHNOhLr8/view?usp=sharing

**Server System (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS (Jellyfin Server, LXC), proxmox 6.4-6 (base OS for the server)
 - Jellyfin Version: 10.7.5
 - Hardware settings & device: none
 - Reverse proxy: traefik
 - Other hardware notes: Media mounted in CIFS/SMB share
 
**Client System (please complete the following information):**
 - Device: Lenovo Thinkpad T480s
 - OS: Windows 10
 - Client: "Jellyfin Media Player" "1.6.0"
 - Client: 1.6.0

**The issue:**
The movie has multiple subtitle tracks. Some for CC, some for other languages and some for foreign languages spoken within the movie. All of them are seperate subtitle tracks, however, I can only ever choose one. If I choose CC, I don't get the information from foreign languages, if I selected the subtitle for that, I don't get the CC subtitle. My BD does not have this problem.

**Comment by cvium** [comment]
We don't support multiple tracks (known as dual subtitles in VLC). You'll have to merge the subtitles manually.

**Comment by MinecraftPlaye** [comment]
> You'll have to merge the subtitles manually.

Do you know by chance how I can merge them?
