### ISSUE TITLE
Wrong image loads when searching

### ISSUE THREAD

**Issue by ptruman** [jellyfin/jellyfin#6167]
I open Jellyfin on Android (client), PC (webpage) or Android (webpage) and login.
Click search
Enter something like IMG_201807 (to find all images starting with that date)
I click on a specific image in the list shown

Jellyfin displays the first image in the folder of the image, not the clicked image.

If I click on the 3 dots for the desired image to edit metadata, the correct file information is shown

**Describe the bug**

**System (please complete the following information):**
 - Debian
 - Docker
 - Android (Chrome or official client) or PC via Chrome
 - PC : Chrome 91.0.4472.77 / Android (when in Chrome) :  - 91.0.4472.88
 - Jellyfin Version: 10.7.5 
 - Playback: Direct
 - Installed Plugins: AudioDB v 10.7.5.0, Cover Art Archive, 2.0.0.0, MusicBrainz 10.7.5.0, OMDb 10.7.5.0
 - Reverse Proxy: Traefik
 - Base URL: /web/index.html
 - Networking: macvlan (dedicated IP)
 - Storage: local (Docker bind mounted folder to host)

**To Reproduce**
Per description

**Expected behavior**
The image clicked on should be displayed, not the first/earliest file in the folder

**Comment by ptruman** [comment]
Still happening (on any web client, current docker version)

**Comment by nielsvanvelzen** [comment]
Unable to reproduce. Searching for images in a photo library and then clicking on one always shows the correct image for me.

**Comment by ptruman** [comment]
> Unable to reproduce. Searching for images in a photo library and then clicking on one always shows the correct image for me.

Happy to screen share to demo if it helps.
I load Jellyfin, hit the magnifying glass, and enter "IMG_2021" as an example.  I can then click any image, and it will only display the "first" image that resides in the folder the image the thumbnail is based on is in.

From the search results, if I click the three dots, and "Edit metadata", that does show me the link to the correct image, but clicking it just never works :\ (on Android client, Android web or PC web)

**Comment by MadKillerChicken** [comment]
Can confirm this happening on my end too, with the latest version (2.4.2, 10.7.7). Web (desktop and mobile) and Android. It also hasn't anything to do with specifically searching for images. It's enough to open the photo library and select any of the photos. Very rarely it actually displays the selected image, instead displaying the very first of the library.

**Comment by ptruman** [comment]
This seems to be working now.  I'll assess again more thoroughly.
