### ISSUE TITLE
Subtitle encoding not detected properly

### ISSUE THREAD

**Issue by nitanmarcel** [jellyfin/jellyfin#6169]
There's something that drives me crazy for a few hours and I couldn't find a proper solution yet.

I want to watch a movie and jellyfin can't properly detect the encoding of the subtitle. Some of the characters in that subtitle (Romanian) got displayed with some exclamation mark boxes, searching a little online I've found that changing the subtitle file to utf-8 will fix the issue but now I have another one. Characters like "ă" "â" "î" "ș" "ț" are replaces with random characters, and I haven't managed to find a way to change their encoding to be displayed correctly

 Is there a way to change subtitles encoding? 

![image](https://user-images.githubusercontent.com/41646249/121508521-5d523480-c9ee-11eb-816b-620ad986ed91.png)

**Comment by crobibero** [comment]
Please fill out the issue template, it’s there for a reason.
