### ISSUE TITLE
Filter videos by audio stream language

### ISSUE THREAD

**Issue by taconaut** [jellyfin/jellyfin#617]
**Describe the feature you'd like**
Add the ability to filter by available audio stream language for videos

**Additional context**
I'd like to be able to filter video streams (movies, series) by available audio language

I will work on this to get a hands on with the Jellyfin code. I'm checking the filtering by Genre implementation, which has to be very similar.

TODO:
- [x] Support Backend filtering:
  - [x] Add string property BaseItemsRequest.AudioLanguages
  - [x] Implement SQLite filtering based on BaseItemsRequest.AudioLanguages
  - [x] Expose available AudioLanguages in API (all languages available for any video file)
- [ ] Support Frontend filter selection
  - [x] Get the available AudioLanguages
  - [x] Display available AudioLanguages in filter pane
       - [ ] Map language code to (localized?) language name (e.g. eng -> English; fre -> French)
  - [x] Pass the AudioLanguages select in filter to API for filtering

**Comment by taconaut** [comment]
Currently implementing on branch https://github.com/taconaut/jellyfin/tree/feature/FilterVideosByAudioStreamLanguage

**Comment by dkanada** [comment]
See [here] for an API call to get localization labels for languages.

**Comment by taconaut** [comment]
Thanks @daknin, I've got most of the implementation, but as js in not my speciality, I've still got some issues. I should have it ready by the weekend.
As I couldn't find any json containing key=code, value=language, I've written a little scraper outputting the wanted json here https://github.com/taconaut/ISO639ToJson. See bottom of README for the two possible outputs; I intend to use the native one.

**Comment by JustAMan** [comment]
I think it should be enough for now to stuff in frontend, but I might be wrong here.

**Comment by taconaut** [comment]
Both can be right.
My reasoning to put it in the frontend was that the backend only needs the codes to do what it has to do and the language names are only there for the end user.
A counter argument would be that there are many clients (web, smart TVs, mobile apps...) which will all have to have to have their own implementation and might not be coherent. This can be a benefit as well, if one wants to fully localize the names for each language, the other wants to show native names and the third one English.

If adding it to the backend I wouldn't have exposed resources, but included the language names directly as key/values in the get filters query.
