### ISSUE TITLE
Syncplay library permissions issue

### ISSUE THREAD

**Issue by xddman** [jellyfin/jellyfin#6170]
So ive been having a syncplay issue for a while. Always on latest stable version, currently 10.7.5.

Basically if you have two libraries that contain folders like

Library 1: /home/folder1/
Library 2: /home/folder1/folder2/

If user 1 and user 2 have access to Library 2 but not Library 1, syncplay won't work, if you open library 2 and create a syncplay group, you wont be able to play anything. Clicking play just doesnt work. Leaving the group allows you to play everything from Library 2. Same with user 1 joining user 2's group. If you play a video from library 2 and create a syncplay group, user 2 wont even see the group. My assumption is that permissions are overlapping.

If user 1 only has access to Library 2 but user 2 has access to both Library 1 and Library 2, when user 1 plays a video and makes a syncplay group, user 2 will be able to join and watch synced.
But if user 2 plays a video from Library 2 and makes a group, user 1 wont see the group at all.

Edit:
Just to add a bit more.
If i make a third library that doesnt share a folder with any other library, users can syncplay normally like intended, no issues, the issue occurs only if two libraries contain same folders/files

**Comment by crobibero** [comment]
I believe that library structure isn't supported and causes issues in more areas then syncplay, but I could be wrong.
