### ISSUE TITLE
EncoderController shows up in OpenAPI spec

### ISSUE THREAD

**Issue by nielsvanvelzen** [jellyfin/jellyfin#6179]
**Describe the bug**

The [EncoderController](https://github.com/jellyfin/jellyfin/blob/master/tests/Jellyfin.Server.Integration.Tests/Controllers/EncoderController.cs) introduced in #5990 shows up in the OpenAPI spec. Which it should not.

**To Reproduce**
1. Generate Kotlin SDK using unstable OpenAPI spec
2. EncoderApi.kt is generated

**Expected behavior**
EncoderController should not show up in OpenAPI spec

**Additional context**

See https://github.com/jellyfin/jellyfin-sdk-kotlin/blob/3dc145d4f45986f7e81c4c3676d69f7e858692f6/jellyfin-api/src/main/kotlin-generated/org/jellyfin/sdk/api/operations/EncoderApi.kt#L16-L37

**Comment by crobibero** [comment]
Looking at the commit message, the bot is doing “ Update OpenAPI to unstable”, which is correct to me as the endpoint doesn’t exist in the latest stable spec

**Comment by nielsvanvelzen** [comment]
Correct, the bot is updating the unstable branch (10.8) but the controller it's adding is in a test project and not in the actual release builds.

**Comment by crobibero** [comment]
Ah I missed that part- that’s likely because we’re using a test to get the generated spec… I’ll look into getting the file another way
