### ISSUE TITLE
`.mod` and `.xm` audio files don't get transcoded

### ISSUE THREAD

**Issue by NebelNidas** [jellyfin/jellyfin#6181]
I have plenty of [`.mod`](https://en.wikipedia.org/wiki/MOD_(file_format)) and [`.xm`](https://en.wikipedia.org/wiki/XM_(file_format)) chiptunes from the [Mod Archive](https://modarchive.org/) and similar sites, and want to listen to them through my Jellyfin music library. Unfortunately, Jellyfin fails to transcode these file types into something the client can play. Would it be feasible to implement support for this?

**Comment by Bond-009** [comment]
Same issue as #9034, should we just not scan these files if we don't support playback?

**Comment by NebelNidas** [comment]
Hmm, apparently you need to use the `libopenmpt` library for it to work: https://superuser.com/a/1112757

**Comment by nyanmisaka** [comment]
Will be fixed in `jellyfin-ffmpeg5` 5.1.3-1 release.

**Comment by NebelNidas** [comment]
Nice, thank you very much 😄

**Comment by srcrist** [comment]
Issue closed by https://github.com/jellyfin/jellyfin-ffmpeg/pull/233
