### ISSUE TITLE
Favourited Studios are not shown under favourites

### ISSUE THREAD

**Issue by Drapersniper** [jellyfin/jellyfin#6198]
**Describe the bug**

**System (please complete the following information):**
 - OS: Windows
 - Virtualization:  N/A
 - Clients: N/A
 - Browser:  N/A
 - Jellyfin Version: 10.7.6
 - Playback: N/A
 - Installed Plugins: N/A
 - Reverse Proxy: N/A
 - Base URL: N/A
 - Networking: N/A
 - Storage: N/A

**To Reproduce**
1. Go to a studio page
2. Favourite this studio
3. Go to your Favourite items
4. Observe Studio is not shown under favourites.

**Expected behavior**
Studio to be shown under favourites.

**Server Logs**
N/A (There is no errors)

**FFmpeg Logs**
N/A
**Browser Console Logs**
N/A (There is no errors)

**Comment by HybridSarcasm** [comment]
This has been open quite a while. Can this be re-produced with the current build? If so, please update the bug report details. Thanks!

**Comment by sevenrats** [comment]
@Drapersniper Views are handled entirely by the client so 1) it is a feature request which you should take to features.jellyfin.org and 2) it is in the wrong repo anyway, make sure to reference the client you are requesting the feature for in your request.
Thank you!
