### ISSUE TITLE
Media from multiple libraries are merged in Favourite view

### ISSUE THREAD

**Issue by Drapersniper** [jellyfin/jellyfin#6199]
**Describe the bug**

**System (please complete the following information):**
 - OS: Windows
 - Virtualization:  N/A
 - Clients: N/A
 - Browser:  N/A
 - Jellyfin Version: 10.7.6
 - Playback: N/A
 - Installed Plugins: N/A
 - Reverse Proxy: N/A
 - Base URL: N/A
 - Networking: N/A
 - Storage: N/A

**To Reproduce**
1. Make 2 Libraries of the same type (i.e Anime and TV Shows)
2. Add an series to each library
3. Favourite both series
4. Go to your favourited items.

**Expected behavior**
The items to be split under their own library names i.e a section for all favourited Anime and a section for all Favourited TV Shows.

**Server Logs**
N/A (There is no errors)

**FFmpeg Logs**
N/A
**Browser Console Logs**
N/A (There is no errors)

**Comment by srcrist** [comment]
Closing this issue as it is not an actual bug, but a request for new functionality. Please submit such requests to [features.jeyllfin.org](features.jellyfin.org).
