### ISSUE TITLE
Live TV does not retrieve channels - HDHomeRun CONNECT

### ISSUE THREAD

**Issue by peperunas** [jellyfin/jellyfin#6207]
**Describe the bug**
Jellyfin does not retrieve the channels from the DVR. No channels are viewable as a consequence.

**System (please complete the following information):**
 - OS: Unstable docker image
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Firefox 89
 - Jellyfin Version: 10.8.0
 - Playback: N/A
 - Installed Plugins: OpenSubtitles
 - Reverse Proxy: Traefik
 - Base URL: None
 - Networking: Host
 - Storage: local

**To Reproduce**
1. Register the DVR
2. Wait for the guide to be updated (~5 seconds)

**Expected behavior**
Channels available to watch.

**Server Logs**
https://pastebin.com/rnPZpacr

**Screenshots**
![image](https://user-images.githubusercontent.com/6033387/122682019-0c60ee00-d1ef-11eb-8a2f-453e178e8e23.png)

**Additional context**
The DVR works fine if the channel is accessed directly from its URI.

DVR Model: HDHR4-2DT
DVR Firmware: 20210210

**Comment by srcrist** [comment]
Are you still experiencing this issue on 10.8.11?

**Comment by johangant** [comment]
I'm experiencing this bug using 10.8.12 with a HDHomeRun device on my network. Works great through their app, and streams well in VLC, but playback is very slow in Jellyfin and the EPG isn't downloaded from the HDHomeRun device which does have it populated from a channel scan in the app

**Comment by johangant** [comment]
Removing, re-adding the HDHomeRun tuner into Jellyfin (triggers guide refresh) shows the following logs:

```
[2024-03-21 11:14:10.600 +00:00] [INF] Discovered tuner device "HD Homerun" at "http://192.168.86.38"
[2024-03-21 11:14:10.626 +00:00] [INF] Refreshing guide with 7 days of guide data
[2024-03-21 11:14:16.570 +00:00] [INF] "Refresh Guide" Completed after 0 minute(s) and 8 seconds
[2024-03-21 11:14:16.570 +00:00] [INF] ExecuteQueuedTasks
```

This would appear to be a successful attempt fetch new data but this does not appear in the guide UI:

![image](https://github.com/jellyfin/jellyfin/assets/451261/42e3e4bc-927e-4096-bded-8f3f31cca112)

I can't see any relevant system logs on the HDHomeRun device relating to a guide request, but there are 174 tuned channels it lists which can be browsed/viewed with the native HDHomeRun app. It's unclear why this data isn't making its way into Jellyfin and surfacing to the channel guide in the UI.
