### ISSUE TITLE
Unsupported subtitle format causes Jellyfin to ignore profile settings that disallow video transcoding

### ISSUE THREAD

**Issue by egeym** [jellyfin/jellyfin#6211]
**Describe the bug**

Even when "Allow video playback that requires transcoding" is unchecked in the user that's specified in the DLNA settings, Jellyfin ignores it when unsupported subtitles are embedded in the video container and transcodes to overlay the subtitles on the video.

**System (please complete the following information):**
 - OS: Windows 10 Build 2004
 - Virtualization: None
 - Clients: LG CX OLED webOS 5 DLNA Client
 - Browser: None
 - Jellyfin Version: 10.7.5
 - Playback: Direct Play, Direct Stream, Transcode
 - Installed Plugins: OpenSubtitles
 - Reverse Proxy: None
 - Base URL: None
 - Networking: Local
 - Storage: Local USB

**To Reproduce**

1. Uncheck "Allow video playback that requires transcoding" in user profile that's specified in the DLNA settings
2. Play content with supported video codec with embedded subtitles that are not in the DLNA profile (in this case anything other than SRT) but that has external subtitles
3. Jellyfin ignores the user profile setting that disallows video transcoding and transcodes the video to overlay the embedded subtitle, TranscodeReasons=SubtitleCodecNotSupported
3. The external subtitles are sent to the DLNA client and are rendered by the client media player correctly, however the unsupported subtitle is overlayed on the video (both external and embedded subtitles are played at the same time)

**Expected behavior**
Jellyfin would remain faithful to the user profile settings and not attempt to overlay unsupported subtitles and transcode

**Server Logs**

`[2021-06-21 17:05:24.022 +03:00] [WRN] [19] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://192.168.1.15:8096/videos/f5ee619d-9a8a-b3a8-d6ec-0a45a3279086/stream.ts?DeviceProfileId=6d0b8ff1b607dc993811a829529a5e18&DeviceId=test&MediaSourceId=f5ee619d9a8ab3a8d6ec0a45a3279086&VideoCodec=h264&AudioCodec=ac3,aac,mp3&AudioStreamIndex=1&SubtitleStreamIndex=3&VideoBitrate=139551999&AudioBitrate=448001&MaxWidth=1920&MaxHeight=1080&SubtitleMethod=Encode&RequireAvc=false&Tag=4feef4a5a1f792d1a8b952ced3698441&h264-level=41&ac3-audiochannels=6&aac-audiochannels=6&mp3-audiochannels=6&TranscodeReasons=SubtitleCodecNotSupported&dlnaheaders=true" to "192.168.1.105" in 0:00:01.7336525 with Status Code 200 [2021-06-21 17:05:42.603 +03:00] [INF] [17] Jellyfin.Api.Helpers.TranscodingJobHelper: C:\Program Files\Jellyfin\Server\ffmpeg.exe -f matroska,webm -i file:"G:\fil\The Lives of Others (2006)\The Lives of Others (2006) (1080p BDRip x265 10bit EAC3 5.1 - r0b0t) [TAoE].mkv" -map 0:0 -map 0:1 -codec:v:0 libx264 -force_key_frames "expr:gte(t,n_forced*5)" -filter_complex "[0:3]scale=1920x1080[sub];[0:0]scale=trunc(min(max(iw\,ih*dar)\,min(1920\,1080*dar))/2)*2:trunc(min(max(iw/dar\,ih)\,min(1920/dar\,1080))/2)*2[base];[base][sub]overlay" -pix_fmt yuv420p -preset superfast -crf 23 -maxrate 18134185 -bufsize 36268370 -level 41 -x264opts:0 subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none -vsync -1 -map_metadata -1 -map_chapters -1 -threads 0 -codec:a:0 ac3 -ac 6 -ab 448001 -y "C:\ProgramData\Jellyfin\Server\transcodes\952dda9960361d15d811c7011821f837.ts"`

**Additional context**
I had posted on r/Jellyfin a couple days ago about seemingly unnecessary transcoding to my LG CX over DLNA even after adding HEVC to supported codecs. Even when I turned off video transcoding for the only profile on the system that I made sure also was selected as the default profile for DLNA it transcoded.
With some scrutiny and investigation I found out that even if video transcoding is turned off, if there's ANY subtitle embedded in the MKV that's not srt (the only subtitle on the LG Smart TV profile) it overlays the subtitle on the video. Even if I don't want it and have external subtitles. If I have external subtitles it would send the external subtitle correctly AND overlay the embedded subtitle even if I selected the external subtitle.

I now added all subtitle formats in the generic DLNA profile to the LG profile and it works correctly.

**Comment by HybridSarcasm** [comment]
This has been open quite a while. Can this be re-produced with the current build? If so, please update the bug report details. Thanks!
