### ISSUE TITLE
Problem with video having mp3 audio on iOS

### ISSUE THREAD

**Issue by AlphaScorpii-dev** [jellyfin/jellyfin#6221]
I'm having an issue with video having a mp3 audio track, but on iOS only.
I have tested them when accessing my server from Firefox and Chrome (from a Windows laptop and a Chromebook) without any issue.
However, on iOS, I have no sound, neither from the Jellyfin app nor from Safari.
The same file works fine when read from VLC or the Jellyfin Native app (TestFlight)

**Media Info of the file**

> General
> Complete name                            : S01E20.mp4
> Format                                   : MPEG-4
> Format profile                           : Base Media
> Codec ID                                 : isom (mp41)
> File size                                : 459 MiB
> Duration                                 : 24 min 0 s
> Overall bit rate                         : 2 672 kb/s
> Encoded date                             : UTC 1970-01-01 00:00:00
> Tagged date                              : UTC 1970-01-01 00:00:00
> Writing application                      : PotEncoder
> 
> Video
> ID                                       : 1
> Format                                   : AVC
> Format/Info                              : Advanced Video Codec
> Format profile                           : Baseline@L3.1
> Format settings                          : 1 Ref Frames
> Format settings, CABAC                   : No
> Format settings, ReFrames                : 1 frame
> Codec ID                                 : avc1
> Codec ID/Info                            : Advanced Video Coding
> Duration                                 : 24 min 0 s
> Bit rate                                 : 2 348 kb/s
> Width                                    : 1 280 pixels
> Height                                   : 720 pixels
> Display aspect ratio                     : 16:9
> Frame rate mode                          : Constant
> Frame rate                               : 23.976 (23976/1000) FPS
> Color space                              : YUV
> Chroma subsampling                       : 4:2:0
> Bit depth                                : 8 bits
> Scan type                                : Progressive
> Bits/(Pixel*Frame)                       : 0.106
> Stream size                              : 403 MiB (88%)
> Encoded date                             : UTC 1970-01-01 00:00:00
> Tagged date                              : UTC 1970-01-01 00:00:00
> Codec configuration box                  : avcC
> 
> Audio
> ID                                       : 2
> Format                                   : MPEG Audio
> Format version                           : Version 1
> Format profile                           : Layer 3
> Format settings                          : Joint stereo
> Codec ID                                 : mp4a-6B
> Duration                                 : 23 min 59 s
> Bit rate mode                            : Constant
> Bit rate                                 : 320 kb/s
> Channel(s)                               : 2 channels
> Sampling rate                            : 44.1 kHz
> Compression mode                         : Lossy
> Stream size                              : 54.9 MiB (12%)
> Writing library                          : LAME3.98.2
> Encoded date                             : UTC 1970-01-01 00:00:00
> Tagged date                              : UTC 1970-01-01 00:00:00

**Logs**

> [2021-06-24 10:57:13.631 +00:00] [INF] [46] Jellyfin.Api.Controllers.MediaInfoController: GetPostedPlaybackInfo profile: DeviceProfile { Name: null, Id: null, Identification: null, FriendlyName: null, Manufacturer: null, ManufacturerUrl: null, ModelName: null, ModelDescription: null, ModelNumber: null, ModelUrl: null, SerialNumber: null, EnableAlbumArtInDidl: False, EnableSingleAlbumArtLimit: False, EnableSingleSubtitleLimit: False, SupportedMediaTypes: "Audio,Photo,Video", UserId: null, AlbumArtPn: null, MaxAlbumArtWidth: 0, MaxAlbumArtHeight: 0, MaxIconWidth: null, MaxIconHeight: null, MaxStreamingBitrate: 120000000, MaxStaticBitrate: 100000000, MusicStreamingTranscodingBitrate: 384000, MaxStaticMusicBitrate: null, SonyAggregationFlags: null, ProtocolInfo: null, TimelineOffsetSeconds: 0, RequiresPlainVideoItems: False, RequiresPlainFolders: False, EnableMSMediaReceiverRegistrar: False, IgnoreTranscodeByteRangeRequests: False, XmlRootAttributes: [], DirectPlayProfiles: [DirectPlayProfile { Container: "mp4,m4v", AudioCodec: "aac,mp3,ac3,eac3,flac,alac", VideoCodec: "h264", Type: Video }, DirectPlayProfile { Container: "mov", AudioCodec: "aac,mp3,ac3,eac3,flac,alac", VideoCodec: "h264", Type: Video }, DirectPlayProfile { Container: "mp3", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "aac", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "m4a", AudioCodec: "aac", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "m4b", AudioCodec: "aac", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "flac", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "alac", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "m4a", AudioCodec: "alac", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "m4b", AudioCodec: "alac", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "wav", AudioCodec: null, VideoCodec: null, Type: Audio }], TranscodingProfiles: [TranscodingProfile { Container: "aac", Type: Audio, VideoCodec: null, AudioCodec: "aac", Protocol: "hls", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 2, SegmentLength: 0, BreakOnNonKeyFrames: True }, TranscodingProfile { Container: "aac", Type: Audio, VideoCodec: null, AudioCodec: "aac", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "mp3", Type: Audio, VideoCodec: null, AudioCodec: "mp3", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "wav", Type: Audio, VideoCodec: null, AudioCodec: "wav", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "mp3", Type: Audio, VideoCodec: null, AudioCodec: "mp3", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "aac", Type: Audio, VideoCodec: null, AudioCodec: "aac", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "wav", Type: Audio, VideoCodec: null, AudioCodec: "wav", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "ts", Type: Video, VideoCodec: "h264", AudioCodec: "aac,mp3,ac3,eac3", Protocol: "hls", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 2, SegmentLength: 0, BreakOnNonKeyFrames: True }, TranscodingProfile { Container: "mp4", Type: Video, VideoCodec: "h264", AudioCodec: "aac,mp3,ac3,eac3,flac,alac", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: null, MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }], ContainerProfiles: [], CodecProfiles: [CodecProfile { Type: Video, Conditions: [ProfileCondition { Condition: NotEquals, Property: IsAnamorphic, Value: "true", IsRequired: False }, ProfileCondition { Condition: EqualsAny, Property: VideoProfile, Value: "high|main|baseline|constrained baseline", IsRequired: False }, ProfileCondition { Condition: LessThanEqual, Property: VideoLevel, Value: "51", IsRequired: False }, ProfileCondition { Condition: NotEquals, Property: IsInterlaced, Value: "true", IsRequired: False }], ApplyConditions: [], Codec: "h264", Container: null }, CodecProfile { Type: Video, Conditions: [ProfileCondition { Condition: NotEquals, Property: IsAnamorphic, Value: "true", IsRequired: False }, ProfileCondition { Condition: EqualsAny, Property: VideoProfile, Value: "main|main 10", IsRequired: False }, ProfileCondition { Condition: LessThanEqual, Property: VideoLevel, Value: "183", IsRequired: False }, ProfileCondition { Condition: NotEquals, Property: IsInterlaced, Value: "true", IsRequired: False }], ApplyConditions: [], Codec: "hevc", Container: null }], ResponseProfiles: [ResponseProfile { Container: "m4v", AudioCodec: null, VideoCodec: null, Type: Video, OrgPn: null, MimeType: "video/mp4", Conditions: [] }], SubtitleProfiles: [SubtitleProfile { Format: "vtt", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ass", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ssa", Method: External, DidlMode: null, Language: null, Container: null }] }
> [2021-06-24 10:57:13.658 +00:00] [INF] [46] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "manfred". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
> [2021-06-24 10:57:13.658 +00:00] [INF] [46] Jellyfin.Api.Helpers.MediaInfoHelper: Profile: "Unknown Profile", Path: "/media/S01E20.mp4", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
> [2021-06-24 10:57:13.659 +00:00] [INF] [46] Jellyfin.Api.Helpers.MediaInfoHelper: Profile: "Unknown Profile", Path: "/media/S01E20.mp4", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
> [2021-06-24 10:57:13.659 +00:00] [INF] [46] Jellyfin.Api.Helpers.MediaInfoHelper: Profile: "Unknown Profile", Path: "/media/S01E20.mp4", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
> [2021-06-24 10:57:15.812 +00:00] [WRN] [51] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://192.168.26.2:8096/Sessions/Playing" to "192.168.26.75" in 0:00:01.5552718 with Status Code 204
> [2021-06-24 10:57:16.390 +00:00] [WRN] [63] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://192.168.26.2:8096/Sessions/Playing/Progress" to "192.168.26.75" in 0:00:01.9096649 with Status Code 204
> [2021-06-24 10:57:20.333 +00:00] [WRN] [75] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS "192.168.26.75" error receiving data: "The remote party closed the WebSocket connection without completing the close handshake."
> [2021-06-24 10:57:20.391 +00:00] [ERR] [51] Emby.Server.Implementations.Session.SessionManager: Error reporting playback progress
> MediaBrowser.Common.Extensions.ResourceNotFoundException: Session 974adbf8df5032bccee4215d7cebf6ed not found.
>    at Emby.Server.Implementations.Session.SessionManager.GetSession(String sessionId, Boolean throwOnMissing)
>    at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
>    at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
> [2021-06-24 10:57:20.756 +00:00] [INF] [75] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.26.75" closed
> 

**Server System (please complete the following information):**
 - OS: Docker on Linux, installed on a Synology NAS
 - Jellyfin Version: 10.7.6
 - Hardware settings & device: Synology DS918+
 
**Client System (please complete the following information):**
 - Device: iPhone SE2
 - OS: iOS 14.6
 - Client: Jellyfin app / Safari
 - Client and Browser Version: Jellyfin 1.4.1 / Safari 14

**Comment by GDM-PTY** [comment]
Hello @AlphaScorpii-dev

This is not a Jellyfin issue. iOS doesn't support native mp3 compression because of something from a license, I can't quite remember.

There what you can do is use a third party application that comes with codec for example Infuse App

**Comment by srcrist** [comment]
Closing this issue as it does not reference a Jellyfin server bug.
