### ISSUE TITLE
Film identified incorrectly

### ISSUE THREAD

**Issue by ThomasPGH** [jellyfin/jellyfin#6223]
**Describe the bug**
Film "The Door (2009)" becomes "Someone's Knocking at the Door (2009)"

**System (please complete the following information):**
Windows 10, Jellyfin 10.7.6

**To Reproduce**
Create film "The Door (2009)". Scan library. It becomes "Someone's Knocking at the Door (2009)"

**Expected behavior**
Should be "The Door (2009)".

**Comment by ThomasPGH** [comment]
"Face (1997)" becomes "Face/Off (1997)"

**Comment by ThomasPGH** [comment]
Beyond (2015) (https://www.imdb.com/title/tt4270408/) is incorrectly identified as Beyond the Reach (2014) (https://www.imdb.com/title/tt2911668/).

**Comment by NebelNidas** [comment]
That happens quite often, if the movies' names are too similar. The solution is to embed the IMDB or TMDB id into the movie filename. See [here](https://support.emby.media/support/solutions/articles/44001159102-movie-naming) under "ID Tags in Folder & File Names"

**Comment by ebb-earl-co** [comment]
That's a great resource, @NebelNidas. IMO this issue is more about the service chosen to fetch metadata than Jellyfin itself, so maybe move to close it with the resource that @NebelNidas linked to?
