### ISSUE TITLE
Library scans take long time even with all metadata disabled

### ISSUE THREAD

**Issue by gitterspec** [jellyfin/jellyfin#6224]
For my movies and TV shows, I use "Music Videos" and turn off all Fetchers in order to make sure no metadata is fetched. Combining this with "Folders" view, I am trying to use Jellyfin in a raw "file explorer" mode. However, it still takes a long time i.e. a few minutes to scan a couple hundred files. If all metadata/fetchers are disabled, shouldn't this be the speed of a directory listing i.e. <1 second?

**Comment by Artiume** [comment]
ffprobe will still be used to detect codecs and details about the files and write all this to the database, that's going to take time and not be instant.
