### ISSUE TITLE
Can't create bookmark when reading an ebook

### ISSUE THREAD

**Issue by tuxrinku** [jellyfin/jellyfin#6225]
**Describe the bug**
I can't find a way to add a bookmark while reading an ebook. I have the different chapters entries in the menu but I can't add custom ones.

**System (please complete the following information):**
 - OS: Ubuntu 20.04
 - Virtualization: Docker
 - Clients: Browser and Android
 - Browser: Firefox 89
 - Jellyfin Version: 10.7.5
 - Reverse Proxy: nginx
 - Base URL: none
 - Networking: Host
 - Storage: local

**Comment by crobibero** [comment]
This isn’t a bug, but a feature request. 
Feature requests belong at https://features.jellyfin.org/
