### ISSUE TITLE
Button to increase playback speed disappears when casting to TV/device

### ISSUE THREAD

**Issue by TyranitarTar** [jellyfin/jellyfin#6226]
Not sure if this is a bug, or a not as of yet implemented feature. 

But when I cast from my Galaxy Note phone to my Samsung TV, the button to increase playback speed disappears. If you stop casting and watch on the native player on the android app, it comes back.

I know that it's possible to cast with increased playback speed, since if you use VLC as an external player and cast to your TV, you can increase the cast playback speed.

**Comment by HybridSarcasm** [comment]
This has been open quite a while. Can this be re-produced with the current build? If so, please update the bug report details. Thanks!

**Comment by srcrist** [comment]
Closing this issue as it does not contain a genuine Jellyfin bug.
