### ISSUE TITLE
Dashboard - Current playback information missing

### ISSUE THREAD

**Issue by timonoj** [jellyfin/jellyfin#6230]
Hi guys! I have this minor bug in the dashboard, where the tiles showing what each client is playing is missing the little button that actually shows how the playback is being done, whether there's transcoding being done and the reason for it. I get the icon next to it, to send a message to the client, but not the one to show the playback details.

Any ideas what might be causing it?

Running Jellyfin 10.7.6 on an Ubuntu 20.04.2 LXC container. This icon is missing in any browser I'm using, Chrome, Firefox and Edge. The Android app also misses it.
![jellyfin_no_playback_details](https://user-images.githubusercontent.com/10449143/123513815-e2fa0380-d6c1-11eb-8575-901a5bbf5e6c.png)

**Comment by Bond-009** [comment]
Still an issue on the latest release/master?

**Comment by Bond-009** [comment]
Closing as stale
