### ISSUE TITLE
Jellyfin LDAP Authenticated Users Cannot Change their password

### ISSUE THREAD

**Issue by ukyawzinlatt** [jellyfin/jellyfin#6245]
I have setup Jellyfin server 10.7.5. with LDAP plugin LDAP-Auth11.0.0.0 version. After setup properly, LDAP authenticated users cannot change their own password. Is there possible way for users can change their passwords with LDAP authentication?

**Comment by crobibero** [comment]
There’s a PR to implement this, but it hasn’t been merged.

https://github.com/jellyfin/jellyfin-plugin-ldapauth/pull/53

Additionally, plugin specific issues should be created in the plugin repo.
