### ISSUE TITLE
Possible to set EnableMetrics via environment variable?

### ISSUE THREAD

**Issue by se-jaeger** [jellyfin/jellyfin#6247]
I tried to enable prometheus monitoring at startup but could not find the possibility to see `EnableMetrics` to true.

Does somebody know if and how this is possible?

I checked the code but I'm not familiar with C#.

**Comment by BaronGreenback** [comment]
The setting is in the settings.xml file found in the data folder.

**Comment by se-jaeger** [comment]
Thanks, I actually found it and it works as expected. My question was rather if it is possible to enable monitoring before the first startup. I use automated deployment on kubernetes and it would be great to set this with an env variable for example.

**Comment by BaronGreenback** [comment]
Not at the moment. Might be able to have two config folders and do it via a different environmental var.

**Comment by srcrist** [comment]
Closing this issue as it does not reference a Jellyfin bug. I took the liberty of migrating this feature request to https://features.jellyfin.org/posts/2397/enable-metrics-with-env-variable for you.

**Comment by donaldgifford** [comment]
Add this `JELLYFIN_EnableMetrics=true` for it to use the env var to set it.
