### ISSUE TITLE
Incorrect display of Romanian diacritics fonts in the subtitle files

### ISSUE THREAD

**Issue by ioan-stan** [jellyfin/jellyfin#6251]
**Describe the bug**

Incorrect display of Romanian diacritics fonts in the Romanian subtitle files, as shown in the screenshot attached. There are about five such special fonts.

**System (please complete the following information):**
 - OS: [Ubuntu 20.04]
 - Virtualization: [none]
 - Clients: [any]
 - Browser: [any]
 - Jellyfin Version: [10.7.6]
 - Playback: [any] 
 - Installed Plugins: [None]
 - Reverse Proxy: [none]
 - Base URL: [none]
 - Networking: [Host]
 - Storage: [local
![fonts issue](https://user-images.githubusercontent.com/60917232/124284795-41265b00-db88-11eb-8411-f1e30afa45d7.PNG)
]

**To Reproduce**

Anytime Romanian srt file is played

**Comment by crobibero** [comment]
As I said in your Reddit post, you need to add falback fonts.

**Comment by ioan-stan** [comment]
Hi Crobibero, it seems fallback fonts work with ass subtitles, not with srt ones. Please correct me if you can prove otherwise.

How can we track this issue and follow up?
