### ISSUE TITLE
Disable Transcoding in LAN?

### ISSUE THREAD

**Issue by Horuyuki** [jellyfin/jellyfin#6252]
I am using jellyfin in local network.

I have movies in 264 and 265. Is there a way for me to stream them directly without using ffmpeg to transcode?

It is eating up so much of my CPU that way things become laggy.

**Comment by BaronGreenback** [comment]
Need more information - which client are you using - and onto what device?

Is the end device capable of direct playing 264 and 265?

**Comment by Horuyuki** [comment]
Host computer is arch installation from AUR `10.7.6-1`

Onto iPad 6th gen and also localhost:8096

iPad was able to play back the codec, and in any case the localhost web UI should not need to fire up ffmpeg in order to play the movies since it is a local web UI.

And yes, using mpv to play those 264 and 265 works nicely.

**Comment by ebb-earl-co** [comment]
@Horuyuki you could create a user account for which transcoding is disabled and use that account on the clients (iPad, others) that are trying to play back on the local network.

**Comment by BigusBeckus** [comment]
I use the same method @ebb-earl-co suggested and it can definitely cause some playback issues. I'm on android so I have the client set to use an external player (MX Player) which works well enough. If there's a similar option on iOS, that might be your best bet.

**Comment by cvium** [comment]
This sounds like a [feature request](https://features.jellyfin.org/) to me. We do not currently have the capability to disable transcoding based on network.
