### ISSUE TITLE
ffmpeg segfaults when using NVENC through Jellyfin

### ISSUE THREAD

**Issue by peperunas** [jellyfin/jellyfin#6254]
**Describe the bug**
`NVENC` does not work when `ffmpeg` is called by Jellyfin, resulting in a segfault.

If `ffmpeg` is called with the same command line arguments by a regular user, the video is transcoded correctly.

**System (please complete the following information):**
 - OS: NixOS
 - Virtualization: None
 - Clients: Web
 - Browser: Firefox 79
 - Jellyfin Version: 10.7.6
 - Playback: Transcode
 - Installed Plugins: none
 - Reverse Proxy: nginx
 - Base URL: none
 - Networking: Host
 - Storage: local

**To Reproduce**
1. Activate NVENC in playback options.
2. Force a video to be transcoded

**Expected behavior**
The video is transcoded correctly and the media reproduces.

**System Logs**

This is the segfault when `ffmpeg` is invoked by Jellyfin.

```
Jul 02 20:16:00 x jellyfin[13999]: [20:16:00] [INF] [85] Jellyfin.Api.Helpers.TranscodingJobHelper: /nix/store/4s28gah285pmn9644vkqy7g2r9sn5j3g-ffmpeg-4.4-bin/bin/ffmpeg -c:v h264_cuvid -resize 424x176 -i file:"/media/.." -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_nvenc -pix_fmt yuv420p -preset default -b:v 336000 -maxrate 336000 -bufsize 672000 -profile:v:0 high -g:v:0 72 -keyint_min:v:0 72 -sc_threshold:v:0 0 -start_at_zero -vsync -1 -codec:a:0 aac -ac 6 -ab 384000 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/var/lib/jellyfin/transcodes/ead9b2810d5eb25f8f8d4cb73e734267%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/var/lib/jellyfin/transcodes/ead9b2810d5eb25f8f8d4cb73e734267.m3u8"
Jul 02 20:16:01 x systemd-coredump[89702]: Process 89700 (ffmpeg) of user 996 dumped core.
```

**FFmpeg Logs**

When the same command is **executed by a normal user or by the jellyfin user** in separate shell, the media is transcoded correctly.

**Comment by cvium** [comment]
Seems more like a nixos problem and not a jellyfin problem

**Comment by joshuaboniface** [comment]
>"/var/lib/jellyfin/transcodes/ead9b2810d5eb25f8f8d4cb73e734267.m3u8"

If I had to guess, this is probably (part of) the issue, given that NixOS doesn't have normal LFHS paths like that. Try changing your transcoding temp dir in the settings.

**Comment by peperunas** [comment]
Closed by https://github.com/NixOS/nixpkgs/pull/163491
