### ISSUE TITLE
First start language menu still empty choice.

### ISSUE THREAD

**Issue by jerome-diver** [jellyfin/jellyfin#6261]
**Describe the bug**
[same than this report](https://github.com/jellyfin/jellyfin/issues/6250) that has been close by @crobibero without any fix done (so i don't know why he decide to close it, please, do not do that it doesn't help).
[posted also here](https://github.com/jellyfin/jellyfin-web/issues/2780)

**Comment by crobibero** [comment]
This is not a server issue. Please continue in the linked web issue.
