### ISSUE TITLE
Can't grant "Playlist" Library access to users

### ISSUE THREAD

**Issue by embolon** [jellyfin/jellyfin#6264]
**Describe the bug**

Administrator can't grant a user "Playlist" Library access without enable access to all libraries.

**System (please complete the following information):**
 - OS: [Debian]
 - Virtualization: [Docker]
 - Clients: [Browser]
 - Browser: [Microsoft Edge]
 - Jellyfin Version: [10.7.6 stable]
 - Playback: [Direct Play, Remux, Direct Stream, Transcode] 
 - Installed Plugins: [TVDB]
 - Reverse Proxy: [none]
 - Base URL: [none]
 - Networking: [Bridge, 8096 exposed]
 - Storage: [Local]

**To Reproduce**

2. Click on 'Users'
3. Scroll down to 'Library accesses'
4. No "Playlist" Shows up to grant to a user
5. Have to choose "Enable access to all libraries" to make the user able to use a playlist even if the playlist is generated by that user.

**Expected behavior**

"Playlist" should show up as one of the Libraries to grant to the user like "Collections"

**Server Logs**

When user tries to the access the Playlist Library. It just keeps cycle and docker shows this error.
[06:40:51] [WRN] [28] Jellyfin.Api.Controllers.ItemsController: jellyfin is not permitted to access Library Playlists.

**FFmpeg Logs**

**Browser Console Logs**

**Screenshots**

**Additional context**

**Comment by BeecherNetworks** [comment]
Can confirm this, same problem.

**Comment by itkfilelor** [comment]
same here. 10.7.7

**Comment by rickysarraf** [comment]
I have the same problem on JellyFin 10.8.1

My restricted normal user, that created the Playlist in the first place, is not able to access it.

**Comment by Shadowghost** [comment]
Playlists are designed to be user specific. So the library will pop up once the user created a playlist.
Access control is fixed by #8526 leading to all items in a playlist are playable by the user and only the user having access to the playlist.

**Comment by meonkeys** [comment]
Related: https://features.jellyfin.org/posts/173/share-playlists

**Comment by fiver22** [comment]
> https://github.com/jellyfin/jellyfin/pull/9466 exposes the playlist ACL interface via the API. Jellyfin web needs to implement granting permissions though.

Is there any end-user facing documentation that explains how to do this -share a playlist to other users?

**Comment by Shadowghost** [comment]
Since the user-facing interface in Jellyfin-Web is still not implemented there is no way for users to utilize this functionality right now. Keep in mind that this is feature is only available in unstable right now anyway

**Comment by srcrist** [comment]
Issue closed by https://github.com/jellyfin/jellyfin/pull/8526 and https://github.com/jellyfin/jellyfin/pull/9466.
