### ISSUE TITLE
feature suggestion

### ISSUE THREAD

**Issue by sH1222J** [jellyfin/jellyfin#6265]
**PLEASE DO NOT OPEN FEATURE REQUEST ISSUES ON GITHUB**

**Feature requests should be opened on our dedicated [feature request](https://features.jellyfin.org/) hub so they can be appropriately discussed and prioritized.**

However, if you are willing to contribute to the project by adding a new feature yourself, then please ensure that you first review our [documentation](https://docs.jellyfin.org/general/contributing/development.html) on contributing code. Once you have reviewed the documentation, feel free to come back here and open an issue here outlining your proposed approach so that it can be documented, tracked, and discussed by other team members.

The built-in player in the Jellypin app for Android doesn't seem to have a 10-second rewind or 10-second fast-forward feature. Please put

Image types have a 'list' on the web, but not in the Android app.
request more

**Comment by crobibero** [comment]
Please read before opening feature requests.
