### ISSUE TITLE
Duplicate Album Listing

### ISSUE THREAD

**Issue by MattKercher** [jellyfin/jellyfin#6271]
**Describe the Bug**
When artists are featured on an album as a guest artist, the album appears under both the artist's list of albums (as if they're the album artist) as well as appearing under the "Appears On" label. Including the artist under only one or a few of the tracks on the album should only show the album under the "Appears On" label. In my case, I have both the album artist and the guest artist included under the Vorbis tag for "Artist" using a semi-colon as a delimiter, and the artist is only included on one of the tracks. I can't be positive, but I'm fairly sure this is a new bug, as I think previously the albums were only shown under "Appears On", unless I just didn't notice it being in both places until recently. 

Side Note: I tried to confirm the bug for Android TV, but Android TV doesn't include an "Appears On" row nor does it seem to support multiple artists listed under the track. Instead the album they're guest featured on is listed under the "Albums" row, while going to the album doesn't show the artist being guest featured whatsoever.

**System:**
 - OS: Arch Linux
 - Virtualization: N/A
 - Clients: Browser, Android
 - Browser: Firefox 89
 - Jellyfin Version: 10.7.6
 - Playback: Direct Play
 - Installed Plugins: AudioDB, Bookshelf, MusicBrainz, OMDb, Open Subtitles, TheTVDB
 - Reverse Proxy: Apache
 - Base URL: none
 - Storage: local

**To Reproduce**
1. Include a guest artist in the artist field.
2. Refresh the library
3. Go to the guest artist's page
4. See duplicate album under "Albums" and "Appears On"

**Expected behavior**
I'd expect the album only be featured under "Appears On", as they're not the album artist.

**Screenshots**
Elton John is one of the artists listed with 'The Pink Phantom' on 'Song Machine', but as you can see on his artist page it shows it both as it being his album as well as it him being a guest on it.
![Elton John shows Song Machine as one of his albums](https://goggles.cloud/s/J4ZsXAcALsCrtiG/preview) ![Song Machine only has Elton John listed under one of the tracks](https://goggles.cloud/s/jfXGSXC9S9cktQL/preview)

**Additional Context**
MusicBrainz is listed first followed by AudioDB for the metadata downloaders on the library, but I'm not sure if that's relevant since Jellyfin tends to honor the Vorbis/ID3 tags for stuff like this.

**Comment by tuxsudo12** [comment]
I have this same issue, using 10.7.7 on Linux

**Comment by telans** [comment]
Please just tag this as confirmed

**Comment by telans** [comment]
Still current

**Comment by Bond-009** [comment]
Is this still an issue in the latest release (currently 10.9.4)?

**Comment by felix920506** [comment]
Comments suggest issue fixed in 10.9, closing
