### ISSUE TITLE
Unable to bind to loopback

### ISSUE THREAD

**Issue by kevincox** [jellyfin/jellyfin#6272]
I'm having the same issue described in the original post. I am trying to bind to localhost but instead Jellyfin is binding to all addresses. This is a security and privacy issue.

```
[INF] Defined LAN addresses : [127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[INF] Defined LAN exclusions : []
[INF] Using LAN addresses: [127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[INF] Using bind addresses: []
[INF] Using bind exclusions: []
...
[INF] Kestrel listening on Any IP4 Address
```

See https://github.com/jellyfin/jellyfin/issues/5761 for context.

**Comment by crobibero** [comment]
Please fill out the full issue template, and please include the full network.xml.

**Comment by kevincox** [comment]
Please see https://github.com/jellyfin/jellyfin/issues/5761#issuecomment-817184015. I am now running jellyfin 10.7.6

**Comment by kevincox** [comment]
**System (please complete the following information):**
 - OS: NixOS
 - Virtualization: None
 - Clients: N/A
 - Browser: N/A
 - Jellyfin Version: [e.g. 10.4.3, nightly 20191231]
 - Playback:N/A
 - Installed Plugins: none
 - Reverse Proxy: N/A
 - Base URL:N/A
 - Networking: Host
 - Storage: local

**To Reproduce**

1. Use linked network.xml. Notably setting the bind address to 127.0.0.1
2. Start jellyfin
3. Try to access port from a different machine.
4. It works!!!

**Expected behavior**
Jellyfin binds to localhost when told to and doesn't leak itself.

**Server Logs**
See linked issue.

**FFmpeg Logs**
N/A

**Browser Console Logs**
N/A

**Screenshots**
N/A

**Additional context**

**Comment by kevincox** [comment]
I have found a mitigation to making the port public.

1. Apply
2. Use `systemd` option `PrivateNetwork=true`.
3. Configure Jellyfin to listen on a UNIX socket.

You can do a similar thing without systemd but this way Jellyfin will have no ability to bind to an external IP address, keeping it secure. You can the use a reverse proxy or similar to connect to the unix socket.

The main downside is that this also prevents outbound connections. But that is better than being public in my opinion.
