### ISSUE TITLE
Firefox playback stops randomly

### ISSUE THREAD

**Issue by Iss-in** [jellyfin/jellyfin#6273]
**Describe the bug**
Playback stops most of the time at few certain specific time in every long media file, only way to go forward is to click on a somewhat later time in stream. Issue occurs in Firefox only. 

for logs, played the video from a bit before its stopping point(different for different files)  multiple times. weirdly  those particular stop time bookmark went away after I tested a few times for logs( video stopped there ). 
**System (please complete the following information):**
 - OS: Arch
 - Virtualization: None
 - Clients: Browser
 - Browser: Firefox  89.0.2-1
 - Jellyfin Version:  10.7.6-1
 - Playback: VAAPI
 - Installed Plugins: Audiodb,OMDB,Open Subtitles,MusicBrainz
 - Reverse Proxy:  none
 - Base URL:  /jellyfin
 - Networking:  Host
 - Storage:  local

**To Reproduce**
1. Play a video file ( preferably a tv show )
2. Playback always stops at some unique time point for a particular video, ie  for a file sample.mkv, playback stops automatically at time t1 and t2 between its duration

**Expected behavior**
should play till end without any interruption

** Logs**
https://gist.github.com/Iss-in/c492b2b499a65013bdc6f5a3cbc6b4fc

**Browser Console Logs**  -- in gist, gives error sometimes

**Comment by wvengen** [comment]
Same thing here:

 -  OS: Debian 11.0
 -  Virtualization: None
 -  Clients: Browser
 -  Browser: Firefox 93.0 on Ubuntu
 -  Jellyfin Version: 10.7.7-1
 -  Playback: VAAPI
 -  Installed Plugins: Audiodb,OMDB,MusicBrainz
 -  Reverse Proxy: none
 -  Base URL: /
 -  Networking: Host
 -  Storage: local

Happened with various movies, often after ~30min-1h (?), then after 5-20min. Playback stalls. If I wait for 1-4 minutes, the stream may continue to play (first with audio only, then video comes in too).

@lss-in the gist is inaccessible

**Comment by sevenrats** [comment]
These logs clearly show that your network becomes temporarily unreachable. It's not clear that this is a bug in jellyfin or jellyfin-web.
