### ISSUE TITLE
SSA/ASS Subtitles are hidden behind video

### ISSUE THREAD

**Issue by petertriho** [jellyfin/jellyfin#6275]
Probably related to #6122, but subtitles are appearing behind the video (does not happen in VLC)

This happens to any version after 10.7.6, no issues with 10.7.5

**Comment by ikomhoog** [comment]
How do you know they are actually behind the video?
Or how can I test it to see if it is indeed the same as my issue?

**Comment by petertriho** [comment]
I tested it with a 4:3 video and saw subtitles on the sides of the video (in the black bars on the side).

Might be worth testing out 10.7.5 as that worked for me

**Comment by sevenrats** [comment]
please provide the info necessary to recreate this issue, such as client versions.

**Comment by petertriho** [comment]
I'm on v10.8.11 now and it doesn't look like it's an issue anymore
