### ISSUE TITLE
Albums don't display the artist below the title if tracks contain no embedded metadata

### ISSUE THREAD

**Issue by digitalentity** [jellyfin/jellyfin#6278]
**Describe the bug**
In some of the albums in my library the artist is not shown:
![image](https://user-images.githubusercontent.com/11059099/125157575-25185000-e16c-11eb-9ec0-e3d7e2eae94d.png)

Metadata is correctly (yet manually) populated on album tracks (MusicBrainz didn't populate it, but that's a different issue).

Files don't have ID3 tags.

**System (please complete the following information):**
 - OS: Ubuntu
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Chrome 91
 - Jellyfin Version: 10.7.6
 - Storage: NFS

**To Reproduce**
This issue can't be reproduced at will, but happens consistently to the same album.

**Expected behavior**
Album artist is displayed

**Comment by digitalentity** [comment]
This actually quite reliably happens with music files that don't contain ID3 tags. Album might be correctly identified by Jellyfin with MusicBrainz, but individual tracks metadata is not populated. As a result - no artist is displayed on the album and order of tracks is not correct (alphabetical, instead of as-in-album)

**Comment by digitalentity** [comment]
Confirmed, if files don't contain embedded metadata, Album/Artist/Song name are not correctly identified by Jellyfin even if metadata is populated manually later

**Comment by digitalentity** [comment]
Update:

**To Reproduce:**

1. Create a new Album folder (not currentl existing in the library)
2. Add a single MP3 track without embedded metadata (w/o ID3 tag)
3. Scan the library
4. Observe a new album without an artist
5. Set the metadata manually on the album and track
6. Observe the album **still** without an artist
7. Update a file with any ID3 tag editor, populate the artist, track name, track number and album fields
8. Scan the libraty
9. Observe the album with correct metadata and with correct cover images got from MusicBrainz

**Comment by rpavlik** [comment]
Hmm, not sure if I'm seeing this or if I am seeing something else: the symptom is the same, but all my files have been updated by musicbrainz picard to have metadata tags.
