### ISSUE TITLE
Rebuilt Docker Container and certain Top Directory Libraries fail to load and Search Broken

### ISSUE THREAD

**Issue by manakill** [jellyfin/jellyfin#6282]
**Describe the bug**

Rebuilt the Docker to update to latest version. Now some things don't load at all.

**Search button doesn't do anything now**

My "Kids TV-Shows" loads fine however "Kids Movies" shows blank and is unresponsive. 

My "Adult TV-Shows" loads fine however "Adult Movies" shows blank and is unresponsive.

**System (please complete the following information):**
 - OS: [e.g. Debian, Windows] Raspian
 - Virtualization: [e.g. Docker, KVM, LXC] Docker
 - Clients: [Browser, Android, Fire Stick, etc.] Android, Browser
 - Browser: [e.g. Firefox 72, Chrome 80, Safari 13] Firefox
 - Jellyfin Version: [e.g. 10.4.3, nightly 20191231] v 10.7.6
 - Playback: [Direct Play, Remux, Direct Stream, Transcode] ---
 - Installed Plugins: [e.g. none, Fanart, Anime, etc.] ---
 - Reverse Proxy: [e.g. none, nginx, apache, etc.] Caddy
 - Base URL: [e.g. none, yes: /example] ---
 - Networking: [e.g. Host, Bridge/NAT] Bridge
 - Storage: [e.g. local, NFS, cloud] External Drive

**To Reproduce**
Retry what I said with folders and categories structured the same

**Expected behavior**
The sections load as normal.

Loads fine:
![image](https://user-images.githubusercontent.com/9597295/125171615-24d77f00-e183-11eb-9435-0a9db376b95f.png)

Kids TV and Adult TV Loads fine:
![image](https://user-images.githubusercontent.com/9597295/125171636-3b7dd600-e183-11eb-8729-7f8e90e29f6d.png)

Adult and Kids Movies is Blank:
![image](https://user-images.githubusercontent.com/9597295/125171649-4b95b580-e183-11eb-8ece-b0b41b6265e2.png)

**Comment by crobibero** [comment]
What docker tag are you pulling from?
“Newest Docker Pull” doesn’t really mean anything

**Comment by manakill** [comment]
linuxserver/jellyfin:latest
v 10.7.6

**Comment by crobibero** [comment]
Please provide server logs

**Comment by manakill** [comment]
> 
> 
> Please provide server logs

Which ones? Portainer?

**Comment by manakill** [comment]
Ok so the Portainer logs didn't show anything abnormal and after some hours I tried again and it appears to be working all fine now. I hate it when that happens lol.
