### ISSUE TITLE
Remux not affected by transcode throttle

### ISSUE THREAD

**Issue by krutburken** [jellyfin/jellyfin#6299]
**Describe the bug**
When remuxing, the throttle setting seems to be ignored. Maybe this is more of feature request since the option clearly is a transcode throttle, but anyway...

**System (please complete the following information):**
 - OS: CentOS
 - Virtualization: Docker
 - Clients: All that needs remuxing
 - Jellyfin Version: 10.7.6
 - Playback: Remux
 - Reverse Proxy: nginx
 - Base URL: none
 - Networking: bridge
 - Storage: nfs

**To Reproduce**
1. Activate transcode throttle
2. Start playback for an item that requires remux
3. Jellyfin/ffmpeg remuxes the whole file at once without throttling, causing lag before the playback starts

**Expected behavior**
Remux should happen in chunks dependent on current playback location.

**Server Logs**
Not really an error, but I can add logs if needed.

**Additional context**
The background here is that the remux congests the network if you run storage on a machine separate to where the jellyfin application is hosted. My storage (repurposed netapp san running zfs) can handle up to 10gbit sequential reads, but the network between the two is only 1gbit.

**Comment by Artiume** [comment]
are you using hardware acceleration at all? Can you provide ffmpeg logs

**Comment by krutburken** [comment]
Yes nvenc, though the remux gets done on cpu regardless. "Unfortunately" remuxes are pretty rare in my library since I transcoded all my media, but I'll see if I can produce one

**Comment by Artiume** [comment]
https://github.com/jellyfin/jellyfin/blob/607df7899f8402b9e550c02b93fff36d89537f8c/Jellyfin.Api/Helpers/TranscodingJobHelper.cs#L624

So while hardware acceleration is enabled, the throttler is disabled. Though while remuxing, I'm not even sure that the gpu would be used so it might make sense to allow remuxing with hardware accel enabled. @nyanmisaka you have any thoughts?

**Comment by krutburken** [comment]
Ah I see, didn't know that. Well in that case this isn't really a bug, but a feature request to add an option to throttle the remux process.

**Comment by nyanmisaka** [comment]
> So while hardware acceleration is enabled, the throttler is disabled. Though while remuxing, I'm not even sure that the gpu would be used so it might make sense to allow remuxing with hardware accel enabled. @nyanmisaka you have any thoughts?

I will try out this throttling impl with HWA and see if we can re-enable it.

As for not working in remux:
https://github.com/jellyfin/jellyfin/blob/9f378feb82f7145b060ca69cd5c69b44abd2690e/Jellyfin.Api/Helpers/TranscodingJobHelper.cs#L632

**Comment by srcrist** [comment]
Issue closed by https://github.com/jellyfin/jellyfin/pull/7994

**Comment by srcrist** [comment]
Issue closed by https://github.com/jellyfin/jellyfin/pull/7994
