### ISSUE TITLE
Videos Recorded in Portrait Mode are Rotated -90 Degrees When Transcoded using (h264_nvenc)

### ISSUE THREAD

**Issue by ChildLearningClub** [jellyfin/jellyfin#6305]
**Describe the bug**

Videos Recorded in Portrait Mode are Rotated -90 Degrees When Transcoded using (h264_nvenc). Believe related to the "displaymatrix: rotation of -90.00 degrees" parameter added to the end of the nvenc ffmpeg command.

**System (please complete the following information):**
 - OS: [Windows]
 - Clients: [Windows, ios]
 - Browser: [Firefox 72]
 - Jellyfin Windows Server Version [10.7.6]
 - Playback: [Transcode NVENC] 
 - Reverse Proxy: [nginx]

**To Reproduce**

1. Enable NVENC 264 transcoding
2. play video that has been recorded in portait mode using transcoding and nvenc.
3. result is video played back at a -90 degree rotaton.
 
**Expected behavior**

The video should play back in the same orientation as the non trans-coded video plays. 

**FFmpeg Logs**
------------------------------------------------------
**LIBX264**

`  Duration: 00:01:42.85, start: 0.000000, bitrate: 15528 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1920x1080, 15371 kb/s, 30 fps, 30 tbr, 600 tbn, 1200 tbc (default)
    Metadata:
      rotate          : 90
      creation_time   : 2021-05-21T07:02:15.000000Z
      handler_name    : Core Media Video
      encoder         : H.264
    Side data:
      displaymatrix: rotation of -90.00 degrees
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, mono, fltp, 100 kb/s (default)
    Metadata:
      creation_time   : 2021-05-21T07:02:15.000000Z
      handler_name    : Core Media Audio
    Stream #0:2(und): Data: none (mebx / 0x7862656D) (default)
    Metadata:
      creation_time   : 2021-05-21T07:02:15.000000Z
      handler_name    : Core Media Metadata
    Stream #0:3(und): Data: none (mebx / 0x7862656D), 9 kb/s (default)
    Metadata:
      creation_time   : 2021-05-21T07:02:15.000000Z
      handler_name    : Core Media Metadata
    Stream #0:4(und): Data: none (mebx / 0x7862656D), 37 kb/s (default)
    Metadata:
      creation_time   : 2021-05-21T07:02:15.000000Z
      handler_name    : Core Media Metadata
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
[libx264 @ 00000194e0edd280] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 00000194e0edd280] profile Main, level 4.1, 4:2:0, 8-bit
[libx264 @ 00000194e0edd280] 264 - core 159 r2991 1771b55 - H.264/MPEG-4 AVC codec - Copyleft 2003-2019 - http://www.videolan.org/x264.html - options: cabac=1 ref=1 deblock=1:0:0 analyse=0x1:0 me=dia subme=0 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=4 chroma_me=0 trellis=0 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=0 threads=24 lookahead_threads=4 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=1 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=10 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 vbv_maxrate=319 vbv_bufsize=639 crf_max=0.0 nal_hrd=none filler=0 ip_ratio=1.40 aq=1:1.00
Output #0, hls, to 'C:\ProgramData\Jellyfin\Server\transcodes\9f2947bad90ef32d672e1e7b3198b2c9.m3u8':
  Metadata:
    encoder         : Lavf58.45.100
    Stream #0:0: Video: h264 (libx264), yuv420p, 426x756, q=-1--1, 30 fps, 90k tbn, 30 tbc (default)
    Metadata:
      encoder         : Lavc58.91.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 319000/0/0 buffer size: 639000 vbv_delay: N/A
      displaymatrix: rotation of -0.00 degrees`

RESULT:

![firefox_Su2KT9Hn49](https://user-images.githubusercontent.com/25701774/125763794-abe42a0e-f811-4122-aa78-a6d67a134ad8.png)

------------------------------------------------------
**H264_NVENC**

`  Duration: 00:01:42.85, start: 0.000000, bitrate: 15528 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1920x1080, 15371 kb/s, 30 fps, 30 tbr, 600 tbn, 1200 tbc (default)
    Metadata:
      rotate          : 90
      creation_time   : 2021-05-21T07:02:15.000000Z
      handler_name    : Core Media Video
      encoder         : H.264
    Side data:
      displaymatrix: rotation of -90.00 degrees
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, mono, fltp, 100 kb/s (default)
    Metadata:
      creation_time   : 2021-05-21T07:02:15.000000Z
      handler_name    : Core Media Audio
    Stream #0:2(und): Data: none (mebx / 0x7862656D) (default)
    Metadata:
      creation_time   : 2021-05-21T07:02:15.000000Z
      handler_name    : Core Media Metadata
    Stream #0:3(und): Data: none (mebx / 0x7862656D), 9 kb/s (default)
    Metadata:
      creation_time   : 2021-05-21T07:02:15.000000Z
      handler_name    : Core Media Metadata
    Stream #0:4(und): Data: none (mebx / 0x7862656D), 37 kb/s (default)
    Metadata:
      creation_time   : 2021-05-21T07:02:15.000000Z
      handler_name    : Core Media Metadata
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (h264_nvenc))
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
Output #0, hls, to 'C:\ProgramData\Jellyfin\Server\transcodes\470b56c8671b84c28231aed288ad8cc2.m3u8':
  Metadata:
    encoder         : Lavf58.45.100
    Stream #0:0: Video: h264 (h264_nvenc) (High), cuda, 426x238, q=-1--1, 319 kb/s, 30 fps, 90k tbn, 30 tbc (default)
    Metadata:
      encoder         : Lavc58.91.100 h264_nvenc
    Side data:
      cpb: bitrate max/min/avg: 319892/0/319892 buffer size: 639784 vbv_delay: N/A
      displaymatrix: rotation of -90.00 degrees`

RESULT:

![firefox_Srh4floiMA](https://user-images.githubusercontent.com/25701774/125763726-955440aa-370a-4d2a-a9c6-28966f880c08.jpg)

**Additional context**

Auto - Direct play will play back the video without the -90 Rotation, as does when trans-coded with the CPU libx264, it's only when run through NVENC being trans-coded and videos taken in "portrait" that the -90 degree rotation occurs. There is no issue with videos originally recorded in "landscape" mode

**Comment by HybridSarcasm** [comment]
This has been open quite a while. Can this be re-produced with the current build? If so, please update the bug report details. Thanks!

**Comment by ChildLearningClub** [comment]
@HybridSarcasm I apologize I did not see your last reply from Oct last year. I will close this and reopen/ create a new one if I experience this issue again when I have time to test it.

**Comment by ChildLearningClub** [comment]
Thank you.
