### ISSUE TITLE
Metadata refresh deletes existing background images when there are non to fetch

### ISSUE THREAD

**Issue by tamburra** [jellyfin/jellyfin#6310]
**Describe the bug**

Refreshing metadata of a TV Show season with "Replace existing images" enabled will delete pre existing background images when there are non to fetch.  

I am manually organizing UFC PPV in a tv show library with the metadata locked on the tv show so I can manually organize the show without Jellyfin making any changes to the metadata.  The season numbers and episodes numbers do not correspond with any metadata provider.  Because I lock the series from updating nfo metadata, no thumbnails are generated when I add content to the server (which is expected).  I do run the refresh metadata with replace existing images enabled so the TV Screen Grabber can grab a screenshot thumbnail for the episodes I add.  The main issue is that Jellyfin is deleting a background image i already have in place when i run the refresh metadata.  All other primary and thumbnail images are NOT deleted.  Only the background image is deleted on refresh.

**System (please complete the following information):**
 - OS: Debian Buster
 - Virtualization: Docker linuxserver.io
 - Jellyfin Version: 10.7.6
 - Storage: NFS

**Comment by baozi510** [comment]
me too

**Comment by baozi510** [comment]
me too
