### ISSUE TITLE
Roku experience not like other platforms 

### ISSUE THREAD

**Issue by sindizzy** [jellyfin/jellyfin#6313]
**Describe the bug**
Not sure if this is a bug or feature request. First, I have 2 Android TV devices, an Android phone, an Amazon Fire Tablet, a Roku stick, and a Roku TV. The Roku experience seems to be much different than other platforms. For Movies you don't get the headers Suggestions, Trailers, favorites, etc. Also the Music category responds with "This CollectionFolder contains no items". When I view my server on the web or with my Android or Fire tablet the music folder is enumerated,

**System (please complete the following information):**
I run my Jellyfin server on Windows 10 x64.

**To Reproduce**
Use a Roku device.

**Expected behavior**
A similar experience to other platforms.

**Comment by crobibero** [comment]
This isn’t a bug, but a request for Roku.

**Comment by sindizzy** [comment]
Ok so where would I put this then?
