### ISSUE TITLE
400 Bad Request when trying to group versions

### ISSUE THREAD

**Issue by RobCubed** [jellyfin/jellyfin#6317]
**Describe the bug**

**System (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS
 - Virtualization: N/A
 - Clients: Browser
 - Browser: Firefox 90, Ungoogled Chromium 87.0.4280.67
 - Jellyfin Version: 20210718.1-unstable
 - Playback: Transcode
 - Hardware Acceleration: None
 - Installed Plugins: None
 - Reverse Proxy: None
 - Base URL: None
 - Networking: NAT
 - Storage: Local

**To Reproduce**
1. Go to any library
2. Long click on one video/series
3. Select 2 or more videos
4. Select the "..."
5. Click "Group versions"
6. Infinite loading bar

Inspecting the network request that it sends, it shows that the /Videos/MergeVersions endpoint is returning a 400 Bad Request, despite it seeming valid, and the message "Please supply at least two videos to merge."

**Expected behavior**
(In terms of shows) the series to merge into one listing

**Server Logs**
None around doing this

**FFmpeg Logs**
None around doing this

**Browser Console Logs**
`POST http://[url]/Videos/MergeVersions?Ids=dfefc9911c4e290609c5a64e3e600095,27a87a348982e0943672f61f8d9633b0
[HTTP/1.1 400 Bad Request 198ms]`

`Uncaught (in promise) Response { type: "basic", url: "[url]/Videos/MergeVersions?Ids=dfefc9911c4e290609c5a64e3e600095%2C27a87a348982e0943672f61f8d9633b0", redirected: false, status: 400, ok: false, statusText: "Bad Request", headers: Headers, body: ReadableStream, bodyUsed: false }`

**Comment by ragekit** [comment]
I came to report that exact same bug also

**Comment by ragekit** [comment]
Probably Related : https://github.com/jellyfin/jellyfin/issues/3178

**Comment by jNullj** [comment]
Having the same bug: server runs on officeal docker, client is using latest google chrome for windows.
Server is behind a reverse proxy using apache

**Comment by cvium** [comment]
It's only really supported for movies afaik
