### ISSUE TITLE
LiveTV Channel Merge

### ISSUE THREAD

**Issue by meestark** [jellyfin/jellyfin#632]
Requesting a feature to handle channel merging for LiveTV

Use case for this would be multiple IPTV m3u playlists being fed into Jellyfin, but would combine the same channel into one channel (as opposed to showing duplicate channels as is the current status).  When all the connections are used up for the first playlist (2), then Jellyfin would instead choose the second playlist.

I have not tested, but apparently this may already work for HDHomeRun tuners, just not IPTV.

**Comment by meestark** [comment]
I'm not sure if this is client side per say though? Wouldn't jellyfin still need to have the error handling to know that:

- Channel X is available from three different tuners, A, B and C (each limited to 2 streams)
- Tuner A has both streams utilized, will now send connection to tuner B instead

**Comment by sparky8251** [comment]
Was thinking in terms of how the normal TV/Movie libraries can be grouped. For those, the only server side stuff is a is db entry that says "this user wants these grouped". Client handles changing the display so they look like one to you, the user.

If this isn't the way you'd want this to work, I'd agree. It should stay here.

**Comment by meestark** [comment]
I think there'd still have to be some logic server side to know when a tuner is full.

However, your thought leads me into another approach, which could be treating each tuner as a library, then choose to only share tuner A with user X, tuner B with user Y and so on

**Comment by Floflobel** [comment]
Indeed it could be a beginning that would group live TV. I am for this feature.

**Comment by jrote1** [comment]
Is there any plans to still add this feature? I think it would be very useful
