### ISSUE TITLE
Jellyfin won't start on Raspberry Pi 4

### ISSUE THREAD

**Issue by 1beb** [jellyfin/jellyfin#6331]
**Describe the bug**

Unable to start service.
```
sudo systemctl status jellyfin.service
● jellyfin.service - Jellyfin Media Server
   Loaded: loaded (/lib/systemd/system/jellyfin.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/jellyfin.service.d
           └─jellyfin.service.conf
   Active: failed (Result: signal) since Wed 2021-07-21 04:06:16 EDT; 14s ago
  Process: 4470 ExecStart=/usr/bin/jellyfin ${JELLYFIN_WEB_OPT} ${JELLYFIN_RESTART_OPT} ${JELLYFIN_FFMPEG_OPT} ${JELLYFIN_SERVIC
 Main PID: 4470 (code=killed, signal=ABRT)

Jul 21 04:06:16 raspberrypi systemd[1]: jellyfin.service: Service RestartSec=100ms expired, scheduling restart.
Jul 21 04:06:16 raspberrypi systemd[1]: jellyfin.service: Scheduled restart job, restart counter is at 5.
Jul 21 04:06:16 raspberrypi systemd[1]: Stopped Jellyfin Media Server.
Jul 21 04:06:16 raspberrypi systemd[1]: jellyfin.service: Start request repeated too quickly.
Jul 21 04:06:16 raspberrypi systemd[1]: jellyfin.service: Failed with result 'signal'.
Jul 21 04:06:16 raspberrypi systemd[1]: Failed to start Jellyfin Media Server.
```

**System (please complete the following information):**

Raspberry Pi, with Raspbian

**To Reproduce**

No idea. It just happened.

**Expected behavior**

Starts

**Server Logs**

You can see these with: 

```
$ journalctl -n10 -f
Jul 21 04:11:17 raspberrypi systemd[1]: jellyfin.service: Main process exited, code=killed, status=6/ABRT
Jul 21 04:11:17 raspberrypi systemd[1]: jellyfin.service: Failed with result 'signal'.
Jul 21 04:11:17 raspberrypi systemd[1]: jellyfin.service: Service RestartSec=100ms expired, scheduling restart.
Jul 21 04:11:17 raspberrypi systemd[1]: jellyfin.service: Scheduled restart job, restart counter is at 1.
Jul 21 04:11:17 raspberrypi systemd[1]: Stopped Jellyfin Media Server.
Jul 21 04:11:17 raspberrypi systemd[1]: Started Jellyfin Media Server.
Jul 21 04:11:18 raspberrypi jellyfin[6444]: Unhandled Exception
Jul 21 04:11:18 raspberrypi jellyfin[6444]: System.UnauthorizedAccessException: Access to the path '/var/log/jellyfin' is denied.
Jul 21 04:11:18 raspberrypi jellyfin[6444]:  ---> System.IO.IOException: Permission denied
Jul 21 04:11:18 raspberrypi jellyfin[6444]:    --- End of inner exception stack trace ---
Jul 21 04:11:18 raspberrypi jellyfin[6444]:    at System.IO.FileSystem.CreateDirectory(String fullPath)
Jul 21 04:11:18 raspberrypi jellyfin[6444]:    at System.IO.Directory.CreateDirectory(String path)
Jul 21 04:11:18 raspberrypi jellyfin[6444]:    at Jellyfin.Server.Program.CreateApplicationPaths(StartupOptions options)
Jul 21 04:11:18 raspberrypi jellyfin[6444]:    at Jellyfin.Server.Program.StartApp(StartupOptions options)
Jul 21 04:11:18 raspberrypi jellyfin[6444]:    at Jellyfin.Server.Program.<Main>(String[] args)
```

**Solution**

It appears that somehow the `/var/logs/jellyfin` folder on my Pi was deleted, or perhaps not being created appropriately. 

1. Create the folder: 

```
$ sudo mkdir /var/log/jellyfin
```

2. Set jellyfin as owner (otherwise you'll get a different permission error)

```
$ sudo chown -R jellyfin /var/log/jellyfin 
```

3. Restart jellyfin

```
$ sudo systemctl restart jellyfin.service
```

**Comment by 1beb** [comment]
Creating this for future searchers.

**Comment by michael9dk** [comment]
Same issue when these folders are missing:

/var/lib/jellyfin/metadata
/var/cache/jellyfin

Jelllyfin should revert to the default setting and restore the missing folder.


@1beb Please open this bug again.

**Comment by mrfoxie** [comment]
> **Describe the bug**
> 
> Unable to start service.
> 
> ```
> sudo systemctl status jellyfin.service
> ● jellyfin.service - Jellyfin Media Server
>    Loaded: loaded (/lib/systemd/system/jellyfin.service; enabled; vendor preset: enabled)
>   Drop-In: /etc/systemd/system/jellyfin.service.d
>            └─jellyfin.service.conf
>    Active: failed (Result: signal) since Wed 2021-07-21 04:06:16 EDT; 14s ago
>   Process: 4470 ExecStart=/usr/bin/jellyfin ${JELLYFIN_WEB_OPT} ${JELLYFIN_RESTART_OPT} ${JELLYFIN_FFMPEG_OPT} ${JELLYFIN_SERVIC
>  Main PID: 4470 (code=killed, signal=ABRT)
> 
> Jul 21 04:06:16 raspberrypi systemd[1]: jellyfin.service: Service RestartSec=100ms expired, scheduling restart.
> Jul 21 04:06:16 raspberrypi systemd[1]: jellyfin.service: Scheduled restart job, restart counter is at 5.
> Jul 21 04:06:16 raspberrypi systemd[1]: Stopped Jellyfin Media Server.
> Jul 21 04:06:16 raspberrypi systemd[1]: jellyfin.service: Start request repeated too quickly.
> Jul 21 04:06:16 raspberrypi systemd[1]: jellyfin.service: Failed with result 'signal'.
> Jul 21 04:06:16 raspberrypi systemd[1]: Failed to start Jellyfin Media Server.
> ```
> 
> **System (please complete the following information):**
> 
> Raspberry Pi, with Raspbian
> 
> **To Reproduce**
> 
> No idea. It just happened.
> 
> **Expected behavior**
> 
> Starts
> 
> **Server Logs**
> 
> You can see these with:
> 
> ```
> $ journalctl -n10 -f
> Jul 21 04:11:17 raspberrypi systemd[1]: jellyfin.service: Main process exited, code=killed, status=6/ABRT
> Jul 21 04:11:17 raspberrypi systemd[1]: jellyfin.service: Failed with result 'signal'.
> Jul 21 04:11:17 raspberrypi systemd[1]: jellyfin.service: Service RestartSec=100ms expired, scheduling restart.
> Jul 21 04:11:17 raspberrypi systemd[1]: jellyfin.service: Scheduled restart job, restart counter is at 1.
> Jul 21 04:11:17 raspberrypi systemd[1]: Stopped Jellyfin Media Server.
> Jul 21 04:11:17 raspberrypi systemd[1]: Started Jellyfin Media Server.
> Jul 21 04:11:18 raspberrypi jellyfin[6444]: Unhandled Exception
> Jul 21 04:11:18 raspberrypi jellyfin[6444]: System.UnauthorizedAccessException: Access to the path '/var/log/jellyfin' is denied.
> Jul 21 04:11:18 raspberrypi jellyfin[6444]:  ---> System.IO.IOException: Permission denied
> Jul 21 04:11:18 raspberrypi jellyfin[6444]:    --- End of inner exception stack trace ---
> Jul 21 04:11:18 raspberrypi jellyfin[6444]:    at System.IO.FileSystem.CreateDirectory(String fullPath)
> Jul 21 04:11:18 raspberrypi jellyfin[6444]:    at System.IO.Directory.CreateDirectory(String path)
> Jul 21 04:11:18 raspberrypi jellyfin[6444]:    at Jellyfin.Server.Program.CreateApplicationPaths(StartupOptions options)
> Jul 21 04:11:18 raspberrypi jellyfin[6444]:    at Jellyfin.Server.Program.StartApp(StartupOptions options)
> Jul 21 04:11:18 raspberrypi jellyfin[6444]:    at Jellyfin.Server.Program.<Main>(String[] args)
> ```
> 
> **Solution**
> 
> It appears that somehow the `/var/logs/jellyfin` folder on my Pi was deleted, or perhaps not being created appropriately.
> 
> 1. Create the folder:
> 
> ```
> $ sudo mkdir /var/log/jellyfin
> ```
> 
> 2. Set jellyfin as owner (otherwise you'll get a different permission error)
> 
> ```
> $ sudo chown -R jellyfin /var/log/jellyfin 
> ```
> 
> 3. Restart jellyfin
> 
> ```
> $ sudo systemctl restart jellyfin.service
> ```

Thank bro this really helped me to run it on raspberry pi 4

**Comment by 1beb** [comment]
> Same issue when these folders are missing:
> 
> /var/lib/jellyfin/metadata /var/cache/jellyfin
> 
> Jelllyfin should revert to the default setting and restore the missing folder.
> 
> @1beb Please open this bug again.

I wrote this issue as a PSA. I'm not sure if it's a bug or rather something that I did. I think the experimental way in which an Rpi is often used and my inability to recreate this error make it more likely that the problem was between the keyboard and the chair :)

**Comment by michael9dk** [comment]
I deleted those folders intentionally (to verify correct detection of my library). And can reproduce the error.

**Comment by otac0n** [comment]
Similar behavior if files (.xml OR .json) are zero-length:

https://forum.jellyfin.org/t-solved-service-failed-to-start
