### ISSUE TITLE
mesa-va-drivers outdated in docker image

### ISSUE THREAD

**Issue by MayeulC** [jellyfin/jellyfin#6332]
### Bug Description
mesa-va-drivers in the docker image is from debian buster.

It's quite outdated ([18.3](https://packages.debian.org/buster/mesa-va-drivers)) and lacks several features, [among which HEVC support for AMD GPUs](https://jellyfin.org/docs/general/administration/hardware-acceleration.html#vaapi)

I suggest to use a bullseye backport. Unfortunately, mesa was not oficially backported, but I rolled my own, and it works very well.

libllvm11 is needed as a dependency, but it is in official backports. All in all, the packages that require backporting are: `libdrm2 libdrm-amdgpu1 libdrm-common mesa-va-drivers`

### Suggested fix
Multiple ways:
* wait for bullseye to release, which should happen soon. As a downside, expect history to repeat itself in a few months
* base the jellyfin image off something else such as alpine, which provides more timely updates for that kind of packages. Debian provides little added value when using containers, anyway.
* maintain a mesa backport and include it in the base image

For those who are desperate to get this working at all costs, here are the deb files: 
[backports-mesa20.3-buster.zip](https://github.com/jellyfin/jellyfin/files/6856269/backports-mesa20.3-buster.zip)

I wouldn't personally trust a random person on the internet with packages like these, but once extracted, you can install them with `dpkg -i *.deb`. You will also need to enable backports in /etc/apt/sources.list, then install libllvm11. HEVC transcoding should work right away.

If you want to compile those yourself, you will need to backport `mesa`, `libdrm` and possibly `libva` and `libglvnd` as dependencies.

### Additional info

**System (please complete the following information):**
 - OS: Debian Buster (with mesa backports)
 - Virtualization: Docker jellyfin/jellyfin:latest (896141b3cd3a)
 - Clients: Browser
 - Jellyfin Version: 10.7.6
 - Playback: transcode
 - Hardware Acceleration: VAAPI
 
The rest is a bit irrelevant

**To Reproduce**
1. Setup jellyfin/jellyfin:latest
2. Get a recent AMD GPU
3. Try enabling HW decoding of h.265 in the settings.
4. Play some h.265 media with transcoding enabled
5. Transcoding fails. It also fails when running the command manually

**Expected behavior**
Transcoding should work out-of-the-box

**Server Logs**
```
[INF] [5] Jellyfin.Api.Helpers.TranscodingJobHelper: /usr/lib/jellyfin-ffmpeg/ffmpeg -hwaccel vaapi -hwaccel_output_format vaapi -vaapi_device [[[snip]]]
[ERR] [18] Jellyfin.Api.Helpers.TranscodingJobHelper: FFmpeg exited with code 1
```

**FFmpeg Logs**
```
# docker exec  -it jellyfin bash
I have no name!@server:/$ /usr/lib/jellyfin-ffmpeg/ffmpeg -hwaccel vaapi -hwaccel_output_format vaapi -vaapi_device /dev/dri/renderD128 -i file:"/media/HEVC.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:2 -map -0:s -codec:v:0 h264_vaapi -b:v 7304275 -maxrate 7304275 -bufs
ize 14608550 -profile:v:0 high -level 41  -force_key_frames:0 "expr:gte(t,0+n_forced*3)" -vf "format=nv12|vaapi,hwupload,scale_vaapi=format=nv12" -start_at_zero -vsync -1 -codec:a:0 aac -ac 2 -ab 139318 -copyt
s -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/tmp/a.ts" -hls_playlist_type vod -hls_list_size 0 -y "/tmp/a.m3u8"
ffmpeg version 4.3.2-Jellyfin Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-gpl --enabl
e-version3 --enable-static --enable-libfontconfig --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libmp3lam
e --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --arch=amd64 --enable-opencl --en
able-vaapi --enable-amf --enable-libmfx --enable-vdpau --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvenc --enable-nvdec --enable-ffnvcodec
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[[[snip]]]
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (native) -> h264 (h264_vaapi))
  Stream #0:2 -> #0:1 (aac (native) -> aac (native))
Press [q] to stop, [?] for help
[Parsed_scale_vaapi_2 @ 0x56103b410a80] Failed to render parameter buffer: 6 (invalid VASurfaceID).
Error while filtering: Input/output error
Failed to inject frame into filter network: Input/output error
Error while processing the decoded data for stream #0:0
[aac @ 0x56103adc72c0] Qavg: 65536.000
[aac @ 0x56103adc72c0] 2 frames left in the queue on closing
Conversion failed!
```

**Additional context**
I believe this is strongly related, if not the cause, of the following issues:

https://github.com/jellyfin/jellyfin/issues/2473 
https://github.com/jellyfin/jellyfin/issues/3580
https://github.com/jellyfin/jellyfin/issues/5647
https://github.com/jellyfin/jellyfin/issues/4066
https://github.com/jellyfin/jellyfin/issues/2787
https://github.com/jellyfin/jellyfin/issues/3463
https://github.com/jellyfin/jellyfin/issues/4119

**Comment by crobibero** [comment]
This is fixed in unstable, we now use `bullseye` as the base image.

**Comment by MayeulC** [comment]
Now that mesa is available in backports, you can simply execute the following after starting the docker image:

```
echo "deb http://deb.debian.org/debian buster-backports main" >> /etc/apt/sources.list
apt update
apt install -y mesa-va-drivers/buster-backports
```

It might be worth doing in the official stable image.
