### ISSUE TITLE
The movie will be lost after scanning the media library. This is a serious problem that can be reproduced

### ISSUE THREAD

**Issue by wangdlhebei** [jellyfin/jellyfin#6337]
When there is **a movie** file and **several folders** in a folder, the folder will be scanned as a movie folder, and the contents will not be visible or scanned

**Comment by T-bond** [comment]
Maybe filling out the template would help, as I don't have the issue mentioned here. This report in this form is almost totally useless.

**Comment by wangdlhebei** [comment]
> Maybe filling out the template would help, as I don't have the issue mentioned here. This report in this form is almost totally useless.

![image](https://user-images.githubusercontent.com/44386804/127793996-27bd011d-a6fa-4e5f-b719-ae8d95471fa0.png)
I found that there is a problem here. When a movie, it will be presented as a folder，Then I added the judgment condition in the red box

**Comment by srcrist** [comment]
Closing this issue as it does not reference and apparent Jellyfin bug. Please follow the naming and organization conventions documented at https://jellyfin.org/docs/general/server/media/movies/, and feel free to visit our support communities on the forums and the Matrix/Discord server for additional help resolving scanning and matching issues.
