### ISSUE TITLE
Remote access re-enable after initial set up

### ISSUE THREAD

**Issue by Horuyuki** [jellyfin/jellyfin#6341]
Installed Jellyfin on ubuntu 20.04 via apt.

I unchecked the allow remote connections when I was configuring jellyfin initially at the first visit.

It is running behind a reverse proxy on a remote VPS.

Now I can't connect to the server because of that. What should I edit via ssh in order to regain remote access?

**Comment by crobibero** [comment]
This isn’t a bug, but was an issue fixed with 10.7.
In networking.xml there should be a key “EnableRemoteAccess”

**Comment by Horuyuki** [comment]
> This isn’t a bug, but was an issue fixed with 10.7.
> In networking.xml there should be a key “EnableRemoteAccess”

Sorry but I think I made another mistake, deleted the jellyfin dir under .config. How can I get it back?

**Comment by Horuyuki** [comment]
Ok, you can just run the `jellyfin` command to get things set up again. Or also delete the folder in `.local/share/jellyfin` and then restart the service.
