### ISSUE TITLE
Real time monitoring not picking up new media in 10.7.6 docker

### ISSUE THREAD

**Issue by absolution1** [jellyfin/jellyfin#6353]
**Describe the bug**
My jellyfin setup is not detecting new media added to the watched directories, despite 'Enable Real time monitoring' being ticked.

**System (please complete the following information):**
 - OS: Host OS is ubuntu server 20.04 running docker.
 - Virtualization: Docker, specifically running linuxserver/jellyfin:bionic-version-10.7.6-1
 - Clients: Various, but unrelated
 - Browser: Safari, but unrelated
 - Jellyfin Version: 10.7.6 linuxserver.io container
 - Playback: N/A
 - Hardware N/A
 - Installed Plugins: AudioDB, Kodi Sync Queue, MusicBrainz, OMDb
 - Reverse Proxy: Caddy
 - Base URL: None
 - Networking: Docker handles networking.  Host server connected via wire to home network
 - Storage: BTRFS formatted hard drives directly connected by SATA to the host system.  Directories are exposed to the container via ` --mount type=bind,source=/mnt/fdrive/entertainment,target=/media2,readonly \`.  The watched directories ('tv' and 'movies') are two separate btrfs subvolumes.

**To Reproduce**
Configure server as above.  Add media to a watched directory.  See that no media is added to the library unless manually scanned.

**Expected behavior**
Added media should be added (almost) instantly to the jellyfin library

**Server Logs**
NA

**FFmpeg Logs**
NA

**Browser Console Logs**
NA

**Screenshots**
NA

**Additional context**
I've increased the inotify water limit on the host.
I've installed `inotify-tools` in the jellyfin container but this did not help.

--Thanks in advance for any help!  And, x1000 thanks for developing Jellyfin.--

**Comment by codeghari** [comment]
Have the same issue. I'm on the official docker container and my server is using CIFS mounted on the host and then bind to the jellyfin container. Worked on the previous iterations of Jellyfin but seems to have stopped working on 10.7.6. Usually after a new file is in the library it is picked up within a minute or two. Now only a media scan will get the file visible.

**Comment by jvoinot** [comment]
I don't know if it is associated, but i found this error log:

[2021-10-14 18:51:39.841 +02:00] [ERR] [187] Emby.Server.Implementations.IO.LibraryMonitor: Error in Directory watcher for: "/data/tvshows"
System.IO.IOException: The configured user limit (8192) on the number of inotify watches has been reached, or the operating system failed to allocate a required resource.
[2021-10-14 18:51:41.185 +02:00] [INF] [187] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "/data/tvshows"

**Comment by cvium** [comment]
@jvoinot It's very related. Without enough notify watches it won't pick up any changes. It needs 1 watcher per file

**Comment by absolution1** [comment]
To update this bug, I've noticed that the media is eventually added to the library but it takes quite a long time.  I haven't timed it but its on the timescale of hours.  It is way longer than how quickly the monitoring picked up the media on my old windows install of jellyfin.

**Comment by Akirainblack** [comment]
sudo su
echo fs.inotify.max_user_watches=1048576 | tee -a /etc/sysctl.conf && sysctl -p /etc/sysctl.conf
Should fix this on a Synology (has to be run after EVERY reboot) also, historically:
echo fs.inotify.max_user_watches=1048576 | sudo tee -a /etc/sysctl.conf && sysctl -p /etc/sysctl.conf
used to work, however has stopped working since an update from Synology.

**Comment by Bond-009** [comment]
Closing this as the media is getting picked up, we have other issues tracking slow scan speeds.

**Comment by alessandro-vitali** [comment]
Hi, we've had pretty much the same issue on a [new bug report](https://github.com/jellyfin/jellyfin/issues/1690) (also using Synology's DSM). 

@Akirainblack what is the difference between your approach and the one of @jvoinot ? When I run your command through SSH on my Synology, I just get permission denied to /etc/sysctl.conf (which I don't completely understand, as I'm using sudo) However, just using echo to append the higher value to /proc/sys/fs/inotify/max_user_instances should be enough, right? Are you changing /etc/sysctl.conf and why?
