### ISSUE TITLE
LiveTV's now showing does not offer tuning to the show.

### ISSUE THREAD

**Issue by madscientist42** [jellyfin/jellyfin#6359]
It's a bit less than useful to just allow you to play (tune) the LiveTV over to  the channel from just the schedule and the channels list.  The obvious thing is to be able to do more than schedule or start a recording off of the on-the-air-now list of shows presented.  It should be able to (Can't fully remember if it did or not...but...I know that the Android client _**explicitly**_ offers the ability, which is now broken...) even if it never did it.  If it didn't use to do this, this should be converted over to a feature request instead.

 - OS: Linux
 - Virtualization: None
 - Clients: Tried with Android, Roku, and Browser.
 - Browser: Version 91.0.4472.101 of Chromium and 90.0.2 (64-bit) of Firefox on Mint 19
 - Jellyfin Version: 10.0.7
 - Playback: Doesn't matter
 - Hardware Acceleration: N/A
 - Installed Plugins: None.
 - Reverse Proxy: None
 - Base URL: None
 - Networking: Host
 - Storage: Local

To reproduce: Try playing (tuning) the current LiveTV shows from the screen list on any client.  It fails on Android and Roku, no option to play is provided for the Browsers.

Expected behavior: Tuning to the show in question on the channel it resides on when clicked to on the Appliance clients, and tuning to being offered on the show info screen.

**Comment by HybridSarcasm** [comment]
This has been open quite a while. Can this be re-produced with the current build? If so, please update the bug report details. Thanks!

**Comment by srcrist** [comment]
Closing this issue as it does not reference an apparent Jellyfin server bug. If you believe this is a feature you'd like to request, please submit it at features.jellyfin.org, and if you believe that it's a bug in the functionality of the client, please submit an issue to the repository for the relevant clients. It sounds to me like this is mostly a request for better functionality, so probably a feature request.

**Comment by madscientist42** [comment]
I'd forgotten that I'd even FILED this.  An Upgrade to a later version of JF seems to have fixed the issue out of box.

**Comment by madscientist42** [comment]
(So closing it very much was the right call there...  X-D)

**Comment by srcrist** [comment]
No worries. We're just doing housekeeping and trying to clean up old and stale issues that remain open in the repo. Let us know if you have any other issues.

**Comment by madscientist42** [comment]
Been happy for a bit since the update cleared the use cases I had for
things.  :D   Will chime in as needed.  The work's appreciated...it gives
the house TV, "superpowers," at this point and I'm setting up other family
members with the same magic.

Figured this was housecleaning...  Just wanted to assure you I'd not seen
the request for more info, but that it appears to have been fully fixed
with later versions.
