### ISSUE TITLE
Subfolder not displayed 

### ISSUE THREAD

**Issue by fangjzh** [jellyfin/jellyfin#6361]
**Describe the bug**

When there is one video and one subfolder in a folder, the entire folder will be recognised as a video, videos and pictures in the subfolder will not displayed. When I add a new picture to this folder, files in the subfolder will be detected and displayed.

**System (please complete the following information):**
 - OS: Windows 10
 - Virtualization: None
 - Clients: Browser
 - Browser: Firefox and Chrome
 - Jellyfin Version: 10.7.0

**Comment by wangdlhebei** [comment]
https://github.com/jellyfin/jellyfin/issues/6337

**Comment by srcrist** [comment]
Closing this issue as it does not reference an apparent Jellyfin bug. Please follow the naming and organization conventions documented at https://jellyfin.org/docs/general/server/media/movies/, and feel free to visit our support communities on the forums and the Matrix/Discord server for additional help resolving scanning and matching issues.
