### ISSUE TITLE
Jellyfin fails to install / start

### ISSUE THREAD

**Issue by ghost** [jellyfin/jellyfin#6362]
**Describe the bug**
Following the standard guide for [Ubuntu ](https://jellyfin.org/docs/general/administration/installing.html#ubuntu), fails to properly install and run. Missing Environment file?

**System (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS /  20.04 / focal
 - Virtualization: none
 - Clients: n/a
 - Browser: n/a
 - Jellyfin Version: 10.7.6
 - Playback: n/a 
 - Hardware Acceleration: n/a
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: none
 - Networking: NAT
 - Storage: local
 - 
**To Reproduce**

1. follow: https://jellyfin.org/docs/general/administration/installing.html#ubuntu
2. step 7 `sudo systemctl restart jellyfin` fails.

**Expected behavior**

Install to complete and run without issues, or indication of how to fix issue(s)

**Server Logs**
see attached for install logs

**FFmpeg Logs**
n/a

**Browser Console Logs**
n/a

**Screenshots**
n/a

**Additional context**
```
root@:/etc/systemd/system/jellyfin.service.d# ls -al
total 8
drwxr-xr-x  2 root root 4096 Jul 29 11:25 .
drwxr-xr-x 23 root root 4096 Jul 29 11:39 ..
root@:/etc/systemd/system/jellyfin.service.d#
```

`/etc/systemd/system/multi-user.target.wants/jellyfin.service`
> [Unit]
> Description = Jellyfin Media Server
> After = network.target
> 
> [Service]
> Type = simple
> EnvironmentFile = /etc/default/jellyfin
> User = jellyfin
> ExecStart = /usr/bin/jellyfin ${JELLYFIN_WEB_OPT} ${JELLYFIN_RESTART_OPT} ${JELLYFIN_FFMPEG_>
> Restart = on-failure
> TimeoutSec = 15
> 
> [Install]
> WantedBy = multi-user.target

```
root@:/etc/default# ls /etc/default/jellyfin*
ls: cannot access '/etc/default/jellyfin*': No such file or directory
root@:/etc/default#
```

[Jellyfin-6362-InstallLog.txt](https://github.com/jellyfin/jellyfin/files/6900342/Jellyfin-6362-InstallLog.txt)

**Comment by sevenrats** [comment]
Can't reproduce. Please open a new issue if you still experience this.
