### ISSUE TITLE
Images not showing for migrated library

### ISSUE THREAD

**Issue by CubeyGlyph** [jellyfin/jellyfin#6365]
Describe the bug
Images will not show for TV shows or their seasons.

To Reproduce
I migrated my library to different physical drives. Initially I took the existing library and pointed it at the new location and the images no longer displayed. I deleted the old library and created a new one and scanned that new location. It still has no images. I have migrated other libraries and did not get this issue.

Expected behavior
Images should be available

Screenshots
![Screen Shot 2021-07-30 at 11 59 14 AM](https://user-images.githubusercontent.com/82244912/127680006-174127f0-9373-4aca-8018-33ad40906df0.png)
![Screen Shot 2021-07-30 at 12 00 39 PM](https://user-images.githubusercontent.com/82244912/127680118-adb42801-35fb-4bff-b4e5-fb62787b199d.png)

**Comment by CubeyGlyph** [comment]
> What are your library's settings in relation to metadata providers? Are there any errors in the logs when you run a scan?

Metadata downloaders set in the library are AniSearch, AniList, AniDB, TheTVDB, and TVmaze.  Then they are ranked and ordered by priority.  Set to never automatically (but I would expect manual should update it).  Image fetchers all turned on and settings configured to pull all image types. Saving artwork into media folders.  Looking into logs will post...

**Comment by CubeyGlyph** [comment]
It appears that some recent update has partially fixed this, I am suddenly able to pull images from some sources, but not all, and it sometimes selects the image on scan and sometimes does not.
<img width="1115" alt="2021-09-16_09-23-01" src="https://user-images.githubusercontent.com/82244912/133620091-e79d8b58-4638-44f8-a7cd-af527949da6c.png">

**Comment by HybridSarcasm** [comment]
This has been open quite a while. Can this be re-produced with the current build? If so, please update the bug report details. Thanks!

**Comment by Bond-009** [comment]
Closing as stale
