### ISSUE TITLE
Have a more robust default name parser

### ISSUE THREAD

**Issue by sushilicious** [jellyfin/jellyfin#6382]
Ingoring [...] at the beginning of a file/directory name. I know I'm not conforming to the naming standard presented, but having this extra rule would make the default name parsing significantly better for anime and asian shows. For a lot of anime, it is fairly common to have the name of the subtitling group at the beginning of the name (e.g., "[HorribleSubs] Made in Abyss - 12 [720p].mkv"). For many asian shows, it is also common to have the broadcasting group at the beginning of the file name (e.g.,  "[tvN] 연애말고 결혼 E01~E16 END HDTV.H264.720p"). Just being able to handle [...] at the beginning of the file/directory name would make at least 50% of the unrecognized items in my library recognized by the default parser.

More generally, I think the name parsing could use an overhaul. To get the name of a series/object, the majority of the library and plugins call `LibraryManager.ParseName`. This hands it over to `VideoResolver`, which in turn cleans with `CleanStringParser`. The cleaning done by this parser is fairly simplistic and employs a giant regex with an incomplete set of stop words. For example, 'blu-ray' is included but 'Blu-ray' is not. To make this a little better, I propose one or both of the following.

1. Instead of `ParseName` returning a single parsed name, have it return a list of parsed names in decreasing confidence order (possibly with the confidence scores). This way, we are not committed to a single title. For example, in many cases we would like to remove the numbers at the end of a name (e.g., "BNA Brand New Animal 01-06") because they refer to episode numbers, but some movies/shows legitimately have \<number\>-\<number\> in their title (e.g., "Sa 204-272"). So, it would make sense for `ParseName` to return both the name with and without the number. Many plugins already effectively do this; they try searching one title, and if it doesn't work, they modify it a little and try again. This change would just centralize those efforts.

2. Make the name parsing pluggable. Make an `INameParser` interface and try these parsers in turn in `ParseName`. This would allow people to use 3rd-party name parsers which are fairly good (e.g., [guessit](https://github.com/guessit-io/guessit)). Someone could even build a plugin which would allow the user to specify their own custom formatting for their media. This also has the added effect of addressing issues like #6255, since we would be able to create different parsers for different media.

I actually already have some code written for the 2nd proposal if you guys are interested.

In both cases, a parser which adheres to the syntax given in the manual can be run first to ensure proper parsing.

In the case that both proposals seem unappealing, I suggest that the default parser be significantly updated to handle a wider range of formats. There's just something nice about turning on a system and having it automatically recognize all your files.

**Comment by info-path** [comment]
I also found out today that there is a problem with parsing filenames. Scanning the library ignores files that have the same name at the beginning. Here is an example where a file with a longer name is not found: 

```
2020.01 - some-name-of-file.mp4
2020.01 - some-name-of-file-cut-scenes.mp4
```

Jellyfin version: 10.7.6

**Comment by srcrist** [comment]
Closing this issue as it does not reference a Jellyfin server bug. Jellyfin requires the use of the naming and organization conventions documented here: https://jellyfin.org/docs/general/server/media/shows. Deviations from these conventions are handled on a best-effort basis and cannot be supported. If you would like to make a feature request for additional parsing functionality, please do so at features.jellyfin.org. Also, feel free to visit our support communities on the forums or the Matrix/Discord server for help troubleshooting scanning and matching issues.
