### ISSUE TITLE
Plan to Upgrade to .NET 6

### ISSUE THREAD

**Issue by richlander** [jellyfin/jellyfin#6385]
If you read my [.NET blog posts](https://devblogs.microsoft.com/dotnet/announcing-net-6-preview-6/), you'll know that we will soon we releasing .NET 6 (November 2021) and .NET 5 will go EOL soonish after (May, 2022). It addition, .NET 6 RC1 will be a Go-Live release, meaning that RC1 (and after) is a high confidence release and supported in production.

I'm naturally biased. I'd suggest moving to .NET 6 sooner than later. Perhaps it makes sense to switch to .NET 6 in containers first since that's a more isolated scenario.

I don't know Jellyfin well enough to suggest which features make sense to adopt first, to take advantage of the new release. It might depend on the distribution type. For example, I'm going to suggest adopting ready-to-run compilation in (at least) the container images you ship. It appears that this feature improves startup time by ~1.5s from my testing.

Somewhat separately, .NET 6 Debian container images are based off of Bullseye instead of Buster (what you are using now). You could consider moving to Bullseye at the same time.

Anyone interested in targeting the RC1 release (when it comes)? Certainly, if Jellyfin adopted RC1 or RC2, I'd want to talk about the project in the .NET 6 final release blog post to draw attention to an early adopter.

What are your thoughts on moving to .NET 6?

**Comment by dkanada** [comment]
If I recall correctly, we switched to .NET 5 extremely fast, so I don't think there will be any pushback from another quick update to the .NET 6 release candidates. Just for reference, what does .NET 6 support look like on Ubuntu?

**Comment by crobibero** [comment]
We’re eager to move to .NET 6, we even have a branch where @Bond-009 was playing with the upgrade

https://github.com/jellyfin/jellyfin/tree/dotnet6

I believe we decided against ready to run as it increases the compiled size for a minimal startup increase- and since this is a server application we don’t expect the server to be restarted regularly. I could be remembering incorrectly, but that’s what I remember the response being last time I brought up ready to run.

It would be interesting to move to .NET 6 for release 10.8, but I’m not sure when our next release is scheduled for

**Comment by richlander** [comment]
Cool. That sounds great.

I can get you the size increase. We could also push that out a little. We have a new [PGO](https://devblogs.microsoft.com/dotnet/conversation-about-pgo/) tech that can be used to significantly reduce the size of crossgen code.

I just took a quick look at that branch. I'd start more simply (as I have done for my perf testing) by just upgrading Jellyfin.Server to .NET 6. That's all that is technically required (unless you have other separate processes I haven't found).

For Ubuntu, we support all the in-support Ubuntu releases. We also still support 16.04 even though it is now in extended support. I assume that covers the bases.

If the master branch is intended for a release after September (when RC1 will ship), I'd suggest moving to .NET 6 now.

**Comment by cvium** [comment]
Fixed by #6590

**Comment by richlander** [comment]
Woohoo!
