### ISSUE TITLE
NormalizationForm

### ISSUE THREAD

**Issue by sushilicious** [jellyfin/jellyfin#6393]
**Describe the bug**
`NormalizationForm.FormKD` is messing up korean titles with utf8.

**System (please complete the following information):**
 - OS: Archlinux and also on Debian
 - Virtualization: Docker and bare-metal
 - Clients: Browser
 - Browser: Firefox 91.0b
 - Jellyfin Version: master (commit 2521a13d7d8df3bfa5291386ba4389469f02ade8)
 - Playback: N/A
 - Hardware Acceleration: none
 - Installed Plugins: Anime, TVDB
 - Reverse Proxy: none
 - Base URL: none
 - Networking: Host
 - Storage: Local mounted and docker-mounted

**To Reproduce**
1. Add Korean files encoded in utf8.
2. Scan using one of the plugins using `FormKD`, (e.g., AniDB, TVDB)
3. Watch as logs send a very strangely encoded query.

**Expected behavior**
I expect to see a query encoded in utf8.

**Server Logs**
[2021-08-03 13:43:49.311 -07:00] [ERR] [29] Jellyfin.Plugin.Tvdb.Providers.TvdbSeriesProvider: No series results found for "운명처럼 널 사랑해"
(Supposed to be "운명처럼 널 사랑해")

[2021-08-03 13:44:18.087 -07:00] [ERR] [42] Jellyfin.Plugin.Tvdb.Providers.TvdbSeriesProvider: No series results found for "애타는 로맨스"
(Supposed to be "애타는 로맨스")

**FFmpeg Logs**
n/a

**Browser Console Logs**
n/a

**Screenshots**
n/a

**Additional context**
I've already added this as an issue to the tvdb plugin (jellyfin/jellyfin-plugin-tvdb#44), but this seems to many other plugins, so I'm creating another issue here.

Is there a reason why `NormalizationForm.FormKD` is used as opposed to something like `NormalizationForm.FormC`?

I'm asking because said normalization form is screwing up korean video titles encoded in utf8 (i.e., it works if I change it `FormC`). Are there any languages that depend on it? If so, I'll add a special case for korean, if not I'll add a pull request just changing it to `FormC`.

Perhaps jellyfin should provide a normalization API (e.g., handle encoding, remove "the"), so that issues like this can be changed managed in one location?

**Comment by crobibero** [comment]
Just for my understanding- the output is the following, where the top line is current output, and bottom line is correct output? Firefox renders them both as the second line, but pasting them into notepad++ provides this result.
![image](https://user-images.githubusercontent.com/24963659/128600921-3a0faff2-a59a-4901-a95d-e18048cae6c0.png)

**Comment by sushilicious** [comment]
That is correct.

I believe the top is using a unicode block for Korean that's been deprecated for a while now, so many websites don't recognize it.

**Comment by crobibero** [comment]
Just as an update- I've gone through the plugins that we provide and have created PRs to update the NormalizationForm
