### ISSUE TITLE
not working docker rpi4

### ISSUE THREAD

**Issue by sgb999** [jellyfin/jellyfin#6399]
**Describe the bug**

**System (please complete the following information):**
 - OS: Raspbian 32-bit
 - Virtualization: Docker
 - Clients: any
 - Browser: Firefox
 - Jellyfin Version: 10.7.6-1
 - Playback: N/A
 - Hardware Acceleration: N/A
 - Installed Plugins: [N/A
 - Reverse Proxy: [none
 - Base URL: 192.168.0.2:8096
 - Networking: Bridge
 - Storage: local

**To Reproduce**

1. pull docker image docker pull linuxserver/jellyfin (arm7 package)
2. expose ports 8096, 7359, 1900 (7359 and 1900 are udp)
3. Create 5 volumes for config, movies, tv, music and videos
4. Set env variables, GUID and PUID to 1000 (for my specific user), TZ Europe/London

**Expected behavior**
The webpage should load

**Server Logs**
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
[s6-init] ensuring user provided files have correct perms...exited 0.,
[fix-attrs.d] applying ownership & permissions fixes...,
[fix-attrs.d] done.,
[cont-init.d] executing container initialization scripts...,
[cont-init.d] 01-envfile: executing... ,
[cont-init.d] 01-envfile: exited 0.,
[cont-init.d] 10-adduser: executing... ,
,
-------------------------------------,
          _         (),
         | |  ___   _    __,
         | | / __| | |  /  \,
         | | \__ \ | | | () |,
         |_| |___/ |_|  \__/,
,
,
Brought to you by linuxserver.io,
-------------------------------------,
,
To support the app dev(s) visit:,
Jellyfin: https://opencollective.com/jellyfin,
,
To support LSIO projects visit:,
https://www.linuxserver.io/donate/,
-------------------------------------,
GID/UID,
-------------------------------------,
,
User uid:    1000,
User gid:    1000,
-------------------------------------,
,
[cont-init.d] 10-adduser: exited 0.,
[cont-init.d] 30-config: executing... ,
[cont-init.d] 30-config: exited 0.,
[cont-init.d] 40-gid-video: executing... ,
[cont-init.d] 40-gid-video: exited 0.,
[cont-init.d] 90-custom-folders: executing... ,
[cont-init.d] 90-custom-folders: exited 0.,
[cont-init.d] 99-custom-scripts: executing... ,
[custom-init] no custom files found exiting...,
[cont-init.d] 99-custom-scripts: exited 0.,
[cont-init.d] done.,
[services.d] starting services,
[services.d] done.,
```

**Screenshots**
![image](https://user-images.githubusercontent.com/59648138/128436578-bf54879e-f860-4d8f-b424-f09b49326276.png)

**Comment by sgb999** [comment]
it seems like although the port is open when checking ports with netstat, it will not allow any client to see this port is open when i try using telnet on windows
![image](https://user-images.githubusercontent.com/59648138/128436954-cf37f5f4-c1cf-4b18-862d-5cd95378883d.png)

**Comment by jester-xbmc** [comment]
Maybe trying pulling for the official docker ?

https://hub.docker.com/r/jellyfin/jellyfin/

**Comment by jorensanbar** [comment]
You're installing in correct order, but you need to update your Rasberry Pi OS:

FIX: https://docs.linuxserver.io/faq#libseccomp

Use OPTION 2.

**Comment by cvium** [comment]
We don't support unofficial images, but it looks like you may have received the proper help
