### ISSUE TITLE
Replace bower with webpack

### ISSUE THREAD

**Issue by dcrdev** [jellyfin/jellyfin#64]
Bower has been dead a long time - we should replace it with something more robust for managing out Javascript dependencies.

Suggestion: Webpack

**Comment by blindman** [comment]
You sure you don't mean something like yarn/npm?

Webpack is more for bundling your assets (js, css, images, etc) while bower is a package manager to pull in all of your dependencies.

**Comment by joshuaboniface** [comment]
Closing in favour of jellyfin-web#21
