### ISSUE TITLE
Jellyfin for Kodi: Music not syncing

### ISSUE THREAD

**Issue by Hetoft** [jellyfin/jellyfin#6400]
**Describe the bug**
Jellyfin for Kodi doesn't properly sync music. All albums and artists appear, but no songs are showing. I have tried using both Kodi for Android (OnePlus 6T), Android TV (Chromecast with Google TV) and Debian (OSMC), both Kodi 18 and 19. My music is named and structured accordingly to the Jellyfin documentation. I also tried multiple ways of naming the files and folders, plus different MP3s and artists, but to no avail. The songs show up fine if I add them through the SMB share in Kodi, bypassing Jellyfin. Please see the Kodi log here for for information: https://paste.kodi.tv/ditiloqisa.kodi

**System (please complete the following information):**
 - OS: Debian Stretch
 - Server: Vero 4K (ARM)
 - Clients: Vero 4K (Debian), Android TV and Android 11
 - Kodi version: 18.9 and 19.1
 - Jellyfin Version: 10.7.6
 - Reverse Proxy: None
 - Networking: Local network, wired and wireless
 - Storage: Local server, shared through Jellyfin and SMB

**To Reproduce**

1. Setup a shared music library in Jellyfin server
2. Install Jellyfin for Kodi (clean install)
3. Setup your server settings in the client
4. Choose a single music library to sync
5. Wait for it for finish syncing
6. Check your Kodi music library - which should contain songs, but doesn't. Artists and albums are showing, but the albums are empty. 

**Expected behavior**
I expected my music to show up in Kodi and being playable, using the correct metadata. 

**Logs**
https://paste.kodi.tv/ditiloqisa.kodi

**Comment by HybridSarcasm** [comment]
This has been open quite a while. Can this be re-produced with the current build? If so, please update the bug report details. Thanks!
