### ISSUE TITLE
Jellyfin app play store

### ISSUE THREAD

**Issue by xarmadigi** [jellyfin/jellyfin#6410]
Android app
Oficial Play Store
Hi, app Android 2.3 not rules live tv.
Not open.
I hace installed the before version and it rules perfectly.

Great Job my friends always!!! Good Luck!!!

**Comment by TimGels** [comment]
It does not open live TV on the Android app?

**Comment by xarmadigi** [comment]
Not reproduce. Not works external reproductor, not works exo, and not works html

**Comment by xarmadigi** [comment]
I have tested it on different terminals, with 2.3.1. and the result is that a message always pops up stating that it cannot be played on this device. Html stays loading, exo doesn't play and external doesn't even open. Using live tv with m3u tunner
