### ISSUE TITLE
Displayed backdrop not cycling

### ISSUE THREAD

**Issue by sflix** [jellyfin/jellyfin#6411]
**Describe the bug**
Backdrop not changing/cycling when library is configured for more than 1 backdrop to be fetched or tv/movie has more than 1 backdrop artwork files. 

**System (please complete the following information):**
Using: docker imgage in synology, and kodi addon with native paths.

**To Reproduce**
Browse into a tv show or movie information. 

**Expected behavior**
Cycling backdrops are to be showed in background tv/movie info.

**Comment by cvium** [comment]
This is a client issue. Which client are you using?

**Comment by gibahjoe** [comment]
Currently experiencing this issue on LGTV client. The backdrop does not cycle like it does on the web.
