### ISSUE TITLE
Full of 【AuthenticationScheme: CustomAuthentication was challenged】in log file

### ISSUE THREAD

**Issue by nukewarrior** [jellyfin/jellyfin#6419]
![image](https://user-images.githubusercontent.com/10683831/129325949-b581ee6f-a5d4-4f99-bf77-40a81edb63ff.png)

【CustomAuthentication was challenged】keeps coming every 5-8 seconds without any incoming connections.

monitoring cmd( on my openwrt router):【tcpdump -ni pppoe-wan port <port_number>】

 - OS: Synology DSM 6.2
 - Virtualization: Docker
 - Jellyfin Version: 10.7.6
 - Networking: Host

**Comment by Vertux** [comment]
Just for information. I did run into a similar issue too with a fresh Jellyfin installation. 
```
Dez 20 16:45:41 jellyfin jellyfin[3774]: [16:45:41] [INF] AuthenticationScheme: CustomAuthentication was challenged.
Dez 20 16:45:42 jellyfin jellyfin[3774]: [16:45:42] [INF] CustomAuthentication was not authenticated. Failure message: Invalid token.
```
The reason was, that Firefox had cached an old authentication token from a former test installation of Jellyfin. If you first clear the browser cache the configuration wizard starts without issues.
