### ISSUE TITLE
Movie identification is not correct

### ISSUE THREAD

**Issue by jorensanbar** [jellyfin/jellyfin#6426]
As you can see, my server does not identify the movies, it only includes the name of the file.

![imagen](https://user-images.githubusercontent.com/25260359/129458594-0489eb1f-b284-4720-870f-16ca1c104385.png)

Previously I used PLEX, and this one does the identification. In Jellyfin the identification is perfect if I do it manually. But manually identifying 1000 movies is a lot of work.

The names of the files, I start it with the year of publication, to keep track when there are great sagas. According to the documentation, the year is placed at the end, but that would make the files to be arranged in alphabetical order, and not by date.

![imagen](https://user-images.githubusercontent.com/25260359/129458634-7e974bb0-c0d3-4fc0-b652-9b9db9eb93d0.png)

The request is to include the analysis mode: Year- Name. Like PLEX does.

Edit:
This only occurs in sagas when they are in a single folder. Example:

- **Jurasic Park (Main folder)**
- 1993- Jurassic Park.mkv
- 1997- The Lost World- Jurassic Park.mkv
- 2001- Jurassic Park III.mkv

In single films, identification is done correctly:

- **Jungle Cruise (Main folder)**
- 2021- Jungle Cruise.mkv

**Comment by keturo** [comment]
You must put the movies into single folders or the identification is not possible when different movies are in a single Sub Folder.
Another solution is to put the movies into the root media folder, this would also work.

Take a look in the documentation:
https://jellyfin.org/docs/general/server/media/movies.html

**Comment by jorensanbar** [comment]
In the end I had to do it manually, film by film. Putting all the movies in single folders would be a mess, especially in sagas.

Now, the problem occurs in the TV Shows, with the Specials.

I already did the renaming using the following format:
TV_Show_Name - S00E## - OriginalName.

![imagen](https://user-images.githubusercontent.com/25260359/129629813-7b29ca7b-837b-4392-8605-4e324b565511.png)

But, But you always assign the name like: Episode 1, 2, 3 etc, you never get the real information.

![imagen](https://user-images.githubusercontent.com/25260359/129629883-030edc94-23e2-4599-9c6f-a9d24538fc45.png)

Although it does detect external IDs, it never loads the metadata information:

![imagen](https://user-images.githubusercontent.com/25260359/129630002-8d2b42a1-82f6-4b1d-aa37-f6dc4096055d.png)

If I click on the button on the right, it takes me to the page with all the information, but it never loads it into Jellyfin:
![imagen](https://user-images.githubusercontent.com/25260359/129630092-899d2940-da73-4495-88eb-a9cd6ce66475.png)

I already installed the AniDB Plugin, giving the same result, all the specials are saved as: Special - Episode #

**Comment by jorensanbar** [comment]
I made sure the information existed in TMDB, but Jellyfin does not load the information.

You can see that in the season of specials, it has all the information, but Jellyfin does not download it: https://www.themoviedb.org/tv/63926/seasons?language=en

**Comment by jorensanbar** [comment]
I had to search the Emby forums for a solution.

You must install the TVDB Plugin, and mark it as the first option to obtain episode information.

**Comment by jorensanbar** [comment]
> You must put the movies into single folders or the identification is not possible when different movies are in a single Sub Folder.
> 
> Take a look in the documentation: https://jellyfin.org/docs/general/server/media/movies.html

Solution from EMBY: https://support.emby.media/support/solutions/articles/44001159102-movie-naming

Renaming the files, and including the ID in the name:
![imagen](https://user-images.githubusercontent.com/25260359/129948965-2b668629-3f29-47ab-b143-48c8792a24b0.png)

In this way, a complete saga can be found in your folder, and the identification is done automatically:

![imagen](https://user-images.githubusercontent.com/25260359/129949231-a68e6730-0605-4c3d-b7b2-14d4153191a0.png)
