### ISSUE TITLE
Use TheoryData instead of MemberData and ClassData

### ISSUE THREAD

**Issue by Bond-009** [jellyfin/jellyfin#6432]
`TheoryData` is strongly typed, making our tests more robust.
[Example of `TheoryData` in use](https://github.com/jellyfin/jellyfin/blob/master/tests/Jellyfin.Server.Tests/ParseNetworkTests.cs)

**Comment by ianjazz246** [comment]
I'm interested in helping out with this issue. I just wanted to confirm that we are trying to replace `InlineData` attributes in all tests with a `MemberTheory`. Is [something like this commit ](https://github.com/ianjazz246/jellyfin/commit/c5393b25798098aa079c185971b7ac28e5f5b994) correct?

**Comment by crobibero** [comment]
That is correct, and we also want tests that use `MemberData` to use `TheoryData` as well

**Comment by Bond-009** [comment]
> I'm interested in helping out with this issue. I just wanted to confirm that we are trying to replace `InlineData` attributes in all tests with a `MemberTheory`. Is [something like this commit ](https://github.com/ianjazz246/jellyfin/commit/c5393b25798098aa079c185971b7ac28e5f5b994) correct? 

No, InlineData is already strongly typed, no point in replacing it.
We only want to replace MemberData and ClassData

**Comment by ianjazz246** [comment]
Thanks for cleaning that up for me. I'll get started on this.
