### ISSUE TITLE
Upgrade Docker image to Debian 11 (Bullseye)

### ISSUE THREAD

**Issue by loganmarchione** [jellyfin/jellyfin#6433]
**Describe the bug**

Debian 11 (Bullseye) was just [released](https://www.debian.org/News/2021/20210814). It contains the new version of [intel-media-va-driver](https://packages.debian.org/bullseye/intel-media-va-driver) which is useful for people trying to do hardware transcoding on Intel 10th Gen.

**Additional context**

Check out these issues too:  
https://github.com/jellyfin/jellyfin/issues/6332
https://github.com/jellyfin/jellyfin/issues/5993
https://github.com/jellyfin/jellyfin/issues/3631
https://github.com/jellyfin/jellyfin/issues/3580

**Comment by crobibero** [comment]
Microsoft's images are based on buster for 5.0, and bullseye for 6.0. After 6.0 is released, we will automatically be on bullseye when that is released.

**Comment by loganmarchione** [comment]
Ah ok my bad. I was going off this line from the Dockerfile. 

`FROM debian:buster-slim as app`

You can probably close this in favor of #6385 of you want.
