### ISSUE TITLE
Empty subtitle file returned when getting external 

### ISSUE THREAD

**Issue by Tthecreator** [jellyfin/jellyfin#644]
**Intro**
I've setup jellyfin in VS for myself and have been fiddling around a little bit with subtitles. My idea was for myself to add .ass support for the web interface trough a js library. During that process I found that external subtitle files were not even correctly given to the client in the first place.

**To Reproduce**
1. I've been using this as a testfile: https://github.com/brenopolanski/html5-video-webvtt-example
2. I've also renamed the subtitle files to MIB2.vtt. I'm mainly testing the .vtt subtitles for now to see how things work.
3. I tried the following request: http://localhost:8096/emby/Videos/79f83831-1e56-692a-66e3-f978776a9bb4/79f838311e56692a66e3f978776a9bb4/Subtitles/3/0/Stream.vtt?api_key=cb7c618d09a949999de9ca8e53f50dcf (I got this request from wireshark)

**Bug**
This should return at least some subtitle data. Instead only 'WEBVTT' is returned with nothing else. My subtitle file is indeed filled.

**System (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Jellyfin Version: 10.0.2.0

**Additional context**
I'm currently trying to solve this problem myself but am still reporting it as I'm quite overwhelmed with the amount of code that this project has. I've been mazing my way trough all the subtitle code and am figuring it out step by step. Though if I do give up eventually I will have still made the report.

**Comment by JustAMan** [comment]
Might be related to https://github.com/jellyfin/jellyfin/pull/636

**Comment by Tthecreator** [comment]
Manually applying the change from #636 doesn't seem to affect my problem.

**Comment by Tthecreator** [comment]
I'm currently working on this after solving the last bug, and there seem to be some problems, but I could see this issue 'evolve' way too much so I'm going to wait with posting anything until I figure out what my exact problem is.

**Comment by cvium** [comment]
It's fixed in #629 ;)

**Comment by Tthecreator** [comment]
Okay great now internal subtitles aren't working again. Not detected... weird
