### ISSUE TITLE
Disable embedded or image-based subtitles

### ISSUE THREAD

**Issue by matthew-jones-uk** [jellyfin/jellyfin#6442]
Image-based (usually PGS) subtitles cause issues with direct streaming, transcoding, etc and often come packaged with media. A way to disable all embedded titles for a library, or more specifically image-based subs would be very useful.

**Comment by cvium** [comment]
If you're filing a bug, please fill out the issue template properly. If you're making a feature request, it belongs here https://features.jellyfin.org/
