### ISSUE TITLE
Changing Data Path - Ubuntu

### ISSUE THREAD

**Issue by NutellaDragon** [jellyfin/jellyfin#6448]
Changed my data location by editing JELLYFIN_DATA_DIR /etc/default/jellyfin

Can confirm that issue #1235 is still present

**System (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS
 - Virtualization: none
 - Clients: Kodi on Chromecast
 - Browser: Chrome 92
 - Jellyfin Version: 10.7.6

**To Reproduce**
Change the JELLYFIN_DATA_DIR location in /etc/default/jellyfin
Kodi sync throws errors that it cannot find the network path
In Dashboard > Libraries, nothing is editable.

Following the advise to edit library.db and replace /var/lib/jellyfin to the new location as detailed in #1235 works around it.

**Comment by srcrist** [comment]
Issue closed as a duplicate of https://github.com/jellyfin/jellyfin/issues/1235. The path to ultimate resolution of this issue remains a rework of the DB functionality, which is already in progress.
