### ISSUE TITLE
Global internet streaming limit ignored

### ISSUE THREAD

**Issue by gebhaard** [jellyfin/jellyfin#6458]
Hello,

I am more than satisfied with Jellyfin, but there's a small problem I came across recently.
I have several friends who use my server, and to not overload my 23Mbps upload speed, I set the global "Internet streaming bitrate limit" to 4Mbps. However, whenever I look at my dashboard to check on the users, its always transcoding to more than 4Mbps bitrate, sometimes even unbelievable numbers, like 30+Mbps.
Am I misunderstanding something between internet streaming limit and transcoding bitrate limit, or is there something wrong?

I run Jellyfin 10.7.6 with OpenMediaVault in a Docker container, using jellyfin/jellyfin image.
Thanks.

**Comment by GodTamIt** [comment]
When you're seeing these 30 Mbps limits, is the stream, by chance, direct playing or direct streaming? You can see this typically in the player by clicking Settings -> Playback Data, at least in web player.

If so, this is a [known TODO](https://github.com/jellyfin/jellyfin/blob/e15fea5dade9478d9667399eb0c245917d3e1513/MediaBrowser.Model/Dlna/StreamBuilder.cs#L679). I think I might be able to submit a PR for this once some of my other changes land.

**Comment by twicehopped** [comment]
I am also seeing this setting ignored.

Server: 

Version: 10.7.7
Operating System: Windows
Architecture: X64

Client:

Roku Ultra (Roku Ultra)
Jellyfin Roku 1.4.12
