### ISSUE TITLE
Subtitles parameters are ignored

### ISSUE THREAD

**Issue by Ex4l** [jellyfin/jellyfin#6459]
**Describe the bug**
Since last update I'm trying to use big subtitles size but it's staying normal and the size is unchanged while playing videos ( no matter if subtitles are embedded or not) It was working perfectly prior to 10.7.6

**System (please complete the following information):**
 - OS: Synology (Linux)
 - Virtualization: Docker
 - Clients:Web on Opera (chrome based)
 - Browser: Opera Version :77.0.4054.277
 - Jellyfin Version: 10.7.6
 - Playback: Transcode (I think ?)
 - Hardware Acceleration: None
 - Installed Plugins: Trakt.tv
 - Reverse Proxy: None
 - Base URL: None
 - Networking: local
 - Storage: local
**To Reproduce**

1. Go to settings, subtitles and modify your subtitles settings and set them to larger
2. Play a video with embedded subtitles
3. See that the subtitles are normal size and not larger.

**Expected behavior**
Subtitles parameters working normally.

**Comment by gummykage** [comment]
Having same issue on Chrome / ios 13.5 Jellyfin app latest.

**Comment by srcrist** [comment]
Closing this issue as it does not reference a Jellyfin server bug. If this issue persists in the latest version of your respective client, please submit a new issue to the repository for the client in question. Subtitle display is handled by the individual clients, and different clients handle this differently.
