### ISSUE TITLE
[Video] Identify with replace existing images fails

### ISSUE THREAD

**Issue by PointReact** [jellyfin/jellyfin#6467]
https://www.youtube.com/watch?v=a4R1RmNFahY

**Comment by GodTamIt** [comment]
I've gotten to the root of this bug.

It's neither slow nor timing out.

The desired image you see from your video is being filtered out by the `IncludeAllLanguages` setting [here](https://github.com/jellyfin/jellyfin/blob/c794e48562e209a93886a91a7d99380462350194/MediaBrowser.Providers/Manager/ItemImageProvider.cs#L278).

I think I can add a temporary fix that should result in desired behavior until there's a longer-term solution (probably a UI setting).
