### ISSUE TITLE
Unidentified movie file

### ISSUE THREAD

**Issue by jorensanbar** [jellyfin/jellyfin#6468]
Bug:
There is a movie which the file analysis system does not detect.

 - OS: Rapsberry Pi OS
 - Virtualization: Docker
 - Clients: ALL
 - Browser: Firefox 91
 - Jellyfin Version: 10.7.6
 - Hardware Acceleration: OMX
 - Installed Plugins: AnimeDB, TVDB, TMDB Box
 - Storage: [local]

**To Reproduce**

1. Create a Movie Folder: **Go!**
2. Put Movie file with original name and TMDBID: **Go! (2020) - [tmdbid=520765].mkv**
3. Update Library
4. File not detected

![imagen](https://user-images.githubusercontent.com/25260359/131012183-f1daa825-027b-4214-b912-f9783f7937a1.png)

Movie data: https://www.themoviedb.org/movie/520765-go-karts

**Comment by Bond-009** [comment]
Incorrect folder structure, paths should be `Go! (2020)/Go! (2020) - [tmdbid=520765].mkv` and `/data/movies/Jungle (2017)/Jungle (2017) [tmdbid=390062].mkv` respectively.
