### ISSUE TITLE
browser player gets dark overlay on mobile

### ISSUE THREAD

**Issue by Maltahl** [jellyfin/jellyfin#647]
When testing out jellyfin on the phone i got a bug like issue #297 when doing the gisture for turn light up and down on the phone.

I then tried to switch browser (was using firefox) and then tried chrome with same result.

To reproduce:

1. Play any video on mobile using browser
2. Slide finger on the left side to turn up/down the light.
3. Now the screen is completly dark and you have to stop the video and go back in from the menu to be able to watch the video agian. Sound will still play during the darking of the player.

**Comment by JustAMan** [comment]
@bobberb can you elaborate what you meant here? or is it wrong issue for your response? I cannot understand the connection between the submitter's issue and your comment, sorry.

**Comment by bobberb** [comment]
@justaman sorry I had matrix open at the same time - I saw mention of all this being frontend issues. Regarding certain items with subtitles moving from direct to transcode triggers same dark overlay. Should have opened a new issue and given fully details.
