### ISSUE TITLE
[Video] Files with article reversal are not automatically identified

### ISSUE THREAD

**Issue by PointReact** [jellyfin/jellyfin#6471]
https://www.youtube.com/watch?v=fDCZr4g18mk

Summary: Movies with titles like "The Movie" but have the files renamed like "Movie, The" must be manually identified.  Bonus bug where the image you click on when manually identifying a movie is not the image that is used.

**Comment by srcrist** [comment]
Closing this issue as it does not reference a genuine Jellyfin bug. Article reversal can be handled within the Jellyfin interface. Media file should be named and organized according to the conventions outlined in the Jellyfin documentation, and file and directory names should reflect the official names of the media they contain for best results.
