### ISSUE TITLE
LiveTV - cannot sync streams between devices.  Timeline error when trying to get to 'now'. 

### ISSUE THREAD

**Issue by supersebbo** [jellyfin/jellyfin#6476]
**Describe the bug**
When streaming a Live TV program on two devices on the same Jellyfin account, Jellyfin (correctly) uses the same remux temp file for both devices, however it's very difficult to get the devices to reach the same playback point, to get them even close to in sync.  This is particularly noticable with live sport.

**System (please complete the following information):**
 - Debian
 - KVM
 - Android, iPad
 - Browser: [e.g. Firefox 72, Chrome 80, Safari 13]
 - 10.7.6
 - LiveTV Remux

**To Reproduce**

1. Start playing a LiveTV channel on one device. 
2. Some time later start playing the same LiveTV channel on another device (same account)
3. The LiveTV stream will start at the start of the Remux temp file from the first device (can this behaviour be changed?)
4. On the second device, drag the playback slider all the way to the right (which should be 'now')
5. The stream on the second device will scrub forward, however will still be significantly behind the first device (by up to 30 minutes in my testing)
6. You can get them to sync up (very tediously) by then keeping pressing the fast-foward button on the second device which seems to allow it to scrub beyond the end of the playback slider. 

**Expected behavior**
When you drag the playback slider on the second device all the way to the right, it should go to the most current point in the remux temp file/stream i.e 'now'
Ideally it should try to sync 'now' with other devices on the same account streaming the same LiveTV channel. It is very frsutrating, particularly with Live Sport to have it at different playback points in different rooms.

**Comment by srcrist** [comment]
The fact that playback starts from the beginning of a previous client's temp file probably rises to the level of a bug. But it should also be stated that the Live TV functionality isn't intended to keep all clients perfectly in sync. Even commercial Live TV streaming can be off by as much as several minutes from client to client.

Are you able to confirm that this behavior persists in version 10.8.11?
