### ISSUE TITLE
Some multi-disc albums are not divided by disc number

### ISSUE THREAD

**Issue by ShredderWalnut** [jellyfin/jellyfin#6488]
**Describe the bug**

**System (please complete the following information):**
 - OS: Raspberry Pi OS
 - Virtualization: none
 - Clients: affects all clients
 - Browser: Safari 15
 - Jellyfin Version: 10.7.6
 - Playback: not applicable
 - Hardware Acceleration: not applicable
 - Installed Plugins: InfuseSync, Kodi Sync Queue, Open Subtitles, TheTVDB
 - Reverse Proxy: none
 - Base URL: none
 - Networking: not applicable
 - Storage: local

**To Reproduce**

1. Create a `Music` library in Jellyfin and point it to a local folder.
2. Add some `.flac` files into the folder. Organize the files according to the *Discs* section in the [official docs](https://jellyfin.org/docs/general/server/media/music.html).

**Expected behavior**

All the multi-disc albums are divided by disc number.

**Server Logs**

No errors found.

**FFmpeg Logs**

Not applicable.

**Browser Console Logs**

Not applicable.

**Screenshots**

Screenshot 01. This album has four discs, and Jellyfin correctly divides the album into four sections accordingly:
<img width="1392" alt="01" src="https://user-images.githubusercontent.com/34428332/131529308-d6ec5ba9-1817-414e-93bd-02d328663997.png">
Screenshot 02. This album has two discs, but Jellyfin does not divide the album accordingly. Instead, no disc numbers are displayed and all tracks are sorted by track number first and track title next:
<img width="1392" alt="02" src="https://user-images.githubusercontent.com/34428332/131529590-f05d1f87-8517-45de-b4cc-4fcb964d7f3c.png">
Screenshot 03. This is track 1, disc 1 from the problematic album shown in screenshot 02.
<img width="1392" alt="03" src="https://user-images.githubusercontent.com/34428332/131529903-f1ce5b82-82e2-48b7-ba49-ec22a0698fe1.png">
Screenshot 04. This is track 1, disc 2 from the same album.
<img width="1392" alt="04" src="https://user-images.githubusercontent.com/34428332/131529977-987edf25-06b3-4a74-a9ef-271b268453fe.png">

**Additional context**

1. I am aware that this issue can be manually fixed by filling in the correct disc number in each track's metadata field. However, this issue could still be caused by a bug.
2. Despite the fact that tracks from different discs of the same album have different values in their `Album` metadata field (as shown in screenshot 03 and 04 above), all the tracks are grouped under a single album, so I believe this issue are not related to #5605 at all.

**Comment by ShredderWalnut** [comment]
Update:

After further research, I used [XLD](https://tmkk.undo.jp/xld/index_e.html) to automatically grab metadata from MusicBrainz so that the `.flac` files have correct `Album` and `Disc number` metadata tag values. This fixed the issue for me and Jellyfin can correctly split all multi-disc albums into separate discs.

I assumed correct folder hierarchies alone should be able to make Jellyfin populate all metadata values, but apparently I need to have the correct values in the files themselves first for Jellyfin to recognize them.

**Comment by sulisu** [comment]
It is not fixed in 10.8.0.0 beta2.

**Comment by arnaldoperez** [comment]
Still not fixed in 10.8.10

**Comment by tomkowz** [comment]
This is still issue in 10.9.2.

I have an album with 2 disks, mp3 files in CD 1 and CD 2 directories. With kid3 app I added "Disc Number" metadata, refreshed metadata and the files are not grouped by disks. There is a list of 1, 1, 2, 2 and so on. However, when I put that album directory to Music app then it presents them grouped by disks.

**Comment by Shadowghost** [comment]
What's your file structure and do your files have multiple tags (e.g. ID3v1 and ID3v2)?

**Comment by tomkowz** [comment]
Hey! Sorry, I think it was something wrong with refreshing metadata or some weird detail on the title of the album, not sure. What I did to fix that was:
1) Make sure metadata is refreshed including cover refresh (no changes)
2) Then I thought I'll rename album to "Album Name (CD 1)" and "Ablum Name (CD 2)" and refreshed metadata as in step 1. And this fixed the issue.
3) Then I brought back the original title for both CDs, refreshed metadata and I can see correct album name with correct grouping. Wondering if there was some difference in album name but then I guess they would be grouped as separate albums instead of one from the beginning.

Maybe the album title updating did some trick to refreshing metadata?

**Comment by tomkowz** [comment]
Oh and regarding my files structure:

> Music
>> Artist
>>> Album
>>>> CD1 > mp3 files
>>>> CD2 > mp3 files

Using ID3 v2.3.0

**Comment by Shadowghost** [comment]
Sounds like inconsistent album title to me 🤔 
Glad that it is resolved though.
