### ISSUE TITLE
Add Google Drive as a media source but also include google drive's pre-made transcodes.

### ISSUE THREAD

**Issue by bnichs5** [jellyfin/jellyfin#650]
Below I linked DDurdle's python script. It connects to your google drive account and will output .strm files of your videos of all resolutions 360p to 1080p transcodes and the option to play original file. It would be awesome and really convenient if you could somehow implement this into Jellyfin.

https://github.com/ddurdle/Python-GoogleDrive-VideoStream

**Comment by EraYaN** [comment]
All media sources will have to be handled by the OS. That is the current view point of the team. Otherwise we need to maintain way to many services (cause everyone wants in) with tons of often unstable APIs, and we don't want to do that.
