### ISSUE TITLE
Media end time does not update with respect to playback speed

### ISSUE THREAD

**Issue by sortedcord** [jellyfin/jellyfin#6509]
The time at which a video ends does not change when I change the playback speed. 

**System:**
 - OS: Ubuntu
 - Clients: Browser 
 - Browser: Chrome 93
 - Jellyfin Version: 10.7.6

**Expected behavior**
I have a 2 hour video which I am streaming at 1x speed. If it's currently 2PM then Jellyfin promptly shows that the video ends at ~4PM. Seeking also updates the end time. However, If I am streaming the video at 2x speed, still it displays that the video ends at 4PM. I don't think that this a client specific bug as I tested on both iOS and browser and get the same thing.

**Comment by cvium** [comment]
Wrong repo and duplicate https://github.com/jellyfin/jellyfin-web/issues/2700
