### ISSUE TITLE
Playlists 'infinite loading' if the user not have all access libraries

### ISSUE THREAD

**Issue by davipro34** [jellyfin/jellyfin#6514]
The Playlists 'infinite loading' if the user not have all access libraries.

**Describe the bug**
The playlists don't launch if I not have all access libraries.
Whith and whithout server plugins, the bug remains.
If I check the box 'Enable access to all libraries' for the user, it's ok.
If I check the box 'Allow this user to manage the server' for the user, it's Not ok.

**System (please complete the following information):**
 - OS: Debian 10
 - Virtualization: VM guest (KVM Proxmox)
 - Clients: Browser, Android (and app Gelli on Android)
 - Browser: Firefox 91.0.2 (64 bits), Chromium Version 93.0.4577.63 (Build officiel) snap (64 bits)
 - Jellyfin Version: 10.7.6
 - FFmpeg Version: don't know
 - Playback: don't know 
 - Hardware Acceleration: don't know
 - Installed Plugins: AudioDB10.7.6.0 , Auto Organize9.0.0.0 , Kodi Sync Queue6.0.0.0 , MusicBrainz10.7.6.0 , OMDb10.7.6.0, Playback Reporting10.0.0.0 , Reports12.0.0.0
 - Reverse Proxy: none
 - Base URL: none
 - Networking: NAT
 - Storage: local mount of SMB share on NAS
 
 **To Reproduce**
1. Go to 'Media'
2. Click on 'Playlists'
3. See infinite loading
 Or
1. Go to 'Media / Music'
2. Click on 'header section : Playlists'
3. Choose to open 'one of your playlists'
4. Click on 'header play button'
3. See infinite loading

**Screenshots**
![1_JellyFin_info_srv](https://user-images.githubusercontent.com/78750640/132186322-071a29cc-24e1-4800-9c30-7f1e9e5f94ab.png)

![2_JellyFin_Access_Libraries](https://user-images.githubusercontent.com/78750640/132186341-fd571a9c-91a7-4685-952e-1e6c10de2ced.png)

![3_JellyFin_pb_playlists](https://user-images.githubusercontent.com/78750640/132186482-3d2aec54-00a3-4233-a27c-ee5322611e72.gif)

![4_JellyFin_pb_playlists](https://user-images.githubusercontent.com/78750640/132186543-a679a00b-d953-4ac7-a597-6176f737bcdf.gif)

**Additional context**
The bug is still on WebClient (any browser, any PC, Linux and Windows), on Android App "Jellyfin (Mobile)" and "JellyFin (AndroidTV)" and "Gelli (Android FDroid).

When you check the box "Enable access to all libraries" for the user, it's ok.
All users are concerned except the admin.

**Comment by hhchenchong** [comment]
I think you have the same bug with me

**Comment by SteveDinn** [comment]
This looks the same as this bug I logged back in April: https://github.com/jellyfin/jellyfin/issues/5939
Glad to know it's not just me :)

**Comment by Methatronc** [comment]
I confirm to experience this as well, with Jellyfin Web 10.7.6, not tried on the app though as I don't use it.

**Comment by mueslimak3r** [comment]
I also have this bug

**Comment by davipro34** [comment]
I just tested on a Manjaro OS with a clean and new installation of Jellyfin in version 10.7.7.
Bug # 6828 remains present.
Bug # 6514 remains present.
I have three different installations that have the same issues.
If I need testing I can help.

**Comment by mihailim** [comment]
Seems to be the same issue as #6264 .

**Comment by Dengesiz07** [comment]
Just to share my observation hoping that this issue would be solved soon.

When I edit a playlist.xml to share it with another user, even if the user "Enable access to all libraries" is set, "Playlists" menu  (or this shared playlist) on the main dashboard will not show up until the user creates his first playlist.

**Comment by jabocg** [comment]
I ran into this issue, and judging by the logs, it is a specific permissions thing. This log is found after trying to access Playlists without full access:

```[2022-11-29 22:35:45.505 +00:00] [WRN] [44] Jellyfin.Api.Controllers.ItemsController: "jabocg" is not permitted to access Library "Playlists".```

You can still add shows and movies to a playlist, and therefore create a new one, but the only way to get back to that created playlist is to add a new thing to it. You also can't "play" the playlist by using the big play button, only by clicking one of the items added to the playlist.

A workaround I found is to create a new library called "Playlists" and point it to Jellyfin's playlists directory(default is `/config/data/playlists`), and then grant my user access to this new library. It's not ideal, and I haven't been using for long so there might be some unintended consequences, but it might help in the meantime waiting for a true fix.

**Comment by meonkeys** [comment]
I just started seeing this bug recently. Maybe since upgrading to version 10.8.8?

Toggling "Enable access to all libraries" does **not** help.

I see lots of log messages like this:

```
[16:25:41] [WRN] [292] Jellyfin.Api.Controllers.ItemsController: JoeUser is not permitted to access Library PlaylistCreatedByJillUser
```

Note that `PlaylistCreatedByJillUser` is not a Jellyfin Library, it is a playlist.

**Comment by Shadowghost** [comment]
#8526 Should fix playlist permissions. This will also disable that users can see arbitrary playlists created by other users (this was never intended behaviour).

**Comment by felix920506** [comment]
@CDubs00 the fix will not be available in 10.8.x and will only be out in Jellyfin 10.9

**Comment by arquesing** [comment]
This bug persists in Jellyfin version 10.9.11. The issue is not limited to playlists; it occurs with any video when users are given access to only specific libraries and not all libraries.

Is there any additional information?

**Comment by EsmailELBoBDev2** [comment]
I use latest version and can say its not fixed too
