### ISSUE TITLE
Windows installer not built for 10.7.7

### ISSUE THREAD

**Issue by K900** [jellyfin/jellyfin#6525]
Hi! I maintain the Chocolatey package for Jellyfin, and I've noticed the new release is tagged on Github, but a Windows installer is not available at https://repo.jellyfin.org/releases/server/windows/stable/. All other builds have been updated, but the installer is still on 10.7.6. Is this intentional?

**Comment by crobibero** [comment]
The windows installer is built manually, so we just haven’t done it yet.

**Comment by K900** [comment]
I see. Is it better to switch the package to installing the portable version then? Or maybe I can help with automating the installer builds?

**Comment by anthonylavado** [comment]
@K900 My apologies, this will be coming shortly. There is some preliminary work to automate it, but things got stalled when we didn't have a release for a while.

**Comment by anthonylavado** [comment]
@K900 This is now available.

**Comment by K900** [comment]
Thank you!
