### ISSUE TITLE
Debian unstable update/installation issue

### ISSUE THREAD

**Issue by ich777** [jellyfin/jellyfin#6529]
**Describe the bug**
Not sure but is something broken with the unstable builds for Debian or did I do something wrong? Every time I try to upgrade  or install the necessary packages I get this:

```
The following packages have unmet dependencies:
 jellyfin : Depends: jellyfin-server (>= 20210908.8-unstable) but it is not going to be installed
Unable to correct problems, you have held broken packages.
```

This was working about 2 days ago flawlessly, did something change?

**System (please complete the following information):**
 - OS: Debian 11 (Bullseye)
 - Jellyfin Version:  unstable 20210908.8

**Comment by aptalca** [comment]
Same thing with the Ubuntu unstable repo:
```
The following packages have unmet dependencies:
 jellyfin : Depends: jellyfin-web (>= 20210910.11-unstable) but 20210910.5-unstable is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by ich777** [comment]
Is there any information on this...

**Comment by joshuaboniface** [comment]
Bullseye is now "stable", and we use the distro names in the repo.

Can you post your `sources.list` entries?

**Comment by ich777** [comment]
@joshuaboniface thank you for the response, here are the content from my `sources.list`:

```
# deb cdrom:[Debian GNU/Linux testing _Buster_ - Official Snapshot amd64 DVD Binary-1 20190527-04:04]/ buster contrib main

#deb cdrom:[Debian GNU/Linux testing _Buster_ - Official Snapshot amd64 DVD Binary-1 20190527-04:04]/ buster contrib main

#deb http://security.debian.org/debian-security buster/updates main contrib non-free

deb http://deb.debian.org/debian bullseye main contrib non-free
deb http://deb.debian.org/debian bullseye-updates main contrib non-free
deb http://security.debian.org/debian-security bullseye-security main
deb http://ftp.debian.org/debian bullseye-backports main contrib non-free
```

This is how I added the Jellyfin source:
```
curl -s https://repo.jellyfin.org/debian/jellyfin_team.gpg.key | apt-key add - && \
echo 'deb [arch=amd64] https://repo.jellyfin.org/debian bullseye main unstable' > /etc/apt/sources.list.d/jellyfin.list && \
apt-get update
```

**Comment by joshuaboniface** [comment]
OK that looks right to me. It does indeed look like something is borked on the repo side. We'll take a look.

**Comment by ich777** [comment]
Tried it again but still the same with the newest build:
```
The following packages have unmet dependencies:
 jellyfin : Depends: jellyfin-server (>= 20210914.7-unstable) but it is not going to be installed
```

**Comment by aptalca** [comment]
@joshuaboniface just fyi, we see the same behavior with the ubuntu unstable repo as well
Here's a failed build: https://ci.linuxserver.io/blue/organizations/jenkins/Docker-Pipeline-Builders%2Fdocker-jellyfin/detail/nightly/1485/pipeline
And here's the Dockerfile: https://github.com/linuxserver/docker-jellyfin/blob/nightly/Dockerfile#L22

**Comment by joshuaboniface** [comment]
So I've taken a look and it looks like it's just an issue with the metapackage `jellyfin`. There's some versioning wonkiness with it compared to the others. I'm going to try to fix it, but that said, for right now (and for LSIO images, probably long-term too), a good workaround would be to ignore and remove the `jellyfin` metapackage, and just manually install `jellyfin-server` and `jellyfin-web` packages. The metapackage was mostly for seamless upgrades when we first introduced that split but was kept for convenience.

**Comment by ich777** [comment]
@joshuaboniface is it expected that `jellyfin-web` is version 20210917.5 and `jellyfin-server` is version 20210913.13?
I've gone through a few old build logs and the two where always the same version.

Also something seems to be wrong with the `jellyfin` meta package, the dependencies are wrong:
`Depends: jellyfin-server (>= 20210917.5-unstable), jellyfin-web (>= 20210917.5-unstable), jellyfin-ffmpeg (>= 4.2.1-2)`

This can't work because in the `jellyfin` meta it says that `jellyfin-server` is:
```
Package: jellyfin-server
Version: 20210913.13-unstable
```

and `jellyfin-web` is:
```
Package: jellyfin-web
Version: 20210917.5-unstable
```

Also attached the file where you can see it:
[jellyfin.txt](https://github.com/jellyfin/jellyfin/files/7187458/jellyfin.txt)
