### ISSUE TITLE
TVMaze Plugin - 8.0.0.0 - Status is "Malfunctioned"

### ISSUE THREAD

**Issue by MovieWiz** [jellyfin/jellyfin#6533]
The TVMaze 8.0.0.0 no longer retrieves metadata.  When checking the plugins in the server dashboard, the status for the plugin is "Malfunctioned".

 - OS: Windows
 - Jellyfin Version: 10.7.6, stable

**To Reproduce**
1. Start the server
2. Open server in browser
3. Go to the Plugin section in the Dashboard
4. See that the status of the plugin

**Expected behavior**
The TVMaze plugin should startup correctly.

**Comment by crobibero** [comment]
I believe tvmaze v8 requires Jellyfin 10.7.7. We are actively working on fixing the plugin being installed when it is not compatible.
