### ISSUE TITLE
network mounted media takes 20 seconds to direct play

### ISSUE THREAD

**Issue by jameskimmel** [jellyfin/jellyfin#6537]
**Describe the bug**
My jellyfin server uses a nfs mounted media. Direct play any file takes around 20 seconds. If jellyfin transcodes or remuxes a file, it instantly (1s) plays.  

**System (please complete the following information):**
 - OS: Ubuntu Server 20.04.1
 - Virtualization: no
 - Clients: any
 - Browser: any
 - Jellyfin Version: 10.7.7
 - FFmpeg Version: unknown
 - Playback: Direct Play triggers the bug, Remux and Transcode work fine
 - Hardware Acceleration: none
 - Installed Plugins: none
 - Reverse Proxy: nginx
 - Base URL: none
 - Networking:
 - Storage: NFS share from TrueNAS

**To Reproduce**

1. put media on NFS drive
2. direct play any file
3. you see a blank black screen for 20 seconds

**Expected behavior**

It should not take 20 seconds to direct play a file or at least show some kind of "loading in progress" instead of a black screen. I initially thought it crashed and my JMP is broken, because I never waited for such a long time.

**Server Logs**

slow http response warnings around 20 seconds.

**Additional context**

Someone mentioned, it could be a .net problem.

**Comment by geilername** [comment]
if you are using NFSv3 thats your problem. switch to NFSv4 and your problem will be solved

**Comment by jameskimmel** [comment]
I will give it a try. I never really thought about NFSv4, because TrueNAS uses NFSv3 by default. 
Maybe this could be added to the docs or system requirements to warn other users?

**Comment by jameskimmel** [comment]
Switching to NFSv4 did solve the issue! slow https response warning went down form 20 seconds to 0.72 seconds :)
