### ISSUE TITLE
Cannot access jellyfin outside localhost.

### ISSUE THREAD

**Issue by lavadrop** [jellyfin/jellyfin#6540]
**Describe the bug**
I cannot access the jellyfin webUI or from a third party app or official iOS app locally, only the host can open the webUI.

**System (please complete the following information):**
 - OS: OpenSUSE
 - Virtualization: Docker
 - Clients: Firefox, Firefox on iOS, MrMC on AppleTV and official iOS app
 - Browser: Firefox 91, Firefox Daylight 36
 - Jellyfin Version: 10.7.7 
 - FFmpeg Version: excuse me?
 - Playback: irrelevant 
 - Hardware Acceleration: default
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: none
 - Networking: Host, apparently
 - Storage: local

**To Reproduce**

1. Go to [internal IP]:8096
2. Error: "Unable to connect Firefox can't stablish a connection to the server at [internal IP]:8096 

**Expected behavior**
Load the WebUI or connect to the server on the iOS app or the tvOS app.

**Server Logs**
https://gist.github.com/lavadrop/9fa445c0ed8d3bb99daf6aa5950594da

**Additional context**
Installed the jellyfin docker image per the main download page code at jellyfin.org (stable)

**Comment by cyber89** [comment]
You should check your docker network configuration and binding port

**Comment by lavadrop** [comment]
I did, there is nothing configured in firewalld, just 2 zones and nothing bound to docker. Disabling firewalld makes jellyfin accesible. I don't think the installation instructions take into consideration distros that block everything and activate firewalld by default, like openSUSE.

**Comment by Artiume** [comment]
can i see your docker configuration for jellyfin

**Comment by lavadrop** [comment]
Sure, sorry for the late reply.

https://gist.github.com/lavadrop/3a97f325ad5feb85f88d60ad70281c82

**Comment by CanalWood** [comment]
Hello,
I use Docker on my Syno with Jellyfin package without any network pb on the HTTP port. 
I've trouble with SSL port(#6650).

Could you check : netstat -tuplen |grep 8096

**Comment by Bond-009** [comment]
Sounds like your firewall is doing it's job.
Research how to open ports for your firewall, that's not something jellyfin should do automatically.
