### ISSUE TITLE
Future debian CODENAME removal and jellyfin install issues

### ISSUE THREAD

**Issue by martadinata666** [jellyfin/jellyfin#6547]
**Describe the bug**

As the future debian base-files removing some part such as CODENAME  [base-files-changelog](https://tracker.debian.org/news/1249897/accepted-base-files-12-source-into-unstable/)
The installation method refered at https://jellyfin.org/downloads/ breaking the repo URL.

`bullseye`
```
debian@2565810defec:/$ echo "deb [arch=$( dpkg --print-architecture )] https://repo.jellyfin.org/$( awk -F'=' '/^ID=/{ print $NF }' /etc/os-release ) $( awk -F'=' '/^VERSION_CODENAME=/{ print $NF }' /etc/os-release ) main unstable"
deb [arch=amd64] https://repo.jellyfin.org/debian bullseye main unstable
```
`bullseye os-release`
```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

`sid/unstable/testing`
```
deb [arch=amd64] https://repo.jellyfin.org/debian  main unstable
```
`sid/unstable/testing os-release`
```
PRETTY_NAME="Debian GNU/Linux bookworm/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
**System (please complete the following information):**
 - OS: Debian Sid and Bullseye
 - Docker image

**To Reproduce**
1. Just rebasing the base debian image.

**Expected behavior**
1. Repo generated correctly

**Comment by crobibero** [comment]
Thank you for the report. I don’t see this as a bug because bullseye was just released and sid won’t be out for quite some time.

**Comment by martadinata666** [comment]
Yes, but also it affect the current native install on debian testing/sid as the base-files package already update to v12. Workaround just use `bullseye` in repo line instead empty space as generated.

**Comment by mikeage** [comment]
Bookworm has been out for a while now, and the bullseye packages seem to not be compatible with the libraries included in bookworm (e.g., libx264 is now libx264-164, not -160).

```
$ sudo apt install jellyfin
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 jellyfin-ffmpeg : Depends: libvpx6 (>= 1.6.0) but it is not installable
                   Depends: libwebp6 (>= 0.5.1) but it is not installable
                   Depends: libx264-160 (>= 2:0.160.3011+gitcde9a93) but it is not installable
                   Depends: libx265-192 (>= 3.2) but it is not installable
```

Is there any plans for a bookworm compatible repo?

**Comment by Shadowghost** [comment]
We're currently only supporting Debian stable and oldstable, bookworm is still designated testing.

**Comment by mikeage** [comment]
Thanks. I wasn't sure if the comment from 2021 was about not supporting testing as a strategic decision, or just about the specific timing of bullseye just having come out. I appreciate the clarification.

**Comment by martadinata666** [comment]
it about jellyfin install on debian `testing` it used to be `bullseye` now `bookworm`, i raised this because my CI image based on debian testing, but as the dev tell it only `oldstable` and `stable`. so be it. 👍🏼
