### ISSUE TITLE
".vtt" subtitle files do not load when playing ".strm" file media

### ISSUE THREAD

**Issue by atmos-o** [jellyfin/jellyfin#6561]
When playing a  `.strm` video, the `VTT` subtitle file in the same directory level does not show. It shows the subtitle as an option in JF's pop-up but refuses to display. 

`.srt` subtitles are found & played perfectly fine.

**Comment by atmos-o** [comment]
I badly want vtt to work for me coz I have everything already prepared in that. 

I've put on hold creating a script to mirror all files in a directory with my media and replacing video files to `.strm` for this single reason.

I have JF installed through docker using hotio's image. Nothing else changed other than some tweaks to allow GPU access to the container. And my media is hosted and accessed through a web index.

How do you have yours?

**Comment by sevenrats** [comment]
Please provide the minimum information necessary to test this issue, such as an example strm link and corresponding vtt subtitle.

**Comment by Bond-009** [comment]
Closing as not enough info
