### ISSUE TITLE
EPG doesn't account for different time zones

### ISSUE THREAD

**Issue by nextlooper42** [jellyfin/jellyfin#6573]
**Describe the bug**
If you add for example Canadian iptv streams to Jellyfin and also add EPG source for them (source is from canada) and you live in for example Europe it will not account for different time zone and show EPG as that time zone, not Canadian.

Example: 
Show in Canada starts at 14:30 in Quebec (UTC-4).
This will show in Wien as 14:30 (currently UTC+2 Summer time), instead of 20:30

**System (please complete the following information):**
 - OS: W10 
 - Browser: FF 92
 - Jellyfin Version: 10.7.6

**To Reproduce**
1. Add IPTV stream
2. Add EPG source from that same country as IPTV stream
3. Live in different time zone
4. Be confused about weird EPG that doesn't match TV

**Expected behavior**
Be able to assign time zone to EPG for each channel, so it will recalculate the time to correct one.

**Comment by Artiume** [comment]
does the epg data show what time zone it's for?

**Comment by nextlooper42** [comment]
> 
> 
> does the epg data show what time zone it's for?

No, i don't know any _free_ that include that kind of information.

Tested with https://github.com/iptv-org/epg

**Comment by jedis00** [comment]
Has this been resolved?

**Comment by tompomdg** [comment]
For me unfortunately not.
