### ISSUE TITLE
Xbox Support

### ISSUE THREAD

**Issue by SirDragonClaw** [jellyfin/jellyfin#6585]
The Xbox version no longer works, why is this and how are people supposed to use jellyfin without Xbox support?

**Comment by crobibero** [comment]
The unfinished xbox client was archived quite a while ago. The only client that I know of is [Videotape](https://www.microsoft.com/en-us/p/videotape-a-modern-vlc-alternative/9nlvh2ll4p1z#activetab=pivot:overviewtab)

**Comment by cvium** [comment]
The Xbox One X/S has a browser and DLNA support.

**Comment by SirDragonClaw** [comment]
Using the Xbox controller to control its browser is a terrible experience imo.

**Comment by nielsvanvelzen** [comment]
You can try changing the "Display Mode"  to "TV" in in the display settings.
