### ISSUE TITLE
Changing season number in metadata results the files in that season being unplayable

### ISSUE THREAD

**Issue by dic1911** [jellyfin/jellyfin#6586]
**Describe the bug**
Changing season number in metadata results the files being unplayable.

**System (please complete the following information):**
 - OS: Linux
 - Virtualization: None
 - Clients: Only tested in browser and jellyfin media player, but all should be affected
 - Browser: [e.g. Firefox 91, Chrome 93, Safari 13]
 - Jellyfin Version: 10.7.7
 - FFmpeg Version: None?
 - Playback: Direct Play
 - Hardware Acceleration: none
 - Installed Plugins: AniDB
 - Reverse Proxy: none
 - Base URL: none
 - Networking: Any
 - Storage: local

**To Reproduce**

1. Use "Edit metadata" button on whatever season
    (in my case I have plenty of anime in library that only contains season 2 or newer, but Jellyfin marked it as season 1)
2. Change season number from 1 to the right number
3. Tries to play the video
4. Fails with "This client isn't compatible with the media and the server isn't sending a compatible media format." error.

**Expected behavior**

Nothing breaks after editing metadata.

**Comment by cvium** [comment]
You forgot the logs

![image](https://user-images.githubusercontent.com/675118/134128937-b090ddbf-74a6-4503-84e9-86bb71c3bf53.png)

**Comment by dic1911** [comment]
> You forgot the logs
Server doesn't output any log when the bug is being produced

**Comment by Cookie-Monster-Coder** [comment]
Same issue but I am not changing the season number. There are no errors. Nothing will play.

**Comment by dic1911** [comment]
Not 100% sure but it works fine on current version after setting season metadata for both video and the parent "folder".

Closing this issue until the bug comes up again.
