### ISSUE TITLE
Double quotes issue while recording from LiveTV

### ISSUE THREAD

**Issue by alexlo0** [jellyfin/jellyfin#6587]
**Describe the bug**
I have a LiveTV M3U tuner and XMLTV TV guide set up. When I try to record any TV programm with double quotes in it's name the issue occurs, i.e. ffmpeg fails. As I understood this happens 'cause of unescaped double quotes in cmdline while instantiating ffmpeg. Please check.

**System (please complete the following information):**
 - OS: Debian
 - Virtualization: LXC
 - Clients: Browser
 - Browser: Firefox 78.14.0esr
 - Jellyfin Version: 10.7.7-1
 - FFmpeg Version: 4.3.2-1-buster (Jellyfin)
 - Playback: none
 - Hardware Acceleration: none
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: none
 - Networking: Bridge
 - Storage: local

**Expected behavior**
Recording is done successfully.

**Server Logs**
[jellyfin20210921.log](https://github.com/jellyfin/jellyfin/files/7202336/jellyfin20210921.log)

**FFmpeg Logs**
[record-transcode-0eb4f792-501f-40aa-a116-7e3dffdef9eb.txt](https://github.com/jellyfin/jellyfin/files/7202335/record-transcode-0eb4f792-501f-40aa-a116-7e3dffdef9eb.txt)

**Comment by Bond-009** [comment]
Should be fixed by #6588
