### ISSUE TITLE
CUDA/NVDEC Hardware Acceleration not being applied to transcode command

### ISSUE THREAD

**Issue by dark-swordsman** [jellyfin/jellyfin#6606]
**Describe the bug**

When a stream that requires transcoding starts, hwaccel or decode flags are not applied to the ffmpeg command. This is with an HEVC 10-bit video (1080p and 4K) on a GTX 1070, which supports HEVC 10-bit decoding.

**System (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS Server
 - Virtualization: QEMU Linux KVM on Proxmox
 - GPU: EVGA GTX 1070 FTW 2
 - Clients:  Web
 - Browser: Chrome 93.0.4577.82
 - Jellyfin Version: 10.7.7
 - FFmpeg Version: 4.3.1-Jellyfin
 - Playback: Transcode
 - Hardware Acceleration: NVENC
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: none
 - Networking: Host (I'm not sure if this correct)
 - Storage: Boot is Linux LVM in Proxmox, video file is served via SMB

**To Reproduce**

1. Enable Nvidia NVENC hardware acceleration under Dashboard > Playback
2. Enable H264, HEVC, and all others under "Enable hardware decoding for"
3. Check "Enable 10-Bit hardware decoding for HEVC"
4. Check "Enable hardware encoding"
5. Click Save
6. Play video in Chrome browser that is HEVC 10 bit source
7. Transcoding works, but the ffmpeg log file doesn't show `-hwaccel` as a flag.

**Expected behavior**

Since the GTX 1070 supports HEVC 8, 10, and 12 bit decoding according to the NVIDIA Encode/Decode matrix, the ffmpeg command should include `-hwaccel` and the video should be decoded with NVDEC.

**Server Logs**

No log errors, but here is what it says about decoders, encoders, and hardware acceleration:
```
[2021-09-24 08:09:55.521 +00:00] [INF] Found ffmpeg version "4.3.1"
[2021-09-24 08:09:55.546 +00:00] [INF] Available "decoders": ["h264", "h264_qsv", "h264_cuvid", "hevc", "hevc_qsv", "hevc_cuvid", "mpeg2video", "mpeg2_qsv", "mpeg2_cuvid", "mpeg4", "mpeg4_cuvid", "msmpeg4", "vc1_qsv", "vc1_cuvid", "vp8_cuvid", "vp8_qsv", "vp9_cuvid", "vp9_qsv", "aac", "ac3", "flac", "mp3"]
[2021-09-24 08:09:55.556 +00:00] [INF] Available "encoders": ["libx264", "h264_amf", "h264_nvenc", "h264_qsv", "h264_v4l2m2m", "h264_vaapi", "libx265", "hevc_amf", "hevc_nvenc", "hevc_qsv", "hevc_vaapi", "mpeg4", "msmpeg4", "libvpx", "libvpx-vp9", "aac", "ac3", "flac", "libmp3lame", "libopus", "libvorbis", "srt"]
[2021-09-24 08:09:55.565 +00:00] [INF] Available hwaccel types: ["vdpau", "cuda", "vaapi", "qsv", "drm", "opencl"]
[2021-09-24 08:09:55.566 +00:00] [INF] FFmpeg: Custom: "/usr/lib/jellyfin-ffmpeg/ffmpeg"
```

**FFmpeg Logs**

No errors, but here is the command line example for one video:
```
/usr/lib/jellyfin-ffmpeg/ffmpeg -ss 00:16:06.000 -noaccurate_seek \
-i file:"/[1080p HEVCvideo].mkv" -map_metadata -1 -map_chapters \
-1 -threads 2 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_nvenc \
-pix_fmt yuv420p -preset fast -b:v 5547988 -maxrate 5547988 \
-bufsize 11095976 -profile:v:0 high -g:v:0 72 -keyint_min:v:0 72 \
-sc_threshold:v:0 0 \
-vf "scale=trunc(min(max(iw\,ih*dar)\,min(1920\,816*dar))/2)*2:trunc(min(max(iw/dar\,ih)\,min(1920/dar\,816))/2)*2" \
-start_at_zero -vsync -1 -codec:a:0 copy -strict -2 -copyts \
-avoid_negative_ts disabled -max_muxing_queue_size 4096 \
-f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts \
-start_number 322 \
-hls_segment_filename "/var/lib/jellyfin/transcodes/7c9fe8fafe4e929fe13c802d8557e6e6%d.ts" \
-hls_playlist_type vod -hls_list_size 0 -y "/var/lib/jellyfin/transcodes/7c9fe8fafe4e929fe13c802d8557e6e6.m3u8"
```

**Browser Console Logs**

No browser log errors.

**Screenshots**

**Additional context**

I have also tried without Tone Mapping, as well as turning off the advanced NVDEC checkbox.

I also tried a 1080p H264 8 bit source to see what would happen. It seems to have applied cuda hwaccel, but I don't believe it applied nvdec. Though, it managed only 10% CPU on 10 cores and was transcoding at about 400 FPS.

```
/usr/lib/jellyfin-ffmpeg/ffmpeg -hwaccel cuda -hwaccel_output_format cuda \
-extra_hw_frames 3 -autorotate 0 -i file:"/var/archive/.data/Movies/h264_8bit_movie.mkv" \
-map_metadata -1 -map_chapters -1 -threads 2 -map 0:0 -map 0:1 -map -0:s \
-codec:v:0 h264_nvenc -preset fast -b:v 2616000 -maxrate 2616000 \
-bufsize 5232000 -profile:v:0 high -g:v:0 72 -keyint_min:v:0 72 -sc_threshold:v:0 0 \
-vf "scale_cuda=w=1280:h=720:format=nv12" -start_at_zero -vsync -1 \
-codec:a:0 aac -ac 2 -ab 384000 -copyts -avoid_negative_ts disabled \
-max_muxing_queue_size 4096 -f hls -max_delay 5000000 -hls_time 3 \
-hls_segment_type mpegts -start_number 0 -hls_segment_filename "/var/lib/jellyfin/transcodes/faeebdfe492ed7caadcc1d7c0882c842%d.ts" \
-hls_playlist_type vod -hls_list_size 0 -y "/var/lib/jellyfin/transcodes/faeebdfe492ed7caadcc1d7c0882c842.m3u8"
```

**Comment by nyanmisaka** [comment]
Can you share the full ffmpeg log?

**Comment by dark-swordsman** [comment]
@nyanmisaka yep, here's a pastebin. Let me know if a different format works better.
https://pastebin.com/Gsgmfdru

**Comment by andreaskern** [comment]
I'm looking at the same problem
jellyfin is using the Lavc58.55.100 libx265 instead of cuda.
the problem should be arround this part in the EncodindHelper where it should add the hwaccel string but does not.

https://github.com/jellyfin/jellyfin/blob/b96dbbf553820861eab9d1a453adcc8ce8a9ef05/MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs#L3918

**Comment by dark-swordsman** [comment]
@andreaskern If it's using libx265, then that means it's _encoding_ the video with the CPU. I don't think this is directly related, unless you have enabled all the proper hardware acceleration options. 

Though, if you do, then it could be similar in how Jellyfin is just not applying the correct ffmpeg settings in general.

Also, for anyone else: Let me know if there's any other information I can provide.

**Comment by andreaskern** [comment]
What I see in the original post is that there is a `cuda` hardware accel type and the check in source is for `nvenc` (although we are checking for decoding capabilities). There is also the abbreviation `cuvid` which I can't figure out what it stands for and `nvdec` which does seem to be used anywhere.

I guess this is just a name mixup.

**Comment by dark-swordsman** [comment]
Yeah. `h264_cuvid` and `hevc_cuvid` are the decoders from my understanding. As you can see in this line:

```
Available "decoders": ["h264", "h264_qsv", "h264_cuvid", "hevc", "hevc_qsv", "hevc_cuvid", "mpeg2video", "mpeg2_qsv", "mpeg2_cuvid", "mpeg4", "mpeg4_cuvid", "msmpeg4", "vc1_qsv", "vc1_cuvid", "vp8_cuvid", "vp8_qsv", "vp9_cuvid", "vp9_qsv", "aac", "ac3", "flac", "mp3"]
```

**Comment by dark-swordsman** [comment]
Since I'm sure the main dev team is busy, is there any chance I can get some pointers as to where the code for this is (mainly whatever is determining the ffmpeg commands)? I don't really know C#, but I know JavaScript and my way around ffmpeg, so I wouldn't mind taking a crack at debugging this.

**Comment by nyanmisaka** [comment]
It's weird as the switch of NVDEC/CUVID decoder is almost controlled by user for the time being. And it's only disabled for H.264 10bit contents and when the ffmpeg binary provided by user is lacking of certain codec_cuvid decoder or cuda hwaccel type and related filters.

https://github.com/jellyfin/jellyfin/blob/53186c766bddf954483d7b40e385b382eabd0d8e/MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs#L3623

https://github.com/jellyfin/jellyfin/blob/53186c766bddf954483d7b40e385b382eabd0d8e/MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs#L115

**Comment by dark-swordsman** [comment]
I see now. I guess I missed it in the docs that `-hwaccel cuda` is part of NVDEC and does decoding. I didn't think CUDA cores were capable of decoding video. 

So in terms of H264 8-bit, hardware accelerated decoding is working I guess. But it is still strange that it doesn't work for HEVC videos, at least in Jellyfin calling the ffmpeg command.

Though, I just did a test, and I noticed that `cuda` did not work, but `nvdec` did.

cuda:
```shell
$ /usr/lib/jellyfin-ffmpeg/ffmpeg -hwaccel cuda -hwaccel_output_format cuda -i video-test/blends-s1e01-hevc.mkv -c:a copy -c:s copy -c:v h264_nvenc -preset slow -pix_fmt yuv420p h264_output.mkv

Impossible to convert between the formats supported by the filter 'Parsed_null_0' and the filter 'auto_scaler_0'
Error reinitializing filters!
Failed to inject frame into filter network: Function not implemented
Error while processing the decoded data for stream #0:0
Conversion failed!
```

nvdec:
```shell
/usr/lib/jellyfin-ffmpeg/ffmpeg -hwaccel nvdec -hwaccel_device 0 -i video-test/blends-s1e
01-hevc.mkv -c:a copy -c:s copy -c:v h264_nvenc -preset slow -pix_fmt yuv420p h264_output.mkv
```

**Comment by nyanmisaka** [comment]
‘-hwaccel nvdec’ is just a placeholder in ffmpeg. There are two ways to utilize Nvidia decoder and avoid copying data to memory.

-hwaccel cuda -hwaccel_output_format cuda -c:v hevc_cuvid -i file
-hwaccel cuda -hwaccel_output_format cuda -i file

The first one will use old cuvid decoder path and the second one use nvdec accelerator path. Both will output cuda surface.

-hwaccel cuvid is depreciated and replaced by -hwaccel cuda -hwaccel_output_format cuda. It uses nvidia parser instead of ffmpeg parser, results in some corrupted frames when decoding HDR contents.

Cuda accelerator is widely supported from Maxwell to the latest Ampere. Do not mix hw format with sw format. -pix_fmt yuv420p  should not be used in a zero copy pipeline. Cuvid built in resize function can be replaced by scale_cuda.

Seems that you are using an outdated jellyfin-ffmpeg. The latest one is 4.3.2-1.
