### ISSUE TITLE
jellyfin.org Document Settings cause Reverse Proxy 302 ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by SnailDove** [jellyfin/jellyfin#6610]
**Describe the bug**

As the title describes, "302 ERR_TOO_MANY_REDIRECTS in the context of Reverse Proxy settings in Nginx".

**System (please complete the following information):**
 - OS: Linux
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Chrome 93, Safari 13
 - Jellyfin Version: 10.7.7
 - Playback: [Direct Play, Remux, Direct Stream, Transcode] 
 - Hardware Acceleration: VAAPI
 - Installed Plugins:  Fanart etc.
 - Reverse Proxy: nginx
 - Base URL: /jellyfin
 - Networking: Bridge
 - Storage: local

**To Reproduce**

Open the URL on the browsers, `192.168.31.29/jellyfin/` (it's the IP of the server installed Nginx), it is directed to the URL `http://192.168.31.29/jellyfin/web/index.html` and ends on the following page
```
This page isn’t working192.168.31.29 
redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS
```

My Nginx proxy settings are pretty simple, according to the jellyfin.org [Documents](https://jellyfin.org/docs/general/networking/nginx.html#nginx-with-subpath-exampleorgjellyfin) and In the Jellyfin server Dashboard, the base URL has been set `/jellyfin`.
```txt
server {
        listen       80;
        listen       [::]:80;
        server_name  localhost;


        set $jellyfin 192.168.31.5;
        set $CalibreWeb 192.168.31.5;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;

        location / {
            root   html;
            index  index.html index.htm;
        }

        # it books
        location /itbooks {
                proxy_pass              http://$CalibreWeb:20000;
                proxy_set_header        Host            $http_host;
                proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header        X-Scheme        $scheme;
                proxy_set_header        X-Script-Name   /itbooks;
        }

       #jellyfin
        location /jellyfin {
            return 302 $scheme://$host/jellyfin/;
        }

        location /jellyfin/ {
            # Proxy main Jellyfin traffic
            # The / at the end is significant.
            # https://www.acunetix.com/blog/articles/a-fresh-look-on-reverse-proxy-related-attacks/     
            proxy_pass http://$jellyfin:17000/jellyfin/;

            proxy_pass_request_headers on;

            proxy_set_header Host $host;

            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host $http_host;

            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $http_connection;

            # Disable buffering when the Nginx proxy gets very resource-heavy upon streaming
            proxy_buffering off;
         }
        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

        # proxy the PHP scripts to Apache listening on 127.0.0.1:80
        #
        #location ~ \.php$ {
        #    proxy_pass   http://127.0.0.1;
        #}

        # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
        #
        #location ~ \.php$ {
        #    root           html;
        #    fastcgi_pass   127.0.0.1:9000;
        #    fastcgi_index  index.php;
        #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
        #    include        fastcgi_params;
        #}

        # deny access to .htaccess files, if Apache's document root
        # concurs with nginx's one
        #
        #location ~ /\.ht {
        #    deny  all;
        #}
 }
```
The other site, 'Calibre Web', it's reverse proxied well on the Nginx server and the `nginx.conf` is tested well.

**Expected behavior**

Open the URL, `192.168.31.29/jellyfin/`, it will be directed to the login page!
**Server Logs**

None

**Browser Console Logs**

Failed to load response data `/jellyfin/web/index.html`: No resource with given identifier found.

**Additional context**

On LAN, the browsers can access the Jellyfin server directly and it works well. But through the Reverse Proxy server, "Nginx", Not.

**Comment by Artiume** [comment]
```
location /jellyfin {
            return 302 $scheme://$host/jellyfin/;
        }

        location /jellyfin/ {
```
why both? It doesn't feel right

**Comment by SnailDove** [comment]
Add some additional context, if I configure the Nginx according to https://github.com/jellyfin/jellyfin/issues/1979#issuecomment-570965456 it works fine but as the jellyfin.org [Documents](https://jellyfin.org/docs/general/networking/nginx.html#nginx-with-subpath-exampleorgjellyfin) Not!
```txt
        #jellyfin

        location /jellyfin {
            return 302 $scheme://$host/jellyfin/;
        }

        location /jellyfin/ {
            # Proxy main Jellyfin traffic
            # The / at the end is significant.
            # https://www.acunetix.com/blog/articles/a-fresh-look-on-reverse-proxy-related-attacks/     
            proxy_pass http://192.168.31.5:17000/;  
            proxy_redirect default;
            proxy_redirect / /jellyfin/;  #  Important leaving the BaseUrl setting of the jellyfin server blank


            proxy_pass_request_headers on;

            proxy_set_header Host $host;

            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host $http_host;

            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $http_connection;

            # Disable buffering when the nginx proxy gets very resource heavy upon streaming
            proxy_buffering off;
        }
```

**Comment by SnailDove** [comment]
> ```
>         location /jellyfin {
>             return 302 $scheme://$host/jellyfin/;
>         }
> 
>         location /jellyfin/ {
> ```
> 
> why both? It doesn't feel right

It's right! This setting will ensure when input the URL `https://xxxx.com/jellyfin`, it will be directed to the `https://xxxx.com/jellyfin/`.

**Comment by sphaero** [comment]
This is happening with the documented apache reverse proxy settings as well

**Comment by sphaero** [comment]
Workaround by adding a redirect in apache for the initial login url and not using any base url in jellyfin:
```
Redirect /web/index.html /<BASEURL>/web/index.html
```

**Comment by sol8712** [comment]
This is still not fixed, the instructions in the docs do not work with nginx, this is wrong to close.

**Comment by CaptainXLAB** [comment]
I found a solution after 7 hours of investigating and searching "nginx jellyfin too many redirects" and went to a lot of pages too, found nothing...

Who wrote the docs for nginx config? Who decided to use a variable for no reason? Why hasn't this been found out or fixed yet?

That one decision to use a variable instead of the IPv4 directly - that was the problem for me.

Instead of
`set $jellyfin 192.168.1.100`
and then using
`proxy_pass http://$jellyfin:8096/jellyfin/`

remove the variable and directly put the IPv4 in `proxy_pass`
`proxy_pass http://192.168.1.100/jellyfin/`

I can finally access everything without problems. No more "too many redirects" errors. Finally.

Found no solutions anywhere so far so,
Hope this helps someone.

**Comment by Morikko** [comment]
I still had to apply https://github.com/jellyfin/jellyfin/issues/6610#issuecomment-927498410 on 10.8.10 to avoid too many redirects.

I only added `proxy_redirect default;` as `proxy_redirect / /jellyfin/;` would add it in double when the BaseUrl setting of the jellyfin server is also set.

**Comment by felix920506** [comment]
Hi, issues with the documentation should be directed to the jellyfin.org repo.
