### ISSUE TITLE
VPP Tone mapping too dark

### ISSUE THREAD

**Issue by Kekskruemel** [jellyfin/jellyfin#6624]
**Describe the bug**

Using VPP Tone mapping the picture is way too dark. Using OpenCL Tone mapping the picture ist correct.

**System (please complete the following information):**
 - OS: [e.g. Debian, Windows] Unraid
 - Virtualization: [e.g. Docker, KVM, LXC] Docker
 - Clients: [Browser, Android, Fire Stick, etc.] Android
 - Browser: [e.g. Firefox 91, Chrome 93, Safari 13] Android App
 - Jellyfin Version: [e.g. 10.7.6, unstable 20191231] 10.7.7
 - FFmpeg Version: [e.g. 4.3.2-Jellyfin] 4.3.2-Jellyfin
 - Playback: [Direct Play, Remux, Direct Stream, Transcode]  Transcode
 - Hardware Acceleration: [e.g. none, VAAPI, NVENC, etc.] Intel Quick Sync
 - Installed Plugins: [e.g. none, Fanart, Anime, etc.] none
 - Reverse Proxy: [e.g. none, nginx, apache, etc.] none
 - Base URL: [e.g. none, yes: /example] none
 - Networking: [e.g. Host, Bridge/NAT] Bridge
 - Storage: [e.g. local, NFS, cloud] SMB

**To Reproduce**

Start a Transcode with VPP Tone mapping enabled.

**Expected behavior**

Correct Brightness for the Movie. VPP Tone mapping is way too dark. You can't see anything in dark scenes.

**Server Logs**

Attached

**FFmpeg Logs**

Attached

**Screenshots**

https://imgur.com/G9CIxZK
[ffmpeg.txt](https://github.com/jellyfin/jellyfin/files/7236524/ffmpeg.txt)
[server.txt](https://github.com/jellyfin/jellyfin/files/7236549/server.txt)

**Comment by nyanmisaka** [comment]
AFAIK there is no fine-tuning options in VPP tonemapping filter. Please check the OpenCL tonemapping.

**Comment by Hukuma1** [comment]
Thank you for adding the options to make it brighter, @nyanmisaka for `10.8.1`!

The default setting of 0 still leaves it as dark as it was before. Is that the intended behavior? To match the software one, I had to put brightness gain to 10 (even though it says default should be left at 0). Not sure, but just a quick comparison with the naked eye.

**Comment by nyanmisaka** [comment]
> Thank you for adding the options to make it brighter, @nyanmisaka for `10.8.1`!
> 
> The default setting of 0 still leaves it as dark as it was before. Is that the intended behavior? To match the software one, I had to put brightness gain to 10 (even though it says default should be left at 0). Not sure, but just a quick comparison with the naked eye.

That’s intended for the time being. The default value will be changed when I received enough feedback. And FYI another OpenCL option is also hardware implementation but more compute intensive than VPP. We don’t do software tonemap.

**Comment by Hukuma1** [comment]
Ah, my apologies. Good to hear that VPP is less intensive. This works great now!

Let me know if there's anything I could provide to help you narrow down the default values for later.

**Comment by florensie** [comment]
Some of my findings.
With VPP tonemapping, no brightness gain:
![afbeelding](https://user-images.githubusercontent.com/13403842/222994146-a64683bc-a279-4e48-bf59-ab92689a2dab.png)

With OpenCL tonemapping:
![afbeelding](https://user-images.githubusercontent.com/13403842/222994335-31ba22cf-3b89-4e53-a571-92734a65adf3.png)

Native (direct play) with Jellyfin Media Player:
![afbeelding](https://user-images.githubusercontent.com/13403842/222994443-cb28b66d-c629-4248-bd93-69ff1ef13020.png)

With VPP, brightness gain set to 10 (suggested above). This is still darker compared to OpenCL/native. Also, as a side effect the black bars have also increased in brightness.
![afbeelding](https://user-images.githubusercontent.com/13403842/222994214-b7026284-3bfa-439d-8deb-dbd0ad6aa198.png)

**Comment by Feierkuula** [comment]
This command enables me to use opencl with QSV, for me, i was able to use hable algo for conversion HDR->SDR:

ffmpeg -analyzeduration 200M -init_hw_device vaapi=va:/dev/dri/renderD129,driver=iHD -init_hw_device qsv=qs@va -init_hw_device opencl=ocl@va -filter_hw_device qs -hwaccel qsv -hwaccel_output_format qsv -autorotate 0 -i usovDUt2Jhfwftn.mkv -map_metadata -1 -map_chapters -1 -vf "scale_qsv=w=1920:h=1080,hwmap=derive_device=opencl,tonemap_opencl=format=p010le:p=bt709:t=bt709:m=bt709:tonemap=hable:peak=100:desat=0,hwdownload" -pix_fmt p010le -vcodec av1_qsv test.mkv

in case if anyone needs it.
