### ISSUE TITLE
Can not access True NAS SMB shares 

### ISSUE THREAD

**Issue by elogreb** [jellyfin/jellyfin#6626]
I amruning Jellyfin as a WIndows service on a WIndows Server 2016. I can not include TrueNAS shares either over the LAN nor when they are mounted as network drives. I can not find a fix for this anywhere so I post here as a last resort..

WHen Jellyfin is instaled basic under my user account everythong works just fine...

**Comment by Artiume** [comment]
basic installation is preferred over advanced as running jellyfin as a service breaks hardware acceleration. what are you trying to accomplish by using the advanced installation? we've actually discussed removing it as it causes so many headaches
