### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by cipy** [jellyfin/jellyfin#6628]
**Describe the bug**

error NETSDK1045: The current .NET SDK does not support targeting .NET 6.0.  Either target .NET 5.0 or lower, or use a version of the .NET SDK that supports .NET 6.0. [~/work/jellyfin/tests/Jellyfin.Extensions.Tests/Jellyfin.Extensions.Tests.csproj]

Build FAILED.

**System (please complete the following information):**

Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster

 - OS: [e.g. Debian, Windows]
 - Virtualization: [e.g. Docker, KVM, LXC]
 - Clients: [Browser, Android, Fire Stick, etc.]
 - Browser: [e.g. Firefox 91, Chrome 93, Safari 13]
 - Jellyfin Version: [e.g. 10.7.6, unstable 20191231]
 - FFmpeg Version: [e.g. 4.3.2-Jellyfin]
 - Playback: [Direct Play, Remux, Direct Stream, Transcode] 
 - Hardware Acceleration: [e.g. none, VAAPI, NVENC, etc.]
 - Installed Plugins: [e.g. none, Fanart, Anime, etc.]
 - Reverse Proxy: [e.g. none, nginx, apache, etc.]
 - Base URL: [e.g. none, yes: /example]
 - Networking: [e.g. Host, Bridge/NAT]
 - Storage: [e.g. local, NFS, cloud]

**To Reproduce**

**Expected behavior**

**Server Logs**

**FFmpeg Logs**

**Browser Console Logs**

**Screenshots**

**Additional context**

**Comment by cvium** [comment]
Install the .net 6.0 rc1 SDK
