### ISSUE TITLE
BUG: Extras are scanned as movie, when movie directory has multiple video files

### ISSUE THREAD

**Issue by Dixin** [jellyfin/jellyfin#6630]
**Extras are scanned as movie, when movie directory has multiple video files. **

When movie directory has one single video file, its extras directory contents are correctly recognized as extras.

- some-movie-directory
  - featurettes
    - extra.mp4 <ins>=> Works correctly.</ins>
  - some-movie.mp4
  - some-movie.nfo
  - poster.jpg

When movie directory has multiple video files, its extras directory contents are incorrectly scanned as movies.

- some-movie-directory
  - featurettes
    - extra.mp4 <ins>=> Scanned as movie and shows in library.</ins>
    - extra.nfo <ins>=> Tried to delete this file. Not helpful. It will be regenerated.</ins>
    - poster.jpg
  - some-movie.EXTENDED.mp4
  - some-movie.EXTENDED.nfo
  - some-movie.EXTENDED-poster.jpg
  - some-movie.THEATRICAL.mp4
  - some-movie.THEATRICAL.nfo
  - some-movie.THEATRICAL-poster.jpg 

This bug presents for a long time. It is in the latest release too.

**System (please complete the following information):**
 - OS: Windows
 - Virtualization: none
 - Clients: Browser
 - Browser: Edge 93
 - Jellyfin Version: 10.7.7
 - FFmpeg Version: 
 - Playback: 
 - Hardware Acceleration: NVENC
 - Installed Plugins: 
 - Reverse Proxy: 
 - Base URL: none
 - Networking: Host
 - Storage: local

**Comment by Dixin** [comment]
This bug still exists.

**Comment by cvium** [comment]
I am not sure this exists in the 10.8 alpha

**Comment by ZigMeowNyan** [comment]
I'm on 10.8.7 and this happens to me. What's more, it also occurs with extras using suffixes directly in the movie directory instead of in extras subdirectories.

It's a huge hindrance to having movie folders with multiple cuts and extras in them.
