### ISSUE TITLE
Problem with SSL certificate since DST Root R3 expiration

### ISSUE THREAD

**Issue by davidcheeeese** [jellyfin/jellyfin#6634]
Hello, I got a problem to connect Jellyfin server with some client since DST Root R3 certificate expiration, on a system using Let's Encrypt certificate renewed with certbot.
I'm still able to connect from Opera browser on Linux, Firefox on Android 11, but not from Jellyfin android client, Gelli client or Opera on android 11

**System (please complete the following information):**
 - OS: Archlinux
 - Clients: Jellyfin Android, Gelli
 - Jellyfin Version: 10.7.5
 - Reverse Proxy: none
 
**To Reproduce**
- Generate a lets encrypt certificate with certbot (on nginx)
- Use openssl to create a pfx version.
- Start jellyfin server, produce the logger error message.
- Jellyfin android client or Gelli are not able to connect, Opera or Firefox on Linux still able to connect Jellyfin server.

**Expected behavior**
Be able to connect from Gelly or Jellyfin Android client

**Server Logs**
jellyfin[22871]: System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
jellyfin[22871]:  ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: NotTimeValid
jellyfin[22871]:    at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
jellyfin[22871]:    at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
jellyfin[22871]:    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
jellyfin[22871]:    --- End of inner exception stack trace ---
jellyfin[22871]:    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
jellyfin[22871]:    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
jellyfin[22871]:    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
jellyfin[22871]:    at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
jellyfin[22871]:    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
jellyfin[22871]:    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
jellyfin[22871]:    at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
jellyfin[22871]:    at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
jellyfin[22871]:    at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
jellyfin[22871]:    at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationT>
jellyfin[22871]:    at System.Net.Http.Json.HttpClientJsonExtensions.GetFromJsonAsyncCore[T](Task`1 taskResponse, JsonSerializerOptions options, CancellationToken cancellationToken)
jellyfin[22871]:    at Emby.Server.Implementations.Updates.InstallationManager.GetPackages(String manifestName, String manifest, Boolean filterIncompatible, CancellationToken cancellationToken)

**Additional context**
Tested the cerficate chain with https://www.geocerts.com/ssl-checker considered as valid.

Certificate Chain Complete?
All of the correct Intermediate CA Certificates are installed. Your SSL certificate is installed correctly and should be supported in all the major web browsers without problems.

certificate	
Common Name:DST Root CA X3
Organization: Digital Signature Trust Co.
Valid: September 30, 2000 to September 30, 2021
Issuer: DST Root CA X3

certificate intermediate	
Common Name:R3
Organization: Let's Encrypt
Valid: October 07, 2020 to September 29, 2021
Issuer: DST Root CA X3

certificate intermediate	
Common Name:domain.name
Organization:
Valid: September 30, 2021 to December 29, 2021
Issuer: R3

**Comment by crobibero** [comment]
This is not a Jellyfin issue. See https://www.reddit.com/r/jellyfin/comments/pybpau/lets_encrypt_users_take_note/ for more information.

**Comment by tjharman** [comment]
@crobibero Turns it was a Jellyfin issue: https://github.com/jellyfin/jellyfin/issues/6650

**Comment by devlin016** [comment]
why dont the repo admins do wordaround #3 listed on https://www.openssl.org/blog/blog/2021/09/13/LetsEncryptRootCertExpire/ . I doubt anything that old is running a jellyfin server.
