### ISSUE TITLE
SortTitle can not be ignored and is scraped 

### ISSUE THREAD

**Issue by an0Nym0us63** [jellyfin/jellyfin#6635]
**Describe the bug**
SortTitle is scraped when a new media is added. And i guess it is maybe created by jellyfin as i can't find any sortitle field on tmdb. The issue (and quite annoying issue) is tthat we cant tell jellyfin not to do that. And the sort title is based on the original title. So as a french guy, sorting by name results in a complete mess unless i go one by one remove the sort title tag in the metadatas of each imported movie.

**System (please complete the following information):**
 - OS: [Debian]
 - Virtualization: no
 - Clients: only a server issue
 - Jellyfin Version: 10.7.7
 - FFmpeg 4.3.2-Jellyfin
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: none
 - Storage: moutn nfs

**To Reproduce**
Lets imagine you are all configured to scrape French metadata
Have a movie let's imagine The Autopsy of Jane Doe (in french the name is The Jane Doe Identity)
Scan medias

**Expected behavior**
Expects to have 

title : The Jane Doe Identity
original title : The Autopsy of Jane Doe

and no sort title

And i have autopsy jane doe as a sort title which messes for a french guy. And this happens for every movie the sorttitle seems to be forced upon the original title and not the language title

**Screenshots**
![image](https://user-images.githubusercontent.com/2008029/135468534-b0166f23-13a1-4dfe-a464-dba3258297c7.png)

**Comment by KevoM** [comment]
Same issue here. Sort titles come from Radarr.
I try to replace all metadatas by triggering the Jellyfin rescan with the replace option, but sort titles stay in English.

It's not based on original titles but on english titles.

screenshot 1. English movie, french translated title for display > the movie is sorted with the english title
<img width="1071" alt="Capture d’écran 2022-05-23 à 10 54 11" src="https://user-images.githubusercontent.com/8274366/169782983-7e942c2e-7976-4c08-87f2-30e4b61d298f.png">

screenshot 2. French movie, english translated title > the movie is sorted with the english title
<img width="1073" alt="Capture d’écran 2022-05-23 à 10 55 13" src="https://user-images.githubusercontent.com/8274366/169783022-14f9d0a7-8408-4036-9b3c-31d256fd5648.png">
