### ISSUE TITLE
HDD / LAN copy performance issues during Library scan 

### ISSUE THREAD

**Issue by FrankBKK** [jellyfin/jellyfin#6637]
I run Plex and Jellyfin concurrently on the same PC - mediafiles are on drive d: - both JF and Plex are doing a full library scan. 

In the meantime when copying a large set of files (>1GB/file) from this drive to a NAS the transfer rate drops from >100MB/s to <10MB/sec

I understand that some performance is lost with an ongoing scan but these numbers seem a bit unusual so I played around with plex and JF - turning the scan off, shutting plex down, shutting JF down etc. 

Turns out that JF is  responsible for these transfer speed drops - when I shutdown JF (while Plex still scanning) the rates go back up immediately. Stopping the Scan on JF only seems to have no effect - only shutdown helps.

 - OS: Windows 10
 - Virtualization: none 
 - Clients: any 
 - Browser: any
 - Jellyfin Version: 10.7.7
 - FFmpeg Version: current
 - Playback: none
 - Hardware Acceleration: none
 - Installed Plugins: Fanart, Reports
 - Reverse Proxy: none
 - Networking: local LAN
 - Storage: local

**Comment by michael9dk** [comment]
This could be the generation of thumbnails from videos.
