### ISSUE TITLE
4k HEVC HDR/DolbyVision dont work via Direct streaming and transcodes instead

### ISSUE THREAD

**Issue by averageguyoriginal** [jellyfin/jellyfin#6640]
**Describe the bug**

on my new android tv that supports 4k hevc dolby vision and hdr with mkv file support, jellyfin always plays the videos in transcoding insteads of direct streaming. but when i use emby on it it work just fine with direct streaming. is there any specific settings i need to change for it to direct stream lke emby? or the jellyfin itself doesnt support it? also some hevc 1080p videos also dont direct play while some do.

EDIT:- i found online to do some settings so it doesnt transcode but theres still a problem. when it plays dolby vision video it doesnt show colors normally instead it shows colors like i m playing on a non dolby vision tv. But my tv is dolby vision suported and i played with emby and it works fine. only playing in jellyfin in direct or transcode mode it still doesnt show colors as normal.

**Comment by KSOYU** [comment]
hevc格式的视频都没有办法正常播放，都会异常卡顿。解决方法好像有，进设置里面。用户。把播放需要转码的视频勾掉就行。那依然可以硬件转码。别的视频又转不码了

**Comment by thisisawesome1994** [comment]
I have this issue still.

**Comment by cmbarba** [comment]
I'm also experiencing this issue. 2160p SDR and HDR10 direct play, but Dolby Vision always transcodes. The dashboard says "The number of audio channels is not supported", but looking at the logs it looks like the audio is direct streaming and the video is being transcoded:

Stream mapping:
  Stream #0:0 -> #0:0 (hevc (native) -> hevc (hevc_nvenc))
  Stream #0:2 -> #0:1 (ac3 (native) -> ac3 (native))

I'm able to direct play the same Dolby Vision content on the same TV using Plex.

I'm on server 10.8.0beta2 and watching on Android TV 0.13.3.

**Comment by Shadowghost** [comment]
Your logs imply that audio and video are transcoded (otherwise there would be `(copy)`  instead of `(ac3 (native) -> ac3 (native))`.

Even though video should not be transcoded if only audio is unsupported...

**Comment by cmbarba** [comment]
> Your logs imply that audio and video are transcoded (otherwise there would be `(copy)` instead of `(ac3 (native) -> ac3 (native))`.
> 
> Even though video should not be transcoded if only audio is unsupported...

Thanks for the clarification, I don't really know how to read the logs.

I've tried another video file that I know is only HDR10 and which uses TrueHD audio which I know my setup doesn't support. The Stream mapping from the log output is as follows:
```
  Stream #0:0 -> #0:0 (hevc (native) -> hevc (hevc_nvenc))
  Stream #0:1 -> #0:1 (truehd (native) -> ac3 (native))
```
It seems that Jellyfin always transcodes both video and audio if any transcoding is needed. Again for reference I tried it in Plex and only the audio is transcoded while the video is direct streamed.

**Comment by Shadowghost** [comment]
This is a known bug in 10.7.7 but should not happen in 10.8 beta so it's weird that you're having this problem.

I'm not sure if we currently check for HDR compatibility if we transcode, it's quite possible that HDR only works if direct played.

**Comment by cmbarba** [comment]
The Dolby Vision video that I initially described in my [first comment](https://github.com/jellyfin/jellyfin/issues/6640#issuecomment-1117010667) had a TruHD audio track as its default track, which needed transcoding. If I switched to the second audio track, a compatibility track, it still transcoded. I just tried a different Dolby Vision video, this time one with only a single audio track that I know is supported. This time I received the following popups on my TV:

`Player errors encountered. Will re-try`

and

`Too many errors. Giving up`

I don't see an ffmpeg log, but in the general log I can see where it tries to play it (The Transformers Movie). See attached
[Log File](https://github.com/jellyfin/jellyfin/files/8624825/DVlog.txt).

**Comment by jivanpal** [comment]
The issue of video being transcoded unnecessarily when only audio needs transcoding is still present in 10.8.1, but apparently fixed by #8078, so this issue will presumably also be fixed in 10.8.2 once it is released.

**Comment by Vinu-Suhas** [comment]
even in my macbook pro m1 dolby vision files have green or purple tint ,while HDR is fine.Please fix this issue ASAP

**Comment by mastra90** [comment]
Same thing still happening to me in Jan 2023... Purple muck when streaming DV content in MKV on a LG C2

**Comment by Vinu-Suhas** [comment]
Btw the Green/purple muck is there even in **mp4** in my macbook(native app) .I have also heard that if you insert a hard drive to LG tv it would directly play only mp4 dolby vision files would work .
Also note that all **greenn/purple issue is gone** in **safari** browser ,although in playback info it displays as remuxing

**Comment by Delicates** [comment]
4K HEVC HDR/DolbyVision plays fine for me on SONY with Android TV client v0.15.11 and server v10.8.10.
Key things:
* In Jellyfin client select ExoPlayer as the Preferred media player (libVLC doesn't support DV).
* In Jellyfin server for each Library Folder configure the Shared Network Folder path to allow client to bypass the server completely during playback by accessing files directly via a network share.

Works like a charm.

The only thing I wish is for Jellyfin to identify video types as "HDR10", "HDR10+" and "DV", instead of just "HDR".
Also would've been nice to have an option for the client to show real-time playback info about source/transcode/playback formats.

**Comment by Shadowghost** [comment]
`The only thing I wish is for Jellyfin to identify video types as "HDR10", "HDR10+" and "DV", instead of just "HDR".` - This is already exposed via mediainfo, just not used for creating the version/track string used by the clients.

`Also would've been nice to have an option for the client to show real-time playback info about source/transcode/playback formats.` - JF-Web already has it, it depends on the client.

**Comment by Delicates** [comment]
> `The only thing I wish is for Jellyfin to identify video types as "HDR10", "HDR10+" and "DV", instead of just "HDR".` - This is already exposed via mediainfo, just not used for creating the version/track string used by the clients.

Yes, I'm talking about exposing HDR type via version/track string used by the clients.
Here's an example of Media Info:
![image](https://github.com/jellyfin/jellyfin/assets/5669128/878cd6d6-1414-4b35-a27c-c677ef6fc680)

The first highlighted field is used by the clients, and that's where I wish HDR type was reflected.
I think the second highlighted field is where HDR type is supposed to be stored internally:

https://github.com/jellyfin/jellyfin/blob/9de667f8ce92ee575da8b278490fe5cafff8c6ed/Jellyfin.Data/Enums/VideoRangeType.cs

But as you can see in the screenshot, even here it is not identifying media as DV, despite knowing that it is DV as per fields below it.

**Comment by nwgat** [comment]
> Same thing still happening to me in Jan 2023... Green/purple muck when streaming DV content in MKV on a LG C2. Tested it with MP4 and it works. Plex has the exact same issue funnily enough.

on my C2, its more random, sometime it works in HDR  Mode sometimes in Dolby Vision Mode

Chromecast with Google TV 4K + LG C2 (2022)
