### ISSUE TITLE
IPTV with series : series category is empty

### ISSUE THREAD

**Issue by kornflex** [jellyfin/jellyfin#6643]
Hello,

My iptv m3u file contains movies and series.

I can see my TV channel but in the serie category, it's empty.

How jellyfin add things in this category ? My m3u file need to be formatted with specific tags ?
Same thing for movies ? How can I add them ?

I don't see help in wiki :/

If it's not possible, could you please add this to your roadmap ?
It would be great to have jellyfin fully compatible with xstream code IPTV. Jellyfin would be able to get live TV channels, EPG and VOD without using  xteve to filter tv channel etc...

Thank you

**Comment by myhrmans** [comment]
Same problem here. Did you manage to solve this?

**Comment by kornflex** [comment]
I used a workaround : create strm files
This my project, fork : https://github.com/kornflex/iptv-strmmaker

**Comment by srcrist** [comment]
Closing this issue as it does not reference a Jellyfin bug. The category information is provided by the XML data from your Live TV provider.
