### ISSUE TITLE
Admin user broke after update

### ISSUE THREAD

**Issue by Xyz00777** [jellyfin/jellyfin#6645]
**Describe the bug**
I updatet my server from 10.6.2 to 10.7.7

**System (please complete the following information):**
 - OS: Ubuntu Server 20.03 LTS
 - Virtualization: VM Virtualized on proxmox
 - Clients: not depending but used opera and chrome
 - Jellyfin Version: 10.7.7 stable
 - Reverse Proxy: im using from outside nginx but also happened inside the network

**To Reproduce**
1. install "new" apt key to can update your server from the old version to the new :D
2. update the server and restart it
3. try to login with an admin user and fail with an error: "MessageUnauthorizedUser"

**Expected behavior**
Im should be able to login without problems with my user

**Server Logs**
sorry web terminal photo only
![nRo1xP3KDP](https://user-images.githubusercontent.com/52142054/135621634-3cd7521e-755e-4cda-9814-e152ad498ad3.png)

**Browser Console Logs**
?

**Additional context**
so what happend and what i done:
i updated the apt keys and after that i updated my server. after that i wanted to login with my admin user but couldnt because i got the error message "MessageUnauthorizedUser" after a few times i thought the user could be locked out (even when i didnt activated it). Because of that I i searched and found 2 things i could try:
1. go into the user policy.xml and reenable the user by setting a false by userisdisabled
2. restart the initialization wizard in /etc/jellyfin/system.xml and reset the passwort or a new user
I Tried out both thinks. I couldnt done the first because the user wasnt disabled... The Second didnt worked either (same error as above)
I even tried to give my normal user admin privilges inside his system.xml config but these didnt worked. I still can login with the user but he get no admin. (Side Info after everything i tried i restart the server every time, in mean time i already restartet the server around 10 times or so :D ) 
Normal users still can login without problems, i was just confused that i have around 10 users inside jellyfin but in /etc/jellyfin/users are only 4 folders is these another bug?.

Did i miss anything? or do you have any other ideas?
Hope you can help me.
Greetings

**Comment by cvium** [comment]
You cannot edit the userpolicy anymore. The disabled state of a user is now in the `jellyfin.db` database file. You can enable a user by executing this query `update Permissions set Value = 0 where UserId in (select Id from Users where username = '<INSERT USERNAME>')`

**Comment by Xyz00777** [comment]
@cvium thanks for the information. i found the jellyfin.db but dont know how to send the query, it would be really helpful if you dont only say me what query i should use but also how to user it :D

greetings

**Comment by cvium** [comment]
If you have a gui then https://sqlitebrowser.org/ otherwise use sqlite3 cli `sqlite3 <path to db>` and then run the query

**Comment by cvium** [comment]
Is there a permissions table?

**Comment by cvium** [comment]
What is the query you ran? Did you copy mine?
