### ISSUE TITLE
Chosen audio track suboptimal on Chrome

### ISSUE THREAD

**Issue by brianjmurrell** [jellyfin/jellyfin#6655]
**Describe the bug**
When playing media on Chrome that has both an AAC media track as well as a surround sound track such as AC3, the AAC track is not chosen by default, incurring an unnecessary transcode at playback time.

Additionally, the audio track selector shows _Default_ for all tracks.

**System (please complete the following information):**
 - OS: Linux
 - Virtualization: None
 - Clients: Browser
 - Browser: Chrome 93.0.4577.82 (Official Build) (64-bit)
 - Jellyfin Version: 10.7.7
 - FFmpeg Version: N/A
 - Playback: Direct, with suboptimal transcode of audio -- which this issue is about
 - Hardware Acceleration: none
 - Installed Plugins: N/A
 - Reverse Proxy: none
 - Base URL: none
 - Networking: native
 - Storage: local

**To Reproduce**

1. Obtain or create media with both an AC3 track as well as AAC track
2. Play media in Chrome from Jellyfin
4. Observe in playback data that the original is AC3 and that the track playing is AAC.  Also observe in the track list that the AC3 track is being played.  Also observe on the Jellyfin server an unnecessary ffmpeg running to transcode the audio.
5. Choose the AAC native track from the player
6. Observe all of the nasty behaviour from #4 above is gone.

**Expected behavior**
Should automatically choose the AAC track
Also, should not show _Default_ on every track in the track list

**Server Logs**
N/A

**FFmpeg Logs**
N/A

**Browser Console Logs**
N/A

**Screenshots**
Default playback without explicitly selecting an audio track:
![image](https://user-images.githubusercontent.com/559317/135755160-f97b7e9c-4562-403a-bf5f-9966a9dab77b.png)

Available tracks:
![image](https://user-images.githubusercontent.com/559317/135755185-5aab69c5-318c-4aad-adb2-cb6946a4b6e1.png)
(Notice how both say _Default_, as an aside)

Playback data when AAC track is explicitly chosen:
![image](https://user-images.githubusercontent.com/559317/135755237-f04feb55-6571-4d98-9c1f-0d19131f6126.png)

**Additional context**
None

**Comment by Shadowghost** [comment]
Except the fact that the default track is the intended track to be played alongside the video we don't know what the other tracks are meant for.

Automagically choosing the track based on best compatibility and language could lead to e.g. using a commentary track. If the track languages aren't properly tagged this could also lead to choosing a track with a totally different language than the intended one on movies with more than one audio language.

I understand why choosing the most compatible track may seem like a good idea but I think it'd lead to way more problems than it solves.

**Comment by Artiume** [comment]
For 10.8 (or Jellyfin Media Player), we have an algorithm for selecting the best audio or subs. Try it to see if you think this bug is still an issue.

https://github.com/jellyfin/jellyfin-web/pull/2621

**Comment by brianjmurrell** [comment]
> Except the fact that the default track is the intended track to be played alongside the video we don't know what the other tracks are meant for.

Ahhh.  So are you saying that all tracks that are just different encodings (6ch, 2ch, etc.) of the actual sound track will all say _Default_ and that it's not intended that _Default_ to be applied to just one those different encodings of the same track?

> Automagically choosing the track based on best compatibility and language could lead to e.g. using a commentary track.

Yes, if my understanding of what you are saying above is correct.  So my desired behaviour then is to automatically choose, among the different tracks marked as _Default_, the one that is encoded to match the output hardware.

> For 10.8 (or Jellyfin Media Player), we have an algorithm for selecting the best audio or subs. Try it to see if you think this bug is still an issue.
> 
> [jellyfin/jellyfin-web#2621](https://github.com/jellyfin/jellyfin-web/pull/2621)

Am I misunderstanding that this only affects multiple media items played one after another and has no benefit to the first/initial item played?

**Comment by Artiume** [comment]
Correct, so it's for Shows and not movies. I personally encode the stereo track first and the 5.1 second so you have to manually select the 5.1 if you want surround sound. There really isn't a good way to 'assume' what is the best track to play. Based on experience, the stereo tracks that are listed last are typically the commentary tracks. I feel like if we tried to make Jellyfin smarter than it really is, it would cause people to complain about audio preference because of odd-case encoded media.
