### ISSUE TITLE
Prevent Windows from going to sleep with active streams

### ISSUE THREAD

**Issue by wesleylancel** [jellyfin/jellyfin#6658]
Jellyfin doesn't seem to keep Windows awake when it's actively streaming to remote clients causing it to go to sleep because of inactivity. Similar software (Plex) makes sure it stays awake when streaming.

**Comment by nielsvanvelzen** [comment]
https://features.jellyfin.org/posts/581/prevent-os-from-sleeping-hibernating-while-streaming
