### ISSUE TITLE
Detection of s/pdif audio passthrough

### ISSUE THREAD

**Issue by dmyourthesis** [jellyfin/jellyfin#6660]
**Describe the bug**
Detect the presence of a s/pdif passthrough on a sink(TV/projector), and transcode the audio to the supported formats (dts,ac3)

**System (please complete the following information):**
 - Clients: AndroidTV 0.12, Roku Beta Version 1.4 build 9
 - Jellyfin Version: 10.7.7
 - Playback: [Direct Play, Remux, Direct Stream, Transcode] yes

**To Reproduce**

1. Use the Jellyfin app on either an AndroidTV or Roku directly connected to a TV via HDMI and with a receiver connected to the TV via s/pdif.
2. Play any file with more than 2 channels of audio that is not already encoded in ac3 or dts
3. The audio stream that reaches the audio receiver is stereo (PCM, I think)

**Expected behavior**

3. Client detects s/pdif interface
4. Tells server to transcode the audio to ac3 5.1 or dts 5.1

or

1.5. Server/app setting that forces the desired transcode
4. Server transcodes all audio tracks with more than 2 channels into AC3 or DTS if not already.

**FFmpeg Logs**

This is the desired log that occurs when using Kodi.
[jellyfinkodilog.txt](https://github.com/jellyfin/jellyfin/files/7275155/jellyfinkodilog.txt)
I tried to get logs for the Roku and AndroidTV app, but they direct played the same file and its aac 5.1 and 7.1 audio track, which ended up a stereo pcm on my receiver.

**Additional context**

I have had three workarounds to this problem, one tedious, one no longer working, and Kodi.
Tedious is pre-transcoding all content as the apps seem to handle audio that is already in ac3 or dts in a favorable manner.
Use the Emby client and signal playback problems until it had the desired behavior. (No longer working)
Kodi app on the androidTV using this set-up: 
In the Kodi settings---Channels=2.0 Allow passthrough = On; AC3 capable receiver = On; DTS capable = on
In the Kodi Jellyfin add-on settings---Force Transcode = On; Preferred audio codec = AC3; Audio bitrate= 320; Audio max channels = 6

**Comment by dieplanes789** [comment]
This is still an issue. My entire library is now stuck down mixing to stereo ruining the dialogue from the center channel.
