### ISSUE TITLE
Switch to TagLib for scanning of music files

### ISSUE THREAD

**Issue by nvllsvm** [jellyfin/jellyfin#667]
The current scanning uses ffprobe and is quite slow. My library 180GB MP3 (16,431 tracks) is taking well over an hour to scan. I suspect that [TagLib](https://github.com/mono/taglib-sharp/) would be able to scan the metadata more efficiently - especially considering that Python and Mutagen were able to scan the whole library in under 5 minutes and thus showing that the bottle neck is clearly in the software.

**Comment by EraYaN** [comment]
Does TagLib support the media types, cant' really find much? Otherwise we might need MediaInfo or something similar to get this info. [Example wrapper](https://github.com/StefH/MediaInfo.DotNetWrapper) That could be used for video scanning as well though.

**Comment by JustAMan** [comment]
This requires having a `mediainfo.dll` for all OSes, introducing another native dependency except `ffmpeg` (though the idea itself looks worth exploring).

**Comment by EraYaN** [comment]
Mmm I think the biggest challenge would be the ARM targets.
