### ISSUE TITLE
Poor Order of Cast

### ISSUE THREAD

**Issue by seniorm0ment** [jellyfin/jellyfin#6684]
Metadata always grabs cast in a poor order it seems. It displays it randomly, instead of main characters first, and so on. 

Jellyfin 10.7.7
Windows 10

**Comment by seniorm0ment** [comment]
relevant

**Comment by sevenrats** [comment]
please create a feature request at features.jellyfin.org or an issue in the appropriate client repo.

**Comment by srcrist** [comment]
Possible duplicate of https://github.com/jellyfin/jellyfin/issues/9966. Unable to replicate this issue.
