### ISSUE TITLE
[bug] Latest TV Shows shown multiple times on homepage

### ISSUE THREAD

**Issue by t0m-As** [jellyfin/jellyfin#6685]
**Describe the bug**
TV Shows type of library. When one show spreaded across multiple folders in root folder, the" Lastest shows" on main screen shows the same show more times. Library "merge shows split across folder" is enabled, and in "TV shows" library is showed only once. 

/share/Series/ Directory tree: 
/911.la.S01
/911.la.s02
/better.call.saul.S01
/better.call.saul.s02

so in "Latest" i have 2 times 911 and 2 times Better Call Saul

**System**
 - OS: NAS, ADM 3.5.7.RKU2
 - Virtualization: Docker
 - Clients: Browser, Andriod app
 - Browser: any
 - Jellyfin Version: 10.7.7, stable, clean install
 - Installed Plugins: base
 - Networking: Bridge

**To Reproduce**
Make directories by seasons.

**Expected behavior**
"Latest TV shows" shows only 1 item/series.

**Server Logs**
[Log.txt](https://github.com/jellyfin/jellyfin/files/7321046/Log.txt)

**Screenshots**
File tree on disk: 
![filetree](https://user-images.githubusercontent.com/92298950/136762997-13d70914-9557-4627-931a-c9be467d968a.JPG)

Enabled merge: 
![merge_enabled](https://user-images.githubusercontent.com/92298950/136763450-ba2d8abd-259a-480e-ba53-d1134cc70d4d.JPG)

Homepage with more items: 
![latest_homepage](https://user-images.githubusercontent.com/92298950/136763468-a441aa5a-03ed-44a7-bd6c-72f77b819719.JPG)

Library with correctly showed 1 item only: 
![tvshow_library_ok](https://user-images.githubusercontent.com/92298950/136763476-fe8f0085-947c-45a1-8f84-7270f6dc794e.JPG)

**Comment by krutburken** [comment]
Documentation (https://jellyfin.org/docs/general/server/media/shows.html) describes how to organize your shows. The way you're doing it probably just isn't supported.
