### ISSUE TITLE
Thumbnails randomly not showing

### ISSUE THREAD

**Issue by hasezoey** [jellyfin/jellyfin#6693]
**Describe the bug**
Sometimes when going between pages, the previews / thumbnails randomly dont show

**System (please complete the following information):**
 - OS: Ubuntu Server 21.04 (Jellyfin server), Manjaro 21.1.4 Firefox (Client)
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Firefox 93
 - Jellyfin Version: Jellyfin Docker 10.8.0 (`jellyfin/jellyfin:unstable@sha256:c2bd230f4425e8bb7f95f6f9a18f1aa9589ffa062173c47a871da524e16c3154`)
 - FFmpeg Version: Whatever is in the docker by default
 - Playback: Not applicable to this issue
 - Hardware Acceleration: Not applicable to this issue
 - Installed Plugins: MusicBrainz
 - Reverse Proxy: nginx
 - Base URL: yes, Not applicable to this issue
 - Networking: Docker (Host)
 - Storage: Local (Docker bind mount)

**To Reproduce**
it can be reproduced by many steps, but the most noticeable to me was:

1. go to home page
2. enter some library
3. enter some entity (like a song, album, artist id, movie, etc)
4. go back with the browser `Back` button or the mouse back button
5. observe sometimes not loading thumbnails

**Expected behavior**

**Server Logs**

**Browser Console Logs**

<details>
<summary>Firefox 93 console log</summary>

```txt
setting page base to /web main.jellyfin.bundle.js:2:12188
Stored JSON credentials: {"Servers":[{"DateLastAccessed":1634039900528,"LastConnectionMode":2,"ManualAddress":"https://jellyfin.sylvi","manualAddressOnly":true,"Name":"sylvi","Id":"0411b444f3724b91bc87f05bbbb2b883","LocalAddress":"http://192.168.2.6:8096","AccessToken":"3849050a0afc4fca94fad166a447d78b","UserId":"1cb49d64ac50431daf0f9a7260fcbc77"}]} main.jellyfin.bundle.js:2:786418
Begin ConnectionManager constructor main.jellyfin.bundle.js:2:776166
Translation dictionary is empty. 4 main.jellyfin.bundle.js:2:345096
ApiClient serverAddress: https://jellyfin.sylvi main.jellyfin.bundle.js:2:713085
ApiClient appName: Jellyfin Web main.jellyfin.bundle.js:2:713138
ApiClient appVersion: 10.8.0 main.jellyfin.bundle.js:2:713185
ApiClient deviceName: Firefox main.jellyfin.bundle.js:2:713235
ApiClient deviceId: TW96aWxsYS81LjAgKFgxMTsgTGludXggeDg2XzY0OyBydjo5Mi4wKSBHZWNrby8yMDEwMDEwMSBGaXJlZm94LzkyLjB8MTYzMTg4OTE5MzgwMQ11 main.jellyfin.bundle.js:2:713285
returning instance from getOrAddApiClient main.jellyfin.bundle.js:2:780362
defining core routes main.jellyfin.bundle.js:2:1141613
URL candidates: 
Array [ "https://jellyfin.sylvi" ]
main.jellyfin.bundle.js:2:331405
creating ApiClient singleton main.jellyfin.bundle.js:2:2244
ApiClient serverAddress: https://jellyfin.sylvi main.jellyfin.bundle.js:2:713085
ApiClient appName: Jellyfin Web main.jellyfin.bundle.js:2:713138
ApiClient appVersion: 10.8.0 main.jellyfin.bundle.js:2:713185
ApiClient deviceName: Firefox main.jellyfin.bundle.js:2:713235
ApiClient deviceId: TW96aWxsYS81LjAgKFgxMTsgTGludXggeDg2XzY0OyBydjo5Mi4wKSBHZWNrby8yMDEwMDEwMSBGaXJlZm94LzkyLjB8MTYzMTg4OTE5MzgwMQ11 main.jellyfin.bundle.js:2:713285
loaded ApiClient singleton main.jellyfin.bundle.js:2:2479
initAfterDependencies promises resolved main.jellyfin.bundle.js:2:1175254
using default fonts main.jellyfin.bundle.js:2:1176120
loading installed plugins main.jellyfin.bundle.js:2:1176247
loading packages main.jellyfin.bundle.js:2:1138719
getTryConnectPromise https://jellyfin.sylvi main.jellyfin.bundle.js:2:783405
ConnectionManager requesting url: https://jellyfin.sylvi/system/info/public main.jellyfin.bundle.js:2:774501
fetchWithTimeout: timeoutMs: 20000, url: https://jellyfin.sylvi/system/info/public main.jellyfin.bundle.js:2:775076
fetchWithTimeout: succeeded connecting to url: https://jellyfin.sylvi/system/info/public main.jellyfin.bundle.js:2:775281
ConnectionManager response status: 200, url: https://jellyfin.sylvi/system/info/public main.jellyfin.bundle.js:2:775518
Reconnect succeeded to https://jellyfin.sylvi main.jellyfin.bundle.js:2:783565
ConnectionManager requesting url: https://jellyfin.sylvi/System/Info main.jellyfin.bundle.js:2:774501
ConnectionManager response status: 200, url: https://jellyfin.sylvi/System/Info main.jellyfin.bundle.js:2:775518
returning instance from getOrAddApiClient main.jellyfin.bundle.js:2:780362
Setting server address to https://jellyfin.sylvi main.jellyfin.bundle.js:2:720987
Requesting url without automatic networking: https://jellyfin.sylvi/Sessions/Capabilities/Full main.jellyfin.bundle.js:2:715939
calling apiClient.ensureWebSocket main.jellyfin.bundle.js:2:776984
opening web socket with url: wss://jellyfin.sylvi/socket?api_key=3849050a0afc4fca94fad166a447d78b&deviceId=TW96aWxsYS81LjAgKFgxMTsgTGludXggeDg2XzY0OyBydjo5Mi4wKSBHZWNrby8yMDEwMDEwMSBGaXJlZm94LzkyLjB8MTYzMTg4OTE5MzgwMQ11 main.jellyfin.bundle.js:2:719483
Requesting https://jellyfin.sylvi/Users/1cb49d64ac50431daf0f9a7260fcbc77 main.jellyfin.bundle.js:2:714862
returning instance from getOrAddApiClient main.jellyfin.bundle.js:2:780362
Requesting https://jellyfin.sylvi/DisplayPreferences/usersettings?userId=1cb49d64ac50431daf0f9a7260fcbc77&client=emby main.jellyfin.bundle.js:2:714862
web socket connection opened main.jellyfin.bundle.js:2:763533
Requesting https://jellyfin.sylvi/Sessions?ControllableByUserId=1cb49d64ac50431daf0f9a7260fcbc77 main.jellyfin.bundle.js:2:714862
Received ForceKeepAlive from server. Timeout is 60 seconds. main.jellyfin.bundle.js:2:763083
Sending web socket message: KeepAlive main.jellyfin.bundle.js:2:720015
Clearing KeepAlive for 
WebSocket { url: "wss://jellyfin.sylvi/socket?api_key=3849050a0afc4fca94fad166a447d78b&deviceId=TW96aWxsYS81LjAgKFgxMTsgTGludXggeDg2XzY0OyBydjo5Mi4wKSBHZWNrby8yMDEwMDEwMSBGaXJlZm94LzkyLjB8MTYzMTg4OTE5MzgwMQ11", readyState: 1, bufferedAmount: 0, onopen: C(), onerror: E(), onclose: ()
, extensions: "", protocol: "", onmessage: x(), binaryType: "blob" }
main.jellyfin.bundle.js:2:763384
resolving connectToServers with result.State: SignedIn main.jellyfin.bundle.js:2:782532
processing path request: /web#!/home.html main.jellyfin.bundle.js:2:20487
user is authenticated main.jellyfin.bundle.js:2:20856
proceeding to page: /web#!/home.html main.jellyfin.bundle.js:2:21077
Received KeepAlive from server. main.jellyfin.bundle.js:2:762999
Requesting https://jellyfin.sylvi/Users/1cb49d64ac50431daf0f9a7260fcbc77/Views 2 main.jellyfin.bundle.js:2:714862
Requesting https://jellyfin.sylvi/Users/1cb49d64ac50431daf0f9a7260fcbc7…ckdrop%2CThumb&EnableTotalRecordCount=false&MediaTypes=Video main.jellyfin.bundle.js:2:714862
Requesting https://jellyfin.sylvi/Users/1cb49d64ac50431daf0f9a7260fcbc7…ckdrop%2CThumb&EnableTotalRecordCount=false&MediaTypes=Audio main.jellyfin.bundle.js:2:714862
Requesting https://jellyfin.sylvi/Users/1cb49d64ac50431daf0f9a7260fcbc7…2CBackdrop%2CThumb&ParentId=7e64e319657a9516ec78490da03edccb main.jellyfin.bundle.js:2:714862
Requesting https://jellyfin.sylvi/Users/1cb49d64ac50431daf0f9a7260fcbc7…2CBackdrop%2CThumb&ParentId=27f4c3bbf242db3933c10fe22917c37e main.jellyfin.bundle.js:2:714862
Requesting https://jellyfin.sylvi/Users/1cb49d64ac50431daf0f9a7260fcbc7…2CBackdrop%2CThumb&ParentId=f137a2dd21bbc1b99aa5c0f6bf02a805 main.jellyfin.bundle.js:2:714862
Requesting https://jellyfin.sylvi/Users/1cb49d64ac50431daf0f9a7260fcbc7…2CBackdrop%2CThumb&ParentId=52f1cc5cfe5ba8c9452cebe7bca9e026 main.jellyfin.bundle.js:2:714862
Requesting https://jellyfin.sylvi/Users/1cb49d64ac50431daf0f9a7260fcbc7…2CBackdrop%2CThumb&ParentId=a656b907eb3a73532e40e44b968d0225 main.jellyfin.bundle.js:2:714862
Requesting https://jellyfin.sylvi/Shows/NextUp?Limit=24&Fields=PrimaryI…tEpisode=false&NextUpDateCutoff=2020-10-12T11%3A59%3A26.514Z main.jellyfin.bundle.js:2:714862
processing path request: /web#!/music.html main.jellyfin.bundle.js:2:20487
user is authenticated main.jellyfin.bundle.js:2:20856
proceeding to page: /web#!/music.html main.jellyfin.bundle.js:2:21077
Requesting https://jellyfin.sylvi/Users/1cb49d64ac50431daf0f9a7260fcbc77/Items/7e64e319657a9516ec78490da03edccb main.jellyfin.bundle.js:2:714862
Requesting https://jellyfin.sylvi/Users/1cb49d64ac50431daf0f9a7260fcbc7…tIndex=0&Limit=100&ParentId=7e64e319657a9516ec78490da03edccb main.jellyfin.bundle.js:2:714862
Requesting url without automatic networking: https://jellyfin.sylvi/DisplayPreferences/usersettings?userId=1cb49d64ac50431daf0f9a7260fcbc77&client=emby main.jellyfin.bundle.js:2:715939
processing path request: /web#!/home.html main.jellyfin.bundle.js:2:20487
user is authenticated main.jellyfin.bundle.js:2:20856
proceeding to page: /web#!/home.html main.jellyfin.bundle.js:2:21077
Requesting https://jellyfin.sylvi/System/Endpoint main.jellyfin.bundle.js:2:714862
```

</details>

**Screenshots**
Video showing what happens (at `00:10`, before showing how to reproduce it): https://www.youtube.com/watch?v=xW9ZqVmlUyE

Note: yes in this case i am switching between stuff fast, but it even happens sometimes when doing it slowly.
also even when waiting for some time, it will not show up (reference `00:10` at the video)

**Additional context**

**Comment by icedterminal** [comment]
Oh good an open issue for this. I've seen this bug for a while. It's peculiar. I'll try my best to give a detailed description. As I do not have a recording of this:

### Description:
Images that have loaded and appear in the viewport, will not appear again once they have left the viewport. It somehow extends to images that have never entered the viewport.

### Example 1:
1. Search for content. In my case I used the term *"special"*.
2. The results are listed and the images from the relevant media load as expected.
3. Scroll the content left to see hidden results on the right. Observe images will appear as expected.
4. Now scroll the content right to see the once shown results on the left. Observe images have disappeared.
5. Once more, scroll the content left and observe those images on right have disappeared too.
6. Now all results from the search have missing images.

### Example 2:
1. Open the Music library.
2. I prefer to browse by artist, so I click an artist I want.
3. Artist page displays all albums and their images. Up to this point all images have loaded.
4. Go back a page to see the Artists. Observe images have disappeared.
5. Click on a different artist. Observe the images do not load.

### Potential solutions
This bug was rectified with a server restart. However, it will manifest again after some time. Can take hours to days. Interestingly, I do not know if this is related, I have recently changed my server configuration to disable the usage of `/swap` by editing `/etc/fstab`. Since I have done this, it's been a week now and I have yet to see it manifest again.

### Notes
It didn't matter what client was viewing Jellyfin content with. When any client exhibits this behavior, they all do. Desktop or mobile browser and the apps on my iOS and Android devices. If the user has chosen the option to use a blur placeholder until images load, instead of disappearing, there will be a permanent blur.

**Comment by JPVenson** [comment]
@hasezoey I have the same problem as you. Turn of the DarkReader addon. That it should work again. For some reason DarkReader overwrites the button image on some tiles with a `data-darkreader-inline-bgimage` attribute. That hides the image.

**Comment by hasezoey** [comment]
> @hasezoey I have the same problem as you. Turn of the DarkReader addon. Then it should work again. For some reason DarkReader overwrites the button image on some tiles with a `data-darkreader-inline-bgimage` attribute. That hides the image.

thanks, can confirm that somehow DarkReader messes with jellyfin's provided images

**Comment by aransou** [comment]
I confirm the problem with not showing some thumpnails e.g. for interpret. This is in the firefox webview and also in the android app. I checked the .mp3 files and there is a picture included.
