### ISSUE TITLE
Jellyfin doesn't open the HTTPS port

### ISSUE THREAD

**Issue by CStafford-14** [jellyfin/jellyfin#6697]
**Describe the bug**
Jellyfin doesn't open the HTTPS port for some reason. This is made obvious by running `netstat -lt` and the HTTPS port (8920) is not in use.

**System (please complete the following information):**
 - OS: Ubuntu Server 20.04
 - Virtualization: None
 - Clients: Browser
 - Browser: Firefox 93
 - Jellyfin Version: 10.7.7 Stable
 - FFmpeg Version: Default
 - Playback: Default
 - Hardware Acceleration: None
 - Installed Plugins: Default
 - Reverse Proxy: NGINX
 - Base URL: N/A
 - Networking: Host
 - Storage: Local

**To Reproduce**

1. Start Jellyfin
2. Try connecting over HTTPS

**Expected behavior**
I connect to Jellyfin

**Server Logs**
Log is empty...

**Screenshots**

![Screenshot from 2021-10-13 16-55-28](https://user-images.githubusercontent.com/35039669/137211522-75bacc0f-1906-46e3-a8f8-2f8ebd671c8a.png)

**Additional context**
Most values are left to their defaults. NGINX yields a bad gateway when connecting via the reverse proxy (HTTPS/443) and Firefox can't establish a connection when connecting directly to the HTTPS port (HTTPS/8920)

HTTPS is enabled in networking settings, and I have added the correct certificate file and password.

**Comment by CStafford-14** [comment]
> Just to be sure because it's not called out in the post - is Automatic Port Mapping enabled in the Jellyfin settings?

No, it's disabled.

**Comment by pauperis** [comment]
I'm suffering the exact same problem.

I can remotely access Jellyfin through http://jellyfin.example.com and also through http://example.com:8096, but even I enabled HTTPS the port is never opened so I cannot access through https://example.com:8920 nor http://example.com:8920.

Running netstat -lt I can check port 8096 is opened but 8920 not.

Also i configured nginx as reverse proxy so i can access Jellyfin through https://jellyfin.example.com but internally nginx connects to Jellyfin through http which is not the desired behaviour.

Trying to solve the issue on Known Proxies I added my server IPv4 nd IPv6 in a comma separated list. Also, in HTTPS settings -> Custom SSL certificate path: I added the full path to my Letsencrypt full certificate, ie: /etc/letsencrypt/archive/example.com/fullchain.pem but had no luck.

IPv4 and IPv6 protocols are both enabled.

I also did run systemctl restart jellyfin but no luck at all.

**Comment by GregTheHun** [comment]
I generate my keys through OpnSense, and using every combination I've been able to conceive, I have not gotten this working...

(Trombones)

**Comment by NiRit100** [comment]
> EDIT
> Creating the certificate through the following command fix the issue:
> openssl pkcs12 -export -out /etc/jellyfin/mycert.com.pfx -inkey /etc/letsencrypt/live/mydomain.com/privkey.pem -in /etc/letsencrypt/live/mydomain.com/cert.pem -passout pass:123456
> chown jellyfin:jellyfin /etc/jellyfin/mycert.com.pfx
> systemctl restart jellyfin
> END EDIT

Yep, that solved it for me on windows (of course not with these exact commands, but it was related to file access restrictions on the certificate file).

**Comment by troyhatchard** [comment]
For anyone else coming to this in the future, my issue (like above), was due to an improper certificate. I couldn't find any logs that referenced this, so it was hard to find. I am using NGINX as a proxy, and I had to create a .pfx file from the certificates NGINX created for Jellyfin, then point Jellyfin at that file. Then it worked!

**Comment by j-winston** [comment]
> > EDIT
> > Creating the certificate through the following command fix the issue:
> > openssl pkcs12 -export -out /etc/jellyfin/mycert.com.pfx -inkey /etc/letsencrypt/live/mydomain.com/privkey.pem -in /etc/letsencrypt/live/mydomain.com/cert.pem -passout pass:123456
> > **chown jellyfin:jellyfin /etc/jellyfin/mycert.com.pfx**
> > systemctl restart jellyfin
> > END EDIT
> 
> Yep, that solved it for me on windows (of course not with these exact commands, but it was related to file access restrictions on the certificate file).

Solved! Finally! This issue was driving me bonkers using Tailscale to generate a certificate. What worked? 

1. Ensuring my certificate was a proper .pfx file using the openssl command above. Tailscale generates a .key and .crt file. Simply pointing the Jellyfin server to a .crt file wasn't cutting it--duh. 
2. Permissions. As shown using 'chown' to change user and group ownership of the .pfx file after it's created. 
3. Not sure if this makes a difference but I did actually set a password for the certificate, during step 1--generating the certificate. 
4. Restarting jellyfin and just to be safe, testing https in incognito mode. 

Love!!

**Comment by buzzy** [comment]
And how do you guys make sure this pfx-file keeps up to date, as the cert will need to be updated like very 3 months...

**Comment by nirit100** [comment]
> how do you guys make sure this pfx-file keeps up to date

Jellyfin just stores a path that points to the certificate file, as far as I know. 

I do it like this:
Jellyfin has a path to a symbolic link that In turn points to the certificate file. 
I update the certificate using a small script I wrote that is run automatically every three months, that
 -  executes certbot to renew the certificate
 - on success calls openssl to convert the cert file format
 - on success updates the link file
 
That script is probably pretty hacky and there may be better ways to do it. It works though.

**Comment by buzzy** [comment]
> > how do you guys make sure this pfx-file keeps up to date
> 
> Jellyfin just stores a path that points to the certificate file, as far as I know.
> 
> I do it like this: Jellyfin has a path to a symbolic link that In turn points to the certificate file. I update the certificate using a small script I wrote that is run automatically every three months, that
> 
> * executes certbot to renew the certificate
> * on success calls openssl to convert the cert file format
> * on success updates the link file
> 
> That script is probably pretty hacky and there may be better ways to do it. It works though.

Well, the thing is that certbot normally updates the cert automatically itself and other software, like nginx, just points to the cert generated by certbot. That means no custom scripts are needed. In this case, jellyfin obviously need some weird format that certbot does not generate. Hence, a manual script will need to be run every time certbot updates the cert.

Seems like your solution was to disable the automatic certbot runs and do it manually. I know I can do the same, but as you said, it feels hacky.

**Comment by sakers** [comment]
It also appears that the certificate file has to have owner jellyfin and have 0600 permissions for it to work. 
Started working for me when I set the cert file to this: 

-rw------- 1 jellyfin jellyfin 2850 Jan 30 14:18 jellyfin.pfx
