### ISSUE TITLE
Discuss testing strategy

### ISSUE THREAD

**Issue by BnMcG** [jellyfin/jellyfin#67]
It looks like there aren't any (at least, no open-source) test suites for the codebase, I think we should look at what to prioritise in terms of testing the existing codebase, and perhaps implement a policy that all future PRs require tests? At least the problem can be addressed going forwards, then.

With that in mind, it may be a good idea to decide on a testing library/toolset and then create test projects for each of the C# projects in the solution, so that it's easy for future contributors to add tests to their PRs.

I've personally had good experience with NUnit as a unit testing framework, Moq for mocking and Autofixture for resolving dependencies easily, but I'm happy to accept whatever is popular nowadays.

**Comment by BnMcG** [comment]
#59 - This seems like it could benefit from however the roadmap pans out, so linking it for visibility.

**Comment by SpootDev** [comment]
From the boo-boo's that get released with Emby........I've assumed there are no unit tests at all.   hehhee

**Comment by JustAMan** [comment]
Yeah, the codebase looks like it's written in "release it and test by running on your users' machines" way.

I'm personally okay with whatever framework you choose, as I know none right now :D

**Comment by anthonylavado** [comment]
We'll be revisiting this in a new Roadmap document, currently in progress.
