### ISSUE TITLE
Fedora versions support

### ISSUE THREAD

**Issue by claneys** [jellyfin/jellyfin#6701]
**Describe the bug**

I open an issue to get some news about it, sorry if it isn't the right place.
I only see package for fedora 33, https://repo.jellyfin.org/releases/server/fedora/, is it wanted to only support this version of fedora ? Is it planned to support next version as we will have the version 35 coming soon.

**System (please complete the following information):**
 - OS: Fedora 33

**Comment by harryofbath** [comment]
Currently running those packages on Fedora 34 without issue.

**Comment by claneys** [comment]
Ok, thanks for that :) I'll stick to that repo as well so.
