### ISSUE TITLE
UDP/RTSP Streaming

### ISSUE THREAD

**Issue by Paulus1337** [jellyfin/jellyfin#6720]
Just wondering more out of intrest. I noticed the applications + streams both go through TCP/HTTP(S).
Is it possible/hard/an improvement to run the streams on a UDP protocol that also uses TCP for control like: RTSP?

Purely to improve bandwidth, but of course means poking extra protocols in your network so also has its disadvantages, just wondering if it was ever considered and I am no expert.

**Comment by GrabbenD** [comment]
Did the potential support for UDP/RTSP streaming ever get revisited?

Perhaps this could be achieved by the Reverse Proxy?
