### ISSUE TITLE
Correctly identify subtitle language。

### ISSUE THREAD

**Issue by i-iooi-i** [jellyfin/jellyfin#6723]
Hello, I'm a plex user. I'm back now. I'm using jellyfin. Its interface is very beautiful. I would like to raise a question I found. When I define the suffix "zh_cn" for the names of all subtitle files, Can the suffix "zh_cn" in the subtitle name be automatically recognized as Chinese language? Plex is recognizable. I found jellyfin can't recognize it. thank you.better and better.

![Snipaste_2021-10-21_22-41-05](https://user-images.githubusercontent.com/1827701/138302855-b40db0c5-7e8c-46ba-8b8b-3db08c74dd6c.png)

**Comment by shirt-dev** [comment]
This issue still exists.

**Comment by shirt-dev** [comment]
![image](https://user-images.githubusercontent.com/2660574/157133915-cad3ae44-a2fa-4960-b74c-db3fdf5b9067.png)

**Comment by webysther** [comment]
same as #9072

**Comment by Bond-009** [comment]
Duplicate of #6302
