### ISSUE TITLE
 Multiple Connection Segmented Streaming #3206 

### ISSUE THREAD

**Issue by macearl** [jellyfin/jellyfin#6724]
As I can't reopen the issue : https://github.com/jellyfin/jellyfin/issues/3206 I will create a new one. 

Feel free to reopen the old one and close this one. 

For further context see the older messages in the linked issue. 

If I download anything from my server (via ftp, http,...) and use multiple connections I can saturate my upload bandwidth of 50Mbit/s

However if on the same day and at the same time, after all other downloads/uploads are stopped, someone tries to watch something through jellyfin they often encounter buffering issues.

I'm also using almost exclusively direct streaming with no transcoding and the buffer on the client is usually increased to hold at least 100MB of cache (this is the limit some of my RPi4s can handle). Also there is almost always only a single client watching something at a time.

If you need any Logs or want me to run some tests let me know. I think streaming through multiple connections could greatly improve the stability in a lot of cases.

**Comment by macearl** [comment]
Go away bot

**Comment by MrHugelberg** [comment]
Would love to see that implemented! I have the same problem.

**Comment by Bond-009** [comment]
Feature requests go here: https://features.jellyfin.org/
