### ISSUE TITLE
4K HDR HVEC content abruptly stops after 30-40 min. Any idea how to fix it?

### ISSUE THREAD

**Issue by HenkoHallows** [jellyfin/jellyfin#6733]
**Server System**
 - OS: [Windows]
 - Jellyfin Version: [10.7.7]
 - Hardware settings & device: [NVENC on GTX2080, VAAPI on AMD Ryzen 7 3800X 8-Core Processor ]
 
**Client System**
 - Device: [Desktop]
 - OS: [Windows]
 - Client: [Web/Browser]
 - Browser (if Web client): [Brave]
 - Client and Browser Version: [V1.31.87]
[Issue.txt](https://github.com/jellyfin/jellyfin/files/7409053/Issue.txt)

**Comment by HenkoHallows** [comment]
I mainly play movies locally, and I have no proxy.
Web browsers say I'm out of memory, I've used Brave and Firefox.

Same thing happens on Android, only it stops, crashes and logs me out and renders Jellyfin useless until I restart Jellyfin, that has only happened when I've used it through Android, It's very weird.

**Comment by HenkoHallows** [comment]
4K HDR mkv content messages in Dashboard:
The media is being converted into a format that is compatible with the device that is playing the media.
Framerate: 82fps

32.1 Mbps TS H264 AAC


Reason for transcoding:
VideoCodecNotSupported
AudioCodecNotSupported

And another:
The media is being converted into a format that is compatible with the device that is playing the media.
Framerate: 75fps

37.2 Mbps TS H264 AAC


Reason for transcoding:
VideoCodecNotSupported
AudioCodecNotSupported


I have other 1080p content that seems to lag now and then and this is the message I get in the Dashboard for 1080p mkv:
The media is compatible with the device regarding resolution and media type (H.264, AC3, etc), but in an incompatible file container (mkv, avi, wmv, etc). The video will be re-packaged on the fly before being sent to the device.


Direct stream uses very little processing power with a minimal loss in video quality.


As far as I can see online, the formats in use should be compatible? but I'm still getting these, and I'm guessing they are the only causes for my problems

I have no idea what I should convert them to or how, I'm new to that part of this.

**Comment by HenkoHallows** [comment]
Alright, Jellyfin just crashed again.
I've tried restarting, Shutting down the system and starting it again. but now it just wont start.
So this is new.

**Comment by crobibero** [comment]
[2021-10-31 13:13:21.388 +01:00] [FTL] [1] Main: Error while starting server.
Full: SQLitePCL.pretty.SQLiteException: database or disk is full

Your drive is full. Likely the cause of the original issue, and Jellyfin not being able to start again.

**Comment by HenkoHallows** [comment]
That doesn't make sense, there's 40 GB left
