### ISSUE TITLE
ffmpeg incorrectly launched (

### ISSUE THREAD

**Issue by Tthecreator** [jellyfin/jellyfin#674]
**Describe the bug**
It seems that in the latest dev build ffmpeg streaming is broken. This seems to be due to the '-segment_time_delta' argument. In my case this was '0,021' but ffmpeg on windows doesn't accept the comma. If I use a point it works fine but I don't know if that's supposed to happen.

**To Reproduce**
1. Open a video. (Mine was a 20 minute anime episode)
2. Look at server logs

**Expected behavior**
Streaming should start and no errors should show up.

**Logs**
```
[segment muxer @ 00000181ef5e4800] Unable to parse option value "0,021" as duration
[segment muxer @ 00000181ef5e4800] Error setting option segment_time_delta to value 0,021.
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Error initializing output stream 0:1 --
```

**System (please complete the following information):**
 - OS: Windows
 - Browser: Opera
 - Jellyfin Version: 10.0.2+ (latest dev as of the making of this issue)
 - ffmpeg version: ffmpeg-20190119-32fb83e-win64-static

**Additional context**
It seems to work fine when segment_time_delta has a dot instead of comma. If I want to fix this then I should probably first look at what the segment_time_delta even does exactly and if it's supposed to even be a floating value like this.

**Comment by Bond-009** [comment]
I'm closing this issue as the problem in question never hit master and got removed from dev.
