### ISSUE TITLE
Client Player not remembering position and randomly goes back to beginning

### ISSUE THREAD

**Issue by Phoenix-004** [jellyfin/jellyfin#6760]
**Describe the bug**

**System (please complete the following information):**
 - OS: Linux Mint (Debian/Ubuntu)
 - Virtualization: N/A
 - Clients: Browser, Android TV
 - Browser: Chrome 95 (stable)
 - Jellyfin Version: 10.7.7 Android TV app Version 0.12.2
 - FFmpeg Version: 4.3.2. Jellyfin-ffmpeg
 - Playback: Direct Play, Direct Stream, Transcode 
 - Hardware Acceleration: MediaCodec Android
 - Installed Plugins: Theme Songs
 - Reverse Proxy: None
 - Base URL: None
 - Networking: Host
 - Storage: Local, SMB

**To Reproduce**

1. Start video playback on Android TV app: 0.12.2
2. Seekbar stays at 0.00 regardless of video playback location
3. At random can jump back to the start of the video

**Expected behavior**

**Server Logs**

**FFmpeg Logs**

**Browser Console Logs**

**Screenshots**

**Additional context**

**Comment by crobibero** [comment]
I can’t find the specific issue, but this is a known Android TV issue, not a server issue.
