### ISSUE TITLE
10.8.0-alpha1: Docker containers still built with Debian 10

### ISSUE THREAD

**Issue by yesrod** [jellyfin/jellyfin#6768]
**Describe the bug**
According to the MR at https://github.com/jellyfin/jellyfin/pull/6434 , the Docker container should be using Debian 11 (Bullseye). However, I just updated my local server, and the container is still using Debian 10 (Buster).

**System (please complete the following information):**
 - OS: OpenMediaVault 5.6.13 (Debian 10.10)
 - Virtualization: Docker
 - Clients: Browser, Android, Kodi
 - Browser: Firefox 93.0
 - Jellyfin Version: 10.8.0-alpha1
 - FFmpeg Version: jellyfin-ffmpeg 4.3.2-1-buster
 - Playback: Direct Play, Transcode
 - Hardware Acceleration: VAAPI
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: none
 - Networking: Docker macvlan
 - Storage: local

**To Reproduce**
1. Run a container with `jellyfin:10.8.0-alpha` Docker image
2. Enter Docker container with `docker -exec -it <container name> /bin/bash`
3. Check Debian version with `cat /etc/debian_version`
4. Observe that the Debian version is `10.11` instead of `11.0` or `11.1`

**Expected behavior**
root@jellyfin:/# cat /etc/debian_version 
11.1

**Server Logs**
N/A

**FFmpeg Logs**
N/A

**Browser Console Logs**
N/A

**Screenshots**
N/A

**Additional context**
I'm specifically eager to have Debian 11-based containers to finally allow my AMD card to do HEVC transcoding successfully.

**Comment by joshuaboniface** [comment]
Thanks for the heads up. The main images are Bullseye, but the metaimage isn't. That'll be updated for Alpha 2!

**Comment by crobibero** [comment]
Fixed by https://github.com/jellyfin/jellyfin-metapackages/pull/13
