### ISSUE TITLE
Dashboard/Home Screen show duplicates

### ISSUE THREAD

**Issue by ShakeSp33r** [jellyfin/jellyfin#6775]
**Describe the bug**
I have 1 big directory with all my shows in called TV Shows, then a separate directory with soft links to the TVShows for all shows that has "Food" in the nfo, same with NetFlix. Therefore on the Dashboard (Home Screen) some TVShows would appear multiple times.

**To Reproduce**
Create directory with soft link to TVShow in main library.
Add new library pointing to the directory with the soft link.
Scan new library.

**System (please complete the following information):**
OS: linuxserver/jellyfin docker
Browser: Chrome
Jellyfin Version: 10.7.7

**Expected**
Videos grouped by filename/TV Show

**Screenshot**
![Screenshot 2021-11-04 at 13 13 49](https://user-images.githubusercontent.com/69896780/140304695-fbb5964b-5115-4e77-b43b-a7156eba9c68.png)

**Comment by ShakeSp33r** [comment]
This is still an issue, not critical

**Comment by michaelkrieger** [comment]
Still an issue.  Also in "continue watching" and "up next"
