### ISSUE TITLE
Can't start v10.8.0-alpha1

### ISSUE THREAD

**Issue by darkarp** [jellyfin/jellyfin#6776]
**Describe the bug**
Built the new 10.8.0-alpha1 release and when starting, this error keeps popping up: ` System.ArgumentNullException: Value cannot be null. (Parameter 'provider')`. This also happens when trying out the pre-built version of 10.8.0-1

Stack trace:
```
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'provider')
at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
at Emby.Server.Implementations.ApplicationHost.Resolve[T]()
at Jellyfin.Server.Program.StartApp(StartupOptions options)
at Jellyfin.Server.Program.<Main>(String[] args)
jellyfin.service: Main process exited, code=dumped, status=6/ABRT
jellyfin.service: Failed with result 'core-dump'.
```

**System (please complete the following information):**
 - OS: Ubuntu 20.04
 - Virtualization: No virtualization - native

**Comment by BugFixesAndPerformanceImprovements** [comment]
I get the same `System.ArgumentNullException: Value cannot be null. (Parameter 'provider')` error in Windows using an existing Jellyfin database. Creating a new database works fine.

The log also mentions:

`Main: Error while starting server.
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load type 'SQLitePCL.pretty.IResultSetValue' from assembly 'SQLitePCL.pretty, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.`

**Comment by antipiot** [comment]
Having simila issue here on docker with container 10.8.0-alpha1:

Made a copy of my actual config folder and started a new container with alpha image:
Log attached show error with db migration:
```
[19:44:26] [INF] [1] Main: Running query planner optimizations in the database... This might take a while
[19:44:26] [FTL] [1] Main: Unhandled Exception
```

[_jellyfin8_logs.txt](https://github.com/jellyfin/jellyfin/files/7478072/_jellyfin8_logs.txt)

**Comment by crobibero** [comment]
> Main: Error while starting server. System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Could not load type 'SQLitePCL.pretty.IResultSetValue' from assembly 'SQLitePCL.pretty, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

Try removing the Playback Reporting plugin and Reports plugin

**Comment by darkarp** [comment]
It seems this issue happens when uprading from the previous version. What's the proper upgrade path from `10.7.7` to `10.8.0-1`?

**Comment by crobibero** [comment]
I’m fairly certain the log lines posted in this issue are all from plugins failing. Theoretically the plugin shouldn’t be able to stop the server from starting up, but there are many edge cases

**Comment by antipiot** [comment]
> 
> 
> > Main: Error while starting server. System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Could not load type 'SQLitePCL.pretty.IResultSetValue' from assembly 'SQLitePCL.pretty, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
> 
> Try removing the Playback Reporting plugin and Reports plugin
I tried to remove the plugin "Reporting playback" but error is still present:

```
[07:25:20] [INF] [1] Main: Running query planner optimizations in the database... This might take a while
[07:25:20] [FTL] [1] Main: Unhandled Exception
System.ArgumentNullException: Value cannot be null. (Parameter 'provider')
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
```

**Comment by darkarp** [comment]
I can confirm that after deleting the entire data directory (for me at `/var/lib/jellyfin/data`) the error disappears

**Comment by crobibero** [comment]
If anyone is having this issue after removing the PlaybackReporting plugin, please post the full startup log
