### ISSUE TITLE
Undefined

### ISSUE THREAD

**Issue by miltondonizeti** [jellyfin/jellyfin#6785]
oi meu nome é milton 
Estou usando a versão jellyfin_10.7.7_windows-x64
no meu notebook a rede local com ip:8096
Eu gostaria de usar o jellyfin_10.7.7_windows-x64 na rede externa.
Liguei na operadora de internet para liberar uma porta para uso do servidor jellyfin_10.7.7_windows-x64 para windows
Durante um tempo deu tudo certo
Depois de 10 dias o jellyfin_10.7.7_windows-x64 começou e apresentar falhas para uso na rede externa
Liguei na operadora de internet reportei o problema (porta fechada)
Depois de configuração do roteador TL-WR845N 3 antenas voltou a funcionar por mais 5 dias
e o depois apareceu outro problema na rede externa.
Sempre que vou tentar acesso ao servidor  jellyfin_10.7.7_windows-x64 através de ip e porta fornecidos pela operadora de internet.
Não consigo.
Agora outro problema que aparece no aparelho de celular Android versão 11 no aplicativo chrome é (Selecione Servidor Aparece a palavra UNDEFINED)
SEMPRE QUE COLOCO O IP EXTERNO E A PORTA fornecidos pela operadora aparece a mensagem (Falha na Conexão)
Desde já Agradeço

**Comment by Bond-009** [comment]
> hi my name is milton
I'm using jellyfin_10.7.7_windows-x64 version
on my notebook the local network with ip:8096
I would like to use jellyfin_10.7.7_windows-x64 on the external network.
I called the internet operator to release a port for using the jellyfin_10.7.7_windows-x64 server for windows
For a while everything went fine.
After 10 days jellyfin_10.7.7_windows-x64 started and failed to use on external network
I called the internet provider and reported the problem (closed door)
After configuring the TL-WR845N 3 antennas router it worked again for another 5 days
and then another problem appeared on the external network.
Whenever I try to access jellyfin_10.7.7_windows-x64 server through ip and port provided by the internet operator.
I can not.
Now another problem that appears on the Android version 11 mobile device in the chrome application is (Select Server The word UNDEFINED appears)
WHENEVER I PUT THE EXTERNAL IP AND THE PORT provided by the operator, the message (Connection Failed) appears
Thank you very much in advance 

For support join our matrix: https://matrix.to/#/#jellyfin-troubleshooting:matrix.org

https://jellyfin.org/contact/
