### ISSUE TITLE
Slow HTTP response

### ISSUE THREAD

**Issue by lyaschuchenko** [jellyfin/jellyfin#6787]
Hi!

Last 3 days looking up problem - jellyfin loads cpu to 4 -7 (5 min) and in log have slow HTTP response.i reinstall jellyfin but problem not gone.

jellyfin.service - Jellyfin Media Server                                                                                                                           Loaded: loaded (/lib/systemd/system/jellyfin.service; enabled; vendor preset: enabled)                                                                         Drop-In: /etc/systemd/system/jellyfin.service.d                                                                                                                          └─jellyfin.service.conf                                                                                                                                 Active: active (running) since Sat 2021-11-06 13:14:52 UTC; 32min ago
   Main PID: 1386 (jellyfin)
      Tasks: 65 (limit: 9237)
     Memory: 193.0M
     CGroup: /system.slice/jellyfin.service                                                                                                                                  └─1386 /usr/bin/jellyfin --webdir=/usr/share/jellyfin/web --restartpath=/usr/lib/jellyfin/restart.sh --ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg
Nov 06 13:43:21 media.local.lan jellyfin[1386]: [13:43:21] [INF] WS 10.50.16.1 closed                                                                           Nov 06 13:43:34 media.local.lan jellyfin[1386]: [13:43:25] [WRN] Slow HTTP Response from http://10.50.16.10:8096/System/Info to 10.50.16.1 in 0:00:12.5135953 w>Nov 06 13:43:34 media.local.lan jellyfin[1386]: [13:43:25] [INF] WS 10.50.16.1 request                                                                          Nov 06 13:43:38 media.local.lan jellyfin[1386]: [13:43:38] [WRN] Slow HTTP Response from http://10.50.16.10:8096/Sessions/Capabilities/Full to 10.50.16.1 in 0:>Nov 06 13:43:42 media.local.lan jellyfin[1386]: [13:43:42] [WRN] Slow HTTP Response from http://10.50.16.10:8096/DisplayPreferences/usersettings?userId=71b8baf>Nov 06 13:45:17 media.local.lan jellyfin[1386]: [13:45:17] [INF] WS 10.50.16.1 closed                                                                           Nov 06 13:46:52 media.local.lan jellyfin[1386]: [13:46:52] [WRN] Slow HTTP Response from http://10.50.16.10:8096/Users/71b8baf504704079a47d0b0158572816/Views t>Nov 06 13:46:52 media.local.lan jellyfin[1386]: [13:46:52] [WRN] Slow HTTP Response from http://10.50.16.10:8096/Users/71b8baf504704079a47d0b0158572816/Views t>Nov 06 13:46:52 media.local.lan jellyfin[1386]: [13:46:52] [WRN] Slow HTTP Response from http://10.50.16.10:8096/Users/71b8baf504704079a47d0b0158572816/Views t>Nov 06 13:46:52 media.local.lan jellyfin[1386]: [13:46:52] [WRN] Slow HTTP Response from http://10.50.16.10:8096/Users/71b8baf504704079a47d0b0158572816/Views t>~

Any solution?

**Comment by lyaschuchenko** [comment]
Resolved. Have 36% defrag on my zfs pool. After re-creation all good

**Comment by clintjonesgit** [comment]
As the user closed this thread and the status 200 warning about slow http responses is still a very real issue for many users, and defragmenting a disk has less than nothing to do with the issue for all of us from what I can tell, this should really be deleted. It's just cluttering the search results and in no way is helpful to anyone. Just my 2c, not hating on the author or the post just saying it isn't helpful to anyone.
