### ISSUE TITLE
ICanHazIP for WAN Address blocks page loads

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin#679]
**Describe the bug**
If there is an issue accessing ICanHazIP, then page loads appear to be blocked while the 10s timeout is reached.

**To Reproduce**
1. Use some local network mechanism to block ICanHazIP
2. Load any Jellyfin page
3. Observe delay in loading, and in logs, an error with a timeout

**Expected behavior**
Requesting IP information should not block page loads of possible, and should probably be cached (with a manual refresh button available)

**Logs**
Sample logs from a user available here: 
https://pastebin.com/mSRS4Gq2

**System (please complete the following information):**
 - OS:
 - Browser: 
 - Jellyfin Version: 10.0.2

**Additional context**
Apologies for not gathering more info, but it shouldn’t be specific to one particular install.

**Comment by anthonylavado** [comment]
Haven’t had any other reports of this, so I’m tempted to close it for now.

**Comment by TangoEcho** [comment]
If Jellyfin doesn't have an active internet connection this error will still occur. I don't see why it should hold up the page load for so long just to check for an IP.

**Comment by anthonylavado** [comment]
Don’t think this will make it in this release then, but now on the board for the next after that. Need more C# eyes on the code, as this hasn’t come up much.

**Comment by anthonylavado** [comment]
Okay, so we either need someone to fix this so it doesn't block page loading (if that's even possible), or find a way to disable the check in the UI.

If we can get Emby for Kodi updated to not require this, that would be a bonus. I guess it's requested by the plug-in so people can have remote Kodi access to an Jellyfin install?

**Comment by joshuaboniface** [comment]
1. I think we should refactor this to be a cron job, not every page load - that never made any sense to me.
2. If we can't do 1, it should time out in 0.5-1 second, not 10 seconds.
3. If 2 is a problem, maybe a faster service (ipinfo.io is one) would be better.

**Comment by dkanada** [comment]
I think it's only used in web on the dashboard to show the remote address, I can remove this and then there would be no reason to report it at all. I can also head over to Emby for Kodi and make sure it's unused there, but I thought that client was broken for some reason already.

**Comment by joshuaboniface** [comment]
@dkanada EfK/jellyfin-kodi requires it for some reason, we hit that back in ~Jan when we tried to remove it the first time. BTW icanhazip.com works fine for me right now.

**Comment by anthonylavado** [comment]
> If icanhazip continues to be unreliable, maybe we can look at ipinfo.io's free plan (or, just use it, i doubt they'd notice, though that's a grey area).

@joshuaboniface I don't think it's that the site is unreliable, it's more that routing to any external source introduces possible issues. In this case, canhaz has just been unlucky.

Also, I think EfK may be broken as @dkanada says.

**Comment by Nedlinin** [comment]
OpenDNS might be another way to accomplish this?  


Obviously nslookup isn't the proper option but just as an example:

`
nslookup myip.opendns.com. resolver1.opendns.com
`

Should return the external IP of the requesting machine.  I'd expect opendns to have great up times and no API to register for as it's just DNS.

**Comment by oddstr13** [comment]
Personally I've been using plain nginx for things like this; https://oddstr13.openshell.no/ip/
```nginx
    location /ip/ {
        default_type text/plain;
        echo $remote_addr;
    }
```
So, if we choose to host our own IP lookup service, it is *really* easy to set up.
IPv4 vs IPv6 can either be done on the DNS level, or by explicitly using only IPv4 or IPv6 in the client.
We can also disable logging, to partially solve the phoning home concern.

**Comment by PrplHaz4** [comment]
From the sound of it, this should be configurable, so people can balance their own need for security/privacy...

Options:
- Use External lookup service: (enter URL of lookup service - default is icanhazip - maybe cache this value anytime a new one is received so it doesn't need to be a blocking call?)
- Use static value: (manually enter IP that should appear in WAN IP field - maybe default to localhost?)

I wasn't able to find any official source, but this cloudflare endpoint is pretty easy to parse (and, IMO, is likely more reliable and trusted - whatever that means)...so I'll add this to the list of acceptable IP lookup services...

`https://www.cloudflare.com/cdn-cgi/trace`
```
fl=11f74
h=www.cloudflare.com
ip=123.456.235.133
ts=1562939893.219
visit_scheme=https
uag=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0
colo=EWR
http=http/2
loc=US
tls=TLSv1.3
sni=plaintext
warp=off
```
