### ISSUE TITLE
LocalNetworkAddresses is ignored, not listening on IPv6 localhost

### ISSUE THREAD

**Issue by VMelnalksnis** [jellyfin/jellyfin#6790]
**Describe the bug**
Jellyfin is available on all available addresses (`*:8096`) despite setting Networking -> Bind to local network address.

**System (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS
 - Virtualization: LXC
 - Clients: Browser
 - Browser: Firefox 94.0.1
 - Jellyfin Version: 10.7.7-1
 - FFmpeg Version: 4.3.1-4-focal
 - Playback: -
 - Hardware Acceleration: none
 - Installed Plugins: AudioDB, MusicBrainz, OMDb, Playback Reporting
 - Reverse Proxy: nginx
 - Base URL: none
 - Networking: -
 - Storage: local

**To Reproduce**
Enter either `::1`, `[::1]` or `127.0.0.1` in Bind to local network address.

**Expected behavior**
Jellyfin listening only on the specified address.

**Server Logs**

```
[INF] Using LAN addresses: [::1/128,fc00::/7,fe80::/10,127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[INF] Using bind addresses: []
[INF] Using bind exclusions: []
[INF] Kestrel listening on All Addresses
[INF] Defined LAN addresses : [::1/128,fc00::/7,fe80::/10,127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[INF] Defined LAN exclusions : []
[INF] Using LAN addresses: [::1/128,fc00::/7,fe80::/10,127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
```

**Additional context**
After disabling IPv4, Jellyfin listens on all IPv6 addresses except `[::1]`.
Also, accessing Jellyfin directly instead of through a reverse proxy always gives the initial setup wizard instead of login/home page.

**Comment by crobibero** [comment]
This was fixed in https://github.com/jellyfin/jellyfin/pull/5773 for 10.8
