### ISSUE TITLE
Two bugs(green lines and mixed colors) in QSV acceleration and suggestions to fix them

### ISSUE THREAD

**Issue by 54601** [jellyfin/jellyfin#6809]
### Bug description:
Thanks for your attention and help as always. Those bugs I mentioned only occurs when hardware acceleration is enabled during QSV. You can see my detailed bug report in earlier versions here:
green lines: #5535 
mixed colors: #6524 
I think it's worth mentioning that the green lines' issue now has a new symptom being the image itself is looking greyish and the lines aren't exactly green. Please refer to down below.
Green lines:
![image](https://user-images.githubusercontent.com/80608553/140875197-4235edc1-7a51-4df0-ba8e-6ece2ede6d69.png)
Mixed colors:
![image](https://user-images.githubusercontent.com/80608553/140875341-7151b418-725f-4bd2-900e-f2c28026fd62.png)
-------------------------------------------------------------------
### Logs
And here's what the log says:
Green lines: 
`ffmpeg.exe -init_hw_device qsv=hw -filter_hw_device hw -i file:"{Hidden}\House.S01E01.Chi_Eng.BDrip.720X396-YYeTs.rmvb" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:1 -map 0:0 -map -0:s -codec:v:0 h264_qsv -preset 7 -look_ahead 0 -b:v 2777062 -maxrate 2777062 -bufsize 5554124 -profile:v:0 high -level 41 -g:v:0 72 -keyint_min:v:0 72 -sc_threshold:v:0 0 -vf "vpp_qsv=format=nv12" -start_at_zero -vsync -1 -codec:a:0 copy -strict -2 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "C:\ProgramData\Jellyfin\Server\transcodes\e69db036e53d724ce0a5beb4e89506f7%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "C:\ProgramData\Jellyfin\Server\transcodes\e69db036e53d724ce0a5beb4e89506f7.m3u8"`
Mixed colors:
`ffmpeg.exe -c:v hevc_qsv -hwaccel qsv -i file:"{Hidden}\Darkest.Hour.2017.2160p.BluRay.x265.10bit.SDR.DTS-HD.MA.TrueHD.7.1.Atmos-SWTYBLZ.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_qsv -preset 7 -look_ahead 0 -b:v 59360000 -maxrate 59360000 -bufsize 118720000 -profile:v:0 high -level 41 -g:v:0 72 -keyint_min:v:0 72 -sc_threshold:v:0 0 -vf "vpp_qsv=format=nv12" -start_at_zero -vsync -1 -codec:a:0 aac -ac 6 -ab 640000 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "C:\ProgramData\Jellyfin\Server\transcodes\34d91dd5751114c3901e425c2c817f2b%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "C:\ProgramData\Jellyfin\Server\transcodes\34d91dd5751114c3901e425c2c817f2b.m3u8"
`
----------------------------------------------
### How to fix it
Thankfully, I got some hands from a few very nice guys and they have offered the solution. I tested the code they offered, and it worked as intended.
Green lines:
`ffmpeg.exe -init_hw_device qsv=hw -filter_hw_device hw -i file:"{Hidden}\House.S01E01.Chi_Eng.BDrip.720X396-YYeTs.rmvb" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:1 -map 0:0 -map -0:s -codec:v:0 h264_qsv -preset 7 -look_ahead 0 -b:v 2777062 -maxrate 2777062 -bufsize 5554124 -profile:v:0 high -level 41 -g:v:0 72 -keyint_min:v:0 72 -sc_threshold:v:0 0 -vf "hwupload=extra_hw_frames=64,vpp_qsv=format=nv12" -start_at_zero -vsync -1 -codec:a:0 copy -strict -2 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "C:\ProgramData\Jellyfin\Server\transcodes\e69db036e53d724ce0a5beb4e89506f7%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "C:\ProgramData\Jellyfin\Server\transcodes\e69db036e53d724ce0a5beb4e89506f7.m3u8"`
Mixed colors:
`ffmpeg.exe -threads 0 -init_hw_device d3d11va=hw -init_hw_device qsv=intel@hw -hwaccel d3d11va -hwaccel_output_format d3d11 -i file:"{Hidden}\Darkest.Hour.2017.2160p.BluRay.x265.10bit.SDR.DTS-HD.MA.TrueHD.7.1.Atmos-SWTYBLZ\Darkest.Hour.2017.2160p.BluRay.x265.10bit.SDR.DTS-HD.MA.TrueHD.7.1.Atmos-SWTYBLZ.mkv" -c:v h264_qsv -preset 7 -look_ahead 0 -b:v 62870617 -maxrate 62870617 -bufsize 125741234 -profile:v high -level 41 -vf "hwmap=derive_device=qsv,vpp_qsv=format=nv12" -max_muxing_queue_size 2048 -y "C:\ProgramData\Jellyfin\Server\transcodes\tmp.mp4"`
I don't fully understand the reason behind those codes, but it seems the green line problem has something to do with a file called "jellyfin/MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs". I downloaded the source file of 10.7.7 and checked it. To my surprise, the bug seems to be fixed, at least according to @icedterminal , the guy who helped me, the necessary changes have been made.
`// When burning in graphical subtitles using overlay_qsv, upload videostream to the same qsv context.
            else if (isLinux && hasGraphicalSubs && (isQsvH264Encoder || isQsvHevcEncoder)
                     && !(isTonemappingSupportedOnQsv && isVppTonemappingSupported))
            {
                filters.Add("hwupload=extra_hw_frames=64");
            }`
However, judging by the logs, "hwupload=extra_hw_frames=64"  doesn't make it to the final commend. I wonder if this has something to do with the fact that I'm hosting it on a Win10 machine and deleting the flag "isLinux" will help.
---------------------------------
### Help needed
Embarrassingly, I don't know how to build from source code to test my theory. I tried to follow the guidelines in [https://jellyfin.org/docs/general/administration/building.html](url). But, a step by step mimication shows the following errors.
`>windows\build-jellyfin.ps1 -verbose

    目录: C:\Users\hidden\Desktop\jellyfin\dist

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         2021/11/9     13:21                jellyfin-win-nsis
Resolve-Path : 找不到路径“C:\Users\hidden\Desktop\jellyfin-ux”，因为该路径不存在。
所在位置 C:\Users\hidden\Desktop\jellyfin\windows\build-jellyfin.ps1:31 字符: 23
+ $ResolvedUXLocation = Resolve-Path $UXLocation
+                       ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\hidden\Desktop\jellyfin-ux:String) [Resolve-Path], ItemNotFoundEx
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.ResolvePathCommand

详细信息: Starting Build Process: Selected Environment is win-x64
详细信息: windowsversion-Architecture: win-x64
详细信息: InstallLocation: C:\Users\hidden\Desktop\jellyfin\dist\jellyfin-win-nsis
详细信息: DotNetVerbosity: Minimal
用于 .NET 的 Microsoft (R) 生成引擎版本 17.0.0+c9eb9dd64
版权所有(C) Microsoft Corporation。保留所有权利。

  正在确定要还原的项目…
 {Hidden}
CSC : error SA0001: XML comment analysis is disabled due to project configuration [C:\Users\hidden\Desktop\jellyfin\src\Jellyfin.Extensions\Jellyfin.Extensions.csproj]
  DvdLib -> C:\Users\hidden\Desktop\jellyfin\DvdLib\bin\Release\net6.0\DvdLib.dll
  Jellyfin.Data -> C:\Users\hidden\Desktop\jellyfin\Jellyfin.Data\bin\Release\net6.0\Jellyfin.Data.dll
详细信息: Finished`
Sorry about the Chinese, it basically says that it can't find a path called “C:\Users\hidden\Desktop\jellyfin-ux”, and the error happens in line 31, char 23 of build-jellyfin.ps1. As for the Error note in the end, I tried several versions of dotnet sdk, from 3.1 as recommended to 6.0. When I use 3.1, it says "error NETSDK1045: 当前 .NET SDK 不支持将 .NET 6.0 设置为目标。请将 .NET 5.0 或更低版本设置为目标，或使用支持 .NET 6.0 的 .NET SDK 版本。" I googled it and found out that it basically says that I need to download a higher version of donet, thus the 5.0 and 6.0 come in. 
I will be really happy if someone can tell me where I'm wrong, so I can debug for myself, or maybe fix those bugs in the next version? I think there are many people using intel system as a cheaper and more power-efficient way to host jellyfin, so this may help many people.
Any way, thank you for your time.

**Comment by icedterminal** [comment]
Possibly because of https://github.com/jellyfin/jellyfin/pull/5534#issuecomment-814981617 - which was linked in your original thread. The fix was placed in a development branch. Pending further changes.

Right below that someone using a docker container mentioned they no longer had issues in 10.7.6. That was the case for me as well. Upgrading to 10.7.7 brought it back. Building from source with suggested code snippet works. Ignoring all potential side effects of not handling subtitles. I don't use subtitles in any case.

There has no been official update in that thread for some time.

**Comment by 54601** [comment]
> Possibly because of [#5534 (comment)](https://github.com/jellyfin/jellyfin/pull/5534#issuecomment-814981617) - which was linked in your original thread. The fix was placed in a development branch. Pending further changes.
> 
> Right below that someone using a docker container mentioned they no longer had issues in 10.7.6. That was the case for me as well. Upgrading to 10.7.7 brought it back. Building from source with suggested code snippet works. Ignoring all potential side effects of not handling subtitles. I don't use subtitles in any case.
> 
> There has no been official update in that thread for some time.

I tried to downgrade it to 10.7.6, and the problem continues. It seems that the problem could have something to do with docker.
And, by the way, thank you again. This is the second time I get important help from you.

**Comment by icedterminal** [comment]
> I tried to downgrade it to 10.7.6, and the problem continues.

That's unfortunate.

Here's 10.7.7 [MediaBrowser.Controller.dll](https://github.com/jellyfin/jellyfin/files/7503438/MediaBrowser.Controller.zip) with the snippet of adjusted code.

For future reference, instead of opening a new issue for the same problem you're facing, add a comment to the exist open issue(s) and see if there is a status update.

**Comment by 54601** [comment]
> > I tried to downgrade it to 10.7.6, and the problem continues.
> 
> That's unfortunate.
> 
> Here's 10.7.7 [MediaBrowser.Controller.dll](https://github.com/jellyfin/jellyfin/files/7503438/MediaBrowser.Controller.zip) with the snippet of adjusted code.
> 
> For future reference, instead of opening a new issue for the same problem you're facing, add a comment to the exist open issue(s) and see if there is a status update.

Thank you, I'll remember that.

**Comment by 54601** [comment]
> > I tried to downgrade it to 10.7.6, and the problem continues.
> 
> That's unfortunate.
> 
> Here's 10.7.7 [MediaBrowser.Controller.dll](https://github.com/jellyfin/jellyfin/files/7503438/MediaBrowser.Controller.zip) with the snippet of adjusted code.
> 
> For future reference, instead of opening a new issue for the same problem you're facing, add a comment to the exist open issue(s) and see if there is a status update.

I tried with your file, it solved the first problem, many thanks. As for the second, I guess I'll just wait for the further versions.

**Comment by 54601** [comment]
> Using the new hwaccel pipeline in my next PR with jellyfin-ffmpeg 4.4.1 should fix these two issues. Stay tuned.

Great, I will.
