### ISSUE TITLE
[Issue]: Episode/Film Information no longer displayed.

### ISSUE THREAD

**Issue by Akirainblack** [jellyfin/jellyfin#6824]
### Please describe your bug

Metatdata is no longer displayed during playback:

Eg. watching Jeeves & Wooster
Season 1 Episode 1, if I brought up the timeline it would show the episode information:
Aunt Agatha wants Bertie to marry Honoria Glossop so that she will mould his character and infuse much needed strong blood in the Wooster line. But old chum Bingo Little is in love with her, so Bertie hatches a scheme to set things straight. Luckily, Jeeves has arrived to save Bertie from his own schemes (and hangovers).

Clearart is still displayed showing the title in the correct font.

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: Synology NAS
- Virtualization: docker
- Clients:browser, android-tv, android
- Browser: brave, edge
- FFmpeg Version:default with Jellyfin 10.7.7
- Playback Method: direct play
- Hardware Acceleration:none
- Plugins:none
- Reverse Proxy: none
- Base URL: none
- Networking: bridge
- Storage: local
```

### Jellyfin logs

```shell
N/A as wouldn't display this.
```

### FFmpeg logs

```shell
N/A
```

### Please attach any browser or client logs here

N/A

### Please attach any screenshots here

N/A as the information isn't displayed.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
What client did you have this issue with?

**Comment by Akirainblack** [comment]
I've tried with all, 12.3 Android TV, 2.4.0 Android and in a browser, which is why I figured this was the place to post.

**Comment by Akirainblack** [comment]
Any input at all other than the automated?

**Comment by Bond-009** [comment]
Closing as working as intended
