### ISSUE TITLE
Actors "overview" allways fetch in English

### ISSUE THREAD

**Issue by yresquirol** [jellyfin/jellyfin#6827]
From the default tag and image providers TheMovieDb provides more information..... however when using this provider, the overview about the actors is returned in English regardless of the language defined in the library.

-- Tested on Windows 10 and Ubuntu 20.04 --
![issue](https://user-images.githubusercontent.com/35172997/141377404-9c46e996-3f03-4edc-8f42-158587798b56.png)

**Comment by WWWesten** [comment]
I confirm it. Seems fetching the language variants not implemented yet see https://github.com/jellyfin/jellyfin/blob/master/MediaBrowser.Providers/Plugins/Tmdb/People/TmdbPersonProvider.cs



                item.SetProviderId(MetadataProvider.Tmdb, person.Id.ToString(CultureInfo.InvariantCulture));

InvariantCulture is English

**Comment by yresquirol** [comment]
> I confirm it. Seems fetching the language variants not implemented yet see https://github.com/jellyfin/jellyfin/blob/master/MediaBrowser.Providers/Plugins/Tmdb/People/TmdbPersonProvider.cs
> 
> ```
>             item.SetProviderId(MetadataProvider.Tmdb, person.Id.ToString(CultureInfo.InvariantCulture));
> ```
> 
> InvariantCulture is English

This only sets InvariantCulture to person.Id but I think the solution is within the function where that line is found. As soon as I have results I comment. Thanks

**Comment by yresquirol** [comment]
In version 10.8 (still in development) it is already fixed. I have taken that solution and implemented it in version 10.7.7
