### ISSUE TITLE
Blu-Ray Subtitle Positioning Incorrect

### ISSUE THREAD

**Issue by dathbe** [jellyfin/jellyfin#6833]
When displaying subtitles, the location is off for cropped videos.  It appears that the subtitles are coded to the to the top left of the original file, but when black bars are cropped out of a rip (either left/right black bars or top/bottom black bars), Jellyfin displays the subtitles relative to the top left of the remaining video area.  This leads to subtitles that are off-center and sometimes out of the visible area.  

E.g., on 4:3 material, the subtitles are shifted too far left, and for ultrawide material the subtitles are shifted down.  

VLC handles subtitles correctly, so I suspect this can be addressed by telling Jellyfin to display the subtitles relative to the SCREEN instead of relative to the cropped video area.  

See screenshots.
![a](https://user-images.githubusercontent.com/14321825/141605408-f892910c-3ed4-4c0a-84b9-f006c957d661.png)

I'm running server v10.7.7.  And I've tested this on an iPhone, casting to a Vizio TV, in the web player, and on Roku.  All clients have the same issue.  I'm not sure whether this applies to DVDs or not.  
![b](https://user-images.githubusercontent.com/14321825/141605698-0f4a3f16-253c-4ec5-8f4c-bba1d45abc2d.png)

**Comment by mathmaniac43** [comment]
I believe I am experiencing a similar issue. This may also be related to #4436.

This first image is from Jellyfin in Firefox desktop (fullscreen, but the issue persists when not fullscreen, and also exists in the Jellyfin app on my Android phone):
![image](https://user-images.githubusercontent.com/918497/147793193-f7e6b7a9-4693-4fe0-9a63-b50a7a3fe528.png)


This second image is from Celluloid on Linux Mint (Ubuntu Linux):
![image](https://user-images.githubusercontent.com/918497/147793208-215dc2d0-a3ef-4fae-8116-07f49143bab3.png)

**Comment by nyanmisaka** [comment]
Does the subtitle burn-in enabled? Can you share the ffmpeg transcoding log?

**Comment by mathmaniac43** [comment]
My understanding is that this example uses bitmapped subtitles. I am not sure why downloading and viewing the .mp4 file directly positioned them better... but I believe that burn-in settings are on automatic.

Here is the metadata for this particular video, which uses `DVDSUB`:
![image](https://user-images.githubusercontent.com/918497/147837401-16c3275e-c56d-48b2-8f98-195fdaf51428.png)

Here is the ffmpeg transcoding log from running about the first minute of the episode:
[FFmpeg.Transcode-2021-12-31_19-40-37_2cca5c5313c1d7eaa6fec949adb24a9c_357b2e62.log](https://github.com/jellyfin/jellyfin/files/7796945/FFmpeg.Transcode-2021-12-31_19-40-37_2cca5c5313c1d7eaa6fec949adb24a9c_357b2e62.log)

That video is from a DVD as well. I have a few videos from Blu-Rays as well, which use `PGSSUB` instead. Those subtitles seem to be added on the client and respect the subtitle positioning settings in Jellyfin.
