### ISSUE TITLE
Jellyfin fails media scan if emby book directory missing

### ISSUE THREAD

**Issue by CountMurphy** [jellyfin/jellyfin#684]
**Describe the bug**
Upon media scan, jellyfin reports failure if emby books directory missing

**To Reproduce**
1. Click setings
2. Scheduled tasks
3. Scan library

**Expected behavior**
Jellyfin should scan the library without error

**Logs**
System.IO.DirectoryNotFoundException: Could not find a part of the path '/var/lib/emby/root/default/Books'.

**Screenshots**

**System (please complete the following information):**
 - OS: Arch Linux
 - Browser: Firefox
 - Jellyfin Version: 10.0.2

**Additional context**
work around by creating a symbolic link for the emby directory.
in /var/lib:
ln -s jellyfin emby

**Comment by JustAMan** [comment]
Did you get it by migrating from existing Emby installation or from clean install?

**Comment by CountMurphy** [comment]
This was a migration. If migrations are not officially supported, I'm more than happy to close the ticket and just live with the sym link

**Comment by JustAMan** [comment]
@sparky8251 FYI - this seems to be yet another peculiarity in db schema

**Comment by sparky8251** [comment]
This is just one of those hard coded paths I guess. He could rewrite them in the database itself and it should fix it, he would just want to automate it since there will be so many.

**Comment by CountMurphy** [comment]
I can do that. Should I close the ticket?

**Comment by hawken93** [comment]
A recommendation is to symlink /var/lib/emby to /var/lib/jellyfin. I think future redo of the db will solve it properly over time so a workaround should be ok for now..
