### ISSUE TITLE
[Issue]: Playlist disapear when library is  scanned

### ISSUE THREAD

**Issue by Weels92** [jellyfin/jellyfin#6861]
### Please describe your bug

Hello there, i still have a problem, when i create a playlist of music, it's appear in playlist, but everytime a library is scanned the playlist vanish. do you know this problem ? how can i resolve it ? Thanks a lot for your help 

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS:Windows
- Virtualization:
- Clients:All
- Browser:ALL
- FFmpeg Version:ALL
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SightSpirit** [comment]
This could be related to #5481.

**Comment by Weels92** [comment]
Clean install repair my problem

**Comment by Bond-009** [comment]
Seems fixed
