### ISSUE TITLE
10.8.0 alpha2 Media library sort BUG.

### ISSUE THREAD

**Issue by shaino** [jellyfin/jellyfin#6863]
### Please describe your bug

It's a pity that my question in #6858 was closed.

In the web browser, select the media library sorting method other than NAME. Refresh the page and the sorting will revert to the default NAME sorting.

I downgraded alpha1 without this bug.

In order to eliminate the influence of Docker version, I went to the official website to download the .DEB upgrade package.
Server(and web) 10.8.0 alpha1 installation package is correct. This bug occurs when installing Server (and web) 10.8.0 alpha2 package.

The web installation package remains unchanged from 10.7.7. Only server is installed. The situation is the same. The Bug in Alpha2.

1 select sort
![Snipaste_2021-11-18_16-08-35](https://user-images.githubusercontent.com/34017325/142379261-e26bf51e-1183-49a9-b0a7-841597eb66c3.jpg)

2 selected other than NAME
![Snipaste_2021-11-18_16-07-27](https://user-images.githubusercontent.com/34017325/142379463-a1708918-3970-4585-9e8d-098b2926bf2b.jpg)

3 Refresh the page and the sorting will revert to the default NAME sorting
![Snipaste_2021-11-18_16-07-04](https://user-images.githubusercontent.com/34017325/142379541-20045ced-b209-400b-b907-d82680b0d0b0.jpg)

### Jellyfin Version

Other

### if other:

10.8.0 alpha2

### Environment

```markdown
- OS:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
This has been fixed in alpha-3
