### ISSUE TITLE
[Issue]: Zap2It

### ISSUE THREAD

**Issue by WWWesten** [jellyfin/jellyfin#6872]
### Please describe your bug

Zap2It doesn't reachable in my country. Even with Tor Browser, VPN and by any other alternative ways. Seems they blocked foreign visitors as me. Then it makes no sense to keep this provider at the core code, wasting resources. It's time to cut and move the code to a separate plugin. Whoever needs it (obviously, the residents of the USA and Canada) will download the plugin for themselves. 

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
I don’t see how this is a bug. Eventually we plan on moving all providers to plugins, but that time is not now.

**Comment by cvium** [comment]
We don't even have a Zap2It provider lol. This is basically the code you're complaining about https://github.com/jellyfin/jellyfin/blob/master/MediaBrowser.Providers/TV/Zap2ItExternalId.cs
