### ISSUE TITLE
[Issue]: 10.8.0 alpha2 User Settings

### ISSUE THREAD

**Issue by MRDJellyfin** [jellyfin/jellyfin#6875]
### Please describe your bug

 When selecting User Settings in the one corresponding to the Start (in Spanish INICIO I don't know how it is named in English), when I change the options from what to see at the Start except for the first one to "nothing" it does not make the changes and whenever I enter again to configure, they are the same by default, (I would like to point out that I only have Movies for the moment) in the stable version 10.7.7 for Windows 64 it maintains what I had selected, not the ones that are by default, in the Apha 2 version there are 10 options while in the stable 7 there are only 9, since a new call "Continue Reading" was added (I don't remember what I did to only show me my media)

### Jellyfin Version

Other

### if other:

Alpha 2

### Environment

```markdown
- OS:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
This issue has been fixed by https://github.com/jellyfin/jellyfin/pull/6854
