### ISSUE TITLE
[Issue]: users can't change their passwords

### ISSUE THREAD

**Issue by orzel** [jellyfin/jellyfin#6886]
### Please describe your bug

When a user has forgotten his password, he clicks on the link "forgot password", then enters his username, then clicks ok.

What we got:
a popup saying "Forgot Password" / "Please try again within your home network to initiate the password reset process."

What we expect : a way for a user to change his password.

Tested:
* with several users
* several versions of jellyfin (10.7.7 and 10.7.2)
* different browser (chomium and firefox)
* all tests were performed from the local network. The same one as specified in settings/advanced/networking/"LAN network"

Anyway, all users are actually NOT on the local network, they are outside of course. I don't understand why there would be such a restricting rule... I mean, fortunately facebook or google doesn't restrict passaword change to their internal network.. ?

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: linux
- Virtualization: docker
- Clients: chromium, 
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Please attach any screenshots here

![image](https://user-images.githubusercontent.com/1975747/142769791-9f5eaf71-0945-495c-8444-c60d74b90782.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cvium** [comment]
Please include server logs.

Regarding your last paragraph: We're not Google nor Facebook nor are their products self hosted. Terrible example :)
Our password reset feature is very simplistic and thus requires both LAN and server access.

**Comment by orzel** [comment]
I dont know where to look. On the server hosting the application, there's a directoy `jellyfin/log/`, with files like `FFmpeg.Transcode-2021-11-23_22-22-21_a211edbec92735fc4846f69cf9182302_05693e79.log` or `log_20211124.log`
When I reproduce this error, nothing is added to any of those files.

**Comment by zynexiz** [comment]
Just noticed the same issue here, there's no way to change a users password. Logging in with admin, I tried to change the password, but it still require the old password before I can change it (which is quite odd when you are the administrator, I don't know the users password). Clicking reset password seemed to clear it, but still can't enter a new one. When trying to enter one, it just trow an error "Invalid username or password. Please try again".

I also tried resetting it from the login page, found the pin in the jellyfin folder on the server. But the pin don't work, still complains that the password is incorrect.

**Comment by orzel** [comment]
I can confirm the bug is still there. I reproduced it just before writing this comment. I'm currently using jellyfin 10.8.9. It's still very annoying, our admin need to change password for users.
We haven't noticed any change in behaviour accross all the updates we did.

**Comment by cvium** [comment]
I can see that I should have closed this issue long ago. The password reset feature is very basic and insecure. Having it only be accessible on LAN is a compromise that has existed since before Jellyfin came into existence.

Feature request, not a bug.

**Comment by orzel** [comment]
I don't understand. Even on the LAN users can't change their password. I still have to find a way for any user to be able to to do so in any condition. If it's never possible, why does jellyfin propose this link ???

**Comment by ipkpjersi** [comment]
I'm also experiencing this FWIW, I think it is genuinely a bug (as in-secure as the password reset feature may be, I think it's still a bug) as I have 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16 and Jellyfin is being hosted on a PC that has a 192.168.3.x IP, and I'm accessing it from another PC that has a 192.168.3.x IP but it does not detect it as the same network. Though since it's not a secure feature currently, I'm not expecting this to be fixed, but just thought I would share my experiences.
