### ISSUE TITLE
[Issue]: admin can't change a user password

### ISSUE THREAD

**Issue by orzel** [jellyfin/jellyfin#6887]
### Please describe your bug

Users can't change their password by themselves  (see #6886). So I try to change it as admin, going to the user account, "password" tab, and add a password (twice)

I got a popup "Login Failure" / "Invalid username or password. Please try again."

I expect the password to be changed (and ideally a mail sent to the user providing the new password).

It's huge. I mean, i have no way to allow access to several users, they've been blocked for weeks out of the site, and even as admin I can't do anything..

Tested with
* jellyfin 10.7.2 and 10.7.7
* firefox and chromium

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: Linux / Gentoo
- Virtualization: docker
- Clients: linux
- Browser: chromium/firefox
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Please attach any screenshots here

![image](https://user-images.githubusercontent.com/1975747/142770109-815798f6-4052-4486-bdd7-0cd0a8a38bb4.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cvium** [comment]
Please include logs

**Comment by orzel** [comment]
Ok. When I reproduce, this line is logged : 

> Authentication request for "xx" has been denied because this account is currently disabled

And indeed, the "disabled" was selected in the user profile. Unchecking fixed the problem. I dont know why it was disabled, probably some security feature somewhere.
May I respectfully propose that in this case, the admin get a meaningful message instead of `Invalid username or password` ? For example the one found in log is useful to understand what happens.
