### ISSUE TITLE
10.8 Alpha 2 Gender not in alphabetical order

### ISSUE THREAD

**Issue by MRDJellyfin** [jellyfin/jellyfin#6892]
### Please describe your bug

When selected in the option to the top of the right side Genre (in Windows 10 64), it does not put it alphabetically in descending order as in the stable version 10.7.7.

![image](https://user-images.githubusercontent.com/82923908/142802421-bd886868-482b-4d7e-9cb0-d2e03fa4dc03.png)

stable 10.7.7

![image](https://user-images.githubusercontent.com/82923908/142802281-2091b9f1-88c5-49ed-945d-0c4eed1d93aa.png)

### Jellyfin Version

Other

### Environment

```markdown
- OS:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ianjazz246** [comment]
This is caused by the web client. The web client makes API requests to /Genres with SortBy=Random. If SortBy=SortName, the genres are in alphabetical order

**Comment by MRDJellyfin** [comment]
Thanks for the answer and sorry for my ignorance, but how could I make it appear correctly in Windows 10 64 on Aplha 2
