### ISSUE TITLE
VolleyError.com.Android.Volley.ServerError AndroidTV with LiveTV 

### ISSUE THREAD

**Issue by Japhys** [jellyfin/jellyfin#6901]
I just got a new Sony Bravia Android TV. Jellyfin runs beautifully, 4K not a problem. Only thing that does not work is LiveTV.

I am using the lastest version of Jellyfin on Win10 on a very fast network
M3uTuner with  hand full of streams without TVGuide
I get this error before I even see the channels, straight after selecting LiveTV

`[2021-11-24 07:29:58.165 +01:00] [WRN] [38] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://example.com:8096/LiveTv/Recordings?UserId=removed&IsInProgress=true&Fields=CanDelete%2CPrimaryImageAspectRatio&EnableTotalRecordCount=false&EnableImageTypes=Primary%2CThumb%2CBackdrop" to "removed" in 0:00:04.1384213 with Status Code 500`

**Comment by Japhys** [comment]
Any idea anyone?

**Comment by zhenry9** [comment]
Same issue for me

**Comment by Japhys** [comment]
I did look into his any further because I was also planning to get a new fast linux machine and figured it would solve itself miraculously when using Linux Mint, Jellyfin Docker and Android TV. Unfortunately it doesn't work with this setup either. I see this in the log

`[hls @ 0x5614d61e1e40] Opening 'https://cbcnewshd-f.akamaihd.net/i/cbcnews_1@8981/segment23397887_2500_av-p.ts?sd=10' for reading
[hls @ 0x5614d61e1e40] Opening 'https://cbcnewshd-f.akamaihd.net/i/cbcnews_1@8981/segment23397888_2500_av-p.ts?sd=10' for reading
[NULL @ 0x5614d684adc0] non-existing PPS 0 referenced
[h264 @ 0x5614d684cd80] non-existing PPS 0 referenced
[h264 @ 0x5614d684cd80] decode_slice_header error
[h264 @ 0x5614d684cd80] no frame!`
