### ISSUE TITLE
This client isn't compatible with the media and the server isn't sending a compatible media format.

### ISSUE THREAD

**Issue by TheSmashy** [jellyfin/jellyfin#6905]
I get this error with every file I try to play, including MP3s.
![image](https://user-images.githubusercontent.com/25392589/143464152-c297659a-cacb-4f34-b3f3-2a4edb2097f2.png)

**Logs**
All my logs are empty.
-rw-r--r-- 1 jellyfin jellyfin    0 Nov 25 08:28 FFmpeg.Transcode-2021-11-25_08-28-31_959f7b812e3a7315cf6f1d7d57435148_1047e80c.log
-rw-r--r-- 1 jellyfin jellyfin    0 Nov 25 08:28 FFmpeg.Transcode-2021-11-25_08-28-31_959f7b812e3a7315cf6f1d7d57435148_a2a59f5a.log
-rw-r--r-- 1 jellyfin jellyfin    0 Nov 25 08:28 FFmpeg.Transcode-2021-11-25_08-28-45_959f7b812e3a7315cf6f1d7d57435148_410fcfe4.log
-rw-r--r-- 1 jellyfin jellyfin    0 Nov 25 08:28 FFmpeg.Transcode-2021-11-25_08-28-45_959f7b812e3a7315cf6f1d7d57435148_950666df.log
-rw-r--r-- 1 jellyfin jellyfin    0 Nov 25 08:29 FFmpeg.Transcode-2021-11-25_08-29-05_959f7b812e3a7315cf6f1d7d57435148_5f4c4301.log
-rw-r--r-- 1 jellyfin jellyfin    0 Nov 25 08:29 FFmpeg.Transcode-2021-11-25_08-29-05_959f7b812e3a7315cf6f1d7d57435148_68c4e751.log
-rw-r--r-- 1 jellyfin jellyfin    0 Nov 25 08:29 FFmpeg.Transcode-2021-11-25_08-29-25_959f7b812e3a7315cf6f1d7d57435148_9acc9ce2.log
-rw-r--r-- 1 jellyfin jellyfin    0 Nov 25 08:29 FFmpeg.Transcode-2021-11-25_08-29-25_959f7b812e3a7315cf6f1d7d57435148_a8fae602.log
-rw-r--r-- 1 jellyfin jellyfin    0 Nov 25 08:30 FFmpeg.Transcode-2021-11-25_08-30-54_e3b0bb5889b8b423d92a7bd5ee9be42e_4d6a846a.log
-rw-r--r-- 1 jellyfin jellyfin    0 Nov 25 08:30 FFmpeg.Transcode-2021-11-25_08-30-54_e3b0bb5889b8b423d92a7bd5ee9be42e_9ac0e491.log
-rw-r--r-- 1 jellyfin jellyfin    0 Nov 25 08:31 FFmpeg.Transcode-2021-11-25_08-31-22_5e2eca153554d4ecd1a3b71e2836ce5c_c839c658.log
-rw-r--r-- 1 jellyfin jellyfin    0 Nov 25 08:31 FFmpeg.Transcode-2021-11-25_08-31-22_5e2eca153554d4ecd1a3b71e2836ce5c_da40c0a1.log
-rw-r--r-- 1 jellyfin jellyfin    0 Nov 25 08:42 FFmpeg.Transcode-2021-11-25_08-42-46_7b0e8fe6e6c945f23ceb2d2d66d5ee96_a21dbe3b.log
-rw-r--r-- 1 jellyfin jellyfin    0 Nov 25 08:42 FFmpeg.Transcode-2021-11-25_08-42-46_7b0e8fe6e6c945f23ceb2d2d66d5ee96_a3b0fd5d.log
-rw-r--r-- 1 jellyfin jellyfin    0 Nov 25 08:55 FFmpeg.Transcode-2021-11-25_08-55-14_7b0e8fe6e6c945f23ceb2d2d66d5ee96_5dd52469.log
-rw-r--r-- 1 jellyfin jellyfin    0 Nov 25 08:55 FFmpeg.Transcode-2021-11-25_08-55-15_7b0e8fe6e6c945f23ceb2d2d66d5ee96_d322f469.log
-rw-r--r-- 1 jellyfin jellyfin    0 Nov 22 02:00 jellyfin20211121.log
-rw-r--r-- 1 jellyfin jellyfin    0 Nov 22 21:51 jellyfin20211122.log
-rw-r--r-- 1 jellyfin jellyfin    0 Nov 24 00:45 jellyfin20211123.log
-rw-r--r-- 1 jellyfin jellyfin    0 Nov 25 02:00 jellyfin20211124.log
-rw-r--r-- 1 jellyfin jellyfin    0 Nov 25 08:55 jellyfin20211125.log

 - OS: Raspbian GNU/Linux 10 (buster)
 - Jellyfin Version: 10.7.7.0
 - Hardware settings & device: OpenMAX OMX on Raspberry Pi 4
 - Reverse proxy: no
 - Other hardware notes: Media stored on external USB 3.0 HDD
 
**Client System (please complete the following information):**
 - Device: Dell G5 5000 PC, Lenovo ThinkPad, Samsung Galaxy Android phone.
 - OS: Android, Windows
 - Client: Web/Browser, Android, Electron
 - Browser (if Web client): Firefox, Chrome
 - Client and Browser Version: 94.0.2 and 96.0.4664.45

**Comment by TheSmashy** [comment]
I got an FFMpeg log:
```
FFmpeg.Transcode-2021-11-25_12-04-39_db74336c45134b8eb418a1c1e6970d86_
FFmpeg.Transcode-2021-11-25_12-04-39_db74336c45134b8eb418a1c1e6970d86_589891f8.log
FFmpeg.Transcode-2021-11-25_12-04-39_db74336c45134b8eb418a1c1e6970d86_9257231f.log
root@jellyfin:/var/log/jellyfin# more FFmpeg.Transcode-2021-11-25_12-04-39_db74336c45134b8eb418a1c1e6970d86_589891f8.log
/audio/db74336c-4513-4b8e-b418-a1c1e6970d86/stream

{"Protocol":0,"Id":"db74336c45134b8eb418a1c1e6970d86","Path":"/mnt/bigdisk/Music/kleptones/kleptones
 - 24h split/The Kleptones - 24 Hours - 1-01 - 0700 Still Start.mp3","EncoderPath":null,"EncoderProt
ocol":null,"Type":0,"Container":"mp3","Size":4497832,"Name":"The Kleptones - 24 Hours - 1-01 - 0700
Still Start","IsRemote":false,"ETag":"f13c6a7d50d63b11c0388c21f11161e4","RunTimeTicks":1833795968,"R
eadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTrans
coding":true,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"Require
sOpening":false,"OpenToken":null,"RequiresClosing":false,"LiveStreamId":null,"BufferMs":null,"Requir
esLooping":false,"SupportsProbing":true,"VideoType":null,"IsoType":null,"Video3DFormat":null,"MediaS
treams":[{"Codec":"mp3","CodecTag":null,"Language":null,"ColorRange":null,"ColorSpace":null,"ColorTr
ansfer":null,"ColorPrimaries":null,"Comment":null,"TimeBase":"1/14112000","CodecTimeBase":"1/44100",
"Title":null,"VideoRange":null,"localizedUndefined":null,"localizedDefault":null,"localizedForced":n
ull,"DisplayTitle":"MP3 - Stereo","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLay
out":"stereo","BitRate":191698,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":2,"Sa
mpleRate":44100,"IsDefault":false,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":nul
l,"RealFrameRate":null,"Profile":null,"Type":0,"AspectRatio":null,"Index":0,"Score":null,"IsExternal
":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"
SupportsExternalStream":false,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec"
:"mjpeg","CodecTag":null,"Language":null,"ColorRange":null,"ColorSpace":"bt470bg","ColorTransfer":nu
ll,"ColorPrimaries":null,"Comment":"Cover (front)","TimeBase":"1/90000","CodecTimeBase":"0/1","Title
":null,"VideoRange":null,"localizedUndefined":null,"localizedDefault":null,"localizedForced":null,"D
isplayTitle":null,"NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRa
te":null,"BitDepth":8,"RefFrames":1,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault
":false,"IsForced":false,"Height":1430,"Width":1430,"AverageFrameRate":null,"RealFrameRate":90000,"P
rofile":"Baseline","Type":3,"AspectRatio":"1:1","Index":1,"Score":null,"IsExternal":false,"DeliveryM
ethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalSt
ream":false,"Path":null,"PixelFormat":"yuvj420p","Level":-99,"IsAnamorphic":null}],"MediaAttachments
":[],"Formats":[],"Bitrate":196219,"Timestamp":null,"RequiredHttpHeaders":{},"TranscodingUrl":null,"
TranscodingSubProtocol":null,"TranscodingContainer":null,"AnalyzeDurationMs":null,"DefaultAudioStrea
mIndex":null,"DefaultSubtitleStreamIndex":null}

/usr/lib/jellyfin-ffmpeg/ffmpeg -i file:"/mnt/bigdisk/Music/kleptones/kleptones - 24h split/The Klep
tones - 24 Hours - 1-01 - 0700 Still Start.mp3" -threads 0 -vn -ab 128000 -ac 2 -ar 44100 -id3v2_ver
sion 3 -write_id3v1 1 -y "/var/lib/jellyfin/transcodes/e446066058b5b3143eded7c39293bfdd"


ffmpeg version 4.3.2-Jellyfin Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-2)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disa
ble-doc --disable-ffplay --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-gp
l --enable-version3 --enable-static --enable-libfontconfig --enable-fontconfig --enable-gmp --enable
-gnutls --enable-libass --enable-libbluray --enable-libdrm --enable-libfreetype --enable-libfribidi
--enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enabl
e-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --tool
chain=hardened --enable-cross-compile --enable-omx --enable-omx-rpi --enable-mmal --arch=armhf --cro
ss-prefix=/usr/bin/arm-linux-gnueabihf-
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
file:/mnt/bigdisk/Music/kleptones/kleptones - 24h split/The Kleptones - 24 Hours - 1-01 - 0700 Still
 Start.mp3: No such file or directory

```

**Comment by TheSmashy** [comment]
Fixed it. Sorry.

**Comment by garret2wheels** [comment]
I get the same situation.  How did you fix it?

**Comment by TheSmashy** [comment]
My external storage was offline.  Check yours with `df -h`
