### ISSUE TITLE
Support base URL configuration inside Jellyfin

### ISSUE THREAD

**Issue by joshuaboniface** [jellyfin/jellyfin#691]
**Describe the feature you'd like**
Jellyfin should support user-configurable base URLs, e.g. `my.domain/jellyfin/`

**Additional context**
This is a very common deployment configuration for self-hosted services, to allow users to specify multiple services by path under a single domain on a single port, especially behind a reverse proxy.

UI configuration would be related to #192 and should likely be included with it.

**Comment by JustAMan** [comment]
Seems to be a duplicate of #337

**Comment by joshuaboniface** [comment]
@JustAMan Kinda, I'd consider this the "super-issue" of that one.
