### ISSUE TITLE
[Issue]: trying to change servername fails

### ISSUE THREAD

**Issue by brianjmurrell** [jellyfin/jellyfin#6910]
### Please describe your bug

When I try to change the Server Name I get an error:

There was an error processing the request. Please try again later.

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: CentOS 8
- Virtualization: None
- Clients: UI
- Browser: Chrome
- FFmpeg Version: N/A
- Playback Method: N/A
- Hardware Acceleration: N/A
- Plugins: N/A
- Reverse Proxy: None
- Base URL: None
- Networking: Native
- Storage: Local
```

### Jellyfin logs

```shell
Nothing in the logs
```

### FFmpeg logs

```shell
N/A
```

### Please attach any screenshots here

![image](https://user-images.githubusercontent.com/559317/143633846-af276293-c2f7-4da0-a2b8-4a55f6364dbe.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brianjmurrell** [comment]
Not stale

**Comment by nielsvanvelzen** [comment]
Not much we can help with without server/client logs.

**Comment by brianjmurrell** [comment]
As I mentioned in the original description, there was nothing logged as a result of this.

**Comment by crobibero** [comment]
Can't reproduce on master
