### ISSUE TITLE
[Issue]: Albums missing on newly added artists / songs

### ISSUE THREAD

**Issue by kavemang** [jellyfin/jellyfin#6919]
### Please describe your bug

I recently added a couple new artists/albums/songs to my music library via lidarr, the artists and songs appear but the albums are missing. I can play the songs from the artist page and if I try clicking into the associated album from the song itself the page hangs on the loading animation. The albums also do not appear under the artist page 

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: Ubuntu 20 LTS
- Virtualization: Docker
- Clients: multiple
- Browser: vivaldi but N/A
- Plugins: AudioDB, MusicBrainz
- Reverse Proxy: Caddy
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by cvium** [comment]
Please include the logs...........

**Comment by kavemang** [comment]
Should i pull logs: 
-while viewing one of the new arists with this issue 
-or while lidarr is in the middle of loading a new arists content 
-Or while trying a metadata refresh?
