### ISSUE TITLE
[Issue]: GPU crashes when transcoding using VAAPI

### ISSUE THREAD

**Issue by NCLI** [jellyfin/jellyfin#6921]
### Please describe your bug

On both the stable and unstable docker image, the GPU of my 2200g pro often crashes, or at least enters some kind of degraded state, when trying to transcode files, requiring me to reboot the system in order to use the GPU for anything. It seems to consistently happen for heavy transcodes, such as 4K -> 1080p. Sometimes it brings the entire system down with it.

Looking at Radeontop, I see that "Graphics pipe" goes straight to 100%, and never comes back down.

### Jellyfin Version

10.7.7

### if other:

10.0.8.0

### Environment

```markdown
- OS: Ubuntu 20.04
- Virtualization: Docker
- Clients: Browser
- Browser: Firefox
- FFmpeg Version: 4.3.2-Jellyfin
- Playback Method: Transcode
- Hardware Acceleration: VAAPI
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

[dmesg.txt](https://github.com/jellyfin/jellyfin/files/7613357/dmesg.txt)
[dmesg2.txt](https://github.com/jellyfin/jellyfin/files/7613356/dmesg2.txt)

### Jellyfin logs

[Log.txt](https://github.com/jellyfin/jellyfin/files/7613354/Log.txt)

### FFmpeg logs

[TranscodeLog1.txt](https://github.com/jellyfin/jellyfin/files/7613358/TranscodeLog1.txt)
[TranscodeLog2.txt](https://github.com/jellyfin/jellyfin/files/7613359/TranscodeLog2.txt)
[TranscodeLog3.txt](https://github.com/jellyfin/jellyfin/files/7613360/TranscodeLog3.txt)
[TranscodeLog4.txt](https://github.com/jellyfin/jellyfin/files/7613355/TranscodeLog4.txt)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NCLI** [comment]
[Log.txt](https://github.com/jellyfin/jellyfin/files/7613354/Log.txt)
[TranscodeLog4.txt](https://github.com/jellyfin/jellyfin/files/7613355/TranscodeLog4.txt)
[dmesg2.txt](https://github.com/jellyfin/jellyfin/files/7613356/dmesg2.txt)
[dmesg.txt](https://github.com/jellyfin/jellyfin/files/7613357/dmesg.txt)
[TranscodeLog1.txt](https://github.com/jellyfin/jellyfin/files/7613358/TranscodeLog1.txt)
[TranscodeLog2.txt](https://github.com/jellyfin/jellyfin/files/7613359/TranscodeLog2.txt)
[TranscodeLog3.txt](https://github.com/jellyfin/jellyfin/files/7613360/TranscodeLog3.txt)

**Comment by nyanmisaka** [comment]
It's an upstream issue in amdgpu kernel driver. Try to downgrade or upgrade kernel or firmware may resolve it.
https://gitlab.freedesktop.org/mesa/mesa/-/issues/5359
https://gitlab.freedesktop.org/mesa/mesa/-/issues/5162
