### ISSUE TITLE
Provide 'help' page for command line users

### ISSUE THREAD

**Issue by ploughpuff** [jellyfin/jellyfin#693]
There are numerous options/switches available in Jellyfin but no help page is available to remind users what they are when executing from the command line.  To address this, I started putting together a crude 'help' page [here](https://github.com/ploughpuff/jellyfin/commit/c59cfc42b1e9a327fa2dcca858b78b49e5771962#diff-4ee36df3f7cae4f4687c920c303b76e7)

During this work, I wondered about leveraging an existing args handler (a basic getopt respin), such as [commandlineparser](https://github.com/commandlineparser/commandline), to offer a better route for improvements.

Unfortunately, it doesn't appear Jellyfin adheres to the POSIX syntax for command line options, namely single hyphen for single chars, and double hyphen for words (example: -a --all, -h, --human-readable)? 
 Instead it uses single hyphens everywhere (example: -configdir -ffmpeg).  This presents a problem with all the packages I've tested so far, but is anyone aware of a C# package that would work?

Alternatively, we modify all the switches to POSIX syntax.  Possibly the right answer, but what are the implications?

I'm posting this issue for feedback on the idea (of creating a help page) and best way forward (if any)...

**Comment by joshuaboniface** [comment]
I think switching to POSIX standards is ideal. Most of the time these flags are wrapped by something else (a Dockerfile, systemd unit file, etc.) so changing them should be straightforward. I definitely support having a help page on the CLi, especially since we're distributing portable standalone binaries with no packaging now.

**Comment by ploughpuff** [comment]
Closing issue now PR has been delivered and tested working.

Use --help or -h to display what switches are available.
