### ISSUE TITLE
Jellyfin Server for Home Assistant and and Alexa skill?

### ISSUE THREAD

**Issue by leaderdog** [jellyfin/jellyfin#6960]
Hi,

I'm currently working on getting a home automation setup for my friend who is quadriplegic with speech issues.  I've had to go through many hoops and issues, but I'm not any good with programming, so we have to use plex server which is natively on Home Assistant and the Plex skill on Alexa.  It's real hit or miss, it works great for a bit and then just doesn't.

I know someone created an alexa jellyfin skill, but it's self hosted and quite honestly it didn't work when I tried (more than likely my fault) but my friend lives in a care home, and we don't have access to the main routers so I need an Alexa skill that works through Alexa itself.

My friend has an acquired brain injury, so everything was affected including memory and speech so we need to keep things simple so a different program that is made for people like him we use to record phrases that then we pass to Alexa via routines.  We use it mainly for playlists and just put all his music into one, and have to create a couple different playlists for him to call his favorite bands since Alexa cannot understand his speech at all.

There is a Jellyfin Media player some one created via HACS but that's just a player.  I need to host the server on the laptop we're running through the Home Assistant OS.

I'm hoping an official version of these could be made, or some kind soul that has the technical knowledge to create this would amazing too.

**Comment by Anti-ctrl** [comment]
As a workaround for the time: Install Ubuntu on the Laptop and install Docker on it with HA Supervised.
[https://peyanski.com/how-to-install-home-assistant-supervised-official-way/#Home_Assistant_Supervised_method](url)

The above Link is a great tutorial which I used to setup HA Supervised in Docker on my RPi 4B. Should work the same on Ubuntu LTS. You can then install Jellyfin alongside. Either as another Docker container, or as an independent service.

Best wishes to you and your friend!
