### ISSUE TITLE
[Issue]: 10.8-unstable Docker - Memory leak ?

### ISSUE THREAD

**Issue by Ge082** [jellyfin/jellyfin#6970]
### Please describe your bug

Running 10.8-unstable for testing, noticed something strange.
RAM doesn't seem to be cleared when client disconnects, it results in RAM constantly rising up in total usage

No one was using jellyfin here except me, all I did was clicking on content that does contain background images. Closing webclient doesn't clear anything. The only way to clear it is to restart the container.

Best way to do it is activate background image in settings and click on any content that displays background image, Ram will build up but rarely clears out. Logs doesn't show anything anormal

Same stuff happen in 10.8-hwa

### Jellyfin Version

Other

### if other:

10.8-unstable

### Environment

```markdown
- OS: OMV5
- Virtualization: Docker
- Clients: web-client
- Browser:edge
- FFmpeg Version: /
- Playback Method: /
- Hardware Acceleration: /
- Plugins: /
- Reverse Proxy: /
- Base URL: /
- Networking: /
- Storage: /
```

### Please attach any screenshots here

![Sans titre 18](https://user-images.githubusercontent.com/76789478/145660385-acdfbcce-be1f-47b7-88f3-415fcddafacb.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
It is only a memory leak if the memory usage continues to climb without ever stopping. There's a lot of stuff being cached in memory, so high usage isn't necessarily any indication.

**Comment by Ge082** [comment]
Indeed, it seems to stabilize at some points, if you don't mind the issue can be closed
