### ISSUE TITLE
[Issue]: *.jpe files instead of *.jpg

### ISSUE THREAD

**Issue by devenator** [jellyfin/jellyfin#6972]
### Please describe your bug

I've noticed a few days ago, that jellyfin started to create *.jpe files instead of *.jpg (-thumb, posters, extraart etc). At the same time, the error below appeared in the logs. Looking at the git log, i've suspected the MIME-Changes 707e5bab9787a4275345d35819af98eb9a682199, and after a rollback to December, 2nd, commit a474e4cf3b2843e2602b7cea28065f3b928e0cf1 it was back to normal.

Can someone reproduce this?

### Jellyfin Version

Other

### if other:

10.8.x latest commit 4d446eb614584b27366d5994bd01552ed4108b70

### Environment

```markdown
- OS: Debian (packages built with docker-image)
- Virtualization: no
```

### Jellyfin logs

```shell
[2021-12-10 19:14:29.307 +01:00] [ERR] Image conversion failed for "/TVShows/Late Show with Stephen Colbert/The Late Show with Stephen Colbert - 2021.12.09 - Michael B. Jordan-thumb.jpe"
System.NotImplementedException: The method or operation is not implemented.
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.ConvertImage(String inputPath, String outputPath)
   at Emby.Drawing.ImageProcessor.GetSupportedImage(String originalImagePath, DateTime dateModified)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by devenator** [comment]
Thanks a lot!

**Comment by moeffju** [comment]
Is there any way to fix the wrong library entries and make the logs quieter? Even after updating to 10.8.0-alpha5 the error persists in the logs. Refresh did not seem to make a difference.
