### ISSUE TITLE
The configdir should default to the proper XDG config location

### ISSUE THREAD

**Issue by joshuaboniface** [jellyfin/jellyfin#698]
**Is your feature request related to a problem? Please describe.**
The current defaults with configdir are not XDG compliant.

**Describe the solution you'd like**
The configdir should default to `~/.config/jellyfin` (the XDG specification location for configuration data) now that this location is separated from the main data directory.

**Describe alternatives you've considered**
Any other solution is manual, and we should conform to the spec.

**Additional context**
From Reddit: https://old.reddit.com/r/jellyfin/comments/ahmzlo/request_portable_version_of_jellyfin/eernw46/

**Comment by joshuaboniface** [comment]
CC @Bond-009

**Comment by joshuaboniface** [comment]
@Bond-009 I did forget that, right. This is more for discussion, maybe it might be worthwhile to do this sometimes, e.g. if its creating a fresh data dir?

@KristupasSavickas When packaged, yes, but the portable binaries can be run as a local user.

**Comment by Pimmelton** [comment]
For the sake of clarity, it should be emphasized that XDG compliant defaults for config, data and transient cached data are most relevant to a user running a personal server instance as that user, whether from a local directory extracted from an archive, or eventually in the form of something like snaps or flatpaks (installed at the system level but intended to be run by individual users).

Defaults for server-level instances and truly portable instances are going to be different.  The former will depend on the conventions of the local OS environment and the latter should be entirely local to where the portable instance is being run from (eg. a folder on a USB device).

**Comment by joshuaboniface** [comment]
@Pimmelton Correct, we're already doing several checks for the CLI flag (used extensively in the packaging infrastructure), the XDG_* environment variables, and only then falling back to these default home directories. A portable setup (basically starting with a script) could easily set `configdir` to be under `datadir` without any issues, which would replicate the default configuration.

However the upgrade issue is indeed a concern, so it should probably check to see if a `<datadir>/config` directory exists first, and then use that if it does, before defaulting elsewhere. i however don't know if that's ideal from the C# side - CC @Bond-009 @JustAMan

**Comment by ploughpuff** [comment]
There are three paths that can be driven from outside the software 1)datadir, 2)configdir and 3)logdir.  The logic for settings these three paths is as follows:

datadir:
```
IF      env var $JELLYFIN_DATA_PATH
ELSE IF cli switch --programdata
ELSE IF windows, use <Environment.SpecialFolder.ApplicationData>/jellyfin
ELSE IF $XDG_DATA_HOME then $XDG_DATA_HOME/jellyfin
ELSE    $HOME/.local/share/jellyfin
```
configdir:
```
IF      $JELLYFIN_CONFIG_DIR
ELSE IF --configdir
ELSE    <datadir>/config
```
logdir:
```
IF      $JELLYFIN_LOG_DIR
ELSE IF --logdir
ELSE    <datadir>/log
```

The following observations can be made:
1. Not fully XDG compliant (aka this issue!).  Suggestion is to move config folder under $XDG_CONFIG_HOME, but care must be taken to use any existing folders (eg `<datadir>/config`) before creating new XDG locations.
1. The Cache folder is currently at `<datadir>/cache`.  This needs moving to $XDG_CACHE_HOME.
1. Why do ENV settings take precedence over CLI switches?  Surely this is the wrong way round.
1. Should Windows perform similar to XDG or ok to use one folder? (https://stackoverflow.com/questions/43853548/xdg-basedir-directories-for-windows)
1. User requires ability to run from complete portable location.  A new '--portable' switch could be used to indicate when to create folder at `<exe location>/jellyfin`, otherwise how do we tell?

To that end, I've come up with the following logic for review:
datadir:
```
IF      --programdata
ELSE IF $JELLYFIN_DATA_PATH
ELSE IF --portable, use <exe location>/jellyfin (possibly better name for folder otherwise jellyfin/jellyfin/ etc.?)
ELSE IF windows, use <Environment.SpecialFolder.ApplicationData>/jellyfin (possibly change to LocalApplicationData?)
ELSE IF $XDG_DATA_HOME then use $XDG_DATA_HOME/jellyfin
ELSE    use $HOME/.local/share/jellyfin
```
configdir:
```
IF      --configdir
ELSE IF $JELLYFIN_CONFIG_DIR
ELSE IF --portable, use <datadir>/config
ELSE IF windows, use <datadir>/config
ELSE IF <datadir>/config exists, use that
ELSE IF $XDG_CONFIG_HOME use $XDG_CONFIG_HOME/jellyfin
ELSE    $HOME/.config/jellyfin
```
logdir:
```
IF      --logdir
ELSE IF $JELLYFIN_LOG_DIR
ELSE    <datadir>/log
```
The cache folder currently hangs off `<datadir>`  This would need moving too:
```
IF      windows, use <datadir>/cache
ELSE IF $XDG_CACHE_HOME use $XDG_CACHE_HOME/jellyfin
ELSE    $HOME/.cache/jellyfin
```

Thoughts?

**Comment by JustAMan** [comment]
I like the proposal.

**Comment by joshuaboniface** [comment]
Sounds good to me!

>Not fully XDG compliant (aka this issue!). Suggestion is to move config folder under $XDG_CONFIG_HOME, but care must be taken to use any existing folders (eg <datadir>/config) before creating new XDG locations.
> The Cache folder is currently at <datadir>/cache. This needs moving to $XDG_CACHE_HOME.
> Why do ENV settings take precedence over CLI switches? Surely this is the wrong way round.

Agreed, CLI flags should be first not the Envvars - I think I suggested the alternate for some reason early on, but I'd rather this be POSIX compliant.

> Should Windows perform similar to XDG or ok to use one folder? (https://stackoverflow.com/questions/43853548/xdg-basedir-directories-for-windows)

That's a good point, I think whatever the standard seems to be should be our goal.

> User requires ability to run from complete portable location. A new '--portable' switch could be used to indicate when to create folder at <exe location>/jellyfin, otherwise how do we tell?

I think for this, we should write a (simple!) wrapper script to set the options to a single folder - I'd rather not bake this logic into the code if we can avoid it. `jellyfin-portable.ps1` or so.

**Comment by ploughpuff** [comment]
Regarding portable:
If a startup script supplied --datadir then our current approach would happily create `<datadir>/config` and `<datadir>/log`, which is ideal.  As the default behaviour needs to become XDG then so the config and log become something like:

```
IF      --configdir
ELSE IF $JELLYFIN_CONFIG_DIR
ELSE IF --datadir, use <datadir>/config
ELSE IF <datadir>/config exists, use that
ELSE IF windows, use <datadir>/config (or adopt something similar to XDG)
ELSE IF $XDG_CONFIG_HOME use $XDG_CONFIG_HOME/jellyfin
ELSE    $HOME/.config/jellyfin
```
