### ISSUE TITLE
[Issue]: 10.8-alpha3 and unstable: Service does not start on LXC anymore

### ISSUE THREAD

**Issue by Shadowghost** [jellyfin/jellyfin#6984]
### Please describe your bug

Since https://github.com/jellyfin/jellyfin/pull/6953 Jellyfin will not start on LXC anymore and exits with `(code=exited, status=226/NAMESPACE)`

This is most likely caused by permission issues on the ressources which systemd tries to modify based on the additional hardening.

I checked each of the new options and adding an override at `/etc/systemd/system/jellyfin.service.d/override.conf` with the following content fixes the startup:
```
RestrictNamespaces=false
ProtectControlGroups=false
ProtectKernelLogs=false
ProtectKernelModules=false
ProtectKernelTunables=false
PrivateTmp=false
```

If there is any other way to properly make this work on LXC without disabling those settings that would be optimal. Otherwise we should consider reverting those changes because they can break existing installs on LXC.

### Jellyfin Version

10.8-alpha3

### Environment

```markdown
- OS: Debian 11
- Virtualization: LXC privileged on proxmox VE 7.1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joshuaboniface** [comment]
I think it's probably prudent just to remove those particular hardening items, and leave the remainder (I do recall there being a lot more).

On any systemd environment we run, by default, we run as an unprivileged user, so I think we're doing to end up with most of that hardening "on" by default anyways.
