### ISSUE TITLE
[Issue]: m4b files not play with iOS app

### ISSUE THREAD

**Issue by ghost** [jellyfin/jellyfin#6986]
### Please describe your bug

Not sure should this .m4b filetype even play with iOS device even it is invented by apple?
Anyways this .m4b seems to be best format for audiobooks. +10 separate .mp3 files seems a bit messy under every book.

Server: 10.7.7 (unRAID docker)
iOS: 1.4.1

I will just get notification "This client isn't compatible with the media and the server isn't sending a compatible media format."
File play fine with browser (firefox) and Jellyfin Media Player desktop app (Linux) and with all other players including plex, vlc, mpv, booksonic etc.
Should chapters to be visible with .m4b files?

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ndaman** [comment]
I'm getting the same issue on Android, and what's frustrating is that when I go to download the file to play locally instead, it downloads a different file instead of the .m4b. Are m4b files supported by Jellyfin?

**Comment by Gitraffe** [comment]
Do you get embedded metadata (image etc.) grabbed correctly from file? 
If I create 1 file from same audibook with same application. Only difference in settings is extension:
mp3: Image and metadata is grabbed from file
m4a: No image and metadata, but plays with iOS app
m4b: No image and metadata, no go with iOS app but works pretty much with everything else I tried. (not having android device)

So there might be some problems on server side also.

**Comment by Conellys** [comment]
Hello!

I can confirm this error with all m4b files.

Running Jellyfin in Docker V10.7.7 via Docker Compose with the lscr.io image.
Trying to access the files via mobile client iphone 11 (ios 15.3), app version iOS 1.4.1. Accessing via Chrome, Opera, Firefox and Safari also does not work.
Same error message.

Playing the same file via Android apps (2.4.1) on various devices works fine. Playing over VLC player also works perfectly fine. I dare to rule out a server-side issue but rather suspect (a) the app or (b) the device. But cannot say which is the problem.

No images and metadata are retrieved. Image Extractor failed.

Re-deploying container, re-scanning library does not work.
Logfiles just state that playback was stopped at 0ms. No apprent error messages.

Sample for acces via browser:
Playback stopped reported by app "Jellyfin Web" "10.7.6" playing "FILE". Stopped at "0" ms

 Sample iOs app:
Playback stopped reported by app "Jellyfin Mobile (iOS)" "1.4.1" playing "FILE". Stopped at "0" ms

Is this a known bug?

Many thanks!

**Comment by realitymolder** [comment]
I have the same issue with my desktop, it's a problem with Jellyfin as it seems. Because it states that Jellyfin supports m4b files.

**Comment by Conellys** [comment]
I can confirm that this is still an issue with updated device, server and app but the same setup as outlined above. What makes me wonder is that it works on Android phones but not on iOS which is bizarre due to m4b being the issue.

**Comment by gVes** [comment]
I have the same issue.
With Hardware Acceleration on, works great on macOS but getting a playback error on iOS devices. with HW acceleration off, it's working fine on iOS however. No clue why this would happen. Any ideas guys?

Thanks.

**Comment by mstickler1** [comment]
Long time plex user who just installed jellyfin today primarily for the audiobook and book support. I was extremely disappointed when my m4b files would not play in the browser but then I noticed something. Some of them were playing. Specifically if there was a cue file in the directory jellyfin was picking it up as the file to be played and then would error but if there was no cue file then the m4b played normally. I'm thinking this may not be an issue related to m4b playback but to support for cue files.

**Comment by nlflint** [comment]
> Long time plex user who just installed jellyfin today primarily for the audiobook and book support. I was extremely disappointed when my m4b files would not play in the browser but then I noticed something. Some of them were playing. Specifically if there was a cue file in the directory jellyfin was picking it up as the file to be played and then would error but if there was no cue file then the m4b played normally. I'm thinking this may not be an issue related to m4b playback but to support for cue files.

In my situation, I have no cue files at all. Just m4b files and they don’t play via iOS app.

As an alternative, I’ve been using the AudibookShelf project. It’s another self-hosted media server but focused on audiobooks and podcasts. It works really well with m4b and has an iOS app and website.

**Comment by WeisseTeetasse** [comment]
This bug is still current on the current stable version, in addition it does not play on safari either.

**Comment by atmask** [comment]
Is there an ETA for a new release version that includes this fix?

**Comment by crobibero** [comment]
> Is there an ETA for a new release version that includes this fix?

https://jellyfin.org/posts/testing-10.9.0
