### ISSUE TITLE
[Issue]: Server seems to have forgotten password, can't reset it

### ISSUE THREAD

**Issue by azukaar** [jellyfin/jellyfin#6990]
### Please describe your bug

So I haven't used my server for 3-4 weeks (holidays). When I tried to use Jellyfin again, my password was rejected. I know it is correct because I am using a password manager for it. I have then started the battle of trying to reset password.

This is what I am getting, I think something definitly went wrong somewhere. It tells me  the file is undefined for the pin : 

![image](https://user-images.githubusercontent.com/7872597/145876905-01856a20-c56f-4937-9312-be8491158d9c.png)

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS:Ubuntu
- Virtualization: no
- Clients: web
- Browser: firefox
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy: NGINX
- Base URL: /
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
The file path has been fixed in https://github.com/jellyfin/jellyfin/pull/6673
Try looking in your config / data directories to find the file.
