### ISSUE TITLE
[Issue]: 10.8.3 Alpha unable to cast media with HE-AACv2 encoded audio to Chromecast v2

### ISSUE THREAD

**Issue by schlnk** [jellyfin/jellyfin#6999]
### Please describe your bug

Trying to cast to Chromecast v2 media with HE-AACv2 encoded audio track. Chromecast tries to play it, but shows only black screen. If I re-encode audio track to LC-AAC everything works fine. Server tries to direct play media, but according to [documentation ](https://developers.google.com/cast/docs/media) Chromecast doesn't support HE-AACv2 codec. Probably server should direct stream instead and transcode audio to HE-AAC (v1) or LC-AAC.

Steps to reproduce:
1. Try to cast to Chromecast  media with parameters (see below). Chromecast wont play it.
2. Re-encode audio track to LC-AAC and try again. Chromecast should play it.

```Video
Title1080p H264 SDR
CodecH264
AVCNo
ProfileHigh
Level40
Resolution1920x1080
Aspect ratio16:9
InterlacedNo
Framerate25
Bitrate4232 kbps
Bit depth8 bit
Video rangeSDR
Color spacebt709
Color transferbt709
Color primariesbt709
Pixel formatyuv420p
Ref frames1
```
```Audio
TitleRussian - AAC - Stereo - Default
Languagerus
CodecAAC
ProfileHE-AACv2
Layoutstereo
Channels2 ch
Bitrate126 kbps
Sample rate48000 Hz
DefaultYes
```

### Jellyfin Version

Other

### if other:

10.8.3

### Environment

```markdown
- OS: Debian, Raspberry PI4
- Virtualization: None
- Clients: Chromecast v2
- Browser: N/A
- FFmpeg Version: 4.3.2-Jellyfin
- Playback Method: Direct Play
- Hardware Acceleration: None
- Plugins: None
- Reverse Proxy: None
- Base URL: N/A
- Networking: N/A
- Storage: N/A
```

### Jellyfin logs

```shell
Nothing special in the Jellyfin logs.
```

### FFmpeg logs

```shell
No ffmpeg logs generated, because server tries to direct play this media.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lazi3b0y** [comment]
Experiencing the same thing when casting movies/series with HE-AAC from Jellyfin for Android.
