### ISSUE TITLE
Web UI - Fallback options in user settings to playing trailer as theme video

### ISSUE THREAD

**Issue by 1ucay** [jellyfin/jellyfin#7008]
Hello,
can you please add checkbox in user settings, which lead to playing trailer as theme video in web ui?
I have some theme videos in folder /backdrops/theme.mp4, but there are few of them. But I have many movies with trailers.
It could be nice.
Thank you

**Comment by crobibero** [comment]
Feature requests belong at https://features.jellyfin.org/
