### ISSUE TITLE
Using #452 (EF Core) causes app to crash on launch

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin#701]
**Describe the bug**
Jellyfin will crash within about five seconds of launch. Quick testing appears to indicate that #452 is the source of the crash, as reverting it locally stops the issue.

**To Reproduce**
1. Clone latest master.
2. Build (in my case, using VS for Mac).
3. Launch Jellyfin
4. See error in console, and launched webpage doesn't load.

**Expected behavior**
Though I know Master is a rolling dev, Jellyfin should run.

**Logs**
https://paste.debian.net/1062418

**System (please complete the following information):**
 - OS: macOS Mojave 10.14.2
 - Browser: Safari, but it doesn't get that far 😄 
 - Jellyfin Version: Latest master, at time of writing this is 
https://github.com/jellyfin/jellyfin/commit/b4fdfb562dada77ff6d9c75bbc9e5e5b3ee977a2

**Comment by EraYaN** [comment]
That stack trace does not seem to be from the EF Core implementation. But the other SQLite library, that is weird.
