### ISSUE TITLE
Black at the bottom of this subtitle

### ISSUE THREAD

**Issue by tobylibo** [jellyfin/jellyfin#7032]
Why is there such an ugly black at the bottom of this subtitle?  Don’t you think it affects your perception?  If it is a small screen of a mobile device, it is understandable for fear that the user cannot see the subtitles. Then why should there be such a black as the background color on a large-screen TV?  When you watch a movie in a movie theater, you have seen which movie has subtitles in this style.  It's hard to understand.

There is no purpose of attack, just a simple idea, of course it can be improved and better.  It doesn’t matter if you don’t improve, it’s a free app after all

![6660B890-D66A-4945-9CD1-3E79C3082285](https://user-images.githubusercontent.com/76021750/146862049-817e5857-7ed1-4e1b-9d78-35ded2fb35ab.jpeg)

**Comment by crobibero** [comment]
I assume this is AndroidTV, this is not something that can be changed at the moment
