### ISSUE TITLE
[Issue]: ffmpeg logs

### ISSUE THREAD

**Issue by hnotcold** [jellyfin/jellyfin#7036]
### Please describe your bug

https://www.aliyundrive.com/s/QacEv33isD2，日志在这里，大佬辛苦看下

### Jellyfin Version

Other

### Environment

```markdown
- OS:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hnotcold** [comment]
Cannot load libcuda.so.1
[AVHWDeviceContext @ 0x562894e1d340] Could not dynamically load CUDA
Device creation failed: -1313558101.
Failed to set value 'cuda=cu:0' for option 'init_hw_device': Unknown error occurred
Error parsing global options: Unknown error occurred

**Comment by nyanmisaka** [comment]
你是否已经按照官方教程添加了nvidia相关的启动参数？
```
Start your container adding these parameters:

-e NVIDIA_DRIVER_CAPABILITIES=all \
-e NVIDIA_VISIBLE_DEVICES=all \
--gpus all \
A complete run command would look like this:

docker run -d \
 --name=jellyfin \
 -e NVIDIA_DRIVER_CAPABILITIES=all \
 -e NVIDIA_VISIBLE_DEVICES=all \
 --gpus all \
 -p 8096:8096 \
 -p 8920:8920 \
 -v /config:/config \
 -v /media:/media \
 -v /cache:/cache \
 --restart unless-stopped \
 jellyfin/jellyfin
Or with docker-compose >1.28, add the deploy and environment parts to your Jellyfin service:

services:
  jellyfin:
    image: jellyfin/jellyfin
  # ... your Jellyfin config
  environment:
    NVIDIA_DRIVER_CAPABILITIES: all
    NVIDIA_VISIBLE_DEVICES: all
  deploy:
    resources:
      reservations:
        devices:
        - capabilities: [gpu]
There are some special steps when running with the following option:

--user 1000:1000
You may need to add this user to the video group on your host machine:

usermod -aG video user
Once the container is started you can again validate access to the host resources:

docker exec -it jellyfin nvidia-smi
If you get driver information, everything is fine but if you get an error like couldn't find libnvidia-ml.so library in your system you need to run the following command:

docker exec -it jellyfin ldconfig
After that, you should ensure the NVIDIA driver loads correctly.
```

**Comment by hnotcold** [comment]
> 你是否已经按照官方教程添加了nvidia相关的启动参数？ https://jellyfin.org/docs/general/administration/hardware-acceleration.html#nvidia-nvenc
> 
> ```
> Start your container adding these parameters:
> 
> -e NVIDIA_DRIVER_CAPABILITIES=all \
> -e NVIDIA_VISIBLE_DEVICES=all \
> --gpus all \
> A complete run command would look like this:
> 
> docker run -d \
>  --name=jellyfin \
>  -e NVIDIA_DRIVER_CAPABILITIES=all \
>  -e NVIDIA_VISIBLE_DEVICES=all \
>  --gpus all \
>  -p 8096:8096 \
>  -p 8920:8920 \
>  -v /config:/config \
>  -v /media:/media \
>  -v /cache:/cache \
>  --restart unless-stopped \
>  jellyfin/jellyfin
> Or with docker-compose >1.28, add the deploy and environment parts to your Jellyfin service:
> 
> services:
>   jellyfin:
>     image: jellyfin/jellyfin
>   # ... your Jellyfin config
>   environment:
>     NVIDIA_DRIVER_CAPABILITIES: all
>     NVIDIA_VISIBLE_DEVICES: all
>   deploy:
>     resources:
>       reservations:
>         devices:
>         - capabilities: [gpu]
> There are some special steps when running with the following option:
> 
> --user 1000:1000
> You may need to add this user to the video group on your host machine:
> 
> usermod -aG video user
> Once the container is started you can again validate access to the host resources:
> 
> docker exec -it jellyfin nvidia-smi
> If you get driver information, everything is fine but if you get an error like couldn't find libnvidia-ml.so library in your system you need to run the following command:
> 
> docker exec -it jellyfin ldconfig
> After that, you should ensure the NVIDIA driver loads correctly.
> ```

运行的时候提示以下提示：docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].

**Comment by nyanmisaka** [comment]
> 运行的时候提示以下提示：docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].

似乎你没有安装nvidia为docker提供的运行库 `NVIDIA Container Toolkit`
1. https://blog.csdn.net/dou3516/article/details/108314908
2. https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#getting-started

**Comment by hnotcold** [comment]
> > 运行的时候提示以下提示：docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
> 
> 似乎你没有安装nvidia为docker提供的运行库 `NVIDIA Container Toolkit` 请查看以下链接来解决：
> 
> 1. https://blog.csdn.net/dou3516/article/details/108314908
> 2. https://www.cnblogs.com/GengMingYan/p/14962878.html
> 3. https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#getting-started

老大你的这三个教程我看了，qts不支持自己安装这些，估计还是要寻找官方的人来支持一下了，qts不支持源

**Comment by athdesk** [comment]
this is still happening, it shouldn't be closed

**Comment by 4n4n4s** [comment]
I could solve the issue by adding 
```
  environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
```
to the environment config as I am using the image: ghcr.io/linuxserver/jellyfin
