### ISSUE TITLE
Add file size to media info page

### ISSUE THREAD

**Issue by dinki** [jellyfin/jellyfin#704]
The Jellyfin media info page shows everything about the files with the exception of the file size.  This would be useful information for many users.

**Comment by dinki** [comment]
This request complete.  Thanks.  Tidying up my open issues.

**Comment by mazzystr** [comment]
The file size is incorrectly calculated in 10.3.5
<img width="1524" alt="Screen Shot 2019-06-29 at 4 56 20 PM" src="https://user-images.githubusercontent.com/2479463/60389451-14b64080-9a8f-11e9-9729-961cf6694bca.png">
<img width="974" alt="Screen Shot 2019-06-29 at 4 56 34 PM" src="https://user-images.githubusercontent.com/2479463/60389452-14b64080-9a8f-11e9-985c-d5cae43f4db7.png">

**Comment by mazzystr** [comment]
@dinki ^

**Comment by dinki** [comment]
Very odd.  This is what I'm seeing:

![image](https://user-images.githubusercontent.com/2521542/60441518-c3b46280-9bdc-11e9-81a9-4fb258664b17.png)

![image](https://user-images.githubusercontent.com/2521542/60441540-d29b1500-9bdc-11e9-83cc-4388a7988e20.png)

Which is right.  I checked the type that @cvium used and it certainly should fit.  Perhaps he can look at it.

**Comment by mazzystr** [comment]
Now it's the correct size.  Maybe I had to wait for a database update?
<img width="1456" alt="Screen Shot 2019-07-01 at 1 14 47 PM" src="https://user-images.githubusercontent.com/2479463/60454667-616e5880-9c02-11e9-9ceb-a84f43815b35.png">
