### ISSUE TITLE
[Issue]: '11-Dec-2021 21:26' - after no more unstable server builds 

### ISSUE THREAD

**Issue by WWWesten** [jellyfin/jellyfin#7061]
### Please describe your bug

No more unstable server builds after 11-Dec-2021 21:26 https://repo.jellyfin.org/releases/server/windows/unstable/server/
Same way for Linux and MacOS.

### Jellyfin Version

Other

### if other:

10.8.0

### Environment

```markdown
- OS:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by WWWesten** [comment]
https://github.com/jellyfin/jellyfin-web/issues/3222

**Comment by Shadowghost** [comment]
There are some problems with the scripts collecting the CI artifacts and generating the meta-packages at the moment. It's being worked on.

In the meantime you can download the server and web packages directly from the CI artifacts if necessary.

**Comment by WWWesten** [comment]
Merry Christmas and Happy New Year @Shadowghost! Can You show me direct links to that CI artifacts for core and web?
Thanks!
