### ISSUE TITLE
[enhancement] Seperate sub/domain for streaming

### ISSUE THREAD

**Issue by MikeMatau** [jellyfin/jellyfin#7064]
I would like to be able to have a second domain or subdomain for streaming.
This would enable me to have cloudflare with caching active for the ui, covers, fanart, etc. but not for the real streams, so there would be no violation of the cloudflare TOS.

**Comment by cvium** [comment]
This would require a lot of changes in the server code and client apps. Unlikely to be implemented.

And feature requests belong here: https://features.jellyfin.org
