### ISSUE TITLE
 Playback Error This client isn't compatible with the media and the server isn't sending a compatible media format. HEVC with VAAPI

### ISSUE THREAD

**Issue by AfricaByTot0** [jellyfin/jellyfin#7081]
**Media Info of the file**

Title4K HEVC HDR
CodecHEVC
ProfileMain 10
Level150
Resolution3840x2160
Aspect ratio16:9
InterlacedNo
Framerate23.976025
Bitrate18573 kbps
Video rangeHDR
Color spacebt2020nc
Color transfersmpte2084
Color primariesbt2020
Pixel formatyuv420p10le
Ref frames1
**Logs**

https://pastebin.com/JDPgS9NY
**FFmpeg Logs**

https://pastebin.com/vrAdx3b2
**Stats for Nerds Screenshots**

N/A
**Server System (please complete the following information):**
 - OS: Docker on Ubuntu Server 20.04.3
 - Jellyfin Version: 10.7.7
 - Hardware settings & device: VAAPI on Radeon Vega 8 Graphics
 - Reverse proxy: [No
 - Other hardware notes: Media mounted locally
 
**Client System (please complete the following information):**
 - Device: Acer Spin 5, Custom Home PC
 - OS: Pop!OS and Windows 10
 - Client: Web browser
 - Browser (if Web client): Firefox
 - Client and Browser Version: 10.7.6 and 95.0.2
 
 I only have this issue with HEVC, any other media format is completely fine.

**Comment by whiteowl3** [comment]
Firefox refuses to support HEVC due to licensing issues.
https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Video_codecs#HEVC
https://bugzilla.mozilla.org/show_bug.cgi?id=1332136

**Comment by nyanmisaka** [comment]
Fixed in jellyfin-ffmpeg5 with our self-build Mesa.
