### ISSUE TITLE
[Issue]: portable-combined missing web-client 10.8.0-alpha3

### ISSUE THREAD

**Issue by heitbaum** [jellyfin/jellyfin#7085]
### Please describe your bug

The combined tar.gz did not include the web-client.

https://repo.jellyfin.org/releases/server/portable/stable-pre/10.8.0-alpha3/combined/

jellyfin_10.8.0-alpha3.tar.gz

### Jellyfin Version

Other

### if other:

10.8.0-alpha3

### Environment

```markdown
- OS:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joshuaboniface** [comment]
Thanks for the heads up, this has been fixed.
