### ISSUE TITLE
[Issue]: ALPHA: Docker health check does not work correctly when using macvlan network type

### ISSUE THREAD

**Issue by yesrod** [jellyfin/jellyfin#7098]
### Please describe your bug

The Docker health check doesn't work right if I use a macvlan network to have the Jellyfin container on its own IP address.

I get the following output (sorry for bad formatting, this is what I get from Docker)

```
% Total % Received % Xferd Average Speed Time Time Time Current Dload Upload Total Spent Left Speed 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 curl: (7) Failed to connect to localhost port 8096: Connection refused 
```

### Jellyfin Version

Other

### if other:

10.8.0-alpha3

### Environment

```markdown
- OS: OpenMediaVault 5 (Debian 10)
- Virtualization: Docker
- Clients: Browser, Android, Kodi
- Browser: Firefox 95.0.2
- FFmpeg Version: jellyfin-ffmpeg/now 4.3.2-1-bullseye amd64 [installed,local]
- Playback Method: Direct Play, Transcode
- Hardware Acceleration: VAAPI
- Plugins: none
- Reverse Proxy: none
- Base URL: none
- Networking: Host/macvlan
- Storage: local/bind mount
```

### Jellyfin logs

```shell
N/A
```

### FFmpeg logs

```shell
N/A
```

### Please attach any browser or client logs here

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
This doesn't seem like a bug. Just change the healthcheck environment variable.

**Comment by yesrod** [comment]
Yep, I completely missed that was configurable.  For posterity's sake, I changed `$HEALTHCHECK_URL` to `http://server.url/health` and that was sufficient to fix the health check.  Sorry for spam.
