### ISSUE TITLE
[Issue]: Transcoding is maxing out CPU

### ISSUE THREAD

**Issue by paranerd** [jellyfin/jellyfin#7110]
### Please describe your bug

Jellyfin puts some heavy loads on my CPU. I've tried a couple of different codec combinations and CPU usage is always way too high.

**What I've tested:**
- Playing any kind of file on my **iPhone 12** using the Jellyfin Beta works fine, anytime.
- Playing HEVC Main 10 with EAC3 7.1 on the new **Chromecast with Google TV** maxes out all 4 cores of my Intel i5. Logs say `VideoCodecNotSupported` even though the Chromecast spec sheet explicitly lists HEVC Main 10.

Disabling Video Transcoding for my user got usage down to ~120% CPU combined in any scenario (for Chromecast).

What's more: Stopping the movie didn't always stop the transcoding, so my server continued to be hard at work.

For comparison: Playing the same HEVC Main 10 with EAC3 7.1 file via Plex my CPU mostly stays <10% for all 4 cores combined.

I'm running version 10.7.7 in a Docker container.

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: Ubuntu
- Virtualization: Docker
- Clients: iPhone, Chromecast
- Browser: Brave, Safari
- FFmpeg Version:
- Playback Method: Transcode
- Hardware Acceleration: none
- Plugins:
- Reverse Proxy: nginx
- Base URL:
- Networking: Bridge
- Storage: SMB
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Goblinlordx** [comment]
Just as a note, I have an intel i5-1135g7 (11th gen tiger lake).  Without hardware acceleration I get fairly high CPU usage. With it, I get barely any. This seems pretty much expected for HEVC encoding without hardware acceleration. I can't comment on the `VideoCodecNotSupported` but that sounds like the primary issue here. Incorrect codec support detection would probably be more appropriate as a description.

**Comment by paranerd** [comment]
Thank you for sharing!

I did actually expect for HEVC encoded files but sadly it's the same for H.264 with 5.1 audio (which the Chromecast can definitely handle and should thus not require any transcoding).

**Comment by GrandpaCode** [comment]
Similar config, but i noticed the following note from the admin dashboard when viewing from my nVidia Shield client

The media is being converted into a format that is compatible with the device that is playing the media.
Framerate: 44fps

1.4 Mbps MKV HEVC AC3

Reason for transcoding:
ContainerNotSupported
VideoCodecNotSupported
AudioCodecNotSupported

Hopefully this provides some context

**Comment by paranerd** [comment]
Tried again now to see if things have improved. Sadly no changes.

However, I gave the MacOS Desktop Client a try and that one works as expected with a combined CPU load of ~10%.
Also I now realized that Jellyfin not only maxes out my CPUs for EAC3 7.1 media but for ANY media, even H264 DTS5.1 (which is definitely supported by Chromecast with Google TV, according to the documentation: "H.264 High Profile up to level 5.1 (4Kx2K/30fps)").

I would absolutely LOVE to use Jellyfin but with a single stream maxing out my server this is just not feasible... Any support would be highly appreciated!

**Comment by cvium** [comment]
Can't support much without ffmpeg logs and playback info/stats for nerds

**Comment by paranerd** [comment]
Thanks for the feedback!
Where/how would I get those?

**Comment by fromage9747** [comment]
@paranerd Under logs in Jellyfin Dashboard.  The FFmpeg log is generated there for ease of access:

![image](https://user-images.githubusercontent.com/23147783/229418523-09a87511-64b1-41d0-8fb2-f417a4c38d1b.png)

**Comment by sevenrats** [comment]
not clear that this report indicates a bug in jellyfin.

**Comment by CelianGdfrd** [comment]
I'm having the same problem on my server. Sometimes, Jellyfin reaches 700% CPU usage for no reason, and all playbacks get jammed.
I have the logs. Can I just drop them here ?

**Comment by sevenrats** [comment]
This is for bug reports. A bug is when the code doesn't work. You need troubleshooting, please reach out in one of our chat spaces.

**Comment by fromage9747** [comment]
@CelianGdfrd I gave up in trying to troubleshoot as everywhere I tried to get help, I got fingers pointed at me that its my problem.  So now I have to scheduled a daily restart of the docker container and a weekly reboot of the server.  Sometimes even twice or three times a week.

**Comment by sevenrats** [comment]
o..... k.... guys this is a dead issue. we are all emailing a dozen people about a non-bug that was closed more than 2 years ago.  Sorry you had a bad time fromage, we are standing by to help whenever you need.
