### ISSUE TITLE
[Issue]: 10.8.5 Alpha Missing TMDb Box Sets update in manifest-stable.json

### ISSUE THREAD

**Issue by MRDJellyfin** [jellyfin/jellyfin#7126]
### Please describe your bug

In Windows 10 64 an error is generated by TMDb Box Sets version 8 since the manifest-stable.json is not updated (which is the one I have used in previous versions of Alpha and currently), since it has not been updated to version 9, but said update if it is in manifest-unstable.json, I did the update manually to version 9 and no more problems.

 "guid": "bc4aad2e-d3d0-4725-a5e2-fd07949e5b42",
        "name": "TMDb Box Sets",
        "description": "Automatically create movie box sets based on TMDb collections",
        "overview": "Automatically create movie box sets based on TMDb collections",
        "owner": "jellyfin",
        "category": "Metadata",
        "versions": [
            {
                "version": "9.0.0.0",
                "changelog": "- Use BaseItemKind (#56) @crobibero\n\n### Bug Fixes ###\n- Update TMDbBoxSetManager.cs (#49) @WWWesten",
                "targetAbi": "10.8.0.0",
                "sourceUrl": "https://repo.jellyfin.org/releases/plugin/tmdb-box-sets/tmdb-box-sets_9.0.0.0.zip",
                "checksum": "dfa634c9fce4da16cd8d202c5278c3cb",
                "timestamp": "2022-01-05T16:04:58Z"

### Jellyfin Version

Other

### Environment

```markdown
- OS:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
Thank you for the report, we are already looking into it.

**Comment by MRDJellyfin** [comment]
Has the same problem "The TVDB"

**Comment by crobibero** [comment]
All plugins in manifest-stable have been corrected
