### ISSUE TITLE
[Issue]: Release server certificate verification fail

### ISSUE THREAD

**Issue by Brazen00** [jellyfin/jellyfin#7128]
### Please describe your bug

Trying to install jellyfin as per https://jellyfin.org/docs/general/administration/installing.html#debian

Ran the command
`wget -O - https://repo.jellyfin.org/debian/jellyfin_team.gpg.key | sudo apt-key add -`

Got the response
`
--2022-01-07 13:18:01--  https://repo.jellyfin.org/debian/jellyfin_team.gpg.key
Resolving repo.jellyfin.org (repo.jellyfin.org)... 68.183.204.194, 2604:a880:cad:d0::cf3:f001
Connecting to repo.jellyfin.org (repo.jellyfin.org)|68.183.204.194|:443... connected.
ERROR: The certificate of ‘repo.jellyfin.org’ is not trusted.
ERROR: The certificate of ‘repo.jellyfin.org’ has expired.
gpg: no valid OpenPGP data found.
`

### Jellyfin Version

Other

### Environment

```markdown
- OS:Raspbian
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
Are you able to access https://repo.jellyfin.org?

I cant reproduce this error

**Comment by anthonylavado** [comment]
Is this the first time you're trying to add the key & repo, or have you done it before?

We did switch out keys just over a year ago, and if you had the old one, it could cause an issue.

Our post about the switch: https://jellyfin.org/posts/jellyfin-apt-key/

**Comment by Brazen00** [comment]
I have done it before. However, after crobibero's reply, I tried the exact same command, and it is now working.
