### ISSUE TITLE
[Issue]: disable remote connections 

### ISSUE THREAD

**Issue by rikrdo89** [jellyfin/jellyfin#7135]
### Please describe your bug

I want to disable remote connections to my jellyfin server. when I try to uncheck the  box (that I initially checked during setup), I canot save those changes.

Since I just setup my jellyfin behind a reverse proxy server, I dont want remote connections enable anymore.

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ferferga** [comment]
What does exactly happen after clicking Save?

**Comment by rikrdo89** [comment]
Clicking save does nothing. The save button does not respond to clicking.

**Comment by yukihito23** [comment]
I'm seeing something similar randomly in the Networking > Save action where on frontend UI it seems like it's doing nothing and I can't save but in console logs it shows this set of logs every time the Save button is clicked. https://i.imgur.com/cLhsYWI.png

I've been trying to figure out if it's something I've done but weirdly, I can get save to work randomly once in a while even if I left it as un-savable last time I tried interacting with the page itself so kind of confused.

This is on my NAS running ver.10.7.6 / Linux / x64
