### ISSUE TITLE
[Issue]: Infinite Scroll/Page Limit Option Missing in Library Settings under Display as Merged PR indicates

### ISSUE THREAD

**Issue by CHNOK** [jellyfin/jellyfin#7144]
### Please describe your bug

The suggestion on the Finder and merging of PR #983 suggest there should be a option under display in settings to change page limit/infinite scroll. The only "Display" option visible is the tab under Library which does not have the page limit option listed.

Suggestion: https://features.jellyfin.org/posts/216/remove-pagination-use-lazy-loading-for-library-view
PR: https://github.com/jellyfin/jellyfin-web/pull/983

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: Windows
- Virtualization:
- Clients: Browser
- Browser: Firefox 95
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ferferga** [comment]
![image](https://user-images.githubusercontent.com/10274099/148682949-a051ec14-91ef-4dc4-8ab8-fcda5782d18c.png)

**Comment by CHNOK** [comment]
Nevermind, I am blind. Thanks for the screenshot and sorry for the waste of time.
