### ISSUE TITLE
[Issue]: multi version movie

### ISSUE THREAD

**Issue by iEvoken** [jellyfin/jellyfin#7155]
### Please describe your bug

after fresh install and clean library scan i got that "version section" is disappeared on my multi version movies. (webui show there is tow movies but when i click on poster "version section" is not there)

on 10.7.7 everything is ok.

### Jellyfin Version

Other

### if other:

10.8.0

### Environment

```markdown
- OS: Linux
- Virtualization: Docker
- Clients: Browser
- Browser: Chrome 97
- FFmpeg Version: 
- Playback Method: Direct Play
- Hardware Acceleration: none
- Plugins: Fanart
- Reverse Proxy: None
- Base URL: none
- Networking: Host
- Storage: local
```

### Please attach any screenshots here

![Screenshot_20220110-213517](https://user-images.githubusercontent.com/64152441/148817063-fa7c4020-f79b-49cf-9071-1725c0392e81.png)
![Screenshot_20220110-214324](https://user-images.githubusercontent.com/64152441/148817435-8a9b8576-809e-4289-b752-3c1179cf8166.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shadowghost** [comment]
What's your filesystem layout?

**Comment by iEvoken** [comment]
> What's your filesystem layout?

Movies
└── Three Times (2005)
    ├── Three Times (2005) - 1080p.mp4
    └── Three Times (2005) - 480p.mp4

**Comment by whiteowl3** [comment]
#7189
