### ISSUE TITLE
[Issue]: Search limited to 24 results.

### ISSUE THREAD

**Issue by trevormbell** [jellyfin/jellyfin#7156]
### Please describe your bug

It seems that the search function will only display 24 results. Even if I search for a keyword that I know has more results, only 24 show up. 

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: Windows 10 Pro
- Virtualization:
- Clients: Browser
- Browser: Chrome
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage: Local
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
This is not a server bug. The web client limits the results returned to 24 per type.
