### ISSUE TITLE
Login Security Feature Request

### ISSUE THREAD

**Issue by MrHumanRebel** [jellyfin/jellyfin#7159]
1. Google reCAPTCHA support at login screen: 
    This would prevent bots spamming login attempts to the Jellyfin server.
    https://www.google.com/recaptcha/about/

2. Bruteforce blocker:
    Disable/lock login page for the IP address if wrong Username or Password until the admin unlocks it, or for "X" minutes.

**Comment by crobibero** [comment]
feature requests belong at https://features.jellyfin.org/

We already have "Failed login tries before user is locked out", which is similar to 2
