### ISSUE TITLE
[Issue]: Wrong aspect ratio on Firefox Ubuntu

### ISSUE THREAD

**Issue by peboettch** [jellyfin/jellyfin#7165]
### Please describe your bug

I've tried Jellyfin with some of my transcoded dvd-content. The videos have a resolution of 720x576 with a SAR of 64:45 and a DAR (=aspect ratio) of 16:9. In Chromium (97.0) the 16:9 video flag is respected and the video shows perfectly fine. In Firefox (95.0.1) the video has a wrong aspect ratio (seems like 4:3, but could also be 64:45) and I have to manually select "fill" as an aspect ratio every time I want to watch a video.
I know that this is not necessarily a Jellyfin bug, but I want to know if maybe there is a fix that could be implemented (or is already available).
I can provide further info if needed.

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS:Ubuntu Server 20.04.
- Virtualization:Docker
- Clients:Browser
- Browser:Firefox 95.0.1.
- FFmpeg Version:bundled with Docker
- Playback Method:Transcode as well as Direct Stream
- Hardware Acceleration:none
- Plugins:none
- Reverse Proxy:none
- Base URL:none
- Networking:host
- Storage:local
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by peboettch** [comment]
The Bug still exists with the latest beta.

**Comment by skittlesvampir** [comment]
I can confirm this, 4:3 in Firefox but 16:9 (as it should be) in Chromium and the android app.
If I open the video file directly in each browser (Ctrl+O and select the video), I get a 4:3 in Firefox and 16:9 in Chromium, so it's pretty likely that Jellyfin can't do anything about it (expect maybe if you write some code that detects if the browser does it wrong and then starts transcoding to scale it).
