### ISSUE TITLE
[Issue]: 10.8.0 Alpha 5 Possible error in Hardware Acceleration Options

### ISSUE THREAD

**Issue by MRDJellyfin** [jellyfin/jellyfin#7166]
### Please describe your bug

In Windows 10 64 in the Hardware acceleration options, the OpenCL Device option does not appear, while in the stable 10.7.7 it does. Also in Media Player, in its version 1.7.0 preliminary 2 if it appears (but the 0.0 does not appear as fixed as in the stable web version of Jelyfin 10.7.7). Sorry for my ignorance, but I don't know if this option should appear or if it was removed from the Alpha. (If it should not appear, it would be necessary to correct it in Media Player version 1.7.0. Preliminary 2 if applicable ).

### Jellyfin Version

Other

### Environment

```markdown
- OS:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Please attach any screenshots here

Stable  10.7.7
![Captura de pantalla (109)](https://user-images.githubusercontent.com/82923908/149276749-df4c1e5d-ed26-4604-9171-f926c6623402.png)

Alpha 5
![Captura de pantalla (110)](https://user-images.githubusercontent.com/82923908/149276876-2819a0c5-9471-47d0-bcde-8d990dadc7ab.png)

Media Player
![Captura de pantalla (111)](https://user-images.githubusercontent.com/82923908/149276915-285eb2ec-03ef-408d-96f2-4697602e51be.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nyanmisaka** [comment]
The OpenCL box has been removed in 10.8 Alpha 5 since we don't need it anymore.
Updating jellyfin-web to alpha 5 can solve this issue.

**Comment by MRDJellyfin** [comment]
Thanks, I have made the copy from Apha 5 to Media Player and this option no longer appears.
