### ISSUE TITLE
[Issue]: all users can add to collections

### ISSUE THREAD

**Issue by michaelkrieger** [jellyfin/jellyfin#7179]
### Please describe your bug

A regular user with no modify/edit permission is able to add movies to a new collection and add to an existing collection.

users without edit permission shouldn’t be able to do that as collections should be curated by the system 

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: Debian 11
- Virtualization: Docker 
- Clients: iOS App
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by michaelkrieger** [comment]
Allow media deletion and allow managing server are both off

**Comment by cheetashock** [comment]
They can also delete collections in their entirety.

**Comment by michaelkrieger** [comment]
This seems like an important security fix needed

**Comment by DesertCookie** [comment]
This explains the plethora of weird collections that popped up in my library recently.

**Comment by Bakeneko** [comment]
Any progress on this? This is a huge issue. I use [this quick fix](https://github.com/Bakeneko/jellyfin/commit/1d23c27641067c2bb54ef44219f11b3da63b1a79) but an official fix (even temporary one) would be great.

**Comment by ppittle** [comment]
Possibly similar issue: https://github.com/jellyfin/jellyfin/issues/2410

**Comment by michaelkrieger** [comment]
Seems like a security issue...

**Comment by VladandGaret** [comment]
Hi,
I'm trying to apply the fix for this collections issue, but I can't find the .cs files. How can I proceed? My server is running on Windows 10
