### ISSUE TITLE
Same Movie Different Versions in Same folder but not stacking

### ISSUE THREAD

**Issue by bnichs5** [jellyfin/jellyfin#718]
I have 2 different files of the same movie in the same folder named after that movie. Instead of Jellyfin stacking the the versions it shows me the two different thumbnails for the movie when browsing my collection. Can anyone either attempt to fix this or tell me what i am doing wrong?

Thanks

**Comment by anthonylavado** [comment]
@bnichs5 There’s a verrrry specific format to follow for the files to match up.

Can you tell us what the folder name is like, and what the file names are like?
You can change the name if you want to.

Example:

```
My Movie (2005)
- My Movie.mkv 
```

**Comment by JustAMan** [comment]
Can you try adding spaces around `-`? It's really picky about that it seems.

**Comment by cvium** [comment]
Different versions like different resolutions etc.? Or is it more like Extended, Director's cut?

**Comment by bnichs5** [comment]
Same movie. Same resolution.just a different bitrate.

**Comment by bnichs5** [comment]
It looks like this.

https://gyazo.com/f499b586d77694c4a579876f8d518f31

**Comment by JustAMan** [comment]
Can you post exact file names?

**Comment by anthonylavado** [comment]
Just for reference, this is the Emby guide: https://github.com/MediaBrowser/Wiki/wiki/Movie-naming#multi-version-movies

It **really** cares about the spacing if you’re using dashes.

**Comment by bnichs5** [comment]
https://gyazo.com/f7d36b0df98c27b4b0a1e0cc4ec53862

**Comment by anthonylavado** [comment]
@bnichs5 thank you for the details!

So the issue is that the movies are not named exactly as the folder.

Instead of:
`A.Private.War.2018.1080p.BluRay.H264.AAC-RARBG.mp4`

It should be:
`A Private War (2018) - 1080P BluRay H264 AAC.mp4`

And so on. As long as all files begin with (note the spaces):
`A Private War (2018) - `

Then they will stack. The text after the dash can be whatever you want. It is the after dash text that will show up as the option list when you’re looking at the movie in Jellyfin.

**Comment by bnichs5** [comment]
Very interesting. thanks! I will give it a try.

**Comment by AnonymousWebHacker** [comment]
I have the same error .

I have the same folder name and the videos, separated by their resolution, however jellyfin recognizes it as 2 different movies

```
 ls -l Sisu\ \(2023\)/
total 2274692
-rw-r--r-- 1 jellyfin jellyfin     127276 may 16 21:40  backdrop1.jpg
-rw-r--r-- 1 jellyfin jellyfin    1037050 may 16 21:40  folder.jpg
-rw-r--r-- 1 jellyfin jellyfin     401902 may 16 21:40  logo.png
-rw-r--r-- 1 jellyfin jellyfin     870548 sep  4 10:56 'Sisu (2022) - [1080P]-backdrop1.jpg'
-rw-r--r-- 1 jellyfin jellyfin    1216858 sep  4 10:55 'Sisu (2022) - [1080P]-backdrop.jpg'
-rw-r--r-- 1 jellyfin jellyfin     970911 sep  4 10:55 'Sisu (2022) - [1080P]-logo.png'
-rwxr--r-- 1 jellyfin jellyfin 1558566155 sep  4 10:48 'Sisu (2022) - [1080P].mkv'
-rw-r--r-- 1 jellyfin jellyfin       7417 sep  4 10:56 'Sisu (2022) - [1080P].nfo'
-rw-r--r-- 1 jellyfin jellyfin    1037050 sep  4 10:54 'Sisu (2022) - [1080P]-poster.jpg'
-rw-r--r-- 1 jellyfin jellyfin     870548 sep  4 10:56 'Sisu (2023) - [720P]-backdrop1.jpg'
-rw-r--r-- 1 jellyfin jellyfin    1216858 sep  4 10:56 'Sisu (2023) - [720P]-backdrop.jpg'
-rw-r--r-- 1 jellyfin jellyfin     970911 sep  4 10:55 'Sisu (2023) - [720P]-logo.png'
-rwxr--r-- 1 jellyfin jellyfin  760897453 may 16 21:34 'Sisu (2023) - [720P].mkv'
-rw-r--r-- 1 jellyfin jellyfin       7414 sep  4 10:56 'Sisu (2023) - [720P].nfo'
-rw-r--r-- 1 jellyfin jellyfin    1037050 sep  4 10:55 'Sisu (2023) - [720P]-poster.jpg'
```

**Comment by cvium** [comment]
But the filenames are not the same? One is 2022 and the other 2023

**Comment by AnonymousWebHacker** [comment]
> But the filenames are not the same? One is 2022 and the other 2023

hahhahahah tanks :)
