### ISSUE TITLE
On the Android app, I cant skip ahead

### ISSUE THREAD

**Issue by bnichs5** [jellyfin/jellyfin#719]
On the android app, I cant skip ahead in a movie. might be because its a .strm file. but i'm not sure. I can skip ahead just fine in a web browser(not mobile).

**Comment by tiedtoastar** [comment]
Would you be able to try any other movie files? If this is one specific movie, could you attach the metadata for the file?

**Comment by bnichs5** [comment]
its for all of them

**Comment by Drondemovies** [comment]
What are you using to create the .strm files? Might have something to do with it.

**Comment by bnichs5** [comment]
Drive_strm

**Comment by Drondemovies** [comment]
Is it the ddurdle script?

**Comment by bnichs5** [comment]
Not Ddurdle. Using this one instead. https://github.com/l3uddz/drive_strm

It integrates with cloudbox easy. That's why.

**Comment by Drondemovies** [comment]
Are you using transcode or original?

**Comment by bnichs5** [comment]
I'm using both the google transcodes and original.

**Comment by Drondemovies** [comment]
I had the same problem using ddurdle .strm, using the original file fixed it (using emby/jellyfin).

**Comment by ddurdle** [comment]
shouldn't this be moved to an issue in the android app, since it only happens with the android app?

**Comment by ddurdle** [comment]
Also, is the issue happening for you in the mobile version?  I couldn't get the Android TV app version to play anything (strm, live tv, local media).  I've had success playing everything on the android mobile version on a Fire tablet.  I could resume google transcode streams (I don't recall testing fast forwarding).

I have been looking at the code (it is open source after all), and I've got some ideas on improving playback for STRM files.  It might also be possible to incorporate CORs support, which would be of great benefit for Google Transcode streams.
