### ISSUE TITLE
[Issue]: Executing calls from Swagger UI after authorizing returns 401 Unauthorized

### ISSUE THREAD

**Issue by caseyscarborough** [jellyfin/jellyfin#7190]
### Please describe your bug

When viewing the `/api-docs/swagger` endpoint, the "Try it out" calls don't work due to 401 authorization failure after setting the authorization header.

Would it be possible to set the authorization to use the `X-Emby-Token` header or for the requests to pass the `api_key` or `ApiKey` parameters? I'm looking at the options [in the source code here](https://github.com/jellyfin/jellyfin/blob/master/Jellyfin.Server.Implementations/Security/AuthorizationContext.cs#L78-L97).

I think this is due to `X-Emby-Authorization` header at the very bottom of the `openapi.json` file:

```json
    "securitySchemes": {
      "CustomAuthentication": {
        "type": "apiKey",
        "description": "API key header parameter",
        "name": "X-Emby-Authorization",
        "in": "header"
      }
    }
```

It's completely possible I'm using this incorrectly so please let me know if that's the case.

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: Ubuntu 20.04
- Virtualization: Kubernetes
- Clients: Browser
- Browser: Chrome
- Reverse Proxy: Nginx
```

### Jellyfin logs

This is the only log that appears on the server when making the request:

```shell
[00:24:55] [INF] [59] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.
```

### Please attach any browser or client logs here

<img width="639" alt="Screen Shot 2022-01-16 at 12 43 38 AM" src="https://user-images.githubusercontent.com/3237612/149648780-5088bdee-7625-4eb1-a91a-71fe909bf0d4.png">

### Please attach any screenshots here

<img width="749" alt="Screen Shot 2022-01-16 at 12 39 16 AM" src="https://user-images.githubusercontent.com/3237612/149648795-125ce749-f960-4e33-b791-3e809d2dd35f.png">

<img width="596" alt="Screen Shot 2022-01-16 at 12 39 30 AM" src="https://user-images.githubusercontent.com/3237612/149648799-75021265-51e9-4f99-92d1-fa1a4a715b8e.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
I was able to authenticate by putting the following into that textbox: `Mediabrowser Token="$token"`
eg: `Mediabrowser Token="12345abcdef"`

**Comment by caseyscarborough** [comment]
Awesome, that fixed it @crobibero. Thanks so much!

**Comment by matthewstrasiotto** [comment]
although @crobibero gives a fix for this, I think that the documentation of how to correclty format this value needs improvement, and i wonder if that's worth addressing

**Comment by vortex91** [comment]
this needs to be addresssed in api doc.  As the same issue is present when doing api calls via python scirpts for some but not all endpoints

**Comment by infinitecreator** [comment]
I can confirm [crobiber](https://github.com/crobibero) solution still works as of now

**Comment by Parcothsai** [comment]
I can confirm @crobibero solution works, thanks you very much for that  !

**Comment by IvanKlossSE** [comment]
I just ran into this issue and @crobibero's solution still works. Thanks!

This issue should be open

**Comment by Jheesbrough** [comment]
Isssue is still present in swagger.
