### ISSUE TITLE
[Issue]: Error when creating collection with invalid characters

### ISSUE THREAD

**Issue by Goblinlordx** [jellyfin/jellyfin#7200]
### Please describe your bug

I have the following setup:
 - Jellyfin running inside a docker container
 - lib folder is mapped to a folder on an `exFAT` formatted partition
 
 When creating a collection containing an invalid character in the name (":" in this case), I get an error and the collection is not created. No error message is presented to the user.
 
 Steps to recreate (using setup described):
  1. Select some movies
  2. Add to a new collection with an invalid character in the name ("Berserk: Golden Age Arc Collection" was the name used for me)
  3. Operation never completes and is stuck at loading. When viewing the logs I see the following error:
  
  ```
  [2022-01-16 20:56:22.908 +00:00] [ERR] [11] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request: "Could not find a part of the path '/var/lib/jellyfin/data/collections/Berserk: Golden Age Arc Collection [boxset]'". URL "POST" "/Collections".
  ```
  
  I actually ran into this when using the box set plugin and reported the issue in it's repo first.. Upon further investigation, it seems it might be more desirable to do something in Jellyfin rather than the plugin.

Issue Ref: [Issue](https://github.com/jellyfin/jellyfin-plugin-tmdbboxsets/issues/57)

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: Linux
- Virtualization: Docker
- Clients: Any (Browser in this case)
- Browser: Chrome
- FFmpeg Version: (not sure where to check this)
- Playback Method: N/A (not a playback issue
- Hardware Acceleration: N/A (not a playback issue
- Plugins: N/A (Error occurs when using adding collection manually)
- Reverse Proxy: Traefik
- Base URL: none
- Networking: Docker internal network (no special networking setting)
- Storage: Local (`/var/lib/jellyfin` folder mapped to folder on exFAT formatted partition)

Docker compose settings for jellyfin service (real domain name removed):

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    restart: unless-stopped
    environment:
      - JELLYFIN_CACHE_DIR=/var/cache/jellyfin
      - JELLYFIN_CONFIG_DIR=/etc/jellyfin
      - JELLYFIN_DATA_DIR=/var/lib/jellyfin
      - JELLYFIN_LOG_DIR=/var/log/jellyfin
    volumes:
      - /media/terra/jellyfin/config:/etc/jellyfin
      - /media/terra/jellyfin/cache:/var/cache/jellyfin
      - /media/terra/jellyfin/lib:/var/lib/jellyfin
      - /media/terra/jellyfin/log:/var/log/jellyfin
      - /media/terra/media:/media
    labels:
      - "traefik.http.routers.jellyfin.rule=Host(\"jellyfin.####.com\")"
      - "traefik.http.routers.jellyfin.tls=true"
      - "traefik.http.routers.jellyfin.tls.certresolver=primary"
      - "traefik.http.routers.jellyfin.tls.domains[0].main=jellyfin.####.com"
      - "traefik.http.routers.jellyfin.service=jellyfin-svc"
      - "traefik.http.services.jellyfin-svc.loadBalancer.server.port=8096"
      - "traefik.http.services.jellyfin-svc.loadBalancer.passHostHeader=true"
```
```


### Jellyfin logs

```shell
[2022-01-16 20:56:22.908 +00:00] [ERR] [11] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request: "Could not find a part of the path '/var/lib/jellyfin/data/collections/Berserk: Golden Age Arc Collection [boxset]'". URL "POST" "/Collections".
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Goblinlordx** [comment]
This issue still exists.

**Comment by GreatestFool** [comment]
@Goblinlordx I assume you've figured it out by now, but essentially, don't use characters like `:` in file or directory names, even if your specific OS supports it. Many do not, and you'll have an easier time if you avoid special characters in the name. A dash, for example, is what the documentation recommends and that should function for all operating systems.

Here's a [random list I found online](https://www.mtu.edu/umc/services/websites/writing/characters-avoid/), if you'd like a reference. You can also likely find actual official documentation for illegal or protected characters in file and directory names for the operating systems you search for.
