### ISSUE TITLE
[Issue]: Searching from live tv guide results in matches in wrong categories

### ISSUE THREAD

**Issue by SenorSmartyPants** [jellyfin/jellyfin#7204]
### Please describe your bug

When searching live tv guide data search produces results in wrong categories. See screenshot below.

Go to. Live Tv -> Guide -> Search
http://localhost:8096/web/index.html#!/search.html?collectionType=livetv
Search for a series name in the guide. 
Witness many false positives.

Requested searches pass parameters of IsKids, IsMovie, etc to /User/{userid}/Items/
http://localhost:8096/Users/5099a249125a4292ba59df36931326de/Items?searchTerm=nature&Limit=24&Recursive=true&EnableTotalRecordCount=false&ImageTypeLimit=1&IncludePeople=false&IncludeMedia=true&IncludeGenres=false&IncludeStudios=false&IncludeArtists=false&IncludeItemTypes=LiveTvProgram&IsMovie=true&IsSeries=false&IsSports=false&IsKids=false&IsNews=false&api_key=282c242238df40ca88df65fa4f6c8dfc

ItemsController does not bind those parameters
https://github.com/jellyfin/jellyfin/blob/b6b7a89bf2e54a4cb6731ba401d1858f37ddb449/Jellyfin.Api/Controllers/ItemsController.cs#L586

### Jellyfin Version

Other

### if other:

10.8.0

### Environment

```markdown
- OS:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Please attach any screenshots here

![image](https://user-images.githubusercontent.com/991618/149683107-fe78a893-ac4b-4684-9af4-e2d32461ade2.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SenorSmartyPants** [comment]
Still a problem

**Comment by srcrist** [comment]
Issue is closed by https://github.com/jellyfin/jellyfin/pull/7780
