### ISSUE TITLE
[Issue]: Cannot compute blurhash

### ISSUE THREAD

**Issue by dream10201** [jellyfin/jellyfin#7212]
### Please describe your bug

`[2022-01-18 02:57:24.161 +08:00] [ERR] Cannot compute blurhash for "/mnt/data/media/image/wallhaven-3zzd1v.jpg"
System.NullReferenceException: Object reference not set to an instance of an object.
   at BlurHashSharp.SkiaSharp.BlurHashEncoder.Encode(Int32 xComponent, Int32 yComponent, String filename, Int32 maxWidth, Int32 maxHeight)
   at Emby.Drawing.ImageProcessor.GetImageBlurHash(String path)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)`

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS:raspberry 4b 8G
- Virtualization:debian 11
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dream10201** [comment]
[wallhaven-3zzd1v.zip](https://github.com/jellyfin/jellyfin/files/7885456/wallhaven-3zzd1v.zip)

**Comment by BoscoMurray** [comment]
I'm also runing 10.7.7 and have the same error for several files

**Comment by Coloradohusky** [comment]
Duplicate of #3687?
