### ISSUE TITLE
Ffmpeg uses extreme cpu

### ISSUE THREAD

**Issue by Rajeshsahoo12** [jellyfin/jellyfin#7216]
Currently using jellyfin docker image from https://www.linuxserver.io/

Facing issue of high cpu usage while streaming in night hours. I use jellyfin for android tv, android phone & web based on windows pc.

But when I stream contents in night time. 

There is high usage of cpu for FFMPEG. Here below is image from linux server terminal. Any solution to fix this.

And system load reaches more than 8.0. Due to which playback becomes unstable & it just stucks.

![image](https://user-images.githubusercontent.com/54216637/150020966-80f579ad-fc3f-4873-97a1-84f5f5cd46b3.png)

**Comment by Goblinlordx** [comment]
It is probably helpful to create issues using the template to ensure necessary information is provided. I am not a dev who has been working on this project but looking at the issue, it seems like something that could reasonably happen depending on the machine specs (support for hardware acceleration?), version information, content encoding type, as well as if the content is being transcoded (it sounds like it might be).

When something is being transcoded, there are certain formats which if there is no hardware acceleration, I do believe high CPU usage would be expected.

As a note, this is just coming from me as a user of this project.

**Comment by DarpanIO** [comment]
i can understand the high usage for server purposes but when using in localhost consumption should be less . I want to request the developer to include "Original video settings" also so that when using in localhost it doesn't work as a media server but as a local media player with some metadata about media

**Comment by Kivylius** [comment]
I have recently switched from emby and Im also keep getting this issue too, Im on synolagy nas 720+,  in not even big files, like 2-3gb, restart do not work, my net/hardware is able to support 4k, and defo had no issues with smaller files before, seems like jellyfin maybe the issues;

As above said: Can we not just steam mkv files without conversion.

``` 
PID USER      PR  NI    VIRT    RES  %CPU %MEM     TIME+ S COMMAND                                                                                                                                                                                                                                                                                                                                                                                                                                                            
28749 root    20   0 1137.1m 293.9m 292.1  7.8   4:59.72 S /var/packages/ffmpeg/target/bin/ffmpeg -ss 00:04:12.000 -noaccurate_seek -f matroska,webm -i file:/volume1/file.mkv -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 libx264 -pix_fmt yuv420p -preset veryfast -crf 23 -maxrate 5420863 -bufsize 10841726 -profile:v:0 high -level 41 -x264opts:0 subme+ 
```

**Comment by castillo92** [comment]
> I have recently switched from emby and Im also keep getting this issue too, Im on synolagy nas 720+, in not even big files, like 2-3gb, restart do not work, my net/hardware is able to support 4k, and defo had no issues with smaller files before, seems like jellyfin maybe the issues;
> 
> As above said: Can we not just steam mkv files without conversion like you can do via VLC on tables, phones, etc.. Or an option in quality "Original", let the media player handle that and even if its not supported it will complain. Seems like a total waste of cpu tbh as the same files on vlc plays with like 2% cpu.
> 
> ```
> PID USER      PR  NI    VIRT    RES  %CPU %MEM     TIME+ S COMMAND                                                                                                                                                                                                                                                                                                                                                                                                                                                            
> 28749 root    20   0 1137.1m 293.9m 292.1  7.8   4:59.72 S /var/packages/ffmpeg/target/bin/ffmpeg -ss 00:04:12.000 -noaccurate_seek -f matroska,webm -i file:/volume1/file.mkv -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 libx264 -pix_fmt yuv420p -preset veryfast -crf 23 -maxrate 5420863 -bufsize 10841726 -profile:v:0 high -level 41 -x264opts:0 subme+ 
> ```

This is happening to me too since lot of months... I would like an option "quality original" to minimize the CPU ussage

**Comment by nyanmisaka** [comment]
Why don't you use Jellyfin Media Player client on desktop? Browsers usually have the worst video/audio compatibility.

For example, it's impossible to play HEVC or Dolby or DTS audio in Chrome/Firefox without server side transcoding. The browser just doesn't support these formats.

**Comment by nyanmisaka** [comment]
This is not a server issue, transcoding happens only when your phone, tv client or browser doesn’t support certain formats. If you want to completely disable transcoding, go to Dashboard-Users, you can uncheck transcoding here.

**Comment by TheOverpassArsonist** [comment]
> Why don't you use Jellyfin Media Player client on desktop? Browsers usually have the worst video/audio compatibility.
> 
> For example, it's impossible to play HEVC or Dolby or DTS audio in Chrome/Firefox without server side transcoding. The browser just doesn't support these formats.

The Media Player Client doesn't respect multimedia control keys, browsers do.
