### ISSUE TITLE
[Issue]: Windows unstable archives again is empty

### ISSUE THREAD

**Issue by WWWesten** [jellyfin/jellyfin#7218]
### Please describe your bug

https://repo.jellyfin.org/releases/server/windows/unstable/ again and again is empty. @joshuaboniface @anthonylavado what's up?

### Jellyfin Version

Other

### if other:

10.8.0

### Environment

```markdown
- OS:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anthonylavado** [comment]
The mirrors have been updated with a fix. What happened is that there was an update to the page that build the download listing. Most of the content is pretty much the same across all distributions. In this case, some of the code to generate the page was copied over from the stable release, and it was looking for an installer folder (which doesn't exist for unstable builds).
