### ISSUE TITLE
[Issue]: Unable to Play or Shuffle Music Collections

### ISSUE THREAD

**Issue by unarj** [jellyfin/jellyfin#7226]
### Please describe your bug

have 3 music collections,.  all of them will not play from browser or Android client with the same error "Playback Error, The client isn't compatible with the media and the server isn't sending a compatible media format."  individual albums int eh collections play without issue.

tested by making a collection with a single album I'm 100% sure plays without issue, this fails with the same error.

no output is generated on the console, looks like there is no attempt at all to serve the media.

movie collections seem to play fine.

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: ubunut 20.04
- Virtualization: docker
- Clients: Windows, Android
- Browser: chrome, firefox
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by unarj** [comment]
this is still an issue.  collection of only music files, pressing play or shuffle causes error popup.

**Comment by unarj** [comment]
verified that this is till an issue with 10.8.0 docker release

**Comment by kerenon** [comment]
Still an issue with release 10.8.3 (docker).
