### ISSUE TITLE
[Issue]: Reduce the number of queries

### ISSUE THREAD

**Issue by jaysonsantos** [jellyfin/jellyfin#7237]
### Please describe your bug

Hi there, first thank you all for this amazing project, I really want to see Jellyfin as a 1st grade product :).
I'd like to open this issue in order to propose query reduction per routes, so this could make more effective usage of the disk when sqlite has to fetch data from it.
To try and measure the pain points of the app, I started a branch to instrumentate the code with opentelemetry (if it is something you would like to have upstream, let me know).
Here you can see an average of time per route, note that my local server uses HDD, so any random read would suffer.
![image](https://user-images.githubusercontent.com/51510/150653393-0f9d9909-96ef-451b-8568-912ab7c6b9db.png)
Then you can see on the details, that many queries will be issued (a bit hard to see here, but i can share the dashboard with whoever wants to see it).
![image](https://user-images.githubusercontent.com/51510/150653452-31dc5dae-8045-46b7-be9a-36b976fc0b42.png)

The effects of this is that you can also see that it seems to be locked in a transaction because other threads/tasks are using the db for a longer period.
![image](https://user-images.githubusercontent.com/51510/150653518-feb0da4b-cf83-47ec-a532-c358e54ea783.png)

What do you say? Do you see this as an improvement to be made? 
I see slow endpoints even when running from my dev machine with nvme, so I guess that the locks are the ones affecting its performance.

### Jellyfin Version

Other

### if other:

master branch

### Environment

```markdown
- OS: Ubuntu 20.04
- Virtualization: Bare metal
- Clients: Browser, Android, Fire TV Cube, Android TV, iOS
- Browser: Chrome
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins: trakt
- Reverse Proxy: direct connection
- Base URL: /
- Networking: host
- Storage: nfs
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cvium** [comment]
I would personally be interested in seeing how you did the instrumentation, but I'm not sure it's something we'd upstream.

**Comment by jaysonsantos** [comment]
@cvium my current local patch you can find here https://gist.github.com/0ae616d0f3c73c577da8eff72707e1f6

**Comment by jaysonsantos** [comment]
@cvium the cool thing is that it could be upstreamed without additional "weight" on standar installations because it only reports for subscribers of the ActivitySource's, and it could be only activated if provided a collector's url, i guess this would help observe patterns where the app is being slow

**Comment by mic-max** [comment]
Dang, I would love to get open telemetry out of my Jellyfin server and am sad this didn't get added
