### ISSUE TITLE
[IMPROVE]: Detects movie title as a TV Show (Mixed Library)

### ISSUE THREAD

**Issue by castillo92** [jellyfin/jellyfin#7244]
### Please describe your bug

In my instance of Jellifyn I have a library setup as "Mixed" type, because I have movies and TV Shows inside and it works well until now.

But today I joined all movies of Disney inside a folder "Disney" and it detect it as a TV Show instead of a folder with multiple movies. It overwrite a lot of metadata with a show I do not have. And "Folder view" shows the same as entering in the library. I do not understand

The layout of my library is the following

```
Libray
 |- Folder TV Show 1
 |- Folder TV Show 2
 |- Folder TV Show 3
 |- Folder TV Show ...
 |
 |- Folder Disney
 |   |- Movie 1
 |   |- Movie 2
 |   |- Movie 3
 |   |- ...
 |
 |- Movie 1
 |- Movie 2
 |- Movie 3
 |- ...
```

The titles above is some of the files that was triggering the "TV Show" label in entire folder.

```
Fantasia 2000 (1999)
        Season 20

Wall-E (2008) 1080p
        Season 1 chapter 8

Aladdin.2019.mHD.BluRay.DD5.1.x264.mkv
        Season 20 Chapter 19

Encanto (2021) (DSN+ WEB-DL 1080p AVC ES NEUTRO DD+ 5.1 - EN DD+ 7.1 Subs]
     Note the "(" instead of "["
Plus changing the titles that contains numbers with romans symbols, as you said:

101 Dalmatas (1961)
    Season 1 chapter 1
    Changed: One Hundred and One Dalmatians (1961)

Shrek 1
Shrek 2
Shrek 3
Shrek 4
Peter Pan 1 (1953)
Peter Pan 2 (2002)
Los increibles 1 (2004)
Los increibles 2 (2018)
```

All TV Shows triggers was solved changing number by Romans numbers or cleaning the filename. Could we work to improve REGEX detection?

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: Debian 10.7.7
- Virtualization: ESXi
- Clients: Browser
- Browser: Chrome 91.0
- FFmpeg Version: N/A
- Playback Method: Direct or transcode
- Hardware Acceleration: None
- Plugins: No
- Reverse Proxy: Apache
- Base URL: domain.com/jellyfin/
- Networking: NAT
- Storage: HDD local
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sourpatched** [comment]
Clearing the file names could help with this. It's also best to keep Movies and showing in it's own folder.
