### ISSUE TITLE
[Issue]: Refresh Metadata -> search for missing metadata overwrites episode overview

### ISSUE THREAD

**Issue by SenorSmartyPants** [jellyfin/jellyfin#7247]
### Please describe your bug

in 10.7.7 and 10.8.0

- Go to episode
- edit metadata
- change overview to "test"
- refresh metadata, search for missing
- overview is restored to whatever provider returns. Overview is no longer "test"

So unless I'm miss understanding what missing metadata is, this seems like a problem.

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS:Armbian
- Virtualization: Docker
- Clients: Browser
- Browser:Chrome
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins: TVDB, TMDB
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kirichenec** [comment]
bug still present!

**Comment by kirichenec** [comment]
Bug still present! All series overviews was overriden today

OS : Windows 11
Jellyfin version: 10.10.7 (not as service)
