### ISSUE TITLE
Published Server URIs does not apply a subpath input

### ISSUE THREAD

**Issue by PanDoreS** [jellyfin/jellyfin#7251]
Hey there!

I've been struggling to apply the last bit of my Jellyfin server.

I'm trying to setup a reverse proxy with the Docker image of Jellyfin.
The setup works quite well, except on the fact that I'm unable to add Jellyfin as a subpath.

System:
OS: Debian 10
Virtualization: Docker
Clients: Browser
Browser: Version 15.2 (17612.3.6.1.6)
Jellyfin Version: 10.7.7
Installed Plugins: None
Reverse Proxy: Nginx

I've been following [this documentation](https://jellyfin.org/docs/general/networking/nginx.html#nginx-with-subpath-exampleorgjellyfin) from the Jellyfin website.
For now, no traffic is passed through Nginx as I'm testing directly with the exposed Docker port.

From what I understood of the documentation, I should insert the raw subpath in the `Published Server URIs` field.
The goal for me is to have `https://server.uri:8096/jellyfin`.

However, the output `/jellyfin` doesn't change the subpath, after, of course, restarting the server.

Looking at the logs I can observe the following error:
```
jellyfin    | [20:33:35] [ERR] [29] Jellyfin.Networking.Manager.NetworkManager: Unable to parse bind override: /jellyfin
```

[From what I read of the code](https://github.com/jellyfin/jellyfin/blob/4d1b8246513b352d65d4db6afcb97ae1e984c760/Jellyfin.Networking/Manager/NetworkManager.cs#L920), it is expected to have the value split by a `=` character.

I've tried each setting parsed in the first half, `all` and `external`.
I've also tried multiple settings like `server.uri/jellyfin`, `https://server.uri/jellyfin`.
No luck, either I hit a parsing error, or the setting is not applied.

cURLing the server on `/jellyfin` each time gives a 404 error:
```
curl http://server.uri/8096/jellyfin/ -v
*   Trying x.x.x.x:8096...
* Connected to server.uri (x.x.x.x) port 8096 (#0)
> GET /jellyfin/ HTTP/1.1
> Host: server.uri:8096
> User-Agent: curl/7.77.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Date: Tue, 25 Jan 2022 20:53:48 GMT
< Server: Kestrel
< Content-Length: 0
< X-Response-Time-ms: 0
<
* Connection #0 to host server.uri left intact
```

Would you have any tips on what I'm missing here?

Thanks a lot!

**Comment by crobibero** [comment]
Have you tried setting your baseUrl?

https://jellyfin.org/docs/general/networking/index.html#base-url

**Comment by PanDoreS** [comment]
Yep, I'm definitively tired. It was indeed the wrong setting I was changing.
Sorry about that and thanks for your help crobibero!
