### ISSUE TITLE
10.8.0 "Keyframe Extractor" task localization problem

### ISSUE THREAD

**Issue by WWWesten** [jellyfin/jellyfin#7254]
### Please describe your bug

With PR https://github.com/jellyfin/jellyfin/pull/6600 was implemented a new scheduled task "Keyframe extract". Header of the task and they description lable are hardcoded and non-localizable. It has inconsistency counter other scheduled tasks' texts.

1. Need implementing globalization of hardcoded exppressions
2. Need rewording header "Keyframe Extractor" to "Extract Keyframes" (may be like "Extract Chapter Images" task)

@cvium what do you think about this? TNX

### Jellyfin Version

Other

### if other:

10.8.0

### Environment

```markdown
- OS:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cvium** [comment]
Makes sense.

**Comment by AnonymousWebHacker** [comment]
> 1. globalization of hardcoded exppressions

waiting for "globalization of hardcoded exppressions"
