### ISSUE TITLE
[Issue]: Duplicate albums when multiple versions of the album are present

### ISSUE THREAD

**Issue by b1scoito** [jellyfin/jellyfin#7261]
### Please describe your bug

When multiple versions of the same album are present (e.g, different pressings, transcodes) it shows duplicate versions of the album. I know that's expected functionality, but having a option to select multiple codecs on just one album would much more organized.

A good way to check for different versions is checking for the Catalogue number and the codec as said before too.

I, for example, have the same version of the album in 24bit FLAC, FLAC, MP3 CBR and MP3 VBR.

Here's a screenshot:
![image](https://user-images.githubusercontent.com/17802984/151672636-af66e9a5-589d-4111-9b58-76e379ca75d5.png)

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: Ubuntu 20.04.3 LTS (GNU/Linux 5.13.0-27-generic x86_64)
- Virtualization: Docker
- Clients: Browser, iOS
- Browser: Chrome 97.0.4692.99
- FFmpeg Version: 4.3.2-Jellyfin
- Playback Method: Direct Play
- Hardware Acceleration: none
- Plugins: AniList 4.0.0.0, AudioDB 10.7.7.0, InfuseSync 1.4.1.0, Last.fm 7.0.0.0, MusicBrainz 10.7.7.0, OMDb 10.7.7.0, Open Subtitles 12.0.0.0, Playback Reporting 10.0.0.0, Reports 12.0.0.0, Trakt 12.0.0.0
- Reverse Proxy: nginx
- Base URL: none
- Networking: Host
- Storage: local
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by b1scoito** [comment]
Update on this: Would be nice to have a black list for scanning file types on the library settings, for example, exclude mp3 from getting scanned.

**Comment by 42triangles** [comment]
I have found a probably related issue, if you have two libraries, and an album is in both libraries, it'll be displayed two times in each library.

Though probably caused by the same underlying behaviour as far as I can tell, if I should open another issue for this please do feel free to tell me.

**Comment by b1scoito** [comment]
It's most likely caused by the same behavior.

**Comment by b1scoito** [comment]
Yes, the "issue" still persists on version 10.8.9.

**Comment by Bond-009** [comment]
Falls under this feature request
https://features.jellyfin.org/posts/994/multiple-versions-of-music
