### ISSUE TITLE
Wrong translation in Polish

### ISSUE THREAD

**Issue by sakej** [jellyfin/jellyfin#7262]
### Please describe your bug

Should be "Strumieniuj" 
sure Cast is also Obsada but that is wrong meaning here
![image](https://user-images.githubusercontent.com/15695263/151675920-636be161-f9fc-437b-9f1a-627fbc9831c0.png)

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
https://translate.jellyfin.org/
