### ISSUE TITLE
[Issue]: No error message when transcoding is disabled

### ISSUE THREAD

**Issue by innosflew** [jellyfin/jellyfin#7278]
### Please describe your bug

My goal is to force every user to only use the clients which support direct play for most types of media, so I have disabled audio and video transcoding for every user, but when people try to play media from clients that don't support direct play instead of giving an error message it just simply loads in a frozen image with the thumbnail when it requires video transcoding, and when it requires audio transcoding it plays the media without audio. This could cause a lot of confusion and could make people think there is something wrong with Jellyfin.

My suggestion would be (assuming this is not a bug that's specific to me) an error message that would say something like:

> "This media couldn't be played because [video/audio] transcoding is disabled. Please use a client which support Direct Play for this type of media, such as the Jellyfin Media Player."

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: Windows 11
- Virtualization:
- Clients: Browser, Windows Jellyfin Media Player, Android Jellyfin app
- Browser: Firefox 96
- FFmpeg Version:
- Playback Method: Transcode
- Hardware Acceleration: none
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Please attach any screenshots here

This is what you see when you try to play a media that requires video transcoding. No error message, nothing. And you can't even click on something to go back. You have to reload the site.
![image](https://user-images.githubusercontent.com/18039193/152691260-96be998c-e0f6-47af-a5ad-94f8a41c9a86.png)

And when it requires audio transcoding it plays the video without audio. This could also confuse people, and it would be better if it didn't play the media just gave an errpr message.
![image](https://user-images.githubusercontent.com/18039193/152691442-def2ff12-598b-4865-b5d5-29a0fada75c9.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by UttermostUsername** [comment]
This is still an issue. I'm commenting because the bot says "To avoid abandoned issues, it will be closed in 21 days if there are no new comments."
