### ISSUE TITLE
Show helpful error message when "No capable devices found"

### ISSUE THREAD

**Issue by Germs2004** [jellyfin/jellyfin#7292]
### Please describe your bug

When transcoding is attempted and ffmpeg outputs the error "No capable devices found," that error gets written to a log file and the Jellyfin web client only shows a generic error to the user.  That makes it difficult for the user to identify the cause of the problem unless they happen across that log file and understand it.  Please change Jellyfin to detect that error output and display a more helpful error message.

Suggested new error message:

"This media cannot be played right now because the server's hardware acceleration device is not available.  The server administrator likely needs to choose a different hardware acceleration device in the Jellyfin settings."

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: Windows 10
- Virtualization: none
- Clients: Browser
- Browser: Brave, Chrome, Edge
- FFmpeg Version: n4.3.2-Jellyfin
- Hardware Acceleration: nvenc
- Reverse Proxy: no
```

### FFmpeg logs

```shell
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (native) -> h264 (h264_nvenc))
  Stream #0:1 -> #0:1 (aac (native) -> aac (native))
Press [q] to stop, [?] for help
[h264_nvenc @ 000001f3783d8a00] No capable devices found
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
[aac @ 000001f3783be540] Qavg: 64087.523
[aac @ 000001f3783be540] 2 frames left in the queue on closing
Conversion failed!
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sourpatched** [comment]
Is it possible for Jellyfin to have a "health Check" when the transecode settings are saved. This would include searching the server for the devices and letting admin know if something is missing.

**Comment by Germs2004** [comment]
> Is it possible for Jellyfin to have a "health Check" when the transecode settings are saved. This would include searching the server for the devices and letting admin know if something is missing.

That's a good idea too - that settings page would be easier if it could hide the options that aren't valid, or at least warn the admin when they click save if they have selected a device that isn't detected in that system.

**Comment by sourpatched** [comment]
And on the dashboard page within the server info have "hardware acceleration: Active (in green)"

**Comment by nyanmisaka** [comment]
`[h264_nvenc @ 000001f3783d8a00] No capable devices found`
It means your NVIDIA GPU doesn’t support NVENC.
