### ISSUE TITLE
Can you add a feature/setting to change the version of a movie while it is currently playing?

### ISSUE THREAD

**Issue by bnichs5** [jellyfin/jellyfin#731]
Can you add a feature/setting to change the version of a movie while it is currently playing?

So if im in the middle of a movie and it starts to lag do to high bitrate and I have another version with a lower bitrate I can switch to that by clicking the settings gear at the bottom of the video and switch and it will automatically start playing again where I left off before.

I hope that makes sense.

**Comment by JustAMan** [comment]
I don't think current settings allow you to change the movie version being played, they mostly apply to transcode and stuff, and, if I get @bnichs5 correctly, he/she wants to change to another version (with lower bitrate) and _still_ direct play it on the fly.

**Comment by bnichs5** [comment]
That's exactly right.
