### ISSUE TITLE
Seeking/Fast forwarding transcoded video does not work using DLNA

### ISSUE THREAD

**Issue by alexeynl** [jellyfin/jellyfin#7329]
During the playback transcoded video (i see .ts extension in the video name) using DLNA i can't change timeline position or using fast forward/backward )button << or >> is not active) in player.

Is this a bug, not supported feature (for example UMS can do this) or misconfiguration on my side?

Server is Jellyfin 10.8.0
Clients: Embedded player of Samsung Smart TV 2018, VLC 3.4.4 for ATV

**Comment by dylanrush** [comment]
This is still a problem for me. 

You shouldn’t have to re-encode your whole library to get basic features like skipping ahead. 

If a DLNA client requests to start playing at some point in the media, then the transcoder should go and start at the point. 

Currently with my DLNA client, if you skip forward the media will reset to the beginning.

**Comment by cvium** [comment]
Often, it is the dlna client not conforming with the spec. Dlna is not great to work with
