### ISSUE TITLE
[Issue]: Inconsistent stripping of file name in Video/Audio selection dropdowns/display

### ISSUE THREAD

**Issue by michaelkrieger** [jellyfin/jellyfin#7330]
### Please describe your bug

Within Jellyfin Web, as well as the Android-TV app, there seems to be inconsistent stripping of filenames in selecting the video/audio track.  I've noticed it on long file names in particular.

Some movies I see "4K HEVC HDR" as the video and "TrueHD 7.1 Atmos - Eng - Default" as the audio.
Others, I get "Movie.Name.2004.2160p.US.BluRay.REMUX.HEVC.DTS-HD.MA.TrueHD [cut off]" as the video name and "Movie.Name.2004.2160p.US.BluRay.REMUX.HEVC.DTS-HD.MA.TrueHD.Atmos-RLS - Eng - Dolby" as the audio selector.

This creates scrolling on the AndroidTV platform (which makes it hard to find the track you need) and cuts off until you drop down on Jellyfin-web (or is unviewable if it is cut off).

It seems to be a bug that it's not stripping the filename in the Audio/Video dropdowns of some movies and is displaying it for others, possibly due to the length of the filename.

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: Debian
- Virtualization: Docker
- Clients: Chrome, FireStick 4k Max
- Browser: Chrome 98
- FFmpeg Version: N/A
- Playback Method: N/A
- Hardware Acceleration: N/A
- Plugins: N/A
- Reverse Proxy: Traefik
- Base URL: none
- Networking: Bridge
- Storage: local
```

### Please attach any screenshots here

Not working as intended on many movies
[The obfuscated content is the movie name ie: "Movie.Name.2160p..." and release group "-ABC".]

![2022-02-17](https://user-images.githubusercontent.com/7321259/154562998-1d43eb37-262a-400a-bd69-9fa88a4d10eb.png)

Working as intended on some other movies
![2022-02-17 (1)](https://user-images.githubusercontent.com/7321259/154563145-0512773f-a983-427f-8b99-f5991103feae.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by michaelkrieger** [comment]
Still seeing this on all platforms..

**Comment by Shadowghost** [comment]
The track names are generated from codec info and the track name set within the container.
I guess in your case the "clean" track name does not have a track name set in the container and just displays the autogenerated part while the cut-off track name has one set, leading to the messy track name because we just dumbly insert it into the generated one.

**Comment by michaelkrieger** [comment]
What’s the point in displaying the whole filename here?  The important part is the language and track type (DTS-MA, etc). The filename has already been selected when the movie version was chosen.

my view is the file name should either be removed entirely, cropped to the first X characters to prevent exceeding the drop down (web) or scrolling (tv), or at least placed after the language/type.

i think the ideal would be to search/replace the filename and remove it entirely as that will show consistent behaviour with those which do have a track name set.

**Comment by Shadowghost** [comment]
It's not the file name which is shown. It's the name of the track inside the container.
