### ISSUE TITLE
[Issue]: Logs flooded with [WRN] Slow HTTP Response messages

### ISSUE THREAD

**Issue by ioogithub** [jellyfin/jellyfin#7348]
### Please describe your bug

The logs are flooded with slow HTTP response messages. This is an issue because the logs are being spammed with this message making it difficult to use the logs for useful troubleshooting. There are thousands of these messages up to 10 every second.

What is this message telling me? Is this an indication of a configuration problem? Almost all of these entries are less than a second. Is this considered a slow response time?

This is a new fresh install of Jellyfin.

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: Raspberry Pi 4B
- Virtualization: No
- Clients: Browser
- Browser: Firefox 97.0
- FFmpeg Version: ?
- Playback Method: n/a
- Hardware Acceleration: none
- Plugins: none
- Reverse Proxy: Apache
- Base URL: none
- Networking: Host
- Storage: local
```

### Jellyfin logs

```shell
[2022-02-21 12:18:51.566 -05:00] [WRN] Slow HTTP Response from "http://192.x.x.x/Items/70de05f19a446bd74d2cc8ff9b424572/Images/Primary?fillHeight=427&fillWidth=320&quality=96&tag=e966d8dc32b2e21b2d03f9a39a5e6884" to "192.x.x.x" in 0:00:00.9899466 with Status Code 200

[2022-02-21 12:18:52.031 -05:00] [WRN] Slow HTTP Response from "http://192.x.x.x/Items/e5e700a0234372084d251d6867698898/Images/Primary?fillHeight=427&fillWidth=320&quality=96&tag=34feecd611e4eb26d338ad5cd4112dc4" to "192.x.x.x" in  0:00:01.0591586 with Status Code 200

[2022-02-21 12:18:52.104 -05:00] [WRN] Slow HTTP Response from "http://192.x.x.x/Items/6f1d2db1cac50539643a4dfd999f5c4d/Images/Primary?fillHeight=427&fillWidth=320&quality=96&tag=b18163a4aa4b58c97192e901d76e3616" to "192.x.x.x" in 0:00:00.7037635 with Status Code 200

[2022-02-21 12:18:52.542 -05:00] [WRN] Slow HTTP Response from "http://192.x.x.x/Items/2c8ab7e4c62f71367e1f9a3ffcc1569b/Images/Primary?fillHeight=427&fillWidth=320&quality=96&tag=a9abbbc3f090010b05714c8777c113e1" to "192.x.x.x" in 0:00:00.6137338 with Status Code 200
```
```


### FFmpeg logs

```shell
n/a
```

### Please attach any browser or client logs here

n/a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by spannerman79** [comment]
https://github.com/jellyfin/jellyfin/issues/2455#issuecomment-802990196

I edited my `system.xml`.

Find `<EnableSlowResponseWarning>` and change `true` to `false`

I restarted Jellyfin after the change (not sure if it was required or not - but a restart of the service wouldn't hurt)

>What is this message telling me? Is this an indication of a configuration problem? Almost all of these entries are less than a second. Is this considered a slow response time?

_Perhaps_ your hardware is underpowered? 🤷‍♂️

**Comment by Al4ndil** [comment]
Hi @spannerman79 

I have the same messages on my logs with a debian machine (2 CPU, 12Go RAM). I don't think it has underpowered right ?!

**Comment by dannymichel** [comment]
> Hi @spannerman79
> 
> I have the same messages on my logs with a debian machine (2 CPU, 12Go RAM). I don't think it has underpowered right ?!

nothing to do with underpowered hardware. my server is a beast and this has always happened and continues to happen with jellyfin for me https://youtu.be/FTctXyJSMTs

**Comment by RubenTeixeira** [comment]
Agreed @Al4ndil.

It seems to me (at least that seems to be my case) this might have something to do with running the instance behind a reverse proxy.

**Comment by Cebrain** [comment]
> Agreed @Al4ndil.
> 
> It seems to me (at least that seems to be my case) this might have something to do with running the instance behind a reverse proxy.

I also use jellyfin behind reverse proxy. This is spamming the log.
I disabled the entry in the Dashboard -> Logs -> "Log a warning message ..."

![image](https://user-images.githubusercontent.com/78339531/204510020-75ee5554-316f-462d-b624-bb6ff2dbcddf.png)

Dont know if i could tweak the proxy to make it better.

**Comment by mtekman** [comment]
> _Perhaps_ your hardware is underpowered? 🤷‍

I believe this might be the case for anyone running Jellyfin server on a Raspberry Pi 4. I consistently get this message when trying to transcode a large film. 

The solution (at least for me) was to increase the GPU/RAM split in the `/boot/config.txt` file to:

```
gpu_mem_256=192
gpu_mem_512=256
gpu_mem_1024=256
```

Apologies that this response is hardware-specific, but I genuinely believe this was the main limiting factor (it couldn't transcode fast enough and so couldn't post the video snippets punctually?) in my case, and I would be surprised if I was the only one using Jellyfin on a Rpi4.
