### ISSUE TITLE
[Issue]: [10.8.0] Unable to play more than 100 songs via SyncPlay.

### ISSUE THREAD

**Issue by sapphic-wallflower** [jellyfin/jellyfin#7350]
### Please describe your bug

On the "Albums" menu of a music library, the "Play All" button does nothing while in a SyncPlay group. 

Steps to reproduce: 

Step 1: Have more than 100 songs in your library.
Step 2: Join a SyncPlay group.
Step 3: Go to the "Albums" tab of your music library and click "Play All". 

Nothing will happen afterwards. Video attached in the final box below. 

### Jellyfin Version

Other

### if other:

10.8.0 (Alpha 5)

### Environment

```markdown
- OS: Linux (Ubuntu 21.10 Impish)
- Virtualization: n/a
- Clients: Browser, Jellyfin Media Player (1.6.1 & 1.7.0-pre3), Jellyfin Mobile
- Browser: Mozilla Firefox 97.0, Google Chrome 98.0.4758.102, 
- FFmpeg Version: 4.4-6ubuntu5
- Playback Method: 
- Hardware Acceleration: Nvidia NVENC
- Plugins: AniDB, AniList, AniSearch, AudioDB, MusicBrainz, OMDb, TMDb, Studio Images
- Reverse Proxy: none
- Base URL:
- Networking:
- Storage: local
```

### Jellyfin logs

```shell
After clicking play, this is what outputs. 
[2022-02-21 22:24:21.968 -05:00] [INF] Session "a894bf2af502a2ede23aa7eefce8d214" requested Play in group "7021917f-c8dd-4fa2-827f-7c9adb0b34f4" that is Waiting.

Nothing happens.
```

### Please attach any browser or client logs here

![image](https://user-images.githubusercontent.com/70827619/155057684-3178682d-f15a-4a9e-b551-9bf0e4db0394.png)

### Please attach any screenshots here

https://user-images.githubusercontent.com/70827619/155057980-5899dea1-2d75-43cd-80de-8f25add817b2.mp4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Lixus99** [comment]
Seems to be related to issue [#2483](https://github.com/jellyfin/jellyfin-web/issues/2483)
