### ISSUE TITLE
Tries to read comicinfo.xml as an image

### ISSUE THREAD

**Issue by Meyu-Sys** [jellyfin/jellyfin#7353]
### Please describe your bug

Jellyfin's comic book   reader tries to read comicinfo.xml as an actual image instead of ignoring it

Step(s) to reproduce
1) create a cbz or cbr with a comicinfo.xml file in it
2) try to read it you will see a image failing to load in place of the comicinfo.xml

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: Windows
- Virtualization:
- Clients: All
- Browser:All
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Please attach any screenshots here

![2022-02-23_10-46](https://user-images.githubusercontent.com/86107480/155265270-4955e4a8-5ed6-4cec-ab7d-83725a0e29d1.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MinecraftPlaye** [comment]
Should be resolved in Jellyfin 10.8.0 by jellyfin/jellyfin-web#3361.
