### ISSUE TITLE
[Issue]: "Airs before episode" Special Metadata Not Sorting Correctly

### ISSUE THREAD

**Issue by FlaringAfro** [jellyfin/jellyfin#7354]
### Please describe your bug

After editing a Special's metadata to be sorted in the middle of a season, the episode still appears at the beginning. Other Special sorts ("Airs before season" and "Airs after season") seem to work fine, even if implemented for the same episode. The Library is Shows. I didn't see any documentation on any kind of formatting so I tried multiple values. This happens for all shows, and another [Reddit user](https://www.reddit.com/r/jellyfin/comments/sgu6ip/special_airs_before_episode_functionality/) has encountered the same issue.

**Folder structure**
TV Shows
├── Show Name
│   ├── Season 01
│   │   ├── Show Name S00E01.mkv
│   │   ├── Show Name S01E01.mkv
.
.
.
│   │   ├── Show Name S01E15.mkv

**Airs before episode value attempts in UI (letters weren't accepted)**
13
S01E13
01e13
01x13
0113

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: Windows 10
- Virtualization: None
- Browser: Chrome
- Plugins: AudioDB, MusicBrainz, OMDb
- Metadata Path: C:\ProgramData\Jellyfin\Server\metadata
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by YodaQ** [comment]
Do you also have the airs before season set to 1 and airs after season is blank. As far as i know the formatting is just a number as in 3. It would be great if the documentation was clearer on this though.

**Comment by Gaweringo** [comment]
For anyone coming across this in the future: If you want the special to be in the first season between episode 12 and 13 for example, set:
Airs before series: 1 | Airs after series: | Airs before episode 13
In the metadata settings.
Airs before needs to be filled in. Airs after series needs to be empty (only used if special is after all episodes of a season). Airs before episode is used to position the special in the season it is set to air before, with "Airs before series".
A bit confusing, but it works.
