### ISSUE TITLE
[Issue]: Folders in DLNA are empty

### ISSUE THREAD

**Issue by dffvb** [jellyfin/jellyfin#7356]
### Please describe your bug

Hi there, 

had this issue on Windows and now on Docker. If you check the DLNA Server and go to folder view these are always empty. Other view works and plays... 

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS:Windows
- Virtualization: Docker
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by arthurEspooner** [comment]
same
