### ISSUE TITLE
InfuseSync plugin does not work in 10.8.0 [Issue]: 

### ISSUE THREAD

**Issue by 0TTA** [jellyfin/jellyfin#7358]
### Please describe your bug

The title says it all.

### Jellyfin Version

Other

### if other:

10.8.0

### Environment

```markdown
- OS:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
The InfuseSync plugin is not maintained by Jellyfin, and plugins do not typically target unreleased versions of Jellyfin. 

https://github.com/firecore/InfuseSync
