### ISSUE TITLE
[Issue]: can‘t open pdf files in books section

### ISSUE THREAD

**Issue by mecca219er** [jellyfin/jellyfin#7360]
### Please describe your bug

i installed the stable version on windows 10 for server, and also i imported some pdf files as books，after i created a media library based on “books” contents，i can't open any pdf files at any client.

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: windows10
- Virtualization: N/A
- Clients: browsers，ios
- Browser: Chrome latest
- FFmpeg Version: don't know (installer) 
- Playback Method: add pdf files in a book folder, then use it as book media
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mecca219er** [comment]
Has anyone used the book section?

**Comment by prahal** [comment]
Using docker 10.8.0-alpha5 but it works here.
Are your pdf files DRM free?

For one https://elinux.org/images/f/f9/Petazzoni-device-tree-dummies_0.pdf .
