### ISSUE TITLE
Hardware acceleration transcoding using NVIDIA Container Toolkit not working.

### ISSUE THREAD

**Issue by Topkif** [jellyfin/jellyfin#7367]
Hi, I have installed a standalone version of docker (20.10.12) in Truenas Scale (Debian 11, kernel 5.10.93) and it has been working great with other apps.
The NVIDIA driver comes already installed, as well as the toolkit.
Then I installed jellyfin with docker run (and I also tried linuxserver.io compose file):
`docker run -d \
 --name=jellyfin \
 --gpus all \
 -p 8096:8096 \
 -p 8920:8920 \
 --volume /mnt/tank/jellyfin/config:/config \
 --volume /mnt/tank/jellyfin/cache:/cache \
 --volume /mnt/tank/jellyfin/data:/media\
 --restart unless-stopped \
 jellyfin/jellyfin`

It installed fine and if I do a `docker exec -it jellyfin nvidia-smi` I get:
![image](https://user-images.githubusercontent.com/81412017/155903121-ad7f6c91-d4da-43f5-bec6-0e9e6846102c.png)
So far so good! 😀

But then I enable jellyfin hardware acceleration using NVIDIA NVENC this error appears 
![image](https://user-images.githubusercontent.com/81412017/155903693-2e9a1ce3-b568-4805-88e9-e69ccc6c6232.png)

The logs are: 
[Log.txt](https://github.com/jellyfin/jellyfin/files/8149561/Log.txt)
What does this error means? `CUDA_ERROR_UNKNOWN: unknown error Device creation failed: -1313558101.`

Could you please help me diagnose this, I have tried so many things I don't know what to do next but to ask for help. Thank you.

**Comment by lucas-gautier** [comment]
Per the log file attached, video file may not be compatible with NVEC hardware acceleration because H264 at 4K resolution is not supported by the GPU hardware. TrueNAS Scale may also be missing a required software component, but I think the culprit is most likely the incompatible H264 source codec.

1. Can you try encoding a new 4K source file in HEVC format and retry on TrueNAS Scale?
2. Is the error reproducible on a regular/vanilla Debian 11 installation?

Referenced documentation: 
https://jellyfin.org/docs/general/administration/hardware-acceleration.html#h264--avc-10-bit-videos

**Comment by Topkif** [comment]
Sory for the delay, and thank you for answering me. I had tested the same video on jellyfin installed with truecharts and it worked great, but I don't want to use truecharts. So the video is not the problem I think.
Nevertheless I tried with an h265 4K video and it could be played from 4k to 480p but was very jerky (even without transcoding), but same problem occured when I scale it down to 360p.
I tried to reproduce the error on Debian 11. I had some problems installing the drivers but I think I did it. Now I see this:
![image](https://user-images.githubusercontent.com/81412017/156256048-11626e63-a907-48a5-8dbc-e43b1a62870a.png)

But after installing Jellyfin, the exact same problem occured but the log file is different: [Log_deb720p.txt](https://github.com/jellyfin/jellyfin/files/8165029/Log_deb720p.txt)
I will search the web for "Cannot load libnvcuvid.so.1"
Do you know a way of telling if the nvidia driver and the toolkit are properly installed?

**Comment by Topkif** [comment]
Ok I made it work on truenas scale by unistalling and reinstalling the driver and installing the nvidia container runtime, ans setting the default runtime to "nvidia" in daemon.json for docker.
