### ISSUE TITLE
Add a setting so subtitles only show when requested.

### ISSUE THREAD

**Issue by BobHassok** [jellyfin/jellyfin#7368]
Can we make it so subtitles don't automatically show? I would prefer an option, even if it's buried in the admin panel, to make it so subtitles only show when requested. I don't like that subtitles show automatically, I want the default playback to not have subtitles enabled. Also thanks for the awesome media server!

**Comment by crobibero** [comment]
Does this dropdown do what you want?

![image](https://user-images.githubusercontent.com/24963659/155904635-9c0738ef-9214-48ab-8872-6851aa4dfcd6.png)
Profile -> Subtitles

This option is likely client-specific.

**Comment by BobHassok** [comment]
> Does this dropdown do what you want?
> 
> ![image](https://user-images.githubusercontent.com/24963659/155904635-9c0738ef-9214-48ab-8872-6851aa4dfcd6.png) Profile -> Subtitles
> 
> This option is likely client-specific.

This does exactly what I want. I didn't realize it was profile specific.

This can be closed, thank you!
