### ISSUE TITLE
Group library folders use poster instead backdrop

### ISSUE THREAD

**Issue by n8llcaster** [jellyfin/jellyfin#7390]
**Describe The Bug**
If you use group function in Profile -> Home -> Library Folders Jellyfin will group categories as should, but it generates picture for icon in Home screen from poster rather than clean backdrop (background). Result is rather ugly.

**Steps To Reproduce**
1. Go to Profile -> Home -> Library Folders
2. Click on multiple libraries of movies/show to group
3. Return to home screen
4. You will see grouped shows/movies with background behind text generated from poster

**Expected Behavior**
Usage of backdrop (background), which has no text.

**Screenshots**
![group](https://user-images.githubusercontent.com/29764734/136243198-6f5e6efd-ceb1-419a-abbb-6f85dcfa280e.png)
![group example](https://user-images.githubusercontent.com/29764734/136243202-9675d7dd-2f3f-468d-b0f5-e2afeac1d84a.png)

**System (please complete the following information):**
 - Platform: W10/W11
 - Browser: FF93
 - Jellyfin Version: 10.7.7

**Comment by 1337joe** [comment]
Fixed for 10.8: #7221
