### ISSUE TITLE
[Issue]: "path is too long" error when add nfs or cifs mounted directory

### ISSUE THREAD

**Issue by ms8x8x** [jellyfin/jellyfin#7395]
### Please describe your bug

after mounting  nfs or cifs to local dir, files are normal in local system; but when adding to the library, the page just failed with nothing and logged some errors:

Error processing request: "The path '/mnt/videos/f/downloads/suc' is too long, or a component of the specified path is too long". URL "GET" "/Environment/DirectoryContents".

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: debian 11 standard lxc
- Virtualization: pve 7
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
Error processing request: "The path '/mnt/videos/f/downloads/suc' is too long, or a component of the specified path is too long". URL "GET" "/Environment/DirectoryContents".
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lhname** [comment]
I find the reason for this question.[jaantaponen](https://github.com/jaantaponen)has answered.It is a long time.something filename is too long in the folder
