### ISSUE TITLE
System.InvalidOperationException: The server is expected to host the web client

### ISSUE THREAD

**Issue by Chaos1141** [jellyfin/jellyfin#7401]
I'm seeing this on a fresh install and can't seem to find any solutions elsewhere.
![Screenshot from 2022-03-05 01-36-19](https://user-images.githubusercontent.com/94289619/156873632-c167e0ab-2ffc-4510-b807-653a3e4a246d.png)

**Comment by Shadowghost** [comment]
If you are using APT to install jellyfin, make sure the packages `jellyfin-server jellyfin-web jellyfin-ffmpeg` are installed and restart the service after installing the missing ones.

**Comment by Chaos1141** [comment]
![Screenshot from 2022-03-05 21-39-01](https://user-images.githubusercontent.com/94289619/156908335-71e79999-e213-4ac4-b5ef-f3e3c2058697.png)

**Comment by Chaos1141** [comment]
looks like a wipe and fresh install fixed it
