### ISSUE TITLE
[Issue]: Cast & Crew limited to 3

### ISSUE THREAD

**Issue by nodje** [jellyfin/jellyfin#7402]
### Please describe your bug

Identified movies never get more than 3 Cast & Crews. 
Same movies on Plex gets a lot more, and metadata are available on TMDB and others.

It has to be an issue somewhere

### Jellyfin Version

Other

### if other:

10.8.0-alpha5

### Environment

```markdown
- OS:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 1337joe** [comment]
What metadata providers are enabled on your library?

**Comment by rob-mur** [comment]
I have been unable to reproduce this bug on the main branch, using just the default metadata providers. I think more information would be needed to investigate this further.

**Comment by nodje** [comment]
Ok, I got it, TheMovieDb has to be in first position as a metadata downloader,
If The Open Movie Database  is first only 3 casts are fetched.

**Comment by rob-mur** [comment]
Interesting, I just tried it both ways (as well as if TheMovieDb was selected as a provider or not) and couldn't recreate the bug, at least for the film I was looking at. In any case, the next step looks to be to assess if the response from tomdb is actually limited to 3 or if jellyfin is discarding them somewhere?

**Comment by nodje** [comment]
Are there any specific logs I could look at during fetching of metadata?
Or a log level that I could activate to get more info?
