### ISSUE TITLE
Compatible with WD MY CLOUD EX2 ULTRA 

### ISSUE THREAD

**Issue by TheSamsungFreak** [jellyfin/jellyfin#7412]
Hello.. You are doing a good job.. I have a NAS at home WD MyCloud EX 2 Ultra. is it possible to make jellyfin compatible like emby. emby runs and works.. but i like jellyfin better..

**Comment by crobibero** [comment]
There is an existing feature request for WD MyCloud support: https://features.jellyfin.org/posts/733/add-support-for-wd-my-cloud-home-jellyfin-server-version
