### ISSUE TITLE
[Issue]: Transcoded output doesn't support proper HTTP HEAD responses

### ISSUE THREAD

**Issue by SenorSmartyPants** [jellyfin/jellyfin#7428]
### Please describe your bug

This issue is similar to #7137, but that PR only affected direct streaming output. Please support proper HTTP HEAD responses when remuxing or transcoding.

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cvium** [comment]
And what is a "proper HTTP HEAD response" in this case? We don't know the file size in advance, so the only useful information might be the content-type?

**Comment by SenorSmartyPants** [comment]
I've tested one or two other transcoders that could output HTTP 206 responses. I'm assuming that if the target video/audio/etc birates are known file size could be estimated.

**Comment by cvium** [comment]
An estimation wouldn't be valid, would it?

**Comment by SenorSmartyPants** [comment]
I'm assuming a close estimate would be good enough to support streaming and seeking for clients that rely on 206 responses.

**Comment by cvium** [comment]
But according to the spec, the headers must be identical if not omitted.

If the response is chunked, content length is not necessary, but I'm not sure what the GET returns.

**Comment by SenorSmartyPants** [comment]
I'm not sure what to tell you, I'm not an expert on this subject. I just know I found 1 or 2 transcoding servers that made compatible responses to my client. Unfortunately, the ones I found were not open source. I used them as debug tools to wireshark working responses.

> But according to the spec, the headers must be identical if not omitted.

Which headers must be identical? Content-Length? Identical to what, the HEAD vs the GET?

These hardware clients just won't stream if the HTTP server doesn't support 206 responses.

**Comment by tacerus** [comment]
Hi,

is this issue related to my stream URLs not providing a HEAD method?

```
$ curl -IXHEAD '[xxx:2200::abc]:8096/Items/5bc7ed61bd7901814d615a7b74d7eedd/Download?api_key=xxx'
HTTP/1.1 405 Method Not Allowed
Date: Wed, 27 Apr 2022 20:49:05 GMT
Server: Kestrel
Allow: GET
X-Response-Time-ms: 2
```

**Comment by SenorSmartyPants** [comment]
Pinging @nyanmisaka , Would you have any thoughts on this?
