### ISSUE TITLE
Clean install (fresh data directory) does not start anymore

### ISSUE THREAD

**Issue by lbeltrame** [jellyfin/jellyfin#744]
**Describe the bug**
The server does not start anymore after wiping the data directory, configuration, build and source directory.

The displayed error is always the same:

```
Unhandled Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path '/home/emby/jellyfin-data/config/ScheduledTasks/2c66a88b-ca43-e565-d7f8-099f825478f1.js'.
```
Then the process coredumps with SIGABRT.

`ScheduledTasks` is not created at all and I have no idea what the file would be. The behavior is 100% reproducible even when changing data directories.

**To Reproduce**

1. Clone jellyfin and submodules
2. Build with, for example `dotnet publish --configuration Release --output=/any/path/jellyfin-build --self-contained --runtime linux-x64`
3. Start the server with an empty data directory

**Expected behavior**
Server starts.

**Logs**
See above for logs.

**Comment by Bond-009** [comment]
Was just fixed #743
