### ISSUE TITLE
[Issue]: Editing the Metadata Settings of a Library folder fails

### ISSUE THREAD

**Issue by DUOLabs333** [jellyfin/jellyfin#7464]
### Please describe your bug

1. Go to "Dashboard" as Admin
2. Go to Libraries
3. Go to "Manage Library"
4. Uncheck one of the "Metadata Downloaders"
5. Press OK
6. See that the operation never completes

### Jellyfin Version

Other

### if other:

20220314.5

### Environment

```markdown
- OS: Arch Linux
- Virtualization:
- Clients: Android and Browser
- Browser: Firefox 88, Chrome 99
- FFmpeg Version: 4.4.1
- Playback Method: Transcode
- Hardware Acceleration: None
- Plugins: None
- Reverse Proxy: nginx
- Base URL: none
- Networking: Host
- Storage: local
```

### Please attach any screenshots here

![image](https://user-images.githubusercontent.com/49244768/158464988-f118d4b4-7c5d-448a-8739-7bf4ee5fbaa6.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Nalsai** [comment]
I had that issue too. The cause for me was that I switched from the linuxserver image to the official one. I moved the data correctly, but it was still trying to access it at the wrong path when I wanted to edit a library.

**Comment by Nalsai** [comment]
Possibly. You need to get the jellyfin logs to see what's wrong.

**Comment by Nalsai** [comment]
`Could not find a part of the path '/home/system/Services/jellyfin/service/data/root/default/Media'`
That's the problem

**Comment by DUOLabs333** [comment]
How would I change that?

**Comment by Nalsai** [comment]
I'm assuming `/home/system/Services/jellyfin/service/` is your data directory, which you have set with either `--datadir` or `JELLYFIN_DATA_DIR`. 
From there, your library options should be in `root/default/Media`, which is probably where they are, but when trying to edit a library, jellyfin is looking in `data/root/default/Media`. I believe that is set in `data/library.db`, so you would have to edit it there. It's a SQLite database (make sure to backup before).
When I ran into this issue I tried creating a symlink from `data/root/` to `root/`, but I still had some issues and was going to move to another server, so I just fully recreated my configuration.

**Comment by DUOLabs333** [comment]
Could I delete `Media` and start afresh?

**Comment by Nalsai** [comment]
You would have to delete the whole data directory (`/home/system/Services/jellyfin/data/data`) to start afresh.

**Comment by Nalsai** [comment]
Actually, deletin media might work but I'm not sure

**Comment by DUOLabs333** [comment]
Yes, deleting `Media` worked.
