### ISSUE TITLE
Emby plugin can not connect to jellyfin

### ISSUE THREAD

**Issue by ugenehan** [jellyfin/jellyfin#747]
When i use the emby for Kodi add-on  to connect tojellyfin server,it reports error as "invalid user name or password".IP address and port are all correct,and it can connect to emby server.
kodi version:18rc2
kodi emby plugin:4.0.1
jellyfin version:10.1.0

**Comment by ugenehan** [comment]
> Emby changed a lot of things in 4.0, so don't expect any compatibility. Our own fork will eventually be updated: https://github.com/jellyfin/jellyfin-kodi

The same error with jellyfin-kodi. And the jellyfin-kodi can't be installed to kodi 17.6.

**Comment by RazeLighter777** [comment]
This issue should be closed imo. We shouldn’t be playing cat and mouse with compatibility.

**Comment by joshuaboniface** [comment]
Agreed, compatibility with official Emby plugins isn't guaranteed to work at all - the fact it does with the logging changes is actually kind of a surprise, but we should focus on our own Kodi plugin, which I believe works? Needs confirmation on that.

**Comment by ugenehan** [comment]
> Agreed, compatibility with official Emby plugins isn't guaranteed to work at all - the fact it does with the logging changes is actually kind of a surprise, but we should focus on our own Kodi plugin, which I believe works? Needs confirmation on that.

The same error occurred in your own Kodi plugin.https://github.com/jellyfin/jellyfin-kodi
It can not installed on Kodi 17.Although it can be installed on kodi 18, it appears invalid username or password

**Comment by hawken93** [comment]
maybe change the issue to be about jellyfin-kodi then, otherwise it's invalid.

I don't have kodi and I think there's probably a lack of testers for kodi so it would be nice if you want to hang in here and help testing it if it gets worked on :)

(mods: maybe move this issue over there)

**Comment by cvium** [comment]
Testers needed: https://github.com/jellyfin/jellyfin-kodi/pull/3

**Comment by LeoVerto** [comment]
According to [this reddit thread](https://www.reddit.com/r/jellyfin/comments/an2ceq/emby_for_kodi_405_should_work_with_jellyfin/) Emby for Kodi should work again, can anyone confirm this?

**Comment by NotExpectYet** [comment]
Can confirm, been using it for a week or two now and it's working great!
