### ISSUE TITLE
[Issue]: Mint installation LTS 20.04 not working.

### ISSUE THREAD

**Issue by CyberaxAnnon** [jellyfin/jellyfin#7473]
### Please describe your bug

When following the official instruction online for the Ubuntu instructions and when installing it gives the following error

E: The repository 'https://repo.jellyfin.org/linuxmint una Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

This is not on a VM and rather a new install of mint. 
May be related to #7463, but related to 22.04 LTS?

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: Mint 20.03
- Virtualization: No
- Clients: N/A
- Browser: Firefox
- FFmpeg Version: N/A
- Playback Method: N/A
- Hardware Acceleration: N/A
- Plugins: N/A
- Reverse Proxy: N/A
- Base URL: N/A
- Networking: N/A
- Storage: N/A
```

### Please attach any screenshots here

![Untitled](https://user-images.githubusercontent.com/99626705/158923143-85946c16-860f-4b5a-a880-48f9429f1b51.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shadowghost** [comment]
Mint is not officially supported, you need to use the codename of an equivalent ubuntu distro in your sources.list

**Comment by Ghostfreak803** [comment]
Just edit the repo name and replace `.../linuxmint una` with `.../ubuntu focal`

**Comment by CyberaxAnnon** [comment]
I am having trouble trying to find the item to replace. 
Do I have to replace it within the 3rd instruction? 

echo "deb [arch=$( dpkg --print-architecture )] https://repo.jellyfin.org/$( awk -F'=' '/^ID=/{ print $NF }' /etc/os-release ) $( awk -F'=' '/^VERSION_CODENAME=/{ print $NF }' /etc/os-release ) main" | sudo tee /etc/apt/sources.list.d/jellyfin.list

**Comment by Ghostfreak803** [comment]
> I am having trouble trying to find the item to replace. 
> Do I have to replace it within the 3rd instruction? 
> 
> echo "deb [arch=$( dpkg --print-architecture )] https://repo.jellyfin.org/$( awk -F'=' '/^ID=/{ print $NF }' /etc/os-release ) $( awk -F'=' '/^VERSION_CODENAME=/{ print $NF }' /etc/os-release ) main" | sudo tee /etc/apt/sources.list.d/jellyfin.list
> 
> 

Well you can do that but i was talking about the repo address that's already saved now in your sources list. Simply open the Software Sources program and you'll find it under 'Additional Repositories'. Click on 'Edit' after selecting the jellyfin repo.

**Comment by CyberaxAnnon** [comment]
Thank you so much.
New to Linux and am still learning lol.
Appreciate the help.
