### ISSUE TITLE
Change Movie library from pages to a list

### ISSUE THREAD

**Issue by bnichs5** [jellyfin/jellyfin#748]
Anyway to remove the multiple pages for movies and make it one endless stream of movies to choose from?

**Comment by JustAMan** [comment]
Can you edit accordingly to enhancement template?.. At least please provide some reasoning or use case.

**Comment by wjbeckett** [comment]
> Anyway to remove the multiple pages for movies and make it one endless stream of movies to choose from?

Definitely want to see this. Pagination is a little annoying. It's easier to see all moves in one scrolling page rather than having to move forward and back through pages.

**Comment by sparky8251** [comment]
For those that find this issue, look here!

https://www.reddit.com/r/jellyfin/comments/autbcf/feature_request_show_all_items_in_library_on_one/ehamy9l/

Seems there is a way to configure this by editing a file.

**Comment by anthonylavado** [comment]
Closing in favour of #1237.
