### ISSUE TITLE
Installation page not found

### ISSUE THREAD

**Issue by mrashwin15** [jellyfin/jellyfin#750]
I took clone of the project and run build-jellyfin.ps1 using microsoft powersheel with admin rights. Process gets completed then when I go to server folder and run the executable file then it shows and error in browser "Could not find a part of the path 'jellyfin-web\src\index.html'". Here is the screenshot link of browser and also of terminal.

https://drive.google.com/file/d/1Ih-HECe_JNp5JRqnTokdsKJRQZbbx49V/view?usp=sharing
https://drive.google.com/file/d/1m9WfCSPX0tFEeadz6O5muoKhbwGLBbEW/view?usp=sharing

**Comment by ploughpuff** [comment]
I'm no expert, but have you initialised the sub-modules from git?
`git submodule update --init`

https://jellyfin.readthedocs.io/en/latest/user-docs/building/#building-jellyfin-from-source

**Comment by RazeLighter777** [comment]
This issue should be closed.

**Comment by JustAMan** [comment]
@LogicalPhallacy can you comment on the issue?
