### ISSUE TITLE
[Issue]: Change Error and Warning traces format

### ISSUE THREAD

**Issue by ngosang** [jellyfin/jellyfin#7500]
### Please describe your bug

I'm using Grafana + Loki as monitoring system. The Error and Warning traces from Jellyfin server are not parsed correctly because they don't follow the standard. Well, there is not universal standard but you traces are not detected. 

Current traces:
```
[09:42:06] [ERR] [59] MediaBrowser.Providers.Movies.MovieMetadataService: Error in ffprobe
[20:55:11] [WRN] [108] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS 192.168.1.92 error receiving data:
```

Proposed:

* Replace `[ERR] ` => `[ERROR] `
* Replace `[WRN] ` => `[WARN] `
 

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: Docker
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
This isnt a bug.
You can customize the log output by following the docs here: https://github.com/serilog/serilog/wiki/Formatting-Output

**Comment by ngosang** [comment]
@crobibero Thank you for the information.

I fixed the issue editing the file `logging.default.json` and replacing `{Level:u3}` with `{Level:u4}`

Could you make that value the default? It will fix central logging for other users and the traces are a bit more readable too.
