### ISSUE TITLE
[Issue]: Wrong docker tag for beta1

### ISSUE THREAD

**Issue by Extarys** [jellyfin/jellyfin#7501]
### Please describe your bug

On the release information page, it says the docker tag will be `10.8.0-alpha5`, but that is the tag for the last alpha 5.

The tag should probably be read as `10.8.0-beta1`

https://github.com/jellyfin/jellyfin/releases/tag/v10.8.0-beta1

### Jellyfin Version

Other

### Environment

```markdown
- OS:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TimGels** [comment]
The text in the [release ](https://github.com/jellyfin/jellyfin/releases/tag/v10.8.0-beta1)has been updated to `10.8.0-beta1` now.
