### ISSUE TITLE
[Issue]: Fedora 33 is EOL lets create packages for Fedora 34 and 35

### ISSUE THREAD

**Issue by yodatak** [jellyfin/jellyfin#7504]
### Please describe your bug

https://docs.fedoraproject.org/en-US/releases/eol/

Fedora 33 is EOL so lets create package to target Fedora 35

We should do like this : 

https://github.com/jellyfin/jellyfin-web/pull/2524/files

### Jellyfin Version

Other

### if other:

10.8

### Environment

```markdown
- OS: Fedora 
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mihawk90** [comment]
> to target Fedora 35

F36 is on the horizon so that should be added to the list to ideally build for all of them.

I don't know what you are building with currently (GitHub Actions? Docker? Local install?), but you might want to look into using [Mock](https://rpm-software-management.github.io/mock/). This is the intended way to build RPMs for Fedora (and EL) and is how both the official Fedora repos build it (on Koji), and what RPM Fusion and COPR use as well.

The spec may need some adjustments, but I haven't played around with it too much so far.

**Comment by SR-Lut3t1um** [comment]
The current build script can be easily changed to support Fedora 34, 35 and 36 (In theory there is another issue blocking fed36 support rn). However the Fedora 36 version works good on Fedora 35 yet.

**Comment by mihawk90** [comment]
The Makefile can already deal with any Fedora version you throw at it (well, any that has a Mock configuration file for it available in F33 since the Docker is on F33). Why it's not doing that I can't tell though since I don't know anything about Azure pipelines.

**Comment by mihawk90** [comment]
OK so I looked into this a bit and it seems that the [build in Docker](https://github.com/jellyfin/jellyfin/blob/master/deployment/Dockerfile.fedora.amd64) isn't actually using the Makefile (and therefore Mock) to build the actual RPMs, it's just using straight `rpmbuild` instead. `rpmbuild` always only builds for the currently running OS release version, so for a short-term fix just bumping this should be enough:

https://github.com/jellyfin/jellyfin/blob/5176f3ee89e6fcbe391a40a76f5b0ccfe30c8350/deployment/Dockerfile.fedora.amd64#L1

Long-term we can look into building multiple versions (always latest and latest-1), which is what Fedora themselves support.

I can get a PR ready for the short-term fix I think, shouldn't need any other changes.

**Comment by logic** [comment]
A quick update: Fedora 34 is now EOL as of today, and Jellyfin is built against libraries no longer shipped in Fedora 36, which makes it impossible to upgrade to F36:

```
Error:
 Problem: package jellyfin-server-10.7.7-1.fc33.x86_64 requires liblttng-ust.so.0()(64bit), but none of the providers can be installed
  - lttng-ust-2.12.0-4.fc34.x86_64 does not belong to a distupgrade repository
  - problem with installed package jellyfin-server-10.7.7-1.fc33.x86_64
```

**Comment by mihawk90** [comment]
We know, which is why #7471 exists in the first place.
The solution is the same that I posted in that issue. Build it yourself based on my PR, TLDR on how to do that is in that issue.
Alternatively you can run it in Docker or Podman if you have that set up already.
