### ISSUE TITLE
Cannot load 2 different xmltv files via URL

### ISSUE THREAD

**Issue by lolento** [jellyfin/jellyfin#751]
It seems I can only load 1 xmltv file for the Live Tv function vua URL method.  When I try to load 2 different URLs for 2 different tuners (hdhr and iptv), Jellyfin on recognizes the last URL.  If I switch one of the URL to a local file, then both xmltv works.

**Comment by win98se** [comment]
This problem still exists as of 4 February 2020, program version 10.4.3.

**Comment by dkanada** [comment]
@PrplHaz4 can you confirm that this issue still exists on the nightlies?

**Comment by cvium** [comment]
Seems ok to me. Make a new issue if it persists.
