### ISSUE TITLE
[Issue]: parse thumb tag error from existed nfo file

### ISSUE THREAD

**Issue by binpan0423** [jellyfin/jellyfin#7517]
### Please describe your bug

can't show the thumb image.
the thumb.jpg is existed in the path with the movie file.

nfo tag:
 ```
 <poster>poster.jpg</poster>
  <thumb>thumb.jpg</thumb>
  <fanart>fanart.jpg</fanart>
```

the code log this error:

```
if (!Uri.TryCreate(val, UriKind.Absolute, out var uri))
{
    Logger.LogError("Image location {Path} specified in nfo file for {ItemName} is not a valid URL or file path.", val, itemResult.Item.Name);
    return;
}
```
can we use UriKind.RelativeOrAbsolute or combine the full path in code to solve this?

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS:Window10 
- Virtualization:
- Clients:Browser
- Browser:Chrome
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
MediaBrowser.XbmcMetadata.Providers.MovieNfoProvider: Image location "thumb.jpg" specified in nfo file for "TestMovie" is not a valid URL or file path
```

### Please attach any screenshots here

![image](https://user-images.githubusercontent.com/6335877/160625767-dee09e1c-2abb-4d3f-a453-bae72f042fb1.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
I just tested scanning using a nfo file. Unfortunately the item's path isn't available when this function is called, so we can't combine the full path.

Using `UriKind.RelativeOrAbsolute` won't work either, as it won't know what the path is relative to.

In any case, those images should be picked up just by naming convention

**Comment by binpan0423** [comment]
> I just tested scanning using a nfo file. Unfortunately the item's path isn't available when this function is called, so we can't combine the full path.
> 
> Using `UriKind.RelativeOrAbsolute` won't work either, as it won't know what the path is relative to.
> 
> In any case, those images should be picked up just by naming convention

When the movie is a single one without -cd1 or -cd2. The images could be picked up.
But in the case above, the images can not be picked up, instead the image in exetrafanart got used as thumb.
What naming format  should I use when dealing with those movies. I need to use local nfos.

**Comment by Rebuilding127** [comment]
I have the same problem, is it Fixed ?

**Comment by dysl357085918** [comment]
Same issue.
