### ISSUE TITLE
AutoOrganize plugin should be included in the default package

### ISSUE THREAD

**Issue by lolento** [jellyfin/jellyfin#752]
Please include this plugin with the default Jellyfin package.

**Comment by sparky8251** [comment]
If we do this, it should be OFF by default. I have no desire for my server renaming my files. I name them before the server gets to scan them.

**Comment by hawken93** [comment]
Any particular reason why it can't be a plugin available in the plugin store when it arrives?

**Comment by hawken93** [comment]
https://github.com/jellyfin/jellyfin-plugin-autoorganize/pull/1 btw as of right now, we have working code and we'll be able to push it to plugin store really soon

**Comment by JustAMan** [comment]
@lolento 
> Please include this plugin with the default Jellyfin package.

Please provide some reasoning why it's needed there. I have no doubt it has to be available in the "plugin store", but bundled by default?.. I would argue we don't need _any_ plugins to be bundled by default.

**Comment by lolento** [comment]
Ok, I think it makes sense to be available in the plugin store.
