### ISSUE TITLE
[Issue]: Movies Series' Not Show in Alphabetical Order

### ISSUE THREAD

**Issue by RedSoxFan04** [jellyfin/jellyfin#7520]
### Please describe your bug

Movies from a series (i.e. Pirates of the Caribbean, Mummy, Matrix) are shown in alphabetical order instead of also having a chronological sub-order. For example,the Pirates of the Caribbean movies are arranged as such:
Dead Man's Chest (2006)
At World's End (2007)
The Curse of the Black Pearl (2003)

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: OpenMediavault 6
- Virtualization:None
- Clients:N/A
- Browser:Firefox
- FFmpeg Version:N/A
- Playback Method:N/A
- Hardware Acceleration:N/A
- Plugins:N/A
- Reverse Proxy:N/A
- Base URL:N/A
- Networking:N/A
- Storage:N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by whiteowl3** [comment]
Use the "Sort Title" function.  I use like "pirates caribbean 1" "pirates caribbean 2" etc
![image](https://user-images.githubusercontent.com/71030468/160899684-8d8294e7-fc2c-4e6d-820b-a97b35952da4.png)
