### ISSUE TITLE
[Issue]: [10.8.0] Related Movies Section only displays movies from the same genre in reverse alphabetical order

### ISSUE THREAD

**Issue by alcalear** [jellyfin/jellyfin#7524]
### Please describe your bug

After upgrading to 10.8.0 beta1 the "More Like This" section for related movies only displays films from the same genre, in reverse alphabetical order. For example, if you click on a movie with the genre 'comedy', the related movies will be an alphabetized list of all movies containing the comedy genre, starting with Z. This includes ones with multiple genres and those with only comedy as the genre. This makes it difficult to find new content because most of the time the list is almost identical between movies.

It's the same for all genres -- clicking on an action movie will provide a reverse alphabetized selection of all movies with 'action' in the genre field -- and completely disregards tags. It also looks like it does the same thing with TV Shows. 

Just a guess, but it looks like it might have something to do with PR #6867?

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Synology
- Virtualization: Docker
- Clients: Jellyfin Media Player
- Browser: Chrome 100
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by whiteowl3** [comment]
Are you sure this is not a feature request?  If the code is doing what it is supposed to then there is no bug.  What behavior would you prefer to see instead of what it is doing now?

**Comment by alcalear** [comment]
Is this expected behavior though? Maybe I misunderstood the new feature, but I interpreted it to mean that it would check for genre and include it as a factor in displaying related media. As it stands now, Jellyfin is only using genre to provide the movies and is displaying them with no variation in a set order. It also no longer includes similarly tagged media. 

If this is the correct behavior, I'll happily close the issue and create a new feature request, but I don't think it is. It's a pretty big change from 10.7.7 and earlier, and makes the section more of an extension of the genres tab. In my _very_ limited understanding of the code, I don't think this is what that change was intended to do.

For reference, this is the "More Like This" section from a movie with comedy as the genre. I was going to include pictures from four other unrelated movies with the same genre, but it was redundant as they were identical. 

![image](https://user-images.githubusercontent.com/102642201/160910632-c959b0ba-8779-4ecd-8dad-8fd5fb758f8d.png)

**Comment by BrunoPaiva513** [comment]
I agree with @alcalear. I believe this is a relevant bug due to the different way it was specified in the version update.

**Comment by AllenWalk** [comment]
I am experiencing this behavior as well. 
Every item in the library has the same set of More Like This items. 
The behavior in 10.7 was to include items that have the same tags, not by only genre (its too broad).
