### ISSUE TITLE
Request: Episode title TBA update on rescan

### ISSUE THREAD

**Issue by Akirainblack** [jellyfin/jellyfin#7530]
Just as a suggestion. When Jellyfin does a metadata refresh could it also attempt to update any episodes/series with TBA in the title of the episode?
e.g. Moon Knight S01:E01 TBA
is refreshed on a library rescan any time one is performed until it changes to.
Moon Knight S01:E01 The Goldfish Problem
At which point it stops being refreshed.

**Comment by kellcomnet2** [comment]
+1 jeopardy does his too where the contestants are often tba until post airtime. a better implementation might be a plugin that scans for configurable keywords to refresh metadata.

**Comment by SenorSmartyPants** [comment]
Check out my plug-in, it can do this exactly. 

Not updated for 10.8 yet

https://github.com/SenorSmartyPants/jellyfin-plugin-refreshsparse

**Comment by kellcomnet2** [comment]
> Check out my plug-in, it can do this exactly.
> 
> Not updated for 10.8 yet
> 
> https://github.com/SenorSmartyPants/jellyfin-plugin-refreshsparse

This looks like the exact solution I was thinking of, do you have an ETA ON A 10.8 update?

**Comment by SenorSmartyPants** [comment]
Probably this week.

**Comment by Akirainblack** [comment]
I can't seem to get it to compile with the supplied instructions.
I downloaded the linked .net and ran the command in the folder.
I just get:
Could not execute because the application was not found or a compatible .NET SDK is not installed.
Possible reasons for this include:
  * You intended to execute a .NET program:
      The application 'publish' does not exist.
  * You intended to execute a .NET SDK command:
      It was not possible to find any installed .NET SDKs.
      Install a .NET SDK from:
        https://aka.ms/dotnet-download

Any idea where I'm going wrong?

**Comment by SenorSmartyPants** [comment]
> > Check out my plug-in, it can do this exactly.
> > Not updated for 10.8 yet
> > https://github.com/SenorSmartyPants/jellyfin-plugin-refreshsparse
> 
> This looks like the exact solution I was thinking of, do you have an ETA ON A 10.8 update?

I updated my repo with 2 releases. One for 10.7 and one for 10.8. Each release has a dll for download as well.
