### ISSUE TITLE
[Issue]: OpenApi Definition for UpdateNamedConfiguration does not identify a Request Body

### ISSUE THREAD

**Issue by DMouse10462** [jellyfin/jellyfin#7536]
### Please describe your bug

A cursory reading of the Swashbuckle docs and the UpdateNamedConfiguration method itself in ConfigurationController.cs leads me to believe that this is caused by the manual processing of the request body in the method rather than defining it as a parameter with the [FromBody] annotation.

The method appears to be dynamically determining the type of the body based on the named configuration - for example, the "dlna" configuration casts the body to `DlnaOptions`. I'm not certain how this could be remedied in a way that's friendly to both OpenAPI and the dynamic behavior, but I have a couple ideas (possibly naive ones since Dotnet/C# isn't my specialty):

1. The half-baked method: parameterize it as some generic JSON-compatible type (string/base JsonObject-ish class) that OpenAPI can accept well enough to generate code that allows for a body to be passed in. This solves the problem but is terrible in the way of type safety. Not much worse than it is right now though.

2. The inheritance route: create something like `INamedConfiguration` that `DlnaOptions` and the other named configuration POCOs (is that a term like POJO is in Java?) can inherit from to use as the type for the paremeter; I'm not sure how happy this would make Swashbuckle. In the best case, it would create type definitions for all of the subclasses and we'd be set to use them as needed in clients. At its worst, it would create some garbage/blank definition for the spec and we'd have to either find a way to get Swashbuckle to attach type definitions for the subclasses or define them manually in the client implementations (not ideal).

It's also possible that both of my suggestions aren't the best route and there's an even better way to handle this. Suggestions are welcome - I'd like to try tackling this, but I'm a Groovy/Grails/Micronaut developer by day so it'll take me some time to get acquainted with the dev environment to try my approaches to see how they fit.

This issue affects all clients utilizing the OpenAPI output such as in-org projects like jellyfin-client-axios and consumers of such API clients like jellyfin-vue. I came across this issue while trying to implement DLNA settings in jellyfin-vue as a learning experience.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Any/All
- Virtualization: N/A
- Clients: OpenAPI Consumers
- Browser: N/A
- FFmpeg Version: N/A
- Playback Method: N/A
- Hardware Acceleration: N/A
- Plugins: None, but this may raise questions about how plugins define their types.
- Reverse Proxy: N/A
- Base URL: N/A
- Networking: N/A
- Storage: N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DMouse10462** [comment]
I've reconsidered a few points around option 2, mainly surrounding the idea of using an interface. The biggest problem is that you can't just define a parameter with an interface type because there's no constructor to deserialize into.

I've pretty much got an option 1 solution up and running, but I'm struggling to determine how I'd manually add the necessary configuration POCOs to the OpenAPI output. I'm still looking at inheritance to potentially solve this issue if nothing else.

**Comment by crobibero** [comment]
I think the solution is to implement  `oneOf`

https://github.com/domaindrivendev/Swashbuckle.AspNetCore#inheritance-and-polymorphism
