### ISSUE TITLE
[Issue]: Red Screen Unchangable, does not fix, and it seems to be an theme that does not change.

### ISSUE THREAD

**Issue by KoboDev** [jellyfin/jellyfin#7539]
### Please describe your bug

Red Screen Theme, except my theme is Black (Default), changing themes does not work.

### Jellyfin Version

Other

### if other:

Jellyfin-androidtv 0.13.2 release

### Environment

```markdown
- OS: Google Android TV TCL
- Virtualization: N/A
- Clients: Android TV
- Browser: Unknown
- FFmpeg Version: Unknown
- Playback Method: N/A
- Hardware Acceleration: ON
- Plugins: None
- Storage: 2tb (Separate Drives)
```

### Please attach any screenshots here

![image](https://user-images.githubusercontent.com/78581464/161360730-51cfef7e-0eec-42c0-b5ba-245a0387be2f.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by KoboDev** [comment]
Edit: Well this is embarrassing, but it seems to be seasonal theme.
But what seasonal theme is this?
Disabling fixes the issue, although you have to change to a different theme in order to get rid of it.

1. Disable Season themes
2. Switch from Dark Default or other theme to a different theme
3. Fixed.

But it never showed up like this before so again, what Seasonal Theme is this supposed to be?

**Comment by crobibero** [comment]
https://github.com/jellyfin/jellyfin-androidtv/issues/1592
