### ISSUE TITLE
Problem with movie versions

### ISSUE THREAD

**Issue by didaktiik** [jellyfin/jellyfin#7540]
### Describe the bug

Hello,

I been having this issue with versions ever since they had been introduced to Android TV beta versions (beta4?). As you can see bellow, my files follow the name convention required for movies versions.

- 'Home' version stands for LAN streaming (best quality), basically for home use in general
- 'Internet' version is a version made for remote streaming (bitrate is restricted to 4-8Mbit, Level 4.1, AAC & AC3 sound)

For the most part of my movie library, Android TV client (Nvidia Shield 2017,  Jellyfin client 0.13.0 is installed) chooses the 'Home' version at Home, but for some movies it insists on 'Internet' version not matter what I do. Not only the 'Internet' version is pre-seleted by default (in version selector) but it plays that version as well despite the 'Home' version plays fine, when chosen manually (direct play, no transcode or some compatibility issue).

Remote streaming (from a remote location, using different Nvidia Shield TV, but same client version) always chooses the 'Internet' version, most likely due the max bitrate settings set in the client (10Mbit/s).

Example of a movie (folder listing, so you can see file naming) where an incorrect version is selected by default:

```
[thatuser@manjaro-pc Home Alone 2: Lost in New York (1992)]$ pwd
/media/NAS414/Plex/Movies/Home Alone 2: Lost in New York (1992)
[thatuser@manjaro-pc Home Alone 2: Lost in New York (1992)]$ ls -la
total 29121192
drwxr-xr-x   2 nobody users        4096 Mar  8 15:15  .
drwxrwxrwx 126 nobody users        4096 Mar 17 22:06  ..
-rwxrw-rw-   1 nobody users       66222 Oct 13  2020 'Home Alone 2: Lost in New York (1992) - Home.cs.srt'
-rwxrwxrwx   1 nobody users       91334 Oct 13  2020 'Home Alone 2: Lost in New York (1992) - Home.en.srt'
-rwxrwxrwx   1 nobody users 25332523689 Dec 31 11:06 'Home Alone 2: Lost in New York (1992) - Home.mkv'
-rw-rw-rw-   1 nobody users       66222 Oct 13  2020 'Home Alone 2: Lost in New York (1992) - Internet.cs.srt'
-rw-rw-rw-   1 nobody users       91334 Oct 13  2020 'Home Alone 2: Lost in New York (1992) - Internet.en.srt'
-rw-r--r--   1 nobody users  4487228001 Feb 21 12:07 'Home Alone 2: Lost in New York (1992) - Internet.mp4'
```

### Application version

0.13.0

### Where did you install the app from?

Google Play

### Device information

Nvidia Shield 2017

### Android version

Android 11

### Jellyfin server version

10.7.7

**Comment by sourpatched** [comment]
10.8.0 has have a big transcoding update with heaps more options. I understand most won't try beta and that's okay.

**Comment by didaktiik** [comment]
I might explore server beta option then :-) Let me reconsider it. As far as 10.7.7 experience goes, I have been quite happy with it. Unless we start speaking about movie versions though. Still, we are not sure 100%, whether it is client or server related problem or some kind of underying problem elsewhere, right?

Thanks!

-- 
  
  ***@***.***

**Comment by mikewesten** [comment]
In general, the server isn't sending alphabetically ordered movie versions to the AndroidTV client. It works as expected on Jellyfin Media Player for desktop. However, AndroidTV orders them in descending order by _pixel width, specifically_.

Suppose you have 2 movie versions where one is 1918x1080 in resolution and the other is 1920x1080 in resolution. You can see where a problem will occur... unless by happy coincidence your 1920x1080 version was already filenamed alphabetically ahead of your 1918x1080 version.

**Comment by didaktiik** [comment]
Well, I got Aliens movie, 2 files

Aliens (1986) - Home.mkv
Aliens (1986) - Internet.mkv

Both are 1920 x 1036.

Still, Aliens (1986) - Internet.mkv is picked up as default, and played as default until I manually change it to Home beforehand.

If both have the same width, then the alphabetical approach should be applied, right?

**Comment by didaktiik** [comment]
Well, regardless the player (ExoPlayer or Vimu) some movies default to 2nd version. I have been unable to indentify the pattern. Vimu is my player of choice, ExoPlayer is quite incosistent and has problems with 5.1 FLAC (sometimes it plays without transcoding, the other time it transodes etc.).
