### ISSUE TITLE
[Issue]: 10.8.0 Beta 1:  Disabling Remote Connections disables Local Connections Too

### ISSUE THREAD

**Issue by texneus** [jellyfin/jellyfin#7547]
### Please describe your bug

10.8.0 Beta 1 Linux Standalone (non-MUSL) - Fresh install.  Started with the following script (not run as a service):

```
#!/bin/bash
JELLYFINDIR="/home/media/Downloads/Jellyfin"
FFMPEGDIR="/usr/share/jellyfin-ffmpeg"

"$JELLYFINDIR/jellyfin/jellyfin" \
  -d "$JELLYFINDIR/data" \
  -C "$JELLYFINDIR/cache" \
  -c "$JELLYFINDIR/config" \
  -l "$JELLYFINDIR/log" \
  --ffmpeg "$FFMPEGDIR/ffmpeg"
```

When initially accessed through a web browser at 127.0.0.1:8096 the setup wizard appears as expected.  When it gets to the option of remote access, the top box "Allow remote connections to this server" is checked by default.  I want to access this instance of jellyfin via localhost only, so I uncheck it:

![10 8 0 B1-1a](https://user-images.githubusercontent.com/23441049/161440943-5d46666d-18d2-49be-86ad-c8505a0a2b0b.jpg)

At the completion of the setup wizard, I cannot connect to Jellyfin.  The server is shown...

![10 8 0 B1-1b](https://user-images.githubusercontent.com/23441049/161441017-d600d0d7-6392-488f-bf65-3aeb63480cec.jpg)

...but clicking on it says it is unable to connect:

![10 8 0 B1-1c](https://user-images.githubusercontent.com/23441049/161441026-fea8d945-5391-4ba4-85e7-a65f7b0d0838.jpg)

Clearing out the config (etc) directories and starting over, but this time leaving "Allow remote connections to this server" checked allows it to be accessible to the local host:

![10 8 0 B1-2a](https://user-images.githubusercontent.com/23441049/161441074-06ca549a-1844-48f8-90cd-78144aee9750.jpg)

![10 8 0 B1-2b](https://user-images.githubusercontent.com/23441049/161441077-a843f667-7fce-46ce-a02c-cb648b1a3e7d.jpg)

This seems to be erroneous behavior as local access is necessary to continue to setup and configure Jellyfin.  I don't believe this option blocked all access in the past.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: MX Linux 19.4
- Virtualization: N/A
- Clients: localhost
- Browser: Firefox 91.7 ESR
- FFmpeg Version: jellyfin-ffmpeg_4.4.1-4-buster_amd64
- Playback Method: N/A
- Hardware Acceleration: N/A
- Plugins: none
- Reverse Proxy: none - direct access to 127.0.0.1
- Base URL: http://127.0.0.1:8096
- Networking: none - direct access to 127.0.0.1
- Storage: N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BulgarianHealer** [comment]
Same bug on windows.

**Comment by crobibero** [comment]
Fixed by https://github.com/jellyfin/jellyfin/pull/7549
