### ISSUE TITLE
improvement for hevc transcoding

### ISSUE THREAD

**Issue by xmu714** [jellyfin/jellyfin#755]
I am using a NAS with Intel G4560 CPU, it's graphics perfictly supports HEVC decoding /encoding，but when I was using jellyfin with option **quick sync** transcoding, ffmpeg failed,  According to log file:
```
[hevc_qsv @ 000002ad33eae540] Could not load the requested plugin '15dd936825ad475ea34e35f3f54217a6': specified object was not found (-9)
[hevc_qsv @ 000002ad33eae540] Error loading plugins
[hevc_qsv @ 000002ad33eae540] Error initializing an MFX session
Error while decoding stream #0:1: Function not implemented
```
I thought maybe fffmpeg parameters do not worked. So I compared ffmpeg official quick sync transcoding examples:
```
ffmpeg -hwaccel qsv -c:v hevc_qsv -i input.mp4 -vf 'vpp_qsv=framerate=60,scale_qsv=w=1920:h=1080' -c:v h264_qsv out.mp4
```
While jellyfin's:
```
ffmpeg.exe -c:v hevc_qsv  -i file:"input.mp4" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:1 -map 0:0 -map -0:s -codec:v:0 h264_qsv -preset 7 -look_ahead 0 -b:v 119554625 -maxrate 119554625 -bufsize 239109250 -profile:v high -level 4.1 -force_key_frames "expr:gte(t,n_forced*3)" -copyts -vsync -1 -codec:a:0 libmp3lame -ac 2 -ab 384000  -f segment -max_delay 5000000 -avoid_negative_ts disabled -start_at_zero -segment_time 3  -individual_header_trailer 0 -segment_format mpegts -segment_list_type m3u8 -segment_start_number 0 -segment_list "%AppData%\Roaming\jellyfin\transcoding-temp\xxx.m3u8" -y "AppData%\Roaming\jellyfin\transcoding-temp\xxx%d.ts"
```
So I tried to add **-hwaccel qsv** with the latest ffmpeg, and it worked successfully.
I think the parameter **-hwaccel qsv** is helpful, hope you can try it.

**Comment by BobOkisama** [comment]
I am looking for the same for nvenc and nvdec. Right now they are using Van's build which does not include vaapi or nvenc/dec support. They have plans to make their own build of ffmpeg in the future which include those options.
In the meantime https://github.com/jrottenberg/ffmpeg has a build with vaapi (no nvend/dec yet) that you can use, then just point JF to it and that should work.

**Comment by skyzonemc** [comment]
@BobOkisama Coiuld you please explain how to use jrottenbergs ffmpeg with jellyfin?
