### ISSUE TITLE
[Issue]: Server 10.7.6: tvdb is still being used for metadata, even with the tvdb plugin disabled on the server and in the library.

### ISSUE THREAD

**Issue by Overwatching** [jellyfin/jellyfin#7550]
### Please describe your bug

I have the tvdb plugin disabled.
I have a 'shows' library.
tvdb is included by default in every metadata section that it can pull metadata for in the library's `options.xml`.
The library does not have the option to disable tvdb as a source for any of the metadata sections.

Removing it from the relevant sections of the library's `options.xml` does not seem to actually remove it as a source for that type of metadata.  

Example:

- I created a new 'shows' library using an empty folder as the source.
- I configured the library to store metadata in Nfo and use the following metadata providers.
  - TheMovieDb
  - The Open Movie Database
  - Screen Grabber
- I created a folder named `Blade Runner - Black Lotus (2021)` in the empty library folder.

After a few minutes, the metadata for the series is located and downloaded into `tvshow.nfo` in the previously empty folder.
It contains...

    <?xml version="1.0" encoding="utf-8" standalone="yes"?>
    <tvshow>
      <plot>Los Angeles 2032. A young woman wakes up with no memories, and possessing deadly skills. The only clues to her mystery are a locked data device and a tattoo of a black lotus. Putting together the pieces, she must hunt down the people responsible for her brutal and bloody past to find the truth of her lost identity.</plot>
      <outline>Los Angeles 2032. A young woman wakes up with no memories, and possessing deadly skills. The only clues to her mystery are a locked data device and a tattoo of a black lotus. Putting together the pieces, she must hunt down the people responsible for her brutal and bloody past to find the truth of her lost identity.</outline>
      <lockdata>false</lockdata>
      <dateadded>2022-04-03 23:29:33</dateadded>
      <title>Blade Runner: Black Lotus</title>
      <originaltitle>Blade Runner: Black Lotus</originaltitle>
      <writer>Shinichiro Watanabe</writer>
      <writer>Takehiko Minato</writer>
      <writer>Philip K. Dick</writer>
      <credits>Shinichiro Watanabe</credits>
      <credits>Takehiko Minato</credits>
      <credits>Philip K. Dick</credits>
      <trailer>plugin://plugin.video.youtube/?action=play_video&amp;videoid=KlmnXPRJbGg</trailer>
      <trailer>plugin://plugin.video.youtube/?action=play_video&amp;videoid=eUu3lK_Z8VM</trailer>
      <trailer>plugin://plugin.video.youtube/?action=play_video&amp;videoid=nZhVHq8GjZI</trailer>
      <trailer>plugin://plugin.video.youtube/?action=play_video&amp;videoid=8V-KE7Jh35o</trailer>
      <trailer>plugin://plugin.video.youtube/?action=play_video&amp;videoid=ahNgjVcq4sA</trailer>
      <rating>6</rating>
      <year>2021</year>
      <mpaa>TV-14</mpaa>
      <imdb_id>tt9359796</imdb_id>
      <tmdbid>84553</tmdbid>
      <premiered>2021-11-13</premiered>
      <releasedate>2021-11-13</releasedate>
      <enddate>2022-02-05</enddate>
      <runtime>22</runtime>
      <genre>Animation</genre>
      <genre>Sci-Fi &amp; Fantasy</genre>
      <genre>Action &amp; Adventure</genre>
      <studio>Adult Swim</studio>
      <studio>Crunchyroll</studio>
      <tag>future</tag>
      <tag>artificial intelligence</tag>
      <tag>revenge</tag>
      <tag>thriller</tag>
      <tag>cyberpunk</tag>
      <tag>anime</tag>
      <tvdbid>356155</tvdbid>
      <art>
        <poster>L:\TestLibrary\Blade Runner - Black Lotus (2021)\folder.jpg</poster>
        <fanart>L:\TestLibrary\Blade Runner - Black Lotus (2021)\backdrop.jpg</fanart>
      </art>
      <actor>
        <name>Jessica Henwick</name>
        <role>Elle (voice)</role>
        <type>Actor</type>
        <sortorder>0</sortorder>
        <thumb>C:\Jellyfin\Server\metadata\People\J\Jessica Henwick\folder.jpg</thumb>
      </actor>
      <actor>
        <name>Will Yun Lee</name>
        <role>Joseph (voice)</role>
        <type>Actor</type>
        <sortorder>1</sortorder>
        <thumb>C:\Jellyfin\Server\metadata\People\W\Will Yun Lee\folder.jpg</thumb>
      </actor>
      <actor>
        <name>Wes Bentley</name>
        <role>Niander Wallace Jr. (voice)</role>
        <type>Actor</type>
        <sortorder>3</sortorder>
        <thumb>C:\Jellyfin\Server\metadata\People\W\Wes Bentley\folder.jpg</thumb>
      </actor>
      <actor>
        <name>Samira Wiley</name>
        <role>Officer Alani Davis (voice)</role>
        <type>Actor</type>
        <sortorder>5</sortorder>
        <thumb>C:\Jellyfin\Server\metadata\People\S\Samira Wiley\folder.jpg</thumb>
      </actor>
      <actor>
        <name>Andrew A. Kosove</name>
        <role>Executive Producer</role>
        <type>Producer</type>
      </actor>
      <actor>
        <name>Broderick Johnson</name>
        <role>Executive Producer</role>
        <type>Producer</type>
        <thumb>C:\Jellyfin\Server\metadata\People\B\Broderick Johnson\folder.jpg</thumb>
      </actor>
      <actor>
        <name>Laura Lancaster</name>
        <role>Executive Producer</role>
        <type>Producer</type>
      </actor>
      <actor>
        <name>Joseph Chou</name>
        <role>Executive Producer</role>
        <type>Producer</type>
        <thumb>C:\Jellyfin\Server\metadata\People\J\Joseph Chou\folder.jpg</thumb>
      </actor>
      <actor>
        <name>Scott Parish</name>
        <role>Producer</role>
        <type>Producer</type>
      </actor>
      <actor>
        <name>Ben Cook</name>
        <role>Producer</role>
        <type>Producer</type>
      </actor>
      <actor>
        <name>Eugene Son</name>
        <role>Producer</role>
        <type>Producer</type>
      </actor>
      <actor>
        <name>Al-Francis Cuenca</name>
        <role>Producer</role>
        <type>Producer</type>
      </actor>
      <actor>
        <name>Ken Duer</name>
        <role>Co-Producer</role>
        <type>Producer</type>
      </actor>
      <actor>
        <name>Hiroshi Yagishita</name>
        <role>Line Producer</role>
        <type>Producer</type>
      </actor>
      <actor>
        <name>Chen Yi Fei</name>
        <role>Line Producer</role>
        <type>Producer</type>
      </actor>
      <actor>
        <name>Makiko Nagano</name>
        <role>Associate Producer</role>
        <type>Producer</type>
      </actor>
      <actor>
        <name>Masaji Shiina</name>
        <role>Associate Producer</role>
        <type>Producer</type>
      </actor>
      <actor>
        <name>Max Nishi</name>
        <role>Associate Producer</role>
        <type>Producer</type>
      </actor>
      <actor>
        <name>Takenari Maeda</name>
        <role>Associate Producer</role>
        <type>Producer</type>
      </actor>
      <actor>
        <name>Ben Roberts</name>
        <role>Executive Producer</role>
        <type>Producer</type>
      </actor>
      <id>356155</id>
      <episodeguide>
        <url cache="356155.xml">http://www.thetvdb.com/api/1D62F2F90030C444/series/356155/all/en.zip</url>
      </episodeguide>
      <season>-1</season>
      <episode>-1</episode>
      <status>Ended</status>
    </tvshow>

It seems pretty clear that tvdb is still being queried.

Where are these lines coming from?

- `<tvdbid>356155</tvdbid>`
- `<id>356155</id>`
-     <episodeguide>
        <url cache="356155.xml">http://www.thetvdb.com/api/1D62F2F90030C444/series/356155/all/en.zip</url>
      </episodeguide>

I also don't see where the following lines are coming from.

- `<imdb_id>tt9359796</imdb_id>` I do not have imdb as a metadata source.
- `<trailer>....` The first trailer `KlmnXPRJbGg` is listed on the TMDb page. But none of the others are. Nor are they included on The Open Movie Database (that I can see at least)

Are settings not being honored or is there something else funky going on in the background?

### Jellyfin Version

10.7.z

### if other:

10.7.7

### Environment

```markdown
- OS: Windows
- Plugins:
  - AniDB - 3.0.0.0
  - AniList - 2.0.0.0
  - AudioDB - 10.7.6.0
  - Kitsu - 2.0.0.0
  - MusicBrainz - 10.7.6.0
  - OMDb - 10.7.6.0
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Overwatching** [comment]
Correction:

- Version should be 10.7.6 not 10.7.7

**Comment by cvium** [comment]
> It seems pretty clear that tvdb is still being queried.

It is very common for metadata providers to reference each other eg. Trakt will usually tell you the imdb, tmdb and tvdb ids etc. That does not mean the provider plugin is active.

> <trailer>.... The first trailer KlmnXPRJbGg is listed on the TMDb page. But none of the others are. Nor are they included on The Open Movie Database (that I can see at least)

They are all listed on the TMDb videos page.

I see no evidence of tvdb or any other deactivated providers being active.

**Comment by Overwatching** [comment]
> They are all listed on the TMDb videos page.

Ahh. The first one is the main trailer link, and the other 5 are in the media-subsection. Though only 3 are in the 'trailer' section. The other 3 are in the 'Opening Credits' section.

**Comment by cvium** [comment]
> The other 3 are in the 'Opening Credits' section.

Yeah, they don't actually say which type of video it is in the API response, so we don't filter them.

**Comment by Overwatching** [comment]
> Yeah, they don't actually say which type of video it is in the API response, so we don't filter them.

I started investigating this as a side issue while trying to figure out how to disable all the 'internet' stuff on the server. Like trailers.

I should have started out by firing up a sniffer and watching the traffic, but for some reason it seemed obvious.

Now I'm ACTUALLY going to sniff the traffic, because there probably are other things happening that I don't know about, or don't want.

**Comment by cvium** [comment]
This will fix the trailer type check https://github.com/jellyfin/jellyfin/pull/7551
