### ISSUE TITLE
[10.8.0][Issue]: Very relevant bug in the search system appeared in version 10.8.0

### ISSUE THREAD

**Issue by BrunoPaiva513** [jellyfin/jellyfin#7560]
### Please describe your bug

Hi!

The update to the Beta 8.0 version of Jellyfin generated a major bug in the search engine.

**Accented words (very common in other languages) are no longer detected in the search. For example:**
When searching in Portuguese for Cidadão, the movie Cidadão Kane (the famous Citizen Kane in the original title) is not found due to the existence of “ã” in the word.

Previous versions of Jellyfin normally found titles like this. But I think it's also worth mentioning that my only annoyance with this wonderful platform was the fact that searches differentiate accented letters. In languages where the use of accents is common, search engines always understand searches like “cidadÃo” and “cidAo” in the same way. I believe it would be relevant to also solve this old problem, which is related.

Thank you very much
Bruno

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 1337joe** [comment]
Other accent-related recent tickets:
#7450
#7484
