### ISSUE TITLE
[Issue]: Syncplay not synced up

### ISSUE THREAD

**Issue by dessalines** [jellyfin/jellyfin#7579]
### Please describe your bug

The join group and start / stop buttons work, but our streams quickly become offset by more than a few seconds. if we skip forward or backwards, or move to a specific time, then the problem becomes even worse, sometimes as much as a minute off.

We are both using the web player.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS:mac, android
- Virtualization:
- Clients: web, jellyfin android with web player
- Browser:
- FFmpeg Version:
- Playback Method: direct play
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Numerok** [comment]
Same, in time offset it says 1557ms and difference is ~10ms, tried to offset it back but although it says the diff is around zero they are clearly a couple or more seconds off sometimes even with compensation enabled in settings

**Comment by GaryLyon** [comment]
Having a same/similar issue. My config is as follows: Jellyfin 10.8.9 on a new Ubuntu 22.04.1 LTS install. Created three users (one admin, two regular), put behind a nginx reverse proxy (Does SSL encryption as well) following the document on the jellyfin site.

On WiFi/same network, devices will either be dead on or off by a few ms. I've only had it drift once. On cellular, they start off out of sync and only get worse.

Only listening to music as we have two phones on two vehicles trying to listen to the same thing. (We can hear the other so when it's off it just sounds bad.) Tried using Jellyfin as Spotify's group play option had issues as well with staying in sync/dropping groups.

**Comment by GaryLyon** [comment]
Is there anything from Logs or tracing that I can do to help this issue?

**Comment by dessalines** [comment]
I don't have a jellyfin test setup or anything, but you can easily replicate it with the behavior above.

**Comment by GaryLyon** [comment]
> I don't have a jellyfin test setup or anything, but you can easily replicate it with the behavior above.

Yup. That question was towards the Jellyfin team.

**Comment by sevenrats** [comment]
Hi, thanks for your report!  There are a few issues at hand here.  One, syncplay code is not owned by any developer right now and I don't think anybody is even sure how it works.  Two, syncplay is not designed to be any closer than this and code to bring it closer than a few milliseconds was already rejected.  There are no plans to make syncplay sync any closer than a few ms.
