### ISSUE TITLE
[Issue][10.7][10.8] Searching for images doesn't pull up any results

### ISSUE THREAD

**Issue by nifty360s** [jellyfin/jellyfin#7587]
Hello, on 10.7 and 10.8 I can't get the image search to work. Selecting the search icon just pulls up a blank screen. It's working fine when I roll back to 10.6.0, though. 
![image](https://user-images.githubusercontent.com/59210650/162815718-784ae890-0476-4051-9a2a-be1b96d29038.png)

![image](https://user-images.githubusercontent.com/59210650/162815928-f01bb2b9-f40a-4e40-9aeb-d15521c1d5eb.png)

**Comment by sourpatched** [comment]
Do you have any WebExtensions blocking this on the browser? Like an ad blocker?

**Comment by nifty360s** [comment]
> Do you have any WebExtensions blocking this on the browser? Like an ad blocker?

I hadn't thought of that, but no. No ad blockers enabled on my server or the machine I'm searching on. I did, however, just realize that it finds images for shows just fine. Seems to only be my movies library that's not working leading me to believe that this is an issue on my end and not a jellyfin issue.

**Comment by sourpatched** [comment]
I found TVDB wasn't loading because it blocked in the browser.

Have a look at your plugins, remove some old ones if you have any and check your setting for movies.

**Comment by nifty360s** [comment]
So I don't know what exactly fixed it, but I removed a bunch of plugins. I had like 4 versions of some of my plugins for some reason, maybe because I tried out the unstable docker image for like 1 hour and went back to stable? I also just created a new "movies2" library and nuked the old one. The new movies library is letting me search no problem. Thanks for your help @sourpatched you're the best.

**Comment by sourpatched** [comment]
You're welcome, glad it's fixed.

**Comment by crobibero** [comment]
Closing as fixed

**Comment by Bobybhangu** [comment]
Hi there, i am having the same issue. the images is coming up for shows but not for the movies. i would appreciate your help very much
