### ISSUE TITLE
[Issue]:  Jellyfin aur not target  1.8.0 beta1

### ISSUE THREAD

**Issue by ainz29** [jellyfin/jellyfin#7588]
### Please describe your bug

Following the steps described on the jellyfin page I try to use the instructions to install on archlinux(unstable)
git clone https://aur.archlinux.org/jellyfin-git.git
cd jellyfin-git
makepkg -yes

Everything works fine, except that it doesn't install version 1.8.0beta1 to test as the latest available, instead it installs 1.8.0 Alpha5 and it is not possible to force it to install the beta since the alpha is configured in the extraction from the repo.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS:Archlinux
- Virtualization:NO
- Clients:jellyfin 1.8.0 Alpha5
- Browser:Firefox
- FFmpeg Version:2.5.0
- Playback Method:
- Hardware Acceleration:YES
- Plugins:YES
- Reverse Proxy:NO
- Base URL:
- Networking:
- Storage:
```

### Please attach any screenshots here

![jellyfin update beta1 archlinux](https://user-images.githubusercontent.com/89356039/162870645-c9243b65-fbb1-4a3a-af06-6b66427211c8.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
The aur package is not maintained by Jellyfin. You would need to contact its maintainer.
