### ISSUE TITLE
Add hide/ignore for series/seasons/episodes, as an alternative to favorite.

### ISSUE THREAD

**Issue by SenorSmartyPants** [jellyfin/jellyfin#759]
**Is your feature request related to a problem? Please describe.**

Two (or more) users on the server. One user doesn't want to watch some series that are being added to JF. Would rather not even see those series in latest media, or Next up.

**Describe the solution you'd like**

Add another option to the favorite button. Normal/Favorite/Ignore(or Hide) would be the 3 states. Hidden items would never appear on the home page, or in Latest media or Next up. Would only appear in TV Show view with Hidden enabled as a filter.

**Describe alternatives you've considered**

I've considered creating separate directories to store series that the other user does not care about. Put all the series in there, add that directory to tv library. But then each user can not set what they can about. And it gets more difficult with more users.

**Additional context**

**Comment by sparky8251** [comment]
This will require database tweaks (favorites are stored in the userdisplayprefs iirc), so it won't happen until the migration to ef core is complete.

**Comment by SenorSmartyPants** [comment]
Heres what I imagine to unhide.

Go to TV Shows page. Open filter menu. Hidden will be a new option under "Filters". Check Hidden. Hidden items will now be displayed, allowing user to navigate to them and unhide them.
