### ISSUE TITLE
[Issue]: movie mismatches

### ISSUE THREAD

**Issue by drbuckingham** [jellyfin/jellyfin#7594]
### Please describe your bug

Version 10.7.7
Debian 11.3 / apt install
TMDB provider is configured as primary

Movies that were mismatched (exact directory names listed vs movie names mismatched to):
	"Lincoln (2012) [tmdbid-72976]" as "Abraham Lincoln: Vampire Hunter (2012)"
	"Darkness (2002) [tmdbid-11056]" as "Army of Darkness (1992)"
	"Old Fashioned (2014) [tmdbid-297462]" as "A Good Old Fashioned Orgy (2011)"
	"Justice (2017) [tmdbid-453807]" as "Justice League (2017)"
	"Max (2015) [tmdbid-272878]" as "Mad Max: Fury Road (2015)"
	"Mary (2019) [tmdbid-419706]" as "Mary Magdalene (2018)"
	"Gold (2016) [tmdbid-334524]" as "One Piece Film: GOLD (2016)"
	"Pet Semetary (2019) [tmdbid-157433]" as "Pet Semetary (1989)"
	"Robin Hood (1991) [tmdbid-30841]" as "Robin Hood: Prince of Thieves (1991)"
	"Robocop (2014) [tmdbid-97020]" as "Robocop (1987)"
	"Saw 3D (2010) [tmdbid-41439]" as "Saw IV (2007)"

It is obviously ignoring the provided tmdbid even though that should (in my opinion) take precedence when provided.  

Regardless, in the case of "Darkness (2002)" being mistaken for "Army of Darkness (1992)" shouldn't happen, nor "Mary (2019)" for "Mary Magdelene (2018)" when the directory names exactly match the title on TMDB.  The provided year is being ignored in the case of "Robocop (2014)" being mismatched to "Robocop (1987)".

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: Debian 11
- Virtualization: KVM/QEMU
- Clients: Web & Jellyfin Media Player
- Browser: Vivaldi
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shadowghost** [comment]
tmdbid parsing was added in #6912 and the ability to denote it with a hyphen in #7076 - both PRs are not present in 10.7.7

**Comment by crobibero** [comment]
Closing as fixed in 10.8

**Comment by SkyDiver7199** [comment]
It's still happening in 10.9.3

**Comment by Shadowghost** [comment]
Please open a new issue with more information.
