### ISSUE TITLE
[Issue]: "stable-pre" releases are not pushed to APT repo

### ISSUE THREAD

**Issue by zkhcohen** [jellyfin/jellyfin#7597]
### Please describe your bug

**I'm categorizing this as a development issue, not a feature request for the software. This is an issue with the half-implemented rollout of the new stable-pre category.**

Unlike the stable and unstable releases, the releases in the newly-added "stable-pre" category (https://repo.jellyfin.org/releases/server/ubuntu/versions/stable-pre/server/) are not being tagged/pushed to the APT repo. 

This prevents other projects, such as the extremely popular Linuxserver Docker image from being able to pull these packages - https://github.com/linuxserver/docker-jellyfin/issues/151

The CI pipeline (https://github.com/jellyfin/jellyfin/blob/master/.ci/azure-pipelines-package.yml) should be updated to build and publish to a stable-pre repo.

Because the release cadence is very slow for this project, I think it's important to make these stable prereleases more accessible.

### Jellyfin Version

Other

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joshuaboniface** [comment]
This is a fair point. However, as part of the 10.8.0 release (or, well, precisely, right after it) we're completely revamping our CI which has been in the works for some time. As such, we've made the explicit choice to leave stable-pre out of the repos for this release cycle.

Our hope with the updated CI is that it will make stable (and prerelease) releases much less cumbersome for us, automating away a lot of what is now grunt work and BASH scripts to GitHub Actions, and letting us up the cadence a fair bit. As part of that, there will be some ability to download pre-releases from Apt.

That said, I don't think there's actually a very good way to accomplish this. We're currently differentiating `stable` and `unstable` via separate "components" in Apt speak. Changing components requires the user to explicitly do so in their `sources.list` entries. So functionally, it would require lots of end-user work to switch to and then away from the pre-release component, and I'm not sure anyone is going to really do that.

Finally on the specific subject of Linuxserver Docker images - should they really be building pre-release releases of our software? It's pre-release - it's designed for finding bugs and testing, and adding a 3rd party into the mix who is, to be completely honest, just taking the `.deb` packages and installing them anyways, seems slightly (for lack of a better word) counterproductive.

**Comment by ArchemedIan** [comment]
just a suggestion https://www.reddit.com/r/jellyfin/comments/uqjvpd/comment/i9dtakr/?utm_source=share&utm_medium=web2x&context=3

**Comment by zkhcohen** [comment]
> just a suggestion https://www.reddit.com/r/jellyfin/comments/uqjvpd/comment/i9dtakr/?utm_source=share&utm_medium=web2x&context=3

It's not exactly related - auto-updating vs CI. You can use something like Watchtower to auto-update if you're using Docker. Also, nightly CI already exists. You can change your tag to that if you want it to get frequent updates.

The intention of publishing stable-pre to apt is to provide third-party devs the ability to easily pull and develop off of a certain pre-release state, instead of integrating all of the changes in the nightly releases. That drift can be pretty significant when you're trying to troubleshoot issues with features that are frequently updated, such as transcoding. It also enables users who have had significant bugs fixed in stable-pre releases to get those updates without having to use the jellyfin/jellyfin image. Linuxserver images are popular for a number of reasons, one of the biggest being the ability to change the UID/GID the container is run under. Note that both the official Jellyfin image and the Linuxserver one both have over 100M pulls on DockerHub. A vast number of users are being left behind as a result of the slow release cadence.

If their release cadence increases, then we no-longer have to worry about the **_massive_** number of changes between major and minor releases.
