### ISSUE TITLE
[Issue]: issue when playing video with embed subtitles on macOS and iPadOS

### ISSUE THREAD

**Issue by upstroke-version** [jellyfin/jellyfin#7599]
### Please describe your bug

I have issue when playing video with embed subtitles(not burned subtitles, just subtitles inside of video file container).
Regardless of subtitle preference on client, embedded subtitles are always displayed and can't be turned off. 
Because of that when I disable subtitle, there is one subtitle displayed on screen, and  when I enable subtitle, there are two
subtitles on screen.
When I tested futher to find the cause of the issue. I found out that subtitle, which is always displayed, follows macOS's subtitle style preference, and second subtitle, which I can control, follows the Jellyfin client's subtitle settings.

In a nutshell, I think Jellyfin has some issue with macOS's Safari and iOS's player.
I'm using macOS Safari web client and ios app on iPad, and they both have the same issue.
macOS and iOS's OS native subtitle feature just alway's show subtitle when it's embeded on video file.

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS:Raspberry pi os
- Virtualization:docker
- Clients:macOS(safari),iPadOS(app)
- Browser: Safari 15.5
- FFmpeg Version:
- Playback Method:Direct Play, Direct Stream, Transcode
- Hardware Acceleration:
- Plugins:none
- Reverse Proxy:none
- Base URL:
- Networking:
- Storage:local
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mnoah66** [comment]
Sounds like this is related to #https://github.com/jellyfin/jellyfin-expo/issues/98
