### ISSUE TITLE
Improved Genre Page

### ISSUE THREAD

**Issue by dannymichel** [jellyfin/jellyfin#7607]
on jellyfin-web: when you go to the root ``genres`` page you have a list of genres headings then a limited number of shows/movies in that genre. you have to scroll down that entire page of posters to see categories because what it should be is a genre listed with one poster you can click then it takes you to another page where everything in that genre. This should be a grid rather than a list.

on firestick: you have the same as above but its not a limited list. it shows you the same kind of list but it puts literally everything in that genre on one line each category in alphabetical order. you're supposed to be able to click one image/poster representing that category on both web and firestick and be presented with a new page with everything in that genre.

**Comment by nielsvanvelzen** [comment]
Requests for the server/web/overall go to features.jellyfin.org.
Requests for the Android TV app can be posted as issue in the jellyfin-androidtv repository.
