### ISSUE TITLE
[Issue]: Emby.Drawing.ImageProcessor Image conversion failed

### ISSUE THREAD

**Issue by nodje** [jellyfin/jellyfin#7616]
### Please describe your bug

Nothing visible in the user interface, but in the logs this error is recurrent:

```
[08:18:29] [ERR] [52] Emby.Drawing.ImageProcessor: Image conversion failed for /config/metadata/library/2a/2afc0ddcedc567261c952450ce4d3534/poster.jpe
System.NotImplementedException: The method or operation is not implemented.
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.ConvertImage(String inputPath, String outputPath)
   at Emby.Drawing.ImageProcessor.GetSupportedImage(String originalImagePath, DateTime dateModified)
```

This has been around since 10.7, still not fix in 10.8.0-beta2. 
I'm not sure how bad this is feature wise.

NB: it could be simply that the extension is not recognized, but then this file is generated by Jellyfin. So it could from another component not storing the file extension correctly.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
The jpe file was erroneously created b Jellyfin, so you can just delete it.

That bug has been fixed
