### ISSUE TITLE
Alternative audio tracks does not work

### ISSUE THREAD

**Issue by Maltahl** [jellyfin/jellyfin#762]
**Describe the bug**
When playing a video with multiple language tracks i am unable to get the video to play another audio track than the default of the media.

**To Reproduce**
1. Play a video with more than 1 audio track in another language for easier bug spotting
2. Try to change audio track while playing.
3. Try to change audio track before playing
4. Audio wont change regardless of the chosen audio track

**Expected behavior**
To switch audio track to the chosen audio track.

**System (please complete the following information):**
 - OS: Debian 9
 - Streaming Platform: Firefox, Jellyfin app, Chromium and Chromecast tested
 - Jellyfin Version: 10.1.0

**Additional context**
This works fine in Emby currently when switching between different audio tracks

**Comment by JustAMan** [comment]
@Maltahl do you have transcoding enabled in your settings? And what is the media properties you're trying to watch?

**Comment by RazeLighter777** [comment]
Tested and works on my machine with latest build. Can you post your ffmpeg logs?

**Comment by Maltahl** [comment]
i cant seem to reproduce the error any more after a day. 
I did not update server, clients or the media played. 
The log does not come out with anything conclusive. 
Properly a bad day or something random, sorry.

**Comment by rangeroob** [comment]
Describe the bug
When playing a video with multiple language tracks i am unable to get the video to play another audio track than the default of the media. Funny enough I am having the same problem that @Maltahl had but only on my android web browsers and not the desktop web browsers(though they direct stream instead of direct play, but that is another issue)

To Reproduce

    Play a video with more than 1 audio track in another language for easier bug spotting
    Try to change audio track while playing.
    Try to change audio track before playing
    Audio wont change regardless of the chosen audio track

Expected behavior
To switch audio track to the chosen audio track.

System (please complete the following information):

    OS: Debian 9 / Android 5.1
    Streaming Platform: Firefox 67 for Android & Chromium for Android
    Jellyfin Version: 10.3.3

**Comment by rangeroob** [comment]
Sorry for the delay, I solved my problem. Apparently Jellyfin didn't like a self signed cert. Once I changed that to a Let's Encrypt cert and it seemed to fix my issue with the audio not switching.
