### ISSUE TITLE
Titulos sumindo dos rescentes adicionados na tela inicial

### ISSUE THREAD

**Issue by damiao12345** [jellyfin/jellyfin#7620]
### Please describe your bug

Quando adiciona um titulo denomidado serie, os outros somem e fica so o ultimo adicionado

![01](https://user-images.githubusercontent.com/103868279/163894847-8a8ae72a-cfa8-4be1-a8d1-4e99de457133.png)
![02](https://user-images.githubusercontent.com/103868279/163894866-c18f983a-7ba8-4b86-9d2f-2879334548e9.png)
![03](https://user-images.githubusercontent.com/103868279/163894875-4a9beaac-d396-4bba-ad6e-f5e7ab970ca3.png)
.

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: todos
- Virtualization: windos e linux
- Clients: todos
- Browser:todos
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Please attach any screenshots here

![01](https://user-images.githubusercontent.com/103868279/163895021-4dc6693e-1a2d-453e-a960-e95d34b81854.png)
![02](https://user-images.githubusercontent.com/103868279/163895022-31c2c9a9-efce-4dc1-8006-4a5d57e812d2.png)
![03](https://user-images.githubusercontent.com/103868279/163895024-3c5e3dfb-2397-4375-8843-efcfe5e4b242.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alexbrooksglide** [comment]
Também estou tendo um problema parecido... Tenho uns 20 títulos de séries, mas mostra somente 5 na tela inicial...
