### ISSUE TITLE
"Keep Original Title"-option.

### ISSUE THREAD

**Issue by chilledhobbit** [jellyfin/jellyfin#765]
An option like this would simply add the opportunity to have your native language set as metadata language, but keep the original title of the movie.

For example, I need swedish as metadata language so all the movie info is in Swedish. But I want to keep the original movie title. (I hate Swedish titles on movies that are not from Sweden) 

I know that the original title is in the database, but without this option it will take som time to fix every movie manually. 

You can find exactly this option in Kodi's scraper.

**Comment by JustAMan** [comment]
Can you please provide some reasoning for that option? Examples maybe?

**Comment by hawken93** [comment]
https://www.filmweb.no/filmnytt/article1193157.ece

**Comment by chilledhobbit** [comment]
Haha wtf, Norway is even worse than Sweden! :P

**Comment by JustAMan** [comment]
Maybe we should add original title in a lesser font without any options? Might be a useful addition.

**Comment by hawken93** [comment]
In that case I'd argue I want an option to flip them so the translated title is in the smaller font :P

**Comment by chilledhobbit** [comment]
LeoVerto, that will be possible with this option. As it is now, I have to manually edit the foreign movie titles or the Swedish ones, depends on what Metadata language you use.

**Comment by sparky8251** [comment]
I watch anime, I only speak english. I do not like english titles for anime.

This isn't just a "I speak/read two languages" feature request. It'd be ideal if we can do it by library and by series. Maybe something with the metadata manager that is a toggle option?

**Comment by chilledhobbit** [comment]
Exactly! 

This is how it's look like In Kodi for example:

![tapatalk_1548946763643](https://user-images.githubusercontent.com/47156096/52062920-bb92c100-2571-11e9-86f3-e58b2b7e57b8.png)

**Comment by Matt07211** [comment]
Funny you should mention anime, the anime plugin has the option to pull in English,  transliteration and Full Japanese (as Hawken has said above), but it's an all of nothing approach, the whole library has to be the option you have choosen (I personally prefer a mix and match between the the transliteration or the English title, as I remember some show names as the former or latter) and then you have to force a metadata reset.

So I'm personally in support of having the option to display both versions of a show/movies name underneath each other. As well as a per show toggle so you can manually switch the options per show if you like.

So the db will have to hold both (or multiple versions) of a shows name then...

**Comment by sparky8251** [comment]
Which means this is now a post EF Core Migration issue.

**Comment by JustAMan** [comment]
Re-labelling as `feature`.
