### ISSUE TITLE
BUG: Ubuntu 22.04 LTS is not supported (libssl1.1)

### ISSUE THREAD

**Issue by michael9dk** [jellyfin/jellyfin#7650]
Ubuntu 22.04 has upgraded libssl to v3.0.
Jellyfin depends on libssl1.1 which isnt available. 

More details here:
https://www.reddit.com/r/jellyfin/comments/ua0d30/unable_to_install_jellyfin_from_the_ubuntu_repo/

https://www.reddit.com/r/jellyfin/comments/u8y3pj/jellyfin_fails_to_start_with_ubuntu_2204_lts/

**Comment by cvium** [comment]
You're 6 hours too late... https://github.com/jellyfin/jellyfin/pull/7648
