### ISSUE TITLE
[Bug] Grabs Video From Different, Unpermitted Library As A Movie Version

### ISSUE THREAD

**Issue by seniorm0ment** [jellyfin/jellyfin#7653]
Please describe your bug

I have multiple libraries, to describe this bug I will present two.
"Movies", "Videos". As well as 2 users "User 1"", "User 2".
User 1 has access to only Movies.

The Movies library has it's own path "media/Movies".
The Videos library has it's own path "media/Videos".
There are no conflicting files with these two libraries, all the files are in their own folders.

Recently as User 1, upon clicking on a movie on Andorid TV (replicated on browser, and Android), it played a video from the Videos library with a similar title. I was very confused because User 1 SHOULD not have access to this library.

I realized, that for some reason, Jellyfin grabbed the video from the Videos library, and added it as a separate version that you can select from to that Movie for User 1.
**This is a major permissions bug, the video should not touch that library, or that user.** 

Jellyfin Version
10.7.7

Environment

- OS: Win 10 Home
- Virtualization: None
- Clients: Browser, Android TV, Android
- Browser: Librewolf, Firefox
- FFmpeg Version: Latest
- Playback Method: N/A
- Hardware Acceleration: N/A
- Plugins: Default
- Reverse Proxy: N/A
- Base URL: 
- Networking: Ethernet/WiFi
- Storage: iSCSI Windows

Jellyfin logs
No response

FFmpeg logs
No response

Please attach any browser or client logs here
No response

Please attach any screenshots here
No response

Code of Conduct
- [x]   I agree to follow this project's Code of Conduct

**Comment by seniorm0ment** [comment]
Relevant

**Comment by seniorm0ment** [comment]
Can confirm this issue still exists.
Any news on it?

**Comment by seniorm0ment** [comment]
Relevant

**Comment by seniorm0ment** [comment]
Relevant

**Comment by crobibero** [comment]
If you are still experiencing this issue you will need to provide more information, I cannot replicate this issue. 

I have Harry Potter in 1080p and 4k, in separate paths and libraries, and they are not listed together.
