### ISSUE TITLE
[Issue]: TMDb blocked in Russia

### ISSUE THREAD

**Issue by QuaiGoner** [jellyfin/jellyfin#7655]
### Please describe your bug

For reference: 
- https://www.themoviedb.org/talk/6036ee9d4fd141003eae8534?page=4
- https://www.themoviedb.org/talk/6036ee9d4fd141003eae8534?page=2

TL:DR

Russian gov. blocked some IPs from TMDbs API pool, issue can be semi-resolved if you put non-blocked IP in hosts file, but i tried it and ive got weird results where some movies scraped as complete other in Images, but have correct actors.
Can we looked at that issue from Jellyfin standpoint and provide some kind of a workaround?

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: Ubuntu 20.04
- Virtualization: Docker container
- Clients: Android/Web UI
- Browser: Chrome v 100.*
- FFmpeg Version: Not applicable
- Playback Method: Not applicable
- Hardware Acceleration: Not applicable
- Plugins: Not applicable
- Reverse Proxy: Not applicable
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
This is not a Jellyfin bug.
