### ISSUE TITLE
[Bug]: Permissions to Library 

### ISSUE THREAD

**Issue by black-dagon** [jellyfin/jellyfin#7669]
### Please describe your bug

First permission bug:

Users with Library restrictions are allowed to access library items using direct link.

Steps to reproduce:
1. Create library and add movies to it
2. Create test user and restrict user to above mentioned library
3. Use admin user / full access user and go to above mentioned library, click on movie and get URL
4. As test user login into jellyfin using web browser and copy paste URL from above step
5. Witness the movie to which user should not have access (also includes playing the movie)

Second permission bug:

If user who has access to Library gives user who doesnt have access direct link to Library, the user without access will be able to:
  - Access the Library page, but wont be able to see anything in Movies, Trailers, Favourites, Collections tab
  - Access the Library page, and access movies through Suggestions tab
  - Access the Library page, and see genres in Genre tab, but without movies

Steps to reproduce:
1. Create library and add movies to it
2. Create test user and restrict user to above mentioned library
3. Use admin user / full access user and go to above mentioned library and get URL
4. As test user login into jellyfin using web browser and copy paste URL from above step
5. Witness infinite loading:

![image](https://user-images.githubusercontent.com/6535127/165553408-66c71837-553e-4d34-ad9c-062698f1e912.png)

6. As test user click on suggestion tab and witness suggestions coming from restricted library:

![image](https://user-images.githubusercontent.com/6535127/165553572-000fdcc4-204e-413f-bb92-77ba7e81f50a.png)

7. As test user click on genres tab and witness genres (but NOT actual movie info) coming from restricted library:

![image](https://user-images.githubusercontent.com/6535127/165553693-760d174c-f67c-404d-ab71-2a8cdca43894.png)

8. As test user click on sidenav and witness restricted library appearing in navbar:

![image](https://user-images.githubusercontent.com/6535127/165553870-fa9f2f6b-02b5-4a77-a8dc-df595d182a3a.png)

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: RHEL 8
- Virtualization: Docker / ghcr.io/linuxserver/jellyfin
- Clients: Browser
- Browser: Firefox, possibly others as well
- FFmpeg Version: n/a
- Playback Method: Default web player
- Hardware Acceleration: Enabled but not used
- Plugins: AniDb, AniList, AudioDB, MusicBrainz, Omdb metadata plugins
- Reverse Proxy: Nginx with caching
- Base URL: jellyfin.mydomain.lan
- Networking: Docker bridge with reverse proxy
- Storage: local
```

### Jellyfin logs

```shell
When accessing movie directly through link:
- Nothing in logs

When accessing movie library directly through link:
- jellyfin    | [17:23:27] [WRN] [143] Jellyfin.Api.Controllers.ItemsController: test is not permitted to access Library Movies.
```

### Please attach any browser or client logs here

When accessing movie library directly:

![image](https://user-images.githubusercontent.com/6535127/165554430-5817cf99-1790-4c49-bb0d-a1d8cd2f0f9a.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
Already captured as a part of https://github.com/jellyfin/jellyfin/issues/5415
