### ISSUE TITLE
[Issue]:  Unable to read symlink file size causes the program to fail

### ISSUE THREAD

**Issue by chowder3907** [jellyfin/jellyfin#7674]
### Please describe your bug

I am running jellyfin beta 2 using the .deb files on debian 11 x86_64. My library has the media files symlinked from another directory. I cannot play anything as I get this error in the log

```
[2022-04-28 00:23:51.433 -04:00] [ERR] Reading the file size of the symlink at "/home/media/HDD/movies/The Batman (2022)/The Batman (2022) 1080p.mp4" failed. Marking the file as not existing.
System.IO.FileNotFoundException: Could not find file '/home/media/HDD/movies/The Batman (2022)/The Batman (2022) 1080p.mp4'.
```
The player (I am using the web server through brave) gives me the error "This client isn't compatible with the media and the server isn't sending a compatible media format."
[

I have hardware acceleration disabled. 
[jellyfin20220428.log](https://github.com/jellyfin/jellyfin/files/8579610/jellyfin20220428.log)
FFmpeg.Transcode-2022-04-28_01-04-34_5f9267cf4d91b38bd7c05cb8972d2054_c106125d.log](https://github.com/jellyfin/jellyfin/files/8579627/FFmpeg.Transcode-2022-04-28_01-04-34_5f9267cf4d91b38bd7c05cb8972d2054_c106125d.log)

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS:Debian 11 x86_64
- Virtualization: none
- Clients:Browser
- Browser:Brave 1.37.116
- FFmpeg Version: jellyfin 4.4.1-4
- Playback Method:N/A
- Hardware Acceleration:none
- Plugins:none
- Reverse Proxy:none
- Base URL:none
- Networking:host
- Storage:local, symlinked to a docker container
```

### Jellyfin logs

```shell
FFmpeg.Transcode-2022-04-28_01-04-34_5f9267cf4d91b38bd7c05cb8972d2054_c106125d.log]
```

### FFmpeg logs

```shell
(https://github.com/jellyfin/jellyfin/files/8579627/FFmpeg.Transcode-2022-04-28_01-04-34_5f9267cf4d91b38bd7c05cb8972d2054_c106125d.log)
```

### Please attach any screenshots here

![image](https://user-images.githubusercontent.com/63274355/165680134-3e555425-bb28-4c92-ae50-77320041709c.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cvium** [comment]
FileNotFound. Your file either doesn't exist or you're using symlinks and the symlink is what is called "dangling" ie. it points to a file that does not exist.

A file not found error can also mean jellyfin doesn't have permissions to access the file in some situations. Either way, this is not a Jellyfin specific issue.
