### ISSUE TITLE
[Issue]: Ubuntu 22.04 Jammy repo config broken

### ISSUE THREAD

**Issue by ruhrscholz** [jellyfin/jellyfin#7677]
### Please describe your bug

Hello, I just added the Jellyfin repo to a stock Ubuntu 22.04 LTS server installation. The repo stinng is `deb [arch=amd64] https://repo.jellyfin.org/ubuntu jammy main`.

When actually trying to install jellyfin, after updating the package caches of course, I get:

```
user@jellyfin:~$ sudo apt install jellyfin
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 jellyfin : Depends: jellyfin-server but it is not installable
            Depends: jellyfin-web but it is not installable
E: Unable to correct problems, you have held broken packages.
```

Trying to install either jellyfin-server or jellyfin-web manually yields no installation candidates:

```
user@jellyfin:~$ sudo apt install jellyfin-server
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package jellyfin-server is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'jellyfin-server' has no installation candidate
```
Grepping the local apt cache returns only two packages inside the jellyfin repo: jellyfin itself (which requires jellyfin-{web,server}) and jellyfin-ffmpeg.

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: Ubuntu 22.04 LTS
- Virtualization: KVM
- Clients: N/A
- Browser: N/A
- FFmpeg Version: N/A
- Playback Method: N/A
- Hardware Acceleration: None
- Plugins: N/A
- Reverse Proxy: Nginx
- Base URL: none
- Networking: Bridge
- Storage: NFS
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
Ubuntu 22.04 is supported as of 10.8.

**Comment by ruhrscholz** [comment]
If this is the case, then the official website seems to be incorrect, as it states Ubuntu Jammy to be supported for stable releases if I understand the versioning correctly.
