### ISSUE TITLE
This client isn't compatible with the media and the server isn't sending a compatible media format.

### ISSUE THREAD

**Issue by TheHellSite** [jellyfin/jellyfin#7678]
**Describe The Bug**
Since a few days every playback fails with the error in the title.
The platform (android app, browser, fire tv, ...) doesn't matter, it stopped working on all of them.

**Additional Context**
The only thing I did was a full system upgrade of my Arch Linux LXC.
What is strange though is that the logs don't indicate any playback error as far as I can tell.
All permissions on the render device and media/transcode/jellyfin directories are also set correctly.

Reverting to a backup before the system update fixes the playback issues.
But again the logs on the updated system don't indicate any major error.

The only thing that could be causing the issues is this line:
````
[2022-04-28 23:09:16.973 +02:00] [WRN] [10] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "https://vod.mydomain.com/videos/c7456c57-4437-6c1f-74ed-3640b2882148/live.m3u8?DeviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6OTIuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC85Mi4wfDE2MzE4MTAzNzI2OTY1&MediaSourceId=c7456c5744376c1f74ed3640b2882148&VideoCodec=h264&AudioCodec=aac,mp3&VideoBitrate=29808000&AudioBitrate=192000&PlaySessionId=e778a366fa9f4e79a881cc5f78a7a472&api_key=5263b3a6e4af449fa7b39ab52a3f0bb9&TranscodingMaxAudioChannels=6&RequireAvc=false&Tag=ff80d766b8bc650980a0394082065591&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51&h264-deinterlace=true&TranscodeReasons=ContainerNotSupported,ContainerBitrateExceedsLimit&allowVideoStreamCopy=false&allowAudioStreamCopy=false&allowAudioStreamCopy=false" to "REMOTE_CLIENT_IP" in 0:00:06.391838 with Status Code 200
````

Also everything mentioned here didn't fix the issue. https://github.com/jellyfin/jellyfin-web/discussions/3410#discussioncomment-2139179

**Media Info of the file**
The media format (codec, ...) doesn't matter. The issue arises for every media file in my library.
It has been working fine before the system update.

**Logs**
[jellyfin.txt](https://github.com/jellyfin/jellyfin-web/files/8587012/jellyfin.txt)

**FFmpeg Logs**
[FFmpeg.Transcode-2022-04-28_23-09-00_c7456c5744376c1f74ed3640b2882148_44e50cb1.log](https://github.com/jellyfin/jellyfin-web/files/8587009/FFmpeg.Transcode-2022-04-28_23-09-00_c7456c5744376c1f74ed3640b2882148_44e50cb1.log)
[FFmpeg.Transcode-2022-04-28_23-09-06_c7456c5744376c1f74ed3640b2882148_e977a96e.log](https://github.com/jellyfin/jellyfin-web/files/8587010/FFmpeg.Transcode-2022-04-28_23-09-06_c7456c5744376c1f74ed3640b2882148_e977a96e.log)
[FFmpeg.Transcode-2022-04-28_23-09-10_c7456c5744376c1f74ed3640b2882148_55c89105.log](https://github.com/jellyfin/jellyfin-web/files/8587011/FFmpeg.Transcode-2022-04-28_23-09-10_c7456c5744376c1f74ed3640b2882148_55c89105.log)

**Stats for Nerds Screenshots**
N/A

**Screenshots**
![error](https://user-images.githubusercontent.com/34900685/165856817-bcd2db9c-832f-4d10-a87b-482aa02892b5.png)

**Server System (please complete the following information):**
 - OS: Arch Linux LXC (latest stable updates) on Proxmox 7.x (latest stable updates)
 - Jellyfin Version: 10.7.7
 - Hardware settings & device: AMD Ryzen 3 PRO 4350G with Radeon Graphics
 - Reverse proxy: HAProxy
 - Other hardware notes: The media folder is mounted on the PVE host using a CIFS share and then integrated in the LXC using a read only bind mount. The transcodes folder is using an old SSD (still good and working) which is mounted on the PVE host and then integrated in the LXC using a read/write bind mount.
 
**Client System (please complete the following information):**
 - Device: not relevant
 - OS: Windows, Android, ...
 - Client: Web/Browser, Android, Android TV, ...
 - Browser (if Web client): Firefox, Chrome, Safari, Edge, ...
 - Client and Browser Version: latest stable

**Comment by Gygun** [comment]
Same error here, but in my case it works fine in 10.7, but fails in every 10.8 pre release. All with default settings (fresh install). No hardware acceleration.

**Comment by maltejur** [comment]
Possibly because of ffmpeg v5, see https://github.com/jellyfin/jellyfin/issues/7355. Does your log contain something along the lines of `The JSON value could not be converted to System.Int32`?

**Comment by Gygun** [comment]
This error is no longer present in Beta 3 (for me)! I'm so glad it work now!
I tried both ffmpeg 4.4 and 5, but there was no way to make it work with either version. I don't really know what it was, but both beta 1 and 2 didn't work at all.

**Comment by cavedog8** [comment]
So just to add here.

The error is jellyfin failing to transcode the file.

Go to Dashboard > Playback and look for FFmpeg path:

the path is already there.  Click on the magnifying glass and select the same ffmpeg path that was displayed there.  Save. 

For some reason Jellyfin is failing to use ffmpeg even though the path is correct. Reselecting it and saving fixes the issue.

**Comment by Gygun** [comment]
Update from new versions:
Stable 10.8.0 works just fine but without hard acc.
Using nvenc, I only made it work with ffmpeg 4.4.1. If I use the default 5.0.1 I got that error again.
Same with 10.8.1. Downgrade ffmpeg is the way.

**Comment by friki67** [comment]
> Downgrade ffmpeg is the way.
Noob question: how to downgrade ffmpeg in the docker container? Is there an "easy" way?

**Comment by Rykimaruh** [comment]
> So just to add here.
> 
> The error is jellyfin failing to transcode the file.
> 
> Go to Dashboard > Playback and look for FFmpeg path:
> 
> the path is already there. Click on the magnifying glass and select the same ffmpeg path that was displayed there. Save.
> 
> For some reason Jellyfin is failing to use ffmpeg even though the path is correct. Reselecting it and saving fixes the issue. As per the pic below it's already there and the path is valid but it wants you to reselect it and click save then suddenly all the media works without any issues.
> 
> Took me log to figure it out and played with many versions right up to the very latest unstable.
> 
> https://i.snipboard.io/fXKc9r.jpg

For some reason, I don't see it in the list any longer.

**Comment by Bond-009** [comment]
This should be fixed in the latest release (#7355) if not, please open an issue that follows the template

**Comment by DesertCookie** [comment]
Hoping for the latest update to fix this as it does happen with 10.8 for me too, every time I have Quick Sync enabled for transcoding and `/dev/dri` passed through.

**Comment by KOYK** [comment]
Please forgive me for posting in a closed issue, but any idea where I can find ffmpeg 4.4.1 for windows 7?
Am looking for it for 2 hours now, and I can only find its source code.

**Comment by s-kaczmarek** [comment]
Reporting the same problem on docker version 10.8.5 It did work fine on 10.6.4. Fix with pointing FFmpeg path does not work for me.

**Comment by Rolli700** [comment]
> So just to add here.
> 
> The error is jellyfin failing to transcode the file.
> 
> Go to Dashboard > Playback and look for FFmpeg path:
> 
> the path is already there. Click on the magnifying glass and select the same ffmpeg path that was displayed there. Save.
> 
> For some reason Jellyfin is failing to use ffmpeg even though the path is correct. Reselecting it and saving fixes the issue. As per the pic below it's already there and the path is valid but it wants you to reselect it and click save then suddenly all the media works without any issues.
> 
> Took me log to figure it out and played with many versions right up to the very latest unstable.
> 
> https://i.snipboard.io/fXKc9r.jpg

This did the trick for me! Thx!

**Comment by nathanfranke** [comment]
Using [docker](https://hub.docker.com/r/jellyfin/jellyfin/) and re-setting the FFmpeg path as suggested earlier didn't initially work for me, but doing that plus a restart (`docker-compose down`, `docker-compose up -d`) did fix the issue. In any case, I think this issue should be re-opened. If setting of the ffmpeg path again is making it work, whatever that did should be automatically done on start-up.

**Comment by realYUMYULACK** [comment]
I don't know if this will help anyone here but it worked for me:

I had to disable hardware decoding for me at the particular point (H264 in my case).

After that, the file played normally.

**Comment by NHAS** [comment]
I have tried all the suggestions in this thread, Im using the docker version with no hardware acceleration and it does not work.

**Comment by d3lm4n** [comment]
Like NHA, I also tried every solution and nothing worked.

Synology 918+
DSM 7.1.1-42962
Docker 20.10.3-1308
Jellyfin 10.8.9

**Comment by sejka** [comment]
Weirdly, the thing that worked for me was turning transcoding off, then it started working.
![image](https://user-images.githubusercontent.com/2963600/216573612-4ec86635-a92f-4048-bc5b-5b83e6bf9084.png)
![image](https://user-images.githubusercontent.com/2963600/216573764-47a95a76-16de-4488-b7e5-02a37aa6d89b.png)

**Comment by stresskiller** [comment]
Running in to the same problem 

Synology 918+ 8GB memory
DSM:  7.1.1-42962 Update 4
Docker:  20.10.3-1308
Jellyfin :  10.8.9

same movies run without issues on other platforms like plex , jellyfin just keeps saying that client isn't comaptible

**Comment by NHAS** [comment]
I have found moving from NGINX to Caddy has resolved my issues. The default nginx configuration didnt work for me for some reason

**Comment by Yougraj** [comment]
Same thing is happening on my server please someone solve it.

**Comment by ManuelFte** [comment]
I just faced this same problem on my Manjaro after upgrading from kernel 5.10 to 6.1. I'm using Jellyfin 10.8.10 on Docker  23.0.4.

The error was persisting after reboots, but it got fixed after I disabled the systemd Docker service, rebooted, and started the service again.

**Comment by m4dh0rs3** [comment]
If you're here for getting the "Playback Error", this could be any kind of `ffmpeg` error. If the logs include the `ffmpeg` command run that failed, try running it yourself. It helped me realize, that I hadn't connected my harddrive.

So this can also be user error.
