### ISSUE TITLE
[Issue]: many inotify watches created even with automatic scanning disabled

### ISSUE THREAD

**Issue by srd424** [jellyfin/jellyfin#7684]
### Please describe your bug

I disabled automatic scanning of media directories on my libraries as I do not need this feature and wanted to keep the number if inotify watches down on my lightweight server. However a large number of watches are still created:

```
root@nuc:~# pid=$(pgrep jellyfin)
root@nuc:~# ls -l /proc/$pid/fd | grep inotify
lr-x------ 1 steved steved 64 Apr 30 15:18 220 -> anon_inode:inotify
lr-x------ 1 steved steved 64 Apr 30 15:19 65 -> anon_inode:inotify
root@nuc:~# wc -l /proc/$pid/fdinfo/{220,65}
843 /proc/2494612/fdinfo/220
6603 /proc/2494612/fdinfo/65
7446 total
```
These all seem to be various files on the metadata partition:
```
root@nuc:~# head -n 5 /proc/$pid/fdinfo/{220,65} | grep ^inotify
inotify wd:348 ino:a0062 sdev:fd00051 mask:3c6 ignored_mask:0 fhandle-bytes:8 fhandle-type:1 f_handle:62000a00cf8a3ffd
inotify wd:347 ino:a0063 sdev:fd00051 mask:3c6 ignored_mask:0 fhandle-bytes:8 fhandle-type:1 f_handle:63000a008db2dea4
inotify wd:19c8 ino:7f801 sdev:fd00051 mask:3c6 ignored_mask:0 fhandle-bytes:8 fhandle-type:1 f_handle:01f80700c5448d68
inotify wd:19c7 ino:bf401 sdev:fd00051 mask:3c6 ignored_mask:0 fhandle-bytes:8 fhandle-type:1 f_handle:01f40b0086983480
root@nuc:~# stat /vol/jfin-meta/ | grep Device
Device: fd51h/64849d    Inode: 2           Links: 8
root@nuc:~# find /vol/jfin-meta/ -inum $(printf "%d" 0xbf401)
/vol/jfin-meta/custom-services.d
root@nuc:~# find /vol/jfin-meta/ -inum $(printf "%d" 0x7f801)
/vol/jfin-meta/log
root@nuc:~# find /vol/jfin-meta/ -inum $(printf "%d" 0xa0062)
/vol/jfin-meta/data/metadata/library/f8/f897016206b9c5cc3fa1c494f120aee4
```

60bece614aeb05558741b81a624f37ce2921c027 seems to add a check to avoid this happening, but it's clearly not working, unless this behaviour is by design?

### Jellyfin Version

Other

### if other:

Linuxserver.io version:- 20220428.3-unstable-ls911 Build-date:- 2022-04-28T16:00:16-05:00

### Environment

```markdown
- OS: Ubuntu 20.04, 22.04
- Virtualization: systemd-nspawn, podman
- Clients: Fire TV
- Browser: Chrome 101
- FFmpeg Version: n/a
- Playback Method: n/a
- Hardware Acceleration: none
- Plugins: standard
- Reverse Proxy: none
- Base URL: http://nuc-ocihost.lan:8096/
- Networking: ethernet
- Storage: SSD, HDD, LVM, bcache, ext4
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ArabCoders** [comment]
This problem still exists on

Version: 10.8.5
Operating System: Linux
Architecture: X64

**Comment by edrock200** [comment]
Can confirm this is still happening on latest (Version: 10.8.9) Jellyfin. I have all realtime monitoring off. As soon as jellyfin is started, it ends up with tons of inotify watches:
`   INOTIFY   INSTANCES
   WATCHES      PER   
    COUNT     PROCESS   PID USER         COMMAND
------------------------------------------------------------
 1250100         2     14209 user    /usr/bin/jellyfin --ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg`

But monitoring is not on:

`find . -type f -name options.xml -exec grep Monitor {} \;
  <EnableRealtimeMonitor>false</EnableRealtimeMonitor>
  <EnableRealtimeMonitor>false</EnableRealtimeMonitor>
  <EnableRealtimeMonitor>false</EnableRealtimeMonitor>
  <EnableRealtimeMonitor>false</EnableRealtimeMonitor>
  <EnableRealtimeMonitor>false</EnableRealtimeMonitor>
  <EnableRealtimeMonitor>false</EnableRealtimeMonitor>
  <EnableRealtimeMonitor>false</EnableRealtimeMonitor>
  <EnableRealtimeMonitor>false</EnableRealtimeMonitor>
  <EnableRealtimeMonitor>false</EnableRealtimeMonitor>
  <EnableRealtimeMonitor>false</EnableRealtimeMonitor>
  <EnableRealtimeMonitor>false</EnableRealtimeMonitor>`

**Comment by twiclo** [comment]
```
[root@toph /]# lsof -K | grep inotify | cut -d' ' -f 1 | uniq -c
     14 polkitd
      1 firewalld
      4 NetworkMa
   8964 jellyfin
      2 rsyslogd
 ```

**Comment by edrock200** [comment]
Something is still triggering watches. Checked all libraries again to ensure no realtime monitoring is on, restart, redeployed, etc. but as soon as it starts, it begins to eat up inotify watches.

`   INOTIFY   INSTANCES
   WATCHES      PER   
    COUNT     PROCESS   PID USER         COMMAND
------------------------------------------------------------
 1325718         2      4976 user /usr/bin/jellyfin --ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg
 1325718         2     30981 user   /usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -init_hw_device vaapi=va:,driver=iHD -filter_hw_device va -hwaccel vaapi -hwaccel_output_format vaapi -autorotate 0 -i f`

The log also shows entries like this which sounds like the realtime monitor, but I'm not sure:
`[2023-05-25 20:18:32.588 +02:00] [INF] [203] Emby.Server.Implementations.IO.LibraryMonitor: "Season 1" ("/path/to/random/show/Season 01") will be refreshed.`

**Comment by edrock200** [comment]
@Bond-009 should I open a new issue since this is closed? I grabbed some verbose logs to post if that's helpful.
