### ISSUE TITLE
[Issue]: InfuseSync1.4.2.0 状态： NotSupported

### ISSUE THREAD

**Issue by AntaresXL** [jellyfin/jellyfin#7687]
### Please describe your bug

InfuseSync1.4.2.0 
状态： NotSupported

InfuseSync1.4.2.0 
Added support for Jellyfin 10.8.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS:DSM 6.2.4-25556
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
InfuseSync is not maintained by Jellyfin. 
https://github.com/firecore/InfuseSync/
