### ISSUE TITLE
[Issue]: Search by tag in Photo library (Home Video & Photo)

### ISSUE THREAD

**Issue by matteocedroni** [jellyfin/jellyfin#7691]
### Please describe your bug

Hi,
I added a library for Home Video & Photo with content type Photo.

Search returns no results for any tag

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Bond-009** [comment]
Should be fixed by #8842
