### ISSUE TITLE
[Issue]: Last Added tv-shows (series) section on startpages is losing entries

### ISSUE THREAD

**Issue by Weedalf** [jellyfin/jellyfin#7703]
### Please describe your bug

The Last Added TvShows Tab on startpage has a strange behavior. While Adding new TV-Shows I lose my entries on "last added Shows" on Startpage.

I read in matrix chat that only TV-Shows are shown from the 80 episodes you added last. But in my Understanding this makes no sense.

example:
I add to my library: episodes of Star Trek TOS, All episodes of DS9, all VOYAGER Episodes and at last Star Trek TNG (176 Episodes)
You will only see Star Trek TNG at last added TV Shows. People who look at your Startpage now would not recognize that you uploaded all this different star trek shows.

If you now rename in every TV shows one episode and do a library scan after that you will see this tv shows in last added.
But not more than 80 tv shows (if my information is correct)  

In my opinion the number of episodes should not considered when determining which and how many series to show in the "last series" section. if you touch one episode or add one to a tv series , if this series is existing on the server or not does not matter, this series  should be the new first entry of "last added tv-series". 

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: Raspbian 
- Plugins: intros, ldap, reports, playback reporting
- Reverse Proxy: caddy
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by thornbill** [comment]
Closing as a duplicate of #1880
