### ISSUE TITLE
HEVC transcoding problems

### ISSUE THREAD

**Issue by xmu714** [jellyfin/jellyfin#771]
As mentioned by issue #755 , I want to enable Hardware Acceleration for my jellyfin server on windows 10, but I found when I opened option **Intel Quick Sync** as HW acceleration, ffmpeg exited with errors:
```
[hevc_qsv @ 000002ad33eae540] Could not load the requested plugin '15dd936825ad475ea34e35f3f54217a6': specified object was not found (-9)
[hevc_qsv @ 000002ad33eae540] Error loading plugins
[hevc_qsv @ 000002ad33eae540] Error initializing an MFX session
Error while decoding stream #0:1: Function not implemented
```
I fond that with **--hwaccel qsv** and the latest ffmpeg build, ffmpeg worked successfully with no errors.

Today I manually built jellyfin from source，added **--hwaccel qsv** in `EncodingHelper.cs` in line 2198:
 `return "-c:v hevc_qsv ";` to `return "-hwaccel qsv -c:v hevc_qsv`, and ffmpeg did transformed my HEVC video to ts segments in folder `transcoding-temp`.

**But when I watched this video through browsers, the browser only plyed first segment and hang instead of continueing**, anybody knows how to solve it?

**Comment by scurrvy2020** [comment]
which browser are you using?  I had some issues with firefox, but it's working fine with chromium.
