### ISSUE TITLE
Merge folders of the same name in different locations

### ISSUE THREAD

**Issue by microdockman** [jellyfin/jellyfin#7711]
Due to limited storage space, I need to add a folder with the same name to expand the space on the new disk。
Jellyfin will display two file collection of the same name. if it can display only one folder and automatically rename the repeated file ？

I don't want to manual sorting, it's too much work

**Comment by michaelkrieger** [comment]
You can add two folders to the same library. They then appear as one.

for TV shows, select (in the manage library) to automatically merge folders with series spread across multiple folders) to avoid duplicate shows.

**Comment by microdockman** [comment]
> You can add two folders to the same library. They then appear as one.
> 
> for TV shows, select (in the manage library) to automatically merge folders with series spread across multiple folders) to avoid duplicate shows.

''You can add two folders to the same library. They then appear as one.''
Yes, it's a manual solution. It's a lot of work

''for TV shows, select (in the manage library) to automatically merge folders with series spread across multiple folders) to avoid duplicate shows.''
I chose type is ''mix of Film and TV'',everything looks fine, and when the merge option is checked, a collection is generated based on the file name, which seems different from the folder merge of the same name

**Comment by cvium** [comment]
If you are using Linux, you can use something like [mergerfs ](https://github.com/trapexit/mergerfs) to join multiple drives to one "virtual" drive.

But this is a feature request and one I do not believe makes sense. People have many reasons for using the same folder names without necessarily wanting to group them and we do not want to add the extra complexity of handling it.

**Comment by isaacgr** [comment]
> You can add two folders to the same library. They then appear as one.
> 
> for TV shows, select (in the manage library) to automatically merge folders with series spread across multiple folders) to avoid duplicate shows.

I have a mixed library with Movies and shows. Any way I could get this functionality with that library? It doesnt have that option.

**Comment by d03j** [comment]
> If you are using Linux, you can use something like [mergerfs ](https://github.com/trapexit/mergerfs) to join multiple drives to one "virtual" drive.

I know this is closed but, FYI, the mergefs folks themselves say "[When setting up software like Plex, Jellyfin, etc. point to the underlying filesystems. Not mergerfs.](https://trapexit.github.io/mergerfs/faq/limit_drive_spinup/#what-if-you-only-query-already-active-drives)"
