### ISSUE TITLE
[Issue]: 10.8.0 spamming journalctl logs

### ISSUE THREAD

**Issue by ManuLinares** [jellyfin/jellyfin#7713]
### Please describe your bug

to reproduce check logs with

`journalctl -feb --no-tail`

these three messages are being spammed all the time.

```
Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : [192.168.200.0/24]
Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : []
Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: [192.168.200.0/24]

```

### Jellyfin Version

10.8.0

### if other:

10.8.0_beta2

### Environment

```markdown
- OS: Manjaro XFCE
- Virtualization: NO
- Clients: Not aplicable
- Browser: Not aplicable
- FFmpeg Version: Not aplicable
- Playback Method: Not aplicable
- Hardware Acceleration: Not aplicable
- Plugins: standard and opensubtitles
- Reverse Proxy: no
- Base URL: none
- Networking: Host
- Storage: local
```

### Jellyfin logs

```shell
https://pastebin.com/bG00g8st
```

### Please attach any screenshots here

![image](https://user-images.githubusercontent.com/3720020/167023778-6db1ae11-118f-4099-b833-81ebd98442f7.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Xavantex** [comment]
I still experience this in 10.8.10, is it a setting?
