### ISSUE TITLE
[Issue]: apt upgrade to last stable ffmpeg-jellyfin (5.0.1-2-bullseye) make majors issues (stream and adding h.264 movies, 100% i9 CPU)

### ISSUE THREAD

**Issue by VigibotDev** [jellyfin/jellyfin#7715]
### Please describe your bug

Sorry since I apt upgraded my server a new package become updated : ffmpeg-jellyfin

Start-Date: 2022-05-04  12:18:53
Commandline: apt upgrade
Upgrade: jellyfin-ffmpeg:amd64 (4.4.1-4-bullseye, 5.0.1-2-bullseye)
End-Date: 2022-05-04  12:18:55

and now it make a lot of problems... 100% CPU for some time when I add movies (but some work) all AVC.
When it try to get chapter images, and they never come... No audio choice, no subtile choice and movie won't launch in browser I think it can't remux because movie work on jellyfin client (direct file stream). I run on last stable (production) and I can't make more test for now because this freeze my family media center and they complain lol.

I downgraded to previously installed : 4.4.1-4-bullseye to workaround the issue on last. 4.4.1-4-bullseye appear the last(?) working version.

apt install jellyfin-ffmpeg=4.4.1-4-bullseye

I can install the last jellyfin-ffmpeg=5.0.1-2-bullseye package on a dev machine if you request more (logs) or cmdline to try with.

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: Debian 11
- Virtualization: None
- Clients: All
- Browser: All
- FFmpeg Version: ffmpeg version 5.0.1-Jellyfin Copyright (c) 2000-2022 the FFmpeg developers
- Playback Method: all
- Hardware Acceleration: no
- Plugins: two stock reporting plugin
- Reverse Proxy: apache
- Base URL:
- Networking: 10gbps
- Storage: local mount (not over network)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
I highly recommend you downgrade to ffmpeg 4 as ffmpeg 5 isn't supported in Jellyfin 10.7.7

https://github.com/jellyfin/jellyfin-ffmpeg/issues/138#issuecomment-1117620765
