### ISSUE TITLE
[Issue]: Weird Next Up Behavior

### ISSUE THREAD

**Issue by dannymichel** [jellyfin/jellyfin#7719]
### Please describe your bug

Notice how I have tons 'next up' but the homepage only shows one thing. Keep in mind that my setting is to show 365 days of 'next up' and that the last 6 episodes were watched within the last 7 days.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Mac
- Virtualization: Docker
- Clients: Web
- Browser: Chrome
- Plugins: Trakt, Infuse, OpenSubtitles
- Reverse Proxy: Nginx
- Storage: Cloud(Google Drive/Rclone/Mergerfs)
```

### Please attach any screenshots here

https://www.youtube.com/watch?v=dhLeoze56UU

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cvium** [comment]
Possibly fixed by https://github.com/jellyfin/jellyfin/pull/8348

**Comment by dannymichel** [comment]
> Possibly fixed by https://github.com/jellyfin/jellyfin/pull/8348

It is 100% fixed yes
