### ISSUE TITLE
Duplicate finder 

### ISSUE THREAD

**Issue by mu-stash** [jellyfin/jellyfin#772]
Hi, 

Sometimes, on the film detail page, I'm wondering: Have I already seen this one ? And the search function gives me the answer: Yes, I have this film twice in different places. 

It would be great to have a specific page to detect duplicates. For example: a drop box allow the user to select a type of id. Let's say I choose: "imdb Id". Then a table shows for each row a different "imdb id", and for each col, the video files for this imdb id.

Significant details should allow the user to know what to do. It may be a multipart movie, for example. But if the user recognizes a duplicate, details like codec, file size, etc. should help him to choose the best version. There should be a button to delete the unwanted file. 

I do not know the database structure of jellyfin, but I believe a few simple requests should do the trick. Maybe it could be done for TV show episodes too ?

Anyway, thank you for the good work.

**Comment by cvium** [comment]
Once we fix the multi-version handling, it should just be a simple view filter, so I'm not sure I agree that it should be a plugin. (It is after all default functionality in Plex)

**Comment by sparky8251** [comment]
Well, if we want to separate the web ui from the server as well, we would need a plugin arch for the web ui (which we dont have yet).

Probably should be in the main project or wait until we got a new web ui.
