### ISSUE TITLE
[Issue]: Accessing Jellyfin from domain not working

### ISSUE THREAD

**Issue by oscie57** [jellyfin/jellyfin#7721]
### Please describe your bug

I have Jellyfin set up in the most basic way, with the port being on 8096. I wanted to share my Jellyfin server with friends and family so I opened it via port forwarding. myip:8096 works but when its on the actual domain it doesnt. I use cloudflare for DNS but it doesnt have proxy enabled. On chrome I get ERR_SSL_PROTOCOL_ERROR, on firefox its SSL_ERROR_RX_RECORD_TOO_LONG. I have no idea why this isnt working, even when going to http://domain. I dont have SSL setup because I dont know how so I just use HTTP. any ideas? it doesnt work on chrome or firefox, but it does on safari.

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: Windows
- Virtualization: None
- Clients: Browser
- Browser: Chrome 101
- FFmpeg Version: 2022-01-13-git-c936c319bd-full_build-www.gyan.dev
- Storage: Local
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by SquaredPotato** [comment]
If you're a beginner I'd recommend to use what's called a reverse proxy. 
Programs like Traefik or Nginx-reverse-proxy-manager are your friend when making things available outside of your home network. They also take care of your SSL problems by providing  an easy way to setup certificates. 
Another important aspect of _not_ using HTTPS when going outside your home network is that it's really easy to leak your credentials in a MITM attack, so please consider closing your port-forward until you have things figured out.

With that out of the way, you could try checking if HTTPS is enabled in jellyfins' networking settings.
