### ISSUE TITLE
Hardware acceleration

### ISSUE THREAD

**Issue by bekon16** [jellyfin/jellyfin#773]
Hardware Acceleration

Hi, is on JellyFin hardware acceleration support for Nvidia GPU? - such as it was in Emby?
Here is my setup: server / hypervisor XCP-NG > virtual machine with Debian 9 and Emby.
XCP-NG allow assigning dedicated GPU to virtual machine (pass through). In my server i have only i3 2120t cpu in most cases it is enough to play even 10GB mkv movie in 1080p, but sometimes i need to wait a little to smoothly play movie. In new version of emby hardware acceleration is only for premium users...
I'd like to buy some nvidia gpu and use it to transcode movies (instead of CPU). Is this option available in Jellyfin to use nvidia gpu to decode movies? 

I hope this is properly channel to ask my question, if not please tell me where should i wrote.

Best regards.

**Comment by Essasetic** [comment]
Hardware Acceleration currently doesn't work. This is due to the FFmpeg build they use. It's in the works though!

**Comment by bekon16** [comment]
Thanks, for reply. If it will be fixed where i can read about it? To test and check if its really working?

**Comment by JustAMan** [comment]
@bekon16 I think latest dockerfile-based build should use ffmpeg that has at least vaapi support, so you can use your CPU integrated graphics if you pass it through. nvidia one is planned for sure, you can track #191 for progress.

**Comment by bekon16** [comment]
Thanks for information. Unfortunately vaapi is unsupported on xcp-ng, dedicated GPU is required.

**Comment by JustAMan** [comment]
Cannot you just run it in docker on host?

**Comment by bekon16** [comment]
No. Because its a virtual machine which dont have access to intel GPU, so it does no matter that it is docker or something else.

**Comment by Hello-User** [comment]
He means run the docker image on the machine hosting your virtual machines instead of on one of the virtual machines, that way you can give docker direct access to the igpu instead of having to deal with multiple levels of virtualization

**Comment by bekon16** [comment]
Its not possible (in my case), because of:
- HV supervisor (OS for docker)  is installed on pendrive - for few reasons (i know i can run only docker and mount media from external drive - its pointless)
- Its XCP-NG, not pure Centos 7 i dont wanna more problems than i can handle
- Generally its a bad idea
Anyway thanks for help. 
I'll wait for next releases if there will be support for hardware acceleration for external GPU - i become a new user of jellyfin.

**Comment by Komic** [comment]
Damn, HW decoding technical support is sparse. :/
I think parsing `ffmpeg -hwaccels` and display the result could be a good start?

**Comment by Komic** [comment]
Damn, HW decoding technical support is sparse. :/
I think parsing `ffmpeg -hwaccels` could be a good start?
