### ISSUE TITLE
Where is the storage information for people's profiles stored?

### ISSUE THREAD

**Issue by kofzhanganguo** [jellyfin/jellyfin#7730]
![Snipaste_2022-05-10_09-57-39](https://user-images.githubusercontent.com/32073931/167527166-c6213cf7-378c-4837-9ace-845810385192.jpg)
My software is moved to another computer, how do I back up the actor's profile, the actor's photo can be found and copied to another computer for re-scanning, but how do I back up the actor's profile to other computers?

**Comment by icedterminal** [comment]
You would need to backup the database itself: `library.db`

**Comment by kofzhanganguo** [comment]
This approach is unscientific. It should generate NFO metadata under the character picture folder, and save all the information of the actors in the NFO, so after the migration, you can directly scan the character information, and back up the library.db media library data, which caused Confusion, such as I add other media libraries on another device, etc., this will cause conflicts.

**Comment by icedterminal** [comment]
It doesn't automatically. You have to tell it to during setup. Additionally, Jellyfin will still fetch metadata online. It is a requested feature to not do so.  https://features.jellyfin.org/posts/745/make-nfo-an-adjustable-metadata-provider

I am unsure if Jellyfin would do it now after your Library has been set up for however long you have had it.
