### ISSUE TITLE
Parental Controls not respected when searching

### ISSUE THREAD

**Issue by candry7731** [jellyfin/jellyfin#7733]
### Please describe your bug

I am running Linux with Jellyfin 10.8
The search function is not excluding parental control tags or ratings and showing content that should be excluded. 

I have Parental Content setup for users with excluded tags

User Parental Content exclude tags, , See image
![image](https://user-images.githubusercontent.com/83685828/167650571-2dc4a9da-73ee-467f-bfdc-9f93c37c193c.png)

Live TV Meta Data (Channel is set to have tag, ADULT-XXX),, See image
![image](https://user-images.githubusercontent.com/83685828/167650304-ac8c422d-65c5-4f55-bd7a-08c99f4815b0.png)

This is being filtered out of the live tv correctly however when you search the channels that should be excluded show up as all kinds of media types, See image
![image](https://user-images.githubusercontent.com/83685828/167650895-a53cc2b9-cf8d-438b-ae6b-07e683cbf3e2.png)

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Debian
- Virtualization:
- Clients: All
- Browser: Chrome
- FFmpeg Version: 4.32
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shadowghost** [comment]
Most likely fixed by #8526
