### ISSUE TITLE
[Issue]:  jellyfin have unmet dependencies - Unable to install

### ISSUE THREAD

**Issue by diasdmhub** [jellyfin/jellyfin#7742]
### Please describe your bug

While following the [official Ubuntu installation steps](https://jellyfin.org/downloads/), the provided repository fails to fulfill Jellyfin dependencies.
I'm using Ubuntu:
```
$ cat /etc/issue.net
Ubuntu 22.04 LTS
```
I have installed the official repository
```
$ cat /etc/apt/sources.list.d/jellyfin.list
deb [arch=amd64] https://repo.jellyfin.org/ubuntu jammy main
```
All repositories are updated.
```
$ sudo apt update
Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 https://repo.jellyfin.org/ubuntu jammy InRelease
Hit:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu jammy-security InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
```
When I try to install Jellyfin it is unable to find the correct dependencies.
```
$ sudo apt install jellyfin
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 jellyfin : Depends: jellyfin-server but it is not installable
            Depends: jellyfin-web but it is not installable
E: Unable to correct problems, you have held broken packages.
```
When I search for Jellyfin packages, no _server_ or _web_ packages are found.
```
$ sudo apt search jellyfin
Sorting... Done
Full Text Search... Done
jellyfin/unknown 10.7.7-1 all
  Provides the Jellyfin Free Software Media System
jellyfin-ffmpeg/unknown 4.4.1-4-jammy amd64
  Tools for transcoding, streaming and playing of multimedia files
jellyfin-ffmpeg5/unknown 5.0.1-3-jammy amd64
  Tools for transcoding, streaming and playing of multimedia files
```

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: Ubuntu 22.04 LTS
- Virtualization: LXC
- Clients: N/A
- Browser: N/A
- FFmpeg Version: N/A
- Playback Method: N/A
- Hardware Acceleration: N/A
- Plugins: N/A
- Reverse Proxy: N/A
- Base URL: N/A
- Networking: Local
- Storage: N/A
```

### Jellyfin logs

```shell
N/A
```

### FFmpeg logs

```shell
N/A
```

### Please attach any browser or client logs here

N/A

### Please attach any screenshots here

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ehussong** [comment]
Can confirm I am also experiencing this issue on a fresh 22.04 Ubuntu install.

**Comment by GamerBene19** [comment]
I just experienced this issue aswell, however the doc says:

> Supported releases are bionic, cosmic, disco, eoan, and focal.

So it's not really a big surprise i guess. Still - it would be nice if `jammy` was supported aswell ^^

**Comment by Shadowghost** [comment]
Will be the case with 10.8 (I think it's already the case with 10.8 beta)

**Comment by ehussong** [comment]
> I just experienced this issue aswell, however the doc says:
> 
> > Supported releases are bionic, cosmic, disco, eoan, and focal.
> 
> So it's not really a big surprise i guess. Still - it would be nice if `jammy` was supported aswell ^^

The download page states:
>We support amd64, armhf, and arm64 for architectures, debian and ubuntu for distributions, buster and bullseye for Debian releases and bionic, focal, impish **and jammy** for Ubuntu releases.

**Comment by icedterminal** [comment]
`jellyfin-server` at this time depends on `libssl1.1` (openssl 1.1.1f) for the HTTPS function. This package is obsolete in 22.04 and doesn't exist. Ubuntu 22.04 ships with `libssl3` (openssl 3.0.2).

> Will be the case with 10.8 (I think it's already the case with 10.8 beta)

At this time, no, that is not the case.

```
root@vmx22:/home/vmx# dpkg -i jellyfin-server*.deb
Selecting previously unselected package jellyfin-server.
(Reading database ... 214038 files and directories currently installed.)
Preparing to unpack jellyfin-server_10.8.0~beta2_amd64.deb ...
Unpacking jellyfin-server (10.8.0~beta2) ...
dpkg: dependency problems prevent configuration of jellyfin-server:
 jellyfin-server depends on at; however:
  Package at is not installed.
 jellyfin-server depends on libssl1.1; however:
  Package libssl1.1 is not installed.

dpkg: error processing package jellyfin-server (--install):
 dependency problems - leaving unconfigured
Processing triggers for libc-bin (2.35-0ubuntu3) ...
Errors were encountered while processing:
 jellyfin-server
```

You can't install (downgrade to) `libssl1.1` on 22.04 without hosing your system. *A lot* of software still uses OpenSSL 1.1.1f. It is still supported until 2023-09-11. When it comes to upgrading OS versions, you should generally wait a year, or until the depends are present for the software you use.

**Comment by diasdmhub** [comment]
It seems that there are no `jellyfin-server` or `jellyfin-web` packages available for Jammy release.

I see that it depends on `libssl1.1`, but I believe the issue here is with those Jellyfin absent packages.

If Ubuntu Jammy is not supported, maybe Jellyfin download page should be updated.
But, if it is supported after all, I hope that the provided repository is fixed soon.

**Comment by sparky3387** [comment]
Just so you know, the unstable branch does install

**Comment by Sokwva** [comment]
same issue on bionic.

**Comment by david-a-hillman** [comment]
Same issue on focal.

Running jellyfin 10.7.7-1, but cannot upgrade to 10.8.0-1.

**Comment by sparky3387** [comment]
This issue should be resolved are you using the main repo?

**Comment by Kingster01** [comment]
im getting same error on debian 10 buster jellyfin 10.8.0-1 is being held back.
jellyfin/unknown 10.8.0-1 all [upgradable from: 10.7.7-1]
jellyfin/now 10.7.7-1 all [installed,upgradable to: 10.8.0-1]

i do a jellyfin -v and i get 
Jellyfin.Server 10.8.0.0

I do sudo apt search jellyfin i get 
jellyfin/unknown 10.8.0-1 all [upgradable from: 10.7.7-1]
  Provides the Jellyfin Free Software Media System

jellyfin-ffmpeg/unknown,now 4.4.1-4-buster amd64 [installed,automatic]
  Tools for transcoding, streaming and playing of multimedia files

jellyfin-ffmpeg5/unknown 5.0.1-7-buster amd64
  Tools for transcoding, streaming and playing of multimedia files

jellyfin-server/unknown,now 10.8.0-1 amd64 [installed,automatic]
  Jellyfin is the Free Software Media System.

jellyfin-web/unknown,now 10.8.0-1 all [installed,automatic]
  Jellyfin is the Free Software Media System.

**Comment by david-a-hillman** [comment]
@sparky3387  I'm not sure to whom your question was directed, but I am using:

deb [arch=amd64] https://repo.jellyfin.org/ubuntu focal main

**Comment by sparky3387** [comment]
> @sparky3387 I'm not sure to whom your question was directed, but I am using:
> 
> deb [arch=amd64] https://repo.jellyfin.org/ubuntu focal main

Im using the jammy repo, maybe thats the difference, have you tried doing a purge and reinstall?

**Comment by Kingster01** [comment]
i commented yesterday was having same issue on debian buster not sure why it was deleted but all good not both server and web updated properly all issues fixed thanks

**Comment by jhon-ran** [comment]
During my last OS update (Raspberry Pi OS) I got the following error:
`jellyfin-ffmpeg5: conflicts jellyfin-ffmpeg but 4.4.1-1-bullseye is to be installed`
The server keeps working though with no apparent issues. I tried some fixes, but the error keeps popping up. Any ideas how to get rid of this error?

**Comment by dixonge** [comment]
I was having the same issues - the fix was to install the jammy version of ffmpeg from here:

https://repo.jellyfin.org/releases/server/ubuntu/versions/jellyfin-ffmpeg/5.1-1/

Use the one appropriate for your architecture. After that install, jellyfin installed right away, no unmet dependencies.

**Comment by JedMeister** [comment]
Same/similar issue with Debian Buster:
```
> apt update

Hit:1 http://security.debian.org buster/updates InRelease
Hit:2 http://deb.debian.org/debian buster InRelease
Ign:3 http://archive.turnkeylinux.org/debian buster-security InRelease
Ign:4 http://archive.turnkeylinux.org/debian buster InRelease
Hit:5 http://archive.turnkeylinux.org/debian buster-security Release
Hit:7 https://repo.jellyfin.org/debian buster InRelease
Hit:8 http://archive.turnkeylinux.org/debian buster Release
Reading package lists...
Building dependency tree...
Reading state information...
1 package can be upgraded. Run 'apt list --upgradable' to see it.

>  apt install jellyfin -y

Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 jellyfin : Depends: jellyfin-server (>= 10.8.3-1) but 10.7.2-1 is to be installed
            Depends: jellyfin-web (>= 10.8.3-1) but 10.7.2-1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by JedMeister** [comment]
FYI this works (there may be a simpler way, but I only tested this):
```
apt update
apt install -y jellyfin-ffmpeg5
apt install -y jellyfin-server=10.8.4-1 jellyfin-web=10.8.4-1
apt-mark auto jellyfin-web jellyfin-server jellyfin-ffmpeg5
apt autoremove
```
After the above steps:
```
~# apt policy jellyfin*
jellyfin-web:
  Installed: 10.8.4-1
  Candidate: 10.8.4-1
  Version table:
 *** 10.8.4-1 100
         10 https://repo.jellyfin.org/debian buster/main amd64 Packages
        100 /var/lib/dpkg/status
jellyfin-ffmpeg:
  Installed: (none)
  Candidate: 4.4.1-4-buster
  Version table:
     4.4.1-4-buster 10
         10 https://repo.jellyfin.org/debian buster/main amd64 Packages
     4.3.2-1-buster -1
        100 /var/lib/dpkg/status
jellyfin-server:
  Installed: 10.8.4-1
  Candidate: 10.8.4-1
  Version table:
 *** 10.8.4-1 100
         10 https://repo.jellyfin.org/debian buster/main amd64 Packages
        100 /var/lib/dpkg/status
jellyfin-ffmpeg5:
  Installed: 5.1-2-buster
  Candidate: 5.1-2-buster
  Version table:
 *** 5.1-2-buster 100
         10 https://repo.jellyfin.org/debian buster/main amd64 Packages
        100 /var/lib/dpkg/status
jellyfin:
  Installed: 10.8.4-1
  Candidate: 10.8.4-1
  Version table:
 *** 10.8.4-1 500
         10 https://repo.jellyfin.org/debian buster/main amd64 Packages
        100 /var/lib/dpkg/status
```
