### ISSUE TITLE
[Issue]: A library named "Collections" keeps reappearing even after manual deletion

### ISSUE THREAD

**Issue by cuihaoleo** [jellyfin/jellyfin#7747]
### Please describe your bug

A library named "Collections" was automatically created by Jellyfin:
![image](https://user-images.githubusercontent.com/889871/168443202-9bc7dfca-8256-47d3-aa3d-a7b70da6b06b.png)

I removed it from settings. But after a while Jellyfin recreated it.

The path the library points to is `/var/lib/jellyfin/root/default/Collections`.

The content of it is the "The Lord of the Rings Collection", a colleciton of 3 movies. The actually file of each episode is stored as an individual movie in another library. I think this is some auto-merging feature that went buggy.

I don't know if the bug appeared after one update. But I'm pretty sure it wasn't there until recent weeks.

Plugins enabled:
![image](https://user-images.githubusercontent.com/889871/168443529-55a9f0f0-4171-4b1b-a47c-bab68faf524c.png)

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Debian testing (bookworm)
- Virtualization: None
- FFmpeg Version: jellyfin-ffmpeg5 5.0.1-3-bullseye
- Plugins: See the screenshot above
- Base URL: /
- Storage: local
```

### Jellyfin logs

I don't see anything useful:
```shell
/var/log/jellyfin # rg 'Collections'
jellyfin20220511.log
2249:[2022-05-11 20:15:02.001 -07:00] [INF] Removing item, Type: "CollectionFolder", Name: "Collections", Path: "/var/lib/jellyfin/root/default/Collections", Id: [REDACTED-UUID]
2250:[2022-05-11 20:15:02.171 -07:00] [WRN] Slow HTTP Response from "https://[REDACTED-DOMAIN]/Library/VirtualFolders?refreshLibrary=true&name=Collections" to "[REDACTED-IP]" in 0:00:00.9389611 with Status Code 204
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gummykage** [comment]
It's been happening to me also. 10.8.0 beta 1 and 2 did this. Previous it would only appear when I used the plugin to create boxsets. It's pretty irritating.

**Comment by cvium** [comment]
Go to your Library settings and uncheck this 
![image](https://user-images.githubusercontent.com/675118/168473871-744c83c7-5f47-495d-acad-84a844866b5c.png)

**Comment by cuihaoleo** [comment]
Yeah. I can confirm this works. Thanks!

> Go to your Library settings and uncheck this ![image](https://user-images.githubusercontent.com/675118/168473871-744c83c7-5f47-495d-acad-84a844866b5c.png)

**Comment by wickedyoda** [comment]
Having the same issue, removed the option to auto-add to collections. Went via CLI and changed collections in the default config to false, removed config/data/collections and any other reference to them. Anytime it runs a full scan for new media the folder is rebuilt. 
![image](https://user-images.githubusercontent.com/68271168/189248379-df57ead3-bf92-4f09-8def-b0a0552cb0f2.png)

**Comment by mattiasghodsian** [comment]
I have the same issue as @wickedyoda collections are disabled for one of my librarys but they reappear after full scan or recreating the library

![image](https://github.com/jellyfin/jellyfin/assets/20265517/da2d91a1-e260-4bdc-85c1-0111727c5d83)
