### ISSUE TITLE
[issue]: Jellyfin is ignoring "[tmdbid-00000]" in folder name when importing, getting the wrong movie

### ISSUE THREAD

**Issue by NaturalBornCamper** [jellyfin/jellyfin#7748]
Seems like Jellyfin is ignoring the `TmdbId` as per your [official naming guide](https://jellyfin.org/docs/general/server/media/movies.html)
_In order to help with identifying a movie, Jellyfin can make use of media provider identifiers. This can be specified in your movie's folder name, for example: Film (2010) [imdbid-tt0106145] or Film (2018) [tmdbid-65567]_

Movie path is `\movies\Hours (2013) [tmdbid-172803]\Hours (2013) [SDTV].avi` but it was identified as "127 Hours (2010)" instead of [Hours (2013)](https://www.themoviedb.org/movie/172803-hours)
![image](https://user-images.githubusercontent.com/1697306/168457976-558021aa-807a-4e66-bf9b-6fd1d346b850.png)

![image](https://user-images.githubusercontent.com/1697306/168457995-5bf85385-a49e-473d-ad7a-3cfcdc95984b.png)

I did not tag as a bug yet, in case I missed something, however I didn't find anything on Googleor Github about Jellyfin ignoring `TmdbId`.

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: DietPi (Debian)
- Virtualization: None
- Clients: Windows 10, Windows 11, Android
- Browser: Opera, Chrome, official media player on Windows, official media player on Android
- FFmpeg Version: Irrelevant
- Playback Method: Irrelevant
- Hardware Acceleration: None
- Plugins: The Movie DB, The Open Movie Database
- Reverse Proxy: None
- Base URL: none
- Networking: Host
- Storage: local
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cvium** [comment]
This is a 10.8 feature

**Comment by NaturalBornCamper** [comment]
Wow, so rare that the docs are ready before the release in software engineering, Kudos, good job and can't wait for 10.8!
