### ISSUE TITLE
Add CSS custom server global [[Display the backdrops in the background]

### ISSUE THREAD

**Issue by AnonymousWebHacker** [jellyfin/jellyfin#7763]
I've added a custom CSS on my server, and the desktop/android clients adapt perfectly to the new css, but they each have to manually enable [Display the backdrops in the background of some pages while browsing the library.]

Is there any way to activate this general for all users? if not, it would be a very good option in the server settings

**Comment by crobibero** [comment]
No, bulk setting of settings is not a current feature.

Feature requests belong at https://features.jellyfin.org
