### ISSUE TITLE
[Issue]:  MessageUnauthorizedUser after update to 10.8 beta 3

### ISSUE THREAD

**Issue by StevMaHo** [jellyfin/jellyfin#7770]
### Please describe your bug

switched to 10.8 beta3 today from 10.7.7
 Now I can no longer log in with my user accounts (admin and not admin)

i get this error message: MessageUnauthorizedUser

tried it on my mobile phone and my pc where jellfin is installed.

after reinstall back to 10.7.7 i dont get this error

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS:Windows
- Virtualization:
- Clients:Browser, Android
- Browser:Edge
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Please attach any browser or client logs here

[log_20220518.log](https://github.com/jellyfin/jellyfin/files/8718067/log_20220518.log)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cvium** [comment]
Try clearing the browser cache and do a re-login in the Android app.

**Comment by StevMaHo** [comment]
It does not work. Also tried to reinstall the jellyfin app, a new browser and also tried it on a device where I have never used jellyfin. It just doesn't want me to log in. 

After a Clean Install IT works

**Comment by cvium** [comment]
Your user might have been disabled after too many login attempts https://jellyfin.org/docs/general/server/users/adding-managing-users.html#locking-and-unlocking-users

**Comment by StevMaHo** [comment]
At first I thought so too, then i set the startup wizard to false in system.xml and created a new user. but with these user the error comes too.

**Comment by Gotrees** [comment]
how do I unlock if I'm locked out of my admin account?
