### ISSUE TITLE
[Issue]: Samsung TV (pre-Tizen, DLNA only) is not showing subtitles from Jellyfin 10.7.7

### ISSUE THREAD

**Issue by Freealx** [jellyfin/jellyfin#7771]
### Please describe your bug

Hi guys,

Samsung TV model UN46D6900 (pre-Tizen, DLNA only) is not showing subtitles from Jellyfin 10.7.7
The used DLNA profile is "Samsung Smart TV" and there are no indication for any problem in the DLNA debug logging.
When a remote managed casting is used the subtitle option is shown, but cannot be selected.
The subtitle is an external SRT file and the encoding is not changing the behavior... ANSI, UTF8 (with/without BOM) - all variations are still not shown on the TV.
When playing it on VLC Player (PC or Android) everything is working fine and the subtitles are shown.

As a reference, when using dockerized ReadyMedia (miniDLNA) server from the same TNAS, the subtitles are shown perfectly fine on the same Samsung TV.

After reading a ton of contractionary information from different sources decided to "speak" with the source ;-)

Greets,

Alex

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: TNAS linux (TerraMaster F5-221)
- Virtualization: Docker
- Clients: Samsung TV
- Browser: n/a
- FFmpeg Version: 4.3.2-Jellyfin
- Playback Method: Direct Stream
- Hardware Acceleration: none
- Plugins: none
- Reverse Proxy: none
- Base URL: none
- Networking: Host
- Storage: local
```

### Jellyfin logs

```shell
[2022-05-19 01:44:13.689 +00:00] [INF] [30] Emby.Dlna.Main.DlnaEntryPoint: Profile: "Samsung Smart TV", Path: "/media/Videos/TV Shows/XXXX/XXXX S01E01 - XXXXXXX.mp4", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2022-05-19 01:44:16.573 +00:00] [INF] [27] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "DLNA" "10.7.7" playing "XXXXXXX". Stopped at "2209000" ms
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by megas7** [comment]
the same problem on me on the latest version
