### ISSUE TITLE
[Feature Request]:  eBook Library similar to other Libraries

### ISSUE THREAD

**Issue by manf0001** [jellyfin/jellyfin#7772]
Hello,   This is more of a request for the eBook Library.

I set up a library for ebooks, and added my books, but the library looks just very basic like I am using other content.    It just lists all the ebooks in a folder view.

Could it be possible to make the ebook library more like the Music Library, where when I go into it, I can see a listing of the books, or different options across the top to view by Author, or Genre of book.

**Comment by crobibero** [comment]
Feature requests belong at https://features.jellyfin.org
