### ISSUE TITLE
[BUG] 10.8.0.0 beta3 DVD playback issue on Rocky Linux (CentOS builds)

### ISSUE THREAD

**Issue by jrvmedic** [jellyfin/jellyfin#7786]
1. Virgin installation of Rocky Linux 8.6
2. Virgin installation of  ffmpeg v5.0.1 static from ffmpeg.org website. Verfied it can transcode file VOB -> MP4
3.  Virgin installation of JellyFin v10.8.0.0 beta3 for Centos according to instructions on website.
4. Via browser to localhost:8096, added folder with two DVD images to create library, and scanned it.
5. From web browser attempted to play either of the DVDs yields "Playback Error" (see image).
6. Checking the .log shows a transcode problem when manually running the generated command line for the ffmpeg utitlity. (see below)
7. ffmpeg appears to complain that the input paramter (-i file:"/media/dvds/_YOUNG_SHELDON/YOUNG_SHELDON_S01_D2_2017" ) is a directory, and is not a file - Which is entirely true;
8. however, inside the folder (on disc) is the folder "VIDEO_TS", and therein are a dozen files (names VIDEO_TS.BUF/.IFO, etc and many .VOB files. This "dvd image" plays fine when directed to "play disc to VLC"
9. I would have expected JellyFin Server software to have generated an ffmpeg command line with one of the VOB files, or more probably, one of the .IFO files. Perhaps this is considered to be a "bug" in the ffmpeg software, and not a bug in the JellyFin software. But in any event, JellyFin server does not appear to play any DVD images that are put into its libraries.

May-23: I have confirmed that if the ffmpeg command -i parameter is changed from ]]]file:"/media/dvds/_YOUNG_SHELDON/YOUNG_SHELDON_S01_D2_2017"[[[ to ]]]file:"/media/dvds/_YOUNG_SHELDON/YOUNG_SHELDON_S01_D2_2017/VIDEO_TS/VIDEO_TS.VOB"[[[ then the .m3u8 file gets generated, and the .ts's files for it are created. The question therefore is: "What is the correct behavior for Jellyfin Server? Should it leave decoding of the sub-directories to ffmpeg? Or is its behavior correct and the containing folder above it is correct on the command line?"

I am unable to find documentation and/or examples of ffmpeg referencing a "dvd image" aka "a directory image of VOB,IFO, and BUF files", so my guess is that Jellyfin Server is creating the wrong -i parameter for ffmepg - but I cannot find any documentation as to what the new DVD behavior of Jellyfin should be.

**Logs**
FFmpeg.Transcode-2022-05-22...... file in the Jellyfin Server log folder:
/videos/a14917e5-ed12-9a90-c07d-5c3bbc750008/live.m3u8

{"Protocol":0,"Id":"a14917e5ed129a90c07d5c3bbc750008","Path":"/media/dvds/_YOUNG_SHELDON/YOUNG_SHELDON_S01_D2_2017","EncoderPath":null,"EncoderProtocol":null,"Type":0,"Container":"","Size":null,"Name":"YOUNG_SHELDON_S01_D2_2017/DVD","IsRemote":false,"ETag":"543b6ca4c9f21c87d81daf7a932499c0","RunTimeTicks":null,"ReadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":false,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"OpenToken":null,"RequiresClosing":false,"LiveStreamId":null,"BufferMs":null,"RequiresLooping":false,"SupportsProbing":true,"VideoType":2,"IsoType":null,"Video3DFormat":null,"MediaStreams":[],"MediaAttachments":[],"Formats":[],"Bitrate":null,"Timestamp":null,"RequiredHttpHeaders":{},"TranscodingUrl":null,"TranscodingSubProtocol":null,"TranscodingContainer":null,"AnalyzeDurationMs":null,"DefaultAudioStreamIndex":null,"DefaultSubtitleStreamIndex":null}

ffmpeg -autorotate 0 -i file:"/media/dvds/_YOUNG_SHELDON/YOUNG_SHELDON_S01_D2_2017" -map_metadata -1 -map_chapters -1 -threads 0 -sn   -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_base_url "hls/898136d196e8f5f7df2385bf8e95b03c/" -hls_segment_filename "/var/lib/jellyfin/transcodes/898136d196e8f5f7df2385bf8e95b03c%d.ts" -hls_playlist_type event -hls_list_size 0 -y "/var/lib/jellyfin/transcodes/898136d196e8f5f7df2385bf8e95b03c.m3u8"

ffmpeg version 5.0.1-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
  libavdevice    59.  4.100 / 59.  4.100
  libavfilter     8. 24.100 /  8. 24.100
  libswscale      6.  4.100 /  6.  4.100
  libswresample   4.  3.100 /  4.  3.100
  libpostproc    56.  3.100 / 56.  3.100
file:/media/dvds/_YOUNG_SHELDON/YOUNG_SHELDON_S01_D2_2017: Is a directory

**Stats for Nerds Screenshots**
![image](https://user-images.githubusercontent.com/31710230/169722972-7a25b781-8daf-4d31-a31e-c2604d297ce7.png)

**Server System (please complete the following information):**
 - OS: [e.g. Docker on Linux, Docker on Windows, Debian, Windows]
 - Jellyfin Version: 10.8.0.0 on Rocky Linux 8.6
 - FFmpeg Version: ffmpeg version 5.0.1-static https://johnvansickle.com/ffmpeg/
 
**Client System (please complete the following information):**
 - Device: Dell laptop 
 - OS: Rocky Linux 8.6
 - Client: Web
 - Browser (if Web client): FireFox and Chrome browser (many differ versions)
 - Client and Browser Version: many versions

**Comment by Roardom** [comment]
VIDEO_TS folders still remain unplayable in 10.8.4.

I believe the intended way to do this via ffmpeg is via dvd2concat, which requires lsdvd, which requires libdvdread.

Alternatively, it looks like the code jellyfin should be using to simply concat .VOB files is located at https://github.com/jellyfin/jellyfin/blob/33611614ed3362bd6b9b83781a47927fc16bba5a/MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs#L826, but it doesn't seem to actually be used anywhere.

**Comment by Shadowghost** [comment]
Folder based DVD playback was never supported. Please merge them into an ISO. That should playback as intended.

**Comment by jrvmedic** [comment]
As opposed to the comment from Shadowghost, and as part of the basis for my original comment, Jellyfin on Windows *DID* support VIDEO_TS images. FFmpeg CAN stream/render VIDEO_TS but it did not appear to work on linux with any of the versions of 10.8 that I tested. I just tried installing 10.7 on WIndows, and it works fine for my huge collection of DVDs. WIth all the high-quality QA testing for 10.8, something was broken and my comment from a year ago tried to flag it so.

**Comment by Roardom** [comment]
10.7 is the first release they're broken. DVDs playback perfectly fine in 10.6.4 using the linuxserver.io docker container last I tested if I'm remembering correctly (it's some commit on master between 2020-08-05 and 2020-08-11 based on notes I wrote last time I tried finding the cause). I also noticed when using this version that libraries are scanned much quicker (1 minute vs 30 minutes), but haven't dug into the default settings yet, wondered if it had something to do with every folder erroring when scanning in the current version. If you want DVD support, you can simply use version 10.6.4, but I wouldn't recommend opening it up to the internet as I would assume there have been security vulnerabilities fixed since then.

One day I hope to dig into the code deeper and fix it, but I'm not familiar with the codebase and my free time being limited is mostly spent on other open source projects.

**Comment by RTUnit** [comment]
Just as an option to suggest... I converted few of my DVDs to MKV. MakeMKV does this lossless by just packing them into MKV container. Takes a few seconds per each DVD. I used docker version of MakeMKV (https://hub.docker.com/r/jlesage/makemkv).

**Comment by Roardom** [comment]
> Ok I see one minor issue. The DVD play time is being calculated wrong, its being recalculated when its played so ffwd to 1 hour and 30 mins is difficult. Any ideas?

Afaik, every reverse engineered solution so far to playback dvds doesn't work perfectly. Ideally libdvdread should be used to play back dvds, which would most likely work better than the solution in 10.6.4, but it should be simply accepted that if you aren't using a licensed player, you will most likely come across a dvd that doesn't work perfectly. Some issues won't be able to be fixed until the DVD specifications are leaked / made public so that open source players can implement support for them properly.

> Just as an option to suggest... I converted few of my DVDs to MKV. MakeMKV does this lossless by just packing them into MKV container. Takes a few seconds per each DVD. I used docker version of MakeMKV (https://hub.docker.com/r/jlesage/makemkv).

I have well over 50TB of discs (including Blu-ray). I'd have to double that storage space if I wanted to keep an mkv for every disc I already have backed up. It'd also be a real pain to rename each file, figure out the names of all the extras on movie discs, and for tv discs you'd have to play each disc in VLC and make sure you're naming each episode correctly. That's besides the fact that makemkv has had bugs in the past that has resulted in faulty files (e.g. prior to version 1.15.4 a pop is heard throughout TrueHD tracks).

Fwiw, I currently use kodi with the jellyfin for kodi addon with the storage hosted on an smb server and using the native paths option. This setup plays back discs, both dvds and bds, with menus even. Supposedly would work remotely as well, although I haven't tried that yet.

**Comment by Shadowghost** [comment]
If someone wants to test it, I've fixed up our current implementation to some point in a test branch: https://github.com/Shadowghost/jellyfin/commits/dvdlib-fix (based off master)
DVD folders are properly recognized and all non-menu VOBs sent to ffmpeg but at least with my test setup ffmpeg keeps getting stuck at some point.
DVD ISOs seem to not work as well as I expected them to do with ffmpeg. Most likely we should deprecate support and just support DVD folders if I get them working.

**Comment by BryanJacobs** [comment]
In 10.8.9-1, collecting metadata from and playing back DVD folders is broken, but BDMV folders work fine.

With the above branch rebased on jellyfin master, collecting metadata for DVD folders works well, but playback doesn't. The web client displays a spinner forever, and the server logs show this (partial) stacktrace:

    [2023-02-02 XX:09:29.354 +XX:00] [ERR] [18] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/Videos/1f60a0e1c58a47f5b9e4586e22a3f9c3/AdditionalParts".                           
System.TypeInitializationException: The type initializer for 'Nikse.SubtitleEdit.Core.Common.Configuration' threw an exception.                                                                                    
 ---> System.UnauthorizedAccessException: Access to the path '/Subtitle Edit' is denied.                                                                                                                           
 ---> System.IO.IOException: Permission denied                                                                                                                                                                     
   --- End of inner exception stack trace ---                                                                                                                                                                      
   at System.IO.FileSystem.CreateParentsAndDirectory(String fullPath, UnixFileMode unixCreateMode)                                                                                                                 
   at System.IO.FileSystem.CreateDirectory(String fullPath, UnixFileMode unixCreateMode)                                                                                                                           
   at System.IO.Directory.CreateDirectory(String path)                                                                                                                                                             
   at Nikse.SubtitleEdit.Core.Common.Configuration.GetDataDirectory()                                                                                                                                              
   at Nikse.SubtitleEdit.Core.Common.Configuration..cctor()                                                                                                                                                        
   --- End of inner exception stack trace ---                                                                                                                                                                      
   at Nikse.SubtitleEdit.Core.Common.Configuration.get_Settings()                                                                                                                                                  
   at Nikse.SubtitleEdit.Core.SubtitleFormats.MPlayer2.get_Extension()                                                                                                                                             
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEditParser.<>c.<.ctor>b__2_0(SubtitleFormat subtitleFormat) in /home/aur/jellyfin-git/src/jellyfin/MediaBrowser.MediaEncoding/Subtitles/SubtitleEditParser.cs:li
ne 30                                                                                                                                                                                                              
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()                                                                                                                                                        
   at System.Linq.Lookup`2.Create(IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)                                                                                                          
   at System.Linq.GroupedEnumerable`2.GetEnumerator()                                                                                                                                                              
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)                                                   
   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEditParser..ctor(ILogger`1 logger) in /home/aur/jellyfin-git/src/jellyfin/MediaBrowser.MediaEncoding/Subtitles/SubtitleEditParser.cs:line 29                    
   at InvokeStub_SubtitleEditParser..ctor(Object, Object, IntPtr*)           

It looks to me like the code is literally attempting to access the path `/Subtitle Edit` on the filesystem. Not great. The client sees a 500 response with `Request Failed` to all `AdditionalParts` API calls for BDMV or DVD folders.

This happens regardless of whether the client sets the subtitle preference to "always" or to "never".

So in summary, one thing is fixed, and one thing is broken by the changes.

**Comment by BryanJacobs** [comment]
The above may be https://github.com/jellyfin/jellyfin/issues/9190 .

**Comment by Shadowghost** [comment]
@BryanJacobs your error has nothing to do with the issue discussed here or with the changes I made.

I rebased my branch on current master and it works fine with local DVD folders if the files are fine. I'm mentioning this because one of my test DVDs had a VOB with a wrongly coded runtime, resulting in ffmpeg hanging/crashing. There is nothing we can do in that case.

DVD ISO playback is still borked but without re-adding mount permissions for Jellyfin (which imo is a security risk I don't want to reintroduce) there is nothing I can do about that.

@AndrzejL-eu you'd need to compile Jellyfin off my branch and replace your current binaries with the new ones.

**Comment by Shadowghost** [comment]
You need to checkout the correct branch too before building:
```
git clone -b dvdlib-fix https://github.com/Shadowghost/jellyfin.git
cd jellyfin
sudo ./build -t docker -p debian.amd64
```

**Comment by Shadowghost** [comment]
This are master builds. Some of the plugins might not work as intended. It seems like TVDB is your problem.

**Comment by BryanJacobs** [comment]
@Shadowghost You're right, my problem is https://github.com/jellyfin/jellyfin/issues/8198 . From a Linux server, master has broken streaming.

If you backport your changes to a release branch without that issue I can test streaming with them, but barring that I can't test. Thanks for the work you've done anyway, and sorry.

**Comment by Shadowghost** [comment]
I came up with another approach, if you want to test again, use the `dvdbdfix` branch of my fork.

**Comment by Shadowghost** [comment]
DVD and BD folders should now work with episodes too.
Apart from that the DVD and BD playback code now properly concatenates all major title VOBs/M2TS files with the correct timestamps. This results in working skipping and proper playback (before most of the time only the first file of the main title was played). And we don't need to rely on DvdLib anymore (though it still exists in the branch).

**Comment by Shadowghost** [comment]
Seems to me like you need to set up a proper testing library to make sure your testing is conclusive.

**Comment by Shadowghost** [comment]
What exactly is your filesystem layout?
It should work if adhering to our common movie layout. I extensively tested this on a clean instance with a single movie library using the parent library folder as source folder:
```
parent library folder
|-- Movie A title (year)
    |-- VIDEO_TS
| Movie B title (year)
    |-- BDMV
```

**Comment by Shadowghost** [comment]
Sorry to hear that but nonetheless your library layout is not adhering to what Jellyfin expects so that is most likely the cause of some if not most of the problems you are encountering.
You sometimes have multiple DISC folders inside the same folder as a VIDEO_TS folder or movie folders inside a parent folder describing the collection (Like `Harry Potter`).
I'm also not sure how well the scanner handles things like extraimages and posters for VIDEO_TS based movies, that's something I will look at now :)
