### ISSUE TITLE
[Issue]: Jellyfin now populate fanart (backdrop) in an extrafanart folder

### ISSUE THREAD

**Issue by KevoM** [jellyfin/jellyfin#7787]
### Please describe your bug

I'm using beta2 and beta3.

Jellyfin add automatically any change in my library with complete folders created with the same user by Radarr.
I allowed JF to change or correct metadata by activating downloaders, nfo, etc

Radarr put posters and fanart alongside the movie. until now Jellyfin did the same.

I got weird duplicate in an extrafanart folder. I found that Jellyfin can replace poster.jpg, but with fanart, it creates an extra folder and put one or multiple fanart*.jpg

(Option for maximum backdrop is set to 1)

Is this the norm ?

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Armv7
- Virtualization: Docker
- Clients: Jellyfin Media Player (Macos), Browser
- Browser: Brave, Firefox
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins: 
- Reverse Proxy: nginx
- Base URL:
- Networking:
- Storage: local
```

### Please attach any screenshots here

![edo6uqrg54191](https://user-images.githubusercontent.com/8274366/169777037-508aaf1e-cd4e-407b-bc17-e48761bdb0ef.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by androiddisk** [comment]
https://jellyfin.org/docs/general/server/media/movies#backdrop

**Comment by androiddisk** [comment]
The jpg can't be put in this way
