### ISSUE TITLE
[Issue]: 10.8.0.0 beta3 - secondary LAN adapter slows down JF HTTP server

### ISSUE THREAD

**Issue by FrankBKK** [jellyfin/jellyfin#7791]
### Please describe your bug

I noticed that when running JF on a system with a secondary, not connected LAN adapter and Settings 'Bind to local network address:' left empty  JF becomes extremely slow (startup times > 5 minutes /  Slow HTTP Responses from "http://192.168.2.100:8096 etc.) 

Is that the intended behavior ?  Shouldn't an unconnected LAN IP just better be ignored ? 

Once JF is bound explicitly to one LAN it runs smooth though. 

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: WIN
- Virtualization: Portable
- Clients: n.a.
- Browser: n.a.
- FFmpeg Version: n.a.
- Playback Method: n.a.
- Hardware Acceleration: n.a.
- Plugins: n.a.
- Reverse Proxy: none
- Base URL: none
- Networking: Host  
- Storage: local
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cvium** [comment]
Logs?
