### ISSUE TITLE
[Issue]: jellyfin-server_20220524.8-unstable_amd64.deb fails to install on virgin ubuntu jammy 22.04 LTS

### ISSUE THREAD

**Issue by jrvmedic** [jellyfin/jellyfin#7793]
### Please describe your bug

Most recent .deb file fails to install on virgin OS

$ uname -a
Linux ubuntu00 5.15.0-25-generic #25-Ubuntu SMP Wed Mar 30 15:54:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

$ sudo dpkg -i jellyfin-server_20220524.8-unstable_amd64.deb jellyfin-web_20220524.6-unstable_all.deb 
(Reading database ... 160186 files and directories currently installed.)
Preparing to unpack jellyfin-server_20220524.8-unstable_amd64.deb ...
Unpacking jellyfin-server (20220524.8-unstable) over (20220524.8-unstable) ...
Selecting previously unselected package jellyfin-web.
Preparing to unpack jellyfin-web_20220524.6-unstable_all.deb ...
Unpacking jellyfin-web (20220524.6-unstable) ...
dpkg: dependency problems prevent configuration of jellyfin-server:
 jellyfin-server depends on at; however:
  Package at is not installed.

dpkg: error processing package jellyfin-server (--install):
 dependency problems - leaving unconfigured
Setting up jellyfin-web (20220524.6-unstable) ...
Processing triggers for libc-bin (2.35-0ubuntu3) ...
Errors were encountered while processing:
 jellyfin-server

### Jellyfin Version

10.8.0

### if other:

jellyfin-server_20220524.8-unstable_amd64.deb

### Environment

```markdown
- OS:$ uname -a
Linux ubuntu00 5.15.0-25-generic #25-Ubuntu SMP Wed Mar 30 15:54:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- Virtualization:
- Clients:
- Browser:  firefox
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
not yet installed
```

### FFmpeg logs

```shell
not yet installed
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zehnerGIT** [comment]
Ubuntu 22.04 switched from OpenSSL 1.1 to OpenSSL 3.0, but jellyfin depends on OpenSSL 1.1. If you update from 20.04 you have the old libssl1.1 still installed, so an upgrade installation works (I've gone the 20.04|10.7 -> 22.04|10.7 way without problems). If you do a new install, only libssl3 is installed.
You can try to install libssl1.1 from an older ubuntu version (http://packages.ubuntu.com) or compile OpenSSL 1.1 yourself, but OpenSSL is a very central package, so I would not recommend that to unexperienced linux users. Sooner or later, the repo version of jellyfin will integrate OpenSSL 3 and then you no longer need such workarounds.
