### ISSUE TITLE
Agroup movies fail and show double

### ISSUE THREAD

**Issue by Sirfrancis17** [jellyfin/jellyfin#780]
I select the two movies in the web browser and group them, but even so, the movies are seen in duplicate (if there are two)
<a href="http://es.tinypic.com?ref=2wdtw12" target="_blank"><img src="http://i64.tinypic.com/2wdtw12.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by Sirfrancis17** [comment]
They are different quality 1080 and 4k. I have all the movies in one folder. Is it obligatory to have each collection in its own folder?

**Comment by JustAMan** [comment]
I think it is for grouping them, at least that's my impression of trying to use that grouping feature.
You may be able to group them manually via metadata editor, but I'd recommend against manual metadata intervention to make sure your library can be easily re-scanned without damage.

**Comment by Sirfrancis17** [comment]
10.1.0

**Comment by cvium** [comment]
That description is for future improvements. I forgot to create an issue to track it.

If you can build from master it should just work automatically after a metadata refesh

**Comment by Sirfrancis17** [comment]
I Dont now how... I have jellyfish in docker and the Last versión (pull)
How i do with docker?

**Comment by cvium** [comment]
@Sirfrancis17 Sorry for not responding sooner. I am not too familiar with build processes.

cc @joshuaboniface

**Comment by Sirfrancis17** [comment]
The new versión (10.2) has the same error

**Comment by ferferga** [comment]
This is still happening

@anthonylavado How I should name the movies with different qualities? So I can fix part of the issues with my library.

**Comment by JustAMan** [comment]
@ferferga doesn't this section of docs help? https://jellyfin.org/docs/general/server/media/movies.html#multiple-versions-of-a-movie
