### ISSUE TITLE
Jellyfin 10.7-10.8 Media library scraping

### ISSUE THREAD

**Issue by zhangxuan1340** [jellyfin/jellyfin#7804]
Jellyfin 10.7.7 when scraping the media library, the number of concurrent tasks reaches 100 + simultaneous tasks, while 10.6.4 and emby are two tasks at the same time. Of course, the advantage of this is that the media library can be created quickly. However, when my file library is very large, there will be errors when there are WebDAV and fuse media libraries, resulting in abnormal emptying of the media library, but there is no such situation in 10.6.4, Can we launch switches for multi-threaded scraping and single threaded scraping, because the media library usually established will not move it, and it can basically refresh the library without feeling when real-time monitoring is turned on.

I hope the official group will consider adding switches for single thread and multi thread scraping media libraries.

ps: Machine Translation

**Comment by crobibero** [comment]
You should be able to limit the amount of scanning threads by setting these two fields in system.xml

If the value is 0 it will use as many threads as there are processors

LibraryScanFanoutConcurrency
LibraryMetadataRefreshConcurrency

**Comment by zhangxuan1340** [comment]
It can be modified through files. I'll try it. Because my processor is 56 core, it's probably what you said.

**Comment by zhangxuan1340** [comment]
Jellyfin. Add this parameter under XML file?  

LibraryScanoutConcurrency = 2
LibraryMetadataRefreshConcurrency = 2

**Comment by crobibero** [comment]
No- there's an existing file `system.xml` in the configuration directory.

My file has the following lines. You would just need to update the values (where it says `0`)

```xml
<ServerConfiguration>
[...]
  <LibraryScanFanoutConcurrency>0</LibraryScanFanoutConcurrency>
  <LibraryMetadataRefreshConcurrency>0</LibraryMetadataRefreshConcurrency>
[...]
</ServerConfiguration>
```

**Comment by zhangxuan1340** [comment]
Ok Thank
