### ISSUE TITLE
[Issue]: Cant change standard language for subtitle

### ISSUE THREAD

**Issue by neggard** [jellyfin/jellyfin#7814]
### Please describe your bug

Regardless of which language you choose as the default for the user, I get Danish as Default.
Have tried to choose both Swedish and Finnish but still Danish is the default.
If I choose Danish, it is still Danish that is the default :)

This bug has always been there for me. Have tried different version of the server.
This happend on all client, android, androidTV and browser

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS:Synology NAS V.7.1
- Virtualization:
- Clients: All
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Please attach any screenshots here

![subtitle](https://user-images.githubusercontent.com/51259182/170879508-2aeb78f3-16c3-4805-916b-921968990d85.jpg)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cvium** [comment]
Have you tried editing your profile instead? I could be wrong, but I don't think the setting in your screenshot even affects this in any way, nor should it.
![image](https://user-images.githubusercontent.com/675118/170893667-498db98b-060f-4bd1-bba4-e4c99c580b1a.png)

**Comment by gummykage** [comment]
Subtitles are affected by what you choose in your profile and whether or not the movie has been played before. If you have played the movie before and want it to auto choose a subtitle like it's first time played you need to delete it from your database.

Stop your server locate this db file located in your server/data/ folder:

![image](https://user-images.githubusercontent.com/9695713/171038249-776a10cf-4c30-455b-86ee-ed8d25fab58d.png)

Open this db file with DB Browser for SQLite and set the UserDatas table -> Subtitlestreamsindex column of the video you just played to NULL. If you don't care about your previous subtitle selections and just wanna wipe it all to first time subtitle behavior, just select the column and ALT+Del to auto set the whole column to NULL and save the changes. (WARNING THIS WILL DELETE SUBTITLE SELECTIONS FOR ALL USERS) I'd suggest you add a new movie, figure out the key that belongs to it and play with that one movie only. But if ur the only user, its safe to just set it all to NULL.

![image](https://user-images.githubusercontent.com/9695713/171038778-0c9bde75-e5b4-49bd-aa1c-ccdd66dbc9a3.png)

Now when you select the movie the subtitle selection will be based on your subtitle preferences in your profile.

Now there's a chance your movie or mkv file metadata isn't set correctly. If its MP4 use mp4box. If it's MKV use MKVToolNix GUI.

![image](https://user-images.githubusercontent.com/9695713/171039031-c12ea3f6-325b-4bba-be36-7ff7ccfa169a.png)

If you plan to use Smart Auto it looks at your Audio track and if the language doesn't match the one in your profile it will auto find subtitles by the one you selected.

If you plan to use Default set the subtitle in the mkv file to:

Default Track - Yes
Track Enabled - Yes
Original Language - (Depends if it matches the movie)

Language and Language (IETF BCP 47) is set to the correct language so Jellyfin will recognize language the subtitle is set to.

If you plan to  use Forced in your profile then ONLY subtitles that have the forced flag ticked will be auto loaded on first try.

Just remember a few things, if you played the movie once, it's no longer going to look at your profile subtitle preferences as it overrides everything and just uses what you picked on this user account from this point on.

Also if you plan to use external subtitles but keep subtitles in the mkv file itself, then use MKVToolNix Header Editor and set default to no and it will prefer external subtitles (Doesn't have to process them).

Naming for external subtitles:

Dumbledore (2022).default.en.srt
Dumbledore (2022).en.English [SHD].srt
Dumbledore (2022).forced.en.srt

This will create 3 subtitles with external attached in the jellyfin menu.

Here's an example of embedded subtitles and external ones:

![image](https://user-images.githubusercontent.com/9695713/171039817-64ca7916-2190-445d-aca5-9de56ccebac4.png)

**Comment by szerencl** [comment]
I have subtitles set to always play and selected English as the preferred language. I want English audio and English subtitles.
![kép](https://user-images.githubusercontent.com/57007996/207677628-31acce51-3ddb-4181-ba76-dd32a8d453cf.png)

However Jellyfin still doesn't respect the setting it just selects Hungarian, or sometimes the first available (Danish. Chinese etc.) (I think when there is no Hungarian).
![kép](https://user-images.githubusercontent.com/57007996/207677381-a8c5329c-db3e-45d7-bb5f-0c11cb1a615f.png)![kép](https://user-images.githubusercontent.com/57007996/207680879-7373af2d-7bfc-440d-ad67-c77548d91be0.png)


I checked the things mentioned above.
In the database the subtitle is null for everything as it's a fresh install.
![kép](https://user-images.githubusercontent.com/57007996/207677014-07d899f5-0411-49c1-8608-93ee2915bea2.png)
In the metadata every subtitle is labelled correctly and all of them are enabled.
![kép](https://user-images.githubusercontent.com/57007996/207677226-6abb060b-058b-4100-8dee-04656236644e.png)
