### ISSUE TITLE
what is the difference between stream type hls and video?

### ISSUE THREAD

**Issue by swhoro** [jellyfin/jellyfin#7827]
I want to develop a jellyfin-like server with golang as practice.
I am curious about what is the difference between these stream types.
I read some articles about hls, it seems hls split a video to many .ts files to stream.
And when the stream type is video, it seems it always request the same .mov file?
What's more, if I want to stream hdr and dolby vision video, what should I do.
And if there any suggested blogs, articles, books?

**Comment by ycy1164656** [comment]
seems like stream is like downloading the whole file?

**Comment by Bond-009** [comment]
This really isn't the place to ask
