### ISSUE TITLE
[Issue]: In Live TV, refreshing guide data doesn't update channel images after remapping them manually 

### ISSUE THREAD

**Issue by danielearwicker** [jellyfin/jellyfin#7834]
### Please describe your bug

I set up HD Homerun and Schedulesdirect, let the guide refresh and found a lot of channels incorrectly mapped. When I manually remapped them I tried refreshing it a few times, although the channel content was now correct, the image didn't get corrected.

I stepped through `LiveTvManager.GetChannelAsync` and found where it says:

```cs
if (!item.HasImage(ImageType.Primary))
```

So the channel already has a primary image (the incorrect one from the auto-mapped channel) and this seems to stop it from re-fetching. Should there be some kind of comparison between the old/new URL strings so it can detect when the cached image is wrong? I am happy to look into this further if this seems like the right direction.

### Jellyfin Version

Other

### if other:

master branch

### Environment

```markdown
- OS: MacOS
- Virtualization:
- Clients: Browser
- Browser: Safari 15.5
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jurgenhaas** [comment]
I'm having the exact same issue and would hope, that this could be resolved. Maybe with the linked PR?

**Comment by Broglah1** [comment]
ditto same issue

**Comment by arab21dwc** [comment]
Same issue please add something to refresh tuner

**Comment by Aetherinox** [comment]
Sad to see this get closed. There needs to be at least some type of action to force refresh these instead of having to do it manually for over 300 channels. Easier just to wipe the entire set of data for channels and re-add.
