### ISSUE TITLE
[Issue]: Cannot manually set or change album artist

### ISSUE THREAD

**Issue by gitdev-bash** [jellyfin/jellyfin#7839]
### Please describe your bug

I am unable to change the album artist anywhere. Musicbrainz has the correct value, but somehow i am getting a completely random value for a single album. Also i can't seem change the value anywhere in the GUI. Editing the NFO file causes Jellyfin to overwrite it again to the random value.
Duplicate of #2315

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: Debian
- Virtualization: none
- Clients: Browser, IOS
- Browser: -
- FFmpeg Version: included
- Playback Method: -
- Hardware Acceleration: none
- Plugins: default
- Reverse Proxy: none
- Base URL: no
- Networking: host
- Storage: local
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Maxplosion** [comment]
whats the metadata of the files themselves like? do all of them have the same new album artist? you can check with e.g. mp3tag tool

**Comment by kuflierl** [comment]
> whats the metadata of the files themselves like? do all of them have the same new album artist? you can check with e.g. mp3tag tool

After some trial and error, I have found out that a tag named 'Band' in the mp3 files is overwriting the Album Artist (exiftool dump). This tag was not visible in mp3tool and etc and I had a hard time finding it.

But my initial issue still persist, that one can not simply be overwrite this tag with the nfo files.

Anyway, thanks for pointing me in the right direction.

**Comment by Maxplosion** [comment]
yeah that's what I suspected.
In mp3tag there is a context menu for extended tags, there you should see all that are on the file. 
My recommendation is to use Musicbrainz Picard to tag the files and first set it to whipe existing tags of the files (you can also specify what to keep) this way you have clean metadata and jellyfin will have the least troubles to scan and match correctly. works 97% fine for all of my tracks, also obscure stuff that I fully manually tag.

**Comment by Kajaqq** [comment]
Issue still happening, please add a function to change other metadata than the name of the album, it would really help with wrong assigned artists/wrong tagged files.

**Comment by TeaRexJack** [comment]
Years later, still a problem.

**Comment by ThinLiquid** [comment]
Still a problem here!
