### ISSUE TITLE
Enable dynamic plugin load and unload

### ISSUE THREAD

**Issue by LogicalPhallacy** [jellyfin/jellyfin#784]
**Is your feature request related to a problem? Please describe.**
Restarting servers to load or unload plugins is dumb and wastes time.

**Describe the solution you'd like**
This should be tagged with dotnet core 3 as that will be bringing the unload load functionality of Appdomains which would enable exactly this sort of thing.

**Describe alternatives you've considered**
We could keep it the way it is and require server restarts that technically ought not to be needed.

**Additional context**
@JustAMan please tag for dotnet core 3

**Comment by cvium** [comment]
It's just not feasible even in .NET 5. Unloading is a huge can of worms.
