### ISSUE TITLE
music genre are numbers

### ISSUE THREAD

**Issue by icf20** [jellyfin/jellyfin#7844]
![image](https://user-images.githubusercontent.com/17784575/172025652-36fbddfa-a72f-4d7f-8752-c8e550514abc.png)

for some odd reason, numbers are music genre 

![image](https://user-images.githubusercontent.com/17784575/172025727-231dfe03-b35b-4a47-ac8f-9d3b2242dc42.png)

https://musicbrainz.org/release/0b537869-27ff-44ca-883a-0f3080c23a7a field is none and here https://www.theaudiodb.com/album/2126445 is trance

**Comment by crobibero** [comment]
Please fill out the template, it's there for a reason.

**Comment by icf20** [comment]
> Please fill out the template, it's there for a reason.

huh?

**Comment by icf20** [comment]
> if you create a new issue there is a template with questions to fill out,

There is no template, everything is empty, there looks to be a bug on the github platform

**Comment by Bond-009** [comment]
https://github.com/jellyfin/jellyfin/issues/new?assignees=&labels=bug%2Ctriage&template=issue+report.yml&title=%5BIssue%5D%3A+
