### ISSUE TITLE
Unable to complete setup wizard (spinning circle)

### ISSUE THREAD

**Issue by ploughpuff** [jellyfin/jellyfin#786]
**Describe the bug**
Merge #742 seems to have broken the setup wizard.  I get spinning circle when trying to go from page 2 to 3.

**To Reproduce**
CO master branch
Start Jellyfin with clean (virgin) data folder (I used -programdata d:\temp\742data)
Page 1, click next
Page 2, click next

**Expected behavior**
Should move to page 3

**Actual behaviour**
Stay on page 2 with spinning circle.

**Logs**
[log_20190201.log](https://github.com/jellyfin/jellyfin/files/2823050/log_20190201.log)

**Screenshots**

![image](https://user-images.githubusercontent.com/33969763/52144362-f4a46180-2655-11e9-9bab-44c419ea6571.png)

**System (please complete the following information):**
 - OS: Windows, VS17 debug mode
 - Browser: Brave
 - Jellyfin Version: master

**Additional context**

**Comment by cvium** [comment]
Need to update the submodule

**Comment by ploughpuff** [comment]
I'm running with latest jellyfin-web submodule.
So this is a know limitation on master right now?

**Comment by ploughpuff** [comment]
```
C:\git_repos\jellyfin\MediaBrowser.WebDashboard\jellyfin-web>git remote -v
origin  https://github.com/jellyfin/jellyfin-web.git (fetch)
origin  https://github.com/jellyfin/jellyfin-web.git (push)

C:\git_repos\jellyfin\MediaBrowser.WebDashboard\jellyfin-web>git checkout master
Checking out files: 100% (307/307), done.
Previous HEAD position was 094c1deae Merge pull request #49 from jellyfin/release-10.1.0
Switched to branch 'master'
Your branch is up to date with 'origin/master'.

C:\git_repos\jellyfin\MediaBrowser.WebDashboard\jellyfin-web>git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

**Comment by cvium** [comment]
Have you cleared the browser cache? It works for me

**Comment by ploughpuff** [comment]
That was it!  Thank you.

Switching to private browse window (effectively clean cache) and different window is shown, which I can navigate away from:

![image](https://user-images.githubusercontent.com/33969763/52148636-3d621780-2662-11e9-8c5e-c5f7a5a4fb47.png)
