### ISSUE TITLE
Issue started in 10.7.0 and is still in 10.7.7 Dvd Vobs do not load unless they are single files. ffmpeg permission denied. 10.6.4 was the last working version that would still play folders with a DVD video_ts.ifo, video_ts.bup and *.vob

### ISSUE THREAD

**Issue by Jrossi3334** [jellyfin/jellyfin#7861]
Issue started in 10.7.0 and is still in 10.7.7 Dvd Vobs do not load unless they are single files. ffmpeg permission denied. 10.6.4 was the last working version that would still play folders with a DVD video_ts.ifo, video_ts.bup and *.vob 

/videos/d67d6d4e-6276-f0fd-2527-24473bb179a7/live.m3u8

{"Protocol":0,"Id":"d67d6d4e6276f0fd252724473bb179a7","Path":"K:\\Testing\\Video","EncoderPath":null,"EncoderProtocol":null,"Type":0,"Container":"","Size":null,"Name":"Video/DVD","IsRemote":false,"ETag":"79b360cf2d3dcd2da9d3dbb42c3d3b89","RunTimeTicks":null,"ReadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":false,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"OpenToken":null,"RequiresClosing":false,"LiveStreamId":null,"BufferMs":null,"RequiresLooping":false,"SupportsProbing":true,"VideoType":2,"IsoType":null,"Video3DFormat":null,"MediaStreams":[],"MediaAttachments":[],"Formats":[],"Bitrate":null,"Timestamp":null,"RequiredHttpHeaders":{},"TranscodingUrl":null,"TranscodingSubProtocol":null,"TranscodingContainer":null,"AnalyzeDurationMs":null,"DefaultAudioStreamIndex":null,"DefaultSubtitleStreamIndex":null}

C:\Program Files\Jellyfin\Server\ffmpeg.exe -i file:"K:\Testing\Video" -map_metadata -1 -map_chapters -1 -threads 0 -sn   -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_base_url "hls/13f95e56ef1263cee86d0c07b880a540/" -hls_playlist_type event -hls_segment_filename "K:\Jellyfin Temps\transcodes\13f95e56ef1263cee86d0c07b880a540%d.ts" -y "K:\Jellyfin Temps\transcodes\13f95e56ef1263cee86d0c07b880a540.m3u8"

ffmpeg version n4.3.1-Jellyfin Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10.2.0 (Rev6, Built by MSYS2 project)
  configuration:  --disable-static --enable-shared --cc='ccache gcc' --cxx='ccache g++' --extra-version=Jellyfin --disable-ffplay --disable-debug --enable-gpl --enable-version3 --enable-bzlib --enable-iconv --enable-lzma --enable-zlib --enable-sdl2 --enable-fontconfig --enable-gmp --enable-libass --enable-libzimg --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libdav1d --enable-opencl --enable-dxva2 --enable-d3d11va --enable-amf --enable-libmfx --enable-cuda --enable-cuda-llvm --disable-cuda-nvcc --enable-cuvid --enable-nvenc --enable-nvdec --enable-ffnvcodec --enable-gnutls
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
file:K:\Testing\Video: Permission denied

_Originally posted by @Jrossi3334 in https://github.com/jellyfin/jellyfin/issues/7065#issuecomment-1144263387_

**Comment by deleteforever** [comment]
i see this is still going on, would like hear if it could be fixed for future versions. it's the only thing that is still lacking on jellyfin for me.

**Comment by toneto33** [comment]
Same problem here, and also the only feature lacking on jellyfin for me.

**Comment by Bond-009** [comment]
Duplicate of #7065
