### ISSUE TITLE
Album not showing up if empty folder with same name but different capitalization exists

### ISSUE THREAD

**Issue by AlexKraak** [jellyfin/jellyfin#787]
**Description**

Sorry if this is way too specific a bug to my music library, but i had 2 folders like so
Artist/(2016) The Album name/
Artist/(2016) The Album Name/

One of these folders was empty, containing only a folder.jpg while the other contained all the tracks and a folder.jpg but because one was empty the folder with the tracks never got checked

**Expected behavior**

The library scan should check both folders, i assume it is case insensitive while in this case maybe it should be?

**System:**
 - OS: Docker
 - Browser: Firefox, Yatse, Mobile app
 - Jellyfin Version: Version 10.1.0

**Additional context**
Thanks so much for this project its super cool, I'm really enjoying my jellyfin experience :)

**Comment by JustAMan** [comment]
I think most checks are case-insensitive, plus Windows and some default installs of MacOS don't even support case sensitivity in paths.
I am also failing to see real use for such naming scheme, but am open to be proved wrong. 

For now I am tempted to close as "working as intended", but let's hear more people in case I am wrong.

**Comment by AlexKraak** [comment]
The naming scheme wasnt intentional, it was changed by beets but it left files behind so thats why there were 2 folders, The album shows up in supysonic/other players so I figured I would report it here just in case it might be preferred behavior
