### ISSUE TITLE
Virtual folders with name pattern

### ISSUE THREAD

**Issue by gaalos** [jellyfin/jellyfin#7879]
Hi, 
It might be nice if Jellyfin can create virtual folders based on name 
For example 

myserie.s01.E01.mkv
myserie.s01.E03.mkv
myserie.s01.E03.mkv
myserie.s01.E04.mkv

Create folder named myserie/S01/E01...4

myserie.s02.E01.mkv
myserie.s02.E03.mkv
myserie.s02.E03.mkv
myserie.s02.E04.mkv

Create folder named myserie/S02/E01...4

For example on big repository without any tree. Like mount point without subfolders

Best regards

**Comment by cvium** [comment]
We use Fider for feature requests: https://features.jellyfin.org/
