### ISSUE TITLE
[Issue]: 10.8.0 Jellyfin ignores poster and fanart already existing in the directory and instead pulls it from from tmdb/tvdb even with all metadata tuned off for the library 

### ISSUE THREAD

**Issue by GuardToad** [jellyfin/jellyfin#7882]
### Please describe your bug

This wasn't the behaviour on 10.7.7 and only started happening after i upgraded to 10.8.

Steps to Reproduce.
Upgrade to 10.8.
Have radarr download Movie Metadata and Movie Images in the Kodi (XBMC) / Emby format.
Replace the poster.jpg with something that doesn't match image on tmdb/tvdb.
Scan library.
Observe that the poster jellyfin uses isn't the one you placed in the directory but the one from tmdb/tvdb.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS:Debian
- Virtualization:Docker
```

### Please attach any screenshots here

Library metadata settings
![bild](https://user-images.githubusercontent.com/81426702/173205617-b1d256a4-34d1-47bc-8771-065ec06684dd.png)
![bild](https://user-images.githubusercontent.com/81426702/173205627-82979d19-28a3-4b1e-815b-864b88c177be.png)

pihole logs of the image fetch from tmdb
![bild](https://user-images.githubusercontent.com/81426702/173205671-7be09f5f-ff77-4e26-ba6d-6bca7dd04ced.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cvium** [comment]
And what about the NFO?

**Comment by GuardToad** [comment]
This is the NFO
[borat.subsequent.moviefilm.1080p.zip](https://github.com/jellyfin/jellyfin/files/8884807/borat.subsequent.moviefilm.1080p.zip)

**Comment by cvium** [comment]
Your NFO is pointing to TMDb :) Related to #7836 and fixed by #7873
