### ISSUE TITLE
[Issue]: Jellyfin is ignoring "[imdbid-tt1051155]" in folder name when importing, getting the wrong tv show

### ISSUE THREAD

**Issue by NaturalBornCamper** [jellyfin/jellyfin#7905]
Seems like Jellyfin is ignoring the `imdbid` as per your [official naming guide](https://jellyfin.org/docs/general/server/media/shows.html)
_In order to help with identifying a series, Jellyfin can make use of media provider identifiers. This can be specified in your show's folder name, for example: Series (2010) [imdbid-tt0106145] or Series (2018) [tmdbid-65567]_

Movie path is `\tv\Documentaries\The Universe [imdbid-tt1051155]` but it was identified as "Masters of the Universe: Revelation" instead of [The Universe](https://www.imdb.com/title/tt1051155/)

I did not tag as a bug yet, in case I missed something, however I didn't find anything on Google or Github about Jellyfin ignoring `Imdb Id`.

### Jellyfin Version

 10.8.0

### Environment

```markdown
- OS: DietPi (Debian)
- Virtualization: None
- Clients: Windows 10, Windows 11, Android
- Browser: Opera, Chrome, official media player on Windows, official media player on Android
- FFmpeg Version: Irrelevant
- Playback Method: Irrelevant
- Hardware Acceleration: None
- Plugins: The TV DB, The Movie DB, The Open Movie Database
- Reverse Proxy: None
- Base URL: none
- Networking: Host
- Storage: local
```

### Please attach any screenshots here

![image](https://user-images.githubusercontent.com/1697306/173263955-bd148081-4d2b-4548-81ac-2df77f3bb698.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cvium** [comment]
Shows do not support the imdbid tag. You can use `tvdbid`, `tvmazeid` or `tmdbid`

**Comment by NaturalBornCamper** [comment]
Ah ok so I guess it's the docs that need updating then? I'll rename my folder then thanks!

**Comment by cvium** [comment]
I don't mean to be rude, but we no longer support 10.7.x.

**Comment by NeobinX** [comment]
Will test it with 10.8.1 again, once it is out.
Thanks for the quick reply.

**Comment by NaturalBornCamper** [comment]
Not sure if issue should be closed or moved somewhere else. I didn't close it hoping an admin would either move it or contact the proper staff to change the documentation as this is the issue, not the code 
Docs still mention to use the imdb-id, while [cvium](https://github.com/cvium) said imdb-id is not supported.

**Comment by daullmer** [comment]
The documentation is open source as well so everyone can fix it. I have gone ahead and created a pull request for you. jellyfin/jellyfin.org#247

**Comment by NaturalBornCamper** [comment]
I hadn't realized docs were on the repo and I could have made a pull request myself, noted for next time thanks!

**Comment by pktiuk** [comment]
Hello,   
I also came here trying to figure out why there are problems with `imdbid`.
