### ISSUE TITLE
Chromecast support broken on Chrome

### ISSUE THREAD

**Issue by alexalouit** [jellyfin/jellyfin#791]
With latest Google Chrome version (v73) on Mac OS and Android, Jellyfin don't show Chromecast.
Chrome Mac OS built-in button does.
This works fine with older version.

Anyone got same problem?

**Comment by alexalouit** [comment]
Maybe duplicate #640

**Comment by cvium** [comment]
Works for me on macOS

**Comment by BobOkisama** [comment]
It is broken in the mobile apps. There is a mobile version that is supposed to be fixed for JF, but you have to compile it yourself currently.
https://github.com/jellyfin/jellyfin-android
https://github.com/jellyfin/jellyfin-ios

Personally I think the guys should ask for some donations to buy the kit/license needed to post a official Android/iOS app on both stores.

**Comment by alexalouit** [comment]
@cvium which version of chrome did you use?

**Comment by BobOkisama** [comment]
Ahh, then I am out of my league on this. I will try it out later tonight on my system from the web and report back.
Just so we know, are you using linux, windows, or OSX as your host?

**Comment by anthonylavado** [comment]
@BobOkisama We have accounts to post to various stores. We'd do this for the Android app, but it's not quite ready just yet.

The iOS app code doesn't work - I'll edit that repo to make it clear. We do have plans to support more platforms in the works, but for iOS, you can use VLC and or Infuse with their DLNA functions. Both work really well.

VLC also works on Chrome too! :)

**Comment by anthonylavado** [comment]
Digging in to this... I can replicate with the standard release of Version 72.0.3626.81 (Official Build) (64-bit) on my Mac. The Chromecast option does not show up there.

Tested with latest Chrome on my Android test device (Version 72.0.3626.76), not working either.

**Comment by anthonylavado** [comment]
Currently tracking:

# Chromecast Issue


| Platform | Version      | Status             |
|----------|--------------|--------------------|
| macOS    | 72.0.3626.81 | :x:                |
| Android  | 72.0.3626.76 | :x:                |
| Android  | 71.0.3578.99 | :white_check_mark: |
| ChromeOS  [1]| 72.0.3626.49 | :x:                |


[1] ChromeOS as reported in #640.

**Comment by joshuaboniface** [comment]
Specifically, from the Chrome dev console on 71:

```
cast_sender.js:67 [Deprecation] Using the Presentation API on insecure origins is deprecated and will be removed in M72. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details. 
```

So, it looks like 72 fully removes cast-over-HTTP support. I'm now working on documentation of reverse proxying to add to the install guide, with a mention of this explicitly.

**Comment by cvium** [comment]
I am on `Version 72.0.3626.81 (Official Build) (64-bit)` and it works for me.

**Comment by anthonylavado** [comment]
Alternately, if you're using Chrome on the same computer that is running Jellyfin, if you connect using "localhost:8096" or similar, it will also work. (Thanks to Luke for pointing this out.)

**Comment by cvium** [comment]
https://www.chromium.org/Home/chromium-security/prefer-secure-origins-for-powerful-new-features/#TOC-Definitions-

**Comment by mazzystr** [comment]
I currently use Chromecast (firmware 1.37.144496) streaming from Plex (3.53.7) on unencrypted connections.  I don't require https streaming.  I don't have the cpu cycles and electricity to spare.  Keep in my my streaming goal is to put a small beaglebone in the family minivan and let my kids stream movies from their Amazon Kindle Fires.  

The Chromecast plot thickens...

Here is my list of **broken** Chromecasting (firmware 1.37.144496)...
MacOS Firefox (Chromecast (firmware 1.37.144496) / JellyFin (v10.1.0)) / JellyFin (v10.1.0)
Android JellyFin (release_beta2) / JellyFin (v10.1.0)) / JellyFin (v10.1.0)

Here is my list of **working** Chromecasting (firmware 1.37.144496)...
MacOS Chrome (Version 71.0.3578.98 (Official Build) (64-bit)) / JellyFin (v10.1.0)) / JellyFin (v10.1.0)

**Comment by anthonylavado** [comment]
Firefox doesn’t have Chromecast support to my knowledge...

The Jellyfin Android app has some fixes to go through for Casting to be more reliable. If you don’t see it as an option, try leaving the app on screen, locking for a minute, then trying again.

The HTTPS requirement for casting is with Chrome browsers version 72+, whether it’s Android or Computer. There’s nothing we can do about it, it’s a change in Google’s code. They essentially broke it for everyone that was doing it, including Emby and Plex. Apps aren’t subject to the same restrictions, if you’re using them.

Plex also has the benefit of “giving” you a workaround with their “app.plex.tv” website, because they run it with HTTPS, and then it connects to your local setup. We’d love to do that, but we don’t support central servers 🙂

**Comment by mazzystr** [comment]
> Firefox doesn’t have Chromecast support to my knowledge...
It does.  

> re https...
Understood and I'm not against https.  I need it to be minimal as possible to get working meaning self signed certificate for .local tld.  

> re “app.plex.tv”
Oh yea, definitely. I'm here _because_ of Plex's central sign on.  We had a week long internet outage about 6 months ago (our local fiber loop got the excavator and it took them a while to pul a new line) which locked us out of our media center.  That set me on a journey which led me here.  I'm mostly liking what I'm seeing.  The communication is excellent and a far cry from the other apps.

**Comment by alexalouit** [comment]
For those who need, ere's what I do to reverse proxing with apache on debian stable

```
$ apt-get update
$ apt-get -y install apache2
$ echo -e 'ProxyPass "/" "http://127.0.0.1:8096/"\nProxyPassReverse "/" "http://127.0.0.1:8096/"' > /etc/apache2/conf-available/jellyfin.conf 
$ a2enconf jellyfin
$ a2enmod proxy
$ a2enmod proxy_http
$ a2ensite default-ssl
$ systemctl restart apache2
```

Jellyfin must be accessible under https://your-ip with self-signed certificate

**Comment by anthonylavado** [comment]
>> Firefox doesn’t have Chromecast support to my knowledge...

>It does.

Ah, on Android. I forget it's a browser there (iOS user myself). I was thinking desktop. My mistake. Carry on! :smile:

**Comment by denkuy** [comment]
Temporary Workaround
- go to chrome://flags/#unsafely-treat-insecure-origin-as-secure
- enable unsafely-treat-insecure-origin-as-secure
- add http://<EMBY_SERVER_IP>:8096

This works for me, however chrome forgets about this exception once closed.

**Comment by JustAMan** [comment]
I think the "fix" for this issue should be a document section in our docs describing the findings, and this issue should be closed after the docs are updated. It's nothing on our side we can do actually.

**Comment by icf20** [comment]
@JustAMan so chrome wont change course,
---
is there any other browser that support chromecast and dont have this issue?

**Comment by JustAMan** [comment]
I heard wind that maybe Firefox starts to support Chromecast... here's what I was able to find: https://www.linuxuprising.com/2019/01/fxcast-adds-chromecast-support-to.html

**Comment by icf20** [comment]
for linux users on arch downgrade is not longer a option to run version 71.0.35

/usr/lib/chromium/chromium: error while loading shared libraries: libicui18n.so.63: cannot open shared object file: No such file or directory


:angry: :angry: :angry:

**Comment by icf20** [comment]
this should be left pinned since is not solved

**Comment by mazzystr** [comment]
Chromecast has been working great for me.  

JellyFin: Version 10.2.1
Android: 9
App: jellyfin-android_release_beta8.apk

**Comment by anthonylavado** [comment]
@icf20 I removed the pin because there is no way to solve it easily. The only fix is to use HTTPS, and we can't really make that happen for everyone automatically. There are probably ways to generate certificates for people, but since everyone's set up is different, it's not a reliable way to go. Note that we're not alone in this - Emby and Plex both have the exact same issue.

Most people will use the apps, and those are will have Chromecast support built in.

**Comment by mazzystr** [comment]
My JellyFin install isn't https'd... still works

**Comment by anthonylavado** [comment]
@mazzystr But are you using the app, or the web interface? Our app doesn't require you to have HTTPS in order to cast (apps aren't subject to the same restrictions). The HTTPS requirement is *purely* using Chrome on Desktop or on Android.

**Comment by mazzystr** [comment]
Ah oops!  Yea I confirm that.  Chromecast cast target is not available in both Chrome or Firefox.

**Comment by anthonylavado** [comment]
Okay, closing for now. We'll do what we can with docs, but there's nothing left to do here. Chrome has moved on.

**Comment by icf20** [comment]
@anthonylavado if there is noway to get around this https requirement then chrome make jellyfin/emby useless

**Comment by DrPandemic** [comment]
@icf20 as it was mentioned earlier, there's many ways for way to work around this restriction.

1. Add a self-signed cert in front of your instance.
2. Put a real cert in front of your app.
3. Downgrade chrome.
4. Use the app 
5. Run chrome with `--unsafely-treat-insecure-origin-as-secure="http://example.com"`
6. Open the app your your localhost.
7. If the app is on another computer, forward the port on your computer to be able to use localhost.

For now, all of those solutions can't be done by us. So you'll need to customize a little bit your installation to be able to work with this closed source technology (Chromecast).

**Comment by nermin99** [comment]
@ghost 

> Temporary Workaround
> 
> * go to chrome://flags/#unsafely-treat-insecure-origin-as-secure
> * enable unsafely-treat-insecure-origin-as-secure
> * add http://<EMBY_SERVER_IP>:8096
> 
> This works for me, however chrome forgets about this exception once closed.

This doesn't work anymore for me.
