### ISSUE TITLE
Jellyfin  service crash inmediatly.   Failed to create CoreCLR, HRESULT: 0x8007FF02

### ISSUE THREAD

**Issue by rubentest** [jellyfin/jellyfin#7915]
Debian 11. Jellyfin.Server 10.8.0.0

packages installed from official repo: 
`jellyfin-ffmpeg5  jellyfin-server   jellyfin-web`

> systemd[1]: Started Jellyfin Media Server.
jellyfin[278151]: Failed to create CoreCLR, HRESULT: 0x8007FF02
systemd[1]: jellyfin.service: Main process exited, code=exited, status=137/n/a
systemd[1]: jellyfin.service: Failed with result 'exit-code'.

**Comment by ericfabregithub** [comment]
I installed Jellyfin.server 10.8.0.0 
Ubuntu Linux 20.04.4
Linux 4.9.277-83 sur aarch64
Informations sur le processeur | Hardkernel ODROID-HC4, 4 noyaux
 
I have the same problem 

Systemd[1]: Started Jellyfin Media Server.
Jun 13 23:19:54 cloud jellyfin[32527]: Failed to create CoreCLR, HRESULT: 0x8007FF02
Jun 13 23:19:54 cloud systemd[1]: jellyfin.service: Main process exited, code=exited, status=137/n/a
Jun 13 23:19:54 cloud systemd[1]: jellyfin.service: Failed with result 'exit-code'.
Jun 13 23:19:54 cloud systemd[1]: jellyfin.service: Scheduled restart job, restart counter is at 1.

**Comment by crobibero** [comment]
Likely duplicate of https://github.com/jellyfin/jellyfin/issues/7503

**Comment by aouvrard** [comment]
Hi everyone,

After read [this comment](https://github.com/dotnet/runtime/issues/44417#issuecomment-724236814) I try to disable memlock parameter on systemd service `#SystemCallFilter=~@memlock`  

This resolve issue but I don't known it's good

**Comment by ericfabregithub** [comment]
Hi eveyrone,

As aouvrad i disabled #SystemCallFilter=~@memlock in /lib/systemd/system/jellyfin.service and its works fine

**Comment by bv101rj** [comment]
> Run `sudo setenforce permissive` for temp fix.

This did the trick for me on Fedora 36

**Comment by kid1412621** [comment]
I believe this related to this one: https://github.com/jellyfin/jellyfin/issues/8303

**Comment by bv101rj** [comment]
It for sure is, reached out on that closed issue for more info and got back that changes need to be made with SELinux, going to try messing around with that sometime this week. If I can get a fix I will post it here / see what I can do to find out why its not working out of the box.

**Comment by devmalick** [comment]
`[dev@MX1 ~]$ sudo systemctl status jellyfin.service 
× jellyfin.service - Jellyfin Media Server
     Loaded: loaded (/usr/lib/systemd/system/jellyfin.service; enabled; preset: disabled)
     Active: failed (Result: exit-code) since Mon 2022-11-21 16:21:55 IST; 2min 40s ago
   Duration: 3ms
    Process: 8946 ExecStart=/usr/bin/dotnet /usr/lib/jellyfin/jellyfin.dll --datadir ${JELLYFIN_DATA_DIRECTORY} --cachedir ${JELLYFIN_CACHE_DIRECTORY} ${JELLYFIN_ADD_OPTS} (code=exited, sta>
   Main PID: 8946 (code=exited, status=150)
        CPU: 3ms

Nov 21 16:21:55 MX1 dotnet[8946]: Framework: 'Microsoft.NETCore.App', version '6.0.0' (x64)
Nov 21 16:21:55 MX1 dotnet[8946]: .NET location: /usr/share/dotnet/
Nov 21 16:21:55 MX1 dotnet[8946]: The following frameworks were found:
Nov 21 16:21:55 MX1 dotnet[8946]:   7.0.0 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
Nov 21 16:21:55 MX1 dotnet[8946]: Learn about framework resolution:
Nov 21 16:21:55 MX1 dotnet[8946]: https://aka.ms/dotnet/app-launch-failed
Nov 21 16:21:55 MX1 dotnet[8946]: To install missing framework, download:
Nov 21 16:21:55 MX1 dotnet[8946]: https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.0&arch=x64&rid=garuda-x64
Nov 21 16:21:55 MX1 systemd[1]: jellyfin.service: Main process exited, code=exited, status=150/n/a
Nov 21 16:21:55 MX1 systemd[1]: jellyfin.service: Failed with result 'exit-code'.

`

what to do not able to resolve

**Comment by bv101rj** [comment]
> Run `sudo setenforce permissive` for temp fix.

Hav you you tried this?

**Comment by devmalick** [comment]
it is working fine right now.
