### ISSUE TITLE
[Issue]: Syncplay forces the first version to be played

### ISSUE THREAD

**Issue by katruud** [jellyfin/jellyfin#7919]
### Please describe your bug

With version 10.8.0 on Unraid, I can start playing any version of a show. However, when I start a syncplay group, it reverts to playing the first version of the show.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS:Unraid
- Virtualization: Docker
- Clients: Windows 10/11
- Browser: Edge
- FFmpeg Version: 
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by d3vr** [comment]
Can confirm I'm experiencing the same issue on Jellyfin v10.8.1

**Comment by MoshiBar** [comment]
im experiencing the same issue on version 10.8.9
also when in a group and starting any video, it will revert to the original version before starting

**Comment by mprentice** [comment]
Same issue on version 10.8.10. Server is Ubuntu, web clients are Mac, behavior observed in Firefox & Chrome browsers.
