### ISSUE TITLE
[Issue]: 10.8 does not play DivX or Xvid videos

### ISSUE THREAD

**Issue by ThomasPGH** [jellyfin/jellyfin#7922]
### Please describe your bug

Every Xvid or DivX video I've tried so far fails with an error. Tested with Firefox and iOS client.

Stream mapping:
  Stream #0:0 (mpeg4) -> setparams:default
  Stream #0:2 (dvdsub) -> scale:default
  format:default -> Stream #0:0 (h264_amf)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
[matroska,webm @ 000001f5095fd7c0] sub2video: using 720x544 canvas
[AVHWFramesContext @ 000001f5095fdc00] Only fixed-size pools are supported for D3D11 to OpenCL mapping.
[Parsed_hwmap_7 @ 000001f509a06800] Failed to create derived source frames context: -22.
[Parsed_hwmap_7 @ 000001f509a06800] Failed to configure output pad on Parsed_hwmap_7
Error reinitializing filters!
Failed to inject frame into filter network: Invalid argument
Error while processing the decoded data for stream #0:0
Conversion failed!

Played perfectly fine in 10.7.6.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Windows 10
- Virtualization:
- Clients: iOS
- Browser: Firefox
- FFmpeg Version:
ffmpeg version 5.0.1-Jellyfin Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 10-win32 (GCC) 20220113
  configuration: --prefix=/opt/ffmpeg --arch=x86_64 --target-os=mingw32 --cross-prefix=x86_64-w64-mingw32- --pkg-config=pkg-config --pkg-config-flags=--static --extra-libs='-lfftw3 -lstdc++' --extra-cflags=-DCHROMAPRINT_NODLL --extra-version=Jellyfin --disable-ffplay --disable-debug --disable-doc --disable-sdl2 --disable-ptx-compression --disable-w32threads --enable-pthreads --enable-shared --enable-lto --enable-gpl --enable-version3 --enable-schannel --enable-iconv --enable-libxml2 --enable-zlib --enable-lzma --enable-gmp --enable-chromaprint --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libass --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libwebp --enable-libvpx --enable-libzimg --enable-libx264 --enable-libx265 --enable-libdav1d --enable-libfdk-aac --enable-opencl --enable-dxva2 --enable-d3d11va --enable-amf --enable-libmfx --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc

- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nyanmisaka** [comment]
Can you share a 1 minute clip of the DivX/Xvid video?

`ffmpeg -i DivX.mp4 -c:v copy -an -sn -t 60 -y clip.mp4`

**Comment by ThomasPGH** [comment]
Unfortunately I couldn't find anything that short in DivX or Xvid. I'll try to find a short example later.
Here's the full log of a (longer) file:

/videos/77ebb238-7562-4a12-ca34-7ac0f95ebe28/hls1/main/0.ts

{"Protocol":0,"Id":"77ebb23875624a12ca347ac0f95ebe28","Path":"M:\\Media\\Shorts\\tgsoe\\tgsoe.avi","EncoderPath":null,"EncoderProtocol":null,"Type":0,"Container":"avi","Size":1723561984,"Name":"tgsoe","IsRemote":false,"ETag":"09db2c72c028d79fb28c1a30bfd34650","RunTimeTicks":91519019020,"ReadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"OpenToken":null,"RequiresClosing":false,"LiveStreamId":null,"BufferMs":null,"RequiresLooping":false,"SupportsProbing":true,"VideoType":0,"IsoType":null,"Video3DFormat":null,"MediaStreams":[{"Codec":"mpeg4","CodecTag":"XVID","Language":null,"ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"Comment":null,"TimeBase":"125/2997","CodecTimeBase":null,"Title":null,"VideoRange":"SDR","LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"DisplayTitle":"480p MPEG4 SDR","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":1433798,"BitDepth":8,"RefFrames":1,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":false,"IsForced":false,"Height":464,"Width":640,"AverageFrameRate":23.976,"RealFrameRate":23.976,"Profile":"Advanced Simple Profile","Type":1,"AspectRatio":"4:3","Index":0,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":"yuv420p","Level":5,"IsAnamorphic":null},{"Codec":"mp3","CodecTag":null,"Language":null,"ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"Comment":null,"TimeBase":"3/125","CodecTimeBase":null,"Title":null,"VideoRange":null,"LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"DisplayTitle":"MP3 - Mono","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":"mono","BitRate":60128,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":1,"SampleRate":48000,"IsDefault":false,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":0,"AspectRatio":null,"Index":1,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null}],"MediaAttachments":[],"Formats":[],"Bitrate":1506626,"Timestamp":null,"RequiredHttpHeaders":{},"TranscodingUrl":null,"TranscodingSubProtocol":null,"TranscodingContainer":null,"AnalyzeDurationMs":null,"DefaultAudioStreamIndex":null,"DefaultSubtitleStreamIndex":null}

C:\Program Files\Jellyfin\Server\ffmpeg.exe -analyzeduration 200M -init_hw_device d3d11va=dx11:,vendor=0x1002 -init_hw_device opencl=ocl@dx11 -filter_hw_device ocl -hwaccel d3d11va -hwaccel_output_format d3d11 -autorotate 0 -i file:"M:\Media\Shorts\tgsoe\tgsoe.avi" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_amf -quality speed -rc cbr -qmin 0 -qmax 32 -b:v 3584495 -maxrate 3584495 -bufsize 7168990 -profile:v:0 high -level 51 -g:v:0 72 -keyint_min:v:0 72 -vf "setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,hwmap=derive_device=opencl,scale_opencl=format=nv12,hwmap=derive_device=d3d11va:reverse=1,format=d3d11" -codec:a:0 libmp3lame -ac 1 -ab 60128 -ar 48000 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "D:\ProgramData\Jellyfin\Server\transcodes\481b1136c3865367207856ffcbb485d3%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "D:\ProgramData\Jellyfin\Server\transcodes\481b1136c3865367207856ffcbb485d3.m3u8"


ffmpeg version 5.0.1-Jellyfin Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 10-win32 (GCC) 20220113
  configuration: --prefix=/opt/ffmpeg --arch=x86_64 --target-os=mingw32 --cross-prefix=x86_64-w64-mingw32- --pkg-config=pkg-config --pkg-config-flags=--static --extra-libs='-lfftw3 -lstdc++' --extra-cflags=-DCHROMAPRINT_NODLL --extra-version=Jellyfin --disable-ffplay --disable-debug --disable-doc --disable-sdl2 --disable-ptx-compression --disable-w32threads --enable-pthreads --enable-shared --enable-lto --enable-gpl --enable-version3 --enable-schannel --enable-iconv --enable-libxml2 --enable-zlib --enable-lzma --enable-gmp --enable-chromaprint --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libass --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libwebp --enable-libvpx --enable-libzimg --enable-libx264 --enable-libx265 --enable-libdav1d --enable-libfdk-aac --enable-opencl --enable-dxva2 --enable-d3d11va --enable-amf --enable-libmfx --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
  libavdevice    59.  4.100 / 59.  4.100
  libavfilter     8. 24.100 /  8. 24.100
  libswscale      6.  4.100 /  6.  4.100
  libswresample   4.  3.100 /  4.  3.100
  libpostproc    56.  3.100 / 56.  3.100
[AVHWDeviceContext @ 00000145d294cec0] Using device 1002:15dd (AMD Radeon(TM) Vega 8 Graphics).
Input #0, avi, from 'file:M:\Media\Shorts\tgsoe\tgsoe.avi':
  Metadata:
    software        : VirtualDubMod 1.5.10.2 (build 2540/release)
  Duration: 02:32:31.90, start: 0.000000, bitrate: 1506 kb/s
  Stream #0:0: Video: mpeg4 (Advanced Simple Profile) (XVID / 0x44495658), yuv420p, 640x464 [SAR 1:1 DAR 40:29], 1433 kb/s, 23.98 fps, 23.98 tbr, 23.98 tbn
  Stream #0:1: Audio: mp3 (U[0][0][0] / 0x0055), 48000 Hz, mono, fltp, 60 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (mpeg4 (native) -> h264 (h264_amf))
  Stream #0:1 -> #0:1 (mp3 (mp3float) -> mp3 (libmp3lame))
Press [q] to stop, [?] for help
[AVHWFramesContext @ 00000145dc9e1900] Only fixed-size pools are supported for D3D11 to OpenCL mapping.
[Parsed_hwmap_3 @ 00000145d2971e80] Failed to create derived source frames context: -22.
[Parsed_hwmap_3 @ 00000145d2971e80] Failed to configure output pad on Parsed_hwmap_3
Error reinitializing filters!
Failed to inject frame into filter network: Invalid argument
Error while processing the decoded data for stream #0:0
[libmp3lame @ 00000145d2970740] 6 frames left in the queue on closing
Conversion failed!

**Comment by ThomasPGH** [comment]
I found this example on the net:
https://software-download.name/sample-xvid-video-file/dl/xvid-sample-video.zip
This is the log file for it:

/videos/193d7fbb-8df4-33b2-43e7-cd270cf764fe/hls1/main/0.ts

{"Protocol":0,"Id":"193d7fbb8df433b243e7cd270cf764fe","Path":"M:\\Media\\Shorts\\tgsoe\\xvid.avi","EncoderPath":null,"EncoderProtocol":null,"Type":0,"Container":"avi","Size":7327744,"Name":"xvid","IsRemote":false,"ETag":"59e0886c50572e597fc888dc1fef4b84","RunTimeTicks":1800004710,"ReadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"OpenToken":null,"RequiresClosing":false,"LiveStreamId":null,"BufferMs":null,"RequiresLooping":false,"SupportsProbing":true,"VideoType":0,"IsoType":null,"Video3DFormat":null,"MediaStreams":[{"Codec":"mpeg4","CodecTag":"XVID","Language":null,"ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"Comment":null,"TimeBase":"64447/1000000","CodecTimeBase":null,"Title":null,"VideoRange":"SDR","LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"DisplayTitle":"720p MPEG4 SDR","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":203654,"BitDepth":8,"RefFrames":1,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":false,"IsForced":false,"Height":600,"Width":800,"AverageFrameRate":15.516626,"RealFrameRate":15,"Profile":"Simple Profile","Type":1,"AspectRatio":"4:3","Index":0,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":"yuv420p","Level":3,"IsAnamorphic":null},{"Codec":"mp3","CodecTag":null,"Language":null,"ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"Comment":null,"TimeBase":"1/14522","CodecTimeBase":null,"Title":null,"VideoRange":null,"LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"DisplayTitle":"MP3 - Mono","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":"mono","BitRate":116176,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":1,"SampleRate":22050,"IsDefault":false,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":0,"AspectRatio":null,"Index":1,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null}],"MediaAttachments":[],"Formats":[],"Bitrate":325676,"Timestamp":null,"RequiredHttpHeaders":{},"TranscodingUrl":null,"TranscodingSubProtocol":null,"TranscodingContainer":null,"AnalyzeDurationMs":null,"DefaultAudioStreamIndex":null,"DefaultSubtitleStreamIndex":null}

C:\Program Files\Jellyfin\Server\ffmpeg.exe -analyzeduration 200M -init_hw_device d3d11va=dx11:,vendor=0x1002 -init_hw_device opencl=ocl@dx11 -filter_hw_device ocl -hwaccel d3d11va -hwaccel_output_format d3d11 -autorotate 0 -i file:"M:\Media\Shorts\tgsoe\xvid.avi" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_amf -quality speed -rc cbr -qmin 0 -qmax 32 -b:v 1527405 -maxrate 1527405 -bufsize 3054810 -profile:v:0 high -level 51 -g:v:0 45 -keyint_min:v:0 45 -vf "setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,hwmap=derive_device=opencl,scale_opencl=format=nv12,hwmap=derive_device=d3d11va:reverse=1,format=d3d11" -codec:a:0 libmp3lame -ac 1 -ab 116176 -ar 22050 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "D:\ProgramData\Jellyfin\Server\transcodes\ad4b0b6f495354b1fd5c6d672304ad94%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "D:\ProgramData\Jellyfin\Server\transcodes\ad4b0b6f495354b1fd5c6d672304ad94.m3u8"


ffmpeg version 5.0.1-Jellyfin Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 10-win32 (GCC) 20220113
  configuration: --prefix=/opt/ffmpeg --arch=x86_64 --target-os=mingw32 --cross-prefix=x86_64-w64-mingw32- --pkg-config=pkg-config --pkg-config-flags=--static --extra-libs='-lfftw3 -lstdc++' --extra-cflags=-DCHROMAPRINT_NODLL --extra-version=Jellyfin --disable-ffplay --disable-debug --disable-doc --disable-sdl2 --disable-ptx-compression --disable-w32threads --enable-pthreads --enable-shared --enable-lto --enable-gpl --enable-version3 --enable-schannel --enable-iconv --enable-libxml2 --enable-zlib --enable-lzma --enable-gmp --enable-chromaprint --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libass --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libwebp --enable-libvpx --enable-libzimg --enable-libx264 --enable-libx265 --enable-libdav1d --enable-libfdk-aac --enable-opencl --enable-dxva2 --enable-d3d11va --enable-amf --enable-libmfx --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
  libavdevice    59.  4.100 / 59.  4.100
  libavfilter     8. 24.100 /  8. 24.100
  libswscale      6.  4.100 /  6.  4.100
  libswresample   4.  3.100 /  4.  3.100
  libpostproc    56.  3.100 / 56.  3.100
[AVHWDeviceContext @ 000002bf95bacec0] Using device 1002:15dd (AMD Radeon(TM) Vega 8 Graphics).
[avi @ 000002bf955cc440] non-interleaved AVI
Input #0, avi, from 'file:M:\Media\Shorts\tgsoe\xvid.avi':
  Duration: 00:03:00.00, start: 0.000000, bitrate: 325 kb/s
  Stream #0:0: Video: mpeg4 (Simple Profile) (XVID / 0x44495658), yuv420p, 800x600 [SAR 1:1 DAR 4:3], 203 kb/s, 15.52 fps, 15 tbr, 15.52 tbn
  Stream #0:1: Audio: mp3 (U[0][0][0] / 0x0055), 22050 Hz, mono, fltp, 116 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (mpeg4 (native) -> h264 (h264_amf))
  Stream #0:1 -> #0:1 (mp3 (mp3float) -> mp3 (libmp3lame))
Press [q] to stop, [?] for help
[libmp3lame @ 000002bf95bdd900] Queue input is backward in time
    Last message repeated 4 times
[AVHWFramesContext @ 000002bfa01f6080] Only fixed-size pools are supported for D3D11 to OpenCL mapping.
[Parsed_hwmap_3 @ 000002bf95bb2c80] Failed to create derived source frames context: -22.
[Parsed_hwmap_3 @ 000002bf95bb2c80] Failed to configure output pad on Parsed_hwmap_3
Error reinitializing filters!
Failed to inject frame into filter network: Invalid argument
Error while processing the decoded data for stream #0:0
[libmp3lame @ 000002bf95bdd900] 4 frames left in the queue on closing
Conversion failed!

**Comment by nyanmisaka** [comment]
Thanks, that's enough. Can you disable HW decoding for MPEG4 and try again?

**Comment by ThomasPGH** [comment]
This works.

**Comment by ThomasPGH** [comment]
Thanks!
