### ISSUE TITLE
Create Jellyfin.app for macOS

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin#793]
**Describe the feature you'd like**
A single package that users can download, which contains `Jellyfin.app`. Once placed in the /Applications folder, it can then be launched. Like Emby's package, this would not have a visible terminal window showing the app, but there would be a tray icon to launch the Web UI/stop the app, etc.

**Additional context**
Some light research shows that Emby uses Electron for the tray portion of the app: https://emby.media/community/index.php?/topic/64430-process-called-open/

I'm still uncertain how the rest of it is called.

Eventually, we'll also want to see if we can get this signed by Apple to avoid Gatekeeper restrictions (This will be a separate issue, as long as this is allowed by the license).

**Comment by BananaManCJ** [comment]
I would also like this feature.

**Comment by anthonylavado** [comment]
I don't want to promise the world just yet, but... I've made some good headway on this and I'm working on getting it up to spec.

Current Todo List (subject to change, will move to project soon):

- [ ] Make all menu items in test app work
- [ ] Handle all startup arguments, and persist them across restarts of app
- [ ] Add a start on login option
- [ ] Control whether Web UI launches on startup or not
- [ ] Bundle Jellyfin inside the app resources
- [ ] Bundle FFmpeg in the app resources
- [ ] Set startup arguments to point to internal FFmpeg
- [ ] Create advanced/hidden menu to open log folder

Future Todo list:
- [ ] Investigate sandboxing options
- [ ] Investigate Gatekeeper/Code signing for easier distribution
- [ ] Investigate easy packaging methods for fast updates when a new release of Jellyfin arrives

**Comment by DrPandemic** [comment]
>  Investigate easy packaging methods for fast updates when a new release of Jellyfin arrives

Maybe `brew` could be a good candidate. I heard horror stories about the mac app store, I don't know if it's now better.

**Comment by anthonylavado** [comment]
@DrPandemic I should rephrase that. I meant "How can we automate building the .app with an updated copy of Jellyfin when we create a release".

**Comment by anthonylavado** [comment]
Tracking further progress of this in its own repo: https://github.com/jellyfin/jellyfin-server-macos
