### ISSUE TITLE
[Issue]: Changing metadata path in web client doesn't work as expected

### ISSUE THREAD

**Issue by Germs2004** [jellyfin/jellyfin#7931]
### Please describe your bug

**Problem:**
I'm trying to move my Jellyfin folders to a different location.  When I edit the metadata path in dashboardgeneral.html, and move my metadata folder to the new location, Jellyfin fails to load any metadata from the new location.  Even if I edit the database directly to replace some values in TypedBaseItems with the new path, same problem.  It seems Jellyfin must have multiple references to the old path that are not updated properly when I edited the path in the web client.

I don't know how accurate this workaround guide is (https://github.com/jellyfin/jellyfin/discussions/6924), but it's far too complicated for most people to follow.

**What should happen:**
When a user changes their metadata path, Jellyfin should automatically move the current metadata files to the new location, and update everything (database, files) that needs to be updated so that everything works seamlessly.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Windows 11 Pro
- Virtualization: no
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cvium** [comment]
Well-known quirk but it's not a bug per se.
