### ISSUE TITLE
[Issue]: Taiwan is not a country

### ISSUE THREAD

**Issue by an0i** [jellyfin/jellyfin#7937]
### Please describe your bug

Emby.Server.Implementations/Localization/countries.json
"Taiwan" -> "Taiwan, China"

### Jellyfin Version

10.8.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joshuaboniface** [comment]
It has an ISO code, so it's a country for our purposes, and is in our list. As are Armenia and Palestine. While we don't currently include any other obvious disputed states (South Sudan, Ossetia, etc.), we're also missing plenty of "undisputed" states too, so this does not set a precedent. This is not a bug.
