### ISSUE TITLE
[Issue]: Some Shows Are Not Included in Next Up

### ISSUE THREAD

**Issue by dannymichel** [jellyfin/jellyfin#7938]
### Please describe your bug

[1]When you click a show, the next episode up does not show.
https://localhost:8096/web/#/details?id=<show id>&<server id>

[2]When you go to the next up page, the aformentioned show is not listed 
https://localhost:8096/web/#/list.html?type=nextup&serverId=

[3]When you mark an episode as watched and there are a number of episodes following that episode, it doesn't show up for [1] or [2] or on the front page for next up

What i've tried:
Unmarking an episode as watched and remarking it as watched
Deleting all plugins
Unmarking every show in every season as unwatched then marking just one episode as watched.
Refreshing metadata for that show
Confirming episode and season number for that show
Deleting that show and replacing it under a new folder with a new name
Separating specials from seasons
Including specials with seasons
Deleting all *extras* and trailers from shows
Using the previously watched option in next up.

What i've ruled out:
Shows with *other* and *trailers* folders
Shows with *specials*

What I know:
When using the option to show previously watched in next up, random episodes of these problem shows will appear.
When you unmark every episode of these problem shows as watched, enable previously watched and proceed to mark episodes as watched, episodes in complete random order from that show will appear as next up

Image for page [1] 
<img width="1255" alt="1" src="https://user-images.githubusercontent.com/1161544/173763334-8f38eeac-0588-4920-b525-741138e490b5.png">

Image for page [2]
<img width="1250" alt="2" src="https://user-images.githubusercontent.com/1161544/173763367-6e628cb0-8029-4997-af4e-aff072138907.png">

Image for page [3]
<img width="1253" alt="3" src="https://user-images.githubusercontent.com/1161544/173763400-7851730e-f546-4833-81a7-7eed5fdfe6c2.png">

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Linux/Ubuntu
- Virtualization: Docker
- Clients: Any
- Browser: Any
- Plugins: None
- Reverse Proxy: Nginx
- Storage: Rclone/GDrive/Mergerfs
```

### Please attach any screenshots here

Image for page [1] 
<img width="1255" alt="1" src="https://user-images.githubusercontent.com/1161544/173763334-8f38eeac-0588-4920-b525-741138e490b5.png">

Image for page [2]
<img width="1250" alt="2" src="https://user-images.githubusercontent.com/1161544/173763367-6e628cb0-8029-4997-af4e-aff072138907.png">

Image for page [3]
<img width="1253" alt="3" src="https://user-images.githubusercontent.com/1161544/173763400-7851730e-f546-4833-81a7-7eed5fdfe6c2.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by thornbill** [comment]
1. Based on your screenshots this is very clearly Veso (your hard fork of Jellyfin). We do not provide support for forks here. If you are able to reproduce the issue in **Jellyfin**, please open a new issue with the steps outlined as you did here.
2. It also appears you are using a build of unstable not 10.8.0 based on the information provided.
3. Please include any relevant settings you have changed (i.e. including rewatching in next up).
