### ISSUE TITLE
[Issue]: No option to choose "none" when correcting channel mappings

### ISSUE THREAD

**Issue by mdsmithspangler1130** [jellyfin/jellyfin#7949]
### Please describe your bug

 I am not sure if this is a bug or if there is something I am doing on my end that is causing this. So I am using the live tv feature using the HDHomeRun option pulling from Xteve. I use SchedulesDirect along with an xmltv source for my epg data. SchedulesDirect tries to auto map the channels which is fine, but I am running into an issue where it maps some channels incorrectly because SchedulesDirect doesn't have guide data for it. Jellyfin won't allow me to unselect the guide data it assigned without selecting another guide data source. This becomes an issue because some of the channels I only want to use guide data from the xmltv source but can't since Jellyfin has already assigned it in SchedulesDirect, so now it shows up with the incorrect information on the tv guide. Basically Jellyfin doesn't give me an option for no epg when assigning guide data, and I think that is what I need in this case.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Windows Server Running inside of VMWare ESXi
- Virtualization: N/A (Using the Jellyfin server program for windows.
- Clients: Browser, Android, Roku, AppleTV, Google TV Hub, iOS
- Browser: Chrome, Safari, Microsoft Edge
- FFmpeg Version: The default that is installed with Jellyfin
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mdsmithspangler1130** [comment]
If possible, it would be nice to be able to set a primary and a secondary epg source. So one epg source is used first, and if it can't pull data for a channel, then try using the secondary epg source before displaying no data.

**Comment by crobibero** [comment]
> If possible, it would be nice to be able to set a primary and a secondary epg source. So one epg source is used first, and if it can't pull data for a channel, then try using the secondary epg source before displaying no data.

https://features.jellyfin.org
