### ISSUE TITLE
exec vanished, drive letter reversion[Issue]: 

### ISSUE THREAD

**Issue by jimlynnjulian** [jellyfin/jellyfin#7962]
### Please describe your bug

Did a pre-boot check for Jellyfin and made a couple of discoveries.
1. One of the drives for which I had assigned a sequential letter had reverted to a Windows choice.
2.  The executable, 'Jellyfin.Windows.Tray.exe'm had disappeared.
Is there a condition under which Jellyfin deletes the exec?
I checked Windows Virus mechanism and there's no indication of any perceived threat. 
I keep most security mechanisms turned off.
Version 10.8.0
Can I re-install without losing data?
I'm trying a simple drop-in of the executable.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
Jellyfin does not delete the the tray app.
It is a direct install / upgrade by running the new installer

**Comment by jimlynnjulian** [comment]
> Jellyfin does not delete the the tray app. It is a direct install / upgrade by running the new installer

I copied files from a download into the Server directory and got things running. Have know idea why the file was deleted or by whom.
