### ISSUE TITLE
[Issue]: Playlists are not synchronized with Kodi

### ISSUE THREAD

**Issue by update-freak** [jellyfin/jellyfin#7970]
### Please describe your bug

Playlists (e.g. on NAS at volume1/music/playlists/Last Three Years.m3u) are shown in Jellyfin on Browser, but not in Kodi (connected with Jellyfin Addon)

Steps to reproduce:
1. Create a playlist, e.g. with VirtualDJ and store the m3u on NAS
2. Jellyfin found this playlist (it is shown online)
3. Start Kodi and wait for the Jellyfin-Sync
4. result: you see the playlist not on Kodi

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS:Windows and LibreELEC
- Virtualization: Docker
- Clients: Browser
- Browser: Chrome 102
```

### Please attach any screenshots here

Playlist in Browser:
![playlist jellyfin browser](https://user-images.githubusercontent.com/40196995/174497666-3e8db5e3-65c4-4374-8bbc-aebc969163d7.png)

Playlists in Kodi (with Jellyfin Addon):
![playlist kodi](https://user-images.githubusercontent.com/40196995/174497677-8230f50f-138c-4fc7-b50e-ed1a19d57004.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by update-freak** [comment]
Is it not possible to use a m3u with the following songs that this playlist will be recognized in Kodi with Jellyfin Plugin?

```
../Music/Lost Frequencies - Where Are You Now.flac
../Music/Imanbek - Hey Baby.flac
../Music/Loud Luxury - Aftertaste.flac
../Music/Calvo - No Scrubs (Jolyon Petch Remix).flac
../Music/Christopher Damas - Mr. Colin.flac
```

**Comment by Bond-009** [comment]
https://github.com/jellyfin/jellyfin-kodi/issues/175
