### ISSUE TITLE
Disable remove media from library Or give option to user

### ISSUE THREAD

**Issue by sourpatched** [jellyfin/jellyfin#7973]
As per https://github.com/jellyfin/jellyfin/issues/3517
My hard drive "failed" and Jellyfin removed everything on that drive from the library db. I've fixed the drive and it now working however now it's spent the past hour scanning it. 

Would it be possible to have user input before anything is removed from the database or give option to set clean up time?

**Comment by crobibero** [comment]
This is not currently possible. 

Feature requests belong at https://features.jellyfin.org/
