### ISSUE TITLE
[Issue]: Jellyfin sometimes ignores the presence of a .ignore file.

### ISSUE THREAD

**Issue by DexLuther** [jellyfin/jellyfin#7986]
Folders with an .ignore file present are often scanned into the library anyway resulting in unwanted content in the library and other events to trigger such as unwanted and/or premature Notifications.

**Steps to Reproduce**:
1. Have content not previously scanned into the Library.
2. Add an .ignore file inside the media folder.
3. Move the media folder into an appropriate Watched folder.

**Expected Results**:
- The .ignore file functions properly and prevents the folder from being scanned and added to the library as described here: https://support.emby.media/support/solutions/articles/44001159118-excluding-files-folders

**Actual Results**:
- The .ignore file is ignored and the media is scanned into the library.

**Notes**:

- The .ignore file seems to function most often when a folder is already scanned into the library, an .ignore file is added and then a `Refresh Metadata > Scan for new and updates files` is performed. The content is then removed from the library and not scanned again.
-  This issue technically duplicates #5135, but was closed as fixed.

### Jellyfin Version

10.8.0

### if other:

10.7.7

### Environment

```markdown
- OS: Windows 10 (64-bit)
- Virtualization: None
- Clients: N/A
- Browser: N/A
- FFmpeg Version: N/A
- Playback Method: N/A
- Hardware Acceleration: N/A
- Plugins: TVDB and other metadata plugins
- Reverse Proxy: None
- Base URL:none
- Networking:Host
- Storage:Local
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JakeHL** [comment]
I am also experiencing this issue.
