### ISSUE TITLE
[Issue]: Cannot play .avi files

### ISSUE THREAD

**Issue by umbongodrink** [jellyfin/jellyfin#7989]
### Please describe your bug

I have an Intel NUC8i3BEH 32GB RAM running Ubuntu 20.04LTS machine, which hosts my bare-metal Jellyfin installation. I have 2 Jellyfin clients, one is installed on a nVidia Shield Pro, the other is installed on a Sony Bravia TV. Both run Jellyfin client 0.13.6 on AndroidTV. 

I am trying to play .avi files. The output of MediaInfo is here:
```
General
Complete name                            : /Users/k/Desktop/Melrose.Place.S01E05.avi
Format                                   : AVI
Format/Info                              : Audio Video Interleave
File size                                : 349 MiB
Duration                                 : 43 min 12 s
Overall bit rate                         : 1 128 kb/s
Writing application                      : VirtualDubMod 1.5.10.2 (build 2540/release)
Writing library                          : VirtualDubMod build 2540/release

Video
ID                                       : 0
Format                                   : MPEG-4 Visual
Format profile                           : Advanced Simple@L5
Format settings                          : BVOP1
Format settings, BVOP                    : 1
Format settings, QPel                    : No
Format settings, GMC                     : No warppoints
Format settings, Matrix                  : Default (H.263)
Muxing mode                              : Packed bitstream
Codec ID                                 : XVID
Codec ID/Hint                            : XviD
Duration                                 : 43 min 12 s
Bit rate                                 : 990 kb/s
Width                                    : 640 pixels
Height                                   : 480 pixels
Display aspect ratio                     : 4:3
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Compression mode                         : Lossy
Bits/(Pixel*Frame)                       : 0.134
Stream size                              : 306 MiB (88%)
Writing library                          : XviD 1.1.0 (UTC 2005-11-22)

Audio
ID                                       : 1
Format                                   : MPEG Audio
Format version                           : Version 1
Format profile                           : Layer 3
Format settings                          : Joint stereo / MS Stereo
Codec ID                                 : 55
Codec ID/Hint                            : MP3
Duration                                 : 43 min 12 s
Bit rate mode                            : Constant
Bit rate                                 : 128 kb/s
Channel(s)                               : 2 channels
Sampling rate                            : 48.0 kHz
Compression mode                         : Lossy
Stream size                              : 39.6 MiB (11%)
Alignment                                : Aligned on interleaves
Interleave, duration                     : 42  ms (1.00 video frame)
Interleave, preload duration             : 504  ms
```

When my Jellyfin server was running version 10.7.7, the avi file would play fine on the nVidia Shield Pro Jellyfin client, but not on the Sony Brava TV Jellyfin client. 

Now I have upgraded my server to version 10.8.0 and the .avi file does not play on either the nVidia Shield Pro nor the Sony Brava TV. In both instances I receive the error message: 

```
Player error encountered. Will re-try...
Too many errors. Giving up.
```

It is very curious as to why this file used to be able to be played, and now isn't playable at all. 

I have tried changing the Preferred media player from ExoPlayer to LibVLC but this doesn't make any difference for either client. I believe when the file used to be able to be played on the nVidia Shield Pro the Preferred media player was set to LibVLC, but now neither media player will play back the file. 

The file is a relatively old format, so should be easily playable by a modern piece of software such as Jellyfin I would have thought. 

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Ubuntu 20.04LTS
- Virtualization:
- Clients: AndroidTV with Jellyfin 0.13.6 (on both nVidia Shield Pro and Sony Bravia TV platforms)
- Browser:
- FFmpeg Version:
- Playback Method: (no transcoding)
- Hardware Acceleration: none
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking: Ethernet
- Storage: Local
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shadowghost** [comment]
Please add Jellyfin logs from the failing playback to your post.

**Comment by cskaryd** [comment]
Not O.P., but having the same issue:

[2022-06-21 11:43:48.443 -04:00] [INF] [30] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "{redacted}". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2022-06-21 11:43:48.445 -04:00] [INF] [30] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile="Anonymous Profile", Path="{redacted}.avi", AudioStreamIndex=1, SubtitleStreamIndex=-1 ) => ( PlayMethod=Transcode, TranscodeReason=VideoCodecNotSupported ) "media:/videos/2a4cd7bb-0ad8-97a1-6596-b2455d43283e/master.m3u8?MediaSourceId=2a4cd7bb0ad897a16596b2455d43283e&VideoCodec=h264,mpeg2video,h265,hevc&AudioCodec=aac,ac3&AudioStreamIndex=1&VideoBitrate=139936000&AudioBitrate=64000&MaxFramerate=29.97&api_key=<token>&SubtitleMethod=Encode&TranscodingMaxAudioChannels=6&RequireAvc=false&Tag=fe5001339a00b958fb68bd0d19387f87&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&mpeg4-level=-99&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51&aac-audiochannels=6&TranscodeReasons=VideoCodecNotSupported"
[2022-06-21 11:43:49.193 -04:00] [INF] [192] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Jellyfin Roku" "1.4.12" playing "{redacted}". Stopped at "0" ms

**Comment by umbongodrink** [comment]
> Please add Jellyfin logs from the failing playback to your post.

Sure, can you please direct me to what exactly you want, and where. 
Also, do you only want the logs for the Jellyfin server (and not either of the clients)? 

I have tailed the last 500 lines of /var/log/jellyfin/jellyfin20220626.log and attached them here.
[last500lines_from_jellyfin.log.txt](https://github.com/jellyfin/jellyfin/files/8987320/last500lines_from_jellyfin.log.txt)

**Comment by bt0070069** [comment]
I'm also having the same issue. 

My jellyfin server is version 10.8.5 installed in a docker container on a Synology DiskStation DS220+.

An .avi file (XVID/MP3) will no longer play using Jellyfin for Android TV version 0.14.4.

The problem began when I updated my server from 10.7.x and the client to 0.14.x

I guess the newer clients have dropped support for older codecs.

Unfortunately the only fix I've found is to use handbrake to convert the .avi files (XVID/MP3) to .mp4 files (H264/AAC). Been at it for weeks now. Judging by the date of this thread, I'll be done before a solution is rolled out.

**Comment by cskaryd** [comment]
> I'm also having the same issue.
> 
> My jellyfin server is version 10.8.5 installed in a docker container on a Synology DiskStation DS220+.

I solved my problem above back in June by ensuring that I was using the correct version of both ffmpeg and ffprobe.  While I had installed the versions from the Jellyfin repos, the standard versions from Ubuntu were also installed and being used by the service.  Be sure to set the explicit path to the Jellyfin version of ffmpeg by going to the hamburger menu in the upper left, then Dashboard, then Playback, and find the FFmpeg path setting.  For me that was /usr/lib/jellyfin-ffmpeg/ffmpeg rather than /usr/bin/ffmpeg

Hope that helps.

**Comment by bt0070069** [comment]
Unfortunately my FFmpgeg path was already /usr/lib/jellyfin-ffmpeg/ffmpeg, but thank you for your reply. 

I have completed converting all my old .avi files to .mp4; at least the ones that couldn't be re-downloaded in .mp4 or .mkv containers, so this is no longer an issue for me.

**Comment by cskaryd** [comment]
> Unfortunately my FFmpgeg path was already /usr/lib/jellyfin-ffmpeg/ffmpeg

Only other thought would be permissions and owner/group.  I found my problem buried in a cryptic log message.

But glad you got sorted one way or another.

**Comment by bt0070069** [comment]
It's got to be an issue with the Jellyfin for Android TV app, rather than the server side, as the .avi files will play on the Jellyfin for Ubuntu (flatpak) app.

**Comment by gmpreussner** [comment]
AVI playback is still broken in 10.8.10.

You guys really gotta stop auto-closing tickets if there is nobody on the team to respond to these. Too many tickets for unresolved issues are being closed, which makes it look like everything should work fine, and users will end up creating new, duplicate tickets over and over again.

**Comment by ChrizZz90** [comment]
yes, still broken and only the AndroidTV version has trouble

**Comment by StoryHack** [comment]
I'm on 10.8.10, and I get the same issue. It' won't play from the roku, and it won't play from the browser, either.

**Comment by oliverlevay** [comment]
same, can't play older .avi movies on my tv

**Comment by Shadowghost** [comment]
If this is only specific to some clients please report it over there. Likely it is just a problem with their device profile.

**Comment by gmpreussner** [comment]
> It' won't play from the roku, and it won't play from the browser, either.

It's also broken in the web browser for me. Tried Chrome, Firefox, and Edge.

**Comment by gmpreussner** [comment]
I inspected the affected videos with FFMEPG, and in my case it seems that they are all older videos recorded with handheld photo cameras. Here's some example metadata:

```
Input #0, avi, from 'v:\TestVideo.AVI':
  Metadata:
    creation_time   : 2015-07-11 13:58:33
    software        : CanonMVI02
  Duration: 00:01:45.83, start: 0.000000, bitrate: 14984 kb/s
  Stream #0:0: Video: mjpeg (Baseline) (MJPG / 0x47504A4D), yuvj422p(pc, bt470bg/unknown/unknown), 640x480, 14895 kb/s, 30 fps, 30 tbr, 30 tbn
  Stream #0:1: Audio: pcm_u8 ([1][0][0][0] / 0x0001), 11024 Hz, 1 channels, u8, 88 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (mjpeg (native) -> mpeg4 (native))
  Stream #0:1 -> #0:1 (pcm_u8 (native) -> aac (native))
```

**Comment by Shadowghost** [comment]
Might be fixed by https://github.com/jellyfin/jellyfin/pull/10173
