### ISSUE TITLE
Build results in ImageMagick errors

### ISSUE THREAD

**Issue by joshuaboniface** [jellyfin/jellyfin#8]
@JustAMan wondering if you've hit this:

```dotnet publish --configuration Release /var/home/joshua/Projects/Emby/jellyfin/MediaBrowser.sln --output='/var/home/joshua/Projects/Emby/jellyfin/usr/lib/jellyfin/bin'```

```
ImageMagickEncoder.cs(2,7): error CS0246: The type or namespace name 'ImageMagickSharp' could not be found (are you mis
sing a using directive or an assembly reference?) [/var/home/joshua/Projects/Emby/jellyfin/Emby.Drawing.ImageMagick/Emb
y.Drawing.ImageMagick.csproj]
PercentPlayedDrawer.cs(1,7): error CS0246: The type or namespace name 'ImageMagickSharp' could not be found (are you mi
ssing a using directive or an assembly reference?) [/var/home/joshua/Projects/Emby/jellyfin/Emby.Drawing.ImageMagick/Em
by.Drawing.ImageMagick.csproj]
```
etc.

I suppose the `debian/rules` config is missing a step, any thoughts?

**Comment by joshuaboniface** [comment]
Oh I needed to initialize and grab the submodules.

**Comment by JustAMan** [comment]
Yes, submodules. Pls clone them to this organization as well, that should be a proper way.

**Comment by dcrdev** [comment]
Actually newer versions of Emby utilise skia and the only reason they package imagemagick directly was to prevent users having differing versions across platforms - imagemagick being particularly prone to abi changes.

Skia would be the way to go - it's available in nuget and would therefore negate the need to include it in this repository at all.

I'll do some work on a new server entry point at some point, that'll solve this.
