### ISSUE TITLE
Cannot run Jellyfin server without internet

### ISSUE THREAD

**Issue by guikubivan** [jellyfin/jellyfin#8011]
Server dies and I see in the logs the following:
![20220626_001102](https://user-images.githubusercontent.com/194133/175803571-5b035d4a-df23-491d-8a73-288e1440fe99.jpg)

**Comment by cvium** [comment]
Please fill out the issue template. And we do not support 10.7.x. _And_ that error is unrelated to whatever problem you have.

**Comment by guikubivan** [comment]
Ah I didn't know there was a newer version, will give it a go! Thank you!
