### ISSUE TITLE
[Issue]: Installer fails to upgrade to 10.8.1 on Windows 10

### ISSUE THREAD

**Issue by vsviridov** [jellyfin/jellyfin#8024]
### Please describe your bug

Installation starts but almost immediately following error appears:
![image](https://user-images.githubusercontent.com/221684/175993014-6e71196f-5c69-4dec-89e3-86cc03ac94da.png)

If "Ignore"d - same thing happens for the next file in the folder

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Windows 10
- Virtualization: None
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vsviridov** [comment]
The application installed in user mode (not service) was still running, and it looks like the installer didn't terminate it properly.

The tray icon was gone, but there were still residual `jellify.exe` processes in the system.

After killing them manually the installer was able to continue.

**Comment by nyanmisaka** [comment]
Installer issues should be opened at here: https://github.com/jellyfin/jellyfin-server-windows
