### ISSUE TITLE
[Issue]: Save artwork into media folders not working as expected for movies

### ISSUE THREAD

**Issue by mbhayden14** [jellyfin/jellyfin#8026]
### Please describe your bug

I have the 'Save artwork into media folders' option selected for each of my libraries, and before upgrading to 10.8.0/10.8.1, a 'folder.jpg' & 'backdrop.jpg' would be saved to the same location of the movie files each time you add & identify a new movie (along with automatically updating themselves when changing existing art work). After updating it seems to not be working; this is what happens:

- When adding a new movie (& identifying it), no new 'folder.jpg' & 'backdrop.jpg' are created in its media folder.
- When updating a existing movie's art work in the browser, the previous 'folder.jpg' & 'backdrop.jpg' in its media folder do not get updated. This makes it so the next time you run 'Scan Media Library' the artwork reverts back to its previous version that is still saved in the media folder.

I attempted to restart the Jellyfin application and also turn on and off the 'Save artwork into media folders' option, but it still isn't working.

### Jellyfin Version

Other

### if other:

10.8.1

### Environment

```markdown
- OS: Linux (Ubuntu)
- Virtualization: Docker
- Clients: Browser
- Browser: Brave/Chrome
- FFmpeg Version: N/A
- Playback Method: N/A
- Hardware Acceleration: N/A
- Plugins: none
- Reverse Proxy: none
- Base URL: none
- Networking: N/A
- Storage: local
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mbhayden14** [comment]
Still an issue as of 10.8.3

**Comment by Gh0st-drive** [comment]
Still an issue in 10.8.10
