### ISSUE TITLE
[Issue]: NextUp shows episodes on user creation

### ISSUE THREAD

**Issue by l4kr** [jellyfin/jellyfin#8029]
### Please describe your bug

Hi, I've been getting new NextUp shows on a brand new account creation. I even tried a new test server (without plugins or anything) and the issue persists so it seems like a pure Jellyfin issue.

To replicate: create a new user in Jellyfin, watch NextUp appear out of thin air.

### Jellyfin Version

Other

### if other:

10.8.1

### Environment

```markdown
- OS: Debian
- Virtualization: Docker
- Clients: All browsers
- Browser: Firefox, Chrome
- Storage: Docker volume
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cvium** [comment]
Working as intended. If a user has not watched anything, the first episode of every show will appear in Next Up. This can be disabled but the location of this option escapes me at the moment.
