### ISSUE TITLE
[Issue]: Dolby Vision to SDR - AMD GPU missing OpenCL drivers?

### ISSUE THREAD

**Issue by jpslv** [jellyfin/jellyfin#8030]
### Please describe your bug

Can't play DoVi profile 5 media files on **Jellyfin (v10.8.1)** installed via docker on **unRAID (v6.10.3)**.

When **tone mapping is enabled** I get the following error message:

> _"Playback Error. This client isn't compatible with the media and the server isn't sending a compatible media format."_

When **tone mapping is disabled** I can play the video but with all those greens and purples (see screenshots).

**Full ffmpeg log:** https://pastebin.com/586Y573H

Thank you for the amazing jellyfin software and for any help you can provide.

### Jellyfin Version

Other

### if other:

10.8.1

### Environment

```markdown
- OS: unRAID (v6.10.3)
- Docker app: Official Jellyfin
- Clients: Browser
- Browser: Firefox
- Playback Method: Transcode
- Hardware Acceleration: VAAPI
- GPU: AMD Ryzen™ 5 3400GE
```

### FFmpeg logs

```shell
ffmpeg version 5.0.1-Jellyfin Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-libs=-lfftw3f --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-static --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
  libavdevice    59.  4.100 / 59.  4.100
  libavfilter     8. 24.100 /  8. 24.100
  libswscale      6.  4.100 /  6.  4.100
  libswresample   4.  3.100 /  4.  3.100
  libpostproc    56.  3.100 / 56.  3.100
Input #0, matroska,webm, from 'file:/tv/1_tv_shows/Obi-Wan Kenobi (2022)/Season 1/Obi.Wan.Kenobi.S01E04.Part.IV.2160p.WEB-DL.DDP5.1.Atmos.DV.HEVC-PROPER.mkv':
  Metadata:
    encoder         : libebml v1.4.2 + libmatroska v1.6.4
  Duration: 00:36:23.46, start: 0.000000, bitrate: 22446 kb/s
  Chapters:
    Chapter #0:0: start 7.000000, end 94.833000
      Metadata:
        title           : Recap
    Chapter #0:1: start 94.833000, end 95.000000
      Metadata:
        title           : End of Recap
    Chapter #0:2: start 95.000000, end 120.792000
      Metadata:
        title           : Intro
    Chapter #0:3: start 120.792000, end 2084.000000
      Metadata:
        title           : End of Intro
    Chapter #0:4: start 2084.000000, end 2183.456000
      Metadata:
        title           : Credits
  Stream #0:0: Video: hevc (Main 10), yuv420p10le(pc), 3840x2160 [SAR 1:1 DAR 16:9], 24 fps, 24 tbr, 1k tbn
    Metadata:
      BPS             : 21674232
      DURATION        : 00:36:23.417000000
      NUMBER_OF_FRAMES: 52402
      NUMBER_OF_BYTES : 5915486051
      _STATISTICS_WRITING_APP: mkvmerge v68.0.0 ('The Curtain') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Side data:
      DOVI configuration record: version: 1.0, profile: 5, level: 6, rpu flag: 1, el flag: 0, bl flag: 1, compatibility id: 0
  Stream #0:1(eng): Audio: eac3, 48000 Hz, 5.1(side), fltp, 768 kb/s
    Metadata:
      BPS             : 768000
      DURATION        : 00:36:23.456000000
      NUMBER_OF_FRAMES: 68233
      NUMBER_OF_BYTES : 209611776
      _STATISTICS_WRITING_APP: mkvmerge v68.0.0 ('The Curtain') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
```

### Please attach any screenshots here

**Jellyfin version:**

![image](https://user-images.githubusercontent.com/95918883/176390659-00699138-32e1-4a21-b7d2-01290d784c02.png)

**Transcoding settings:**

![image](https://user-images.githubusercontent.com/95918883/176390744-cbdeb94f-a2a0-4c36-9e21-7ab2c0a7b21c.png)

**Tone mapping disabled:**

![image](https://user-images.githubusercontent.com/95918883/176390813-0fe35476-137c-4771-9e0f-41be954bacec.png)

**Video playback with tone mapping disabled:**

![image](https://user-images.githubusercontent.com/95918883/176391697-310807f3-b1cc-4e68-ad94-13caf9e3bc21.png)

**Tone mapping enabled:**

![image](https://user-images.githubusercontent.com/95918883/176393191-ef35dce4-fc98-49aa-8306-aa15b1f8410e.png)

**Video playback with tone mapping enabled:**

![image](https://user-images.githubusercontent.com/95918883/176393298-04dd5ead-e8d6-4f88-b8c0-b33da4d6f1e4.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shadofall** [comment]
> We don’t ship AMD’s OpenCL runtime within our container, which is too big and it’s legacy version is proprietary. You have to install it on your own.
> 
> https://jellyfin.org/docs/general/administration/hardware-acceleration.html#opencl--cuda--intel-vpp-tone-mapping
> 
> https://www.amd.com/en/support/kb/release-notes/rn-amdgpu-unified-linux-22-10-2
> 
> https://amdgpu-install.readthedocs.io/en/latest/

@nyanmisaka 

Define to big?  i would think most users would find it acceptable for the image to grow 100-200 MB for full AMD support instead of being told to buy intel/nvidia and written off or do it your self every time they need to update their docker image

or a choice between an AMD ready and non AMD ready image.

**Comment by nyanmisaka** [comment]
Not just because of the size, but because some parts of the amdgpu-pro OpenCL stack are proprietary and we can't include it in our official docker image.

Also we will move to the free Vulkan RADV in the future. #7708

**Comment by Shadowghost** [comment]
The problem is that you'd force all users of non-amd hardware to download additional data they don't need. Intel and Nvidia runtimes are way smaller so it's a non issue there.

**Comment by shadofall** [comment]
Closed Source i get, Its kinda annoying but i get it lol "eww closed source in my open source" Way it was worded it wasn't clear to me that legacy components of the OpenCL were proprietary. I read it as more. older smaller versions are proprietary

Thanks for the Clarifications on that part

But i'll stand by my opinion on size just being a slight inconvenience

**Comment by aviallon** [comment]
Correct me if I'm wrong, but ROCm OpenCL support is fully opensource, isn't it?

**Comment by aviallon** [comment]
Also, couldn't a docker mod be simply created for that?

**Comment by jpslv** [comment]
If someone could create a mod, it would be awesome!
