### ISSUE TITLE
[Issue]: Subfolder organization error

### ISSUE THREAD

**Issue by hnrazevedo** [jellyfin/jellyfin#8031]
### Please describe your bug

When adding videos in subfolders, the system is considering only the parent folder as Series Title and the child folder as Season Name, the subfolders of the first child are ignored in the tracking and the media are all grouped in the child folder.

Example directories:

```
School 1:
    - Course 1:
        - Class 1:
            - Class 1.1;
            - Class 1.2;
        - Class 2:
            - Class 2.1;
            - Class 2.2;
```

Exit on Jellyfin:

```
School 1:
    - Course 1:
        - Class 1.1;
        - Class 1.2;
        - Class 2.1;
        - Class 2.2;
```

I don't remember which version of Jellyfin I was on before but this didn't happen, it was like this after the distro update and d Jellyfin.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Debian 11.3
- Virtualization: No
- Clients: Navegador
- Browser: Chrome 96
- FFmpeg Version: 5.0.1-Jellyfin
- Playback Method: Direct
- Hardware Acceleration: No
- Plugins: no
- Reverse Proxy: nginx
- Base URL: no
- Networking: host
- Storage: local
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jojo141185** [comment]
This problem still exists for media scanners of type 'series'. 
Is there a plan to make the scanner more flexible regarding folder structure in the future?

**Comment by felix920506** [comment]
That is a feature request. Please submit them to https://features.jellyfin.org
