### ISSUE TITLE
[Issue]: `/System/Info` and `/System/Info/Public` endpoints seems to be taking either 5 or 15 seconds to respond behind Nginx

### ISSUE THREAD

**Issue by jarylc** [jellyfin/jellyfin#8032]
### Please describe your bug

`/System/Info` and `/System/Info/Public` endpoints seems to be taking either 5 or 15 seconds to respond behind Nginx

This causes Android and LG WebOS to time out when trying to access Jellyfin.

I have tried without SSL as well, same issue ruling the possibility of SSL being the issue out.

Other endpoints under `/System/` seems fine, tested:
1. `/System/Endpoint`
2. `/System/Configuration/network`

I have also tried to 1:1 match my Nginx configurations with https://jellyfin.org/docs/general/networking/nginx.html, but same issue.

My suspicion is on `GetSmartApiUrl`, but I will continue to test tomorrow.

### Jellyfin Version

Other

### if other:

10.8.1

### Environment

```markdown
- OS: Debian
- Virtualization: Docker
- Clients: Browser
- Browser: Firefox Nightly 103.0a1 (2022-06-04) (64-bit)
- Reverse Proxy: Nginx 1.20.2 built with OpenSSL 3.0.3 3 May 2022 (running with OpenSSL 3.0.4 21 Jun 2022)
- Base URL: None
- Networking: Host over Nginx
- Storage: Local
```

### Jellyfin logs

```shell
No useful logs
```

### FFmpeg logs

```shell
Not related to video playback
```

### Please attach any browser or client logs here

Over Nginx:
![image](https://user-images.githubusercontent.com/1162128/176529522-094dce74-b0c4-4cde-9f78-d7f8c1faec82.png)

Direct:
![image](https://user-images.githubusercontent.com/1162128/176529687-2803439a-6209-4280-b2cf-eefb67a99653.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jarylc** [comment]
Since I was using `linuxserver` image, I had to set the `JELLYFIN_PublishedServerUrl` environment variable and this was solved, it was indeed a problem with `GetSmartApiUrl`

**Comment by awsms** [comment]
I have the same issue, however I'm seeing a GET request in my network console, to $server_address:$jellyfin_port/system/info/public instead of the $domain_name/system/info/public format.
I'm using the nginx configuration from jellyfin that you linked in OP.
