### ISSUE TITLE
[Issue]: Unable to delete Recordings

### ISSUE THREAD

**Issue by stevenliuit** [jellyfin/jellyfin#8035]
### Please describe your bug

After I added the live TV m3u8 source and deleted it, there will be an additional recordings file in /data/livetv/recordings, and it will also appear in my media library and will appear again after a while.

### Jellyfin Version

Other

### if other:

10.8.1

### Environment

```markdown
- OS:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by viown** [comment]
I was able to fix this by removing the 'livetv' directory completely.

**Comment by stevenliuit** [comment]
> I was able to fix this by removing the 'livetv' directory completely.

me too
