### ISSUE TITLE
4K HEVC HDR on ChromeCast with Google TV

### ISSUE THREAD

**Issue by ArtyomFR** [jellyfin/jellyfin#8040]
**Media Info of the file**

>Vidéo
Titre: 4K HEVC HDR
Codec: HEVC
Profil: Main 10
Niveau: 150
Résolution: 3840x1608
Ratio d'aspect original: 2.40:1
Entrelacé: No
Images par seconde: 23.976025
Débit: 4441 kbps
Plage vidéo: HDR
Espace couleur: bt2020nc
Transfert couleur: smpte2084
Couleurs primaires: bt2020
Format de pixel: yuv420p10le
Images de référence: 1
Audio
Titre: VFF - Fre - AAC - 5.1 - Default
Langue: fre
Codec: AAC
Profil: HE-AAC
Répartition: 5.1
Chaînes: 6 ch
Débit: 210 kbps
Débit échantillon: 48000 Hz
Défaut: Yes
Forcé: No
Externe: No
Audio
Titre: VO - Eng - AAC - 5.1
Langue: eng
Codec: AAC
Profil: HE-AAC
Répartition: 5.1
Chaînes: 6 ch
Débit: 202 kbps
Débit échantillon: 48000 Hz
Défaut: No
Forcé: No
Externe: No

Or

>Vidéo
Titre: 4K HEVC HDR
Codec: HEVC
Profil: Main 10
Niveau: 150
Résolution: 3840x1606
Ratio d'aspect original: 2.40:1
Entrelacé: No
Images par seconde: 23.976025
Débit: 6493 kbps
Plage vidéo: HDR
Espace couleur: bt2020nc
Transfert couleur: smpte2084
Couleurs primaires: bt2020
Format de pixel: yuv420p10le
Images de référence: 1
Audio
Titre: FR VFF : AAC 5.1 - Fre - Default
Langue: fre
Codec: AAC
Profil: LC
Répartition: 5.1
Chaînes: 6 ch
Débit: 371 kbps
Débit échantillon: 48000 Hz
Défaut: Yes
Forcé: No
Externe: No
Audio
Titre: ENG VO : AAC 7.1
Langue: eng
Codec: AAC
Profil: LC
Répartition: 7.1
Chaînes: 8 ch
Débit: 438 kbps
Débit échantillon: 48000 Hz
Défaut: No
Forcé: No
Externe: No

**Logs**
Nothing special on server logs at first sight

**FFmpeg Logs**
No transcoding or remux

**Stats for Nerds Screenshots**
Nerds Stats not available

**Server System (please complete the following information):**
 - OS: Docker on Synology
 - Jellyfin Version: 10.8.1
 - Hardware settings & device: VAAPI on  Intel Celeron J4125
 - Reverse proxy: Synology
 - Other hardware notes: Synology
 
**Client System (please complete the following information):**
 - Device: ChromeCast with Google TV
 - OS: Android TV
 - Client: Android TV
 - Client and Browser Version: jellyfin-androidtv 0.13.6 release

**Description:**
When playing a HEVC 4K HDR media, the audio output is right put image first suffer very low framerate and then stop.
Wifi connection don't seem to be the probleme, tested with airflow, 40 to 60  mbps.

**Comment by Dragon548** [comment]
Did you find a solution to your problem?
Because I have the same problem on a Google TV.
So I will be interested in the solution.
Thanks in advance.

**Comment by ArtyomFR** [comment]
Hi!
I'm sorry to say that but no, I've have no solution for this.
I've also made more test with different media, and I can reproduce this with medias that have strictely the same vidéo/audio properties in jellyfin. The only change is that one is lagging the other is not.

**Comment by Dragon548** [comment]
Thanks for your quick return.
So we just have to wait for the Android 13 update hoping that it solves our problem...

**Comment by rocketfuelindustries** [comment]
I have the same problem and it's driving me nuts - Chromecast with Google TV can't DirectPlay UHD HDR 2160p content at a rate faster than ~0.3FPS. Transcoding the same files to a web client is buttery smooth. I wish there was a way to tell Jellyfin "always force transcoding to the stupid weak Chromecast". Transcoding the same files to a web client is buttery smooth.

**Comment by ArtyomFR** [comment]
Honnestly, I have no idea of what cause this issue.
After some more tests, some files that are 4K HDR just play fine in directplay, some with exact same properties according to jellyfin data won't.
I have first thought that CCWGT was just not powerfull enough to play these file even if it can decode it, but forced to see that it inded can.
But maybe we should transfere this issue to the android TV app repo since it work just fine everywhere else.

**Comment by rocketfuelindustries** [comment]
> I have first thought that CCWGT was just not powerfull enough to play these file even if it can decode it

I get exactly the same result trying to DirectPlay the same files using Android TV standalone VLC app or Kodi app on the same Chromecast. I'm choosing them as external player in the JF app, though, in case that makes a difference.

> But maybe we should transfere this issue to the android TV app repo

I wonder this too, but I'd really like a server-side "always transcode to x client" option. I seem to be alone in that, though. Everyone else wants an "always DirectPlay" option.
