### ISSUE TITLE
[Issue]: Metadata Manager: Disabling tags has no effect

### ISSUE THREAD

**Issue by Sledgehamma** [jellyfin/jellyfin#8041]
### Please describe your bug

The following option doesn't have any effect:
Metadata -> Movies -> Enabled Fields -> Tags

As far as I understand this should disable collecting and/or saving of tags for movies. 
However, tags are still saved for new movies and are also written to the NFO. Same happens when I refresh all metadata.  Is this a bug or am I misunderstanding this option?

### Jellyfin Version

Other

### if other:

10.8.1

### Environment

```markdown
- OS: Linux
- Virtualization: Docker
- Clients: 
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RevMetcalf** [comment]
Unfortunately, this issue still exists. I've recently experienced it and made a post on the Jellyfin forum, which can be found here:
[](https://forum.jellyfin.org/t-specifying-metadata-fields-to-download?pid=51277#pid51277)

**Comment by RevMetcalf** [comment]
Unfortunately, this issue still exists. I've recently experienced it and made a post on the Jellyfin forum, which can be found here:
[https://forum.jellyfin.org/t-specifying-metadata-fields-to-download](https://forum.jellyfin.org/t-specifying-metadata-fields-to-download)

**Comment by felix920506** [comment]
Please open a new report instead of attempting to revive an ancient report.
