### ISSUE TITLE
[Issue]: HDR lost when audio track needs transcoding

### ISSUE THREAD

**Issue by stoically** [jellyfin/jellyfin#8043]
### Please describe your bug

My media files with HVEC 4K HDR video tracks and DTS audio tracks aren't switching my device into HDR mode any longer. All of those files need to go through audio track transcoding, as my device isn't capable of playing DTS tracks.

This used to work thanks to https://github.com/jellyfin/jellyfin/pull/7325 until 10.8.0-beta2. It stopped working since 10.8.0-beta3 and still doesn't work with 10.8.0 and 10.8.1.

It still works if the media file is fully capable of direct play. So, using the same media files with HVEC 4K HDR video tracks but switching to an AC3 Dolby Digital audio track will switch the device into HDR mode as expected.

Please let me know if you need further information.

Related issues: https://github.com/jellyfin/jellyfin/issues/6450, https://github.com/jellyfin/jellyfin/issues/7295

Maybe related issues: https://github.com/jellyfin/jellyfin/issues/8040, https://github.com/jellyfin/jellyfin/issues/7835

### Environment

```markdown
- OS: Ubuntu 
- Virtualization: Docker
- Clients: LG 49UN71006LB. Tested with Jellyfin WebOS App and Stock Browser
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin Version

10.8.1

### Jellyfin logs

[jellyfin.log](https://github.com/jellyfin/jellyfin/files/9026712/jellyfin.log)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cvium** [comment]
Always include logs

**Comment by stoically** [comment]
Right, my bad. Attached the log to the initial description. The problematic line seems to be

> [06:39:39] [DBG] [52] Jellyfin.Api.Controllers.DynamicHlsController: Starting transcoding because currentTranscodingIndex=null

**Comment by cvium** [comment]
What exactly is the issue and what is the expected behaviour?

**Comment by whiteowl3** [comment]
@stoically are you trying to say that you lost HDR?  your audio track has nothing to do with this transcode according to your logs. if the issue is "HDR data lost for no reason when transcoding" then it should just be called something like that. as is this issue is very confusing to interpret.

**Comment by stoically** [comment]
@whiteowl3 Updated the initial description and title. Hope that clears things up.

**Comment by stoically** [comment]
Had to update title and description again. Tried to make it as precise as possible.

**Comment by stoically** [comment]
Like, all I can say is that the symptoms are the same as in #7295, but obviously I shouldn't try to open an issue with a diagnosis of the issue source if I'm not familiar with the code base. It is related to the audio track tho, since DTS tracks cause the issue while it works fine with AC3. Also the same media file with the same audio track (DTS) does switch the device into HDR still with Jellyfin Server version 10.8.0-beta2. So it is a regression _somehow_.

**Comment by stoically** [comment]
Still an issue with 10.8.4. Please let me know if I can provide more information regarding the issue or ways to reproduce it.

**Comment by dabohda** [comment]
Same problem with 10.8.8. When I play a movie with Direct Play (video and audio is supported) HDR works. If I switch to an unsupported audio stream during video playback and the video stream is also encoded due to the current bug, HDR is gone and the TV switches to SDR. I am using the Webos client on my LG C2. Let me know if I can give you more information.
