### ISSUE TITLE
[Issue]: release linux stable combined for v10.8.1 missing

### ISSUE THREAD

**Issue by Kariton** [jellyfin/jellyfin#8048]
### Please describe your bug

There is no current combined release file under https://repo.jellyfin.org/releases/server/linux/stable/ available.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by acedogblast** [comment]
Has already been fixed. Check here: https://repo.jellyfin.org/releases/server/linux/stable/
Should be closed now.
