### ISSUE TITLE
[Issue]: Incorrect display of tones in the preview image (Dolby Vision)

### ISSUE THREAD

**Issue by Akeyn** [jellyfin/jellyfin#8049]
### Please describe your bug

I am very glad that there is support for DoVi Profile 5.
There is a minor issue, but very noticeable
![wrong_tones](https://user-images.githubusercontent.com/26007646/177014879-c375eaba-0a94-4db6-88a1-b1fcab30e83f.png)

### Jellyfin Version

Other

### if other:

10.8.1

### Environment

```markdown
- OS: Windows
- Virtualization:
- Clients: Browser
- Browser: Google Chrome
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins: none
- Reverse Proxy:
- Base URL: 127.0.0.1:8096
- Networking:
- Storage: local
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nyanmisaka** [comment]
DoVi cover image/thumbnails support will be added once we finished software tonemapping.

**Comment by Akeyn** [comment]
> DoVi P5 cover image/thumbnails support will be added once we finished software tonemapping.

Thanks for the reply, just wanted to make sure you know about it

**Comment by Akeyn** [comment]
@jellyfin-bot The issue is still unresolved in 10.8.5 version.
