### ISSUE TITLE
[Issue]: Albums with 2 CDs sowing like 2 diferent albums

### ISSUE THREAD

**Issue by alculete** [jellyfin/jellyfin#8053]
### Please describe your bug

Search albums with 2 CDs, and you will notice that the album appears twice with different tracks.
It should show only one album with multiple CDs

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Ubuntu-server 22.04
- Virtualization: Docker's latest channel
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Maxplosion** [comment]
what client are you using? Web browser? Phone?
Multiple CDs are shown correctly for me. 
Have you checked the documentation on file naming?
did you check the tags of the files to make sure they are the same for both albums? (also check extended metadata tags, as those often are the culprid)

**Comment by alculete** [comment]
All devices show the same. For example, if I have an album from **John Doe** with the name **Jane Doe** with two CDs it will show **Jane Doe** and then the second album **Jane Doe** and not **Jane Doe CD1** and **Jane Doe CD2**
