### ISSUE TITLE
[Issue]: Login disclaimer not working on 10.8.1

### ISSUE THREAD

**Issue by l4kr** [jellyfin/jellyfin#8060]
### Please describe your bug

Describe The Bug
Hi! When I change the login disclaimer in server settings it doesn't work even on a fresh install.
When tested on 10.7.7 it works perfectly fine.

Steps To Reproduce:
change login disclaimer

Expected Behavior:
A disclaimer should show on login page

### Jellyfin Version

Other

### if other:

10.8.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ppittle** [comment]
Could not reproduce on master (63d943a) or on my main media server running `10.8.3`

![image](https://user-images.githubusercontent.com/1190907/185235006-5f857175-c713-4435-adaa-a28c6aa20573.png)

Are you using the Web Client?  And do you have any Custom CSS or other UI tweaks configured?

**Comment by l4kr** [comment]
Hi, this was a problem on my side. I don't know what was the problem or how I resolved it but it's not an issue anymore. I will close this.
