### ISSUE TITLE
Jellyfin 4k HEVC stutter and lag

### ISSUE THREAD

**Issue by mlause** [jellyfin/jellyfin#8062]
I've tried to play The Batman to my 2nd generation Apple TV 4k. I've used infuse and MrMC. Both have terrible lag and stutter. I've tried this with Plex and no issues. This should be direct play as ATV support the format. The log file I attached is from 7/3 where I tested MrMC. My jellyfin server is 10.10.60.51. And my ATV is 10.10.61.18. There may have been a test to the ipad where it did transcode, but I don't have stutter issues there. 

**Media Info of the file**

Video
Title: 4K HEVC HDR
Codec: HEVC
Profile: Main 10
Level: 153
Resolution: 3840x2160
Aspect ratio: 16:9
Interlaced: No
Framerate: 23.976025
Bitrate: 57324 kbps
Bit depth: 10 bit
Video range: HDR
Video range type: HDR10
DV title: DV Profile 7.6
DV version major: 1
DV version minor: 0
DV profile: 7
DV level: 6
DV rpu preset flag: 1
DV el preset flag: 1
DV bl preset flag: 1
DV bl signal compatibility id: 6
Color space: bt2020nc
Color transfer: smpte2084
Color primaries: bt2020
Pixel format: yuv420p10le
Ref frames: 1

Audio
Title: AC-3 5.1-EX - English - Dolby Digital
Language: eng
Codec: AC3
Layout: 5.1
Channels: 6 ch
Bitrate: 448 kbps
Sample rate: 48000 Hz
Default: No
Forced: No
External: No

**Logs**

**Server System (please complete the following information):**
 - OS: Docker on Linux
 - Jellyfin Version: 10.8.1
 - Hardware settings & device: NVENC on GTX1050 Ti
 - Reverse proxy: none
 - Other hardware notes: Running on Unraid server latest
 
**Client System (please complete the following information):**
 - Device: Apple TV 4k 2nd gen
 - OS: iOS
 - Client: Infuse, MrMC

[log_20220703.log](https://github.com/jellyfin/jellyfin/files/9041393/log_20220703.log)

**Comment by nyanmisaka** [comment]
Since this only happens on Swiftfin(Jellyfin tvOS), you should report it to https://github.com/jellyfin/Swiftfin

**Comment by mlause** [comment]
It happens on Swiftfin, MrMC, and Infuse. Here is another log from the day before that probably caught one of the other apps
[log_20220702.log](https://github.com/jellyfin/jellyfin/files/9041470/log_20220702.log)
.

**Comment by nyanmisaka** [comment]
Then you should check your network.

**Comment by mlause** [comment]
The network is fine. Like I said there are no issues with stutter via Plex. I can play the files from the server to my desktop via VLC without issues.

**Comment by SR-Lut3t1um** [comment]
What do you mean by horrible? I'm also experiencing issues with big movies (70gb+), all are 4k ripped (legally in germany) from Blu Ray. I'm not sure what exactly my problem is, but I did check drivespeed, fragmentation and networkspeed neither of them are my issue.

**Comment by mlause** [comment]
I deleted the docker and rebuilt it. I also reset my apple tv. That fixed my issue. There must have been a bug somewhere.

**Comment by Bond-009** [comment]
Closing as fixed

**Comment by Panda260** [comment]
> What do you mean by horrible? I'm also experiencing issues with big movies (70gb+), all are 4k ripped (legally in germany) from Blu Ray. I'm not sure what exactly my problem is, but I did check drivespeed, fragmentation and networkspeed neither of them are my issue. 

Yea i have the Same Problem as Well 4k 50+GB 
Network ist fine Drives are fast CPU should bei strong emuth Intel Xeon Gold 6266C only using 8 cores for jellyfin

Das ist schon nervig...
