### ISSUE TITLE
[Issue]: why is "EnableMpegtsM2TsMode" ignored?

### ISSUE THREAD

**Issue by Andy2244** [jellyfin/jellyfin#8067]
### Please describe your bug

https://github.com/jellyfin/jellyfin/blob/master/Jellyfin.Api/Helpers/StreamingHelpers.cs
`// state.EnableMpegtsM2TsMode = transcodingProfile.EnableMpegtsM2TsMode;`

Any reason why this is commented, without any note/feedback to the clients trying to use it?

### Jellyfin Version

10.8.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
That line was originally created here: https://github.com/jellyfin/jellyfin/commit/1d7d52ff9e42c3efb4bb2c65e82a4a82faf9decb

So it was brought over from Emby.

**Comment by Andy2244** [comment]
ah ok, trying to figure out why the mode is not applied. Will check the other helper objects.
