### ISSUE TITLE
[Issue]: Admin dashboard become very slow to show about 10 "active devices" after few hours of use.

### ISSUE THREAD

**Issue by VigibotDev** [jellyfin/jellyfin#8068]
### Please describe your bug

Admin dashboard become very slow to show about 10 "active devices" after few hours of use.

I must restart Jellyfin to solve the problem.

### Jellyfin Version

Other

### if other:

10.8.1 (last Debian stable)

### Environment

```markdown
- OS: Debian 11
- Virtualization: No, bare metal with stable Debian package
- Clients: about 10, any
- Browser: any
- FFmpeg Version: any
- Playback Method: any
- Hardware Acceleration: No
- Plugins: No
- Reverse Proxy: Apache + websocket
- Base URL: /jellyfin
- Networking: 10GB
- Storage: 14 * Exos 16TB
```

### Jellyfin logs

```shell
[2022-07-18 22:22:22.060 +02:00] [ERR] Error reporting playback progress
MediaBrowser.Common.Extensions.ResourceNotFoundException: Session fb8f43bc90206bdb339a399e244e20a3 not found.
   at Emby.Server.Implementations.Session.SessionManager.GetSession(String sessionId, Boolean throwOnMissing)
   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
   at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
[2022-07-18 22:22:22.068 +02:00] [INF] Processing playback tracker : "SmVsbHlmaW5NZWRpYVBsYXllciAxLjcuMC1wcmUzICh3aW5kb3dzLXg4Nl82NCAxMCl8MTY0MzQ3OTc3MDIwMA11-306e6540b9b24612bfd75b5d2a5fea7b-298b36522f6011e8692298ae42b5e721"
[2022-07-18 22:22:22.793 +02:00] [ERR] Error sending web socket message Sessions
System.Net.WebSockets.WebSocketException (0x80004005): The WebSocket is in an invalid state ('Aborted') for this operation. Valid states are: 'Open, CloseReceived'
   at System.Net.WebSockets.WebSocketValidate.ThrowIfInvalidState(WebSocketState currentState, Boolean isDisposed, WebSocketState[] validStates)
   at System.Net.WebSockets.ManagedWebSocket.SendAsync(ReadOnlyMemory`1 buffer, WebSocketMessageType messageType, WebSocketMessageFlags messageFlags, CancellationToken cancellationToken)
--- End of stack trace from previous location ---
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by VigibotDev** [comment]
This one look also linked : https://github.com/jellyfin/jellyfin/issues/8179

**Comment by VigibotDev** [comment]
Look fixed on 10.8.6, problem hard to reproduce but I'm about 90% sure with a few days of heavy use.

**Comment by VigibotDev** [comment]
Update to 10.8.7 the problem is back:(

**Comment by cvium** [comment]
Impossible. 10.8.7 contains nothing that would cause it to reappear. It must've not been fixed.

**Comment by VigibotDev** [comment]
We are therefore in the 10% of doubt that I had issued, the problem has never been corrected. It takes at least a dozen users and it's not systematic!

**Comment by VigibotDev** [comment]
Yes... We are therefore in the 10% of doubt that I had issued, the problem has never been corrected. It takes at least a dozen users and it's not systematic! I can't understand who (type of user ?) show this issue.
Because 10.8.6 2 days ago runned fine with about 30 users and high performance in admin panel ! Server network and performance sized for more than 200 users with 4K streams... Tested with the same IP source, problem appear in production with users from different network location (IPv4 & IPv6 dual stack with proper Apache reverse proxy) and different client type, I can't benchmark this:( The bug only appear on the first panel page (problem is userlist, if I go rapidly on others config pages, it's ok)

**Comment by VigibotDev** [comment]
Problem still here...
I found some thing, Pannel do a lot of large XHR request and with Playback/BitrateTest this is abnormal...
![Bug](https://user-images.githubusercontent.com/4873680/223758338-62b8f8d9-9598-4186-84c2-aee2d66a56d6.png)
![Bug2](https://user-images.githubusercontent.com/4873680/223758353-2cda88c7-c2ae-49fd-aafc-6bf0a69c49e4.png)

**Comment by VigibotDev** [comment]
I see a very large amount of websocket data when there is the bug on the admin panel... I use /proc/net/nf_conntrack kernel module on the server. It's require a websocket sniffer (wireshark or browser extension) to debug more

**Comment by javigmsuperka** [comment]
I was going crazy, and I found that issue on GitHub. It just happened to me exactly the same with 15 streams. I opened the dashboard, and shortly after, I had to restart the server.
