### ISSUE TITLE
[Issue]: TotalRecordCount wrong on grouped Library Folders when Limit is set.

### ISSUE THREAD

**Issue by SenorSmartyPants** [jellyfin/jellyfin#8069]
### Please describe your bug

I just noticed that on some queries JF is not returning a correct record count when filtering and setting a limit. ParentID is a TV show aggregate library (2 Tv show libraries displayed as one). This works fine when ParentID is a non aggreate movie library. It works fine if I remove the limit or the parentID (but then it's not filtering by that parentID).

`http://192.168.1.4:8096/Users/<USERID>/Items/?IncludeItemTypes=Series&Limit=12&ParentID=<PARENTID>&Recursive=true&SeriesStatus=Continuing&SortBy=SortName&StartIndex=0&api_key=<APIKEY>`

That returns `TotalRecordCount: 12` while this
`http://192.168.1.4:8096/Users/<USERID>/Items/?IncludeItemTypes=Series&ParentID=<PARENTID>&Recursive=true&SeriesStatus=Continuing&SortBy=SortName&StartIndex=0&api_key=<APIKEY>`
Returns the correct `TotalRecordCount: 87`.

Other filters that don't return correct `TotalRecordCount`
Filters=IsUnplayed
Filters=IsPlayed
SeriesStatus=

Works:
Genres=
NameStartsWith=
OfficialRatings=
Years=

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SenorSmartyPants** [comment]
Still an issue. Reopen please

**Comment by SteveDinn** [comment]
Thanks to @michaelrusf, I'm pretty sure that this is related to my issue here: #7959.
