### ISSUE TITLE
[Issue]: Collections ProductionYear based on oldest movie in collection instead of newest

### ISSUE THREAD

**Issue by sbranden** [jellyfin/jellyfin#8079]
### Please describe your bug

The metadata for ProductionYear of Collections is set based on the oldest movie in the collection instead of the newest.
This causes issues such as sorting Movies based on date with collections enabled.  The collection ends up being buried at an older place in the order rather than the newer location. 

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sbranden** [comment]
Issue still exists.  Unfortunately it doesn't seem like others understand that current implementation is wrong.  Fix provided that works.  If someone tells me how to add a configuration option to enable/disable it can we have it included.

**Comment by Bond-009** [comment]
Closing as this is intended behavior, further discussion can happen on the PR.

**Comment by sbranden** [comment]
The intended behavior is wrong then.  This is a bug making collections not that useful.
