### ISSUE TITLE
multi-part movies can not switch to next part

### ISSUE THREAD

**Issue by mujiubai** [jellyfin/jellyfin#8090]
**Media Info of the file**

I rename the multi-part movie file to the type:
 - aaaa-cd1.mp4
 - aaaa-cd2.mp4
 
the jellyfin can successly detect the cd2 movie as the additional part, but when I play the cd1 version movie, I cannot use the button(all the lower left corner button I have try) switch to the cd2 version, only back to the movie introduce page to choose cd2 version, it's very inconvenient to use. is a bug ? or my operation is wrong? thanks a lot!

**Server System (please complete the following information):**
 - OS: [Docker on Linux]
 - Jellyfin Version: [10.8.1]
 - Hardware settings & device: [intel G5905]
 - Reverse proxy:
 - Other hardware notes: 
 
**Client System (please complete the following information):**
 - Device: [windows, quest2]
 - OS: [Android, Windows]
 - Client: [Web/Browser]
 - Browser (if Web client): [Chrome, quest2-browser]
 - Client and Browser Version:

**Comment by cvium** [comment]
This is not a bug. That is unfortunately how the feature has always been. Plex has much better support for it.
