### ISSUE TITLE
Closed Captioning for Live TV

### ISSUE THREAD

**Issue by Maskedman** [jellyfin/jellyfin#81]
This is a big issue in Emby, if we can get this to work before they do, I'll guarantee that there will be a very significant increase in people switching away from Emby.

**Comment by anthonylavado** [comment]
Thank you for the note! We're working on getting everything stable right now, but we'll look at this for the roadmap.

**Comment by RaeBoz** [comment]
+1 
I would love to see this too! I know it wouldn't be perfect, but I would take anything.
