### ISSUE TITLE
[Issue]: Files in "Extras" folders are not treated as specials for TV shows

### ISSUE THREAD

**Issue by algirdasN** [jellyfin/jellyfin#8100]
### Please describe your bug

For TV shows, files in "Extras" folders are not treated as specials (they are not grouped under "Specials" by the seasons). Instead, they are placed in a new section - "Special Features" - below "Cast & Crew". The metadata for the files are not getting fetched as well. It works properly if specials are placed in folders named "Specials", "Season 00" or "0". 

"Extras" folders for TV shows used to work at some time in the past (probably 10.7.x).

**Steps to reproduce:**
1. Create an "Extras" folder under the TV series and add a video file to it.
2. Refresh metadata for the TV series.

**Actual result:** files in "Extras" folder are not grouped under "Specials"
**Expected result:** files in "Extras" folder should be grouped under "Specials"

### Jellyfin Version

Other

### if other:

10.8.1

### Environment

```markdown
- OS: Linux Mint 20.3
- Virtualization: -
- Clients: Browser, Jellyfin Media Player, iOS
- Installed Plugins: none
- Storage: local
```

## using "Extras" folder
![image](https://user-images.githubusercontent.com/61432976/178165868-f4190258-0c97-4bad-867b-6b73eb3ad203.png)

## using "Specials" folder
![image](https://user-images.githubusercontent.com/61432976/178165919-0a429a90-d96e-455f-98cf-a3c86188b81a.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SenorSmartyPants** [comment]
Put your file in the specials folder. It is a special, not an extra. 

10.8.0 added support for extras for TV series and seasons. The docs haven't been update to reflect this yet. It follows the same rules as movie extras. 

https://jellyfin.org/docs/general/server/media/movies.html#movie-extras

**Comment by algirdasN** [comment]
Yes, I solved it for myself by moving the files to “Specials” directory. 

The question here is whether “Extras” folder not working for TV series is intended behavior. It definitely used to work in previous Jellyfin versions as I used to have everything stored in “Extras” and it showed up under specials. Only recently I noticed that this is no longer the case.

**Comment by SenorSmartyPants** [comment]
Extras subfolder is now behaving as designed. This is a behavior change from 10.7, but I wouldn't describe it as not working. Any of the subfolders listed in [movie extras](https://jellyfin.org/docs/general/server/media/movies.html#movie-extras) are now treated as `extras` type folders.

**Comment by algirdasN** [comment]
Thank you for the explanation. Closing the ticket since this is expected behavior.
