### ISSUE TITLE
Infinite scrolling + timeline

### ISSUE THREAD

**Issue by darrepac** [jellyfin/jellyfin#8102]
Hi

I think that Jellyfin is missing the goal in terms of Photos support.
It is at least missing the all photos view with infinite scrolling + timeline on the side as are doing google photo, onedrive,.... and Plex...

**Comment by crobibero** [comment]
Feature requests belong at https://features.jellyfin.org

**Comment by darrepac** [comment]
ok so don't propose to create feature request here ;)
