### ISSUE TITLE
[Issue]: If a folder contains a single video as well as child folders, only the one video can be played

### ISSUE THREAD

**Issue by oshi97** [jellyfin/jellyfin#8106]
### Please describe your bug

Noticed what seems to be a recurring pattern that, if I have a folder that only contains a single video file but also contains some additional child folders, the jellyfin web UI renders the folder as a single video instead. This leads to the child folders being unreachable. I noticed that the problem goes away if the folder either contains multiple videos/photos, or if I move the sole video into a child folder. I feel like this is unexpected behavior but could be wrong - I'm using the built in Photo type

### Jellyfin Version

Other

### if other:

10.8.1

### Environment

```markdown
- OS: Windows
- Virtualization: none
- Clients: Browser
- Browser: Chrome
- FFmpeg Version: 2022-06-22-git-fed07efcde-full_build-www.gyan.dev
- Playback Method: Direct Play
- Hardware Acceleration: NVENC
- Plugins: none
- Reverse Proxy: none
- Base URL: none
- Networking:
- Storage: local
```

### Please attach any browser or client logs here

![image](https://user-images.githubusercontent.com/23005393/178315750-854c5516-cff3-450c-9d5f-73e5d3dfb345.png)

### Please attach any screenshots here

example of the web UI displaying a folder named `testFolder` as a video, which I would expect to only occur if the folder's only content was a single video: 
![image](https://user-images.githubusercontent.com/23005393/178316083-e3893899-eb65-4ed5-9583-742f60c65cce.png)

actual contents of the folder, 1 video + 1 folder with a different video:
![image](https://user-images.githubusercontent.com/23005393/178316207-1d69b62f-d933-4e65-8d47-7b63d3cc39e6.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DocJr90** [comment]
This still occurs, and does so with an ISO file in the parent directory. The child directories are inaccessible. Creating a dedicated child directory for the ISO file does resolve the issue.

**Comment by fidesachates** [comment]
This bug impacts me

**Comment by tudorapo** [comment]
I have this bug too. Is it possible to have a "show the filesystem don't try to be smart" option somewhere?

**Comment by nonobio** [comment]
Hi,
It is similar to my issue: https://github.com/jellyfin/jellyfin/issues/9221#issuecomment-1636713205
