### ISSUE TITLE
QSV transcoding command not working on ubuntu 22.04

### ISSUE THREAD

**Issue by frankyifei** [jellyfin/jellyfin#8117]
QSV Transcode not working on ubuntu 22.04. Jellyfin passed a very strange command to ffmpeg. I did not set Vaapi in settings, QSV was selected.
the command looks like this 
`/usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -init_hw_device vaapi=va:,driver=iHD,kernel_driver=i915 -init_hw_device qsv=qs@va -filter_hw_device qs -hwaccel qsv -hwaccel_output_format qsv -c:v h264_qsv -autorotate 0 -canvas_size 1280x690 -i file:"/media/win_e/Movies/魔女宅急便 (1989)/魔女宅急便 (1989) h264-720p AAC-2ch.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -codec:v:0 h264_qsv -low_power 1 -preset 7 -look_ahead 0 -b:v 3073050 -maxrate 3073050 -bufsize 6146100 -profile:v:0 high -level 40 -g:v:0 72 -keyint_min:v:0 72 -filter_complex "[0:2]scale=flags=fast_bilinear,format=bgra,hwupload=derive_device=qsv:extra_hw_frames=64[sub];[0:0]setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale_qsv=format=nv12[main];[main][sub]overlay_qsv=eof_action=endall:shortest=1:repeatlast=0:w=1280:h=690" -start_at_zero -codec:a:0 aac -ac 2 -ab 192000 -ar 48000 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/var/lib/jellyfin/transcodes/c15d50052657ce55ccab5e6360564de4%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/var/lib/jellyfin/transcodes/c15d50052657ce55ccab5e6360564de4.m3u8"`

by removing the strange part, This command seems working well in terminal. 
`/usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -hwaccel qsv -hwaccel_output_format qsv -c:v h264_qsv -autorotate 0 -canvas_size 1280x690 -i file:"/media/win_e/Movies/魔女宅急便 (1989)/魔女宅急便 (1989) h264-720p AAC-2ch.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -codec:v:0 h264_qsv -low_power 1 -preset 7 -look_ahead 0 -b:v 3073050 -maxrate 3073050 -bufsize 6146100 -profile:v:0 high -level 40 -g:v:0 72 -keyint_min:v:0 72 -filter_complex "[0:2]scale=flags=fast_bilinear,format=bgra,hwupload=derive_device=qsv:extra_hw_frames=64[sub];[0:0]setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale_qsv=format=nv12[main];[main][sub]overlay_qsv=eof_action=endall:shortest=1:repeatlast=0:w=1280:h=690" -start_at_zero -codec:a:0 aac -ac 2 -ab 192000 -ar 48000 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/var/lib/jellyfin/transcodes/c15d50052657ce55ccab5e6360564de4%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/var/lib/jellyfin/transcodes/c15d50052657ce55ccab5e6360564de4.m3u8"`

![截图 2022-07-14 00-58-39](https://user-images.githubusercontent.com/8104251/178772457-09709a3e-5c30-4007-9cdb-015c3e2e2429.png)
**Media Info of the file**
video 720P H264 SDR
audio AAC stereo

**FFmpeg Logs**
```
ffmpeg version 4.4.1-Jellyfin Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-18ubuntu1)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-static --enable-gmp --enable-gnutls --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --arch=amd64 --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-vdpau --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Device creation failed: -542398533.
Failed to set value 'vaapi=va:,driver=iHD,kernel_driver=i915' for option 'init_hw_device': Generic error in an external library
Error parsing global options: Generic error in an external library
```

**Server System (please complete the following information):**
 - OS: ubuntu 22.04
 - Jellyfin Version: 18.01
 -  UHD600 
 - Reverse proxy: no
 - Other hardware notes: no
 
**Client System (please complete the following information):**
on any clients

**Comment by Shadowghost** [comment]
Please upgrade to jellyfin-ffmpeg 5.0.1 and try again. The parts you removed initialize the correct driver and runtime environment of the hardware acceleration pipeline. You're seeing VAAPI because QSV is based on VAAPI.

Also keep in mind, that the Kernel shipped with Ubuntu 22.04 has a regression impacting QSV operation (see comment in our HWA docs).
