### ISSUE TITLE
Support for Zooming as in Kodi's GUI

### ISSUE THREAD

**Issue by VoodooZ** [jellyfin/jellyfin#813]
At a minimum being able to scale videos with odd ratios so one can maximize vertical size even at the expense of a losing some horizontal parts of the scene.. 
I think Kodi does it perfectly. Custom and preset zooms.
I don't even mean weird anomorphic scaling either. just zoom/scale.
Everything else looks great so far..

Thanks in advance,

**Comment by JustAMan** [comment]
Can you provide more explanation of the feature? Some illustrative screenshots maybe?
I think I'm getting what you ask for, but I want to be sure, and my telepathy skills of late are flaky :)

**Comment by VoodooZ** [comment]
Not sure how I could capture that visually.
In previous kodi 17, you could open a dialog and do custom zoom where a slider where you could scale video up or down in realtime. It would show you the scale factor too which is nice.

But at this point I'd take just having a few preset too.
ex: fill vertically (where you zoom until the top and bottom black bars are gone.. (with obvious left and right image loss...)

I think this could be done in hardware from what I read about Nvidia hardware acceleration operations...

Hope this helps.

**Comment by ckcr4lyf** [comment]
This could potentially be fixed by https://github.com/jellyfin/jellyfin-web/pull/7627
