### ISSUE TITLE
[ISSUE] Guide does not order digital subchannels correctly when 10 or more subchannels are present

### ISSUE THREAD

**Issue by godkarmachine** [jellyfin/jellyfin#8138]
I've noticed a minor bug in the live TV guide when viewing a channel with 10 or more subchannels.  The guide appears to display the .10 subchannel (and presumably higher subchannels) before the .1 subchannel.  I've verified this on both the Web and Android TV clients.

I presume this would also affect channels with more than 10 subchannels, but I have only been able to verify it with a channel with 10 subchannels, as this is the most any one channel has in my market.

Repro steps:

1. Connect and configure an HDHomeRun device with an antenna, and configure in Jellyfin
2. Load guide data (I am using XMLTV guide data via zap2xml), and associate it with the HDHomeRun tuner
3. Open your client and navigate to the Live TV Guide View
4. Find a channel with 10 subchannels (in my case, this is channel 5 in Wichita KS 67207)

Expected behavior:

Subchannels should be displayed in the following order:
X.1
X.2
X.3
...
X.9
X.10

Observed behavior:

Subchannels are displayed in the following order:
X.10
X.1
X.2
...
X.8
X.9

**Comment by godkarmachine** [comment]
![2022_07_22_09_15_00_Live_TV_Mozilla_Firefox](https://user-images.githubusercontent.com/1330252/180458277-16083040-2811-48c0-bc2d-a79577d1e365.png)

Screengrab of the issue

**Comment by godkarmachine** [comment]
Actually, as it turns out, there is another channel in the area with more than 10 subchannels.  And the behavior with more is even stranger.
![2022_07_22_09_18_24_Live_TV_Mozilla_Firefox](https://user-images.githubusercontent.com/1330252/180458917-c551ca62-ac0e-45d9-a8b2-ef0a159b0a08.png)

**Comment by someperson** [comment]
This still appears to be a problem... any updates?
