### ISSUE TITLE
Add referer parameter to ffmpeg

### ISSUE THREAD

**Issue by joseph39** [jellyfin/jellyfin#8143]
As of https://trac.ffmpeg.org/ticket/2179, ffmpeg supports referer parameter which injects Referer header to the HTTP request for remote content. Have EncodingHelper pass this in if it's included in RemoteHttpHeaders.

**Comment by steven-b89** [comment]
Hi,

I have a question about this one...
I have an .m3u file with the follow lines specifies:

#EXTM3U
#EXTINF:-1 tvg-id="EchoroukTV.dz" tvg-logo="https://i.imgur.com/FtrSAqu.png" group-title="Undefined",Echorouk TV (1080p)
#EXTVLCOPT:Referer: https://echorouk.dzsecurity.net
https://echorouk-live-tv.dzsecurity.net/fullres/EchoroukTV_First/playlist.m3u8

I've tried to adjust the #EXTVLCOPT in multiple ways but can't seem to get it working.
Where can I pass the http-referer so I can stream this channel through Jellyfin.


Regards,
Steven
