### ISSUE TITLE
ffmpeg path not displayed in Docker version

### ISSUE THREAD

**Issue by texneus** [jellyfin/jellyfin#815]
I am running the Docker 10.1.0 version under Debian.  On the Transcoding settings page there is a dialog box to provide a path for ffmpeg.  In the jellyfin Docker container it is blank and outlined in a red box, as if it's trying to draw attention to an error condition.  I note through the top command on the Debian host that ffmpeg appears to be called (it appears up at the top of the list now and again during a library scan).  I suspect the empty/red outline box is not intentional.

Docker command:
```
docker run -d \
  --name jellyfin \
  -v /opt/jellyfin/data:/config \
  -v /mnt/Media:/mnt/Media \
  -v /mnt/RecordedTV1:/mnt/RecordedTV1 \
  -v /mnt/RecordedTV2:/mnt/RecordedTV2 \
  -p 8096:8096 \
  -p 8920:8920 \
  -u 107:20 \
   jellyfin/jellyfin
```

**Comment by JustAMan** [comment]
@joshuaboniface @nvllsvm can you guys look at Dockerfile and make it so we always pass `--ffmpeg` and `--ffprobe` there, so this box has normal value?

@texneus I think the only "bad" implication is that you see a red box around that input field, Jellyfin should be able to find `ffmpeg` in `$PATH` just fine (and it does, looking from what you wrote).

**Comment by texneus** [comment]
@JustAman - I agree it's mostly cosmetic but I'm also hesitant to change anything on this page out of fear it will save the empty path to ffmpeg for real.

**Comment by ploughpuff** [comment]
Supplying --ffmpeg is given the encoder type of 'External' and these are not shown on the UI transcode page.  In fact, the text box is acively hidden from the user:

`"External" == systemInfo.EncoderLocationType ? (page.querySelector(".fldEncoderPath").classList.add("hide"), page.querySelector(".txtEncoderPath").removeAttribute("required"))`

I'm working on some improvements in FFmpeg pathing and was going to document my thoughts in a new issue for you guys to consider...

**Comment by LeoVerto** [comment]
Closing this to minimize duplicates, please continue discussing this in #478! :octopus:
