### ISSUE TITLE
[Issue]: ASS subtitles in external .MKS files always start at beginning of video

### ISSUE THREAD

**Issue by SusStew** [jellyfin/jellyfin#8157]
**Issue description**
Window on right shows Aegisub with original subtitle and window on left shows subtitle extracted automatically by Jellyfin using FFmpeg to `/config/data/`.
![Screenshot from 2022-07-22 03-15-50](https://user-images.githubusercontent.com/78996552/180384863-790239e8-9846-4783-9f5b-4fbce2c286a0.png)
This causes all subtitles to be early by over a minute.

External .ASS files do not have the same issue, however. These .ASS files do not support the same features as .MKS files though, like tagging and attached font files.
Playing the video file directly using MPV and using the .MKS file's subtitles does not have the same issue.

**Logs**
```
[2022-07-22 02:48:29.424 -04:00] [INF] [531] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: "/usr/lib/jellyfin-ffmpeg/ffmpeg" "-i file:\"/media/Multimedia/Jellyfin/Anime/Movies/A Silent Voice/A Silent Voice.mks\" -map 0:1 -an -vn -c:s copy \"/config/data/subtitles/a/a5432ab7-76df-10c0-b24f-e6a2f00bc319.ass\""
[2022-07-22 02:48:29.512 -04:00] [INF] [523] MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder: ffmpeg subtitle extraction completed for "file:\"/media/Multimedia/Jellyfin/Anime/Movies/A Silent Voice/A Silent Voice.mks\"" to "/config/data/subtitles/a/a5432ab7-76df-10c0-b24f-e6a2f00bc319.ass"
```

**Server System:**
 - OS: Docker on Linux
 - Jellyfin Version: 10.8.1
 - Hardware settings & device: NVENC on GTX980
 - Reverse proxy: none
 - Other hardware notes: Media mounted over NFS
 
**Client System:**
 - OS: Linux, Android
 - Client: Jellyfin Media Player, Jellyfin Android

**Comment by Shadowghost** [comment]
Can you try extracting it manually with `/usr/lib/jellyfin-ffmpeg/ffmpeg" -fix_sub_duration <rest-of-the-command>` and check if it fixes anything?
If not it's be helpful if you could provide the original ASS and the MKS so I can test it locally.

**Comment by SusStew** [comment]
> Can you try extracting it manually with `/usr/lib/jellyfin-ffmpeg/ffmpeg" -fix_sub_duration <rest-of-the-command>` and check if it fixes anything? If not it's be helpful if you could provide the original ASS and the MKS so I can test it locally.

Using that flag manually with FFmpeg didn't change anything. The subtitles are still starting early.

**Comment by nyanmisaka** [comment]
Please attach the MKS subtitle file.

**Comment by SusStew** [comment]
[A Silent Voice.mks.gz](https://github.com/jellyfin/jellyfin/files/9173084/A.Silent.Voice.mks.gz)

**Comment by SusStew** [comment]
The .ASS files are from [this repo on GitHub](https://github.com/nedragrevev/custom-subs/raw/master/A%20Silent%20Voice_AU%20Madman%20BD_Full%20Eng%20With%20and%20Without%20Honorifics%2C%20and%20Signs%20and%20Song%20Only%20Vers_v3.1_nedragrevev.7z).

**Comment by Shadowghost** [comment]
#8182 should fix it. Adding `-copyts` fixed the timestamp issues for me.

**Comment by Shadowghost** [comment]
@SusStew can you check if 10.8.4 fixes the issue for you and close the issue if it does?
You might need to remove the already extracted subtitles.

**Comment by SusStew** [comment]
The new Jellyfin version 10.8.4 does fix this issue. Thanks!
