### ISSUE TITLE
Can not delete empty genre folders for music

### ISSUE THREAD

**Issue by Gaffers2277** [jellyfin/jellyfin#8173]
I cleaned up some meta data for some albums and changed the genre. So Jellyfin recoginised the genre change and made a new folder but the old folder is still there, but when i went to delete the old folder it told me - There was an error deleting the item from the server. Please check that Jellyfin has write access to the media folder and try again. I looked to see if i could find a directory to give permissions but there doesnt seem to be a directory for music genres.

**Comment by Gaffers2277** [comment]
After scanning the library a few times it seems to have resolved the issue

**Comment by VigibotDev** [comment]
Version : 10.8.10 it's not closed for me. I removed a lot of music and added few. Jellyfin keep genre and posters from old music.

**Comment by geoffcorey** [comment]
Same here.  Cleaned up genres for the music and now I have genres with nothing associated with it.

**Comment by VigibotDev** [comment]
I refreshed few time + clear the browser cache (i think it's useless) and done.... No problem for me lol

**Comment by geoffcorey** [comment]
Seems if you rename the Genre to Empty it will clear up

**Comment by projectgus** [comment]
I don't know if it's the only way, but selecting "Refresh Metadata" and "Replace All Metadata" for the Music library seems to clean up empty genres when it finishes. The refresh can take a while to complete.
