### ISSUE TITLE
How to uninstall MacOS

### ISSUE THREAD

**Issue by akimad** [jellyfin/jellyfin#818]
Hi,

I don't find how to completely uninstall Jellyfin in MacOS?

Thank you,
Damien

**Comment by TheSIlentLink** [comment]
If I remember correctly it also puts files in .local.

**Comment by anthonylavado** [comment]
Closing in 24h unless there are more comments?

The steps above are correct (to my knowledge).

**Comment by akimad** [comment]
I followed all your instructions and it's all correct 👍🏻 Thank you!
