### ISSUE TITLE
Add Force Transcoding Setting 

### ISSUE THREAD

**Issue by SuperMitic** [jellyfin/jellyfin#8183]
I explain my problem. I have a LG CX WebOS TV with the lastest version of Jellyfin. I have some 4K 60fps 60MBit video recorded with the Gopro. When i play these video in every app on the TV the video lags/loose frames (there is something that the TV can't decode in the gopro video, this happens even in native app with USB). But the TV is able to decode 4K 60Fps HEVC 50/60 MBit. So i would like to have a setting to force transcoding and a setting to choose costum resolution and bitrate. so that i can enable force transcoding and transcode the video to 4K 60Fps 50/60Mbit HEVC.
Now the only way to enable transcode is to choose a lower bitrate but also lower resolution, for example 1080p 40Mbit. 
Please allow a setting to force transcoding and a setting to choose custom resolution and bitrate.

**Comment by crobibero** [comment]
Feature requests belong at https://features.jellyfin.org
