### ISSUE TITLE
[Issue]: Jellyfin not using embedded artwork in MP4 files (created in Subler on MacOS) since 10.8.1 update

### ISSUE THREAD

**Issue by InsectRepellent3000** [jellyfin/jellyfin#8184]
### Please describe your bug

I used to prepare my files with Subler saving metadata and Artwork in the MP4 files on MacOS
Movies added to the folder would show artwork in the WebUi on MacOS and also in my Android Client very well
I always had all the 'scrapers' turned off in order to force using embedded data
Since update to 10.8.1 it uses the text metadata (movie descriptions etc..) but not the artwork anymore

### Jellyfin Version

Other

### if other:

10.8.1

### Environment

```markdown
- OS: MacOS
- Virtualization:
- Clients: Browser and android 
- Browser:Safari 
- FFmpeg Version: I'm not sure
- Playback Method: in browser or in android 
- Hardware Acceleration: I think all off 
- Plugins: standard 
- Reverse Proxy:
- Base URL:
- Networking: gigabit ethernet and wifi in house
- Storage: dual drive raid attached via usb to mac server
```

### Please attach any screenshots here

Just shows the standard clapboard icon for the movie only

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 1337joe** [comment]
Do you have all "Image Fetcher"s turned off for the library in question?

10.8 moved the code to extract embedded images from video files out of the "Screen Grabber" into the "Embedded Image Extractor" to allow for expanding the range of embedded files supported. I just created a [pull request](jellyfin/jellyfin-docs#714) to update the documentation to mention that.

**Comment by InsectRepellent3000** [comment]
Thanks for reply - actually I think so - I checked in Libraries - selected Movies and 3 dots to edit and they are all off
If I use Tiny Media Manager of course its everything
If I don't it reads the metadata movie description etc.. but not pulling the image generated with Subler saved into MP4 file

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by InsectRepellent3000** [comment]
During the reimport experiment I know see what you mean
I selected the Embedded Extractor only and disabled all the others correctly
I initially deselcted all on this test

Now I'm getting images again - Thank you for your effort !

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by 1337joe** [comment]
Glad that fixed it, thanks for letting me know.
