### ISSUE TITLE
[Issue]: Transcoded HDR Content no longer playing in HDR after upgrading to 10.8.1

### ISSUE THREAD

**Issue by sdfg2** [jellyfin/jellyfin#8192]
### Please describe your bug

Playing HDR files that require transcoding no longer transcodes HDR as well.  Tested with a file I played last week, which played fine in 10.7.7 with jellyfin-mpeg, but stubbornly refuses to work now!  All I did was upgrade jellyfin-ffmpeg to jellyfin-ffmpeg5, and jellyfin itself from 10.7.7.

Could be related to #8043 ? though in this case it's the video and not the audio that needs transcoded.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: arch
- Virtualization: none
- Clients: LG CX TV
- Browser: n/a
- FFmpeg Version: jellyfin-ffmpeg5
- Playback Method: transcode
- Hardware Acceleration: yes
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
https://pastebin.com/vYuDTfWB
```

### FFmpeg logs

```shell
https://pastebin.com/WSaW2HeM
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aidenfoxx** [comment]
I am also experiencing this issue since upgrading to 10.8.4. HDR transcoding used to work fine, but is no longer working on my TV or desktop no matter what transcoding settings I use.

##Environment
```
- OS: Ubuntu 22.04
- Clients: Samsung Q70, Windows 10
- FFmpeg Version: 5.1.1-Jellyfin
- Playback Method: transcode
- Hardware Acceleration: yes and no
```

**Comment by aidenfoxx** [comment]
Could it be this commit causing the issue? https://github.com/jellyfin/jellyfin/commit/cf8aa37f5bd9bc76a78aac4e4232328f82fa4596
