### ISSUE TITLE
Guide not using channel number when display name starts with a number

### ISSUE THREAD

**Issue by jhorning** [jellyfin/jellyfin#820]
I have a few UK channels in an m3u where the name starts with a number (5 Spike, 5 Star, 5 USA). In the guide, these are all listed as channel 5 despite having unique channel numbers in the m3u.

This is the information in the m3u for 5 USA
`#EXTINF:0 channelID="x-ID.248" tvg-chno="1141" tvg-name="5 USA" tvg-id="1141" tvg-logo="https://s3.amazonaws.com/schedulesdirect/assets/stationLogos/s52335_h3_aa.png" group-title="UK CHANNELS",5 USA`

This is how it looks in the guide.
![2019-02-05_10-54-17](https://user-images.githubusercontent.com/905067/52290353-7d145200-2935-11e9-836e-cf8af00f4072.png)

**Comment by fruhnow** [comment]
to me it looks like that channelnumbers are ignored completely when coming from a m3u-File. The channels are ordered alphabetically instead. Can you confirm this?

**Comment by fruhnow** [comment]
As of now, jellyfin doesnt recognize the tvg-chno Tag. I added a pull Request fixing this: #863 
Maybe this already adresses ur problem. If not, the GetChannelNumber-Method in M3uParser.cs could be checked deeper.
