### ISSUE TITLE
[Issue]: My RAM usage goes to 95% and in my Jellyfin logs are errors

### ISSUE THREAD

**Issue by SgtYoshi** [jellyfin/jellyfin#8204]
### Please describe your bug

So first of all hello,

my problem is a little weird but bear with me. My first problem was that everytime I fired up Jellyfin it's RAM usage went to like 95% and after 3 Minutes staying that high the server just crashed, well not just crashed it completly destroyed itself. I couldn't get it working again, not after 5 reboots of the VM, not after 5 service restarts. I had the problem for 3 days with no way fixing it BUT yesterday i checked the option that said "transcode reduce" (the option to limit the amount of transcoding jellyfin does). After that the RAM usage stops at 95% BUT it doesn't crash anymore, even if 2 people watch a movie. So my first question would be if this high RAM usage is normal or abnormal.

For the install of Jellyfin I followed the tutorial on the website under "Ubuntu". I use an Ubuntu 22.04 live Server VM as a Q35 machine and GPU passtrough to get hardware acceleration working. I have a Samba share on a diffrent VM to mount my ZFSpool in Jellyfin per /etc/fstab and have 10TB to my disposal,

The second thing is I got somebody to look at my logs, particular the jellyfin log, he was no expert but spotted some warnings and errors in my Jellyfin log. So he redirectet me to the Github page to seek help and some clearance why my RAM usage is so high and where all the errors and warnings are coming from

I really hope somebody can help. Just so you know im by no mean a advanced user, I only startet tinkering with this stuff 2 weeks ago.

![Bild_2022-08-02_194151479](https://user-images.githubusercontent.com/110481607/182439345-13490e17-31c8-4870-a483-a67e087ab95f.png)
![Bild_2022-08-02_194202234](https://user-images.githubusercontent.com/110481607/182439383-d12b55fb-f38d-4f3a-95bf-3826831a86ec.png)
![Bild_2022-08-02_194216422](https://user-images.githubusercontent.com/110481607/182439426-c3050fc1-d4f9-4a04-bd75-6b5d54c3bf16.png)

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Ubuntu live Server 22.04
- Virtualization: per Proxmox
- Clients: Jellyfin Media Player
- Browser: Opera
- FFmpeg Version: dont know where to look that up
- Playback Method: Transcode
- Hardware Acceleration: NVENC
- Plugins: standart
- Reverse Proxy: none
- Base URL: none
- Networking: Host 
- Storage: Raid, NFS
```

### Jellyfin logs

```shell
The log where to long so i put a pastebin here instead.

https://pastebin.com/9bf22Ysf
```

### FFmpeg logs

```shell
The log was to long so i put a pastebin here instead.

https://pastebin.com/kKTFgVFD
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fashni** [comment]
I have similar issue regarding memory usage. Just upgraded my docker container from 10.7.7 to 10.8.3 and it keeps filling up the RAM and the swap of my machine even when it's not playing anything. Had to restart the host completely because at that point the host has become unresponsive to any input.

The host itself is not that powerful, just an old dual core laptop with 1GB of RAM and 3GB swap space, with Ubuntu 20.04. I'm the only user, and it was fine even capable to transcode until I upgraded to the latest version.
