### ISSUE TITLE
10.8.3 issues trying to play from series list

### ISSUE THREAD

**Issue by Nazar78** [jellyfin/jellyfin#8205]
Hi,

I noticed (actually reported by few of my family members) since the 10.8.3 update on my Debian 11, there's an issue trying to play any videos from the series list. It will pop up the client isn't compatible and server isn't responding, sort of like that sorry I can't recall, followed by the infinite loading circle. 

However if I were to "search" the series name and play from that result, the video will play fine. Not sure about other clients but I tested in the latest Chrome.

I immediately downgraded to 10.8.1 and it worked perfectly. I've confirmed it had nothing to do with reverse proxy as I also tested in direct LAN IP.

Sorry again I can't provide any debug logs for now as the server was set to fatal logging and I have family members currently accessing the server remotely for me to do any debugging or restart. I also checked there's no DirectStream or Remux logs produced in 10.8.3 when playing from the series list but they exists when downgraded back to 10.8.1.

> jellyfin         10.8.3-1        
> jellyfin-ffmpeg5 5.0.1-8-bullseye
> jellyfin-server  10.8.3-1        
> jellyfin-web     10.8.3-1       
 
> Video
> Codec: H264
> AVC: No
> Profile: High
> Level: 31
> Resolution: 1280x690
> Aspect ratio: 1.85:1
> Interlaced: No
> Framerate: 23.976025
> Bitrate: 838 kbps
> Bit depth: 8 bit
> Video range: SDR
> Video range type: SDR
> Pixel format: yuv420p
> Ref frames: 1
> NAL: 0

> Audio
> Language: eng
> Codec: AAC
> Profile: LC
> Layout: stereo
> Channels: 2 ch
> Bitrate: 256 kbps
> Sample rate: 48000 Hz
> Default: Yes
> Forced: No
> External: No

> Subtitle
> Language: eng
> Codec: SUBRIP
> Default: Yes
> Forced: No
> External: No

**Comment by dhbtfs** [comment]
Can confirm having the same issue.  
Disabling Hardware acceleration does nothing either, just a test I did I guess.

**Comment by fengapappit** [comment]
Same issue here, using latest docker build of this version.

**Comment by YvanGuidoin** [comment]
Same issue too debian 11 LXC through apt installs, no HWA

**Comment by Extarys** [comment]
Having this issue using the docker container labelled 10.8.3 and the flatpak client `Jellyfin Media Player   com.github.iwalton3.jellyfin-media-player       1.7.1   stable  flathub system`

**Comment by notarobot63** [comment]
Hi, 
it has been reported by many on Reddit: https://www.reddit.com/r/jellyfin/comments/wdxrpt/take_two_hotfix_1083_is_out/
The problem seems to be happening only with users that have administrative rights.

**Comment by ricowalker** [comment]
> Hi, it has been reported by many on Reddit: https://www.reddit.com/r/jellyfin/comments/wdxrpt/take_two_hotfix_1083_is_out/ The problem seems to be happening only with users that have administrative rights.

I've had the same issue to a user without administrative rights, with what seems like random episodes since both x264 & x265 episodes both did, and did not play. With or without transcoding, with or without reverse proxy.

A roll back to 10.8.1 seemed to fix the issue for now, as I mentioned in #8198

**Comment by sfkpmr** [comment]
> Hi, it has been reported by many on Reddit: https://www.reddit.com/r/jellyfin/comments/wdxrpt/take_two_hotfix_1083_is_out/ The problem seems to be happening only with users that have administrative rights.

Yes, it isn't limited to the series list.

**Comment by fengapappit** [comment]
From what I saw, the files only play when played from the results of a search directly.

Anything else leads to the popup instantly :
![image](https://user-images.githubusercontent.com/6908355/182706676-5def26b3-c619-49d2-8794-3af3981946d6.png)

It does not trigger any ffmpeg logging so I would guess that something got broken in the few preparation steps between the client asking for content and actually reading the content.
It also does not trigger any other logging that the opening and closing of the websocket while doing the following operation:
- Open Jellyfin client
- Click on any media to play it (where the popup happens)
- Close the client

```
[2022-08-03 20:35:23.912 +00:00] [INF] [68] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "172.17.0.1" request
[2022-08-03 20:38:36.647 +00:00] [INF] [75] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "172.17.0.1" closed
```

While it looks like a client issue, the only thing that got updated was the Jellyfin Server which could mean that an API/interface got broken somewhere.

**Comment by toraddict** [comment]
I have the same issue. I run Jellyfin in a Ubuntu LXC, I get this issue every time I add a new file and I can't play the new file. I discovered that this command fixes the issue "sudo chown -R jellyfin:jellyfin /location/of/directory". Every time I add a new file I have to run the command again, I suspect this might be a permissions issue. This didn't happen in 10.8.1.

**Comment by DirtyRacer1337** [comment]
Disabling `Display missing episodes within seasons` solved problem for me

**Comment by mLgz0rn** [comment]
> Disabling `Display missing episodes within seasons` solved problem for me

I can confirm that this also fixes it for me

**Comment by 0xMargo** [comment]
> Disabling `Display missing episodes within seasons` solved problem for me

this work for me too

**Comment by ogkimra** [comment]
This happens with me but gets fixed after restarting jellyfin container
