### ISSUE TITLE
[Issue]: Movie matching

### ISSUE THREAD

**Issue by FairlyBored** [jellyfin/jellyfin#8211]
### Please describe your bug

Jellyfin fails to correctly match movies with one word names when there are other movies with that one word in the name and then more. I tried searching for existing bugs and the only my (poor) searching ability found was #7594 which was closed and also talks about IDs.

An example would be the movie [Carter (2022)](https://www.themoviedb.org/movie/800345?language=en-US). Jellyfin picks Coach Carter (2005) despite Carter (2022) being an exact match for the name. Even if you use the Identify option to correct it, and input the year, you get 3 other movies before the right one. So it's not just a file naming issue. This happens for me many many movies with one word names. The year seems to be ignored, and it doesn't favour the exact matches. 

### Jellyfin Version

Other

### if other:

10.8.1

### Environment

```markdown
- OS: Linux Mint
- Virtualization: Virtualbox on windows host
- Clients: Browser
- Browser:Firefox
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy: Nginx
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by s-t-e-v-e-n-k** [comment]
This also happens with TV Shows: A good example here is [Evil](https://www.themoviedb.org/tv/86848-evil), which was matched as [Resident Evil](https://www.themoviedb.org/tv/108296-resident-evil).

**Comment by phaelax** [comment]
I'll confirm this as well.  "X-Men" will match to "x-men: apocalypse". I've had a few others as well.

**Comment by fz2018** [comment]
Some examples of this happening for me (there are others but I can't remember all of them):

• "Frankenstein (2015)" misidentified as Victor Frankenstein (2015)
• "Monsters (2010)" misidentified as Monsters vs Aliens (2009)
• "Will (2011)" misidentified as Good Will Hunting (1997)
• "I Am Love (2009)" misidentified as a bonus feature of some kind relating to the actual film

(As a side note, I really wish JellyFin could identify titles with ", The" at the end. It works fine for titles with ", A", so I don't know why it can't work for both…not sure about ", An".)

**Comment by SamuelMila** [comment]
Such pages or forums are important so that people can know from where they can some good inspirational movies. They should post their question here on the page of [123 movies](https://ww5.0123movie.net/) and will get answers pretty quickly. I will also do the same

**Comment by logic** [comment]
Noticed this evening that it happened with Belle (2021) as well (it defaults to Belle (2013), which is also the first result for manual identification when supplying the movie name and year). I'm running 10.8.5.

Interestingly, taking a cue from [the documentation](https://jellyfin.org/docs/general/server/media/movies/) and adding `[imdbid-tt13651628]` to the folder name caused Jellyfin to correctly identify the film, but caused the two formats of the movie (`Belle (2021) - 1080p.mkv` and `Belle (2021) - 2160p.mkv`) to show up as separate entries in the movie list. I tried several variations on the filenames, and wasn't able to find a variation that caused them to be merged.

So, as long as you don't store multiple cuts/formats/versions of films, that's a possible workaround until this issue gets addressed.

**Comment by cvium** [comment]
The documentation is pretty clear on grouping. The filenames must match the folder name

**Comment by logic** [comment]
As I mentioned, I tried several naming variations. One of them was:

* `/path/to/storage/Belle (2021) [imdbid-tt13651628]`
  - `Belle (2021) [imdbid-tt13651628] - 2160p.mkv`
  - `Belle (2021) [imdbid-tt13651628] - 1080p.mkv`

Identification worked correctly, but grouping failed.

**Comment by G2G2G2G** [comment]
"Alien 3 (1992).mkv" scans to `Aliens 1984` as well, probably related

>The documentation is pretty clear on grouping. The filenames must match the folder name

In testing this is irrelevant to how it scans. Also if a person is organized, doing their structure like this disorganizes a lot of franchises and series with different naming scheme movies (e.g. Lock, Stock and Two Smoking Barrels (1998) and Snatch (2000)) etc.
It is a poor solution. Name and year are enough for 99.9% of movies. There are like 2 that I've seen in the past 20 years that actually need more to auto scan with ancient systems before all of these existed.
