### ISSUE TITLE
Jellyfin 10.8.3 prevent my nas from sleeping

### ISSUE THREAD

**Issue by sat4all1** [jellyfin/jellyfin#8225]
### Please describe your bug

Since upgrading from 10.7.7 to 10.8.3, jellyfin is preventing my nas from entering hibernation mode.
By switching off jellyfin docker container my nas hibernate just fine during inactivity, downgrading to 10.7.7 also fix the problem.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: DSM 7.1
- Virtualization: Docker
- Clients: Android, Windows
- Browser: chrome 103
- FFmpeg Version:
- Playback Method: Direct Play
- Hardware Acceleration: VAAPI
- Plugins: Kodi Sync Queue, Fanart tv
- Reverse Proxy: none
- Base URL:
- Networking: Bridge
- Storage: local
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by asds234** [comment]
I have the same problem as you
