### ISSUE TITLE
Broken images when identifying media

### ISSUE THREAD

**Issue by Evoley** [jellyfin/jellyfin#823]
**Describe the bug**
When re-identifying media that has been wrongly identified.. the search results show broken images. 

**To Reproduce**

1. Go to any wrongly identified movie to tv show
2. Click on 'Identify'
3. Enter TMDB or TVDB number'

**Expected behavior**
Images to be shown.

**Logs**
[log_20190205 - Copy.log](https://github.com/jellyfin/jellyfin/files/2833868/log_20190205.-.Copy.log)

**Screenshots**

![image](https://user-images.githubusercontent.com/10457130/52304001-96ca8f00-295f-11e9-8245-f0730f0cba0b.png)
![image](https://user-images.githubusercontent.com/10457130/52304100-dd1fee00-295f-11e9-9f44-850bf3134ff2.png)
![image](https://user-images.githubusercontent.com/10457130/52304231-456ecf80-2960-11e9-814d-7f43b3d7b6f6.png)

**System (please complete the following information):**
 - OS: Windows
 - Browser: Vivaldi
 - Jellyfin Version: 10.1.0

Comment's
I am not exactly sure if this is entirely intentional or not. Iirc (before Emby went closed source) Emby had the same problem.

**Comment by KasidisMunkongdee** [comment]
Same here, seems like TMDB scraper not working

**Comment by cvium** [comment]
I am unable to reproduce this. It looks like you have plugins from a previous emby install

**Comment by KasidisMunkongdee** [comment]
> I am unable to reproduce this. It looks like you have plugins from a previous emby install

How to auto scan library
