### ISSUE TITLE
[Issue]: Fetched community rating not accepted when editing metadata

### ISSUE THREAD

**Issue by MMMZZZZ** [jellyfin/jellyfin#8238]
### Please describe your bug

Apparently the metadata fetcher can get the community rating in higher precision (8.266 instead of the usual two-digit 8.3). However, when trying to edit and save metadata, these additional digits seem to cause trouble; jellyfin wants me to reduce it to the usual two digits.

Steps to reproduce:
* Add "Zack Snyder's Justice League" (IMDB ID tt12361974, TMDB ID 791373). Other movies may work as well but most of them only have one or two digit resolution for the community rating.
* Open the dialog to edit its metadata. You should see a community rating of 8.266
* Click save (no need to edit anything).
* A message appears that only 8.2 or 8.3 are valid community ratings. 

Desired behavior: 
* Either the metadata fetcher does something wrong and those additional digits are garbage (a.k.a. they shouldn't have been fetched at all).
* Or, if they're actually accurate, the dialog should accept them. The additional digits don't seem to cause any issues. The movie page displays properly 8.3 as rating. 

Kind regards,
Max

### Jellyfin Version

Other

### if other:

10.8.1

### Environment

```markdown
- OS: Windows 10 LTSC 2019
- Virtualization:No
- Clients: Browser
- Browser: Firefox Desktop 103.0.1 x64
- FFmpeg Version: doesn't apply
- Playback Method: doesn't apply
- Hardware Acceleration: doesn't apply
- Plugins: doesn't apply 
- Reverse Proxy: nginx
- Base URL: none
- Networking: host
- Storage: local
```

### Please attach any screenshots here

![image](https://user-images.githubusercontent.com/36891873/183878431-b8a2a3bf-eb0e-452e-96b7-dc4e18c95612.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CrispyBaguette** [comment]
Since the PR that fixed this was closed, I submitted the same bug in the issues for the web UI [here](https://github.com/jellyfin/jellyfin-web/issues/4093).

**Comment by daullmer** [comment]
Will be closing this in favour of jellyfin/jellyfin-web#4093
