### ISSUE TITLE
[Issue]: ItemQuery with ItemSortBy.SeriesDatePlayed and ItemFilter.IsUnplayed/IsPlayed = broken results

### ISSUE THREAD

**Issue by Andy2244** [jellyfin/jellyfin#8249]
### Please describe your bug

For a series the `ItemSortBy.SeriesDatePlayed` in combination with a `ItemQuery` will work correctly, yet if we add `IsUnplayed/IsPlayed` filters the ordering is wrong, it should just filter out the played/unplayed items, yet it also changes the sorting back to "SortName".

This happens with AndroidTv and Webclient so its a server issue.

### Jellyfin Version

10.8.0

### Environment

```markdown
- Clients: AndroidTv, Webclient
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jamesmurphy746** [comment]
I seem to be experiencing Timeout errors on AndroidTV client seemingly around the same time it's trying to populate 'next up'.. I wonder if this could be related?
