### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by banzo** [jellyfin/jellyfin#825]
Add FreeBSD support 

Since #95 is done, would it just be a matter of adding a build script (#335)?

This would be a first step to get a Freenas plugin (#346)

**Comment by horizonbrave** [comment]
looking forward to it, thanks!

**Comment by onny** [comment]
Of course this depends on having dotnet core running on FreeBSD and it seems there is some progress to get it supported: https://github.com/dotnet/corefx/issues?q=freebsd+label%3Aos-freebsd
Instructions on how to build it (maybe outdated): https://github.com/dotnet/corefx/wiki/Building-.NET-Core--2.x-on-FreeBSD

**Comment by amarshall** [comment]
The corefx repo has been moved, so the links above are now: [tickets labelled os-freebsd](https://github.com/dotnet/runtime/labels/os-freebsd) and [main ticket](https://github.com/dotnet/runtime/issues/14537). The “old” instructions seem to still to be the most up-to-date; there’s a [ticket for rewriting them](https://github.com/dotnet/runtime/issues/31238).

**Comment by srcrist** [comment]
Closing this issue as it does not contain a Jellyfin bug. I have taken the liberty of migrating this proposal to the feature request site at https://features.jellyfin.org/posts/2367/freebsd-support where it can be further monitored and discussed.
