### ISSUE TITLE
[Issue]: Secondary metadownloaders usually ignored on series matching.

### ISSUE THREAD

**Issue by Sorek** [jellyfin/jellyfin#8254]
### Please describe your bug

Issue:  Jellyfin will use the first series metadownloader even on an extremely poor match.  This happens even if a much better match exists on a secondary source.

Steps to Reproduce:
1.  Enable Anilist and TMDB as a source in the same library. 
2.  Put Anilist as the primary source.
3.  Create series folder "The Last Ship" with some files.
4.  Anilist will identify it as "Case Closed: The Lost Ship" (emphasis LOST and not Last)
5.  Jellyfin completely ignores the fact that a 100% perfect match exists on the secondary source.

Expected Behavior:  It will pick a perfect match over a poor one.

### Jellyfin Version

Other

### if other:

10.8.3

### Environment

```markdown
- OS: Windows 10 64
- Virtualization: None
- Clients: Chrome
- Browser: Chrome
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins: AniList
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 1337joe** [comment]
The plugin itself reports when it's found a match, Jellyfin just accepts the first provider (according to the configured ordering) that says it's got the item.

Does this happen with anything besides the anilist plugin as the first provider? I looked into an anilist-related bug report sometime last year and seem to remember finding that the anilist plugin has no logic to determine if what it finds actually matches the item so it just accepts the top search result and reports success.
