### ISSUE TITLE
Playing H264 file who contain DOVI side_data is being transcoded

### ISSUE THREAD

**Issue by antipiot** [jellyfin/jellyfin#8260]
Hello there!

i'm not sure about what is causing what i feels to be a bug, but first let me explain what im trying to acheive:
I try to uniformize my library, doing so, i convert all my files to h264 8 bits and aac audio in order to avoid transcodes as much as possible.
When the file is HDR, i tonemap it.

The file below was converted using tonmap to h264: Once this file is played trough jellyfin, it get's transcoded, as it appears in Edge, due to DOVI informations.
Once again, my goal is to avoid transcodes:
- Are thoses DOVI indormations usable in h264?
- - If not, may be interstind to check for dovi or other side data only on h265 files
- if they are: and idea on how i can get rid of thoses "side_data"?

```
[SIDE_DATA]
side_data_type=DOVI configuration record
dv_version_major=1
dv_version_minor=0
dv_profile=8
dv_level=6
rpu_present_flag=1
el_present_flag=0
bl_present_flag=1
dv_bl_signal_compatibility_id=1
[/SIDE_DATA]
```

**Media Info of the file**
[file.txt](https://github.com/jellyfin/jellyfin/files/9333019/file.txt)

**Stats for Nerds Screenshots**
Fun fact, stats for nerd dont show the same message under edge than FF
Stats as displayed on edge
![image](https://user-images.githubusercontent.com/26579988/184531335-5786fc37-25f3-4eda-be35-ede9cba2aeb8.png)
Stats as displayed on FF
![image](https://user-images.githubusercontent.com/26579988/184531343-7d4706c9-fbad-4347-80d9-5725c5b2429a.png)

**Server System (please complete the following information):**
 - OS: Docker
 - Jellyfin Version: Latest
 
**Client System (please complete the following information):**
 - Browser (if Web client): Edge and FF

If you need more informations or tests, please let me know!

Regards - JS

**Comment by nyanmisaka** [comment]
You transcoded a DOVI Profile 8 (HDR10 compatible) video without stripping its DOVI side data, which is used by Jellyfin to identify DOVI HDR files. Solution is to extract the raw video and audio data and then remux.

```
ffmpeg -y -i h264_with_dovi_p8_sd.mkv -map 0:v -c:v copy raw.h264 -map 0:a -c:v copy raw.aac
ffmpeg -i raw.h264 -i raw.aac -c copy h264_fixed.mkv
```

**Comment by antipiot** [comment]
> You transcoded a DOVI Profile 8 (HDR10 compatible) video without stripping its DOVI side data, which is used by Jellyfin to identify DOVI HDR files. Solution is to extract the raw video and audio data and then remux.
> 
> ```
> ffmpeg -y -i h264_with_dovi_p8_sd.mkv -map 0:v -c:v copy raw.h264 -map 0:a -c:a copy raw.aac
> ffmpeg -y -i raw.h264 -i raw.aac -c copy h264_fixed.mkv
> ```

Thanks for your help! that was pretty much my guess!
Thing is that id' like to keep the other usefull metadata and audio tracks that may come along in a one-liner.

How to get rid of thoses informations in only one line? isn't there a flag or something?
Should this not be ignored by Jellyfin when the file cant actually be HDR 10?

Regards!

**Comment by antipiot** [comment]
kind of related:
https://github.com/mpv-player/mpv/issues/9982

**Comment by nyanmisaka** [comment]
> Thing is that id' like to keep the other usefull metadata and audio tracks that may come along in a one-liner.

1. Use an older ffmpeg < 4.4 that doesn't support DOVI sidedata to transcode your video.
2. Or use pipe and nut container:
`ffmpeg -i "h264_with_dovi_p8_sd.mkv" -an -sn -c copy -f nut - | ffmpeg -i - -i "h264_with_dovi_p8_sd.mkv" -map 0:v -map 1:a -c copy -y h264_fixed.mkv`

> How to get rid of thoses informations in only one ffmpeg task? isn't there a flag or something? Should this not be ignored by Jellyfin when the file cant actually be HDR 10?

There's a [`sidedata` filter](https://github.com/FFmpeg/FFmpeg/blob/master/libavfilter/f_sidedata.c) to modify the sidedata field of AVframe but [DOVI has not been added](https://github.com/FFmpeg/FFmpeg/blob/c6f22940e442ac2d2142ec9dce7ed8474c97aad2/libavutil/frame.h#L199-L211) into it. You have to modify the source code and compile a custom ffmpeg and then [insert it into the filter chain](http://ffmpeg.org/ffmpeg-all.html#sidedata_002c-asidedata) during the transcoding.

> PS: Why does Edge and FF show different "transcoding Reasons" for the same thing? Edge infos helped me to confirm what i was suspecting.

IIRC mkv container is not supported in FF, which should be the cause.

**Comment by antipiot** [comment]
> 

Many thanks for all thoses informations.
I guess i'll wait a bit for AVframe to support this!

**Comment by ThewBear** [comment]
@antipiot 
> I guess i'll wait a bit for AVframe to support this!

I tested on the latest master branch and the `sidedata=delete` filter works now. May be because of this commit https://github.com/FFmpeg/FFmpeg/commit/2621be35397291c03c9a48c28e9283404899868a

**Comment by antipiot** [comment]
> @antipiot
> 
> > I guess i'll wait a bit for AVframe to support this!
> 
> I tested on the latest master branch and the `sidedata=delete` filter works now. May be because of this commit [FFmpeg/FFmpeg@2621be3](https://github.com/FFmpeg/FFmpeg/commit/2621be35397291c03c9a48c28e9283404899868a)

Hey!
Thanks a lot for your check!
