### ISSUE TITLE
[Issue]: Merging multiple movie libraries into movies category requires full library access

### ISSUE THREAD

**Issue by rTiGd2** [jellyfin/jellyfin#8263]
### Please describe your bug

I have three different 'Movie' libraries and have set-up to collate all of these into the single Movies category.
If I don't enable a user with 'full access' but still give them access to all of the libraries individually, they don't see any movies in the grouped category at all, it's just a blank grid.
I haven't tried to split out one or more of the libraries from their access to test but I suspect if it happens when they have all access individually (but not access to all libraries) breaks things, I suspect the same would create the issue

### Jellyfin Version

Other

### if other:

10.8.3

### Environment

```markdown
- OS: Ubuntu 22.10
- Virtualization: N/A
- Clients: Android TV (NVIDIA Shield)
- Browser: N/A
- FFmpeg Version: Packaged
- Playback Method: N/A
- Hardware Acceleration: N/A
- Plugins: N/A
- Reverse Proxy: N/A
- Base URL: N/A
- Networking: N/A
- Storage: NFS
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shadowghost** [comment]
Likely fixed by #8526
