### ISSUE TITLE
ID not working after updates

### ISSUE THREAD

**Issue by jimlynnjulian** [jellyfin/jellyfin#8264]
### Please describe your bug

Prior to updates, Identify worked with nothing but an IMDB number, e.g. tt0123456.
Now, even with name and year included, the process does not work.
Unless the updates changed some settings, there seems to be a problem.

Win11 Pro-x64
jellyfin 10.8.3

### Jellyfin Version

10.8.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
What do you mean by Identify? Are you referring to manual identify via the web ui or automatic during scan?

Please provide logs

**Comment by jimlynnjulian** [comment]
I'm using the web app on the LG browser. The drop-down menu item (along with metadata, images, etc)
[log_20220830.zip](https://github.com/jellyfin/jellyfin/files/9457093/log_20220830.zip)
