### ISSUE TITLE
CoverArt Plugin

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin#828]
**Describe the feature you'd like**
In Emby, a premium plugin is available that edits the media posters to have a "frame", like a blu-ray case, or a CD case. This frame is often tied to the quality of the file, so a 4K/2160p file would have a 4K case on it, etc.

Since this plugin was never publicly available, this is more of a request that a similar thing gets created, if possible.

**Additional context**
This request is filed as per this post on the forum: https://forum.jellyfin.org/t/emby-coverart-plugin/65?u=anthonylavado

**Comment by BobOkisama** [comment]
I would love to see this added. It was one of my fav plugins and REALLY made identifying your media so much easier at a glance.

**Comment by anthonylavado** [comment]
Tagging in #480, as that is now closed, and this was requested in it.
