### ISSUE TITLE
[Issue]: Jellyfin in Docker fails to start on boot because of /dev/dri/renderD128, but works when restarting the container

### ISSUE THREAD

**Issue by spagootie** [jellyfin/jellyfin#8282]
### Please describe your bug

 I've been trying to get hardware encoding with VAAPI working in Docker on my RX 6600. I followed the jellyfin hardware encoding docs, and here's my docker run command for the container:

`docker run -d --user 953:953 -e JELLYFIN_CACHE_DIR=/var/cache/jellyfin -e JELLYFIN_CONFIG_DIR=/etc/jellyfin -e JELLYFIN_DATA_DIR=/var/lib/jellyfin -e JELLYFIN_LOG_DIR=/var/log/jellyfin --mount type=bind,source=/etc/jellyfin,target=/etc/jellyfin --mount type=bind,source=/var/cache/jellyfin,target=/var/cache/jellyfin --mount type=bind,source=/var/lib/jellyfin,target=/var/lib/jellyfin --mount type=bind,source=/var/log/jellyfin,target=/var/log/jellyfin --mount type=bind,source=/mnt/media,target=/media --net=host --restart=always --group-add=989 --device /dev/dri/renderD128:/dev/dri/renderD128 jellyfin/jellyfin`

User 953 is part of the render group, and group 989 is the render group, although user 953 is part of the render group anyway. When I start my computer, the Jellyfin container fails to start, but when I manually restart it, it works fine. When I inspect the container after booting, it says this is why it failed:

`error gathering device information while adding custom device "\/dev/dri/renderD128\": no such file or directory.`

I'm running Arch Linux with libva-mesa-driver 22.1.6-1 and mesa 22.1.6-1.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Arch Linux
- Virtualization: Docker
- Clients:
- Browser:
- FFmpeg Version: 
- Playback Method:
- Hardware Acceleration: vaapi
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
This sounds like docker is starting before your gpu is initialized, doesnt sound like a Jellyfin issue but a docker one.

**Comment by nyanmisaka** [comment]
Try to add 60sec startup delay to the docker service.

**Comment by spagootie** [comment]
> Try to add 60sec startup delay to the docker service.

This fixed the problem, and the container starts.  But, when I try to connect, jellyfin gives the "We're unable to connect to the selected server right now. Please ensure it is running and try again." error. It's probably unrelated though.
