### ISSUE TITLE
[Issue]: Audio track and subtitle not set when a show episode end

### ISSUE THREAD

**Issue by Ale4224** [jellyfin/jellyfin#8286]
### Please describe your bug

When i'm whatching a tv show with an audio track and/or a subtitle that is not the default one, and i finish an episode, the next episode doesn't keep the audio and subtitle track choosen set, but it shows that it is set, so i need to set another one first and then set the one i want back

Step to reproduce:

- watch a tv show with multiple audio track and/or subtitles
- choose a different audio track/subtitle than the defualt one
- go to next episode

Expacted:
- the choosen audio trak/subtitle is kept in the next episode

What happen instead:
- the default audio track/subtitle are playing, but the choosen audio trakc/subtitle are selected

### Jellyfin Version

10.8.0

### if other:

10.8.4

### Environment

```markdown
- OS: Windows 10 pro
- Virtualization: no
- Clients: Browser
- Browser: Chrome 104.0.5112.101
- FFmpeg Version: 2021-09-11-git-3e127b595a-full_build-www.gyan.dev
- Playback Method: don't know
- Hardware Acceleration: none
- Plugins: none
- Reverse Proxy: none
- Base URL: none
- Networking: Host
- Storage: local
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Plinz** [comment]
Same issue on 10.8.4.
- OS: Linux
- Virtualization: no
- Clients: Browser
- Browser: Firefox 105.0.1
- FFmpeg Version: 5.1.1
- Playback Method: Streaming direct
- Hardware Acceleration: none
- Plugins: none
- Reverse Proxy: nginx
- Base URL: /jellyfin
- Networking: Host
- Storage: local
