### ISSUE TITLE
[Issue]: Actor thumbnails not loading untill clicked

### ISSUE THREAD

**Issue by Maypul** [jellyfin/jellyfin#8288]
### Please describe your bug

Hello,
I can not seem to get to work actors thumbnails to work otu of the box. They appear blank until I click on them, then, they are loaded and displayed correctly afterwards. I have browsed forums and issue hub, there seems to be some topics on it, some fixes but maybe my specific scenario is just not applicable.

Since my local data is already placed with the movie Jellyfin loads it just fine and it seems to be also using links from .nfo file for actors. If the link is working Jellyfin loads the link from nfo, connects to the internet and downloads the picture. If the link is outdated (which happens occasionaly, pictures do update), Jellyfin simply will wait for the user to click on blank actor and then it seems to look for the actors for itself and download the correct data. I have tried emptying the links in nfo and leaving them blank in hope Jellyfin would detect there is no link and manage the data for itself, but no success. I guess data must be 100% managed by Jellyfin or 100% local with correct links to online repository... so not that local.

Now, my local database is managed by TinyMediaManager and I do have .actors directory but I understand Jellyfin does not read it, it is fine. Ideally I would love to see an option that would allow me to check that Jellyfin always manages actors by itself, since it has bigger database on them than TMM (with actor descriptions), Right now even If I disable all online providers the actor database is still loaded online once you click on blank actor. So funcionality seems to be here, just would be nice to have it somehow enabled and not needed the user input aka clicknig on each actor separately.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Docker on Synology DMS 7
- Virtualization: Docker
- Clients: Firefox
- Browser: Firefox
- FFmpeg Version: N/A
- Playback Method: N/A
- Hardware Acceleration: N/A
- Plugins: N/A
- Reverse Proxy: Traefik
- Base URL:
- Networking:
- Storage:
```

### Please attach any screenshots here

Jack Black has working link to tmdb in nfo and Oliver Platt not: https://prnt.sc/q6p88MB5L5q5
Clicking on Olivier, Jellyfin laods the data itself, library providers all are unckecked: https://prnt.sc/asaRDje3fuy2
Now it works: https://prnt.sc/zAmtp_PGs-MD

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by onthecliff** [comment]
also have this issue

**Comment by RainyDAy59** [comment]
I have this issue as well.  Only some of the actor images show up; the rest either require clicking to populate them onto the screen, or I have to locate them online, download them onto my computer, and then upload them into Jellyfin, which is an incredibly tedious process.

**Comment by gummykage** [comment]
This issue is happening on a brand new install through docker.

**Comment by toni-do** [comment]
> Same issue. Jellyfin 10.8.9 in docker. When I select a movie and click on "Refresh metadata" for that movie the following gets logged (seems one entry for every actor):
> 
> ```
> > [2023-02-27 19:16:02.390 +01:00] [WRN] [13] Emby.Server.Implementations.Library.LibraryManager: Cannot fetch image from "http://image.tmdb.org/t/p/w185/snVedHnRxdD16RdcDhRJbGyvbUF.jpg"
> > System.InvalidOperationException: Operation is not valid due to the current state of the object.
> >    at Emby.Server.Implementations.Library.LibraryManager.ConvertImageToLocal(BaseItem item, ItemImageInfo image, Int32 imageIndex)
> >    at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
> ```

Long story short: delete the thumb line in the nfo file and refresh the metadata.

I have migrated from Kodi to Jellyfin. The library was managed by tinymediamanager. tinymediamanager has stored the URL to the actor's thumb in the nfo file which is stored in the same directory as the video file. It looks like this:
```
  <actor>
    <name>Bruce Willis</name>
    <role>John McClane</role>
    <thumb>http://image.tmdb.org/t/p/w185/kI1OluWhLJk3pnR19VjOfABpnTY.jpg</thumb>
    <profile/>
  </actor>
```
Jellyfin seems to prefer the URL stored in the nfo file and fails to download the image because the URL is invalid (for whatever reason). Delete the line and refresh the metadata. 

I recommend to test it with one actor of one movie first, before modifying all the nfo files. Don't forget reload the current webpage (CTRL + F5) to see the newly downloaded pictures.

Jellyfin should try do download the image from a different source if it fails to download the image from the URL stored in the nfo file.

**Comment by Stefan300381** [comment]
same issue here, same situation with moving from kodi / tinymediamanager to jellyfin.
@toni-do do you use any automation script to remove the given line from the nfo files? I cannot open 1000 directories and replace the line manually ;-)

**Comment by toni-do** [comment]
> same issue here, same situation with moving from kodi / tinymediamanager to jellyfin. @toni-do do you use any automation script to remove the given line from the nfo files? I cannot open 1000 directories and replace the line manually ;-)

If you are on Linux and your movies are stored in path lets say "/mnt/movies", then you can run these 4 one-liners:
`for NFO in $(find /mnt/movies -iname "*.nfo"); do sed -i "/<thumb>http:\/\/image.tmdb.org/d" $NFO; done`
`for NFO in $(find /mnt/movies -iname "*.nfo"); do sed -i "/<thumb>https:\/\/image.tmdb.org/d" $NFO; done`
`for NFO in $(find /mnt/movies -iname "*.nfo"); do sed -i "/<thumb>http:\/\/ia.media-imdb.com\/images/d" $NFO; done`
`for NFO in $(find /mnt/movies -iname "*.nfo"); do sed -i "/<thumb>https:\/\/ia.media-imdb.com\/images/d" $NFO; done`

That will remove all lines from every nfo file which contains:
<thumb>http://image.tmdb.org
<thumb>https://image.tmdb.org
<thumb>http://ia.media-imdb.com/images
<thumb>https://ia.media-imdb.com/images

Please change the path to your movies. Use it on your own risk.

**Comment by npgockel** [comment]
Same issue on Windows Server

**Comment by toni-do** [comment]
Please also try to a increase "The maximum number of cast members to fetch for an item." The setting can be found in Dashboard -> Plugins -> tmdb settings.

**Comment by jdyz** [comment]
Same issue on version 10.8.10, but only for movies,  Actor thumbnails are normal for the content type shows .
And I have tested versions from 10.7.7 to 10.8.10,  only version 10.7.7 works.

**Comment by gummykage** [comment]
![image](https://github.com/jellyfin/jellyfin/assets/9695713/a7a1b2a5-cb6c-4a79-b7e7-6bb12515a3c8)

Having the same issue. If I click on the actor it will then load the thumbnail.

**Comment by gummykage** [comment]
Actor images are not working for TV shows or Movies unless clicked on, Brand new install, It appears the problem stems from the actor image are stored in local paths and if they already existed skia library doesn't create a thumbnail for the main page unless you click on it and it detects its missing.

**Comment by gummykage** [comment]
Last thing, the easiest way to fix this if you find yourself deleting <thumb> would be to have Tiny Media Manager re-scrape your problem movies and disable saving metadata to .nfo in jellyfin until this is fully fixed.

**Comment by gummykage** [comment]
![image](https://github.com/jellyfin/jellyfin/assets/9695713/113361bb-9323-41c1-aeb6-6b32f0ea2fd8)
Disable this causes nfo actor image path to be modified to a local path which causes the bug if you use the same nfo file in a completely new instance of JF.

**Comment by gummykage** [comment]
You can leave the <thumb> url to imdb for actor img </thumb> by un ticking store metadata in the library settings after all your original nfo files have been fixed, for new adds from Tiny Media Manager.

**Comment by peterzolczer** [comment]
I have this very issue on my fresh install on docker, 10.8.10. Blurry or no (cover/artist/poster/etc.) images, doesn't matter whether I use a client or open it in browser:

![image](https://github.com/jellyfin/jellyfin/assets/121183484/923ff271-ab21-41d9-8b6f-a3b96b2524a8)

**Comment by deltonio2** [comment]
You can find a workaround to get all actors photos of your server here : https://github.com/jellyfin/jellyfin/issues/8103#issuecomment-1730783019

**Comment by srcrist** [comment]
Closing this issue as a duplicate of https://github.com/jellyfin/jellyfin/issues/8103

**Comment by quincarter** [comment]
I deleted all my .nfo files and jpg/pngs stored with my content and did a complete rescan. I got actor images. 

I can tell you my nfo files are from Emby or Kodi. Not sure if there's a disconnect there between jellyfin. But every item now has a full actor list. I'm also not 100% sure about the use case of an nfo file in jellyfin/emby/kodi. If someone could explain that to me then I'd appreciate that. 

My educated guess is it gives somewhat of a cache for the stored metadata of a piece of content. If I modify the metadata, will it save there?

**Comment by herigrosir** [comment]
Actor thumbnails not loading untill clicked
this bug jellyfin

**Comment by qingbo** [comment]
I started to use tmm+jellyfin recently. I applied optimal settings for Jellyfin in tmm and noticed that Jellyfin (10.11.8) displays actor thumbnails for TV series but not for movies. All fetchers are disabled in both Jellyfin libraries.

Then I noticed the difference in NFO settings of tmm - "TV Shows" section has "Add artwork URLs to the NFO" enabled. I enabled this option for in NFO settings in movies section, re-scraped the movies, and Jellyfin can now show actor thumbnails for the movie library too.

Note - when you hover on that checkbox it says something like "when using Jellyfin you may want to disable this". Once enabled, tmm adds `<thumb>` to `<fanart>`, `<actor>` tags in the .nfo files.

Hope this helps.
