### ISSUE TITLE
[Issue]: Auto-loop live streams not working | m3u8 live streams stopping

### ISSUE THREAD

**Issue by DesertCookie** [jellyfin/jellyfin#8289]
### Please describe your bug

The option `Auto-loop live streams` does not seem to work. I added an m3u8 file live stream with the following content (German public TV):

```
#EXTM3U
#EXTINF:-1,ZDF neo
https://zdf-hls-16.akamaized.net/hls/live/2016499/de/high/master.m3u8
```

This file worked with an old installation previously (possibly `10.6`, if I remember correctly). Now, the stream stops after 40-60 seconds. All live recordings are exactly one minute in length.

There is no difference in behavior with the option enabled or disabled. I confirmed that the stream needs to be looped by enabling looping in VLC which successfully plays the stream (dropping a few frames every loop).

I have tested with `10.8.1` and `10.8.4`.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Docker (unRAID)
- Clients: Jellyfin Media Player, Android App (Exo player), Firefox (desktop, mobile)
- Browser: Firefox
- Hardware Acceleration: 11600K iGPU
- Reverse Proxy: Nginx Proxy Manager
```

### Jellyfin logs

Nothing immediately apparent (See [here](https://nc.rhprivat.de/s/Nzy64oEfcAbHrff)).

**Comment by mflage** [comment]
Does this work on 10.8.0-beta3?

**Comment by DesertCookie** [comment]
On that version, I cannot even get it to play the live streams. I get the server isn't sending a compatible media format error. In fact, I seem to get that a lot where it didn't use to happen ever since 10.8.x. I have only noticed it now though as I've not been watching a lot.

**Comment by mac-lucky** [comment]
Same problem for me on newest jellyfin 10.8.9
