### ISSUE TITLE
[Issue]: Android client does not connect to remote server via domain (nginx reverse proxy)

### ISSUE THREAD

**Issue by WubzyGD** [jellyfin/jellyfin#8302]
### Please describe your bug

Hello! I just got Jellyfin set up last night. I set up a subdomain, jelly.wubzy.xyz, got it an https certificate, DNS done, and got it an nginx reverse proxy - the works. Overall, it is working fine.

This instance is **not on my home network**, and **works with 0 issues on web clients**, both on the remote network and mine.

My issue is that the mobile client (I've tried official and findroid) does not connect to the remote server when trying to use jelly.wubzy.xyz. If at all possible, I would like to avoid port forwarding as a solution to this issue, as it is exclusive to the mobile app. (See screenshot of connection attempt result below).

I have tried a fair number of things to sniff out the error, with no luck. My phone and PC both have no issues connecting to the sever via the web clients, and all of the proxies nginx is running (6 or 7) are being connected to with no issues on both my phone and PC. I am running on an unmodded, unrooted s22 ultra, with no tweaks to my network or anything like that. I've checked both access and error logs for nginx, and neither produce _any_ log when I attempt to connect via the mobile app, suggesting that the app is not properly trying to connect.

Is it just not possible to use a domain name to connect via the mobile app? Is there a piece I'm missing?

See [this reddit post](https://www.reddit.com/r/jellyfin/comments/wupnmy/remote_connect_to_proxied_jellyfin_through_app/) where I initially brought up the issue.

### Jellyfin Version

Other

### if other:

10.8.4

### Environment

```markdown
- OS: Windows (host)
- Virtualization:
- Clients: Android (Official)
- Reverse Proxy: Nginx
- Base URL: jelly.wubzy.xyz
```

### Please attach any screenshots here

![image](https://user-images.githubusercontent.com/63122940/186120921-895d0825-7f37-4947-a0ce-8291216059c6.png)

The **same result** is produced when prepending with `https://`, `http://`, adding my port, adding trailing slashes, and effectively all combinations of the like. (Yes I know those tests are mildly excessive, but debugging is debugging)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nielsvanvelzen** [comment]
Opening your server and it redirects to the base url `/jelly`. Have you tried entering `jelly.wubzy.xyz/jelly` as URL in the app?

**Comment by WubzyGD** [comment]
i'm gonna go cry
Thanks for having a keen eye @nielsvanvelzen 

i swear i removed the base url!!
