### ISSUE TITLE
[Issue]: unable to start service

### ISSUE THREAD

**Issue by jahanson** [jellyfin/jellyfin#8303]
### Please describe your bug

I'm having an issue with starting the jellyfin service on fedora36. It runs fine if I cd to `/var/lib` and `sudo runuser -u jellyfin /usr/lib64/jellyfin/jellyfin`. The service file doesn't have much in it at all so i'm just at a loss here. It's the stock service file for the latest rpm (10.8.4).

### Jellyfin Version

Other

### if other:

10.8.4

### Environment

```markdown
- OS: Fedora 36 Workstation
- Virtualization: none
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
no logs captured besides the service failure

× jellyfin.service - Jellyfin Media Server
     Loaded: loaded (/usr/lib/systemd/system/jellyfin.service; disabled; vendor preset: disabled)
    Drop-In: /etc/systemd/system/jellyfin.service.d
             └─override.conf
     Active: failed (Result: exit-code) since Tue 2022-08-23 09:07:04 CDT; 2s ago
    Process: 3737 ExecStart=/usr/bin/jellyfin ${JELLYFIN_WEB_OPT} ${JELLYFIN_RESTART_OPT} ${JELLYFIN_FFMPEG_OPT} ${JELLYFIN_SERVICE_OPT} ${JELLYFIN_NOWEBAPP_OPT} ${JELLYFIN_ADDITIONAL_OPTS} (code=exite>
   Main PID: 3737 (code=exited, status=137)
        CPU: 6ms

Aug 23 09:07:04 s01 systemd[1]: jellyfin.service: Scheduled restart job, restart counter is at 5.
Aug 23 09:07:04 s01 systemd[1]: Stopped jellyfin.service - Jellyfin Media Server.
Aug 23 09:07:04 s01 systemd[1]: jellyfin.service: Start request repeated too quickly.
Aug 23 09:07:04 s01 systemd[1]: jellyfin.service: Failed with result 'exit-code'.
Aug 23 09:07:04 s01 systemd[1]: Failed to start jellyfin.service - Jellyfin Media Server.
```

### Please attach any screenshots here

This is a fresh installation of Fedora 36 Workstation and I'm at a loss for how to get this thing running from the service.

I've tried starting the service as normal

![2022-08-23 09_07_54-Element _ Jellyfin Troubleshooting](https://user-images.githubusercontent.com/1548511/186180570-ab669045-db11-4cae-a81d-0c2ab9ae3bb5.png)

But the only way to get it to work is to `cd /var/lib && sudo runuser -u jellyfin /usr/lib64/jellyfin/jellyfin`

![2022-08-23 09_08_42-Element _ Jellyfin Troubleshooting](https://user-images.githubusercontent.com/1548511/186180721-294217a1-8b82-4ccc-b8ad-7cf9f85172c0.png)

The service file is stock from the 10.8.4 RPM.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jahanson** [comment]
This was an issue with SELinux and adding all of the exceptions it needs got it working through systemd.

**Comment by bv101rj** [comment]
> This was an issue with SELinux and adding all of the exceptions it needs got it working through systemd.

Do you still have the change you made on hand for this? I have made several, however its not had much effect.

**Comment by bv101rj** [comment]
Thank you very much, I should be able to piece the rest together from there.

Normally using Gentoo / Artix so SELinux isn't something I have had to mess with in almost 6 years.
