### ISSUE TITLE
[Issue]: No "critics rating" for series.

### ISSUE THREAD

**Issue by arielherself** [jellyfin/jellyfin#8307]
### Please describe your bug

Currently, I can only customise critics rating for movies rather than series, and automatic metadata fetcher also doesn't retrieve critics rating for movies. Can you add the feature to Jellyfin? Your work is greatly appreciated.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Ubuntu 22.04LTS
- Virtualization: KVM
- Clients: Browser
- Browser: Chrome 104
- FFmpeg Version: irrelevant
- Playback Method: irrelevant
- Hardware Acceleration: irrelevant
- Plugins: none
- Reverse Proxy: none
- Base URL: none
- Networking: Host
- Storage: cloud
```

### Jellyfin logs

```shell
~
```

### FFmpeg logs

```shell
~
```

### Please attach any browser or client logs here

~

### Please attach any screenshots here

~

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by daullmer** [comment]
The automatic fetching should be working. What metadata provider are you using? 
You just can't edit the rating in the metadata editor
