### ISSUE TITLE
[Issue]: Jellyfin only detecting one episode of entire TV series

### ISSUE THREAD

**Issue by owenashurst** [jellyfin/jellyfin#8328]
### Please describe your bug

Jellyfin is only detecting one episode of a TV series.

Folders named as; Series 1, Series 2, Series 3, Series 4, Series 5, Series 6, Series 7

Episodes named as; 
1.01 Big Brother
1.02 Go West Young Man
etc...

### Jellyfin Version

Other

### if other:

10.8.4

### Environment

```markdown
- OS: Ubuntu Server 20.04 LTS
- Virtualization: Docker
- Clients: All
- Browser: All
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Please attach any screenshots here

![image](https://user-images.githubusercontent.com/4403436/187039533-8edd933d-4bca-4b32-a15e-eae8e41c7e35.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
What plugins do you have installed?
Please try Jellyfin v10.8.4.
Please post your actual structure, not just a summary of it.
Does this happen to all shows, or only this one?

**Comment by owenashurst** [comment]
> What plugins do you have installed? Please try Jellyfin v10.8.4. Please post your actual structure, not just a summary of it. Does this happen to all shows, or only this one?

Plugins wise;
![image](https://user-images.githubusercontent.com/4403436/187079581-0b64b2c6-2cb4-4627-9451-1c5eecc9b168.png)

Folder structure should have been fairly self explanatory...

TVSeries
  - Only Fools and Horses
      - Series 1
          - 1.01 Big Brother
          - 1.02 Go West Young Man

This doesn't happen to any other show, this is the only one I've noticed it doing it to. It's also the only one I've seen the filename as `<season>.<episode> <name>`. Normally they're named as `<name>.S01E01`.

**Comment by owenashurst** [comment]
It appears to be taking the first part of the filename which in this case, is the season, and marking each episode as that number. E.g. Season 3, all episodes appear as episode 3, Season 4, all episodes appear as episode 4, etc.

**Comment by crobibero** [comment]
That isnt a supported naming scheme so Im not surprised that it didnt work.

**Comment by owenashurst** [comment]
> That isnt a supported naming scheme so Im not surprised that it didnt work.

Which is what I expected, however I have seen that naming convention used before. I'm presuming there's a way to expand on the existing naming parser to include it? I don't mind submitting a PR if you could point me in the right direction as to where that may be please?

**Comment by srcrist** [comment]
The need to adhere to the naming conventions in the Jellyfin documentation is an intentional design choice that various aspects of the server use to parse the media and its metadata. Closing this issue as it is not actually a bug. Feel free to submit a feature request at features.jellyfin.org if you would like to request that additional naming schemes be supported.
