### ISSUE TITLE
[Issue]: Multiple seasons being merged into one, possibly being caused by number in show name.

### ISSUE THREAD

**Issue by justinbyoung** [jellyfin/jellyfin#8336]
### Please describe your bug

All seasons merged into one with Show that contains a number. I have two shows, 8 Out of 10 Cats and 8 Out Of 10 Cats does Countdown. All episodes are being put into Season 8 except for specials.

Looking at the Metadata for each episode the correct season and episode numbers are detected.

I have included a screenshot with an episode with the correct metadata, but it is still placed in the incorrect season.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Debian
- Virtualization: Proxmox
- Clients:  Android TV
- Browser: Chrome
- FFmpeg Version:
- Playback Method:Direct
- Hardware Acceleration: Quicksync
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Please attach any screenshots here

![image](https://user-images.githubusercontent.com/27791449/187101201-0a9efbc6-81dd-483b-b3ce-c58617d5f6b7.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by justinbyoung** [comment]
I managed to find a manual fix for this. I noticed when I selected the Season 8 folder in the list, the path was for a different season. I changed the season title and season number to the season from the path, saved the entry, refreshed the metadata for the season, reloaded the page and it had added that season while keeping season 8. Season 8 had then had the path of yet another season. I repeated this for each season. Very manual as each of those shows has over 20 seasons.

**Comment by justinbyoung** [comment]
This bug still exists in 10.8.8. New episodes of 8 Out of 10 Cats Does Countdown are still being set as being in Series 8.

**Comment by Dnkhatri** [comment]
This is not happening for me what naming convention do you use. And are you using sonarr?

**Comment by justinbyoung** [comment]
An example file name for the latest episode. Yes using sonarr for renaming. 

8 Out of 10 Cats Does Countdown - S24E01 - Jonathan Ross, Joe Wilkinson, Roisin Conaty, Ahir Shah.mkv

Issue also happens with the show Avenue 5, all episodes are put into season 5, despite there only being two seasons.

**Comment by Dnkhatri** [comment]
That what I use too. Maybe because I am using sonarr to generate kodi/emby metadata.nfo files jellyfin is getting the correct info.
