### ISSUE TITLE
Optimize IP TV with low speed

### ISSUE THREAD

**Issue by AnonymousWebHacker** [jellyfin/jellyfin#8337]
### Situation:
- Relatively low internet speed 2 mb/s
- Live TV transmission in FullHD that needs example 10 mb/s
![DeepinScreenshot_Seleccionar área_20220828204543](https://user-images.githubusercontent.com/43164089/187102594-25c140c9-ff43-4ce5-b61e-7e8b686196f4.png)

**What I am going to write later is possible with nginx , as a cache server.**

### Problem:
 Having a limited speed from the TV provider, to a jellyfin server, and your intermediary ISP, is only 2 MB/s speed, it is impossible to watch a transmission without problems.

### Solution:
In the jellyfin server in charge of resecting the TV show, you can store the transmission locally at a speed of 2 mb/s, and once the buffer is stored, transmit to the clients.
The transmission jellyfin server - jellyfin clients, will have a slight delay in time in terms of transmission in real time.

###  To implement:
Add to the jellyfin server the nginx option to cache the transmission.

**Comment by Bond-009** [comment]
This is a feature request: https://features.jellyfin.org
