### ISSUE TITLE
SSL Certificate Chain

### ISSUE THREAD

**Issue by robsee** [jellyfin/jellyfin#8340]
It seems that even if you add the full certificate chain to the p12 file, the https server only serves out the server certificate. This breaks iOS clients if your cert chain has any intermediate certificates in it.

**Comment by crobibero** [comment]
Looks like it should be possible in dotnet 7.
https://github.com/dotnet/aspnetcore/issues/21513

**Comment by flip-dots** [comment]
I am not certain but I think this is why I cannot play music served from Jellyfin on my Sonos speakers over DNLA. They require the full certificate chain to work over https.

**Comment by flip-dots** [comment]
> 

Nevermind, it seems to be working now. Issue was when Jellyfin sent the media URL to the player it sent the IP address not the domain name, I fixed it by adding this to network.xml for each sonos player

<PublishedServerUriBySubnet>
    <string>[IP of Sonos Player]/24=[Jellyfin domain name]:8920</string>
  </PublishedServerUriBySubnet>

**Comment by sjorge** [comment]
Well, looks like i can step messing with my p12. I was trying to figure out why i was not gettint a correct chain (and thus issues on iOS)

**Comment by robsee** [comment]
> Well, looks like i can step messing with my p12. I was trying to figure out why i was not gettint a correct chain (and thus issues on iOS)

I'm thinking of putting haproxy in front of mine to handle the SSL.  That being said If you are using it with the Kodi addon, video playback is terrible with SSL enabled on that platform.

**Comment by bertmelis** [comment]
It's not only just playback, I also cannot connect through HTTPS with my browser because the chain of trust is broken.
Of course I can ignore the warning.

Should this be solved in the git version, as it has just been upgraded to .NET 7?

**Comment by sjorge** [comment]
> EDIT: Tried with the jellyfin:unstable docker image, still has broken certificate chain.

Same, still broken in unstable at least.

**Comment by MarkCiliaVincenti** [comment]
This library would solve the SSL certificate chain issues you're having: https://github.com/MarkCiliaVincenti/TlsCertificateLoader
