### ISSUE TITLE
Media Will Not Play

### ISSUE THREAD

**Issue by Mossy93** [jellyfin/jellyfin#8346]
**Media Info of the file**
Tested most recently on a 1080p MP4 file of Big Buck Bunny. The file plays fine on VLC on my system. Any media will not play in Jellyfin.

**Logs**
[Jellyfin Log](https://zerobin.net/?30e0d231fe2c9cb0#YI+9x4Fkt1PC5w2litnkh2RhzdMsMzPaIIIxMi64MgU=)

**Server System (please complete the following information):**
 - OS: Garuda Linux x86_64
 - Jellyfin Version: 10.9.0
 - Hardware settings & device: No hardware acceleration enabled. Ryzen 5 5600X, 16GB RAM, nVidia RTX 3060
 - Reverse proxy: N/A LAN use only.
 
**Client System (please complete the following information):**
 Tested using Localhost, but the same results on my Android app on my Galaxy S20 5G FE

**Comment by crobibero** [comment]
I highly recommend you use 10.8.4

Unstable (10.9) has an upstream subtitle library bug.

**Comment by Mossy93** [comment]
I just uninstalled the version from the Chaotic AUR repository and installed the version 10.8.4 from the actual AUR. Everything seems to be working. Thanks.

**Comment by realitymolder** [comment]
> I just uninstalled the version from the Chaotic AUR repository and installed the version 10.8.4 from the actual AUR. Everything seems to be working. Thanks.

If that's the case, consider closing the issue :)
