### ISSUE TITLE
10.8.1 version VAAPI playback issue on j4125

### ISSUE THREAD

**Issue by dushiying** [jellyfin/jellyfin#8355]
**Media Info of the file**
1080P H264 DSR ACC5.1

**Logs**
[log.txt](https://github.com/jellyfin/jellyfin/files/9482974/log.txt)

**FFmpeg Logs**
[FFmpeg.txt](https://github.com/jellyfin/jellyfin/files/9482978/FFmpeg.txt)

**Stats for Nerds Screenshots**
<img width="637" alt="image" src="https://user-images.githubusercontent.com/21332871/188279592-37194175-f3a4-4075-ad69-bbe74f446ff7.png">
<img width="919" alt="image" src="https://user-images.githubusercontent.com/21332871/188279652-7acb2646-5618-4fe9-8d89-9e04bc465d77.png">
always loading....

**Server System (please complete the following information):**
 - OS: Docker on Linux DarkSkys918 4.4.59+ #25426 SMP PREEMPT Mon Dec 14 18:48:50 CST 2020 x86_64 GNU/Linux synology_apollolake_918+
 - Jellyfin Version: 10.8.1
 - Hardware settings & device: VAAPI on Intel J4125
 - Reverse proxy: no
 - Other hardware notes: on Synology ds918
 
**Client System (please complete the following information):**
 - Device: Custom HTPC
 - OS: Windows
 - Client: Web/Browser
 - Browser (if Web client):Chrome
 - Client and Browser Version: 104.0.5112.102

**Comment by nyanmisaka** [comment]
https://github.com/intel/media-driver#known-issues-and-limitations

It seems to be caused by the old kernel version 4.4.59. Update your system to the latest release first.

Can you uncheck the "OS native DXVA or VAAPI decoder" and try again?

**Comment by dushiying** [comment]
> 

You are right ! ! ! After upgrading, it plays goooooooooood

**Comment by dushiying** [comment]
> 



> https://github.com/intel/media-driver#known-issues-and-limitations
> 
> It seems to be caused by the old kernel version 4.4.59. Update your system to the latest release first.
> 
> Can you uncheck the "OS native DXVA or VAAPI decoder" and try again?

You are right ! ! ! After upgrading, it plays goooooooooood
