### ISSUE TITLE
hosting settings not saved

### ISSUE THREAD

**Issue by jjgalvez** [jellyfin/jellyfin#836]
**Describe the bug**

Unable to change the hosting settings from the advanced > hosting tab

**To Reproduce**

 1. Go to the advanced tab hosting secitton
 1. make a change such as uncheck "Allow remote connections to this server"
 1. Click save
 1. Click on the Warning popup about needing a cert for https
 1. restart jellyfin service
 1. see error: check settings, they have - they have reverted to the original settings 

**Expected behavior**

The changed settings should stick

**Logs**

no errors recorded that I could find

**Screenshots**

none

**System (please complete the following information):**
 - OS: Arch
 - Browser: Chrome and Firefox
 - Jellyfin Version: 10.1.0]

**Additional context**

**Comment by cvium** [comment]
The dialog text is
```
To enable secure connections, you will need to supply a trusted SSL certificate, such as Lets Encrypt. Please either supply a certificate, or disable secure connections.
```
If you disable secure connections it will let you save.

![image](https://user-images.githubusercontent.com/675118/52501893-b244cc80-2be1-11e9-845c-850a14f82988.png)

**Comment by jjgalvez** [comment]
Boy do I feel stupid thank you for clarifying that




Get Outlook for Android







On Fri, Feb 8, 2019 at 2:40 PM -0500, "Claus Vium" <notifications@github.com> wrote:












The dialog text is
To enable secure connections, you will need to supply a trusted SSL certificate, such as Lets Encrypt. Please either supply a certificate, or disable secure connections.



If you disable secure connections it will let you save.
