### ISSUE TITLE
求助硬解失败

### ISSUE THREAD

**Issue by jianjam** [jellyfin/jellyfin#8367]
**Media Info of the file**

视频
标题: 4K HEVC HDR
编码: HEVC
配置: Main 10
等级: 150
分辨率: 3840x2080
长宽比: 1.85:1
隔行扫描: No
帧率: 23.976025
比特率: 15541 kbps
位深度: 10 bit
动态范围: HDR
动态范围类型: HDR10
色彩空间: bt2020nc
色彩转换: smpte2084
色彩初选: bt2020
像素格式: yuv420p10le
参考帧: 1
**Logs**

[https://zerobin.net/?9413ce8e99177d9d#PTaN41Amq03ckkeVcEH0z21e18mLbFtNdiKVIba/Lt0=](url)
**FFmpeg Logs**
[https://zerobin.net/?f1424c5ee3cbe61e#QD9iGFV1lJHxzttSIV0tPaEvdbvgIX8YOLfO0Ldtu80=](url)

**Server System (please complete the following information):**
 - OS: [Docker on QNAP-Linux]
 - Jellyfin Version: [10.8.4]
 - Hardware settings & device: [Intel QSV on QNAP-264C  cpu:N5105]
 
**Client System (please complete the following information):**
 - Device: [PC]
 - OS: [Windows 10]
 - Client: [Web/Browser]
 - Browser (if Web client): [Chrome]
 - Client and Browser Version: [105.0.5195.102]

**Comment by nyanmisaka** [comment]
> [Parsed_tonemap_vaapi_1 @ 0x5632ed8e83c0] VAAPI driver doesn't support HDR

N5105 doesn't support VPP tonemapping, use OpenCL instead.

**Comment by Imccccc** [comment]
how do i configure OpenCL?

**Comment by nyanmisaka** [comment]
> how do i configure OpenCL?

What is your GPU model and your platform?

**Comment by nyanmisaka** [comment]
> @nyanmisaka How to know my intel cpu support VPP？

Read this matrix.

https://github.com/intel/media-driver#video-processing-features

**Comment by Imccccc** [comment]
> > how do i configure OpenCL?
> 
> What is your GPU model and your platform?

i did fix this problem by disabling vpp mapping
