### ISSUE TITLE
Movie titles not displayed after adding them

### ISSUE THREAD

**Issue by fguarneri** [jellyfin/jellyfin#8368]
Hello, I have installed the latest Jellyfin server on desktop Ubuntu 22.04. All my movies have followed the recommended naming scheme. When I went to add the movies folder (in Movies category) containing the files  (ie. titanic (1997).mp4, point break (1991).avi  etc.....), ONLY one movie showed up. When I did the same BUT added these same movies in category "Mixed movies and Shows" , then they all showed up properly. I did not do any permission modifications either.

Can't understand why the Movies category displays only ONE movie and the category Mixed movies and shows displays them ALL.

Can someone please explain?

Thanks
Frank

**Comment by Bond-009** [comment]
Please fill out the template
