### ISSUE TITLE
Security issue when browsing libraries

### ISSUE THREAD

**Issue by quentinus95** [jellyfin/jellyfin#837]
Hi,

I'm not (yet) using Jellyfin, but there was a security issue in Emby I pointed out almost one year ago.

Does the issue still exist in Jellyfin? It is pretty serious in my opinion.

https://github.com/MediaBrowser/Emby/issues/3270

Thanks!

**Comment by joshuaboniface** [comment]
Ooh that is a heck of a security hole. I don't think we've explicitly fixed it, but will take a look.

**Comment by bobberb** [comment]
oh, who knew my requested feature of "public share links" was here the whole tikme @joshuaboniface 🤣

**Comment by JustAMan** [comment]
> oh, who knew my requested feature of "public share links" was here the whole time @joshuaboniface 🤣

Don't worry, we'll fix it so it won't work @bobberb ;)

**Comment by hawken93** [comment]
I think Luke's thing in that thread and fixing this hole could be done by passing on auth to the target device instead of making a big gaping hole and having a relatively short timeout on that. Does this mean that the chromecast working at all is because of this? Lol

**Comment by JustAMan** [comment]
I am not sure I support Luke idea of allowing admin to cast to target device no matter who is logged there...

Though we can still support that use case if we properly support temporary links to media, like @bobberb asks.

**Comment by hawken93** [comment]
How does the chromecast authenticate

**Comment by cvium** [comment]
It uses the user's auth token

**Comment by hawken93** [comment]
Aha, then I agree with @justaman. Sharing links could be used with some kind of share token :)

**Comment by bobberb** [comment]
tokens a la seafile +/- expiry times?
![ss](https://user-images.githubusercontent.com/1891836/52590961-a854e080-2e10-11e9-95fa-a384b31a7975.png)

**Comment by JustAMan** [comment]
Something along this lines, yes.

**Comment by Tolriq** [comment]
I do not follow actively this, but be aware that this will require proper thinking for many cases.

Typically you can send http header when streaming to UPnP devices and many other cases. Protecting the media require proper thinking and documentation as you'll break things on the road (Including my app :p) 

Plex support passing the token via url get params, don't know if Emby/JellyFin also support that, but it would be mandatory to support both headers and a GET param to be able to support all the players currently usable.

**Comment by dkanada** [comment]
> passing the token via url get params

I think we support this in some capacity already because the log pages are sent with the token in the query strings. Not sure how often it gets used but seems like the ideal solution in most cases, excepting the public share feature listed above.

**Comment by joshuaboniface** [comment]
Well, good news - I can't seem to reproduce this!

I followed the steps you outlined:

1. Set a non-admin user to be unable to view my TV library.
2. Copy the URL of the Library itself, as well as a specific element (show) within it.
3. Logged out of my admin user, and in as the non-admin user.
4. Pasted both URLs in the address bar.

In both cases, nothing happened - no errors, but also no unexpected access to the library.

I *think* based on this that we're good here - when and how it was fixed I'm not sure, but it does seem to be. If you can verify that would be appreciated, otherwise we can close this one out!

**Comment by joshuaboniface** [comment]
Closing based on my testing above - if this still occurs and can be replicated please let us know!
