### ISSUE TITLE
[Issue]: Artists duplicated when adding new music

### ISSUE THREAD

**Issue by pssandhu** [jellyfin/jellyfin#8373]
### Please describe your bug

I added additional music by an artist who was already in my library and now they have two different artist pages.

Since this artist had no proper source of online metadata, I had previously added images and a description manually. If the artist had auto-downloaded metadata I never would have noticed this issue.

The two artist pages have different IDs in their URLs. Only the pre-existing one is shown on the Album Artists and Artists pages in the Music library. When I click on the album artist from that page it shows their info and music correctly.

If I navigate to one of their albums via `Music Library -> Albums - > Album 1` and then click on their name to go to the artist page, I am taken to a different page for that artist. It shows their music correctly but none of the metadata I added in the past.

Only the pre-existing artist page has files under `config/metadata/artists`.

I tried removing all of the artist's music and metadata files, refreshing the library, then adding back just the music. However, it made no difference. This occurred on version 10.7.6 so I updated to 10.8.4 but it is still happening with other artists.

This was my initial folder structure and everything worked perfectly:
```
Music/Artist 1 - Album 1/

Music/Artist 2/Album 2/
Music/Artist 2/Singles/Album 3/Album 3.mp3
```
- Album 1 has two album artists, Artist 1 and Artist 3, but all tracks of its only have Artist 1 as the artist

I added a single by Artist 1 and gave them a folder which now looks like:
```
Music/Artist 1/Album 1/
Music/Artist 1/Singles/Album 4/Album 4.mp3
```
The bug occurred after this change. The same thing happened when changing `Music/Album 5/` to `Music/Album Artist/Album 5/`.

In addition to finding this bug, we should also consider how an affected user could fix a library like this without having to manually re-add metadata for multiple artists and keep the duplicated pages in sync.

### Jellyfin Version

Other

### if other:

10.8.4 and 10.7.6

### Environment

```markdown
- OS: Linux Mint 20.3
- Virtualization: Docker
- Clients: All
- Browser: All
- FFmpeg Version: The one from the docker image. Log says "4.3.2" and Custom: "/usr/lib/jellyfin-ffmpeg/ffmpeg"
- Playback Method: n/a
- Hardware Acceleration: n/a
- Plugins: AudioDB, Fanart, MusicBrainz, OMDb, Studio Images, TMDb
- Reverse Proxy: nginx
- Base URL: none
- Networking: n/a
- Storage: Local, read-only via docker
```

### Jellyfin logs

```shell
Nothing in the log apart from an attempt to delete the new artist id during a library scan which had no effect:
[INF] [74] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "MusicArtist", Name: "Artist 1", Path: "/Music/Artist 1", Id: 33bc1511-316d-3286-99ef-7c4fcba91657
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pssandhu** [comment]
Still an issue

**Comment by the-physicser** [comment]
I also have this issue. There are a number of artists that are duplicated. If I look at the metadata for the artist, one of them has for the path:
/config/data/metadata/artists/ARTISTNAME

The other one's path is the path to the music files.

**Comment by pbogre** [comment]
same issue here, i noticed that the displayed artist with path `/config/data/metadata/artists/...` has no `Delete media` option, while the other displayed artist which is where the media actually comes from does.

**Comment by pssandhu** [comment]
Still an issue

**Comment by BugsWorld** [comment]
> I also have this issue. There are a number of artists that are duplicated. If I look at the metadata for the artist, one of them has for the path: /config/data/metadata/artists/ARTISTNAME
> 
> The other one's path is the path to the music files.

Same issue here. I tried deleting media of one of the artists and noticed the artist folder under the metadata folder wasn't deleted. So I tried deleting that folder as well manually but that just broke things once I added the music back. It now just shows a black image as the artist primary image. Seems like there's no way to reset things for that artist now.

**Comment by Berzeck** [comment]
I have the same issue. Do developers need more information? if so, what information is needed? 
I can even enable access to an instance so they can check this bug. It is very annoying

**Comment by nothing2obvi** [comment]
Still happening for me on 10.8.13, just for a few artists. One is in `/config/data/metadata/artists` and the other one is where the actual music files are located.

**Comment by JustMarkov** [comment]
Still happens, one in `/config/data/metadata/artists` and one where the music folder is.

**Comment by kaasneus** [comment]
Yep, still the same issue. Have a duplicate that points to "/config/data/metadata/artists/ArtistName", where the normal one just points to where the media is located. I've tried everything barring rebuilding the docker container.

**Comment by WTFBlaze** [comment]
This is STILL an issue. Even if you disable all metadata and image fetchers for the music library it will STILL do this.

**Comment by BPowell76** [comment]
I can confirm this is also still an issue. For example, I have albums for the artist `At The Gates`, but Jellyfin as a separate metadata listing that is duplicating the albums for the artist in the library.
