### ISSUE TITLE
[Issue]: Duplicates in "Continue Watching" section

### ISSUE THREAD

**Issue by Zuko** [jellyfin/jellyfin#8385]
### Please describe your bug

When movie is in two different library's _(different version/resolution)_ "Continue Watching" section shows all versions when I start watching one of them.

### Jellyfin Version

Other

### if other:

1.8.4

### Please attach any screenshots here

![image](https://user-images.githubusercontent.com/521035/189529203-65a516af-bdab-4fb3-a4a2-146178abe486.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adenbley** [comment]
I will add to this that I run into this problem. This happens in multiple clients (tested web and roku).

To duplicate:

-have existing library with TV comment
-create a new library and corresponding folder with TV content
-hard link a show from existing folder to new folder
-watch an episode
-observe that "continue watching" shows the episode 2x

**Comment by Ghilteras** [comment]
Same problem here, any traction on this bug?

**Comment by Metrabyte** [comment]
I am also having this issue. Are there any updates to this?

**Comment by felix920506** [comment]
If it still happens after 10.11 comes out please open a new issue.

**Comment by sysr-q** [comment]
Just wanted to chime in here for future searchers, that after all sorts of finagling with Library settings in 10.10.7, the only thing I was able to do to solve this was surgery on the sqlite3 database.

Keep in mind, this has a million ways of going wrong, so take copious backups, backups of your backups, etc unless you want rebuild everything from scratch.

1. Find your Jellyfin `library.db`, mine was at `/var/lib/jellyfin/data/library.db`. **Stop Jellyfin**.
2. Look for references to your old folder. Mine was ghost references showing up as duplicate "Continue Watching" entries, referencing files in `/hoard/Movies` after I changed where I mount my NFS drive.
3. `$ sqlite3 library.db "SELECT type, Path FROM TypedBaseItems WHERE Path LIKE '%hoard/Movies%';" | less -S`
4. Double check the things you see, and triple check your backups. There should be mostly lots of entries like:
```
MediaBrowser.Controller.Entities.Video|/hoard/Movies/Alita.Battle.Angel.2019/Alita.Battle.Angel.2019 - 2160P.mkv
MediaBrowser.Controller.Entities.Movies.Movie|/hoard/Movies/The.Matrix.Trilogy.1999-2003/The Matrix Reloaded (2003) + Extras/The Matrix Reloaded (2003).mp4
```
5. `$ sqlite3 library.db "DELETE FROM TypedBaseItems WHERE Path LIKE '%hoard/Movies%';"`

Boom, all gone. You can safely start Jellyfin, check the logs for errors, check for duplicate entries, and roll back the DB if necessary. In my case I just did another Full Library Scan and it was finally resolved.
