### ISSUE TITLE
[Issue]: Special Features not sorting correctly (alphanumerically)

### ISSUE THREAD

**Issue by somewherebutnothere** [jellyfin/jellyfin#8387]
### Please describe your bug

Special Features are not sorting correctly, as in alphanumerically.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Ubuntu Server 22.04
- Virtualization: Docker
- Clients: Web
- Browser: Chrome
```

### Please attach any screenshots here

![image](https://user-images.githubusercontent.com/6793358/189545149-51fcad83-0f49-4455-9e78-e34fbd4e99a6.png)

![image](https://user-images.githubusercontent.com/6793358/189545685-5a14a546-5b3b-481d-ba62-96da29ba4027.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RatVader** [comment]
I've experienced this same issue with unexpected sorting of a TV Show's "extras" directory in Ubuntu 18.04.6 LTS (GNU/Linux 4.15.0-204-generic x86_64) running Jellyfin.Server 10.8.9.0 on March 26, 2023.  I had files sorted like so, with Jellyfin seemingly ignoring the numbers at the beginning:
- 02. Ending 1.mkv
- 04. Ending 2.mkv
- 01. Opening 1.mkv
- 03. Opening 2.mkv

I was able to sort them by preceding the number with an 'E' but the same method failed when preceded by an 'O', 'S', or 'S00E':
- E01 Opening 1.mkv
- E02 Ending 1.mkv
- E03 Opening 2.mkv
- E04 Ending 2.mkv
