### ISSUE TITLE
[Issue]: [10.8.X] Libraries Deleted at random

### ISSUE THREAD

**Issue by buzzzz2138** [jellyfin/jellyfin#8388]
### Please describe your bug

Yesterday nothing wrong with the system.  Logs attached. 
Today, images stopped appearing and were blurred.  Restarted Jellyfin and 3 of 4 libraries were deleted.  Media was not disconnected.  Of the 4 libraries, 2 are on one physical and 2 are on a different physical drive.  The one remained, the sibling library on the same physical drive was deleted.   This is an Open Media Vault setup and the drive do not disconnect.  The SMART status doesn't change. 

This is related but not a duplicate of #1714.  **This is not a feature request.** 

Logs from a good day.
[temp_log_20220910.log](https://github.com/jellyfin/jellyfin/files/9544145/temp_log_20220910.log)
Logs from the bad day. 
[temp_log_20220911.log](https://github.com/jellyfin/jellyfin/files/9544146/temp_log_20220911.log)

### Jellyfin Version

10.8.4

### Environment

```markdown
- OS: Debian 11
- Virtualization: No
- Clients: FireFox/Android/Roku
- Browser: Firefox
- FFmpeg Version: 
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy: Yes but not being used.
- Base URL:
- Networking:
- Storage: Physical attached hard drives.
```

### Jellyfin logs

```shell
See description and attached logs.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Slug-Cat** [comment]
do you mean the jellyfin data for those libraries was deleted or that Jellyfin actually deleted the content files of the libraries?

**Comment by buzzzz2138** [comment]
Jellyfin data for those libraries were deleted.  The jellyfin data is on the same drive as the OS. 

I have jellyfin in a docker with read only to the media files.

**Comment by whiteowl3** [comment]
can we see the permissions of the media folders and an ```id <username>``` for the user jellyfin runs as?

**Comment by buzzzz2138** [comment]
![image](https://user-images.githubusercontent.com/3680372/191650721-bc69ff8e-4294-433c-9273-36e9dba31afc.png)

D1 is one drive.
D2 is a second drive.
D3 is a third drive. 
Each line represents a library. 

In the disconnects previously for example, /New and /Movies Libraries were deleted, but not /Kids. 

User:
![image](https://user-images.githubusercontent.com/3680372/191651067-37883f0a-978f-43e3-8b27-a32c17cc5fef.png)

**Comment by whiteowl3** [comment]
you should check the actual source of truth, not whatever gui this is.  like ```ls -l``` in the library itself.  last I checked, jellyfin will remove information for folders that it can no longer read. YOU are root in your container, but surely jellyfin is not running as root?  the jellyfin user requires read access to the directories, or it will delete database data.

**Comment by buzzzz2138** [comment]
Jellyfin is ran as root.  Should it be.... probably not. 
That is a portainer container in Open Media Vault.  Even tho it's root, and because it's ran inside the docker container, Jellyfin has read only access to the media files and read/write access to the config and cache folder that are in the /etc/Jellyfin location.  Nothing else.

**Comment by buzzzz2138** [comment]
This occurs on JellyFin 10.8.8

I notice the last time it occured it removed collections, all libraries except for an empty one, and all Live TV connections.  Almost like the server was starting brand new except it still had all of the users and when the libraries were added back the the watch status was correct. 

I don't know if it's related but the Playback Reporting plugin disappears after a intermittent number of days.  Sometimes it's 8 days, sometimes it's 3 days.  I add it back, restart the Jellyfin and all the data is still there.

**Comment by buzzzz2138** [comment]
Happened again.  Latest log. 
[deleted_libraries_20230218.log](https://github.com/jellyfin/jellyfin/files/10774435/deleted_libraries_20230218.log)

Watch something that finished at midnight.  Everything was fine.  At 7 am, all of the libraries were gone.

**Comment by zuiopertz** [comment]
Same issue. Happened two times so far for me. 
First time 5 of 6 libraries were gone. All covers were suddenly blurred. 
Second time: today...
Docker on Synology / vers. 10.8.9

Also can confirm that it seems like a full restart of jellyfin but my users were still there. My applied theme/skin was also resettet to default.

**Comment by buzzzz2138** [comment]
Happened again.  Logs attached.  Happened sometime between 17:00 and 21:45 hours. 
[mod_temp_log_20230412.log](https://github.com/jellyfin/jellyfin/files/11218063/mod_temp_log_20230412.log)
No users were deleted.  Live TV wasn't deleted.  All Libraries were deleted along with Plugins. It was like someone came in and deleted them.  But I was the only one to log into via activities.  Was watching something that finished at 21:45 then there were some things that were blurred out.  Went to libraries and most of them were gone, the remaining ones had zero media.

**Comment by buzzzz2138** [comment]
Another month another wipe.  Occured around 18:00 hours and 19:40 hours.
All libraries disappeared along with Plugins.  Line 730 of the attached logs has a System.Xml.XmlException: Reference to undeclared entity 'ns_extend'. Line 13, position16.  Might be something. 
[mod_Jellyfin_05_13_23.txt](https://github.com/jellyfin/jellyfin/files/11471060/mod_Jellyfin_05_13_23.txt)

**Comment by buzzzz2138** [comment]
Didn't mean to close this.

**Comment by buzzzz2138** [comment]
Great Timing.  This happen again today.

**Comment by thornbill** [comment]
Yes the contents of the cache directory are regularly deleted to avoid old transcode files consuming a bunch of space. Having the config and cache directories point to the same place is a profoundly terrible idea.

**Comment by buzzzz2138** [comment]
> Yes the contents of the cache directory are regularly deleted to avoid old transcode files consuming a bunch of space. Having the config and cache directories point to the same place is a profoundly terrible idea.

"avoid old transcode files"
Are those not in the /config/transcodes directory?
Only the /config and /cache are defined in the docker compose.

**Comment by Bond-009** [comment]
Default transcode path is cache path + "transcodes"
