### ISSUE TITLE
oncloud玩客云并不支持是否有更新armv7的计划

### ISSUE THREAD

**Issue by ludyleocn** [jellyfin/jellyfin#8389]
你好，我想使用玩客云搭载jellyfin 平台是armv7
请问作者是否有这方面的开发计划？

**Comment by Bond-009** [comment]
> Hello, I want to use the player cloud to carry the jellyfin platform is armv7
Does the author have any plans for this development?

Are you talking about a client?

**Comment by n0thing2speak** [comment]
> 

i think he/she want an ARM32 server

**Comment by Bond-009** [comment]
We already support ARM32
