### ISSUE TITLE
Support for VDPAU Nvidia hardware gpu acceleartion

### ISSUE THREAD

**Issue by nickcorona** [jellyfin/jellyfin#839]
**Describe the feature you'd like**
Support for VDPAU Nvidia hardware gpu acceleartion

**Additional context**

**Comment by nvllsvm** [comment]
The ffmpeg distribution we're using doesn't support it. 

https://github.com/jrottenberg/ffmpeg/issues/147

Perhaps we could upstream patches to it.

**Comment by nvllsvm** [comment]
EDIT - disregard previous comment - VDPAU and nvenc/nvdec are two different things.

**Comment by DarkJoney** [comment]
I also vote for this feature, because we must cover a lot of different hardware.
I have mistaken with a GT1030, because nVidia didn't had a clear NVENC description while I was buying it.
I would like to see any alternative methods of transcoding, which would run at any CUDA supported GPU.

**Comment by joshuaboniface** [comment]
Added to the `jellyfin-ffmpeg` Debian/Ubuntu packages; will be available with the `-4` package.
