### ISSUE TITLE
[Issue]: Various issues with deleting episodes

### ISSUE THREAD

**Issue by Sophist-UK** [jellyfin/jellyfin#8392]
### Please describe your bug

1. When deleting the last episode in a directory, if the directory is now empty it does not also delete the directory.
2. Directories with zero media files in still show up as a title.
3. Continue watching does not ignore empty directories so if e.g. you have an empty directory for Series 2, you do not get a Series 3 episode shown as Next Up or Continue watching.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS:Windows
- Virtualization: No
- Clients: Firestick, Android
- Browser: Chrome
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins: 
- Reverse Proxy: None
- Base URL:
- Networking: Wifi G
- Storage: Windows native NTFS
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Sophist-UK** [comment]
I am not quite sure what I am supposed to do to avoid this issue becoming stale. I reported a problem so that someone could address it - if there is no one addressing it and it goes stale that seems to be a major issue with this project.

**Comment by Sophist-UK** [comment]
I am not quite sure what I am supposed to do to avoid this issue becoming stale. I reported a problem so that someone could address it - if there is no one addressing it and it goes stale that seems to be a major issue with this project.

**Comment by Sophist-UK** [comment]
I am not quite sure what I am supposed to do to avoid this issue becoming stale. I reported a problem so that someone could address it - if there is no one addressing it and it goes stale that seems to be a major issue with this project.

**Comment by Shadowghost** [comment]
We're currently cleaning up issues and properly setting labels to prevent this happening in the future.

Sidenote on the issue though: Deleting things from within Jellyfin is not a major functionality in itself (we even considered removing it alltogether at some point) and none of us devs actually use it, so the interest in fixing this is currently quite low because there are other issues having more impact on the main capabilities of Jellyfin, e.g. playback.

**Comment by Sophist-UK** [comment]
Whilst I am / have been a contributor to several other open-source projects, I am not a C# programmer so cannot help with this one.

**Comment by phito** [comment]
this bug is fixed

**Comment by felix920506** [comment]
reported as fixed by user, closing
