### ISSUE TITLE
[Issue]: Unable to browse Movies in grouped Movies view unless access is enabled to all libraries

### ISSUE THREAD

**Issue by justinbyoung** [jellyfin/jellyfin#8398]
### Please describe your bug

I have multiple Movie libraries.

Movies HD, Movies 4K and Movies SD.

A user has access to the Movies HD and Movies 4K libraries and can access them okay. However when these libraries are grouped into a single Movies view the user can no longer browse the Movies in the Movies library. The list appears as empty with a spinning progress wheel. However Suggestions and Collections still work and it is possible to view and play movies from there. This is both in the browser and the Android TV app.

Checking the jellyfin log when attempting to browse the movies I see the following error:

[2022-09-13 12:51:08.530 +12:00] [WRN] "Justin" is not permitted to access Library "Movies".

If I select "enable access to all libraries" for this user then the problem goes away. It has to be that particular option, if I manually select all of the libraries the problem still happens.

### Jellyfin Version

Other

### if other:

10.8.4

### Environment

```markdown
- OS: Debian
- Virtualization: Proxmox
- Clients: Android TV, Browser
- Browser: Chrome
- FFmpeg Version:
- Playback Method: Any
- Hardware Acceleration: Quicksync
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
[2022-09-13 12:51:08.530 +12:00] [WRN] "Justin" is not permitted to access Library "Movies".
```

### Please attach any screenshots here

![image](https://user-images.githubusercontent.com/27791449/189786385-d985e357-1796-4062-8ca2-3e12e74c8a89.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tdeacon** [comment]
I can second this. I don't currently have time to look at the code, but this is a repeatable bug.

If two different folders are added (and given permission to a user), then under Home settings on the user the two folders are set to automatically group they are no longer accessible from said user - even though separately the user can access them just fine.

**Comment by justinbyoung** [comment]
I haven't had a chance to test this lately. It was a breaking bug for my family so we are still mostly using Plex, but if this bug still exists it seems to be quite a major one so should still be looked into.

**Comment by tdeacon** [comment]
My apologies. This bug was fixed. Even though whoever did, didn't respond to this thread. I believe things worked properly by January of 2023.
