### ISSUE TITLE
Non-admin users download subtitles

### ISSUE THREAD

**Issue by thejacer87** [jellyfin/jellyfin#84]
i think you'd get like 30% of emby users if you could make it so our wives could download subtitles w/o their accounts having to be admin accounts.

**Comment by JustAMan** [comment]
Care to explain more? :) I have non-admin account that can view movies with subtitles on and off... so what does "download subtitles" mean?

**Comment by thejacer87** [comment]
in the web interface, only user's with the "Allow this user to manage the server" have the ability to "edit subtitles" (ie search/download them)

clicking the dot menu in a movie's view page:

![image](https://user-images.githubusercontent.com/6412919/49881008-2cbfbe80-fde2-11e8-8787-aa9b5ba60ed1.png)

as admin:

![image](https://user-images.githubusercontent.com/6412919/49881055-452fd900-fde2-11e8-9cb5-786f05020e2d.png)

**Comment by JustAMan** [comment]
I see. What is the reason you want to download subtitles then? I see a case when you want to download all the content (media file + subs), is it what you want? Or just subtitles?

**Comment by jbstep** [comment]
In my case, my wife may be watching something on her account that does not have subtitles. She has no way of searching and adding them herself.

**Comment by thejacer87** [comment]
ya sorry, i think you are misunderstanding "download subtitles" i dont want them on my local client. i want to be able to "edit subtitles" which downloads them from open subtitles so the show/movie can be viewed with subtitiles

exactly how @jbstep described. 

sometimes shows don't have subtitles downloaded for w/e reason. and my wife requires me to go and get them, bcuz her account can't. which is ridiculous

**Comment by JustAMan** [comment]
So this needs special permissions defined, like "edit subtitles", which admin should be able to grant other users on per-user or per-group basis then.

**Comment by thejacer87** [comment]
looks like itll be in emby 3.6 https://github.com/MediaBrowser/Emby/issues/3071
