### ISSUE TITLE
[Issue]: Audiobooks are showing only the first Episode

### ISSUE THREAD

**Issue by realitymolder** [jellyfin/jellyfin#8404]
### Audiobooks are showing only the first Episode

Steps to reproduce:

1. Put the audiobook files in a route:  path/to/audiobooks/[authorName]/[bookName]
2. Add a media library with the content type of books and add the route.
3. Scan the new library for files.
4. Go to my media section -> books -> [Author Name] folder.
5. You will now see only one file to stream, but the folder has many. 

### Jellyfin Version

Other

### if other:

10.8.4

### Environment

```markdown
- OS: Ubuntu Server 22.04
- Virtualization: Docker
- Clients: Google Chromecast With Google TV
- FFmpeg Version: 4.4.2-0ubuntu0.22.04.1
- Playback Method: Not Sure
- Hardware Acceleration: NVENC
- Installed Plugins: Bookshelf (tried without it as well)
```

### Please attach any screenshots here

![image](https://user-images.githubusercontent.com/26459151/190121768-ce50c6d7-1371-43c3-bd31-420856e32c40.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ArchiusPendragon** [comment]
Experiencing this issue on latest build. 

Chapterized audiobooks - with separate MP4 files for each given chapter of a story - only show the first file for download or reading; with no way to itemize each individual file.

This would require stitching the chapterized files into a single, larger, monolithic file; or converting the library to Music instead; which both pose their own issues.

**Comment by DocBlizz** [comment]
Same exact issue but on Windows 10

**Comment by RikuAzhurlar** [comment]
Issue experienced on release 10.8.9 with official Bookshelf plugin. 

Environment, OS: Debian 11
Virtualization: None
Clients: Google Chrome and Jellyfin Media player
Installed Plugins: Bookshelf

Issue appears to be Jellyfin or the plugin itself expecting monolithic files. This was not present on older builds as several references exist online mentioning the proper handling of chapterized audiobooks, and is in part why I attempted to use this solution.

**Comment by 1337joe** [comment]
Anyone having this problem: can you give me a directory listing of the contents of a directory that's exhibiting this behavior?

As far as I can tell this depends on the names of the media in the problem folder, so without those names being included in the bug report I can't tell if my fix works for your cases.

**Comment by Synraw** [comment]
Most of my library is tagged, I noticed you could possibly make use of track number tag as it seems that its commonly used for chapters
