### ISSUE TITLE
enable UPNP? 

### ISSUE THREAD

**Issue by servimo** [jellyfin/jellyfin#8405]
What to do if I want do enable UPNP?   I want to browse my media library.

**Comment by Bond-009** [comment]
Do you mean DLNA?
Dashboard > DLNA > Enable DLNA Server

**Comment by servimo** [comment]
I try to browse/play my media in VLC but don't show any file. In the old
Jellyfin I could.

Em qua., 14 de set. de 2022 18:14, Bond-009 ***@***.***>
escreveu:

**Comment by Bond-009** [comment]
Same issue as https://github.com/jellyfin/jellyfin/issues/7668 probably

**Comment by servimo** [comment]
I think is not the same issue, in my old TV DONA works, I can see movies, in my mi box using VLC I can't.

**Comment by servimo** [comment]
Now, after updating to 10.8.5 is working.
