### ISSUE TITLE
[Issue]: NFO watched status not imported for movies or episodes

### ISSUE THREAD

**Issue by matthewpritchett** [jellyfin/jellyfin#8415]
### Please describe your bug

Same issue as the previously resolved #1640 

I am working on migrating my server from an Ubuntu install to a Truenas Scale (using Truecharts) installation and since I already have all metadata and watched status saved in NFO files I tested the import process and it seems like it isn’t reading the watched tags in the NFO file. I disabled all other metadata providers and had disabled saving NFO before importing as well as setting the user for watched status. I import and the majority of data from the NFO is imported correctly but watched is always shown as false on the webui. Curious if there’s anything specific I need to set for it to work or if it might be a bug introduced since the previous issue was fixed. Thanks!

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Truenas Scale
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matthewpritchett** [comment]
Meant to put #1640

**Comment by daullmer** [comment]
Could you maybe provide us one of your nfo files and your nfo config  file? You should find the latter at in you configuration folder at `config/xbmcmetadata.xml`. Theoretically the watched status import should be working correctly.

**Comment by matthewpritchett** [comment]
Yes! I will work on getting both of those this week and post in here. Thanks!

**Comment by ProfessionalismIsMyMiddleName** [comment]
@matthewpritchett, Did you find the solution to your issue?
If not, since I have the same exact problem, here are my xbmcmetadata.xml and an example nfo whose watched tag is not imported (in a zip because github). 
[nfo sample and config file.zip](https://github.com/jellyfin/jellyfin/files/10327327/nfo.sample.and.config.file.zip)

**Comment by matthewpritchett** [comment]
No solution besides using a third party tool to sync watch statuses. I just forgot to post my debug info here. Hopefully sometime soon I’ll get time to.

**Comment by bez820** [comment]
I have this same issue too. The watched status (and played dates) from my nfo files (created by Emby) are not coming across to Jellyfin 10.8.8

[config and nfo sample.zip](https://github.com/jellyfin/jellyfin/files/10370444/config.and.nfo.sample.zip)

**Comment by ProfessionalismIsMyMiddleName** [comment]
Well, as you can see, I ended up looking into it myself, and I think I found the source of the issue.
From what I've seen, the importing of the watched, playcount and lastplayed tags was 100% broken, or in any case I can't see how it would have worked, so I'm surprised we were so few having the issue.
In any case, I made a pull request if anyone want to test it.
