### ISSUE TITLE
[Issue]: Very poor menu Performance on clients and other errors

### ISSUE THREAD

**Issue by Hallo951** [jellyfin/jellyfin#8436]
### Please describe your bug

Hello, 

I have the latest jellyfin (10.8.4) running in Docker on my NAS (Synology D920+, 1TB SSD read/write cache, 4 GB RAM (still upgrading to 20 GB)). The largest library is about 1000 movies. My TV (LG OLED 65 BX with webos 5) is connected via WIFI over 5G. I installed the jellyfin client on the TV via the dev mod. To 90% everything works. What does not work properly is the following:

1. The performance of the menu from the client on the LG TV is very slow and sluggish especially within the very large library. For libraries with less movies it is a little better but also not very good. On another client, for example the cell phone, almost everything runs much better. What can I do to make it run smoother on the TV? 

2. When I want to play a 4K movie with a 7.1 audio track on the TV, it is transcoded via hardware transcoding (QSV). This also seems to work normally, but the movie stalls every 10 - 20s, as if it is buffering something in between. Is this due to the still too small RAM or what? This observed faltering occurs on all clients. 

3. Filtering by video type (e.g. 4k movies) does not work for me. This behavior also occurs on all clients. 

4. I have all the metadata for the movies stored locally. I have created these with TinyMediaManager. For movie collections, TinyMediaManager creates a separate folder for me with the covers of the respective movie collection. I have in Jellyfin but not yet found a way to read them. Currently, the cover of the first movie is taken for movie collections or you edit the movie collections manually. Both is not a nice solution. It would be better to do it like Kodi with a separate cover order... 

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Synology DSM 7.1.1 (Linux) 
- Virtualization: Docker
- Clients:LG TV (webOS 5), Android
- Browser:
- FFmpeg Version: 4.4.2-46
- Playback Method: direct, transcode
- Hardware Acceleration: QSV
- Plugins: none
- Reverse Proxy: - 
- Base URL: - 
- Networking: - 
- Storage: NAS (Synology D920+)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Hallo951** [comment]
Small update:

I have just installed the new RAM (+16 GB) and carried out the first tests. It looks like my stuttering problem with transcoded films has been solved. The other problems still remain...

**Comment by whiteowl3** [comment]
Transcoding 4k on a NAS is an unrealistic expectation, it will essentially never work no matter how much ram you put in.
As far as your data structure, you will want to write a script to move them over to Jellyfin's recommended metadata architecture, there is no simple way to make Jellyfin change the way it loads metadata.  As long as Jellyfin correctly identifies what the name and year of the movie is, you don't need Tiny; Jellyfin is pretty good at finding metadata.

**Comment by Hallo951** [comment]
Hello,

I decided to use TinyMediaManger because I am a fan of offline metadata and this ensures that the next time I read in the same metadata as I once created. With an online connection this is not guaranteed.  The transcoding of a 4k movie is actually running quite well now. I haven't had any stuttering or dropouts on the TV yet. Also the CPU load was just about 20%. However, I noticed that a 4k HDR x265 10Bit movie lost a lot of color after transcoding and was also very "outshined" (bright). Is this a bug or is there something that can be adjusted?

**Comment by retroNUC** [comment]
> What can I do to make it run smoother on the TV?

I've found that blur and animated scaling effects both seem to kill performance on the WebOS client, but I'm using an [alternate theme](https://github.com/CTalvio/Ultrachromic). I'm not sure if this'll work for the default theme, but inserting this into the 'Custom CSS Code' section to force hardware accelerated rendering and webkit implementation of filter effects helped me out:

`/* backdrop intensity tweaks */
.backdropImage {-webkit-transform: translate3d(0, 0, 0);
-webkit-filter: blur(40px) saturate(120%) contrast(120%) brightness(40%);}`
