### ISSUE TITLE
Jellyfin Error

### ISSUE THREAD

**Issue by chiragnahata** [jellyfin/jellyfin#8444]
Jellyfin Not playing

My content in Jellyfin is not playing. Please help

Website : http://129.213.86.197:8096
Login Id : Help
Password : jellyfinhelp

Please login and check the issue and help me out as soon as possible.

**Comment by neilsb** [comment]
We are not able to troubleshoot issues with your system.  If you have problems with your you can try our [troubleshooting room](https://jellyfin.org/contact/), or if you find a problem with the software then please feel free to raise an issue with full details about the error you encountered and your system details.
