### ISSUE TITLE
[Issue]: Jellyfin libraries don't resist reboot / library rebuild is finnicky

### ISSUE THREAD

**Issue by maurocolella** [jellyfin/jellyfin#8448]
### Please describe your bug

Hi. First of all, Jellyfin is stunning. Wish I could contribute more.

Second: I have had this problem twice so far, within just a few days.

I run the official Jellyfin container on Docker (Portainer) via docker compose, on top of Manjaro.

I use watchtower to update containers automatically, a bind mount to keep configurations, and BTRFS.

The first time, watchtower updated and restarted, I think Portainer itself, causing all my stacks to restart, and my library was shot. There still is a catalog of metadata and it seems correct, but I am unable to browse the library, for all purposes it shows empty.

I tried rescanning all libraries, this was a bit finnicky. Moving away from that web page, then coming back to it, or trying to restart the scan a few times didn't quite appear to produce the desired result.

This same situation has happened again this morning after a power outage.

Finally, I tried running the full library scan again patiently, keeping a browser tab open for it to run, and would you know? It worked.

Is it possible to implement some kind of auto-healing and/or integrity checks on the db?

Also, is the library rebuild task dependent upon UI? Is it something that could run decoupled, through some queue?

It's not too much of a snag, but there's a grey area.

Thanks.

### Jellyfin Version

Other

### if other:

10.8.4

### Environment

```markdown
- OS: Manjaro Linux 22.0.0 
- Virtualization: Docker
- Clients: Android, Android/Google TV, Linux (desktop), browser
- Browser: Chrome Version 105.0.5195.125 (Official Build) (64-bit)
- FFmpeg Version: ffmpeg version 5.1-Jellyfin
- Playback Method: ?
- Hardware Acceleration: N/A
- Plugins: None
- Reverse Proxy: Custom, Nging
- Base URL: via IP
- Networking:
- Storage:
```

### Jellyfin logs

```shell
No new logs since outage. Logs end yesterday, no log output from rescan.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by szszoke** [comment]
I seem to be having a similar problem, my libraries disappeared from Jellyfin after a server reboot. @maurocolella did you manage to find a solution to this problem?

**Comment by mdcayton** [comment]
Having the same issue.  Every time the container is restarted Jellyfin thinks its starting from a fresh install.

**Comment by maurocolella** [comment]
Actually (and apologies for the belated reply), this wasn't a software issue in my case, but primarily due to docker starting before my file systems were mounted - hence bind mounts just weren't available. 

When running in Docker, I reckon there is little if anything Jellyfin can do about that; although there might have been other issues at play.

This much was on me, and a problem with the underlying filesystem.
