### ISSUE TITLE
[Issue]: Low fps in hardware transcoding (QSV) with tone mapping and subtitles

### ISSUE THREAD

**Issue by Hallo951** [jellyfin/jellyfin#8456]
### Please describe your bug

I have a problem transcoding my 4k HDR movies with my synology D920+ NAS. I use jellyfine/jellyfine in the latest version in synolgy docker. The fps achieved is around 20 fps. This leads to dropouts while watching by one stream. Is there a way to optimize this on the software side? A friend of mine has the same NAS in use, but uses Plex and there the transcoding works with the same settings without dropouts or anything else. 

If there is no possibility on the software side, what would I have to change on the hardware side so that everything works?

### Jellyfin Version

10.8.5

### Environment

```markdown
- OS: Synolgy
- Virtualization: Docker
- Clients: LG TV (webos 5)
- Browser:
- FFmpeg Version: current
- Playback Method: jellyfin clint for webos
- Hardware Acceleration: QSV with tone mapping and subtitles
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking: 5 Ghz Wifi (100% signal)
- Storage:
```

### Jellyfin logs

[log_20220926.log](https://github.com/jellyfin/jellyfin/files/9643437/log_20220926.log)

### FFmpeg logs

[FFmpeg.Transcode-2022-09-26_06-03-41_c81b6ea7f85694933715075c3c3ceb53_82945099.log](https://github.com/jellyfin/jellyfin/files/9643441/FFmpeg.Transcode-2022-09-26_06-03-41_c81b6ea7f85694933715075c3c3ceb53_82945099.log)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nyanmisaka** [comment]
Can you share the ffmpeg log?

**Comment by Hallo951** [comment]
Sure. 

I hope these are the right logs....once jellyfin in general and then the transcode itself.

[log_20220926.log](https://github.com/jellyfin/jellyfin/files/9643428/log_20220926.log)
[FFmpeg.Transcode-2022-09-26_06-03-41_c81b6ea7f85694933715075c3c3ceb53_82945099.log](https://github.com/jellyfin/jellyfin/files/9643429/FFmpeg.Transcode-2022-09-26_06-03-41_c81b6ea7f85694933715075c3c3ceb53_82945099.log)

**Comment by nyanmisaka** [comment]
Try disabling VPP tonemapping and use the OpenCL instead.

**Comment by Hallo951** [comment]
Thanks for your quick reply.

I tested it but if I disable VPP tonemapping and only have the other one enabled, I have an even worse result (13 fps). Here is the new log:

[FFmpeg.Transcode-2022-09-26_07-40-10_c81b6ea7f85694933715075c3c3ceb53_eedeadeb.log](https://github.com/jellyfin/jellyfin/files/9644055/FFmpeg.Transcode-2022-09-26_07-40-10_c81b6ea7f85694933715075c3c3ceb53_eedeadeb.log)

**Comment by nyanmisaka** [comment]
Plex can't do hardware-based subtitle burning, but Jellyfin does support. So I suspect the Plex client is requesting a lower resolution like 2k or 1080p to achieve >24fps transcoding, but Jellyfin uses 4k (3840x2160), which is way more compute and memory bandwidth intensive. Do you have dual channel memory installed?

**Comment by Hallo951** [comment]
That's possible. I'll have to ask my friend.

What do you mean by channel memory installed? Is that software? Hardware-wise, jellyfin runs inside the synology docker on a synology D920+ with 20 GB RAM and 2 x 1TB SSD as read/write cache. The HDDs are enterprise hard drives from seagate.

What else can I do to make the 4k films run smoothly? Without tonemapping, I get a transcoding rate of about 38 fps. But with that, the film just doesn't look good any more.
