### ISSUE TITLE
Auto Box Sets plugin

### ISSUE THREAD

**Issue by bwaddington** [jellyfin/jellyfin#846]
**Describe the feature you'd like**

**Additional context**

**Comment by cvium** [comment]
https://github.com/cvium/jellyfin-plugin-tmdbboxsets/releases

**Comment by bwaddington** [comment]
dosnt seem to work

**Comment by cvium** [comment]
What's wrong?

**Comment by bwaddington** [comment]
i have tried both pre-compiled binaries. i'm using jellyfin version 10.1.0 
Jellyfin.Plugin.TMDbBoxSets.10.1.0.dll - scans in about 5 sec and add no boxsets
Jellyfin.Plugin.TMDbBoxSets.dll - just comes up with an alert Unexpected error occurred!

**Comment by bwaddington** [comment]
could you please update jellyfin-plugin-tmdbboxsets to make it compatible with jellyfin version 10.2.1 and would it be possible to add this to the jellyfin plugin page thank you
