### ISSUE TITLE
[Issue]: Jellyfin ffmpeg (linuxserver.io image) is not using hardware video enhacement on intel GPU QSV/VAAPI

### ISSUE THREAD

**Issue by marys1234** [jellyfin/jellyfin#8461]
### Please describe your bug

For the live streaming transcoding (enigma2 plugin), in comparison to Jellyfin 10.7.7 on Fedora and Fedora native ffmpeg, hardware transcoding (vaapi or qsv) on the same intel GPU is not using hardware video enhancement features, therefore CPU utilization is much higher.
Jellyfin 10.7.7 and Fedora ffmpeg log: FFmpeg.Transcode_10_7_7.txt
[FFmpeg.Transcode_10_7_7.txt](https://github.com/jellyfin/jellyfin/files/9646666/FFmpeg.Transcode_10_7_7.txt)
Jellyfin 10.7.7 and Fedora ffmpeg intel_gpu_top screenshot: Intel_gpu_top_10.7.7.jpg
![Intel_gpu_top_10 7 7](https://user-images.githubusercontent.com/59769205/192289966-000fc698-9bab-4308-a189-5387c56b2ebc.jpg)

Jellyfin 10.8.5 with latest Jellyfin ffmpeg on linuxserver.io docker container, ffmpeg log:  FFmpeg.Transcode_10.8.4_LS_Docker.txt
[FFmpeg.Transcode_10.8.4_LS_Docker.txt](https://github.com/jellyfin/jellyfin/files/9646676/FFmpeg.Transcode_10.8.4_LS_Docker.txt)
Jellyfin 10.8.5 with latest Jellyfin ffmpeg on linuxserver.io docker container, intel_gpu_top screenshot: Intel_gpu_top_10.8.4_LS_Docker.jpg
![Intel_gpu_top_10 8 4_LS_Docker](https://user-images.githubusercontent.com/59769205/192291024-0f4a7efa-3040-4830-b54a-c1df619dd58d.jpg)

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nyanmisaka** [comment]
Have you enabled H264 hardware decoding? It's disabled from the 10.8 log.

**Comment by marys1234** [comment]
Yes it is, see encoding.xml
[encoding.xml.txt](https://github.com/jellyfin/jellyfin/files/9668871/encoding.xml.txt)
