### ISSUE TITLE
[Issue]: No DD 5.1 audio on direct stream

### ISSUE THREAD

**Issue by Hallo951** [jellyfin/jellyfin#8462]
### Please describe your bug

I'm getting the creeps once again. I just get no audio when I want to play a movie with a Dolby Digital 5.1 audio track in direct play via jellyfin (running in a docker) on my LG TV. If the movie needs to be transcoded, for example because of the subtitles or a DTS audio track, I have normal audio and everything works. The following things I have already tried while troubleshooting.

1. play the affected movie directly on the TV with the native player using a USB stick. Result: The movie plays without glitches with the dolby digital .5.1 audio track. So it can't be the movie itself, since it plays without problems on my TV.

2. completely uninstalled jellyfin webos client on the TV and reinstalled it again. Result: no fix of the error.

3. reinstalled jellyfin on my NAS (synology D920+) in docker using new containers in version 10.8.4 and 10.8.5. Result: no fix for the error.

As I said, I'm really desperate why this does not work in direct play via jellyfin. Is there any audiocodec missing on my NAS or is this a direct error in jellyfin? I have already ruled out all other sources of error (TV, client). So the error must be in jellyfin. It is almost as if there is no audio at all. Which of course is not true, since the movie works fine natively via USB on the TV. I just don't understand this. 

Please please please help me!!!

### Jellyfin Version

10.8.5

### Environment

```- OS: Synolgy DS 920+
- Virtualization: Docker
- Clients: LG TV (webos 5)
- Browser:
- FFmpeg Version: current
- Playback Method:
- Hardware Acceleration: QSV with tone mapping and subtitles
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking: 5 Ghz Wifi (100% Signal)
- Storage: NSF
```

### Jellyfin logs

[log_20220926 (1).log](https://github.com/jellyfin/jellyfin/files/9649467/log_20220926.1.log)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Hallo951** [comment]
Update:

I have now reset the entire TV to factory settings. Result: No solution to the problem.

I have completely uninstalled and reinstalled ffmpeg. Result: No solution of the problem.

I have connected the TV via LAN: Result: no solution to the problem.

I connected the NAS to another place in the network. Result: no solution to the problem.

I also noticed that jellyfin has a problem with switching audio tracks in general (at least for me). When I change the audio track, it is immediately displayed in the playback information on the TV under original media information, but the sound does not come immediately or sometimes not at all.

**Comment by Hallo951** [comment]
I have found out something new. The playback of movies with DD (ac3) does not work only for some movies. Many movies do work. Others do not (e.g. The Accountant or Ad Astra). 

I had the misfortune to get exactly those movies which do not work. I haven't found out yet what makes the difference between a non working ac3 audio track and a working ac3 audio track. 

Are there different versions within the ac3 codec or something? 

Is there a log from the client itself somewhere where you can see what it is doing to identify errors? 

Is there a tool to read information from the mkv's, especially their audio tracks? VLC says with the not working and working movies that the ac3 audio tracks are identical from the codec. As a reminder, the movies that don't work on the webos work on all other clients as well as with the native player from LG. So somewhere on the webos client there is something wrong with certain ac3 audio tracks.

**Comment by iwatch-x** [comment]
i have a kind of same issue the issue is eac3 plays on my lg tv but after the 10.8.5 update it sounds like it plays true a tube of pipe

**Comment by Hallo951** [comment]
So, I have now tested the same film with Emby and everything works there on the same TV. So unfortunately the fault lies 100% with jellyfin or with the jellyfin webos client. My guess is rather the second, because otherwise many more people would have complained.

Another problem, which I'm sure also has to do with the client, is the fact that I can't get jellyfin to play a film with a pcm_s24le audio track in conjunction with the webos client so that I also have sound. Normally it would have to transcode this audio track as my TV doesn't support it natively. However, Jellyfin thinks that my TV can do this and plays the film in direct play, with the result that the film has no sound. Adjusting the dlna profile has no effect with the webos client. It works with emby.
