### ISSUE TITLE
Pixelated Video

### ISSUE THREAD

**Issue by markcagatandavis** [jellyfin/jellyfin#8467]
When watching this series via Jellyfin I am getting pixelated video. For some reason only seems to be happening to this series... I did watch this using VLC on my computer and seems to work without any issues. Transcoding seems to work fine on other videos and HA without issues. Let me know if you require additional details.  

**Media Info of the file**
[Jellyfin_10.8.4_MediaInfo.txt](https://github.com/jellyfin/jellyfin/files/9664521/Jellyfin_10.8.4_MediaInfo.txt)

**Logs**

[Jellyfin_10.8.4_Logs.txt](https://github.com/jellyfin/jellyfin/files/9664530/Jellyfin_10.8.4_Logs.txt)

**FFmpeg Logs**
[Jellyfin_10.8.4_FFMPEG.txt](https://github.com/jellyfin/jellyfin/files/9664574/Jellyfin_10.8.4_FFMPEG.txt)

**Stats for Nerds Screenshots**
![image](https://user-images.githubusercontent.com/29704539/192768524-d214c6b7-ebf8-4d36-816c-9e24698975b0.png)

**Server System (please complete the following information):**
 - OS: Linux Synology DiskStation Manager 7.1-42661
 - Jellyfin Version: 10.8.4
 - Hardware settings & device: Intel QuickYnc (QSV)
 - Reverse proxy: Synology Reverse Proxy
 - Other hardware notes:  Synology DiskStation DS920+ + 4x 16TB WD red drives + HA enabled with correct drivers added and permissions.
 
**Client System (please complete the following information):**
 - Device: Tested on: Winodws 10 OS , Android Samsung App, Heisens TV with Google TV app
 - OS: Windows & Android
 - Client: Web/Browser, Android, Android TV
 - Browser (if Web client): Chrome, MS Edge
 - Client and Browser Version: Version 105.0.1343.50 (Official build) (64-bit)

Thanks :)

**Comment by nyanmisaka** [comment]
```
[h264 @ 0x5643050bf540] top block unavailable for requested intra mode -1
[h264 @ 0x5643050bf540] error while decoding MB 6 0, bytestream 190881
[h264 @ 0x5643050bf540] concealing 8160 DC, 8160 AC, 8160 MV errors in I frame
[h264 @ 0x564305353900] mmco: unref short failure
[h264 @ 0x5643050d4e40] top block unavailable for requested intra mode
[h264 @ 0x5643050d4e40] error while decoding MB 7 0, bytestream 43805
[h264 @ 0x5643050d4e40] concealing 8160 DC, 8160 AC, 8160 MV errors in P frame
[h264 @ 0x564305353900] top block unavailable for requested intra mode -1
[h264 @ 0x564305353900] error while decoding MB 39 0, bytestream 4977
[h264 @ 0x564305353900] concealing 8160 DC, 8160 AC, 8160 MV errors in B frame
```

This is caused by the broken x264 encoder that used to encode this H.264 High 4:4:4  video.

You have to fix the video by yourself. See this reply: https://github.com/jellyfin/jellyfin-ffmpeg/issues/47#issuecomment-741722767

**Comment by markcagatandavis** [comment]
> 

This sadly didn't work :( 

`C:\FFMPEG\bin>ffmpeg -i "Made in Abyss - S01E13 - The Challengers HDTV-1080p.mkv" -c:v copy -an -sn -y "raw.h264"
ffmpeg version 2022-10-20-git-eb9153b4a7-full_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 12.1.0 (Rev2, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libvpl --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      57. 39.101 / 57. 39.101
  libavcodec     59. 51.100 / 59. 51.100
  libavformat    59. 34.101 / 59. 34.101
  libavdevice    59.  8.101 / 59.  8.101
  libavfilter     8. 49.101 /  8. 49.101
  libswscale      6.  8.112 /  6.  8.112
  libswresample   4.  9.100 /  4.  9.100
  libpostproc    56.  7.100 / 56.  7.100
Input #0, matroska,webm, from 'Made in Abyss - S01E13 - The Challengers HDTV-1080p.mkv':
  Metadata:
    encoder         : libebml v1.3.4 + libmatroska v1.4.5
    creation_time   : 2017-10-12T07:17:25.000000Z
  Duration: 00:47:20.80, start: 0.000000, bitrate: 3696 kb/s
  Stream #0:0(jpn): Video: h264 (High 4:4:4 Predictive), yuv444p10le(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn (default)
    Metadata:
      BPS             : 3470735
      BPS-eng         : 3470735
      DURATION        : 00:47:20.797000000
      DURATION-eng    : 00:47:20.797000000
      NUMBER_OF_FRAMES: 68111
      NUMBER_OF_FRAMES-eng: 68111
      NUMBER_OF_BYTES : 1232457034
      NUMBER_OF_BYTES-eng: 1232457034
      _STATISTICS_WRITING_APP: mkvmerge v13.0.0 ('The Juggler') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v13.0.0 ('The Juggler') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2017-10-12 07:17:25
      _STATISTICS_WRITING_DATE_UTC-eng: 2017-10-12 07:17:25
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:1(jpn): Audio: eac3, 48000 Hz, stereo, fltp, 224 kb/s (default)
    Metadata:
      BPS             : 224000
      BPS-eng         : 224000
      DURATION        : 00:47:20.800000000
      DURATION-eng    : 00:47:20.800000000
      NUMBER_OF_FRAMES: 88775
      NUMBER_OF_FRAMES-eng: 88775
      NUMBER_OF_BYTES : 79542400
      NUMBER_OF_BYTES-eng: 79542400
      _STATISTICS_WRITING_APP: mkvmerge v13.0.0 ('The Juggler') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v13.0.0 ('The Juggler') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2017-10-12 07:17:25
      _STATISTICS_WRITING_DATE_UTC-eng: 2017-10-12 07:17:25
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:2(eng): Subtitle: ass (default)
    Metadata:
      BPS             : 95
      BPS-eng         : 95
      DURATION        : 00:47:07.710000000
      DURATION-eng    : 00:47:07.710000000
      NUMBER_OF_FRAMES: 664
      NUMBER_OF_FRAMES-eng: 664
      NUMBER_OF_BYTES : 33739
      NUMBER_OF_BYTES-eng: 33739
      _STATISTICS_WRITING_APP: mkvmerge v13.0.0 ('The Juggler') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v13.0.0 ('The Juggler') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2017-10-12 07:17:25
      _STATISTICS_WRITING_DATE_UTC-eng: 2017-10-12 07:17:25
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:3(por): Subtitle: ass
    Metadata:
      BPS             : 86
      BPS-eng         : 86
      DURATION        : 00:47:07.710000000
      DURATION-eng    : 00:47:07.710000000
      NUMBER_OF_FRAMES: 630
      NUMBER_OF_FRAMES-eng: 630
      NUMBER_OF_BYTES : 30691
      NUMBER_OF_BYTES-eng: 30691
      _STATISTICS_WRITING_APP: mkvmerge v13.0.0 ('The Juggler') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v13.0.0 ('The Juggler') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2017-10-12 07:17:25
      _STATISTICS_WRITING_DATE_UTC-eng: 2017-10-12 07:17:25
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:4(spa): Subtitle: ass
    Metadata:
      BPS             : 87
      BPS-eng         : 87
      DURATION        : 00:47:07.710000000
      DURATION-eng    : 00:47:07.710000000
      NUMBER_OF_FRAMES: 633
      NUMBER_OF_FRAMES-eng: 633
      NUMBER_OF_BYTES : 30933
      NUMBER_OF_BYTES-eng: 30933
      _STATISTICS_WRITING_APP: mkvmerge v13.0.0 ('The Juggler') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v13.0.0 ('The Juggler') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2017-10-12 07:17:25
      _STATISTICS_WRITING_DATE_UTC-eng: 2017-10-12 07:17:25
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
Output #0, h264, to 'raw.h264':
  Metadata:
    encoder         : Lavf59.34.101
  Stream #0:0(jpn): Video: h264 (High 4:4:4 Predictive), yuv444p10le(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 23.98 fps, 23.98 tbr, 23.98 tbn (default)
    Metadata:
      BPS             : 3470735
      BPS-eng         : 3470735
      DURATION        : 00:47:20.797000000
      DURATION-eng    : 00:47:20.797000000
      NUMBER_OF_FRAMES: 68111
      NUMBER_OF_FRAMES-eng: 68111
      NUMBER_OF_BYTES : 1232457034
      NUMBER_OF_BYTES-eng: 1232457034
      _STATISTICS_WRITING_APP: mkvmerge v13.0.0 ('The Juggler') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v13.0.0 ('The Juggler') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2017-10-12 07:17:25
      _STATISTICS_WRITING_DATE_UTC-eng: 2017-10-12 07:17:25
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
Press [q] to stop, [?] for help
frame=68111 fps=39072 q=-1.0 Lsize= 1203571kB time=00:47:20.67 bitrate=3470.9kbits/s speed=1.63e+03x
video:1203571kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown

C:\FFMPEG\bin>ffpeg -i ""c:\temp\raw.h264" -i "C:\temp\Made in Abyss - S01E13 - The Challengers HDTV-1080p.mkv" map 0:v -c:v copy -bsf:v h264_metadata="sei_user_data=dc45e9bde6d948b7962cd820d923eeef+x264 - core 148 r2721+55 e19946b t_mod_Custom [10-bit@all X86_64]" -an -sn -v quiet -y "videostream.mp4"
'ffpeg' is not recognized as an internal or external command,
operable program or batch file.

C:\FFMPEG\bin>ffpeg -i "raw.h264" -i "Made in Abyss - S01E13 - The Challengers HDTV-1080p.mkv" map 0:v -c:v copy -bsf:v h264_metadata="sei_user_data=dc45e9bde6d948b7962cd820d923eeef+x264 - core 148 r2721+55 e19946b t_mod_Custom [10-bit@all X86_64]" -an -sn -v quiet -y "videostream.mp4"
'ffpeg' is not recognized as an internal or external command,
operable program or batch file.

C:\FFMPEG\bin>ffmpeg -i "raw.h264" -i "Made in Abyss - S01E13 - The Challengers HDTV-1080p.mkv  -map 0:v -c:v copy -bsf:v h264_metadata="sei_user_data=dc45e9bde6d948b7962cd820d923eeef+x264 - core 148 r2721+55 e19946b t_mod_Custom [10-bit@all X86_64]" -an -sn -v quiet -y "videostream.mp4"
ffmpeg version 2022-10-20-git-eb9153b4a7-full_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 12.1.0 (Rev2, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libvpl --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      57. 39.101 / 57. 39.101
  libavcodec     59. 51.100 / 59. 51.100
  libavformat    59. 34.101 / 59. 34.101
  libavdevice    59.  8.101 / 59.  8.101
  libavfilter     8. 49.101 /  8. 49.101
  libswscale      6.  8.112 /  6.  8.112
  libswresample   4.  9.100 /  4.  9.100
  libpostproc    56.  7.100 / 56.  7.100
Input #0, h264, from 'raw.h264':
  Duration: N/A, bitrate: N/A
  Stream #0:0: Video: h264 (High 4:4:4 Predictive), yuv444p10le(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1200k tbn
Made in Abyss - S01E13 - The Challengers HDTV-1080p.mkv  -map 0:v -c:v copy -bsf:v h264_metadata=sei_user_data=dc45e9bde6d948b7962cd820d923eeef+x264: Invalid argument

C:\FFMPEG\bin>ffmpeg -i "raw.h264" -i "Made in Abyss - S01E13 - The Challengers HDTV-1080p.mkv" -map 0:v -c:v copy -bsf:v h264_metadata="sei_user_data=dc45e9bde6d948b7962cd820d923eeef+x264 - core 148 r2721+55 e19946b t_mod_Custom [10-bit@all X86_64]" -an -sn -v quiet -y "videostream.mp4"

C:\FFMPEG\bin>ffmpeg -i "videostream.mp4" -i "Made in Abyss - S01E13 - The Challengers HDTV-1080p.mkv"  -map 0:v -map 1:a -map 1:s -c:v copy -c:a copy -c:s copy -v quiet -y "FinalExport.mp4"

C:\FFMPEG\bin>ffmpeg -i "videostream.mp4" -i "Made in Abyss - S01E13 - The Challengers HDTV-1080p.mkv"  -map 0:v -map 1:a -map 1:s -c:v copy -c:a copy -c:s copy -v quiet -y "FinalExport.mp4"

C:\FFMPEG\bin>ffmpeg -i "videostream.mp4" -i "Made in Abyss - S01E13 - The Challengers HDTV-1080p.mkv" -map 0:v -map 1:a -map 1:s -c:v copy -c:a copy -c:s copy -v quiet -y "FinalExport.mp4"

C:\FFMPEG\bin>ffmpeg -i "videostream.mp4" -i "Made in Abyss - S01E13 - The Challengers HDTV-1080p.mkv" -map 0:v -map 1:a -map 1:s -c:v copy -c:a copy -c:s copy -v quiet -y "FinalExport.mp4"

C:\FFMPEG\bin>ffmpeg -i "videostream.mp4" -i "Made in Abyss - S01E13 - The Challengers HDTV-1080p.mkv" -map 0:v -map 1:a -map 1:s -c:v copy -c:a copy -c:s copy -v quiet -y "Fatekaleid liner Prisma☆Illya 3rei!! NCED1 ger sub fixed.mp4"

C:\FFMPEG\bin>ffmpeg -i "videostream.mp4" -i "Made in Abyss - S01E13 - The Challengers HDTV-1080p.mkv" -map 0:v -map 1:a -map 1:s -c:v copy -c:a copy -c:s copy -v quiet -y "FinalExport.mp4"

C:\FFMPEG\bin>ffmpeg -i "c:\ffmpeg\bin\videostream.mp4" -i "c:\ffmpeg\bin\Made in Abyss - S01E13 - The Challengers HDTV-1080p.mkv" -map 0:v -map 1:a -map 1:s -c:v copy -c:a copy -c:s copy -v quiet -y "FinalExport.mp4"

C:\FFMPEG\bin>ffmpeg -i "c:\ffmpeg\bin\videostream.mp4" -i "c:\ffmpeg\bin\Made in Abyss - S01E13 - The Challengers HDTV-1080p.mkv" -map 0:v -map 1:a -map 1:s -c:v copy -c:a copy -c:s copy -v quiet -y "FinalExport.mkv"

C:\FFMPEG\bin>ffmpeg -i "Made in Abyss - S01E12 - The True Nature of the Curse HDTV-1080p.mkv" -c:v copy -an -sn -y "raw.h264"
ffmpeg version 2022-10-20-git-eb9153b4a7-full_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 12.1.0 (Rev2, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libvpl --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      57. 39.101 / 57. 39.101
  libavcodec     59. 51.100 / 59. 51.100
  libavformat    59. 34.101 / 59. 34.101
  libavdevice    59.  8.101 / 59.  8.101
  libavfilter     8. 49.101 /  8. 49.101
  libswscale      6.  8.112 /  6.  8.112
  libswresample   4.  9.100 /  4.  9.100
  libpostproc    56.  7.100 / 56.  7.100
Input #0, matroska,webm, from 'Made in Abyss - S01E12 - The True Nature of the Curse HDTV-1080p.mkv':
  Metadata:
    encoder         : libebml v1.3.4 + libmatroska v1.4.5
    creation_time   : 2017-10-12T07:16:30.000000Z
  Duration: 00:23:41.18, start: 0.000000, bitrate: 4801 kb/s
  Stream #0:0(jpn): Video: h264 (High 4:4:4 Predictive), yuv444p10le(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn (default)
    Metadata:
      BPS             : 4575382
      BPS-eng         : 4575382
      DURATION        : 00:23:41.170000000
      DURATION-eng    : 00:23:41.170000000
      NUMBER_OF_FRAMES: 34074
      NUMBER_OF_FRAMES-eng: 34074
      NUMBER_OF_BYTES : 812799476
      NUMBER_OF_BYTES-eng: 812799476
      _STATISTICS_WRITING_APP: mkvmerge v13.0.0 ('The Juggler') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v13.0.0 ('The Juggler') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2017-10-12 07:16:30
      _STATISTICS_WRITING_DATE_UTC-eng: 2017-10-12 07:16:30
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:1(jpn): Audio: eac3, 48000 Hz, stereo, fltp, 224 kb/s (default)
    Metadata:
      BPS             : 224000
      BPS-eng         : 224000
      DURATION        : 00:23:41.184000000
      DURATION-eng    : 00:23:41.184000000
      NUMBER_OF_FRAMES: 44412
      NUMBER_OF_FRAMES-eng: 44412
      NUMBER_OF_BYTES : 39793152
      NUMBER_OF_BYTES-eng: 39793152
      _STATISTICS_WRITING_APP: mkvmerge v13.0.0 ('The Juggler') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v13.0.0 ('The Juggler') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2017-10-12 07:16:30
      _STATISTICS_WRITING_DATE_UTC-eng: 2017-10-12 07:16:30
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:2(eng): Subtitle: ass (default)
    Metadata:
      BPS             : 115
      BPS-eng         : 115
      DURATION        : 00:23:38.170000000
      DURATION-eng    : 00:23:38.170000000
      NUMBER_OF_FRAMES: 398
      NUMBER_OF_FRAMES-eng: 398
      NUMBER_OF_BYTES : 20387
      NUMBER_OF_BYTES-eng: 20387
      _STATISTICS_WRITING_APP: mkvmerge v13.0.0 ('The Juggler') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v13.0.0 ('The Juggler') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2017-10-12 07:16:30
      _STATISTICS_WRITING_DATE_UTC-eng: 2017-10-12 07:16:30
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:3(por): Subtitle: ass
    Metadata:
      BPS             : 102
      BPS-eng         : 102
      DURATION        : 00:23:38.130000000
      DURATION-eng    : 00:23:38.130000000
      NUMBER_OF_FRAMES: 361
      NUMBER_OF_FRAMES-eng: 361
      NUMBER_OF_BYTES : 18119
      NUMBER_OF_BYTES-eng: 18119
      _STATISTICS_WRITING_APP: mkvmerge v13.0.0 ('The Juggler') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v13.0.0 ('The Juggler') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2017-10-12 07:16:30
      _STATISTICS_WRITING_DATE_UTC-eng: 2017-10-12 07:16:30
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:4(spa): Subtitle: ass
    Metadata:
      BPS             : 99
      BPS-eng         : 99
      DURATION        : 00:23:38.130000000
      DURATION-eng    : 00:23:38.130000000
      NUMBER_OF_FRAMES: 350
      NUMBER_OF_FRAMES-eng: 350
      NUMBER_OF_BYTES : 17606
      NUMBER_OF_BYTES-eng: 17606
      _STATISTICS_WRITING_APP: mkvmerge v13.0.0 ('The Juggler') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v13.0.0 ('The Juggler') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2017-10-12 07:16:30
      _STATISTICS_WRITING_DATE_UTC-eng: 2017-10-12 07:16:30
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
Output #0, h264, to 'raw.h264':
  Metadata:
    encoder         : Lavf59.34.101
  Stream #0:0(jpn): Video: h264 (High 4:4:4 Predictive), yuv444p10le(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 23.98 fps, 23.98 tbr, 23.98 tbn (default)
    Metadata:
      BPS             : 4575382
      BPS-eng         : 4575382
      DURATION        : 00:23:41.170000000
      DURATION-eng    : 00:23:41.170000000
      NUMBER_OF_FRAMES: 34074
      NUMBER_OF_FRAMES-eng: 34074
      NUMBER_OF_BYTES : 812799476
      NUMBER_OF_BYTES-eng: 812799476
      _STATISTICS_WRITING_APP: mkvmerge v13.0.0 ('The Juggler') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v13.0.0 ('The Juggler') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2017-10-12 07:16:30
      _STATISTICS_WRITING_DATE_UTC-eng: 2017-10-12 07:16:30
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
Press [q] to stop, [?] for help
frame=34074 fps=0.0 q=-1.0 Lsize=  793749kB time=00:23:41.04 bitrate=4575.8kbits/s speed=1.54e+03x
video:793749kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown

C:\FFMPEG\bin>C:\FFMPEG\bin>ffmpeg -i "videostream.mp4" -i "Made in Abyss - S01E12 - The True Nature of the Curse HDTV-1080p.mkv" -map 0:v -map 1:a -map 1:s -c:v copy -c:a copy -c:s copy -v quiet -y "FinalExport.mp4"
'C:\FFMPEG\bin' is not recognized as an internal or external command,
operable program or batch file.

C:\FFMPEG\bin>ffmpeg -i "videostream.mp4" -i "Made in Abyss - S01E12 - The True Nature of the Curse HDTV-1080p.mkv" -map 0:v -map 1:a -map 1:s -c:v copy -c:a copy -c:s copy -v quiet -y "FinalExport.mp4"

C:\FFMPEG\bin>ffmpeg -i "raw.h264" -i "Made in Abyss - S01E12 - The True Nature of the Curse HDTV-1080p.mkv" -map 0:v -c:v copy -bsf:v h264_metadata="sei_user_data=dc45e9bde6d948b7962cd820d923eeef+x264 - core 148 r2721+55 e19946b t_mod_Custom [10-bit@all X86_64]" -an -sn -v quiet -y "videostream.mp4"

C:\FFMPEG\bin>ffmpeg -i "videostream.mp4" -i "Made in Abyss - S01E12 - The True Nature of the Curse HDTV-1080p.mkv" -map 0:v -map 1:a -map 1:s -c:v copy -c:a copy -c:s copy -v quiet -y "FinalExport.mkv"

C:\FFMPEG\bin>ffmpeg -i "videostream.mp4" -i "Made in Abyss - S01E12 - The True Nature of the Curse HDTV-1080p.mkv" -map 0:v -map 1:a -map 1:s -c:v copy -c:a copy -c:s copy -v quiet -y "FinalExport.mp4"`

I can see the file size did grow by a few MB's. Everything works fine if I play it on VLC on the PC but just not via Jellyfin.

**Comment by markcagatandavis** [comment]
This can be closed. I got another source and works fine. Thanks :)
