### ISSUE TITLE
Feature: Add music/Albums to personal user libary

### ISSUE THREAD

**Issue by coreybruce** [jellyfin/jellyfin#8481]
Hi I would  like request the ability to be able to add music on my own server into from your personal per user collection to your own personal library that you than can play or shuffle similar to how Spotify or Youtube Music does it as it makes the music player on Jellyfin feel incomplete and seems like it's only for single user use.  I have a few of my family members who use my jellyfin sever so I would be adding a big variety of music.

I will use Youtube Music as a example as I use it

![image](https://user-images.githubusercontent.com/8393780/193403249-3b134fac-1370-478d-9de7-b6e1c170e06a.png)

![image](https://user-images.githubusercontent.com/8393780/193403269-76ba09fa-be88-4a77-8a47-5b4c24f4abb9.png)

![image](https://user-images.githubusercontent.com/8393780/193403285-9c5939e8-3195-4755-b701-95e80e5590c8.png)

![image](https://user-images.githubusercontent.com/8393780/193403378-4ae2697a-305f-42d8-bc65-4c18d7b4cf1d.png)

![image](https://user-images.githubusercontent.com/8393780/193403382-06705667-3a38-4416-ba28-d90b4a1c5e97.png)

The Music player works but ineeds work, feels very basic and missing features that would make this a fantastic and even better than Youtube Music or Spotify since you have full control over your content and server that you can run yourself. :smile:

**Comment by coreybruce** [comment]
I'm still here waiting to see some progress on this

**Comment by Bond-009** [comment]
Feature requests go here: https://features.jellyfin.org/
