### ISSUE TITLE
[Issue]: All the posters are blurry and impossible to have an image instead

### ISSUE THREAD

**Issue by maverick40** [jellyfin/jellyfin#8482]
### Please describe your bug

I just replaced Emby (prenium) with Jellyfin (which I find much superior). I have all my perfect architecture with the poster and nfo already present on my server. The problem is that jellyfin does not add me any poster, only a blurry location instead.

### Jellyfin Version

10.8.0

### if other:

10.8.5

### Environment

```markdown
- OS:Open Media Vault
- Virtualization:
- Clients:Safari 
- Browser:
- FFmpeg Version:
- Playback Method:Webos TV LG OLED
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:FIBRE
- Storage:3HDD Internal
```

### Please attach any screenshots here

https://share.cleanshot.com/8Spdkb

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by LePips** [comment]
That's the BlurHash of the image, it's used as a placeholder while your image is loading. Clearly, your image isn't loading fast enough or at all.

**Comment by sand-bit** [comment]
This seems to still happen even on a local network. Host is an AMD Zen 3 eight core, and the media is located on a SSD. 
Happens on the web/browser player. Issue goes away on page refresh, so it seems like there is an underlying issue here.

**Comment by scicomrunner** [comment]
try updating your jellyfin version a blur fix was released in 1.8.6

**Comment by peterzolczer** [comment]
I have this very issue on my fresh install on docker, 10.8.10. Blurry or no (cover/artist/poster/etc.) images, doesn't matter whether I use a client or open it in browser:

![image](https://github.com/jellyfin/jellyfin/assets/121183484/c33e450b-b75d-4630-b6c7-b966e7aceaf5)

**Comment by sina510** [comment]
Mine is doing it too but only to some movies and not others and only on different devices than the server. On the server everything looks fine but on other devices half the movies are blurry.![Image](https://github.com/user-attachments/assets/84c6e4ef-c5a2-440b-9aae-23627f7425e6)
