### ISSUE TITLE
[Issue]: tvshow.nfo `namedseason` not working

### ISSUE THREAD

**Issue by jmbannon** [jellyfin/jellyfin#8489]
### Please describe your bug

```
<?xml version='1.0' encoding='utf-8'?>
<tvshow>
  <genre>Music</genre>
  <namedseason number="1">Videos</namedseason>
  <namedseason number="2">Music Videos</namedseason>
  <title>Beyond the Guitar</title>
</tvshow>
```
The `tvshow.nfo` above does not recognize named seasons when importing custom tv shows. Names them as Season 1, Season 2, etc

See namedseason kodi usage here: https://kodi.wiki/view/NFO_files/TV_shows

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shadowghost** [comment]
https://github.com/jellyfin/jellyfin/pull/8203 implements this.

**Comment by jmbannon** [comment]
This issue still affects me

**Comment by Code-Slave** [comment]
Whats the issue with the pull request. This would be a nice addition

**Comment by vegedb** [comment]
@crobibero 

May we know what's the new naming convention in nfo?
