### ISSUE TITLE
[Issue]: user can remove media from collection even if thats prohibited

### ISSUE THREAD

**Issue by Karmylr** [jellyfin/jellyfin#8494]
### Please describe your bug

I have chosen to prevent media from being removed from the collection, but still can remove

### Jellyfin Version

Other

### if other:

10.8.5

### Environment

```markdown
- OS:ubuntu
- Virtualization:yes
- Clients:android phone
- Browser:chrome
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by neilsb** [comment]
The user settings for "Allow media deletion from" is specifically to prevent users from deleting media from the disk.   I don't believe collections should really appear in this list, as the settings related to the library in which the media exists will control whether it can be deleted or not.

However, this setting is not intended to allow you to control whether users can add or remove items to the collection.   There is a [existing feature request](https://features.jellyfin.org/posts/1591/permission-for-collection-management) for permissions on collections which should be followed for progress on what you are describing.
