### ISSUE TITLE
[Issue]: HEVC content getting transcoded back to HEVC

### ISSUE THREAD

**Issue by erdemoney** [jellyfin/jellyfin#8495]
Hi I just set Jellyfin up for the first time after using Plex for many years and am unfortunately running into some issues with my library of 1080p h.265 (HEVC) content. When playing movies in the jellyfin web player in Safari 16 (which supports HEVC) I am seeing my content be transcoded to HEVC with the reason "The video codec is not supported"
![Screen Shot 2022-10-04 at 11 11 25 PM](https://user-images.githubusercontent.com/21229271/194120427-7c58767d-eea1-4740-a634-3040817ed128.png)

If its transcoding to HEVC and playing HEVC then that means that it must recognize my player supports HEVC so why is it transcoding in the first place? Plex will direct play my content no problem.
![Screen Shot 2022-10-04 at 11 55 13 PM](https://user-images.githubusercontent.com/21229271/194120577-3f79a654-4752-4bca-9e9f-e3706fbc13a7.png)

FFmpeg logs show "SupportsDirectStream" and "SupportsDirectPlay" as true but im not sure if that means what I think it does.
`
{"Protocol":0,"Id":"cffe23b640e5698a0f152df8e85f3d1d","Path":"/media/movies/Howl\u0027s Moving Castle (2004)/Howls.Moving.Castle.2004.BluRay.1080p.x265.10bit.4Audio.MNHD-FRDS.mkv","EncoderPath":null,"EncoderProtocol":null,"Type":0,"Container":"mkv,webm","Size":5901484032,"Name":"Howls.Moving.Castle.2004.BluRay.1080p.x265.10bit.4Audio.MNHD-FRDS","IsRemote":false,"ETag":"247efa5fde6ae00872a2fe51c897387c","RunTimeTicks":71491837952,"ReadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"OpenToken":null,"RequiresClosing":false,"LiveStreamId":null,"BufferMs":null,"RequiresLooping":false,"SupportsProbing":true,"VideoType":0,"IsoType":null,"Video3DFormat":null,"MediaStreams":
`

### Jellyfin Version

Other

### if other:

10.8.5

### Environment

```markdown
- OS: TrueNAS Scale (Debian)
- Virtualization: No
- Clients: Browser
- Browser: Safari
- FFmpeg Version: 5.1.1-Jellyfin
- Playback Method: Direct Play/Transcode
- Hardware Acceleration: Yes (GPU)
- Plugins: None
- Reverse Proxy: Traefik
- Base URL: None
- Networking: Host
- Storage: local
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by erdemoney** [comment]
Referencing this: https://jellyfin.org/docs/general/clients/codec-support.html
My content is using the .mkv container, which is not supported by Safari however it still should not be transcoding. It should just be remuxing it to .mp4 or whatever. I found that if I restrict transcoding for my user I can force the correct behavior as shown below.
![Screen Shot 2022-10-05 at 11 02 30 AM](https://user-images.githubusercontent.com/21229271/194130713-9029b68a-5a98-456c-8a15-a2e7da55bc07.png)

**Comment by aldasa** [comment]
Similar issue to this so didn't want to open another bug report.

I use a custom version of chrome that is built with HVEC support, and have the same problem.

also restricting user transcode allows the video to playback as normal.

**Comment by Shadowghost** [comment]
The main culprit here ishould be the codec being `HEVC Main 10`. Essentially this means that the source material has 10 bit color depth (or at least that's the profile it was encoded with) - which is unsupported on most browsers.

FYI: In the case of custom chromium builds we can't recognize those so the normal chrome support flags are used. They obviously get ignored if you disable transcoding.

**Comment by eyezak** [comment]
This will work without disabling transcoding, if you enable User Settings -> Playback -> "Prefer fMP4-HLS Media Container". It is unfortunate this does not enable by default for safari.

Note: HDR support for safari is limited to specific models and display outputs. See https://support.apple.com/en-ca/HT210980 for details.

**Comment by kiler129** [comment]
> The main culprit here ishould be the codec being `HEVC Main 10`. Essentially this means that the source material has 10 bit color depth (or at least that's the profile it was encoded with) - which is unsupported on most browsers and require transcode for 8 bit displays too.

Correct me if I'm wrong, but Safari does generally support HDR playback, even if it does its own tone mapping for 8 bit displays. In my case Jellyfin forcefully transcodes `HEVC Main 10` to `H264` claiming that the codec is not supported. Remuxing the video from mkv to mp4 without any other changes makes it playable in Safari.
Attempting to transcode HEVC to H264 on a 80Mb/s file results in ~19fps with my NVENC ;)



> Note: HDR support for safari is limited to specific models and display outputs. See https://support.apple.com/en-ca/HT210980 for details.

I believe these are requirements for HDR playback to actually display HDR, but it will play HDR with tone mapping on older hardware as well. However, I don't have anything to test with.

**Comment by guiweber** [comment]
I'm seeing the same issue on Firefox (Windows). I just moved from Emby and I was surprised that all the HEVC movies that were direct playing in the browser with Emby needed transcoding with Jellyfin. Checking the "Prefer fMP4-HLS Media Container" option fixed the issue.

Why isn't the option set by default on the browsers where it is beneficial?

**Comment by blampe** [comment]
> When playing movies in the jellyfin web player in Safari 16 (which supports HEVC)

Safari supports _some_ flavors of HEVC. In particular it only supports the `hvc1` format and not `hev1`. 

https://developer.apple.com/documentation/http-live-streaming/hls-authoring-specification-for-apple-devices#Video

> 1.10. You SHOULD use video formats in which the parameter sets are stored in the sample descriptions, rather than the samples. (That is, use 'avc1', 'hvc1', or 'dvh1' rather than 'avc3', 'hev1', or 'dvhe'.)

It's possible you're seeing transcoding due to your container having the wrong format. If this is the case, you can fix it by re-tagging the media with `hvc1`:

```
ffmpeg -vcodec copy -acodec copy -tag:v hvc1 -i in.mp4 out.mp4
```

If this is the source of your problem, attempting to play `in.mp4` locally (in QuickTime) will give you an error like "This file contains some media which isn't compatible with QuickTime Player". Playing the re-tagged `out.mp4` works fine.

Perhaps JF could detect this and remux to `hvc1` instead of transcoding?

**Comment by kiler129** [comment]
AFAIK this is still an issue. These bots are a cancer of GitHub.

**Comment by ben-xx** [comment]
What is happening:
- .mkv & .mp4 container h265 streams are transcoded to h264, MPEG Transport Stream (.ts files) for Safari-based clients

What could (should?) happen:
- if Safari version >= 11
- .mkv & .mp4 h265 streams get remuxed to "hvc1" tagged mp4 fragments (fMP4)
- default "Prefer fMP4-HLS Media Container" to ON (when on Safari client)
- rename "Prefer fMP4-HLS Media Container" toggle to "Prefer Streaming / DirectPlay" (see thoughts below)

Who's affected:
- the ~17% that use Safari/Jellyfin app on iPadOS/iOS/MacOS ([caniuse.com](https://caniuse.com/?search=hevc))
- Chrome (& Jellyfin Android app) is OK / not affected (63%+ users)
- Firefox/Edge/Opera... HEVC hardly supported / too small

Questions / Unknowns:
- would this work for h265 10 bit streams?
- for HEVC HDR streams?
---

Just adding a +1 to issue and describing my situation/experience.

To avoid Jellyfin transcoding 265 (8 bit) -> 264 for Safari 17.2 client (MacOS 14.2.1)...

I needed to:
- convert mkv to mp4 container, and
- `ffmpeg -tag:v hvc1` the mp4 (it can't be "hev1" for Safari)
- client side Jellyfin profile set "Prefer fMP4-HLS Media Container": **ON** (I think?)

Result:
- Jellyfin remuxed mp4 into fragmented mp4 (fMP4), without transcoding to h264

Thanks to everyone in this thread for the help.

---
Thoughts on renaming "Prefer fMP4-HLS Media Container"

This is the current description:

> "Prefer fMP4-HLS Media Container"
> Prefer to use fMP4 as the default container for HLS, making it possible to direct stream HEVC content on supported devices.

Maybe something along the lines of:

> "Prefer Streaming / DirectPlay"
> Avoid transcoding video when simply repackaging container will allow play on your device. (Easier on Jellyfin server.)

I'm a complete noob re: video stuff, only learning about ffmpeg/Jellyfin this past week, but pretty comfortable in tech stuff generally and the amount of jargon / acronyms / competing standards in video stuff is mindboggling.  Kudos & thanks to all the guys (brave souls) who contribute to making Jellyfin.  It's a great project.

**Comment by nyanmisaka** [comment]
> To avoid Jellyfin transcoding 265 (8 bit) -> 264 for Safari 17.2 client (MacOS 14.2.1)...
> 
> I needed to:
> 
> * convert mkv to mp4 container, and
> * `ffmpeg -tag:v hvc1` the mp4 (it can't be "hev1" for Safari)
> * client side Jellyfin profile set "Prefer fMP4-HLS Media Container": **ON** (I think?)

The first two steps are unnecessary. As long as your Safari supports HEVC, after enabling the fMP4 container, Jellyfin will automatically add the code tag as hvc1 or dvh1 and stream it to the client through HLS.

If you want videos that have been converted to meet Safari requirements to be directly playable, [this PR](https://github.com/jellyfin/jellyfin-web/pull/5183) enables that.

---

> Thoughts on renaming "Prefer fMP4-HLS Media Container"
> 
> This is the current description:
> 
> > "Prefer fMP4-HLS Media Container"
> > Prefer to use fMP4 as the default container for HLS, making it possible to direct stream HEVC content on supported devices.
> 
> Maybe something along the lines of:
> 
> > "Prefer Streaming / DirectPlay"
> > Avoid transcoding video when simply repackaging container will allow play on your device. (Easier on Jellyfin server.)
> 
> I'm a complete noob re: video stuff, only learning about ffmpeg/Jellyfin this past week, but pretty comfortable in tech stuff generally and the amount of jargon / acronyms / competing standards in video stuff is mindboggling. Kudos & thanks to all the guys (brave souls) who contribute to making Jellyfin. It's a great project.

This is indeed a less user-friendly option as it contains technical abbreviations. Since we can't verify if all platforms support it, we've added this option to leave it up to users. But in the future we may enable it by default.

**Comment by strech345** [comment]
sorry i dont get it why on my m1 mac on chrome it transcode an hevc main (without 10). some other hevc videos works without transcoding.

```
Wiedergabe-Informationen
Player
Html Video Player
Abspielmethode
Transkodierung
Protokoll
http
Streamtyp
HLS
Videoinformationen
Playerabmessungen
3600x1900
Videoauflösung
1920x1080
Ausgelassene Frames
0
Fehlerhafte Frames
0
Transkodierungsinfo
Videocodec
AV1
Audiocodec
AAC
Audiokanäle
2
Bitrate
5.1 Mbps
Fortschritt der Transkodierung
0.2%
Bildrate der Transkodierung
8.7 fps (0.36x)
Grund für Transkodierung
Der Videocodec wird nicht unterstützt
Der Audiocodec wird nicht unterstützt
Der Untertitelcodec wird nicht unterstützt
Die Anzahl der Audiokanäle wird nicht unterstützt
Original Medium-Information
Container
webm
Größe
1012.5 MiB
Bitrate
3.1 Mbps
Videocodec
HEVC Main
Video-Bitrate
2.4 Mbps
Video-Dynamikumfang
SDR
Audiocodec
AAC HE-AAC
Audio-Bitrate
320 kbps
Audiokanäle
2
Audio-Abtastrate
48000 Hz
```
