### ISSUE TITLE
[Issue]: Deleting a library deletes all metadata for the files in it, even if the files are still present in other libraries

### ISSUE THREAD

**Issue by BratPfanneTV** [jellyfin/jellyfin#8497]
### Please describe your bug

Okay so I'm unsure if this could be intended or if it's actually a bug, but if it's intended I feel like it shouldn't be. I have several Movie libraries each containing hundreds of movies. Today I decided it'd be interesting to have a library containing all my movies, just to see the bulk of them in one place. So I created such a library containing the folders for all the other ones. Shortly thereafter I decided I didn't want this library after all, because it caused undesirable things that happen when a movie is present multiple times (Showing up multiple times in Continue Watching, showing up multiple times when viewing an actor etc). So I deleted the library, and suddenly I find the metadata for all my original libraries gone! Thousands of movies needed to be re-scraped and hundreds of manual corrections are gone! 

### Jellyfin Version

Other

### if other:

10.8.5

### Environment

```markdown
- OS: Debian
- Virtualization: Apt
- Clients: Web
- Browser: Microsoft Edge
- FFmpeg Version: jellyfin-ffmpeg5 5.5-1-focal
- Playback Method: Not applicable
- Hardware Acceleration: None
- Plugins: AudioDB, MusicBrainz, OMDb, Studio Images, TMDb
- Reverse Proxy: nginx
- Base URL: none
- Networking: -
- Storage: mounted cloud
```

### Jellyfin logs

```shell
[2022-10-06 00:02:16.926 +02:00] [INF] Removing item, Type: "CollectionFolder", Name: "All Movies", Path: "/var/lib/jellyfin/root/default/All Movies", Id: b303e108-a6d9-3411-f4ca-cbad0e81059e
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cvium** [comment]
Having the same folder/file in multiple libraries is not supported. I wouldn't consider this a bug even if the behaviour is extremely annoying.
