### ISSUE TITLE
Support S3

### ISSUE THREAD

**Issue by jaredallard** [jellyfin/jellyfin#850]
**Describe the feature you'd like**

Ability to load media (play, search, etc) files from S3 (or S3 compatible API, see minio for an example)

**Additional context**

I run a media server and one of the most expensive parts of cloud hosting it is storage, it'd be awesome if we could pull from S3 so then I save money and have it be distributed!

**Comment by EraYaN** [comment]
I feel this should be handled on the OS/File System level. We just ripped out SMB support, so I think it's unlikely other file system providers would be a good fit.

As for "fixes":
There is a FUSE driver for S3, Amazon does not recommend using it as a block device though, but it is possible, especially in readonly format to stop the amount of file transactions costing you a ton) https://github.com/s3fs-fuse/s3fs-fuse/wiki/Fuse-Over-Amazon (Works on Linux and macOS)

For Azure you can just mount Azure Files as SMB shares AND there is a FUSE implementation for Blob storage as well: https://github.com/Azure/azure-storage-fuse Official even, with a local cache.

**Comment by jaredallard** [comment]
@EraYaN Yeah, I can see this being a wontdo easily, but my problem w/ FUSE drivers is that they tend to be somewhat difficult to setup (in my case I'm using Kuberenetes to run Jellyfin, and setting up stuff like that is a hack to begin w/ and to maintain). So, if it's not terribly difficult to have done that would be awesome.

**Comment by mazzystr** [comment]
My dream is to get away from a POSIX filesystem for media also.  A few years ago I tried to put media files into a S3 bucket then used MountainDuck to present S3 bucket as a POSIX filesystem to feed Plex.  It didn't work well but the idea is still in the back of my mind.  

AWS is going to charge for network usage for S3 transfers.  That simply won't scale.

I think Linux and Ceph is the future for local storage.  The ceph fuse client is awesome, performant, and really shows some potential especially when we have all our apps containerized.

**Comment by jaredallard** [comment]
For now I am using gcsfuse, and have yet to have any issue. I think I will contribute back a doc that details how to run through this process with various drivers instead.

**Comment by MatthiasGrandl** [comment]
+1. S3 support would be a dream. Object storage is perfect for media playback. Would love to use Ceph S3 as a storage backend for Jellyfin.

**Comment by jaredallard** [comment]
@EraYaN is there any chance that we could reconsider this? As my use of GCS has scaled, gcsfuse, and other alternatives aren't functioning very well.

**Comment by EraYaN** [comment]
I don't think so, mostly since this will be maintenance hell. There are just too many storage options, this also requires even more (or better) support for virtual filesystems.

**Comment by HeroCC** [comment]
Just to add on to this, the feature suggestion said ffmpeg needs an actual file. The AWS API / CLI supports [presigned](https://docs.aws.amazon.com/AmazonS3/latest/userguide/ShareObjectPreSignedURL.html) urls. I'm not familiar with how the internals of Jellyfin work, but if plugins can add their own media to the server, one could search through the S3 bucket, and generate & pass along those presigned URLs as needed.
