### ISSUE TITLE
[Issue]: jellyfin does not yet understand SDH tag for external streams

### ISSUE THREAD

**Issue by systemcrash** [jellyfin/jellyfin#8506]
### Please describe your bug

SDH = Subtitles for the Deaf and Hard of Hearing

The server currently handles subs, and other tracks in a side-by-side manner. 
It recognizes, `default`, `forced`, but not `SDH` (upper or lower or any case)

https://jellyfin.org/docs/general/server/media/external-files.html

e.g.
```
a.mkv
a.default.en.srt
a.forced.ru.srt
a.en.dts
a.ru.ac3
...
```

It does not yet understand SDH. 

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
https://github.com/jellyfin/jellyfin/issues/4291
