### ISSUE TITLE
No sound when playing FLAC music files

### ISSUE THREAD

**Issue by Zenthae** [jellyfin/jellyfin#8525]
Hello,

When i play a music in the flac format, the music is playing (cursor moving and all) but there is no sound coming out.
On the same system, same file, with Kodi, it's working fine

**Media Info of the file**

Title: FLAC - Stereo
Codec: FLAC
Layout: stereo
Channels: 2 ch
Bitrate: 769 kbps
Sample rate: 44100 Hz
Bit depth: 16 bit
Default: No
Forced: No
External: No

**Logs**

**FFmpeg Logs**

**Stats for Nerds Screenshots**

**Server System (please complete the following information):**
 - OS: Docker on Linux
 - Jellyfin Version: 10.8.5
 - Hardware settings & device: Synology NAS
 - Reverse proxy: none
 - Other hardware notes: Local disk mounted in the container
 
**Client System (please complete the following information):**
 - Device: Freebox Mini
 - OS: Android
 - Client: Android
 - Client Version: 2.4.4

**Comment by Bond-009** [comment]
This needs some more info, can you give server logs?
