### ISSUE TITLE
[Issue]: Bad quality video in 10.9.0

### ISSUE THREAD

**Issue by brutric** [jellyfin/jellyfin#8535]
### Please describe your bug

The video quality in 10.9.0 compared to 10.8.5 is pixelated. I will get a screenshot comparison later. I'm not sure what has changed but there is definitely a difference.

### Jellyfin Version

Other

### if other:

10.9.0

### Environment

```markdown
- OS: Linux
- Virtualization: Docker
- Clients: Web
- Browser: Chrome
- FFmpeg Version:
- Playback Method: Chrome
- Hardware Acceleration: No
- Plugins: No
- Reverse Proxy: Local
- Base URL: Localhost
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Bond-009** [comment]
Can't do much without more info.
logs or "stats for nerds" i.e. playback info

**Comment by Bond-009** [comment]
Not enough info
