### ISSUE TITLE
[Issue]: People with same name are merged

### ISSUE THREAD

**Issue by SenorSmartyPants** [jellyfin/jellyfin#8539]
### Please describe your bug

Actor `Tom Holland` and Director `Tom Holland` are displayed with one person page and all the works combined. Actor was in my system first. Director information over wrote actor.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Please attach any screenshots here

![image](https://user-images.githubusercontent.com/991618/195181941-aa735563-3c6b-4d04-a0f5-5e36376b0bc6.png)

![image](https://user-images.githubusercontent.com/991618/195182294-3faa963f-e4f7-498c-a2e8-7d1837acfc47.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cvium** [comment]
There's already a pretty old issue about this. Nothing we can really do. A lot of providers only use strings for actors

**Comment by SenorSmartyPants** [comment]
Oh, I didn't find the old issue. 

If a provider does provide an ID (like IMDB and TMDB do) the metadata could be stored in the form of
Person/T/Tom Holland [TMDB-64796]
Person/T/Tom Holland [TMDB-1136406]

**Comment by crobibero** [comment]
https://github.com/jellyfin/jellyfin/issues/3356
