### ISSUE TITLE
[Issue]: [bug] running jellyfin server fails on "new Uri(localPath)" in BaseUrlRedirectionMiddleware.cs

### ISSUE THREAD

**Issue by Sky-High** [jellyfin/jellyfin#8550]
### Please describe your bug

Recently I git-cloned the jellyfin and jellyfin-web repository and ran 10.8.4 and 10.8.5 fine in Visual Studio on Windows 10.
A couple of days ago I performed a fresh git clone. With this 10.9.0 version, running jellyfin fails with the following message in the startup log:

	[09:46:48] [ERR] [3] Microsoft.AspNetCore.Server.Kestrel: Connection id "0HMLDN0VUJ3NA", Request id "0HMLDN0VUJ3NA:00000002":
	An unhandled exception was thrown by the application. System.UriFormatException: Invalid URI: The format of the URI could not be determined.
	...
	at Jellyfin.Server.Middleware.BaseUrlRedirectionMiddleware.Invoke(HttpContext httpContext, IServerConfigurationManager serverConfigurationManager) in
	C:\o\git\y\jellyfin\Jellyfin.Server\Middleware\BaseUrlRedirectionMiddleware.cs:line 68

Debugging into BaseUrlRedirectionMiddleware.cs reveals that the Invoke method at line 43 is called and assigns localPath="/", which indeed results in an error at line 68:
  var uri = new Uri(localPath);
as "/" is not an acceptable argument for Uri.

Now my question is: the last couple of weeks some commits have been performed on BaseUrlRedirectionMiddleware.cs, so should I assume that this file is currently Work-in-Progress and just wait until that is completed? Or am I doing something wrong?

Tags: backend, bug, regression

### Jellyfin Version

Other

### if other:

10.9.0

### Environment

```markdown
- OS: Windows 10
- Virtualization:
- Clients:
- Browser: Edge
- FFmpeg Version: 5.1.2-1
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shadowghost** [comment]
Seems like I missed this case when rewriting the logic in #8408. I'll take a look at it.

**Comment by Shadowghost** [comment]
What was the URI you encountered this error on?

**Comment by Sky-High** [comment]
I just performed "git clone https://github.com/jellyfin/jellyfin.git" and ran jellyfin from Visual Studio by hitting the F5 (after copying jellyfin-web/dist to jellyfin\Jellyfin.Server\bin\Debug\net6.0\jellyfin-web).
No changes in baseUrlPrefix.

Which means that jellyfin runs at http://localhost:8096. I am not exactly sure what BaseUrlRedirectionMiddleware.cs does, but apparently starting jellyfin this way ends up with localpath being set to "/". The "local" window in VisualStudio with a breakpoint at line 48 of BaseUrlRedirectionMiddleware it attached, if that helps.	

[debug.txt](https://github.com/jellyfin/jellyfin/files/9784932/debug.txt)

(With 10.8.5 localpath has the same value, by the way, but the method works fine as the code has no "new Uri(localpath)" )

**Comment by Sky-High** [comment]
> What was the URI you encountered this error on?
> 
> **Edit:** Can you check if [Shadowghost@1ee5795](https://github.com/Shadowghost/jellyfin/commit/1ee5795f9bd20793aa792fdb8301aba2225d4a91) fixes your problem?

This gives:
[12:29:13] [ERR] [3] Microsoft.AspNetCore.Server.Kestrel: Connection id "0HMLDPRO08KMB", Request id "0HMLDPRO08KMB:00000002": An unhandled exception was thrown by the application.
System.InvalidOperationException: This operation is not supported for a relative URI.
   at System.Uri.MakeRelativeUri(Uri uri)
   at Jellyfin.Server.Middleware.BaseUrlRedirectionMiddleware.Invoke(HttpContext httpContext, IServerConfigurationManager serverConfigurationManager) in C:\o\git\jellyfin90\Jellyfin.Server\Middleware\BaseUrlRedirectionMiddleware.cs:line 69
   at Microsoft.AspNetCore.Watch.BrowserRefresh.BrowserRefreshMiddleware.InvokeAsync(HttpContext context)

**Comment by Shadowghost** [comment]
Thanks for the infos, I can reproduce it now and will look into it further.
