### ISSUE TITLE
Problem Whit Api Create User

### ISSUE THREAD

**Issue by BexDevs** [jellyfin/jellyfin#8557]
Can you help me? I have BIG PROBLEM whit Jellyfin api

if i create a user via Jellyfin dashboard i see all the libraries and movies.  If I create movies via the meta API I can't find them anymore, why?

**Comment by neilsb** [comment]
Please see out [Contact Page](https://jellyfin.org/contact) for the best places to get help with this issue.  Our Matrix (Bridged t Discord) Troubleshooting or Development room would be best for this question.
