### ISSUE TITLE
Bug - Multiple versions of films are not merged anymore

### ISSUE THREAD

**Issue by ThomasPGH** [jellyfin/jellyfin#8568]
This does not work anymore with 10.8.5:

Multiple Versions of a Movie

Multiple versions of a movie can be stored together and presented as a single title. Place each movie version in the same folder and give each version a name with the folder name as a prefix as seen below.

Movies
└── Best_Movie_Ever (2019)
    ├── Best_Movie_Ever (2019) - 1080P.mp4
    ├── Best_Movie_Ever (2019) - 720P.mp4
    └── Best_Movie_Ever (2019) - Directors Cut.mp4

**Comment by ThomasPGH** [comment]
I should probably add that the bug only shows for newly added films or when trying to add new versions to an existing film. Multiple versions stored with previous versions of Jellyfin still work as they should.

**Comment by ThomasPGH** [comment]
It came back. I don't know why it doesn't work.

**Comment by ThomasPGH** [comment]
![image](https://user-images.githubusercontent.com/35429038/198903627-7ad49bec-02b4-47d4-a63c-d0fbbaab94f6.png)
![image](https://user-images.githubusercontent.com/35429038/198903632-b83fe57c-9dc7-4860-a8f1-e92f39e71466.png)

I checked and copied and pasted the title to ensure they're exactly the same up to the blank-dash-blank part. No idea what's differerent.

**Comment by cvium** [comment]
Folder name?

**Comment by ThomasPGH** [comment]
The Haunted House (1908) [imdbid-tt0449308]

**Comment by ThomasPGH** [comment]
Here we go. I omitted the imdbid and it works. It's the " [imdbid-tt0449308]" that prevents the files from being merged.

**Comment by cvium** [comment]
The folder name must be a substring of the filename. Glad you figured it out.

**Comment by ThomasPGH** [comment]
Shouldn't the "tip" then be removed, as it is obviously incorrect because it doesn't work with what's mentioned in the paragraph right afterwards?
https://jellyfin.org/docs/general/server/media/movies/
