### ISSUE TITLE
playback reporting plugin

### ISSUE THREAD

**Issue by bwaddington** [jellyfin/jellyfin#859]
**Describe the feature you'd like**

**Additional context**

**Comment by cvium** [comment]
What's that? Need a little more context

**Comment by bwaddington** [comment]
it was a plugin for emby, it let u see what is been, being watched and by who on the server

**Comment by bwaddington** [comment]
only thing i can find with a visual 
https://emby.media/community/index.php?/topic/57430-playback-reporting-plugin/?p=642486

**Comment by bwaddington** [comment]
seems to be working ok. need vs to build untill it can be add to jellyfin plugin page 

https://github.com/jellyfin/jellyfin-plugin-playbackreporting

**Comment by dkanada** [comment]
This plugin has been added so the issue can be closed.
