### ISSUE TITLE
Ipad OS fail to play hevec (x265) files on official client 

### ISSUE THREAD

**Issue by krishne35** [jellyfin/jellyfin#8599]
**Media Info of the file**
Video
Title: 1080p HEVC SDR
Codec: HEVC
Codec tag: hev1
Profile: Main 10
Level: 120
Resolution: 1920x804
Aspect ratio: 2.40:1
Interlaced: No
Framerate: 23.976025
Bitrate: 1999 kbps
Bit depth: 10 bit
Video range: SDR
Video range type: SDR
Pixel format: yuv420p10le
Ref frames: 1

**Logs**
[Logs](https://pastebin.com/S6V4S7WU)

**FFmpeg Logs**
[FFMPEG LOGS](https://pastebin.com/q5iGLu19)

**Stats for Nerds Screenshots**
>![IMG_0030.PNG](https://user-images.githubusercontent.com/35328770/197103520-f22ebf69-c887-4549-910a-7cacdce84321.PNG)
**Server System (please complete the following information):**
 - OS: DOCKER (LINUXSERVER)
 - Jellyfin Version: 10.8.5
 - Hardware settings & device: i7 8th gen 
 - Reverse proxy: nginx reverse proxy
 - Other hardware notes: media mounted via rclone_RD

 - Device: Ipad mini 4
 - OS: [IPAD OS 15.6.1]
 - Client: official app
 - Browser (if Web client): Firefox (same issue)
 - Client and Browser Version: 1.5.0 expo 43.0.0

**Comment by aihy** [comment]
me too, using ipad mini 4

**Comment by Shadowghost** [comment]
Is transcoding enabled for the user?
The source media is 10bit HEVC in SDR, this requires transcoding for most clients (including the iPad) because they only have 8bit displays.

**Comment by krishne35** [comment]
> Is transcoding enabled for the user?
> The source media is 10bit HEVC in SDR, this requires transcoding for most clients (including the iPad) because they only have 8bit displays.

Transcoding is fine but why doesn't it play tho

**Comment by aihy** [comment]
Maybe 5.1 channel aac is not supported by iPad Mini 4.

**Comment by aihy** [comment]
> Video formats supported: H.264 video up to 4K, 30 frames per second, High Profile level 4.2 with AAC‑LC audio up to 160 Kbps, 48kHz, stereo audio or Dolby Audio up to 1008 Kbps, 48kHz, stereo or multichannel audio, in .m4v, .mp4, and .mov file formats; MPEG‑4 video up to 2.5 Mbps, 640 by 480 pixels, 30 frames per second, Simple Profile with AAC‑LC audio up to 160 Kbps per channel, 48kHz, stereo audio or Dolby Audio up to 1008 Kbps, 48kHz, stereo or multichannel audio, in .m4v, .mp4, and .mov file formats; Motion JPEG (M‑JPEG) up to 35 Mbps, 1280 by 720 pixels, 30 frames per second, audio in ulaw, PCM stereo audio in .avi file format

[iPad mini 4 - Technical Specifications](https://support.apple.com/kb/SP725?viewlocale=en_US&locale=en_US)

**Comment by krishne35** [comment]
Did anyone find a workaround for this ?

**Comment by simonl169** [comment]
I'm having the same problem

**Comment by huangwb8** [comment]
I also have the same issue. Still without any solutions.

**Comment by huangwb8** [comment]
I use Jellyfin Version 10.8.8 (until 2023-01-18). This problem is still alive.
