### ISSUE TITLE
[Issue]: When the resolution is 4K，pgssub  Subtitle Positioning Incorrect

### ISSUE THREAD

**Issue by beelink387** [jellyfin/jellyfin#8602]
### Please describe your bug

meida info：<img width="739" alt="截屏2022-10-21 01 27 11" src="https://user-images.githubusercontent.com/23068026/197170812-95ba2bdf-f36c-4f92-af2b-bf96e26d229e.png">
<img width="500" alt="截屏2022-10-21 01 27 16" src="https://user-images.githubusercontent.com/23068026/197170827-04b2e59e-1999-4606-b901-29885d7683fa.png">

1080P-20M，PGSSUB display Positioning correct
<img width="1680" alt="截屏2022-10-21 01 10 27" src="https://user-images.githubusercontent.com/23068026/197170908-c9852c84-8ba9-4573-a08d-6b194cc89504.png">

1080-40M，PGSSUB Subtitle Positioning Incorrect （ps：Option display error, resolution is 4k）
<img width="1680" alt="截屏2022-10-21 01 09 48" src="https://user-images.githubusercontent.com/23068026/197170952-34900b9b-5ef8-4f5d-ba96-430b8d0b3804.png">

4K-80M，PGSSUB Subtitle Positioning Incorrect 
<img width="1680" alt="截屏2022-10-21 01 06 50" src="https://user-images.githubusercontent.com/23068026/197171012-5b00362b-f820-48f2-a242-4496edb46421.png">

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS:windows10
- Virtualization: none
- Clients:Browser / Android
- Browser:Chrome 106
- FFmpeg Version:jellyfin-ffmpeg_5.1.2-2-windows_win64
- Playback Method: Transcode
- Hardware Acceleration: NVENC
- Plugins: none
- Reverse Proxy: none
- Base URL: none
- Networking: Host
- Storage:smb
```

### Please attach any browser or client logs here

[log.zip](https://github.com/jellyfin/jellyfin/files/9837998/log.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sphaero** [comment]
I can confirm that subtitles position incorrect here as well in Firefox. Playing a transcoded DVD with embedded subtitles. 

jellyfin (10.8.7-1)

**Comment by nyanmisaka** [comment]
Can you post a video clip and the subtitle file to here?

**Comment by sphaero** [comment]
file upload is too big I'm afraid. Here's a screenshot

 
![subtitle](https://user-images.githubusercontent.com/832465/199217321-80a06f99-5093-4201-81dc-1bd7ae888f28.png)

**Comment by sphaero** [comment]
And media info:

```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '566c0c52d12a624ed55bdc12fd4b69960a594f19c80e5a31446f9100388914e0.m4v':
  Metadata:
    major_brand     : mp42
    minor_version   : 512
    compatible_brands: mp42iso2avc1mp41
    creation_time   : 2022-10-11T13:22:48.000000Z
    encoder         : HandBrake 1.5.1 2022011000
  Duration: 01:54:14.06, start: 0.000000, bitrate: 1079 kb/s
  Chapters:
    Chapter #0:0: start 0.000000, end 724.720000
      Metadata:
        title           : Chapter 1
    Chapter #0:1: start 724.720000, end 1299.120000
      Metadata:
        title           : Chapter 2
    Chapter #0:2: start 1299.120000, end 2004.120000
      Metadata:
        title           : Chapter 3
    Chapter #0:3: start 2004.120000, end 2625.800000
      Metadata:
        title           : Chapter 4
    Chapter #0:4: start 2625.800000, end 3318.080000
      Metadata:
        title           : Chapter 5
    Chapter #0:5: start 3318.080000, end 4326.080000
      Metadata:
        title           : Chapter 6
    Chapter #0:6: start 4326.080000, end 4838.760000
      Metadata:
        title           : Chapter 7
    Chapter #0:7: start 4838.760000, end 5496.040000
      Metadata:
        title           : Chapter 8
    Chapter #0:8: start 5496.040000, end 6148.200000
      Metadata:
        title           : Chapter 9
    Chapter #0:9: start 6148.200000, end 6852.968000
      Metadata:
        title           : Chapter 10
  Stream #0:0[0x1](und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, smpte170m/bt470bg/bt709, progressive), 720x426 [SAR 64:45 DAR 512:213], 735 kb/s, 25 fps, 25 tbr, 90k tbn (default)
    Metadata:
      creation_time   : 2022-10-11T13:22:48.000000Z
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 160 kb/s (default)
    Metadata:
      creation_time   : 2022-10-11T13:22:48.000000Z
      handler_name    : Stereo
      vendor_id       : [0][0][0][0]
  Stream #0:2[0x3](fra): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 160 kb/s
    Metadata:
      creation_time   : 2022-10-11T13:22:48.000000Z
      handler_name    : Stereo
      vendor_id       : [0][0][0][0]
  Stream #0:3[0x4](nld): Subtitle: dvd_subtitle (mp4s / 0x7334706D), 720x576, 3 kb/s (default)
    Metadata:
      creation_time   : 2022-10-11T13:22:48.000000Z
      handler_name    : SubtitleHandler
  Stream #0:4[0x5](nld): Subtitle: dvd_subtitle (mp4s / 0x7334706D), 720x576, 3 kb/s
    Metadata:
      creation_time   : 2022-10-11T13:22:48.000000Z
      handler_name    : SubtitleHandler
  Stream #0:5[0x6](fra): Subtitle: dvd_subtitle (mp4s / 0x7334706D), 720x576, 3 kb/s
    Metadata:
      creation_time   : 2022-10-11T13:22:48.000000Z
      handler_name    : SubtitleHandler
  Stream #0:6[0x7](fra): Subtitle: dvd_subtitle (mp4s / 0x7334706D), 720x576, 3 kb/s
    Metadata:
      creation_time   : 2022-10-11T13:22:48.000000Z
      handler_name    : SubtitleHandler
  Stream #0:7[0x8](fra): Subtitle: dvd_subtitle (mp4s / 0x7334706D), 720x576, 0 kb/s
    Metadata:
      creation_time   : 2022-10-11T13:22:48.000000Z
      handler_name    : SubtitleHandler
  Stream #0:8[0x9](fra): Subtitle: dvd_subtitle (mp4s / 0x7334706D), 720x576, 0 kb/s
    Metadata:
      creation_time   : 2022-10-11T13:22:48.000000Z
      handler_name    : SubtitleHandler
  Stream #0:9[0xa](eng): Data: bin_data (text / 0x74786574)
    Metadata:
      creation_time   : 2022-10-11T13:22:48.000000Z
      handler_name    : SubtitleHandler
```

**Comment by nyanmisaka** [comment]
> file upload is too big I'm afraid. Here's a screenshot

Use ffmpeg to cut a 10 min clip.

`ffmpeg -i video.mkv -an -c:v copy -c:s copy -t 600 -strict -2 -y clip.mkv`

**Comment by sphaero** [comment]
Used this cmd to also copy subtitles and audio. There's at least a subtitle event at 7:00

`ffmpeg -i 566c0c52d12a624ed55bdc12fd4b69960a594f19c80e5a31446f9100388914e0.m4v -c:a copy -c:v copy -c:s copy -t 600 -strict -2 -y clip.mkv`

https://pong.hku.nl/~arnaud/clip.mkv

**Comment by beelink387** [comment]
Please modify the file name。file list:
1)clip.mkv 2.zip.001
2)clip.mkv 2.zip.002
3)clip.mkv 2.zip.003

ffmpeg -ss 00:10:10 -i video.mkv -an -c:v copy -c:s copy -t 2 -strict -10 -y clip.mkv

[clip.mkv 2.zip.001.zip](https://github.com/jellyfin/jellyfin/files/9909393/clip.mkv.2.zip.001.zip)
[clip.mkv 2.zip.002.zip](https://github.com/jellyfin/jellyfin/files/9909395/clip.mkv.2.zip.002.zip)
[clip.mkv 2.zip.003.zip](https://github.com/jellyfin/jellyfin/files/9909397/clip.mkv.2.zip.003.zip)

**Comment by sphaero** [comment]
Sorry I don't understand what you want me to do? Do I need to cut the file again?

**Comment by beelink387** [comment]
> Sorry I don't understand what you want me to do? Do I need to cut the file again?

I reply to  @nyanmisaka ：）
