### ISSUE TITLE
什么时候可以加入跳过片头功能

### ISSUE THREAD

**Issue by cnfjice** [jellyfin/jellyfin#8605]
羡慕emby的跳过片头功能，jellyfin尝试了Infuse Sync插件，无法使用。。。希望作者可以考虑一下。。。万分感谢。

**Comment by nyanmisaka** [comment]
Don't envy it, we also have **intro-skipper**. I've been using it for months and it works great!

https://github.com/ConfusedPolarBear/intro-skipper

**Comment by cnfjice** [comment]
> 

Thanks, this is a very nice plugin.

**Comment by Joackk** [comment]
> > Envy of emby's function of skipping titles, jellyfin tried the Infuse Sync plug-in and couldn't use it. . . I hope the author can think about it. . . Many thanks.
> 
> Don't envy it, we also have **intro-skipper**. I've been using it for months and it works great!
> 
> https://github.com/ConfusedPolarBear/intro-skipper

This plugin seems to be no longer supported in the new version, and he has been archived. I got the hint in the 10.9.7 release: NotSupported

**Comment by refined-fish** [comment]
> > > 羡慕 emby 的跳过标题功能，jellyfin 尝试了 Infuse Sync 插件，但无法使用。。。我希望作者能好好想想。。。非常感谢。
> > 
> > 
> > 不要羡慕它，我们还有 **intro-skipper**。我已经使用它几个月了，效果很好！
> > https://github.com/ConfusedPolarBear/intro-skipper
> 
> 这个插件似乎在新版本中不再支持，他已经被存档了。我在 10.9.7 版本中得到了提示：NotSupported

已经有一个新的在维护版本了，这是地址
https://github.com/jumoog/intro-skipper

**Comment by Joackk** [comment]
@refined-fish 感谢，太好了
