### ISSUE TITLE
Connecting to yatse doesn't work

### ISSUE THREAD

**Issue by nickcorona** [jellyfin/jellyfin#861]
**Describe the bug**
My IP address and port are 192.168.1.2, and 8096, respectively. I enter this into the Yatse, and it returns the following error:
"Unable to get Kodi version:
Check the port value and that this port is not used by another software on the host..."

**Comment by EraYaN** [comment]
Jellyfin should not report the Kodi version. Are you sure you are entering in the correct details in the correct place?

**Comment by fruhnow** [comment]
i am experiencing the same behavior with a current emby server and latest yatse from the play store

**Comment by EraYaN** [comment]
This might be an upstream problem.

**Comment by JustAMan** [comment]
cc @tolriq

**Comment by Tolriq** [comment]
You need to select add Emby host :) (Should probably rename that one to indicate also JellyFin)

Only when you try to add a Kodi server can show a message about getting Kodi version :)
