### ISSUE TITLE
[Issue]: Specific Library empty

### ISSUE THREAD

**Issue by DuvelCorp** [jellyfin/jellyfin#8613]
### Please describe your bug

Long-time user. Perfectly working installation serving 10000 movies and shows to 20 users on LAN and WAN

Issue : I've got only one of my libraries that isn't showing any item.

![image](https://user-images.githubusercontent.com/33682764/197388116-f3b3e70c-6e2d-45be-9864-b6d5fba99624.png)

Important note : this library is mostly as old as all the others, and was perfectly working for > 1 year.
Since I am helping the Jellyseer dev to test its software, I have make a change to that library. Previously its name contained accented chars, it was named "DA - Télé". To debug some issues with Jellyseer I have been asked to rename it with no special chars. I have done this on other libraries and had no issues. Only this one is broken.

Data folder is on the same storage area than all the rest, and the owner/permissions on the folder and subfolder are exactly the same too.

For most of the shows (only anime), the folder and files organization do respect Jellyfin guidelines. Example:
![image](https://user-images.githubusercontent.com/33682764/197391414-373cde3b-3c21-418f-8d5c-a3d33f731705.png)

I can see all items of the folder in the "metadata"  menu : 

![image](https://user-images.githubusercontent.com/33682764/197388287-23bb99d3-61e2-44b1-b779-10ae30cca65a.png)

Perfectly match:

![image](https://user-images.githubusercontent.com/33682764/197388322-29d6c94f-a1ed-4028-b0db-f730c4591a24.png)

But the library only shows a unique and empty TV show :

![image](https://user-images.githubusercontent.com/33682764/197388387-bd55a905-0c93-4408-8a98-b70382116276.png)

Got a fair experience in server administration and with Jellyfin and I have spent one hour on the issue on everything I could think about, and I have zero explanation so far.

Things I tried : 
* Starting all possible sync, multiple times
* Scrutinizing all the logs. I see NOTHING about this library being scanned, and not a single line on any of its contain. No errors whatsoever. Only this line is present multiple times [2022-10-23 12:14:49.446 +02:00] [INF] Watching directory "/media/plex/da/tele" 
* Upgrade Jellyfin from 10.8.4 to 10.8.5.1, and restarting it
* Checking if the permissions on the folder and subfolders are correct, and they are.
* Deleting the library and recreating it, with different names.
* Inspecting all lib parameters, again and again. 

Additionally I inspected the library.db with SQLite Browser, and I  find some references of the missing contain in it: 
![image](https://user-images.githubusercontent.com/33682764/197391035-d28bad4f-3ab1-4451-9653-77701eca1cac.png)

At that point I dont know what to think anymore. The most frustrating is that there's just ZERO information about a potential issue in the logs.

I have read another similar issue here https://github.com/jellyfin/jellyfin/issues/8518
I have basically the same problem, however my environment is completely different and the solution proposed is not applicable to me, ie disabling IPV6. Its already disabled.

### Jellyfin Version

10.8.5.1

### Environment

```markdown
- OS: Ubuntu Server 22.04 LTS
- Virtualization: Vmware ESXi 6
- Clients:- Browser: Android, Firefox, Chrome, Safari, Edge, PS4
- FFmpeg Version: ?
- Playback Method: All
- Hardware Acceleration: none
- Plugins: A lot
- Reverse Proxy: Apache
- Base URL: N/A
- Networking: Host/LAN
- Storage: NFS
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cvium** [comment]
Can you enable debug logs and then do a Force Refresh on the DA - Tele library? Then post the logs.
