### ISSUE TITLE
H264 High 10 gets transcoded into 8 bit

### ISSUE THREAD

**Issue by Eniff** [jellyfin/jellyfin#8615]
### Please describe your bug

I have a H264 High 10 bit video file that I want to trancode to my LG WebOS TV equipped with the official WebOS content store app. I have a nvidia Turing GPU with support for 10 bit HEVC encoding but jellyfin still encodes with 8 bit color format.

I want jellyfin to transcode H264 10bit into HEVC 10bit.

### Jellyfin Version

Other

### if other:

10.8.1

### Environment

```markdown
- OS: Windows 10
- Virtualization: -
- Clients: LG WebOS 6.0 TV
- Browser:
- FFmpeg Version:
- Playback Method: Official WebOS app
- Hardware Acceleration: Turing NVENC
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### FFmpeg logs

```shell
Input #0, matroska,webm, from '*':
  Metadata:
    creation_time   : 2021-09-26T17:15:12.000000Z
    ENCODER         : Lavf58.42.101
  Duration: 00:24:14.09, start: 0.000000, bitrate: 13300 kb/s
  Stream #0:0: Video: h264 (High 10), yuv420p10le(progressive), 1920x1080, SAR 1:1 DAR 16:9, 23.98 fps, 23.98 tbr, 1k tbn (default)

Output #0, hls, to '*':
  Metadata:
    encoder         : Lavf59.16.100
  Stream #0:0: Video: hevc (Main) (hvc1 / 0x31637668), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 7980 kb/s, 23.98 fps, 24k tbn (default)
    Metadata:
      encoder         : Lavc59.18.100 hevc_nvenc
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by nyanmisaka** [comment]
This is not an issue, currently we only transcode to 8bit SDR.

**Comment by Eniff** [comment]
I understand. Is there no plan to include an option to transcode into 10bit? I see on my TV that the colors suffer a bit from the re-transformation even though the source was 8 bit originally.

_Off topic question: Is there any way to set CQP (Constant Quantization Parameters) or CBR (Constant Bit Rate) for NVENC encoder?_
