### ISSUE TITLE
[Issue]: Can't automatically merge series that are spread across muiltple folders

### ISSUE THREAD

**Issue by dnpl** [jellyfin/jellyfin#8616]
### Please describe your bug

I download different series from different websites, but they can't merge series that are spread across muiltple folders. for exmaple, 那山那海.Na.Shan.Na.Hai.2022.1080p.WEB-DL.H264.AAC, 那山那海.Na.Shan.Na.Hai.2022.2160p.WEB-DL.H265.AAC,山哈闹海.Na.Shan.Na.Hai.2022.2160p.WEB-DL.H265.AAC,那山那海.Na.Shan.Na.Hai.2022.1080p.WEB-DL.H264.AAC. This show spread in four folders, and jellyfin display four series with same name（as shown in pictures）(automatically merge series that are spread across muiltple folders was enabled).

### Jellyfin Version

10.8.5

### Environment

```markdown
- OS: docker on openwrt
- Virtualization: no
- Clients: Andriod, iPhone
- Browser: Chrome
- FFmpeg Version:none
- Playback Method:none 
- Hardware Acceleration:latest 
- Plugins: TMDB
- Reverse Proxy:none
- Base URL:default
- Networking: simple lan
- Storage: hdd
```

### Jellyfin logs

```shell
there was no log
```

### FFmpeg logs

```shell
there was no log
```

### Please attach any browser or client logs here

there was no log

### Please attach any screenshots here

![image](https://user-images.githubusercontent.com/22452022/197538384-3d109b86-496b-4b7e-8bce-a3a7fa415147.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aaruni96** [comment]
I am affected by the same bug.

I have the following folder structure :

`device1/tv/tv-show(yyyy)/season 01` and `device2/tv/tv-show(yyyy)/season 02`

This shows up in the interface as tv-show with only season 1, and another copy of tv-show with only season 2.

**Comment by aaruni96** [comment]
This bug still affects me on Jellyfin 10.8.10

**Comment by aaruni96** [comment]
This issue still affects me.

**Comment by srcrist** [comment]
Closing this issue as it does not reference an actual Jellyfin bug. Metadata matching requires following the naming and organization conventions documented here: https://jellyfin.org/docs/general/server/media/shows/. Please visit our support communities on the forum or at our Matrix/Discord server if you need help, and people will gladly assist you with configuring your metadata providers to match media correctly.
