### ISSUE TITLE
"Next up" not showing all/most shows

### ISSUE THREAD

**Issue by fwmm01** [jellyfin/jellyfin#8619]
os: debian bullseye
hardware: RockPro64 v2.1

The next up section has just stopped displaying the next episode for most of my shows I am watching. Only recently happened. I recently updated the server, but nothing seemed to have broke immediately after.

I have refreshed metadata and re-scanned the library. No change.

Any ideas what has caused this?

**Comment by cvium** [comment]
Duplicate of #8477
