### ISSUE TITLE
[Issue]: Skia library not available on Qnap QTS 5.0.1

### ISSUE THREAD

**Issue by gummykage** [jellyfin/jellyfin#8639]
### Please describe your bug

![2](https://user-images.githubusercontent.com/9695713/198444877-17db9670-cc07-44d6-b24e-5dd6c5f050a1.jpg)

Installs of jellyfin through qpkg files work perfectly and hardware acceleration also works perfectly. The problem is because this library isn't loaded, Constant errors appear in the logs about aspect ratios not being able to be calculated and other anomalies such as actor thumbnails won't load until you click on them and the main library buttons never generate a random image from the collage function.

![image](https://user-images.githubusercontent.com/9695713/198451354-0a385334-f190-404c-8b96-f7de6e291eba.png)

### Jellyfin Version

Other

### if other:

10.9.0-unstable

### Environment

```markdown
- OS:Unbuntu/Qnap QTS 5.0.1-latest
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version: 5.1.1
- Playback Method:
- Hardware Acceleration: VAAPI
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
We dont provide the Qnap package so you'll have to ask that maintainer. It's likely just a missing build flag.

**Comment by gummykage** [comment]
I totally hear ya, I'm just trying to figure out what flag it might need for example to build it myself. For Qnap all I do is extract the deb files for ubuntu and drop them in a directory with the right permissions and it fires right up. (Using official builds)... Is skia dependent on something on ubuntu itself? Reason I ask Qnap runs a stripped down version of it. If I use LinuxStation and install a fresh ubuntu in a VM it runs perfectly but because of limitations of the device it won't pass the hardware accelerated encoding to the container...
