### ISSUE TITLE
[Issue]: Building from Source on non-Debian Based Linux not Working

### ISSUE THREAD

**Issue by nezartarbin** [jellyfin/jellyfin#8652]
### Please describe your bug

Building from source on non-Debian based Linux does not work, giving the misleading misleading:

```
Cross-building is not supported for native builds, use 'docker' builds on amd64 for cross-building.
```

### Diagnosis
After digging through, this seems to be due to the fact that [./build.sh](https://github.com/jellyfin/jellyfin/blob/master/build.sh) has a hard dependency on dpkg, as shown on [line 37](https://github.com/jellyfin/jellyfin/blob/master/build.sh) and [line 46](https://github.com/jellyfin/jellyfin/blob/master/build.sh). This script seems to get called even for the non-Debian "general linux" build.

### Steps to reproduce:
- using Arch Linux or Alpine Linux as base OS
- clone repo
- run `./build --type native --platform linux-arm64` for arm64 machines, or `./build --type native --platform linux-amd64` on x86 machines.
- you will receive the error mentioned above

### Proposed Solution

If given green light, I can contribute to fixing this. I was thinking of using `ldd --version` and parse the output to check architecture and libc instead of `dpkg`, as it is a general linux utility found on most distributions as far as I know. But in case the team has other suggestions on how to fix, I would be happy to help with that too.

### Jellyfin Version

Other

### if other:

10.8.5 and latest in git

### Environment

```markdown
- OS: Arch Linux and Alpine Linux (tried both)
- Virtualization: Native and podman container (tried both)
- Clients: jellyfin
- Browser:
- FFmpeg Version: 5.1.2
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
Cross-building is not supported for native builds, use 'docker' builds on amd64 for cross-building.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nielsvanvelzen** [comment]
You don't need the build.sh script. Just use `dotnet build`. AFAIK the build.sh script is only used in CI.

**Comment by nezartarbin** [comment]
Thanks for the response @nielsvanvelzen ! The `build.sh` script is used in the `./build` file, and the [Build from Source instructions on the website](https://jellyfin.org/docs/general/administration/building) reference using `./build` to build jellyfin from source. If this is to be left as is, I would suggest updating the "Build from Source" instructions to use the `dotnet build` command. What do you think?

**Comment by nezartarbin** [comment]
sorry, I just realized this is all in the ./build file as well, and that `build.sh` does not matter here. `build` has the same issue though, I just referenced the wrong file. Will edit the issue with the new details and links

**Comment by nielsvanvelzen** [comment]
Good point. Looks like the README in this repository is updated but the docs are really outdated.
