### ISSUE TITLE
[Issue]: PR Broke Next Up

### ISSUE THREAD

**Issue by lancerocke** [jellyfin/jellyfin#8655]
### Please describe your bug

This pr https://github.com/jellyfin/jellyfin/pull/8501 broke next up for me. 
When i use 10.9.0 it's fine and i can see season 2 episode 1 of peter grill and the philosopher's time as next up 
but when i'm on 10.8.5 or 10.8.6 i don't see season 2 episode 1 and next. if i set season 2 episode 1 as watched season 2 episode 2 will show up as next up

### Jellyfin Version

Other

### if other:

10.8.5

### Environment

```markdown
- OS: Ubuntu
- Virtualization: Docker
- Clients: Browser 
- Browser: Chrome
- Playback Method: Browser
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cvium** [comment]
This PR wasn't in 10.8.5. I'm also gonna need a lot more info about your setup and playstates. It'll be easiest if you just send me your library.db file

**Comment by cvium** [comment]
> > This PR wasn't in 10.8.5. I'm also gonna need a lot more info about your setup and playstates. It'll be easiest if you just send me your library.db file
> 
> [redacted]

Thank you. I have downloaded it and removed the link (there shouldn't be any sensitive data in it, but better safe than sorry).

Which series are exhibiting the issue?

**Comment by innologi** [comment]
I'm having a slight variation of this issue in 10.8.6 that might offer some insight into the cause of both problems.

https://github.com/jellyfin/jellyfin/pull/8501/commits/373c63bcc7078a7f2e4d68fb9032b2af7cb804fc#diff-499c6648deb50426423a38662b1985416ce586ff0c0101fee00127d06966e3abR227

`lastWatchedEpisode` may be populated with a previous season episode.

Example (any TV show):
- I finish watching S01E10 (final episode of S01)
- S02E10 (final episode of S02) will be in Next Up
- I finish watching S02E01
- Next Up will adjust by showing S02E02.

**Comment by jayache80** [comment]
I installed 10.8.7 and Next Up is still buggy for me.

Example:
I have unwatched episodes 2022-10-31, 2022-11-01, 2022-11-02

Expected:
Episode 2022-10-31 is Next Up

Actual:
Episode 2022-11-01 is Next Up

**Comment by jayache80** [comment]
@GBMiro I just pulled down 10.8.8 and this issue is still present.

It can be random and non-deterministic.

For example, I have two unwatched episodes:
2022-12-07
2022-12-08

And right now it is currently showing 2022-12-07 as Next Up, which is expected. But if I go mark an older episode as unwatched, say:
2022-11-29

Then I would expect 2022-11-29 to be Next Up, but it is not. 2022-12-07 is still next up. If I mark 2022-12-07 and 2022-12-08 as watched, only then does 2022-11-29 appear as Next Up.

**Comment by GBMiro** [comment]
I'm also on 10.8.8.
I've tried to reproduce your steps but I cannot get the same result. My Next Up is always being calculated from the newest episode aired that is marked as watched. If this episode is the last one, even though I have older episodes as unwatched, they are not shown,

I've manually checked episodes in this show so the issue can be perfectly seen:
![Git](https://user-images.githubusercontent.com/15947095/206854669-8369b484-f237-47e0-8277-d9fcc5f017f1.jpg)
First images show episodes 1, 2, 11 as watched (rest is unwatched: 3,4, 5...), and the Next Up is episode 12 when it should be 3.
If I mark episode 12 as watched (bottom images), I would also  expect episode 3 to show in Next Up but it does not.

**Comment by GBMiro** [comment]
I'm also on 10.8.8.
I've tried to reproduce your steps but I cannot get the same result. My Next Up is always being calculated from the newest episode aired that is marked as watched. If this episode is the last one, even though I have older episodes as unwatched, they are not shown,
