### ISSUE TITLE
[Issue]: H.265 10-bit in MKV containers don't direct stream to MP4 containers when supported (on Chrome v107).

### ISSUE THREAD

**Issue by maru801** [jellyfin/jellyfin#8656]
### Please describe your bug

Since Chrome 107 now supports HEVC 10-bit video content through gpu acceleration only, this type of content can be direct played on any chromium-based browser on v107 provided that it's in a MP4 container.

If you have a HEVC 10-bit video in a MKV container, Jellyfin fails to direct stream where it just converts the container to a MP4 container, and transcodes the content into H.264 instead.

Also, the playback info reports the original media container as webm containers instead of MKV. It seems to me like this is another issue.

H.265 10-bit in a MP4 container playback Info:
![MP4](https://user-images.githubusercontent.com/80718617/198859426-c626efec-f087-4316-84ed-18444c0ceeab.jpg)

H.265 10-bit in a MKV container playback info:
![MKV](https://user-images.githubusercontent.com/80718617/198859451-ea54a914-fa7d-4351-b670-4cecbdeeb405.jpg)

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Linux
- Virtualization: Docker
- Clients: Browser
- Browser: Chrome
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration: VAAPI
- Plugins:
- Reverse Proxy: None
- Base URL: None
- Networking: Host
- Storage: Local
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BJET67** [comment]
I'm having the same issue

**Comment by nyanmisaka** [comment]
MKV is not supported by Chrome.
