### ISSUE TITLE
[Issue]: Ubuntu 20.04 cant install Jellyfin

### ISSUE THREAD

**Issue by Karmylr** [jellyfin/jellyfin#8671]
logs:
root@ubuntu:~# apt install jellyfin
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 jellyfin : Depends: jellyfin-ffmpeg5 (>= 5.0.0) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
root@ubuntu:~#

**Comment by nyanmisaka** [comment]
The `jellyfin` metapackage is deprecated in the unstable branch.
Please use `apt install jellyfin-server jellyfin-web jellyfin-ffmpeg5` instead.

**Comment by Karmylr** [comment]
> 

thanks for reply! but still cant install. here is the logs:
The following packages have unmet dependencies:
 jellyfin-ffmpeg5 : Depends: libvpx5 (>= 1.6.0) but it is not installable
                    Depends: libx264-152 but it is not installable
                    Depends: libx265-146 (>= 2.6) but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by Karmylr** [comment]
> The `jellyfin` metapackage is deprecated in the unstable branch. Please use `apt install jellyfin-server jellyfin-web jellyfin-ffmpeg5` instead.

thanks for reply! but still cant install. here is the logs:
The following packages have unmet dependencies:
jellyfin-ffmpeg5 : Depends: libvpx5 (>= 1.6.0) but it is not installable
Depends: libx264-152 but it is not installable
Depends: libx265-146 (>= 2.6) but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by nyanmisaka** [comment]
Have you added the correct repo "focal" aka 20.04 to the apt sources?

If so, please make an upgrade before installing new packages.

**Comment by Karmylr** [comment]
> Have you added the correct repo "focal" aka 20.04 to the apt sources?
> 
> If so, please make an upgrade before installing new packages.

after apt update && apt upgrade, still show these logs:
![image](https://user-images.githubusercontent.com/69903376/199241327-7570b941-4b64-41fa-8fc6-f60aa139d8ad.png)

**Comment by nyanmisaka** [comment]
Purge the old jellyfin and jellyfin-ffmpeg packages.

```
sudo apt purge jellyfin jellyfin-ffmpeg
sudo apt install jellyfin-ffmpeg5 jellyfin-server jellyfin-web
```

```
root@ubuntu-vm:~$ apt show jellyfin-ffmpeg5
Package: jellyfin-ffmpeg5
Version: 5.1.2-4-focal
Priority: optional
Section: video
Source: jellyfin-ffmpeg (5.1.2-4)
Maintainer: Jellyfin Packaging Team <packaging@jellyfin.org>
Installed-Size: 226 MB
Depends: libass9 (>= 1:0.13.6), libbluray2 (>= 1:0.2.2), libc6 (>= 2.29), libelf1 (>= 0.142), libexpat1 (>= 2.0.1), libfontconfig1 (>= 2.12.6), libfreetype6 (>= 2.2.1), libfribidi0 (>= 0.19.2), libgcc-s1 (>= 3.4), libgmp10, libgnutls30 (>= 3.6.12), libllvm12 (>= 1:9~svn298832-1~), libmp3lame0 (>= 3.100), libopus0 (>= 1.1), libpciaccess0, libstdc++6 (>= 9), libtheora0 (>= 1.0), libudev1 (>= 183), libvorbis0a (>= 1.1.2), libvorbisenc2 (>= 1.1.2), libvpx6 (>= 1.6.0), libwebp6 (>= 0.5.1), libwebpmux3 (>= 0.6.1-2ubuntu0.20.04.1), libx11-xcb1 (>= 2:1.6.9), libx264-155, libx265-179 (>= 3.2), libxcb-dri2-0 (>= 1.8), libxcb-dri3-0 (>= 1.13), libxcb-present0, libxcb-randr0 (>= 1.13), libxcb-shm0, libxcb-sync1, libxcb-xfixes0, libxcb1 (>= 1.9.2), libxshmfence1, libzstd1 (>= 1.3.2), libzvbi0 (>= 0.2.35), ocl-icd-libopencl1 | libopencl1, ocl-icd-libopencl1 (>= 1.0) | libopencl-1.1-1, ocl-icd-libopencl1 (>= 1.0) | libopencl-1.2-1, zlib1g (>= 1:1.2.0.2)
Conflicts: jellyfin-ffmpeg
Replaces: jellyfin-ffmpeg
```

**Comment by nyanmisaka** [comment]
Also the libvpx5 doesn't exist on Ubuntu 20.04.
https://packages.ubuntu.com/search?suite=focal&arch=any&searchon=names&keywords=libvpx

You can use `cat /etc/apt/sources.list.d/jellyfin.list` and `lsb_release -a` to check if you are on Ubuntu focal 20.04.

**Comment by Karmylr** [comment]
I've change into Debian 11.
![image](https://user-images.githubusercontent.com/69903376/199246137-89344b7f-dc39-413e-bb95-7049815c426c.png)

**Comment by nyanmisaka** [comment]
`ubuntu bionic main` is Ubuntu 18.04. It cannot be installed on either 20.04 or Debian 11.

You have to change bionic to focal or bullseye.

**Comment by Karmylr** [comment]
I think im on bullseye

**Comment by Karmylr** [comment]
> 

how

**Comment by nyanmisaka** [comment]
Yes you are on bullseye. But your jellyfin sources is installed as Ubuntu 18.04 bionic:
/etc/apt/sources.list.d/jellyfin.list

**Comment by Karmylr** [comment]
Im on bullseye now. these logs appear:
![image](https://user-images.githubusercontent.com/69903376/199247953-e8ec4ad5-f395-45ec-8c41-2fa26047f8fa.png)

**Comment by nyanmisaka** [comment]
Change ubuntu to debian...

**Comment by Karmylr** [comment]
Yeah, i said that in "https://github.com/jellyfin/jellyfin/issues/8671#issuecomment-1298520141"

**Comment by Karmylr** [comment]
> Change ubuntu to debian...

Thx, solved now.
