### ISSUE TITLE
[Issue]: LiveTV EnsureFileUnique Causing High CPU usage

### ISSUE THREAD

**Issue by jedthe3rd** [jellyfin/jellyfin#8676]
### Please describe your bug

There seems to be an issue with LiveTV recording that causes a thread leak leading to constant CPU usage (~30%) even when no recordings are occurring.

I have narrowed it down to this function call: https://github.com/jellyfin/jellyfin/blob/99e31846bf38c066fa6817f289757b9202a56e04/Emby.Server.Implementations/LiveTv/EmbyTV/EmbyTV.cs#L1278

I ran Visual Studio performance profiler on jellyfin and I was able to find what it was spending all the CPU cycles on.
I attached screenshots of the results.

Looks like this was also an issue in Emby: https://emby.media/community/index.php?/topic/75454-100-cpu-usage/

### Jellyfin Version

10.8.0

### if other:

10.8.6

### Environment

```markdown
- OS: Windows 10
- Virtualization: N/A
- Clients: N/A
- Browser: N/A
- FFmpeg Version: 5.1.2-1
- Playback Method: N/A
- Hardware Acceleration: Yes
- Plugins: 
AniDB7.0.0.0
AniList5.0.0.0
AudioDB10.8.6.0
Bookshelf9.0.0.0
Cover Art Archive7.0.0.0
IMVDb3.0.0.0
InfuseSync1.4.2.0
Kitsu4.0.0.0
MusicBrainz10.8.6.0
OMDb10.8.6.0
Playback Reporting13.0.0.0
Reports15.0.0.0
Studio Images10.8.6.0
TMDb10.8.6.0
TMDb Box Sets10.0.0.0
TVmaze10.0.0.0
TheTVDB8.0.0.0
VGMdb2.0.0.0
- Reverse Proxy: N/A
- Base URL: N/A
- Networking: 10GbE to NAS and 1GbE to LAN
- Storage: TrueNAS SMB3 NAS over 10GbE
```

### Jellyfin logs

```shell
No relevant log output.
```

### FFmpeg logs

```shell
No relevant log output.
```

### Please attach any screenshots here

![image](https://user-images.githubusercontent.com/7817335/199325650-2fdf373c-5659-4539-aa89-630de1e563f3.png)
![image](https://user-images.githubusercontent.com/7817335/199325745-bfbe5fe6-a941-4798-bb2b-c7420747e184.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cvium** [comment]
As mentioned on Matrix, I need to see your seriestimers.json and timers.json files.

**Comment by jedthe3rd** [comment]
[seriestimers.json](https://gist.github.com/jedthe3rd/6b8bee2be35756d8003c58c3cbd8d5a6)
[timers.json](https://gist.github.com/jedthe3rd/fc33b1fa41c1b5274d65e87f1166c628)

I redacted some stuff to keep things professional. Anything redacted is replaced with <redacted>.

**Comment by cvium** [comment]
When does the CPU usage occur? And do you have any idea of what it is it's trying to record?

**Comment by jedthe3rd** [comment]
> When does the CPU usage occur? And do you have any idea of what it is it's trying to record?

That's the weird thing. I think the usage is triggered by recordings starting as it isn't there when I restart my jellyfin instance but after a bit and a few recordings triggering it starts consuming large amounts of CPU even if no one is watching anything. If I then turn off all recordings it doesn't stop trying to ensure file is unique. Can I backup the *timers.json files and delete them to test removing all schedules and see if the CPU usage stops with all schedules deleted?

**Comment by cvium** [comment]
I can't be sure, but I think it should be relatively safe. I recommend taking a full backup though :)

**Comment by jedthe3rd** [comment]
Ok, I will try it out when I get a chance this week. That will at least help us narrow it down to what part of the code is getting stuck. Either recording timers triggering or scheduled timers being set.
