### ISSUE TITLE
[Issue]: Shows wrong album cover when file includes multiple images

### ISSUE THREAD

**Issue by dbolton** [jellyfin/jellyfin#8682]
### Please describe your bug

I have FLAC music files with a "cover (front)" and "cover (back)". Jellyfin shows the back cover instead of the front cover. 

When the file includes multiple pictures, Jellyfin should prefer files that contain one of these words: "front, cover, album" (with the word "front" most preferred). 

### Jellyfin Version

10.8.0

### if other:

10.8.6

### Environment

```markdown
- OS:Linux
- Virtualization: Docker
- Clients: Windows, Android
- Browser: Firefox
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins: None
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Please attach any screenshots here

![image](https://user-images.githubusercontent.com/712270/199651526-45e62288-6749-49d9-ad15-711e554204fb.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 1337joe** [comment]
Looking at [the code](https://github.com/jellyfin/jellyfin/blob/b2b4bd82d73be08fa0e1b15b3313b1a0e03d9839/MediaBrowser.Providers/MediaInfo/AudioImageProvider.cs#L85) the logic goes "front" > "cover" > any image.

I tagged a FLAC song with front and back cover images using kid3 and I can see the tag names "Cover (front)" and "Cover (back)" in the comment field of the streams when I debug and it works exactly as expected.

Any chance you can run ffprobe on the file to get the list of attachments and tags for debugging: `ffprobe /tmp/jellyfin/music/test.flac`

I'm specifically looking for the comment field on the attached pic streams (file title doesn't seem to get read in for audio files).

**Comment by dbolton** [comment]
Is this the output you need?

```
  Metadata:
    ARTIST          : Daniel Barenboim
    TITLE           : Piano Sonata No. 1 in F minor, Op. 2 No. 1: 1. Allegro [Beethoven 1793-1795]
    ALBUM           : Beethoven: The Piano Sonatas
    DATE            : 1984
    GENRE           : Classical
    track           : 01
    TRACKTOTAL      : 12
    disc            : 01
    DISCTOTAL       : 09
    MEDIA           : CD
    album_artist    : Daniel Barenboim
    COMPOSER        : Ludwig van Beethoven
    CDTOC           : C+96+42ED+9FEF+DF7A+13817+1B8E6+238BB+2736C+2E428+39AD3+430C6+461D9+4BCF6
    ENCODER         : fre:ac v1.1.6
  Duration: 00:03:46.44, start: 0.000000, bitrate: 436 kb/s
  Stream #0:0: Audio: flac, 44100 Hz, stereo, s16
  Stream #0:1: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 750x758 [SAR 96:96 DAR 375:379], 90k tbr, 90k tbn (attached pic)
    Metadata:
      comment         : Cover (front)
  Stream #0:2: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 740x736 [SAR 96:96 DAR 185:184], 90k tbr, 90k tbn (attached pic)
    Metadata:
      comment         : Cover (back)

```

I noticed when I play a file it shows the front cover (bottom corner of screenshot below), but the album shows the back cover (top left of screenshot). 
![image](https://user-images.githubusercontent.com/712270/199897005-39687fc7-57ef-45cc-9268-e5e9dc3b2ffd.png)

**Comment by 1337joe** [comment]
That's exactly the output I was looking for. Unfortunately it roughly matches what I see on my test files so nothing jumps out at me for what's going wrong. I'll try to find time to poke at it some more this weekend.

**Comment by dbolton** [comment]
Still affects me
