### ISSUE TITLE
[Issue]: HEVC hardware video acceleration not working properly

### ISSUE THREAD

**Issue by pojlFDlxCOvZ4Kg8y1l4** [jellyfin/jellyfin#8683]
### Please describe your bug

When using hardware transcoding on a J4105 system with HEVC media the video looks featureless and pink/white.  
Software transcoding and directplay are not affected, as well as X264 hardware transcodes.  

This is how this scene should look like: 
![image](https://user-images.githubusercontent.com/42654642/199618810-687dbec6-7e93-4da2-82cc-4e4f92238d0c.png)
but looks like this with HEVC hardware transcoding enabled:
![image](https://user-images.githubusercontent.com/42654642/199618680-fb493acc-50d1-4d80-ab28-0079fd2c2d02.png)  
and a different media file (tried several different movies and shows): 
![image](https://user-images.githubusercontent.com/42654642/199682124-44c457af-6e33-4bbc-a93a-22960b5329f6.png)

I've [opened a issue with the package maintainer](https://github.com/alexbelgium/hassio-addons/issues/537), which responded quick with a fix but sadly didn't work. He referred me to the Jellyfin team.
The issue I made earlier can be found here: https://github.com/alexbelgium/hassio-addons/tree/master/jellyfin

### Jellyfin Version

10.8.0

### if other:

10.8.7-1-ls186-2 https://github.com/alexbelgium/hassio-addons/tree/master/jellyfin based on the linuxserver.io docker image

### Environment

```markdown
- OS:
Home Assistant 2022.10.5 
Supervisor 2022.10.0 
Operating System 9.3 
Frontend 20221010.0 - latest 

- Virtualization: no
- Clients: Current version of Jellyfin media player, Firefox 106.0.3 64 bit, Chrome Version 107.0.5304.88 (Official Build) (64-bit)
- Browser: Firefox 106.0.3 64 bit, Chrome Version 107.0.5304.88 (Official Build) (64-bit)
- FFmpeg Version: MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Found ffmpeg version 5.1.2
- Playback Method: problem occurs with HEVC hardware transcoding. 
- Hardware Acceleration: both intel quick sync and VAAPI
- Plugins: no extra plugins
- Reverse Proxy: no additional proxy used, but I saw NGINX in the add-on logs. 
- Base URL: local IP with default port
- Networking: piggyback docker
- Storage: local
```

### Jellyfin logs

```shell
10:00:03] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Found ffmpeg version 5.1.2
[10:00:03] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available decoders: ["libdav1d", "av1", "av1_cuvid", "av1_qsv", "h264", "h264_qsv", "h264_cuvid", "hevc", "hevc_qsv", "hevc_cuvid", "mpeg2video", "mpeg2_qsv", "mpeg2_cuvid", "mpeg4", "mpeg4_cuvid", "msmpeg4", "vc1_qsv", "vc1_cuvid", "vp8", "libvpx", "vp8_cuvid", "vp8_qsv", "vp9", "libvpx-vp9", "vp9_cuvid", "vp9_qsv", "aac", "ac3", "flac", "mp3"]
[10:00:03] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available encoders: ["libx264", "h264_amf", "h264_nvenc", "h264_qsv", "h264_v4l2m2m", "h264_vaapi", "libx265", "hevc_amf", "hevc_nvenc", "hevc_qsv", "hevc_vaapi", "mpeg4", "msmpeg4", "libvpx", "libvpx-vp9", "aac", "libfdk_aac", "ac3", "flac", "libmp3lame", "libopus", "libvorbis", "srt"]
```

### Please attach any screenshots here

[Hardware addition transcode log.txt](https://github.com/jellyfin/jellyfin/files/9927169/Hardware.addition.transcode.log.txt)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nyanmisaka** [comment]
Can you share a video clip that contains these frames?

**Comment by pojlFDlxCOvZ4Kg8y1l4** [comment]
Kernel version 5.15.74
I've downloaded a few variations of the "big buck bunny" video. 

- x264 works fine
- VP8 works fine
- VP9 works fine
- HEVC does not. 

Video of a HEVC file where I start in a low bitrate to force transcoding, move to auto for direct play, and switch back to a low bitrate to force transcoding: 


https://user-images.githubusercontent.com/42654642/199697461-01c8fdc6-dc1f-4238-860c-1eb177eb8504.mp4

**Comment by nyanmisaka** [comment]
I'll try it with my 7th Gen Intel and get back to you.

**Comment by nyanmisaka** [comment]
It seems that the issue is specific to that processor J4105 or platform GeminiLake.
I can't reproduce it on i5-7300HQ with HD630 iGPU and on ARC A380 dGPU.

Please run `/usr/lib/jellyfin-ffmpeg/vainfo` and copy the output here.

Also please try this command with jellyfin-ffmpeg5 and see whether the output file contains artifacts?

`
/usr/lib/jellyfin-ffmpeg/ffmpeg -init_hw_device vaapi=va:,driver=iHD,kernel_driver=i915 -init_hw_device qsv=qs@va -filter_hw_device qs -hwaccel qsv -hwaccel_output_format qsv -c:v hevc_qsv -i "Big_Buck_Bunny_1080_10s_30MB.mp4" -an -sn -vf scale_qsv=format=nv12 -c:v h264_qsv -preset veryfast -b:v 2M -maxrate 2M -y "OUTPUT.mp4"
`

**Comment by pojlFDlxCOvZ4Kg8y1l4** [comment]
> docker exec 3bcc21f741ab /usr/lib/jellyfin-ffmpeg/vainfo

libva info: VA-API version 1.16.0
libva info: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_16
libva info: va_openDriver() returns 0
Trying display: drm
vainfo: VA-API version: 1.16 (libva 2.16.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 22.5.4 (e461c05)
vainfo: Supported profile and entrypoints
      VAProfileNone                   : VAEntrypointVideoProc
      VAProfileNone                   : VAEntrypointStats
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointFEI
      VAProfileH264Main               : VAEntrypointEncSliceLP
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointFEI
      VAProfileH264High               : VAEntrypointEncSliceLP
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline: VAEntrypointFEI
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          : VAEntrypointVLD
      VAProfileVP8Version0_3          : VAEntrypointEncSlice
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointEncSlice
      VAProfileHEVCMain               : VAEntrypointFEI
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileHEVCMain10             : VAEntrypointEncSlice
      VAProfileVP9Profile0            : VAEntrypointVLD
      VAProfileVP9Profile2            : VAEntrypointVLD

Output from your command is also showing the same weird output.

[ffmpeg conversion nyanmisika.txt](https://github.com/jellyfin/jellyfin/files/9929380/ffmpeg.conversion.nyanmisika.txt)

https://user-images.githubusercontent.com/42654642/199727380-ec9bc92e-0c1d-4f0f-8c98-f780949258a0.mp4

**Comment by nyanmisaka** [comment]
Thanks! What if you don't use our custom ffmpeg, use the stock ffmpeg from distro to run this command?

Make sure `intel-media-va-driver-non-free` pkg is installed before doing this.

**Comment by nyanmisaka** [comment]
If the issue persists, please file an issue to [media-driver](https://github.com/intel/media-driver) and link to this ticket. Intel devs can look into it.

**Comment by alexbelgium** [comment]
https://github.com/intel/media-driver/issues/930 ?

**Comment by pojlFDlxCOvZ4Kg8y1l4** [comment]
> Thanks! What if you don't use our custom ffmpeg, use the stock ffmpeg from distro to run this command?
> 
> Make sure `intel-media-va-driver-non-free` pkg is installed before doing this.

Package maintainer is being awesome and made a quick change with this commit:
https://github.com/alexbelgium/hassio-addons/commit/e8b704311a070b0f0c4f5f4d061993c028ab9734 
which includes the alpine `intel-opencl intel-media-va-driver-non-free` packages now.  

Sadly, this does not change the weird picture.  
I'm creating a issue to intel's media-driver repo right now.

**Comment by caiusseverus** [comment]
> It seems that the issue is specific to that processor J4105 or platform GeminiLake. I can't reproduce it on i5-7300HQ with HD630 iGPU and on ARC A380 dGPU.
> 
> Please run `/usr/lib/jellyfin-ffmpeg/vainfo` and copy the output here.
> 
> Also please try this command with jellyfin-ffmpeg5 and see whether the output file contains artifacts?
> 
> `/usr/lib/jellyfin-ffmpeg/ffmpeg -init_hw_device vaapi=va:,driver=iHD,kernel_driver=i915 -init_hw_device qsv=qs@va -filter_hw_device qs -hwaccel qsv -hwaccel_output_format qsv -c:v hevc_qsv -i "Big_Buck_Bunny_1080_10s_30MB.mp4" -an -sn -vf scale_qsv=format=nv12 -c:v h264_qsv -preset veryfast -b:v 2M -maxrate 2M -y "OUTPUT.mp4"`

If it's any use, I've just tried this command line with my J4105 and the output is fine - no artefacts visible and the file looks as expected. Samples:

![vlcsnap-2022-11-15-18h14m08s243](https://user-images.githubusercontent.com/7763268/201995288-fa2e4ecb-be25-434b-8c1b-08991a2a2e18.png)

![vlcsnap-2022-11-15-18h14m26s139](https://user-images.githubusercontent.com/7763268/201995297-e87acd14-c3d3-4111-bec5-996c66cb6436.png)

I have a slightly earlier version of the iHD driver installed and I'm not using docker:

> libva info: VA-API version 1.14.0
libva info: User environment variable requested driver 'iHD'
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_14
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.14 (libva 2.14.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 22.4.3 (74f40ee)

Updating to the latest driver version in the intel repo shows no change - the output is artefact free still:

> libva info: VA-API version 1.15.0
libva info: User environment variable requested driver 'iHD'
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_15
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.15 (libva 2.15.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 22.5.0 (7e9cc59)
