### ISSUE TITLE
Client fails to playback (directplay) .mkv files (serverbuild 10.8.7, transcoding not allowed)

### ISSUE THREAD

**Issue by gordon848** [jellyfin/jellyfin#8684]
**Media Info of the file**
screenshot

**Logs**
`[2022-11-01 21:47:39.092 +01:00] [INF] [18] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "test". EnablePlaybackRemuxing: False EnableVideoPlaybackTranscoding: False EnableAudioPlaybackTranscoding: False [2022-11-01 21:47:39.111 +01:00] [INF] [18] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile="Jellyfin Media Player", Path="/data/some.mkv", AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=Transcode, TranscodeReason=ContainerBitrateExceedsLimit ) "media:/videos/45183281-52cb-1f65-556e-16bb7cccc896/stream?MediaSourceId=4518328152cb1f65556e16bb7cccc896&AudioStreamIndex=1&api_key=<token>&RequireAvc=false&Tag=d1acc283c96ae0440e9dd4d9f005abe7&TranscodeReasons=ContainerBitrateExceedsLimit" [2022-11-01 21:47:41.082 +01:00] [INF] [8] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Jellyfin Media Player" "1.7.1" playing "Ciao". Stopped at "0" ms% `

**FFmpeg Logs**
none

**Stats for Nerds Screenshots**
none

**Server System (please complete the following information):**
 - OS: Docker on Linux (linuxserver)
 - Jellyfin Version: 10.8.7
 - Hardware settings & device: i5 7500t
 - Reverse proxy: no
 - Other hardware notes: /
 
**Client System:**
 - Device: Laptop
 - OS: Linux
 - Client: Jellyfinmediaplayer 1.7.1

Im not sure if this is a player related problem or a server problem. If I play a typical .mkv file I get a Playbackerror (Tries to transcode which is disabled for all users). Somehow this has something to do with the serverbuild. Using 10.7.7 I can direct play all of my files. But using latest (10.8.7) I cant play most of my .mkv files (AC3 audio).

Using kodi" or jellyfin-mpv-shim as a client plays all files even in build 10.8.7. So I guess JMP has problems with the 10.8.x builds? Or is there an issue with the 10.8.x builds? #8018 seems to be a similar problem.

![1](https://user-images.githubusercontent.com/91946909/199732853-96d7ea36-ffab-4ed8-acf1-6e3f2b844162.jpg)
![2](https://user-images.githubusercontent.com/91946909/199732859-4db98b50-c4a8-43fa-89ed-accaadfa8c07.jpg)
![3](https://user-images.githubusercontent.com/91946909/199732865-81b5d62e-2d64-4b54-9623-cd521ca48586.jpg)
![4](https://user-images.githubusercontent.com/91946909/199732868-295592a7-3a3e-4ee3-8dc6-9e5ed5e315f5.jpg)

**Comment by andyandybeginner** [comment]
well. I have similar issue. Will keep an eye on this thread if anyone can help
