### ISSUE TITLE
[Issue]: Known Proxies fails with hostname instead of IP

### ISSUE THREAD

**Issue by DavidFair** [jellyfin/jellyfin#8692]
### Please describe your bug

Running Jellyfin with the Known Proxies settings set to a hostname will cause the ASP middleware to flag the IP as an unknown proxy. This prevents the `X-Forwarded-For` header from being parsed, so the server sees the proxy IP breaking external network detection.

Looking at the description in the web interface: `Comma separated list of IP addresses or hostnames of known proxies` implies that a hostname should be equivalent to a hardcoded IP. For Docker containers this is a key point, otherwise the admin will have to update the proxy IP each time they restart the relevant container.

(Note: I understand that Jellyfin may need to be restarted when Traefik restarts to resolve the new IP, but it's better than manually updating the IP each time). 

Troubleshooting completed:
- Checked the `X-Forwarded-For` header using the [whoami](https://hub.docker.com/r/containous/whoami) container, this correctly shows the real IP of the device, so Traefik passes the headers through
- Checked that the Jellyfin container could resolve the DNS name through `ping traefik`, this resolved to `172.18.0.78` at the time
- Checked logging for Jellyfin when known proxies is set to the hostname `traefik`. IPv6/4 dual stack gives:
```
[DBG] [44] Microsoft.AspNetCore.HttpOverrides.ForwardedHeadersMiddleware: Unknown proxy: "[::ffff:172.18.0.78]:47438"
<snip>
[INF] [36] Jellyfin.Api.Helpers.MediaInfoHelper: RemoteClientBitrateLimit: 4500000, RemoteIp: "172.18.0.78", IsInLocalNetwork: False
```

Whilst the IPv4 stack gives:
```
[DBG] [10] Microsoft.AspNetCore.HttpOverrides.ForwardedHeadersMiddleware: Unknown proxy: "172.18.0.78:59330"
<snip>
[INF] [10] Jellyfin.Api.Helpers.MediaInfoHelper: RemoteClientBitrateLimit: 4500000, RemoteIp: "172.18.0.78", IsInLocalNetwork: False
```
- Switched to using the hardcoded IP `172.18.0.78` for known proxies. This correctly parses the header and now detects the remote client IP.

Possible Solutions:
- Parse the hostname and inject the current IP into the list of accepted proxy IPs. Care would have to be taken on dual stack deployments (see logging)
- Allow for the entry of a CIDR (similar to known networks). This has security implications from this risk of a user doing something silly like `0.0.0.0/0` and effectively accepting external headers sent to Jellyfin.
- Update the web UI to document this limitation (though this shifts the burden onto the user to assign a static IP for their container now)
- Something else?
 

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Ubuntu
- Virtualization: Docker (LinuxServer.io)
- Reverse Proxy: Traefik
- Base URL: https://videos.<domain>
- Networking: Docker Swarm + Traefik (Host mode)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shadowghost** [comment]
#8147 should handle this properly.
