### ISSUE TITLE
Docker image can't build ImageMagickSharp, TagLibSharp

### ISSUE THREAD

**Issue by BnMcG** [jellyfin/jellyfin#87]
The docker image can't build these two projects correctly as they have .Net 4.5 targets, and the Docker image is missing Mono.

I think our options are either:

1. Remove .Net 4.5 targets from ImageMagickSharp, TagLibSharp (and see if anything breaks)
2. Find an argument for `dotnet build` to specify targets to build
3. Add Mono to the Docker image

In my opinion, those are also listed in order of most to least preferable.

I'll have a go at removing .Net 4.5 targets shortly.

**Comment by BnMcG** [comment]
Removing the ImageMagickSharp and TagLibSharp build configurations is causing problems in #82, where users can't build the solution unless these projects have already been compiled. Not sure why the Docker image still builds successfully, though.

**Comment by BnMcG** [comment]
So we can specify a framework to build against in the dotnet build command, but because we need to target multiple frameworks (netstandard2.0, netcoreapp2.1), we can't build properly...

Even after specifying netstandard2.0 and running against only taglibsharp.csproj, when you target netcoreapp2.1 and run against the mediabrowser.sln, it doesn't recognise that a netstandard library has already been compiled for taglibsharp and then errors out that there's no netcoreapp2.1 target.

The easy option here is to wait for Mono to release a new taglib-sharp NuGet package, as then we don't need to worry about compiling it at all (thanks @Bond-009 for the suggestion!), but there's been an open issue on this with taglib-sharp for a while now (mono/taglib-sharp#40)  without any news.

In the short term I'd recommend forking the taglib-sharp repository into the jellyfin GitHub organisation, updating the csproj in the fork to only target .Net Standard. If/when Mono release a new taglib-sharp NuGet package, we can ditch the fork and move back to the official NuGet package. In the meantime, any updates we need from upstream that aren't released in any new packages can always be merged into the fork easily.

**Comment by JustAMan** [comment]
@BnMcG it seems to me that forking and fixing is the best we could do now. Would you be able to make it happen? :)

**Comment by BnMcG** [comment]
@JustAMan, I need somebody with appropriate access to the Jellyfin organisation to fork taglib-sharp into it, @joshuaboniface has said he'll do it at some point today, but if you can make it happen sooner I'm happy to change the csproj and update references in the Jellyfin repository.

**Comment by JustAMan** [comment]
I do not have enough permissions (and I don't want them now, I have enough on my plate tbh :), so you have to wait for @joshuaboniface

**Comment by nvllsvm** [comment]
@joshuaboniface Hold off on action for a bit. I'll try a few things tonight. I'd like to leaving forking as the very last resort.

**Comment by RazeLighter777** [comment]
We are not using Mono anymore. Use the Nuget package if you are going to do this. I am working on a pull request now.

**Comment by RazeLighter777** [comment]
I managed to build the container successfully. Just use nuget to add the TagLib 2.1 library, and it will build correctly. Do you want me to make a pull request?

**Comment by nvllsvm** [comment]
@RazeLighter777 - No, that version apparently is missing a lot of features https://github.com/jellyfin/jellyfin/pull/41#issuecomment-446218891

**Comment by RazeLighter777** [comment]
@nvllsvm Are those features critical to the project?

**Comment by nvllsvm** [comment]
Depends - Opus is growing in popularity and FLAC is already popular. 

I'd rather us stay on master than downgrade to a six year old version.

**Comment by BnMcG** [comment]
Is there any progress on this? I still can't build the MediaBrowser solution at the moment.

**Comment by RazeLighter777** [comment]
You can build it if you add TagLib 2.1 to the Emby.Photos csproj file with nuget. But apparently that version is outdated (doesn’t support flac or opus) so we are not doing that.

**Comment by BnMcG** [comment]
I've worked around for now by building taglib-sharp and imagemagicksharp using the CLI, this fails the Net 4.5 compilation but it still compiles the .net standard version first. This seems to work as long as I don't clean the solution, in which case I need to manually re-compile these from the cli again.

**Comment by anthonylavado** [comment]
So, in attempting to set up my build environment on macOS (10.14.2, VS 7.7.2), I've noticed I have a variant of this as well.

Visual Studio for Mac comes with Mono, even though it recognizes .NET Core and offers to install it, if you don't have it.

In the default debug configuration for the solution, taglib-sharp isn't marked for building, so I just had to enable it in the Solution Options.

**Comment by anthonylavado** [comment]
So if I copy `taglib-sharp.dll` from `/ThirdParty⁩/taglib-sharp⁩/src⁩/bin⁩/Release⁩/net40` into `netstandard20`, then the whole build works, because it can now find the DLL it needs with the right target name. I haven't _tried_ the Photos function yet (if that's where this is called), I've only tried streaming a few test clips, but it seems to work. Is there something I can check to make sure Taglib is used?

cc @nvllsvm

**Comment by anthonylavado** [comment]
So TagLub has been updated in Beta right now. Would be good to test it

https://www.nuget.org/packages/TagLibSharp

https://github.com/mono/taglib-sharp/issues/138

**Comment by Bond-009** [comment]
Both of the projects in question have been removed.
