### ISSUE TITLE
[Issue]: Direct Stream transcoding of audio not being executed with custom DLNA profile

### ISSUE THREAD

**Issue by MorpheusUK** [jellyfin/jellyfin#8701]
### Please describe your bug

With an Mastroka (mkv) container containing H.264 video and dts encoded audio it is not possible to only have the audio transcoded.

Prerequisites:
Jellyfin configured for DLNA and discoverable on your network

Reproduction Steps:
1. From the menu select Dashboard->DLNA
2. Select the profiles tab and press the '+' beside Custom profile
3. Add relevant information to allow your DLNA client to be identified and ensure dts isn't listed in the Direct Playback tab
4. Select the codec tab
5. Select new and select "Video Audio" and add dts as the codec. Then select ok
6. On your client that doesn't support DTS (2020 LG TV), play the video from the DLNA browser connected to the Jellyfin server

Expected Result:
The video should play directly but the audio should be transcoded and play

Actual Result:
The video plays with no sound as the audio isn't transcoded. The only way to get the audio transcoded is to force the video to be transcoded as well by removing h264 from the direct playback tab.

### Jellyfin Version

Other

### if other:

10.8.7

### Environment

```markdown
- OS: Synology DSM 7.1.1
- Virtualization: Docker (jellyfin/jellyfin)
- Clients: LG BX (2020) TV
- Browser: Firefox 105.0.2, Vivaldi 5.5
- FFmpeg Version: jellyfin-ffmpeg
- Playback Method: DLNA
- Hardware Acceleration: Intel QSV
- Plugins: None
- Reverse Proxy: None
- Base URL: http://mynas:8096/web/index.html#!/dlnaprofiles.html
- Networking: host
- Storage: local
```

### Jellyfin logs

```shell
[2022-11-03 22:32:23.788 +00:00] [DBG] [30] Emby.Dlna.DlnaManager: Found matching device profile: "[LG] webOS TV OLED55BX6LB" [2022-11-03 22:32:23.791 +00:00] [DBG] [30] Emby.Dlna.ContentDirectory.ContentDirectoryService: Control request. Headers: [KeyValuePair`2 { Key: "Host", Value: ["myserver:8096"] }, KeyValuePair`2 { Key: "User-Agent", Value: ["Linux/4.4.84-612.37.jebil.2 UPnP/1.0 LGE WebOS TV LGE_DLNA_SDK/1.6.0/04.40.18 DLNADOC/1.50"] }, KeyValuePair`2 { Key: "Content-Type", Value: ["text/xml; charset=\"utf-8\""] }, KeyValuePair`2 { Key: "Content-Length", Value: ["278"] }, KeyValuePair`2 { Key: "SOAPAction", Value: ["\"urn:schemas-upnp-org:service:ContentDirectory:1#GetSearchCapabilities\""] }, KeyValuePair`2 { Key: "DLNADeviceName.lge.com", Value: ["%5bLG%5d%20webOS%20TV%20OLED55BX6LB"] }] 


[2022-11-03 22:32:28.681 +00:00] [DBG] [36] Emby.Dlna.ContentDirectory.ContentDirectoryService: Profile: "[LG] webOS TV OLED55BX6LB", Path: "/data/media/Movies/film1/movie.mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: True [2022-11-03 22:32:28.681 +00:00] [DBG] [36] Emby.Dlna.ContentDirectory.ContentDirectoryService: Transcode Result for Profile: "[LG] webOS TV OLED55BX6LB", Path: "/data/media/Movies/film1/movie.mkv", PlayMethod: DirectStream, AudioStreamIndex: 1, SubtitleStreamIndex: -1, Reasons: 0 [2022-11-03 22:32:28.681 +00:00] [DBG] [36] Emby.Dlna.ContentDirectory.ContentDirectoryService: DirectPlay Result for Profile: "[LG] webOS TV OLED55BX6LB", Path: "/data/media/Movies/film1/movie.mkv", PlayMethod: DirectStream, AudioStreamIndex: 1, SubtitleStreamIndex: -1, Reasons: AudioCodecNotSupported
```

### FFmpeg logs

```shell
No logs created
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dabohda** [comment]
Would you share your dlna profile? Or is there a place to share them?

I am working on my dlna profile to get streaming working with my lg c2 2022. I want to get direct stream working with dts audio track like you.

Did you try it with the Jellyfin Webos app?

**Comment by MorpheusUK** [comment]
> Would you share your dlna profile? Or is there a place to share them?
> 
> I am working on my dlna profile to get streaming working with my lg c2 2022. I want to get direct stream working with dts-ac3 transcode like you.
> 
> Did you try it with the Jellyfin Webos app?

The WebOS app for my 2020 model has only been just released today (well I think technically yesterday now as we are past midnight) so I haven't tried it yet. However I did pick up a newer Chromecast model with Google TV which I installed the Android app on over the Black Friday week and only tested that briefly but it seemed to work well. 

I never solved the DTS transcoding issue via DLNA. I ended up adding an AC3 track to one of the files using ffmpeg as a work around as recommended on my query on Reddit before getting the Chromecast with Google TV and being able to run the app on there.

The command to do that in ffmpeg in case you want to try it is:
ffmpeg.exe -i input.mkv -map 0:v -map 0:a:0 -map 0:a -map 0:s? -c:v copy -c:s copy -c:a copy -c:a:0 eac3 -ab 1536k -disposition:a:0 default -disposition:a:1 0 output.mkv

My profile is below which you can use as a starting point at least:

`<?xml version="1.0" encoding="utf-8"?>
<Profile xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Name>[LG] webOS TV OLED55BX6LB</Name>
  <Identification>
    <FriendlyName>[LG] webOS TV OLED55BX6LB</FriendlyName>
    <ModelNumber />
    <SerialNumber />
    <ModelName />
    <ModelDescription />
    <ModelUrl />
    <Manufacturer />
    <ManufacturerUrl />
    <Headers>
      <HttpHeaderInfo name="DLNADeviceName.lge.com" value="[LG] webOS TV OLED55BX6LB" match="Equals" />
      <HttpHeaderInfo name="DLNADeviceName.lge.com" value="%5bLG%5d%20webOS%20TV%20OLED55BX6LB" match="Equals" />
    </Headers>
  </Identification>
  <FriendlyName />
  <Manufacturer>Jellyfin</Manufacturer>
  <ManufacturerUrl>https://github.com/jellyfin/jellyfin</ManufacturerUrl>
  <ModelName>Jellyfin Server</ModelName>
  <ModelNumber>01</ModelNumber>
  <ModelUrl>https://github.com/jellyfin/jellyfin</ModelUrl>
  <SerialNumber />
  <SupportedMediaTypes>Audio,Photo,Video</SupportedMediaTypes>
  <UserId />
  <AlbumArtPn>JPEG_SM</AlbumArtPn>
  <MaxAlbumArtWidth>480</MaxAlbumArtWidth>
  <MaxAlbumArtHeight>480</MaxAlbumArtHeight>
  <MaxIconWidth>48</MaxIconWidth>
  <MaxIconHeight>48</MaxIconHeight>
  <MaxStreamingBitrate>140000000</MaxStreamingBitrate>
  <MaxStaticBitrate>140000000</MaxStaticBitrate>
  <MusicStreamingTranscodingBitrate>512000</MusicStreamingTranscodingBitrate>
  <MaxStaticMusicBitrate>8000000</MaxStaticMusicBitrate>
  <SonyAggregationFlags />
  <ProtocolInfo>http-get:*:video/mpeg:*,http-get:*:video/mp4:*,http-get:*:video/vnd.dlna.mpeg-tts:*,http-get:*:video/avi:*,http-get:*:video/x-matroska:*,http-get:*:video/x-ms-wmv:*,http-get:*:video/wtv:*,http-get:*:audio/mpeg:*,http-get:*:audio/mp3:*,http-get:*:audio/mp4:*,http-get:*:audio/x-ms-wma:*,http-get:*:audio/wav:*,http-get:*:audio/L16:*,http-get:*:image/jpeg:*,http-get:*:image/png:*,http-get:*:image/gif:*,http-get:*:image/tiff:*</ProtocolInfo>
  <TimelineOffsetSeconds>10</TimelineOffsetSeconds>
  <IgnoreTranscodeByteRangeRequests>true</IgnoreTranscodeByteRangeRequests>
  <XmlRootAttributes />
  <DirectPlayProfiles>
    <DirectPlayProfile container="ts,mpegts,avi,mkv,m2ts,mp4,m4v" audioCodec="aac,ac3,eac3,mp3" videoCodec="hevc,h264,mpeg4" type="Video" />
    <DirectPlayProfile container="mp3" type="Audio" />
    <DirectPlayProfile container="jpeg,png,bmp" audioCodec="" videoCodec="" type="Photo" />
    <DirectPlayProfile container="flac" audioCodec="flac" videoCodec="" type="Audio" />
    <DirectPlayProfile container="ogg" audioCodec="vorbis" videoCodec="" type="Audio" />
    <DirectPlayProfile container="wma" audioCodec="wma" videoCodec="" type="Audio" />
    <DirectPlayProfile container="wav" audioCodec="" videoCodec="" type="Audio" />
  </DirectPlayProfiles>
  <TranscodingProfiles>
    <TranscodingProfile container="mp3" type="Audio" videoCodec="" audioCodec="mp3" protocol="">
      <Conditions />
    </TranscodingProfile>
    <TranscodingProfile container="ts" type="Video" videoCodec="hevc" audioCodec="ac3" protocol="" enableMpegtsM2TsMode="true">
      <Conditions />
    </TranscodingProfile>
    <TranscodingProfile container="jpeg" type="Photo" videoCodec="" audioCodec="" protocol="">
      <Conditions />
    </TranscodingProfile>
  </TranscodingProfiles>
  <ContainerProfiles>
    <ContainerProfile type="Photo" container="">
      <Conditions>
        <ProfileCondition condition="LessThanEqual" property="Width" value="1920" isRequired="true" />
        <ProfileCondition condition="LessThanEqual" property="Height" value="1080" isRequired="true" />
      </Conditions>
    </ContainerProfile>
  </ContainerProfiles>
  <CodecProfiles>
    <CodecProfile type="VideoAudio" codec="ac3,eac3,aac,mp3">
      <Conditions>
        <ProfileCondition condition="LessThanEqual" property="AudioChannels" value="6" isRequired="true" />
      </Conditions>
      <ApplyConditions />
    </CodecProfile>
    <CodecProfile type="VideoAudio" codec="dca,dts">
      <Conditions>
        <ProfileCondition condition="Equals" property="AudioProfile" value="dts" isRequired="true" />
      </Conditions>
      <ApplyConditions />
    </CodecProfile>
  </CodecProfiles>
  <ResponseProfiles>
    <ResponseProfile container="mkv" type="Video" mimeType="video/x-matroska">
      <Conditions />
    </ResponseProfile>
    <ResponseProfile container="m4v" type="Video" mimeType="video/mp4">
      <Conditions />
    </ResponseProfile>
    <ResponseProfile container="ts,mpegts" type="Video" mimeType="video/mpeg">
      <Conditions />
    </ResponseProfile>
  </ResponseProfiles>
  <SubtitleProfiles>
    <SubtitleProfile format="srt" method="Embed" />
    <SubtitleProfile format="srt" method="External" />
  </SubtitleProfiles>
</Profile>`
