### ISSUE TITLE
[Issue]: For series without season and episode number metadata, Next Up chooses its next item by `PresentationUniqueKey`

### ISSUE THREAD

**Issue by blackwind** [jellyfin/jellyfin#8702]
### Please describe your bug

I have one particular show that isn't listed on any of the metadata providers, doesn't have season or episode number metadata, doesn't have `ForcedSortTitle`s, but does have chronological titles ("Episode 200: Having Some Fun", "Episode 201: This Is a Great Day"...). Choosing the next up episode by title or date added would be sufficient to produce the expected result (Jellyfin is capable of ordering them properly when I navigate into the series), but I've investigated in `library.db`, and Jellyfin is definitely choosing the next episode based on `PresentationUniqueKey`. I have about 40 episodes of the show in question currently, I've run an SQL query to display only those episodes, I've sorted by `PresentationUniqueKey`, and each time I mark the next up episode as watched, Jellyfin always chooses the next `PresentationUniqueKey` in alphabetical order as its next episode.

### Jellyfin Version

10.8.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AustinHasten** [comment]
Running into this as well. Sorting by Name, SortName, or ForcedSortName would work well in my situation.

**Comment by blackwind** [comment]
Still an issue.

**Comment by blackwind** [comment]
Still an issue.

**Comment by blackwind** [comment]
Still an issue.
