### ISSUE TITLE
[Issue]: Cannot play music folder when Library page size = 230+

### ISSUE THREAD

**Issue by kiawizard** [jellyfin/jellyfin#8704]
### Please describe your bug

I have a music folder with 1600 tracks. The default page size is 100. I wanted to shuffle-play the whole folder, but shuffling is done inside the selected page (among 100 tracks). I have increased the page size to unlimited (= 0), after that going to library, "Songs" and clicking any track produces an AJAX error (the request is just too long). Experimentally I found that maximum page size which allows to play music is 229

AJAX call is: https://my_domain/Users/65fc16d12e09449db590a6b6f27783b3/Items?Ids=a8b79f0d517ae97fee2f7a46e2ee7800%2C3683f48cfba35f0b1a939ac2e19db16f%2C1f237ba8aa59b6410d05d03ad57fc7e7%2Cdb584540c37b51dd023772064074e0a5%2Cbc65b50027fae59a433f62f9f040a979%2C9ad57f40160b8f3de75a0af28422bfc5%2Cf815401b65df154865cd2584db1e3731%2Cbaa266b59a3a1961c8681f16c27eb3a6%2C79231ae88636b46ebf06ac21fd2336b9%2Cd79b94ef547eec5cb26afeb7d309b934%2C05bf3420e3c39fb5cd50d5e9ad669231%2C5013d898bd4503410c5e9bf82fb9d9d8%2Ce322b40dd574e38b36137f01a50fedce%2Ce1cddebf8fe0ac3593fbcb6b3841475f%2Cb41f42970b9d19144ec35150ebeef3e8%2C63a0a6e489231a740bdf77467ced1fd4%2C4adadc6a55fe90f8ab783dc76e81d377%2C1533ea04e59ee48151d317af970043c9%2C8c2340d93d8f03c58d71d2731f0312c1%2Ca50a823f42a3b5c5c3b7cb0d846e0b7e%2Cd4fd03d4f357149e4b493d20e0bb57c5%2Cc7d8cd9fc60fae55091a6c610c023034%2Cc888681a166b96fcdeadd671433afbb3%2Ca25baad7e31cbb90b6afabd9c6286297%2C556eb097a4ca08a6fcc321c12a41cdba%2C6b0645fdb439f9226660aab2a39335b5%2C00fd754990bbd975af55d7025536ef8b%2C9065d4e43b340b19e4505ef3d57cc5a2%2C61fe162d12866b01ea614b0fdbf86b04%2C6be45c490160a4fce0058054d0e4efc2%2Cc2877b4519d1e184641d2acc058013ef%2Cb983e0450b76609f990f00b493a71105%2Cac5e2d15658ad1226d98cfa93b896051%2C3359ac57913923f198f2417e7e517652%2C8a34f3335f7f01cadfc0506d11fbecbf%2Cf28ceb635db70d7bfa151883b4319afe%2Cda72882bdaab5e9a324d45d2e84430e6%2C6ec951dac5f1b721ad348f5e502f07bc%2C5cffb4e2863ed0f0744a6b8b923132da%2C36cfd27292e963cf0b28074bca10a720%2C2c49333b1b85fe345a08ad4f138e0b61%2C5da8614f676746ec7245f04c44e270a4%2Cf14417bf0bef86974190ba1959faae86%2Cbb40035d1cca4bcac00915acb60b0b2b%2Cef17adfd82c19cb709dd360f6cca0037%2C95700b47cfa65c2d61500a76a686866a%2Ce965538a3f9d1ac69cacf4288f7b02be%2Caec09adbcb7cf131e6c979e2e81e3c21%2C6efed29157c4f56447de844ed805f808%2Cde9b941a8e2985586f923db900d11d80%2C3b416ee377fa7a419fa7d8f2a04f53d3%2Cdc7cef24ec87bd4a2a7c23677f54786d%2C61d1931d62ef5e93c42f75cf2a1b4650%2Cd04f522ddf084008479f02e73fb1a0c4%2Ce9ba3cef741b422e745e152b73ff94f5%2C6808da28eb218d8cc48750859c03bb09%2C904aeba6b39134dbd464921a628aedc0%2Cbbb995d70f60170fb250130ca85aef9d%2C6dcee6504d1697ac524e71897d29fc73%2C2012e57660914fdf6daad12786e44406%2Cb54ed0b07640509e637afef500a33ac9%2C97d0283315a7fe9258b0bb2a8fc1de9e%2Ce35ce9ce4d07f3b386adeae8cfd7d472%2C182890f381afb6f7f63af39c68b81320%2C40e1d8865d024cb57045d5db4bcdb5af%2C01fa9142537e0a966cf38d093aba4230%2C86153b443c2928db8632c694f47c0399%2C59f4e6afc99b59d2dbc7d8f52cc1f727%2C162825c5d0323cf47bcaf2177f9420b4%2Cd3cf3ed86325089ce001f097ba7743ad%2C38721758476c048ed3e5c0fadff0c3f4%2C3329fea8b7766665d15cecf8164e1b82%2C1392b4d2741b3f662dd31f8357c1fb00%2Cc93496e8718439f349872eedc6029abb%2C61e16243961ea3dfd63ef5b16dbecba1%2C6cc5b021c6e6a157ce1ebe5ffd34b5c2%2C4f36a3e20432c4b8f8c546368006eaa7%2C6f8e90293072e8943a667ecf3404a3b5%2C1e26d45e4a3623efe12ba09772790621%2Cba530861fb8561df3b8009d56c25db5c%2Cf727e50689ab182e1080983b7b58153f%2C95c341555f74566d808874b359f0b82a%2Cd9a52d02baee0be5907b4b8806f898f2%2Cf301c9af84f913532e8739296aa07cc4%2Cc8fe02d4aaa574e0235f69a1c604daef%2Ca561f76f3675e5f355638a1a4bbb9a66%2C49618fac5b332d39058f4a55e63a6d73%2C6607599176679162db5e794250bf92c6%2Caf1c2fe901ca742ca94b28ff27abe6e7%2C85e87a7d2968c32f492e32c73c4dded5%2Cfde0894776c8860fc799637aa2044713%2Cd7660489a183160fc41a88479781ad38%2C8ef69890958a4cd1956ede7a93e8b5c3%2C77977998d298041d2363882fee833d3e%2C87aabf2237054c08011b3847361751ae%2C91283b76f91966876ae505c373725241%2C134a7eea4d87e1e01b4d302b02ab8a17%2Cbaf22b8a5c7c91766baf1010bcd6f938%2C954257988111f06c2b84c06c226c4d80%2C16b202761dec28f2514395eb5ea21ee1%2C7fb48a71b2f26e30be3b844871b281ba%2C67202efb73c36bdb062eb3028daca42b%2C649f5c619a4af9c4e24bb2128f56c8b5%2Cac1cc99322165027fffcc509b437b17a%2Cc27cd2a8fac192ed2a03483257f1f2fe%2C0a64feb7d179137e8acbafedb0b2b13f%2Ca9831bbeea6c01d7d6d2e21e8c0c004a%2Cc0546ea34f1bfedb33018ced6c9decea%2C8bfc88bdb6bd5c0109ab214a2764147e%2Cdd4873eb9a12ce754a5d97157b04aeb8%2Cd42511714233d3f1dcb2fe1ba4abb9f9%2Caabfb14a29161fddaa1152457d105e17%2Cfefee3c3b795a616a4a29f1cf73a159f%2C168e1b8d77140589423cd14fffd611a0%2Cdf6e3291bd0fed44ff378b247e284f10%2C86fa5db6e3edcdef9c660bffac86fe3b%2Ceecc30fb348b7dc63a807c9e139ee55c%2C1020cafafadf1191b6eada633d2af489%2C8d1f5cfebba4b33d4075d983c82152be%2C34549076d5d6711df91a19d2a70096c0%2C0759f1851423f763753d6f167fa1e14a%2Cfbc08a3ce7ea123c8d425dbae74abf4f%2Ccffd668159546335b26196b2f087e505%2C2cb703bfc1a6fae8c292e552babb6a74%2C767445218ff1d2a5de330b5da9ff9dbb%2C45d43c689b0946228c191690294f508a%2C954bf1255ed4542fab44fcc2d76c4730%2Ca8d8e83d92e88bd5681158e8fc4e14d0%2C5b22d51bfb7af99cf8f95ad4d7586783%2C5805d93902da18fbc514e7364181b38d%2C908db6845299966830692cebb7d0bb43%2C01c511bdc0fd876cfc0e724704edad5d%2C2707192d51dc07de6e775f82325c15ff%2Cf22b311375f4c0ea26d07537166f7454%2C7a72e087cb4822852b60f704f7efe65d%2Cb30c093021d41f606afc96a107bc8ac8%2C5362b1d5942c6fcdc86697413e424cd7%2Ce305dcd89ea43b07051c13f55cebe54e%2Cdbb4ee2225406caa1abe3ce700e7cbe0%2Ce4b65a258bcd20699c3b35e3382e9a3b%2Cd256289487f40da19c78a0be7549eebb%2C89b7b867c8e8588ba597f6ef1d0d954a%2C6fa7be22b8b37c9a002827f77eb73dc3%2C89893ae380efd828094609b929779a2b%2Cf5fdf021c4ac42729cc49e8d3766e106%2C4930d33bacb06d2e40d35d41191e05e6%2Cdd7d6b9d254a0aa29f9f7aee5540ed2c%2C02c8aaeae5679622fff114190a304fd0%2C75a0a378f003b874ef01f838b8eaf6e7%2C89e4d86e0265fd38592e1f63989b10cd%2C94aa54aca0f9a088a60eac9fdb4b331d%2C0b79de922eced3802e18569948b95b20%2C0fc7d4d67ee27f8e887ef6b614036f60%2Cf0d8681ba95bda44c65f2c45cec18def%2Ccd0b04ce302275db21605e273c3ea575%2Cd2f215edc03e0e3a604489c265835259%2C2f84991b0c9e029b5d23a08bb982b67d%2C2d33b2579d0d43f9b9c6ee2b5aff6e9a%2C5dd3562f6845d07e4c7ef4685c6d1a3f%2C1ca6e0b49880a0050c2a46baf33f5db8%2Cbdc118fd82d3f33097e6b4813ff5900e%2C917ab504e327834f5004bd9f671ad664%2C1fadfd3c4720f70438519ee80b221bbc%2C9a7bf479dee546f16a9caf7183496590%2Cc98113524809a9c75782d852ae9e48df%2C8f8a13ac0e5fb3a0a9a2dd804622dd1d%2C2630b4c40353ea3e1760d0b3c0509acc%2C819d737e21184428dbf01cd445546ad9%2C0eb74749dd296914e7fe62adddbb2f2c%2C3d7ca59df5827bbed3814f35b634c119%2C7d5fc09b738776aeda65f948c24bae6e%2Cf2fc9920619f41122b8d2f62ffb0b890%2C4380d00c8f6a45ab36478c4c9f81a2d0%2C9db5f81383041e66af3e88908b7a1330%2Cc706d136236a43d1afa490629829828d%2C37c6a267a6bfae1f3b55b5d0f3913afb%2C826ad9bf5e657bfd821be73c914ffb47%2C7f146b1a3f58822956279b96ac120940%2Cddc4bd826a143f010a5b46848d0ab9cf%2C2d0e6ac2295c2a9c1ba21077d1647c26%2C53e369c702a3d880b8e1f13d690cd4d8%2C1ecc6890a9ea9cd6b175433791c3a5ff%2Cce77beea8bcefc58c0d7c915d90d5916%2Cedfaa16aea6ed58bd7b5914c120df467%2C207f5a3bb87d3204f692c9f1a4a6cbad%2Cd8588f4f744b5081b8c825be11735bd5%2Ce01a9d2e9fd79ec4a0557b92ecf2bde0%2C66fe091aebf79df79087f5f463ea8552%2Cecd2e9879ad3f4e7483fd4b09b05bdc9%2C44cbfac50027e237c8377c73c5c5252f%2C8172bd8ea8f3c6d613fa28801eda28e8%2C9baca058ea3e8d0b2ff90db01345563e%2Cc7878b27b0732fdb689b30085443c0ef%2Caa1d605d92f28eccf1441e2325c4cfc3%2Cc16bcb3678bd7d89ccf056f00788930a%2C1bccbb8b699ee120b280a01705db971a%2C3af3015e42fff74ecee30fadd8075c7b%2C998df57c8b54211b66290d6e7ef16c89%2C7a38d43c33fe061fe283cfd4c0084d2a%2C23063b93020c9177f8953668b4e748b4%2C91ab7b1ddfb09dd2c09d48761a5ba4ec%2C4d5101b81380d2a500f6821175a37aed%2Ced83592c2edf6258a18c18945c624a7c%2Cb1336ee519f72ccde0cef8329c3739a9%2Ccc3d86a60df0190c479b1f7408a95db2%2C2a793161ed2519407e61789fae0f1181%2C5def467f91602496c3053d796c145e0f%2Ca5fdb9749ab3a37e1953c1862fe7ffc6%2C571660759a8935b36db0df59e82726db%2C056b870a3dc072f414e33bcf31791d67%2C94ac74be4eb75a40a329e42245f4502d%2Cc66b38307f4d648123ebc80fbec6def0%2C63a394da5eeb89035a56ef520ecc7c39%2C6982c69542b496fc7f4d01df078f5cdb%2C512a96cbc795037b69f9d17bf96810ca%2C92dde5cbfae8a6e006e0145b5a2a6379%2C5ccd661f1b281e1268b015f959e3bbd5%2Ca5a7b61d5d4c5585be44c5b3abf328eb%2Cfa7492e2d05bc6f4637a730db875e3c2%2C5ad0707b8125b827a2454750db14a4a0%2C1694fb3247ae96040e949d9fa978eedc%2C6bd36b10257ef7a5432114a9b9fe7298%2Cdbad4a7a6718f7be75679a601698d875%2C65c81d576b5b39195ce49cfb1fc2d29e%2C25f3ed6c58ee355383caa22193bdc371%2C22663e50c3ccf72f6b6ae5ea383d09ea%2C6d0e47f7071090e21da3b20c655979c6%2C528634fd9f51f92c92c66b9a650ae22d%2C069eb22672fa1327e9e165ebe03bc62c%2Ca12264ee27ee2ae5a1acaf99441d3fba&Limit=300&Fields=Chapters&ExcludeLocationTypes=Virtual&EnableTotalRecordCount=false&CollapseBoxSetItems=false

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Windows
- Virtualization: none
- Clients: Browser
- Browser: Chrome 107
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kiawizard** [comment]
Please do not close the issue, it is very important. The ability to use jellyfin as a music player for folders with 230+ songs is at stake

**Comment by Bond-009** [comment]
Should be fixed by https://github.com/jellyfin/jellyfin-web/pull/4221
