### ISSUE TITLE
Unable to play MPEG4 in browser with remux

### ISSUE THREAD

**Issue by bttd** [jellyfin/jellyfin#8705]
Hi,
I try to set up my jellyfin, to make it able to play mpeg4 encoded series episodes in the browser. And I need some help.
If I start playing a mpeg4 video in the browser, It pops up on the dashboard and shows it remuxed, but the video doesn't start on the other side,  and a pop-up came in, the video format is not supported on device.

**Media Info of the file**

Video
Title: 360p MPEG4 SDR
Codec: MPEG4
Codec tag: XVID
Profile: Advanced Simple Profile
Level: 5
Resolution: 608x352
Aspect ratio: 19:11
Interlaced: No
Framerate: 25
Bitrate: 1479 kbps
Bit depth: 8 bit
Video range: SDR
Video range type: SDR
Pixel format: yuv420p
Ref frames: 1

Audio
Title: MP3 - Stereo
Codec: MP3
Layout: stereo
Channels: 2 ch
Bitrate: 128 kbps
Sample rate: 48000 Hz
Default: No
Forced: No
External: No

**Logs**
https://pastebin.com/awv9fT2j

**FFmpeg Logs**
https://pastebin.com/xzBkHxJN

**Server System (please complete the following information):**
 - OS: Docker on Linux
 - Jellyfin Version: 10.8.7
 - Hardware settings & device: NVENC on GTX1050
 - Reverse proxy: caddy
 
**Client System (please complete the following information):**
 - Device: Macbook Pro intel
 - OS: MACOS 13
 - Client: Web
 - Browser (if Web client): Safari, Chrome
 - Client and Browser Version: 16.1 and 107.0.5304.87

**Comment by sevenrats** [comment]
XVID in an mp4 should technically be possible, but it is a rarely supported combination.  There are almost no xvid mp4s in existence.  I don't know if Jellyfin supports it or not, very few media suites do.  It's advisable to reencode in this case.  If you want to use a browser, go for h264 in an .mp4 or a .ts container.
