### ISSUE TITLE
[Issue]: mp3 files are not shown

### ISSUE THREAD

**Issue by Karmylr** [jellyfin/jellyfin#8712]
### Please describe your bug

i put a mp3 file in the folder. but after freshing the meta data, it wasnt shown

### Jellyfin Version

Other

### if other:

10.8.7

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
Invalid issue, no information provided.

**Comment by Karmylr** [comment]
> Invalid issue, no information provided.

What information do I need to provide?
