### ISSUE TITLE
[Issue]: Installing on raspberry pi 4 installs useless windows dlls instead of jellyfin-web

### ISSUE THREAD

**Issue by mahtjarohst** [jellyfin/jellyfin#8715]
### Please describe your bug

I cannot for the life of me get the jellyfin server to start on a fresh installation on raspberry pi. I ran 'jellyfin' in terminal and it returned this error 

'Main: The server is expected to host the web client, but the provided content directory is either invalid or empty: /usr/lib/jellyfin/bin/jellyfin-web. If you do not want to host the web client with the server, you may set the '--nowebclient' command line flag, or set'hostwebclient=false' in your config settings.'

When you cd to /usr/lib/jellyfin/bin, the jellyfin-web folder is not there, instead there are a bunch of dll files. I'm not running this on Windows, so I am not sure what those are doing there. Nevertheless, the jellyfin-web folder is not there.

### Jellyfin Version

10.8.0

### if other:

10.8.7

### Environment

```markdown
- OS:raspberry pi OS
- Virtualization:none
- Clients:Browser, Roku, Android
- Browser:Firefox
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
Cannot access logs, the server does not start because jellyfin-web folder is missing.
```

### FFmpeg logs

```shell
Cannot access logs, the server does not start because jellyfin-web folder is missing.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anthonylavado** [comment]
Any particular reason you're running `Jellyfin` rather than starting the service?

For example, `systemctl start jellyfin` (may or may not require `sudo` at the start).

As a reference, the DLLs aren't useless they're actually part of the program. It's just a file extension to reference code, which happened to also be popular on Windows.

**Comment by Bond-009** [comment]
Not enough info/no reponse
