### ISSUE TITLE
[Issue]: Dockerfile / image inconsistencies

### ISSUE THREAD

**Issue by dsiebel** [jellyfin/jellyfin#8717]
### Please describe your bug

I am currently trying to set up Jellyfin on Docker on a Linux host.
Therefore I am using the latest official stable image `jellyfin/jellyfin@sha256:be002e4cb2bc0fd8181f7fef10a337bc75efe55a91467cd5f8c2e8dfdbe86b67`, according to the [documentation](https://jellyfin.org/docs/general/administration/installing#docker) on which I built my own image.
Upon inspecting the official image I pulled I noticed that what I am seeing in the `docker inspect` output does not match the [Dockerfile(s) in the repo](https://github.com/jellyfin/jellyfin/blob/master/Dockerfile.arm64).

For example:
The image has `ENTRYPOINT="/jellyfin/jellyfin"` while the Dockerfile configures
```
ENTRYPOINT ["./jellyfin/jellyfin", \
    "--datadir", "/config", \
    "--cachedir", "/cache", \
    "--ffmpeg", "/usr/bin/ffmpeg"]
```

Also the image's environment variables like `JELLYFIN_DATA_DIR=/config` are nowhere to be found in the aforementioned Dockerfile.

So maybe you can help me clarify my confusion:

Is this expected?
Is there a different Dockerfile being used to build the official images on Dockerhub and if so where can I find it?

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Macos
- Virtualization: Docker
- Clients: iOS, iPadOS
- Browser: Firefox 106.0.5
- FFmpeg Version: docker built-in
- Playback Method:
- Hardware Acceleration: none
- Plugins: none
- Reverse Proxy: traefik (not in use, yet)
- Base URL:
- Networking: Bridge
- Storage: local
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
https://github.com/jellyfin/jellyfin-metapackages
