### ISSUE TITLE
Library access controls do not prevent API listing of all server content

### ISSUE THREAD

**Issue by thornbill** [jellyfin/jellyfin#8718]
### Please describe your bug

Limiting a user's access to libraries does not prevent them from discovering and listing the contents of all libraries on a server via the API. Similarly disabling live TV access does not prevent a user from listing all TV channels via the API.

1. Disable a user's access to all libraries and live TV in the admin dashboard.
2. Verify that the `Policy` returned by `/Users/{USER_ID}` includes:
   * `EnableAllFolders: false`
   * `EnabledFolders: []`
   * `EnableLiveTvAccess: false`
3. Make a request to `/Library/MediaFolders` and observe that a list of ALL libraries are returned.
4. Using a library ID returned in the previous step, make a request to `/Users/{USER_ID}/Items?ParentId={LIBRARY_ID}` and observe that a list of ALL library contents are returned.
5. Make a request to `/LiveTv/Channels` and observe that a list of ALL channels are returned.

### Jellyfin Version

likely all, tested on 10.8.1, 10.8.7, and unstable

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by VideoFX** [comment]
Oh I got this too, i posted this before i noticed your post: https://github.com/jellyfin/jellyfin/issues/8730
