### ISSUE TITLE
Web player can't play AV1 encoded video

### ISSUE THREAD

**Issue by xescure** [jellyfin/jellyfin#8720]
I cannot play this file or any other file that is encoded in the same format with the web client. It works flawlessly through the media player.

**Media Info of the file**
General
Unique ID                                : 318324084940021307647559631213814775470 (0xEF7AFD1CCA7CD64C601FE87CD5427EAE)
Complete name                            : /home/xescure/Downloads/op/One Piece - S07E30 - Where Vivi's Voice Gets Heard! The Hero Descends! HDTV-1080p.mkv
Format                                   : Matroska
Format version                           : Version 4
File size                                : 511 MiB
Duration                                 : 24 min 0 s
Overall bit rate                         : 2 978 kb/s
Movie name                               : [Lia] One Piece - 0121 [1080p]
Writing application                      : Lavf59.27.100
Writing library                          : Lavf59.27.100
ErrorDetectionType                       : Per level 1

Video
ID                                       : 1
Format                                   : AV1
Format/Info                              : AOMedia Video 1
Format profile                           : Main@L4.0
Codec ID                                 : V_AV1
Duration                                 : 24 min 0 s
Bit rate                                 : 7 978 kb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Bits/(Pixel*Frame)                       : 0.160
Stream size                              : 1.34 GiB
Writing library                          : Lavc59.37.100 libsvtav1
Default                                  : Yes
Forced                                   : No
Color range                              : Limited

Audio
ID                                       : 2
Format                                   : Opus
Codec ID                                 : A_OPUS
Duration                                 : 24 min 0 s
Bit rate                                 : 128 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 43.066 FPS (1115 SPF)
Bit depth                                : 32 bits
Compression mode                         : Lossy
Delay relative to video                  : -7 ms
Stream size                              : 22.0 MiB (4%)
Writing library                          : Lavc59.37.100 libopus
Language                                 : Japanese
Default                                  : Yes
Forced                                   : No

Text
ID                                       : 3
Format                                   : ASS
Codec ID                                 : S_TEXT/ASS
Codec ID/Info                            : Advanced Sub Station Alpha
Duration                                 : 23 min 47 s
Bit rate                                 : 65 b/s
Count of elements                        : 208
Compression mode                         : Lossless
Stream size                              : 11.2 KiB (0%)
Writing library                          : Lavc59.37.100 ssa
Language                                 : English
Default                                  : Yes
Forced                                   : No

**Logs**
[Logs](https://pastebin.com/KaSWTP1y)

**FFmpeg Logs**
[Logs](https://pastebin.com/90M7zjCw)

**Stats for Nerds Screenshots**
![image](https://user-images.githubusercontent.com/12898109/200896882-568e74c0-3a8a-454f-bd1c-2c466bd4a45e.png)

**Server System (please complete the following information):**
 - OS: Docker on linux
 - Jellyfin Version: 10.8.7
 - Hardware settings & device: No hardware acceleration
 - Reverse proxy: None
 - Other hardware notes: None
 
**Client System (please complete the following information):**
 - Device: Laptop
 - OS: Kubuntu
 - Client: Web
 - Browser (if Web client): Firefox
 - Client and Browser Version: Firefox 106.0.5 (64-bit)

**Comment by AeroBliss** [comment]
I am running into this exact issue.
