### ISSUE TITLE
[Issue]: TV show episodes split in multiple parts are listed in wrong order

### ISSUE THREAD

**Issue by Fedec96** [jellyfin/jellyfin#8750]
### Please describe your bug

Sometimes show on Blu-ray discs are split differently compared to how they're listed on your favorite movies/shows database. "The Good Place" is the perfect example. On TMDB season 3 has 12 episodes as episodes 1 and 2 are merged in one. But they're two separate episodes on disc. I successfully had them listed as 2 parts in Jellyfin but they're listed in the wrong order.

Running 10.8.7 on Synology DSM 7.1 & Docker.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Synology DSM 7.1
- Virtualization: Docker
```

### Please attach any screenshots here

![Screenshot from 2022-11-15 09-24-32](https://user-images.githubusercontent.com/16012592/201868398-0c30a49d-e6e0-4fe6-842f-48528a4b16eb.png)

![Screenshot from 2022-11-15 09-24-48](https://user-images.githubusercontent.com/16012592/201868376-93fc0d87-697d-43ff-8607-6b8f6c0f869a.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cvium** [comment]
They are not supposed to be listed as 2 parts if it's a single file. What you have done here is unsupported.

**Comment by Fedec96** [comment]
Thanks for your answer. So, if I understand it correctly, there's NO way to tell Jellyfin an episode is split in two parts, regardless of what I specifically did as a workaround?

**Comment by cvium** [comment]
I think your current workaround is the only option right now

**Comment by SenorSmartyPants** [comment]
I just ran into this myself and found out that JF actually does currently support tv episode file stacking, but it was not documented. 

So I updated the [documentation](https://jellyfin.org/docs/general/server/media/shows/#episodes-split-across-multiple-parts). You will get 1 episode in your season list, if you click into the episode there will be "Additional Parts" listed if you follow the naming guide.

**Comment by Fedec96** [comment]
> 

Brilliant! Thanks. Worked like a charm:

`The Good Place - S03E01 - Blu-ray - Part 1.mkv`
`The Good Place - S03E01 - Blu-ray - Part 2.mkv`

The second part is showing as additional part with the name `The Good Place - S03E01 - Blu-ray - Part 2`.

**Comment by SenorSmartyPants** [comment]
You can change the name of the second part manually by using edit metadata, if you want.
