### ISSUE TITLE
[Issue]: metadate not being grabbed and updating episode names or images

### ISSUE THREAD

**Issue by coreybruce** [jellyfin/jellyfin#8762]
### Please describe your bug

Jellyfin isn't fully grabbing meta data, correctly changing episode titles or grabbing show images so I have had to update series titles, images etc myself. Noticed this happening after 2 versions ago of jellyfin.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Manjaro
- Virtualization: none
- Clients: Jellyfin official app
- Browser: N/A
- FFmpeg Version:  4.4.1-4
- Playback Method: 
- Hardware Acceleration:
- Plugins: none
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Please attach any screenshots here

![image](https://user-images.githubusercontent.com/8393780/202292427-0fda5eb4-8de8-4751-92b7-d93633b08beb.png)

![image](https://user-images.githubusercontent.com/8393780/202292565-d4fd8093-9fe5-446f-bf5a-b57be5eaf2ac.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by potatodiet** [comment]
I copied your South Park example with the following filesystem layout and didn't have any issues with Jellyfin grabbing the metadata. Can you upload your logs?

    TV//South Park/Season 1:
    South.Park.S01E01.Cartman.Gets.An.Anal.Probe.1080p.Bluray.AV1.Opus.AV1D.mov
    South.Park.S01E02.Weight.Gain.4000.mov
    South.Park.S01E03.Volcano.mov

**Comment by coreybruce** [comment]
> I copied your South Park example with the following filesystem layout and didn't have any issues with Jellyfin grabbing the metadata. Can you upload your logs? Also, try using the latest version which right now is 10.8.8
> 
> ```
> TV//South Park/Season 1:
> South.Park.S01E01.Cartman.Gets.An.Anal.Probe.1080p.Bluray.AV1.Opus.AV1D.mov
> South.Park.S01E02.Weight.Gain.4000.mov
> South.Park.S01E03.Volcano.mov
> ```

Hey thanks for the reply, I think a couple jellyfin updates ago they resolved this because I don't have been the issue now.
