### ISSUE TITLE
[Issue]: file /usr/lib/firewalld/services/jellyfin.xml from install of firewalld-1.2.1-1.fc37.noarch conflicts with file from package jellyfin-server-10.8.7-1.fc36.x86_64

### ISSUE THREAD

**Issue by Nodens-** [jellyfin/jellyfin#8767]
### Please describe your bug

This is probably known to the Fedora RPM maintainer but can't hurt to note it here just in case it's not.

Apparently `firewalld-1.2.1-1.fc37.noarch` package that comes with `F37`, which released yesterday, is packing a `jellyfin.xml` firewall service definition file by default. This poses an issue as it prevents upgrading to F37 with Jellyfin installed.

### Jellyfin Version

Other

### if other:

10.8.7-1

### Environment

```markdown
- OS:Fedora 36
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
https://github.com/jellyfin/jellyfin/issues/8587
