### ISSUE TITLE
LG WEBOS App - Wrong language is played when playing HEVC 4K HDR directly, when transcoding everything is OK

### ISSUE THREAD

**Issue by Otako77** [jellyfin/jellyfin#8769]
Hello, everyone,
The following problem: When a 4K HDR HEVC Main 10 film is played directly, the wrong language is played. If I want to hear German, I have to select 2 audio tracks higher. If the film is transcoded to H264, the problem does not exist.
![IMG_0998](https://user-images.githubusercontent.com/88830944/202562575-e818e1de-5856-413f-b1d6-fa9f36dcaca2.jpeg)

I can't use the first 2 audio tracks. When the first audio track is selected, I can only hear the third. Does TRUEHD matter?

Server: Linux Ubuntu 22.04.01 Jellyfin 10.8.7, Hardware: I3 6100, 8 GB, GTX 1650 Driver 5.20

Player: WebOS 6 LG C1 77

 My M1 Mac Air doesn't have the problem. Everything is fine here.
<img width="1440" alt="Bildschirmfoto 2022-11-17 um 22 27 50" src="https://user-images.githubusercontent.com/88830944/202563595-6690524a-4179-41b4-854d-d58b7965bd97.png">

The log says AudioStreamIndex=5 but it is definitely index 7. The first two audio tracks are TRUEHD. These may not be counted by the Jellyfin Player on the LG TV.

[2022-11-17 21:32:41.337 +00:00] [INF] StreamBuilder.BuildVideoItem( Profile="Anonymous Profile", Path="/media/mediahdd1/Filme/Hollywood/DUNE.mkv", AudioStreamIndex=5, SubtitleStreamIndex=-1 ) => ( PlayMethod=DirectPlay, TranscodeReason=0 ) "media:/videos/a53af67d-6166-b9d5-c271-95e63faa3b4f/stream.mkv?MediaSourceId=a53af67d6166b9d5c27195e63faa3b4f&Static=true&VideoCodec=hevc&AudioCodec=ac3&AudioStreamIndex=5&api_key=<token>&SubtitleMethod=Encode&Tag=f75efd13696685804fa3523eb2fc52f1"

**Media Info of the file**

**Logs**

**FFmpeg Logs**

**Stats for Nerds Screenshots**

**Server System (please complete the following information):**
 - OS: [e.g. Docker on Linux, Docker on Windows, Debian, Windows]
 - Jellyfin Version: [e.g. 10.0.1]
 - Hardware settings & device: [e.g. NVENC on GTX1060, VAAPI on Intel i7 8700K]
 - Reverse proxy: [e.g. no, nginx, apache, etc.]
 - Other hardware notes: [e.g. Media mounted in CIFS/SMB share, Media mounted from Google Drive]
 
**Client System (please complete the following information):**
 - Device: [e.g. Apple iPhone XS, Xbox One S, LG OLED55C8, Samsung Galaxy Note9, Custom HTPC]
 - OS: [e.g. iOS, Android, Windows, macOS]
 - Client: [e.g. Web/Browser, webOS, Android, Android TV, Electron]
 - Browser (if Web client): [e.g. Firefox, Chrome, Safari]
 - Client and Browser Version: [e.g. 10.3.4 and 68.0]

**Comment by tomikaka22** [comment]
Relevant issue: https://github.com/jellyfin/jellyfin-webos/issues/85

**Comment by colemar** [comment]
I can confirm this issue is still present with Jellyifin app version 1.1.2 on WebOS 5.4.2-2601.
No problem using WebOS browser on the same LG TV device.
No problem using Edge browser on Windows.

**Comment by Anulo2** [comment]
Still present on latest webos and jellyin. Can choose the language but it does not get applied

**Comment by akritm** [comment]
Still same issue, occuring only on LG TV (WebOS 5.50.00). The TV itself supports DTS-HS tracks.

**Comment by felix920506** [comment]
Please report this issue to the WebOS client repo. https://github.com/jellyfin/jellyfin-webos
