### ISSUE TITLE
Jellyfin using number instead of filename when no metadata available for episode titles

### ISSUE THREAD

**Issue by wickedfable** [jellyfin/jellyfin#8776]
I recently updated my Jellyfin server from 10.7.6 to 10.8.7. In 10.7.6, I had a show that had no proper metadata to pull from which Jellyfin used to populate the episode titles with the filename for. Now, in 10.8.7, Jellyfin will use a number for the title instead, which I assume is the episode number.

As an example, for a file named "66. This Day is Great S22E66.mkv", Jellyfin 10.7.6 would name the episode "66. This Day is Great S22E66".  In 10.8.7, the episode is being named "66" instead. So the filename isn't being used correctly as a title anymore it seems.

**Comment by justinbyoung** [comment]
I have a similar issue with any show with a number in the title, Jellyfin sorts all episodes into a single series based on that number.

e.g. Avenue 5, all episodes are sorted into Series 5, and 8 Out Of 10 Cats Does Countdown, all episodes are sorted into Series 8.

**Comment by wickedfable** [comment]
![2023-03-14 11_25_41-Jellyfin_-_Google_Chrome](https://user-images.githubusercontent.com/1691076/225051098-635268f2-6f91-4322-b6f2-07072ae85ca6.png)
![2023-03-14 11_25_52-Jellyfin_-_Google_Chrome](https://user-images.githubusercontent.com/1691076/225051100-ad55e19b-0bdb-40ff-bc08-40e27ea841d9.png)

Thought I would add some screenshots to give a better idea of what's happening. You can see one is using the full file name, which is what Jellyfin used to be able to do, but the other is just using a number for the episode/file instead.
