### ISSUE TITLE
[Issue]: Doesn't prevent Windows from sleeping with active streams

### ISSUE THREAD

**Issue by lsrom** [jellyfin/jellyfin#8780]
### Please describe your bug

Server is running on Windows desktop which is set to sleep after 20 minuts of idle. Jellyfin server should prevent Windows from sleeping when there are active streams.

### Jellyfin Version

Other

### if other:

10.8.5

### Environment

```markdown
- OS: Windows 10
- Virtualization: no
- Clients: Any client
```

### Jellyfin logs

```shell
No logs, this is not a crash just missing functionality.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nielsvanvelzen** [comment]
This is not a bug but a [feature request](https://features.jellyfin.org/posts/581/prevent-os-from-sleeping-hibernating-while-streaming)
