### ISSUE TITLE
[Issue]: Cannot switch language

### ISSUE THREAD

**Issue by LaT3St** [jellyfin/jellyfin#8781]
### Please describe your bug

I just installed Jellyfin and encountered a problem with my .mp4 which has multiple languages as different audio tracks. The switching seems to occur but then the first audio track just continuous as if i hadn't changed anything.

### Jellyfin Version

Other

### if other:

10.8.7

### Environment

```markdown
- OS: Arch Linux
- Virtualization: Docker
- Clients: Browser
- Browser: Firefox
- FFmpeg Version: -
- Playback Method: Direct Play
- Hardware Acceleration: none
- Plugins:none
- Reverse Proxy: Traefik
- Base URL: none
- Networking: Bridge
- Storage: cloud
```

### Jellyfin logs

```shell
jellyfin  | [02:44:13] [WRN] [8] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from https://!PRIVATE!/Videos/fbbad5a283fd0bd612a93f6ba5a60b6c/stream.mp4?Static=true&mediaSourceId=fbbad5a283fd0bd612a93f6ba5a60b6c&deviceId=TW96aWxsYS81LjAgKFgxMTsgTGludXggeDg2XzY0OyBydjoxMDcuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC8xMDcuMHwxNjY4OTk4NTU0NDUy&api_key=0cf1c81dbf41416387a94d22606f3ab1&Tag=b12d7a8830772e64aae82545856919ac to !PRIVATE! in 0:00:00.7355049 with Status Code 206
```

### Please attach any browser or client logs here

A bunch of this:

Requesting url without automatic networking: https://!PRIVATE!/Sessions/Playing/Progress

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by LaT3St** [comment]
Is #762 or #8350 related?

**Comment by ThomasPGH** [comment]
I've got the same issue with Firefox (Windows). When I use the Jellyfin Media Player (Windows) switching the language works.
So, it might be related to the web client and not Jellyfin itself.

**Comment by pgartl** [comment]
Same issue with app on GoogleTV (Sony Bravia)
