### ISSUE TITLE
Server injects HTML that turns off most security features in a browser

### ISSUE THREAD

**Issue by sparky8251** [jellyfin/jellyfin#879]
**Describe the bug**
[This bit of code turns off all kinds of safety settings whenever index.html (the top level of the web UI) is loaded](https://github.com/jellyfin/jellyfin/blob/eb4b7051676b7493a57a99a821d5dd38bd9d4919/MediaBrowser.WebDashboard/Api/PackageCreator.cs#L138).

**Expected behavior**
Web app should function properly without disabling every security function known to man.

**Comment by dkanada** [comment]
resolved in #2966
