### ISSUE TITLE
Question: Will the Jellyfin client for LG TVs be further developed on the basis of webos?

### ISSUE THREAD

**Issue by Hallo951** [jellyfin/jellyfin#8800]
Hello,

I am an enthusiastic jellyfin user. I use an LG TV to watch films and would like to use the jellyfin client for webos on it. For more than 4 months I have been pointing out various problems and errors on the github page of jellyfin webos, which make an effective use of jellyfin on an LG TV very difficult or it is only possible with cutbacks. Also, if you look at the development of the jellyfin client on webos in general, it seems that there is no more progress in this area. This is a great pity, as jellyfin is a great piece of software in itself, but it can only be used effectively if the corresponding clients are not only supported but also run without errors.

Is it at all likely that the Jellyfin client for webos will be developed further?

**Comment by crobibero** [comment]
The client is under development. Most changes take place in the web repo.

This is the server repo.
