### ISSUE TITLE
[Issue]: gpg: no valid OpenPGP data found.

### ISSUE THREAD

**Issue by teja3go** [jellyfin/jellyfin#8802]
### Please describe your bug

When i tried to install jellyfin on ubuntu after the first command from docs

sudo mkdir /etc/apt/keyrings
curl -fsSL https://repo.jellyfin.org/$( awk -F'=' '/^ID=/{ print $NF }' /etc/os-release )/jellyfin_team.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/jellyfin.gpg

it gave me this

curl: (22) The requested URL returned error: 404
                                                gpg: no valid OpenPGP data found.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS:Ubuntu 20.04
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by teja3go** [comment]
i found the solution

**Comment by josephchigiz** [comment]
Please give the solution

**Comment by teja3go** [comment]
Actually it wasn't a big.
As soon as I realised that I cooked the Issey myself.
I use Linux mint and i thought that entering Ubuntu command will install it fine but it did not.
So i modified the command where it automatically grabs the Ubuntu version and pipe it to other command and it fixed for me.
