### ISSUE TITLE
Certain data locations are not using `datadir` properly

### ISSUE THREAD

**Issue by joshuaboniface** [jellyfin/jellyfin#881]
**Describe the bug**
Some elements of the media library (cache, or download data perhaps - not sure) continue to try to use the default system location (in Debian, `/var/lib/jellyfin`) even when the `--datadir` option is passed with a different value.

Did some digging and was able to confirm that this issue has two completely different symptoms:

Most of the time, rescanning a library just fails in the browser since the library `itemId` can't be found - there are no server-side errors but the API client must be trying to grab this from a folder that it expects at `/var/lib/jellyfin`, but is not finding (despite the `datadir` being elsewhere).

The second symptom occurrs if a library starts to scan. If the original location does not exist, this results in an occasional error stack trace indicating that ` /var/lib/jellyfin/root/default/<library>` can't be found.

All of these issues disappear if the `datadir` is restored to the default.

**To Reproduce**
1. Move the default data directory to a new location (do not recreate the original data location):
    ```
    $ sudo systemctl stop jellyfin
    $ sudo mv /var/lib/jellyfin /srv/jellyfin
    ```
1. Set `--datadir` on the command line (`/etc/default/jellyfin`) to the new location:
    ```
    $ grep 'DATA_DIRECTORY' /etc/default/jellyfin
    JELLYFIN_DATA_DIRECTORY="/srv/jellyfin"
    ```
1. Start Jellyfin and rescan a library.

**Expected behavior**
No errors, all data is written to `/srv/jellyfin`, all lookups are from `/srv/jellyfin`.

**Logs**

Failure to scan libraries, in browser:
```
Error: null itemId
apiclient.js:739:28
ApiClient.prototype.refreshItem
http://test5:8096/web/bower_components/emby-apiclient/apiclient.js:739:28
onSubmit/<
http://test5:8096/web/bower_components/emby-webcomponents/refreshdialog/refreshdialog.js:79:13
forEach self-hosted:261:13 onSubmit
http://test5:8096/web/bower_components/emby-webcomponents/refreshdialog/refreshdialog.js:78:9
onSubmit self-hosted:977:17 
```

Occasional error when scanning actually results:
```
Feb 11 21:28:02 jf1 jellyfin[515]: [21:28:02] [ERR] Error refreshing owned items for /var/lib/jellyfin/root/default/Movies 
Feb 11 21:28:02 jf1 jellyfin[515]: System.IO.DirectoryNotFoundException: Could not find a part of the path '/var/lib/jellyfin/root/default/Movies'.
Feb 11 21:28:02 jf1 jellyfin[515]:    at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound) 
Feb 11 21:28:02 jf1 jellyfin[515]:    at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, EnumerationOptions options)
Feb 11 21:28:02 jf1 jellyfin[515]:    at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options)
Feb 11 21:28:02 jf1 jellyfin[515]:    at System.IO.Enumeration.FileSystemEnumerableFactory.DirectoryInfos(String directory, String expression, EnumerationOptions options)
Feb 11 21:28:02 jf1 jellyfin[515]:    at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
Feb 11 21:28:02 jf1 jellyfin[515]:    at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemEntries(String path, Boolean recursive) in /jellyfin/Emby.Server.Implementations/IO/ManagedFileSystem.cs:line 782
Feb 11 21:28:02 jf1 jellyfin[515]:    at MediaBrowser.Controller.Providers.DirectoryService.GetFileSystemEntries(String path) in /jellyfin/MediaBrowser.Controller/Providers/DirectoryService.cs:line 28
Feb 11 21:28:02 jf1 jellyfin[515]:    at MediaBrowser.Controller.IO.FileData.GetFilteredFileSystemEntries(IDirectoryService directoryService, String path, IFileSystem fileSystem, IServerApplicationHost appHost, ILogger logger, ItemResolveArgs args, Int32 flattenFolderDepth, Boolean resolveShortcuts) in /jellyfin/MediaBrowser.Controller/IO/FileData.cs:line 56
Feb 11 21:28:02 jf1 jellyfin[515]:    at MediaBrowser.Controller.Entities.CollectionFolder.CreateResolveArgs(IDirectoryService directoryService, Boolean setPhysicalLocations) in /jellyfin/MediaBrowser.Controller/Entities/CollectionFolder.cs:line 281
Feb 11 21:28:02 jf1 jellyfin[515]:    at MediaBrowser.Controller.Entities.CollectionFolder.GetFileSystemChildren(IDirectoryService directoryService) in /jellyfin/MediaBrowser.Controller/Entities/CollectionFolder.cs:line 163
Feb 11 21:28:02 jf1 jellyfin[515]:    at MediaBrowser.Controller.Entities.BaseItem.RefreshMetadata(MetadataRefreshOptions options, CancellationToken cancellationToken) in /jellyfin/MediaBrowser.Controller/Entities/BaseItem.cs:line 1317   
```

**Screenshots**

**System (please complete the following information):**
 - OS: Debian
 - Browser: Firefox 64
 - Jellyfin Version: 10.2.0-rc1

**Additional context**
N/A

**Comment by joshuaboniface** [comment]
More testing: this is actually a symptom of #404 a.k.a. the "hardcoded database paths" issue. Updating the database as in https://github.com/jellyfin/jellyfin/issues/404#issuecomment-451640691 fixes the issue. Updated script that works (and is more generic):

```
$ cat fix-db.sh
#!/bin/sh
db=${1:-/var/lib/jellyfin/data/library.db}
oldpath=${2:-/var/lib/emby-server}
newpath=${3:-/var/lib/jellyfin}
sqlite3 ${db} << SQL
UPDATE Chapters2
SET ImagePath=REPLACE(ImagePath, '${oldpath}', '${newpath}');
UPDATE TypedBaseItems
SET Path=REPLACE(Path, '${oldpath}', '${newpath}');
UPDATE TypedBaseItems
SET data=REPLACE(data, '${oldpath}', '${newpath}');
SQL
```

**Comment by Yetangitu** [comment]
This might be an ancient, dead thread but the issue seems to be alive still in 10.7.0. Even after changing every occurrence of the original data path (`/var/lib/jellyfin`) to the new (`/srv/jellyfin`) in all places which contain that path there are some parts of the web UI which refuse to function:

 - Dashboard is empty
 - Scheduled Tasks does not load, shows a spinner

Are there more hard-coded paths, is part of the code using a hashed representation of the path in some way, ...?

The log stays silent on this issue, even with debug logging enabled.
