### ISSUE TITLE
[Issue]: IMDb ratings are inaccurate

### ISSUE THREAD

**Issue by CutterXYZ** [jellyfin/jellyfin#8816]
### Please describe your bug

IMDb ratings in Jellyfin are different from the ratings visible on the website.
For example, Pulp Fiction is rated 8.9 on IMDb and 8.5 in Jellyfin.
Updating the metadata doesn't change it.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS:Win10
- Virtualization:no
- Clients:Jellyfin Media Player
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shadowghost** [comment]
We don't pull ratings from IMDb directly. They are part of the data coming from other 3rd party sites like TMDb. We're limited to what they provide since scraping the IMDb website is a TOS validation.

**Comment by neingeist** [comment]
I was under the impression that the ratings in Jellyfin are the TMDB ratings? I consistently get the same values as visible on TMDB as user score, divided by 10. (I.e. 20% user score becomes 2.0). Sorting by IMDb rating is actually sorting by TMDB ratings, so this is technically a UI bug, I think. The API results call it "CommunityRating".

Probably depending on configuration, I just try to figure this stuff out.

**Comment by neingeist** [comment]
In other words: What you see is a community rating, in my configuration this means the TMDB user score/rating, in yours probably too. Not the IMDB rating. (Sadly, I must say, because the TMDB ratings are not always as helpful as the IMDB ratings.)

**Comment by neingeist** [comment]
Ah, if I "up" the  priority of the OMDB API ("Metadata downloaders", put OMDB before TMDB) I do get IMDB ratings, provided by OMDB. These are not up-to-date, but for me, it may be good enough.
