### ISSUE TITLE
[Issue] Can't read Freebox TV playlist.m3u

### ISSUE THREAD

**Issue by Xenoxis** [jellyfin/jellyfin#8818]
Hello, I have a freebox where my server is connected to, i want to use the iptv service available with my freebox thats allow to watch tv on any of my devices on my LAN, so i decided to use my JellyFin server which already contains all my movies and series.
But I can't watch any of the TV listed on the m3u file provided by my Freebox, can you help me to fix this issue ?

**Media Info of the file**
The m3u file :
[playlist.m3u.txt](https://github.com/jellyfin/jellyfin/files/10105268/playlist.m3u.txt)

**Logs**
[jellyfin_log.txt](https://github.com/jellyfin/jellyfin/files/10105256/jellyfin_log.txt)

**FFmpeg Logs**

[ffmpeg_log.txt](https://github.com/jellyfin/jellyfin/files/10105235/ffmpeg_log.txt)

**Stats for Nerds Screenshots**
![image](https://user-images.githubusercontent.com/19935648/204321106-99207d96-97e0-418c-a482-d6542342ab48.png)

**Server System (please complete the following information):**
 - OS: Linux (Ubuntu Server 22.02 LTS x64)
 - Jellyfin Version: 10.8.7
 - Hardware settings & device: 2x Intel(R) Xeon(R) CPU   X5690  @ 3.47GHz +  NVIDIA T600
 - Reverse proxy: no
 
**Client System (please complete the following information):**
 - Device: Any compatibles with JellyFin
 - OS: Windows, Android
 - Client: WebBrowser, apps
 - Browser (if Web client): any

**Comment by Xenoxis** [comment]
Hello, someone know why i have this issue ?

**Comment by Xenoxis** [comment]
Hello, i've still received anything about my issue, I have been forgotten ?
@Bond-009 @TelepathicWalrus @icedterminal

**Comment by Xenoxis** [comment]
Up, issue still affecting me.

**Comment by Chr0nos** [comment]
Hi,
i'm having the same issue with jellyfin 10.8.10, (mine is behind a reverse proxy & run from a docker container)

> services-jellyfin-1  | [17:21:43] [INF] [20] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile=Anonymous Profile, Path=rtsp://mafreebox.freebox.fr/fbxtv_pub/stream?namespace=1&service=201&flavour=hd, AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=Transcode, TranscodeReason=ContainerNotSupported, VideoCodecNotSupported ) media:/videos/a88484e4-b402-3f2e-e781-d06cd1162088/master.m3u8?MediaSourceId=2d8c957d36ef16734d480f2a56916453&VideoCodec=h264&AudioCodec=aac,mp3&VideoBitrate=119808000&AudioBitrate=192000&api_key=<token>&LiveStreamId=a17c75760a04e99b68cf766e11316e1c_09efa0d56b934a82adec00a87b837fb0_2d8c957d36ef16734d480f2a56916453&TranscodingMaxAudioChannels=2&RequireAvc=false&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&TranscodeReasons=ContainerNotSupported,%20VideoCodecNotSupported
> services-jellyfin-1  | [17:21:43] [INF] [13] Jellyfin.Api.Controllers.DynamicHlsController: Current HLS implementation doesn't support non-keyframe breaks but one is requested, ignoring that request

it sounds like it would be an issue with the video container or format?
does anyone managed to have it working?

**Comment by Xenoxis** [comment]
Hey, this issue still going on for me, and I've seen this ticket was closed and placed in "Insufficient data" stuff ... Si what additional informations should I provide ?

**Comment by felix920506** [comment]
Please file your issue on this repo. https://github.com/jellyfin/jellyfin-web
