### ISSUE TITLE
Docker Images should be available for Windows Containers

### ISSUE THREAD

**Issue by LogicalPhallacy** [jellyfin/jellyfin#884]
**Is your feature request related to a problem? Please describe.**
Windows Containers allow significantly better performance for Docker when hosted on a Windows Host. We should also provide a Windows Container friendly dockerfile

**Describe the solution you'd like**
It looks like building a windows version would just take a script modification to also import a windows ffmpeg and some system libraries, the buildfile would likely be more straightforward than the current dockerfile.

**Describe alternatives you've considered**
Hosting the Linux container on a windows host works, but it requires full Hyper-V virtualization which comes with security benefits but also with perf overhead.

**Comment by LogicalPhallacy** [comment]
This enhancement is blocked until the issue of missing libraries in windows server nano and core editions can be addressed. Referencing a related emby bug. This also blocks the use of Windows Server Core or Server Nano outside a container without bringing in the required libs from a full windows server. 

#https://github.com/MediaBrowser/Emby/issues/3175

**Comment by sevenrats** [comment]
moved to https://features.jellyfin.org/posts/2353/docker-images-should-be-available-for-windows-containers
