### ISSUE TITLE
[Issue]: Error 'AuthenticationScheme: CustomAuthentication was forbidden' for Infuse when syncing library in 10.8.8

### ISSUE THREAD

**Issue by tanc** [jellyfin/jellyfin#8844]
### Please describe your bug

Infuse client on Apple TV (TVOS) can no longer index the library. This is a breaking change from version Jellyfin 10.8.7 to 10.8.8.

I have reverted to 10.8.7 and confirmed that indexing works with no errors. When on Jellyfin 10.8.8 indexing fails with the log message below in Jellyfin's logs.

Diffing the code between 10.8.7 and 10.8.8 it seems some API authentication has changed. Is this something that can be resolved in Jellyfin or does Infuse need updating?

### Jellyfin Version

Other

### if other:

10.8.8

### Environment

```markdown
- OS: Ubuntu
- Virtualization: Docker
- Clients: Infuse (TVOS)
```

### Jellyfin logs

```shell
[11:07:50] [WRN] [20] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://192.168.1.10:8896/Packages to 192.168.1.177 in 0:00:01.1929737 with Status Code 200
[11:07:50] [INF] [10] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was forbidden.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by firecore** [comment]
A fix for this will be available in the next Infuse release (7.4.9).

https://community.firecore.com/t/indexing-error-with-jellyfin-10-8-8/39834/20
