### ISSUE TITLE
Random playlists fail to play after updating to 10.8.8

### ISSUE THREAD

**Issue by FazeThree71** [jellyfin/jellyfin#8845]
I posted this in the sub on Reddit and was prompted to post this here. 

After updating to 10.8.8 via Portainer, attempting to play random playlists results in a spinning animation that never recovers. I discovered that if I delete and re-create the playlist, that works. As does playing tracks via Artist. This isn't affecting all playlists - just some.

**Logs**
See https://www.klgrth.io/paste/aztd2 

The responder on Reddit stated that the only unusual thing seen was System.FormatException: SongCount is not a valid value for ItemFields.

**Server System (please complete the following information):**
 - OS: Docker on CentOS 
 - Jellyfin Version: 10.8.8
 - Hardware settings & device: TerraMaster F2-221, Celeron J3355
 - Reverse proxy: N/A
 - Other hardware notes: Dual Samsung 870 QVO 2TB SSDs in a Raid-1
 
**Client System (please complete the following information):**
 - Device: Ryzen 5 2600, Asus B450M-A 32GB RAM, GeForce 980Ti
 - OS: Windows 11 x64 22H2 Build 22621.900
 - Client: Web browser, Jellyfin Desktop x64
 - Browser Chrome, Firefox 
 - Client and Browser Version: Chrome 107.0.5304.123, Firefox 107.0.1, Jellyfin Desktop 1.7.1-1

**Comment by tscheney** [comment]
I have this same problem after updating to 10.8.8. I believe the key is that it will spin forever if you try to play a playlist created by another user. I have made new playlists and as soon as I switch users the playlist will no longer play.

**Comment by FazeThree71** [comment]
In my case, I'm logged in as the user who created the playlists (admin). 

I did locate where the playlists are stored (in a Docker) and saved the playlist.xml from one that was messed up. Recreating that and confirming it worked, I exported it again. Doing a diff on them only shows differences on the <Added> and <UserId> tags.  I'm not entirely sure why the <UserId> changed and may see if just updating that manually fixes this so I don't have to completely recreate all of the ones that are busted. 

I'm now on 10.8.9 and the problem is still present.

**Comment by FazeThree71** [comment]
This issue is still present.

**Comment by hunjixin** [comment]
also have this problem, i am sure nothing about permission.

**Comment by felix920506** [comment]
Should be fixed in #9466 , #9746 and #9770 on master.

**Comment by tuxfoo** [comment]
> I have this same problem after updating to 10.8.8. I believe the key is that it will spin forever if you try to play a playlist created by another user. I have made new playlists and as soon as I switch users the playlist will no longer play.

In my case it is the same, this bug only occurs if the playlist was created by another user. (Version 8.12)

**Comment by Shadowghost** [comment]
None of the mentioned fixes are in the current stable release 10.8.x, they will be part of 10.9
