### ISSUE TITLE
[Issue]: Pioneer system shows only "newest" node since Jellyfin 10.8.0

### ISSUE THREAD

**Issue by SuperMario4889** [jellyfin/jellyfin#8858]
### Please describe your bug

Hello,

I have a problem with access via DLNA. Pioneer MRX-5 and Pioneer HM86D access jellyfin via DLNA. Since version 10.8.0, only " Newest" is displayed for music. All other menu items are missing. In addition, only the most recently added album is displayed under "Newest".

![Screenshot_20221205-131129](https://user-images.githubusercontent.com/119861458/205637703-c5a87ad9-f25d-48cd-aab9-7ba67d024f0c.jpg)
![Screenshot_20221205-131134](https://user-images.githubusercontent.com/119861458/205637718-4132ffdb-a118-4d06-9d75-a46adcabdf8a.jpg)
![Screenshot_20221205-131139](https://user-images.githubusercontent.com/119861458/205637733-5413651c-2ccb-4357-9deb-7ea654aa38d1.jpg)
![Screenshot_20221205-132423](https://user-images.githubusercontent.com/119861458/205637751-a9b995c6-5231-43e5-aabe-7a963bf888ea.jpg)

I hope you find the error. Thanks a lot

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rea-ducks** [comment]
Since I'm a new Jellyfin user I can not speak about past versions, but yes, my Pioneer X-HM76 also only shows "Newest" for Jellyfin. While it shows everything for my MiniDLNA server as does foobar2000 for both servers. So there must be something incompatible for the Pioneers.

**Comment by SuperMario4889** [comment]
Unfortunately, the problem still exists.

**Comment by SuperMario4889** [comment]
Unfortunately, the problem still exists (Version 10.8.9).

**Comment by SuperMario4889** [comment]
Unfortunately, the problem still exists (Version 10.8.10).
