### ISSUE TITLE
[Issue]: Scanning TB level of Audiobook library is slow

### ISSUE THREAD

**Issue by J4gQBqqR** [jellyfin/jellyfin#8860]
### Please describe your bug

Related: #8778, #8507, #7206, #3722, #3736, #987, #42

I have a library of audiobooks with 15TB of m4a, mp3, ogg files. Literally on the level of ~ 1 million files.
This is kind of unavoidable as audiobook library tends to have tons more chapters comparing to music albums.

My library hit the performance wall hard on SQLite to the level that Jellyfin is unusable with this library. 
Is there anything I can do currently with this issue?

### Jellyfin Version

Other

### if other:

10.8.8

### Environment

```markdown
- OS: Latest Arch rolling release
- Virtualization: latest Docker release on Arch
- Clients: Browser Web client
- Browser: Firefox/Librewolf
- FFmpeg Version: Linuxserver.io version
- Playback Method: N/A
- Hardware Acceleration: N/A
- Plugins:
- Reverse Proxy: Linuxserver.io SWAG
- Base URL: based on subdomain (no sub directory)
- Networking: Fiber
- Storage: 40TB HDD
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brettpetch** [comment]
I recently had similar issues with sqlite db not keeping up. Have done the following to help the db live in memory a little more. 

Overall performance went from 30s search to about 4s. 

```
sqlite3 library.db

PRAGMA main.page_size = 4096;
PRAGMA main.cache_size=10000;
PRAGMA main.locking_mode=EXCLUSIVE;
PRAGMA main.synchronous=NORMAL;
PRAGMA main.journal_mode=WAL;
PRAGMA main.cache_size=5000;
PRAGMA main.temp_store = MEMORY;
.quit
```

**Comment by J4gQBqqR** [comment]
There is still no good solution to improve performance of SQL library on huge library. We are in the SQLite world.

**Comment by brettpetch** [comment]
> There is still no good solution to improve performance of SQL library on huge library. We are in the SQLite world.

Allegedly devs are working on migration to EFCore but I don't see a roadmap of that anywhere that makes it visible. After they do this it should open possibilities for external dbs if they decide it's appropriate.

**Comment by cvium** [comment]
We are using WAL and some minor optimizations in 10.9 (unstable). Might have an effect.
