### ISSUE TITLE
[Issue]: TV library not displaying New TV shows when added

### ISSUE THREAD

**Issue by VampiricAlien** [jellyfin/jellyfin#8861]
### Please describe your bug

Jellyfin shows a notification that new media has been added but doesn't always show in new tv shows.
Same issue with movies https://github.com/jellyfin/jellyfin/issues/8654 

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Ubuntu 22.04 
- Virtualization: none
- Clients: Web and ATV
- Browser:
- FFmpeg Version: 5.0 (jellyfin)
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy: none
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
None
```

### FFmpeg logs

```shell
None
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by VampiricAlien** [comment]
@iFraan I am unable to disable the plugin, there isn't an option so I deselected the scan option and rescanned but no luck.

**Comment by iFraan** [comment]
Its under the plugins tab. You can both disable and uninstall it.

**Comment by VampiricAlien** [comment]
The 3 dot menu, I only have settings. Is there another way around this or do I have to remove the plugin folder?
