### ISSUE TITLE
[Issue]: Can't install Jellyfin if dotnet is already installed

### ISSUE THREAD

**Issue by ImanolFotia** [jellyfin/jellyfin#8872]
### Can't install Jellyfin if dotnet is already installed

I'm using the latest Fedora 37 and neither package will install alongside the other, i.e. can't install jellyfin if dotnet is installed, and can't install dotnet if jellyfin is installed

What I'm doing:

`sudo dnf install jellyfin`

What I'm getting:
`Error: Transaction test error:
  file /usr/lib/.build-id/68/73960cdb17942ebcbf54311816fe30b0ae2292 from install of jellyfin-server-10.8.8-1.fc37.x86_64 conflicts with file from package dotnet-sdk-6.0-6.0.111-1.fc37.x86_64
`

I'm using Jellyfin 10.8.8

### My system:

OS: Fedora Linux 37 (Workstation Edition) x86_64 
Kernel: 6.0.11-300.fc37.x86_64 
Shell: bash 5.2.9 
DE: GNOME 43.1 

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Fedora Linux 37 (Workstation Edition) x86_64 
- Virtualization: No
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

**Comment by Seeings** [comment]
I'm having the same issue when updating from jellyfin-server-10.8.7-2.fc36 to 10.8.8-1.fc37 (I recently upgraded from Fedora 36 to Fedora 37 so it's using the old fc36 install of 10.8.7-2)

I tried uninstalling dotnet-sdk but then I just get that it can't open the jellyfin-server*.rpm.
Otherwise I'm getting the same error as ImanolFotia.

**Comment by Seeings** [comment]
This problem persist with the latest 10.8.9 update.

**Comment by Seeings** [comment]
I seem to have been able to install the 10.8.9 update now after removing dotnet (uninstalling the old jellyfin-server-10.8.7-2.fc36 with it) and renaming the folder /usr/lib64/jellyfin-web to jellyfin-web.backup. Seeing as the new version seems to be using a symlink to /usr/share/jellyfin-web instead. So it had problem with the old jellyfin-web folder existing.
