### ISSUE TITLE
docker+jellyfin 视频转码调用硬解时，显示不支持硬件解码（实际支持硬件解码），显示信息错误。

### ISSUE THREAD

**Issue by allenbao** [jellyfin/jellyfin#8873]
![52D93DBA-4AC5-467c-824A-C992061FB0AE](https://user-images.githubusercontent.com/3050209/206364891-ee71a5a9-2f7f-476b-a738-68b87886f167.png)
问题：docker+jellyfin 视频转码调用硬解时，显示信息为不支持硬件解码（实际支持硬件解码），显示信息错误，如图。
期待：docker+jellyfin 视频转码调用硬解时，若支持硬件解码，则显示信息也同样展示为支持硬件解码。

**Comment by fuxin052** [comment]
我有类似的问题
出现问题的视频 https://drive.google.com/file/d/1-mz29xN5yr_FkbufHcESdVwCN_HHe9KL/view?usp=sharing
系统: windows10
浏览器: chrome108.0.5359.99（64 位）
jellyfin版本: 10.8.7 docker amd64

视频格式为hevc main10 / aac 浏览器可以直接播放, 但是用jellyfin播放时 会被转码为h264
当我取消用户的转码权限时, 视频会被转封装

**Comment by microbiolee** [comment]
> 我有类似的问题 出现问题的视频 https://drive.google.com/file/d/1-mz29xN5yr_FkbufHcESdVwCN_HHe9KL/view?usp=sharing 系统: windows10 浏览器: chrome108.0.5359.99（64 位） jellyfin版本: 10.8.7 docker amd64
> 
> 视频格式为hevc main10 / aac 浏览器可以直接播放, 但是用jellyfin播放时 会被转码为h264 当我取消用户的转码权限时, 视频会被转封装

我也有相同的问题，10.8.8的jellyfin服务端，然后无论在Safari还是在chrome（版本120）播放jellyfin上的hevc，都会视频和音频不支持导致转码。不过我发现hevc main的视频是可以串流的，hevc main 10的是必须要转码的。这是为何？
