### ISSUE TITLE
[Issue]: TV: "Clips" folder contents added to episode list instead of "Special Features"

### ISSUE THREAD

**Issue by listy-bit** [jellyfin/jellyfin#8878]
### Please describe your bug

Instead of the documented function of a season's "Clips" folder which is to use its contents as a category of Special Feature for that season, the contents are added as episodes -- and not just in the relevant season either. I have Season 16/Clips/ files turning up as episodes in Season 16 AND Season 19.

### Jellyfin Version

Other

### if other:

10.8.8

### Environment

```markdown
- OS: Ubuntu
- Virtualization: None
- Clients: Browser, iOS, Kodi, JellyCon
- Storage: local
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Bond-009** [comment]
Should be fixed on master branch by #8638
