### ISSUE TITLE
[Issue]: Synology nvidia card, docker NVENC cannot call

### ISSUE THREAD

**Issue by xdhgsq** [jellyfin/jellyfin#8880]
### Please describe your bug

I have an nvidia Tesla P4 card, which can be recognized on Synology, nvidia-smi can see the graphics card information, I created jellyfin using Docker version 20.10.3, from nyanmisaka/jellyfin,

### 1. docker command
          docker run -d --name jellyfin_2 \
          -p 8096:8099 \
          -e NVIDIA_VISIBLE_DEVICES=all \
          -v /volume2/16TB/jellfin_2/config:/config \
          -v /volume2/16TB/jellfin_2/cache:/cache \
          -v /volume2/16TB/video:/video \
          -v /usr/local/bin/nvidia-smi:/usr/local/bin/nvidia-smi \
          -v/usr/local/bin/nvidia-cuda-mps-control:/usr/local/bin/nvidia-cuda-mps-control \
          -v /usr/local/bin/nvidia-persistenced:/usr/local/bin/nvidia-persistenced \
          -v /usr/local/bin/nvidia-cuda-mps-server:/usr/local/bin/nvidia-cuda-mps-server \
          -v /usr/local/bin/nvidia-debugdump:/usr/local/bin/nvidia-debugdump \
          -v /usr/lib/libnvcuvid.so:/usr/lib/libnvcuvid.so \
          -v /usr/lib/libnvidia-cfg.so:/usr/lib/libnvidia-cfg.so \
          -v /usr/lib/libnvidia-compiler.so:/usr/lib/libnvidia-compiler.so \
          -v /usr/lib/libnvidia-eglcore.so:/usr/lib/libnvidia-eglcore.so \
          -v /usr/lib/libnvidia-encode.so:/usr/lib/libnvidia-encode.so \
          -v /usr/lib/libnvidia-fatbinaryloader.so:/usr/lib/libnvidia-fatbinaryloader.so \
          -v /usr/lib/libnvidia-fbc.so:/usr/lib/libnvidia-fbc.so \
          -v /usr/lib/libnvidia-glcore.so:/usr/lib/libnvidia-glcore.so \
          -v /usr/lib/libnvidia-glsi.so:/usr/lib/libnvidia-glsi.so \
          -v /usr/lib/libnvidia-ifr.so:/usr/lib/libnvidia-ifr.so \
          -v /usr/lib/libnvidia-ml.so:/usr/lib/libnvidia-ml.so \
          -v /usr/lib/libnvidia-opencl.so:/usr/lib/libnvidia-opencl.so \
          -v /usr/lib/libnvidia-ptxjitcompiler.so:/usr/lib/libnvidia-ptxjitcompiler.so \
          -v /usr/lib/libnvidia-tls.so:/usr/lib/libnvidia-tls.so \
          --device /dev/dri:/dev/dri \
          --device /dev/nvidia0:/dev/nvidia0 \
          --device /dev/nvidiactl:/dev/nvidiactl \
          --device /dev/nvidia-uvm:/dev/nvidia-uvm \
          --device /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools \
          --restart unless-stopped \
          nyanmisaka/jellyfin:latest
`
### 2. After successful creation
          docker exec -it [container name] /bin/bash
           ldconfig

### 3. docker execute
           root@705fd981254d:/# nvidia-smi
           Fri Dec  9 09:45:47 2022
           +-----------------------------------------------------------------------------+
           | NVIDIA-SMI 440.44       Driver Version: 440.44       CUDA Version: N/A      |
           |-------------------------------+----------------------+----------------------+
           | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
           | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
           |===============================+======================+======================|
           |   0  Tesla P4            Off  | 00000000:01:00.0 Off |                    0 |
           | N/A   39C    P0    23W /  75W |      0MiB /  7611MiB |      3%      Default |
           +-------------------------------+----------------------+----------------------+

           +-----------------------------------------------------------------------------+
           | Processes:                                                       GPU Memory |
           |  GPU       PID   Type   Process name                             Usage      |
           |=============================================================================|
           |  No running processes found                                                 |
           +-----------------------------------------------------------------------------+

### 4. As a result, NVENC cannot call
![image](https://user-images.githubusercontent.com/94951545/206673890-c2415c80-35c9-4193-84bc-e8c4c1d19810.png)

![image](https://user-images.githubusercontent.com/94951545/206673810-d439bbfa-efa3-4b97-ab2f-f4f2f14b2444.png)

### Jellyfin Version

10.8.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nyanmisaka** [comment]
> Minimum required driver version since Jellyfin 10.8:

> Linux: 470.57.02
> Windows: 471.41

https://jellyfin.org/docs/general/administration/hardware-acceleration/#nvidia-nvenc

**Comment by xdhgsq** [comment]
> > Minimum required driver version since Jellyfin 10.8:
> 
> > Linux: 470.57.02
> > Windows: 471.41
> 
> https://jellyfin.org/docs/general/administration/hardware-acceleration/#nvidia-nvenc

我已经在docker上成功调用了群辉上的独显，详细折腾连接放底下了，感谢你的回复
群辉独显N卡，jellyfin成功调用转码
https://www.right.com.cn/forum/thread-8267275-1-1.html
