### ISSUE TITLE
[Issue]: Metadata refresh modes need a clearer description

### ISSUE THREAD

**Issue by abstractionmage** [jellyfin/jellyfin#8882]
In the left sidebar, clicking at "Dashboard", then on "Libraries", then clicking the three dots on one of my libraries and clicking on "Scan Library" brings me to a dialogue that lets me select one of three refresh modes:
- "Scan for new and updated files" (the one I always use, seems to leave my metadata intact)
- "Search for missing metadata" (which, as a side effect, also **deletes** any genre metadata I have manually entered. I neither expect nor appreciate such behavior given the innocent description.)
- "Replace all metadata" (I have no idea what my metadata is going to be replaced with, but it sounds exactly like the thing I don't want to happen.)

The issue is that none of these modes are described very well and the user essentially has to guess what they do, and wrong guesses can lead to a loss of metadata.

I would therefore propose more detailled explainations be added to clarify what _exactly_ each of these refresh modes does and which metadata it replaces or merges or even removes.

### Jellyfin Version

10.8.8

### Environment

```markdown
- OS: DietPi
- Virtualization: Docker
- Clients: Windows, Manjaro
- Browser: Chrome 108.0.5359.98
- Playback Method: Direct Play
- Hardware Acceleration: none
- Plugins: AudioDB, MusicBrainz
- Reverse Proxy: nginx
- Base URL: none
- Networking: Host
- Storage: local
```
### Screenshot

![Jellyfin refresh modes](https://user-images.githubusercontent.com/37195767/206700793-40b03e8c-9785-4bff-be8d-56f7e3061762.png)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by deltonio2** [comment]
When I select "Search for missing metadata" I absolutely do not expect the metadata that I have manually filled in to be deleted, the wording is indeed not clear at all. I lost hours and hours of work because of this.

**Comment by deltonio2** [comment]
Actually, "Search for missing metadata" seems to have the same effect as "Replace all metadata".
More than a description issue, it seems to be a bug, that "Search for missing metadata" should only add missing metadata and not modify/remove existing ones.
A bug has been opened for this ([#9760](https://github.com/jellyfin/jellyfin/issues/9760)).

**Comment by srcrist** [comment]
Closing this issue as it does not contain an actionable jellyfin server bug. The best place to address this is probably the documentation. You could submit an issue to the documentation repo if you don't have time, or simply a PR to add better descriptions to the documentation if you're willing. Will address https://github.com/jellyfin/jellyfin/issues/9760 as we process that issue.
