### ISSUE TITLE
[Issue]: People metadata should not be a free flow text input field

### ISSUE THREAD

**Issue by rickysarraf** [jellyfin/jellyfin#8907]
### Please describe your bug

Consider the below images for describing the bug please.

![Screenshot_20221214_182617](https://user-images.githubusercontent.com/65480/207603586-940faef3-7a55-4e5c-96e6-380a36271370.png)

In the above screenshot, I have created a couple of `Collections`. And it rightly shows the collection items in there, in a drop down list, which is perfect.

Now please consider the below screenshot.
![Screenshot_20221214_182651](https://user-images.githubusercontent.com/65480/207603951-1f7aa492-3662-4d6f-912a-a5fd450bf83d.png)

I was to add the `People` metadata to this content. I already have created a couple of `People` items. But, as you can see in the screenshot, the `People` field is not a drop down list. Instead, it is a free flow text input field. That is a problem because:

* I don't get to see a list of people I already created
* I could free-flow add the name of the Person. But that is error prone and can lead is duplicates (with linespaces, incorrect spellings etc)

### Expected Behavior

[] People should be a drop down list, listing all people already available in our Database
[] There should also be a `New Person` option there, which would then allow the free-flow text field.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Linux
- Virtualization: Docker
- Clients: Jellyfind MPV Client (Flatpak)
- Browser: NA
- FFmpeg Version: NA
- Playback Method: NA
- Hardware Acceleration: NA
- Plugins: NA
- Reverse Proxy: NA
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
This isn't a bug but a feature request.
https://features.jellyfin.org/
