### ISSUE TITLE
[Issue]: Movie collection changes not saved to movie NFO files

### ISSUE THREAD

**Issue by GHMJT** [jellyfin/jellyfin#8910]
### Please describe your bug

Adding/removing movies to/from Jellyfin collections are not saved to node &#60;set&#62;MovieCollection&#60;/set&#62; in local movie NFO files.

Condition: Metadata savers are set to NFO in library settings. Other data is properly writing to local NFO files, but not &#60;set&#62;MovieCollection&#60;/set&#62; nodes.

Related: The feature for creating Jellyfin collections based on local movie NFO files was recently added in 10.8...
https://features.jellyfin.org/posts/73/create-collection-based-on-nfo

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shadowghost** [comment]
I see a problem here: You can add items to multiple Collections in Jellyfin - which one should be the one saved to the NFO?

**Comment by GHMJT** [comment]
I'd presume this format..

<set>Collection 1</set>
<set>Collection 2</set>
<set>Collection 3</set>

I'd suggest writing to NFOs in this format, however I just did a test and Jellyfin is not pulling multiple sets from NFO files in this format. So just a suggestion.

**Comment by Shadowghost** [comment]
We're adhering to Kodi NFO standards and it does not support multiple set instances so it's unlikely this gets added.

**Comment by GHMJT** [comment]
I just did a test. Kodi works with multiple sets in NFO files by using the first set. So this solution would maintain compatibility with both Kodi and Jellyfin.

Alternatively Jellyfin could apply just one set when saving to NFO so that export function is at least possible, albeit limited to Kodi standard.

NFO import/export would be a significant feature because NFO most easily and universally migrates cross platform, or same platform when migrating to new hardware systems.

**Comment by GHMJT** [comment]
Update: Jellyfin movie set import from NFO isn't working even with single sets. Jellyfin is the best media server but it's not geared for universal media management. Best stick with a dedicated media manager or manual NFO editing.
