### ISSUE TITLE
[Issue]: Characters with dots on them are rendered as "�"

### ISSUE THREAD

**Issue by IzKuipers** [jellyfin/jellyfin#8920]
### Please describe your bug

Characters that have dots on them are rendered as question marks in Jellyfin. A good example of this is the "ö" character; it is rendered as "�" instead of the actual correct character.

This may be because of a character set issue, or it may very well be a metadata issue, but I've been having this issue for years without any apparent way of fixing it. I couldn't find any results online on how to resolve the issue, so that's why I'm posting it here.

### Jellyfin Version

Other

### if other:

10.8.8

### Environment

```markdown
- OS: Windows 10 22H2 X64
- Virtualization: None
- Clients: Browser
- Browser: Chrome 108.0.5359.125
- FFmpeg Version: 5.1.2
- Playback Method: Direct Play
- Hardware Acceleration: VAAPI
- Plugins: none
- Reverse Proxy: nginx - localhost:8096 -> media.twiserver.nl
- Base URL: /
- Networking: Connected to router via WiFi
- Storage: 1TB SATA SSD (Samsung 870QVO) on NTFS
```

### Jellyfin logs

```shell
(no relevant logs)
```

### FFmpeg logs

```shell
(no relevant logs)
```

### Please attach any browser or client logs here

(no relevant logs)

### Please attach any screenshots here

![image](https://user-images.githubusercontent.com/76709090/208296556-fe47841c-a8b8-4cdc-8bfc-2c415f557afa.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by photonconvergence** [comment]
What character encoding are you using for your metadata?

I am able to reproduce with Windows-1252 encoding in the tags. Characters render properly for me with UTF-8 encoding.

**Comment by IzKuipers** [comment]
I'm using UTF-8 everywhere

**Comment by clementduveau** [comment]
As I use Jellyfin fully in French (metadata included) I also have a lot of special characters (é è ô œ ï ê à ...) but I never had any issue, not even with Emby.

Is it happening to all non-ASCII characters ? On all devices and apps connected ? Would you mind give a guest access to your instance to see the bug ?

**Comment by IzKuipers** [comment]
As far as I can tell it happens on all devices I look at

I can give you access to a guest account on my Jellyfin instance, though sending the credentials publicly seems a bit unsafe.
