### ISSUE TITLE
[Issue]: Rescan not showing filenames even with prefer filenames selected

### ISSUE THREAD

**Issue by jasonycw** [jellyfin/jellyfin#8947]
### Please describe your bug

1. After initial setup, setup the first library as "Mixed Movies and Shows" content type and found that all the files are not named properly
2. Go to Dashboard > Libraries
3. Edit the library that have all the files name incorrectly
4. Untick all metadata downloaders and untick "Prefer embedded titles over filenames"
5. Scan library with "Replace all metadata" and tick "Replace existing images"
6. Wait until all loading complete and go back to the library
7. Still some files are named incorrectly

Anyway to completely redo all the metadata and rescan the library so that the titles are all just folder names and file names?
I do not want any metadata automation, just want it to show and sort by file names

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS:Windows 10
- Virtualization: EXE
- Clients: Browser
- Browser: Chrome latest
- FFmpeg Version: not sure
- Playback Method: n/a
- Hardware Acceleration: default
- Plugins: none
- Reverse Proxy:none
- Base URL:none
- Networking: host
- Storage: local
```

### Please attach any screenshots here

This is the library setting (I only have one library)
![image](https://user-images.githubusercontent.com/4518597/209346008-4e71f5de-7fa7-4394-bf80-6be792d1d9e0.png)

After untick all the metadata and all the rescanning, I still see quite a lot of video files like
![image](https://user-images.githubusercontent.com/4518597/209346471-89957b82-5a14-4b66-9ea2-621c8bb5cee4.png)

I need to manually change their title back to the file name one by one
![image](https://user-images.githubusercontent.com/4518597/209346526-e99d3ced-ff82-449f-9619-a8fcac6aa3c0.png)

It's very annoying when the "automation" complete mess up and make it impossible to identify or search file
![image](https://user-images.githubusercontent.com/4518597/209346639-ce01c258-1218-459a-98ca-5fc4660c05ab.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jasonycw** [comment]
Not stale

**Comment by weiwch** [comment]
I still have the same problem on version 10.8.13. You could choose library type to be photos, not mixed show/movie if you want a plain folder view, which is a compromise solution.

**Comment by Ngwind** [comment]
I  have the same problem on v10.8.10 too

**Comment by bGZo** [comment]
Just **select content type to `Home videos and photos`**, which works for me as following in 2024.

![](https://raw.githack.com/bGZo/assets/dev/2024/20241103002709.png)

**Comment by johnoneil** [comment]
I can confirm this is still an issue with a 10.10.1 build.

I can also confirm the workaround to set `Home Videos and Photos` does work to present pure filenames, but the bug remains.

**Comment by KyattPL** [comment]
Have the same issue, I think it's somehow related to the filenames. Every video taken with my phone with names like "VID_20220726_190243" seems fine, but lets say "Eurovision_2021_Cyprus" gets cut to only "Eurovision". Changing it to something like "Grand Final Eurovision Cyprus 2021" solves it. I don't know what's the difference between the first ("VID...") and second title is but yeah, annoying.

**Comment by KyattPL** [comment]
For anyone wondering I did rename my files and everything works properly. I'd recommend using PowerToys's PowerRename utility and ask chatgpt (if you're not a regex wizard) for any regex to rename a lot your files.

**Comment by thecosmicskye** [comment]
Still broken

**Comment by L8HRS** [comment]
still an issue but I see this is set to Not Planned as per earlier comment by jellyfin-bot
