### ISSUE TITLE
[Issue]: Private playlists are not properly hidden if users create playlists

### ISSUE THREAD

**Issue by danielcb114** [jellyfin/jellyfin#8950]
### Please describe your bug

Reproduction steps:

1. Create an admin user
2. Create a playlist as the admin user for a private library
3. Create a user without admin permissions
4. Switch to the newly-created user account
5. Create a playlist on the new user account
6. Create another playlist and you will now be able to see the playlist for the private library 

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shadowghost** [comment]
Should be fixed by #8526
