### ISSUE TITLE
Jellyfin wont startup localhost, and internal

### ISSUE THREAD

**Issue by alexmilanionline** [jellyfin/jellyfin#8955]
### Please describe your bug

Today I tried accessing Jellyfin will not load localhost where the actual V10.8.8. USing Windows 10 Pro OS BUILD: 19045.2364 open when to Jellyfin tray app open Jellyfing welcoming jellyfin logo comes up and get stuck can anyone help I have tried everything??? Also when I tried to access from another computer I get this error message??? http://192.168.138.169:8096/http://192.168.138.169:8920/web/index.html#!/home.html/web/index.html

And I also get this message? Can someone help and resolve this please?
The page isn’t redirecting properly

Firefox has detected that the server is redirecting the request for this address in a way that will never complete.

This problem can sometimes be caused by disabling or refusing to accept cookies.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

https://drive.google.com/file/d/1C3W0FtXmTthrRYJ9NcAhHlL2GmyNac1U/view?usp=share_link

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by spupuz** [comment]
got same problem jellyfin does startup but at the end does not load correctly from web or app.
Ho can i check if it is something related to a pluign or what else?

**Comment by andy9879** [comment]
your url looks weird. try
http://192.168.138.169:8096
