### ISSUE TITLE
[Issue]: -other extra is showing up as a movie

### ISSUE THREAD

**Issue by slick-nick-90** [jellyfin/jellyfin#8962]
### Please describe your bug

in my folder structure I have the following
movie_name (2004)/3 Plot Holes-other.mkv
movie_name (2004)/movie_name.mkv

it recognizes the -other file as another movie

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: debian
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins: none
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by slick-nick-90** [comment]
I'm still having the same issue on the latest release

**Comment by 1337joe** [comment]
What type library is this happening in? I can't reproduce it on a `Movie` library.

**Comment by slick-nick-90** [comment]
It's a movie library 
![Screenshot_20230223-005025](https://user-images.githubusercontent.com/61570822/220849839-058521d9-d6f7-4bbc-96ad-25c6c3572fca.png)

The -other files show up as separate movies

**Comment by 1337joe** [comment]
`other` as a suffix is a fairly new addition. It's in the code baseline (as of October) and is therefore in the documentation but won't be in a release until 10.9.0 (or whatever the next non-patch release is).

I'd recommend using the suffix `-extras` since it will be treated the same as `-other` and that suffix was definitely handled in 1.8.0.

**Comment by Cyberfighter** [comment]
I have a similar issue with "other" content. I have my movies organized using the folder structure so my "other" special features are in an "other" folder that is within the Movie's folder. My special features just doesn't appear at all anywhere though.

I run both Plex and Jellyfin on my Library so I unfortunately can't use the Extras folder as Plex does not support this Extra Type. I did however confirm that renaming to Extras, does bring it up in Jellyfin where it should.
