### ISSUE TITLE
[Issue]: Multiple versions of movies, brackets not behaving as expected

### ISSUE THREAD

**Issue by Jollerprutt** [jellyfin/jellyfin#8963]
### Please describe your bug

According to the documentation, labels can be placed between brackets and still behave as if there were no brackets.
https://jellyfin.org/docs/general/server/media/movies/#multiple-versions-of-a-movie

But adding the brackets change the version sorting and display.
Adding resolutions and other labels such as Extended edition without brackets behaves as expected and works well.
But when enclosed in brackets the sorting priority disappears and everything behaves like arbitrary text, being sorted alphabetically.
This means 1080p gets sorted before 2160p since 1 is lower than 2.

Also the brackets show up in the version box while browsing the library.

My guess is this is a parsing issue where the brackets get included as part of the label, that would explain both symptoms.

### Jellyfin Version

10.8.0

### if other:

10.8.6

### Environment

```markdown
- OS: Linux (Synology)
- Virtualization: Docker
- Clients: Browser
- Browser: Firefox 108.0.1
- FFmpeg Version: N/A
- Playback Method: N/A
- Hardware Acceleration: none
- Plugins: none
- Reverse Proxy: local
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shadowghost** [comment]
AFAIK resolutions get handled with priority and are sorted ascending before sorting alphabetically.

**Comment by Jollerprutt** [comment]
Yes that is the expected behaviour, but it only works without brackets.

**Comment by Bond-009** [comment]
This should be fixed in master (unstable), can you test?

**Comment by mikewesten** [comment]
Noticed this as well. If the server behavior can't be changed to match the documentation, then at least change the documentation to match the server behavior.
