### ISSUE TITLE
Jellyfin WebOS app on Homebrew channel

### ISSUE THREAD

**Issue by jimlynnjulian** [jellyfin/jellyfin#8970]
### Please describe your bug

Not a bug but a possible oversight.
I just discovered there is a Jellyfin app available in the Homebrew channel for LG WebOS.
Is that app an official release? A brief discussion of the subject would be helpful.
'Rooting' one's TV sounds risky. There is even a mention of the possibility of 'bricking' the TV.
Nobody wants to brick a TV that cost $$$$$. If the app is an official release, an article on jailbreaking
LG TVs for use with the Homebrew Jellyfin app might relieve some apprehension regarding the issue.
The existing WebOS app is for WebOS versions later than mine, 5.50.10.

### Jellyfin Version

10.8.0

### Environment

```markdown
WebOS 5.50.10
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
Homebrew is not maintained or supported by Jellyfin. 
The app they provide is an official release, taken from https://github.com/jellyfin/jellyfin-webos/releases/tag/v1.1.0

**Comment by jimlynnjulian** [comment]
This brings up an issue. What do people with older (WebOS 5.50.10) versions do? The existing WebOS LG app is for versions beginning with 6.0, I believe. I have always used the LG web browser to run the Jellyfin web app. Is that the final stage of development for earlier versions of WebOS?
