### ISSUE TITLE
[Issue]: Jellyfin dont stack .mkv movies

### ISSUE THREAD

**Issue by ksb749** [jellyfin/jellyfin#8975]
### Please describe your bug

I have some movies in multiple resolutions, and just noticed that Jellyfin dosent stack .mkv meida.

Movie 1 (1999) - 576.mp4
Movie 1 (1999) - 720p hevc.mp4

The above example would be stacked, but if it's .mkv it wont like this:

Movie 1 (1999) - 576.mkv
Movie 1 (1999) - 1080p hevc.mkv

And this means i have 2 of "Movie 1 (1999) shown in my library, instead of just 1, where when i would click on it, i would be able to change resolution before i play it.

### Jellyfin Version

10.8.0

### if other:

10.8.8

### Environment

```markdown
- OS:Rasberry Pi OS
- Clients: Jellyfin media player + web player
- Browser: Chromium
- FFmpeg Version: jellyfin-ffmpeg5/now 5.1.2-5-bullseye arm64
- Playback Method: direct playback
- Hardware Acceleration: disabled
- Plugins: none
- Reverse Proxy: Caddy
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shadowghost** [comment]
I could not reproduce this on a fresh instance with exactly your described file layout.
