### ISSUE TITLE
[Issue]: Debian build still wrong for jellyfin-web location

### ISSUE THREAD

**Issue by donteiser** [jellyfin/jellyfin#8976]
### Please describe your bug

Jellyfin-web won't start.

In Debian-based distros (like MX Linux), after installing jellyfin with the published instructions on https://jellyfin.org/docs/general/installation/linux

Starting jellyfin FAILS when using:  sudo service jellyfin start

This problem was noted on Reddit two years ago in the article at:
https://www.reddit.com/r/jellyfin/comments/hutsa1/can_we_get_updated_installation_instructions/

"[Surrealdoughnut](https://www.reddit.com/user/Surrealdoughnut/)
[2 yr. ago](https://www.reddit.com/r/jellyfin/comments/hutsa1/comment/fyptttg/?utm_source=reddit&utm_medium=web2x&context=3)
[u/Gabriel-p](https://www.reddit.com/u/Gabriel-p/) It looks like on an ubuntu installation it gets installed in /usr/share/jellyfin/web instead of /usr/lib/jellyfin/bin/jellyfin-web. Something must be wrong with the installer?

Running this command should fix it sudo jellyfin -w /usr/share/jellyfin/web "

... and I can confirm that this command does currently allow jellyfin-web to start.

Please fix this problem in the Debian build.  Thanks.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: MX Linux
Linux mx 5.10.0-20-amd64 #1 SMP Debian 5.10.158-2 (2022-12-13) x86_64 GNU/Linux
- Virtualization: none
- Clients: all
- Browser: all
- FFmpeg Version: latest
- Playback Method: all
- Hardware Acceleration: none
- Plugins: none
- Reverse Proxy: none
- Base URL: http://localhost:8096
- Networking: Ethernet
- Storage: local SSD
```

### Jellyfin logs

```shell
No log output when this fails.
```

### Please attach any screenshots here

$ sudo service jellyfin start
[sudo] password for xx 
Starting Jellyfin Media Server: jellyfin.

$ sudo service jellyfin status
jellyfin is not running ... failed!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anthonylavado** [comment]
I asked this in chat, but just to be sure it's not missed:

I notice in your issue you linked to the docs. Is there any particular reason you used those instructions? Was it the Generic Insrall section or the Debian section?

From the main site, clicking the "Download Now" button would take you to this page - https://jellyfin.org/downloads/server - and the instructions there shouldn't cause any issues like this. Perhaps we need to bring both in sync.

**Comment by donteiser** [comment]
Thanks so much, Anthony.  

So it sounds like there are two different sets of installation instructions for Debian, the one you recommend which is located at: https://jellyfin.org/downloads/server/

versus the one I used in the Installation --> Linux --> Debian section of the website https://jellyfin.org/docs/general/installation/linux  which state that we should do the following:

"Install Jellyfin via our APT repository or via manual archives (.deb).

Use extrepo to enable the jellyfin repositories (or see steps 1-3 below for manual repository setup):

sudo apt install extrepo
sudo extrepo enable jellyfin

Update APT repositories:
sudo apt update

Install Jellyfin:
sudo apt install jellyfin

**Comment by anthonylavado** [comment]
At first glance, the instructions you quoted there seem like they _should_ achieve the same end result. It's the actual `apt install Jellyfin` that matters, because that should unpack and set everything correctly. We'll still give it a review and make sure everything lines up though.

It mag be that there's something about our Debian packaging that MX Linux doesn't like or doesn't perform correctly. AFAIK everyone I've spoken to who uses regular Debian, Ubuntu, or Raspbian seems to have everything run just fine.

**Comment by donteiser** [comment]
I did a sudo apt remove jellyfin jellyfin-web
which was successful.

Then tried the curl method.  That fails, too.  See below:

curl https://repo.jellyfin.org/install-debuntu.sh | sudo bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9310  100  9310    0     0  28297      0 --:--:-- --:--:-- --:--:-- 28384
> Determining optimal repository settings.

Found the following details from '/etc/os-release':
  Real OS:            debian
  Repository OS:      debian
  Repository Release: bullseye
  CPU Architecture:   amd64
If this looks correct, press <Enter> now to continue installing Jellyfin. 

> Creating APT keyring directory.

> Fetching repository signing key.

> Installing Jellyfin repository into APT.
Types: deb
URIs: https://repo.jellyfin.org/debian
Suites: bullseye
Components: main
Architectures: amd64
Signed-By: /etc/apt/keyrings/jellyfin.gpg

> Updating APT repositories.
E: Conflicting values set for option Signed-By regarding source https://repo.jellyfin.org/debian/ bullseye: /var/lib/extrepo/keys/jellyfin.asc != /etc/apt/keyrings/jellyfin.gpg
E: The list of sources could not be read.
Failed to update APT repositories. Something is wrong with your APT sources, GPG keys, or Internet connection. Try again shortly or use https://jellyfin.org/contact to find us for troubleshooting.

**Comment by EZUsername42** [comment]
> It may be that there's something about our Debian packaging that MX Linux doesn't like or doesn't perform correctly. AFAIK everyone I've spoken to who uses regular Debian, Ubuntu, or Raspbian seems to have everything run just fine.

I can confirm the issue exists in standard Debian as well. 


> Running this command should fix it sudo jellyfin -w /usr/share/jellyfin/web "
> 
> ... and I can confirm that this command does currently allow jellyfin-web to start.

I was unable to fix it using this command.
