### ISSUE TITLE
[Issue]: Audio tracks don't stay on selected version of video if multiple versions of audio tracks are present.

### ISSUE THREAD

**Issue by glebinski** [jellyfin/jellyfin#8983]
### Please describe your bug

If I were to watch any sort of show that contains more than 1 version of  audio tracks (Japanese & English in this case) and select English, the next episode of that show would start with Japanese voice-overs instead of English while it would still show English as the selected track.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Ubuntu Server
- Virtualization: N/A
- Clients: Web, Android
- Browser: Firefox
- FFmpeg Version: 4.2.7
- Playback Method: Direct Play
- Hardware Acceleration: none
- Plugins: AudioDB, MusicBrainz, TMDb, OMDb, Studio Images
- Reverse Proxy: none
- Base URL: none
- Networking:
- Storage: local
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CoconutStarshipForever** [comment]
Yes, I've got the same problem.

It appear that the server will always start with the default audio track even if the client is set from last episode of a show.

I always have to select another track then back on the desired track to ask the server for the correct one.

**Comment by Shadowghost** [comment]
If the show was scanned in before 10.8 try refreshing the metadata.
