### ISSUE TITLE
Metadata not added automatically anymore

### ISSUE THREAD

**Issue by tommyguuuun** [jellyfin/jellyfin#9004]
Since the last update, my files are added automatically, but there is no metadata added to the entry. Just the name + year.

When i do a "refresh metadata" it works like before. But now i have to do it manually to every file, it doesn't work automatically as before.

I have the latest version installed in docker on DSM 7.1 (Synology DS1522+). 

The name structure for this example is: Fight Club (1999)/Fight Club (1999) {imdb-tt0137523} Remastered [Remux-1080p][DTS-HD HRA 7.1][h264].mkv - But i don't think this is the problem, as it works as expected when i do a manual refresh.

![2023-01-03 14_03_40-Jellyfin](https://user-images.githubusercontent.com/26925125/210362778-cf752551-23e8-4b6f-8fee-b8cb44c1ae47.png)

**Comment by Bond-009** [comment]
Please fill out the issue template (logs, version, etc)

**Comment by antiops** [comment]
Got a similar issue, might be related to https://github.com/jellyfin/jellyfin/issues/8989
