### ISSUE TITLE
DV content direct plays on devices that do not support it instead of transcoding.

### ISSUE THREAD

**Issue by morkyy** [jellyfin/jellyfin#9012]
I have set up HW transcoding and also set up all the correct tonemapping for DV content. 
I have a TV where DV is supported and DV content, direct plays there with no issues.

When attempting to play DV content on a device that doesn't support DV (but supports everything else) that content direct plays when it should be transcoding. I have to manually lower the quality to force a transcode so that I get correct tone mapping.

Is there a check for DV support on the client similar to how a check is made for supported codecs? Whether a client supports DV should be taken into account for transcoding now that DV tone mapping is working.

Client I'm using is the Jellyfin media player on windows.

**Comment by Shadowghost** [comment]
This depends on the client properly selecting the appropiate codec profiles.
