### ISSUE TITLE
[Issue]: Collection items never get removed if they dont exist anymore

### ISSUE THREAD

**Issue by dionysius** [jellyfin/jellyfin#9025]
### Please describe your bug

In the logs I saw the following line:
`[2023-01-07 05:08:26.535 +00:00] [WRN] Unable to find linked item at path "/mnt/samba/public/Movies/The XXX/XXX.mp4"`

This file/folder does not exist anymore (more than a month).

- I have not found anything related to this entry in `jellyfin.db` or `library.db`
- But I do have found it in `/var/lib/jellyfin/data/collections/The XXX/collection.xml`

And I believe this is related.

- Media rescan, Metadata rescan, Replace all metadata via Browser did not help.
- Removing Collection via Admin Dashboard via Browser immediately created the collection again (different issue, plenty of this reported already) **but the wrong items are now gone within collection.xml - so this might have fixed the issue**

Whichever job is responsible should also remove nonexisting items in collections.

### Jellyfin Version

10.8.4-1

### Environment

```markdown
- OS: Ubuntu jammy
- Reverse Proxy: nginx
- Base URL: /
```

### Jellyfin logs

see above

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shadowghost** [comment]
Please update to 10.8.8, run a library scan and check again.

**Comment by dionysius** [comment]
Yeah due to a bug on my apt setup, packages from the jellyfin apt were never automatically updated. Unfortunately the collection deletion already fixed it so cannot check again. Will open a new issue if something new comes up

**Comment by Liquoriced** [comment]
I have the same issue, but neither the update to 10.8.8 nor deleting the Collections via Admin Dashboard fixed it.
I also removed and reinstalled the boxset plugin, but alas the problem is still there.

This also makes the collections library browsing sluggish
