### ISSUE TITLE
[Issue]: cant chromecast from fdroid build 

### ISSUE THREAD

**Issue by cyanide699** [jellyfin/jellyfin#9027]
### Please describe your bug

Jellyfin client from fdroid doesn't find any chromecast devices

Jellyfin client from playstore does find chromecast devices

V 2.4.4 in pixel 7 pro

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shadowghost** [comment]
Chromecast requires proprietary libraries which are not allowed in apps posted on fdroid. If you want to use chromecast you need to use the playstore version.

**Comment by cyanide699** [comment]
> Chromecast requires proprietary libraries which are not allowed in apps posted on fdroid. If you want to use chromecast you need to use the playstore version.

ah thankyou for the info i wasnt aware of!
