### ISSUE TITLE
Latest jellyfin:master show tag and label text on everything

### ISSUE THREAD

**Issue by BobOkisama** [jellyfin/jellyfin#903]
Latest jellyfin:master docker image, all the text is showing up saying tab and label. This shows up everywhere, in settings, in main page, menus.

![capture](https://user-images.githubusercontent.com/22991784/52872200-e7897700-3119-11e9-8336-0d9ab9d2bfb6.PNG)

**Comment by cvium** [comment]
Clear your cache

**Comment by JustAMan** [comment]
Duplicate of https://github.com/jellyfin/jellyfin-web/issues/134, fixed in upcoming release.
