### ISSUE TITLE
[Issue]: DLNA broadcasting not working as soon as https is activated

### ISSUE THREAD

**Issue by Tinigriffy** [jellyfin/jellyfin#9036]
### Please describe your bug

Hi my issue is quiet simple and I have seen many report around it but it was supposed to be fixed in serie 1.8.X.X or the issue were closed automatically.

So as soon as I activated HTTPS option (but I do not enforce it) the DLNA boradcasting is not working.
The WS call are done using the ip and http, but  wireshark shows that the stream url provided to my old jongo S3 is using https. Unfortunately it is does not support it and it even reports that the url is wrong when it tries to play it.

Here a file with the wireshark dump. renderer ip is 192.168.10.40 and jelly is 192.168.0.17
[dlna_error.txt](https://github.com/jellyfin/jellyfin/files/10367404/dlna_error.txt)

### Jellyfin Version

10.8.0

### if other:

10.8.8

### Environment

```markdown
- OS: Linux Fedroa 37
- Virtualization: podman with jellyfin/jellyfin:lastest image
- Clients: none
- Browser: firefox 108.0.1
- FFmpeg Version: version embeded is the odcker image
- Playback Method: dnla
- Hardware Acceleration: no
- Plugins: no
- Reverse Proxy: non
- Base URL: default
- Networking: macvlan
- Storage: local
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shadowghost** [comment]
Likely fixed by #8147 - please reopen if this still happens on unstable.
