### ISSUE TITLE
[Plugin Request] m3u functionality possible as plugin?

### ISSUE THREAD

**Issue by NicoJuicy** [jellyfin/jellyfin#9037]
I don't see that much documentation on writing a plugin. I'm aware of plugins that provide "metadata" from certain files.

Would it be possible to write a plugin that parses m3u information and suggests this as a playlist in Jellyfin? If so, then i can see to write it myselve.

It would be usefull to know if you think that can be done and/or what the limitations would be.

**Comment by Bond-009** [comment]
Maybe request it here?: https://features.jellyfin.org/
