### ISSUE TITLE
[Issue]: Unable to scan library with TVDB

### ISSUE THREAD

**Issue by UltraHKR** [jellyfin/jellyfin#9038]
### Please describe your bug

Recently (about 4 days or so) my library scans completely fail.

My data import routine is as follows:
1. Rename files with FileBot
2. Move files to respective library
3. Hit Scan all libraries button.

But recently I manually added a few collections, and everything went in flames... (Possibly related)

Diagnostics done:
- restart JF
- retry scanning all libraries
- disabling TVDB in all libraries
- removing TVDB from JF

The only way to fix this issue is to completely remove TVDB plugin. 

Attached is a log with debug level enabled: 
[JF Debug log.txt](https://github.com/jellyfin/jellyfin/files/10367739/JF.Debug.log.txt)

### Jellyfin Version

10.8.0

### if other:

10.8.8

### Environment

```markdown
- OS: TrueNAS Scale 22.12.0
- Virtualization: Docker (linuxserver/jellyfin:10.8.8-1-ls192)
- FFmpeg Version: 
- Playback Method: NA
- Hardware Acceleration: none
- Plugins: TVDB v8.0.0.0
- Reverse Proxy: no
- Base URL: none
- Networking: Host?
- Storage: local
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by UltraHKR** [comment]
Also if you check the logs certain files are saved with improper extensions 
please search the attached file for "*.jpe" files.....

I didnt notice until I tried to manually check the file, triyng to diagnose the TVDB problem........

**Comment by darthShadow** [comment]
https://github.com/jellyfin/jellyfin/issues/8989
