### ISSUE TITLE
[Issue]: No internet radio stations using Jellyfin DLNA server / DLNA Clients

### ISSUE THREAD

**Issue by GH0000000000** [jellyfin/jellyfin#9039]
### Please describe your bug

I would like to play internet radio stations using Jellyfin DLNA server.
Is it possible to upload to JF the list of my favorite internet radios and share them for my DLNA Clients eg AVR ? I know (according to this page https://jellyfin.org/docs/general/server/media/internet-radio/) how to setup internet radio stations in JF. My JF Clients are able to see TELEVION folder and play my Radio.m3u stations, however my DLNA Clients are able to see TELEVION folder under DLNA only (btw, it should be named RADIO or sth like that) but the folder is empty (no content). So, using JF DLNA I am not able to play m3u radio stations, why ?

### Jellyfin Version

10.8.0

### if other:

NAS Asustor JF 10.8.8.r01

### Environment

```markdown
- OS:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Rybeusz100** [comment]
I'm facing the same issue, any plans to address it?

**Comment by GH0000000000** [comment]
I think the answer is here 
https://www.youtube.com/watch?v=jKF5GtBIxpM 
timeline14:50
