### ISSUE TITLE
[Issue]: The repository 'https://repo.jellyfin.org/debian stable Release' does not have a Release file.

### ISSUE THREAD

**Issue by skibbipl** [jellyfin/jellyfin#9041]
### Please describe your bug

Cannot install jellyfin from official repository on debian unstable (bookworm). Apt complains:
```
E: The repository 'https://repo.jellyfin.org/debian stable Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
jellyfin.sources:
```
Types: deb
URIs: https://repo.jellyfin.org/debian
Suites: stable
Components: main
Architectures: amd64
Signed-By: /etc/apt/keyrings/jellyfin.gpg
```

### Jellyfin Version

Other

### if other:

N/A

### Environment

```markdown
- OS: Debian unstable
- Virtualization: N/A
- Clients: N/A
- Browser: N/A
- FFmpeg Version: N/A
- Playback Method: N/A
- Hardware Acceleration: N/A
- Plugins: N/A
- Reverse Proxy: N/A
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anthonylavado** [comment]
I'd have to defer to some of my colleagues for a 100% answer on this, but I believe we only have official releases for `buster` and `bullseye`. That said, I don't know that there's actually a `stable` release file, and that instead one of the supported distributions needs to be in the Suite field.

**Comment by skibbipl** [comment]
Ok, that makes sense. But it seems bullseye is dependent on too old libraries, not available on debian unstable. So I cannot install it.

**Comment by EZUsername42** [comment]
> Ok, that makes sense. But it seems bullseye is dependent on too old libraries, not available on debian unstable. So I cannot install it.

What errors are you getting when you try and install? 

I am also experiencing the following errors installing on Debian, although I run bullseye. The install package seems to set the wrong directories for jellyfin-web and ffmpeg. 
https://github.com/jellyfin/jellyfin/issues/8976
https://github.com/jellyfin/jellyfin/issues/7902

I hope this helps point you in the right direction.

**Comment by skibbipl** [comment]
> What errors are you getting when you try and install?
In debian unstable there are newer versions of mmpeg libraries, so I cannot install it. It would be nice to have testing version of jellyfin that is on par with debian testing libraries.
