### ISSUE TITLE
Enable transcoding to EAC3

### ISSUE THREAD

**Issue by rohitharkhani** [jellyfin/jellyfin#9045]
FFMPEG seems to have EAC3 encoder however jelly fin server has only ac3 not sure if it is possible to enable EAC3 encoder to enable truehd atmos to atmos. 

Right now when I pay truehd with atmos it converts to AC3 and atmos metadata is lost. 

https://github.com/jellyfin/jellyfin/blob/51c7c85b4cdaed9e86fc8699de61e489c9223a17/MediaBrowser.MediaEncoding/Encoder/EncoderValidator.cs#L29

**Comment by Shadowghost** [comment]
FFmpeg does not support decoding and encoding the atmos substream so your usecase is not supported right now.

**Comment by rohitharkhani** [comment]
yes, atmos is not supported however eac3 can be enabled to support 7.1 because right now TrueHD is encoded to ac3 which is 5.1 only.

**Comment by Shadowghost** [comment]
Another problem is that the EAC3 encoder in ffmpeg isn't on-par with the AC3 or AAC encoder. Looking at the code, Jellyfin will prefer any other codec over AC3 and AC3 over EAC3 when transcoding audio and the client announces multiple audio codec support.

**Comment by rohitharkhani** [comment]
True, but when I look at the major android tv or streaming devices. it supports EAC3 however for other like FLAC or AAC it does not support 7.1. It might not be worth for desktops or other devices however I feel worth it for android devices. 

for me at least on two devices android 10 tv and fire tv stick 4k max it uses ac3.

**Comment by supersebbo** [comment]
I’m going to +1 this.  This would allow many users to keep the original 7.1 tracks when having to transcode TrueHD, as it seems it’s quite common for devices to limit AC3/AAC to 5.1 channels (LG TVs included).

**Comment by gnattu** [comment]
I understand that some devices do not support 7.1 channel aac but unfortunately ffmpeg's eac3 encoder implementation is cannot encode more thant 5.1 either, as reported by `ffmpeg -h encoder=eac3`:

```
Encoder eac3 [ATSC A/52 E-AC-3]:
    General capabilities: dr1
    Threading capabilities: none
    Supported sample rates: 48000 44100 32000
    Supported sample formats: fltp
    Supported channel layouts: mono stereo 3.0(back) 3.0 quad(side) quad 4.0 5.0(side) 5.0 2 channels (FC+LFE) 2.1 4 channels (FL+FR+LFE+BC) 3.1 4.1 5.1(side) 5.1
```
