### ISSUE TITLE
Direct play capped at 2Mbps, software transcode not being used

### ISSUE THREAD

**Issue by pablordgez** [jellyfin/jellyfin#9063]
**Media Info of the file**
Container: mp4
Codec: HEVC Main 10
Video range type: SDR
Audio codec: AAC LC

**Logs**
Edit: here's the relevant part as the previous link is the live log and it will keep updating if I use jellyfin https://pastebin.com/vK42PcRZ

**FFmpeg Logs**
No transcoding, no logs are created

**Stats for Nerds Screenshots**
(It's in Spanish)
![image](https://user-images.githubusercontent.com/85810125/211680636-ff5ad997-ab1f-4721-9f49-1dd9345c44b1.png)

**Server System (please complete the following information):**
 - OS: Ubuntu Server 22.04LTS
 - Jellyfin Version: 10.8.8
 - Hardware settings & device: no hardware acceleration
 - Reverse proxy: cloudflare tunnels
 - Other hardware notes: media mounted on google drive
 
**Client System (please complete the following information):**
 - Device: was able to reproduce the issue on a phone and PC
 - OS: Android, Windows
 - Client: Web, Android
 - Browser (if Web client): Chrome
 - Client and Browser Version: Android: 2.4.4 Chrome: 108.0.5359.125

When streaming content from the Android client or Chrome, it uses Direct play but capped at 2Mbps, however stil at 1080p and maintaining image quality, which leads to it heavily stuttering. This happened on Chrome on both my PC and phone (both support the codec the video was using) and the Android Client. When using the third party Droidfin client, activating the experimental video player it worked fine.

It's using Direct play, not transcoding. My server can't do hardware acceleration but can handle software transcoding just fine. I can also be sure that it isn't using software transcoding by the fact that no ffmepg logs are created and the CPU usage is extremely low (usually is about 50% when transcoding, but it's at about 2%)

I made sure that the transfer rate wasn't limited in settings. It wasn't, but upon limiting it to 1Mbps, it started transcoding from 1080p to 480p and it stopped stuttering. I tried Microsoft Edge, and it transcoded instead of using Direct Play, didn't stutter at all.
Any ideas?

**Comment by andyearnshaw** [comment]
If you're using cloudflare tunnels, is it possible they're limiting the bandwidth intentionally for video files? It's explicitly against their T&C to use their proxies for anything other than normal website activity.
