### ISSUE TITLE
[Issue]: People thumbnails are large and take up a lot of unnecessary disk space, so should be downscaled

### ISSUE THREAD

**Issue by Webreaper** [jellyfin/jellyfin#9069]
### Please describe your bug

The thumbnails displayed for people can be extremely large (over 1MB) because they're pulled directly from the metadata sources such as TMDB, but are not rescaled when JF caches them locally. This can result in hundreds of MB of unnecessary storage being wasted locally. 

Jellyfin should really scale them down to some sensible max size, so that they're all no more than a couple of hundred KB or less. 

You probably already have thumbnail scaling code in the codebase - if not, please feel free to steal mine: https://github.com/Webreaper/Damselfly/blob/master/Damselfly.Core.ImageProcessing/SkiaSharpProcessor.cs#L25 (I seem to remember that JF uses Skiasharp to do its image manipulation). It would be trivial to feed a stream into that code so that the JF code that downloads the thumbs would automatically pass it through a downscaling filter before writing it to disk in `/metadata/People`.

Related: https://github.com/jellyfin/jellyfin/issues/5344 - this may also prevent space being wasted on JF mobile clients running on phones, where it also seems the thumbs are sent without any scaling. 

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DaCHack** [comment]
@Webreaper made a good point here.
Anything happened on this already?

**Comment by artecnico** [comment]
I also find this interesting. Maybe it should be re-opened as a "Featrure Request" instead of a bug...

**Comment by enrycami** [comment]
I think this has been fixed or something changed. On my install, with 3000+ pictures in the metadata/People folder, it only takes up about 500MB, so around 150kB per picture. Curiously some are very low (30 kB or less), while other can reach half a MB

**Comment by cydwarf** [comment]
> something changed

nope, still there. I just made a backup, ZIP is 557MB, and 486MB of them are for People only. Jennifer Aniston has the biggest face (1.32MB, full 2000x3000 px), all wrinkled. Then David Denman and Clarke Peters. Dunno why I need to store their portraits. 200x300px would be just fine.
