### ISSUE TITLE
[Issue]: Download missing subtitles scheduled task does nothing

### ISSUE THREAD

**Issue by Sheepyhead** [jellyfin/jellyfin#9081]
### Please describe your bug

I'm running a pretty standard jellyfin server from my synology nas through docker. When I attempt to run the "download missing subtitles" task, either through a schedule, or by simply clicking the run button in the "scheduled tasks" menu in the dashboard, nothing happens. The task immediately ends having done nothing. The logs report no errors, all I have is attached

I have attempted to fix this by installing the opensubtitles plugin, but that changed nothing even after a server reboot.

### Jellyfin Version

Other

### if other:

10.8.1

### Environment

```markdown
- OS:Linux
- Virtualization:Docker
- Clients:Linux, Android
- FFmpeg Version:5.0.1-Jellyfin
- Plugins:OpenSubtitles
```

### Jellyfin logs

```shell
[2023-01-12 16:11:51.133 +00:00] [INF] [20] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "Download missing subtitles"
[2023-01-12 16:11:51.171 +00:00] [INF] [20] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Download missing subtitles" Completed after 0 minute(s) and 0 seconds
[2023-01-12 16:11:51.208 +00:00] [INF] [20] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by owenxuereb** [comment]
+1 to this issue. Manual Search works (I've setup the opensubtitles plugin).

**Comment by sofiageo** [comment]
This is not a bug, you need to enable subtitle downloading for each collection.

**Comment by owenxuereb** [comment]
> This is not a bug, you need to enable subtitle downloading for each collection.

Will look into this and update accordingly. If you have any link to the documentation where I can apply this, please let me know. Thank you.

**Comment by owenxuereb** [comment]
Thank you @sofiageo . Went into the library > manage library and collections > download subtitles > select languages and saved. Ran the schedule manually but still no requests were passed to the Opensubtitles API.

**Comment by fmarotta** [comment]
If "save subtitles into media folders" is active, make sure that the jellyfin user have write access to those folders (or deactivate that option).

**Comment by owenxuereb** [comment]
I've solved this issue by doing as I stated previously with the addition of unthicking the "Only download subtitles that are a perfect match ...". The schedule downloaded subtitles for every video in my library with some not matching the timing conpletely and fixed by using the offset option in the gear part (bottom right of player).

**Comment by Sheepyhead** [comment]
> This is not a bug, you need to enable subtitle downloading for each collection.

This was the issue, kinda obscure but it seems to work now!

**Comment by dmackca** [comment]
I don't have the subtitles plugin installed at all, but the scheduled task is still configured to run every 12 hours, so it _definitely_ does nothing in a default install.

**Comment by Stooovie** [comment]
> If "save subtitles into media folders" is active, make sure that the jellyfin user have write access to those folders (or deactivate that option).

Can you please help me with this? I run Jellyfin in a Proxmox LXC and media is on a NAS mounted inside this LXC. It's too complicated for me to untangle. I have no idea what the current user is - I manage the JF LXC as root but that's probably not the proper user... I really don't know.  

Thanks!

**Comment by fmarotta** [comment]
Hi, I am not familiar with your setup, but when you install Jellyfin in Debian or Ubuntu it automatically creates a user and a group, both called "jellyfin". I used `chgrp -R jellyfin /my/media/directory` to change the group owner of the folders where the movies are. I would try to run the `chgrp` command on the directory that you mount in the LXC :)

For more debugging and testing, you could run a bash shell inside the LXC and do `su jellyfin`. That will tell you whether the jellyfin user exists and, if so, you will impersonate that user, so you can try to run commands and check if you have the appropriate permissions.

**Comment by Stooovie** [comment]
When i do "su jellyfin" inside the LXC, I don't get anything at all, like this:
```
root@jelly:~# su jellyfin

root@jelly:~# 
root@jelly:~# 
```
The default root user in the LXC does have write permissions... I'm sort of afraid to tinker with the perms on the NAS mount as it already has all sorts of -arr suite permissions. 

Oh well.

Thanks you!

**Comment by Stooovie** [comment]
so, no, chgrp -R jellyfin finishes without error, so does chmod -R g+w /THEMOUNTPATH, but jellyfin user still doesn't have write perms. This is probably way out of my skillset. I will have to do without subs in Kodi for Jellyfin (the original reason for all this - addon mode is way too slow and native mode doesn't allow downloading subs into media folders as the write is not permitted)

**Comment by Stooovie** [comment]
tried running this on the NAS itself
sudo chown -R jellyfin:jellyfin /volume1/Public/Video/TEST
sudo chmod -R 755 /volume1/Public/Video/TEST
but user jellyfin in the LXC still can't write.

What am I missing?

**Comment by fmarotta** [comment]
Interesting.. could it be that the uid/gid is not the same between the host and the container? if so, [this](https://forum.proxmox.com/threads/lxc-and-mount-point-permission-denied.111693/) might point you in the right direction.
