### ISSUE TITLE
Google Cast not working in Android: 

### ISSUE THREAD

**Issue by Tequenikality** [jellyfin/jellyfin#9089]
### Please describe your bug

Hi all;

I've seen a few posts on this already, but no resolutions. So, as of the date of posting, JellyFin server is up to date, Android app is up-to-date, all updates are installed in the server's OS (Debian 11) and the Android app was installed from G Play.

I have JellyFin installed on my server which also runs a static HTML website and Nextcloud instance as separate vHosts, so, to integrate well with the existing system, I created a new vHost as a sub-site (IE jellyfin.example.com) and proxy to the JF server, as described in the article [here](https://jellyfin.org/docs/general/networking/apache/).

Initially, no problems. I could connect to that website and access JF, no problems at all. I could even use the Windows player app with no issues. However, the problem came when I tried to use the Android app. It was jittery as anyone's business, but I found a workaround to that by switching to the integrated player in the settings.

However, cast still doesn't work, no matter what I do. I've tried suggestions from all over the internet including CSP policies, messing with my Let's Encrypt certificates, using PFX files instead of PEM files, using a different subdomain, you name it, I've probably tried it.

The closest I got was a suggestion from someone to remove the fullchain file because of LE's changes to their root certificate, but when I did this, the Android app stopped recognizing my server entirely. I could go to it via the web on my phone, but the app would say "tried 3 variations without success".

Alas, no matter what I do, the app immediately closes the Chromecast controls and the Chromecast itself goes blank until disconnected. No amount of trying to play or change files or anything makes it work. Don't know what else to do but it would really stink if the casting just doesn't work on the Android version of JF.

### Jellyfin Version

Other

### if other:

10.8.8

### Environment

```markdown
- OS: Debian 11 (Stable)
- Virtualization: None
- Clients: Android (G Play)
- Browser: N/A
- FFmpeg Version: No idea - whatever comes bundled with JF 10.8.8
- Playback Method: Transcode / Direct Stream
- Hardware Acceleration: VAAPI (also tested with none, no difference)
- Plugins: No extras, just whatever comes with JF 10.8.8
- Reverse Proxy: Apache
- Base URL: None
- Networking: Direct Ethernet connection to router, tested on LAN with firewall disabled completely
- Storage: 4tb local RAID 5
```

### Jellyfin logs

```shell
Only thing of note in the logs are these messages:

[INF] Playback stopped reported by app "Chromecast" "2.1.0" playing "Star Trek Into Darkness". Stopped at "0" ms
[WRN] Slow HTTP response from "http://jellyfin.example.com/Sessions/Playing/Stopped" to [IP ADDRESS] in 0:00:1.5381164 with status code 204
[WRN] WS "192.168.1.170" error receiving data: "The remote party closed the WebSocket connection without completing the close handshake."
[WRN] WS "192.168.1.170" closed.
```

### FFmpeg logs

```shell
Nothing relevant in these logs.
```

### Please attach any browser or client logs here

N/A - I don't have root so I can't access Android logs.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Tequenikality** [comment]
Any thoughts on this, please?

**Comment by satstarter** [comment]
Dont know if its the same problem but i get no cast icon anymore since i updated everything
server 10.8.9 and jellyfin android 2.5.1 beta on samsung tab and 2.4.4 on samsung phone
so no joy playing music from jellyfin on my google nest speakers anymore help please!
