### ISSUE TITLE
Slow collections browsing

### ISSUE THREAD

**Issue by Liquoriced** [jellyfin/jellyfin#9091]
### Please describe your bug

Accessing movie collections takes 20 seconds (see log).
Deleting collections and uninstalling and reinstalling collections plugin doesn't fix the issue.

To Reproduce
    Access Media Library via dashboard
    Click on 'Movies'
    Click on 'Collections' tab
    Collections pop-up in about **20 seconds**

Expected behavior
    Simply displaying the previously-saved movie collections should not introduce a dramatic slowdown when accessing it.

### Jellyfin Version

10.8.0

### Environment

```markdown
OS: Linux
    Virtualization: Docker
    Clients: Browser
    Browser: Firefox 86
    Jellyfin Version: 10.8.8
    Playback: Direct Play
    Installed Plugins: TMDB Box Sets
    Reverse Proxy:none
    Storage: local NAS
```

### Jellyfin logs

```shell
LOG
[2023-01-14 12:45:20.707 +00:00] [WRN] [29] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://192.168.50.245:8096/Users/f0d28b45a3284512a2aecaadae100aba/Items?SortBy=SortName&SortOrder=Ascending&IncludeItemTypes=BoxSet&Recursive=true&Fields=PrimaryImageAspectRatio%2CSortName&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CBanner%2CThumb&StartIndex=0&Limit=100&ParentId=f137a2dd21bbc1b99aa5c0f6bf02a805" to "172.17.0.1" in 0:00:18.1022623 with Status Code 200
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sirjmann92** [comment]
Same issue with Jellyfin 10.8.9 (Docker/Synology DSM) and TMDb Box Sets plugin version 10.0.0.0

Server: jellyfin
Version: 10.8.9
Operating System: Linux
Architecture: X64

**Comment by anym001** [comment]
Same issue here. 
I am using Jellyfin on my Unraid Server with TMDb Box Sets plugin version 10.0.0.0

Server: f59357331119
Version: 10.8.9
Operating System: Linux
Architecture: X64

**Comment by Liquoriced** [comment]
Additionally, while the slow browsing bug was temporarily resolved by changing one setting in the past (see issue #5424 - "Collections affect library browsing "), the fix of changing the way collections are handled (see pull request #5808 - "Optimize the way items are grouped into collections ") made it so the solution of changing the setting no longer improved the browsing experience.

In other words, for some of us, collections are still fairly broken.

**Comment by Liquoriced** [comment]
This is issue is still ongoing and it still hasn't been fixed.

**Comment by srcrist** [comment]
This issue may possibly be closed by https://github.com/jellyfin/jellyfin/pull/9643, but these symptoms can also be caused by slow storage. Is anyone using SSD storage for their data blob experiencing this issue?

**Comment by anym001** [comment]
I am using Jellyfin version 10.8.11 and unfortunately no improvement. The loading times are still extremely long. For info, I use a Nvme ssd.  Speed should therefore be no problem on the hardware side.

**Comment by srcrist** [comment]
If you are using docker, the previously mentioned PR may fix the issue. It is not in 10.8.11. It will be in 10.9.

**Comment by Liquoriced** [comment]
I

> This issue may possibly be closed by #9643, but these symptoms can also be caused by slow storage. Is anyone using SSD storage for their data blob experiencing this issue?

I'm not using SSD, but I'm 100% sure that's not the culprit: as mentioned in my previous comment above (Mar 29), the issue temporarily went away once when changing an option made it so that collections were loaded **instantly** for me (which I assume is the intended behavior). No other settings were changed, and collections browsing was flawless.

I can't wait to test version 10.9, whenever that will come.

**Comment by anym001** [comment]
I recently tidied up my libraries a bit and deleted my music collection from Jellyfin, among other things.
I noticed that the movie collections are now opened again instantly after I deleted manually created music playlists.

Could there be a connection here?

**Comment by sevenrats** [comment]
> I'm not using SSD, but I'm 100% sure that's not the culprit: as mentioned in my previous comment above (Mar 29), the issue temporarily went away once when changing an option made it so that collections were loaded **instantly** for me (which I 

ok so what was the setting?

**Comment by sevenrats** [comment]
fixed in unstable pending release.  If you have this issue on 10.9, please open a new report.
