### ISSUE TITLE
Install on NAS without Docker possible?

### ISSUE THREAD

**Issue by Tazcom** [jellyfin/jellyfin#9098]
### Please describe your bug

I am using a Synology DS120j so the cheapest one. It doesnt have Docker in the Appstore so i sadly cant install your software.

Is there any workaround already in the meantime? I couldnt find anything on your website.. 

Thank so much in advance.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS:Win + Synology
- Virtualization: Synology
- Clients:
- Browser: Chrome
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration: no
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gsymeoni** [comment]
Jellyfin has been repackaged into native Synology .spk on [synocommunity](https://synocommunity.com/package/jellyfin). 

Follow their main page for instructions

**Comment by Bond-009** [comment]
See #293
