### ISSUE TITLE
Shuffle only shuffles some part of the library

### ISSUE THREAD

**Issue by Appoxo** [jellyfin/jellyfin#9113]
### Please describe your bug

This was confirmed by two parties on the jellyfin subreddit [reddit thread](https://www.reddit.com/r/jellyfin/comments/10dwley/some_strange_shuffle_behavior/).  

This issue can be reproduced with both the web and the windows client.  
If a song is played from the "Songs" section and then shuffled, the shuffling seems to be biased and only choose from a predetermined part of the library. The scope of the shuffle couldn't be pinpointed exactly. 

Example for a shuffle from an alphabetical ascending order: 
", 5, A, A, A, A, A, 3, A, A, A, A, A,A, A, A, ,A, A, A,

The same happens when the order is reversed.
鬼, 月, 琥, 空, 指, 雨, 桜, 雲, 愛, 美, and so on...  
  
Shuffle from the album overview can't be tested due to the sheer volume of albums.

This issue is not expressed with the 3rd party android app "Finamp" (see pictures attached below). The app version is 0.6.10 on a Google Pixel 7 Pro.

### Jellyfin Version

10.8.0

### if other:

10.8.8

### Environment

```markdown
- OS: Debian 11/Docker
- Virtualization: Yes, Docker
- Docker Image: Linuxserver.io version:- 10.8.8-1-ls195 Build-date:- 2023-01-12T03:42:55+01:00
- Clients: Jellyfin Media Player v1.7.1
- Browser: Firefox v108.0.2
- FFmpeg Version: unknown
- Playback Method: unknown
- Hardware Acceleration: not utilized
- Plugins: unknown
- Reverse Proxy: yes. Traefik
- Base URL: /
- Networking:
- Storage: local. USB.
```

### Jellyfin logs

```shell
Log was too big for github
https://pastebin.com/UYRCTfcw
```

### Please attach any screenshots here

Shuffle Asc: 
![image](https://user-images.githubusercontent.com/17850993/213022066-7623f456-8569-45f9-92e5-92f1c94ccef5.png) 

Shuffle Des:
![image](https://user-images.githubusercontent.com/17850993/213022291-e9968e78-b17e-4840-b275-1b411519e160.png)

Finamp - 3rd party android client:
![Screenshot_20230117-224231](https://user-images.githubusercontent.com/17850993/213023961-eac338b7-4fa5-437a-84da-f13f8622be95.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Appoxo** [comment]
Issue still persists.  
Tested with:
Server: Server: Jellyfin | Version: 10.8.10 | OS: Linux | Architektur: X64
Desktop (Browser): Firefox 113.0.1 (64-Bit)  
Mobile (Android) Jellyfin App: v2.5.0

Issue does not exist with:
Mobile (Android) Finamp: v0.6.14

**Comment by Appoxo** [comment]
> I'm not sure if it's related,  but my Jellyfin only shuffles the songs on the current page. Even though I have thousands of songs, shuffling only plays through the 100 on the current page.

This is exactly the issue I mentioned.

**Comment by nuttapillar** [comment]
I usually Musicbee as my music player, and it has no problem shuffling a library of over 200,000 songs, so it'd be good if Jellyfin could work just as well. It even only takes about 1 second to filter the library to match my search results, whilst Jellyfin is very slow. I'm hoping they can also improve this department. Musicbee really is a perfect example of how it should work.

**Comment by Appoxo** [comment]
@nuttapillar As I mentioned in my issue Finamp also has no problem. Currently at 2900 songs and Finamp has no problem shuffling the whole library

Regarding responsiveness: I feel like Jellyfin is very responsive (most of my stuff is on HDD while the application is in docker and on NVMe-SSD. I feel like the application waits for the user finish typing before searching (which I prefer. I do not need a prediction results). But that part is outside of scope.

**Comment by Appoxo** [comment]
Issue still persist.
Tested on Jellyfin Android Client 2.6.0-beta2
Smartphone: Pixel 7 Pro - Android 13

**Comment by sotornien** [comment]
V10.9.7 on Docker Linux, Issue still persists. Clicking on the Music Library followed by the click on the shuffle button 
![image](https://github.com/user-attachments/assets/11cc416b-9074-47e3-a2b8-15eab2eb535e) will shuffle always the same songs. In my Case only the Songs from the last 3 Albums gets into the shuffle Playlist.

@NutchapolSal Thanks for the hint about using the Dot-Menu (
![image](https://github.com/user-attachments/assets/833ea580-1b47-4133-bec0-109e78a05025)
) from Home. This will at least shuffle all Songs. But the Playlist is still limited
