### ISSUE TITLE
[Issue]: Some degraded posters on Jellyfin Web in Chrome, seems to be related to fillheight calculation

### ISSUE THREAD

**Issue by deslea** [jellyfin/jellyfin#9125]
### Please describe your bug

Selected posters appear degraded when browsing libraries in Jellyfin Web, as shown in the first image below (Becoming Anne Boleyn and Becoming King). 

The posters are able to be viewed in good quality in other views, see second image (Becoming Anne Boleyn page).

On comparing the affected versus unaffected images in Chrome Inspector, the affected images have a different fillHeight to the unaffected ones:

Affected example, fillHeight 120: 
button data-action="link" class="cardImageContainer coveredImage cardContent itemAction lazy blurhashed lazy-image-fadein-fast" aria-label="Becoming King True Royalty Presents The Untold Story" style="background-image: url(&quot;http://192.168.1.30:8096/Items/264339f002e5b623ef8b38854b64f16b/Images/Primary?fillHeight=120&amp;fillWidth=213&amp;quality=96&amp;tag=ce6f0e4514d771bc88b1d79572657605&quot;);"

Unaffected example, fillHeight 320:
button data-action="link" class="cardImageContainer coveredImage cardContent itemAction lazy blurhashed lazy-image-fadein-fast" aria-label="Being James Bond" style="background-image: url(&quot;http://192.168.1.30:8096/Items/02fc7db96f871d42a0074d88c2552ea9/Images/Primary?fillHeight=320&amp;fillWidth=213&amp;quality=96&amp;tag=f96120ae90cd9ffe530c229ccf0e8833&quot;);"

On manipulating an affected image in Inspector to have a fillHeight (of, in this case, 320) to match the unaffected images, the problem is resolved in that instance for that image, see third image below (Becoming King has had the fillHeight changed, Becoming Anne Boleyn left alone for contrast).

A common denominator is that the affected images are of a different ratio to the display (eg, shows for which I only have a 16:9 thumbnail on a poster view).

Places where it **doesn't** happen: (1) The FireTV app. The FireTV app shows what I would consider expected behaviour, the image is cut off but not degraded, see the fourth image below. (2) In Chrome with other examples of image mismatch, eg square icons on Folder view with poster icons, icons are cut off but not degraded, see fifth image below. (3) Safari on iPad surfing the web interface doesn't show the degradation (I haven't included a shot of that), which suggests to me that some browsers can recover from the problem but Chrome can't.

If relevant, the library I am using here is a mixed type library. I don't have any corresponding examples in an exclusively Movies or Shows library for comparison.

### Jellyfin Version

Other

### if other:

10.8.6

### Environment

```markdown
- OS: Windows
- Virtualization: None
- Clients:  Unaffected: FireTV.
- Browser: Affected: Chrome in some views. Unaffected: Safari.
```

### Please attach any screenshots here

Image 1: Degraded icons in Jellyfin Web (Battle of Agincourt, Becoming Anne Boleyn, Becoming King), common denominator is mismatch in ratio between icon and view (landscape icon, poster view)
![image](https://user-images.githubusercontent.com/71571014/213404150-8d2c5363-3a86-4833-b469-1cb55e7bd042.png)

Image 2: Becoming Anne Boleyn shown correctly in another view
![image](https://user-images.githubusercontent.com/71571014/213404379-b3380a83-6fa9-4e77-a233-7554c74c1d0b.png)

Image 3: Becoming King corrected by manipulating fillHeight in browser dev tools to match non-degraded example Becoming James Bond
![image](https://user-images.githubusercontent.com/71571014/213404584-cb41d1c5-e0e2-45f9-bdbd-db1edd05c367.png)

Image 4: Same library on Jellyfin FireTV app, shows expected behaviour, icons cut off but no degradation
![image](https://user-images.githubusercontent.com/71571014/213408776-7c2c5701-8a60-4fef-8eff-690e72ddc3e3.png)

Image 5: Different library with a different type of mismatch in Chrome (square display/poster icon), shows expected behaviour, icons cut off but no degradation.
![image](https://user-images.githubusercontent.com/71571014/213410281-856861d1-daf2-4a82-b6d7-3a76877b460d.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ZIWAE** [comment]
same issue, any solution?

**Comment by ZIWAE** [comment]
not fixed yet
