### ISSUE TITLE
[Issue]: Use correct audio and subtitles on "next episode" (browser client)

### ISSUE THREAD

**Issue by DevPGSV** [jellyfin/jellyfin#9141]
### Please describe your bug

This issue happens when watching a TV show with multiple episodes, and those episodes have multiple audio and/or subtitle streams.
If the first episode is played, and the audio or the subtitles are changed to a value different to the default (for example, it starts playing in spanish and then I change the language to english with subtitles in spanish), it works as expected. Then that episode ends, and the second episode begins. 
When the second episode starts playing, it starts in the default audio and subtitle configuration, not the one that was selected before. However, when trying to to configure the audio and subtitles again, the list of languages does remember the selection of the previous episode. So, in this example, in the second episode it would start playing in spanish without subtitles, but it would say that it is playing in english with spanish subtitles.

### Jellyfin Version

Other

### if other:

10.8.7

### Environment

```markdown
- OS: ArchLinux
- Virtualization: Docker
- Clients: Browser
- Browser: Brave Versión 1.46.153 Chromium: 108.0.5359.128 (Build oficial) (64 bits)
```

### Jellyfin logs

```shell
No logs relevant to this issue
```

### FFmpeg logs

```shell
No logs relevant to this issue
```

### Please attach any screenshots here

![image](https://user-images.githubusercontent.com/5631093/213813753-da4f25a8-5c30-4071-a9d9-a8249a4e2ac0.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
This is not a bug, but an existing feature request: https://features.jellyfin.org/posts/194/remember-subtitle-and-audio-track-choice-between-episodes

**Comment by gurka** [comment]
Isn't this considered a bug now, since this https://github.com/jellyfin/jellyfin-web/pull/2621 has been merged?
Although, this ticket might belong to jellyfin-web

**Comment by N0K0** [comment]
Seems related to this issue too: https://github.com/jellyfin/jellyfin-web/issues/3994
