### ISSUE TITLE
Real time monitoring issue

### ISSUE THREAD

**Issue by ThaBozz** [jellyfin/jellyfin#9144]
### Please describe your bug

I have real time monitoring enabled for my movie library. The moment I add a new movie folder to the library, I see the following on the log (slightly edited for privacy):

[2023-01-21 06:27:52.718 +00:00] [ERR] Error in Directory watcher for: "<LIBRARY_PATH>"
System.UnauthorizedAccessException: Access to the path '<LIBRARY_PATH>/<MOVIE_PATH>' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---

However, if I scan the library manually through the Web UI, Jellyfin picks up the new movie.

File permissions are 1770 for movie folders, 0640 for files
File ownership is <MY_USER>:jellyfin

### Jellyfin Version

Other

### if other:

Jellyfin.Server 10.8.8.0

### Environment

```markdown
- OS: Ubuntu 22.04.1 LTS
- Virtualization: None (Bare Metal Install)
- Clients: N/A
- Browser: N/A
- FFmpeg Version: N/A
- Playback Method: N/A
- Hardware Acceleration: N/A
- Plugins: AudioDB, kodi Sync Queue, MusicBrainz, OMDb, Studio Images, TMDb
- Reverse Proxy: None
- Base URL: none
- Networking: N/A
- Storage: local (zfs)
```

### Jellyfin logs

```shell
[2023-01-21 06:27:52.718 +00:00] [ERR] Error in Directory watcher for: "<LIBRARY_PATH>"
System.UnauthorizedAccessException: Access to the path '<LIBRARY_PATH>/<MOVIE_PATH>' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
```

### FFmpeg logs

```shell
N/A
```

### Please attach any browser or client logs here

N/A

### Please attach any screenshots here

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by agilob** [comment]
You have deployed it incorrectly, give more permissions to the library.

**Comment by ThaBozz** [comment]
Wait, what are the actual required permissions? Do the required permissions
differ between real time monitoring and manual scan? As I stated, manual
scan works with those permissions. Thanks.

**Comment by ThaBozz** [comment]
Now I changed to 0770 on directories (U+RWX,G+RWX), 0660 on files (U+RW, G+RW), and I am still getting the same error. Also, manual library scanning works, so I find it unlikely to be a permissions issue.
