### ISSUE TITLE
Setting Cache Dir to Root Directory Causes Recursive Deletion of Files

### ISSUE THREAD

**Issue by brian-armstrong** [jellyfin/jellyfin#9158]
Hello,

I was recently trying out Jellyfin on Windows and set the cache directory to one of my root disk drives. I figured it would create a subdirectory for itself as most programs do. Apparently instead it just decided that this entire directory was Jellyfin's. Later it did a `Emby.Server.Implementations.ScheduledTasks.Tasks.DeleteCacheFileTask` which, to my horror, deleted just about everything in this directory.

To not automatically create subdirectory in the configured cache directory while also automatically periodically `rm -rf`ing the contents of this directory is, in my opinion, a massively reckless combination of options. This runs counter to the common sense of most other applications and creates a dangerous scenario where user data can be deleted. The server config presents no warning that the top-level directory given to CachePath will be periodically cleared.

**Comment by 1337joe** [comment]
This also happens for transcode and possibly log directories. Closing this in favor of #9785 to cover all cases
