### ISSUE TITLE
Let installation admin enforce password strength

### ISSUE THREAD

**Issue by iacchi** [jellyfin/jellyfin#916]
Currently, users can choose whatever they want as password. It would be good if, in the backend, there was a setting to enforce some kind of password strength that the admin user can activate for all users. The options that I have in mind are: minimum password length, force presence in the password of lowercase and/or uppercase and/or numbers and/or special characters. These 5 fields would be enabled/disabled individually and if a user changes or sets a password that is not up to the configured standard, the system will throw an error to the user. Depending on the settings, there should be a paragraph of text in the change password page to explain to users what the password requirements are.

**Comment by LeoVerto** [comment]
[zxcvbn](https://github.com/dropbox/zxcvbn) might be a good library for doing this in a "smart" way.

**Comment by EraYaN** [comment]
Or this one: https://github.com/mickford/zxcvbn-cs for server side password strength calculations. Since otherwise it's not enforceable.
