### ISSUE TITLE
[Issue]: Hardware acceleration for amdgpu r7 260

### ISSUE THREAD

**Issue by picarica** [jellyfin/jellyfin#9167]
### Please describe your bug

i cant seem to get hardware acceleration working, i have .mkv with h265 coding, and the video is fine i can play it fine, but when i play it in browser or via kodi plugin on remote machine, it says media is not supported
my setup is TrueNAS with jellyfin plugin in jail, when downloading package drm-kmod but it still doesnt work, i could only find gudes how to make it work via docker, but i am not and dont want to use docker what are the needed packages for plain freebsd hardware acceleration?

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Frebbsd
- Virtualization: None or jail chroot
- Clients: browser, raspberry pi 4 kodi
- Browser: Firefox newest
- FFmpeg Version: not sure, the one packaged with it
- Playback Method: not sure, via browser or that kodi plugin addon type of playback
- Hardware Acceleration: triedm AMD fmp and VAAPI
- Plugins: None yet
- Reverse Proxy: None
- Base URL: nope
- Networking: works local network
- Storage: local NAS
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nyanmisaka** [comment]
R7 260 is too old for H.265 decoding.
You need RX 400 series and newer for H.265 10bit playback.

**Comment by picarica** [comment]
> 

oh damn, is there any other way to enabled hardware decoding? for example decode video client side for my kodi? or to enable software decoding ?
