### ISSUE TITLE
ratings-kz.csv

### ISSUE THREAD

**Issue by WWWesten** [jellyfin/jellyfin#918]
**Is your feature request related to a problem? Please describe.**

Old version is based on a old rules in the Law about Culture, they now are deprecated.

**Describe the solution you'd like**

Change content of the file ratings-kz.csv by new laws (Law about Cinematography and Law about protect children from harmful information see http://adilet.zan.kz/rus/docs/Z1900000212 and http://adilet.zan.kz/rus/docs/Z1800000169)

**Describe alternatives you've considered**

No

**Additional context**

New content of the file ratings-kz.csv is as followed:
```
KZ-6-,0
KZ-6+,6
KZ-12+,12
KZ-14+,14
KZ-16+,16
KZ-18+,18
KZ-21+,21
```

**Comment by JustAMan** [comment]
@WWWesten can you submit a PR with fixed csv file?

**Comment by WWWesten** [comment]
https://github.com/jellyfin/jellyfin/pull/984
