### ISSUE TITLE
[Issue]: multi pod in Kubernetes 

### ISSUE THREAD

**Issue by yuval987** [jellyfin/jellyfin#9183]
### Please describe your bug

Hi,
I installed the last version of jellyfin in k8s and I have a problem when I try to add a new pod.
I'm attaching a log from the pod.
Thanks

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Linux 
- Virtualization: k8s
- Clients: all
- Browser:Ll
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
Busy: SQLitePCL.pretty.SQLiteException: database is locked
   at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cvium** [comment]
Not a bug. Jellyfin cannot be scaled.
