### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by Sirfrancis17** [jellyfin/jellyfin#919]
I try install plugins from "https://repo.jellyfin.org/releases/plugin/"
But only work opensubtitules
The others (trakt, anime, autoorganize) Dont work and Dont show in settings
Its normal?

**Comment by anthonylavado** [comment]
@Sirfrancis17 Yes, this is normal. Some must be updated with every release, and that will happen with these plugins. Hopefully this is later today.

**Comment by Sirfrancis17** [comment]
My versión is not updates. I user docker and my versión is 10.1.0. Its need update?

**Comment by WWWesten** [comment]
I can see the Tract in the My Plugins list and see the plugin's settings page. Not yet configure with the Tract site.
@Sirfrancis17 Autoorganize plugin is as You are described.
BTW JF is latest 10.2.0 version (not rc2). Plugins are installed from Catalog page (now there empty).

**Comment by anthonylavado** [comment]
10.2.0 is still building for Docker. We're in queue and waiting.

**Comment by Sirfrancis17** [comment]
Then it is normal that being in 10.1 I do not work plugins?

**Comment by anthonylavado** [comment]
@sirfrancis17 - Yes, plug-ins are only officially supported as of 10.2.0.

**Comment by Sirfrancis17** [comment]
i update jellyfin to 10.2 but the plugins dont work (only opensubtitules) it's normal?

**Comment by JustAMan** [comment]
I don't think we've officially released the plugins yet, only the server.
Plugins will be released soon - we're fixing them to work with 10.2.0 (as far as I'm aware what's left for most is just packaging and publishing new versions, so should happen really soon).

CC @cvium and @joshuaboniface for more information on plugins.

**Comment by Sirfrancis17** [comment]
Thanks

**Comment by Sirfrancis17** [comment]
Thanks. Trakt and anime Works but autoorganize crash. It's shows server error

**Comment by JustAMan** [comment]
@Sirfrancis17 please report that crash at respective plugin [repo](https://github.com/jellyfin/jellyfin-plugin-autoorganize)
