### ISSUE TITLE
Add OCI image annotations to docker hub published jellyfin/jellyfin images

### ISSUE THREAD

**Issue by candrews** [jellyfin/jellyfin#9209]
The images published to https://hub.docker.com/r/jellyfin/jellyfin do not have [OCI image annotations](
https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys), such as `org.opencontainers.image.source`

These annotations are useful for people to manual use as well as for use by tools. For example, [Snyk uses them in its UI](https://snyk.io/blog/how-and-when-to-use-docker-labels-oci-container-annotations/) and [Renovate uses them to find release notes](https://github.com/renovatebot/renovate/blob/34.115.1/lib/modules/datasource/docker/readme.md).

I believe at least these labels should be added to the images:
* `org.opencontainers.image.source`
* `org.opencontainers.image.revision`

**Comment by nielsvanvelzen** [comment]
We're rewriting our CI and with that the way the docker images are created. I believe @h1dden-da3m0n already implemented OCI labels.

**Comment by crazy-max** [comment]
You could build the image using the OCI exporter and set `annotation.<key>=<value>` attribute: https://docs.docker.com/build/exporters/oci-docker/#annotations

**Comment by candrews** [comment]
> We're rewriting our CI and with that the way the docker images are created.

I submitted a PR to add the label within the current CI implementation: https://github.com/jellyfin/jellyfin/pull/9210

**Comment by crazy-max** [comment]
Be careful, a `label` is not an OCI annotation and will not be seen as such.

**Comment by candrews** [comment]
FWIW, it seems others are setting OCI annotations via labels, for example mariadb: https://github.com/MariaDB/mariadb-docker/commit/4a7fcb60b1ae342f5855d075e648450843f2473d

Is there a different way other than labels that this should be done?
