### ISSUE TITLE
Movies are not identified if flat movie organization is used

### ISSUE THREAD

**Issue by alashow** [jellyfin/jellyfin#921]
**Describe the bug**
In `10.2.0` If flat movie organization is used (`/movies/Movie (year).ext`), Jellyfin fails to identify movies.
It identifies them as "Movies", I guess the parent folder's name.

**Expected behavior**
Prior to `10.2.0` movies were identified correctly if flat movies organization is used.

**Screenshots**
https://imgur.com/a/3fKIMuN

**System (please complete the following information):**
 - OS: Docker
 - Browser: Chrome
 - Jellyfin Version: 10.2.0

**Additional context**
Possible causes: https://github.com/jellyfin/jellyfin/pull/739, https://github.com/jellyfin/jellyfin/pull/621

**Comment by sparky8251** [comment]
This is a confirmed regression and has been labeled as such.

**Comment by liggy1** [comment]
Not adding a new issue, because I think this could be related. My movies are organized in a way
`/Movie Title/File.ext`
when I have multiple versions (e.g. DVD and Blu-Ray) then it's
`/Movie Title/Movie Title - DVD.ext`
`/Movie Title/Movie Title - BD.ext`
in some cases I also have 
`/Movie Title/Extras/Whatever special I have.ext`

Up to `10.1.0` this ended up in one entry with the option to choose between DVD and BD version. Extras didn't show since switching from Emby to Jellyfin, but that's a different issue and I already raised #561 for this one.

With `10.2.0` I now have two entries for the movie plus one movie named "Extras". Would be great if this behavior could be reverted to what it was before.

**Comment by cvium** [comment]
It works for me 
![image](https://user-images.githubusercontent.com/675118/52911856-03238780-32aa-11e9-91d0-895b09d53d6f.png)

![image](https://user-images.githubusercontent.com/675118/52911900-5c8bb680-32aa-11e9-99aa-2ad0022489e3.png)

**Comment by iacchi** [comment]
alashow: did you run a full library sescan asking to overwrite all metadata before you ended up with that, or did it do it on its own without any input from you? In the second case, my movie library is still fine and I also use a flat organisation, so I can't say that I can reproduce the bug. In the first case, I think it's related to something that I just posted on the jellyfin subreddit: https://www.reddit.com/r/jellyfin/comments/arjjsx/entry_identification_broken_in_1020/

**Comment by liggy1** [comment]
That's strange indeed. I just created folders and some empty files to confirm the behavior
![image](https://user-images.githubusercontent.com/42473363/52912042-36671600-32ac-11e9-9941-7c3c3efd37d6.png)
Then did a rescan of my movies and that's what my latest movies are supposed to be
![image](https://user-images.githubusercontent.com/42473363/52912054-5f87a680-32ac-11e9-9a2d-da6e322e19e1.png)

I don't think that it matters, but just for completeness, I'm using the Docker image on Debian Linux

**Comment by alashow** [comment]
@iacchi the first scan was triggered automatically ("Enable real-time monitoring"). I tried rescanning with "Replace all metadata" option but it didn't help.

My movie media files strictly followed "flat movie organization" (one quality, `{Movie} ({year}.{ext}` + `{Movie} ({year}.{lang}.srt`) so it was easy to re-organize / group them with this little script:

<details>
  <summary>Show the script</summary>

```bash
#!/bin/bash

# move "Movie (year).mkv" files to respective "Movie (year)" folder
for full_filename in *mkv; do
  extension="${full_filename##*.}"
  filename="${full_filename%.*}"
  mkdir -p "$filename"
  mv "$full_filename" "$filename/$full_filename"
done

# move "Movie (year).mp4" files to respective "Movie (year)" folder
for full_filename in *mp4; do
  extension="${full_filename##*.}"
  filename="${full_filename%.*}"
  mkdir -p "$filename"
  mv "$full_filename" "$filename/$full_filename"
done

# move "Movie (year).avi" files to respective "Movie (year)" folder
for full_filename in *avi; do
  extension="${full_filename##*.}"
  filename="${full_filename%.*}"
  mkdir -p "$filename"
  mv "$full_filename" "$filename/$full_filename"
done

# move "Movie (year).eng.srt" files to respective "Movie (year)" folder
for full_filename in *eng.srt; do
  extension="${full_filename##*.}"
  filename="${full_filename%.eng.*}"
  mkdir -p "$filename"
  mv "$full_filename" "$filename/$full_filename"
done

# move "Movie (year).en.srt" files to respective "Movie (year)" folder
for full_filename in *en.srt; do
  extension="${full_filename##*.}"
  filename="${full_filename%.en.*}"
  mkdir -p "$filename"
  mv "$full_filename" "$filename/$full_filename"
done
```

</details>

**Comment by JustAMan** [comment]
@alashow if you can build yourself a test server, could you please try with https://github.com/jellyfin/jellyfin/pull/924 and report back? It might be a fix for your issue.

**Comment by alashow** [comment]
I don't know how to build the whole server. I use Docker container's provided in `jellyfin/jellyfin`.
Also, like I said above, I already re-organized my movie library to non-flat structure.

It should be easy enough to reproduce this error though?

**Comment by NeverEnoughTime** [comment]
I can confirm this is happening on my server.  I have a folder named "Incoming" I drop my rips into to double check they encoded okay before I move them to the proper folders.  After 10.2.0 they all come up as Incoming now.  The only exception I've noticed is that a couple reprips I did, that I also dropped into the Incoming folder, did correctly identify, presumably because they already exist in the database in another folder.

OS: Ubuntu 18.04

**Comment by liggy1** [comment]
#933 fixes the grouping behaviour again - at least for me

**Comment by Evoley** [comment]
Tried the fix and it's still not matching some movies for me. About 75% of my library.
[log_20190220 - Copy.log](https://github.com/jellyfin/jellyfin/files/2887541/log_20190220.-.Copy.log)

**Comment by joshuaboniface** [comment]
@Evoley That looks like a different (media-related perhaps) bug - we've reverted all the code that touched this functionality since 10.1.0 in 10.2.1, can you test that out? IF that doesn't solve it let's open a new issue with that particular error.

**Comment by Evoley** [comment]
@joshuaboniface Re-added the folder and It's still missing movies. Missed about 12 movies in total. I haven't gotten the error I posted above yet.

**Comment by cvium** [comment]
The errors you're experiencing seem unrelated to the original issue. Chapter and image extraction works for me. Maybe the metadata in your video files is bad.

Either way, please open a new issue.
