### ISSUE TITLE
How to remove the PlaySessionId field in video stream link?

### ISSUE THREAD

**Issue by niannianyouyu** [jellyfin/jellyfin#9225]
### Discussed in https://github.com/jellyfin/jellyfin/discussions/9224

<div type='discussions-op-text'>

<sup>Originally posted by **niannianyouyu** February  1, 2023</sup>
Hi,

I'd like to remove the `PlaySessionId` field in video stream link?
(e.g: http://192.168.x.x:8096/video/..../stream.mp4?PlaySessionId=....&amp;DeviceId=...&amp;MediaSourceId=..., we change it to http://192.168.x.x:8096/video/..../stream.mp4?....&amp;DeviceId=...&amp;MediaSourceId=...)

I have tried to modify the `main.jellyfin.bundle.js` in C:\Program Files\Jellyfin\Server\jellyfin-web, to let the function containing the `PlaySessionId` field return null, but the `PlaySessionId` field still exists in stream link. How should I do? </div>

**Comment by nielsvanvelzen** [comment]
Please don't open both an issue and discussion. Closing the issue in favor of the discussion.

**Comment by niannianyouyu** [comment]
OK, Sorry for this.
