### ISSUE TITLE
rework how fullscreen works for WebUI

### ISSUE THREAD

**Issue by JourneyOver** [jellyfin/jellyfin#923]
I think this is more an enhancement than a Feature Request/Bug so I used the Enhancement Request for this.

**Is your feature request related to a problem? Please describe.**

Would love to make the switch to jellyfin, but the way fullscreen on the video player for the WebUI works is so annoying due to the fact that it fullscreens the entire browser, instead of only fullscreening the video player. When the video ends (be it when the end of the movie/episode ends or I force end it) it ends up keeping the entire browser fullscreen, making me have to go about forcing it back to non-fullscreen.

**Describe the solution you'd like**

Make going fullscreen on the video player, make just the player go fullscreen (Like pretty much how Plex/Youtube/any other player works) instead of the entire browser.

**Comment by joshuaboniface** [comment]
The ideal solution isn't possible with how the WebUI currently works (we will change that, eventually). But for now the linked PR above should fix the the issue. Please test the 10.2.1 release and let us know.

**Comment by JourneyOver** [comment]
@joshuaboniface Yep looks to be working just fine, once the video ends it looks to exit fullscreen mode :D so even though the current method is not your ideal solution it at least looks to be working perfectly ^^

**Comment by JustAMan** [comment]
Closing as verified by submitter.
