### ISSUE TITLE
thumbnail on photo playing

### ISSUE THREAD

**Issue by jerome-cui** [jellyfin/jellyfin#9235]
Description: low quality photos when playing photos in a photo library

I have lots of photos each with size more than 10M and I imported into jellyfin as photo library. On playing the photos in one folder it will always download the original file. It would be slow and mass network usage. I hope it could use a quality reduced photos or thumbnails. Maybe we can config the thumbnail size or based on the device screen size.

**Comment by Bond-009** [comment]
Feature requests go here: https://features.jellyfin.org/
