### ISSUE TITLE
[Issue]: "favorites > songs > shuffle" doesn't work with DLNA 'Play To'

### ISSUE THREAD

**Issue by mdorman** [jellyfin/jellyfin#9240]
### Please describe your bug

In both the web interface and the Jellyfin IOS app, if I navigate to the list of my favorite songs and click/tap "Shuffle", songs will start playing in an apparently random order.

On the other hand, if I choose to "Play On" a DLNA device, the "Shuffle" button becomes unresponsive---and if the shuffle was already playing something, when I choose the DLNA device, playback will stop.

On the other hand, I do successfully stream albums and individually picked songs via DLNA all the time.

### Jellyfin Version

10.8.9

### Environment

```markdown
- OS: NixOS
- Virtualization: N/A
- Clients: Browser, IOS
- Browser: Firefox 10X
- FFmpeg Version: 5.1.2
- Playback Method: DLNA
- Hardware Acceleration: None
- Plugins: none
- Reverse Proxy: none
- Base URL: none
- Networking: Host
- Storage: local
```

### Jellyfin logs

```shell
There is literally no logging produced when I attempt to initiate playback this way.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SjoerdV** [comment]
same issue with 'mpv-shim' on desktop AND Web Player (wrappers) -> no shuffle for favorites.
