### ISSUE TITLE
jellyfin remux asynchronous after skipping

### ISSUE THREAD

**Issue by DerP4si** [jellyfin/jellyfin#9241]
If using Chrome the Video get's remuxed, rather then transcoded. This remuxing leads to an delay between audio n video in wich the video is delayed between 700-2800ms. It seems to only occur if not started from 0:00.

**Media Info of the file**
westworld.s01e02.german.dl.1080p.bluray.x265
Container: mkv
Pfad: /medien/H265/Serien/Westworld/S01/Westworld.S01E02.German.DL.1080p.BluRay.x265/westworld.s01e02.german.dl.1080p.bluray.x265.mkv
Größe: 2580 MB

Untertitel
Titel: Ger - Standard - Erzwungen - ASS
Sprache: ger
Codec: ASS
Standard: Yes
Erzwungen: Yes
Extern: No

Video
Titel: 1080p HEVC SDR
Codec: HEVC
Profil: Main
Level: 120
Auflösung: 1920x1080
Seitenverhältnis: 16:9
Zeilensprungverfahren: No
Bildrate: 23.976025
Bitrate: 6156 kbps
Bit-Tiefe: 8 bit
Videobereich: SDR
Video range type: SDR
Farbraum: bt709
Farbübertragung: bt709
Primärfarben: bt709
Pixelformat: yuv420p
Referenz-Frames: 1

Audio
Titel: Surround - Ger - Dolby Digital - 5.1 - Default
Sprache: ger
Codec: AC3
Darstellung: 5.1
Kanäle: 6 ch
Bitrate: 640 kbps
Abtastrate: 48000 Hz
Standard: Yes
Erzwungen: No
Extern: No

Audio
Titel: Surround - Eng - DTS - 5.1
Sprache: eng
Codec: DTS
Profil: DTS
Darstellung: 5.1
Kanäle: 6 ch
Bitrate: 1536 kbps
Abtastrate: 48000 Hz
Standard: No
Erzwungen: No
Extern: No

**Logs**
[remux_logs.txt](https://github.com/jellyfin/jellyfin/files/10578015/remux_logs.txt)

**FFmpeg Logs**
[ffmpeg.txt](https://github.com/jellyfin/jellyfin/files/10578016/ffmpeg.txt)

**Stats for Nerds Screenshots**
![image](https://user-images.githubusercontent.com/28807283/216577252-15059e8e-a265-45ff-928b-03cdc0f257d9.png) 
![image](https://user-images.githubusercontent.com/28807283/216577337-2be6029c-bb6f-49f1-bf52-7e1576df68a4.png)
(sry for the german language)

**Server System (please complete the following information):**
 - OS: Docker on Linux, Synology
 - Jellyfin Version: 10.8.9
 - Hardware settings & device: VAAPI on Intel Celeron J4125
 - Reverse proxy: apache (ProxyPass /socket ws://.... like in the documentation)
 - Other hardware notes: Local Media
 
**Client System (please complete the following information):**
 - Device: PC
 - OS: Windows 10
 - Client: Web/Browser
 - Browser (if Web client): Chrome
 - Client and Browser Version:  10.8.9 and 109.0.5414.120

**Comment by magns12** [comment]
Similar issue here

**Comment by nicolai455** [comment]
Its probably the same issue as #9330

**Comment by Matix-Media** [comment]
Same issue. Limiting audio to 7.1 on desktop chrome fixes the issue for me, but only desktop, not mobile android app (also chrome based?)

**Comment by LiamKarlMitchell** [comment]
Having same issue on Google Chrome and Opera, when skipping, recently installed intro skipper plugin which made it more obvious, also happens when manually skipping or when continuing playback from non 0:00.

In playback I set Audio to Stereo but it did not help.
Is there a way to force transcode to some other format as to not use direct streaming? Or disable remuxing?
Or is it something to change in my Video drivers - Radeon?

Tried to check on Edge/Firefox but I get this error for most media but maybe that is unrelated.

> Playback Error
> This client isn't compatible with the media and the server isn't sending a compatible media format.

**Browser versions**
Google Chrome
Version 110.0.5481.178 (Official Build) (64-bit)
"Chrome is up to date" Version 111.0.5563.65 (Official Build) (64-bit)

Running from WSL2 docker container on Windows 10 host.

**Comment by lionking102** [comment]
Same issue here.

**Comment by NickCloudAT** [comment]
Same issue, but only noticed it after changing my librarys to a network path (switched from local storage to a NAS).
Only seems to happen with the web-based player.
Happens for me on Chrome and in the Android App when not using the integrated but web-based player.

Also can confirm what others say: Seems to only happen when not starting from 00:00 but when pausing, skipping etc.

**Comment by freddiN** [comment]
I had the same issue, but it does HOT happen with the new v0.3.1 vue client.

**Comment by thomascour** [comment]
Same here, using Chrome or WebOs app.. only on HVEC direct streaming. audio and subtitles out of sync when skipping, it really sucks.

**Comment by rifuller** [comment]
First time Jellyfin user. I believe I'm experiencing this issue as well. Only when skipping. 

```
Playback Info
Player:
Html Video Player
Play method:
Direct streaming
Protocol:
http
Stream type:
Video
Video Info
Player dimensions:
3584x1814
Video resolution:
1920x1080
Dropped frames:
0
Corrupted frames:
0
Direct Streaming Info
Video codec:
HEVC (direct)
Audio codec:
AAC
Original Media Info
Container:
webm
Size:
135.8 MiB
Bitrate:
2.9 Mbps
Video codec:
HEVC Main 10
Video bitrate:
2.6 Mbps
Video range type:
SDR
Audio codec:
EAC3
Audio bitrate:
256 kbps
Audio channels:
6
Audio sample rate:
48000 Hz
```

**Comment by Bond-009** [comment]
Fixed by https://github.com/jellyfin/jellyfin-web/pull/4385
