### ISSUE TITLE
Shared video can be watched online

### ISSUE THREAD

**Issue by BearHero520** [jellyfin/jellyfin#9244]
**Describe the feature you'd like**

I hope that I can customize the shared video, for example, share the video to other users and watch it directly on the browser without logging in. Although there is a direct link to share, it can only be downloaded on most browsers. Finally, I hope that the jellfin project will get better and better
**Additional context**

![image](https://user-images.githubusercontent.com/57251023/216505817-fe91cae0-e955-4d36-a281-5bb84e5ef1f9.png)

**Comment by crobibero** [comment]
Sounds like you want this existing feature request.

https://features.jellyfin.org/posts/1313/anonymous-guest-access
