### ISSUE TITLE
Ability to whitelist content for a profile

### ISSUE THREAD

**Issue by smidley** [jellyfin/jellyfin#928]
It would be great to have the ability to block all content on a users account unless it’s whitelisted at the movie or show level.

**Comment by JustAMan** [comment]
Could you please follow the template for feature request? At least describe a use case for what you want so it's more clear what you want to be done.

**Comment by smidley** [comment]
Sorry about that, let me try to phrase it differently.  
When I create a user account, I currently have the ability to go to Parental Controls, then click "Block Items with Tags".  This is fine in some cases, but my content gets added randomly, and this means that if I'm blocking all content with certain tags for one of my kids profiles, and then an unrated movie gets randomly added and I don't notice, they would have this possibly inappropriate movie in their profile available to them.

The solution would be to block ALL content unless it's tagged with a specific tag.
