### ISSUE TITLE
[Issue]: Latency 👾

### ISSUE THREAD

**Issue by ksyfink** [jellyfin/jellyfin#9295]

**Comment by arucard21** [comment]
You can try enabling BBR on your OS as described here: https://www.cyberciti.biz/cloud-computing/increase-your-linux-server-internet-speed-with-tcp-bbr-congestion-control/

I'm not sure exactly what this does, but it did seem to reduce my latency. Though the cost is that you use more bandwidth on the server's side. But I'm just another user here, so ymmv. 😄

**Comment by wejudging** [comment]
me too +1

**Comment by icedterminal** [comment]
Because you're behind Cloudflare. This is what is adding the latency. *Do not use Cloudflare proxy services on free accounts*. There are several reasons. Most notably it is against the terms of service. Emphasis mine:

> The Services are offered primarily as a platform to cache and serve web pages and websites. Unless explicitly included as part of a Paid Service purchased by you, you agree to use the Services solely for the purpose of (i) serving web pages as viewed through a web browser or other functionally equivalent applications, including rendering Hypertext Markup Language (HTML) or other functional equivalents, and (ii) serving web APIs subject to the restrictions set forth in this Section 2.8. **Use of the Services for serving video or a disproportionate percentage of pictures, audio files, or other non-HTML content is prohibited, unless purchased separately as part of a Paid Service or expressly allowed under our Supplemental Terms for a specific Service.** If we determine you have breached this Section 2.8, we may immediately suspend or restrict your use of the Services, or limit End User access to certain of your resources through the Services.
>
> &ndash; [Cloudflare Self-Serve Terms](https://www.cloudflare.com/terms/#28-limitation-on-serving-non-html-content)

If you proceed anyway your account may be terminated for abuse. I have asked Cloudflare support on what users can do if they have their own self-hosted media servers and want to take advantage of the security services. Here is that support inquiry:

### Me
> Per 2.8 of the Self-Serve agreement, serving a large amount of non-HTML media is prohibited unless, quote unquote: "explicitly included as part of a Paid Service"
> 
> https://www.cloudflare.com/terms/#28-limitation-on-serving-non-html-content
> 
> If a customer has self-hosted media that is located on a server in their home, all aspects of this media is handled by their server. This includes, but not limited to: encode, decode, and storage. They want to access this media over the internet (think Spotify/Netflix) but cannot enable the "orange cloud" without being in violation of the terms set out in 2.8.
> 
> What is this paid service?
> 
> I see there is a "Cloudflare Stream" - However, it appears this does not apply based on the description of the service. The user simply needs the ability to serve an already compatible media file to the requesting device over the internet through Cloudflare's proxy services, without caching.

### Cloudflare
> Hi there -
> 
> Thank you for contacting Cloudflare Support. Apologies for the delay in getting back to you; we have had an increase of tickets in recent weeks and we are currently working through the ticket queue backlog. You can also use the Cloudflare Community forums to request assistance at any time.
> 
> Per your question:
> 
> > What is this paid service?
> 
> In this context, "paid service" refers to something like Cloudflare Argo, Images, Workers, R2, Stream (as you noted), etc. where usage-based billing is applied to traffic that traverses our network. The service a customer chooses would depend on their use case.
> 
> For example, what you describe sounds like a potential use case for Argo Smart Routing, although please note that Argo Smart Routing applies to essentially all traffic that passes through our network for a given domain and can thus result in large charges for sites that handle significant amounts of media. You can review Argo billing information here: [Billing for Argo.](https://support.cloudflare.com/hc/en-us/articles/115000224192-Billing-for-Argo)
> 
> As there is no further action for Cloudflare Support to take at this point, I will mark this as 'solved.' However, you can still respond to this ticket if you have further questions related to this issue.
> 
> Kind regards,
> 
> Alex P.
> Technical Support Engineer - Cloudflare

If you continue to use Cloudflare services as you are now, you will continue to see high latency. You need to purchase the additional Argo routing which then speeds the connection up as well bringing your account in line with the terms of service. You then disable caching for video streams so your account cache storage does not hold outdated, useless stream information.
