### ISSUE TITLE
[Issue]: Nginx caching gives old Live TV data

### ISSUE THREAD

**Issue by johncsuti** [jellyfin/jellyfin#9296]
### Please describe your bug

Hello,

I setup video caching using nginx to allow for combining streams instead of creating multiple streams to jellyfin. However after using your guide, i found nginx serving dated live tv streams. Causing it to play something from the night before instead of current tv. This caused it to read as much as possible from nginx and cause buffering and "unexpected" issues when it reaches the end of the cached content.

Am i doing something wrong? I feel like it might have something to do with the way i have nginx setup. However, i don't know enough to fix it.

Please advise any config files or questions you may need/have.

### Jellyfin Version

10.8.0

### if other:

10.8.9

### Environment

```markdown
- OS: Ubuntu 22.04 LTS
- Virtualization: None direct hardware
- Clients: All
- Browser: Firefox
- FFmpeg Version: 5.1.2-Jellyfin
- Playback Method: All
- Hardware Acceleration: NVENC
- Plugins: AudioDB, Intros, MusicBrainz, OMDb, OpenSubtitles, Session Cleaner, Studio Images, and TMDb
- Reverse Proxy: Nginx 1.18.0
- Base URL: subdomain https://movies.example.com
- Networking: Host direct public ip (non private/nat) on server
- Storage: NFS (movies and recorded TV shows/series)
```

### Jellyfin logs

```shell
None
```

### FFmpeg logs

```shell
None
```

### Please attach any browser or client logs here

(REMOVED)

### Please attach any screenshots here

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by icedterminal** [comment]
Please provide your nginx config files. You can do so by using gist.github.com or zipping them and attaching them here. Before posting, please remove any sensitive information.

**Comment by icedterminal** [comment]
I also need your core configuration. This being `nginx.conf`. You add another file to that gist.

**Comment by johncsuti** [comment]
https://gist.github.com/johncsuti/285de593ae2a3cb3c8c5d917eaa053e7

**Comment by icedterminal** [comment]
You had several things that weren't optimal. Security configuration was one of the more important corrections. TLS 1.1 was removed. You should use a more modern security configuration but this requires additional setup that isn't a part of this issue.

I moved some things around in both configurations and added or removed additional directives.
[conf.zip](https://github.com/jellyfin/jellyfin/files/10750786/conf.zip)

**Comment by johncsuti** [comment]
Will give those a shot and report back. More information on how to setup jellyfin using nginx would be encouraged as non of your changes were explained or on there.

**Comment by iJokerboy** [comment]
I always wanted to try to use the cache video streams option.
I'm have jellyfin inside portainer using docker... i is running fine. Now i have no idea where to find the config file.... 
I would appreciate any tips...

**Comment by johncsuti** [comment]
> I always wanted to try to use the cache video streams option. I have jellyfin inside portainer using docker... it is running fine. Now i have no idea where to find the config file.... I would appreciate any tips...

You would need to run a web server/reverse proxy in another container and point the proxy to jellyfin. You can't just change a config file in the jellyfin docker container. I have 3 servers setup for jellyfin as fallows.

Host 1: web server/ reverse proxy
Host 2: Jellyfin
Host 3: Media vault (NAS) using NFS
When you go to watch a movie using my servers your request hits Host 1 and uses a cache if possible. If not it goes to Host 2 to start the stream. Host 2 then grabs the file in small blocks using NFS from Host 3.

**Comment by icedterminal** [comment]
> More information on how to setup jellyfin using nginx would be encouraged as non of your changes were explained or on there.

That's *a lot* to explain. Which is why I didn't include any comments. I would be happy to explain and answer your questions, but GitHub issues isn't the place for such a long topic.

Feel free to reach out via Discord (icedterminal#1704) or email.

**Comment by johncsuti** [comment]
I understand each option i was saying that as im sure a lot of new people won't understand your configs. or somethings like ssl_conf/oscp_caching wont work on default installations.

**Comment by icedterminal** [comment]
> somethings like ssl_conf/oscp_caching wont work on default installations.

Hmmm. These do work on a default installation. I'm not sure where you're getting they don't.

**Comment by johncsuti** [comment]
> > somethings like ssl_conf/oscp_caching wont work on default installations.
> 
> Hmmm. These do work on a default installation. I'm not sure where you're getting they don't.

These googling them seems to lead to nowhere.
nginx: [emerg] unknown directive "ssl_conf_command" in /etc/nginx/conf.d/jellyfin.conf
nginx: [emerg] unknown directive "ssl_ocsp_cache" in /etc/nginx/conf.d/jellyfin.conf

**Comment by icedterminal** [comment]
Your nginx build is out of date. That's why. Just noticed it in your OP. You need to update by using the official build.

https://nginx.org/en/linux_packages.html#Ubuntu

As an aside, Ubuntu packages are "frozen" with each release. They receive security updates. Rarely feature updates. Not many people know this. So if you want more frequently updated software, you should use the official releases if available. Rather than Ubuntu's package manager.

**Comment by johncsuti** [comment]
Will update both openssl and nginx just to make sure. Openssl is running 3.0.2 where as the github is 3.0.8
