### ISSUE TITLE
[Issue]: Failed to start Jellyfin Media Server. (9369 ExecStart=/usr/bin/jellyfin $JELLYFIN_WEB_OPT $JELLYFIN_RESTART_OPT $JELLYFIN_FFMPEG_OPT $JELLYFIN_SERVICE_OPT $JELLYFIN_NOWEBAPP_OPT $JELLYFIN_ADDITI>)

### ISSUE THREAD

**Issue by SamuelBanya** [jellyfin/jellyfin#9299]
### Please describe your bug

Hello,

I have the same issue as this one... yet this one was closed for some reason without an actual resolution to the exact problem:
https://github.com/jellyfin/jellyfin/issues/5032

Either way, I'm getting the same exact thing. Same thing can be found on this related Reddit post from another person who literally gave up on your Ubuntu build, and just used Plex instead:
https://www.reddit.com/r/jellyfin/comments/z4tsmb/killed_jellyfin_process_now_cant_start_it/

**Main Gripes:**
My main gripe to start with is that your Ubuntu build itself does not work out of the box, so your team should re-test it to see if actually works, and update the installation instructions found here:
https://jellyfin.org/docs/general/installation/linux

**Now To The Actual Problem:**
I followed the instructions under 'Ubuntu Repository' found here:
https://jellyfin.org/docs/general/installation/linux

The annoying part is that it is missing the very key and crucial command to actually start the systemd service aka right before the '6. Manage the Jellyfin system service with your tool of choice:' section, there should be a command like the following (which I grabbed from an unrelated article (https://www.how2shout.com/linux/how-to-install-jellyfin-media-server-on-ubuntu-20-04-lts/):
`
sudo systemctl enable jellyfin

sudo systemctl start jellyfin
`

I mention that this is annoying, because though I am a mid-tier Linux user, you should really account for the person who is new to all of this, so include everywhere wherever possible.

That being notes, after these two commands are run, I then checked the status and found the related logs found below:
`
Feb 11 22:24:07 homebase systemd[1]: Failed to start Jellyfin Media Server.
...skipping...
× jellyfin.service - Jellyfin Media Server
     Loaded: loaded (/lib/systemd/system/jellyfin.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sat 2023-02-11 22:24:07 UTC; 85ms ago
    Process: 9369 ExecStart=/usr/bin/jellyfin $JELLYFIN_WEB_OPT $JELLYFIN_RESTART_OPT $JELLYFIN_FFMPEG_OPT $JELLYFIN_SERVICE_OPT $JELLYFIN_NOWEBAPP_OPT $JELLYFIN_ADDITI>
   Main PID: 9369 (code=exited, status=203/EXEC)
        CPU: 3ms

Feb 11 22:24:07 homebase systemd[1]: jellyfin.service: Scheduled restart job, restart counter is at 5.
Feb 11 22:24:07 homebase systemd[1]: Stopped Jellyfin Media Server.
Feb 11 22:24:07 homebase systemd[1]: jellyfin.service: Start request repeated too quickly.
Feb 11 22:24:07 homebase systemd[1]: jellyfin.service: Failed with result 'exit-code'.
Feb 11 22:24:07 homebase systemd[1]: Failed to start Jellyfin Media Server.
`

**My Own Next Steps:**
- I am honestly just going to give up and try the Docker version to see if it 'just works' since I don't remember a single issue like this last time I tried this on a separate Fedora machine.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Ubuntu Server
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:

Not sure at all. I just used the basic 'Ubuntu Repository' instructions so whatever that includes is what I have.
```

### Jellyfin logs

```shell
https://bpa.st/VIHO6
```

### Please attach any browser or client logs here

'systemd' related logs:

`
Feb 11 22:24:07 homebase systemd[1]: Failed to start Jellyfin Media Server.
...skipping...
× jellyfin.service - Jellyfin Media Server
     Loaded: loaded (/lib/systemd/system/jellyfin.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sat 2023-02-11 22:24:07 UTC; 85ms ago
    Process: 9369 ExecStart=/usr/bin/jellyfin $JELLYFIN_WEB_OPT $JELLYFIN_RESTART_OPT $JELLYFIN_FFMPEG_OPT $JELLYFIN_SERVICE_OPT $JELLYFIN_NOWEBAPP_OPT $JELLYFIN_ADDITI>
   Main PID: 9369 (code=exited, status=203/EXEC)
        CPU: 3ms

Feb 11 22:24:07 homebase systemd[1]: jellyfin.service: Scheduled restart job, restart counter is at 5.
Feb 11 22:24:07 homebase systemd[1]: Stopped Jellyfin Media Server.
Feb 11 22:24:07 homebase systemd[1]: jellyfin.service: Start request repeated too quickly.
Feb 11 22:24:07 homebase systemd[1]: jellyfin.service: Failed with result 'exit-code'.
Feb 11 22:24:07 homebase systemd[1]: Failed to start Jellyfin Media Server.

`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by srcrist** [comment]
The instructions on the documentation are outdated. The current Ubuntu instructions on the website are to run `curl https://repo.jellyfin.org/install-debuntu.sh | sudo bash. Plenty of people are running jellyfin on Ubuntu, so this isn't a general testing issue. The starting and stopping of services is not "mid-tier" Linux information, and not some process unique to jellyfin.

**Comment by synkoptik** [comment]
Wait.. I ran the new protocol or triage and I am getting the same restart schedule error.

**Comment by Stevetmq** [comment]
Same problem on a different platform.  I used the instructions  https://itsfoss.com/jellyfin-raspberry-pi on a PI 1B+

sudo systemctl enable jellyfin
steve@Home-Pi:~ $ sudo systemctl start jellyfin
steve@Home-Pi:~ $ sudo systemctl status jellyfin
× jellyfin.service - Jellyfin Media Server
     Loaded: loaded (/lib/systemd/system/jellyfin.service; enabled; preset: enabled)
    Drop-In: /etc/systemd/system/jellyfin.service.d
             └─jellyfin.service.conf
     Active: failed (Result: signal) since Fri 2024-05-31 15:29:32 EEST; 4s ago
   Duration: 91ms
    Process: 6454 ExecStart=/usr/bin/jellyfin $JELLYFIN_WEB_OPT $JELLYFIN_FFMPEG_OPT $JELLYFIN_SERVICE_OPT $JELLYFIN_NOWE>
   Main PID: 6454 (code=killed, signal=SEGV)
        CPU: 47ms

May 31 15:29:32 Home-Pi systemd[1]: jellyfin.service: Scheduled restart job, restart counter is at 5.
May 31 15:29:32 Home-Pi systemd[1]: Stopped jellyfin.service - Jellyfin Media Server.
May 31 15:29:32 Home-Pi systemd[1]: jellyfin.service: Start request repeated too quickly.
May 31 15:29:32 Home-Pi systemd[1]: jellyfin.service: Failed with result 'signal'.
May 31 15:29:32 Home-Pi systemd[1]: Failed to start jellyfin.service - Jellyfin Media Server.

The log files are empty

**Comment by cvium** [comment]
The .NET runtime does not support ARMv6. Buy some newer hardware.

**Comment by Stevetmq** [comment]
> The .NET runtime does not support ARMv6. Buy some newer hardware.

You "buy newer hardware" is both insulting(not all of us have rich daddies and mummies) and is not useful esp as the instructions included my hardware on the list of supported hardware.

**Comment by crobibero** [comment]
![image](https://github.com/jellyfin/jellyfin/assets/24963659/086ff748-5315-4456-8568-19ef2c5df053)

from https://jellyfin.org/docs/general/administration/hardware-selection/

**Comment by cvium** [comment]
The RPi 1B+ was released in 2014.

> not all of us have rich daddies and mummies

I take it that means you're young. I'm sorry I can't be of further help. We simply can't and won't support such old hardware. I don't recommend SBCs for this type of application, but I don't consider $35 to be "rich". You can probably find one used.

**Comment by Bond-009** [comment]
> So WTF does apt-get allow it to be installed???

Because you are using a debian repo on raspbian and they have different definitions of armhf, debian expects ARMv7.
https://raspberrypi.stackexchange.com/questions/87392/pi1-armv6-how-to-disable-armhf-packages

> esp as the instructions included my hardware on the list of supported hardware.

AFAIK we don't list the old pis as supported, if so please provide a link.

**Comment by Stevetmq** [comment]
> 

> The RPi 1B+ was released in 2014.
> 
> > not all of us have rich daddies and mummies
> 
> I take it that means you're young. I'm sorry I can't be of further help. We simply can't and won't support such old hardware. I don't recommend SBCs for this type of application, but I don't consider $35 to be "rich". You can probably find one used.

I happen to be 58 but do not want to get in to a personal discussion about that.   My comment was really that at no point in the installation was there an sign or information that the hardware was not capable.  Considering for a long time I had be running "OSMC" and it was only the fact that my media failed that I ended up needing to try other things.   In fact I was not even going to use it to the decoding as my Smart TV does that.  All I needed my the media server side of the project.

**Comment by Stevetmq** [comment]
P.S. You may not consider $35 as much but that's the point, "YOU" don't.   On a income of 11K,  $35 is lots

**Comment by cvium** [comment]
I don't want to get into a philosophical discussion here. Use your money however you want. Bottom line is that .NET support for ARMv6/ARMhf just isn't there and there's nothing we can/will do about it. We are not responsible for any random guides on the internet.

**Comment by Stevetmq** [comment]
>  .NET support for ARMv6/ARMhf just isn't there and there's nothing we can/will do about it. We are not responsible for any random guides on the internet telling you otherwise.

Thank you for this last part of the last replay.  This was much more acceptable replay as it did not include the sarcasm of your first replay.

**Comment by Stevetmq** [comment]
So that others do not fall foul of the same, can I suggest removing the ARMhf package from the repository "https://repo.jellyfin.org/debian bookworm/main armhf jellyfin all 10.9.3+deb12 [2,442 B]"

That way "apt" will not install a program that can not work on such systems.

**Comment by SamuelBanya** [comment]
> The .NET runtime does not support ARMv6. Buy some newer hardware.

Your approach could be nicer dude, maybe "Hey we no longer support that hardware".

To be fair the initial Pi is a bit old and might not be able to handle Jellyfin. But it's the verbiage that might help here to be nicer.

Anyway, I've ran Jellyfin on Portainer within a related Docker image since so it's clearly better on some platforms than others.

**Comment by cvium** [comment]
It's not us that do not support it, it's Microsoft. It is entirely out of our hands.

**Comment by Stevetmq** [comment]
> It's not us that do not support it, it's Microsoft. It is entirely out of our hands.

That is understandable.  I am quite used to getting things working on old hardware.  At the moment I am playing some music on my iMac G4 and my Thinkpad Z60M is dealing with my e-mail.  What throw me a curveball was the error reporting gave me know clue as to why it was not work until I tried

sudo jellyfin --help
I get
Segmentation fault

I hate systemd for that, I am used to OpenRC.   Yes I am old and old school
