### ISSUE TITLE
Dedicated Live TV App

### ISSUE THREAD

**Issue by 12nick12** [jellyfin/jellyfin#93]
I know it's a dumb requests, but I would love a dedicated Live TV app for Roku that would upon start up start playing the last played channel. I used to have DirecTV now and that's what I love about it is it was like a STB where it would just continue with the last played channel upon start up. With my harmony it makes it great for launching a LiveTV activity.

**Comment by 12nick12** [comment]
I don't have much programming expirence. I have made a repo dedicated to making a liveTV only app. I really don't know where to start, but I will try and figure it out lol. https://github.com/12nick12/jellyfin-roku-livetv

**Comment by 12nick12** [comment]
https://feathub.com/jellyfin/jellyfin/+12

**Comment by anthonylavado** [comment]
Hi @12nick12, I'm going to keep this open here with the enhancement label, if that's okay.

**Comment by 12nick12** [comment]
Yeah that would be awesome. Hopefully I can spin something up that looks nice. Roku coding looks pretty simple TBH.

**Comment by penfolduk** [comment]
will this get added to roku channels instead of sideload?

**Comment by 12nick12** [comment]
I really don't know.

**Comment by anthonylavado** [comment]
Roku currently needs a developer, so if you know anyone, please have them reach out!

**Comment by MCTyler** [comment]
has anyone tried connecting to JellyFin with the Emby Roku App? JC.

**Comment by anthonylavado** [comment]
>has anyone tried connecting to JellyFin with the Emby Roku App? JC.

@MCTyler I believe it currently doesn’t work. There is someone who has started a writing a new Roku app to use with Jellyfin, but it still needs a lot of work.

**Comment by candisft** [comment]
An stb emulator for jellyfin exist?
Like a plugin?
