### ISSUE TITLE
[Issue]: Jellyfin may have a problem fetching metadata for titles containing polish special characters

### ISSUE THREAD

**Issue by matgaj** [jellyfin/jellyfin#9308]
### Please describe your bug

I am still testing but it seems that Jellyfin does not fetch metadata for filenames or titles that contain ś,ć,ó,ź letters. Typing the exact same thing as the file name into the search bar in metadata usually returns the correct title as the first result. 

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Debian
- Virtualization: -
- Clients: Browser, Jellyfin Media Player for mac, Swiftfin, AndroidTV
- Browser: Firefox, Safari
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:nvenc
- Plugins:none
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:Local
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bugfixin** [comment]
Can you give some examples of file names and titles that exhibit this? What metadata plugins are installed and enabled for the library these files are included in?

It may also be useful to include logs in case any exceptions are thrown.
