### ISSUE TITLE
Allow grouping of different series of the same kind in one folder

### ISSUE THREAD

**Issue by iacchi** [jellyfin/jellyfin#932]
Right now, Jellyfin can only assume that one folder is equal to one series, which can have sub-folders for the different seasons, like this:

```
series/
--season 1/
----episode1.ext
----episode2.ext
--season 2/
----episode1.ext
----episode2.ext
```

However, some series have different, independent series that would be nice to group together in one parent folder. Two examples of this are Star Trek and CSI. It would be great if Jellyfin could be able to correctly parse a folder structure like this one (example with Star Trek):

```
star trek/
--the original series/
----season 1/
------episode1.ext
------episode2.ext
----season 2/
------episode1.ext
------episode2.ext
--the next generation/
----season 1/
------episode1.ext
------episode2.ext
----season 2/
------episode1.ext
------episode2.ext
```

Emby is already able to do this: https://web.archive.org/web/20181216120039/https://github.com/MediaBrowser/Wiki/wiki/TV-naming#complex-folder-structure
In issue #931 the main subfolders are different versions of the same series, so they should be listed in the same Identification as one entry, while in this case the main subfolders are independent series, so they should be able to be Identified independently.

**Comment by Liggy** [comment]
I guess it would be easier to slightly modify your naming to
```
star trek/
--star trek - the original series/
----season 1/
--star trek - the next generation/
----season 1/
```
Changing the title recognition in Jellyfin can easily show side effects to people who organize their libraries in a different way. Experienced that on 10.2.0 myself

**Comment by iacchi** [comment]
yes, I guell that naming convention is good as well.
