### ISSUE TITLE
[Issue]: Multiple TV seasons are merged into one

### ISSUE THREAD

**Issue by BlueRocketMouse** [jellyfin/jellyfin#9325]
### Please describe your bug

I've recently started having problems with multiple different seasons from a show being merged together. The behavior isn't consistent across all of my shows. Some will merge the entire show into one giant season, some will merge the first couple of seasons but leave later ones separate, and a handful display all seasons as expected with no issues. 

I follow Jellyfin's standard conventions for naming my files and I use local NFO files for my metadata. All external scrapers are turned off. Here is an example of how my files are named/structured:
- TV Shows
- - BEASTARS (2019)
- - - Season 1
- - - - BEASTARS - S01E01.jpg
- - - - BEASTARS - S01E01.mkv
- - - - BEASTARS - S01E01.nfo
- - - Season 2
- - - - BEASTARS - S02E01.jpg
- - - - BEASTARS - S02E01.mkv
- - - - BEASTARS - S02E01.nfo
- - - poster.jpg
- - - tvshow.nfo

The only thing I can think of that has changed in my setup before the problem started is that I upgraded to 10.8.9, but downgrading to older versions didn't fix the issue so I'm not sure if that's really the cause.

### Jellyfin Version

Other

### if other:

10.8.9

### Environment

```markdown
- OS: Windows 10
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Please attach any screenshots here

This show has two seasons, but only displays a single season folder.

![Jellyfin Seasons](https://user-images.githubusercontent.com/70493318/219249869-3e8b9f36-abf5-46c8-9111-1251ac8dc0d1.png)

All episodes are still properly sorted (i.e. season 2 episode 1 is displayed after the last episode of season 1) and checking the episode's metadata shows that Jellyfin is correctly identifying it as belonging to season 2. However, for some reason it is still only displayed in season 1's folder.

![Jellyfin Seasons 2](https://user-images.githubusercontent.com/70493318/219249851-16576a1e-e70e-4d43-b783-852a06c7e878.png)
![jellyfin Seasons 3](https://user-images.githubusercontent.com/70493318/219249838-b466239a-12a6-4759-8d71-2e48bba1146d.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheMelmacian** [comment]
In the Metadata Editor you find a setting called "Display order". Maybe it is set to "Absolute", or "DVD" which differs from the "Aired" order.
see https://thetvdb.com/series/beastars#seasons which offers Aired, DVD and Absolute Order. While Aired shows two seasons with 12 episodes each the Absolute Order only shows one season with 24 episodes.

**Comment by BlueRocketMouse** [comment]
Thank you for the suggestion. I checked the Metadata Editor and the display order is already set to "Aired". I tried changing it to a few of the other options and rescanning the library but it doesn't seem to change anything, so I don't think this is the problem.

**Comment by TheMelmacian** [comment]
It shouldn't make a difference but I had problems with Season folders with single digits in the past, so you could try to rename your folders to **Season 01** and **Season 02**. Maybe you have to additionally "Update Metadata" -> "Replace all Metadata".

You could also check which metadata providers are active for your shows library and in which order they are used.
Sometimes a provider with higher priority returns some unexpected data.

Beyond that I'm out of ideas.

**Comment by BlueRocketMouse** [comment]
Unfortunately, adding a leading zero to the season number and updating with "Replace all metadata" didn't affect it either.

Since I use NFO files generated by tinyMediaManager for my metadata, I have all external metadata providers unchecked/disabled. To my understanding Jellyfin shouldn't be grabbing metadata from the internet at all with this configuration, only reading it from the local NFO files (which have the correct season/episode numbers).

**Comment by TheMelmacian** [comment]
Do you have **season.nfo** files in the season folders? I can't see any in your example.

**Comment by BlueRocketMouse** [comment]
Looks like that was it. A few of my shows have season.nfo files, but most do not. This particular one didn't. I created a season.nfo in each folder and it now displays as it should.

Is this the intended behavior? Up until recently I was able to add more seasons by just creating a new folder, without having to go through the extra step of making NFO files for each one.

**Comment by BlueRocketMouse** [comment]
I'm still experiencing this issue after updating to 10.8.10.

It's still unclear to me whether this is a bug or a new intended behavior for Jellyfin. Creating a season.nfo for each season of every TV show I have would be a lot of additional work so I would rather avoid it if this is something that will be fixed in a future release.

**Comment by FlyingSamson** [comment]
@BlueRocketMouse Do you by any chance have the `YoutubeMetadata` plugin installed? If not maybe somebody else, like me, will stumble over this issue and find the following information helpful:

I observed the very same issues as you (all TV shows only showing one Series with all episodes in correct order in it, but correct metadata in the edit dialog of Jellyfin) and after long search I found that plugin to be the culprit. After I uninstalled the plugin not even a rescan with `Replace all metadata` could clean the mess up. What worked in the end was to rename every TV show folder in the file system (I appended an underscore) then perform a rescan on the TV show library. At this point everything was fine again for me. But of course, you want to name the TV shows back to their original names and perform another rescan at this point.


I strongly suspect [this issue](https://github.com/ankenyr/jellyfin-youtube-metadata-plugin/issues/58) of the plugin to introduce the problem for me. Because it automatically provides another Metadata reader to all existing libraries which cannot be disabled and then on not finding any valid metadata file it returns probably returns some gibberish.

**Comment by BlueRocketMouse** [comment]
@FlyingSamson Thank you for that detailed answer, it was incredibly helpful.

I did indeed used to have the YoutubeMetadata plugin installed. I removed it some time back, but as you mentioned that alone wasn't enough to fix my library. I followed your suggestion to rename/rescan and now my shows are finally displaying their seasons properly.
