### ISSUE TITLE
[Issue]: Entering watched state crashes Kodi Matrix

### ISSUE THREAD

**Issue by InvisibleKnight** [jellyfin/jellyfin#9328]
### Please describe your bug

I'm having a dual-path issue that leads to regular Kodi client crashes.

I have the same issue on two completely different kodi boxes (one is ARM based and the other is x86, different OS as well) and strange enough the crash happens in PKC as well so it might stem from how kodi itself handles multiple paths?

The issue was described [HERE](https://github.com/croneter/PlexKodiConnect/discussions/1838) in the discussion section and somehow resolved by OP. I have no idea how.

 Is my only option to assign just a single folder per library? 

### Jellyfin Version

Other

### if other:

0.7.10+py3

### Environment

```markdown
- Client 1: Intel NUC 11, Windows 10 with Kodi
- Client 2: Vero4k OSMC
- Server: Synology
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Bond-009** [comment]
This isn't a Jellyfin server issue
