### ISSUE TITLE
[Issue]: File order randomly and incomplete filename after ] in folder view.

### ISSUE THREAD

**Issue by ForsakenRei** [jellyfin/jellyfin#9332]
### Please describe your bug

The filename issue in library disccused in https://github.com/jellyfin/jellyfin/issues/5295 is still present from 2021 till now. Show, Movie, Mixed and Music Video seems all have the same problem.

Since there is still no option to just display the filename itself after the [feature request from 2020](https://features.jellyfin.org/posts/619/allow-media-show-their-filenames-rather-than-titles), I have to hope anime specific plugin can help. It does help sometimes but not always. Well that's why there are users like me want an option to just display the filename instead of anything else.

On top of the filename incomplete issue, I also found the file orders in no metadata series are pretty random, which probably because the order is not define by file name if there is no metatdata?
For example, for a folder with files following this naming convention:
`[SeriesName][Language][Episode#][resolution][encoding].mp4`
The only difference in filenames are the `Episode#`, and supposely if there is no metadata found, files should be ordered by `Episode#` from 01 to, say 24. But actually the first one can be 06, then 07 to 20 and go back to 01. In the screenshot the upper episode is 03 but the lower is 06. Combined with the filename display issue it's really hard to distinguish which one is which episode until you check metadata one by one. This is definitely not the designed way to do it.

### Jellyfin Version

Other

### if other:

10.8.9

### Environment

```markdown
- OS:TrueNAS Scale
- Virtualization: k8s
- Clients: Browser
- Browser: Chrome
- FFmpeg Version: 
- Playback Method: Direct
- Hardware Acceleration: No
- Plugins: jellyfin-plugin-bangumi
- Reverse Proxy: N/A
- Base URL: N/A
- Networking: Bridge
- Storage: Local
```

### Jellyfin logs

```shell
N/A
```

### FFmpeg logs

```shell
N/A
```

### Please attach any browser or client logs here

```shell
N/A
```

### Please attach any screenshots here

![image](https://user-images.githubusercontent.com/23041178/219539820-4033f3c2-ae78-42a5-8862-d2fb6f411424.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Bond-009** [comment]
Unsupported naming convention
