### ISSUE TITLE
[Issue]: Episode parsing season number as episode number

### ISSUE THREAD

**Issue by Lenart12** [jellyfin/jellyfin#9341]
`EpisodePathParser` incorrectily identifies `The.Series/Season 3/The Series Season 3 Episode 09 - Episode title.avi` as S03E03 for all episodes inside `The.Series/Season 3/` folder (not S03E09 as expected in the example).

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Linux Debian 11
- Virtualization: None
```

### Please attach any screenshots here

![image](https://user-images.githubusercontent.com/39205323/219776802-caa90f48-dfc8-4793-a8fd-8c1cf234a551.png)
![image](https://user-images.githubusercontent.com/39205323/219776931-9fda47c7-acfb-41da-ae03-c5732e7b0186.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bugfixin** [comment]
Looks like it's matching `.*[\\\/](?![Ee]pisode)(?<seriesname>[\w\s]+?)\s(?<epnumber>[0-9]{1,4})(-(?<endingepnumber>[0-9]{2,4}))*[^\\\/x]*$` from https://github.com/jellyfin/jellyfin/blob/master/Emby.Naming/Common/NamingOptions.cs#L283

Basically, it's being interpreted as a series named "The Sopranos Season" and taking the first number after that as the episode number. 

This naming does not follow naming conventions listed here: https://jellyfin.org/docs/general/server/media/shows/

**Comment by Lenart12** [comment]
You were spot on. Implemented a new rule, hopefully it can be accepted even if nonconventional. 

> Has this behavior changed since previous versions of JF?

I have not been using JF long enough to tell, sorry.
