### ISSUE TITLE
[Issue]: If a folder contains a single video as well as child folders, only the one video can be played

### ISSUE THREAD

**Issue by tudorapo** [jellyfin/jellyfin#9348]
### Please describe your bug

Noticed what seems to be a recurring pattern that, if I have a folder that only contains a single video file but also contains some additional child folders, the jellyfin web UI renders the folder as a single video instead. This leads to the child folders being unreachable. I noticed that the problem goes away if the folder either contains multiple videos/photos, or if I move the sole video into a child folder. I feel like this is unexpected behavior but could be wrong - I'm using the built in Music video type.

Opening as #8106 was closed without comment.

### Jellyfin Version

Other

### if other:

 10.8.9

### Environment

```markdown
- OS: debian
- Virtualization: docker
- Clients: debian
- Browser: firefox beta
- FFmpeg Version: 4.4.3
- Playback Method: no playback happening
- Hardware Acceleration: none
- Plugins: none
- Reverse Proxy: none
- Base URL: .
- Networking: host
- Storage: local
```

### Jellyfin logs

```shell
no relevant log
```

### FFmpeg logs

```shell
no relevant details, no playback
```

### Please attach any screenshots here

![image](https://user-images.githubusercontent.com/32787911/219876866-b7cece04-a5e3-436f-b892-9f8afb3c363a.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tudorapo** [comment]
hello?

**Comment by Shadowghost** [comment]
Hello.

This is how it's implemented. Check out the documentation for supported folder layouts.
Jellyfin is not a glorified file browser.

**Comment by tudorapo** [comment]
sad.
