### ISSUE TITLE
[Issue]: TV show called "Extras" is not detected

### ISSUE THREAD

**Issue by clidx** [jellyfin/jellyfin#9353]
### Please describe your bug

This TV show is rather unfortunately simply called "Extras" [(IMDB)](https://www.imdb.com/title/tt0445114/?ref_=ttls_li_tt). I don't believe Jellyfin is even trying to add it to my library probably because it thinks think the show is a misplaced extras folder. I don't see anything from `Emby.Server.Implementations.IO.LibraryMonitor.` in the logs relating to this TV show, even after a manual library scan and all my other files get refreshed. In docker, my TV shows are mounted to `/data/tv/<show>/<season>`. What's the best way to get this show added to my library given the unfortunate name?

More broadly speaking, at the show level, should jellyfin ignore a show just because it's called "Extras"? A legitimate extras folder should be at the season level.

### Jellyfin Version

Other

### if other:

10.8.9-1

### Environment

```markdown
- OS: Debian
- Virtualization: Docker
- Clients: JMP, Android
- Browser: n/a
- FFmpeg Version: n/a
- Playback Method: n/a
- Hardware Acceleration: n/a
- Plugins: none
- Reverse Proxy: none
- Base URL: none
- Networking: n/a
- Storage: local
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheMelmacian** [comment]
A simple fix is to add the the release date of the show to the folder name: `Extras (2005)`.

**Comment by t4ggno** [comment]
You can even improve the folder name using the TMDB-ID: `Extras [tmdbid=2693]`

**Comment by iuy6tf57765fsegh5yhw45yuh8g4** [comment]
I don't think this is a bug.  Extras is a reserved folder name, but as others have pointed out, as long as you don't use the reserved name and instead change it in any way (such as to add the year) then it works as intended.

Can we close this bug report?
