### ISSUE TITLE
[Issue]: Jellyfin fails to identify if the movie name is in "original name AKA english name (year)" format

### ISSUE THREAD

**Issue by daredeviloff** [jellyfin/jellyfin#9362]
### Please describe your bug

As title says, Jellyfin searches for "original name AKA english name (year)" and fails to find the movie. Expected behavior should be search for "original name (year)", if it fails then it should search for "english name (year)". 

Example:
![image](https://user-images.githubusercontent.com/60948479/220123755-3cdf815d-c875-49a2-9acc-7f02da7fdd56.png)

Moreover, if you try to identify manually, you should identify one-by-one all the versions in the same folder to make it work.

### Jellyfin Version

10.8.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by daredeviloff** [comment]
> This seems more as a featur request than a bug request. Our docs clearly state this not as supported right now.

You're right. Changing right away.

**Comment by Bond-009** [comment]
Features go here: https://features.jellyfin.org/
