### ISSUE TITLE
[Issue]: BSOD occurs when the jellyfin server is running.

### ISSUE THREAD

**Issue by tarokeitaro** [jellyfin/jellyfin#9363]
### Please describe your bug

I have a jellyfin and emby server, jellyfin on the main machine, emby on virtual machines, as long as jellyfin runs on the main engine, there is a bsod that disturbs my server. Finally I moved Jellyfin to a virtual engine (VMware), I thought it would be safe, it turns out that the guest OS (VMware) also experienced BSOD. I was confused by this problem, I could not find what I was looking for from the Jellyfin log. Is there any other logs needed, for example from Windows? Please tell you how to see the log from Windows if needed. Please give me troubleshooting.

### Jellyfin Version

Other

### if other:

10.8.9

### Environment

```markdown
Installed on Host machine
- OS: Windows 11 Pro v22H2 Build 22621.1265
- Virtualization: -
- Clients: All
- Browser: All
- FFmpeg Version: 5.1.2-Jellyfin
- Playback Method: Direct Stream, Transcode for live iptv, and remux
- Hardware Acceleration: NVENC
- Plugins: AniDB, AudioDB, Fanart, MusicBrainz, OMDb, Studio Images, TmDb, TheTVDB, Webhook
- Reverse Proxy: no
- Base URL: no
- Networking: host (1GBps Network)
- Storage: local

Installed on guest OS (VMware)
- OS: Windows 11 Pro v22H2 Build 22621.1265
- Core 4
- Ram 4GB
- Networking: bridge 500MBps Network
```

### Jellyfin logs

```shell
https://cdn.discordapp.com/attachments/1068785711794364567/1077264607242104832/log_20230220.txt
```

### FFmpeg logs

```shell
https://cdn.discordapp.com/attachments/1068785711794364567/1077265218549321848/FFmpeg.Remux-2023-02-19_05-25-32_5fa7457214069fd8f8e3c0a2af6d76ea_e72785d9.logapi_keyd11d8bcd4b1a4372b85ca89e979dcfaa.txt
```

### Please attach any browser or client logs here

-

### Please attach any screenshots here

![image](https://user-images.githubusercontent.com/42670754/220159004-c43937b4-b761-431f-b24f-489ccd42ca33.png)
https://cdn.discordapp.com/attachments/1002541150030266428/1077250753007198318/image.png

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nyanmisaka** [comment]
https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x124---whea-uncorrectable-error

0x00000124 WHEA_UNCORRECTABLE_ERROR

This is more like your hardware/driver failure than Jellyfin.

**Comment by tarokeitaro** [comment]
> https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x124---whea-uncorrectable-error
> 
> 0x00000124 WHEA_UNCORRECTABLE_ERROR
> 
> This is more like your hardware/driver failure than Jellyfin.

even in a virtual machine? this happens also inside a virtual machine.
I'm confused, my pc that only ran emby for a month is fine without jellyfin. but my focus right now is running jellyfin, not emby. trying to run jellyfin on pc running emby at the moment also getting the same error :(
