### ISSUE TITLE
TLS/HTTPS support broken

### ISSUE THREAD

**Issue by ghost** [jellyfin/jellyfin#937]
**Describe the bug**

[Jellyfin documentation](https://jellyfin.readthedocs.io/en/latest/administrator-docs/first-time/) recommends using HTTPS over HTTP, but HTTPS/TLS support is broken, erroring with `ERR_SSL_PROTOCOL_ERROR`  in `Chrome Version 74.0.3702.0 (Official Build) dev (64-bit)` and `SSL_ERROR_RX_RECORD_TOO_LONG` in `IceCat (Firefox) 60.5.0esr (64-bit)`.

**To Reproduce**

1. Go to https://localhost:8096 
2. Observe that it gives an SSL error and Jellyfin cannot be accessed.

**Expected behavior**

Jellyfin should work over HTTPS as the documentation implies/recommends.

**Logs**

N/A 

**Screenshots**

N/A 

**System (please complete the following information):**
 - OS: Fedora 29
 - Browser: 
   - Chrome v74.0.3702.0 
   - IceCat v60.5.0esr
 - Jellyfin Version: 10.2.0-2.fc29 (installed via official RPM) 

**Additional context**

N/A

**Comment by cvium** [comment]
Did you generate an SSL certificate?

**Comment by yuukieve** [comment]
I did not, as I encountered the error during first time setup; the [first time setup documentation](https://jellyfin.readthedocs.io/en/latest/administrator-docs/first-time/) lists an HTTPS URL, so this may be a simple documentation error rather than a bug if Jellyfin cannot be setup under HTTPS the first time.

**Comment by cvium** [comment]
It's on the roadmap to (re)implement self-signed cert generation and Let's Encrypt (as a plugin).

So yes, you are correct. It seems the documentation is lacking wrt. SSL certificate generation.
cc @joshuaboniface

**Comment by JustAMan** [comment]
Also port 8096 is by default plain http, not https. Maybe it's the reason for the issue you're seeing.

**Comment by jerome-diver** [comment]
is there any news about this bug report ? I have the same problem...

**Comment by RIS2000** [comment]
> 
> 
> is there any news about this bug report ? I have the same problem...

same for me (

**Comment by cvium** [comment]
The issue is closed

**Comment by RIS2000** [comment]
> 
> 
> The issue is closed

what is the fix ?

**Comment by RIS2000** [comment]
![изображение](https://user-images.githubusercontent.com/30177105/135671957-01197e8a-643f-4d71-b41d-a79a2b0e47dd.png)

this is helped me

**Comment by BigBrawler** [comment]
This is still an issue. 
Paid for pfx file online via csr service. generated using openssl. Nope.
Also doesn't work generated via softether server manager.
Also doesn't work via softether x.509 cer and private key rsa:4096 as in and inkey in openssl

**Comment by Blarnix** [comment]
@BigBrawler That was the fix for me. I was using a .p12 certificate before as Jellyfin had said in the networking UI and that wasn't valid as it seemed. Thanks for finding this fix.
