### ISSUE TITLE
Upnp forward missing after hours

### ISSUE THREAD

**Issue by Erromango** [jellyfin/jellyfin#9373]
im running jellyfin server on windows11 and having upnp feature enabled
Upnp forward same local ports 8096/8920
after restart server via system tray I can see these ports in openwrt upnp list but maybe hours later they disappeared.

I’ve also host a Plex media server on the same htpc and its upnp works and keeps alive so I’m assuming that there is something wrong with Jellyfin windows

**Comment by illusionJP** [comment]
same, 8096 port will dissarrpear in minites and 8920 will miss in hours
