### ISSUE TITLE
[Issue]: Slow streaming

### ISSUE THREAD

**Issue by mebitek** [jellyfin/jellyfin#9379]
### Please describe your bug

I'm on cloduflare tunnel self hosting jellyfin 10.8 (rapsberry pi 4)  in docker container.
cloduflare test speed reports download 12.6mbps and upload 6.39mbs
however if I set quality to 3mbps the video is continuosly buffering resulting impossible to view the video
connecting to my local lan no problem are reported and I can stream at 60mbps without problem

when I stream over tunnel nload eth0 on my host docker machine reports just 50-100kbit/s
when I stream over lan nload eth0 on my host docker machine reports 20-60Mbit/s

I correctly setup hardware accelleration 
in both case in logs I see:  [WRN] [36] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from [ip or domain name]

could you please help me?

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS:
- Virtualization: docker
- Clients: android, windows, linux
- Browser: brave
- FFmpeg Version: 
- Playback Method:
- Hardware Acceleration: 
- Plugins:
- Reverse Proxy: cloduflare
- Base URL: 
- Networking:
- Storage:
```

### Jellyfin logs

```shell
[WRN] [36] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MrHugelberg** [comment]
Could this be related due to jellyfin using single segment streaming?
https://github.com/jellyfin/jellyfin/issues/3206

**Comment by 1337haXXor** [comment]
I'm experiencing a similar problem. Setup is completely different (Windows Server), but the issue is the same. I have 25mbps upload here, and have JF streaming set to use only 7mbps. But almost all shows constantly buffer. I have a beefy GPU, and the transcodes finish quickly, so it's not that.
