### ISSUE TITLE
Plays theme song while browsing media

### ISSUE THREAD

**Issue by lostmypillow** [jellyfin/jellyfin#938]
I don't know how the hell Plex has them ; I don't know what the provider of the theme song is, but it sure is an entirely optional feature, yet with it, it really adds aesthetic. Just a suggestion.

**Comment by LogicalPhallacy** [comment]
That sounds super cool, and I kind of want this, but sadly to pull it off we'd likely have to do what plex did:

> Essentially, we’ve compiled (thanks to James and many contributors on the forums) a collection of high quality TV theme music samples (30 seconds or less, for reasons of copyright) and stored them on the Plex servers. When you scrape your TV shows, besides downloading metadata, Plex queries our server and if available, will download the theme music.

Without a source for this data, its a huge and potentially copyright infringing (yes 30 seconds or less should be fine, but copyright law is nuts) undertaking that would have to be hosted by each user since we avoid functions that force a dependency on an outside server. 

This might be suitable for a plugin but even then I question the merits.

**Comment by JustAMan** [comment]
I wonder if we can scrape Plex for this data :D

**Comment by lostmypillow** [comment]
Turns out there's an option for that in the menus, but obviously the theme song wasn't playing

**Comment by lostmypillow** [comment]
But yeah now I question its possibility due to copyright issues

**Comment by C-Fu** [comment]
> Without a source for this data, its a huge and potentially copyright infringing (yes 30 seconds or less should be fine, but copyright law is nuts) undertaking that would have to be hosted by each user since we avoid functions that force a dependency on an outside server.
> 
> This might be suitable for a plugin but even then I question the merits.

I don't think you have to do it in that way. I believe the OP was asking if jellyfin can support finding theme.mp3 or themesong.mp3 or similar and play it while browsing a tv series.

The merits are exactly the same as having posters, fanart, banner, logo, etc.

**Comment by Protektor-Desura** [comment]
The copyright issues is no different from TV show logos, actor pictures, network logos, movie posters and all the other data that Jellyfin uses.

**Comment by CowiUY** [comment]
> I don't know how the hell Plex has them ; I don't know what the provider of the theme song is, but it sure is an entirely optional feature, yet with it, it really adds aesthetic. Just a suggestion.

@lostmypillow as @LogicalPhallacy pointed out, they have their own library, but we could use [television tunes](www.televisiontunes.com), you can read their [copyright page](https://www.televisiontunes.com/copyright.php), but I THINK its legal for the Jellyfin Project to use and would be a great feature to add. What do you think?
