### ISSUE TITLE
[Issue]: Audio Book only file not folder

### ISSUE THREAD

**Issue by Cwavs** [jellyfin/jellyfin#9382]
### Please describe your bug

I have a few audio dramas on my server, a lot of them are spread over multiple discs for one of them, for a reason I can't for the life of me figure out, Jellyfin is only presenting me with one file from Disc 2 rather than the folder for Disc 2!

All the files are tagged properly as I normally would and aren't different to any other the others. They're all encoded to Opus from my personal CD Rips.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Ubuntu
- Virtualization: N/A
- Clients: Browser, Windows, Linux, Android
- Browser: Brave v1.48167
- FFmpeg Version: 4.4.1-4-Jellyfin
- Playback Method: N/A
- Hardware Acceleration: N/A
- Plugins: Audio DB, Bookshelf, Cover Art Archive, Fanart, Intro Skipper, Jellyscrub, Merge Versions, MusicBrainz, OMDb, OPDS Feed, Playback Reporting, Reports, Session Cleaner, SkinManager, Studio Images, Subtitle Extract, TMDb, TMDb Box Sets, TheTVDB, Theme Songs, Trakt, VGMdb, Webhook
- Reverse Proxy: none
- Base URL: none
- Networking: N/A
- Storage: Local
```

### Jellyfin logs

```shell
I couldn't find any relevant logs during a scan unfortunately.
```

### Please attach any screenshots here

What I see in Jellyfin:
![image](https://user-images.githubusercontent.com/16854045/221022606-9f6c46ad-114a-4c89-820e-f14b540376a8.png)

What I see in my files
![image](https://user-images.githubusercontent.com/16854045/221022749-7802d731-d323-461a-b120-98c182d8d08e.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 1337joe** [comment]
You screenshotted the directory containing the disks, could you also include what's in the directories? The contents of a directory is the important part to the scanner, so without knowing what's in it we have nothing to test against.

Also, what type library is this, Music, Books, or one of the others?

**Comment by Cwavs** [comment]
Sure I'll grab you one when I next have access! The library type is books at the moment.

**Comment by Cwavs** [comment]
Here are screenshots of the contents of each folder!

Disc 1:
![image](https://user-images.githubusercontent.com/16854045/221242470-5d9e8731-bdad-4bb1-99e7-d16493906685.png)
Disc 2:
![image](https://user-images.githubusercontent.com/16854045/221242279-5926752b-07da-4ab6-ad3e-2bcf2d650f9d.png)
