### ISSUE TITLE
[Issue]: initial scan ffprobe 200mb requirement - couldn't we get away with less?

### ISSUE THREAD

**Issue by ndom91** [jellyfin/jellyfin#9399]
### Please describe your bug

I have an S3 bucket of media mounted via rclone with the VFS caching enabled and in read-only mode.

Initially I couldn't get the initial jellyfin scan to load at all, some sort of issue with ffprobe. It would start a few processes looking at media files, but nothing was ever logged and while show and season info was added to the library in Jellyfin, no media files / episodes were ever visible.

Anyway, long story short, I've fixed this issue but in the course of my research I came across many people complaining about initial scans takinig a long time. I'm having a related issue, because the server I'm running this on only has ~40GB of disk space free, so downloading even ~200mb of every show and movie on there is making the intial scan extremely manually labor intensive. 

> I'm referring to the 200M analyzeduration in this example ffprobe command it runs on every media file in the scan:
> 
> `"/usr/lib/jellyfin-ffmpeg/ffprobe" "-analyzeduration 200M -i file:\"/mnt/tv/Show S01E01 - Episode.mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"`
> 
> Defined here: https://github.com/jellyfin/jellyfin/blob/da25c3ad7b5007c6237777e0d5f2b116789d2e23/Emby.Server.Implementations/ConfigurationOptions.cs#LL19C31-L19C31

Every time it fills up the rclone VFS cache with the initial `ffprobe` 200mb scan's, i have to manually clear the cache dir and it can continue with other directories/episodes.

So my question, why the 200M scan amount to begin with? Can't most of the info be determined without reading any of the actual file at all? And the rest with like the first few seconds / megabytes?

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Ubuntu
- Virtualization: Proxmox KVM
- Clients: Web
- Browser: Brave
- FFmpeg Version: `/usr/lib/jellyfin-ffmpeg/ffmpeg@5.1.2-jellyfin`
- Playback Method: 
- Hardware Acceleration: No
- Plugins:
- Reverse Proxy: nginx
- Base URL:
- Networking:
- Storage: rclone mounted S3 bucket (read only with vfs enabled)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ndom91** [comment]
Okay so I've found a bit of a work around for now. For anyone else that stumbles upon this, setting the `vfs-cache-max-size` to however much max size you have on your disk. As mentioned in the docs, its not a hard limit, but rclone does its best to keep the vfs cache size below that limit.

See: https://rclone.org/commands/rclone_mount/#vfs-file-caching

**Comment by cvium** [comment]
You could just set the environment variable `JELLYFIN_FFmpeg__analyzeduration` to something lower than 200M...

**Comment by grobalt** [comment]
just in case someone has the same issue .. what a shit default setting with 10.9.7 (fresh installation)

https://forums.unraid.net/topic/80744-support-linuxserverio-jellyfin/?do=findComment&comment=1437149
