### ISSUE TITLE
Include external resources (e.g js)

### ISSUE THREAD

**Issue by mckay6842** [jellyfin/jellyfin#94]
To be able to run emby complete locally (when internet is out or not available), external resources should be copied and hosted by jellyfin itself.

I found:
`https://www.gstatic.com/cv/js/sender/v1/cast_sender.js`

maybe there are more

**Comment by mckay6842** [comment]
oh that seems related only to chrome (extension) and chrome cast. All other external resources from emby seems to be removed already.

**Comment by TwizzyDizzy** [comment]
Hey @mckay6842,

A question for my understanding, if you can answer that: are the `gstatic.com` references put inplace by jellyfin or is this added (on the fly) as chrome/chromium detect something in the markup that makes them replace the content with the code that calls `gstatic.com` (and in turn seems to offer "chromecast".

Could you further enlighten me: is it needed to load this external resource in order for chromecast to work?

I appreciate any insight you can provide :)

Cheers
Thomas

**Comment by cvium** [comment]
It's the sender api which they recommend not self hosting, https://developers.google.com/cast/docs/chrome_sender/integrate
