### ISSUE TITLE
FFmpeg fails to transcode for Android TV but not a web browser client

### ISSUE THREAD

**Issue by wrhight** [jellyfin/jellyfin#9412]
**Media Info of the file**

[mediainfo_theempirestrikesback.txt](https://github.com/jellyfin/jellyfin/files/10844423/mediainfo_theempirestrikesback.txt)

**Logs**

[jellyfin.log](https://github.com/jellyfin/jellyfin/files/10844588/jellyfin.log)

**FFmpeg Logs**

[ffmpeg_transcode.log](https://github.com/jellyfin/jellyfin/files/10844589/ffmpeg_transcode.log)

**Stats for Nerds Screenshots**

**Server System (please complete the following information):**
 - OS: [Docker on Linux]
 - Jellyfin Version: [10.8.9]
 - Hardware settings & device: [NVENC on RTX3080]
 - Reverse proxy: [traefik]
 - Other hardware notes: [media bind mounted from local volume]
 
**Client System (please complete the following information):**
 - Device: [Samsung TV w/ Fire Stick 4k]
 - Client: [Jellyfin Android TV]
 - Client Version: [0.15.3]
 
 As you can see in the FFmpeg logs, I get a vague error regarding the encoder for an audio output stream, hinting at incorrect parameters. What's strange is that when playing back the same file via Firefox, it can transcode down to 3mbps (just what I tested) just fine.
 
 By the way, the Jellyfin client on Android TV is reporting the wrong max bitrate which is why it wants to transcode in the first place, but that's a separate issue of course. When increasing the reported bitrate manually, it direct plays without issue.

**Comment by nyanmisaka** [comment]
#9409 should fix this

**Comment by szafranski-pawel** [comment]
I faced similar issue, but FFmpeg failed when I tried to enable subtitles. Switching to VLC fixes the problem, but I lose support for Dolby Vision, so it's just temporary fix.
[FFmpeg_fail.txt](https://github.com/jellyfin/jellyfin/files/10872598/FFmpeg_fail.txt)

ExoPlayer on Android phone is working just fine, so this issue is limited to AndroidTV.
