### ISSUE TITLE
[Issue]: Starts Monero miner after jellyfin install

### ISSUE THREAD

**Issue by mdenushev** [jellyfin/jellyfin#9413]
### Please describe your bug

After installing jellyfin I discovered, that my server has 100% CPU usage, because there is monero miner with jellyfin as a password in configuration.

Installed jellyfin using https://repo.jellyfin.org/install-debuntu.sh

### Jellyfin Version

10.8.0

### if other:

10.8.9.0

### Environment

```markdown
- OS: Ubuntu Server
- Virtualization: QEMU
- Clients: Browser, Swiftfin
- Browser: Firefox
- Plugins: AudioDB, MusicBrainz, OMDb, Studio Images, TMDb, TheTVDB
```

### Please attach any screenshots here

![изображение](https://user-images.githubusercontent.com/31730567/221744658-21c2d76e-cce3-45f0-96fd-69b9bd7a2a1a.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mdenushev** [comment]
[c3pool.zip](https://github.com/jellyfin/jellyfin/files/10846282/c3pool.zip)

**Comment by mdenushev** [comment]
it's not jellyfin related, by bad

**Comment by PrplHaz4** [comment]
This is a pretty serious allegation - when/where did you get the link to the debuntu installer?

Have you installed anything else that correlates to the time you started seeing the increased CPU usage?  Or are you running any jellyfin plugins?
