### ISSUE TITLE
[Issue]: LiveTV Series & Schedule views not following parental controls.

### ISSUE THREAD

**Issue by jedthe3rd** [jellyfin/jellyfin#9420]
### Please describe your bug

When a user that can see a parental control restricted program and schedules a recording, that scheduled recording can be seen by all users even users that can't see the program or channel in any other view. This also applies to Series as well.

I am assuming this is a API issue because both my AndroidTV and web based clients have this issue.

Steps to reproduce:

Create a test user.
Give that users restricted parental controls (using a tag is easiest to test with).
Tag the channel or program you are planning to record/create a recording series with the tag you set in the parental controls for the test user.
As a user without the parental controls restrictions record/create a recording series for that program.
Login as the test user and visit: 
/web/index.html#!/livetv.html?tab=5
/web/index.html#!/livetv.html?tab=4

They will show the program/series recording you just scheduled despite the user not having access to view the program/channel. 

I use both program & channel because if a channel is given meta data so it is restricted via parental controls any programs in the channel it should follow those parental controls. If the program is restricted but the channel not it should follow parental controls correctly.

### Jellyfin Version

Other

### if other:

10.8.9

### Environment

```markdown
- OS: Windows 10
- Virtualization: N/A
- Clients: AndroidTV, Android, Browser
- Browser: Any
- FFmpeg Version: 5.1.2-Jellyfin
- Playback Method: N/A
- Hardware Acceleration: N/A
- Plugins: N/A
- Reverse Proxy: N/A
- Base URL: 
/web/index.html#!/livetv.html?tab=5
/web/index.html#!/livetv.html?tab=4
- Networking: N/A
- Storage: N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jedthe3rd** [comment]
This is probably related to:
#8718

**Comment by jedthe3rd** [comment]
> Can you check if this is still the case on current master/unstable?

Looks like in the Master branch it is fixed for the Schedule view but the Series view still shows the series for the shows that are supposed to be blocked from view for the restricted user.

**Comment by Shadowghost** [comment]
How exactly are the shows blocked? By parental control (rating), blocked tag,...?

Does the show have a proper rating associated to it?

**Comment by jedthe3rd** [comment]
> How exactly are the shows blocked? By parental control (rating), blocked tag,...?
> 
> Does the show have a proper rating associated to it?

I tried both and neither work. The metadata of the show the Series is created for seems to not be checked when it decides what Series are scheduled. I don't think it does any checks it just shows all Series to all users.

**Comment by tetebueno** [comment]
Can this be reopen? I can reproduce this in 10.9.4.

# Steps to reproduce
1. Log into the web UI with both a user with and without parental control enabled.
2. Go to Live TV guide screen.
3. Select a channel with an ongoing show that can only be seen by the user without parental control. It's important to click not on the show but on the channel, so one can see the upcoming shows in the channel.
4. Click on the "play" icon on the top right corner of the channel information.
5. Both users will be accessing the stream.

Some things to consider:
* I'm using ErsatzTV as a Live TV backend with Jellyfin as the media source, so I can confirm the parental information is present on the show (not on the channel, though):
```xml
...
<programme start="20240716143054 -0300" stop="20240716172031 -0300" channel="8.etv">
  <title lang="en">Some movie</title>
  <desc lang="en">Some description.</desc>
  <date>2012</date>
  <category lang="en">Movie</category>
  <category lang="en">Action</category>
  <category lang="en">Adventure</category>
  <category lang="en">Fantasy</category>
  <icon src="https://example.com/iptv/artwork/posters/jellyfin/Items/10dad0799f31bf30916c4b20abc36e13/Images/Primary?tag=d2f5a0a95f0e41f8f3b6f670a80bc03d&fillHeight=440"/>
  <rating>
    <value>PG-13</value> <--- Here...
  </rating>
  <previously-shown/>
</programme>
...
```
* Maybe this occurs on channels that have restricted shows at the moment but unrestricted shows in the future. Haven't been able to test with a channel with no shows that can be seen by the parental control enabled user.

# Jellyfin version
10.9.4

# Environment
- OS: Ubuntu
- Linux Kernel: 6.5.0-35-generic
- Virtualization: Docker
- Clients: Jellyfin web
- Browser: Chromium 126.0.6478.126 (Official Build) snap (64-bit)
- FFmpeg Version: 6.0.1-Jellyfin
- Playback Method: remuxing
- Hardware Acceleration: enabled
- GPU Model: GeForce GTX 1060
- Plugins: N/A
- Reverse Proxy: Nginx
- Base URL: /
- Networking: N/A
- Storage: local

**Comment by cvium** [comment]
Latest version is 10.9.7 though

**Comment by tetebueno** [comment]
Good point.

Just updated to 10.9.7 and still get the same issue.
