### ISSUE TITLE
[Issue]: Library Photo (Photos and Videos) is extremly slow while browsing + pictures are not even loaded

### ISSUE THREAD

**Issue by RkcCorian** [jellyfin/jellyfin#9423]
### Please describe your bug

Background:
- In my libraries (of type photo) I have private pictures and videos organized. I do not use Jellyfin for Videostreaming e.g., of complete films.
- My server is via a docker container (version 10.8.9) on a Synology NAS. I had since today a DS716+II with HW acceleration, now I have a DS923+ w/o HW accelaration and both have the same issue.

What I observe:
- When I browse through my library I can access till the folder level nearly fine. Once I go inside a folder where the private pictures and videos are it gets very slow to navigate and even many (preview) pictures are not loading. The worst is the Fire TV but also my S22 Ultra is lacking.
- When I try to view 4K pictures the first picture might get loaded but after some pictures they are even not loading on the Fire TV (Gen. 3) at all and partly also this happens on my S22 Ultra.
- I clearly have to problem while watching my private videos (which are together with the pictures in the folders)

SUMMARY: Navigation trough my libraries is very slow and showing pictures in 4K even often not possible

I really hope I miss something or you know this problem and can help me anyhow because I like Jellyfin, but simply cannot use it. Many thanks in advance!!!

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS:Server > Linux
- Virtualization: Docker container on Synology DS923+
- Clients:MS Edge on Win10, Android App (2.4.4), Fire TV App (0.15.4)
- Browser:MS Edge
- FFmpeg Version:4.4.3-47
- Playback Method:?
- Hardware Acceleration:None
- Plugins:None
- Reverse Proxy:None
- Base URL:Local Network
- Networking:1GB, Clients with 100MBit
- Storage:Seagate IronWolf (8 TB, 3.5", CMR)
```

### Please attach any screenshots here

Example folder structure that is user for the library of type "Photo"
![image](https://user-images.githubusercontent.com/79741077/222770469-da9d2c16-fea3-4af9-9d5c-914311e9d64e.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RkcCorian** [comment]
Short update... I checked with emby and there it is working fine. So my hardware is sufficient. Therefore I have to switch for now to emby and really hope that the performance can be improved! Many thanks in advance!!

**Comment by Parmenide78** [comment]
+1 Is there an option to create miniature/Thumb ?
It seems to be this request https://features.jellyfin.org/posts/1047/generate-collection-thumb-images
