### ISSUE TITLE
[Issue]: met data keeps changing from what I set to us

### ISSUE THREAD

**Issue by homelab2385** [jellyfin/jellyfin#9432]
### Please describe your bug

I live in the UK I have changed everything in config to match that but the met data is still US. So I went into each title and changed it to appropriate UK rating, but it keeps changing back I have ticked the box on each title to "prevent future changes" and also the same box in the main metadata tab under server admin. Please advise. Thanks 

### Jellyfin Version

Other

### if other:

10.8.9

### Environment

```markdown
- OS: Linux 
- Virtualization:unraid docker
- Clients:Android iOS amozon
- Browser:firexox
- FFmpeg Version:jellyfin
- Playback Method:transcode
- Hardware Acceleration:nvenc
- Plugins:none
- Reverse Proxy:ngix
- Base URL:yes
- Networking:bridge
- Storage:local
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 1337joe** [comment]
Any chance you have NFO files alongside your media providing the metadata? I want to say the metadata fetchers will look at that as truth before considering the locked state of items.

**Comment by nothing2obvi** [comment]
This happens to me on Jellyfin 10.8.9 on Docker Desktop for Mac 4.17.0 on Mac Mini with M1 chip.

I change metadata for seasons (title, season number), select "Lock this element to avoid future changes," click save, refresh, check it again, and it's fine. Then 20 minutes later I look and all the metadata I entered is gone.

These seasons are separated into season folders if that makes any difference.

Similar to #6248.

As for the NFO files, I was under the impression that using the "Edit Metadata" feature in Jellyfin will edit those NFO files for you. Is that incorrect? If so, is it better to just manually edit the NFO files? I suppose I could experiment with that when I have some time.

**Comment by nothing2obvi** [comment]
I just checked my shows that are having this problem. After locking the metadata via the Jellyfin Web UI, on one show, the NFO files do indeed show `<lockdata>true</lockdata>' and all the metadata is still there. On other shows, after locking the metadata via the Jellyfin Web UI, it says `<lockdata>false</lockdata> and all the custom metadata I entered is not there.

I just tried manually editing those failed NFO files to see if they stay locked. Will report back.

**Comment by nothing2obvi** [comment]
After manually editing the NFO files, 95% of the items I edited were reflected in Jellyfin Web UI, while 5% of them had information that was mixed up. I then used the "Edit Metadata" button to make changes and lock the metadata for that 5%. Everything seems to have stuck so far.

**Comment by bigbeau** [comment]
I am also having this problem. Jellyfin either removes the locked flag from the NFO file or just completely ignores it. This persists between restarts. 

I am using the latest build for linux from apt
