### ISSUE TITLE
[Issue]: Anyone can Reset Admin Account on existing instance without using any passwords

### ISSUE THREAD

**Issue by buzzzz2138** [jellyfin/jellyfin#9435]
### Please describe your bug

Intermittently, I think once a restart of the docker, I get the window to select a jellyfin server while going from a Firefox browser to my local network.   If I select to use that one I get a message along the lines of that instance isn't working.  I have to delete it, then refresh the page and I'll get the login page.  Sometimes after I have deleted the instance from firefox, I get the new installation wizard.  In there I select an admin account and the libraries.  

This time when I did it, I went in through my proxy address(NGINX) and not the IP address.  WWW address instead of 192.168.*.*

I got the start up wizard.  Then I was able to change the password on the admin account using the start up wizard, bypassing any built in security and got a jellyfin admin account.  From there I could do anything I want to the server. 

Expected is not to have the first time wizard on an existing server installation. 

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Open Media Vault, Debian
- Virtualization: Docker
- Clients: FireFox, Roku, Android
- Browser: FireFox
- FFmpeg Version: Jellyfin
- Playback Method: NA
- Hardware Acceleration: NA
- Plugins: NA
- Reverse Proxy: nginx
- Base URL: none
- Networking: host
- Storage: local
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Extarys** [comment]
This issue should remain open :/

**Comment by Shadowghost** [comment]
Is this reliably reproducible?

**Comment by buzzzz2138** [comment]
About once a month it happens on my system.  I have no idea how to get it to be reproducible.

**Comment by Shadowghost** [comment]
What is your networking configuration? This might already be fixed in master (we did refactor our access policies).

**Comment by buzzzz2138** [comment]
PC -> NGINX -> website.   Mostly followed the instructions on the jellyfin documentation unless you are looking for something else.  This issue comes is present on both the local host side and the external facing side.
