### ISSUE TITLE
Movie grouping doesn't work at all

### ISSUE THREAD

**Issue by Sirfrancis17** [jellyfin/jellyfin#944]
My movie library contains 4 folders. 1080, 720, 4k, 3d and Children's films 
The children films (are all in the same folder) are grouped correctly , but the different qualities of adult films do not group them. Is it because they're in separate folders?
Example
-Movies (folder)
         - 720  (folder) 
               scream (2012).720.mkv
         - 1080 (folder) 
               scream (2012).1080.mkv
         - children movies (folder) 
                Coco (2017).720.mkv
                Coco (2017).1080.mkv

<a href="http://es.tinypic.com?ref=eoggo" target="_blank"><img src="http://i68.tinypic.com/eoggo.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by iacchi** [comment]
Automated grouping across folders is not supported yet. However, you can do it manually. See here: https://github.com/jellyfin/jellyfin/issues/205#issuecomment-464220991
Maybe we should close this bug and continue in the other one, which is older?

**Comment by Sirfrancis17** [comment]
I saw it but when you group the movies they keep appearing duplicates 
#780
