### ISSUE TITLE
Only 1 core at 100%

### ISSUE THREAD

**Issue by Sirfrancis17** [jellyfin/jellyfin#945]
Hi
I do not know why but Jellyfin only uses me 1 core and this is always at 100% (Just watching the movie list) 
When you enter the Web page and select My library, Jellyfin takes about 15 seconds to load the page (list 100 movies) is it normal to be so late? 
What can be the mistake?
I use Docker (v. Jellyfin 10.2)
<a href="http://es.tinypic.com?ref=2jwsk6" target="_blank"><img src="http://i67.tinypic.com/2jwsk6.png" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by ddurdle** [comment]
Emby has always been a single threaded server application.  JellyFin hasn't fixed this issue yet.

**Comment by Sirfrancis17** [comment]
I added my movie library (gdrive + rclone) to Jellyfin. It has finished the indexing taking more than 1 day. 
Now every time I enter the movie section takes more than 15 seconds to show the content (100 movies) 
Every time go next page (Library) it takes more than 15 seconds.
Also, when I update the library it usually takes hours (no new file) 
This is normal? I say that because in Emby (v4) load the movie page is 1-2 seconds and updating the library takes a few minutes

**Comment by cvium** [comment]
@Sirfrancis17 it's far more interesting to know if Emby 3.5.2 is faster.

**Comment by ddurdle** [comment]
I use Google Drive content and Jellyfin but have no performance issues as such.  Library updates are very fast.

**Comment by Sirfrancis17** [comment]
It's weird. @ddurdle You also use the Docker version?

**Comment by NotExpectYet** [comment]
Mine's worse for loading my 17TB library. Once the dashboard is filled with information it's rather snappy, but takes about 2-3 minutes for that to full load with artwork. I'm on docker, latest version on unraid
. Can do a clean boot and load of the library for logs if it will help?

**Comment by hawken93** [comment]
what kind of CPUs are this? Are these especially slow CPUs or are they desktop / server class?

**Comment by Sirfrancis17** [comment]
Its a amlogic S912 octa core corte a53 64bits

**Comment by hawken93** [comment]
I've looked them up and in single core performance one of these are around 5-6 times slower than what I run jellyfin on so your delays could be up to 5-6 times as long I think..
https://browser.geekbench.com/v4/cpu/11882434

developers can simulate this a bit by using cpulimit, I think, to check if it leads to the same behavior

**Comment by hawken93** [comment]
Does jellyfin go back to idle when you leave it idle? How long does it burn cpu for when you hit it with a refresh?

**Comment by Sirfrancis17** [comment]
Yes.. If jellyfin not work the cpu its 5-10%
When refresh, the cpu burn at 100% but only 1 core from 8 (cpu have 8)

**Comment by Bond-009** [comment]
This should be fixed by #1011
