### ISSUE TITLE
Display "Disk subtitle" next to "Disk X" for multi-disk collections

### ISSUE THREAD

**Issue by MarkWieczorek** [jellyfin/jellyfin#9457]
I have a 24 disk collection of all the original CDs of an artist. The metadata lists these as

```
Disk: 1
Disk number: 1
Disk subtitle: The name of the original album.
```
and so on. However, in the Jellyfin interface, when I click on this collection, each disk is just labeled "Disk1", "Disk 2" and so on. This is non ideal, as I would like to know the name of the disk.

My suggestion is the following:

When displaying collections with multiple disks, instead of just displaying "Disk 1", display this as "Disk: Disk subtitle". For this case, this would be "Disk 1: The name of the original album".

**Comment by crobibero** [comment]
Feature requests belong at https://features.jellyfin.org
