### ISSUE TITLE
Default setting account.

### ISSUE THREAD

**Issue by rems25000** [jellyfin/jellyfin#9472]
Good morning,
Is it possible to preconfigure user settings for new accounts.
For example, the settings (Display, home, reading etc...) as well as critical settings like (Access to features, Remote control, Maximum number of concurrent user sessions, allow downloading...) I made a account which I called "default". How can I make Jellyfin use the user values ​​of this account for future new accounts?
Good for you dear contributors.

**Comment by nielsvanvelzen** [comment]
This is not possible at the moment. If you'd like to have this feature you can request it (or upvote an existing request) at https://features.jellyfin.org/.
