### ISSUE TITLE
[Issue]: splashscreen.png contains porn from hidden libraries

### ISSUE THREAD

**Issue by cevznriny** [jellyfin/jellyfin#9479]
### Please describe your bug

The splashscreen.png image is generated with hidden libraries including adult ones.

This is not appropriate for a family server.

Hidden and age inappropriate libraries should not be considered for inclusion.

### Jellyfin Version

Other

### if other:

10.8.8

### Environment

```markdown
- OS: Windows, Android TV
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 409700696** [comment]
在控制台-常规 里面关闭“Enable the splash screen”
