### ISSUE TITLE
[Issue]: Series cancelled when adjusting series settings

### ISSUE THREAD

**Issue by krelltunez** [jellyfin/jellyfin#9480]
### Please describe your bug

Hi, I just set up Jellyfin for Live TV/DVR using my HDHomeRun.  Long-time Plex user and experienced Linux user in general.  

I'm seeing the behavior referenced in #3523 and apparently fixed in #8752.  But, for me, this isn't fixed and keeps happening.  I actually purged my install and re-installed, only to find the problem is not avoidable.

Steps to reproduce:

1. Schedule a series recording
2. Click "Series Settings"
3. You don't even have to change a setting
4. Exit
5. No future recordings of series show in "Schedule" and it does not record

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Ubuntu LTS
- Virtualization: N/A
- Clients: All
- Browser: Chrome
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by krelltunez** [comment]
I decided not to use Jellyfin.  LiveTV features lacking.  Back to Plex....

**Comment by InvestigationNation** [comment]
This issue [https://github.com/jellyfin/jellyfin/issues/3523](url) has been plaguing me for weeks. This didn't seem to be an issue when I first build my Debian-based server a couple months ago, but it's been an issue for weeks now. Thanks to these bug reports at least I now realize I can record series successfully so long as I don't attempt to enter or tweak "Series Settings"

**Comment by cvium** [comment]
The PR https://github.com/jellyfin/jellyfin/pull/8752 has not been released yet. It will be in 10.9.
