### ISSUE TITLE
[Issue]: System.UnauthorizedAccessException: Access to the path '/var/cache/ldconfig' is denied.

### ISSUE THREAD

**Issue by heis2201** [jellyfin/jellyfin#9486]
### Please describe your bug

[2023-03-14 12:16:08.011 +00:00] [ERR] [18] Emby.Server.Implementations.IO.LibraryMonitor: Error in Directory watcher for: "/"
System.UnauthorizedAccessException: Access to the path '/var/cache/ldconfig' is denied.
 ---> System.IO.IOException: Permission denied

How to deal with this? What does it actually mean and could it be the cause that my library remains empty?

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Fedora37, jellyfin in podman container
- Virtualization: no, baremetal
- Clients:
- Browser: firefox
- FFmpeg Version: 5.1.2
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
The error makes me think that you added the root directory as a media path to a library instead of the actual media path.

**Comment by heis2201** [comment]
this is how I start the container

```
podman run \
 --detach \
 --log-level=error \
 --label "io.containers.autoupdate=registry" \
 --name jellyfin \
 --publish 8096:8096/tcp \
 --rm \
 --user $(id -u):$(id -g) \
 --userns keep-id \
 --volume /home/florian/jellyfin/cache:/cache:Z \
 --volume /home/florian/jellyfin/config:/config:Z \
 --mount type=bind,source=/home/florian/Videos,destination=/media/movies,ro=true,relabel=private \
 --mount type=bind,source=/home/florian/Musik,destination=/media/music,ro=true,relabel=private \
 docker.io/jellyfin/jellyfin:latest
```


Then I created two libraries, one called Movies pointing to `/media/movies`, one called Music pointing to `/media/music`.

Both libraries remain empty on the client(s), however I can `ls /media/movies` and `ls /media/music` within the container and see the content of the host directories

**Comment by heis2201** [comment]
so, here is the fix:
1.) Stopped the container
2.) Deleted cache and config folders on the host
3.) Created new cache and config folders in the same directory
4.) Started container (same flags) ..... and it works....

**Comment by heis2201** [comment]
So, is this a bug? When you accidentally select `/` as library folder but you change it to `/media` later, the first selection is somehow still known to the system and breaks the library? 
I remember I had selected / instead of /media during first setup (just clicked too fast)

**Comment by heis2201** [comment]
> The error makes me think that you added the root directory as a media path to a library instead of the actual media path.

But is this a bug? Because after changing the media path from `/` to `/media` the error didn't disappear. I had accidentally selected `/` but wasn't able to correct my mistake
