### ISSUE TITLE
[Issue]: unable to access my server remotely outside my network

### ISSUE THREAD

**Issue by Netpex22** [jellyfin/jellyfin#9488]
### Please describe your bug

Ive been unable to use Jellyfin remotely since downloading it.  I wrote to them but got no response.  Any information or instructions would be grand>

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS:windows 10
- Virtualization:
- Clients:browser, android and android tv
- Browser:chrome and edge
- FFmpeg Version: the latest
- Playback Method:direct play direct stream
- Hardware Acceleration:
- Plugins:nnone
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:local
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Bond-009** [comment]
https://jellyfin.org/contact

Join the troubleshooting room or Discord, this is a bug tracker.
