### ISSUE TITLE
update

### ISSUE THREAD

**Issue by htttito** [jellyfin/jellyfin#949]
Jellyfin don't update from 10.1.0 to 10.2.0
System: ubuntu-server 64bit
Installed from repository!

**Comment by htttito** [comment]
Jellyfin don't update from 10.1.0 to 10.2.0
System: ubuntu-server 64bit
Installed from repository!

**Comment by bobberb** [comment]
Dear @htttito

Everyone is excited to help. Please do everyone a favor and see your first post to get the best feedback.

**Comment by joshuaboniface** [comment]
@htttito This is a known configuration change with 10.2.0. Please see the updated documentation here: https://jellyfin.readthedocs.io/en/latest/administrator-docs/installing/#ubuntu

**Comment by htttito** [comment]
Thank you! 
The Docu. is a Perfect Work!
