### ISSUE TITLE
[Issue]: What is the purpose of letting jellyfin have `rw` to `card0`?

### ISSUE THREAD

**Issue by lucario** [jellyfin/jellyfin#9500]
### Please describe your bug

Per the hardware acceleration docs for `QSV`, it describes adding your user to the relevant groups for `rw` access to `card0` and `renderD128`. Fedora CoreOS by default allows `o=rw` to `renderD128`, so there is no need to add the user to the relevant group.

My question is for `rw` on `card0`. By default `o=`, what is the purpose of letting jellyfin have `rw` to `card0`? Hardware encode and tone mapping works fine without giving the user executing `jellyfin` `rw` to `card0`.

Ideally the purpose of these permissions should be explained so we are not needlessly granting permission. Jellyfin does not seem to need read or write access to `card0` for `QSV` hardware acceleration to function.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Fedora CoreOS
- Virtualization: Podman rootless
- Hardware Acceleration: QSV
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nyanmisaka** [comment]
`card*` is required by checking the engine usages via `intel_gpu_top`. We may use this tool in the future.

Or it fails with:
```
# intel_gpu_top
Failed to detect engines! (No such file or directory)
(Kernel 4.16 or newer is required for i915 PMU support.)
```

**Comment by nyanmisaka** [comment]
Fixed by https://github.com/jellyfin/jellyfin.org/pull/446
