### ISSUE TITLE
Transcoding TV streams

### ISSUE THREAD

**Issue by markster17** [jellyfin/jellyfin#9506]
Sorry if this was previously asked. I always wonder why my jellyfin TV stream would start transcoding but the same stream plays just fine on VLC player? Both share the same codec library right? I have come to experience that many times.
Could someone give me an answer?
Here is just one example: 
https://ec08.luz1.cache.orange.pl/jupiter/o2-cl7/live/tvrepublika/live.m3u8

**Comment by arucard21** [comment]
I don't use Live TV streams myself but I did notice that there is a user setting that seems to do exactly this.

In your own user's setting, under the Media Playback section (that contains whether to allow media playback and transcoded content), there is an option to force transcoding for remote media sources like Live TV. So you can try disabling this. 

I think transcoding isn't possible with VLC as external player. So it wouldn't be able to do that, even if it's forced.
