### ISSUE TITLE
[Issue]: Music Album Backdrop Images Not Showing

### ISSUE THREAD

**Issue by MagnificentJake** [jellyfin/jellyfin#9520]
### Please describe your bug

Backdrop images added to music albums do not show at all, both when added manually through file explorer or through the Jellyfin UI. Backdrop images added to artists, films, etc function as expected, but music albums do not load them correctly. Within the Jellyfin Edit Images dialogue for the music album, Jellyfin detects that there are backdrop images associated, but they appear as blank grey rectangles (screenshot attached).

Steps to reproduce:
1. Navigate to an album of music within Jellyfin
2. Upload a new backdrop image
3. It doesn't appear properly

Expected behaviour:
Either 1) uploaded backdrop images for music albums display correctly, as they do for other media types, or 2) if unsupported, backdrop images are not available as an option for music albums.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Windows 10
- Virtualization: None
- Clients: Browser, Jellyfin Media Player, Google TV
- Browser: Firefox 111.0, Chrome 111.0.5563.65
- FFmpeg Version: unsure, sorry!
- Playback Method: Direct Play
- Hardware Acceleration: none
- Plugins: none
- Reverse Proxy: none
- Base URL: none
- Networking: Host
- Storage: local
```

### Please attach any screenshots here

![image](https://user-images.githubusercontent.com/63098251/226324248-b824091b-8da4-49a6-b760-f47aba4d6da4.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MagnificentJake** [comment]
^ Issue is still affecting my installation

**Comment by przemek-kvapil** [comment]
I have the same issue
