### ISSUE TITLE
[Issue]:  Health check using old port to check container health status

### ISSUE THREAD

**Issue by vperas** [jellyfin/jellyfin#9532]
### Please describe your bug

After changing port number from 8096 to 80 in "Networking > Server Address Settings > Local HTTP port number", the docker health check always reports status "unhealthy" because it's trying to check health status on port 8096.

From log: "Failed to connect to localhost port 8096: Connection refused"

After adding:

    healthcheck:
      test: curl -i http://localhost/health

to docker compose, the health check works as expected

### Jellyfin Version

Other

### if other:

10.8.9

### Environment

```markdown
Official docker image: jellyfin/jellyfin
Version: 10.8.9
Operating System: Linux
Architecture: X64
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
If you change the port you need to override the healthcheck url yourself.
