### ISSUE TITLE
[Issue]: nvenc slow/slower preset order

### ISSUE THREAD

**Issue by TheTyrius** [jellyfin/jellyfin#9537]
### Please describe your bug

While browsing the transcoding code I noticed that for nvenc the "slow" setting uses a higher preset than the "slower" one. This seemed unintuitive to me, shouldn't it be the other way around? See https://github.com/jellyfin/jellyfin/blob/9f7418cf425ac295967ec5b826d992f69fa2fa10/MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs#L1554-L1564
-> slow uses p6, slower p5, but veryslow is p7

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nyanmisaka** [comment]
It seems the `slow` and `slower` cases are inverted. Feel free to open a PR to fix it.

**Comment by TheTyrius** [comment]
Closed by https://github.com/jellyfin/jellyfin/pull/9538
