### ISSUE TITLE
[Issue]: Missing album from metadata

### ISSUE THREAD

**Issue by update-freak** [jellyfin/jellyfin#9539]
### Please describe your bug

Hello,

I have a music-folder like this on my Synology NAS:
![folder](https://user-images.githubusercontent.com/40196995/227720830-09a6a8af-317f-47cc-8d14-c5de62aff57a.png)
The album is added on all FLAC-files, here e.g. The Imitation Game and also for all files in the folders.

The structure in the folder is the following:
Assassins Creed 2/Disc 1/*.FLAC
Assassins Creed 2/Disc 2/*.FLAC
Assassins Creed 3/*.FLAC ---> all other folders have no Disc 1 and Disc 2.

Also mentioned here https://github.com/jellyfin/jellyfin/issues/7778

I expected to have the albums according to the metadata defined in each FLAC-file and not just only a album when there is a folder. Also it's strange that I have two Assassins Creed 2 folders due to Disc 1 and Disc 2.

### Jellyfin Version

Other

### if other:

10.8.9

### Environment

```markdown
- OS: Synology DSM (Linux)
- Virtualization: Docker
- Clients: Kodi with Jellyfin-Plugin, Windows with Kodi and Jellyfin-Plugin, Android-App
- Browser: Chrome
- Plugins: Kodi Sync Quere
- Reverse Proxy: yes
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Bond-009** [comment]
Isn't this a duplicate of #1757 ?
