### ISSUE TITLE
TVDB and other sources not showing season images if episodes are placed in season folders

### ISSUE THREAD

**Issue by nothing2obvi** [jellyfin/jellyfin#9544]
I noticed that when searching for season posters for a show, if the show's episodes are placed in season folders (Season 01, Season 02, etc.), Jellyfin cannot find images from TVDB or any of the other sources I have enabled. However, if episodes are _not_ placed in season folders, this is not a problem.

Example: Truth Be Told (2019) // Episodes _not_ placed in season folders // Image search for season 2 // The 2 posters I find on thetvdb.com for season 2 are listed here. Although they don't _appear_ below, if you click them or press the download button, they work
![Screen Shot 2023-03-27 at 2 02 35 PM](https://user-images.githubusercontent.com/85228035/228066476-91047e36-c725-41fe-8f31-42c904371409.png)

Example 2: Survivor // Episodes placed in season folders // Image search for season 2 // However when I look for season 2 posters on thetvdb.com, there are indeed posters there.
![Screen Shot 2023-03-27 at 2 02 53 PM](https://user-images.githubusercontent.com/85228035/228066607-362cfb59-de1b-4765-97b6-331167ebca92.png)

### Jellyfin Version

Other

### if other:

10.8.9

### Environment

```markdown
- OS: Mac Ventura 13.2.1
- Virtualization: Docker 14.12
- Clients: Browser
- Browser: Opera 96.0.4693.80
- FFmpeg Version: 
- Playback Method: 
- Hardware Acceleration: none
- Plugins: aniDB, AudioDB, Cover Art Archive, Kodi Sync Queue, MusicBrainz, OMDb, Studio Images, TMDb, TVmaze, TheTVDB, Trakt, Webhook
- Reverse Proxy: none
- Base URL: none
- Networking: bridge(?)
- Storage: local
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Bond-009** [comment]
This works on master (unstable) for me

**Comment by nothing2obvi** [comment]
After going through each season and editing the metadata for "Season Number" this actually does work for me now. I will close this issue.
