### ISSUE TITLE
IPTV Fails to stream on Android Apps

### ISSUE THREAD

**Issue by fuzzynet** [jellyfin/jellyfin#957]
I have tried to play a m3u8 stream that plays fine on emby both on Android and Android TV, but won't load on the jellyfin. It will work on jellyfin thru the web browser.

**Comment by JustAMan** [comment]
@fuzzynet can you fill the issue using the template please?

**Comment by fuzzynet** [comment]
**Describe the bug**
IPTV from m3u8 stream fails to play on Android and Android TV, but will play thru web browser. All other media plays fine. The same stream plays on emby for Android, Android TV and web browser. I have tried the enable/disable direct stream setting for Live TV on Android TV but it didn't make a difference.

**To Reproduce**
1. Go Live TV section on Android or Android TV
2. Play a station.
3. Screen will change to now spinning wheel infidelity.

**Expected behavior**
The stream should load like it does thru web browser.

**Logs**
[jelly-log.txt](https://github.com/jellyfin/jellyfin/files/2889375/jelly-log.txt)

**Screenshots**
N/A

**System (please complete the following information):**
 - OS: Docker
 - Jellyfin Version: 10.2.0
 - Android Version: jellyfin-android_unminified_release_beta5.apk  
 - Android TV Version: jellyfin-androidtv_google-release_beta3.apk

**Comment by fuzzynet** [comment]
After posting this I noticed Jellyfin has released an update to 10.2.1 and have updated it. I have tested playback on Android, but not Android TV yet. It appears the initial stream will load fine, but the subsequent streams load the video, but the on screen display show the first stream's info. After I test on Android TV, I will post a new log file.

**Comment by Chemyto** [comment]
Hi, jellyfin work fine in mobile android, but in android tv, xiaomi mi box, failed to stream live tv.
