### ISSUE TITLE
[Issue]: The movie details page does not display stills

### ISSUE THREAD

**Issue by xiaofan-linux** [jellyfin/jellyfin#9580]
### Please describe your bug

The movie details page does not display stills

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
No info provided.

**Comment by xiaofan-linux** [comment]
> No info provided.

When using jellyfin, I found that sometimes scraped movies come with extrafanart folders, which contain exciting stills from extrafanart1.jpg and extrafanart2.jpg

https://qnam.smzdm.com/202208/15/62fa0f73e8bd87850.jpg_e1080.jpg

However, there is no stills displayed on the video display page of Jellyfin. Instead, take a screenshot of the actual video time period.

https://qnam.smzdm.com/202208/15/62fa0f41ef9529209.jpg_e1080.jpg
