### ISSUE TITLE
[Issue]: Hardware Acceleration not working following suggested fixes

### ISSUE THREAD

**Issue by Artnal** [jellyfin/jellyfin#9582]
### Please describe your bug

Hi there, 

I've recently started to setup Jellyfin on my **Jasper Lake** box and I'm struggling to get the **HWA** to work. I have read through a bunch of threads both here and on other platforms, to no avail. I was wondering wheter I've overlooked something stupid. Disclaimer: I am not that well versed into certain aspects of how HWA works for jellyfin (esp. ffmpeg). 

I am on **Debian 11**, kernel `6.0.0-0.deb11.6-amd64`, using the **linuxserver docker image (latest)**. So far, I have done the following:

- installed `firmware-linux-nonfree`, `intel-media-va-driver`, `intel-media-va-driver-non-free`, `intel-opencl-icd` (after changing the sources to get non-free);
- downloaded the missing firmware for i915 according to `update-initramfs`; 
- ran `update-initramfs -u  && sudo update-grub`;
- added the line `options i915 enable_guc=2` to `/etc/modprobe.d/i915.conf`;

When I run `intel_gpu_top`, everything stays at 0%

The output of `vainfo` is the following:

> error: XDG_RUNTIME_DIR not set in the environment.
MoTTY X11 proxy: Unsupported authorisation protocol
error: can't connect to X server!
libva info: VA-API version 1.10.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_10
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.10 (libva 2.10.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 21.1.1 ()
vainfo: Supported profile and entrypoints
      VAProfileNone                   : VAEntrypointVideoProc
      VAProfileNone                   : VAEntrypointStats
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSliceLP
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSliceLP
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointEncSliceLP
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileHEVCMain10             : VAEntrypointEncSliceLP
      VAProfileVP9Profile0            : VAEntrypointVLD
      VAProfileVP9Profile0            : VAEntrypointEncSliceLP
      VAProfileVP9Profile1            : VAEntrypointVLD
      VAProfileVP9Profile1            : VAEntrypointEncSliceLP
      VAProfileVP9Profile2            : VAEntrypointVLD
      VAProfileVP9Profile2            : VAEntrypointEncSliceLP
      VAProfileVP9Profile3            : VAEntrypointVLD
      VAProfileVP9Profile3            : VAEntrypointEncSliceLP
      VAProfileHEVCMain422_10         : VAEntrypointVLD
      VAProfileHEVCMain444            : VAEntrypointVLD
      VAProfileHEVCMain444            : VAEntrypointEncSliceLP
      VAProfileHEVCMain444_10         : VAEntrypointVLD
      VAProfileHEVCMain444_10         : VAEntrypointEncSliceLP

In case that's useful, the result of `dmesg | grep i915` is

> [    3.150792] i915 0000:00:02.0: [drm] VT-d active for gfx access
[    3.150825] i915 0000:00:02.0: vgaarb: deactivate vga console
[    3.150891] i915 0000:00:02.0: [drm] Using Transparent Hugepages
[    3.152131] i915 0000:00:02.0: vgaarb: changed VGA decodes: olddecodes=io+mem,decodes=io+mem:owns=io+mem
[    3.152217] i915 0000:00:02.0: firmware: direct-loading firmware i915/icl_dmc_ver1_09.bin
[    3.152668] i915 0000:00:02.0: [drm] Finished loading DMC firmware i915/icl_dmc_ver1_09.bin (v1.9)
[    3.153447] i915 0000:00:02.0: firmware: direct-loading firmware i915/ehl_guc_70.1.1.bin
[    3.153686] i915 0000:00:02.0: firmware: direct-loading firmware i915/ehl_huc_9.0.0.bin
[    3.305604] i915 0000:00:02.0: [drm] GuC firmware i915/ehl_guc_70.1.1.bin version 70.1
[    3.305610] i915 0000:00:02.0: [drm] HuC firmware i915/ehl_huc_9.0.0.bin version 9.0
[    3.322286] i915 0000:00:02.0: [drm] HuC authenticated
[    3.322293] i915 0000:00:02.0: [drm] GuC submission disabled
[    3.322295] i915 0000:00:02.0: [drm] GuC SLPC disabled
[    3.324852] [drm] Initialized i915 1.6.0 20201103 for 0000:00:02.0 on minor 0
[    3.329913] i915 0000:00:02.0: [drm] Cannot find any crtc or sizes
[    3.330125] i915 0000:00:02.0: [drm] Cannot find any crtc or sizes
[    5.433070] snd_hda_intel 0000:00:1f.3: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
[    5.642543] mei_hdcp 0000:00:16.0-b638ab7e-94e2-4ea2-a552-d1c54b627f04: bound 0000:00:02.0 (ops i915_hdcp_component_ops [i915])

Is there anything obvious that I should check? I saw a few times that ffmpeg version might be of relevance, but I am not sure to what extent here.

Thanks!

### Jellyfin Version

10.8.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nyanmisaka** [comment]
So where's the error? Upload the ffmpeg transcode log.

**Comment by nyanmisaka** [comment]
> [AVHWDeviceContext @ 0x55c3afa6fcc0] No VA display found for device /dev/dri/renderD128.
Device creation failed: -22.

It means the lsio docker has no permission to access the devices under `/dev/dri`.

Please refer to [lsio's docs](https://github.com/linuxserver/docker-jellyfin), or switch to the official docker image and check [our docs](https://jellyfin.org/docs/general/administration/hardware-acceleration/intel#official-docker).
