### ISSUE TITLE
[Issue]: Cannot get Intel Arc to work

### ISSUE THREAD

**Issue by uhthomas** [jellyfin/jellyfin#9588]
### Please describe your bug

Hey! I just bought an Intel Arc A380 to use for transcoding. I'm using the official Jellyfin image and can't get it to work. The host OS is running Linux 6.2.9 with the latest linux-firmware/i915 firmware. I can see the GPU is detected correctly from inside the container. I've enabled trancoding in Jellyfin and attempts to playback media are met with `Playback Error
This client isn't compatible with the media and the server isn't sending a compatible media format.`

I've also tried both QSV and VAAPI. This is specifically related to encoding, decoding seems to work fine.

See the output from `vainfo`:

```
❯ k -n media exec jellyfin-7f4d47c8f9-2zrvc -- /usr/lib/jellyfin-ffmpeg/vainfo
libva info: VA-API version 1.18.0
libva info: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_18
libva info: va_openDriver() returns 0
Trying display: drm
vainfo: VA-API version: 1.18 (libva 2.18.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 23.1.4 (12e141d)
vainfo: Supported profile and entrypoints
      VAProfileNone                   : VAEntrypointVideoProc
      VAProfileNone                   : VAEntrypointStats
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSliceLP
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSliceLP
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSliceLP
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointEncSliceLP
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileHEVCMain10             : VAEntrypointEncSliceLP
      VAProfileVP9Profile0            : VAEntrypointVLD
      VAProfileVP9Profile1            : VAEntrypointVLD
      VAProfileVP9Profile2            : VAEntrypointVLD
      VAProfileVP9Profile3            : VAEntrypointVLD
      VAProfileHEVCMain12             : VAEntrypointVLD
      VAProfileHEVCMain422_10         : VAEntrypointVLD
      VAProfileHEVCMain422_12         : VAEntrypointVLD
      VAProfileHEVCMain444            : VAEntrypointVLD
      VAProfileHEVCMain444            : VAEntrypointEncSliceLP
      VAProfileHEVCMain444_10         : VAEntrypointVLD
      VAProfileHEVCMain444_10         : VAEntrypointEncSliceLP
      VAProfileHEVCMain444_12         : VAEntrypointVLD
      VAProfileHEVCSccMain            : VAEntrypointVLD
      VAProfileHEVCSccMain            : VAEntrypointEncSliceLP
      VAProfileHEVCSccMain10          : VAEntrypointVLD
      VAProfileHEVCSccMain10          : VAEntrypointEncSliceLP
      VAProfileHEVCSccMain444         : VAEntrypointVLD
      VAProfileHEVCSccMain444         : VAEntrypointEncSliceLP
      VAProfileAV1Profile0            : VAEntrypointVLD
      VAProfileAV1Profile0            : VAEntrypointEncSliceLP
      VAProfileHEVCSccMain444_10      : VAEntrypointVLD
      VAProfileHEVCSccMain444_10      : VAEntrypointEncSliceLP
```

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Linux 6.2.9
- Virtualization: Docker `containerd://1.6.20`
- Clients: Browser
- Browser: Chromium
- FFmpeg Version: 5.1.2-Jellyfin
- Playback Method: Transcode (probably?)
- Hardware Acceleration: QVC, VAAPI
- Plugins: N/A
- Reverse Proxy: N/A
- Base URL: N/A
- Networking: N/A
- Storage: N/A
```

### Jellyfin logs

```shell
N/A
```

### FFmpeg logs

Apologies, I was prevented from creating the issue because it exceeded the maximum length of 65536 characters. Please see these gists:

QSV: https://gist.github.com/uhthomas/990a76a287d271bc318193c6bfd0712e
VAAPI: https://gist.github.com/uhthomas/cdabfdf29f2c0b12a4d0cc52d41d743b

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by almightiest** [comment]
Can you reproduce this in Jellyfin 10.8.9 and the latest jellyfin-ffmpeg5?  I seem to recall there being fixes related to ARC in recent releases, but your versions are very old.

**Comment by nyanmisaka** [comment]
@uhthomas Arc GPU doesn't support VC1 video decoding.
https://github.com/intel/media-driver#decodingencoding-features

**Comment by uhthomas** [comment]
@nyanmisaka That's fine, but I still see issues if VC1 decoding is disabled but with hardware encoding enabled. Do you have any advice on how to get things working? I can upload another log in a second.

**Comment by uhthomas** [comment]
https://gist.github.com/uhthomas/8c6490c2415190358bc540b830e67eca
![image](https://user-images.githubusercontent.com/9749173/229818543-1d9f443e-79fb-48f0-a26d-93454dfbbb0b.png)

**Comment by uhthomas** [comment]
> Can you reproduce this in Jellyfin v10.8.9 and the latest jellyfin-ffmpeg5 v5.1.2-9? I seem to recall there being fixes related to ARC in recent releases, but your versions are very old.
> 
> Does jellyfin user have access to the dri render file? Usually by adding jellyfin to the render group.

This is running in the Jellyfin container, I've tried the latest and `20230401.5-unstable`. Neither work.

**Comment by nyanmisaka** [comment]
> [h264_qsv @ 0x55e1de1ba340] Selected ratecontrol mode is unsupported
> [h264_qsv @ 0x55e1de1ba340] some encoding parameters are not supported by the QSV runtime. Please double check the input parameters.

Guc/Huc firmware is not working on your system. Debug them with the step 4 in https://jellyfin.org/docs/general/administration/hardware-acceleration/intel#configure-and-verify-lp-mode-on-linux

**Comment by uhthomas** [comment]
> > [h264_qsv @ 0x55e1de1ba340] Selected ratecontrol mode is unsupported
> > [h264_qsv @ 0x55e1de1ba340] some encoding parameters are not supported by the QSV runtime. Please double check the input parameters.
> 
> Guc/Huc firmware is not working on your system. Debug them with the step 4 in https://jellyfin.org/docs/general/administration/hardware-acceleration/intel#configure-and-verify-lp-mode-on-linux

This is running in a container, so maybe the firmware is missing from the official Jellyfin container?

**Comment by uhthomas** [comment]
I can see that the firmware is correct and GuC is being loaded. I can try setting GuC 2.

```
dmesg | rg guc
10.0.0.104: kern:    info: [2023-04-02T22:43:56.12710473Z]: i915 0000:06:00.0: [drm] GuC firmware i915/dg2_guc_70.bin version 70.5.1
```

**Comment by uhthomas** [comment]
Thank you for the pointers @nyanmisaka. I found that the `HuC` firmware was not loaded correctly. This is because the intel management engine interface (MEI) was disabled in the kernel. 

https://github.com/uhthomas/pkgs/commit/6a83361b8e4facfe551657e49bc71fa114d8be0f

```
10.0.0.104: kern:     err: [2023-04-02T22:43:53.91355135Z]: i915 0000:06:00.0: [drm] *ERROR* gt: timed out waiting for forcewake ack to clear.
10.0.0.104: kern:  notice: [2023-04-02T22:43:54.01669235Z]: i915 0000:06:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x222/0x240 [i915]
10.0.0.104: kern:     err: [2023-04-02T22:43:54.25415535Z]: i915 0000:06:00.0: [drm] *ERROR* render: timed out waiting for forcewake ack to clear.
10.0.0.104: kern:  notice: [2023-04-02T22:43:54.36146035Z]: i915 0000:06:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x222/0x240 [i915]
10.0.0.104: kern:     err: [2023-04-02T22:43:54.59869935Z]: i915 0000:06:00.0: [drm] *ERROR* vdbox0: timed out waiting for forcewake ack to clear.
10.0.0.104: kern:  notice: [2023-04-02T22:43:54.70600135Z]: i915 0000:06:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x222/0x240 [i915]
10.0.0.104: kern:     err: [2023-04-02T22:43:54.94322635Z]: i915 0000:06:00.0: [drm] *ERROR* vdbox2: timed out waiting for forcewake ack to clear.
10.0.0.104: kern:  notice: [2023-04-02T22:43:55.05052835Z]: i915 0000:06:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x222/0x240 [i915]
10.0.0.104: kern:     err: [2023-04-02T22:43:55.28778135Z]: i915 0000:06:00.0: [drm] *ERROR* vebox0: timed out waiting for forcewake ack to clear.
10.0.0.104: kern:  notice: [2023-04-02T22:43:55.39508335Z]: i915 0000:06:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x222/0x240 [i915]
10.0.0.104: kern:     err: [2023-04-02T22:43:55.63231835Z]: i915 0000:06:00.0: [drm] *ERROR* vebox1: timed out waiting for forcewake ack to clear.
10.0.0.104: kern:  notice: [2023-04-02T22:43:55.73961935Z]: i915 0000:06:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x222/0x240 [i915]
10.0.0.104: kern:    info: [2023-04-02T22:43:55.88071535Z]: i915 0000:06:00.0: [drm] Can't load HuC due to missing MEI modules
10.0.0.104: kern:    info: [2023-04-02T22:43:55.96722335Z]: i915 0000:06:00.0: [drm] HuC init failed with -5
10.0.0.104: kern:    info: [2023-04-02T22:43:56.03600835Z]: i915 0000:06:00.0: [drm] GuC firmware i915/dg2_guc_70.bin version 70.5.1
10.0.0.104: kern:    info: [2023-04-02T22:43:56.12877235Z]: i915 0000:06:00.0: [drm] HuC firmware i915/dg2_huc_gsc.bin version 7.10.3
10.0.0.104: kern:    info: [2023-04-02T22:43:56.22769135Z]: i915 0000:06:00.0: [drm] Finished loading DMC firmware i915/dg2_dmc_ver2_08.bin (v2.8)
10.0.0.104: kern:    info: [2023-04-02T22:43:56.33581935Z]: i915 0000:06:00.0: [drm] GuC submission enabled
10.0.0.104: kern:    info: [2023-04-02T22:43:56.40257535Z]: i915 0000:06:00.0: [drm] GuC SLPC enabled
10.0.0.104: kern:    info: [2023-04-02T22:43:56.46328835Z]: i915 0000:06:00.0: [drm] GuC RC: enabled
10.0.0.104: kern:    info: [2023-04-02T22:43:56.58327735Z]: [drm] Initialized i915 1.6.0 20201103 for 0000:06:00.0 on minor 0
10.0.0.104: kern:    info: [2023-04-02T22:43:56.67061735Z]: i915 0000:06:00.0: [drm] Cannot find any crtc or sizes
10.0.0.104: kern:    info: [2023-04-02T22:43:56.74480835Z]: i915 0000:06:00.0: [drm] Cannot find any crtc or sizes
```

It looks like hardware encoding is now working with Jellyfin and Intel Arc! :)

**Comment by nyanmisaka** [comment]
> Old kernel build configs [may not have the MEI modules enabled](https://gitlab.freedesktop.org/drm/intel/-/issues/7732), which are necessary for using ARC GPU on Linux.

I've mentioned this potential problem in our documentation.
