### ISSUE TITLE
[Issue]: Duplicate shows linked to eachother

### ISSUE THREAD

**Issue by DutchEllie** [jellyfin/jellyfin#9590]
### Please describe your bug

I have two versions of a TV show, that as far as I know cannot be merged together (I don't exactly know how, they're just two different video feeds). I have placed both of them in separate directories and imported them into Jellyfin. They have both been identified as the same show (so far so good), but then when I start playing one and stop playing, in "Continue Watching" both version of the same episode show up!  
In addition to that, when I press complete on one version, the other version is also completed! This is not what I want.

What I want is two entirely separated versions of the same show, next to eachother in Jellyfin. When I watch one, the other isn't affected and "Continue Watching" still shows me the correct next episode.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Ubuntu
- Virtualization: Proxmox
- Clients: Browser, Android
- Browser: Chrome, Firefox
- FFmpeg Version: 5.1.2-Jellyfin
- Playback Method: Transcode
- Hardware Acceleration: NVENC
- Plugins: None
- Reverse Proxy: Nginx
- Base URL: yes, /jellyfin
- Networking: Bridge? It just has its own IP
- Storage: ZFS vm disk
```

### Jellyfin logs

```shell
There doesn't seem to be much of a relevant log. I have a gist here: [https://gist.github.com/DutchEllie/c3bcce5f1ddf66ad86754806e24cb7e7](https://gist.github.com/DutchEllie/c3bcce5f1ddf66ad86754806e24cb7e7)
```

### Please attach any screenshots here

This was after halfway watching the first episode of one of the versions. Both versions show up here.
 
![image](https://user-images.githubusercontent.com/6501187/229600619-0f8166a6-b438-4f2d-abcb-560db7438726.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TimGels** [comment]
I am not familiar with multi versions. But this sounds to me like a "hacky" workaround to get multiple versions for show type working. As far as I know, we only really support multiple versions with movies (I can be wrong, once again, this is not an area in Jellyfin that I have used / tried). That aside, have you considered creating a separate library for the other version? I also heard about people using the Merge Versions plugin, which also sounds like worth looking into perhaps?
