### ISSUE TITLE
Jellyfin AndroidTV not playing MKV files with VAAPI

### ISSUE THREAD

**Issue by Blu3wolf** [jellyfin/jellyfin#9591]
Jellyfin on my Android TV appears to not play back .mkv files. Seems similar to #7642

Log files: 
https://pastebin.com/tVSC5Ldt
https://pastebin.com/ZtTHHcjF

The host has Mesa 23.0.1 from the nonfree.eu repo (to enable VA-API). This is with jellyfin-ffmpeg 5.1.2 from the AUR. Jellyfin for Android TV, 15.6. 

Other files appear to playback fine.

**Comment by Blu3wolf** [comment]
So the Mesa driver I have is already built. Doesnt patching require I build from source?

**Comment by nyanmisaka** [comment]
You have to patch the source code of Mesa and rebuild it.
```
MESA_VA_PIC="mesa/src/gallium/frontends/va/picture.c"
MESA_VA_CONF="mesa/src/gallium/frontends/va/config.c"
# force reporting all packed headers are supported
sed -i 's|value = VA_ENC_PACKED_HEADER_NONE;|value = 0x0000001f;|g' ${MESA_VA_CONF}
sed -i 's|if (attrib_list\[i\].type == VAConfigAttribEncPackedHeaders)|if (0)|g' ${MESA_VA_CONF}
```

**Comment by Blu3wolf** [comment]
Going by the comments on [this related issue](https://gitlab.freedesktop.org/mesa/mesa/-/issues/3524), it seems the driver does indeed not properly support packed headers. Why does patching the driver so that it claims to support it, make any difference?

I appreciate the help very much. At this stage I am thinking of looking for a workaround, such as transcoding the offending files to a different container, rather than patching my driver, which might rather complicate seeking support for it.

**Comment by nyanmisaka** [comment]
> but the firmware on AMD's GPU doesn't support packed headers

Said by the AMD developer. Only Intel has complete VA-API implementations, AMD is only compatible with VA-API but some functions or features have not been implemented.

Close this for now as it's an upstream limitation.

**Comment by candrews** [comment]
@nyanmisaka there's an upstream mesa engineering looking at this problem now: https://gitlab.freedesktop.org/mesa/mesa/-/issues/3524#note_1989027

Perhaps you could chime in too?
