### ISSUE TITLE
[Issue]: Library items not showing up in the gui

### ISSUE THREAD

**Issue by stanelie** [jellyfin/jellyfin#9599]
### Please describe your bug

So, I have this downloads folder where I put all my media, be it tv shows, movies or music.
I've created 3 libraries for it : shows, movies and music. Only the first one shows any items.

Thoughts?

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Ubuntu 18.04 LTS
- Virtualization: yes
- Clients: web, android and Roku
- Browser: Chrome
- FFmpeg Version: 3.4.11-0ubuntu0.1
- Playback Method: Play button
- Hardware Acceleration: No
- Plugins: built in
- Reverse Proxy: no
- Base URL: secret
- Networking: ipv4
- Storage: yes
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Bond-009** [comment]
Did you check the folder permissions?

**Comment by nielsvanvelzen** [comment]
You can't use the same folder in multiple libraries.

**Comment by stanelie** [comment]
Is this a bug or by design?
