### ISSUE TITLE
Api future?

### ISSUE THREAD

**Issue by Tolriq** [jellyfin/jellyfin#96]
Just discovered this fork from a comment on my app (Yatse) that support many things from Emby.

What are the plans on the API versioning?
Move away from Emby with different scheme keep the same, ....?
Just to have a vision to know if I can officially support this fork or nor.

**Comment by joshuaboniface** [comment]
At the moment we don't have a solid future plan to break API compatibility, so as long as your app doesn't do anything to lock out non-premium Emby users, we should remain compatible for a long while yet. Thanks!

**Comment by Tolriq** [comment]
The app enable things on normal Emby version that normally require premium so the oposite ;)
Like smart downloads.

The things is not just about breaking change but about identifying the fork and it's version scheme even for simple additions if you announe Emby 3.6 but are not Emby 3.6 it will be an issue.

I have a new release of my app planned soon and can talk about your fork to give you quite some exposure.

What link do you want pushed?

**Comment by anthonylavado** [comment]
@tolriq I think right now we're just using the main repo page, so that's probably best. @joshuaboniface confirm?

**Comment by joshuaboniface** [comment]
Linking to `http://jellyfin.media` is probably best - right now it redirects to the repo, but when we do get a site going it will be the landing page.

**Comment by Tolriq** [comment]
https://jellyfin.media/ and http://jellyfin.media both don't work :(

I'll put the https://github.com/jellyfin/jellyfin in the changelog for now, the app is not mainly Emby but that changelog will still be seen by many ;)

If things evolves on your side I'll add more things on the forums and website.

Good luck with the fork, I hope you are prepared for the horde of always unhappy users :p

**Comment by gerroon** [comment]
I use Yatse with Emby it is nice, except that well the database sync takes a long time (like 15 min). I am wondering if there could be some optimizations on the database side so that API access is faster?

**Comment by Tolriq** [comment]
Most probably, Movies sync times are the worst but not at that point.

Please open an issue on https://community.yatse.tv/ with logs to have more details about what is so slow for your particular setup.

**Comment by gerroon** [comment]
I know why it is slow, I have thousands of videos/media/ gigagbytes of music

**Comment by Tolriq** [comment]
Not a reason to be 15mn

**Comment by nvllsvm** [comment]
@Tolriq https://jellyfin.media is now functional.

**Comment by Tolriq** [comment]
Well seem you did actually change API versioning :) 
@joshuaboniface @nvllsvm 

https://github.com/jellyfin/jellyfin/commit/f508fe394ac328fedf36a1e2ba5b257bf2e1cef1

API now returns version 10.0.0.0 so will break most consumers that expect something else.

For API consumer to properly handle such change we need to have a way to identify that it's a JellyFin server, 

Would be nice that "/System/Info" have something for that, like a field ```"IsJellyFin":true```

**Comment by Tolriq** [comment]
And since from API point of view you are now a different entity do you have a final logo in vector so I can integrate in Yatse to show the correct one?

**Comment by sparky8251** [comment]
> And since from API point of view you are now a different entity do you have a final logo in vector so I can integrate in Yatse to show the correct one?

Yup! Check https://github.com/jellyfin/jellyfin-ux for the files.

**Comment by joshuaboniface** [comment]
@Tolriq I'm actually considering that a regression. The solution only has one location to change version but I do want us to report that we're "Emby 3.5.2" compliant. Can you confirm where you get the version info from?

**Comment by Tolriq** [comment]
For me yes, any new field to identify Jellyfin is OK that's what I suggested.

For all other consumers I can't tell. But don't know if there's many, and if those do check versions anyway :)

If you really want to be future proof, you can also add another field embyCompatibility: true that way consumers will easily be warned when/if you do change that render API no more compatible in the future by changing that to false.

**Comment by EraYaN** [comment]
#508 takes care of the versioning. And it keeps the main version attribute the same.

For newer APIs we should have a `\v2\` endpoint.

**Comment by Tolriq** [comment]
Nope for ```/v2/``` API for this kind of servers are moving targets, consumers rely on the API version to know if a feature is present or not. But usually API have it's own version scheme to be able to warn about breaking change or not.

You can't add a ```/v2/``` because you add a new parameter to transcoding, Then a ```/v3/``` when you add a new metadata value, it ends at ```v99999999``` ;) Semantic versioning for API is real thing for APIs too.
Do you think you'll keep all the ```/vx/``` active all the time?

Usually API versions are different from server versions to be clean, it's not the case for Plex and Emby so does not necessarily needs to be the case here. Just needs proper documentation so consumers can know what is supported at what version and what version contains a breaking change from previous one.

Do not jump to a ```/v2/``` unless you write a completely new different API. It will be a burden for each sides to manage.

**Comment by EraYaN** [comment]
Well that was the intention if it's going to be very different. I suppose one would aim for a semi-stable api. And then the next architectural change would be v3. something like that.

But if it's me writing a v2 api, there will be client libs to go with it too. And full documentation. But that is something for the far future.

**Comment by Tolriq** [comment]
Stable API means no breaking changes, adding things is still stable API and can stay stable for years while still embracing all the new things.

And for the record I would never use a client lib for that purpose, I have proper optimized ways to handle things and no client libraries could match the requirement and integration needs.

And since I'm dealing with Media Centers APIs since 10 years, please if you write a new thing from scratch involve the consumers of the API, not all requirement can be thought of ;)

**Comment by gerroon** [comment]
I agree with Tolriq. His app does what it does well, so I recommend the Jellyfin devs to take a look at what he is trying to get at.

**Comment by anthonylavado** [comment]
I think we're okay on this front for now. We haven't made any drastic changes to this, as we're focused on getting other things fixed (client apps, and refactoring the server). We can revisit if we need to, as we're definitely not changing the API yet (especially since our own apps use it).
