### ISSUE TITLE
Subtitle Burn in Causes Stuttering and Courruption w/ AMD & VAAPI

### ISSUE THREAD

**Issue by alexi741** [jellyfin/jellyfin#9601]
## Description ##
When attempting to burn-in subtitles, the transcoded video stutters and becomes corrupted .

May be related to https://github.com/jellyfin/jellyfin/issues/9212

**System:**
 - OS: Debian Bookworm (Linux 6.1.0-6-amd64)
 - Jellyfin Version: 20230330.16-unstable
 - FFmpeg Version: 6.0-1-bookworm
 - Hardware settings: VAAPI
 - Video Device: Ryzen PRO 5650GE iGPU
  - Clients: Roku, Web, Android App

## Logs ##

**Media Info of the file**
https://pastebin.com/pMLeifCV

**Jellyfin Server Logs**
https://pastebin.com/vCHGkR1C

**FFmpeg Logs**
https://pastebin.com/JkhKJ4hi

## Media ##

**Sample Video Clip**

[Shin Godzilla — Mozilla Firefox 2023-04-05 14-03-31.webm](https://user-images.githubusercontent.com/1930427/230167664-a43fc092-b2a3-4641-ab5b-677e9942d296.webm)

**Sample Screenshot**
![image](https://user-images.githubusercontent.com/1930427/230147484-1e430f21-6dac-4179-8d80-72ccd7fb0f7d.png)

**radeontop output**
![image](https://user-images.githubusercontent.com/1930427/230154370-bb53f861-df97-44d3-afe3-178094a01a06.png)

**Comment by nyanmisaka** [comment]
#9584

**Comment by alexi741** [comment]
You're a hero, @nyanmisaka!

**Comment by Bond-009** [comment]
Should be fixed by https://github.com/jellyfin/jellyfin/pull/9584
