### ISSUE TITLE
[Bug] High Ram Usage When Transcoding with NVIDIA NVENC

### ISSUE THREAD

**Issue by LoopedSdrawkcaB** [jellyfin/jellyfin#9602]
When NVIDIA NVENC is selected to transcode, memory usage slowly creeps up and uses the 16GB allocated to the VM. I have reverted back to no hardware transcoding and the memory issue disappears. When closing the stream it seems the memory usage hangs and then drops down to about 5GB of usage until I reboot the machine.

Software

- Proxmox 7.3-3
- Ubuntu 22.04.2
- Docker / Docker Compose
- Jellyfin 10.8.9
- Fresh Install
- Nvidia Driver Version 525.89.02

Hardware

- GPU is P4000 
- CPU Xeon(R) W-2133 CPU
- 32GB Ram

**Comment by nyanmisaka** [comment]
@LoopedSdrawkcaB Can you share the ffmpeg transcoding log created by the stream you mentioned and NVENC?

**Comment by LoopedSdrawkcaB** [comment]
[Transcode Log.txt](https://github.com/jellyfin/jellyfin/files/11163178/Transcode.Log.txt)

Here it is

**Comment by nyanmisaka** [comment]
No errors in the log. I don't see any reason NVENC or CUDA will eat up such memory.

Can you check the RAM usage via `top` or `nvidia-smi` and find out which process is the cause?

**Comment by nyanmisaka** [comment]
Close as cannot reproduce on both Linux and Windows.
