### ISSUE TITLE
As time goes by, the media on Jellyfin can hardly be played at all. PLEASE HELP ME :(

### ISSUE THREAD

**Issue by tarokeitaro** [jellyfin/jellyfin#9608]
**Media Info of the file**
Complete name                            : 10.レイメイ.flac
Format                                   : FLAC
Format/Info                              : Free Lossless Audio Codec
File size                                : 44.9 MiB
Duration                                 : 5 min 14 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 1 197 kb/s
Album                                    : 酸欠少女
Album/Performer                          : さユり
Track name                               : レイメイ
Track name/Position                      : 10
Track name/Total                         : 11
Performer                                : さユり & MY FIRST STORY
Recorded date                            : 2022
ISRC                                     : JPU901803696
Cover                                    : Yes
Cover type                               : Cover (front)
Cover MIME                               : image/jpeg
Comment                                  : ExactAudioCopy v1.6
DISCID                                   : 850BB80B

Audio
Format                                   : FLAC
Format/Info                              : Free Lossless Audio Codec
Duration                                 : 5 min 14 s
Bit rate mode                            : Variable
Bit rate                                 : 1 189 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 44.1 kHz
Bit depth                                : 16 bits
Compression mode                         : Lossless
Stream size                              : 44.6 MiB (99%)
Writing library                          : libFLAC 1.2.1 (UTC 2007-09-17)
MD5 of the unencoded content             : D3A796CFBFC2FD69D0D2F79E554C22C2

**Logs**
1:46 AM
[01:46:58] [INF] [19] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app Jellyfin Web 10.8.9 playing レイメイ. Stopped at 261 ms
jellyfin
1:46 AM
System.InvalidOperationException: Response Content-Length mismatch: too few bytes written (0 of 46307502).
jellyfin
1:46 AM
[01:46:58] [ERR] [13] Microsoft.AspNetCore.Server.Kestrel: Connection id "0HMPMKPHNEM4P", Request id "0HMPMKPHNEM4P:00000002": An unhandled exception was thrown by the application.
jellyfin
**FFmpeg Logs**
Direct

**Stats for Nerds Screenshots**
song or video plays for a few milliseconds, then playback error
![image](https://user-images.githubusercontent.com/42670754/230469266-ceeac76a-6a65-44df-a31e-e813dd2e6feb.png)
![image](https://user-images.githubusercontent.com/42670754/230471454-c5f8b477-c70d-47b7-89bb-a4cc1025329a.png)
![image](https://user-images.githubusercontent.com/42670754/230472033-774558bf-ac8c-4600-9d42-6a52c4126b38.png)

**Server System (please complete the following information):**
 - OS: Fedora Linux 37 (Server Edition)
 - Jellyfin Version: Jellyfin.Server 10.8.9.0
 - Hardware settings & device: Software
 - Reverse proxy: nginx
 - Other hardware notes: Media mounted from Google Drive
 
**Client System (please complete the following information):**
 - Device: All device
 - OS: All
 - Client: Jellfin media player. mpv, findroid, finamp
 - Browser: all
 - Client and Browser Version: all

**Comment by tarokeitaro** [comment]
I didn't know what solution to use, all my users complained to me.

Here is a screen shot of how it happened, and what would happen if I played the same media on my other server.
https://cdn.discordapp.com/attachments/800026280204304424/1093965350493761736/2023-04-08_01-25-19.mp4

**Comment by BrianCArnold** [comment]
Have you tried copying some media files to a non-google drive mounted location, adding that location as a library, and trying to play those back? 

Additionally, you have provided the _service_ logs, not the **Jellyfin** logs. 

Go to the Administration Dashboard, and click `Logs` under Advanced. The logs in this location are highly detailed and should be able to help determine the cause of the issue.

**Comment by tarokeitaro** [comment]
I haven't tried playing media from non-google drive yet (I'll try it after this). but I have another server that uses the same source that runs fine

these are the logs from Dashboard > Advanced > Logs
https://stream.animoe.my.id/cloud/share/mnbN4GRJ

I don't understand this log that shows `Microsoft.AspNetCore`
