### ISSUE TITLE
[Issue]: NFO isn't parsed as UTF-8 / Special Characters not displayed correctly

### ISSUE THREAD

**Issue by Wortex17** [jellyfin/jellyfin#9611]
### Please describe your bug

I have added some additional metadata via local NFOs (to augment fetcher data, I am not using the NFO saver)
In this case, I added japenese characters to the originaltitle.
These are displayed as question marks in the client.
Note that the japanese characters fetched from the provider e.g. IMDB are displayed fine - this is only an issue when overwritten via local NFOs

Sample:
```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<tvshow>
  <originaltitle>Acchi Kocchi | あっちこっち</originaltitle>
</tvshow>
```

Update:
I noticed that when editing the data inside jellyfin metadata editor it works fine. Exporting with NFO saver also works with (albeit, the files charset is OEM-US not UTF-8) but reimporting it again (even though its the same file it exported) will break it again.

Could be confirmable/reproducible via an unit test for export-import with japanese characters or emojis

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Synology DSM 7
- Virtualization: Docker
- Clients: Browser
- Browser: Firefox
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Please attach any screenshots here

![grafik](https://user-images.githubusercontent.com/170627/230499634-9926f6ea-476a-4bcf-a908-3df23da13456.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Wortex17** [comment]
I noticed that when editing the data inside jellyfin metadata editor it works fine. Exporting with NFO saver also works with (albeit, the files charset is OEM-US not UTF-8) but reimporting it again (even though its the same file it exported) will break it again.

Could be confirmable/reproducible via an unit test for export-import with japanese characters or emojis

**Comment by Wortex17** [comment]
Still happening

**Comment by Wortex17** [comment]
I can see this was moved to "insufficient data", but no further information was requested - anything we can do to help?

**Comment by felix920506** [comment]
We are waiting for a volunteer to test this

**Comment by Wortex17** [comment]
I'm sorry if I misunderstand, but test what exactly? I don't see any PR to be tested etc.  and while I' offer myself as volunteer, I don't know what data you might need.
The label is undocumented in https://jellyfin.org/docs/general/contributing/issues/#issue-labels

**Comment by Optimus1008** [comment]
I just switched to generating nfo files on my server and got the same problem... but since I'm german all umlaute (öäü) and the "Eszett" (ß) get also replaced by a question mark since the current encoding doesn't support these characters... which is a bummer as they appear many times in the German language...

**Comment by Shadowghost** [comment]
I did check the server code when the issue was filed and the files should be opened in UTF-8 mode, so not sure what else can be done. I will take a look over the weekend again, maybe I missed something.

**Comment by sjorge** [comment]
I can't reproduce this either, I have a lot of tvshow.nfo hint files for my anime e.g. mine for Acchi Kocchi is 
```xml
<?xml version="1.0" encoding="utf-8"?>
<tvshow>
  <title>Acchi Kocchi</title>
  <originaltitle>あっちこっち</originaltitle>
  <uniqueid type="anidb" default="true">8890</uniqueid>
  <uniqueid type="anilist" default="false">12291</uniqueid>
  <uniqueid type="tmdb" default="false">63712</uniqueid>
  <premiered>2012-04-06</premiered>
</tvshow>
```

I wonder if it is because whatever tool/editor write the file did not write it with utf-8 encoding.

**Comment by Shadowghost** [comment]
Would be interesting if someone with bad files can check their encoding. If it is wrong, there isn't much we can do.

**Comment by Optimus1008** [comment]
just deleted all NFOs and let Jellyfin regenerate them... for now, it seems okay, but I'll check again at another time... already checked if, for some reason, any other service (tdarr, sonarr) may cause this, but with no luck... maybe it really was a one-time error... weird nonetheless...

**Comment by Wortex17** [comment]
I'll try to find time to double check this week

**Comment by Wortex17** [comment]
While trying to reproduce the issue, I noticed that this was likely the cause of my original issue:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9153

So it was Notepad++'s fault

I'll try to find time to verify the mentioned export+import route, because i didn't document if i had touched the exported nfo with npp in any way in between (I shouldn't have, but lets see)
