### ISSUE TITLE
[Issue]: Shows sometimes being readded when library scanned

### ISSUE THREAD

**Issue by Gaffers2277** [jellyfin/jellyfin#9615]
### Please describe your bug

Shows i added to the library are being re-added and the date added date is being reset to the current date. Sometimes the library scan works perfectly with no problems just adds new shows and episodes but sometimes it will re-add shows i added before. Its not a big deal but it does mess up the Home Menu latest list, the filter by date added and makes it hard to find the latest episodes added. Would it be possible to lock the date added metadata for a show?

### Jellyfin Version

10.8.0

### if other:

10.8.9

### Environment

```markdown
- OS:Windows 10
- Virtualization:No
- Clients:Jellyfin Media Player, browsers & Roku
- Browser:Safari and Firefox
- FFmpeg Version:
- Playback Method:N/A
- Hardware Acceleration:Yes, Nvidia NVENC
- Plugins:AniDB, AudioDB, CoverArtArchive, IntroSkipper, Intros, Jellyscrub, Musicbrainz, OMDB, OpenSubtitles, Playback Reporting, Reports, SkinManager, Studio Images, TMDB, theTVDB, ThemeSongs, Themerr, Webhooks
- Reverse Proxy:Nginx Reverse Proxy
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Bond-009** [comment]
We have this option in library settings:
![image](https://user-images.githubusercontent.com/21289123/230745594-36de374b-e374-49ce-b266-bbbf6bfb3f8f.png)

**Comment by Gaffers2277** [comment]
Yes i know that setting but that doesnt solve my problem as i have changed that setting but it still re-adds shows so this is a bug. Rather then assume you fixed my problem and close the issue maybe what till i can confirm it fixes it.

**Comment by Bond-009** [comment]
Or I can just reopen it, no big deal.

**Comment by Gaffers2277** [comment]
@Bond-009 Thanks, it seems to be tied to the metadata being updated for the date added tag. It happened again last night clearing all my latest added shows and now just shows one show i added over 6 months ago. I see under the setting you showed that both options will be ignored if there is a metadata value present and when i check the show on the home menu the date added has been updated to todays date.
