### ISSUE TITLE
What does this hash mean ?

### ISSUE THREAD

**Issue by BakkFail** [jellyfin/jellyfin#963]
Hey guys, great work on this repo !
I'm trying to create automatically accounts for my users, but I want them not to have permissions such as admin, media deletion, etc.
I'm altering the database /var/lib/jellyfin/data/users.db, but for permissions I want to edit the file /etc/jellyfin/users/<hash>/policy.xml. But where does this hash come from ?
Thanks for the help

**Comment by EraYaN** [comment]
You might have more luck using parts of the API. Not sure if it is at all documented, but old Emby docs might work.

**Comment by Badidzetai** [comment]
I am interested in this, too : how much of the old Emby docs are related to Jellyfin ?

**Comment by JustAMan** [comment]
Your safe bet should be Emby 3.5.3 docs, anything newer might not work.
