### ISSUE TITLE
[Issue]: Artists with Semicolon in name treated as multiple artists

### ISSUE THREAD

**Issue by FairlyBored** [jellyfin/jellyfin#9636]
### Please describe your bug

Artists with names containing a semicolon are treated as two artists. An example of an artist with a semicolon in the name is [We;Na](https://musicbrainz.org/artist/532996ca-2cf6-4c70-8b4e-7f8a99a2ac62)

For reference, my files(FLAC) are tagged with [Picard[(https://picard.musicbrainz.org/) and matched to their corresponding entries on MusicBrainz, and contain the appropriate MBIDs in addition to standard tags.

### Jellyfin Version

10.8.0

### if other:

10.8.9

### Environment

```markdown
- OS:Linux
- Virtualization:VirtualBox
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AmbulantRex** [comment]
The `;`, `'|'`, `,`, and `/` characters are very common to use as delimiters. In the case of Artists, I believe this is the relevant code:
https://github.com/jellyfin/jellyfin/blob/c2b88f1852b16c2dde69b13c89feb34f78268057/MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs#L152-L162

Obviously, some artists are going to use our delimiters (e.g. AC/DC) so a whitelist appears to be available in this same file here:

https://github.com/jellyfin/jellyfin/blob/c2b88f1852b16c2dde69b13c89feb34f78268057/MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs#L45-L71

If this is the right spot, then it could be as simple as adding another artist to the list. A more robust solution may be warranted though.

**Comment by AverageHelper** [comment]
I'm facing this issue as well with artist [リア;クオ](https://www.youtube.com/@liaquo) (lia;quo). Is there some escape character I should enter manually in the metadata editor i.e. `lia\;quo`? Or is the current solution to file a PR to add affected artist's names to [ProbeResultNormalizer.cs](https://github.com/1337joe/jellyfin/blob/927fe33d3a0ec7f9e0fb568cfd423c6e8b966c9d/MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs#L44) (as in #10329)?

**Comment by gnattu** [comment]
See this: https://github.com/jellyfin/jellyfin/pull/12385

This behavior is fully customizable in 10.10. The old behavior and the normalizer is no longer relevant unless our new preferred prober cannot detect your tagged data.

We don't recommend manually editing music metadata directly in the metadata manager and put them properly tagged in the original file should be preferred as that editor does not handle such multi-value tags very well.

**Comment by AverageHelper** [comment]
Aw dang, and I just got done manually splitting a bunch of artist names that way 😅

**Comment by AverageHelper** [comment]
Oh gosh, I'm tired, lol. I just figured out that #12385 doesn't have to do with needing my music files properly tagged haha.

So (for future googlers I guess) there's a (new?) Library setting where we can add our own whitelist of artists with separator characters in their name!

In my case tho, adding the affected artist to that list (e.g. `lia;quo`) and re-scanning leaves the affected track still showing `lia` and `quo` as separate artists (e.g. "lia, quo" where the metadata editor reads `lia;quo`), but maybe there's some other process or cron job where Jellyfin might go through and notice that track later on?

I suppose I might need to learn Picard or something anyway, huh 😔

**Comment by gnattu** [comment]
> In my case tho, adding the affected artist to that list (e.g. lia;quo) and re-scanning leaves the affected track still showing lia and quo as separate artists (e.g. "lia, quo" where the metadata editor reads lia;quo), but maybe there's some other process or cron job where Jellyfin might go through and notice that track later on?

You need replace all metadata scan to re-create the artists.

**Comment by AverageHelper** [comment]
Ohhhh gotcha. That worked, thanks for the help!
