### ISSUE TITLE
Mjpeg avi support

### ISSUE THREAD

**Issue by Peny20** [jellyfin/jellyfin#9639]
I am running Jellyfin server on docker on ubuntu server for about a year. Meanwhile I had to update my jellyfin server to a newer version, because jellyfin client on TV needed the newer version of the serwer. Lately I tried to open on TV old MJPEG .avi video file but It failed and I got message "This client isn't compatible with the media and the server isn't sending a compatible media format.". I am pretty sure that on older versions of Jellyfin I was able to play this video on TV using Jellyfin client So, I have a question. Does Jellyfin support  MJPEG .avi video formats or do I remember incorrectly?  I tried to update server to a newer version 10.8.9, but still I cannot play this type of videos (on web browser it fails too). 

**Media Info of the file**

Image
Codec: MJPEG
Codec tag: MJPG
Profile: Baseline
Resolution: 640x480
Bitrate: 5066 kbps
Bit depth: 8 bit
Color space: bt470bg
Pixel format: yuvj422p
Ref frames: 1

Audio
Title: PCM_U8 - 1 ch
Codec: PCM_U8
Channels: 1 ch
Bitrate: 88 kbps
Sample rate: 11024 Hz
Bit depth: 8 bit
Default: No
Forced: No
External: No

**Logs**
"This client isn't compatible with the media and the server isn't sending a compatible media format."

**FFmpeg Logs**
/videos/0d7a699b-2248-587b-7dac-0fbb7e861916/hls1/main/0.ts

{"Protocol":0,"Id":"0d7a699b2248587b7dac0fbb7e861916","Path":"/media/videos/2008/2008_06_15 f TANIEC PAWEL/MVI_9123.AVI","EncoderPath":null,"EncoderProtocol":null,"Type":0,"Container":"avi","Size":19341394,"Name":"MVI_9123","IsRemote":false,"ETag":"60ddcfc269c7abec096e3a1c44891a77","RunTimeTicks":300000000,"ReadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"OpenToken":null,"RequiresClosing":false,"LiveStreamId":null,"BufferMs":null,"RequiresLooping":false,"SupportsProbing":true,"VideoType":0,"IsoType":null,"Video3DFormat":null,"MediaStreams":[{"Codec":"mjpeg","CodecTag":"MJPG","Language":null,"ColorRange":null,"ColorSpace":"bt470bg","ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Comment":null,"TimeBase":"1/10","CodecTimeBase":null,"Title":null,"VideoRange":null,"VideoRangeType":null,"VideoDoViTitle":null,"LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"DisplayTitle":null,"NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":5083796,"BitDepth":8,"RefFrames":1,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":false,"IsForced":false,"Height":480,"Width":640,"AverageFrameRate":10,"RealFrameRate":10,"Profile":"Baseline","Type":3,"AspectRatio":"4:3","Index":0,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":"yuvj422p","Level":-99,"IsAnamorphic":null},{"Codec":"pcm_u8","CodecTag":null,"Language":null,"ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Comment":null,"TimeBase":"1/11024","CodecTimeBase":null,"Title":null,"VideoRange":null,"VideoRangeType":null,"VideoDoViTitle":null,"LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"DisplayTitle":"PCM_U8 - 1 ch","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":88192,"BitDepth":8,"RefFrames":null,"PacketLength":null,"Channels":1,"SampleRate":11024,"IsDefault":false,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":0,"AspectRatio":null,"Index":1,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null}],"MediaAttachments":[],"Formats":[],"Bitrate":5157705,"Timestamp":null,"RequiredHttpHeaders":{},"TranscodingUrl":null,"TranscodingSubProtocol":null,"TranscodingContainer":null,"AnalyzeDurationMs":null,"DefaultAudioStreamIndex":null,"DefaultSubtitleStreamIndex":null}

/usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -init_hw_device cuda=cu:0 -filter_hw_device cu -autorotate 0 -i file:"/media/videos/2008/2008_06_15 f TANIEC PAWEL/MVI_9123.AVI" -map_metadata -1 -map_chapters -1 -threads 0 -vn -map 0:1 -map -0:s  -codec:a:0 libfdk_aac -ac 1 -ab 128000 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/config/transcodes/389a1fd82eff9cb28164a61a3d30a21e%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/config/transcodes/389a1fd82eff9cb28164a61a3d30a21e.m3u8"

ffmpeg version 5.1.2-Jellyfin Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-libs=-lfftw3f --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-static --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libsvtav1 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Guessed Channel Layout for Input Stream #0.1 : mono
Input #0, avi, from 'file:/media/videos/2008/2008_06_15 f TANIEC PAWEL/MVI_9123.AVI':
  Metadata:
    creation_time   : 2008-06-15 13:27:19
    software        : CanonMVI01
  Duration: 00:00:30.00, start: 0.000000, bitrate: 5157 kb/s
  Stream #0:0: Video: mjpeg (Baseline) (MJPG / 0x47504A4D), yuvj422p(pc, bt470bg/unknown/unknown), 640x480, 5083 kb/s, 10 fps, 10 tbr, 10 tbn
  Stream #0:1: Audio: pcm_u8 ([1][0][0][0] / 0x0001), 11024 Hz, mono, u8, 88 kb/s
Stream mapping:
  Stream #0:1 -> #0:0 (pcm_u8 (native) -> aac (libfdk_aac))
Press [q] to stop, [?] for help
[mpegts @ 0x561c7b092000] frame size not set
Output #0, hls, to '/config/transcodes/389a1fd82eff9cb28164a61a3d30a21e.m3u8':
  Metadata:
    encoder         : Lavf59.27.100
  Stream #0:0: Audio: aac, 11025 Hz, mono, s16, 128 kb/s
    Metadata:
      encoder         : Lavc59.37.100 libfdk_aac
size=N/A time=00:00:00.00 bitrate=N/A speed=   0x    
[hls @ 0x561c7b00b1c0] Opening '/config/transcodes/389a1fd82eff9cb28164a61a3d30a21e0.ts' for writing
[hls @ 0x561c7b00b1c0] Opening '/config/transcodes/389a1fd82eff9cb28164a61a3d30a21e1.ts' for writing
[hls @ 0x561c7b00b1c0] Opening '/config/transcodes/389a1fd82eff9cb28164a61a3d30a21e2.ts' for writing
[hls @ 0x561c7b00b1c0] Opening '/config/transcodes/389a1fd82eff9cb28164a61a3d30a21e3.ts' for writing
[hls @ 0x561c7b00b1c0] Opening '/config/transcodes/389a1fd82eff9cb28164a61a3d30a21e4.ts' for writing
[hls @ 0x561c7b00b1c0] Opening '/config/transcodes/389a1fd82eff9cb28164a61a3d30a21e5.ts' for writing
[hls @ 0x561c7b00b1c0] Opening '/config/transcodes/389a1fd82eff9cb28164a61a3d30a21e6.ts' for writing
[hls @ 0x561c7b00b1c0] Opening '/config/transcodes/389a1fd82eff9cb28164a61a3d30a21e7.ts' for writing
[hls @ 0x561c7b00b1c0] Opening '/config/transcodes/389a1fd82eff9cb28164a61a3d30a21e8.ts' for writing
[hls @ 0x561c7b00b1c0] Opening '/config/transcodes/389a1fd82eff9cb28164a61a3d30a21e9.ts' for writing
[hls @ 0x561c7b00b1c0] Opening '/config/transcodes/389a1fd82eff9cb28164a61a3d30a21e10.ts' for writing
size=N/A time=00:00:29.25 bitrate=N/A speed= 126x    
video:0kB audio:244kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown

**Stats for Nerds Screenshots**
![image](https://user-images.githubusercontent.com/19267082/231767080-de3a24d3-549c-4b56-8b8a-ad52e99dfccb.png)

**Server System (please complete the following information):**
 - OS: Docker on Linux
 - Jellyfin Version: 10.8.9
 - Hardware settings & device:  NVENC on rtx3050
 - Other hardware notes: Media mounted in SMB share
 
**Client System (please complete the following information):**
I can provide if necessary.

**Comment by pinovecs** [comment]
I have been using Jellyfin for about a year+ and I was never successful running AVI files.  I don't know if they were MJPEG format AVIs but a number of mine didn't work so I began converting them.

**Comment by mtekman** [comment]
Apologies for bumping, but I am getting the same problem with [FUJIFILM FinePix F20](https://en.wikipedia.org/wiki/Fujifilm_FinePix_F_series#F20) movies.

The audio plays fine, but the video is just a black screen. Interestingly, there are still good thumbnails for the video, so something in the JellyFin software stack can read the video.

Output of ffprobe:

```
Input #0, avi, from 'DSCF3013.AVI':
  Duration: 00:00:03.00, start: 0.000000, bitrate: 9376 kb/s
    Stream #0:0: Video: mjpeg (Baseline) (MJPG / 0x47504A4D), yuvj422p(pc, bt470bg/unknown/unknown), 640x480, 9307 kb/s, 30 fps, 30 tbr, 30 tbn, 30 tbc
    Metadata:
      Make            : FUJIFILM
      Model           : FinePix F20
      DateTime        : 2017:06:06 13:35:38
      JPEGInterchangeFormat:     506
      JPEGInterchangeFormatLength:    9160
      Copyright       :
      DateTimeOriginal: 2017:06:06 13:35:38
      DateTimeDigitized: 2017:06:06 13:35:38
      MakerNote       :
                      :  70,  85,  74,  73,  70,  73,  76,  77,  12,   0,   0,   0,  17,   0,   0,   0
                      :   7,   0,   4,   0,   0,   0,  48,  49,  51,  48,  16,   0,   2,   0,  43,   0
                      :   0,   0, 222,   0,   0,   0,   0,  16,   2,   0,   8,   0,   0,   0,  10,   1
                      :   0,   0,   1,  16,   3,   0,   1,   0,   0,   0,   3,   0,   0,   0,   2,  16
                      :   3,   0,   1,   0,   0,   0,   0,   0,   0,   0,  16,  16,   3,   0,   1,   0
                      :   0,   0,   2,   0,   0,   0,  17,  16,  10,   0,   1,   0,   0,   0,  18,   1
                      :   0,   0,  32,  16,   3,   0,   1,   0,   0,   0,   0,   0,   0,   0,  33,  16
                      :   3,   0,   1,   0,   0,   0,   0,   0,   0,   0,  48,  16,   3,   0,   1,   0
                      :   0,   0,   0,   0,   0,   0,  49,  16,   3,   0,   1,   0,   0,   0,   0,   0
                      :   0,   0,   0,  17,   3,   0,   1,   0,   0,   0,   0,   0,   0,   0,   0,  18
                      :   3,   0,   1,   0,   0,   0,   0,   0,   0,   0,   0,  19,   3,   0,   1,   0
                      :   0,   0,   0,   0,   0,   0,   1,  19,   3,   0,   1,   0,   0,   0,   0,   0
                      :   0,   0,   2,  19,   3,   0,   1,   0,   0,   0,   0,   0,   0,   0,   3,  19
                      :   3,   0,   1,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  70,  67
                      :  32,  70,  67,  84,  48,  48,  48,  50,  51,  32,  53,  57,  50,  68,  51,  49
                      :  51,  49,  51,  50,  51,  52,  48,  55,  48,  49,  50,  55,  56,  65,  57,  51
                      :  51,  48,  51,  48,  70,  66,  48,  67,   0,   0,  78,  79,  82,  77,  65,  76
                      :  32,   0,   0,   0,   0,   0, 100,   0,   0,   0
      title           : FUJIFILM AVI STREAM 0100
    Stream #0:1: Audio: pcm_u8 ([1][0][0][0] / 0x0001), 16000 Hz, 1 channels, u8, 128 kb/s
```

**Comment by wacko37** [comment]
bump! same issue on AVI file with MJPEG codec. Black screen with normal sound for a few seconds the video stops  with playback error.

Media info :

Image
Codec: MJPEG
Codec tag: MJPG
Profile: Baseline
Resolution: 640x480
Bitrate: 5074 kbps
Bit depth: 8 bit
Color space: bt470bg
Pixel format: yuvj422p
Ref frames: 1


Audio
Title: PCM_U8 - 1 ch
Codec: PCM_U8
Channels: 1 ch
Bitrate: 88 kbps
Sample rate: 11024 Hz
Bit depth: 8 bit
Default: No
Forced: No
External: No

**Comment by wacko37** [comment]
Log to help troubleshoot
[jellyfin.log](https://github.com/jellyfin/jellyfin/files/12272596/jellyfin.log)

**Comment by wacko37** [comment]
Had original posted this issue over at linuxserver - Jellyfin, so just updating that open issue to reflect the BUG status here
