### ISSUE TITLE
[Issue]: Ersatztv m3u / xmltv authentication issue

### ISSUE THREAD

**Issue by tuxx** [jellyfin/jellyfin#9644]
### Please describe your bug

When i try to add livetv to jellyfin (ersatztv) i get the following error in the jellyfin log:

Dashboard -> Live TV -> M3U Tuner -> URL: http://local.ip:8409/channels.m3u
(Also tried other useragents to no avail).

```
jellyfin    | [01:32:05] [INF] [74] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was forbidden.
```

I found a reddit post that suggested clearing the JELLYFIN_CONFIG/cache/*_channels folders.. but these did not exist. 

https://www.reddit.com/r/jellyfin/comments/vqsfi1/comment/iev9qtn/

The ersatztv m3u and xmltv urls don't use any authentication, so i'm guessing this is a jellyfin bug? If more info needs to be supplied please let me know.

### Jellyfin Version

Other

### if other:

10.8.9

### Environment

```markdown
- OS: Ubuntu 20.04.6 LTS
- Virtualization: Docker
- Clients: Browser
- Browser: Chromium
- FFmpeg Version: 5.1.2-Jellyfin
- Playback Method: None
- Hardware Acceleration: nvenc
- Plugins: none
- Reverse Proxy: Caddy
- Base URL: none
- Networking: Host
- Storage: local
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Traace** [comment]
I have the same issue with Jellyfin Version 10.8.9. Both M3U and HD Homerun Tuners are affeced. I can add nothing anymore...

Seems like this issue only occurs if an older jellyfin versions gets upgraded to 10.8.9. Because I ran a test with a freshy installed 10.8.9 and it works there.

With 10.8.9 there was a change regarding livetv auth. Maybe a regression? https://github.com/jellyfin/jellyfin/pull/9130

**Comment by tuxx** [comment]
Yep seems like the downgrade works for me too.

**Comment by SuperMario4889** [comment]
I have the same problem.

**Comment by ramboozer** [comment]
Same problem as well. I was able to add one then couldn't add a second. I tried removing the first one I add...and I keep getting the same message in error

Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was forbidden.

**Comment by ziogref** [comment]
Was unable to add M3U Live TV on Jellyfin 10.8.11
Downgraded to 10.8.8 and it just worked
