### ISSUE TITLE
[RFC] Allow cache_size to be set by Operator

### ISSUE THREAD

**Issue by Silvenga** [jellyfin/jellyfin#9646]
Recently, Plex exposed the `cache_size` SQLite option to users, and reportedly this has a significant increase in performance in some deployments.

Right now `Emby.Server.Implementations.Data.SqliteItemRepository.CacheSize` sets the cache size for the SQLite connection. This is currently hard coded to `20_000` pages (about 82MB, assuming a page is 4KiB).

It would be ideal if Jellyfin could also expose this option so that operators could play around with it and see if that helps performance. I would propose, rather than exposing it in the UI (at least for now), allow operators to configure this via an environment variable (e.g. `JELLYFIN_SQLITE_CACHE_SIZE_MB`). Over time, the Jellyfin can see if increasing the default would be useful (or even exposing it in the UI). Other future niceties could include dynamically calculating this value based on restrictions such as Docker memory limits (as already done by the runtime).

I would love to make a PR if this change is acceptable.

**Comment by Silvenga** [comment]
From my side, my instance of Jellyfin sees a good amount of read thrashing on the SQLite DB, which _appears_ to be a primary bottleneck. My hypnosis is that increasing the cache size will allow SQLite to keep more pages in memory, and reduce read IOPS.

**Comment by Silvenga** [comment]
> This sounds like it would be easily testable, yes?

I'm not sure what you mean there. The code changes to support setting this via an env var is easily tested, yeah. Testing Jelly under load is much harder (which is why I want to make this option settable by the operator and not hardcoded in Jelly).

I don't think we can safely change the default - since that could negatively impact users who manage Jelly on smaller servers (think Pi's). I personally have a massive media library and a K8s/Ceph cluster with a massive amount of RAM. For me, RAM is cheaper than disk IOPS or CPU.

> Is there a good script that can be used to stress test a jellyfin instance, for use in such testing?

I'm not sure there is a good one, there's just so much that could be happening. I'm personally trying to make Jelly usable with a large media collection. I can't use `inotify` on my cluster, since the filesystem is distributed across multiple nodes, `inotify` is handled by the kernel interface localized at each node. Instead I have to poll for changes, which has a significant impact on performance during the scan - due to the amount of reading from the DB involved.

Really, to test, I'm looking at my metrics and seeing if a change in this option reduces the amount of read/write IOPS - a test over the course of weeks. There's no guarantee that my test will even be valid given all the variables involved.

**Comment by satmandu** [comment]
> I'm not sure what you mean there. The code changes to support setting this via an env var is easily tested, yeah. Testing Jelly under load is much harder (which is why I want to make this option settable by the operator and not hardcoded in Jelly).

Could you hardcode an increase to the SQLite cache_size, rebuild jellyfin, and see if your performance improves? That would be one data point. 

If you see a performance increase, it might be worth submitting a PR.

**Comment by Silvenga** [comment]
I guess I'm thinking more long term - allow this to be a troubleshooting step that users can try when dealing with poor performance. Allow operators to play with this setting e.g. decrease the setting if they see a lot of RAM usage, increase if performance is bad.

I don't want my weird setup to be a datapoint - it's way more complex than most. What normal person has 1TB of RAM available to play with. 😹

Ultimately, I want to make a PR that allows operators to customize this value (myself included). Really, just another tool that the operator can try.

If this helps me, and helps others, maybe this is something that could be officially documented/supported (e.g. added to the UI like Plex did). But I don't think we're at that point yet - optimizing SQLite is a beast. 

I could be completely wrong about my problem - but that doesn't mean someone else with a similar symptoms will have the same problem, and this option could help them.
