### ISSUE TITLE
What other ways are there to manually refresh media information besides renaming directories or files?

### ISSUE THREAD

**Issue by soundlift** [jellyfin/jellyfin#9651]
The reason for this is that NasTools created hard links during directory synchronization before the file was fully copied, causing Jellyfin to read an incomplete file in real-time monitoring and unable to recognize media information.

Refreshing the media library or metadata does not work to reacquire media information. Even deleting media files and recreating hard links does not seem to work, and renaming directories or files is the only way to make Jellyfin recognize them again.

Are there any other solutions?

**Comment by harleyknd1** [comment]
if you have the .nfo option enabled, you can delete those files and wait for a re-sync, at least that's how I do it

**Comment by soundlift** [comment]
> if you have the .nfo option enabled, you can delete those files and wait for a re-sync, at least that's how I do it

Thanks for the reply, but it doesn't work

**Comment by soundlift** [comment]
correct，renaming doesn't work, only modifying the directory will trigger a re-recognition.

**Comment by soundlift** [comment]
"I found the issue. It's because I was using Samba to mount from TrueNAS Scale to Debian, which occasionally caused media files to not retrieve media information and required renaming. It wasn't a caching issue with Jellyfin. I've resolved it by switching to NFS sharing."
