### ISSUE TITLE
[Issue]: Subtitle stream title is not meaningful

### ISSUE THREAD

**Issue by ZzZombo** [jellyfin/jellyfin#9652]
### Please describe your bug

The subtitles do not have any meaningful title, and I believe it makes VLC not correctly load my preferred subtitles automatically.

### Jellyfin Version

10.8.9

### Environment

```markdown
- OS: Windows 10.
- Linux Kernel: N/A.
- Virtualization: none.
- Clients: VLC.
- Browser: N/A.
- FFmpeg Version: your custom.
- Playback Method: I believe `transcode`.
- Hardware Acceleration: NVENC.
- GPU Model: RTX 2060 Super.
- Plugins: ???
- Reverse Proxy: none.
- Base URL: none.
- Networking: ???
- Storage: local.
```

### Please attach any screenshots here

![image](https://user-images.githubusercontent.com/10889612/232475570-48dd427d-ca7c-497f-8b9e-37a60d6a1dd6.png)
![image](https://user-images.githubusercontent.com/10889612/232476913-2a55f133-7a79-4d10-9908-65bd9d20e4d8.png)
The highlighted line reads "Language: \<snip>".

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by harleyknd1** [comment]
Subs should be grabbed from the file where available, it looks to be more of an issue with the file itself, when you directly open it in vlc and check the subs, how is it listed there?
![image](https://user-images.githubusercontent.com/2973129/232632952-886f987a-0ae4-4fa7-89b8-4f2f144ec64b.png)

**Comment by ZzZombo** [comment]
See yourself:
![image](https://user-images.githubusercontent.com/10889612/232644233-9ecf597a-d35c-4976-a9f7-4e809af35d83.png)

The only correctly listed subtitles are the last, added manually.

**Comment by BrianCArnold** [comment]
If I'm understanding correctly, VLC is showing `Дорожка 1 - [2:8096\...]`, correct?

Do you have screenshot of a different application opening that file and showing the correct subtitle names?

**Comment by ZzZombo** [comment]
Sorry for missing the notification on this one. What do you mean "and showing the correct subtitle names"? Do you imply it's the fault of VLC? Besides, I have no other players to open movies through DLNA. Maybe you can suggest something slim for a quick test.

**Comment by ZzZombo** [comment]
I still wait for @BrianCArnold's reply to my question.
