### ISSUE TITLE
[Issue]: DS210+ without Docker?

### ISSUE THREAD

**Issue by UltronReal** [jellyfin/jellyfin#9668]
### Please describe your bug

>Hey, I'm currently using a Synology DS210+ for my storage needs. Unfortunately, this model doesn't come with Docker, which I need to install Jellyfin, my media server software of choice. I've been searching for ways to get around this limitation, but so far I haven't found a clear answer.

>I'm wondering if there's a workaround or a different approach I can take to get Jellyfin up and running on my DS210+. I'm open to suggestions and would appreciate any advice you can offer. 
Thanks!

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS:
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Bond-009** [comment]
See #293
