### ISSUE TITLE
[Issue]: HWA No Codec Supported

### ISSUE THREAD

**Issue by cooky807** [jellyfin/jellyfin#9683]
### Please describe your bug

I am running jellyfin on a VM hosted on an Unraid Server.
Right know I am trying to get Hardware acceleration set up and running, but there seems to be an Issue wit the supported codecs.
I have run through the following Guide: https://jellyfin.org/docs/general/administration/hardware-acceleration/intel/ 

OS: Ubuntu 22.04.2 LTS
Kernel: Linux 5.15.0-70-generic
CPU: Intel Pentium CPU G4620

All Jellyfin packages are installed and updated:
![grafik](https://user-images.githubusercontent.com/131691307/234043839-62e2511f-876f-4a81-85a2-86544f761c20.png)

The Graphics Card is passed through to the VM and recognized by Ubuntu. The output from `lshw -class display` shows:
![grafik](https://user-images.githubusercontent.com/131691307/234048518-76bff7a1-fd62-43ce-bb24-11421766c06a.png)
The Second card should be used (Intel HD-Grafik 630 from the CPU).

The renderD128 folder is available and the jellyfin user is in th video and render group. I tried already to set the rights of the folders to 777 for testing.
![grafik](https://user-images.githubusercontent.com/131691307/234045596-d30542ce-886e-4afe-a3dd-4c4427181157.png)

intel-opencl-icd ist installed in Version 22.14.22890-1

But by running the vainfo there seems to be no Codecs available `sudo /usr/lib/jellyfin-ffmpeg/vainfo --display drm --device /dev/dri/renderD128`
![grafik](https://user-images.githubusercontent.com/131691307/234046537-7a426c9a-6a46-45cb-98a2-e3daddd0723b.png)

Running the Code with the "normal" ffmpeg `sudo vainfo` gives the same output.

Trying to do a quick test with ffmpeg also returns a message of missing codecs:
`sudo ffmpeg -hwaccel vaapi -hwaccel_output_format vaapi -hwaccel_device /dev/dri/renderD128 -i ./temp/test.mp4 -c:v h264_vaapi ./temp/Testvideo-Intel.mkv`
...
`Stream mapping:

  Stream #0:0 -> #0:0 (h264 (native) -> h264 (h264_vaapi))

  Stream #0:1 -> #0:1 (aac (native) -> vorbis (libvorbis))

Press [q] to stop, [?] for help

[h264 @ 0x55e31424d880] No support for codec h264 profile 77.`
...

I have already tried to add some additional drivers:
intel-media-va-driver-non-free / intel-media-va-driver
i965-va-driver-shaders / i965-va-driver
But I think the required drivers are already in the jellyfin packages, anaway there was no difference in the output.

I don't really know if its related to this but I can't run the `intel_gpu_top` command, there is also an issue:
![grafik](https://user-images.githubusercontent.com/131691307/234050963-099f138f-faf4-4887-be59-b098226c3145.png)

Thank you for helping.
If any additional Infos are needed I will add them soon.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Ubuntu 22.04.2 LTS
- Linux Kernel: 5.15.0-70-generic
- Virtualization: KVM
- Hardware Acceleration: Not yet
- GPU Model: Intel HD-Grafik 630
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nyanmisaka** [comment]
@cooky807 You may need to seek help from the [drm/intel](https://gitlab.freedesktop.org/drm/intel/-/issues) and the Unraid community. I suspect the iGPU passthrough is not complete or kernel driver failed, causes user-mode drivers iHD/i965 to report zero supported codecs.

**Comment by cooky807** [comment]
There was a problem by passing through the iGPU, with some more tests I figuerd out that it was not completly possible.
Buying a second GPU and passthrough this one worked.
So no problem with Jellyfin.
