### ISSUE TITLE
[Issue]: TV Playback Failed since Version 10.8.10

### ISSUE THREAD

**Issue by Shadow27374** [jellyfin/jellyfin#9687]
### Please describe your bug

Since version 10.8.10 almost all TV channels do not work anymore.
Back to version 10.8.9 and it works again as expected.

The clients still have 10.8.10.

### Jellyfin Version

10.8.z

### if other:

Clients are Windows 10

### Environment

```markdown
- OS: Ubuntu Server 22.04.2 LTS 
- Linux Kernel: 5.19.0-40-generic #41~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 31 16:00:14 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
- Virtualization: Docker
- Clients: Windows 10
- Browser: Chrome
- FFmpeg Version: Dockerimage
- Playback Method: Client (Windows 10)
- Hardware Acceleration: QuickSync
- GPU Model: Intel UHD Graphics (Jasper Lake 32 EU) (450 - 900 MHz)
- Plugins: none
- Reverse Proxy: traefik
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by killertrust** [comment]
same problem here before the update it was working

![image](https://user-images.githubusercontent.com/71734496/234345586-5fda757b-5072-4b96-a245-77c87f56fc80.png)

**Comment by mooninite** [comment]
I'm seeing the following error in my transcoder log:

<pre>[hevc_vaapi @ 0x55f9df14ccc0] Access unit too large: 8192 < 20880.
[hevc_vaapi @ 0x55f9df14ccc0] Failed to write extra header 0: -28.
[hevc_vaapi @ 0x55f9df14ccc0] Encode failed: -28.
[vost#0:0/hevc_vaapi @ 0x55f9df14c800] Error submitting video frame to the encoder</pre>

System:
* Fedora 38 x86_64
* Jellyfin 10.8.10
* FFMPEG 6.0 (upstream, not ffmpeg-jellyfin)
* HDHomeRun 4k (playing MPEG2 ATSC 1.0 streams)

Downgrading to FFMPEG 5.1.3 (upstream) restores LiveTV playback.

**Comment by Shadow27374** [comment]
Then this is probably only due to FFMPEG which is already included in the Docker container. At least if you use Docker like me.

**Comment by Killface1980** [comment]
I've also downgraded my docker. 
Latest version ignored the fMP4 remux option completely, _everything_ was transcoded as either the container or the video codec weren't supported. This applied to live tv and every other media. Even hls segmenter from EratzTV was not compatible.
I think I'll skip the current version.

**Comment by mooninite** [comment]
The issue has not yet been addressed. (commenting to keep it open)

**Comment by killertrust** [comment]
trying different things no one work for me, the last thing I'm trying is building in a vm a new install and it work now try to clean my server install and how to migrate all the configurations

**Comment by Killface1980** [comment]
Same issue here. What I've noticed is that my JMP at home works as intended, while using JMP at work leads to the same behaviour for Live TV as described above. No idea where the difference lies, both machines with Windows 11 and intel/Nvidia combo. 
At work, I have a dual monitor setup, the only obvious difference I can think of.

**Comment by mooninite** [comment]
Still an issue with 10.8.11. Same error. I started to investigate the issue.

* Only affects 1080i channels. 720p channels do not error.
* No difference if you use low power encoder mode.
* The encode *sometimes* works. Due to the nature of OTA the stream can sometimes get "good" video data quickly (within a few frames) or sometimes it takes up to 2-3 seconds to get "good" data. I noticed if the stream starts quickly the 1080i channels work. If it takes longer than a second the stream fails.
* Increasing analyzeduration does not help, increasing buffer sizes do not help.

I have saved OTA TS files of both "bad" and "good" stream data from the same channel if anyone wants to debug it.

I am guessing FFMPEG 6 is less tolerant of bad data sent through the VA-API pipeline. The software rendering (libx264) pipeline handles the data without an error. I have a feeling this should be reported against FFMPEG as a possible bug.

**Comment by nyanmisaka** [comment]
https://github.com/FFmpeg/FFmpeg/commit/f5f1c1fd6bf892d0aaf7b2ea0c01857ca321319e
This commit introdueced in upstream 6.0+ seems to be the suspicious one.

Live TV video streams may contain ASTC A53 CC subtitles in SEI data, but the encoder complains about it. Try manually running the ffmpeg command line you got from the log file and disabling the extra SEI data by appending `-sei 0` after the `-c:v h264_vaapi` or `-c:v hevc_vaapi`.

@mooninite Let me know if it works.

**Comment by mooninite** [comment]
@nyanmisaka , that option does get the "bad" TS data to encode. Thanks. The "good" data also encodes with "-sei 0" set. Should be harmless to include as a standard flag?

**Comment by nyanmisaka** [comment]
@mooninite Try this one `-sei -a53_cc`, the 2nd `-` should clear the default a53 cc flag, which equals to `&= ~SEI_A53_CC`.

**Comment by mooninite** [comment]
@nyanmisaka the `-sei -a53_cc` option works, too.

**Comment by nyanmisaka** [comment]
@mooninite We may not have a 10.8.12 version in the future, so you will need to add this patch manually. https://github.com/jellyfin/jellyfin/pull/10275

Or temporarily use jellyfin-ffmpeg5 instead.

**Comment by mooninite** [comment]
Thanks, @nyanmisaka . Fedora will carry the patch in the mean time.

https://koji.rpmfusion.org/koji/buildinfo?buildID=26861
