### ISSUE TITLE
Audio crossfading between tracks

### ISSUE THREAD

**Issue by onny** [jellyfin/jellyfin#969]
Hey,

**Describe the feature you'd like**

it would be really cool to have a audio crossfading option so that tracks in a queue are mixed between the ending and the starting of the next song.

**Additional context**

Maybe an additional switch is required to enable/disable crossfading and an additional playback option to set crossfading time in seconds.

Best regards,
Jonas

**Comment by dkanada** [comment]
This would probably be a client option rather than a server one, is there a specific client you would like to see implement this feature?

**Comment by onny** [comment]
Jellyfin-web and Jellyfin-Android

**Comment by onny** [comment]
Created issue for jellyfin-web https://github.com/jellyfin/jellyfin-web/issues/151 and jellyfin-android https://github.com/jellyfin/jellyfin-android/issues/93 :+1: Thanks!
