### ISSUE TITLE
[Issue]: Jellyfin does not unsubscribe from Live TV streams

### ISSUE THREAD

**Issue by TippyLion28** [jellyfin/jellyfin#9690]
### Please describe your bug

I am trying to connect Jellyfin to my M3U/XML TV server. It mostly works but Jellyfin does not seem to unsubscribe from the HTTP stream when the content is closed. The TV server then thinks someone is still watching and it's impossible to switch to any other channel as it is not possible for the tuner to connect to multiple channels at the same time.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Windows 10
- Linux Kernel: none
- Virtualization: none
- Clients: Browser, Android
- Browser: Firefox
- FFmpeg Version: Unsure
- Playback Method: Transcode
- Hardware Acceleration: NVENC
- GPU Model: GTX1050Ti
- Plugins: none
- Reverse Proxy: no
- Base URL: no
- Networking: host
- Storage: n/a
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TippyLion28** [comment]
Still an issue for me

**Comment by JPVenson** [comment]
stap it bot

**Comment by mcrerick** [comment]
check this #10982  an this #12241 i think its the same issue, a critical issue that needs to be fixed. anybody could crash the server opening channels.
