### ISSUE TITLE
[Issue]: REST API: /Items Bad Request

### ISSUE THREAD

**Issue by endrl** [jellyfin/jellyfin#9708]
### Please describe your bug

According to openapi docs this should be possible: `GET http://localhost:8096/Items?api_key=KEY`.

- It passes the apiKey check [ItemsController.cs](https://github.com/jellyfin/jellyfin/blob/master/Jellyfin.Api/Controllers/ItemsController.cs#L249)
- User is null at this point [ItemsController.cs](https://github.com/jellyfin/jellyfin/blob/master/Jellyfin.Api/Controllers/ItemsController.cs#L510)
- Throws at [Folder.cs](https://github.com/jellyfin/jellyfin/blob/master/MediaBrowser.Controller/Entities/Folder.cs#L1273)

Thank you for feedback

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Windows 10
- Linux Kernel: -
- Virtualization: -
- Clients: -
- Browser: -
- FFmpeg Version: -
- Playback Method: -
- Hardware Acceleration: -
- GPU Model: -
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nielsvanvelzen** [comment]
The user id is required in 10.8.z. In 10.9 it can infer the id based on authentication headers.

**Comment by endrl** [comment]
Oh, i'm sorry. I use master, not 10.8. The links/docs are from master. Pending PR?

**Comment by nielsvanvelzen** [comment]
Hmm I guess because an api key doesn't have a user id not everything works in this specific endpoint.
