### ISSUE TITLE
Jellyfin only gets 15 first actors with local metadata activated

### ISSUE THREAD

**Issue by deltonio2** [jellyfin/jellyfin#9709]
### Please describe your bug

I only see the first 15 actors listed on TMDB on the movie page on Jellyfin.
I defined the metadata to be stored locally, in the NFO file created by Jellyfin, there are only the first 15 actors.
If I manually add a 16th actor in the NFO file, it displays correctly on the movie page on Jellyfin.

Step to reproduce :

- define the metadata to be stored locally ;
- add a movie with more that 15 actors referenced on TMDB.

### Jellyfin Version

10.8.z

### if other:

10.8.10

### Environment

```markdown
- OS: Debian 11
- Linux Kernel:  6.0.0-0.deb11.2-amd64
- Virtualization: N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
This is configurable in the TMDb plug-in settings.
