### ISSUE TITLE
Add cohabitation between Jellyfin and Jellyseerr.

### ISSUE THREAD

**Issue by laborantine** [jellyfin/jellyfin#9717]
(Sorry for my english, i'm french) 

Hello, i don't know if it's possible to make Jellyseerr cohabit in Jellyfin. Let me explain :

Today, I have two subdomains, one for Jellyseerr and the other for Jellyfin. What would be appreciable would be to retain only one interface with the two services.

If it's too complicated, would it be possible to personalize a message during a search. For example, when a user searches for a movie not found in my database, a message that can be personalized is written, such as "Sorry, no movie matches your search. However, you can send a request to [*link redirecting to Jellyseerr*](url)."

PS : I'm impressed with the work you provide, thank you very much and keep it up!

**Comment by cantcurecancer** [comment]
I am interested in this as well. I would like to be able to just click a button when content isn't available and it take them to a jellyseerr interface to make the request.

**Comment by ntallfellow** [comment]
It sounds like this is something that would be easily doable in Jellyfin on your own. You would have to dive in to the Jellyfin config file (which I have heard is easy to modify) and modify the search return when nothing is returned. Add a http link to jellyseer with your search appended to it. If you are using a Jellyfin with no password (and are using Jellyseer with that acct) then it will bring you direct to the search.

Chat GPT is your friend in this scenario.

**Comment by Manbearpig92** [comment]
you can do that already with enhanced jellyfin. but finding new content is the problem. it would be better if you could directly add jellyseerr discover to jellyfin so you can browse and request directly from jellyfin
