### ISSUE TITLE
[Issue]: Non-admin user can delete media files

### ISSUE THREAD

**Issue by SuperDumbTM** [jellyfin/jellyfin#9732]
### Please describe your bug

Delete media option is available to non-admin users and able to delete a media or an episode.

A non-admin user (`Allow this user to manage the server` option is not checked) should not be able to delete any file.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Ubuntu
- Linux Kernel: 6.2.6-1-pve
- Virtualization: Docker
- Clients: Broswer
- Browser: Firefox 112
- FFmpeg Version: N/A
- Playback Method: N/A
- Hardware Acceleration: N/A
- GPU Model: N/A
- Plugins: N/A
- Reverse Proxy: N/A
- Base URL: N/A
- Networking: N/A
- Storage: N/A
```

### Please attach any screenshots here

![圖片](https://user-images.githubusercontent.com/71750702/236485933-ce4d573c-51b2-41a5-aed8-97075f4e2566.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
Does the delete media button work? Or is it just an item in the list?

**Comment by SuperDumbTM** [comment]
> Does the delete media button work? Or is it just an item in the list?

Yes, it works

**Comment by nielsvanvelzen** [comment]
The "manage server" option is not used when validating if a user may delete media. There are separate options for that in the "Allow media deletion from:" section when modifying a user.

**Comment by SuperDumbTM** [comment]
> The "manage server" option is not used when validating if a user may delete media. There are separate options for that in the "Allow media deletion from:" section when modifying a user.

Oh, I just realise that. Unchecking that option resolved the issue, thanks for the clarification.
