### ISSUE TITLE
[Issue]: Google Safe Browsing is flagging and blocking Jellyfin Servers due to login prompt on homepage.

### ISSUE THREAD

**Issue by fange26** [jellyfin/jellyfin#9734]
### Please describe your bug

Google checks for input fields on homepage and flags pages as a deceptive site. To resolve this issue Google Support recommended creating  a landing page that links to the login page. 

EDIT: the flag also stops the android app from working. Users will be greeted with Connection cannot be established ERROR.

### Jellyfin Version

10.8.9

### Environment

```markdown
- OS:Windows Server 2019
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:Chrome, Firefox, Opera
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Please attach any screenshots here

![deceptive site page](https://user-images.githubusercontent.com/33208153/236635791-61af3c91-d751-430e-9163-7e2dc682fa73.png)

![google](https://user-images.githubusercontent.com/33208153/236635915-71ee3e7e-a6e3-475c-a670-f67f618a18bd.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nielsvanvelzen** [comment]
duplicate https://github.com/jellyfin/jellyfin-web/issues/4076
