### ISSUE TITLE
[Issue]: Can't install the jellyscurb plugin

### ISSUE THREAD

**Issue by UriSheinman** [jellyfin/jellyfin#9735]
### Please describe your bug

I've been trying to install the jellyscurb plugin on my server but I can't get it to work. I've tried via a repo but it gives an error (log screenshot attached) and I've tries manually copying the dll to a plugins folder in programdata but it won't show up.
Please help

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Windows 10
- Linux Kernel: N/A
- Virtualization: N/A
- Clients: android via findroid
- Browser: Chromium Edge
- FFmpeg Version: idk
- Playback Method: Direct Stream
- Hardware Acceleration: idk
- GPU Model:N/A
- Plugins: trying to install Jellyscrub
- Reverse Proxy: N/A
- Base URL: none
- Networking: idk
- Storage: local
```

### Jellyfin logs

```shell
Jellyfin.Server.Middleware. ExceptionMiddleware:

Error processing request. URL "POST"

"/Packages/Installed/Jellyscrub".

System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (github.com:443)
```

### Please attach any screenshots here

![Screenshot_20230506-224351](https://user-images.githubusercontent.com/132785427/236645860-fc1acac0-c40f-4e1c-8edd-7f2803c6e033.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
Looks like your server can’t access GitHub. This is not a Jellyfin issue.
