### ISSUE TITLE
[Issue]: Unable to show files without metadata

### ISSUE THREAD

**Issue by deadpahn** [jellyfin/jellyfin#9736]
### Please describe your bug

I've been spending a lot of time trying to get a folder to map properly. At this point I want to give up on it but Jellyfin forces the incorrect labeling it thinks is correct. The only work around for this would be to see the files as they are on the file system. My page right now has 20 folders named "Season" with no way to tell which order they are in.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS:
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sevenrats** [comment]
jellyfin does not support folder view. you may open a feature request at features.jellyfin.org
