### ISSUE TITLE
[Issue]: QSV can not been open

### ISSUE THREAD

**Issue by pureGavin** [jellyfin/jellyfin#9742]
### Please describe your bug

my cpu is I3-4130, the problem is i can not use QSV. Does 4th intel CPU to old for QSV?

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS:Ubuntu 22.04.1
- Linux Kernel: 5.15 i guess
- Virtualization: docker latest
- Clients: only test on the latest version of firefox
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration: QSV doesn't work, but VAAPI worded
- GPU Model:none
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Bond-009** [comment]
That CPU is unsupported by Intel Media Driver
https://jellyfin.org/docs/general/administration/hardware-acceleration/intel/#acceleration-methods
https://github.com/intel/media-driver#supported-platforms
