### ISSUE TITLE
Problem with BDMV catalog and PGSSUB

### ISSUE THREAD

**Issue by Ilia1** [jellyfin/jellyfin#9756]
Hardware decoding is enabled.
When I try to play a video without subtitles it's OK. If I turn on subtitles, only the audio remains. Instead of video there is a black screen.
But if I copy an m2ts file separately from the bdmv directory, it plays correctly with subtitles.

**Logs**
This is in the logs when playing the bdmv directory
`Error initializing output stream 0:1 -- Subtitle encoding currently only possible from text to text or bitmap to bitmap`

**Server System (please complete the following information):**
 - OS: void linux
 - Jellyfin Version: 10.8.10
 - Hardware settings & device: VAAPI on AMD
 
**Client System (please complete the following information):**
 - Device: web and android tested
 - OS: Android, Linux
 - Client: web and android tested
 - Browser (if Web client): Firefox

**Comment by Shadowghost** [comment]
Likely fixed by #9254 if not feel free to reopen.
