### ISSUE TITLE
Jellyfin Not Seeing Entire Episode Catalog of TV Seasons

### ISSUE THREAD

**Issue by thejaceman** [jellyfin/jellyfin#9757]
### Please describe your bug
Supposedly, this behavior was also found in issues: #7855, #7945, and #8023 

Jellyfin cannot see all episodes of TV shows, in spite of the fact that all files are named correctly with a naming convention that makes telling them apart easy. And if it does detect multiple episodes, it is refusing to fetch individual metadata for each episode in spite of library scans and manual metadata refresh requests.

### Jellyfin Version
10.8.9

if other:
No response

### Environment
- OS: Windows 11 x64
- Virtualization: None 
- Clients: Web\Android\Roku
- Browser: Edge\Chrome
- FFmpeg Version: latest included

### Jellyfin logs
No response

### FFmpeg logs
No response

### Please attach any browser or client logs here
No response

### Please attach any screenshots here
![05122023 01](https://github.com/jellyfin/jellyfin/assets/26730141/74a2f562-7a45-4a36-abe2-7761288f2576)
![05122023 02](https://github.com/jellyfin/jellyfin/assets/26730141/c6c7f36a-b979-45ff-96ce-efcc4504ab99)
![05122023 03](https://github.com/jellyfin/jellyfin/assets/26730141/3a8b70e2-58b9-46bd-bfaa-4c22c166fa35)
![05122023 04](https://github.com/jellyfin/jellyfin/assets/26730141/0dc8ee27-596c-4e87-9c2f-661248fe818e)

### Code of Conduct
 I agree to follow this project's Code of Conduct

**Comment by thejaceman** [comment]
Tried removing the metadata folders and hoped that would work. It didn't help. Ultimately, I wound up remuxing the mp4 files to mkv and deleted the original ones. It worked to make sure the media was correctly picked up and identified, but that's a pretty painful workaround.

**Comment by Gloryandel** [comment]
Season 3->Season 03?

**Comment by sevenrats** [comment]
i would recommend removing the hyphens from your filenames
