### ISSUE TITLE
Unable to play a strm file with mkv link

### ISSUE THREAD

**Issue by aurelien-logiciels-bernard** [jellyfin/jellyfin#9783]
Hello, on my Synology server, I have created a directory containing *.strm files that each point to http streams of movies. 
VLC plays these files very well without any problems.
By creating a dedicated library in Jellyfin, the files are well analyzed but impossible to play. I tried with Web, Windows, AndroidTV clients, the result is always the same.
I attach a log at the end of the message.

Is there a setting missing in Jellyfin?
What can I do?
[FFmpeg.Transcode-2023-05-17_11-59-14_7fd97480edb9a4f0338be8e152156dff_8f827f7a.log](https://github.com/jellyfin/jellyfin/files/11496924/FFmpeg.Transcode-2023-05-17_11-59-14_7fd97480edb9a4f0338be8e152156dff_8f827f7a.log)

**Comment by aurelien-logiciels-bernard** [comment]
I tried to install a more recent version of the ffmpeg package. On Synology, I found version 6. In Jellyfin, I changed the path of FFmpeg to /var/packages/ffmpeg6/target/bin/ffmpeg6.
Not better...

**Comment by sevenrats** [comment]
Please share the information necessary to replicate this bug, including an example link.

**Comment by sevenrats** [comment]
Can't reproduce this bug. Strm libraries are working as intended other than known bugs.
