### ISSUE TITLE
[Issue]: Metadata Import from nfo files fail in 10.8.10 (and below in *all* 10.8.x)

### ISSUE THREAD

**Issue by k1llerk3ks** [jellyfin/jellyfin#9790]
### Please describe your bug

Adding Release-date metadata from nfo files still fails in latest version 10.8.10. 

1. Run a jellyfin server and have it create an album.nfo file with releasedate (Day, Month and Year). Copy the folder with the information into another jellyfin instance, import it to your library.
2. You will see, that the releasedate is now changed to 01.01.YYYY. Manually editing this tag after importing does not work either.

This bug persists in whole 10.8.x, only in 10.7.x correct importing works.

See this video demonstration of the bug:

https://www.youtube.com/watch?v=6zj9QQz-MZM

Very much hoping for a quick fix, i can't use a current jellyfin version for this purpose...
Happy to help with anything that leads to the fix of this bug! I'm just not a C# Developer...

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Manjaro Linux / Docker
- Linux Kernel:6.x
- Virtualization: Docker
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shadowghost** [comment]
Can you please provide an example NFO or entry so we can check against that?

**Comment by k1llerk3ks** [comment]
just an example album.nfo, with mp3 files in the same folder. Thank you so much for your answer!

```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<album>
  <review></review>
  <outline></outline>
  <lockdata>true</lockdata>
  <lockedfields>Overview</lockedfields>
  <dateadded>2020-08-11 16:54:05</dateadded>
  <title>Detailed Description</title>
  <year>2020</year>
  <premiered>2020-07-01</premiered>
  <releasedate>2020-07-01</releasedate>
  <runtime>33</runtime>
  <art>
    <poster>/data/media/Psychedelic/Producer/Krapul - Detailed Description (2020)/cover.jpg</poster>
  </art>
  <artist>Krapul</artist>
  <albumartist>Funky Freaks Records</albumartist>
  <albumartist>Krapul</albumartist>
  <track>
    <position>1</position>
    <title>Ceremonial Theurgy (150)</title>
    <duration>08:00</duration>
  </track>
  <track>
    <position>2</position>
    <title>Dusk Light (150)</title>
    <duration>07:15</duration>
  </track>
  <track>
    <position>3</position>
    <title>Detailed Description (150)</title>
    <duration>08:42</duration>
  </track>
  <track>
    <position>4</position>
    <title>Epiphyte (150)</title>
    <duration>08:48</duration>
  </track>
</album>
```
