### ISSUE TITLE
[Issue]: Loading thumbnails for a photo library crashes due to out of memory. Possible memory leak?

### ISSUE THREAD

**Issue by CozzyBro2** [jellyfin/jellyfin#9795]
### Please describe your bug

Steps to reproduce:
1. Create an image library with any high amount of images.
2. Wait for jellyfin to finish scanning it.
3. Enter the library, observe your cpu and memory usage spike a little.
4. Scroll rapidly, or even at a mild pace, all the way down. (Even worse if you have pagination disabled)

Problem:
Cpu and memory spike to insane amounts and you will probably run out of memory and the OOMK will activate.
Note: I've tried this without swap memory at first, the crash just occurs a lot earlier. With 7gb of swap it will max that out too and crash.

Use Case:
My exact use case is an Image library with most of my phone's images. There are folders for each Phone i've ever owned. Both of the phone folders have more than 2000 images a piece. 

Once I enter a folder with more than a few hundred images, the problem gets out of hand. I presume the problem here is the process for generating thumbnails not having any limitations, and trying to generate thumbnails for thousands of images concurrently. 

Side note: Caching these thumbnails would probably fix the issue. Maybe generate and cache them during the initial scan?

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Debian 11 Bullseye (RPI OS Server)
- Linux Kernel: aarch64 Linux 6.1.21-v8+
- Virtualization: Docker
- Clients / Browser: Observable on any client
- FFmpeg Version: ffmpeg-jellyfin, Installed through docker image of jellyfin 10.8.10
- Playback Method: N/A
- Hardware Acceleration: VA-API, occurs regardless of HW accel setting
- GPU Model: Pi 400 Gpu
- Reverse Proxy: NGINX Proxy Manager, occurs when connecting locally too
- Storage: External SSD, occurs on internal SD card too
```

### Please attach any screenshots here

![image](https://github.com/jellyfin/jellyfin/assets/76234965/ce2042af-aad1-4194-b538-79f8a30b8274)
Sorry for the bad screenshot.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by moonsn** [comment]
I have the same problem on 10.8.10. After adding a new library with 1000+(33G) photos, the instance will crash when viewing the content of the library. 

adding more memory to the instance will delay the crash, but can't fix it.
