### ISSUE TITLE
[Issue]: How to use Apple Video Toolbox on Jellyfin installed via Docker?

### ISSUE THREAD

**Issue by nothing2obvi** [jellyfin/jellyfin#9796]
### Please describe your bug

I would like to use Apple Video Toolbox with Jellyfin 10.8.10 installed via Docker. Is this possible? Or do I need to use the MacOS version of Jellyfin in order for this to work?

Thank you very much for your input.

### Jellyfin Version

10.8.z

### if other:

10.8.10

### Environment

```markdown
- OS: Mac OS Ventura 13.2.1
- Virtualization: Docker 4.19.0
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by srcrist** [comment]
Closing this issue as it does not contain an actual Jellyfin bug. Please see our support communities on the forums or the Matrix/Discord server for assistance with configuration and use.
