### ISSUE TITLE
Vaapi transcode not working on Ubuntu 22.04

### ISSUE THREAD

**Issue by Skorrr** [jellyfin/jellyfin#9797]
I've been living with Jellyfin without hardware transcode but I'd like to have it working on all my devices without having to rely on mpv all the time.

Here is my server config, this is an old pc that I had lying around, now setup headless:
Ati Radeon HD 5450
Intel Celeron 450
Ubuntu 22.04
Jellyfin 10.8.10

Media in question is H264, can play fine on most devices but not on some and not at lower resolution.

Here is FFmpeg logs using VAAPI:

/usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -ss 00:13:30.000 -init_hw_device vaapi=va:/dev/dri/renderD128 -filter_hw_device va -hwaccel vaapi -hwaccel_output_format vaapi -autorotate 0 -i file:"/media/hdd/Media/Film/South Park Bigger Longer & Uncut (1999).mkv" -autoscale 0 -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -codec:v:0 h264_vaapi -rc_mode VBR -b:v 3526211 -maxrate 3526211 -bufsize 7052422 -profile:v:0 high -force_key_frames:0 "expr:gte(t,810+n_forced*3)" -vf "setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale_vaapi=format=nv12:extra_hw_frames=24,hwmap,format=nv12,subtitles=f='/media/hdd/Media/Film/South Park Bigger Longer & Uncut (1999).mkv':si=0:fontsdir='/var/cache/jellyfin/attachments/baae6290216c3a1f7016d8c409c7bc8d',hwmap,format=vaapi" -start_at_zero -codec:a:0 copy -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 270 -hls_segment_filename "/var/lib/jellyfin/transcodes/fbc38f454186b603a840ec1a3440c494%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/var/lib/jellyfin/transcodes/fbc38f454186b603a840ec1a3440c494.m3u8"

ffmpeg version 5.1.3-Jellyfin Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.3.0-1ubuntu1~22.04)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-libs=-lfftw3f --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libsvtav1 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, matroska,webm, from 'file:/media/hdd/Media/Film/South Park Bigger Longer & Uncut (1999).mkv':
  Metadata:
    title           : South Park : Bigger Longer & Uncut (1999)
    encoder         : libebml v1.3.1 + libmatroska v1.4.2
    creation_time   : 2015-04-29T22:34:30.000000Z
  Duration: 01:21:18.94, start: 0.000000, bitrate: 3526 kb/s
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 1920x1072, SAR 1:1 DAR 120:67, 23.98 fps, 23.98 tbr, 1k tbn (default)
    Metadata:
      _STATISTICS_WRITING_APP: mkvmerge v7.8.0 ('River Man') 64bit built on Mar 27 2015 16:31:37
      _STATISTICS_WRITING_APP-eng: mkvmerge v7.8.0 ('River Man') 64bit built on Mar 27 2015 16:31:37
      _STATISTICS_WRITING_DATE_UTC: 2015-04-29 22:34:30
      _STATISTICS_WRITING_DATE_UTC-eng: 2015-04-29 22:34:30
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      BPS             : 2245182
      BPS-eng         : 2245182
      DURATION        : 01:21:15.496000000
      DURATION-eng    : 01:21:15.496000000
      NUMBER_OF_FRAMES: 116895
      NUMBER_OF_FRAMES-eng: 116895
      NUMBER_OF_BYTES : 1368297168
      NUMBER_OF_BYTES-eng: 1368297168
  Stream #0:1(fre): Audio: ac3, 48000 Hz, 5.1(side), fltp, 384 kb/s (default) (forced)
    Metadata:
      title           : VFF AC3 5.1 @384 kbps
      _STATISTICS_WRITING_APP: mkvmerge v7.8.0 ('River Man') 64bit built on Mar 27 2015 16:31:37
      _STATISTICS_WRITING_APP-eng: mkvmerge v7.8.0 ('River Man') 64bit built on Mar 27 2015 16:31:37
      _STATISTICS_WRITING_DATE_UTC: 2015-04-29 22:34:30
      _STATISTICS_WRITING_DATE_UTC-eng: 2015-04-29 22:34:30
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      BPS             : 384000
      BPS-eng         : 384000
      DURATION        : 01:21:18.944000000
      DURATION-eng    : 01:21:18.944000000
      NUMBER_OF_FRAMES: 152467
      NUMBER_OF_FRAMES-eng: 152467
      NUMBER_OF_BYTES : 234189312
      NUMBER_OF_BYTES-eng: 23418931
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (h264_vaapi))
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
[Parsed_subtitles_4 @ 0x5645d20c5900] libass API version: 0x1502000
[Parsed_subtitles_4 @ 0x5645d20c5900] libass source: tarball: 0.15.2
[Parsed_subtitles_4 @ 0x5645d20c5900] Shaper: FriBidi 1.0.8 (SIMPLE) HarfBuzz-ng 2.7.4 (COMPLEX)
[Parsed_subtitles_4 @ 0x5645d20c5900] Using font provider fontconfig
[Parsed_subtitles_4 @ 0x5645d20c5900] Track has custom format line(s). 'ScaledBorderAndShadow' will default to 'yes'.]([url](url))

______________________

> /usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -ss 00:13:30.000 -init_hw_device vaapi=va:/dev/dri/renderD128 -filter_hw_device va -hwaccel vaapi -hwaccel_output_format vaapi -autorotate 0 -i file:"/media/hdd/Media/Film/South Park Bigger Longer & Uncut (1999).mkv" -autoscale 0 -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -codec:v:0 h264_vaapi -rc_mode VBR -b:v 3526211 -maxrate 3526211 -bufsize 7052422 -profile:v:0 high -force_key_frames:0 "expr:gte(t,810+n_forced*3)" -vf "setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale_vaapi=format=nv12:extra_hw_frames=24,hwmap,format=nv12,subtitles=f='/media/hdd/Media/Film/South Park Bigger Longer & Uncut (1999).mkv':si=0:fontsdir='/var/cache/jellyfin/attachments/baae6290216c3a1f7016d8c409c7bc8d',hwmap,format=vaapi" -start_at_zero -codec:a:0 copy -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 270 -hls_segment_filename "/var/lib/jellyfin/transcodes/fbc38f454186b603a840ec1a3440c494%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/var/lib/jellyfin/transcodes/fbc38f454186b603a840ec1a3440c494.m3u8"

Entering the command in cli I get this:

[h264_vaapi @ 0x55940ecca640] No usable encoding entrypoint found for profile VAProfileH264High (7).
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!

_______________________

with `vainfo` I get this:

error: can't connect to X server!
libva info: VA-API version 1.14.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/r600_drv_video.so
libva info: Found init function __vaDriverInit_1_14
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.14 (libva 2.12.0)
vainfo: Driver version: Mesa Gallium driver 22.2.5 for AMD CEDAR (DRM 2.50.0 / 5.19.0-41-generic, LLVM 15.0.6)
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointVLD
      VAProfileNone                   : VAEntrypointVideoProc

**Comment by nyanmisaka** [comment]
Your GPU `AMD CEDAR` has no video encoding support.

**Comment by Skorrr** [comment]
It has Unified Video Decoder 2.3 which should be able to decode/encode VC1 as well as H264
See "Cedar" at UVD 2.3 https://en.wikipedia.org/wiki/Unified_Video_Decoder
