### ISSUE TITLE
Add `uid` Field to user model

### ISSUE THREAD

**Issue by sdimovv** [jellyfin/jellyfin#9805]
I would like to add a new field called `uid` (name can be changed if needed). 

The type of the field would be `Guid` and it will be used to uniquely identity a user. 

My use case is the following: https://github.com/jellyfin/jellyfin-plugin-ldapauth/issues/146

# TL;DR
Currently the LDAP plugin uses the `LDAP username attribute` to both uniquely identify a user and as a display name. However, usernames and emails change. Thus, if an LDAP authenticated user changes the value of what was set as the username attribute in the plugin, they will be considered a completely different user. This may also lead to user impersonation if another user then changes their username attribute to the previously used one by the other user. 

However, setting the plugin username attribute to someting unique and immutable is not a good solution, because this attribute is also used as display name, leading to rather ugly display names being shown in the UI. 

Adding the `uid` attribute will allow the LDAP plugin to make a clear distinction between what is used to uniquely identify users and what is used as a display name. 

# Proposed implementation
For existing users this field could be set to a randomly generated Guid, while for creating new users there could be a choice to either provide a Guid to be set or get assigned a random one automatically.

# Questions
I am willing to have a go at implementing this, but I am not a C# developer (I'm familiar with Django and Python). Thus, I have a few questions:

- Can someone please outline the steps needed to create a new migration which adds the new field to the user model?
- Apart from adding the new field, setting it's value to a random Guid for existing users in the migration, and implementing 2 new methods in the `UserManager.cs` (find user by uid and create user with uid) is there anything else i need to worry about?

**Comment by nielsvanvelzen** [comment]
Users already have an identifier:

https://github.com/jellyfin/jellyfin/blob/dd57303a27dca0d35360423066792acf95e45ece/Jellyfin.Data/Entities/User.cs#L72

**Comment by sdimovv** [comment]
> Users already have an identifier:
> 
> https://github.com/jellyfin/jellyfin/blob/dd57303a27dca0d35360423066792acf95e45ece/Jellyfin.Data/Entities/User.cs#L72

Please don't mistake the `Id` with an `uid`! The `Id` is the **primary key** of the user model entry in the DB. And yes, while it is unique, it is **not** user settable. This makes it unusable for the use case I have.

**Comment by nielsvanvelzen** [comment]
So you want a second id that the plugin can set? IMO the plugin should map that internally, should be fairly easy to listen for user create/update/delete events from the server and update the mapping when necessary.

**Comment by sdimovv** [comment]
Interesting, I didn't realize plug-ins are allowed raw access to the DB. I had an idea in the begging to add a property in the plugin config class where i can map the uid against an user id but i assumed this is not a supported use case for it. 

If you don't mind, would you be able to write down some step-by-step implementation notes in the plugin ticket? They don't have to be very detailed, as long as they explain how to achieve what you propose. Like I said, C# is not a language I am familiar with and would appreciate any help I can get to implement this.

**Comment by nielsvanvelzen** [comment]
I'm not familiar enough with the server code (or plugin development) to give an example. I'm quite sure a plugin does not have access to the database though, so I'd probably just create a `Dictionary<Guid, Guid>` (key=ldap id, value=jellyfin id) that is serialized & deserialized to/from a file.

**Comment by sdimovv** [comment]
Not the best solutuon and I am not sure if extensions are even allowed to read/write arbitrary files. But might work as a temporary solution until someting like an uid field is added to the server code.

**Comment by Shadowghost** [comment]
They can write to their own config files (see e.g. the trakt plugin).
