### ISSUE TITLE
[Issue]: Pagination missing on unstable 10.9

### ISSUE THREAD

**Issue by Killface1980** [jellyfin/jellyfin#9809]
### Please describe your bug

With reference to https://github.com/jellyfin/jellyfin-web/issues/4574

With the switch to the unstable branch, all my library items display only the maximum amount per page with the pagination missing. The issue lasts for about 4 weeks now.
Nothing unusual in the logs. Switching back to the stable branch solves the issue for me.
Also JF on iOs truncates the entries to the max display value per page.
Issue appeared on JF in Docker and with a fresh Windows installation and fresh libraries.
Using the unstable web client with the stable server result in no issue. 

Max display set to 250
![image](https://github.com/jellyfin/jellyfin-web/assets/16738568/f4de0da8-6a45-4b3d-9d9a-0ee3b9c5d0d4)

Max display set to 0
![image](https://github.com/jellyfin/jellyfin-web/assets/16738568/d94e183d-67b4-4a8f-be25-f6e8b416ec18)

### Jellyfin Version

Other

### if other:

unstable

### Environment

```markdown
- OS: Windows 11 / Official Docker image
- Linux Kernel:
- Virtualization: Native/ Docker
- Clients: 10.9
- Browser: Chrome / JF iOS
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
Nothing unusual found
```

### Please attach any screenshots here

![image](https://github.com/jellyfin/jellyfin/assets/16738568/b06376d6-3164-4c42-b202-429f4626900f)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Tolriq** [comment]
See https://github.com/jellyfin/jellyfin/pull/9770 for the cause.
