### ISSUE TITLE
[Issue]: Android Client cannot connect to server

### ISSUE THREAD

**Issue by pinghedm** [jellyfin/jellyfin#9810]
### Please describe your bug

I have jellyfin running on my local network with a caddy reverse proxy, and also accessible from outside my network.

I upgraded to a new android phone, and I can not connect to my server using the jellyfin app (either installed from google play or from f droid)

I have tried connected to my local server with

http://192.168.0.136:8096 - this works in my browser and is what my old device, which can still connect, is connected to.  It is also what shows up in the available servers menu.
https://jellyfin.[mydomain] - this also works in a web browser currently

I have tried with and without trailing slashes.  In all cases I get the following error:

![image](https://github.com/jellyfin/jellyfin/assets/8351465/ca8de22c-5347-495c-aec4-8d3e313df8e0)

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: Ubuntu 22.04.2
- Linux Kernel: 5.15.0-69-generic
- Virtualization: none
- Clients: Android, Browser
- Browser: Chrome 112 [latest]
- FFmpeg Version: 5.1.3-Jellyfin
- Playback Method: I'm not sure what this is asking for.
- Hardware Acceleration: none
- GPU Model: none
- Plugins: Open Subtitles
- Reverse Proxy: caddy
- Base URL: none
- Networking: I'm not sure what this is asking for
- Storage: local
```

### Please attach any browser or client logs here

I don't know where docs that would allow me to get logs from the android client are - happy to add them if someone can point me to how I can get them

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nielsvanvelzen** [comment]
Jellyfin 10.7 is end of life and not supported.

**Comment by pinghedm** [comment]
Oh!  Thanks - upgrading solved the problem
