### ISSUE TITLE
Add FULL version to server dashboard in web interface

### ISSUE THREAD

**Issue by daniel-widrick** [jellyfin/jellyfin#982]
**Is your feature request related to a problem? Please describe.**
Would be nice to have a more clear release version shown on the dashboard web interface.

Was working on #965 and didn't realize that my "10.2.0" was behind the latest "10.2.0" at the time. 

**Describe the solution you'd like**
Would be nice to see the full version name in the dashboard for purposes of debugging.
EG: 10.2.0-RC1

**Describe alternatives you've considered**
I realized the difference when I checked the actual jellyfin directory name on the server.

**Comment by joshuaboniface** [comment]
We did investigate in the past, and found that it was extremely complicated to do so, causing all sorts of headaches. But it's worth keeping an eye on doing this, perhaps as a second field for "additional info". CC @EraYaN @nvllsvm

**Comment by EraYaN** [comment]
Well it’s very doable, just not “non-complex” although for now we can add an InformationalVersion attribute.
