### ISSUE TITLE
log files

### ISSUE THREAD

**Issue by htttito** [jellyfin/jellyfin#983]
Hi!
Jellyfin changes .log files from jellyfin.log to  log.1, log.2,..... by 10MB.
Wow thats much...
I protect jellyfin with fail2ban....so changing the log file is not so functionally.
- Is there a possibility to change the switch form log to log.1, log2....?
- Is there a possibility to change the size?
Thanks!

**Comment by JustAMan** [comment]
We use Serilog which is configurable by the end user, I believe you should be able to configure all that yourself.

cc @Bond-009 for details.

**Comment by joshuaboniface** [comment]
Unfortunately this is a limitation of the Serilog file sink, I already asked in an issue with them and it's not possible. You're probably better to disable the file logging altogether and use `journalctl` for `fail2ban`.
