### ISSUE TITLE
[Issue]: Metadata Manager page not loading: "CustomAuthentication" was forbidden.

### ISSUE THREAD

**Issue by Sjoerdfc** [jellyfin/jellyfin#9837]
### Please describe your bug

Yesterday I wanted to edit the metadata of a file, and I opened the Metadata Manager with Firefox, but the page would not load. It just says "Loading..." with a spinning animation. I don't use the Metadata Manager much, so I did not notice this earlier. Jellyfin has been working fine, it scans new files, I can open the admin dashboard, and everything plays correctly. Only the Metadata Manager page will not load. I thought maybe this is a jellyfin-web issue, but the same happens in the Android client.

I tried clearing my browser cache, using different browsers, disabling browser plugins, and incognito mode. I normally run Jellyfin through a reverse proxy (Caddy), but I also tried opening the web interface directly without the proxy, and the same thing happens.

I started downgrading to earlier versions to see if a change caused this. I initially ran version 10.8.10-1. In version 10.8.9-1 it stil did not work. But then in 10.8.8-1 the Metadata Manager loaded again, and everything worked.

I get an CustomAuthentication error in the logs in versions >= 10.8.9-1, see the log file below.

### Jellyfin Version

10.8.9

### Environment

```markdown
- OS: Ubuntu 22.04.2 LTS
- Linux Kernel: 5.15.0-72-generic
- Virtualization: KVM
- Clients: Web and Android Client
- Browser: Firefox 113 and Chrome
- FFmpeg Version: jellyfin-ffmpeg5 5.1.3-1-jammy
- Playback Method: n/a
- Hardware Acceleration: Yes
- GPU Model: Quadro P400
- Plugins: AudioDB, Kodi Sync Queue, MusicBrainz, OMDb, Studio Images, TMDb, Trakt
- Reverse Proxy: Caddy, but also tested without 
- Base URL: none
- Networking: Linux Bridge
- Storage: NFS
```

### Jellyfin logs

```shell
[2023-05-30 06:53:12.488 +00:00] [INF] WS "10.10.0.6" request
[2023-05-30 06:53:12.709 +00:00] [INF] "StartupTrigger" fired for task: "Update Plugins"
[2023-05-30 06:53:12.710 +00:00] [INF] Queuing task "PluginUpdateTask"
[2023-05-30 06:53:12.712 +00:00] [INF] Executing "Update Plugins"
[2023-05-30 06:53:13.708 +00:00] [INF] "Update Plugins" Completed after 0 minute(s) and 0 seconds
[2023-05-30 06:53:13.712 +00:00] [INF] ExecuteQueuedTasks
[2023-05-30 06:53:15.612 +00:00] [INF] AuthenticationScheme: "CustomAuthentication" was forbidden.
[2023-05-30 06:53:18.750 +00:00] [INF] AuthenticationScheme: "CustomAuthentication" was forbidden.
```

### Please attach any browser or client logs here

![jellyfin browser log](https://github.com/jellyfin/jellyfin/assets/22343961/46b7ab36-f623-4062-a030-de29209f4ee0)

### Please attach any screenshots here

![image](https://github.com/jellyfin/jellyfin/assets/22343961/d6d890d2-9f6b-492d-ade2-ebe5995242c3)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deep-soft** [comment]
from web admin:
Users \ Profiles \ <name of the user>
check: "Allow Live TV access"

**Comment by Sjoerdfc** [comment]
Uhm, huh. Yes, that fixed it.

But isn't this still a bug? What has Live TV have to do with the Metadata Manager? 

In the documentation it only states:
"**Allow Live TV access** Unchecking this option will block the user's access to watch Live TV."

**Comment by deep-soft** [comment]
You're right.
For me does not matter, I don't have Live TV entries defined.
But until it's fixed was the only option to cleanup the log.
Probably, somewhere in the code, must be something like that: if user it's not allowed to see those Live TV entries then do not check for authentication for that user.

**Comment by Sjoerdfc** [comment]
Unfortunately I saw this too late. 

I just upgraded to 10.8.11 and tested this again, and the bug is still there. As soon as I uncheck the "Allow Live TV access" under Users, I cannot open the Metadata Manager. It seems to me this still needs to be fixed someday, so this issue must be opened again. 

And since @deep-soft suggested the workaround, it seems I'm not the only one with this problem.

**Comment by felix920506** [comment]
Does this happen on master?

**Comment by felix920506** [comment]
Sometimes things get fixed as a side effect of something else so it would be appreciated if you could test on master.
Please make backups of configs, databases etc. as the upgrade is irreversible.
