### ISSUE TITLE
Jellyfin loading issue when attempting to add libraries

### ISSUE THREAD

**Issue by RitchZoeSquad** [jellyfin/jellyfin#9839]
Hello Guys I'm having issues with Jellyfin where it will not read nothing on my Usb or extenal drives it used to read my disk fine; now it does not read them anymore. I have multiple usb's connected to it and it used to read them now Its stuck on this page loading and loading every single one of them does that . I've already uninstalled it multiple times. I've installed Jellyin on multiple of my servers and its still doing this. I've cleared my cache and its still not letting me read anything on my libraries. Please help I dont think its a permission issues because its doing the same exact errors on both linux and windows.

Windows Operating System 
Windows 8.10 Version 
Version 113.0.5672.126 (Official Build) (arm64)

**Comment by JPVenson** [comment]
Please follow the Bug report template and include the asked logfiles.

**Comment by felix920506** [comment]
Closing this as it is not a valid issue report. 

Please head to our [forum or Matrix/Discord channels](https://jellyfin.org/contact) for general questions and troubleshooting.

Alternatively, open a new issue and fill out the issue template properly.
