### ISSUE TITLE
[Issue]: Large Number of INotify Watchers on Configuration Directory (Also Slow Startup Speeds)

### ISSUE THREAD

**Issue by Silvenga** [jellyfin/jellyfin#9843]
### Please describe your bug

Some Ubuntu built-in services started crashing on my server. From diagnosing these, I found that the crashes were a result of running out of allow inotify handler fd's.

```
   INOTIFY   INSTANCES
   WATCHES      PER
    COUNT     PROCESS   PID USER         COMMAND
------------------------------------------------------------
    6321         1      15590 root        ./jellyfin/jellyfin --ffmpeg /usr/lib/jellyfin-ffmpeg/ffmpeg --nowebclient
```

Now, I've disabled watching for library changes months ago (my file system doesn't support them, so they don't actually work correctly). I also looked at the code for a possible bug around enabling watching of these folders, but I only see `FileSystemWatcher` created in `LibraryMonitor`.

So I started doing reverse lookups of the inotify referenced inodes.

```
find . -inum 11287023  -printf "%i %p\n"
11287023 ./config/data/metadata/library/76/76d9b1adcf5cccfb0a61d0a7c62ff884
```

And all the inodes I sampled where in the `./config` directory, which is strange... why over 6k watchers?

### Jellyfin Version

10.8.9

### Environment

```markdown
- OS: Ubuntu
- Linux Kernel: 5.4.0-1108-azure
- Virtualization: Hyper-V (and containerd)
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage: ext4
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Silvenga** [comment]
I *think* this might be related to `IConfiguration` as I've seen similar problems in production workloads. I'll try with a custom build container and see what happens 🤷

**Comment by Silvenga** [comment]
Ugh, it is `IConfiguration`

![image](https://github.com/jellyfin/jellyfin/assets/2753330/361ddbde-7a4c-4064-ae28-2565943f6cba)

My env var must be bad.

**Comment by Silvenga** [comment]
Turns out the default configuration mounts for [linuxserver/docker-jellyfin](https://github.com/linuxserver/docker-jellyfin) are just bad. This was the reason why my jelly instance was taking 3+ minutes to start serving requests.

The default linuxserver/docker-jellyfin settings are to place all the metadata in the /config folder, plus the images default `JELLYFIN_CONFIG_DIR=/config`. This causes thousands of inotify watchers + a recursive directory scan.

I'll keep this open, I can make a document PR to warn uses if the Jelly project feels that would be useful.

**Comment by cvium** [comment]
Nice detective work. Seems like there's unfortunately no way to disable that file watcher

**Comment by Silvenga** [comment]
@cvium would the project be open to disable file watching if possible (in non-dev builds)? I saw that file watching was explicitly enabled on the included configuration files - I didn't know if that would break someone.

I can take a deeper look if so, and maybe make a PR. I swear `DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE=false` used to work, but maybe it moved or something... Maybe removing the usage of base configuration path (for `IConfiguration`) and explicitly specifying the full path to each configuration file could just work.

I think that given the number of users that use the [linuxserver/docker-jellyfin](https://github.com/linuxserver/docker-jellyfin) images, and how hard it is to change the configuration base path (requires db changes), it would be a good idea, since this could improve startup times by orders of magnitudes (about 3-5 minutes for my 300GB metadata directory).

**Comment by edrock200** [comment]
For reference, the hotio container seems to do the same thing.

**Comment by Silvenga** [comment]
Oops, thanks for linking that @edrock200 - completely missed that during my (admittedly brief) search.

**Comment by edrock200** [comment]
As tempting as this is to replicate, I will wait for an update as I fear subsequent updates may break your patch. But appreciate the share @Silvenga

**Comment by edrock200** [comment]
> DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE=false

Hmm.....your post got me googling...and this env variable seemed to get rid of all the watches. It doesn't seem to break anything from my initial testing but that doesn't mean much. However inotify watchers are gone. Only made one change. Added env var
DOTNET_USE_POLLING_FILE_WATCHER=1

**Comment by edrock200** [comment]
@Silvenga after several days, setting the above env variable seems to be working with no side effects.

**Comment by edrock200** [comment]
It did speed up startup a little, but more importantly the navigation seems more responsive.

**Comment by srcrist** [comment]
Jellyfin's part in this issue should be closed out by https://github.com/jellyfin/jellyfin/pull/9447. Anything beyond that will require users to reach out to lsio about their container.
