### ISSUE TITLE
[Issue]: Handle movies with multiple/split files as one item

### ISSUE THREAD

**Issue by Kagee** [jellyfin/jellyfin#9848]
### Please describe your bug

> This is also a feature request [[1]](https://features.jellyfin.org/posts/198/handle-movies-with-multiple-split-files-as-one-item), but since that was closed, I was instructed to make a bug report. 

Currently when having a movie as multiple parts, named using any of the recognized patterns (i.e. cd, part, pt)  Jellyfish will show the movie as a movie (part 1) with "Additional Parts". (see screenshots)

The expected behaviour would be to show it as one movie (combining the playtime, making chapter list based on all files), and either transcoding the files to play as a single movie on the fly, or simply automaticly start playing the next part when finished with the first. As can be seen in the comments on the feature request, this is what is wanted and expected from this feature.

The directory sctructure for the library used for testing.
````
JellyfishBug
├── Big Buck Bunny Multiple Parts
│   ├── Big Buck Bunny-CD1.mkv
│   └── Big Buck Bunny-CD2.mkv
└── Big Buck Bunny Single Part
    └── Big Buck Bunny.mkv

2 directories, 3 files
````

### Jellyfin Version

10.8.z

### if other:

10.8.10

### Environment

```markdown
- OS: Ubuntu 22.04 (server)
- Clients: Windows 10, Android 13 (client)
- Browser: Chrome
```

### Please attach any screenshots here

How a movie split into to part-files is presented:
![image](https://github.com/jellyfin/jellyfin/assets/686579/4e1f90e6-768d-4fd4-9b16-2f2b81a5ebbf)

How the same movie in  a single file is presented, and what is expected with multi-part files:
![image](https://github.com/jellyfin/jellyfin/assets/686579/0c1c9404-33f4-437a-84ee-f2ce4562e538)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cvium** [comment]
I think there's some confusion surrounding this. The bug that you're describing is how it is intended to work.

**Comment by Kagee** [comment]
Would it then not be sensible to re-open the feature request?

**Comment by cvium** [comment]
It would, but I can't do it from my current location.

**Comment by dmitrylyzo** [comment]
FYI, in webui 10.9, additional parts will be added to the play queue automatically.
https://github.com/jellyfin/jellyfin-web/pull/4210

**Comment by Kagee** [comment]
That will be an improvement indeed.

**Comment by thornbill** [comment]
That feature request describes the feature as it already exists. If you want the behavior to be different, you should create a new feature request that clearly describes how you think it should work in comparison to how it currently works.

**Comment by Phippe** [comment]
FWIW, you can easily join multiple parts in MKVToolNix by starting with the first part, then importing all the remaining parts with "add/append to an existing source file" (or whatever it's called in English).
