### ISSUE TITLE
ALAC Won't play in Firefox and Chrome

### ISSUE THREAD

**Issue by felix920506** [jellyfin/jellyfin#9850]
**Media Info of the file**
https://hastebin.skyra.pw/agububizup.yaml

**Logs**
https://hastebin.skyra.pw/renobiniba.yaml

**FFmpeg Logs**
N/A

**Stats for Nerds Screenshots**
N/A

**Server System (please complete the following information):**
 - OS: Ubuntu 23.04 Server
 - Jellyfin Version: 10.8.10
 - Hardware settings & device: QSV enabled on Arc A750 (Not applicable to Audio)
 - Reverse proxy: Caddy
 - Other hardware notes: Media mounted from SMB share
 
**Client System (please complete the following information):**
 - Device: Macbook Pro 2021 14 inch (M1 Pro CPU)
 - OS: MacOS
 - Client: Browser
 - Browser Firefox and Chrome
 - Client and Browser Version: 113.0.2 (Firefox), 113.0.5672.126 (Chrome)

Other info: The file plays normally in Safari and JMP

**Comment by Bond-009** [comment]
Can you test unstable/master? It works fine for me on both firefox and chromium.
I used test files from here: http://www.hyperion-records.co.uk/testfiles.asp

**Comment by felix920506** [comment]
I have tested the same file with the master branch and it plays correctly in Firefox.

**Comment by Bond-009** [comment]
Great, this is fixed for Jellyfin 10.9
