### ISSUE TITLE
Docker stop timeout

### ISSUE THREAD

**Issue by stp6778** [jellyfin/jellyfin#9852]
### Please describe your bug

Hi,
JF 10.9.0 doesn't respond to kill -15 signal
Works fine for JF 10.8.10

$ time docker stop jellyfin
jellyfin

real    0m10,731s
user    0m0,044s
sys     0m0,038s

### Jellyfin Version

Other

### if other:

10.9.0

### Environment

```markdown
- OS: Debian
- Virtualization: Docker
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
What is the exact command you are using?

**Comment by stp6778** [comment]
The command is "time docker stop jellyfin"
It takes 10 seconds to complete : JF finally stops after docker sent a kill -9 signal 
There are no messages about shutdown in logfile because of the kill -9
