### ISSUE TITLE
Adding a TV show to my Favorites adds an additional unwanted movie

### ISSUE THREAD

**Issue by Sevenyx** [jellyfin/jellyfin#9853]
When I try to add certain TV shows to my Favorites list, it erroneously adds a movie as well. For example, if I add "Better Call Saul" to my Favorites, the movie "Eminem: All Access Europe" is added as well, even though I didn't add it. If I try to remove the auto-added movie from my Favorites, it will remove both the movie and the TV show as well (as if they're the same item somehow). This is happening with a couple of other TV shows as well. I've duplicated this error on both the Chrome browser and the Android app. I asked the server owner about this and I was told that this is the first time he's ever heard of this happening, and to post here.

**Comment by felix920506** [comment]
Could you fill out the issue template please?

**Comment by felix920506** [comment]
Issue template not filled, closing as invalid.
