### ISSUE TITLE
[Issue]: API /Items and /Users/{UserID}/Items Endpoint does not return all Items

### ISSUE THREAD

**Issue by CyferShepard** [jellyfin/jellyfin#9864]
### Please describe your bug

Describe the bug
I have the movie 'Avengers Endgame' in my library. If I use the API to get a list of items for a library ID some results are missing eg the mentioned movie.

To Reproduce
In Postman, set url to: http://jellyfin:8096/users/{UserID}/items/?ParentID={LibraryID} for  /Users/{UserID}/Items endpoint
or http://jellydfin:8096/items?parentID={LibraryID}  for the /Items Endpoint

Compare number of items returned vs the number of items in your library. This is most prominent with large libraries around 100+ items

I have discovered the issue with multiple different users on their own machines aswell.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Ubuntu Linux 20.04.6
- Linux Kernel: Linux 5.4.0-150-generic on x86_64
- Virtualization: Proxmox
- Clients: Other
- Browser: Axios/Postman
- Reverse Proxy: none
- Base URL: none
- Networking: Host
- Storage: Local
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nielsvanvelzen** [comment]
You cannot list everything at once, you should use pagination (limit and startIndex parameters). You might also need to set the recursive parameter to `true`.

**Comment by CyferShepard** [comment]
Hi @nielsvanvelzen , thanks for this, Il give it a try and report back, maybe to prevent an issue like this it should default to a set limit unless one is provided or an index is proviy? Right now the return limit seems random. In my case it breaks around 724 from the total of 735 items

**Comment by CyferShepard** [comment]
Thank you so much @nielsvanvelzen , this fixed the issue iv been having
