### ISSUE TITLE
[Issue]: Band name being split wrongly

### ISSUE THREAD

**Issue by ghost** [jellyfin/jellyfin#9871]
### Please describe your bug

# Description
The band She/Her/Hers is being split into She, Her and Hers, even though it has been added to the SplitWhitelist.
see: 
https://github.com/jellyfin/jellyfin/blob/c155ea1decb6967f4c1c7b4851fdcac8fe83b001/MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs#L45-L74

- **Band:** She/Her/Hers
- **Files:** https://sheherhers.bandcamp.com/album/she-her-hers (can be downloaded for free)

## Steps to reproduce:

1. put the files into any folder (i used an empty folder)
2. start the jellyfin server and scan
3. go to Music -> Album artists
4. See that there are 3 artists, She, Her and Hers
 
 
## other things i tried:
- instead of using "She/Her/Hers" in the metadata, i used "She-Her-Hers" and that worked, this is what i would expect to happen with the actual band name too.
- search for She/Her/Hers on musicbrainz, just to make sure it actually exists and can be found

I have reproduced this in both the latest truenas scale app, as well as locally on my laptop when trying to have a look if i could possibly fix it (turns out no, so here we are).

### Jellyfin Version

Other

### if other:

latest master & 10.8.10

### Environment

```markdown
- OS: EndeavourOS (~Archlinux)
- Linux Kernel: 6.3.5-arch1-1
- Virtualization: None
- Clients: Latest Web Client
- Browser: Firefox 113.0.2
- FFmpeg Version: 6.0
- Playback Method: None
- Hardware Acceleration: None
- GPU Model: None
- Plugins: None
- Reverse Proxy: None
- Base URL: None
- Networking: None
- Storage: local
```

### Please attach any screenshots here

# Plain scan, no changes to jellyfin or metadata
![Screenshot_20230608_162850](https://github.com/jellyfin/jellyfin/assets/42149402/c5d3b348-59e2-4067-b57a-dfe917fd4a62)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by peppage** [comment]
This is happening when it fetches the data from the tags. The code you linked is reading the values from ffprobe but then it loads the tags again using https://github.com/mono/taglib-sharp

Here's the issue in their project for something similar https://github.com/mono/taglib-sharp/issues/193

The refreshing is happening here
https://github.com/jellyfin/jellyfin/blob/c155ea1decb6967f4c1c7b4851fdcac8fe83b001/MediaBrowser.Providers/MediaInfo/AudioFileProber.cs#L180-L213

**Comment by FallenValkyrie** [comment]
ah... i had feared that was the case...
is there a workaround?
