### ISSUE TITLE
[Issue]: Jellyfin pulls textless posters from TMDB when language-matching posters exist

### ISSUE THREAD

**Issue by akesher123** [jellyfin/jellyfin#9878]
### Please describe your bug

For awhile now, occasionally Jellyfin pulls posters from TMDB with no text despite there being language-matching posters with text with more votes. These are annoying and clearly wrong, requiring manual intervention. Perhaps posters should be picked by most votes first, I feel it would produce more accurate results more often.

For example, my server instead of picking the primary image on the TMDB page for _The Great Dictator_, instead picked the textless one under "No Language" https://www.themoviedb.org/movie/914-the-great-dictator/images/posters?language=en-US

I found this PR that might have something to do with it: https://github.com/jellyfin/jellyfin/pull/8946

I thought this PR might have fixed it, but I can confirm with the attached image below (automatically sourced image is the same as the first one shown below) that this still reproduces

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Unraid
- Linux Kernel:
- Virtualization: docker
- Clients: Any
- Browser: Any
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Please attach any screenshots here

Another active example is _Harry Potter and the Order of the Phoenix_, which currently shows this priority
![image](https://github.com/jellyfin/jellyfin/assets/110856441/1bf317f3-4af7-4dfb-ac45-4de439901f8b)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by akesher123** [comment]
Actually, it looks like this exact behavior was fixed by the above PR, but this PR has never been put into a release branch, or is at least not in the patch notes.

When can we expect this to hit a stable release? It would be wonderful to have it.

**Comment by crobibero** [comment]
https://jellyfin.org/docs/general/faq#when-will-release-x-happen-when-will-feature-x-be-available
