### ISSUE TITLE
[Issue]: Jellyfin uses old German translation

### ISSUE THREAD

**Issue by Killface1980** [jellyfin/jellyfin#9879]
### Please describe your bug

In the German translation, there is still a typo that has been solved a year ago.
https://translate.jellyfin.org/translate/jellyfin/jellyfin-web/de/?offset=1&q=hinter+den+kulissen&sort_by=-priority%2Cposition&checksum=#history

I'm using the modified Web Client from the Intro Skipper plugin, if this might be the cause.

Also "Featurettes" are labelled as "Behind the scenes" in German, although they reside in their proper directory.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS:
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Please attach any screenshots here
German language
![image](https://github.com/jellyfin/jellyfin/assets/16738568/49cb5e3b-b2d2-4248-9f07-b13f589a4d44)
English version
![image](https://github.com/jellyfin/jellyfin/assets/16738568/6e0b1864-c9c6-4164-9a6f-44ce11296255)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shadowghost** [comment]
Translations are only updated on major version forking so this is to be expected.
