### ISSUE TITLE
PDF/CBZ Streaming

### ISSUE THREAD

**Issue by ohitstom** [jellyfin/jellyfin#9883]
When storing comics/books in pdf format they refuse to [stream](https://apryse.com/blog/mobile/streaming-a-pdf-from-the-web?utm_qliurn=share-7056430449291628544&campaign_id=202007786&ad_id=255640986&li_fat_id=2afbbd8e-0b59-4a21-9552-02aca7769500) like video media, instead forcing the user to download and extract client side. This isnt ideal for any devices out of network since comics can often be 100mb+ in size.

Not entirely sure if this should be under feature requests, but it makes book reading out of network almost impossible for anything other than low chapter count black and white text books.

**Comment by drazil100** [comment]
I would like to second this request. If it only took a minute I would be happy to wait, but the volume I just tried to load took over 10 minutes and I am pretty sure it got stuck (downloaded in like 3 minutes after closing the app and reopening it). It's horribly unusable for comics as it is now. 

I can understand if this is not a priority in the slightest. Chances are I should probably just find another solution for comics and just use Jellyfin for my movies tv shows and music, but I wanted to throw my support behind this request too as I was a little surprised how unusable Jellyfin is for comics.

**Comment by sevenrats** [comment]
moved https://features.jellyfin.org/posts/2364/pdf-cbz-streaming
