### ISSUE TITLE
Do not allow users to delete media by default

### ISSUE THREAD

**Issue by LeoVerto** [jellyfin/jellyfin#989]
While it probably makes sense for some deployments I do not believe allowing any user to delete any media is a sensible default setting.

For further discussion, see [this reddit thread](https://www.reddit.com/r/jellyfin/comments/atp9a3/how_to_disable_delete_for_non_admin_users/).

**Comment by bobberb** [comment]
https://github.com/jellyfin/jellyfin/issues/79
