### ISSUE TITLE
[Issue]: Jellyfin couldn't properly identify an episode as being part of an already-existing TV show because of a specific MKV file

### ISSUE THREAD

**Issue by hbCyber** [jellyfin/jellyfin#9896]
### Please describe your bug

I added an MKV file of a TV show episode to my library. The episode was the 1st episode of the 2nd season. My library already had all episodes of the 1st season, and the metadata was retrieved properly.

Once the MKV was added, Jellyfin would oddly identify the file as a separate entity, not part of the parent show. The episode would appear in the "Latest shows" panel, but couldn't be found in the "Shows" library. Furthermore, if I navigated to the "Shows" library and manually selected the parent show (to whom the episode belonged), the episode itself also couldn't be found.

Editing the episode's metadata and manually inserting IMDB and TVDB IDs for that episode did not solve the issue.

When I inspected the media information for that episode, I noticed that Jellyfin did not output any information other than the file name. Usually, that panel includes more information about the video/audio streams, etc. 

As a result, I tried converting the MKV file to MP4 using Handbrake and the "Fast 1080p" preset. Once the episode was converted, I replaced the MKV file with the MP4 file in the library, and triggered a rescan.

The episode was properly inventoried after that; it was correctly part of the parent show, and the metadata was retrieved successfully.

I hope this helps track down the issue!

Here's the log.
[log_20230616.log](https://github.com/jellyfin/jellyfin/files/11772726/log_20230616.log)

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Windows 10
```

### Please attach any browser or client logs here

Out of curiosity, I ran `ffprobe` on the original MKV file. Here are the results:
```
C:\Programs\ffmpeg\bin>ffprobe "Star Trek - Strange New Worlds - S02E01 - The Broken Circle HDTV-1080p.mkv"
ffprobe version 6.0-essentials_build-www.gyan.dev Copyright (c) 2007-2023 the FFmpeg developers
  built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libvpl --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
Input #0, matroska,webm, from 'Star Trek - Strange New Worlds - S02E01 - The Broken Circle HDTV-1080p.mkv':
  Metadata:
    title           : Star.Trek.Strange.New.Worlds.S02E01
    COMMENT         : ELiTE-Thu-15-Jun-2023,15:22:02,1080p,23,faster,4540461,0,-1
    ENCODER         : Lavf59.16.100
  Duration: 00:52:41.34, start: 0.000000, bitrate: 1310 kb/s
  Stream #0:0: Video: hevc (Main), yuv420p(tv, bt709, progressive), 1920x800 [SAR 1:1 DAR 12:5], 24 fps, 24 tbr, 1k tbn (default)
    Metadata:
      ENCODER         : Lavc59.18.100 libx265
      DURATION        : 00:52:41.339000000
  Stream #0:1(eng): Audio: ac3, 48000 Hz, 5.1(side), fltp, 448 kb/s (default)
    Metadata:
      ENCODER         : Lavc59.18.100 ac3
      DURATION        : 00:52:41.344000000
  Stream #0:2(eng): Subtitle: subrip
    Metadata:
      DURATION        : 00:51:07.852000000
```

### Please attach any screenshots here

Screenshot of how the episode appeared in the UI:
![image](https://github.com/jellyfin/jellyfin/assets/7698618/074351d1-0223-49fd-ac11-e501372e92af)

Screenshot of the media information panel of the original MKV file:
![image](https://github.com/jellyfin/jellyfin/assets/7698618/189515e2-493e-4f76-9945-93f7bb3a5dae)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by srcrist** [comment]
Hey there. It's possible that the metadata simply did not exist on the provider at the time you were trying to add this episode. There can sometimes be a delay between when an episode airs, and when users submit the metadata information to the metadata providers. I don't see anything that leaps out as particularly wrong with what you did, but I also haven't seen any other reports of this being an issue, which makes me think it was probably a temporary provider issue, and not a Jellyfin bug.

Are you able to confirm that this is still an issue with this episode now?

**Comment by clockwork-ws** [comment]
> Hey there. It's possible that the metadata simply did not exist on the provider at the time you were trying to add this episode. There can sometimes be a delay between when an episode airs, and when users submit the metadata information to the metadata providers. I don't see anything that leaps out as particularly wrong with what you did, but I also haven't seen any other reports of this being an issue, which makes me think it was probably a temporary provider issue, and not a Jellyfin bug.
> 
> Are you able to confirm that this is still an issue with this episode now?

Thanks for the response!

I don't think the metadata was the issue as other episodes from that season were parsed just fine, and the information came instantly once I converted the video from MKV to MP4. I really think the issue was something to do with the media file having something about it that "crashed" the Jellyfin metadata process.

Unfortunately I do not have the original MKV file for analysis at that point.

The episode is working fine since I posted the issue, as I had converted it to MP4 and that solved the issue. Note that this isn't an issue with MKVs in general, I have plenty of those on Jellyfin and the other ones work fine. I was just posting this in case it helps track down an issue in the MKV parser that crashes the metadata retrieval process.

**Comment by hbCyber** [comment]
Thanks for the response!

I don't think the metadata was the issue as other episodes from that season were parsed just fine, and the information came instantly once I converted the video from MKV to MP4. I really think the issue was something to do with the media file having something about it that "crashed" the Jellyfin metadata process.

Unfortunately I do not have the original MKV file for analysis at that point.

The episode is working fine since I posted the issue, as I had converted it to MP4 and that solved the issue. Note that this isn't an issue with MKVs in general, I have plenty of those on Jellyfin and the other ones work fine. I was just posting this in case it helps track down an issue in the MKV parser that crashes the metadata retrieval process.

**Comment by srcrist** [comment]
Alright. Sounds good. I'll go ahead and close this one down as stale, then, since we no longer have access to this specific file. It might have been been a corrupt header in the container or something. If it ever reoccurs, just open another issue.
