### ISSUE TITLE
Feedback on Jellyfin Subreddit going dark

### ISSUE THREAD

**Issue by VampiricAlien** [jellyfin/jellyfin#9898]
### Please describe your bug

"We're now private indefinitely due to Reddit Incorporated's poor management and decisions related to third party platforms and content management. See https://jellyfin.org/contact for contact options. For more (and updated) information see /r/ModCoord. https://www.reddit.com/r/ModCoord/comments/1476fkn/reddit_blackout_2023_save_3rd_party_apps/ Messages sent via the button below will receive no reply."

I am all for taking a stance however the lack of information from the jellyfin Team is a little troublesome.  I expected a blog post or a pinned "issue" stating what was going on and why. I thought the subreddit got taken over a few days ago, that's when I learnt about the Reddit going dark. 

I just felt like I needed to say something, no hard feelings.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS:
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by skribe-too** [comment]
This isn't a bug, and the github issues are not a soap box. What sort of additional information did you expect? There really isn't additional information to provide you. The project has closed its reddit presence and is exploring other options. The subreddit was run by the jellyfin team itself. What you quoted already provides you with other points of contact. 

When there is an announcement to make, I am sure an announcement will be made.

**Comment by crobibero** [comment]
https://jellyfin.org/posts/new-forum
