### ISSUE TITLE
Moving to GH issues for Feature Requests

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin#99]
Right now we call out using Feathub in the readme. While the service is "free" for the time being, it's hard to tell if it's very active/will stay up. 

I'd like to come up with one solid place to monitor, and right now that's here on this repo.

Ideally, I would like to do something similar to what twbs/bootstrap has set up, where there's a feature request link on their readme, that brings you this:
https://github.com/twbs/bootstrap/issues/new?template=feature.md&labels=feature

It opens the issue creator, populates it with a Feature Request template, and will apply the appropriate label.

Does this sound good?

**Comment by thejacer87** [comment]
i never liked using feathub. i guess it keeps the issue queue cleaner... but i prefer everything in one spot

**Comment by BnMcG** [comment]
Would prefer to use GitHub for this, could be useful in conjunction with milestones for version releases as well.

**Comment by anthonylavado** [comment]
Thanks folks, I'll put this together tonight.

**Comment by JustAMan** [comment]
I'm for single tracking place, too.

**Comment by Terror-Gene** [comment]
The main reason i prefer feathub is because it gives a clear list of what the most requested features are. makes it easy to see if its already been requested & is easy to +1. But that's just my opinion from an end user point of view.

**Comment by nvllsvm** [comment]
+1 for GitHub issues. We're already using quite a few services and technologies - best to keep it simple for now.

**Comment by anthonylavado** [comment]
This is done. Closing.
