### ISSUE TITLE
[Issue]: 2 Music Libraries not seperated

### ISSUE THREAD

**Issue by Y0ngg4n** [jellyfin/jellyfin#9903]
### Please describe your bug

If you create 2 music libraries with different folders. They are not seperated.
You can view the playlists and the music from both.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Debian 11
- Linux Kernel: 
- Virtualization: Docker
- Clients: Firefox, Android, Finamp
- Browser: 186920
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL: /
- Networking:
- Storage: local
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by HybridSarcasm** [comment]
This has been open quite a while. Can this be re-produced with the current build? If so, please update the bug report details. Thanks!

**Comment by Y0ngg4n** [comment]
@HybridSarcasm seems to work now
