### ISSUE TITLE
[Issue]: artists with multiple credit names are listed as different artists

### ISSUE THREAD

**Issue by csaavedra** [jellyfin/jellyfin#9913]
### Please describe your bug

I have albums by the artists "Los Pericos" that have varying credit artist (see https://musicbrainz.org/artist/fe50841b-f14b-4882-a4be-38a04f69374b, 5 of their albums are credited to "Pericos"). Jellyfin lists two different artists: "Pericos" and "Los Pericos". Both have a link to the same artist page in MusicBrainz.

Artists with varying artist credits should be listed as one, using the main artist name for indexing / listing and the credit artist name for credits on albums only.

### Jellyfin Version

10.8.z

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by csaavedra** [comment]
This still an issue, yes.

**Comment by sjorge** [comment]
> This still an issue, yes.

I've also been hitting this, e.g. https://musicbrainz.org/artist/aabb1d9f-be12-45b3-a84d-a1fc3e8181fd

Although I've been able to work around it with `MusicBrain Picard` which I was using anyway to tag my music by enabling these to options:

<img width="817" alt="Screenshot 2024-02-18 at 09 42 49" src="https://github.com/jellyfin/jellyfin/assets/379665/016d4556-c761-4426-949c-53a716021b75">

MusicBrain Picard then seems to use the main artist name regardless of what is set on the individual albums. Not perfect, but good enough. In the case mentioned above it uses `Tiësto` in all places, where before it was a mix of `Tiësto` and `DJ Tiësto`.

**Comment by csaavedra** [comment]
Still an issue.

**Comment by felix920506** [comment]
JF identifies people with names. If you would like JF to be able to identify them using means other than names, please open a feature request at https://features.jellyfin.org
