### ISSUE TITLE
Audio delay when hitting play

### ISSUE THREAD

**Issue by DaGloaDone** [jellyfin/jellyfin#9918]
Hello :)
So when i watch Movies or Tv-Shows everytime i hit play after i paused, the Audio doesn‘t continue the same time as the video does. The Video plays for like a second without audio and then it starts.

this happens to me on all devices (Firestick with Kodi and Jellyfin plugin, IOS devices with swiftfin)

thank you :)

**Comment by felix920506** [comment]
Closing this as it is not a valid issue report. 

Please head to our [forum or Matrix/Discord channels](https://jellyfin.org/contact) for troubleshooting and general questions.
