### ISSUE TITLE
Move To Library Hook

### ISSUE THREAD

**Issue by oatsvine** [jellyfin/jellyfin#9922]
I'm willing to contribute to this, but I have a feeling that this feature must exist in a community plugin somewhere. Any pointers appreciated.

The Jellyfin UI has a "delete" action, which deletes the underlying media directory. It seems intuitive to also include a "move" action to move media from one library to another. Now, I understand why it's not that simple. I think Jellyfin can easily update its db, but rules for moving files on the filesystem may not be as straightforward.

What I'm looking for is a "move" action that simply calls a "hook" to let me move the files as I see fit. In its simplest form, it would call a shell script with the source path in stdin, entrusting the script to move and then print the destination path in stdout. Jeffyfin would handle the rest. Of course, using webhooks or other web standards works just as well.

I believe this is a high-value feature because, even if Jellyfin engineered a safe file system "move" implementation, it won't be enough for users who seed these files via torrent clients. By providing a good "move" abstraction, users can re-used their existing scripts.

**Comment by JPVenson** [comment]
Moving a file is unfortunately _not_ that easy. JF relies in its database for identification of a media file on its path. So the path is a key generation factor for its id. Updating all this, is no easy task.
On the other hand, i think the feature is really not "in scope" of what JF should do, esp. not with the background on contributing anything towards easier use of torrent users.

**Comment by ZacharyACoon** [comment]
> Moving a file is unfortunately _not_ that easy. JF relies in its database for identification of a media file on its path. So the path is a key generation factor for its id. Updating all this, is no easy task. On the other hand, i think the feature is really not "in scope" of what JF should do, esp. not with the background on contributing anything towards easier use of torrent users.

Traditionally the way this is handled is to abstract a "library directory", which can be altered.
Then any file in the database is simply a relative path within the library.

Then anyone can move their entire library, and all it requires is a single library path update.

all files are simply referred to and accessed as   `library_directory + media_directory`

**Comment by Bond-009** [comment]
Feature requests go [here](https://features.jellyfin.org/)

**Comment by Dobeemixer** [comment]
Any good way to do this? Don’t need anything fancy but wondering if there’s a way to change Library page without making metadata messy
