### ISSUE TITLE
Certifications included Country Code

### ISSUE THREAD

**Issue by purevertigo** [jellyfin/jellyfin#9931]
### Please describe your bug

When viewing the info page on the client device/web the certification includes the country code before it which should be hidden.

For example like the picture below - 

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS:Windows
- Clients: All
- Browser: All
```

### Please attach any screenshots here

![Screenshot 2023-06-26 204601](https://github.com/jellyfin/jellyfin/assets/6506461/93400030-3bec-4371-affa-0b8e3652dbb1)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
Can you please explain how this is a bug? This sounds like a feature request to me.

**Comment by purevertigo** [comment]
> 

Definitely a bug. It should be listed as e.g.
MA15+
and the 
AU-
should be hidden behind the UI. Just like Plex does.

**Comment by purevertigo** [comment]
> Can you please explain how this is a bug? This sounds like a feature request to me.

Definitely a bug. It should be listed as e.g.
MA15+
and the
AU-
should be hidden behind the UI. Just like Plex does.

**Comment by Shadowghost** [comment]
IMHO this is not a but because the ratings provided by the metadata providers usually fall back to US based ratings if there are none specific to your country.
And e.g. PG has different implications in different rating systems, making it indistinguishable without the country code prepended.

And just because Plex does it doesn't mean we need to do it or it's the right way to do it.

**Comment by purevertigo** [comment]
> IMHO this is not a but because the ratings provided by the metadata providers usually fall back to US based ratings if there are none specific to your country. And e.g. PG has different implications in different rating systems, making it indistinguishable without the country code prepended.
> 
> And just because Plex does it doesn't mean we need to do it or it's the right way to do it.

If there is an NFO present you can add your own certification rating.

with the second point, I did not mean to take away the country code. Keep it in the edit field and nfo but 'hide' it in the UI again.

I was just pointing out that Plex has done certifications right in this regard.

**Comment by srcrist** [comment]
Closing this issue as it is not actually a bug, but a UI design preference. Feel free to submit ideas for different UI designs by visiting the UX/UI channels on Matrix/Discord, or submitting them as feature requests at [features.jellyfin.org](features.jellyfin.org).
