### ISSUE TITLE
[Issue]: Movie images randomly disappear

### ISSUE THREAD

**Issue by need4swede** [jellyfin/jellyfin#9937]
### Please describe your bug

Previously functioning metadata images (such as primary, backdrops, logos, etc.) randomly stop displaying, most commonly after doing a library scan / refresh but also periodically (possibly after a scheduled task refresh). The images are set to be stored within the respective media's directory and can be found and accessed just fine. At no point are the images deleted or lost - they are right where they should be. (See screenshots)

Upon doing a refresh of an effected film, the images appear instantly. Doing a refresh on the library as a whole does nothing - the movies have to be refreshed individually. 

This occurs every time I refresh the movie library, but effects movies at random. This only happens to movies and I have not observed this behavior with TV Shows. This effects every client, including media players such as Infuse on our Apple TV. The images don't appear and doing a 'metadata refresh' on the client does nothing. Upon doing a refresh server side, the images all appear as they should on every client device immediately. 

### Jellyfin Version

Other

### if other:

10.8.10

### Environment

```markdown
- OS: Windows 11
- Clients: Browser, Infuse (Apple TV)
- Browser: Firefox (114.0.2), Chrome
- FFmpeg Version: Whatever came with Jellyfin 10.8.10
- Playback Method: All of the Above
- Hardware Acceleration: NVENC
- GPU Model: T600
- Plugins: Intro Skipper, Fanart, IMVDb, Local Intros, Session Cleaner, TMDb, TheTVDB, Theme Songs
- Reverse Proxy: none
- Base URL: none
- Networking: Host
- Storage: SMB Share
```

### Please attach any screenshots here

<img width="1398" alt="Screenshot_2023-06-27_at_09 34 37" src="https://github.com/jellyfin/jellyfin/assets/57847545/ecfd2d56-48a6-442c-b275-91ba1167f45a">

https://github.com/jellyfin/jellyfin/assets/57847545/8fa52ce8-f3d4-4d34-a04c-e5a7b469d5de

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gummykage** [comment]
I had this exact problem, and the way I resolved it was for each of the movies that weren't showing up, I remuxed it with MKVToolsNIX GUI. Eventually out of some 2000+ movies I found 17 movies that were causing issues during metadata refreshes or Scan media library. It caused random images to vanish out of the library mostly because it causes aborts during the scanning process. I now believe strongly that the mkv file has some sort of corruption as this did eventually full solve my issue.

**Comment by srcrist** [comment]
These symptoms would most describe intermittent connectivity issues with your storage device. That this is not a commonly reported issue points away from any sort of UI bug and toward some sort of specific configuration issue for the server in question. If you review your server logs they may contain information to help you troubleshoot. We also have troubleshooting communities on the forums and our Matrix/Discord server if you would like someone to help you look over your logs.

**Comment by Y0ngg4n** [comment]
same issue here

**Comment by Y0ngg4n** [comment]
not stale
