### ISSUE TITLE
[Issue]: HTTP 500s are not reported

### ISSUE THREAD

**Issue by Haarolean** [jellyfin/jellyfin#9946]
### Please describe your bug

Tried to upload subtitles as a file first from an ios (iPad) client, but nothing happened, did the same right after within a browser version on pc, and got HTTP 500 with "Error processing request.". It would be nice to let the client know something didn't work instead of swallowing the error.

### Jellyfin Version

Other

### if other:

10.8.10

### Environment

```markdown
- OS:
- Linux Kernel:
- Virtualization: docker
- Clients: ipad, browser
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Please attach any browser or client logs here

Failed request: `POST http://xxx:8096/Videos/cc71ef2ec3139d848c29dfebf753a253/Subtitles`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jacobslusser** [comment]
A 500 response is usually the result of an unexpected exception, i.e. we don't know why it failed the way it did, otherwise we would have provided a more specific response.

Are you able to replicate it and get the Jellyfin logs to help us track down the issue? Can you share the subtitle file that is causing the issue?

**Comment by Haarolean** [comment]
> A 500 response is usually the result of an unexpected exception, i.e. we don't know why it failed the way it did, otherwise we would have provided a more specific response.
> 
> 
> 
> Are you able to replicate it and get the Jellyfin logs to help us track down the issue? Can you share the subtitle file that is causing the issue?

It's not that you don't show the details, in the case of the app you don't show the error at all.

**Comment by Haarolean** [comment]
Bump
