### ISSUE TITLE
[Issue]: Shuffle in a mixed image folder only plays videos if videos are present

### ISSUE THREAD

**Issue by JohnEridium** [jellyfin/jellyfin#9956]
### Please describe your bug

When creating an album of the type „images“, where both images and videos are present, shuffle only plays the videos. Instead, I’d expect it to play images and videos if these are the media types present.

I don’t really know what Logs I should provide, but it is reconstructible. It was also mentioned in issue #4256 but it was closed due to inactivity (no one but OP responded and next to me, another user commented that It was still not fixed after the issue was closed.)

### Jellyfin Version

10.8.11

### Environment

```markdown
- OS: Debian 11
- Linux Kernel: 5.15.107-2-pve 
- Virtualization: LXC on PVE 8.0.4
- Clients: iOS + macOS 
- Browser: Safari
- FFmpeg Version: 5.1.3-Jellyfin
- Playback Method:
- Hardware Acceleration: NVENC
- GPU Model: Nvidia 1050Ti
- Plugins: InfuseSync, AudioDB, MusicBrainz, OMDb, TMDb, YouTube metadata, StudioImages
- Reverse Proxy: NginxProxyManager
- Base URL: subdomain, not via URL path
- Networking: Ethernet
- Storage: local —> LXC ZFS mountpoint
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by HybridSarcasm** [comment]
This has been open quite a while. Can this be re-produced with the current build? If so, please update the bug report details. Thanks!

**Comment by JohnEridium** [comment]
Hi, yes, this is still present in the current jellyfish version (10.8.11).
The tree layout of the image library is like this:

Library:
'-Vacations
      '-2019
          '-place1
                '-(mix of png, jpg, mp4 files)
          '-place2
                '-(mix of png, jpg, mp4 files)

if I start a shuffle in the root dir of the library (where Vacations lies next to other folders) I get images and videos in the shuffle. But if I click shuffle in the directory where 2019 and other directories are, I only get videos.

What more infos should I provide? I'm not sure what else to include since the logs include no errors or warnings and I'd need to anonymes them because the files and directory names include names

**Comment by ReedSchroeder** [comment]
Just came across this as I have been having the same problem.

**Comment by qucee98** [comment]
same issue for me, except it plays only images. I'm using web browser client.

**Comment by qucee98** [comment]
@HybridSarcasm can we reopen this issue?

Is there a configuration we can set to filter by file type extensions when doing `shuffle` from a root directory containing mix of images, videos, gifs, etc...?

CC: @LukePulverenti, @Bond-009, @crobibero, @theguymadmax, @JPVenson, @joshuaboniface, @nielsvanvelzen, @weblate

Related issue closed without resolution: https://github.com/jellyfin/jellyfin/issues/4256
