### ISSUE TITLE
Android TV official app can't play SSA/ASS subtitles (there is no option to enable like in the Android app for mobiles)

### ISSUE THREAD

**Issue by raulpetru** [jellyfin/jellyfin#9964]
**Media Info of the file**
General
Unique ID                                : 209830786305952452455496204121740007415 (0x9DDBF08074F133633075C5A441A1D7F7)
Complete name                            : Z:\Anime\Demon Slayer Kimetsu no Yaiba (2019)\Season 3\[Subsplease] Kimetsu No Yaiba - Yuukaku-Hen - 01 (1080P) [E6815c78].mkv
Format                                   : Matroska
Format version                           : Version 4
File size                                : 983 MiB
Duration                                 : 46 min 51 s
Overall bit rate                         : 2 934 kb/s
Frame rate                               : 23.976 FPS
Encoded date                             : 2023-06-12 16:29:15 UTC
Writing application                      : HandBrake 1.6.1 2023012300
Writing library                          : Lavf59.27.100
ErrorDetectionType                       : Per level 1
Attachments                              : Roboto-Medium.ttf / Roboto-MediumItalic.ttf / arial.ttf / arialbd.ttf / comic.ttf / comicbd.ttf / times.ttf / timesbd.ttf / trebuc.ttf / trebucbd.ttf / verdana.ttf / verdanab.ttf

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : Main@L4
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 4 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 46 min 51 s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Writing library                          : x264 core 164 r3100 ed0f7a6
Encoding settings                        : cabac=1 / ref=2 / deblock=1:0:0 / analyse=0x1:0x111 / me=hex / subme=6 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=0 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=18 / lookahead_threads=3 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=1 / keyint=240 / keyint_min=24 / scenecut=40 / intra_refresh=0 / rc_lookahead=30 / rc=crf / mbtree=1 / crf=22.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / vbv_maxrate=20000 / vbv_bufsize=25000 / crf_max=0.0 / nal_hrd=none / filler=0 / ip_ratio=1.40 / aq=1:1.00
Default                                  : Yes
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709

Audio
ID                                       : 2
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : A_AAC-2
Duration                                 : 46 min 51 s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 44.1 kHz
Frame rate                               : 43.066 FPS (1024 SPF)
Compression mode                         : Lossy
Delay relative to video                  : -23 ms
Title                                    : Stereo
Language                                 : Japanese
Default                                  : Yes
Forced                                   : No

Text
ID                                       : 3
Format                                   : ASS
Codec ID                                 : S_TEXT/ASS
Codec ID/Info                            : Advanced Sub Station Alpha
Duration                                 : 46 min 51 s
Compression mode                         : Lossless
Title                                    : English subs
Language                                 : English
Default                                  : No
Forced                                   : No

**Server System (please complete the following information):**
 - OS: Raspbian (no docker)
 - Jellyfin Version: 10.8.10
 - Hardware settings & device: Raspberry PI 4 ARM64
 - Reverse proxy: Caddy
 - Other hardware notes: external HDD connected via USB3 to Raspberry
 
**Client System (please complete the following information):**
 - Device: TV PHILIPS 43PUS7906,4K, HDR, 108 cm, UHD43PUS7906
 - OS: Android TV
 - Client: Jellyfin-androidtv 0.15.11 release using integrated Exo player

The issue is that the video file will remux on official Android TV app without even showing the subtitles. I get the same result on Android phone if I disable the "Allow SSA/ASS subtitles in direct play". But on Android TV in client settings there is no option to enable "Allow SSA/ASS subtitles in direct play".

**Comment by happyTonakai** [comment]
I have the same issue, how did you fix it?

**Comment by raulpetru** [comment]
> I have the same issue, how did you fix it?

From app's settings, use external player. I recommend MX Player or maybe MPV (but I haven't tried this one, I just know it's reputation on Windows because is lightweight but very powerful.).

**Comment by happyTonakai** [comment]
> > I have the same issue, how did you fix it?
> 
> I also posted this issue in the Jellyfin TV client repository, a dev said it might add this feature someday but it's not a priority. You can read it here: [jellyfin/jellyfin-androidtv#2875](https://github.com/jellyfin/jellyfin-androidtv/issues/2875)
> 
> I'm using a workaround.
> 
> From app's settings, use external player. I recommend MX Player or maybe MPV (but I haven't tried this one, I just know it's reputation on Windows because is lightweight but very powerful.).
> 
> For Android I recommend Findroid client, I believe they are also working on an Android TV version but it's not launched yet.

Thank you. Using external player can fix the case of internal subtitles, but it fails to find the external subtitles.

The underlying ExoPlayer now supports ass/ssa subtitles, and I think libVLC supports it too. I don't know why thei said that...
