### ISSUE TITLE
Books don't works well on my phone

### ISSUE THREAD

**Issue by poireauu** [jellyfin/jellyfin#9967]
Hi everyone,

I don't know why but my books wont show properly, they are show in a weird way like in this video:
https://www.youtube.com/shorts/qtt227yaPrE

**Comment by Bond-009** [comment]
Please fill out the issue template

**Comment by felix920506** [comment]
Closing this as it is not a valid issue report. 

Please head to our [forum or Matrix/Discord channels](https://jellyfin.org/contact) for troubleshooting and general questions.
