### ISSUE TITLE
[Issue]: missing interpolation in the `MaskToCidr` method

### ISSUE THREAD

**Issue by VasilievSerg** [jellyfin/jellyfin#9975]
### Please describe your bug

I've checked project sources with the PVS-Studio analyzer and found missing interpolation character:
```
....
if (!mask.TryWriteBytes(bytes, out var bytesWritten))
{
  Console.WriteLine("Unable to write address bytes, only {bytesWritten} bytes written.");
}
....
```
[Link to the sources](https://github.com/jellyfin/jellyfin/blob/5b711f38d143fc3eca231c745a52fedbe7a10092/Jellyfin.Networking/Extensions/NetworkExtensions.cs#L107).

The `bytesWritten` variable's value won't be written to the string as the `$` character is missed.

### Jellyfin Version

Other

### if other:

the `master` branch

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nielsvanvelzen** [comment]
Well feel free to open a pull request with a fix

**Comment by Shadowghost** [comment]
I integrated the change in #9875
