### ISSUE TITLE
[Issue]: "Replace all metadata" does not replace all metadata database IDs 

### ISSUE THREAD

**Issue by furrnace** [jellyfin/jellyfin#9976]
### Please describe your bug

The function "Replace all metadata" did not replace metadata downloader IDs (External IDs in "Edit metadata") for me in Shows library.

Reproduce:

1) prepare shows folder using TVDB IDs in file names and in tvshows.nfo files containing URLs 
2) example shows are Magnum PI (1980) and Magnum PI (2018) with proper TVDB IDs in filenames and tvshow.nfo files (containing URLs for TVDB Magnum PI (1980) and for Magnum PI (2018), respectively)
3) start with fresh install with stock plugins
4) scan the folder using TMDB: both shows will display as Magnum PI (2018), verify that the external IDs for TMDB and IMDB point to Magnum PI 2018 for both show folders
5) install TVDB plugin, disable TMDB downloader everwhere  in manager library for the Shows folder
6) Scan the Magnum PI 1980 show with "Replace all metadata"
7) verify that external IDs have not been corrected: TVDB ID points to Magnum PI 1980, TMDB ID points to Magnum PI 2018 (should have been deleted as TMDB download is disabled), IMDB ID points to Magnum PI (2018) (and should have been overwritten with gthe ID for Magnum PI (1980))

### Jellyfin Version

10.8.z

### if other:

10.8.10

### Environment

```markdown
- OS: container of LinuxServer.io
- Linux Kernel: irrelevant
- Virtualization: Docker
- Clients: Browser
- Browser: Firefox
- FFmpeg Version: as in LSIO container
- Playback Method: irrelvant
- Hardware Acceleration: none
- GPU Model: none
- Plugins: TMDB, TVDB
- Reverse Proxy: none
- Base URL: empty
- Networking: irrelevant
- Storage: XFS
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mikewesten** [comment]
This has been an issue forever. When replacing fields, the 'Replace all metadata' function seems to only replace one value for another. It never replaces a value for a null value. But it should. Obviously. 
This behavior occurs with all fields, not only just the TMDB, TVDB and IMDB ID fields.
