### ISSUE TITLE
[Feature Request] Use native video framerate for alphasrc filter with ASS subtitles.

### ISSUE THREAD

**Issue by liampwll** [jellyfin/jellyfin#9981]
Currently when a video contains ASS subtitles a framerate of 10fps is used, presumably to save resources, however this works poorly with subtitles are placed on top of existing moving text in a video. Using the framerate of the video instead resolves this issue. I have linked to one location where 10fps is selected below, but their are also two more in that file.

https://github.com/jellyfin/jellyfin/blob/2a02170944ff4dad6a5754dd7e066f114e27fc54/MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs#L4384C26-L4384C26

Addtionally, here is a video showing the framerate set to 10 and the video framerate to demonstrate the problem:

https://www.youtube.com/watch?v=sLga9KKU4Do

**Comment by nyanmisaka** [comment]
This is intentionally used to boost iGPU transcoding performance.

In the future there will be an option that will allow you to use native FPS.

**Comment by liampwll** [comment]
Fixed by #10924
