### ISSUE TITLE
Jellyfin does not save the account settings

### ISSUE THREAD

**Issue by JRModX** [jellyfin/jellyfin#9990]
### Please describe your bug

If I save the settings and log in from another device, I lose all my pre-configured settings.

Jellyfin verson: 10.8.10

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Windows 10
- Linux Kernel: -
- Virtualization: 
- Clients: -
- Browser: Microsoft Edge
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
You'll need to be much more specific to what settings and client(s) you're using.

**Comment by gummykage** [comment]
This is normal behavior. Account settings are device specific. Jellyfin Chrome, Jellyfin Media Player, and Jellyfin iOS is what I use and I have 3 completely different sets of preferences.
