### ISSUE TITLE
[Issue]: Apache2 Proxy

### ISSUE THREAD

**Issue by Fr0zka** [jellyfin/jellyfin#9994]
### Please describe your bug

Hello, i don't think its an issue either a feature to add.. i'd like to know if its possible to only access Jellyfin web interface through Apache2 for example : 

- 01.02.02.04:8096 -> won't work
- mydomain.com -> will work

for now i can freely access it on both (using proxypass) and well.. i just don't like it is all x:

### Jellyfin Version

10.8.z

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cvium** [comment]
If you're using Linux you could probably set something up with iptables, but this is not really the place. You might get more help on [our forums or Matrix channels](https://jellyfin.org/contact), but this is not the proper place.

**Comment by Fr0zka** [comment]
If anyone stumble upon this, the solution using iptables is :

-iptables -I INPUT -p tcp --dport "YOURPORT" -j DROP
(If you have multiple website to block the port so they're not accessible outside of your proxypass juste, add another line like the above, with the right port)

-iptables -I INPUT -p tcp -s 127.0.0.1 -j ACCEPT

-iptables -I INPUT -p tcp -s "YourServerPublicIP" -j ACCEPT
